### ISSUE TITLE
It's not possible to upload files with spaces in path

### ISSUE THREAD

**Issue by aplicacionamedida** [SeleniumHQ/selenium#1000]
I tested. It works in firefox. It's possible to upload a file writing the path character by character to an input type file. Including file paths containing spaces.

But in chrome It doesn't work. At least in Linux. It's not possible to upload a file which path name contains spaces.

**Comment by barancev** [comment]
Please report this issue to the chromedriver tracker:
https://sites.google.com/a/chromium.org/chromedriver/help
