### ISSUE TITLE
Frames are not identified when the browser user interface is not available (tests are run as services)

### ISSUE THREAD

**Issue by mosam14** [SeleniumHQ/selenium#1001]
Scenario : Integrating the selenium maven tests with Jenkins/Teamcity in order to schedule these tests once in a week. The tests are for automating a website which contains many frames and subframes. So in order to identify an element every time i need to switch among frames.

Code snippet :

String Username = s.getCell(0,row).getContents();
String Password = s.getCell(1,row).getContents();
Login(Username,Password);
Thread.sleep(5000);
driver.switchTo().frame(0);

Problem: When the tests are run through command line or eclipse, they pass. Problem occurs when the tests are run through Jenkins/Teamcity. The reason might be that these two tools (Jenkins/Teamcity) do not perform tests on real browsers. Instead the tests are run from backend. Hence, the frames are not identified and exception is thrown. 

Note : Even after putting wait condition before switching to frame exception is thrown.

Expected output : Frames should be identified and switched successfully.

Actual output :

Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Windows\TEMP\scoped_dir2716_17285}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=44.0.2403.157, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 5f43812bb3037e1d67f35126d19bc50d
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.frame(RemoteWebDriver.java:869)
    at testproject.Browser.ExportTestCase(Browser.java:120)
    at testproject.testclass.Login(testclass.java:16)

Results :

Failed tests: 
  testclass.Login:16->Browser.ExportTestCase:120 » NoSuchFrame no such frame
  (...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[ERROR] There are test failures.

Please refer to D:\svn_workspace\TestlinkBackup\target\surefire-reports for the individual test results.
[JENKINS] Recording test results
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.converters.BooleanConverter).
log4j:WARN Please initialize the log4j system properly.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 minutes 22 seconds
[INFO] Finished at: Tue Sep 01 10:43:51 IST 2015
[INFO] Final Memory: 42M/234M
[INFO] ------------------------------------------------------------------------
[JENKINS] Archiving D:\svn_workspace\TestlinkBackup\pom.xml to TestlinkBackup/TestlinkBackup/0.0.1-SNAPSHOT/TestlinkBackup-0.0.1-SNAPSHOT.pom
channel stopped
Finished: UNSTABLE
Please provide solution to this.

**Comment by barancev** [comment]
Please report this issue to the chromedriver tracker:
https://sites.google.com/a/chromium.org/chromedriver/help

Also be aware that running a browser without access to desktop (an interactive session) may cause various issues in the browser itself because it is a GUI program.
