### ISSUE TITLE
[🐛 Bug]: Selenium Grid loading after linking hub to nodes

### ISSUE THREAD

**Issue by haidariaa** [SeleniumHQ/selenium#10016]
### What happened?

After linking the Selenium Grid hub for port `localhost:4444` with Chrome and Firefox browsers, I wanted to check the nodes in the hub with my localhost address but it is just loading and never display the nodes. I tried it with different browsers but they're the same.

### How can we reproduce the issue?

```shell
1. linking the hub with nodes:
docker run -d -P --link selenium-hub:hub selenium/node-chrome-debug
docker run -d -P --link selenium-hub:hub selenium/node-firefox-debug
2. Checking the nodes on Selenium-Grid URL at:
http://mylocalhost:4444
```

### Relevant log output

```shell
NA
```

### Operating System

macOS

### Selenium version

Java 15.0.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.69

### What are the browser driver(s) and version(s) where you see this issue?

selenium-chrome-driver 3.141.59

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment]
@haidariaa, Grid 3 is not supported anymore. To use Grid 4 in Docker, please check https://github.com/seleniumhq/docker-selenium/. The readme has examples that can help you have the Grid running locally.
