### ISSUE TITLE
[🐛 Bug]: FindElements By TagName doesn't work anymore inside Shadow root element

### ISSUE THREAD

**Issue by squilcon** [SeleniumHQ/selenium#10025]
### What happened?

When using version 4.0.0 and up of Selenium, I get this error now when trying to find elements by tag name inside a shadow root element

```
javascript error: b.getElementsByTagName is not a function
  (Session info: chrome=95.0.4638.69)
```

This error isn't there when I use version 3.141.0 and it's only when the find element is with tag name as far as I checked.

I'm using the x64 version of ChromeDriver 95.0.4638.69 and the application is in C# with .Net5.0

To reproduce, simply try it with Chrome download page.

### How can we reproduce the issue?

```shell
[HttpGet("TestShadowRoot")]
        public bool TestShadowRoot()
        {
            try
            {
                var driver = new ChromeDriverNoOptions().GenerateDriver(); //Change this to generate the driver
                driver.Navigate().GoToUrl("chrome://downloads");
                var root = driver.FindElement(By.XPath("/*"));
                var shadowRoot = (IWebElement)((IJavaScriptExecutor)driver).ExecuteScript("return arguments[0].querySelector(arguments[1]).shadowRoot", 
                                                                                          root, 
                                                                                          new string[] { "downloads-manager" });
                var elements = shadowRoot.FindElements(By.TagName("cr-button"));
            }
            catch (Exception ex)
            {
                return false;
            }

            return true;
        }
```

### Relevant log output

```shell
javascript error: b.getElementsByTagName is not a function
  (Session info: chrome=95.0.4638.69)
```

### Operating System

Windows 10

### Selenium version

C# 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95.0.4638.69

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95.0.4638.69

**Comment by AutomatedTester** [comment]
Chrome blocked this when they added shadow dom support which is really unfortunate from them

**Comment by fenchu** [comment]
same as #100019, chromedriver v95.0.4638.17 works.

**Comment by derRichter** [comment]
we can confirm this problem with chromedriver 96, all fine with driver 95.x on newest chrome-browser 96.x
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3958
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3948
we use selenium version 3.141.59, hope there is no force to use selenium 4?

my workaround at the moment is to use or downgrade to version 95.0.4638.69.
works also fine with chromium/chrome browser 96.x

good on this constellation is that we got no (error-)message like
"This version of ChromeDriver only supports Chrome version..." or
"Chrome version must be ..."

hope the next stable of chromium-browser 97 is also compatible to chromedriver 95 or 
the other way round

**Comment by diemol** [comment]
Closing as this is/was an issue in Chrome/ChromeDriiver.
