### ISSUE TITLE
Webdriver remote capabilities for Microsoft Edge (selenium-webdriver 2.47.1)

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#1002]
Hello, 
selenium webdriver capabilities have wrong browser_name for Microsoft edge.(should be similar to ie)
```
Selenium::WebDriver::Remote::Capabilities.edge 
{
    :browser_name       => "MicrosoftEdge",
    :platform           => :windows,
    :javascript_enabled => true
  }
```
The reason is:
 When selenium node is configured  with "browserName": "edge"
  selenium throw error: "Driver info: driver.version: unknown"

When selenium node is configured  with "browserName": "MicrosoftEdge"
desired capabilities cannot find browser_name='edge'

**Comment by lukeis** [comment]
will be fixed in the next release
