### ISSUE TITLE
[🐛 Bug]: Display es-ES instead of es-419 for chrome headless

### ISSUE THREAD

**Issue by sumpler** [SeleniumHQ/selenium#10021]
### What happened?

When I set es_419/es-419 for chrome headless, the chrome shows es-ES. But for chrome debug mode, the language change to es-419 correctly. 
What should I do to change language to es-419 for chrome headless? Could anyone help me?

### How can we reproduce the issue?

```shell
options = Selenium::WebDriver::Chrome::Options.new(args: ['headless', '--lang=es-419'])
@driver = Selenium::WebDriver.for(:chrome, options: options)
```

### Relevant log output

```shell
09:10:31.417 INFO [LocalDistributor.newSession] - Session request received by the distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --verbose, --blink-settings=imagesEnab..., --use-fake-ui-for-media-stream, --use-fake-device-for-media..., --lang=es_419, --enable-automation, --disable-background-timer-..., --disable-renderer-backgrou..., --disable-backgrounding-occ..., --disable-ipc-flooding-prot..., --allow-http-screen-capture, --no-user-gesture-required, --autoplay-policy=no-user-g..., --ignore-autoplay-restrictions, --disable-gpu, --disable-dev-shm-usage, --ignore-certificate-errors, --allow-running-insecure-co..., --disable-web-security]}}]
Starting ChromeDriver 95.0.4638.54 (d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}) on port 16960
```

### Operating System

Windows 10

### Selenium version

4.0.0-rc-1

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 95.0.4638.69 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95.0.4638.54 (d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs

### Are you using Selenium Grid?

4.0.0-rc-1 (revision bc5511cbda)

**Comment by diemol** [comment]
Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
