### ISSUE TITLE
[🐛 Bug]: misleading log message

### ISSUE THREAD

**Issue by SiKing** [SeleniumHQ/selenium#10033]
### What happened?

There is a misleading log message. See steps to reproduce, below.

### How can we reproduce the issue?

I have the following script:

```java
long start = System.currentTimeMillis();
driver.manage().timeouts().scriptTimeout(Duration.ofMillis(10000));
// this will obviously time out!
driver.executeAsyncScript("window.setTimeout(arguments[arguments.length - 1], 20000);");
log.info("Elapsed time: " + (System.currentTimeMillis() - start));
```

### Relevant log output

The above script produces **expected** org.openqa.selenium.ScriptTimeoutException. This is followed by the message:

```shell
Command: [f634c328f5ee0db65e63f424e23f7ef2, executeAsyncScript {script=window.setTimeout(arguments[arguments.length - 1], 20000);, args=[]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 95.0.4638.69, chrome: {chromedriverVersion: 95.0.4638.17 (a9d0719444d4b..., userDataDir: /tmp/.com.google.Chrome.ejxyR3}, goog:chromeOptions: {debuggerAddress: localhost:46805}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:46805/devtoo..., se:cdpVersion: 95.0.4638.69, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

My question (bug) is specifically about the "timeouts: {script: 30000}" part above. I am expecting to see "script: 10000" in my case.

### Operating System

all

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

all?

### What are the browser driver(s) and version(s) where you see this issue?

all?

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
`Capabilities` represents what the user requested from the driver / server to be fulfilled.
Yes, you can update timeout values after the session was created, but you should think of the Capabilities object as a record of the initial negotiation not the current status.

Plus, the recommended practice is to set those values in the capabilities and not change them after the session has started.
