### ISSUE TITLE
[🚀 Feature]: Remove legacy end points in favour of W3C in python bindings

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#10031]
### Feature and motivation

There are a number of dead endpoints in the python code that have been improved through the standards process. We should remove them.

If there is a `W3C_` endpoint like https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py#L284-L285 we should delete the similarly named non-W3C endpoint like https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py#L282-L283

### Usage example

When you've done that please make sure to run the python tests with `bazel test //py:auto-firefox --//common:pin_browsers` and `bazel test //py:auto-chrome --//common:pin_browsers`

**Comment by dosas** [comment]
https://github.com/SeleniumHQ/selenium/pull/10075

**Comment by AutomatedTester** [comment]
landed in #10075
