### ISSUE TITLE
[🐛 Bug]: Selenium v4 - Browsers crash after 300s of idle time, even with a jasmineTimeout = 900s

### ISSUE THREAD

**Issue by pedrofig-td** [SeleniumHQ/selenium#10030]
### What happened?

We have several tests that open multiple browsers, and some of that browsers need be idle for some minutes before any expectation.
When using selenium 3.141.59 this was working just fine, but when using selenium 4.0.0, the browsers close unexpectedly after 300 seconds.
We have a defaultTimeoutInterval = 900 seconds.
It has been hard to understand the root cause of this issue since we have no logs available when the browsers close unexpectedly.

Note: If we perform some action on the browser (breaking the idle time) the test finishes successfully.

### How can we reproduce the issue?

```shell
We can reproduce this by implementing a test that opens a browser session and stays idle for more than 300 seconds, while having a jasmineTimeout higher than that.
```

### Relevant log output

```shell
Unfortunately there is no logs available when the browser automatically close.
```

### Operating System

macOS Big Sur Version 11.6

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 95.0.4638.69

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 95.0.4638.69

### Are you using Selenium Grid?

Yes (not on my machine, just on the pipeline)

**Comment by pujagani** [comment]
Thank you for sharing the details. The Grid has a default value of 300 seconds after which it quits the session which has not had any activity in that time duration. It might help by setting the CLI option `--session-timeout` for the Grid to a longer time period based on the requirement on your end. Please refer for additional cli-options https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#node. Please try it out and let us know if that helps. Thank you!

**Comment by pedrofig-td** [comment]
Thanks for the feedback.

This issue happens when running locally the test on my machine. This test is not yet running on the Grid.
If I set the Jasmine timeout (defaultTimeoutInterval) to a value above the 300 seconds:
- When using selenium v3 (3.141.59) all works as expected. The Jasmine timeout is respected even if a browser is idle during that time.
- When using selenium v4 (4.0.0), the Jasmine timeout is not anymore respected and after the 300 seconds of idle time the browsers automatically close.

It seems that the latest selenium version `session idle timeout` is not respecting the Jasmine timeout.

**Comment by pujagani** [comment]
Thank you for providing the details. Can you please provide a reproducible test project/script that uses jasmine along with some details about how you run the tests (the commands used)? It will help us recreate the problem and fix it. Will really appreciate that. Thank you!

**Comment by pedrofig-td** [comment]
I have created a simple project [webdriverio-example](https://github.com/pedrofig-td/webdriverio-example) using selenium v4 (4.0.0).
This project has a Jasmine timeout of 10m (`defaultTimeoutInterval: 600000`) and a test that opens a simple webpage, waits 350 seconds, and then validate that the browser is still opened by checking it's URL. The test is failing, since the browser terminates after 300s of idle time (not respecting the defined 600s of the Jasmine timeout), and it is not possible anymore to retrieve the browser URL from the session.
Testing the exact same project with selenium v3, it works properly.

Steps to reproduce:
`npm install`
`npm test`

**Comment by harsha509** [comment]
HI @pedrofig-td,

Thanks for raising the issue.

1. I see you're using `wdio/selenium-standalone-service` in the provided example, i.e `WebdriverIO` starts the selenium in standalone mode === standalone grid mode

2. As @pujagani  mentioned above, the grid has a default timeout of 30 seconds in `Selenium3` and `Selenium4`

3. When the WDIO starts the standalone service using Selenium4, the default timeout is set to 300 seconds (as Selenium4 expects a `--session-timeout` to override default timeout ignoring other timeouts mentioned in the config file)

The solution is, you need to pass arguments `--session-timeout` which can be greater or eq to defaultTimeout. Like below

```
  services: [
    [
      "selenium-standalone",
      {
        logPath: "./logs/output/selenium-server-logs",
        args: {
          version: "4.0.0",
          seleniumArgs: ['--session-timeout', 600000],
          drivers: {
            chrome: { version: "96.0.4664.45" },
          },
        },
      },
    ],
  ],
```

**How it worked for Selenium 3**

In Selenium 4 grid, when the session expires, the session is closed properly which closes the browser. Which was not done in Selenium 3 grid.

Hope this helps!

Thanks,
Sri Harsha

**Comment by pedrofig-td** [comment]
Thanks for the detailed answer.

That was part of the solution to my problem.
Beside passing the '--session-timeout' (BTW, the session-timeout value should be specified in seconds), I also had to update the @wdio/selenium-standalone-service dependency since it had an [update](https://github.com/webdriverio/webdriverio/commits/main/packages/wdio-selenium-standalone-service/package.json) recently to [support selenium v4](https://github.com/webdriverio/selenium-standalone/releases).

Thank you very much for you support!
