### ISSUE TITLE
[🚀 Feature]: [python] Set default executable path in service object

### ISSUE THREAD

**Issue by dosas** [SeleniumHQ/selenium#10036]
### Feature and motivation

Right now using the webdriver (for i.e. firefox) is done by:

```
from selenium.webdriver import Firefox
driver = Firefox()
```
This works since the `executable_path` is set to a [default:](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#L47) but this option is deprecated and will be replaced by the [service object](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/service.py).

But the service object does not have a default executable path.

So right now, the following does not work:

```
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.service import Service

driver  = Firefox(service=Service())
TypeError: __init__() missing 1 required positional argument: 'executable_path'
```

I don't known how this will be solved or handled in the future or if I'm missing something here but the [`DEFAULT_EXECUTABLE_PATH`](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#L36) should be defined in the service module for every browser and used as default in the Service object.

I am happy to do a PR

### Usage example

See above.

**Comment by AutomatedTester** [comment]
a PR would be lovely :)

**Comment by dosas** [comment]
https://github.com/SeleniumHQ/selenium/pull/10057

**Comment by dosas** [comment]
Merged
