### ISSUE TITLE
[🚀 Feature]: Remove unused Touch Endpoints in python

### ISSUE THREAD

**Issue by AutomatedTester** [SeleniumHQ/selenium#10032]
### Feature and motivation

There are a number of endpoints to do with touch that are legacy and are not used. The new Actions API support these much better. We need to remove them in https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py#L322-L337 and anywhere using the `Command` class

### Usage example

When you've done that please make sure to run the python tests with bazel test //py:auto-firefox --//common:pin_browsers and bazel test //py:auto-chrome --//common:pin_browsers

**Comment by dosas** [comment]
I would like to tackle that but I get 15 failing tests for firefox and 45 for chrome on trunk :(

**Comment by AutomatedTester** [comment]
> I would like to tackle that but I get 15 failing tests for firefox and 45 for chrome on trunk :(

What OS are you on? I'm not getting that

**Comment by dosas** [comment]
I'm on Debian 10, I just rebased and I get the same:
```
//py:auto-firefox-test/selenium/webdriver/common/alerts_tests.py         FAILED in 40.1s
//py:auto-firefox-test/selenium/webdriver/common/api_example_tests.py    FAILED in 19.5s
//py:auto-firefox-test/selenium/webdriver/common/click_scrolling_tests.py FAILED in 23.8s
//py:auto-firefox-test/selenium/webdriver/common/driver_element_finding_tests.py FAILED in 38.0s
//py:auto-firefox-test/selenium/webdriver/common/executing_async_javascript_tests.py FAILED in 49.7s
//py:auto-firefox-test/selenium/webdriver/common/frame_switching_tests.py FAILED in 42.1s
//py:auto-firefox-test/selenium/webdriver/common/interactions_tests.py   FAILED in 24.5s
//py:auto-firefox-test/selenium/webdriver/common/quit_tests.py           FAILED in 7.0s
//py:auto-firefox-test/selenium/webdriver/common/select_class_tests.py   FAILED in 53.6s
//py:auto-firefox-test/selenium/webdriver/common/upload_tests.py         FAILED in 17.5s
//py:auto-firefox-test/selenium/webdriver/common/visibility_tests.py     FAILED in 24.0s
//py:auto-firefox-test/selenium/webdriver/common/webdriverwait_tests.py  FAILED in 87.1s
//py:auto-firefox-test/selenium/webdriver/common/window_switching_tests.py FAILED in 23.0s
//py:auto-firefox-test/selenium/webdriver/common/window_tests.py         FAILED in 13.9s
```
Most of the error logs read:
```
...
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

py/selenium/webdriver/remote/errorhandler.py:247: WebDriverException
```

**Comment by AutomatedTester** [comment]
Looks like Firefox on debian is having issues. Please make sure that you have Firefox installed instead and with geckodriver on the path and use `bazel test //py:test-firefox`

**Comment by dosas** [comment]
@AutomatedTester I have a few questions left:
1. Are you sure the lines from above are correct? Shouldn't it be https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py#L328-L343 (Since it says related to touch)?
2. There is mention of the Action API, do you have a reference to this API?
3. How for example would this command be replaced:  https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/touch_actions.py#L57 or is this already the new actions API?

**Comment by titusfortner** [comment]
Sorry to step on toes @dosas I'm trying to close as many open issues as I can before the end of the year. Come chat with us on Selenium Slack if you'd like to collaborate on these.

816ad6ebb5353431c37f160b2b9b0056b6efdb4e
