### ISSUE TITLE
[🐛 Bug]: Selenium pauses execution of code when using Remote DevTools

### ISSUE THREAD

**Issue by KasimAhmic** [SeleniumHQ/selenium#10038]
### What happened?

I'm launching an instance of ChromeDriver with the remote debugging port option set and I can access the remote dev tools just fine however whenever I do, the script just pauses execution and sits there on the page. There are no errors in the console or in the browser and there are no indicators that anything has gone wrong. One oddity I noticed was that if I repeatedly scroll up and down on the page, the script will continue so long as I continue scrolling.

This issue has already been reported here (#9759) but lacked details so I figured I'd open a new issue. I'm not really sure what to make of all this or even where I should post this issue so I'm just starting here. I'll be happy to file an issue elsewhere if someone can point me in the right direction.

**Steps to reproduce:**

1. Run the example script below
2. Go to http://localhost:9000
3. Click on the `React Image Gallery` link
4. Wait a bit and you should not see the script doing anything
5. Rapidly scroll up and down and the script should continue execution
6. Stop scrolling and the script should pause

**EDIT:**
You may not have to _continuously_ scroll. I was just able to get the script going again scrolling once in between action. It seems that all it needs is the remote debugger to send it a command/action? Not sure.

### How can we reproduce the issue?

```shell
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import DesiredCapabilities
from selenium.webdriver.common.by import By
from selenium import webdriver
from time import sleep


def start_driver():
    chrome_options = Options()
    chrome_options.add_argument("--remote-debugging-port=9000")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument('--disable-dev-shm-usage')
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--disable-translate")
    chrome_options.add_argument("--disable-extensions")
    chrome_options.add_argument("--disable-background-networking")
    chrome_options.add_argument("--safebrowsing-disable-auto-update")
    chrome_options.add_argument("--disable-sync")
    chrome_options.add_argument("--metrics-recording-only")
    chrome_options.add_argument("--disable-default-apps")
    chrome_options.add_argument("--no-first-run")
    chrome_options.add_argument("--disable-setuid-sandbox")
    chrome_options.add_argument("--hide-scrollbars")
    chrome_options.add_argument("--no-zygote")
    chrome_options.add_argument("--autoplay-policy=no-user-gesture-required")
    chrome_options.add_argument("--disable-notifications")
    chrome_options.add_argument("--disable-logging")
    chrome_options.add_argument("--disable-permissions-api")
    chrome_options.add_argument("--ignore-certificate-errors")
    chrome_options.add_argument("--window-size=1280,720")
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])

    chrome_options.page_load_strategy = "eager"

    capabilities = DesiredCapabilities.CHROME

    return webdriver.Chrome(
        executable_path="SOME_PATH_TO_CHROME",
        options=chrome_options,
        desired_capabilities=capabilities
    )


driver = start_driver()

for _ in range(50):
    driver.get("https://www.linxtion.com/demo/react-image-gallery/")

    sleep(5)

    right_nav = driver.find_element(By.CLASS_NAME, "image-gallery-right-nav")

    for _ in range(5):
        right_nav.click()

        sleep(2)
```

### Relevant log output

```shell
There is none. As far as Selenium is concerned, everything is still operating nominally.
```

### Operating System

Windows 10

### Selenium version

Python 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95.0.4638

### Are you using Selenium Grid?

No

**Comment by pcorliss** [comment]
I ran into this issue as well. Options listed below aren't necessary to reproduce the issue. Latest selenium-webdriver and ruby used to reproduce. Selenium v3 has the same issue. I suspect this may be a chromedriver issue or selenium-chromedriver interaction issue.

Steps to reproduce:
1. `ruby selenium.rb`
2. Connect remote debugger by navigating to `http://localhost:9222` or using `chrome://inspect`
3. exit pry debugger
4. Execution continues but blocks after click occurs

If you run the following without connecting to the remote debugger it executes without issue.

```ruby
require 'pry'
require 'selenium-webdriver'

# driver = Selenium::WebDriver.for :chrome

options = Selenium::WebDriver::Chrome::Options.new
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--remote-debugging-port=9222') # debug
options.add_argument('--ignore-certificate-errors')
options.add_argument('--disable-popup-blocking')
options.add_argument('--disable-translate')
driver = Selenium::WebDriver.for(:chrome, options: options)

driver.get 'https://google.com'

puts "Pausing in debugger. Navigate to localhost:9222 and open debugger."
binding.pry

search_box = driver.find_element(name: 'q')
search_button = driver.find_element(name: 'btnK')
sleep 2
search_box.send_keys 'Selenium'
sleep 1
puts "Clicking Button"
search_button.click # Execution pauses and eventually times out here when remote debugger is open
puts "Done Clicking"

binding.pry

sel_attr = driver.find_element(name: 'q').attribute('value') # => "Selenium"
puts "Selenium Attr Found: #{sel_attr}"

puts "Done"
```

**Comment by titusfortner** [comment]
I don't understand the reproduction case for this. Why am I manually going to a site in the middle of automation? How is what is happening an issue with Selenium code if it requires manual intervention?

When I navigate to that page, I'm getting:
> This page is deprecated and will be removed

What is it that you are trying to do?

**Comment by pcorliss** [comment]
I'm trying to open the chrome remote debugger for a headless chrome instance. This is useful for connecting to already running selenium runs or on systems that don't have a desktop interface. Navigating to `localhost:9222` presents a link to open the chrome remote debugger which attaches to the running chrome instance.

You can also do the following to achieve the same thing and avoid the deprecation warning.
1. Navigate to `chrome://inspect`
2. Click `Configure`
3. Add `localhost:9222`
4. Wait or refresh the page until the view notices the available debugger
5. Click inspect

Once connected and you allow the code to continue you can watch selenium continue operating but it will execute the click operation but hang waiting for something even though the page has loaded successfully.

**Comment by titusfortner** [comment]
Yeah, there's nothing for Selenium to change. Selenium is sending the correct commands to the driver. If the correct thing isn't happening in a given configuration, it's because the driver isn't handling it.

**Comment by KasimAhmic** [comment]
> Yeah, there's nothing for Selenium to change. Selenium is sending the correct commands to the driver. If the correct thing isn't happening in a given configuration, it's because the driver isn't handling it.

Understood. For anyone else who comes across this issue, I've opened a ticket with the ChromeDriver team here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3986
