### ISSUE TITLE
Microsoft Edge missing icon in selenium grid console

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#1004]
![screenshot from 2015-09-04 09 05 55](https://cloud.githubusercontent.com/assets/5420655/9684247/468b236a-52e4-11e5-8a2e-071e25dfc081.png)

**Comment by ddavison** [comment]
fixed in 5c4049245c5b859ca0c57e87c6aec2a89be6f143

**Comment by vveliev** [comment]
:thumbsup:
