### ISSUE TITLE
[🐛 Bug]: Cannot use Selenium 4 BiDi to listen to console.log - Stuck on monitor.StartEventMonitoring()

### ISSUE THREAD

**Issue by fractalocity** [SeleniumHQ/selenium#10048]
### What happened?

I cannot get past the monitor.StartEventMonitoring() in the below code:

======================================

`<Some misc Selenium code here>`
`IJavaScriptEngine monitor = new JavaScriptEngine(driver);`
`List<string> consoleMessages = new List<string>();`
`monitor.JavaScriptConsoleApiCalled += (sender, e) =>`
`{`
`    consoleMessages.Add(e.MessageContent);`
`};`
`await monitor.StartEventMonitoring();`

`<Existing code>`
`someButton.Click(); // <== I can never get to this line of code. I'm stuck on the await line.`
`int messageCount = consoleMessages.Count; `

======================================

The above code came from the following Selenium Docs link:[ Selenium Docs BiDi](https://www.selenium.dev/documentation/webdriver/bidi_apis/#listen-to-consolelog-events)

The problem is that I cannot get past the 'await monitor.StartEventMonitoring()' line of code. I thought I would 'startMonitoring' ... then this monitoring task would run in the background, and the 'someButton.Click()' would then execute. But the code is waiting for 'await monitor.StartEventMonitoring()' line to complete before going onto the next line of code. I thought the monitor would run in the background and I could then check the consoleMessages List every so often to see if any messages had been added to the list. I removed the 'await' which is in front of the monitor.StartEventMonitoring(); but even if I do this the execution of the code will not get past monitor.StartEventMonitoring();

### How can we reproduce the issue?

```shell
Try using the code example from selenium docs (see link in the 'what happened' section).
```

### Relevant log output

```shell
none
```

### Operating System

Windows 10

### Selenium version

C# Selenium 4.0.0-rc1

### What are the browser(s) and version(s) where you see this issue?

Chrome 95

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 95 driver

### Are you using Selenium Grid?

no

**Comment by jimevans** [comment]
@fractalocity I am utterly unable to reproduce your scenario. Is there some other code that may be causing it? Without seeing what else is happening in the system, it's impossible to diagnose the issue.
