### ISSUE TITLE
[🐛 Bug]: Unable to start Firefox 94 with custome profile

### ISSUE THREAD

**Issue by scruel** [SeleniumHQ/selenium#10041]
### What happened?

Selenium not able to pass the profile variable to geckodriver, it was still using the temp profile when started.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile

profile_path = r"C:\Users\scruel\AppData\Roaming\Mozilla\Firefox\Profiles\test.default-release"
options=Options()
options.log.level = "trace"
options.set_preference('profile', profile_path)
browser = webdriver.Firefox(options=options)
```

### Relevant log output

```shell
1636940642906	geckodriver	INFO	Listening on 127.0.0.1:5149
1636940645941	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "5150" "-no-remote" "-profile" "C:\\Users\\scruel\\AppData\\Local\\Temp\\rust_mozprofileayfj0h"
1636940645947	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:5155
1636940646209	RemoteAgent	DEBUG	CDP enabled
1636940646209	Marionette	INFO	Marionette enabled
1636940646262	Marionette	TRACE	Received observer notification toplevel-window-ready
```

### Operating System

Windows 10 Pro

### Selenium version

Selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 94

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 30.0.0

**Comment by titusfortner** [comment]
Essentially `profile` is not a valid `preference` so it makes sense that setting it won't do anything. The `Options` class has a `profile` setter, but it has been deprecated, see comment here: https://github.com/SeleniumHQ/selenium/issues/9997#issuecomment-960761423
