### ISSUE TITLE
[🐛 Bug]: IEDriverServer 4.0.0 doesn't work with native events disabled

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#10043]
### What happened?

The last version of IEDriver that worked fine with native events disabled was 3.150.1.

### How can we reproduce the issue?

```shell
InternetExplorerOptions ieOptions = new InternetExplorerOptions();
ieOptions.disableNativeEvents(); // IMPORTANT
WebDriver driver = new InternetExplorerDriver(ieOptions);
driver.get("http://www.google.com");
new WebDriverWait(driver, Duration.ofMillis(10000), Duration.ofMillis(100)).until(
	ExpectedConditions.visibilityOfElementLocated(By.name("q")));
WebElement searchField = driver.findElement(By.name("q"));
searchField.sendKeys("test");
searchField.submit();
new WebDriverWait(driver, Duration.ofMillis(10000), Duration.ofMillis(100)).until(
	ExpectedConditions.titleContains("test"));
driver.quit();
```

### Relevant log output

```shell
Started InternetExplorerDriver server (32-bit)
4.0.0.0
Listening on port 56213
Only local connections are allowed
Nov 15, 2021 12:27:55 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "main" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for title to contain "test". Current title: "Google" (tried for 10 second(s) with 100 milliseconds interval)
Build info: version: '4.0.0', revision: '3a21814679'
System info: host: '...', ip: '...', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.edgechromium: false, ie.edgepath: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:56213/, nativeEvents: false, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 80ecfb08-dd39-4fe3-b1d8-cbdcba770191
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:138)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at Test.main(Test.java:24)
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

IE 11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.0.0

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
So, `submit()` is not really recommended any more. Does this work if you click the Google Search button instead?

**Comment by JohnA2** [comment]
In this case even `sendKeys()` has no effect because I don't see anything typed in the field.

**Comment by diemol** [comment]
What happens if you use the IE Mode in Edge?

**Comment by JohnA2** [comment]
> What happens if you use the IE Mode in Edge?

I'm not really interested in that combination, so I've never tried it.

**Comment by titusfortner** [comment]
I'm not sure how native events makes a difference here.
The submit button is now implemented with JavaScript.

**Comment by diemol** [comment]
@JohnA2 this is why I suggested it
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp

IE won't be supported anymore soon.

**Comment by titusfortner** [comment]
Ok, I was right. Submit method is one of the places that IE does not use Native events. 
Perhaps Selenium 3 was using the endpoint, and in Selenium 4 it only uses the JS execution?

> there are some scenarios when submitting an HTML form via WebElement’s submit() method may have the same effect. This can happen if the driver calls the JavaScript submit() function on the form, and there is an onSubmit event handler that calls the JavaScript alert(), confirm(), or prompt() functions

https://www.selenium.dev/documentation/ie_driver_server/#clicking-option-elements-or-submitting-forms-and-alert

Bug is filed here:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3508

The workaround is to click the submit button so that it doesn't use JS

**Comment by JohnA2** [comment]
> @JohnA2 this is why I suggested it https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp
> 
> IE won't be supported anymore soon.

IE won't be supported in the latest build of Windows 10 soon, but it will still be supported in older OS for some time. Please check "Which platforms will be affected" [here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549).

> Ok, I was right. Submit method is one of the places that IE does not use Native events. Perhaps Selenium 3 was using the endpoint, and in Selenium 4 it only uses the JS execution?
> 
> > there are some scenarios when submitting an HTML form via WebElement’s submit() method may have the same effect. This can happen if the driver calls the JavaScript submit() function on the form, and there is an onSubmit event handler that calls the JavaScript alert(), confirm(), or prompt() functions
> 
> https://www.selenium.dev/documentation/ie_driver_server/#clicking-option-elements-or-submitting-forms-and-alert
> 
> Bug is filed here: [SeleniumHQ/selenium-google-code-issue-archive#3508](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3508)
> 
> The workaround is to click the submit button so that it doesn't use JS

IE uses native events by default and uses JS execution if I specify `ieOptions.disableNativeEvents();`, like in my code above. The reasons why one or the other might be better are described in
http://jimevansmusic.blogspot.com/2012/06/whats-wrong-with-internet-explorer.html
http://jimevansmusic.blogspot.com/2013/01/revisiting-native-events-in-ie-driver.html

I currently use Selenium 4 with IEDriver 3.150.1.1. Everything works fine with that combination, so it's not a Selenium 3 vs 4 thing. This bug only occurs if I update IEDriver to 4.0.0.0.

I understand that IE is a dying browser one way or another, and therefore investigating and fixing IEDriver might be not worth it. I can just keep using the old driver until IE goes away completely.
