### ISSUE TITLE
[🐛 Bug]: uploadFile not working with docker images exposing chromedriver directly

### ISSUE THREAD

**Issue by tyge68** [SeleniumHQ/selenium#10045]
### What happened?

While trying to switch to latest selenium api 4.0, we hit the issue with the uploadFile.
Generally if we use selenium chrome standalone docker image there are no issues, as that one uses selenium server internally.

But if you use other distributions (like selenoide/vnc:chrome_95.0) which allow to easily do video recording of the tests, the uploadFile will fails as it doesn't know the command with .../se/file since that is not implemented in the chromedriver out of the box, instead it should use .../file which is implemented.

As both should be possible, I suppose we need a fallback mechanism to allow this to work, or eventually a mechanism to detect or turn it one based on environment variable / system properties.

### How can we reproduce the issue?

```shell
- Assuming it's a java based project
- Assuming it enable LocalFileDetector in your driver with following: ((RemoteWebDriver) driver).setFileDetector(new LocalFileDetector());
- Assuming the page have a input of type "file"
- On your selenium element, sendKeys(...) with corresponding filepath in the input element of type "file"

observe the error in the logs (see below)

This is due to the current code (1) which force to use .../se/file for UPLOAD_FILE operation, while chromedriver implement it at .../file already.
(1) https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java#L161
```

### Relevant log output

```shell
INFO: Detected dialect: W3C

org.openqa.selenium.UnsupportedCommandException: unknown command: unknown command: session/c6d981124b6ec773f82df7c6eb73da7d/se/file
```

### Operating System

Linux, Mac

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 95, Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

95.0.4638.69, 96.0.4664.35

**Comment by AutomatedTester** [comment]
The problem here is that you're using `RemoteWebDriver` which then assumes that there is a Selenium grid, potentially on a different machine, that it is connecting to. Once we make that assumption we use it for deciding when to upload files or not and how to do it. If it is in a docker container you can always upload the file as part of the step of building the container or you can add a selenium server that you connect. 

This is why Selenium docker containers have the server on them.

**Comment by AutomatedTester** [comment]
If chrome driver is allowing connections from outside a container that is them not following https://w3c.github.io/webdriver/#security which could be seen as a security vulnerability
