### ISSUE TITLE
[🚀 Feature]: Documentation about Actions API in WebDriver W3C Protocol to do things like zoom in

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#10049]
### Feature and motivation

I noticed on this link: https://www.lambdatest.com/blog/selenium4-w3c-webdriver-protocol/ that it was said that it is possible to use the Actions API in WebDriver W3C Protocol to do things like perform multi-touch actions, zoom-in, zoom-out, pressing two keys simultaneously, and more. I am unable to find documentation about how to do these things.

### Usage example

I am working on using the Actions API in WebDriver to zoom in a page.

**Comment by titusfortner** [comment]
Moving this to our docs repo: https://github.com/SeleniumHQ/seleniumhq.github.io/issues/906
