### ISSUE TITLE
[🐛 Bug]: NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute

### ISSUE THREAD

**Issue by RedDevil91** [SeleniumHQ/selenium#10051]
### What happened?

Tried to use the `Select` class (`org.openqa.selenium.support.ui.Select`) as before but this feature doesn't work anymore.

### How can we reproduce the issue?

```shell
Select groupBy = new Select(groupByButton());

//the definition of groupByButton
public WebElement groupByButton();
```

### Relevant log output

```shell
org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String;
java.lang.NoSuchMethodError: org.openqa.selenium.WebElement.getDomAttribute(Ljava/lang/String;)Ljava/lang/String;
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
```

### Operating System

Win 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver v96.0.4664.45

**Comment by titusfortner** [comment]
I've seen this issue before and it is a dependency version conflict. Please double check that everything related to Selenium is set to 4.x and that nothing that requires Selenium 3 (e.g., Appium 7) is included in your dependencies.

**Comment by RedDevil91** [comment]
That can be a problem, I will check it and give a feedback tomorrow morning!

**Comment by asolntsev** [comment]
@RedDevil91 Did the tomorrow morning come in the end? :)

@titusfortner Pretty sure, it's an issue with dependency versions, I believe the issue can be closed.

**Comment by RedDevil91** [comment]
Sorry for the delay but I had other things to do before release. I removed every dependency which needed the old Selenium version and the issue is still the same. I checked the implementation and the [constructor of the `Select`](https://github.com/SeleniumHQ/selenium/blob/e6dc722b183455ed006a93558cbbb0c949619a00/java/src/org/openqa/selenium/support/ui/Select.java#L54) uses the `getDomAttribute` on a `WebElement`. However the `WebElement` doesn't [support ](https://github.com/SeleniumHQ/selenium/blob/e6dc722b183455ed006a93558cbbb0c949619a00/java/src/org/openqa/selenium/WebElement.java#L131) this method. Is this intentional? @asolntsev @titusfortner

**Comment by diemol** [comment]
Do you have Appium bindings in the same project? If so, that is causing the issue. You might try the version 8 beta for the Appium Java bindings.

**Comment by asolntsev** [comment]
@RedDevil91 Yes, it's intentional. All implementations of `WebElement` do override method `getDomAttribute()`. It never throws `UnsupportedOperationException` in real life. 

Please execute `mvn dependency:tree` or `gradle dependencies`, and you will see the problem. As described in [this example](https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/).
