### ISSUE TITLE
[🐛 Bug]: Trace selenium webDriver within Docker does not appear ?

### ISSUE THREAD

**Issue by simonprovost** [SeleniumHQ/selenium#10055]
### What happened?

We are using a Firefox-based selenium webDriver for testing purposes. Using a dockerized approach, we are also using a standalone Firefox selenium image _(see Docker-compose)_. We have a crash that refers to `Failed to decode response from marionette`, such issue has already been solved a lot in this repository issues section. However, we did not find a way to fix it and we would like to export the selenium webDriver trace to see if we can better understand what is going on or if we should create a new issue following logs, so we would appreciate any help you can provide. Following the snippet that follows, how can we track the log in the docker, as it does not display elsewhere at the moment:

```python

 firefox_profile = webdriver.FirefoxProfile(fp_path) #fp_path is not  relevant to be added here it is our firefox profile path
 options = webdriver.FirefoxOptions()

 options.browser_version = '92'
 options.platform_name = 'Windows 10'
 options.page_load_strategy = 'eager'
 options.log.level = "TRACE"

 driver = webdriver.Remote(command_executor="http://selenium:4444/wd/hub",
                           desired_capabilities=DesiredCapabilities.FIREFOX,
                           browser_profile=firefox_profile,
                           options=options)
```

So, here's our docker-compose file (Note: we use the shm_size as recommended a lot in many issues's threads):

```shell
version: "3"
services:
  selenium:
    image: selenium/standalone-firefox:4.0.0-rc-3-20211010
    ports:
      - 4444:4444
      - 7900:7900
    mem_limit: 2500m
    mem_reservation: 2500m
    shm_size: 2gb

  our_solution:
    container_name: our_solution_container_name
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./api:/app/api
    command: sleep 5000
    depends_on:
      - selenium
    ports:
      - 8050:8050
    shm_size: '4gb'
    mem_limit: 2500m
    mem_reservation: 2500m
```

### How can we reproduce the issue?

```shell
Using:

- Docker version 20.10.8, build 3967b7d
- selenium/standalone-firefox:4.0.0-rc-3-20211010
- Python 3.7

To run this snippet, create a docker-compose using the selenium standalone-firefox image (as seen above) as its first service and a simple Python solution as its second. Build and configure the docker-compose in order to run the python solution from a command line interpreter. There is no traceback file for any crashes or any actions that were outputted.
```

### Relevant log output

```shell
//Trying to get some.
```

### Operating System

MacOS Monterey

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 92

### What are the browser driver(s) and version(s) where you see this issue?

Selenium WebDriver / Marionette ?

**Comment by diemol** [comment]
It is not really clear what the issue is, and it most likely looks like a question on how to setup this.

Based on the capabilties you are sending
```
 options.browser_version = '92'
 options.platform_name = 'Windows 10'
 options.page_load_strategy = 'eager'
 options.log.level = "TRACE"
```

Means that you are requesting a Firefox 92 on Windows, when the Docker image released on https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-3-20211010, has Firefox 93 and all these containers run on Linux.

For more questions, please use the links posted above.
