### ISSUE TITLE
[🐛 Bug]: RemoteWebDriverBuilder does not respect config with local driver

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10064]
### What happened?

When using `RemoteWebDriverBuilder.config()` to set a `ClientConfig` instance that does not contain a `baseUri` and does not set an address with `address()` method, the `build()` method will get a non null return from `this.getLocalDriver()`, but that method does not create a driver using the provided `ClientConfig` values.

I don't actually see a way to set a `ClientConfig` for local driver sessions, which, if that's the case, is a bigger issue to address. For this I think we should at least throw an exception that the config instance provided can not be respected if we get a local driver result.

### How can we reproduce the issue?

```shell
FirefoxOptions browserOptions = new FirefoxOptions();
        ClientConfig config = ClientConfig.defaultConfig()
                .connectionTimeout(Duration.ofMinutes(5))
                .readTimeout(Duration.ofMinutes(4));

        WebDriver driver = RemoteWebDriver.builder()
                .oneOf(browserOptions)
                .config(config)
                .build();
```

### Relevant log output

```shell
n/a
```

### Operating System

n/a

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
I was having a look and this is not a simple change. Right now, there is no simple way to pass a `ClientConfig` to a local driver. We would need to start opening the different drivers so they can receive that configuration or hopefully find a smarter way to do this.
