### ISSUE TITLE
[🐛 Bug]: Unable to Create Grid Node

### ISSUE THREAD

**Issue by Metonya** [SeleniumHQ/selenium#10073]
### What happened?

Hello,
I'm trying to get the grid up and running with Selenium 4.0. I get an error when I try to connect the Node after I stand up the hub.
I don't have this problem when I start it as standalone.
https://gist.github.com/Metonya/506fd064b6f724a1f47144c01cfad986

### How can we reproduce the issue?

```shell
java -jar selenium-server-4.0.0.jar hub
java -jar selenium-server-4.0.0.jar node --detect-drivers true
```

### Relevant log output

```shell
Node;
INFO [NodeServer$1.lambda$start$1] - Sending registration event...

Hub;
Caused by: org.openqa.selenium.json.JsonException: Unable to create instance of class org.openqa.selenium.grid.data.NodeStatus
...
Caused by: java.lang.IllegalArgumentException: Slot ID must be set
        at org.openqa.selenium.internal.Require.nonNull(Require.java:56)
        at org.openqa.selenium.grid.data.Slot.<init>(Slot.java:38)
        at org.openqa.selenium.grid.data.Slot.fromJson(Slot.java:116)
        ... 40 more

Status;
6:27
{
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
    ]
  }
}
```

### Operating System

Windows 10

### Selenium version

Java Selenium 4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

96.0.4664.45 

### Are you using Selenium Grid?

4.0.0

**Comment by lopukhDA** [comment]
Hello. Do you have Selenium hub and Selenium node on the same machine?
What you see from these URLs: http://localhost:4444/ui/index.html#/ and http://localhost:4444/status/

**Comment by diemol** [comment]
From a conversation in Slack:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/5992658/144262634-2148609b-d349-494b-b8cc-c4d16013451a.png">
![image](https://user-images.githubusercontent.com/5992658/144262653-249faa05-1f43-4705-98cf-b14e48f373a5.png)

Seems we have issues encoding the payload.

**Comment by diemol** [comment]
Thanks for reporting this and coming to our Slack channel to share more details. This has been fixed and we will release a version with this in the next few days.
