### ISSUE TITLE
[🐛 Bug]: InvalidArgumentError on Firefox Remote Capabilities

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [SeleniumHQ/selenium#10076]
### What happened?

When starting up a new/default Firefox profile with remote capabilities I see the below error

```Bash
Selenium::WebDriver::Error::InvalidArgumentError: Invalid moz:firefoxOptions field capabilities
from C:/<path_to_installed_ruby>/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
```
I was not able to fetch more detail error logs. Let me know how to do that it could help debug error.

BTW If I skip the capabilities part ,`capabilities: Selenium::WebDriver::Remote::Capabilities.firefox(accept_insecure_certs: true)` Firefox opens up as expected and my test pass.

### How can we reproduce the issue?

```shell
Watir::Browser.start('https://www.google.com/maps',
                         :firefox,
                         options: { profile:      Selenium::WebDriver::Firefox::Profile.new,
                                    capabilities: Selenium::WebDriver::Remote::Capabilities
                                                    .firefox(accept_insecure_certs: true)
                         }
    )
```

### Relevant log output

```shell
Selenium::WebDriver::Error::InvalidArgumentError: Invalid moz:firefoxOptions field capabilities
from C:/<path_to_installed_ruby>/ruby/gems/2.6.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok'
```

### Operating System

Windows 10
### Watir version

Watir 7.1.0

### Selenium version

Selenium-webdriver 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 94.0.2

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment]
You're putting `profile` in the wrong spot.

This works:
```ruby
browser = Watir::Browser.new(:firefox,
                             accept_insecure_certs: true, 
                             profile: Selenium::WebDriver::Firefox::Profile.new)
```

A few other notes, you should avoid using `Firefox::Profile`, if you have specific preferences or arguments to set, you should use them directly:

```ruby
browser = Watir::Browser.new(:firefox,
                             accept_insecure_certs: true, 
                             options: {prefs: {foo: 'bar'}, args: ['foo', 'bar']})
```

Of note, Watir 7 is set up so that you don't need to use Selenium classes directly.

Watir converts the `:options` value from a `Hash` into the correct Selenium browser `Options` class. You can see what keywords are valid for Firefox here: https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/firefox/options.rb#L28-L41
