### ISSUE TITLE
[🐛 Bug]: selenium 4.0: find_element returning dictionary instead of WebElement (Win App Driver)

### ISSUE THREAD

**Issue by CandyLuWang** [SeleniumHQ/selenium#10079]
### What happened?

Tested with Win App Driver 1.2.99 and Appium-Python-Client 2.0.0.
Code: driver.find_element(By.XPATH, <xpath expression>)
Return: {'ELEMENT': '42.1312384.4.2'}
![image](https://user-images.githubusercontent.com/18415164/143203722-6cc03cfd-0f72-45a2-a411-b6cafaa8e598.png)

### How can we reproduce the issue?

```shell
Code: driver.find_element(By.XPATH, <xpath expression>)
Return: {'ELEMENT': '42.1312384.4.2'}
```

### Relevant log output

```shell
self = <util.win_settings.Win10Settings object at 0x00000249E5A278B0>
session = <appium.webdriver.webdriver.WebDriver (session="C3CA67AF-4207-48C4-A90E-0A345049DC16")>

    def go_to_display_settings_page(self, session):
        jjj = session.find_element(By.XPATH, "//Window[@Name='Settings'][@AutomationId='TitleBar']/Button[@Name='Maximize Settings'][@AutomationId='Maximize']")
>       jjj.click()
E       AttributeError: 'dict' object has no attribute 'click'
```

### Operating System

OS: Win10 (Version: 21H1, Build: 19043.1348)

### Selenium version

Selenium 4.0.0

### What are the browser(s) and version(s) where you see this issue?

No Browser

### What are the browser driver(s) and version(s) where you see this issue?

Win App Driver 1.2.99

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
Please downgrade to Selenium 3.14 and raise an issue with the https://github.com/microsoft/WinAppDriver project so they can follow the [W3C element identifier](https://w3c.github.io/webdriver/#dfn-web-element-identifier). The python bindings are going to be following more W3C spec items closer moving forward which will create other long term problems if the WinAppDriver team don't follow suit.
