### ISSUE TITLE
[🐛 Bug]: Cannot find "locateWith" in JavaScript environment

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#10070]
### What happened?

Cannot find "locatewith" in JavaScript environment.

I noticed a code in `selenium-webdriver/index.js` that
```javascript
exports.withLocator = by.withLocator
```
Should "withLocator " be changed to "locateWith"?

### How can we reproduce the issue?

```shell
const { locateWith } = require('selenium-webdriver');
console.log(locateWith);
```

### Relevant log output

```shell
undefined
```

### Operating System

win10

### Selenium version

javascript 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.45

**Comment by harsha509** [comment]
Hi @ULQUIARROSYX,

Thank you for raising the issue!

it should be `locateWith` and this is fixed with commit https://github.com/SeleniumHQ/selenium/commit/5380516e656695cffaa892113042c0aca01ad030 and will be available in selenium-webdriver@4.1.0.

Thanks,
SriHarsha
