### ISSUE TITLE
Brave browser closes instantly when opened from __init__ method in Python

### ISSUE THREAD

**Issue by Elias-Poor** [SeleniumHQ/selenium#10082]
### What happened?

When opening Brave browser from __init__ method, the browser will open and then instantly close. Paths to browser executable and chrome driver are both correct, provided code snippet works as expected when taken out of the class.

### How can we reproduce the issue?

```shell
---------Works as expected---------

from selenium import webdriver
from selenium.webdriver.chrome.service import Service

driver_path = Service('C:/chromedriver.exe')
op = webdriver.ChromeOptions()
op.binary_location = 'C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe'
browser = webdriver.Chrome(service=driver_path, options=op)

---------Does not work as expected---------

from selenium import webdriver
from selenium.webdriver.chrome.service import Service


class Main:
    def __init__(self):
        driver_path = Service('C:/chromedriver.exe')
        op = webdriver.ChromeOptions()
        op.binary_location = 'C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe'
        self.browser = webdriver.Chrome(service=driver_path, options=op)


if __name__ == '__main__':
    Main()
```

### Relevant log output

```shell
Process finished with exit code 0
```

### Operating System

Windows 10

### Selenium version

Python 3.8, Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Brave V1.32.106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.20

**Comment by diemol** [comment]
This normally happens when there is no compatibility between the browser version and the ChromeDriver version. As we don't support Brave by default, this is rather a question, therefore I will close this and provide links where you can reach our chat and other channels to continue the conversation.
