### ISSUE TITLE
[🐛 Bug]: (dotnet) Selenium can't handle with default field value

### ISSUE THREAD

**Issue by refaeli-io** [SeleniumHQ/selenium#10089]
### What happened?

I trigged the bug using filter textbox - elemnt on  the web.
In our company, we developer the ronusing react. With  react there is dependence with a field call : default value. 
In any advanced framework or libary has this feature

When I filtering the table with the filter textbox elemnt, the test fails. 
First I clear the text in th filterring text box elemnt, because I dont want to use the defult value , to filter.
Then I send keys - the filterring value that I want.
Whereupon, the text in the text box value is chaining.

For example : the default value in the text box elemt is : `Shahar`. I clear that value and send key with the value : `AutomationDeveloper`.
But, react using the default value with the value I sent using the SendKeys() method.So, in the filtering box the value is : `ShaharAutomationDeveloper`

### How can we reproduce the issue?

```shell
You can support the default field attribute and enusre the send keys method or clear method (I think the problem  is in the sendKeysmethod) works with new frameworks or libaries ablilities.

The solution I found his to send the keys : ctrl + a. and then the key : delete
```

### Relevant log output

```shell
The log output is because I filltering wrong data because selenium chains strings
```

### Operating System

Windows 10

### Selenium version

dotnet core 3.1 and dotnet 5

### What are the browser(s) and version(s) where you see this issue?

All chrome versions

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 80 until present version

### Are you using Selenium Grid?

Also using seleium gird 4

**Comment by jimevans** [comment]
@ShaharM7 All the .NET C# `SendKeys` method is doing is calling the [W3C WebDriver Specification's `Element Send Keys` end point](https://w3c.github.io/webdriver/#element-send-keys). If the behavior in the browser isn't what you expect, you should direct your issue report to the issue tracker for the driver (chromedriver, geckodriver, etc.) that does not act "correctly" for you.
