### ISSUE TITLE
[🐛 Bug]: Geckodriver on Centos not starting

### ISSUE THREAD

**Issue by Bllacky** [SeleniumHQ/selenium#10088]
### What happened?

I am writing in regard to the issue #10014

I did some extensive testing over the past few days.
My code:
```
def get_firefox_driver(is_proxy, proxy_params):
    global_var.DEFAULT_LOAD_TIME
    options = FirefoxOptions()

    try:
        driver = webdriver.Firefox(options=options)
        time.sleep(10)
    except TimeoutException:
        print("Firefox took more than 60 seconds start!")
        print("FFEx:"+repr(e))
    except Exception as e:
        print("FFEx:"+repr(e))
        
    try:
        driver.implicitly_wait(1)
        driver.set_window_size(1920, 1080)
        driver.set_page_load_timeout(global_var.DEFAULT_LOAD_TIME)
        driver.set_script_timeout(20)
    except Exception as e:
        print("Unable to start driver {}.".format(repr(e)))
    
        driver.get("https://www.bing.com/")
    
    return driver
```
ERROR
```
CEx:SessionNotCreatedException('session not created: No matching capabilities found', None, ['#0 0x558bba045ee3 <unknown>', '#1 0x558bb9b13608 <unknown>', '#2 0x558bb9b6c2a5 <unknown>', '#3 0x558bb9b6b6c6 <unknown>', '#4 0x558bb9b6cd4d <unknown>', '#5 0x558bb9b67163 <unknown>', '#6 0x558bb9b3cbfc <unknown>', '#7 0x558bb9b3dc05 <unknown>', '#8 0x558bba077baa <unknown>', '#9 0x558bba08d651 <unknown>', '#10 0x558bba078b05 <unknown>', '#11 0x558bba08ea68 <unknown>', '#12 0x558bba06d05f <unknown>', '#13 0x558bba0a9818 <unknown>', '#14 0x558bba0a9998 <unknown>', '#15 0x558bba0c4eed <unknown>', '#16 0x7f46598adea5 <unknown>', ''])
Unable to start driver UnboundLocalError("local variable 'driver' referenced before assignment").
```
gekodriver.log
```
console.log: WebExtensions: reset-default-search: starting.
console.log: WebExtensions: reset-default-search: No addons in our list are installed.
1637925795164   geckodriver     INFO    Listening on 127.0.0.1:44759
1637925795168   mozrunner::runner       INFO    Running command: "/bin/firefox" "--marionette" "--remote-debugging-port" "40606" "-no-remote" "-profile" "/tmp/rust_mozprofileFWvysu"
Running without a11y support!
1637925795517   Marionette      INFO    Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofileFWvysu/search.json.mozlz4", (void 0)))
DevTools listening on ws://localhost:40606/devtools/browser/a56408aa-1343-4f12-93ac-802bb2c7c728
1637925798414   Marionette      INFO    Listening on port 45437
1637925798496   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
1637925810193   Marionette      INFO    Stopped listening on port 45437
JavaScript error: chrome://global/content/elements/browser-custom-element.js, line 1671: NotFoundError: No such JSWindowActor 'MarionetteEvents'
JavaScript error: resource:///modules/Interactions.jsm, line 209: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]
!!! error running onStopped callback: TypeError: callback is not a function
1637925810920   RemoteAgent     ERROR   unable to stop listener: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIWindowMediator.getEnumerator]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://remote/content/cdp/observers/TargetObserver.jsm :: stop :: line 64"  data: no] Stack trace: stop()@TargetObserver.jsm:64
unwatchForTabs()@TargetList.jsm:70
unwatchForTargets()@TargetList.jsm:37
destructor()@TargetList.jsm:109
stop()@CDP.jsm:104
close()@RemoteAgent.jsm:138
1637926224227   geckodriver     INFO    Listening on 127.0.0.1:59093
1637926224231   mozrunner::runner       INFO    Running command: "/bin/firefox" "--marionette" "--remote-debugging-port" "47588" "-no-remote" "-profile" "/tmp/rust_mozprofile0dbwCJ"
Running without a11y support!
1637926224615   Marionette      INFO    Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofile0dbwCJ/search.json.mozlz4", (void 0)))
DevTools listening on ws://localhost:47588/devtools/browser/55789d37-fad9-4600-92d4-582adfe86781
1637926227215   Marionette      INFO    Listening on port 33191
1637926227505   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
1637926238888   Marionette      INFO    Stopped listening on port 33191
JavaScript error: chrome://global/content/elements/browser-custom-element.js, line 1671: NotFoundError: No such JSWindowActor 'MarionetteEvents'
JavaScript error: resource:///modules/Interactions.jsm, line 209: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIUserIdleService.removeIdleObserver]
!!! error running onStopped callback: TypeError: callback is not a function
1637926239699   RemoteAgent     ERROR   unable to stop listener: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIWindowMediator.getEnumerator]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://remote/content/cdp/observers/TargetObserver.jsm :: stop :: line 64"  data: no] Stack trace: stop()@TargetObserver.jsm:64
unwatchForTabs()@TargetList.jsm:70
unwatchForTargets()@TargetList.jsm:37
destructor()@TargetList.jsm:109
stop()@CDP.jsm:104
close()@RemoteAgent.jsm:138

```

I tried this only on Centos 7 and 8.
One on a physical machine, the other on an AWS machine.

I created a clean venv with the following packages:
```
async-generator==1.10
attrs==21.2.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.7
click==8.0.3
cryptography==36.0.0
decorator==5.1.0
fake-useragent==0.1.11
Flask==2.0.2
h11==0.12.0
idna==3.3
itsdangerous==2.0.1
Jinja2==3.0.3
MarkupSafe==2.0.1
outcome==1.1.0
pdfminer.six==20200517
pdfplumber==0.5.28
Pillow==8.4.0
pycparser==2.21
pycryptodome==3.11.0
pyOpenSSL==21.0.0
requests==2.26.0
selenium==4.1.0
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
trio==0.19.0
trio-websocket==0.9.2
urllib3==1.26.7
validators==0.18.2
Wand==0.6.7
Werkzeug==2.0.2
wsproto==1.0.0
```

Using latest geckodriver copied in venv/bin
firefox.x86_64                                                                 91.3.0-1.el7.centos 
Python 3.8.12

### How can we reproduce the issue?

```shell
I think I provided all the details above for creating a test environment.
```

### Relevant log output

```shell
See above
```

### Operating System

Centos 7 / Centos 8

### Selenium version

4.0.0r2 and above - works on 4.0.0r1

### What are the browser(s) and version(s) where you see this issue?

Firefox 90 and above

### What are the browser driver(s) and version(s) where you see this issue?

0.30.0

**Comment by AutomatedTester** [comment]
I still can't recreate the issue. Please can you add trace logs from geckodriver. see https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html how to enable it

**Comment by Bllacky** [comment]
> I still can't recreate the issue. Please can you add trace logs from geckodriver. see https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html how to enable it

Sure thing, but please be patient and don't close the issue fast. I am trying my best to give you the feedback you need but I have to juggle between doing many things so sometimes it takes a bit more.

**Comment by Bllacky** [comment]
[geckodriver.log](https://github.com/SeleniumHQ/selenium/files/7642999/geckodriver.log)
here is the trace log for geckodriver
I also tried to disable SELinux by setting ```setenforce 0``` but it didn't fix the issue, so I guess it's not a SELinux issue.

**Comment by AutomatedTester** [comment]
That log looks like there was a successful session, nothing you mentioned in the first comment is in this log

**Comment by whimboo** [comment]
Maybe set again `setenforce 1` and check if that is actually causing the problem.

**Comment by Bllacky** [comment]
> That log looks like there was a successful session, nothing you mentioned in the first comment is in this log

Yet the session failed just like every time. Also, I never quit the geckodriver, it should still be running after I open bing.com, yet I see this in the trace log:
```1638457965252	Marionette	DEBUG	0 -> [0,8,"Marionette:Quit",{"flags":["eForceQuit"]}]
1638457965253	Marionette	INFO	Stopped listening on port 43390
1638457965287	Marionette	TRACE	Received observer notification quit-application
1638457965287	Marionette	TRACE	Received observer notification quit-application
1638457965288	Marionette	DEBUG	Marionette stopped listening
```
@whimboo Already tried, doesn't seem to change anything.

**Comment by whimboo** [comment]
Well, you missed two important lines when you added the excerpt from the trace log:

```
1638457965252	webdriver::server	DEBUG	-> DELETE /session/5dcf8dde-18c3-48d0-9db8-ec695dd5f240 
1638457965252	Marionette	DEBUG	0 -> [0,8,"Marionette:Quit",{"flags":["eForceQuit"]}]
1638457965253	Marionette	INFO	Stopped listening on port 43390
```

This clearly sends a delete session command to Firefox and as such geckodriver triggers Marionette to quit Firefox. I don't see anything problematic here.

**Comment by Bllacky** [comment]
> Well, you missed two important lines when you added the excerpt from the trace log:
> 
> ```
> 1638457965252	webdriver::server	DEBUG	-> DELETE /session/5dcf8dde-18c3-48d0-9db8-ec695dd5f240 
> 1638457965252	Marionette	DEBUG	0 -> [0,8,"Marionette:Quit",{"flags":["eForceQuit"]}]
> 1638457965253	Marionette	INFO	Stopped listening on port 43390
> ```
> 
> This clearly sends a delete session command to Firefox and as such geckodriver triggers Marionette to quit Firefox. I don't see anything problematic here.

I see this is kinda problematic. First, this behaviour didn't happen in 4.0.0RC1 and second, I want to open a page and then perform some actions on it. How can I perform any kind of action on a page after I open it if the session gets deleted?

Remember, my code is the one I provided above, in the first post of this thread.

This is the same log file with version 4.0.0RC1:
```
1638521151933   geckodriver     INFO    Listening on 127.0.0.1:39083
1638521152437   mozrunner::runner       INFO    Running command: "/bin/firefox" "--marionette" "--remote-debugging-port" "9222" "-no-remote" "-profile" "/tmp/rust_mozprofileCxrbjY"
Running without a11y support!
1638521155062   Marionette      INFO    Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofileCxrbjY/search.json.mozlz4", (void 0)))

!!! could not start server on port 9222: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.init]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: _start :: line 574"  data: no]

1638521160350   RemoteAgent     ERROR   unable to stop listener: [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: stop :: line 628"  data: no] Stack trace: stop()@HTTPD.jsm:628
close()@RemoteAgent.jsm:142
asyncListen()@RemoteAgent.jsm:129
listen()@RemoteAgent.jsm:119
_scheduleStartupIdleTasks/task/<()@resource:///modules/BrowserGlue.jsm:2576
1638521160350   RemoteAgent     ERROR   Unable to start remote agent: : [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: _start :: line 619"  data: no] Stack trace: _start()@HTTPD.jsm:619
asyncListen()@RemoteAgent.jsm:124
listen()@RemoteAgent.jsm:119
_scheduleStartupIdleTasks/task/<()@resource:///modules/BrowserGlue.jsm:2576
1638521160379   Marionette      INFO    Listening on port 40874
1638521160848   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
1638521164051   Marionette      WARN    Ignoring event 'DOMContentLoaded' because document has an invalid readyState of 'complete'.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

NS_ERROR_SOCKET_ADDRESS_IN_USE is probably because I didn't clean quit geckodriver before testing, but used the kill command. However, geckodriver still starts successfully and I am able to control firefox via Selenium.

**Comment by whimboo** [comment]
The code in comment 0 is not complete. Note that there are missing lines that trigger the following script execution:

```
1638457964726	webdriver::server	DEBUG	-> POST /session/5dcf8dde-18c3-48d0-9db8-ec695dd5f240/execute/sync {"script": "return run_status;", "args": []}
1638457964729	Marionette	DEBUG	0 -> [0,7,"WebDriver:ExecuteScript",{"args":[],"script":"return run_status;"}]
1638457964732	Marionette	TRACE	[19] MarionetteCommands actor created for window id 2147483650
1638457964736	Marionette	DEBUG	0 <- [1,7,{"error":"javascript error","message":"ReferenceError: run_status is not defined","stacktrace":"@https://www.bing.com/:2:7\n@https://www.bing.com/:3:8\n"},null]
1638457964737	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"javascript error","message":"ReferenceError: run_status is not defined","stacktrace":"@https://www.bing.com/:2:7\n@https://www.bing.com/:3:8\n"}}
```

And this happens after the URL has been successfully loaded. So I assume there is some missing try/catch and the error bubbles up and causes Selenium to close the session.

**Comment by Bllacky** [comment]
> The code in comment 0 is not complete. Note that there are missing lines that trigger the following script execution:
> 
> ```
> 1638457964726	webdriver::server	DEBUG	-> POST /session/5dcf8dde-18c3-48d0-9db8-ec695dd5f240/execute/sync {"script": "return run_status;", "args": []}
> 1638457964729	Marionette	DEBUG	0 -> [0,7,"WebDriver:ExecuteScript",{"args":[],"script":"return run_status;"}]
> 1638457964732	Marionette	TRACE	[19] MarionetteCommands actor created for window id 2147483650
> 1638457964736	Marionette	DEBUG	0 <- [1,7,{"error":"javascript error","message":"ReferenceError: run_status is not defined","stacktrace":"@https://www.bing.com/:2:7\n@https://www.bing.com/:3:8\n"},null]
> 1638457964737	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"javascript error","message":"ReferenceError: run_status is not defined","stacktrace":"@https://www.bing.com/:2:7\n@https://www.bing.com/:3:8\n"}}
> ```
> 
> And this happens after the URL has been successfully loaded. So I assume there is some missing try/catch and the error bubbles up and causes Selenium to close the session.

**Comment by Bllacky** [comment]
> The code in comment 0 is not complete. Note that there are missing lines that trigger the following script execution:
> 

You are right. It had one extra line. Here is the trace logs for selenium 4.0.0rc1 and 4.1.0 with the above code. I think this should be a lot more helpful.
[geckodriver_410.log](https://github.com/SeleniumHQ/selenium/files/7648458/geckodriver_410.log)
[geckodriver_400rc1.log](https://github.com/SeleniumHQ/selenium/files/7648460/geckodriver_400rc1.log)

**Comment by AutomatedTester** [comment]
The 4.1 looks like a normal log. As @whimboo pointed out that your script is passing a `driver.quit()` We can see that in 

```log
1638525008853	webdriver::server	DEBUG	-> DELETE /session/ca585419-882a-411f-862f-3165f2cb0a16 
1638525008853	Marionette	DEBUG	0 -> [0,6,"Marionette:Quit",{"flags":["eForceQuit"]}]
1638525008854	Marionette	INFO	Stopped listening on port 34294
1638525008899	Marionette	TRACE	Received observer notification quit-application
1638525008899	Marionette	TRACE	Received observer notification quit-application
1638525008900	Marionette	DEBUG	Marionette stopped listening
```
The top line is a client is sending a command over to geckodriver. 

In your rc1 log, there is no `DELETE` which means it's not being sent over from the client.

One other thing, none of these logs contain 
```
CEx:SessionNotCreatedException('session not created: No matching capabilities found', None, ['#0 0x558bba045ee3 <unknown>', '#1 0x558bb9b13608 <unknown>', '#2 0x558bb9b6c2a5 <unknown>', '#3 0x558bb9b6b6c6 <unknown>', '#4 0x558bb9b6cd4d <unknown>', '#5 0x558bb9b67163 <unknown>', '#6 0x558bb9b3cbfc <unknown>', '#7 0x558bb9b3dc05 <unknown>', '#8 0x558bba077baa <unknown>', '#9 0x558bba08d651 <unknown>', '#10 0x558bba078b05 <unknown>', '#11 0x558bba08ea68 <unknown>', '#12 0x558bba06d05f <unknown>', '#13 0x558bba0a9818 <unknown>', '#14 0x558bba0a9998 <unknown>', '#15 0x558bba0c4eed <unknown>', '#16 0x7f46598adea5 <unknown>', ''])
Unable to start driver UnboundLocalError("local variable 'driver' referenced before assignment").
``` 

which was in your original comment.

We're still not seeing the issue you're getting at all.

**Comment by Bllacky** [comment]
> The 4.1 looks like a normal log. As @whimboo pointed out that your script is passing a `driver.quit()` We can see that in
> 
> ```
> 1638525008853	webdriver::server	DEBUG	-> DELETE /session/ca585419-882a-411f-862f-3165f2cb0a16 
> 1638525008853	Marionette	DEBUG	0 -> [0,6,"Marionette:Quit",{"flags":["eForceQuit"]}]
> 1638525008854	Marionette	INFO	Stopped listening on port 34294
> 1638525008899	Marionette	TRACE	Received observer notification quit-application
> 1638525008899	Marionette	TRACE	Received observer notification quit-application
> 1638525008900	Marionette	DEBUG	Marionette stopped listening
> ```
> 
> The top line is a client is sending a command over to geckodriver.
> 
> In your rc1 log, there is no `DELETE` which means it's not being sent over from the client.
> 
> One other thing, none of these logs contain
> 
> ```
> CEx:SessionNotCreatedException('session not created: No matching capabilities found', None, ['#0 0x558bba045ee3 <unknown>', '#1 0x558bb9b13608 <unknown>', '#2 0x558bb9b6c2a5 <unknown>', '#3 0x558bb9b6b6c6 <unknown>', '#4 0x558bb9b6cd4d <unknown>', '#5 0x558bb9b67163 <unknown>', '#6 0x558bb9b3cbfc <unknown>', '#7 0x558bb9b3dc05 <unknown>', '#8 0x558bba077baa <unknown>', '#9 0x558bba08d651 <unknown>', '#10 0x558bba078b05 <unknown>', '#11 0x558bba08ea68 <unknown>', '#12 0x558bba06d05f <unknown>', '#13 0x558bba0a9818 <unknown>', '#14 0x558bba0a9998 <unknown>', '#15 0x558bba0c4eed <unknown>', '#16 0x7f46598adea5 <unknown>', ''])
> Unable to start driver UnboundLocalError("local variable 'driver' referenced before assignment").
> ```
> 
> which was in your original comment.
> 
> We're still not seeing the issue you're getting at all.

I will investigate further. However, please keep in mind that the tracelogs I posted in my last comment are for exactly the same code I posted in the initial message. As you can see, the one from 4.1.0 has driver.quit() the other from 4.0.0rc1 doesn't have it. My code has no driver.quiet(). I can only conclude that the driver.quit() command is coming from selenium for some reason.

I will try to build a simple test environment and if that fails too, I will zip it and place it here.

**Comment by Bllacky** [comment]
Guys, I'm an idiot. For some reason, the error seemed to come from the geckodriver but it was actually from the chromedriver! I am starting up a service that opens up one firefox session and another chrome session and then I send commands to both browsers.

Anyway, the issue was from initialising chrome driver with the following parameters:
```   
options.platform_name = "WINDOWS"
options.platform_version = "10"
```
Opening up chrome driver in 4.0.0rc2 and above with the above options will make chrome fail with the error code mentioned in this issue.

Thanks for the guidance in debugging this problem.
Closing this issue.

**Comment by AutomatedTester** [comment]
Glad we got to bottom of it
