### ISSUE TITLE
.Net Selenium Chrome Sendkeys Problems sending letters missing

### ISSUE THREAD

**Issue by hepter** [SeleniumHQ/selenium#1008]
I have a problem sending letters missing on Chrome.does not send some characters

Running Code:

 Dim Message As String = "This example is a message(eeeiiiooo)"
 Dim driver As New ChromeDriver(BinDizin)
 driver.Navigate.GoToUrl("http://www.samplesite.com/blablabla")
 For i = 0 To 9
     fe.FindElement(By.Name("descrpt")).SendKeys(Message)
     fe.FindElement(By.Name("descrpt")).SendKeys(vbLf)
 Next

Originak Text: This example is a message(eeeiiiooo)

Website Textbox outputs:
This example is a message(eeeiiiooo)
This example is a message(eeeiiiooo)
This example is a messageeeeiiiooo)   missing letter "("
This example is a message(eeeiiiooo)
This example is a message(eeiiiooo)   missing letter "e"
This example is a message(eeeiiiooo)
This example is a message(eeeiiiooo)
This example is a message(eeiiiooo)   missing letter "e"
This eample is a message(eeeiiiooo)   missing letter "x"
This example is a message(eeeiiiooo)

I have a problem occurs while Sending a password in PassBox How can I solve this problem

Chrome Version:45.0.2454.85

Chromedriver.exe version:2.18.343845

**Comment by barancev** [comment]
Please report this issue to the chromedriver tracker:
https://sites.google.com/a/chromium.org/chromedriver/help
