### ISSUE TITLE
PhantomJS driver in Python does not properly accept proxy

### ISSUE THREAD

**Issue by PaintingInAir** [SeleniumHQ/selenium#1009]
Adding a proxy via the service argument: --proxy=ip:port does not result in the proxy being used. The same is true for adding the proxy via desired capabilities.

The specific proxy was testing with PhantomJS directly via command line, and does work as expected. It only does not work when used with Selenium.

Note: this specific proxy is accessed via localhost "--proxy=localhost:8081". I do not have an external proxy to test.

**Comment by llaskin** [comment]
Per the project owner, we are removing this from the project @shs96c @detro

**Comment by barancev** [comment]
Anyway, please report PhantomJS driver issues to the corresponding tracker: https://github.com/detro/ghostdriver/issues
