### ISSUE TITLE
[🐛 Bug]: 2 of netty-transport-native-epoll-4.1.69.Final.jar

### ISSUE THREAD

**Issue by Dmole** [SeleniumHQ/selenium#10102]
### What happened?

selenium-java-4.1.0.zip contains lib/netty-transport-native-epoll-4.1.69.Final.jar 2 times.

### How can we reproduce the issue?

```shell
if [ "$(7z l selenium-java-4.1.0.zip | grep -Ec "netty-transport-native-epoll-.*\.Final.jar")" -gt 1 ] ; then
    echo "Fail";
fi
```

### Relevant log output

```shell
> ls -hal
total 8.0K
drwxrwxr-x 2 tim tim 4.0K 2021-11-29 13:26 .
drwxrwxr-x 3 tim tim 4.0K 2021-11-29 13:19 ..


> 7z x ../selenium-java-4.1.0.zip 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (806C1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 24643465 bytes (24 MiB)

Extracting archive: ../selenium-java-4.1.0.zip
--
Path = ../selenium-java-4.1.0.zip
Type = zip
Physical Size = 24643465

    
Would you like to replace the existing file:
  Path:     ./lib/netty-transport-native-epoll-4.1.69.Final.jar
  Size:     171406 bytes (168 KiB)
  Modified: 2010-01-01 00:00:00
with the file from archive:
  Path:     lib/netty-transport-native-epoll-4.1.69.Final.jar
  Size:     140549 bytes (138 KiB)
  Modified: 2010-01-01 00:00:00
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? Q

Archives with Errors: 1



Break signaled


> 7z l ../selenium-java-4.1.0.zip | grep netty-transport-native-epoll-4.1.69.Final.jar
2010-01-01 00:00:00 .....       171406       171406  lib/netty-transport-native-epoll-4.1.69.Final.jar
2010-01-01 00:00:00 .....       140549       140549  lib/netty-transport-native-epoll-4.1.69.Final.jar
```

### Operating System

N/A

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by Dmole** [comment]
7z l selenium-java-4.1.0.zip | grep "\.\.\.\.\." | perl -pe 's/.* //g'  | sort | uniq -c | grep -v " 1 " | sort -nr
          2 lib/netty-transport-native-kqueue-4.1.69.Final.jar
          2 lib/netty-transport-native-epoll-4.1.69.Final.jar

Would be a good test for CI as it could error out on any paths with multiples in the zip, and let someone know which files are causing the issue.

**Comment by diemol** [comment]
Fixed by https://github.com/SeleniumHQ/selenium/commit/612896f443f03e84efc1444197b02564dffce1e2#diff-9c3b2865d63832d4165deeb595c9aa5d8242fcfbf768f52dcd0dd18f0784957bL36-L40. Will be visible in the next release.

Thanks, @pujagani!

**Comment by pkoenig10** [comment]
After this change, `selenium-remote-driver` now has dependencies on both `netty-transport-native-epoll` and `netty-transport-classes-epoll`. These JARs have identical classes and result in duplicate classes at runtime.
- `netty-transport-classes-epoll` comes from `selenium-remote-driver`
- `netty-transport-native-epoll` comes from `async-http-client`

Can we update the dependencies to exclusively use one or the other?

**Comment by pkoenig10** [comment]
Nevermind, this was caused because I was depending on different versions of `netty-transport-classes-epoll` and `netty-transport-native-epoll`. The duplicate classes were resolved once I used a consistent version with [netty-transport-native-epoll](https://github.com/netty/netty/pull/11798).
