### ISSUE TITLE
[🐛 Bug]: Selenium is expecting pages to load faster than it can, only on *Chrom*

### ISSUE THREAD

**Issue by signed-log** [SeleniumHQ/selenium#10100]
### What happened?

NOTE : The same exact script works on Firefox `94.0.1` with `GeckoDriver` `v0.30.0` on the same exact machine

Selenium is expecting \*Chrom\* to load pages way faster than it can do, querying elements when the elements aren't still loaded resulting on errors.

It only ever happened to me on NVIDIA Driver download pages

When switching from the `*nix` driver list page (https://www.nvidia.com/en-us/drivers/unix/) to the appropriate download page.  
It seems to have loaded the page from the outside (i.e all elements *seem* loaded when looking at the webpage, but in depth they aren't), so when I try to query an attribute of an element (like with 
```python
driver.find_elements(
    By.CSS_SELECTOR,
    "#mainContent > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > "
    "a:nth-child(1)")[0].get_attribute("href")
```
)
that isn't loaded it fails (see errors 1 and 2)

Will have a report on both Google and MS websites too

### How can we reproduce the issue?

```shell
from selenium.webdriver.common.by import By

driver = Chrome() #or ChromiumEdge()
driver.get("https://www.nvidia.com/en-us/drivers/unix/")
link_text = driver.find_elements(
    By.CSS_SELECTOR,
    f"#rightContent > p:nth-child(1) > a:nth-child(3)")[0].text
driver.find_element(By.LINK_TEXT, link_text).click()
# Only works consistently with a time.sleep(1)
driver.find_element(By.ID, "lnkDwnldBtn").click()
dl_link = driver.find_elements(
    By.CSS_SELECTOR,
    "#mainContent > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > "
    "a:nth-child(1)")[0].get_attribute("href")
driver.close()
```

### Relevant log output

```shell
--- ERROR 1 ---

Traceback (most recent call last):
  File "./main.py", line 184, in <module>
    dl_link, driver_version = get_dl_url(os_code=os_code, branch_code=branch_code)
  File "./main.py", line 161, in get_dl_url
    driver.close()
  File "/home/stig124/.local/share/virtualenvs/autonvidia-ouBhMtGZ/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 937, in close
    self.execute(Command.CLOSE)
  File "/home/stig124/.local/share/virtualenvs/autonvidia-ouBhMtGZ/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/stig124/.local/share/virtualenvs/autonvidia-ouBhMtGZ/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x55eedc1d3473 <unknown>
#1 0x55eedbc48307 <unknown>
#2 0x55eedbc74e6f <unknown>
#3 0x55eedbc76315 <unknown>
#4 0x55eedc1fd2a7 <unknown>
#5 0x55eedc20ce6d <unknown>
#6 0x55eedc20cbe9 <unknown>
#7 0x55eedc20d312 <unknown>
#8 0x55eedc1fe7bb <unknown>
#9 0x55eedc20d605 <unknown>
#10 0x55eedc1f43d5 <unknown>
#11 0x55eedc224638 <unknown>
#12 0x55eedc2247e8 <unknown>
#13 0x55eedc23edaa <unknown>
#14 0x7fca97c73b37 <unknown>
#15 0xaaaaaaaaaaaaaaaa <unknown>

--- ERROR 2 ---
Traceback (most recent call last):
  File "./main.py", line 183, in <module>
    dl_link, driver_version = get_dl_url(os_code=os_code, branch_code=branch_code)
  File "./main.py", line 155, in get_dl_url
    dl_link = driver.find_elements(
IndexError: list index out of range
```

### Operating System

openSUSE Tumbleweed

### Selenium version

Python 3.8.12 | Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge (dev channel) 97.0.1072.13 | Chrome (stable) 96.0.4664.45

### What are the browser driver(s) and version(s) where you see this issue?

EdgeChromiumDriver 97.0.1072.13 | ChromeDriver 96.0.4664.45

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
Unfortunately, Selenium doesn't control how the browser transitions between pages, that is done by Chromium Browsers.

Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
