### ISSUE TITLE
Selenium grid jar file missing from Maven respository

### ISSUE THREAD

**Issue by AidanMcD** [SeleniumHQ/selenium#1011]
Go to https://repo1.maven.org/maven2/org/openqa/selenium/grid/selenium-grid/1.0.2/

There is a zip file and a POM but no Jar file.

**Comment by barancev** [comment]
Selenium Grid is now part of Selenium Server:
http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-server%7C2.47.1%7Cjar
