### ISSUE TITLE
[🚀 Feature]: Support stereotypes `configs` from the CLI with Relay

### ISSUE THREAD

**Issue by cytung** [SeleniumHQ/selenium#10115]
### Feature and motivation

When I'm trying to [relay commands to a service endpoint](https://www.selenium.dev/documentation/grid/configuring_components/toml_options/#relaying-commands-to-a-service-endpoint-that-supports-webdriver) via CLI, I only found 4 options in the [CLI Options Docs](https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#relay) (`--service-url`, `--service-host`, `--service-port` and `--service-status-endpoint`). I cannot find an option that corresponds to `configs` for the `[relay]` in TOML Options to define stereotypes supported by the service.

### Usage example

According to [selenium/java/src/org/openqa/selenium/grid/node/relay/RelayOptions.java](https://github.com/SeleniumHQ/selenium/blob/319fd1afd7cfd9fd5418320de8bc8396e3bb70a5/java/src/org/openqa/selenium/grid/node/relay/RelayOptions.java), it seems like `configs` should contain `maxSessions` and `stereotype`, so the usage may look like:
```
java -jar selenium-server-<version>.jar node --relay-configs max-sessions=1 stereotype='{"browserName": "safari", "platformName": "iOS",  "appium:platformVersion": "14.5"}' --service-url "http://localhost:4723/wd/hub"
```

**Comment by diemol** [comment]
This was more a bug fix since we forgot to add the option when the relay feature was implemented. It will look like this

```
--service-configuration max-sessions=2 stereotype='{"browserName": "safari", "platformName": "iOS", appium:platformVersion": "14.5"}}' --service-url "http://localhost:4723/wd/hub"
```
