### ISSUE TITLE
[🐛 Bug]: Custom capability not working with Selenium 4

### ISSUE THREAD

**Issue by kartick-s** [SeleniumHQ/selenium#10128]
### What happened?

I have one hub with two nodes. First node is having custom capability ("goog:customcap", true) & second node is the regular one.
I'm passing ("goog:customcap", true) capability in my code so that it gets executed in Node1. However observed that it's randomly routed to node1 & node2 for execution. Which is not expected.

Kindly suggest how to implement custom capability in Selenium 4.

### How can we reproduce the issue?

```shell
Start the hub and 2 nodes:
java -jar selenium-server-4.0.0.jar hub


A special node that supports a custom capability
java -jar selenium-server-4.0.0.jar node --detect-drivers false --driver-configuration display-name="Chrome (custom capability true)" max-sessions=1 stereotype={\"browserName\":\"chrome\",\"goog:customcap\":true} --port 6161


A regular node that doesn't define any custom capabilities
java -jar selenium-server-4.0.0.jar node --detect-drivers false --driver-configuration display-name="Chrome" max-sessions=1 stereotype={\"browserName\":\"chrome\"} --port 6262
```

### Relevant log output

```shell
I expect that when I run the below code, it will be executed only on the first node, but it runs on all 2 of them.

DesiredCapabilities capabilities = new DesiredCapabilities();

capabilities.setCapability("browserName","chrome");
capabilities.setCapability("goog:customcap", true); 


WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), capabilities);
driver.get("http://example.com");
Thread.sleep(1000);
driver.quit();
```

### Operating System

Hub--> Linux(RHEL7), Node --> Windows server 2016

### Selenium version

selenium-server-4.0.0

### What are the browser(s) and version(s) where you see this issue?

Browser: Chrome , Browser version: 95

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95

### Are you using Selenium Grid?

4.0.0

**Comment by diemol** [comment]
A couple of things... The `goog:` prefix is reserved for Chrome and ChromeDriver, so adding any custom capability with it will result in unexpected results. If you want to add custom caps, it needs to be with a custom prefix as well, and the capability needs to be always provided in the session request, otherwise it won't be matched. For example, you need to provide both cases in tests, either `customPrefix:true` and `customPrefix:false`.

You can also overwrite the behaviour by implementing a `SlotMatcher` and passing it through [`--slot-matcher`](https://www.selenium.dev/documentation/grid/configuration/cli_options/#distributor).

**Comment by kartick-s** [comment]
Hi Team,

As you suggest, I have changed the custom capability to ("gsg:customcap", true)
I have one hub with two nodes. First node is having custom capability ("gsg:customcap", true) & the second node is the regular one.
When I'm passing ("gsg:customcap", true) capability in my code, then It gets executed in Node1. But when I'm NOT PASSING the custom capability, then also it gets executed in First node which is not expected.

I want Node1 to take only those session requests which have the custom capability ("gsg:customcap", true). 
Please suggest.

**Comment by eravion** [comment]
Hello,
Same issue here.
We are using customcap to point specific node.

**Comment by diemol** [comment]
Because you need to always send the custom capability on your tests.

**Comment by eravion** [comment]
linked to : https://github.com/SeleniumHQ/selenium/issues/10175
