### ISSUE TITLE
[🐛 Bug]: Issue in Selenium 4- Relative locator. 

### ISSUE THREAD

**Issue by GokiAmmulu** [SeleniumHQ/selenium#10123]
### What happened?

Below direction enters value in the very next below object and this is not constant. Sometimes this is working fine and adds value in the correct object. 

### How can we reproduce the issue?

```shell
Since using the option for the official site. I am not allowed to provide the details here.
```

### Relevant log output

```shell
Incorrect textbox identified.
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Version 96.0.4664.45 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Version 96.0.4664.45 (Official Build) (64-bit)

### Are you using Selenium Grid?

No

**Comment by GokiAmmulu** [comment]
Hi Team,

Below the code I am using and providing you the DOM structure and application view for your reference.

By using the below code, 
Case 1: Script is running sometimes correctly by inputting the value in the ID textbox without any issues
Case 2: Value is not entered in the ID textbox and code comes out of the loop 

Same code is not running sometimes, wanted to know the cause of this issue. Please check the code and attached additional details for reference. 

[Selenium 4 - Relative Locator - Issue.docx](https://github.com/SeleniumHQ/selenium/files/7693107/Selenium.4.-.Relative.Locator.-.Issue.docx)

if(driver.findElements(RelativeLocator.with(By.tagName("input")).below(By.xpath("//*[text()='ID']"))).size()!=0) 
{
           element=driver.findElement(RelativeLocator.with(By.tagName("input")).below(By.xpath("//*[text()=''ID']")));
}

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site). It does not need to be the exact same code you are using internally, it needs to be something we can use to reproduce the issue.

**Comment by titusfortner** [comment]
Relative locators are inherently a little vague. They work by traversing the DOM node near an element and evaluating each element's `rect` (coordinates and dimensions). It can be easy for one element to slightly overlap another in a way that the "wrong" element will be selected. Relative locators are a nice shortcut when the specific DOM you are working with makes them easy to use, and will be more trouble than they are worth for most others.

In this specific case, you should be using a plain locator to find the input element that has an aria-label attribute of "ID"
