### ISSUE TITLE
[🐛 Bug]: Update .NET API Docs

### ISSUE THREAD

**Issue by JonathonAnderson** [SeleniumHQ/selenium#10126]
### What happened?

The available stable API version for C# is 4.1.0, but when I open the docs and navigate to the ChromeDriver section, the content is for version 3.1.0. This was exceptionally confusing for me as numerous methods have been removed, but they are listed in the docs, so I couldn't figure out why the methods were not available.

### How can we reproduce the issue?

```shell
Navigate to ChromeDriver section of docs
https://www.selenium.dev/selenium/docs/api/dotnet/index.html
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664

**Comment by titusfortner** [comment]
The root issue here is [bazel limitations in .NET](https://github.com/SeleniumHQ/selenium/issues/10465)
