### ISSUE TITLE
Deadlink in Documentatoin

### ISSUE THREAD

**Issue by notnull1** [SeleniumHQ/selenium#1013]
http://docs.seleniumhq.org/docs/07_selenium_grid.jsp#what-is-selenium-grid
Chapter : How Selenium-Grid Works–With a Hub and Nodes¶
Deadlink at : "A diagram illustrates this."  to : http://selenium-grid.seleniumhq.org/how_it_works.html

**Comment by ddavison** [comment]
Moved to https://github.com/SeleniumHQ/www.seleniumhq.org/issues/40

Thanks for this report!
