### ISSUE TITLE
[🚀 Feature]: WaitForNavigation method

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#10136]
### Feature and motivation

Just like in puppeteer, a WaitForNavigation method would be really useful because currently there's no way to wait for navigation and know when a page has been fully loaded.

having options like NetworkIdle2 and Load would also be great.

### Usage example

`driver.Navigate().WaitForNavigation()`

another one would accept parameters such as `NetworkIdle2` and `Load`, `DOMContentLoaded` and so on.

**Comment by AutomatedTester** [comment]
@dahanj95

**Comment by AutomatedTester** [comment]
@dahanj95 I think this is a reasonable request however there is not much we can do until we can get it into the [WebDriver Spec](w3c.github.io/webdriver/). 

It should be a "simple" case of adding new values to different [page load strategies](https://w3c.github.io/webdriver/#dfn-table-of-page-load-strategies) and then getting browser vendors to implement this for us. I expect this to be doable since both Firefox and Chrome are supporting puppeteer.

**Comment by ghost** [comment]
According to [this](https://github.com/w3c/webdriver/issues/1636#issuecomment-994684060) comment, it seems like WebDriver already allows this capability. Why not implement it? Selenium should have supported this by initial version, how on earth would we wait for navigation to complete without this functionality?

**Comment by diemol** [comment]
How on earth can we claim that something is not implemented when we don't check the docs? :)
https://www.selenium.dev/documentation/webdriver/capabilities/shared/#pageloadstrategy

**Comment by ghost** [comment]
> How on earth can we claim that something is not implemented when we don't check the docs? :) https://www.selenium.dev/documentation/webdriver/capabilities/shared/#pageloadstrategy

Hahahahahaha, yeah you're right! 😀. I didn't know that was the problem all along, the documentation. I just thought that this was by design and not by the specs lol. I wrote them [here](https://github.com/w3c/webdriver/issues/1636#issuecomment-994739337) about it.

**Comment by titusfortner** [comment]
Sounds like advanced ways of waiting for navigation are not on the horizon for the spec, which means not yet for Selenium. Hopefully we can figure out more things to do with BiDi as that spec progresses this next year.

**Comment by ghost** [comment]
@AutomatedTester I see that there's a "complete" strategy, but when I load a modern web app page Selenium triggers complete before the page finishes to load completely (when I debug and set a bp on the next line after GoToUrl, I can still see that the circle is loading and my bp is hit). I'm not sure what's causing this behaviour behind the scenes, that's why I requested this feature. Anyways, I switched to Playwright, seems like this is the new modern way of automated testing for modern web apps which is going to replace Selenium & Puppeteer.
