### ISSUE TITLE
[🚀 Feature]: Publish Selenium Server 4.1.0 to https://selenium-release.storage.googleapis.com

### ISSUE THREAD

**Issue by mjmj** [SeleniumHQ/selenium#10134]
### Feature and motivation

Hi, Not sure who controls publishing new releases to https://selenium-release.storage.googleapis.com/index.html, but it would be helpful to be able to pull 4.1.0 stand alone server there. Selenium grid extras and a few projects look for newer versions there by default. Thank you!

### Usage example

Browse https://selenium-release.storage.googleapis.com/index.html and notice latest is 4.0 alpha versions.

**Comment by diemol** [comment]
Please check https://www.selenium.dev/blog/2021/downloads-now-on-github-releases/
