### ISSUE TITLE
[🚀 Feature]: Access to ShadowRoot in typescript

### ISSUE THREAD

**Issue by adomened** [SeleniumHQ/selenium#10135]
### Feature and motivation

What I am looking for is to obtain the elements contained in ShadowRoot to be able to interact with them through Selenium. Thanks. This proposal comes because of the problems I am having in Chrome 96

### Usage example

```javascript
public async getExtShadowRoot(selectorShadowHost: string): Promise<WebElement> {
    let shadowHost: WebElementPromise;
    await (shadowHost = this.driver.findElement(By.css(selectorShadowHost)));
    return this.driver.executeScript("return arguments[0].shadowRoot", shadowHost);
  }

  public async findShadowDomElement(selectorShadowHost: string, selectorShadowDomElement: string) {
    let shadowRoot;
    let element;
    await (shadowRoot = this.getExtShadowRoot(selectorShadowHost));
    await shadowRoot.then(async (result) => {
      await (element = result.findElement(By.css(selectorShadowDomElement)));
    });
    return element 
  }
```

Get access to the element identified by the .container selector from within a ShadowRoot

``` javascript
@findByIntoSahdowRoot('settings-ui', '.container')
  public element!: WebComponent;
```

**Comment by Sckye** [comment]
I have a similar issue as well that only started happening with ChromeDriver version 96.  When casting to an IWebElement, it throws an exception of:

`var shadowRootElement = (IWebElement) driver.ExecuteScript("return arguments[0].shadowRoot", element);`

**System.InvalidCastException: 'Unable to cast object of type 'OpenQA.Selenium.ShadowRoot' to type 'OpenQA.Selenium.IWebElement'.'**

**Comment by diemol** [comment]
@harsha509 do we need to make any changes in the bindings to support this? I thought this was supposed to be working already.
