### ISSUE TITLE
[🚀 Feature]:  Switching between drivers/Switching between two or more browser windows with single driver/multiple drivers.

### ISSUE THREAD

**Issue by mustaq-13** [SeleniumHQ/selenium#10130]
### Feature and motivation

Our team is working on a project wherein we need to automate an application with multiple users simultaneously . Therefore,
we need to perform set of workflows on say user 'A' and switch to user 'B' to approve the actions performed on user 'A'. Now, again switch back to user 'A' and perform some more actions and so on. To automate this workflow we need two browser windows running simultaneously, and this requires two drivers to trigger two browser windows. Therefore, we are using two drivers to automate this scenario.

Problem Statement: Selenium supports switching between two different browser tabs/windows, but there is no such feature to switch between two drivers in selenium.

### Usage example

Selenium community is very vast and provides numerous solutions in automating web applications. While researching on driver switch workflow over the internet in various discussion forums, we noticed that there are many organizations and individuals who are stuck with this problem statement. Therefore, we think it will be a great help to the whole selenium community if this feature (switching between drivers) is being developed.

An example code snippet is attached for your reference.
[Demo.zip](https://github.com/SeleniumHQ/selenium/files/7692970/Demo.zip)

**Comment by titusfortner** [comment]
We've had similar requests, and mostly it comes down to the fact that the driver all works off of a single session id. If we allowed users to swap out what the session id is, there's no way of knowing the capabilities match. It would be possible I suppose to manage those in complicated dictionaries, but that would get difficult to maintain very quickly. It's much better for everyone to just manage the two driver objects in your code.

Is there something you can't do right now with your setup, or are you just hoping for something more convenient from the Selenium library?

**Comment by mustaq-13** [comment]
Our scenario requires two users working on similar application simultaneously on two browser windows, one user performs some actions and the other approves it. Therefore, we need to switch between user1 and user2 multiple times. As we have 
similar application for both users, we cannot use browser tabs here because, upon refresh on any one window both the browser windows will reload and override with the latest logged in user data.

Therefore to avoid the above problem if we use two different drivers, each for user1 and user2, we will end up with switching between drivers issue.

We would greatly appreciate it, if you could provide us with a workaround/feature to accomplish our requirement. Thank You!

**Comment by titusfortner** [comment]
Yes, the desired implementation is one session per driver and if you need two independent sessions in your tests, it is necessary to manage the two driver instances in your code.
