### ISSUE TITLE
[🐛 Bug]: The c-nodejs documentation describes a method setDownloadPath that does not seem to exist in TypeScript

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#10139]
### What happened?

The C-nodejs [documentation](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Driver.html#setDownloadPath) describes the method `setDownloadPath` but it does not appear in the definition of the WebDriver in TypeScript.

### How can we reproduce the issue?

```shell
const {Builder} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('chrome').build();
  await driver.setDownloadPath('./temp');
  await driver.quit();
})();
```

### Relevant log output

```shell
Property 'setDownloadPath' does not exist on type 'WebDriver'.
```

### Operating System

macOS Monterey

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96

**Comment by diemol** [comment]
Seems the linked PR was merged, so this should be working already. Closing.
