### ISSUE TITLE
[🐛 Bug]: Ruby Firefox - impossible choose non-default profile (Profiles.from_name does not work)

### ISSUE THREAD

**Issue by mingulov** [SeleniumHQ/selenium#10146]
### What happened?

ruby, selenium-webdriver 4.1.0 (most probably since 3.150.0)

The next line fails due to missing Util / Util.app_data_path:
Selenium::WebDriver::Firefox::Profile.from_name("profile_name")

Util.app_data_path is used twice in lib/selenium/webdriver/firefox/profiles_ini.rb, but it is removed more than 2 years ago:

https://github.com/SeleniumHQ/selenium/commit/32262cc6b87d3c466e3eab5c6445394f300ec1cd

As a workaround - I have provided my own copy of that function (and everything started to work), but it would be nice to fix it.
Or is there some other way now to use profiles for Firefox in selenium?

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'
Selenium::WebDriver::Firefox::Profile.from_name("profile_name")
```

### Relevant log output

```shell
Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/firefox/profiles_ini.rb:26:in `initialize': uninitialized constant Selenium::WebDriver::Firefox::ProfilesIni::Util (NameError)
        from Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/firefox/profile.rb:41:in `new'
        from Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/firefox/profile.rb:41:in `ini'
        from Ruby30/lib/ruby/gems/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/firefox/profile.rb:45:in `from_name'
```

### Operating System

Windows 10

### Selenium version

ruby, selenium-webdriver 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 95

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by titusfortner** [comment]
Added it back: 195671ce91808096aa73b4209c2b3c5f5b946d25
Will be available in 4.2
