### ISSUE TITLE
[🐛 Bug]: Selenium cannot interact with Vue framework elements

### ISSUE THREAD

**Issue by GgStormer** [SeleniumHQ/selenium#10151]
### What happened?

Some of the elements under the special symbols on html page such as (for example):
`<!--fragment#176258b1598#head-->`
or:
`<!---->`

are not visible by Selenium. It cannot wait until any element under such symbols is displayed or interact with it.

These symbols are generated directly by Vue js framework.
So it would be great to fix Selenium to work with it.

### How can we reproduce the issue?

```
        WebDriver driver = new ChromeDriver();
        WebDriverManager.chromedriver().setup();
        driver.manage().window().maximize();
        driver.get("https://mamikos.com/");
        WebDriverWait wait = new WebDriverWait(driver, 10);
        WebElement accessibleEl = driver.findElement(By.id("home"));
        WebElement notAccessibleEl = driver.findElement(By.id("loginModal"));
        wait.until(ExpectedConditions.visibilityOf(accessibleEl));
        wait.until(ExpectedConditions.visibilityOf(notAccessibleEl));
```

Expected behavior: Selenium can find both accessibleEl and notAccessibleEl elements.

Actual behavior: it can find only accessibleEl and fails on:
`wait.until(ExpectedConditions.visibilityOf(notAccessibleEl));`

Because notAccessibleEl webelement is under Vue Js fragment in html source code of page.

### Relevant log output

```shell
Step failed
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of [[ChromeDriver: chrome on WINDOWS (6a76b544351ef7665626cc0262f39401)] -> id: loginModal] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EPRUPET', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 96.0.4664.93, chrome: {chromedriverVersion: 96.0.4664.45 (76e4c1bb2ab46..., userDataDir: C:\Users\IGOR_G~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:60019}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 6a76b544351ef7665626cc0262f39401
```

### Operating System

win/linux

### Selenium version

Java 1.8.0_231

### What are the browser(s) and version(s) where you see this issue?

chrome 96.0.4664.93

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver

**Comment by GgStormer** [comment]
Hello! I have found website which uses Vue fragments:
https://mamikos.com/

Updated the issue with extended information.

**Comment by titusfortner** [comment]
This has nothing to do with Vue elements.
The "notAccessibleEl" is literally not visible on the page. It has a height of zero, so a user can't work with it, so Selenium won't let you, either.

You need to click on whatever pops up the login modal and work with the elements displayed in that modal.
