### ISSUE TITLE
[🐛 Bug]: Selenium tests fails on start up when browser is not in foreground

### ISSUE THREAD

**Issue by BhavinMasterM** [SeleniumHQ/selenium#10159]
### What happened?

While executing selenium tests with latest version of selenium, it opens the browser but fails to navigate to website when opened browser is not in the foreground of the screen. For example if we execute the tests through Jenkins on remote desktop, if the remote desktop is opened on local screen in foreground it executes the tests perfectly fine but fails when the remote connection is put in background/minimized. Local execution works fine because for each session it brings the browser in foreground of the screen.

Note: we see a line printed as org.openqa.selenium.remote.ProtocolHandshake createSession for successful execution but it dose not print on failure.

Always it wants the remote machine on focused.

### How can we reproduce the issue?

```shell
Execute the tests(selenium version 4.0.0-rc-1) on remote machine without having the connection to remote machine opened in the local machine.

We have tried the same with latest selenium version 4.0.0.0 for IE and EDGE browsers.
```

### Relevant log output

```shell
It is giving the same error messages mentioned in the issue #10137. 

Due to company security restrictions, we are not allowed to share the log information.
```

### Operating System

Windows 10

### Selenium version

selenium version 4.0.0-rc-1

### What are the browser(s) and version(s) where you see this issue?

IE and IE compatible EDGE browsers

### What are the browser driver(s) and version(s) where you see this issue?

IE driver 4.0.0.0s

### Are you using Selenium Grid?

NA

**Comment by AutomatedTester** [comment]
This is because the browser doesn't have access to a desktop. Since browsers require a GUI to work you will need to make sure one is available on your remote machine.

**Comment by BhavinMasterM** [comment]
@AutomatedTester The browser is available on the remote machine.

**Comment by AutomatedTester** [comment]
I didn't say it wasn't available. I was saying that it sounds like you don't have a Window Manager like X, or XVFB available. For issues like this please use the forum to ask for help on how to set that up properly.

**Comment by BhavinMasterM** [comment]
But the same tests are working fine with older version of selenium.
