### ISSUE TITLE
[🚀 Feature]: Allow to specify HttpOnly attribute when adding new cookie with py bindings

### ISSUE THREAD

**Issue by jacopotediosi** [SeleniumHQ/selenium#10158]
### Feature and motivation

According to WebDriver specification of [Add Cookie](https://www.w3.org/TR/webdriver/#add-cookie) it should be possible to set various cookie attributes. However, constructor of Cookie class in python bindings doesn't have parameters for the HttpOnly one.

https://github.com/SeleniumHQ/selenium/blob/007037c9654f2040f3e28ed508a623f2a54cde11/py/selenium/webdriver/remote/webdriver.py#L1112

Would be great to have them like guys in js do :)

https://github.com/SeleniumHQ/selenium/blob/007037c9654f2040f3e28ed508a623f2a54cde11/javascript/node/selenium-webdriver/lib/webdriver.js#L1615

### Usage example

.

**Comment by titusfortner** [comment]
This was already supported, you just need to add it to the `cookie_dict`.
I added it to the docstring to make it explicit: fe6c1899e43afc824b0b160bd9faf432f70b5b29
