### ISSUE TITLE
[🚀 Feature]: Using Selenium with PowerShell

### ISSUE THREAD

**Issue by lpeder6** [SeleniumHQ/selenium#10154]
### Feature and motivation

PowerShell is a powerful language that is automatically installed and updated on a user's computer that has Windows installed. However, for some reason, there's not a lot of documentation on the use of PowerShell and Selenium. It would be nice to have this as an option to C#, Python, etc., where people could use Selenium with PowerShell. Then, people could use PowerShell and Selenium to utilize all the WebDriver capabilities. 

### Usage example

$ScriptPath = "C:\Users\lpeder6\Documents\PowerShell\Selenium"

Add-Type -Path "$ScriptPath\WebDriver.dll"

$SeleniumOptions = New-Object OpenQA.Selenium.Edge.EdgeOptions

$SeleniumOptions.UseWebSocketUrl = "http://omega2010.uhc.com/Production"

$SeleniumOptions.LeaveBrowserRunning = $true

New-Variable -Name EdgeS -Value ([OpenQA.Selenium.Edge.EdgeDriverService]) -Force
$DefaultService = $EdgeS::CreateDefaultService()

$DefaultService.HideCommandPromptWindow = $true

$Edge = New-Object OpenQA.Selenium.Edge.EdgeDriver -ArgumentList @($DefaultService, $SeleniumOptions)

#This is the same as 'session_id = driver.session_id
$Handle = $Edge.WindowHandles

#Not sure how to use the handle to reuse the URL
$Edge.Navigate().GoToUrl("http://mywebsite.com")

**Comment by AutomatedTester** [comment]
Thank for raising this feature request. We support all options for people to use Selenium. Unfortunately, we don't have the time to document all permutations and APIs for all languages. If you wanted to submit PRs for our Docs we would be very grateful but this would be low on our priority list to do ourselves.
