### ISSUE TITLE
[🐛 Bug]: Selenium is working well under Docker container but not when deployed on cloud

### ISSUE THREAD

**Issue by simonprovost** [SeleniumHQ/selenium#10152]
### What happened?

To begin, we have devised a solution using Selenium that scrapes for the purpose of obtaining some freely available data but is not very expensive in terms of processing. The solution is both locally and dockerized (locally again) working. While we are currently attempting to deploy it utilising AZURE ACR/ACI beneath these docker containers. Things change, the solution ceases to function properly despite the fact that no code changes have been made. Our question is, could you possibly lead us toward creating a good crash log, given what we now have was already there previously (locally on docker / locally on our machine)? Or, if you notice a crash in our traceback, could you direct us to the cause and solution? _Note: We have heard about directly outputting a crash file from the web remote driver, but we could not find any documentation on this; perhaps we missed the good documentation page._

### How can we reproduce the issue?

Using a simple way for scraping data from a web page. Every aspect of the system should be dockerized. See the results of utilising Azure ACR for docker container storage and ACI for obtaining a remote address. What we have noticed is that if we do not do a lot on each page that opens, there is no "crash" However, if we open ten pages and scrape information from each, everything will crash. We initially encountered this issue on Docker locally, as our Docker desktop did not allow for sufficient RAM. However, here we have ten gigabytes of memory and two CPUs available for the selenium grid docker container as well as our Python solution under its docker container.

### Relevant log output

```shell
Everything could be retrieves on this Hastening output log:

https://www.toptal.com/developers/hastebin/imibibepex.apache
```

### Operating System

Azure container Instance under linux ubuntu latest stable version

### Selenium version

Selenium GRID 4.1.0 stable version

### What are the browser(s) and version(s) where you see this issue?

Firefox remove web driver

### What are the browser driver(s) and version(s) where you see this issue?

Firefox version associated with the selenium grid image

### Are you using Selenium Grid?

4.1.0

**Comment by diemol** [comment]
This is very ambiguous. Not sure if you have an actual bug or you are asking a question, in case of the latter, please join us in the [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by titusfortner** [comment]
@diemol do we log crash info to a file?

Not sure what else we can do with this ticket. A non-reproducible "it crashes when we do too much" could be any number of not-Selenium-code related things.

**Comment by diemol** [comment]
Closing as we did not get more information.
