### ISSUE TITLE
[🐛 Bug]: What happened to the Selenium Python API Documentation?

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#10165]
### What happened?

The [![SeleniumPyDocumentation](https://user-images.githubusercontent.com/26503213/146682543-f4f890f6-e7c5-4cd6-9353-3651f40712eb.png)](https://www.selenium.dev/selenium/docs/api/py/api.html#selenium-documentation) seems to have been taken down partially?

Any reason to take it down?

### How can we reproduce the issue?

```shell
Access the [Selenium Python API Documentation](https://www.selenium.dev/selenium/docs/api/py/api.html) link.
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by mgavish** [comment]
Additionally, the pages that are visible are not loading properly.

![image](https://user-images.githubusercontent.com/44953898/146980243-5de3d0c7-5f27-4981-a090-954422302d37.png)

**Comment by PhilippSelenium** [comment]
Also the intersphinx mapping is incomplete: https://www.selenium.dev/selenium/docs/api/py/objects.inv

**Comment by titusfortner** [comment]
Looks like we tried to update Sphinx version and something wasn't happy. I regenerated 4.1 docs with an older version of Sphinx and it looks like it's working now.
