### ISSUE TITLE
[🐛 Bug]: Custom capability not working properly in Selenium 4

### ISSUE THREAD

**Issue by kartick-s** [SeleniumHQ/selenium#10175]
### What happened?

I have one hub with two nodes. First node is having custom capability ("gsg:customcap", true) & the second node is the regular one.
When I'm passing ("gsg:customcap", true) capability in my code, then It gets executed in Node1. But when I'm NOT PASSING the custom capability, then also it gets executed in First node which is not expected.

I want Node1 to take only those session requests which have the custom capability ("gsg:customcap", true).
Please check & suggest.

### How can we reproduce the issue?

```shell
Start the hub and 2 nodes:
java -jar selenium-server-4.1.1.jar hub


A special node(Node1) that supports a custom capability
java -jar selenium-server-4.1.1.jar node --detect-drivers false --driver-configuration display-name="Chrome (custom capability true)" max-sessions=1 stereotype={\"browserName\":\"chrome\",\"gsg:customcap\":true} --port 6161


A regular node(Node2) that doesn't define any custom capabilities
java -jar selenium-server-4.1.1.jar node --detect-drivers false --driver-configuration display-name="Chrome" max-sessions=1 stereotype={\"browserName\":\"chrome\"} --port 6262
```

### Relevant log output

```shell
I expect that when I run the below code, it will be executed only on the second node, but it runs on all 2 of them.

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("browserName","chrome");

WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), capabilities);
driver.get("http://example.com");
Thread.sleep(1000);
driver.quit();
```

### Operating System

Linux(RHEL7)

### Selenium version

selenium-server-4.1.1

### What are the browser(s) and version(s) where you see this issue?

Browser: Chrome , Browser version: 95

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 95

### Are you using Selenium Grid?

4.1.1

**Comment by titusfortner** [comment]
This is working as expected. Your code is what determines what is required.
When your capabilities require a session where the custom capability value is `true` than the hub will only return a node that matches that capability.
When your capabilities don't specify it as a requirement for a session, though, the hub will ignore it when returning a node. 

You probably need to start the other nodes with the custom capability set to `false`, and then have your capabilities require a session where that capability value is `false`.

**Comment by eravion** [comment]
Hello,
In my context, I'll need to define a lot of "false" (at least 20).
And in case I add a new custom-cap, I'll have to add the false version to all nodes.
Could it be possible to have a "false" by default?

**Comment by diemol** [comment]
The current implementation tries its best to handle custom capabilities, but to have a better customization one needs to implement their own https://www.selenium.dev/documentation/grid/configuration/cli_options/#distributor [Slot Matcher](https://github.com/SeleniumHQ/selenium/blob/f8dad5900361653a87fd96a8f3a7fedf3740edf5/java/src/org/openqa/selenium/grid/data/DefaultSlotMatcher.java).

This is because in your case, using `false` is that is needed, but in other cases it might be different.

**Comment by eravion** [comment]
Hello,

My need was to identify a node on a specific network.
As the network is always available on the node configuration, I added an applicationName with this information.
I also added robot name in case I want to point a specific node.

I'm using Ansible to setup the node.

**Extract of ansible inventory**
        node01:
            ansible_host: 'node_ip_address'
            hub_selenium_4_ip: 'hub_ip_address'
            hub_selenium_4_port: '4444'
            node_network: 'node_network'
            node_service_ip: 'node_service_ip (may be different than the ip used to communicate with the hub)'


**node config file : selenium-node_firefox.toml**
[events]
publish = "tcp://{{ hub_selenium_4_ip }}:4442"
subscribe = "tcp://{{ hub_selenium_4_ip }}:4443"

[server]
host = "{{ node_service_ip }}"
port = 5555

[node]
session-timeout = "300"
override-max-sessions = true
detect-drivers = false
max-sessions = 5

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "platformName": "Linux", "version":"{{ node_network }} {{ inventory_hostname }}", "networkname:applicationName":"{{ node_network }}", "nodename:applicationName":"{{ inventory_hostname }}" }'
max-sessions = 5


**Robotframework function to open browser**
!Generic_OpenBrowser
    [Arguments]    ${platform}    ${custom-cap}
    ${capabilities} =    Create Dictionary    platform=${platform}    browserName=firefox    networkname:applicationName=${custom-cap}    
    log    ${capabilities}
    Open Browser    about:blank    remote_url=${remoteURL}     desired_capabilities=${capabilities}
 

This configuration answer to my need.
Hope it can help.

**Comment by diemol** [comment]
Then you need to send `networkname:applicationName` in all your tests.

**Comment by eravion** [comment]
Yes, this is how my test are configured.
Each one have to run on a specific network.
The hub is providing the access to nodes on multiple network.

Previously on selenium 2.53 (old version ...), we were using the browser version on the node config file to identify the network.
With selenium4 it is not possible, the applicationName is perfect for our need.

**Comment by diemol** [comment]
Then please create a new issue with a way to reproduce it and sharing all the logs.

**Comment by eravion** [comment]
To be honest, I don't think it is critical as updating the browser version is not clean.
From my point of view, it is better to explain how to use applicationName to answer to this need.
That's the reason why I shared my configuration.

BTW, if you want, I can create this issue.

**Comment by diemol** [comment]
Nevermind, I will reopen this one and have a look when time permits.

**Comment by diemol** [comment]
I had a look at this and it is working as expected, in separate comments I will show how I configured the Grid.

Addressing the initial post:
```
# Starting the Hub
java -jar selenium-server-4.1.1.jar hub
# Starting Node A
java -jar selenium-server-4.1.1.jar node --detect-drivers false --driver-configuration display-name="Chrome (custom capability true)" max-sessions=1 stereotype='{"browserName":"chrome","gsg:customcap":true}' --port 6161
# Starting Node B
java -jar selenium-server-4.1.1.jar node --detect-drivers false --driver-configuration display-name="Chrome (custom capability false)" max-sessions=1 stereotype='{"browserName":"chrome","gsg:customcap":false}' --port 6262
```

Please not that the custom capability needs to be part of both nodes. Otherwise the node that lacks the custom capability will not be able to match it when a request comes.

Sample code to match Node A:
```java
  ChromeOptions options = new ChromeOptions();
  options.setCapability("gsg:customcap", true);
  WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
  driver.get("https://selenium.dev");
  driver.quit();
```

Sample code to match Node B:
```java
  ChromeOptions options = new ChromeOptions();
  options.setCapability("gsg:customcap", false);
  WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
  driver.get("https://selenium.dev");
  driver.quit();
```

It is really important to always send the custom capability in each single request. If the custom capability is not present in the session request, the Node won't use it in the matching process.

**Comment by diemol** [comment]
Addressing the toml config question, here is a config that works:

```toml
[events]
publish = "tcp://192.168.1.100:4442"
subscribe = "tcp://192.168.1.100:4443"

[server]
host = "192.168.1.100"
port = 5555

[node]
session-timeout = "300"
override-max-sessions = true
detect-drivers = false
max-sessions = 5

[[node.driver-configuration]]
display-name = "firefox"
stereotype = '{"browserName": "firefox", "platformName": "macOS", "browserVersion":"96", "networkname:applicationName":"node_1", "nodename:applicationName":"app_1" }'
max-sessions = 5
```

and to match that Node, the request would look like this:
```java
FirefoxOptions options = new FirefoxOptions();
options.setCapability("networkname:applicationName", "node_2");
options.setCapability("nodename:applicationName", "app_2");
options.setBrowserVersion("96");
options.setPlatformName("macOS");
WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), options);
driver.get("https://selenium.dev");
driver.quit();
```

In the provided toml example in this [comment](https://github.com/SeleniumHQ/selenium/issues/10175#issuecomment-1009733951), the `version` field was not working as it is not a W3C WebDriver standard capability, it needs to be `browserVersion`.

**Comment by diemol** [comment]
Documentation was added for this https://www.selenium.dev/documentation/grid/configuration/toml_options/#setting-custom-capabilities-for-matching-specific-nodes. The code I used to validate this can be seen here https://github.com/diemol/selenium-issues/tree/master/selenium/issue-10175
