### ISSUE TITLE
[🚀 Feature]: Support setting timeouts in capabilities

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10183]
### Feature and motivation

W3C supports adding timeout values when starting a session, which isn't currently implemented in .NET
The existing Timeout classes need to be subclassed or superclassed to make it work correctly, and I'm not sure which one.

### Usage example

Setting timeouts on the driver currently looks like this:
```
driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(2);
```
So I think the API will look like this
```
options.Timeouts().ImplicitWait = TimeSpan.FromSeconds(1);
options.Timeouts().AsynchronousJavaScript = TimeSpan.FromSeconds(1);
options.Timeouts().PageLoad = TimeSpan.FromSeconds(2);
```

**Comment by diemol** [comment]
@titusfortner do you know where the changes need to be made? Perhaps we can describe that a bit and see if someone gets motivated to contribute.

**Comment by titusfortner** [comment]
We had discussed at one point trying to reuse the existing timeouts class logic in the options
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Timeouts.cs

What needed to be subclassed by which wasn't straightforward. TBH, might be best just to add it and the implementation can get fixed later if that matters.

**Comment by titusfortner** [comment]
@nvborisenko do you have any interest in adding this ability to the Options?

It is generally preferred to set timeout values once as part of the capabilities and then not touch them again for the rest of the session.

**Comment by nvborisenko** [comment]
@YevgeniyShunevych do you want help here?

**Comment by nvborisenko** [comment]
Or alternative API like:
```csharp
options.Timeouts.ImplicitWait = TimeSpan.FromSeconds(1); // Timeouts as property
```

Or even simplified:
```csharp
options.ImplicitWaitTimeout = TimeSpan.FromSeconds(1);
```

Last variant is applied in Java binding if I am not mistaking. I would prefer this one too.
