### ISSUE TITLE
[🐛 Bug]: IE Driver GetAttributeValue incorrectly using atom

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10181]
### What happened?

Per spec, using the attribute endpoint should return only the attribute, not the result of the atom.

### How can we reproduce the issue?

```shell
Based on the IE driver code: https://github.com/SeleniumHQ/selenium/blob/trunk/cpp/iedriver/Element.cpp#L572
```

### Relevant log output

```shell
n/a
```

### Operating System

Windows

### Selenium version

trunk

### What are the browser(s) and version(s) where you see this issue?

IE

### What are the browser driver(s) and version(s) where you see this issue?

latest

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
Is this still relevant? Should we report this to the Edge folks who are now maintaining the IE Driver?

**Comment by titusfortner** [comment]
I mean, it's relevant, but probably not high priority.
