### ISSUE TITLE
Update JS API Docs

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10185]
### Feature and motivation

Last update was for Selenium 4 alpha

### Usage example

This page should stay up to date:
https://seleniumhq.github.io/selenium/docs/api/javascript/index.html

**Comment by titusfortner** [comment]
So I believe we need to update to JSHint/typedoc to get this working again?

**Comment by kupietools** [comment]
Not knowledgeable enough to contribute to documentation, but as a new Selenium user, the need for JS API documentation is a big one. At the very least, update the wiki so it doesn't claim there is documentation and then direct users to a 404 page. Thanks.

**Comment by diemol** [comment]
@kupietools it is a good idea to mention that in the wiki. 

We will try to work on this in the next release.

**Comment by kupietools** [comment]
@diemol Thanks. I've never used github's wiki features before except to glance at on occasion, where in the wiki would I be able to leave comments like that? I don't even see a clear way to edit the pages.

**Comment by diemol** [comment]
I left that as a note for me, @kupietools.

**Comment by diemol** [comment]
https://www.selenium.dev/selenium/docs/api/javascript/

**Comment by kupietools** [comment]
Thanks so much!
