### ISSUE TITLE
[🚀 Feature]: Possibility to reduce stacktrace from WebDriverWait

### ISSUE THREAD

**Issue by VladimirPodolian** [SeleniumHQ/selenium#10195]
### Feature and motivation

I wanna have possibility to reduce stacktrace output from `WebDriverWait.until` due to long output (see picture). I can create an PR, but need approve of idea.
<img width="1163" alt="SM" src="https://user-images.githubusercontent.com/36446855/147622605-34985b2d-22a7-4ec1-91aa-8400c5458d42.png">

### Usage example

```python
def until(self, method, message='', capture_stacktrace=True)
    ...
    if capture_stacktrace:
        stacktrace = getattr(exc, 'stacktrace', None)
    ...
```

**Comment by titusfortner** [comment]
I don't think this is Selenium's responsibility and that the Google team needs to address this, but as I mentioned in the PR, I'll discuss the toggle option with other team members.

**Comment by diemol** [comment]
During the most recent TLC meeting, the team decided that Selenium should not truncate a browser driver's output. In this particular case, this should be raised to the ChromeDriver team. @VladimirPodolyan @titusfortner do you know if there is an issue for this already?

https://www.selenium.dev/meetings/2022/tlc-01-19/#truncate-unnecessary-portions-of-the-stack-trace-returned-by-recent-versions-of-chromedriver
