### ISSUE TITLE
[🐛 Bug]: C#-Selenium.WebDriver 4.1.0-AddAdditionalOption& AddAdditionalCapability method are not working properly

### ISSUE THREAD

**Issue by fescobar** [SeleniumHQ/selenium#10192]
### What happened?

I'm trying to upgrade my `Selenium.WebDriver` from `3.141.0` to `4.1.0` version in C# DOTNET 5
With version `3.141.0` I used to create an object of `DesiredCapabilities` to setting up different capabilities 

```sh
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("browser", "chrome");
capabilities.SetCapability("browserstack.user", "MY USER");
capabilities.SetCapability("browserstack.key", "MY KEY");
IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), capabilities);
```
and I got something like this received for the Selenium Grid or any other tool like BrowserStack:
```sh
{
  "browserName":"chrome",
  "browserstack.user":"MY USER",
  "browserstack.key":"MY KEY"
}
```
* NOTE ALL THE ATTRIBUTES ARE IN THE JSON ROOT. This json is read it by BrowserStack without any issue.

I know you changed the visibility of the class `DesiredCapabilities`, that is the reason I can not use it anymore.

I was checking some info about this change https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#addadditionalcapability-is-deprecated and it's recommended to use `AddAdditionalOption`

When I implemented the suggested code
```sh
  var opts = new ChromeOptions();
  opts.AddAdditionalOption("browserstack.user", "MY USER");
  opts.AddAdditionalOption("browserstack.key", "MY KEY");
  IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), opts.ToCapabilities());
```
I'm not getting those options in the JSON received in the Grid. The additional options appear when I debug the `opts` variable but those values are not sent to the Grid Server.

```sh
{
  "browserName":"chrome",
  "goog:chromeOptions":{
    
  }
}
```
The issue I'm having it's because those additional options are required for BrowserStack (for Authentication and specify browsers/devices)

That is the reason my test fails when I use BrowserStack. 
I know there is a deprecated method like `AddAdditionalCapability `

```sh
var opts = new ChromeOptions();
opts.AddAdditionalCapability("browserstack.user", "MY USER", true);
opts.AddAdditionalCapability("browserstack.key", "MY KEY", false);

IWebDriver driver = new RemoteWebDriver(
new Uri("http://localhost:4444/wd/hub"), opts.ToCapabilities());
```
but the same it's not working properly, I'm getting the next json in the grid server

```sh
{
  "browserName":"chrome",
  "goog:chromeOptions":{
    "browserstack.key":"MY KEY"
  }
}
```
NOTE the `browserstack.key` ATTRIBUTE IS NOT IN THE ROOT JSON, WHERE IS EXPECTED FOR THE BS TOOL.

1. Is this an issue? with the new version, are you planning don't allow the users to put additional options in the root?
2. All the cloud tools should have their own specific capabilities as a child in the JSON?
3. `AddAdditionalCapability ` deprecated method, should be working as same as before even with the new version?
4. Should BrowserStack and other tools instead of reading the BS capabilities from the root should read from something like this `bstack:options`

Thank you in advance.

### How can we reproduce the issue?

```shell
Check the next 2 test cases using the new method `AddAdditionalOption` and the deprecated method `AddAdditionalCapability`


using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;

namespace QAAutomationCore.Test
{
    class SeleniumTest
    {
        [Test]
        public void checkAddAdditionalOption()
        {
            IWebDriver driver = null;
            try
            {
                var opts = new ChromeOptions();
                opts.AddAdditionalOption("browserstack.user", "MY USER");
                opts.AddAdditionalOption("browserstack.key", "MY KEY");

                driver = new RemoteWebDriver(
                    new Uri("http://localhost:4444/wd/hub"), opts.ToCapabilities()
                );
            }
            finally {
                if (driver != null) {
                    driver.Quit();
                }
            }
        }


        [Test]
        public void checkAddAdditionalCapability()
        {
            IWebDriver driver = null;
            try
            {
                var opts = new ChromeOptions();
                opts.AddAdditionalCapability("browserstack.user", "MY USER", true);
                opts.AddAdditionalCapability("browserstack.key", "MY KEY", false);

                driver = new RemoteWebDriver(
                    new Uri("http://localhost:4444/wd/hub"), opts.ToCapabilities()
                );
            }
            finally
            {
                if (driver != null)
                {
                    driver.Quit();
                }
            }
        }

    }
}
```

### Relevant log output

```shell
Logs are shown in the description.
```

### Operating System

WINDOWS 10 PRO / DOTNET 5

### Selenium version

C#-Selenium.WebDriver 4.1.0

### What are the browser(s) and version(s) where you see this issue?

CHROME 96.0

### What are the browser driver(s) and version(s) where you see this issue?

96

### Are you using Selenium Grid?

4.1.0 (revision 87802e897b) & BrowserStack

**Comment by titusfortner** [comment]
BrowserStack wants you to create a Dictionary and pass it in to `bstack:options`

See here for specific code examples: https://www.browserstack.com/automate/capabilities?tag=selenium-4

**Comment by fescobar** [comment]
@titusfortner BS is just an example. I use other tools like Selenoid where you need to pass parameters in the json root. Then, they should update those tools too? By compatibility Selenium4 should support that too?


For example, selenoid requires a capability named  `enableVNC: true`, but that is not working because that capability is not in the root because `AddAdditionalCapability` is not working properly. Please check that.
https://aerokube.com/selenoid/latest/#_live_browser_screen_enablevnc

**Comment by titusfortner** [comment]
W3c compliant needs to have vendor namespacing, which means if it isn't one of the 10 listed in the spec, it needs to have a colon.

**Comment by fescobar** [comment]
@titusfortner Ok, thank you so much for the explanation.
