### ISSUE TITLE
[🐛 Bug]: 'Open new tab' feature doesn't work when browser runs in 'incognito' mode

### ISSUE THREAD

**Issue by sagui14** [SeleniumHQ/selenium#10201]
### What happened?

I was trying to open a new tab with Selenium 4.1.1: driver.switchTo().newWindow(WindowType.TAB);
This command doesn't work when the browser starts in Incognito mode

### How can we reproduce the issue?

```shell
start browser in incognito mode
load any url
try to open a new tab with above command
```

### Relevant log output

```shell
org.openqa.selenium.WebDriverException: unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
```

### Operating System

Windows 10

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

96.0.4664.45

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
I can reproduce this issue, but there's nothing that can be done in the Selenium codebase about it. Selenium is sending the correct information to the driver, but the driver is not able to handle it.

**Comment by sagui14** [comment]
Hi

Thanks for prompt reply.
So, are there any action items or this situation will stay as is?

Regards,
Sagui

**Comment by titusfortner** [comment]
You can create an issue with the ChromeDriver team:
https://bugs.chromium.org/p/chromedriver/issues/list

I checked already that there isn't one already open. They haven't been the most responsive to issues recently, though. Can you open a new window with JS and switch to it (i.e., is it just the new window command that's a problem, or is it any window switching).
