### ISSUE TITLE
2.47.1 release on npm

### ISSUE THREAD

**Issue by aullman** [SeleniumHQ/selenium#1021]
When is there going to be a 2.47.1 release on npm? I'm waiting for it so that Firefox > 37 can work again with directConnect.

https://github.com/SeleniumHQ/selenium/issues/437
https://github.com/angular/protractor/issues/2134

**Comment by doctyper** [comment]
I'm blocked here as well.

**Comment by davidlehn** [comment]
A new selenium-webdriver release to npm would also fix node 4.x support.

**Comment by mekdev** [comment]
+1 for node 4.x support :)

**Comment by ddavison** [comment]
@jleyba

**Comment by jleyba** [comment]
Bumped to 2.47.0 in c71d126bb24fa11b78cd0b0ce8a479940ba5a9e3.

Package has been pushed to npm.
