### ISSUE TITLE
[🐛 Bug]: Shadowroot for geckdriver

### ISSUE THREAD

**Issue by renanllisboa** [SeleniumHQ/selenium#10217]
### What happened?

Is there a possible implementation of shadowroot method in geckodriver that can be use shadow_root webdriver method like as in Chromium webdriver like chomedriver?

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOpt

webdriver = webdriver.Firefox()

webdriver.get('http://localhost:2018/')

element = webdriver.execute_script("return document.querySelector('wa-combobox')")

element.shadow_root
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/TOTVS/workspaces/workspace_scripts/shadow_dow_selenium4/test_selenium_script.py", line 15, in <module>
    element.shadow_root
  File "C:\TOTVS\venv\venv01\lib\site-packages\selenium\webdriver\remote\webelement.py", line 556, in shadow_root
    assert self._parent.caps["browserName"].lower() not in ["firefox", "safari"], "This only currently works in Chromium based browsers"
AssertionError: This only currently works in Chromium based browsers
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 95.0.2

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.30.0

**Comment by titusfortner** [comment]
This is something that Mozilla needs to implement in the Firefox/Marionette/Geckodriver code, not something in the Selenium code.

@AutomatedTester has put a lot of time into making it work there; is there an issue for tracking the status of this?

**Comment by titusfortner** [comment]
Getting Shadow Root appears to be in Nightly now:
https://hg.mozilla.org/mozilla-central/rev/1b281ca3301b

But finding elements in the root is not yet
https://bugzilla.mozilla.org/show_bug.cgi?id=1700095

Can track support for that here — https://wpt.fyi/results/webdriver/tests/find_element_from_shadow_root

**Comment by renanllisboa** [comment]
Thanks @titusfortner , so before implement these methods in selenuim, we must wait for mozilla/geckdriver team work on it.

**Comment by titusfortner** [comment]
Everything is implemented in Selenium. As soon as there is a driver /browser released that supports it, this functionality will just work.

**Comment by renanllisboa** [comment]
Thanks for your attention and support @titusfortner . have a nice day.
