### ISSUE TITLE
[🐛 Bug]: action_builder.ActionBuilder.add_wheel_input throws TypeError

### ISSUE THREAD

**Issue by colons** [SeleniumHQ/selenium#10210]
Calling `ActionBuilder.add_wheel_input()` will always throw a `TypeError`. There are no tests or docs that I can see, so I'm unsure whether to remove the `kind` argument from `add_wheel_input` or add it to `WheelInput.__init__()`. This appears to have been the case since [it was introduced](https://github.com/SeleniumHQ/selenium/commit/122c9f9feaa69a3d052858c307f86e3cb37e85b4).

### How can we reproduce the issue?

You can reproduce the `TypeError` without even creating a `WebDriver` instance by doing:

```python
>>> from selenium.webdriver.common.action_chains import ActionChains
>>> ActionChains('').w3c_actions.add_wheel_input('', '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../selenium/webdriver/common/actions/action_builder.py", line 77, in add_wheel_input
    new_input = WheelInput(kind, name)
TypeError: __init__() takes 2 positional arguments
```

**Comment by symonk** [comment]
@AutomatedTester should `kind` as an arg be dropped here? not familiar with the code but from a quick check it's largely unused
