### ISSUE TITLE
[🐛 Bug]: Chrome WebDriver service argument unexpected

### ISSUE THREAD

**Issue by whwotjd9090** [SeleniumHQ/selenium#10226]
### What happened?

i try

```
chrome_service: Service = Service(executable_path=chrome_driver_path)
chrome_driver: WebDriver = WebDriver(service=chrome_service, options=chrome_opt)
```

pycharm warning apper : Unexpected argument on service parameter

### How can we reproduce the issue?

```shell
import chromedriver_autoinstaller
from selenium.webdriver.chrome.webdriver import WebDriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service


chrome_driver_path = chromedriver_autoinstaller.install()

chrome_opt: Options = Options()
chrome_opt.add_argument("--incognito")

chrome_service: Service = Service(executable_path=chrome_driver_path)

chrome_driver: WebDriver = WebDriver(service=chrome_service, options=chrome_opt)
chrome_driver.get('https://www.python.org/')
chrome_driver.close()
```

### Relevant log output

```shell
Unexpected argument
```

### Operating System

Windows 10

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 97

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.71

![error](https://user-images.githubusercontent.com/44334543/148430320-af6c4e70-446f-443d-ba2f-04da9621d9ed.png)

**Comment by titusfortner** [comment]
`chromedriver_autoinstaller.install()` should put the driver on `PATH` not output a path String, so you don't need to use a service class.

On the other hand, if you use `webdriver_manager` (https://github.com/SergeyPirogov/webdriver_manager)
You need to do: 
```py
Service(executable_path=ChromeDriverManager().install())
```

**Comment by whwotjd9090** [comment]
thank you!
But WebDriver's executable_path is deprecated argument. So i want to use service argument with Service class, how can i do?

**Comment by titusfortner** [comment]
That is the service class.

Look, I just redid this documentation of the 3 ways to do drivers: https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#three-ways-to-use-drivers

one library is setting it on path, the other is setting it somewhere that can be used with Service class
