### ISSUE TITLE
Authentication using RemoteWebDriver

### ISSUE THREAD

**Issue by RemiNV** [SeleniumHQ/selenium#1022]
In the current WebDriver version, authentication cannot be configured using the RemoteWebDriver (see http://stackoverflow.com/questions/32365872/ntlm-authentication-in-selenium-remotewebdriver). The only way to configure it is by overriding the modifyWebClient method of the HtmlUnitDriver, which is not available when using the RemoteWebDriver.

As a result, .NET projects have no way to use Selenium if they require authentication.

I have created the following branch to solve this issue:
https://github.com/RemiNV/selenium/tree/feature-webdrivercredentials

Basically, you can now configure authentication just like you configure proxies; example in .NET:

```
var capabilities = DesiredCapabilities.HtmlUnitWithJavaScript();
var credentials = new WebDriverCredentials() {
    Type = AuthType.NTLM,
    Username = "username",
    Password = "password",
    NtlmDomain = "domain"
};

capabilities.SetCapability("credentials", credentials);
var driver = new RemoteWebDriver(capabilities);
```

This only works with HtmlUnit (I guess configuring the other browsers may not be that easy).

It works as I want it to, and I would like to open a pull request. However, before I spend time writing unit tests and updating the documentation, I would like to know if this is likely to be merged in the main branch, or if you see a problem with my approach/other things missing in my branch. Any thoughts ?

**Comment by jimevans** [comment]
Given that the .NET bindings have implemented an authentication method as part of the `IAlert` interface, I'm not entirely sure introducing multiple ways of accomplishing the same thing is the best approach. I haven't had time to fully evaluate the proposal though.

**Comment by RemiNV** [comment]
I understand the concern; would the IAlert concept be also usable with HTMLUnit (without any UI) and through the RemoteWebDriver (which is the only way to run HTMLUnit in .NET) ? I thought not, which is why I worked on this. I also thought that being able to configure default credentials would be useful.

**Comment by barancev** [comment]
Selenium is following the W3C WebDriver standard [1] now, and we're waiting for the corresponding issue [2] on the standard to be resolved. We hardly will merge an alternative implementation so I'm going to close the issue. If you think that this approach is more vital please comment on the issue [2].

[1] https://w3c.github.io/webdriver/
[2] https://github.com/w3c/webdriver/issues/385
