### ISSUE TITLE
[🐛 Bug]: In Edge(IE mode), I'm not able to enable pop-ups 

### ISSUE THREAD

**Issue by hendryang** [SeleniumHQ/selenium#10221]
### What happened?

Hi Folks, I've tried couple ways to enable pop ups via ieOptions/edgeOptions but still it's getting blocked. Appreicate any help on this. Thanks for your time.

Please refer to below snippet:

```
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.ignoreZoomSettings();
        ieOptions.setCapability("ignoreProtectedModeSettings", true);
        ieOptions.attachToEdgeChrome();
        ieOptions.setCapability("disable-popup-blocking", true);  // doesn't work
        ieOptions.setCapability("--disable-popup-blocking", true);  // doesn't work
        
        EdgeOptions edgeOptions = new EdgeOptions();
        HashMap<String, Object> edgePref = new HashMap<>();
        edgePref.put ( "profile.default_content_setting_values.popups" , true); // doesn't work with 0,1,false,true
        edgeOptions.setExperimentalOption("prefs" , edgePref);
        edgeOptions.addArguments("disable-popup-blocking"); // doesn't work

        ieOptions.merge(edgeOptions);
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        driver = new InternetExplorerDriver(ieOptions);
```

### How can we reproduce the issue?

```shell
Execute the snippet code, Edge Browser with IE mode will spin up and access any site with pop ups. All pops up will get blocked , unless I manually allow it.
```

### Relevant log output

```shell
N/A . No logs, however below is sample print out from `ieOptions.getCapabilities()`

[--disable-popup-blocking, browserName, disable-popup-blocking, ie.edgechromium, ie.edgepath, ignoreProtectedModeSettings, ignoreZoomSetting, se:ieOptions]
```

### Operating System

Windows 10

### Selenium version

4.1.1 selenium-java

### What are the browser(s) and version(s) where you see this issue?

IEDriver 4.0.0 , Edge 95 , IE 11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.0.0 , Edge 95 , IE 11

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
disabling popup blocking is not supported as an option in IE, so it isn't available in IE mode for Edge, either. 
There is a registry key that works for IE, but I'm not sure about Edge with IE Mode.
You can read more here: https://github.com/SeleniumHQ/selenium/issues/8868#issuecomment-978217729
