### ISSUE TITLE
[🐛 Bug]: Cannot cast shadow root element to an IWebElement in version 96+

### ISSUE THREAD

**Issue by Sckye** [SeleniumHQ/selenium#10227]
### What happened?

This only started happening with ChromeDriver version 96.  In C#, when executing a JS command to get the shadow root element and then casting it to an IWebElement, it throws an exception of:

**System.InvalidCastException: 'Unable to cast object of type 'OpenQA.Selenium.ShadowRoot' to type 'OpenQA.Selenium.IWebElement'.'**

### How can we reproduce the issue?

```shell
`var shadowRootElement = (IWebElement) driver.ExecuteScript("return arguments[0].shadowRoot", element);`
```

### Relevant log output

```shell
**System.InvalidCastException: 'Unable to cast object of type 'OpenQA.Selenium.ShadowRoot' to type 'OpenQA.Selenium.IWebElement'.'**
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver v96

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
You should use `GetShadowRoot()` in Selenium 4.1 instead of executing a script.
The interface is going to be `ISearchContext` not `IWebElement`

I explained what all is going on here: https://titusfortner.com/2021/11/22/shadow-dom-selenium.html

**Comment by Sckye** [comment]
Thank you for the quick response.  It did not initially solve my problem because I really needed it to be returned as an IWebElement (and not an ISearchContext), which was possible in v95 and below.
But I implemented a workaround so all is good now.  Thanks~

**Comment by udifaintuch** [comment]
@Sckye can you please share here your workaround.
I also need it to be IWebElement and not ISearchContext

**Comment by Sckye** [comment]
@udifaintuch Sure thing.  Here are the steps:

1. After getting the ISearchContext for the ShadowRoot, find any child element using XPath selector `./*`
2. Once you have the child element, get its parent element (which is the same element as the shadow root) using selector `.//parent::*`
