### ISSUE TITLE
[🐛 Bug]: Selenium 4.1.0 failed to obtain webdriver instance for Chrome, Edge and Safari on macOS (M1)

### ISSUE THREAD

**Issue by zhongdongy** [SeleniumHQ/selenium#10234]
### What happened?

When trying to obtain the webdriver instance using Python `3.10` (Selenium `4.1.0`) on macOS Big Sur (`11.6`) **Apple Silicon**, Selenium raises an exception, but the message only includes a line break "\n". 

Confirmed browsers that have this issue:
- Safari: version `15.2 (16612.3.6.1.8, 16612)`
- Microsoft Edge stable: `97.0.1072.55`, driver version: `97.0.1072.55 (ce3bf3364880558d4945082f4ac36e01fe36716e)`
- Microsoft Edge canary: `99.0.1127.0`, driver version: `99.0.1127.0 (66f7d37d5932c101d04eac8b872ec520160c21ff)`
- Google Chrome stable: `97.0.4692.36` driver version: `97.0.4692.36 (747e0a0f19c13ca6ee136200f5b097448ae4892f-refs/branch-heads/4692@{#607})`

However, the same example codes works just fine on Linux systems (`x86_64`)

### How can we reproduce the issue?

```shell
1. Install web browser (Microsoft Edge): 97.0.1072.55
2. Install web driver of the same version: 97.0.1072.55
3. Run this code (Python 3.10 and Selenium 4.1.0)

from selenium.webdriver import Edge

try:
    exec_path = "/Users/zhongdongy/Libs/msedgedriver"
    driver = Edge(exec_path)
    print(driver)
    driver.get('https://bing.com')
except Exception as e:
    print(e)
    exit(1)
```

### Relevant log output

```shell
The exception only includes one "\n" in exception message.

![Screenshot of exception in PyCharm debugger](https://i.stack.imgur.com/NeWIM.png)
```

### Operating System

macOS Big Sur

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge 97, Edge 99, Chrome 97, Safari 15.2

### What are the browser driver(s) and version(s) where you see this issue?

Edge 97.0.1072.55, Edge 99.0.1127.0, Chrome 97.0.4692.36

### Are you using Selenium Grid?

No

**Comment by zhongdongy** [comment]
Sorry the contents are kind of messed up in the "how to reproduce" and "log output" sections. 

I tried the same code with same versions of Chrome and Edge on Linux (`x86_64`) and got no issue. But on macOS, all versions of chromium based browsers provide a universal binary (both `x86_64` and `arm64`), while the web drivers (even canary channel) only provide `x86_64` arch. I suspected this was the cause but how come Safari also failed with the same exception?

**Comment by titusfortner** [comment]
I'm not sure the drivers issue, I'm seeing m1/arm64 options in the download locations:

http://chromedriver.storage.googleapis.com/index.html?path=97.0.4692.71/
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

You could consider using webdriver_manager package, which should automatically provide the correct driver (but I haven't tested it on M1).

The Safari driver is built into the OS, so it shouldn't be giving an error.

Your code should be giving you deprecation warnings. In Selenium 4 you want to do:

```py
    service = Service(executable_path="/path/to/chromedriver")

    driver = webdriver.Chrome(service=service)
```

Try the code above and provide a full stack trace instead of rescuing the error.

**Comment by zhongdongy** [comment]
Thanks @titusfortner, I'll try chromewebdriver for mac M1 and see if the issue still exists. But the arm64 option from Microsoft Edge website is actually an `exe` executable, looks like it's for Windows distributions.

**Comment by zhongdongy** [comment]
> ```shell
> from selenium.webdriver import Edge
> 
> try:
>     exec_path = "/Users/zhongdongy/Libs/msedgedriver"
>     driver = Edge(exec_path)
>     print(driver)
>     driver.get('https://bing.com')
> except Exception as e:
>     print(e)
>     exit(1)
> ```

Hi @titusfortner, thanks again for the advice, but even with chromewebdriver for M1, same issue still occurs, here's the traceback (Google Chrome):

```python
Traceback (most recent call last):
  File "/Users/zhongdongy/Workspace/repos/py-media-tools/test.py", line 9, in <module>
    driver = Chrome(service=Service(executable_path=exec_path))
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 211, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
 # This is a line break of exception message
```

Updated code:
```python
from traceback import print_exception

from selenium.common.exceptions import WebDriverException
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.service import Service

try:
    exec_path = "/Users/zhongdongy/Libs/chromedriver"
    driver = Chrome(service=Service(executable_path=exec_path))
    print(driver)
    driver.get('https://bing.com')
except Exception as e:
    print_exception(WebDriverException, e, e.__traceback__)
```

Executables:
```
Chrome: Version 97.0.4692.71 (Official Build) (arm64)
ChromeDriver: 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247})
Driver arch: /Users/zhongdongy/Libs/chromedriver: Mach-O 64-bit executable arm64
```
---
I've also got stack trace info for Safari (only changed `Chrome` to `Safari` in the source code and updated the imports):
```python
Traceback (most recent call last):
  File "/Users/zhongdongy/Workspace/repos/py-media-tools/test.py", line 10, in <module>
    driver = Safari()
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/safari/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/Users/zhongdongy/.conda/envs/py-media-tools/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 211, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: 
 # This is a line break of exception message
```

**Comment by titusfortner** [comment]
The `WebDriverException` isn't giving any other message? I can't tell if your code is obscuring information with the exception handling.

**Comment by zhongdongy** [comment]
> The `WebDriverException` isn't giving any other message? I can't tell if your code is obscuring information with the exception handling.

No, there is nothing else in the exception message, just a '\n' character, which is very strange because I can't find anyone posting same behavior. And are you suggesting to remove try...except... and let Python interpreter print the error message and stack trace to console?

**Comment by titusfortner** [comment]
yes, that's what I'm suggesting, but I don't know if it will provide any more information as Python isn't my main language. I can't think of a reason for why both safaridriver and chromedriver would be giving you the same error when starting a session with the code you provided.

**Comment by titusfortner** [comment]
@zhongdongy were you able to figure out a solution?

**Comment by zhongdongy** [comment]
> @zhongdongy were you able to figure out a solution?

Sorry I couldn't find a solution yet. I'll keep you updated once got any clue or solution.

**Comment by SinghHrmn** [comment]
@zhongdongy I'm using 
- Macbook Pro `M1 chip` macOS `Monterey` 12.2.1
- `Edge 99.0.1150.55` (Official build) (arm64) [Drivers](https://msedgedriver.azureedge.net/99.0.1150.55/edgedriver_mac64.zip)
- Python 3.10
- Selenium 4.1.0

Apart from `Big Sur` I followed everything but `couldn’t reproduce this issue`.
running the following code 

```python
from traceback import print_exception

from selenium.common.exceptions import WebDriverException
from selenium.webdriver import Chrome, Safari, Edge
from selenium.webdriver.chrome.service import Service

try:
    exec_path = "/Users/harmandeepsingh/Downloads/edgedriver_mac64/msedgedriver"
    driver = Edge(service=Service(executable_path=exec_path))
    print(driver)
    driver.get('https://bing.com')
except Exception as e:
    print_exception(WebDriverException, e, e.__traceback__)
```
resulted in 
```zsh
<selenium.webdriver.edge.webdriver.WebDriver (session="f16026cf82bf54e9f8c1fe5e964a61d0")>
```

 However I dig into the selenium 4.1.0 code and it seems the issue of empty message `Message: \n` is coming from `ErrorHandler` class in `lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py` 

Can you please run the code in debug mode for this file? 
And see how the values change for 
- `value`
- `message`
- `exception_class`

That will help in better understanding of the root cause

**Comment by titusfortner** [comment]
do not have enough information to continue troubleshooting this at this time.
