### ISSUE TITLE
[🐛 Bug]: With Chromedriver 97 / Python, unable to find elements within shadow-root parent element

### ISSUE THREAD

**Issue by DimaEdunov** [SeleniumHQ/selenium#10237]
### What happened?

Once using the latest chrome-driver version = 97, I have an issue with shadow root elements.
Once finding the shadow-root element on the DOM, I want to look up an element inside the shadow-root element.

Starting from version 97, this is not possible, and exception is thrown,
few days ago while using version 96, all worked fine

### How can we reproduce the issue?

```shell
(Python)

In the previous version, chrome-driver = 96, I could do the following thing :
shadow_root = self.driver.execute_script('return arguments[0].shadowRoot',self.driver.find_element_by_tag_name(SocialElements.SOCIAL_SHADOW_ROOT_PARENT_ELEMENT))                                               

shadow_root.find_element_by_css_selector("i[class*='social-icon-dots']").click()

BUT, on version 97, I'm getting an exception:
"AttributeError: 'ShadowRoot' object has no attribute 'find_element_by_css_selector'"
```

### Relevant log output

```shell
E       AttributeError: 'ShadowRoot' object has no attribute 'find_element_by_css_selector'
```

### Operating System

Windows 10

### Selenium version

Python - Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 97.0.4692.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.71

### Are you using Selenium Grid?

No, pytest has parallel execution within its framework

**Comment by SunMarc** [comment]
@DimaEdunov I had the same issue but I was able to solve it by using `shadow_root.find_element(By.CSS_SELECTOR,"i[class*='social-icon-dots']")` . Hope it works for you :)

**Comment by diemol** [comment]
Thank you for replying, @SunMarc. That is accurate.

@DimaEdunov please follow the fix show above.

**Comment by DimaEdunov** [comment]
Works like a charm,
@SunMarc , @diemol - Thanks, guys.

ain't no automation, like Selenium automation, Yii-ha (-:
