### ISSUE TITLE
[🚀 Feature]: Update doc to add `sendAndGetDevToolsCommand`

### ISSUE THREAD

**Issue by compulim** [SeleniumHQ/selenium#10240]
### Feature and motivation

On this page for Chromium-only WebDriver definition, it only listed `sendDevToolsCommand`.

https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Driver.html

It should also add `sendAndGetDevToolsCommand`, which is from [this commit](https://github.com/SeleniumHQ/selenium/commit/8735ef954c9ed0100e7bba48b5c1cd8e2e6a793e).

As pointed out from [this issue](https://github.com/SeleniumHQ/selenium/issues/8764), may also be great to update the doc to explicitly point out that the `sendDevToolsCommand` will not get a return value, developer will need to call `sendAndGetDevToolsCommand` if a return value is expected.

### Usage example

`sendDevToolsCommand` is great, but it is not obvious that this command is unidirectional (no return value).

There is a newer `sendAndGetDevToolsCommand` which is bidirectional. However, it is not documented properly.

I believe if the `sendAndGetDevToolsCommand` is documented properly, there will be an uptick of developers using this new command instead of the original `sendDevToolsCommand`.

For example, we can use the new `sendAndGetDevToolsCommand` to snapshot the accessibility tree of the page:

```js
await webDriver.sendDevToolsCommand('Accessibility.enable');

const { nodes } = await webDriver.sendAndGetDevToolsCommand('Accessibility.getFullAXTree');

console.log(nodes); // Snapshot of AXNode tree
```

**Comment by SinghHrmn** [comment]
@compulim Thanks for your contribution. 

It looks like the API document generator is broken and it has been a while since new docs have been generated. @harsha509 and I are looking into how to resolve this issue. 

We use `js-dossier` to generate docs which is not being maintained anymore so we are looking into alternatives for that. Once fixed we'll update this thread.

**Comment by rrfaria** [comment]
it is also missing in typescript 
looking fast is missing file with chromium types
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/selenium-webdriver

**Comment by SinghHrmn** [comment]
@rrfaria The typescript stuff is on list of works to be done. It will soon be updated.  Thanks.
