### ISSUE TITLE
[🐛 Bug]: Impossible to use CDP via WS or HTTP with Selenium 4.x

### ISSUE THREAD

**Issue by Mecanik** [SeleniumHQ/selenium#10243]
### What happened?

For the last few days me and other people have been trying to use CDP commands via Selenium, however nothing seems to function as expected. Selenium always returns "se:cdp": "ws://" instead of HTTP - that's problem 1, and problem 2 is that even trying to communicate via ws:// Selenium never returns anything, it just gets stuck.  If you do send "bad" or "missing" parameters Selenium will return an error message, but if you do send a "correct" command, nothing will happen.

I would like to focus only on problem 2 which is the ws:// cdp usage, since I spent several days to try and use HTTP without success.

Please note that I have ensured and triple checked and tested several variations of Chrome + ChromeDriver.

### How can we reproduce the issue?

```shell
Try to communicate via ws://, send the following test: {"id":123213123,"sessionId":"975cefdf3e55bc59341ec6a3f9564216","method":"Network.setUserAgentOverride","params":{"userAgent":"banana","acceptLanguage":"minion world","platform":"apple"}} - nothing will happen.
```

### Relevant log output

```shell
Nothing, unfortunately. No error, no output, absolutely nothing.
```

### Operating System

Windows 10

### Selenium version

Java version "1.8.0_311"

### What are the browser(s) and version(s) where you see this issue?

Chrome 96.0.4664.110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 96.0.4664.110

### Are you using Selenium Grid?

4.1.1

**Comment by diemol** [comment]
What code can we use to reproduce the issue?

**Comment by Mecanik** [comment]
> What code can we use to reproduce the issue?

I used C++ and also web client but the result will be the same (I believe) using any code. Try to send that data via ws:// and see nothing happens.

**Comment by diemol** [comment]
I am using the Selenium bindings and things work as expected, not sure what approach you are using but we have all these examples that work https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/

**Comment by diemol** [comment]
Closing as we did not get any more information.
