### ISSUE TITLE
[🐛 Bug]: Adding CDP listener results in Connection pool is full errors

### ISSUE THREAD

**Issue by ManiMozaffar** [SeleniumHQ/selenium#10259]
### What happened?

whenever I'm using CDP listener with the undetected driver, on the new version, I'm getting this error after adding a few listeners:
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost

By adding a CDP listener, a few times in a row, with 3 seconds interval between each, it'll keep the errors shown above on the terminal. It was running fine on previous versions, however, the previous version was detected by Cloudflare, so using them is not an option for me. I guess the reason is that the CDP connection made will not be closed after they ran completely.

### How can we reproduce the issue?

```shell
driver.add_cdp_listener('Network.requestWillBeSent', self.get_header)
I should also mention that the method get_header usually finishes in less than mili seconds.
```

### Relevant log output

```shell
Python 3.9.9
undetected-chromedriver 3.1.3
selenium 4.1.0

-------------
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
```

### Operating System

Macos & windows 10

### Selenium version

Python 4.1

### What are the browser(s) and version(s) where you see this issue?

Chrome v96

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver v96

### Are you using Selenium Grid?

No

**Comment by ManiMozaffar** [comment]
so far I've readen the source code, If I'm not wrong, the problem is that the connection to the localhost's pool should increase in order to solve this problem. I noticed 2 connection, that could be related to cdp add listen eventer.

Line 1582, webdriver\remote\webdriver.py
```
def _get_cdp_details(self):
        import json
        import urllib3
        ## It was this:
        http = urllib3.PoolManager()
        ## Changed to this:
        http = urllib3.PoolManager(num_pools=3000)
```


Line 131, webdriver\remote\remote_connection.py

```
def _get_connection_manager(self):

        pool_manager_init_args = {
            'timeout': self._timeout
        }
        if self._ca_certs:
            pool_manager_init_args['cert_reqs'] = 'CERT_REQUIRED'
            pool_manager_init_args['ca_certs'] = self._ca_certs
        
        ## It was this:
        return urllib3.PoolManager(**pool_manager_init_args) if not self._proxy_url else \
            urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args)
        ## Changed to this:
        return urllib3.PoolManager(**pool_manager_init_args, num_pools=30000) if not self._proxy_url else \
            urllib3.ProxyManager(self._proxy_url, **pool_manager_init_args, num_pools=30000)

```

**However, changing both didn't help, and I still have this problem. Tried downgrading the selenium, and it didn't help. It sounds like this problem exists since add_cdp_listener method has been added.**

**Comment by ManiMozaffar** [comment]
I have fixed the problem by changing the urllib3 source code, I'm still looking forward to a solution from selenium, I could only see 2 connection which I described above

**Comment by matthiasfru** [comment]
> I have fixed the problem by changing the urllib3 source code, I'm still looking forward to a solution from selenium, I could only see 2 connection which I described above

I have the same problem, would you mind posting your fix?

**Comment by ultrafunkamsterdam** [comment]
This is about an issue in my fork due to an early (wrong) adoption. Not in upstream. This can be closed. official repo has `no .add_cdp_listener(event, callback)`  method.  @ManiMozaffar, i'm working on this.

**Comment by diemol** [comment]
Thanks for letting us know, @ultrafunkamsterdam. Closing.
