### ISSUE TITLE
[🐛 Bug]: Selenium C#-- Test cannot be executed in the old Browser versions

### ISSUE THREAD

**Issue by svadivel0006** [SeleniumHQ/selenium#10252]
### What happened?

In Selenium C#, test script execution is failing in the old versions of browsers

Details:

Selenium WebDriver: V 4.1.0
Chrome                   : V 86.0.4240.75
Chrome Driver        : V 86.0.4240.22 (Release note says: Supports Chrome version 86)

Screenshots:

Error Message:

![Error Message](https://user-images.githubusercontent.com/85741928/149606152-4a4f5a49-8ac1-4131-8fca-440bca4e958b.png)

Chrome Installed Version:

![Chrome Installed Version](https://user-images.githubusercontent.com/85741928/149606158-f77c53c1-ea0a-4b05-abc9-fec06dcd7a3d.png)

Chrome Driver Details:

![Chrome Driver Details](https://user-images.githubusercontent.com/85741928/149606166-e87d1574-5ae1-47b7-922b-bb39063d760d.png)

Chrome Driver Release Notes:

![Chrome Driver Release Notes](https://user-images.githubusercontent.com/85741928/149606172-513f5dc2-673b-45fe-bc3f-9948145f9b47.png)

CodeBase:

![CodeBase1](https://user-images.githubusercontent.com/85741928/149606181-25cf0e7c-cca9-49f6-9660-c2cbc477a882.png)

### How can we reproduce the issue?

```shell
Test with old versions of Browsers
```

### Relevant log output

```shell
Message: 
System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 86.0.4240.75 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe (SessionNotCreated)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
ChromeDriver.ctor()
```

### Operating System

Windows 10

### Selenium version

C# v4.0.30319

### What are the browser(s) and version(s) where you see this issue?

Chrome - 86

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 86.0.4240.22

**Comment by titusfortner** [comment]
Your setup is downloading and using Chromedriver v97
By default WebDriverManager library is getting the latest chromedriver and using it.

Take a look at the advanced usage directions for that library and explicitly specify the version of Chromedriver you want to use. https://github.com/rosolko/WebDriverManager.Net#advanced

**Comment by svadivel0006** [comment]
Hi,

Thanks for the update

Code :

System.Environment.SetEnvironmentVariable("webdriver.chrome.driver",
"Path\\chromedriver_win32\\chromedriver.exe"); //Chrome Version 85 driver
driver = new ChromeDriver();

After using the above code too the error is thrown

Regards,
Vadivel Sekar

**Comment by titusfortner** [comment]
C# bindings looks for that as a System Property not an Environment variable, but using the driver manager will probably be easier to manage.

**Comment by svadivel0006** [comment]
Hi,

Update the code is working for Chrome version 97.

Code:
System.Environment.SetEnvironmentVariable("webdriver.chrome.driver",
"Path\\chromedriver_win32\\chromedriver.exe"); //Chrome Version 97 driver
driver = new ChromeDriver();

But the same code throws an error when the Chrome version is 86.

Regards,
Vadivel Sekar

**Comment by titusfortner** [comment]
The driver version needs to match the browser version, so you need to download the correct driver for the browser, and this is most easily done with the manager code than juggling multiple driver versions yourself.

**Comment by svadivel0006** [comment]
Hi,

Thanks for the update

Kindly can you confirm whether the test scripts can be run in
older versions?

I have tried to run it in the old versions and it is failing.

Note:
WebDriverManager is not downloading the old version drivers, hence test
scripts are failing
When the driver is passed manually through code, where driver version and
installed browsers are matched, the test scripts are failing.

Regards,
Vadivel Sekar

**Comment by titusfortner** [comment]
If you have the right driver, it will work. What code are you using to tell the manager to use the old version?

**Comment by svadivel0006** [comment]
Kindly find the update.

Details:

===========================================================================================================================================

The below code is working for Chrome version 97.

Code:
System.Environment.SetEnvironmentVariable("webdriver.chrome.driver",
"Path\\chromedriver.exe"); //Chrome Version 97 driver
driver = new ChromeDriver();

===========================================================================================================================================

The below code is not working for Chrome version 86.

Code:
System.Environment.SetEnvironmentVariable("webdriver.chrome.driver",
"Path\\chromedriver_win32\\chromedriver.exe"); //Chrome Version 86 driver
driver = new ChromeDriver();

Selenium WebDriver: V 4.1.0

Chrome                              : V 86.0.4240.75

Chrome Driver              : V 86.0.4240.22 (Release note says: Supports
Chrome version 86)


Confirm whether the Chrome and Chrome Driver are compatible?
===========================================================================================================================================

*Note: The WebDriverManager is not downloading the old version of browsers
such as Chrome 86 and other old browsers*

Can you please update the code and screenshots, where you confirm that the
Selenium V 4.1.0, is working in the old browser versions.

**Comment by titusfortner** [comment]
You aren't listening to anything I'm saying. 
1. You can't use the same driver for multiple versions
2. To specify the location, you need to use a System Property, not an Environment variable.
3. To use the Driver Manager you need to follow the directions on their documentation, which I linked to:
https://github.com/rosolko/WebDriverManager.Net#advanced

Specifically something like this:
```csharp
new DriverManager().SetUpDriver(new ChromeConfig(), "86")
```

**Comment by svadivel0006** [comment]
Still getting the same error, used the code base which you mentioned and
the details are as follows.

Details:

CodeBase:
[image: image.png]

Error Stack Tree:
[image: image.png]

WebDriverManager In-Built Code:

[image: image.png]

**Comment by titusfortner** [comment]
None of the images came through.

**Comment by svadivel0006** [comment]
Open the bug, henceforth I can attach it there. If sent through email,
these are not reflecting

**Comment by titusfortner** [comment]
I'm not reopening because it is not a bug, but I will still try to help you get your system sorted.
I think you need to reply from a website not from your email for images to work.
Alternately you can copy and paste the text which is easier for us.

**Comment by svadivel0006** [comment]
Details are as follows

Error Stack Tree:
==============================================================================================
  Message:
System.ArgumentOutOfRangeException : Length cannot be less than zero.
(Parameter 'length')
TearDown : System.NullReferenceException : Object reference not set to an
instance of an object.

  Stack Trace:
String.Substring(Int32 startIndex, Int32 length)
UrlHelper.BuildUrl(String url, String version)
DriverManager.SetUpDriver(IDriverConfig config, String version,
Architecture architecture)
Base.InitBrowser(String browserName) line 116

CodeBase:
=============================================================================================
new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig(), "86");
driver.Value = new ChromeDriver();

WebDriverManager In-Built Code:
=============================================================================================
using System;
using System.Net;
using WebDriverManager.DriverConfigs;
using WebDriverManager.Helpers;
using WebDriverManager.Services;

namespace WebDriverManager
{
    public class DriverManager
    {
        public DriverManager();
        public DriverManager(IBinaryService binaryService, IVariableService
variableService);

        [Obsolete("binaryName parameter is redundant, use SetUpDriver(url,
binaryPath)")]
        public string SetUpDriver(string url, string binaryPath, string
binaryName);
        public string SetUpDriver(string url, string binaryPath);
        public string SetUpDriver(IDriverConfig config, string version =
"Latest", Architecture architecture = Architecture.Auto);
        public DriverManager WithProxy(IWebProxy proxy);
    }
}

=============================================================================================

Selenium WebDriver: V 4.1.0

Chrome                              : V 86.0.4240.75

Chrome Driver              : V 86.0.4240.22 (Release note says: Supports
Chrome version 86)

=============================================================================================

The chromedriver V 86.0.4240.22 is available only for 32-bit and not for 64
bit over the internet. The WebDriverManager is not downloading either. The
Release note says it supports the Chrome version 86. Hence not able to pass
the ChromeDriver manually or using the WebDriverManager.

The case is for all the older versions of Chrome, Edge, Firefox which are
not working.

Hope I have given enough information, please try to give a solution or
close it, as the discussion is not heading in the right direction.

Note: Raised the same issue with WebDriverManager and not yet received any
update

**Comment by titusfortner** [comment]
Looks like you need the exact version number:
```
new DriverManager().SetUpDriver(new ChromeConfig(), "86.0.4240.22");
```

Versions list:
https://chromedriver.storage.googleapis.com/

**Comment by svadivel0006** [comment]
It's not working and the details are as follows.

The installed chrome-64 bit version is "86.0.4240.75" but the chromedriver
is available only for the 32-bit.

It is not present in the link (https://chromedriver.storage.googleapis.com/)
you have shared and over the internet too.

If you confirm it is working, share the share screenshot and the chrome-64
bit versions "86.0.4240.75", chromedriver file or link?

Code used:

new DriverManager().SetUpDriver(new ChromeConfig(), "86.0.4240.22");

or

driver.Value = new ChromeDriver(@"C:\Downloads\chromedriver_win32");

or

new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());

**Comment by titusfortner** [comment]
Windows drivers only come in 32 bit, and that's fine.

what happens when you use this code:
```
new DriverManager().SetUpDriver(new ChromeConfig(), "86.0.4240.22");
```

**Comment by svadivel0006** [comment]
It is displaying an error, requesting you to close the thread, as it is not
heading in the proper direction, thanks for the help and support.
