### ISSUE TITLE
[🚀 Feature]: Support sending Firefox Addon directory as temporary in Remote Sessions

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10265]
### Feature and motivation

Firefox Addon endpoint supports either `path` or `addon` parameter, with addon being a base64 encoded string of a compressed file, which can be either an xpi or a zip file.

Directories are needed to support the temporary parameter. Rather than implementing a file detector and trying to upload the directory to a remote machine, directories should be zipped and base 64 encoded and sent with the `addon` parameter.

Supporting temporary parameter is https://github.com/SeleniumHQ/selenium/issues/10084
It was fixed in every language, except .NET has outstanding PR — https://github.com/SeleniumHQ/selenium/pull/10093
So, it works if the user zips the directory and passes it in, but it would be nice for Selenium to do this for the user.

A great example of this by @nickgaya in JS is here:
https://github.com/SeleniumHQ/selenium/pull/10216

### Usage example

```
String id = ((HasExtensions) augmentedDriver).installExtension(Paths.get("path/to/addon/directory/"), true);
```

**Comment by pmgexpo17** [comment]
> ### Feature and motivation
> Firefox Addon endpoint supports either `path` or `addon` parameter, with addon being a base64 encoded string of a compressed file, which can be either an xpi or a zip file.
> 
> Directories are needed to support the temporary parameter. Rather than implementing a file detector and trying to upload the directory to a remote machine, directories should be zipped and base 64 encoded and sent with the `addon` parameter.
> 
> Supporting temporary parameter is #10084 It was fixed in every language, except .NET has outstanding PR — #10093 So, it works if the user zips the directory and passes it in, but it would be nice for Selenium to do this for the user.
> 
> A great example of this by @nickgaya in JS is here: #10216
> 
> ### Usage example
> ```
> String id = ((HasExtensions) augmentedDriver).installExtension(Paths.get("path/to/addon/directory/"), true);
> ```

Hi,
I'm trying to understand best-practice web-extension devops. It's like mining for gold ! My use-case is this : I've got firefox running in a container on a remote server and I want to deploy a web extension remotely to it in real-time. I want to deploy clusters of firefox containers "in the cloud". I've haven't yet found a good architecture picture that shows how this happens in terms of transmitting the INSTALL_ADDON command and payload to geckodriver. Is geckodriver like a service listener that accepts connections and commands to pass on to Firefox? Does it listen on port 4444 or is that the selenium webdriver service port? Do I need selenium driver just to pass an INSTALL_ADDON payload to geckodriver? Is geckodriver a websocket service, Http or Tcp? I've encountered vague answers to all these at times but .. it's not solid info, suitable for investment .. Lol ! Given the context of this feature, it seems the perfect place to ask these questions? I suppose I don't have to remotely connect directly to geckodriver, I could do a relay of local to remote app, with the remote app being local to the target geckodriver. @titusfortner please consider providing a small example of how remote real-time extension install and reinstall can be accomplished. Thanks in advance !
