### ISSUE TITLE
[🐛 Bug]: 404 in Ruby documentation "TimeoutError.html"

### ISSUE THREAD

**Issue by veenadevi** [SeleniumHQ/selenium#10262]
### What happened?

1. Open https://www.selenium.dev/selenium/docs/api/rb/index.html
2. Click WebDriver->Wait from left frame, it navigates to "https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/Wait.html"
3. Scroll to the bottom and click TimeOutError 

![image](https://user-images.githubusercontent.com/2890751/149895421-967ca23f-a5d6-4eb7-83e5-835cabfc8df9.png)
 
Actual Result 
Getting 404 

![image](https://user-images.githubusercontent.com/2890751/149895674-858444a4-1df9-4c5f-8eb3-8af645423f38.png)

Expected Result
TimeOutError Class Explanation htmp page 

### What browsers and operating systems are you seeing the problem on?

OS: Mac Monterey
Browser: Google Chrome
Browser version: Version 97.0.4692.71 (Official Build) (x86_64)

**Comment by titusfortner** [comment]
Hmm, no idea why the file was named `TimeOutError.html` instead of `TimeoutError.html`, but it's been fixed.
