### ISSUE TITLE
[🐛 Bug]: Getting Shadow Root throws UnsupportedOperationException

### ISSUE THREAD

**Issue by PraveenHudgi1** [SeleniumHQ/selenium#10269]
### What happened?

I am getting error when script is executing 2 line.

1.WebElement shadowHost = driver.findElement(By.cssSelector("#shadow_host"));
2.SearchContext shadowRoot = shadowHost.getShadowRoot();

Error:java.lang.UnsupportedOperationException: getShadowRoot

Serinity 3.1.15(Selenium version 4.1.1)
Chrome browser:97
Windows 10
Java:8 update 251

@titusfortner 

### How can we reproduce the issue?

```shell
Steps to reproduce:

1.Create an account with uipath cloud community application from this link https://cloud.uipath.com and login into application.
2.There you will find left side panel in that left side panel have shadow element.
3.Getting an error when I am trying to click one of the option which is present at left side panel.
```

### Relevant log output

```shell
Error:java.lang.UnsupportedOperationException: getShadowRoot
```

### Operating System

Windows 10

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 97

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 97.0.4692.99

**Comment by titusfortner** [comment]
What is the locator you are using?

This code works for me after logging in:
```
        WebElement shadowHost = driver.findElement(By.tagName("portal-nav"));
        SearchContext shadowRoot = shadowHost.getShadowRoot();
        WebElement shadowContent = shadowRoot.findElement(By.className("pt-menu-group"));
```

**Comment by PraveenHudgi1** [comment]
I am using xpath locator to get shadowHost and we are using serenity framework

 WebElement shadowHost = find(By.xpath("//portal-nav"));
 SearchContext shadowRoot = shadowHost.getShadowRoot();

There are two things to note down
1.I am using xpath instead of tagName,but I have tried with tagName it doesn't worked for me,getting same error.
2.So now only difference left is  Find(Selector) this method is used to get the element ,which is part of serenity framework method.

**Comment by diemol** [comment]
>So now only difference left is Find(Selector) this method is used to get the element ,which is part of serenity framework method.

Ok, that is good information. It hints that the issue might be in Serenity itself. Please report the issue over there.

**Comment by titusfortner** [comment]
Yeah, the other time I saw someone report this error, it was also using serenity, so this seems likely. Please file a report with them https://github.com/serenity-bdd/serenity-core/issues and add a link to this issue. Thanks.

**Comment by PraveenHudgi1** [comment]
I have raised a bug w.r.t serenity .

Thank you!!
