### ISSUE TITLE
[🚀 Feature]: Add Safari Options to Python

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10267]
### Feature and motivation

Python is the only language not to have a Safari Options class.

There are only 2 options, and they aren't likely to be used, so low priority, but should be an easy update for someone looking to jump in. Well, except that safari doesn't do `apple:safariOptions` like the other drivers, both of these options are individually namespaced with `safari:` so that might make things complicated in Python potentially

here's what Ruby has:
https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/safari/options.rb

### Usage example

```py
    options = SafariOptions()
    driver = webdriver.Safari(options=options)
```

**Comment by gsalk2** [comment]
I am trying to suppress the deprecation warning for desired capabilities. I am struggling to pass desired capabilities via Options object for Safari based browsers since there is no Safari Options class. All other browsers run successfully on remote Selenium Grid. I am able to create a copy of desired capabilities object for safari and append what I need, however webdriver.Remote() is expecting Options object rather than just a desired capabilities dictionary. This is my code for running tests across various browsers. Does anyone have any recommendations on how to proceed without a Safari Options class?

`class WebdriverManager:
    """Configurations for all browsers. Add your selection after --browser in the command line"""
    BROWSER_OPTIONS = {'chrome', 'edge', 'firefox', 'galaxyS9+', 'internet explorer', 'iPhoneXR', 'safari'}
    DRIVER_OPTIONS = None
    DESIRED_CAPABILITIES = None
    driver = None

    @classmethod
    def __configure_browser(cls, browser: str = 'chrome', os_version: str = 'undefined',
                            redirect_downloads: str = None):
        """
        Set the Desired Capabilities and Options for the driver

        Args:
            browser: Name of the targeted browser
            os_version: Override to provide OS version (mobile only)
            redirect_downloads: Specified path destination for redirecting downloads

        Returns:
            None
        """

        if browser not in cls.BROWSER_OPTIONS:
            raise ValueError('Invalid browser, expected one of the following: %s' % cls.BROWSER_OPTIONS)

        elif browser == 'chrome':
            cls.DRIVER_OPTIONS = webdriver.ChromeOptions()
            cls.DESIRED_CAPABILITIES = {'browserName': 'chrome', 'platform': 'WINDOWS'}
            cls.DRIVER_OPTIONS.capabilities.update(cls.DESIRED_CAPABILITIES)
            cls.DRIVER_OPTIONS.add_argument("--disable-popup-blocking")
            cls.DRIVER_OPTIONS.add_experimental_option('prefs', {'credentials_enable_service': False})
            cls.DRIVER_OPTIONS.add_experimental_option('excludeSwitches', ['enable-automation'])
            cls.DRIVER_OPTIONS.add_experimental_option('useAutomationExtension', False)
            if redirect_downloads:
                cls.DRIVER_OPTIONS.add_experimental_option('prefs', {"download.default_directory": redirect_downloads})

        elif browser == 'edge':
            cls.DRIVER_OPTIONS = webdriver.EdgeOptions()
            cls.DESIRED_CAPABILITIES = {'browserName': 'MicrosoftEdge', 'platform': 'WINDOWS'}
            cls.DRIVER_OPTIONS.capabilities.update(cls.DESIRED_CAPABILITIES)

        elif browser == 'firefox':
            cls.DRIVER_OPTIONS = webdriver.FirefoxOptions()
            cls.DESIRED_CAPABILITIES = {'browserName': 'firefox', 'platform': 'WINDOWS'}
            cls.DRIVER_OPTIONS.capabilities.update(cls.DESIRED_CAPABILITIES)

        elif browser == 'galaxyS9+':
            cls.DRIVER_OPTIONS = webdriver.ChromeOptions()
            cls.DESIRED_CAPABILITIES = {'name': 'Galaxy S9+', 'platform': 'Android', 'browserName': 'chrome',
                                        'deviceName': 'Galaxy S9+', 'deviceOrientation': 'portrait',
                                        'unicodeKeyboard': True, 'resetKeyboard': True, 'version': os_version}
            cls.DRIVER_OPTIONS.capabilities.update(cls.DESIRED_CAPABILITIES)

        elif browser == 'internet explorer':
            cls.DRIVER_OPTIONS = webdriver.IeOptions()
            cls.DESIRED_CAPABILITIES = {'browserName': 'internet explorer', 'platform': 'WINDOWS'}
            cls.DRIVER_OPTIONS.capabilities.update(cls.DESIRED_CAPABILITIES)

        elif browser == 'iPhoneXR':
            cls.DRIVER_OPTIONS = DesiredCapabilities.SAFARI.copy()
            cls.DESIRED_CAPABILITIES = {'name': 'iPhone XR', 'platform': 'iOS', 'browserName': 'safari',
                                        'deviceName': 'iPhoneXR', 'deviceOrientation': 'portrait',
                                        'automationName': 'XCUITest', 'version': os_version,
                                        'platformVersion': os_version}
            cls.DRIVER_OPTIONS.update(cls.DESIRED_CAPABILITIES)

        elif browser == 'safari':
            cls.DRIVER_OPTIONS = DesiredCapabilities.SAFARI.copy()
            cls.DESIRED_CAPABILITIES = {'browserName': 'safari', 'platform': 'macOS'}
            cls.DRIVER_OPTIONS.update(cls.DESIRED_CAPABILITIES)

        else:
            raise ValueError('Browser configuration does not exist')

    @classmethod
    def create_driver(cls, browser: str = 'chrome', ip_address: str = 'undefined', os_version: str = 'undefined',
                      redirect_downloads: str = None):
        """

        Args:
            browser: Name of the targeted browser
            ip_address: Override to use Grid IP Address
            os_version: Override to provide OS version (mobile only)
            redirect_downloads: Specified path destination for redirecting downloads

        Returns:
            None
        """
        cls.__configure_browser(browser, os_version, redirect_downloads=redirect_downloads)

        # Remote Driver
        if ip_address != 'undefined':
            cls.driver = webdriver.Remote(
                command_executor='http://' + ip_address + '/wd/hub',
                options=cls.DRIVER_OPTIONS
            )

        # Local Driver
        elif browser == 'chrome':
            cls.driver = webdriver.Chrome(options=cls.DRIVER_OPTIONS)

        elif browser == 'edge':
            cls.driver = webdriver.Edge()

        elif browser == 'firefox':
            cls.driver = webdriver.Firefox()

        elif browser == 'internet explorer':
            cls.driver = webdriver.Ie()

    @classmethod
    def get_driver(cls):
        """
        Get the class level webdrvier

        Returns:
            Class level webdriver, if configured
        """
        return cls.driver`

**Comment by titusfortner** [comment]
> Does anyone have any recommendations on how to proceed without a Safari Options class

Nope, this is a better reason for why Python bindings need a `SafariOptions` class than, "the other languages have one." :)

Do you have any interest in making a PR with a new class? Even if it only implements `browserName` it would be helpful.

**Comment by gsalk2** [comment]
Resolved with:
from selenium.webdriver.safari.options import Options
cls.DRIVER_OPTIONS = Options()
