### ISSUE TITLE
[🐛 Bug]: element.click() does not work when scaling is used

### ISSUE THREAD

**Issue by TomXRX** [SeleniumHQ/selenium#10260]
### What happened?

I use docker-selenium-novnc as a web browser for my phone, so that I can access some website like a computer. Everything works fine when using when the scaling is set to 100%.

When I read comics, some picture are slightly too big, so most of the time I set scaling at 90%.

### How can we reproduce the issue?

```shell
set scale to 90% then click.
```

### Relevant log output

```shell
the ".click()" waits forever until I scale chrome back to default.
```

### Operating System

docker for win

### Selenium version

selenium/hub:4.1.0-20211123

### What are the browser(s) and version(s) where you see this issue?

selenium/node-chrome:4.1.0-20211123

### What are the browser driver(s) and version(s) where you see this issue?

selenium/node-chrome:4.1.0-20211123

### Are you using Selenium Grid?

selenium/hub:4.1.0-20211123

**Comment by titusfortner** [comment]
There is no error being returned, the code just hangs?

**Comment by TomXRX** [comment]
> There is no error being returned, the code just hangs?

Sorry, I did not notice I put all my code in a for loop. The "element.click()" actually returns immediately.

And this function returns "None" in python, It always does.

I just excpect it to throw an Error if it failed to do something.

**Comment by TomXRX** [comment]
I tried to do something like:

back=driver.execute_script("return document.body.style.transform")
driver.execute_script("document.body.style.transform='scale(1)';")
ele[0].click()
driver.execute_script("document.body.style.transform='{}';".format(back))

And I find out that the scaling on chrome UI is another independent thing. I'm confused.

**Comment by titusfortner** [comment]
Ah, looks like this is a known issue in Chromedriver:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2605#c7
