### ISSUE TITLE
IE Driver produces inconsistent results with HTML5 window post messaging

### ISSUE THREAD

**Issue by tawniburger** [SeleniumHQ/selenium#1026]
Hi everyone, I have an application which uses the HTML5 window messaging to communicate between two different browser windows. This communication works fine outside of my automated tests and with Selenium with the Chrome Webdriver, but is inconsistent with the IE Webdriver. Sometimes it works, others it doesn’t and I can’t find a rhyme or reason to it.

Here is what the application does:
1.  A parent page is loaded
2.  A button is clicked on the parent page to launch a new child window
3.  When the child window is launched, it sends a window.postMessage back to the parent page
4.  The parent page receives this message to then create channel messaging with ports

From logging results, I can see that the child window always sends the message, but the parent window does not always receive it. The parent and child windows are in the same domain. Here is the test code, it’s pretty straight forward:

```
   driver.get( "http://localhost:8081/parentPage.html" );
   WebElement childButton = driver.findElement(By.id("launchBrowserButton"));
   assertThat( childButton.isEnabled(), is(true) );
   childButton.click();
```

Please let me know if you need any more information.

Thanks,
Tawni

**Comment by rhpijnacker** [comment]
Hi Tawni,

I am experiencing exactly the same problem. But for me it always consistently fails. 
Also sending message from parent to child does not seem to work at all.

Kind regards, Ronald

**Comment by barancev** [comment]
Sorry it was not properly addressed on time, but we need a [concise reproducible test case](http://sscce.org/) for this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproductoin scenario. Feel free to reopen it if you have one.
