### ISSUE TITLE
[🚀 Feature]: Read desired capabilities from Json file directly

### ISSUE THREAD

**Issue by krishtoautomate** [SeleniumHQ/selenium#10279]
### Feature and motivation

Read capabilities from json file directly from file system

WebDriver driver = new WebDriver("PATH_TO_JSON_FILE/desiredCapabilities.json");

### Usage example

WebDriver driver = new WebDriver("PATH_TO_JSON_FILE/desiredCapabilities.json");

python has similar functionality and it ll be great if other programming languages support same

**Comment by diemol** [comment]
This is more suitable for a helper method inside a testing framework. You could also implement it in your test suite, loading the file and then parsing it into the Capabilities object.
