### ISSUE TITLE
[🚀 Feature]: Start distributing Selenium Server on Maven once again

### ISSUE THREAD

**Issue by wrbst** [SeleniumHQ/selenium#10274]
### Feature and motivation

Hello mates,
I'm proposing to start once again distributing Selenium Server over Maven.
The last release is **selenium-server 4.0.0-alpha-2 / 02.July.2019**

I've searched a lot what motivates this move back in 2019 - stopping the distribution, but didn't find any news/article, etc.

We have quite a big UI framework depending on selenium-java and selenium-server and recently we start upgrading it from Java 8 to most recent Java 17.

No current version over Maven is a big drawback as most of the things are automated and manually updating single dependency is a pain.

### Usage example

Selenium-java and Selenium-server are going hand by hand, it's logical both to have distribution over Maven.

**Comment by diemol** [comment]
It is present in maven, it seems we changed the name
https://search.maven.org/artifact/org.seleniumhq.selenium/selenium-grid/4.1.1/jar

**Comment by wrbst** [comment]
Hello Diego, 

Thank you for the clarification! 
Additional confusion has come from the fact that the released Assets here in Github include selenium-server.jar or .zip, but no selenium-grid. While in Maven is opposite - no new selenium-server, but we have the latest selenium-grid - and as there is no information on this matter becomes confusing.

It's worth correcting this mismatch, at least adding information to https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server that the artifact was moved to: selenium-grid.
Like here: https://mvnrepository.com/artifact/jsch/jsch 

Thank you once again.
