### ISSUE TITLE
Chrome version must be >= 43.0.2357.0

### ISSUE THREAD

**Issue by Berekett** [SeleniumHQ/selenium#1027]
hello, I am having an issue using selenium 2.47, chromedriver=2.19.346078, it is giving me 'Chrome version must be >= 43.0.2357.0' error but the one that I have is version 44. Any idea? thanks

**Comment by barancev** [comment]
Please report this issue to the chromedriver tracker:
https://sites.google.com/a/chromium.org/chromedriver/help
