### ISSUE TITLE
[🐛 Bug]: Non-descriptive exceptions talk about CDP

### ISSUE THREAD

**Issue by Artur-** [SeleniumHQ/selenium#10286]
### What happened?

When running the first test ever using Selenium 4 (after migrating from 3) I got the following output
```
Jan 25, 2022 4:07:59 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 97, so returning the closest version found: 96
Jan 25, 2022 4:07:59 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 97 of 96
```

I have no idea what CDP is. Among suggestions from google is "Carbon Disclosure Project" but I don't think that's it

There are so many questions here:
Do I have CDP? Have I installed CDP? Should I install another CDP? Is it ok that 96 is pretty close to 97? Did Selenium find a CDP implementation for version 97 even though it didn't find an exact match for version 97. What does even "of 96" mean in the second log? Where there only 96 versions but still version 97 was found?

Jokes aside, I can start googling it and maybe CDP is somehow related to Chrome as I was trying to run a Chrome test but could the exception messages please instead tell what I should do? 96 and 97 sound like Chrome or Chromedriver versions but both of them are 97.x on my machine

### How can we reproduce the issue?

```shell
By having the wrong CDP version I guess..
```

### Relevant log output

```shell
Jan 25, 2022 4:07:59 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 97, so returning the closest version found: 96
Jan 25, 2022 4:07:59 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 97 of 96
```

### Operating System

macOs Big Sur

### Selenium version

Java 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 97

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.71

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
You can read about it here https://www.selenium.dev/documentation/webdriver/bidirectional/

Also, you get the warning because we have not released in the bindings CDP 97, but this will happen in a couple of days.
