### ISSUE TITLE
[🐛 Bug]: WebdriverJS FluentWait

### ISSUE THREAD

**Issue by Zidious** [SeleniumHQ/selenium#10284]
### What happened?

WebdriverJS FluentWait works in Javascript as per the example in the [documentation](https://www.selenium.dev/documentation/webdriver/waits/#fluentwait). However in TypeScript we are missing the types for the 4th parameter (the frequency at which it polls).

Working JavaScript example (which is polling and including the frequency at which it polls: 

```shell
const { Builder } = require("selenium-webdriver");

function myFunc() {
  console.log("hello world");
}

(async function example() {
  let driver = await new Builder().forBrowser("chrome").build();
  await driver.get("http://google.com");
  // should log 5 times, polling every 1 second then times out
  await driver.wait(myFunc, 5000, "Timed out after 5 seconds", 1000);
  await driver.close();
})();
```

### How can we reproduce the issue?

```shell
import { Builder } from "selenium-webdriver";

function myFunc() {
  console.log("hello world");
}

(async function example() {
  let driver = await new Builder().forBrowser("chrome").build();
  await driver.get("http://google.com");
  // should log 5 times, polling every 1 second then times out
  await driver.wait(myFunc, 5000, "Timed out after 5 seconds", 1000);
  await driver.close();
})();
```

Note: if we cast the `driver` to `any` we are able to get it polling correctly: 

```
await (driver as any).wait(myFunc, 5000, "Timed out after 5 seconds", 1000);
```

### Relevant log output

```shell
index.ts:11:65 - error TS2554: Expected 1-3 arguments, but got 4.
11   await driver.wait(myFunc, 5000, "Timed out after 5 seconds", 1000);
```

Issue is within `types.d.ts:` 

```
 wait(condition: WebElementCondition, opt_timeout?: number, opt_message?: string): WebElementPromise;
```

### Operating System

macOS

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

97

**Comment by diemol** [comment]
The linked PR to `DefinitelyTyped` was merged, so this should be fine already. Closing.
