### ISSUE TITLE
[🐛 Bug]: firefox flapak does not go to page

### ISSUE THREAD

**Issue by yellowhat** [SeleniumHQ/selenium#10283]
### What happened?

Hi,
I would like to use selenium against firefox installed using flatpak.
Using the scripts below, firefox is opened but it does not continue, seems stuck waiting for firefox to be opened.

### How can we reproduce the issue?

```shell
python -m venv /tmp/env
source /tmp/env/bin/activate
pip install --no-cache selenium webdriver-manager

python firefox.py
```

`firefox.py`:
```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager

options = Options()
options.binary_location = "/var/lib/flatpak/exports/bin/org.mozilla.firefox"
options.add_argument("-profile /home/vasco/.mozilla")
options.add_argument("-private")

service = Service(GeckoDriverManager().install())

with webdriver.Firefox(options=options, service=service) as driver:
    driver.maximize_window()
    driver.get("http://google.com/ncr")
    driver.quit()
```

### Relevant log output

```shell
====== WebDriver manager ======
Could not get version for firefox with the any command: firefox --version
Current firefox version is UNKNOWN
Get LATEST geckodriver version for UNKNOWN firefox
Driver [/home/vasco/.wdm/drivers/geckodriver/linux64/v0.30.0/geckodriver] found in cache
```

### Operating System

Gentoo

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 96.0.2

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by titusfortner** [comment]
This is a `webdriver_manager` issue. That library is trying to determine the version of the browser to make sure the correct driver is installed. It probably has a way to specify the location of the browser to check, or to skip that check, you'd have to read their docs. Alternately, you remove the manager and download the driver and put it in a directory on PATH env variable, or specify the path in the Service class.

**Comment by yellowhat** [comment]
Sorry for the late reply.
As you suggested I tried:

```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.binary_location = "/var/lib/flatpak/exports/bin/org.mozilla.firefox"
options.add_argument("-profile /home/vasco/.mozilla")
options.add_argument("-private")

with webdriver.Firefox(options=options) as driver:
    driver.get("http://google.com")
    driver.quit()
```
with the `geckodriver` binary (version 0.30.0) in `/usr/local/bin`.

The firefox window opens, in private mode, but it does not open `google.com` and/or exit with no output from the console.

May I ask to reopen the issue?

Thanks

**Comment by titusfortner** [comment]
Your original issue was that the browser wasn't opening. 

Does it work as you expect if it don't add the extra arguments? Setting profile that way is not currently recommended.

**Comment by AutomatedTester** [comment]
What is flatpak? Is it a repackaged Firefox?

**Comment by yellowhat** [comment]
Sorry for the late reply.
@titusfortner the issue has always been about: firefox window opens but it does not load the `google.com` page.
If I do not specify the `options.add_argument("-profile /home/vasco/.mozilla")` I get an error message on opening firefox `Your Firefox profile cannot be loaded. It may be missing or inaccessible.`
@AutomatedTester yes [flatpak](https://flatpak.org/) is a sort of sandboxed repackage of firefox.

**Comment by AutomatedTester** [comment]
If it’s a repackaged Firefox the people repackaging will need to make sure all the [`remote`](https://searchfox.org/mozilla-central/source/remote) code is packaged up otherwise geckodriver has nothing to connect to.

**Comment by yellowhat** [comment]
If I add `options.add_argument("--marionette")`, in the address bar there is an icon with the description `Browser is under remote control (reason: Marionette)`. Does this mean that the `remote` option is included?
