### ISSUE TITLE
[🐛 Bug]: - In Linux OS - getShadowRoot() method is not accessible for Selenium4 

### ISSUE THREAD

**Issue by anushareddyqa** [SeleniumHQ/selenium#10287]
### What happened?

I have upgraded selenium version to 4.0.0. Now we have a method getShadowRoot(). I have used the below code.

    @Test
      public void recommendedCode() {
      WebDriverManager.chromedriver().setup();
      driver = new ChromeDriver();
      driver.get("http://watir.com/examples/shadow_dom.html");

      WebElement shadowHost = driver.findElement(By.cssSelector("#shadow_host"));
      SearchContext shadowRoot = shadowHost.getShadowRoot();
      WebElement shadowContent = shadowRoot.findElement(By.cssSelector("#shadow_content"));

      Assertions.assertEquals("some text", shadowContent.getText());
    }

This was working fine in Windows OS. 
For the same code, I am getting error at getShadowRoot() for linux OS. Under Webelement, we have getShadowRoot(), still getting the error
![ShadowRoot issue in Linux OS](https://user-images.githubusercontent.com/17266028/151034672-bbcb9a7d-c6e6-4af3-9eb1-e1ce54565d91.png)

### How can we reproduce the issue?

```shell
@Test
public void recommendedCode() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();

    driver.get("http://watir.com/examples/shadow_dom.html");

    WebElement shadowHost = driver.findElement(By.cssSelector("#shadow_host"));
    SearchContext shadowRoot = shadowHost.getShadowRoot();
    WebElement shadowContent = shadowRoot.findElement(By.cssSelector("#shadow_content"));

    Assertions.assertEquals("some text", shadowContent.getText());
}

use linux OS. in eclipse - selenium maven project, use this code in any class file and check
```

### Relevant log output

```shell
Getting compilation error
```

### Operating System

Linux OS

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 97

### What are the browser driver(s) and version(s) where you see this issue?

97.0.4692.99

### Are you using Selenium Grid?

 No

**Comment by titusfortner** [comment]
I think this is a dependency issue. What do you have in your POM? 

Just use this, and it will pull in everything else you need:

```
<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.1.1</version>
</dependency>
```

**Comment by anushareddyqa** [comment]
@titusfortner Thank you for the update. We have tried using version 4.1.1, still facing the same issue. Please advise is there any other possible ways to handle shadow root elements.

**Comment by titusfortner** [comment]
I'm not sure what more to tell you here. The class is there and available. If you don't have any dependency issues, perhaps it is an eclipse cache issue? Does it work if you run command line? Do you need to update your m2 directory to make sure only the correct version of Selenium is present?

There's nothing we can change in the Selenium code that will make it work on your computer.
