### ISSUE TITLE
Missing DLL in Download

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#1028]
I downloaded 
http://selenium-release.storage.googleapis.com/2.47/selenium-dotnet-2.47.0.zip

There is the WebDriver.dll in the ZIP file which references to Newtonsoft.json.dll.
But this DLL is missing in the ZIP file.

**Comment by jimevans** [comment]
The Jsan.NET assembly is merged into WebDriver.dll using ILMerge. There is no need to ship the reference separately.
