### ISSUE TITLE
[🐛 Bug]: Getting UnsupportedOperationException when while selecting values from dropdowns in selenium-4.0.0

### ISSUE THREAD

**Issue by Tejareddy1** [SeleniumHQ/selenium#10290]
### What happened?

Getting UnsupportedOperationException when while selecting dropdowns org.openqa.selenium.support.ui.Select class from selenium 4.0.0 (tried latest 4.1.1 as well). The same code works fine with 3.141.59 version. I am getting this issue while upgrading the selenium library in my project.  

java.lang.UnsupportedOperationException: getDomAttribute
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)

### How can we reproduce the issue?

```shell
Getting UnsupportedOperationException when while selecting dropdowns org.openqa.selenium.support.ui.Select class from selenium 4.0.0 (tried latest 4.1.1 as well)

java.lang.UnsupportedOperationException: getDomAttribute
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
```

### Relevant log output

```shell
java.lang.UnsupportedOperationException: getDomAttribute
	at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131)
	at org.openqa.selenium.support.ui.Select.<init>(Select.java:54)
```

### Operating System

macOS or linux

### Selenium version

Java 8

### What are the browser(s) and version(s) where you see this issue?

chrome 96

### What are the browser driver(s) and version(s) where you see this issue?

97.0.4692.71

**Comment by pujagani** [comment]
Thank you for providing details regarding the error. Please provide a reproducible test script/project/code snippet. It will help us reproduce and debug the error. Thank you!

**Comment by titusfortner** [comment]
I see this issue when there is a dependency conflict. Do you perhaps also require a version of Appium that requires Selenium 3 libraries?

**Comment by Tejareddy1** [comment]
I don't think this is due to a dependency issue. the same was working with selenium 3.141.59 version and I don't have appium in my project dependencies.

**Comment by titusfortner** [comment]
`getDomAttribute()` is new in Selenium 4.  But I see now that your error isn't that it isn't being found, but that it's returning unsupported operation. Can you verify that you are getting a W3C session instead of an OSS session? Which one you're getting should be displayed STDOUT after creating the session.

**Comment by Tejareddy1** [comment]
I over ride the getDomAttribute() method in my project then it works
