### ISSUE TITLE
 System.ArgumentNullException: Frame element cannot be null (Parameter 'frameElement')

### ISSUE THREAD

**Issue by qaguru1** [SeleniumHQ/selenium#10294]
### What happened?

unable to locate Iframe no matter what I do. I am unable to locate a iFrame?

### How can we reproduce the issue?

```shell
use switch to iframe method
```

### Relevant log output

```shell
System.ArgumentNullException: Frame element cannot be null (Parameter 'frameElement')
```

### Operating System

Windows 10

### Selenium version

3

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome

### Are you using Selenium Grid?

no

**Comment by qaguru1** [comment]
var element = "foo"
var fooElement = driver.FindElement(By.XPath(element));
driver.SwitchTo().Frame(findElement(fooElement ));

**Comment by qaguru1** [comment]
> Hi, @qaguru1. Please follow the issue template, we need more information to reproduce the issue.
> 
> Either a complete code snippet and URL/HTML (if more than one file is needed, provide a GitHub repo and instructions to run the code), the specific versions used, or a more detailed description to help us understand the issue.
> 
> Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.
> 
> Reply to this issue when all information is provided, thank you.

var element = "foo"
var fooElement = driver.FindElement(By.XPath(element));
driver.SwitchTo().Frame(fooElement );

**Comment by diemol** [comment]
This is still not enough to reproduce the issue.

Please provide a complete test script. For example, the one above does not show which website is being used, which version of the Selenium bindings, what version of the browser, etc...

**Comment by qaguru1** [comment]
@diemol  browser is Chrome.  Selenium version is from .NET latest nuget package. version 3.   I am having difficulty finding the iframe to click on the button that is inside the iframe.

**Comment by diemol** [comment]
Please share a complete code example that we can use to reproduce this. Please not that we are not troubleshooting Selenium 3 anymore.
Before sharing your complete code example, please upgrade to Selenium 4.

**Comment by titusfortner** [comment]
That error only happens if you are passing in a `null` value to the `Frame()` method, so you aren't passing in a valid element, and that isn't a valid XPath for locating an element.

Try something like this:
```
var fooElement = driver.FindElement(By.TagName("frame"));
```

**Comment by qaguru1** [comment]
@diemol   I just checked. I do have SE version 4.  I do have the latest selenium 4.  This code was working before. for some reason. It starting failing.

**Comment by qaguru1** [comment]
> Please share a complete code example that we can use to reproduce this. Please not that we are not troubleshooting Selenium 3 anymore. Before sharing your complete code example, please upgrade to Selenium 4.

@diemol I just checked. I do have SE version 4. I do have the latest selenium 4. This code was working before. for some reason. It starting failing.

**Comment by qaguru1** [comment]
> That error only happens if you are passing in a `null` value to the `Frame()` method, so you aren't passing in a valid element, and that isn't a valid XPath for locating an element.
> 
> Try something like this:
> 
> ```
> var fooElement = driver.FindElement(By.TagName("frame"));
> ```

This code was working perfectly fine before. For some reason It started failing recently.

**Comment by qaguru1** [comment]
@diemol   @titusfortner  this iframe is inside a body tag. Could that be a reason? I have read some folks complaining and having about frames inside a BODY html?

`<button type="button" id="PayNowButton" role="button" class="btn btn-success btn-block" onclick="payNow();" xpath="1">Pay Now</button>`

^^^ This is the button I am trying to click on???  but It is NOT working.

**Comment by qaguru1** [comment]
this button is inside some kind of a hidden iFrame.  under a BODY tag.  Not sure that is the root cause?

**Comment by titusfortner** [comment]
So, html always has a `head` and a `body` tag. Everything you interact with on a page is in a `body` tag.

You can't click on a button inside an iframe without first switching to the iframe.
You can't switch to an iframe if the iframe isn't displayed.

Can you share the html you are working with?
Selenium didn't change how it works with frames. Somehow you are getting a null value when you attempt to locate the frame, so you need to figure out why you're getting null instead of an exception. Are you rescuing the exception?

**Comment by qaguru1** [comment]
@titusfortner  I am trying to find the element that is inside a frame => PayNowButton

here is the HTML =>





<!DOCTYPE html>

<html lang="en"  class="lightwindow" >
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title>My _ _ | _</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex, nofollow, noodp" />
    <meta name="description" content="_ for your _ _ are listed here." />
    <meta property="og:title" content="_ | Free _ e _es _, Free E-_" />
    <meta property="og:description" content="_ , _ your _ _es. _ _." />
    <meta property="og:image" content="https://www_/images/_-icon-fb.png" />
    <link rel="canonical" href="https://www.__" />
    <meta name="author" content="_, Inc." />
    
    <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
    
        
           
        <script type="text/javascript" src=".js"></script>           
    
    

    
"__,___,irs.gov,facebook_,twitter_,localhost,127.0.0.1","DefaultSecurityRedirect": "https://www.__",    };    _ config;};</script><script type="text/javascript" src="https://_.__/__2021/scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/bootstrap.min.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/bootstrap-slider.min.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/inputfilters.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/product_s.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/distraction.js?tav=20220125.2"></script>


    
	<link rel="stylesheet" href="https://_.__/__2021/css/jquery.fancybox.css?tav=20220125.2" type="text/css" />
<script type="text/javascript" src="https://_.__/__2021/scripts/jquery.fancybox.pack.js?tav=20220125.2"></script>
<<script type="text/javascript" src="https://_.__/__2021/scripts/globalvariables.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/windows.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/close_.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/common.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/copypicker.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/details.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/fancyboxhelpers.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/interviewhelpers.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/navigation.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/showimportwindows.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/showinfo.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/showtools.js?tav=20220125.2"></script>

<script src="https://_.__/auth/js/refreshSession.js" type="text/javascript"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/usertimeout.js?tav=20220125.2"></script>
<script type="text/javascript" src="https://_.__/__2021/scripts/google_analytics.js?tav=20220125.2"></script>

<script type="text/javascript">
    var dataLayer = [{
        'pageType'      : 'Application',
        'contentType'   : '_',
        'userType'      : 'Guest',
        'userId'        : '',
        'ol_Id'       : '',
        'signedIn'      : 'Yes'
    }];
</script>

    <script type="text/javascript">
        (function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
            var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src = 'https://www.googletagmanager_/gtm.js?id=' +
                i +
                dl +
                '&gtm_auth=&gtm_preview=env-1&gtm_cookies_win=x';
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', '-');     
        		
		let s = document.createElement('link');
		s.rel = "preload";
		s.href = "/_/2021/";
		s.type = "document";
		document.head.appendChild(s);
		let t = document.createElement('link');
		t.rel = "preload";
		t.href = "/_/css/chuck-common*.css";
		t.type = "style";
		document.head.appendChild(t);
		let v = document.createElement('link');
		v.rel = "preload";
		v.href = "/_/css/chuck-vendors*.css";
		v.type = "style";
		document.head.appendChild(v);

    </script>
    
</head>

<body class="lightwindow"  ontouchstart>
    
    <noscript>
        <iframe src="//www.googletagmanager_/ns.html?id=GTM-MJLZSZ" height="0" width="0" style="display: none; visibility: hidden"></iframe>
    </noscript>
    
    
<script type="text/javascript">
    function payNow() {
        if (window.opener && window.opener.$j.fancybox) {
            if (window.opener) {
                window.opener.OnUpdateSplash();
                window.opener.OnNavClick('/_manager2021/_manager.dll/PayNow?nav_script=&show_topics=0');
            }
            closeFancyBox();
            window.close();
        }
        else if (parent && parent.$j.fancybox) {
            parent.OnUpdateSplash();
            parent.OnNavClick('//.dll/PayNow?nav_script=&show_topics=0');
            closeFancyBox();
        }
    }

    function add_PayerSupport() {
        jQuery.ajax({
            url: "//_manager.dll/OnAdd_payerSupport",
            // doesn't like actual nothing sent in a post, so send "nothing"
            data: "nothing",
            type: "POST",
            success: function () { payNow();},
            error: function () { payNow(); }
        });
    }

</script>

<iframe id="dataFrame" name="dataFrame" src="/_manager2021/_manager.dll/GetAccountInfo?fromPage=MyAccount.asp&sub=1&t=52850.63" style="width:0px;height:0px;border:none;display:none;"></iframe>

<body id="mainContent" class="mainContent lightwindow" onload="CheckPayNowButton();">
    <script type="text/javascript">
        function CheckPayNowButton() {
            if (parent.getFeatureStatus("hid__") === "disabled") {
                var element = document.getElementById("PayNowButton");
                element.parentNode.removeChild(element);
            }
        }
    </script>

    <div id="my_" class="container-fluid">
        <h1 id="interview-title" class="mb-2">My _ _ _</h1>

        <p>_ _ for your _ are listed below. Prices are determined at time of _ and subject to change.</p>
<h3 class="mb-1">_ _ _ _</h3>
<ul class="mb-2"><li>Your _ _ fee is $.</li><li>Your _ _ fee is $.</li><li>If you elect to add _ _, the fee is $.</li>
</ul><div class='row'><div class='col-lg-6 col-md-6 col-sm-6 col-xs-12'><button type='button' id='PayNowButton' role='button' class='btn btn-success btn-block' onclick='payNow();'>Pay Now</button></div></div>

        <div id="ccInfoDest"></div>
    </div>


        <script type="text/javascript">
            if ($j === undefined) {
                var $j = jQuery.noConflict();
            }

            var cImagesDir = "https://_.__/__2021/images/";
        </script>

    </body>
</html>

**Comment by qaguru1** [comment]
> So, html always has a `head` and a `body` tag. Everything you interact with on a page is in a `body` tag.
> 
> You can't click on a button inside an iframe without first switching to the iframe. You can't switch to an iframe if the iframe isn't displayed.
> 
> Can you share the html you are working with? Selenium didn't change how it works with frames. Somehow you are getting a null value when you attempt to locate the frame, so you need to figure out why you're getting null instead of an exception. Are you rescuing the exception?



@titusfortner I am trying to find the element that is inside a frame => PayNowButton

here is the HTML =>

<title>My _ _ | _</title>
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">

    
       
    <script type="text/javascript" src=".js"></script>           


",,irs.gov,facebook,twitter_,localhost,127.0.0.1","DefaultSecurityRedirect": "https://www.__", }; _ config;};</script><script type="text/javascript" src="https://_.__/__2021/scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript" src="https://_.__/__2021/scripts/bootstrap.min.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/bootstrap-slider.min.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/inputfilters.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/product_s.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/distraction.js?tav=20220125.2"></script>

<link rel="stylesheet" href="https://_.__/__2021/css/jquery.fancybox.css?tav=20220125.2" type="text/css" />
<script type="text/javascript" src="https://_.__/__2021/scripts/jquery.fancybox.pack.js?tav=20220125.2"></script>
<<script type="text/javascript" src="https://_.__/__2021/scripts/globalvariables.js?tav=20220125.2"></script>

<script type="text/javascript" src="https://_.__/__2021/scripts/windows.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/close_.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/common.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/copypicker.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/details.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/fancyboxhelpers.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/interviewhelpers.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/navigation.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/showimportwindows.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/showinfo.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/showtools.js?tav=20220125.2"></script> <script src="https://_.__/auth/js/refreshSession.js" type="text/javascript"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/usertimeout.js?tav=20220125.2"></script> <script type="text/javascript" src="https://_.__/__2021/scripts/google_analytics.js?tav=20220125.2"></script> <script type="text/javascript"> var dataLayer = [{ 'pageType' : 'Application', 'contentType' : '_', 'userType' : 'Guest', 'userId' : '', 'ol_Id' : '', 'signedIn' : 'Yes' }]; </script>
<script type="text/javascript">
    (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
        var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src = 'https://www.googletagmanager_/gtm.js?id=' +
            i +
            dl +
            '&gtm_auth=&gtm_preview=env-1&gtm_cookies_win=x';
        f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', '-');     
    		
	let s = document.createElement('link');
	s.rel = "preload";
	s.href = "/_/2021/";
	s.type = "document";
	document.head.appendChild(s);
	let t = document.createElement('link');
	t.rel = "preload";
	t.href = "/_/css/chuck-common*.css";
	t.type = "style";
	document.head.appendChild(t);
	let v = document.createElement('link');
	v.rel = "preload";
	v.href = "/_/css/chuck-vendors*.css";
	v.type = "style";
	document.head.appendChild(v);

</script>
<iframe src="//www.googletagmanager_/ns.html?id=GTM-MJLZSZ" height="0" width="0" style="display: none; visibility: hidden"></iframe> <script type="text/javascript"> function payNow() { if (window.opener && window.opener.$j.fancybox) { if (window.opener) { window.opener.OnUpdateSplash(); window.opener.OnNavClick('/_manager2021/_manager.dll/PayNow?nav_script=&show_topics=0'); } closeFancyBox(); window.close(); } else if (parent && parent.$j.fancybox) { parent.OnUpdateSplash(); parent.OnNavClick('//.dll/PayNow?nav_script=&show_topics=0'); closeFancyBox(); } } function add_PayerSupport() { jQuery.ajax({ url: "//_manager.dll/OnAdd_payerSupport", // doesn't like actual nothing sent in a post, so send "nothing" data: "nothing", type: "POST", success: function () { payNow();}, error: function () { payNow(); } }); } </script> <iframe id="dataFrame" name="dataFrame" src="/_manager2021/_manager.dll/GetAccountInfo?fromPage=MyAccount.asp&sub=1&t=52850.63" style="width:0px;height:0px;border:none;display:none;"></iframe> <script type="text/javascript"> function CheckPayNowButton() { if (parent.getFeatureStatus("hid__") === "disabled") { var element = document.getElementById("PayNowButton"); element.parentNode.removeChild(element); } } </script>
<div id="my_" class="container-fluid">
    <h1 id="interview-title" class="mb-2">My _ _ _</h1>

    <p>_ _ for your _ are listed below. Prices are determined at time of _ and subject to change.</p>
_ _ _ _
Your _ _ fee is $.
Your _ _ fee is $.
If you elect to add _ _, the fee is $.
Pay Now
    <div id="ccInfoDest"></div>
</div>


    <script type="text/javascript">
        if ($j === undefined) {
            var $j = jQuery.noConflict();
        }

        var cImagesDir = "https://_.__/__2021/images/";
    </script>

</body>

**Comment by titusfortner** [comment]
So, there are 2 iframes here. Is it possible that the iframe you want is now the second one?

**Comment by qaguru1** [comment]
@titusfortner  which iframe are you referring to? this is what I have

`driver.SwitchTo().Frame(driver.FindElement(By.XPath("//*[@id='mainContent']")));`

**Comment by qaguru1** [comment]
> So, there are 2 iframes here. Is it possible that the iframe you want is now the second one?

@titusfortner which iframe are you referring to? this is what I have

driver.SwitchTo().Frame(driver.FindElement(By.XPath("//*[@id='mainContent']")));

**Comment by titusfortner** [comment]
It's really hard to tell from just the page source you referenced, but
```
<iframe src="//./.htmlid=-" height="0" width="0" style="display: none; visibility: hidden"></iframe>
```
and
```
<iframe id="dataFrame" name="dataFrame" src="//_manager.dll/GetAccountInfo?fromPage=MyAccount.asp&sub=1&t=52850.63" style="width:0px;height:0px;border:none;display:none;"></iframe>
```

I don't see an iframe that has an id of `mainContent` is it nested inside one of the above iframes?

**Comment by qaguru1** [comment]
> It's really hard to tell from just the page source you referenced, but
> 
> ```
> <iframe src="//./.htmlid=-" height="0" width="0" style="display: none; visibility: hidden"></iframe>
> ```
> 
> and
> 
> ```
> <iframe id="dataFrame" name="dataFrame" src="//_manager.dll/GetAccountInfo?fromPage=MyAccount.asp&sub=1&t=52850.63" style="width:0px;height:0px;border:none;display:none;"></iframe>
> ```
> 
> I don't see an iframe that has an id of `mainContent` is it nested inside one of the above iframes?

@titusfortner 
sorry I had the wrong ID. that is the actual ID of the body tag

this is what I have  =>  `driver.SwitchTo().Frame(driver.FindElement(By.XPath("//*[@id='dataFrame']")))`

**Comment by qaguru1** [comment]
@titusfortner   Is it possible I can share my screen?

**Comment by diemol** [comment]
@qaguru1 please share a code snippet we can use to troubleshoot the issue, it will simply take longer if only bits of information are shared in every single comment.

**Comment by qaguru1** [comment]
@diemol  I posted a question in selenium slack channel.

**Comment by diemol** [comment]
Replied over there.
