### ISSUE TITLE
[🚀 Feature]: Support retrieving groupCollapsed group labels

### ISSUE THREAD

**Issue by jieqiu0630** [SeleniumHQ/selenium#10302]
### Feature and motivation

Currently,  collapsed log groups' labels cannot be retrieved from the browser logs via functions like `driver.get_log("browser")`.

For example, if my I log the following to my console:
```
console.groupCollapsed("group label");
console.log("hello");
console.log("world");
console.groupEnd();
```
Only `"hello"` and `"world"` will be retrieved from `driver.get_log("browser")`. `"group label"`, the label of this inline console log group, is not captured. 

It would be great if group labels can be captured as normal console log messages.

### Usage example

In certain scenarios, we would like to use console log messages along with selenium as a way of testing our web app. We also use `groupCollapsed` to not clutter the console. Ideally, we would like to get the group labels as they may contain useful information for our testing.

**Comment by titusfortner** [comment]
Thanks for your request.

Logging is not currently defined in the w3c spec (https://github.com/w3c/webdriver/issues/406), and what is provided is essentially whatever the Browser Driver decides should be included. So, asking for something additional would need to go be requested from Google. It's possible that upcoming BiDi features will allow you to get this information from the browser directly, but I don't know.
