### ISSUE TITLE
[🚀 Feature]: Support to add capabilites for python selenium by edge options

### ISSUE THREAD

**Issue by Nepitwin** [SeleniumHQ/selenium#10309]
### Feature and motivation

It would be nice if following C# code can be used also in Python usage to add arguments or capabilities to edge.

```
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using System.Threading;

namespace EdgeDriverSample
{
    class Program
    {
        static void Main(string[] args)
        {
            var options = new EdgeOptions();
            options.AddArgument("--disable-features=msSmartScreenProtection");

            var driver = new EdgeDriver(options);

	    // Should navigate to smartscreen test site instead of blocking.
            driver.Url = "https://nav.smartscreen.msft.net/other/malware.html";

            Thread.Sleep(5000);
            driver.Quit();
        }
    }
}
```

This will disable the microsoft smart screen feature by edge for all tests.
From current documentation their is only three method implementations supported for edge options.

https://www.selenium.dev/selenium/docs/api/py/webdriver_edge/selenium.webdriver.edge.options.html#module-selenium.webdriver.edge.options

### Usage example

```
from selenium.webdriver.edge import options as EdgeOptions

def create_edge_options():
    options = EdgeOptions()
    options.add_argument("--disable-features=msSmartScreenProtection");
    return options
```

**Comment by diemol** [comment]
In Python, [`EdgeOptions` extends `ChromiumOptions`](https://github.com/SeleniumHQ/selenium/blob/87e3833c04af07236ebb7c3f4259a949358ccfb7/py/selenium/webdriver/edge/options.py#L22),  which then [extends ArgOptions](https://github.com/SeleniumHQ/selenium/blob/14c76671a5aad8b6a3209a7b831edc1d49be1daf/py/selenium/webdriver/chromium/options.py#L27), and there you have [the arguments](https://github.com/SeleniumHQ/selenium/blob/41a34dfbdfc70c90cc133e9a9cf5470236f0ff5e/py/selenium/webdriver/common/options.py#L234).
