### ISSUE TITLE
[🐛 Bug]: WheelScrollInteraction does not work for dotnet Selenium

### ISSUE THREAD

**Issue by eversoutheast** [SeleniumHQ/selenium#10303]
### What happened?

Exception after execute reproduce code.
OpenQA.Selenium.WebDriverArgumentException: 'invalid argument
from invalid argument: type of action must be the string 'scroll' or 'pause'
  (Session info: chrome=97.0.4692.99)'

Root cause:
line 155 in https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Interactions/WheelInputDevice.cs
Currently: toReturn["type"] = "pointerMove";
Should be: toReturn["type"] = "scroll"

### How can we reproduce the issue?

```shell
public void TestScroll()
        {
            ChromeDriver driver = new ChromeDriver();
            Thread.Sleep(1000);

            driver.Url = "http://baidu.com";
            Thread.Sleep(1000);
            driver.Manage().Window.Maximize();
            Thread.Sleep(500);

            var kwEle = driver.FindElement(By.Id("kw"));
            kwEle.SendKeys("abcxyz");
            Thread.Sleep(500);
            var suEle = driver.FindElement(By.Id("su"));
            suEle.Click();
            Thread.Sleep(1000);

            WheelInputDevice wheel1 = new WheelInputDevice();
            Interaction scrollDown = wheel1.CreateWheelScroll(0, 100, TimeSpan.FromSeconds(1));
            IList<ActionSequence> asList = new List<ActionSequence>();

            ActionSequence @as = new ActionSequence(wheel1);
            @as.AddAction(scrollDown);
            asList.Add(@as);

            ((WebDriver)driver).PerformActions(asList);
        }
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

dotnet 4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 97.0.4692.99

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.7100

**Comment by diemol** [comment]
Not an expert on this area, but could you please help us with a PR? And hopefully a regression test?

**Comment by eversoutheast** [comment]
https://github.com/SeleniumHQ/selenium/pull/10304 is created.

**Comment by eversoutheast** [comment]
This issue can be closed as https://github.com/SeleniumHQ/selenium/pull/10304 is merged
