### ISSUE TITLE
[🚀 Feature]: Window events listener onWindowMove

### ISSUE THREAD

**Issue by maximandrews** [SeleniumHQ/selenium#10314]
### Feature and motivation

Would be great to have ability to capture movements of the browser window.

There are two ways of testing in browser:
1. Tests automation. When you start all of your tests from command line and it goes through all of your test suits.
2. Live/hot reload. When software engineer does coding and observes changes in the browser.

In the scenario of a live/hot reload, software engineer may move their browser windows all over the screen or even multiple screens.

Would be great to be able to capture these movements to enable to save and restore windows setup.
Currently, we can get/set window position, but we can't listen to changes.
https://www.selenium.dev/documentation/webdriver/browser/windows/#get-window-position

I suppose it should be part of BiDirectional API.
https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/

What do you think about that?

### Usage example

```
const {Builder, By} = require('selenium-webdriver');
(async () => {
  try {
    let driver = new Builder()
      .forBrowser('safari')
      .build();

    const observeMe = await driver.getWindowHandle();
    await driver.onWindowMove(observeMe, async function (event) {
      const rect = await driver.manage().window(event.windowHandle).getRect();
      console.log(rect);
    });
  } catch (e){
    console.log(e);
  }
})();
```

**Comment by diemol** [comment]
Not sure if this is a use case that should be added, but I am not the one to decide that. You could propose it here https://github.com/w3c/webdriver-bidi.

I guess you can also register a JS function that captures the mouse movements, and listen to it through the events (this is just an idea, I have not tried this).

I will close this as this needs to be decided first on the spec.

**Comment by diemol** [comment]
If you create an issue/proposal in the spec, please share the link here so others can check it out.
