### ISSUE TITLE
[🚀 Feature]: TestNG support to run feature files in parallel(like Junit 4)

### ISSUE THREAD

**Issue by surajgupta7175** [SeleniumHQ/selenium#10315]
### Feature and motivation

Is your feature request related to a problem? Please describe.
With Version 4 Selenium and cucumber-jvm. We cannot run feature files parallely using TestNG . The same feature is available with Junit

Currently when we run 2 threads,
Scenario 1 & 2 present in same feature file gets executed
Problem - Scenario 2 is dependent on Scenario 1 to complete

Under maven-surefireplugin

```
<properties>
		<property>
		<name>dataproviderthreadcount</name>
		<value>2</value>
		</property>
</properties>
<parallel>classes</parallel> 
<useUnlimitedThreads>true</useUnlimitedThreads> 
					
<perCoreThreadCount>true</perCoreThreadCount>
<includes> 
	<include>Runner Path to be added</include>
</includes>
```

Article used to setup - https://cucumber.io/docs/guides/parallel-execution/?sbsearch=parallel

### Usage example

In Junit we can run feature file in parallel

This feature is required in testng since many a time scenarios present in same feature file are interdependednt and single thread should run/pick one feature file

**Comment by diemol** [comment]
This is independent from Selenium. What happens if you only use TestNG without  cucumber-jvm?

**Comment by titusfortner** [comment]
Here's an example of how to run tests in parallel with TestNG

https://github.com/saucelabs-training/demo-java/blob/main/selenium-testng-examples/pom.xml
