### ISSUE TITLE
[🐛 Bug]: Selenium Python - SendKeys does not work when computer is locked

### ISSUE THREAD

**Issue by allanbides** [SeleniumHQ/selenium#10329]
### What happened?

Hi,

I use python 3.9.5 and selenium 4.1.0 with microsoft Edge 98.0.1108.43 on Windows 10 to fill a date in a text box with the code below:

```
#element is the web element I want to fill
element = "element_name"
date = driver.find_element(By.ID, element)

date.click()
date.clear()

#Positionate cursor at text box beginning
for i in range(1,10):
    date.send_keys(Keys.ARROW_LEFT)
    
#Fill the date
date.send_keys("11022022")
```

I use windows task scheduler to run a python script when the computer is locked.

This code uses to work when I am logged in and using the computer, but when it's locked the send keys fails, it used to work with edge version 95, but in recent vesions stopped.

I also have tried to force windows to always focus on browser windows, so the webpage always has the keyboard focus, but it also does not works.

### How can we reproduce the issue?

```shell
Try to fill a text box with a python script when computer is locked.
```

### Relevant log output

```shell
I does not have a log.
```

### Operating System

Windows 10

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge 98.0.1108.43

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 98.0.1108.43

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This sounds like a driver issue. What do Chrome and Firefox do?

**Comment by AutomatedTester** [comment]
This is a chrome issue https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999 and a duplicate #10318

**Comment by AutomatedTester** [comment]
also, on Windows a "scheduled task" doesn't have access to a desktop so is unsupported by selenium
