### ISSUE TITLE
WebDriver interface WebElement now extends TakesScreenshot

### ISSUE THREAD

**Issue by xlenz** [SeleniumHQ/selenium#1032]
Due to changes from 2.46
public interface WebElement extends SearchContext {
to 2.47
public interface WebElement extends SearchContext, TakesScreenshot {

it is now required to implement everywhere 
<X> X getScreenshotAs(OutputType<X> var1) throws WebDriverException;

Is this change really required?

**Comment by lukeis** [comment]
Yes... It's apart of the W3C spec

https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot
