### ISSUE TITLE
[🚀 Feature]: deleteNetworkConditions missing in Javascript

### ISSUE THREAD

**Issue by slhck** [SeleniumHQ/selenium#10322]
### Feature and motivation

Currently the Javascript Chrome WebDriver only has methods to set and get the network conditions:

https://github.com/SeleniumHQ/selenium/blob/66b14c5578a915ae5b931ad857d0cd341c361377/javascript/node/selenium-webdriver/chromium.js#L700-L737

However, other languages support also deleting those conditions, e.g. in Java:

https://github.com/SeleniumHQ/selenium/blob/66b14c5578a915ae5b931ad857d0cd341c361377/java/src/org/openqa/selenium/chromium/ChromiumDriver.java#L286-L288

Or Python:

https://github.com/SeleniumHQ/selenium/blob/341b454c4a3c16a227b4e70e90044eede68f37e4/py/selenium/webdriver/chromium/webdriver.py#L142-L146

Would it be possibe to add the same functionality to Javascript?

### Usage example

```js
driver.setNetworkConditions({ offline: false, throughput: 500, latency: 0 });
driver.deleteNetworkConditions()
```

**Comment by harsha509** [comment]
Basically it was non-official and undocumented Chromium command. If other language bindings has this, then sure we need to implement!

**Comment by slhck** [comment]
Yeah, at least for consistency purposes it would be good. My PR should add this, and from what I can see here, it works as expected. In the meantime I added my own executor method, but it will be easier if there is a public function.
