### ISSUE TITLE
[🐛 Bug]: Python Chrome Options Detach: true not working 

### ISSUE THREAD

**Issue by lestrato** [SeleniumHQ/selenium#10337]
### What happened?

I am looking to keep a driver instance indefinitely, using the `detach: true` chrome option. The window keeps open for a few seconds after the Python script completes, then it closes.

I've also tried `browser = webdriver.Chrome(settings.SELENIUM_DRIVER, options=chrome_options)` 
to no avail.

Appreciate any & all help!

### How can we reproduce the issue?

```shell
if __name__ == '__main__':
    from selenium.webdriver.chrome.options import Options
    from selenium import webdriver
    chrome_options = Options()
    chrome_options.add_experimental_option("detach", True)
    browser = webdriver.Chrome(settings.SELENIUM_DRIVER, chrome_options=chrome_options)
    browser.get('https://www.google.com/')
    browser.maximize_window()
```

### Relevant log output

```shell
$ winpty python robot.py
D:\Youtube\youtube\robot.py:187: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(settings.SELENIUM_DRIVER, chrome_options=chrome_options)
D:\Youtube\youtube\robot.py:187: DeprecationWarning: use options instead of chrome_options
  browser = webdriver.Chrome(settings.SELENIUM_DRIVER, chrome_options=chrome_options)

DevTools listening on ws://127.0.0.1:51710/devtools/browser/4c1fe583-427c-4097-9777-522958188ec5
(venv) 
useme@DESKTOP MINGW64 /d/Youtube/youtube (master)
```

### Operating System

Windows 10

### Selenium version

Python selenium==4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 97.0.4692.99

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 97.0.4692.71

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This is working for me:

```py
from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions

options = ChromeOptions()
options.add_experimental_option("detach", True)
driver = webdriver.Chrome(options=options)
```

Can you verify you aren't calling `driver.quit()` in any after hook? That will close the browser regardless of detach.

**Comment by lestrato** [comment]
Hello! Thanks for the response, I still experience the same issue with your script: my controlled browser closes 2-3 seconds after the script ends. There's no line to call `driver.quit()`
I thought to try updating my browser and using a newer driver (to no avail):
```
Browser version Version 98.0.4758.82 (Official Build) (64-bit)
Chromium driver 98.0.4758.80
```

I wonder what my issue is related to, maybe I can try a reinstall of Chrome.
Do you imagine there might be some automatic garbage collector that is taking over after Python quits?

Latest script:
```python
import settings

from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions

if __name__ == '__main__':
    options = ChromeOptions()
    options.add_experimental_option("detach", True)
    browser = webdriver.Chrome(settings.SELENIUM_DRIVER, options=options)
```

**Comment by lestrato** [comment]
I got the browser to stay open for a lot longer, it still quits eventually though, and sometimes the tab session gives me an `Error code: STATUS_CONTROL_C_EXIT`

What I did differently was I added `options.add_argument('--no-sandbox')`, hoping to bypass security.

---
Edit: Tried with Mozilla then Opera, same story, quits after 3 seconds.

**Comment by lestrato** [comment]
`options.add_experimental_option("detach", True)` is working on my Mac system! I will try another Windows device soon.

**Comment by titusfortner** [comment]
`detach` is a chromium specific feature, so it isn't expected to work for Mozilla.
I can see it as potentially being an issue on Windows vs Mac. If you can duplicate that it is a Windows issue, then it needs to be reported to Google. Thanks.
