### ISSUE TITLE
[🐛 Bug]: When Edge IEmode is run in parallel, one of the operations will conflict with the other.

### ISSUE THREAD

**Issue by HiroyukiSakoh** [SeleniumHQ/selenium#10339]
### What happened?

The CI system automatically runs UI tests in parallel.
When using EdgeIE mode, one test fails.
One Navigate operation will affect the other browser.

### How can we reproduce the issue?

I created a simple, single console program.
[Here](https://github.com/HiroyukiSakoh/ReproEdgeIEModeParallel/blob/main/ReproEdgeIEModeParallel/Program.cs)

I ran the caller's program separately, and got the same result.

### Relevant log output

Log of the execution of the reproducing program.
[Here](https://github.com/HiroyukiSakoh/ReproEdgeIEModeParallel/tree/main/Log_v4.0.0)

### Operating System

Windows10,Windows11

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge 98.0.1108.43

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.0.0

**Comment by HiroyukiSakoh** [comment]
From looking at [cpp/iedriver/BrowserFactory.cpp FindEdgeWindow](https://github.com/SeleniumHQ/selenium/blob/5561cda968e2c392b350e9a1c40bb381491f58a6/cpp/iedriver/BrowserFactory.cpp#L1078), 
I think it is looking at the other handler where the browser handler identifies it.
I changed it so that it only looks at the child handler when the process ID matches the parent window, and it works fine
 now,
but the wait time for Quit is long, so I don't think it's a perfect fix.

[My QuickFix code](https://github.com/HiroyukiSakoh/selenium/commit/44af88bad326f4ba7d3037b5d3e25bd21bfb91f2)

Log when QuickFix IEDriver is executed.
[Here](https://github.com/HiroyukiSakoh/ReproEdgeIEModeParallel/tree/main/Log_QuickFix)

**Comment by titusfortner** [comment]
Can you make a PR with this? It might be a bit before we can get to it, but we appreciate it. Thanks!

**Comment by HiroyukiSakoh** [comment]
@titusfortner 
There are multiple callers to the modified method, 
and I haven't been able to determine if there are any side effects to the modification.
```
IECommandExecutor::OpenNewBrowserTab
IECommandExecutor::CreateNewBrowser
IECommandExecutor::OnAfterNewWindow
IECommandExecutor::OnBrowserReattach
```
I think this might affect #8868 and so on.

Should I still make a pull request?

**Comment by titusfortner** [comment]
You might actually ask about this code idea in that other issue since there are Edge developers following that one.
