### ISSUE TITLE
Selenium RC doesn't recognize opened window in firefox by selectwindow method

### ISSUE THREAD

**Issue by nadi12345** [SeleniumHQ/selenium#1033]
In an automation test, selenium rc opened a new window by clicking a link. but when I try to change the control to newly opened child window, it is not working. selenium.getallwindows by title doesn't returns the title of my window. Please fix ASAP or suggest me... Thanks in advance

**Comment by lukeis** [comment]
Selenium RC is deprecated and no longer receives support. Please switch to WebDriver. You can try to solicit more help on the [selenium-users mailing list](https://groups.google.com/forum/#!forum/selenium-users)
