### ISSUE TITLE
[🚀 Feature]: Support WebDriver BiDi and "log.entryAdded" events (with Firefox)

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#10335]
### Feature and motivation

With the [WebDriver BiDi specification](https://w3c.github.io/webdriver-bidi/) moving forward it would be great to see support for this protocol being added to Selenium. In case of Firefox we already added the `log.entryAdded` event and relevant commands like `session.subscribe` to get relevant logging events for console API calls and Javascript exceptions on the page.

Given the high request of Selenium users for such an API it would be great to move the current implementation for Firefox which is based on CDP over to WebDriver BiDi. On our side we have the following bug on file:

https://bugzilla.mozilla.org/show_bug.cgi?id=1753991

CC'ing @AutomatedTester, @shs96c, @titusfortner, @diemol

### Usage example

From the user's perspective the API for logging events might not change and could probably the same as when using the CDP backend.

**Comment by diemol** [comment]
Added tags for the other bindings so we can track progress.

**Comment by whimboo** [comment]
@diemol who could potentially could give an update of the current implementation status of this feature in Selenium? Thanks.

**Comment by titusfortner** [comment]
I don't think we want to track these additions in issues. We should use Puja's more systematic tracking system.

**Comment by whimboo** [comment]
> I don't think we want to track these additions in issues. We should use Puja's more systematic tracking system.

Out of interest. How does that work?
