### ISSUE TITLE
[🐛 Bug]: Chrome's Webdriver getting stuck on `driver.get(URL)` since v91+

### ISSUE THREAD

**Issue by Joacchim** [SeleniumHQ/selenium#10336]
### What happened?

Hello,

As a pet project, I'm working on a web-extension, which is tested using selenium's python binding.
After a while without activity, I got back to it recently, discovering that my automated tests were no longer able to pass reliably for chrome. Coming here, my issue looked very much like https://github.com/SeleniumHQ/selenium/issues/10002 (where I [commented](https://github.com/SeleniumHQ/selenium/issues/10002#issuecomment-1030918722)), but seems to be slightly different.

To detail the issue, at a very high reproduction rate (but not 100%, so some tests still pass), selenium gets completely stuck on a `driver.get(URL)` call, halting the progress of all tests. Obviously the CI thus times-out after a while without any output. I identified this situation by running our pytest tests with the `--pdb` option, then interrupting with a Ctrl+C keypress to obtain the stack trace (cf my comment in #10002 ).

As it does not seem easy to reproduce with a simple python script, so I suspect that either the fact that we're loading a web-extension, or that the sites we rely on for testing are slow might play an important part in this issue.

Also, attempting to set the following did not help:
 - option: --disable-browser-side-navigation
 - `driver.set_page_load_timeout(30)` failed to trigger the TimeoutException

### How can we reproduce the issue?

For now, I don't have much more than our own repository and its Circle CI tests:
 https://github.com/BookMyComics-Developers/BookMyComics

### Relevant log output

```shell
tests/func/test_register.py::TestRegister::test_escape_key_handling[chrome] ^CFAILED
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

controller = <tests.func.utils.bmc.BmcController object at 0x7f0afa41eb50>
unique_reader = <tests.func.utils.support.manganato.MangaNatoDriver object at 0x7f0afa1742d0>

    @staticmethod
    def test_escape_key_handling(controller, unique_reader):
        """
            Validates that pressing the "ESCAPE" key on the "adder menu"
            discards it.
        """
>       init_sidebar(unique_reader, controller)

tests/func/test_register.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/func/utils/bmc.py:373: in init_sidebar
    reader_driver.load_random(predicate=predicate)
tests/func/utils/__init__.py:27: in wrapper
    return func(*args, **kwargs)
tests/func/utils/__init__.py:46: in wrapper
    ret = func(self, *args, **kwargs)
tests/func/utils/support/manganato.py:33: in load_random
    mangas = self._get_mangas()
tests/func/utils/support/manganato.py:18: in _get_mangas
    self.home()
tests/func/utils/support/manganato.py:26: in home
    self._driver.get('https://manganato.com/')
../../.virtualenvs/bmc37/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py:436: in get
    self.execute(Command.GET, {'url': url})
../../.virtualenvs/bmc37/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py:422: in execute
    response = self.command_executor.execute(driver_command, params)
../../.virtualenvs/bmc37/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py:421: in execute
    return self._request(command_info[0], url, body=data)
../../.virtualenvs/bmc37/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py:443: in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/request.py:79: in request
    method, url, fields=fields, headers=headers, **urlopen_kw
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/request.py:170: in request_encode_body
    return self.urlopen(method, url, **extra_kw)
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/poolmanager.py:375: in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/connectionpool.py:710: in urlopen
    chunked=chunked,
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/connectionpool.py:449: in _make_request
    six.raise_from(e, None)
<string>:3: in raise_from
    ???
../../.virtualenvs/bmc37/lib/python3.7/site-packages/urllib3/connectionpool.py:444: in _make_request
    httplib_response = conn.getresponse()
/usr/lib/python3.7/http/client.py:1348: in getresponse
    response.begin()
/usr/lib/python3.7/http/client.py:315: in begin
    version, status, reason = self._read_status()
/usr/lib/python3.7/http/client.py:276: in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <socket.SocketIO object at 0x7f0afa41ead0>, b = <memory at 0x7f0afa54abb0>

    def readinto(self, b):
        """Read up to len(b) bytes into the writable buffer *b* and return
        the number of bytes read.  If the socket is non-blocking and no bytes
        are available, None is returned.
    
        If *b* is non-empty, a 0 return value indicates that the connection
        was shutdown at the other end.
        """
        self._checkClosed()
        self._checkReadable()
        if self._timeout_occurred:
            raise OSError("cannot read from timed out object")
        while True:
            try:
>               return self._sock.recv_into(b)
E               KeyboardInterrupt

/usr/lib/python3.7/socket.py:589: KeyboardInterrupt
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

### Operating System

Ubuntu/Debian, depending on the environment (personal computer, CI)

### Selenium version

python3.7 selenium=4.1.0 , python3.6 selenium=3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 91+

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 91+

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
are you running tests in parallel or in series?

You're getting the same issue in Selenium 3 & Selenium 4?

**Comment by Joacchim** [comment]
Hello,
Tests are run in a sequential manner, and I've tried to update to Selenium 4 to check for improvements, and I still encounter the issue. (It might reproduce slighly less on my computer, maybe, but that's it).

Note also that chrome does not always block on the same test (to exclude suspicion of a previous test triggering some odd state)

**Comment by titusfortner** [comment]
I mean, it really sounds like the issue is bad performance of the System Under Test.

That said `set_page_load_timeout` should cause a timeout when navigating to a page, and you're saying that it waits until the CI build times out instead?

Can you turn on Chromedriver logging and see what it is recording?

**Comment by Joacchim** [comment]
Can do, do you have a pointer to the proper method to ensure I retrieve all logs from my CI ? I'll try it this weekend, I'm unsure I'll have time before then.

**Comment by titusfortner** [comment]
https://chromedriver.chromium.org/logging

**Comment by Joacchim** [comment]
Hello, took me some time, thanks for the tip.
Here's the output of a case where the browser got stuck, but I'm unable to interpret it myself, so I hope it'll prove useful.
[chrome.log](https://github.com/SeleniumHQ/selenium/files/8092703/chrome.log)

**Comment by pdille** [comment]
I've also been experiencing this behavior with selenium-webdriver (v4.1.1) under nodejs (v12.22.10)

driver.get() calls are being made sequentially and system is not under heavy load at all. As with the original poster, it's not 100% reproducible.

**Comment by titusfortner** [comment]
Yeah, looking at the logs, there's nothing obvious where it is in a bad state for Selenium.
Unfortunately, there isn't anything Selenium can do here.
Either it is a bug with what Chromedriver is doing, and you can try raising the issue with Google (https://bugs.chromium.org/p/chromedriver/issues/list), or it is an intermittent issue with your system under test.
