### ISSUE TITLE
[🐛 Bug]: Click does not work out

### ISSUE THREAD

**Issue by allanbides** [SeleniumHQ/selenium#10330]
### What happened?

Hi,

I use python 3.9.5 and selenium 4.1.0 with microsoft Edge 98.0.1108.43 on Windows 10  and operations like below when I have to click in something at the page does not work in any case.

```
#element is the web element I want to fill
element = "element_name"
date = driver.find_element(By.ID, element)

date.click()
```

I figure out to solve this with below code but it is not the ideal and genarates some other problems.

```
webelement.WebElement.click = lambda self : driver.execute_script("arguments[0].click();", self)
```

Is it a Known Bug?

Thanks.

### How can we reproduce the issue?

```shell
Any code the needs to click in buttons or links.
```

### Relevant log output

```shell
No log to provide.
```

### Operating System

Windows 10

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Edge 98.0.1108.43

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 98.0.1108.43

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Clicking links and buttons definitely works in Selenium, so you haven't provided us with a way to duplicate your error.

Does clicking the element not do anything, or does it result in an error? 

There are 2 likely possibilities. 
1. It is some kind of timing issue and the browser isn't ready to do what you need when you click it. Sometimes dynamic sites will display the element but won't attach the action to it in time. What you should wait for will depend on what kind of error you get. If you aren't getting an error, put a small sleep and see if it fixes it.
2. Selenium makes sure that elements are interactable to properly replicate an actual user's experience, whereas using JavaScript will allow you to click anything. The error message will tell you what is causing the problem.
