### ISSUE TITLE
[🐛 Bug]: MoveToElement - RemoteWebDriver threw an exception of type 'System.InvalidOperationException'

### ISSUE THREAD

**Issue by sc-mk** [SeleniumHQ/selenium#10344]
### What happened?

Hi,
I'm using code below for move to element, but actionExecutor returns an exception.
Chromedriver version: 98.0.4758.48 win32
Can you help me, please?
![actionExecutor_exception](https://user-images.githubusercontent.com/3882110/153233507-716c3b95-ac6e-4748-8000-074b9fdf0a0c.png)

### How can we reproduce the issue?

```shell
IWebElement element = driver.FindElement(By.LinkText(link_text));
Actions ac = new Actions(driver);
ac.MoveToElement(element);
ac.Build().Perform();
```
```


### Relevant log output

```shell
ac > actionExecutor

ApplicationCache = '((OpenQA.Selenium.Remote.RemoteWebDriver)ac.actionExecutor).ApplicationCache' threw an exception of type 'System.InvalidOperationException'
LocationContext = '((OpenQA.Selenium.Remote.RemoteWebDriver)ac.actionExecutor).LocationContext' threw an exception of type 'System.InvalidOperationException'
```

### Operating System

Windows 10

### Selenium version

3.14

### What are the browser(s) and version(s) where you see this issue?

Chrome 98.0.4758.82

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.48

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
First, please update to Selenium 4.1 so we can evaluate with latest code.
Second, is this actually halting your test, or is it just recording an error that was rescued in the code?

If it's an error, please copy and paste the full stack trace.

**Comment by sc-mk** [comment]
I caught this exception during debugging.

**Comment by titusfortner** [comment]
Right, what happens when you run with latest version of Selenium without catching the exception.

**Comment by sc-mk** [comment]
Works with version 4.1
Thank you for advice, Titus.

**Comment by sc-mk** [comment]
Hi @titusfortner 

bad news, the same problem is back.
((OpenQA.Selenium.WebDriver)ac.ActionExecutor).ApplicationCache = '((OpenQA.Selenium.WebDriver)ac.ActionExecutor).ApplicationCache' threw an exception of type 'System.InvalidOperationException'

I'm using the latest version, all is updated.
Selenium version: 4.1
"browserName": "chrome",
"browserVersion": "98.0.4758.102",
"chromedriverVersion": "98.0.4758.102"

Can you help me, please?

**Comment by titusfortner** [comment]
Ah, sorry, wasn't even paying attention to the method. This is not a valid endpoint for w3c, and is no longer supported by Chrome.

**Comment by titusfortner** [comment]
@mariankral wrt https://github.com/SeleniumHQ/selenium/issues/10397#issuecomment-1059146375

Are you just getting log outputs with the word "error" in them, or are you getting errors when trying to do something with Selenium?
