### ISSUE TITLE
[🐛 Bug]: Headless is ignored for Firefox when CapabilityType.LOGGING_PREFS is set

### ISSUE THREAD

**Issue by christophs78** [SeleniumHQ/selenium#10349]
### What happened?

Headless worked with Selenium 3.x for Chrome and Firefox.
With Selenium 4.1.2 it does not work for Firefox anymore. (Firefox is still started with UI)

~~After some debugging i currently think it´s lost there:~~
![image](https://user-images.githubusercontent.com/10461942/153289191-1cb97ab2-b4d9-4063-9e8a-fcaabd3a2fb3.png)

### How can we reproduce the issue?

```java
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions = firefoxOptions.setHeadless(true);
return new FirefoxDriver(firefoxOptions);
```
```

### Operating System

Windows 11

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 97

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

### Are you using Selenium Grid?

-

**Comment by diemol** [comment]
I cannot reproduce this, I created this small project for that and Firefox is started headless.

https://github.com/diemol/selenium-issues/tree/master/selenium/issue-10349

**Comment by titusfortner** [comment]
Agreed, this is working as expected.

```
FirefoxOptions options = new FirefoxOptions();
options.setHeadless(true);
driver = new FirefoxDriver(options);
```

`args` end up inside the `moz:firefoxOptions` map, so you aren't seeing it in the top level of the `caps` object.

Let us know if you continue to have difficulties, and always feel free to reach out to us on chat https://www.selenium.dev/support/#ChatRoom

**Comment by christophs78** [comment]
Sorry for pasting an incomplete reproducer.... (too late, too tired?)

Headless stops working with Firefox when i enable CapabilityType.LOGGING_PREFS. Is this expected because Firefox can do this only with active UI?

```java
public class FfHeadless {

    public static void main (String[] args) {
        FirefoxOptions options = new FirefoxOptions();
        options.setHeadless(true);
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.BROWSER, Level.ALL);
        options.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);
        FirefoxDriver driver = new FirefoxDriver(options);
        driver.get("https://selenium.dev");
        driver.quit();
    }

}
```

**Comment by titusfortner** [comment]
Oh, interesting, yeah, then this is a geckodriver issue.
