### ISSUE TITLE
[🐛 Bug]: Ruby `send_keys` wrong for combination like `element.send_keys([:shift, 'a'])` after update to Chromedriver v98

### ISSUE THREAD

**Issue by ShockwaveNN** [SeleniumHQ/selenium#10343]
### What happened?

Not sure that this is a best place to report it, I think it may be a bug in Chromedriver itself, but have a bad experience contacting google issue tracker, so I'll start in this repo, sorry if I'm doing this wrong

So after updating Chromedriver to v98 I got troubles with sending those combinations to input areas:
```
element.send_keys([:shift, 'a'])
element.send_keys([:control, 'a'])

```
And probably all others combination of several keys

Example code is attached with chromedriver included:
[chromedriver-bug-send-keys.zip](https://github.com/SeleniumHQ/selenium/files/8033620/chromedriver-bug-send-keys.zip)

### How can we reproduce the issue?

I've attached archive with required files, but steps are:

1. Create HTML file `test.rb` with:
```
<html lang="en">
    <body>
        <label>
            <input>
        </label>
    </body>
</html>

```

2. Create this spec file `test_input_spec.rb`, which will compare result of execution of Chromedriver v97 and v98:
```
# frozen_string_literal: true

require 'rspec'
require 'selenium-webdriver'

text_to_input = 'TestText'

describe 'text_input' do
  it 'chromedriver 97' do
    service = Selenium::WebDriver::Chrome::Service.new(path: "#{Dir.pwd}/chromedriver_linux_97")

    driver = Selenium::WebDriver.for(:chrome, service: service)
    driver.navigate.to("file://#{Dir.pwd}/test.html")
    element = driver.find_element(:xpath, '//input')
    element.send_keys(text_to_input)
    element.send_keys([:shift, 'a'])
    expect(element.attribute('value')).to eq("#{text_to_input}A")
  end

  it 'chromedriver 97' do
    service = Selenium::WebDriver::Chrome::Service.new(path: "#{Dir.pwd}/chromedriver_linux_98")

    driver = Selenium::WebDriver.for(:chrome, service: service)
    driver.navigate.to("file://#{Dir.pwd}/test.html")
    element = driver.find_element(:xpath, '//input')
    element.send_keys(text_to_input)
    element.send_keys([:shift, 'a'])
    expect(element.attribute('value')).to eq("#{text_to_input}A")
  end
end
```

3. Download `ChromeDriver 97.0.4692.71` and `ChromeDriver 98.0.4758.80` and place it in same folder as `chromedriver_linux_97` and `chromedriver_linux_98`

4. run ` rspec text_input_spec.rb`
and see output for errors.

And of course I can enter `A` as `A`, not as `[:shift, 'a']`, but it's just for simplicity of example

### Relevant log output

```shell
Output of this script will be:

.F

Failures:

  1) text_input chromedriver 97
     Failure/Error: expect(element.attribute('value')).to eq("#{text_to_input}A")
     
       expected: "TestTextA"
            got: "TestTextA"
     
       (compared using ==)
     # ./text_input_spec.rb:28:in `block (2 levels) in <top (required)>'

Finished in 2.28 seconds (files took 0.14498 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./text_input_spec.rb:20 # text_input chromedriver 97
```

So Chromedriver 97 correctly calls `[:shift, 'a']` as `A`

But chromedriver 98 input `A` instead (some kind of incorrect unicode symbol)

You can see it on screenshot:

### Operating System

Ubuntu 20.04

### Selenium version

ruby gem selenium-webdriver (4.1.0)

### What are the browser(s) and version(s) where you see this issue?

 98.0.4758.80 

### What are the browser driver(s) and version(s) where you see this issue?

98.0.4758.80 is broken and everything ok on 97.0.4692.71

### Are you using Selenium Grid?

Nope

**Comment by diemol** [comment]
This is a ChromeDriver issue, which several people are bumping into, please star to follow this issue https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999

**Comment by ShockwaveNN** [comment]
Thanks )

Tried to find in chromedriver but without luck )
