### ISSUE TITLE
[🐛 Bug]: Not possible to locate Element that is a child of <form>

### ISSUE THREAD

**Issue by ChristianErdtmann** [SeleniumHQ/selenium#10347]
### What happened?

Hey iam trying to select elements in a form iam now allready on the secound website where i got this problem.
Here ist the HTML Code:
<div class="animate form login_form">
            <section class="login_content">
                <a href="/"><img src="../img/logo.png" width="150px" border="0" alt="Mailinator logo"></a>
                <br><br>
                <h1 style="color:#000;">Get Started with your Mailinator Trial!</h1>
                <h2>Set Your Password</h2>

                <form>
                    <div id="many_team_invite_error" style="color:lightcoral;text-align: center;border:none;">
                    </div>
                    <div>
                        <h1>affiliate96@it-ce.de</h1>
                    </div>
                    <br>
                    <div>
                        <input type="password" id="many_team_invite_password" aria-label="Password" style="background-color: white;color:black;" onkeydown="if (event.keyCode == 13) { many_team_invite_v3('affiliate96@it-ce.de', '1079505192702'); return false; }" class="form-control" placeholder="Set Your Password" required="">
                    </div>
                    <div>
                        <input type="password" id="many_team_invite_reenter" aria-label="Reenter password" style="background-color: white;color:black;" onkeydown="if (event.keyCode == 13) { many_team_invite_v3('affiliate96@it-ce.de', '1079505192702'); return false; }" class="form-control" placeholder="Re-Enter Password" required="">
                    </div>
                    <div>
                        <a class="btn btn-default submit" onclick="many_team_invite_v3('affiliate96@it-ce.de', '1079505192702');">Submit</a>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">
                        <p style="color:#000;background-color: #fff;">Already have an account?
                            <a href="/v3/login.jsp" class="to_register" style="color:#000;background-color: #fff;"> Log in </a>
                        </p>

                        <div class="clearfix"></div>
                        <br>

                        <div>
                            <p style="color:black;">Copyright 2022 Manybrain, LLC. All Rights Reserved
    <br>
    <a style="color:black;background-color: white;font-weight: bold;" href="/v4/terms.html" aria-label="Terms and Conditions">
        Terms &amp; Conditions</a>
    <a style="color:black;background-color: white;font-weight: bold;" href="/v4/privacy.html" aria-label="Privacy Policy">Privacy Policy</a>
    <a style="width:100%;cursor: pointer;font-weight:bold;text-align: left;background-color: white;color:black;font-weight:bold;" tabindex="0" href="/v4/accessibility.html">Accessibility</a>
    <a style="width:100%;cursor: pointer;font-weight:bold;text-align: left;background-color: white;color:black;font-weight:bold;" tabindex="0" href="/v4/security.html">Security</a>
</p>

                        </div>
                    </div>
                </form>
            </section>
        </div>

I want to enter the passwort in the input if i check my elementpath in webbrowser inspector it find the element but selenium dont find it. Its not in an iframe but its in a form. I allready tried to switch with:

driver3.SwitchTo().Frame(driver3.FindElement(By.XPath("//section[@class='login_content']/form")));

But then it said the Element is not a frame.
Thats right :D its a form but i cant find a way in web to get elements inside a form.

Is this a bug or what should i do to get it to work?

### How can we reproduce the issue?

```shell
Try to locate an element inside a <form> Children.
```

### Relevant log output

```shell
Element is not a frame
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 98.0.4758.82

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 98.0.4758.82 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
If the form element is inside a frame, you have to first locate the frame element, switch to the frame associated with the frame element, then locate the form element inside that frame.
