### ISSUE TITLE
[🐛 Bug]: When adding Selenium.WebDriver to C# project using VSCode, the project doesn't compile

### ISSUE THREAD

**Issue by tarekahf** [SeleniumHQ/selenium#10354]
### What happened?

I was following the steps here:

https://www.fleekitsolutions.com/use-selenium-c-visual-studio-code/

To use Selenium 4 with vs code. I installed .NET 5 and .NET 6 SDK. 

I created the sample Hello World Project using `dotnet new console` and tried to import the Selenium.WebDriver package using NuGet, and run `dotnet restore`, I get the following error:

`error NU1100: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for 'net6.0'.`
![vscode CS Selenium error](https://user-images.githubusercontent.com/20842027/153446555-60f02daf-6a29-4cde-9f49-fba6898bfa1e.png)

### How can we reproduce the issue?

```shell
- Open vscode
- Switch to .NET 5 to verify or use .NET 6 (the default and latest one installed)
`dotnet new globaljson --sdk-version 5.0.405 --force`
- Create sample dotnet project using `dotnet new console`
- Run the project ==> is is good
- Import Selnium.WebDriver using NuGet Add Package (Ctrl-Shift-P)
- Run `dotnet restore` you will get this error:
`error NU1100: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for 'net6.0'`
```

### Relevant log output
- The OmniSharp server output will display the following:
```shell
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj'.
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj(0,0): Error: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for '.NETFramework,Version=v4.8'.
c:\Projects\Selenium\demoProject\FirsProj\FirsProj.csproj(0,0): Error: Unable to resolve 'Selenium.WebDriver (>= 4.1.0)' for '.NETFramework,Version=v4.8/win7-x86'.

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: FirsProj
[warn]: OmniSharp.MSBuild.PackageDependencyChecker
        FirsProj: Did not find 'Selenium.WebDriver' in lock file.
```

### Operating System

Windows 10 Enterprise

### Selenium version

C# with .NET 6 and VSCode

### What are the browser(s) and version(s) where you see this issue?

98.0.4758.82

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.82

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
Selenium does not yet support .NET 6, please use .NET 5

.NET 6 requires Visual Studio 2022, and Selenium is built with Bazel which doesn't yet support VS 2022.
When down-level IDE support is available or Bazel supports VS 2022, we'll be able to provide support for it.

**Comment by tarekahf** [comment]
Thank you @titusfortner for the update. Could you please point me to the link where I can tell which .NET version is supported for Selenium?

**Comment by titusfortner** [comment]
I think it's shown in nuget what is supported:

https://www.nuget.org/packages/Selenium.WebDriver/

**Comment by tarekahf** [comment]
It's not mentioned anywhere... Unless I can't find it. Please tell me how to find it.

**Comment by titusfortner** [comment]
There's a list in the dependencies tab.

Also our build tool uses this list — https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/selenium-dotnet-version.bzl

**Comment by tarekahf** [comment]
Thank you so much for the great info ...

I came across this section in NuGet gallery:

> .NETFramework 4.5
> No dependencies.
> .NETFramework 4.6
> No dependencies.
> .NETFramework 4.7
> No dependencies.
> .NETFramework 4.8
> No dependencies.
> .NETStandard 2.0
> Newtonsoft.Json (>= 12.0.3)
> .NETStandard 2.1
> Newtonsoft.Json (>= 12.0.3)
> net5.0
> Newtonsoft.Json (>= 12.0.3)

I want to be sure I am reading the above correctly... please bear with me...

So, this means only the listed .NET versions above are supported, correct? Now since I used .NET 5, I have to add the Netonsoft.Json package, correct?

So far, I only set up the Hello World example using the `dotnet new console` command line under vscode and added the Selenium.WebDriver package latest version using NuGet. Now the project is compiling. Note that I switched the project to .NET 6 and it is still compiling, is that expected? I didn't yet start using Selenium.WebDriver APIs. I will do that soon. I managed so far to compile the basic Hello World program with Selenium WebDriver added to the C# project under vscode.

The problem in my case is that I installed everything using the latest MS Build Tools installer based on Visual Studio 2022. I think this tool installed the NuGet package manager but it didn't initialize the config file under `%appdata%\NuGet\nuget.config` as it was empty. I discovered this after long hours of research.

I am planning to edit the related Selenium documentation to point out the possible issue of the `nuget.config` is empty and how to get started using vs code and which .NET parts to install. This part is so confusing as there are many variations such as .NET SDK, Framework, Developer Pack, .NET Core, .NET Standard ...etc.

I appreciate your feedback.

Tarek

**Comment by titusfortner** [comment]
> I have to add the Netonsoft.Json package

No, Nuget handles that. I pointed out that location since it explicitly lists which frameworks are supported. I wouldn't expect things to work with .NET 6.

Since I'm on a Mac, I've only ever implemented Selenium with .NET core (e.g., https://github.com/SeleniumHQ/seleniumhq.github.io/tree/dev/examples/dotnet/SeleniumDocs). I'm not sure advantages of using Core vs Framework on a Windows machine.
