### ISSUE TITLE
[🐛 Bug]: Wrong screenshot is generated for elements within iframes

### ISSUE THREAD

**Issue by gadragomir** [SeleniumHQ/selenium#10350]
### What happened?

I am trying to take a screenshot of an element within an iframe using both TakesScreenshot and AShot classes upon switching to that certain iframe and I receive a wrong screenshot which is not of that element.

### How can we reproduce the issue?

```shell
1. Have either Chrome 98.0.4758.82 or Microsoft Edge 98.0.1108.43 installed
2. Execute the following code on any website that has elements within an iframe (used http://demo.automationtesting.in/Frames.html for this test):

TakesScreenshot:
String currentUserDirectory = System.getProperty("user.home");
    File screenshot = ((TakesScreenshot) getWebDriver()).getScreenshotAs(OutputType.FILE);
    BufferedImage fullImg = ImageIO.read(screenshot);
    
    Point point = element.getLocation();
    
    setElementWidth(element.getSize().getWidth());
    setElementHeight(element.getSize().getHeight());
    
    BufferedImage elementScreenshot = fullImg.getSubimage(point.getX(), point.getY(), elementWidth, elementHeight);
    ImageIO.write(elementScreenshot, "png", screenshot);
    
    File screenshotPath = new File(currentUserDirectory + "\\Desktop\\" + " " + screenshotName);
    FileUtils.copyFile(screenshot, screenshotPath);

Test class method:

TakeScreenshot takeScreenshot = new TakeScreenshot(getWebDriver());
    
    TakeScreenshot takeScreenshot = new TakeScreenshot(getWebDriver());

    Thread.sleep(2000);
    getWebDriver().switchTo().frame(singleFrame);
    testElement.sendKeys("test");
    takeScreenshot.elementScreenshot(testElement, "TestElementTakesScreenshot.png"); // TakesScreenshot method
```

### Relevant log output

```shell
No issues are received in the console.
```

### Operating System

Windows 11

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 98.0.4758.82 & Microsoft Edge 98.0.1108.43

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.80 & EdgeDriver 98.0.1108.43

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
In short, it is impossible to know what is going on with segments of your code. We need a code snippet we can copy and paste to our IDE to reproduce the issue.

**Comment by gadragomir** [comment]
> In short, it is impossible to know what is going on with segments of your code. We need a code snippet we can copy and paste to our IDE to reproduce the issue.

I have added the code to this Github repo: https://github.com/gadragomir/ElementScreenshot
Hope it's a lot better now. If not, let me know.

**Comment by titusfortner** [comment]
You can just use the method on the element itself:

```
        driver.get("http://demo.automationtesting.in/Frames.html");
        driver.switchTo().frame("singleframe");

        WebElement input = driver.findElement(By.tagName("input"));
        input.sendKeys("test");

        byte[] screenshotAs = input.getScreenshotAs(OutputType.BYTES);
        Path screenshot = Paths.get("path/to/TestElementTakesScreenshot.png");
        Files.write(screenshot, screenshotAs);
```
