### ISSUE TITLE
[🚀 Feature]: How to use Python to modify the data source of XPath

### ISSUE THREAD

**Issue by leecmd** [SeleniumHQ/selenium#10367]
### Feature and motivation

How to use Python to modify the data source of XPath

When I use XPath to locate in IE9, the running speed is too slow, but I can only find a way for Java to modify the XPath source, so I need some help. Thank you

### Usage example

java like:
       selenium = new DefaultSelenium(location, port, browser, targetPath);   
        selenium.start();   
        selenium.useXpathLibrary("javascript-xpath");  

How should Python be modified

**Comment by titusfortner** [comment]
This is Selenium RC (Selenium 1.0) functionality, which has not been actively developed in over a decade. 

In WebDriver, the means for implementing XPath is managed by the browser vendor driver and is not adjustable by the end user.
