### ISSUE TITLE
[🐛 Bug]: The HTTP request to the remote WebDriver server for URL http://localhost:57871/session/9ee0614f78d6247023cd56f0b84f1575/url timed out after 60 seconds.

### ISSUE THREAD

**Issue by ChristianErdtmann** [SeleniumHQ/selenium#10362]
### What happened?

Hey i try to open a URL with ChromeDriver and get the error "The HTTP request to the remote WebDriver server for URL http://localhost:57871/session/9ee0614f78d6247023cd56f0b84f1575/url timed out after 60 seconds."

I allready tried to set timeout up to 180 but this dont worked.

The same driver open 2 Websites bevore the error occurs. If it try to open the 3. Website with this driver it alltimes crash.

Is there a solution for this?

It does not crash everytime but in 90% of the runs it crash.

I have 2 drivers running and i allready tried to sleep between the stat of the drivers. But that dont worked.

I have allready added this 2 lines:
options.AddArgument("no-sandbox");
options.AddArgument("--remote-debugging-port=0");
But that dont worked.

Here is the code (is skipped it a little bit to the relevant lines because its a big program):

ChromeDriver driver = null;
ChromeDriver driver3 = null;
ChromeOptions options = new ChromeOptions();

options.AddArguments("disable-blink-features=AutomationControlled");
options.AddArgument("no-sandbox");
options.AddArgument("--remote-debugging-port=0");

driver3 = new ChromeDriver(options);
Thread.Sleep(3000);
driver = new ChromeDriver(options);

driver.Navigate().GoToUrl("https://www.behindthename.com/random/random.php?number=1&sets=1&gender=m&surname=&randomsurname=yes&usage_ger=1");

Thread.Sleep(10000);

driver.Navigate().GoToUrl("https://all-inkl.com/login/");

Thred.Sleeop(10000);

driver.Navigate().GoToUrl("https://all-inkl.com/login/");

I dont know why but alltime it tries to open the secound time https://all-inkl.com/login/ i got a crash.

### How can we reproduce the issue?

```shell
Dont know see code above.
```

### Relevant log output

```shell
No
```

### Operating System

Windows 10

### Selenium version

4.0.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 98.0.4758.82

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 98.0.4758.82

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
@ChristianErdtmann what happens when you upgrade to the latest release? Also, what happens if you use a different url than https://all-inkl.com/login/?

If it is still failing after trying the suggestions above, a complete code snippet to reproduce the issue would be necessary.

**Comment by ChristianErdtmann** [comment]
Dont know so right what you mean with update to latest release. I allready use version 4.1.0 and I use the latest nuget paket available in visual studio. How should i upgrade and what?

I now testin it with different URLs and make a stak trace i send the results here if iam ready

**Comment by ChristianErdtmann** [comment]
It fails with other URLs to here is the log:

13.02.2022 16:59:41: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.GenerateSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 575.  The HTTP request to the remote WebDriver server for URL http://localhost:51652/session/b481c8a0500d376f46d0277b0d1b570f/url timed out after 60 seconds.
13.02.2022 17:00:41: Failed by open URL https://all-inkl.com/login/    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.GenerateSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 585.  The HTTP request to the remote WebDriver server for URL http://localhost:51652/session/b481c8a0500d376f46d0277b0d1b570f/url timed out after 60 seconds.
13.02.2022 17:02:48: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.DeleteSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 673.  The HTTP request to the remote WebDriver server for URL http://localhost:51652/session/b481c8a0500d376f46d0277b0d1b570f/url timed out after 60 seconds.
13.02.2022 17:03:48: Failed by open URL https://all-inkl.com/login/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.DeleteSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 684.  The HTTP request to the remote WebDriver server for URL http://localhost:51652/session/b481c8a0500d376f46d0277b0d1b570f/url timed out after 60 seconds.
13.02.2022 17:06:42: Start Generate random Name and Logindata
13.02.2022 17:06:50: Finished random Name and Logindata Generation
13.02.2022 17:06:50: Erstelle Subdomain und Mail
13.02.2022 17:07:52: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.GenerateSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 577.  The HTTP request to the remote WebDriver server for URL http://localhost:52681/session/a5d88fec55a9bef8e1f82a58236f4787/url timed out after 60 seconds.
13.02.2022 17:08:52: Failed by open URL https://all-inkl.com/login/    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.GenerateSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 587.  The HTTP request to the remote WebDriver server for URL http://localhost:52681/session/a5d88fec55a9bef8e1f82a58236f4787/url timed out after 60 seconds.
13.02.2022 17:09:59: Error: The HTTP request to the remote WebDriver server for URL http://localhost:52681/session/a5d88fec55a9bef8e1f82a58236f4787/element timed out after 60 seconds.    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   bei OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   bei OpenQA.Selenium.By.FindElement(ISearchContext context)
   bei OpenQA.Selenium.WebDriver.FindElement(By by)
   bei BotCreator.Program.GenerateSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 598.
   bei BotCreator.Program.Main(String[] args) in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 79.
13.02.2022 17:10:59: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.DeleteSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 675.  The HTTP request to the remote WebDriver server for URL http://localhost:52681/session/a5d88fec55a9bef8e1f82a58236f4787/url timed out after 60 seconds.
13.02.2022 17:11:59: Failed by open URL https://all-inkl.com/login/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei BotCreator.Program.DeleteSubdomain() in D:\IT-CE Dropbox\Christian Erdtmann\ALLES\CHRISTIAN\05_PROGRAMMING_PROJECTS\BotCreatorTor\BotCreator\Program.cs:Zeile 686.  The HTTP request to the remote WebDriver server for URL http://localhost:52681/session/a5d88fec55a9bef8e1f82a58236f4787/url timed out after 60 seconds.

**Comment by ChristianErdtmann** [comment]
It worked fine for the last two weeks but now it crashe all the time i work with 2 other programs they i have written with the same drivers and all the same for the other programs all is ok but this one alltimes crash.

**Comment by ChristianErdtmann** [comment]
Sometimes i got the same error with 1 of the other programs but not so often

**Comment by ChristianErdtmann** [comment]
Here are some Codesnippets:

--START OF THE PROGRAM-- (skripped to relevant part)

ChromeDriver driver = null;
        Random rnd = new Random();
        ChromeDriver driver3 = null;
        ChromeOptions options = new ChromeOptions();

        static void Main(string[] args)
        {
            Program program = new Program();
            try
            {
                //Read Botnumber
                program.ReadBotNumber();
                //increment Botnumber
                int iBotNumber = Convert.ToInt32(program.BotNumber);
                iBotNumber++;
                program.BotNumber = iBotNumber.ToString();


                //Write Botnumber
                program.WriteLastBotnumber();


                program.options.AddArguments("disable-blink-features=AutomationControlled");
                program.options.AddArgument("no-sandbox");
                program.options.AddArgument("--remote-debugging-port=0");
                //program.driver3 = new ChromeDriver(ChromeDriverService.CreateDefaultService() ,program.options, TimeSpan.FromSeconds(180));
                //program.driver = new ChromeDriver(ChromeDriverService.CreateDefaultService(), program.options, TimeSpan.FromSeconds(180));
                program.driver3 = new ChromeDriver(program.options);
                Thread.Sleep(3000);
                program.driver = new ChromeDriver(program.options);

                Thread.Sleep(5000);

                //Generate Random name and Logindata
                program.Logger(@"Start Generate random Name and Logindata");
                program.GetRandomName();
                program.Logger(@"Finished random Name and Logindata Generation");

                //program.GenerateNamesFromNameFiles();

                program.Logger("Erstelle Subdomain und Mail");
                program.GenerateSubdomain();

                program.sPass = program.RandomString(10, false);


In the function GetRandomName() the driver opens https://www.behindthename.com/random/random.php?number=1&sets=1&gender=m&surname=&randomsurname=yes&usage_ger=1 fine. I got never an error with this first URL that is open in the driver but with nearly all following URLs i try to open.

The Site is loading compleate in the browser i can see all and interact with elements. But the program say the request timed out i dont understand this so right because the http request was seccesfull and the site hast build. But i get this error.



--- FUNCTION GENERATE SUBDOMAIN ------ (skripped to relevant part)
public void GenerateSubdomain()
        {
            string sSubdomain;
            Thread.Sleep(2000);

            try
            {
                driver.Navigate().GoToUrl("https://www.rettmobil-international.com/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://www.rettmobil-international.com/" + ex.StackTrace + "  " + ex.Message);
            }

            try
            {
                driver.Navigate().GoToUrl("https://all-inkl.com/login/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://all-inkl.com/login/ " + ex.StackTrace + "  " + ex.Message);
            }



----- FUNCTION DELETE SUBDOMAIN ----- (skripped to relevant part)

public void DeleteSubdomain()
        {

            try
            {
                driver.Navigate().GoToUrl("https://www.rettmobil-international.com/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://www.rettmobil-international.com/" + ex.StackTrace + "  " + ex.Message);
            }


            try
            {
                driver.Navigate().GoToUrl(" https://all-inkl.com/login/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://all-inkl.com/login/" + ex.StackTrace + "  " + ex.Message);
            }

            Thread.Sleep(7000);



The code above also containse now the other testURLsi insert to test if it fails with other URLs too.

**Comment by ChristianErdtmann** [comment]
I dont think that the problem is my code. I think its something other because sometimes its working. If the code would be wrong it would never be working. I think so :D but i dont know

**Comment by pujagani** [comment]
Thank you for sharing the details. However, the code snippet shared is not reproducible as it. Based on what is shared, the issue you faced happens to seems to happen when multiple drivers are run so I created and ran the example below. 

```
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Chrome;
using System;
using System.Threading;

namespace SeleniumDotNetUnitTests
{
    public class MultipleUrlsTest
    {
        [Test]
        public void shouldBeAbleTocreate3Drivers()
        {
            for (int i = 0; i <= 10; i++)
            {
                WebDriver driver1 = new ChromeDriver("/Users/Puja/Downloads/webdrivers/");
                WebDriver driver2 = new ChromeDriver("/Users/Puja/Downloads/webdrivers/");
                WebDriver driver3 = new ChromeDriver("/Users/Puja/Downloads/webdrivers/");

                try
                {
                    driver1.Navigate().GoToUrl("https://www.behindthename.com/random/random.php?number=1&sets=1&gender=m&surname=&randomsurname=yes&usage_ger=1");
                }
                catch
                {
                    Assert.Fail();
                }

                Thread.Sleep(10000);

                try
                {
                    driver1.Navigate().GoToUrl("https://all-inkl.com/login/");
                }
                catch
                {
                    Assert.Fail();
                }

                Thread.Sleep(10000);

                try
                {
                    driver1.Navigate().GoToUrl("https://all-inkl.com/login/");
                }
                catch
                {
                    Assert.Fail();
                }
                driver1.Close();
                driver2.Close();
                driver3.Close();
            }
        }
    }
}
```

The test did not fail once and I also ran the test with just one driver as well. 
Selenium version - 4.1.0
OS - MacOS BigSur 11.4

The .csproj file is shared below:
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.1.0" />
    <PackageReference Include="Selenium.Support" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Selenium.WebDriver" />
    <None Remove="Selenium.Support" />
  </ItemGroup>
</Project>
```
Please check if the issue you are facing is due to a dependency version. If not, then as requested, we will need a complete reproducible test script/project. It will help us reproduce the issue and fix it. Thank you!

**Comment by ChristianErdtmann** [comment]
Ok thanks will try it in the afternoon and report results.

**Comment by ChristianErdtmann** [comment]
Your Code worked fine for me. No errors. My other programs have no error too.

I copied the Project now minimized it to the relevant code and can reproduce the error with that. (Sometimes it works but sometimes it crash)
Here is the full code:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Net;
using System.IO;
using Microsoft.Win32.TaskScheduler;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using Newtonsoft.Json.Linq;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Firefox;

namespace TestHTMLResponse
{
    class Program
    {
        string sPass = "";
        string vorname = "";
        string name = "";

        string sMailAllInkl = "";
        string sPassAllInkl = "";

        string sFullSubdomain;
        string sDomain = "";

        ChromeDriver driver = null;
        Random rnd = new Random();
        ChromeDriver driver3 = null;
        ChromeOptions options = new ChromeOptions();

        static void Main(string[] args)
        {
            Program program = new Program();
            try
            {
                program.options.AddArguments("disable-blink-features=AutomationControlled");
                program.options.AddArgument("no-sandbox");
                program.options.AddArgument("--remote-debugging-port=0");
                program.driver3 = new ChromeDriver(program.options);
                Thread.Sleep(3000);
                program.driver = new ChromeDriver(program.options);

                Thread.Sleep(5000);

                //Generate Random name and Logindata
                program.Logger(@"Start Generate random Name and Logindata");
                program.GetRandomName();
                program.Logger(@"Finished random Name and Logindata Generation");

                //program.GenerateNamesFromNameFiles();

                program.Logger("Erstelle Subdomain und Mail");
                program.GenerateSubdomain();

                program.sPass = program.RandomString(10, false);

                //Delete Subdomain
                program.DeleteSubdomain();

                //Close Drivers
                program.Logger("FINISHED: Close drivers and End Program");
                if (program.driver != null)
                {
                    program.driver.Close();
                    program.driver.Quit();
                }
                if (program.driver3 != null)
                {
                    program.driver3.Close();
                    program.driver3.Quit();
                }
            }
            catch (Exception ex)
            {
                program.Logger("Error: " + ex.Message + " " + ex.StackTrace);

                program.DeleteSubdomain();

                if (program.driver != null)
                {
                    program.driver.Close();
                    program.driver.Quit();
                }
                if (program.driver3 != null)
                {
                    program.driver3.Close();
                    program.driver3.Quit();
                }
                throw;
            }
        }

        public void GetRandomName()
        {
            try
            {
                driver.Navigate().GoToUrl("https://www.behindthename.com/random/random.php?number=1&sets=1&gender=m&surname=&randomsurname=yes&usage_ger=1");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Error by open https://www.behindthename.com/random/random.php?number=1&sets=1&gender=m&surname=&randomsurname=yes&usage_ger=1:" + ex.Message + " " + ex.StackTrace);
            }
            driver.FindElement(By.XPath("//span[text()='Accept All']")).Click();


            vorname = driver.FindElement(By.XPath("//div[@class='random-results']/a")).GetAttribute("innerHTML");

            name = driver.FindElement(By.XPath("//div[@class='random-results']/a[2]")).GetAttribute("innerHTML");
        }

        public void Logger(string lines)
        {
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            path = removeExeFromPathChar(path);
            path = path + @"\Log\";
            VerifyDir(path);
            string fileName = DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Year.ToString() + "_Logs.txt";

            try
            {
                System.IO.StreamWriter file = new System.IO.StreamWriter(path + fileName, true);
                file.WriteLine(DateTime.Now.ToString() + ": " + lines);
                file.Close();
            }
            catch (Exception) { }
        }

        public static String removeExeFromPathChar(String s)
        {
            return (s == null || s.Length == 0)
              ? null
              : (s.Substring(0, s.Length - 14));
        }

        public void VerifyDir(string path)
        {
            try
            {
                DirectoryInfo dir = new DirectoryInfo(path);
                if (!dir.Exists)
                {
                    dir.Create();
                }
            }
            catch { }
        }

        // Generates a random string with a given size.    
        public string RandomString(int size, bool lowerCase = false)
        {
            var builder = new StringBuilder(size);

            char offset = lowerCase ? 'a' : 'A';
            const int lettersOffset = 26; // A...Z or a..z: length=26  

            for (var i = 0; i < size; i++)
            {
                var @char = (char)rnd.Next(offset, offset + lettersOffset);
                builder.Append(@char);
            }

            return lowerCase ? builder.ToString().ToLower() : builder.ToString();
        }

        public void GenerateSubdomain()
        {
            Thread.Sleep(2000);
            try
            {
                driver.Navigate().GoToUrl("https://www.rettmobil-international.com/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://www.rettmobil-international.com/" + ex.StackTrace + "  " + ex.Message);
            }

            try
            {
                driver.Navigate().GoToUrl("https://all-inkl.com/login/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://all-inkl.com/login/ " + ex.StackTrace + "  " + ex.Message);
            }

            Thread.Sleep(7000);
        }

        public void DeleteSubdomain()
        {

            try
            {
                driver.Navigate().GoToUrl("https://www.rettmobil-international.com/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://www.rettmobil-international.com/" + ex.StackTrace + "  " + ex.Message);
            }


            try
            {
                driver.Navigate().GoToUrl(" https://all-inkl.com/login/");
                Thread.Sleep(5000);
            }
            catch (Exception ex)
            {
                Logger("Failed by open URL https://all-inkl.com/login/" + ex.StackTrace + "  " + ex.Message);
            }

            Thread.Sleep(7000);

            IWebElement element = driver.FindElement(By.XPath("//input[@id='username_ma']"));
            element.SendKeys("635726");
            element = driver.FindElement(By.XPath("//input[@id='password_ma']"));
            element.SendKeys("RoD1JhB5##jOnfl1rx");
            driver.FindElement(By.Name("Login_ma")).Click();
            driver.FindElement(By.XPath("//div[@id='wrapper']/div/div/center/table/tbody/tr/td/table/tbody/tr[7]/td/a")).Click();
            Thread.Sleep(10000);
            string URL = driver.FindElement(By.XPath("//div[@id='wrapper']/div/div/center/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td[4]/a")).GetAttribute("href");
            driver.Navigate().GoToUrl(URL);
            Thread.Sleep(7000);
            driver.FindElement(By.XPath("//div[@class='navigation_box']/div[5]/p/a")).Click();

            string StringPart1 = "//a[text()='";
            string StringPart2 = "']";

            string subdomainToDeleteElementPath = StringPart1 + sFullSubdomain + StringPart2;

            IWebElement node = driver.FindElement(By.XPath(subdomainToDeleteElementPath));
            IWebElement parent = node.GetParent();
            parent = parent.GetParent();
            parent = parent.GetParent();
            parent = parent.GetParent();
            parent.FindElement(By.XPath("td[5]/p/span[2]/a")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.XPath("//td[@id='frame']/form/div/input")).Click();
            Thread.Sleep(1000);
        }

        private bool IsElementPresent(By by)
        {
            try
            {
                driver.FindElement(by);
                return true;
            }
            catch (NoSuchElementException)
            {
                return false;
            }
        }
    }

    public static class MyExtensions
    {
        public static IWebElement GetParent(this IWebElement node)
        {
            return node.FindElement(By.XPath(".."));
        }
    }
}


Testet it with 2 different PCs now and the Error happens on both machines.

Here is the log:
14.02.2022 15:11:47: Start Generate random Name and Logindata
14.02.2022 15:11:58: Finished random Name and Logindata Generation
14.02.2022 15:11:58: Erstelle Subdomain und Mail
14.02.2022 15:13:10: Error: chrome not reachable
  (Session info: chrome=98.0.4758.82)    bei OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   bei OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   bei OpenQA.Selenium.By.FindElement(ISearchContext context)
   bei OpenQA.Selenium.WebDriver.FindElement(By by)
   bei TestHTMLResponse.Program.DeleteSubdomain() in C:\Users\wolfgang\source\repos\TestHTMLResponse\TestHTMLResponse\Program.cs:Zeile 230.
   bei TestHTMLResponse.Program.Main(String[] args) in C:\Users\wolfgang\source\repos\TestHTMLResponse\TestHTMLResponse\Program.cs:Zeile 63.
14.02.2022 15:13:25: Start Generate random Name and Logindata
14.02.2022 15:13:37: Finished random Name and Logindata Generation
14.02.2022 15:13:37: Erstelle Subdomain und Mail
14.02.2022 15:14:39: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei TestHTMLResponse.Program.GenerateSubdomain() in C:\Users\wolfgang\source\repos\TestHTMLResponse\TestHTMLResponse\Program.cs:Zeile 183.  The HTTP request to the remote WebDriver server for URL http://localhost:63860/session/196703042e530a68261be5d5223ce568/url timed out after 60 seconds.
14.02.2022 15:15:39: Failed by open URL https://all-inkl.com/login/    bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei TestHTMLResponse.Program.GenerateSubdomain() in C:\Users\wolfgang\source\repos\TestHTMLResponse\TestHTMLResponse\Program.cs:Zeile 193.  The HTTP request to the remote WebDriver server for URL http://localhost:63860/session/196703042e530a68261be5d5223ce568/url timed out after 60 seconds.
14.02.2022 15:16:46: Failed by open URL https://www.rettmobil-international.com/   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.WebDriver.set_Url(String value)
   bei OpenQA.Selenium.Navigator.GoToUrl(String url)
   bei TestHTMLResponse.Program.DeleteSubdomain() in C:\Users\wolfgang\source\repos\TestHTMLResponse\TestHTMLResponse\Program.cs:Zeile 209.  The HTTP request to the remote WebDriver server for URL http://localhost:63860/session/196703042e530a68261be5d5223ce568/url timed out after 60 seconds.

Hope you can reproduce it.

**Comment by ChristianErdtmann** [comment]
Please delete the Username and Password in the delete subdomain function. My acces to the webhoster is blocked caus of to much login attempts

**Comment by pujagani** [comment]
Thank you for the details. I was not exactly able to reproduce the problem. I have run the code a sufficient number of times but I did not come across the timeout exception. What I did see was that only for ChromeDriver (EdgeDriver and FirefoxDrivers do not hang), the code hangs at: 
 ```
public void GenerateSubdomain()
    {
        Thread.Sleep(2000);
        try
        {
            driver.Navigate().GoToUrl("https://www.rettmobil-international.com/");
            Thread.Sleep(5000);
        }
        catch (Exception ex)
        {
            Logger("Failed by open URL https://www.rettmobil-international.com/" + ex.StackTrace + "  " + ex.Message);
        }
```
But if the contents of GenerateSubdomain are copy-pasted in the main method and not called via a method it works fine for ChromeDriver. I suspect a potential threading problem however I am not well versed with C# threading. I run the code using Visual Studio on Mac (This crashes way too often and it could be due to that as well). I suggest reaching out to us via one of the chat rooms https://www.selenium.dev/support/.

**Comment by ChristianErdtmann** [comment]
Strange that you don't get the timeout error.
I have now copied the code again into a working project and then the other project no longer works either and always gets a timeout.

**Comment by ChristianErdtmann** [comment]
i tried how you said to copy the logic the the main function but this doesnt work i still get the timeout error.

**Comment by ChristianErdtmann** [comment]
if iam delete the program.GetRandomName() function, so that the first URL is never opened all following URLs open wihtout a problem.
I now open the URL in program.GetRandomName(); in a seperat driver. But i think this problem will happens again. A right solution would be nice.

**Comment by pujagani** [comment]
> i tried how you said to copy the logic the the main function but this doesnt work i still get the timeout error.

Thank you for trying and providing updates. But the solution worked for me to prevent the code from being stuck. Since I was unable to reproduce the error, it is not the recommended solution for the same.  It might be good idea to reach out to us via one of the chat rooms https://www.selenium.dev/support/. Other developers and Selenium contributors hang out there, you might get some solution or help there.
