### ISSUE TITLE
[🚀 Feature]: Get XPath from IWebElement

### ISSUE THREAD

**Issue by ChristianErdtmann** [SeleniumHQ/selenium#10369]
### Feature and motivation

Hey i mean it would be very nice to get the XPath from an existing IWebElement to work with this path and change it like needed.

### Usage example

As example i have this Extension which give me back an IWebElement:
    public static class MyExtensions
    {
        public static IWebElement GetParent(this IWebElement node)
        {
            return node.FindElement(By.XPath(".."));
        }
    }

after that i want to check if its present on the page with 

        private bool IsElementPresent(By by)
        {
            try
            {
                driver.FindElement(by);
                return true;
            }
            catch (NoSuchElementException)
            {
                return false;
            }
        }

For the isElementPresent i need the XPath. But i dont get the whole xPath because i navigated from an other element with GetParent and from the final node again down in the DOM and have just a part of the xPath

**Comment by ChristianErdtmann** [comment]
It would also be nice for Debuging to get the Path after using oftern Parent or Child or Neigbor functions.
If i could now what is the actual xPath to see where iam at the moment.

**Comment by titusfortner** [comment]
I agree this is a great feature with many potential applications. Since there are a bunch of different ways it can be implemented and used, though, we do not add this functionality directly to Selenium and highly encourage our users to implement this kind of thing in their own test frameworks/libraries/code.
