### ISSUE TITLE
[🐛 Bug]: Node not registering on Hub for non Dockerised grid 4 on AWS Ec2

### ISSUE THREAD

**Issue by TahirAkhlaq** [SeleniumHQ/selenium#10373]
### What happened?

**I've create 3 Ec2 Instance all with Elastic IP .In Grid 4 I'm able to create a hub but when I'm trying to register the node machines.**

it only giving the **[NodeServer$1.lambda$start$1] - Sending registration event**.

**In Grid Version 3 with selenium server 3.141 jar I am able to register the node from different machine.**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/20920506/154750832-9f0b6cdb-cdfe-4ece-a3bc-8cb136aaa9d5.png)

**In Grid Version 4 with Selenium Server 4.1.2 For same machine hub and node working but I am not able to register any node from different machine.** 

<img width="1123" alt="Screenshot 2022-02-19 at 1 12 29 AM" src="https://user-images.githubusercontent.com/20920506/154751253-7832f8cd-f8f9-4f6e-895e-cf73d2e76961.png">

**Hub Registered with Version 4**

<img width="997" alt="Screenshot 2022-02-19 at 1 16 21 AM" src="https://user-images.githubusercontent.com/20920506/154751714-83494dde-8ecc-4b4d-86d7-5ae063e6e07d.png">

**Node is not registering.**

<img width="843" alt="Screenshot 2022-02-19 at 1 20 28 AM" src="https://user-images.githubusercontent.com/20920506/154752017-bfdd52a7-2878-4fa0-86cc-1a2a9adededb.png">

### How can we reproduce the issue?

```shell
On Machine 1 
java -jar selenium-server-4.1.2.jar hub

On Machine 2
java -jar selenium-server-4.1.2.jar node --detect-drivers true --publish-events  tcp://172.168.1.157:4442 --subscribe-events tcp://172.168.1.157:4443
```

### Relevant log output

```shell
Logs For Hub machine:

C:\Users\Administrator\Desktop\bat>java -jar selenium-server-4.1.2.jar hub
19:24:30.166 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
19:24:30.166 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
19:24:30.463 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.168.1.157:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.168.1.157:4443]
19:24:30.544 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.168.1.157:4442 and tcp://172.168.1.157:4443
19:24:30.575 INFO [UnboundZmqEventBus.<init>] - Sockets created
19:24:31.591 INFO [UnboundZmqEventBus.<init>] - Event bus ready
19:24:32.559 INFO [Hub.execute] - Started Selenium Hub 4.1.2 (revision 9a5a329c5a): http://172.168.1.157:4444



Logs For Node machine:


19:04:51.991 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
19:04:51.994 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
19:04:52.061 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.168.1.157:4442 and tcp://172.168.1.157:4443
19:04:52.084 INFO [UnboundZmqEventBus.<init>] - Sockets created
19:04:53.090 INFO [UnboundZmqEventBus.<init>] - Event bus ready
19:04:53.157 INFO [NodeServer.createHandlers] - Reporting self as: http://169.254.228.24:5555
19:04:53.172 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
19:04:53.187 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
19:04:53.204 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 12 times
19:04:53.204 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
19:04:53.217 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
19:04:53.312 INFO [NodeServer$1.start] - Starting registration process for node id 20fae541-650b-4042-9b8d-91e5471d03b8
19:04:53.312 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://169.254.228.24:5555
19:04:53.318 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:03.328 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:13.337 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:23.346 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:33.351 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:43.360 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:05:53.363 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:03.370 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:13.378 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:23.381 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:33.388 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:43.396 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
19:06:53.314 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

Mac, Windows, Ubantu ec2

### Selenium version

Selenium server 4.1.2

### What are the browser(s) and version(s) where you see this issue?

For Grid 4

### What are the browser driver(s) and version(s) where you see this issue?

Safari

### Are you using Selenium Grid?

4.1.2

**Comment by diemol** [comment]
The error means that the Hub cannot reach the IP 169.254.228.24. If the Hub should reach the Node through a different IP, please set it with the `--host` flag in Machine 2.

**Comment by TahirAkhlaq** [comment]
> The error means that the Hub cannot reach the IP 169.254.228.24. If the Hub should reach the Node through a different IP, please set it with the `--host` flag in Machine 2.

**I tried with Public IP of machine 2 with --host flag**.

```
java -jar selenium-server-4.1.2.jar node --detect-drivers true --publish-events  tcp://172.168.1.157:4442 --subscribe-events tcp://172.168.1.157:4443 --host 3.111.81.46
```

> LOGs for above command and 3.111.81.46 is public ip of Machine 2

```
10:14:08.606 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
10:14:08.612 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:14:08.730 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.168.1.157:4442 and tcp://172.168.1.157:4443
10:14:08.783 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:14:09.785 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:14:09.918 INFO [NodeServer.createHandlers] - Reporting self as: http://3.111.81.46:5555
10:14:09.938 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
10:14:09.975 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
10:14:10.009 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times
10:14:10.027 INFO [Node.<init>] - Binding additional locator mechanisms: relative, id, name
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
	at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.netty.server.ServerBindException: **Could not bind to address or port is already in use. Host 3.111.81.46, Port 5555**
	at org.openqa.selenium.netty.server.NettyServer.start(NettyServer.java:169)
	at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:191)
	at org.openqa.selenium.grid.node.httpd.NodeServer$1.start(NodeServer.java:188)
	at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:230)
	at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
	at org.openqa.selenium.grid.Main.launch(Main.java:83)
	at org.openqa.selenium.grid.Main.go(Main.java:57)
	at org.openqa.selenium.grid.Main.main(Main.java:42)
	... 6 more
**Caused by: java.net.BindException: Cannot assign requested address**
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.handler.logging.LoggingHandler.bind(LoggingHandler.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by diemol** [comment]
Ok, that means the server cannot bind to that IP address due to the network configuration. However, you can still make the Node report itself with that address by using `--bind-host false`. Check the docs at
https://www.selenium.dev/documentation/grid/configuration/cli_options/#server

**Comment by TahirAkhlaq** [comment]
@diemol thanks for response Windows Machine got Connected but still getting the error on Mac Machine .

Below command i ran.

`ec2-user@Mac-mini jar % java -jar selenium-server-4.1.2.jar node --detect-drivers true --publish-events tcp://172.168.1.109:4442 --subscribe-events tcp://172.168.1.109:4443 --bind-host false --host 172.168.0.139`


Tried with both public and private host ip.
Below is log.

11:23:33.000 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:23:33.003 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:23:33.068 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.168.1.109:4442 and tcp://172.168.1.109:4443
11:23:33.092 INFO [UnboundZmqEventBus.<init>] - Sockets created
11:23:34.096 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:23:34.159 INFO [NodeServer.createHandlers] - Reporting self as: http://172.168.0.139:5555
11:23:34.175 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
11:23:34.189 INFO [NodeOptions.discoverDrivers] - Discovered 2 driver(s)
11:23:34.206 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
11:23:34.207 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 12 times
11:23:34.220 INFO [Node.<init>] - Binding additional locator mechanisms: id, name, relative
11:23:34.456 INFO [NodeServer$1.start] - Starting registration process for node id 6f39970d-1447-4f14-99ac-9019d6270f23
11:23:34.457 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://172.168.0.139:5555
11:23:34.462 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:23:44.470 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:23:54.476 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
11:24:04.485 INFO [NodeServer$1.lambda$start$1] - Sending registration event..

**Below is the EC2 Instance details for your reference** 
<img width="988" alt="Screenshot 2022-02-21 at 4 59 24 PM" src="https://user-images.githubusercontent.com/20920506/154946860-883e7013-58df-4da4-b36a-508f29e3a094.png">

**Below is the inbound details of Ec2 instance.**
<img width="988" alt="Screenshot 2022-02-21 at 5 00 45 PM" src="https://user-images.githubusercontent.com/20920506/154947069-0c6a0dfe-348f-48e9-8b01-712d5af4a56e.png">

@diemol **do we need to open any specific port or any changes in Ec2 for Mac machine because with same inbound group Windows and Ubantu Machine are getting connected**
.

**Comment by TahirAkhlaq** [comment]
@diemol problem solved my opening the port on Ec2 Security Group
<img width="1146" alt="Screenshot 2022-02-21 at 6 44 12 PM" src="https://user-images.githubusercontent.com/20920506/154962336-7ac6b345-e8bb-404a-981c-a1521f168f27.png">.

Thanks for response !!

**Comment by larissaflores19** [comment]
Hello @TahirAkhlaq, I'm having the same issue (Node not registering on Hub) is there a possibility to share what changes did you do in the security group? I will really appreciate it. thanks!

**Comment by TahirAkhlaq** [comment]
Please Refer the SS for ports info.

<img width="1006" alt="Screenshot 2022-02-22 at 6 42 16 PM" src="https://user-images.githubusercontent.com/20920506/155139377-b651c088-0aac-4b12-9bfa-f09b9f443f23.png">
