### ISSUE TITLE
[🐛 Bug]: Missing .NET documentation comments

### ISSUE THREAD

**Issue by BaerMitUmlaut** [SeleniumHQ/selenium#10371]
### What happened?

The NuGet packages have no documentation comments at all. This affects all versions >= 4.0.0.

- v4.1.0:  
  ![grafik](https://user-images.githubusercontent.com/9693842/154506165-9f94741f-cc5a-467b-a7f7-267f036b8b63.png)
- v3.141.0  
  ![grafik](https://user-images.githubusercontent.com/9693842/154506055-6203d5d1-3582-47f3-94a6-87673f3818e1.png)

### How can we reproduce the issue?

```shell
- Install version 4.1.0 of the Selenium.Support package
- Press F12 on any Selenium type -> no documentation comments
- Downgrade to version 3.141.0
- Press F12 on any Selenium type -> documentation comments 🎉
```

### Relevant log output

```shell
-
```

### Operating System

Windows 11

### Selenium version

.NET 4.0.0, 4.0.1, 4.1.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.8000

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Yes, we haven't had the time too work on that.

Please follow https://github.com/SeleniumHQ/selenium/issues/10126 for updates.

**Comment by BaerMitUmlaut** [comment]
#10126 is about the online documentation, which does contain the info I am missing in the screenshot above:
https://www.selenium.dev/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_IWebDriver_Manage.htm

This bug is about the documentation delivered by the NuGet package as described in my reproduction steps. I suspect this is a problem within your actual build and not at all related to your online documentation - though I'm not sure how you generate the latter.

**Comment by diemol** [comment]
Thank you for clarifying, reopening.

**Comment by diemol** [comment]
PR merged. Thank you.

**Comment by titusfortner** [comment]
Looks like #10376 didn't fix the issue.

**Comment by diemol** [comment]
Is this still an issue? I think we merged a couple of PRs for this (PRs I cannot recall now).

**Comment by titusfortner** [comment]
This issue is about the comments (like Javadoc) not showing up in the IDE. The fix is to put an xml file somewhere that the packaging can reference it, and the bazel rules do not yet support this (I just double checked with the new dotnet rules owner)

**Comment by nvborisenko** [comment]
Fixed by new bazel rules for dotnet.
