### ISSUE TITLE
[🐛 Bug]: Very important time difference when executing driver.page_source

### ISSUE THREAD

**Issue by tianjinexpats** [SeleniumHQ/selenium#10381]
### What happened?

Hello, this is my first report on Github I hope that it is the appropriate way to do it.
I found this issue with selenium and beautiful soup with python 3.8

While I try to recover in a while 1 the content of a page using selenium and beautiful soup, I saw that time time do the exact same action driver.page_source can take up to 2 time for the exact same page with for obtaining the same "size" value

My CPU and memory are always under 50%

thank you
regards

### How can we reproduce the issue?

```shell
from datetime import datetime
from bs4 import BeautifulSoup
from sys import getsizeof
import time
from selenium import webdriver

from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


from selenium.webdriver.chrome.options import Options



caps = DesiredCapabilities().CHROME
caps["pageLoadStrategy"] = "normal"        
chrome_options = Options()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome(desired_capabilities=caps, options=chrome_options)
driver.get("https://www.baidu.com/")
  
time.sleep(10)   #wait in a bad way that it is properly loaded
          
        
timetablecontent , sizecontent , sizesoup, timetablesoup=[],[],[],[]
for i in range(0,500):

    start = datetime.now()
    content = driver.page_source    
    stop=datetime.now()
    timetablecontent.append(stop-start)
    
    start = datetime.now()
    soup = BeautifulSoup(content,features="lxml") 
    stop=datetime.now()
    timetablesoup.append(stop-start)   
    
    sizecontent.append(getsizeof(content))
    sizesoup.append(getsizeof(soup))
    
print("Temps max",max(timetablecontent))
print("Temps min",min(timetablecontent))
print("Temps max",max(timetablesoup))
print("Temps min",min(timetablesoup))
print("Content max",max(sizecontent))
print("Content min",min(sizecontent))
print("Soup max",max(sizesoup))
print("Soup min",min(sizesoup))
```

### Relevant log output

```shell
Temps max 0:00:00.187500
Temps min 0:00:00.099914
Temps max 0:00:00.140625
Temps min 0:00:00.031243
Content max 786244
Content min 786244
Soup max 48
Soup min 48
```

### Operating System

Windows 10 and Ubuntu

### Selenium version

Python 3.9

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

 Chrome Driver 97.0.4692.71

**Comment by diemol** [comment]
I am not sure what the actual issue is. You are comparing execution times of `driver.page_source` with `BeautifulSoup(content,features="lxml")`, most likely to be complete different methods.

I will tag this as a question so you can get the links where you can join our chat and mail list, in case you want to post and formulate your complete query over there.

**Comment by tianjinexpats** [comment]
Hello, 

thank you very much for your answer, 
I was comparing the execution time of driver.page_source with driver.page_source , by putting it into a loop
I have removed the BeautifulSoup(content,features="lxml") part of the code for more clarity, sorry for the confusion

I am still obtaining 
Max source time 0:00:00.207447
Min source time 0:00:00.068315
Size of content max: 778078
Size of content min: 778078

driver.page_source taking from 0.06 to 0.20 second to obtain the same content from the same page.


```
caps = DesiredCapabilities().CHROME
caps["pageLoadStrategy"] = "normal"        
chrome_options = Options()
chrome_options.add_argument("--headless")
driver = webdriver.Chrome(desired_capabilities=caps, options=chrome_options)
driver.get("https://www.baidu.com/")
     
time.sleep(10)            
timetablecontent , sizecontent =[],[]

for i in range(0,500):

    start1 = datetime.now()
    content = driver.page_source    
    stop=datetime.now()
    timetablecontent.append(stop-start1)    
    sizecontent.append(getsizeof(content))

print("Max source time",max(timetablecontent))
print("Min source time",min(timetablecontent))


print("Size of content max",max(sizecontent))
print("Size of content min",min(sizecontent))
```

**Comment by diemol** [comment]
Getting the page source is not a deterministic action, many things can affect the call. It might be very fast if the network connection is stable and fast, or it might be a bit slower if the network conditions change. Also, the page might be having dynamic content that changes from time to time. All in all, many factors can change the load time.

**Comment by tianjinexpats** [comment]
thank you for your answer, as I am sure the page do not have any dynamic content, I will give a look to the network conditions
That is indeed something that I should  but haven't double check
