### ISSUE TITLE
manage.deleteCookies() Doesn't work with new FF

### ISSUE THREAD

**Issue by chillywrap** [SeleniumHQ/selenium#1038]
With the New 2.47.1 and firefox 40.0.3. Having manage.deleteCookies() doesn't clear the cookies.
Checked this "getWebDriver().manage().getCookies()" and got an empty set for firefox.

Chrome is all good with the same code.

**Comment by AutomatedTester** [comment]
For issues please provide a concise reproducible test case and describe what results you are seeing and what results you expect.

See CONTRIBUTING.md

**Comment by chillywrap** [comment]
While Testing an eCommerce Site, If i have an item in my basket. if i clear the cookies the basket gets cleared.

I was using webdriver().manage().deleteCookies() to delete cookies and i used to get a new session with empty basket.

after the new release of firefox and selenium that's not the case, the item still stays in the basket, i.e cookies are not deleted.

If i use chrome, the cookies are deleted as expected and i can get a new session with clean basket.
