### ISSUE TITLE
[🐛 Bug]: Python selenium4 --headless from ChromeOptions doesn't apply if use desired_capabilities

### ISSUE THREAD

**Issue by akrasnov-marfatech** [SeleniumHQ/selenium#10384]
### What happened?

ChromeOptions passed as desired_capabities are lost when passed as command line arguments.

### How can we reproduce the issue?

```shell
from selenium.webdriver import Chrome, ChromeOptions

options = ChromeOptions()
options.add_argument('--headless')
caps = options.to_capabilities()

driver = Chrome(desired_capabilities=caps)
time.sleep(10)
driver.quit()
```

### Relevant log output

```shell
There is no logs.

Im add print('capabilities is ', capabilities) to webdriver.py:267 and see this:
capabilities is  {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'goog:chromeOptions': {'extensions': [], 'args': []}}

When expected:
capabilities is  {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'goog:chromeOptions': {'extensions': [], 'args': ['--headless']}}
```

### Operating System

Any

### Selenium version

Python, 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 99

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Desired Capabilities are deprecated and will be removed soon. Please pass in as options instead of as capabilities.
