### ISSUE TITLE
[🐛 Bug]: Sending chord of CTRL-a to input field writes unicode character &#57344; instead

### ISSUE THREAD

**Issue by stevenerat** [SeleniumHQ/selenium#10393]
### What happened?

When run in Selenium 4 Grid on Windows 10 (from a Mac client), `element.sendKeys(Keys.chord(Keys.CONTROL, "a"))` writes unicode character `&#57344;` instead.  This breaks test flows that sends keys to input fields.

When run in Selenium 4 Grid configuration on Mac, then there is no visible character input to the field.

selenium-server-4.1.2.jar (Standalone grid configuration)
Chrome 98.0.4758.102
ChromeDriver 98.0.4758.48
Windows 10 (grid with standalone hub/node)
Mac 10.15.7 (client)
Azul Zulu JDK 1.8

### How can we reproduce the issue?

```shell
Run against Selenium 4.1.2 Grid on Windows 10; Set a break point on driver.quit and observe the input field shows a single character when debugger stops.


    @Test
    public void sendChordCtrlAIssue() throws MalformedURLException {

            WebDriver driver = new RemoteWebDriver(new URL(HUB_ADDR), new ChromeOptions());
        try {
            driver.get("https://www.google.com");
            WebElement searchFieldLocator = driver.findElement(By.xpath("//input[@title='Search']"));
            searchFieldLocator.sendKeys(Keys.chord(Keys.CONTROL, "a"));
        } finally {
            driver.quit();
        }
    }
```
```


### Relevant log output

```shell
NA
```

### Operating System

Windows 10

### Selenium version

Azul Zuli 1.8

### What are the browser(s) and version(s) where you see this issue?

Chrome 98

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98

### Are you using Selenium Grid?

4.1.2

**Comment by titusfortner** [comment]
That character is the decimal representation of the hex code `'\uE000'` which we use to represent `null`. When using a "chord," it is appended to the end of the string to represent the termination of the multiple simultaneous key presses.

Looks like this broke with Chrome 98 — https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999

Some people have reported success with updating to Chromedriver 98.0.4758.102
