### ISSUE TITLE
[🐛 Bug]: Can't change height/width with "Save as PDF"

### ISSUE THREAD

**Issue by knightas7** [SeleniumHQ/selenium#10394]
### What happened?

I tried to save a page by "print - Save as PDF".
I want to save it with 'legal' page size format, so I tried with "hegith_microns" as 355600, "width_microns" as 215900.
And it turns out, no matter how much I changed it, it just save as default size.

 

### How can we reproduce the issue?

```shell
I tried this code:


    chrome_options = webdriver.ChromeOptions()

    settings = {
        "recentDestinations": [{
            "id": "Save as PDF",
            "origin": "local",
            "account": ""
        }],
        "selectedDestinationId": "Save as PDF",
        "version": 2,
        "mediaSize": {
            "height_microns": 355600,
            "width_microns": 215900,
            "name": "NA_legal",
            "custom_display_name": "legal"
        },
        "isCssBackgroundEnabled": True,
        "isHeaderFooterEnabled": True,
    }


    prefs = {'printing.print_preview_sticky_settings.appState' : json.dumps(settings)}

    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument('--kiosk-printing')
    chrome_options.add_experimental_option('prefs', prefs)

    driver = webdriver.Chrome("chromedriver.exe", options=chrome_options)
    driver.get('page')
    driver.execute_script('window.print();')

I've tried several other pages with enough height to tell diffrence.
```

### Relevant log output

```shell
None have occured.
Seems to it just get a height/width value as "unavailable value" and try with default size.
```

### Operating System

Windows 10

### Selenium version

Python 3.9 - selenium 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 98

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 98.0.4758.102

**Comment by titusfortner** [comment]
Looks like it works on Firefox but not Chrome https://wpt.fyi/results/webdriver/tests/print/printcmd.py?label=experimental&label=master&aligned
https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/print/printcmd.py#L33
