### ISSUE TITLE
[🐛 Bug]:Py version 4.1.1 can't find the path. Look at the updated description and delete it. Why?

### ISSUE THREAD

**Issue by timwang-ai** [SeleniumHQ/selenium#10395]
### What happened?

from selenium.webdriver import TouchActions, ActionChains
E   ImportError: cannot import name 'TouchActions' from 'selenium.webdriver'

### How can we reproduce the issue?

```shell
from selenium.webdriver import TouchActions, ActionChains
E   ImportError: cannot import name 'TouchActions' from 'selenium.webdriver'
```

### Relevant log output

```shell
from selenium.webdriver import TouchActions, ActionChains
E   ImportError: cannot import name 'TouchActions' from 'selenium.webdriver'
```

### Operating System

Windows 10

### Selenium version

Python 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Chrome-98

### What are the browser driver(s) and version(s) where you see this issue?

Chrome-98

### Are you using Selenium Grid?

4.0.0

**Comment by ghost** [comment]
I'm getting the same error on 4.1.1 and 4.1.2. It's fine on 4.1.0. Not sure why it was removed, but please don't make breaking changes like this in a patch release.

**Comment by TaikerLiang** [comment]
Same error on 4.1.2, downgrade to 4.1.0, and it's fine now.

**Comment by mdmintz** [comment]
Found the likely issue:
https://github.com/SeleniumHQ/selenium/commit/816ad6ebb5353431c37f160b2b9b0056b6efdb4e
CC @titusfortner 
(There was no Deprecation warning for that, so ``TouchActions`` should probably get put back.)

And the minimum example to reproduce is:

```
from selenium.webdriver import TouchActions
...
ImportError: cannot import name 'TouchActions' from 'selenium.webdriver'
```

(The ``ActionChains`` part in the original description was misleading, as that is fine.)

**Comment by AutomatedTester** [comment]
What driver are you using with this @TaikerLiang ? None of the browser drivers support this endpoint

**Comment by ghost** [comment]
In my case this is re-exported by `selenium-wire` but is not actually used:

https://github.com/wkeeling/selenium-wire/blob/c93ffd3de45eb676ccc7b9cdaa811c5389cac3b8/seleniumwire/webdriver.py#L14

**Comment by mdmintz** [comment]
Relevant ticket: https://github.com/wkeeling/selenium-wire/issues/513

**Comment by mdmintz** [comment]
Fixed by https://github.com/wkeeling/selenium-wire/issues/513#issuecomment-1051270017
(``selenium-wire 4.6.2``)

Everyone, please upgrade your selenium-wire versions if you hit this issue.
CC @titusfortner @AutomatedTester
