### ISSUE TITLE
[🐛 Bug]: Selenium Hub container - status code is 200, even if the grid isn't ready

### ISSUE THREAD

**Issue by Bjego** [SeleniumHQ/selenium#10391]
### What happened?

When the grid isn't ready the healthcheck shouldn't return a 200 OK status code.

I think the correct status code would be 503.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses

When the grid would return a proper status code - health checks would make a real sense, which could lead to a pod restart.

![image](https://user-images.githubusercontent.com/12625568/155353017-f1600d73-3677-45aa-a177-ec20cf15216c.png)

### How can we reproduce the issue?

```shell
Start a hub in kubernetes and see the health check statuscode in your browser. It's always "OK".

apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4
          ports:
            - containerPort: 4444
            - containerPort: 4443
            - containerPort: 4442
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "250Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 15
            timeoutSeconds: 5
```

### Relevant log output

```shell
No server logs
```

### Operating System

Docker Container

### Selenium version

image: selenium/hub:4

### What are the browser(s) and version(s) where you see this issue?

ignore

### What are the browser driver(s) and version(s) where you see this issue?

ignore

### Are you using Selenium Grid?

image: selenium/hub:4

**Comment by Bjego** [comment]
Thank you @pujagani 👍

**Comment by diemol** [comment]
I reverted this change (but kept the added tests) because the spec is not specific about what status code should be returned when the Grid is not ready. The `/status` endpoint is meant to be used to find out if the Grid is able to create a session or not, not to report the status of its components, please check https://www.w3.org/TR/webdriver1/#status.

When talking about the health status of the Grid, in order to perform some action on it (like, restarting a pod in Kubernetes), the endpoint to query is `/readyz`. For example, querying that endpoint in the Hub will check that all other components are up.

**Comment by diemol** [comment]
I made changes to the `/readyz` endpoint so the desired http status code is returned.

**Comment by Bjego** [comment]
> I made changes to the `/readyz` endpoint so the desired http status code is returned.

Thank you. So the /readyz endpoint is now using proper status codes, so that tools running healthchecks like kubernetes can restart the grid on their own?

**Comment by Bjego** [comment]
Do we need a change in the helmchart as well?
https://github.com/SeleniumHQ/docker-selenium/blob/trunk/chart/selenium-grid/templates/hub-deployment.yaml

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/chart/selenium-grid/values.yaml#L199

**Comment by Bjego** [comment]
Guess that's the case will fiddle a ticket there!

**Comment by Bjego** [comment]
https://github.com/SeleniumHQ/docker-selenium/issues/1529
