### ISSUE TITLE
[🐛 Bug]: Selenium 4 / Safari / Proxy - Response code 500. Message: Capability 'proxy' could not be honored.

### ISSUE THREAD

**Issue by NikolayStanoev** [SeleniumHQ/selenium#10401]
### What happened?

When I try to run locally safari tests using Selenium 4.1.0 and proxy I get SessionNotCreatedException with the following message --> Could not start a new session. Response code 500. Message: Capability 'proxy' could not be honored.

### How can we reproduce the issue?

```shell
You can use the following code snippet

        Proxy proxy = new Proxy();
        proxy.setAutodetect(false);
        proxy.setSslProxy("localhost:8080");
        proxy.setHttpProxy("localhost:8080");
        SafariOptions safariOptions = new SafariOptions();
        safariOptions.setProxy(proxy);  
        safariOptions.setAcceptInsecureCerts(true);

        WebDriver webDriver = new SafariDriver(safariOptions);
        webDriver.get("https://www.google.com");
        webDriver.close();

If you change safariOptions.setProxy(proxy); to safariOptions.setCapability("proxy", proxy); the same error is displayed
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Capability 'proxy' could not be honored.
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'wks101009.local', ip: 'fe80:0:0:0:10c8:3b73:9595:1c3e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.5', java.version: '11.0.12'
Driver info: org.openqa.selenium.safari.SafariDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: safari, proxy: {httpProxy: localhost:8080, proxyType: manual, sslProxy: localhost:8080}}], desiredCapabilities=Capabilities {acceptInsecureCerts: true, browserName: safari, proxy: Proxy(manual, http=localhos...}}]
Capabilities {}
```

### Operating System

macOS Big Sur 11.6

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Safari - 15.1

### What are the browser driver(s) and version(s) where you see this issue?

SafariDriver - 4.1.0

### Are you using Selenium Grid?

No

**Comment by NikolayStanoev** [comment]
The following code example with Chrome starts the browser and open the site via proxy without any problems:

        Proxy proxy = new Proxy();
        proxy.setAutodetect(false);
        proxy.setSslProxy("localhost:8080");
        proxy.setHttpProxy("localhost:8080");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setProxy(proxy);
        chromeOptions.setAcceptInsecureCerts(true);
        WebDriverManager.chromedriver().setup();
        WebDriver webDriver = new ChromeDriver(chromeOptions);
        webDriver.get("https://www.google.com");
        webDriver.close();

**Comment by titusfortner** [comment]
Unfortunately, Safari does not work with proxies. This is a limitation of safaridriver and not the Selenium project; best option is to file a bug with Apple — https://bugreport.apple.com
