### ISSUE TITLE
[🐛 Bug]: SafariDriver throws WebDriverException without any message

### ISSUE THREAD

**Issue by romek-codes** [SeleniumHQ/selenium#10406]
### What happened?

Hello, I wrote tests using ChromeDriver and GeckoDriver and i don't have any issues with them inside of Windows, today i started working on implementing these tests on macOS with Safari and am having a weird issue that I haven't seen before and I also couldn't find any resources online to help me. 

Almost all of my code runs without any issue, but some one off lines are affected and when i call .click() they throw me the WebDriverException with an empty Message. 

When using except to pass the thrown exception all tests keep running without a problem like nothing has happened, which is my temporary fix for now.

Does anybody have any idea what could be the cause of this? 

### How can we reproduce the issue?

```shell
profile_selector = 'app-dating-match > div > div:nth-child('+ str(profile_to_click_nth_child) +') > div.card-content > div.details > div.details-container > p'

profile = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, profile_selector)))

profile.click() # Exception gets thrown here
```

### Relevant log output

```shell
Exception has occurred: WebDriverException
Message: 
  File "/Users/romanjuszczyk/Documents/GitHub/MSD-Community-Tests/community_tests.py", line 866, in test_opening_profiles_limit_basic
    profile.click()
  File "/Users/romanjuszczyk/Documents/GitHub/MSD-Community-Tests/community_tests.py", line 929, in test_basic_member_limits
    test_opening_profiles_limit_basic()
  File "/Users/romanjuszczyk/Documents/GitHub/MSD-Community-Tests/community_tests.py", line 3209, in run_tests
    test_basic_member_limits() # Webdriverexception
  File "/Users/romanjuszczyk/Documents/GitHub/MSD-Community-Tests/community_tests.py", line 3250, in <module>
    run_tests()
```

### Operating System

macOS

### Selenium version

Python 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Safari 15.2 (17612.3.6.1.6)

### What are the browser driver(s) and version(s) where you see this issue?

Included with Safari 15.2 (17612.3.6.1.6)

**Comment by titusfortner** [comment]
If it is working properly in Chrome and Firefox, then the issue is almost always with safaridriver, which means there isn't anything we can do in Selenium code, unfortunately. Further, the empty message means safaridriver isn't even giving useful information about why it is breaking. Your workaround is the one I would have suggested. It is unfortunate that it is necessary when running with Safari.
