### ISSUE TITLE
[🐛 Bug]: Unable to run tests on docker selenium grid using macOS

### ISSUE THREAD

**Issue by gvsharshavardhan** [SeleniumHQ/selenium#10400]
### What happened?

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'HARSHAs-Air.ht.home', ip: '2607:fea8:e00:6130:0:0:0:b2ed%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.1', java.version: '11.0.14'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]
Capabilities {}

### How can we reproduce the issue?

```shell
Docker commands used to create grid:
docker run -d --link selenium-hub:hub selenium/node-chrome:3.4.0
docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.4.0

code:
String browserName = Optional.ofNullable(System.getProperty("browser")).orElse("chrome");
        String remote_url = "http://localhost:4444/wd/hub";
        if (browserName.equalsIgnoreCase("chrome")) {
            ChromeOptions options = new ChromeOptions();
            this.driver = new RemoteWebDriver(new URL(remote_url), options);
        } else if (browserName.equalsIgnoreCase("firefox")) {
            FirefoxOptions options = new FirefoxOptions();
            this.driver = new RemoteWebDriver(new URL(remote_url), options);
        }
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'HARSHAs-Air.ht.home', ip: '2607:fea8:e00:6130:0:0:0:b2ed%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.1', java.version: '11.0.14'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [], extensions: []}}}]
Capabilities {}
```

### Operating System

ProductName:macOS ;ProductVersion:12.1 ;BuildVersion:	21C52

### Selenium version

4.1.1

### What are the browser(s) and version(s) where you see this issue?

selenium/node-chrome:3.4.0

### What are the browser driver(s) and version(s) where you see this issue?

selenium/node-chrome:3.4.0

### Are you using Selenium Grid?

selenium/node-chrome:3.4.0

**Comment by diemol** [comment]
`selenium/node-chrome:3.4.0` are really old images. Seems you are using Selenium 4.1.1 on the client side and Grid 3.4.0, which we don't encourage.

Please try to use the latest images and also add `--shm-size="2g"` to the command. Without that, the browser will crash.
https://github.com/SeleniumHQ/docker-selenium#quick-start

We can reopen if you still have issues after upgrading and using the suggested commands.
