### ISSUE TITLE
[🐛 Bug]: An error is reported on the page when searching for the title in the API document

### ISSUE THREAD

**Issue by zhangheng0027** [SeleniumHQ/selenium#10415]
### What happened?

When viewing the API document, page 404

### How can we reproduce the issue?

```shell
Access address:https://www.selenium.dev/selenium/docs/api/java/overview-summary.html
seach : title
select : org.openqa.selenium.support.ui.ExpectedConditions.titleContains(String)
```

### Relevant log output

```shell
404 File not found
```

### Operating System

win7

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

None

**Comment by zhangheng0027** [comment]
Access url: https://www.selenium.dev/selenium/docs/api/java/undefined/org/openqa/selenium/support/ui/ExpectedConditions.html#titleContains(java.lang.String)

**Comment by titusfortner** [comment]
Looks like search results form API page are getting an extra `undefined` added to them (e.g. https://www.selenium.dev/selenium/docs/api/java/undefined/org/openqa/selenium/remote/tracing/EventAttributeValue). Looks like it is only for "Members" and "Types" not for "Packages."

@diemol how are we generating these? Would the reorg we did for Se4 affect this?
