### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedException for Edge in IE Mode

### ISSUE THREAD

**Issue by AradhanaJamwal** [SeleniumHQ/selenium#10411]
### What happened?

I am facing issue while automating the application using Selenium 4 in IE mode in Microsoft Edge with Internet Explorer Driver. 
I have followed the steps given in the [Microsoft Blog](https://blogs.windows.com/msedgedev/2022/02/01/test-ie-mode-in-microsoft-edge-internet-explorer-driver/)  but still not able to get the results.
Language Used- JAVA
Browser- IE Compatibility Mode 

Code Snippet- 
 public static void main(String[] args) {        
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        
        WebDriver driver = new InternetExplorerDriver(ieOptions);
        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("IE mode", Keys.RETURN);
        driver.close();
    }
Issue: I am able to launch the browser in "Edge compatibility mode" but not able to move further. The screen is stuck on the page with following error:

 "This is the initial start page for the WebDriver server".

![image](https://user-images.githubusercontent.com/63354414/156769485-5c7d2c43-4816-43e6-a0d9-e277f3165e7b.png)

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
public class IEDriverSample {
    public static void main(String[] args) {        
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        
        WebDriver driver = new InternetExplorerDriver(ieOptions);
        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("IE mode", Keys.RETURN);
        driver.close();
    }
}
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 10

### Selenium version

<dependency>             <groupId>org.seleniumhq.selenium</groupId>             <artifactId>selenium-java</artifactId>             <version>4.1.2</version>         </dependency>

### What are the browser(s) and version(s) where you see this issue?

IE Mode in Edge

### What are the browser driver(s) and version(s) where you see this issue?

IE Driver 4.0.0.0 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Those aren't errors. Those are expected information bars being displayed on Edge when automating in IE Mode.
Are you getting an actual error in your code? Or is your command to navigate to another page not doing anything?

**Comment by AradhanaJamwal** [comment]
After launching the browser I am not able to navigate to the url .. Though I have written the code to launch the url “www.bing.com” but it  I am stuck on this webdriver start up page…

**Comment by titusfortner** [comment]
Make sure you are using the full `https://www.bing.com`. It should either navigate or throw an error. Are you getting an error on the next line when it tries to find an element that isn't there? At some point you should be getting an error.

**Comment by AradhanaJamwal** [comment]
Yes I am using the full URL.. here is the code snippet..
public class IEDriverSample {
    public static void main(String[] args) {
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");

        WebDriver driver = new InternetExplorerDriver(ieOptions);
        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("IE mode", Keys.RETURN);
        driver.close();
    }

After 4 minutes of time I got this error:

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.1.2', revision: '9a5a329c5a'

![image](https://user-images.githubusercontent.com/63354414/157016170-ce63c692-f3c7-4f40-95f1-6ad7bb78a013.png)

**Comment by titusfortner** [comment]
Yeah, not sure on this one. The code is right. The driver is starting the browser, but then quits.
Are you sure you are using the 32bit version of IEDriver?

**Comment by AradhanaJamwal** [comment]
yes IE driver version is correct. But there is one observation I found yesterday, I am trying to run this script on my laptop issued by my organization and Microsoft Edge browser is managed by my organization.. They have set up some policies for this browser.. Could that be one of the cause.. but I am not sure what exactly is refraining me to run this script successfully. Could you please help me to understand if some browser policy can impact this execution... Following are the policies:
![image](https://user-images.githubusercontent.com/63354414/157106712-792ea7d6-8bdf-45c8-b082-7b7d814259ae.png)

**Comment by titusfortner** [comment]
I have no idea on the Edge policies.

Are you using the 32 bit version or the 64 bit version of IE Driver? Please make sure you are using the 32 bit version.

**Comment by AradhanaJamwal** [comment]
I am using 32 bit version only

**Comment by AradhanaJamwal** [comment]
What could be the reason for this error and is there any way to rectify it?

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Shall I use any additional capabilities ?

**Comment by titusfortner** [comment]
I don't know. The code is correct and it works for everyone else. Can you download a different version of Edge and point to it and see if it works? Beyond that I'm not sure we can help.

**Comment by AradhanaJamwal** [comment]
This is resolved after adding few IE capabilities... Now other issue that I am facing after using selenium 4 is - On clicking most of the elements its throwing following error.. But same function and locator is working for Selenium 3..

org.openqa.selenium.ElementNotInteractableException: Received a JavaScript error attempting to click on the element using synthetic events. We are assuming this is because the element isn't displayed, but it may be due to other problems with executing JavaScript.

I

**Comment by BhavinMasterM** [comment]
@AradhanaJamwal can you share which capabilities you have added to solve the issue? I am also facing similar issue.

**Comment by AradhanaJamwal** [comment]
> @AradhanaJamwal can you share which capabilities you have added to solve the issue? I am also facing similar issue.

 System.out.println("Launching Edge IE Compatibility Mode Browser using IE Driver");
            System.setProperty("webdriver.ie.driver", "Driver\\IEDriverServer.exe");
            InternetExplorerOptions ieOptions = new InternetExplorerOptions();
            ieOptions.attachToEdgeChrome();
            ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
            ieOptions.ignoreZoomSettings();
            ieOptions.introduceFlakinessByIgnoringSecurityDomains();
            ieOptions.disableNativeEvents();
            ieOptions.requireWindowFocus();
            ieOptions.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);
            ieOptions.destructivelyEnsureCleanSession();
            ieOptions.enablePersistentHovering();

**Comment by AradhanaJamwal** [comment]
> This is resolved after adding few IE capabilities... Now other issue that I am facing after using selenium 4 is - On clicking most of the elements its throwing following error.. But same function and locator is working for Selenium 3..
> 
> org.openqa.selenium.ElementNotInteractableException: Received a JavaScript error attempting to click on the element using synthetic events. We are assuming this is because the element isn't displayed, but it may be due to other problems with executing JavaScript.
> 
> I

@titusfortner  - Could you please help me in sorting out the above error. I am not sure why this error is reflecting although its working fine with lower version of IE Webdriver....(lower than 4)

**Comment by titusfortner** [comment]
Can you narrow down which capability made the difference between being able to start the session? Perhaps it is the zoom issue (IE driver requires zoom to be at 100%).

You're setting a bunch of capabilities that aren't recommended, so it's not necessarily surprising that you might have issues. IE settings are a pain, and using them with Edge cause a lot more, please be very careful when changing away from the default.

Since the original reported issue has been resolved, I'm closing this.
