### ISSUE TITLE
[🐛 Bug]: Server terminated early with status 126; chrome and chromedriver appear to be compatible

### ISSUE THREAD

**Issue by paul-bell** [SeleniumHQ/selenium#10412]
### What happened?

I cannot be sure at exactly what point my containerized Node.js program fails. 

I am using what look to be the latest versions of the Google chrome browser binary and an apparently compatible version of the chromedriver.

chrome:
Google Chrome 99.0.4844.51 unknown

chromedriver:
ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875})

### How can we reproduce the issue?

```shell
I'm not sure how best to reproduce it. The code I'm running is part of a considerably larger system and cannot readily be extracted and condensed.
```

### Relevant log output

```shell
Error: Server terminated early with status 126
/../node_modules/selenium-webdriver/remote/index.js:248
                reject(Error(e.message))
                       ^
Error: Server terminated early with status 126
    at /data/hermes/node_modules/selenium-webdriver/remote/index.js:248:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating System

Containerized CentOS 7 running atop Ubuntu 18.04.1

### Selenium version

Node.js 16.4.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 99.0.4844.51

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875})

### Are you using Selenium Grid?

I don't think so

**Comment by titusfortner** [comment]
That error indicates that you are using the wrong chromedriver (e.g. wrong bit or wrong OS)

How are you installing the driver? Are you manually downloading it or using something like chromedriver npm?

**Comment by diemol** [comment]
Closing as we did not get more information.
