### ISSUE TITLE
[🐛 Bug]: Requests for MicrosoftEdge create wrong browser

### ISSUE THREAD

**Issue by andrewnicols** [SeleniumHQ/selenium#10410]
### What happened?

When trying to create new session for Edge with some parameters, I get different sessions. This seems to mostly be either Firefox or Safari, depending on what parameters are passed in. Sometimes I get Edge, but it really seems to vary. I may get Edge five times in a row, but then only Firefox or only Safari.

### How can we reproduce the issue?

```shell
#!/bin/bash

WDURL="http://localhost:4444/wd/hub";

CAPABILITIES='{"capabilities":{"firstMatch":[{"browserName":"MicrosoftEdge","ms:edgeChromium":true}]},"desiredCapabilities":{"tags":["mandarin.per.nicols.uk","PHP 7.4.28"],"browserName":"MicrosoftEdge","ms:edgeChromium":true,"browser":"edge","ignoreZoomSetting":false,"name":"Behat feature suite"}}'

RESPONSE=`curl -s  -H 'Content-Type: application/json; charset=utf-8' -d "${CAPABILITIES}" "${WDURL}/session"`
SESSIONID=`echo "${RESPONSE}" | python3 -c "import sys, json; print(json.load(sys.stdin)['value']['sessionId'])"`

echo $RESPONSE

echo "Deleting window:"
curl -X DELETE "${WDURL}/session/${SESSIONID}"
echo
```

### Relevant log output
[wrongbrowser.log](https://github.com/SeleniumHQ/selenium/files/8182700/wrongbrowser.log)

### Operating System

macOS Monterey 12.2.1

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Edge 98.0.1108.62

### What are the browser driver(s) and version(s) where you see this issue?

edgedriver 98.0.1108.62

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
When using Selenium 4, do not pass in `desiredCapabilities`, only `capabilities` and you do not need `ms:edgeChromium`, Selenium 4 no longer supports EdgeHTML.

The code above nests `desiredCapabilities` inside `capabilities`, the grid ends up translating the request so as to give you the first of 3 matching capabilities. In this case, one of the capabilities is empty, so any available session will work.

Relevant portion of log:
```
 [Capabilities {}, Capabilities {browserName: MicrosoftEdge, ms:edgeChromium: true}, Capabilities {browser: edge, browserName: MicrosoftEdge, ignoreZoomSetting: false, ms:edgeChromium: true, name: Behat feature suite, tags: [mandarin.per.nicols.uk, PHP 7.4.28]}]
```

**Comment by diemol** [comment]
Thanks for triaging, @titusfortner!
I will reopen this to have this on the bug list, and fix it on the Grid.

**Comment by andrewnicols** [comment]
So this is a bug in selenium 4 then?

**Comment by diemol** [comment]
I'm not a 100% sure. I need to check the commit history to understand why this behavior exists.

**Comment by titusfortner** [comment]
The root cause of this particular issue is that you sent an invalid structure with how you nested capabilities.

Selenium should error when this happens rather than defaulting to "use anything." To an extent I don't care since the Selenium libraries can't make this mistake. On the other hand, maybe there are other errors that Selenium library users will experience based on the bug here, so probably worth our looking at it.
