### ISSUE TITLE
No source code tag to match PyPI 4.1.2 release

### ISSUE THREAD

**Issue by apteryks** [SeleniumHQ/selenium#10425]
### What happened?

I'm trying to package the latest release for Guix, but there's no source distribution on PyPI, and the latest release tagged here is 4.1.0.

### How can we reproduce the issue?

```shell
Compare the version string in PyPI vs what's been tagged.
```

### Relevant log output

```shell
N/A.
```

### Operating System

N/A

### Selenium version

4.1.1 and 4.1.2

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by titusfortner** [comment]
We only tag minor versions since they apply to all languages in this mono-repo. Language specific updates are made as patch versions.

If you need you can look at commit messages for when the version is bumped
https://github.com/SeleniumHQ/selenium/commit/a2a58baba0a9f7289de1cd7d98c7eb05a148613a

**Comment by apteryks** [comment]
OK, thank you for explaining.
