### ISSUE TITLE
[🚀 Feature]: Include options class in Safari webdrivers remote RemoteWebDriver constructor

### ISSUE THREAD

**Issue by MWschutte** [SeleniumHQ/selenium#10428]
### Feature and motivation

In the Safari [webdriver constructor](https://github.com/SeleniumHQ/selenium/blob/a2a58baba0a9f7289de1cd7d98c7eb05a148613a/py/selenium/webdriver/safari/webdriver.py#L42) in the Ptyhon library an Options class can be passed as argument. However this options class is never used. In webdriver classes of other browsers the options class is passed to the constructor of the RemoteWebDriver class, the class that he webdriver implements.

### Usage example

options = Options()

webdriver(options=options)

**Comment by titusfortner** [comment]
Yes, we just added the `SafariOptions` class to Python, but it doesn't look like we hooked it into the driver. Thanks for bringing it to our attention.

**Comment by symonk** [comment]
@titusfortner / @MWschutte can we close this? looks like PR was merged.
