### ISSUE TITLE
[🐛 Bug]: Python NoReturn type in Chromium Options

### ISSUE THREAD

**Issue by AlexBelanger** [SeleniumHQ/selenium#10429]
### What happened?

For the Python ChromeOptions, NoReturn is used  incorrectly and throws Pylance off. 

Python Selenium Version: 4.1.0 was working fine (no return types)
Python Selenium Version: 4.1.3 pylance error shows up.

For the functions where NoReturn is used incorrectly, the return type should be changed to None.

### How can we reproduce the issue?

```shell
from selenium.webdriver import ChromeOptions

class CustomOptions(ChromeOptions):
    def __init__(self, page_load_strategy = 'normal', headless=True) -> None:
        super().__init__()

        if headless:
            self.add_argument('headless')  
            self.add_argument('window-size=1920,1080')
        else:
            self.add_argument('start-maximized')

        self.add_experimental_option('useAutomationExtension', False)
        self.add_argument('--ignore-certificate-errors')
        self.add_argument('--incognito')
        self.add_argument('--disable-blink-features=AutomationControlled')
        self.add_argument('--log-level=3')
        self.page_load_strategy = page_load_strategy
```

### Relevant log output

```shell
Pylance:

(method) add_argument: (argument: Any) -> None
Adds an argument to the list

:Args:

Sets the arguments
Code is unreachable Pylance
```

### Operating System

Windows 11

### Selenium version

Python selenium v 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver version 99

### Are you using Selenium Grid?

None

**Comment by titusfortner** [comment]
Can you make a PR with the fixes?

**Comment by AlexBelanger** [comment]
@titusfortner Yes I can, I wasn't sure how to setup the repos on my laptop. I'll try using the main readme https://github.com/SeleniumHQ/selenium

**Comment by titusfortner** [comment]
Thanks, if you run into any difficulties with the setup feel free to contact us on chat — https://www.selenium.dev/support/#ChatRoom
