### ISSUE TITLE
Cant acess shadowdom element after msedgedriver update

### ISSUE THREAD

**Issue by MilvenCossa** [SeleniumHQ/selenium#10434]
### What happened?

After updating a Microsoft edge browser , when i run my test i have the following error: java.lang.UnsupportedOperationException: getShadowRoot. 

### How can we reproduce the issue?

```shell
WebElement shadowHost = driver.findElement(By.cssSelector("#shadow_host"));
SearchContext shadowRoot = shadowHost.getShadowRoot();
WebElement shadowContent = shadowRoot.findElement(By.cssSelector("#shadow_content"));
```

### Relevant log output

```shell
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 32.566 s <<< FAILURE! - in TestSuite
[ERROR] tests.base.PesquisaDeEntidadeIT.criarEntidade  Time elapsed: 4.424 s  <<< FAILURE!
java.lang.UnsupportedOperationException: getShadowRoot
```

### Operating System

Windows 10

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Microsoft edge 99.0.1150.36

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver 99.0.1150.36

**Comment by titusfortner** [comment]
The only way to get this error is from the WebElement Interface, which throws this as the default 

This means the class returned by `driver.findElement(By.cssSelector("#shadow_host"))` isn't implementing that method, which likely means you are actually using an old class, which means you most likely have a dependency conflict.

Please investigate — https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

Make sure all Selenium versions in the tree are 4.1.2

**Comment by MilvenCossa** [comment]
I have updated all the selenium versions to match 4.1.2 but i still face the same issue.

Note:  i´m using vaadin test bench 23.0.1 , as the website i´m automating is using vaadin for front-end

![Capture](https://user-images.githubusercontent.com/24649838/158959346-cbc848bf-435f-4366-8f2b-3e37bda7c767.PNG)

**Comment by titusfortner** [comment]
What are you using to troubleshoot? Can you put a debug point for the class instance getting returned from the findElement? *Something is getting returned that doesn't implement `getShadowRoot()` and we need to know what that is to help you further.

**Comment by diemol** [comment]
I will close this because we did not get more information.
