### ISSUE TITLE
[🐛 Bug]: Chromium based browsers do not throw InsecureCertificateException

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#10446]
### What happened?

Accessing https://self-signed.badssl.com/ using chrome or edge does not throw InsecureCertificateException.

### How can we reproduce the issue?

```shell
from selenium import webdriver                                                                                                                                                                             
driver = webdriver.Chrome()                                                                                                                                                                                
driver.get("https://self-signed.badssl.com/")
```

### Relevant log output

```shell
.
```

### Operating System

linux

### Selenium version

python 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 99.0.4844.51

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

**Comment by diemol** [comment]
Please check this with the ChromeDriver team. I checked, and the Python bindings are not setting `acceptInsecureCerts` to `true` by default.

**Comment by PhilippSelenium** [comment]
> Please check this with the ChromeDriver team. I checked, and the Python bindings are not setting `acceptInsecureCerts` to `true` by default.

@diemol What does not setting `acceptInsecureCerts to true by default.` have to do with this bug?

This is exactely the point: The default is False so it should raise the error?

**Comment by PhilippSelenium** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4061

**Comment by diemol** [comment]
> > Please check this with the ChromeDriver team. I checked, and the Python bindings are not setting `acceptInsecureCerts` to `true` by default.
> 
> @diemol What does not setting `acceptInsecureCerts to true by default.` have to do with this bug?
> 
> This is exactely the point: The default is False so it should raise the error?

Yes. Since the bindings are not setting the capability to `true`, I assume the driver should error, which is why I suggest to reach to the ChromeDriver team.

**Comment by PhilippSelenium** [comment]
Thank you for the clarification, I reached out.
