### ISSUE TITLE
[🐛 Bug]: [py] [firefox] acceptInsecureCerts from deprecated capabilities overwrites options.accept_insecure_certs

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#10442]
### What happened?

In [L136](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#L136) if the deprecated capabilities option is None the default is set to  ```DesiredCapabilities.FIREFOX```
Then in [L168](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#L168)
The deprecated default from acceptInsecureCerts overwrites the set value from the options object.  

I am happy to put the proposed changes in a PR with the changes proposed below (Do not initialize deprecated parameters to a default use empty dict instead):

https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/webdriver.py#L135-L140
```
        if capabilities is None:
            capabilities = {}
        if not options:
            options = Options()
```

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.accept_insecure_certs = False

driver = webdriver.Firefox(options=options)
driver.capabilities()
```

yields:

```
{'acceptInsecureCerts': True,
 'browserName': 'firefox',
...
```
```


### Relevant log output

```shell
.
```

### Operating System

Linux

### Selenium version

python selenium==4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 98.0

### What are the browser driver(s) and version(s) where you see this issue?

gecko 0.30.0

**Comment by titusfortner** [comment]
We're removing the ability to send capabilities in Selenium 4.3. If you can PR a fix for Selenium 4.2 we'll get it in there. Thanks
