### ISSUE TITLE
[🐛 Bug]: session not created: This version of ChromeDriver only supports Chrome version 97 Current browser version is 99.0.4844.51

### ISSUE THREAD

**Issue by mironb13** [SeleniumHQ/selenium#10441]
### What happened?

I am trying to run some classes via CMD with the command : mvn test

When I run it throw the eclipse with testng it's run well.

But when I am trying to run it from CMD I got this message :

```
session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 99.0.4844.51
```
Before that I got this 

```
Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 23849
Only local connections are allowed.
```
My chromedriver is :

```
C:\Program Files\Selenium\ChromeDriver>chromeDriver -v
ChromeDriver 99.0.4844.51
```
What is the problem ? From where its take the sentence "This version of ChromeDriver only supports Chrome version 97" ? How can I make it works please ?

### How can we reproduce the issue?

```shell
I am trying to run from CMD the command : mvn test
```

### Relevant log output

```shell
session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 99.0.4844.51
```

### Operating System

Windowa 10

### Selenium version

4

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

 99.0.4844.51

**Comment by PhilippSelenium** [comment]
What version of chrome browser are you using?

**Comment by mironb13** [comment]
![image](https://user-images.githubusercontent.com/67999496/158194243-0df35f58-1637-4ec3-8087-47966cda1429.png)

**Comment by AutomatedTester** [comment]
Please update your version of chromedriver to 99.* to match Chrome. Due to the way chromedriver works with underlying technologies, within it's control, it can't guarantee that each driver works with the next version of the browser 🤷

**Comment by raultomescu** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/13545609/158269492-6b0fb9e6-cd33-4064-ac82-f6cee536c672.png">

I get this with the latest selenium-webdriver / chromedriver. Any ideas?

**Comment by mironb13** [comment]
> Please update your version of chromedriver to 99.* to match Chrome. Due to the way chromedriver works with underlying technologies, within it's control, it can't guarantee that each driver works with the

My chromedriver is updated to the match chromedriver version as I wrote in my post.
