### ISSUE TITLE
Python selenium webdriver throws unicode Attributes errors

### ISSUE THREAD

**Issue by sri85** [SeleniumHQ/selenium#1044]
We are using python selenium webdriver , of late we see error like `<type 'exceptions.AttributeError'>, AttributeError("'unicode' object has no attribute 'text'",), <traceback object at 0x0000000003434C48>)` . 

We are using 2.45 version of selenium python version 2.7.7 . 

And also we see this problem intermittently ? Is it a known issue , when i dug into source code of webdriver.py it has a line ` str= basestring ` which should fix most of the unicode errors. Since it happens intermittently its hard to provide more logs

**Comment by lukeis** [comment]
please provide a full traceback of the error and sample code to attempt to reproduce this. As it stands there's nothing anyone can do to even look into your issue. We can reopen this when something more is provided.

Also for generic user help / questions. Please ask on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by sri85** [comment]
`  self.compare_units_test('Singapore')
line 391, in compare_units_test
    self.assertTrue(home_page.is_loaded(), Errors.HOMEPAGE_LOGO_ERROR)
  File "", line 32, in is_loaded
    "Logo did not load results in 10 seconds")
  File "\venv\lib\site-packages\pscore\core\support\ps_wait.py", line 20, in until_visible
    self._wait_until_visible(locator, timeout, message, True)
  File "venv\lib\site-packages\pscore\core\support\ps_wait.py", line 15, in _wait_until_visible
    wait.until(EC.visibility_of_element_located(locator), message=message)
  File "\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 66, in until
    value = method(self._driver)
  File "\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 72, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File \venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 90, in _element_if_visible
    return element if element.is_displayed() else False
AttributeError: 'unicode' object has no attribute 'is_displayed'

2015-09-10 15:56:36 - INFO  wd_testcase.py:111 in run : Test Runner: Tearing down test: test_compare_units (tests.test.TestFlightsSearch)
2015-09-10 15:56:36 - INFO  wd_testcase.py:48 in tearDown : Test Runner: Attempting to teardown.
2015-09-10 15:56:36 - ERROR  wd_testcase.py:125 in run : Traceback (most recent call last):
  File \venv\lib\site-packages\pscore\core\wd_testcase.py", line 112, in run
    self.tearDown()
  File "\venv\lib\site-packages\pscore\core\wd_testcase.py", line 49, in tearDown
    WebDriverFinalizer.finalize(self.driver, self.has_failed(), self.logger, self.test_context)
  File "\venv\lib\site-packages\pscore\core\finalizers.py", line 28, in finalize
    WebDriverFinalizer.finalize_skygrid(driver, test_failed, test_context)
  File "\lib\site-packages\pscore\core\finalizers.py", line 152, in finalize_skygrid
    WebDriverFinalizer.finalise_skygrid_driver_failure(driver, test_context)
  File "\venv\lib\site-packages\pscore\core\finalizers.py", line 168, in finalise_skygrid_driver_failure
    final_url = driver.current_url
  File "venv\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 201, in __getattr__
    raise AttributeError(name)
AttributeError: current_url`

**Comment by sri85** [comment]
Could you reopen this issue now

**Comment by lukeis** [comment]
the stacktrace is a good start... can you provide some code to attempt to reproduce this on our side?  Seems that there's more in play here than you're letting on originally, you appear to be using the event firing webdriver too.

**Comment by sri85** [comment]
Below is code snippet that i have in my framework:
So basically i have implemented cusomt wait methods and then i am monkey patching the driver to be able to use these custom methods
```
class WebDriverExtensions(object):
    def wait_until(self, func, timeout, timeout_message):
        """

        :type self: selenium.webdriver.remote.webdriver.WebDriver
        """
        WebDriverWait(self, timeout).until(
            lambda method: func(), timeout_message)
        return self

    
    @staticmethod
    def patch(driver):
        """

        :type driver: selenium.webdriver.remote.webdriver.WebDriver
        """
        driver.wait_until = WebDriverExtensions().wait_until
        driver.wait = PSWait(driver)
        return driver
```
```
class PSWait(object):
    def __init__(self, driver):
        self.driver = driver

    def _wait_until_visible(self, locator, timeout, message, is_visible):
        if message is None:
            message = "Could not find {} in {} seconds".format(str(locator), timeout)

        wait = WebDriverWait(self.driver, timeout)
        if is_visible:
            wait.until(EC.visibility_of_element_located(locator), message=message)
        else:
            wait.until(EC.invisibility_of_element_located(locator), message=message)

    def until_visible(self, locator, timeout=3, message=None):
        self._wait_until_visible(locator, timeout, message, True)

    def until_not_visible(self, locator, timeout=3, message=None):
        self._wait_until_visible(locator, timeout, message, False)
```
```
driver = WebDriverExtensions.patch(driver)
        driver = EventFiringWebDriver(driver, DefaultWebDriverEventListener(driver))
```

**Comment by sri85** [comment]
Some of the elements which throw this error are , hope this helps
`By.XPATH, "//a[@class='company-logo']"`
`self.driver.find_element(By.XPATH, "(//div[@class='browse-data-entry']/h3)[{}]".format(index)).text`

**Comment by lukeis** [comment]
I just tried to reproduce with your code provided and i don't know what DefaultWebDriverEventListener is:

https://gist.github.com/lukeis/b30520ada6c27e58c31e

**Comment by sri85** [comment]
I have updated the code for `DefaultWebDriverEventListener`

**Comment by lukeis** [comment]
I've updated my gist:
https://gist.github.com/lukeis/b30520ada6c27e58c31e

Can't reproduce the issue, tried running a few times.

**Comment by sri85** [comment]
Thanks for trying :+1:

**Comment by sri85** [comment]
As I said it isn't reproducible 100% , happens intermittently

**Comment by sri85** [comment]
I found out the root cause of the bug , one of the test was calling the `driver.quit` and our framework in its teardown class was trying to access the `driver` object , that's the reason it was throwing error
