### ISSUE TITLE
ctrl +c in python terminal while driver is open [🐛 Bug]: 

### ISSUE THREAD

**Issue by arne182** [SeleniumHQ/selenium#10444]
### What happened?

The webpage will crash if in the terminal a ctrl+c command is used. Which might be used to correct for in incorrect input into the terminal.
Expected would be the KeyboardInterrupt in the terminal to not cause the web driver to close.

### How can we reproduce the issue?

```shell
Start a python Terminal.
Start the selenium driver
press ctrl+c
```

### Relevant log output

```shell
None
```

### Operating System

Windows 10

### Selenium version

4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 98

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 98.0.4758.102

**Comment by AutomatedTester** [comment]
When you said `start a selenium server`, what exactly do you mean? Is that run a test? start the Java jar?

**Comment by arne182** [comment]
![image](https://user-images.githubusercontent.com/844102/158564437-a38a2c8e-380f-4b99-a012-b9e07c4ac641.png)
After pressing ctrl+c in the python terminal the webdriver crashes.
![image](https://user-images.githubusercontent.com/844102/158564533-2f331974-ef7b-4448-ac24-8cd5feecc4db.png)
The Chrome closes and does not allow any further commands from the webdriver

**Comment by symonk** [comment]
seems _reasonable_ to me? I don't think selenium wants to start implementing signal handlers / catching KBI/sigint etc

**Comment by titusfortner** [comment]
It looks like `ctrl-c` raises an exception, and if it isn't handled, it will end the session. 
I'm not a Python expert, but It looks like a signal handler can be created by the user at the beginning of a session to manage this if needed. I don't think it is something Selenium should be doing.

**Comment by arne182** [comment]
In the terminal you sometimes need the ctrl+c and no other python module that I know of has this issue. I have tracked this all the way down to subprocess.Popen not staying open. It should not even be passing things into popen like keyboardinterrupt but it must be something to do with the pipe being used. I have even tried to put it into its own thread but it still closes. Who decided to use popen to get the webdriver communication going?

**Comment by titusfortner** [comment]
Apparently managing processes in Python is a pain in general, and Selenium has some use cases that other python modules don't. Looks like Popen is used to start the driver (essentially a separate server running on your machine), which is independent of the commands the bindings are sending to it. Perhaps you could start the driver manually and use RemoteWebDriver to access it if you need this?

**Comment by titusfortner** [comment]
Wanted to add a quick note that this was discussed more in detail here:
https://github.com/SeleniumHQ/selenium/issues/11303
