### ISSUE TITLE
[🐛 Bug]: Message: unknown error: bad inspector message

### ISSUE THREAD

**Issue by uitestteam** [SeleniumHQ/selenium#10447]
### What happened?

We are automating test execution of Oracle web based application. Our scripts ran successfully until last week 06-Mar-22. Script is getting failed from 07-Mar-22 displaying error message "Bad Inspector Message". Facing issue in some pages.

When we researched on Bad Inspector Message error on google, they have mentioned as “when Selenium can't parse the HTML or text of the elements because the elements are invalid unicode characters”.
We have enquired and came to know that other companies who automate the same application are also facing this issue.  We need selenium team help to resolve this issue as it working fine in tools like UFT.

Chrome Browser version:  99.0.4844.51
Chrome Driver version : 4.0.0-alpha-6

Note: we are logging new issue as old ticket #7359 has been closed.
We never faced this issue in same oracle web application for the past 1.5 years.

Error looks like: 
unknown error: bad inspector message: {"id":521,"result":{"root":{"nodeId":2696,"backendNodeId":2469,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":2,"children":

### How can we reproduce the issue?

```shell
Even a normal click through selenium is not working for a few pages in the oracle web application and is working for other pages.
```

### Relevant log output

```shell
unknown error: bad inspector message: {"id":521,"result":{"root":{"nodeId":2696,"backendNodeId":2469,"nodeType":9,"nodeName":"#document","localName":"","nodeValue":"","childNodeCount":2,"children":
```

### Operating System

Windows Server 2016

### Selenium version

JDK 17.0.1

### What are the browser(s) and version(s) where you see this issue?

 Chrome Browser version:  99.0.4844.51

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver version : 4.0.0-alpha-6

**Comment by titusfortner** [comment]
Maybe it is this issue? https://bugs.chromium.org/p/chromedriver/issues/detail?id=2269&q=navigate&can=2&sort=-id
They tried to fix it in Chrome 98, but they reverted it in Chrome 99 because it broke sendKeys
https://chromedriver.storage.googleapis.com/99.0.4844.35/notes.txt

Regardless of whether that is the correct issue, the fix will have to be made by Google.

**Comment by uitestteam** [comment]
Facing this issue with 99 versions of chrome, the same has been communicated with Chrome team and waiting for update.

**Comment by cor3000** [comment]
added reproducing case to (not about unicode characters but deeply nested DOMs causing this "bad inspector message")
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4064
and marked duplicates (both about the same error / and deeply nested DOM elements)
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4101
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4102

**Comment by Ankurku** [comment]
Hi, I am getting same issue while execution Oracle web based application in the Edge browser. Can you please let me know where can i log the bug ?

**Comment by Pikamander2** [comment]
We're getting this same error now too after updating to ChromeDriver 101.

Our Python script has been the same for a long time so it's definitely something new on Chrome's end.

**Comment by cor3000** [comment]
This morning I tried again with a nightly chromium build of version 104 and the error seemed to be fixed (in my test case provided in https://bugs.chromium.org/p/chromedriver/issues/detail?id=4064)
Can anyone confirm that observation?
