### ISSUE TITLE
[🐛 Bug]: ClientConfig.connectionTimeout setter is gone

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#10453]
### What happened?

We implemented a custom HttpClientFactory/HttpClient based on the Java 11 HttpClient to get rid of the netty dependencies.
Our ClientConfig is initialized with values out of a configuration file, but the connectionTimeout setter has been removed in commit 
https://github.com/SeleniumHQ/selenium/commit/1990a43a745669e87acb39331a0742979ecc728a 

@pujagani Is it possible to get it back please

### How can we reproduce the issue?

```shell
ClientConfig.defaultConfig().connectionTimeout(Duration.ofSeconds(1337))
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10 x64

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

none - this is api related

### What are the browser driver(s) and version(s) where you see this issue?

none - this is api related

**Comment by diemol** [comment]
It was removed because it has no effect on the configuration since we use a single instance of the HTTP client library we use. 

Not sure if adding it back makes sense, given that it does not change the settings at all.

**Comment by joerg1985** [comment]
Following this argumentation you sould remove the setters of `authenticateAs`, `connectionTimeout` and `readTimeout` too. ;)

These are also not used in the default code path used to start the driver and it seems not possible to change these values after the HttpClient is created.

Why is this setting treated different compared to all the others?

**Comment by diemol** [comment]
`authenticateAs` and `readTimeout` are creating a new object, the builder pattern is used. Also, there is no setter for `connectionTimeout`.

And yes, `authenticateAs` and `readTimeout` are used when creating the HTTP Client. 

They are all used here https://github.com/SeleniumHQ/selenium/blob/897caec5f850adb084d4409d1c5f8f57b6e66d26/java/src/org/openqa/selenium/remote/http/netty/NettyClient.java#L81-L120.  But when creating requests, it is not possible to set a connection timeout https://github.com/SeleniumHQ/selenium/blob/702b3aae7385adf331d75cdeacd79720cf6b9c84/java/src/org/openqa/selenium/remote/http/netty/NettyHttpHandler.java#L57-L63. It is how the client we use works. 

If we change to a different client in the future, and is used, probably we will end up adding it again.

**Comment by joerg1985** [comment]
Thank you for your time, i will close this and use a custom client config.
