### ISSUE TITLE
Proxy cannot be passed in from capabilities in protractor.conf.js for selenium-webdriver js/node 

### ISSUE THREAD

**Issue by theandrewlane** [SeleniumHQ/selenium#1046]
A proxy should be read in from capabilities, however it is not. 

from selenium-webdriver/builder.js 

``` 
 /** @private {?string} */
  this.proxy_ = null;

  /** @private {!webdriver.Capabilities} */
  this.capabilities_ = new Capabilities();
```

```  
if (url) {
    var executor = executors.createExecutor(url, this.proxy_);
    return WebDriver.createSession(executor, capabilities, this.flow_);
  }
```

We should have something like this instead:

```this.proxy_ = this.capabities.proxy; ```

**Comment by jleyba** [comment]
`Builder#proxy_` defines the proxy for [_webdriver_ commands](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/builder.js#L170).

The actual browser proxy is specified through [capabilities](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/builder.js#L240).
