### ISSUE TITLE
[🐛 Bug]: When using scroll-behavior smooth scroll and element outside of view port get error move target out of bounds

### ISSUE THREAD

**Issue by AceOfSpades29** [SeleniumHQ/selenium#10468]
### What happened?

Created a jsbin that uses smooth scroll. Please see code snippet and use it in a new project. This is using Selenium 4.0.1 (WebDriver and Support). 

What I expected to happen was that when using Actions MoveToElement when the element is outside of the view port, the element will scroll into view. What actually happens is the move target out of bounds error happens. 

### How can we reproduce the issue?

```shell
[TestClass]
    public class UnitTest1
    {
        private WebDriver _driver;
        [TestInitialize]
        public void Init()
        {
            _driver = new ChromeDriver(@"..\..\drivers");
        }

        [TestMethod]
        public async Task Test_MoveToElementSelenium()
        {
            _driver.Navigate().GoToUrl("https://output.jsbin.com/husomir");
            var moveToElement = _driver.FindElement(By.Id("three"));
            var actions = new Actions(_driver);
            actions.MoveToElement(moveToElement).Build().Perform();
            _driver.Quit();
        }

        [TestCleanup]
        public void Cleanup()
        {
            _driver.Quit();
        }
    }
```

### Relevant log output

```shell
Test method Tests.UnitTest1.Test_MoveToElementSelenium threw exception: 
    OpenQA.Selenium.MoveTargetOutOfBoundsException: move target out of bounds
      (Session info: chrome=99.0.4844.82)
```

### Operating System

Windows 10

### Selenium version

4.0.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 99 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
This is expected behavior per the specification. Mouse movements should not scroll the page. We are adding native scrolling functionality in the next minor version of Selenium (4.2), but it's not the most straightforward implementation so it has taken us a little while. In the meantime you can scroll the page with JavaScript or take one of the actions that automatically scrolls the element into view: `sendKeys()`, `clear()`, `click()` and `getScreenshotAs()`
