### ISSUE TITLE
[🐛 Bug]: Shadow Element are not working with latest version of chrome.

### ISSUE THREAD

**Issue by kunalbehl12** [SeleniumHQ/selenium#10476]
### What happened?

Hi,

I am using  99.0.4844.82 Windows Chrome version using Python BDD framework. We have test cases scenarios using Shadow element. It was working with 98 version chrome. 
test cases have started failing with latest version. 

Could you please advise.
![image](https://user-images.githubusercontent.com/93395588/160108682-4efca880-2b9e-4816-9300-45986460b3ed.png)

### How can we reproduce the issue?

```shell
Shadow element test case with 99 version chrome
```

### Relevant log output

```shell
Assertion Error
```

### Operating System

Windows 10

### Selenium version

4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

99.0.4844.82

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
If this was working in Chrome 98 and failing in Chrome 99, please report it to the ChromeDriver team.

**Comment by kunalbehl12** [comment]
https://github.com/SeleniumHQ/selenium/issues/10019#issuecomment-972671939

this is the original issue.
