### ISSUE TITLE
CSP cannot be enabled in FirefoxDriver

### ISSUE THREAD

**Issue by bmannix** [SeleniumHQ/selenium#1047]
A few years ago, @barancev made a change (https://github.com/SeleniumHQ/selenium/commit/1b3c4fcf96d37f53130612f37021005e7eb865dc) to fix a javascript error encountered when evaluate.js was included on a page.  

https://code.google.com/p/selenium/issues/detail?id=6358

However, the effect of this change is that it is impossible to launch a Firefox instance that respects CSP headers and directives.  CSP is becoming increasingly relevant and many sites are implementing it.  I think it's fine to leave CSP disabled by default, however, we should not prevent users from setting this attribute to true by including it in the "frozen" (immutable) section of the Firefox driver configuration.  Instead, it should be moved to the "mutable" section so that users can change the value of this setting and execute tests in a context that respects CSP headers and directives.

**Comment by barancev** [comment]
Unfortunately, FirefoxDriver can't work with CSP enabled.
You'll have to wait till MarionetteDriver hits the ground running.
