### ISSUE TITLE
[🐛 Bug]: fullscreen_window() in combination with options.set_preference() is not working

### ISSUE THREAD

**Issue by tissi-2** [SeleniumHQ/selenium#10475]
### What happened?

The aim in my project is to get a kiosk-like fullscreen firefox that does not show any menu, search or address bar, even if you hover with the mouse over the top screen. The only way to get out of the fullscreen should be by pressing the F11 key.

To achieve that I already tried the following:
[https://support.mozilla.org/en-US/questions/1323320
](https://support.mozilla.org/en-US/questions/1323320)

This works fine when using firefox without the webdriver.
As far as I know the use of specific profiles has been deprecated, so the chrome folder with the userChrome.css will not be copied, hence it will not be taken into account when firefox is called via selenium/geckodriver.

The next approach was using firefox preferences via Options(). There is a way to prevent the bars from showing up by using

´<html><body>

full-screen-api.ignore-widgets | true
-- | --

</body>
</html>´

This also works fine, but in combination with the command driver.fullscreen_window() it ends up in a windowed firefox which is not fullscreen nor maximized.

I then tried to first maximize the window and then calling the fullscreen command, but even with that it first maximizes the window and subsequently ends up in a smaller windowed firefox which always has a certain size.

I ended up using pyautogui.press('f11'), but that really should not be the answer to the problem. Why not using Chrome and chromedriver? Because I'd like to stick with python and firefox.

Below you will find the code with testing an existing firefox profile.

### How can we reproduce the issue?

```shell
options=Options()
options.Profile='C:/Users/Tissi/AppData/Roaming/Mozilla/Firefox/Profiles/xx513scw.Selenium_Test'
options.binary_location = 'C:/Program Files/Mozilla Firefox/firefox.exe'
options.set_preference("full-screen-api.ignore-widgets", True)
service = Service(r'C:\Python310x64\geckodriver')
driver = webdriver.Firefox(service=service, options=options)
driver.maximize_window()
driver.fullscreen_window()
```

### Relevant log output

```shell
I do not have any log.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 98.0.1. 64-bit

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0 (2021-09-16, d372710b98a6)

### Are you using Selenium Grid?

Not applicable

**Comment by diemol** [comment]
This is more a question of how to do X in Firefox, which could be posted to one of the links below or asked in the chats (links below) where some Mozilla GeckoDriver folks are present. Not sure if https://github.com/mozilla/geckodriver is a place to ask this as well.
