### ISSUE TITLE
[🐛 Bug]: Getting HttpMethod for PUT request returns GET

### ISSUE THREAD

**Issue by fviktor92** [SeleniumHQ/selenium#10484]
### What happened?

Tried network interception for a PUT request, but it is not possible, because the org.openqa.selenium.remote.http.HttpMethod does not contain a PUT value. When a PUT request is intercepted and HttpRequest.getMethod() is called, it returns HttpMethod.GET

### How can we reproduce the issue?

```shell
https://github.com/fviktor92/test_framework_kotlin/blob/master/src/test/kotlin/com/fviktor/test_framework_kotlin/ui/SwaggerV2Test.kt
updatingAnExistingPetShouldSucceed test method

1. Set a breakpoint in org.openqa.selenium.devtools.NetworkInterceptor#NetworkInterceptor(org.openqa.selenium.WebDriver, org.openqa.selenium.remote.http.Routable)
2. Execute above mentioned test case
3. When breakpoint is reached, because the PUT request has been sent to /pet endpoint, call req.method
Actual result: "GET"
Expected result: "PUT"
```

### Relevant log output

```shell
{}
```

### Operating System

Windows 10

### Selenium version

Java 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 99.0.4844.51

**Comment by diemol** [comment]
Linked PR was merged and this will be available in the next release. Ideally in 1-2 weeks.
