### ISSUE TITLE
[🐛 Bug]: Microsoft Edge in IE Mode: On clicking elements its throwing 'org.openqa.selenium.ElementNotInteractableException' error. But same function and locator is working for Selenium 3.

### ISSUE THREAD

**Issue by message2guna** [SeleniumHQ/selenium#10488]
### What happened?

Recently I have moved from selenium 3.14 to Selenium 4  in order to enable automation in Microsoft edge with IE mode.

On clicking most of the elements its throwing following error.. But same function and locator is working for Selenium 3..

org.openqa.selenium.ElementNotInteractableException: Received a JavaScript error attempting to click on the element using synthetic events. We are assuming this is because the element isn't displayed, but it may be due to other problems with executing JavaScript.
or
org.openqa.selenium.InvalidElementStateException: A JavaScript error was encountered clearing the element. The driver assumes this is because the element is hidden, disabled or read-only, and it must not be to clear the element.

Build info: version: '4.0.0', revision: '3a21814679'
os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18'

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
public class IEDriverSample {
    public static void main(String[] args) {        
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        
        WebDriver driver = new InternetExplorerDriver(ieOptions);
        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("IE mode", Keys.RETURN);
        driver.close();
    }
}
```

### Relevant log output

```shell
org.openqa.selenium.InvalidElementStateException: A JavaScript error was encountered clearing the element. The driver assumes this is because the element is hidden, disabled or read-only, and it must not be to clear the element.
Build info: version: '4.0.0', revision: '3a21814679'
os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [1c7a0657-9a30-4d56-b477-d6cf21e45fb0, clearElement {id=4f3ce207-d0f4-43db-a8e3-89a8cd680829}]
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: true, ie.browserCommandLineSwitches: , ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:55036/, nativeEvents: true, requireWindowFocus: false}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Element: [[InternetExplorerDriver: internet explorer on WINDOWS (1c7a0657-9a30-4d56-b477-d6cf21e45fb0)] -> xpath: //input[contains(@name,'effectiveDate')]]
Session ID: 1c7a0657-9a30-4d56-b477-d6cf21e45fb0
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft edge with IE mode

### What are the browser driver(s) and version(s) where you see this issue?

IE driver 4.0.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
The error log you've provided says you are attempting to send the clear command to an input element with the name "effectiveDate"
Since the clear command only works for input elements with a text type, the effective date element is of a different type. This is expected, do not send the clear command to that element.

**Comment by message2guna** [comment]
"Effective date" is an element with a text type. Clear command is working for the same element when we tried in Selenium-Java 3.
Issue exists only in Selenium-Java 4.0.0 version.

**Comment by titusfortner** [comment]
Do you have reproducible code for it?

**Comment by message2guna** [comment]
**Here is the code** 
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
public class IEDriverSample {
    public static void main(String[] args) {        
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        WebDriver driver = new InternetExplorerDriver(ieOptions);
        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.clear();
        driver.close();
    }
}

**System info:**
OS: Windows 10
Selenium : Java 4.0.0
Driver: IE driver 4.0.0
Edge Browser: Version: 99
