### ISSUE TITLE
Alert dialog dismissed automatically when UnhandledAlertError raised

### ISSUE THREAD

**Issue by duncan-bayne** [SeleniumHQ/selenium#1048]
This change was introduced in [selenium-webdriver 2.18.0](https://github.com/SeleniumHQ/selenium/blob/master/rb/CHANGES#L408):

> Firefox and IE:
>  * Raise UnhandledAlertError if an alert is present during an operation. The unhandled alert is also dismissed to mitigate repeat exceptions.

I believe this change is in error, because it creates several problems:

1. It becomes impossible to write a step that asserts the presence of the alert and dismisses it, if any prior step triggers an UnhandledAlertError.
2. The behaviour varies between Firefox / IE and Chrome.

**Comment by lukeis** [comment]
you can override the default behavior right now -

desiredCapability.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.<choose one>)

this should work for Firefox / IE.

The W3C spec is defining unexpected alert behavior (kind of it seems a bit unclear) - https://w3c.github.io/webdriver/webdriver-spec.html#user-prompts

For issues related to chromedriver, please log bugs with them:
https://code.google.com/p/chromedriver/issues/list

For FirefoxDriver (not marionette) and IE Driver bugs should be continued to log here, but please log them with concise issues that can be reproduced (example scripts are very appreciated) with expected results.

For now, will close this issue, until there's something more actionable we can do.
