### ISSUE TITLE
[🐛 Bug]: (ruby) location_once_scrolled_into_view throws element not interactable

### ISSUE THREAD

**Issue by seleniumghost** [SeleniumHQ/selenium#10498]
### What happened?

After updating from ruby 2.2.4p230 with selenium-webdriver 3.141.0 to ruby 3.1.1p18 with selenium-webdriver-4.1.0 i got the problem that location_once_scrolled_into_view throws element not interactable. After a lot of research I found https://github.com/watir/watir/issues/884#issuecomment-573124544:

> Selenium is using #send_keys to bring the element into view, which only works for keyboard-interactable elements
> I would suggest logging a bug in the Selenium project - ie I don't think it makes sense that their #location_once_scrolled_into_view does not work for label elements.

With that I finally was able to track it back to https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/remote/bridge.rb:

```
def element_location_once_scrolled_into_view(element)
   send_keys_to_element(element, [''])
   element_location(element)
end
```

After commenting it out, it got back to work.

```
def element_location_once_scrolled_into_view(element)
   #send_keys_to_element(element, [''])
   element_location(element)
end
```

I could not find any reason (e.g. in https://www.w3.org/TR/webdriver/#dfn-scrolls-into-view) why this line with #send_keys should be in here.

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'
$driver = Selenium::WebDriver.for :chrome
$driver.get "https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&hl=en-GB"
($driver.find_element(:xpath,"//span[contains(text(),'‪English (United Kingdom)‬')]")).location_once_scrolled_into_view
```

### Relevant log output

```shell
"[ERROR]Selenium::WebDriver::Error::ElementNotInteractableError: element not interactable\n  (Session info: chrome=99.0.4844.84)"
```

### Operating System

Windows 10

### Selenium version

selenium-webdriver-4.1.0, ruby 3.1.1p18

### What are the browser(s) and version(s) where you see this issue?

Chrome 99.0.4844.84

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

**Comment by titusfortner** [comment]
If you remove the command to send keys, you get the location returned, but it won't scroll the element into view if it is outside the viewport. If you need the location, use that method instead. If you need the scrolling, selenium will have a better implementation for this in the next release.

**Comment by seleniumghost** [comment]
Hm, you are correct, it does not scroll. But an issue which blocks if element is not interactable is worse for me. I also made the experience that send keys does not work if there is no visible UI / headless.

Within the bridge the following command did not work, but i was able to use it in my custom steps, so i got a workaround: 
> execute_script("arguments[0].scrollIntoView();", element)

When this new release can be expected?

**Comment by titusfortner** [comment]
What is it you are trying to do? For most users, the only reason to scroll something into view is to do something with it, so current behavior makes sense.

Taking an element screenshot will also scroll the element into view:
https://w3c.github.io/webdriver/#take-element-screenshot

You can do this and just ignore the return value:
```
element.screenshot_as :png
```

> When this new release can be expected?

When it has been implemented in all the supported languages; we don't have a timeframe for it.

**Comment by seleniumghost** [comment]
Well, I am trying to scroll it into view. It might be that I use it then for a screenshot, but have also a lot of other use cases.

As it did not fix it enough, i added execute_script in selenium-webdriver-4.1.0\lib\selenium\webdriver\common\element.rb, so i got a workaround for the meantime until the next release: 

> def location_once_scrolled_into_view
>   bridge.element_location_once_scrolled_into_view @id
>   driver.execute_script("arguments[0].scrollIntoView();", self)
> end

Thank you for your help.
