### ISSUE TITLE
[🐛 Bug]: The driver is not executable

### ISSUE THREAD

**Issue by Orange-es** [SeleniumHQ/selenium#10493]
### What happened?

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project sendMail04: An exception occured while executing the Java class. The driver is not executable: /home/runner/work/SendHealth/SendHealth/chromedriver -> [Help 1]
![123](https://user-images.githubusercontent.com/54025960/160774807-51482bed-76bf-4d89-ac27-8bfce562aa76.png)

I don't know why this is happening, please help me

### How can we reproduce the issue?

```shell
I don't have a clue
```

### Relevant log output

```shell
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project sendMail04: An exception occured while executing the Java class. The driver is not executable: /home/runner/work/SendHealth/SendHealth/chromedriver -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

### Operating System

Ubuntu

### Selenium version

4.1.3

### What are the browser(s) and version(s) where you see this issue?

chrome 99.0.4844.35

### What are the browser driver(s) and version(s) where you see this issue?

chrome 99.0.4844.35

### Are you using Selenium Grid?

I don't have a clue

**Comment by Orange-es** [comment]
> How can we reproduce the issue?
This is the code address look at it

https://github.com/Orange-es/SendHealth.git

**Comment by diemol** [comment]
Seems you are not having the error anymore https://github.com/Orange-es/SendHealth/runs/5750150175?check_suite_focus=true#step:8:32

You needed to make ChromeDriver executable, which you did https://github.com/Orange-es/SendHealth/commit/8950671ef87ead92346aab96f3ca3b8781596374
