### ISSUE TITLE
[🐛 Bug]: Not able to read url to parallel instances in edge browser for IE mode using selenium

### ISSUE THREAD

**Issue by Akshatha-chowta** [SeleniumHQ/selenium#10495]
### What happened?

Edge(IE mode), parallel instance of edge in IE mode does not open/load the url. It load's the url only in one instance, for rest of the instances url does not load(struck on localhost #### page). Also, no error is thrown by the selenium.

### How can we reproduce the issue?

```shell
System.setProperty("webdriver.ie.driver", "C:\\Selenium\\IEDriverServer.exe");
            InternetExplorerOptions options = new InternetExplorerOptions();
            options.attachToEdgeChrome();
             options.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
             options.ignoreZoomSettings();
             options.introduceFlakinessByIgnoringSecurityDomains();
             options.disableNativeEvents();
            options.requireWindowFocus();
            options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);
            options.destructivelyEnsureCleanSession();
            options.enablePersistentHovering();
              DriverFactory.getInstance().setDriver(new InternetExplorerDriver(options));
```

### Relevant log output

```shell
In console it is not showing any error logs , it is showing all expected execution steps.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.1.2

### What are the browser(s) and version(s) where you see this issue?

edge 99.0.1150.55

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.0.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Can you please share a GitHub repository so we can clone it an reproduce the issue?

**Comment by Akshatha-chowta** [comment]
Hi Diemol,
Please find below repository for above illustrated issue.
https://github.com/YogeshBathri/EdgeIEMode.git

**Comment by diemol** [comment]
What command can I use to run the project?

**Comment by Akshatha-chowta** [comment]
You can use testng.xml suite to run .
Also make sure in edge browser setting, 
1. Internet explorer mode button should be : ON 
2. Allow sites to reloaded in internet Explorer mode should be :ALLOW

**Comment by HiroyukiSakoh** [comment]
Might it be the same problem?
https://github.com/SeleniumHQ/selenium/issues/10339

**Comment by diemol** [comment]
I was able to reproduce the issue, with a more simple [example](https://github.com/diemol/selenium-issues/blob/c15bcc368fbd1633e0fb2e3bc5185b6ed97eb853/selenium/issue-10495/src/test/java/Issue10495Test.java).

However, since Edge in IE Mode seems to be using the same IE engine, probably sessions in parallel won't work. But it is better to as the Edge team on this.

**Comment by Akshatha-chowta** [comment]
Hi Team,
I have created issue with MSEdgedriver team for the same.
https://github.com/MicrosoftEdge/EdgeWebDriver/issues/11

**Comment by HiroyukiSakoh** [comment]
@diemol 
I think this issue is related to the EdgeIE mode feature of IEDriver. 
will MicrosoftEdgeWebDriver support IE mode in the future?
Or will the Edge team develop not only EdgeWebDriver but also IEDriver?

As I have presented in QuickFix #10339, 
I think the problem is caused by the identification of the Edge window handler in IEDriver.

**Comment by diemol** [comment]
The Edge team has been kind to implement the IE Mode in Edge support through the IEDriver, that is why we suggest to post the issue there.

**Comment by HiroyukiSakoh** [comment]
Oh, I get it.
