### ISSUE TITLE
[🐛 Bug]: Exceptions talk about CDP 100 with selenium 4 and devtool v85

### ISSUE THREAD

**Issue by kavyaks0422** [SeleniumHQ/selenium#10507]
### What happened?

I was running my scripts in Chrome 99 and Edge 99 using Selenium 4 and dev tool V85, it worked fine. but after the update of Chrome and Edge to its higher version(100), I am getting exceptions that talk about CDP

![image](https://user-images.githubusercontent.com/94300883/161509224-cfd1eaf2-2991-47bc-84f3-c51e8f2bbeca.png)

How can I overcome this issue with CDP, since we have other dependency with selenium 4, so it is not possible us to upgrade selenium version, also let us know why devtool v85 is not compatible with CDP100?

### How can we reproduce the issue?

```shell
By using Selenium 4 and devtools v85 for launching edge and chrome browsers
```

### Relevant log output

```shell
Apr 04, 2022 8:28:42 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 100, so returning the closest version found: a no-op implementation

Apr 04, 2022 8:28:42 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Unable to find CDP implementation matching 100.

Apr 04, 2022 8:28:42 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.0.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
org.openqa.selenium.devtools.DevToolsException: You are using a no-op implementation of the CDP. The most likely reason for this is that Selenium was unable to find an implementation of the CDP protocol that matches your browser. Please be sure to include an implementation on the classpath, possibly by adding a new (maven) dependency of `org.seleniumhq.selenium:selenium-devtools-vNN:4.0.0` where `NN` matches the major version of the browser you're using.
Build info: version: '4.0.0', revision: '3a21814679'
```

### Operating System

Windows 10

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 100, Edge 100

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 100.0.4896.60 , Edge 100.0.1185.29 

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment]
Thank you for sharing the details. Kindly, upgrade to the latest release 4.1.3. This will be able to pick up the nearest matching version and your code/tests should run as expected for CDP 100. When the exact matching version is not found, Selenium tries to map to one of the nearest 5 supported versions https://github.com/SeleniumHQ/selenium/blob/468b5e345d430688776aa64f65fc2a1395e7aee5/java/src/org/openqa/selenium/devtools/CdpVersionFinder.java#L133. In 4.0.0, the maximum supported version is 95 and hence it is not able to find the nearest match. 
The exact support for Chrome 100 is added as part of https://github.com/SeleniumHQ/selenium/commit/1c14b91718699c2ee3dec06f8f48d83a5e0769b5. It will be available in the next release.

**Comment by titusfortner** [comment]
Couple notes:
These are warnings not errors, things probably will still work as expected
v85 is present because that is the version required by Firefox. For chrome, you want the closest version to the released version of Chrome.
