### ISSUE TITLE
[🐛 Bug]: Headless ignores guest/incognito option

### ISSUE THREAD

**Issue by michael-kubala** [SeleniumHQ/selenium#10505]
### What happened?

I'm using ASP.NET Core 5 (also tried with 6) with Selenium 4.1. When I run my code regularly, it works fine, but when I set it to headless, I don't think any of the options work including the Guest, inPrivate, or incognito mode because I keep getting 2FA prompts as if it is logging in with my cached credentials.

Here are my options with EdgeDriver:

```
var options = new EdgeOptions();
options.AddArgument("-guest");
options.AddArgument("disable-gpu");
options.AddArgument("headless");

using (var driver = new EdgeDriver(DRIVERS_PATH, options))
{
   driver.Manage().Window.Maximize();
   driver.Manage().Cookies.DeleteAllCookies();

   var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(45));

   driver.Navigate().GoToUrl(recordUrl);
   // get a 2FA prompt here 
}
```
Or when using ChromeOptions

```
var options = new ChromeOptions();
            options.AddArguments("--headless");
            options.AddArguments("--window-size=1920,1080");
            options.AddArguments("--disable-gpu");
            options.AddArguments("--disable-extensions");
            options.AddArguments("--proxy-server='direct://'");
            options.AddArguments("--proxy-bypass-list=*");
            options.AddArguments("--start-maximized");
            options.AddArguments("--no-first-run");
            options.AddArguments("--no-default-browser-check");
            options.AddArguments("--ignore-certificate-errors");
            options.AddArguments("--test-type");
            options.AddArguments("--user-agent=\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36\"");
            //options.AddArguments("--guest");
            options.AddArguments("--incognito");
```

I'm trying to connect to D365. I've test connecting to SharePoint with the same result. 

### How can we reproduce the issue?

```shell
var options = new EdgeOptions();
options.AddArgument("-guest");
options.AddArgument("disable-gpu");
options.AddArgument("headless");

using (var driver = new EdgeDriver(DRIVERS_PATH, options))
{
   driver.Manage().Window.Maximize();
   driver.Manage().Cookies.DeleteAllCookies();

   var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(45));

   driver.Navigate().GoToUrl(recordUrl);
   // get a 2FA prompt here 
}
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10 Enterprise

### Selenium version

C# version 4.1

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge Version 99.0.1150.55 (Official build) (64-bit), Google Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 99.0.1153.0 x64 and x86

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Also, what happens when you use Firefox? 
Probably you need to report this to the ChromeDriver team, it is known that headless has different behavior compared to a normal headed browser.

**Comment by titusfortner** [comment]
If it's working in production Chromium release, but not working in headless, then Selenium is sending the right commands to the driver, and the issue is something that isn't supported by the browser in headless mode. You can raise an issue with Chromedriver team to address this, but it might not be possible.

**Comment by michael-kubala** [comment]
Thanks for the feedback. I switched to using Firefox and it is working correctly so I will just use that instead and will see about maybe reporting this to the ChromeDriver team.
