### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by duaa-alkilanie** [SeleniumHQ/selenium#10506]
### What happened?

From the Website Locator strategies page in the documentation of **Chaining relative locators**, there is a Circle brace missing from **the locator Chaining**

 Expected : 
RelativeLocator.with(By.tagName("button")).below(By.id("email")).toRightOf(By.id("cancel"));
Actual : 
RelativeLocator.with(By.tagName("button")).below(By.id("email").toRightOf(By.id("cancel"));

<img width="1440" alt="Screen Shot 2022-04-03 at 1 15 51 AM" src="https://user-images.githubusercontent.com/64094336/161404580-1b45fb73-1fd1-48be-96f1-ecc748709d7d.png">

### How can we reproduce the issue?

```shell
Test step : 
1- go to https://www.selenium.dev/documentation/webdriver/elements/locators/
2- scroll down to get  https://www.selenium.dev/documentation/webdriver/elements/locators/#chaining-relative-locators
3- check the **Chaining relative locators**
```

### Relevant log output

```shell
N/A
```

### Operating System

macOS (Big Sur)

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

Chrome 99 

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by baflQA** [comment]
Hey, I've "fixed" that in https://github.com/SeleniumHQ/seleniumhq.github.io/pull/981, plus some more brackets related fixes.
