### ISSUE TITLE
Inconvenient text querying & manipulation

### ISSUE THREAD

**Issue by xmo-odoo** [SeleniumHQ/selenium#1050]
Manipulating `contenteditable` elements with webdriver (e.g. testing an RTE's flow) is quite inconvenient right now, while it's possible to get all the text of an object, selecting text requires action chains and iffy offsets, and I've found no way to get the offset of some text within an element so things are really quite inconvenient and really not cross-platform. I also haven't found a way to query text selection e.g. know/copy currently selected text.

There's always the alternative of using text ranges from within JS/DOM, but it removes much of the user-similar interaction with page content webdriver provides.

**Comment by lukeis** [comment]
this issue report leaves us with nothing really actionable?

If there's a high level conceptual miss in the WebDriver API, then I suggest logging a bug against the W3C standard being developed:
https://w3c.github.io/webdriver/webdriver-spec.html

If I understand you correctly, you want to be able to replicate highlighting / selecting text on the screen? (If so, action chains is the best way to accomplish this... sorry if you think that's painful, but I don't think there's an alternative... if you can think of an alternative, please propose it with the w3c spec)

**Comment by xmo-odoo** [comment]
> this issue report leaves us with nothing really actionable?

Not really, sorry, it's more of a "there's a hole in here and I'm not sure how you'd fill it" kind of report.

> If there's a high level conceptual miss in the WebDriver API, then I suggest logging a bug against the W3C standard being developed: https://w3c.github.io/webdriver/webdriver-spec.html

Ah I wasn't sure about the relation between the two, will do.

> If I understand you correctly, you want to be able to replicate highlighting / selecting text on the screen?

Yes, or more generally manipulating text within elements (in more ways than just "remove all the text" and "append to the existing text")

> If so, action chains is the best way to accomplish this... sorry if you think that's painful

It's really that there's a part of the puzzle missing, many action chains work in term of pixel offsets but there seems to be no way to match/find text and translate that text into offsets, so action chains would be extremely brittle if they were cross-platform to start with, which I'm not even certain of.

**Comment by ddavison** [comment]
related https://github.com/w3c/webdriver/pull/108
