### ISSUE TITLE
[🚀 Feature]: Chrome101 adds a  verify your identity popup I'm unable to pass with selenium

### ISSUE THREAD

**Issue by fenchu** [SeleniumHQ/selenium#10517]
### Feature and motivation

Chrome: Version 101.0.4951.15 (Official Build) beta (64-bit)

from chrome101 this popup happens on my machine when I ask for access to the fido2 security key feature
https://docs.microsoft.com/en-us/azure/active-directory/authentication/fido2-compatibility

I'm unable to control it via selenium, the chrome developer console do not react on it.
I have to manually just press enter to continue. but sending this enter I'm unable to.

Is there a way to bypass it via config? or chrome developer api?

How can I pass this?
![chrome100-verify-your-identity](https://user-images.githubusercontent.com/11349883/161975709-1caa88c8-af62-424c-8fae-2e308bff5a93.jpg)

### Usage example

```
       wd.get(url)
        el = WebDriverWait(wd, args.webwait).until(EC.presence_of_element_located((By.XPATH, "//bp-button[@name='authenticationExecution'] | //*[@id='fido2']")))
        el.click()
        log.info("here the security key popup happens - code below have no impact")
        action = ActionChains(wd)
        action.send_keys(Keys.ARROW_DOWN).perform()
        action = ActionChains(wd)
        action.send_keys(Keys.ENTER).perform()
```

**Comment by AutomatedTester** [comment]
It looks like we will need to see about getting https://wpt.fyi/results/webdriver/tests/permissions/set.py?label=master&label=experimental&aligned&q=permissions implemented in Selenium. I didn't realise the chrome folks had implemented it.

**Comment by diemol** [comment]
What needs to be implemented, @AutomatedTester?

**Comment by pujagani** [comment]
Thank you for sharing the details. The Chrome-specific WebAuth flow triggered in the code shared is not specific to Chrome 101 version. It was added approximately around Chrome 67. The "pop-up" shared is of the login for the website you are trying to access since it has enabled WebAuthn. To automate WebAuthn steps, https://w3c.github.io/webauthn/#sctn-automation defines a set of APIs that Selenium needs to implement. Currently, only Java implementation exists. For other language bindings, it is tracked in https://github.com/SeleniumHQ/selenium/issues/10541.

To verify that the VirtualAuthenticator will solve the issue, I ran a Java example and it handles the web authentication flow as expected. 
public static void main(String args[]) throws InterruptedException {

```
    WebDriver driver = new ChromeDriver();

    HasVirtualAuthenticator virtualAuthenticatorManager = ((HasVirtualAuthenticator) driver);

    VirtualAuthenticatorOptions options = new VirtualAuthenticatorOptions();
    options.setIsUserConsenting(true);
    options.setProtocol(VirtualAuthenticatorOptions.Protocol.U2F);
    options.setTransport(VirtualAuthenticatorOptions.Transport.USB);
    VirtualAuthenticator authenticator = virtualAuthenticatorManager.addVirtualAuthenticator(options);
    authenticator.setUserVerified(true);

    driver.get("https://webauthn.io/");
    WebElement userName = driver.findElement(By.id("input-email"));
    userName.sendKeys("username");

    Select selectAttestation = new Select(driver.findElement(By.id("select-attestation")));
    selectAttestation.selectByVisibleText("Direct");

    Select authenticatorType = new Select(driver.findElement(By.id("select-authenticator")));
    authenticatorType.selectByValue("cross-platform");

    WebElement register = driver.findElement(By.id("register-button"));
    register.click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(40));

    WebElement login = driver.findElement(By.id("login-button"));

    wait.until(ExpectedConditions.elementToBeClickable(login));
    login.click();

    wait.until(ExpectedConditions.presenceOfElementLocated(By.className("col-lg-12")));

    if (driver.getPageSource().contains("You're logged in!")) {
      System.out.println("Success");
    } else {
      System.out.println("Failed");
    }

    driver.quit();
```

**Comment by pujagani** [comment]
> It looks like we will need to see about getting https://wpt.fyi/results/webdriver/tests/permissions/set.py?label=master&label=experimental&aligned&q=permissions implemented in Selenium. I didn't realise the chrome folks had implemented it.

Permissions are already implemented in all Selenium language bindings. However, Permissions are not applicable in the WebAuthn context.

**Comment by SinghHrmn** [comment]
@diemol 
CC: @AutomatedTester @pujagani 

We can close this as it is being tracked in #10541

**Comment by diemol** [comment]
Thank you for pointing it out, @SinghHrmn

Closing.
