### ISSUE TITLE
[🚀 Feature]: wait until page reload, wait until url change

### ISSUE THREAD

**Issue by HeyKJ** [SeleniumHQ/selenium#10512]
### Feature and motivation

hello.
thank you for making selenium.
i have a deep respect for Selenium developers.

please add wait until page reload, wait until url change.
it might be useful everywhere.

### Usage example

```
await driver.wait(until.pageReload({
     reloadTrigger: () => driver.findElement(By.css("#submit")).click()
}), 3000)
// after reload...

await driver.wait(until.urlChange({
    changeTrigger: () => driver.findElement(By.css(".movePage")).click() 
}), 3000)
// after change
```

**Comment by titusfortner** [comment]
Yes, these are very useful methods for your tests. 
Selenium leaves these methods for the user to implement in their own code. 

I implement like this in my Ruby automation code; it'll look different in JS
```
original_url = driver.current_url
take_navigation_action()
wait.until { driver.current_url != original_url }
```

```
located_element = find_existing_element()
take_reloading_action()
wait.until do
  begin
    !located_element.displayed?
  rescue StaleElementReferenceError
      true
  end
end
```
