### ISSUE TITLE
[🐛 Bug]: tags missing for 4.1.1-4.1.3

### ISSUE THREAD

**Issue by bollwyvl** [SeleniumHQ/selenium#10511]
### What happened?

The official packages on e.g. PyPI have been updated with versions newer than 4.1.0, but the sources have not been tagged.

https://github.com/SeleniumHQ/selenium/tags

See also https://github.com/SeleniumHQ/selenium/issues/9917: issues like these are making it harder for downstreams to package selenium.

### How can we reproduce the issue?

```shell
- Visit PyPi
- pick a version
- download the wheel
- visit github
- try to find the commit from which the wheel was built
```

### Relevant log output

```shell
n/a
```

### Operating System

all

### Selenium version

4.1.1+

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
For the mono-repo we are only creating tags that apply to the whole project. Each language releases a 4.1.0, but patch releases (e.g., 4.1.1) are for language binding specific updates.

Is there a particular use case you have in mind? Remember that some of the files in the released package are generated by the build process, and are not stored in the repo. If you need to see exactly what code is being used in the release, you should be able to just unzip the wheel file. Alternatively, you can look at the commit where the version has been updated in the code: https://github.com/SeleniumHQ/selenium/blame/trunk/py/BUILD.bazel#L8

**Comment by bollwyvl** [comment]
Thanks for the reply.

As with the sdists issue, predictable version-based URLs that yield
hashable input artifacts are far easier for downstream package managers to
automate against.

Wheels discard a fair amount of build information, and parsing bazel files
sounds brittle as well... But if that's the best we're going to get...

**Comment by AutomatedTester** [comment]
@bollwyvl We can start stamping the wheels so that they have a some more build info in them. I haven't done this yet as it can impact the build caching but we can add it in if you think it help
