### ISSUE TITLE
[🐛 Bug]: Driver method call hangs when there is an alert in child window

### ISSUE THREAD

**Issue by justinearl** [SeleniumHQ/selenium#10522]
### What happened?

When an alert is present in other window handles the execution of most driver method calls causes a timeout. Simple alert checking in current window also does not work.

### How can we reproduce the issue?

```python
from selenium import webdriver

driver = webdriver.Chrome()

driver.get('https://www.google.com/')
driver.execute_script('window.open("", "popupwindow", "width=500,height=500");')

parentWindowHandle = driver.current_window_handle
childWindows = driver.window_handles
childWindows.remove(parentWindowHandle)

# Switch to any child window to generate an alert
driver.switch_to.window(childWindows[0])
driver.execute_script("alert('Sample ALert')")

# Switch back to parent window
driver.switch_to.window(parentWindowHandle)

# Most of the driver call fail here since there is an alert in the other window
alert = driver.switch_to.alert

print(f'Alert: {alert}')
```

### Relevant log output

```shell
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=99.0.4844.84)
```

### Operating System

Windows 10

### Selenium version

Python 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.84

**Comment by diemol** [comment]
Does the same happen in Firefox or Safari?

**Comment by titusfortner** [comment]
This is expected behavior.

The alert doesn't exist on browsing context of the parent window, but on the "child" window. Switch back to the other window and handle the alert (or better don't switch off of that window without first addressing the alert)

**Comment by justinearl** [comment]
I was automating some website that spawn a new window with alert when some action is done. It is easy to dismiss the alert if there is only one "child" window since we only need to switch to one window, but with multiple windows you would still need to check which window has an alert and `switch_to.alert` would hang the driver until it timeout if it was called in the wrong window

**Comment by titusfortner** [comment]
Ah, yes, this should raise an error immediately not hang. I can reproduce it.

**Comment by titusfortner** [comment]
I tried to see if varying the unhandled prompt behavior affects this and it doesn't seem so. Interestingly, when the window is spawned from the new window command we don't see this problem. Finally, though, this is working as expected on Firefox, which means that it is a chromedriver issue, and a ticket will need to be raised there.
