### ISSUE TITLE
[🐛 Bug]: Gecko driver triggers MutationObserver for unrelated events

### ISSUE THREAD

**Issue by rbri** [SeleniumHQ/selenium#10520]
### What happened?

Running the page below with real browsers (by clicking the button) produces only 'click' as output.

Running the same with Selenium produces 'attributes; styleattributes; styleattributes; styleattributes; styleclick' when using the gecko driver and FF.

### How can we reproduce the issue?

```shell
<html>
<body>
	<button id="testButton">Click me</button>
	<div id="logArea"></div>
	
	<script>
	const button = document.getElementById('testButton');
    const div = document.getElementById('logArea');
    button.addEventListener('click', e => {
		div.innerHTML += "click ";    });
		const targetNode = document.getElementById('testButton');
		const config = { attributes: true, childList: true, subtree: true };
		const callback = function(mutationsList, observer) {
			mutationsList.forEach(function(mutation) {
				div.innerHTML += mutation.type + "; ";
				div.innerHTML += mutation.attributeName;
			});
		document.count++;
	};
	
	const observer = new MutationObserver(callback);
	observer.observe(targetNode, config);
	</script>
</body></html>
```

### Relevant log output

```shell
none
```

### Operating System

Windows 10

### Selenium version

Java 1.8 / Selenium 4.1.3 / GeckoDriver 0.30.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 98

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
I went through the comments from the linked issue and I see this works in ChromeDriver/Chrome. Therefore, I suggest to report this to the Mozilla folks.
