### ISSUE TITLE
[🚀 Feature]: Update bazel toolchains to 5.1.1 to support current Bazel release

### ISSUE THREAD

**Issue by FantasqueX** [SeleniumHQ/selenium#10525]
### Feature and motivation

I would like to make a package for selenium on ArchLinux. However, what stops me is selenium requires the version of Bazel is 4.2.1. I wonder whether it is possible to upgrade the version Bazel used by selenium just like this PR #8386

### Usage example

After the change, I can make a package on ArchLinux to help distribute selenium

**Comment by AutomatedTester** [comment]
It's on my todo. The last time I worked on this I was hitting issues with `rules_nodejs` not working as expected. 

What is it in bazel 5 that you need so I can make sure it works for you

**Comment by FantasqueX** [comment]
All I need is the ability to build selenium python wheel using the current release version of bazel in order to make a package. Looking forward to your work!

**Comment by diemol** [comment]
This has been already done, and instructions to build Selenium python for release can be seen here https://github.com/SeleniumHQ/selenium/wiki/Releasing-Selenium
