### ISSUE TITLE
[🐛 Bug]: "invalid cookie domain" thrown when on 500 server error page

### ISSUE THREAD

**Issue by idontusenumbers** [SeleniumHQ/selenium#10532]
### What happened?

Calling `webDriver.manage().addCookie(new Cookie("XDEBUG_SESSION", "IDEA"))` when the browser is showing a 500 error screen causes 'invalid cookie domain' exception. This exception is very confusing because the current URL reports the correct domain and the cookie has no domain specified.

Fixing the 500 error and re-running causes the cookie set to succeed.

Many servers will respond with a content body for a 500 error; but some may not. When no body is returned, the browser renders a generic 500 error screen. I suspect it is this generic error screen that is leading to the invalid cookie domain exception, however a missing content body for a response should not impact the cookie or at least cause a more reasonable exception message like "Cannot set cookie on browser-generated generic error screen for 500 response code"

### How can we reproduce the issue?

```shell
Using docker image `seleniarm/standalone-chromium:4.1.2-20220227`
```

### Relevant log output

```shell
org.openqa.selenium.InvalidCookieDomainException: invalid cookie domain
          (Session info: chrome=98.0.4758.102)
        Build info: version: '4.1.2', revision: '9a5a329c5a'
        System info: host: '8047a03e41c1', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '11.0.14.1'
        Driver info: org.openqa.selenium.remote.RemoteWebDriver
        Command: [193fd5e6405aec2cc413ddc777afe5c5, addCookie {cookie=XDEBUG_SESSION=IDEA; path=/}]
        Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 98.0.4758.102, chrome: {chromedriverVersion: 98.0.4758.102 (273bf7ac8c90..., userDataDir: /tmp/.org.chromium.Chromium...}, goog:chromeOptions: {debuggerAddress: localhost:45225}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.27.0.12:4444/sessi..., se:cdpVersion: 98.0.4758.102, se:vnc: ws://172.27.0.12:4444/sessi..., se:vncEnabled: true, se:vncLocalAddress: ws://172.27.0.12:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
        Session ID: 193fd5e6405aec2cc413ddc777afe5c5
          at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
          at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
          at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
          at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
          at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
          at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
          at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
          at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:763)
```

### Operating System

Linux

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 98.0.4758.102

### What are the browser driver(s) and version(s) where you see this issue?

98.0.4758.102

**Comment by titusfortner** [comment]
This isn't enough information to duplicate your issue.

Does it work with Firefox?

**Comment by idontusenumbers** [comment]
I have not tried Firefox; it would not be trivial for me to try in firefox.

Were you able to setup a server to return a 500 error without a body and still set a cookie successfully in Chrome?

Here's a screenshot of the browser when that `invalid cookie domain` exception is thrown: 
![image](https://user-images.githubusercontent.com/1175031/162589987-415c46ee-c318-4bea-a4f9-8a3128f5eb77.png)

**Comment by diemol** [comment]
You could either share a GitHub repository that enables us to run a server that returns 500 or you can try with Firefox. We are really short on people and do not have the time to build a server to do that, it might be easy, but we simply do not have the bandwidth. Thank you.

**Comment by titusfortner** [comment]
I seem to recall a bug report somewhere for not being able to set cookies when there isn't a tld. You're saying it works for that site when it's on a page that didn't return a 500 error?

**Comment by idontusenumbers** [comment]
Correct; it works fine when I fix the 500 error. The URL returned by the driver is the same in both the success case and the 500 error case, which is why that invalid cookie domain error is so misleading.

I suspect the browser is some how storing the origin of the rendered page, and for the error page that's not the same as the URL the error page belongs to.

**Comment by idontusenumbers** [comment]
Is there some preferred method for test cases? I feel like a proper test case would be a docker compose with a tiny service to return the 500 plus a server to run selenium tests plus selenium itself which sounds like a lot and mostly not the core of the problem; got a pointer to a solid regression test I can use as an example?

**Comment by titusfortner** [comment]
So, finding out what Firefox does would tell us a lot.

I actually think the page being returned is a "[cookie averse document object](https://html.spec.whatwg.org/#cookie-averse-document-object)," and the driver is doing the correct thing here. ([See step 5](https://w3c.github.io/webdriver/#add-cookie))

Either way, Selenium code is sending the correct things to the driver and the driver is what is returning the error, so if it is a bug, it's going to be a bug in chromedriver. Again, showing that it works in Firefox and doesn't in Chrome is the best way to get a Chrome bug prioritized.

**Comment by idontusenumbers** [comment]
@titusfortner thank you for your research and guidance. I reported to chromedriver https://bugs.chromium.org/p/chromedriver/issues/detail?id=4089
