### ISSUE TITLE
[🐛 Bug]: ElementNotVisibleException class is not found in selenium 4.1.3. Getting compilation issues saying ElementNotVisibleException not found

### ISSUE THREAD

**Issue by Tejareddy1** [SeleniumHQ/selenium#10538]
### What happened?

I am trying to upgrade my framework with the latest selenium 4.1.3 in my project and when I am trying to run the existing tests in my local by upgrading the framework with the latest selenium framework(4.1.3) then I am facing compilation issues for the older tests saying ElementNotVisibleException class is not found in selenium 4.1.3. Getting compilation issues saying ElementNotVisibleException not found. If it is deprecated, please let us know which appropriate exception to use.? if not why am I getting compilation issues.

### How can we reproduce the issue?

```shell
Try to use the latest selenium 4.1.3 version in the frameowork and try to run the tests by adding ElementNotVisibleException class in your code and then finally run the tests.
```

### Relevant log output

```shell
I am trying to upgrade my framework with the latest selenium 4.1.3 in my project and when I am trying to run the existing tests in my local by upgrading the framework with the latest selenium framework(4.1.3) then I am facing compilation issues for the older tests saying ElementNotVisibleException class is not found in selenium 4.1.3. Getting compilation issues saying ElementNotVisibleException not found. If it is deprecated, please let us know which appropriate exception to use.? if not why am I getting compilation issues.
```

### Operating System

macOS

### Selenium version

4.1.3

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome

**Comment by diemol** [comment]
Since Selenium 4 is more strict regarding W3C WebDriver, and W3C WebDriver has nothing to say about visibility at this point. If an element is not visible, the driver in W3C mode should return a `ElementNotInteractableException`

**Comment by Tejareddy1** [comment]
@diemol ,thanks for your quick reply
