### ISSUE TITLE
[🐛 Bug]:  [java-client] Getting HTTP Method for PATCH request return GET

### ISSUE THREAD

**Issue by argotri** [SeleniumHQ/selenium#10539]
### What happened?

i'm trying to test https://reqres.in/ from UI to try  Network request feature from Selenium 4. 
but when i'm clicking on this link 
![image](https://user-images.githubusercontent.com/5022171/163054289-a0fb810b-ee61-4385-8479-f4f4e9fca57e.png)
my network interceptor detect GET instead of PATCH 
![image](https://user-images.githubusercontent.com/5022171/163054390-ccd1883d-5725-4386-a058-461687df8e0a.png)
this is the sample from the inspect network when i do click manualy
![image](https://user-images.githubusercontent.com/5022171/163055147-1c5fa8e7-7d71-447c-a7ca-8e369a34a4a2.png)

Thank you

### How can we reproduce the issue?

```shell
please clone from my repository on the branch Serenity
https://github.com/argotri/selenium4-framework-sample/tree/serenity

then run test file BugSeleniumIdentification.java on method test() , the console will be print httpMethod , Url , and StatusCode after automation click on PATCH request.
```

### Relevant log output

```shell
Current output : 
GET https://reqres.in/api/users/2 200

Expected Output : 
PATCH https://reqres.in/api/users/2 200
```

### Operating System

Windows 10

### Selenium version

Java 4.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100.0.4896.60

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
PR was merged.
