### ISSUE TITLE
[🐛 Bug]: Selenium 4.1.0 proxy in capability does not change to what was set

### ISSUE THREAD

**Issue by spdev01** [SeleniumHQ/selenium#10533]
### What happened?

When I followed the instruction as posted on [official selenium documentation]( https://www.selenium.dev/documentation/webdriver/capabilities/shared/#proxy ) on how to configure webdriver to utilize proxy in python by using DesiredCapabilities, the session that was connected to the target URL showed that it was connected from my IP address instead of the proxy ip address that I set up. Furthermore, when I checked driver.desired_capabilities it shows that it is using localhost ip address instead of the proxy address as if the setup that was done prior had no effect at all (The result from ip checking website shows my ip addres instead).
This behavior, however does not appear and it works fine when I followed the [instruction on C#](https://www.selenium.dev/documentation/webdriver/capabilities/shared/#proxy) as every worked correctly.

### How can we reproduce the issue?

```shell
from seleniumwire import webdriver
import time

proxy_ip = "xx.xx.xx.xx"
proxy_port = xxxx

PROXY_STR = "{}:{}".format(proxy_ip,proxy_port)

webdriver.DesiredCapabilities.FIREFOX['proxy'] = {
"httpProxy": PROXY_STR,
"ftpProxy": PROXY_STR,
"sslProxy": PROXY_STR,
"proxyType": "MANUAL",

}

with webdriver.Firefox(executable_path='./firefox_drivers/geckodriver.exe') as driver:
    driver.get("https://ipinfo.io")
    print(driver.desired_capabilities['proxy'])
    time.sleep(400)
```

### Relevant log output

```shell
1649525375697	geckodriver	INFO	Listening on 127.0.0.1:61488
1649525378751	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "61489" "-no-remote" "-profile" "C:\\Users\\schwi\\AppData\\Local\\Temp\\rust_mozprofilexrv1d6"
1649525378995	Marionette	INFO	Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\schwi\\AppData\\Local\\Temp\\rust_mozprofilexrv1d6\\search.json.mozlz4", (void 0)))
DevTools listening on ws://localhost:61489/devtools/browser/0424e4a1-96ec-44a0-9b04-964687713111
1649525380625	Marionette	INFO	Listening on port 61495
1649525380799	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
1649525380801	RemoteAgent	INFO	Proxy settings initialised: {"proxyType":"manual","httpProxy":"127.0.0.1:61486","sslProxy":"127.0.0.1:61486"}
```

### Operating System

Windows10

### Selenium version

Python 3.9.2, Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 99.0

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by symonk** [comment]
@spdev01 your example is using a `seleniumwire` library that I am not really familiar with; does the same happen here when using only `selenium`? if so please let me know and I will look into it.  Also `ftpProxy` is likely no longer supported; we should update our firefox docs regardless

**Comment by spdev01** [comment]
My god what have I done. I was messing around with both selenium and seleniumwire and did not realize that I forgot to switch it back. Thank you so much @symonk , this is now solved

**Comment by symonk** [comment]
no problem; please feel free to close this issue if it's no longer a problem
