### ISSUE TITLE
[🚀 Feature]: 

### ISSUE THREAD

**Issue by AradhanaJamwal** [SeleniumHQ/selenium#10546]
### Feature and motivation

As per the [Microsoft Blog](https://blogs.windows.com/msedgedev/2022/02/01/test-ie-mode-in-microsoft-edge-internet-explorer-driver/), IE driver 4.0.0 or later binding is needed for automating the application in IE compatibility mode in Edge.

After June 15 once IE will get sunset, would it be feasible to automate the application supporting "IE compatibility mode" using IE driver ? 

### Usage example

Since starting June 15, 2022, Internet Explorer 11 will no longer be supported so need a solution where we can use selenium to test the  legacy applications in Internet Explorer (IE) mode in Microsoft Edge.

Need a robust solution which will support the automation of the application supported in IE mode in MS Edge.
As current solution provided is using IE driver and once the IE will get sunset how the driver will work to support the IE mode?

**Comment by diemol** [comment]
This is already possible https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp

**Comment by AradhanaJamwal** [comment]
As per the above resolution, we need to use IE driver for automating IE mode compatible application.
 
What after June 15, when there will be no IE on our system, will the same solution will be effective to automate IE mode supported application? How IE driver will work when there won't be Internet Explorer?

**Comment by diemol** [comment]
>As per the above resolution, we need to use IE driver for automating IE mode compatible application.

Yes

>What after June 15, when there will be no IE on our system, will the same solution will be effective to automate IE mode supported application? How IE driver will work when there won't be Internet Explorer?

The Microsoft Edge team folks have been extremely kind and have made changes to the IE Driver so it can work with Edge in IE Mode. So, it should continue to work. Please check the docs I linked above and report specific errors to https://github.com/MicrosoftEdge/EdgeWebDriver
