### ISSUE TITLE
[🐛 Bug]: unable to connect to node to hub when using sdf port forwarding via haproxy server

### ISSUE THREAD

**Issue by shettypriy** [SeleniumHQ/selenium#10559]
### What happened?

I have installed selenium version 4 hub on a debian 11 machine which is running fine and a node is installed on another debian 11 machine. Node joins the hub when using the public IP address of the hub as shown in the below command and everything is working fine

java -jar selenium-server-4.1.2.jar node --hub http://public_ipaddress:4444 --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"us}'

We  have made a second setup wherein the hub is behind a haproxy service and local port forwarding is used and following is the command used to start the node

java -jar selenium-server-4.1.2.jar node --hub http://127.0.0.1:35577/wd/hub --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"us"}'

Here port forwarding is used on the selenium node, where the port number 35577 is sending the request to haproxy server on bind port 35555 and then it will be  forwarded to the backend selenium hub server public_ipaddress:4444. However, the node is not connecting to the hub when using the above command and it says 

15:40:55.925 INFO [NodeServer$1.start] - Starting registration process for node id 95e7aa7d-d8fa-4ef2-b800-7a915562e6e4
15:40:55.926 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://public_IP_address_of_node:5555
15:40:55.937 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:05.949 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:15.963 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:25.974 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:35.985 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:45.996 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:56.003 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:06.011 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:16.025 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:26.033 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:36.041 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:46.047 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:55.932 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

### How can we reproduce the issue?

```shell
java -jar selenium-server-4.1.2.jar node --hub http://127.0.0.1:35577/wd/hub --detect-drivers false --log-level "fine" --port 5555 --override-max-sessions true --max-sessions 74 --max-threads 55 --driver-configuration display-name="$(hostname)" max-sessions=74  stereotype='{"browserName":"chrome","cluster:pcgeo":"us"}'
```

### Relevant log output

```shell
15:40:55.925 INFO [NodeServer$1.start] - Starting registration process for node id 95e7aa7d-d8fa-4ef2-b800-7a915562e6e4
15:40:55.926 INFO [NodeServer.execute] - Started Selenium node 4.1.2 (revision 9a5a329c5a): http://public_IP_address_of_node:5555
15:40:55.937 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:05.949 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:15.963 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:25.974 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:35.985 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:45.996 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:41:56.003 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:06.011 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:16.025 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:26.033 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:36.041 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:46.047 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
15:42:55.932 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

debian 11

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

chrome browser and  version 99

### What are the browser driver(s) and version(s) where you see this issue?

chromdriver 99

### Are you using Selenium Grid?

yes

**Comment by diemol** [comment]
The Node registers to the Hub using the EventBus (which lives also in the Hub but listens to different ports). When you avoid the HAProxy, those ports (4442 for publish, 4443 for subscribe) are open. But when you add the HAProxy in front and only allow the 4444 port then you are blocking the other 2, which is why the event is sent but probably never reaches the EventBus.

Check how to allow those ports (4442, 4443) in HAProxy, and then tell the Node where to send the events with `--publish-events tcp://<hubMachineIp>:<portReplacementFor4442>` and `--subscribe-events tcp://<hubMachineIp>:<portReplacementFor4443>`

**Comment by shettypriy** [comment]
thank you @diemol. This solves my issue
