### ISSUE TITLE
[🐛 Bug]: Selenium Click Action not working after upgrading chrome version to 100.

### ISSUE THREAD

**Issue by ssd9881** [SeleniumHQ/selenium#10554]
### What happened?

When trying to click on the Web Element using Selenium's Actions class there is no exception thrown but the element is not getting clicked.
This test case was working before upgrading to chrome version 100.
Below is the implementation for the click action:

((JavascriptExecutor)driver).executeScript("arguments[0].scrollIntoView(true);", 1)
Actions acts = new Actions(driver);
acts.click(query);
Action action = acts.build();
action.perform();

After trying to scroll to the object to bring it in viewport, a few cases working but remaining not.
I am not able to figure out why they are failing, because there are no pattern. Changing implementation is not possible as it will have huge implications in maintaining. So we have to make it work only through this code.

### How can we reproduce the issue?

```shell
NA
```

### Relevant log output

```shell
The action is passing as no exception is thrown but in reality it doesn't click the web object.
```

### Operating System

Windows 10

### Selenium version

Java 8 selenium 3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 100.0.4896.75

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver  100.0.4896.60

**Comment by titusfortner** [comment]
If it was working in v99 but broken in v100 then it is very likely a chromedriver issue and not something for the Selenium project to fix. We also recommend updating to Selenium 4 since we don't still support Selenium 3.
