### ISSUE TITLE
[🐛 Bug]: Selenium 4.1.3 org.openqa.selenium.devtools.DevToolsException: Unable to create DevTools connection. When running on Selenoid.

### ISSUE THREAD

**Issue by sachinhr10** [SeleniumHQ/selenium#10565]
### What happened?

org.openqa.selenium.devtools.DevToolsException: Unable to create DevTools connection
is the error message.
Stack trace: 
Driver info: DevTools Connection
20:35:31 	at org.openqa.selenium.devtools.HasDevTools.lambda$getDevTools$0(HasDevTools.java:25)
20:35:31 	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
20:35:31 	at org.openqa.selenium.devtools.HasDevTools.getDevTools(HasDevTools.java:25)
20:35:31 	at org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$WfZIZ2kE.getDevTools(Unknown Source)
20:35:31 	at com.logmein.piranha.webdriver.selenoidtests.SelenoidGridTest.testSelenoidChrome(SelenoidGridTest.java:38)

We're facing this issue when trying to create a session on Selenoid setup on a remote machine, whereas on local machine it works.

### How can we reproduce the issue?

```shell
Facing this when running on Selenoid. 
driver = new RemoteWebDriver(
					URI.create("http://selenoid-ip:4444/wd/hub").toURL(),
					capabilities
					);
WebDriver webDriver = driver.webDriver();
        webDriver = new Augmenter().augment(webDriver);
        DevTools devTools =  ((HasDevTools) webDriver).getDevTools();
        devTools.createSession();
```

### Relevant log output

```shell
20:35:31 org.openqa.selenium.devtools.DevToolsException: Unable to create DevTools connection
20:35:31 Build info: version: '4.1.3', revision: '7b1ebf28ef'
20:35:31 System info: host: '', ip: '', os.name: 'Linux', os.arch: 'amd64', os.version: '', java.version: '13'
20:35:31 Driver info: DevTools Connection
20:35:31 	at org.openqa.selenium.devtools.HasDevTools.lambda$getDevTools$0(HasDevTools.java:25)
20:35:31 	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
20:35:31 	at org.openqa.selenium.devtools.HasDevTools.getDevTools(HasDevTools.java:25)
20:35:31 	at org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$WfZIZ2kE.getDevTools(Unknown Source)
20:35:31 	at com.logmein.piranha.webdriver.selenoidtests.SelenoidGridTest.testSelenoidChrome(SelenoidGridTest.java:38)
```

### Operating System

macOSBigsur, Linux

### Selenium version

Java Selenium 4.1.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100

**Comment by diemol** [comment]
Please report the issue to the Selenoid project.
