### ISSUE TITLE
[🐛 Bug]: Intercepting network response produces exception

### ISSUE THREAD

**Issue by dokisha** [SeleniumHQ/selenium#10574]
### What happened?

Intercepting network response crashes the browser. 

@titusfortner [said](https://stackoverflow.com/a/71975826/2620206): 
the code is assuming responseHeaders will be there, but that's optional according to [chromedevtools.github.io/devtools-protocol/tot/Fetch](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/)

### How can we reproduce the issue?

```shell
#issue is reproduced by typing `irb` and pasting the code below

require "watir"
require "selenium/devtools"

Selenium::WebDriver::Chrome::Service.driver_path = '/chromedriver99.0.4844.51'
Selenium::WebDriver::Chrome.path = '/chrome99.0.4844.84/google-chrome'
options = Selenium::WebDriver::Chrome::Options.new
options.add_option("args", ["--no-sandbox"])

browser = Watir::Browser.new :chrome, options: options

log_file = File.open("/tmp/network.log", 'w')
browser.wd.intercept do |request, &continue|
    continue.call(request) do |response|
      log_file << "#{request.id} \t
                   #{request.method} \t
                   #{response.code} \t
                   #{request.url} \n"
    end
end

browser.goto "youtube.com" #this crashes the browser
```

### Relevant log output

```shell
#<Thread:0x00005590f1bcda90@/selenium-webdriver-4.1.0/lib/selenium/webdriver/devtools.rb:145 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /selenium-webdriver-4.1.0/lib/selenium/webdriver/devtools.rb:155:in `block in callback_thread'
        2: from /selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver_extensions/has_network_interception.rb:68:in `block in intercept'
        1: from /selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver_extensions/has_network_interception.rb:109:in `intercept_response'
/selenium-webdriver-4.1.0/lib/selenium/webdriver/devtools/response.rb:38:in `from': undefined method `each_with_object' for nil:NilClass (NoMethodError)
```

### Operating System

Ubuntu

### Selenium version

ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

### What are the browser(s) and version(s) where you see this issue?

Chrome 99.0.4844.84

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver99.0.4844.51

### Are you using Selenium Grid?

No

**Comment by meetme2meat** [comment]
@titusfortner I'm facing the similar. If it works for you we can safeguard that (using a PR). replacing this 

> https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/devtools/response.rb#L38
```
params.fetch('responseHeaders', []).each_with_ob...
```

**Comment by titusfortner** [comment]
PRs very appreciated, ideally with a spec. Do we know when the response header won't be present?
