### ISSUE TITLE
chromedriver not changing [🐛 Bug]: 

### ISSUE THREAD

**Issue by chiboreache** [SeleniumHQ/selenium#10570]
### What happened?

trying run **headless vivaldi** with my profile - not working

trying run **chromium** with my profile - not working

only default one **chromedriver** works with some non-.config profile

### How can we reproduce the issue?

`driver = webdriver.Chrome(service=Service('/usr/bin/vivaldi-stable'), options=options)`

it's just open new blank vivaldi window and do nothing!

`options.binary_location = '/usr/bin/vivaldi-stable'`

**USELESS..**

`options.add_argument('--user-data-dir=/home/chibo/.config/chromium/Default')`
`options.add_argument('user-data-dir=/home/chibo/.config/chromium/Default')`

**DON'T CARE AT ALL**

### Relevant log output

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service


options = Options()

options.binary_location = '/usr/bin/vivaldi-stable'


options.add_argument('disable-infobars')
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-gpu')
options.add_argument('--user-data-dir=/home/chibo/.config/chromium/Default')


driver = webdriver.Chrome(
    service=Service('/usr/bin/vivaldi-stable'),
    options=options
)

URL = 'https://www.youtube.com'

driver.get(URL)
driver.set_window_size(800, 1200)
driver.save_screenshot("screenshot.png")

driver.quit()

print('#DONE')
```

### Operating System

Arch Linux 5.17.3-arch1-1

### Selenium version

python-selenium 4.1.0-2

### What are the browser(s) and version(s) where you see this issue?

vivaldi 5.2.2623.39-1

### What are the browser driver(s) and version(s) where you see this issue?

Chrome/100.0.4896.133

### Python?

Python 3.10.4

**Comment by diemol** [comment]
To set a profile, check the instructions from the [ChromeDriver site](https://chromedriver.chromium.org/capabilities#h.p_ID_64). Also, the path of the [service should](https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/#python-1) be the path of the browser driver, ChromeDriver in this case. However, since ChromeDriver won't drive Chrome but Vivaldi, it is not guaranteed all features will work the same.

Please try changing that setting for the service path and try again.

**Comment by chiboreache** [comment]
found some solution, which is not working `~_~`

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("start-maximized")
options.binary_location=r'C:\Users\levir\AppData\Local\Vivaldi\Application\vivaldi.exe'
driver = webdriver.Chrome(executable_path=r'C:\path\to\chromedriver.exe', options=options)
driver.get('http://google.com/')
```
https://localcoder.org/how-to-initiate-a-chromium-based-vivaldi-browser-session-using-selenium-and-pyth

none of the three...
___

but i found something interesting in my package manager - there is no conflict when i trying to install vivaldi

does this mean that vivaldi doesn't have chromedriver at all ?

![2022-04-22x00:48:31](https://user-images.githubusercontent.com/16459251/164558460-419d70ad-532e-4dd6-b446-ae46d23e1941.jpg)

but why it's opens blank window instead....

**Comment by chiboreache** [comment]
after compiling vivaldi from aur (not pacman) it's worked `options.binary_location = '/usr/bin/vivaldi-snapshot'`

but profile is still default one

**Comment by chiboreache** [comment]
# 😰 😱 😓

```python
# ! not working
options.add_argument('--user-data-dir=/home/chibo/.config/vivaldi-snapshot/Default')
options.add_argument('--profile-directory=Person 1')

# ? working
options.add_argument('--user-data-dir=/home/chibo/.config/vivaldi-snapshot')
options.add_argument('--profile-directory=Default')
```
