### ISSUE TITLE
[🐛 Bug]: Missing ByAll from Selenium3 in Selenium4

### ISSUE THREAD

**Issue by TFTomSun** [SeleniumHQ/selenium#10572]
### What happened?

Selenium 3 (C#) had a ByAll class which made it possible to search by multiple criteria. I tried to find something similar in Selenium 4 without success. I couldn't also find any hint that ByAll got removed during the Selenium 3 to 4 version change.
 
The upgrade guide https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/ doesn't mention that breaking change at all.

### How can we reproduce the issue?

```shell
Reference Selenium 3 -> ByAll class is there
Reference Selenium 4 -> no ByAll class exists
```

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ByAll' could not be found (are you missing a using directive or an assembly reference?)	Siemens.Collaboration.Net.Web.Automation	D:\Git\siemens\apis.webautomation\src\Siemens.Collaboration.Net.Web.Automation\_global\SeleniumExtensions.cs	1453	N/A
```

### Operating System

Windows 10

### Selenium version

CSharp latest 

### What are the browser(s) and version(s) where you see this issue?

Chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

ChromDriver latest

**Comment by titusfortner** [comment]
The entire PageFactory was marked Obsolete in Selenium 3.11
http://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html

The code should be available in `DotNetSeleniumExtras` if you need to continue using it.
