### ISSUE TITLE
[🐛 Bug]: Webdriver.firefox API documentation incomplete

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#10571]
### What happened?

The Webdriver.firefox API documentation (https://www.selenium.dev/selenium/docs/api/py/api.html#webdriver-firefox) is incomplete, in that it doesn't mention `selenium.webdriver.firefox.remote_connection` or `selenium.webdriver.firefox.service`.

### How can we reproduce the issue?

Visit https://www.selenium.dev/selenium/docs/api/py/api.html#webdriver-firefox and note the following links:
- selenium.webdriver.firefox.extension_connection
- selenium.webdriver.firefox.firefox_binary
- selenium.webdriver.firefox.options
- selenium.webdriver.firefox.firefox_profile
- selenium.webdriver.firefox.webdriver

However, viewing the source code (https://github.com/SeleniumHQ/selenium/tree/trunk/py/selenium/webdriver/firefox) shows the missing items:
- remote_connection
- service

### Relevant log output

```shell
n/a
```

### Operating System

Kubuntu

### Selenium version

Python 4.1.3

### What are the browser(s) and version(s) where you see this issue?

LibreWolf 99.0.1

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.31.0

**Comment by ghost** [comment]
I believe this is the place where the documentation needs updating: https://github.com/SeleniumHQ/selenium/tree/trunk/py/docs/source/webdriver_firefox

**Comment by titusfortner** [comment]
@BWPanda thanks for pointing this out. Python requests for fixes have been outstripping our resources recently. Would you mind making a PR with the fixes? It would be very helpful. Thanks.

**Comment by SinghHrmn** [comment]
@BWPanda The Python API docs have been updated thanks!
https://www.selenium.dev/selenium/docs/api/py/api.html
