### ISSUE TITLE
Firefox -38 working very slow with Selenium Webdriver v 2.47.. Please help

### ISSUE THREAD

**Issue by NehaDua** [SeleniumHQ/selenium#1057]
My FF 31 upgraded to FF 38 , so I updated Selenium webdriver to 2.47 to make it compatible with FF 38 .
But its performance is very slow , it increases testing time by 100%,please tell me any work around or fix it .
Thanks,
Neha Dua

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by NehaDua** [comment]
Hi This is issue for me ... providing you the detailed code here :

FF -38.2.1
Webdriver-v2.47
Code:
          		caps = DesiredCapabilities.firefox();
          		caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
          		caps.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, org.openqa.selenium.UnexpectedAlertBehaviour.IGNORE); 
          		objWebDriver = new FirefoxDriver(caps);
          	objWebDriver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
          	objWebDriver.get(URL);



Result:


It is opening URL fine but it is taking a long time to open the URL and perform further action on it .
after I upgrade Driver from 2.39 to 2.47 because of FF upgradation to 38.

Please let me know in case any other information is required.

Thanks,
Neha Dua

**Comment by barancev** [comment]
What's the URL? What operations' performance is degraded? Please provide your measurements.

**Comment by NehaDua** [comment]
URL :https://l4dridap1273:8446/web/earth/login

Currently opening this URL taking Long time as compare to before , i have also tested with Public URL "https://www.google.com/" and got same the results

**Comment by barancev** [comment]
I've done a benchmark of these two Selenium versions against a sample static page deployed to the local HTTP server. Here is the sample:
```
    DesiredCapabilities caps = DesiredCapabilities.firefox();
    caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
    FirefoxDriver driver = new FirefoxDriver(caps);
    try {
      long start = System.currentTimeMillis();
      for (int i = 1; i < 1000; i++) {
        driver.get("https://localhost/applications.html");
      }
      long end = System.currentTimeMillis();
      System.out.println("" + (end - start));
      
    } catch (Throwable e) {
        e.printStackTrace();
    } finally {
        if (driver != null) {
            driver.quit();
        }
    }
```

Here are the results:

Selenium 2.47 + FF40: 96715, 92480, 92924
Selenium 2.47 + FF31: 93270, 99167, 93622
Selenium 2.39 + FF31: 95225, 99240, 98208

So the performance is roughly the same.

**Comment by NehaDua** [comment]
Hi Alexei,


I have tested the code with even less count (100) on my System (Windows 7)
, results are quite different.

 DesiredCapabilities caps = DesiredCapabilities.firefox();
    caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
    FirefoxDriver driver = new FirefoxDriver(caps);
    try {
      long start = System.currentTimeMillis();
      for (int i = 1; i < 100; i++) {
        driver.get("https://localhost/applications.html");
      }
      long end = System.currentTimeMillis();
      System.out.println("" + (end - start));

    } catch (Throwable e) {
        e.printStackTrace();
    } finally {
        if (driver != null) {
            driver.quit();
        }
    }


Here are the results:

Selenium 2.47 + FF38.2.1: 426328
Selenium 2.46 + FF38.2.1 : 435489


Can you please test with FF 38 .


Thanks,

Neha Dua

**Comment by barancev** [comment]
Selenium 2.47 + FF38.2.1: 95269

**Comment by NehaDua** [comment]
How come it is taking much time on my system(Windows 7 ) ,  is it possible that it may due to add-on installed on FF( Firebug,firepath,Selenium builder)it is taking longer time ?

If you can share any other reason which make it taking long time then please share

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
