### ISSUE TITLE
[🐛 Bug]: Selenium NuGet package not updated with newer CDP bindings

### ISSUE THREAD

**Issue by jeffreyrivor** [SeleniumHQ/selenium#10583]
### What happened?

The Selenium.WebDriver 4.1.0 NuGet package is several major releases behind the stable Chrome DevTools Protocol, so it does not work with latest stable of Chrome (v100.x as of this writing). The latest version in 4.1.0 release is v96 which is no longer works against v100. The .NET bindings are clearly being kept updated as the CDP is versioned (see <https://github.com/SeleniumHQ/selenium/commits/trunk/dotnet/src/webdriver/DevTools>) but no NuGet package releases have been made.

It seems to me that there should be a new 4.x.x release of the Selenium.WebDriver NuGet package based on the latest trunk.

### How can we reproduce the issue?

```shell
- Create .NET 5.0 test project using dotnet new
- Install latest Chrome (v100.x)
- Add Selenium.WebDriver 4.1.0 and Selenium.WebDriver.ChromeDriver 100.x matching Chrome version

In a test, attempt to create a DevTools session to use something available in the latest available DevTools version in the 4.1.0 package.


using OpenQA.Selenium.DevTools.V96.Fetch; // no newer NuGet package version to use V100.Fetch

var driver = new ChromeDriver();
var fetchAdapater = new FetchAdapater(driver.GetDevToolsSession());
```
```


### Relevant log output

```shell
Error: OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session. ---> System.NullReferenceException: Object reference not set to an instance of an object..
  Stack Trace:
      at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session, Int32 versionRange)
   at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session)
   at OpenQA.Selenium.DevTools.DevToolsSession.StartSession(Int32 requestedProtocolVersion)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(Int32 devToolsProtocolVersion)
--- End of inner exception stack trace ---
```

### Operating System

Windows Server 2022

### Selenium version

.NET 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 101.0.4951.15

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.15

**Comment by diemol** [comment]
4.1.1 was released earlier today which supports recent CDP versions.
