### ISSUE TITLE
Selenium inside Docker TLS Handshake Error[🐛 Bug]: 

### ISSUE THREAD

**Issue by thlorenzen** [SeleniumHQ/selenium#10588]
### What happened?

When trying to reach ea.com from inside Docker Container with selenium. I get an webpage with following Error:
`502 Bad Gateway
TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')`

It happended since I update chromedriver and google-chrome and it only happens inside Docker-Container.

Im not sure if its correct to post it here, but im stuck since 2 days with this errror.

### How can we reproduce the issue?

```shell
print("not local init...")
# chrome_options.add_argument('--headless')
chrome_options.add_argument("--window-size=1920x1080")
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--remote-debugging-port=9222")
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--ignore-ssl-errors')

driver = webdriver.Chrome(options=chrome_options)
```

### Relevant log output

```shell
502 Bad Gateway
TlsProtocolException('Cannot establish TLS with accounts.ea.com:443 (sni: accounts.ea.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'\', \'unsafe legacy renegotiation disabled\')])")')`
```

### Operating System

Ubuntu

### Selenium version

newest

### What are the browser(s) and version(s) where you see this issue?

101

### What are the browser driver(s) and version(s) where you see this issue?

chrome

**Comment by diemol** [comment]
This does seem like an issue either with the website or Chrome/ChromeDriver. You can try reporting it to the Chrome team or contacting the site directly.
