### ISSUE TITLE
[🐛 Bug]: IEDriver.WindowHandles does not return all handles

### ISSUE THREAD

**Issue by p-system** [SeleniumHQ/selenium#10599]
### What happened?

I updated Selenium to 4. I test legacy app that runs only on IE. Now IE will be closed down and I need to switch to MS Egde in capability mode. My tests during execution need to switch to new browser windows and uses function IWebDriver.WindowHandles to do it (code below).

COmparing to Selenium 3 I had to add new options for a driver to run test on Edge like this:

```
var options = new InternetExplorerOptions();
options.AttachToEdgeChrome = true;
options.EdgeExecutablePath = @"\msedge.exe";

```
Then I use code like this to switch between browser windows when user open new browser window in tested application:

```
public Context SwitchToNewIEWindow(string windowTitle, bool isEqual = true)
{
for (int i = 0; i < context.GetTimeout().Seconds; i++)
{
try
{
var ieWindowHandlers = context.GetDriver().WindowHandles;
foreach(var handler in ieWindowHandlers)
{
var window = context.GetDriver().SwitchTo().Window(handler);
bool condition = isEqual ? window.Title == windowTitle : window.Title.Contains(windowTitle);
if (condition)
{
context.SetDriver(window);
context.SetCurrentWindow(windowTitle);
return context;
}
}
}
catch (Exception)
{
context.Wait(1);
}
}
throw new Exception($"No window found with title: {windowTitle}");

    }

```
In Selenium 3 everything works fine and WindowHandles function returns 2 handles. In Selenium 4 and IEDriver in Edge mode this function returns only 1 handle of main browser window. In my case waiting a few seconds ( as it is recommended in guidelines) does not change anything. Even after a minute I still get only handle of first window. Any suggestions how to make it work properly again in Selenium 4.

I am aware of issue #8868 but this one was closed. In my opinion the error still exists and should be fixed somehow.

### How can we reproduce the issue?

```shell
public Context SwitchToNewIEWindow(string windowTitle, bool isEqual = true)
{
for (int i = 0; i < context.GetTimeout().Seconds; i++)
{
try
{
var ieWindowHandlers = context.GetDriver().WindowHandles;
foreach(var handler in ieWindowHandlers)
{
var window = context.GetDriver().SwitchTo().Window(handler);
bool condition = isEqual ? window.Title == windowTitle : window.Title.Contains(windowTitle);
if (condition)
{
context.SetDriver(window);
context.SetCurrentWindow(windowTitle);
return context;
}
}
}
catch (Exception)
{
context.Wait(1);
}
}
throw new Exception($"No window found with title: {windowTitle}");

    }
```

### Relevant log output

```shell
var ieWindowHandlers = context.GetDriver().WindowHandles; return 1 handle of first browser window and ignore any other browser window that is open within application.
```
I have also tried to use NewWindow function to open new window within my test but unfortunately this function open IE browser instead of new Edge window whitch I think is another error : 

context.GetDriver().SwitchTo().NewWindow(WindowType.Window);

### Operating System

Windows 10

### Selenium version

Selenium.WebDriver 4.1,1

### What are the browser(s) and version(s) where you see this issue?

Wersja 101.0.1210.32 - 64bit

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver.IEDriver 4.0.0.1

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
@p-system #8868 was closed because it needs to be reported to the right team, which is what I [commented](https://github.com/SeleniumHQ/selenium/issues/8868#issuecomment-1104839846).

Perhaps you can help by reporting that? Thanks!

**Comment by p-system** [comment]
I do not understand why you keep saying that it requires fixes in MSEdgeDriver. 
Testing Legacy Application is done by using IEDriver in Edge mode  (not MSEdgeDriver) with specific options (
options.AttachToEdgeChrome = true; 
options.EdgeExecutablePath = @"\msedge.exe";
)?
So why this bug is closed if it should be fixed (for a second time regarding https://github.com/SeleniumHQ/selenium/issues/8868)?

**Comment by diemol** [comment]
Because the MDEdge team were kind enough to implement the changes in IEDriver.

**Comment by p-system** [comment]
Thanks a lot for explanation.
