### ISSUE TITLE
In IE browser, getting an error message saying "Error communicating with the remote browser. It may have died". 

### ISSUE THREAD

**Issue by devendarreddy** [SeleniumHQ/selenium#1059]
I have to verify the table of results and my code is implemented as shown below

List<WebElement> results = webDriver.findElements(By.cssSelector("* /deep/ #sortTable > tbody > tr"));		
		
		for (WebElement ele : results) {
			System.out
					.print("++++++++++++++++++++++++ PRINT THE ELEMENTS++++++++++++++ "
							+ ele.getText());
			if ((ele.getText().contains(searchValue))
					| (ele.getText().equals(searchValue))) {
				counter += 1;
			}
		}

		if (counter >= 1) {
			return true;
		} else {
			return false;
		}

HTML: 

<table id="sortTable" class="data-listing"><thead><tr class="row table__head"><th class="col table-head">Primary ID <i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></th><th class="col table-head">Scanned Date &amp; Time <i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></th><th class="col table-head">Terminal Serial # <i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></th><th class="col table-head">Unique Modifier <i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></th><th class="col table-head">IP Address <i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></th></tr></thead><tbody><tr ng-repeat="iData in invData.tableData | orderBy:iData[0]" class="row ng-scope"><td class="col"><a href="#" style="color:blue !important"><strong class="ng-binding">ATM001</strong></a><p class="h6 ng-binding ng-scope ng-hide" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">ATM001</p><p class="h6 ng-binding ng-scope" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">DELL   - 1072009</p><p class="h6 ng-binding ng-scope ng-hide" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">0</p></td><td class="col ng-binding"></td><td class="col ng-binding"></td><td class="col ng-binding"></td><td class="col ng-binding"></td></tr><tr ng-repeat="iData in invData.tableData | orderBy:iData[0]" class="row ng-scope"><td class="col"><a href="#" style="color:blue !important"><strong class="ng-binding">ATM002</strong></a><p class="h6 ng-binding ng-scope ng-hide" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">ATM002</p><p class="h6 ng-binding ng-scope" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">DELL   - 1072009</p><p class="h6 ng-binding ng-scope ng-hide" ng-repeat="data in iData track by $index" ng-show="$index > 0 &amp;&amp; $index < iData.length-1">0</p></td><td class="col ng-binding"></td><td class="col ng-binding"></td><td class="col ng-binding"></td><td class="col ng-binding"></td></tr></tbody></table>

Note: In our project, we are using shadow DOM

**Comment by mach6** [comment]
We need more information. What selenium version and IE driver version? Also, is this still an issue on the newer versions? Please reply back and we can re-open this issue if needed.
