### ISSUE TITLE
[🐛 Bug]: Unexpected free port is appended to the argument list when '--connect-existing' is used

### ISSUE THREAD

**Issue by seizu** [SeleniumHQ/selenium#10598]
### What happened?

Unexpected free port is appended to the argument list when '--connect-existing' is used.
The driver unexpectedly quits with status code 64.

Error occurs in: 8b984a0 selenium/py/selenium/webdriver/firefox/service.py
Line 57

### How can we reproduce the issue?

```shell
from selenium import webdriver
browser = webdriver.Firefox('./',service_args=['--connect-existing','--marionette-port=2828'], log_path='./')
```
```


### Relevant log output

```shell
Geckodriver Log:

geckodriver: error: Found argument '53610' which wasn't expected, or isn't valid in this context

USAGE:
    geckodriver [OPTIONS]

For more information try --help
```

### Operating System

Win10x64

### Selenium version

4.1.3 (Python 3.x)

### What are the browser(s) and version(s) where you see this issue?

Firefox v99.0.1

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.31.0

**Comment by diemol** [comment]
Thank you for reporting this, we want to make a release soon, so this should be part of 4.1.4
