### ISSUE TITLE
[🐛 Bug]: 使用window_handles获取不到窗口句柄

### ISSUE THREAD

**Issue by Mo-rot** [SeleniumHQ/selenium#10595]
### What happened?

我的自动化脚本执行时，点击了一个会弹出新窗口的按钮，我尝试使用web.window_handles获取新窗口的句柄（新窗口已经正常打开），但是只获取到当前窗口的句柄，请问这是什么原因？

### How can we reproduce the issue?

```shell
def scan():
    while True:
        try:
            switch_to_frame(web, "fraMenu")
            web.find_element(by=By.XPATH, value="//a[@title='新扫描管理']").click()
            web.save_screenshot('./image.png')  # 截图
            web.find_element(by=By.XPATH, value="//a[@title='扫描']").send_keys(Keys.ENTER)
            switch_to_frame(web, "fraInterface")
            break
        except:
            pass

    web.switch_to.default_content()
    h1 = web.current_window_handle
    print("h1：", h1)
    for i in range(1000):
        h2 = web.window_handles
        print("h2：", h2)
        if len(h2)>1:
            break

scan()
```

### Relevant log output

```shell
h1： 9c2a633a-8808-4b2e-bc6a-378d3e440729
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
h2： ['9c2a633a-8808-4b2e-bc6a-378d3e440729']
```

### Operating System

Windows10

### Selenium version

Python 3.7.6

### What are the browser(s) and version(s) where you see this issue?

IE10

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_Win32_4.0.0

### Are you using Selenium Grid?

selenium 4.1.2

**Comment by diemol** [comment]
From Google Translate:
>When my automation script is executed, I click a button that will pop up a new window. I try to use web.window_handles to get the handle of the new window (the new window has been opened normally), but only the handle of the current window is obtained, what is the reason for this? ?

**Comment by diemol** [comment]
If it is not a question because it is a bug, then please fill all the required data so we can reproduce the issue.
