### ISSUE TITLE
[🐛 Bug]: Python Proxy configuration with Proxy network

### ISSUE THREAD

**Issue by lukehamil55** [SeleniumHQ/selenium#10605]
### What happened?

![proxy](https://user-images.githubusercontent.com/86263323/166492874-e19d376e-36a8-4993-946f-22d22a439a00.png)
I am using a proxy network and want to configure it with Selenium on Python. I have seen many resources use the HOST:PORT method of configuration, but proxy networks uses the "URL method" of http://USER:PASSWORD@PROXY:PORT.

See different types of configurations below:

### How can we reproduce the issue?

```shell
###Selenium_Options###
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument("--proxy-server=http://USER:PASSWORD@PROXY:PORT")
driver = webdriver.Chrome(options=options)
driver.get("https://some_url.com")



###Desired_Capabilities###
from selenium import webdriver
from selenium.webdriver.common.proxy import *

proxy_url = "http://USER:PASSWORD@PROXY:PORT"
proxy = Proxy({
    'proxyType': ProxyType.MANUAL,
    'httpProxy': proxy_url,
    'sslProxy': proxy_url,
    'noProxy': ''})

capabilities = webdriver.DesiredCapabilities.CHROME
proxy.add_to_capabilities(capabilities)

driver = webdriver.Chrome(desired_capabilities=capabilities)
driver.get("https://some_url.com")
```

### Relevant log output

Log does not throw any errors with the above configurations, all the errors on on a browser side:

Reference above attached image for Selenium_Options error. 

Desired Capabilities does not throw any browser errors, but the configuration still fails to add proxy.

*Proxy "URL" is in a working state and has been tested using the requests library.

FOR MORE INFORMATION: https://stackoverflow.com/questions/70806778/python-selenium-proxy-network

### Operating System

Windows 10

### Selenium version

Tried with: 3.141.0 and 4.0.0a7

### What are the browser(s) and version(s) where you see this issue?

Version 101.0.4951.41

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

### Are you using Selenium Grid?

NA

**Comment by diemol** [comment]
Please update to the most recent Python release (4.1.3 at the moment), there were some fixes related to Proxy usage in recent releases, and then report back. Thanks!

**Comment by lukehamil55** [comment]
@diemol I believe you mean the most recent Selenium release... not Python. Checking in on this!

**Comment by lukehamil55** [comment]
I updated Selenium to the most recent release:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/86263323/166700905-7d72b272-7f58-4d16-a113-a74b1956278f.png">
Then ran a test using both selenium options and desired capabilities (As shown originally). I received the same errors that I originally received.

**Comment by symonk** [comment]
@lukehamil55 could you debug the remote connection? I don't have any time available for a little while before I can get a chance to look into it

**Comment by lukehamil55** [comment]
@symonk what do you mean by debugging the remote connection? I haven't heard that term before.

**Comment by symonk** [comment]
sorry I meant just debugging the web driver running in your environment, in particular what happens as part of the webdrivers `RemoteConnection` regarding the proxy config

**Comment by lukehamil55** [comment]
@symonk Ran code in debug mode using both the Selenium Options configuration and the Desired Capabilities configuration. For the **Selenium options configuration** under my "options" variable I found some information that may be important:
<img width="712" alt="image" src="https://user-images.githubusercontent.com/86263323/166748117-6e106567-b2ad-4b21-a6d7-7b33b8342b68.png">
The initial loading of the args seemed to have went through (I tested it using my actual credentials, it's the same output):
<img width="720" alt="image" src="https://user-images.githubusercontent.com/86263323/166749421-bc7c37f9-0f2c-48c6-aae1-9aa551545520.png">

For **Desired Capabilities configuration**, the driver variable is loaded with the proxy parameter:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/86263323/166819331-b3a9767e-ba3c-44e4-9151-713ef205806d.png">

Is this enough debug information to assess the proxy issue?

**Comment by symonk** [comment]
Thanks @lukehamil55 I will get a look it shortly, could you share the exact reproducible code you are using (excluding any sensitive information of course) to make it as recreatable as possible

**Comment by lukehamil55** [comment]
Appreciate your help @symonk, the "How can we reproduce the issue?" section is the exact reproducible code other than the driver.get() command which fetches "https://whatismyipaddress.com/" so that I can check my IP. In order to recreate the same issue however, you will need a proxy network URL endpoint like I have demonstrated in my code (http://USER:PASSWORD@PROXY:PORT)

**Comment by symonk** [comment]
@lukehamil55 do you observe the same behaviour on `selenium==4.1.4` (now available for installation on pypi)

**Comment by lukehamil55** [comment]
@symonk Just did an upgrade to selenium 4.1.4, still receive the exact same errors

**Comment by lukehamil55** [comment]
@symonk For extra context, I ran the below code using urllib.request with the proxy endpoint configuration, and the IP is correctly applied and cycled:
```
import urllib.request
opener = urllib.request.build_opener(
    urllib.request.ProxyHandler(
        {'http': 'http://USER:PASSWORD@PROXY:PORT/',
        'https': 'http://USER:PASSWORD@PROXY:PORT/'}))
print(opener.open('http://lumtest.com/myip.json').read())
```
The website http://lumtest.com/myip.json can also be used to check one's personal IP. At this point, is it safe to rule out the validity of the proxy network endpoint, and that this problem solely lies with Selenium?

**Comment by C370228492** [comment]
version 4.1.5 , proxy still not work.

**Comment by C370228492** [comment]
I run the ###Desired_Capabilities### case,   where __version__ = "4.1.5" .  when proxy_url endwith char '/'  it don't work ;  when proxy_url not endwith char '/'  it work

**Comment by lukehamil55** [comment]
@C370228492 There is no ending char '/' for the desired capabilities case. I see the confusion as I did use an ending char '/' in my urllib.request example. I upgraded to version="4.1.5" and ran the desired capabilities with and without the ending char '/' . I found no difference in output.

**Comment by lukehamil55** [comment]
What else is needed to further troubleshoot? Test credentials?

**Comment by titusfortner** [comment]
[The spec](https://w3c.github.io/webdriver/#proxy) says just host and port, but that "The [host](https://w3c.github.io/webdriver/#dfn-host) may [include credentials](https://w3c.github.io/webdriver/#dfn-includes-credentials)" 
So it should look like this:
```
user:pass@localhost:8080
```

That being said, I know that Firefox does not support authentication with proxies (https://bugzilla.mozilla.org/show_bug.cgi?id=1395886), so it's possible that neither does Chromedriver, though I don't see an open ticket for it on their tracker.

Either way, this repo is sending along the right code to the right place, so if you can not get this to work, an issue will need to get filed with the chromedriver project.

**Comment by lukehamil55** [comment]
Opened an issue with the chromedriver project: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4118
Will update this thread when I reach a solution.

**Comment by lukehamil55** [comment]
@diemol @titusfortner @C370228492 @symonk 

I am happy to share that I have **finally figured it out!** I had to zip up a json file and js script that configured my proxy credentials, then **add that zip file as an extension** in Selenium.

Step by step guide can be found here: https://stackoverflow.com/questions/70806778/python-selenium-proxy-network/72564293#72564293
