### ISSUE TITLE
[🚀 Feature]: release selenium-devtools gem v101

### ISSUE THREAD

**Issue by annaswims** [SeleniumHQ/selenium#10602]
### Feature and motivation

Any chance you could release a new version of the selenium-devtools ruby gem?
This commit would fix my issues
https://github.com/SeleniumHQ/selenium/commit/4f1d7d7c6a115c0601a2882144637440f15e037c

### Usage example

gem release, please.

**Comment by diemol** [comment]
Just released it https://rubygems.org/gems/selenium-devtools/versions/0.101.0

**Comment by boris-petrov** [comment]
I see that version 0.101 requires Ruby 2.7+. This breaks JRuby users as JRuby is still stuck on Ruby 2.6. Is that change really necessary?

**Comment by titusfortner** [comment]
Yeah, I'm not sure what the Ruby community is supposed to do here to properly accommodate JRuby when it falls behind by more than 2 1/2 years. Ruby has an extremely reliable release cycle and support policy. Ruby 2.6 is not supported any more and shouldn't be used. We've updated to Ruby 2.7 syntax in Selenium.

https://twitter.com/titusfortner/status/1514331982062358531
The dev said a new JRuby will be released soon.

**Comment by boris-petrov** [comment]
That's great to hear! Thanks for the heads-up! :)
