### ISSUE TITLE
[🐛 Bug]: Unable to switchTo().Frame(iframe) on iframes inside a shadow dom

### ISSUE THREAD

**Issue by jmalmsten-panopto** [SeleniumHQ/selenium#10607]
### Description
Whenever I try to call Driver.switchTo().Frame(iframeElem) on an iframe inside of a shadow dom I get a NullReferenceException instead.

#### Context
We are testing how our product integrates when embedded into test LMS sites. This test was working until one LMS made an update wrapping embedded content in a shadow dom. We need to switch to the iframe to verify the content loaded correctly.

### Repro Steps
1. Put an iframe inside of a shadow dom
2. Attempt to retrieve the iframe in a test and switch to it

#### Expected: 
I can switch to the iframe and verify some of the content inside of it. 

#### Actual:
I got a System.NullReferenceException when trying to switch to the frame. When I debug the test the iframe element does not appear to be null when it is passed to Frame(iframe).

Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    **EventFiringTargetLocator.Frame(IWebElement frameElement)**
    LMSBase.SwitchToEmbedViewerFrame(Boolean isViewerNested) line 76
    LMSTestBase.OpenViewer(Boolean isViewerNested) line 282
    D2LTests.D2LVerifyEmbed() line 479

### Test Code
I have tried with Selenium 4's GetShadowRoot function:
```
public IWebElement GetShadowElement(IWebDriver driver, IWebElement shadowHost, string cssOfShadowElement)
{
    ISearchContext shadowRoot = shadowHost.GetShadowRoot();
    return shadowRoot.FindElement(By.CssSelector(cssOfShadowElement));
}

...

IWebElement embedViewerFrameElem = this.GetShadowElement(Driver, EmbedViewerShadowHost, "iframe[src*='panopto']");

Driver.SwitchTo().Frame(embedViewerFrameElem);
```

and with the following javascript execution:
```
var shadowHost = Driver.FindElement(By.CssSelector("d2l-html-block"));

js = (IJavaScriptExecutor)Driver;

var shadowRoot = (ISearchContext)js.ExecuteScript("return arguments[0].shadowRoot", shadowHost);
IWebElement embedViewerFrameElem = shadowRoot.FindElement(By.CssSelector("iframe[src*='panopto']"));

Driver.SwitchTo().Frame(embedViewerFrameElem);
```

### How can we reproduce the issue?

```shell
### Repro Steps
1. Put an iframe inside of a shadow dom
2. Attempt to retrieve the iframe in a test and switch to it

Test code snippets are above
```

### Relevant log output

```shell
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    EventFiringTargetLocator.Frame(IWebElement frameElement)
    LMSBase.SwitchToEmbedViewerFrame(Boolean isViewerNested) line 76
    LMSTestBase.OpenViewer(Boolean isViewerNested) line 282
    D2LTests.D2LVerifyEmbed() line 479
```

### Operating System

Windows 10

### Selenium version

C# 4.1.0

### What are the browser(s) and version(s) where you see this issue?

chrome 101.0.4951.41

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

**Comment by titusfortner** [comment]
Looks like Chrome does not recognize the element as being a frame. I think it is supposed to treat that element the same as one outside the shadow DOM, so it is probably a chromedriver bug. You can file a ticket, or better, write a test for it here: https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/switch_to_frame/switch_webelement.py
