### ISSUE TITLE
[🐛 Bug]: Actions Selenium Java mouse action drag and drop not working when cursor type changes after clickandhold

### ISSUE THREAD

**Issue by icodelongtime** [SeleniumHQ/selenium#10601]
### What happened?

Actions Selenium Java mouse action drag and drop not working when cursor type changes after clickandhold

### How can we reproduce the issue?

```shell
Actions Selenium Java mouse action drag and drop not working when cursor type changes after clickandhold

Use case: 
1. Mouse cursor type: Pointer
2. Move to source element.
3. click and hold with mouse cursor type: changing to a rectangle block.
4. Move to target element and release.


Start Code snippet:

import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;

builder.moveToElement(fromWebElement).clickAndHold().moveToElement(toWebElement).perform()
Thread.sleep(2000);
builder.moveToElement(toWebElement).release().build().perform();


or:
builder.moveToElement(fromWebElement).dragAndDrop(fromWebElement,toWebElement).clickAndHold().build().perform();

end Code snippet:


Above different code do not work fully.
The mouse pointer moves to the source element and clicks on draggable element as i notice the cursor type change to rectangle block to confirm click and hold. 
But action of moving to the target element with draggable element does happen. 
If i manually move the mouse the cursor type changes back to pointer and i see the pointer move to target element without the draggable element.
```

### Relevant log output

```shell
noen
```

### Operating System

Windows Server 2019

### Selenium version

Java 8

### What are the browser(s) and version(s) where you see this issue?

Chrome 100

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 100.0.4896.60

**Comment by icodelongtime** [comment]
cannot share application. Please check on any pubic application when mouse pointer icon to different image when draggable element is clicked and held. 
 code snippet.

builder.moveToElement(fromWebElement).clickAndHold().moveToElement(toWebElement).perform()
Thread.sleep(2000);
builder.moveToElement(toWebElement).release().build().perform();

**Comment by diemol** [comment]
>Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.

**Comment by titusfortner** [comment]
Drag and Drop is not working in the drivers right now, unfortunately.
https://github.com/w3c/webdriver/issues/1488
