### ISSUE TITLE
[🐛 Bug]: ignoreZoomSetting

### ISSUE THREAD

**Issue by lonelyGentleman** [SeleniumHQ/selenium#10614]
### What happened?

Unexpected error launching Internet Explorer. Browser zoom level was set to 125%. It should be set to 100%
ie options ignoreZoomSetting can not work

### How can we reproduce the issue?

```shell
async initDriver() {
        let ieOptions = new IE.Options()
        ieOptions.addArguments('--headless')
        ieOptions.addArguments('--disable-gpu')
        ieOptions.addArguments('--no-sandbox')
        ieOptions.addArguments('--start-maximized')
        ieOptions.addArguments('--disable-dev-shm-usage')
        ieOptions.addArguments('--incognito')
        ieOptions.addArguments('excludeSwitches', ['enable-automation'])
        ieOptions.ignoreZoomSetting(true)
        const driver = await new Builder().
            setIeOptions(ieOptions).
            forBrowser('internet explorer').build();
        this.driver = driver;
        context.set('driver', driver);

        return async () => {
            await this.driver.quit()
            process.exit(0)
        }
    }
```

### Relevant log output

```shell
Unexpected error launching Internet Explorer. Browser zoom level was set to 125%. It should be set to 100%
```

### Operating System

windows 10

### Selenium version

^4.0.0-alpha.7

### What are the browser(s) and version(s) where you see this issue?

IE 11

### What are the browser driver(s) and version(s) where you see this issue?

19044.1645

**Comment by diemol** [comment]
Seems you are mixing a lot of arguments valid only for Chrome/Edge. Please check the required setup for the IEDriver at https://www.selenium.dev/documentation/ie_driver_server/

In addition, IE is not going to be supported soon, please try the IE mode in Edge, check details at https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium

If after checking the setup and using IE mode in Edge things are not working, please provide a GitHub repo with a full setup so we can troubleshoot the issue, and then we can reopen the issue.
