### ISSUE TITLE
[🚀 Feature]: Does dotnet have any plans to add performance to LogType?

### ISSUE THREAD

**Issue by wqscode** [SeleniumHQ/selenium#10616]
### Feature and motivation

options. SetLoggingPreference("performance", OpenQA.Selenium.LogLevel.All);

### Usage example

 options.SetLoggingPreference("performance", OpenQA.Selenium.LogLevel.All);

 var GetLog = driver.Manage().Logs.GetLog("performance");

**Comment by wqscode** [comment]
> @15192095633，感谢您创建此问题。我们会尽快解决问题。
> 
> 维护者信息

Which version are you planning to fix?

**Comment by titusfortner** [comment]
Added d62a05ac10f21a4488bf051c51dcc956327b5abb
