### ISSUE TITLE
[🐛 Bug]: "Error: Invalid URL: http:/" with Node.js v18

### ISSUE THREAD

**Issue by slhck** [SeleniumHQ/selenium#10619]
### What happened?

Using selenium-webdriver with Node.js v18 is not possible, as an error is thrown.

```
Error: Invalid URL: http:/
    at getRequestOptions (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/index.js:51:11)
```

To reproduce, install Node.js v18 or higher (e.g. via `nvm install node`).

Given the following `package.json`:

```json
{
  "dependencies": {
    "selenium-webdriver": "^4.1.2"
  }
}
```

Run the sample code in `index.js` with `node index.js`:

```javascript
const { Builder, By, Key, until } = require("selenium-webdriver");
(async function example() {
  let driver = await new Builder().forBrowser("chrome").build();
  try {
    await driver.get("http://www.google.com/ncr");
    await driver.findElement(By.name("q")).sendKeys("webdriver", Key.RETURN);
    await driver.wait(until.titleIs("webdriver - Google Search"), 1000);
  } finally {
    await driver.quit();
  }
})();
```

With Node.js v18, I get:

```
➜ node index.js  
/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/index.js:51
    throw new Error('Invalid URL: ' + aUrl)
          ^

Error: Invalid URL: http:/
    at getRequestOptions (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/index.js:51:11)
    at new HttpClient (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/index.js:90:21)
    at getStatus (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/util.js:38:18)
    at checkServerStatus (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/util.js:76:14)
    at /Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/util.js:74:5
    at new Promise (<anonymous>)
    at Object.waitForServer (/Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/http/util.js:57:10)
    at /Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/remote/index.js:251:24
    at new Promise (<anonymous>)
    at /Users/werner/Desktop/selenium-node-test/node_modules/selenium-webdriver/remote/index.js:246:20

Node.js v18.1.0
```

With Node.js v16 (the current LTS release), it works fine. It should be noted though that with v18, the variables for the `.format` call are:

```
serverUrl: http:/, hostname: undefined, port: 52511, self.path_: /
```

Whereas for v16, the variables are:

```
serverUrl: http://127.0.0.1:52535/, hostname: 127.0.0.1, port: 52535, self.path_: /
```

Notably, the hostname is undefined in Node.js v18. This leads me to the function `os.networkInterfaces()` whose output is different in v18 compared to v16.

Here is v16:

```
> os.networkInterfaces()
{
  lo0: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    }
   ...
```

And here is v18:

```
> os.networkInterfaces()
{
  lo0: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 4,
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    },
    ...
```

See that the `family` property now reads `4` and not `IPv4`.

### How can we reproduce the issue?

```shell
Shown above.
```

### Relevant log output

```shell
Log already shown in reproducible example above.
```

### Operating System

Any

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Irrelevant

### What are the browser driver(s) and version(s) where you see this issue?

Irrelevant

### Are you using Selenium Grid?

No

**Comment by slhck** [comment]
A minute after posting, I saw that this was fixed in dec3bb83f6f353b751d1b8eb33ac672c70305a01.

Can we please get a new release? Last one was in November 2021.

**Comment by titusfortner** [comment]
@slhck v4.1.2 was released 3 weeks ago — https://www.npmjs.com/package/selenium-webdriver/v/4.1.2

**Comment by simonua** [comment]
Hi @titusfortner, I appreciate all the work on this repo and package! Would you be able to roll a new version with this commit, please? It would be awesome to use Node 18 with it.

Thank you!

**Comment by titusfortner** [comment]
Hoping to have one next week, but no promises, it'll happen when we can make it happen.

**Comment by simonua** [comment]
Of course! Thank you so much!

**Comment by slhck** [comment]
> @slhck v4.1.2 was released 3 weeks ago — https://www.npmjs.com/package/selenium-webdriver/v/4.1.2

It seems the GitHub releases are out of date. This is what I checked and it said that the last release was 6 months ago. But yes, you're right, the patch release is newer.

**Comment by titusfortner** [comment]
Patch releases are language specific. Minor releases are for the entire project, so we only update github releases for minor and major releases.

**Comment by slhck** [comment]
Got it, thanks for the clarification! 👍

**Comment by simonkurtz-MSFT** [comment]
I am now successfully running my tests with Node 18.2 with 4.2.0. Very awesome, @titusfortner! Thank you very much!
