### ISSUE TITLE
Javadoc not being released to maven2 repo for selenium-java

### ISSUE THREAD

**Issue by psufoxman** [SeleniumHQ/selenium#1062]
Starting with Selenium 2.45.0, the javadocs for selenium-java are not appearing in the maven repo.

ex: http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.45.0/

This is still an issue with the latest 2.47.1:
http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.47.1/

**Comment by lukeis** [comment]
thanks for bringing this to my attention... no idea why that started happening, haven't changed the normal maven deploy process i follow. I'll check into why the sources and docs aren't getting attached.

**Comment by lukeis** [comment]
apparently I've been using java 8 for the most part... and selenium's javadoc fail to build with java 8... left a note to myself to build / deploy with 7 until we fix the issues in our javadoc.

2.47.2 has been deployed to maven central and was built from the 2.47.1 tag. (will show up in central very soon)

**Comment by psufoxman** [comment]
Looks like this issue is back again with the 2.48.X release.  Would you like a new issue to track?

**Comment by lukeis** [comment]
@psufoxman funny thing... 'selenium-java' has no source code in it at all :)

-sources jars are getting uploaded correctly for all of our other artifacts for example:

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-server/2.48.2/

**Comment by lukeis** [comment]
(and javadoc)
