### ISSUE TITLE
[🐛 Bug]: cant able to switch between windows in IE (mode) in serenity framework

### ISSUE THREAD

**Issue by kishoreCraziee** [SeleniumHQ/selenium#10629]
### What happened?

While executing in IE mode in edge, I cant able to switch to the new window, if anyone have the solution please help me with the solution.
Below is the code I was using,

String parent=driver.getWindowHandle();
Set<String>s=driver.getWindowHandles();
Iterator<String> I1= s.iterator();
while(I1.hasNext())
{
String child_window=I1.next();
if(!parent.equals(child_window))
{
driver.switchTo().window(child_window);
}

### How can we reproduce the issue?

```shell
String parent=driver.getWindowHandle();
Set<String>s=driver.getWindowHandles();
Iterator<String> I1= s.iterator();
while(I1.hasNext())
{
String child_window=I1.next();
if(!parent.equals(child_window))
{
driver.switchTo().window(child_window);
}
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

edge 101 version

### What are the browser driver(s) and version(s) where you see this issue?

msEdgeDriver 101 version

**Comment by diemol** [comment]
Please check the [docs and limitations](https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#known-limitations), if you have more questions, please use the links shared below.
