### ISSUE TITLE
[🐛 Bug]: Wrong type for WebElement.get_property

### ISSUE THREAD

**Issue by eNcacz** [SeleniumHQ/selenium#10624]
### What happened?

This is similar issue to #10623 

In this case it's not so straightforward. The `WebElement.get_property` declare return value type as `str`. 
It is true in many cases but if you try to get property 'parentElement' (see example below), then the return value is `WebElement`.
But mypy (PyCharm and other linters) complains that result of get_property is always `str`.
Can you declare return type of `get_property` as `Union` of all possible types, which the method can return?

### How can we reproduce the issue?

```shell
from chromedriver_binary.utils import get_chromedriver_path
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webelement import WebElement


def test():
  driver = webdriver.Chrome(executable_path=get_chromedriver_path() + '/chromedriver')
  driver.get('http://www.example.com/')
  element = driver.find_element(by=By.TAG_NAME, value='h1')
  parentElement: WebElement = element.get_property('parentElement')
  print(type(parentElement))


if __name__ == '__main__':
  test()
```

### Relevant log output

```shell
no log needed
```

### Operating System

Gentoo Linux

### Selenium version

Python 4.1.5

### What are the browser(s) and version(s) where you see this issue?

not relevant

### What are the browser driver(s) and version(s) where you see this issue?

not relevant

**Comment by symonk** [comment]
Thanks @eNcacz our typing is a mess right now and not actually enforced (adding it to a sizeable code base is not so straight forward especially when we do a lot of things dynamically; I will get a look at this as soon as I have any free time, I've been fixing a few other typing mishaps recently

**Comment by titusfortner** [comment]
Yeah, we unwrap a lot of things. I think this is what we want, but I'm not an expert on typing, (yet):

```python
def get_property(self, name) -> Union[str,WebElement,ShadowRoot,dict,list]:
```

**Comment by symonk** [comment]
LGTM @titusfortner (I'll defer to you on the actual types returned there) but since we are py3.7+ best to roll with `typing.Dict[K_Type, V_Type]` & `typing.List[Generic_Type]` here rather than the builtin `dict` & `list` as I don't think they work properly until `3.9+`

**Comment by titusfortner** [comment]
Here's the deal.
Everything that returns from `execute()`:
https://github.com/SeleniumHQ/selenium/blob/d5273d8bc564b4af1cf8eb7688360dc7fab018ab/py/selenium/webdriver/remote/webdriver.py#L410

Gets unwrapped:
https://github.com/SeleniumHQ/selenium/blob/d5273d8bc564b4af1cf8eb7688360dc7fab018ab/py/selenium/webdriver/remote/webdriver.py#L395

So, what I suggested above is every single type that could theoretically get unwrapped. But we know more about might come back from each command execution, so we can probably be smarter about it, but we'll need to be conscientious about it. get_property() shouldn't return a dict or a list, I don't think? Oh, but it could return a boolean. Sigh. Not sure how far to go down this path.

**Comment by eNcacz** [comment]
> Yeah, we unwrap a lot of things. I think this is what we want, but I'm not an expert on typing, (yet):
> 
> ```python
> def get_property(self, name) -> Union[str,WebElement,ShadowRoot,dict,list]:
> ```

It looks good to me.

**Comment by titusfortner** [comment]
Java & .NET convert all non-Element values to Strings, but Ruby returns the type it gets, which I think is more accurate to the purpose of differentiating properties from attributes.

Based on this — https://javascript.info/dom-attributes-and-properties#dom-properties-are-typed
Looks like we can expect `str`, `bool`, `WebElement`, `dict`. Nothing preventing a list, but I wouldn't expect that.

**Comment by eNcacz** [comment]
@titusfortner I think this list is not enough. For example 

* `clientHeight` property is returned as `int`
* `fooBar` property is returned as `NoneType` 
* `childNodes` property is returned as `list`

Just put these names to the example above to test it.

So I think it will be better to use `Optional[Union[str, int, bool, WebElement, dict, list]]`

**Comment by titusfortner** [comment]
Would you mind helping by making a PR for the changes you'd like to see?
