### ISSUE TITLE
Logo in SVG available?

### ISSUE THREAD

**Issue by royduin** [SeleniumHQ/selenium#1063]
I'd like to add the Selenium logo to https://github.com/websiddu/technology-icons, see: https://github.com/websiddu/technology-icons/issues/12. Is there a SVG available?

**Comment by lukeis** [comment]
here's one:
https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/webapp/images/originals/Selenium%20Logo%20Upright.svg

**Comment by royduin** [comment]
Thank you!
