### ISSUE TITLE
[🐛 Bug]: Queue size is always high and the grid is drastically underutilized

### ISSUE THREAD

**Issue by amitkpal83** [SeleniumHQ/selenium#10635]
### What happened?

![ErrorScreenshot](https://user-images.githubusercontent.com/6175985/167858548-a1c96c8b-610b-452a-b1cd-c87d0ea77fda.png)
Queue size is more than 10 and nodes are already up. But still it will take atleast 10 to 15 minutes to pickup those test and process. Which is making run slower.

### How can we reproduce the issue?

```shell
It is a simple test suite and setup in Kubernetes cluster with Keda for scaling.
```

### Relevant log output

```shell
No errors. It is just like it is taking time to utilize chrome nodes.
```

### Operating System

Linux

### Selenium version

Java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 

### What are the browser driver(s) and version(s) where you see this issue?

v.91.0

### Are you using Selenium Grid?

Grid version: 4.0.0-rc-1

**Comment by diemol** [comment]
Please try the most recent version (4.1.4) and let us know how it goes. Also, we need a way to reproduce what you see, otherwise we cannot really troubleshoot things.

**Comment by diemol** [comment]
Closing as we did not get more information.
