### ISSUE TITLE
🐛 Session timeout exception while launching Edge in IE mode

### ISSUE THREAD

**Issue by SubhenduShekhar** [SeleniumHQ/selenium#10633]
### What happened?

See #9793 the scenario is exactly same. But even after using the mentioned solution and configuring with the latest of selenium and IEDriverServer.exe versions, the problem remains same. i.e., Edge opens in IE mode successfully but control is never returned back to the script.

### How can we reproduce the issue?

```shell
Language: C#
1. Download Selenium.Webdriver v4.1.1
2. Download 32-Bit IEDriverServer.exe v4.0.0 or higher and put it in path(say C:/Drivers/IEDriverServer.exe)
3. Use below script:

using OpenQA.Selenium.IE;

namespace SeleniumTest
{
    class Program
    {
        static void Main(string[] args)
        {

            var driver = new InternetExplorerDriver(@"C:\Driver", new InternetExplorerOptions
            {
                AttachToEdgeChrome = true,
                EdgeExecutablePath = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
                IgnoreZoomLevel = true
            });
        }
    }
}

```
```


### Relevant log output

```shell
OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:53359/session timed out after 60 seconds.'
```

### Operating System

Windows 10

### Selenium version

DOTNET 4.1.1

### What are the browser(s) and version(s) where you see this issue?

Edge 101.0.1210.39

### What are the browser driver(s) and version(s) where you see this issue?

32/64-Bit IEDriverServer 4.0.0.0

**Comment by diemol** [comment]
I have seen this when my IE configuration was not correct. 

Are your settings and configuration the recommended one? 
* https://www.selenium.dev/documentation/ie_driver_server/ 
* https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp.

**Comment by SubhenduShekhar** [comment]
@diemol I using the recommended settings as mentioned in the document. Still no luck :(

**Comment by diemol** [comment]
OK, then I would recommend to report this to the Edge folks.

**Comment by diemol** [comment]
I know the comment mentions the EdgeDriver but the idea is to report the issue to them as they are also helping to maintain the IE in Edge mode integration.

**Comment by SubhenduShekhar** [comment]
@diemol even the standard way of initiating IEDriver is also not working. Refer this snippet:
`using OpenQA.Selenium.IE;

namespace SeleniumTest
{
    class Program
    {
        static void Main(string[] args)
        {

            var driver = new InternetExplorerDriver(@"D:\PythonDemo\userdata");
        }
    }
}
`
