### ISSUE TITLE
[🚀 Feature]: Having Search box added in Selenium 4 Grid GUI

### ISSUE THREAD

**Issue by Nkperiwal** [SeleniumHQ/selenium#10632]
### Feature and motivation

**Scenario:** When we start our selenium automation test script execution on Selenium4 Grid GUI (http://localhost:4444/ui/index.html), we can see the sessions gets located to required TestCases. We do have sorting option or can see 15 VNC sessions at time but it's difficult when the TestCases number being executed are more (~80 I am currently executing).

**Issue:** We cannot directly search with session ID or name (if we set it using setCapability("se:name","")) in VNC Sessions UI.

**Request:** Request to add new feature of adding search box in Sessions Grid 4 VNC GUI to making the search easy.

**Original Grid-4** 

<img width="1904" alt="Original Grid4" src="https://user-images.githubusercontent.com/35780233/167840815-77536c1b-b25c-422f-8139-564c073f1bf1.png">

**Modified Grid-4** 

<img width="1904" alt="Modified Grid 4" src="https://user-images.githubusercontent.com/35780233/167840782-425dc616-80cf-4d6f-a3d8-5f37f6795505.png">

### Usage example

I am going to use this search box feature for Sessions Grid 4 GUI to search particular sessionId or the name of VNC for the session I provided.

**Comment by diemol** [comment]
@Nkperiwal would you like to help us with a PR?

**Comment by zzhilin** [comment]
Hi I would like to work on this issue.

**Comment by diemol** [comment]
@zzhilin Feel free to send us a PR 🎉
