### ISSUE TITLE
Timeout settings are confusing and inconsistent

### ISSUE THREAD

**Issue by OndraM** [SeleniumHQ/selenium#1064]
Hi, I need to extend the default timeout (as my test needs to sleep for a while) and I run into these two confusing behaviors of the Selenium server:

1. The hub settings
====
The docs say, the `-timeout` and `-browserTimeout` values should be in seconds:
> -timeout <nnnn>: an integer number of seconds we should allow a client to be idle

If the hub is started with timeout value provided: `java -jar selenium-server-standalone-2.47.1.jar -role hub -timeout 900` the console prints: `timeout : 900000`. So it look like the internal representation is in ms. I think this (not the internal representation, but the config output and "config input" (= CLI params) should be consistent to avoid confusion about unit of the value.

2. The node settings
====
Also for the node, according to the help, the `-timeout` and `-browserTimeout` values should be in seconds.
So I start the node with command `java -jar selenium-server-standalone-2.47.1.jar -role node -timeout 900`. But not when I check in the grid console the Configuration tab for the node, there is printed `timeout:900`. So is this ms or secs now? 

Unlike the hub settings, it looks like the input value is actually in miliseconds here - when tested, the firefox browser window created by node run with this param (`-timeout 900`) is closed in less than few seconds (`WARN - session ext. key ... has TIMED OUT due to client inactivity and will be released.`], however, using miliseconds value (`-timeout 900000`) makes the node holding for 15 minutes. I also find few questions on Stackoverflow from people trying to use the seconds value on the node and reporting it not to be preventing the browser from timeout (which could simply be caused by the wrong unit used - secs/ms).

So the settings is inconsistent amongst hub, node and the documentation.

**Comment by semonte** [comment]
I have signed the CLA.

**Comment by harriswong** [comment]
There is a commit in 2.49.1 that may address this: https://github.com/SeleniumHQ/selenium/commit/545fba4d6c02645e1530d97a3c20bda74631a180

**Comment by semonte** [comment]
Yes that commit relates to the same issue. This PR is about displaying the data and 545fba4 is about using the correct time unit.

**Comment by mach6** [comment]
I believe this is fixed for Se3. Please re-open if you have follow-up comments.
