### ISSUE TITLE
[🐛 Bug]: In Java17 creating new Chrome driver causes runtime exception

### ISSUE THREAD

**Issue by benwilbur** [SeleniumHQ/selenium#10644]
### What happened?

Simply creating a new ChromeDriver causes this runtime error. Similar to previous issue #7676 (https://github.com/SeleniumHQ/selenium/issues/7676)

### How can we reproduce the issue?

```shell
WebDriver driver = new ChromeDriver();
```

### Relevant log output

```shell
Exception in thread "main" java.util.ServiceConfigurationError: org.openqa.selenium.devtools.CdpInfo: module org.seleniumhq.selenium.remote_driver does not declare `uses`
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:579)
	at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:507)
	at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1653)
	at org.seleniumhq.selenium.remote_driver/org.openqa.selenium.devtools.CdpVersionFinder.<init>(CdpVersionFinder.java:44)
	at org.seleniumhq.selenium.chromium_driver/org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:126)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:106)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:93)
	at org.seleniumhq.selenium.chrome_driver/org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:48)
```

### Operating System

Windows 7

### Selenium version

Java 4.1.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 101

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

### Are you using Selenium Grid?

None

**Comment by titusfortner** [comment]
Plenty of people use Java 17 with Selenium, so we can't reproduce your issue with just that line. What are you requiring in your pom? Please verify you don't have a dependency issue.

**Comment by SaudAlshareef** [comment]
i am facing the same issue and my pom is
![image](https://user-images.githubusercontent.com/71377529/168469037-4306c542-ef89-497a-926f-b76aa1aa7133.png)
![image](https://user-images.githubusercontent.com/71377529/168469087-825a4720-c195-40b6-b4c4-4c04753e2940.png)
![image](https://user-images.githubusercontent.com/71377529/168469094-e68e32da-e4d3-426b-9756-85c345bce3ca.png)

**Comment by diemol** [comment]
Can you please share a GitHub repository with the complete setup so we ca. replicate?

**Comment by alaahong** [comment]
Working well on Java 17 + Java 4.1.4 + Chrome 101.

Suggest to take a try:
1. Try to refresh your dependencies as your involved. From your mentioned issues, we find that the keywords  "uses" is from Selenium 3, not 4
2. As this is a CDP issue, you might face some version issue? you can set chrome binary in options as target version;

**Comment by valodzka** [comment]
@diemol @alaahong I see same error message, here minimal project that triggers it: https://github.com/valodzka/selenium-bug-10644

**Comment by yaoyuqi** [comment]
I have the same issue. I find that it is due to lack of modularity access rights.  
In the  class org.openqa.selenium.devtools.CdpVersionFinder, the constructor uses Serviceloader to load CdpInfo class. 
However, the remote-driver's module descriptor missed the statement "uses org.openqa.selenium.devtools.CdpInfo;".
Meanwhile, I find that the statement existed until version 4.1.3.

**Comment by theobarrague** [comment]
Same issue here on 4.3.0 with Chromium 106.0.5213.0

**Comment by titusfortner** [comment]
You can't have a static variable for the driver. Define it inside main, or run it from a non-static context like in JUnit.

**Comment by titusfortner** [comment]
So, it wasn't moving the variable out of static that got this working, I got it working by removing the `module-info.java` file, which I don't think is what we want. I'm re-opening; another Java dev will have to chime in on this.

**Comment by titusfortner** [comment]
There we go. Sorry for not realizing that my "fix" was the wrong one, and thank you for the reproducible repo, it was very helpful.

https://github.com/SeleniumHQ/selenium/commit/4ed89beda0d67665987dcba4ea8812afea34de7f
