### ISSUE TITLE
[🐛 Bug]: frame command does not support using an ID or name directly 

### ISSUE THREAD

**Issue by gravityvi** [SeleniumHQ/selenium#10654]
### What happened?

We can't use frame command with ID or names like:
```js
// Using the ID
await driver.switchTo().frame('buttonframe');`

// Or using the name instead
await driver.switchTo().frame('myframe');
```
But as per [docs](https://www.selenium.dev/documentation/webdriver/browser/frames/#using-a-name-or-id), it says we can do that

### What browsers and operating systems are you seeing the problem on?

Across all browsers

**Comment by harsha509** [comment]
Hi @gravityvi ,

Looks like JS doesn't have support for it. It needs to be updated.

**Comment by harsha509** [comment]
implementing this should do the work for ID. 

```
frame(id) {
    let frameReference = id;

    if (typeof id === "string") {
        frameReference = this.driver_.findElement({
            id: id
        });
    }

    return this.driver_.execute(
        new command.Command(command.Name.SWITCH_TO_FRAME).setParameter('id', frameReference)
    )}
```

**Comment by harsha509** [comment]
[This](https://github.com/SeleniumHQ/selenium/commit/97aeedba6a10e24947958bd0af5c05ce3e093a03) should add support to switch frame by id. 

Following the ruby implementation. switch to frame `by.name` can be done by passing WebElement.

**Comment by AutomatedTester** [comment]
This is by design from the webdriver spec. To get around this you will need to follow what @harsha509 put. You can see the python version at https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/switch_to.py#L70-L94
