### ISSUE TITLE
[🚀 Feature]: [py] A common interface/mixin for element location `find_element(...)` & `find_elements(...)`

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#10652]
### Feature and motivation

There is some duplication throughout the following areas that are (largely) carrying out the same tasks:

```console
grep -rE "def find_elements?\(" * 
selenium/webdriver/remote/webdriver.py:    def find_element(self, by=By.ID, value=None) -> WebElement:
selenium/webdriver/remote/webdriver.py:    def find_elements(self, by=By.ID, value=None) -> List[WebElement]:
selenium/webdriver/remote/webelement.py:    def find_element(self, by=By.ID, value=None):
selenium/webdriver/remote/webelement.py:    def find_elements(self, by=By.ID, value=None):
selenium/webdriver/remote/shadowroot.py:    def find_element(self, by: By = By.ID, value: str = None):
selenium/webdriver/remote/shadowroot.py:    def find_elements(self, by: By = By.ID, value: str = None):
selenium/webdriver/support/event_firing_webdriver.py:    def find_element(self, by=By.ID, value=None):
selenium/webdriver/support/event_firing_webdriver.py:    def find_elements(self, by=By.ID, value=None):
selenium/webdriver/support/event_firing_webdriver.py:    def find_element(self, by=By.ID, value=None):
selenium/webdriver/support/event_firing_webdriver.py:    def find_elements(self, by=By.ID, value=None):
```

Note: `EventFiringWebDriver` is just dynamically dispatching calls at runtime and implements nothing itself.

These areas can likely be simplified by exposing some sort of `LocatesElementsMixin` (or whatever is better named in line with other bindings; a mixin class is just an idea as it has some drawbacks too, but this issue is more just to figure out what would be a good approach to unifying it.

A few of the problems:

 - Keeping backwards compatibility
 - The actual webdriver `Command` dispatch varies throughout
 - instance attributes vary in naming which makes a mixin class a little tougher and unclean

Curious on your thoughts to this?  @AutomatedTester has a comment in `ShadowRoot.py` here; I assume it was also aiming to move towards something _like_ this?

https://github.com/SeleniumHQ/selenium/blob/575b878db2efccdde95ea8d0bdf6b8db4bea1fa0/py/selenium/webdriver/remote/shadowroot.py#L26

Python is not java of course so we should keep that in mind and leverage duck typing etc where applicable.

**Comment by AutomatedTester** [comment]
This part of the deprecation plan in my head for the `find_element_*` method to get us to this point and then we can move to either using Mixins here or have a pure object (like .NET/Java).

**Comment by symonk** [comment]
@titusfortner cleared the milestone here; don't think it's a good one, let's focus on clearing down what needs removed first, then we can look at consolidating the APIs

**Comment by titusfortner** [comment]
@AutomatedTester were you thinking of having a SearchContext class that each of these methods can call? (because I know you don't like mix-ins)
