### ISSUE TITLE
[🐛 Bug]: ChromeOptions Detach not working

### ISSUE THREAD

**Issue by cljiahao** [SeleniumHQ/selenium#10658]
### What happened?

Previously worked on Selenium 4.1.3 with Chromedriver v101. The chrome browser opens and stayed open after completing its task. 

Saw that there was some update regarding about 4.1.3 which causes the next lines of code unreadable. Thus, updated to 4.1.5. 
Next lines of code are readable but the detach argument isn't working anymore either. 

Used the code as below and the browser closes right after the webpage is loaded.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_experimental_option("detach", True)

driver = webdriver.Chrome(options=chrome_options)

driver.get('https://www.google.com')
```

### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:57091/devtools/browser/df209925-c880-494d-9a7f-6dcb98216d52
```

### Operating System

Windows 10

### Selenium version

4.1.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 101.0.4951.67

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

### Are you using Selenium Grid?

No

**Comment by cljiahao** [comment]
New Findings:
Using python idle, the function works. The chrome webpage did not close. 

P.S. The above mentioned error occurs when using VSCode. Unsure where it causes the selenium to quit.

**Comment by titusfortner** [comment]
It worked in VsCode in previous version of Selenium python?

**Comment by symonk** [comment]
This works completely fine for me on `4.1.3` & `4.1.5`.

```console
chromedriver --version && pip freeze | grep selenium                                                                                                                          ✔  pythonProject5 🐍  20:55:05   
ChromeDriver 101.0.4951.64 (d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208})
selenium==4.1.5
```
-----

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options


def main() -> int:
    chrome_options = Options()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get('https://www.google.com')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
```

browser remains open as you would expect.

**Comment by cljiahao** [comment]
> It worked in VsCode in previous version of Selenium python?

It worked in VsCode previously but stopped after updating to 4.1.5.

> This works completely fine for me on `4.1.3` & `4.1.5`.
> 
> ```
> chromedriver --version && pip freeze | grep selenium                                                                                                                          ✔  pythonProject5 🐍  20:55:05   
> ChromeDriver 101.0.4951.64 (d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208})
> selenium==4.1.5
> ```
> 
> ```python
> from selenium import webdriver
> from selenium.webdriver.chrome.options import Options
> 
> 
> def main() -> int:
>     chrome_options = Options()
>     chrome_options.add_experimental_option("detach", True)
>     driver = webdriver.Chrome(options=chrome_options)
>     driver.get('https://www.google.com')
>     return 0
> 
> 
> if __name__ == "__main__":
>     raise SystemExit(main())
> ```
> 
> browser remains open as you would expect.

tested the code and it still closes after it loads when running on VsCode.

**Comment by symonk** [comment]
@cljiahao does this work when you run `python main.py` from the commandline/terminal as expected? (if so its whatever the IDE is doing to the processes/children and theres likely nothing for us to investigate).  If it still happens on the CLI, please let me know and we can look into it.

**Comment by cljiahao** [comment]
@symonk It worked on the IDE previously, thus would like to know why couldn't work now.
When running via CLI, it works perfectly!

Understood that there's nothing to be done, probably some IDE issues. Will close this issue! thank you!
