### ISSUE TITLE
[🐛 Bug]: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by alimp5** [SeleniumHQ/selenium#10666]
### What happened?
        from selenium.webdriver.support import expected_conditions as EC
        from selenium.webdriver.common.by import By
        from selenium import webdriver
        from selenium.webdriver.firefox.options import Options
        from selenium.webdriver.common.keys import Keys
        from selenium.webdriver.common.by import By
        from selenium.common import exceptions
        from selenium.webdriver.common.action_chains import ActionChains
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.firefox.webdriver import FirefoxProfile
        from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
        from selenium.webdriver.common.proxy import Proxy, ProxyType
        from selenium.webdriver.firefox.service import Service

        profile_path = "F:\\ea_env\\..................\\firefox_profile"
        cookie_path  = "F:\\ea_env\\..................\\firefox_cookie.pkl"
        my_url = "https://kitchen.applitools.com/ingredients/canvas/"
        
        profile_path = r"C:\Users\..................\Roaming\Mozilla\Firefox\Profiles\2jwvchja.bot5"
        desktop_path = str(pathlib.Path.home()) + '\\Desktop'
        gecko_path = f"{desktop_path}\\geckodriver.exe"
        options = Options()
        options.headless = False
        options.set_preference('profile', profile_path)
        service = Service(gecko_path)
        options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
        options.add_argument('--excludeSwitches --enable-logging')
        options.add_argument('--no-default-browser-check')
        options.add_argument('--no-sandbox')
        driver = webdriver.Firefox (service=service, options=options)
        driver.implicitly_wait(100)
        driver.set_page_load_timeout(100)

        driver.get (my_url)
        canvas = driver.find_element(By.ID, "burger_canvas")
        action = ActionChains(driver)
        action.move_to_element_with_offset(canvas, 500, 350).click().perform()

### How can we reproduce the issue?

```shell
I followed tutorial below and tried to do it by Python Standalone Selenium.
https://www.youtube.com/watch?v=NebFQ31NFtE
target url for test:
https://kitchen.applitools.com/ingredients/canvas

I saved canvas picture and tried to find the center location of canvas's button (Lets Eat) via Paint.
x: 500px
y: 350px

https://imgur.com/a/kya1dji
```

### Relevant log output

```shell
Exception ignored in: <function Popen.__del__ at 0x0000013663B6E430>
Traceback (most recent call last):
  File "C:\Python38\lib\subprocess.py", line 949, in __del__        
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Python38\lib\subprocess.py", line 1348, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:     
OSError: [WinError 6] The handle is invalid
```

### Operating System

Windows 10 - 64 bit - latest build

### Selenium version

Python 3.8.10 & 3.9.10 -- Selenim 4.1.5

### What are the browser(s) and version(s) where you see this issue?

Firefox 99

### What are the browser driver(s) and version(s) where you see this issue?

Gecko driver 0.31

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
We cannot really troubleshoot a tutorial that is out of date, please reach out to the tutorial creator and ask them to update the content.

**Comment by alimp5** [comment]
@diemol 
I'm doing it with python selenium with latest changed that released by selenium team.
the tutorial is based on C#.  but i want to test it with python.....   
where is problem, when i want to do it with python :)?
i want to click on a CANVAS.

on a real project i encounter an error and selenium can't find the canvas element by id. 
i searched and googled a lot about canvas and those didn't work....

mentioned site is a good target to test the selenium.

**Comment by alimp5** [comment]
@diemol 
why without any try to read and understand the root cause of problem,,,, you closed it?
i'm talking with a noob senior? or i'm a noob :)?

when you can't read and understand the problem, you can't solve the problem. :)

**Comment by alimp5** [comment]
dears,
please recheck this issue that closed by a ...... :)

@shs96c
@barancev
@jarib
@AutomatedTester
@dfabulich

**Comment by alimp5** [comment]
```
        canvas = self.driver.find_element(By.ID, "burger_canvas")
        canvas_dimen = canvas.size
        canvas_location = canvas.location
        
        canvas_center_x = int(canvas_dimen.get('width') / 2)
        canvas_center_y = int(canvas_dimen.get('height') / 2)
        
        loc_x = int((canvas_center_x / 3) * 2)
        loc_y = int((canvas_center_y / 3) * 2)
        
        action = ActionChains(self.driver)
        action.move_to_element_with_offset(canvas, loc_x, loc_y).click().perform()
```

and again:
```
Exception ignored in: <function Popen.__del__ at 0x000002039FB9E3A0>
Traceback (most recent call last):
  File "C:\Python38\lib\subprocess.py", line 949, in __del__        
    self._internal_poll(_deadstate=_maxsize)
  File "C:\Python38\lib\subprocess.py", line 1348, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:     
OSError: [WinError 6] The handle is invalid
```

**Comment by diemol** [comment]
Apologies if closing this was perceived as a harsh thing, I did not mean to do that. What I meant to say is that this is a question about why something is not working on a tutorial not done by the Selenium team. If you need help figuring this out, I will leave some links below where you can reach out to us and the community to understand what the issue might be.

**Comment by alimp5** [comment]
@diemol 
I downgrade selenium to version `4.0.0 beta`. and i didn't receive any error message...... 👍 
when i'm talking about selenium bugs and a core developer is talking about tutorial t-shooting........
Nothing Else..............

**Comment by titusfortner** [comment]
Your initial submission does not read like a bug report, but like you don't know how to do something in Selenium. We close those issues because there are other places to get help.

If you think you have found a bug, you need to provide a reproducible use case, error message and a stack trace. You provided a bunch of information that won't help us figure out the problem, and not enough information that would. What line of your code caused the error? A generic Python error could be a Selenium issue or something on your system, we need more info to help.

Now, no one likes feeling dismissed, but getting upset and tagging old contributors and adding emoji responses to your own comments is weird and unlikely to result in people wanting to help you. If you have something reproducible or even if you can tell us in which release something stopped working, that we can do something with.

**Comment by alimp5** [comment]
@titusfortner 
i added everything in first comment for selenium team to debug codes and reproduce the issue quickly.
reaction to correct answer is my opinion; even a comment from myself to solve an incorrect answer from selenium-team developer.

thanks you.
THE END..

**Comment by alimp5** [comment]
@titusfortner 
@diemol 
Thanks You and Selenium Team for this amazing framework ;X
have the best times in best places ;X

🥇 SELENIUM 🥇
