### ISSUE TITLE
[🚀 Feature]: Add selenium grid to maven central

### ISSUE THREAD

**Issue by giflw** [SeleniumHQ/selenium#10665]
### Feature and motivation

Add selenium grid to maven central to allow embedding it on Java aplications. Can be added just the http server for remote driver.

### Usage example

Build a custom remote web driver without need to reimplement the server api redirections to web driver implementation. It can be HTMLUnit, or a web driver that I'm building for JavaFX WebView

**Comment by diemol** [comment]
This is already available 
https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-grid
https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-grid/4.1.4/

**Comment by giflw** [comment]
Thanks. I was searching using search.maven.org and could not find it....
