### ISSUE TITLE
[🚀 Feature]: AAU I want to be able to use the upload a Folder with Files with RemoteWebElement sendKeys

### ISSUE THREAD

**Issue by gsgPerkin** [SeleniumHQ/selenium#10664]
### Feature and motivation

I will explain what are we trying to do. We want to sendkeys with RemoteWebElement to a folderBrowserDialog in ChromeWebDriver. When we try to do this in local machines we can send keys to the folderBrowserDialog without further problem, but when we launch the same test in the Selenoid machines that use RemoteWebElement Seleniumcode will check if there is a before the sendkeys or making the zip to upload. These are the particular lines of code.

`List<File> files = (List)var10000.map((xva$0) -> {
                return var10001.getLocalFile(new CharSequence[]{xva$0});
            }).collect(Collectors.toList());
            if (!files.isEmpty() && !files.contains((Object)null)) {
                allKeysToSend = (String)files.stream().map(this::upload).collect(Collectors.joining("\n"));
            }`
 
So, since we are giving a Folder path who contains all the files we want to upload there is no file explicit and the files.isEmpty() is failing, as it is expected. We try to give also one file present in the folder, but this is also not working since the folder browser is not accepting files only folder paths.       

### Usage example

The use of this feature will be upload the folder, with a variable number of filesz, making use of the folderBrowserDialog when we are working with RemoteMachines in Selenium grid. 
Since it is working already in local machines will be nice if it work as well in remoteWebElement.

**Comment by titusfortner** [comment]
For a remote machine you need to use a local file detector. It will look to see if there is a matching file on the computer executing the code and upload it to the computer running the browser and provide the path of the new location to the driver.

https://www.selenium.dev/documentation/webdriver/remote_webdriver/#local-file-detector

**Comment by gsgPerkin** [comment]
We are using already remote machine, we upload files without further problem. The issue here is load the entire folder (who contains several files) with this Browserdialog 
![image](https://user-images.githubusercontent.com/91734900/169025155-1f98de89-ba0d-4c75-a93b-1cbb5a11acf0.png)
![image](https://user-images.githubusercontent.com/91734900/169025366-45d6740b-85d4-414a-a5ec-dec1ccfead0c.png)

In that particular folder there are two files. We cannot select one of them with this particular dialog, we only can give it the folder path.

**Comment by diemol** [comment]
You need to give the file path to one or more files, folder paths do not work.

**Comment by gsgPerkin** [comment]
That was my point creating this as a request, because if we cannot give a file/s path because the Browserdialog only admits folder paths and we cannot give a folder path to selenium with files in it we cannot upload the files in anyway. 
In local this is working just fine, you only need to give the folder path where the files are and the browser will upload them without any further problem. 
So I was thinking this may be possible to change with a RemoteWebElement folderToUpload method in the class, letting the user select if what they are uploading is a folder or a file, and if it is a folder uploading that folder in the same way we are uploading the files.

**Comment by titusfortner** [comment]
Ah, I see, sorry for the misunderstanding.

So, this is something that would need to be proposed to w3c.
Per [the W3C WebDriver specification](https://w3c.github.io/webdriver/#:~:text=first%20matching%20condition%3A-,file,-is%20true), it is not supported.

Perhaps if we implement a separate upload endpoint, this could be included — https://github.com/w3c/webdriver/issues/1355
