### ISSUE TITLE
[🐛 Bug]: getScreenshotAs on web element doesn't use retina resolution unlike driver screenshot 

### ISSUE THREAD

**Issue by MykolaGolubyev** [SeleniumHQ/selenium#10679]
### What happened?

Hello,

```driver.getScreenshotAs``` generates HiDPI screenshot when ran on retina display. 
```webElement.getScreenshotAs``` generates single pixel screenshot in the same environment/test. 

Didn't notice a setting to affect this. Could you please help me figure out what am I missing? 

### How can we reproduce the issue?

```shell
execute `webElement.getScreenshotAs` using hi dpi output device
```

### Relevant log output

```shell
NA
```

### Operating System

Latest Mac

### Selenium version

Java 4.1.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 101

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 101.0.4951.41

**Comment by titusfortner** [comment]
I'm using a retina display and it is all working as expected.

Make sure `element.getSize()` matches the size you expect, you might not be working with the element you think you are.

You didn't mention which `OutputType` you are attempting to use. Does it make a difference if you use a different one?

Is the behavior different between Firefox & Chrome?

**Comment by MykolaGolubyev** [comment]
Thank you for getting back to me.
To clarify, the captured content is correct, i.e. the actual element visuals are captured. The problem is it captured with a single pixel precision. I.e. if element size is 100x100, the actual image is also 100x100, not 200x200 (pixelRatio = 2).
I capture image into `BufferedImage`. Will try a different option and a different browser later today or tomorrow.

**Comment by titusfortner** [comment]
Oh, I see what you are saying. Yes, the correct behavior per the spec is to return the size of the canvas. https://w3c.github.io/webdriver/#dfn-take-element-screenshot

If you think the behavior should be different for a higher pixelRatio, then it needs to be proposed in the w3c issue tracker.

**Comment by MykolaGolubyev** [comment]
Oh interesting, thanks for the explanation.
@titusfortner I read the item number 2 for both element screenshot and screen screenshot. They look very similar
> Let screenshot result be the result of [trying](https://w3c.github.io/webdriver/#dfn-try) to call [draw a bounding box from the framebuffer](https://w3c.github.io/webdriver/#dfn-draw-a-bounding-box-from-the-framebuffer), given root rect as an argument.

But they behave differently. Full screenshot uses double pixels and is the desired result. Element screenshot uses single pixel.

**Comment by titusfortner** [comment]
Another thing to check... what does Firefox do?

**Comment by MykolaGolubyev** [comment]
@titusfortner Firefox is storing double pixel buffer

**Comment by titusfortner** [comment]
Then it might be worth reporting the issue to chromedriver.
