### ISSUE TITLE
selenium taking screenshots larger than expected

### ISSUE THREAD

**Issue by EMCP** [SeleniumHQ/selenium#1067]
Hi selenium team, I have a question on the browser.takeScreenshot() functionality.  Using you in conjunction with Protractor...

It seems I can set the window/browser size.. via a call such as
```
    describe("login", function () {

        it("should go to login page", function () {
            browser.driver.manage().window().setSize(width, height);
            browser.get('/');
            expect(browser.getTitle()).toEqual("MyTitle");
            browser.takeScreenshot().then(function(png) {
                var stream = fs.createWriteStream("somepathandfilename");
                stream.write(new Buffer(png, 'base64'));
                stream.end();
           });
        });
```
The result of this process isn't matching the browser drivers dimensions.. I can work around this but just wondering, why?

Resulting image in the case of a width x height = 367 x 667 , was turned into 800x1190

**Comment by jimevans** [comment]
Under the current definitions for taking screenshots (as defined by the open source project), screenshots should be of the full DOM, irrespective of window size. There are two things to note, however. First, Chrome has an outstanding issue where it only creates screenshots of the visible view port. Second, the W3C WebDriver specification defines screenshots as current view port only. No currently shipping driver implementations are spec-compliant yet.

**Comment by EMCP** [comment]
Thank you for the explanation

**Comment by jamessimo** [comment]
@jimevans Reading through the [W3 webdriver spec](http://www.w3.org/TR/webdriver/#take-screenshot) for screen shots it seems that the current definitions for taking screenshots is 

>"The Take Screenshot command takes a screenshot of the top-level browsing context’s viewport." 

reading that and these comments :
https://github.com/ariya/phantomjs/pull/13422#issuecomment-149440353 
https://github.com/SeleniumHQ/selenium/issues/646

This issue should be re-opened until the browser.takeScreenshot() functionality works as stated by the W3C ?  (unless this issue is already open else where)

**Comment by jimevans** [comment]
The Selenium implementations of WebDriver make no claim to be compliant with the spec. Furthermore, the spec is still an Editor's Draft, and subject to revision at any time. Once the spec becomes a Candidate Recommendation, there will be an effort in the Selenium code base to enable compliance with the spec, and a release with that code enabled. At that time, this bug, if it still exists, should be reopened.
