### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by gdszps** [SeleniumHQ/selenium#10678]
### What happened?

Fetch.requestPaused not callback

### How can we reproduce the issue?

```shell
driver.execute_cdp_cmd('Fetch.enable', {'patterns':[{'urlPattern':'*.png'}]})
driver.add_cdp_listener('Fetch.authRequired', testtest)
driver.add_cdp_listener('Fetch.requestPaused', testtest)
```

### Relevant log output

```shell
null
```

### Operating System

mac os

### Selenium version

python  3.7

### What are the browser(s) and version(s) where you see this issue?

chrome 101

### What are the browser driver(s) and version(s) where you see this issue?

chrome 101

### Are you using Selenium Grid?

4.1

**Comment by titusfortner** [comment]
`add_cdp_listener()` is not a Selenium method, you appear to be using a different library.
