### ISSUE TITLE
[🐛 Bug]: Unable to get cookies on IE Compatibility mode with IEDriverServer 4.0.0

### ISSUE THREAD

**Issue by souban-git** [SeleniumHQ/selenium#10687]
### What happened?

Edge Version 101
IE Driver version 4.0.0 32 bit

Hi, My website IE Compatibility mode enabled. When I am launching my website using IE mode with IEdriver 4.0.0
i am unable to read cookies from the website. Able to fetch cookies when working on Edge and IE browsers separately

Configuration : 
{"se:ieOptions":{"ie.edgechromium":true,"ie.edgepath":"C:/Program Files )x86)/Microsoft/Edge/Application/msedge.exe"}}
Method used to get cookies:
Set<Cookie> bCookie = <IEdriver>.manage().getCookies();
also tried
(String) <iedriver>.executeScript("return document.cookie");

for both above methods getting below error

getCookies:{}Could not retrieve cookies.
The most common cause of this error is
mismatch in the bitness between the driver and browser. In particular, be sure you are not
attempting to use a 64-bit IEDriverServer-exe against IE 10 or 11,
even on 64-bit Windows

### How can we reproduce the issue?

```shell
Edge Version 101
IE Driver version 4.0.0 32 bit

Hi, My website IE Compatibility mode enabled. When I am launching my website using IE mode with IEdriver 4.0.0
i am unable to read cookies from the website. Able to fetch cookies when working on Edge and IE browsers separately

Configuration : 
{"se:ieOptions":{"ie.edgechromium":true,"ie.edgepath":"C:/Program Files )x86)/Microsoft/Edge/Application/msedge.exe"}}
Method used to get cookies:
Set<Cookie> bCookie = <IEdriver>.manage().getCookies();
also tried
(String) <iedriver>.executeScript("return document.cookie");

for both above methods getting below error

getCookies:{}Could not retrieve cookies.
The most common cause of this error is
mismatch in the bitness between the driver and browser. In particular, be sure you are not
attempting to use a 64-bit IEDriverServer-exe against IE 10 or 11,
even on 64-bit Windows
```

### Relevant log output

```shell
Edge Version 101
IE Driver version 4.0.0 32 bit

Hi, My website IE Compatibility mode enabled. When I am launching my website using IE mode with IEdriver 4.0.0
i am unable to read cookies from the website. Able to fetch cookies when working on Edge and IE browsers separately

Configuration : 
{"se:ieOptions":{"ie.edgechromium":true,"ie.edgepath":"C:/Program Files )x86)/Microsoft/Edge/Application/msedge.exe"}}
Method used to get cookies:
Set<Cookie> bCookie = <IEdriver>.manage().getCookies();
also tried
(String) <iedriver>.executeScript("return document.cookie");

for both above methods getting below error

getCookies:{}Could not retrieve cookies.
The most common cause of this error is
mismatch in the bitness between the driver and browser. In particular, be sure you are not
attempting to use a 64-bit IEDriverServer-exe against IE 10 or 11,
even on 64-bit Windows
```

### Operating System

Windows 10

### Selenium version

Java 1.8

### What are the browser(s) and version(s) where you see this issue?

Edge 101

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.0.0

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Closing as no more info was provided.
