### ISSUE TITLE
[🐛 Bug]: Capabilities issues with 4.1.5

### ISSUE THREAD

**Issue by adigaboy** [SeleniumHQ/selenium#10680]
### What happened?

Main issue for now is that I can't enable VNC with 4.1.5.

Old code working with 4.1.3 was using desired_capabilities, tried to use options but it doesn't work.

**4.1.3 code:**
```
capabilities = DesiredCapabilities.CHROME.copy()
capabilities['enableVNC'] = True
driver = webdriver.Remote(
    command_executor=self.selenium_remote_url,
    desired_capabilities=capabilities,
)
```

**4.1.5 code:**
```
options = webdriver.ChromeOptions()
options.set_capability("enableVNC", True)
driver = webdriver.Remote(
    command_executor=selenium_remote_url,
    options=options,
)
```

**Results:**
4.1.3: session created with VNC
4.1.5: session created without VNC

### How can we reproduce the issue?

```shell
options = webdriver.ChromeOptions()
options.set_capability("enableVNC", True)
driver = SelenoidRemote(
    command_executor=self.selenium_remote_url,
    options=options,
)
```

### Relevant log output

```shell
No vnc
```

### Operating System

Ubuntu 20

### Selenium version

4.1.5

### What are the browser(s) and version(s) where you see this issue?

any Chrome versions

### What are the browser driver(s) and version(s) where you see this issue?

all chrome versions

**Comment by titusfortner** [comment]
Selenium now only supports WebDriver specification compliant implementations. You need to ask the Selenoid project how to properly set their value.
