### ISSUE TITLE
[🐛 Bug]: Contained Firefox can't be used on MacOS

### ISSUE THREAD

**Issue by bogdancondurache** [SeleniumHQ/selenium#10686]
### What happened?

For the project https://github.com/robocorp/rpaframework/ we're installing an isolated Firefox and adding that to the path. But because as seen here https://github.com/SeleniumHQ/selenium/blob/dab928e6ac2c270b03d0199f381950c998c3f8b0/py/selenium/webdriver/firefox/firefox_binary.py#L152 the path for MacOS is hardcoded and not searched for in $PATH, Selenium will never find and use that version.

### How can we reproduce the issue?

```shell
Install Firefox on MacOS in a different path. Add it to the $PATH global variable and try to use Selenium against it. Selenium will fail, not being able to find Firefox.
```

### Relevant log output

```shell
SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary
```

### Operating System

MacOS Monterey 12.3

### Selenium version

3.141.0 (but based on the code seems like it should be on all versions)

### What are the browser(s) and version(s) where you see this issue?

Firefox 98, 99 and 100

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.30.0

**Comment by diemol** [comment]
You can always provide the path, if not provided, then the location you mention will be used.

```
- firefox_path - Path to the Firefox executable. By default, it will be detected from the standard locations.
```

**Comment by bogdancondurache** [comment]
@diemol Whilst I agree with you, I still think this is a bug. Why? Because some apps will be able only to setup the system properly (proper env vars, proper values and order of $PATH and so on) and not change the `firefox_path` value. Also, based on the docs you mentioned, by default it should `be detected from the standard locations`, which is clearly not the case because it is hardcoded. Hardcoding a path instead of using the usual means of finding an executable that everyone does, sounds like a bug. Specially when it's done just for MacOS.

**Comment by diemol** [comment]
Even if we rework the logic and follow your comments, or if we simply remove the path for macOS, GeckoDriver still will use this path as they know better the default locations. 

Also, which are these ones?
>by default it should be detected from the standard locations

**Comment by bogdancondurache** [comment]
> Even if we rework the logic and follow your comments, or if we simply remove the path for macOS, GeckoDriver still will use this path as they know better the default locations.

I'm not sure the problem is in GeckoDriver. This works well on Windows and Linux because (I assume) Gecko calculates the paths properly.
 
> Also, which are these ones?
> 
> > by default it should be detected from the standard locations

Usually the convention is to take each folder from `$PATH` in order and try to use the binary from there, that's why the order is important. From what I see, this is done by Selenium on Linux using the `which` method here: https://github.com/SeleniumHQ/selenium/blob/dab928e6ac2c270b03d0199f381950c998c3f8b0/py/selenium/webdriver/firefox/firefox_binary.py#L211

I think this should be the best approach for MacOS as well, if the binary couldn't be found in the path currently hardcoded:
https://github.com/SeleniumHQ/selenium/blob/dab928e6ac2c270b03d0199f381950c998c3f8b0/py/selenium/webdriver/firefox/firefox_binary.py#L153

**Comment by diemol** [comment]
Sounds good, would you like to send us a PR? Probably @symonk and @AutomatedTester can help us to review.

**Comment by symonk** [comment]
Most certainly a pull request would be useful, I'm not on my mac right now or I would investigate, we can `which firefox` perhaps to derive `start path` _if_ `firefox` is available on path but I have no idea if thats normal on OSX.

**Comment by diemol** [comment]
@bogdancondurache are you interested in sending a PR?

**Comment by bogdancondurache** [comment]
@diemol @symonk I was on vacation, here is the PR I think will fix this: https://github.com/SeleniumHQ/selenium/pull/10818
