### ISSUE TITLE
[🚀 Feature]: Add Pause action to C# API

### ISSUE THREAD

**Issue by sbMohammadUddin** [SeleniumHQ/selenium#10691]
### Feature and motivation

Unlike other languages, the C#/DotNet language API does not have the Pause method on the Actions class and the PauseInteraction is unable to be instantiated for use with the ActionBuilder class as it marked as internal. I believe this is an oversight and the API should have been included already.

### Usage example

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#pause(long)

**Comment by sbMohammadUddin** [comment]
In this other issue, it was promised that the API would get added however it never happened.
https://github.com/SeleniumHQ/selenium/issues/6528#issuecomment-429338800

**Comment by titusfortner** [comment]
You can add a Pause Interaction to an `ActionBuilder` instance yourself, but I'm actually right now working on making sure the Actions APIs are more consistent across the languages. Not sure if I'll get it all done in time for 4.2.

**Comment by titusfortner** [comment]
merged https://github.com/SeleniumHQ/selenium/commit/8977cf7dbfd2ae8cd303f960f830071b683c1d26
