### ISSUE TITLE
[🐛 Bug]: Same error with every new chrome version when using bidi_connection()

### ISSUE THREAD

**Issue by gromovoff** [SeleniumHQ/selenium#10699]
### What happened?

driver.bidi_connection() fails every time when new chrome version is released. I have opened this defect in the past. 

The line that is causing it is located under webdriver.py

devtools = import_module("selenium.webdriver.common.devtools.v{}".format(version))

Devtools module don`t seem to be updating fast enough. It is hard to use bidi_connection in a professional setting.
Currently it fails for chrome version 102

### How can we reproduce the issue?

```shell
Update chrome and webdriver to version 102. 
Run:
async with driver.bidi_connection() as bidi_session:
   session, devtools = bidi_session.session, bidi_session.devtools
```

### Relevant log output

```shell
ModuleNotFoundError
```

### Operating System

windows and mac os

### Selenium version

python

### What are the browser(s) and version(s) where you see this issue?

chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

102.0.5005

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
This is something we are getting better internally. It is tricky to release before a Chrome version comes out, but we are now doing our best to release a couple of days later at most. CDP support for Chrome 102 should come out tomorrow. I will close this issue when we do that.

**Comment by gromovoff** [comment]
@diemol there are no issues with java bindings. I believe that it falls back to a previous devtools version. can we have that too?

**Comment by symonk** [comment]
`102` looks supported in the upcoming `4.2` - We can definitely do more here; _trying_ `101` in this instance maybe wouldn't hurt? but it's still not ideal.

**Comment by titusfortner** [comment]
@gromovoff Java & .NET will use the closest supporting version it finds.
Ruby implements a separate gem so it can be released independent of Selenium itself.
Python & JavaScript are the two that are unfortunately needed in a timely fashion with current implementations.

**Comment by gromovoff** [comment]
yes, maybe we can try going up recursively and issue some sort of warning..

**Comment by gromovoff** [comment]
or... can we decouple devtools from bidi_session? This way I can try implementing messaging over sockets on my own.. without importing devtools module

**Comment by titusfortner** [comment]
devtools integration based on browser version is a temporary measure while we implement the BiDi spec https://github.com/w3c/webdriver-bidi.

@diemol we probably can at least look at what it would take for Python to be more permissive with versioning before closing this.

**Comment by symonk** [comment]
Hi @gromovoff Thanks! in `4.3` we will fall back to finding the `latest` version available that should stop this problem from constantly happening for now.

**Comment by gromovoff** [comment]
@symonk Thanks! I have also noticed that we are running cdp and webdriver on the same thread. My understanding is that blocking and non-blocking python code should be executed on separate threads ( this way we can listen to network events async in real time and still perform selenium tasks). Good example of that is in PyChrome repo. Would it make sense to create a new feature request? Thanks!!!

**Comment by symonk** [comment]
The async functionality of selenium in python land needs some improvements, I haven't got around to looking into it too much just yet (and won't for a little while) Any improvements there would be greatly welcomed in a pull request! to my knowledge we have some basic implementation(s) but would require some refactoring to support things better going forward.
