### ISSUE TITLE
[🚀 Feature]: Add support for Chromium's "preferCSSPageSize" to PrintOptions

### ISSUE THREAD

**Issue by redmist77** [SeleniumHQ/selenium#10692]
### Feature and motivation

This should be an easy addition.  It's just a PrintOption addition i.e. preferCSSPageSize true:false

### Usage example

This is useful when automating PDF creation.  It allows page sizing to be done in the CSS rather than hard-coding or via complex settings management.

**Comment by titusfortner** [comment]
Thanks for the suggestion.

If you look at the [chromedriver implementation](https://github.com/chromium/chromium/blob/main/chrome/test/chromedriver/window_commands.cc#L2305),
`preferCSSPageSize` is toggled when you set `shrinkToFit` to `false`, [which you can already do ](https://github.com/SeleniumHQ/selenium/blob/11647cc16596111f06d13b0e5f1bdf7e964ccba9/java/src/org/openqa/selenium/print/PrintOptions.java#L95)
