### ISSUE TITLE
[🐛 Bug]: unhandledPromptBehavior doesn't work

### ISSUE THREAD

**Issue by TBAIKamine** [SeleniumHQ/selenium#10690]
### What happened?

am using python 3.9.12 with pip 22.1.1

my localhost has an index.html file with only one line of code: `<script>alert("hi")</script>`

expected result is to have the above alert dissapear but it doesnt

### How can we reproduce the issue?

```shell
from selenium.webdriver import Chrome
from selenium.webdriver import ChromeOptions
from selenium.webdriver.chrome.service import Service
import time
options = ChromeOptions()
options.set_capability("unhandledPromptBehavior", "dismiss")
service = Service(executable_path="/usr/local/bin/chromedriver")
driver = Chrome(service=service,options=options)
driver.maximize_window()
driver.get("http://localhost:8888")
time.sleep(5)
driver.quit()
```

### Relevant log output

```shell
no output.
```

### Operating System

macos Montery 12.3.1

### Selenium version

4.1.5

### What are the browser(s) and version(s) where you see this issue?

chrome 101.0.4951.64 arm64

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 101.0.4951.41

### Are you using Selenium Grid?

no

**Comment by symonk** [comment]
The session response should include it being set correctly:

```console
...,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss",...
```

The prompt/alert handling will only fire when you try something while its `present` I think; e.g if you try to find an element after this it should work & dismiss, vs the default `dismiss and notify` which would subsequently raise a `UnexpectedAlertPresentException`
