### ISSUE TITLE
[🐛 Bug]: Sometimes application URL is not getting launched on Edge Browser with IEMode ,using Selenium Java

### ISSUE THREAD

**Issue by divya415** [SeleniumHQ/selenium#10707]
### What happened?

When I am launching my website using IE mode with IEDriver 4.0.0 , sometimes the application URL doesn't get launched the driver stucks displaying a blank page with message as "This is the initial start page for WebDriver Server" .
The issue exists even after killing browser and driver instances in Task Manager and deleting files in %temp% folder

Configurations:
Edge Version 101
IE Driver version 4.0.0 32 bit

Using below IEOptions:
 
InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
    Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
    ieOptions.attachToEdgeChrome();
    ieOptions.withEdgeExecutablePath("msedge.exe");     // Edge Browser directory path

    edgeIe11Options.introduceFlakinessByIgnoringSecurityDomains();
    edgeIe11Options.ignoreZoomSettings();
    edgeIe11Options.enablePersistentHovering();
    edgeIe11Options.takeFullPageScreenshot();
    edgeIe11Options.disableNativeEvents();
    edgeIe11Options.requireWindowFocus();
    edgeIe11Options.destructivelyEnsureCleanSession();

    edgeIe11Options.setCapability("ignoreProtectedModeSettings", true);
    edgeIe11Options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);

### How can we reproduce the issue?

```shell
No
```

### Relevant log output

```shell
No
```

### Operating System

windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge Browser 101 version with IEMode

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.0.0 

### Are you using Selenium Grid?

4.0.0-alpha-2

**Comment by titusfortner** [comment]
Se can't do anything about this without something we can reproduce.
You definitely need to upgrade your grid version, though.

**Comment by diemol** [comment]
Closing as no more info was provided.
