### ISSUE TITLE
CodeMirror: Element is not currently visible and so may not be interacted with

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#1070]
I am trying to drive the CodeMirror widget but it proves impossibile to enter any text into it because of the error "Element is not currently visible and so may not be interacted with".

CodeMirror is a javascript library to edit code in a browser window.

It makes quite an odd use of a textarea to allow the text to be input. The textarea is always available for input but the fxDriver extension isShown method doesn't think so. I think that method implements a strategy to figure out if the element is editable, but that strategy fails in this case.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ygmarchi** [comment]
Try the following test with webdriver, it reproduces the error.
Can you please reopen the issue?
Thanks, Carlo.

<pre>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://codemirror.net/" />
<title>code-mirror</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">code-mirror</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>https://codemirror.net/</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>css=div &gt; textarea</td>
	<td>something</td>
</tr>
</tbody></table>
</body>
</html>

</pre>
