### ISSUE TITLE
[🐛 Bug]: Tab cannot be switched in IE compatibility mode of edge.

### ISSUE THREAD

**Issue by accamo** [SeleniumHQ/selenium#10701]
### What happened?

When I try to switch tab with driver.switchTo().window() at IE compatibility mode of edge,it doesn't work.

It worked using chrome and edge.

### Detail

Currently, we are testing an application that requires tab switching using Edge IE mode.

Using driver.switchTo().window() code only changes the focus of the program.

During runtime, we observed that the above code does not change the focus of the screen.

We have come up to the solution of using driver.switchTo().window() and send key (CTRL + Tab) to switch both program and screen focus. However, since send keys are unstable (not returning any indication whether it successfully switched tab or not), we would like to know is it possible to have the driver.switchTo().window() code support both program and screen focus switch for Edge IE mode? Is it expected that driver.switchTo().window() only supports program focus?

Regarding tab and window, are there assurances that there is no difference in terms of data, function and control between window and tab?

### Relevant log output

```shell
nothing
```

### Operating System

Windows 10

### Selenium version

selenium 4.1.2, java 11

### What are the browser(s) and version(s) where you see this issue?

edge 101.0.1210.53

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.0.0

**Comment by titusfortner** [comment]
I think this is a duplicate of #8868
The fix will be in IE Driver 4.2 which should be released very soon.

**Comment by accamo** [comment]
> 

@titusfortner  Thank you!
But the problem here seems different.
 I can get the correct handles in the program, but the focus did not change to the tab I wanted.
 I have provided additional explanation in the ticket description.

just in case, my driver configuration:
```shell
driver = {
			System.setProperty("webdriver.ie.driver", "./src/test/resources/driver/IEDriverServer.exe")
			InternetExplorerOptions options = new InternetExplorerOptions()
            options.requireWindowFocus()
			options.attachToEdgeChrome()
			options.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe")
			def driver = new InternetExplorerDriver(options)
			driver.manage().window().maximize()
			driver}
```

**Comment by diemol** [comment]
If the issue is different, then we need more information, please see below.

**Comment by titusfortner** [comment]
Please try with latest IE Driver v4.2

**Comment by accamo** [comment]
@diemol 
I'm sorry because there are so many packages and the code can't be exposed.
when using the IE compatibility mode of edge, clicking the link will open a new tab. 
when switch tab，
The window switching is also successful in the background(java test), but the focus of the actual screen focus is not switched.

**Comment by accamo** [comment]
@titusfortner 
Sorry, this problem still exists. 
Is it because ie11 uses window instead of tab when using webdriver control?

**Comment by diemol** [comment]
Without a way to reproduce it we cannot tell if it is a Selenium issue or an issue in the IE mode of Edge. It does not need to be the same code you use internally, but something we can use to reproduce the issue.

**Comment by sargis-tovmasyan** [comment]
I am not able to test it on 4.2.0 because webdriver is stuck on the initial page and doesn't do anything...
but 4.0.0 has this issue
just create the driver open a new tab then try to switch back to the first tab (programmatically it is happening because I can run tests on the first tab but visually I cant see that tab was switched ...)

Try this  to reproduce (Nuget versions: 4.0.0, IEDriverServer version: 4.0.0)

### C#
```csharp
var service = InternetExplorerDriverService.CreateDefaultService(DRIVER_DIRECTORY, DRIVER_NAME);
var ieOptions = new InternetExplorerOptions()
{
    PageLoadStrategy = PageLoadStrategy.None,
    Proxy = null,
    AttachToEdgeChrome = true,
    EdgeExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" //Default installation path...
};

var webDriver = new InternetExplorerDriver(service, ieOptions);

webDriver.Navigate().GoToUrl("http://bing.com");
var firstHandler = webDriver.CurrentWindowHandle;
webDriver.SwitchTo().NewWindow(WindowType.Tab);
webDriver.Navigate().GoToUrl("http://google.com");
webDriver.SwitchTo().Window(firstHandler);

//Automation on first page
var searchTextBox = webDriver.FindElement(By.Id("sb_form_q"));
var searchButton = webDriver.FindElement(By.Id("search_icon"));
searchTextBox.SendKeys("Test");
searchButton.Click();

```
### Demo:
![demo_switchTab_issue](https://user-images.githubusercontent.com/35834865/171832159-8bfcc524-3f71-4059-9e52-83f9c92edbd5.gif)

**Comment by titusfortner** [comment]
We can't do anything about 4.0, we can only fix problems in 4.2, so let's figure out why you can't get 4.2 working. What error do you get? What code are you using to start it?

**Comment by sargis-tovmasyan** [comment]
> We can't do anything about 4.0, we can only fix problems in 4.2, so let's figure out why you can't get 4.2 working. What error do you get? What code are you using to start it?

Тhe same code as shown above! but with updated NuGet "WebDriver" and IEDriverServer.exe (both 4.2.0)
No errors/exceptions... only timeout error after 60 seconds (expected).

![demo_4 2 0_start_issue](https://user-images.githubusercontent.com/35834865/172550006-1fcdccd8-ab64-4b44-a086-19831e1f4a52.gif)

**Comment by diemol** [comment]
Can you please try what the Edge team suggests when opening new windows and then report back?
https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#opening-new-windows

**Comment by sargis-tovmasyan** [comment]
> Can you please try what the Edge team suggests when opening new windows and then report back? https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/ie-mode?tabs=c-sharp#opening-new-windows

The issue is not in opening a new tab, the issue is in switching between opened tabs!

**Comment by sargis-tovmasyan** [comment]
UPD: running 4.2.0 from the %SOLUTION_DIR%/bin/Debug folder works! 
Result: Tab not switched!

![demo_4 2 0_start_issue_3](https://user-images.githubusercontent.com/35834865/172621703-af50d03b-550f-4afb-ae0f-8d8f41e7ed18.gif)

No error messages on the command line interface ...

**Comment by Saqo1995s** [comment]
> @diemol I'm sorry because there are so many packages and the code can't be exposed. when using the IE compatibility mode of edge, clicking the link will open a new tab. when switch tab， The window switching is also successful in the background(java test), but the focus of the actual screen focus is not switched.

same for .NET

**Comment by sargis-tovmasyan** [comment]
@diemol, @titusfortner  is there any update on this?

**Comment by diemol** [comment]
I was troubleshooting this on my Windows machine and I was able to reproduce it. Somehow IEDriver does not switch back to the initial window handle. Here is the code I was using, also following the recommendation from the docs in Edge.

```csharp
        static void Main(string[] args)
        {
            var ieOptions = new InternetExplorerOptions()
            {
                PageLoadStrategy = PageLoadStrategy.None,
                Proxy = null,
                AttachToEdgeChrome = true,
                EdgeExecutablePath = @"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
            };

            var webDriver = new InternetExplorerDriver(ieOptions);
            webDriver.Navigate().GoToUrl("http://bing.com");
            var firstHandler = webDriver.CurrentWindowHandle;
            webDriver.SwitchTo().NewWindow(WindowType.Tab);
            webDriver.Navigate().GoToUrl("http://google.com");
            webDriver.SwitchTo().Window(firstHandler); // Does not go to the initial window handle.
            Console.WriteLine(webDriver.WindowHandles.Count);
            webDriver.SwitchTo().Window(firstHandler);
            var newWindowHandle = webDriver.CurrentWindowHandle;
            Console.WriteLine("First handle: " + firstHandler);
            foreach (string window in webDriver.WindowHandles)
            {
                Console.WriteLine("Handle: " + window);
                if(newWindowHandle != window)
                {
                    webDriver.SwitchTo().Window(window);
                    break;
                }
            }
            Thread.Sleep(5000);

            //Automation on first page
            //var searchTextBox = webDriver.FindElement(By.Id("sb_form_q"));
            //var searchButton = webDriver.FindElement(By.Id("search_icon"));
            //searchTextBox.SendKeys("Test");
            //searchButton.Click();

            webDriver.Quit();
        }
```

There is not much we can do at the Selenium project since the Edge folks are the ones who are kindly helping to maintain the IEDriver. Please report this issue to their team. I will leave the links to report it below.
