### ISSUE TITLE
[🐛 Bug]: ruby 2.7.5 got status code 500 (Selenium::WebDriver::Error::ServerError)

### ISSUE THREAD

**Issue by RayChenLDL** [SeleniumHQ/selenium#10718]
### What happened?

I am using ruby 2.7.3 and watir 7.1.0, trying to run the ui test on the selenium grid 4 (4.0.0-beta-3-prerelease-20210402);

I started the selenium grid 4 with all the docker containers, including selenium hub and chrome & edge nodes. they are setup very well;

with my ruby, I am trying to open a new browser:
$browser = Watir::Browser.new :"chrome", :url => "http://localhost:4444/wd/hub"

then got the error:
**status code 500 (Selenium::WebDriver::Error::ServerError)**

### How can we reproduce the issue?

```shell
Run the commands below to spin up selenium grid 4:
docker network create nut

docker run -d -p 4442-4444:4442-4444 --network nut --name selenium-hub selenium/hub:4.0.0-beta-3-prerelease-20210402

docker run -d -p 5901:5900 --network nut --name selenium-chrome -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome:4.0.0-beta-3-prerelease-20210402


docker run -d -p 5902:5900 --network nut --name selenium-edge -e SE_EVENT_BUS_HOST=selenium-hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-edge:4.0.0-beta-3-prerelease-20210402

then with ruby:
$browser = Watir::Browser.new :"chrome", :url => "http://localhost:4444/wd/hub"
```

### Relevant log output

```shell
status code 500 (Selenium::WebDriver::Error::ServerError)
```

### Operating System

Windows10

### Selenium version

ruby 2.7.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 101.0.4951.6

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 101.0.4951.6

### Are you using Selenium Grid?

selenium grid 4.0.0-beta-3-prerelease-20210402

**Comment by diemol** [comment]
Can you please try with the most recent release -> https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.2.1-20220531
Just pointing that out because Chrome 101.0.4951.6 is not available in 4.0.0-beta-3-prerelease-20210402

If the issue still persists, please share the Docker container logs, for both Hub and Nodes

**Comment by RayChenLDL** [comment]
@diemol thanks for quick response. As you advised, I setup the selenium grid using 4.2.1-20220531. Got the new error as below.
![image](https://user-images.githubusercontent.com/40652062/171390907-571290f8-b591-4c9b-921f-6e6698ee74be.png)

**Comment by RayChenLDL** [comment]
after adding args of '--disable-dev-shm-usage', it is working well. thanks anyway.

**Comment by diemol** [comment]
Ah ok, the issue is that you are not adding `shm` to the start command.
>☝️ When executing docker run for an image that contains a browser please use the flag --shm-size=2g to use the host's shared memory.

**Comment by RayChenLDL** [comment]
With selenium grid [4.2.1-20220531], my test is running well on chrome node and firefox node, but got the error below for edge. Even I use the flag --shm-size=2g to use the host's shared memory.

![image](https://user-images.githubusercontent.com/40652062/171556840-303c823d-755f-412d-867e-ac7acc0b569e.png)

**Comment by RayChenLDL** [comment]
Could you re-open this ticket and have a look at the edge node?
