### ISSUE TITLE
[🐛 Bug]: Status endpoint

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10725]
### What happened?

Someone pointed out that I incorrectly removed status endpoint from Python (still supported https://w3c.github.io/webdriver/#status). I removed it because no method was calling it. Need to make sure all the languages have methods that can call this endpoint. Don't have time to investigate now and don't want to forget.

### How can we reproduce the issue?

```shell
driver.status
```

### Relevant log output

```shell
none
```

### Operating System

n/a

### Selenium version

latest

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
Can you share the link from the previous implementation?

In practice, having a `/status` endpoint call on the client side only makes sense for a `RemoteWebDriver`. But the way the clients are implemented, it means that a session needs to exist to us a `RemoteWebDriver` instance. Perhaps it needs to be a static call?

**Comment by pujagani** [comment]
@diemol I think you are right. Based on what I understand from https://w3c.github.io/webdriver/#status. This endpoint is not dependent on any pre-existing session. This command seems to be like a check before creating a session. A static call seems like a proper fit here.

**Comment by symonk** [comment]
I revisited a naive draft I looked into (was just following the spec verbatim but I think yes it should be some sort of static call

**Comment by pujagani** [comment]
I was looking into how to implement this in Java binding. To add to Diego's point, the implementation has all details like the remote server URL (webdriver URL) only when an instance is created. Without that information, making a call to the remote end (webdriver) to get the status is not possible. Hence, implementing a static method that is available for end-users to use does not seem possible. 
Additionally, if the method is available as a non-static method, the session will be created prior to that. If session creation fails we throw an error. So the user will be unable to use status at that point. Leaving the only chance to use the status API when session creation was successful. I might be missing use cases where this is needed. But based on my understanding, the status endpoint is useful for session creation, and in our case, we do that when creating a driver instance. 
Appreciate any thoughts on how can we proceed or the need for a user-facing status API.

**Comment by diemol** [comment]
As a first implementation, I would add the static call as `RemoteWebDriver.status(URL)`. Yes, the user would need to provide the URL again when the driver is actually created. But then they could use the return value to be sure the remote end point is ready to receive requests.

**Comment by pujagani** [comment]
Thank you so much, Diego. RemoteWebDriver methods are inherited by browser-specific driver implementations (ChromiumDriver, SafariDriver, FirefoxDriver). In that cases, where the driver service is created by Selenium, users will not have access to the remote URL before the instance is created. How should we handle that?

**Comment by diemol** [comment]
I think using the `/status` endpoint only makes sense in the `RemoteWebDriver` scenario because browser specific drivers are already taking care of starting the driver locally.

The scenario would be something like:
- User wants to start a session in a Grid or cloud service.
- Queries the `/status` endpoint
- If `ready: true` is returned, then start the session

**Comment by pujagani** [comment]
This gives me a better idea of the usage. Thank you so much! https://w3c.github.io/webdriver/#dfn-remote-ends also helped me understand a few teams around this and we already have it implemented in Grid (intermediary node)!

**Comment by titusfortner** [comment]
So... theoretically, users should be able to start a service on a specific port and create/end sessions without quitting the service. It isn't how we've implemented the code for most of the languages/browsers, but @symonk and I noticed that it was an option for Safari in Python, and it kind of makes sense to support it across the board.

So I see this feature as being the first step to supporting that feature, but it does mean it needs to work for more than just RemoteWebDriver. (I haven't looked at @pujagani's PR closely enough to know, just the test that focused on the Grid).

**Comment by diemol** [comment]
JS also was having a single service to create all Chrome sessions, but some drivers support more than one concurrent session. I do not see the benefit of the local use case, given the way we manage session creation, which is a driver per session.

**Comment by pujagani** [comment]
@titusfortner What you suggested is possible because of the way the WebDriver interface and RemoteWebDriver class are designed in the Java bindings. Since all driver classes inherit RemoteWebDriver, they have access to the static status endpoint as long as the service URL is provided.  

```
ChromeDriverService service = new ChromeDriverService.Builder()
      .usingAnyFreePort()
      .build();

service.start();

Status status = ChromeDriver.status(service.getUrl());

if (status.isReady()) {
   ChromeDriver driver = new ChromeDriver(service);
   driver.get("http://google.com");
   driver.quit();
}

service.stop();
```
I will try and add a test to showcase this.
However, C# implementation is slightly different and the PR changes only allow status API to be accessed from RemoteWebDriver. Once, we reach a consensus about how we want to access it, it can be easily updated.

**Comment by titusfortner** [comment]
> single service to create all Chrome sessions

This isn't the use case I'm thinking either.

Default is killing the driver process when Selenium sends the quit command to the driver.

Optionally you start the service with a keep alive parameter. This decouples the session from the service. It would speed up safari, IE and Chrome when running consecutive tests, and I'm not sure the impact on Firefox. Tbh, this is the kind of thing that would be interesting as an exercise for new selenium contributors....

**Comment by titusfortner** [comment]
I should note that to use the existing service, you'd need to pass in the url/port to a service object.

**Comment by diemol** [comment]
Right, and we have gotten reports of users trying to use `RemoteWebDriver` with a URL to a running local service, and we recommend them to use the current functionality.

I guess there are use cases where including the local execution scenario is valid, but I believe the sound more like experiments than a real use case for now. Which is why I think having an implementation to check status for remote Grid is what we should implement at the moment.

**Comment by titusfortner** [comment]
Well, this issue was created because there is a valid w3c endpoint that isn't supported by the Selenium bindings. It is valid for the drivers locally the same way it is for Grid. Selenium should provide access to it, regardless of how people choose to use it.

**Comment by diemol** [comment]
You are right, the spec talks about "remote ends", so this applies to drivers in local executions as well. Do we need to go through all the complexity of adding the local use case in all bindings now?

**Comment by titusfortner** [comment]
We don't need to do anything right now, just saying that if we are implementing something, it might make sense to ensure it works both locally and remotely, even when the use case is more obvious for remote.

**Comment by diemol** [comment]
After discussing this in the wider committer group, and considering the initial motivation plus evaluating the value this adds, we all decided to not include this across all bindings. 

I've reverted the change done to the Java bindings, and I will close the .NET pull request.
