### ISSUE TITLE
[🐛 Bug]: Deprecation warning

### ISSUE THREAD

**Issue by erdoganb** [SeleniumHQ/selenium#10720]
### What happened?

Hello,
i was parsing some html with PYTHON. Ive encountered some warning.
Actually my parser is working good, bu in terminal, suggests to change them to newers.
And it is same on documentation.
First ive done it by documentation but, tried some code of older posts in web.
So

What browsers and operating systems are you seeing the problem on?

windows 10, chrome browser 102.0.5005.63.

### How can we reproduce the issue?

```shell
(Altough im not sure if im doing sth wrong but...)
When i follow the instructions on the terminal, it DOES NOT work.
I am using selenium 4.2.0.
using webdriver as chromedriver.
```

### Relevant log output

```shell
these are the lines on terminal

...in.py:11: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
username = driver.find_element_by_id('username')

...in.py:13: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
password = driver.find_element_by_id('password')

...in.py:15: DeprecationWarning: find_element_by_class_name is deprecated. Please use find_element(by=By.CLASS_NAME, value=name) instead
```

### Operating System

Windows 10

### Selenium version

4.2.0

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome browser 102.0.5005.63.

**Comment by titusfortner** [comment]
What are you trying that isn't working? We can't help you without more specifics.

**Comment by symonk** [comment]
@erdoganb you are finding elements using `find_element_by_*` methods; these will no longer be available in `4.3` and you should move to `find_element(...)` instead (and its plural `find_elements` counterpart).  Please share some example code of what you are doing and I will assist

**Comment by erdoganb** [comment]
hello @symonk, im saying that:
i can do some stuff with by using #find_element_by_id('username')#
i can NOT do the same stuff by using #find_element(By.ID, value='username')#

Actually, in the terminal warns me for the use of new methods, but new methods are not working in my data.

**Comment by titusfortner** [comment]
how is it not working? Are you getting an error? What error? Do you have code we can execute to reproduce it? Everything is working fine in our tests, so we need more information to know what might be different with your situation.

**Comment by erdoganb** [comment]
from selenium import webdriver
import time

page = webdriver.Chrome("C:\WebDriver\chromedriver")

page.get('https://linkedin.com/uas/login')

time.sleep(4)

page.find_element(by=by.ID, value="username").send_keys("test@mail.com")

page.find_element(By.ID, "password").send_keys("123123123" + Keys.ENTER)

this is my exact code, note that either of the last 2 rows are not working.
What am i doing wrong?

and this is on the terminal

File "c:\erdo-dev\python\deneme-yanılma\selenium-deneme.py", line 13, in <module>
    page.find_element(by=by.ID, value="username").send_keys("test@mail.com")
NameError: name 'by' is not defined


------
ive tried with by, BY, By
same result every time

**Comment by symonk** [comment]
you need to import:

```python
from selenium.webdriver.common.by import By
```
