### ISSUE TITLE
[🚀 Feature]: Default IE Options to use IE Mode in Edge

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#10729]
### Feature and motivation

Microsoft is deprecating IE soon, and based on this post https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection, any usage of IE will be launching Edge instead.

Should IE Options to have these options by default?

```java
ieOptions.attachToEdgeChrome();
ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
```

### Usage example

Instead of 

```java
public class IEDriverSample {
    public static void main(String[] args) {        
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        ieOptions.attachToEdgeChrome();
        ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        
        WebDriver driver = new InternetExplorerDriver(ieOptions);

        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("WebDriver", Keys.RETURN);

        driver.close();
    }
}
```

Have this using IE Mode in Edge by default.

```java
public class IEDriverSample {
    public static void main(String[] args) {        
        WebDriver driver = new InternetExplorerDriver(new InternetExplorerOptions());

        driver.get("http://www.bing.com");
        WebElement elem = driver.findElement(By.id("sb_form_q"));
        elem.sendKeys("WebDriver", Keys.RETURN);

        driver.close();
    }
}

**Comment by titusfortner** [comment]
We can also set this in the IEDriver instead of/in addition to?

**Comment by mirci0ne** [comment]
Will be a good idea to have this options by default to launch directly the Edge with Internet Explorer mode set ON or OFF, also will be very useful this option to pass more easy capabilities, plus Edge will be more near to the real setups.
Another remark I saw in Windows, Selenium Edgedriver with IE mode is using settings from Internet Explorer like Windows policies maybe will be a good idea to use settings from Edge for Windows ?

**Comment by titusfortner** [comment]
If we merge #10938  it will satisfy what this Issue is requesting without us needing to change Options code.

I was also wondering if we want to go a step further and do this:

```java
WebDriver driver = new EdgeDriver(new InternetExplorerOptions());
```

On the one hand it isn't an actual Edge Driver, but on the other, it is confusing to specify InternetExplorerDriver and get an Edge browser.

**Comment by pujagani** [comment]
https://github.com/SeleniumHQ/selenium/issues/10600 might be a concern related to this issue

**Comment by titusfortner** [comment]
Ok, we decided that we should not change the bindings code if #10938 works as expected.
If IEDriver automatically redirects to Edge on the Machine, then IE Driver will use Edge by default without the user needing to specify anything in capabilities.

If IEDriver and Edge are both installed, the current options will continue to work for the time being. At some point I think IEDriver will stop supporting standalone IE entirely.

I'll keep this open in case the PR isn't merged and we need another solution.

**Comment by titusfortner** [comment]
@pujagani I don't see how 10600 should affect this, am I missing something?

**Comment by pujagani** [comment]
Thank you, Titus. After the details shared by you, I don't think it is a concern.

**Comment by titusfortner** [comment]
This has been merged for next release of IE Driver
