### ISSUE TITLE
[🐛 Bug]: loading 2 or more UNPACKED chrome extensions using Selenium and python loads only last one

### ISSUE THREAD

**Issue by meeffe** [SeleniumHQ/selenium#10728]
### What happened?

I tried to load 2 (or more) UNPACKED chrome extensions using Selenium and python 3.10. Selenium loaded only the last one instead of 2.

### How can we reproduce the issue?

```shell
Below code adds only the last extension so one extension is added instead of two. SO this line is executed only:


options.add_argument("load-extension=/Users/path/Downloads/python/proj/folder/ext_2_folder")
```

Full code to reproduce the issue:

```

from selenium.webdriver.chrome.service import Service
from selenium import webdriver

options = webdriver.ChromeOptions()

options.add_argument("load-extension=/Users/path/Downloads/python/proj/folder/ext_1_folder")
options.add_argument("load-extension=/Users/path/Downloads/python/proj/folder/ext_2_folder")
s = Service('/Users/path/Downloads/python/proj/folder/chromedriver')

driver = webdriver.Chrome(service=s, options=options)
driver.get("chrome://extensions")

```
```


### Relevant log output

```shell
no output
```

### Operating System

macos monterey

### Selenium version

4.1.5

### What are the browser(s) and version(s) where you see this issue?

I tested on Chrome 102 (newest one)

### What are the browser driver(s) and version(s) where you see this issue?

102.0.5005.61

### Are you using Selenium Grid?

no

**Comment by meeffe** [comment]
any quick workaround on this?

**Comment by titusfortner** [comment]
Don't use the add argument to set extensions, use the extension method on the chrome options class instead.

**Comment by meeffe** [comment]
@titusfortner no. It does not work that way (or I am missing something)

When I try to load UNPACKED extensions using 

```
options.add_extension("/Users/path/Downloads/python/proj/folder/ext_1_folder")
options.add_extension("/Users/path/Downloads/python/proj/folder/ext_2_folder")

```
I am getting the following error
```
file_ = open(ext, 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/Users/path/Downloads/python/proj/folder/ext_1_folder'
```

So it does work with straight .crx extensions but does not work with UNPACKED ones.

(or give me a proper code please)

In this specific scenario I have to use unpacked extensions and Selenium should allow to do that

**Comment by titusfortner** [comment]
This should work, but I haven't looked at it on python. I'll reopen and evaluate. Thanks.

**Comment by symonk** [comment]
I think `add_extension` might require a `.crx`? I did have a look into this using 2 placeholder extensions in `/tmp` (with a simple manifest/html setup) and like you report; when hitting the `chrome://extensions` there is only one shown

**Comment by meeffe** [comment]
thats the way of adding multiple unpacked extensions:

```
options.add_argument("load-extension=/path_to_folder_1,/path_to_folder_2")
```
topic closed.
