### ISSUE TITLE
[🐛 Bug]: Test using keyboard tabbing runs endlessly without failing (C# specflow, selenium 4.2.0)

### ISSUE THREAD

**Issue by Wanizame18** [SeleniumHQ/selenium#10722]
### What happened?

Since installing the package (selenium.webdriver net bindings for the SW API) I have a test which uses the below code to tab through a page of elements, since the update to 4.2.0 it no longer tabs beyond the first element on the page and it does not time out like other steps but stalls endlessly.  If i go back to the previous version the step runs in a second with no issues. 

	When I use the "Tab" key on my keyboard to reach "Change Password" - **stalls here**
	And I press "Enter"
	And I am taken to the "Change Password" page
	
Apologies If i am missing something obviously I am relatively new to automation and coding and still trying to find my bearings. 	

### How can we reproduce the issue?

```shell
Actions act = new Actions(driver);
            act.SendKeys(Keys.Tab);


            IWebElement elem = null;

            do
            {
                act.Perform();
                elem = driver.SwitchTo().ActiveElement();
                Debug.WriteLine("Text from an element: " + elem.Text);

            }
            while (!elem.Text.Contains(elementName));

        }
```

### Relevant log output

```shell
no log output
```

### Operating System

Windows 10

### Selenium version

C# 

### What are the browser(s) and version(s) where you see this issue?

CHROME 102

### What are the browser driver(s) and version(s) where you see this issue?

SELENIUM.WEBDRIIVER 4.2.0

**Comment by titusfortner** [comment]
I can't duplicate your issue. I can use Actions to send a tab to move from one field to another with .NET in Selenium 4.2.

Is there a reason you are using Actions class for this?
Looping while sending a TAB key seems inherently brittle since you can't be assured of starting in a known state.

What version were you using previously where it worked?

**Comment by diemol** [comment]
Closing as no more input was provided.

**Comment by Wanizame18** [comment]
Hi Apologies for not responding, I had an unfortunate life event which took me away from work for the last couple of weeks.  thank you for all your feedback.  I will amend my scripts and try again, thank you for looking into the issue.
