### ISSUE TITLE
[🐛 Bug]: Commands with waiting fail on the last Chrome version

### ISSUE THREAD

**Issue by SergeyKhmel11** [SeleniumHQ/selenium#10721]
### What happened?

I click on 'Sign in'-button in my register form. After that I need to check, that element appears on the page (e.g. User Name)
I set the [wait for element present]-command after the command [click]:[sign-in-button]. Next step is page refresh. After that the [wait for...] command fails

### How can we reproduce the issue?

```shell
Create a test-case using [wait for element present]-command after page update.
```

### Relevant log output

```shell
-
```

### Operating System

MAC OS Monterey 12.4

### Selenium version

3.17.2

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 102.0.5005.61 (Official Build) (x86_64)

### What are the browser driver(s) and version(s) where you see this issue?

Version 102.0.5005.61 (Official Build) (x86_64)

### Are you using Selenium Grid?

No

**Comment by symonk** [comment]
which language are you using? please share some example code, a vague report like this is impossible to help you at all.

**Comment by diemol** [comment]
Closing as we did not get more information.
