### ISSUE TITLE
[🚀 Feature]: ErrorInResponseException

### ISSUE THREAD

**Issue by DoTheBestMayB** [SeleniumHQ/selenium#10736]
### Feature and motivation

ErrorInResponseException supported by selenium 3.141.0

### Usage example

I used selenium 3.141.0

ErrorInResponseException occurred when response was delayed due to a large number of users on the site.
So I made good use of this exception.

An IDE say that ErrorInResponseException has been lost since recently migrated to selenium 4.2.0.
I found that it was deleted due to this issue https://github.com/SeleniumHQ/selenium/issues/7134

I can't find exception that replaces ErrorInResponseException at Selenium 4 documentation, so could you please support ErrorInResponseException again?

**Comment by symonk** [comment]
@DoTheBestMayB I'm going to assume you are using the python bindings; please share some example code that you are using to catch this particular exception, looking at the thread it was removed as 'dead code' - potentially incorrectly if your case is valid.

**Comment by DoTheBestMayB** [comment]
@symonk Yes python, and I use like below


```python
while True:
    try:
        element = driver.find_element(by=By.XPATH, value='//*[@id="someID"]')
        driver.execute_script("arguments[0].click();", element)
        break
    except (NoSuchElementException, ErrorInResponseException):
        if "Success" in driver.current_url:
            break
        else:
            time.sleep(5)
```

**Comment by symonk** [comment]
@DoTheBestMayB I don't think `ErrorInResponseException` was ever thrown here? `NoSuchElementException` is likely sufficient.

**Comment by diemol** [comment]
That error type is not a W3C WebDriver supported one, https://www.w3.org/TR/webdriver1/#handling-errors, which is another strong reason to remove it.

**Comment by DoTheBestMayB** [comment]
@symonk I've never experienced an `ErrorInResponseException` before, and I can't reproduce the error because I can't create a server lack.

`NoSuchElementException` can't catch exception, exception backtrace say `ErrorInResponseException` is occured.
`ErrorInResponseException` occurs when a response delay occurs due to a severe server rack.

@diemol Then what is the replacement for `ErrorInResponseException`?

**Comment by diemol** [comment]
`ErrorInResponseException` was most likely never used because WebDriver has no mechanism to check how many users are present on the site and if this is causing delays on the response. Those metrics are specific to each environment and application. That is why there is no replacement and, as @symonk says, `NoSuchElementException` should be sufficient for the context you describe.
