### ISSUE TITLE
[🚀 Feature]: Replace HTTP Client in Java

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#10730]
### Feature and motivation

The client we currently use seems to be unmaintained https://github.com/AsyncHttpClient/async-http-client

### Usage example

After checking for a while, this one seems to be a good replacement. 
https://github.com/reactor/reactor-netty

Open to other alternatives though. 

Ideally, we will add more details below about the implementation steps.

**Comment by joerg1985** [comment]
Hi,

we did replace the AsyncHttpClient with the Java 11 HttpClient here at work, to get rid of this dependency.
The requirements of Selenium are also Java 11, so there is no need for a additional dependency.

As far as i can remember this was a small change (a class with less than 200 lines of code) and it is working well for us.
Are you interrested in this, i could give a try with a PR in middle of june?

Kind regards
Jörg

PS: we only changed it on the client side, i am not sure if the server is using this too.

**Comment by diemol** [comment]
Selenium still supports Java 8, otherwise we would have moved to the Java 11 HttpClient.

Another path for this is, maybe, to set a date to stop supporting Java 8 and then move to the client in Java 11.

**Comment by titusfortner** [comment]
If the Java 11 one works for what we need that seems like by far the best approach since it will continue to be supported

**Comment by pujagani** [comment]
+1 If plan to support Java 11, then that might be the best way forward.

**Comment by joerg1985** [comment]
This branch has a java 11 based HttpClient implementation, in case you decide to update to java 11:
https://github.com/joerg1985/selenium/tree/java-11-http-client

To make it build the java release version in .bazelrc has to be changed from 8 to 11.
To use the client set the webdriver.http.factory property to "java11".

Kind regards
Jörg

**Comment by pujagani** [comment]
Adding the Java 11 client changes made by Simon for reference https://github.com/SeleniumHQ/selenium/commit/9b012df78dbbfd84d8fef06308f40fbf6a29455b

**Comment by diemol** [comment]
Closing this as we have the new client https://www.selenium.dev/blog/2022/using-java11-httpclient/
