### ISSUE TITLE
[🐛 Bug]: `getText()` returns inconsistent result across browsers when element text contains redundant whitespaces

### ISSUE THREAD

**Issue by tim-yao** [SeleniumHQ/selenium#10735]
### What happened?

`getText()` returns inconsistent result when element text contains redundant whitespaces.

For example, on a webpage, we have HTML like this:
```
<p id="test-double-whitespaces">
 Test  text
</p>
<p id="test-whitespaces">
 Here is  some   text   I      wrote   
</p>
```
We have more than one whitespace in the text. In most browsers, like Chrome and Safari, the redundant whitespaces will be removed when the HTML gets rendered. However, if we use the selenium webdriver `getText()` command to get the text value, I will get inconsistent results.

In chromedriver, I get no redundant whitespaces:
```
Test text
Here is some text I wrote
```
In safari driver, I get the original text with all whitespaces:
```
 Test  text


 Here is  some   text   I      wrote  
```

### How can we reproduce the issue?

```shell
I have setup a test content: https://jsfiddle.net/tyao/o0v8jywm/1/

Run below code:

const {Builder, Browser, By, Key, until} = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const safari = require('selenium-webdriver/safari');

(async function example() {
    const serviceS = new safari.ServiceBuilder('/usr/bin/safaridriver');
    let driverS = await new Builder().forBrowser(Browser.SAFARI).build();
    console.log('Safari ===========================================================');
    await getResult(driverS);

    const serviceC = new chrome.ServiceBuilder(require('chromedriver').path);
    let driverC = await new Builder().forBrowser(Browser.CHROME).build();
    console.log('Chrome ===========================================================');
    await getResult(driverC);
})();

async function getResult(driver) {
    try {
        await driver.get('https://jsfiddle.net/tyao/o0v8jywm/1/');
        await driver.switchTo().frame('result')
        let text1 = await driver.findElement(By.css('#test-double-whitespaces')).getText();
        let text2 = await driver.findElement(By.css('#test-whitespaces')).getText();
        console.log(text1)
        console.log(text2)
      } finally {
        await driver.quit();
      }
}
```

You should see output:
```
Safari ===========================================================

 Test  text


 Here is  some   text   I      wrote   

Chrome ===========================================================
Test text
Here is some text I wrote
```
```
```

### Relevant log output

```shell
No error log
```

### Operating System

macOs Monterey

### Selenium version

JavaScript v4.2.0

### What are the browser(s) and version(s) where you see this issue?

Safari Version 15.4 (17613.1.17.1.13)

### What are the browser driver(s) and version(s) where you see this issue?

Safari 15.4 (17613.1.17.1.13)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Text method is supposed to render what the user sees on the page. This is a known safari bug. We should probably add a test in wpt to track it

**Comment by tim-yao** [comment]
Thanks, @titusfortner. As you mentioned that it's a known Safari bug, I shouldn't create a new issue in Safari I guess. Do you have a link to the Safari bug? I am new in this area, it can save some of my time. I am happy to have a look and follow up with the Safari team. Cheers!

**Comment by diemol** [comment]
Link to create a bug report with them is above your comment.

**Comment by tim-yao** [comment]
> Link to create a bug report with them is above your comment.

Hi @diemol. Thanks for the help. Sorry, I was asking for the known bug link. 
To solve the problem, I know the link to create a new bug report, but I don't think I should create a new bug if there is an existing bug already?

**Comment by diemol** [comment]
Good point. I do not have the link but I believe it is possible to search in their bug tracker.
