### ISSUE TITLE
[🚀 Feature]: Add a codecov badge to the repository

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#10738]
### Feature and motivation

There is a codecov check that happens for some of the code. I think it would be good to see the percent code coverage on the main page of the Selenium repository.

### Usage example

This is useful to see how the code coverage is on the repository.

**Comment by diemol** [comment]
It would not be a real % because it is only used for Python. But feel free to send us a PR with the badge if you like.
