### ISSUE TITLE
[🐛 Bug]: Not able to add response headers using Fetch.fulfillRequest()

### ISSUE THREAD

**Issue by arvinder06** [SeleniumHQ/selenium#10734]
### What happened?

I am trying to modify the response body for one of the request using selenium 4. I am able to reach upto some extent where modifying the request is breaking my application as it required 2 response headers. I am adding these mandatory response headers while modifying the response body, however, they does not seems to be added on the Network tab of chrome devtools. 

Because the application is breaking that mean the code is working but it is just not adding the response header.

### How can we reproduce the issue?

```shell
WebDriver webDriver = new ChromeDriver(chromeOptions);
                DevTools devTools = ((ChromeDriver) webDriver).getDevTools();
                devTools.createSession();
       			devTools.send(Fetch.enable(Optional.empty(), Optional.empty()));
       			String response = "{\"status\": \"SUCCESS\"}";

        devTools.addListener(Fetch.requestPaused(), req -> {
            String url = req.getRequest().getUrl();
            if (url.equals("https://***** Hidden ******")) {
                List<HeaderEntry> corsHeaders = new ArrayList<>();
                corsHeaders.add(new HeaderEntry("Access-Control-Allow-Origin", "https://*** Hidden ****"));
                corsHeaders.add(new HeaderEntry("Access-Control-Allow-Credentials", "true"));

                devTools.send(Fetch.fulfillRequest
                        (
                                req.getRequestId(),
                                200,
                                Optional.of(corsHeaders),
                                Optional.empty(),
                                Optional.of(Base64.getEncoder().encodeToString(response.getBytes())),
                                Optional.of("OK")
                        )
                );
            } else {
                devTools.send(Fetch.continueRequest(
                        req.getRequestId(),
                        Optional.of(url),
                        Optional.of(req.getRequest().getMethod()),
                        req.getRequest().getPostData(),
                        req.getResponseHeaders(),
                        Optional.empty()));
            }
        });
```

### Relevant log output

```shell
Chrome screenshot where not a single response header is added and the application is breaking
![image](https://user-images.githubusercontent.com/28785545/172136414-907aaa57-4d9f-48e3-883b-d1ce569d00cd.png)

```

### Operating System

Windows 10

### Selenium version

4.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 97.0.4692.71 - Organization managed

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Version 97.0.4692.71 - Organization managed

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
If I understand correctly, the code works given that the headers get added and the application under test works as expected when the headers get added. However, you do not see the headers in the Developer tools in the Chrome browser.

Selenium simply offers access to CDP through the bindings, therefore it might be that CDP or Chrome is not showing in the UI the headers you are adding. If that is very important to you, I recommend creating an issue in the Chromium repository to dig into it. https://bugs.chromium.org/p/chromium/issues/list
