### ISSUE TITLE
Codespell report for "Selenium" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [SeleniumHQ/selenium#10731]
### What happened?

The FOSS server [fossies.org](https://fossies.org) - supporting now also the [Selenium](https://fossies.org/linux/selenium) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "Selenium" development version:

&nbsp;https://fossies.org/linux/test/selenium-trunk.tar.gz/codespell.html

That version-independent URL should redirect always to the report for the latest "trunk" version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and is continuously updated (currently with a half-hourly refresh rate).

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Especially interesting may be unassigned errors marked by a "?" since they may be contained in the source code itself. Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can exclude them if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/test/selenium-trunk.tar.gz/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/test/selenium-trunk.tar.gz/codespell_fps.html) and a [misspelling history](https://fossies.org/linux/test/selenium-trunk.tar.gz/codespell_hist.html) (log).

OK, spelling corrections certainly have a low priority, but they may also contribute to the overall quality of a software project. So I hope that the report can nevertheless be a little bit useful.

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by symonk** [comment]
would happily accept a PR addressing any typos 😉

**Comment by jschleus** [comment]
This is an understandable but unrealizable suggestion, I quote the following excerpt from the abobe mentioned short documentation:

> A note: Fossies provides as an information only the source code spelling check reports with the special option to inspect the context of the probably misspelled words in a fast and comfortable way. However Fossies doesn't create for e.g. "diff"-like files usable by the "patch" command or even GitHub pull requests (PRs) since the risk is too high that something would be wrongly corrected (but here you may find some small [codespell usage hints](https://fossies.org/codespell_usage_hints.html)).

In some cases also the in the misspelling report mentioned linked list of the found errors in the original text format can be helpful (scripting).

**Comment by diemol** [comment]
We appreciate and acknowledge the good intention of the issue and the potential benefits. However, it has become a common activity to create issues or pull requests in this repository that add an integration to perform some type of activity on the code base. Such as code quality or things like "Codespell". 

The truth is that these types of integrations end up increasing the work load of an already reduced Selenium team. We do not have the bandwidth to check the Codespell reports and address the changes. Hence the suggestion that you send us PR corrections, @jschleus.

I will close this as there is no action we can actually take now, if our team ever grows, we'd be happy to have a look.
