### ISSUE TITLE
[🚀 Feature]: python 4.2.0 tag missing

### ISSUE THREAD

**Issue by SuperSandro2000** [SeleniumHQ/selenium#10732]
### Feature and motivation

The git tag for https://pypi.org/project/selenium/4.2.0/ is missing.

### Usage example

When building packages from source it is quite handy to have the git history right next to it.

**Comment by diemol** [comment]
This is the tag https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.2.0

Specific tags for languages are only created for patch versions.
