### ISSUE TITLE
[🚀 Feature]: Make it easier to figure out which areas need tests in the repository

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#10747]
### Feature and motivation

I recently asked about having a badge for codecov in the repository. It was closed because codecov is only for Python code. I think it would be good to have some way to know which parts of the code need to be tested. 

NOTE:

- Since there is going to be some code removal for the move to Selenium 4.3, I will be okay with this waiting until Selenium 4.3 is released, which would mean that all of the code that was used for supporting the legacy protocol has been removed.

### Usage example

To find areas that need tests so that they can be used to generate documentation for the site. This happened in the Pull Request: copy web content to be served on selenium.dev (https://github.com/SeleniumHQ/selenium/pull/10637)

**Comment by symonk** [comment]
I'm not against a `codecov` badge in the `/py` specific README 👍 (missed the other ticket sorry)

**Comment by diemol** [comment]
That is a good idea, @symonk.

@ollie-iterators would you like to send a PR to add a badge where @symonk points out?

**Comment by ollie-iterators** [comment]
It's not just about the python tests. It would be good for the other versions as well (C#, Java, JavaScript and Ruby)

**Comment by diemol** [comment]
OK, then we will leave this open because that will take a long while. Happy to receive contributions, @ollie-iterators!

**Comment by ollie-iterators** [comment]
> That is a good idea, @symonk.
> 
> @ollie-iterators would you like to send a PR to add a badge where @symonk points out?

When I check out the codecov information for the Selenium repository, it always says: "Coverage is either being processed, there has been no coverage report uploaded, or there was an error processing."
