### ISSUE TITLE
[🐛 Bug]: TouchActions in DotNet do not work

### ISSUE THREAD

**Issue by ICannotStopEatingMeat** [SeleniumHQ/selenium#10746]
### What happened?

The TouchActions in .Net do not work at all because the TouchActions class uses a separate ActionBuilder. 
When calling Perform() the ActionBuilder from the base class is used which does not have any actions registered.

```
public class Actions : IAction    {
        private readonly TimeSpan DefaultScrollDuration = TimeSpan.FromMilliseconds(250);
        private readonly TimeSpan DefaultMouseMoveDuration = TimeSpan.FromMilliseconds(250);
        private ActionBuilder actionBuilder = new ActionBuilder(); //<--- is used when calling Perform()
```

```
public class TouchActions : Actions
    {
        private readonly TimeSpan DefaultScrollMoveDuration = TimeSpan.FromSeconds(2);
        private readonly TimeSpan DefaultLongPressDuration = TimeSpan.FromSeconds(2);
        private readonly TimeSpan DefaultFlickDuration = TimeSpan.FromMilliseconds(100);
        private ActionBuilder actionBuilder = new ActionBuilder(); //<---- is used to build touch actions
```

### How can we reproduce the issue?

```shell
new TouchActions(myDriver).SingleTap(myElement).Perform();
```

### Relevant log output

```shell
Fails silently
```

### Operating System

Windows 10

### Selenium version

4.2

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by titusfortner** [comment]
`TouchActions` class has already been removed in the other languages and we neglected to do it in .NET. It will be removed for the next release.

You can use the `ActionBuilder` class to create a `PointerInputDevice` of `PointerKind.Touch` if your pointer needs to be a finger. This will work for everything that only requires one finger. Example for pen: https://www.selenium.dev/documentation/webdriver/actions_api/pen/#using-a-pen

For things that require multiple fingers, I've added this ticket for coming up with an API to make things easier: https://github.com/SeleniumHQ/selenium/issues/10808
