### ISSUE TITLE
Make fully qualifying of href/src attributes configurable

### ISSUE THREAD

**Issue by DaniRey** [SeleniumHQ/selenium#1074]
In HtmlUnitWebElement on line 371 the url always gets fully qualified. See the following code snippet.

```java
    if ("href".equals(lowerName) || "src".equals(lowerName)) {
      if (!element.hasAttribute(name)) {
        return null;
      }

      String link = element.getAttribute(name).trim();
      HtmlPage page = (HtmlPage) element.getPage();
      try {
        return page.getFullyQualifiedUrl(link).toString();
      } catch (MalformedURLException e) {
        return null;
      }
    }
```

I would prefer this to be configurable. Sometimes I want to explicitly test whether the attribute contains an absolute link or fully qualified url. As the link is always turned into a fully qualified url, this is not possible anymore.

**Comment by jimevans** [comment]
This is in keeping with the behavior of other drivers, and is standard behavior for the `getAttibute` method. If you want the actual value of the attribute as specified in the HTML source, use JavaScript.
