### ISSUE TITLE
[🚀 Feature]: deno support

### ISSUE THREAD

**Issue by caperaven** [SeleniumHQ/selenium#10754]
### Feature and motivation

We are moving away from nodejs to deno.
Selenium is important too us and it would be great to have deno support as an alternative to nodejs.
I have tried to use the CDN
https://www.skypack.dev/view/selenium-webdriver
But I still get an error of http being required

/*
 * [Package Error] [Package Error] "http" does not exist. (Imported by "selenium-webdriver:14:7").
 *
 * The package "selenium-webdriver:14:7" depends on this Node.js built-in module.
 * Node.js built-in modules (like "fs", "http", etc.) are Node.js-specific, and do
 * not exist in non-Node environments like Deno or the web browser. Skypack CDN polyfills
 * most of these modules for you automatically, but this one could not be polyfilled.
 *
 * How to fix:
 *   - Let the package author know that you'd like to run their package in the browser.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

throw new Error("[Package Error] \"http\" does not exist. (Imported by \"selenium-webdriver:14:7\").");
export default null;

I have posted a request on deno side for compat mode to include http but in reality if would far better to just have selenium work directly with deno instead of using compat mode.

### Usage example

Testing UI in a deno environment void of nodejs

**Comment by rahulmr** [comment]
Any update on this? Any example whether it works or not using Deno

**Comment by diemol** [comment]
@rahulmr this is open for contributions, we do not have bandwidth to work on this at the moment and there is not a clear interest from the community to prioritize this.
