### ISSUE TITLE
[🐛 Bug]: [Python] WebDriver constructor must not assume that BaseOptions instance has _ignore_local_proxy property

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#10755]
### What happened?

I'm talking about https://github.com/SeleniumHQ/selenium/blob/27ff5866dc1f50e4a01733fb6b0f3e734a72363b/py/selenium/webdriver/remote/webdriver.py#L256

The typing info says `options: Union[BaseOptions, List[BaseOptions]] = None`, while `_ignore_local_proxy` property is only defined for `ArgOptions` class. This means any code that inherits Options from BaseOptions rather than from ArgOptions would fail with missing attribute error (which is also happening for the Appium Python client)

### How can we reproduce the issue?

```shell
Pass any custom class inherited from BaseOptions rather than from ArgOptions to the WebDriver constructor
```

### Relevant log output

```shell
if options:
                capabilities = options.to_capabilities()
>               _ignore_local_proxy = options._ignore_local_proxy
E               AttributeError: 'UiAutomator2Options' object has no attribute '_ignore_local_proxy'
```
```


### Operating System

macOS

### Selenium version

Python 3.9

### What are the browser(s) and version(s) where you see this issue?

Appium

### What are the browser driver(s) and version(s) where you see this issue?

Any

### Are you using Selenium Grid?

_No response_

**Comment by mykola-mokhnach** [comment]
I assume such issue could be easily caught with mypy automatically

**Comment by symonk** [comment]
It could but we have a lot of work to get that going, types at the moment are quite frankly very messy, any PRs introducing improved types would be greatly appreciated. `tox -e mypy` exists but its extremely broken and not enforced in CI at all, it's a mammoth task to get everything typed etc

**Comment by titusfortner** [comment]
I think the fix for this should have been just moving it from `ArgOptions` to `BaseOptions`?
At any rate, I finally have a PR to at least deprecate this parameter entirely: https://github.com/SeleniumHQ/selenium/pull/13286

**Comment by mykola-mokhnach** [comment]
Thanks @titusfortner for taking care of it. 
This also means we'd need to adjust Appium Python client after the next Selenium release.
FYI @KazuCocoa

**Comment by diemol** [comment]
@mykola-mokhnach would https://github.com/SeleniumHQ/selenium/pull/13926 be enough while we merge @titusfortner's PR?

**Comment by diemol** [comment]
I will merge it and if we need to fix something else, we iterate on it.
