### ISSUE TITLE
[🐛 Bug]: Seleniun nodejs move action documentation or implementation is incorrect

### ISSUE THREAD

**Issue by praveendvd** [SeleniumHQ/selenium#10753]
### What happened?

https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html

this.move( options ) → Actions

**The move options. Defaults to moving the mouse to the top-left corner of the viewport over 100ms.**

The documentation says the default implementation of move is to , move to top left of the view port. But the implemenation is :

https://github.com/SeleniumHQ/selenium/blob/be408c02a10b7ae36578306f4d78ccd78d5fb690/javascript/node/selenium-webdriver/lib/input.js#L878

  ```
move({ x = 0, y = 0, duration = 100, origin = Origin.VIEWPORT } = {}) {
    return this.insert(
      this.mouse_,
      this.mouse_.move({ x, y, duration, origin })
    )
  }
```
its moving 0,0 relative pixel relative to view port . So its not moving to top left corner but remains at the center of the viewport

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

MacOS

### Selenium version

Selenium 4 , Nodejs

### What are the browser(s) and version(s) where you see this issue?

All browsers

### What are the browser driver(s) and version(s) where you see this issue?

Latest chromedriver

### Are you using Selenium Grid?

No

**Comment by praveendvd** [comment]
x and y is relative to the origin , so if origin is viewport will it be the centre of the viewport ? or top left of the view port ? Anyway documenation need to be updated 


Could someone point to the source code where this distinction is made whether its the top left corner or not

**Comment by praveendvd** [comment]
I could take it up and update the documentation

**Comment by diemol** [comment]
Closing as it was replied in Slack.

![image](https://user-images.githubusercontent.com/5992658/173342921-b1e3525a-4bde-4724-94a7-26c0a23b3d9f.png)
