### ISSUE TITLE
[🐛 Bug]: CI executes pytest using `3.8.10` in ubuntu.

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#10767]
### What happened?

CI is currently executing pytest under a global install of python `3.8.10`.  Given the headaches we had for `4.1` where various `types` that only work on 3.8+ got introduced as well as the sweeping python3.7+ syntax upgrades I will be merging in `4.3` I would like to add a blocker on 4.3 until CI is running everything through python `3.7` as it _should_ be.

### How can we reproduce the issue?

Look at any *failing* python build in CI; notice how `pytest` is being invoked with `python 3.8.10` this is by mistake as we setup `3.7` prior in actions, I assume its maybe the default/bootstrapped sys python of the ubuntu version? or we need to tweak bazel toolchains etc

Example: https://github.com/SeleniumHQ/selenium/runs/6867087000?check_suite_focus=true#step:9:64

**Comment by titusfortner** [comment]
I don't think we can actually do this one with Bazel; I'll let you close it if you want, but I'm removing the milestone.

**Comment by symonk** [comment]
closing this, its very unfortunate that we cannot test against what we support with bazel easily.  If anyone has a good way to do so, please re-open it
