### ISSUE TITLE
[🚀 Feature]: GoLang Client

### ISSUE THREAD

**Issue by TorbenHammes** [SeleniumHQ/selenium#10762]
### Feature and motivation

Hey there,
is it possible to offer a GoLang Client?

### Usage example

Using Selenium in Go Projects

**Comment by diemol** [comment]
There is this one https://github.com/tebeka/selenium

We do not plan to provide our own (at least for now). Our team is currently very small and we are just being able to keep up with maintenance tasks and sometimes add a feature per release, so adding a new client is a huge effort.

Perhaps some work can be done by the community on the linked one to bring it up to date and then we could reference it as an official client.
