### ISSUE TITLE
[🚀 Feature]: How to move a file downloaded in Node machine to the hub machine using Selenium Grid?

### ISSUE THREAD

**Issue by sayanbir** [SeleniumHQ/selenium#10765]
### Feature and motivation

I have Hub with 2 nodes. Now while executing the test cases in the nodes in chrome browser, I want to access the files downloaded in the node and move them to the hub for further use. How to achieve that using Selenium Grid 4?

In my case, the default download directory for chrome is the 'Downloads' folder.

### Usage example

Sometimes we need to access the files of the node machine and use them in the hub machine for future operations. For that scenario how to do it?

**Comment by diemol** [comment]
This is not supported yet, have a look at https://github.com/SeleniumHQ/selenium/issues/9218 for future reference. Links  above are useful so you can ask others for their approach.
