### ISSUE TITLE
[🐛 Bug]: [Java] FirefoxProfile is incorrectly loaded

### ISSUE THREAD

**Issue by frensjan** [SeleniumHQ/selenium#10775]
### What happened?

When setting preferences in a `FirefoxProfile`, these settings can't be correctly read from the profiles from `FirefoxOptions#getProfile()`.

### How can we reproduce the issue?

```shell
import org.junit.jupiter.api.Test;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;

import static org.junit.jupiter.api.Assertions.assertEquals;

class FirefoxProfileTest {

    @Test
    void testFirefoxProfileIO() {
        String key = "browser.startup.homepage";
        String value = "about:robots";

        FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference(key, value);

        FirefoxOptions options = new FirefoxOptions();
        options.setProfile(profile);

        assertEquals(profile.getStringPreference(key, "-"), value);
        assertEquals(options.getProfile().getStringPreference(key, "-"), value); // <-- fails here
    }
}
```

### Relevant log output

```shell
org.opentest4j.AssertionFailedError: 
Expected :-
Actual   :about:robots
```

### Operating System

macOS Monterey

### Selenium version

Java 4.2.2

### What are the browser(s) and version(s) where you see this issue?

Firefox, version n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

**Comment by frensjan** [comment]
The issue seems to be in my view that although the preferences are correctly loaded in `org.openqa.selenium.firefox.FirefoxProfile#FirefoxProfile(java.io.File)` they aren't actually stored in `org.openqa.selenium.firefox.FirefoxProfile#additionalPrefs`.

**Comment by pujagani** [comment]
> The issue seems to be in my view that although the preferences are correctly loaded in `org.openqa.selenium.firefox.FirefoxProfile#FirefoxProfile(java.io.File)` they aren't actually stored in `org.openqa.selenium.firefox.FirefoxProfile#additionalPrefs`.

Thank you for sharing the details. I was able to reproduce the issue. You are right. The additionalPrefs are not populated after being read from a file. I think some additional checks need to be added to help settle the same. I am looking into how it can be done.

**Comment by frensjan** [comment]
Super, thanks!
