### ISSUE TITLE
CodeMirror: Element is not currently visible and so may not be interacted with

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#1077]
I am trying to drive the CodeMirror widget but it proves impossibile to enter any text into it because of the error "Element is not currently visible and so may not be interacted with".

CodeMirror is a javascript library to edit code in a browser window.

It makes quite an odd use of a textarea to allow the text to be input. The textarea is always available for input but the fxDriver extension isShown method doesn't think so. I think that method implements a strategy to figure out if the element is editable, but that strategy fails in this case.

Try the following test with webdriver, it reproduces the error.

Thanks, Carlo.

<pre>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://codemirror.net/" />
<title>code-mirror</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">code-mirror</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>https://codemirror.net/</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>css=div &gt; textarea</td>
	<td>something</td>
</tr>
</tbody></table>
</body>
</html>

</pre>

**Comment by samitbadle** [comment]
The textarea where you enter text is actually 1px wide and is moved to where the current cursor is.
Due to the way the library works, it is not possible to use Selenium-IDE, unless you make some changes to the application itself. One such workaround could be to change the code and make the textarea a bit wider.

**Comment by ygmarchi** [comment]
It doesn't seem to me that the text area is 1px wide.

What's surely true is that the problem lies in the algorithm used by the fx-driver to determined if an element is shown or not.

Since that actually the very point addressed by this issue, it should have been left open, not closed.

![code-mirror](https://cloud.githubusercontent.com/assets/1649687/10193350/cbac39fa-6782-11e5-9787-73e14b973e2d.png)

**Comment by twalpole** [comment]
@ygmarchi in your example the textarea is inside alive with height of 0px and overflow hidden - hence - not visible

**Comment by ygmarchi** [comment]
Yes, thanks, I hadn't noticed that.
