### ISSUE TITLE
[🚀 Feature]: Ability to pass user data directory argument to IEDriverServer for use automating Edge legacy mode

### ISSUE THREAD

**Issue by lukeinstone** [SeleniumHQ/selenium#10770]
### Feature and motivation

Currently, as far as I can see there is no way to add options to the Edge browser instance that is launched when using IEDriverServer to automate Edge Legacy mode. This means that you are unable to pass a 'user-data-dir' parameter to the Edge browser window (as you can when using msedgedriver), which means my organisations' profile sign in window appears. This causes any automation to fail when automating Edge legacy mode. 

Please note that this profile sign in window only appears when using IEDriverServer version 4.0.0 and above, which is mentioned as a pre-requisite by Selenium for Edge legacy automation. If I use a version less than 4.0.0, such as 3.150.1.2, then this window does not appear. 

![image](https://user-images.githubusercontent.com/107465910/173531210-a0d913b1-8e0a-471b-96ca-c3815a8b864a.png)

### Usage example

Edge implementation: 
EdgeOptions.AddArguments("user-data-dir=" + EnvironmentContext.LocalDirectory, "--start-maximized");

**Comment by diemol** [comment]
I think you should propose this to the Edge team, since they have been kind enough about maintaining the IEDriver and make Edge work in IEMode

**Comment by lukeinstone** [comment]
Thanks, raised here: https://github.com/MicrosoftEdge/EdgeWebDriver/issues/29
