### ISSUE TITLE
[🐛 Bug]: [Python] [Firefox] Impossible to reach DEVNULL log_file in Service

### ISSUE THREAD

**Issue by Commaster** [SeleniumHQ/selenium#10783]
### What happened?

I'm guessing after https://github.com/SeleniumHQ/selenium/commit/99d4173c64a849e71eaa0a9e4436584573ebe371 it became impossible to reach a `DEVNULL` state for https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/service.py#L41 since passing `DEVNULL` as the `log_path` argument is a `-3` and calls open at https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/service.py#L49 which obviously fails.

Specifying `log_path` as `''` does remove the `geckodriver.log` file but dumps all geckodriver output to stdout/stderr.

The current workaround is to `pathlib.Path('geckodriver.log').unlink(True)` after each run, which is suboptimal.

### How can we reproduce the issue?

```shell
service = selenium.webdriver.firefox.service.Service(log_path=subprocess.DEVNULL)
browser = selenium.webdriver.Firefox(service=service)
```

### Relevant log output

```shell
.../lib/python3.8/site-packages/selenium/webdriver/firefox/service.py", line 49, in __init__
    log_file = open(log_path, "a+") if log_path else None
ValueError: negative file descriptor
```

### Operating System

Ubuntu

### Selenium version

Python 3.8.10

### What are the browser(s) and version(s) where you see this issue?

Firefox 101

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 101

**Comment by symonk** [comment]
Thanks @Commaster, design could use a little TLC in around this area for sure.  There is a similar ticket about using named pipes too, what happens if you just simply use `os.devnull` as your `log_path` ?

```python
serv = Service(log_path=os.devnull)
driver = WebDriver(service=serv)
```

**Comment by Commaster** [comment]
> what happens if you just simply use `os.devnull` as your `log_path` ?

Seems to work without complaints over the last 10 minutes testing. Thank you, a much better "workaround"!

**Comment by symonk** [comment]
No problem, I'm going to close this one as a workaround exists; when `4.3` I plan to overhaul the design of service(s) and options in the near future and will keep extensibility at the forefront to cater to issues like this as part of that.

**Comment by Commaster** [comment]
Possibly this should be available through some value, either `''` or `None` as a shortcut... or at least mentioned in the Service comments?
