### ISSUE TITLE
[🐛 Bug]: Codecov python code summary is consistently not working

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#10787]
### What happened?

When I go to the CodeCov URL for the Selenium (https://app.codecov.io/gh/SeleniumHQ/selenium/), there is always a message saying that "Coverage is either being processed, there has been no coverage report uploaded, or there was an error processing."

This makes it difficult to see which areas need tests.

### How can we reproduce the issue?

```shell
Go to the URL: https://app.codecov.io/gh/SeleniumHQ/selenium/
```

### Relevant log output

```shell
Coverage is either being processed, there has been no coverage report uploaded, or there was an error processing.
```

### Operating System

N/A (This is about the CodeCov site)

### Selenium version

N/A (This is about CodeCov)

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by symonk** [comment]
will take a look at the github actions later; we should have bazel generate `.coverage` file in an appropriate format and upload it using their official action; (I don't know what we are doing right now and I have no time to look) but that's where to start

**Comment by symonk** [comment]
@diemol could we look into this? i see commits tracked on codecov but no stats data, we are likely missing the appropriate format, maybe quite tricky across multiple languages etc

**Comment by diemol** [comment]
I'd like to use Codecov across languages and get rid of Sonar, it is just a bunch of work.

**Comment by ollie-iterators** [comment]
This is an action that can upload code coverage to Codecov if it helps: https://github.com/codecov/codecov-action

**Comment by ollie-iterators** [comment]
Strangely, the code coverage works as expected on my fork of selenium

**Comment by diemol** [comment]
Not sure what changed, but I see that this is working as expected now https://app.codecov.io/gh/SeleniumHQ/selenium/tree/trunk
