### ISSUE TITLE
[🐛 Bug]: devtools.debugger.enable() causes exception

### ISSUE THREAD

**Issue by TimRecktenwald** [SeleniumHQ/selenium#10804]
### What happened?

Trying to enable the Chrome DevTools debugger using the wrappers provided by Selenium will cause an exception. The `enable()` functions for other CDP domains seem to work though (e.g., `devtools.runtime.enable()`).

### How can we reproduce the issue?

```shell
import trio
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


async def main():
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

    async with driver.bidi_connection() as connection:
        session, devtools = connection.session, connection.devtools

        driver.get('https://google.com')

        # Try to enable debugger
        await session.execute(devtools.debugger.enable())


trio.run(main)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    trio.run(main)
  File "/home/tim/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "bug.py", line 16, in main
    await session.execute(devtools.debugger.enable())
  File "/usr/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1188, in bidi_connection
    yield BidiConnection(session, cdp, devtools)
  File "/usr/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 481, in open_cdp
    await conn.aclose()
  File "/home/tim/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 813, in __aexit__
    raise combined_error_from_nursery
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 458, in _reader_task
    session._handle_data(data)
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 256, in _handle_data
    self._handle_event(data)
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/bidi/cdp.py", line 293, in _handle_event
    event = devtools.util.parse_json_event(data)
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/devtools/v102/util.py", line 19, in parse_json_event
    return _event_parsers[json['method']].from_json(json['params'])
  File "/home/tim/.local/lib/python3.8/site-packages/selenium/webdriver/common/devtools/v102/debugger.py", line 1219, in from_json
    script_language=debugger.ScriptLanguage.from_json(json['scriptLanguage']) if 'scriptLanguage' in json else None,
NameError: name 'debugger' is not defined
```

### Operating System

Linux Mint 20.1

### Selenium version

Python 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 102.0.5005

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102.0.5005.61

**Comment by symonk** [comment]
Thanks @TimRecktenwald for the report, is it the same with `devtools 103` in `4.3`? Will take a look shortly

**Comment by TimRecktenwald** [comment]
Yes, the error persists with version 103 of Chrome and ChromeDriver.

**Comment by symonk** [comment]
I had a look and i'm not entirely sure what is responsible for generating these `devtools` modules; but the `ScriptParsed` event which is likely similar to what you are retrieving first here is trying to deserialise the event and in doing so using a `debugger.ScriptLanguage` class, however the `debugger.` namespace is not available; setting it to just `ScriptLanguage.from_json(...)` does infact deserialise the `ScriptParsed` event successfully.  This has likely been broken forever, looking in `v85` it also suffers the same problem

**Comment by TimRecktenwald** [comment]
Thanks for looking into the issue. The same holds true for the `debugger.DebugSymbols` class one line beneath. I guess the patch has to be applied to `ScriptFailedToParse` as well, as it uses the same construct regarding `ScriptLanguage`.

**Comment by symonk** [comment]
Exactly, I think there is a `generate.py` responsible for generating the files from: https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/js_protocol.json - there is likely many cases referencing the same module in the `$ref` - doing a `from . import <module name>` inside each generated module might be a quick (albeit hacky) fix as `debugger` in this instance _would_ exist in the namespace, ideally we probably would omit the module prefix if such classes are inside the generated module.

Quick look, perhaps stripping matching `domain` from the `$ref` is a better solution.

**Comment by symonk** [comment]
Thanks  for the report @TimRecktenwald I have a small patch but the upstream generator is likely also broken which I will look to submit a patch too; should be _usable_ when we ship a fix
