### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver doesn't properly handle response from the external resource

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#10805]
### What happened?

I use some 3rd-party provided hub, for instance, BrowserStack. When I want to start a remote session, then I expect the session is started. I know that I forgot to put api key for my BrowserStack account, and status code of http response from BrowserStack is 401 (or 403).

```csharp
var driver = new RemoteWebDriver(uri, options); // where uri is the link to /wd/hub
```

This line of code was successfully executed without exceptions, but my browser session was not started.

### How can we reproduce the issue?

```shell
Try to start a remote session with incorrect driver options.
```

### Relevant log output

```shell
No output.
```

### Operating System

any

### Selenium version

any dotnet, selenium 4.0+

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

Remote

**Comment by titusfortner** [comment]
I'm actually getting what I expect from a 401 error:
> threw exception. OpenQA.Selenium.WebDriverException: failed serving request POST /wd/hub/session: Unauthorized.

But I see the issue for a 404 error. I'm going through your PR now.

**Comment by nvborisenko** [comment]
In my case
```csharp
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Remote;

var driver = new RemoteWebDriver(new Uri("http://hub-cloud.browserstack.com/wd/hub/"), new ChromeOptions());
```

```
Unhandled exception. OpenQA.Selenium.WebDriverException: The new session command returned a value ('Authorization required') that is not a valid JSON object.
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
```

If remote response is json, then this piece of code doesn't throw any exception.

This PR handles remote responses properly and throws an exception with exact information what were wrong (taken from response body).
