### ISSUE TITLE
[🐛 Bug]: artifact version 4.3.0 not committed to org.seleniumhq.selenium yet

### ISSUE THREAD

**Issue by hollyw2025** [SeleniumHQ/selenium#10803]
### What happened?

Hi, my chrome upgraded to Version 103.0.5060.53, and I also upgraded my local Chrome driver to the same version, https://chromedriver.storage.googleapis.com/index.html?path=103.0.5060.53/ 

I noticed that only v4.3.0 support 103, (https://github.com/SeleniumHQ/selenium/blob/trunk/java/CHANGELOG ), v 4.3.0 only got checked in a few hours ago. I can't pull out this version from maven artifact yet. 

Please check in.   
Thank you

### How can we reproduce the issue?

```shell
<dependency>
		    <groupId>org.seleniumhq.selenium</groupId>
		    <artifactId>selenium-api</artifactId>
		    <version>4.3.0</version>
</dependency>
[{
	"resource": "/Users/../Projects/apimportalautotest/portaltest",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "964",
	"severity": 8,
	"message": "The container 'Maven Dependencies' references non existing library '/Users/...m2/repository/org/seleniumhq/selenium/selenium-api/4.3.0/selenium-api-4.3.0.jar'",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

### Relevant log output

```shell
<dependency>
		    <groupId>org.seleniumhq.selenium</groupId>
		    <artifactId>selenium-api</artifactId>
		    <version>4.3.0</version>
</dependency>
[{
	"resource": "/Users/..Projects/apimportalautotest/portaltest",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "964",
	"severity": 8,
	"message": "The container 'Maven Dependencies' references non existing library '/Users/../.m2/repository/org/seleniumhq/selenium/selenium-api/4.3.0/selenium-api-4.3.0.jar'",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

### Operating System

MAC

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  Version 103.0.5060.53

### What are the browser driver(s) and version(s) where you see this issue?

Chrome  Version 103.0.5060.53

**Comment by hollyw2025** [comment]
Thank you, waiting for it to be resolved

**Comment by symonk** [comment]
Thanks @hollyhw15 the release is in flight and should be good to pull in shortly.

**Comment by hollyw2025** [comment]
Hi, 
4.3.0 still can't be pull out, its Fri, June 24th, 10:30am
