### ISSUE TITLE
phantomjs web driver not closing socket

### ISSUE THREAD

**Issue by chemicwepn** [SeleniumHQ/selenium#1080]
Hi,

I am using phantomjsdriver 1.2.1 and selenium-java 2.47.1. I notice after every call to driver.quit(), the socket stays in CLOSE_WAIT state. It doesn't get closed, and end up wasting a lot file descriptors, eventually if I have a long running process, it will consume all sockets. Since my application needs to be up all the time, I have thousands of sockets in CLOSE_WAIT state. 

If you simple run "driver.get(url) and then driver.quit()" in a for loop, then monitor the socket state with 
"netstat -tonp", I see something like this:

tcp6       1      0 127.0.0.1:40791         127.0.0.1:7936          CLOSE_WAIT  16626/java       off (0.00/0/0)
tcp6       1      0 127.0.0.1:44967         127.0.0.1:7431          CLOSE_WAIT  16626/java       off (0.00/0/0)
tcp6       1      0 127.0.0.1:52849         127.0.0.1:23807         CLOSE_WAIT  16626/java       off (0.00/0/0)
tcp6       1      0 127.0.0.1:44493         127.0.0.1:10229         CLOSE_WAIT  16626/java       off (0.00/0/0)
tcp6       1      0 127.0.0.1:56702         127.0.0.1:22088         CLOSE_WAIT  16626/java       off (0.00/0/0)
tcp6       1      0 127.0.0.1:34134         127.0.0.1:8235          CLOSE_WAIT  16626/java       off (0.00/0/0)
....

Please take a look at this problem. It really affects the stability of our application when we want it to be up all the time. 

Thanks

**Comment by yamburg** [comment]
Hi,

Has anyone found a workaround for this issue?
For me this problem very critical, it broke stability and performance on my server

Thanks!

**Comment by sgoeschl** [comment]
Hi folks, to keep you in the loop - http://mail-archives.apache.org/mod_mbox/commons-user/201601.mbox/%3cCACK3WSf+fxx_GSVV68bK6VyLSB6hcEyhavb-jBNcYhaBiQ6YbA@mail.gmail.com%3e

Cheers,

Siegfried Goeschl

**Comment by sgoeschl** [comment]
I had a closer look at the issue since I'm a Apache Commons Exec maintainer and would hate the thought to break Selenium with my code :-)

**Comment by sgoeschl** [comment]
I played with your GitHub repo [https://github.com/cgamache/openfile](https://github.com/cgamache/openfile)

### 1. First Take

Your test program actually starts a JVM and the Selenium library start multiple "phantomjs" executable to run the test as shown below

```
application> ps -ef | grep phantom
  501  1021   460   0  9:26PM ttys000    0:00.71 java -jar openfile.jar /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
  501  1073  1062   0  9:26PM ttys000    0:00.08 /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs --webdriver=36418 --webdriver-logfile=/Users/sgoeschl/work/github/cgamache/openfile/target/phantomjsdriver.log
```

So commons-exec is used under the hood to run the "phantomjs" binary and make sure nothing hangs (output & error thread pumping, watchdog, ..)

When the "WebDriver" has finished its work there 

* is no ***phantomjs*** process running
* is only your program running as shown below

```
application> ps -ef | grep phantom
  501  1021   460   0  9:23PM ttys000    0:00.72 java -jar openfile.jar /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
  501  1034   469   0  9:23PM ttys001    0:00.00 grep phantom
```

And as described we have a couple of ports in CLOSE_WAIT stemming from your program 

```
application> lsof -p 1021 | grep CLOSE_WAIT
java    1021 sgoeschl   16u    IPv6 0x78418468470e25c7       0t0     TCP localhost:50581->localhost:40560 (CLOSE_WAIT)
java    1021 sgoeschl   18u    IPv6 0x784184685efd95a7       0t0     TCP localhost:50599->localhost:45319 (CLOSE_WAIT)
java    1021 sgoeschl   19u    IPv6 0x784184685efdc0a7       0t0     TCP localhost:50620->localhost:17950 (CLOSE_WAIT)
java    1021 sgoeschl   20u    IPv6 0x78418468470e3087       0t0     TCP localhost:50641->localhost:41916 (CLOSE_WAIT)
java    1021 sgoeschl   21u    IPv6 0x78418468470e4b67       0t0     TCP localhost:50661->localhost:25113 (CLOSE_WAIT)
```

As far as common-exec is concerned everything is fine - the ***phantomjs*** processes where nicely executed and no process is left

So you have 5 ports in limbo which exactly corresponds to the number of created ***phantom.js*** instances

```
INFO: executable: /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
INFO: executable: /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
INFO: executable: /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
INFO: executable: /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
INFO: executable: /usr/local/Cellar/phantomjs/2.1.0/bin/phantomjs
```

This nicely corresponds to your test code

```
public static final int REPS = 5;

for (; i < REPS; i++) {
    WebDriver driver = new PhantomJSDriver(caps);
    driver.get("http://www.apache.org");
    driver.quit();
}
```

In other words each ***phantomjs*** process leaves exactly on port behind :-)


### 2. Second Take

So where is this port coming from? The next session - starting the test programm leaves the 5 ports behind

```
application> lsof -p 1329 | grep CLOSE_WAIT
java    1329 sgoeschl   16u    IPv6 0x784184686037bb07       0t0     TCP localhost:51358->localhost:30177 (CLOSE_WAIT)
java    1329 sgoeschl   18u    IPv6 0x784184685f5c3b47       0t0     TCP localhost:51379->localhost:cadkey-tablet (CLOSE_WAIT)
java    1329 sgoeschl   19u    IPv6 0x784184686037f0c7       0t0     TCP localhost:51400->localhost:43648 (CLOSE_WAIT)
java    1329 sgoeschl   20u    IPv6 0x784184686037c5c7       0t0     TCP localhost:51418->localhost:34505 (CLOSE_WAIT)
java    1329 sgoeschl   21u    IPv6 0x78418468470e1047       0t0     TCP localhost:51438->localhost:30905 (CLOSE_WAIT)
```

All of ports are actually found in phantomjsdriver.log (cadkey-tablet is actually port 1400)

```
[INFO  - 2016-01-26T20:51:19.697Z] GhostDriver - Main - running on port 30177
[INFO  - 2016-01-26T20:51:21.685Z] GhostDriver - Main - running on port 1400
[INFO  - 2016-01-26T20:51:23.427Z] GhostDriver - Main - running on port 43648
[INFO  - 2016-01-26T20:51:25.156Z] GhostDriver - Main - running on port 34505
[INFO  - 2016-01-26T20:51:26.887Z] GhostDriver - Main - running on port 30905
```

So the ports are actually used/opened for ***GhostDriver*** and left there even when ***driver.quit()*** was called


### 3. Conclusion

* ASFAIK it is not commons-exec issue since all ***phantomjs*** were cleanly terminated
* Each ***PhantomJSDriver*** invocation leaves a port in ***CLOSE_WAIT*** behind
* Those ports are linked to ***GhostDriver - Main - running on port 30177***

**Comment by cgamache** [comment]
Siegfried, I really appreciate the thorough inspection you have given. With your help I think I've targeted the real problem...

GhostDriver can't exist outside of phantomjs. GhostDriver is an implementation of WebDriver Wire Protocol which runs on phantomjs's JavaScript engine. It can't run without phantomjs. 

We can rest easy that commons-exec is not holding open the file handle. That's good. I think the PhantomJSDriver is firing a copy of phantomjs up using commons-exec, but it's not communicating with the service through commons-exec. Upon closer inspection selenium-java is communicating through tcp/ip to a WebDriver server phantomjs is popping up on random available ports. This happens to be an instance of some class that implements org.apache.http.client.HttpClient, by default it looks to be org.apache.http.impl.client.CloseableHttpClient ... I think that when commons-exec terminates phantomjs, thereby terminating the GhostDriver server, the HttpClient is still attached to that port.

Here's my take on the real problem:

I think the selenium folks didn't consider port closing (org.apache.http.client.HttpClient doesn't have a close method to implement) a necessary step and they figured that if whatever service the HttpClient was attached to shut itself down that the port would automatically close itself down also. The standard use for selenium usually doesn't require it to run for days and days on end. I can't fault them for missing it.

That being said, they made this difficult to override in consumer classes by keeping a lot of the guts of the connections hidden behind private classes and private member data.

So, I'll need to dig into selenium-java, change a few interfaces to make sure that whatever HttpClient is used will have a close() hook, and then make sure that whatever is driving the HttpClient has access to the close hook on shutdown, and fires it. When the HttpClient is closed, the file descriptor should disappear.

Thank you again for your help. It was indispensable!

**Comment by krosenvold** [comment]
I'm quite sure you can change the code to use CloseableHttpClient where applicable, that should solve it, right ?

**Comment by cgamache** [comment]
Changing the underlying impl to CloseableHttpClient and calling .close() actually closes the whole pool. Not quite what we wanted. Instead, I poked a hole in the interface which will allow the command executor to call close on DriverCommand.QUIT which closes idle connections. That seemed to get the job done. 

...Now we wait to see if we pass CI and get merged into master.

**Comment by krosenvold** [comment]
If I remember this correctly, you will need a ClientConnetionManager, which will actually prevent the connection from being closed when calling close() unless the connection manager decides it should be shut down.

**Comment by cgamache** [comment]
Yes! The patch I made co-opted the connection manager to release the idle connections in the pool.

The patch didn't break the build. That's good news!

**Comment by sgoeschl** [comment]
Well, hope the patch does not break Selenium :-)

**Comment by cgamache** [comment]
Highly doubtful it will break Selenium. There might be a sexier way to do it, but this is the least obtrusive way I could conjure up.

Selenium has 69 outstanding pull requests that came before mine. I'm not super-hopeful that this gets merged soon, busy people being what they are.

@chemicwepn and @yamburg I do have a semi-complicated workaround. If you're interested, follow @unindicted and I'll message you the gory details.

**Comment by sgoeschl** [comment]
See https://github.com/SeleniumHQ/selenium/pull/1545
