### ISSUE TITLE
[🐛 Bug]: Using HasAuthentication with Augmenter throws ClassCastException

### ISSUE THREAD

**Issue by arsen-papoyan** [SeleniumHQ/selenium#10828]
### What happened?

Getting an error in case of RemoteWebDriver using HasAuthentication.

### How can we reproduce the issue?

```shell
Project: Maven
Runner: TestNG

src/main/java folder:

public class DriverMobile {

    public static WebDriver webDriver;
    public static DevTools devTools;

    public static void initDriver() {
        Map<String, String> mobileEmulation = new HashMap<>();
        mobileEmulation.put("deviceName", "iPhone 12 Pro");
        ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("mobileEmulation", mobileEmulation);
        assertionMode = SOFT;
        driverManagerEnabled = true;
        screenshots = false;
        savePageSource = false;
        headless = false;
        remote = "remoteMachineUrl";
        browserCapabilities = options;
        open();
        webDriver = new Augmenter().augment(getWebDriver());
        devTools = ((HasDevTools) webDriver).getDevTools();
        ((HasAuthentication) webDriver).register(UsernameAndPassword.of("username", "password"));
    }
}

src/test/java folder:

public class HasAuthenticationTest {

    @Test
    public void test(){
        DriverMobile.initDriver();
        open("https://www.google.com/");
    }
}

pom XML:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Draft</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <aspectj.version>1.9.6</aspectj.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide-testng</artifactId>
            <version>6.6.5</version>
        </dependency>
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.12.10</version>
        </dependency>
    </dependencies>

The problem is only arising in the case of running the test on the remote machine, when I run the test on the local machine, everything is okay.
```

### Relevant log output

```shell
java.lang.ClassCastException: class org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$W9YhfBNu cannot be cast to class org.openqa.selenium.HasAuthentication (org.openqa.selenium.remote.RemoteWebDriver$ByteBuddy$W9YhfBNu is in unnamed module of loader net.bytebuddy.dynamic.loading.ByteArrayClassLoader @5fa9247b; org.openqa.selenium.HasAuthentication is in unnamed module of loader 'app')

	at SelenideDriver.DriverMobile.initDriver(DriverMobile.java:40)
	at HasAuthenticationTest.test(HasAuthenticationTest.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Operating System

Local: macOS Monterey / Remote: Windows 10

### Selenium version

JavaSE 14: version 16.0.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102

### Are you using Selenium Grid?

Selenium Grid (selenium server 4.1.4)

**Comment by diemol** [comment]
@asolntsev do you know what version of Selenium is that Selenide release using?

**Comment by asolntsev** [comment]
@diemol Selenide 6.6.5 uses latest Selenium 4.3.0 (unless it's explicitly overridden in the project).

**Comment by asolntsev** [comment]
@diemol I quickly looked into the issue: the problem is that Selenium doesn't have `HasAuthenticationAugmenterProvider` (like `AddHasCdp`, `AddHasExtensions`, `BiDiProvider`, `AddHasCasting` etc.)

**Comment by titusfortner** [comment]
Just did a quick look at what ChromiumDriver implements.
Neither `HasAuthentication` or `HasLogEvents` has associated `AugmenterProvider` implementations

**Comment by pujagani** [comment]
Thank you for sharing the details. Yes, they are not associated with `AugmenterProvider`. I will start looking into how that can be done and mainly try to understand why it is this way. 
Meanwhile, sharing an example of how augmenter allows for adding augmentation for missing interfaces.
```
 public static void main(String[] args) throws MalformedURLException, InterruptedException {
    ChromeOptions chromeOptions = new ChromeOptions();
    WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), chromeOptions);

    Augmenter augmenter = new Augmenter();

    driver = augmenter.augment(driver);

    DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();

    driver = augmenter.
      addDriverAugmentation("chrome", HasAuthentication.class, (caps, exec) ->
        (whenThisMatches, useTheseCredentials) -> {
          devTools.getDomains().network().addAuthHandler(whenThisMatches, useTheseCredentials);
        }).augment(driver);

    ((HasAuthentication) driver).register(UsernameAndPassword.of("test", "test"));
    driver.get("http://localhost:2310/basicAuth");

    System.out.println(driver.findElement(By.tagName("h1")).getText());

    driver.quit();
  }
```

```
public class ChromeDevToolsAugmenterDOMMutationChaining {

  public static void main(String[] args) throws MalformedURLException, InterruptedException {
    ChromeOptions chromeOptions = new ChromeOptions();
    AtomicReference<DomMutationEvent> seen = new AtomicReference<>();
    AtomicReference<WebDriver> augmentedDriver = new AtomicReference<>();
    CountDownLatch latch = new CountDownLatch(1);

    Augmenter augmenter = new Augmenter();

    WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), chromeOptions);
    driver = augmenter.
      addDriverAugmentation("chrome", HasLogEvents.class, (caps, exec) -> new HasLogEvents() {
        @Override
        public <X> void onLogEvent(EventType<X> kind) {
          kind.initializeListener(augmentedDriver.get());
        }
      }).augment(driver);

    if (driver instanceof HasLogEvents) {
      augmentedDriver.set(driver);
    } else {
      System.out.println("Error error");
    }


    ((HasLogEvents) driver).onLogEvent(domMutation(mutation -> {
      seen.set(mutation);
      System.out.println(mutation.getAttributeName());
      System.out.println(mutation.getCurrentValue());
      latch.countDown();
    }));

    driver.get("https://www.google.com");
    WebElement span = driver.findElement(By.cssSelector("span"));

    ((JavascriptExecutor) driver)
      .executeScript("arguments[0].setAttribute('cheese', 'gouda');", span);

    latch.await();
    driver.quit();
  }
}
```

**Comment by pujagani** [comment]
I had a detailed look. `HasAuthentication` and `HasLogEvents` seem to be designed in way that provide a user friendly API but under the hood it uses devtools currently. The way Augmenter was designed was mainly for sending additional HTTP commands to the remote webdriver.  So there is no access to devtools in `HasAuthentication` and `HasLogEvents`. In order to do that, it seems like a major rewrite and moving parts around. However, I think it ties well with the idea of having a uniform set of front-facing APIs and under the hood based on driver capability we identify if the implementation needs BiDi or Devtools connection.  Accordingly, since most additional command related interfaces are deprecated in the Augmenter (https://github.com/SeleniumHQ/selenium/blob/632849cb88d64947367557f490253f2b6897e393/java/src/org/openqa/selenium/remote/Augmenter.java#L68), the Augmenter can adapt to new use cases.

**Comment by arsen-papoyan** [comment]
Hello,
Are there any updates on this?

**Comment by diemol** [comment]
If there were updates, they would have been posted already :)

**Comment by titusfortner** [comment]
We have a BiDi working group meeting tomorrow and part of what I'm hoping to do is agree on our planned API which is the first step in getting the implementation sorted.

**Comment by pujagani** [comment]
BiDi spec work from the Selenium side and BiDi browser side efforts are in progress. From the Selenium side, the goal is to make the BiDi APIs easy to use and have abstractions that allow passing the driver and getting the BiDi features. That mostly means no more augmenter in the future (yet to figure out and discuss this transition).

**Comment by arsen-papoyan** [comment]
Hello,
Before the implementation will be live, can anyone please suggest how I can log in with the alert window?
I have a standalone mobile web app ("https://m.site.com") and this option doesn't work for me: ("https://username:password@website"), so I use HasAuthentication, but it does not work in the case of RemoteWebDriver.

**Comment by pujagani** [comment]
Please use the code snippet shared earlier https://github.com/SeleniumHQ/selenium/issues/10828#issuecomment-1173524496

**Comment by Purus** [comment]
In the below example, what does the value "chrome" actually refers to? As per the source code, it has to be a capability. I am not sure if the value really matters.

```java
 driver = augmenter.
      addDriverAugmentation("chrome", HasLogEvents.class, (caps, exec) -> new HasLogEvents() {
        @Override
        public <X> void onLogEvent(EventType<X> kind) {
          kind.initializeListener(augmentedDriver.get());
        }
      }).augment(driver);
```

@pujagani

**Comment by pujagani** [comment]
It is used in the core implementation of Augmenter. Augmenter enhances the driver by adding interfaces it does not implement. https://github.com/SeleniumHQ/selenium/blob/000c2cf10d522a90bb765e6ff6882114eefcadc4/java/src/org/openqa/selenium/remote/Augmenter.java#L165 finds the matching list of interfaces that needs to be added by checking a predicate. The capability passed in the "`addDriverAugmentation`" is a part of the predicate check https://github.com/SeleniumHQ/selenium/blob/000c2cf10d522a90bb765e6ff6882114eefcadc4/java/src/org/openqa/selenium/remote/Augmenter.java#L132. If the capability is present then that interface is added. 

"chrome" is a valid capability 
![Screenshot 2022-10-17 at 1 09 30 PM](https://user-images.githubusercontent.com/10705590/196125170-38b96f03-6893-42b8-bffa-5578213e3e9d.png)

Which when matched returns a list of matching interfaces which includes "LogEvents"
![Screenshot 2022-10-17 at 1 42 37 PM](https://user-images.githubusercontent.com/10705590/196125320-b5c10393-18ab-4bcf-b1bf-22b239757fe2.png)

Essentially, it indicates that if the returned capabilities from the browser have the "capability name" we passed while adding the augmentation, then that interface should be added.

**Comment by Purus** [comment]
Thanks. it makes sense. But have some observations for the below code. For the below augmentation, the matching args are zero. Is `HasAuthentication` is difference scenario?

```java
        WebDriver driver = new Augmenter().
                addDriverAugmentation("chrome", HasAuthentication.class, (caps, exec) -> (whenThisMatches, useTheseCredentials) -> devTools.getDomains().network().addAuthHandler(whenThisMatches, useTheseCredentials)).augment(getWebDriver());

        ((HasAuthentication) driver).register(() -> new UsernameAndPassword(credentials.getUsername(), credentials.getPassword()));
```

**Comment by pujagani** [comment]
" For the below augmentation, the matching args are zero" - Can you please elaborate? I am afraid I do not understand the question here.
