### ISSUE TITLE
[🐛 Bug]: Cannot pass custom capabilities to handshake

### ISSUE THREAD

**Issue by AndriusZal** [SeleniumHQ/selenium#10825]
### What happened?

When trying to pass some custom desired capabilities (like access key, test name, etc), Selenium shortlists all the passed capabilities according to `_W3C_CAPABILITY_NAMES` list and losses the ones which are necessary for the handshake. This bug started after https://github.com/SeleniumHQ/selenium/pull/10494 being merged. The bug disappears if this change is reverted.

### How can we reproduce the issue?

```shell
from selenium import webdriver
options = webdriver.ChromeOptions()
options.set_capability("browserVersion", 103)
options.set_capability("testName", current_test_name)
options.set_capability("accessKey", get_browser_access_key())
webdriver.Remote('<ADDRESS_WHICH_REQUIRES_KEY>', options=options)
```

### Relevant log output

```shell
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10e475f00>
response = {'status': 401, 'value': '{\n  "message" : "No credentials provided",\n  "value" : {\n    "message" : "No credentials provided"\n  },\n  "status" : 401\n}'}
```

### Operating System

macOS Monterey

### Selenium version

Python 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

**Comment by diemol** [comment]
That is the expected behavior. You need to prefix custom capabilities. Please check the docs from the cloud vendor you are using.
