### ISSUE TITLE
[🚀 Feature]:  W3C Capabilities of InternetExplorerOptions

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/selenium#10822]
### Feature and motivation

Once we execute with Edge IE Mode, there is warn in log

```
Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [elementScrollBehavior, enablePersistentHover, ie.browserCommandLineSwitches, ie.edgechromium, ie.edgepath, ie.enableFullPageScreenshot, ie.ensureCleanSession, ie.fileUploadDialogTimeout, ie.forceCreateProcessApi, ie.useLegacyFileUploadDialogHandling, ie.usePerProcessProxy, ignoreProtectedModeSettings, ignoreZoomSetting, initialBrowserUrl, nativeEvents, requireWindowFocus, silent]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
```

I tried to set almost values from docs (https://www.selenium.dev/documentation/webdriver/capabilities/internet_explorer/),  I'm sure there are some capabilities expired in Edge IE Mode ( as we should only have this way to run IE at this moment),  but what's the qualified capability?
And meanwhile, there won't any Deprecated in InternetExplorerOptions, so user don't know what should be using with latest Selenium.

### Usage example

Full configurations case

```
  @Test
  public void internetExplorerOptionsTest() {
    ieOptions = new InternetExplorerOptions();
    ieOptions.attachToEdgeChrome();
    ieOptions.ignoreZoomSettings();
    ieOptions.destructivelyEnsureCleanSession();
    ieOptions.requireWindowFocus();
    ieOptions.introduceFlakinessByIgnoringSecurityDomains();
    ieOptions.takeFullPageScreenshot();
    ieOptions.disableNativeEvents();
    ieOptions.waitForUploadDialogUpTo(Duration.ofMillis(1000L));
    ieOptions.useLegacyUploadDialog();
    ieOptions.elementScrollTo(ElementScrollBehavior.TOP);
    ieOptions.enablePersistentHovering();
    ieOptions.usePerProcessProxy();
    ieOptions.useCreateProcessApiToLaunchIe();
    ieOptions.addCommandSwitches("-k");
    ieOptions.addCommandSwitches("-private");
    ieOptions.setCapability("silent", true);
    ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
    ieOptions.withInitialBrowserUrl("https://www.ianzhang.cn");
    driver = new InternetExplorerDriver(ieOptions);
    driver.get("https://www.bing.com");
  }
```

```
Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [elementScrollBehavior, enablePersistentHover, ie.browserCommandLineSwitches, ie.edgechromium, ie.edgepath, ie.enableFullPageScreenshot, ie.ensureCleanSession, ie.fileUploadDialogTimeout, ie.forceCreateProcessApi, ie.useLegacyFileUploadDialogHandling, ie.usePerProcessProxy, ignoreProtectedModeSettings, ignoreZoomSetting, initialBrowserUrl, nativeEvents, requireWindowFocus, silent]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/

```

Minimal Case
```
  @Test
  public void internetExplorerOptionsInputTest() {
    ieOptions = new InternetExplorerOptions();
    ieOptions.attachToEdgeChrome();
    ieOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
    driver = new InternetExplorerDriver(ieOptions);
    driver.get("https://www.bing.com");
  }
```

```
Started InternetExplorerDriver server (64-bit)
4.2.0.0
Listening on port 63513
Only local connections are allowed
6月 28, 2022 4:11:23 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
6月 28, 2022 4:11:23 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
WARN: Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [ie.edgechromium, ie.edgepath]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/

```

**Comment by diemol** [comment]
What version of Selenium?

**Comment by alaahong** [comment]
Hi @diemol  
It's Selenium 4.3.0 with IE Driver 4.2.0 .  
OS is Windows 11 
Edge is 103

**Comment by diemol** [comment]
Thanks, I was able to see the log warnings. That was a mistake I did, the validation is done properly in the `RemoteWebDriver` but not so well in `ProtocolHandshake`. This is all part of the process to remove JWP support in Java.

The issue with `InternetExplorerOptions` is that capabilities are being put at the top level and inside `se:ieOptions`, and it is only needed in `se:ieOptions`. This change was already planned.

I just pushed a change that will avoid those warnings when 4.4 is released since all capabilities will be inside `se:ieOptions`.

**Comment by alaahong** [comment]
Thanks for your following, it's fine in next version. Just wonder if any deprecated capabilities list of IE Driver ? As I mentioned in #10821 ,  seems not all capabilities still work on latest Edge IE Mode.

**Comment by diemol** [comment]
It depends on what the Edge team determines. They are being kind enough by maintaining the IEDriver these days. If not all caps are working in IE Mode, those issues should be reported to them. (See comments in the issue you linked)

**Comment by 1merzoua** [comment]
> It depends on what the Edge team determines. They are being kind enough by maintaining the IEDriver these days. If not all caps are working in IE Mode, those issues should be reported to them. (See comments in th

Hello @diemol, 

Thanks for your reply,

Have you any idea about the release date of the new IE Driver version ?

**Comment by diemol** [comment]
Not sure, I think there are no pending changes to be released.
