### ISSUE TITLE
[🐛 Bug]: Using Selenium 3.141.59 Version not able to launch Edge browser by configuring Edge for IE instance in selenium java code

### ISSUE THREAD

**Issue by sachinj256** [SeleniumHQ/selenium#10827]
### What happened?

IE mode on Edge browser.

with reference to below doc, tried with selenium version 3.141.59 but fail to call Edge browser.

https://github.com/yasin-codoid/QA-Testing/tree/LaunchEdgeBrowser-IEMode

### How can we reproduce the issue?

```shell
Code to reproduce the issue


System.setProperty("webdriver.ie.driver", <<IE-Driver-Path>>);
    InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
    Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
    ops.put("ie.edgechromium", true);
    ops.put("ie.edgepath", "msedge.exe");     // Edge Browser directory path

    edgeIe11Options.introduceFlakinessByIgnoringSecurityDomains();
    edgeIe11Options.ignoreZoomSettings();
    edgeIe11Options.enablePersistentHovering();
    edgeIe11Options.takeFullPageScreenshot();
    edgeIe11Options.disableNativeEvents();
    edgeIe11Options.requireWindowFocus();
    edgeIe11Options.destructivelyEnsureCleanSession();

    edgeIe11Options.setCapability("ignoreProtectedModeSettings", true);
    edgeIe11Options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);

    WebDriver driver;
    driver = new InternetExplorerDriver(edgeIe11Options);
    wait = new WebDriverWait(driver, 25);
    driver.get("https://github.com/");
    driver.close();
```

### Relevant log output

```shell
Using the above code, still IE browser gets invoked.

but when tried calling browser using command prompt edge browser gets invoked.

"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --new-window --ie-mode-file-url "www.google.com"
```

### Operating System

Windows 10

### Selenium version

Selenium 3.141.59 Version

### What are the browser(s) and version(s) where you see this issue?

Ms Edge - Version 102.0.1245.39, IE version - version 21H2(OS Build 19044.1706)

### What are the browser driver(s) and version(s) where you see this issue?

Browser Driver version: IEDriverServer 3.14.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
You need to use the latest version of Selenium and the IE Driver for that. Old versions might work with workarounds but it is not supported.

**Comment by diemol** [comment]
Latest versions can be seen here https://www.selenium.dev/downloads/

**Comment by alaahong** [comment]
You can take a try to set additional capability. 
Below code is fine on Selenium 3.141.59 with IEDriver 4.2.0, but it will not work if remove the ops put or capability set.

```

  @Test
  public void desiredCapabilitiesTest() {
    InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
    Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
    ops.put("ie.edgechromium", true);
    ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");    
    edgeIe11Options.setCapability("ie.edgechromium", true);
    edgeIe11Options.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");   
    driver = new InternetExplorerDriver(edgeIe11Options);
    driver.get("https://www.bing.com/");
    driver.findElement(By.id("sb_form_q")).sendKeys("Selenium");
    driver.findElement(By.id("sb_form_q")).clear();
  }

```

**Comment by sachinj256** [comment]
Thanks alaahong & diemol for quick feedback and solution, this works for me.

**Comment by sachinj256** [comment]
One more query, when I come out of the above code block, driver value getting as null, any specific reason and what should be the way to handle it

**Comment by sachinj256** [comment]
> You can take a try to set additional capability. Below code is fine on Selenium 3.141.59 with IEDriver 4.2.0, but it will not work if remove the ops put or capability set.
> 
> ```
> 
>   @Test
>   public void desiredCapabilitiesTest() {
>     InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
>     Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
>     ops.put("ie.edgechromium", true);
>     ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");    
>     edgeIe11Options.setCapability("ie.edgechromium", true);
>     edgeIe11Options.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");   
>     driver = new InternetExplorerDriver(edgeIe11Options);
>     driver.get("https://www.bing.com/");
>     driver.findElement(By.id("sb_form_q")).sendKeys("Selenium");
>     driver.findElement(By.id("sb_form_q")).clear();
>   }
> ```

Hi,  tried with the above code, it works fine, thanks. but when come out from the above block, driver value getting as Null and getting null pointer exception, can you please assist how to make driver alive outside of this code block?

**Comment by alaahong** [comment]
I guess you just facing a Java issue, not the Selenium.

e.g. If you are working with JUnit , it should be something just like

```
public class DesiredCapabilitiesTest {
  protected WebDriver driver;

  @BeforeEach
  void setupClass() {
    //XXX
  }
 
  @Test
  public void desiredCapabilitiesTest() {
    InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
    Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
    ops.put("ie.edgechromium", true);
    ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");    
    edgeIe11Options.setCapability("ie.edgechromium", true);
    edgeIe11Options.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");   
    driver = new InternetExplorerDriver(edgeIe11Options);
    driver.get("https://www.bing.com/");
    driver.findElement(By.id("sb_form_q")).sendKeys("Selenium");
    driver.findElement(By.id("sb_form_q")).clear();
  }

  @AfterEach
  void teardown() {
    if (driver != null) {
      driver.quit();
    }
  }
}

```

You just new the Driver Instance in a method. You can try to initial the Driver in a before method , that would be fine for per execution.

**Comment by alaahong** [comment]
I guess you just facing a Java issue, not the Selenium.

e.g. If you are working with JUnit , it should be something just like

```
public class DesiredCapabilitiesTest {
  protected WebDriver driver;

  @BeforeEach
  void setupClass() {
    //XXX
  }
 
  @Test
  public void desiredCapabilitiesTest() {
    InternetExplorerOptions edgeIe11Options = new InternetExplorerOptions();
    Map<String, Object> ops = (Map<String, Object>) edgeIe11Options.getCapability("se:ieOptions");
    ops.put("ie.edgechromium", true);
    ops.put("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");    
    edgeIe11Options.setCapability("ie.edgechromium", true);
    edgeIe11Options.setCapability("ie.edgepath", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");   
    driver = new InternetExplorerDriver(edgeIe11Options);
    driver.get("https://www.bing.com/");
    driver.findElement(By.id("sb_form_q")).sendKeys("Selenium");
    driver.findElement(By.id("sb_form_q")).clear();
  }

  @AfterEach
  void teardown() {
    if (driver != null) {
      driver.quit();
    }
  }
}

```

You just new the Driver Instance in a method. You can try to initial the Driver in a before method , that would be fine for per execution.
