### ISSUE TITLE
[🐛 Bug]: Deprecated functionality removed in a minor version

### ISSUE THREAD

**Issue by chrisbutler** [SeleniumHQ/selenium#10830]
### What happened?

Hi folks,

First of all, big thanks to all the active maintainers on this project. Selenium is an awesome tool and the amount of complexity you all are dealing with on a daily basis is mind-boggling. With that in mind, I hate to even be filing this issue, but I wanted to try to do my part to help out the community.

Based on my understanding of SemVer, it calls for a major version bump when backwards-incompatible changes are introduced (e.g. removing deprecated features, or possibly even the change to `move_to` behavior). Maybe I'm misunderstanding something but it seems like the 4.3 release isn't respecting that rule.

We were certainly surprised to find that those changes had been made in a minor version update, and while I imagine there may be some good reasons for the Selenium team choosing to do this it also has some potential downsides for users of the package.

Just wanted to put this out there to see if either I'm missing something here, or maybe there is some room for improvement in the way releases are handled going forward?

Thanks!

### How can we reproduce the issue?

```shell
The changelogs for 4.3 detail the removed functionality: https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.3.0
```

### Relevant log output

```shell
no relevant log output
```

### Operating System

MacOS

### Selenium version

4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by AutomatedTester** [comment]
Thanks for raising this. 

The selenium project has never followed semver mostly because even projects that claim to do follow it regularly get it wrong. 

Functionality that has been deprecated will be in sending out warnings for a minimum of 2 minor versions to give people enough time to upgrade their code. We also try to limit deprecations unless are absolutely necessary to make sure that people can generally have good upgrade paths in their code. If you want to come to discuss this further with us feel free to hit me up on slack/matrix/IRC in the #selenium-tlc channel.

**Comment by mockdeep** [comment]
@AutomatedTester is there a recommended way to update code on the previous version that is forwards compatible? This breaks a lot of tests for us.

> because even projects that claim to do follow it regularly get it wrong.

I'm not sure I understand this rationale. Even if other projects get it wrong sometimes, isn't it still worth it to try?

**Comment by mockdeep** [comment]
It looks like the docs need to be updated as well. They [still say the offsets are from the top-left corner](https://github.com/SeleniumHQ/selenium/blob/7b1c6461f618fefcb8fec4a972bc7ec1abb47c34/rb/lib/selenium/webdriver/common/interactions/pointer_actions.rb#L91-L94).

**Comment by titusfortner** [comment]
@mockdeep good catch. Would you like to make a PR for it?

**Comment by mockdeep** [comment]
Donezo: https://github.com/SeleniumHQ/selenium/pull/10872
