### ISSUE TITLE
[🚀 Feature]: Initialize findby via constructors

### ISSUE THREAD

**Issue by skyhirider** [SeleniumHQ/selenium#10836]
### Feature and motivation

@ findby is very handy with an ajax element locator factory as it solves the stale element problem while giving a fixed amount of time for elements to appear.

But when the locator needs to be language specific annotations can not be used. Having the ability to construct these objects directly in the code would be great, as driver.findelement needs a lot of boilerplate to provide the same functionality.

If this is already possible then I was not able to find it in any documentation or when asking on your irc channel which would instead mean that the docs could be updated.

### Usage example

@findby(xpath = '//div[@name='englishText']')
Webelement element

But what if I need 'germanText' instead?

new FindBy(By.xpath(String,format('//div[@name='%s']',variableText),this)

**Comment by titusfortner** [comment]
Thank you for the suggestion. The `FindBy` class in the support package was created for the `PageFactory` implementation, which is still provided, but is no longer recommended; and we do not plan to make updates to it at this time.

**Comment by skyhirider** [comment]
@titusfortner Thank you, what is the current recommended way to achieve this then except for annotations?

**Comment by diemol** [comment]
There is no other recommended way, annotations is the way to go.

**Comment by skyhirider** [comment]
Thanks, but what about the use case where you need variables inside the locators? Annotations can't do that and there is no other way to get the same functionality apart from driver.findelement and then handling the waits and exceptions or creating a utility method.

A constructor would be handy.

**Comment by titusfortner** [comment]
You would need to implement your own Page Object Model that stores the locators directly. Then you could have a method that accepted an argument to create a dynamic locator. 

```java
public By getElementByName(String name) {
    return By.xpath(String.format('//div[@name='%s']', name));
}
```

**Comment by skyhirider** [comment]
You are right. I would also need to implement a method that would use said locators while explicitly waiting until the element is available as well as re-locating the element if the webelement created via the By becomes stale.

Something that @ findby already does great, but it can't be parameterized.

What is interesting there is a 3rd party library that may do something like this, a shame its not part of Selenium itself - https://stackoverflow.com/a/66170701/1341887

**Comment by titusfortner** [comment]
Selenium has a lot to keep up with all by itself.

We've tried to be minimally opinionated to allow other libraries to provide more opinionated code options that may or may not make sense to all users.

The part that we haven't been great about is finding a way to publicize and support various add-ons and support projects. We're working to figure out how to improve that.

But yeah, I'm not exactly a fan of Page Factory implementation (https://titusfortner.com/2021/02/03/page-factory-optimization.html); if it were just up to me, we'd spin off a lot of the opinionated stuff in the support package and allow the community to maintain it.

**Comment by skyhirider** [comment]
I am surprised the factory was not marked as deprecated. Having the ability for the community to create add-ons would be great, especially something for supporting multi language deployments.

I can create my own solution, but it seems like a problem at least one one other person probably had and solved over the years selenium was live.

And reading your article is exactly why a constructor for FindBy that is not using annotations would be handy - I'm assuming FindBy's are smart and only do an element lookup if a stale element exception is thrown. The page factory could be deprecated by implementing a findby constructor if its something that is possible.

**Comment by titusfortner** [comment]
No, that's a major reason I don't care for the solution— `FindBy` is not smart, and gets in the way of you making them smarter. ☹️ 

Page Factory doesn't have to be deprecated for people to build alternate solutions, but maybe it would help to generate more conversations about it.
