### ISSUE TITLE
Can't send key combinations in Safari

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1084]
This problem was raised on the old issue tracker: https://code.google.com/p/selenium/issues/detail?id=8118

[Here is the Watir spec that fails just for safari](https://github.com/watir/watirspec/blob/master/element_spec.rb#L308)
It treats [:command, 'a'] as if just 'a' was entered.
:backspace works correctly.

**Comment by lukeis** [comment]
command + a, implies that you are trying to trigger a browser / OS level action to 'select all'. This is not going to be possible with the current safari driver as it is limited to synthetic JavaScript events only. And most websites don't attempt to implement handling those key strokes in JavaScript (it wouldn't make sense to)

If this was reported by someone else I would close it as won't/ can't fix. Up to you what you want to do with it @titusfortner

**Comment by titusfortner** [comment]
Ah, ok. I'm confused by what specs have and haven't been marked as working for Safari in the Watir project. If this has never been implemented I'm not sure why it wasn't guarded against already. I assumed it was a new bug that I should get a reference to for the spec.

If this is a synthetic JavaScript issue, we can close this and I'll mark it not implemented in the Watirspecs. Thanks.
