### ISSUE TITLE
[🐛 Bug]: [Python] [Firefox] install_addon polluting /tmp

### ISSUE THREAD

**Issue by Commaster** [SeleniumHQ/selenium#10841]
### What happened?

I'm not sure if this is a Selenium or a Marionette issue.

After multiple starts with local addon file installs I ran out of disk space and discovered a huge mess in /tmp.
A lot of copies of the local addon file (identical file size).
Any chance to automatically clean those up when we delete the temporary profile dir?

### How can we reproduce the issue?

```shell
browser = webdriver.Firefox()
browser.install_addon(os.path.join(os.getcwd(), 'NAME.xpi'), True)#addon file is in the cwd
browser.quit()
```

### Relevant log output

```shell
...
1780499 addon-ffed1201-6e45-4a10-8fa8-5c0a326680f7.xpi
1780499 addon-9b4bde59-a74d-4706-90a2-20ec1a010c80.xpi
1780499 addon-f91bb2ff-b81b-43ea-9b54-3d819ac6406f.xpi
...
```

### Operating System

Ubuntu 20.04

### Selenium version

Python 3.8.10 Selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 101

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 101

**Comment by symonk** [comment]
@titusfortner @diemol should this be the responsibility of selenium? one example in `pytest` is for its temp directories as part of its `pytester` plugin it deletes directories `>3` IIRC, should selenium perhaps prevent writing such files in a dir if a file with the same sum exists? (is that something we control even?)

**Comment by titusfortner** [comment]
Ah yeah, sorry, didn't read it closely enough; that's this issue — https://github.com/mozilla/geckodriver/issues/299

**Comment by Commaster** [comment]
> Ah yeah, sorry, didn't read it closely enough; that's this issue — [mozilla/geckodriver#299](https://github.com/mozilla/geckodriver/issues/299)

But the `rust_mozprofile` folders aren't an issue. This is about the addon files outside those folders in /tmp. In fact, even when terminating the firefox process abruptly (as described in the issue you mentioned) the `rust_mozprofile` gets cleaned up, only a `Temp-%GUID%` folder remains.
But the addon files remain no matter what on each run.

**Comment by titusfortner** [comment]
Selenium doesn't put anything in tmp, that's geckodriver, and it should be cleaning up after itself. Ask in that issue if cleaning up addons is also being worked on with that ticket or if you need to create a new one.

**Comment by Commaster** [comment]
I see... thank you!
