### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed on getting window size from firefox

### ISSUE THREAD

**Issue by ibodog** [SeleniumHQ/selenium#10848]
### What happened?

There is an exception when trying to get (or set) an existing browser window size for Firefox remote webdriver (using LambdaTest grid).

code like:
driver.manage().window().getSize()

produces error:
org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed
Command duration or timeout: 167 milliseconds
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'mypc.nowhere.net', ip: 'fe80:0:0:0:899:fc07:3009:778f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.9'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [bd8a1356-1c44-4082-9452-8bc047964991, getCurrentWindowSize {}]
Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, binary: E:\firefox\100.0\firefox.exe, browserName: firefox, browserVersion: 100.0, enableNetworkThrottling: false, moz:accessibilityChecks: false, moz:buildID: 20220419190903, moz:firefoxOptions: {args: [--width=1920, --height=1000], binary: E:\firefox\100.0\firefox.exe, prefs: {devtools.console.stdout.content: true, network.proxy.allow_hijacking_localhost: true, network.proxy.http: 127.0.0.1, network.proxy.http_port: 46000, network.proxy.no_proxies_on: , network.proxy.ssl: 127.0.0.1, network.proxy.ssl_port: 46000, network.proxy.type: 1}}, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 324, moz:profile: C:\Users\ltuser\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, performance: false, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, video: true}

### How can we reproduce the issue?
You might need access to LambdaTest Selenium Grid v4...

```shell
MutableCapabilities browserOptions = null;
browserOptions = new FirefoxOptions();
((FirefoxOptions) browserOptions).setAcceptInsecureCerts(true);
((FirefoxOptions) browserOptions).setPageLoadStrategy(PageLoadStrategy.EAGER);
((FirefoxOptions) browserOptions).addPreference("devtools.console.stdout.content", true);

HashMap<String, Object> ltOptions = new HashMap<String, Object>();
ltOptions.put("user", Config.LT_USERNAME);
ltOptions.put("accessKey", Config.LT_ACCESS_KEY);
ltOptions.put("platformName", "Windows 11");
ltOptions.put("network", false);
ltOptions.put("console", true);
ltOptions.put("selenium_version", "4.1.2");
ltOptions.put("terminal", true);
browserOptions.setCapability("LT:Options", ltOptions);

URL webDriverRemoteURL = new URL("https://my.name:myApiKey@hub.lambdatest.com/wd/hub");

WebDriver driver = new RemoteWebDriver(webDriverRemoteURL, browserOptions);

driver.manage().window().getSize();

```

### Relevant log output

```shell
org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed
Command duration or timeout: 167 milliseconds
Build info: version: '4.2.1', revision: 'ac4d0fdd4a'
System info: host: 'mypc.nowhere.net', ip: 'fe80:0:0:0:899:fc07:3009:778f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.9'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [bd8a1356-1c44-4082-9452-8bc047964991, getCurrentWindowSize {}]
Capabilities {acceptInsecureCerts: true, acceptSslCerts: true, binary: E:\firefox\100.0\firefox.exe, browserName: firefox, browserVersion: 100.0, enableNetworkThrottling: false, moz:accessibilityChecks: false, moz:buildID: 20220419190903, moz:firefoxOptions: {args: [--width=1920, --height=1000], binary: E:\firefox\100.0\firefox.exe, prefs: {devtools.console.stdout.content: true, network.proxy.allow_hijacking_localhost: true, network.proxy.http: 127.0.0.1, network.proxy.http_port: 46000, network.proxy.no_proxies_on: , network.proxy.ssl: 127.0.0.1, network.proxy.ssl_port: 46000, network.proxy.type: 1}}, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:processID: 324, moz:profile: C:\Users\ltuser\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, performance: false, platformName: WINDOWS, platformVersion: 10.0, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, video: true}
```

### Operating System

Test runner is MacOS X, running remote selenium 4 grid on LambdaTest

### Selenium version

4.3.0 on test runner, 4.2.1 on LambdaTest

### What are the browser(s) and version(s) where you see this issue?

Firefox 102

### What are the browser driver(s) and version(s) where you see this issue?

remoteWebdriver on LambdaTest v4 grid

### Are you using Selenium Grid?

4.1.2

**Comment by ibodog** [comment]
Updated the snippet to include all browser options set up.

**Comment by diemol** [comment]
Forgot to ask, does this happen when you use a local Grid?

**Comment by ibodog** [comment]
Running sample test against my local grid (at v4.3.0) and there is no similar error.  LambdaTest grid is supposed to be 4.1.2.  I also have reached out to their support with this same information.  Are there docs on how to proxy the connection between the Java libraries and the remote WebDriver?

**Comment by diemol** [comment]
Thanks for clearing that out for us. If Grid works well, it might be probably an issue in the LambdaTest cloud. Please double check with their support. 

Regarding RemoteWebDriver docs, please check https://www.selenium.dev/documentation/webdriver/remote_webdriver/
