### ISSUE TITLE
[🚀 Feature]: selenium 4 supports PageFactory

### ISSUE THREAD

**Issue by agaramudhala** [SeleniumHQ/selenium#10842]
### Feature and motivation

selenium 4 supports PageFactory similar to Se v3 

### Usage example

public class PublicPage {
    public WebElement element;
  }

  public static class Page {
    @FindBy(name = "someForm")
    WebElement formElement;

    @FindBy(tagName = "div")
    @CacheLookup
    List<WebElement> divs;
  }

**Comment by titusfortner** [comment]
It still works, but we recommend against using it.
