### ISSUE TITLE
[🐛 Bug]: Debug and Run differ from crashing the script

### ISSUE THREAD

**Issue by greenthus** [SeleniumHQ/selenium#10853]
### What happened?

When I use Run for the script it fails at row #139
However when I Debug the script it fails at row #20.

Additional information:
The .cs file uses a helper.cs

the helpers file:
![image](https://user-images.githubusercontent.com/104067056/177563055-b89041fe-6542-427f-9984-383da6a25c8b.png)

![image](https://user-images.githubusercontent.com/104067056/177563600-4d45c6a3-86ef-4c24-8e51-a5e14abca328.png)

### How can we reproduce the issue?

```shell
Use Run,
then use Debug
/\
\/
(starting from the small icon by mouseclick)
```

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.FixAnalyzers.CSharpFixerWithFixAllAnalyzer cannot be created from C:\Users\Specimend\.nuget\packages\microsoft.codeanalysis.analyzers\1.1.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll: Could not load type 'Microsoft.CodeAnalysis.Analyzers.FixAnalyzers.FixerWithFixAllAnalyzer`1' from assembly 'Microsoft.CodeAnalysis.Analyzers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=specimend'..	CT.Services		1	Active
```

### Operating System

Windows 10

### Selenium version

latest stable

### What are the browser(s) and version(s) where you see this issue?

Edge Version 103.0.1264.44 (Official build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver latest

**Comment by titusfortner** [comment]
I'm also not following how it is a Selenium issue if it works fine without debugging. Seems like a potential issue in the debugger?

**Comment by valentijnpeters** [comment]
I agree to that last part. I actually think it is a issue in the debugger....

**Comment by pujagani** [comment]
I am not very clear which line is causing the crash. But typically in cases where a code behaves differently during running and debugging, there is a good chance if threads are involved that there is a potential deadlock or a race condition since the debugger slows things down significantly so the same does not resurface when running. But in this case, as mentioned by previous contributors, the debugger seems to have an issue.

**Comment by diemol** [comment]
I'm going to close this as there is nothing for us to troubleshoot related to Selenium. If there is an issue related to Selenium please provide all the information required in the template.

**Comment by greenthus** [comment]
What we don't understand is as we set var wait = new WebDriverWait(webDriver, TimeSpan.FromSeconds(40));
it does not work but if we use thread.sleep it does.

**Comment by greenthus** [comment]
And also we agree now it is Visual Studio related. not Selenium caused. So I will give Bill a call I guess...

**Comment by valentijnpeters** [comment]
A sort of solution was:

#if DEBUG
Thread.Sleep...
#end
