### ISSUE TITLE
Screenshoot content sometimes cropped with the IE driver

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#1085]
The InternetExplorer driver sometimes crops the content of a web page when it takes a screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/918557/10170317/3524e380-66cc-11e5-9caf-c2be6166c873.png)

Environment :
Windows 8.1 64bit, IE11, IE Driver 2.47.0 32bit

To reproduce:

    var driver = new InternetExplorerDriver();
    driver.Manage().Window.Size = new System.Drawing.Size(800, 600);
    driver.Navigate().GoToUrl("https://en.wikipedia.org/wiki/Eurytios_Krater");
    driver.GetScreenshot().SaveAsFile(@"screenshot.png", ImageFormat.Png);
    driver.Quit();

This is due to the resizing that sometimes alter the size of the content.
A fix would be to check and readjust the new size of the window and take the offsetWidth and offsetHeight for the capture.
Here is a c# example:

    int docWidth = doc.scrollWidth;
    int docHeight = doc.scrollHeight;
    
    var view = (IOleDocumentView)doc;
    view.SetRect(new RECT(0, 0, docWidth, docHeight));
    
    if (docHeight < doc.scrollHeight) {
        view.SetRect(new RECT(0, 0, docWidth, doc.scrollHeight));
    }
    int screenshotWidth = doc.offsetWidth;
    int screenshotHeight = doc.offsetHeight;
    ...

**Comment by jimevans** [comment]
And how do you handle so-called "infinite scrolling" pages? As soon as you adjust the size, it then no longer matches the size of the document.

And I remind you again that the concept of a "full page" screenshot is going away, in favor of taking an image of the current view port only. If you have a problem with this, I suggest you take it up with the [W3C working group producing the WebDriver specification](http://www.w3.org/testing/browser/).

**Comment by jimevans** [comment]
Fixed in e45a461. Please note carefully the commit message. There are corner cases that will not be fixed after this update.

**Comment by florentbr** [comment]
> And how do you handle so-called "infinite scrolling" pages? As soon as you adjust the size, it then no longer matches the size of the document.

I don't think "infinite scrolling" is relevant here since the content is loaded asynchronously and triggered by scrolling events. The sizing of the window to the scroll width/height doesn't change the size of the content, at least not intentionally. For example, I successfully took a screenshot on this "infinite scrolling" page by resizing the window a second time :
https://twitter.com/cnnbrk
Moreover, if the content is resized on the second call, then it most certainly was on the first call too.

> And I remind you again that the concept of a "full page" screenshot is going away, in favour of taking an image of the current view port only. If you have a problem with this, I suggest you take it up with the W3C working group producing the WebDriver specification.

I understand and I don't have a problem with that, either way I'm good. I only have a beef with half working/buggy features.
As the only option here, I'm just expecting to have what the Firefox driver gives us when taking a full screenshot.

> Fixed in e45a461. Please note carefully the commit message. There are corner cases that will not be fixed after this update.

I disagree with this fix as it intentionally changes the size of the content and therefore produce a different rendering. The scrollWidth property doesn't include the size of the scrollbar, so this fix produces a content that is 17px wider. Moreover since IE10 the scroll bar can be overlaid on the content and doesn't even interfer in the width: http://www.bbc.co.uk/news

Though, it's not a bad idea and it would be a perfect solution if the scroll bar were still present after the resizing. It doesn't seems to be possible by setting the overflowY css property (I'm getting an exception probably due to cross processing restrictions).
Another solution would be to remove 2px to the targeted size to force the scroll bar to stay:

    int scrollWidth = docEle.scrollWidth;
    int scrollHeight = docEle.scrollHeight;

    if (scrollHeight > clientRect.Height && winEle.innerWidth != docEle.offsetWidth) {
        scrollHeight -= 2;
        scrollWidth += GetSystemMetrics(SM_CXVSCROLL);
    }
    if (scrollWidth > clientRect.Width && winEle.innerHeight != docEle.offsetHeight) {
        scrollWidth -= 2;
        scrollHeight += GetSystemMetrics(SM_CYHSCROLL);
    }

**Comment by jimevans** [comment]
I think you may have misinterpreted the scroll-bar-thickness-calculation bit. There is no way that I know of to generate a full-page screenshot in IE without resizing the window. This means that you'll potentially trigger rendering changed _no matter what_. Nevertheless, this change no longer modifies the window size in a dimension where it is not required to do so. The previous behavior **would** do so, potentially narrowing the window size, which did cause the behavior you reported. Leaving the scroll bar in place would most emphatically _**not**_ produce screenshots consistent with those generated by the Firefox driver. I will comment more with further examples when I'm at my desk and not mobile. I would encourage you to engage in further discussion on the matter in the project IRC channel.

**Comment by florentbr** [comment]
> I think you may have misinterpreted the scroll-bar-thickness-calculation bit. There is no way that I know of to generate a full-page screenshot in IE without resizing the window. This means that you'll potentially trigger rendering changed no matter what

I'm aware that your fix is trying to compensate the thickness of the scrollbar and nerve implied that it is possible to get the screenshot of the content without resizing the window. I'm just stating that the window need to be resized (measured with USER32:GetWindowRect) without resizing the content (measured with scrollWidth and scrollHeight).

>  Nevertheless, this change no longer modifies the window size in a dimension where it is not required to do so. The previous behaviour would do so, potentially narrowing the window size, which did cause the behaviour you reported.

With the current version (2.47.0.3), the driver measures the content of the page with scrollWidth and scrollHeight and then resize the window to these values.
While it is ok for most of the web pages, it is not for pages using "Viewport Sized Typography" CSS (vw, vh). The issue with this is that it makes the scroll bars disappear with potentially an impact on the scrollHeight. This is the case with wikipedia: https://en.wikipedia.org/wiki/Eurytios_Krater

Now with your fix (2.47.0.4), the driver measures the content of the page with scrollWidth and scrollHeight and then resize the window to these values plus the size of thickness of the scroll bar (if any). The issue with this is that once the window is resized, the scroll bar disappear, increasing the with/height of the content by the thickness of the scroll bar and therefore generates a different layout.

> Leaving the scroll bar in place would most emphatically not produce screenshots consistent with those generated by the Firefox driver. 

Here is an example that shows the need to force the scroll bar with your fix:
![test-wikipedia](https://cloud.githubusercontent.com/assets/918557/10197128/0f43eda6-678e-11e5-96ee-20cf40d96954.png)

**Comment by jimevans** [comment]
Alright, I'll try one more time. If this doesn't provide a satisfactory result, I'm throwing my hands up. The next commit will resize the window to the proper size to display the entire DOM, less 2 pixels in either direction that display a scroll bar. This should retain the scroll bars, which will be cropped out of the resulting image. This will be 2.47.0.5, when I'm done with the commit.

**Comment by florentbr** [comment]
I may have found a way to force the scroll bar.
I'll let you know tomorrow if it's a reliable way.

**Comment by jimevans** [comment]
Bear in mind that I really don't want to be manipulating the DOM within the screenshot command handler. Far better to simply manipulate the window attributes using the Windows API. If your solution involves manipulating DOM or CSS properties, it'll likely be a non-starter.

**Comment by florentbr** [comment]
As it turns out, forcing the scroll bar using CSS (overflowX/overflowY) is not reliable since there is too much logic to take into account. So the best remaining solution is to remove 2px on the height to force the vertical scroll bar and to add its thickness to the width.
This operation should be done only when the content is higher than the height of the window.
In case the vertical scroll bar is overlaid (www.bbc.com/news), this operation must be skipped.
Moreover, there is no need to deal with the horizontal scrollbar thickness as it doesn't contribute to the construction of the layout (or slightly and messing with the width produces much more side effects).

Now regarding the last commit [ab1e647](https://github.com/SeleniumHQ/selenium/commit/219e8982ae64c1c8e5f5b9da1a10e572496c7450) , it is almost correct.
The screenshot is just missing 17 pixels on the width/height and creates a 2 pixels black border in some cases:
https://en.wikipedia.org/wiki/Type_920_hospital_ship (800x600)
https://en-gb.facebook.com (800x600)
http://www.bing.com/search?q=selenium (800x600)

![sc-ie-facebook](https://cloud.githubusercontent.com/assets/918557/10245749/82b1b05a-6902-11e5-9b49-e2186ba846da.png)


I slightly modified the last commit to include the scrollbar thickness and to remove the 2px black border (ScreenshotCommandHandler.h line 162):

    if (original_height > target_window_height) {
      target_window_height = original_height;
    } else if (target_window_width != original_width) {      
      //If the content width equals the window width then
      //the scrollbar is overlaid and there is no need to
      //add the thickness of the scrollbar.
      document_info.height -= 2;
      target_window_height -= 2;
      target_window_width += ::GetSystemMetrics(SM_CXVSCROLL);
    }
    
    if (original_width > target_window_width) {
      target_window_width = original_width;
    }

I rebuilt the server and successfully took a screen of the right size for the following web sites:
https://en.wikipedia.org/wiki/Eurytios_Krater
https://en-gb.facebook.com
http://www.bbc.co.uk/news
https://www.youtube.com
https://www.amazon.com
https://twitter.com/CNN
http://www.ebay.com/
https://login.live.com/
https://www.linkedin.com/
http://www.bing.com/search?q=selenium
http://www.msn.com/en-gb/

**Comment by jimevans** [comment]
You realize that by adding in the height of the vertical scroll bar to `target_window_width`, you've come full circle to the exact solution you complained about before, right? Only now, you're resizing the entire window to be wide enough to include the scroll bar width, which could trigger a flow redraw. If you change `target_window_width` *at all*, you're leaving yourself open to that kind of layout recalculation.

**Comment by jimevans** [comment]
Further investigation for one of the sites you deem problematic due to "hidden" scroll bars in IE. For http://www.bbc.co.uk/news, I've taken screenshots in both Firefox and IE 11, with the window width set by the driver to be 800px. For the Firefox screenshot, that yields a screenshot of width 771 pixels; for IE, the width of the screenshot is 784 pixels. This means that the difference between the window width and the screenshot image width is 29 pixels for Firefox, and 16 pixels for IE. As it happens, this is the exact difference between `window.outerWidth` and `document.documentElement.scrollWidth` for each browser. Can you explain how this is incorrect, given that the browsers themselves represent this difference?

**Comment by florentbr** [comment]
> Outside of the blank 2-pixel border in IE, which I agree should be adjusted, can you explain how this is incorrect, given that the browsers themselves represent this difference?

It's just like you said, there is nothing incorrect with "http://www.bbc.co.uk/news" except for the blank 2-pixels.

Since this back and forth is not going anywhere, I took the screenshot of 25 of the most visited US websites for v2.48.0.0, v2.47.0.3 and created a fix [@e9a3677](https://github.com/florentbr/selenium/commit/e9a3677503cb7cebf7a4c82c8c57c2e873ae4e7b). In the table below, you'll find the cropping lengths as well as the presence of the scroll bar or not. 

**Screenshots:**
https://drive.google.com/folderview?id=0B9bjVGLYkEX_bVM2Y01XTndqOXM&usp=sharing

**Resuts table:**
![image](https://cloud.githubusercontent.com/assets/918557/11156478/0b886aa6-8a44-11e5-9e35-e3e9c01105e1.png)

As you can see with v2.48.0.0 most of the screenshots have the page content hidden by the scrollbars. I managed to fix most of the issues with the commit [@e9a3677](https://github.com/florentbr/selenium/commit/e9a3677503cb7cebf7a4c82c8c57c2e873ae4e7b) without deteriorating the performance and without pulling the DOM. All the remaining issues are tagged as "FAILED" and unfixable by resizing the window since the content is build according to the view size or requires scrolling to be loaded.

**Branch:** https://github.com/florentbr/selenium/tree/fix-%231085
**Commit:** https://github.com/florentbr/selenium/commit/e9a3677503cb7cebf7a4c82c8c57c2e873ae4e7b
**Build:** https://drive.google.com/open?id=0B9bjVGLYkEX_eG1wanBBZzBqSmM

**Comment by jimevans** [comment]
How do these screenshots compare (in size, content, and layout) to those generated via the Firefox driver? If they compare favorably, and the behavior after your change satisfies you, I'll be happy to take your change as a pull request. Please remember to rebase your commit, and to sign the [Contributors License Agreement](https://spreadsheets.google.com/spreadsheet/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0), if you haven't already done so.
