### ISSUE TITLE
[🐛 Bug]: [C#] [Chrome] Cannot allow Chrome to know Location

### ISSUE THREAD

**Issue by MarioMartinPlaza** [SeleniumHQ/selenium#10850]
### What happened?

Hi,

I can't allow Chrome to know Location when appears the popup asking if i want to allow.

I try a lot of solutions that i found on internet (Stackoverflow, medium, this Issue list, etc..) but nothing work and i don't know if i'm doing somenthing wrong or there are some bug in the new versión of selenium (i tried to downgraded to 4.0.0 and still the problem)

I Use the following ChromeOptions:

```
  chromiumOptions.AddArgument("--disable-infobars");
  chromiumOptions.AddArgument("--ignore-certificate-errors");
  chromiumOptions.AddArgument("--allow-running-insecure-content");
  chromiumOptions.AddArgument("--disable-blink-features=AutomationControlled");
  chromiumOptions.AddArgument("--disable-dev-shm-usage");
  chromiumOptions.AddArguments("headless");
  chromiumOptions.AddAdditionalChromeOption("useAutomationExtension", false);
  chromiumOptions.AddExcludedArgument("enable-automation");
  chromiumOptions.AddArguments("--disable-gpu");
  chromiumOptions.AddArgument("--no-sandbox");
```

And i tried the following options whithout results:

```
chromiumOptions.AddUserProfilePreference("profile.default_content_settings.geolocation", 1);
chromiumOptions.AddUserProfilePreference("profile.managed_default_content_settings.geolocation", 1);
```

Also i tried with cdp command

```
Dictionary<string, object> commandParameters = new Dictionary<string, object>();
commandParameters = new Dictionary<string, object>();
commandParameters.Add("origin", "https://www.openstreetmap.org");
commandParameters.Add("permissions", new List<string>() { "geolocation" });
seleniumBrowser.ExecuteCdpCommand("Browser.grantPermissions", commandParameters);
```

But nothing works and still appear the Chrome Location Popup asking if i want to allow.

Thanks in advance!

### How can we reproduce the issue?

```shell
Navigate to https://www.openstreetmap.org and click in this button //span[@class='icon geolocate']
```

### Relevant log output

```shell
See above
```

### Operating System

Windows 10

### Selenium version

DotNet 4.3.0 

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060.66

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Sorry, we can't help with this, either. Selenium is just taking what you provide to the classes sending it to the driver to tell it what to do. What the driver supports and how the browser behaves is completely up to Google. SO and the rest are the right places to look.
