### ISSUE TITLE
[🐛 Bug]: selenium 4 issue with identifying element with css selector

### ISSUE THREAD

**Issue by ravi005e** [SeleniumHQ/selenium#10862]
### What happened?

trying to identify css selector driver.findElement(By.css("input[name='username']"), get message not able to findElement, used to work in selenium 3x

### How can we reproduce the issue?

```shell
driver.findElement(By.css("input[name='username']")
```

### Relevant log output

```shell
unable to find element
```

### Operating System

mac bigsur

### Selenium version

java

### What are the browser(s) and version(s) where you see this issue?

chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 102

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
The correct code is:

```java
driver.findElement(By.cssSelector("input[name='username']")
```
Here's an example in our test suite:
https://github.com/SeleniumHQ/selenium/blob/trunk/java/test/org/openqa/selenium/ElementFindingTest.java#L548
