### ISSUE TITLE
[🐛 Bug]: Setting profile with set_preference doesn't work with webdriver

### ISSUE THREAD

**Issue by theCarefulIcarus** [SeleniumHQ/selenium#10864]
### What happened?

Hey guys! I'm only getting started with my first intent to build a web scraper with Python, Selenium, BeautifulSoup and Firefox. I've been searching the whole afternoon trying to get my head around which methods are deprecated or not and have seen many things (desiredCapabilities, profile classes, etc.) that are all deprecated. Also saw how they did it in Java or other languages but I couldn't find a solution to my specific problem.

I want to load my usual firefox (release-default) profile to be able to use the Widevine Content Decryption Module Plugin to load the amazon music page where I want to get data from.

The problem is I can't make the firefox window start with the desired add-on or profile. 

Someone else has had a similiar issue but with a remote webdriver  #9949, but I'm not sure if it's the same problem because I don't do anything with remote webdrivers.

Also mentioned was the use of prefs or zipping the profile but honestly I don't know how or if that would work.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options

options = Options()
profile_path = r'D:\Omnia\Privat\Sonstiges\jj0zhvr9.Scraper Profile'

options.set_preference('profile', profile_path)
service = Service(r'./driver/geckodriver.exe')

driver = webdriver.Firefox(options=options, service=service)
driver.get("https://music.amazon.com")
```

### Relevant log output

```shell
.
```

### Operating System

Windows 11

### Selenium version

Python 3.8.5

### What are the browser(s) and version(s) where you see this issue?

Firefox 102.0.1

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.31.0

**Comment by titusfortner** [comment]
If it's an add-on, you can try the `install_addon()` method on the driver instance after it is already created.

**Comment by theCarefulIcarus** [comment]
Thanks for the quick answer!
I finally found an option how I could load the whole profile that worked:
`options.add_argument('-profile')
options.add_argument(profile_path)
`
You should use a new firefox profile though, not the default one, because the folder is read-only and didn't work for me.

**Comment by titusfortner** [comment]
It is recommended:
1. Not to use a profile if you can set the prefs/args/addons that you want without it
2. If you have to use a profile, set it with the profile method on the options class (might be a property in Python, can't remember)
