### ISSUE TITLE
[🐛 Bug]: Custom SlotMatcher not working as expected

### ISSUE THREAD

**Issue by ketanb02** [SeleniumHQ/selenium#10867]
### What happened?

Creating a custom Slot Matcher - where if user is not passing the custom capability, the custom slot matcher code will add the key and value for the  capability and then will match.

Node 1 -  "c:customCap":"beta"
Node 2 -  "c:customCap":"alpha"
Node 3 -  "c:customCap":"default"

Scenario - User is only passing browser as chrome, so now my custom slot matcher code has added the "c:customCap":"default". But still Selenium grid is not respecting this added capability and execution is going to any of the nodes irrespective of the value of "c:customCap". 

Expected - The request should go to  Node 3 -  "c:customCap":"default"

### How can we reproduce the issue?

```shell
I am adding c:customCap to the passed capability and then matching and returning

boolean custCapMatch = stereotype.asMap().get("c:customCap").equals(capabilities.asMap().get("c:customCap"));

return basicChecks && custCapMatch;

basicChecks  is only checking the default selenium grid capabilities

Node setup

java -jar selenium-server-4.3.0.jar node --detect-drivers false --driver-configuration display-name="Chrome Beta" max-sessions=2 stereotype={\"browserName\":\"chrome\",\"c:customCap\":\"beta\"} --port 5557

java -jar selenium-server-4.3.0.jar node --detect-drivers false --driver-configuration display-name="Chrome1" max-sessions=2 stereotype={\"browserName\":\"chrome\",\"c:customCap\":\"alpha\"} --port 5558

java -jar selenium-server-4.3.0.jar node --detect-drivers false --driver-configuration display-name="Chrome2" max-sessions=2 stereotype={\"browserName\":\"chrome\",\"c:customCap\":false} --port 5559
```

### Relevant log output

```shell
orgcap - {browserName=chrome, platformName=WINDOWS, acceptInsecureCerts=true}
orgcap - [acceptInsecureCerts, browserName, platformName]
modcap - {c:customCap=default, browserName=chrome, platformName=WINDOWS, acceptInsecureCerts=true}
newcap - [acceptInsecureCerts, browserName, c:customCap, platformName]
added customCap
c - true
b - true
11:00:11.674 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
```

### Operating System

Windows 10

### Selenium version

selenium-server-4.3.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

chrome 103

### Are you using Selenium Grid?

4.3.0

**Comment by diemol** [comment]
Not sure why this has been created as an issue. It seems you are trying to provide your own custom SlotMatcher, if you need help, please come to our chats (link below) and we'd be happy to help. I will tag this as a question and close it since it is not an issue with the normal released Selenium Grid.

**Comment by ketanb02** [comment]
Not sure but I think its the issue with normal Selenium Grid. If i added the c:customcap using customSlotMatcher, grid should consider it. But its not happening

modcap - {c:customCap=default, browserName=chrome, platformName=WINDOWS, acceptInsecureCerts=true}
newcap - [acceptInsecureCerts, browserName, c:customCap, platformName]

If you see above message when "c:customCap=default" is present - it should only route to node which has this capability but its not happening. Its routing with any node.

Though i have also posted it as question. 

Thank you
