### ISSUE TITLE
[🚀 Feature]: Support Select Lists in Javascript

### ISSUE THREAD

**Issue by PeteSwauger** [SeleniumHQ/selenium#10879]
### Feature and motivation

Our web application has implemented multi-select lists and I want to exercise selecting multiple list entries in our automated tests.

### Usage example

After building a list of values to include or exclude in a query, the user can multi-select values in the list to remove with one button click.  I cannot automate this with our code that is implemented in javascript.

**Comment by titusfortner** [comment]
What exactly isn't working for you?

If you locate the options you want to select and send the click command, Selenium should select them without de-selecting other options. My implementation of this is in Ruby not JavaScript, but there is nothing special involved, just click everything you want to be selected.

**Comment by PeteSwauger** [comment]
Thanks for your comment.  Would you share an example of the code needed?  I have tried various things but no luck.

**Comment by diemol** [comment]
What did you try? Can you share your code as well, please?

**Comment by PeteSwauger** [comment]
The following code finds the list items and clicks on each, but when the second is clicked the first is unselected.  I need both to be selected.   

   let dropdownItems = await driver.findElements(By.xpath("//li[contains(@class,'ui-listbox-item ui-corner-all')]//span"));
    await driver.actions().keyDown(Key.CONTROL);
    for (const item of dropdownItems) {
            await item.click();
    }

**Comment by titusfortner** [comment]
You don't need to use keyDown. Just click everything you want and it should keep the others selected still.
