### ISSUE TITLE
[🚀 Feature]: Keep support for MoveToElementOffsetOrigin.TopLeft

### ISSUE THREAD

**Issue by Hujanita** [SeleniumHQ/selenium#10874]
### Feature and motivation

Starting version 4.3 MoveToElementOffsetOrigin.TopLeft is not supported anymore (only Center is). Is it possible to bring this back in action MoveToElement? We have tests that are dedicated to click on certain points in canvas and recalculation from center is with our dataset simply impossible. I dont know what exactly happened that you stopped supporting this option for version 4.3 but for us is crucial breaking change.

### Usage example

We simply want the option to calculate from top left corner like it was in version 4.2. Just make the center option default value but please consider to still supporting this otherwise we dont know how to change our data sets.
[Obsolete("Starting in Selenium 4.3 only MoveToElementOffsetOrigin.Center will be supported")]
    public Actions MoveToElement(
      IWebElement toElement,
      int offsetX,
      int offsetY,
      MoveToElementOffsetOrigin offsetOrigin)
    {
      Actions.GetLocatableFromElement(toElement);
      if (offsetOrigin == MoveToElementOffsetOrigin.TopLeft)
      {
        Size size = toElement.Size;
        int xOffset = offsetX - size.Width / 2;
        int yOffset = offsetY - size.Height / 2;
        this.actionBuilder.AddAction(this.defaultMouse.CreatePointerMove(toElement, xOffset, yOffset, this.DefaultMouseMoveDuration));
      }
      else
        this.actionBuilder.AddAction(this.defaultMouse.CreatePointerMove(toElement, offsetX, offsetY, this.DefaultMouseMoveDuration));
      return this;
    }

**Comment by titusfortner** [comment]
Your suggestion only works for elements that are completely inside the viewport.

Since Selenium does not scroll by default, it can't guarantee that the pointer is in the upper left hand corner of the element.

Users can add this functionality in their projects if they choose to.
