### ISSUE TITLE
[🐛 Bug]: Blank Web Page Dialog after a button clicked in IE mode on Edge , but working in manual way.

### ISSUE THREAD

**Issue by IronFist000** [SeleniumHQ/selenium#10875]
### What happened?

I'm Automating an Website in my organization using selenium Java in IE Mode on Edge, everything is working fine until I clicked this button it is showing blank webpage dialog pop window but when I tried this flow from beginning by manually clicking on that button it is going to open a new window the redirects to the payment page (_See 3rd image_ ) but that is not happening in automation and I've noticed that when I had start my application it displays login page that is working on **IE 11 mode** compatibility after performing login the home page is opened that is in **IE mode 5** and rest of the flow continuous in IE mode 5 only, till that button that is bringing a new webpage dialog popup window, I've checked that payment window is running on **IE 11 mode** while running the flow manually. So my question is the IE driver not able to switch modes from **IE 5 to IE 11** but at the beginning the mode got changed from **IE 11 to IE 5** . 
![image](https://user-images.githubusercontent.com/109272734/178983064-6783db43-2a51-4f16-980a-69b577307af4.png)

In this page that payment button is present, this page is running on **IE 5 Mode**

![image](https://user-images.githubusercontent.com/109272734/178984485-1101c14c-c9d6-4333-840c-523993b14cda.png)

when I'm trying to do manually from the beginning and come to this page and click on the payment button then it opens new window that is running on **IE 11 Mode**

![image](https://user-images.githubusercontent.com/109272734/178985056-0f4f85fc-1d22-443f-9d38-7958cea8dbf3.png)

But in the automation when I try to click on the payment button, then it is showing blank webpage dialog popup window as you can see in the first image. Please help me with this problem has been suffering from two days.

### How can we reproduce the issue?

```shell
I'm Afraid that you cannot able to reproduce the flow because the application is running in Intranet.
```

### Relevant log output

```shell
No errors were came, the issue is about the visibility of the window.
```

### Operating System

Windows 10

### Selenium version

Java 4.2.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge - 101.0.1210.39 and IE - 11

### What are the browser driver(s) and version(s) where you see this issue?

Internet Explorer Driver Server - 32 bit -- 4.2.0.0 version

### Are you using Selenium Grid?

No Selenium Grid is used

**Comment by diemol** [comment]
Not sure how we can help here because there is not a way we can either reproduce this nor verify if the behavior is correct or not.

I will share links below where you can post your question and also some links where you can reach out to the Edge team (who has been kind enough to drive the IE mode implementation).
