### ISSUE TITLE
[🐛 Bug]: Not able to run the test in non headless mode in linux

### ISSUE THREAD

**Issue by amitkpal83** [SeleniumHQ/selenium#10876]
### What happened?

Not able to run the test in non headless mode in linux. I have created the docker linux image and running the test in container. Test are running fine with --headless option but without that its not working. Below is the error

  Error Message:
   OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

### How can we reproduce the issue?

```shell
Any test we can take and run in linux enviroment without --headless chrome option
```

### Relevant log output

```shell
Error Message:
   OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
```

### Operating System

Debian

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 103

**Comment by diemol** [comment]
You need to have Xvfb installed to run those tests in a container. We do not troubleshoot the docker image you have created, but we offer ones ready to use https://github.com/SeleniumHQ/docker-selenium
