### ISSUE TITLE
[🐛 Bug]: Can't compile wait.until(ExpectedCondition) method

### ISSUE THREAD

**Issue by davbalabekyan** [SeleniumHQ/selenium#10883]
### What happened?

I use explicit wait for waiting in order to element to be clickable , but I get compile error when I write 
       Wait<WebDriver> wait = new WebDriverWait(driver,Duration.ofSeconds(15);
       
       wait.until(ExpectedConditions.elementToBeClickable(target));

### How can we reproduce the issue?

```shell
I don't know
```

### Relevant log output

```shell
/Users/dav/IdeaProjects/WikipediaTest/src/main/java/helpers/WaitHelper.java:26:21
java: method until in interface org.openqa.selenium.support.ui.Wait<F> cannot be applied to given types;
  required: java.util.function.Function<? super org.openqa.selenium.WebDriver,T>
  found: org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
  reason: cannot infer type-variable(s) T
    (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,T>)
```

### Operating System

MacOS

### Selenium version

4.2.1

### What are the browser(s) and version(s) where you see this issue?

102.0.1 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

0.31.0

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Update your Selenium version, this was the fix - #10695
