### ISSUE TITLE
[🚀 Feature]: do we have any plan to support Safari on grid 4?

### ISSUE THREAD

**Issue by RayChenLDL** [SeleniumHQ/selenium#10885]
### Feature and motivation

Safari is a browser most of the senior managers are using. do we have any plan to support it?

### Usage example

senior managers are using mac book with safari

**Comment by diemol** [comment]
It has always been supported. If you are facing any issues implementing it, I'll leave some links below you can use to ask for help.

**Comment by RayChenLDL** [comment]
Thanks，do you have any link on how I could start useing it? Is it a docker node and could work with hub container? I have been using selenium grid 4 docker container including hub, chrome node and Firefox node. I never see there is a safari node, is there ?

**Comment by titusfortner** [comment]
Duplicate of https://github.com/SeleniumHQ/docker-selenium/issues/957
