### ISSUE TITLE
Getting WebGL issue with Selenium - WebDriver[🐛 Bug]: 

### ISSUE THREAD

**Issue by arsen-papoyan** [SeleniumHQ/selenium#10887]
### What happened?

Could you please help to understand why I am getting the WebGL problem in the case of WebDriver-Selenium?
![WebGL](https://user-images.githubusercontent.com/74778982/179543898-e5d8afc9-de8d-4211-b32b-7c213c0983c4.png)

### How can we reproduce the issue?

```shell
When I open the game manually, this does not happen, but there is a WebGL issue when running the automation test.
The problem arose after chrome version: 101, before that everything was working fine.
In Firefox everything works fine.
```

### Relevant log output

```shell
Please find the attached screenshot.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.3.0 , JavaSE 14: version 16.0.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060.114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

### Are you using Selenium Grid?

Selenium Grid (selenium server 4.1.4)

**Comment by cocorossello** [comment]
I assume that you are using grid with docker container. I'm not sure if it's a chromedriver issue, it only happens inside a docker container, so not sure where should this issue be reported (not a selenium issue at all, anyway).

Let's see if someone gives a hint in the chromedriver team.

I opened this issue in stackoverflow, but I had no luck https://stackoverflow.com/questions/70948512/how-to-enable-webgl-in-headless-chrome-96-within-selenium-docker-project-to-r

**Comment by arsen-papoyan** [comment]
@cocorossello Thank you for your comment.
I don't use the docker container, there is a problem if it runs on the local machine. 
I opened a question on https://bugs.chromium.org/ but got no response.
BTW, the problem exists in Windows 10, in macOS everything works fine.

**Comment by cocorossello** [comment]
My problem with webgl is solved with chrome 104, you should try it
