### ISSUE TITLE
[🐛 Bug]:  Touch/flick API is giving "Cannot call non W3C standard command while in W3C mode" in POSTMAN

### ISSUE THREAD

**Issue by vishnuprakash9845** [SeleniumHQ/selenium#10881]
### What happened?

Tried to test all the Selenium API's in Postman, most of them worked but few of the API's started to give message like "Cannot call non W3C standard command while in W3C mode".

1. In the Postman called a Create Session API and captured the Session ID.
POST - [ http://localhost:9515/session]

2. Using this Session ID navigated to URL and maximized the browser window.
POST - [http://localhost:9515/session/{{sessionId}}/url]
POST - [http://localhost:9515/session/{{sessionId}}/window/maximize]

3. Tried to Identify the Element by POST Call
POST - [http://localhost:9515/session/{{sessionId}}/element]

4. Tried to call below API with respective body values and every time getting the same message.
![image](https://user-images.githubusercontent.com/24207575/179250126-b94d212c-b27c-4446-aea6-dfc457814371.png)
![POSTMAN2](https://user-images.githubusercontent.com/24207575/179250811-9e45dda1-db60-4888-acd3-802b46a26011.PNG)

Can anyone help me solving this scroll issue using POSTMAN.

### How can we reproduce the issue?

```shell
API: POST - http://localhost:9515/session/{{sessionId}}/touch/flick

Body: 
{
    "element":"{{nameBoxElement}}",
    "xoffset ":0,
    "yoffset ":250,
    "speed":10
}
```

### Relevant log output

```shell
{
    "value": {
        "error": "unknown command",
        "message": "unknown command: Cannot call non W3C standard command while in W3C mode",
        "stacktrace": "Backtrace:\n\tOrdinal0 [0x01476463+2188387]\n\tOrdinal0 [0x0140E461+1762401]\n\tOrdinal0 [0x01323D78+802168]\n\tOrdinal0 [0x01346D39+945465]\n\tOrdinal0 [0x01347AD6+948950]\n\tGetHandleVerifier [0x017171F2+2712546]\n\tGetHandleVerifier [0x0170886D+2652765]\n\tGetHandleVerifier [0x0150002A+520730]\n\tGetHandleVerifier [0x014FEE06+516086]\n\tOrdinal0 [0x0141468B+1787531]\n\tOrdinal0 [0x01418E88+1805960]\n\tOrdinal0 [0x01418F75+1806197]\n\tOrdinal0 [0x01421DF1+1842673]\n\tBaseThreadInitThunk [0x76D6919F+14]\n\tRtlInitializeExceptionChain [0x7788AD2F+143]\n\tRtlInitializeExceptionChain [0x7788ACFA+90]\n"
    }
}
```

### Operating System

Windows 10

### Selenium version

Selenium here not required

### What are the browser(s) and version(s) where you see this issue?

Chrome 103.0.5060.114

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 103.0.5060.114

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
The touch API is no longer supported. It has been replaced by the Actions API, where "touch" is a subtype of pointer input

https://w3c.github.io/webdriver/#pointer-input-source

**Comment by vishnuprakash9845** [comment]
> The touch API is no longer supported. It has been replaced by the Actions API, where "touch" is a subtype of pointer input
> 
> https://w3c.github.io/webdriver/#pointer-input-source

@titusfortner got it. Thanks for the reply.

![image](https://user-images.githubusercontent.com/24207575/179271001-0e63c96f-a8f4-4687-9b08-8d53023b624b.png)


Is there any example how to use this API,getting bit confused on the JSON body to pass.

**Comment by titusfortner** [comment]
Yes, the Actions API is powerful but not straightforward. Your best bet is to pick your preferred Selenium language and dig through this repo to see what JSON it crafts for each use case. Feel free to reach out to us on Slack if you have questions.

https://www.selenium.dev/support/#ChatRoom
