### ISSUE TITLE
[🚀 Feature]: Support custom headers for remote WebDriver connection (python)

### ISSUE THREAD

**Issue by scook12** [SeleniumHQ/selenium#10892]
### Feature and motivation

In `RemoteConnection`, the `get_remote_connection_headers` method has a set of logical defaults it builds, but there's no way for a user to make an addition to these headers.

Adding a hook or property that the consuming code can set to add to these headers would be a big help.

### Usage example

I need to add a host header for requests to be successful to my selenium grid running behind traefik reverse proxy. Without this feature, I can't use selenium python out of the box to create sessions (initializing `WebDriver` throws 404 errors because traefik doesn't know where to route without the host header).

Passing a parameter from `WebDriver` to `RemoteConnection` ought to do the trick:
```py
driver = WebDriver(command_executor, additional_headers={"Host": "some-value"})
```

**Comment by symonk** [comment]
I _think_ as a workaround you an pass your own RemoteConnection object as a command executor at the moment tho thats a bit heavy handed for the use case maybe, will take a look when i'm home

**Comment by jamesmortensen** [comment]
Just to clarify, @scook12 are you wanting to set a custom header to allow your test code to access a Selenium Grid on a secured remote server?  

For instance, WebdriverIO lets me do something like this in my configuration file:

```
    port: 443,
    protocol: 'https',
    hostname: 'myremoteseleniumserver.example.com',
    headers: {
        'authorization': 'Bearer some_token_which_the_server_uses_to_keep_out_bad_actors'
    },
    strictSSL: true,
    path: '/wd/hub'
```

Is something like this what you're looking for, or are you looking to control the headers that the browser sends to the app under test?

**Comment by scook12** [comment]
@jamesmortensen yes, I need to control headers sent to the grid!

My grid is deployed behind Traefik and using the `Host` directive requires this header, so my test code needs to pass it to for reverse proxy to route appropriately.

For more context, the intent was to use subdomains to organize my hubs. We test on web and mobile (via appium) deployed on docker swarm. I wanted `mobile.domain.com` and `web.domain.com` to route to the appropriate hub service, depending on which platform our test code is being run against.

To do that, I just need to include the Host header in requests sent via `WebDriver` to the grid. I tested this in a debug session, and it worked, but monkeypatching these headers is really convoluted and creating our own `RemoteConnection` object is, as symonk mentioned, a pretty heavy solution for a one-line change to the current behavior.

Hopefully that helps clarify!

**Comment by jamesmortensen** [comment]
UPDATE:  Unpublished and renamed to "selenium-proxy" as it's incorrect to say it's a "reverse proxy". Sorry for any inconvenience.

----

@scook12 I have had some success with this [Selenium Proxy Server](https://www.npmjs.com/package/selenium-proxy) which I just published.  I wanted to be able to set the authorization header, but not every test automation library makes that easy to do.  With the proxy server, we can modify the headers for any framework we want to use just by pointing the testing library to the proxy server.

So what you can do is configure your testing library to go through this proxy, and then configure the proxy to communicate securely to your Selenium grid.  The proxy handles rewriting the headers with the token so the testing library doesn't need to.  It's written in Node.js, but that shouldn't be a problem since Selenium WebDriver is a standard.  If you try it out, let me know if you run into any trouble.

**Comment by titusfortner** [comment]
@symonk we could add an `additional_headers` argument to constructor or as a class property in `RemoteConnection` to update the [default headers](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/remote_connection.py#L108-L112) 

In the meantime the user *could subclass the browser specific subclass, but that is clumsy indeed.

**Comment by ttlns** [comment]
#### Actually, I found a quite sneaky way without using a ___Proxy___ or ___Extension___:
You can change the Headers in `continue_request()` at `my_headers = {"sec-ch-ua-platform": "Android"}` .

```python
# resource: https://stackoverflow.com/questions/66227508/selenium-4-0-0-beta-1-how-add-event-listeners-in-cdp

class cdp_listener:
    from typing import Dict

    def __init__(self):
        self.listeners = {}
    async def async_helper(self):
        async with driver.bidi_connection() as connection:
            session, devtools = connection.session, connection.devtools

            for listener in self.listeners.items():
                my_listener = await listener[1]["listener"](connection=connection)

                async for event in my_listener:
                    try:
                        await session.execute(listener[1]["at_event"](event=event, connection=connection))
                    except Exception as e:
                        print(e)

    def trio_helper(self):
        import trio
        trio.run(self.async_helper)

    def start_threaded(self, listeners: Dict[str,Dict[callable, callable]] = {}):
        if listeners:
            self.listeners = listeners

        import threading
        thread = threading.Thread(target=self.trio_helper)
        thread.start()
        return thread

    def add_listeners(self, listeners: Dict[str,Dict[callable, callable]]):
        self.listeners = listeners

    def remove_listener(self, listener:str):
        del self.listeners[listener]

async def all_requests(connection):
    session, devtools = connection.session, connection.devtools
    pattern = map(devtools.fetch.RequestPattern.from_json,[{"urlPattern":"*"}])
    pattern = list(pattern)
    await session.execute(devtools.fetch.enable(patterns=pattern))

    return session.listen(devtools.fetch.RequestPaused)

def continue_request(event, connection):
    print({"type":event.resource_type.to_json(),"frame_id": event.frame_id, "url": event.request.url})
    session, devtools = connection.session, connection.devtools

    headers = event.request.headers.to_json()

    my_headers = {"sec-ch-ua-platform": "Android"}
    headers.update(my_headers)
    my_headers = []
    for item in headers.items():
        my_headers.append(devtools.fetch.HeaderEntry.from_json({"name": item[0], "value": item[1]}))

    return devtools.fetch.continue_request(request_id=event.request_id, headers=my_headers)


cdp_listener = cdp_listener()
thread = cdp_listener.start_threaded(listeners= {"continue":{"listener":all_requests,"at_event":continue_request}})

driver.get('https://modheader.com/headers?product=ModHeader')
```

**Comment by ttlns** [comment]
pretty sure this would have to be added to the webdriver spec or (if it isn't already) to Webdriver BiDi

**Comment by titusfortner** [comment]
There's 2 pieces.
* The Remote Connection class uses an http client to send requests and receive responses between the code and the driver/server.
* All assets in the browser are loaded via responses to requests.

BiDi/network interception manages the second one. This issue relates to the first one.

**Comment by titusfortner** [comment]
Hmm, this might be a part of this larger issue — https://github.com/SeleniumHQ/selenium/issues/12368

**Comment by amardeep2006** [comment]
I have a similar requirement. I want to use an apigateway to protect the selenium grid via an APIKEY that should be present in http headers. Is this possible in Selenium Java to pass custom http header while using RemoteWebdriver class. I looked at #12368 but could not see a discussion about custom headers.
Thanks

**Comment by navin772** [comment]
I think what is being requested here is resolved by this PR - https://github.com/SeleniumHQ/selenium/pull/14587

Although, it was for [Better compatibility with appium python](https://github.com/SeleniumHQ/selenium/issues/13959), it introduced a new class variable `extra_headers` that can be used for this specific use case.

**Comment by harsha509** [comment]
Changes landed with PR https://github.com/SeleniumHQ/selenium/pull/14587

Closing as resolved!

**Comment by VietND96** [comment]
In part of #13286 - via ClientConfig, the header `authorization` can be configured
- Basic auth: `ClientConfig(username="admin", password="admin")`
- Bearer token (or similar): `ClientConfig(auth_type="Bearer", token=f"{access_token}")`

See more: https://www.selenium.dev/documentation/webdriver/drivers/http_client/
