### ISSUE TITLE
[🐛 Bug]: Clicking on button do nothing in chrome browser, the same button opens up a child window when I click it manually

### ISSUE THREAD

**Issue by KiranTest** [SeleniumHQ/selenium#10896]
### What happened?

I have problem with clicking on a button using selenium in **Chrome** browser only. 
**Scenario:** In our web application there is a scenario where logged in user can choose the products, add it to cart, select payment methods and Click on **Proceed to Payment**. On clicking **Proceed to Payment** to secure payment, it should open a new child window with option to login to the payment method and process payments. 

In the above scenario, I have issue with Click():  After selecting Google pay radio, when I click on _Proceed to Payment_ Nothing happens, no errors thrown. I can't see the child window to Sign in to _**Google pay**_. (Tried all the possible ways - Selenium Click() & JS click, Keyboard inputs & Actions). Surprisingly in the same automation session if I click that button manually it is opening sign in to Google  child window. I have checked if there frames nothing is there. Don't understand why the button press doesn't open child window using automation methods. click doesn't work, though the button returns true for isDisplayed(), is Enabled & clickable . 

This issue happens only in chrome browser. Other browsers open the Google sign in child window when I click on Proceed To Payment. `

### How can we reproduce the issue?

```shell
I cant share my application flow. It happens specific to ecommerce payment method Google and Chrome browser. I have tried below methods to click on the element. 

String payMethod = "GooglePay ";
if(clickPayMethodV2(payMethod)) {
	clickElement(agreeCheckBox, "Agree Terms Check box");
	Assert.assertTrue(isElemenEnbaledClickable(ProceedToSecurePay, 4), "ProceedToSecurePay button is disabled for PayPal");
	boolean status =	isElemenEnbaledClickable(ProceedToSecurePay, 5);
		JavascriptExecutor js = (JavascriptExecutor) driver;	
		//js.executeScript("arguments[0].scrollIntoView();", element);	
		//Thread.sleep(1000);	
//				js.executeScript("arguments[0].click();", element);
		driver.findElement(By.cssSelector("srgc2-secure-payment > form")).click();
		ProceedToSecurePay = driver.findElement(By.xpath("//button[contains(.,'Proceed to secure payment')]"));
		js.executeScript("arguments[0].focus;", ProceedToSecurePay);
		js.executeScript("arguments[0].click();", ProceedToSecurePay);
		clickElement(ProceedToSecurePay, "ProceedToSecurePay");
		
		js.executeScript("var ele = arguments[0];ele.addEventListener('click', function() {ele.setAttribute('automationTrack','true');});",ProceedToSecurePay);
		ProceedToSecurePay.click();
		System.out.println(ProceedToSecurePay.getAttribute("automationTrack"));	
		//System.out.println(ProceedToSecurePay.getShadowRoot().toString());
		click(ProceedToSecurePay, "Proceed To SecurePay button");
	
	
	clickElementJS(ProceedToSecurePay, "ProceedToSecurePay");
	}
else {
	logInfoExtent("Failed to click on Payment method: "+payMethod +"in checkout Step 3. PAYMENT");
	throw new TestException("Failed to select Payment method: "+payMethod +"in checkout Step 3. PAYMENT");
}


Actions action=new Actions(driver);
action.moveToElement(ProceedToSecurePay).perform();
action.moveToElement(ProceedToSecurePay).click().perform();

ProceedToSecurePay.submit();
ProceedToSecurePay.sendKeys(Keys.ENTER);
```

### Relevant log output

```shell
There were no errors thrown after Click() method. 

But there is an error in console. 
"Cannot show PaymentRequest UI in a preview page or a background tab."
PaymentRequest.show() requires either transient user activation or delegated payment request capability
```

### Operating System

Windows 10

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 104 or any other 102 103

### What are the browser driver(s) and version(s) where you see this issue?

 104.0.5112.29 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
If it's a Chrome issue, then there's nothing Selenium can do to fix this. There's also a good chance that Chrome explicitly prevents this from being done while in an automated session.
