### ISSUE TITLE
Returning Blank Page in Chrome

### ISSUE THREAD

**Issue by Diplomat2015** [SeleniumHQ/selenium#1089]
HI,

I am having an issue with opening our site in chrome.We are using latest Chrome Brwoser,Chromedriver and standalone server.But when I am trying to open the said URL in remote server using Chrome it is returning blank page.But correct page is displayed If I am trying to open a site like "google.com".

This is the error I am getting..

An exception of type 'OpenQA.Selenium.NoSuchElementException' occurred in WebDriver.dll but was not handled in user code

Additional information: no such element

  (Session info: chrome=45.0.2454.101)

  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 34 milliseconds

For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'

System info: host: 'MIHQSELNAPADM01', ip: '192.168.12.64', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_55'

*** Element info: {Using=xpath, value=//*[@id='FirstName']}

Session ID: dee63ee72d4ac4b25299f06ce62f391a

Driver info: org.openqa.selenium.chrome.ChromeDriver

Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\SELENI~1\AppData\Local\Temp\scoped_dir6940_8890}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=45.0.2454.101, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]

Please advice if there is anything I can do to fix this,

**Comment by sri85** [comment]
Does it happen only with Chrome ?

**Comment by rubig** [comment]
Could you please give the url of the page you want to open? If the browser opens google.com OK but your site is broken, there must be something special about the url you want to open.

**Comment by Photonios** [comment]
This issue should be closed, there's no reproduction case and no-one has looked at this in a long time.

**Comment by nzaitseva** [comment]
I have the same issue. When I try to open coles.com.au it works, but if I try to visit subdomain shops.coles.com.au  it shows the blank page. I've tried latest versions of Firefox and Chrome.
