### ISSUE TITLE
[🐛 Bug]: Selenium grid 4 getting TargetInvocationException caused by selenium.grid.config.configException

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#10909]
### What happened?

We are recently migrating from selenium grid 3 to grid 4. 
In the grid configuration command line file, trying to pass driver configurations using --driver-configurations 

("java exe "  -jar "selenium jar "  node --override-max-session true --hub "hub address"  --port "port" --session-timeouts 300 --host "node name" --driver-configuration display-name="Edge" max-sessions=2 webdriver-path="path of driver" stereotype='{"browserName": "edge", "browserVersion": "102", "maxInstances" : "5"}'  --driver-configuration display-name="chrome" max-sessions=2 webdriver-path="path of driver" stereotype='{"browserName": "chrome", "browserVersion": "102", "maxInstances" : "3"}' 

when execute from command line, getting **InvocationTargetException** caused by 
org.openqa.selenium.grid.config.ConfigException : **One or more driver configs does not have the required 'key=value' structure.**

Is the way I gave the driver-configuration is correct ? I have same for firefox and ie as well. If I remove the driver-configuration, node is getting added to grid.

Appreciate the help.
<img width="851" alt="grid4 error" src="https://user-images.githubusercontent.com/16626518/181341714-dfc3e98c-3379-4fa0-9419-ada7238ce41e.PNG">

### How can we reproduce the issue?

```shell
("java exe " -jar "selenium jar " node --override-max-session true --hub "hub address" --port "port" --session-timeouts 300 --host "node name" --driver-configuration display-name="Edge" max-sessions=2 webdriver-path="path of driver" stereotype='{"browserName": "edge", "browserVersion": "102", "maxInstances" : "5"}' --driver-configuration display-name="chrome" max-sessions=2 webdriver-path="path of driver" stereotype='{"browserName": "chrome", "browserVersion": "102", "maxInstances" : "3"}'
```

### Relevant log output

```shell
attached the screenshot
```

### Operating System

Win 10

### Selenium version

Selenium 4

### What are the browser(s) and version(s) where you see this issue?

chrome 102, edge 102

### What are the browser driver(s) and version(s) where you see this issue?

chromedrive 102 , edge drive 102

### Are you using Selenium Grid?

4.1.3

**Comment by pujagani** [comment]
Thank you for sharing the details. Please double-check the names and values by referring to https://www.selenium.dev/documentation/grid/configuration/cli_options/. 
By a quick glance, I have a few suggestions.
Please ensure the port is not a string but an int, change "override-max-session" to "override-max-sessions", change "session-timeouts" to "session-timeout", and please ensure correct capability names are added as well for the browser name.
For driver-configuration I used and it worked as expected, 
```
--driver-configuration display-name="Edge" max-sessions=2 webdriver-path="/Users/Puja/Downloads/webdrivers/"
stereotype={\"browserName\":\"msedge\",\"browserVersion\":\"102\",\"maxInstances\":\"5\"}
```
The quotes in the driver configuration need escaping because I am running it via IntelliJ otherwise it should work as it is.

**Comment by remyanekkuth** [comment]
thank you @pujagani . when I escaped the configuration, it worked.
