### ISSUE TITLE
[🐛 Bug]: Selenium >= 4 requires utf-8 encoding to be delcared on `Content-Type` header

### ISSUE THREAD

**Issue by lamalex** [SeleniumHQ/selenium#10913]
### What happened?

Starting a session with Selenium >= 4 requires the HTTP request's `Content-Type` header to declare the character encoding as utf-8.

`Content-Type: application/json`
results in
```"Content-Type header does not indicate utf-8 encoded json: application/json"```

Per the [RFC](https://www.ietf.org/rfc/rfc4627.txt), section 3 UTF-8 is the default encoding for the `application/json` mime-type and requiring its declaration is redundant.

### How can we reproduce the issue?

```shell
Send any HTTP request without `;charset=utf-8` in the `Content-Type` header with Selenium version > 4
```

### Relevant log output

```shell
Error: CmdError(Standard(WebDriver { error: UnknownError, message: "Content-Type header does not indicate utf-8 encoded json: application/json", stacktrace: "" }))
```

### Operating System

Any

### Selenium version

>= 4

### What are the browser(s) and version(s) where you see this issue?

Any

### What are the browser driver(s) and version(s) where you see this issue?

Any

**Comment by diemol** [comment]
How did you get that error? What were you using on the client side and server side?

**Comment by lamalex** [comment]
The server side is browserstack, the client side is the Rust client library [ThirtyFour](https://github.com/stevepryde/thirtyfour).

My colleague has an alternate implementation written using [selenium-webdriver](https://github.com/SeleniumHQ/selenium/tree/trunk/javascript/node/selenium-webdriver#readme).

When we inspect the requests between the two libraries they are identical with the exception being `selenium-webdriver` includes `charset=utf-8` in the `Content-Type` header, and `thirtyfour` does not.

When we hack our `thirtyfour` dependency to manually include `charset=utf-8` on the HTTP request from the Rust implementation the request receives a 200 response and our tests execute as expected.

By downgrading the requested selenium version in our browserstack request to 3.141.0 the code works without `charset=utf-8` on the request.

Requiring `charset=utf-8` on the `Content-Type` header feels approximately contrary to [RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1) which explicitly **requires** JSON between systems outside of a closed ecosystem to be UTF-8 encoded.

**Comment by diemol** [comment]
Thank you for sharing more details. I understand the JSON RFC sets UTF-8 as default encoding and the additional content you reference from the HTTP RFC. However, it does not say that the default is UTF-8.

But aside of the RFCs, the core reason to add that check was a security vulnerability report we got while implementing Selenium 4. The reported agreed to not disclose the details because lots of people still use Grid 3.x, which has the vulnerability. 

So, it'd be great if [ThirtyFour](https://github.com/stevepryde/thirtyfour) includes charset=utf-8 in the Content-Type header. Are you in touch with that project?

**Comment by lamalex** [comment]
I can try submitting an upstream patch, however I still think that this is a bug on Selenium that mis-places the burden on clients. I believe the spec **does** specify the default encoding as utf-8.

From [RFC4627](https://datatracker.ietf.org/doc/html/rfc4627#section-3)
> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8.

and

From [RFC8259](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1)
> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8.

**Comment by diemol** [comment]
Not sure if it is a bug, but it is there to prevent the vulnerability.

Actually, this shows that the Selenium project is not doing a great job in the collaboration with other WebDriver projects. This change should have been shared across other implementations and not just us waiting for them to catch up. We are now working on that by starting to meet with those projects and avoid these type of issues in the future.

**Comment by diemol** [comment]
Closing as the issue was raised in the fantoccini project.
