### ISSUE TITLE
[🐛 Bug]: Modifier keys for MacOS 'control' (⌃, "\u2303") and 'option' (⌥, "\u2325") unavailable

### ISSUE THREAD

**Issue by cpeck-rmvd** [SeleniumHQ/selenium#10912]
### What happened?

(observed with python bindings, but examination of `Keys` in Java seemed to proved the same)

Using the Keys class, one cannot press the Mac modifier keys "control" (different from "command") or "option". The inability to use these keys represents a gap between what's possible with Selenium vs end user; the keys can prove useful when writing tests.

### How can we reproduce the issue?

```shell
See for example https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/keys.py, which does not contain said keys.
```

### Relevant log output

```shell
Not needed to reproduce
```

### Operating System

macOS

### Selenium version

Python 4.3.0

### What are the browser(s) and version(s) where you see this issue?

I have only tried Chrome but... it is clearly browser-agnostic

### What are the browser driver(s) and version(s) where you see this issue?

clearly driver-agnostic

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
Thank you for the details. As long as the Unicode values listed are PUA Unicode values, it can be added to the code in different language bindings. I was unable to find the PUA value and confirm after a quick search. Can you please point to the right resource just to confirm this and also double-check if we are missing some other values that we can add? Would really appreciate it. Thank you!

**Comment by titusfortner** [comment]
The `CONTROL` and `ALT` constants in that file should properly map to the Mac keys you want to use.

The values of the constants in that file do not correspond to the unicode values of the keys, but to unassigned code points that are interpreted by the driver based on this table in the specification: https://w3c.github.io/webdriver/#keyboard-actions
