### ISSUE TITLE
[🐛 Bug]: Memory leak when clicking an element (NodeJS)

### ISSUE THREAD

**Issue by theunreal** [SeleniumHQ/selenium#10915]
### What happened?

I added a simple piece of code to my NodeJS app, and for some reason, the line that clicks on an element triggers some kind of memory leak in my application.
The image below describes the amount of free/used memory in my application, before and after commenting item.click(); (full snippet below)
Enabling the item.click() method to download an item by clicking drains up to 2 GB of memory!!

![image](https://user-images.githubusercontent.com/6171883/181904955-e48c49cd-b87b-4d70-ac31-48f6c9a6d485.png)

```
const scanItems = async () => {
    onDownloadStart();
    const items = await global.driver.findElements(By.css('.webgrid tbody tr a'));
    console.log(`Found ${items.length} items`);
    for (const item of items) {
        try {
            await item.click(); // The graph above shows the memory usage when comment / not commenting this line
            await sleep(300);
            increaseDownloadedCount();
        } catch (e) {
            console.log('Bad item found, skip', e);
        }
    }
}
```

### How can we reproduce the issue?

Navigate with selenium to `http://prices.shufersal.co.il/`, then try clicking the links in the table:
```shell

  const scanItems = async () => {
    onDownloadStart();
    const items = await global.driver.findElements(By.css('.webgrid tbody tr a'));
    console.log(`Found ${items.length} items`);
    for (const item of items) {
        try {
            // await item.click();
            await sleep(300);
            increaseDownloadedCount();
        } catch (e) {
            console.log('Bad item found, skip', e);
        }
    }
}

'--no-sandbox', '--disable-dev-shm-usage', 'log-path=chromedriver.log',
        '--window-size=1920,1080',
        '--ignore-certificate-errors',
        'safebrowsing-disable-extension-blacklist',
        'safebrowsing-disable-download-protection',
        '--disable-logging',
        '--disable-gpu',
        '--disable-extensions',
        '--log-level=2',
        '--no-sandbox',
        '--headless'];


Uncommenting `await item.click();` triggers a memory leak. `item.click()` performs a file download on a specific web page.
```

### Relevant log output (log level was set to 3)
```Starting Selenium Grid Standalone...
09:59:53.915 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
09:59:53.921 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
09:59:54.772 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
09:59:54.844 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "103.0","se:noVncPort": 7900,"browserName": "chrome","platformName": "LINUX","se:vncEnabled": true} 1 times
09:59:54.867 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id
09:59:54.894 INFO [GridModel.setAvailability] - Switching Node 6d373c28-d167-4df3-bcb9-fb276f332a64 (uri: http://172.18.0.5:4444) from DOWN to UP
09:59:54.895 INFO [LocalDistributor.add] - Added node 6d373c28-d167-4df3-bcb9-fb276f332a64 at http://172.18.0.5:4444. Health check every 120s
09:59:55.076 INFO [Standalone.execute] - Started Selenium Standalone 4.3.0 (revision a4995e2c09*): http://172.18.0.5:4444
10:00:36.689 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-sandbox, --disable-dev-shm-usage, log-path=chromedriver.log, --window-size=1920,1080, --ignore-certificate-errors, safebrowsing-disable-extens..., safebrowsing-disable-downlo..., --disable-logging, --disable-gpu, --disable-extensions, --log-level=3, --no-sandbox, --headless], prefs: {download.default_directory: /home/seluser/Downloads, download.prompt_for_download: false, profile.default_content_settings.popups: 0, safebrowsing.enabled: true}}}]
Starting ChromeDriver 103.0.5060.53 (a1711811edd74ff1cf2150f36ffa3b0dae40b17f-refs/branch-heads/5060@{#853}) on port 44468
Only local connections are allowed.
Please[ s1e6e5 9h1t7t5p236s.:7/2/8c]h[rSoEmVeEdRrEi]v:e rb.icnhdr(o)m ifuami.loerdg:/ sCeacnunroitty -acsosnisgind erreaqtuieosnted address (99)
s for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
10:00:37.233 INFO [ProtocolHandshake.createSession] - Detected upstream dialect: W3C
10:00:37.253 INFO [LocalNode.newSession] - Session created by the Node. Id: 86004dcb57ef8139e22a086407c15191, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: /tmp/.com.google.Chrome.YSa5c9}, goog:chromeOptions: {debuggerAddress: localhost:38692}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: http://localhost:38692, se:cdpVersion: 103.0.5060.53, se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
10:00:37.261 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 86004dcb57ef8139e22a086407c15191
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: /tmp/.com.google.Chrome.YSa5c9}, goog:chromeOptions: {debuggerAddress: localhost:38692}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: Proxy(), se:cdp: ws://172.18.0.5:4444/sessio..., se:cdpVersion: 103.0.5060.53, se:vnc: ws://172.18.0.5:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.5:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
```

### Operating System

CentOS 7

### Selenium version

 "selenium-webdriver": "4.3.1", selenium/standalone-chrome:4.3.0-20220624

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

chrome diver 103

### Are you using Selenium Grid?

selenium/standalone-chrome:4.3.0-20220624 (not sure if that what you mean)

**Comment by theunreal** [comment]
Which information is missing? The issue template is filled..

**Comment by diemol** [comment]
But we cannot copy & paste this code because there is no HTML/URL to be used to reproduce the issue.

**Comment by theunreal** [comment]
> But we cannot copy & paste this code because there is no HTML/URL to be used to reproduce the issue.

URL is http://prices.shufersal.co.il/

**Comment by diemol** [comment]
Missed that from the initial comment, apologies.

How are you measuring this? What happens when you click manually?

**Comment by theunreal** [comment]
> Missed that from the initial comment, apologies.
> 
> How are you measuring this? What happens when you click manually?

I'm measuring the memory in my machine, my memory started to shrink when running the code above, I ran it again and again until I found that it was caused by `item.click`, and only in the website I provided above, not sure why.
Not sure how I can check `manual` click,  since I have no memory limit locally, and I'm able to reproduce it on my VPS only - not sure how to manual click the link there

**Comment by diemol** [comment]
WebDriver just sends the event to click, it does not change the application at all, it does not inject any JS for that particular event. I do not see how it could be caused by Selenium WebDriver. What I am suggesting is to click manually several times monitor the application.

**Comment by theunreal** [comment]
> WebDriver just sends the event to click, it does not change the application at all, it does not inject any JS for that particular event. I do not see how it could be caused by Selenium WebDriver. What I am suggesting is to click manually several times monitor the application.

Well, I did more debug on this and found it that chrome memory was increased, not sure why. Removing --headles did the trick- and memory is OK this way. Not sure why headless mode is leaking memory in this case. Anyway, it looks like a chrome issue..

**Comment by diemol** [comment]
OK, thanks for reporting back. If you want to check with the Chrome/ChromeDriver team about this, I will leave some links below.

**Comment by diemol** [comment]
To be honest, this could be an issue with your application. You should check other browsers and if the behavior is the same, then it is most likely a bug in your app.
