### ISSUE TITLE
[🐛 Bug]: Unable to Load a .xpi extension on firefox without a FirefoxProfile created

### ISSUE THREAD

**Issue by gbrabelo** [SeleniumHQ/selenium#10910]
### What happened?

Hello!

  I'm currently migrating from sel3 to sel4 and updating everything that was deprecated. Everything went smoothly, until I migrated everything from FirefoxProfile to FirefoxOptions: Every option still works fine from what I could see, but when I try loading an .xpi extension, I get the following error:

```
selenium.common.exceptions.WebDriverException: Message: Could not install add-on: C:\Users\gbrabelo\AppData\Local\Temp\addon-01f66145-c781-4da4-ab28-cd20949a695d.xpi: Add-on webpki@lacunasoftware.com is not compatible with application version. add-on minVersion: 50.0a1.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:513:5
install@chrome://remote/content/marionette/addon.js:86:13
```

Looks to me that the remote driver thinks it is a Chrome? Looks to me that it is unable to compare to Firefox version (>50), even though I'm using the latest Firefox.

Extension used download from: https://docs.lacunasoftware.com/pt-br/articles/web-pki/installation-webpki-gpo.html
direct link> https://cdn.lacunasoftware.com/webpki/webpki-ext.zip

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.service import Service

a_service = Service(executable_path='gecko_path')
driver = webdriver.Firefox(service=a_service)
# it works if you add a profile though>
# driver = webdriver.Firefox(service=a_service, firefox_profile=webdriver.FirefoxProfile())
driver.install_addon('webpki-firefox-ext.xpi', temporary=True)
```

### Relevant log output

```shell
selenium.common.exceptions.WebDriverException: Message: Could not install add-on: C:\Users\gbrabelo\AppData\Local\Temp\addon-83b613a7-aed6-4e3c-bf4b-15ebf282470c.xpi: Add-on webpki@lacunasoftware.com is not compatible with application version. add-on minVersion: 50.0a1.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:186:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:513:5
install@chrome://remote/content/marionette/addon.js:86:13
```

### Operating System

Win10 and latest Mac

### Selenium version

Python 3.10 with Sel4.3.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 102

### What are the browser driver(s) and version(s) where you see this issue?

gecko v0.31

### Are you using Selenium Grid?

No

**Comment by gbrabelo** [comment]
is there anything I can do to help?

**Comment by TamsilAmani** [comment]
I am working on this issue.

**Comment by TamsilAmani** [comment]
I have tried to install the following 3 .xpi files with the code provided above. In my opinion the issuer's .xpi file has a requirement for FirefoxProfile to be present. @gbrabelo have you tried installing any other addon?

- Repo XPI = https://github.com/SeleniumHQ/selenium/blob/trunk/common/extensions/webextensions-selenium-example.xpi
- My XPI (a third-party XPI which I used for testing) = https://addons.mozilla.org/en-US/firefox/addon/ghostery/?src=homepage-collection-featured
- Issuer XPI = https://cdn.lacunasoftware.com/webpki/webpki-ext.zip (provided above)

  | Nothing Set | FirefoxProfile Set | FirefoxOptions Set
-- | -- | -- | --
Repo XPI | Installs | Installs (with warning) | Installs
My XPI | Installs | Installs (with warning) | Installs
Issuer XPI | Does not Install | Installs (with warning) | Does not Install

**Comment by TamsilAmani** [comment]
Also, manually installing the Issuer's XPI on firefox _(without being under the control of selenium)_ gives error. 
`"Web PKI could not be installed because it has a high risk of causing stability or security problems"`

So I can conclude that the problem is with the XPI file being used @gbrabelo 
<img width="683" alt="Screenshot 2022-09-06 at 3 37 31 PM" src="https://user-images.githubusercontent.com/14896831/188609677-bc4f3df2-a8bd-46f8-a687-05192299ad44.png">

**Comment by brunocapu** [comment]
For WebPKI latest web-extension version on Firefox, please install through the official setup-site: https://get.webpkiplugin.com/

If access to the latest XPI file is needed, please download it from the all-versions list on the API:
[GET]
https://get.webpkiplugin.com/firefox-extensions

![image](https://user-images.githubusercontent.com/3412136/210368822-498cb124-f82f-4647-bf6d-867e6fe5f876.png)

**Comment by titusfortner** [comment]
Regardless of how this gets installed. The code in the Selenium repo is sending the correct things to the driver. If the driver or the browser do not like the add-on, then it needs to be addressed with Mozilla.
