### ISSUE TITLE
Selenium standalone server creates zombie processes

### ISSUE THREAD

**Issue by frank-calma** [SeleniumHQ/selenium#1091]
We run a fairly aggressive distributed selenium grid, executing ~200 tests per node machine per hour. Each test is run using a new chrome driver instance. We have found that the memory on our nodes gradually fills up. After some investigation, we found that our selenium standalone server was holding on to thousands of handles to dead chromedriver instances. Each one was taking up 20kb of ram, and no longer attached to any live process / PID. After resetting the server, these zombie processes were immediately released from memory. At present we have not attempted to replicate the issue using firefox/IE or through local execution. 

![zombie processes](https://cloud.githubusercontent.com/assets/6556555/10207594/3cc3adf4-6782-11e5-9a25-84a7dedb2440.png)

**Comment by AJ-72** [comment]
chromedriver.exe usually gets killed when you do a browser.quit(). Is your browser closing correctly after the test?

**Comment by barancev** [comment]
Just don't forget to call driver.quit()

**Comment by frank-calma** [comment]
Yes, we are calling driver.quit(). The chromedriver instance is being closed from the task manager / process / PID level, but remains as a memory fragment.

**Comment by elirenato** [comment]
Same problem for with Chrome Standalone, I`m also using driver.quit() properly, I also tried another suggestions that I saw on the web (DBUS_SESSION_BUS_ADDRESS=/dev/null) but this error is still almost 3 years after the last message.

**Comment by cgoldberg** [comment]
@tarellel Please submit a new issue and include all information specified in the new issue template.... this issue is already closed.  Also, "me too" comments with no relevant details are entirely unhelpful.
