### ISSUE TITLE
[🐛 Bug]: Switching parent frames on a web page with more than 100 iframes takes 7.5 seconds

### ISSUE THREAD

**Issue by dzl94** [SeleniumHQ/selenium#10914]
### What happened?

I used selenium to crawl data from a web page. The source code of this web page used more than 100 iframes. It is normal to switch subframes, but when switch back to the parent frame, sometimes it is normal while sometimes it takes too long, even 7.5 seconds. Is it because there are too many iframes on this page? Is there any solution.

### How can we reproduce the issue?

```shell
driver.switch_to.parent_iframe(Element)
driver.switch_to.default_contents
```

### Relevant log output

```shell
switch to parent iframe costs 7.5s
```

### Operating System

windows7

### Selenium version

python

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver

**Comment by pujagani** [comment]
Thank you for providing the details. However, if you think it is a potential performance problem that needs fixing, we might need more details regarding reproducing it. Feel free to discuss further in any of our [community channels (Slack/IRC/Matrix) ](https://www.selenium.dev/support/). Please join any of the channels and the Selenium team will help you understand this better. Thank you!

**Comment by titusfortner** [comment]
Selenium is only responsible for sending and receiving the commands from the driver. If there is a performance issue in how long it is taking the driver to respond, then it needs to be raised with Google on their tracker.
