### ISSUE TITLE
[🐛 Bug]: Unable to use same port across multiple nodes in selenium grid 4

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#10926]
### What happened?

The way grid 3 set up was environment integ and pre-production will listen to port 5555 . Integ will listen to development server hub and pre-production in prepoduction server hub. 
sandbox and user acceptance will listen to 4444

In grid 4 same configuration we did for port 5955 4944 respectively. 
Integ is working fine. But when try to run the command with --port 5950 getting error " address in use" 
how can we use same port across multiple nodes. 

command we run is 

JAVA -jar "jar " node --hub http:selenium:5955/grid/register --port 5900 --host "computer name "

### How can we reproduce the issue?

```shell
Two nodes with same port in different environment with different server.
Add first node and validate 
JAVA -jar "jar " node --hub http:selenium:5955/grid/register --port 5900 --host "computer name "
go to the second server, configure same port for diff envt. and run again
will get exception at point --port
```

### Relevant log output

```shell
value is not acceptable for --port .
```

### Operating System

windows 10

### Selenium version

4.1.3

### What are the browser(s) and version(s) where you see this issue?

chrome 102, edge -103

### What are the browser driver(s) and version(s) where you see this issue?

chromeDriver 102, edye -103

### Are you using Selenium Grid?

4.1.3

**Comment by diemol** [comment]
A few things, `http:selenium:5955/grid/register` is not a valid URL to register, and we also need the full commands and logs for each command. We cannot triage this until more information  is provided.

**Comment by remyanekkuth** [comment]
@diemol I set up this port and hub was working fine. 
I was able to resolve the issue by mentioning—publish-events and —subscriber-events .
