### ISSUE TITLE
[🐛 Bug]: Getting "An error occurred while retrieving a new session: "unknown error: Chrome failed to start: crashed."

### ISSUE THREAD

**Issue by MadhuPal1** [SeleniumHQ/selenium#10920]
### What happened?

I am using Nightwatch framework to execute my automation scripts
Earlier I was using Google chrome version 103 and selenium chromedriver was too of version 103.
After autoupdate of Google chrome version 104, I am getting below error while trying to execute my automation scripts through nightwatch(Chromedriver is also updated to version 104)

Unable to create new session.

UnknownError: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'IN-B2SSZ53', ip: '192.168.138.230', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
	Ordinal0 [0x011B8823+2197539]
	Ordinal0 [0x01150911+1771793]
	Ordinal0 [0x01063FE8+802792]
	Ordinal0 [0x01082831+927793]
	Ordinal0 [0x0107EA51+911953]
	Ordinal0 [0x010B2260+1122912]
	Ordinal0 [0x010B1EBA+1121978]
	Ordinal0 [0x010AD476+1102966]
	Ordinal0 [0x01087660+947808]
	Ordinal0 [0x01088556+951638]
	GetHandleVerifier [0x01461A32+2740578]
	GetHandleVerifier [0x01453776+2682534]
	GetHandleVerifier [0x0124307A+518058]
	GetHandleVerifier [0x01242196+514246]
	Ordinal0 [0x01157ADB+1800923]
	Ordinal0 [0x0115C2E8+1819368]
	Ordinal0 [0x0115C3D5+1819605]
	Ordinal0 [0x01165810+1857552]
	BaseThreadInitThunk [0x767BFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77EB7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77EB7A6E+238]

I tried to downgrade the versions, still getting above issue.
Can anybody help me in this.

### How can we reproduce the issue?

```shell
NA
```

### Relevant log output

```shell
Unable to create new session.

UnknownError: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'IN-B2SSZ53', ip: '192.168.138.230', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
	Ordinal0 [0x011B8823+2197539]
	Ordinal0 [0x01150911+1771793]
	Ordinal0 [0x01063FE8+802792]
	Ordinal0 [0x01082831+927793]
	Ordinal0 [0x0107EA51+911953]
	Ordinal0 [0x010B2260+1122912]
	Ordinal0 [0x010B1EBA+1121978]
	Ordinal0 [0x010AD476+1102966]
	Ordinal0 [0x01087660+947808]
	Ordinal0 [0x01088556+951638]
	GetHandleVerifier [0x01461A32+2740578]
	GetHandleVerifier [0x01453776+2682534]
	GetHandleVerifier [0x0124307A+518058]
	GetHandleVerifier [0x01242196+514246]
	Ordinal0 [0x01157ADB+1800923]
	Ordinal0 [0x0115C2E8+1819368]
	Ordinal0 [0x0115C3D5+1819605]
	Ordinal0 [0x01165810+1857552]
	BaseThreadInitThunk [0x767BFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77EB7A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77EB7A6E+238]
```

### Operating System

Windows 10

### Selenium version

"^4.0.0-alpha.1"

### What are the browser(s) and version(s) where you see this issue?

Google chrome 104

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.29

### Are you using Selenium Grid?

"selenium-server-standalone-jar": "^3.141.5"

**Comment by diemol** [comment]
Please upgrade your dependencies to the latest releases, Selenium is already on version 4, for example. Not sure what the latest in Nightwatch is. 

If after upgrading, this is reproducible in a consistent way, I would recommend to report this to the ChromeDriver team. I will leave some links below so you can do that.
