### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by HansZempMF** [SeleniumHQ/selenium#10923]
### What happened?

Selenium doesn't find the last element in a web 
![ElementSelection](https://user-images.githubusercontent.com/110677308/183088999-b22b7cfd-488c-4dd6-b7eb-d37d60e2191d.png)
site with GUI, headless it does.
I was using Selenium 4.1.3, then upgraded to 4.3.0. In both versions the same problem.
I attached a code snippet (ElementSelection.png) and also the results, first with GUI (WithGui.png)
![WithGui](https://user-images.githubusercontent.com/110677308/183089543-073d038c-2840-4d96-b6a5-f00cb9d8f5b0.png) and then headless (Headless.png)
![Headless](https://user-images.githubusercontent.com/110677308/183089805-bc627e52-1a99-4bbe-8f30-4e6a67ff231c.png)
Please remark: 
With GUI "i" is 11 and the last entry in list is "TexTrace".
Headless "i" is 12 and the last entry in list is "The TEAM Team".
The code, I'm using is exactly the same, except first with GUI then headless.
Has anybody an explanation for this behavior?

### How can we reproduce the issue?

```shell
I also attached the whole files:
FindLabelTexts.py (with GUI)
FindLabelTextsHeadless.py (headless)
and my functions and driver files:
AzureFunctions.py (with GUI)
AzureFunctionsHeadless.py (headless)
AzureDriver.py (with GUI)
AzureDriverHeadless.py (headless)
```

### Relevant log output

```shell
See under "What happened?"
```

### Operating System

Windows 10

### Selenium version

Python, Selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 104.0.5112.79 (Offizieller Build) (64-Bit)

### What are the browser driver(s) and version(s) where you see this issue?

Selenium webdriver

### Are you using Selenium Grid?

No

**Comment by HansZempMF** [comment]
Same behavior with Firefox

**Comment by adibkhaled** [comment]
@4HimAlone : I believe you may have set a window size for your headless driver.  Check below link, hopefully this will solve your issue:

[selenium-firefox-headless-returns-different-results](https://stackoverflow.com/questions/59031706/selenium-firefox-headless-returns-different-results/59033268#59033268)

**Comment by HansZempMF** [comment]
Hi adibkhaled

Yes, I use winow size and start maximized in headless. So I built a new GUI Version. Since you don't support the extension .py, I changed all files to extension .txt for the attachments:

- BackupAzureDevOps1
[BackupAzureDevOps1.txt](https://github.com/SeleniumHQ/selenium/files/9279243/BackupAzureDevOps1.txt)
- AzureFunctions1
[AzureFunctions1.txt](https://github.com/SeleniumHQ/selenium/files/9279245/AzureFunctions1.txt)
- AzureDriver1
[BackupAzureDevOps1.txt](https://github.com/SeleniumHQ/selenium/files/9279292/BackupAzureDevOps1.txt)
[AzureDriver1.txt](https://github.com/SeleniumHQ/selenium/files/9279293/AzureDriver1.txt)
[AzureFunctions1.txt](https://github.com/SeleniumHQ/selenium/files/9279294/AzureFunctions1.txt)

[AzureDriver1.txt](https://github.com/SeleniumHQ/selenium/files/9279244/AzureDriver1.txt)

With this the only difference to my headless version is the missing headless option. But the behavior is still as before. The last entry (The TEAM Team) is still missing. And using the headless version the entry (The TEAM Team) is found.

**Comment by HansZempMF** [comment]
[AzureDriverHeadless.txt](https://github.com/SeleniumHQ/selenium/files/9279445/AzureDriverHeadless.txt)
Hi diemol
Please see my newest attachments. Is this enough to reproduce the issue? Don't try to login. The pw is no longer valid.
I also attached my headless configuration (AzureDriverHeadless). All the file names ending wit "1" are with GUI.

**Comment by diemol** [comment]
I am not sure what we can do with those files. We need a complete script that can reproduce the issue, it does not need to be the exact same one you are using in your environment, just something complete enough for us to troubleshoot.

Please note we do not have an Azure account and neither won't troubleshoot issues related to an specific environment. If you are able to run your code locally successfully, then it means something is needed in your Azure env.

**Comment by HansZempMF** [comment]
Hi diemo

Well, I sent the main scirpt (BackupAzureDevOps1). From there I import some own functions (AzureFunctions1). From AzureFunctions1 I import AzureDriver1. With these 3 files you have all the code.
Additionally I attached now the headless version AzureBackupDevOpsHeadless
[BackupAzureDevOpsHeadless.txt](https://github.com/SeleniumHQ/selenium/files/9279874/BackupAzureDevOpsHeadless.txt)
I'm sure this is not an Azure Problem since it works headless. And if it works headless, it has to work with GUI too.

**Comment by diemol** [comment]
Finally I understand what your issue is, the code does not work when you avoid the headless flag.

In a CI or remote server you need to set up a display for the browser to open and work as a regular GUI application. A common alternative is to use Xvfb.

If you have more questions, feel free to drop by the chats we have in the Selenium community (links below).
