### ISSUE TITLE
[🐛 Bug]: In selenium grid 4 , selenium test is running only in headless mode for chrome driver

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#10922]
### What happened?

Recently updated grid 3 to grid 4. 
When execute existing web test for chrome, test is successful but execution is in non GUI mode. Unable to see the execution in node.
Chrome driver instantiating a session with blank page with data : . Test is successful. 

Same test run against selenium 3 and grid 3 , test is executing in GUI mode.

In selenium grid 4 , is the chrome driver execution is default to headless mode ? If so , then how can I change it to GUI mode. 

Passing the capabilities through --driver-configuration from toml file. Please suggest. 

Appreciate your help.

### How can we reproduce the issue?

```shell
Execute a selenium test against selenium grid 4 nodes with driver as chrome.
```

### Relevant log output

```shell
test is successful. But chrome driver opens a blank page with data :
```

### Operating System

windows 10

### Selenium version

Serenity 2.3.10

### What are the browser(s) and version(s) where you see this issue?

chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 102.0.5005

### Are you using Selenium Grid?

4.1.3

**Comment by diemol** [comment]
Closing as we did not get more information.
