### ISSUE TITLE
[🐛 Bug]: Translate Doesn't Work with Chrome

### ISSUE THREAD

**Issue by Ahmad-Agbaria** [SeleniumHQ/selenium#10925]
### What happened?

**Translation Doesn't Work With Any Language-Pairs in Chrome**

# Initializing Chrome reference

chrome_path = Service("C:\Python\Anaconda\chromedriver.exe")
custom_options = webdriver.ChromeOptions()

prefs = {
  "translate_whitelists": {"ja":"en"},
  "translate":{"enabled":"True"}
}
custom_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(service = chrome_path, options=custom_options)
I've also tried

custom_options.add_argument('--lang=en')
driver = webdriver.Chrome(service = chrome_path, options=custom_options)

Issue was discussed multiple times on stackoverflow, for example: https://stackoverflow.com/questions/70876934/translating-chrome-page-using-selenium-is-not-working

### How can we reproduce the issue?

```shell
Selenium Python Package Version: 4.3.0
Chrome Version: 104.0.5112.83
Chrome-Driver Version: 104.0.5112.79
Python Version: 3.10.6

Note: The mentioned bug affects multiple versions and not only these.
```

### Relevant log output

```shell
.
```

### Operating System

macOS Big Sur

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 104.0.5112.83

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.79

**Comment by diemol** [comment]
This is a Chrome only feature, please reach out to the Chrome/ChromeDriver team for more information.

**Comment by titusfortner** [comment]
fwiw, there is nothing wrong with chrome/chromedriver. This is a Ruby example (Se 4.3, Chrome 104, Big Sur)

```ruby
opts = {translate: {enabled: true}, translate_whitelists: {ja: 'en'}}
chrome_opts = Selenium::WebDriver::Chrome::Options.new(prefs: opts)
d = Selenium::WebDriver.for :chrome, options: chrome_opts
d.get 'https://bbc.com/japanese'
```

-----
<img width="796" alt="Screen Shot 2022-08-09 at 1 08 19 PM" src="https://user-images.githubusercontent.com/777185/183727794-cdf5d25f-a8ee-4c1a-a234-266afa301a51.png">

-----

Should work in Python. @symonk can you verify?

**Comment by Ahmad-Agbaria** [comment]
@titusfortner I can confirm this isn't working for me using python:

```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

chrome_path = Service("./chromedriver")
custom_options = webdriver.ChromeOptions()

prefs = {
    "translate_whitelists": {"ja": "en"},
    "translate": {"enabled": "true"}
}
custom_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(service=chrome_path, options=custom_options)
driver.get('https://bbc.com/japanese')
```

@diemol seems the problem is related to python version only and not to chrome driver.

**Comment by symonk** [comment]
when calling to `/newSession` in this case, the following capabilities are provided (post-processed):

```python
{'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': 'normal', 'goog:chromeOptions': {'prefs': {'translate_whitelists': {'ja': 'en'}, 'translate': {'enabled': 'true'}}, 'extensions': [], 'args': []}}}}
```

however the remote end response capabilities returns:

```
'goog:chromeOptions': {'debuggerAddress': 'localhost:49882'}
```

and the page is not translated automatically, i need to read into prefs/and the goog: vendor key/capability (and the expected formats) in general, will report back shortly

**Comment by titusfortner** [comment]
Those capabilities look right... try just doing a `driver.refresh()`.

**Comment by Ahmad-Agbaria** [comment]
Doing `driver.refresh()` didn't solve the problem.

**Comment by titusfortner** [comment]
Oh, `enabled` value needs to be a boolean, not a String

**Comment by titusfortner** [comment]
This is what I'm sending to Chrome via Ruby, which works:
```
{"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"prefs":{"translate":{"enabled":true},"translate_whitelists":{"ja":"en"}}}}}}
```

**Comment by Ahmad-Agbaria** [comment]
Changed to boolean still same issue

**Comment by lindsey98** [comment]
I suspect it works for Ruby but not Python, I have the same problem as @Ahmad-Agbaria, ```driver.refresh()``` and change to boolean do not work

**Comment by symonk** [comment]
I suspect it might be to do with something on the chrome it is running on, language packs or something etc

**Comment by titusfortner** [comment]
There's just a weird timing thing going on. Looks like it takes a while after Chrome starts for it to register the setting. This works:

```
driver = webdriver.Chrome(service=chrome_path, options=custom_options)
sleep(15)
driver.get('https://bbc.com/japanese')
```

Here's an example of it working on Sauce Labs: https://app.saucelabs.com/tests/c753cff805c849b389d60a5b02a68390#3
