### ISSUE TITLE
[🐛 Bug]: DotNet WebDriver msedge(Ver:103.0.1264.77）Use EdgeOptions DebuggerAddress is 127.0.0.1:50521  Error

### ISSUE THREAD

**Issue by flysky2005** [SeleniumHQ/selenium#10921]
### What happened?

OpenQA.Selenium.WebDriverArgumentException: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: ms:edgeOptions
from invalid argument: unrecognized msedge option: excludeSwitches
   在 OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   在 OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   在 OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   在 OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   在 OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   在 OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   在 XRBrowser.MainForm.CreateEdgeDriver(Boolean& isRunning)）

### How can we reproduce the issue?

```shell
var options = new EdgeOptions();
var debugHost = "127.0.0.1";
var debugPort = 50521;
options.DebuggerAddress = $"{debugHost}:{debugPort}";
driver = new EdgeDriver(driverService, options, TimeSpan.FromSeconds(40));
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverArgumentException: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: ms:edgeOptions
from invalid argument: unrecognized msedge option: excludeSwitches
   在 OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   在 OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   在 OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   在 OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   在 OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   在 OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   在 XRBrowser.MainForm.CreateEdgeDriver(Boolean& isRunning)）
```

### Operating System

Windows 11

### Selenium version

Dotnet 4.3

### What are the browser(s) and version(s) where you see this issue?

msedge 103.0.1264.77

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver 103.0.1264.77

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Can you please share a more complete code snippet? I was not able to reproduce this.

**Comment by flysky2005** [comment]
```csharp
        private void button1_Click(object sender, EventArgs e)
        {
            EdgeOptions options = new EdgeOptions();
            options.AddArguments("start-maximized");
            options.AddExcludedArgument("enable-automation");
           
            var debugHost = "127.0.0.1";
            var debugPort = 45411;
            options.AddArgument($"--remote-debugging-host={debugHost}");
            options.AddArgument($"--remote-debugging-port={debugPort}");
            options.DebuggerAddress = $"{debugHost}:{debugPort}";
            var service = EdgeDriverService.CreateDefaultService();
            //----- Create ChromeDriver -----
            
            driver = new EdgeDriver(service, options, TimeSpan.FromSeconds(40));

            driver.Navigate().GoToUrl("www.bing.com");
        }
```

**Comment by diemol** [comment]
I was able to see the issue. We are going to work on it. As a workaround for now, please comment out the line below and it should work.

```csharp
EdgeOptions options = new EdgeOptions();
options.AddArguments("start-maximized");
options.AddExcludedArgument("enable-automation");

var debugHost = "127.0.0.1";
var debugPort = 45411;
options.AddArgument($"remote-debugging-host={debugHost}");
options.AddArgument($"remote-debugging-port={debugPort}");
//options.DebuggerAddress = $"{debugHost}:{debugPort}"; <== Comment out this line

EdgeDriver driver = new EdgeDriver(options);
driver.Navigate().GoToUrl("https://www.bing.com/");
driver.Quit();
```

**Comment by pujagani** [comment]
I was able to reproduce the issue and triage it. There is a bug in how Selenium C# is sending "debuggerAddress" to the browser. It should be part of the "args" but sending it as a capability.
```
{[]: newSession {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["start-maximized","--remote-debugging-host=127.0.0.1","--remote-debugging-port=45411"],"debuggerAddress":"127.0.0.1:45411","excludeSwitches":["enable-automation"]}}]}}}
```
I have some changes made on my local to fix it but I am still iterating over the best way to fix this.
Meanwhile, please use the code snippet below as a workaround:

```
 EdgeOptions options = new EdgeOptions();

            options.AddArguments("start-maximized");
            options.AddExcludedArgument("enable-automation");

            var debugHost = "127.0.0.1";
            var debugPort = 45411;
            options.AddArgument($"remote-debugging-host={debugHost}");
            options.AddArgument($"remote-debugging-port={debugPort}");
            options.AddArgument($"debuggerAddress={debugHost}:{debugPort}");
            //  options.DebuggerAddress = $"{debugHost}:{debugPort}";

            EdgeDriver driver = new EdgeDriver(options);

            driver.Navigate().GoToUrl("https://www.bing.com/");
            driver.Quit();

```

**Comment by titusfortner** [comment]
According to the Chromedriver docs it is its own capability, and even the driver code itself appears to support it — https://github.com/bayandin/chromedriver/blob/main/capabilities.cc#L598-L599

If it is not working, then I think this is a chromedriver bug, and not a problem with Selenium code.

**Comment by pujagani** [comment]
+1 with Titus's comment. Selenium seems to have done the right thing. https://chromedriver.chromium.org/capabilities#h.p_ID_102 also mentions it needs to be top-level capability. I could see this error as far as Chrome version 85.

**Comment by flysky2005** [comment]
thank you
