### ISSUE TITLE
[🐛 Bug]: Unable to create "select" class object , "NoMethodError: undefined method `element_dom_attribute' for nil:NilClass

### ISSUE THREAD

**Issue by maheshchaudharCoupa** [SeleniumHQ/selenium#10927]
### What happened?

We have upgraded selenium-webdriver to 4.3.0 version, then we are not able to uses Select class.

Selenium::WebDriver::Support::Select.new(webelement)
NoMethodError: undefined method `element_dom_attribute' for nil:NilClass
from /Users/**/.rvm/gems/ruby-2.7.4/gems/selenium-webdriver-4.3.0/lib/selenium/webdriver/common/element.rb:146:in `dom_attribute'

### How can we reproduce the issue?

```shell
Try to create select class object with selenium webdriver version 4.3.0.

Selenium::WebDriver::Support::Select.new(element)
```

### Relevant log output

```shell
NoMethodError: undefined method `element_dom_attribute' for nil:NilClass
from /Users/**/.rvm/gems/ruby-2.7.4/gems/selenium-webdriver-4.3.0/lib/selenium/webdriver/common/element.rb:146:in `dom_attribute'
```

### Operating System

macOS Monterey

### Selenium version

Ruby 4.3.0

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver

**Comment by titusfortner** [comment]
That's odd, you need to pass in an element to Select constructor. It will have `#tag_name` called on it and verify that it is a `select` tag before it tries to call `#element_dom_attribute`, except according to that error message, the element object is `null`. Are you monkey patching something?

**Comment by diemol** [comment]
@harsha509 just added this to the JS bindings, will be available on the next release.
https://github.com/SeleniumHQ/selenium/commit/35adf8bef56cd5efc166feda96224b74800b8503

**Comment by titusfortner** [comment]
@diemol this was a Ruby issue not a JS issue, but we didn't hear back, so we can leave closed. Will re-open if get more info.

**Comment by titusfortner** [comment]
@diemol this was a Ruby issue not a JS issue, but we didn't hear back, so we can leave closed. Will re-open if get more info.

**Comment by maheshchaudharCoupa** [comment]
Thanks guys for all your inputs, this was issues with configuration and resolved now
