### ISSUE TITLE
[🐛 Bug]: Redundant extra dependencies for urllib3[secure] in Selenium 4

### ISSUE THREAD

**Issue by BLKSerene** [SeleniumHQ/selenium#10931]
### What happened?

It seems that the extra dependencies for `urllib3[secure]` in [setup.py](https://github.com/SeleniumHQ/selenium/blob/a6f8028b5cc6ceaf535c00bcee8c364e1b90d71b/py/setup.py#L73) of `Selenium 4` are redundant since `urllib3.contrib.pyopenssl` is not used in any file.

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

Python 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 104

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 104

**Comment by symonk** [comment]
Thanks for the issue @BLKSerene, this was addressed in #10932 and will be no longer included in `4.5`+
