### ISSUE TITLE
[🐛 Bug]: In jdk17 with JPMS creating new Chrome driver causes runtime exception (same as #10644)

### ISSUE THREAD

**Issue by valodzka** [SeleniumHQ/selenium#10933]
### What happened?

Bug #10644 was incorrectly closed by @titusfortner, it still valid as of selenium 4.3.0
See #10644 to see many users comments and details.

Here the full reproducer https://github.com/valodzka/selenium-bug-10644

### How can we reproduce the issue?

```shell
Clone https://github.com/valodzka/selenium-bug-10644 and try run it
```

### Relevant log output

```shell
see bug #10644
```

### Operating System

Probably all, tested on Mac OS and Windows

### Selenium version

jdk 17, selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 103

### Are you using Selenium Grid?

No

**Comment by sergeyblohin** [comment]
> Bug https://github.com/SeleniumHQ/selenium/issues/10644 was incorrectly closed by @tit --usfortner--

Hi) I am the @tit whose name was originally written in the first message.
It would be a simple funny coincidence if I haven't been involved in UI testing automation using Selenium/Cypress technologies for 10 years.

**Comment by tit** [comment]
Hi! I am @tit from first message (before correct typo).
It would be a simple funny coincidence if I haven't been involved in UI testing automation using Selenium/Cypress technologies for 10 years. :)

**Comment by titusfortner** [comment]
First, don't open a new ticket for something that was closed. If you have questions, reply on the closed ticket, we still respond on closed tickets. 

Second, I reproduced your issue, then removed the driver variable from a static context and the problem went away. Send me a reproducible example that doesn't have a static variable and I'll reopen the first ticket.

**Comment by valodzka** [comment]
> Second, I reproduced your issue, then removed the driver variable from a static context and the problem went away. Send me a reproducible example that doesn't have a static variable and I'll reopen the first ticket.

@titusfortner I removed all static variables in the reproducer before opening this bug and I can see that issue still present. Also I don't think that the JPMS module issue has anything to do with the `static` modifier. So I suppose you also changed something else to make it work. Reproducer still triggers the issue without static variable, you can use provided repository to check.

> First, don't open a new ticket for something that was closed. If you have questions, reply on the closed ticket, we still respond on closed tickets.

Ok, next time I will do that. But based on my experience with other projects, comments to closed issues are often ignored.
