### ISSUE TITLE
[🐛 Bug]: Re-add logging endpoints to Grid

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#10949]
### What happened?

When running on Grid, the logging endpoints return an error (all browsers except for Chrome).

```
org.openqa.selenium.UnsupportedCommandException: The command 'GET /session/167E1FE8-9D49-4B7A-94FB-D36B77AC51D1/se/log/types' was not found.
```

We should add those endpoints to Grid, and add anything received from the driver.

Adding the Session logs for grid would be a nice bonus, but this shouldn't error.

### How can we reproduce the issue?

```shell
Capabilities options = new SafariOptions();
driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), options);
driver.manage().logs().getAvailableLogTypes();
```

### Operating System

n/a

### Selenium version

4.4.0

### What are the browser(s) and version(s) where you see this issue?

Firefox, Safari

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

4.4.0

**Comment by TamsilAmani** [comment]
I am looking into this issue

**Comment by AutomatedTester** [comment]
@titusfortner I have a few questions that I hope you can clarify.

* Does Chrome endpoints still exist when `{w3c:true}`?
* While this is good for Chrome support, do we want to be adding this back just for one browser? Wouldn't it be better to wait for the similar feature set that is coming in WebDriver Bidi
* What value do we see this having over getting people to move over to our OpenTelemetry support? (yes it doesn't give us browser internals but see question 2)

**Comment by TamsilAmani** [comment]
@AutomatedTester I tested the issue with `{w3c:true}`, the end point exists in chrome.

**Comment by diemol** [comment]
What I understand is that Chrome works in Grid and probably others work too but the endpoint does not exist, is that right, @titusfortner?

**Comment by AutomatedTester** [comment]
Firefox doesn't support this endpoint, and I don't think that safari has support. This is going to only benefit Chrome users. I'm not fully against only supporting just chrome but we need to make it a deliberate choice

**Comment by diemol** [comment]
Now remembering, I think this has always been a Chrome/Chromium only feature. I assume that Grid 3 responds in the same way. 

Should we leave it as it is and wait for BiDi?

**Comment by titusfortner** [comment]
At the very least, we need for it `getAvailableLogTypes()` to return an empty list not throw an exception. Or to remove the method if we don't want to support it.

**Comment by TamsilAmani** [comment]
@titusfortner, as per @AutomatedTester it is better to deprecate and remove the method. Shall I make the change?

**Comment by titusfortner** [comment]
Actually, looking at this again... Chromium supports that endpoint:
https://github.com/bayandin/chromedriver/blob/d856c5891c91d5386e06b7f6ac5356b555e27e0c/client/command_executor.py#L182

So this should be supported via augmenter, instead of through the RemoteWebDriver directly.
Same thing with .NET - adding it to the list of `chromiumCustomCommands`

So, yeah, now I think we should deprecate `logs()` from `Options` interface, but I think we want to have a `chromium/AddLogs.java` file with an `AutoService` that implements `Logs`.

Allow Chrome/Edge users to do:
((Logs) driver).logs.getAvailableLogTypes()`

Maybe we need to discuss this again?

**Comment by AutomatedTester** [comment]
I think we should deprecate and remove in favour of what we do with bidi and work towards cross browser compatibility

**Comment by titusfortner** [comment]
The one piece that is missing here is that we do not have a way of getting Grid logs right now. Previously, this endpoint is what allowed that. Supporting that is independent of what BiDi does for browser logs.

**Comment by diemol** [comment]
During the meeting held on [24.11.2022](https://www.selenium.dev/meetings/2022/tlc-11-24/) it was agreed not to implement logging features at this time, but that an error shouldn’t be thrown for a valid method asking about supported logs.

**Comment by titusfortner** [comment]
We should revisit this.

I'm pretty sure in our last conversation about it we were thinking of "browser" logs, which people can implement whatever they want with BiDi, so it doesn't make sense to put this endpoint back in.

But right now there is no way for the client code to get logging information for the driver or the server, and the user really should be able to get these.

**Comment by pujagani** [comment]
After yesterday's TLC discussion, can we close this?

**Comment by diemol** [comment]
I believe so.
