### ISSUE TITLE
Selenium standalone server creates zombie processes AFTER CALLING driver.quit()

### ISSUE THREAD

**Issue by frank-calma** [SeleniumHQ/selenium#1094]
We run a fairly aggressive distributed selenium grid, executing ~200 tests per node machine per hour. Each test is run using a new chrome driver instance for each test, and properly calling driver.quit() at the end of each test. We have found that the memory on our nodes gradually fills up. After some investigation, we found that our selenium standalone server was holding on to thousands of handles to dead chromedriver instances. Each one was taking up 20kb of ram, and no longer attached to any live process / PID. After resetting the server, these zombie processes were immediately released from memory. At present we have not attempted to replicate the issue using firefox/IE or through local execution. 
![zombie processes](https://cloud.githubusercontent.com/assets/6556555/10232681/fa91598c-683e-11e5-9040-4e90c6c02303.png)

**Comment by ddavison** [comment]
I haven't seen this behavior for quite some time, but when I used to be on windows, I had a similar problem, and we weren't the only ones. 

I [wrote this answer](http://stackoverflow.com/questions/21320837/release-selenium-chromedriver-exe-from-memory/21320949#21320949) a long time ago. honestly if its still popping up, it may be worth bringing up to the chrimedriver team as well. this only seems to happen on windows. havnt encountered it once when I switched to a mac.

**Comment by mach6** [comment]
@frank-calma is this still an issue in Selenium 3 and the latest chromedriver? If so, please comment back and we can re-open this.

**Comment by frank-calma** [comment]
I dunno. We switched to a dynamic dockerized grid, and I'm not going back.

**Comment by hardeepkukreja** [comment]
@mach6 @frank-calma  I am having same issue with Firefox. Could you please guide that how can I fix the same.

**Comment by aakashgupta96** [comment]
Hi,

I am also facing the same issue with geckodriver and Firefox with selenium-ruby bindings. Even after calling driver.quit( ) approximately 5% of times, geckodriver becomes zombie and keeps on running in background.
Any suggestions to avoid this?

**Comment by titusfortner** [comment]
@aakashgupta96 the Ruby bindings stop the driver with the [`at_exit` hook](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/service.rb#L67). Unless your ruby processes are being halted abnormally, there shouldn't be an issue. If they are being halted abnormally, then you'll need your own solution for ending processes.

**Comment by ajimix** [comment]
I'm having the same problem. Running a lot of tests with node [selenium-webdriver](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver) and even after calling `driver.quit()` some firefox processes doesn't get closed.

**Comment by koreyba** [comment]
The same problem now with Selenium 3.14 and Chromedriver 2.43.
When I use driver.Quit() it creates a process that eats 30-50% of my CPU. 
3 processes like this eat my CPU on 100%.

**Comment by dima-kov** [comment]
Still actually
