### ISSUE TITLE
[🐛 Bug]: Installation of a browser extension in Firefox with Java

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#10946]
### What happened?

The following [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/extensions/DarkBgFirefoxTest.java) installs a browser extension in Firefox with Selenium and Java. The test works nicely since this extension changes the page background to black. The equivalent [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/extensions/DarkBgChromeTest.java) in Chrome also works.

Nevertheless, if I change the XPI extension to another one ([this](https://github.com/bonigarcia/browserwatcher/releases/download/1.2.0/browserwatcher-1.2.0.xpi)), the extension is not installed. The following [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/extensions/BrowserWatcherFirefoxTest.java) allows to reproduce the issue (we can check that the extension is not loaded since the variable `logs` is `null`).

The equivalent [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/extensions/BrowserWatcherChromeTest.java) in Chrome works nicely (we can check that the extension is loaded since the variable `logs` not `null`).

Moreover, the same extension can be installed in Firefox but using `installExtension` instead to the installation using the profile. This [test](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/extensions/InstallBrowserWatcherFirefoxTest.java) proves it. Nevertheless, I would need to do it using the first approach (i.e., through `FirefoxProfile` and `FirefoxOptions`).

### How can we reproduce the issue?

```shell
1. Clone https://github.com/bonigarcia/webdrivermanager-examples
2. Run BrowserWatcherFirefoxTest
3. The variable logs is null (and it should not), and so, the test fails
```

### Relevant log output

```shell
Check the output of the variable logs in the previous tests.
```

### Operating System

Ubuntu 20.04, Windows 10, and macOS 11

### Selenium version

Java 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 103

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.31.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Why can't you use the `installExtension()` method? Feel free to pile on to my feature request in https://github.com/mozilla/geckodriver/issues/1476

If this is working for one extension, but not other, it means that Selenium is sending the correct thing to the driver, and the driver is having an issue with it for some reason. It's probably a duplicate of one of the bugs like this: https://github.com/mozilla/geckodriver/issues/1588

**Comment by bonigarcia** [comment]
I use `installExtension()`, but I would prefer to use options to install the extension since the `installExtension()` approach only works for local Firefox (i.e., `FirefoxDriver` objects), and I would like to do it as well for remote Firefox (i.e., `RemoteWebDriver` objects).

**Comment by titusfortner** [comment]
Ah, but you can use it remotely, just need to use the Augmenter; here's an example — https://docs.saucelabs.com/web-apps/automated-testing/selenium/selenium4/#install-and-uninstall-add-ons

**Comment by bonigarcia** [comment]
I did not know it. Indeed, using the augmenter did the trick, thanks a lot, @titusfortner!

**Comment by titusfortner** [comment]
Selenium has a few *very cool classes that haven't gotten nearly enough attention. Eventually it all will be added to our docs. :)
