### ISSUE TITLE
[🐛 Bug]: send_keys do nothing 

### ISSUE THREAD

**Issue by anisaAnya** [SeleniumHQ/selenium#10948]
### What happened?

https://github.com/SeleniumHQ/selenium/issues/6790
Same behavior as in this old issue.

`browser.find_element(by=By.TAG_NAME, value='body').send_keys(Keys.COMMAND + "t")`
does nothing and no error logs appear. 
FireFox version 103.0.2 (most recent)
MacOS 
selenium==4.2.0

### How can we reproduce the issue?

```shell
browser = webdriver.Firefox()
browser.find_element(by=By.TAG_NAME, value='body').send_keys(Keys.COMMAND + "t")
```

### Relevant log output

```shell
no logs
```

### Operating System

Mac OS

### Selenium version

selenium==4.2.0 Python

### What are the browser(s) and version(s) where you see this issue?

FireFox 103

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver

**Comment by anisaAnya** [comment]
It would be nice if anyone suggest how to open a new browser's tab if Command+t doesn't work

**Comment by titusfortner** [comment]
The Selenium provided way to create a new tab is this:
```
driver.switch_to.new_window('tab')
```

Selenium is properly sending those keys, but the driver is choosing not to translate that into opening a new browser context.
