### ISSUE TITLE
[🐛 Bug]:  chrome not reachable

### ISSUE THREAD

**Issue by Lyfhael** [SeleniumHQ/selenium#10945]
### What happened?

I use undetected_chromedriver, which uses Selenium, for my script that crawls web pages 24/7. I launch the script from my Debian 10 VPS through this command : `nohup python3 -u program.py > archiver.out &`

It works. But when if I close ssh session(I use putty) to my VPS, and that I relog in, when I check the logs in `archiver.out` I see bunch of `chrome not reachable` and it doesn't fix itself, I need to restart the program.

Since my VPS has no GUI or monitor, I used  this : 
```
#install Xvfb
sudo apt-get install xvfb

#set display number to :99
Xvfb :99 -ac &
export DISPLAY=:99    

#you are now having an X display by Xvfb
```

And in my python script that runs Selenium, I use this : 
```
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options
from selenium import webdriver

from pyvirtualdisplay import Display

display = Display(visible=0, size=(800, 600))
display.start()
options = webdriver.ChromeOptions() 
options.add_argument("--no-sandbox")
driver = uc.Chrome(use_subprocess=True,executable_path="/usr/local/bin/chromedriver",options=options)
```

It's like upon closing the SSH session, the display disconnects somehow, making Selenium unable to connect to it. Because I recognize this error message `chrome not reachable`, I had it before when I had not created the display with Xvfb. But I can't be sure 100%

### How can we reproduce the issue?

```shell
Take the code I wrote in "What Happened", use it to crawl web pages in a debian 10 environement with no GUI, and don't forget to setup a display with the code I also wrote above about Xvfb, then disconnect from the ssh session to your debian 10 vps, and the relog in, and you should have the error.
```

### Relevant log output

```shell
Message: chrome not reachable
  (Session info: chrome=104.0.5112.79)
Stacktrace:
#0 0x55d616cf3403 <unknown>
#1 0x55d616af964b <unknown>
#2 0x55d616ae9d24 <unknown>
#3 0x55d616adae2e <unknown>
#4 0x55d616adf962 <unknown>
#5 0x55d616ae4946 <unknown>
#6 0x55d616afab72 <unknown>
#7 0x55d616b612f1 <unknown>
#8 0x55d616b4e8f3 <unknown>
#9 0x55d616b240d8 <unknown>
#10 0x55d616b25205 <unknown>
#11 0x55d616d3ae3d <unknown>
#12 0x55d616d3ddb6 <unknown>
#13 0x55d616d2413e <unknown>
#14 0x55d616d3e9b5 <unknown>
#15 0x55d616d18970 <unknown>
#16 0x55d616d5b228 <unknown>
#17 0x55d616d5b3bf <unknown>
#18 0x55d616d75abe <unknown>
#19 0x7f0d49a52fa3 <unknown>
```

### Operating System

Debian 10

### Selenium version

Python 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 104.0.5112.79

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307})

**Comment by diemol** [comment]
This is most likely not related to Selenium at all. When the SSH session disconnects, probably the user session stops working properly. Check alternatives, like running everything as a demon, you can also check tools like Supervisor for these things.

**Comment by Lyfhael** [comment]
> This is most likely not related to Selenium at all. When the SSH session disconnects, probably the user session stops working properly. Check alternatives, like running everything as a demon, you can also check tools like Supervisor for these things.

Supervisor did the trick, you're a lifesaver thanks man.
