### ISSUE TITLE
[🚀 Feature]: Add a constructor for RemoteWebdriver that accepts a DriverService class

### ISSUE THREAD

**Issue by JonathonFord** [SeleniumHQ/selenium#10957]
### Feature and motivation

Hello I am currently trying to use the selenium hub with docker and one of the things we require is to run a webdriver as a certain user. We can do this with the Service class for normal drivers but there is no way to do this with a webdriver from what I can tell. We are looking into editing the chrome nodes to be authenticated as a user but it would be much simpler if we could just pass a service in the constructor of the remote webdriver 

### Usage example

service.DriverProcessStarting += (object sender, DriverServiceProcessStartingEventArgs e) =>
    {
        // In some versions of .NET, ProcessStartInfo.Password requires a
        // SecureString, not a string, and there is no easy conversion between
        // the two. The below trick will work, but you'd be better off having
        // your password argument be a SecureString in the first place.
        SecureString securePassword = new NetworkCredential("", password).SecurePassword;
        e.DriverServiceProcessStartInfo.UserName = username;
        e.DriverServiceProcessStartInfo.Password = securePassword;
        e.DriverServiceProcessStartInfo.Domain = domain;
    }

    Driver = new RemoteWebDriver(uri, service, options);

**Comment by diemol** [comment]
The `DriverServiceProcessStartInfo` feature seems to be only present in the C# bindings, and probably only works on Windows. Given that the Docker images are using Ubuntu, I imagine this won't work.

But more than that, can you explain why you need to run "webdriver as a certain user"? What is the use case?

**Comment by titusfortner** [comment]
Process start info is cross platform, and just provides info on how to start the process. That said, it appears that `Password` is explicitly Windows-only https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.password?view=net-6.0#system-diagnostics-processstartinfo-password

**Comment by titusfortner** [comment]
Separately from this specific use case, it would be "nice" to be able to pass arguments to a grid node to instruct it how to start the driver...

**Comment by diemol** [comment]
There are tools outside Selenium Grid that can do that. Supervisor is an example. You can configure the user to use when starting the Node, and every child process should inherit that.

What I'm saying is that so far it doesn't not seem like a feature Grid needs to have.

**Comment by JonathonFord** [comment]
Sorry for the late reply. Most of the UI tests I run are for in house web aplications. These sites sign users in using AD (windows active directory), I thought if I could pass a username and password to a service and pass that to a webdriver it might be able to run that instance of chromedriver with the service account specified

**Comment by diemol** [comment]
The approach I would recommend is to start the `Nodes` in Selenium Grid with the user that is already signed in the AD, and you will probably need Windows machines for that. 

I am not aware how this can be done with Docker Selenium since it uses Ubuntu. Probably you can do that only with Windows machines.

I will close this as this is something Grid should not take care of but rather the environment where it is being used.
