### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by viijaysolanki** [SeleniumHQ/selenium#10952]
### What happened?

this is my code
..
.
.
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

class TwitterBot:
    def __init__(self ,username,password):
        self.username=username
        self.password=password
        
        self.bot = webdriver.Firefox()
    def login(self):
        bot = self.bot
        bot.get('https://www.twitter.com')
        time.sleep(3) 
        email = bot.find_element_by_class_name('email-input')
        password = bot.find_element_by_name('session[password]')
        email.clear()
        password.clear()
        email.send_keys(self.username)
        password.send_keys(self.password)

ed = TwitterBot( 'useremail' , 'userpassword')
ed.login()

### How can we reproduce the issue?

```shell
please help me solve this error
i am just using this just to login to twitter  but getting ton of error
```

### Relevant log output

```shell
this is the error i am getting
.
.
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vijaysolanki777\AppData\Local\Programs\Python\appt.py", line 23, in <module>
    ed = TwitterBot( 'ourfirst1@protonmail.com' , 'subkapyaarabaalmodi@2002')
  File "C:\Users\vijaysolanki777\AppData\Local\Programs\Python\appt.py", line 10, in __init__
    self.bot = webdriver.Firefox()
  File "C:\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 172, in __init__
    self.service.start()
  File "C:\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

### Operating System

windows 8.1

### Selenium version

python 3.9

### What are the browser(s) and version(s) where you see this issue?

firefox latest

### What are the browser driver(s) and version(s) where you see this issue?

chrome latest and gecko is latest

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
Thank you for the details. As the error message says "`Message: 'geckodriver' executable needs to be in PATH.`" This is not a Selenium error but a setup issue. Please ensure the driver is on your system path. Refer to https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#2-the-path-environment-variable for more details.
