### ISSUE TITLE
[🚀 Feature]: Expose websocket connection from CDP connection

### ISSUE THREAD

**Issue by slhck** [SeleniumHQ/selenium#10960]
### Feature and motivation

Currently, the WebDriver exposes specific methods like:

```js
async onLogEvent(connection, callback)
async onLogException(connection, callback)
async logMutationEvents(connection, callback)
```

These all invoke particular Chrome DevTools Protocol methods and register listeners on the WebSocket for responses.

It would be very helpful to expose the underlying WebSocket connection for users to be able to manually inspect events. The `_wsConnection` property is not accessible publicly though.

### Usage example

For instance, it would be nice to be able to do:

```js
const cdpConnection = await driver.createCDPConnection('page');
const websocket = cdpConnection.getWsConnection();
websocket.on('message', (message) => {
  const params = JSON.parse(message)
  // do something with the message    
});
```

**Comment by diemol** [comment]
I believe we do not want that because the idea is to expose an stable API/methods and replace the implementation with WebDriver BiDi. 

However, let's see what the others say.

**Comment by pujagani** [comment]
+1 with Diego's comment. To add to it, we plan to have APIs that let users add event listeners for any event.

**Comment by slhck** [comment]
In that case, having listeners would be a good solution too. Right now it's just very arbitrary in terms of what is being exposed. Looking forward to those features!
