### ISSUE TITLE
[🐛 Bug]: Invalid handling of strings as iterables in `frame_to_be_available_and_switch_to_it`

### ISSUE THREAD

**Issue by Mr986897** [SeleniumHQ/selenium#10963]
### What happened?

In selenium webdriver/support/expected_conditions py line 247 The _predicate function in frame_to_be_available_and_switch_to_it is incorrect for locator. When using locator as an ID, it will also enter the first IF branch and trigger an exception similar to the following: "TypeError: find_element() takes from 1 to 3 positional arguments but 8 were given" We should check the locator type. If it is a character, we should go to the else branch.

### How can we reproduce the issue?

```shell
wait.until(ec.frame_to_be_available_and_switch_to_it("iframe3"))
```

### Relevant log output

```shell
File "/xxxxxx/case.py", line 32, in test_add
    wait.until(ec.frame_to_be_available_and_switch_to_it("iframe3"))
  File "/xxxxxx/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 81, in until
    value = method(self._driver)
  File "/xxxxxx/venv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 256, in _predicate
    driver.switch_to.frame(driver.find_element(*locator))
TypeError: find_element() takes from 1 to 3 positional arguments but 8 were given
```

### Operating System

Mac

### Selenium version

python

### What are the browser(s) and version(s) where you see this issue?

all

### What are the browser driver(s) and version(s) where you see this issue?

all

### Are you using Selenium Grid?

all

**Comment by symonk** [comment]
Thanks @Mr986897, Good spot; `str` types in python will pass the `hasinstance(x, "__iter__")` check and be unpacked as characters here.  I am on vacation but will fix it when I am home if someone else hasen't by then, without looking too much we should check maybe if its not string types, likely a python2 outlier that never got updated.  Checking `__iter__` is also likely not sufficient as it may fail unjustly for anything using the older style iteration protocol via `__getitem__`.  Instead try create an iterable of locator via `iter(locator)` and catch the exception to determine if its truly iterable or not.

Thanks

**Comment by mdmintz** [comment]
https://github.com/SeleniumHQ/selenium/pull/10967
