### ISSUE TITLE
[🐛 Bug]: BrowserFactory::LaunchEdgeInIEMode always creates temp user-data-dir so we cannot use Default profile

### ISSUE THREAD

**Issue by sohrabtowfighi** [SeleniumHQ/selenium#10968]
### What happened?

I am trying to run IE in Edge using the default user profile as shown in the code below.
It never works.
I realized that the iedriver java code hardcodes that a temporary directory is needed.
This is related to pull request [10006 ](https://github.com/SeleniumHQ/selenium/pull/10006)

The relevant code is found in selenium/cpp/iedriver/BrowserFactory.cpp
See the function, void BrowserFactory::LaunchEdgeInIEMode

  // create a temporary directory for IEDriver test
  std::wstring temp_dir;
  if (CreateUniqueTempDir(temp_dir)) {
    LOG(TRACE) << L"Using temporary folder " << LOGWSTRING(temp_dir) << ".";
    executable_and_url.append(L" --user-data-dir=" + temp_dir);
    this->edge_user_data_dir_ = temp_dir;
  }

It does not make sense to me why we need to hard code the user-data-dir. It is important that selenium be able to operate using a specified profile. The script below intentionally comments out the path to the msedge.exe file so that an error is raised. In the error output, it is clear that a temporary directory is being used as the user-data-dir

### How can we reproduce the issue?

```shell
from selenium import webdriver
import os
import sys
ieOptions = webdriver.IeOptions() 
pwd = os.path.dirname(sys.argv[0])
web_driver_path = os.path.join(pwd,'IEDriverServer.exe')    
msedge_user_profile = ('C:/Users/' + os.getlogin() + 
                       '/AppData/Local/Microsoft/Edge/User Data/')
ieOptions.add_additional_option('user-data-dir', msedge_user_profile)
ieOptions.add_additional_option("profile-directory", "Profile 1")
ieOptions.attach_to_edge_chrome = True
#ieOptions.edge_executable_path = (
#             'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe')
```

### Relevant log output

```shell
File "C:\Users\admin\Desktop\pyCC\test.py", line 18, in <module>
    driver = webdriver.Ie(executable_path=web_driver_path, options=ieOptions)
  File "C:\Users\admin\anaconda3\lib\site-packages\selenium\webdriver\ie\webdriv
er.py", line 110, in __init__
    super().__init__(
  File "C:\Users\admin\anaconda3\lib\site-packages\selenium\webdriver\remote\web
driver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\admin\anaconda3\lib\site-packages\selenium\webdriver\remote\web
driver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\admin\anaconda3\lib\site-packages\selenium\webdriver\remote\web
driver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\admin\anaconda3\lib\site-packages\selenium\webdriver\remote\err
orhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unexpected error
 launching Internet Explorer. CreateProcess() failed for edge with the following
 command: msedge.exe --ie-mode-force --internet-explorer-integration=iemode --us
er-data-dir=C:\Users\admin\AppData\Local\Temp\IEDriver-0d804d6b-746b-4dfe-9393-5
d44c3bb0984 --no-first-run --no-service-autorun --disable-sync --disable-feature
s=msImplicitSignin --disable-popup-blocking http://localhost:58342/
```

### Operating System

Windows 10

### Selenium version

4.4.3

### What are the browser(s) and version(s) where you see this issue?

MS Edge 104.0.1293.63 (Official build) (64-bit) 

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.3.0.0

**Comment by sohrabtowfighi** [comment]
Hi @diemol 
The task is not related to MSEdgeDriver. 
The task is related to the IEDriverServer. 
The relevant code is found in selenium/cpp/iedriver/BrowserFactory.cpp

**Comment by diemol** [comment]
They are now being kind enough to help us maintain the IEDriver. That is why.

**Comment by titusfortner** [comment]
It makes sense that it defaults to a temp directory so that it behaves like other drivers. I agree that there should be a way to specify this. A PR to add that feature would be appreciated.

**Comment by sohrabtowfighi** [comment]
> It makes sense that it defaults to a temp directory so that it behaves like other drivers. I agree that there should be a way to specify this. A PR to add that feature would be appreciated.


Please say this here:

https://github.com/MicrosoftEdge/EdgeWebDriver/issues/29

**Comment by titusfortner** [comment]
Microsoft already knows what they are doing there. I was mostly responding to:

> It does not make sense to me why we need to hard code the user-data-dir

**Comment by sohrabtowfighi** [comment]
As described above, Microsoft agreed to maintain the IE driver. The issue I
linked is the specific problem you are mentioning. Please state in the Ms
Edge driver issue that I linked that you are looking for a fix for the IE
driver. Thanks.

**Comment by sohrabtowfighi** [comment]
FYI, I figured out a workaround. This was posted [here](https://github.com/MicrosoftEdge/EdgeWebDriver/issues/29).

> I was able to get around this issue with some edits to the browser factory code. I have provided some of the surrounding code so that you can ctrl-f to the relevant section.
> 
> ```
> // These flags force Edge into a mode where it will only run MSHTML
> executable_and_url.append(L" --ie-mode-force");
> executable_and_url.append(L" --internet-explorer-integration=iemode");
> 
> // THIS IS NEW
> // create a temporary directory for IEDriver test if --user-data-dir is not already
> // supplied
> std::wstring temp_dir;
> if (StringUtilities::ToString(browser_command_line_switches_).find("--user-data-dir") == std::string::npos) {
>   if (CreateUniqueTempDir(temp_dir)) {
>     LOG(TRACE) << L"Using temporary folder " << LOGWSTRING(temp_dir) << ".";
>     executable_and_url.append(L" --user-data-dir=" + temp_dir);
>     this->edge_user_data_dir_ = temp_dir;
>   }
> }
> 
> executable_and_url.append(L" --no-first-run");
> executable_and_url.append(L" --no-service-autorun");
> executable_and_url.append(L" --disable-sync");
> executable_and_url.append(L" --disable-features=msImplicitSignin");
> executable_and_url.append(L" --disable-popup-blocking");
> 
> // THIS IS NEW
> if (this->browser_command_line_switches_.size() != 0) {
>   executable_and_url.append(L" ");
>   executable_and_url.append(this->browser_command_line_switches_);
> }
> 
> executable_and_url.append(L" ");
> executable_and_url.append(this->initial_browser_url_);
> 
> LOG(TRACE) << "IE starting command line is: '"
>            << LOGWSTRING(executable_and_url) << "'.";
> ```

> I also make sure that when adding arguments in python, I put the variables in double quotes.
> 
> ```
> ieOptions.add_argument('--user-data-dir="'+msedge_user_profile + '"')
> ieOptions.add_argument('--profile-directory="Default"')
> ```
