### ISSUE TITLE
[🐛 Bug]: chrome init error

### ISSUE THREAD

**Issue by 276091990** [SeleniumHQ/selenium#10966]
### What happened?

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse args
from invalid argument: each argument must be a string
Build info: version: '4.4.0', revision: 'e5c75ed026a'

### How can we reproduce the issue?

```shell
no
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse args
from invalid argument: each argument must be a string
Build info: version: '4.4.0', revision: 'e5c75ed026a'
```

### Operating System

win10

### Selenium version

java 4.4.0

### What are the browser(s) and version(s) where you see this issue?

chrome 103.0.5060.53

### What are the browser driver(s) and version(s) where you see this issue?

chrome 103.0.5060.134

**Comment by diemol** [comment]
Closing as no more information was provided.
