### ISSUE TITLE
[🐛 Bug]: element.find_element() ignores given parent element

### ISSUE THREAD

**Issue by kirode** [SeleniumHQ/selenium#10972]
### What happened?

1) I use driver.find_elements() to find list of elements
2) Then I use specific element and try to find his child

As you can see in the screenshot - element is AJAX Data topic.
but when I use element.find_element() - it returns the 1st topics that match given locator, ignores the parent one (Dynamic ID)
![image](https://user-images.githubusercontent.com/16559528/186203603-7f0c6a52-607f-44e8-91b4-7c104e745588.png)
![image](https://user-images.githubusercontent.com/16559528/186203939-ec820c30-3250-4552-a33b-8407c9b9651c.png)

selenium version is 4.4.3
python 3.10
site I use to debug this one - http://uitestingplayground.com/
but you can reproduce it with any site where a list of parent elements got the same child elements

### How can we reproduce the issue?

```shell
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver import Chrome

driver = Chrome(ChromeDriverManager().install())
driver.get('http://uitestingplayground.com/')
div_loc = '//div[@class="col-sm"]'
link_loc = '//h3//a'
p_loc = '//p'

elems = driver.find_elements(By.XPATH, div_loc)
el6 = elems[6]
print(el6.text)
print(elems[6].find_element(By.XPATH, link_loc).text)
driver.close()
```

### Relevant log output

```shell
E:\work_projects\selenium_bug\sel_src.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome(ChromeDriverManager().install())
AJAX Data
Some elements may appear on a page after loading data with AJAX request
Dynamic ID

Process finished with exit code 0
```

### Operating System

win 11

### Selenium version

python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 104.0.5112.101

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDirver 104.0.5112.79

**Comment by titusfortner** [comment]
So, `//` is to reference from the root node, so it doesn't make sense to use it to select elements below a context node. Maybe Chromedriver should convert `//` to `./` by default when the search context is provided as an element, but that's a bug for chromedriver.

In your case, just switch to `./` instead of `//` and everything should work as you expect.
