### ISSUE TITLE
[🚀 Feature]: Support for older geckodriver versions

### ISSUE THREAD

**Issue by dryu99** [SeleniumHQ/selenium#10978]
### Feature and motivation

I think it would be helpful if the latest version of Selenium was able to support older geckodriver versions. I'm currently using Selenium Grid 4.4 and geckodriver versions < 3.1 don't work since Selenium 4.4 relies on the `--allow-origins` argument which is only available on version 3.1:

```
/opt/geckodriver-0.30.0: error: Found argument '--allow-origins' which wasn't expected, or isn't valid in this context
```

I've been following this [thread](https://github.com/mozilla/geckodriver/issues/1959) in the geckodriver repo where other users have reported experiencing similar issues. If there aren't plans to support this anytime soon does anyone know any alternatives to work with older versions of geckodriver without downgrading Selenium?

### Usage example

Running automated tests on different versions of Firefox/geckodriver to make sure my website isn't breaking for users who may be using older Firefox versions.

**Comment by titusfortner** [comment]
Back when driver code used to be maintained by the Selenium project, only one version of a driver was supported (the one bundled in the release), and we had a policy of supporting the previous two "Extended Release" browser versions with that driver. Now that the driver code is decoupled from the Selenium code and maintained by the browser vendor directly, you have the ability to do more things. Selenium's policy is still that it will support the latest driver version, and it is up to Mozilla to decide how many browser versions back can be supported by the most recent driver. In this case, the latest driver supports the previous 2 extended release versions, so this is not different from what we've always done.

I think we'd consider PRs that found a maintainable way to provide support for older drivers, but our primary focus is to make sure that the latest features work with the current driver.
