### ISSUE TITLE
[🚀 Feature]: Support go language

### ISSUE THREAD

**Issue by refaeli-io** [SeleniumHQ/selenium#10983]
### Feature and motivation

Support go SDK library client to use selenium webdriver with go

### Usage example

I want for example to develop an automation infrastructure and on that develop an e2e tests

**Comment by titusfortner** [comment]
Thank you for the suggestion. There is an implementation of Go that can be found here — https://github.com/tebeka/selenium

We would consider adding additional implementations to the official project, but only if the developers were willing to work with us to integrate it into our build system and ensure that the functionality matches that of the other languages, as well as being committed to maintaining the code. None of that is simple, and wouldn't be done as a result of an open ticket, so I'm going to close this one.
