### ISSUE TITLE
Selenium web driver launches a Firefox browser only if I close out previously opened 'FF' browsers.

### ISSUE THREAD

**Issue by rajpradeep32** [SeleniumHQ/selenium#1098]
Selenium web driver launches a new 'Firefox' browser only if I close out previously opened 'FF' browsers which is of  a different java class related with selenium web driver.
Am facing this issue all of a sudden earlier it was working fine.

Jars used : selenium-2.47.1

**Comment by sri85** [comment]
Can you post the code snippet that is causing this problem?

**Comment by lukeis** [comment]
Please provide a reproducible test case and list relevant browser and OS versions. Closing for now, can reopen when a test case is provided
