### ISSUE TITLE
[🐛 Bug]: XPATH div[10+] cannot retrieve text.

### ISSUE THREAD

**Issue by tallmega** [SeleniumHQ/selenium#10996]
### What happened?

When retrieving absolute and relative XPATH nodes, a div greater than 9 will return an empty text value.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

options = Options()
options.headless = True
options.add_argument("--window-size=1920,1200")

driver = webdriver.Chrome(options=options, service=Service(ChromeDriverManager().install()))
driver.get("https://www.cntower.ca/lighting-schedule/")
colour9 = driver.find_element(by=By.XPATH, value='//*[@id="block-de-theme-content"]/div/article/div/div/div/div[1]/div/div/div/div/div/div[9]/article/div[1]/div[2]')
colour10 = driver.find_element(by=By.XPATH, value='//*[@id="block-de-theme-content"]/div/article/div/div/div/div[1]/div/div/div/div/div/div[10]/article/div[1]/div[2]')

print(colour9.text) #returns a string
print(colour10.text) #returns an empty string
driver.quit()
```

### Relevant log output

```shell
N/A
```

### Operating System

Ubuntu / Multiple

### Selenium version

Python 3.9.6

### What are the browser(s) and version(s) where you see this issue?

Chromium 93.0.4577.82

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 93.0.4577.82

### Are you using Selenium Grid?

No

**Comment by symonk** [comment]
Will take a look, it's likely an issue with `headless` and the window size etc, as an xpath like that is very brittle and may not be returning what you think but will try it out shortly.

if you drop `options.add_argument("--window-size=1920,1200")` - what happens?

**Comment by tallmega** [comment]
Thanks!

Brittle I agree, but I have it running a loop.  The first nine values from two xpaths return properly, but not 10+.
________________________________

**Comment by symonk** [comment]
very interesting! let's take a look

**Comment by symonk** [comment]
@tallmega it looks to me like the tiles are not properly rendered  / visible here until _scrolling_ occurs on that particular URL so I'm not sure it's a particular xpath & div index of `>9`, the elements are found but their _visible text_ is likely empty?  https://w3c.github.io/webdriver/#get-element-text.  Whether thats:

 - A problem on this specific site
 - Working as intended inline with the spec
 - A straight up bug

I am not so sure ;), need to do a bit of digging.

For example if you scroll to the bottom of the page, then query *all* the texts, likely prints out correctly.

-----

Naive example to prove out the theory:

```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


with webdriver.Chrome(service=Service(ChromeDriverManager().install())) as driver:
    driver.get("https://www.cntower.ca/lighting-schedule/")
    elements = driver.find_elements("xpath", "//span[@class='field field--name-title field--type-string field--label-hidden']")
    for element in elements:
        driver.execute_script("arguments[0].scrollIntoView();", element)
        print(element.text)
```

**Comment by tallmega** [comment]
Amazing!  I will test this out!  Sincere apologies for reporting a not-bug, and appreciate the knowledge transfer!

**Comment by titusfortner** [comment]
I think there's just something in your absolute XPath tripping you up.

Loop over this (or tweak for whatever you're actually trying to capture):

```
driver.find_elements(by=By.CSS, value='div.row article h2')
```

Feel free to reach us at https://www.selenium.dev/support/#ChatRoom
