### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by vitaliyshepel** [SeleniumHQ/selenium#10999]
### What happened?

Hello, guys. Thanks for a new selenium-webdriver publication.
I am currently trying to integrate this package into **Quasar framework**(vue.js) directly for some data automation.
But after install it, getting module not found error.
Please take a look at this screenshot.
![image](https://user-images.githubusercontent.com/108946949/188217615-818616d8-496d-428a-a962-863874d93c62.png)

- my current node.js version is v14.17.6.

- By the way, it's working on node.js project created from scratch but not for Quasar framework. (frontend)
Looking for your kind guidance and help!
Thanks, Vitaliy

### How can we reproduce the issue?

```shell
Create a new Quasar framework and setup selenium webdriver and import it inside the script.
```

### Relevant log output

```shell
ERROR  Failed to compile with 1 errors                                                                       2:28:35 PM
 error  in ./node_modules/selenium-webdriver/lib/virtual_authenticator.js

Module parse failed: Unexpected token (26:18)
File was processed with these loaders:
 * ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
| class VirtualAuthenticatorOptions {
|
>   static Protocol = {
|     "CTAP2": 'ctap2',
|     "U2F": 'ctap1/u2f',

 @ ./node_modules/selenium-webdriver/lib/webdriver.js 40:19-53
 @ ./node_modules/selenium-webdriver/index.js
 @ ./logic/utils/automation.js
 @ ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/components/shared/QnaForm.vue?vue&type=script&lang=js&
 @ ./src/components/shared/QnaForm.vue?vue&type=script&lang=js&
 @ ./src/components/shared/QnaForm.vue
 @ ./node_modules/@quasar/app/lib/webpack/loader.transform-quasar-imports.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/@quasar/app/lib/webpack/loader.auto-import-client.js?kebab!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Menu-Items/AutomateQnA.vue?vue&type=script&lang=js&
 @ ./src/components/Menu-Items/AutomateQnA.vue?vue&type=script&lang=js&
 @ ./src/components/Menu-Items/AutomateQnA.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 (webpack)/hot/dev-server.js ./.quasar/client-entry.js
```

### Operating System

Windows 10

### Selenium version

Javascript, nodejs

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromeDriver 104.0.0

### Are you using Selenium Grid?

4.3.0

**Comment by vitaliyshepel** [comment]
@diemol 
Is selenium webdriver npm package not allow to use with frontend javascript framework?

**Comment by titusfortner** [comment]
Selenium is a browser automation tool that can be used to interact with webpages regardless of what framework they are created with.

**Comment by vitaliyshepel** [comment]
Okay, but I am not sure why I am getting this kind of error if I import it inside the frontend framework like this.

`const { By, Key, Builder, until } = require( 'selenium-webdriver');
require('chromedriver');

function automationQnA(str) {
  console.log(str)
  let driver = new Builder().forBrowser("chrome").build()
          try {
                driver.navigate().to(`${url}`)
                const state = driver.wait(until.urlIs(`${url}/todo`));
                if (state) {
                  let textarea = driver.findElement(By.xpath("/html/body/table/tbody/tr[4]/td/table[4]/tbody/tr[3]/td[1]/textarea"))
                  console.log(textarea, typeof(textarea))
                  textarea.sendKeys("test")
                }
          }

          finally {
            driver.quit();
          }
          return;
}

module.exports = {
  automationQnA
}`
