### ISSUE TITLE
[🐛 Bug]: Selenium.Support.UI.ExpectedConditions class not found

### ISSUE THREAD

**Issue by naeemakram** [SeleniumHQ/selenium#11006]
### What happened?

The Selenium support classes are not being found by Visual Studio. I have tried to update to the latest version of VS, but still no luck.

### How can we reproduce the issue?

```shell
Create a new project with .Net Core 6 and NUnit. Added packages Selenium.Support, Selenium.WebDriver, WebDriverManager.
Create a new test script and add the following namespaces:
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager;
using WebDriverManager.Helpers;

Create an instance of WebDriver at class level.
Anywhere in the default generate test method try typing ExpectedConditions.
The method will not be displayed by the VS.

Copying the method call from the docs also doesn't help.
IWebElement element = wait.Until(ExpectedConditions.ElementExists(By.Id("foo")));
```

### Relevant log output

```shell
None available.
```

### Operating System

Windows 11

### Selenium version

Dotnet 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

WebDriverManager

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Yes, it was deprecated for quite a while, then removed in e3680a379f113b830275968c9e28ad8bbf3dc699

Please use anonymous functions / lambdas to create your own expected conditions.

**Comment by naeemakram** [comment]
The documentation needs to an update. I got the docs repo set up on my machine. I will make the change as soon as I get some time.

**Comment by titusfortner** [comment]
That would be appreciated, thank you!
