### ISSUE TITLE
Promise returned by *get* never resolved in Firefox Aurora and Firefox Nightly

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#1100]
```
var webdriver = require('selenium-webdriver'),
    By = require('selenium-webdriver').By,
    until = require('selenium-webdriver').until;

var firefox = require('selenium-webdriver/firefox');
var binary = new firefox.Binary('/path/to/firefox-bin');
var options = new firefox.Options().setBinary(binary);
var driver = new firefox.Driver(options);

driver.get('http://www.google.com/ncr').then(function() {
  console.log("Loading completed!");
})
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```

The `Loading completed!` message isn't logged if you run with Firefox Aurora or Firefox Nightly.

**Comment by jleyba** [comment]
Only Firefox versions ESR, ESR-1, N, and N-1 are supported by Selenium.

**Comment by marco-c** [comment]
Is 'N' the release version?

I've managed to temporarily circumvent the problem with some very bad code:
```
driver.executeScript(function() {
  window.location = 'url';
});
driver.sleep(5000);
```
I imagine most commands won't work after something like this, but the ones I strictly need are working.

**Comment by lukeis** [comment]
yes, N is the release channel. If you'd like to run Aurora / Nightly I suggest you use marionette instead:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by marco-c** [comment]
> yes, N is the release channel. If you'd like to run Aurora / Nightly I suggest you use marionette instead:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

Thank you!
