### ISSUE TITLE
[🐛 Bug]: Chrome Version 105 Supported

### ISSUE THREAD

**Issue by OGExclusives** [SeleniumHQ/selenium#11018]
### What happened?

I assume chrome have updated their browser and now your web driver does not work. 

the error states the driver only supports version 103, we are now on 105. 

### How can we reproduce the issue?

```shell
Install latest version of chrome and run
```

### Relevant log output

```shell
.
```

### Operating System

Windows 11

### Selenium version

Latest

### What are the browser(s) and version(s) where you see this issue?

Latest

### What are the browser driver(s) and version(s) where you see this issue?

Latest

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
You need to keep the driver updated — http://selenium.dev/documentation/webdriver/getting_started/install_drivers/
