### ISSUE TITLE
[🐛 Bug]: Select constructor always throws UnsupportedOperationException exeption

### ISSUE THREAD

**Issue by MarinaLazurko** [SeleniumHQ/selenium#11022]
### What happened?

I need to use Select class in my framework
I create object. of class Select using it's own constructor
But this constructor always throws UnsupportedOperationException because it uses method getDomAttribute which is:

public Select(WebElement element) {
    String tagName = element.getTagName();

    if (null == tagName || !"select".equals(tagName.toLowerCase())) {
      throw new UnexpectedTagNameException("select", tagName);
    }

    this.element = element;

    String value = element.**getDomAttribute**("multiple");

    // The atoms normalize the returned value, but check for "false"
    isMulti = (value != null && !"false".equals(value));
  }

default String getDomAttribute(String name) {
    throw new UnsupportedOperationException("getDomAttribute");
  }

### How can we reproduce the issue?

```shell
Select select = new Select(driver.findElement(By.cssselector("your select webelement selector"));
It calls constructor:
public Select(WebElement element) {
    String tagName = element.getTagName();

    if (null == tagName || !"select".equals(tagName.toLowerCase())) {
      throw new UnexpectedTagNameException("select", tagName);
    }

    this.element = element;

    String value = element.getDomAttribute("multiple");

    // The atoms normalize the returned value, but check for "false"
    isMulti = (value != null && !"false".equals(value));
  }


Constructor uses method String value = element.getDomAttribute("multiple") which does't have implementation and just throws exception.
```

### Relevant log output

```shell
java.lang.UnsupportedOperationException: getDomAttribute
```

### Operating System

macOS

### Selenium version

4.4.0, java

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

Version 105.0.5195.102 

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
You have a dependency conflict the with version of the Support jar. Make sure all Selenium versions are using the latest version. Here's some info to help investigate the issue: https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html
