### ISSUE TITLE
[🐛 Bug]: Python free_port() function has potential for race conditions

### ISSUE THREAD

**Issue by Padge91** [SeleniumHQ/selenium#11027]
### What happened?

I'm running several workers concurrently on a single machine. These workers are consumers in a producer-consumer pattern, and primarily run these selenium processes. When multiple jobs are submitted to the queue simultaneously (usually while queue is empty), I see several processes fail with the error code `Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1`. This error is inconsistent, and only appears to happen when several workers start processing in tandem.

After doing some research and testing, I believe this is due to the `free_port()` function at `https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/utils.py`. The function creates a socket which binds to an available port provided by the OS, and then passes that port to the `Service` to pass along to the driver. I believe the problem comes in when the function reads the port from the open socket, and then closes the socket which releases the port.

It's possible for a process to bind to the previously acquired port before this port is properly passed to the driver, leading to the driver crashing, and the error function we see above. This also makes sense as to why it's inconsistent.

It's pretty complicated to reproduce but I have a script which (so far) appears to make it happen once out of every 300 attempts (default of 10 attempts per execution). I'm also using seleniumwire, but this doesn't appear to make a difference in my testing. A lower level script can probably reproduce the output easier.

### How can we reproduce the issue?

```shell
from seleniumwire import webdriver as seleniumwire_webdriver
from multiprocessing import Process

def run():
	try:
		binary_path = '/usr/bin/chromium-browser'
		driver_path = "/usr/bin/chromedriver"

		options = seleniumwire_webdriver.ChromeOptions()  # define options
		options.headless = True
		options.add_argument("--start-maximized")
		options.add_argument("--headless")
		options.binary_location = binary_path # location of the Chrome Browser binary

		seleniumwire_options = {
			"connection_keep_alive": True
		}

		with seleniumwire_webdriver.Chrome(driver_path, seleniumwire_options=seleniumwire_options, chrome_options=options) as driver:
			driver.get("https://www.google.com")

	except Exception as e:
		print("error: "+str(e))

if __name__ == "__main__":
	threads = []
	for i in range(0, 10):
		p = Process(target=run)
		p.start()
		threads.append(p)

	for p in threads:
		p.join()
```

### Relevant log output

```shell
Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1
```

### Operating System

Ubuntu 22.04.1 LTS

### Selenium version

Python 3.8.5, 3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chromium 105.0.5195.102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 105.0.5195.102

**Comment by Padge91** [comment]
After thinking about this more, I don't think there's a realistic change Selenium could make to avoid the issue. It appears the OS is returning ports which have been recently released (something I thought wasn't common).

The only solution/workaround which comes to my mind is randomly selecting a port number in my application code from a range of ports I can dedicate to the chromedriver processes. It's not great, but selecting from a range of **n** ports should have a low probability of collisions, and I can also add in my own logic to retry **m** times with a new port if it's already allocated. Since these processes are short-lived, this should only rarely add a small overhead.

Open to other suggestions.

**Comment by AutomatedTester** [comment]
There is some work that could be done but it's not trivial. My team discussed this eons ago https://bugzilla.mozilla.org/show_bug.cgi?id=1240830 but it wasn't simple to do.

**Comment by Padge91** [comment]
Thanks for the reference. I certainly appreciate the complexity it introduces, and it seems like a reasonable solution. 

I'll pursue my random ports approach for the time being. Thank you for the response!
