### ISSUE TITLE
[🐛 Bug]: cygwin environment issue

### ISSUE THREAD

**Issue by mora-01** [SeleniumHQ/selenium#11026]
### What happened?

on cygwin environment, I encounted the following issue when executing watir program :

selenium-webdriver-4.4.0/lib/selenium/webdriver/common/platform.rb:127:in `tr': no implicit conversion of nil into String (TypeError)

The isssue is resolved by modifing platform.rb file

before modification :
  @os ||= case host_os
        when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
          :windows
        when /darwin|mac os/
          :macosx
        when /linux/
after modification :
  @os ||= case host_os
        when /mswin|msys|mingw|bccwin|wince|emc/
          :windows
        when /darwin|mac os/
          :macosx
        when /linux|cygwin/

### How can we reproduce the issue?

```shell
require "watir"
Watir::Browser.new
```

### Relevant log output

```shell
error : platform.rb:127:in `tr': no implicit conversion of nil into String (TypeError)
```

### Operating System

windows 10/11

### Selenium version

ruby

### What are the browser(s) and version(s) where you see this issue?

firefox, chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 105.0.5195.52

**Comment by titusfortner** [comment]
Yes, this was a weird bug introduced by successive rubocop updates; fixed with #10973 will be available in the next release.
