### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by ronaldpetty** [SeleniumHQ/selenium#1102]
Hello,

This might be the wrong place for this but not sure where else to put it.  On the NPM website for selenium-webdriver (https://www.npmjs.com/package/selenium-webdriver), it mentions an 'example' directory.  From the website page:

Usage
The sample below and others are included in the example directory. You may also find the tests for selenium-webdriver informative.

I am unable to find 'example' directory anywhere (not in the repo or on the site.)

Can someone add clarity to that?

Regards.

Ron

**Comment by lukeis** [comment]
https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example

Although I believe it's included in the npm bundle that gets installed.

**Comment by jleyba** [comment]
It is included with the npm package.

**Comment by ronaldpetty** [comment]
Confirmed, its in the npm module.  My vote would be to include in the repo, for that is where I always look first (read things before installing things.)  Thanks for pointing me to the current place.
