### ISSUE TITLE
[🐛 Bug]: Selenium Keys not working on Mac Chrome

### ISSUE THREAD

**Issue by hello297** [SeleniumHQ/selenium#11023]
### What happened?

I have some test cases that navigate dropdown boxes using Keys.ARROW_DOWN and Keys.ENTER.
Previously they were working fine on my windows machine but since I switched to MAC, they no longer work.

The output from shows like this, 
`Sent  to desiredDeliveryTimeDropDown
 Sent  to desiredDeliveryTimeDropDown`
The  being different characters for each input.

### How can we reproduce the issue?

```shell
Do .sendKeys() to a select element with input as Keys.ARROW_DOWN, Keys.DOWN, or Keys.ENTER.
Nothing happens.
```

### Relevant log output

```shell
No errors in logs
```

### Operating System

macOS Monterey

### Selenium version

Java 3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 105.0.5195.102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 104.0.5112.79

**Comment by titusfortner** [comment]
Selenium is sending the commands to chromedriver and the driver translates the behaviors for the browser. If it is working on Windows, but not on Mac, it means that Selenium is sending the correct commands, but that the driver is behaving differently between platforms. Try executing with Firefox and see if it works as expected.

**Comment by hello297** [comment]
@titusfortner 
Thanks for the reply.
Unfortunately the code base was written around chrome so I won't be able to test it on firefox (at least within a timely manner)

**Comment by hello297** [comment]
I've found a work around by using the Select class for now.
Thank you.
