### ISSUE TITLE
[🐛 Bug]: webElement.sendKeys carriage return to a textarea

### ISSUE THREAD

**Issue by guoruizo** [SeleniumHQ/selenium#11020]
### What happened?

I am using selenium to type multi-line text to <textarea> in html. When the text contains carriage return character (\r or U+000D), I found selenium didn't type it in the text area (attached my reproduction code). The newline character (\n or U+000A) is typed.

According to <textarea> w3c standard, <textarea> normalizes newline remaining \r.
https://html.spec.whatwg.org/#the-textarea-element:normalize-newlines
https://infra.spec.whatwg.org/#normalize-newlines
quote "To normalize newlines in a [string], replace every U+000D CR U+000A LF [code point] pair with a single U+000A LF [code point] and then replace every remaining U+000D CR [code point]."

When I use selenium to sendKeys a text with both \r\n and \r (e.g. "line 1\r\nline 2\rline 3"), I only see \n was typed but \r is ignored. Because if \r is also type, I would see <textarea> normalize \r\n -> \n and \r -> \n.

Without using selenium, I can prove the \r can be typed to <textarea> and is normalized to \n. This is my jsbin demo code:
https://jsbin.com/xapisezini/edit?html,js,console,output

### How can we reproduce the issue?

```shell
/* reproduce selenium sendKey test */
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.concurrent.TimeUnit;
public class MyTest {
    private WebDriver driver;
    @Before
    public void setup() {
        System.setProperty("webdriver.chrome.driver","chromedriver");
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Test
    public void testTextArea() throws InterruptedException {
        driver.get(<localhost URL to hello.html>);
        WebElement ta = driver.findElement(By.id("w3review"));
        ta.sendKeys("line 1\r\nline 2\rline 3");
    }

    @After
    public void teardown() {
        driver.quit();
    }
}

/* hello.html */
<!DOCTYPE html>
<html>
<body>
<h1>The textarea element</h1>
  <p><label>Reproduce sendKeys:</label></p>
  <textarea id="w3review"></textarea>
</body>
</html>
```

### Relevant log output

```shell
After selenium sendKeys to <textarea>, the observed textarea is
line 1
line 2line 3

I am expecting desired textarea
line 1
line 2
line 3
```

### Operating System

Debian 10

### Selenium version

Java <groupId>org.seleniumhq.selenium</groupId><artifactId>selenium-support</artifactId><version>2.31.0</version>

### What are the browser(s) and version(s) where you see this issue?

Chrome 99

### What are the browser driver(s) and version(s) where you see this issue?

<groupId>org.seleniumhq.selenium</groupId><artifactId>selenium-chrome-driver</artifactId><version>4.4.0</version>

**Comment by titusfortner** [comment]
Selenium is sending the string to the driver the way you provide it. If the behavior in the browser is not what is intended, it is likely a chromedriver bug. When filing a bug there, it is often helpful to compare it to the behavior of Firefox.

**Comment by guoruizo** [comment]
> Selenium is sending the string to the driver the way you provide it. If the behavior in the browser is not what is intended, it is likely a chromedriver bug. When filing a bug there, it is often helpful to compare it to the behavior of Firefox.

@titusfortner I like to make sure instead of 'likely', how do you peel off Selenium code and prove this is ChromeDriver? Where I can find ChromeDriver call is made in Selenium and create a different reproduction step for driver?

**Comment by titusfortner** [comment]
I said "likely" because perhaps it isn't considered a bug by Google. 

Start with seeing what Firefox does with the same code.  You can curl commands to the driver (https://w3c.github.io/webdriver/#element-send-keys), but probably easiest to go through Selenium interface.

**Comment by guoruizo** [comment]
> I said "likely" because perhaps it isn't considered a bug by Google.
> 
> Start with seeing what Firefox does with the same code. You can curl commands to the driver (https://w3c.github.io/webdriver/#element-send-keys), but probably easiest to go through Selenium interface.

@titusfortner Firefox looks working fine and does sendkey \r over to the textarea. I created a bug-report at 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4210

The issue hasn't been triaged by ChromeDriver team. I am new to issues reported on ChromeDriver, do you know how engaging that community is to at least triage it? Scanning some other posts there, I am not very optimistic.

**Comment by titusfortner** [comment]
The best way to get one of the browser vendors to look at something is to write a web platform test and show that it is passing in one browser and not another... Not sure where it fits in here, but if you can PR something here it should get looked at: https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/element_send_keys

If you get it figured out, tag me in the PR or link to it here so I see it.
