### ISSUE TITLE
[🚀 Feature]:  Extend the ChromeDriver support to latest Chrome version possible. 

### ISSUE THREAD

**Issue by patil-milind** [SeleniumHQ/selenium#11033]
### Feature and motivation

Some time back in one of the Chromium version 92.** found the security vulnerability and it was fixed in the later version.
And the current ChromDriver version in selenium is not supporting the latest Chromium version(Supporting up to 96 version only). Please extend the Support to latest Chromium version.   

### Usage example

Automation can be done on the latest chromium version available.

**Comment by titusfortner** [comment]
Selenium does not bundle the chromedriver, you have to update it yourself
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
