### ISSUE TITLE
[🐛 Bug]:  Unable to find an exact match for CDP version 105, so returning the closest version found: 104

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [SeleniumHQ/selenium#11042]
### What happened?

**Selenium version:** 4.4.0

**Actual result:**  Unable to find an exact match for CDP version 105, so returning the closest version found: 104

![error](https://user-images.githubusercontent.com/86394952/190994563-eb78f498-14aa-4206-bea5-291c9cdfe0a5.png)

### How can we reproduce the issue?

```shell
WebDriver driver = new ChromeDriver();
openBrowser(driver,"http://192.168.15.237/bagisto-demo/public/");
String[] cartProducts = {"Men's Polo T-shirt","Sunglasses"}; // products for add to cart.
addToCart(driver,cartProducts); // add-Product-to-cart

public static void addToCart(WebDriver driver, String[] cartProducts) {
int j=0;
List<WebElement> products = driver.findElements(By.cssSelector("div.card-body")); 
for (int i=1;i<products.size();i++) {
List itemForAddToCart = Arrays.asList(cartProducts); 
if (itemForAddToCart.contains(products)) {
	j++;
driver.findElement(By.xpath("//button[@class='btn btn-add-to-cart.small-padding']")).click();
}
if(j == cartProducts.length) {
		break;
}			
}		
}
```

### Relevant log output

```shell
Sep 19, 2022 3:20:04 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Sep 19, 2022 3:20:05 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Sep 19, 2022 3:20:05 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
```

### Operating System

ubunt 64bit

### Selenium version

java: 18.0.2.1, selenium: 4.4.0

### What are the browser(s) and version(s) where you see this issue?

ChromeDriver, v.105.0.5195.125

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver, v.105.0.5195.125

### Are you using Selenium Grid?

no

**Comment by Sanjaybhattwebkul** [comment]
My pom.xml file is this.
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>bagissto</groupId>
  <artifactId>core</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>core</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

 <dependencies>
    
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>4.4.0</version>
    </dependency>
    
</dependencies>

</project>

**Comment by symonk** [comment]
we need to ship `4.5.0`.  should be coming soon with `105` devtools

**Comment by titusfortner** [comment]
It's in trunk, as soon as there is a release this will be available. Everything should still work with 104, this is just a warning.
