### ISSUE TITLE
[🐛 Bug]: The TAB page switch in Internet Explorer does not take effect, and no error is reported

### ISSUE THREAD

**Issue by Suoweiwuu** [SeleniumHQ/selenium#11041]
### What happened?

The TAB page switch in Internet Explorer does not take effect, and no error is reported.
this is my code:

`        public void TestMethod1()
        {
            InternetExplorerDriverService service = InternetExplorerDriverService.CreateDefaultService(@"F:\IEDriverServer_Win32_4.3.0");
            service.LogFile = "./iedriver.log";
            service.LoggingLevel = InternetExplorerDriverLogLevel.Trace;
            WebDriver webDriver = new InternetExplorerDriver(service);

            webDriver.Navigate().GoToUrl("http://bing.com");
            var firstHandler = webDriver.CurrentWindowHandle;
            webDriver.SwitchTo().NewWindow(WindowType.Tab);
            webDriver.Navigate().GoToUrl("http://www.bing.com");
            webDriver.SwitchTo().Window(firstHandler); // Does not go to the initial window handle.
            webDriver.SwitchTo().Window(firstHandler);
            var newWindowHandle = webDriver.CurrentWindowHandle;
            foreach (string window in webDriver.WindowHandles)
            {
                if (newWindowHandle != window)
                {
                    webDriver.SwitchTo().Window(window);
                    break;
                }
            }
            Thread.Sleep(5000);
            webDriver.Quit();
        }
[iedriver.log](https://github.com/SeleniumHQ/selenium/files/9594247/iedriver.log)
`

### How can we reproduce the issue?

```shell
As above
```

### Relevant log output

```shell
The log file is attached
```

### Operating System

win 10

### Selenium version

Selenium4.4

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriver 4.3

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
The logs show the right thing happening:

1. You get the current handle `eec8e13c`
2. You create and switch to a new tab `f4b18db0`
3. You navigate to bing
4. You switch back to the first tab `eec8e13c`
5. You get the list of windows that includes both of the above handles
6. You call to switch to the first tab again `eec8e13c`
7. You get the current handle `eec8e13c`
8. You get the list of windows that includes both of the above handles
9. You call to switch to the second tab `f4b18db0`
10. You end the session.

This is the code that you actually ran, not what you reported:
```
        var firstHandler = webDriver.CurrentWindowHandle; // 1
        webDriver.SwitchTo().NewWindow(WindowType.Tab); // 2
        webDriver.Navigate().GoToUrl("http://www.bing.com"); // 3
        webDriver.SwitchTo().Window(firstHandler); // 4

       // webDriver.SwitchTo().Window(firstHandler) --> this never happened, the next line did
        var handles = webDriver.WindowHandles(); // 5

        webDriver.SwitchTo().Window(firstHandler); // 6
        var newWindowHandle = webDriver.CurrentWindowHandle; // 7 (this is the first window because you switched back to it)
        foreach (string window in webDriver.WindowHandles) // 8
        {
            if (newWindowHandle != window)
            {
                webDriver.SwitchTo().Window(window); // 9 (switches to second window because you check against the first window)
                break;
            }
        }
    }

**Comment by CococoloSimida** [comment]
I'm really sorry for some problems with the code I uploaded. I update it to explain my problems more clearly
`
         
            webDriver.Navigate().GoToUrl("http://bing.com");
            var firstHandler = webDriver.CurrentWindowHandle;
            webDriver.SwitchTo().NewWindow(WindowType.Tab);
            webDriver.Navigate().GoToUrl("http://bing.com");
            webDriver.SwitchTo().Window(firstHandler); //switch window
            var secondHandler = webDriver.CurrentWindowHandle;
            //The firstHandler should be different from the secondHandler, but it's not.
            Trace.Write($"firstHandler: {firstHandler}, secondHandler: {secondHandler}");

![1](https://user-images.githubusercontent.com/37428412/190938841-16d9f90c-e9f0-4c0d-83b0-166703d6640e.png)

[iedriver.log](https://github.com/SeleniumHQ/selenium/files/9595758/iedriver.log)

`
Another question is how Selenium implements the switching action, which I don't see in the source code.

![2](https://user-images.githubusercontent.com/37428412/190942566-01589d51-1184-4d8b-8101-e4e83860239c.png)

I really hope you can answer my confusion, Thanks!

**Comment by titusfortner** [comment]
You're switching back to the first window, then assigning `secondHandler` to the same handle as `firstHandler`

```
        webDriver.SwitchTo().Window(firstHandler); //switch window
        var secondHandler = webDriver.CurrentWindowHandle;
```
