### ISSUE TITLE
[🚀 Feature]: while launching URL in chrome screen going blank and can see only popup with username passwd fields. How to handle/inspect/remove it in WebdriverIO 

### ISSUE THREAD

**Issue by Md-Ayub** [SeleniumHQ/selenium#11043]
### Feature and motivation

while launching URL in chrome, screen going blank and can see only popup with username passwd fields. How to handle/inspect/remove it by using WebdriverIO/typescript.

### Usage example

To handle popup

**Comment by titusfortner** [comment]
You need to ask the WebdriverIO community - https://webdriver.io/community/support
