### ISSUE TITLE
[🐛 Bug]: geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by sumitsg004** [SeleniumHQ/selenium#11052]
### What happened?

I migrated from Selenium 3.141.59 to 4.2.2 version.

Facing an issue while launching browser specific to firefox. 

Error message - 
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context
Error injecting constructor, org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start
-up failure.

Selenium version - 4.2.2
Firefox version - 81
Gecko driver version - tried with 0.29.0.  (also tried geckodriver versions with 0.27.0, 0.28.0, 0.30.0, and 0.31.0 )

Is there any restriction on which firefox version should be used? 
Didnt face this issue when using Selenium version 3.141.59. 

Any help on this issue would be really helpful

### How can we reproduce the issue?

```shell
Cannot share project repo, will see if I can create sample github project to replicate the issue
```

### Relevant log output

```shell
Error injecting constructor, org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start
-up failure.

error: Found argument '--websocket-port' which wasn't expected, or
 isn't valid in this context
```

### Operating System

Windows 10

### Selenium version

Selenium-java 4.2.2

### What are the browser(s) and version(s) where you see this issue?

Firefox version 81

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver version - 0.29.0, 0.27.0, 0.28.0, 0.30.0, 0.31.0 - tested all versions

**Comment by pujagani** [comment]
Thank you for the details. Geckodriver version >= 0.30.0 is required. Firefox version >= 85 is required.

**Comment by sumitsg004** [comment]
Thanks @pujagani for quick response. Is there a mapping between Firefox and Geckodriver version? 

I upgraded firefox to latest version(105)
Geckodriver version - 0.30.0

Getting similar error - 
error: Found argument '--allow-origins' which wasn't expected, or 
isn't valid in this context

USAGE:
    geckodriver.exe --port <PORT> --websocket-port <PORT>
    
   Note - When I use 0.31.0 - I don't see this issue, but with 0.30.0 issue persists. Is there any mapping between firefox and geckdriver versions? 

Thanks

**Comment by pujagani** [comment]
You make a fair point. There is no document I am aware of that provides this mapping. I will make a note of this and see if we can add this info to Selenium docs for future reference.

**Comment by titusfortner** [comment]
Yes, there is — https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
and you're right, we should link to it in our docs.

**Comment by sumitsg004** [comment]
thanks @pujagani and @titusfortner
