### ISSUE TITLE
[🐛 Bug]: Missing documentation of service arg to __init__() of Firefox

### ISSUE THREAD

**Issue by stevecj** [SeleniumHQ/selenium#11067]
### What happened?

In selenium/py/selenium/webdriver/firefox/webdriver.py, the docstring for `WebDriver#__init__()` is missing documentation for the `service` argument.

### How can we reproduce the issue?

```shell
n/a
```

### Relevant log output

```shell
n/a
```

### Operating System

n/a

### Selenium version

Trunk as of Sep 29, 2022

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

**Comment by symonk** [comment]
Thanks @stevecj
