### ISSUE TITLE
[🚀 Feature]: Selenium python to function on linux

### ISSUE THREAD

**Issue by ShivamAmratlalPatel** [SeleniumHQ/selenium#11063]
### Feature and motivation

I'm using selenium python to automate web tasks but I want to run it on my server. However my server runs Linux and the package does not work with Linux. My script functions perfectly on Windows. 

### Usage example

I think a lot of people would want to add their automation scripts to servers, most of which run Linux so this would massively help the commmunity.

**Comment by symonk** [comment]
@ShivamAmratlalPatel what exactly doesn't run? What are you trying? Which flavour of Linux? Please reopen this when there is some sort of context / recreatable example

**Comment by titusfortner** [comment]
All of our Python tests are executed on Linux and work just fine: https://github.com/SeleniumHQ/selenium/actions/workflows/ci-python.yml?query=branch%3Atrunk
