### ISSUE TITLE
Selenium Remote Webdriver ignoring timeout and browserTimeout arguments

### ISSUE THREAD

**Issue by MetaMemoryT** [SeleniumHQ/selenium#1106]
After 30mins browser is closed no matter what command line parameters are used: I have tried various combinations of:

```
java -jar "selenium\build\java\server\src\org\openqa\grid\selenium\selenium-standalone.jar" -timeout=999999 -browserTimeout=999999 -Dwebdriver.server.s ession.timeout=999999 -Dwebdriver.server.browser.timeout=999999
```

```
java -jar "selenium\build\java\server\src\org\openqa\grid\selenium\selenium-standalone.jar" -timeout=-1 -browserTimeout=-1 -Dwebdriver.server.session.timeout=-1 -Dwebdriver.server.browser.timeout=-1
```

```
java -jar "selenium-server-standalone-2.47.1.jar" -timeout=999999999 -browserTimeout=999999 -Dwebdriver.server.session.timeout=0
```

```
java -jar "C:\nodejs\node_modules\selenium-server-standalone-jar\jar\selenium-server-standalone-2.47.1.jar" -timeout=999999999 -browserTimeout=9999999 -Dwebdriver.server.session.timeout=9999999
```

It logs a message like:
```
09:41:01.915 INFO - Session 3c366b28-a7a4-4f97-805f-2e5fe7b97b21 deleted due to client timeout
```

Related discussion and issues:
https://groups.google.com/forum/?utm_medium=email&amp;utm_source=footer#!msg/selenium-users/XFYh36Ua2Mg/TBCioWkLm7oJ

https://code.google.com/p/selenium/issues/detail?id=3224

This is reporting the failure of the hub to update nodes:
https://github.com/SeleniumHQ/selenium/issues/374

Platform: 64-bit Windows 8.1

if you need any more debug info just ask.

**Comment by MetaMemoryT** [comment]
Trying to investigate:

https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/remote/server/SessionCleaner.java#L89

**Comment by lukeis** [comment]
java property flags must be specified BEFORE the "-jar" command line option...

java -DpropertyName=value -jar selenium-server....

**Comment by emiglobetrotting** [comment]
seems problem has been solved, specifying the java property flags as provided by lukels  solved the problem

**Comment by rameshnss** [comment]
@lukeis @emiglobetrotting Please let me know the complete command to start the hub with DpropertyName syntax

**Comment by emiglobetrotting** [comment]
@rameshnss  this is how you can start the hub with timeout option, for example setting timeout to 86400 seconds

     java -Dwebdriver.server.session.timeout=86400 -jar selenium-server-standalone-2.48.2.jar

**Comment by rameshnss** [comment]
@emiglobetrotting  86400 is in milli seconds right?

**Comment by emiglobetrotting** [comment]
no, time is in seconds ( 3600s * 24 hours in a day = 86400 seconds )
