### ISSUE TITLE
[🚀 Feature]: Kill subprocesses when Python process is terminated abnormally

### ISSUE THREAD

**Issue by stevecj** [SeleniumHQ/selenium#11076]
### Feature and motivation

Currently, when a Python process is using selenium via the Python API, if the main Python process is terminated abnormally, the Selenium subprocess remain running.

It is possible to have a subprocess receive a signal when Python is terminated (either normally or abnormally) by opening the subprocess with a pipe to its stdin. Either one of the existing subprocesses or a new dedicated subprocess could use this mechanism to clean up.

### Usage example

n/a

**Comment by titusfortner** [comment]
Would you be interested in creating a pull request demonstrating this? Thanks.

**Comment by symonk** [comment]
what do you have in mind exactly @stevecj ? python by default won't do any finalizers on `SIGTERM` or `SIGKILL` (without registering bespoke handlers via the `signal` module) IIRC.  Cross platform presents other problems in itself possibly, would be keen to see an example of what you have in mind here

Thanks

**Comment by stevecj** [comment]
@titusfortner  I haven't looked at Selenium source code much yet, but I can take a look, and see if I can make a PR.

@symonk The strategy I have used in other similar situations is to start a subprocess for the specific purpose of cleaning up subprocesses if necessary. The new subprocess is created with a stdin pipe, and then it waits for input on that. No input will ever come, so it blocks until the pipe is closed, and then it gets an exception. When that happens, it knows to run cleanup on the pids it was told about via command arguments when it was started.

**Comment by stevecj** [comment]
Update: I have been swamped with other stuff. I still intend to look into making a PR for this soon.

**Comment by stevecj** [comment]
…or not so soon, but I still intend to get around to this.

**Comment by titusfortner** [comment]
PR still would be welcome, but this isn't a priority for us to track.
