### ISSUE TITLE
[🐛 Bug]: Default NettyClient configuration results to frequent 407 proxy authentication failures

### ISSUE THREAD

**Issue by ldiary** [SeleniumHQ/selenium#11072]
### What happened?

When connecting to BrowserStack via our company proxy, successful connection happens by chance, with a failure rate of 90%. Even if it managed to get a successful connection, though, after just few minutes the connection gets terminated with 407 Proxy Authentication error.

The only way I was able to solve this issue, is by replacing [this part of NettyClient](https://github.com/SeleniumHQ/selenium/blob/3167e93110f70937ddec6bfbfce87ccef03c4f30/java/src/org/openqa/selenium/remote/http/netty/NettyClient.java#L77) with a replacement code below: 

```java
Realm.Builder companyRealm = new Realm.Builder(
    System.getProperty("http.proxyUser"),
    System.getProperty("http.proxyPassword"));

companyRealm.setUsePreemptiveAuth(true)
    .setScheme(Realm.AuthScheme.BASIC)
    .setRealmName("COMPANY_AD");

ProxyServer.Builder companyProxy = new ProxyServer.Builder(
    System.getProperty("http.proxyHost"),
    Integer.parseInt(System.getProperty("http.proxyPort")));

companyProxy.setRealm(companyRealm.build());

DefaultAsyncHttpClientConfig.Builder clientConfig = new DefaultAsyncHttpClientConfig.Builder()
    .setThreadFactory(new DefaultThreadFactory("AsyncHttpClient", true))
    .setUseInsecureTrustManager(true)
    .setAggregateWebSocketFrameFragments(true)
    .setWebSocketMaxBufferSize(Integer.MAX_VALUE)
    .setWebSocketMaxFrameSize(Integer.MAX_VALUE)
    .setNettyTimer(TIMER)
    .setRequestTimeout(toClampedInt(config.readTimeout().toMillis()))
    .setConnectTimeout(toClampedInt(config.connectionTimeout().toMillis()))
    .setReadTimeout(toClampedInt(config.readTimeout().toMillis()))
    .setFollowRedirect(true)
    .setMaxRequestRetry(0)
    .setProxyServer(companyProxy.build());
return Dsl.asyncHttpClient(clientConfig.build());
```

There was a similar [code there before](https://github.com/SeleniumHQ/selenium/commit/abfbc4dbb4d9cb9a29b34e068b4d861b8089b276) which was then moved[ into NettyMessages](https://github.com/SeleniumHQ/selenium/blob/3167e93110f70937ddec6bfbfce87ccef03c4f30/java/src/org/openqa/selenium/remote/http/netty/NettyMessages.java#L82). Our proxy connection is successful even without this realm and proxy setting in the NettyMessages, as long as there is realm and proxy setting in the NettyClient.

Can you please consider putting back the realm and proxy setting when instantiating an AsyncHttpClient in NettyClient? Or if it is already possible using a different method, please let me know. 

### How can we reproduce the issue?

This code which is similar approach to [an example given here](https://github.com/SeleniumHQ/selenium/issues/10231#issuecomment-1036013964) is the one that suffers from frequent 407 proxy authentication issues:

```java
HttpCommandExecutor executor = new HttpCommandExecutor(
        MobileCommand.commandRepository,
        ClientConfig.defaultConfig()
                .baseUrl(browserstackUrl)
                .authenticateAs(new UsernameAndPassword(System.getProperty("http.proxyUser"),System.getProperty("http.proxyPassword")))
                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(System.getProperty("http.proxyHost"), Integer.parseInt(System.getProperty("http.proxyPort"))))),
        new NettyClient.Factory()
);
```

The only way I can successfully connect to our proxy is through the code below in combination with the modified version of NettyClient I mentioned above.

```java
HttpCommandExecutor executor = new HttpCommandExecutor(
        MobileCommand.commandRepository,
        browserstackUrl, 
        new ModifiedNettyClient.Factory()
);
```

When creating a modified NettyClient, though, I also have to create my own copy of NettyWebSocket, NettyMessages, and NettyDomainSocketClient. Therefore, it would be nice if we are able, by default, to configure the Netty (AsyncHttpClient) to contain these realm and proxy settings.

### Relevant log output

Below is part of the log output when using the default NettyClient configuration; the connection was successfully started but then after few minutes it gets terminated due to 407 error - `Can't handle 407 as auth was already performed`
```shell
09:20:55.689 [Forwarding findElement on session 3442b80d09dbaf30a02161f714793309beb009cf to remote] DEBUG o.a.netty.request.NettyRequestSender *** Using pooled Channel '[id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80]' for 'POST' to 'https://bsUser:bsAccessKey@hub-cloud.browserstack.com/wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element'
09:20:55.689 [Forwarding findElement on session 3442b80d09dbaf30a02161f714793309beb009cf to remote] DEBUG o.a.netty.request.NettyRequestSender *** Using open Channel [id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80] for POST '/wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element'
09:20:55.814 [AsyncHttpClient-1-3] DEBUG o.a.netty.handler.HttpHandler ***

Request DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element HTTP/1.1
User-Agent: selenium/4.4.0 (java mac)
Content-Length: 50
Content-Type: application/json; charset=utf-8
host: hub-cloud.browserstack.com
authorization: Basic Xxxxxxx
accept: */*

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 26 Sep 2022 08:20:55 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Source-From: 02
x-powered-by: Express
vary: X-HTTP-Method-Override
etag: W/"c7-+"
content-length: 456

09:20:55.815 [AsyncHttpClient-1-3] DEBUG o.a.netty.channel.ChannelManager *** Adding key: CompositePartitionKey(targetHostBaseUrl=https://hub-cloud.browserstack.com:443, virtualHost=null, proxyHost=proxy.company, proxyPort=80, proxyType=HTTP for channel [id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80]
09:20:55.815 [Forwarding isElementDisplayed on session 3442b80d09dbaf30a02161f714793309beb009cf to remote] DEBUG o.a.netty.request.NettyRequestSender *** Using pooled Channel '[id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80]' for 'GET' to 'https://bsUser:bsAccessKey@hub-cloud.browserstack.com/wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element/00000000-0000-0a2b-ffff-ffff00000294/displayed'
09:20:55.815 [Forwarding isElementDisplayed on session 3442b80d09dbaf30a02161f714793309beb009cf to remote] DEBUG o.a.netty.request.NettyRequestSender *** Using open Channel [id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80] for GET '/wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element/00000000-0000-0a2b-ffff-ffff00000294/displayed'
09:20:55.912 [AsyncHttpClient-1-3] DEBUG o.a.netty.handler.HttpHandler ***

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /wd/hub/session/3442b80d09dbaf30a02161f714793309beb009cf/element/00000000-0000-0a2b-ffff-ffff00000294/displayed HTTP/1.1
User-Agent: selenium/4.4.0 (java mac)
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
host: hub-cloud.browserstack.com
authorization: Basic Xxxxxxx
accept: */*

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 26 Sep 2022 08:20:55 GMT
Content-Type: application/json; charset=utf-8
Connection: close
Source-From: 02
x-powered-by: Express
etag: W/"4c-"
content-length: 80

09:20:55.913 [AsyncHttpClient-1-3] DEBUG o.a.netty.channel.ChannelManager *** Closing Channel [id: 0xd1a269d4, L:/10.196.135.127:55596 - R:proxy.company/128.11.227.250:80]
09:20:55.913 [AsyncHttpClient-1-3] DEBUG o.a.netty.handler.HttpHandler *** Channel Closed: [id: 0xd1a269d4, L:/10.196.135.127:55596 ! R:proxy.company/128.11.227.250:80] with attribute DISCARD
09:20:55.949 [AsyncHttpClient-1-4] DEBUG o.a.n.channel.NettyConnectListener *** Using new Channel '[id: 0xec6ab2bc, L:/10.196.135.127:55608 - R:proxy.company/128.11.227.250:80]' for 'CONNECT' to 'hub-cloud.browserstack.com:443'
09:20:56.194 [AsyncHttpClient-1-4] DEBUG o.a.netty.handler.HttpHandler ***

Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
CONNECT hub-cloud.browserstack.com:443 HTTP/1.1
user-agent: selenium/4.4.0 (java mac)
host: hub-cloud.browserstack.com
authorization: Basic Xxxxxxx
proxy-authorization: Basic Xxxxxxx
accept: */*

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NEGOTIATE
Proxy-Authenticate: NTLM
Proxy-Authenticate: BASIC realm="COMPANY_AD"
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
content-length: 1122

09:20:56.195 [AsyncHttpClient-1-4] INFO  o.a.n.h.i.ProxyUnauthorized407Interceptor *** Can't handle 407 as auth was already performed
09:20:56.195 [AsyncHttpClient-1-4] DEBUG o.a.netty.channel.ChannelManager *** Closing Channel [id: 0xec6ab2bc, L:/10.196.135.127:55608 - R:proxy.company/128.11.227.250:80]
09:20:56.196 [AsyncHttpClient-1-4] DEBUG o.a.netty.handler.HttpHandler *** Channel Closed: [id: 0xec6ab2bc, L:/10.196.135.127:55608 ! R:proxy.company/128.11.227.250:80] with attribute DISCARD
```

From here on, no matter how many times it tries to re-connect, AsyncHttpClient will always throw the 407 error - `Can't handle 407 as auth was already performed`

### Operating System

macOS Monterey

### Selenium version

selenium-java 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Appium

### What are the browser driver(s) and version(s) where you see this issue?

Appium 8.2.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
What version of Java are you using. You might try the new Java 11 http client support - https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by ldiary** [comment]
> What version of Java are you using. You might try the new Java 11 http client support - https://www.selenium.dev/blog/2022/using-java11-httpclient/

I am using Java 11... but I can't use java 11 httpclient, as it is now, as well because it has its own bug:
https://github.com/SeleniumHQ/selenium/issues/11068#issuecomment-1264741929

**Comment by pujagani** [comment]
Thank you for sharing the details. I was trying to reproduce the error to understand why this is happening. I ran the code snippet below and was unable to reproduce it (courtesy to Diego for sharing the code snippet in a related issue) : 

```
public static void main(String[] args) throws MalformedURLException, InterruptedException {
      for (int i=0; i <=100; i++) {
          ChromeOptions browserOptions = new ChromeOptions();
          // Proxy started with https://github.com/diemol/squid-with-basic-auth
          Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 3128));
          ClientConfig config = ClientConfig.defaultConfig()
            .baseUrl(new URL("http://192.168.29.178:4444"))
            .authenticateAs(new UsernameAndPassword("docker-proxy", "selenium"))
            .proxy(proxy);
          WebDriver driver = RemoteWebDriver.builder()
            .oneOf(browserOptions)
            .config(config)
            .build();
          driver.get("https://selenium.dev");
          driver.quit();
      }
  }
```
I am now thinking it could be potentially related to using the HttpCommandExecutor. But I will need to try and reproduce the error. Do you have any observations on your end based on your test runs so far? Thanks!

**Comment by ldiary** [comment]
@pujagani There are two issues, one is the low rate of successful connection and the other is the abrupt termination after a successful connection. The later is easy to reproduce;  you will need to simulate a Proxy server that challenge the HTTP client to re-authenticate, probably after few minutes (if not few seconds) after a successful authentication is already made.  When the Proxy server sends the following response to the client, 
```
Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NEGOTIATE
Proxy-Authenticate: NTLM
Proxy-Authenticate: BASIC realm="COMPANY_AD"
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
content-length: 1122
```
the client declines to re-authenticate and closes the connection instead. 
The first issue might be hard to reproduce but I think it can be reproduced if the Proxy sends another authentication challenge just right after the client has attempted once.

**Comment by pujagani** [comment]
Thank you for sharing the insights. Since reproducing the issue does not seem trivial and our long-term goal is to move to Java 11 (I understand there is a bug that needs solving), I am afraid that giving this issue a priority without a reproducible test script/project is feasible. 
To ensure that AsyncHttpClient and Selenium are doing the right thing. I have stepped through the code and it seems like it should not matter if the proxy and realm are set in the request or when creating the HTTP client. At every step, it checks for the proxy in the request first and if that is not present, it checks if the proxy is available in the config that is created when the AsyncHttpClient instance is created. Ideally, the same values are used later to create a NettyResponseFuture.
Unless there is a bug similar to https://github.com/AsyncHttpClient/async-http-client/issues/1094 that exists but is difficult to confirm without reproducing the error.

**Comment by ldiary** [comment]
@pujagani yes, I'm fine with that. Let me close this bug since a workaround is already provided as well for those who might face same issues with their proxy.
