### ISSUE TITLE
[🐛 Bug]: Type difference of returned typed array in chrome and firefox

### ISSUE THREAD

**Issue by eyaler** [SeleniumHQ/selenium#11070]
### What happened?

I am using `driver.execute_script('return my_uint8array')` to get the value of a Uint8Array variable. On chrome I get a list and on firefox i get a dict.

### How can we reproduce the issue?

```shell
<script>
my_uint8array = new Uint8Array([1, 2, 3])
</script>
```

```
ret = driver.execute_script('return my_uint8array')
print(type(ret))
```
```


### Relevant log output

```shell
for chrome/msedge:
`<class 'list'>`

for firefox:
`<class 'dict'>`
```

### Operating System

windows 11

### Selenium version

python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

chrome 106, firefox 105

### What are the browser driver(s) and version(s) where you see this issue?

chrome 106, gecko 0.31.0

**Comment by eyaler** [comment]
note: the python dict has keys which are strings and sorted in lexicographical order, so the get back the list you need to do:
`[v for k, v in sorted(ret.items(), key=lambda x: int(x[0]))]`

**Comment by titusfortner** [comment]
Different browsers are providing different responses to executing the same code that Selenium is properly sending. Determine which browser is doing the incorrect thing and raise a bug with that browser.
