### ISSUE TITLE
[🚀 Feature]: Make it possible to prevent the spammy logging

### ISSUE THREAD

**Issue by Artur-** [SeleniumHQ/selenium#11088]
### Feature and motivation

When you have a lot of tests in a project, a major part of the build log contains these rows
```
Oct 05, 2022 2:29:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected upstream dialect: W3C
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104
Oct 05, 2022 2:29:03 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 105 of 104
```

The rows do not help me as a user in any way and are making it super hard to read the build log. They are probably useful in the case that something is wrong and I need to debug it but not in 99% of the builds.

There should be some way to get rid of these messages. To me it seems like
- `Detected upstream dialect: W3C` - this is clearly a debug message and could be debug level
- `WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104` - this can be important to know if something fails, maybe it can be logged once and not every time?
- `INFO: Found CDP implementation for version 105 of 104` - I don't know what this means "105 of 104" and it feels like this is debug info also. The problematic case when there is a mismatch is covered by the previous one

There is probably a cumbersome way to implement log filtering to get rid of these but that sounds unreasonable to do separately in every project.

### Usage example

-

**Comment by pujagani** [comment]
Thank you for the details. I have updated the logs and their levels to reduce the noise. 

"`WARNING: Unable to find an exact match for CDP version 105, so returning the closest version found: 104 - this can be important to know if something fails, maybe it can be logged once and not every time?`"  is likely to be logged for each new session created i.e. when a new WebDriver instance is created.

**Comment by pujagani** [comment]
The changes will be available as part of the next release.
