### ISSUE TITLE
sendKeys sends numbers one digit at a time in firefox

### ISSUE THREAD

**Issue by snowymike** [SeleniumHQ/selenium#1108]
this issue is similar to https://code.google.com/p/selenium/issues/detail?id=7809 and http://stackoverflow.com/questions/23412912/selenium-send-keys-doesnt-work-if-input-type-number which have been issues with firefox and numeric inputs in the past.

with firefox 41 and selenium 2.47.1, calling WebElement.sendKeys("123") will just send the first digit.  to successfully send all digits I have to call sendKeys in a loop for each digit.

to reproduce, you need an <input type="number">.  no issue with other input types.  IE and Chrome web driver's work fine with input type of number.

**Comment by snowymike** [comment]
html was interpreted in prior post.  to reproduce, you need an html input with a type set equal to number.

**Comment by doberkofler** [comment]
+1

**Comment by barancev** [comment]
Both legacy Firefox driver and new Firefox driver (geckodriver) support number input field.

Proved by this sample of code, Selenium Java 3.5.3, Firefox ESR 52 (legacy driver) and Firefox 55 (geckodriver):
```
driver.get("https://jsbin.com/qulivib");
driver.findElement(By.id("numField")).sendKeys("12345");
assertEquals(driver.findElement(By.id("numField")).getAttribute("value"), "12345");
```

**Comment by snowymike** [comment]
confirmed in selenium 3.5.3 and firefox 47.0.1 (legacy driver).
