### ISSUE TITLE
[🐛 Bug]: `RemoteWebDriver.GetDevToolsSession` throws `OpenQA.Selenium.WebDriverException: A WebSocket address for DevTools protocol has been detected, but the protocol version cannot be automatically detected. You must specify a protocol version.` when chrome is 106

### ISSUE THREAD

**Issue by arnonax-tr** [SeleniumHQ/selenium#11089]
### What happened?

* Run latest version (4.5.0) of Selenium Grid, with Chrome 106.
* Create a dotnet project referencing WebDriver 4.5.0
* After creating the remote driver call:
```
var devtools = driver.GetDevToolsSession(106);
```
## Actual result:
```
OpenQA.Selenium.WebDriverException: A WebSocket address for DevTools protocol has been detected, but the protocol version cannot be automatically detected. You must specify a protocol version.
```
## Expected Result:
No exception occurs and a DevTools session is created

## Root cause:
[This commit](https://github.com/SeleniumHQ/selenium/commit/3170a497f8c6ecd3247fb5fb7662828723ad8f42) changed  `DevToolsSession.AutoDetectDevToolsProtocolVersion` from `0` to `106`.

### How can we reproduce the issue?

```shell
See above.
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

DotNet 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

105.0.5195.52

### Are you using Selenium Grid?

4.5.0

**Comment by diemol** [comment]
@arnonax-tr does it work with Selenium 4.4.0?

@titusfortner should this have been changed?
https://github.com/SeleniumHQ/selenium/commit/3170a497f8c6ecd3247fb5fb7662828723ad8f42#diff-0beb90c52c9357d5c8b3d1b68279e46971b026839cb7122bb29c6022776bff56L39

**Comment by titusfortner** [comment]
Nope. that was a temp change when I was trying to get tests to work before I upgraded chrome version, and I didn't change it back. I'll fix.

**Comment by titusfortner** [comment]
4.5.1 has been released. Thanks for reporting.
