### ISSUE TITLE
[🐛 Bug]: No way to accept SSL certificate in HEADLESS mode

### ISSUE THREAD

**Issue by oluwasegunolu** [SeleniumHQ/selenium#11081]
### What happened?

HI,
I'm trying to run tests in headless Chrome Before entering the page, I have to select the client certificate for authentication. How to do this in headless mode?

I am currently facing an issue with running feature tests using an end-to-end  environment in headless mode
Its works fine in normal chrome mode. but fail when you switch to the headless mode it fails with access denied.

### How can we reproduce the issue?

```shell
NA
```

### Relevant log output

```shell
` Seamless app did not load within the specified timeout (RuntimeError)
  ./features/support/hooks.rb:72:in `rescue in block in <top (required)>'
  ./features/support/hooks.rb
:66:in `Before'`


**Screenshot attached below:**
![chromeA_valid_movies_entitlement_user_navigates_through_the_app_and_plays_out_the_movies_VOD_content](https://user-images.githubusercontent.com/67695189/193785652-da63adf2-2b12-4057-a911-e256c48e702d.png)
```

### Operating System

macOS

### Selenium version

Ruby 3.*

### What are the browser(s) and version(s) where you see this issue?

Chrome 102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 102

**Comment by titusfortner** [comment]
Headless chrome is not a "real" browser. It takes shortcuts to allow it to run in headless, and not all features will work. You can raise an issue with Google on their chromium tracker for additional support in their headless browser.

**Comment by oluwasegunolu** [comment]
Thanks, @titusfortner for your quick response. I will follow your suggestion..

**Comment by titusfortner** [comment]
@oluwasegunolu also you can use `--headless=chrome` which might work for your needs. It's the full browser, just headless.
