### ISSUE TITLE
Running selenium webdriver test in safari private mode

### ISSUE THREAD

**Issue by neetissingh** [SeleniumHQ/selenium#1109]
We have requirement to run our selenium webdriver test in safari private mode.
I don't see any option how to run it.

**Comment by sri85** [comment]
This looks like a suitable question to be asked stackoverflow.com

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
