### ISSUE TITLE
[🐛 Bug]: SSL exceptions not raised anymore

### ISSUE THREAD

**Issue by mghiglieri** [SeleniumHQ/selenium#11098]
### What happened?

In former versions of selenium for Python exceptions were raised if a SSL error (certificate invalid, untrusted root, etc.) occured. Now, no exception is raised. Anybody knows a reason for that behavior ?

Thanks
Marco

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

options = webdriver.ChromeOptions()
options.add_argument("no-sandbox")
options.add_argument("headless")
options.add_argument("start-maximized")

s = Service('/usr/local/bin/chromedriver')
driver = webdriver.Chrome(service=s, options=options)


driver.get("https://untrusted-root.badssl.com/")
print(driver.title)
```

### Relevant log output

```shell
no output
```

### Operating System

Ubuntu 20LTS

### Selenium version

selenium==4.5.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 106.0.5249.103 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61

### Are you using Selenium Grid?

not used

**Comment by symonk** [comment]
which versions in particular @mghiglieri ?

**Comment by mghiglieri** [comment]
@symonk Thanks for asking. Just checked all versions down to 3.9. No exceptions at all.

Chromedriver issue or Chrome?

**Comment by diemol** [comment]
If you changed the Selenium Python versions and the behavior was the same, it is most likely to be a ChromeDriver/Chrome issue.
