### ISSUE TITLE
[🐛 Bug]: webdriver.Chrome() will make the codes below it are unreachable

### ISSUE THREAD

**Issue by aa3507943** [SeleniumHQ/selenium#11091]
### What happened?

if use webdriver.Chrome() function, it will make the codes below it are unreachable

### How can we reproduce the issue?

```shell
from selenium import webdriver

webdriver.Chrome()
a = 1
print(a)
```

### Relevant log output

```shell
Code is unreachablePylance
```

### Operating System

Windows 10

### Selenium version

selenium 3.141.0 with python 3.9

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 106.0.5249.103

**Comment by titusfortner** [comment]
Please upgrade to latest version of Selenium - https://github.com/microsoft/pylance-release/issues/2869
