### ISSUE TITLE
[🐛 Bug]: ActionChains.scroll_to_element InvalidArgumentException: Message: unknown variant wheel

### ISSUE THREAD

**Issue by dominiclondon** [SeleniumHQ/selenium#11090]
### What happened?

When calling `ActionChains(driver).scroll_to_element(elem).perform()`, it fails with:
```
InvalidArgumentException: Message: unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 226`
```

I notice that https://github.com/SeleniumHQ/selenium/blob/dcdff48f36ace73100e0d521e307583975f3a0c0/py/selenium/webdriver/common/actions/interaction.py#L23 is missing `WHEEL`, but I tried patching that locally and it still fails.

### How can we reproduce the issue?

```shell
ActionChains(driver).scroll_to_element(elem).perform()
```

### Relevant log output

```shell
1665085965359   webdriver::server       DEBUG   -> POST /session/7de8b18e-527e-49e9-bba2-f7e64b613e95/actions {"actions": [{"type": "pointer", "parameters": {"pointerType": "mouse"}, "id": "mouse", "actions": [{"type": "pointerMove", "duration": 250, "x": 0, "y": 0, "origin": {"element-6066-11e4-a52e-4f735466cecf": "cbe05c9d-cbfa-4c22-8dfc-0338c3c199d6"}}]}, {"type": "key", "id": "key", "actions": [{"type": "pause", "duration": 0}]}, {"type": "wheel", "id": "wheel", "actions": [{"type": "scroll", "x": 0, "y": 0, "deltaX": 0, "deltaY": 0, "duration": 0, "origin": {"element-6066-11e4-a52e-4f735466cecf": "cbe05c9d-cbfa-4c22-8dfc-0338c3c199d6"}}]}]}
1665085965359   webdriver::server       DEBUG   <- 400 Bad Request {"value":{"error":"invalid argument","message":"unknown variant `wheel`, expected one of `none`, `key`, `pointer` at line 1 column 541","stacktrace":""}}
```

### Operating System

macOS, Windows 10

### Selenium version

Python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.103, Firefox 105.0.1 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61, geckodriver 0.31.0

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
This code works fine in Chrome (all of the code on [this page](https://www.selenium.dev/documentation/webdriver/actions_api/wheel/)is regularly [run and passing](https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/3201027884/jobs/5228590812#step:7:112))

The error you're getting is because this is not supported yet in Firefox (I can't remember if it is expected in v106 or v107, but it is coming)

`SOURCE_TYPES` isn't actually used anywhere any longer, so it doesn't need to be added there.

**Comment by dominiclondon** [comment]
@titusfortner Thanks for taking a look, the irony is this is only needed on Firefox because it doesn't implement `move_to_element` in the same way as other browsers.

**Comment by titusfortner** [comment]
@dominiclondon — fwiw, Firefox is doing `move_to_element` "correctly" and Chrome is doing it wrong, not that it matters to getting your code to work. :)
