### ISSUE TITLE
[🐛 Bug]: We should be able to get the selected option even when the element is disabled

### ISSUE THREAD

**Issue by yazad** [SeleniumHQ/selenium#11092]
### What happened?

[[dotnot] change default behavior for Select class with disabled elements](https://github.com/SeleniumHQ/selenium/commit/fa85effa0e77d946a3f4dcc94a9d0b6b407c2749)
The above commit has changed the default behavior of the SelectElement
It now checks if the element is enabled/disabled in the constructor and throws an exception if its disabled.
We should be able to get the selected option even when the element is disabled.

`var value = new SelectElement(webElement).SelectedOption.Text;`
Now throws an exception if the element is disabled

### How can we reproduce the issue?

```shell
// webElement is disabled, below should still work
var value = new SelectElement(webElement).SelectedOption.Text;
```

### Relevant log output

```shell
Exception: Select element is disabled and may not be used.
```

### Operating System

Windows 10

### Selenium version

C# 4.5

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.6100

### Are you using Selenium Grid?

4.5

**Comment by titusfortner** [comment]
The `SelectElement` class is designed to be an easier way to select options in a drop down. It is in the `Support` package which is intended to provide examples of higher level functionality and optional opinionated behavior.

The code you are looking for to get information about an element in the DOM is:
```
var value = webElement.FindElement(By.CssSelector("option[selected=selected]").Text;
```

You are also welcome to make your own class based on the `SelectElement` - https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/support/UI/SelectElement.cs

**Comment by yazad** [comment]
It is a useful helper (which worked before)

`var value = webElement.FindElement(By.CssSelector("option[selected=selected]").Text;`
This would not work for options loaded dynamically through slots, but SelectedOption.Text works.
I believe it will be good to check if it is enabled or not while Setting a value, but Getters should work regardless it is enabled or not

**Comment by titusfortner** [comment]
See the discussion here - https://github.com/SeleniumHQ/selenium/issues/10812#issuecomment-1272354171
