### ISSUE TITLE
[🐛 Bug]: Unrecognised option moz:debuggerAddress with default debugger_address: true

### ISSUE THREAD

**Issue by mkllnk** [SeleniumHQ/selenium#11103]
### What happened?

After upgrading from 4.4.0 to 4.5.0 our specs raise an error:

          Selenium::WebDriver::Error::InvalidArgumentError:
            Unrecognised option moz:debuggerAddress

I noticed 58f5833ba02543487aa8e8441c18cebaecef2495 in the release notes and we can avoid that error by setting `debugger_address: false`.

Our options used to be:
```rb
  options = Selenium::WebDriver::Firefox::Options.new(
    binary: path,
    args:,
  )
```

We use Capybara with Rspec to run tests and on the first `visit` call it would raise the above error. We currently use Firefox 91.10.0esr but I also tried the latest 102.3.0esr which still raised the error.

### How can we reproduce the issue?

```shell
Capybara.register_driver :selenium do |app|
  require 'selenium/webdriver'

  Selenium::WebDriver::Firefox::Profile.new do |profile|
    profile['focusmanager.testmode'] = true
    profile['startup.homepage_welcome_url.additional'] = 'about:blank'
    profile['browser.startup.homepage_override.mstone'] = 'ignore'
  end

  options = Selenium::WebDriver::Firefox::Options.new(
    debugger_address: true
  )

  # Register new driver
  Capybara::Selenium::Driver.new(
    app,
    browser: :firefox,
    capabilities: [options],
  )
end
```

### Relevant log output

```shell
Failures:

  1) Admin Products Daily Stock when managing stock values navigates and saves among weeks and suppliers correctly
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit login_path
          
          Selenium::WebDriver::Error::InvalidArgumentError:
            Unrecognised option moz:debuggerAddress
          # <internal:kernel>:90:in `tap'
```

### Operating System

Debian GNU/Linux 10 (buster)

### Selenium version

Ruby 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 91.10.0esr, Firefox 102.3.0esr

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.28.0

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Yes, you need to update your geckodriver version, the only supported driver for Firefox v91+ is v0.31.0 - https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

**Comment by mkllnk** [comment]
Ooops, sorry to bug you. Turns out we were still using the geckodriver-bin gem instead of webdrivers. Now it works! :+1:
