### ISSUE TITLE
[🐛 Bug]: Bazel fails to run when a different version is installed by brew

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#11106]
### What happened?

I was trying to generate the atom for `Get Text` by using the following bazel command:
```bash
bazel build //javascript/atoms/fragments:get-text
```

But that failed with:
```
ERROR: The project you're trying to build requires Bazel 5.1.1 (specified in /Users/henrik/code/selenium/.bazelversion), but it wasn't found in /opt/homebrew/Cellar/bazel/5.3.0/libexec/bin.
```

Note that I have a newer version of Bazel installed which I assume should also work and that 5.1.1 is more or less the minimum required version?

### How can we reproduce the issue?

```shell
On MacOS install `bazel` via `brew` and then run the above mentioned command to build the atom.
```

### Relevant log output

```shell
ERROR: The project you're trying to build requires Bazel 5.1.1 (specified in /Users/henrik/code/selenium/.bazelversion), but it wasn't found in /opt/homebrew/Cellar/bazel/5.3.0/libexec/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

You can download the required version directly using this command:
  (cd "/opt/homebrew/Cellar/bazel/5.3.0/libexec/bin" && curl -fLO https://releases.bazel.build/5.1.1/release/bazel-5.1.1-darwin-arm64 && chmod +x bazel-5.1.1-darwin-arm64)
```

### Operating System

MacOS 12.6

### Selenium version

Latest trunk

### What are the browser(s) and version(s) where you see this issue?

Firefox 107

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.31.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
We recommend to install `bazelisk`, and with that, the `bazel` binary version gets managed for you.

https://github.com/SeleniumHQ/selenium#requirements

`brew install bazelisk`

**Comment by whimboo** [comment]
Oh, looks like I missed that particular line. Installing `bazelisk` fixed it for me. Thanks!

Should maybe a hint for that be printed when the command fails?

**Comment by diemol** [comment]
The error comes from the `bazel` binary, we cannot change it. :/

**Comment by whimboo** [comment]
Ok so you can probably close this issue.
