### ISSUE TITLE
FindElement(By.XPath()) wraps NoSuchElementException in TargetInvocationException

### ISSUE THREAD

**Issue by vkazar** [SeleniumHQ/selenium#1110]
Hi All!

I'm using C#+NUnit+Selenium 2.47
When I check the presence of the element by FindElement method I expect NoSuchElementException, but sometimes it turns into TargetInvocationException.

> System.Reflection.TargetInvocationException : Адресат вызова создал исключение.
----> OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"xpath","selector":".//span[contains(@data-bind,'UnId')][text()='1']/../span[contains(@data-bind,'WrId')][text()='177']"}
(Session info: chrome=45.0.2454.101)
(Driver info: chromedriver=2.19.346078 (6f1f0cde889532d48ce8242342d0b84f94b114a1),platform=Windows NT 6.3 x86_64)
в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
в System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
в System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
в System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
в OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(ref MessageData msgData, Int32 type)
в OpenQA.Selenium.ISearchContext.FindElement(By by)
в BDPUiTest.Pages.Order.CalculatePage.CheckPersonalExist(WR_WORKERS worker, ref Boolean isOk, ref String errMsg) в CalculatePage.cs: line 142
в BDPUiTest.Pages.Order.CalculatePage.CheckPersonalExist(List'1 workers) в CalculatePage.cs: line 94
в BDPUiTest.Pages.Order.CalculatePage.CheckPersonalExist(WR_WORKERS worker) в CalculatePage.cs: line 108
в BDPUiTest.TestHelpers.OnOrderAddOrRemovePersonalHelper.CheckPersonalExists(Boolean isExpected) в OnOrderAddOrRemovePersonalHelper.cs: line 43
в BDPUiTest.Tests.OnOrderAddOrRemovePersonalToOrderTest.AddPersonalToOrder(Cases Case) в OnOrderAddOrRemovePersonalToOrderTest.cs: line 29
--NoSuchElementException
в OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
в OpenQA.Selenium.Remote.RemoteWebElement.FindElement(String mechanism, String value)
в OpenQA.Selenium.By.FindElement(ISearchContext context)

Why did this happen and how to eliminate it?

**Comment by Photonios** [comment]
This should be closed. The report offers no way to reproduce the issue and it hasn't been looked at for a long time.
