### ISSUE TITLE
[🐛 Bug]: Edge in IE-mode cannot select dropdown from single-select dropdown menu

### ISSUE THREAD

**Issue by m0sseltje** [SeleniumHQ/selenium#11119]
### What happened?

Dear people of the Selenium community,
I’m facing an issue with the Internet Explorer Driver Server and I’m hoping someone knows a way of fixing this or whether this is really an issue with the IE Driver Server and we need to wait for a new version of this driver.

So in short, we had a functioning test automation tool which used an older version of Selenium (3.141.59). A while ago, Internet Explorer was turned off in our work environment, forcing us to switch to Edge. The application we test only works properly in IE or the IE-mode in Edge. Because of this, we upgraded our test automation tool to the newest version of Selenium with the corresponding Internet Explorer Driver Server (at the time 4.3.0.0; but we’ve also tried the newer version (4.5.0.0).  
However, we notice that when using the IE-mode of Edge, dropdown menu options can not be selected (our dropdown menu is single select). 

The error we get, is: Cannot locate option with value [X], not possible to set this dropdown choice. 
Is there any way around this issue so that we can still use Edge in IE-mode? We do not have the option to use another browser, as the application is specifically built to function correcly in IE or Edge's IE-mode (and this will not change in the near future). I'm hoping someone can help, thank you in advance!

### How can we reproduce the issue?

```shell
Unfortunately I cannot share the code as it contains client-sensitive data.
```

### Relevant log output

```shell
Cannot locate option with value [X], not possible to set this dropdown choice.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.3.0

### What are the browser(s) and version(s) where you see this issue?

Edge (version 106.0.1370.42 (64-bit))

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer.exe (version 4.3.0.0 and 4.5.0.0, 32-bit)

**Comment by diemol** [comment]
Closing this as no more information was provided.

**Comment by m0sseltje** [comment]
Unfortunately my colleague who has access to the code, is absent from work at the moment, so I can't post the info required right now (I can't post the client URL anyway, but I can post the code and logging info when I receive it).

**Comment by diemol** [comment]
More importantly, we need a complete way to reproduce the issue, so we can have a look at it.

**Comment by titusfortner** [comment]
Is this Java? Take a look at our documentation - https://www.selenium.dev/documentation/webdriver/support_features/select_lists/#value
and the corresponding example code - https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk//examples/java/src/test/java/dev/selenium/support/SelectListTest.java#L33

Can you get the example code working? If so, figure out what is different between the example html and your html that might cause one to work and the other not to.
