### ISSUE TITLE
[dotnet] Would be better to migrate DriverService to use new HttpClient

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#11111]
### Feature and motivation

Selenium v4 started usage of `HttpClient` for all http requests.

But `DriverService` is skipped by mistake, it's still using old `HttpWebRequest`.

https://github.com/SeleniumHQ/selenium/blob/9e9156072ca1634a227d6b361a7d6d5d61ca917c/dotnet/src/webdriver/DriverService.cs#L223

### Usage example

-

**Comment by nvborisenko** [comment]
Oh, nice issue id: #11111. Seems somebody wants I provide a PR to resolve this issue.

**Comment by titusfortner** [comment]
Yes, please on the PR. I'll take all the .NET help I can get right now. :) Thanks
