### ISSUE TITLE
[🐛 Bug]: keyDown(Key.CONTROL) in actions doesn't work.

### ISSUE THREAD

**Issue by zpiecuch81** [SeleniumHQ/selenium#11127]
### What happened?

When trying to test web app functionality, when element is double clicked with control button pressed event is passed to DOM element, but ctrl is not pressed. I'm using selenium in nodejs. The command I use to do it is as follows:

const actions = driver.actions({async: true});
await actions.keyDown(Key.CONTROL).doubleClick(element2clickOn).keyUp(Key.CONTROL).perform();

In webbrowser logs I can see that the double click event is there, however the ctrlKey member of the event is false. If I put Key.SHIFT or Key.ALT and try it, then I see that corresponding shiftKey or altKey of the event are set to true.
Similar problem is with single click.

### How can we reproduce the issue?

```shell
//test.html file
<html>
<head>
  <script>
    function doubleClick(event){
      console.dir(event);
    }
  </script>
</head>
<body>
  <button id="button" ondblclick="doubleClick(event)" type="button">Click me</button>
</body>
</html>

//selenium test in js file:
const caps = new Capabilities();
caps.setPageLoadStrategy("normal");
const driver = await new Builder().withCapabilities(caps).forBrowser('chrome').build();
await driver.get('test.html');

const button= await driver.findElement(By.css('#button'));
const actions = driver.actions({async: true});
await actions.keyDown(Key.CONTROL).doubleClick(button).keyUp(Key.CONTROL).perform();
await actions.keyDown(Key.CONTROL).click(button).keyUp(Key.CONTROL).perform();
```

### Relevant log output

```shell
MouseEvent
isTrusted: true
altKey: false
bubbles: true
button: 0
buttons: 0
cancelBubble: false
cancelable: true
clientX: 41
clientY: 18
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 2
eventPhase: 0
fromElement: null
layerX: 41
layerY: 18
metaKey: false
movementX: 0
movementY: 0
offsetX: 31
offsetY: 8
pageX: 41
pageY: 18
path: (5) [button#button, body, html, document, Window]
relatedTarget: null
returnValue: true
screenX: 41
screenY: 18
shiftKey: false
sourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}
srcElement: button#button
target: button#button
timeStamp: 165.0999999998603
toElement: button#button
type: "dblclick"
view: Window {window: Window, self: Window, document: document, name: '', location: Location, …}
which: 1
x: 41
y: 18
[[Prototype]]: MouseEvent
```

### Operating System

Windows 10

### Selenium version

JavaScript, nodejs v18.6, npm v8.14, selenium-webdriver v4.1.1

### What are the browser(s) and version(s) where you see this issue?

Edge 106.0.1370.42 (64bit), Chrome 106.0.5249.103 (64bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61, msedgedriver 106.0.1370.42

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Well, the control button is working in our example JS code on Windows in our tests (you can reproduce yourself):

We run this code: 
https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/javascript/test/actionsApi/keysTest.spec.js#L70
in Windows:
https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/3246207422/jobs/5324692364#step:7:46

Are you just going off of what the console is showing or is trying to use it not working for you elsewhere?

**Comment by zpiecuch81** [comment]
Thanks @titusfortner for quick reply.
I did check the test setup you provided link for and turns out that the difference is in the way actions are created. In my tests I add there _{async: true}_ parameter, after removing it, the functionality works as expected.
So my work is unblocked.

Still little interested why ALT and SHIFT worked properly with the _{async: true}_ parameter.

Thanks again,
Zbyszek
