### ISSUE TITLE
[🐛 Bug]: Index of Python documentation is incomplete

### ISSUE THREAD

**Issue by dornech** [SeleniumHQ/selenium#11135]
### What happened?

Please check https://www.selenium.dev/selenium/docs/api/py/genindex.html and you will see ...

### How can we reproduce the issue?

```shell
got o https://www.selenium.dev/selenium/docs/api/py/genindex.html
```

### Relevant log output

```shell
n. a.
```

### Operating System

Win10

### Selenium version

Python

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

106

### Are you using Selenium Grid?

4.5

**Comment by diemol** [comment]
I regenerated the Python API docs and it looks good now, not sure why it was rendered like that before.
