### ISSUE TITLE
[🚀 Feature]: upload file(from network) to remote node

### ISSUE THREAD

**Issue by HrOice** [SeleniumHQ/selenium#11139]
### Feature and motivation

Is there any plan to support upload some network files ([http:// or](http://%20or/) [https:// etc.)](https://%20etc.%29/) to an element of input[@type=file].
I knew LocalFileDetector, and it is a beautiful  tool to upload local file . I can download network file and upload to remote node. but i think it is inefficiency when upload large network files.
I found (com.thoughtworks.selenium.webdriven.commands.AttachFile) from source code and i think it supported this feature before. 
But it looks like not support  now . Or I don't know how to use it.
Thanks.

### Usage example

```
  @Override
  protected Void handleSeleneseCommand(WebDriver driver, String locator, String value) {
    File file = downloadFile(value);

    WebElement element = finder.findElement(driver, locator);
    element.clear();
    element.sendKeys(file.getAbsolutePath());

    return null;
  }
```

**Comment by titusfortner** [comment]
That's not what an input element with a file type is for. Selenium focuses on implementing browser interactions to mimic the way users interact with them, which is to upload a file from the local computer.
