### ISSUE TITLE
[🚀 Feature]: Allow the new SeleniumManager CLI to be used as a Rust lib crate

### ISSUE THREAD

**Issue by stevepryde** [SeleniumHQ/selenium#11132]
### Feature and motivation

Hi, I'm the owner/maintainer of the `thirtyfour` rust crate (rust selenium client).

We're looking at adding some functionality to thirtyfour in future to manage WebDriver versions and starting/stopping them locally. A lot of those features look like they will be part of the new SeleniumManager tool. However it's only a CLI at the moment.

It would be awesome if you could structure that rust crate as a lib + bin and expose the same API via the lib, so that thirtyfour can use this directly and expose the same functionality within our crate without having to shell out to run the binary (and require users to install the binary).

I'd be happy to contribute this feature if you like, including collaborating with people on your team to get the API/design right.

### Usage example

Instead of rust projects having to shell out to the SeleniumManager CLI, it would be much nicer to import that crate as a dependency in thirtyfour and we can expose the same functionality via our own API in thirtyfour.

This provides far better integration for users of thirtyfour, and any other rust projects in the same space.

**Comment by bonigarcia** [comment]
Hi @stevepryde. Indeed this seems a look idea to me. Can you please provide a PR about that? And, of course, your feedback about the design of Selenium Manager is welcome. Thanks!

**Comment by 0xvasanth** [comment]
Hi @stevepryde, I am very much interested to work in this feature can you create the plan and roadmap? will help you out on that. we can connect using slack

**Comment by stevepryde** [comment]
> Hi @stevepryde, I am very much interested to work in this feature can you create the plan and roadmap? will help you out on that. we can connect using slack

See the above github-actions comment above yours. I'm not leading this feature and don't have time to work on it currently, sorry.

**Comment by bcpeinhardt** [comment]
@stevepryde just so you know I tried this out and you can in fact pull in the library and used it. You just have to do a git dependency from the selenium project with the branch set as trunk.

Idk if this should be wrapped or reexported under a feature flag in the future, but for now might be worth mentioning in the README with an example Cargo.toml snippet since WebDriverManager functionality is so widely used in other bindings.

Let me know if you'd like it there and I'll edit the README and make a pull request.

**Comment by stevepryde** [comment]
> Let me know if you'd like it there and I'll edit the README and make a pull request.

@bcpeinhardt That sounds like a good idea. Thanks.
