### ISSUE TITLE
[🐛 Bug]: selenium/hub:latest is not at all loading new nodes with any version 

### ISSUE THREAD

**Issue by prashantigs** [SeleniumHQ/selenium#11141]
### What happened?

selenium/hub:latest is not at all loading new nodes with any version 

i hit http://localhost:4444/ its keep saying loading 
![image](https://user-images.githubusercontent.com/96814019/196353941-ca608ade-5254-4512-87b8-b429e451e108.png)

Can someone help me with this

### How can we reproduce the issue?

```shell
The command i tried .

$ docker network create newGrid 
$ docker run -d -p 4444:4444 --net newGrid --name selenium-hub3 selenium/hub:latest
$ docker run -d --net newGrid -e HUB_HOST=selenium-hub --shm-size=2g selenium/node-chrome:latest
$ docker run -d --net newGrid-e HUB_HOST=selenium-hub --shm-size=2g selenium/node-firefox:latest
```

### Relevant log output

```shell
Its keep loading not showing nodes
```

### Operating System

windows 1o

### Selenium version

serenity-core v3.2.0

### What are the browser(s) and version(s) where you see this issue?

latest

### What are the browser driver(s) and version(s) where you see this issue?

latest

### Are you using Selenium Grid?

yes

**Comment by diemol** [comment]
Seems you are using old env vars, which were used in Selenium Grid 3. Please follow the current docs https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes

**Comment by prashantigs** [comment]
Thanks i am checking
