### ISSUE TITLE
[🐛 Bug]: When I ask server A to execute an automated script on server B by selenium-grid，I cannot use Chrome DevTools Protocol

### ISSUE THREAD

**Issue by wkxLegend** [SeleniumHQ/selenium#11142]
### What happened?

When I ask server A to execute an automated script on server B by selenium-grid. I get an error.
```
File "/code/selenium_execute/debug.py", line 359, in fetch
    trio.run(f)
  File "/usr/local/sbin/python-3.8/lib/python3.8/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/code/selenium_execute/debug.py", line 331, in f
    async with execute_object.driver.bidi_connection() as connection:
  File "/usr/local/sbin/python-3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/sbin/python-3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1176, in bidi_connection
    version, ws_url = self._get_cdp_details()
  File "/usr/local/sbin/python-3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1199, in _get_cdp_details
    res = http.request('GET', f"http://{debugger_address}/json/version")
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=64459): Max retries exceeded with url: /json/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c90401280>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Because of selenium-grid is used, The chrome browser runs on server B. this host should be the ip address of server B instead of the 'localhost' of server A. Therefore,  I cannot call the Chrome DevTools Protocol of server B on server A

### How can we reproduce the issue?

First, set server A as the Hub using selenium-grid

Second, set server B to node

Third, run selenium in python on server A and execute it on server B using RemoteDriver()

```
async with driver.bidi_connection() as connection
```

When you use the code above for connecting CDP, you will reproduce the issue

### Relevant log output

```shell
No
```

### Operating System

mac OS

### Selenium version

Python selenium 4.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106

### Are you using Selenium Grid?

Selenium Grid 3.141.0

**Comment by diemol** [comment]
I believe this is because you are using an old version of Selenium Grid. Please use the latest (4.5.0 at the moment of writing this), and if needed, set the `--grid-url` value in the [Node](https://www.selenium.dev/documentation/grid/configuration/cli_options/#node).

If the issue still happens, please provide the information required by the template and we will reopen.
