### ISSUE TITLE
[🐛 Bug]: hasAuthentication interface is not working in Jenkins (Linux / chrome) to bypass SSO

### ISSUE THREAD

**Issue by Ponsuryaprakash** [SeleniumHQ/selenium#11151]
### What happened?

Our application URL is different from authentication server URL. 

In local, using hasAuthentication I can able to bypass this SSO. But in Jenkins, it is failing.

### How can we reproduce the issue?

```shell
I used the below code:
Predicate<URI> uriPredicate = uri -> uri.getHost().contains ("xyz.abc.com");
HasAuthentication drAuth = (HasAuthentication) driver;
drAuth.register(uriPredicate, UsernameAndPassword.of("user","password"));
```

### Relevant log output

```shell
No output for this code
```

### Operating System

Linux

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

Chrome 98

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 98

### Are you using Selenium Grid?

No

**Comment by Ponsuryaprakash** [comment]
@pujagani could you check this out

**Comment by diemol** [comment]
That works for basic authentication not for SSO. At the moment there is no solution for that and could be proposed either at https://github.com/w3c/webdriver or https://github.com/w3c/webdriver-bidi.

**Comment by Ponsuryaprakash** [comment]
Hi @diemol , in my local system (private window) of chrome browser, I am able to achieve the SSO login with different user using the same code.

**Comment by diemol** [comment]
Then it is a matter of the machine setup, if you need help, we'd be happy to chat in our [IRC/Slack channel](https://www.selenium.dev/support/) where the community can help you as well.

**Comment by Ponsuryaprakash** [comment]
Sure @diemol , thanks
