### ISSUE TITLE
[🐛 Bug]: Wrong type for get_full_page_screenshot_as_png

### ISSUE THREAD

**Issue by eNcacz** [SeleniumHQ/selenium#11157]
### What happened?

The `WebDriver` class in `selenium/webdriver/firefox/webdriver.py` file has a method `get_full_page_screenshot_as_png` which declare the return type as `str`, but it returns the output of `b64decode` method which returns `bytes`.

See the `get_full_page_screenshot_as_png` source code in selenium 4.5.0 package. It looks like this one:

```python
    def get_full_page_screenshot_as_png(self) -> str:
        """
        Gets the full document screenshot of the current window as a binary data.

        :Usage:
            ::

                driver.get_full_page_screenshot_as_png()
        """
        return base64.b64decode(self.get_full_page_screenshot_as_base64().encode('ascii'))
```

So the `get_full_page_screenshot_as_png` seems to return `str` but in runtime it returns `bytes`. The `str` type for return value should be changed to `bytes`.

If you run the example below, then it works as expected - the `screenshot` variable is `bytes` but PyCharm (and mypy) complains for line 7 that `Expected type 'bytes', got 'str' instead` which is not true in runtime.

### How can we reproduce the issue?

```shell
from selenium import webdriver


def test():
  driver = webdriver.Firefox(executable_path='... put proper path here ...')
  driver.get('http://www.example.com/')
  screenshot:bytes = driver.get_full_page_screenshot_as_png()
  print(type(screenshot))


if __name__ == '__main__':
  test()
```

### Relevant log output

```shell
No logs needed.
```

### Operating System

Gentoo Linux

### Selenium version

Python 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 104.0.2

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.32.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
@eNcacz could you make a PR with the fix?

**Comment by titusfortner** [comment]
Thank you.
