### ISSUE TITLE
[🐛 Bug][java]: Switching base64 decoder to a strict mode is going to break the compatibility with various Appium drivers

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#11168]
### What happened?

Inclusion of https://github.com/SeleniumHQ/selenium/pull/11107 into the lib release is going to create issues with Appium driver compatibility. Some of these drivers are returning screenshots being base64-encoded with line breaks, which is against RFC4648 standard, but still complies to RFC2045. Calling Base64.getDecoder().decode would throw an exception for such blobs, while Base64.getMimeDecoder().decode would not (RFC4648-encoded blob could still be properly decoded properly by the MIME decoder though).

We did update Appium drivers to return screenshots in RFC4648, although older versions of them still use the old method. And we cannot limit newer client versions to be used only with newest driver releases. That is why my proposal would be to revert the above PR and let the client to accept both standards, even though the w3c standard is being strict about that.

### How can we reproduce the issue?

```shell
See above
```

### Relevant log output

```shell
None
```

### Operating System

Any

### Selenium version

4.5.0+

### What are the browser(s) and version(s) where you see this issue?

Any

### What are the browser driver(s) and version(s) where you see this issue?

Any

**Comment by titusfortner** [comment]
@pujagani / @diemol is this controversial? can we just revert that commit? Do we need to discuss in meeting tomorrow?

**Comment by pujagani** [comment]
Yes, I think we need to discuss it. Mainly around the point that w3c is being strict with the standard it accepts and changes we made in line with that but should we allow additional standards as well?

**Comment by pujagani** [comment]
I am also thinking, we had a similar issue in terms of the minimum geckodriver version to be used with the respective Selenium version to support CDP. On similar lines, is it okay for Appium to call out which version to use if they need the RFC2045 standards? Since the newer version of Appium will be going the spec-compliant way too.

**Comment by diemol** [comment]
>We did update Appium drivers to return screenshots in RFC4648, although older versions of them still use the old method. And we cannot limit newer client versions to be used only with newest driver releases.

@mykola-mokhnach is this meant to support users who are still with older versions? Why can't we ask users to upgrade? If we cannot ask them (for whatever reason), what is the timeline/deadline where we can use only the spec-compliant mode?

**Comment by valfirst** [comment]
@diemol sometimes users do not have full control over their infrastructure, for examples, clouds, like, SauceLabs or BrowserStack

**Comment by diemol** [comment]
Well, cloud providers should have relative recent versions available. Which is why I was asking what is the timeline/deadline where we can use only the spec-compliant mode?

**Comment by mykola-mokhnach** [comment]
I've only updated drivers recently. Which means we'd need to keep the legacy implementation for quite a while, at least one year. Also, the change would be a breaking one (e.g. I would expect changing of the major lib version)

**Comment by titusfortner** [comment]
What driver versions are compliant and which break?
What would prevent someone from updating their driver versions?
If they can't update driver versions, can't they lock their Selenium version to an older version?
How hard would it be for Appium to create its own implementation of screenshots that allow non-compliant coding?

**Comment by titusfortner** [comment]
I'm somewhat sympathetic to maintaining backwards compatibility, but we've pushed hard to be completely standards compliant. If we revert the change to the non-compliant option it has to be a temporary fix; i.e., we need a better long-term plan than "wait a year."

**Comment by mykola-mokhnach** [comment]
> What driver versions are compliant and which break?

From these that I know would break: appium-xcuitest-driver, appium-uiautomator2-driver, appium-espresso-driver, appium-mac2-driver
Basically all the main mobile drivers. The base64 screenshot encoding has been changed there some days ago, so basically all the previous versions of them would stop working properly

> What would prevent someone from updating their driver versions?

Many people still use Appium 1. Newer driver versions are not compatible to it.

> If they can't update driver versions, can't they lock their Selenium version to an older version?

They can. Although it won't work if/when they decide to update their appium client, because we also have minimum selenium client version requirements.

> How hard would it be for Appium to create its own implementation of screenshots that allow non-compliant coding?

If we are talking only about screenshots then not very hard, I would just have to override one method in the derived driver class

**Comment by titusfortner** [comment]
What else besides screenshots is affected? 

If we only need to update one method, and we can be reasonably assured that if they are using the latest Selenium they can use the latest Appium, this seems like the best solution for now. 

For the future, we do want to see if we can determine these issues ahead of time. :)

**Comment by mykola-mokhnach** [comment]
AFAIK base64 encoding is only used for screenshots. I don't remember any other places it would be needed

**Comment by titusfortner** [comment]
Thanks for raising this for us to discuss. Looks like we have a good-enough solution for now, so I'll close this.
