### ISSUE TITLE
[🚀 Feature]: Node details from Selenium session

### ISSUE THREAD

**Issue by albertalgi** [SeleniumHQ/selenium#11161]
### Feature and motivation

Hello,

I have more than one grid with some nodes each. For session tracking and logging purposes, I was wandering if it is possible to get the name (or the ID) or specific information of the node on which the Selenium session was executed using the Selenium driver at runtime. 

I have not been able to find any information on this. If there is already a way to get this information during a test run, please could you tell me how?

Thank you in advance,
albertalgi

### Usage example

I would use the Selenium driver as follows in Python:

nodeID = driver.node.getID()

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/grid/advanced_features/graphql_support/
