### ISSUE TITLE
Easier way to restart Firefox

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#1116]
Currently, if you want to restart Firefox, you need to create a new `Firefox.Binary` instance.
Moreover, I can't find a simple way to keep the same profile.

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by marco-c** [comment]
Here's an example of the issue I've filed. Let's say you use a *startBrowser* function to restart a browser (after *driver.close* and *driver.quit*).

This works, because it creates a new instance of Firefox.Binary:
```
function startBrowser() {
  var firefoxBinary = new firefox.Binary(firefoxBinaryPath);
  var firefoxOptions = new firefox.Options().setBinary(firefoxBinary);
  var builder = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(firefoxOptions);
  var driver = builder.build();
}
```

This doesn't work, because it doesn't use a new instance of *Firefox.Binary*:
```
var firefoxBinary = new firefox.Binary(firefoxBinaryPath);
var firefoxOptions = new firefox.Options().setBinary(firefoxBinary);
var builder = new webdriver.Builder()
  .forBrowser('firefox')
  .setFirefoxOptions(firefoxOptions);
function startBrowser() {
  var driver = builder.build();
}
```

The second option fails because in firefox/binary.js there's this code:
```
Binary.prototype.launch = function(profile) {
  if (this.command_) {
    throw Error('Firefox is already running');
  }
```

The *command_* property is set in the Binary class, but never reset to null, so it will never allow you to restart the browser.

**Comment by marco-c** [comment]
So, to make it short, *Binary::launch* fails even if Firefox isn't running.
