### ISSUE TITLE
[🚀 Feature]: Status Code for fail fast approach iin python

### ISSUE THREAD

**Issue by codejunction** [SeleniumHQ/selenium#11176]
### Feature and motivation

generate status code as a driver property
Test Scenarios:
  1. testing page redirection
  2. unauthorized
  3. server(backend) failure
 
Why:
 1. Avoid url check for current url or redirected url
 2. Status Check tests for UI

### Usage example

```python
driver = webdriver.Chrome(
            service=Service(self.executable_path),
            options=self.options,
            desired_capabilities=self.capabilities,
        )
driver.get(self._test_root_ui)
self._logger.debug(driver.status_code)
```

**Comment by titusfortner** [comment]
There are so many status codes when it comes to browser requests, this is outside the scope of the project. We recommend using a proxy if you want to investigate this functionality.
