### ISSUE TITLE
How to load unsafe scripts on Chrome using WebDriver

### ISSUE THREAD

**Issue by rajdepot** [SeleniumHQ/selenium#1117]
![image](https://cloud.githubusercontent.com/assets/15016177/10340289/0358cfe4-6d2d-11e5-933e-15c4f33d4cf8.png)
![chrome unsafe script issue](https://cloud.githubusercontent.com/assets/15016177/10340336/30e96900-6d2d-11e5-90b6-723cf59e0f89.png)

**Comment by rajdepot** [comment]
Above issue is blocking Login action

**Comment by lukeis** [comment]
from chrome specific related issues, please log them on the chromedriver bug tracker:
code.google.com/p/chromedriver/issues/list

**Comment by Jeremiah-** [comment]
Did you ever find a fix for this?
