### ISSUE TITLE
[🐛 Bug]: [python] and Modal Dialog

### ISSUE THREAD

**Issue by Pfzoz** [SeleniumHQ/selenium#11170]
### What happened?

I don't know precisely how to address this problem, as I have no smarts in web services or anything alike.
I'm trying to access this web page automatically and check one of the boxes on (what I suppose is called) the modal window, that pops up after you click the button "Downloads", on the bottom of the page.
I'm able to identify the element, it has its own unique id so that is easily done, I try and guarantee its existence by printing one of its attributes, and it works correctly aswell.
However, by any methods I try, I cannot reach that element and click it, or do most actions I wish to.
I've tried different solutions such as moving to the element, reaching a different iframe (which the page doesn't hold any for that place), checked window-handles and there's only the original one, and also checked alerts and I receive nothing.
I've tried even executing scrollIntoView() as javascript code, and it returns me None on python code, doesn't seem to help.
By using ActionChains, it tells me original element is not displayed, indeed when I use the method getDisplayed(), it says it is not displayed (although I can see it clearly on the browser), by using the click method of the element  it tells me it could not scroll into view, other methods such as send_keys() tell me element is not interactble.
I've tried different drivers aswell.

### How can we reproduce the issue?

```shell
# it can be reproduced by the following code
driver = webdriver.Firefox()
driver.get("https://sidra.ibge.gov.br/tabela/5457")
driver.maximize_window()
time.sleep(10)
driver.find_element_by_id("botao-downloads").click()
time.sleep(3)
driver.find_element_by_id("id-terr-cod").click()
```

### Relevant log output

```shell
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable

selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Origin element is not displayed
```

### Operating System

Linux (Mx Wildflower)

### Selenium version

Python (3.9.12)

### What are the browser(s) and version(s) where you see this issue?

Firefox & Chrome

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.32.0 and Chromedriver 107.0.5304.62

**Comment by titusfortner** [comment]
Huh, this is weird. No idea what's going on here...

but...

this works, and I have no idea why.

```
driver.find_element(id: 'modal-downloads').find_elements(class_name: 'checkbox-inline')[3].click
```

**Comment by Pfzoz** [comment]
> Huh, this is weird. No idea what's going on here...
> 
> but...
> 
> this works, and I have no idea why.
> 
> ```
> driver.find_element(id: 'modal-downloads').find_elements(class_name: 'checkbox-inline')[3].click
> ```

That did work! Thank you so much.
