### ISSUE TITLE
[🐛 Bug]: Unable to parse response from server since Selenium Java 4.5.1 with LitteProxy (BrowserUP-Proxy) in Chrome-Headless-Mode

### ISSUE THREAD

**Issue by derRichter** [SeleniumHQ/selenium#11186]
### What happened?

Hi,

since Selenium-Java ver. 4.5.1 and up to 4.5.3, maybe with the new PortPropper-Feature, we have no working connection anymore over LitteProxy [(last version of BrowserUp-Proxy)](https://github.com/valfirst/browserup-proxy/) if the ChromeDriver eg. the Chromium in Headless-Mode.
If the Headless-Mode turned off, there are no problems with the connection.

When we use Selenium-Java 4.5.0 or older all fine in Headless-Mode with the Proxy-Connection.
Without Proxy-Connection also no Problems, only since Version 4.5.1 with Proxy the we get this responce as a html-website:

"Unable to parse response from server"
(see the chromedriver-logs)

What can we do to use the headless-mode?

greats

### How can we reproduce the issue?
[chromedriver-log_selenium-4.5.3-over-browserupproxy_headlessmode-on.txt](https://github.com/SeleniumHQ/selenium/files/9886936/chromedriver-log_selenium-4.5.3-over-browserupproxy_headlessmode-on.txt)

```shell
Use Selenium-Java ver. 4.5.1 or newer with BrowserUp-Proxy as proxy (and aktivated Headless-Mode) the connection over the proxy is not working.
"Unable to parse response from server"
```

### Relevant log output

```shell
1666946167.460][INFO]: [26c81179a9a5f201506b413ded982055] COMMAND Navigate {
   "url": "https://meine.santander.de/"
}
[1666946167.460][INFO]: Waiting for pending navigations...
[1666946167.460][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=19) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "expression": "1"
}
[1666946167.461][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=19) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}
[1666946167.461][INFO]: Done waiting for pending navigations. Status: ok
[1666946167.461][DEBUG]: DevTools WebSocket Command: Page.navigate (id=20) (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "url": "https://meine.santander.de/"
}
[1666946167.464][DEBUG]: DevTools WebSocket Event: Network.requestWillBeSent (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "documentURL": "https://meine.santander.de/",
   "frameId": "A2DEB70026F4443A5F9F4552CD56BB27",
   "hasUserGesture": false,
   "initiator": {
      "type": "other"
   },
   "loaderId": "652EFF04148AF1013A80091645D22E58",
   "redirectHasExtraInfo": false,
   "request": {
      "headers": {
         "Upgrade-Insecure-Requests": "1",
         "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.0 Safari/537.36"
      },
      "initialPriority": "VeryHigh",
      "isSameSite": true,
      "method": "GET",
      "mixedContentType": "none",
      "referrerPolicy": "strict-origin-when-cross-origin",
      "url": "https://meine.santander.de/"
   },
   "requestId": "652EFF04148AF1013A80091645D22E58",
   "timestamp": 952391.648372,
   "type": "Document",
   "wallTime": 1666946167.463118
}
[1028/103607.510720:WARNING:resource_bundle.cc(450)] locale_file_path.empty() for locale de-DE
[1666946169.107][DEBUG]: DevTools WebSocket Event: Network.requestWillBeSentExtraInfo (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "associatedCookies": [  ],
   "connectTiming": {
      "requestTime": 952391.649863
   },
   "headers": {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "de-DE",
      "Connection": "keep-alive",
      "Host": "meine.santander.de",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "none",
      "Sec-Fetch-User": "?1",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/107.0.5304.0 Safari/537.36"
   },
   "requestId": "652EFF04148AF1013A80091645D22E58"
}
[1666946169.204][DEBUG]: DevTools WebSocket Event: Network.responseReceivedExtraInfo (session_id=1CCCC906AAE3732025A84F73338E4A7A) A2DEB70026F4443A5F9F4552CD56BB27 {
   "blockedCookies": [  ],
   "headers": {
      "content-length": "36",
      "content-type": "text/html; charset=utf-8",
      "date": "Fri, 28 Oct 2022 08:36:09 GMT",
      "via": "1.1 BrowserUpProxy"
   },
   "headersText": "HTTP/1.1 502 Bad Gateway\r\ncontent-length: 36\r\ncontent-type: text/html; charset=utf-8\r\nvia: 1.1 BrowserUpProxy\r\ndate: Fri, 28 Oct 2022 08:36:09 GMT\r\n\r\n",
   "requestId": "652EFF04148AF1013A80091645D22E58",
   "resourceIPAddressSpace": "Unknown",
   "statusCode": 502
}
```

### Operating System

Windows 10, macOS 10.14

### Selenium version

Selenium Java 4.5.1, 4.5.2, 4.5.3

### What are the browser(s) and version(s) where you see this issue?

Chromium 107.0.5304.68

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver-Version 107.0.5304.62

**Comment by diemol** [comment]
How can we reproduce the issue? Can you share a test or a GitHub project that we can run to reproduce it?

**Comment by derRichter** [comment]
"How can we reproduce the issue?"

Use Selenium-Java ver. 4.5.1 or newer with BrowserUp-Proxy as proxy.
and call the site: https://meine.santander.de

(with Selenium-Java vers. 4.5."0" or older no problmes)

**Comment by diemol** [comment]
Can you provide that setup, please?

**Comment by derRichter** [comment]
? i dont know what you meen. My code is not working stand-alone, i have to write a code for this for standalone only call this website over proxy with selenium

can you use the attached log?

**Comment by diemol** [comment]
I understand there is an issue, however I need a self contained test that we can use to reproduce the issue. Creating it ourselves brings ambiguity and probably won't reproduce the issue. That is why it is better if you please help us by giving us some code that we can use to see the same issue you are seeing.

**Comment by derRichter** [comment]
thx, i understand that.
here is my test-case,  maybe jar-conflicts ...
[little.tester.zip](https://github.com/SeleniumHQ/selenium/files/9890807/little.tester.zip)

**Comment by titusfortner** [comment]
You can also try the new chrome headless mode by specifying `chrome`:

```
--headless=chrome
```

**Comment by derRichter** [comment]
its the same, and with the new browserup-proxy 2.2.4 with the same netty-version is the same issue now without headless-mode also
there is any conflict

**Comment by derRichter** [comment]
OK, looks like that, this run with the "new" command-line option "--headless=chrome" is sometimes better. But i don't understand why?! because not everytime, you can reproduce then the error with switch on the old (headless)option-setting.
is the new and the old one active, is also better sometimes working.

do you understand why i get a "bad gateway"-error when i use only the "old" headless-option?
[little.tester new-headless.zip](https://github.com/SeleniumHQ/selenium/files/9895666/little.tester.new-headless.zip)


Is there any documentation for the command-line options?
I need to know since witch versions are working with the "new" headless-option, because i use now both, the old and new one to support the old one also

**Comment by derRichter** [comment]
maybe is also a problem with the redirects of this site https://meine.santander.de/olb
https://www.whatsmydns.net/redirect-checker?q=https%3A%2F%2Fmeine.santander.de%2Folb


[little.tester new-headless.zip](https://github.com/SeleniumHQ/selenium/files/9895667/little.tester.new-headless.zip)

**Comment by titusfortner** [comment]
For the old headless mode, Google removed a bunch of extra functionality to speed things up for users needing to test basic browser faster.

The "new" headless mode is the full browser just not being displayed. If it is working for one and not the other, it's like a problem with something Chrome removed to speed up headless.

If you're still seeing the error when not headless then that's not the issue. It could be certificate related? Try setting it to accept insecure certs (https://w3c.github.io/webdriver/#dfn-insecure-tls-certificates)

Selenium is throwing this error because it is expecting a JSON response, and is instead getting an html response with an error. The root cause is going to either be a bug in chromedriver, a configuration issue with chromedriver, or something with proxy settings. None of those things can we really address here.
