### ISSUE TITLE
[🐛 Bug]: ChromeDriver v107.0.5304.62 starts and stops with Selenium 4.5.3

### ISSUE THREAD

**Issue by vicozohili** [SeleniumHQ/selenium#11187]
### What happened?

ChromeDriver v107.0.5304.62 starts and stops with Selenium 4.5.3.
This does not occur with Selenium 4.5.0.

### How can we reproduce the issue?

```shell
Update to Selenium 4.5.3
```

### Relevant log output

```shell
No output, the chromedriver.exe just terminates
```

### Operating System

Windows

### Selenium version

4.5.3

### What are the browser(s) and version(s) where you see this issue?

Chrome v107.0.5304.88

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver v107.0.5304.62

### Are you using Selenium Grid?

4.5.3

**Comment by diemol** [comment]
Closing as we did not get more information.
