### ISSUE TITLE
[🐛 Bug]: Selenium grid keeps on loading in the UI while created through docker

### ISSUE THREAD

**Issue by Sauravpersonal08** [SeleniumHQ/selenium#11196]
### What happened?

docker pull selenium/hub
docker pull selenium/node-chrome-debug
docker pull selenium/node-firefox-debug
docker network create mynetworkselenium

Hub
docker run -d -p 4445:4444 --net mynetworkselenium --name seleniumHub selenium/hub
docker run -d -p 4446:5900 --net mynetworkselenium -e HUB_HOST=seleniumHub --name chromeNode selenium/node-chrome-debug
docker run -d -p 4447:5900 --net mynetworkselenium -e HUB_HOST=seleniumHub --name firefoxNode selenium/node-firefox-debug

<img width="960" alt="2022-10-30" src="https://user-images.githubusercontent.com/52004006/198860232-3c309a5d-f6ef-44d6-a4a5-516389b46c92.png">

### How can we reproduce the issue?

```shell
docker pull selenium/hub
docker pull selenium/node-chrome-debug
docker pull selenium/node-firefox-debug
docker network create mynetworkselenium

Hub
docker run -d -p 4445:4444 --net mynetworkselenium --name seleniumHub selenium/hub
docker run -d -p 4446:5900 --net mynetworkselenium -e HUB_HOST=seleniumHub --name chromeNode selenium/node-chrome-debug
docker run -d -p 4447:5900 --net mynetworkselenium -e HUB_HOST=seleniumHub --name firefoxNode selenium/node-firefox-debug
```

### Relevant log output

```shell
User should able to execute test cases in selenium grid
```

### Operating System

windows 11

### Selenium version

java

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver

### Are you using Selenium Grid?

selenium grid

**Comment by diemol** [comment]
`debug` containers are not working for Selenium 4. The new images have everything you need, please follow the instructions at https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes
