### ISSUE TITLE
[🚀 Feature]: Export backend code object or function to browser.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [SeleniumHQ/selenium#11194]
### Feature and motivation

it's add js invoke backend capability.

### Usage example

For example, I use C# backend:

```c#
EdgeOptions op = new EdgeOptions();
var esrv = EdgeDriverService.CreateDefaultService(".\\", "msedgedriver.exe");
var drv = new EdgeDriver(esrv, op);

drv.AddBackendObjectToJs("objectName", new JsInvokeMethodClass());
```

and Js:

```js
objectName.xxxfunction();
```

**Comment by diemol** [comment]
I am not really understanding what you mean. Is it to add a JS script that executes in the browser?

**Comment by MiyamuraMiyako** [comment]
@diemol It's similar to cefsharp or electron, browser can execute c# or nodejs code.

**Comment by MiyamuraMiyako** [comment]
@diemol   It's similar to cefsharp or electron, browser can execute c# or nodejs code.

**Comment by diemol** [comment]
Can you share a link or an example to understand better?

**Comment by MiyamuraMiyako** [comment]
example:
https://stackoverflow.com/questions/51259813/call-c-sharp-function-from-javascript-using-cefsharp-in-windows-form-app

or

https://www.c-sharpcorner.com/article/communication-between-winforms-application-and-web-application-using-cefsharp-br/

**Comment by diemol** [comment]
Thanks for sharing the links. That is out of the scope of this project. In the upcoming standard https://github.com/w3c/webdriver-bidi, there will be a way to register a JS function from the C# code (and other languages as well), but not the other way around.
