### ISSUE TITLE
[🐛 Bug]: unable to store data in chrome local storage 

### ISSUE THREAD

**Issue by andreyDavid** [SeleniumHQ/selenium#11208]
### What happened?

After my chrome got updated to version 107 i can't store any data in local storage of chrome using selenium - getting timeout - Timeout waiting for response on 113  

a simple example code is provided.

I use a mac with m1 pro processor 

### How can we reproduce the issue?

```shell
run the following code 

`driver = webdriver.Chrome(executable_path="/Applications/Google Chrome.app")
 driver.get('https://www.google.com')
 driver.execute_script(f"window.localStorage.setItem('fp',{'123'});")
`
```

### Relevant log output

```shell
Timeout waiting for response on 113
```

### Operating System

macOS Monterey - version 12.6.1

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 107.0.5304.87

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 107.0.5304.62

### Are you using Selenium Grid?

Nope

**Comment by diemol** [comment]
If this happens after the upgrade, it is most likely a Chrome bug.
