### ISSUE TITLE
[🐛 Bug]: Selenium .net test run stops when using DevTool

### ISSUE THREAD

**Issue by VictorYakushenko** [SeleniumHQ/selenium#11207]
### What happened?

Selenium .net test run aborted when using DevTool for monitoring. 
This bug is reproduced for NetworkRequestSent and NetworkResponseReceived.
After this bug happens even TearDown is not executed, looks like stackoverflow.

To reproduce this bug you need 
- .Net project with Selenium, Chromedriver and Nunit only
- StartMonitoring
- Navigate one or few times to https://www.youtube.com/ (I added youtube just for example, I also reproduced it on other site)

### How can we reproduce the issue?

```shell
public class Tests
    {
        IWebDriver driver;
        INetwork network;

        [SetUp]
        public void Setup()
        {
            driver = new ChromeDriver();
            driver.Manage().Window.Maximize();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);
            network = driver.Manage().Network;
            network.NetworkResponseReceived += OnNetworkResponseReceived;
            network.StartMonitoring();
        }

        [TearDown]
        public void TearDown()
        {
            network.StopMonitoring();
            driver.Quit();
        }

        [Test]
        public void Test1()
        {
            driver.Navigate().GoToUrl("https://www.youtube.com/");

        }

        private void OnNetworkResponseReceived(object sender, NetworkResponseReceivedEventArgs e)
        {
        }
    }
```

### Relevant log output

```shell
Building Test Projects
========== Starting test run ==========
NUnit Adapter 4.2.0.0: Test execution started
Running selected tests in D:\Work\Repos\SeleniumTest\SeleniumTest\bin\Debug\net6.0\SeleniumTest.dll
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run
The active test run was aborted. Reason: Unable to communicate with test host process.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

### Operating System

Windows 11

### Selenium version

4.5.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107

**Comment by titusfortner** [comment]
This is at least the same reproduction case for the issue in #11129 so fixing one will fix both; we can track there. 

Also of note - we'd welcome any implementation suggestions or Pull requests, but the current code is a temporary solution while we work on getting the WebDriver BiDi protocol implemented.

**Comment by githubDiabsolut** [comment]
I am encountering the same bug in my work
