### ISSUE TITLE
[🚀 Feature]: Compress Selenium Manager Binaries

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11204]
### Feature and motivation

I think the packages themselves get compressed, so I'm not sure if it would benefit us to zip the binaries and unzip in code, or not.

Might be worth checking to see what difference it makes before adding the extra code.

### Usage example

Transparent to the user; everything that was done in 4.6 would still work, just when we call the equivalent `getBinary()` method, it would need to also unzip it.

**Comment by nvborisenko** [comment]
Please don't apply it in .Net. Nuget package, which is primary distribution method, is already `zip` archive.

**Comment by titusfortner** [comment]
There are 2 advantages.

1. Smaller binaries stored in repo
2. Some of the packages in some of the languages might be smaller

The task here is to see how much of a difference it would make in which languages, etc. If we don't have to deal with compression in the code that would be nice, but I want to make sure we are making an informed decision about it.

**Comment by titusfortner** [comment]
Packages are already compressed, so no end value found. if we're concerned about adding too much overhead to the repo, there are better fixes.
