### ISSUE TITLE
Bug in 2.48.0 getting value of a data attribute when it contains a DateTime in ISO8601 format

### ISSUE THREAD

**Issue by crowbarsolutions** [SeleniumHQ/selenium#1120]
I found a bug that only happens when using version 2.48.0 of the Selenium Webdriver and Support nuget packages (for C#). I am using the latest chrome driver 2.19.

I have an element in my page that looks like so:

    <div id="comments">
        <time id="CreatedOn" data-utc="2015-09-10T19:23:37.3631878Z">2015/09/10 13:23</time>
    </div>

I have a test that grabs the value of the data-utc attribute.

    [FindsBy(How = How.CssSelector, Using = "#comments time")]
    private IWebElement commentTimestamp;
    
    public static string GetTimeValueUtc() 
    {
        return commentTimestamp.GetAttribute("data-utc");
    }

In version 2.47.0 this function returns the string "2015-09-10T19:23:37.3631878Z" as expected.

But in version 2.48.0 this function returns the string "9/10/2015 7:23:37 PM".

To make sure it wasn't my code, I reverted back to 2.47.0 and verified that was the only difference that causes this inconsistency.

Perhaps there's some kind of weird casting going in the lastest version? I know .NET looooooves casting anything resembling a DateTime without being asked.

**Comment by jimevans** [comment]
The issue was introduced when the JSON parsing of responses from browser drivers was refactored to remove the attribute-based deserialization of JSON responses. The default settings for the Json.NET deserializer are to change date strings into `DateTime` data types. This had been turned off in the previous code, but changing this setting in the refactored code was forgotten. Working on a patch now.

**Comment by sdimkov** [comment]
I believe this got fixed in [release 2.48.1](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-2.48.1)

**Comment by jimevans** [comment]
@sdimkov No, this issue is specific to the .NET bindings, and the fix, while completed and committed, has not been released as a binary release yet.

**Comment by martincostello** [comment]
Is there an ETA for the next version?

**Comment by jimevans** [comment]
No, there is no ETA. I can't commit to a time frame, only to be yelled at if, for some reason, I have to miss that time frame for a release.
