### ISSUE TITLE
[🐛 Bug]: Rust definitions prevent Bazel on Windows

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11212]
### What happened?

The Rust definitions appear to assume that they will only be used on Linux or Mac.

Because they are in `selenium/WORKSPACE` they are always loaded even when not being used.

### How can we reproduce the issue?

```shell
`bazel build grid`
```

### Relevant log output

```shell
PS C:\Users\titusfortner\git\selenium> bazel test //rb:chrome-test
Starting local Bazel server and connecting to it...
ERROR: Traceback (most recent call last):
        File "C:/users/titusfortner/_bazel_titusfortner/ly5wn6nu/external/rules_rust/rust/private/rustc.bzl", line 1838, column 34, in <toplevel>
                build_setting = config.string(flag = True, allow_multiple = True),
Error in string: string() got unexpected keyword argument 'allow_multiple'
ERROR: error loading package '': in C:/users/titusfortner/_bazel_titusfortner/ly5wn6nu/external/rules_rust/crate_universe/defs.bzl: in C:/users/titusfortner/_bazel_titusfortner/ly5wn6nu/external/rules_rust/crate_universe/private/crates_repository.bzl: in C:/users/titusfortner/_bazel_titusfortner/ly5wn6nu/external/rules_rust/rust/defs.bzl: Extension file 'rust/private/rustc.bzl' has errors
I
```

### Operating System

Windows 11

### Selenium version

Trunk

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
grid builds the java client which builds `Selenium-mananger` does it not?

**Comment by titusfortner** [comment]
No, selenium manager is currently only built "manually" (https://github.com/SeleniumHQ/selenium/actions/workflows/build-selenium-manager.yml) and the assets are downloaded and stored in the repo.

**Comment by titusfortner** [comment]
fixed by updating my bazel version. :-D
