### ISSUE TITLE
[🐛 Bug]: OpenQA.Selenium.WebDriverException: 'Unexpected error creating WebSocket DevTools session.'

### ISSUE THREAD

**Issue by arnonax-tr** [SeleniumHQ/selenium#11225]
### What happened?

After Chrome is updated more than 5 versions, `Driver.GetDevToolsSession()` throws the following exception:
```
OpenQA.Selenium.WebDriverException : Unexpected error creating WebSocket DevTools session.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.
   at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(Int32 devToolsProtocolVersion)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession()
```
First, the exception is not informative, as [this comment ](https://github.com/SeleniumHQ/selenium/blob/79f1c02ae20c359daa5652d790894d5e4e24d93f/dotnet/src/webdriver/DevTools/DevToolsDomains.cs#L130) alludes to.
But the more frustrating thing is that I must update WebDriver NuGet when Chrome decides to update and not when I choose to. I would consider it acceptable if there were actually any breaking changes in the CDP, but recently I compared the classes of the V85 vs V105 and found no differences other than the version number, so I don't understand why it is necessary.

### How can we reproduce the issue?

```shell
Given Chrome 107 (or later) is installed
When I create a new .net project and add a reference to WebDriver 4.2.0 with the following code:

    var driver = new ChromeDriver();
    var devTools = chromeDriver.GetDevToolsSession();

Then I get the exception mentioned above.
```
**Notes:**
1. In the real-world scenario I have an existing project with WebDriver 4.2.0 which works with Chrome 106, and it cease to work when Chrome is updated to 107.

2. If I create a new project with WebDriver 4.6.0 (latest) and I'll wait few months until chrome 113 will come out, I believe that I'll get the same exception.

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

DotNet (see description above)

### What are the browser(s) and version(s) where you see this issue?

Chrome 107 (see description above)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 107.0.5304.62

### Are you using Selenium Grid?

No.

**Comment by titusfortner** [comment]
Selenium 4.2 can only provide devtools support for Chrome v102 since that was what was released at the time. Google does not maintain a stable API for Chrome DevTools, so there will be backwards compatibility issues. We are working on a new WebDriver-BiDi solution that will eventually provide a consistent, backwards compatible API, but in the meantime, you have to use the latest version of Selenium to have support for the latest version of Chrome DevTools.

**Comment by arnonax-tr** [comment]
Thanks @titusfortner for your answer. But still:
* My code continues to work perfectly fine after the upgrade to Selenium 4.6 without any breaking change
* I recently compared the source code of [V85](https://github.com/SeleniumHQ/selenium/tree/trunk/dotnet/src/webdriver/DevTools/v85) to that of V104, and found not difference other than things related to the version number. I believe that if Ill do the comparison again with [V107](https://github.com/SeleniumHQ/selenium/tree/trunk/dotnet/src/webdriver/DevTools/v107) the result will be the same.

So if something really changed and broke compatibility, then I accept that I must upgrade in order to work with my current browser, but that doesn't seem to be the case. 
(Can you highlight an example of such breaking change?)

**Comment by titusfortner** [comment]
yes an example of a breaking change is:
```
Unexpected error creating WebSocket DevTools session
```

We didn't create that error just to arbitrarily keep you from using a more recent version. For *some reason chromedriver v107 does not like what Selenium v4.2 & devtools v102 is sending to it wrt getting the devtools session for Chrome v107.

I was just explaining why we can't do anything about it—we can't support a version of Chrome DevTools that doesn't exist when we publish a specific version of Selenium.

The code actually is changing, it's just not the code committed in the repo. The interesting stuff is built by bazel when packaged; for example you can see the differences to the pdls being used between 103 & 106 here - https://github.com/SeleniumHQ/selenium/commit/697c717a28428e252e03a188ab99a545e5ebf7c3

**Comment by arnonax-tr** [comment]
Thanks. I still don't fully understand, but I get that there are things I'm less familiar with (like those pdl files), so I'll just take your word for it.
