### ISSUE TITLE
[🚀 Feature]: Customized source matrix and Disable/Enable Switch in Selenium Manager

### ISSUE THREAD

**Issue by alaahong** [SeleniumHQ/selenium#11223]
### Feature and motivation

It's a great feature to provide such universal golden function within Selenium. It can be working well as expected. But do we have the possible to take a look below two feature proposals?

**feature 1 -- Customized source matrix**
No external configuration within SeleniumManager
![image](https://user-images.githubusercontent.com/3264250/200110333-453d5650-b9f4-4de8-88d8-d5396df25f65.png)
And meanwhile, we also can't find out such guide in --help or release blog.
![image](https://user-images.githubusercontent.com/3264250/200110371-156e08d6-fe18-4055-91d4-93d32ed0357e.png)

This is required for intranet or behind-firewall users, they might be facing issue as below log
```
11月 05, 2022 3:52:08 下午 org.openqa.selenium.remote.service.DriverService findExecutable
警告: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\Ian\AppData\Local\Temp\selenium-manager653129306572008581132864560872458\selenium-manager.exe, --driver, geckodriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.3'
Driver info: driver.version: FirefoxDriver

java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```
Many companies do not allow download binary from internet, they have engineering team to sync driver into internal artifactory, it would be great if we can configure the driver link mapping.

**feature 2 -- Enable/Disable switch**
From blog, seems the manager will detect PATH before download by default, but can we directly provide the switch in parameter to enable or disable manager as user's mind?

Thanks.

### Usage example

N/A

**Comment by diemol** [comment]
>feature 1 -- Customized source matrix

There will be a documentation page for Selenium Manager when it gets its first release out of the beta. Right now it is only being released as part of the bindings, but in the future it will be also released on its own. The features of supporting a proxy or a different download URL are part of the roadmap. However, we do not have those particular features public. @bonigarcia @titusfortner should we create GitHub issues for each one of the features we have planned for Selenium Manager?

>feature 2 -- Enable/Disable switch
>From blog, seems the manager will detect PATH before download by default, but can we directly provide the switch in parameter to enable or disable manager as user's mind?

Right now, Selenium Manager will only be used as a fallback. This means if the user does not provide the driver location or if the driver is not present on the `PATH`, then it will be used. 

I will close this issue as soon as we make the roadmap public.

**Comment by bonigarcia** [comment]
@diemol Yes, if you want, we can create GitHub issues for the next features. So far, the roadmap is the Selenium Manager [README](https://github.com/SeleniumHQ/selenium/tree/trunk/rust), and also, we have a [backlog](https://docs.google.com/document/d/16TwXLJdeW1r4QHp8PlqC-7C4Max1HV25hZGkK5eGUKQ/edit) with ideas about future development etc. at the end of the original Selenium Manager proposal document.

**Comment by diemol** [comment]
@bonigarcia I think it is a good idea to have issues to keep track of the overall progress.

**Comment by titusfortner** [comment]
You shouldn't be getting an error from Selenium Manager, all of that should be caught with the original "download a driver" error message displayed. Is this happening from a network error? I meant to test these by turning off wifi and seeing what happened.

> should we create GitHub issues for each one of the features we have planned for Selenium Manager

Yes.

**Comment by bonigarcia** [comment]
I have updated the Selenium Manager M2 milestones in its README (see #11235). The GitHub issues for these features are:
#11210, #11132, #11239, and #11238.

**Comment by symonk** [comment]
👍 pointing at an internal mirror/artifactory etc for downloads would be useful, even if it was just exposed via environment variables, allowing different browsers to have fine grained control would be nice too there (i.e download chromed from A and geckod from B) via like `SELENIUM_CHROME_HOST` / `SELENIUM_FIREFOX_HOST` (or similar).

**Comment by titusfortner** [comment]
1. Matrix

Is the idea to support users creating their own files to match the remote files currently being parsed, etc with their own links to the various driver versions? Wouldn't it make more sense for the user to put in the code the location of the specific browser and/or driver they want to use? This seems like a lot of extra work for a use case more easily solved by other means.

2. PATH
 
Right now, it is the bindings looking on PATH for the browser, not selenium manager.

I think Selenium Manager probably should be the one looking on PATH? The bindings are each doing things slightly differently here, so whatever Selenium Manager does might be a breaking change.

3. Precedence

I think what we eventually want is this order of precedence: 
    * specific path provided by user (browser or driver)
    * valid driver located on PATH (ignores old drivers)
    * valid driver in cache (satisfies TTL limit)
    * download driver from remote source
    
It would probably make sense for this to be completely managed by the selenium manager so the logic is consistent across all the languages.

**Comment by bonigarcia** [comment]
I think this issue is no longer required, right? I'm closing it. Please re-open if something is still missing.
