### ISSUE TITLE
[🐛 Bug]: Chrome profile not loaded with headless

### ISSUE THREAD

**Issue by utzlol** [SeleniumHQ/selenium#11224]
### What happened?

I have chrome profile with credentials inside. It's normal when selenium is not launched by headless, but something really wrong happens with headless. In headless, the profile doesn't load even though options are inserted.

### How can we reproduce the issue?

```shell
options.add_argument("--user-data-dir=/home/user/.config/google-chrome")
options.add_argument("--profile-directory=Profile 1")
options.headless = True
```

### Relevant log output

```shell
No log output
```

### Operating System

Arch Linux

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 107

**Comment by diemol** [comment]
IIRC, profiles are not supported by headless.

A couple of things, `options.headless = True` will be deprecated soon in favor of passing the argument. Also, we will recommend soon to use the `headless=chrome` option. 

You can use it like this `options.add_argument("--headless=chrome")`

Give it a try, and see if profiles work with that mode. If not, most likely you will need to run the full browser with a window manager like `Xvfb`.
