### ISSUE TITLE
[🐛 Bug]: signing to google cloud platform with selenium shows network issues

### ISSUE THREAD

**Issue by adirzoari** [SeleniumHQ/selenium#11220]
### What happened?

I'm using selenium (4.5.0) & selenium wire (5.1.0) in my project. I'm writing flows to log in google cloud portals..

I enter my google cloud mail then, press on continue in Google sign in and then it log in to gcp.

I got some errors:

> Request has invalid authentication credentials. Expected OAuth 2 access token, login cookie or other...

> ERR_PROXY_CONNECTION_FAILED
![Screen Shot 2022-11-03 at 18 11 29](https://user-images.githubusercontent.com/20258998/199895838-f35f9f57-8e8e-44e1-addf-2865c4849196.jpg)

![Screen Shot 2022-11-03 at 23 05 37](https://user-images.githubusercontent.com/20258998/199882154-121803a4-78f1-42b4-9415-b885a4975740.jpg)

when I do the same flow **manually** without automation, with the same credentials, it works fine and no any network error.

my web driver
`from seleniumwire import webdriver
from seleniumwire.webdriver import ChromeOptions

def test_gcp_flow():

    options = ChromeOptions()
    options.add_experimental_option("detach", True)
    options.add_argument('--no-sandbox')
    options.add_argument('--single-process')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--start-maximized")
    options.add_argument('--auto-open-devtools-for-tabs')
    options.add_argument('--log-level=2')
    options.add_argument('--disable-features=IsolateOrigins,site-per-process')
    options.add_argument("--ignore_ssl")
    options.add_argument('--ignore-ssl-errors')
    options.add_argument('--ignore-certificate-errors')
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-setuid-sandbox")
    options.add_argument("--dns-prefetch-disable")
    options.add_argument('ignore-certificate-errors')
    options.add_argument('disable-web-security')
    options.add_argument('--allow-insecure-localhost')

    driver = webdriver.Chrome(options=options)
    driver.get('....any-hidden-url')
    # more flow actions - then it open gcp portal`

I added openssl.cnf (without this openssl, it shows me TLS ssl issue) to run it locally in my test using Pycharm:
`openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation`

### How can we reproduce the issue?

```shell
when I enter to gcp with my credentials and run my automation flow.
when I do it manually - it works without any problem.
what I'm expecting is that to sign in to gmail without network/token issues.
```

I tried to use Firefox webdriver and it works good without any network issue.
### Relevant log output

```shell
"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
"ERR_HTTP2_SERVER_REFUSED_STREAM"
```

### Operating System

mac

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

chrome - 107.0.5304.87

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Most likely the site has some control against automated scripts. There is not much we can do, but probably you can reach out to them to figure out a way to automate those flows.
