### ISSUE TITLE
[🐛 Bug]: WebDriverLink is redirected to 404 error page.

### ISSUE THREAD

**Issue by puneetksha** [SeleniumHQ/selenium#11227]
### What happened?

WebDriverLink is redirected to 404 error page.

### How can we reproduce the issue?

```shell
1. Navigate to the following URL
https://www.selenium.dev/documentation/legacy/selenium_2/faq/#q-can-i-run-multiple-instances-of-the-webdriver-sub-classes
2. Q: What’s the Selenium WebDriver API equivalent to TextPresent ?
3. Click on WebDriverWait link. 
4. Observe the behavior.
```

### Relevant log output

```shell
Outcome - 404 error.
```

### Operating System

windows 10

### Selenium version

4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107

**Comment by diemol** [comment]
That is legacy documentation and it it kept for historical reasons, the versions mentioned there are not supported or maintained anymore. It is completely possible that a link is broken or not existing anymore. In short, those docs won't be changed and/or maintained.
