### ISSUE TITLE
[🚀 Feature]: Support for browser beta/canary/dev versions in Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11239]
### Feature and motivation

Include support for browser version detection, considering not only stable versions, but also beta/canary/dev for Chrome, Firefox, Edge.

### Usage example

If for example Chrome beta is installed in the system, Selenium Manager should be able to detect its versions.

**Comment by titusfortner** [comment]
Is this what we're looking to support with this Issue?

```
selenium-manager --browser chrome --browser-version beta
```

**Comment by bonigarcia** [comment]
My intention for this milestone was only to consider the known commands to discover the browser version, not only for stable browsers, but also for beta/dev/etc. This way, Selenium Manager tries to discover (in order) the version of the stable browser, if not found, then the beta, etc. For M3 (about configuration) we can consider to force the use of beta/dev/etc. In addition, also in M3, we can implement a flag to specify a custom location for the browser (I did something similar in WebDriverManager).

**Comment by titusfortner** [comment]
I agree we need to implement the flag to specify a custom location for the browser.

I was thinking this feature would be a way to ask selenium-manager to auto-locate bea/dev/canary without having to pass in the location directly.

I don't think selenium-manager should use non-production browseer unless a user specifies it.

**Comment by titusfortner** [comment]
Discussion in TLC meeting was not to automatically use a non-prod version of a browser unless explicitly requested. Detection of non-prod browsers will be a nice feature for users to specify instead of specific versions.

**Comment by bonigarcia** [comment]
Completed with #11334.
