### ISSUE TITLE
[🐛 Bug]: Driver.Manage().Logs.GetLog(LogType.Browser) is not working for Firefox browser.

### ISSUE THREAD

**Issue by TsvetanIlchev** [SeleniumHQ/selenium#11232]
### What happened?

Browser: Firefox
Browser Version: 106.0.5 (64-bit)
Selenium.WebDriver.GeckoDriver.Win64 version: 0.32.0

Browser: Chrome 107.0.5304.88 
Browser Version: 106.0.5 (64-bit)
Selenium.WebDriver.ChromeDriver version: 107.0.5304.6200

Selenium C# version: 4.6.0

======Description======
I'm trying to get everything that is logged into the browser's console on Firefox, but unfortunately the following is returning 0 entries as count:

            FirefoxOptions options = new FirefoxOptions();
            options.SetLoggingPreference(LogType.Browser, LogLevel.All);
            var driver = new FirefoxDriver(options);

            driver.Navigate().GoToUrl("https://community.rsa.com/t5/community-support-knowledge-base/how-to-capture-a-web-browser-console-log-for-troubleshooting/ta-p/6966");
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);

            var entries = driver.Manage().Logs.GetLog(LogType.Browser);

            foreach (var entry in entries)
            {
                Console.WriteLine($"Firefox {entry}");
            }

If I do the same for Chrome, everything is fine:

            ChromeOptions options2 = new ChromeOptions();
            options2.SetLoggingPreference(LogType.Browser, LogLevel.All);
            var driver2 = new ChromeDriver(options2);

            driver2.Navigate().GoToUrl("https://community.rsa.com/t5/community-support-knowledge-base/how-to-capture-a-web-browser-console-log-for-troubleshooting/ta-p/6966");
            driver2.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);

            var entries2 = driver2.Manage().Logs.GetLog(LogType.Browser);
            
            foreach (var entry in entries2)
            {
                Console.WriteLine($"Chrome {entry}");
            }

### How can we reproduce the issue?

```shell
Use this:
            FirefoxOptions options = new FirefoxOptions();
            options.SetLoggingPreference(LogType.Browser, LogLevel.All);

            var driver = new FirefoxDriver(options);

            driver.Navigate().GoToUrl("https://community.rsa.com/t5/community-support-knowledge-base/how-to-capture-a-web-browser-console-log-for-troubleshooting/ta-p/6966");
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);

            var entries = driver.Manage().Logs.GetLog(LogType.Browser);

            foreach (var entry in entries)
            {
                Console.WriteLine($"Firefox {entry}");
            }
```

### Relevant log output

```shell
No output.
```

### Operating System

Windows 10

### Selenium version

DotNet 6

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.88, Firefox 106.0.5 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver version: 107.0.5304.6200, GeckoDriver.Win64 version: 0.32.0

**Comment by diemol** [comment]
Firefox does not have logs in the same way Chrome does. 

Different browser vendors are working with the Selenium project to have that feature in a standard way, there are already some bits of the functionality there, but we need to wait some more time to have it in Firefox as well. Please follow the development at https://github.com/w3c/webdriver-bidi
