### ISSUE TITLE
Cannot schedule concurrent requests

### ISSUE THREAD

**Issue by DanielHeath** [SeleniumHQ/selenium#1124]
I'm using selenium-webdriver with a remote driver, with relatively high (seconds) latency.

One of the things our tests do is request a bunch of elements by CSS, then call getText() on each of them.
Because element.getText() schedules a command in the flow, each of these commands runs in series.
I think commands which do not mutate the page (findElement, getText etc) should run in parallel.

**Comment by jleyba** [comment]
This is working as intended. `getText()` may not modify the page, but it depends on the state of the page and any other actions you make. That said, `2.48.0` will include changes that will make it easier to schedule concurrent actions. I'm hoping to push the release this weekend.

**Comment by DanielHeath** [comment]
Unless I'm missing something, a `getText()` followed immediately by another `getText()` can be safely rolled into a single operation.
