### ISSUE TITLE
[🐛 Bug]: Get log doesn't return log from an iframe

### ISSUE THREAD

**Issue by Reksa97** [SeleniumHQ/selenium#11242]
### What happened?

I was trying to write a test for checking that an application doesn't log any errors to the browser console.
The issue seems to be that it is inside an iframe, as the logs from outside of it are returned correctly.

I added a python code snippet for reproducing this. I used iframetester.com to embed my [sample app](https://github.com/Reksa97/Reksa97.github.io/blob/main/index.html) which logs to browser console every second.

As you can see from the logs, only the top level logs are returned and the ones coming from the iframe are lost.
Can this be fixed or do we need to do manual testing in this case?

### How can we reproduce the issue?

```shell
import time
from selenium import webdriver, __version__ as selenium_version

print(f'selenium version: {selenium_version}\n')

options = webdriver.ChromeOptions()
options.add_argument('--auto-open-devtools-for-tabs')
capabilities = webdriver.DesiredCapabilities.CHROME.copy()
capabilities['goog:loggingPrefs'] = {'browser': 'ALL'}

# get log when log comes from iframe
driver = webdriver.Chrome(options=options, desired_capabilities=capabilities)
driver.get("https://iframetester.com/?url=https://reksa97.github.io/")
# wait until iframe is loaded
time.sleep(10)
driver.execute_script('console.log("log outside of iframe")') # is caught by get_log
driver.switch_to.frame('iframe-window')
driver.execute_script('console.log("log in iframe")') # not caught by get_log
print('log with iframe')
for log in driver.get_log('browser'):
    print(log)

# get log straight from the website, no iframe, no problem
driver.get("https://reksa97.github.io/")
time.sleep(10)
print('\nlog without iframe')
for log in driver.get_log('browser'):
    print(log)

driver.close()
```

### Relevant log output

```shell
selenium version: 4.6.0

log with iframe
{'level': 'INFO', 'message': 'https://iframetester.com/js/index.js 105:12 "iframe loaded"', 'source': 'console-api', 'timestamp': 1667917206781}
{'level': 'INFO', 'message': 'console-api 2:32 "log outside of iframe"', 'source': 'console-api', 'timestamp': 1667917216814}

log without iframe
{'level': 'WARNING', 'message': "security - Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", 'source': 'security', 'timestamp': 1667917217036}
{'level': 'SEVERE', 'message': 'https://reksa97.github.io/favicon.ico - Failed to load resource: the server responded with a status of 404 ()', 'source': 'network', 'timestamp': 1667917217171}
{'level': 'INFO', 'message': 'https://reksa97.github.io/ 2:12 "loop" 0', 'source': 'console-api', 'timestamp': 1667917218933}
{'level': 'INFO', 'message': 'https://reksa97.github.io/ 2:12 "loop" 1', 'source': 'console-api', 'timestamp': 1667917221578}
{'level': 'INFO', 'message': 'https://reksa97.github.io/ 2:12 "loop" 2', 'source': 'console-api', 'timestamp': 1667917223016}
{'level': 'INFO', 'message': 'https://reksa97.github.io/ 2:12 "loop" 3', 'source': 'console-api', 'timestamp': 1667917225513}
```

### Operating System

macOS Ventura

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.87 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62 (1eec40d3a5764881c92085aaee66d25075c159aa-refs/branch-heads/5304@{#942})

**Comment by titusfortner** [comment]
the browsers are what decides what to store and provide in their logs, so to the extent it is a problem, it needs to be addressed by Google.

Also, you might want to check out the new BiDi implementation for console logs:
https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/?language=python#listen-to-consolelog-events
