### ISSUE TITLE
[🐛 Bug]: driver.Manage().Cookies.AddCookie is not adding expiry and adding additional character for domain

### ISSUE THREAD

**Issue by samkhayal** [SeleniumHQ/selenium#11246]
### What happened?

so i am trying to set a cookie in chrome using selenium webdriver c# to bypass sso authentication. however after the cookie is set i found an additional character is added to the domain and the expiry is set as null 

 cookie1Dictionary.Add("domain", "somesite.com");
            cookie1Dictionary.Add("path", "/");
            cookie1Dictionary.Add("expiry", expirationdate.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"));            
            cookie1Dictionary.Add("secure", true);
            cookie1Dictionary.Add("isHttpOnly", false);
            cookie1Dictionary.Add("sameSite", "None");

            //***********************************
            var cookie1 = Cookie.FromDictionary(cookie1Dictionary);
            
            driver.Manage().Cookies.AddCookie(cookie1);
after running the script i checked the cookie and i found out that domain has an extra . in front of the domain so the domain is .somesite.com and expiry is session / null
is this an issue with chrome ?

### How can we reproduce the issue?

```shell
cookie1Dictionary.Add("domain", "google.com");
            cookie1Dictionary.Add("path", "/");
            cookie1Dictionary.Add("expiry", expirationdate.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"));            
            cookie1Dictionary.Add("secure", true);
            cookie1Dictionary.Add("isHttpOnly", false);
            cookie1Dictionary.Add("sameSite", "None");

            //***********************************
            var cookie1 = Cookie.FromDictionary(cookie1Dictionary);
            
           driver.Manage().Cookies.AddCookie(cookie1);
```

### Relevant log output

```shell
na
```

### Operating System

windows 10 

### Selenium version

4.1.1 and 4.6

### What are the browser(s) and version(s) where you see this issue?

chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 107

**Comment by diemol** [comment]
Are you navigating to the domain first? I do not see that in the code provided.

**Comment by samkhayal** [comment]
driver.Navigate().GoToUrl("https://stg-dd.somesite.com/welcome");
            Thread.Sleep(1000);

var cookies = driver.Manage().Cookies.AllCookies;

            DateTime currentTime = DateTime.Now;
            DateTime expirationdate = currentTime.AddHours(7);

            var cookie1Dictionary = new System.Collections.Generic.Dictionary<string, object>();

cookie1Dictionary.Add("domain", "google.com");
            cookie1Dictionary.Add("path", "/");
            cookie1Dictionary.Add("expiry", expirationdate.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"));            
            cookie1Dictionary.Add("secure", true);
            cookie1Dictionary.Add("isHttpOnly", false);
            cookie1Dictionary.Add("sameSite", "None");

            //***********************************
            var cookie1 = Cookie.FromDictionary(cookie1Dictionary);
            
           driver.Manage().Cookies.AddCookie(cookie1);
driver.Navigate().GoToUrl("https://stg-dd.somesite.com/login");

**Comment by diemol** [comment]
You need to navigate first to the site where you want to create a cookie
https://www.selenium.dev/documentation/webdriver/interactions/cookies/#add-cookie

**Comment by samkhayal** [comment]
Diemol , i am doing that and still not adding the cookie. not sure why you closed this ticket without reading the code above.
i am navigating to the welcome page and before going to login, i am attemtping to set the cookie. the cookie name is getting set  , the expiry is set as session/null and for the domain it is adding an additional character. did you even read the original post/issue ?

putting it back here ,
driver.Navigate().GoToUrl("https://stg-dd.somesite.com/welcome");
Thread.Sleep(1000);

var cookies = driver.Manage().Cookies.AllCookies;

        DateTime currentTime = DateTime.Now;
        DateTime expirationdate = currentTime.AddHours(7);

        var cookie1Dictionary = new System.Collections.Generic.Dictionary<string, object>();
cookie1Dictionary.Add("domain", "google.com");
cookie1Dictionary.Add("path", "/");
cookie1Dictionary.Add("expiry", expirationdate.ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff'Z'"));
cookie1Dictionary.Add("secure", true);
cookie1Dictionary.Add("isHttpOnly", false);
cookie1Dictionary.Add("sameSite", "None");

        //***********************************
        var cookie1 = Cookie.FromDictionary(cookie1Dictionary);
        
       driver.Manage().Cookies.AddCookie(cookie1);
driver.Navigate().GoToUrl("https://stg-dd.somesite.com/login");

https://github.com/SeleniumHQ/selenium/labels/R-awaiting%20answer
https://github.com/SeleniumHQ/selenium/labels/C-dotnet
https://github.com/SeleniumHQ/selenium/labels/I-defect

**Comment by diemol** [comment]
Because you are trying to set a cookie on `google.com` but you have not visited the `google.com` domain. Please have a look at the link I shared from the docs.

**Comment by samkhayal** [comment]
driver.Navigate().GoToUrl("https://stg-dd.somesite.com/welcome");

driver.Navigate().GoToUrl("https://stg-dd.somesite.com/login");

are these two domains different ?

**Comment by samkhayal** [comment]
![image](https://user-images.githubusercontent.com/50032073/201359196-c72628f8-697f-4b99-b9b8-249596bb932b.png)

**Comment by samkhayal** [comment]
do you see what is not getting set ? the domain and the expires

**Comment by samkhayal** [comment]
> Because you are trying to set a cookie on `google.com` but you have not visited the `google.com` domain. Please have a look at the link I shared from the docs.

I am following the documentation although the documentation was not clear about going to domain first an then go to login :).

**Comment by titusfortner** [comment]
fwiw, the documentation clearly says:
> First of all, you need to be on the domain that the cookie will be valid for.

**Comment by samkhayal** [comment]
which is this one https://stg-dd.somesite.com right ? i am going to the welcome page cause if i go to this domain it will take me directly to the /login therefore i am going to /welcome which also on the same domain stg-dd.somesite.com. but as you see in the screenshot there is an additional .added to the domain i am not sure where it is coming from

**Comment by samkhayal** [comment]
why is it adding an extra dot to the domain ?
