### ISSUE TITLE
[🐛 Bug]:  Node not registering on Hub on AWS Ec2

### ISSUE THREAD

**Issue by IssamDerHirte** [SeleniumHQ/selenium#11247]
### What happened?

I created a Ec2 Instance. Iable to create a hub but when I'm trying to register the node machine,  it only giving the [NodeServer$1.lambda$start$1] - Sending registration event.

I tried everything to fix this, but everything I tried failed.
If I try to add a node on the same IP I have the Hub on everything works fine, but as soon as I try it on a remote server it doesnt work.

I even tried to open the ports:
![image](https://user-images.githubusercontent.com/62181177/200955400-e221ce06-f202-4559-b97c-18a62be7477a.png)

Here a screen of the cmd:
![image](https://user-images.githubusercontent.com/62181177/200955022-0adb3703-be7a-4245-9dc7-d7877df282cc.png)

Registered Hub:
![image](https://user-images.githubusercontent.com/62181177/200955852-7303a342-d591-4e29-9b00-7eb4458b8097.png)

I am already extremely frustrated and dont know what to do, I'm already several days on the error.

### How can we reproduce the issue?

```shell
Local machine
java -jar selenium-server-4.6.0.jar hub

On Machine 2
java -jar selenium-server-4.6.0.jar node --hub http://192.168.0.43:4444
```

### Relevant log output

```shell
Logs on screens
```

### Operating System

Windows 10

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

**Comment by diemol** [comment]
You need to expose the Bus ports when the Hub and Nodes are running on different machines. https://www.selenium.dev/documentation/grid/getting_started/#node-and-hub-on-different-machines
