### ISSUE TITLE
[🚀 Feature]: Use Process.spawn instead of the child_process gem

### ISSUE THREAD

**Issue by eregon** [SeleniumHQ/selenium#11251]
### Feature and motivation

Since selenium is Ruby 2.7+ it can use Process.spawn which exists since 2.4.
Process.spawn covers the whole API of child_process, so there is no need for that dependency and it should be fairly easy to remove it.
`child_process` is unfortunately not very actively maintained, and that causes issues, for instance https://github.com/oracle/truffleruby/issues/1525 / https://github.com/enkessler/childprocess/issues/172.

### Usage example

As a result, selenium would have 1 less dependency, one less piece of highly platform-dependent code, and runs better on more platforms.

**Comment by eregon** [comment]
Another advantage is `Process.spawn` is faster than fork+exec s used by `child_process`, because that can use vfork() or posix_spawn for instance.

**Comment by p0deje** [comment]
Let's see how it goes, I've also added TruffleRuby to the list of Rubies for unit tests on CI https://github.com/SeleniumHQ/selenium/commit/04ede9e6f163de7d67aaf702caab8b663069f493

**Comment by eregon** [comment]
Thank you, that was fast!

I see the CI failed at https://github.com/SeleniumHQ/selenium/actions/runs/3448105944/jobs/5754819891
It seems `LANG` is not set or set to `C`, and `HOME` is not set either. Are those variables unset on purpose?

**Comment by p0deje** [comment]
I've fixed it in https://github.com/SeleniumHQ/selenium/commit/a2d76326d7c0c04ab29b54345bd855004c544418. Those variables are unset by default by Bazel, so I had to explicitly propagate them. I suppose TruffleRuby also suffers from https://github.com/jruby/jruby/issues/5661

**Comment by eregon** [comment]
Thank you, I've filed https://github.com/oracle/truffleruby/issues/2784 to account for that.
I'm rather surprised Bazel changes the ENV like this, but that's how it is.

And with your change it seems like TruffleRuby passes the test suite, nice! https://github.com/SeleniumHQ/selenium/actions/runs/3460208424/jobs/5776525182

**Comment by p0deje** [comment]
Bazel unsets everything in ENV by default to make builds more hermetic.
