### ISSUE TITLE
[🐛 Bug]: Proxy authentication not working

### ISSUE THREAD

**Issue by samacm** [SeleniumHQ/selenium#11254]
### What happened?

We have tried with many possible options for proxy authentication. But still we are not able to authenticate URL's via Proxy

Test 1:
 proxy = new Proxy();
 proxy.setHttpProxy("192.168.0.500");
            proxy.setSocksUsername("test");
            proxy.setSocksPassword("123456789");
            //Add the proxy to our capabilities 
            capabilities.setCapability("proxy", proxy);
            //Start a new ChromeDriver using the capabilities object we created and added the proxy to
            driver = new ChromeDriver(capabilities);

We are getting This site cannot be reached error.

Test 2: we tried with socks proxy
We are getting This site cannot be reached error.

Test 3 : We tried passing credentials in URL.
We are getting This site cannot be reached error.

Test 4: Adding chrome add-on and attaching manifest.json (referred from one of the python implementation in goolge)
Cannot read manifest

### How can we reproduce the issue?

```shell
Try to launch URL which is behind proxy and pass authentication.
```

### Relevant log output

```shell
NA
```

### Operating System

Windows10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 106

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Didn't get more information, we'll treat this as a question.
