### ISSUE TITLE
Selenium webdriver working in code but not responding in IIS

### ISSUE THREAD

**Issue by VarshaMarkale** [SeleniumHQ/selenium#1125]
I have used selenium-server-standalone-2.47.1 for C# application.

The below code is working fine in FF,but when deployed on IIS the selenium.open function is
getting hanged.

Please help.

The code is as below:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Text;
using System.Net;
using System.IO;
using OpenQA.Selenium.IE;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using System.Security.Cryptography;
using OpenQA.Selenium.Support.UI;
using Selenium;
using Selenium.Internal.SeleniumEmulation;

 protected void btncmn_Click(object sender, EventArgs e)
        {

            try
            {   
IWebDriver driver = new FirefoxDriver();
              
                String baseUrl = "http://www.google.co.in";

		 ISelenium selenium = new WebDriverBackedSelenium(driver, baseUrl);
                

                selenium.Start();

            
                WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromMinutes(30));
                
                selenium.Open("http://www.google.co.in");
                

                
                IWebDriver driverInstance = ((WebDriverBackedSelenium)selenium).UnderlyingWebDriver;
                
                selenium.Stop();

 }
            catch(Exception ex)
            {
            
                File.WriteAllText(@"F:\logerr.txt", ex.Message.ToString());
            }

            finally
            {
            }

        }

**Comment by gsampath127** [comment]
Can anyone please provide solution for this

**Comment by VarshaMarkale** [comment]
I have got the below answer in Selenium group.And I developed win application.


Answer:
Why are you deploying the test on IIS? You do know that doing so means executing Selenium UI tests on the IIS machine under the context of the user account that runs IIS.

There might be an issue with permissions and/or that the IIS user account is not associated to any graphical desktop session, so it will fail or get stuck as you observed.

You are better off just running a batch script, etc. remotely using PSExec.exe to kick off such test. And if you wanted a nice GUI wrapper on top of that, build one as a .NET desktop app rather than web app, which simply calls the script with a process command.

**Comment by gsampath127** [comment]
Thanks

But Here my requirement is to do testing of about 1 lakh urls.

So we have to create web app and perform testing based on client urls.

And the web app to deployed in iis.

Main purpose of web app is that we can perform testing from anywhere.

And genereate the reports to Client.

**Comment by rsangin** [comment]
@gsampath127 i have the exact same problem.
did you solve that?

**Comment by gsampath127** [comment]
We can not run selenium drivers in IIS . Since drivers are limited it's own
servers.so we can achieve this by using window service.
