### ISSUE TITLE
[🐛 Bug]: Manager Downloads old Chrome-Driver

### ISSUE THREAD

**Issue by MuhSchaf** [SeleniumHQ/selenium#11250]
### What happened?

After updating Selenium to version 4.6 in DotNet, the new feature "Selenium manager" downloads an old Chrome driver version.

### How can we reproduce the issue?

```shell
To reproduce:
- update on 4.6
- remove the chrome-driver path from the call to the chrome-driver-constructor
-> see log output
```

### Relevant log output

```shell
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 100
```

### Operating System

Windows 10

### Selenium version

DotNet 4.6

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

Chrome-Driver 100 (because loads old driver version)

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
That seems hard to reproduce. Are you sure there is no other ChromeDriver on the path? Because from the log it seems like Selenium Manager was not used at all.

**Comment by MuhSchaf** [comment]
Well, you are right. 
There was an old driver lying around.
I am sorry that I have opened a can of worms unnecessarily.
Thank you for your fast reply.

Be blessed and have a great day.
