### ISSUE TITLE
[🚀 Feature]: [Selenium Manager] User should have option to fallback to previous stable version of browser driver

### ISSUE THREAD

**Issue by saiparth** [SeleniumHQ/selenium#11269]
### Feature and motivation

Thanks for adding selenium manager. 
One request is, sometimes latest version of chromedriver may have some issues. Previous version of driver may work with latest version of chrome. hence rather than having blocked, User should be able to specify fallback option so that selenium will download previous stable version.
Ex: 
Chrome 106 and Chromedriver 106 - Timed out receiving message from renderer
Chrome 106 and Chromedriver 105 - works fine

Thanks

### Usage example

I should be able to specify browser driver version or Boolean flag to fallback to previous stable version while initializing browser.

**Comment by diemol** [comment]
That is a feature that we need to double check because it is not a common case but for now you can always set the location [of your driver](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#4-hard-coded-location), as Selenium Manager is a fallback for now.

@titusfortner @bonigarcia thoughts?

**Comment by bonigarcia** [comment]
I had never heard about this need. Although technically, it is possible to use the previous stable version of a given browser with Selenium Manager, I think this is not the best approach.

Selenium Manager uses the recommended driver version for a given browser. For instance, for Chrome 106, the official chromedriver version should be 106.0.5249.61 (see the [chomedriver download page](https://chromedriver.chromium.org/downloads)). If chromedriver 106.x has some problem that does not happen in version 105.x, maybe it is worth reporting it (see [chomedriver contributing page](https://chromedriver.chromium.org/contributing)).

**Comment by diemol** [comment]
I think that is a good point, and in any case, I believe we won't change the interface drastically when Selenium Manager is the default in Selenium, users should be able to set the location of the driver.

**Comment by titusfortner** [comment]
This is a legit use case in either direction (newer or older versions).
The Selenium Manager already supports this, but the bindings do not.

This will give the location of that driver regardless of the browser version.
```
selenium-manger --browser chrome --driver-version 106.0.5249.61
```

The languages need to provide access to this functionality, though.

We should discuss how we want users to pass this info in for future versions of Selenium, I don't think we need to wait for it to be the default implementation to get this to work.

**Comment by titusfortner** [comment]
I think how we do this will be determined by #11353.
If there is any specific outcomes from this one, please provide input there.
