### ISSUE TITLE
Selenium problems with detecting tabs/windows on Firefox 41.0.1

### ISSUE THREAD

**Issue by itsenov** [SeleniumHQ/selenium#1126]
Currently no matter if you have several tabs opened in latest Firefox, Selenium sees them as only one.

Before when I use driver.close it close the current window but not the browser if there are more tabs like it's described -> https://i.gyazo.com/70d4984d0ba63e15b534b650903f9fb7.png
but right now it close the whole Firefox instance.

Also if I try to switch to another Window (tab) it's not happening since it detect that I have only one tab (which is wrong).

**Comment by yankoBede** [comment]
I met the same issue on my side :(

**Comment by barancev** [comment]
Tabs are explicitly not supported in FirefoxDriver.
