### ISSUE TITLE
[🐛 Bug]: Memory leak by creating multiple HttpClient-*-SelectorManager  threads when using jdk11 http client in loop with selenium grid

### ISSUE THREAD

**Issue by pogrebnyaksa** [SeleniumHQ/selenium#11270]
### What happened?

I experience memory leak in my app - selenium spawns multiple threads.

### How can we reproduce the issue?

```shell
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <selenium.version>4.6.0</selenium.version>
        <lombok.version>1.18.24</lombok.version>
        <spring-web.version>5.3.23</spring-web.version>
        <jackson-databind.version>2.14.0</jackson-databind.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-devtools-v107</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-http-jdk-client</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.springframework/spring-web -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring-web.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-databind.version}</version>
        </dependency>



        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>



    
    @SneakyThrows
    public static void main(String[] args) {
        System.setProperty("webdriver.http.factory", "jdk-http-client");

        while (true) {
            WebDriver driver = null;
            try {
                ChromeOptions chromeOptions = new ChromeOptions();
                chromeOptions.setHeadless(false);
                chromeOptions.addArguments(
                        "--ignore-certificate-errors",
                        "--auto-open-devtools-for-tabs"
                );
                driver = RemoteWebDriver.builder()
                        .augmentUsing(new Augmenter())
                        .oneOf(chromeOptions)
                        .address(GRID_URL)
                        .build();
                driver.get("http://example.com/");
            } catch (Exception e) {
                log.info("Exception ", e);
            } finally{
                if (driver != null) {
                    driver.quit();
                }
            }

            TimeUnit.SECONDS.sleep(5);
        }
    }

If you make thread dumps periodically - you can see that number of HttpClient-*-SelectorManager threads is increasing rather quickly (in 5 minutes I see 90 threads).
```

### Relevant log output

```shell
no log output required
```

### Operating System

Debian 9, Ubuntu 20.04.3

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

chrome 107.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62

### Are you using Selenium Grid?

Yes, 4.6.0

**Comment by diemol** [comment]
Also, some evidence and graphs showing the leak would be very helpful to troubleshoot this.

**Comment by joerg1985** [comment]
@pogrebnyaksa 
could you replace the `TimeUnit.SECONDS.sleep(5);` with a `System.gc(); ` call?
The selector threads should stop when GC is triggered.

In the real world the GC should automatically run after some time.
The loop does not generate enought trash to make it run automatically ;)

**Comment by pogrebnyaksa** [comment]
> Also, some evidence and graphs showing the leak would be very helpful to troubleshoot this.

Please, look into repo [https://github.com/pogrebnyaksa/selenium-repo](https://github.com/pogrebnyaksa/selenium-repo).
There you can find sources, threaddumps and screenshoot with threads increasing.

**Comment by pogrebnyaksa** [comment]
> @pogrebnyaksa could you replace the `TimeUnit.SECONDS.sleep(5);` with a `System.gc(); ` call? The selector threads should stop when GC is triggered.
> 
> In the real world the GC should automatically run after some time. The loop does not generate enought trash to make it run automatically ;)

You are right, manual call GC cleans all hanging threads from jdk11 http client, but it is not normal to spawn such huge amount of threads until GC clean them all. I have reached 700 of threads and that's not the end - it pollutes thread dumps and makes monitoring of service more complicated. Also I think it is a good practice to shutdown threads when they are not needed any more

**Comment by joerg1985** [comment]
@pogrebnyaksa I agree a graceful shutdown is good practice and Selenium has a mechanism to clear unused clients.
But there is no way to stop a single java HttpClient, this is usually done automatically.

I created a PR to call `System.gc()` when a client is not in use any more. 
This should help in your case, but i am not sure if they will merge it.

**Comment by titusfortner** [comment]
Is this a Java issue or a Rust issue? The Java code for Selenium Manager does not do anything with http commands directly, that's all in the selenium-manager executable.

**Comment by diemol** [comment]
This is not related to Selenium Manager.

**Comment by titusfortner** [comment]
Sigh. Selector Manager. Sorry. Thanks.
