### ISSUE TITLE
[🚀 Feature]: let the UnreachableBrowserException not leak details of the command

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#11275]
### Motivation
If a `UnreachableBrowserException` is raised in a sensitive area there will be sensitive information in the logs.

e.g. the basic-auth infos are leaked here
```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'
Driver info: com.my.company.ta.driver.factory.SeleniumDrivers$2
Command: [4ade0fd2dd7fa0b55833438a7af7386d, get {url=https://user:password@mysavedomain.com/}]
Capabilities ...
Session ID: 4ade0fd2dd7fa0b55833438a7af7386d
Caused by: java.io.UncheckedIOException: java.net.http.HttpTimeoutException: request timed out
Caused by: java.net.http.HttpTimeoutException: request timed out
```

### Feature
There are several options to ensure the parameters are not logged in the CI pipeline:

a) Modify the `UnreachableBrowserException` to only contain the parameter values if `org.openqa.selenium.internal.Debug.IS_DEBUG` is set to true. In other cases it should be enought to know the names of the parameters send.

b) Modify the UnreachableBrowserException to respect a new system property e.g. `org.openqa.selenium.SUPPRESS_COMMAND_PARAMETERS`. If this flag is set only dump the name of the parameters set.

### Usage example

We are using encryption to ensure secrets are not visible to regular users in our continuous integration pipeline.
E.g. a Jenkins user can view the logs & workspace, but there are only encrypted secrets.
The logging will also ensure there are no secrets shown in the build logs.

A UnreachableBrowserException will currently leak this informations to regular users usually not able to read this informations.

**Comment by diemol** [comment]
Thank you, @joerg1985. Good catch. This makes sense. I believe option a would be more suitable.

**Comment by debanjanc01** [comment]
Hey @diemol! I'd like to work on this issue. Option A mention above does seem like the suitable fix. Could you please assign this to me?

**Comment by diemol** [comment]
@debanjanc01 we usually don't assign issues because that limits the people who want to contribute. Just commenting here is enough. Feel free to send us a PR.

**Comment by debanjanc01** [comment]
Hey @diemol , I am unable to figure out how to mock the behaviour of `org.openqa.selenium.internal.Debug.isDebugging` inside `RemoteWebDriverUnitTest.java`. The idea is to test out that command parameters are a part of the exception log only when the debug is `true`. 
Is there some `Capabilities` that could be passed in while creating the `WebDriverFixture`?
Could you please provide some guidance here?

**Comment by krmahadevan** [comment]
@debanjanc01 - You can try something like this.

First define a handler like this

```java
  public static Function<Command, Response> unreachableBrowser(Supplier<Boolean> supplier) {
    return cmd -> {
      if (supplier.get()) {
        throw new RuntimeException("I am a problem");
      }
      return echoCapabilities.apply(cmd);
    };
  }
```

Now if you have a test that looks like below, you should be able to trigger that exception

```java
  @Test
  void sampleTest() {
    final AtomicBoolean flag = new AtomicBoolean(false);
    Supplier<Boolean> supplier = () -> {
      boolean toReturn = flag.get();
      flag.set(!flag.get());
      return toReturn;
    };
    WebDriverFixture fixture = new WebDriverFixture(
      new ImmutableCapabilities("browserName", "cheese"),
      unreachableBrowser(supplier)
    );
    fixture.driver.get("http://localhost:1234");
  }
```

You would have to enhance 

* the test to include the JVM argument enabling/disabling (maybe within a `try..catch` so that you can reset it back after the test runs to completion) and also use the assertion that verifies the exception.. something like below

```java
    assertThatExceptionOfType(WebDriverException.class)
      .isThrownBy(fixture.driver::getCurrentUrl)
      .withMessageStartingWith("BOOM!!!")
      .withMessageContaining("Build info: ")
```

Hope that helps!

**Comment by debanjanc01** [comment]
Hey @krmahadevan thanks for the detailed input! 

Could you please elaborate on the below?
> You would have to enhance the test to include the JVM argument enabling/disabling

The problem here is `org.openqa.selenium.internal.Debug#isDebugging` - this is a static method. Currently the `Mockito.mockStatic` is not supported in the codebase.

Even if I set the system property explicitly, since the `Debug` class has a static block, the system property is persisted throughout all the test cases and not just a single test.

**Comment by krmahadevan** [comment]
@debanjanc01 - The following steps can be followed ( The exact correctness of them will be determined only by someone who is more Bazel educated). These steps got the below test to  pass.

My sample test case

```java
  @Test
  public void exampleTest() {
    try (MockedStatic<Debug> debugMock = Mockito.mockStatic(Debug.class)) {
      debugMock.when(Debug::isDebugging).thenReturn(true);
      assertThat(Debug.isDebugging()).isTrue();
    }
  }
```

Steps that I followed:

1. After [this](https://github.com/SeleniumHQ/selenium/blob/trunk/java/maven_deps.bzl#L98) I added `"org.mockito:mockito-inline:4.8.1",`
2. Now I opened up a terminal and ran the command `REPIN=1 bazel run @unpinned_maven//:pin` This command will take sometime.
3. Now I went back and added `artifact("org.mockito:mockito-inline"),` after [this](https://github.com/SeleniumHQ/selenium/blob/trunk/java/test/org/openqa/selenium/remote/BUILD.bazel#L35) line.
4. When I ran the above cited test, it worked.

Hope that helps!

**Comment by debanjanc01** [comment]
@krmahadevan this is exactly what I was planning to do. Thanks for adding the detailed steps on here as well. 

Since I'm new to the codebase I'm not sure if adding the mockito-inline dependency is something advisable/something I should be doing.

**Comment by krmahadevan** [comment]
> Since I'm new to the codebase I'm not sure if adding the mockito-inline dependency is something advisable/something I should be doing.

The best way to find that out is by having someone from the dev group review it for you :) 

Personally speaking, adding this dependency would be the straight forward way of getting past this mockito roadblock. The round about way to do this would be to alter the `Debug` class and then provide a `reset()` and a `reinitialize()` methods in it, for the sake of testing. I dont know if that's something that would be welcome.

**Comment by debanjanc01** [comment]
@krmahadevan I agree with this that adding the dependency is the easier solution here. 

I'll take your advise and wait for the feedback by the dev group. :) 

Thanks for all the help!

**Comment by debanjanc01** [comment]
Hey guys, wanted to check if someone from the dev team had the chance to take a look at this.
