### ISSUE TITLE
[🚀 Feature]: Publish index of released assets

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11280]
### Feature and motivation

Right now users need to use GithubAPI to parse our released assets: https://github.com/SeleniumHQ/selenium/releases

We could publish an xml/json file (similar to https://chromedriver.storage.googleapis.com/) to make it easier for people to determine the location of a specific version of their desired asset.

We should be able to auto-generate this file using Github API via Github Actions.

### Usage example

People can already use this if they need - https://api.github.com/repos/seleniumhq/selenium/releases

But it would be nice if it were more minimal and perhaps organized by Asset (e.g., Grid, IEDriver 32) rather than by version

**Comment by diemol** [comment]
We have now https://github.com/SeleniumHQ/selenium/blob/trunk/common/mirror/selenium, which can be accessed without dealing with the GitHub API quota limit through https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/mirror/selenium. Closing this.
