### ISSUE TITLE
Firefox binaries at custom paths don't work on mac

### ISSUE THREAD

**Issue by dwt** [SeleniumHQ/selenium#1128]
Hi there,

quite a few developers (myself included) have their firefox binaries not at /Applications/Firefox but somewhere else.

Thats way https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_binary.py#L145 doesn't work for me.

Now I've solved this for my projects by monkey patching selenium to make it ask the system where firefox is instead of assuming it is in /Applications.

That looks something like this:

```python
class Monkey(object):
    def patch(self):
        import sys
        if not sys.platform.startswith('darwin'):
            return
        def find_firefox_path(self):
            from subprocess import check_output
            import os
            firefox_path = check_output(["mdfind", "kMDItemFSName = Firefox.app"]).decode('utf-8').strip()
            return os.path.join(firefox_path, "Contents/MacOS/firefox-bin")
        from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
        FirefoxBinary._get_firefox_start_cmd = find_firefox_path
Monkey().patch()
´´´

Why don't you adapt that to get into selenium proper so I don't have to monkey patch this anymore?

**Comment by lukeis** [comment]
because we provide a way for users that use non-standard firefox install locations already:

````
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
firefox_binary = FirefoxBinary(firefox_path="/Your/Sekrit/Firefox/Path")
driver = webdriver.Firefox(firefox_binary=firefox_binary)
```

**Comment by dwt** [comment]
Out of interest: On Windows you scan the registry for firefox, on linux you scan the full path - just on mac os x you only ever check /Applications/Firefox.app and that's it.

Why? You could ask the system where it has firefox installed on mac os x too if you wanted, for example via something like:

```shell
$ mdfind "kMDItemCFBundleIdentifier == 'org.mozilla.firefox'"
/Users/me/Applications/Network/Browser/Firefox.app
```

If you feel that that is too simple, you could also ask the native API for that thing, namely LaunchServices

```python
import objc
import LaunchServices
path = LaunchServices.LSFindApplicationForInfo(0, 'org.mozilla.firefox', None, None, None)[2]
print(path)
```

I'm bringing this up, because quite a lot of long time mac power users structure their /Applications folder int several subfolders for quicker access. (Or like me, prefer to have their self installed apps in their home folders, so it's easier to get a working environment back when reinstalling os x as you just need to migrate the user folder)

**Comment by cgoldberg** [comment]
How about subprocess'ing the `which` command to find Firefox?  I think that should work on Linux and Mac... It's pretty standard across *nix platforms.

p.s.  dwt, Why not just provide a PR instead of opening an issue?

**Comment by lukeis** [comment]
@cgoldberg `which` doesn't work on OSX, since the Firefox.app is very seldom (if ever) on the system $PATH.

@dwt I don't mind adding the `mdfind` solution as a fallback if the path isn't specified and the firefox binary isn't found in the default location. (I say that it would be a fallback, because I wouldn't want users to end up getting unexpected behavior... when I ran that command locally, I ended up with multiple firefox app's being returned, because I had installed via brew/cask also).

**Comment by dwt** [comment]
@cgoldberg Well, I wouldn't open a pull request if I don't know beforehand that you're willing to take it. Thats why after the initial reply I worked with the downstream project splinter instead https://github.com/cobrateam/splinter/pull/437

@lukels: Yes, this should be a fallback, and I would work it in as such (if you're willing to take my pull request). I think the other platforms (linux/windows) show quite nicely how that would fit in.

As per finding multiple foxes: I think a default behavior that finds one fox if it is installed is a great first step as a fallback behavior, if it's not what you want, you can always specify a specific path.

**Comment by cgoldberg** [comment]
@dwt I'm just saying you are more likely to get a contribution merged if you say: "here, I did all the work... If you like it, just click the merge button".

After all, it takes just about as long to create an issue with code snippets as it does to just submit a real PR.  However, by forgoing the PR, you are relying on the goodwill of an existing contributor to take on the work rather than contributing yourself.

**Comment by dwt** [comment]
@cgoldberg No, for me it doesn't. Pulling this example code out of an existing project of mine is vastly faster than reading into the selenium code base, understanding how you do unit tests, checking out the project, creating a branch, building some clear commits, pushing them to github and opening a pull request here.

Especially to then discover that you maintainers actually don't want the feature and that I have just lost some 3 hours of my life.

So instead I open a bug report, see how you react. Listen to how you deal with non members of the project and then make up my mind to instead work with a downstream project of yours where they reply to the same bug report with a much more welcoming: 'hey, why don't you open a pull request for this, friend'.

Do you wonder why I've chosen to work with them instead of with you?

(initially that is, I did continue the discussion on this bug after sleeping over it).

**Comment by cgoldberg** [comment]
@dwt,

> Especially to then discover that you maintainers actually don't 
> want the feature and that I have just lost some 3 hours of my life.

The feature you implemented already existed.

> So instead I open a bug report, see how you react. 
> Listen to how you deal with non members of the project 

what exactly is a "member" of selenium project, and how were you dealt this unfairly?  I'm not a maintainer and have never joined any organization related to selenium.  I'm just a contributor.

> 'hey, why don't you open a pull request for this, friend'.

that's exactly what I asked... ("Why not just provide a PR") , which is why your response kinda baffles me.  But, my apologies if phrasing wasn't as welcoming as your accustomed to... (I can work on adding "friend" to my correspondences).

**Comment by dwt** [comment]
@cgoldberg Sorry, I probably overreacted here and I mean to apologize to you. In my above answer I was relating more to the initial answer to this bug report, which made me think that you guys probably wouldn't take on a contribution by me. I take this simple rule of thumb to gauge answers to bug reports: whoever answers to a bug report, speaks for the project, as he is much more deeply involved than I am.

But to be clear: Before I get a go ahead from maintainers that the feature I'm proposing is something they'd like to take into the project, I'm not investing any work. I learned that the hard way in the past, and I'm not repeating the mistake.

So to be clear: Dear maintainers. I'm proposing to extend the auto configuration of Selenium to work work more similar on mac to what it does on *nix and windows. Specifically, it should ask the system where Firefox is installed, if it doesn't find it at the standard location. Would you merge that?

**Comment by lukeis** [comment]
@dwt yes, I would merge that. 

Sorry if you think my initial reply was abrupt. We receive (an excessive amount of) bug reports that are either not issues or don't have steps to reproduce or in some other way are not clear what their issue is. Discussions like this are much better suited on our Google groups or on IRC.
