### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by ErgondataLucas** [SeleniumHQ/selenium#11288]
### What happened?

I'm trying to use selenium in python to work with Internet Explorer and I'm using windows 11 
When I try to open a website, the windown opens, but the script doesn't understand and after few minutes return a error about time response.

I createde the subkey in regedit: 
KEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE
DWORD value named iexplore.exe with value 0

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

ie_options = webdriver.IeOptions()
ie_options.attach_to_edge_chrome = True
ie_options.ignore_protected_mode_settings = True
ie_options.edge_executable_path = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
driver = webdriver.Ie(options=ie_options)

driver.get("http://www.bing.com")
```

### Relevant log output

```shell
self.error_handler.check_response(response)
  File "c:\ProgramData\robocorp\ht\300a73d_b1f3c24_9ba66f27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timed out waiting for page to load.
```

### Operating System

windows 11

### Selenium version

python 3.10.7 - Selenium 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Edge 107.0.1418.52

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer_x64_4.6.0

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
That happens when this is not set properly:
>On IE 7 or higher on Windows Vista, Windows 7, or Windows 10, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose “Internet Options…” from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled “Enable Protected Mode”.

2nd bullet point at https://www.selenium.dev/documentation/ie_driver_server/#required-configuration

**Comment by titusfortner** [comment]
@diemol fyi - you can't set those in Windows 11.

@ErgondataLucas this guide should help - https://titusfortner.com/2022/09/28/edge-ie-mode.html

**Comment by diemol** [comment]
Maybe that post should be part of our docs?
