### ISSUE TITLE
[🚀 Feature]: add scroll event in selenium

### ISSUE THREAD

**Issue by bysxx** [SeleniumHQ/selenium#11287]
### Feature and motivation

Puppeteer can make scroll event by mouse.wheel function,
but Selenium can't make scroll event without execute_script.. 
I think this structure is not intuitive and it would be more intuitive to incorporate features 

### Usage example

driver.scroll(deltaX, deltaY)

**Comment by diemol** [comment]
Please have a look at https://www.selenium.dev/documentation/webdriver/actions_api/

**Comment by bysxx** [comment]
I was looking at another document that was like an official document :(
