### ISSUE TITLE
[🐛 Bug]: It's No need driver.quit()

### ISSUE THREAD

**Issue by joker1024567** [SeleniumHQ/selenium#11285]
### What happened?

In the latest stable chromedvider and edgedvier，driver.quit() is No need，It closed on its own
what happen，Is this really a bug，right？

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Edge()
driver.get('https://bing.com')
element = driver.find_element(By.ID, 'sb_form_q')
element.send_keys('WebDriver')
element.submit()
time.sleep(5)
It closed on its own
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://selenium.dev")
It closed on its own
```

### Relevant log output

```shell
There are no warnings
```

### Operating System

Windows 10

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107，Edge 107

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver 107.0.1418.52；chromedriver 107.0.5304.62

**Comment by diemol** [comment]
Can you share the complete execution logs? This is very unlikely, if this was true, we would have tons of issues related to this.

**Comment by titusfortner** [comment]
Selenium cleans up after itself. When the Python program exits, the process that the driver is running in will get killed, which in turn closes the browser. If you want the browser to stay open even with the driver is stopped, you can set `detached` to `True`.

https://stackoverflow.com/a/43615712/4072371

You should still manage the quit yourself, especially if you run more than one session in the same code.
