### ISSUE TITLE
[🐛 Bug]: Selenium Manager use Proxy info from Browser Options

### ISSUE THREAD

**Issue by rupaagra** [SeleniumHQ/selenium#11294]
### What happened?

**I have tried using Selenium manager feature in selenium version 4.6. On my company network selenium manager is unable to download browser driver.** 

Earlier I was using webdriver manager on my company network to download drivers, for that I have set proxy in webdriver manager like this :
WebDriverManager.chromedriver().proxy("proxy").setup(); and it was working fine with web driver manager.

**In selenium manager is there any way to set the proxy or how selenium manager going to work on networks behind proxy?** 

I have tested  same on my personal network which does not have any firewall and proxy restriction. Selenium manager is able to download browser drivers here and I am able to execute my script without setting browser exe path.

### How can we reproduce the issue?

```shell
I have tried with below codes on network behind proxy

1. WebDriver driver = new ChromeDriver()
   driver.get("https://google.com") 

2. Tried to set proxy in chrome options
ChromeOptions options = new ChromeOptions().addArguments("--proxy-server=<Proxy url>");
WebDriver driver = new ChromeDriver(options)
driver.get("https://google.com")
```

### Relevant log output

```shell
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\Rupal\AppData\Local\Temp\1\selenium-manager1724451228000609043917808946591\selenium-manager.exe, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: driver.version: Driver
java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
                at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
                at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
                at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
                at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
                at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
```

### Operating System

Windows 10

### Selenium version

4.6

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

not able to download driver version

### Are you using Selenium Grid?

no

**Comment by bonigarcia** [comment]
The current implementation of Selenium Manager (milestone 1, M1) does not support the proxy setup. But indeed, this is a crucial feature for many users, and it is in the [roadmap](https://github.com/SeleniumHQ/selenium/tree/trunk/rust#roadmap) (for M3).

I recommend you keep using WebDriverManager until Selenium Manager M3 is released (currently, we are developing M2).

**Comment by rupaagra** [comment]
Thanks for your reply. This is really helpful for us.

**Comment by titusfortner** [comment]
The Rust portion of this was completed in #11575

I'm updating this to reflect that the bindings need to implement it.

**Comment by jay14687se** [comment]
@titusfortner Can you please let me know if the proxy feature been implemented in Selenium 4.8.3? Since the issue still persists.

**Comment by diemol** [comment]
This has not been implemented.

**Comment by titusfortner** [comment]
Now that we have the Driver Finder in all the languages, getting the proxy details from the options instance and sending it to the selenium manager binary in the bindings should be pretty easy.

@rupaagra it should also be noted that our plan for implementation would look for a proxy set in `options.setProxy(myProxyInstance)` not `--proxy-server=<Proxy url>`

@jay14687se are you using the proxy in your options class for your tests?

**Comment by jay14687se** [comment]
@titusfortner I usually set proxy for the entire JVM process using System.setProperty. I assumed this would work since all my test urls need proxy to run successfully. But looks like the current implementation looks at the options class. But I will give this a try and update on the same. Another good addition/suggestion would be to check if proxy is set on a JVM level and use it accordingly.

**Comment by titusfortner** [comment]
@diemol do you know how Selenium works with proxies set as properties? Does Selenium create a Proxy object or does the http client figure it out? I think we check environment variables in Python for this?

**Comment by mdmintz** [comment]
You can get the driver via proxy with [SeleniumBase](https://github.com/seleniumbase/SeleniumBase):

https://github.com/seleniumbase/SeleniumBase/issues/1844#issuecomment-1517218055

If you want to download a driver via proxy directly, use:
* ``sbase get DRIVER --proxy=server:port`` or ``sbase get DRIVER --proxy=user:pass@server:port``
--> Eg. ``sbase get chromedriver --proxy=user:pass@1.2.3.4:1234``

If you want tests that already use a proxy to also download the driver via the same proxy:
* ``pytest TEST.py --proxy=server:port --proxy-driver``
* ``pytest TEST.py --proxy=user:pass@server:port --proxy-driver``
(If you don't add the ``--proxy-driver`` option, the tests will still use proxy settings from ``--proxy=PROXY``, but the driver will be downloaded without using a proxy.)

**Comment by titusfortner** [comment]
This is what I was referring to earlier that the Selenium Python implementation does: https://github.com/SeleniumHQ/selenium/blob/selenium-4.9.0/py/selenium/webdriver/remote/remote_connection.py#L119-L122

**Comment by titusfortner** [comment]
the nice thing about using proxy in options is that it works for both local and remote.

**Comment by titusfortner** [comment]
Ruby implemented [ed313de](https://github.com/SeleniumHQ/selenium/commit/ed313de742b607a1636c600725d1e37c01c12bfc)

**Comment by titusfortner** [comment]
Python implemented - https://github.com/SeleniumHQ/selenium/commit/5b406700f9418b9824a214d1bf7375e94e7ac2da

**Comment by diemol** [comment]
Completed via https://github.com/SeleniumHQ/selenium/commit/ba638161e2ca7cf799bb946c51ed7904e54fbdb0

**Comment by z1rus** [comment]
hello everyone and thanks for your great work but could give me somebody an example how to use selenium manager with a proxy in python?

**Comment by titusfortner** [comment]
```py
proxy = Proxy({"proxyType": ProxyType.MANUAL})
proxy.http_proxy = "http://user:password@host:port"
options = webdriver.ChromeOptions()
options.proxy = proxy
```

**Comment by prabhuapparaju** [comment]
@titusfortner 
Can you please help me in implementing selenium manager with a proxy in Nodejs with an example.

Thanks in Advance

**Comment by titusfortner** [comment]
@prabhuapparaju this code has not been updated for Selenium 4 😞 
But I think it still works for JavaScript?
https://www.selenium.dev/documentation/webdriver/drivers/options/#proxy
