### ISSUE TITLE
[🐛 Bug]: with JSON Wire Protocol,can not get sessions info

### ISSUE THREAD

**Issue by yanchunhuo** [SeleniumHQ/selenium#11292]
### What happened?

I used the http client to request the '/sessions' interface and returned an error。

### How can we reproduce the issue?

```shell
get http://hub/sessions
```

### Relevant log output

```shell
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002fsessions",
    "stacktrace": ""
  }
}
```

### Operating System

Windows 7

### Selenium version

selenium server 4.6.0

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

107.0.5304.107

**Comment by diemol** [comment]
Please check https://www.selenium.dev/documentation/grid/advanced_features/endpoints/
