### ISSUE TITLE
Move selenium-webdriver node project into a separate GitHub repo

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#1129]
This would make it easier for people to fork it and set their fork as a dependency for their project.
npm doesn't support setting a subdirectory in a git repository as a dependency: https://github.com/npm/npm/issues/2974

**Comment by marco-c** [comment]
Forget it, I thought there wasn't a build step for the node module.

**Comment by jleyba** [comment]
`./go node:deploy` generates `build/javascript/node/selenium-webdriver`

**Comment by marco-c** [comment]
Yeah, I did that and created a repo with the build :smiley:
