### ISSUE TITLE
[🚀 Feature]: [dotnet] asynchronous

### ISSUE THREAD

**Issue by tqk2811** [SeleniumHQ/selenium#11299]
### Feature and motivation

-Set all functionality using HttpClient as async
-Synchronous function will move to used as extensions (compatible)  

Motivation: Performance, just for not create new thread per every Selenium

### Usage example

```csharp
var driver = await ChromeDriver.ConstructorAsync(chromeDriverService, chromeOptions, CommandTimeout);
....
var elements = await driver.FindElementsAsync(....);
```

Example [commit](https://github.com/tqk2811/selenium/commit/27558a0ac27fd3f24f53e0d1ea175809d63ba355)

**Comment by titusfortner** [comment]
We've discussed this internally. Doing this would essentially double our API and create a large maintenance burden on an already under-served implementation. There's a decent chance we'll create an entirely new async implementation, but it would likely come at the expense of support for the existing code base.

We'll be sure to make announcements if we decide to go this route.
