### ISSUE TITLE
Release 2.48.1 has an issue with proxies

### ISSUE THREAD

**Issue by kronar** [SeleniumHQ/selenium#1130]
There is a following configuration of grid 
Hub started with proxy class "java -cp "selenium-server-standalone.jar;proxy.jar" -role hub ...."
Node started with same proxy jar java -cp "selenium-server-standalone.jar;proxy.jar" -role node ....

After updating all  infrastructure on 2.48.1 we faced following stacktrace in log of hub

INFO   | jvm 1    | 2015/10/09 11:11:30 | java.lang.NoClassDefFoundError: Could not initialize class Proxy
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at java.lang.Class.forName(Class.java:264)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemote
Proxy.java:420)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.openqa.grid.web.servlet.RegistrationServlet.process(Registrati
onServlet.java:86)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.openqa.grid.web.servlet.RegistrationServlet.doPost(Registratio
nServlet.java:60)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.j
ava:808)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandl
er.java:587)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/10/09 11:11:30 |       at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHa

In this configuration nodes cant register on hub (Status code 500) .

I've reverted only hub down to 2.47.1 and registration process  was successfull.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
