### ISSUE TITLE
[🚀 Feature]: Support .NET Selenium Manager via Bazel

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11304]
### Feature and motivation

Unlike other bindings, we got Selenium Manager to behave the right way in the nuget package for release, but it is not properly bundled to be able to use with Bazel for testing. Might need to be a part of overall Bazel Build improvements (#10465)

### Usage example

(automatically use Selenium Manager during tests)

**Comment by diemol** [comment]
I think Java has the same problem. I deleted GeckoDriver from the PATH and tests with bazel did not run. Can you try?

**Comment by titusfortner** [comment]
Java works just fine for me with bazel. Too fine since it is getting all the drivers for some reason. :)

**Comment by diemol** [comment]
IIRC, this was implemented by the linked PR.
