### ISSUE TITLE
[🚀 Feature]: Add Remote Cache to Bazel Builds

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11306]
### Feature and motivation

@p0deje is improving caching on CI, but we can improve performance for both local & CI execution to be able to store cache remotely.

### Usage example

N/A

**Comment by p0deje** [comment]
Completed in https://github.com/SeleniumHQ/selenium/commit/87b4de808b41798c03a60f463ccf4958beff8049
