### ISSUE TITLE
[🐛 Bug]: [Exception ignored in: <function Service.__del__ at ...] Problem with Services.__del__... driver inside Class

### ISSUE THREAD

**Issue by michelmetran** [SeleniumHQ/selenium#11309]
### What happened?

I'm studying the Page Object Model (POM), to package the driver, all the features and operations needed to do scrapping... 
I used to do it through scripts, without using Class and Object Oriented Programming concepts.

However, when creating the driver in the __init__ of a Class, I get an error
*<function Service.__del__ at 0x000001AD36775CF0>*

Tested on Wi10 and PopOS 22.04. In both Operating Systems gives error.

Evaluating the __del__ function, I didn't understand why it is called, when I use the driver in the __init__ of a Class

```
def __del__(self) -> None:
    # `subprocess.Popen` doesn't send signal on `__del__`;
    # so we attempt to close the launched process when `__del__`
    # is triggered.
    # do not use globals here; interpreter shutdown may have already cleaned them up
    # and they would be `None`. This goes for anything this method is referencing internally.
    try:
        self.stop()
    except Exception:
        pass
```
<br>

I found similar error in: https://github.com/seleniumhq/selenium/issues/1504

### How can we reproduce the issue?

```shell
import time
from pathlib import Path
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from traquitanas.scrapping import gecko # To Download Gecko Driver and Get Path to Gecko

# Base Path
project_path = Path(__file__).absolute().parents[1]
print(project_path)

# Create Paths
scrapy_path = project_path / 'scrapy'
scrapy_path.mkdir(exist_ok=True)

driver_path = scrapy_path / 'driver'
driver_path.mkdir(exist_ok=True)

logs_path = scrapy_path / 'logs'
logs_path.mkdir(exist_ok=True)

# Set Class
class Driver:
    def __init__(self, driver_path, logs_path):
        # Services
        service = FirefoxService(
            executable_path=gecko.get_path_geckodriver(
                driver_path, verify_ssl=True
            ),
            log_path=logs_path / 'geckodriver.log',
        )

        # Driver
        self._driver = webdriver.Firefox(service=service)

    def login(self, url):
        # Get URL
        self._driver.get(url)

    def fechar(self):
        self._driver.quit()


# Classe
page = Driver(driver_path, logs_path)
page.login('https://github.com/')

# Do Something

# Close Connection
time.sleep(2)
page.fechar()
```

### Relevant log output

```shell
Exception ignored in: <function Service.__del__ at 0x0000023A31F39CF0>
Traceback (most recent call last):
  File "C:\Users\michelsilva\Documents\Apps\Miniconda\envs\pablocarreira-lastest\lib\site-packages\selenium\webdriver\common\service.py", line 177, in __del__
AttributeError: 'NoneType' object has no attribute 'suppress'
```

### Operating System

Windows 10 or PopOS 22.04

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 107.0 64 bits

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver  0.32

### Are you using Selenium Grid?

No

**Comment by mdmintz** [comment]
Fix was committed here: https://github.com/SeleniumHQ/selenium/commit/1d5210a838f559398f7ce33fb9026160f931610d but not yet released.

**Comment by michelmetran** [comment]
Thank you for the information!!

**Comment by mdmintz** [comment]
Released in https://pypi.org/project/selenium/4.6.1/ a few minutes ago. This ticket can be closed.

**Comment by michelmetran** [comment]
Tks,
Already tested! 
Not more errors!!!
