### ISSUE TITLE
[🚀 Feature]: write in docs about `se:cdp` capability

### ISSUE THREAD

**Issue by DudaGod** [SeleniumHQ/selenium#11318]
### Feature and motivation

In documentation https://www.selenium.dev/documentation/ I can't find anything about capability `se:cdp`. Found only in changelog - https://github.com/SeleniumHQ/selenium/blob/79f1c02ae20c359daa5652d790894d5e4e24d93f/java/CHANGELOG#L344-L346. Moreover there are another `se:cdp*` capabilities.

Can we describe it?

### Usage example

I want to connect to cdp by myself. But I can't find anything about these capabilities in documentation.

**Comment by titusfortner** [comment]
There's nothing user-facing with this capability. The grid adds the value to the capabilities, so the bindings know the correct version to use. You can connect to cdp using the various executeCDP / devtools methods here - https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/
