### ISSUE TITLE
[🚀 Feature]: Not support multiple environment, by using params  webPreferences-> partition

### ISSUE THREAD

**Issue by onlyis** [SeleniumHQ/selenium#11321]
### Feature and motivation

[🚀 Feature]: Not support multiple environment, by using params  webPreferences-> partition

### Usage example

it can be use multiple environment in chrome account

**Comment by titusfortner** [comment]
I don't know what this means, can you clarify or provide examples?

**Comment by diemol** [comment]
Closing as we did not get more information.
