### ISSUE TITLE
[🐛 Bug]: Not support option (prefs -> partition) but i find it on the doc,this version not support it to handle multiple account environment

### ISSUE THREAD

**Issue by onlyis** [SeleniumHQ/selenium#11322]
### What happened?

not support it to handle multiple account environment

### How can we reproduce the issue?

```shell
Map<String, Object> prefs = new HashMap<String, Object>();
        prefs.put("partition", "persist:random22");
        chromeOptions.setExperimentalOption("prefs", prefs
        );
```

### Relevant log output

```shell
Map<String, Object> prefs = new HashMap<String, Object>();
        prefs.put("partition", "persist:random22");
        chromeOptions.setExperimentalOption("prefs", prefs
        );
```

### Operating System

win10

### Selenium version

107

### What are the browser(s) and version(s) where you see this issue?

chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

107

**Comment by titusfortner** [comment]
I'm not sure what you're trying to do. Here is a list of available prefs:
https://chromium.googlesource.com/chromium/src/+/master/chrome/common/pref_names.cc
