### ISSUE TITLE
Encoded symbols in JavaDoc

### ISSUE THREAD

**Issue by VladislavLopatynsky** [SeleniumHQ/selenium#1132]
Hello, guys! 
Seems after migration to Java 8 in some cases after JavaDoc generation some symbols were not decoded.

https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html

See the Sample section:

     Wait&lt;WebDriver&gt; wait = new FluentWait&lt;WebDriver&gt;(driver)

**Comment by lukeis** [comment]
pull requests happily accepted to fix them... Initially I "fixed" the javadoc errors that were being reported, but didn't look at the outcome for these cases... not sure how to fix this.
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L53

(Pull requests would be appreciated :) )

**Comment by jleyba** [comment]
Change the enclosing `{@code}` to `<code>...</code>`

`{@code}` is like `{@literal}`, so `&lt;` is rendered as `&amp;lt;`
