### ISSUE TITLE
[🐛 Bug]: 4.6.1 is on PyPI, but there is no tag on GitHub

### ISSUE THREAD

**Issue by frafra** [SeleniumHQ/selenium#11337]
### What happened?

See the title.

### How can we reproduce the issue?

```shell
Look at GitHub tags and releases, and on https://pypi.org/project/selenium/#history.
```

### Relevant log output

```shell
See the pages.
```

### Operating System

Not relevant

### Selenium version

Not relevant

### What are the browser(s) and version(s) where you see this issue?

Not relevant

### What are the browser driver(s) and version(s) where you see this issue?

Not relevant

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.6.1-python
