### ISSUE TITLE
[🐞 Bug]: Socket connection is not getting closed in the hub node in Selenium grid 4.6.0

### ISSUE THREAD

**Issue by Codude** [SeleniumHQ/selenium#11336]
### What happened?

Selenium grid : 4.6.0
OS : ubuntu 18.04 LTS

While we run more threads in parallel several drivers are created simultaneously. For a single automation run, we are getting many unclosed processes piled up on on JVM (PFA). This happens after we migrated from selenium 4.2.2 to 4.6.0 

<img width="792" alt="Screenshot 2022-11-30 at 11 09 12 AM" src="https://user-images.githubusercontent.com/36496990/204716529-3b6043aa-c4f7-4b73-b402-35ebde938b26.png">

### How can we reproduce the issue?

```shell
Run hub and node in selenium 4.6.0 and try to open as many drivers as you can and check the running process in JVM.
```

### Relevant log output

```shell
java    12621 test  482u     IPv6            2995095       0t0      TCP <host1>:41134-><host2>:https (CLOSE_WAIT)
java    12621 test  483u     IPv6            2995123       0t0      TCP <host1>:41616-><host2>:https (CLOSE_WAIT)
java    12621 test  484u     IPv6            2995128       0t0      TCP <host1>:41626-><host2>:https (CLOSE_WAIT)
java    12621 test  485u     IPv6            3001717       0t0      TCP <host1>:42424-><host2>:https (CLOSE_WAIT)
java    12621 test  489u     IPv6            3001733       0t0      TCP <host1>:42456-><host2>:https (CLOSE_WAIT)
```

### Operating System

Ubuntu 18.04

### Selenium version

Java 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 106.0.5249.119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106.0.5249.61

### Are you using Selenium Grid?

4.6.0

**Comment by Codude** [comment]
Reverted back to selenium 4.2.2, I can still see those CLOSE_WAIT processes not closed for this version too. Only difference is amount of processes. grid 4.6.0 has more ( atleast 3 times ) processes in this state than grid 4.2.2.

**Comment by diemol** [comment]
Seems to be the same as #11270, can you please double check?

**Comment by Codude** [comment]
```
@Override
	public void quit() {
		//same as parent implementation, we just try to quit multiple times to make sure we close it incase of any runtime errors
		for(int i=0;i<5;i++) {
			try {
				super.quit();
				break;
			}
			catch(Exception e) {}
		}
System.gc();
	}
```

We override the quit() method and do this to ensure run time errors. We didn't use any sleep in here as mentioned in the previous bug. I've added the mentioned ```System.gc();``` call after the loop but still we got those ```CLOSE_WAIT``` in grid 4.6.0

The same code I used in grid 4.2.2, there are no CLOSE_WAIT calls in the JVM process

**Comment by pujagani** [comment]
If the concern is the socket connection not closing on quit, then the fix https://github.com/SeleniumHQ/selenium/pull/11345 should ideally take care of it. We open websocket connection when initializing any driver that supports CDP, however, we were not closing the socket on `driver.quit()`. The fix for the same has been added. We are waiting to ensure all CI tests pass before merging it in.

**Comment by diemol** [comment]
PR #11345 has been merged, so this should be fixed. I will do a 4.7.1 release in 1-2 days and you can check this again.
