### ISSUE TITLE
selenium-webdriver-4.6.x gem for ARM 

### ISSUE THREAD

**Issue by gongomgra** [SeleniumHQ/selenium#11333]
### What happened?

I see latest selenium-webdriver gem's versions 4.6.x install a couple of binary files (linux and macos). However, it looks like the Linux binaries are for x86-64 architecture, but I'm installing the gem in a Debian-11 ARM container. This gem version was installed running the `rails new` command. I see previous minor version 4.5.0 (from September this year) didn't install any binary in the filesystem. Does it mean ARM is not supported for this new version?

### How can we reproduce the issue?

```shell
Install selenium-webdriver gem versions 4.5.0 and 4.6.1 in Debian-11 ARM.
```

### Relevant log output

```shell
root@53f3db406b94:/# uname -a
Linux 53f3db406b94 4.19.0-19-arm64 #1 SMP Debian 4.19.232-1 (2022-03-07) aarch64 GNU/Linux

# 4.5.0
root@53f3db406b94:/opt# ls /opt/ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.5.0
CHANGES  Gemfile  LICENSE  NOTICE  README.md  lib  selenium-webdriver.gemspec
# 4.6.0
root@53f3db406b94:/opt# ls /opt/ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.0
CHANGES  Gemfile  LICENSE  NOTICE  README.md  bin  lib  selenium-webdriver.gemspec
# 4.6.1
root@53f3db406b94:/opt# ls /opt/ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.1
CHANGES  Gemfile  LICENSE  NOTICE  README.md  bin  lib  selenium-webdriver.gemspec

root@6c259306eaf3:/opt# find . -type f -name selenium-manager
./ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.1/bin/macos/selenium-manager
./ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.1/bin/linux/selenium-manager

root@6c259306eaf3:/opt# file /opt/ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.1/bin/linux/selenium-manager
/opt/ruby/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.6.1/bin/linux/selenium-manager: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=39c8254e5dd7f3b683f00255db4dd949c583a161, for GNU/Linux 3.2.0, stripped
```

### Operating System

debian-11 ARM

### Selenium version

selenium-webdriver-4.6.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
The binaries are part of a new beta feature: https://www.selenium.dev/blog/2022/introducing-selenium-manager/
They are created in rust, which should be able to cross compile, but we haven't gotten that all tooled in, so we are using github actions to build them for us and copying them into the repo. Github actions only supports windows, linux and mac, so those are the 3 binaries we're distributing right now. Eventually we'll get this sorted out and include additional binaries.

This shouldn't impact the functioning of the rest of Selenium in any way.
