### ISSUE TITLE
[🐛 Bug]:   class file for org.openqa.selenium.Rotatable not found for appium ios driver on 4.6.0 and 4.7.0 versions

### ISSUE THREAD

**Issue by nir-tal-talkspace** [SeleniumHQ/selenium#11347]
### What happened?

getting this error:

```
class file for org.openqa.selenium.Rotatable not found
/home/circleci/project/mobile-ios-client/src/test/java/glue/steps/pages/webview/CommonWebSteps.java:47: error: cannot access Rotatable
```

looks like it's related to this commit: https://github.com/SeleniumHQ/selenium/commit/946d78976989eeed81f469ee733c31adf43ea70e

### How can we reproduce the issue?

created https://github.com/nir-tal-talkspace/appium that demonstrates the issue

![image](https://user-images.githubusercontent.com/71274151/205234463-cbd9fa39-075c-42a6-b73e-fc350b799a68.png)

### Relevant log output

```shell
class file for org.openqa.selenium.Rotatable not found
/home/circleci/project/mobile-ios-client/src/test/java/glue/steps/pages/webview/CommonWebSteps.java:47: error: cannot access Rotatable
```

### Operating System

Ubuntu 20

### Selenium version

4.6.0 / 4.7.0

### Are you using Selenium Grid?

No

**Comment by nir-tal-talkspace** [comment]
this issue happens on selenium version 4.6.0 from yesterday and 4.7.0

**Comment by nir-tal-talkspace** [comment]
@mykola-mokhnach @diemol @pujagani @valfirst @titusfortner

**Comment by nir-tal-talkspace** [comment]
created https://github.com/nir-tal-talkspace/appium that demonstrates the issue


![image](https://user-images.githubusercontent.com/71274151/205225481-031716b5-0cd1-4a79-a1bf-f2ed6919740a.png)

@pujagani

**Comment by mykola-mokhnach** [comment]
I assume this is the expected behaviour as the interface has been already marked as deprecated before.
Prepared a PR to appium java client, which removes the dependency to the legacy interface: https://github.com/appium/java-client/pull/1811

**Comment by diemol** [comment]
@mykola-mokhnach is right, we deprecated and waited for several releases.

**Comment by titusfortner** [comment]
We really need to figure out the snapshot releases so we can test with Appium before releasing - https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry
