### ISSUE TITLE
[🚀 Feature]: Selenium Manager - allow to ignore build matching

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11353]
### Feature and motivation

User should be able to specify any version of browser and driver they want, and if the driver would otherwise complain, they need to specify to ignore the complaint.

This should include the ability to set separate driver and browser versions, and therefore allow setting the driver version with just the major version number.

This will require bindings to parse the `goog:chromeOptions` capability for an arg with `disable-build-check`.

### Usage example

```
selenium-manager --browser chrome --browser-version 105 --driver-version 108 --disable-build-check
```
or
```
selenium-manager --browser chrome --browser-version canary --driver-version dev --disable-build-check
```

I *don't think you need to check `--disable-build-check` if a user does something that the driver itself will allow:
```
selenium-manager --browser chrome --browser-version 108 --driver-version 107
```

**Comment by diemol** [comment]
I am not sure if Selenium Manager needs to be aware of `--disable-build-check`. It should probably be just the bindings, like if the browser and browser version are different, add the `--disable-build-check` flag. However, this flexibility opens the door for user errors, which indeed are user created but they could end up in issue reports (given that users try all different combinations). 

Also, this is Chromium only.

**Comment by titusfortner** [comment]
Scenario:
```
DriverService ds = new ChromeDriverService.Builder()
  .withBrowserVersion("106")
  .withDriverVersion("103")
  .build();
Chromedriver driver = new ChromeDriver(ds, new ChromeOptions());
```
Bindings will translate to:
```
selenium-manager --browser chrome --browser-version 106 --driver-version 103
```

If Selenium Manager just returns the v103 of the chromedriver, then the driver will error when the code tries to use it.

I think it makes sense for Selenium Manager to be the one that throws the error where we can give a better message about what the user needs to do (use a matching version or add `--disable-build-check` to the ChromeOptions).

And yes, Chrome & Edge only.

**Comment by titusfortner** [comment]
Ok, new scenario...

Maybe we don't let the user specify driver version in code, and user puts an older version of driver on PATH that they want to use. Normally we'd throw a warning saying your driver version is old, we're giving you the updated one...
If a user passes `--disable-build-check` then we throw the warning but still use it?

**Comment by diemol** [comment]
Makes sense. I think letting users specify the driver version is not ideal because it opens the door to many unsupported use cases. If they want to have a special environment, they can set it up by putting it on the PATH.

**Comment by titusfortner** [comment]
The thing I want to figure out is how best to support that scenario ("no really, I want to use this old one") from #11373 

`--disable-build-check` isn't the most obvious way to express this, though.

Maybe we tell users if they want a specific, outdated version, that they need to specify it directly (or use System Properties).

**Comment by titusfortner** [comment]
I no longer think this is what we want to do. The Selenium code should only be specifying the browser name/version/location as necessary and let Selenium Manager figure out the right driver.
