### ISSUE TITLE
[🚀 Feature]: Selenium Manager support browserName recognized by each driver

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11352]
### Feature and motivation

Right now `--browser` only supports `iexplorer` and it seems like it should be easy to support both. All of the Selenium code right now is either "IE" or "InternetExplorer". I had to hack a workaround in Python code,  (though hopefully we change this soon anyway).

### Usage example

```
selenium-manager --browser ie
```

**Comment by diemol** [comment]
👍  this makes sense

**Comment by titusfortner** [comment]
So, looking at actual implementations, what we really want is "internet explorer" here (https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/Browser.java#L41)

and for that matter `MicrosoftEdge`: https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/Browser.java#L32

I'm guessing we can't have spaces on command line, so maybe `internet-explorer` or `internet_explorer`?

**Comment by bonigarcia** [comment]
Completed with #11420.

**Comment by titusfortner** [comment]
I'm still having issues with multiple browser names on my mac, so I'm reopening to track

This is mac64 built from [se_mgr_browser_path](https://github.com/SeleniumHQ/selenium/tree/se_mgr_browser_path) branch

```
sl-1495:macos titusfortner$ /Users/titusfortner/code/selenium/rb/bin/macos/selenium-manager --browser iexplorer
INFO	/Users/titusfortner/.cache/selenium/IEDriverServer/win32/4.7.0/IEDriverServer
sl-1495:macos titusfortner$ /Users/titusfortner/code/selenium/rb/bin/macos/selenium-manager --browser internetexplorer
ERROR	Invalid browser/driver name
sl-1495:macos titusfortner$ /Users/titusfortner/code/selenium/rb/bin/macos/selenium-manager --browser ie
ERROR	Invalid browser/driver name
sl-1495:macos titusfortner$ /Users/titusfortner/code/selenium/rb/bin/macos/selenium-manager --browser internet-explorer
ERROR	Invalid browser/driver name
```

**Comment by titusfortner** [comment]
and this was a mistake on my part, working as intended in the latest branches.
