### ISSUE TITLE
[🚀 Feature]: Selenium Manager Manager

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11358]
### Feature and motivation

As we increase the functionality of the Selenium Manager, and as we are looking to implement more architectures (#11357), we probably should figure out a better way to package Selenium Manager binaries.

One option is to create and bundle a super small binary for each architecture, whose sole job is to download the correct manager. I recognize this can also be done by the bindings as well, but tbh I'd rather not deal with http libraries in each of the bindings to execute the same feature.

### Usage example

n/a

**Comment by bonigarcia** [comment]
If I am not wrong, we don't want this feature anymore. I'm closing it. Please re-open if required.
