### ISSUE TITLE
[🚀 Feature]: Java Jar snapshots on Github Packages

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11355]
### Feature and motivation

Appium project has had some issues with Selenium removing things before they were ready for them. Thankfully @mykola-mokhnach and @SrinivasanTarget  have been very responsive, but we still run into issues like: https://github.com/appium/java-client/pull/1811

If we can figure out how to release to https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry
that should allow Appium to test against it without cluttering up maven itself 

### Usage example

n/a

**Comment by SrinivasanTarget** [comment]
@titusfortner a week back we worked on automated release to maven Central from GitHub release in appium Java client. We can utilise that knowledge here.

**Comment by titusfortner** [comment]
Problem is that it's likely going to be a bit tricky with bazel :-/

**Comment by diemol** [comment]
Closed via https://github.com/SeleniumHQ/seleniumhq.github.io/commit/da59b01cb9340efe209516fcd031f82b360f0b47

Java Grid can be downloaded from the [Nightly tag ](https://github.com/SeleniumHQ/selenium/releases/tag/nightly) and the bindings can be taken from the [snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/org/seleniumhq/selenium/selenium-java/). I also added https://www.selenium.dev/downloads/#nightly to share info on how to use them.
