### ISSUE TITLE
[🐛 Bug]: Unexpected TimeoutError from the Renderer

### ISSUE THREAD

**Issue by Mr-D-007** [SeleniumHQ/selenium#11363]
### What happened?

While running a test case, selenium-wire is getting TimeoutError while running the steps that says TimeoutError getting response from the Renderer. It is happening every time I want to run the test case.

### How can we reproduce the issue?

```shell
driver.get(DOMAIN)
```

### Relevant log output

```shell
Timed out receiving message from renderer: 300.000 (Session info: headless chrome=103.0.5060.114)
```

### Operating System

MacOS Intel

### Selenium version

5.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 103.0.5060.114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 103.0.5060.53

**Comment by diemol** [comment]
Closing as no more information was given.
