### ISSUE TITLE
[🚀 Feature]: What does Selenium + Appium consolidation mean?

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#11364]
### Feature and motivation

At the selenium.github.io repository, the records of meetings discusses something that is called "Selenium + Appium consolidation".

Does this mean that Appium would be moved to the Selenium organization, or will the code be copied over to the Selenium repository?

### Usage example

It would be nice to know what is going to be done with Selenium and Appium in the future.

**Comment by diemol** [comment]
It is a long term idea that we still need to go into details. Feel free to join the link to the chat above to get more details.
