### ISSUE TITLE
[🚀 Feature]: Selenium Manager get Browser Version from Options classes

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11372]
### Feature and motivation

~Java already supports passing in Options to Service class for Chrome to get logging level — 
We'll want to expand on that for all service classes, and then implement it in each of the other languages.~

We decided not to expand on what was currently being done in Java and to implement a Driver Finder class that will consume the browser options instance and update the service instance.

In Progress:
Ruby - #11523 
Java - #11491

**Comment by diemol** [comment]
JS -> https://github.com/SeleniumHQ/selenium/commit/2c1bd8eb164a80e382616951bf56bede57b576b2

**Comment by diemol** [comment]
Implemented in all bindings, closing.
