### ISSUE TITLE
[🐛 Bug]: BitBucket Pipeline is marked as Failed though Test is Passed when Migrated to Selenium 4 to use WebDriver Manager

### ISSUE THREAD

**Issue by Sasi4usi** [SeleniumHQ/selenium#11386]
### What happened?

Having a Hybrid framework uses Maven Project in Java Programming. To utilize Selenium Driver Manager we have upgraded Selenium version from 2.53.0 to 4.6.0. Bit Bucket is our automation repository. We have Pipeline enabled in Bit Bucket. Bit Bucket pipeline has been configured run on a windows server (i.e. self-hosted) Runner.

Bitbucket pipeline is passed with earlier version but it is getting failed once upgraded to the Selenium 4 version. Maven build process is getting completed successfully with no errors and failures. Even TestNG result also does not have any errors/failures. But Pipeline step is still getting marked as Failed.

We do not know the issue is with Selenium Manager or Selenium 4 version. But we ensured that it is not from Bit Bucket side. Reverted the changes and ran the Pipeline again. Pipeline is getting passed once reverted. 

### How can we reproduce the issue?

```shell
1. Have a Maven Project with Selenium 4.6.0 dependency
2. Invoke browser using Selenium Driver Manager
3. Push the code to the Bit Bucket Repository
4. Add a Windows 10 Runner in Bit Bucket Repository
5. Create a Pipeline to build a Maven Project (i.e. to execute automation test)
```

### Relevant log output

```shell
Maven Console Log:

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.563 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ FrameworkCore2.0 ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Users\xxxxx\atlassian-bitbucket-pipelines-runner\temp\965507bc-86c8-5f4a-af2c-8731bed4c82b\1670476923823\build\target\FrameworkCore2.0-0.0.2-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  58.683 s
[INFO] Finished at: 2022-12-07T23:26:16-06:00
[INFO] ------------------------------------------------------------------------

Build Teardown Log in BitBucket:

Skipping cache upload for failed step
Searching for test report files in directories named [failsafe-reports, TestResults, surefire-reports, test-reports, test-results] down to a depth of 4
Found matching test report file C:\Users\xxxxxx\atlassian-bitbucket-pipelines-runner\bin\..\temp\965507bc-86c8-5f4a-af2c-8731bed4c82b\1670476923823\build\target\surefire-reports\junitreports\TEST-application.Driver.xml
Located test suite containing 1 tests, with 0 failures and 0 errors.
Found matching test report file C:\Users\xxxxxx\atlassian-bitbucket-pipelines-runner\bin\..\temp\965507bc-86c8-5f4a-af2c-8731bed4c82b\1670476923823\build\target\surefire-reports\Suite\Test.xml
Located test suite containing 1 tests, with 0 failures and 0 errors.
Found matching test report file C:\Users\xxxxxx\atlassian-bitbucket-pipelines-runner\bin\..\temp\965507bc-86c8-5f4a-af2c-8731bed4c82b\1670476923823\build\target\surefire-reports\TEST-TestSuite.xml
Located test suite containing 1 tests, with 0 failures and 0 errors.
Found matching test report file C:\Users\xxxxxx\atlassian-bitbucket-pipelines-runner\bin\..\temp\965507bc-86c8-5f4a-af2c-8731bed4c82b\1670476923823\build\target\surefire-reports\testng-results.xml
Finished scanning for test reports. Found 4 test report files.
Merged test suites, total number tests is 3, with 0 failures and 0 errors.
Uploading test results
Finished uploading test results.
```

### Operating System

Windows 10

### Selenium version

Java JDK 13.0.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

**Comment by diemol** [comment]
2.53.0 to 4.6.0 is a huge jump. I would suggest to do the migration step by step and not all test cases at once. In addition, if there is a specific Selenium bug, please share a deterministic way to reproduce it.

**Comment by Sasi4usi** [comment]
@diemol I agree with you its really a huge Jump. But, scrips are getting executed successfully in local machines. So there is no issue with this migration. So the issue currently facing is only with CI/CD pipeline execution. Even we are able to confirm that this is no way related to Bit Bucket as the reverted version (i.e. older version of Selenium) is working fine with BB pipeline.

Sufficient information has been provided if you could give it a try that would be really appreciable. I do not have any concern if I need to wait till more people start screaming about this issue.

**Comment by diemol** [comment]
I am sorry, we do not have enough time to create a project in BitBucket from scratch and try it out. Also, if things work locally, my assumption is that there must be something in the environment that needs to be done to make things work. We do not use BitBucket, we use GitHub actions.

I believe that if this was a common issue, either BitBucket support or this issue tracker would be flooded with user comments.

If you have anything specific that we can use to reproduce the issue and help, please provide it. Else, most likely this issue will be eventually closed. If you wish, we can treat this issue as a question, which we will give you helpful links to find help and then close the issue.

**Comment by Sasi4usi** [comment]
I have posted this issue here only after posting with Bit Bucket support. I will follow up with that issue.  I will post the defects in future if any found with Selenium. Anyhow thank you so much for the quick response.

I will try to execute the pipeline script without using Selenium Driver Manager and update my observation here. After that I have no concern with closing this issue. Thanks once again.

I have even executed with Bony Garcia WebDriver Manager with Selenium 4.0. I am not facing such issue with Bit Bucket pipeline. So I am able conclude that this issue with communication between Selenium Driver Manager and BitBucket Pipeline.

**Comment by Sasi4usi** [comment]
I am closing this issue as I am not sure whether issue is with Bit Bucket side or Selenium Driver Manager side.
