### ISSUE TITLE
[🚀 Feature]: Python 3.10 support (and Info at PyPI)

### ISSUE THREAD

**Issue by TTMaZe** [SeleniumHQ/selenium#11387]
### Feature and motivation

Official support for Python 3.10 would be nice. 
(I refer to [PyPI/selenium](https://pypi.org/project/selenium/) where the _Programming Language_ list ends with 3.9)

### Usage example

We would like to enable a dependent project to be run with Python 3.10.

**Comment by symonk** [comment]
everything should be fine on `3.10` - we should probably test on that if we aren't already, we just need to update the classifiers accordingly

**Comment by AutomatedTester** [comment]
tested with 3.10 and we're good to go

**Comment by diemol** [comment]
Should we merge this, @symonk?

**Comment by symonk** [comment]
should be corrected in the `4.8.0` release as far as the meta data is concerned on pypi
