### ISSUE TITLE
[🐛 Bug]: Chromedriver for Linux version 108.0.5359 does not work in headless mode.

### ISSUE THREAD

**Issue by bzorefreigo** [SeleniumHQ/selenium#11388]
### What happened?

I am running some tests on an Ubuntu 20.04 machine.
I have the latest Chrome browser version 108.0.5359.94  installed.
I am using Service(ChromeDriverManager().install() in order to download and install the compatible chromedriver.
When I run a simple code to create a driver, I am getting en error (see log output) which does not happen if I run it in regular (not headless mode).

### How can we reproduce the issue?

```shell
To reproduce this issue you can use this code:

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument('--remote-debugging-port=9222')
chrome_options.add_argument('--no-sandbox')
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
print(driver)

If you run it as is, you should encounter the issue.
If you mark out the line "chrome_options.add_argument("--headless")" you will get a print of the driver object (something like this: <selenium.webdriver.chrome.webdriver.WebDriver (session="5895d3fbbd23d081dc23e9e883d914d1")>)
```

### Relevant log output

```shell
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55600cae82a3 <unknown>
#1 0x55600c8a6f77 <unknown>
#2 0x55600c8cf5f7 <unknown>
#3 0x55600c8cb7d0 <unknown>
#4 0x55600c90c0b7 <unknown>
#5 0x55600c90ba5f <unknown>
#6 0x55600c903903 <unknown>
#7 0x55600c8d6ece <unknown>
#8 0x55600c8d7fde <unknown>
#9 0x55600cb3863e <unknown>
#10 0x55600cb3bb79 <unknown>
#11 0x55600cb1e89e <unknown>
#12 0x55600cb3ca83 <unknown>
#13 0x55600cb11505 <unknown>
#14 0x55600cb5dca8 <unknown>
#15 0x55600cb5de36 <unknown>
#16 0x55600cb79333 <unknown>
#17 0x7f513dc5bb43 <unknown>
```

### Operating System

Ubuntu 22.04.1 LTS

### Selenium version

4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.94

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 108.0.5359.71

**Comment by titusfortner** [comment]
Is that the correct location of your chrome instance? If not, you need to specify the `binary` property in your options class. If it is correct, try downloading the correct driver and pointing to the location directly to see if the issue is in how the `ChromeDriverManager()` is determining what driver to download.

Selenium is working on an official driver manager, but we probably need to address #11351 & #11356 before we can ensure that you don't have this issue.

**Comment by bzorefreigo** [comment]
Thank you for your reply. 
That is indeed my Chrome's binary location:
`[~]$ which google-chrome
/usr/bin/google-chrome`

As for the driver, the chromedriver downloads page (https://chromedriver.chromium.org/downloads) mentions that "If you are using Chrome version 108, please download ChromeDriver 108.0.5359.71".
I downloaded ChromeDriver 108.0.5359.71 and despite deprecated, I used the "executable_path" to point to the chromedriver:
driver = webdriver.Chrome(executable_path='/home/boazz/Downloads/chromedriver', options=chrome_options)

I got the same error.

**Comment by titusfortner** [comment]
Forgot to ask the more important question, does it work when it isn't headless? (xvfb if no ui) or --headless=chrome

**Comment by bzorefreigo** [comment]
Yes it does.

When marking out the line stating "chrome_options.add_argument("--headless")", there is no error and the driver is created correctly.

**Comment by titusfortner** [comment]
You can use `--headless=chrome` if you want, then.

The only difference between headless mode and non-headless mode is a flag sent to chromedriver, so specific bugs/issues would need to be referred to Google.

**Comment by tex0l** [comment]
I am experiencing the same issue, is there any kind of workaround?

**Comment by bzorefreigo** [comment]
@tex0l You can try the following chrome options:

chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--window-size=1920,1080')
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--disable-dev-shm-usage')
