### ISSUE TITLE
[🚀 Feature]: Selenium-Manager falls back to the latest driver version if a given version still needs to be released

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11383]
### Feature and motivation

Continuation of #11334. When a given driver version is unavailable in its repository (e.g., chromedriver `110`), Selenium Manager should fall back to the `latest` version.

### Usage example

```
./selenium-manager --browser chrome --browser-version dev
```

... and `dev` exists on the machine, but the required driver version (e.g., chromedriver `110`) has not been released yet.

**Comment by titusfortner** [comment]
Just to be clear.

Assume versions:
Production: v100
Beta: v101
Dev: v102
Canary: v102

When Dev exists on the machine, but chromedriver v102 hasn't been released yet through regular channel, then Selenium Manager should get v101.

**Comment by bonigarcia** [comment]
Completed with #11454.
