### ISSUE TITLE
[🚀 Feature]: Remove unnecessary old commands which are deprecitated

### ISSUE THREAD

**Issue by DanielOberlechner** [SeleniumHQ/selenium#11380]
### Feature and motivation

Hi I was using selenium and therefore copying a lot of google but half of the stuff does not work, because its depreciated.
I'm a guy I love to udr always the newest software so a downgrade would be no option..

How is the Development going so far?

Kind regards,
Daniel Oberlechner

### Usage example

buttons = driver.find_elements_by_link_text('View Profile')
driver.findElement((By.TAG_NAME("button")).click()

Both find elements seem not to work because they are depreciated...

Is there something we can do to fix this problem?

**Comment by diemol** [comment]
You can always check our [docs](https://www.selenium.dev/documentation/) and a [blog post](https://www.selenium.dev/blog/2022/python-locators-se4/) about the specific topic.

**Comment by DanielOberlechner** [comment]
> You can always check our [docs](https://www.selenium.dev/documentation/) and a [blog post](https://www.selenium.dev/blog/2022/python-locators-se4/) about the specific topic.

Thanks for the link I've already found it but sometimes I'm faster google some little things instead reading tons of lectures ...

But maybe if you guys have time you can remove the old depreciated commands...

**Comment by diemol** [comment]
It has been removed since 4.3.0
https://github.com/SeleniumHQ/selenium/blob/trunk/py/CHANGES#L56

**Comment by DanielOberlechner** [comment]
![Bildschirm­foto 2022-12-08 um 01 32 20](https://user-images.githubusercontent.com/10922763/206327240-0d2bd045-866c-4277-8200-3acc4c2845a5.png)
Are u sure about the version number. Have installed these days everything from new but your version does not match mine ,,,,
