### ISSUE TITLE
[🐛 Bug]:  JavascriptError: javascript error: circular reference on executeScript with function which ties to return a 'massive' object 

### ISSUE THREAD

**Issue by potapovDim** [SeleniumHQ/selenium#11389]
### What happened?

Not sure is it a bug, or is it a way how it should work, but seems like when i use arrow function without curly brackets (body) that returns objects (i.e window) this call throws an error which is not very informative 

### How can we reproduce the issue?

```shell
async function throwsError(url) {
  await browser.executeScript((openUrl) => window.open(openUrl, '_blank'), url);
}

async function worksFine(url) {
  await browser.executeScript((openUrl) => { window.open(openUrl, '_blank') }, url);
}
```

### Relevant log output

```shell
JavascriptError: javascript error: circular reference
  (Session info: chrome=108.0.5359.94)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:587:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:515:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.execute (node_modules/selenium-webdriver/lib/webdriver.js:742:17)
```

### Operating System

macOS Ventura

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

Any

### What are the browser driver(s) and version(s) where you see this issue?

Latest

### Are you using Selenium Grid?

-

**Comment by AutomatedTester** [comment]
This is going to be a tricky one. I am surprised that the Browser isn't throwing the error since overly complex items can't be serialised. e.g. `window` is a great example. We  may need to get this raised up to the browsers for them to solve and we just process the error messages.  It will allow faster error reporting to the client
