### ISSUE TITLE
build fail during npm install

### ISSUE THREAD

**Issue by loganfreeman** [SeleniumHQ/selenium#1139]
make: Entering directory `/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'
npm ERR! EEXIST, open '/home/jenkins/.npm/6a99e61f-ins-npm-lodash-2-4-2-package-tgz.lock'
File exists: /home/jenkins/.npm/6a99e61f-ins-npm-lodash-2-4-2-package-tgz.lock
Move it away, and try again.

**Comment by jleyba** [comment]
bufferutil is an optional dependency

Make sure you are using Node 0.12.x or 4.x
