### ISSUE TITLE
[🚀 Feature]: switch to tab without focusing

### ISSUE THREAD

**Issue by tetratensor** [SeleniumHQ/selenium#11393]
### Feature and motivation

I'm using the c# Selenium and Chrome webdriver on Windows 10. I like to have a GUI up for debugging purposes, but my code keeps bringing the browser into focus. Specifically, lines like

driver.switchTo().window(tabs.get(1));

will bring the automated Chrome browser into focus, taking me away from checking my e-mail etc.

How can I get Selenium to "silently" focus on a new tab (or window etc) so I can do something else.

### Usage example

maybe silent parameter?
driver.switchTo().window(tabs.get(1), SwitchOption.Silent);

**Comment by diemol** [comment]
That is the nature of how browsers work together with automation. An alternative is to run the session headless when you do not need to debug the UI, or use a Grid like https://github.com/SeleniumHQ/docker-selenium
