### ISSUE TITLE
[🐛 Bug]: Code is unreachable

### ISSUE THREAD

**Issue by charliemday** [SeleniumHQ/selenium#11398]
### What happened?

Using the `webdriver.Chrome()` makes the code below unreachable using VSCode and Pylance. There's this [issue](https://github.com/SeleniumHQ/selenium/issues/11091) which was closed and the solution was to upgrade Selenium but this problem seems to persist on `selenium==4.7.2`.

### How can we reproduce the issue?

```shell
from selenium import webdriver

webdriver.Chrome()

# Code is "unreachable" because of the previous line

a = 1
print(a)
```

### Relevant log output

```shell
Code is unreachable (Pylance)
```

### Operating System

macOS Catalina

### Selenium version

Python 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 107.0.5304.121

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 108

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
Does the code work when you execute it away from pylance?

**Comment by charliemday** [comment]
> Does the code work when you execute it away from pylance?

Yes, the execution of the code works fine both in VSCode and out. It's with Pylance in VSCode it registers it incorrectly as `Unreachable`. 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/45036245/206696932-fd137415-e761-4265-9196-16bb9ef24516.png">

**Comment by titusfortner** [comment]
Fwiw previous issue had to do with our having a no return type instead of a none type on one of the methods.

https://github.com/microsoft/pylance-release/issues/2807

**Comment by symonk** [comment]
@charliemday can you try with the latest version of the extension in vscode if not already? I cannot recreate it with pylance on a fresh install

**Comment by charliemday** [comment]
> @charliemday can you try with the latest version of the extension in vscode if not already? I cannot recreate it with pylance on a fresh install

I've upgraded Pylance and restarted the language server but still experiencing the issue. Which VSCode and Pylance version are you using to try recreating this? Mine are:

Pylance == `v2022.12.20`
VSCode == `1.73.1`
Selenium == `4.7.2`
Python == `3.7.8`

<img width="400" alt="image" src="https://user-images.githubusercontent.com/45036245/206859838-3bb0bbfd-9334-43aa-8d04-97f9fab6f1c0.png">

**Comment by charliemday** [comment]
For reference this issue has seemed to resolve itself after auto-updating to VSCode [1.74](https://github.com/microsoft/vscode/releases/tag/1.74.0) and with the current packages I no longer get the Pylance `unreachable` error: 

Pylance == `v2022.12.20`
VSCode == `^1.74`
Selenium == `4.7.2`
Python == `3.7.8`

**Comment by symonk** [comment]
Much appreciated, thanks!
