### ISSUE TITLE
[🐛 Bug]: SeleniumServer does not start selenium 4.x jar standalone 

### ISSUE THREAD

**Issue by potapovDim** [SeleniumHQ/selenium#11405]
### What happened?

Selenium server can not start selenium 4.4.0 as a standalone server

### How can we reproduce the issue?

```shell
const { SeleniumServer } = require('selenium-webdriver/remote');

test();
async function test() {
  const pathToJar3xJar = './.selenium/selenium-server/3.141.59/selenium-server.jar';
  const pathToJar4xJar = './.selenium/selenium-server/4.4.0/selenium-server.jar';

  const args = {
    args: [],
    jvmArgs: ['-Dwebdriver.chrome.driver=./.selenium/chromedriver/latest-x64/chromedriver'],
    port: undefined,
  };

  // this works fine
  const server3xJar = new SeleniumServer(pathToJar3xJar, args);
  /* does not work
  the problem that selenium 4.х requires "standalone" right after the jar file what is not happen
  when the same args are used
  */
  const server4xJar = new SeleniumServer(pathToJar4xJar, args);
}
```

### Relevant log output

```shell
Error: Server terminated early with status 0
      at /node_modules/selenium-webdriver/remote/index.js:249:24
```

### Operating System

macOS Ventura

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by diemol** [comment]
Grid 4 needs a parameter to specify the role the server will start with. In this case you need to add `standalone` so the server starts in that mode.

**Comment by potapovDim** [comment]
@diemol @harsha509  should it be here? args: [], in args section ? can you provide an example ?
in case if i will add  'standalone' to args array it will not work due to order of arguments which go to child_process.spawn 
**java** [
  '-Dwebdriver.chrome.driver=./.selenium/chromedriver/latest-x64/chromedriver',
  '-jar',
  './.selenium/selenium-server/4.4.0/selenium-server.jar',
  '-port',
  49351,
  'standalone'
]
and it still does not work

```
const args = {
    args: ['standalone'],
    jvmArgs: ['-Dwebdriver.chrome.driver=./.selenium/chromedriver/latest-x64/chromedriver'],
    port: undefined,
  };
```

**Comment by diemol** [comment]
The command should be `java -Dwebdriver.chrome.driver=./.selenium/chromedriver/latest-x64/chromedriver jar selenium-server.jar standalone --port 49351`

I am not fluent in JavaScript, so not sure how that maps to the code you are using.

**Comment by potapovDim** [comment]
@diemol yes you are right, but this command args are managed by SeleniumServer, i have dirty workaround 
```
const server = new SeleniumServer(combinedConfig.seleniumServerJar, serverConf);

    server.args_ = [...serverConf.jvmArgs, '-jar', combinedConfig.seleniumServerJar, 'standalone', '--port', `${port}`];
```
 but it seems to be a bug of the selenium-webdriver js, can we reopen this issue ?
 
 code is here 
 https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/remote/index.js#L474

**Comment by potapovDim** [comment]
@harsha509 do you want me to prepare fix for this ?

**Comment by diemol** [comment]
I never understood that this was in the Selenium codebase. PRs are appreciated.

**Comment by harsha509** [comment]
Hi @potapovDim ,

Sure, if you've fix ready, could you please raise the PR. 

I have time today will take a look!

**Comment by potapovDim** [comment]
@harsha509 https://github.com/SeleniumHQ/selenium/pull/11412

**Comment by harsha509** [comment]
Closing as fix is landed with https://github.com/SeleniumHQ/selenium/pull/11412!

Thank you @potapovDim 🎉
