### ISSUE TITLE
[🐛 Bug]:  WARN [DriverService.findExecutable] - Unable to obtain driver using Selenium Manager: The driver executable must exist

### ISSUE THREAD

**Issue by amiablekrishna** [SeleniumHQ/selenium#11415]
### What happened?

Using Selenium Grid 4.7.0 version to connect the Hub and Node.  So i started the hub command in my local machine and started the Node command in VM, before that, i set the Chrome driver path in my local machine and VM.
Hub Machine
`java -jar selenium-server-4.7.0.jar hub --publish-events tcp://<hub-ip>:8886 --subscribe-events tcp://<hub-ip>:8887 --port 8888`

Node Machine (Remote Machine)
`java -jar "C:\QATools\selenium-server-4.7.0.jar" node --publish-events tcp://<hub-ip>:8886 --subscribe-events tcp://<hub-ip>.1:8887`

when I run the Node command in VM, i see this message "WARN [DriverService.findExecutable] - Unable to obtain driver using Selenium Manager: The driver executable must exist: C:\"
then i see the Sending registration event message, and No communication between Hub and Node

### How can we reproduce the issue?

```shell

C:\>chromedriver.exe -v
ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016})

Remote Machine - Command Prompt

C:\> java -jar "C:\QATools\selenium-server-4.7.0.jar" node --publish-events tcp://<hub-ip>:8886 --subscribe-events tcp://<hub-ip>.1:8887
```

### Relevant log output

```shell
10:03:20.764 INFO [LogManager$RootLogger.log] - Using the system default encoding
10:03:20.769 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
10:03:20.964 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.212.203.1:8886 and tcp://10.212.203.1:8887
10:03:21.044 INFO [UnboundZmqEventBus.<init>] - Sockets created
10:03:22.052 INFO [UnboundZmqEventBus.<init>] - Event bus ready
10:03:22.187 INFO [NodeServer.createHandlers] - Reporting self as: http://10.237.48.12:5555
10:03:22.342 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
10:03:22.607 WARN [DriverService.findExecutable] - Unable to obtain driver using Selenium Manager: The driver executable must exist: C:\
10:03:22.687 WARN [DriverService.findExecutable] - Unable to obtain driver using Selenium Manager: The driver executable must exist: C:\
10:03:22.767 WARN [DriverService.findExecutable] - Unable to obtain driver using Selenium Manager: The driver executable must exist: C:\
10:03:22.772 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
10:03:22.827 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 2 times
10:03:22.837 INFO [Node.<init>] - Binding additional locator mechanisms: id, relative, name
10:03:23.232 INFO [NodeServer$1.start] - Starting registration process for Node http://10.237.48.12:5555
10:03:23.232 INFO [NodeServer.execute] - Started Selenium node 4.7.0 (revision 52e3a49ea2): http://10.237.48.12:5555
10:03:23.247 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:03:33.254 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:03:43.258 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:03:53.260 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:04:03.264 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:04:13.267 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
10:04:23.267 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

Windows 10

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

### Are you using Selenium Grid?

4.7.0

**Comment by titusfortner** [comment]
This was fixed here: https://github.com/SeleniumHQ/selenium/commit/2af020fd12c02ef094a5713b7345c71882056443

**Comment by amiablekrishna** [comment]
I am using Selenium Grid and while configuring the hub and Node through command prompt, i see this issue, not from coding.

![image](https://user-images.githubusercontent.com/14812501/207115501-4dde66f0-4538-43e2-8fc6-ee91f817278e.png)

**Comment by diemol** [comment]
Which browsers do you have installed on the Node?

**Comment by amiablekrishna** [comment]
Browser : 108.0.5359.99
ChromeDriver 108.0.5359.71

**Comment by diemol** [comment]
OK, so two different things. The warnings are shown because Grid tries to find a driver for all supported browsers, however only Chrome is present. But that does not prevent Grid to start successfully.

I assume the real problem is that the Hub tries to reach out to the Node and fails. Can you share the Hub logs in debug mode?

**Comment by amiablekrishna** [comment]
Hub Log

C:\QATools>java -jar selenium-server-4.7.0.jar hub --publish-events tcp://10.212.203.1:8886 --subscribe-events tcp://10.212.203.1:8887 --port 8888
11:00:29.407 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
11:00:29.414 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
11:00:30.063 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://10.212.203.1:8886, advertising as tcp://10.212.203.1:8886], XSUB binding to [binding to tcp://10.212.203.1:8887, advertising as tcp://10.212.203.1:8887]
11:00:30.146 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.212.203.1:8886 and tcp://10.212.203.1:8887
11:00:30.183 INFO [UnboundZmqEventBus.<init>] - Sockets created
11:00:31.186 INFO [UnboundZmqEventBus.<init>] - Event bus ready
11:00:33.357 INFO [Hub.execute] - Started Selenium Hub 4.7.0 (revision 52e3a49ea2): http://10.212.203.1:8888

**Comment by diemol** [comment]
Debug mode please?

**Comment by amiablekrishna** [comment]
C:\QATools>java -jar selenium-server-4.7.0.jar hub --publish-events tcp://10.212.203.1:8886 --subscribe-events tcp://10.212.203.1:8887 --port 8888 --log-level FINE
12:51:08.323 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
12:51:08.330 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
12:51:08.416 DEBUG [AutoConfiguredOpenTelemetrySdkBuilder.build] - Global OpenTelemetry set to OpenTelemetrySdk{tracerProvider=SdkTracerProvider{clock=SystemClock{}, idGenerator=RandomIdGenerator{}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, spanLimitsSupplier=SpanLimitsValue{maxNumberOfAttributes=128, maxNumberOfEvents=128, maxNumberOfLinks=128, maxNumberOfAttributesPerEvent=128, maxNumberOfAttributesPerLink=128, maxAttributeValueLength=2147483647}, sampler=ParentBased{root:AlwaysOnSampler,remoteParentSampled:AlwaysOnSampler,remoteParentNotSampled:AlwaysOffSampler,localParentSampled:AlwaysOnSampler,localParentNotSampled:AlwaysOffSampler}, spanProcessor=SimpleSpanProcessor{spanExporter=org.openqa.selenium.remote.tracing.opentelemetry.SeleniumSpanExporter$1@4461c7e3}}, meterProvider=SdkMeterProvider{clock=SystemClock{}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, metricReaders=[], views=[]}} by autoconfiguration
12:51:08.970 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://10.212.203.1:8886, advertising as tcp://10.212.203.1:8886], XSUB binding to [binding to tcp://10.212.203.1:8887, advertising as tcp://10.212.203.1:8887]
12:51:09.045 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://10.212.203.1:8886 and tcp://10.212.203.1:8887
12:51:09.080 INFO [UnboundZmqEventBus.<init>] - Sockets created
12:51:10.083 INFO [UnboundZmqEventBus.<init>] - Event bus ready
12:51:11.590 DEBUG [MultithreadEventLoopGroup.<clinit>] - -Dio.netty.eventLoopThreads: 16
12:51:11.607 DEBUG [InternalThreadLocalMap.<clinit>] - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
12:51:11.608 DEBUG [InternalThreadLocalMap.<clinit>] - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
12:51:11.629 DEBUG [PlatformDependent0.explicitNoUnsafeCause0] - -Dio.netty.noUnsafe: false
12:51:11.630 DEBUG [PlatformDependent0.javaVersion0] - Java version: 18
12:51:11.631 DEBUG [PlatformDependent0.<clinit>] - sun.misc.Unsafe.theUnsafe: available
12:51:11.632 DEBUG [PlatformDependent0.<clinit>] - sun.misc.Unsafe.copyMemory: available
12:51:11.633 DEBUG [PlatformDependent0.<clinit>] - sun.misc.Unsafe.storeFence: available
12:51:11.634 DEBUG [PlatformDependent0.<clinit>] - java.nio.Buffer.address: available
12:51:11.634 DEBUG [PlatformDependent0.<clinit>] - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
12:51:11.636 DEBUG [PlatformDependent0.<clinit>] - java.nio.Bits.unaligned: available, true
12:51:11.637 DEBUG [PlatformDependent0.<clinit>] - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @2669b199
12:51:11.638 DEBUG [PlatformDependent0.<clinit>] - java.nio.DirectByteBuffer.<init>(long, int): unavailable
12:51:11.639 DEBUG [PlatformDependent.unsafeUnavailabilityCause0] - sun.misc.Unsafe: available
12:51:11.643 DEBUG [PlatformDependent.estimateMaxDirectMemory] - maxDirectMemory: 8522825728 bytes (maybe)
12:51:11.644 DEBUG [PlatformDependent.tmpdir0] - -Dio.netty.tmpdir: C:\Users\ggunase\AppData\Local\Temp\1 (java.io.tmpdir)
12:51:11.645 DEBUG [PlatformDependent.bitMode0] - -Dio.netty.bitMode: 64 (sun.arch.data.model)
12:51:11.647 DEBUG [PlatformDependent.isWindows0] - Platform: Windows
12:51:11.648 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.maxDirectMemory: -1 bytes
12:51:11.648 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.uninitializedArrayAllocationThreshold: -1
12:51:11.650 DEBUG [CleanerJava9.<clinit>] - java.nio.ByteBuffer.cleaner(): available
12:51:11.651 DEBUG [PlatformDependent.<clinit>] - -Dio.netty.noPreferDirect: false
12:51:11.652 DEBUG [NioEventLoop.<clinit>] - -Dio.netty.noKeySetOptimization: false
12:51:11.653 DEBUG [NioEventLoop.<clinit>] - -Dio.netty.selectorAutoRebuildThreshold: 512
12:51:11.661 DEBUG [PlatformDependent$Mpsc.<clinit>] - org.jctools-core.MpscChunkedArrayQueue: available
12:51:12.134 DEBUG [DefaultChannelId.<clinit>] - -Dio.netty.processId: 15508 (auto-detected)
12:51:12.139 DEBUG [NetUtil.<clinit>] - -Djava.net.preferIPv4Stack: false
12:51:12.140 DEBUG [NetUtil.<clinit>] - -Djava.net.preferIPv6Addresses: false
12:51:12.157 DEBUG [NetUtilInitializations.determineLoopback] - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
12:51:12.158 DEBUG [NetUtil$SoMaxConnAction.run] - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
12:51:12.184 DEBUG [DefaultChannelId.<clinit>] - -Dio.netty.machineId: 00:05:9a:ff:fe:3c:7a:00 (auto-detected)
12:51:12.194 DEBUG [ResourceLeakDetector.<clinit>] - -Dio.netty.leakDetection.level: simple
12:51:12.195 DEBUG [ResourceLeakDetector.<clinit>] - -Dio.netty.leakDetection.targetRecords: 4
12:51:12.220 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.numHeapArenas: 16
12:51:12.220 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.numDirectArenas: 16
12:51:12.222 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.pageSize: 8192
12:51:12.224 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxOrder: 9
12:51:12.227 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.chunkSize: 4194304
12:51:12.228 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.smallCacheSize: 256
12:51:12.228 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.normalCacheSize: 64
12:51:12.229 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
12:51:12.229 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.cacheTrimInterval: 8192
12:51:12.229 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
12:51:12.230 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.useCacheForAllThreads: false
12:51:12.230 DEBUG [PooledByteBufAllocator.<clinit>] - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
12:51:12.243 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.allocator.type: pooled
12:51:12.243 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.threadLocalDirectBufferSize: 0
12:51:12.244 DEBUG [ByteBufUtil.<clinit>] - -Dio.netty.maxThreadLocalCharBufferSize: 16384
12:51:12.262 DEBUG [LoggingHandler.channelRegistered] - [id: 0x12e350d3] REGISTERED
12:51:12.265 DEBUG [LoggingHandler.bind] - [id: 0x12e350d3] BIND: /0.0.0.0:8888
12:51:12.268 INFO [Hub.execute] - Started Selenium Hub 4.7.0 (revision 52e3a49ea2): http://10.212.203.1:8888
12:51:12.268 DEBUG [LoggingHandler.channelActive] - [id: 0x12e350d3, L:/[0:0:0:0:0:0:0:0]:8888] ACTIVE
12:51:14.940 DEBUG [LoggingHandler.channelRead] - [id: 0x12e350d3, L:/[0:0:0:0:0:0:0:0]:8888] READ: [id: 0xf3110c18, L:/10.212.203.1:8888 - R:/10.212.203.1:59780]
12:51:14.941 DEBUG [LoggingHandler.channelRead] - [id: 0x12e350d3, L:/[0:0:0:0:0:0:0:0]:8888] READ: [id: 0xa1e65dbe, L:/10.212.203.1:8888 - R:/10.212.203.1:59781]
12:51:14.942 DEBUG [LoggingHandler.channelReadComplete] - [id: 0x12e350d3, L:/[0:0:0:0:0:0:0:0]:8888] READ COMPLETE
12:51:14.960 DEBUG [AbstractByteBuf.<clinit>] - -Dio.netty.buffer.checkAccessible: true
12:51:14.961 DEBUG [AbstractByteBuf.<clinit>] - -Dio.netty.buffer.checkBounds: true
12:51:14.962 DEBUG [ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector] - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@5e06ede8
12:51:14.973 DEBUG [ZlibCodecFactory.<clinit>] - -Dio.netty.noJdkZlibDecoder: false
12:51:14.973 DEBUG [ZlibCodecFactory.<clinit>] - -Dio.netty.noJdkZlibEncoder: false
12:51:14.988 DEBUG [Recycler.<clinit>] - -Dio.netty.recycler.maxCapacityPerThread: 4096
12:51:14.989 DEBUG [Recycler.<clinit>] - -Dio.netty.recycler.ratio: 8
12:51:14.991 DEBUG [Recycler.<clinit>] - -Dio.netty.recycler.chunkSize: 32
12:51:14.992 DEBUG [Recycler.<clinit>] - -Dio.netty.recycler.blocking: false
12:51:15.020 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /graphql HTTP/1.1
Host: 10.212.203.1:8888
Connection: keep-alive
accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
content-type: application/json
Origin: http://10.212.203.1:8888
Referer: http://10.212.203.1:8888/ui
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
content-length: 361
12:51:15.020 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /graphql HTTP/1.1
Host: 10.212.203.1:8888
Connection: keep-alive
accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
content-type: application/json
Origin: http://10.212.203.1:8888
Referer: http://10.212.203.1:8888/ui
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
content-length: 211
12:51:15.021 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /graphql HTTP/1.1
Host: 10.212.203.1:8888
Connection: keep-alive
accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
content-type: application/json
Origin: http://10.212.203.1:8888
Referer: http://10.212.203.1:8888/ui
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
content-length: 361
12:51:15.024 DEBUG [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /graphql HTTP/1.1
Host: 10.212.203.1:8888
Connection: keep-alive
accept: */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
content-type: application/json
Origin: http://10.212.203.1:8888
Referer: http://10.212.203.1:8888/ui
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
content-length: 211
12:51:15.032 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 211, cap: 211/211, unwrapped: PooledUnsafeDirectByteBuf(ridx: 614, widx: 614, cap: 2048)), decoderResult: success)
12:51:15.032 DEBUG [RequestConverter.channelRead0] - Incoming message: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 361, cap: 361/361, unwrapped: PooledUnsafeDirectByteBuf(ridx: 764, widx: 764, cap: 2048)), decoderResult: success)
12:51:15.036 DEBUG [RequestConverter.channelRead0] - End of http request: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 211, widx: 211, cap: 211/211, unwrapped: PooledUnsafeDirectByteBuf(ridx: 614, widx: 614, cap: 2048)), decoderResult: success)
12:51:15.036 DEBUG [RequestConverter.channelRead0] - End of http request: DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 361, widx: 361, cap: 361/361, unwrapped: PooledUnsafeDirectByteBuf(ridx: 764, widx: 764, cap: 2048)), decoderResult: success)
12:51:15.121 DEBUG [GraphQL.executeAsync] - Executing request. operation name: 'null'. query: 'query GetNodes {
  nodesInfo {
    nodes {
      id
      uri
      status
      maxSession
      slotCount
      stereotypes
      version
      sessionCount
      osInfo {
        version
        name
        arch
        __typename
      }
      __typename
    }
    __typename
  }
}'. variables '{}'
12:51:15.121 DEBUG [GraphQL.executeAsync] - Executing request. operation name: 'null'. query: 'query Summary {
  grid {
    uri
    totalSlots
    nodeCount
    maxSession
    sessionCount
    sessionQueueSize
    version
    __typename
  }
}'. variables '{}'
12:51:15.133 DEBUG [GraphQL.parseAndValidate] - Parsing query: 'query GetNodes {
  nodesInfo {
    nodes {
      id
      uri
      status
      maxSession
      slotCount
      stereotypes
      version
      sessionCount
      osInfo {
        version
        name
        arch
        __typename
      }
      __typename
    }
    __typename
  }
}'...
12:51:15.133 DEBUG [GraphQL.parseAndValidate] - Parsing query: 'query Summary {
  grid {
    uri
    totalSlots
    nodeCount
    maxSession
    sessionCount
    sessionQueueSize
    version
    __typename
  }
}'...
12:51:15.144 DEBUG [GraphQL.parseAndValidate] - Validating query: 'query Summary {
  grid {
    uri
    totalSlots
    nodeCount
    maxSession
    sessionCount
    sessionQueueSize
    version
    __typename
  }
}'
12:51:15.144 DEBUG [GraphQL.parseAndValidate] - Validating query: 'query GetNodes {
  nodesInfo {
    nodes {
      id
      uri
      status
      maxSession
      slotCount
      stereotypes
      version
      sessionCount
      osInfo {
        version
        name
        arch
        __typename
      }
      __typename
    }
    __typename
  }
}'
12:51:15.181 DEBUG [GraphQL.execute] - Executing 'f55b61c1-ea16-4598-af12-45e796fd2a00'. operation name: 'null'. query: 'query GetNodes {
  nodesInfo {
    nodes {
      id
      uri
      status
      maxSession
      slotCount
      stereotypes
      version
      sessionCount
      osInfo {
        version
        name
        arch
        __typename
      }
      __typename
    }
    __typename
  }
}'. variables '{}'
12:51:15.181 DEBUG [GraphQL.execute] - Executing '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6'. operation name: 'null'. query: 'query Summary {
  grid {
    uri
    totalSlots
    nodeCount
    maxSession
    sessionCount
    sessionQueueSize
    version
    __typename
  }
}'. variables '{}'
12:51:15.191 DEBUG [Execution.executeOperation] - Executing 'f55b61c1-ea16-4598-af12-45e796fd2a00' query operation: 'QUERY' using 'graphql.execution.AsyncExecutionStrategy' execution strategy
12:51:15.191 DEBUG [Execution.executeOperation] - Executing '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' query operation: 'QUERY' using 'graphql.execution.AsyncExecutionStrategy' execution strategy
12:51:15.215 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid'...
12:51:15.215 DEBUG [ExecutionStrategy.completeField] - 'f55b61c1-ea16-4598-af12-45e796fd2a00' completing field '/nodesInfo'...
12:51:15.230 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/uri'...
12:51:15.230 DEBUG [ExecutionStrategy.completeField] - 'f55b61c1-ea16-4598-af12-45e796fd2a00' completing field '/nodesInfo/nodes'...
12:51:15.234 DEBUG [ExecutionStrategy.completeField] - 'f55b61c1-ea16-4598-af12-45e796fd2a00' completing field '/nodesInfo/__typename'...
12:51:15.236 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/totalSlots'...
12:51:15.237 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/nodeCount'...
12:51:15.239 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/maxSession'...
12:51:15.240 DEBUG [GraphQL.lambda$execute$14] - Execution 'f55b61c1-ea16-4598-af12-45e796fd2a00' completed with zero errors
12:51:15.242 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/sessionCount'...
12:51:15.243 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/sessionQueueSize'...
12:51:15.245 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/version'...
12:51:15.246 DEBUG [ExecutionStrategy.completeField] - '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completing field '/grid/__typename'...
12:51:15.246 DEBUG [GraphQL.lambda$execute$14] - Execution '45f8be8b-1366-43a6-8ca1-7a4857c8d2d6' completed with zero errors
12:51:15.250 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=c812ba37ebad205352a7700d453dba55, spanId=36853a1f5048575d, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=grid.status, kind=INTERNAL, startEpochNanos=1670871075067000000, endEpochNanos=1670871075247907601, attributes=AttributesMap{data={http.method=POST, http.status_code=200, http.target=/graphql}, capacity=128, totalAddedValues=3}, totalAttributeCount=3, events=[ImmutableEventData{name=Graphql query executed, attributes={http.flavor=1, http.host="10.212.203.1:8888", http.method="POST", http.request_content_length="361", http.scheme="HTTP", http.status_code=200, http.target="/graphql", http.user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", logger="org.openqa.selenium.grid.graphql.GraphqlHandler"}, epochNanos=1670871075246977000, totalAttributeCount=9}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=OK, description=Kind: OK Description:}, hasEnded=true}
12:51:15.250 DEBUG [SeleniumSpanExporter$1.lambda$export$4] - SpanData{spanContext=ImmutableSpanContext{traceId=f6cd344ae30318f25720b7ab71bc20d5, spanId=f0df608ac4c37ff4, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=grid.status, kind=INTERNAL, startEpochNanos=1670871075067000000, endEpochNanos=1670871075247881900, attributes=AttributesMap{data={http.method=POST, http.status_code=200, http.target=/graphql}, capacity=128, totalAddedValues=3}, totalAttributeCount=3, events=[ImmutableEventData{name=Graphql query executed, attributes={http.flavor=1, http.host="10.212.203.1:8888", http.method="POST", http.request_content_length="211", http.scheme="HTTP", http.status_code=200, http.target="/graphql", http.user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", logger="org.openqa.selenium.grid.graphql.GraphqlHandler"}, epochNanos=1670871075247831200, totalAttributeCount=9}], totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=OK, description=Kind: OK Description:}, hasEnded=true}
12:51:15.256 DEBUG [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "c812ba37ebad205352a7700d453dba55","eventTime": 1670871075246977000,"eventName": "Graphql query executed","attributes": {"http.flavor": 1,"http.host": "10.212.203.1:8888","http.method": "POST","http.request_content_length": "361","http.scheme": "HTTP","http.status_code": 200,"http.target": "\u002fgraphql","http.user_agent": "Mozilla\u002f5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f108.0.0.0 Safari\u002f537.36","logger": "org.openqa.selenium.grid.graphql.GraphqlHandler"}}

12:51:15.256 DEBUG [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "f6cd344ae30318f25720b7ab71bc20d5","eventTime": 1670871075247831200,"eventName": "Graphql query executed","attributes": {"http.flavor": 1,"http.host": "10.212.203.1:8888","http.method": "POST","http.request_content_length": "211","http.scheme": "HTTP","http.status_code": 200,"http.target": "\u002fgraphql","http.user_agent": "Mozilla\u002f5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\u002f537.36 (KHTML, like Gecko) Chrome\u002f108.0.0.0 Safari\u002f537.36","logger": "org.openqa.selenium.grid.graphql.GraphqlHandler"}}

**Comment by diemol** [comment]
Seems the Node is not sending the events to the bus. Check that the VM can reach the Hub and the ports where the bus is listening.

**Comment by aswathy-krishnan-ocl** [comment]
Hello, is this issue solved?

**Comment by diemol** [comment]
What exactly? I never got a reply to the comment above.

**Comment by diemol** [comment]
Closing this issue, lack of information.
