### ISSUE TITLE
[🐛 Bug]: Selenium Manager is not working with .NetCore Project having Specflow.Specrun as runner. 

### ISSUE THREAD

**Issue by miaskadu** [SeleniumHQ/selenium#11419]
### What happened?

Hello,

I have recently tried using Selenium Manager which downloads matching driver based on Chrome Installed without using any external library. But it does not work for me using .Net 3.1 Project having Specflow.Specrun as runner, it works perfectly with Specflow.Nunit & Specflow.Xunit.

Problem with Specflow.Nunit & Specflow.Xunit is that it does not support Default.srprofile setting due to which retry & parallel execution will stop working.

Can someone suggest any alternative solution to this?

### How can we reproduce the issue?

```shell
1. Create .netCore 3.1 Project with Specflow choosing Specflow+Runner.
2. Add Selenium 4.6.0 Nuget Package
3. Try to initialize Driver.
```

### Relevant log output

```shell
Message: 
Exception has been thrown by the target of an invocation. -> The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

      Stack Trace: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
ChromeDriverService.CreateDefaultService()
ChromeDriver.ctor(ChromeOptions options)
Driver.Initialize(Browser browser, Application application) line 98
LaunchBrowser.ctor() line 14
   --- End of inner exception stack trace ---
RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
<13 more frames...>
RunnerTestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments, TimeSpan& duration)
TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance) line 481
TestExecutionEngine.OnAfterLastStep() line 234
RunnerTestExecutionEngine.OnAfterLastStep()
TestRunner.CollectScenarioErrors() line 60
CWHomeHealthFeature.ScenarioCleanup()
CWHomeHealthFeature.ClinicalWeb_AdmitAHHPatient() line 23
StaticOrInstanceMethodExecutor.ExecuteInternal(ITestThreadExecutionContext testThreadExecutionContext)
StaticOrInstanceMethodExecutor.Execute(ITestThreadExecutionContext testThreadExecutionContext)
TestNodeTask.Execute()
```

### Operating System

Windows 10

### Selenium version

4.6.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 108.0.5359.99

### What are the browser driver(s) and version(s) where you see this issue?

Chrome - 108.0.5359.99

**Comment by bonigarcia** [comment]
@miaskadu Can you try with Selenium Manager 4.7.0, please?

**Comment by miaskadu** [comment]
Tried with 4.7.0 too. It didn't worked. Can you try in your end. You will
see the line saying Chromedriver. exe not found.

**Comment by bonigarcia** [comment]
I am not an expert in .Net, but I tried the following and it works as expected:

**.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="4.7.0" />
  </ItemGroup>

</Project>
```

**.cs**
```csharp
using System;
using OpenQA.Selenium.Chrome;

 namespace Example {
     static class BasicSelenium {
          [STAThread]
          static void Main()
          {
               var driver = new ChromeDriver();
               driver.Quit();
          }

     }
}
```

**shell**
```
> dotnet run

Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 57120
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:57123/devtools/browser/96f3506f-8a05-4ac8-a815-ee29c1f73af1
```

@miaskadu Maybe you can provide a running piece of code to try to reproduce the issue.

**Comment by miaskadu** [comment]
Problem occurs when you use Specflow+Runner Project. Please find below step to create Specflow Project

1. Step I

<img width="944" alt="image" src="https://user-images.githubusercontent.com/33831305/207525220-895b1a69-a8e2-46f3-ac17-8b64aaea5a63.png">

2. Step II

<img width="796" alt="image" src="https://user-images.githubusercontent.com/33831305/207522926-237325fa-dd27-45ab-939f-4bd58066d85f.png">

3. Step III
<img width="842" alt="image" src="https://user-images.githubusercontent.com/33831305/207525009-8cb1d32b-e879-4d16-b9a5-9df34f8e630c.png">


4. Please find the below Project Zip which only focus on driver launch & it is not happening.

[SeleniumManagerWithSpecflowProject.zip](https://github.com/SeleniumHQ/selenium/files/10225012/SeleniumManagerWithSpecflowProject.zip)

**Comment by titusfortner** [comment]
You apparently need a specflow account to run this code, so we can't duplicate it.

If it is working with some Specflow products and not others, I suggest raising the issue with Specflow devs.
