### ISSUE TITLE
[🐛 Bug]: use IEDriverServer 4.7, always open edge, i need to open IE11.

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/selenium#11418]
### What happened?

I use IEDriverServer 4.7, always open edge, i need to open IE11.

### How can we reproduce the issue?

```shell
...
```

### Relevant log output

```shell
...
```

### Operating System

Windows10

### Selenium version

Java 4.7.0

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.7.0 Win32

**Comment by diemol** [comment]
You need to check what happens when you open IE directly. Microsoft made that redirection in recent updates. Most likely not related to Selenium IEServer.

**Comment by titusfortner** [comment]
There's a registry setting that IE Driver looks for to determine if it should automatically use edge. I need to find it and document it. 

That said, selenium officially does not support standalone internet explorer any longer

**Comment by titusfortner** [comment]
If this is set to "1" it will redirect to Edge automatically. If you do not want it to do that, you should be able to set it to "0" and it should work
HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Ext\\CLSID\\1FD49718-1D00-4B19-AF5F-070AF6D5D54C
