### ISSUE TITLE
[🐛 Bug]: webdriver - Process unexpectedly closed with status 127 (Geckodriver)

### ISSUE THREAD

**Issue by self-dmz** [SeleniumHQ/selenium#11414]
### What happened?

Hi!

Just trying to start working with Geckodriver get the following exception: "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 127".

Using Chrome driver the code below works fine.

webdriver-manager==3.8.5
selenium==4.7.2

Thanks in advance

### How can we reproduce the issue?

```shell
# Try to start this script

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

opts = Options()
opts.log.level = "trace"
opts.add_argument('--headless')

# ------ Process unexpectedly closed with status 127
driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))

# ------ Process unexpectedly closed with status 127
#driver = webdriver.Firefox(options=opts, executable_path=GeckoDriverManager().install())
#driver = webdriver.Firefox(executable_path="/media/dmz/HDD/geckodriver/geckodriver")

# ------ Process unexpectedly closed with status 127
#service = FirefoxService(executable_path="/media/dmz/HDD/geckodriver/geckodriver")
#driver = webdriver.Firefox(options=opts, service=service)

driver.get('https://google.com')

print(driver.title)
```

### Relevant log output

```shell
[WDM] - Downloading: 19.0kB [00:00, 6.53MB/s]                   
Traceback (most recent call last):
  File "/media/dmz/HDD/RPT/Python/techPanda/debug.py", line 11, in <module>
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
  File "/media/dmz/HDD/RPT/Python/techPanda/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/media/dmz/HDD/RPT/Python/techPanda/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/media/dmz/HDD/RPT/Python/techPanda/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/media/dmz/HDD/RPT/Python/techPanda/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/media/dmz/HDD/RPT/Python/techPanda/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 127
```

### Operating System

Linux Mint 20.3 x86_64; 5.4.0-135-generic

### Selenium version

selenium==4.7.2

### What are the browser(s) and version(s) where you see this issue?

Browser doesn't start, Firefox version = 107.0.1 (64)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver-v0.32.0-linux64

### Are you using Selenium Grid?

NO

**Comment by diemol** [comment]
What happens if you avoid `webdriver-manager`? Selenium has an embedded manager for drivers (called Selenium Manager) since 4.6.0.

**Comment by self-dmz** [comment]
# ! --- The same exception is got - "Process unexpectedly closed with  # status 127"

import time
from selenium import webdriver

driver = webdriver.Firefox()    #  selenium.common.exceptions.WebDriverException: Message: 
                                              #  Process unexpectedly closed with  # status 127

# driver = webdriver.Chrome()  --  works OK !
driver.maximize_window()
driver.get('https://google.com')
print(driver.title)

time.sleep(3)
driver.quit()

**Comment by self-dmz** [comment]
`! --- The same exception is got - "Process unexpectedly closed with # status 127"

import time
from selenium import webdriver

driver = webdriver.Firefox() # selenium.common.exceptions.WebDriverException: Message:
# Process unexpectedly closed with # status 127
driver = webdriver.Chrome() -- works OK !

driver.maximize_window()
driver.get('https://google.com/')
print(driver.title)

time.sleep(3)
driver.quit()`

**Comment by self-dmz** [comment]
`! --- The same exception is got - "Process unexpectedly closed with # status 127"

import time
from selenium import webdriver

driver = webdriver.Firefox() #  Message: Process unexpectedly closed with status 127

driver = webdriver.Chrome() # -- works OK !

driver.maximize_window()
driver.get('https://google.com/')
print(driver.title)

time.sleep(3)
driver.quit()`

**Comment by symonk** [comment]
@self-dmz can you try the same example with a virtual env that is not residing in `/media/` ?

**Comment by self-dmz** [comment]
I tired with new project created at /home... It fails with the same exception. webdriver.Chrome() works properly. The same script is used. 

> Traceback (most recent call last):
  File "/home/dmz/python/geckoIssue/debug.py", line 4, in <module>
    driver = webdriver.Firefox() # Message: Process unexpectedly closed with status 127
  File "/home/dmz/python/geckoIssue/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/home/dmz/python/geckoIssue/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/dmz/python/geckoIssue/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/dmz/python/geckoIssue/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/dmz/python/geckoIssue/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 12

**Comment by benxyzzy** [comment]
I got the same error, and a `geckodriver.log` in the working directory contained lines like

```
1672176966006	geckodriver	INFO	Listening on 127.0.0.1:38849
/snap/firefox/current/firefox.launcher: 46: exec: /snap/pycharm-professional/314/usr/lib/firefox/firefox: not found
1672176966516	mozrunner::runner	INFO	Running command: "/snap/firefox/current/firefox.launcher" "--marionette" "--remote-debugging-port" "37603" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/tmp/rust_mozprofileg3ocu3"
/snap/firefox/current/firefox.launcher: 46: exec: /snap/pycharm-professional/314/usr/lib/firefox/firefox: not found
```

You can see I am using a snap install of PyCharm which seems to be messing up the path to the firefox executable?
This is on Ubuntu 22.04, Python 3.10.6, with selenium==4.7.2 and webdriver-manager==3.8.5 installed in a venv.

(so I ran my code again in a terminal outside PyCharm and got a different error, but I guess that's a different issue):
```
1672178047545	geckodriver	INFO	Listening on 127.0.0.1:37587
1672178048153	mozrunner::runner	INFO	Running command: "/snap/bin/firefox" "--marionette" "--remote-debugging-port" "40965" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/tmp/rust_mozprofiletcMcJG"
Gtk-Message: 21:54:08.241: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
```
plus a nice popup error message window `Your Firefox profile cannot be loaded. It may be missing or inaccessible`. And the exception message this time is `Process unexpectedly closed with status 1`

**Comment by titusfortner** [comment]
Snap is a pain for selenium. It has its own driver and none of the driver managers support it. You need to explicitly pass on the location to the driver in the service constructor.

@self-dmz are you also using snap?

**Comment by benxyzzy** [comment]
Following @titusfortner 's advice and [this](https://stackoverflow.com/a/74188454/1375657), the following works for me, within PyCharm and not needing to do anything special regarding Firefox profile locations:

```
    install_dir = "/snap/firefox/current/usr/lib/firefox"
    driver_loc = os.path.join(install_dir, "geckodriver")
    binary_loc = os.path.join(install_dir, "firefox")

    service = FirefoxService(driver_loc)
    opts = webdriver.FirefoxOptions()
    opts.binary_location = binary_loc
    driver = webdriver.Firefox(service=service, options=opts)
```

Note that the `opts.binary_location` is required, not just the driver location.

`/snap/firefox/current` is a symlink to the current version directory within `/snap/firefox`, so I'm hoping that is a better way to dynamically keep pointed at the right binary + driver, without the `subprocess("find ...")` hack in the SO answer

**Comment by self-dmz** [comment]
> Snap is a pain for selenium. It has its own driver and none of the driver managers support it. You need to explicitly pass on the location to the driver in the service constructor.
> 
> @self-dmz are you also using snap?

yes, firefox installed via snap. and the scheme described by @benxyzzy also works on my PC.

**Comment by self-dmz** [comment]
> Following @titusfortner 's advice and [this](https://stackoverflow.com/a/74188454/1375657), the following works for me, within PyCharm and not needing to do anything special regarding Firefox profile locations:
> 
> ```
>     install_dir = "/snap/firefox/current/usr/lib/firefox"
>     driver_loc = os.path.join(install_dir, "geckodriver")
>     binary_loc = os.path.join(install_dir, "firefox")
> 
>     service = FirefoxService(driver_loc)
>     opts = webdriver.FirefoxOptions()
>     opts.binary_location = binary_loc
>     driver = webdriver.Firefox(service=service, options=opts)
> ```
> 
> Note that the `opts.binary_location` is required, not just the driver location.
> 
> `/snap/firefox/current` is a symlink to the current version directory within `/snap/firefox`, so I'm hoping that is a better way to dynamically keep pointed at the right binary + driver, without the `subprocess("find ...")` hack in the SO answer

many thanks, @benxyzzy! the code you provided works in my case.

**Comment by AntiPetrun** [comment]
Hi, guys! I have such problem: NameError: name 'FirefoxService' is not defined

**Comment by hotenov** [comment]
@AntiPetrun Hi! Check your imports, because in issue description more common `Service` was imported as `FirefoxService` _(with other module name)_

> from selenium.webdriver.firefox.service import Service as FirefoxService

**Comment by manel00** [comment]
Hello, still having the same issue... anyone knows how to fix it? I am using ubuntu 22

**Comment by swapnil-uptycs** [comment]
Hello, still having the same issue... anyone knows how to fix it? I am using ubuntu 20

**Comment by titusfortner** [comment]
As of Selenium 4.11, you don't need to `import as` for the service classes (https://www.selenium.dev/documentation/webdriver/drivers/service/#default-service-instance)

try:
```
    install_dir = "/snap/firefox/current/usr/lib/firefox"
    driver_loc = os.path.join(install_dir, "geckodriver")
    binary_loc = os.path.join(install_dir, "firefox")

    service = webdriver.FirefoxService(driver_loc)
    opts = webdriver.FirefoxOptions()
    opts.binary_location = binary_loc
    driver = webdriver.Firefox(service=service, options=opts)
```
