### ISSUE TITLE
[🚀 Feature]: Provide option to increase HTTP timeout by system property

### ISSUE THREAD

**Issue by hornyja4** [SeleniumHQ/selenium#11428]
### Feature and motivation

Hi, for our Selenium tests is needed to increase HTTP command timeout set by default to 3 minutes in `ClientConfig.defaultConfig()` method. We have limited amount of session on our grid and big amount of tests we are running. When test is in queue for 3 minutes, it fails on `java.net.http.HttpTimeoutException: request timed out` at `org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:286)`

I think this setting should be configurable and not hardly set. Is there any reason for 3 minutes timeout?

![image](https://user-images.githubusercontent.com/15084479/207603448-6458a914-1432-4a63-81ea-987ecaa4d2bb.png)

### Usage example

It would be great to set http timeout by system property before running test suites. Also, speed of test execution depends on speed of test environment which we cannot control, so it's logical there will be some tests in queue for more than 3 minutes.

**Comment by diemol** [comment]
You can create the `ClientConfig` you need and pass it on the client side through `RemoteWebDriver.builder().config(config)`. However, you need to adjust the timeout on the Grid as well.
