### ISSUE TITLE
[🚀 Feature]: Desired Capability for iOS 16+ disable autofill password for 3rd party apps

### ISSUE THREAD

**Issue by Sam-Levene** [SeleniumHQ/selenium#11426]
### Feature and motivation

<img width="758" alt="Screenshot 2022-12-14 at 10 07 36" src="https://user-images.githubusercontent.com/19433453/207566739-20c99e2e-8b7a-4f39-b11a-ca7908c2f62d.png">

As of iOS 16+, the default function is to enable this setting in the iPhone's Settings->Passwords-> Password Options area for 3rd party apps as standard; however this is impacting my work as a QA tester of 3rd party apps on iPhones in an automated capacity using Selenium and Appium as the Strong Password recommendation is blocking entering and recognising of data in the field. (It does not affect Selenium's ability to enter data, but does affect the ability for the app from recognising the data in the field)

<img width="422" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/19433453/207568436-4f776466-d4f5-47a0-aae6-cbcf9812ec02.png">

Can it be possible to create a desired capability to disable this autofill passwords setting so that I do not have to manually disable the setting?

### Usage example

As mentioned above, as I am a QA Automation Engineer specialising in testing 3rd party apps on iPhones, I would be using this desired capability to make sure that the autofill passwords was disabled so that I could enter data into the password field and not see the following:
<img width="422" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/19433453/207568143-7680d7de-902a-4d38-b13e-a45de6d5bba2.png">

*PLEASE NOTE* I was using an app that I found on the App store in my country and is not representative of any real-life usages, I was just testing any 3rd party app on an iPhone

**Comment by titusfortner** [comment]
iOS specific capabilities will depend on the abilities of the Apple safaridriver or the Appium team's XCUIDriver. I would raise this issue in the Appium github tracker to see if either of those drivers have a way to do that. Thanks.
