### ISSUE TITLE
[🐛 Bug]: When the download button is clicked, IEDriver is stuck and does not perform the rest of the process.

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/selenium#11425]
### What happened?

When the download button is clicked, IEDriver is stuck and does not perform the rest of the process.

When I manually refresh the page, the process continues.

### How can we reproduce the issue?

```shell
none
```

### Relevant log output

```shell
none
```

### Operating System

Windows10

### Selenium version

Java 4.7.0

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.7.0 Win32

**Comment by diemol** [comment]
Closing as no more information was given.
