### ISSUE TITLE
[🐛 Bug]: [Grid] Sessionslot not released if create session fails

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/selenium#11427]
### What happened?

Hello, 

I've configured a grid v4 as follows:
```
HUB --> NODE with Relay --> Appium --> Android emulator
```
I try to create a session on the android device
On the first try, appium is correctly called, but fails creating a session (whatever the reason, the important point is that it fails on first call. In my case, this is because I request the chrome browser without providing the right driver file)
So, if I correctly understand the behaviour, Distributor tries to recreate the session.
But this time, it fails quickly
On hub, logs are (repeated several times per second):
```
No slots found for request 23cabc3f-c004-4e28-92d7-37b291183abd and capabilities Capabilities {appium:automationName: Appium, appium:newCommandTimeout: 120, appium:platformVersion: 11, browserName: chrome, goog:chromeOptions: {args: [--disable-translate, --disable-web-security, --disable-site-isolation-tr..., --disable-features=IsolateO...], extensions: []}, nativeWebScreenshot: true, pageLoadStrategy: normal, platformName: ANDROID}
12:01:49.131 INFO [LocalDistributor.newSession] - Unable to find a free slot for request 23cabc3f-c004-4e28-92d7-37b291183abd. 
```

On node, logs are (repeated several times per second)
```
12:04:39.910 INFO [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /se/grid/node/session HTTP/1.1
User-Agent: selenium/4.7.2 (java windows)
X-REGISTRATION-SECRET: 
traceparent: 00-eee5ea07c6ca0e888db260440fc0a90f-639f321f239d9edb-01
transfer-encoding: chunked
host: 127.0.0.1:5555
accept: */*
12:04:39.910 INFO [RequestConverter.channelRead0] - Incoming message: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 604, cap: 604/604, unwrapped: PooledUnsafeDirectByteBuf(ridx: 851, widx: 851, cap: 8192)), decoderResult: success)
12:04:39.910 INFO [RequestConverter.channelRead0] - Incoming message: EmptyLastHttpContent
12:04:39.910 INFO [RequestConverter.channelRead0] - End of http request: EmptyLastHttpContent
12:04:39.913 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "eee5ea07c6ca0e888db260440fc0a90f","eventTime": 1671015879910983900,"eventName": "No slot matched the requested capabilities. ","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {appium:automationName: Appium, appium:newCommandTimeout: 120, appium:platformVersion: 11, browserName: chrome, goog:chromeOptions: {args: [--disable-translate, --disable-web-security, --disable-site-isolation-tr..., --disable-features=IsolateO...], extensions: []}, nativeWebScreenshot: true, pageLoadStrategy: normal, platformName: ANDROID}","session.request.downstreamdialect": "[W3C, OSS]"}}
```

The problem seems to be that, in LocalNode.newSession() method, when node checks for the appium slot to be available, it's seen as unavailable, as if it has not been released after the first failure
Hub/node loops on retry until session-request-timeout

As a side note, I've also seen this behaviour some times with a simple browser session, but could not reproduce this time

### How can we reproduce the issue?

```shell
No script just the above setup

Node TOML Configuration
-----------------------

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723/wd/hub"
status-endpoint = "/status"
configs = ["1","{\"browserName\":\"chrome\",\"appium:deviceName\":\"sdk_gphone_x86_64\",\"platformName\":\"ANDROID\",\"appium:platformVersion\":\"11\"}"]
```

### Relevant log output

```shell
12:04:39.910 INFO [RequestConverter.channelRead0] - Start of http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /se/grid/node/session HTTP/1.1
User-Agent: selenium/4.7.2 (java windows)
X-REGISTRATION-SECRET: 
traceparent: 00-eee5ea07c6ca0e888db260440fc0a90f-639f321f239d9edb-01
transfer-encoding: chunked
host: 127.0.0.1:5555
accept: */*
12:04:39.910 INFO [RequestConverter.channelRead0] - Incoming message: DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 604, cap: 604/604, unwrapped: PooledUnsafeDirectByteBuf(ridx: 851, widx: 851, cap: 8192)), decoderResult: success)
12:04:39.910 INFO [RequestConverter.channelRead0] - Incoming message: EmptyLastHttpContent
12:04:39.910 INFO [RequestConverter.channelRead0] - End of http request: EmptyLastHttpContent
12:04:39.913 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "eee5ea07c6ca0e888db260440fc0a90f","eventTime": 1671015879910983900,"eventName": "No slot matched the requested capabilities. ","attributes": {"current.session.count": 0,"logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {appium:automationName: Appium, appium:newCommandTimeout: 120, appium:platformVersion: 11, browserName: chrome, goog:chromeOptions: {args: [--disable-translate, --disable-web-security, --disable-site-isolation-tr..., --disable-features=IsolateO...], extensions: []}, nativeWebScreenshot: true, pageLoadStrategy: normal, platformName: ANDROID}","session.request.downstreamdialect": "[W3C, OSS]"}}
```

### Operating System

Windows 10

### Selenium version

Java => Selenium 4.7.2 on grid

### What are the browser(s) and version(s) where you see this issue?

Android emulator / appium

### What are the browser driver(s) and version(s) where you see this issue?

Appium 1.22.3

### Are you using Selenium Grid?

4.7.2

**Comment by diemol** [comment]
Can you share the full Hub, Node, and Appium Server logs?

**Comment by bhecquet** [comment]
Hello

Here are the logs
[logs_appium.txt](https://github.com/SeleniumHQ/selenium/files/10235144/logs_appium.txt)
[logs_hub.txt](https://github.com/SeleniumHQ/selenium/files/10235146/logs_hub.txt)
[logs_node.txt](https://github.com/SeleniumHQ/selenium/files/10235147/logs_node.txt)

**Comment by pujagani** [comment]
Thank you for sharing the logs. After going through them what I see is, the first error is observed at timestamp `09:22:19.061` and then the slot is blocked (it probably should be released if there is an error, will need to check this). The last log where the session is retries and does not find a slot is at timestamp `09:22:23.613`. LocalNode regularly does clean up sessions and slots that blocked and not used in a while https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/local/LocalNode.java#L187. The default value for `sessionTimeout` is 5 minutes. This can be changed by passing the "--session-timeout" to the desired value to free up the slot earlier. So far, what happen seems to align with what the Grid is expected to do. 
Not sure if I missed something here.

**Comment by bhecquet** [comment]
Hello

You see the last retry at 09:22:23.613 because I stopped the node / hub at this moment, and to avoid flooding the logs. But if I did not stop, it would continue searching for empty slot for several minutes

Reducing session timeout would reduce the search time, but according to me, the best option would be (as you mention) to see why session is not released when creation fails

Thanks for looking at my issue

**Comment by pujagani** [comment]
I understand and agree with you. But meanwhile does reducing the session timeout help? or does it still not release the slot? I am trying to narrow down the root cause.

**Comment by bhecquet** [comment]
I Will try but it will be in a week
Thanks for your help

**Comment by diemol** [comment]
I can see in the stacktraces some Java classes that do not belong to Selenium Grid, it seems you are using AspectJ to intercept the normal execution flow and alter it. The error is caused by a null pointer exception that prevents the normal flow to be executed and release the slot. 

```
09:22:19.066 WARN [SpanWrappedHttpHandler.execute] - Unable to execute request: null
java.lang.NullPointerException
	at com.infotel.seleniumrobot.grid.aspects.SessionSlotActions.onNewSession(SessionSlotActions.java:110)
	at org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:137)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession_aroundBody2(LocalNode.java:382)
	at org.openqa.selenium.grid.node.local.LocalNode$AjcClosure3.run(LocalNode.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:257)
	at com.infotel.seleniumrobot.grid.aspects.NodeActions.onNewSession(NodeActions.java:46)
	at org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:332)
	at org.openqa.selenium.grid.node.NewNodeSession.execute(NewNodeSession.java:52)
	at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle(Route.java:192)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.security.RequiresSecretFilter.lambda$apply$0(RequiresSecretFilter.java:64)
	at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute(SpanWrappedHttpHandler.java:86)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.grid.node.Node.execute(Node.java:245)
	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:336)
	at org.openqa.selenium.remote.http.Route.execute(Route.java:68)
	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64)
	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

>`	at com.infotel.seleniumrobot.grid.aspects.SessionSlotActions.onNewSession(SessionSlotActions.java:110)`

The class above does not belong to Grid. I'd recommend to have a look at your custom code.

**Comment by pujagani** [comment]
Good eye for detail @diemol!

**Comment by bhecquet** [comment]
Hello
Thanks for the observation, I will correct it and see if problèmes disappears
