### ISSUE TITLE
Getting org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session for SauceLab using selenium 3.4.0[🐛 Bug]: 

### ISSUE THREAD

**Issue by durgesh-provar** [SeleniumHQ/selenium#11430]
### What happened?

Getting org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session for SauceLab using selenium 3.4.0 only in case of "APAC Southeast" datacenter. And same is working using a selenium 4.7.0 jar. and other data centers are working fine with 3.4.0

### How can we reproduce the issue?

```shell
public static void main(String[] args) throws MalformedURLException {
    String sauceUrl = "https://{username}:{accesskey}@ondemand.apac-southeast-1.saucelabs.com/wd/hub";
    DesiredCapabilities cap = new DesiredCapabilities();
    cap.setCapability("browserName", "chrome");
    cap.setCapability("platformName", "windows 10");
    cap.setCapability("browserVersion", "latest");
    RemoteWebDriver driver = new RemoteWebDriver(new URL(sauceUrl), cap);
    driver.get("https://x.github.io/sample-todo-app/");
    System.out.println("working");
  }
```

### Relevant log output

```shell
error: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session desired capabilities = Capabilities [{securityToken=null, acceptSslCerts=true, marionette=true, build=X Test Run 2022-12-15 17:10:56 IST, acceptInsecureCerts=true, name=test.testcase, browserName=firefox, version=106.0, platform=WIN10, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@1595c99e}], required capabilities = Capabilities [{}]
```

### Operating System

windows 10

### Selenium version

3.4.0

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

**Comment by durgesh-provar** [comment]
@olleolleolle @jarib @mdub @aslakhellesoy #selenium #sauceLab
The above-raised issue is a blocker for us, Please take the above issue as your priority.

**Comment by aslakhellesoy** [comment]
@durgesh-provar this is your problem, not mine, so it’s not a priority for me.

**Comment by titusfortner** [comment]
Selenium only supports the latest version, so it is not applicable to post bugs from very old versions.

This is likely due to an issue with your syntax not getting validated as w3c compliant. I recommend upgrading to the latest version of Selenium and using the Platform Configurator provided by Sauce Labs - https://app.saucelabs.com/platform-configurator
