### ISSUE TITLE
[🐛 Bug]: `text-transform: capitalize` incorrectly cases letter after apostrophe

### ISSUE THREAD

**Issue by jeremyatenovis** [SeleniumHQ/selenium#11439]
### What happened?

The text returned incorrectly capitalizes the first letter after an apostrophe if the element has the style `text-transform: capitalize` set. 

I would expect lowercase letters to stay that way as seen in the browser. 

### How can we reproduce the issue?

```shell
I have included READMEs in the repos for quick setup instructions, assuming you already have a ruby and node environment with chrome and chromedriver set up.

Ruby example (with Capybara): https://github.com/jeremyatenovis/capybara-text-transform-bug
Node example (straight selenium driver): https://github.com/jeremyatenovis/node-selenium-bug
```

### Relevant log output

```shell
No logs, it completes normally.
```

### Operating System

MacOS 12.6.1

### Selenium version

Ruby and Node 4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.124 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

**Comment by titusfortner** [comment]
Verified this is the case is both Firefox & Chrome. I think they both use the atom, so I'm labeling it as such.

**Comment by diemol** [comment]
How can we check that they use the atom? Last time I asked about the usage of an atom they replied that there were not using most of them (I believe). Shouldn't we create issues in their trackers to get an answer?
