### ISSUE TITLE
[🐛 Bug]: Selenium Firefox extension does not allow XML to render.

### ISSUE THREAD

**Issue by karozans** [SeleniumHQ/selenium#11441]
### What happened?

I am using the latest version of Firefox for Mac Ventura 13.0 and I have the latest version of the Selenium browser extension.

I am using MAMP.
Mac OS 13.0
Apache 2.4.46
PHP 7.4.21
MySQL 5.7.34

Here is my php code...

`
$result = '<response> 
    <success>
        <code>200</code>    
        <token>blah</token>
        <entity>0</entity>  
        <message>hello</message>    
    </success>
</response>';
`

`
header('Content-Encoding: gzip');
$result = gzencode($result, 1);
echo $result;
`

If I have the Selenium extension enabled, I get just text output.  See the screen shot.

If I disable the Selenium extension, I get the nice XML format.

![with selenium browser extension](https://user-images.githubusercontent.com/91085820/208200488-64ed52bb-d38d-4804-a427-f3037ea8e490.png)
![without selenium browser extension](https://user-images.githubusercontent.com/91085820/208200491-b1f82d3c-4573-4ca1-8d63-116aa1ea3fed.png)

### How can we reproduce the issue?

```shell
`
$result = '<response> 
    <success>
        <code>200</code>    
        <token>blah</token>
        <entity>0</entity>  
        <message>hello</message>    
    </success>
</response>';
`

`
header('Content-Encoding: gzip');
$result = gzencode($result, 1);
echo $result;
`
```

### Relevant log output

```shell
See screen shots for output
```

### Operating System

Mac OS Ventura 13.0

### Selenium version

extension 3.17.4

### What are the browser(s) and version(s) where you see this issue?

Firefox 108

### What are the browser driver(s) and version(s) where you see this issue?

Gecko?

**Comment by diemol** [comment]
Which browser extension are you referring to?

**Comment by karozans** [comment]
The latest version of the Selenium IDE Firefox browser extension on Mac.

See attachment.

![Screenshot 2022-12-18 at 7 43 35 PM](https://user-images.githubusercontent.com/91085820/208337580-6f6e9305-9971-4685-aa3f-a2e303539c61.png)

**Comment by diemol** [comment]
The repository for Selenium IDE is https://github.com/SeleniumHQ/selenium-ide. But I doubt that the issue will get checked because @toddtarsi is doing great work on the new v4 (an Electron based app for Selenium IDE).
