### ISSUE TITLE
[🐛 Bug]: Unable to launch a browsers with a Selenium WebDriver 4.7.0 

### ISSUE THREAD

**Issue by balaji2711** [SeleniumHQ/selenium#11447]
### What happened?

I have just upgraded the selenium web driver version to 4.7.0. After that, I commented on all the web driver manager codes to use the selenium manager feature.

When I run the test case, I get the following error messages -

Firefox:
OpenQA.Selenium.DriverServiceNotFoundException : The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.

Chrome:
OpenQA.Selenium.DriverServiceNotFoundException : The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

Under the bin folder, I can see the selenium-manager.exe application.

![image](https://user-images.githubusercontent.com/15344129/208631050-c329ec92-777e-4269-bcc9-35903edc397a.png)

### How can we reproduce the issue?

```shell
public void OpenBrowser(string browserName, string webBaseUrl, string headlessExecution)
        {
            switch (browserName)
            {
                case "chrome":
                    var chromeOptions = new ChromeOptions();
                    chromeOptions.AddArgument("--start-maximized");
                    chromeOptions.AddArgument("--disable-notifications");
                    chromeOptions.AddArguments("--ignore-certificate-errors");
                    if (headlessExecution == "Yes")
                        chromeOptions.AddArguments("--headless");
                    //new WebDriverManager.DriverManager().SetUpDriver(new ChromeConfig());
                    driver = new ChromeDriver(chromeOptions);
                    driver.Manage().Cookies.DeleteAllCookies();
                    break;

                case "firefox":
                    var firefoxOptions = new FirefoxOptions();
                    if (headlessExecution == "Yes")
                        firefoxOptions.AddArguments("--headless");
                    //new WebDriverManager.DriverManager().SetUpDriver(new FirefoxConfig());
                    driver = new FirefoxDriver(firefoxOptions);
                    driver.Manage().Cookies.DeleteAllCookies();
                    driver.Manage().Window.Maximize();
                    break;

                case "edge":
                    //new WebDriverManager.DriverManager().SetUpDriver(new EdgeConfig());
                    driver = new EdgeDriver();
                    driver.Manage().Cookies.DeleteAllCookies();
                    driver.Manage().Window.Maximize();
                    break;

                case "ie":
                    var ieOptions = new InternetExplorerOptions();
                    ieOptions.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
                    ieOptions.IgnoreZoomLevel = true;
                    //new WebDriverManager.DriverManager().SetUpDriver(new InternetExplorerConfig());
                    driver = new InternetExplorerDriver(ieOptions);
                    driver.Manage().Cookies.DeleteAllCookies();
                    driver.Manage().Window.Maximize();
                    break;

                default:
                    throw new ArgumentException($"Browser not yet implemented - {browserName}");
            }
            driver.Navigate().GoToUrl(webBaseUrl);
        }
```

### Relevant log output

```shell
Message: 
OpenQA.Selenium.DriverServiceNotFoundException : The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

Stack Trace: 
DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
ChromeDriverService.CreateDefaultService()
ChromeDriver.ctor(ChromeOptions options)
DriverFactory.OpenBrowser(String browserName, String webBaseUrl, String headlessExecution) line 29
SeleniumActions.OpenBrowser(String browserName, String webBaseUrl, String headlessExecution) line 799
Hooks.InitializeDrivers(ScenarioContext scenarioContext) line 57
TestExecutionEngine.FireEvents(HookType hookType)
TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
TestExecutionEngine.OnScenarioStart()
TestExecutionEngine.OnAfterLastStep()
TestRunner.CollectScenarioErrors()
LoginFeature.ScenarioCleanup()
```

### Operating System

Windows 10 Enterprise

### Selenium version

Selenium Webdriver 4.7.0, Visual Studio 2022 v17.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome Version - Version 108.0.5359.125 (Official Build) (64-bit), Firefox - 102.6.0esr (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 108.0.5359.71

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
1. Check if you have a `.cache/selenium` directory in your $HOME location. What if anything is in there?
2. What happens if you navigate via command line to the directory with selenium manager and execute: `selenium-manager.exe --driver chromedriver`

**Comment by balaji2711** [comment]
Please find my inline comments -

Check if you have a .cache/selenium directory in your $HOME location. What if anything is in there?
--> Initially nothing was there. As per your step 2, I have executed this command - selenium-manager.exe --driver chromedriver and the chromedriver.exe was added.

What happens if you navigate via the command line to the directory with selenium manager and execute: selenium-manager.exe --driver chromedriver
--> Chromedriver.exe was added under .cache/selenium directory. PFA for the screen-shot

![image](https://user-images.githubusercontent.com/15344129/208766066-cf5f9f21-a283-4908-a6f9-5958bc33f7c4.png)


Again when I try to execute the tests, I get the below error message -

**Chrome:**
OpenQA.Selenium.DriverServiceNotFoundException : The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

![image](https://user-images.githubusercontent.com/15344129/208766329-dde598d8-146a-4d19-83e6-06b9f0beb3e5.png)

**Comment by titusfortner** [comment]
So, right now, the Selenium Manager is supposed to be completely hidden from the user. If Selenium Manager fails, the fix for the end user right now is to download the driver and put it on PATH just like always. This is done by catching the manager error and using the original error. The down side of this is that the reason for Selenium Manager not working is hidden except in the languages that add logging details, which .NET does not.

Really the only thing we can do right now to get the info we need is if you can debug into the Selenium Manager code in Selenium and see what the error is that we're hiding. :-/

**Comment by balaji2711** [comment]
Hi @titusfortner,

I have just debugged the selenium manager code and I don't see any error. Actually, I was able to execute it without any errors. You can refer to the attached screenshot.

![image](https://user-images.githubusercontent.com/15344129/208910513-413dee45-ab05-4fea-a6fa-7bd35666d579.png)

**Comment by titusfortner** [comment]
Does that mean you can't duplicate the error you were seeing before?
What if you delete the `~/.cache/selenium` directory (since it does some caching and might prevent errors).

**Comment by balaji2711** [comment]
After deleting the ~/.cache/selenium &  ~/.bin/Debug/net6.0/selenium-manager, I have reinstalled the web driver & support package. Now I'm able to run the scripts without any issues. Not sure what caused the issues :)

You can find the code [here](https://github.com/balaji2711/CoreAutomator)
