### ISSUE TITLE
[🐛 Bug]: Cannot start local standalone since 4.5.1+

### ISSUE THREAD

**Issue by mokena1990** [SeleniumHQ/selenium#11448]
### What happened?

Hello, Since 4.5.1 version of grid-server cannot start standalone server.
If version of grid is 4.5.0 or lower, then everything starting well.

### How can we reproduce the issue?

```shell
Config config = new MemoizedConfig(
  new MapConfig(ImmutableMap.of(
    "server", Map.ofEntries(Map.entry("port", parsePort()), Map.entry("host", "127.0.0.1")),
    "node", Map.ofEntries(Map.entry("detect-drivers", "true"))))
);
try {
  Standalone standalone = new Standalone();
  server = standalone.asServer(config);
} catch (Exception e) {
  throw new RuntimeException("Can't start SeleniumServer!\n" + e);
}
```

### Relevant log output

```shell
java.lang.NoSuchMethodError: 'boolean org.openqa.selenium.WebDriverInfo.isSupportingBiDi()'

---

org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:156)
org.openqa.selenium.grid.commands.Standalone.createHandlers(Standalone.java:206)
org.openqa.selenium.grid.TemplateGridServerCommand.asServer(TemplateGridServerCommand.java:41)
ru.hh.tests.functional.utils.core.SeleniumServerInit.<init>(SeleniumServerInit.java:67)
ru.hh.tests.functional.utils.core.SeleniumServerInit.<clinit>(SeleniumServerInit.java:26)
ru.hh.tests.functional.utils.core.TestCaseBaseImpl.startLocalServer(TestCaseBaseImpl.java:60)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:372)
org.testng.SuiteRunner.run(SuiteRunner.java:330)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
org.testng.TestNG.runSuites(TestNG.java:1099)
org.testng.TestNG.run(TestNG.java:1067)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

### Operating System

Linux Manjaro

### Selenium version

Java 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.124

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

### Are you using Selenium Grid?

4.7.2

**Comment by krmahadevan** [comment]
@mokena1990 - Can you please share what does your dependencies look like ?

**Comment by pujagani** [comment]
+1 on @krmahadevan's comment. I tried to reproduce the error and was unable to with 4.7.2. The server starts as expected. It would be nice if you could share a reproducible project to reproduce the issue.

**Comment by mokena1990** [comment]
Selenium dependencies look like:
```
<properties>
    <selenium.version>4.7.2</selenium.version>
</properties>

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-grid</artifactId>
    <version>${selenium.version}</version>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>${selenium.version}</version>
    <exclusions>
        <exclusion>
            <groupId>io.netty</groupId>
            <artifactId>netty</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

Removing exclusion is not helping

**Comment by krmahadevan** [comment]
@mokena1990 - I have tried creating a sample project with just that dependencies that you shared. It works fine and I dont see the errors that you are experiencing.

Can you please check with this attached project? If there are changes, please help add them to the pom file and share a project. That way its easier to reproduce the problem.
[github-11448.zip](https://github.com/SeleniumHQ/selenium/files/10274761/github-11448.zip)

**Comment by pujagani** [comment]
Thank you for sharing the details! The sample I tried also has the same dependencies. It feels more like a project setup issue or sometimes when using an IDE like IntelliJ the cache needs to be cleared and restarted. Maybe that might help.

**Comment by mokena1990** [comment]
> @mokena1990 - I have tried creating a sample project with just that dependencies that you shared. It works fine and I dont see the errors that you are experiencing.
> 
> Can you please check with this attached project? If there are changes, please help add them to the pom file and share a project. That way its easier to reproduce the problem. [github-11448.zip](https://github.com/SeleniumHQ/selenium/files/10274761/github-11448.zip)

Yep, server starting fine, @krmahadevan @pujagani  thanks for your help.
I'll look problem on my side.
