### ISSUE TITLE
[🐛 Bug]: Type ahead help suggesting incompatible methods for .window()

### ISSUE THREAD

**Issue by stephaniecp** [SeleniumHQ/selenium#11440]
### What happened?

The type ahead help (seen in Visual Studios Code 1.73.0) is misleading when trying to get or set a screen size with .window(). The .getSize and .setSize are suggested even though they are only available for WebElements.  When a user uses .window(), it is my understanding that the type ahead should suggest .getRect or .setRect instead. 

(Failing) To get the screen size :
`await this.driver.manage().window().getSize()`

(Failing) To set screen :
```
let width = 700
let height = 500
await this.driver.manage().window().setSize({x: 0, y: 0, width: width, height: height})
```

The two examples above kept leading to an error “.getSize is not a function” even though the type ahead help suggests otherwise. I was able to resolve the issue and have my test pass by changing my code with the solutions below. 

(Passing) To get the screen size :
`await this.driver.manage().window().getRect()`

(Passing) To set screen :
```
let width = 700
let height = 500
await this.driver.manage().window().setRect({x: 0, y: 0, width: width, height: height})
```

### How can we reproduce the issue?

```shell
await this.driver.manage().window().getSize();

let width = 700;
let height = 500;
await this.driver.manage().window().setSize({x: 0, y: 0, width: width, height: height});
```

### Relevant log output

```shell
.getSize is not a function
```

### Operating System

MacOS 12.1

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

Version 108.0.5359.124 (Official Build) (x86_64)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
size and position methods should still work and be special wrappers of the rect method. @harsha509 can you verify? Thanks.

**Comment by harsha509** [comment]
HI @titusfortner ,

JS bindings doesn't have them so far, it is as `setRect` and `getRect`. Let me add this wrappers as it is available in other language bindings !

**Comment by harsha509** [comment]
Added wrappers with this [commit](https://github.com/SeleniumHQ/selenium/commit/2ac53b831f446b27b9def1745ac961e79c108726)!
