### ISSUE TITLE
selenium-bom for Maven artifacts?

### ISSUE THREAD

**Issue by psiroky** [SeleniumHQ/selenium#1144]
Hello,

would it make sense to have `org.seleniumhq.selenium:selenium-bom` which would define versions (in `dependencyMangement`) of all Selenium Java artifacts? 

There is already a BOM that is being maintained by Arquillian community (https://github.com/arquillian/arquillian-selenium-bom). It needs to be maintained by someone else and it needs to be kept up to date. If it would be directly in Selenium source, it would be automatically available with every new release.

Are there reasons why it was decided not to have such BOM? Or it simply wasn't done yet? (I might have some time to help here...)

**Comment by lukeis** [comment]
I think just no one has cared to do one. Also, I don't see much point in them, I personally prefer to be more explicit in my poms and define the dependency management section myself and rely on the dependency convergence plugin to make sure things are acting correctly.

I'm not opposed to a Pull Request being made.

**Comment by psiroky** [comment]
Thanks for quick response @lukeis! I will try to add the BOM and will create PR when I find some spare time.

**Comment by joergsesterhenn** [comment]
We would also like to use this at our company. If you have to maintain parentpoms for big enterprises BOMs can safe you a lot of maintenance time. 

The BOM provided by Arquillian could be used as template. I asked them to consider a PR here instead of updating their BOM: https://github.com/arquillian/arquillian-selenium-bom/issues/23

**Comment by shs96c** [comment]
This will require us to patch https://github.com/bazelbuild/rules_jvm_external to support this functionality.

**Comment by remal** [comment]
Please keep it open

**Comment by diemol** [comment]
Would you like to contribute and work on this @remal?

Otherwise, this has been open for 7 years and there is not a huge interest in it.

**Comment by diemol** [comment]
Folks, I am going to close this and if someone wants to jump and help us, we are always available in our chat https://www.selenium.dev/support/.
