### ISSUE TITLE
[🐛 Bug]: Improve Appium - Selenium integration tests

### ISSUE THREAD

**Issue by nir-tal-talkspace** [SeleniumHQ/selenium#11453]
### What happened?

As a result of https://github.com/appium/java-client/issues/1823
Appium always pulls the latest Selenium version - and there is no way to override this (I used the dependency management tag in the pom.xml for Selenium and also try to exclude it from Appium dependency).
The Appium client will fail if there are deprecation tickets that weren't implemented
Here is an example: 
https://github.com/SeleniumHQ/selenium/issues/11347

A native mobile-web cross-platform test is performed on our project using Chrome devtools (which forces us to use the most recent version of Selenium).
As a result, devtools-related bugs can also terminate our mobile efforts, such as this one:
https://github.com/SeleniumHQ/selenium/issues/11401

From a Selenium perspective, I wonder if there is a better way to test Appium. prior to this implementation: 
https://github.com/SeleniumHQ/selenium/issues/11355 

Thanks.

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by nir-tal-talkspace** [comment]
@titusfortner @diemol @mykola-mokhnach

**Comment by titusfortner** [comment]
The fix we have planned for this issue is #11355. If you have a specific suggestion for what else we can do differently, I think both projects would be receptive. Questions or discussions for alternatives should be in either Selenium or Appium Slack, not in a Github issue.
