### ISSUE TITLE
[🐛 Bug]: NullPointerException with jdk http client

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/selenium#11450]
### What happened?

When trying to connect a jdk http client webdriver to a grid using a proxy (with authentication) I get a java.lang.NullPointerException.

### How can we reproduce the issue?

```shell
		System.setProperty("webdriver.http.factory", "jdk-http-client");

		ChromeOptions browserOptions = new ChromeOptions();
		browserOptions.setPlatformName("Linux");

		java.net.Authenticator auth = new java.net.Authenticator() {
			public PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication("username", "pwd".toCharArray());
			}
		};
		java.net.Authenticator.setDefault(auth);

		Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy", port));

		ClientConfig config = ClientConfig.defaultConfig()
				.connectionTimeout(Duration.ofSeconds(45))
				.readTimeout(Duration.ofSeconds(45))
				.proxy(proxy)
				.baseUrl(new URL("gridUrl"));

		HttpCommandExecutor executor = new HttpCommandExecutor(config);
		
		WebDriver driver = new RemoteWebDriver(executor, browserOptions);
```

### Relevant log output

```shell
Caused by: java.lang.NullPointerException
	at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
	at org.openqa.selenium.remote.http.jdk.JdkHttpMessages.lambda$createResponse$4(JdkHttpMessages.java:149)
	at org.openqa.selenium.remote.http.Contents.bytes(Contents.java:80)
	at org.openqa.selenium.remote.http.Contents.string(Contents.java:97)
	at org.openqa.selenium.remote.http.Contents.string(Contents.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:131)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:535)
	... 3 more
```

### Operating System

Windows 10

### Selenium version

Java 4.7.2

### What are the browser(s) and version(s) where you see this issue?

all

### What are the browser driver(s) and version(s) where you see this issue?

all

**Comment by pujagani** [comment]
Thank you for sharing the details. 

I am sharing my understanding of this issue. 
From the stacktrace it seems as if the response received has an issue and we need to fix checks around the same. 
Based on Java docs, Line 149 of JdkHttpMessages states that 

```
Returns the body. Depending on the type of T, the returned body may represent the body after it was read (such as byte[], or String, or Path) or it may represent an object with which the body is read, such as an InputStream.
If this HttpResponse was returned from an invocation of previousResponse() then this method returns null"
```

JavaDoc of previousResponse() states that: 
```
Returns an Optional containing the previous intermediate response if one was received. An intermediate response is one that is received as a result of redirection or authentication. If no previous response was received then an empty Optional is returned.
```

From this, I think adding a null check for the response body should fix it and I will add that fix. But there is no way to test it.
The code snippet is not sufficient to reproduce the issue since it is using a cloud provider. It would be nice if you could share a reproducible code snippet so we can reproduce it and test the fix. Thank you so much!

**Comment by erik-rnbt** [comment]
@pujagani Thanks for the help.

I updated the code above and testet it with a grid that uses no proxy and one grid that needs a proxy. The one without a proxy works and as soon as you add the proxy and switch to the other grid it throws that exception. That might help you to reproduce the issue.

**Comment by pujagani** [comment]
Thank you for the prompt response. How are you using a proxy with the Grid? Just want to ensure the setup is the same.

**Comment by pujagani** [comment]
@erik-rnbt  I have added a null check which might be potentially causing the error. I am mostly hoping it resolves the issue faced. It will be available as part of the next release which will happen in Jan 1st week or so.

**Comment by erik-rnbt** [comment]
Thank you for the quick help. I'll try it out as soon as possible.
