### ISSUE TITLE
[🚀 Feature]: Cleanup downloaded files in Node (Grid)

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#11457]
### Feature and motivation

Grid has now a feature that allows a user to fetch a downloaded file in the Node. This implies that the user downloads the file before, and as sessions get created and ended, potentially the configured download directory will fill up with files. We need to find a way to clean up that directory based on some criteria.

### Usage example

N/A
This is to keep the Node machine healthy.

**Comment by titusfortner** [comment]
The ideal is to implement subdirectories per session.

If the browser stores the uuid, we could implement: `DELETE /session/:sessionId:/se/file/:uuid:` and have the bindings send this as part of `quit()`.

Ideally the node can somehow map the directory with the session and delete it as part of the quit / cleanup process.

**Comment by diemol** [comment]
This was implemented through #11702
