### ISSUE TITLE
[🐛 Bug]: send_keys have unexpected behavior for certain commands

### ISSUE THREAD

**Issue by doscon-git** [SeleniumHQ/selenium#11456]
### What happened?

I am encountering a problem when trying to send the command for creating a new tab, enabling "find" or enabling full screen with the send_keys method or the ActionChains class.

With the Chromedriver and firefox none of the commands do anything when using the ActionChains class.

Sending keys to an element (body) does something when using the Firefox driver, but only for certain commands and it doesn't do what is expected. In my case I send F11 to get fullscreen, but the windows scrolls down instead.

Tried this on a Windows 10 machine and on an Raspberry pi 4 running the latest Raspbian. 

### How can we reproduce the issue?

```shell
from selenium import webdriver
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

# create webdriver object

driver = webdriver.Chrome() # Can be replaced with Chrome() 
driver.capabilities['browserVersion']
driver.get("https://nrk.no") # could be any webpage, but the scroll down effect is visible on this one.

action = ActionChains(driver)
#%%
action.send_keys(Keys.F11).perform() # Nothing happens
time.sleep(1)
driver.find_element("tag name",'body').send_keys(Keys.F11) # scrolls down on Firefox
time.sleep(1)
driver.find_element("tag name",'body').send_keys(Keys.CONTROL + 't') # Nothing happens
time.sleep(1)
action.key_down(Keys.CONTROL).send_keys("t").key_up(Keys.CONTROL).perform() # Nothing happens
time.sleep(1)
action.key_down(Keys.CONTROL).send_keys('F').key_up(Keys.CONTROL).perform() # Nothing happens
time.sleep(1)
action.key_down(Keys.ALT).send_keys('D').key_up(Keys.ALT).perform() # Nothing happens
```

### Relevant log output

```shell
No logs that I can find.
```

### Operating System

Windows 10, Raspbian

### Selenium version

python 3.9.13, Selenium 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 108.0.1 (64-bit), Chrome 108.0.5359.100 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71, Firefox '108.0.1'

**Comment by titusfortner** [comment]
I think this is pretty much by design. There are explicit methods now for switching to a new window or tab; and there is also scrolling support in the actions class directly so you don't need key strokes for that. 

At the very least there is nothing Selenium project can do to make this work, it is up to the drivers themselves what they support and how.

**Comment by doscon-git** [comment]
> I think this is pretty much by design. There are explicit methods now for switching to a new window or tab; and there is also scrolling support in the actions class directly so you don't need key strokes for that.
> 
> At the very least there is nothing Selenium project can do to make this work, it is up to the drivers themselves what they support and how.

Ah, so things have changed, so many out of date guides. I used the explicit methods to do this initially, but when I was changing tabs while in full screen mode (F11) the browser exited fullscreen mode every time. I will have to look into something else to avoid this then. Thanks for the reply.

**Comment by titusfortner** [comment]
Out of date guides are always going to be a problem with an 18 year old project 😦 Especially when our documentation is so far behind.

Oh, yeah If it pulls out of full screen mode to change tabs, that'll be a driver bug. Is that both Firefox & Chrome? But yeah, there's a method for fullscreen mode as well.

**Comment by doscon-git** [comment]
> Out of date guides are always going to be a problem with an 18 year old project 😦 Especially when our documentation is so far behind.
> 
> Oh, yeah If it pulls out of full screen mode to change tabs, that'll be a driver bug. Is that both Firefox & Chrome? But yeah, there's a method for fullscreen mode as well.

Did some more testing and it appears that chrome always reverts back to its original size (when created) when switching tabs. Firefox keeps the full screen when switching tabs, but seems to keep focus on the address bar when creating a new tab thereby preventing the fullscreen from taking effect. Probably some way of defocusing the address field. Just creating all needed tabs initially then fullscreening the window seems to do the trick for Firefox.

**Comment by titusfortner** [comment]
Interesting. ok.

The links for the specific driver bug trackers are in the auto-generated comments above if you want to request different behavior.

**Comment by doscon-git** [comment]
> Interesting. ok.
> 
> The links for the specific driver bug trackers are in the auto-generated comments above if you want to request different behavior.

Checked the link and found this: https://sites.google.com/a/chromium.org/chromedriver/help/keyboard-support
Apparently if you don't have a US-QWERTY keyboard installed some keys will get lost. I did install that now, but still no go. Made a comment in the tracker.
