### ISSUE TITLE
[🚀 Feature]: Deprecate Headless Methods

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11467]
### Feature and motivation

I initially proposed changing to the new Headless (#11099), but @jimevans  convinced us we should just deprecate the method entirely and have people choose what they want in the `args`.

This change will require writing a blog post explaining the change and advertising the new Chrome method, and adding examples to the documentation.

### Usage example

Deprecate this:
```ruby
options = Selenium::WebDriver::Options.chrome
options.headless!
```
and advertise this:
```ruby
options = Selenium::WebDriver::Options.chrome(args: ['--headless=chrome'])
```

**Comment by BorisOsipov** [comment]
Hi @titusfortner!

>This change will require writing a blog post explaining the change and advertising the new Chrome method, and adding examples to the documentation.

I would love to read more about the new Chrome headless mode. Do you know of any blogposts, wikis, or other resources that provide an explanation of the new mode?

**Comment by titusfortner** [comment]
There are none! Which is why we want to write a blog post. 😁 

Literally everything I know about it is [in the code](https://chromium.googlesource.com/chromium/src/+/833543a511a970f44fb074b9f30c6b6268e0be71%5E%21/#F0) and in [the commit message:](https://chromium.googlesource.com/chromium/src/+/833543a511a970f44fb074b9f30c6b6268e0be71).

**Comment by titusfortner** [comment]
All of these have been merged now.

**Comment by karlicoss** [comment]
Just FYI: seems that since chrome 109 you need to use `--headless=new` instead of `--headless=chrome`: https://bugs.chromium.org/p/chromium/issues/detail?id=1380881

Otherwise you get this error

```
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://dimnlpajniiodipidfegljbgmiokjdak/_generated_background_page.html
```

**Comment by titusfortner** [comment]
Yes, I added it to the comments in the commits, e.g., https://github.com/SeleniumHQ/selenium/commit/edfb8faed464e2283cc69e25df47507e1d3542b1
