### ISSUE TITLE
[🚀 Feature]: allow listening to CDP responses and events

### ISSUE THREAD

**Issue by muodov** [SeleniumHQ/selenium#11463]
### Feature and motivation

The existing CDP JS API ([CDPConnection](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/devtools/CDPConnection.js)) is quite basic, but for a full coverage it needs just two more things:

- being able to listen to responses (i.e. incoming messages with matching `id`)
- being able to assign callbacks to events (i.e. incoming messages without `id`). Note that the existing `callback` argument in `execute()` is not that - it's just called when the message is sent.

### Usage example

I have an existing Node app using CDP, and I'm trying to make it work with Selenium Grid. I hope to use the Grid's distributed browser management and keep using CDP for the actual automation commands.

Right now I can certainly do this by instrumenting `CDPConnection._wsConnection` manually, but I'm concerned about future compatibility.

**Comment by pujagani** [comment]
Can you please elaborate on the concern regarding future compatibility and the use case you have for this feature? 
We particularly don't encourage users to use raw CDP APIs as it is since it is version dependent and it might break as the CDP version changes. https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/ 

We encourage users to use user-friendly APIs instead. Additionally, to overcome the shortcomings of CDP and allow multiple browser support BiDi protocol is under work. Refer to https://w3c.github.io/webdriver-bidi/ and https://developer.chrome.com/blog/webdriver-bidi/. Selenium is working together with browser vendors to support the same Initial work is started in JS bindings too. Our long-term goal is to support BiDi and eventually deprecate and remove CDP.

**Comment by muodov** [comment]
@pujagani we have an existing app that is based on puppeteer/CDP, and I'm trying to allow distributed browser pool using Selenium Grid. I'm quite excited about BiDi, but it is not yet ready for our use case. Besides, refactoring the existing codebase would take time.

My concerns about future compatibility stem from the fact that `createCDPConnection()` implicitly [sends some CDP commands](https://github.com/SeleniumHQ/selenium/blob/2ac53b831f446b27b9def1745ac961e79c108726/javascript/node/selenium-webdriver/lib/webdriver.js#L1240). Right now it's pretty innocent, but it may have to do more in the future, which could conflict with whatever the embedding app might be doing if it reuses `CDPConnection._wsConnection`. For this reason, I'm currently just making a [separate WS connection](https://github.com/duckduckgo/tracker-radar-collector/blob/selenium-grid/helpers/selenium.js#L58) to `/session/{sessionId}/se/cdp` and instrument that. It seems to work well, but if I just need the raw CDP, it would be handy to have simple send/receive API in selenium binding itself, since it already has a fitting abstraction `CDPConnection`.

Technically it seems not too difficult to implement, and I'm happy to propose a PR if the selenium team thinks it makes sense.

**Comment by pujagani** [comment]
I understand your use case. Thank you for sharing the details. I appreciate your help to contribute to Selenium and all contributions are welcome. 
However, CDP support is not long-term and it will be removed at some point so adding something at this point and then later removing it will not be ideal for users. Selenium does not recommend sending raw CDP commands. Hence,  additional APIs that support the same do not align with that.  We will not be adding anything further for CDP support except just to keep it updated version-wise until BiDi support takes over fully.
I understand adaptation to BiDi will require code refactoring but all browser vendors themselves will move to BiDi completely at some point and they are currently working towards it actively in collaboration with Selenium. 

Appreciate your help and thought here! But unfortunately, it does not align with the long-term goal Selenium has for CDP.
