### ISSUE TITLE
[🐛 Bug]: Element.clear() fails when document requires Trusted Types

### ISSUE THREAD

**Issue by tosmolka** [SeleniumHQ/selenium#11461]
### What happened?

We are trying to use Selenium to instrument a website that requires [Trusted Types](https://w3c.github.io/trusted-types/dist/spec/) in browser that supports Trusted Types (Chrome/Edge) and it works in most parts. 

What fails is an attempt to call `.clear()` on element with `contenteditable="true"` attribute. This is (most likely) due to the fact that implementation uses empty string assignment into `.innerHTML` property. 

https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/javascript/atoms/action.js#L122

Suggested fix is to achieve the same by other means, without assignment to `.innerHTML`: 

```js
element.textContent = goog.userAgent.GECKO ? ' ' : '';
```

or 

```js
while (element.firstChild) {
  element.removeChild(element.firstChild);
}
```

Or other fix, not sure about differences in behavior between browsers (Firefox). Firefox could even continue using current implementation since it does not support Trusted Types and this bug will not repro there. 

### How can we reproduce the issue?

```shell
const { Builder, By } = require('selenium-webdriver');

(async () => {
    const driver = await new Builder()
      .forBrowser('chrome')
      .build();
    try {
        await driver.get('data:text/html,' + `<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script';" />
  </head>
  <body>
    <div id="test" contenteditable="true">Test</div>
  </body>
</html>
`);
        const element = await driver.findElement(By.id('test'));
        await element.clear();
    } finally {
        await driver.quit();
    }
})();
```

### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:60538/devtools/browser/77b3e399-feb0-42c1-840d-6f54e8a54e4e
c:\Temp\test-selenium\node_modules\selenium-webdriver\lib\error.js:524
    let err = new ctor(data.message)
              ^

JavascriptError: javascript error: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
  (Session info: chrome=108.0.5359.125)
    at Object.throwDecodedError (c:\Temp\test-selenium\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (c:\Temp\test-selenium\node_modules\selenium-webdriver\lib\http.js:587:13)
    at Executor.execute (c:\Temp\test-selenium\node_modules\selenium-webdriver\lib\http.js:515:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (c:\Temp\test-selenium\node_modules\selenium-webdriver\lib\webdriver.js:741:17)
    at async c:\Temp\test-selenium\src\test.js:19:9 {
  remoteStacktrace: 'Backtrace:\n' +
    '\t(No symbol) [0x0093F243]\n' +
    '\t(No symbol) [0x008C7FD1]\n' +
    '\t(No symbol) [0x007BD04D]\n' +
    '\t(No symbol) [0x007BFD34]\n' +
    '\t(No symbol) [0x007BFBE5]\n' +
    '\t(No symbol) [0x007BFE80]\n' +
    '\t(No symbol) [0x007E4C87]\n' +
    '\t(No symbol) [0x0080858C]\n' +
    '\t(No symbol) [0x007E2BFF]\n' +
    '\t(No symbol) [0x00808804]\n' +
    '\t(No symbol) [0x0081C9EB]\n' +
    '\t(No symbol) [0x00808386]\n' +
    '\t(No symbol) [0x007E163C]\n' +
    '\t(No symbol) [0x007E269D]\n' +
    '\tGetHandleVerifier [0x00BD9A22+2655074]\n' +
    '\tGetHandleVerifier [0x00BCCA24+2601828]\n' +
    '\tGetHandleVerifier [0x009E8C0A+619850]\n' +
    '\tGetHandleVerifier [0x009E7830+614768]\n' +
    '\t(No symbol) [0x008D05FC]\n' +
    '\t(No symbol) [0x008D5968]\n' +
    '\t(No symbol) [0x008D5A55]\n' +
    '\t(No symbol) [0x008E051B]\n' +
    '\tBaseThreadInitThunk [0x765F7D69+25]\n' +
    '\tRtlInitializeExceptionChain [0x7768BB9B+107]\n' +
    '\tRtlClearBits [0x7768BB1F+191]\n'
}
```

### Operating System

Windows 11

### Selenium version

JavaScript 4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.125 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

**Comment by titusfortner** [comment]
My first inclination is to close this and ask it be reported to chromedriver bug tracker, but if they are using the atoms we generate (I'm not sure if they are), then it'll just come back here, so let's see if we can run it down.

**Comment by tosmolka** [comment]
@titusfortner , https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/selenium-atoms/README.chromium suggests that ChromeDriver generates atoms from Selenium and applies minor patches.

**Comment by titusfortner** [comment]
Well, that makes sense, then. Do you have a suggestion for an alternate way of changing that value that is compatible with trusted html? I'm not familiar with it at all.

**Comment by tosmolka** [comment]
I think the general consensus in the community is that it's best to replace `.innerHTML = ""` with `.textContent = ""` (see https://github.com/w3c/trusted-types/issues/343). Would that work?

**Comment by titusfortner** [comment]
Want to make a PR? I'm not an atoms expert, but easier to get people to weigh in on a PR. 😄

**Comment by tosmolka** [comment]
I was not able to run atom tests in my environment, not sure why. I need to fix that before attempting a PR :). 

I ran `bazel run debug-server`  and pointed browser to http://localhost:2310/javascript/atoms/test/action_test.html . Test was unable to load http://localhost:2310/javascript/deps.js (404) and failed. I tried fixing by changing path to http://localhost:2310/javascript/atoms/deps.js but then got more 404s for other dependencies . 

Do you know if atom tests are in working order in trunk? Any idea how to fix the issues above? Thanks.

**Comment by titusfortner** [comment]
Wow, yeah, I don't think I've actually ever tried to run the atoms tests.

Just make the change in a PR and we can discuss with the chrome/Firefox devs.

Is there a public website I can get this to fail on? Absolute worst case I can build IE driver with change to the atom and verify it works.

**Comment by xiaotuzididi** [comment]
thankyou verymuch

**Comment by MohammedWaasim** [comment]
Hi There, 
Even I am facing this issue. 
The scenario is:
I am trying to read the file name which is downloaded in runtime from chrome://downloads/

below is the code 
`(String) evaluateJavascript("return document.querySelector('downloads-manager').shadowRoot.querySelector('#downloadsList downloads-item').shadowRoot.querySelector('div#content #file-link').text");`

and the exception found is 
`rg.openqa.selenium.JavascriptException: javascript error: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
  (Session info: chrome=109.0.5414.120)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'`

please help...

**Comment by titusfortner** [comment]
I think we agreed at the last TLC meeting to merge #1504 and ping Google about updating Chromedriver with the result. It's been a long time since we've updated this code, so we're actually not certain the process, but we're working on it. 😄
