### ISSUE TITLE
[🐛 Bug]: Console Window Geckodriver since v4.6.0

### ISSUE THREAD

**Issue by ReMiOS** [SeleniumHQ/selenium#11465]
## System

* Version: geckodriver 0.32.0
* Platform: Windows 11 / Python 3.9.13 
* Firefox: 108.0.1
* Selenium: 4.6.0 and above

## Testcase

After updating Selenium from 4.5.0 to any higher version the geckodriver console window cannot be hidden.
( using Pyinstaller with --noconsole and --onefile option )

I've tried various options in the code, but none seems to hide the console window

Using CREATE_NO_WINDOW worked until selenium v4.6.0:
```
service = Service( geckodriver )
service.creationflags = subprocess.CREATE_NO_WINDOW
```

Tried adding the code below, but without result
`options.add_argument('--disable-gpu') `

```
flag = 0x08000000  # No-Window flag
webdriver.common.service.subprocess.Popen = functools.partial(webdriver.common.service.subprocess.Popen, creationflags=flag )
or webdriver.common.service.subprocess.Popen = functools.partial( subprocess.Popen, creationflags=flag )
```

### How can we reproduce the issue?

```shell
Use selenium and make exe using Pyinstaller with --noconsole and --onefile options
```

### Relevant log output

```shell
just a blank screen
```

### Operating System

Windows 11

### Selenium version

4.6.0+

### What are the browser(s) and version(s) where you see this issue?

Firefox: 108.0.1

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.32.0

### Are you using Selenium Grid?

-

**Comment by titusfortner** [comment]
I don't understand what you are trying to do. Geckodriver is executed without a console by default. You're saying when you package Selenium as an executable it does get displayed by default?

**Comment by ReMiOS** [comment]
Yes excact that
I have an Python script to automate some tasks in Firefox, but since v2.6.0 (also tried 2.6.1 and 2.7.2) 
i get a console window when i try to package it as an executable (using pyinstaller or nuitka).

![geckodriver](https://user-images.githubusercontent.com/6001204/209020387-c605fe21-c49c-4b65-bf54-213650515a98.png)

**Comment by titusfortner** [comment]
@symonk do you remember what we addd in 4.6.

Like, we don't explicitly support your use case, but if there is something we did that we can see an obvious update that solves your issue, we can do that.

**Comment by ReMiOS** [comment]
To reproduce this issue the following code can be used
( change the path location of the firefox.exe and geckodriver.exe for your system )

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
import subprocess
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

binary = FirefoxBinary( fr'''c:\DEMO\FirefoxPortable\App\Firefox64\firefox.exe''' )

ff_service = Service( 'geckodriver.exe' )       
ff_service.creationflags = subprocess.CREATE_NO_WINDOW
        
firefox_options = Options()        
firefox_options.binary_location = binary
firefox_options.add_argument('--disable-gpu') 
browser = webdriver.Firefox( service = ff_service, options = firefox_options )        
browser.get( 'http:\\www.google.com' )

time.sleep( 100 )
```

Make exe package:
`pyinstaller -w -F ff_example.py`

run the test:
```
copy dist\ff_example.exe .
ff_example.exe
```

**Comment by ReMiOS** [comment]
I've updated to Selenium v4.8.0 but unfortunately this does not fix this issue.

**Comment by ReMiOS** [comment]
I think it's caused bij the ABC method that was introduced in the commom/service.py in v4.6+

```
class Service(ABC):
    """The abstract base class for all service objects.  Services typically
    launch a child program in a new process as an interim process to
    communicate with a browser.

```

For now i've fixed it by adding some startupinfo to the subprocess.Popen command

**Comment by AutomatedTester** [comment]
Feel free to submit a PR

**Comment by ReMiOS** [comment]
I don't have much experience with an PR on Github... 
trying to clone the repository gave me an permission error

**Comment by whimboo** [comment]
@ReMiOS you should always be able to clone the repository. Can you please tell us the steps you did and which error you got? Then Selenium folks can help.

**Comment by ReMiOS** [comment]
> @ReMiOS you should always be able to clone the repository. Can you please tell us the steps you did and which error you got? Then Selenium folks can help.

I agree, cloning the repository on linux is no issue. 
But i cannot clone on Windows 11 ... 

In this post i've described on how to reproduce the problem:
[(https://github.com/SeleniumHQ/selenium/issues/11465#issuecomment-1362977172)](https://github.com/SeleniumHQ/selenium/issues/11465#issuecomment-1362977172)

**Comment by symonk** [comment]
Thanks for the recreatable example, i'll take a look - right off the bat we don't allow subprocess `creation_flags` to be passed into services, we probably should! t he service implementation needs a bit of an overhaul to be much more consistent and give much better control to pretty much anytime passed into subprocess spawning

**Comment by symonk** [comment]
@ReMiOS I don't have a `windows` VM handy, but at a quick glance I will assume because this isn't strictly 'public API' it was renamed to be pythonic as `self.creation_flags` and you are now using the old name which has no impact, python won't error here either as it'll bolt onto the instance.  Can you please try with `service.creation_flags = ...` and I'm certain it will work as before.

Commit can be referenced [here](https://github.com/SeleniumHQ/selenium/commit/ba04acdf9ea3e53c483cc38a1ae796496e5da9c1#diff-646e4c91d7ef7fbd2b4c088347c86f5b2d2cab8121b14987f3cb783ad120634cL46)

**Comment by ReMiOS** [comment]
Thanks !
I can confirm changing self.creationflags to self.creation_flags made the geckodriver console window remain hidden.
