### ISSUE TITLE
[🐛 Bug]: Edge in IE mode - The HTTP request to the remote WebDriver server for URL timed out after 60 seconds

### ISSUE THREAD

**Issue by manalikajale** [SeleniumHQ/selenium#11484]
### What happened?

when trying to open any url in Edge with IE mode on, I am receiving exception as  "The HTTP request to the remote WebDriver server for URL timed out after 60 seconds"
Settings - 
URL added to trusted site for IE options
URL added Edge setting to open in compatibility mode 

### How can we reproduce the issue?

```shell
var ieOptions = new InternetExplorerOptions();
 ieOptions.AttachToEdgeChrome = true;
 ieOptions.EdgeExecutablePath = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
 var IEDriverPath = @"C:\Drivers\EdgeIEModeDriver";
 IWebDriver driver = new InternetExplorerDriver(IEDriverPath, ieOptions);
 driver.Manage().Window.Maximize();
 string Url = "http://total-qa.com/";
            try
            {
                driver.Navigate().GoToUrl(Url);
             
                driver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(40));
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(40);


               IWebElement Loginbutton = driver.FindElement(By.XPath("//*[text()='LOGIN']"));
                Loginbutton.Click();
            }
            catch (Exception e) { }
Thread.Sleep(5000);
driver.Quit();
```

### Relevant log output

```shell
Message = "The HTTP request to the remote WebDriver server for URL http://localhost:14204/session/959b5634-39dc-4593-8d40-79ab5f7de066/url timed out after 60 seconds."
```

### Operating System

windows 10

### Selenium version

C# - Selenium.WebDriver 4.7.0 

### What are the browser(s) and version(s) where you see this issue?

Edge Version 108.0.1462.54 (Official build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

IEdriverserver 4.7

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
You have to also set protected mode in registry. I outlined it here https://titusfortner.com/2022/09/28/edge-ie-mode.html
