### ISSUE TITLE
[🐛 Bug]: Chrome Driver throwing an Exception when starting chrome with a defined User-Profile from --user-data-dir--

### ISSUE THREAD

**Issue by Jonsch-HTL** [SeleniumHQ/selenium#11489]
### What happened?

For my Project to automate a carting process in need to start Chrome with a definded Chrome-Profile. To do so I added an   argument to the ChromeOptions as following: options_name.add_argument(f'--user-data-dir={profile}')
-->i already defined profile above: 
profile = '--user-data-dir=C:\\Users\\jonsc\\AppData\\Local\\Google\\Chrome\\User Data\\Default'

Now when i run my program an Exception keeps popping up before starting Chrome.
<img width="319" alt="Exception" src="https://user-images.githubusercontent.com/79207600/209695127-2f7aa3de-00b6-4dc2-88ba-937fb3a66b94.png">
I can just click OK and the program will continue as if nothing happened. 
Can somebody tell me how to fix this?

### How can we reproduce the issue?

```shell
import undetected_chromedriver as uc
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

if __name__ == '__main__':
    url = 'https://www.nike.com/at/t/jumpman-two-trey-herrenschuh-XsmXZK/DO1925-001'
    service_object_name = Service('C:\Chrome-Driver106\driver107\chromedriver.exe')
    profile = '--user-data-dir=	C:\\Users\\"ENTER YOUR USER"\\AppData\\Local\\Google\\Chrome\\User Data\\Default'

    options_name = uc.ChromeOptions()
    options_name.add_argument("--start-maximized")
    options_name.add_argument("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36")
    options_name.add_argument(f'--user-data-dir={profile}')

    browser = uc.Chrome(service=service_object_name, options=options_name, user_subprocess=True)
    browser.get(url)
```

### Relevant log output

```shell
-
```

### Operating System

Windows 11

### Selenium version

Python 3.10

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.125

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 106

**Comment by titusfortner** [comment]
The string you are sending to add argument appears to be:
```
"--user-data-dir=--user-data-dir=C:\Users\jonsc\AppData\Local\Google\Chrome\User Data\Default"
```

Per [ChromeDriver documentation](https://chromedriver.chromium.org/capabilities), you want to send the equivalent of:
```
options.addArguments("user-data-dir=/path/to/your/custom/profile");
```

Further, any issues with what is passed in to these capabilities are going to be issues in the driver and need to be raised with Google, or `undetected_chromedriver`, which we do not support.

**Comment by deleyva** [comment]
In my case I had to add these two lines:

```python
options.add_argument("user-data-dir=/Users/myuser/Library/Application Support/Google/Chrome")
options.add_argument("--profile-directory=Default")
```

But now, it starts with the correct profile but crashes in a second.

**Comment by Scylla2020** [comment]
> In my case I had to add these two lines:
> 
> ```python
> options.add_argument("user-data-dir=/Users/myuser/Library/Application Support/Google/Chrome")
> options.add_argument("--profile-directory=Default")
> ```
> 
> But now, it starts with the correct profile but crashes in a second.

Hi you found any solution to this?

**Comment by pushkinman** [comment]
@Scylla2020 , I've had this exact problem. It was solved by fully quitting Chrome before I ran the code. Sadly this error is thrown every time if you have an instance of Chrome open.
