### ISSUE TITLE
Console processing event, does not send objects. Dotnet [🚀 Feature]: 

### ISSUE THREAD

**Issue by Qialet** [SeleniumHQ/selenium#11487]
### Feature and motivation

Hello. I get the data from the browser console using this code:

```
ChromeOptions options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);
BROWSER = new ChromeDriver(options);

IJavaScriptEngine monitor = new JavaScriptEngine(BROWSER);
monitor.JavaScriptConsoleApiCalled += EventConsole;
Task.Run(() => monitor.StartEventMonitoring());
```

In fact, it gets all the information, BUT! Sometimes json text is sent to the console in the form of objects that the selenium does not send either by object, due to the fact that it was not implemented in principle, or by text, due to the fact that it simply receives 0 object, and sends, ignoring everything else.

My thoughts, I think the error is here, you take out the first object, but ignore the rest, which may possibly contain other information. 

```
        private void OnConsoleApiCalled(object sender, ConsoleApiCalledEventArgs e)
        {
            if (this.JavaScriptConsoleApiCalled != null)
            {
                this.JavaScriptConsoleApiCalled(this, new JavaScriptConsoleApiCalledEventArgs()
                {
                    MessageContent = e.Arguments[0].Value,
                    MessageTimeStamp = e.Timestamp,
                    MessageType = e.Type
                });
            }
        }
```
Source: https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/JavaScriptEngine.cs#L391

I really need a solution to this problem now, I tried to fix your build, but when I try to build the library, it gives an error that there is no path to 2 files, which you really don't have for some reason.

I also apologize if there is an alternative way to get the object, or such a question has already been asked.

### Usage example

To be honest, I do not know what to write here, because I am literally 5% of the information out of 100%... The remaining 95% are in an object that I have no way to get.

**Comment by Qialet** [comment]
The site from which I get the data uses console.log("text", object). Additional information: https://developer.chrome.com/docs/devtools/console/api/#log

**Comment by titusfortner** [comment]
If #12669 did not address this issue, we'll need a new reproducible case.
