### ISSUE TITLE
[🐛 Bug]: Getting timed out message from renderer

### ISSUE THREAD

**Issue by sdet-ab** [SeleniumHQ/selenium#11492]
### What happened?

I am using 
selenium driver version - 4.7.2 revision # 4d4020c3b7
Edge Browser - 107.0.1418.62
OS - Windows 10 64 bit
Java version - 1.8.0_281

Error description - 
After I click on a button inside my webpage a window should appear with list of records which is appearing blank when I tried using my simple Selenium click code. When I tried opening the records page manually it works fine.

I tried multiple browser and selenium version to make sure compatibility issues with driver and browser are not causing below error however the issues are still present.

Error details -
Timed out receiving message from renderer: 3.000 Error in function WebClick

I tried multiple options for wait and edge options for Page load strategy (Eager,None,Normal) but no avail.

### How can we reproduce the issue?

```shell
After I click on a button inside my webpage a window should appear with list of records which is appearing blank when I tried using my simple Selenium click code. When I tried opening the records page manually it works fine.

There is no detailed code as such. I am clicking on one button, which supposed to show record details in separate window however the page loads as blank as Error shown in selenium log as time out in renderer
```

### Relevant log output

```shell
Timed out receiving message from renderer: 3.000
```

### Operating System

Windows 10 64 bit

### Selenium version

Java 4.7.2 revision # 4d4020c3b7

### What are the browser(s) and version(s) where you see this issue?

MS Edge 100,107,108

### What are the browser driver(s) and version(s) where you see this issue?

Edge 107.0.1418.62

### Are you using Selenium Grid?

No

**Comment by pujagani** [comment]
The error you are receiving is from the browser. It could be due to the specific page not loading completely or having some dependencies it is trying to load. Even plugins/pop-ups cause issues sometimes, so please check on your end if the website you are trying to load is getting blocked from being loaded. Please check the wait times also that are being set in the code.
