### ISSUE TITLE
[🐛 Bug]: Selenium grid's load balance is not working

### ISSUE THREAD

**Issue by dylanz666** [SeleniumHQ/selenium#11493]
### What happened?

I have 3 machines.

1 machine is hub and have 1 node
1 machine is node
1 machine is node

When I run my tests with 6 concurrency,
Then only 1 machine will be touched,
Here is the screenshot.

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/25168679/209822311-e0b0657c-441a-49ba-be8f-e430718660f4.png">

I expected 6 tests should be distributed to these 3 machines so that it is load balance per whole selenium server system perspective.

Any suggestion?

### How can we reproduce the issue?

```shell
Please see what happened.
```

### Relevant log output

```shell
no
```

### Operating System

mac

### Selenium version

Java 4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver for chrome 108

### Are you using Selenium Grid?

Jar 4.7.1

**Comment by xiaotuzididi** [comment]
good very good

**Comment by diemol** [comment]
Closing as no more information was given.
