### ISSUE TITLE
[🐛 Bug]: selenium server crashes with memory allocation error

### ISSUE THREAD

**Issue by muodov** [SeleniumHQ/selenium#11518]
### What happened?

I have a selenium Grid node where I run Chromium instances. After a while (usually several hours), the selenium-server jar crashes with a memory error (see below). However, in fact there is plenty of memory available. The same happens to the hub instance, if I run a node on the same machine. I couldn't figure out what's causing it, so I'm looking for advice what else I should check.

## Set up:
OS: Ubuntu 20.04
Kernel version: 5.4.0-1023-azure
Java version: openjdk 11.0.15
nodejs version: 16.16.0
Specs: 64GB RAM, 32 cores (VM on Azure)
Selenium server version: 4.7.2
Chromium version: 108.0.5359.124
Chromedriver: 108.0.5359.124
Selenium server started with concurrency 20

## What I see in console:

```
$ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xmx8g -jar selenium-server-4.7.2.jar node --hub use-crawler-worker2 --max-sessions 20

<...>

03:25:54.465 INFO [SessionSlot.stop] - Stopping session ff5f417d1d6712859c0d70601f1ee874
Starting ChromeDriver 108.0.5359.124 (603c1cb86aff29563721da2a6351c0d08865350d-refs/branch-heads/5359@{#1179}) on port 6649
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fb24e9f5000, 16384, 0) failed; error='Not enough space' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/mtsoy/hs_err_pid211781.log
$
```

See also the crash log file below

## State after the crash:

- I see 20 chromedriver processes started just before the crash, and a bunch of chromium processes spun up by them.
- in total ~230 processes and ~1500 threads

More details including kernel parameters can be found in crash log file attached

## What I have tried so far:
- checking ulimit and kernel parameters like max_threads - all seems high enough, and there's never more than 3k active threads according to htop
- reducing Java heap to 8gb using -Xmx8g
- reducing the node concurrency I tried 15, 20 and 30 with the same result, although higher concurrency increases the chance of crash. Machine this big ought to be enough for such load, and I don't think crash is expected in any case.

### How can we reproduce the issue?

```shell
// request a remote browser using selenium-webdriver:
let driver = await (new Builder()
    .usingServer(options.seleniumHub)
    .forBrowser('chrome')
    .setChromeOptions(opts)
    .build());

// connect to CDP using puppeteer:
const host = new URL(seleniumHub).host;
const sessionId = await driver.getSession().then(session => session.getId());
const debuggerUrl = `ws://${host}/session/${sessionId}/se/cdp`;
const browser = await puppeteer.connect({
    browserWSEndpoint: debuggerUrl,
});
browserContext = browser.defaultBrowserContext();

// ... test some website using CDP here ...

// when done, clean up:

await browserContext.browser().disconnect(); // disconnect puppeteer
await driver.quit(); // close the browser

// repeat for another url
```

### Relevant log output

[hs_err_pid211781.log](https://github.com/SeleniumHQ/selenium/files/10359404/hs_err_pid211781.log)

### Operating System

Ubuntu 20.04

### Selenium version

openjdk 11.0.15, selenium-webdriver JS bindings 4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chromium 108.0.5359.124

### What are the browser driver(s) and version(s) where you see this issue?

108.0.5359.124

### Are you using Selenium Grid?

4.7.2

**Comment by diemol** [comment]
Isn't `-Xmx8g` limiting the size of the Grid Node? Also, what are you actually running? A Hub and a Node on a single machine? Can you please describe what your setup is and share the commands and logs of each Grid process that starts?

**Comment by muodov** [comment]
@diemol sorry, let me clarify. I'm running two identical servers: one with the hub and the script and another is running the node.
I have most problems with the node, but the problem is likely not specific to the node components because if I run a second node (with less concurrency) on the first server, the hub starts to crash too. 

-Xmx indeed limits the heap, but that's the point: according to the error log, the allocation error happens in the _java runtime_, which uses memory outside of the Java heap. In any case, it doesn't help. I suspect that the problem is actually caused not by the lack of memory, but by something else. I initially thought the system ran out of pids (this can sometimes be reported as ENOMEM), but the number of threads is not that high, and the limits are generous.

As for the exact commands, I have described it in the issue. I use selenium only to spawn a browser and connect to CDP. After that I'm only sending cdp commands before quitting the browser.

**Comment by diemol** [comment]
Still, I would need to see the commands and logs for each Grid process (and in which machine is running) to understand better the issue. So far it is not clear how the Grid is configured.

**Comment by diemol** [comment]
I will close this as no more information was provided.

**Comment by krmahadevan** [comment]
@muodov - 

I see that the command you are using to start the node when this crash happened is

```
Command Line: -Xmx8g selenium-server-4.7.2.jar node --hub use-crawler-worker2 --max-sessions 20
```

I noticed that there's no swap space left from the crash logs that you shared

```
SwapTotal:             0 kB
SwapFree:              0 kB
```

and the file header has this 

```
# Native memory allocation (mmap) failed to map 16384 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.
```

Maybe adding more swap space could help here? 

I am just going [this blog](https://jagadesh4java.blogspot.com/2014/09/analyzing-jvm-crash.html) to understand how to parse the crash file and calling this out. I am no expert in this area (atleast not yet)
