### ISSUE TITLE
IE11 exceptions with IEDriverServer: Unable to get browser

### ISSUE THREAD

**Issue by pedkoz** [SeleniumHQ/selenium#1151]
Hi the trouble is when it is running the line: 
        if (webDriver.getPageSource().contains("CertUnknownCA")) {

or the line: 
            webDriver
                    .navigate()
                    .to("javascript:document.getElementById('overridelink').click()");

I get an error: 
Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 17 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'PCUELLO-QA', ip: '192.168.24.215', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Session ID: 1e950c48-aa70-4574-8dfa-02304721d5fc
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:47678/, handlesAlerts=true, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]

It was working fine, i have a function for skipping certified:
    public void skipSecurityCertificate() throws InterruptedException {
        System.out.println("Reviso CertUnknown");
        // If certificate page appears
        if (webDriver.getPageSource().contains("CertUnknownCA")) {
            webDriver
                    .navigate()
                    .to("javascript:document.getElementById('overridelink').click()");
        }
    }

It works on firefox and Chrome and it was working fine with IE. However it doesn't work now in IE11 Version; 11.0.9600.18015

I have IEDriverserver.exe Version 2.48.0 with selenium standalone version: 2.48.2 the lastest version nowdays.

I am running tests on Windows 7 Professional with operative system 64 bits.

Best regards,

**Comment by chadmyers** [comment]
Some things to try:

 1. Make sure your URL is in the Trusted Sites (may or may not help)
 2. Make sure to set up the FEATURE_BFCACHE registry key for both 32-bit and 64-bit registry ([instructions here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6511#issuecomment-192149755))

**Comment by pedkoz** [comment]
Hi,

About first point: I will try, but i think that if I disable manually the protected mode in IE and all my tests run fine, this is not the solution for the trouble, but I will try.

About second point: I have already this added to my registry: 
![image](https://cloud.githubusercontent.com/assets/13293723/23698428/ca9e23b4-03eb-11e7-99f1-759beb1a5806.png)

Thank you very much by answering.

**Comment by RickChihu** [comment]
"On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode"." Uncheck all boxes
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver

**Comment by barancev** [comment]
Is this issue still actual?

**Comment by barancev** [comment]
Closing the issue, it's related to antique IE driver versions and seems to be not relevant anymore.
