### ISSUE TITLE
[🐛 Bug]: Docker selenium Node is only taking the first network found at inspection time (not all the networks)

### ISSUE THREAD

**Issue by dbire** [SeleniumHQ/selenium#11528]
### What happened?

My context is following:

- I am using a docker selenium grid, based on a generic node
  It's docker-compose defines 2 networks:
    - networkA
    - networkB

- I am testing docker web app
  It's docker-compose defines 1 network:
   - networkB

When selenium creates a browser container (whatever which browser is used) and I inspect the created container, I can see rthat the container is only attached to networkA, so my selenium test is failing because cannot resolve my web app container on networkB

I guess this is due to that code: **String networkName = firstNetworkEntry.getKey();** in 
[(https://github.com/SeleniumHQ/selenium/blob/fad29a31254e8b143515381dfc84f2b9484be6f1/java/src/org/openqa/selenium/docker/v1_41/InspectContainer.java)]

Honestly, I don't know if it is a bug or it has been designed like that ? If it is the case may be it should be documented ? 

### How can we reproduce the issue?

```shell
- Run a docker selenium grid with a selenium node which has at least 2 networks defined in it's docker-compose.
- Run any selenium test and put a sleep in it so you have enough time to inspect the container created.
- You should see only one network (the first one given by the inspection of the container)
```

### Relevant log output

```shell
n/a
```

### Operating System

Ubuntu

### Selenium version

selenium/node-docker:4.5.3-20221024

### What are the browser(s) and version(s) where you see this issue?

chrome 106

### What are the browser driver(s) and version(s) where you see this issue?

selenium/node-docker:4.5.3-20221024

### Are you using Selenium Grid?

selenium/hub:4.5.3-20221024

**Comment by diemol** [comment]
This is not clear what the expectation should be. The code you are referring to is only used in Dynamic Grid, which you do not seem to be using. For questions, please use the links below and we'd be happy to reply in our chat.

**Comment by dbire** [comment]
Thanks @diemol for the quick response ! Some clarifications from side:

- I do use a Docker dynamic grid
- My expectation is that the selenium container created should inherit from the same networks than the its generic node it was based on.

**Comment by diemol** [comment]
The child containers will be created under the network where the `node-docker` container is placed.

**Comment by dbire** [comment]
Hi @diemol , I have pushed the code to reproduce and explain in more details the issue here:  [https://github.com/dbire/selenium_issue_11528](https://github.com/dbire/selenium_issue_11528)
