### ISSUE TITLE
[🚀 Feature]: Selenium Manager support Safari & Technology Preview

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11522]
### Feature and motivation

Ok, I get this is kind of dumb, but looking at the Selenium implementations, it would be much easier not to have to treat Safari special. Should be pretty simple to hard code the locations and error if the driver isn't in those locations

### Usage example

```
selenium-manager --browser safari
selenium-manager --driver safaridriver
==> /usr/bin/safaridriver
```
and
```
selenium-manager --browser "Safari\ Technology\ Preview"
selenium-manager --browser SafariTechnologyPreview
selenium-manager --browser SafariTP
==> /Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver
```

**Comment by titusfortner** [comment]
Hmm, just noticed that Ruby doesn't hard code `/usr/bin/safaridriver` and just looks on PATH, and then only stores the location for Technology Preview

**Comment by diemol** [comment]
I do not understand, what would do Selenium Manager for Safari? Can it be enabled through the command line without any user interaction? (I believe you need to enter your password to enable it, right?)

**Comment by titusfortner** [comment]
My thought was that Selenium Manager could store the hard coded locations of the binaries so that we could avoid having 2 constructors — https://github.com/SeleniumHQ/selenium/pull/11491/files#diff-c9e7b1e932fcdfafa7fd1c615d09d8b411f2eabdff0fd1410c397b9aa5ed88f7R18

It's a minor thing, but allows us to treat all drivers the same. /shrug

**Comment by diemol** [comment]
I see. Would then the bindings query Selenium Manager to get the binaries location? Maybe I do not see the whole picture but seems an over optimization.

**Comment by titusfortner** [comment]
My thoughts for desired DriverFinder behavior:
1. If the user explicitly passes in a path for the driver in Service class (constructor/builder/setter depending on language) before driver constructor, then DriverFinder is never called
2. If DriverFinder is called it first checks for Property (Java only)
3. If no property is set/all other languages Selenium Manager:
    * Determines target browser/version (based on Options or defaults)
    * Checks PATH for valid driver (#11373); uses if valid, ignores if invalid
    * Gets list of valid versions & downloads correct version for use
    * If download unsuccessful and out of date version is present, it gets used as backup
 
So, this issue would be for Selenium Manager to look at the hard coded location of safaridriver before checking PATH, then check PATH. It would fail if not found because there is nothing to download. The minor optimization is to push as much of the finding logic into the Manager as possible instead of having to create Safari-only code.

**Comment by diemol** [comment]
@bonigarcia, this was implemented, right?

**Comment by bonigarcia** [comment]
@diemol Yes, it was done in #11609.

**Comment by diemol** [comment]
Great, thank you.
