### ISSUE TITLE
[🐛 Bug]: Python Error - WebDriverException - Message: chrome not reachable

### ISSUE THREAD

**Issue by Canario0001** [SeleniumHQ/selenium#11533]
### What happened?

I am using Python to automate something in my work.
I have to get to specific website and grab a file, which can be easily automated with selenium.

The code works in my personal computer but won't work on any machine I tested here at work.

I think it may be Windows 11 problem or the network we use here.

The code to reproduce is not the entire program, but the important part to solve this issue

### How can we reproduce the issue?

```py
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep, strftime, perf_counter
from os import getenv
from dotenv import load_dotenv

options = webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches', ['enable-logging'])
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
driver.maximize_window()
```

### Relevant log output

```shell
Exception has occurred: WebDriverException
Message: chrome not reachable
Stacktrace:
Backtrace:
	(No symbol) [0x00C5F243]
	(No symbol) [0x00BE7FD1]
	(No symbol) [0x00ADCF10]
	(No symbol) [0x00AD2B0A]
	(No symbol) [0x00AFF04E]
	(No symbol) [0x00AFA97C]
	(No symbol) [0x00AF82E9]
	(No symbol) [0x00B2F056]
	(No symbol) [0x00B2EB2A]
	(No symbol) [0x00B28386]
	(No symbol) [0x00B0163C]
	(No symbol) [0x00B0269D]
	GetHandleVerifier [0x00EF9A22+2655074]
	GetHandleVerifier [0x00EECA24+2601828]
	GetHandleVerifier [0x00D08C0A+619850]
	GetHandleVerifier [0x00D07830+614768]
	(No symbol) [0x00BF05FC]
	(No symbol) [0x00BF5968]
	(No symbol) [0x00BF5A55]
	(No symbol) [0x00C0051B]
	BaseThreadInitThunk [0x76417D69+25]
	RtlInitializeExceptionChain [0x7731BB9B+107]
	RtlClearBits [0x7731BB1F+191]
  File "path/to/the/python/script.py", line 17, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
```

### Operating System

Windows 11 and 10

### Selenium version

Python 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

I have no idea as I am not using the `executable_path` param, but the `service` param.

**Comment by diemol** [comment]
Most likely the work machine does not have the same setup as your personal one. Please follow https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/ and if you have more questions, please reach out to us through the links shown below.

**Comment by Canario0001** [comment]
After some research, I discovered that the problem is related to some AV we use at the company. Thanks for the answers, and sorry for wasting your time.
