### ISSUE TITLE
[🐛 Bug]:  Python bindings don't handle space in class name

### ISSUE THREAD

**Issue by cpeck-rmvd** [SeleniumHQ/selenium#11548]
### What happened?

Currently in the python bindings, this snippet in the find_element and find_elements functions (from `py/selenium/webdriver/remote/webelement.py`):

```
 elif by == By.CLASS_NAME:
            by = By.CSS_SELECTOR
            value = f".{value}"
```

If there are spaces in the class name, it looks for the css selector `'.class_1 class_2 class_3` for example, which fails due to the spaces. I would rather it look for the full value, like this:

```
elif by == By.CLASS_NAME:
            by = By.CSS_SELECTOR
            value = f"[class='{value}']"
```
Although, from our `'class1 class2 class3'` example, it will fail if the user just specifies 'class1'. I suppose this would address that:

```
elif by == By.CLASS_NAME:
            by = By.CSS_SELECTOR
            value = '.' + value.replace(' ', '.')
```
This is confusing for new users, particularly since the resulting error reveals that a css_selector is in fact being used here.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get('https://www.google.com')
"""
Google has a div that looks like this:


<div class="gbqfba gbqfba-hvr" role="presentation" aria-label=""
style="display: none; font-family: Roboto, arial, sans-serif;
overflow: hidden; text-align: center; z-index: 50; height: 34px;
position: absolute; left: 290px; margin: 0px; top: 81px; width: 111px;"
tabindex="-1"><div style="left: 0px; position: absolute; right: 0px;
white-space: nowrap; top: -105px;"><div
"""
driver.find_element(By.CLASS_NAME, 'gbqfba gbqfba-hvr')

"""
Result:

selenium.common.exceptions.NoSuchElementException: Message: no such element: 
Unable to locate element: {"method":"css selector","selector":".gbqfba gbqfba-hvr"}
"""
```

### Relevant log output

```shell
selenium.common.exceptions.NoSuchElementException: Message: no such element: 
Unable to locate element: {"method":"css selector","selector":".gbqfba gbqfba-hvr"}
```

### Operating System

MacOS big sur

### Selenium version

py - 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.94

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.30

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
Class name locators are just for one class. If you want to search for multiple classes you need to use a css selector locator.
