### ISSUE TITLE
[🐛 Bug]: Python WebDriverWait until can take longer than self._timeout to return

### ISSUE THREAD

**Issue by dariopnc** [SeleniumHQ/selenium#11547]
### What happened?

My expectation for the `until` method is that it checks the method provided for as long as `self._timeout` and than return.

What is happening in some cases is that it can be waiting for significantly longer times before giving a return

### How can we reproduce the issue?

```shell
I can reproduce the issue by temporarily disconnecting my PC (and then my code) from the internet, before launching the `until` method.
I can do this on my laptop by turning off WiFi or suspend/resume.
After this network interruption, the controller browser is still alive, I can still navigate the page but if a line containing the `until` method is executed, the code keeps on waiting for way longer than the timeout given (I think around 30 minutes where the timeout was 30 seconds)
```

### Relevant log output

```shell
Only logs I have are from my code, help me obtain useful logs
```

### Operating System

Windows 10

### Selenium version

Python 4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.126

### What are the browser driver(s) and version(s) where you see this issue?

'108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016})'

**Comment by titusfortner** [comment]
So, the `until` method is a way of polling for a condition to be true. The assumption is that the condition can be evaluated immediately, and that the code will continue to execute the condition until it returns true or until the timeout is reached.

If the evaluation of the condition itself takes longer than the provided timeout, the `until` code has nothing to poll for. The code is behaving as intended.
