### ISSUE TITLE
[🐛 Bug]: Getting error of The active test run was aborted. Reason: Test host process crashed

### ISSUE THREAD

**Issue by amitkpal83** [SeleniumHQ/selenium#11540]
### What happened?

We are using linux chrome image to execute selenium test cases. Everything is working fine till we have parallelism=10. But once we start increasing the parallelism to more than 10 to reduce the execution time we are getting the below errors:

The active test run was aborted. Reason: Test host process crashed : [1673449059.734][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1673449059.734][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
Test Run Aborted 

### How can we reproduce the issue?

```shell
Having basic test cases. Not able to share the code due to client policies.
```

### Relevant log output

```shell
The active test run was aborted. Reason: Test host process crashed : [1673449059.734][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1673449059.734][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
Test Run Aborted
```

### Operating System

Linux

### Selenium version

3.141

### What are the browser(s) and version(s) where you see this issue?

chrome 103

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 103

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
This is most likely due to the lack of resources. If you run 10 tests in parallel you should be having 10 CPUs available, once you go up, then more resources are needed. This sizing guidelines can help https://www.selenium.dev/documentation/grid/getting_started/#grid-sizes. If you have more questions, please check the links below.
