### ISSUE TITLE
[🐛 Bug]: VSCode Code is unreachable

### ISSUE THREAD

**Issue by markman641** [SeleniumHQ/selenium#11543]
### What happened?

Using the webdriver.Chrome() makes the code below unreachable using VSCode and Pylance. There's [this ](11398) issue which was closed and the solution was to upgrade Selenium and VSCode but this problem seems to persist on selenium==4.7.2 and VSCode==1.74.3

Everything still executes perfectly, it is just warning in the editor.

Pylance == `v2023.1.20`
VSCode == `1.74.3`
Selenium == `4.7.2`
Python == `3.10.5`

### How can we reproduce the issue?

```shell
`from selenium import webdriver

webdriver.Chrome()

# Code is "unreachable" because of the previous line

a = 1
print(a)`
```

### Relevant log output

```shell
Code is unreachable (Pylance)
```

### Operating System

Windows 11

### Selenium version

4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.125

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 108

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
We have not made any releases since then that could have broken this, have you reached out to Pylance?

**Comment by titusfortner** [comment]
I wonder if there is something that the newer version of Python or Pylance thinks is wrong with our code that it was ok with at a previous version... It's just a warning, so it's not high priority. Our typing support is still in progress.

**Comment by symonk** [comment]
Hi @markman641 could you try with the latest?  I cannot recreate with the following it reports the code is accessible just fine:

```
vscode : 1.74.3
pylance extension : 2023.1.40
selenium : 4.8.0 (also same on 4.7.2)
```

in your `output` tab, have a look in the `python` drop down logs to see if anything odd is happening with `pylance` etc.

Please feel free to re-open this if you find it to be still broken when you upgrade, but I cannot recreate.
