### ISSUE TITLE
[🐛 Bug]: java16 not found module  processed.jcommander

### ISSUE THREAD

**Issue by yuruotong1** [SeleniumHQ/selenium#11556]
### What happened?

when using java16 with module,  my selenium version is 4.7.2, an error was showen: "not found module  processed.jcommander and processed.async.http.client"

### How can we reproduce the issue?

```shell
i think, the problem because selenium-remote-driver.
```

### Relevant log output

```shell
java: 找不到模块: processed.async.http.client
java: 找不到模块: processed.jcommander
```

### Operating System

winsows11

### Selenium version

4.7.2

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

none

### Are you using Selenium Grid?

none

**Comment by yuruotong1** [comment]
Below is my module-info.java.The problem should be in the red arrow line:

![image](https://user-images.githubusercontent.com/31992251/212779710-50dbcd77-5212-4c63-9dff-0eb324dd6d16.png)

**Comment by pujagani** [comment]
Apologies, I attached the wrong tag by mistake.

**Comment by diemol** [comment]
Closing as no more information was given.

**Comment by olivier-duval** [comment]
Hello

I got the exact same problem when I use java module (for example with javafx) in java 17 (with version 4.8.2). This problem is described for example at https://stackoverflow.com/questions/74892632/compilation-error-with-maven-on-intellij-module-not-found-processed-jcommander

So even the simplest program like:

```
package dev.selenium.hello;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class HelloSelenium {
    public static void main(String[] args) {
        WebDriver driver = new ChromeDriver();

        driver.get("https://selenium.dev");

        driver.quit();
    }
}
```

with a "module-info.java" containing
`requires org.seleniumhq.selenium.chrome_driver;`

doesn't work and fail with error:
```
> Task :compileJava FAILED
error: module not found: processed.jcommander
error: module not found: processed.async.http.client
2 errors
```

The problem seem to come from the jar **selenium-remote-driver-4.8.1.jar** that contains the following lines in the **module-info.java** :
```
    requires processed.async.http.client;
    requires processed.jcommander;
```
However, the dependency on **jcommander-1.82.jar** (not a module) should be referenced as:
```
    requires async.http.client;
    requires jcommander;
```
to be compliant with "automatic module" rules (if I understand correctly because - strangely - it doesn't seem to be a problem for provided.toml for example)

Some suggestions (like "use java 1.8") are not really satisfactory. Would it be possible to correct this problem or provide a workaround compatible with module please ?

**Comment by ennioVisco** [comment]
> Hello
> 
> I got the exact same problem when I use java module (for example with javafx) in java 17 (with version 4.8.2). This problem is described for example at https://stackoverflow.com/questions/74892632/compilation-error-with-maven-on-intellij-module-not-found-processed-jcommander
> 
> So even the simplest program like:
> 
> ```
> package dev.selenium.hello;
> 
> import org.openqa.selenium.WebDriver;
> import org.openqa.selenium.chrome.ChromeDriver;
> 
> public class HelloSelenium {
>     public static void main(String[] args) {
>         WebDriver driver = new ChromeDriver();
> 
>         driver.get("https://selenium.dev");
> 
>         driver.quit();
>     }
> }
> ```
> 
> with a "module-info.java" containing `requires org.seleniumhq.selenium.chrome_driver;`
> 
> doesn't work and fail with error:
> 
> ```
> > Task :compileJava FAILED
> error: module not found: processed.jcommander
> error: module not found: processed.async.http.client
> 2 errors
> ```
> 
> The problem seem to come from the jar **selenium-remote-driver-4.8.1.jar** that contains the following lines in the **module-info.java** :
> 
> ```
>     requires processed.async.http.client;
>     requires processed.jcommander;
> ```
> 
> However, the dependency on **jcommander-1.82.jar** (not a module) should be referenced as:
> 
> ```
>     requires async.http.client;
>     requires jcommander;
> ```
> 
> to be compliant with "automatic module" rules (if I understand correctly because - strangely - it doesn't seem to be a problem for provided.toml for example)
> 
> Some suggestions (like "use java 1.8") are not really satisfactory. Would it be possible to correct this problem or provide a workaround compatible with module please ?

I have problems with jtoml as well, perhaps your build stops there and doesn't go on. I think it should be:
```java
requires async.http.client;
requires jcommander;
requires jtoml;
```

**Comment by titusfortner** [comment]
@ennioVisco Can you make a PR with your suggestion? Thanks!

**Comment by ennioVisco** [comment]
> @ennioVisco Can you make a PR with your suggestion? Thanks!

Unfortunately, after completing the read of the thread, and of the related one that mentions this (https://github.com/SeleniumHQ/selenium/issues/11858), I am afraid it's not that simple. 
It seems the `module-info.java` file is auto-generated (I don't get why, I guess there were specific reasons for that):
https://github.com/SeleniumHQ/selenium/blob/38188198d12618224e16a738ca3580dbd4212242/java/src/dev/selenium/tools/modules/ModuleGenerator.java#L209

I'm not that experienced with automatic module generation.

**Comment by titusfortner** [comment]
We auto-generate a lot of things with Bazel. Thanks, we'll look into it more.

**Comment by diemol** [comment]
#12173 should fix this, thanks @joerg1985!

**Comment by ennioVisco** [comment]
> #12173 should fix this, thanks @joerg1985!

Which means it's not live yet, right?
