### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by pedkoz** [SeleniumHQ/selenium#1155]
Hi,

It was working fine, but now i have trouble with firefox driver. I am not sure it can be by a update of firefox or not. It could be.

The error is when I do the 
				driver = new FirefoxDriver(cap);

Driver runs the browser, but it can not be recovered in the variable "driver" for running tests. It fails in that line.

The capabilities are:
		case FIREFOX:

			ProfilesIni allProfiles = new ProfilesIni();
			FirefoxProfile profile = allProfiles.getProfile("default");
			if (!os.equalsIgnoreCase("linux")) {
				profile.setAcceptUntrustedCertificates(true);
				profile.setAssumeUntrustedCertificateIssuer(false);
			}

			capabilities = DesiredCapabilities.firefox();
			// capabilities.setPlatform(org.openqa.selenium.Platform.WINDOWS);

Note: I repeat it always worked fine untill now.

I have selenium-java versiom: 2.46.0 i tested with 2.28.2 too. And probles persists.

The version of firefox is:
40.0.3 in a windows 7 with operative system 64 bits.

Best regards,

**Comment by ddavison** [comment]
could you give us a short test case example that we could reproduce this with?

**Comment by pedkoz** [comment]
Hi,

I have redesigned a test for you:

An example for test is:

package fon.ACCTeam;

import java.io.IOException;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.internal.ProfilesIni;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class Tests {

	protected WebDriver driver;

	@BeforeTest
	@Parameters({})
	public void driverSetup() throws IOException, InterruptedException {
		DesiredCapabilities capabilities;
		ProfilesIni allProfiles = new ProfilesIni();
		FirefoxProfile profile = allProfiles.getProfile("default");

		profile.setAcceptUntrustedCertificates(true);
		profile.setAssumeUntrustedCertificateIssuer(false);

		capabilities = DesiredCapabilities.firefox();

		// capabilities.setPlatform(org.openqa.selenium.Platform.WINDOWS);
		driver = new FirefoxDriver(capabilities);
	}

	@AfterTest
	public void tearDown() throws Exception {
		driver.quit();
	}

	@Test(groups = { "purchases" })
	@Parameters({})
	public void burnPurchasesTest() {
		driver.get("http://www.as.com");
	}
}


When i do: 		driver = new FirefoxDriver(capabilities);
Browser runs, but I receive in the log: and test finishes,
I receive the error.


org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
08198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090701	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1444834090707	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Pedro\\AppData\\Local\\Temp\\anonymous5367079453521728813webdriver-profile\\extensions\\fxdriver@googlecode.com","e":true,"v":"2.44.0","st":1444834065732,"mt":1444834065678}},"app-global":{"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi","e":true,"v":"7.5.0.9082","st":1444316546000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090709	addons.xpi	DEBUG	No changes found
1444834090713	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090713	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090717	addons.xpi	DEBUG	Calling bootstrap method startup on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 7.5.0.9082
1444834090752	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1444834090753	addons.manager	DEBUG	Provider finished startup: XPIProvider
1444834090753	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1444834090753	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1444834090753	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1444834090754	addons.manager	DEBUG	Starting provider: GMPProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1444834090758	addons.manager	DEBUG	Provider finished startup: GMPProvider
1444834090758	addons.manager	DEBUG	Starting provider: PluginProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1444834090759	addons.manager	DEBUG	Provider finished startup: PluginProvider
1444834090759	addons.manager	DEBUG	Completed startup sequence
1444834090810	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\Pedro\AppData\Local\Temp\anonymous5367079453521728813webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1444834090930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1444834090930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1444834090930	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1444834091052	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1444834091052	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1444834091053	addons.xpi-utils	DEBUG	Successfully read XPI database
1444834091116	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1444834091116	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1444834091117	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///C:/Users/Pedro/AppData/Local/Temp/anonymous5367079453521728813webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11487: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: resource://skype_ff_extension-at-jetpack/skype_ff_extension/data/c2c_options_menu_localization.js, line 189: TypeError: document.getElementById(...) is null

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at fon.ACCTeam.Tests.driverSetup(Tests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
FAILED CONFIGURATION: @BeforeTest driverSetup
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
08198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090701	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1444834090707	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Pedro\\AppData\\Local\\Temp\\anonymous5367079453521728813webdriver-profile\\extensions\\fxdriver@googlecode.com","e":true,"v":"2.44.0","st":1444834065732,"mt":1444834065678}},"app-global":{"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi","e":true,"v":"7.5.0.9082","st":1444316546000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090709	addons.xpi	DEBUG	No changes found
1444834090713	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090713	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090717	addons.xpi	DEBUG	Calling bootstrap method startup on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 7.5.0.9082
1444834090752	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1444834090753	addons.manager	DEBUG	Provider finished startup: XPIProvider
1444834090753	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1444834090753	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1444834090753	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1444834090754	addons.manager	DEBUG	Starting provider: GMPProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1444834090758	addons.manager	DEBUG	Provider finished startup: GMPProvider
1444834090758	addons.manager	DEBUG	Starting provider: PluginProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1444834090759	addons.manager	DEBUG	Provider finished startup: PluginProvider
1444834090759	addons.manager	DEBUG	Completed startup sequence
1444834090810	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\Pedro\AppData\Local\Temp\anonymous5367079453521728813webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1444834090930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1444834090930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1444834090930	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1444834091052	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1444834091052	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1444834091053	addons.xpi-utils	DEBUG	Successfully read XPI database
1444834091116	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1444834091116	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1444834091117	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///C:/Users/Pedro/AppData/Local/Temp/anonymous5367079453521728813webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11487: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: resource://skype_ff_extension-at-jetpack/skype_ff_extension/data/c2c_options_menu_localization.js, line 189: TypeError: document.getElementById(...) is null

Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'PCUELLO-QA', ip: '192.168.24.215', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at fon.ACCTeam.Tests.driverSetup(Tests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
08198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090701	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}
1444834090707	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1444834090707	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Pedro\\AppData\\Local\\Temp\\anonymous5367079453521728813webdriver-profile\\extensions\\fxdriver@googlecode.com","e":true,"v":"2.44.0","st":1444834065732,"mt":1444834065678}},"app-global":{"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi","e":true,"v":"7.5.0.9082","st":1444316546000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1441016621704,"mt":1441016621659}}}
1444834090709	addons.xpi	DEBUG	No changes found
1444834090713	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090713	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1444834090717	addons.xpi	DEBUG	Calling bootstrap method startup on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 7.5.0.9082
1444834090752	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1444834090753	addons.manager	DEBUG	Provider finished startup: XPIProvider
1444834090753	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1444834090753	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1444834090753	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1444834090754	addons.manager	DEBUG	Starting provider: GMPProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1444834090758	addons.manager	DEBUG	Provider finished startup: GMPProvider
1444834090758	addons.manager	DEBUG	Starting provider: PluginProvider
1444834090758	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1444834090759	addons.manager	DEBUG	Provider finished startup: PluginProvider
1444834090759	addons.manager	DEBUG	Completed startup sequence
1444834090810	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\Pedro\AppData\Local\Temp\anonymous5367079453521728813webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1444834090930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1444834090930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1444834090930	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1444834091052	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1444834091052	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1444834091053	addons.xpi-utils	DEBUG	Successfully read XPI database
1444834091116	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1444834091116	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1444834091117	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///C:/Users/Pedro/AppData/Local/Temp/anonymous5367079453521728813webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11487: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
JavaScript error: resource://skype_ff_extension-at-jetpack/skype_ff_extension/data/c2c_options_menu_localization.js, line 189: TypeError: document.getElementById(...) is null

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 28 more

Best regards,

**Comment by barancev** [comment]
Selenium 2.44 (that is used according to the log) is out of date.
Firefox 40 requires Selenium 2.47 or newer.
