### ISSUE TITLE
[🐛 Bug]: Max Concurrency value is always 1 in selenium grid 4

### ISSUE THREAD

**Issue by djavvadi** [SeleniumHQ/selenium#11559]
### What happened?

Hi Everyone, 

I am selenium grid since very long time for my daily test executions. I used windows server 2019 cloud machine to run selenium grid with xenon dual core CPU and 16B of RAM. After upgrading selenium server version to 4, I recently encountered that the max concurrency value is always 1 and I couldn't run multi sessions of the browsers at the same time.  

I updated several versions of the selenium but the value is not updated. 

Used below values in Hub and Node configurations too, but the result is same.
'max-sessions'

![image](https://user-images.githubusercontent.com/21127885/212882939-33d0a214-d1f3-40f4-8be9-e56bd998e9ed.png)

### How can we reproduce the issue?

```shell
Command used to run the grid 
java -jar selenium-server-4.7.2.jar --port 4545 --max-threads 3
```

### Relevant log output

```shell
Max. Concurrency: 1
```

### Operating System

WINDOWS SERVER 2019

### Selenium version

java 8

### What are the browser(s) and version(s) where you see this issue?

Chrome  108.0.5359.125 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 108.0.5359.71

### Are you using Selenium Grid?

4.1.1 to 4.7.2

**Comment by diemol** [comment]
With Grid 4 we recommend a single Internet Explorer session due to concurrency issues, if you still want to have more sessions, you need to override the default values. Check https://www.selenium.dev/documentation/grid/configuration/cli_options/#node, specifically `--max-sessions` and `--override-max-sessions`.

**Comment by djavvadi** [comment]
This override option worked, Thank you 

![image](https://user-images.githubusercontent.com/21127885/212911444-fbb3b45a-e056-4b12-bd7f-4d5f50c3180d.png)
