### ISSUE TITLE
Calling .click() on WebElement in Firefox causing page to not render properly

### ISSUE THREAD

**Issue by szaluk** [SeleniumHQ/selenium#1156]
If you run the code example below, Chrome and Safari will properly render the resulting page but in Firefox the page gets cut-off and not rendered properly - half the web elements are missing and the page doesn't fully load.  I have tested on the following and am able to reproduce it consistently:
- Mac OS X Yosemite and Windows 7
- Firefox 40 and 41
- Selenium version 2.47.1 and 2.48.2

Notes about the test:
- If run as is, the test will run on Chrome.  You will just need to comment out the ChromeDriver line and uncomment the FirefoxDriver line to switch browsers
- The browser is intentionally left open at the end so you can see the issue
- If you manually scroll the browser after the example code is executed, you will see the proper heading on the page and the page will be rendered properly in Chrome.  After running it in Firefox you will see the top part of the page is missing.
- I intentionally resize the page to 1024x768 to show the issue since this is the resolution our Grid machines use.  We do see different behavior with different resolutions.

``` java
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.safari.SafariDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class FirefoxIssue {

    public static void main(String args[]) {
        WebDriver webDriver = new ChromeDriver();
        //WebDriver webDriver = new FirefoxDriver();
        //WebDriver webDriver = new SafariDriver();

        WebDriverWait webDriverWait = new WebDriverWait(webDriver, 30l);

        webDriver.manage().window().setSize(new Dimension(1024, 768));

        webDriver.get("https://caspa.liaisoncas.com");

        webDriverWait.until(ExpectedConditions.elementToBeClickable(By.id("cas-login-field-username")));

        WebElement username = webDriver.findElement(By.id("cas-login-field-username"));
        WebElement password = webDriver.findElement(By.id("cas-login-field-password"));
        WebElement signin = webDriver.findElement(By.cssSelector(".cas-login-sign-in-button"));

        username.sendKeys("firefoxissue");
        password.sendKeys("p@ssw0rd");
        signin.click();

        webDriverWait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("div.cas-category-overview-container.cas-academicHistory")));

        WebElement academicHistory = webDriver.findElement(By.cssSelector("div.cas-category-overview-container.cas-academicHistory"));

        academicHistory.click();

        webDriverWait.until(ExpectedConditions.elementToBeClickable(By.linkText("Standardized Tests")));

        WebElement standardizedTests = webDriver.findElement(By.linkText("Standardized Tests"));

        standardizedTests.click();

        webDriverWait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".cas-standardizedtests li:nth-child(2) .cas-transcript-actions button")));

        WebElement addMCATScore = webDriver.findElement(By.cssSelector(".cas-standardizedtests li:nth-child(2) .cas-transcript-actions button"));

        addMCATScore.click();
    }
}
```

**Comment by szaluk** [comment]
You can also just clone the following repo:  https://github.com/szaluk/firefoxissue

That is a complete maven project so you will just have to import it into your IDE and run it.

Thanks,
Steve

**Comment by szaluk** [comment]
I did some more debugging and the issue goes away if I put a small Thread.sleep(5000) right before the line below line and manually scroll that element into the viewable area of the page:

addMCATScore.click();

The issue only  happens when a webelement is outside the viewable area of the page and only in Firefox.

**Comment by szaluk** [comment]
Update on this issue:

If I replace the click() calls on a WebElement with a corresponding Javascript click like below things work fine:

getJavascriptExecutor().executeScript("arguments[0].click();", getWebElement());

I am now facing an issue selecting an option from a select.  I am seeing the same behavior described above when the following method is called in the Select class:

```java
    private void setSelected(WebElement option) {
        if(!option.isSelected()) {
            option.click();
        }

    }
```

There is definitely something broken in the FirefoxDriver when clicking on items in our AngularJS based website.  We are not seeing this issue on our other sites not build on AngularJS

Could this be related to the removal of native events in the FirefoxDriver?

Thanks,
Steve

**Comment by szaluk** [comment]
I updated the GitHub repo with a class that shows the error (FirefoxIssue) and one that shows the workaround (FirefoxIssueFix).  The only difference between the two is the last line and how it clicks on that link.

**Comment by jtabone16** [comment]
Getting the same error with Firefox although everything is rendering properly

**Comment by szaluk** [comment]
Hi,

Has anybody had a chance to investigate this yet?  I have had to do a lot of manipulations through jquery and the JS Executor to click on items in Firefox where I would normally just call .click()

Thanks,
Steve

**Comment by AKSahu** [comment]
Hi Steve,

Good that you brought up this. Even I am facing the same and was wondering about the issue. I think we should update selenium developers about it for a work around for latest firefox browser.

Please keep here posted when you get any updates.

Thanks you so much!

Regards,
Aswini Kumar
http://aksahu.blogspot.in/

**Comment by szaluk** [comment]
Just tried with 2.49.0 but it's still happening.

**Comment by titusfortner** [comment]
This is definitely odd. If you click it directly, the main content doesn't load. If you reload it, everything shows up.

If you use position_once_scrolled_into_view on the element and then click, it loads as expected. This seems to indicate that Firefox Driver is not properly scrolling to the item before clicking it.

**Comment by szaluk** [comment]
@titusfortner - That is right.  I am only seeing this for elements that need to be scrolled.  It's happening in FF whenever a click is done (Select, etc.).

**Comment by szaluk** [comment]
Hey Guys,

Do you think this issue will ever get addressed with the current FF driver or are we waiting for Marionette to be released?  The reason I ask is I need to provide expectations to the management team on what browsers we cover and right now due to this issue, running on FF is inconsistent.  We put in a lot of JS hacks to get this to work but they don't run as well as other browsers.

Thanks!

--Steve

**Comment by titusfortner** [comment]
Is it still broken in the new 2.51 release?

**Comment by szaluk** [comment]
Yes. I tried it earlier.

**Comment by szaluk** [comment]
I will update the github project with the new version as soon as I get home.

**Comment by szaluk** [comment]
I updated the project to 2.51.0

**Comment by szaluk** [comment]
This is still happening using 2.53.0 and Firefox 45.0.1

**Comment by JasonLunn** [comment]
👍

**Comment by rcpeters** [comment]
👍 Driving this is driving me crazy.

**Comment by amitjhs** [comment]
I am facing same issue, with Web Driver 3.4.0 ( Dot Net Binding) and GeckoDriver v0.16.0.  But the  same is working fine with Chrome.

I do not want to put additional wait for FF, What is going wrong here ? Any one can please suggest.

**Comment by barancev** [comment]
The issue is still actual in legacy Firefox driver, but it's not going to be fixed there.

New Firefox driver implementation (aka geckodriver) does not suffer from this issue.
Tested on Selenium 3.5.2 + geckodriver 0.18 + Firefox Nightly 57 using the scenario in the original bug report.
