### ISSUE TITLE
[🐛 Bug]: chrome protocols not available in headless mode

### ISSUE THREAD

**Issue by darrenkel** [SeleniumHQ/selenium#11569]
### What happened?

Chrome protocols return empty pages when using selenium in **headless mode**.

I use the `chrome://extensions` to query the DOM and get the ID for my chrome extension. I always get an empty page when I visit `chrome://extensions` in headless mode

The same can also be said for the `chrome-extension://` protocol as I hardcoded my extension ID and got an empty page when I visited my extension at `chrome-extension://clbcmlfmoadnejkohgjannpaodeoalcj/index.html` (Works fine when not in headless)

### How can we reproduce the issue?

```shell
//Typescript snippet of a class that extends  WebDriver

const chromePages = ["history", "extensions", "settings"]

for (const page of chromePages) {
    await this.get(`chrome://${page}`)
    console.log(`${page} URL:  ${await this.getCurrentUrl()}`)
    console.log(`${page}:  ${await this.getPageSource()}`)
}
```

### Relevant log output

```shell
history URL:  chrome://history/
history:  <html><head></head><body></body></html>
extensions URL:  chrome://extensions/
extensions:  <html><head></head><body></body></html>
settings URL:  chrome://settings/
settings:  <html><head></head><body></body></html>
```

### Operating System

MacOS, Linux

### Selenium version

NPM: selenium-webdriver@4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chrome - 109.0.5414.87 (MacOS), 109.0.5414.74 (Ubuntu)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 109.0.5414.74 (MacOS), 109.0.5414.74 (Ubuntu)

**Comment by diemol** [comment]
Most likely an issue with Chrome itself. What happens when you start Chrome with `--headless=new`? What happens when you use Firefox?

**Comment by darrenkel** [comment]
@diemol it works with `--headless=new`  :raised_hands:

Haven't tried FF as I don't have it setup

**Comment by diemol** [comment]
Great. Closing this issue then.
