### ISSUE TITLE
Unable to see selenium/node-chrome-debug in browser which is up, linked with hub and running in docker - Selenium Grid 4.7.2

### ISSUE THREAD

**Issue by keerthiGit-SDET** [SeleniumHQ/selenium#11564]
### What happened?

In Selenium Grid 4.7.2 - trying to view the chrome node that have been linked to selenium hub.
Steps
1. make the docker available
2. spin up selenium hub using **docker run -d -p 4545:4444 --name selenium-hub selenium/hub**
3. check in browser for selenium hub : http://localhost:4545/ui# 
4. "The Grid has no registered Nodes yet" - this message is displayed
5. spin up and link the selenium hub with chrome node  using **docker run -d -P --link  selenium-hub:hub selenium/node-chrome-debug**
6. refresh the browser  :http://localhost:4545/ui#
7. expected - to see a grid with chrome browser
8. Actual - "The Grid has no registered Nodes yet" - this message is displayed still.
![docker logs](https://user-images.githubusercontent.com/66715365/212991526-740a3903-2906-47cf-9c71-839d14265e5f.png)
![grid UI](https://user-images.githubusercontent.com/66715365/212991539-6ed94f81-4bda-45ec-9ef7-29dcf573257d.png)
![hub and node up and running in terminal](https://user-images.githubusercontent.com/66715365/212991561-2ca16bd8-f4f2-4464-881f-f49ede5515d2.png)

### How can we reproduce the issue?

```shell
C:\Users\lenovo>docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS          PORTS                                   NAMES
d7cb4869dc33   selenium/hub   "/opt/bin/entry_poin…"   14 minutes ago   Up 13 minutes   4442-4443/tcp, 0.0.0.0:4545->4444/tcp   selenium-hub

C:\Users\lenovo>docker run -d -P --link  selenium-hub:hub selenium/node-chrome-debug
d695d1f491677c456af83070580fa71d1392a946c627f7ddab78a78e84167316

C:\Users\lenovo>docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS          PORTS                                   NAMES
d695d1f49167   selenium/node-chrome-debug   "/opt/bin/entry_poin…"   6 seconds ago    Up 4 seconds    0.0.0.0:32769->5900/tcp                 eager_swanson
d7cb4869dc33   selenium/hub                 "/opt/bin/entry_poin…"   20 minutes ago   Up 20 minutes   4442-4443/tcp, 0.0.0.0:4545->4444/tcp   selenium-hub
```

### Relevant log output

```shell
C:\Users\lenovo>docker logs
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container

C:\Users\lenovo>docker logs d7cb4869dc33
2023-01-17 16:53:10,956 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
2023-01-17 16:53:10,969 INFO RPC interface 'supervisor' initialized
2023-01-17 16:53:10,970 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-01-17 16:53:10,971 INFO supervisord started with pid 8
2023-01-17 16:53:11,974 INFO spawned: 'selenium-grid-hub' with pid 10
Tracing is disabled
2023-01-17 16:53:11,978 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
16:53:12.722 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:53:12.732 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:53:12.884 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.17.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.17.0.2:4443]
16:53:12.957 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.17.0.2:4442 and tcp://172.17.0.2:4443
16:53:12.984 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:53:13.986 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:53:15.093 INFO [Hub.execute] - Started Selenium Hub 4.7.2 (revision 4d4020c3b7): http://172.17.0.2:4444
```

### Operating System

windows 11

### Selenium version

 <dependency>             <groupId>org.seleniumhq.selenium</groupId>             <artifactId>selenium-java</artifactId>             <version>4.4.0</version>         </dependency>

### What are the browser(s) and version(s) where you see this issue?

chrome and firefox node aswell

### What are the browser driver(s) and version(s) where you see this issue?

chrome and firefox node aswell

### Are you using Selenium Grid?

Selenium Grid 4.7.2 (revision 4d4020c3b7)

**Comment by diemol** [comment]
Please follow the instructions to start Grid 4 in Docker, https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes

**Comment by SouvikShome11** [comment]
This issue is not resolved.
When I am using **selenium/node-chrome** image it is working fine and we are able to see the node in grid .
But when I am using selenium/node-chrome-debug , the node is not seen in the grid. though the container is running successfully

**Comment by diemol** [comment]
They are the same image now, already since two years ago.
