### ISSUE TITLE
[🚀 Feature]: Palemoon browser

### ISSUE THREAD

**Issue by workatecesisnathaniel** [SeleniumHQ/selenium#11567]
### Feature and motivation

Hi is there any version of selenium that could automate the pale moon browser?It has the same functionality as Firefox 

### Usage example

Could automate any task on palemoon

**Comment by titusfortner** [comment]
Try using geckodriver and set the location of the browser in the options class using binary property/method

**Comment by workatecesisnathaniel** [comment]
It is invoking the browser but not navigating the pages.is there any particular version of selenium that i should use ?

**Comment by titusfortner** [comment]
I see that the browser is based off an old version of Firefox, so you might need an older version of geckodriver. I'd reach out to the devs of pale moon and see if they know what would work. If they need to fork the geckodriver, we can see about adding specific support in our code. Let us know what you find.

**Comment by workatecesisnathaniel** [comment]
The Devs of pale moon are of no help :(

**Comment by titusfortner** [comment]
Sorry to hear that. Nothing we can do without a driver. Let us know if that changes. Thanks
