### ISSUE TITLE
Click on link element identified by title is not actioned

### ISSUE THREAD

**Issue by gavk34** [SeleniumHQ/selenium#1157]
Selenium Version: 2.48.0/2.48.1
Watir-Webdriver: 0.8.0
Not reproducible with 2.47.1

Attempting to click on an element identified by title results in no click action
Example HTML
```
<div class="home-icon">
<a href="xxxxx" title="Some Title"><img src="xxxxx" title="Image Title" alt="alt title"></a>
<h2><a href="xxxxx">Click Here</a></h2>
<p>Some Sample HTML.</p>
</div>
```			
Code
browser.link(:title, 'Some Title').when_present.click

**Comment by lukeis** [comment]
this is not enough to reproduce the issue, please either provide a full page (that includes the css or javascript that may be causing the issue) or a link to a page that reproduces the issue. Also which browser are you using

**Comment by gavk34** [comment]
Sorry I can't provide the javascript/css as the webpage is for an internal application. The browser is FF 41.0.1. 
What is strange though is that I can not reproduce using irb, however running within the Docker container(which is how our automation is run) the error is reproducible every time. 
2.47.1 works ok within the Docker container so I understand if you want to close this as I can't provide more information on the webpage.
I will attempt to reproduce on a public page and if I can I will reopen the issue? Thanks

**Comment by titusfortner** [comment]
@gavk34 - Selecting an element by title is more of a Watir feature than a Selenium one. Update to the latest Watir version (0.9.1 as of last night), and if you still have this problem create a new issue in [The Watir Issue Tracker](https://github.com/watir/watir-webdriver/issues), and we'll try to figure out what's going on there. Thanks.
