### ISSUE TITLE
Exception "Unknown HttpClient factory jdk-http-client" with "jdk http client" in fat jar

### ISSUE THREAD

**Issue by Tyutyunov** [SeleniumHQ/selenium#11574]
### What happened?

I have a java project with dependencies

```
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.7.2</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-http-jdk-client</artifactId>
            <version>4.7.2</version>
        </dependency>
```

I create fat jar using maven-assembly-plugin running command "clean compile assembly:single"

```
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>test.Run</mainClass>
                        </manifest>
                        <manifestEntries>
                            <Class-Path>.</Class-Path>
                        </manifestEntries>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <finalName>TestSelenium</finalName>
                </configuration>
            </plugin>
```

My test code

```
    public static void main(String[] args) throws Exception {
        System.setProperty("webdriver.http.factory", "jdk-http-client");

        System.out.println("START");

        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setBrowserName("chrome");

        String url = "http://grid.url/wd/hub";

        WebDriver driver = new RemoteWebDriver(
                new URL(url), caps
        );
        driver.get("https://www.selenium.dev/");
        Thread.sleep(2000);
        driver.quit();

        System.out.println("END");

    }
```

After run jar

```
java -jar TestSelenium-jar-with-dependencies.jar
START
Exception in thread "main" java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:57)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:73)
	at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:183)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at test.Run.main(Run.java:20)
```

### How can we reproduce the issue?

```shell
Run fat jar
```

### Relevant log output

```shell
java -jar TestSelenium-jar-with-dependencies.jar
START
Exception in thread "main" java.lang.IllegalArgumentException: Unknown HttpClient factory jdk-http-client
	at org.openqa.selenium.remote.http.HttpClient$Factory.create(HttpClient.java:57)
	at org.openqa.selenium.remote.http.HttpClient$Factory.createDefault(HttpClient.java:73)
	at org.openqa.selenium.remote.RemoteWebDriver.createExecutor(RemoteWebDriver.java:183)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at test.Run.main(Run.java:20)
```

### Operating System

Linux, Mac OS

### Selenium version

4.7.2

### What are the browser(s) and version(s) where you see this issue?

Any

### What are the browser driver(s) and version(s) where you see this issue?

Any

### Are you using Selenium Grid?

4.7.2

### Java version?

14.0.2

**Comment by pujagani** [comment]
Thank you for providing the details. I was able to reproduce the issue. This is happening because the `META-INF/services` file is getting overwritten when creating the JAR. I know one popular alternative is to use maven-shade-plugin. I do understand that might not be possible. Please refer to https://stackoverflow.com/questions/47310215/merging-meta-inf-services-files-with-maven-assembly-plugin as one possible solution. Thank you!

**Comment by arjunkhadka-sw** [comment]
Hi @pujagani,
I am facing the same issue. I am using selenium-java: 4.8.1 and selenium-http-jdk-client : 4.8.1. I added selenium-http-jdk-client dependency as a part of the solution to problem mention here : https://support.google.com/chrome/thread/205167021/selenium-is-not-working-with-chrome-after-updating-chrome-to-latest-version-111-0-5563-65?hl=en. But now while running the jar I am facing same issue : "Unknown HttpClient factory jdk-http-client". I am using maven-shade-plugin 3.4.1 to package the jar.

**Comment by arjunkhadka-sw** [comment]
@pujagani, Concatenating Service Entries with the ServicesResourceTransformer solved the problem. Thanks.

**Comment by jgfmachado** [comment]
@arjunkhadka-sw what do you mean by _"Concatenating Service Entries with the ServicesResourceTransformer"_?

**Comment by krmahadevan** [comment]
> @arjunkhadka-sw what do you mean by _"Concatenating Service Entries with the ServicesResourceTransformer"_?

See here: https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

**Comment by Apyz** [comment]
This was the problem on January 20th, but it still hasn't been solved by May 19th. I also have this problem. I hope it can be solved soon

**Comment by titusfortner** [comment]
@Apyz there isn't anything for selenium to fix. Take a look at the links for how to address your problem.

**Comment by Apyz** [comment]
> @Apyz there isn't anything for selenium to fix. Take a look at the links for how to address your problem.

Yes, I've solved it, and although link doesn't offer a direct solution, But I know that is because jdk-http-client in meta-inf/service in the "org.openqa.selenium.remote.http.HttpClient$Factory" are covered off, Using maven-shade-plugin  in  org.apache.maven plugins.shade.resource.servicesResourceTransformer  allows them to merge, and the solution to this problem

**Comment by brlawrence** [comment]
could someone give a summarized steps to resolve this issue. I have the same error still and not sure how to use the maven-shade-plugin

**Comment by naelmarwan1** [comment]
According to https://www.selenium.dev/blog/2022/using-java11-httpclient/, you are required to add this:
`<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-http-jdk-client</artifactId>
  <version>4.5.0</version>
</dependency>`

**AND**

` System.setProperty("webdriver.http.factory", "jdk-http-client");
`

**Comment by titusfortner** [comment]
This is no longer an issue in 4.14 as the jdk client is the default.
