### ISSUE TITLE
[🐛 Bug]: Ruby exception with firefox profiles on Linux due to File.stat on broken link

### ISSUE THREAD

**Issue by mwgkgk** [SeleniumHQ/selenium#11576]
### What happened?

Just the default example code using options.profile

```ruby
require 'selenium-webdriver'

options = Selenium::WebDriver::Firefox::Options.new
options.profile = "default"

driver = Selenium::WebDriver.for :firefox, options: options
```

triggers

```
No such file or directory @ rb_file_s_stat - /tmp/webdriver-rb-profilecopy20230121-192209-yy5fi1/lock (Errno::ENOENT)
```

Due to following code in [lib/selenium/webdriver/common/zipper.rb](https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/common/zipper.rb)

```ruby
      def add_zip_entry(zip, file, entry_name)
        entry = Zip::Entry.new(zip.name, entry_name)
        entry.follow_symlinks = true

        zip.add entry, file
      end
```

Which enables follow_symlinks, as per commit https://github.com/SeleniumHQ/selenium/commit/a44367ad80

This causes Rubyzip to use File.stat instead of File.lstat, which explodes with the above exception when called on firefox profile lock file, which is a weird broken link leading [nowhere](https://superuser.com/questions/1363677/in-a-symlink-pointing-to-127-0-1-1xxxxx-what-is-the-plus-character-for):
```
$ ls -la .mozilla/firefox/1c43irlt.default/lock
lrwxrwxrwx 1 this this 20 Jan 17 17:39 .mozilla/firefox/1c43irlt.default/lock -> 192.168.0.103:+27270
```

Tested with ruby 3.0.5 and 2.7.7 on Linux 6.1.6 and firefox 109.0

Solution could be to remove the above `entry.follow_symlinks = true` line, which works but conflicts with the apparent issue the 2011 commit https://github.com/SeleniumHQ/selenium/commit/a44367ad80 was addressing (which I was unable to track down by it's number).

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'

options = Selenium::WebDriver::Firefox::Options.new
options.profile = "default"

driver = Selenium::WebDriver.for :firefox, options: options
```

### Relevant log output

```shell
irb(main):007:0> driver = Selenium::WebDriver.for :firefox, options: options
/home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:409:in `stat': No such file or directory @ rb_file_s_stat - /tmp/webdriver-rb-profil
ecopy20230121-192209-1x6dcl/lock (Errno::ENOENT)
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:409:in `file_stat'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:551:in `gather_fileinfo_from_srcpath'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:303:in `add'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:89:in `add_zip_entry'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:55:in `block (2 levels) in zip'
        from /usr/lib/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/lib/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/lib/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/lib/ruby/3.0.0/find.rb:43:in `each'
        from /usr/lib/ruby/3.0.0/find.rb:43:in `find'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:54:in `block in zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:78:in `block in with_tmp_zip'
        from /usr/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:76:in `with_tmp_zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb:53:in `zip'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/profile_helper.rb:39:in `encoded'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:144:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:160:in `block in process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each_with_object'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:142:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:160:in `block in process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `each_with_object'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:155:in `process_json_hash'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:142:in `generate_as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/options.rb:116:in `as_json'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:322:in `block in create_bridge'
        from <internal:kernel>:90:in `tap'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:321:in `create_bridge'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:53:in `new'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/driver.rb:53:in `for'
        from /home/this/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver.rb:88:in `for'
        from (irb):7:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/irb-1.4.2/exe/irb:11:in `<top (required)>'
        from /usr/bin/irb:25:in `load'
        from /usr/bin/irb:25:in `<main>'
```

### Operating System

Linux

### Selenium version

Ruby 3.0.5, Ruby 2.7.7

### What are the browser(s) and version(s) where you see this issue?

firefox 109

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.30.0

**Comment by titusfortner** [comment]
We're looking to deprecate a bunch of profile functionality in the next version of Selenium (https://github.com/SeleniumHQ/selenium/issues/11587).

`profile` should only be used if you have an existing profile that you want the driver to use. If you are creating a default profile and adding things to it, you should be using the `prefs` attribute instead.

I'll keep this open to investigate, but let me know if prefs doesn't address your use case.

**Comment by mwgkgk** [comment]
Indeed with Ruby version at least, you can't even assign options.profile if it doesn't find the matching folder in `.mozilla/firefox/`. Hence I used "default" profile in the examples. I want to use a specialized profile for testing is the intention behind this.

The culprit is that it's doing the tmp copy of the profile, and Ruby's File.stat fails on broken links. But Firefox intentionally uses broken link as a lock file, on Linux. So it fails every time. The default for Rubyzip is to use `File.lstat` which doesn't follow links, but in 2011 we've changed the default by adding "entry.follow_symlinks = true" https://github.com/SeleniumHQ/selenium/commit/a44367ad80

To put it in simpler words, looks like nobody used it in a long time, and making Ruby version work with profiles is solved by removing that one line.

**Comment by mwgkgk** [comment]
Workaround: using `options.binary` with a wrapper around Firefox that assigns -P, like this:

```bash
# File on $PATH named firefox-myprofile
exec firefox -P myprofile "$@"
```

Using `options.binary = "firefox-myprofile"` instead of  `options.profile = "myprofile"`:

```ruby
options = Selenium::WebDriver::Firefox::Options.new
# options.profile = "myprofile"
options.binary = "firefox-myprofile"

driver = Selenium::WebDriver.for :firefox, options: options
driver.get "https://github.com"
```

**Comment by titusfortner** [comment]
Ah, yes, I see what you are saying. Can you make a PR for it?

**Comment by mwgkgk** [comment]
I need guidance on how to make this gem installable, i tested my modification in gem folder, but couldn't get gem to install from cloned repo. What are the appropriate commands to run?

**Comment by titusfortner** [comment]
This *should be very straightforward at this point, depending on what OS you're on, but to build the gem, you need to:

* Install bazelisk: https://github.com/SeleniumHQ/selenium/#requirements
* Execute the bazel command: https://github.com/SeleniumHQ/selenium/#ruby

**Comment by mwgkgk** [comment]
I can build and run tests, but it is unclear how to load this in my `irb`.

 - gem install doesn't find gem files
 - rake install doesnt find rake tasks
 - there's a bazel job to push to build and push to rubygems
 - loading top-level file with a `load 'rb/lib/selenium-webdriver.rb` loads fine but doesn't reflect changes i make inside the tree (?). I checked a bunch of times for sanity. Yep, this is definitely the same file I'm changing in `~/.local/share/gem/ruby/3.0.0/gems/selenium-webdriver-4.7.1/lib/selenium/webdriver/common/zipper.rb` and `~/heap/selenium/rb/lib/selenium/webdriver/common/zipper.rb`, but the `require 'selenium-webdriver'` does reflect the changes I make to the respective file, and `load "rb/lib/selenium-webdriver.rb"` doesn't.
  - 3 of the tests fail on freshly cloned repo, 1 additional fails if I make my change (`# entry.follow_symlinks = true`), which tests exactly the functionality i'm trying to disable to make profiles work
  
  I may come back to this later with another try

**Comment by MatzFan** [comment]
@mwgkgk I am having exactly the same problem with Selenium Firefox profiles but can't get your workaround to work. I used your solution to set up an executable wrapper around the `firefox` binary using "default" as the profile name and tested it to make sure it works. It does. But when I run my Ruby code, exactly as you typed it I get the following error when Ruby tries to instantiate the driver: `binary is not a Firefox executable (Selenium::WebDriver::Error::InvalidArgumentError)`. Do you have your workaround code in a repo I can look at?

Also, I'm interested in trying to fix this bug in the Ruby bindings for Selenium WebDriver, so if you can share anything you've done so far I'd be very grateful. TIA.

**Comment by mwgkgk** [comment]
@MatzFan hey! My original example was missing a shebang line. It works if you add something like `#!/usr/bin/env bash` as the first line, like this:
```
#!/usr/bin/env bash

exec firefox -P profilename "$@"
```

**Comment by MatzFan** [comment]
@mwgkgk awesome thanks. I had figured that out and got it to work as it happens but thanks for your response.

**Comment by MatzFan** [comment]
Revisiting this issue I have a question; why does `Selenium::WebDriver::Zipper` need to follow symlinks? There is a test for that functionality [here](https://github.com/SeleniumHQ/selenium/blob/478b430596d54bd432edcd09a0b187f2a6175e1b/rb/spec/integration/selenium/webdriver/zipper_spec.rb#L60) but AFAICT removing the one line `entry.follow_symlinks = true` [here](https://github.com/SeleniumHQ/selenium/blob/33a14a918736285200a7db36a7273d818a02c3bf/rb/lib/selenium/webdriver/common/zipper.rb#L84) doesn't break any driver tests. But, removing that one line *does* fix Firefox profile functionality. So with a simple patch I can do this:
```ruby
require 'selenium-webdriver'

module Selenium
  module WebDriver
    module Zipper
      class << self
        private

        def add_zip_entry(zip, file, entry_name)
          entry = Zip::Entry.new(zip.name, entry_name)
          # entry.follow_symlinks = true

          zip.add entry, file
        end
      end
    end
  end
end

options = Selenium::WebDriver::Firefox::Options.new
options.profile = "default"

driver = Selenium::WebDriver.for :firefox, options: options # no error about missing 'lock' file
```

The OP correctly notes that commit [a44367ad80](https://github.com/SeleniumHQ/selenium/commit/a44367ad80) back in 2011 added the follow symlink functionality, but the issue number it refers to is unrelated.

If there is no reason to have symlinks followed by the Zipper I'll happily remove that line, add some tests for using an existing Firefox profile and do a PR.

Alternatively, as it is only the `lock` file (a broken symlink) in a FF profile that breaks the zipping process, might an alternative be to simply rescue the `Errno::ENOENT` error for the lock file - something like:
```ruby
def add_zip_entry(zip, file, entry_name)
  entry = Zip::Entry.new(zip.name, entry_name)
  entry.follow_symlinks = true

  zip.add entry, file
rescue Errno::ENOENT => e
  raise e unless entry_name == 'lock' # known issue with broken symlink in FF profile 'lock' file

end
```
I'm guessing not having the 'lock' file in a zip archive won't cause any problems given it's been impossible to zip it anyway.

**Comment by titusfortner** [comment]
Right, that was when Selenium was using google code so the issue number won't track.

Is there an issue or something recorded about the symlink being broken? Is this a Firefox bug they should fix? I think rescuing  maintains whatever backwards compatibility exists, but would be nice to link to have more context in the comment.

**Comment by MatzFan** [comment]
Not a bug, a feature - AFAIK the symlink deliberately leads nowhere. @mwgkgk says above "But Firefox intentionally uses broken link as a lock file, on Linux". The last comment on [this post](https://www.linuxquestions.org/questions/linux-software-2/firefox-parentlock-and-lock-785876/) I found (caveat emptor) provides an explanation of the 'lock' file's purpose on Linux. The 'lock' link in my profile is to 0.0.0.2:+2341 and sure enough the PID of FF is 2341. If you delete it  - while FF is not running ;-) it is recreated by the first process that starts FF up so my guess it it is no loss to have it missing from a zip of a profile. I agree the safest thing to do is to catch the error on zipping rather than mess with the following of symlinks. Are you happy I provide a PR based on all this?

**Comment by MatzFan** [comment]
Found old issue 2416: https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/2416

**Comment by titusfortner** [comment]
Yes, PR would be good
