### ISSUE TITLE
[🚀 Feature]: [js] Add functionality for using "touch" pointer in Actions .

### ISSUE THREAD

**Issue by garg3133** [SeleniumHQ/selenium#11570]
### Feature and motivation

Right now, there is no easy way to use Actions with 'touch' pointer type in JavaScript. Even for a single finger interaction, we need to write complex code like below:

```js
// action to scroll downwards
const Pointer = require('selenium-webdriver/lib/input').Pointer;

const actions = this.driver.actions();

const pointer1 = new Pointer('finger-1', 'touch');
// we cannot use chaining below as chaining works for the mouse pointer type only
actions.insert(
  pointer1,
  pointer1.move({ x: 100, y: 500}),
  pointer1.press(),
  pointer1.move({duration: 1000, origin: 'pointer', y: -500}),
  pointer1.release()
);

actions.perform();
```

while the same code can be written for the mouse pointer type as:

```js
const actions = this.driver.actions();

actions
  .move({x: 100, y: 500})
  .press()
  .move({duration: 1000, origin: 'pointer', y: -500})
  .release()
  .perform();
```

This issue is different from #10808 because that issue mainly focuses on multi-touch commands considering single-touch commands work at least, but in JavaScript, even the support for single-touch commands is lacking.

So, I propose the following:

**Proposal 1: Make it easier and more intuitive to use single-touch commands**

* Just like the mouse pointer, there should be a default pointer for 'touch' which can easily be requested using `actions.touch()` command.
  ```js
  const mousePointer = actions.mouse();  // returns default mouse pointer
  const touchPointer = actions.touch();  // should return the default touch pointer
  ```
* Chaining should work for touch pointer as well.
  ```js
  // for mouse, everything would work like before
  actions
    .move({origin: element})
    .press()
    .release()
    .perform();

  // to use the pointer commands touch pointer, we can add a `device` parameter to all the pointer commands,
  // which would default to the mouse pointer for backward compatibility.
  // so, the single-touch actions would work as below
  const touchPointer = actions.touch();

  actions
    .move({origin: element}, touchPointer)
    .press(Button.LEFT, touchPointer)
    .release(Button.LEFT, touchPointer)
    .perform();
  ```

**Proposal 2: Allow setting default pointer (Proposal 1 in #10724)**

As apparent from the single-touch chaining example above, it still won't be very intuitive to use. So, we can add a new `setActivePointer` method, which can be used to switch between mouse and touch pointer while writing actions.

```js
actions
  // perform mouse actions
  .move({origin: element})
  .press()
  .release()
  // perform touch actions
  .setActivePointer(actions.touch())
  .move({origin: element})
  .press()
  .release()
  .perform();
```

**Proposal 3: Support for using multiple fingers at once**

While it does not make any sense to use multiple mouse pointers or multiple keyboard devices at once when writing an action, it is a very common use case to be able to use multiple fingers at once when testing on mobile devices. And so, using multiple touch pointers at once should be as easy as using a single touch pointer.

So, instead of defining a single touch pointer in the [constructor of Actions class](https://github.com/SeleniumHQ/selenium/blob/937cbaa05470fad29e7f2f8e60653039d1a1b8a5/javascript/node/selenium-webdriver/lib/input.js#L596) as below:
```js
this.touch_ = new Pointer('default touch', Pointer.Type.TOUCH)
```
we can define a list instead like below:
```js
this.touch_ = new Map([
  ['default touch', new Pointer('default touch', Pointer.Type.TOUCH)]
])
```

Doing so would make requesting and using multiple touch pointers as easy as using a single touch pointer:

```js
const actions = this.driver.actions({async: true});

const touchPointer = actions.touch();  // returns the default touch pointer with id 'default touch'
const finger1 = actions.touch('finger-1'); // looks through the list of available touch pointers and if a touch pointer is not available, create a new touch pointer with id 'finger-1' and append it to the list
const finger2 = actions.touch('finger-2');  // create a new touch pointer with id 'finger-2' and append it to the list, since it is not already available

// action to pinch zoom-in
actions
  .setActivePointer(finger1)
  .move({duration: 0, x: 100, y: 70})
  .press()
  .move({duration: 1000, origin: 'pointer', x: 0, y: -70})
  .release();

actions
  .setActivePointer(finger2)
  .move({duration: 0, x: 100, y: 100})
  .press()
  .move({duration: 1000, origin: 'pointer', x: 0, y: 70})
  .release();

actions.perform();
```

### Usage example

Provided above.

**Comment by pujagani** [comment]
@titusfortner Can you please help take a look? Your efforts and insights on Actions API will help :)

**Comment by titusfortner** [comment]
First, I haven't looked at JS at all, and we don't have an example here: https://www.selenium.dev/documentation/webdriver/actions_api/pen/

Most of the bindings have an "easy way" and a "hard way" to do actions things.
We want to provide access to common things with the "easy way"

I prefer doing `.move({origin: element}, touchPointer)` over `.setActivePointer(actions.touch())`.
The reason I used "setActive" in Java is to avoid added constructors. When you have default constructors (every other language) it probably makes sense to put it in the constructor.

Proposal 3 is a duplicate of https://github.com/SeleniumHQ/selenium/issues/10808
The way the action spec works is that you have an array for every device. Each item in the array represents a "tick" and a tick either has an action for the device or a `pause` that indicates no action is taken for that device during that tick. The bindings implement actions right now by putting the designated action in the n spot of the array for the designated device, then auto-adding a pause to that n position in the rest of the device arrays.
We need to figure out how to support putting actions for multiple devices (fingers) in the same "n" position of 2 different device arrays instead of auto-pausing. 

I expect this to be challenging (moreso in some languages than others), and to be honest I haven't looked into what this would take in any of the bindings.

Appium has a more native approach to doing gestures, and Nightwatch might be better off working with Appium API for those, anyway?

**Comment by garg3133** [comment]
Thanks, Titus for the comment.

> I prefer doing `.move({origin: element}, touchPointer)` over `.setActivePointer(actions.touch())`.

Yeah, in case of `.move()` command, it makes sense to pass in the `touchPointer` as the second argument. But my concern is with commands like `press()` and `release()`. For a mouse pointer, it's as easy as just writing `actions.press().release()`, but when using the same commands with a touch pointer, we'd need to pass in the first argument as well (`Button.LEFT`) and for that, we'd need to import the `Button` class as well, which just makes the code a lot more verbose for using the same command with other pointer types. That's why I was suggesting to use `.setActivePointer` in JS binding as well.

Or, another solution to this can be to allow using the pointer commands in two ways:
```js
actions.press(button, device);
actions.press(device);  // button defaults to Button.LEFT
```
The same approach has been used for the [`pause` command](https://github.com/SeleniumHQ/selenium/blob/937cbaa05470fad29e7f2f8e60653039d1a1b8a5/javascript/node/selenium-webdriver/lib/input.js#L745), which can be used in two ways:
```js
actions.pause(duration, ...devices);
actions.pause(...devices);  // duration defaults to 0
```


> We need to figure out how to support putting actions for multiple devices (fingers) in the same "n" position of 2 different device arrays instead of auto-pausing.

I'm not sure about other languages but in JS we can write actions in two modes: sync and async. And I agree that figuring this out for the `sync` mode can be challenging, but it's quite simple to use multiple fingers at once in the `async` mode, as we can just first add all the actions to be performed by the first finger and then add all the actions to be performed by the second finger:
```js
const {Button} = require('selenium-webdriver/lib/input');

const actions = this.driver.actions({async: true});
const finger1 = actions.touch('finger-1');
const finger2 = actions.touch('finger-2');

// action to pinch zoom-in
// add action to be performed by the first finger
actions
  .move({ x: 100, y: 70}, finger1)
  .press(Button.LEFT, finger1)
  .pause(finger1)
  .release(Button.LEFT, finger1);

// add actions to be performed by the second finger
actions
  .move({duration: 0, x: 100, y: 100}, finger2)
  .press(Button.LEFT, finger2)
  .move({duration: 1000, origin: 'pointer', x: 0, y: 70}, finger2)
  .release(Button.LEFT, finger2);

// execute the actions
actions.perform();
```

And using `async` mode for pointer-related actions also seems to be the recommended way as all the examples on the [Mouse actions](https://www.selenium.dev/documentation/webdriver/actions_api/mouse/) page have used `{async: true}` for JS.

> Appium has a more native approach to doing gestures, and Nightwatch might be better off working with Appium API for those, anyway?

Actually, no. They only have a [workaround](https://github.com/appium/appium-uiautomator2-driver/blob/0e5ab8f26416efb088e0639f5e6895b8e5ae8e68/lib/commands/touch.js#L22) over Selenium Actions where if we write the actions the Selenium way (`actions.move({origin: element}).press().release().perform()` for example) and send it over to Appium, they check the action type for each action command and if the action type is `pointer`, they change the `pointerType` to `touch`. But the problem with this is that while this works well for native context, this part of code is not executed for web-view contexts and hence, actions do not work the same in web-view or mobile browsers.

Other than actions, Appium also supports the `/touch` endpoints from JSON Wire Protocol to perform gestures, but those are very limited (we cannot perform pinch zoom-in using those). There are also some [`mobile: gesture` commands](https://appium.io/docs/en/writing-running-appium/android/android-mobile-gestures/) but those are also limited and non-standard (platform-specific). In contrast, W3C Actions are really powerful and we can perform just about any gesture using them. Even Appium folks also recommend using W3C Actions to perform gestures.

**Comment by titusfortner** [comment]
So, you don't need "set active" you can just pass the device into the actions constructor at the beginning. See what Ruby does here — https://www.selenium.dev/documentation/webdriver/actions_api/pen/?language=ruby#using-a-pen

Also "Button.LEFT" should be the default.

So, instead of this:
```
actions
  .move({ x: 100, y: 70}, finger1)
  .press(Button.LEFT, finger1)
  .pause(finger1)
  .release(Button.LEFT, finger1);
```

We would have:
```
actions(finger1)
  .move({ x: 100, y: 70})
  .press()
  .pause()
  .release();
```

So, once we provide the ability to designate pointers, you should be able to use async to do the things you need?

What the issue I referenced is for is to be able to provide users, though is along the lines of:
```
actions.pinch().perform();
actions.zoom().perform();
actions.swipe("up").perform();
actions.swipe("down").perform();
```
But we need to think through the parameters for each of the methods to cover the important use cases.

**Comment by titusfortner** [comment]
@harsha509 @TamsilAmani @pujagani if we're working on actions things, maybe worth discussing more in Slack or at TLC?

**Comment by garg3133** [comment]
> So, you don't need "set active" you can just pass the device into the actions constructor at the beginning.

But then, if we pass the pointer device (or pointer type) in the constructor itself, won't we be restricting an `Actions` class instance from being used with more than one pointer device at the same time? For example, if we have the API usage like below:
```js
const actions = this.driver.actions({async: true, pointerType: 'touch'});  // returns Actions class instance

actions
  .move({ x: 100, y: 70})
  .press()
  .pause()
  .release();
```
there is no way we can use the same `actions` instance with mouse or other touch pointer devices. And if we create separate `Actions` class instance to use with other pointer devices, they cannot be performed simultaneously.

> So, once we provide the ability to designate pointers, you should be able to use async to do the things you need?

So, the primary things that we need is:
* Ability to perform pointer-related actions using 'touch' pointer type. (Proposal 1)
* Ability to perform actions using multiple fingers at the same time. (Proposal 3)

So, I suggest that we can work on these first (with touchPointer device passed as the second argument to pointer commands) and then we can discuss and work on how to make it easier for users to use pointer commands with 'touch' device instead of having to pass two arguments (`button` and `device`) on every command.

And based on what you said above, Proposal 3 does not seem to be a duplicate of #10808, since that issue focusses on creating new methods for some common use cases involving multiple fingers, but what I'm suggesting is to give users the ability to use multiple fingers as they would like to. And implementing this capability does not seem to be very difficult, at least in JS binding. Creating new methods for some common use cases can follow. And regarding the parameters, we could probably take inspiration from Appium's [`mobile: gesture` commands](https://appium.io/docs/en/writing-running-appium/android/android-mobile-gestures/#mobile-pinchopengesture).

Also, I'm willing to work on this myself and raise a PR.

**Comment by titusfortner** [comment]
Sorry, didn't mean either/or; you should be able to do both (and this isn't correct JS syntax, but should get across the idea)
Implementing device parameters for each of these methods should be straightforward, and do everything you are asking for.

### Switch to non-mouse pointer
```
driver.actions(pen)
  .move({ x: 100, y: 70})
  .press()
  .pause()
  .release()
  .perform();
```

### Switch between pointers
This is a less common scenario to be honest without getting super complicated, but should be easy to implement. Note that trying to use a setActive method for this would be crazy, and is one of the reasons I think Java (and .NET) is going to need to implement something completely differently for Touch.
```
driver.actions({async: true})
  .move({ x: 100, y: 50}, finger1)
  .pause(finger2)
  .press(finger1)
  .pause(finger2)
  .release(finger1)
  .pause(finger2)
  .move({x: 100, y: 100}, finger1) 
  .move({x: 100, y: 500}, finger2) 
  .press(finger1)
  .press(finger2)
  .move({x: 100, y: 250}, finger1) 
  .move({x: 100, y: 350}, finger2) 
  .release(finger1)
  .release(finger2)
  .perform()
```

### Perform Common Actions
So you could use the code above to do a tap and a pinch, but... that's way more than a user should need to deal with. We'd want to figure out something like:
```
driver.actions()
  .tap({ x: 100, y: 50})
  .pinch()
  .perform()
```
But yes, agree completely about following Appium's lead everywhere we can because this will get complicated quickly.

**Comment by diemol** [comment]
Label removed as per https://www.selenium.dev/meetings/2023/tlc-02-02/#proposalsdecisions
