### ISSUE TITLE
[🐛 Bug]: Builder.forBrowser(Browser.INTERNET_EXPLORER) not use selenium-manager

### ISSUE THREAD

**Issue by cbl980226** [SeleniumHQ/selenium#11579]
### What happened?

new Builder().forBrowser(Browser.INTERNET_EXPLORER).build()

not trying Selenium Manager

(seleniumManager.driverLocation)[https://github.com/SeleniumHQ/selenium/blob/634d19acf1274276f40533f4a1243adf2d1be8fb/javascript/node/selenium-webdriver/common/seleniumManager.js#L66] can't get ie driver location

### How can we reproduce the issue?

```shell
mkdir tests
cd tests
npm init -y
npm add -D selenium-webdriver
touch webdriver.test.js
node webdriver.test.js
```

webdriver.test.js
```js
const { Browser, Builder, By } = require('selenium-webdriver');

(async () => {
  // const driver = await new Builder().forBrowser(Browser.CHROME).build();
  const driver = await new Builder().forBrowser(Browser.INTERNET_EXPLORER).build();
  await driver.get('https://www.selenium.dev/selenium/web/web-form.html');
  const textBox = await driver.findElement(By.name('my-text'));
  const submitButton = await driver.findElement(By.css('button'));

  await textBox.sendKeys('Selenium');
  await submitButton.click();
  await driver.quit();
})();

```

### Relevant log output

```shell
$ node webdriver.test.js
The IEDriverServer.exe executable could not be found on the current PATH,
trying Selenium Manager
Unable to obtain driver using Selenium Manager: Error: Unable to locate dr
iver associated with browser name: internet explorer
```

### Operating System

Windows 10

### Selenium version

Node selenium-webdriver@4.8.0

### What are the browser(s) and version(s) where you see this issue?

None

### What are the browser driver(s) and version(s) where you see this issue?

None

**Comment by diemol** [comment]
Is this still happening with 4.8.0?

**Comment by cbl980226** [comment]
> Is this still happening with 4.8.0?

Yes, I tried it with 4.8.0 version using the example above , it still happens.

driverLocation(Browser.INTERNET_EXPLORER) not allowed

https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/ie.js#L409
```js
  if (!exe) {
    console.log(
      `The ${IEDRIVER_EXE} executable could not be found on the current PATH, trying Selenium Manager`
    )

    try {
      exe = driverLocation(Browser.INTERNET_EXPLORER)
    } catch (err) {
      console.log(`Unable to obtain driver using Selenium Manager: ${err}`)
    }
  }
```

https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/common/seleniumManager.js#L65
```js
/**
 * currently supported browsers for selenium-manager
 * @type {string[]}
 */
const Browser = ['chrome', 'firefox', 'edge']

function driverLocation(browser) {
  if (!Browser.includes(browser.toLocaleString())) {
    throw new Error(
      `Unable to locate driver associated with browser name: ${browser}`
    )
  }
 }
```

**Comment by diemol** [comment]
Are you behind a proxy?

**Comment by cbl980226** [comment]
> Are you behind a proxy?

Yes I use the clash proxy

**Comment by diemol** [comment]
OK, this is not supported yet. This PR implements it https://github.com/SeleniumHQ/selenium/pull/11575, and we should be able to release in a couple of weeks.

**Comment by cbl980226** [comment]
Sorry, I think maybe not proxy problem.

selenium-manager.exe is work for me with proxy.

I created a repository => https://github.com/cbl980226/selenium-manager-test

I only change driverLocation:
https://github.com/cbl980226/selenium-manager-test/blob/master/selenium-manager.js#L59
https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/common/seleniumManager.js#L66

**Comment by diemol** [comment]
@bonigarcia could you please help us to check this?

**Comment by bonigarcia** [comment]
I think the Selenium JavaScript binding should support IExplorer as well, since Selenium Manager already does. If I am not wrong, in this line:

https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/common/seleniumManager.js#L33

... it seems that the JavaScript binding does not supports IExplorer yet.

**Comment by diemol** [comment]
Good point. Thanks @bonigarcia! 

@harsha509, is this a matter of adding `iexplorer` to that array?

**Comment by titusfortner** [comment]
For next version of Selenium, we are hopefully moving to parsing the options instance for browser name and browser version and not using the driver name.

**Comment by harsha509** [comment]
Looks like a diff issue, if IEDriver not found, JS binding send `internet explorer` to selenium-manager instead of `iexplorer`!

Fixed with above commit. tested in windows machine!

**Comment by harsha509** [comment]
> Good point. Thanks @bonigarcia!
> 
> @harsha509, is this a matter of adding `iexplorer` to that array?

Also, added iexplorer into array!

Thank you @diego, @titusfortner !
