### ISSUE TITLE
[🐛 Bug]: Selenium4: RemoteWebDriver cannot connect to selenoid

### ISSUE THREAD

**Issue by egorsh0** [SeleniumHQ/selenium#11572]
### What happened?

Previously, using Selenium version 3.141, connecting to selenoid ui did not cause problems. Sample code below:
```c#
var chromeOptions = new ChromeOptions
{
};

chromeOptions.AddAdditionalCapability("version", "101.0", true);
chromeOptions.AddAdditionalCapability("enableVNC", true, true);
chromeOptions.AddAdditionalCapability("platform", "ANY", true);
chromeOptions.AddAdditionalCapability("name", "Test connect", true);
            
var str = chromeOptions.ToString();
try
{
   var driver = new RemoteWebDriver(new Uri("http://selenoid:4444/wd/hub"), chromeOptions);
   driver.Url = "https://www.google.com";
   driver.Navigate().GoToUrl("https://www.google.com");
                
   Thread.Sleep(10000);
   driver.Quit();
}
catch (Exception e)
{
   Console.WriteLine(e);
   throw;
}
```
After upgrading to Selenium 4.0.0 and above (last test was on version 4.7.0) trying to create a connection with selenoid ui doesn't throw any errors, but in the WebDriver model, creating a Response shows the value "browser not set"
![browser not set](https://user-images.githubusercontent.com/12814406/213654859-023b5a21-4a16-4f94-bccc-beb9ff291b87.PNG)

What were the options to create a connection:
- change AddAdditionalCapability to AddAdditionalOption
```c#
chromeOptions.AddAdditionalOption("enableVNC", true, true);
chromeOptions.AddAdditionalOption("name", "Test connect");
chromeOptions.AddAdditionalOption("version", "101.0");
chromeOptions.AddAdditionalOption("platform", "ANY");
```
- creating a dictionary with the selenoid:options parameter
```c#
Dictionary<string, object> selenoidOptions = new Dictionary<string, object>
{
    {
        "enableVNC", true
    },
    {
        "name", "Test connect"
    },
    {
         "version", "101.0"
    }
 };
 chromeOptions.AddAdditionalOption("selenoid:options", selenoidOptions);
```
- creating options with parameters
```c#
var chromeOptions = new ChromeOptions
{
    BrowserVersion = "101.0",
    PlatformName = "any"
};
```
All options give the same error.
Browser and driver version 109.*

### How can we reproduce the issue?

```shell
Step 1: Create a dotnet Project
Step 2: Add Selenium.WebDriver
Step 3: Write script for launching browser
```

### Relevant log output

```shell
nothing errors in log
```

### Operating System

Windows 10

### Selenium version

NET.5

### What are the browser(s) and version(s) where you see this issue?

Chrome 109

### What are the browser driver(s) and version(s) where you see this issue?

109.0.5414.74

**Comment by diemol** [comment]
Not sure what Selenoid expects as capabilities. Please reach out to them with the issue.
