### ISSUE TITLE
[🐛 Bug]: Internet Explorer Driver doesn' give you a correct size screenshot.

### ISSUE THREAD

**Issue by nwatab** [SeleniumHQ/selenium#11585]
### What happened?
I captured a screenshot (visible area or entire page) with Internet Explorer (IE mode of Edge), and the screenshot I took is not correct in size.

## Screenshot of my display (PII is covered manually in postprocess by me)
<img width="803" alt="214032795-5cba5db6-3575-4066-b73e-e2143cb4cfaf" src="https://user-images.githubusercontent.com/16299750/214193819-562f5854-6f88-443e-bebc-9afff2ca92c9.png">

## Screenshot I took with `driver.GetScreenshot().SaveAsFile(..., ...)` (PII is covered manually in postprocess by me)
<img width="409" alt="1(817x450)" src="https://user-images.githubusercontent.com/16299750/214032943-af42a82b-2db5-44a5-903d-d8f5c1a2e0b4.png">

## What it should be
Instead of capturing only the top left corder, it should capture visible area or entire page (tll the end of scroll).

Personally, in my case, I'm trying to capture entire page by joining each page's screenshot, but I can't to capture right side of a page, neither calculate height.

### How can we reproduce the issue?

```shell
var ieOptions = new InternetExplorerOptions();
ieOptions.AttachToEdgeChrome = true;
ieOptions.EdgeExecutablePath = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
ieOptions.IgnoreZoomLevel = true;
            
var driver = new InternetExplorerDriver(ieOptions);
driver.Url = "file:///c:/users/path/to/file.html";
var winSize = driver.Manage().Window.Size;  // {Width = 1050 Height = 652}
var html = driver.FindElement(By.TagName("html"));
int innerWidth = Int32.Parse(html.GetAttribute("clientWidth"));  // 479
int innerHeight = Int32.Parse(html.GetAttribute("clientHeight"));  // 972

int targetWidth = 800;
int targetHeight = 450;

driver.Manage().Window.Size = new System.Drawing.Size(
    winSize.Width + targetWidth - innerWidth,
    winSize.Height+ targetHeight - innerHeight
);
System.Drawing.Size size = driver.Manage().Window.Size;  // 878, 623
driver.GetScreenshot().SaveAsFile("C:\\Users\\path\\to\\1.png", OpenQA.Selenium.ScreenshotImageFormat.Png);
var nweInnerWidth = html.GetAttribute("clientWidth");  // "800"
var newInnerHeight = html.GetAttribute("clientHeight");  // "450"
driver.ExecuteScript("window.scrollTo(0," + targetHeight.ToString() + ")");
driver.GetScreenshot().SaveAsFile("C:\\Users\\path\\to\\2.png", OpenQA.Selenium.ScreenshotImageFormat.Png); //not shared in this issue
driver.quit()
```

### Relevant log output

```shell
There's no log.
```

### Operating System

Microsoft windows 11 Home Insider Preview (10.0.25281 Build 25281)

### Selenium version

C# 4.7.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge version109.0.1518.61 (official) (64bit)

### What are the browser driver(s) and version(s) where you see this issue?

Internet Explorer 32bit 4.7.0

### Are you using Selenium Grid?

No, I don't use Selenium Grid.

Edit: I removed white margin in a screenshot.

**Comment by diemol** [comment]
As a test, what happens if you avoid calculations just maximize the window and take a screenshot? Do you see the whole visible area? Just wondering if the calculations are affecting the screenshot size.

**Comment by titusfortner** [comment]
First, with latest IEDriver & Windows 11, you shouldn't need an Options instance at all, it should set those values by default.

Second, per the spec, screenshot is intentionally only the active ViewPort, not full page, so yes, you'd have to scroll/stitch yourself.

The top screenshot is what you've taken on your system, and the bottom screenshot is what Selenium generates? Is the test paused on the page, so we're sure we're comparing the same thing?

**Comment by nwatab** [comment]
@diemol 
Thanks. I also tried `driver.Manage().Window().Maximize()`, but it did nothing at all. On the other hand, set `driver.Manage().Window.Size` worked well (I can share source code and results when I have a chance). By changing window size, the screenshot can be smaller (cropped into a small part at the top left), but not bigger than the one shown in my post.

> The top screenshot is what you've taken on your system, and the bottom screenshot is what Selenium generates?  
Yes, exactly. The view port area in the top screenshot should be the same as the bottom one.

**Comment by titusfortner** [comment]
I'm wondering if the screenshot is assuming a different zoom level somehow :-/ 
You can take a screenshot on an element as well, what happens if you take a screenshot of the container you are interested in?

**Comment by nwatab** [comment]
@diemol 
## Case: driver.Manage().WIndow.Maximaze();

The window size gets a little bit bigger, but It still doesn't solve a problem. Maybe zoom configuration is different (I kept `ieOptions` as it was to make comparison clear).

Saved screenshot (C:\\path\\to\\1.png)
<img width="617" alt="1windowMaximize" src="https://user-images.githubusercontent.com/16299750/214472869-2247c012-0f44-4634-b958-992ebd7abd67.png">

Source code
```cs
var ieOptions = new InternetExplorerOptions();
ieOptions.AttachToEdgeChrome = true;
ieOptions.EdgeExecutablePath = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
ieOptions.IgnoreZoomLevel = true;

var winSize = driver.Manage().Window.Size; // {Width = 1050, Height = 652}
var innerWidth = Int32.Parse(html.GetAttribute("clientWidth"));  // 972
var innerHeight = Int32.Parse(html.GetAttribute("clientWidth"));  // 479
var driver = new InternetExplorerDriver(ieOptions);
driver.Url = "file:///c:/path/to/file.html";

var html = driver.FindElement(By.TagName("html"));
driver.Manage().Window.Maximize();
driver.GetScreenshot().SaveAsFile("C:\\path\\to\\1.png", OpenQA.Selenium.ScreenshotImageFormat.Png);
System.Drawing.Size size = driver.Manage().Window.Size;  // 1295, 687, which got a little bit bigger 
var newInnerWidth = html.GetAttribute("clientWidth");  // "1216"
var newInnerHeight = html.GetAttribute("clientHeight");  // "515 "

driver.Quit();

```

**Comment by nwatab** [comment]
@titusfortner 
Yeah, I thought about the zoom level as well. It seems `dotnet` doesn't support element level screenshot? Maybe you happen to know how to take it?
https://www.selenium.dev/selenium/docs/api/dotnet/

**Comment by diemol** [comment]
@nwatab OK, so if this is an error easily reproducible, let's avoid ambiguity and please help us by providing a test case using the latest Selenium version and IEDriver version. Do not forget to put the website you are using or if you are using a local page, please attach the HTML code for us to run the code and reproduce the issue.

**Comment by diemol** [comment]
Closing as no more information was given.
