### ISSUE TITLE
[🐛 Bug]: CI is coming up with various errors when it is run

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#11581]
### What happened?

CI is coming up with errors when it is run.

The errors are:

1. "System.InvalidOperationException : The type is invalid for conversion. You requested domains of type 'OpenQA.Selenium.DevTools.V108.DevToolsSessionDomains', but the version-specific domains for this session are 'OpenQA.Selenium.DevTools.V109.V109Domains'"
2. WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange". This causes an error that is about being unable to locate an element.

### How can we reproduce the issue?

```shell
Run the CI action in the Selenium repository
```

### Relevant log output

```shell
1. "System.InvalidOperationException : The type is invalid for conversion. You requested domains of type 'OpenQA.Selenium.DevTools.V108.DevToolsSessionDomains', but the version-specific domains for this session are 'OpenQA.Selenium.DevTools.V109.V109Domains'"
2. WARNING: Error: Phase "profile-before-change" is finished, it is too late to register completion condition "OS.File: flush I/O queued before profileBeforeChange". This causes an error that is about being unable to locate an element.
```

### Operating System

macOS

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

**Comment by diemol** [comment]
Can you share the link where this is happening please?

**Comment by ollie-iterators** [comment]
It is the new CI workflow that was made while working on improving how Selenium works with Bazel that was done in the PR: https://github.com/SeleniumHQ/selenium/pull/11544. The link where you can see those errors is: https://github.com/SeleniumHQ/selenium/actions/workflows/ci.yml, for a specific workflow, there is: https://github.com/SeleniumHQ/selenium/actions/runs/3986201046

**Comment by diemol** [comment]
Thank you. Could you please also provide the line where this happens? Searching through all the logs for the message is a bit exhausting.

**Comment by titusfortner** [comment]
.NET tests need to match a specific version of Chrome, so when the CI updates the default version, the tests will break. The test code needs to be updated when the CI updates.

**Comment by ollie-iterators** [comment]
Shouldn't that have been done when working on Selenium Manager?

**Comment by ollie-iterators** [comment]
Just search for Error in the logs for one of the failing CI Actions.

**Comment by titusfortner** [comment]
For *reasons* .NET tests are not run with Bazel, which means we can not move the resources where they need to be to use them with bazel. So selenium manager is packaged into the release, but is not used for testing. :(

**Comment by ollie-iterators** [comment]
Isn't that part of the Bazel improvement project? Getting .Net to get Selenium Manager for tests. Also, that is only for the .Net code. There are errors in the Java, Javascript, Ruby, and sometimes Python builds for the CI build.

**Comment by titusfortner** [comment]
Sure, we've decided to switch to the official  .NET bazel rules, but none of us have experience with it.

**Comment by diemol** [comment]
> Just search for Error in the logs for one of the failing CI Actions.

I appreciate issues raised that can help us improve our CI. However, it'd be nice to get a pointer where things are actually happening because you have already seen it in the logs and can provide a link to the exact line where it happens. If you find the time, please help us with more constructive feedback and we'd be glad to time slot this activity.

**Comment by ollie-iterators** [comment]
If the issue with Bazel is about external dependencies, then Bazel 5.0+ has Bzlmod. https://bazel.build/build/bzlmod

**Comment by ollie-iterators** [comment]
Errors list:

System.InvalidOperationException : The type is invalid for conversion. You requested domains of type 'OpenQA.Selenium.DevTools.V108.DevToolsSessionDomains', but the version-specific domains for this session are 'OpenQA.Selenium.DevTools.V109.V109Domains'
-.NET Browser Tests (Chrome net48): 333, 353, 369, 393, 413, 433, 454, 474, 495, 515, 542, 558, 578, 598, 623, 643, 660, 680, 704, 724, 740, 760, 784.
- .NET Browser Tests (Chrome 6.0), 364, 377, 393, 413, 429, 445, 462, 478, 495, 511, 533, 545, 561, 578, 599, 611, 627, 643, 663, 679, 691, 707, 727
- .NET Browser Tests (Chrome, netcoreapp3.1): TODO
- .NET Browser Tests (Firefox, net60): TODO
-

**Comment by titusfortner** [comment]
Would you like to PR the update to the  CDP version references in the test code to match the chrome version being used by the CI?

**Comment by titusfortner** [comment]
I updated the .NET tests. cab3949d60d9f24c2654be5a488bfc0b5eded9f2

We aren't keeping an issue open to track CI failures. Pull Requests for fixes will always be appreciated, and any specific suggestions for fixes will be considered.
