### ISSUE TITLE
[🚀 Feature]: Version-agnostic CDP

### ISSUE THREAD

**Issue by RenderMichael** [SeleniumHQ/selenium#11591]
### Feature and motivation

I use CDP pretty extensively, and it adds a lot of seemingly unnecessary work matching the current chrome version to the available CDP's (we don't just use the latest, we have compatibility requirements).

However, all the tiny changes between versions are irrelevant to us. When scanning network logs, for example, all we're looking for is the request and response headers and bodies, the  request verb and response code. 

I propose a minimal version of CDP which doesn't need changing between version. 

### Usage example

Presumably exactly the same as versioned CDP works

**Comment by titusfortner** [comment]
Yes! We're actively working on implementing WebDriver BiDi that will do this in a cross-browser/vendor-maintained manner.

You can read about it here: https://www.selenium.dev/documentation/webdriver/bidirectional/
