### ISSUE TITLE
[🐛 Bug]: Chrome driver is not killed even after trying driver.quit() 

### ISSUE THREAD

**Issue by shravanv1** [SeleniumHQ/selenium#11602]
### What happened?

Chrome driver is not killed even after trying driver.quit() 

### How can we reproduce the issue?

```shell
not sure
```

### Relevant log output

```shell
1200      6909 52549  0 Jan30 ?        00:00:00 /opt/selenium/chromedriver-94.0.4606.61 --port=3605
1200      7795 52549  0 07:54 ?        00:00:00 /opt/selenium/chromedriver-94.0.4606.61 --port=32223

Toady date is 31 but the above process is still running.
```

### Operating System

mac0S

### Selenium version

org.openqa.grid.selenium.GridLauncherV3 

### What are the browser(s) and version(s) where you see this issue?

chromedriver-94.0.4606.61

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver-94.0.4606.61

### Are you using Selenium Grid?

Selenium grid 3

**Comment by diemol** [comment]
We do not support Grid 3 anymore, so please upgrade and create a new issue if the problem still exists.

**Comment by diemol** [comment]
I will leave some links below in case you want to ask questions.
