### ISSUE TITLE
Monkey Patching selenium driver

### ISSUE THREAD

**Issue by sauravdas1997** [SeleniumHQ/selenium#11600]
### What happened?

Hi,
I am able to patch the selenium driver while using chrome, firefox drivers
```
  class Selenium::WebDriver::Driver
    bridge = instance_method(:create_bridge)
    define_method(:create_bridge) do
      driver = bridge.bind(self).call
    end
  end
```

But unable to do so with remote driver.

My use case, is that whenever the user creates a driver object, I want to override the constructor (or any other method) to get the driver object and all the data related to it.

### How can we reproduce the issue?

```shell
`  class Selenium::WebDriver::Driver
    bridge = instance_method(:create_bridge)
    define_method(:create_bridge) do
      driver = bridge.bind(self).call
    end
  end`
This throws an error when remote driver is used.
```

### Relevant log output

```shell
Not showing any error, it is not going inside the `define_method` and thus not able to receive the driver object.
```

### Operating System

macOS Monterey

### Selenium version

Ruby 2.7.5, Selenium 4.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 109, 108

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

**Comment by diemol** [comment]
Not sure if this is a valid bug report, let's see what @titusfortner says.

However, you mention there is an error on the `How can we reproduce the issue?` section, what is the error?

**Comment by titusfortner** [comment]
I don't understand your use case.
You can already get the bridge instance from the driver, and start a new driver with that bridge instance.

```
          driver = described_class.new
          capabilities = driver.capabilities
          bridge = driver.instance_variable_get(:@bridge)
          http_client = bridge.http
          session_id = bridge.session_id

          driver2 = described_class.new(bridge: bridge)
          bridge2 = driver2.instance_variable_get(:@bridge)

          expect(driver2.capabilities).to eq capabilities
          expect(bridge2).to eq bridge
          expect(bridge2.http).to eq http_client
          expect(bridge2.session_id).to eq session_id
```

**Comment by sauravdas1997** [comment]
Reframing the doubt.

## Setup
I am creating a fresh driver instance.
```
def create_my_selenium_driver
  @driver = Selenium::WebDriver.for :chrome
  @driver.close
  puts '[DRIVER CREATE] '
end

create_my_selenium_driver
```

## What I want ?
I want to extract all the capabilities from this driver instance, as soon as it is created.
```
class Selenium::WebDriver::Driver
  bridge = instance_method(:create_bridge)
  define_method(:create_bridge) do
    driver = bridge.bind(self).call
    $driver = driver
  end
end
```
I was trying the above piece of code but unable not able override this create_bridge method. I need to do it both for `chrome` and `remote` driver. My use case is not to send the created driver instance through any method. I want to override it.

Note: Those 2 snippets are present in different files.

Can you help me achieve that ?

**Comment by titusfortner** [comment]
> I want to extract all the capabilities from this driver instance

You can get the capabilities with:
```
driver.capabilities
```

Since this isn't a bug or a feature request, I'm going to redirect you to where you can ask your question.
