### ISSUE TITLE
[🐛 Bug]: Unwanted connections when connecting to https-url

### ISSUE THREAD

**Issue by erik-rnbt** [SeleniumHQ/selenium#11605]
### What happened?

When I open a https-url in Selenium, Chrome or Edge open the url without any problems but in the background they try to establish a connection to google or microsoft servers which is blocked by my firewall.

It looks like Chrome/Edge is trying to verify the Certificates of the url, but i dont want this to happen cause they are self-signed anyways. 

### How can we reproduce the issue?

```shell
Open any Https-Url with a Chrome or Edge and your network should try to connect to different IPs of Google or Microsoft.
```

### Relevant log output

```shell
Logs are just the destination addresses my firewall is showing.
For example if i use Chrome:
IP:
172.217.16.170
142.251.36.202
142.251.36.170
...
Port:
443
```

### Operating System

Linux

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.71

### Are you using Selenium Grid?

4.7.2

**Comment by diemol** [comment]
Selenium is not trying to connect to the services you mention. It is either ChromeDriver/Chrome or MsEdgeDriver/Edge.

Please report the issue to them. I will leave some links below.
