### ISSUE TITLE
[🐛 Bug]: safari node is not running in hub node configuration for selenium 4.

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#11617]
### What happened?

Using serenity BDD framework 3.3.10, when run safari test in grid getting timeout exception. The test is going to queue in grid console. 

when tried as standalone, test is running successfully. 

serenity version : 3.3.10 
Selenium-server-4.3.0.jar 
safari version -15.6.1

run configuration : 

Java -jar selenium-server-4.3.0.jar node —hub “hub url” —port 4900 —host host name. 

Also tried with safari-driver path , —detect-drivers true . 

same configuration if change to java -jar jar path standalone - works fine . 

relates to this issue: 

https://github.com/SeleniumHQ/selenium/issues/11390

Since I’m unable to reopen this , created new.

attaching the node log . 

> #
[safari_node_executionlog.txt](https://github.com/SeleniumHQ/selenium/files/10637358/safari_node_executionlog.txt)
![A2E0E61D-447C-425A-8D16-016EF5AF63C4](https://user-images.githubusercontent.com/16626518/216873048-ef9026e1-e5a9-476e-838c-6b581a03b358.png)

### How can we reproduce the issue?

```shell
Use selenium/serenity test, run as hub node configuration, test is queued . 

Run configuration from IntelliJ : 

-Denvironment=uat -Dwebdriver.driver=remote -Dwebdriver.remote.driver=safari
```

### Relevant log output

```shell
Timeout exception in the run console.
```

### Operating System

Mac OS Monterey 

### Selenium version

serenity -3.3.10

### What are the browser(s) and version(s) where you see this issue?

Safari 15.6.1

### What are the browser driver(s) and version(s) where you see this issue?

Safari 15.6.1

### Are you using Selenium Grid?

Selenium server 15.6.1

**Comment by remyanekkuth** [comment]
If needed, I can get the hub log as well. 
@diemol  @pujagani  appreciate your help since it’s blocking us for safari configuration

**Comment by krmahadevan** [comment]
@remyanekkuth - What happens when you try the same thing using the latest released selenium version ? You are using `4.3.0` which is not the latest. Can you try again using `4.8.0` and post back the results ?

**Comment by krmahadevan** [comment]
Also just to ensure that we rule out any discrepancy that can be occurring due to serenity, please try using a plain vanilla selenium test method that just spawns a safari browser against the selenium grid (using the latest selenium client bindings ofcourse)

**Comment by remyanekkuth** [comment]
@krmahadevan sure I will try with latest version and get back tomorrow with results

**Comment by remyanekkuth** [comment]
@krmahadevan  tried with selenium server 4.8.0 and behavior is same. 
attaching log from Mac node , I see some errors but not sure what it is. 

[02062023-execution_new.txt](https://github.com/SeleniumHQ/selenium/files/10670275/02062023-execution_new.txt)

I didn’t get a chance to try selenium test. Will try it and update meanwhile.

**Comment by krmahadevan** [comment]
@remyanekkuth - I noticed that you have linked to a similar issue which I had debugged as well. I think its due to the fact that your capabilities are not matching with any node. Please try using plain vanilla webdriver test that uses safari and post back. You will have to look into what you are doing in serenity test to find the gaps and fix it.

**Comment by remyanekkuth** [comment]
@krmahadevan sure I will try selenium test with same configuration. 

Did you find anything from the node log file I attached.

**Comment by krmahadevan** [comment]
@remyanekkuth - The logs don't reveal any issues. So it looks like the hub is not able to match your test case's browser request with the node (Most probably a goof'ed up desired capabilities). Did you try a plain vanilla test against the grid and check if that runs ? My hunch is that you are missing some setting in your serenity BDD test.

**Comment by remyanekkuth** [comment]
@krmahadevan im trying to run selenium test. Since our configuration is for serenity it’s giving me issues. 
would you please point out any selenium template I can use

**Comment by krmahadevan** [comment]
@remyanekkuth - Please run this against your grid and share the result

```java
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.safari.SafariOptions;

public class SafariExample {

  public static void main(String[] args) throws MalformedURLException {
    RemoteWebDriver rwd = null;
    try {
      rwd = new RemoteWebDriver(new URL("http://localhost:4444"), new SafariOptions());
      rwd.get("https://www.selenium.dev");
      System.err.println("Title " + rwd.getTitle());
    } finally {
      if (rwd != null) {
        rwd.quit();
      }
    }
  }
}
```

If this works, then you would need to fix your serenity configuration. Not sure what can be done from selenium side.

**Comment by remyanekkuth** [comment]
I’m having some gradle dependency issues when tries to run it. 
I will update on this option. Meanwhile @krmahadevan  I tried with adding the capabilities in the serenity.conf for running with safari browser and now other browsers are not working with 
-Denvironment=uat -Dwebdriver.remote.driver= chrome 
It always goes to safari. 

How can we add the other browsers or make it work.

**Comment by krmahadevan** [comment]
@remyanekkuth 

> Meanwhile @krmahadevan I tried with adding the capabilities in the serenity.conf for running with safari browser and now other browsers are not working with
-Denvironment=uat -Dwebdriver.remote.driver= chrome
It always goes to safari.

I am not familiar with Serenity. You may need to perhaps post this on the serenity forums  or maybe go through their documentation to figure that out https://serenity-bdd.github.io/docs/guide/driver_config


> I’m having some gradle dependency issues when tries to run it. I will update on this option.

You just need to create a sample maven project with selenium as a dependency and then run it against your Hub. That should suffice. This will clearly tell us if the problem is with your test project setup or if its with the selenium grid (which I doubt)

**Comment by remyanekkuth** [comment]
Since ours is gradle test, I was trying to utilize old existing application to test. I will try adding only the selenium jar and test.

**Comment by krmahadevan** [comment]
@remyanekkuth sure I understand. But the intent of this exercise is to figure out what is causing the problem. 

Is it your test project (or) is it Selenium standalone `4.8.0` jar.

So if you create a sample maven project and manage to run a safari test against the grid, then it will tell us clearly that the problem is most likely in your test project.

**Comment by remyanekkuth** [comment]
@krmahadevan  sorry for the late response. I was having trouble connecting to remote selenium hub. 
I was able to successfully run selenium test against Safari for 4.8.0 grid server. Looks like the issue I am facing is due to Serenity version.

**Comment by krmahadevan** [comment]
@remyanekkuth so can we close this issue while you take this up with serenity folks ?

**Comment by remyanekkuth** [comment]
Thank you @krmahadevan . Closing the issue .
