### ISSUE TITLE
[🐛 Bug]: Selenium 4.8.0 | Chrome 109 | Timed out waiting for driver server to stop

### ISSUE THREAD

**Issue by nainig-impactqa** [SeleniumHQ/selenium#11627]
### What happened?

We are seeing high failures in test runs, due to **Timed out waiting for the driver server to stop**. These started coming from Chrome 109, hence we upgraded from selenium 4.6.0 to 4.8.0,  As per Selenium 4.8.0 release (https://www.selenium.dev/blog/2023/selenium-4-8-0-released/), it supports chromerdriver v107, v108 and v109.

We are on Selenium 4.8.0 and JDK 11. The box we are using is of very high configuration, and the CPU utilization and Memory utilization are low even with 60+ threads. 

**Error Info**:
Skip reason due to test failure as: Timed out waiting for driver server to stop. Build info: version: '4.8.0', revision: '267030adea' System info: [os.name](http://os.name/): 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1' Driver info: org.openqa.selenium.chrome.ChromeDriver Command: [9e8713ab697f632b5fa48a464fa67d11, quit {}] Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.120, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Program Files (x86)\scop...}, goog:chromeOptions: {debuggerAddress: localhost:58415}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:58415/devtoo..., se:cdpVersion: 109.0.5414.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Session ID: 9e8713ab697f632b5fa48a464fa67d11

### How can we reproduce the issue?

```shell
Run with multiple threads with Selenium 4.8.0 and Chrome 109
```

### Relevant log output

```shell
Error Info:
Skip reason due to test failure as: Timed out waiting for driver server to stop. Build info: version: '4.8.0', revision: '267030adea' System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1' Driver info: org.openqa.selenium.chrome.ChromeDriver Command: [9e8713ab697f632b5fa48a464fa67d11, quit {}] Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 109.0.5414.120, chrome: {chromedriverVersion: 109.0.5414.74 (e7c5703604da..., userDataDir: C:\Program Files (x86)\scop...}, goog:chromeOptions: {debuggerAddress: localhost:58415}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:58415/devtoo..., se:cdpVersion: 109.0.5414.120, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Session ID: 9e8713ab697f632b5fa48a464fa67d11
```

### Operating System

Windows, MAC

### Selenium version

Selenium 4.8.0, JDK 11

### What are the browser(s) and version(s) where you see this issue?

Chrome 109 (109.0.5414.120)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriverVersion: 109.0.5414.74 (Downloaded by Selenium Manager under .cache folder)

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Does this happen only when using Chrome 109? What happens if you use Chrome 108?

**Comment by nainig-impactqa** [comment]
We did not face this issue with Chrome 107 with Selenium 4.6.0.

**Comment by diemol** [comment]
What about Chrome 107/108 with Selenium 4.8.0?

**Comment by nainig-impactqa** [comment]
We have not tried that, because chrome upgraded, from 107 to 109, and then as per the selenium 4x release, we upgraded from 4.6.0 to 4.8.0

**Comment by nainig-impactqa** [comment]
**### With Selenium 4.6.0 and Chrome 109**: We observed, it was trying to establish a connection with 107 chromedriver and in the parallel run, many tests failed with errors in establishing the connection. The issue is also reproducible with 5 threads and at times with a single thread.

**### With Selenium 4.8.0 and Chrome 109**: Today, we tried with again one more parallel execution with 30 threads (parallel browser sessions). Out of 1710 test methods, 1592 tests failed due to Could not start a new session. Response code 500. Message: unknown error: DevToolsActivePort file doesn't exist Host info: host: 'XXXXXXXXXX01', ip: 'XXX.XXX.XXX.XX' Build info: version: '4.8.0', revision: '267030adea' System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1' Driver info: org.openqa.selenium.chrome.ChromeDriver Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors, --test-type, --disable-extensions, --disable-infobars, --disable-save-password-bubble, --enable-geolocation, --start-maximized, --disable-notifications, --disable-component-update, --no-sandbox, --disable-dev-shm-usage, --safebrowsing-disable-down..., --safebrowsing-disable-exte...], extensions: [], prefs: {download.default_directory: D:\xxxxxxxxxxxxx\xxxxxxx..., download.prompt_for_download: false, profile.content_settings.exceptions.automatic_downloads.*.setting: 1, safebrowsing.enabled: false}}}], desiredCapabilities=Capabilities {browserName: chrome, goog:chromeOptions: {args: [--ignore-certificate-errors, --test-type, --disable-extensions, --disable-infobars, --disable-save-password-bubble, --enable-geolocation, --start-maximized, --disable-notifications, --disable-component-update, --no-sandbox, --disable-dev-shm-usage, --safebrowsing-disable-down..., --safebrowsing-disable-exte...], extensions: [], prefs: {download.default_directory: D:\xxxxxxxxxxxxx\xxxxxxx..., download.prompt_for_download: false, profile.content_settings.exceptions.automatic_downloads.*.setting: 1, safebrowsing.enabled: false}}}}]. 

It ended up in many stale chrome.exe and chromedriver.exe sessions and took CPU utilization to 100%. When we killed all these sessions, the CPU utilization came down to 10%.

**Comment by diemol** [comment]
This seems to be an issue in Chrome/ChromeDriver.

https://bugs.chromium.org/p/chromedriver/issues/detail?id=4331
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4333
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4343

Please follow updates on the first link.

**Comment by achavva** [comment]
Hi all, I am facing the same issue.....any help please?
Selenium 4.6.0
Java 17
Chrome browser 110

**Comment by nainig-impactqa** [comment]
Downgrade Selenium to 4.6.0,  Chrome to 107 and suppress chrome updates.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by achavva** [comment]
Sure I will try to do that, but it's a temporary fix right. Where can i get
update on this fix?

Thanks for your time in replying.

**Comment by ndtreviv** [comment]
I get the original error (`Timed out waiting for driver server to stop` - nothing about `DevToolsActivePort`) on Selenium 4.6.0, Java 17 and Chrome 108.

None of the issues linked in https://github.com/SeleniumHQ/selenium/issues/11627#issuecomment-1422445986 seem appropriate.

Is the current advice still to downgrade to Chrome 107?

**Comment by nainig-impactqa** [comment]
Yes, you are correct. 

We still faced the issue with Selenium 4.6.0, 4.8.0, 4.8.1, and Chrome 107. As our daily regression runs were getting impacted and giving false failures due to "Timed out waiting for driver server to stop" issue, lastly, we downgraded to Selenium 3.141.59 and Boni Garcia (WebDriverManager).  

It seems Selenium Manager will take more time to come over this issue.

**Comment by achavva** [comment]
Hi guys I waited quite long to get help but none... I resolved the issue by adding both driver.close() and driver.quit().... Not sure this is the actual solution but I got luck... Try urs all the best

**Comment by ndtreviv** [comment]
> Hi guys I waited quite long to get help but none... I resolved the issue by adding both driver.close() and driver.quit().... Not sure this is the actual solution but I got luck... Try urs all the best

I was also already doing this to no avail, alas.

**Comment by lnataraj** [comment]
while the test is in progress I'm getting the same error with Selenium 4.3.0 and chrome driver 111.  can anyone help me with the workaround or fixes?
