### ISSUE TITLE
[🚀 Feature]: Grid customizing outside of the Selenium project

### ISSUE THREAD

**Issue by gadgadskiy** [SeleniumHQ/selenium#11624]
### Feature and motivation

Hi, team!
I have a big project on Selenium 3 with a few of our custom features, and we want to save them during the migration to Selenium 4.
While diving into your current code, I faced a problem: I couldn't extend components located in `org.openqa.selenium.grid.*` package:

1. I can't add your pom as a parent because it has a packaging "jar."
2. The packages are still absent after adding your artifacts as dependencies (selenium-java, selenium-dev tools-v109, etc.). The last version where I saw them is 4.0.0-alpha-2.

Maybe I skipped the other abilities to add customizing, which lies on the surface. What is the easiest way to extend grid features in my custom project?

### Usage example

I want to implement in the separate project classes like `org.openqa.selenium.grid.data.SlotMatcher`, `org.openqa.selenium.grid.node.Node`, etc.

**Comment by krmahadevan** [comment]
@gadgadskiy - To learn how to build your own node, please refer to https://www.selenium.dev/documentation/grid/advanced_features/customize_node/

**Comment by krmahadevan** [comment]
For working with a custom slot matcher (an implementation of `org.openqa.selenium.grid.data.SlotMatcher`) , you can pass in a fully qualified class name via the parameter `----slot-matcher` when you start the `hub` (or) `distributor`

To get detailed help run `java -jar selenium-server-4.8.0.jar hub --help`

> I can't add your pom as a parent because it has a packaging "jar."

You can create your parent pom file which brings in the selenium dependencies as dependencies which you can extend from. Would that not work ?

> What is the easiest way to extend grid features in my custom project?

Apart from the already called out ones, can you please call out explicitly as to what all are you looking at customizing?

If you are looking at adding your own custom grid ui, then it wont be possible out of the box, but you can always build a simple web application that basically uses the endpoints as explained [here](https://www.selenium.dev/documentation/grid/advanced_features/endpoints/) to slurp data and then visualise them on the UI.

The grid now lets you build persistence and thus allows you to scale horizontally the hub (which was earlier the single point of contention). Please refer to this document for more details https://www.selenium.dev/documentation/grid/advanced_features/external_datastore/

**Comment by diemol** [comment]
Thanks for triaging and clarifying, @krmahadevan!

@gadgadskiy, feel free to join us in our chat if you have more questions.

**Comment by gadgadskiy** [comment]
Hi, @krmahadevan. Thank you for the clarification!
The dependency "selenium-grid" mentioned in the article about a custom node is exactly what I need now.
