### ISSUE TITLE
[🐛 Bug]: warning when loading Bridge::COMMANDS

### ISSUE THREAD

**Issue by jdashton** [SeleniumHQ/selenium#11628]
### What happened?

When using Selenium and Chrome with Rails 7 (which implies Zeitwerk mode), the following warning is displayed:

```warning: Expected selenium/webdriver/remote/commands to define Selenium::WebDriver::Remote::COMMANDS but it didn't```

This appears to be because the `COMMANDS` constant is monkey-patched into `class Bridge` in a separate file called `commands.rb`.

One solution would be to merge the contents of `commands.rb` into the file `bridge.rb`.

Another solution would be to add the following line at line 168 in `commands.rb`, after the close of `class Bridge`:
```
      COMMANDS = Bridge::COMMANDS
```

### How can we reproduce the issue?

```shell
After defining a spec that uses Selenium, run
RUBYOPT="-vw" bin/rspec
```

### Relevant log output

```shell
/Users/jdashton/.rvm/gems/ruby-3.2.0@arp_upload_20221130/gems/selenium-webdriver-4.8.0/lib/selenium/webdriver/remote/bridge.rb:626: warning: Expected selenium/webdriver/remote/commands to define Selenium::WebDriver::Remote::COMMANDS but it didn't
```

### Operating System

macOS Ventura Version 13.2

### Selenium version

Ruby 3.2 with selenium-webdriver 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 109

### What are the browser driver(s) and version(s) where you see this issue?

webdrivers 5.2.0

**Comment by titusfortner** [comment]
Thanks. This was fixed by #11603
