### ISSUE TITLE
[🐛 Bug]: download.default_directory after update Chrome and chromedriver not working

### ISSUE THREAD

**Issue by malorny** [SeleniumHQ/selenium#11637]
### What happened?

After update chrome and chromedriver to version 110 chromedriver_mac_arm64 https://chromedriver.chromium.org/downloads
download.default_directory stopped working. Before today's update everything worked.
Please let me know if I need to change anything in the code. The file is downloaded but to the main folder with the application and not to the designated path

chrome_options = Options()
prefs = {'download.default_directory': './x/x'}
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)

### How can we reproduce the issue?

```shell
chrome_options = Options()
prefs = {'download.default_directory': './x/x'}
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)
```

### Relevant log output

```shell
The file is downloaded but to the main folder with the application and not to the designated path
```

### Operating System

macOS Monterey 12.0.1

### Selenium version

4.4.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77

**Comment by malorny** [comment]
I noticed that on windows 10 there is no problem

**Comment by sokol1412** [comment]
@malorny I'm experiencing exactly the same issue on the same Chrome/Chromedriver version. Waiting for the fix.

**Comment by hagaygo** [comment]
Same problem here , our tests that checks file downloads stopped working (still working fine on 109).

Did not test it fully , but it seems it works fine on 110 when not using headless mode , when using headless mode it always faill since it does not find the downloaded file.

**Comment by diemol** [comment]
https://www.selenium.dev/blog/2023/headless-is-going-away/

**Comment by hagaygo** [comment]
@diemol Thanks for the quick response , some how i missed that change , setting the new headless mode seems to eliminate this issue.

**Comment by muppet3000** [comment]
@sokol1412 - Do you know the bug id for Chrome/Chromedriver so that I can follow it's status?

**Comment by malorny** [comment]
> @sokol1412 - Do you know the bug id for Chrome/Chromedriver so that I can follow it's status?

They fix it. Use --headless=new instead --headless and use the entire path to the folder e.g. /Users/xxx/downloads/folder1

**Comment by malorny** [comment]
and download updated chromedriver https://chromedriver.chromium.org/downloads

**Comment by muppet3000** [comment]
Ah, ok thanks. We're using it via a docker-container and the serenity.properties file with `headless=true` so I'll have to work out if switching it to `headless=new` works tomorrow!

**Comment by gerardkmiec** [comment]
Hello. 
Can someone confirm that `headless=new `actually solves the problem with files downloading? 
My tests run on chrome and chromedriver 110, selenium 4.8.1, ubuntu docker container on Actions, download path is defined as an system variable `Environment.SpecialFolder.UserProfile`, however I still have issues with file downloading.
Everything was ok on chrome 109
Thank you!

Edit: I changed docker image to windows, and downloading works fine. It looks like the problem only occurs on ubuntu

**Comment by lordszczepan** [comment]
> 

Hi, I can confirm that this change solves the problem ;)
At least in my c# project.

**Comment by uda832** [comment]
I had the exact same issue where the following worked in previous ChromeDriver versions but it stopped working in 110.0.5481.77 on Windows 10:

```py
chrome_options = Options()
prefs = {'download.default_directory': './x/x'}
chrome_options.add_argument("--headless")
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)
```

I had to make 2 changes:
1. Use the new headless argument as suggested by the previous answers:
```py
chrome_options.add_argument("--headless=new")
```

2. **Also** Add a trailing slash to the folder path:
```py

prefs = {'download.default_directory': '.\\x\\x\\'}
```

This now works:

```py
chrome_options = Options()

# For windows:
prefs = {'download.default_directory': '.\\x\\x\\'}

chrome_options.add_argument("--headless=new")
chrome_options.add_experimental_option('prefs', prefs)
driver = webdriver.Chrome(options=chrome_options)
```

It's strange how it worked fine without the trailing slash previously. Thanks to [this ](https://stackoverflow.com/questions/18026391/selenium-webdriver-in-python-files-download-directory-change-in-chrome-prefere) older post

**Comment by xinmans** [comment]
same issue,  when rebuild the docker, the file download to /app folder what it's wrong folder.


    prefs = {'savefile.default_directory': torrents_path}
    chrome_options.add_experimental_option('prefs', prefs)


root@36c8b6aaa2db:/app# uname -a
Linux 36c8b6aaa2db 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 GNU/Linux
root@36c8b6aaa2db:/app# cat Dockerfile 
FROM python:3.7

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

# install chromedriver
RUN apt-get install -yqq unzip 
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# set display port to avoid crash
ENV DISPLAY=:99

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

# add cron to delete chromedriver cache data under /tmp
RUN apt-get install -y cron
ADD crontabfile /etc/cron.daily/spider-cron
RUN crontab /etc/cron.daily/spider-cron
RUN chmod 755 /etc/cron.daily/*
RUN touch /var/log/cron.log

CMD service cron start && cd /app && python3 torrents_download.py 
root@36c8b6aaa2db:/app# 

root@36c8b6aaa2db:/app# cat requirements.txt 
qbittorrent-api==2022.8.38
redis==4.3.4
beautifulsoup4==4.10.0
bs4==0.0.1
requests==2.28.1
selenium==4.4.3
fake-useragent==1.1.1
psutil==5.9.0
pyyaml==5.3.1
root@36c8b6aaa2db:/app#

**Comment by Anilkumar-Shrestha** [comment]
After this changes, I am facing an error as in this link [ Bug]: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed](https://github.com/SeleniumHQ/selenium/issues/11741#issuecomment-1461907515)
Have anyone face this issue?

**Comment by stell** [comment]
I can confirm headless=new fixes codeception based download tests using anasess/setup-chromedriver

**Comment by easytester21** [comment]
Hi, setting headless=new solves my problem but this solution borns another problem. Maximizing the window size does not work when I do this. I am using this option --window-size=1920x1080

--headless --> download path not working
--headless=new -> maximizing not working

**Comment by fryefryefrye** [comment]
--headless --> download path not working
--headless=new -> maximizing not working

That is the exactly the same problem I have.

**Comment by JoshSchreuder** [comment]
Resizing window with `headless=new` looks to be a Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=1416398

**Comment by xinmans** [comment]
which version is stable？

**Comment by easytester21** [comment]
Now I have installed the latest Version 111.0.5563.110 Chrome on Linux, the bug is not killed yet.

**Comment by gerardkmiec** [comment]
I have chromedriver 111.0.5563.64 on my ubuntu docker image and same as @easytester21, I can confirm that issue is still present

**Comment by easytester21** [comment]
Now it is fixed by Version 111.0.5563.146. :-)

**Comment by Anilkumar-Shrestha** [comment]
I still having same problem on my ubuntu docker image with chrome version `111.0.5563.146-1` and chromeDriver `111.0.5563.64` . ISSUE:: https://github.com/SeleniumHQ/selenium/issues/11637#issuecomment-1462474437

**Comment by Anilkumar-Shrestha** [comment]
It seems like this has been fixed in [ChromeDriver 112.0.5615.28](https://chromedriver.storage.googleapis.com/index.html?path=112.0.5615.28/)  beta version. Has anybody able to test this?
![image](https://user-images.githubusercontent.com/26526138/228848765-cf3bfd24-f9b8-4181-bc70-5ec0852a9fad.png)

**Comment by easytester21** [comment]
> It seems like this has been fixed in [ChromeDriver 112.0.5615.28](https://chromedriver.storage.googleapis.com/index.html?path=112.0.5615.28/) beta version. Has anybody able to test this? ![image](https://user-images.githubusercontent.com/26526138/228848765-cf3bfd24-f9b8-4181-bc70-5ec0852a9fad.png)

I have tested it, unfortunately does not work!

**Comment by gerardkmiec** [comment]
> It seems like this has been fixed in [ChromeDriver 112.0.5615.28](https://chromedriver.storage.googleapis.com/index.html?path=112.0.5615.28/) beta version. Has anybody able to test this? ![image](https://user-images.githubusercontent.com/26526138/228848765-cf3bfd24-f9b8-4181-bc70-5ec0852a9fad.png)

Yup, still not working on ubuntu

**Comment by Anilkumar-Shrestha** [comment]
With chrome version `113.0.5672.64` , issue with download file is working fine with  `chromeOptions.addArguments("--headless=old")` .

**Comment by titusfortner** [comment]
@Anilkumar-Shrestha there is no `--headless=old`. as of right now, it is either `--headless=new` or `--headless`

**Comment by Anilkumar-Shrestha** [comment]
@titusfortner yes, I mean `--headless` .  `--headless=old` represents the traditional headless as well and which works.  https://developer.chrome.com/articles/new-headless/ 
![image](https://github.com/SeleniumHQ/selenium/assets/26526138/a04e9759-0da0-4ca5-8d8e-e2b2cdd3460f)

**Comment by titusfortner** [comment]
Ah, you're right. I missed that. Thanks for sharing.

**Comment by easytester21** [comment]
I use 112.0.5615.165 (Official Build) (64-bit) and setting 'headless=new'.

It works fine!

**Comment by aleksandr-kotlyar** [comment]
> With chrome version `113.0.5672.64` , issue with download file is working fine with  `chromeOptions.addArguments("--headless=old")` .

@Anilkumar-Shrestha 
On ubuntu? Or what os?

**Comment by easytester21** [comment]
options.addArguments("--headless=old");
is working for me too. ON ubuntu.

**Comment by chik145** [comment]
> I had the exact same issue where the following worked in previous ChromeDriver versions but it stopped working in 110.0.5481.77 on Windows 10:
> 
> ```python
> chrome_options = Options()
> prefs = {'download.default_directory': './x/x'}
> chrome_options.add_argument("--headless")
> chrome_options.add_experimental_option('prefs', prefs)
> driver = webdriver.Chrome(options=chrome_options)
> ```
> 
> I had to make 2 changes:
> 
> 1. Use the new headless argument as suggested by the previous answers:
> 
> ```python
> chrome_options.add_argument("--headless=new")
> ```
> 
> 2. **Also** Add a trailing slash to the folder path:
> 
> ```python
> prefs = {'download.default_directory': '.\\x\\x\\'}
> ```
> 
> This now works:
> 
> ```python
> chrome_options = Options()
> 
> # For windows:
> prefs = {'download.default_directory': '.\\x\\x\\'}
> 
> chrome_options.add_argument("--headless=new")
> chrome_options.add_experimental_option('prefs', prefs)
> driver = webdriver.Chrome(options=chrome_options)
> ```
> 
> It's strange how it worked fine without the trailing slash previously. Thanks to [this ](https://stackoverflow.com/questions/18026391/selenium-webdriver-in-python-files-download-directory-change-in-chrome-prefere) older post

how to fix file download issue if chrome is running in normal mode (non headless) ??

**Comment by chik145** [comment]
Hi All, 
can anyone help me to resolve this file download issue ?
using Chome 116 with selenium 4.11

automation in chrome is running in non headless mode

**Comment by titusfortner** [comment]
Update selenium version.

**Comment by chik145** [comment]
> Update selenium version.

Thanks, I have tried with latest 4.14, still same issue

**Comment by chik145** [comment]
@titusfortner 
Some Help

**Comment by titusfortner** [comment]
Replying to an issue that was closed 5 months ago is not the best way to get help.
There are better places to get answers to questions like yours.
