### ISSUE TITLE
Chrome 46 causes WebDriverException

### ISSUE THREAD

**Issue by Feasoron** [SeleniumHQ/selenium#1163]
This morning, we started having all of our automated builds fail with an exception 

     The HTTP request to the remote WebDriver server for URL http://localhost:<Some Port>/session timed out after 60 seconds.

At first, I was unable to reproduce locally. Then I noticed our server was running Chrome 46 and I was running 45. I restarted my chrome to upgrade to 46, and now local tests fail as well. There seems to be an incompatibility between the chromedriver and Chrome 46

**Comment by lukeis** [comment]
for chromedriver issues, please log bugs with the chromedriver project:
https://code.google.com/p/chromedriver/issues/list

Also make sure you're using the latest chromedriver 2.20:
http://chromedriver.storage.googleapis.com/index.html?path=2.20/
