### ISSUE TITLE
[🚀 Feature]: Offline Mode in Selenium Manager

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11639]
### Feature and motivation

This would address issues like #11636 as well as some of the concerns people have raised around changes in perception of security considerations.

I think this should be managed in Rust instead of in each binding and the grid, since there is more functionality the Manager should be doing than just downloads. So that means it needs to be an environment variable. 

### Usage example

`ENV["SELENIUM_MANAGER_DOWNLOADS_DISABLED"] = true`

**Comment by bonigarcia** [comment]
I made some comments in the original feature request (#11636).

Regarding the proposed environment variable proposed in this issue (`SELENIUM_MANAGER_DOWNLOADS_DISABLED`), sure, it can be implemented on the Rust side. But do you mean disable all downloads but keep using the cache?

To make it more compliant with the current implementation, maybe we can add a Selenium Manager flag called `--disable-downloads` to carry out that function. The use of envs is aligned with the proposal on #11690. In that case, the naming convention I proposed for that would convert the `--disable-downloads` flag to `SE_DISABLE_DOWNLOADS`.

**Comment by diemol** [comment]
The original reason/request (#11636) was made because we changed the original Grid behavior. We were downloading drivers and making them available by default. The original behavior was to detect the available drivers and build the stereotypes from there.

I made a fix in this commit https://github.com/SeleniumHQ/selenium/commit/6cb3e2f83fcaf5487c7fdcb73a370ca557b19179

Aside of the Grid use case, no one has asked for this feature. So I believe we do not need this right now.

**Comment by titusfortner** [comment]
Hmm, yeah, I guess for bindings we just tell people to specify the location of the driver if you don't want to toggle selenium manager.

**Comment by titusfortner** [comment]
yeah, I'm going to close this as I think what Diego has done is good enough, can create a new issue if someone wants more.

**Comment by titusfortner** [comment]
I'm reopening this one. If we are going to move functionality for checking whether the driver is on PATH from the bindings to SM, we need users to be able to explicitly tell SM to accept what is on the machine without downloading. I think ENV is the right way to do this.

**Comment by diemol** [comment]
> I made some comments in the original feature request (#11636).
> 
> Regarding the proposed environment variable proposed in this issue (`SELENIUM_MANAGER_DOWNLOADS_DISABLED`), sure, it can be implemented on the Rust side. But do you mean disable all downloads but keep using the cache?
> 
> To make it more compliant with the current implementation, maybe we can add a Selenium Manager flag called `--disable-downloads` to carry out that function. The use of envs is aligned with the proposal on #11690. In that case, the naming convention I proposed for that would convert the `--disable-downloads` flag to `SE_DISABLE_DOWNLOADS`.

Now after learning more about the usage, I think what Boni proposed initially is what we need to implement.

**Comment by titusfortner** [comment]
After further discussion, it was decided that the feature should be considered an "offline mode" which means no network calls of any kind, not just downloads. 

Selenium Manager can look for drivers on PATH or in cache, and log warnings if things don't look correct, but do no remediations

**Comment by titusfortner** [comment]
Done!
