### ISSUE TITLE
[🚀 Feature][cdp][python]: Use devtools script pinning mechanism by default

### ISSUE THREAD

**Issue by brodev3** [SeleniumHQ/selenium#11644]
### Feature and motivation

hello, I am delighted with your work, thank you so much for the opportunities provided with your library, please tell me, are you planning to add  function  that allows you to pin a CDP script to a browser window to the Selenium version on python?
Once again I would like to thank you for your work

### Usage example

Sometimes it is necessary to switch the browser control to manual mode

**Comment by titusfortner** [comment]
We are tracking this in a separate document now.
