### ISSUE TITLE
[🚀 Feature]: Selenium Manager log additional information at FINE level

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11642]
### Feature and motivation

Currently we're only logging warnings, we also want to understand what it is doing when it is "working properly"

Ruby & Python are doing this currently.

### Usage example

n/a

**Comment by diemol** [comment]
Can you share the link of the code to see how Python/Ruby are doing it?

**Comment by titusfortner** [comment]
We probably want to add:
* "Unable to locate Drivers on System, Using Selenium Manager"
* "Executing command line: <command>"
* "Driver located at: <path>"

There will be more things to log upcoming :-D 

Heck, looking at how much Java logs, maybe we even want to turn on `--debug` and put all the info into `FINER` after all. 🤷‍♂️
