### ISSUE TITLE
[🚀 Feature]: Ruby support for older CDP versions

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11651]
### Feature and motivation

Instead of supporting a fall-back option for older CDP versions like other languages, Ruby implements new version support with a separate gem. The idea is that we would be able to keep up with adding CDP support even if we can't keep up with doing a full Selenium release. Currently we're struggling to do even that. So we should allow for users to use the latest available devtools version support (e.g. devtools for v109 with Chrome v110, etc)

### Usage example

n/a

**Comment by arielj** [comment]
hey @titusfortner I'm really interested into having this feature, do you have any tip of where I could start looking on the code? I'd like to try if I can get a PR. I'm not asking for a full explanation but any tip is welcomed

**Comment by titusfortner** [comment]
Hey, yes, that'd be great. I'm not actually even sure what exception/stack trace you get when it doesn't work, but my guess is that we want to rescue the exception and decrement and retry, and that it probably happens here - https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/devtools.rb
