### ISSUE TITLE
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebDriver cannot be cast to org.openqa.selenium.devtools.HasDevTools[🐛 Bug]: 

### ISSUE THREAD

**Issue by bachhavdipak** [SeleniumHQ/selenium#11654]
### What happened?

Getting issue while executing test on experitest.

### How can we reproduce the issue?

```shell
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("accessKey", "");
        WebDriver driver = new RemoteWebDriver(new URL("/wd/hub"), capabilities);
        driver = new Augmenter().augment(driver);

        DevTools devTools = ((HasDevTools) driver).getDevTools();
        devTools.createSession();
        devTools.send(Emulation.setGeolocationOverride(Optional.of(52.5043),
                Optional.of(13.4501),
                Optional.of(1)));

        driver.get("https://my-location.org/");
        driver.quit();
```
```


### Relevant log output

```shell
Exception in thread "main" java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebDriver cannot be cast to org.openqa.selenium.devtools.HasDevTools
```

### Operating System

Windows 10

### Selenium version

JDK 8

### What are the browser(s) and version(s) where you see this issue?

Chrome 

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver-4.7.1

### Are you using Selenium Grid?

Experitest

**Comment by titusfortner** [comment]
The `Augmenter` uses the provided capabilities to know which classes to augment with, and you are providing an empty capabilities. Use `ChromeOptions` instead of `DesiredCapabilities`.
