### ISSUE TITLE
[🐛 Bug]: Can't take a screenshot of an element when the style is changed

### ISSUE THREAD

**Issue by PashaM999** [SeleniumHQ/selenium#11655]
### What happened?

I am using headless chromedriver to make screenshots of the elements on a page, but first I want to make changes to the document's style like so:
```
driver.execute_script('document.body.style.zoom=1.5')
```
After running this `driver.save_screenshot` works fine, but if I do `some_element.screenshot('output.png')`, the image contains some other part of the screen. I am positive that the issue is that selenium does not take into account zoom, but how to get around that? Maybe for now I could somehow scale the location of the element by hand?

### How can we reproduce the issue?

```shell
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

options = Options()
options.headless = True

CHROMEDRIVER_PATH = '/usr/local/bin/chromedriver'

WINDOW_SIZE = "640, 1280"
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--window-size=%s" % WINDOW_SIZE)
chrome_options.add_argument('--no-sandbox')
chrome_options.binary_location = "/usr/bin/google-chrome"

options.add_argument("user-data-dir=/tmp/tarun")
global driver
driver = webdriver.Chrome(service=Service(CHROMEDRIVER_PATH),
                        options=chrome_options
                        )

driver.get('https://stackoverflow.com')
driver.execute_script('document.body.style.zoom=1.5')
driver.find_element(By.CLASS_NAME, 's-topbar--logo').screenshot('out.png')
```
```


### Relevant log output

```shell
No logs, I guess, there is no error, just the image is not what I expect it to be
```

### Operating System

Debian GNU/Linux 10 (buster)

### Selenium version

python 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 110.0.5481.96

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77

**Comment by diemol** [comment]
I do not follow, you mention a style change but the script provided does not do that. Also, does it work if you do not set the zoom? What image do you get and which one did you expect?

**Comment by titusfortner** [comment]
What happens if you reload the page after changing the style?

Regardless, there is nothing for Selenium to do. The behavior of what gets returned from that call is managed by chromedriver.

**Comment by PashaM999** [comment]
@diemol Sorry if I caused confusion. Yes, it works great without the zoom, but when I enable it, instead of the whole image I get only a part of it or a random part of the screen of roughly the same shape. It is as if something saves the location of the element and when I zoom it, it tries to capture the same square, but it is, of course, moved at this point. Hope that's clear enough.
