### ISSUE TITLE
[🚀 Feature]: Add Download Support to Bindings

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11657]
### Status

|                      | Java   | Python | Ruby   | .NET   | JavaScript |
|----------------------|--------|--------|--------|--------|------------|
| PR                   | #12979 | #13023 | #12037 | #12981 | #13102          |
| Capability Method    | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:          |
| Capability Protected | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:          |
| Name List            | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:          |
| Directory Download   | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | ?          |
| Create Directory   | :white_check_mark:      | :white_check_mark:      |  :white_check_mark:      | :white_check_mark:      | :white_check_mark:          |
| Delete               | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:      | :white_check_mark:          |

### Feature and motivation

For the bindings we want to require the user to both enable downloads since we don't want that to be default behavior, and then have the ability to get the list of available files (#11458), and to download a specific file (#11466).

This is going to rely on Grid implementation in #11656 

My Java syntax proposal is below, feedback appreciated.

### Usage example

```
chromeOptions.enableDownloads(true);
driver = new RemoteWebDriver(url, chromeOptions);

driver.get(siteUrl);
driver.findElement(By.id("download-this")).click();
List<Map<String, String>> downloadedFiles = ((HasDownloads) driver).getDownloads();
String fileToDownload = downloadedFiles.get(0).get("name");
((HasDownloads) driver).getDownload(fileToDownload, outputStream);
```

**Comment by titusfortner** [comment]
@harsha509 can you help me with the PR I made and tell me if it should work?

**Comment by harsha509** [comment]
Closing as completed!
