### ISSUE TITLE
[🐛 Bug]: ChromeDriver process left running after driver.quit in 4.8.0 (Ruby)

### ISSUE THREAD

**Issue by mjflint** [SeleniumHQ/selenium#11652]
### What happened?

After starting a Chrome browser using the 4.8.0 Ruby driver, if driver.quit is performed then the browser processes are killed but the ChromeDriver process continues to run until the parent process exits. With previous driver versions the ChromeDriver process is killed immediately after driver.quit.

I have only tested this with the Ruby bindings, and could not see anything in the change log to indicate it is intended behaviour.

### How can we reproduce the issue?

```shell
# In IRB session:
gem 'selenium-webdriver', '=4.8.0'
require 'selenium-webdriver'
options = Selenium::WebDriver::Chrome::Options.new
options.add_argument('--headless')
driver = Selenium::WebDriver.for :chrome, options: options
driver.quit

# In shell (with IRB session still open)
pgrep -a chromedriver
# 86693 /usr/local/bin/chromedriver --port=9515

# If done with earlier selenium-webdriver versions e.g. 4.7.1, the chromedriver process no longer runs
```

### Relevant log output

```shell
irb(main):001:0> gem 'selenium-webdriver', '=4.8.0'
=> true
irb(main):002:0> require 'selenium-webdriver'
=> true
irb(main):003:0> options = Selenium::WebDriver::Chrome::Options.new
=>
#<Selenium::WebDriver::Chrome::Options:0x00007f46afe1c7b8
...
irb(main):004:0> options.add_argument('--headless')
=> ["--headless"]
irb(main):005:0> driver = Selenium::WebDriver.for :chrome, options: options
=> #<Selenium::WebDriver::Chrome::Driver:0x4add1a765e358198 browser=:chrome>
irb(main):006:0> driver.quit
=> nil
irb(main):007:0> `pgrep -a chromedriver`
=> "86693 /usr/local/bin/chromedriver --port=9515\n"
```

### Operating System

Oracle Linux Server 7.9

### Selenium version

Ruby 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 107 and 110 (upgraded to see if Chrome version made a difference, it didn't)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 107.0.5304.62 and 110.0.5481.77

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Ooh, yes. The subclass is setting the manager value before the superclass sets it to null. 

This should fix: https://github.com/SeleniumHQ/selenium/commit/5d8b8a9a0532dc3598cfcd18a2671647b6df41b4

Thanks!
