### ISSUE TITLE
[🚀 Feature]: Grid properly matches enable download support

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11658]
### Feature and motivation

This is an extension of #11656 but I wanted to separate it out.

We know we want the Grid to set whether it allows downloads. Right now we're doing a flag where we have users specify the directory. If we are creating that directory for users, that won't be necessary. We can either keep the flag and change it to `--enable-downloads` or we can do whatever we do now by requiring a match of `se:enableDownloads` capability. I kind of like the latter approach because if a user requests a session with downloads enabled, but the Hub doesn't find a node with it turned on, it would be nice to get a clear error message that this is the case.

### Usage example

backend implementation

**Comment by diemol** [comment]
Closed via #11702
