### ISSUE TITLE
sendKeys() fails to fill <div> element (WebDriver 2.48.2, Java, Firefox 40.0.3 )

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [SeleniumHQ/selenium#1165]
After switch to webdriver 2.48.2 **sendKeys()** method does not work for WebElement:
```
<div class="editor__area" contenteditable="true" tabindex="5" style="height: 250px;"></div>
```
```
@FindBy (css = ".editor__area")  public WebElement bodyEditor; 

public Message setBodyText(String string){
		bodyEditor.sendKeys(string);		
		return this;
}

```
Method *setBodyText(" some string")*  fails to send any symbol to editor field.
While exactly the same code works just fine in case of webdriver 2.47.1
<br>
All-in-one details on snapshot:
![page-firebug code](https://cloud.githubusercontent.com/assets/13039345/10540267/31ef6870-740f-11e5-9e9a-f0bacdd82242.jpg)

**Comment by admizh** [comment]
pls attach stack trace. Which encoding text you sent to type? Do work before selenium update?

**Comment by lukeis** [comment]
can reproduce this using 2.48 w/ FF 41.  It works with 2.47.1 w/ FF41

```
>>> d = w.Remote("http://localhost:4444/wd/hub", {'browserName':'firefox'})
>>> d.execute_script("document.body.innerHTML = arguments[0]", '<div class="editor__area" contenteditable="true" tabindex="5" style="height: 250px;"></div>')
>>> d.find_element_by_tag_name("div").send_keys("testing content editable")
```

**Comment by lukeis** [comment]
this will be fixed in the next release and is due to the content editable element having nothing inside of it initially... as a current workaround you can set some initial contents via javascript, then clear it and then type... (or just set the contents via javascript ;) )

```
>>> d.execute_script("document.body.innerHTML = arguments[0]", '<div class="editor__area" contenteditable="true" tabindex="5" style="height: 250px;"></div>')
>>> e = d.find_element_by_tag_name("div")
>>> d.execute_script("arguments[0].innerHTML='&nbsp;'", e)
>>> e.clear()
>>> e.send_keys('testing content editable')
```
