### ISSUE TITLE
[🚀 Feature]:  Capturing Full Page Screenshot for any webpage

### ISSUE THREAD

**Issue by Gauravrc25** [SeleniumHQ/selenium#11660]
### Feature and motivation

Add API call that will take whole page screenshot with popup and from header to footer.

### Usage example

There is already one API Present for capturing full page screenshot for gecko driver **_get_full_page_screenshot_as_file_**.

**Comment by titusfortner** [comment]
This is a special feature implemented by Mozilla. An equivalent feature would need to be added to chromedriver by Google, so you'll need to request it of them.
