### ISSUE TITLE
[🚀 Feature]: Update GitPod setup to be simpler

### ISSUE THREAD

**Issue by nadvolod** [SeleniumHQ/selenium#11669]
### Feature and motivation

I found a simpler way to be able to set up GitPod for Selenium. This works for me:
https://gist.github.com/nadvolod/73997a12e646e5c00bafb1b9c12fd7b1

I'm not 100% sure what else you all need for this, so I didn't create a PR. However, this works for just running Chrome tests with a VNC Viewer set up.

### Usage example

https://gist.github.com/nadvolod/73997a12e646e5c00bafb1b9c12fd7b1

**Comment by diemol** [comment]
I removed the browser driver code we had for GitPod since it is not needed anymore thanks to Selenium Manager. However, the rest is still needed because that GitPod setup is made to enable contributors develop code for Selenium, not just run Selenium tests.
