### ISSUE TITLE
[🐛 Bug]: Selenium manager is not working when the browser version is less

### ISSUE THREAD

**Issue by Randy1510** [SeleniumHQ/selenium#11664]
### What happened?

I have a chrome version: 105.0.5195.127. When I start executing the testcases, it is not executing. It is saying that System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 105.0.5195.127 with binary path.

Note: I don't have any chromedriver or webdrivermanager installed in the application

### How can we reproduce the issue?

```shell
Downgrade the version of chrome and try to execute.
```

### Relevant log output

```shell
Message: 
Assembly Initialization method TRMSolutionUI_MSTestAssemblyHooks.AssemblyInitialize threw exception. System.InvalidOperationException: System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 109
Current browser version is 105.0.5195.127 with binary path C:\x\chrome.exe (SessionNotCreated). Aborting test execution.

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeOptions options)
DriverFactory.GetWebDriver() line 91
TestSetup.BeforeTestRun() line 29
TestSetup.Before_TestRun() line 26
lambda_method(Closure , IContextManager )
TestExecutionEngine.FireEvents(HookType hookType) line 351
TestExecutionEngine.OnTestRunStart() line 117
TestRunner.OnTestRunStart() line 29
TestRunnerManager.FireTestRunStart() line 116
TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder) line 230
TRMSolutionUI_MSTestAssemblyHooks.AssemblyInitialize(TestContext testContext) line 22
```

### Operating System

Windows 10

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 105.0.5195.127

### What are the browser driver(s) and version(s) where you see this issue?

109

**Comment by diemol** [comment]
@bonigarcia this should work, right?

**Comment by bonigarcia** [comment]
Selenium Manager has the ability to detect the browser version and, using that number, download the correct driver version. Therefore, this issue is not likely caused by Selenium Manager. @Randy1510 Maybe you have an incorrect version of chromedriver (109, it seems) in your PATH. In that case, Selenium Manager is not resolving the driver.

**Comment by Randy1510** [comment]
Hi Boni/Diemol,
Thank you. It worked. As you guys mentioned somewhere in the temp, 109 version was there,

Thank you for the quick response. Please close the bug
