### ISSUE TITLE
[🐛 Bug]: Opening new tab and navigating to url causes the browser to select the url in search line.

### ISSUE THREAD

**Issue by danylo-chekina** [SeleniumHQ/selenium#11665]
### What happened?

After selenium upgrade to version 4.8 we noticed that opening new tab and opening new window have different behaviour.
When we open new tab using `driver.switchTo().newWindow(WindowType.TAB);` and then navigate to specific url using `driver.get("https://google.com");` we see that the url has been selected by the browser...(screen below) With `driver.switchTo().newWindow(WindowType.TAB);` it's never happens.

![image](https://user-images.githubusercontent.com/79544184/219437093-dae7efb9-1d96-4f54-9459-ab6d5374c279.png)

### How can we reproduce the issue?

```shell
driver.switchTo().newWindow(WindowType.TAB);
driver.get("https://google.com");
```

### Relevant log output

```shell
no logs
```

### Operating System

System info: os.name: 'Linux', os.arch: 'aarch64', os.version: '5.10.104-linuxkit', java.version: '11.0.18'

### Selenium version

Build info: version: '4.8.0', revision: '267030adea', https://hub.docker.com/layers/selenium/standalone-chrome/4.8/images/sha256-df7472a13463ff5e5e444bb485460ba1082c779469cbaa1f86b54997335761eb?context=explore

### What are the browser(s) and version(s) where you see this issue?

Chrome, browserVersion: 110.0.5481.77

### What are the browser driver(s) and version(s) where you see this issue?

chromedriverVersion: 110.0.5481.77

**Comment by titusfortner** [comment]
This is likely going to be a difference in the browser/driver version. Selenium doesn't send anything different to the driver. You'll need to raise it as an issue with Google.
