### ISSUE TITLE
[🚀 Feature]: Notorize Selenium Manager binary for macOS

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11673]
### Feature and motivation

The execution of the selenium-manager binary can raise the following error:

![image](https://user-images.githubusercontent.com/5413013/220134668-6d6d8e7c-1bd1-4ff1-9170-ac2c37be6d5f.png)

A possible solution for this potential problem is to notarize the selenium-manager binary for macOS before each release. More info on https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

### Usage example

n/a

**Comment by titusfortner** [comment]
For future reference, this error does not happen when obtaining selenium manager via the bindings packages, only when downloading this file with a browser from an online source.

**Comment by diemol** [comment]
Also, it works fine if it is downloaded through the GitHub API. Documented in the release process https://github.com/SeleniumHQ/selenium/wiki/Releasing-Selenium#general

**Comment by bonigarcia** [comment]
If I'm not wrong, this feature is no longer required. I'm closing it. Please re-open if the issue persists.

**Comment by titusfortner** [comment]
@bonigarcia how hard would it be to get it notarized?

Yes, we can get around it by authenticating through github API and pulling it down programmatically, but mac users can't just download it and use it.

**Comment by bonigarcia** [comment]
The complete procedure is explained in the link contained in the description. It does seem particularly simple to me. In the case of doing it, I suppose we would prefer to do the notarization in an automated or semi-automated manner. According to the previous doc, there are some command-line tools called  `notarytool` and `stapler` (included with Xcode) to do it.

**Comment by titusfortner** [comment]
Hmm, I guess it's only going to be an issue if/when we release the binary independently.

**Comment by bonigarcia** [comment]
Indeed.
