### ISSUE TITLE
[🚀 Feature]: Selenium Manager uses proper geckodriver version

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11671]
### Feature and motivation

Currently, Selenium Manager uses the latest version of geckodriver. This is because geckodriver does not publish any metadata about versioning. This feature has been requested some time ago in the [geckodriver bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1794550) (also in the [geckodriver issue tracker](https://github.com/mozilla/geckodriver/issues/2049)). When this information is available, the Selenium Manager logic should read this info to use the most suitable geckodriver version.

### Usage example

The use of Selenium Manager will not change:

```
selenium-manager --browser firefox
```

**Comment by titusfortner** [comment]
Can we maintain our own list based on https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html until this feature is supported by Firefox?

**Comment by bonigarcia** [comment]
> Can we maintain our own list based on https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html until this feature is supported by Firefox?

Yes, we can. 

I asked about this in the Firefox issue tracker more than a year ago. Then, I asked about its status 3 months ago, but there has been no response:

https://bugzilla.mozilla.org/show_bug.cgi?id=1794550

So yes, I think the better now is to maintain our own metadata based on that page and use it from Selenium Manager. I'll create a PR about that soon.

**Comment by bonigarcia** [comment]
Completed via #13133.
