### ISSUE TITLE
[🚀 Feature]: Selenium Manager downloads latest version of Chrome browser

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11676]
### Status
* Rust - #12353 
* Ruby - #12398 
* Python - #12404 
* .NET - #12405 
* JS - #12411 
* Java - #12424

### Feature and motivation

The next major feature to be implemented in Selenium Manager is the automated management (download, cache) of the principal browsers nowadays: Chrome, Firefox, and Edge.

This issue gets track of the implementation of this feature for downloading the latest version of **Chrome** on the Rust side.

### Usage example

```
selenium-manager --browser chrome --resolve-browser
```

**Comment by bonigarcia** [comment]
Maybe the flag ` --resolve-browser` (specified in the issue description) is not required. When Selenium Manager is called as follows:

```
selenium-manager --browser chrome
```

If the browser (Chrome, in this case) is locally installed, it is detected (and ultimately, used by Selenium). When it is not detected, it is downloaded (using [CfT endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints) for discovery).

**Comment by titusfortner** [comment]
I'm updating this issue to track all the bindings.

**Comment by diemol** [comment]
All PRs got merged!
