### ISSUE TITLE
[🚀 Feature]: Selenium Manager downloads a fixed version of browsers (bindings)

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11679]
### Feature and motivation

The next major feature to be implemented in Selenium Manager is the automated management (download, cache) of the principal browsers nowadays: Chrome, Firefox, and Edge.

This issue gets track of the implementation of this feature for downloading the a fixed version of these browsers on the bindings side.

When the browser is not available, instead of raising an exception, the bindings should call Selenium Manager to manage the browsers (Chrome, Edge, Firefox).

### Usage example

```
selenium-manager --browser chrome --browser-version 101 --resolve-browser
selenium-manager --browser firefox --browser-version 100 --resolve-browser
selenium-manager --browser edge --browser-version 99 --resolve-browser
```

**Comment by diemol** [comment]
This is also done in all bindings.

**Comment by titusfortner** [comment]
This issue is for all the browsers not just Chrome. Are we /can we tracking the others elsewhere?

**Comment by diemol** [comment]
All bindings can pass a browser version already, do we need anything else?

**Comment by titusfortner** [comment]
Oh, this is just the bindings half of it. You're right.
