### ISSUE TITLE
[🚀 Feature]: Clear the metadata in Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11675]
### Feature and motivation

Create a new flag in Selenium Manager (`--clear-metadata`) to clear the metadata (file `~/.cache/selenium/selenium-manager.json`).

### Usage example

```
selenium-manager --clear-metadata
```

**Comment by iampopovich** [comment]
@bonigarcia I'll take it in a few days

**Comment by iampopovich** [comment]
@bonigarcia shouild the flag erase file's content or delete file from folder ?

**Comment by bonigarcia** [comment]
@iampopovich Deleting the metadata file is enough.

**Comment by titusfortner** [comment]
Just to have it documented, What are use cases for clearing Metadata?

**Comment by bonigarcia** [comment]
Metadata contains the time drivers resolutions (e.g., chromedriver 110.0.5481.77 is the correct version for Chrome 110) are considered valid. This value depends on the time in which it was found (by requesting the online metadata of each driver) plus the TTL. Clearing the metadata forces requesting the online metadata again (e.g., even when a previous driver resolution happened recently) but preserves the driver cache.

**Comment by titusfortner** [comment]
So, first run determines latest driver, records it in metadata with a ttl and downloads it to drive.
Subsequent runs, and if it is < ttl, so long as the driver matches, no need to check online if it is the latest.
If `--clear-metadata`, it forces the manager to check again that the downloaded driver is most recent?

Like, it's pretty much just resetting the TTLs?

**Comment by diemol** [comment]
Closed via #11818

**Comment by bonigarcia** [comment]
> Like, it's pretty much just resetting the TTLs?

Similar, but not exactly the same. Using `--browser-ttl 0` ensures that next calls to Selenium Manager checks the driver version using the online info. On the other hand, `--clear-metadata` ensures that the driver version is discovered even though previous recent calls to Selenium Manager (recent means within the TTL, 1 day by default) would have been done.
