### ISSUE TITLE
[🚀 Feature]: Selenium Manager uses proper IEDriverSever version 

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11672]
### Feature and motivation

Currently, Selenium Manager uses the latest version of IEDriverServer when using Internet Explorer. Besides, the internal Rust logic assumes that the latest [release of Selenium](https://github.com/SeleniumHQ/selenium/releases/latest) contains a version of IEDriverServer. This can pose a potential problem if a Selenium release does not ship the IEDriverServer binaries. To avoid this issue, there is an open issue in Selenium (#11280) to publish this info. When this information is available, the Selenium Manager logic should read it to use the most suitable IEDriverServer version.

### Usage example

The use of Selenium Manager will be the same to resolve IEDriverServer:

```
selenium-manager --browser ie
```

**Comment by titusfortner** [comment]
What is SM doing right now?
If we did Selenium release without an IE Driver release what would happen?

Selenium Manager should always get the "latest" regardless of what release it is part of. I think we have access to that from the api releases page without needing to create our own index.

**Comment by bonigarcia** [comment]
Now, the internal Rust logic assumes that the latest [release of Selenium](https://github.com/SeleniumHQ/selenium/releases/latest) contains a version of IEDriverServer. If the latest Selenium release does not contain a IEDriverServer, Selenium Manager will fail. I know this is not ideal, and to improve it, we need to take some action.

Reading the GitHub API to discover the latest IEDriverServer is also an alternative. But to implement this efficiently, we need to create a mirror of the GH API responses to avoid a potential HTTP 403 error when requesting the GH API. This was an old know-issue in WebDriverManager, and it can be solved using an automated job to mirror the GitHub releases (requesting raw GitHub instead). The other solution is to publish the IEDriverServer version, as proposed in #11280.

**Comment by titusfortner** [comment]
Ah, that makes sense.

Can't we just parse this, though to get what we want? https://api.github.com/repos/seleniumhq/selenium/releases

**Comment by bonigarcia** [comment]
Yes, we can parse that. But doing it directly, the error HTTP 403 is likely to happen. I know very well from WebDriverManager. There, I created an scheduled job to mirror these releases (see [job](https://github.com/bonigarcia/webdrivermanager/blob/master/.github/workflows/mirror.yml)), and WebDriverManager queries the mirror (in [raw.githubusercontent](https://raw.githubusercontent.com/bonigarcia/webdrivermanager/master/docs/mirror/selenium)). We can do the same in Selenium Manager, or alternatively, publish the versioning info, as proposed in #11280.

**Comment by diemol** [comment]
I think those two options are basically the same? In terms of what we need. @bonigarcia I added #11280 to the Selenium Manager project. Why don't you copy the same logic you implemented in the WDM repository and add it to the Selenium repository?

**Comment by bonigarcia** [comment]
@diemol. Yes, both alternatives (reading a metadata file or parsing the GH API responses) are equivalent. I opened this feature request proposing to use the metadata since issue #11280 was already proposed. But if #11280 is not done, I can reuse the scheduled job I did in WebDriverManager here in Selenium to get the latest IEDriverServer from the mirrored GH API, no problem.
