### ISSUE TITLE
[🚀 Feature]: Change default folder for Selenium Manager cache

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11688]
### Feature and motivation

Currently, the local folder used for cache in Selenium Manager is `~/.cache/selenium` by default. To change this path, a new flag like `--cache-path <CACHE_PATH>` is required.

### Usage example

```
selenium-manger --browser chrome --cache-path /my/custom/cache
```

**Comment by iampopovich** [comment]
Am i right the custom cache path must be applied for the specified browser ?
The way that Chrome has cache_path1 and FF has cache_path2 is legal right?

**Comment by bonigarcia** [comment]
Completed with #12514.
