### ISSUE TITLE
[🚀 Feature]: Change driver repository URL in Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11687]
### Feature and motivation

Some companies would prefer to mirror the drivers' repositories (e.g., chromedriver, geckodriver) instead of using the official site. In that case, Selenium Manager should be able to specify an alternative repository URL, for instance, using a new flag called `--driver-mirror <MIRROR_URL>`.

### Usage example

```
selenium --browser chrome --driver-mirror http://my-chromedriver-mirror.net
```

**Comment by diemol** [comment]
Wasn't this implemented in a recent PR?

**Comment by bonigarcia** [comment]
Not yet. The last [PR](12514) was about changing `--cache-path`.

**Comment by andham** [comment]
#12388 mentions a planned feature "SE_DRIVER_MIRROR". Any progress on that?
For an air-gapped environment this would be crucial to get Selenium Manager to work.

**Comment by diemol** [comment]
You can track priorities for Selenium Manager here https://github.com/orgs/SeleniumHQ/projects/5/views/1

**Comment by bonigarcia** [comment]
Completed via #12914.
