### ISSUE TITLE
[🚀 Feature]: Configuration file for Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11689]
### Feature and motivation

To centralize all the Selenium Manager configuration values, maybe creating a global configuration file.

TOML can be a simple format for the configuration file. Selenium Manager will look for this file at `~/.cache/selenium/selenium-manager-config.toml`. An example of the content of this file is as follows:

```
browser = "chrome"
driver = "chromedriver"
browser-version = "106"
driver-version = "106.0.5249.61"

browser-path = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
os = "macos"
arch = "x64"
proxy = "myproxy:8080"
browser-ttl = 0
driver-ttl = 86400
driver-mirror = "http://my-chromedriver-mirror.net"
cache-path = "/my/custom/cache"

debug = false
```

The default location of this file could be change using a new flag, e.g. `--config-file <FILE_PATH>`.

### Usage example

```
selenium-manager --browser chrome --config-file /my/custom/sm-config.toml
```

**Comment by titusfortner** [comment]
I don't see a good way for the bindings to use this feature. 

Maybe if we cache the manager in a specific directory, the manager can look in that directory for the config file and we can direct users to put it there?

**Comment by bonigarcia** [comment]
The way I see it, the config file is a way to specify a common setup for all the calls to Selenium Manager. It is a way to avoid using the same configuration again and again per test (e.g., the proxy is set up once and reused in every single call to Selenium Manager). But of course, it is not mandatory.

**Comment by titusfortner** [comment]
Right now we're only pulling things out of the Options class, so there's no way for a user to pass in a location of a config file. Maybe it makes sense to start adding custom capabilities to the Options classes to support Selenium Manager.

**Comment by diemol** [comment]
I do not think this is needed because Selenium Manager needs to be transparent to the bindings user, which is the main use case. This might be useful for Grid users, but again, that is a smaller segment of people and still not sure how many would actually use it. 

I will close this as I believe we do not want this, and if we see use cases for it, we can definitely reopen.

**Comment by titusfortner** [comment]
Actually, I do see potential value here. I suspect that people might want more control than what we're going to give them when we make Selenium Manager opt-out, and either we implement special `se:xxx` Options for Options classes or we support putting a config file on the system somewhere. I guess we can re-open the issue when people ask for it. 😄
