### ISSUE TITLE
[🐛 Bug]: Loading extension with options clears chrome cookies

### ISSUE THREAD

**Issue by oldwizard1010** [SeleniumHQ/selenium#11696]
### What happened?

when loading extension with "options.add_extension" and "options.add_argument --load-extension" to existing profile folder with chromedriver, it clears cookies
(didn't test with firefox)

### How can we reproduce the issue?

```shell
create driver instance with chrome options, use existing profile folder (Log in to some site for example) add load some extensions with options
```

### Relevant log output

```shell
none
```

### Operating System

Arch

### Selenium version

Python 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chromium 109

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 109.0.5414.25

**Comment by diemol** [comment]
Closing this as we did not get more information.
