### ISSUE TITLE
[🐛 Bug]: Selenium Manager flag to not download unwanted drivers

### ISSUE THREAD

**Issue by david-pulkowski** [SeleniumHQ/selenium#11697]
### What happened?

Selenium version: 4.8.1

We use a hub & node setup:
We set our selenium nodes to detect their own browsers & we supply the driver version to use. 

The problem with the selenium-manager in our use case is: 
In our Windows environment we have IE, Chrome, Firefox, & Edge installed. We do not test for IE (nor want the binary downloaded)
Yet now the Internet explorer driver is downloaded by the manager.

Is there a flag to pass to the selenium node to ignore unwanted selenium-manager downloads?
I can see we can set the --driver-implementation flag; while that only sets the node to not configure the undesired browser & makes it not available (IE in our case), yet the manager still downloads the driver, since the driver was detected.

Our security tool flags this download.

### How can we reproduce the issue?

```shell
Start up a windows node, that has IE installed on the system & make sure not to supply an IE driver. Call your instance something like:


 java -Dwebdriver.chrome.driver=C:/selenium/drivers/chromedriver.exe -jar C:/selenium/drivers/selenium-server.jar --detect-drivers true --driver-implementation "chrome" node
```

Then go to users home directory and look in the .cache folder for the driver:
```
C:\Users\$USER\.cache\selenium\IEDriverServer\win32\4.8.0
```
```


### Relevant log output

```shell
16:34:28.664 INFO [NodeOptions.discoverDrivers] - Discovered 4 driver(s)
```

### Operating System

Windows 10 & Server 2019

### Selenium version

Java 11 with 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Latest versions 

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.8.0

### Are you using Selenium Grid?

4.8.1

**Comment by titusfortner** [comment]
For now you can set `--detect-drivers` to `false` and it won't try to locate them.

Our planned long term solution is to have an environment variable that works for both grid and client to skip downloads — #11639

@diemol was there something else we want to do to address this?

**Comment by diemol** [comment]
I think we need to do something Grid specific because inadvertently we changed the default behavior. Whereas is kind of nice to have drivers downloaded, folks like @david-pulkowski are not expecting that. 

I'll figure out what is the best place to add the flag in Grid to restore the original behavior.

**Comment by diemol** [comment]
New `--selenium-manager` flag, `true` by default. When enabled, the log will look like:

```
23:58:10.293 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
23:58:10.296 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
23:58:10.645 INFO [NodeOptions.getSessionFactories] - Detected 8 available processors
23:58:10.654 INFO [NodeOptions.discoverDrivers] - Driver(s) already present on the host: 2
23:58:11.633 INFO [NodeOptions.discoverDrivers] - Driver(s) available through Selenium Manager: 3
23:58:11.644 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times (Host)
23:58:11.645 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 8 times (SM)
23:58:11.645 INFO [NodeOptions.report] - Adding Safari Technology Preview for {"browserName": "Safari Technology Preview"} 1 times (Host)
23:58:11.646 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 8 times (SM)
23:58:11.646 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 8 times (SM)
23:58:11.669 INFO [Node.<init>] - Binding additional locator mechanisms: relative
```

When disabled, only drivers present on the host machine will be used.

This will be part of the next release in ~2 weeks.

**Comment by david-pulkowski** [comment]
@diemol great work! Thank you 💯

**Comment by titusfortner** [comment]
@diemol should it be false by default for backwards compatibility? For bindings I've been pitching this as an opt-in/fallback solution still. I kind of think we should wait for v1 before we make it opt-out?

**Comment by diemol** [comment]
Makes sense, I will make the change.

**Comment by titusfortner** [comment]
Then we should post about how people should turn it on and try it out. :-D
