### ISSUE TITLE
[🚀 Feature]: Different ways to configure Selenium Manager

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11690]
### Feature and motivation

If the Selenium Manager configuration file is implemented (#11689), there will be two ways to configure Selenium Manager. In addition to those, an additional way to specify some common configuration parameters (e.g., the proxy server configuration) can be using *environment variables*. 

In case of implementing the three ways, a order preference should be defined. For instance, as follows:

1. CLI parameters. The configuration specified as CLI parameters are honored in the first place.
2. Configuration file. As defined in #11689.
3. Environment variables. To name these variables, the CLI parameter names can be converted using each parameter name to uppercase and replacing the dash symbol (`-`) with an underscore (`_`) and prepening `SE_`. For example, `browser-ttl` becomes `SE_BROWSER_TTL`.

### Usage example

n/a

**Comment by diemol** [comment]
Implemented via #11810 
Thank you, @bonigarcia!
