### ISSUE TITLE
[🚀 Feature]: Extract Selenium Manager binary to cache (instead of using a temporal file)

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#11692]
### Feature and motivation

In the Java bindings, the Selenium Manager binary is currently decompressed from the JAR, as used in a temporal file (which is later deleted). But instead, if the bindings use Selenium Manager from a known path, such as `~/.cache/selenium/manager/1.0.0/selenium-manager`, the need to decompress it each time is reduced. Moreover, this approach has two extra benefits. First, users can override that binary with a custom compilation (e.g., by a mac-arm64 in macOS). Second, users can manually invoke Selenium Manager (from the shell, as a CLI tool) when Selenium Manager provides additional features (e.g., create project scaffolding).

### Usage example

n/a

**Comment by titusfortner** [comment]
I think this is a duplicate of #11359 ?
It would help Java the most, but if we do this, would be good to do it in all bindings.

**Comment by bonigarcia** [comment]
Yes, it seems a duplicate of that one. We can close it.
