### ISSUE TITLE
[🚀 Feature]: Enable RemoteWebElement's to upload folders too

### ISSUE THREAD

**Issue by tholewebgods** [SeleniumHQ/selenium#11705]
### Feature and motivation

Uploading files on `type="file"` `input` elements is already possible. The `RemoteWebElement` packages the file, transfers it via the Webdriver protocol, unpacks it remotely so that it's available on the remote machine for upload.

Since `input` elements with `type="file"` [can also select and upload directories][inp-wdir] via fetch/XHR it would be great to have E2E tests cover this aswell. For locally driven browsers this is indeed possible, but not for remotely driven browsers.

[inp-wdir]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory

### Usage example

Single page applications allow uploading of folders besides files. E2E tests should cover these cases too.

```
File folder = new File("testdata/folder");
WebElement element = driver.findElement(By.id("folderupload"));
element.sendKeys(folder.getAbsolutePath());
```

**Comment by titusfortner** [comment]
This behavior is specified in the w3c: https://w3c.github.io/webdriver/#element-send-keys (step 8 in The remote end steps for Element Send Keys). If this functionality is added to w3c, we can support it in Selenium.
