### ISSUE TITLE
[🐛 Bug]: DevTools devTool = ((HasDevTools) driver).getDevTools(); cannot be resolved to a type

### ISSUE THREAD

**Issue by ayushi-nyk** [SeleniumHQ/selenium#11700]
### What happened?

I am trying to capture the network logs on grid hence using below code - 

```java
public static void main(String[] args) {
		WebDriver driver ; 
		ChromeOptions options = new ChromeOptions(); 
		try {			
		driver = new RemoteWebDriver(new URL("http://************/wd/hub"), options);
		driver = new Augmenter().augment(driver);
		    	    
		 **DevTools devTool = ((HasDevTools) driver).getDevTools();**
		 devTool.createSession();

	         devTool.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
			
	       devTool.addListener(Network.requestWillBeSent(), request -> {

	              Request req = request.getRequest();
	              System.out.println("Request URL => " + req.getUrl());
	              System.out.println("Request Method => " + req.getMethod());
	              System.out.println("Request Headers => " + req.getHeaders());
	              System.out.println("------------------------------------------------------");

	        });
			
	driver.get("https://www.Google.com/");
	driver.quit();			
		}		
		catch (Exception e) {	
		}		
		}
```

But I am getting error  -
DevTools devTool = ((HasDevTools) driver).getDevTools(); cannot be resolved to a type

### How can we reproduce the issue?

```shell
Selenium Version used - 4.7.0

Use above code to replicate
```

### Relevant log output

```shell
DevTools devTool = ((HasDevTools) driver).getDevTools(); cannot be resolved to a type
```

### Operating System

mac

### Selenium version

4.7

### What are the browser(s) and version(s) where you see this issue?

chrome -108, 109

### What are the browser driver(s) and version(s) where you see this issue?

using webdrivermanager library

### Are you using Selenium Grid?

3

**Comment by diemol** [comment]
We have the [same test](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk//examples/java/src/test/java/dev/selenium/bidirectional/BidiApiRemotewebdriverTest.java#L187-L205) in our documentation and it is working well. 

Please not that you need to use Grid 4 as well.

**Comment by ayushi-nyk** [comment]
Ohk .. Thanks .. But can you please help me to understand why it wont support grid 3 ?

**Comment by diemol** [comment]
You need to use Selenium 4 bindings and Grid 4 because those features were not implemented in Selenium 3. 
Please check https://www.selenium.dev/documentation/webdriver/getting_started/upgrade_to_selenium_4/ and https://www.selenium.dev/documentation/grid/
