### ISSUE TITLE
[🐛 Bug]: Can't capture alert window

### ISSUE THREAD

**Issue by Redysz** [SeleniumHQ/selenium#11707]
### What happened?

I can't access/find/click alert with `alert_is_present` (`TimeoutException`) or `driver.switch_to.alert` (`NoAlertPresentException`) features in both Firefox and Chrome drivers. However the alert is visible. I don't want to ignore that alert or auto-click 'Allow'/'Block' button. Let's say I want to get alert text.
Related  [stackoverflow topic](https://stackoverflow.com/questions/75555968/cant-access-alert-from-selenium-webdriver)

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.by import By


def test_easy():
    driver = webdriver.Firefox()  # The same with Chrome
    driver.get("https://webcamtests.com/check")
    WebDriverWait(driver, 10).until(ec.element_to_be_clickable((By.ID, "webcam-launcher"))).click()
    alert = WebDriverWait(driver, 10).until(ec.alert_is_present())
```

### Relevant log output

```shell
>       alert = WebDriverWait(driver, 10).until(ec.alert_is_present())

tests\test_easy_example.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.support.wait.WebDriverWait (session="4708ba34-ce30-461a-aacf-ca93b63e755d")>
method = <function alert_is_present.<locals>._predicate at 0x000001CFB4122020>
message = ''

    def until(self, method, message: str = ""):
        """Calls the method provided with the driver as an argument until the \
        return value does not evaluate to ``False``.
    
        :param method: callable(WebDriver)
        :param message: optional message for :exc:`TimeoutException`
        :returns: the result of the last call to `method`
        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs
        """
        screen = None
        stacktrace = None
    
        end_time = time.monotonic() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, "screen", None)
                stacktrace = getattr(exc, "stacktrace", None)
            time.sleep(self._poll)
            if time.monotonic() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:
```

### Operating System

Windows 10 64bit

### Selenium version

Python 3.11

### What are the browser(s) and version(s) where you see this issue?

Chrome 110, Chrome Firefox 102.8

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.177, FirefoxDriver 102.8.0

### Are you using Selenium Grid?

No

**Comment by TamsilAmani** [comment]
Looking into this issue

**Comment by titusfortner** [comment]
Those aren't JavaScript alerts, those are from your system asking for permission to display the camera. You have to figure out if you can set options on the browser ahead of time to allow that behavior.

**Comment by Redysz** [comment]
> Those aren't JavaScript alerts, those are from your system asking for permission to display the camera. You have to figure out if you can set options on the browser ahead of time to allow that behavior.

System alerts are totally different. I got information that those are browser ones (and text/options are based on system information). Still it's question if there is a way to use Selenium to set up (anyhow) source options using webdriver. For example I have two cameras and want to choose one and use Selenium (since setting is just a small part of the whole test).

**Comment by TamsilAmani** [comment]
@Redysz I was working on this issue. What titus mentioned is correct. The alert is not part of JS. It is not a part of DOM so I don't think selenium can target it. Regarding your doubts:

> don't want to ignore that alert or auto-click 'Allow'/'Block' button. Let's say I want to get alert text.

The page asking for permission will error out if you don't click **allow**. There's a way to do that. (I'll show it later). Also, getting the text of the prompt can be hardcoded? I'm saying this as all the permissions of a browser follow a fixed template. You can leverage that?

> I have two cameras and want to choose one and use Selenium

This can be done from within the website using selenium. For example, on www.webcamtests.com/check there's an element:
`<select id="webcam-selecter"><option value="">videoinput#1</option></select>
`which can be used to select the preferred webcam. Isn't it?

Here is the code which selects **Allow** from the prompt automatically and uses my camera to show me the results. My webcam starts, I can see the live video and the end results.

```
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options as ChromeOptions
import time


def test_easy():
    options = ChromeOptions()
    options.add_argument("use-fake-ui-for-media-stream")

    driver = webdriver.Chrome(options=options)  # The same with Chrome
    driver.get("https://webcamtests.com/check")
    WebDriverWait(driver, 10).until(ec.element_to_be_clickable((By.ID, "webcam-launcher"))).click()
    time.sleep(30)
    driver.quit()

test_easy()
```

**Comment by diemol** [comment]
Thanks @TamsilAmani and @titusfortner for triaging! 

I will close this as there is no bug to fix, but you can continue posting more if that helps your use case.

**Comment by Redysz** [comment]
Thank you @TamsilAmani for your analysis. Of course [www.webcamtests.com/check](http://www.webcamtests.com/check) was an example. There are many sites where there is no "Allow" button on a page and, what more important, there is no element for choosing source and then selecting from web browser element level is the only way.

On stackoverflow I've got the comment, that for situations like that one can use `py_robot` library in python or `robot` for java.
