### ISSUE TITLE
[🐛 Bug]: WebDriver hanging in case of DevTools opened and tests are executed in multiple thread

### ISSUE THREAD

**Issue by fenben5754** [SeleniumHQ/selenium#11703]
### What happened?

Create at least 2 test in different classes
Set the collection behavior to CollectionPerClass, and the MaxParallelThreads to 2
Create a simple webdriver and get the devtools session
Try to Run the tests in the same time from Test Explorer

result: tests are hanging

expected result: page should opened on all created browser

hint: works fine if I set the MaxPrallelThreads to 3

### How can we reproduce the issue?

```shell
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.DevTools;
using System.Threading;
using Xunit;

[assembly: CollectionBehavior(CollectionBehavior.CollectionPerClass, MaxParallelThreads = 2)]
namespace SeleniumDevtoolMultiThread
{
    public class TestClass1
    {
        [Fact]
        public void Test()
        {
            TestClassHelper.OpenDevToolsAndNavigate();
        }
    }

    public class TestClass2
    {
        [Fact]
        public void Test()
        {
            TestClassHelper.OpenDevToolsAndNavigate();
        }
    }

    public static class TestClassHelper
    {
        public static void OpenDevToolsAndNavigate()
        {
            IWebDriver webDriver = new ChromeDriver();
            IDevTools devTools = webDriver as IDevTools;
            devTools.GetDevToolsSession();
            webDriver.Navigate().GoToUrl("https://www.google.com");
            webDriver.Quit();
        }
    }
}
```

### Relevant log output

```shell
there is no log, the test just hanging
```

### Operating System

Windows 10

### Selenium version

.NET 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 110.0.5481.177

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.7700

### Are you using Selenium Grid?

not used

**Comment by fenben5754** [comment]
hi @titusfortner I see you commented under other devtools relater issues
Maybe can you check this one as well please?
Thanks

**Comment by diemol** [comment]
Where does it hang? Is it still happening on 4.10.0?

**Comment by fenben5754** [comment]
Yes is happening with the latest version as well
Is hanging after start the browser
![IMG_20230627_114044](https://github.com/SeleniumHQ/selenium/assets/58862213/8cd038c0-99d9-4641-ac08-5c0e51592db0)

**Comment by diemol** [comment]
Why are you using a static method? Wouldn't that reuse the variable between threads?

**Comment by fenben5754** [comment]
is just for the more simple example usage
If I increase the max allowed threads to 3, is works fine, but if I add a new 3. test is hanging again
Seems to me the issue is coming if the parallel running tests count is the same or higher than the max allowed threads

**Comment by diemol** [comment]
Right.

We do not have time right now to check this. Would you please help us debug the code to identify on which line it hangs?

**Comment by nvborisenko** [comment]
Good news here I can reproduce the issue. Not good news: my local build is failing to go deeper into investigation.

**Comment by fenben5754** [comment]
@nvborisenko thanks for this fix I just tried it and seems now there is a hanging at this call: 
networkAdapter.Enable(new DevToolsNetwork.EnableCommandSettings()).Wait()
without this Enable call seems is works fine, not sure if this Enable method needs to be called or what is actually doing
Can you suggest on this?

Thanks

**Comment by nvborisenko** [comment]
@fenben5754 please wait until v4.12.4 will be released, and then we will work together :)

**Comment by nvborisenko** [comment]
@fenben5754, 4.12.4 is available, try it and share code snippet to reproduce the issue.

**Comment by fenben5754** [comment]
can reproduce with this build as well

IWebDriver webDriver = new ChromeDriver();
            IDevTools devTools = webDriver as IDevTools;
            var session = devTools.GetDevToolsSession();
            var networkAdapter = session.GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V116.DevToolsSessionDomains>().Network;
            networkAdapter.Enable(new OpenQA.Selenium.DevTools.V116.Network.EnableCommandSettings()).Wait();

code hanging at the Enable().Wait() method, in case of parallell test running

**Comment by nvborisenko** [comment]
Use
```csharp
Task.Run(async () => await networkAdapter.Enable(new OpenQA.Selenium.DevTools.V116.Network.EnableCommandSettings())).Wait();
```

Or become closer to `async/await` pattern
```csharp
public async Task MyTest()
{
  await networkAdapter.Enable(new OpenQA.Selenium.DevTools.V116.Network.EnableCommandSettings());
}
```
