### ISSUE TITLE
[🐛 Bug]: send_keys() is messing up indentation

### ISSUE THREAD

**Issue by MT010104** [SeleniumHQ/selenium#11709]
### What happened?

![image](https://user-images.githubusercontent.com/65756145/221345671-bd6a2ea0-3224-4b26-9946-b44d6c6d5d2c.png)
![image](https://user-images.githubusercontent.com/65756145/221345726-8afd3840-d938-4af6-9103-f22dd61f1ec1.png)
When using "ctrl+c" and "ctrl+v" to copy and paste the code to the textarea, its' indentation doesn't change. But when we use send_keys() to enter the text in, its' indentation will be in a mess.

### How can we reproduce the issue?

```shell
We just wanna enter the code in a common textarea.
```

### Relevant log output

```shell
.
```

### Operating System

macOS

### Selenium version

Python

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

### Are you using Selenium Grid?

4.8.2

**Comment by diemol** [comment]
Closing as we did not get more information.
