### ISSUE TITLE
[🐛 Bug]: Selenium 4.6.0 | Chrome 107 | Error running command: [C:\Users\<user>\AppData\Local\Temp\selenium-managerxxxxxxxxxx\selenium-manager.exe

### ISSUE THREAD

**Issue by nainig-impactqa** [SeleniumHQ/selenium#11708]
### What happened?

Its been many times observed that the test fails at the very initial step, browser invocation with the following error.

Error running command: [C:\Users\<user>\AppData\Local\Temp\selenium-manager26982032366700014792537646203416715\selenium-manager.exe, --driver, chromedriver] Build info: version: '4.6.0', revision: '79f1c02ae20' System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1' Driver info: driver.version: SelUIDriver

The issue is reproducible on Windows as well as MAC.

### How can we reproduce the issue?

```shell
Selenium 4.6.0, Chromer 107
```

### Relevant log output

```shell
C:\Users\<user>\AppData\Local\Temp\selenium-manager26982032366700014792537646203416715\selenium-manager.exe, --driver, chromedriver] Build info: version: '4.6.0', revision: '79f1c02ae20' System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.15.1' Driver info: driver.version: SelUIDriver
```

### Operating System

Win, MAC

### Selenium version

Selenium 4.6.0, JDK11 or JDK 14

### What are the browser(s) and version(s) where you see this issue?

Chrome 107

### What are the browser driver(s) and version(s) where you see this issue?

chromerdriver 107.0.5304.62, chrome: 107

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Please update to 4.8.1, many improvements have been done in both Selenium Java and Selenium Manager. If you are still experiencing an issue, please open a new one with the complete information showing how to reproduce it.
