### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.InvalidSelectorException is not thrown by fluent wait even when it's not ignored

### ISSUE THREAD

**Issue by MohabMohie** [SeleniumHQ/selenium#11712]
### What happened?

https://seleniumhq.slack.com/archives/C0ABCS03F/p1677391208456589

I'm using an invalid element locator (for testing purposes) and I'm trying to identify that element within a fluent wait
The fluent wait is ignoring some exceptions (not including org.openqa.selenium.InvalidSelectorException)
Expected Behavior: the invalid selector exception should be thrown immediately
Actual Behavior: it gets caught and rethrown recursively until a timeout occurs, and then a timeout is thrown with the cause InvalidSelectorException
Here's a gist with the fluentWait block, the expected exceptions block, and a screenshot from the throwable object.
https://gist.github.com/MohabMohie/6c4d16bfca0ad7b15c3e274b631ecdf9
Is this a bug or am I doing something wrong?

### How can we reproduce the issue?

```shell
https://gist.github.com/MohabMohie/6c4d16bfca0ad7b15c3e274b631ecdf9
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 11

### Selenium version

Java 4.8.1

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
The issue is that `InvalidSelectorException` subclasses `NoSuchElementException`.
https://github.com/SeleniumHQ/selenium/blob/selenium-4.8.1/java/src/org/openqa/selenium/InvalidSelectorException.java#L28

This results in incorrect waiting behavior because a bad selector can never be fixed. I believe we had a conversation about this when I changed it in Python. There might be another open issue somewhere about this.

**Comment by MohabMohie** [comment]
@titusfortner I'd love to help fix the issue if you can give me some guidance or a reference in the python code to look at an mimic :)

**Comment by MohabMohie** [comment]
found the other issue and the agreement
https://github.com/SeleniumHQ/selenium/issues/10833

**Comment by titusfortner** [comment]
@diemol did we discuss this in a tlc meeting? I can't remember what we discussed or what we decided previously.

**Comment by diemol** [comment]
https://www.selenium.dev/meetings/2022/tlc-08-17/#proposals

**Comment by MohabMohie** [comment]
I really really want to do this change guys :D looks easy enough as a first contribution :D
I've been wanting to contribute for a while now...

**Comment by diemol** [comment]
Yes, please help us with a pull request. And even a blog post describing the change would be awesome!

**Comment by MohabMohie** [comment]
Okay, I made the fork, and will make the change and open a PR
I'll explore to see how to make a blog post... I noticed that you guys recently migrated to docusaurus 2, so that should be something I can manage 👍

**Comment by MohabMohie** [comment]
@titusfortner @diemol hyg the two PRs for the change and blog post
https://github.com/SeleniumHQ/selenium/pull/11727
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1325
