### ISSUE TITLE
[🚀 Feature]: Direct access to the raw data of the body via stream/byte array and not exclusively as string

### ISSUE THREAD

**Issue by FSharpCSharp** [SeleniumHQ/selenium#11726]
### Feature and motivation

Unfortunately, I have not yet found a way to get to my desired destination even via detours. Intermediary proxies have been the only option so far, but I'd like it better if there was a way to do this in Selenium itself. In this respect I'll put the topic here as a feature request. In my search I have not found a similar feature request yet. If there should be a similar feature request, we can close it right away.

But now to my actual request:
I use Selenium in C# to run automated tests. In this context, I use the possibilities available in Selenium to tap the generated network traffic in order to run further tests. However, in this context I came across something that makes me unhappy. Within the provided network functions and events to influence the same, in all objects the body is available to me exclusively as data type "String". But in my examples binary data is transferred. This results in very unpleasant consequences for me. First, I can't match the data, because I first have to convert the provided string back into a byte array. However, this may cause conversion errors, plus it is completely impractical.

For this reason, my wish would be for Selenium to be able to provide the entire body data as a standalone object. Of course, that can continue to provide the body additionally as a string for all I care, but it should also be possible to access the original data stream in binary form, either as a stream, byte array, or similar constructs. I have roughly sketched this below as an example. For the time being, this only concerns the response side. From my point of view, such a customization would of course have to be done from the request side through everything between status and on the response side.

I would be very grateful if you could provide the data in this form.

### Usage example

```
internal class Program
{
    private static void Main(string[] args)
    {
        IWebDriver driver = new ChromeDriver();
        SetupNetworkLogging(driver);
        driver.Navigate().GoToUrl("https://www.selenium.dev/");

        Console.Read();
    }

    public static void SetupNetworkLogging(IWebDriver driver)
    {
        var manager = new NetworkManager(driver);
        manager.NetworkResponseReceived += ResponseHandler;

        var monitoring = manager.StartMonitoring();
        monitoring.Wait();
    }

    private static void ResponseHandler(object sender, NetworkResponseReceivedEventArgs e)
    {
        // sample binary access
        var body = e.ResponseBody;
        using (Stream responseStream = body.GetStream())
        {
            while (responseStream.Position < responseStream.Length)
            {
                var buffer = new byte[4];
                responseStream.Read(buffer, 0,buffer.Length);
                // The buffer can be processed further here.
            }
        }

        // This way you could get the body as a string, possibly even as an overload with a special encoding.
        Console.Write(body.ToString());
    }
}
```

**Comment by nvborisenko** [comment]
@FSharpCSharp As I understood correctly, you cannot differentiate type of response body, whether it's a string or bytes. I think you can do it via response headers.

If I do like this:
```csharp
network.NetworkResponseReceived += (sender, e) =>
  Console.WriteLine(String.Join(", ", e.ResponseHeaders.Select(h => h.Key + ": " + h.Value)));
```

Then output is like:
```
content-length: 3123, Content-Type: text/html
```

or:
```
content-length: 127, Content-Type: image/gif
```

For binary content `Content-Type` would be `application/octet-stream` or `application/x-binary`.

**Comment by FSharpCSharp** [comment]
At this point, the Content-Type is not the problem. I always receive responses in all events only as text form, including binary data. Therefore, the distinction of the ContentTypes does not help me at all, because everything is always interpreted as text. Even binary data is not delivered as Base64 but converted. It is therefore not possible for me to restore the original data of the web request, which was made in binary form. Therefore, I need direct access to the responses of the web request in the form of a binary stream or a binary array.

To elaborate further, when I say that the Content-Type is not the issue here, I mean that regardless of whether the Content-Type is set to text, JSON, XML or any other type, I always receive the responses in text form. This includes binary data which should ideally be received as a stream of bytes but instead, it's also received as text. This makes it impossible for me to distinguish between different types of content because they are all interpreted as text.

When I mention that even binary data is not delivered as Base64 but converted, it means that instead of receiving a Base64 encoded string that represents the binary data, which could be easily decoded back into its original binary form, I receive a text representation of the binary data. This conversion from binary to text leads to a loss of information which makes it impossible for me to restore the original binary data from the web request.

Finally, when I say that I need direct access to the responses of the web request in the form of a binary stream or a binary array, it means that instead of receiving a text representation of the response data, I would prefer to receive it in its original binary form. This could be either as a stream of bytes (binary stream) or as an array of bytes (binary array). This would allow me to process and handle different types of content appropriately based on their original format and not just as text.

**Comment by titusfortner** [comment]
So, first, the Base64 as a String is how the spec requires things be sent/received.

I don't understand your use case. Do you just need access to what is sent and received? Does the logging solution that @nvborisenko has created recently suffice?

The implementation of sending requests and receiving responses is an internal implementation detail and should not be directly exposed to the end user.

**Comment by FSharpCSharp** [comment]
> So, first, the Base64 as a String is how the spec requires things be sent/received.
> 
> I don't understand your use case. Do you just need access to what is sent and received? Does the logging solution that @nvborisenko has created recently suffice?
> 
> The implementation of sending requests and receiving responses is an internal implementation detail and should not be directly exposed to the end user.

I am working with binary data in web requests, which I need to control and manipulate. However, the API I am using always returns the data in text format, regardless of the original content type. This includes binary data, which is not delivered as Base64 but is instead converted to text. This conversion process results in a loss of information, making it impossible for me to restore the original binary data from the web request.

The issue here is not with the Content-Type, as I receive all responses in text form, regardless of whether the Content-Type is set to text, JSON, XML, or any other type. This makes it impossible for me to distinguish between different types of content because they are all interpreted as text.

What I need is direct access to the body data of the web requests in their original binary form, either as a binary stream or a binary array. This would allow me to handle different types of content appropriately based on their original format, rather than having to convert everything from text.

**Comment by titusfortner** [comment]
Sorry, I wasn't reading this issue closely enough and was thinking of the commands (what Selenium manages) not the web traffic (which is Google manages).

But yes, this is how the protocol works — https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-getResponseBody
Body is always a string and there's a boolean value to let you know if it is encoded.

**Comment by nvborisenko** [comment]
@FSharpCSharp can you please provide example what `e.ResponseBody` returns for you when you cannot determine original type of binary/string data?

**Comment by nvborisenko** [comment]
I am reopening it, in .net we provide API on top of CDP. Protocol defines a flag whether body is encoded or not, while selenium might expose this data in "unpredictable" format higher.

**Comment by titusfortner** [comment]
So what is it that we want Selenium to do here? Do you have a specific code update in mind, @nvborisenko?

**Comment by nvborisenko** [comment]
Expose to the user whether raw data is encoded, as original protocol does it.

**Comment by FSharpCSharp** [comment]
Thank you for your responses and suggestions. I understand that the implementation of sending requests and receiving responses is an internal implementation detail and should not be directly exposed to the end user. However, I am working with binary data in web requests, which I need to control and manipulate. The API I am using always returns the data in text format, regardless of the original content type. This includes binary data, which is not delivered as Base64 but is instead converted to text. This conversion process results in a loss of information, making it impossible for me to restore the original binary data from the web request.

The issue here is not with the Content-Type, as I receive all responses in text form, regardless of whether the Content-Type is set to text, JSON, XML, or any other type. This makes it impossible for me to distinguish between different types of content because they are all interpreted as text.

What I need is direct access to the body data of the web requests in their original binary form, either as a binary stream or a binary array. This would allow me to handle different types of content appropriately based on their original format, rather than having to convert everything from text.

@nvborisenko, your suggestion to expose to the user whether the raw data is encoded, as the original protocol does, could potentially help me determine the original type of the binary/string data. However, it is unclear when and if this change will be implemented.

In the meantime, I could explore other ways to handle different types of content based on their original format, rather than having to convert everything from text. This could involve using different tools or libraries that provide more control over the handling of binary data in web requests. It's also worth noting that the implementation of sending requests and receiving responses is an internal implementation detail and should not be directly exposed to the end user. Therefore, any solution should ideally be implemented in a way that respects this principle.

I hope this is helpful and look forward to further discussions and suggestions. Please let me know if you have any other questions or need further clarification. Good luck with your project!

**Comment by nvborisenko** [comment]
I see a problem, this is why I reopened this ticked.

I looked through the code again, and trying to understand which way suites better for all us. Return `base64` or `byte[]` (with flag which indicates whether it is encoded). `base64` seems better. Now I need to understand the impact of this breaking change, and apply convenient way of deprecating some APIs.

There is no specific timeline to be implemented it.

**Comment by huwei365** [comment]
I met a problem about this. I want to get a image from responsebody, but it's data wrong when i  use  Encoding.UTF8.GetBytes(ResponseBody) convert string to byte[], data length and content not correct when  compare origin image, I try to find cause through resource code , but failed,  I can't find response body from binary translate to string in WebDriver resource code,

**Comment by FSharpCSharp** [comment]
I'm experiencing the same issues as @huwei365, which was the trigger for my inquiry. The problem seems to be that internally, the data no longer appears to be in Base64 but is being converted into "pure" text, including pure binary data. This, of course, makes it impossible to continue working with it, or only with significant compromises.
