### ISSUE TITLE
getText on a select element should return the text of the first selected option

### ISSUE THREAD

**Issue by alb-i986** [SeleniumHQ/selenium#1172]
I need to retrieve the text from a select element, like as follows:

```
<html>
    <body>
    <form>
        <select id="items">
            <option>item1</option>
            <option>item2</option>
            <option>item3</option>
        </select>
     </form>
    </body>
</html>
```

I'd expect getText on `#items` (as well as on `form`) to return what's *visible* on the UI, aka the first selected option, aka "item1" in the example.
Instead, I'm getting a string with all of the options

```
WebElement selectElement = driver.findElement(By.id("items"));
String firstSelectedOptionText = new Select(selectElement).getFirstSelectedOption().getText();
assertEquals(selectElement.getText(), firstSelectedOptionText);
```

is failing with 

```
 java.lang.AssertionError:
Expected :
item1
Actual :
item1\n item2\n item3\n
```

Is this expected?

Selenium v2.47.1
ChromeDriver 2.20.353145
Firefox 41.0.2

Thanks

**Comment by ddavison** [comment]
Here is the javadoc for the method in question:

```java
/**
   * Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements,
   * without any leading or trailing whitespace.
   *
   * @return The innerText of this element.
   */
```

The functionality you request would go against this.  Since the `<select>` does not have innerText, but it's "sub-element `<option>`s" do, it is getting the text of those, so this *is* as expected.  since a `<select>` operates just as an `<input type='text'>` would - It be recommended to use `.getAttribute("value")`

**Comment by barancev** [comment]
Current implementation conforms the standard:
https://w3c.github.io/webdriver/webdriver-spec.html#getelementtext

Feel free to open an issue on the standard if you think this behaviour should be changed.
