### ISSUE TITLE
[🐛 Bug]: clear() method not clearing input on react component

### ISSUE THREAD

**Issue by mrpet88** [SeleniumHQ/selenium#11739]
### What happened?

It seems that clear() method is not working properly with latest version of selenium, in React components. Since I can not provide much details from my company's project, I created a repository, where the issue is reproducible. 

**Steps:**

1. Navigate to a page that has a react input component
2. clear() the input and sendKeys()

**Result:**
Characters are being send next to the previous input. 

**More Info:**
- I don't need a workaround such as Js executor etc, I just need to know if this can be fixed from selenium side, or not. 
- I am able to reproduce with **selenium 3** as well
- I am not able to reproduce it to an input that is not react component
- Using serenity-BDD (older version - which is using selenium 3.x.x) seems to also resolve the issue

**Image:**
- ![clear-issue-selenium4](https://user-images.githubusercontent.com/40420772/223218545-bd74b3ff-8c7b-4bd5-83da-c21339f744a4.png)
- ![clear-issue-debug-screen](https://user-images.githubusercontent.com/40420772/223219318-ba2dde59-4f83-47d4-bcea-b58081ff44bb.png)

### How can we reproduce the issue?

```shell
Here is a link of the repository, where the issue can be reproduced.

https://github.com/mrpet88/check-sendkeys-issue
```

### Relevant log output

```shell
N/A
```

### Operating System

macOS

### Selenium version

selenium-java-4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 110.0.5481.77

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by aahmed-dfe** [comment]
Looks like issue is you've cached `IWebElement` in a variable rather than locating it again - after you've sent keys to it.

Try finding it again through `Driver.FindElement`

Some pseudo code below....

```
Func<IWebElement> getElement = () => driver.FindElement(By.name("email")); 
if(!getElement().getAttribute("value").isEmpty()){
  getElement().Clear();
}
getElement().SendKeys("Selenium");
```

Could also be that you're not locating the right element - that takes input

**Comment by mrpet88** [comment]
> Looks like issue is you've cached `IWebElement` in a variable rather than locating it again - after you've sent keys to it.
> 
> Try finding it again through `Driver.FindElement`
> 
> Some pseudo code below....
> 
> ```
> Func<IWebElement> getElement = () => driver.FindElement(By.name("email")); 
> if(!getElement().getAttribute("value").isEmpty()){
>   getElement().Clear();
> }
> getElement().SendKeys("Selenium");
> ```
> 
> Could also be that you're not locating the right element - that takes input

If you mean something like this:
```for (int i = 0; i <= 7; i++) {
         Supplier<WebElement> getElement = () -> driver.findElement(By.name("email"));
            if (!getElement.get().getAttribute("value").isEmpty()) {
              getElement.get().clear();
            }
            getElement.get().sendKeys("Selenium");
        }```

Still same issue.
If the locator was wrong wouldn't that mean that I wouldn't be able to type into it?

**Comment by aahmed-dfe** [comment]
Thanks for the follow up - Dug into the example;

In the screenshot the clear() doesn't work because `Email is required` it looks like it has `minimum field length` set on the DOM  and there's an email error that appears when you try to clear the input...

There's also the `autocomplete` attribute on there - which has some references here as being problematic --- https://stackoverflow.com/questions/50677760/selenium-clear-command-doesnt-clear-the-element

There's ways around this using javascript when needed; https://stackoverflow.com/questions/17237772/html-how-to-clear-input-using-javascript

setting `element.value = ""` or adding a `placeholder` attribute 

Working example below;
`Driver.ExecuteJavaScript("arguments[0].value = ''", element);`

Hope this solves!

Keen to hear if there's better solutions :)

**Comment by titusfortner** [comment]
We recently made a change to the atom for this — #11504 which I think will address this issue?
But it hasn't yet been implemented in chromedriver, yet. 

@diemol did we reach out to Google about this?

**Comment by diemol** [comment]
>Using serenity-BDD (older version - which is using selenium 3.x.x) seems to also resolve the issue

@mrpet88 I did not understand this part. If you use Serenity-BDD works? But above you mentioned it did not work with Selenium 3.

**Comment by mrpet88** [comment]
> > Using serenity-BDD (older version - which is using selenium 3.x.x) seems to also resolve the issue
> 
> @mrpet88 I did not understand this part. If you use Serenity-BDD works? But above you mentioned it did not work with Selenium 3.

Yes, so I found out, that it was working with `Serenity BDD` because Serenity was using for clear() input Keyboard commands. Which is not the case with the newest versions of Serenity. 
Ofc I found this out, after reporting this issue here. So you can ignore this comment.

**Comment by diemol** [comment]
@titusfortner no, I did not, I forgot, sorry. Anyway, I just shared the information with them

* https://bugs.chromium.org/p/chromedriver/issues/detail?id=4388
* https://github.com/mozilla/geckodriver/issues/2094
* https://github.com/MicrosoftEdge/EdgeWebDriver/issues/73
* https://bugs.webkit.org/show_bug.cgi?id=253704

**Comment by diemol** [comment]
@mrpet88 Thank you for providing your repository to triage this. 

I was able to reproduce it for Chrome, Edge, and Safari. But it works in Firefox. This shows that Selenium is sending the command and something in the browser is not doing the right thing when it comes to a React component. Maybe updating the atoms over there will help, but I recommend reporting this issue to those browsers. I will leave some links below where you can report it.
