### ISSUE TITLE
[🐛 Bug]: Can't Connect to Selenium HUB Connect to Host Failed

### ISSUE THREAD

**Issue by aslanonline** [SeleniumHQ/selenium#11734]
### What happened?

Hello,

I am getting with CURL available Node slots with Graphql.
I am retrieving the results every 3-5 Seconds. I am getting correct results, bot often CURL Can't connect to Grid Hub with Error Code 7. 
My Hub and my Node are on the Same Server.

### How can we reproduce the issue?

```shell
`    $xml='{"query": "{ grid { maxSession, sessionCount } }"}';
    $url='http://XXX.XXX.XXX.XXX:4444/graphql';

    $headers = array(

    "Content-Type: application/json",
    "Content-length: ".strlen($xml),

    );

    //  Initiate curl
    $ch = curl_init();

    // Disable SSL verification
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_ENCODING, "");

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_URL,$url);

    $ret=curl_exec($ch);
    $json=json_decode($ret,true);
    $max=$json['data']['grid']['maxSession'];
    $sessioncount=$json['data']['grid']['sessionCount'];
`
```

### Relevant log output

```shell
-
```

### Operating System

Debian 11

### Selenium version

JAVA 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 110

### Are you using Selenium Grid?

4.8.1

**Comment by aslanonline** [comment]
I am also getting this error in PHP Webdriver

[2023-03-05 19:42:55] local.ERROR: JSON decoding of remote response failed.
Error code: 4
The response: ''
 {"exception":"[object] (Facebook\\WebDriver\\Exception\\Internal\\UnexpectedResponseException(code: 0): JSON decoding of remote response failed.
Error code: 4
The response: ''

**Comment by aslanonline** [comment]
Some strange things.
If I write directly to Putty this one
curl -X POST -H "Content-Type: application/json" --data '{"query": "{ grid { maxSession, sessionCount } }"}' -s XXXX.XXXX.XXXX.XXXX:4444/graphql 

I don't have any connection issues.
Only got errors with cURL in PHP

**Comment by diemol** [comment]
What happens if you try a normal CURL from the terminal? I am pretty sure it is working as intended because the Grid UI queries the GraphQL endpoint every 5 seconds.

**Comment by aslanonline** [comment]
You are right. With Terminal its working perfect.
What can be the problem?

**Comment by diemol** [comment]
Not sure, I would advise to post the question to StackOverflow or come to the chat and ask other Selenium users. I will leave some useful links below.
