### ISSUE TITLE
[🐛 Bug]: Dockerfile does not build. Hash is out of date.

### ISSUE THREAD

**Issue by jasperstone** [SeleniumHQ/selenium#11731]
### What happened?

When [this docker file](https://github.com/SeleniumHQ/selenium/blob/trunk/scripts/dev-image/Dockerfile) was created, it referenced the latest version of ubuntu:focal. Since the latest version of this image has moved forward, the dockerfile no longer builds because the hash doesn't match.

Suggestion:
Change line 3 to the following if you want to maintain the current from image and hash for security.
FROM ubuntu:focal-20210723@sha256:1e48201ccc2ab83afc435394b3bf70af0fa0055215c1e26a5da9b50a1ae367c9

Or change it to the following to just build with the latest image
FROM ubuntu:focal

### How can we reproduce the issue?

```shell
git clone https://github.com/SeleniumHQ/selenium.git
cd .\selenium\scripts\dev-image\
docker build .
```

### Relevant log output

```shell
[+] Building 4.3s (3/3) FINISHED
 => [internal] load build definition from Dockerfile 0.0s
 => => transferring dockerfile: 32B 0.0s
 => [internal] load .dockerignore 0.0s
 => => transferring context: 2B 0.0s
 => ERROR [internal] load metadata for docker.io/ubuntu/focal@sha256:1e48201ccc2ab83afc435394b3bf70af0fa0055215c1e  4.1s
------
 > [internal] load metadata for docker.io/ubuntu/focal@sha256:1e48201ccc2ab83afc435394b3bf70af0fa0055215c1e26a5da9b50a1ae367c9:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

### Operating System

Windows 11 22H2

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
@jasperstone would you like to send a PR to update the image to the most recent release?

**Comment by jasperstone** [comment]
Sure would. Do you have documentation on your PR process? I'm not a contributor on the repo.

**Comment by diemol** [comment]
Our contribution guidelines are here https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md

But in this case, I would be fine if you edit the [`Dockerfile`](https://github.com/SeleniumHQ/selenium/blob/trunk/scripts/dev-image/Dockerfile#L3) and use a tag for a newer image. Then you can either build it locally or use GitPod to test it.

**Comment by symonk** [comment]
bumped the sha on this and its now building ok, thanks @jasperstone for the heads up!
