### ISSUE TITLE
[🚀 Feature]: Add new section for integrations such as Testcontainers

### ISSUE THREAD

**Issue by eddumelendez** [SeleniumHQ/selenium#11738]
### Feature and motivation

[Testcontainers](https://testcontainers.com/) enables to run disposable containers for your tests. 

* `Testcontainers for Java` already provides an integration. See [docs](https://www.testcontainers.org/modules/webdriver_containers/)
* `Testcontainers for .NET` has a [WIP PR](https://github.com/testcontainers/testcontainers-dotnet/pull/780)
* `Testcontainers for Python` already provides an integration. See [docs](https://testcontainers-python.readthedocs.io/en/latest/selenium/README.html)

And although, there is no specific modules for other Testcontainers language implementation, it can be easy to do using the concept of `GenericContainer`

It would be nice to have some documentation as a getting started point between Testcontainers and Selenium.

I can contribute with it.

Cheers

### Usage example

Add one new section for Testcontainers and the content can display what is needed using different tabs per language.

**Comment by refaeli-io** [comment]
@eddumelendez 
Thanks
I will like to add docs about it
tell me where you want to add it. 
With the MkDocs?

**Comment by diemol** [comment]
This should be a reference to TestContainers on the Ecosystem page https://www.selenium.dev/ecosystem/, we won't duplicate their documentation as it creates more maintenance, whereas they keep it up to date.

**Comment by eddumelendez** [comment]
Thanks for pointing out to the ecosystem page, @diemol ! 

@ShaharM7 glad you want to contribute. I think you need to make the changes [here](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/ecosystem/_index.html#L446-L456). Please, let us know once you send the PR so we can take a look.

Thanks in advance

Cheers

**Comment by refaeli-io** [comment]
@eddumelendez 
I do the reference and the [p.r  for dotnet implementation](https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1328)
I would be happy for the developers of the Testcontainers - java implementation to join me 😄  to give them also a credit 

Also, I want to add docs to the [Testcontainers - dotnet website](https://dotnet.testcontainers.org/modules/) under modules section.
Tell me what do you think 😃

**Comment by diemol** [comment]
I left some comments on the PR. I will close this issue and carry on the conversation in the PR.

**Comment by refaeli-io** [comment]
@diemol 
Thanks
