### ISSUE TITLE
 internet explorer 10 browser does not navigate to a website only says  "This is the initial start page for the WebDriver server."

### ISSUE THREAD

**Issue by bleeet** [SeleniumHQ/selenium#1174]
Hi guys 

I upgraded from windows xp to  windows 7 and I am unable to use the internet explorer 10 browser with selenium. When I run my script the the ie browser opens but it does not navigate to the webpage I have entered. A white page opens and it just says "This is the initial start page for the WebDriver server."

does anyone happen to know what is wrong and how I can fix this?

**Comment by jimevans** [comment]
Have you configured IE properly, as documented on [this wiki page](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration)?

**Comment by bleeet** [comment]
yes I have i unchecked protected Mode settings for each zone. and  "Enhanced Protected Mode" is unchecked. The browser worked only 2 times out of the many times I have tried running my script while playing around with the protected Mode settings. I am at a lost as to why it won't open a url. 

by the way I am using selenium wrapper and excel if that matters

**Comment by jimevans** [comment]
Wait, it doesn't _always_ fail? You were able to successfully navigate at least some times? For debugging purposes, remove the wrapper and Excel framework, and use the driver directly from the programming language of your choice (.NET, Java, Python, Ruby, etc.). Also, you'll want to provide the code you're using that fails, and what exceptions, if any, that code throws.

I can state with confidence that navigating to arbitrary web pages is not a global issue with the IE driver. The [Selenium project's continuous integration system](http://ci.seleniumhq.org:8080/) runs literally hundreds of tests on every commit to the project, on multiple browser versions and operating system. One of those is running against IE 10, and those tests have not indicated any global issue with navigation on that browser platform.

**Comment by bleeet** [comment]
thanks for responding. My work environment just moved to win 7 and my applications worked in winxp without any trouble but I just got migrated to win 7 and ie 10 and now is does not work. Chrome works but not ie for some reason.

yea that's the weird part. I started off  using  ie9 and it did not work so I tried upgrading to ie 10 to see if that fixes the issue and it worked successfully on the first try then after it stopped working.  after that I played around with the protected Mode settings it worked once again then stopped working. 

here is the vba code I am using to open the ie browser

<code>

Private Sub over100start_Click()

Dim selenium As New SeleniumWrapper.WebDriver
Dim chromex As New SeleniumWrapper.WebDriver

Dim Shell As Object
Dim IE As Object

Application.EnableCancelKey = xlDisabled





On Error Resume Next

    Set Shell = CreateObject("Shell.Application")

     selenium.Start "IE", "http://www.google.com"
     

     selenium.Open ("http://www.google.com")

     For Each IE In Shell.Windows 'a


        If IE.Type = "HTML Document" Or IE = "Windows Internet Explorer" Or IE = "Microsoft Internet Explorer" Then
            If InStr(IE.LocationName, "Sales Platform") > 0 Then  'c



            End If 'c
       End If

    Next IE  'a

    selenium.executeScript ("javascript:DDLink2( '/ActiveClientList.aspx')")

   Debug.Print ("xpath=//a[@href=""javascript:DDLink2( ""/ActiveClientList.aspx"")""]")




</code>

**Comment by jimevans** [comment]
Okay, so if you're using VBA code (not Visual Basic proper), you'll need to contact the supplier of your wrapper. The Selenium project provides no native bindings that directly support execution via VBA/COM. Additionally, it looks like you're using a different API than the WebDriver API, specifically the Selenium RC API, which is deprecated, and has been so for about the last five years.
