### ISSUE TITLE
[🐛 Bug]: headless=new argument chrashes Chrome

### ISSUE THREAD

**Issue by domosgabor** [SeleniumHQ/selenium#11743]
### What happened?

I have a small application written in C# using chromedriver.exe v110.0.5481.77 and Selenium.WebDriver v4.8.1.
Try to navigate to https://selenium.dev using headless mode.

The C# code is exactly the same as here: https://www.selenium.dev/blog/2023/headless-is-going-away/
```
var options = new ChromeOptions();
options.AddArgument("--headless=new");
var driver = new ChromeDriver(options);
driver.Navigate().GoToUrl("https://selenium.dev");
driver.Quit();
```

It works like expected on my PC and in my dev team on all colleagues laptop. But does not work on one of my clients environment. Client's installed Chrome version is v110.0.5481.77. Tried different .NET verisions, different PC-s on client's environment, error is the same.

What is strange that --headless=old argument works on all PCs.

Error message:
OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: crashed.
The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)

### How can we reproduce the issue?

```shell
var options = new ChromeOptions();
options.AddArgument("--headless=new");
var driver = new ChromeDriver(options);
driver.Navigate().GoToUrl("https://selenium.dev");
driver.Quit();
```

### Relevant log output

```shell
I can see the above detailed error message in the Windows Event Log and a kernelbase.dll errormessage as well.
```

### Operating System

Windows Server 2022 Datacenter

### Selenium version

C#, NET verion 4.7.2, Selenium.WebDriver v4.8.1.

### What are the browser(s) and version(s) where you see this issue?

Chrome 110.0.5481.77 

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver.exe v110.0.5481.77 

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
There is not much Selenium can do, the code passes the arguments to ChromeDriver and Chrome. I will leave some links below so you can reach out to the Chrome developers and post the issue.
