### ISSUE TITLE
[🐛 Bug]: selenium-manager returns multiple lines when chromedriver has been installed through npm

### ISSUE THREAD

**Issue by cosmo0** [SeleniumHQ/selenium#11745]
### What happened?

Source of the issue of https://github.com/SeleniumHQ/selenium-ide/issues/1594

With a certain configuration (see below) `selenium-manager` returns multiple lines, and `selenium-side-runner` cannot process it because it expects a single result, on a single line.

`selenium-side-runner` could be changed to process multiple lines, but the first line returned by `selenium-manager` is the Unix shell script (installed by npm), which is obviously not runnable on Windows. So it's not possible to know which line is the right one.

### How can we reproduce the issue?

As per the documentation: https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner

* Install ChromeDriver through npm: `npm install -g chromedriver`
* Run `selenium-manager.exe -b chrome`

=> multiple lines are returned.

```shell
> npm install -g chromedriver
> .\selenium-manager.exe -b chrome
 INFO    D:\Users\cosmo\AppData\Roaming\npm\chromedriver
 D:\Users\cosmo\AppData\Roaming\npm\chromedriver.cmd
```

If I uninstall the npm chromedriver, it returns a completely different output.

````shell
> npm uninstall -g chromedriver
> .\selenium-manager.exe -b chrome
INFO    D:\Users\cosmo\.cache\selenium\chromedriver\win32\110.0.5481.77\chromedriver.exe`
````

### Operating System

Windows 10

### Selenium version

selenium-side-runner 4.0.0-alpha.42
selenium-manager 1.0.0-M3

**Comment by cosmo0** [comment]
Well, apparently it just uses the `where` command from Windows, which returns multiple entries.

https://github.com/SeleniumHQ/selenium/blob/trunk/rust/src/lib.rs#L252-L258

And sure enough...

````shell
> where chromedriver
D:\Users\cosmo\AppData\Roaming\npm\chromedriver
D:\Users\cosmo\AppData\Roaming\npm\chromedriver.cmd
````

It also means that if, for some reason, I have multiple "executable-looking" files named "chromedriver" in my PATH, it returns all of them. Example if I create dummy ".exe" and ".bat" files next to the "real" ones:

````shell
> where chromedriver
D:\Users\cosmo\AppData\Roaming\npm\chromedriver
D:\Users\cosmo\AppData\Roaming\npm\chromedriver.bat
D:\Users\cosmo\AppData\Roaming\npm\chromedriver.cmd
D:\Users\cosmo\AppData\Roaming\npm\chromedriver.exe
````

Not sure what should be done at this point, especially since Windows doesn't have the "is executable" flag like *nix does.

Maybe the simplest solution would be to try to run each of them in succession with the `--version` arg, and return the most recent one? It turns out all drivers accept this arg and return a first line formatted in the same way.

````shell
> .\chromedriver.exe --version
ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839})
> .\geckodriver.exe --version
geckodriver 0.32.2 (602aa16c20d4 2023-02-08 00:09 +0000)

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
>  .\msedgedriver.exe --version
Microsoft Edge WebDriver 110.0.1587.63 (b26c9b8fc01e4ee6478cd1585db0bdec672b52a6)
````

Another solution would be to not copy the *nix shell script in the npm chromedriver package, but that would not solve the issue in case of users with "chromedriver.xxx" files in their path.

**Comment by bonigarcia** [comment]
Yes, that is a bug in the Rust side. Thanks a lot for reporting. I'll try to fix it for the next release of selenium-manager.
