### ISSUE TITLE
[🚀 Feature]: Optimization of Select.deselect_all()

### ISSUE THREAD

**Issue by simon-spier0** [SeleniumHQ/selenium#11758]
### Feature and motivation

Sometimes I meet `select` elements with a really lot `option`. When I call `deselect_all()` to make sure no option is selected, it takes long time (a few seconds) because this method iterates over all options and checks each one by one if it's selected.
I've thought up a really fast way to do the same and I would like you to implement it in this method. 🙂

### Usage example

Now:
```python
def deselect_all(self) -> None:
	"""Clear all selected entries. This is only valid when the SELECT supports multiple selections.
	throws NotImplementedError If the SELECT does not support multiple selections
	"""
	if not self.is_multiple:
		raise NotImplementedError("You may only deselect all options of a multi-select")
	for opt in self.options:
		self._unset_selected(opt)
```

Optimized:
```python
def deselect_all(self, using_javascript: bool = False) -> None:
	"""Clear all selected entries. This is only valid when the SELECT supports multiple selections.
	throws NotImplementedError If the SELECT does not support multiple selections
	"""
	if not self.is_multiple:
		raise NotImplementedError("You may only deselect all options of a multi-select")
	if using_javascript:
		options = self._driver.execute_script('return arguments[0].selectedOptions', self._el)  # Gets only the selected options without iterating all ones slowly
	else:
		options = self.options
	for opt in options:
		self._unset_selected(opt)
```

Notice that if developer would like to use the optimized way, he would have to send optional driver instance to the Select class.

**Comment by diemol** [comment]
I guess it depends on the number of available options. However, the workaround submitted relies on a JavaScript call, whereas we prefer to keep using WebDriver based methods. Have you considered using a framework built on top of Selenium that perhaps provides such alternative methods? An example is https://github.com/seleniumbase/SeleniumBase

**Comment by simon-spier0** [comment]
Ok, I will use a framework. Thanks for tip.
