### ISSUE TITLE
How to turn on responsive design view.

### ISSUE THREAD

**Issue by Johnz86** [SeleniumHQ/selenium#1175]
I am using java selenium driver and I want to turn on automatically the responsive design view with specific resolution at firefox start. Is it possible? I tried to set.

```
String responsiveMode = "{"+"\"key\":\"800x600\",\n"+"\"name\":\"POS Terminal\",\n"+"\"width\":800,\n"+"\"height\": 600"+"}";
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("devtools.responsiveUI.presets", responsiveMode);
```
But that did not work. Any recommendation?

**Comment by Johnz86** [comment]
Ok, I resolved the issue.

I created this gist. https://gist.github.com/Johnz86/e865a0851c2a255f2902
Used it this way.
```
FirefoxProfile profile = new FirefoxProfile();
FirefoxResponsiveMode.setViewSize(profile, "Mobile Device", 800, 600);
DesiredCapabilities cap = DesiredCapabilities.firefox();
cap.setCapability(FirefoxDriver.PROFILE, profile);
DRIVER = new FirefoxDriver(cap);
DRIVER.manage().window().maximize();
FirefoxResponsiveMode.pressShortcut(DRIVER);
```
It would be nice, if there was a feature like this in future selenium for all browsers.

**Comment by pkraju27** [comment]
the above solution is not working for latest firefox browser
