### ISSUE TITLE
[bidi] BiDi session creation, sending a command and allow adding event listeners

### ISSUE THREAD

**Issue by pujagani** [SeleniumHQ/selenium#11762]
To enable BiDi, when a WebDriver session is created, the request capabilities need to send “webSocketUrl” as true. This will be interpreted by the WebDriver based on the [BiDi protocol connection](https://w3c.github.io/webdriver-bidi/#establishing) process and it will return a WebSocket address in the returned capabilities. 

 The WebSocket address is present “webSocketUrl” capability returned by the browser and that can be used to create a WebSocket connection. 
Once the WebSocket connection is created, then internal APIs to send BiDi commands, subscribe to an event and unsubscribe to an event need to be added. These APIs will be used to implement future user-friendly APIs.

Refer
https://docs.google.com/document/d/1dCd8Y2PYaR5mOGSmNTwllEHNmFqegfoGkP-TCKvPzSU/edit?usp=sharing for the API design.

**Comment by pujagani** [comment]
Java implementation: https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/bidi/BiDi.java, https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/bidi/Connection.java

JS implementation: https://github.com/SeleniumHQ/selenium/commit/3f706707d04adfcdfa44cec2068af689c81a968c

Ruby implementation: https://github.com/SeleniumHQ/selenium/commit/e89eb141aec829af773c7226f8b1c20627146609

**Comment by noomorph** [comment]
@pujagani, if I may ask, does Selenium Hub/Node (nowadays) support **relaying** BiDi traffic? I mean

```
user ←→
(hub) ws://example.com/wd/hub/session/a06dd734-3fe4-4da7-bb6c-2901c8d82c3a/ws  ←→
(node) ws://selenium.node/session/a06dd734-3fe4-4da7-bb6c-2901c8d82c3a/ws ←→
(relay node) ws://localhost:4723/session/a06dd734-3fe4-4da7-bb6c-2901c8d82c3a/ws
```

Thanks in advance!

**Comment by pujagani** [comment]
Yes, it does.

**Comment by pujagani** [comment]
I am closing this issue since tracking everything in one place is easier. Please refer to the [Selenium BiDi tracker](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing) to see the current status.
