### ISSUE TITLE
[🐛 Bug]: IE with in Edge is not working in g=headless

### ISSUE THREAD

**Issue by Gowtham7707** [SeleniumHQ/selenium#11761]
### What happened?

when I running the testcase in IE browser. simultaneously i working another activities(like eclipse) the browser is interrupting, So I implemented Headless mode but its not working IE .
I tried to chrome and edge is working headless mode can you please suggest how to run the IE browser in backend.

### How can we reproduce the issue?

```shell
private static WebDriver configureEdgeDriver() {
		/*
		 * Code for setting Edge webdriver
		 */
		WebDriver edgeDriver;
		EdgeOptions options = new EdgeOptions();
		String headLess = AppConfig.getConfig().get("headlessMode");
		if (headLess != null && "true".equalsIgnoreCase(headLess)) {
			options.addArguments("headless");

		}
        //  DesiredCapabilities capabilities = new DesiredCapabilities();
		//	options.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
		//	options.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		//	capabilities.acceptInsecureCerts();
		//	options.merge(capabilities);
		    options.setAcceptInsecureCerts(true);
		  String driverPath = AppConfig.getConfig().get("driverPath");
			 if(driverPath != null) {
					System.setProperty(AutomationConstants.EDGE_DRIVER, driverPath);
		   }else {
				WebDriverManager.edgedriver().setup();
		   }
		edgeDriver = new EdgeDriver(options);
		edgeDriver.manage().timeouts().implicitlyWait(Duration
				.ofSeconds(Integer.parseInt(AppConfig.getConfig().get(AutomationConstants.WAIT_TIME_IN_SECONDS))));
		edgeDriver.manage().window().maximize();
		return edgeDriver;

	}
```

### Relevant log output

```shell
NA
```

### Operating System

windows 10

### Selenium version

Selenium-4.8.1

### What are the browser(s) and version(s) where you see this issue?

edge 110

### What are the browser driver(s) and version(s) where you see this issue?

IE driver 32 bit

### Are you using Selenium Grid?

Selenium-4.8.0

**Comment by diemol** [comment]
I am not sure that is supposed to work. I believe IE Mode in Edge needs the full browser. I will leave some links below so you can ask the Edge developers.

**Comment by Gowtham7707** [comment]
This issue has been determined by IE mode in Edge
