### ISSUE TITLE
[bidi] Implement user-friendly APIs for log module events

### ISSUE THREAD

**Issue by pujagani** [SeleniumHQ/selenium#11763]
Implement user-friendly APIs as described in https://docs.google.com/document/d/1dCd8Y2PYaR5mOGSmNTwllEHNmFqegfoGkP-TCKvPzSU/edit#heading=h.drkbkldsqznk to implement the log module described in W3C BiDi spec https://w3c.github.io/webdriver-bidi/#module-log

**Comment by pujagani** [comment]
Java implementation: https://github.com/SeleniumHQ/selenium/tree/trunk/java/src/org/openqa/selenium/bidi/log, https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/bidi/LogInspector.java

JS implementation: https://github.com/SeleniumHQ/selenium/commit/3f706707d04adfcdfa44cec2068af689c81a968c

Ruby implementation: https://github.com/SeleniumHQ/selenium/commit/12f0d192662a15b5dcacda399762fab83975ebd0, https://github.com/SeleniumHQ/selenium/commit/e2d160b904261cb0185970aec3758e869558d754

**Comment by diemol** [comment]
Closing the browser was requested in https://github.com/SeleniumHQ/selenium/issues/11933, but it is already being tracked here.

**Comment by ollie-iterators** [comment]
More information on the browser close command was added to webdriver-bidi in this PR: https://github.com/w3c/webdriver-bidi/pull/286

**Comment by pujagani** [comment]
I am closing this issue since tracking everything in one place is easier. Please refer to the [Selenium BiDi tracker](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing) to see the current status.
