### ISSUE TITLE
webdriver.getCurrentUrl   throw a exception[🐛 Bug]: 

### ISSUE THREAD

**Issue by LiHaiYuan0606** [SeleniumHQ/selenium#11774]
### What happened?

An exception occurred when I used the getcurrentUrl interface

### How can we reproduce the issue?

```shell
if(!pluginOpen.isSucess()){
            return pluginOpen;
        }
        final String currentUrl = driver.getCurrentUrl();
        //登录页面
        if(StringUtils.equalsIgnoreCase(currentUrl, LocalContant.loginUrl )){
            //跳转到登录页面
            return login(driver);
        }
        //已经登录了
        if(StringUtils.equalsIgnoreCase(currentUrl, LocalContant.homeUrl )){
            return TaskCompleteModel.ok("登录成功");
        }
```

### Relevant log output

```shell
ChromeDriver was started successfully.
org.openqa.selenium.WebDriverException: unknown error: Runtime.evaluate threw exception: Error: LavaMoat - property "swb_bdoWpoasnfa93pfcPOmcfL_Promise" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11200:17)
  at callFunction (<anonymous>:443:26)
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:677)
  at <anonymous>:460:23
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:677)
  at <anonymous>:461:3
  (Session info: chrome=105.0.5195.147)
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [9b6c092513dfa44a0ac64e0886583949, getCurrentUrl {}]
```

### Operating System

win10

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome 105

**Comment by diemol** [comment]
The error is wrapped in a `WebDriverException` but the error does not seem to come from Selenium, rather a 3rd party dependency. Seems you have an extender framework with custom code. 

If you can provide a way to reproduce the issue only using Selenium dependencies, we'd be happy to have a look.

**Comment by LiHaiYuan0606** [comment]
> The error is wrapped in a `WebDriverException` but the error does not seem to come from Selenium, rather a 3rd party dependency. Seems you have an extender framework with custom code.
> 
> If you can provide a way to reproduce the issue only using Selenium dependencies, we'd be happy to have a look.

I use Selenium to test Metamarsk, call Selenium's getcurrentUrl interface, and then report an erro

**Comment by diemol** [comment]
Still, we need a way to reproduce the issue with Selenium and without external dependencies.

**Comment by iamxiaojianzheng** [comment]
可能跟你启动的chrome浏览器中包含的插件有关系，chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn

**Comment by LiHaiYuan0606** [comment]
> 可能跟你启动的chrome浏览器中包含的插件有关系，chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn

是的，小狐狸插件，这个插件现在用不了了

**Comment by LiHaiYuan0606** [comment]
> reproduce



> Still, we need a way to reproduce the issue with Selenium and without external dependencies.

reproduce step：
1. Install the Metamask plug-in on the browser，Chrome App Store：
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

2. Then open the Metamask using Selenium, code:

        System.setProperty("webdriver.chrome.driver", "webdriverPath");
        System.setProperty("webdriver.chrome.silentOutput", "true");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setExperimentalOption("debuggerAddress", "127.0.0.1:8080" );
        chromeOptions.addArguments("−−lang=en-US");
        final ChromeDriver driver = new ChromeDriver(chromeOptions);
        // open Metamask
        driver.get("chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#onboarding/welcome");
        //  here throw exception
       String url =  driver.getCurrentUrl();

**Comment by diemol** [comment]
Then the issue is related to the plug-in, not Selenium itself. Can you reproduce the issue only with Selenium?

**Comment by Lsc0707** [comment]
你解决了嘛，我也遇见了这个问题

**Comment by Lsc0707** [comment]
> 那么问题出在插件上，而不是Selenium本身。您能否仅使用 Selenium 重现该问题？
This seems to be because the page added a LavaMoat this JS module, this module can be anti-crawler, and currently do not see any good solution.

**Comment by Lsc0707** [comment]
> 那么问题出在插件上，而不是Selenium本身。您能否仅使用 Selenium 重现该问题？

![image](https://user-images.githubusercontent.com/34431400/226115203-0a087217-2103-4c1a-a657-331fc19cc5d8.png)

**Comment by diemol** [comment]
Seems this happens when that plugin is being used, please reach out to the maintainers of that project.

**Comment by LiHaiYuan0606** [comment]
> 你解决了嘛，我也遇见了这个问题

没解决，尝试了很多方法，都失败了
