### ISSUE TITLE
[🚀 Feature]: Support passing Pathname objects for preference values in Ruby

### ISSUE THREAD

**Issue by md5** [SeleniumHQ/selenium#11771]
### Feature and motivation

After spending some time trying to track down why my `download.default_directory` preference for Chrome was not being honored, I determined that the issue was that I was passing a `Pathname` object instead of a `String` (via `Rails.root.join`). It would be great if the Ruby bindings honored `Pathname` objects by automatically calling `#to_s` on them. Barring that, it should at least error out instead of silently dropping the preference.

### Usage example

```ruby
options = Selenium::WebDriver::Chrome::Options.new
options.add_preference(
  :download,
  prompt_for_download: false,
  directory_upgrade: true,
  default_directory: Rails.root.join('tmp', 'capybara-downloads')
)
```

Currently, I have to pass `Rails.root.join('tmp', 'capybara-downloads').to_s` to get this to work.

**Comment by titusfortner** [comment]
So, the driver wants JSON, and Selenium is converting the provided Hash into JSON. `Pathname` is not a valid JSON data type. I guess we *could recursively parse everything and call `#to_s` for everything that isn't valid JSON type, but tbh this really should be responsibility of the user.

**Comment by p0deje** [comment]
Are you sure that it's `Pathname` used? I've just tried locally and it seems to convert to string correctly:

```ruby
options = Selenium::WebDriver::Chrome::Options.new
options.add_preference(
  :download,
  prompt_for_download: false,
  directory_upgrade: true,
  default_directory: Pathname.new('/foo/bar')
)
Selenium::WebDriver.logger.level = :debug
driver = Selenium::WebDriver.for(:chrome, options: options)
...
2023-03-15 09:02:36 INFO Selenium -> POST session
2023-03-15 09:02:36 INFO Selenium    >>> http://127.0.0.1:9515/session | {"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"prefs":{"download":{"prompt_for_download":false,"directory_upgrade":true,"default_directory":"/foo/bar"}}}}}}
```

**Comment by md5** [comment]
> Are you sure that it's `Pathname` used? I've just tried locally and it seems to convert to string correctly

Perhaps not? I was definitely seeing `default_directory` omitted when I called `options.to_json` and it stopped being an issue when I called `#to_s` on the `Pathname`, but your test looks valid. The implementation of `#as_json` for `Pathname` also clearly just calls `#to_s`: https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/json.rb#L230-L234

That code is unchanged since at least Rails 5.1.0... So I guess I'll close this issue as invalid. There was definitely something weird going on, but I'm not sure anymore what it was.
