### ISSUE TITLE
[🚀 Feature]: Add Option to FirefoxDriver to log geckodriver.exe output into a file or null in C#

### ISSUE THREAD

**Issue by RoDo777** [SeleniumHQ/selenium#11772]
### Feature and motivation

With an additional property like "LogfileName" it would be possible to put the marionette output into a file or away at all.

**firefoxService.LogfileName = "marionette.log";** or
**firefoxService.LogfileName = "null";**

Seleniumtest for Chrome, Edge and Firefox in Azure Devops run very fine. You also get a good logging while the test is running and at the end for all the scenarios.

**But:** Firefox logfiles are very inflated, because the geckodriver speaks to marionette, which itself controls the firefox browser session.

This inflated logfiles makes it difficult to see real problems, a lot is unimportant stuff like:
```
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Not ...
console.error: (new TypeError("NetworkError: Network request failed", "resource://services-s
```

### Usage example

It is possible to run geckodriver already before the Selenium tests are starting, like:
`geckodriver.exe --binary "C:\Program Files\Mozilla Firefox\firefox.exe" --log fatal >geckolog.txt`
And, as you see, you can redirect the output into a file.

**So if you put " > {{LogfileName}} at the end of the geckodriver.exe commandline**, it would work the same.
In the moment there is no way to do this (I checked the WebDriver.dll via JustDecompile)

```
FirefoxDriverService firefoxService = FirefoxDriverService.CreateDefaultService();
firefoxService.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";
firefoxService.LogfileName = "geckolog.txt";
```

**So it looks for Firefox:**
![Anmerkung 2023-03-14 211538](https://user-images.githubusercontent.com/7480355/225126058-a25742c7-e83f-4b56-aaaa-3eaf249c0366.png)

**And so clean for Chrome (and also Edge):**
![Anmerkung 2023-03-14 212000](https://user-images.githubusercontent.com/7480355/225126970-43f011d9-42b9-433f-9ff5-3fdf897ade3e.png)

**Comment by titusfortner** [comment]
This functionality exists!

I actually just wrapped it in my new logger jar: https://github.com/titusfortner/selenium-logger (which I mainly wrote to filter out all the logging that isn't useful for Selenium debugging).

To do it without my jar, you just need to set a System property for `FirefoxDriver.SystemProperty.BROWSER_LOGFILE` with the path of the filename or `"/dev/null"`. I do want to change some of how this works (#11410 & #11643) because right now Firefox only allows changing the log level in the Options class, even though it is essentially inaccessible when executed remotely because it gets output to the grid console or to a file on the remote system, so this may change in the future.

If you decide to use my wrapper jar, please let me know how well it works for you or if there is more functionality you want to see.

**Comment by titusfortner** [comment]
@RoDo777 I just updated the README in my project to make the geckodriver pieces more clear.

**Comment by RoDo777** [comment]
> This functionality exists!
> 
> I actually just wrapped it in my new logger jar: https://github.com/titusfortner/selenium-logger (which I mainly wrote to filter out all the logging that isn't useful for Selenium debugging).

Thank you for your quick answer. But as you see on my code lines, I work with Selenium in C#.
I dont know how to set FirefoxDriver.SystemProperty.BROWSER_LOGFILE in my C# code.

I read about this .SystemProperty.BROWSER_LOGFILE in some posts, but it's about Java.
Where or what does it change? Can I put it in the registry (Windows)

I decompiled the WebDriver.dll and there is no option to set a 'BROWSER_LOGFILE' 

```
     FirefoxDriverService firefoxService = FirefoxDriverService.CreateDefaultService();
     firefoxService.LogLevel = FirefoxDriverLogLevel.Fatal;
     firefoxService.SuppressInitialDiagnosticInformation = true;
     firefoxService.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";
     ...
     var fireFoxOptions = new FirefoxOptions
     {
      AcceptInsecureCertificates = true,
      Profile = profile,
      UnhandledPromptBehavior = UnhandledPromptBehavior.Dismiss,
      LogLevel = FirefoxDriverLogLevel.Fatal
     };
     fireFoxOptions.AddAdditionalOption("marionette.log.level", "Fatal");
     fireFoxOptions.AddAdditionalOption("remote.log.level", "Fatal");

    Current = new FirefoxDriver(firefoxService, fireFoxOptions);
```

**Comment by RoDo777** [comment]
@titusfortner
Hi Titus,
as my code is in C# and your (good) solution is for Java, I would kindly ask you to re-open the [Feature] request.

I tried to set environment variables, because  I read this can be used as a Java SystemProperties equivalent.
But to no effect.

Kind regards from Munich, Germany

```
   System.Environment.SetEnvironmentVariable("BROWSER_LOGFILE", @"C:\__tmp\geckodriver.log");
   System.Environment.SetEnvironmentVariable("FirefoxDriver.BROWSER_LOGFILE", @"C:\__tmp\geckodriver.log");

```

**Comment by diemol** [comment]
I added the Java label because I assumed it was Java. I will reopen so this can be considered.

**Comment by titusfortner** [comment]
Gah, I saw Java, and I'm like, YES!

Right, unlike chromedriver, geckodriver does not have the ability to set the log location as an CLI argument. This could be a geckodriver feature request...

I really don't like solving this kind of problem with System Properties / Environment Variables, even though my jar makes use of them in Java. ☹️ 

Does changing log level to fatal work for removing them from console at least?

Looks like we can change where output is sent with:
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput

Any chance you want to try to implement something and make a PR?
Looks like we'd want to add support here: https://github.com/SeleniumHQ/selenium/blob/selenium-4.8.0/dotnet/src/webdriver/DriverService.cs#L276

**Comment by RoDo210765** [comment]
> Right, unlike chromedriver, geckodriver does not have the ability to set the log location as an CLI argument. This could be a geckodriver feature request...

As you see, it is easy just output to a file with  x.exe > xoutput.log
So this would be enough for me and the rest. To get changes in the geckodriver .. oh no .. waiting for month and years

> Does changing log level to fatal work for removing them from console at least?


I get lesser info, of course. Look at the screenshot below, output into a file ..

> Looks like we can change where output is sent with: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput

Also interesting, but the output with > logfile.log is easy, stable and state of the art.

> Any chance you want to try to implement something and make a PR? Looks like we'd want to add support here: https://github.com/SeleniumHQ/selenium/blob/selenium-4.8.0/dotnet/src/webdriver/DriverService.cs#L276
Thank you for the offer, but I dont have the energy in these times ;-) 
I'm not quite sure what this DriverService is about. Is this inside the Selenium Manager Project?
I am so happy that our environment with Azure DevOps runs smooth and stable.
OK, sometimes there is an older browser on the server who executes the tests, but it is managable.

So, thanks for answering me, is a pleasure to 'meet' you ;-) 


### Here in Process Explorer
You see, started in a cmd.exe, runs fine and outputs to geckodriver.log ...
![geckodriver_on_commandline_cmdbox](https://user-images.githubusercontent.com/128001949/225762053-bebe3b21-5b6c-4bb2-8bd3-fbf1ef6dedba.png)

### You dont see the output here ..
![geckodriver_on_commandline_ProcessExplorer](https://user-images.githubusercontent.com/128001949/225762064-82873e25-15d6-4431-953e-56fb9e5244be.png)

### And here some output from marionette which I really dont want to see in my Azure DevOps logfiles
![geckodriver_on_commandline_geckologTXTinNPP](https://user-images.githubusercontent.com/128001949/225762059-abce9c8f-c2bb-44cb-a38a-24d597778a18.png)

**Comment by titusfortner** [comment]
Mozilla is often pretty responsive to changes, and months/years is probably where we're at with a lot of Selenium .NET changes right now due to lack of resources. 

Even if we appended `<logfile.txt` we'd need to figure out how to wire it in, and I'm not sure that's the right solution. Like, if I want to redirect to null instead of a file, it's different depending on platform and shell. This feels like it should be a .NET solution which accounts for this, and not a CLI solution.

**Comment by titusfortner** [comment]
I'm going to close this in favor of #12273 since that will address this.
