### ISSUE TITLE
[🐛 Bug]: Selenium Manager is not able to run the driver: Access is denied (5)

### ISSUE THREAD

**Issue by morepizza** [SeleniumHQ/selenium#11770]
### What happened?

 New Java Project on IntelliJ. Add pom.xml, add reference to Selenium 4.6.0. Added a line of code to initialize the ChromeDriver:

`WebDriver driver = new ChromeDriver();`

Running the program I get the following warning:

```bash
> org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\x\AppData\Local\Temp\selenium-manager35099502931610012782250760965258608\selenium-manager.exe, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver
```

and after that the exception:

```bash
> Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:128)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:49)
	at Main.main(Main.java:23)
```

When I check the temporary path `C:\Users\x\AppData\Local\Temp\selenium-manager35099502931610012782250760965258608\` I found that it doesn't exists.

If I use setProperty(), providing the path, the application works.

I also changed to Selenium 4.8.1, the same results.

### How can we reproduce the issue?

Create a new IntelliJ Java Project. Add support for Maven. Add a reference to Selenium 4.8.1:

```xml
 <dependency>
     <groupId>org.seleniumhq.selenium</groupId>
     <artifactId>selenium-java</artifactId>
     <version>4.8.1</version>
 </dependency>
```

This is the code:

```java
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Main {
    public static void main(String[] args)  {

        WebDriver driver = new ChromeDriver();

        driver.get("https://www.selenium.dev/selenium/web/web-form.html");
        driver.quit();
    }
}
```

### Relevant log output

```shell
mar. 14, 2023 11:21:17 A.M. org.openqa.selenium.manager.SeleniumManager runCommand
WARNING: IOException running command [C:\Users\x\AppData\Local\Temp\selenium-manager3860664272300009403156937473061734\selenium-manager.exe, --driver, chromedriver]: Cannot run program "C:\Users\x\AppData\Local\Temp\selenium-manager3860664272300009403156937473061734\selenium-manager.exe": CreateProcess error=5, Access is denied
mar. 14, 2023 11:21:17 A.M. org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: The driver executable must exist: C:\Users\x\IdeaProjects\untitled
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:149)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:42)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:315)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:456)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:147)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
	at Main.main(Main.java:7)
```

### Operating System

Windows 11

### Selenium version

Java 17.0.6

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111.x

**Comment by krmahadevan** [comment]
@morepizza 

>  org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\x\AppData\Local\Temp\selenium-manager35099502931610012782250760965258608\selenium-manager.exe, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver

You mention that you are on `4.8.1` but the version that is being shown in the above warning states that you are on `4.6.0` Can you please cross check this ? 

Also can you please check if the user that is running the test is the same as the current user ? I ask this because it looks like Selenium was not able to extract the `selenium-manager.exe` executable to the temporary directory from the jars that is available in the CLASSPATH.

**Comment by morepizza** [comment]
Yes, there are two outputs in my submission , one for `4.6.0`  (the first one) and the other one is for `4.8.1`. It's the same behavior.

Yes, it's the same user that is running the tests.

If I run IntelliJ as Administrator (right click on icon and `Run as administrator`), everything works fine.

**Comment by krmahadevan** [comment]
> If I run IntelliJ as Administrator (right click on icon and Run as administrator), everything works fine.

Maybe you need to check if the current user has permissions to write into the temp folder.

**Comment by morepizza** [comment]
Yes, with the current user I have the write permission in the temp folder. The current user is in the `Administrators` group and the IntelliJ and java run with the same user (current user).

**Comment by krmahadevan** [comment]
@morepizza - I am a bit confused here.
You say that the current user is part of the admin group and it has write permission into the temp folder. But when you run your tests by spawning IntelliJ as the current user, it fails because it cannot write into the temp folder.

You also mention that if you spawn IntelliJ as an administrator and then run the tests, then it works fine.

So it kind of hints that there's nothing that could be wrong at Selenium level, but perhaps the permissions issue is at your desktop/laptop.

Can you please try passing a different temp directory location (maybe a sub directory under your home directory wherein you know you can write into)  as explained [in this stackoverflow post](https://stackoverflow.com/a/1924159) and see if that works ?

**Comment by morepizza** [comment]
I made the following tries:
1. added `java -Djava.io.tmpdir=/path/to/tmpdir` in` Run Configurations`. Nothing changed
2. added `TMP=c:\temp;TEMP=c:\temp` in `Environment Variables` from the same Window. The file `selenium-manager.exe` was saved in that folder, but I have another exception:

`Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'xxxx', ip: 'xxxx'
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
	at Main.main(Main.java:14)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:218)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:98)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 6 more`

3. run as administrator, same setup as 2. Everything was working. I looked at the chromedriver.exe path and it was `C:\Users\x\.cache\selenium\chromedriver\win32\111.0.5563.64`.  Here **x** is my user account with administrative rights (full).

**Comment by titusfortner** [comment]
Right now the Java bindings are extracting Selenium Manager executable from the jar into a temporary directory and executing it to get the driver. The user executing Selenium commands needs to be able to execute from a temporary directory.

The only way for Selenium to address this, I think is to do #11359 where we'd copy the executable into the home directory which the user is more likely to have permissions.

Otherwise, permission management is the responsibility of the user.

**Comment by pandoras-toolbox** [comment]
I wrongly assumed it has to do with WebDriverManager. Is this the same issue here like I have described at https://github.com/bonigarcia/webdrivermanager/issues/1022
?

**Comment by bonigarcia** [comment]
I think the relevant trace is the one you reported on the WebDriverManager issue tracker:

```
WARNING: IOException running command [C:\Users\ANDYEN~1.TOG\AppData\Local\Temp\selenium-manager1180539304300395707346508903209\selenium-manager.exe, --browser, chrome, --output, json]: Cannot run program "C:\Users\ANDYEN~1.TOG\AppData\Local\Temp\selenium-manager1180539304300395707346508903209\selenium-manager.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator
```

It seems the execution of the `selenium-manager.exe` binary is blocked due your group policy. However, that this policy can be changed to allow the execution of that binary. See for example this [page](https://www.minitool.com/news/this-program-is-blocked-by-group-policy.html).

Alternatively, you can continue using WebDriverManager:

```
WebDriverManager.chromedriver().setup();
WebDriver driver = new ChromeDriver();
```
