### ISSUE TITLE
[🐛 Bug]: The Grid has no registered Nodes yet

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#11778]
### What happened?

selenium/hub always The Grid has no registered Nodes yet

### How can we reproduce the issue?

```shell
1. run command : docker pull selenium/hub
2. run command : docker pull selenium/node-chrome
3. run command :  docker network create gridnetwork
4. run command : docker run -d -p 4445:4444 --net gridnetwork --name seleniumHub selenium/hub
5. open browser and input http://localhost:4445
```

### Relevant log output

```shell
not available
```

### Operating System

Windows 11

### Selenium version

Selenium Grid 4.8.1 

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Version 111.0.5563.65

### Are you using Selenium Grid?

yes

**Comment by diemol** [comment]
Please follow the docs to get a Grid up and running https://github.com/SeleniumHQ/docker-selenium#hub-and-nodes
