### ISSUE TITLE
[🚀 Feature]: Request to pass test parameters in Devtools console and validate response on console itself 

### ISSUE THREAD

**Issue by harishtesting01** [SeleniumHQ/selenium#11786]
### Feature and motivation

Automating pass test parameters in Devtools console and validate response on console itself 

### Usage example

Passing access tokens and customer id in devtools console and validating the response

**Comment by diemol** [comment]
Not really understanding the request. Can you elaborate and explain better with a real life use case to understand better, please?

**Comment by harishtesting01** [comment]
when I check on BIDI API( CDP implementation) to automate Chrome Dev tools feature .
https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/
It supports only Geo location and Performance logs but additionally I am looking to provide support for passing parameters in chrome dev tools console and validating the response in a automated way.

This use case is automatable using tool called Tosca but could not see a approaching solution using selenium.
<img width="1792" alt="Screenshot 2023-03-17 at 3 40 00 PM" src="https://user-images.githubusercontent.com/120575327/225875723-68b072fe-5300-457a-8f0b-b4d6e868750c.png">

**Comment by diemol** [comment]
The CDP implementation provides some wrappers for common use cases, however you can also access the method to send anything you want to CDP based on https://chromedevtools.github.io/devtools-protocol/. 

Please keep in mind that in the future CDP will be removed and only BiDi will remain, If you have a specific use case not covered in BiDi, please post it https://github.com/w3c/webdriver-bidi

**Comment by diemol** [comment]
Closing, we did not get more information.
