### ISSUE TITLE
[🐛 Bug]: Cannot modify Chrome downloads directory

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#11787]
### What happened?

Since March, 1st, 2023 our Selenium tests run on Chrome in headless mode fail because the setting of a download directory for the browser stopped working and the files started being downloaded to the folder set in the browser. 
You can file the node log attached 
[node.log](https://github.com/SeleniumHQ/selenium/files/11000218/node.log)

### How can we reproduce the issue?

```shell
The ChromeOptions hat we used to set were the ones listed below. We tried replacing the headless argument with options.addArguments("--headless=old"); and options.addArguments("--headless=new"); but the issue was not resolved.
ChromeOptions options = new ChromeOptions(); 
    	options.addExtensions(getClearDownloadsExtension());
    	options.addArguments("disable-infobars"); 
    	if (headless) {
    		options.addArguments("ignore-certificate-errors");
    		options.addArguments("no-sandbox");
    		options.addArguments("disable-dev-shm-usage");
    		options.addArguments("headless");
    		options.addArguments("window-size=1580,1280");
    		options.addArguments("disable-extensions");
    		options.addArguments("disable-gpu");
    		options.setExperimentalOption("useAutomationExtension", false);
    	}
    	Map<String, Object> prefs = new HashMap<String, Object>();
    	prefs.put("download.default_directory", downloadDir);
    	prefs.put("credentials_enable_service", false);
    	prefs.put("profile.password_manager_enabled", false);
    	options.setExperimentalOption("prefs", prefs);
    	capabilities.setCapability(ChromeOptions.CAPABILITY, options);
    	return getRemoteDriver(serverURL, capabilities);
```

### Relevant log output

```shell
Node log is attached in the What happened? part
```

### Operating System

Windows, Linux

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome Version: 111.0.5563.65

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver version:  111.0.5563.64

### Are you using Selenium Grid?

Selenium grid 4

**Comment by diemol** [comment]
Please have a look at https://www.selenium.dev/blog/2023/headless-is-going-away/. If you are still having issues with Headless, please report them to Chrome. I will leave some links below for that.
