### ISSUE TITLE
[🐛 Bug]:  Edge IE Mode tests stopped working with selenium version 4.8.1

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#11784]
### What happened?

Edge IE Mode tests stopped working with selenium version 4.8.1

Edge IE mode works fine using 4.8.0 using edge 110 and 111.

Have the implementation changed for 4.8.1?

### How can we reproduce the issue?

```shell
InternetExplorerOptions options = new InternetExplorerOptions();
options.attachToEdgeChrome();
options.withEdgeExecutablePath("C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe");   
options.setCapability("platformName", "WIN10");   
options.setCapability("browserVersion", "11");	        
options.setCapability("requireWindowFocus", true);
options.setCapability("ie.ensureCleanSession", true);
options.setCapability("ignoreZoomSetting", true);
options.setCapability("nativeEvents", true);
options.setCapability("ignoreProtectedModeSettings", true);
driver = new RemoteWebDriver(new URL(hub_url),options);
driver.manage().window().maximize();

We are running a distributed grid using the default http client.
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: 
Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Could not start a new session. null
```

### Operating System

Windows 10

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge 110, 111

### What are the browser driver(s) and version(s) where you see this issue?

Microsoft Edge Version 111.0.1661.43

### Are you using Selenium Grid?

4.8.1

**Comment by diemol** [comment]
This has been fixed by https://github.com/SeleniumHQ/selenium/commit/ed0fe601775a35432e2492a5d9b0952eb9ce9ed2, which will be release in a couple of days.
