### ISSUE TITLE
[🐛 Bug]: Error in xpath selectors with edge mode IE

### ISSUE THREAD

**Issue by Luciano1689** [SeleniumHQ/selenium#11783]
### What happened?

After migrating selenium web driver from version 3.14 to version 4.8.1 to be able to use edge mode IE. We are having errors in xpath selectors that used to work for us in version 3.14.

I tested with the latest version of firefox and it worked fine.

### How can we reproduce the issue?

```shell
public String validarActividad(ArrayList<Actividad> actividades) throws Exception {
		boolean error=false;
		WebDriverWait wait = new WebDriverWait(driver, ParametrosEjecucion.timeOutElemento);
		wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(byFrame));
		WebElement tabla = driver.findElement(byTablaIntegrantesActividades);
		String aportacion="1";
		List<WebElement> allRows =  tabla.findElements(By.xpath(".//tr[contains(@class,'contTablaCelda')]"));
		for (WebElement row : allRows) { 
			aportacion = row.findElement(By.xpath(".//td[2]/span/span")).getText();			 
		}
		return aportacion;
	}
```

### Relevant log output

```shell
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [b42aae7a-52ff-4116-af1c-15b26a517fa6, findChildElement {id=e1d202a7-9dc6-450c-b47f-39edf9285ca1, using=xpath, value=.//td[2]/span/span}]
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: none, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.edgechromium: true, ie.edgepath: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: , nativeEvents: false, requireWindowFocus: true}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: b42aae7a-52ff-4116-af1c-15b26a517fa6
org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression .//td[2]/span/span because of the following error:
TypeError: El objeto no acepta la propiedad o el método 'each'
For documentation on this error, please visit: https://selenium.dev/exceptions/#invalid_selector_exception
Build info: version: '4.8.1', revision: '8ebccac989'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [b42aae7a-52ff-4116-af1c-15b26a517fa6, findChildElement {id=e1d202a7-9dc6-450c-b47f-39edf9285ca1, using=xpath, value=.//td[2]/span/span}]
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, pageLoadStrategy: none, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.edgechromium: true, ie.edgepath: , ie.ensureCleanSession: false, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: , nativeEvents: false, requireWindowFocus: true}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: b42aae7a-52ff-4116-af1c-15b26a517fa6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:227)
	at pages.gestorTramitesWeb.GestorTramitesWeb2IntegrantesPages.validarActividad(GestorTramitesWeb2IntegrantesPages.java:145)
	at tareas.gestorTramiteWeb.GestorTramiteWeb2Integrantes.validarCargaCamposPantalla(GestorTramiteWeb2Integrantes.java:66)
	at tareas.gestorTramiteWeb.GestorTramiteWeb2Integrantes.ingresoDatos(GestorTramiteWeb2Integrantes.java:97)
```

### Operating System

Windows 10

### Selenium version

Java 1.8 Selenium 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Edge Versión 108.0.1462.54

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 32 bits 4.8.1.0

**Comment by rajeshkumarrobert** [comment]
Mmmm

**Comment by Luciano1689** [comment]
I cannot share the code and for the page it is in an internal network. I tried to reproduce in different page in the web but the error does not appear.

I give you the error that it registers in the webdriver.ie.driver.logfile :
I 2023-03-20 16:47:06:266 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(239) No child frame focus. Focus is on top-level frame
W 2023-03-20 16:47:23:777 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(101) Error response has status code 32 and message 'Unable to locate an element with the xpath expression `.//td[2]/span/span` because of the following error:TypeError: El objeto no acepta la propiedad o el método 'each'' message.

It works in the different drivers, firefox and chrome in the latest version. And also in version 3.14 of selenium with IEServer. But it doesn't work with Edge mode IE.

**Comment by diemol** [comment]
It does not need to be the same page, it can be any page that can be used to reproduce the issue.

**Comment by titusfortner** [comment]
Regardless of why it can't be found, this is the wrong error message from Edge. The selector itself is valid, so it shouldn't throw invalid selector error, and if it can't find the element it should not complain about the method "each." I suspect Edge is giving IE a data type it isn't expecting (or vice versa) can you turn on trace logs for IE?

**Comment by Luciano1689** [comment]
How do I turn on trace logs for edge mode IE?

**Comment by titusfortner** [comment]
```java
InternetExplorerOptions options = new InternetExplorerOptions();
InternetExplorerDriverService service = new InternetExplorerDriverService.Builder().withLogLevel(InternetExplorerDriverLogLevel.TRACE).build();
InternetExplorerDriver driver = new InternetExplorerDriver(options, service)
```

**Comment by Luciano1689** [comment]
This is the log:
T 2023-03-21 17:21:06:617 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(31) Entering Command::Deserialize
D 2023-03-21 17:21:06:617 C:\projects\seleniumhq\selenium\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "findChildElement", "locator" : { "sessionid" : "7fb5271a-b4a7-4611-b389-8bd8200dae03", "id" : "7ce5eecc-98be-48c3-82df-eaaff9a9238d" }, "parameters" : {
  "id": "7ce5eecc-98be-48c3-82df-eaaff9a9238d",
  "using": "xpath",
  "value": ".\u002f\u002ftd[2]\u002fspan\u002fspan"
} }
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(178) Entering IECommandExecutor::OnExecCommand
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(994) Entering IECommandExecutor::DispatchCommand
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(226) Beginning wait for response length to be not zero
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1315) Entering IECommandExecutor::GetCurrentBrowser
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1321) Entering IECommandExecutor::GetManagedBrowser
D 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1012) Checking for alert before executing findChildElement command
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1210) Entering IECommandExecutor::IsAlertActive
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(868) Entering Browser::GetActiveDialogWindowHandle
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(315) Entering Browser::GetContentWindowHandle
D 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1227) No alert handle is found
D 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1059) Executing command: findChildElement
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1315) Entering IECommandExecutor::GetCurrentBrowser
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1321) Entering IECommandExecutor::GetManagedBrowser
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandHandler.cpp(45) Entering IECommandHandler::GetElement
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1625) Entering IECommandExecutor::GetManagedElement
T 2023-03-21 17:21:06:618 C:\projects\seleniumhq\selenium\cpp\iedriver\ElementRepository.cpp(34) Entering ElementRepository::GetManagedElement
T 2023-03-21 17:21:06:626 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1315) Entering IECommandExecutor::GetCurrentBrowser
T 2023-03-21 17:21:06:627 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1321) Entering IECommandExecutor::GetManagedBrowser
T 2023-03-21 17:21:06:627 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(235) Entering Browser::GetDocument
T 2023-03-21 17:21:06:627 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(763) Entering Browser::GetDocumentFromWindow
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1666) Entering IECommandExecutor::LocateElement
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1649) Entering IECommandExecutor::GetElementFindMethod
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\ElementFinder.cpp(43) Entering ElementFinder::FindElement
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1315) Entering IECommandExecutor::GetCurrentBrowser
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1321) Entering IECommandExecutor::GetManagedBrowser
D 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\ElementFinder.cpp(65) Using FindElement atom to locate element having xpath = .//td[2]/span/span
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(235) Entering Browser::GetDocument
T 2023-03-21 17:21:06:630 C:\projects\seleniumhq\selenium\cpp\iedriver\Browser.cpp(763) Entering Browser::GetDocumentFromWindow
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(62) Entering Script::Initialize
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(83) Entering Script::AddArgument(std::wstring)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(118) Entering Script::AddArgument(VARIANT)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(83) Entering Script::AddArgument(std::wstring)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(118) Entering Script::AddArgument(VARIANT)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(112) Entering Script::AddArgument(IHTMLElement*)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(118) Entering Script::AddArgument(VARIANT)
T 2023-03-21 17:21:06:633 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(182) Entering Script::Execute
T 2023-03-21 17:21:06:634 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(634) Entering Script::CreateAnonymousFunction
T 2023-03-21 17:21:06:651 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(575) Entering Script::ConvertResultToJsonValue
T 2023-03-21 17:21:06:651 C:\projects\seleniumhq\selenium\cpp\iedriver\Script.cpp(582) Entering Script::ConvertResultToJsonValue
D 2023-03-21 17:21:06:661 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(105) Result type is JScriptTypeInfo
D 2023-03-21 17:21:06:664 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(105) Result type is JScriptTypeInfo
T 2023-03-21 17:21:06:664 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(449) Entering Script::GetPropertyNameList
D 2023-03-21 17:21:06:666 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(105) Result type is JScriptTypeInfo
D 2023-03-21 17:21:06:667 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(401) -2147352570 [Nombre desconocido.]: Unable to get dispatch ID (dispid) for property toJSON
D 2023-03-21 17:21:06:667 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(325) No toJSON property found on IDispatch
T 2023-03-21 17:21:06:667 C:\projects\seleniumhq\selenium\cpp\iedriver\VariantUtilities.cpp(449) Entering Script::GetPropertyNameList
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(100) Entering Response::SetErrorResponse
W 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(101) Error response has status code 32 and message 'Unable to locate an element with the xpath expression .//td[2]/span/span because of the following error:
TypeError: El objeto no acepta la propiedad o el mÃ©todo 'each'' message
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(94) Entering Response::SetErrorResponse
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(87) Entering Response::SetResponse
D 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1062) Command execution for findChildElement complete
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1315) Entering IECommandExecutor::GetCurrentBrowser
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1321) Entering IECommandExecutor::GetManagedBrowser
T 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(60) Entering Response::Serialize
D 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1127) Setting serialized response to {
	"value" : 
	{
		"error" : "invalid selector",
		"message" : "Unable to locate an element with the xpath expression .//td[2]/span/span because of the following error:\nTypeError: El objeto no acepta la propiedad o el m\u00e9todo 'each'",
		"stacktrace" : ""
	}
}
D 2023-03-21 17:21:06:671 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(1128) Is waiting flag: 0
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\iedriver\IESession.cpp(235) Found non-zero response length
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(201) Entering IECommandExecutor::OnGetResponse
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\iedriver\IECommandExecutor.cpp(641) Entering IECommandExecutor::OnIsSessionValid
D 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(426) Response: {
	"value" : 
	{
		"error" : "invalid selector",
		"message" : "Unable to locate an element with the xpath expression .//td[2]/span/span because of the following error:\nTypeError: El objeto no acepta la propiedad o el m\u00e9todo 'each'",
		"stacktrace" : ""
	}
}
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(479) Entering Server::SendResponseToClient
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\webdriver-server\response.cc(30) Entering Response::Deserialize
T 2023-03-21 17:21:06:678 C:\projects\seleniumhq\selenium\cpp\webdriver-server\server.cc(561) Entering Server::SendHttpBadRequest

**Comment by titusfortner** [comment]
So IEDriver is building a script and executing it in the browser, and the browser does not like executing it.
We'll need to file a bug with Microsoft, but it would be very helpful if we could get a reproducible case.

You're locating a table, then getting a list of rows that contain a value, then getting the text of a nested span.

The code seems weird, though. this rewrites the value for each row, so it's essentially only capturing the last row?
```
		for (WebElement row : allRows) { 
			aportacion = row.findElement(By.xpath(".//td[2]/span/span")).getText();			 
		}
```

At any rate, can you get the text of the whole row? What about just `.//td[2]`? What about `By.css("td:nth-of-type(2) > span > span")`? Can you narrow down which piece is breaking it?

**Comment by Luciano1689** [comment]
The code that I had put was a modification with respect to the original version.

The original code:
```

public boolean validarIntegrantes(ArrayList<PersonaFisica> personasFisica) throws Exception {
		parametros.getLog().getLogger().info("validar integrantes");
		boolean error=false;
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
		wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(byFrame));
		WebElement tabla = driver.findElement(byTablaIntegrantesFisicos);
		List<WebElement> allRows =  tabla.findElements(By.tagName("tr"));
		for (WebElement row : allRows) { 
			int contador = 0;
			String tipoDocumento = row.findElement(By.xpath(".//td[2]/span/span")).getText();
			String pais = row.findElement(By.xpath(".//td[3]//span//span")).getText();
			String nroDocumento = row.findElement(By.xpath(".//td[4]//span//span")).getText();
			String apellidoNombre = row.findElement(By.xpath(".//td[5]/span/span")).getText();
			String relacionLaboral = row.findElement(By.xpath(".//td[6]/span/span")).getText();
			String fechaDesde = row.findElement(By.xpath(".//td[7]/span/span")).getText();
			PersonaFisica persona = personasFisica.get(contador);
			if(!tipoDocumento.equals(String.valueOf(persona.getPersona().getTipoDocumento()))){
				error=true;
			}
			if(!pais.equals(String.valueOf(persona.getPersona().getCodigoPais()))){
				error=true;
			}
			if(!nroDocumento.equals(String.valueOf(persona.getPersona().getNroDocumento()))){
				error=true;
			}
			String apellidoNombreAux = persona.getPersona().getNombre1() +" "+persona.getPersona().getApellido1();				
			if(!apellidoNombre.equals(apellidoNombreAux)){
				error=true;
			}
			if(!relacionLaboral.equals(String.valueOf(persona.getRelacionLaboral()))){
				error=true;
			}
			if(!fechaDesde.equals(tareasAll.convertirFechaAString4(persona.getPersona().getFechaDesde()))){
				error=true;
			}
		}
		driver.switchTo().defaultContent();
		return error;
	}	
```

And the error, when I run with Edge Internet Explorer mode is in the first loop and in the line : 
`String tipoDocumento = row.findElement(By.xpath(".//td[2]/span/span")).getText();`

I did several tests modifying the xpath for example .//td[2] and others and it always gives me the same error.I will try with the css command.

**Comment by iamxiaojianzheng** [comment]
May I ask if you are using ie mode, have you ever been blocked and unable to execute the next step after initializing the driver?

**Comment by titusfortner** [comment]
@iamxiaojianzheng see this article — https://titusfortner.com/2022/09/28/edge-ie-mode.html

**Comment by diemol** [comment]
OK, based on the comments I will leave some links below so you can report this to Microsoft. They need code to actually reproduce the issue.
