### ISSUE TITLE
[🐛 Bug]:   DevToolsActivePort file doesn't exist for ChromeDriver 111 start Windows Chrome 111 (32bit)

### ISSUE THREAD

**Issue by chutang** [SeleniumHQ/selenium#11780]
### What happened?

I am experiencing an issue when attempting to create a Chrome browser session. Initially, the Chrome browser launches successfully, but after a short while, it disappears. When I check the Chrome driver, it displays an error message stating that it is unable to create the session due to an "UnknownError: DevToolsActivePort file doesn't exist."

To provide more information, I have uploaded some screenshots. Could you please review them and help me identify the root cause of this issue? Thank you.
![09_00_15](https://user-images.githubusercontent.com/13866186/225483684-a72e2775-f74c-4310-93af-d363226c1a79.jpg)
![08_59_27](https://user-images.githubusercontent.com/13866186/225483695-67caa6e1-a68f-4ccb-b915-a82982c376cf.jpg)

### How can we reproduce the issue?

```shell
OS : Windows 10  
Selenium server version: 3.141.59 
Chrome driver version: 11.0
Windows Chrome driver version: 111, 32 bit

cat test.bat 
set edgeWebdriver=msedgedriver32bit_106.exe
set chromeWebdriver=chromedriver32bit_111.exe
set firefoxWebdriver=geckodriver_v0.30.0_win64.exe

echo "starting from local host"

start cmd.exe /c "@start /b java.exe -Dwebdriver.edge.driver=".\drivers\%edgeWebdriver%" -Dwebdriver.chrome.driver=".\drivers\%chromeWebdriver%" -Dwebdriver.gecko.driver=".\drivers\%firefoxWebdriver%" -jar selenium-server-standalone-3.141.59.jar -port 4445"


Run test.bat ,
then open : http://localhost:4445 -> create session->choose chrome
```

### Relevant log output

```shell
"UnknownError: DevToolsActivePort file doesn't exist."
Please check screenshot .
```

### Operating System

Windows10

### Selenium version

selenium-server-standalone-3.141.59

### What are the browser(s) and version(s) where you see this issue?

Windows Chrome 111 (32bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDirver 111.0.5563.64

**Comment by chutang** [comment]
Upload log:
Caused by: org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'test', ip: '10.224.34.111', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.12'
Driver info: driver.version: unknown
remote stacktrace: Backtrace:
	(No symbol) [0x00CEDCE3]
	(No symbol) [0x00C839D1]
	(No symbol) [0x00B94DA8]
	(No symbol) [0x00BB44D4]
	(No symbol) [0x00BB0BBF]
	(No symbol) [0x00BAED19]
	(No symbol) [0x00BE15AE]
	(No symbol) [0x00BE129C]
	(No symbol) [0x00BDACC6]
	(No symbol) [0x00BB6F68]
	(No symbol) [0x00BB80CD]
	GetHandleVerifier [0x00F63832+2506274]
	GetHandleVerifier [0x00F99794+2727300]
	GetHandleVerifier [0x00F9E36C+2746716]
	GetHandleVerifier [0x00D96690+617600]
	(No symbol) [0x00C8C712]
	(No symbol) [0x00C91FF8]
	(No symbol) [0x00C920DB]
	(No symbol) [0x00C9C63B]
	BaseThreadInitThunk [0x772300F9+25]
	RtlGetAppContainerNamedObjectPath [0x77617BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77617B8E+238]

**Comment by diemol** [comment]
This is almost always related to the environment where the browser and browser driver are running. There is not much Selenium does around this issue, it just passes options and arguments along. Aside of recommending to upgrade to the most recent Selenium version, I can only share some links below where you can ask questions regarding this issue.

**Comment by chutang** [comment]
Fix this issue after add options.addArguments("--remote-debugging-port=9222");
