### ISSUE TITLE
[🐛 Bug]: Unable to switch to a browser having empty title

### ISSUE THREAD

**Issue by srinukusumanchi** [SeleniumHQ/selenium#11793]
### What happened?

During my testing when I selected a drop-down value in parent window it opens a child window with empty title, Now I want to close child window having empty title but I could not able to close using selenium methods and script is not moving to next line when it executes driver.switchTo().window(window handle)

### How can we reproduce the issue?

```shell
/**
* This function is to switch the driver from Current window to newly opened
* Window
*/
public Boolean switchToWindow(String windowNames) {
boolean flag = false;
String parentWindow = webDriver. getWindowHandle() ;
String[] windows = windowNames.split( regex: "|\|");
for (String window : windows) {
for (String windowHandle: webDriver. getwindowHandles()) {
try {
String title = webDriver.switchTo() .window(windowHandle) .getTitle);
if (title.contains (window)) {
webDriver.switchTo().window(windowHandle);
flag = true;
break;
else {
webDriver.switchTo().window(parentWindow);
}
} catch (NoSuchWindowException e) {
throw new NoSuchWindowexception("Unable to switch the window");
}
if(flag)break;
}
return flag;
}
```

### Relevant log output

```shell
Logs are not displayed as script unable to move to next line when it executes driver.switchTo().Window(empty window string);
```

### Operating System

Windows 10

### Selenium version

Java-8

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver - 111.XXX

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
But your code is what is checking for the titles.

Selenium essentially requires you to get the current window handle, then get the list of active handles, then switch to the handle that is not the current handle.

**Comment by srinukusumanchi** [comment]
> ### What happened?
> 
> During my testing when I selected a drop-down value in parent window it opens a child window with empty title, Now I want to close child window having empty title but I could not able to close using selenium methods and script is not moving to next line when it executes driver.switchTo().window(window handle)
> 
> ### How can we reproduce the issue?
> 
> ```shell
> /**
> 
> * This function is to switch the driver from Current window to newly opened
> 
> * Window
> 
> */
> 
> public Boolean switchToWindow(String windowNames) {
> 
> boolean flag = false;
> 
> String parentWindow = webDriver. getWindowHandle() ;
> 
> String[] windows = windowNames.split( regex: "|\|");
> 
> for (String window : windows) {
> 
> for (String windowHandle: webDriver. getwindowHandles()) {
> 
> try {
> 
> String title = webDriver.switchTo() .window(windowHandle) .getTitle);
> 
> if (title.contains (window)) {
> 
> webDriver.switchTo().window(windowHandle);
> 
> flag = true;
> 
> break;
> 
> else {
> 
> webDriver.switchTo().window(parentWindow);
> 
> }
> 
> } catch (NoSuchWindowException e) {
> 
> throw new NoSuchWindowexception("Unable to switch the window");
> 
> }
> 
> if(flag)break;
> 
> }
> 
> return flag;
> 
> }
> ```
> 
> 
> ### Relevant log output
> 
> ```shell
> Logs are not displayed as script unable to move to next line when it executes driver.switchTo().Window(empty window string);
> ```
> 
> 
> ### Operating System
> 
> Windows 10
> 
> ### Selenium version
> 
> Java-8
> 
> ### What are the browser(s) and version(s) where you see this issue?
> 
> Chrome 111
> 
> ### What are the browser driver(s) and version(s) where you see this issue?
> 
> Chrome driver - 111.XXX
> 
> ### Are you using Selenium Grid?
> 
> No

Can you confirm is there any way to handle browser with empty title?

**Comment by titusfortner** [comment]
Selenium supports switching to windows by handle, not by title. I'll add links for where to ask about how to wrap the method calls to use titles.
