### ISSUE TITLE
[🐛 Bug]: Use the actions.dragAndDropBy method to report an error in headless mode

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/selenium#11799]
### What happened?

I would like to ask whether the drag operation cannot be performed in headless mode?

### How can we reproduce the issue?

```shell
move target out of bounds (Session info: headless chrome=94.0.4606.81)
```

### Relevant log output

```shell
None
```

### Operating System

Windows 10

### Selenium version

Java 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 94.0.4606.81

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 94.0.4606.113

**Comment by titusfortner** [comment]
Out of bounds error means you are trying to either the draggable element is outside of the viewport, or the droppable element is outside the viewport. If it works non-headless, check to make sure that your window size is large enough in headless mode. Take a screenshot and see what it looks like?

**Comment by iamxiaojianzheng** [comment]
> Out of bounds error means you are trying to either the draggable element is outside of the viewport, or the droppable element is outside the viewport. If it works non-headless, check to make sure that your window size is large enough in headless mode. Take a screenshot and see what it looks like?

Thank you for your reminder, and I would also like to ask whether the selenium doc provides relevant documentation on which parameters can be used in the addArguments method?

**Comment by iamxiaojianzheng** [comment]
> > Out of bounds error means you are trying to either the draggable element is outside of the viewport, or the droppable element is outside the viewport. If it works non-headless, check to make sure that your window size is large enough in headless mode. Take a screenshot and see what it looks like?
> 
> Thank you for your reminder, and I would also like to ask whether the selenium doc provides relevant documentation on which parameters can be used in the addArguments method?

For example these codes
```java
DEFAULT_OPTIONS.addArguments("--headless=new");
DEFAULT_OPTIONS.addArguments("--disable-gpu");
DEFAULT_OPTIONS.addArguments("--start-maximized");
DEFAULT_OPTIONS.addArguments("--window-size=1920x1080");
```
Where can I learn about these aguments?

**Comment by titusfortner** [comment]
That's all managed by Google, so Selenium doesn't have any direct control over it, but here is a great resource for that:

https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
