### ISSUE TITLE
[🐛 Bug]: Action DoubleClick just do a single click on Safari

### ISSUE THREAD

**Issue by huydaoQE** [SeleniumHQ/selenium#11791]
### What happened?

When I execute Actions doubleClick on Safari browser, it seem do a single click only (It works normall on other browsers).

### How can we reproduce the issue?

```shell
Execute below example script:

public static void main(String[] args) {
        SafariDriver driver = new SafariDriver();
        driver.get("https://demoqa.com/buttons");
        driver.manage().window().maximize();
        Actions action = new Actions(driver);
        WebElement buttonClick = driver.findElement(By.xpath("//button[text()='Click Me']"));
        WebElement buttonDoubleClick = driver.findElement(By.xpath("//button[@id='doubleClickBtn']"));

        action.doubleClick(buttonClick).perform();
        action.click(buttonDoubleClick).doubleClick(buttonDoubleClick).perform();
        action.pause(1000);
 }
```

### Relevant log output

```shell
N/A
```

### Operating System

macOS Vertuna

### Selenium version

Java 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Safari 16.2

### What are the browser driver(s) and version(s) where you see this issue?

safariDriver

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Does it work on Chrome/Firefox?

**Comment by huydaoQE** [comment]
It works normally on Chrome @diemol

**Comment by diemol** [comment]
Then please report this to the Safari team. I will leave some links below. Thank you.
