### ISSUE TITLE
[🚀 Feature]: support a 'network is idle' heuristic

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#11800]
### Feature and motivation

I have done some tests with playwirght and there is a [networkidle heuristic](https://playwright.dev/docs/navigations#navigation-lifecycle) to detect if the page is fully loaded. This is very handy if you are dealing with alot of dyamically loaded containers with shadow-roots.

My current approach is to search the DOM via JavaScript for "loading" elements, to wait for the application to be ready. I need to customize this script for each and every application / framework i am testing.

The networkidle heuristic would be a very generic approach to detect the loading state of any application and would help alot of people dealing with dyamically loaded containers.

I don't know any option (for all browsers) to implement this on my own. Prehaps the BiDi protocoll could help to implement something like this in the future?

### Usage example

// this is pseudo code
WebDriverWait wait = new WebDriverWait(driver, Duration.ofMinutes(1));

wait.until(ExpectedConditions.networkIsIdle(Duration.ofSeconds(1)));

**Comment by diemol** [comment]
I think it does make sense, but we would not add it directly in Selenium right away. I suggest to check the [WebDriver BiDi uses cases](https://github.com/w3c/webdriver-bidi/blob/master/roadmap.md), and if you do not find it, can you please create an issue in that repository? Then it can be considered and it will potentially work in all browsers.

If you end up creating an issue, please share the link here so we can follow up.

**Comment by titusfortner** [comment]
Network module just landed in BiDi spec

@pujagani / @shs96c / @AutomatedTester — I think I'm right that [Network Interceptor class](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/devtools/NetworkInterceptor.java#L58) can be implemented as is with BiDI? We still need to move it from devtools to bidi module?

At any rate, creating a tool that allows waiting for this should be straightforward? Would *love to promote this functionality.
