### ISSUE TITLE
[🐛 Bug]: ExecuteJavaScript<double> fails if the number has no decimal part

### ISSUE THREAD

**Issue by VulumeCode** [SeleniumHQ/selenium#11801]
### What happened?

In Chrome `Browser.ExecuteJavaScript<double>("{return performance.timeOrigin ;}");` fails 1 in 10 times because it returns a double truncated to 1 decimal. However when the decimal part is 0 Selenium sees this as a long, which is not `IsInstanceOfType` double, so it crashes with `WebDriverException("Script returned a value, but the result could not be cast to the desired type");`.

This means that it is in general not possible to use `double` for `ExecuteJavaScript`, even though it often seems correct.

### How can we reproduce the issue?

```shell
`Browser.ExecuteJavaScript<double>("{return 123.0;}");`
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException : Script returned a value, but the result could not be cast to the desired type
   at OpenQA.Selenium.Support.Extensions.WebDriverExtensions.ExecuteJavaScript[T](IWebDriver driver, String script, Object[] args)
```

### Operating System

Windows 10

### Selenium version

.Net 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111

**Comment by diemol** [comment]
We'll have a look, but before that, is it the same in Firefox and Edge?

**Comment by VulumeCode** [comment]
I can't easily check that, but I suspect so. I followed the debugger and it seems to stem from Newtonsoft's JSON deserializer. It picks the type based on the string value, and Selenium just accepts it. `ExecuteJavaScript<T>` uses `typeof (T).IsInstanceOfType(o)` so it fails when you expect a double. 

I do know Firefox's `performance.timeOrigin` only returns whole numbers so it'll never work with double, but I wouldn't use this as the test case.

**Comment by diemol** [comment]
Can you share a more complete script we can use to reproduce this?

**Comment by nvborisenko** [comment]
I will take a look and prepare a fix, seems I know how to fix it. Left this comment just as a reminder for myself.

**Comment by nvborisenko** [comment]
```C#
using OpenQA.Selenium.Support.Extensions;

driver.ExecuteJavaScript<long>("return 123;");
```
^ works.

```C#
driver.ExecuteJavaScript<int>("return 123;");
```

^ doesn't work.
```
OpenQA.Selenium.WebDriverException: Script returned a value, but the result could not be cast to the desired type
   at OpenQA.Selenium.Support.Extensions.WebDriverExtensions.ExecuteJavaScript[T](IWebDriver driver, String script, Object[] args)
```
