### ISSUE TITLE
[🚀 Feature]: Add IE mode debug log option

### ISSUE THREAD

**Issue by rbourga** [SeleniumHQ/selenium#11804]
### Feature and motivation

With IEDriverServer.exe you currently don't have the option to change the logging happening in Edge (which is running in "IE mode").
This option can be valuable when debugging issues happening in the browser such as crashes or hangs.
When launching Edge, the command line flags to add for logging are:
--enable-logging --vmodule=*/edge_dual_engine/*=3

### Usage example

As an example, the launch of Edge should look like: msedge.exe --enable-logging --vmodule=*/edge_dual_engine/*=3

The log file will be stored in %LOCALAPPDATA%\Microsoft\Edge\User Data\chrome_debug.log

**Comment by titusfortner** [comment]
Well, the place to add this is here - https://github.com/SeleniumHQ/selenium/blob/e43a6c296dfdb35065a7dbd4f73b37f72970357c/cpp/iedriver/BrowserFactory.cpp#L409-L426

But.
We'd need to add a capability to the driver to toggle it, and then add support for it to all the bindings.

If you can figure out how to get the setting/toggle in the driver, we can probably figure out the option in the bindings pretty quickly.
