### ISSUE TITLE
[🚀 Feature]: remove deprecated events classes

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11819]
### Feature and motivation

3 of these classes have been deprecated since 4.0 and can be deleted. 

https://github.com/SeleniumHQ/selenium/tree/trunk/java/src/org/openqa/selenium/support/events

### Usage example

Use webdriver listener and event firing decorator classes instead.

**Comment by diemol** [comment]
Yes, but someone raised a comment in Slack saying that lots of code relies on the deprecated class. So we need to explain why we remove it and add an example showing how to migrate.

**Comment by diemol** [comment]
Related PRs were merged. Thanks, @RevealOscar!
