### ISSUE TITLE
[🐛 Bug]: WebDriver session closes intermittently while taking screenshot.

### ISSUE THREAD

**Issue by ssd9881** [SeleniumHQ/selenium#11813]
### What happened?

This issue has been observed in 3 scenarios
Scenario 1:
    1) Open the main windows, store its handle 
    2) Open its child widow and perform some actions on the instance of child window
    3) Close the child window (clicking on button closes the window) 
    4) Take selenium screenshot
    5) Try to switch to the main window using the handle which has been stored earlier

Scenario 2:
    1) Open the main windows, store its handle 
    2) Open a new tab and perform some actions on the instance of child window
    3) Close the new tab by pressing Ctrl+W
    4) Take selenium screenshot
    5) Try to switch to the main window using the handle which has been stored earlier

Scenario 3:
    1) Open the main windows, store its handle 
    2) Open its child widow and perform some actions on the instance of child window
    3) Close child window (Here clicking on button there is a dialog box that pop up on accepting the dialog the window is closed)
   4) Take selenium screenshot
   5) Switch to parent window with the help of the handle.

In all three cases the script runs fine when 4th step (Capturing Screenshots) is not performed but otherwise it gives the exception:
org.openqa.selenium.WebDriverException: 
java.net.ConnectException: Failed to connect to [localhost/0:0:0:0:0:0:0:1:9958[]

### How can we reproduce the issue?

```shell
1. webElement buttonOnChildWindow= driver.findElement(By.id("clickable"));
   buttonOnChildWindow.click() //This will close the child window
2. TakesScreenshot scrShot =((TakesScreenshot)webdriver);
   File SrcFile=scrShot.getScreenshotAs(OutputType.FILE);
3. driver.switchTo().window(<mainWindow handle of which would already be stored and used here>);  
```

### Relevant log output

```shell
Cause: org.openqa.selenium.WebDriver Error:  java.net.Connect Error:  Failed to connect to localhost/0:0:0:0:0:0:0:1:40114 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53' System info: host: 'CDS-D-992', ip: '192.9.28.221', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_272' Driver info: driver.version: RemoteWebDriver
```

### Operating System

Windows 10

### Selenium version

Zulu 8.54.21 selenium 3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 111.0.5563.65

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111

**Comment by diemol** [comment]
Closing as we did not get a way to reproduce this.
