### ISSUE TITLE
[🚀 Feature]: Add Missing Exceptions

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11817]
### Feature and motivation

Several valid [w3c errors](https://w3c.github.io/webdriver/#ref-for-dfn-error-code-13) are missing from [ErrorCodec](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/ErrorCodec.java) class:

* `detached shadow root` 
* `no such shadow root`
* `insecure certificate`

### Usage example

Right now accessing a page with Insecure Certificate in Firefox returns a generic `WebDriverException`

**Comment by rai971** [comment]
I would like to add all missing [w3c errors](https://w3c.github.io/webdriver/#ref-for-dfn-error-code-13) in [ErrorCodec](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/remote/ErrorCodec.java). class file.
I have forked and cloned the project. let me know if i can go i ahead and push to new branch
FYI - i am new to opensource and would like get any feedback or suggestions.

**Comment by titusfortner** [comment]
Welcome @rai971! Thanks for your help.

We walk through our contribution process here - https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md#code-contributions

Looks like you've forked, cloned, branched and committed, so the next step would be to push the branch with the new commit to your fork, and make a Pull Request to this project: https://github.com/SeleniumHQ/selenium/blob/trunk/CONTRIBUTING.md#step-6-push

If you want to discuss anything, please find us on Slack or IRC - https://www.selenium.dev/support/index.html#ChatRoom
