### ISSUE TITLE
[🐛 Bug]: Remove on spec compliant `desiredCapabilities` and `requiredCapabilities`

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#11820]
### What happened?

Both the `desiredCapabilities` and `requiredCapabilities` were used in pre-WebDriver classic spec times to specify capabilities for the browser. Now this is no longer needed and could be removed.

The WebDriver classic spec only uses `firstMatch` and `alwaysMatch` instead when [processing capabilities](https://w3c.github.io/webdriver/#processing-capabilities).

As per code search there are a couple of Selenium bindings which still make use of the non-spec capabilities matching including Python, Java, C#.

Once the usage is gone we will also [remove it from geckodriver](https://bugzilla.mozilla.org/show_bug.cgi?id=1823907).

Thanks.

CC @diemol, @AutomatedTester, @jimevans.

### How can we reproduce the issue?

Querying the Selenium repository:
https://github.com/SeleniumHQ/selenium/search?q=desiredcapabilities&type=code

### Relevant log output

None

### Operating System

MacOS 13.2.1

### Selenium version

Latest

### What are the browser(s) and version(s) where you see this issue?

Firefox 113

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.32.2

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
For Python this is only present in `ExtensionConnection` which I think we recently agreed needs to be deprecated anyway because I don't think it works for geckodriver.

@nvborisenko can you double check for .NET whether it is still sending both `desiredCapabilities` and `capabilities` in the new session payload to the driver/server?

@diemol how much work is going to be required to pull this out of Java? 

Thanks!

**Comment by nvborisenko** [comment]
Just quickly tested .Net bindings, seems it uses `firstMatch` both for local and remote ends:
```
02:46:18.875 DEBUG HttpCommandExecutor: Executing command: []: newSession {"capabilities":{"firstMatch":[{"browserName":"firefox","acceptInsecureCerts":true,"moz:firefoxOptions":{}}]}}
```

**Comment by diemol** [comment]
I don't think this is in Java anymore, you might find variable names or comments, but `desiredCapabilities` is not used anymore in the payload. Do you have an example where it is still used?

**Comment by titusfortner** [comment]
No, I just didn't remember it had been removed. I guess we're ok to close this.

**Comment by whimboo** [comment]
@titusfortner would you mind telling us what the closed status exactly mean? Is each and every usage of those capabilities gone across all bindings? And (if possible) since which release are the binding no longer using them. I wonder when we can get started to remove the support in geckodriver. Thanks!

**Comment by titusfortner** [comment]
Java was the longest holdout in #11823  (Selenium 4.9)
JS removed with https://github.com/SeleniumHQ/selenium/commit/fa6deeea6bda1e73317157845772e114bd569b7d (Selenium 4.5)
Python in #10494 (Selenium 4.2)
Ruby & .NET both removed this for Selenium 4

**Comment by titusfortner** [comment]
.NET is a little confusing because it references "desiredCapabilities" all over the place still, it just doesn't send it as a key to the driver.

**Comment by whimboo** [comment]
Thanks a lot! So Selenium 4.9 has been released on April 20, 2023 so we should be fine to get it removed in geckodriver now.
