### ISSUE TITLE
[🚀 Feature]: mimic mouse human gestures like NodeJS/pptr Ghost-Cursor

### ISSUE THREAD

**Issue by Mevatlave-Kraspek** [SeleniumHQ/selenium#11824]
### Feature and motivation

For [pptr](https://pptr.dev), they have [Ghost Cursor](https://github.com/Xetera/ghost-cursor) to mimic mouse human gestures.

Is there any project for this purpose?

If not, should neat to have this feature, why not as a plugin, based on [_Bezier curves_](https://en.wikipedia.org/wiki/B%C3%A9zier_curve)

### Usage example

```
from selenium.foobar import CreateCursor
from selenium import webdriver

driver = webdriver.Chrome()
cursor = createCursor(driver)
cursor.click(selector)
```

**Comment by titusfortner** [comment]
There is an [actions specification for pointers](https://w3c.github.io/webdriver/#pointer-actions) that explains what can be done. It is based on moving a mouse in a set duration from one point to another. You can raise an issue there if you think Bezier curves would make sense to add.

What is in spec, we've implemented with [Action Chains](https://github.com/SeleniumHQ/selenium/blob/selenium-4.8.1/py/selenium/webdriver/common/action_chains.py#L212-L248) in Python.
