### ISSUE TITLE
[🚀 Feature]: 

### ISSUE THREAD

**Issue by DanielHJA** [SeleniumHQ/selenium#11839]
### Feature and motivation

It would be amazing if there was a way to record a video of the entire webdriver session.

### Usage example

To review lengthy automations and see what went wrong.

**Comment by titusfortner** [comment]
Great feature idea.

1. The Network module just landed in WebDriver-BiDi spec (https://github.com/w3c/webdriver-bidi/commit/47f0b65df3a01e299f5758cb546ae1af0201b7e9)
2. Firefox Nightly now supports it, we expect Chrome to follow very soon
3. Selenium will hopefully wrap this "soon"
4. It should be possible to construct a video using this functionality
5. We are trying to keep the focus of Selenium on properly wrapping inputs/outputs to/from the driver/browser directly
6. The community should create open source libraries in the various languages to provide extra functionality like this
7. Selenium should highlight and promote those libraries
