### ISSUE TITLE
[🐛 Bug]: Selenium Grid 4.8.1 is responding slow

### ISSUE THREAD

**Issue by ayushi-nyk** [SeleniumHQ/selenium#11836]
### What happened?

Earlier we used to use grid v.3.141.59 on which our 700 test cases were running with 22 parallel nodes and it used to take around 60 to 90 mins .. But now same suit is taking more than 4 hours on grid version 4.8.1 .
We have observed that some test gets stuck on grid for around 1 hour or more ..

What is the reason of slowness .

### How can we reproduce the issue?

```shell
Use selenium standalone jar to get hub up and then make the nodes up using aws ECS service ..
```

### Relevant log output

```shell
NA
```

### Operating System

linux

### Selenium version

4.7.0

### What are the browser(s) and version(s) where you see this issue?

chrome -110

### What are the browser driver(s) and version(s) where you see this issue?

using webdrivermanager library

### Are you using Selenium Grid?

yes - 4.8.1

**Comment by diemol** [comment]
Closing as we did not we details on how to reproduce this.
