### ISSUE TITLE
[🐛 Bug]: click Event on Element with window.close() crashes Chrome with java.io.IOException: HTTP/1.1 header parser received no bytes

### ISSUE THREAD

**Issue by floa93** [SeleniumHQ/selenium#11833]
### What happened?

Hey devs,

we have our UI tests running using the newest Selenium with Chrome. A lot of our pages consist of anchors/buttons which open a new window with JS (with `window.open`). The new window can be closed with a img/anchor/button which is using JS again to return to the previous window (with `window.close`). We noticed that from time to time Selenium or Chrome(not sure) randomly crashes at the click step on a e.g. img element which contains an onclick event with `window.close` . In Selenium 3 with Chrome ~94 we didnt notice a similiar error, so the error appeared after the upgrade. It seems to be a bit random when the error occurs, sometimes at the start of our test suite and sometimes in the middle/end. We checked the resource usage/limits, but it doesnt seem to have an impact.

### How can we reproduce the issue?

```shell
I reproduced the issue with 3 simple HTML files, the simple HTTP node server and the Python Selenium webdriver using the newest docker-selenium standalone Chrome image. 
The repo is : https://github.com/floa93/chrome_selenium_error . 
To reproduce the (random) error it is looped. Sometimes it crashes after 1500 iterations, sometimes after 3000 iterations, sometimes earlier. I know the example may be a bit exaggerated, but it was the only way I could reproduce the issue. 

Thanks for your help!
```

### Relevant log output

```shell
Chrome output with exception: https://gist.github.com/floa93/c0b86db4e9a23418140066c4b5257ad3
Python output with exception: https://gist.github.com/floa93/66aedf3d5ad7563cdb85c6da966c3149
```

### Operating System

Windows 11 + WSL2

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 110.0.5481.77

### Are you using Selenium Grid?

4.8.2

**Comment by joerg1985** [comment]
@floa93 looks like i had the same issue and this looks like a chromedriver issue to me:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=4596
