### ISSUE TITLE
[🐛 Bug]: invalid selector after upgrade from selenium 4.8.1 to 4.8.2 (C#)

### ISSUE THREAD

**Issue by omer-za** [SeleniumHQ/selenium#11842]
### What happened?

I receive error of invalid selector after upgrade from selenium 4.8.1 to 4.8.2 while selector is valid.

### How can we reproduce the issue?

```shell
Try find element with css selector `[data-testid='alert-primary-button'], [data-testid='alert-primary-warn-button'], [data-testid='alert-primary-flat-button'], [data-testid='alert-primary-branded-button']`
```

### Relevant log output

```shell
By.CssSelector: [data-testid='alert-primary-button'], [data-testid='alert-primary-warn-button'], [data-testid='alert-primary-flat-button'], [data-testid='alert-primary-branded-button'] cta ---> OpenQA.Selenium.WebDriverTimeoutException: Timed out after 15 seconds ---> OpenQA.Selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
```
```


### Operating System

Mac

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

Latest

### Are you using Selenium Grid?

_No response_

**Comment by titusfortner** [comment]
We recently stopped subclassing invalid selector exception as a no such element exception. If you are newly getting the error, it has always been invalid and was just being caught as a different error.

As for whether it is actually invalid, that's decided by chrome. You might check it with a validator to make sure. Or check and see if Firefox also flags it.

Either way there is nothing for selenium to do here.
