### ISSUE TITLE
[🐛 Bug]: Chrome's Webdriver getting stuck on driver.get(URL)

### ISSUE THREAD

**Issue by jdotsoft** [SeleniumHQ/selenium#11846]
### What happened?

Chrome's Webdriver getting stuck on driver.get(URL)
See also similar bug report #10336

### How can we reproduce the issue?

```shell
System.out.println("1");
driver.get("https://www.nasdaq.com/market-activity/stocks/ncmi/dividend-history");
System.out.println("2");
```

### Relevant log output

```shell
n/a
```

### Operating System

Windows 10

### Selenium version

Java 8

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 111.0.5563.111 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver_win32_110.0.5481.77.exe

**Comment by diemol** [comment]
Very much likely that website is blocking automation. If this is happening on any website, can you please provide a way to reproduce it?

**Comment by jdotsoft** [comment]
No, this site does not block automation. I found a workaround by 
switching to Edge.

On 2023-03-30 16:12, Diego Molina wrote:

Very much likely that website is blocking automation. If this is 
happening on any website, can you please provide a way to reproduce it?

--
Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
You are receiving this because you were mentioned.Message ID: 
***@***.***>



Links:
------
[1] 
https://github.com/SeleniumHQ/selenium/issues/11846#issuecomment-1490888085
[2]

**Comment by diemol** [comment]
Great.
