### ISSUE TITLE
[🐛 Bug]: FindElement gives invalid xpath error after updating from Selenium 4.7 to 4.8

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#11841]
### What happened?

This code works in Selenium 4.7:

```
FindElement(By.XPath("//*[@id='mat-select-0-panel']/mat-option[.='something odd that doesn't exist']"));
```

But in Selenium 4.8.2, it generates this error:

```
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='mat-select-0-panel']/mat-option[.='something odd that doesn't exist']' is not a valid XPath expression.
```

I looked over the change log and could not identify a change that could be responsible for this.  This cannot be a driver problem, because the same driver is used in both cases.

### How can we reproduce the issue?

```shell
FindElement(By.XPath("//*[@id='mat-select-0-panel']/mat-option[.='something odd that doesn't exist']"));
```

Occurs in both Chrome and Edge.
```


### Relevant log output

```shell
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='mat-select-0-panel']/mat-option[.='something odd that doesn't exist']' is not a valid XPath expression.
  (Session info: chrome=111.0.5563.112)"
     at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
     at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.WebElement.FindElement(String mechanism, String value)
     at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
     at OpenQA.Selenium.By.FindElement(ISearchContext context)
     at OpenQA.Selenium.WebElement.FindElement(By by)
```

### Operating System

Windows 10

### Selenium version

4.8.2
(C# client)

### What are the browser(s) and version(s) where you see this issue?

Chrome 111.0.5563.147, Edge 111.0.1661.54

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 111.0.5563.6400, Edge 111.0.1661.54

**Comment by joerg1985** [comment]
I think this might be related to #10833 / #11712 and the related PR is #11727.

The `'` inside the `doesn't` does break the xpath and the code might have handled a NoSuchElementException differently

**Comment by titusfortner** [comment]
Selenium didn't change what is valid or invalid, we just changed the superclass of the exception that is supposed to be thrown. Are you sure it was working for you before, or were you rescuing the failure as a `NoSuchElementException`?

Because, that selector is not valid. You can't have an unescaped quote in the middle of a quoted string, so it should fail.

That said, I'm not sure `SyntaxError` is the correct error. What does Firefox do?

**Comment by ccarmannt** [comment]
<s>This method call is not wrapped in any exception handling, so no, we weren't trapping a `NoSuchElementException`.</s>

We don't use Firefox here, so I can't speak to what it does.

**Comment by ccarmannt** [comment]
I had to correct my last statement. I failed to notice this was coming from a negative test, which was indeed expecting a `NoSuchElementException`'.

**Comment by titusfortner** [comment]
Excellent.

So, from our side we should check to see why it is returning a syntax error instead of an invalid selector error I think. It might be a chromedriver bug, but need to reproduce it.

**Comment by nvborisenko** [comment]
@ccarmannt your xpath is incorrect
```
'something odd that doesn't exist'
```

Triple `'` symbol. You can rework it to
```
"something odd that doesn't exist"
```

or
```
'something odd that does not exist'
```

**Comment by titusfortner** [comment]
Hmm, yes, I guess a broken String is not just an invalid selector, but is actually a Syntax error, so this is correct. I'll close.
