### ISSUE TITLE
[🚀 Feature]: Keep pointer position on handle reload

### ISSUE THREAD

**Issue by NikkieCold** [SeleniumHQ/selenium#11851]
### Feature and motivation

Now if page were reloaded the pointer position resets to (0, 0).
It would be useful if the cursor position was memorized

### Usage example

In my tests i need to track user's mouse movents and now ithis is impossible to perform without this feature

**Comment by titusfortner** [comment]
Hmm, I'm not sure what the correct behavior here should be, but either way it needs to be decided in w3c spec.
