### ISSUE TITLE
[🐛 Bug]: ChromeDriver can not produce chrome_debug.log  

### ISSUE THREAD

**Issue by chutang** [SeleniumHQ/selenium#11855]
### What happened?

In Mac OS , when use ChromeDriver to start chrome browser  with arguments, I except the new file: chrome_debug.log   would be produced under below folder , but actually this thing not happened .
 /Users/${User}/Library/Application Support/Google/Chrome 
The Chrome driver input arguments is : 
--use-fake-ui-for-media-stream, --no-default-browser-check, --start-maximized, --disable-dev-shm-usage, --no-sandbox, --disable-infobars, --verbose, --log-level=ALL,  --enable-logging, --v=1, --vmodule=webrtc=1

When manually start the chrome with the arguments , the chrome_debug.log  can produced right .
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --use-fake-ui-for-media-stream --no-default-browser-check --start-maximized --disable-dev-shm-usage --no-sandbox --disable-infobars --verbose --log-level=ALL  --enable-logging --v=1 --vmodule=webrtc=1

### How can we reproduce the issue?

```shell
public class ChromeDriverExample {
    public static void main(String[] args) {
        ChromeOptions options = new ChromeOptions();
options.setCapability("goog:loggingPrefs", logPrefs);
			
            // Disable default browser check
			options.addArguments("--no-default-browser-check");
			
			// Start the browser maximized
			options.addArguments("--start-maximized");
			options.addArguments("--disable-dev-shm-usage");
			
			// Incognito mode to disable cache
			//options.addArguments("--incognito");
			options.addArguments("--no-sandbox");
			options.addArguments("--disable-infobars");
			options.addArguments("--verbose");
			options.addArguments("--log-level=ALL");
			//options.addArguments("--log-path=/Users/test/Downloads/");
			options.addArguments("--enable-logging");
			options.addArguments("--v=1");
			options.addArguments("--vmodule=webrtc=1");

        WebDriver driver = new ChromeDriver(options);
    }
}
```

### Relevant log output

```shell
[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--use-fake-ui-for-media-stream, --no-default-browser-check, --start-maximized, --disable-dev-shm-usage, --no-sandbox, --disable-infobars, --verbose, --log-level=ALL, --log-path=/Users/test/, --enable-logging, --v=1, --vmodule=webrtc=1], extensions: [], prefs: {profile.password_manager_enabled: false}}, goog:loggingPrefs: {browser: ALL}, platformName: MAC}, Capabilities {browserName: chrome, goog:chromeOptions: {args: [--use-fake-ui-for-media-stream, --no-default-browser-check, --start-maximized, --disable-dev-shm-usage, --no-sandbox, --disable-infobars, --verbose, --log-level=ALL, --log-path=/Users/test/, --enable-logging, --v=1, --vmodule=webrtc=1], extensions: [], prefs: {profile.password_manager_enabled: false}}, goog:loggingPrefs: {browser: ALL}, loggingPrefs: org.openqa.selenium.logging..., platformName: MAC}]
Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 33068
Only local connections are allowed.
```

### Operating System

MacOS

### Selenium version

selenium-server-standalone-3.141.59

### What are the browser(s) and version(s) where you see this issue?

Mac Chrome 111 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDirver 111.0.5563.64

**Comment by diemol** [comment]
When you start Chrome through ChromeDriver, the logs go to the console by default. You need to use the `--log-path` to send the logs to a given file. You can always check the options by doing `chromedriver --help`.
