### ISSUE TITLE
[🐛 Bug]: module not found: processed.jcommander

### ISSUE THREAD

**Issue by dnicholas2001** [SeleniumHQ/selenium#11858]
### What happened?

Module not found exception when upgrading from Selenium 4.6.0 to 4.8.2

### How can we reproduce the issue?

```shell
Please find attached ZIP with steps to recreate.

1. Require Java 17
2. Create a multi-module Java project
3. Ensure module-info.java exists for **both** modules A and B
4. Create a test that creates a new Chrome Driver, `ApplicationTests.java`
5. Run the test and it fails to compile due to the module exception
```

### Relevant log output

```shell
java: module not found: processed.jcommander
java: module not found: processed.async.http.client
```

### Operating System

Windows 10

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111

### Are you using Selenium Grid?

No

**Comment by dnicholas2001** [comment]
[starter-repro-jcommander.zip](https://github.com/SeleniumHQ/selenium/files/11144355/starter-repro-jcommander.zip)

**Comment by dnicholas2001** [comment]
This is related to #11556

**Comment by titusfortner** [comment]
Do you still see this if you set your project to use the Java 11+ http client?

https://www.selenium.dev/blog/2022/using-java11-httpclient/

**Comment by dnicholas2001** [comment]
@titusfortner Haven't tried that, let me try it real quick.

**Comment by dnicholas2001** [comment]
@titusfortner Many thanks for the suggestion, however, the problem still exists even after following the instructions at https://www.selenium.dev/blog/2022/using-java11-httpclient/

Added this to my POM
```
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-http-jdk-client</artifactId>
      <version>4.8.2</version>
    </dependency>
```

And added this to my Launch configuration in IntelliJ
```
-Dwebdriver.http.factory=jdk-http-client
```

Am noticing a change in the `module-info.java` for the `remote-web-driver` module

![image](https://user-images.githubusercontent.com/7997278/229681737-7adfc8dc-f290-49d6-bcba-28d2d40c86f1.png)

**Comment by titusfortner** [comment]
Hmm, looks like others having this issue as well: 
* https://stackoverflow.com/questions/74892632/compilation-error-with-maven-on-intellij-module-not-found-processed-jcommander
* https://stackoverflow.com/questions/75680712/java-lang-module-findexception-module-processed-jcommander-not-found-required

I think Diego is needed for this one.

**Comment by dnicholas2001** [comment]
@diemol

**Comment by joerg1985** [comment]
Beside the original issue, i think the `processed.async.http.client` should be an optional module (requires static).
So the dependency could be removed from the classpath when the new java 11 client is used.
(I have removed it from my class path via `<exclusions>` in the `pom.xml`)

I think there are alot of modules which should not be in the client jars, e.g. the `io.opentelemetry` modules. 
Or am i wrong and these `io.opentelemetry` modules are in use by the client?
