### ISSUE TITLE
[🐛 Bug]: What is diff between GetScreenshot and TakeScreenshot methods

### ISSUE THREAD

**Issue by oriongonza** [SeleniumHQ/selenium#11877]
### What happened?

The C# ChromeDriver interface exposes two similar functions: 
`TakeScreenshot()` and `GetScreenshot()`, and there's no documentation of when to choose either.
 
It seems like TakeScreenshot does the same but with more error checking.

### Operating System

Windows 10

### Selenium version

C# 4.8.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 111

**Comment by diemol** [comment]
@nvborisenko do you know?

**Comment by nvborisenko** [comment]
`GetScreenshot()` method came from `ITakesScreenshot` interface, meanwhile `TakeScreenshot` is extension method for `IWebDriver`. There is no difference.

If you can use the following, just use it:
```csharp
var driver = new ChromeDriver();
var screenshot = driver.GetScreenshot();
```

Sometimes, people keep driver as `IWebDriver`, then extension method is helpful:
```csharp
IWebDriver driver = new SomeOtherDriver();
var screenshot = driver.TakeScreenshot(); // it compiles even when IWebDriver doesn't have TakeScreenshot() method
```

Be aware, that extension method is shipped in `Selenium.Support` nuget package.
