### ISSUE TITLE
I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://*IPAddress*:5555: No route to host

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#1187]
I am having this issue with Selenium Grid, first time I set up a Grid

I start my Selenium hub on a Linux by this command:
`java -jar /opt/selenium-server/selenium-server-standalone-2.48.2.jar -role hub -port 4444 &`

it is successful:
>Nodes should register to http://10.0.50.34:4444/grid/register/
>Selenium Grid hub is up and running

Then I register my node on a VM Windows to this hub by:
`java -Dwebdriver.ie.driver=C:\Selenium\IEDriverServer.exe -jar selenium-server-standalone-2.48.2.jar -role node -hub http://10.0.50.34:4444/grid/register/`

The node says it's registered to the hub and is ready to use

But then, at the hub, I got this exception:
> Registered a node http://10.211.55.3:5555
> I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.211.55.3:5555: No route to host
> Retrying request to {}->http://10.211.55.3:5555
> I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.211.55.3:5555: No route to host
> Retrying request to {}->http://10.211.55.3:5555
> I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.211.55.3:5555: No route to host
> Retrying request to {}->http://10.211.55.3:5555
> Marking the node http://10.211.55.3:5555 as down: cannot reach the node for 2 tries

**Comment by ddavison** [comment]
are you using aws?  if so, are your nodes behind a VPC?

**Comment by louis57** [comment]
I changed the network type, and it works. Thanks

**Comment by ddavison** [comment]
excellent! :+1:

**Comment by symehmoo** [comment]
@louis57 what network type did you change

**Comment by bagrip** [comment]
@louis57 I am having this issue when I try to connect nodes from other linux host on GCP. What network changes we need to make it to work?
