### ISSUE TITLE
[🐛 Bug]: java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set

### ISSUE THREAD

**Issue by 2397hushar** [SeleniumHQ/selenium#11875]
### What happened?

[selenium feature error.docx](https://github.com/SeleniumHQ/selenium/files/11182943/selenium.feature.error.docx)

### How can we reproduce the issue?

```shell
<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-manager -->
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-manager</artifactId>
<version>4.6.0</version>
</dependency

this is not valid dependency?
```

### Relevant log output

```shell
The path to the driver executable The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/. The latest version can be downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:311)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:135)
	at org.openqa.selenium.edge.EdgeDriverService.access$000(EdgeDriverService.java:40)
```

### Operating System

window 10

### Selenium version

java  2022-06 (4.24.0)

### What are the browser(s) and version(s) where you see this issue?

chrome ,edge firefox

### What are the browser driver(s) and version(s) where you see this issue?

chrome ,edge firefox

### Are you using Selenium Grid?

${seleniumGrid.version

**Comment by titusfortner** [comment]
You get the dependency when you require `selenium-java` so we do not recommend setting it explicitly. Does it work when not added?

**Comment by 2397hushar** [comment]
Still solve now problem
Actually I'm using different system pom dependency and update my project so
now it's working fine
