### ISSUE TITLE
[🐛 Bug]: Downloading unwanted drivers in mac node

### ISSUE THREAD

**Issue by remyanekkuth** [SeleniumHQ/selenium#11870]
### What happened?

As part of the migration to selenium 4 we updated our mac node in feb to run for selenium test on safari browser and was working as expected.
In our case we are using mac only for safari testing. 

Last week when checked in the grid console, I see that mac node have all the browsers now, not only safari.  The test ran successfully when we tested in early march.

![image](https://user-images.githubusercontent.com/16626518/230444570-8f983492-0677-497d-a514-978ede03f931.png)

expected : only safari driver should be available

run config : 

java. -Dwebdriver.safari.driver=/usr/bin/safaridriver  -jar "jar path" node --hub "hub url " --port "port num " --host "host name"   

seelenium jar - **selenium-server-4.8.0.jar** 

**node log in april  :** 

13:43:40.770 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:43:40.774 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:43:40.852 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium:4442 and tcp://selenium:4443
13:43:40.934 INFO [UnboundZmqEventBus.<init>] - Sockets created
13:43:41.939 INFO [UnboundZmqEventBus.<init>] - Event bus ready
13:43:42.029 INFO [NodeServer.createHandlers] - Reporting self as: http://macnode:4900
13:43:42.040 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
13:43:44.016 INFO [NodeOptions.discoverDrivers] - Discovered 4 driver(s)
13:43:44.049 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
13:43:44.050 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 16 times
13:43:44.051 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 16 times
13:43:44.052 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 16 times
13:43:44.098 INFO [Node.<init>] - Binding additional locator mechanisms: relative
13:43:44.303 INFO [NodeServer$1.start] - Starting registration process for Node http://macnode:4900
13:43:44.304 INFO [NodeServer.execute] - Started Selenium node 4.8.0 (revision 267030adea): http://macnode:4900
13:43:44.332 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:43:44.515 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
13:43:45.942 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
Host info: host: ‘macnode’, ip: ‘xxxxxxxxxx’
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.8'
Driver info: driver.version: unknown
13:43:45.961 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 

l**og captured in feb** : 

15:55:48.856 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium:4442 and tcp://selenium:4443
15:55:48.892 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:55:49.896 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:55:49.948 INFO [NodeServer.createHandlers] - Reporting self as: http://MACNode:4900
15:55:49.960 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
15:55:49.978 INFO [NodeOptions.discoverDrivers] - Discovered 1 driver(s)
15:55:50.001 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
15:55:50.008 INFO [Node.<init>] - Binding additional locator mechanisms: name, id, relative

why even though specifying the driver, now all the drivers are getting added . 

appreciate your help

### How can we reproduce the issue?

```shell
safari node with selenium-server-4.8.0.jar 
java -Dwebdriver.safari.driver = /usr/bin/safaridriver -jar "selenium-server-4.8.0.jar path " node --hub "hub url " --port "port num" --host "hostname"
```

### Relevant log output

```shell
13:43:40.770 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
13:43:40.774 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
13:43:40.852 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium:4442 and tcp://selenium:4443
13:43:40.934 INFO [UnboundZmqEventBus.<init>] - Sockets created
13:43:41.939 INFO [UnboundZmqEventBus.<init>] - Event bus ready
13:43:42.029 INFO [NodeServer.createHandlers] - Reporting self as: http://macnode:4900
13:43:42.040 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
13:43:44.016 INFO [NodeOptions.discoverDrivers] - Discovered 4 driver(s)
13:43:44.049 INFO [NodeOptions.report] - Adding Safari for {"browserName": "safari"} 1 times
13:43:44.050 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox"} 16 times
13:43:44.051 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome"} 16 times
13:43:44.052 INFO [NodeOptions.report] - Adding Edge for {"browserName": "MicrosoftEdge"} 16 times
13:43:44.098 INFO [Node.<init>] - Binding additional locator mechanisms: relative
13:43:44.303 INFO [NodeServer$1.start] - Starting registration process for Node http://macnode:4900
13:43:44.304 INFO [NodeServer.execute] - Started Selenium node 4.8.0 (revision 267030adea): http://macnode:4900
13:43:44.332 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
13:43:44.515 INFO [NodeServer.lambda$createHandlers$2] - Node has been added
13:43:45.942 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
Host info: host: ‘macnode’, ip: ‘xxxxxxxxxx’
Build info: version: '4.8.0', revision: '267030adea'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.8'
Driver info: driver.version: unknown
13:43:45.961 WARN [SeleniumSpanExporter$1.lambda$export$1] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary
```

### Operating System

macOS

### Selenium version

selenium-server-4.8.0.jar

### What are the browser(s) and version(s) where you see this issue?

safari 15.6.1

### What are the browser driver(s) and version(s) where you see this issue?

safaridriver-15.6.1

### Are you using Selenium Grid?

4.8.0

**Comment by diemol** [comment]
That is already fixed in 4.8.3

**Comment by remyanekkuth** [comment]
Thank you. Will try with 4.8.3.

**Comment by diemol** [comment]
Closing as this is not happening in 4.8.3
