### ISSUE TITLE
[bidi] implement user-friendly APIs for actions

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#11878]
### Feature and motivation

The feature added was (and this is a quote from the PR): "support for user input, exactly following the actions model
from classic WebDriver. The user sends a list of input devices, and
the state change (if any) of each device in each time period
("tick"). The implementation then converts this into a list of ticks
and performs the relevant state updates in each time period.

By supporting multiple devices acting simultaneously it's possible to
model complex multi-device interactions e.g. multitouch gestures
combined with different key input states.

Compared with classic WebDriver, the main difference is that it's
possible to target the actions at any browsing context, not just the
active browsing context."

### Usage example

Being able to model multi touch gestures combined with multiple input states. This could possibly help people zoom in on the page with selenium.

**Comment by titusfortner** [comment]
This functionality is available in WebDriver-classic, we just haven't had anyone implement it #10808 

That said I'll add this to our BiDi projects list — https://github.com/orgs/SeleniumHQ/projects/6/views/1

Note that the primary author of the BiDi work is out on leave for the next few months. Any PRs would be appreciated, or you may contact us on Slack/IRC to discuss — https://www.selenium.dev/support/index.html#ChatRoom

Thanks.

**Comment by pujagani** [comment]
I am closing this issue since tracking everything in one place is easier. Please refer to the [Selenium BiDi tracker](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing) to see the current status.
