### ISSUE TITLE
[bidi] implement user-friendly APIs for printing a page to a PDF

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#11889]
### Feature and motivation

https://github.com/w3c/webdriver-bidi/commit/a04ee5e3f7a77191d51c21d7070eda7653e2c59f had the roadmap for bidi be updated with some things getting checked off.

NOTE: There is already an issue for the performActions change, and the other changes already had links to the w3c documentation page so I just think this is them making the roadmap up to date.

### Usage example

This could be used to print a website as a pdf.

**Comment by pujagani** [comment]
I am closing this issue since tracking everything in one place is easier. Please refer to the [Selenium BiDi tracker](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing) to see the current status.
