### ISSUE TITLE
[🐛 Bug]: WebDriverWait throws error instantly without waiting the any TimeSpan (C#)

### ISSUE THREAD

**Issue by aspeed98** [SeleniumHQ/selenium#11885]
### What happened?

C#
Using WebDriverWait throws error instantly, without waiting any amount of time given to it.
Code I'm using is correct, in fact this code is 100% taken from the selenium.dev website.
And of course OpenQA.Selenium.Support.UI is being imported to project.
https://www.selenium.dev/documentation/webdriver/waits/

### How can we reproduce the issue?

```shell
ChromeDriver driver = new ChromeDriver();
driver.Url = "https://www.google.com/ncr";
driver.FindElement(By.Name("q")).SendKeys("cheese" + Keys.Enter);

WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
IWebElement firstResult = wait.Until(e => e.FindElement(By.XPath("//div[id='obviously WRONG XPATH']")));

Console.WriteLine(firstResult.Text);
driver.Quit();
```

### Relevant log output

```shell
OpenQA.Selenium.NoSuchElementException: "no such element: Unable to locate element: {"method":"xpath","selector":"//div[id='obviously WRONG XPATH']"}
(Session info: chrome=112.0.5615.50)
```

### Operating System

Windows 11

### Selenium version

4.8...

### What are the browser(s) and version(s) where you see this issue?

Chrome 111, 112, ...

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111.0.5563.64

### Are you using Selenium Grid?

no grid

**Comment by titusfortner** [comment]
I can't duplicate this on Windows 11 with Chrome 111. We do need to change the example code, though.

try:
```
            driver.Url = "https://www.selenium.dev/selenium/web/dynamic.html";
            driver.FindElement(By.Id("adder")).Click();
            
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            IWebElement added = wait.Until(d => d.FindElement(By.Id("box0")));
```

**Comment by nvborisenko** [comment]
@titusfortner I think you will be able to reproduce the issue within following code:
```csharp
            driver.Url = "https://www.selenium.dev/selenium/web/dynamic.html";
            driver.FindElement(By.Id("adder")).Click();
            
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            IWebElement added = wait.Until(d => d.FindElement(By.Id("UNKNOWN_ID")));
```

@aspeed98 you should add `NoSuchElement` exception as ignored while waiting element.

**Comment by titusfortner** [comment]
Hmm, that should be the default behavior, though. I'll try again.

**Comment by nvborisenko** [comment]
You are right, Titus.

Moreover, I executed original code and it works as expected: it waits 10 seconds and then throws exception.

**Comment by diemol** [comment]
Do we need to do something to fix this open issue? Or was it working as expected?

**Comment by nvborisenko** [comment]
Seems  nothing to do from our side, it works as expected. I would ask @aspeed98 to provide cleaner steps for issue reproduction.

**Comment by diemol** [comment]
Closing as we did not get more information.
