### ISSUE TITLE
HtmlUnitWebElement class getText method does not work

### ISSUE THREAD

**Issue by filipcynarski** [SeleniumHQ/selenium#1189]
getText returns empty string for HTML tags like title since 2.46.0 version of selenium-java

It is because of upgrade HTMLUnit now you should use: this.element.asXml() method if you want parse entire HTML or just use asText() method and do not handle HTML parsing on your side.

**Comment by lukeis** [comment]
title and anything in the <head> is technically not visible and the getText method only returns the visible text.

to retrieve the title in particular use driver.getTitle()

if you have other examples where getText isn't doing what you think it should be doing, please provide a reproducible test case with corresponding html / url. We can reopen this issue if that is provided.

**Comment by filipcynarski** [comment]
Yeah, I know that getText for window can be obtained, I wonder if that is stopped working since 2.46.0 was released. Our unit tests stopped passing after update to versions above 2.45.

The test which is failing is:

```java
        assertThat($("title").first().getText()).isEqualTo("Page 2");
```

Where $ is our internal method for find list of elements by css selector.

It was working in 2.45 but stopped working on 2.46 just after HTMLUnit update, when I'm debugging the title is available in HtmlUnitWebElement object but getText method is not able to get the text because it got only <title> tag w/o content and closing tag. If you call this.element.asXml() you will get entire HTML content, something changed in HtmlUnit which casing this issue. I can change my Unit tests but seems like backward compatibility was broken so I'd like to make sure is it intended or not. Please let me know which approach you are going to chose.

**Comment by lukeis** [comment]
as I said, title and things in the head section are treated differently. I know some team members recently spent a good amount of time getting the HtmlUnitDriver to conform to selenium's test suite (which would include verifying that getting title would return an empty string).

I would recommend you update your tests to make the same assumption.

**Comment by filipcynarski** [comment]
Thank you :)
