### ISSUE TITLE
[🐛 Bug]: Not able to upload the File  if Hasauthentication used in our Scripst

### ISSUE THREAD

**Issue by gitnithin** [SeleniumHQ/selenium#11890]
### What happened?

I am using Cucumber framework with Java, For our app ,after we enter the URL , authentication popup appears to handel this i have tried with many methods finally i have used Hasauthentication to pass the credentials, there is one testcase to upload the files but i am not able to upload the files
if we are not using the hasAuthentication it worked file

Note: i have used below methods but it fails to pass the credentials so i have used HASAUTHENTICATION
1. pass the credentials in URL
2. Pass the credentials via AutoIT
3. Pass the credentials using ROBOT class

### How can we reproduce the issue?

```shell
1. use hasauthentication to pass the credentials for login
2. Try to upload the file
```

### Relevant log output

```shell
As testcase gets passed but file is not uploading so didn’t get any logs for that
```

### Operating System

Windows10

### Selenium version

4.7.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

have used Driver Manager

### Are you using Selenium Grid?

no

**Comment by krmahadevan** [comment]
@gitnithin - The latest released version of selenium is `4.8.3`. Please retry using that. If it still is a problem then please help create a sample that can be used to reproduce the problem.

**Comment by diemol** [comment]
Closing as we did not get more information.

**Comment by VickyZebra** [comment]
we are using selenium 4.11.0 with chrome driver, we encounter same issue

**Comment by titusfortner** [comment]
We need a reproducible example to debug it.

**Comment by VickyZebra** [comment]
How should I provide the example? our server is not a public server and it requests SSO which you can not access

**Comment by titusfortner** [comment]
What code are you using, a vague description of a problem for a feature that is generally working is insufficient. Can you turn on logging and give the output? There's nothing actionable in this issue right now.

**Comment by VickyZebra** [comment]
if I used the following method to avoid the login pop up
((HasAuthentication) driver).register(UsernameAndPassword.of(admin_usrname, admin_passwd));

I can not upload the local file to our web site by the following method(to simulate select a file from file browser to upload), the content is empty

        WebElement upload = driver.findElement(By.id("addResourceFileInput"));
        System.out.println("Files upload to resource: "+ResourceLoc.getAbsolutePath());
        upload.sendKeys(ResourceLoc.getAbsolutePath());

without ((HasAuthentication) driver).register(UsernameAndPassword.of(admin_usrname, admin_passwd)); everything works well

**Comment by titusfortner** [comment]
What are you using for the `uriPredicate`?
https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#register-basic-auth

Perhaps you only need it to match the first interaction with the site and then do not want it after?

**Comment by VickyZebra** [comment]
still no luck after updating the codes:
P.S the web url is: https://leopard.zpc-stage.zebra.com/ppme

            Predicate<URI> uriPredicate = uri -> uri.getHost().contains("leopard.zpc-stage.zebra.com");
            ((HasAuthentication) driver).register(uriPredicate, UsernameAndPassword.of(admin_usrname, admin_passwd));
