### ISSUE TITLE
[🐛 Bug]: GraphQL for stereotype is returning a string instead of array/dictionary

### ISSUE THREAD

**Issue by indeed-ted** [SeleniumHQ/selenium#11896]
### What happened?

Hitting the graphql route for nodesInfo -> nodes -> stereotypes works, but the response of stereotypes is a string instead of a proper JSON array/dictionary.

See example:

$ curl -X POST --data '{"query":"{nodesInfo { nodes { id, uri, status, slotCount, sessionCount, stereotypes }} }"}' -s selenium-grid.local/graphql
{
   "data" : {
      "nodesInfo" : {
         "nodes" : [
            {
               "id" : "b2d52875-c4b0-4a30-9de4-d827b32d6e44",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"MicrosoftEdge\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.25:5555"
            },
            {
               "id" : "903b886b-ee18-4638-a5c1-004ad14dcf61",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"chrome\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.23:5555"
            },
            {
               "id" : "9a0e4c70-8ebb-43a5-8a19-146f6f3415ae",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"firefox\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.21:5555"
            }
         ]
      }
   }
}

### How can we reproduce the issue?

```shell
Call this for any Selenium Grid, where the <LINK_TO_GRAPHQL_ENDPOINT> is selenium-grid.local/graphql.

curl -X POST --data '{"query":"{nodesInfo { nodes { id, uri, status, slotCount, sessionCount, stereotypes }} }"}' -s selenium-grid.local/graphql
```

### Relevant log output

```shell
$ curl -X POST --data '{"query":"{nodesInfo { nodes { id, uri, status, slotCount, sessionCount, stereotypes }} }"}' -s selenium-grid.local/graphql
{
   "data" : {
      "nodesInfo" : {
         "nodes" : [
            {
               "id" : "b2d52875-c4b0-4a30-9de4-d827b32d6e44",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"MicrosoftEdge\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.25:5555"
            },
            {
               "id" : "903b886b-ee18-4638-a5c1-004ad14dcf61",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"chrome\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.23:5555"
            },
            {
               "id" : "9a0e4c70-8ebb-43a5-8a19-146f6f3415ae",
               "sessionCount" : 0,
               "slotCount" : 1,
               "status" : "UP",
               "stereotypes" : **"[\n  {\n    \"slots\": 1,\n    \"stereotype\": {\n      \"browserName\": \"firefox\",\n      \"browserVersion\": \"110.0\",\n      \"platformName\": \"LINUX\",\n      \"se:noVncPort\": 7900,\n      \"se:vncEnabled\": true\n    }\n  }\n]"**,
               "uri" : "http://10.244.0.21:5555"
            }
         ]
      }
   }
}
```

### Operating System

Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1031-aws x86_64)

### Selenium version

N/A Only using GraphQL endpoint

### What are the browser(s) and version(s) where you see this issue?

N/A Only using GraphQL endpoint

### What are the browser driver(s) and version(s) where you see this issue?

N/A Only using GraphQL endpoint

### Are you using Selenium Grid?

4.8.1 (Using Helm Chart)

**Comment by titusfortner** [comment]
Checking in on the status of this one. We keep kicking it down the milestone road, want to see where it sits in priority list and if we know where we want to go with it.

**Comment by diemol** [comment]
The problem is that GraphQL does not provide a way to have a schema with a type structure to allow keys and any value. This is how stereotypes work. The value can be anything from a string to a complete JSON object. The current is the best we can do. 

If something changes and there is a way to provide the stereotypes in a better structure in GraphQL, please let us know, and we can find a way to improve this.
