### ISSUE TITLE
[🐛 Bug]: WebdriverWait Throwing java.lang.ClassCastException

### ISSUE THREAD

**Issue by tkumar18** [SeleniumHQ/selenium#11904]
### What happened?

While interacting with Webelement present under iFrame, we need to set the wait time before we perform any action with element. This is working if Element is loaded properly but in case of wait time it is throwing below error message:

new WebDriverWait(driver, Duration.ofSeconds(100))
                        .until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.id(fName)));
 new WebDriverWait(driver, Duration.ofSeconds(30))
                .until(ExpectedConditions
                        .visibilityOf(driver.findElement(By.cssSelector(locator))));

**Error- java.lang.classcastexception: class com.google.common.collect.maps$transformedentriesmap cannot be cast to class org.openqa.selenium.webelement**

### How can we reproduce the issue?

```shell
Steps:
- Navigate to url having iframe
- Switch to iframe using- new WebDriverWait(driver, Duration.ofSeconds(100))
                        .until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.id(fName)));
- Add Wait time for Visibility of Element- new WebDriverWait(driver, Duration.ofSeconds(30))
                .until(ExpectedConditions
                        .visibilityOf(driver.findElement(By.cssSelector(locator))));
I have also tried adding - ignore Exceptions but it doesn't work
```

### Relevant log output

```shell
java.lang.classcastexception: class com.google.common.collect.maps$transformedentriesmap cannot be cast to class org.openqa.selenium.webelement
```

### Operating System

Windows 11

### Selenium version

Java 4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Latest

**Comment by NickOppersdorff** [comment]
I have been seeing the same issue too in Java. https://github.com/SeleniumHQ/selenium/issues/11895

@tkumar18 do you run your tests locally or on a grid?

**Comment by tusharkr18** [comment]
Yes this is on Grid, I am using Browserstack. Unfortunately I cannot share the code coz of IP issue. But I noticed this issue only occurs post switching to iframe.

**Comment by NickOppersdorff** [comment]
> Yes this is on Grid, I am using Browserstack. Unfortunately I cannot share the code coz of IP issue. But I noticed this issue only occurs post switching to iframe.

My guess is that you would get the same issue if you did a search for a non-existent web element.

**Comment by diemol** [comment]
@tusharkr18 can you replicate this issue using Selenium Grid?

**Comment by diemol** [comment]
You can also share any code that helps to replicate the issue, not necessarily the one you use privately.

**Comment by diemol** [comment]
Closing as we did not get more feedback.
