### ISSUE TITLE
[🐛 Bug]: During test execution grid using different browsers. 

### ISSUE THREAD

**Issue by sravan-jessu** [SeleniumHQ/selenium#11909]
### What happened?

I am using latest selenium grid (v4.8.3) with selenium core lib of (v4.2.2), in between during test execution observed that Firefox and chrome browsers got launched even if we set to use desired capabilities of Microsoft Edge browser. can someone assist with what could went wrong? 

### How can we reproduce the issue?

```shell
Running multiple tests with having Microsoft Edge desired capabilities configuration
```

### Relevant log output

```shell
na
```

### Operating System

Windows 10

### Selenium version

4.2.2

### What are the browser(s) and version(s) where you see this issue?

Firefox 111, Chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 111*, Firefox 111.* 

### Are you using Selenium Grid?

4.8.3

**Comment by sravan-jessu** [comment]
Sorry @diemol, due to restrictions I cannot share code snippets or repository URL. the issue is occurring when we ran multiple tests, the first test using as expected browser but in between its using Firefox browser.

**Comment by diemol** [comment]
As the previous comment says, it does not need the same code you are using internally, it can be any code that helps reproduce the issue. We cannot troubleshoot this without a way to reproduce it, else the issue will be eventually closed.

**Comment by diemol** [comment]
Closing as we did not get more feedback.
