### ISSUE TITLE
[🚀 Feature]: py: make trio an optional package dependency

### ISSUE THREAD

**Issue by blueyed** [SeleniumHQ/selenium#11915]
### Feature and motivation

I think the dependency on trio in the Python package could be made optional: it appears to only be necessary for bidi support (via https://github.com/SeleniumHQ/selenium/commits/395a92669255cbf8d2f4efb5bcffa359b1507b3c/py/selenium/webdriver/common/bidi/cdp.py).  I am not sure though what this is exactly (used for/with).

It could be moved into an extra, to be installable using `selenium[trio]` or `selenium[bidi]`.

trio itself has quite a few deps, as of 0.22.0:
```
async-generator = ">=1.9"
attrs = ">=19.2.0"
cffi = {version = ">=1.14", markers = "os_name == \"nt\" and implementation_name != \"pypy\""}
idna = "*"
outcome = "*"
sniffio = "*"
sortedcontainers = "*"
```

Related commits: https://github.com/SeleniumHQ/selenium/commit/587106bf243da214b95e163f9cc3670df9c9fc56, https://github.com/SeleniumHQ/selenium/commit/6e59a16570be0635330b52f3bd2b70060ed78b16

### Usage example

This would allow to have fewer dev dependencies with Python projects, where selenium is used.

**Comment by titusfortner** [comment]
@blueyed can you make a PR for this?

**Comment by blueyed** [comment]
Done: https://github.com/SeleniumHQ/selenium/pull/11920

Is the name "bidi" good for this?
Do you have a reference to read up on what it is for?  That would also be the place to update docs with the PR then.

**Comment by diemol** [comment]
The conversation in the PR was not continued. This looks to be a "nice to have, "but as @AutomatedTester says, BiDi will be required in the future in all cases.
