### ISSUE TITLE
[🐛 Bug]: Exception 'internet explorer is not a valid browser' in IE after upgrading to 4.9.0

### ISSUE THREAD

**Issue by dyadav7** [SeleniumHQ/selenium#11928]
### What happened?

Updated to 4.9 and getting below error exception

          raise SeleniumManagerException(
           selenium.common.exceptions.SeleniumManagerException: Message: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']

### How can we reproduce the issue?

```shell
Use `self.browser = selenium.webdriver.ie.webdriver.WebDriver()`
```

### Relevant log output

```shell
File "D:\\scripts\python\test.py", line 44, in __init__
self.browser = selenium.webdriver.ie.webdriver.WebDriver()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\DIR1\\Python\Python311\Lib\site-packages\selenium\webdriver\ie\webdriver.py", line 127, in __init__
self.iedriver.path = DriverFinder.get_path(self.iedriver, options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\DIR1\\Python\Python311\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 43, in get_path
            raise err
File "C:\DIR1\\Python\Python311\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 40, in get_path
           path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\DIR1\\Python\Python311\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 84, in 
   driver_location
       raise SeleniumManagerException(
       selenium.common.exceptions.SeleniumManagerException: Message: internet explorer is not a valid browser.  Choose one of: ['chrome', 'firefox', 'edge', 'MicrosoftEdge', 'ie']
```

### Operating System

Windows 11

### Selenium version

4.9

### What are the browser(s) and version(s) where you see this issue?

IE

### What are the browser driver(s) and version(s) where you see this issue?

IE

**Comment by titusfortner** [comment]
I think we want to get rid of all of this - https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/selenium_manager.py#L75-L86

If the browser name doesn't match (and if using an options class it will), then the binary should give the correct error.
