### ISSUE TITLE
[🐛 Bug]: Not able to override the permission for audio/video and Sharing in Safari browser

### ISSUE THREAD

**Issue by ssk512** [SeleniumHQ/selenium#11926]
### What happened?

Trying to overide the audio,Video and sharing permission, not able to overide

I added permission in capabalities
const {Builder,Browser, By, Key, until, Capabilities} = require('selenium-webdriver');  

(async function launchSafari() {
let driver = await. new Builder.withCapabilities('microphone'  : 'Allow', 'camera':'Allow').forBrowser('safari').build();

  })();

### How can we reproduce the issue?

```shell
I added permission in capabalities
const {Builder,Browser, By, Key, until, Capabilities} = require('selenium-webdriver');  

(async function launchSafari() {
let driver = await. new Builder.withCapabilities('camera'  : 'Allow').forBrowser('safari').build();
  })();
```

### Relevant log output

```shell
copy paste the url after launch the browser
https://webrtc.github.io/samples/src/content/devices/input-output/
it should default allow microphone and camera
not allowing
```

### Operating System

macos Monterey

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

safari 13

### What are the browser driver(s) and version(s) where you see this issue?

Safaridriver with latestversion

**Comment by titusfortner** [comment]
The only documented things that Safari lets you pass in are these: https://developer.apple.com/documentation/webkit/about_webdriver_for_safari#2957227

Any additional things need to be requested of Apple.
