### ISSUE TITLE
[🐛 Bug]: Handshake response Exception either incorrect or hiding the real issue.

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11927]
### What happened?

Now that Selenium does not support JWP, we can remove some of the Handshake code bits.

This error in particular is masking the reason why it is not seen as a valid w3c payload:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.9.0/java/src/org/openqa/selenium/remote/ProtocolHandshake.java#L146

To hit that line, the response from the server had an HTTP code of 200, so the driver/grid thought it was valid. At the very least we need to include the capabilities that were returned, or what makes us think it isn't valid w3c.

### How can we reproduce the issue?

```shell
Unknown, because the exception is hiding the problem.
```

### Relevant log output

```shell
2023-04-22 19:53:02 FINE - Executing: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}, platformName: ANY, sauce:options: {access_key: foo..., name: waitForNonExistant[ANY_Chro..., tunnelIdentifier: bar, username: baz}}]}] 
2023-04-22 19:53:02 FINE - Exception: newSession Could not start a new session. Handshake response does not match any supported protocol
```

### Operating System

N/A

### Selenium version

Java 4.9

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

latest

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
I've added code to the exception so the response payload is printed and we can understand better what the real error is.

**Comment by ghost** [comment]
I am getting the same issue. Could not start a new session. Handshake response does not match any supported protocol .
How to fix this issue.

**Comment by ghost** [comment]
> I am getting the same issue. Could not start a new session. Handshake response does not match any supported protocol . How to fix this issue.

I am using these capabilities
Capabilities {app: lt://APP1016054147169287820..., appActivity: in.vymo.android.base.main.M..., appPackage: com.getvymo.android, appWaitActivity: *, appium:autoLaunch: true, appium:logLevel: error, appium:skipServerInstallation: false, autoAcceptAlerts: true, autoGrantPermissions: true, automationName: uiautomator2, build: Vymo Android, console: true, deviceName: Oppo.*, deviceOrientation: portrait, devicelog: true, idleTimeout: 900, isRealMobile: true, newCommandTimeout: 600, platformName: ANDROID, platformVersion: 11, timezone: UTC+05:30, visual: true}

**Comment by titusfortner** [comment]
All appium related capabilities need to be prepended with `appium:`
