### ISSUE TITLE
setting text of <input> elements fails with safari (version 2.47)

### ISSUE THREAD

**Issue by chris1248** [SeleniumHQ/selenium#1192]
I am trying to automate setting a file on an input element (using capybara btw):

<input type="file" style="width:150px;" data-reactid=".1.0.0.0.1:2.0">

like this:

find(".margin-t-s input").set(Rails.root.join("spec/fixtures/Test-export.json"))

but it ultimately fails. Nothing gets set on the element.
I found this old thread that seems related:
https://code.google.com/p/selenium/issues/detail?id=4220

But that was friggin nearly 4 years ago. Tell me that Selenium is not dead enough that an issue reported 4 years ago is still outstanding?

**Comment by titusfortner** [comment]
That isn't an open issue. Did you read the resolution and why your request isn't feasible on Safari? You'll need to use a different browser.
