### ISSUE TITLE
[🐛 Bug]: C# DevTools since ActiveSessionId is read only there is no way to change session to a different tab

### ISSUE THREAD

**Issue by alanbelanger** [SeleniumHQ/selenium#11934]
### What happened?

Using this closed issue as the only reliable source of information I could find on the topic, I'm trying to capture network events in a second tab in Chrome. The solution(s) documented in the ticket below all point to changing the ActiveSessionId
https://github.com/SeleniumHQ/selenium/issues/9798

Problem is that in C# the DevToolsSession has ActiveSessionId as readonly, so it cannot be changed:
https://github.com/SeleniumHQ/selenium/blob/c5f457e75dd46db2a586eba3edd0ed2379662543/dotnet/src/webdriver/DevTools/DevToolsSession.cs

I tried destroying the session object and recreating it, calling CloseDevToolsSession then GetDevToolsSession, being careful to destroy and recreate my handlers as well. Even closed the original tab so only the new tab was left. There seems to be no way to capture network events on another tab after the DevToolsSession is attached to the driver. 

Is there any reason this ActiveSessionId needs to be readonly? Is there any outside lower-level way to modify its value?

### How can we reproduce the issue?

```shell
public void AttachToTarget(string urlOrTitle)
{
        this.Stop();
        string targetId = null;
        var targets = _devToolSession.Domains.Target.GetTargets().Result;
        foreach (var target in targets)
        {
            if (target.Type == "page")
            {
                if (target.Title.Contains(urlOrTitle))
                {
                    targetId = target.TargetId;
                    string sessionId = _devToolSession.Domains.Target.AttachToTarget(targetId).Result;
                    // below won't work b/c ActiveSessionId is readonly
                    _devToolSession.ActiveSessionId = sessionId;
                    break;
                }
            }
        }
        _devToolSession.Domains.Target.SetAutoAttach().Wait();
        this.Start();

    }
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

Selenium.WebDriver .net 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 112.0.5615.138 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 112.0.5615.138

**Comment by alanbelanger** [comment]
Theoretically, this should work:

_devTools.CloseDevToolsSession();
_session = _devTools.GetDevToolsSession();

In practice, if your code is in a shared library external to your tests, the call to CloseDevToolsSession hangs forever. Got around this by calling in a different thread, and of course you need to restart your listeners, something like this:

await _session.Domains.JavaScript.DisableRuntime();
await _session.Domains.Network.DisableNetwork();
_session.DevToolsEventReceived -= HandleDevToolsConsole;

var task = Task.Run(() => _devTools.CloseDevToolsSession()).Wait(10000);
_session = _devTools.GetDevToolsSession();

await _session.Domains.JavaScript.EnableRuntime();
await _session.Domains.Network.EnableNetwork();
await _session.Domains.Target.SetAutoAttach();
_session.DevToolsEventReceived += HandleDevToolsConsole;

It mostly works, but I still get intermittent socket errors and it seems like a lot of code for what should be such a simple task.

**Comment by mcichonqa** [comment]
Hi I created similar issue about that, this is probably bug and no workaround exists. I tried use reflection for invoke StartSession method, but it didn't help, its something related with WS connections for tabs. 
Its not clear how it works and how should we use this for more than 1 tab. Could someone explain how we can work with it please?
https://github.com/SeleniumHQ/selenium/issues/11030

**Comment by nvborisenko** [comment]
@alanbelanger can you please re-test your approach with the latest v4.12.4?
```csharp
_devTools.CloseDevToolsSession();
_session = _devTools.GetDevToolsSession();
```

This area was improved significantly.

**Comment by alanbelanger** [comment]
This does work now and does not hang anymore when accessed via NuGet package. I don't seem to get socket errors either. 
Thanks @nvborisenko !

**Comment by nvborisenko** [comment]
Glad to hear.
