### ISSUE TITLE
[🚀 Feature]: webdriver bidi has added two new features recently

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#11932]
### Feature and motivation

https://github.com/w3c/webdriver-bidi/pull/410 shows that Webdriver Bidi has added two new features three days ago.

The features are:

- Network events for the request to be sent, and response started and completed: https://w3c.github.io/webdriver-bidi/#module-network
- Back channel for communicating with the client: https://w3c.github.io/webdriver-bidi/#type-script-Channel

### Usage example

Used to get network events from the browser and communicating with the client with webdriver bidi.

**Comment by diemol** [comment]
Please note that a feature added to the spec doesn't mean that it can be used right away. The feature still needs to be implemented by the browser drivers in order to be actually used. 

We will keep this open so we can implement it in Selenium when any of the drivers implement it.

**Comment by titusfortner** [comment]
We're tracking network in #11768 and the script module in #11767 
Are these separate concerns, or just updates to the things we haven't done, yet?

**Comment by ollie-iterators** [comment]
I am just checking out webdriver-bidi so that I can know what has changed recently. This is just a notice for the Selenium repository that things have been added to webdriver-bidi.

**Comment by ollie-iterators** [comment]
If you feel this is an unnecessary issue, then feel free to close it.

**Comment by ollie-iterators** [comment]
> Please note that a feature added to the spec doesn't mean that it can be used right away. The feature still needs to be implemented by the browser drivers in order to be actually used.
> 
> We will keep this open so we can implement it in Selenium when any of the drivers implement it.

Thanks for the information about that.

**Comment by titusfortner** [comment]
> just checking out webdriver-bidi so that I can know what has changed recently

This is going to be increasingly useful when we catch up on everything that's available. :)

**Comment by pujagani** [comment]
Thank you for bringing this to our notice. We are trying to keep a tab of what is coming in the spec and what browsers are implementing and also trying to add it to Selenium where possible. We also have plans to add few items the Selenium way and working towards it.

**Comment by titusfortner** [comment]
@pujagani I think we should close this and track our work in the github project and/or with the document you are using. What do you want to be the official record we are working off of? We just need to point to it.

**Comment by pujagani** [comment]
I think you are right. We can use both [Github](https://github.com/orgs/SeleniumHQ/projects/6/views/1 ) and the [doc](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing). Doc is more in-depth regarding what browsers have implemented and where we are on it.

**Comment by pujagani** [comment]
Please refer to the above links to track the progress of the BiDi work done in Selenium.
