### ISSUE TITLE
[🐛 Bug]: proxy with username and password does not work

### ISSUE THREAD

**Issue by kaixinwangzi1982** [SeleniumHQ/selenium#11936]
### What happened?

It does not work

### How can we reproduce the issue?

```shell
public static void main (String[] args) throws MalformedURLException {
    ChromeOptions browserOptions = new ChromeOptions();
    // Proxy started with https://github.com/diemol/squid-with-basic-auth
    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 3128));
    ClientConfig config = ClientConfig.defaultConfig()
      .baseUrl(new URL("http://192.168.1.7:4444"))
      .authenticateAs(new UsernameAndPassword("docker-proxy", "selenium"))
      .proxy(proxy);
    WebDriver driver = RemoteWebDriver.builder()
      .oneOf(browserOptions)
      .config(config)
      .build();
    driver.get("https://selenium.dev");
    driver.quit();
  }
```

### Relevant log output

Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 35934
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Exception in thread "main" java.lang.IllegalArgumentException: ClientConfig instances do not work for Local Drivers
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.getLocalDriver(RemoteWebDriverBuilder.java:348)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:370)
	at selenium.TestUA.main(TestUA.java:57)

```


### Operating System

Mac M1

### Selenium version

java 4.9.0

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111.0.5563.41

### Are you using Selenium Grid?

_No response_

**Comment by kaixinwangzi1982** [comment]
@diemol

**Comment by titusfortner** [comment]
There is a new constructor for local drivers that accepts ClientConfig instances. Can you try with that?

**Comment by titusfortner** [comment]
This was fixed with the new constructors.
