### ISSUE TITLE
[🚀 Feature]: Selenium Manager Verbose toggle

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11940]
### Feature and motivation

Selenium Manager respects Environment Variables for setting verbose output. Java does not allow users to dynamically set these, so the bindings should check for the system property and add the `--verbose` flag if found. 

Not sure on Java logs; can we check what the Logger Level is set to in order to toggle verbose? Ruby does this right now. Probably should see on all the bindings, but that's another issue for later.

### Usage example

```
System.setProperty("SE_VERBOSE", "true")
```

**Comment by diemol** [comment]
>Java does not allow users to dynamically set these

What do you mean? Java can read env vars as any other. Maybe I am missing something.

Also, I thought the idea was to respect the logging level so we use that when reading SM logs.

**Comment by titusfortner** [comment]
Java is the only language that can't set environment variables in code, and requires using system properties, so this issue is to allow Java users to make a one line change like the other languages. But users still have to set up logging anyway I guess. Let me look again.

**Comment by diemol** [comment]
Java can read the environment variable and pass it along when the Selenium Manager process is created.

**Comment by titusfortner** [comment]
Most testers find it easier to change a line of code than to futz with environment variables.

Once we merge https://github.com/SeleniumHQ/selenium/pull/11959
We can have them do:
```
Logger.getLogger(SeleniumManager.class.getName()).setLevel(Level.FINE);
Arrays.stream(Logger.getLogger("").getHandlers()).forEach(handler -> {handler.setLevel(Level.INFO);});
```

But I guess the bindings still need to be able to output those details, which requires the logging anyway. I'll close this one and I'll bring it up again if it seems like the right thing to do later. :)
