### ISSUE TITLE
[🐛 Bug]: Node removed after system standby

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#11948]
### What happened?

I did run a selenium standalone server, after the system powered on again from standby the standalone server was not functional.
After looking into the logs and the code i think `GridModel.purgeDeadNodes` was called by the 30s intervall before the heartbeat did update the timestamp in `nodePurgeTimes`.

It looks like there are two concurrent strategies to remove the deadNodes. One is X health checks failed will remove the node and one is time based. The time based strategy is failing in this case and will remove the only node for the standalone server.

This might be an edge case, but would like to share it here. 

PS: In this state the UI is showing 'Loading ...' constantly 

![image](https://user-images.githubusercontent.com/16140691/234312517-257b2280-e1ff-4eee-a1a1-11a0061a8879.png)

### How can we reproduce the issue?

```shell
Send the system into standby, right after the heartbeat did nodePurgeTimes for more than 30s and power it on again and hope for `GridModel.purgeDeadNodes` to run :D
```

### Relevant log output

```shell
09:40:20.401 INFO [GridModel.release] - Releasing slot for session id dec0a19e82c52ca30bb6179848cd5aa6
09:40:20.402 INFO [SessionSlot.stop] - Stopping session dec0a19e82c52ca30bb6179848cd5aa6
14:35:18.655 INFO [GridModel.purgeDeadNodes] - Switching Node http://127.0.0.1:64231 from UP to DOWN
14:35:18.658 INFO [GridModel.purgeDeadNodes] - Removing Node http://127.0.0.1:64231, DOWN for too long
```

### Operating System

Windows 10 x64

### Selenium version

Java 4.8.2

### What are the browser(s) and version(s) where you see this issue?

chrome 112

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 112

### Are you using Selenium Grid?

Standalone 4.8.2

**Comment by diemol** [comment]
@TamsilAmani is this what you are seeing sometimes?

**Comment by TamsilAmani** [comment]
Yes @diemol that's the issue I was talking about and currently working on. Do you have any suggestions for this?

**Comment by TamsilAmani** [comment]
@joerg1985 Can you help me reproduce this issue please? I was trying to follow your steps but `nodePurgeTimes` doesn't happen. I know the issue is there. Maybe I'm doing it wrong. I'm using this script:

```
const { Builder, Capabilities } = require("selenium-webdriver");
var capabilities = Capabilities.chrome();
(async function helloSelenium() {
    let driver = new Builder()
        .usingServer("http://192.168.1.2:4444")   
        .withCapabilities(capabilities)
        .build();
    try {
        await driver.get('http://www.google.com');
        await driver.sleep(120000)
    } finally {
        await driver.quit();
    }
})();  
```

**Comment by joerg1985** [comment]
I do not think there is code needed to reproduce the issue, but i might be wrong.

You could try to suspend `kill -STOP <pid>`, wait several minutes and resume `kill -CONT <pid>` the process.
While this have a look at the logs to check if the two log lines are printed.
Retry it several times if it is not working, it depends on the internal timers of the application.

PS: The Windows Resource Monitor does also support suspension of processes.

**Comment by joerg1985** [comment]
@TamsilAmani could you reproduce it?

**Comment by ecoms-ye** [comment]
```
02:52:09.049 INFO [GridModel.setAvailability] - Switching Node ... (uri: http://...:4444) from DOWN to UP
02:52:09.049 INFO [LocalDistributor.add] - Added node ... at http://...:4444. Health check every 120s
02:52:09.168 INFO [Standalone.execute] - Started Selenium Standalone 4.10.0 (revision c14d967899): http://...:4444
10:36:52.071 INFO [GridModel.purgeDeadNodes] - Switching Node http://...:4444 from UP to DOWN
11:40:45.268 INFO [GridModel.purgeDeadNodes] - Removing Node http://...:4444, DOWN for too long
```

Hello,

Similar issue can be reproduced every morning when I comeback to work.
It seems like after 8 or more hours, node would be removed automatically.
The UI is showing 'Loading ...' constantly too.

It can be solved by restart the selenium docker container,
but in the next morning, I would see it again.

- Operating System: macOS 13.4.1
- Selenium version: 4.10.0 (by using laravel dusk in docker)
- browser: chromium 114 (`seleniarm/standalone-chromium`)
- browser driver: chromedriver 114
- Selenium Grid: Standalone 4.10.0

**Comment by earthpyy** [comment]
> ```
> 02:52:09.049 INFO [GridModel.setAvailability] - Switching Node ... (uri: http://...:4444) from DOWN to UP
> 02:52:09.049 INFO [LocalDistributor.add] - Added node ... at http://...:4444. Health check every 120s
> 02:52:09.168 INFO [Standalone.execute] - Started Selenium Standalone 4.10.0 (revision c14d967899): http://...:4444
> 10:36:52.071 INFO [GridModel.purgeDeadNodes] - Switching Node http://...:4444 from UP to DOWN
> 11:40:45.268 INFO [GridModel.purgeDeadNodes] - Removing Node http://...:4444, DOWN for too long
> ```
> 
> Hello,
> 
> Similar issue can be reproduced every morning when I comeback to work. It seems like after 8 or more hours, node would be removed automatically. The UI is showing 'Loading ...' constantly too.
> 
> It can be solved by restart the selenium docker container, but in the next morning, I would see it again.
> 
> * Operating System: macOS 13.4.1
> * Selenium version: 4.10.0 (by using laravel dusk in docker)
> * browser: chromium 114 (`seleniarm/standalone-chromium`)
> * browser driver: chromedriver 114
> * Selenium Grid: Standalone 4.10.0

I'm having the same problem, same docker image/OS.

For me, node was down ~40 mins after the last session.

```
selenium-1  | 2023-06-28T18:55:24.320609337Z 18:55:24.320 INFO [GridModel.release] - Releasing slot for session id 5285bbe0ce37c95c86f71216f2407959
selenium-1  | 2023-06-28T18:55:24.321331170Z 18:55:24.320 INFO [SessionSlot.stop] - Stopping session 5285bbe0ce37c95c86f71216f2407959
selenium-1  | 2023-06-28T18:55:24.321339170Z 18:55:24.321 WARN [LocalNode.lambda$new$5] - Removing Downloads folder associated with 5285bbe0ce37c95c86f71216f2407959
selenium-1  | 2023-06-28T18:55:24.321449962Z 18:55:24.321 WARN [LocalNode.lambda$new$6] - Removing Uploads folder associated with 5285bbe0ce37c95c86f71216f2407959
selenium-1  | 2023-06-28T19:33:49.770289177Z 19:33:49.766 INFO [GridModel.purgeDeadNodes] - Switching Node http://192.168.80.3:4444 from UP to DOWN
selenium-1  | 2023-06-28T19:38:25.724137218Z 19:38:25.718 INFO [GridModel.purgeDeadNodes] - Removing Node http://192.168.80.3:4444, DOWN for too long
```

**Comment by titusfortner** [comment]
@joerg1985 / @diemol can we get a status update for this? If we know the fix but don't have bandwidth for it, can we add a help wanted label?

Thanks

**Comment by joerg1985** [comment]
@titusfortner i would suggest to close this, the original issue has been fixed and i was waiting for the conformation of @TamsilAmani.

If the issue reported by @ecoms-ye and @earthpyy is still present, a new issue should be raised with a full description how to reproduce it.
