### ISSUE TITLE
[🚀 Feature]: Add an option to remove "remote-allow-origins" from ChromeOptions

### ISSUE THREAD

**Issue by gtach2o** [SeleniumHQ/selenium#11949]
### Feature and motivation

After this happend 
```java
    // Allowing any origin "*" might sound risky but an attacker would need to know
    // the port used to start DevTools to establish a connection. Given these sessions
    // are relatively short-lived, the risk is reduced. Also, this will be removed when
    // we only support Java 11 and above.
    addArguments("--remote-allow-origins=*");
```
our tests stoped working. We can't update to Selenium 4.8.2 or higher
We awlays use  latest chrome driver, current is 112.0.5615.49
JDK native http client 
Java 20 
and everything was working fine until 4.8.2 released
`{args=[--remote-allow-origins=*,` is breaking our automation.
How to remove it from default chrome options? We don't need it. 

### Usage example

removeArguments("--remote-allow-origins=*");

**Comment by diemol** [comment]
What error do you get?

**Comment by gtach2o** [comment]
> What error do you get?

Well, there is no exact error I can share. Adding `--remote-allow-origins=*` in some way affects the iteraction with browser.
Next step after click fails, seems like synchronization doesn't work properly, Selenium doesn't wait properly for page loading.
When we swtich back to `4.8.1` everything works with no issue.

**Comment by gtach2o** [comment]
Maybe adding `--remote-allow-origins=*` does help when netty is still used. 
But have you tested it with `org.seleniumhq.selenium:selenium-http-jdk-client:4.8.2` and `System.setProperty("webdriver.http.factory", "jdk-http-client");` ?

**Comment by titusfortner** [comment]
@diemol are we setting it based on the condition that system property is not set?

**Comment by gtach2o** [comment]
There is no condition 
https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/chromium/ChromiumOptions.java#L138

**Comment by gtach2o** [comment]
Actually our tests fail with 
```
org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression 
```
And I have just noticed this
https://www.selenium.dev/blog/2023/invalid-selector-exception-has-changed/

> The expected result before this change would be that the driver waits until the timeout expires and then throw an InvalidSelectorException.

> This doesn’t make much sense because a broken/invalid selector would never fix itself, and hence should throw immediately.

Really? What about SPA when click can change DOM without page reload? The xpath is valid. 

> Please note that this may have an impact on backwards compatibility

Why it was released under `4.8.2` and not `5.0.0` ?

**Comment by gtach2o** [comment]
Got it working after adding `InvalidSelectorException` into `catch`
Tested with `4.9.0`
- `--remote-allow-origins=*` doesn't affect `jdk-http-client` usage.

I was misled by the lots of important changes made in just a patch release. 

Thank you everyone!

**Comment by titusfortner** [comment]
1. We do not do semantic versioning because there are too many different changes that need to be made in different languages
2. That "breaking change" was a bug fix not a feature change. If you get `InvalidSelectorException` you will never locate an element with it, regardless of page changes. This is why we changed the error; important information about your code was being hidden by an unrelated error.

**Comment by titusfortner** [comment]
I'm going to reopen this because I still think we should consider only setting that value if users are using the old http client. 
We can close once we decide if we want to do that or not.

**Comment by diemol** [comment]
Makes sense, there is no need to add this option when the Java 11 client is used.
