### ISSUE TITLE
[🐛 Bug]: Inconsistently throwing WebDriverException with invalid Browserstack userName and accessKey

### ISSUE THREAD

**Issue by dornelas-hw** [SeleniumHQ/selenium#11943]
### What happened?

When trying to create a new RemoteWebDriver with invalid username and accesskey, it does not always throw a WebDriverException.  I have a test for this that is randomly failing because we are expecting an exception to be thrown.

What happens instead is that the driver was created but the driver's capabilities just show {{ "message": "Invalid username or password"}} and there is no session id.  So what happens is the test continues and fails with a timeout exception instead when it waits for initial page to load.

### How can we reproduce the issue?

```shell
Here is the snippet of where we create the driver for chrome:
 Dictionary<string, object> browserstackOptions2 = new Dictionary<string, object>{
                    {"projectName", "Blah"},
                    {"buildName", "Blah2"},
                    {"sessionName", "sessionName" },
                    {"browserVersion", "latest"},
                    {"networkLogs", "true"},
                    {"debug", "true"},
                    {"userName", "invalidUserName" },
                    {"accessKey", "invalidAccessKey" }
                };
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.AddAdditionalOption("bstack:options", browserstackOptions2);
        chromeOptions.AddAdditionalOption("siteBase", "https://www.google.com/");
        chromeOptions.AddAdditionalOption("environmentId", "abc");
        chromeOptions.AddAdditionalOption("testRetries", "0");
        chromeOptions.AddArgument("no-sandbox");
        string BrowserStackHubUrl = "https://hub-cloud.browserstack.com/wd/hub";
        var driver = new OpenQA.Selenium.Remote.RemoteWebDriver(new Uri(BrowserStackHubUrl), chromeOptions);
```

### Relevant log output

```shell
Test method threw exception OpenQA.Selenium.WebDriverTimeoutException, but exception OpenQA.Selenium.WebDriverException was expected. Exception message: OpenQA.Selenium.WebDriverTimeoutException: Timed out after 60 seconds: Timed out waiting for google page to load
  Stack Trace:
     at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition, CancellationToken token)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Healthwise.QA.WebDriver.Management.Test.Pages.GooglePage..ctor(WebDriverManager`1 manager) in D:\a\qa.webdriver.management\qa.webdriver.management\Healthwise.QA.WebDriver.Management.Test.Selenium\Pages\GooglePage.cs:line 33
--- End of stack trace from previous location ---
   at Healthwise.QA.WebDriver.Management.Managers.AppManager`2.OpenApp[CustomPage]() in D:\a\qa.webdriver.management\qa.webdriver.management\Healthwise.QA.WebDriver.Management\Managers\AppManager.cs:line 158
   at Healthwise.QA.WebDriver.Management.Managers.AppManager`2.OpenApp() in D:\a\qa.webdriver.management\qa.webdriver.management\Healthwise.QA.WebDriver.Management\Managers\AppManager.cs:line 79
   at Healthwise.QA.WebDriver.Management.Test.Selenium.SeleniumTests.RemoteOverrideConfiguration() in D:\a\qa.webdriver.management\qa.webdriver.management\Healthwise.QA.WebDriver.Management.Test.Selenium\SeleniumTests.cs:line 95
```

### Operating System

Windows 10

### Selenium version

C# 4.0.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 112 and Firefox 112

### What are the browser driver(s) and version(s) where you see this issue?

RemoteWebDriver

**Comment by titusfortner** [comment]
> the driver's capabilities just show {{ "message": "Invalid username or password"}} and there is no session id

Can you provide the details on this? It sounds like it might be a Browser Stack issue?

**Comment by diemol** [comment]
I recommend upgrading to the most recent Selenium version and check how to set the [options for BrowserStack](https://www.browserstack.com/automate/capabilities). If that does not help, please reach out to their customer service. If you need more help, I will leave some links below where you can reach our community chat.

**Comment by dornelas-hw** [comment]
I took a closer look at all requests being made and it looks like browserstack is not giving consistent responses since it doesn't always return error field.  This is the response when it doesn't throw the WebDriverException: {"value":{"message":"Invalid username or password"},"sessionId":"","status":13} 
and this is response when we see WebDriverException: {"value":{"error":"Invalid username or password","message":"Invalid username or password"},"sessionId":"","status":13}

I'll be reaching out to BrowserStack next.
