### ISSUE TITLE
[🐛 Bug]: Problem with special character in username

### ISSUE THREAD

**Issue by MuhSchaf** [SeleniumHQ/selenium#11947]
### What happened?

Hi dear Selenium-Team,

Selenium manager can’t find browser driver in user directory when the username has special characters inside. Selenium manager throws an DriverServiceNotFound exception.
To avoid this issue the browser driver has to put in the same directory as the program executable.

### How can we reproduce the issue?

```shell
To reproduce create a Windows Username with a special character like René or Björgensen. After this use Selenium in its default configuration.
```

### Relevant log output

```shell
Exception:
OpenQA.Selenium.DriverServiceNotFoundException: The file C:\Users\RenÃ©\.cache\selenium\chromedriver\win32\112.0.5615.49\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
   at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
   at OpenQA.Selenium.Chromium.ChromiumDriverService..ctor(String executablePath, String executableFileName, Int32 port, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService..ctor(String executablePath, String executableFileName, Int32 port)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService(String driverPath, String driverExecutableFileName)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService(String driverPath)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
```

### Operating System

Windows 10

### Selenium version

4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome (Version 111), Edge 

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver were automatically downloaded by Selenium

**Comment by diemol** [comment]
Please try 4.9.0 and let us know.

**Comment by MuhSchaf** [comment]
Thank you for the fast reply.
Today the changeover to 4.9.0 has been approved by my superior. I will update this ticket, when i have new insights.
Have a great week.

**Comment by MuhSchaf** [comment]
Update:

After the update was implemented the driver can be found. But as the following exception suggest it can't start the driverService.
The Exception only occurs when (again) the Windows Username has a special character.

System.ComponentModel.Win32Exception (2): Das System kann die angegebene Datei nicht finden _[engl: The system cannot find the specified file.]_.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)

**Comment by diemol** [comment]
I thought this was an issue in the C# code but it is actually an issue in the Rust code. @bonigarcia, do you have a moment to check?

**Comment by bonigarcia** [comment]
> I thought this was an issue in the C# code but it is actually an issue in the Rust code.

@diemol How do you know it is a Rust problem?

I tried this on a Windows machine, forcing to use a home folder containing an special character (`René`), and it seems to work as expected:

```
     Running `target\debug\selenium-manager.exe --browser chrome --debug`
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\=\\\\!\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=112.0.5615.138\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 112.0.5615.138
DEBUG   Detected browser: chrome 112
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_112
DEBUG   Required driver: chromedriver 112.0.5615.49
DEBUG   Running command: "chromedriver --version"
DEBUG   Output: ""
DEBUG   Driver URL: https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_win32.zip
DEBUG   File extracted to C:\Users\René\.cache\selenium\chromedriver\win32\112.0.5615.49\chromedriver.exe (12764160 bytes)
INFO    C:\Users\René\.cache\selenium\chromedriver\win32\112.0.5615.49\chromedriver.exe
```

```
     Running `target\debug\selenium-manager.exe --browser chrome --debug --output json`
{
  "logs": [
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Using shell command to find out chrome version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Running command: \"set PFILES=%PROGRAMFILES: (x86)=%&& wmic datafile where name='!PFILES:\\\\=\\\\\\\\!\\\\\\\\Google\\\\\\\\Chrome\\\\\\\\Application\\\\\\\\chrome.exe' get Version /value\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Output: \"\\r\\r\\n\\r\\r\\nVersion=112.0.5615.138\\r\\r\\n\\r\\r\\n\\r\\r\\n\\r\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "The version of chrome is 112.0.5615.138"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Detected browser: chrome 112"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_112"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Required driver: chromedriver 112.0.5615.49"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Running command: \"chromedriver --version\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Output: \"\""
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "Driver URL: https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_win32.zip"
    },
    {
      "level": "DEBUG",
      "timestamp": 1683214168,
      "message": "File extracted to C:\\Users\\René\\.cache\\selenium\\chromedriver\\win32\\112.0.5615.49\\chromedriver.exe (12764160 bytes)"
    },
    {
      "level": "INFO",
      "timestamp": 1683214169,
      "message": "C:\\Users\\René\\.cache\\selenium\\chromedriver\\win32\\112.0.5615.49\\chromedriver.exe"
    }
  ],
  "result": {
    "code": 0,
    "message": "C:\\Users\\René\\.cache\\selenium\\chromedriver\\win32\\112.0.5615.49\\chromedriver.exe"
  }
}
```

My guess is that the problem is the parsing of the JSON output in the dotnet bindings.

@MuhSchaf You can isolate the Rust side by running Selenium Manager separately. You can get the Windows binary from here:

https://github.com/SeleniumHQ/selenium/raw/trunk/common/manager/windows/selenium-manager.exe

... and then, you should be able to run the following command from the shell:

```
selenium-manager --browser chrome --debug
```

**Comment by diemol** [comment]
Yeah, you are right, I think I got carried away while debugging and missed an extra test. Will have a look again.
