### ISSUE TITLE
[🐛 Bug]: java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable

### ISSUE THREAD

**Issue by tusharw02** [SeleniumHQ/selenium#11958]
### What happened?

**Selenium : 4.9.0**
Code - 
**ChromeOptions opt = new ChromeOptions();
opt.setBinary("C:\Users\Tushar\AppData\Local\Google\Chrome\Application\chrome.exe");
WebDriver driver = new ChromeDriver();
driver.get("https://www.google.com/");**

I am trying to run above code with Selenium 4.9.0 and expecting this should not ask for driver setup due to selenium manager.
But getting this error : java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable

### How can we reproduce the issue?

```shell
Selenium : 4.9.0
Code - 
ChromeOptions opt = new ChromeOptions();
opt.setBinary("C:\Users\Tushar\AppData\Local\Google\Chrome\Application\chrome.exe");
WebDriver driver = new ChromeDriver();
driver.get("https://www.google.com/");
```

### Relevant log output

```shell
java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable; for more information on how to install drivers, see https://www.selenium.dev/documentation/webdriver/getting_started/in
stall_drivers/
        at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
        at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:33)
        at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:98)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
        at Test.initilization(Test.java:21)
```

### Operating System

Windows 10

### Selenium version

Java - 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 112.0.5615.138

### What are the browser driver(s) and version(s) where you see this issue?

NA - Its Selenium Manager I am using, No browser driver.

### Are you using Selenium Grid?

NA

**Comment by diemol** [comment]
But you are not using the options in the `ChromeDriver` instantiation. 

Aside of that, are you behind a proxy?

**Comment by tusharw02** [comment]
@diemol Yes, behind a proxy.

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        options.setBinary("C:\\Users\\Tushar\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe");

        WebDriver driver = new ChromeDriver(options);

        driver.get("https://www.google.com/");

**Error** 
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable

**Comment by tusharw02** [comment]
@diemol Also tried with WebDriver Manager - but getting - **Exception in thread "main" io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://chromedriver.storage.googleapis.com/**

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        options.setBinary("C:\\Users\\Tushar\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe");
        WebDriverManager.chromedriver().proxyUser(proxyUserId).proxyPass(proxyPwd).proxy(proxy).useMirror().setup();
        WebDriver driver = new ChromeDriver(options);
        driver.get("https://www.google.com/");

**Comment by titusfortner** [comment]
How is the browser accessing the internet if it is behind a proxy?

**Comment by diemol** [comment]
This will be implemented by https://github.com/SeleniumHQ/selenium/issues/11294, please add yourself as a watcher and try again once we release that feature.
