### ISSUE TITLE
[🐛 Bug]: Internet Explorer automatically recovers from a crash and cannot obtain the handle

### ISSUE THREAD

**Issue by iamxiaojianzheng** [SeleniumHQ/selenium#11956]
### What happened?

When I am using selenium to drive an IE page with office word embedded, after refreshing the page, an automatic crash recovery prompt appears. 

![7d3050fe56d7fcf791cc520df8be665](https://user-images.githubusercontent.com/29248764/234739032-f4a5da91-a09e-4f2e-950b-f87964a22c2e.jpg)

selenium then cannot control the page, but I call 'getWindowHandles()', You can still see the handle of the page, 
but you cannot use the handle to switch to the page.

 And the number of Windows is inconsistent with the number of handles. The handle corresponding to the crashed page does not disappear.

### How can we reproduce the issue?

```shell
Sorry, this is a problem encountered in an Intranet environment. 

I can't find anything like it on the Internet.
```

### Relevant log output

```shell
None
```

### Operating System

Windows10

### Selenium version

Java 4.8.3

### What are the browser(s) and version(s) where you see this issue?

IE11

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.8.1 Win32

**Comment by diemol** [comment]
We are recommending to use IE Mode in Edge these days. But in any case, without a way of reproducing the issue, this will be more likely treated as a question.

**Comment by titusfortner** [comment]
I'm not sure selenium can be expected to recover from the page crashing, even if IE manages to.

**Comment by diemol** [comment]
Closing as we did not get any more input.
