### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: Unable to write Firefox profile

### ISSUE THREAD

**Issue by kevinyeah00** [SeleniumHQ/selenium#11950]
### What happened?

When I use selenium in firefox(Windows10), the terminal shows:

Something generates in /c/xxxxx/profile, but it still does not work.

ps: This code runs normally on my linux OS

### How can we reproduce the issue?

```shell
The command I use is below:

firefox --marionette -profile /c/xxxxx/profile

The relative code is below:
```python
firefox_options = Options()
firefox_options.add_argument("--profile /c/xxxxx/profile")
driver = webdriver.Firefox(options=firefox_options)
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "helper.py", line 46, in <module>
    driver = webdriver.Firefox(options=firefox_options)
  File "C:\Users\11231\.conda\envs\test\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 201, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\11231\.conda\envs\test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\11231\.conda\envs\test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\11231\.conda\envs\test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\11231\.conda\envs\test\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Failed to set preferences: Unable to write Firefox profile: 系统找不到指定的路径。 (os error 3)
```

### Operating System

Windows 10

### Selenium version

python 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 112.0.1

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.32.2

**Comment by diemol** [comment]
What happens if you do not use the profile?

**Comment by titusfortner** [comment]
It looks like you might not have correct permissions to that directory?

**Comment by kevinyeah00** [comment]
> What happens if you do not use the profile?

I want to  connect selenium to an existing browser,  using profile like that way can achieve it on Linux OS. I don't know how to onnect to an existing browser without using profile

**Comment by diemol** [comment]
Why do you mention Selenium Manager? I do not see it on the logs. 

Has this worked before or are you trying out things?

**Comment by kevinyeah00** [comment]
> It looks like you might not have correct permissions to that directory?

When I'm under administrator permission, it still doesn't work, and terminal shows the same message.

**Comment by kevinyeah00** [comment]
> Why do you mention Selenium Manager? I do not see it on the logs.
> 
> Has this worked before or are you trying out things?

sry, that's my old bug, I solved it but forgot to change the title

**Comment by diemol** [comment]
So, has this worked before or are you trying something new?

**Comment by kevinyeah00** [comment]
this worked welll on linux OS, but when it comes to windows10, it can not work

**Comment by diemol** [comment]
OK, so it seems this is a question about getting things working on Windows. I will share some links below where you can ask that.

**Comment by titusfortner** [comment]
If there is a bug here where the same code works in Linux but not on windows, it's likely something that Mozilla would need to fix.
