### ISSUE TITLE
[🐛 Bug]: DriverFinder is broken for Safari Technology Preview

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#11952]
### What happened?

The code is always locating the driver at `/usr/bin/safaridriver` (because it is on PATH and we are evaluating that first). We may need to go back to hard coding the paths until we let Selenium Manager process PATH first (#11356) 

### How can we reproduce the issue?

```shell
SafariOptions options = new SafariOptions();
options.setUseTechnologyPreview(true);
driver = new SafariDriver(service, options);
```

### Relevant log output

```shell
> 2023-04-25 13:26:16 FINE (org.openqa.selenium.remote.RemoteWebDriver) - Exception: newSession Could not start a new session. Response code 500. Message: Could not create a session: A browser with name 'Safari Technology Preview' version '(null)' could not be found on the system.
```

### Operating System

Mac

### Selenium version

Java 4.9

### What are the browser(s) and version(s) where you see this issue?

Safari Technology Preview

### What are the browser driver(s) and version(s) where you see this issue?

safaridriver

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
if anyone sees this and needs it, this works:

```
  SafariTechPreviewDriverService service = new SafariTechPreviewDriverService.Builder()
          .usingDriverExecutable(new File("/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver"))
          .build();
  driver = new SafariDriver(service, new SafariOptions().setUseTechnologyPreview(true));
```

**Comment by diemol** [comment]
Made a simple fix while we work on the linked issue about `PATH`.
