### ISSUE TITLE
Export tests suite results - list of test cases not completed

### ISSUE THREAD

**Issue by calonne** [SeleniumHQ/selenium#1195]
When i used Export test suite resutls , all tests cases are not decribed, 
Selenium tests results modules truncates the list of tests cases details.

The suite contains 1300 tests cases

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
