### ISSUE TITLE
[🚀 Feature]: WebDriver-BiDI: Support for "Preload Scripts"

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#11979]
### Feature and motivation

WebDriver BiDi supports the "bootstrap script" feature under the name "Preload Scripts" now. Given that this was a highly requested feature in the past it would  be great to see it implemented in Selenium.

WebDriver BiDi spec: https://w3c.github.io/webdriver-bidi/#preload-scripts

Details: Once such preload scripts have been added they are automatically evaluated or installed for each and every newly created browsing context. With their help eg. Selenium atoms could easily be installed without having to transfer them for each and every operation.

### Usage example

Each of the required commands has a related WebDriver test. Those can be found at:

* [script.addPreloadScript](https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/bidi/script/add_preload_script)
* [script.removePreloadScript](https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/bidi/script/remove_preload_script)

**Comment by TamsilAmani** [comment]
Working on this feature.

**Comment by titusfortner** [comment]
This has been implemented in ruby and JS and was recently fixed in Java. I'm closing since we'll be tracking updates to other bindings in another document.
