### ISSUE TITLE
[🐛 Bug]: Element Location Does not Update

### ISSUE THREAD

**Issue by aliraza948** [SeleniumHQ/selenium#11977]
### What happened?

When i try to take position of element for click by pyautogui.
with this method:
driver.find_element(B.XPATH,"<path>").location
driver.find_element(B.XPATH,"<path>").rect
both are giving same value of 'x' and 'y' but its not update on scroll

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
import pandas as pd
import pyautogui as aut
import time,random
#s=range(0,10)
opt=webdriver.ChromeOptions()
opt.add_experimental_option('debuggerAddress','127.0.0.1:9233')
b=webdriver.Chrome(options=opt)
b.get('https://www.google.com')
print(b.find_element(By.XPATH,"//input[@name=\'q\'] | //textarea[@name=\'q\']").rect)
```

### Relevant log output

```shell
{'height': 25, 'width': 489, 'x': 231, 'y': 38}
```

### Operating System

Window 10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

112.0

### What are the browser driver(s) and version(s) where you see this issue?

112.0

**Comment by diemol** [comment]
I am not sure what you are trying to do, you mention scrolling but the code does not reflect that. Have you checked the docs for that? https://www.selenium.dev/documentation/webdriver/actions_api/wheel/

**Comment by joerg1985** [comment]
I also stumbled on this, the [w3c-spec](https://www.w3.org/TR/webdriver1/#get-element-rect) has a note to this behaviour.

The position is `relative to the current browsing context’s document element` and this will not change while scrolling.
Screenshots are relative to the viewport. e.g. If you would try to draw a rectangle over the element you will fail.

@aliraza948 is this your issue?

I think there is no `w3c-spec` way to get the rectangle inside the screenshot.
You should be able to get the rectangle using javascript.

@diemol is there a way to get the rectangle inside the screenshot in a `w3c-spec` way?
This should at least handle the viewport and the os zoom level (`window.devicePixelRatio`)
