### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by NazariGamer** [SeleniumHQ/selenium#11976]
### What happened?

With Chrome version 112, Python 3.11.3, Oracle Linux 8.7  and Selenium 4.9.0:

After starting up, program crashes:

`selenium.common.exceptions.sessionnotcreatedexception: Message: session not created: This version of ChromeDriver only supports Chrome version 110 Current browser version is 112.0.5615.165 with binary path /usr/bin/google-chrome`

After checking I can see this in my home dir:

`~/.cache/selenium/chromedriver/linux64/110.0.5481.77/chromedriver`

On the command line:

`google-chrome --version`

gives:

`Google Chrome 112.0.5615.165`

Not sure why ChromeDriver 112 is not installed? Same program on Mac works as expected.

Any ideas?

### How can we reproduce the issue?

```shell
Reproduce environment as above and run following Python script:

from selenium import webdriver
from fake_useragent import UserAgent

options = webdriver.ChromeOptions()
options.add_argument("--headless=new")

ua = UserAgent(use_external_data=True)
userAgent = ua.random

browser = webdriver.Chrome(options=options)

browser.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

browser.execute_cdp_cmd('Network.setUserAgentOverride', {"userAgent": userAgent})

browser.get("https://www.google.com")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "~/oparkingbot/oparkingbot/parkingbot-init.py", line 16, in <module>
    browser = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 112.0.5615.165 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x561fe800fd93 <unknown>
#1 0x561fe7dde2d7 <unknown>
#2 0x561fe7e0b2f4 <unknown>
#3 0x561fe7e0617b <unknown>
#4 0x561fe7e02a3d <unknown>
#5 0x561fe7e474f4 <unknown>
#6 0x561fe7e3e353 <unknown>
#7 0x561fe7e0de40 <unknown>
#8 0x561fe7e0f038 <unknown>
#9 0x561fe80638be <unknown>
#10 0x561fe80678f0 <unknown>
#11 0x561fe8047f90 <unknown>
#12 0x561fe8068b7d <unknown>
#13 0x561fe8039578 <unknown>
#14 0x561fe808d348 <unknown>
#15 0x561fe808d4d6 <unknown>
#16 0x561fe80a7341 <unknown>
#17 0x7f99c4f561da start_thread
```

### Operating System

Oracle Linux 8.7

### Selenium version

Selenium 4.9.0  Python 3.11.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 112

### What are the browser driver(s) and version(s) where you see this issue?

chromdriver 110

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Two possibilities I can think of.
The first is that you have an old version of the driver in a directory on PATH. This seems unlikely if there is an updated one in the Selenium cache. But do a which chromedriver just to check. 
The second is that the driver is looking at a different installation of Chrome than Selenium. Try specifying the binary location in the chrome options class.
Ideally you can turn on logging to see what is happening, but I don't have a python example for this handy. I can try to look later if neither of these help.

**Comment by NazariGamer** [comment]
Hi thanks for looking into this. I did some investigation based on what you said. I was mixing selenium with webdriver-manager and chrome driver-autoinstall and I guess this created a bit of a mess. Now back to selenium only and working fine. The only thing is when I run "which chromedriver" I get an error:

`/usr/bin/which: no chromedriver in (/home/exelanz/.local/bin:/home/exelanz/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)`

I was expecting the chromdwriver to be on the path...?

**Comment by diemol** [comment]
That is expected, there is no need to have ChromeDriver anywhere on the `PATH`, Selenium Manager will get that ready for you. 

Thanks for letting us know things worked out. Closing this.

**Comment by NazariGamer** [comment]
Cool. Thanks!
