### ISSUE TITLE
[🚀 Feature]: add filters in Selenium grid 4 for nodes("browserName":"chrome","browserVersion":"110.0","platformName":"LINUX")

### ISSUE THREAD

**Issue by krishtoautomate** [SeleniumHQ/selenium#11987]
### Feature and motivation

[🚀 Feature]: add filters in Selenium grid 4 for nodes("browserName":"chrome","browserVersion":"110.0","platformName":"LINUX")

grid is showing different versions of chrome, firefox, appium(ios/android) based on nodes connected.

is it possible to add some drop-down filters to see only chrome, specific version, platformName etc

### Usage example

grid is showing different versions of chrome, firefox, appium(ios/android) based on nodes connected.

is it possible to add some drop-down filters to see only chrome, specific version, platformName etc.

**Comment by diemol** [comment]
Where? Is this the Grid UI?

**Comment by krishtoautomate** [comment]
Yes, in the grid UI

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/20734341/235980519-805300c4-69f2-412f-8a77-11a88e7d8c36.png">

**Comment by ksingha161** [comment]
can we also add `"networkname:applicationName":"someName", "nodename:applicationName":"someName"` in the grid UI?

**Comment by krishtoautomate** [comment]
Need some string/value to search/show total count of ios nodes, android nodes, chrome nodes etc. in GRID UI

<img width="1338" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/20734341/89fe7625-2b8b-4c82-b9b1-66098eb04387">
