### ISSUE TITLE
[🚀 Feature]: Add option to use chromedriver managed by Selenium Manager if PATH version not compatible

### ISSUE THREAD

**Issue by stanhu** [SeleniumHQ/selenium#11989]
### Feature and motivation

We have a number of engineers who have `chromedriver` managed by Homebrew. When Chrome updates, they need to keep up-to-date with the latest `chromedriver`. Currently `selenium-webdriver` will download the right version of `chromedriver` ONLY if the Homebrew version is NOT installed.

Uninstalling the Homebrew version doesn't seem like it should be necessary. We would much prefer if `selenium-webdriver` would download and use the right version of `chromedriver` if the version in `PATH` isn't compatible. 

One possible fix would be to drop the `Platform.find_binary` call here:

https://github.com/SeleniumHQ/selenium/blob/d530584d2ef0a56ec98f350583ca374cd1fc1649/rb/lib/selenium/webdriver/common/driver_finder.rb#L26-L29

As far as I understand, `selenium-manager` already looks in the `PATH`:

https://github.com/SeleniumHQ/selenium/blob/b579892869b4d68455bf37d9234cc69bd5ca9f39/rust/src/lib.rs#L318

### Usage example

This would allow the Homebrew version of `chromedriver` to coexist with the version managed by `selenium-webdriver`.

**Comment by stanhu** [comment]
A workaround is to set the `PATH` to give precedence to the binary detected by `selenium-manager`:

```
chrome_options = Selenium::WebDriver::Chrome::Options.chrome
chromedriver_path = File.dirname(Selenium::WebDriver::SeleniumManager.driver_path(chrome_options))
```

Inside the `Capybara.register_server`, set the `PATH`:

```ruby
ENV['PATH'] = "#{chromedriver_path}:#{ENV['PATH']}"
```

**Comment by titusfortner** [comment]
Yes, this matches where we are planning to go. We're tracking this already, elsewhere. Here is an explanation of where we are, and the steps for where we want to go:
https://github.com/SeleniumHQ/selenium/issues/11356#issuecomment-1518290859

There are a few complications we need to handle that make this non-trivial:
* We want Selenium Manager to be entirely "opt-in" right now, which means if you are doing anything to manage drivers yourself, SM won't try to do it for you
* If we do decide to do automatic fixes for users, we'll need to provide a way for them to completely opt-out from using SM (no downloading ever)
* Also, users can intentionally use an old version of the driver by passing in a specific argument to the driver, so we'll need to parse that and pass it in as a flag to SM somehow as to whether to fix or use the outdated driver
