### ISSUE TITLE
[🚀 Feature]: Implement DELETE request that deletes all present files in a session in /session/{sessionId}/se/files in grid

### ISSUE THREAD

**Issue by ksingha161** [SeleniumHQ/selenium#11986]
### Feature and motivation

I understand that files get automatically deleted after a session but let's say I have a test case (which I really do) that does 10 file downloads and those files don't have unique names. Now with the existing implementation when a POST request is made to "/session/{sessionId}/se/files" it will fetch all the files again and there will be a discrepancy between what file I need and what file is being given to me by the endpoint. To avoid this, if a DELETE request is supported, after fetching each file we could delete it and not worry about what file is being provided to us because other files just got deleted. 

Code example below - 

### Usage example

```java
protected String getDownloadedFileByGrid( String expectedFile ) throws Exception {

		 String home = System.getProperty("user.home");
		 SessionId sessionId = ( ( RemoteWebDriver ) driver ).getSessionId();
		 File dirToCopy = new File(home + File.separator + "Downloads" + File.separator +  "gridnodes" + File.separator + sessionId);
		 String uri = String.format("/session/%s/se/files", sessionId );

		 String fileToDownload = null;

		 try ( HttpClient client = HttpClient.Factory.createDefault().createClient(new URL( "http://localhost:4444/" ) )) {
			
			 HttpRequest request = new HttpRequest( org.openqa.selenium.remote.http.HttpMethod.GET, uri);
			 HttpResponse response = client.execute(request);
			 String text = string(response);
			 Type responseType = new TypeToken<Map<String, Map<String, List<String>>>>() {
			 }.getType();
			 Map<String, Map<String, List<String>>> map = new Json().toType(text, responseType);
			 Map<String, List<String>> parsedResponse = map.get("value");
			 for (String eachFile : parsedResponse.get("names")) {
				 if( eachFile.contains( expectedFile ) ) {
					 fileToDownload = eachFile;
					 break;
				 }
			 }
		 }

		 try (HttpClient client = HttpClient.Factory.createDefault().createClient(new URL( "http://localhost:4444/" ) )) {

			 HttpRequest request = new HttpRequest( org.openqa.selenium.remote.http.HttpMethod.POST, uri);
			 request.setContent( Contents.asJson(singletonMap("name", fileToDownload)));
			 HttpResponse response = client.execute(request);
			 String text = string(response);
			 Type responseType = new TypeToken<Map<String, Map<String, String>>>() {
			 }.getType();

			 Map<String, Map<String, String>> map = new Json().toType(text, responseType);
			 Map<String, String> parsedResponse = map.get("value");
			 String encodedContents = parsedResponse.get("contents");
			 Zip.unzip(encodedContents, dirToCopy );
			 System.out.println("The file which was "
					 + "downloaded in the node is now available in the directory: "
					 + dirToCopy.getAbsolutePath());
		 }

		 return dirToCopy + File.separator + fileToDownload;
```

This is where the problem is -
```
for (String eachFile : parsedResponse.get("names")) {
				 if( eachFile.contains( expectedFile ) ) {
					 fileToDownload = eachFile;
					 break;
				 }
			 }
```

Let's say I download 10 files and they don't have unique names and I say give me file that contains ".xls" or ".pdf". First file we get is good but when It downloads the second file, the list of files from node is fetched again. It will check ok this first file contains ".xls" or ".pdf and it will return back the same file.

**Comment by ksingha161** [comment]
So far I've managed to get around by declaring a variable and checking if my last file downloaded is not same as the previous one.  But it is just a workaround.

**Comment by rustunooldu** [comment]
This would be quite useful actually. We have a scenario that would benefit from a long running session, but since the download folder keeps growing, I have to periodically close and re-initiate it.

**Comment by ksingha161** [comment]
Hi @diemol @krmahadevan a little query related to grid downloads. When we download a file in chrome it's fileName during download is shown as **.crdownload** and sometimes **.tmp**  Is there a way to check for these names before we start processing the files?

**Comment by krmahadevan** [comment]
@ksingha161 - The file name is not controlled by the downloads feature in the grid. The Grid only controls the directory into which the file gets saved into. I think the `.tmp` file usually indicates that the file is perhaps still being downloaded? Maybe you can poll a few times till u see the file name change maybe ?

**Comment by ksingha161** [comment]
@krmahadevan I was trying something like this 
`if( names.stream().anyMatch( name -> name.contains( "crdownload" ) )  ||
							 names.stream().anyMatch( name -> name.contains( ".tmp" ) )) {
						 //something
						 TimeUnit.SECONDS.sleep( 10 );
					 }`

But it looks like the sessionId grabs the file in whatever condition it finds it. Basically the `names` list already contains the half downloaded file so I cannot wait for a file to not have the name .temp or .crdownload because the names list has already picked it up.

**Comment by ksingha161** [comment]
@krmahadevan is it possible to add a check in the code that before the file is added to the `names` list in the session, we can make sure it does not contain the name ".crdownload" or ".tmp".

**Comment by krmahadevan** [comment]
@ksingha161 - Its not good to add such edit checks because we don't know what will be an intermediate file and what is a completely downloaded file.

I have seen that browsers basically create temp files into which they save contents and finally they themselves will delete/rename the temp file.

**Comment by ksingha161** [comment]
@krmahadevan understood. But what about chrome only? Whenever a file is downloaded on chrome it's name's always contains ".crdownload".

**Comment by krmahadevan** [comment]
This should explain https://docs.fileformat.com/web/crdownload/

**Comment by titusfortner** [comment]
That just means the file hasn't downloaded yet

**Comment by ksingha161** [comment]
@titusfortner yes exactly. Why I posed this question is because the file in it's download in progess status is pushed inside the names list in grid session which Increases test failures if we want to read the contents of the file, since it has not downloaded yet.

**Comment by titusfortner** [comment]
Get the list of names in the directory and poll to see when the filename you want no longer has that extension.

**Comment by krmahadevan** [comment]
@ksingha161 

> Why I posed this question is because the file in it's download in progess status is pushed inside the names list in grid session 

This is incorrect. The manage downloads feature only does the following:

1. If auto manage downloads is enabled on the node and if it is requested explicitly via the desired capabilities then a new session is spun off with the browser's desired capabilities (only for chrome, edge or firefox) enriched with the folder into which the browser should download files into.
2. The folder into which the files are to be downloaded to, is computed before the new session request is honoured
3. If the user requests to list the files that were downloaded so far in the current session, then the node retrieves those file names in runtime and then returns them to the user.
4. If the user requests to obtain a specific file that was downloaded by the user's currrent webdriver session (by specifying the file name) then that file alone is retrieved to the user.

The grid feature does not remember names before hand nor do any manipulation in terms of the file names.

**Comment by ksingha161** [comment]
@krmahadevan what I meant by names list is this list that contains files. In this screenshot as you can see the last file is download in progress but is pushed inside the list. 
`{
"value": {
"names": [
"one.pdf",
"two.pdf",
"three.pdf.crdownload"
]
}
}` 
![image](https://github.com/SeleniumHQ/selenium/assets/56039095/25ba5300-5201-466a-b0d7-780f31155372)

**Comment by krmahadevan** [comment]
That perhaps is because the chrome browser didn't delete the temporary file as it should have been maybe ? Either case, I think it should be easier for you to filter out temp files at your end and use the actual ones.

**Comment by ksingha161** [comment]
It is not a temp file, this file is currently downloading. The .crdownload extension gets removed once the download completes. For now I guess I'd poll the directory to check if none of the files have this extension (which basically all downloads are completed).

**Comment by krmahadevan** [comment]
> The .crdownload extension gets removed once the download completes.

That was what I meant when I said a temp file

**Comment by aldobrynin** [comment]
I'd vote for such feature for grid. Should we reach an agreement upon this I'm up to make it to PR

In my case this is required for making sessions reusable. 

We have 1000+ tests and in order to setup a new node\session for each test (let's assume it takes 5 seconds) it'd be extra 5s*1000 = ~1.5 hours. But if we use sessions pool, we can avoid that (yes, it'd require us to reset browser state manually)

**Comment by titusfortner** [comment]
You have multiple tests in your suite that download the same file name?
The timing works out to much less than that if you run tests in parallel. But still, I don't see a good reason not to have this. If you want to make a PR, we can evaluate it. Thanks.
