### ISSUE TITLE
[🐛 Bug]: The latest version of Selenium does not support the latest version of urllib3

### ISSUE THREAD

**Issue by mdmintz** [SeleniumHQ/selenium#11988]
### What happened?

Can't install the latest version of ``urllib3`` (``2.0.1``) because ``selenium 4.9.0 depends on urllib3[socks]~=1.26``.

The latest version of ``urllib3`` is ``2.0.1``.

Now that ``requests`` ``2.30.0`` has been released, which supports the latest ``urllib3``, it's now ``selenium`` that's holding things back. ``urllib3[socks]~=1.26`` should be changed to ``urllib3[socks]>=1.26`` (or similar) to allow the latest version of ``requests``.

### How can we reproduce the issue?

```shell
``pip install selenium`` and then ``pip install urllib3==2.0.1``
```

### Relevant log output

```shell
The conflict is caused by:
    <PACKAGE> depends on urllib3[socks]==2.0.1
    selenium 4.9.0 depends on urllib3[socks]~=1.26
```
```


### Operating System

All of them

### Selenium version

Python 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Irrelevant 

### What are the browser driver(s) and version(s) where you see this issue?

Irrelevant 

### Are you using Selenium Grid?

Irrelevant

**Comment by diemol** [comment]
Would you like to send a pull request?

**Comment by mhillebrand** [comment]
urllib3 is up to 2.0.2 now:

https://github.com/urllib3/urllib3/releases/tag/2.0.2

**Comment by mdmintz** [comment]
OK, now it's safe for the PR (I'll create one shortly). The bug that was fixed in ``urllib3`` ``2.0.2`` would've caused major problems for ``selenium``.

**Comment by mdmintz** [comment]
I created a PR: https://github.com/SeleniumHQ/selenium/pull/11993

But given that ``urllib3`` 2 has had some serious issues already (they yanked releases for that), it might be a good idea to wait a bit to make sure it's stable. Eg. When Monday comes and it's still non-yanked, then maybe it's safe this time.

<img width="1185" alt="Screenshot 2023-05-04 at 2 17 53 PM" src="https://user-images.githubusercontent.com/6788579/236293709-703f04e4-91af-412e-b232-9d76abb53b8c.png">

**Comment by AutomatedTester** [comment]
Can you please also add the pip issue number as discussed on slack

**Comment by mdmintz** [comment]
@AutomatedTester `pip` isn't going to allow multiple versions of the same module at the same time. There's already a closed ticket about it: https://github.com/pypa/pip/issues/10352

**Comment by fortzi** [comment]
Great news on this being fixed, thanks @mdmintz! Do you have an idea when this is expected to be released?

**Comment by mdmintz** [comment]
@fortzi It was released in ``selenium`` ``4.9.1`` / ``seleniumbase`` ``4.14.8``

**Comment by mhillebrand** [comment]
@mdmintz I see the tag for it—now that you've mentioned it, but there's no release for 4.9.1.

**Comment by mdmintz** [comment]
@mhillebrand https://github.com/SeleniumHQ/selenium/releases only shows the major ``selenium`` versions. But see https://pypi.org/project/selenium/#history for all available tags.
