### ISSUE TITLE
I get window.editor.app is undefined with Selenium IDR on Firefox 43 

### ISSUE THREAD

**Issue by jamesgodwin333** [SeleniumHQ/selenium#1198]
![selenium ide error](https://cloud.githubusercontent.com/assets/12170809/10769703/c420cc5a-7cbd-11e5-8c26-7dd42f23a90d.jpg)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
