### ISSUE TITLE
ByChained is not available anymore, what is the replacement?

### ISSUE THREAD

**Issue by Mek7** [SeleniumHQ/selenium#11995]
### What happened?

I tried to upgrade nuget package of Selenium.WebDriver and SeleniumSupport from 3.141.0 to 4.9.0.
In code, ByChained is used heavily and I am now getting error stating that ByChained cannot be found

> The type or namespace name 'ByChained' could not be found (are you missing a using directive or an assembly reference?)

I was unable to find a reason on the internet, in github issues of selenium, or in selenium changelog.
Was ByChained class deprecated and removed? And what is the replacement?

### How can we reproduce the issue?

```shell
use ByChained in C# code in a project that has nuget packages Selenium.WebDriver and SeleniumSupport installed.
```

### Relevant log output

```shell
The type or namespace name 'ByChained' could not be found (are you missing a using directive or an assembly reference?)
```

### Operating System

Windows 10

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

browser-independent

### What are the browser driver(s) and version(s) where you see this issue?

browser-independent

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
http://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html

**Comment by Mek7** [comment]
Thanks, but that page discusses PageFactory and ExpectedConditions.
What about ByChained? We are interested to keep our test code base in line with the latest Selenium.

**Comment by titusfortner** [comment]
ByChained was part of page factory.

**Comment by titusfortner** [comment]
I never used that method, but it looks like you have to nest the find element call instead of just passing in multiple locator parameters to a method.

**Comment by Mek7** [comment]
I now solved it.
Whoever stumbles upon this in the future - just download source code of Selenium 3.141.0, extract ByChained.cs from it and use it in your test project.
I still think there was no reason at all to remove ByChained from Selenium. It is a useful class just as By is, and looks like it was removed with the entire PageObjects namespace that it happened to be in.

**Comment by titusfortner** [comment]
Ah, I forgot, the code can be found here as well — https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras

Copying the code you want into your project is a great solution.

It was removed from Selenium not because it wasn't useful, but because it is one of an unlimited number of wrapper classes that Selenium could write and maintain, and we'd rather be focused on the underlying functionality than on various wrapper options. This code rightly belongs available online for people to copy and paste and use, it just does not belong in core Selenium.
