### ISSUE TITLE
[🐛 Bug]: getAttribute returns null

### ISSUE THREAD

**Issue by RobertoPegoraro** [SeleniumHQ/selenium#11996]
### What happened?

I'm trying to retrieve the viewBox attribute from my element

```
<svg aria-label="CheckIcon" class="Icon_primary-base__FQZxF" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"></svg>
```
but when I use
```
myElement.getAttribute("viewBox")
```
Selenium returns `null`

For the other attributes like `role`, `class`, `aria-label` it works good only for viewBox it returns null

Using javascript in the console I can capture the `viewBox` attribute:

![image](https://user-images.githubusercontent.com/10342271/236455167-db7a849c-73a4-48ab-bcdc-17a14404d5f3.png)

### How can we reproduce the issue?

```shell
Create an HTML page with svg attribute or go to https://www.freecodecamp.org/news/use-svg-images-in-css-html/ there is some <svg> tags, then try to capture the viewBox attribute
```

### Relevant log output

```shell
N/A
```

### Operating System

MAC

### Selenium version

Java 4.8.0

### What are the browser(s) and version(s) where you see this issue?

chromedriver 113.0.5672.63 (resolved driver for Chrome 113)

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 113.0.5672.63 (resolved driver for Chrome 113)

### Are you using Selenium Grid?

N/A

**Comment by titusfortner** [comment]
What do you get when you use. `getDomAttrribute()`?

**Comment by RobertoPegoraro** [comment]
Ok, using `getDomAttrribute` it works. But, what is the difference of these methods? Why is there two methods?

Thank you @titusfortner !

**Comment by titusfortner** [comment]
getAttribute is the original selenium implementation that essentially tries to guess what the user probably wants between a property and an attribute.

When creating a w3c spec we couldn't use "what the user probably wants" so there's an endpoint for property and attribute, and the method names are getDomProperty and getDomAttrribute. We kept the original behavior with the original method for backwards compatibility, and it's now implemented with an execute script of a large chunk of JS under the hood.
