### ISSUE TITLE
[🚀 Feature]: Auto scaling node without Kubernetes

### ISSUE THREAD

**Issue by devqaio** [SeleniumHQ/selenium#11999]
### Feature and motivation

We have a requirement where we need to auto scale the node services (from docker-compose file) based on new queue size. However, we can't use Kubernetes for this infrastructure.

I tried to explore but couldn't find any solution around this. Is there any such capability already exists in selenium 4 or is in pipeline for future release?

I am trying to create an autoscaler service around this which need to be deployed in hub, but trying to understand, if there is anything available out-of-the box.  

### Usage example

Let's say we have one service deployed for node-edge with max session count of 5. When the hub receives 6th request, it will auto scale node-edge to 2 which will serve the 6th node till 10th. Same way it will increment the service count.

If service 2 is not attending any request, then it will be turned off making available service node as 1 again.

**Comment by diemol** [comment]
The closest to what you are asking for, out of the box, is https://github.com/SeleniumHQ/docker-selenium#dynamic-grid.
