### ISSUE TITLE
[🐛 Bug]: C# API Docs link does not redirect to the API Docs homepage

### ISSUE THREAD

**Issue by elgatov** [SeleniumHQ/selenium#12009]
### What happened?

When accessing the C# API Docs from https://www.selenium.dev/downloads/, which currently has the url https://goo.gl/uutZjZ, the landing page does not correspond to the API Docs homepage, it must be navigated to via the `Api Documentation` link  in the list at the left side, which corresponds to https://www.selenium.dev/selenium/docs/api/dotnet/api/index.html 

### How can we reproduce the issue?

```shell
Access the API Docs url either from https://goo.gl/uutZjZ or https://www.selenium.dev/selenium/docs/api/dotnet/index.html
```

### Relevant log output

```shell
-
```

### Operating System

-

### Selenium version

-

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by MohammedKamle** [comment]
I am interested in fixing this

**Comment by diemol** [comment]
Fixed through https://github.com/SeleniumHQ/selenium/commit/cbaff758e267556c70d10b04c728aaa88ce84308 and https://github.com/SeleniumHQ/selenium/commit/85a0c67c64fa482a374a23c8bb54db0e22a0aa7d
