### ISSUE TITLE
[🐛 Bug]: [rb]: Debug logger initialize gives "wrong number of arguments"

### ISSUE THREAD

**Issue by jorg-vr** [SeleniumHQ/selenium#12005]
### What happened?

All our tests fail for the new selenium version 4.9.1 (See https://github.com/dodona-edu/dodona/pull/4619)

I traced to root cause to changes made in https://github.com/SeleniumHQ/selenium/commit/1cd84f7b6bf6b45b05371710d2d6eb7cc5631f35

Changing this line https://github.com/SeleniumHQ/selenium/blob/c6f7396f62d02932be0fc3b54846dca12bfa43a6/rb/lib/selenium/webdriver.rb#LL99C42-L99C42 from:
```ruby
@logger ||= WebDriver::Logger.new('Selenium', default_level: level, **opts)
```
to
```ruby
@logger ||= WebDriver::Logger.new(progname: 'Selenium', default_level: level, **opts)
```

Fixes the issue

### How can we reproduce the issue?

```shell
Running any of our tests here https://github.com/dodona-edu/dodona/pull/4619 should reproduce.

I am sorry for not making a smaller example, but I think it would fail in almost any example...
```

### Relevant log output

```shell
/home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/logger.rb:51:in `initialize': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/selenium/logger_suppressor.rb:8:in `initialize'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `new'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:99:in `logger'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:81:in `build_process'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:103:in `start_process'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:57:in `block in start'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
	  from <internal:kernel>:90:in `tap'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/service.rb:91:in `launch'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:334:in `service_url'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.9.1/lib/selenium/webdriver.rb:88:in `for'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/selenium/driver.rb:83:in `browser'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/selenium/driver.rb:104:in `visit'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/session.rb:280:in `visit'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/dsl.rb:52:in `call'
	  from /home/jorg/.rvm/gems/ruby-3.1.2/gems/capybara-3.39.0/lib/capybara/dsl.rb:52:in `visit'
```

### Operating System

Linux mint

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Not using a browser

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 111.0.5563.64

**Comment by kennyadsl** [comment]
Same issue [here](https://app.circleci.com/pipelines/github/solidusio/solidus_paypal_commerce_platform/746/workflows/7747d1d7-3afc-4e6c-9619-713080cea986/jobs/2128), didn't try if the suggested patch works, though.

**Comment by titusfortner** [comment]
This is an issue with how Capybara is wrapping the Selenium Logger. I've submitted a PR for them, and they'll either accept it or get it sorted in another fashion.
https://github.com/teamcapybara/capybara/pull/2665

**Comment by kennyadsl** [comment]
Hello, and thanks again for your work on this issue! 

I just wanted to point out that this issue is still there, at least until a new version of Capybara is released and looking at https://github.com/teamcapybara/capybara/issues/2666, releasing doesn't seem to be a priority at the moment. Maybe it's worth coordinating with the Capybara maintainers to understand how to move this forward. I'm available to help with that if needed, thanks!

**Comment by titusfortner** [comment]
Some people I can't get to be bothered to update off of 5 year old versions. Some people can't stand not to always have the absolute latest versions. 😂 

Capybara is a large open source project with a single unpaid maintainer. He'll get to a release when it is convenient for him to do so. The stakes are pretty low on this one. Just limit the version in your gemspec for now.

**Comment by kennyadsl** [comment]
I understand your point but sometimes it's not a choice. In our case, we are working on an open-source platform with many plugins (each of them is a gem with a standalone test suite) which are using the last version of `selenium-webdriver` without locking its patch-level version. Updating all of them (twice, because we need to unlock the dependency once it is fixed) is not ideal. 

That said, it's not the end of the world and we can definitely wait. I was just offering my help to speed up things if it was useful/needed.

Thanks again for your work here. 👍

**Comment by titusfortner** [comment]
Managing a group of gems is a lot of hassle regardless. Not much to do here in the short term. Long term big picture, finding popular but under resourced open source projects and contributing to them enough to be entrusted with the ability to release them would make a huge difference to the ecosystem.

**Comment by titusfortner** [comment]
Actually another thing here. What all is needed for a release? Is the CI passing? Any other bug fixes needed? Is it just a version bump? changelog? If you make a PR that does the drudge work and make it so that all @twalpole needs to do is merge it and run the release command that might be helpful by itself.

**Comment by kennyadsl** [comment]
I can definitely prepare the version bump, but since there are other things on the master branch since the last release (including [dropping support for Ruby 2.7](https://github.com/teamcapybara/capybara/commit/c112c6463c32a58ba7e3e2b4ef0dd7384644bf97)), I'm not sure what the next version is supposed to be.

**Comment by waiting-for-dev** [comment]
Please, let us know if we should move the conversation to the Capybara issue. For now, I'll keep it here as @twalpole has been tagged, and they can tell us the best thing to do.

We were thinking of backporting the bug fix to the latest stable branch and submitting a PR there. However, we realized there's no `3.39_stable` branch; instead, the "last" one is `3.38_stable`. As we can't create the branch in the repository, we'll happily create the PR if the branch is created. Probably, that would be the best thing to do. A minor release probably needs more considerations, but being a bug fix, a patch release should be enough.

Please, let us know if we can help in any other way, and thanks for your support on this.

**Comment by titusfortner** [comment]
Fork the repo, create your own branch and merge whatever and make a PR with it. Worst case he decides to go a different way (essentially what happened with the PR I made). :)

Just getting in the habit of proposing actual code instead of just raising issues makes a huge difference over time. 
Open source code is "ours," not "theirs."

**Comment by twalpole** [comment]
Releasing takes work, and that takes time. Sometimes we value our family time over unpaid work and I would hope people in a well compensated industry would respect that. @titusfortner went out of his way to submit a PR, for which I went with a different solution and will do a new release when I have a few hours to spend on it. If you really need the latest today feel free to use the master branch of Capybara

**Comment by waiting-for-dev** [comment]
We have the PR ready to be submitted. But we need the corresponding `3.39_stable` branch in the `teamcapybara/capybara` repository to target that one as the base branch. In the meantime, you can see the corresponding code: https://github.com/teamcapybara/capybara/compare/96a8baab1df6159a4c0790b1b21e875ee946fa7d...waiting-for-dev:capybara:v3.39_stable

**Comment by codebender** [comment]
Should v4.9.1 get pulled from rubygems? https://rubygems.org/gems/selenium-webdriver/versions/4.9.1

**Comment by titusfortner** [comment]
Why? To the extent that there is a bug, it is in Capybara, not Selenium. Capybara is wrapping the class with the wrong signature. Adding an optional keyword parameter to a method should not be considered a breaking change.

One thing we might want to coordinate, @twalpole is that Selenium releases a [nightly gem](https://github.com/SeleniumHQ/selenium/pkgs/rubygems/selenium-webdriver). If Capybara ran tests against that, we can double check things are working before we do a Selenium release in the future. And if anyone on this thread wants to help out with that, I'm sure it would be appreciated by everyone...

**Comment by codebender** [comment]
okay understood, it felt like a breaking change because only upgrading the `selenium-webdriver` caused the bug to surface
