### ISSUE TITLE
How to send saved file (not downloaded) from node to hub via auto downloads in grid?

### ISSUE THREAD

**Issue by ksingha161** [SeleniumHQ/selenium#12003]
### Feature and motivation

There are multiple cases when we copy something from the UI and save it into a file and then process it, whether it is HTML or plain text. In grid auto downloads, how can we achieve creating file in node and then sending it to hub? In my case I save some html code which I need to read but it looks like auto downloads is only for downloads. Looking for some help.

### Usage example

I save some html code
`String fileName = "something.html";
		String home = System.getProperty("user.home");
		FileUtils.createFile( someHtml, new File( home + File.separator + "Downloads" + File.separator + fileName ) );`

But session/{sessionId}/se/files return an empty list since this is not a download.

`200: {
  "value": {
    "names": [
    ]
  }
}`

**Comment by krmahadevan** [comment]
@ksingha161 - auto downloads feature in Grid will ONLY let you access those files that were downloaded via the browser. I dont think it is meant to be used as a file browser mechanism on the node.

**Comment by krmahadevan** [comment]
So 

> But session/{sessionId}/se/files return an empty list since this is not a download.

This is working as designed

**Comment by ksingha161** [comment]
Thanks @krmahadevan that's what I thought. Do you know of any other way to achieve this? Or is there any way to achieve this with grid?

**Comment by krmahadevan** [comment]
@ksingha161 - Can you please explain/elaborate what you are trying to do?

**Comment by ksingha161** [comment]
Sure @krmahadevan , I am copying HTML script from the UI. I need to save it into a .html file and open that html script in the browser. It will get saved in the node but problem arises when I need to read it. This is why I need to send it to the hub.

**Comment by krmahadevan** [comment]
> I am copying HTML script from the UI. I need to save it into a .html file 

Please list out the steps that you need to do, to get this done. 

Alternatively you can look at [this blog post](https://sahajamit.medium.com/getting-clipboard-content-from-remote-selenium-chrome-nodes-67a4c4d862bd) for more contextual details.

**Comment by ksingha161** [comment]
@krmahadevan I think what can be implemented is maybe an endpoint through which we can transfer any file from the node to the hub. And not just files present in `{ "value": { "names": [ ] } }`. In this case if I save the html code in "somefile.html" then I can make a post request to the hub with this file.

**Comment by krmahadevan** [comment]
@ksingha161 The auto downloads feature is a very focussed feature of the grid viz., be able to get access to browser downloaded files on a remote node and process the accessed file within the test.

I  dont think the downloads feature was aiming at doing anything beyond that.

Usually files that are created in a node usually arise out of a download from a browser (which this feature addresses). In your case, you web app is doing something else (which you still haven't elaborated by the way in terms of a detailed set of steps so that the use case can be better understood and then reasoned with)

All said and done I would let @diemol / @titusfortner  chime in and provide you with more concrete rationale.

**Comment by ksingha161** [comment]
Pardon me if it was not elaborated but the only explanation I have is that - 
1. I create a file on node (by copying contents from the clipboard).
2. I need to read that file which is not possible if the file is not on the hub
3. To read the file, there should be a way to transfer the file from node to the hub.

**Comment by krmahadevan** [comment]
> I create a file on node (by copying contents from the clipboard).

This is the part that I am curious as well. How are you copying contents of the clipboard ? Please feel free to elaborate this with code snippets or anything else that can help.

**Comment by ksingha161** [comment]
@krmahadevan this is being done via java toolkit 
`String clipboardText = (String) Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);`

**Comment by krmahadevan** [comment]
To the best of my knowledge, 

> Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);

Will work ONLY on the current JVM (where in your test case runs) and NOT on the JVM wherein the node runs. 
Have you gotten this to work on a Grid setup wherein :

* Test runs on MachineA
* Hub runs on MachineB
* Node runs on MachineC

**Comment by ksingha161** [comment]
Right, no actually. When I was using selenium 3, I had explicitly mentioned the test to run on a specific machine with applicationName property in grid and it was all working fine.

**Comment by diemol** [comment]
If you want to copy the HTML from a page, either remote or local, you can always use `driver.getPageSource()`. There is no need to copy things to the clipboard. 

If it is actually being able to access the clipboard, it should be proposed at https://github.com/w3c/webdriver-bidi. 

If you have more questions, I will leave some links you can use below.
