### ISSUE TITLE
[🐛 Bug]: <repository> instead of <dependency> in documentation on [Install a Selenium library] page

### ISSUE THREAD

**Issue by Mirt12** [SeleniumHQ/selenium#12004]
### What happened?

repository instead of dependency in documentation on page [Install a Selenium library]

AC: The text should be 

```xml
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.9.0</version>
</dependency>
```

### How can we reproduce the issue?

Steps:
1. Open page:
https://www.selenium.dev/documentation/webdriver/getting_started/install_library/
2.  Click [Java] tab under "Requirements by language" header.
3. Verify the text is:

```xml
 <repository>
      <id>sonatype-nexus-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
```
instead of 

```xml
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.9.0</version>
</dependency>
```

### Relevant log output

```shell
GET Request URL: https://www.selenium.dev/documentation/webdriver/getting_started/install_library/
```

### Operating System

Windows 10

### Selenium version

Java 17.0.6

### What are the browser(s) and version(s) where you see this issue?

Chrome, FFox, EDGE, IE etc.

### What are the browser driver(s) and version(s) where you see this issue?

Chrome version 112.0.5615.139

**Comment by diemol** [comment]
Thank you for pointing it out, I added that section to test SNAPSHOT releases. I have updated the link so it shows the correct information. The change will go live in a few minutes.

**Comment by Mirt12** [comment]
you are welcome)
