### ISSUE TITLE
[🚀 Feature]: add select_all 

### ISSUE THREAD

**Issue by awangc** [SeleniumHQ/selenium#12010]
### Feature and motivation

In the [select module](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/support/select.py) we find `deselect_all` which simplifies deselecting all options. This proposal is to add `select_all` to simplify selecting all options. 

### Usage example

So we can write

```
Select(driver.find_element_by_id('select_id')).select_all() # assuming tag supports "multiple"
```

instead of getting the options, looping through each, and trying to call one of the `select_by...` calls (like this [example](https://www.lambdatest.com/blog/handling-dropdown-in-selenium-webdriver-python/))

**Comment by titusfortner** [comment]
Closing as we're not currently adding features to the support section. This can be implemented in client code
