### ISSUE TITLE
[🚀 Feature]: [JS] Enable listening to CDP events

### ISSUE THREAD

**Issue by systemboogie** [SeleniumHQ/selenium#12017]
### Feature and motivation

I would like to be able to listen to CDP events, mainly to subscribe to [`Page.screencastFrame`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-screencastFrame). This has been requested in #7339 already, but the request was closed as completed. However, as far as I can see, there was/is no way to add listeners in the JavaScript bindings. If I'm missing something, please let me know!

Otherwise I'd propose in [javascript/node/selenium-webdriver/devtools/CDPConnection.js](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/node/selenium-webdriver/devtools/CDPConnection.js), to add this:

```js
addListener(event, callback) {
  this._wsConnection.on('message', (data) => {
    const payload = JSON.parse(data);
    if (payload.method === event) {
      callback(payload)
    }
  })
}
```

I'd happily provide a PR if it makes sense to you.

### Usage example

The gist of it (omitting package import and driver creation/teardown):

```js

    // Import packages and create driver

    const cdpConnection = await driver.createCDPConnection('page');

    cdpConnection.addListener('Page.screencastFrame', async (payload) => {
      const {
        params: {
          metadata: { timestamp },
          data,
          sessionId,
        },
      } = payload;

      fs.writeFileSync(`${timestamp * 1000000}.jpeg`, data, 'base64');
      await cdpConnection.send('Page.screencastFrameAck', {
        sessionId,
      });
    });

    await cdpConnection.send('Page.startScreencast', {
      format: 'jpeg',
      quality: 50,
      maxWidth: 1920,
      maxHeight: 1080,
      everyNthFrame: 1,
    });

    // Do stuff

    await cdpConnection.send('Page.stopScreencast');
```

**Comment by diemol** [comment]
We do not plan to add more features to the CDP integration because the focus is to leverage the upcoming https://github.com/w3c/webdriver-bidi. If you are missing a feature, you should propose it as an issue over there. 

For this specific use case and scope, you would need to handle the listener. I believe @nir-tal-talkspace has already achieved that.

**Comment by systemboogie** [comment]
Thanks for your swift reply @diemol, I really appreciate it. ❤️

To be fair, adding a listener for CDP events is possible in the other bindings, at least as far as I understand. So this is not about adding a new feature, but enabling the JavaScript bindings (and thus frameworks building on top) to do something that the other bindings already can do.

**Comment by titusfortner** [comment]
Yes, and we'll be removing that code from the other languages once we get it implemented with the bidi-protocol. We don't want to add things we're going to turn around and delete. I would double check that what you need specifically is included there - https://w3c.github.io/webdriver-bidi/#module-contexts-events
