### ISSUE TITLE
[🚀 Feature]: Default All Driver Log Output to dev/null

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12016]
### Feature and motivation

This has always been the default behavior for Ruby.

I think a lot of people are annoyed with how much extra stuff gets sent to the console (especially Firefox — https://github.com/mozilla/geckodriver/issues/619).

Once we document how to turn on logging for the drivers (I'm working on it), I think we should swallow the driver output by default and (maybe) direct people to the docs for how to turn it on/save it.

### Usage example

n/a

**Comment by titusfortner** [comment]
.NET - defaults to no output
Ruby - defaults to no output
Python - defaults to no output, except for Firefox, which defaults to `geckodriver.log`
Java - defaults to stderr
JS  - defaults to no output

**Comment by diemol** [comment]
During the meeting on [25.05.2023](https://www.selenium.dev/meetings/2023/tlc-05-25/) it was decided to move browser driver output to `dev/null`.

**Comment by diemol** [comment]
Reopening because Python is still missing.

**Comment by diemol** [comment]
Implemented in Python via #12103
