### ISSUE TITLE
[🐛 Bug]: accounts.google.com page does not load in Selenium Grid

### ISSUE THREAD

**Issue by VladYuditsky** [SeleniumHQ/selenium#12019]
### What happened?

As of yesterday, all my automated tests were failing once they try to driver.navigate().to("https://accounts.google.com") or "https://mail.google.com/mail/u/0/h/#"
I tried with chrome, firefox (I tried with versions 99, 100, 112, and latest) https://hub.docker.com/r/selenium/node-chrome/tags

The error I get back is "org.openqa.selenium.WebDriverException: 
unknown error: net::ERR_CONNECTION_TIMED_OUT"

I already rebooted my grid, hub, nodes multiple times. I also want to mention that there is no issue when running it locally using WebDriver instead of RemoteDriver

<img width="946" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/28636677/4eb7873b-169d-4010-b0f7-b795492c0615">
<img width="931" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/28636677/20798d41-750f-4747-a40c-96099dd4fbc4">

### How can we reproduce the issue?

```shell
I cannot share all the code but it fails on this part under grid using RemoteDriver. "https://mail.google.com/mail/u/0/h/#" is the url to use gmail basic. However accounts.google.com also fails. I wonder how many other gmail suite tools fail.

driver.navigate().to("https://mail.google.com/mail/u/0/h/#");
// page never loads for google suite
waitForPageLoad(); 


    private void waitForPageLoad()
    {
        ExpectedCondition<Boolean> pageLoadCondition = new ExpectedCondition<Boolean>()
        {
            public Boolean apply(WebDriver driver)
            {
                return ((JavascriptExecutor) driver).executeScript("return document.readyState").equals("complete");
            }
        };

        wait = new WebDriverWait(driver, 30);
        wait.until(pageLoadCondition);
    }
```

### Relevant log output

```shell
The error I get back is "org.openqa.selenium.WebDriverException: 
unknown error: net::ERR_CONNECTION_TIMED_OUT"
```

### Operating System

Linux

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome latest 

### What are the browser driver(s) and version(s) where you see this issue?

latest

### Are you using Selenium Grid?

4.9.1

**Comment by titusfortner** [comment]
We can't help with older versions of Selenium, especially Selenium 3; please update to latest version (4.9.1 right now).

Google can tell when Selenium is accessing the site and may limit logins, so it might be that.

Also, you don't actually need `waitForPageLoad()` in general. If your `pageLoadStrategy` is set to `normal` (which is the default), then the driver will automatically wait for the ready state to be complete before responding.

In any event, there is nothing for Selenium to do here. I'll put some links below for places you can follow up.

**Comment by VladYuditsky** [comment]
Thank you for the fast reply. I will try to upgrade selenium to 4.9.1
