### ISSUE TITLE
[🐛 Bug]: Safari not loading page when used in Github Actions with a nuxt.js website

### ISSUE THREAD

**Issue by MatteoH2O1999** [SeleniumHQ/selenium#12027]
### What happened?

I was setting up a screenshot testing suite for my website using Github actions.
As a first test I tried to take a screenshot of the main page on macos-latest and ubuntu-latest using chrome (which worked) and, with macos, also with safari (which gave back a screenshot with the page text not loaded, only the background color and page height was correct).
In order to reproduce, a workflow on macos-latest must be run where a nuxt website static pages are already generated in the ./dist folder with a package.json containing a "start" script that will call "nuxt start". The script below must be run to start static server, generate screenshots and shutting down server.
Then upload the screenshot as an artifact and it should be blank with only background color and height.
As an example of a run [see here](https://github.com/MatteoH2O1999/MatteoH2O1999.github.io/actions/runs/4949508401).

### How can we reproduce the issue?

```shell
import * as exec from '@actions/exec';
import fs from 'fs';
import os from 'os';
import http from 'http';
import path from 'path';
import childProcess from 'child_process';
import treeKill from 'tree-kill';
import { Builder, until, By, Browser } from 'selenium-webdriver';

const baseUrl = 'http://localhost:3000';

async function websiteUp() {
    return await new Promise((resolve, reject) => {
        http.get(baseUrl, (res) => {resolve(res.statusCode === 200)}).on('error', (e) => {resolve(false)})
    });
}

const baseDirectory = 'path/to/nuxt/website';
const serverProcess = childProcess.exec('npm run start', {cwd: baseDirectory});
while (!(await websiteUp())) {
    await new Promise(resolve => setTimeout(resolve, 1000));
}
await exec.exec('sudo safaridriver --enable', [], {silent: true});

const driver = await new Builder().forBrowser(Browser.SAFARI).build();

await driver.get(baseUrl.concat('/en-us'));
await driver.sleep(2000);
const image = await driver.takeScreenshot();
fs.writeFileSync('./screenshot.png', image, {encoding: 'base64'});

treeKill(serverProcess.pid);
```

### Relevant log output

```shell
No log gets emitted, only a screenshot with a blank page with the correct background color and height.
```

### Operating System

macos-latest(12) Github Actions Runner

### Selenium version

4.9.1 javascript

### What are the browser(s) and version(s) where you see this issue?

Safari 16.4.1 (see runner image)

### What are the browser driver(s) and version(s) where you see this issue?

SafariDriver

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Does it work locally and not in GitHub Actions?

**Comment by MatteoH2O1999** [comment]
I just tested it on a macbook air with macos Ventura and it works fine. The only difference from the above script was that instead of calling `safaridriver --enable` from the script as in CI, I enabled it manually and run the script with that line commented out but the rest was the same and the result was what I expected: a screenshot of everything on screen. The github actions version is still broken.

Expected result from Chrome Github Actions on Ubuntu (same result is obtained from macos, I already tested it):
![expected](https://github.com/SeleniumHQ/selenium/assets/82184604/9dd45fa7-afb5-4811-94a8-a220c30fcf5a)

Actual result from Github Actions on Safari:
![actual](https://github.com/SeleniumHQ/selenium/assets/82184604/2009fc67-6266-4e5c-b3c8-f947d594b620)

**Comment by diemol** [comment]
I do not think you need to run `await exec.exec('sudo safaridriver --enable', [], {silent: true});` to enable Safari in GitHub actions. We do not need to do that to run our examples in macOS.

On the other hand, thanks to your test, it can be seen that the commands sent and received by Selenium to take the screenshot work. However, the GitHub Actions environment needs to be troubleshooted, which is out of our scope. I recommend posting the question to the GitHub Actions folks, or to other forums (which I will share below).
