### ISSUE TITLE
[🚀 Feature]: Support for servlet in hub/node

### ISSUE THREAD

**Issue by idan72** [SeleniumHQ/selenium#12044]
### Feature and motivation

I am using Selenium 3 and wants to upgrade to selenium 4.

In my testing I need to make action on the node machine that selenium can't do like dealing with file explorer (limition of our app that sendkeys to input element not working), click on different keys outside the web and more.

In selenium 3 I implement HttpServlet and than from my code I call http:<node_ip>:5555?param1=<param1>&param2=<param2>

and the code was execute in node machine as part of the test.

Looks like in Selenium 4 it is not supported even if I use the --node-implemantion option.

Thanks

### Usage example

Anothe rexample that I need is to run some windows code with parameters

**Comment by diemol** [comment]
What do you exactly need to do in the custom HTTP request? Several people have asked and at the end they could implement the feature on a side car server running on the same host.

**Comment by idan72** [comment]
It is possible to create my own server to the action needed on the node machines (and I run  my tests on 20 machines) but that require much more handling in the node setup than using the selenium node extension ability exists in Selenium 3.

In some cases I need to handle File explorer at the node, clipbard and run some batch files.

Also the web application open new browser and I run selenium code to work with that browser but I need to run the code on that machine so I can connect to the local remote debugging port

**Comment by diemol** [comment]
>It is possible to create my own server to the action needed on the node machines (and I run my tests on 20 machines) but that require much more handling in the node setup than using the selenium node extension ability exists in Selenium 3.

But you still need to deploy the Grid binary across all the hosts, what is the extra handling needed in this case?


>In some cases I need to handle File explorer at the node, clipbard and run some batch files.

When is this happening? Before, during, after a session? Can you explain more in detail?

>Also the web application open new browser and I run selenium code to work with that browser but I need to run the code on that machine so I can connect to the local remote debugging port

Selenium Grid 4 gives you access out of the box to the remote debugging port via CDP commands, and in the future via WebDriver BiDi commands.

**Comment by idan72** [comment]
1. Today I  start the selenium node running batch file with the extra Jar that contain my custom code and I dont need to handle the "Server" part
2. During the test of the web site I need to add attachment and I need to work with the file explorer (due to some limition in some cases I cant just sendKeys to input element) , I am also need to make copy of text from the web to clipboard and paste it to notepad
3. From the web appliction (that I open using selenium remote webdriver) I can open .Net appliction (Tauri - WebView) that open another browser so I have selenium code that connect to both usin localhost:9222 and localhost:9223.   but this code need to r be run locally on the node.   In selenium 4 I can connect to these browsers remotely ? if yes that will be great. can you send link how to do so ?

**Comment by krmahadevan** [comment]
@idan72 - What if you built all the (3) as part of a standalone server (in any technology since its going to be an independent web app).

For e.g., if you were to be doing in java, you could make use of [UnderTow](https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#the-builder-api) and literally build the server and the endpoints in a few Java lines of code.

You would then deploy this web app along with the node. From the RemoteWebDriver you can always find out to which node your test was routed to and then using that IP (port number would already be known to you), you could send separate http commands to your standalone web app to do (2) and (3)

**Comment by krmahadevan** [comment]
So essentially every machine on which your Selenium4 node runs, you would also run this standalone java app (So 2 JVMs per node machine)

**Comment by idan72** [comment]
Yes, this is possible workaround
I just implement it using HttpServer from Java SDK.

But as you said it require another JVM and another thing to take care  of

**Comment by krmahadevan** [comment]
@idan72 - Here's another approach that I can think of 

You could perhaps create a decorated node (details are available here https://www.selenium.dev/documentation/grid/advanced_features/customize_node/) which would represent your customized node.

You can now configure your `executeDriverCommand` to look like below


```java
  public HttpResponse executeWebDriverCommand(HttpRequest req) {
    try {
      System.err.println("Before executeWebDriverCommand(): " + req.getUri());
      if (req.getUri().contains("greetings")) {
        return executeSomeCommand(req);
      }
      return node.executeWebDriverCommand(req);
    } finally {
      System.err.println("After executeWebDriverCommand()");
    }
  }

  private HttpResponse executeSomeCommand(HttpRequest req) {
    HttpResponse response = new HttpResponse();
    String name = req.getQueryParameter("name");
    response.setContent(Contents.utf8String("Name is " + name));
    return response;
  }

```

And here's how a test case would look like

```java
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpClient.Factory;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;

public class Playground {

  public static void main(String[] args) throws Exception {
    RemoteWebDriver driver = new RemoteWebDriver(
        new URL("http://localhost:4444"), new FirefoxOptions());
    driver.get("https://www.google.com");
    String session = driver.getSessionId().toString();
    String path = "/session/" + session + "/greetings?name=Jack";
    try (HttpClient client = Factory.createDefault()
        .createClient(getNodeURL(session))) {
      HttpRequest req = new HttpRequest(HttpMethod.GET, path);
      HttpResponse response = client.execute(req);
      System.err.println("Response = " + response.toString());
    }
    driver.quit();
  }

  private static URL getNodeURL(String session) throws MalformedURLException {
    //Alter this method to use the session id, and query the
    // https://www.selenium.dev/documentation/grid/advanced_features/endpoints/#grid-status
    // to extract out the node URL
    return new URL("http://localhost:5555");
  }
}

**Comment by krmahadevan** [comment]
Here's the output

```bash
May 17, 2023 9:46:32 AM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Response = 200: Name is Jack

```

**Comment by idan72** [comment]
Hi,
Thnanks for this idea

I implemented this code and thought abbout using it but it look to me wrong although it will works as the method called executedWebDriverCommand and need to send the session

looks like it will quite easy to add one more method to the node class to support any Request.
What do you think ?

**Comment by krmahadevan** [comment]
> looks like it will quite easy to add one more method to the node class to support any Request.

What exactly do you mean by any `Request`? I didn't quite understand this part. Can you please elaborate with an example ?
I ask because, `HttpRequest` is actually any valid http request (you can try sending one even via CLI tools such as `wget` (or) `curl` or using UI tools such as `postman` and it should work with all of them.

**Comment by krmahadevan** [comment]
> I implemented this code and thought abbout using it but it look to me wrong 

Which part is wrong in your observation? Please add some context, since am curious to u'stand why you feel so.

**Comment by idan72** [comment]
the executeWebDriverCommand was meant to be use to communicate with the webdriver and it depend that the URL will contain the session id.

I think that if we will have something like executeCustomRequest that will be called with URL <node url>:<prot>/custom/...
It will be better.
So In code for example it will be : 
    String path = "/custom/greetings?name=Jack";

**Comment by krmahadevan** [comment]
@idan72 

That is not true.

Lets say you refactored the node to look like below, it will literally support everything (i.e., it can work with urls that are session aware and session agnostic)

```java
  @Override
  public HttpResponse executeWebDriverCommand(HttpRequest req) {
    try {
      System.err.println("Before executeWebDriverCommand(): " + req.getUri());
      if (req.getUri().contains("/custom")) {
        return executeSomeCommand(req);
      }
      return node.executeWebDriverCommand(req);
    } finally {
      System.err.println("After executeWebDriverCommand()");
    }
  }

  private HttpResponse executeSomeCommand(HttpRequest req) {
    HttpResponse response = new HttpResponse();
    String name = req.getQueryParameter("name");
    response.setContent(Contents.utf8String("Name is " + name));
    return response;
  }

  @Override
  public boolean matches(HttpRequest req) {
    if (req.getUri().startsWith("/custom")) {
      return true;
    }
    return node.matches(req);
  }

  @Override
  public HttpResponse execute(HttpRequest req) {
    if (req.getUri().contains("/custom")) {
      return executeSomeCommand(req);
    }
    return node.execute(req);
  }

```

And here's the modified sample along with the output

```java
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpClient.Factory;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;

public class Playground {

  public static void main(String[] args) throws Exception {
    RemoteWebDriver driver = new RemoteWebDriver(
        new URL("http://localhost:4444"), new FirefoxOptions());
    driver.get("https://www.google.com");
    String session = driver.getSessionId().toString();
    String path = "/session/" + session + "/custom?name=Jack";
    try (HttpClient client = Factory.createDefault()
        .createClient(getNodeURL(session))) {
      HttpRequest req = new HttpRequest(HttpMethod.GET, path);
      HttpResponse response = client.execute(req);
      System.err.println("Response = " + response.toString());
    }

    path = "/custom?name=krishnan";
    try (HttpClient client = Factory.createDefault()
        .createClient(getNodeURL(session))) {
      HttpRequest req = new HttpRequest(HttpMethod.GET, path);
      HttpResponse response = client.execute(req);
      System.err.println("Second Response = " + response.toString());
    }


    driver.quit();
  }

  private static URL getNodeURL(String session) throws MalformedURLException {
    //Alter this method to use the session id, and query the
    // https://www.selenium.dev/documentation/grid/advanced_features/endpoints/#grid-status
    // to extract out the node URL
    return new URL("http://localhost:5555");
  }
}

```

output

```bash
May 17, 2023 6:28:15 PM org.openqa.selenium.remote.tracing.opentelemetry.OpenTelemetryTracer createTracer
INFO: Using OpenTelemetry for tracing
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Response = 200: Name is Jack
Second Response = 200: Name is krishnan

Process finished with exit code 0
```

**Comment by idan72** [comment]
That will be great, if you add the execute method to the node so you  override it.

It is just sound wrong for me to use method executeWebDriverCommand and execute something that not relevant to web driver

Thanks for your effort

**Comment by krmahadevan** [comment]
@idan72 - The sample I shared is from released version of selenium. So all of that is already there for you to use.

**Comment by idan72** [comment]
Hi,

Looking at the example in https://www.selenium.dev/documentation/grid/advanced_features/customize_node/ I dont see the execute method

Also when I define : 
public class MyNode extends org.openqa.selenium.grid.node.Node 

No need to implement this method as it implement in Node class and not empry abstract method so I didnt notice it.

This is the current implemention  : https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/Node.java

  @Override
  public HttpResponse execute(HttpRequest req) {
    return routes.execute(req);
  }

It looks to me that what you did will work but it is a workaround and not the "clean" way to do it

Thanks for your effort and for the great idea how to overcome this issue

**Comment by diemol** [comment]
Thanks for commenting @krmahadevan and @idan72 

I do understand the use case right now, but since a while ago we are taking the approach of adding features to the core base when a wide range of the community needs them. This is to reduce maintainability given we are a reduced team. So far, only a few folks have asked this feature.

I will leave this issue open for a while to see if more people have thoughts.
