### ISSUE TITLE
[🚀 Feature]: CI should use Selenium Manager for all tests

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12047]
### Feature and motivation

I think our CI should delete the drivers that exist on the runners and always use Selenium Manager. I know that this means if we break Selenium Manager that none of the tests will pass, but it's essentially dog-fooding our own product, and we need something that ensures it works. 

I think @diemol has an alternate proposal.

### Usage example

n/a

**Comment by diemol** [comment]
I think @shs96c had some good arguments against this which I forgot. 

But I would prefer to push nightly releases and run the examples we have in the docs with those nightly releases, which should then use Selenium Manager.

**Comment by titusfortner** [comment]
Nightly releases would be awesome. How long will it take us to set that up? 😄

**Comment by nvborisenko** [comment]
Nightly? Or when we have something new to release?..

**Comment by titusfortner** [comment]
I think ruby creates a gem every night even if nothing has changed. Could probably check if anything has changed if we need to

**Comment by diemol** [comment]
During the meeting on [25.05.2023](https://www.selenium.dev/meetings/2023/tlc-05-25/) it was decided that we should do it, use Selenium Manager in CI by removing the env vars in GitHub runners.
