### ISSUE TITLE
[🐛 Bug]: When I try to download chromedriver with selenium-manager, it failed with error. 

### ISSUE THREAD

**Issue by Lydia-new** [SeleniumHQ/selenium#12048]
### What happened?

Use below command to run:
selenium-manager.exe --browser chrome --timeout 600 --debug

Will get below response:

DEBUG   Using timeout of 600 seconds
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "wmic datafile where name='%PROGRAMFILES:\\=\\\\%\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=113.0.5672.93\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 113.0.5672.93
DEBUG   Detected browser: chrome 113
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113
ERROR   error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

### How can we reproduce the issue?

```shell
run this command: selenium-manager.exe --browser chrome --timeout 600 --debug from a windows client.
```

### Relevant log output

```shell
DEBUG   Using timeout of 600 seconds
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: "wmic datafile where name='%PROGRAMFILES:\\=\\\\%\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe' get Version /value"
DEBUG   Output: "\r\r\n\r\r\nVersion=113.0.5672.93\r\r\n\r\r\n\r\r\n\r"
DEBUG   The version of chrome is 113.0.5672.93
DEBUG   Detected browser: chrome 113
DEBUG   Reading chromedriver version from https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113
ERROR   error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_113): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
```

### Operating System

Windows Server 2019

### Selenium version

python 3.7

### What are the browser(s) and version(s) where you see this issue?

Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113 downloading

### Are you using Selenium Grid?

no.

**Comment by diemol** [comment]
A couple of things...
- For now, Selenium Manager is not meant to be used directly
- Are you behind a proxy?

**Comment by Lydia-new** [comment]
> A couple of things...
> 
> * For now, Selenium Manager is not meant to be used directly
> * Are you behind a proxy?

Thanks for your reply. I checked maybe due to the network issue, I can download it in another environment.  
And for your first question, it can't be used directly? Then how can I use it to manager my driver?

**Comment by Lydia-new** [comment]
I saw it in the below documentation page, so I thought it can be used directly. 

https://www.selenium.dev/blog/2022/introducing-selenium-manager/

![image](https://github.com/SeleniumHQ/selenium/assets/133746621/dcdc01a6-ab3a-4cd0-ab4c-b0cc62d851ca)

**Comment by diemol** [comment]
In the initial post we shared details of how it works and how it is used under the hood. 

To put it short, if you are using the Selenium bindings or Selenium Grid, they will interact with Selenium Manager and manage the drivers for you. No need to use it directly.

**Comment by diemol** [comment]
I will close this issue since it seems it was related to the environment. If you were behind a proxy, please follow https://github.com/SeleniumHQ/selenium/issues/11294 to know when proxy support gets implemented.

**Comment by Lydia-new** [comment]
@diemol hi Diemol, thanks for your reply. But I'm still not quite clear about how to use it? Can you share me a little more detail? Appreciate for your help!

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#1-selenium-manager-beta

If you use Selenium 4.6.0 or newer, you are already using Selenium Manager.

**Comment by Lydia-new** [comment]
I'm using Selenium 4.9, but how to use it in my code, I only know below is using webdriver-manager:
self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

don't know how to use selenium manager by default.

**Comment by diemol** [comment]
No need to use a 3rd party driver manager or to pass a service anymore, only do `driver = webdriver.Chrome()`

**Comment by Lydia-new** [comment]
@diemol I got another issue, hope you can help!
I'm using Selenium 4.9 within C#, when try to download the chromedriver automatically, it always failed with timeout error like below: OpenQA.Selenium.WebDriverException : Invalid response from process (code 65): selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
request or response body error: operation timed out

But if I download it with selenium-manager manual with adding timeout=300, it can success. 
So my question is how can I pass a timeout parameter to default downloading process? Is that possible?

Thanks a lot!

**Comment by diemol** [comment]
Can you please create an issue for that?

**Comment by Lydia-new** [comment]
@diemol Hi Diemol, I have one more question about selenium-manager. Appreciate your help in advance!
The thing is: I've done my code to automatically download chromedriver in my local environment, now I want to move it to another production environment which running with the dll files, so how can I use selenium-manager automatically? Do I need to copy the selenium-manager.exe to the production environment manually?

**Comment by diemol** [comment]
No, you simply need to use a recent version of Selenium. I'll leave some links below in case you have more questions.

**Comment by kenny-q** [comment]
> No need to use a 3rd party driver manager or to pass a service anymore, only do `driver = webdriver.Chrome()`

I haven't found any single place on your documentation that explains the way to use Selenium Manager. Some things are not very intuitive by default, and knowing that we just need to do `driver = webdriver.Chrome()` would be nice to have it documented.

**Comment by diemol** [comment]
Because that is the point, you only need to use Selenium normally and do not care about anything else. No need to configure drivers on your own.

**Comment by titusfortner** [comment]
I just updated how we describe it here - https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#1-selenium-manager-beta
If this is still confusing, I'm sure we can write it better. What can we make less confusing?

**Comment by Lydia-new** [comment]
Yes, but for the user which using old versions, they won't know this at all. At least lots of users are still use webdriver manager.

**Comment by Lydia-new** [comment]
I think you need to write more samples in the documentation, its more easy to understand and get to know it.

**Comment by diemol** [comment]
The point is that nothing special is needed to use Selenium Manager, so docs would say "just use Selenium :)". 

We need to communicate clearly that users do not need 3rd party browser driver managers.

**Comment by kenny-q** [comment]
For me having a very simple example about how to use the new Selenium Manager should do the job. For instance, now we know we just need to do `driver = webdriver.Chrome();` but what type of object is webdriver??? (and so on) So my point is, having a simple snippet on the documentation showing the usage will avoid so many unnecessary questions.

**Comment by kenny-q** [comment]
> The point is that nothing special is needed to use Selenium Manager, so docs would say "just use Selenium :)".
> 
> We need to communicate clearly that users do not need 3rd party browser driver managers.

I agree to disagree, "some things are not very intuitive for everyone". I'm the consumer and I'm giving you my feedback!

**Comment by diemol** [comment]
Is point 1 not clear? What would you improve?
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#four-ways-to-use-drivers

**Comment by kenny-q** [comment]
> Is point 1 not clear? What would you improve? https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#four-ways-to-use-drivers

If you are not here to help, please let others do it, there are 2 people on this thread telling you with examples that the documentation have some gaps on how to actually use Selenium Manager. Let the arrogance aside and at least read our comments.

**Comment by Lydia-new** [comment]
In my opinion, it's more better to add something like this: by using driver = new ChromeDriver(), and the selenium-manager will download the chromedriver(or other driver) automatically in below path: C:/Users/user/.cache... and so on. Every time when you running your test, if your browser upgraded, the driver will upgraded too.

**Comment by kenny-q** [comment]
> In my opinion, it's more better to add something like this: by using driver = new ChromeDriver(), and the selenium-manager will download the chromedriver(or other driver) automatically in below path: C:/Users/user/.cache... and so on. Every time when you running your test, if your browser upgraded, the driver will upgraded too.

Based on one of the comments above we should use `driver = webdriver.Chrome()` on your example is `driver = new ChromeDriver()` but not, this is not confusing at all.

**Comment by krmahadevan** [comment]
@Lydia-new - I would like to view the Selenium Manager as the invisible assistant. It resides behind the scenes and figures out what browser flavour are you automating and based on that, it automatically figures out what driver binary flavour to download depending on your OS flavour and architecture. 

That is its purpose. So from an end-user's perspective, it should not be visible at all. 

The stuff that you called out (such as it would download the chromedriver etc., and dump it in a path that resides in your local machine) are implementation details, which I think are better off if they are present in the selenium manager documentation. Are you suggesting that there should be a link somewhere in http://selenium.dev that basically provides a link to https://github.com/SeleniumHQ/selenium/tree/trunk/rust which explains the selenium manager internals/cli args etc., in more detail ?

**Comment by titusfortner** [comment]
Thanks for the specific suggestion, @Lydia-new 

@kenny-q there's no reason to read malice or arrogance into what Diego is saying. He's literally asking what you would change in the explanation we (I) just updated. But I'm not sure you actually understand this well enough to know how we could explain it better, so let's try to clear up your confusion. You seem confused about how to start Selenium? Or is it just confusion that Selenium is implemented in 5 different languages?

**Comment by kenny-q** [comment]
> Thanks for the specific suggestion, @Lydia-new
> 
> @kenny-q there's no reason to read malice or arrogance into what Diego is saying. He's literally asking what you would change in the explanation we (I) just updated. But I'm not sure you actually understand this well enough to know how we could explain it better, so let's try to clear up your confusion. You seem confused about how to start Selenium? Or is it just confusion that Selenium is implemented in 5 different languages?

My confusion is on how to actually use Selenium Manager, and having it documented to avoid the same questions we all agree that saying on a post that we just need to use `driver = webdriver.Chrome()` is not enough (because again, what's webdriver for example?)

I don't want to use examples, but we all agree that if you read this: https://bonigarcia.dev/webdrivermanager/ is very well documented in a way everyone understand and actually see the code in action. From my perspective that's the gap on your documentation.

**Comment by titusfortner** [comment]
Yes, but webdriver manager isn't automatic. You have to write additional code to use it. It's a separate project that needs explanation.

In current Selenium you no longer have to do anything driver management related. Just start writing Selenium code and Selenium will figure it out for you. You don't even need to know that there is anything called Selenium Manager. It'll just work.

I think you are getting confused between the Python example and the Java example that are both being referenced. This code works: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/src/test/java/dev/selenium/getting_started/FirstScriptTest.java
No drivers on the system, no references to drivers, no references to Selenium Manager.

I think what we eventually want to do is remove "Install Drivers" page entirely, create a special error in bindings for Selenium not finding the driver, and provide a link to https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/ with info on how to determine what's happening and how to address it.

**Comment by kenny-q** [comment]
> 

That's a great idea, but as I mentioned before I was waiting for something more simple like adding one very simple code snippet on the first option on this link: https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#1-selenium-manager-beta

something like this for Java ->

**this is an extract**
```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class ExampleTest {
    WebDriver driver;
    
    public void Test() {
         driver = new ChromeDriver();
         driver.get("https://www.google.com");
    }
}
```
And again I'm not saying that's this is a proper way of doing it or that I want to push "my way", but being honest with you having something like this, very simple documented is very appreciated for everyone.

**Comment by titusfortner** [comment]
But that code snippet is for starting a WebDriver session not "using Selenium Manager"
That code is linked here - https://www.selenium.dev/documentation/webdriver/getting_started/first_script/

You don't use Selenium Manager.
You use the Selenium bindings which use the Selenium Manager.
The frustrating bit here is that you would be less confused if you'd never heard of "Selenium Manager." Things would just work and you wouldn't care how or why (just like I'm guessing you don't care how commands are getting serialized and what endpoints the drivers are listening to).

**Comment by kenny-q** [comment]
You are right, but I'm starting my driver now using somehow the new Selenium Driver, I was using the old `System.setProperty("webdriver.chrome.driver", "path/chromedriver");` before, and Lydia as well (I think)

So from an old consumer perspective, we want to actually see the new way of doing it (which exists, but is just in another place like this last link you posted). Everything is fine, I just lost myself with the new "Selenium Manager" term.

**Comment by titusfortner** [comment]
My frustration comes from knowing that we're not doing a great job communicating things, but not being sure the best way to change tack. :)

**Comment by titusfortner** [comment]
@kenny-q do you think this PR makes things more clear what is going on?
https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1390

**Comment by kenny-q** [comment]
This is wayyy more descriptive!! Huge change for good <3

**Comment by titusfortner** [comment]
Excellent! thanks.
