### ISSUE TITLE
[🚀 Feature]:  Secret variables  / plain-text passwords

### ISSUE THREAD

**Issue by spea1** [SeleniumHQ/selenium#12043]
### Feature and motivation

Nowadays, IT security has become an important issue. In many environments, plain-text passwords are unacceptable. Therefore, the introduction of secret variables should be reconsidered. 

### Usage example

Selenium hub and nodes could be started with a magic word to decrypt these secret variables before they are used. The decrypted contents of these secret variables should also not be logged away. Creating these secret variables with the same magic word should be possible in the IDE, for example.

Hide/mask/scrub secrets/passwords in logs #9339 
https://github.com/SeleniumHQ/selenium/issues/9339

**Comment by titusfortner** [comment]
The last issue was closed due to lack of interest. Is this something you would be interested in working on?

**Comment by spea1** [comment]
> The last issue was closed due to lack of interest. Is this something you would be interested in working on?

I offer myself as a tester.

**Comment by titusfortner** [comment]
The issue is it is not a priority for the devs right now, so we'd need help from someone in the community to help implement this.
