### ISSUE TITLE
[🚀 Feature]: Support for running safari in headless mode

### ISSUE THREAD

**Issue by bryancoxdish** [SeleniumHQ/selenium#12046]
### Feature and motivation

Currently, we are able to run tests with chrome and firefox in headless mode.  With safari the number 2 most common used browser, it would be nice if there was a way to run tests using safari in headless mode.

### Usage example

Currently, we are able to run tests with chrome and firefox in headless mode.  With safari the number 2 most common used browser, it would be nice if there was a way to run tests using safari in headless mode.

**Comment by titusfortner** [comment]
You might be able to try something like https://www.xquartz.org/
