### ISSUE TITLE
Selenium scrolls badly when trying to click on Firefox

### ISSUE THREAD

**Issue by germanp** [SeleniumHQ/selenium#1204]
I've found that selenium scrolls badly when I try to click on a table's row and when to reach this row the browser must scroll down. When this happen, the browser scrolls one extra row past the expected one and it clicks in the wrong location.

I've found that this issue occurs after we upgraded to selenium version 2.4.80, using 2.47.3 this issue doesn't occurs, at least with firefox.

Greets, let me know if you need more info, tks

**Comment by p0deje** [comment]
It might be related to #1202 

please provide a way to reproduce the issue, we can't do anything about it until that is provided. We can reopen the issue when it is provided.
