### ISSUE TITLE
[🐛 Bug]: Use Selenium 4.9 within C# to download automatically failed with timeout error. 

### ISSUE THREAD

**Issue by Lydia-new** [SeleniumHQ/selenium#12053]
### What happened?

I'm using Selenium 4.9 within C#, when try to download the chromedriver automatically, it always failed with timeout error like below: OpenQA.Selenium.WebDriverException : Invalid response from process (code 65): selenium-manager/windows/selenium-manager.exe --browser "chrome" --output json
request or response body error: operation timed out

But if I download it with selenium-manager manual with adding timeout=300, it can success.

So the issue is if we can add some parameter to the code to not using the default timeout value 60, then the issue can be resolved.

### How can we reproduce the issue?

```shell
Using Selenium 4.9 within C#. 
Write below code:
ChromeDriver driver = new ChromeDriver();

It will fail with below error:
Message: OpenQA.Selenium.WebDriverException : Unable to locate driver with path: chromedriver.exe, for more information on how to install drivers see https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
  ----> OpenQA.Selenium.WebDriverException : Invalid response from process (code 65): selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
request or response body error: operation timed out
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
```

### Relevant log output

```shell
Message: OpenQA.Selenium.WebDriverException : Unable to locate driver with path: chromedriver.exe, for more information on how to install drivers see https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
  ----> OpenQA.Selenium.WebDriverException : Invalid response from process (code 65): selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
request or response body error: operation timed out
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
```

### Operating System

Windows 10

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome113

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113

### Are you using Selenium Grid?

NO

**Comment by diemol** [comment]
Thank you for sharing this.

@bonigarcia what is the default timeout in Selenium Manager?

@titusfortner what do you think? This seems to be a slow connection that just needs longer to get the binary. Should we set a longer timeout by default?

**Comment by bonigarcia** [comment]
The default timeout in Selenium Manager is [120 seconds](https://github.com/SeleniumHQ/selenium/blob/trunk/rust/src/lib.rs#LL57C38-L57C145). This timeout is applied from when the request starts connecting until the response body has finished.

This parameter can be easily tuned in the latest versions of Selenium Manager using environment variables or the global configuration file.

Let's suppose we want a timeout of 300 seconds. This setup can be achieved as follows:

1. Creating the following config:  `%HOME%/.cache/selenium/selenium-manager-config.toml` and include the following:
```
timeout = 300
```

2. Set the following environment variable before running Selenium:
```
set SE_TIMEOUT=300
```

**Comment by diemol** [comment]
@Lydia-new can you please one of the above?

**Comment by Lydia-new** [comment]
@diemol  Hi, I've tried adding config file with timeout is 600, but it still failed with the error:

Message: OpenQA.Selenium.WebDriverException : Unable to locate driver with path: chromedriver.exe, for more information on how to install drivers see https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
  ----> OpenQA.Selenium.WebDriverException : Invalid response from process (code 65): selenium-manager/windows/selenium-manager.exe  --browser "chrome" --output json
request or response body error: operation timed out
TearDown : System.NullReferenceException : Object reference not set to an instance of an object

Elapsed time: 0:02:00.698

It seems the config didn't work at all.

**Comment by diemol** [comment]
Can you list the contents of `%HOME%/.cache/selenium/`, please?

**Comment by Lydia-new** [comment]
![image](https://github.com/SeleniumHQ/selenium/assets/133746621/0797a70a-aa91-4447-a004-3e6c59fdb0b7)

**Comment by diemol** [comment]
The issue might be that the Selenium Manager binary we distributed in 4.9 does not have the feature of reading the configuration file yet.

**Comment by Lydia-new** [comment]
So I only can waiting for the 4.10 to release?

**Comment by bonigarcia** [comment]
I have checked the latest [selenium-manager binary](https://github.com/SeleniumHQ/selenium/blob/trunk/common/manager/windows/selenium-manager.exe) and unfortunately it does not contain the patch for configuration file/envs. So yes, I'm afraid until the next Selenium release this feature is not available, sorry.

**Comment by Lydia-new** [comment]
May I ask the timeline for next release? Thanks a lot!

**Comment by diemol** [comment]
If things go well, end of May.

**Comment by Lydia-new** [comment]
Great, well to know that. Thanks!

**Comment by diemol** [comment]
Binaries updated and will be part of the 4.10.0 release

https://github.com/SeleniumHQ/selenium/commit/3c6c3bebe057ba3af262afac4c99f1ceadcdd647
