### ISSUE TITLE
[🚀 Feature]: Selenium Anti-Bot Detection

### ISSUE THREAD

**Issue by justme6666** [SeleniumHQ/selenium#12060]
### Feature and motivation

Hi,

I would be really nice if selenium had a feature to avoid most bot detections, as this is really necessary for web scrapping.

### Usage example

I am using Selenium for web scrapping and I always get a bad score or 0.1- 0.3 (bot) on websites such as https://antcpt.com/score_detector/ instead of a 0.7-0.9 score

I am using chrome webdriver with the following arguments, but I am still detected as a BOT by most websites.....

System.setProperty("webdriver.chrome.driver", webDriverPath);

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--incognito");
        options.addArguments("--ignore-certificate-errors");
        options.addArguments("--remote-allow-origins=*");
        options.addArguments("--disable-blink-features=AutomationControlled");
        options.setExperimentalOption("excludeSwitches", new String[] { "enable-automation" });
        options.setExperimentalOption("useAutomationExtension", false);

I did find this useful tool, an undetectable Chrome webdriver written in Python but my project is written in Java and I will have to re-write it in Python to use the webdriver bellow....so I was hoping there was some quick fix to this, like some arguments like the ones above for me to try before starting to re-write everything in Python....

https://github.com/ultrafunkamsterdam/undetected-chromedriver 

        driver = new ChromeDriver(options);

**Comment by diemol** [comment]
In short, Selenium cannot bypass captcha, it is a bot.

It is by design so websites can detect and allow or disallow if they want to be automated or not.
