### ISSUE TITLE
[🐛 Bug]: Timeout when running Saucelabs tests on Selenium 4.9.0+ using JdkHttpClient

### ISSUE THREAD

**Issue by Artur-** [SeleniumHQ/selenium#12069]
### What happened?

When running multiple Saucelabs tests in parallel we see a lot of timeouts when trying to upgrade from Selenium 4.8.3 to 4.9.0. 

The errors are timeouts creating drivers or `org.openqa.selenium.WebDriverException: Invalid message: ERROR Internal Server Error` or `Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol` (which might be that same but obfuscated because of #11927)

After bisecting the issue, we see that this is caused by #11816. It seems a bit like Saucelabs uses redirects when waiting for a session to be available and Selenium no longer correctly follows those

### How can we reproduce the issue?

```shell
https://github.com/vaadin/testbench/pull/1645 is our test PR which shows the problem when run in our CI. Not sure how to reproduce it elsewhere as it does not reproduce locally. Potentially by running more tests in parallel than available Saucelabs slots, so the tests have to wait for a driver for more than 30-60s.
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol 

or

org.openqa.selenium.WebDriverException: Invalid message: ERROR Internal Server Error
```

### Operating System

Linux, version 4.14.231-173.361.amzn2.x86_64

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Unrelated

### What are the browser driver(s) and version(s) where you see this issue?

Unrelated

**Comment by joerg1985** [comment]
@Artur- You could try to set ` -Djavax.net.debug=all` to see the raw traffic including the redirects from the server. 
The headers of the redirects (without the authentication part) could be helpful to analyze the issue.

**Comment by Artur-** [comment]
I tried debugging this and what I see is:
1. First a lot of POST requests to /session. These happen in parallel as tests are run in parallel
2. For the first N requests, a response of 200 is received and the tests run. All is fine.
3. After about a 30-60s the first 303 response comes in. It has a response header of e.g. `location: /wd/hub/session/21968f90a4ad462a8c5ba00cee4de1c0`
4. Now when that URL is fetched, the response is
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol
```

with the data in the response
```
{status=13, sessionId=21968f90a4ad462a8c5ba00cee4de1c0, value={message=Invalid message: ERROR Internal Server Error}} 
```

**Comment by Artur-** [comment]
Logging the headers does not reveal much more
```
request headers: {Content-Type=[application/json; charset=utf-8], User-Agent=[selenium/4.9.1 (java mac)]}
Response code for (POST) /session is 303
Redirect for (POST) /session to Optional[/wd/hub/session/593eb83b24624f739c5d27d24b898416]
response headers: {content-length=[0], content-type=[text/html], date=[Fri, 19 May 2023 15:40:49 GMT], location=[/wd/hub/session/593eb83b24624f739c5d27d24b898416], server=[monocle/0.42], x-request-id=[459a196e-c2a3-4861-ad94-62d585f0da8a]}
request headers: {Content-Type=[application/json; charset=utf-8], User-Agent=[selenium/4.9.1 (java mac)]}
Response code for (POST) /session is 200
Ending request (POST) /session in 46463ms
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol: {status=13, sessionId=593eb83b24624f739c5d27d24b898416, value={message=Invalid message: ERROR Internal Server Error}} 
```

**Comment by Artur-** [comment]
But is a 303 for a POST request really supposed to re-post the request to the Location URL? Isn't it supposed to do a GET on that URL instead, without a body? https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#temporary_redirections

**Comment by diemol** [comment]
If you want to try it out, I pushed 4.10.0-SNAPSHOT, but you need to add the [SNAPSHOT repository](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/java/pom.xml#L21-L29) to your POM.

**Comment by Artur-** [comment]
I have rerun our tests now quite a few times with the fix and it resolves the problem 🎉
