### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.JavascriptException: Message: javascript error: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by qingfeng520** [SeleniumHQ/selenium#12078]
### What happened?

when run the code the code where report a bug:
driver.find_elements(By.XPATH, '//*[@id="app-content"]/div/div[3]/div/div/button')

### How can we reproduce the issue?

```shell
when run the code: driver.find_elements where report a bug
```

### Relevant log output

```shell
File "D:\Softwares\Python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Softwares\Python3\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\Softwares\Python3\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Object.hasOwn is not a function
  (Session info: chrome=113.0.5672.127)
```

### Operating System

Windows11

### Selenium version

Python 3.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.63

**Comment by diemol** [comment]
We closed a similar issue last week because there was no way of reproducing it.

**Comment by iniyavans** [comment]
@diemol I'm also getting the same issue now 

While running the below code 

` wait.until(EC.presence_of_element_located((By.XPATH, "//button[text()='Get Started']"))).click()`

**Comment by diemol** [comment]
@iniyavans can you please provide a complete script to reproduce the issue? Otherwise it will stale and end up being closed.

**Comment by iniyavans** [comment]
@diemol will share my repo shortly!

**Comment by iniyavans** [comment]
EXTENSION_PATH = os.path.abspath('..') + '/metamask/extension_metamask.crx'

chromeDriver = os.path.abspath('..') + '/metamask/chromedriver/chromedriverV113'

chrome_options = Options()

chrome_options.add_extension(EXTENSION_PATH)

chrome_options.add_experimental_option("detach", True)

chrome_service = Service(chromeDriver)

driver = webdriver.Chrome(options=chrome_options, service=chrome_service)

driver.maximize_window()
    
driver.get("https://www.google.com/")

wait = WebDriverWait(driver, 20)

wait.until(EC.number_of_windows_to_be(2))

driver.switch_to.window(driver.window_handles[1])

wait.until(EC.presence_of_element_located((By.XPATH, "//button[text()='Get Started']"))).click()


@diemol I used above code

**Comment by iniyavans** [comment]
![Screenshot 2023-05-24 at 3 20 46 PM](https://github.com/SeleniumHQ/selenium/assets/88368294/76d5068b-5031-44ea-9769-1831d4133bff)
Getting above issue @diemol

**Comment by diemol** [comment]
Two questions:

- Where do I get this file? `EXTENSION_PATH = os.path.abspath('..') + '/metamask/extension_metamask.crx'`
- Does this happen only with that browser extension? What if you use a different one?

**Comment by iniyavans** [comment]
get the file from the below link @diemol 

https://drive.google.com/file/d/1N_tBBT7S5QKdihD4oPy2MyMj-5Qv8tV9/view?usp=sharing  @diemol

**Comment by iniyavans** [comment]
Answer for Q2: The basic selenium code will be working fine, I need to add the above extension file to automate my project. @diemol

**Comment by diemol** [comment]
OK, a bit of googling shows me that this is the browser extension 
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn

And if it only happens with that extension, there is not much we can do. Have you reached out to them?

**Comment by iniyavans** [comment]
No @diemol We just add the extension during the browser launch, And also the same code worked fine before. The issue comes after updating the Chrome version to 113.

**Comment by diemol** [comment]
I understand, but Selenium is doing its job of launching the browser through ChromeDriver and loading the extension. The code in Selenium has not changed. So you either need to check with the extension maintainers or raise an issue to the ChromeDriver folks.

**Comment by iniyavans** [comment]
Okay @diemol, Thanks!

**Comment by diemol** [comment]
I will leave the links where you can report this, but still, I am not sure if this is something with the extension or the browser.

**Comment by disposablecarcass** [comment]
> Hi, @qingfeng520. This issue has been determined to require fixes in [ChromeDriver](https://chromedriver.chromium.org/home).
> 
> You can see if the feature is passing in the [Web Platform Tests](https://wpt.fyi/results/webdriver/tests).
> 
> If it is something new, please [create an issue](https://bugs.chromium.org/p/chromedriver/issues/list) with the ChromeDriver team. Feel free to comment the issues that you raise back in this issue. Thank you.

Forgive my ignorance, but in that page you listed, how do I actually see if the issue was fixed in Chromedriver?

Does anyone know if this was resolved?

**Comment by titusfortner** [comment]
@disposablecarcass looks like a ticket was opened, but couldn't be reproduced with the provided example so it got closed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4446

If you have a reproducible example, please open a new ticket

**Comment by disposablecarcass** [comment]
> @disposablecarcass looks like a ticket was opened, but couldn't be reproduced with the provided example so it got closed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4446
> 
> If you have a reproducible example, please open a new ticket

thanks. I read thru his instructions in the link you provided and that user describes the issue perfectly. do you know what issues they had reproducing this? did they just not want to install the extension? if so I could upload my whole python project with the crx already moved to the project root. would that help? please let me know if that would be sufficient for someone to reproduce the error. thanks

Edtit: I've created a new issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4660

**Comment by diemol** [comment]
You'd need to ask that in the Chrome bug tracker.

**Comment by NCLnclNCL** [comment]
> > @disposablecarcass looks like a ticket was opened, but couldn't be reproduced with the provided example so it got closed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4446
> > If you have a reproducible example, please open a new ticket
> 
> thanks. I read thru his instructions in the link you provided and that user describes the issue perfectly. do you know what issues they had reproducing this? did they just not want to install the extension? if so I could upload my whole python project with the crx already moved to the project root. would that help? please let me know if that would be sufficient for someone to reproduce the error. thanks
> 
> Edtit: I've created a new issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4660

Because lava moat of metamask , you need disable it https://community.metamask.io/t/can-i-disable-lavamoat/24845/2
