### ISSUE TITLE
[🐛 Bug]: ChromeOptions.AddExtension(string path) doesn't work (C#)

### ISSUE THREAD

**Issue by moonfloww** [SeleniumHQ/selenium#12071]
### What happened?

As far as I can tell, this issue is on Selenium and not ChromeDriver.

In my code, I make a variable called "options" that is of ChromeOptions type. I check for if the extension file exists, download it if it isn't and dismiss if it is already up to date. I do ChromeOptions.AddExtension to add the extension to the ChromeOptions which does not give any errors and is seen to be fine but the extension is not added to ChromeDriver.

Please note that options and driver is defined in another file (Program is a partial class). Driver is not set to an instance of an object, as in, it is defined like `ChromeDriver driver;` instead of `ChromeDriver driver = new ChromeDriver();`. This modifies the ChromeOptions from Program.cs (where the main function is) and is meant to be used in another function which does `driver = new ChromeDriver(options);` (no type declaration because the variable already exists). I split them up for code readability.

I am using .Net 7. If further information is requested, I will provide every other file that is relevant to ChromeDriver.

### How can we reproduce the issue?

```cs
using System;
using System.ComponentModel;
using System.IO;
using System.Net.Http;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace Enurium
{
    public partial class Program
    {
        public static async void InitializeNopeCHAExtension()
        {
            info("Initializing captcha solver extension...");

            if (!File.Exists("ext.crx"))
            {
                File.Create("ext.crx").Close();
                warn("Captcha solver extension file doesn't exist. It has been created as ext.crx.");
            }

            using HttpClient client = new();
            HttpResponseMessage response = await client.GetAsync("https://nopecha.com/f/ext.crx");
            string extension = await response.Content.ReadAsStringAsync();

            if (File.ReadAllText("ext.crx") != extension)
            {
                info("Captcha solver extension is out of date. It has been updated.");
                File.WriteAllText("ext.crx", extension);
            }
            else
            {
                info("Captcha solver extension is up to date.");
            }

            options.AddExtensions(Path.GetFullPath("ext.crx")); // No errors, does absolutely nothing.
            info("Full Path: " + Path.GetFullPath("ext.crx"));
            info("Initialized captcha solver extension.");
        }
    }
}
```

### Relevant log output

```shell
Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 61670
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

DevTools listening on ws://127.0.0.1:61674/devtools/browser/68003bd0-07bd-4f34-826f-0750505bc4f2
```

### Operating System

Windows 10

### Selenium version

C# 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.63

**Comment by moonfloww** [comment]
The code that I provided is enough information. I described the issue. If you want further code, here:


```cs
// Program.cs
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;

namespace Enurium
{
    public partial class Program
    {
        static private ChromeDriver Driver;
        static private ChromeOptions options = new ChromeOptions();
        static private readonly Random r = new Random();
        static private readonly string NopechaKey = "";
        public static void Main()
        {
            Boot();
            InitializeSelenium(); // from Selenium_Initialization.cs //
            Thread.Sleep(1000); // Make sure that the NopeCHA extension has fully loaded //

            // ... //
        }
    }
}

// Initialize Selenium.cs
using OpenQA.Selenium;
using OpenQA.Selenium.Interactions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Enurium
{
    public partial class Program
    {
        public static void InitializeSelenium()
        {
            info("Initializing Selenium...");
            options.AddArguments(new string[] { "--no-sandbox", "--disable-infobars", "--disable-dev-shm-usage", "--disable-blink-features=AutomationControlled" });
            options.AddExcludedArgument("enable-automation");
            options.AddAdditionalOption("useAutomationExtension", false);
            info("Finished initializing arguments.");
            InitializeNopeCHAExtension();
            Driver = new OpenQA.Selenium.Chrome.ChromeDriver(options);
            Thread.Sleep(1000);
            Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(500);
            Driver.Navigate().GoToUrl("https://nopecha.com/setup#sub_1N9LuNCRwBwvt6ptidB0Yrpw");
            info("Captcha solver initialization fully finished.");
        }
    }
}
```

The info functions are for logging things. They are useless in troubleshooting this issue.

**Comment by diemol** [comment]
Where do you install the extension? The code does nothing with it.

**Comment by moonfloww** [comment]
The code I just sent is an add-on to the first code I provided. InitializeNopeCHAExtension() runs options.AddExtension which modifies options (ChromeOptions type), then goes back to the InitializeSelenium() function which actually initializes the driver with the options. However, the extension does not get added to ChromeDriver.

**Comment by titusfortner** [comment]
Adding extension code works in .NET — https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/dotnet/SeleniumDocs/Browsers/ChromeTest.cs#L24

This line of code won't do anything:
```
options.AddAdditionalOption("useAutomationExtension", false);
```
You probably want `AddAdditionalChromeOption`.

Bottom line is that Selenium is doing the right thing and you need to contact the extension authors to figure out why that extension isn't working for you.
