### ISSUE TITLE
[🐛 Bug]: missing selenium-server-4.9.1.jar?

### ISSUE THREAD

**Issue by chenrui333** [SeleniumHQ/selenium#12074]
### What happened?

Based on my reading and research, it should be a 4.9.1 release, but I could not find the release as well as the `selenium-server-4.9.1.jar` is missing? Let me know I missed anything, thanks!

**Comment by diemol** [comment]
Dot (patch) releases are placed under the minor release. https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.9.0/selenium-server-4.9.1.jar
