### ISSUE TITLE
[🐛 Bug]: Incorrect width

### ISSUE THREAD

**Issue by TheCarpetMerchant** [SeleniumHQ/selenium#12080]
### What happened?

The window size is set to 1800x1000 and the element is contained within the page as per Inspect tab, yet selenium cannot move to the end of the element.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import *
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
import time

chrome_options = Options()
chrome_options.add_argument("--window-size=1800,1000")
driver = webdriver.Chrome(options=chrome_options)
driver.get('https://stackoverflow.com/questions/6775351/clicking-at-coordinates-without-identifying-element')

time.sleep(1)

header = driver.find_element(by=By.CSS_SELECTOR, value='div#question-header')
ActionChains(driver).move_to_element_with_offset(header, header.rect['width'], 0).perform()

time.sleep(5)
```

### Relevant log output

```shell
/
```

### Operating System

Windows 10

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver.exe does not have a version number

**Comment by titusfortner** [comment]
Selenium conforms to the w3c specification which stipulates that movement to an element bring the cursor to the "in-view center-point" of the element. Presumably, moving by an offset of the width of that element from its center-point should result in an Out of Bounds Error.
