### ISSUE TITLE
[🐛 Bug]: add_cookie documentation is incorrect + how do I add a cookie ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [SeleniumHQ/selenium#12083]
### What happened?

Using the provided documentation for `add_cookie` leads to an error.

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Chrome()
driver.add_cookie({'name' : 'foo', 'value' : 'bar'}) # Fails with 'invalid cookie domain' despite domain being optional
driver.add_cookie({'name' : 'foo', 'value' : 'bar', 'domain': 'youtube.com'}) # How do I provide a correct domain ?
```

### Relevant log output

```shell
/
```

### Operating System

Windows 10

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver.exe does not have a version number

**Comment by diemol** [comment]
The current docs are correct, you need to be on the domain before creating the cookie.

https://www.selenium.dev/documentation/webdriver/interactions/cookies/#add-cookie

**Comment by TheCarpetMerchant** [comment]
@diemol Then the error should reflect that. How do I set cookies before accessing a url then ?

**Comment by titusfortner** [comment]
You cannot set a cookie for a site you are not on.

You can't set a cookie before navigating to a valid domain. If you set a cookie without specifying the optional domain parameter it will set the cookie on root of the current domain. The domain parameter is there to allow you to set the cookie on a subdomain of the current site instead.

The trick in the documentation is a good one. Most sites have a 404 page you can land on without being redirected.
