### ISSUE TITLE
[🐛 Bug]: NoSuchElementException on certain website since update Edge/Chrome version 113

### ISSUE THREAD

**Issue by IMeijSAR** [SeleniumHQ/selenium#12085]
### What happened?

In our automated regression test set, we have several test that will have to execute some actions on a specific website. However, since the Chrome/Edge update (somewhere between 5th of May and 8th of May) Selenium is unable to locate any elements on the website after login. The elements are there and can be located using developer tools. We are able to interact with the website/get elements by running javascript (see code below) but the selenium driver is unable to find the exact same elements. We added the source code of the website page where we run into trouble as txt.
[sourcecode.txt](https://github.com/SeleniumHQ/selenium/files/11542384/sourcecode.txt)

### How can we reproduce the issue?

```shell
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using System.Threading;

namespace OT_problems
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var driver = new EdgeDriver();
            driver.Navigate().GoToUrl("https://1archief.ontwikkeling.hosting.corp/otcs/llisapi.dll?func=ll&objId=2192251&objAction=browse&viewType=1");
            while (true)
            {
            var elements = driver.FindElements(By.XPath("//input[@id='otds_username']"));
                if (elements.Count > 0)
                {
                    elements[0].SendKeys("*****");
                    break;
                }
            }
            driver.FindElement(By.XPath("//input[@id='otds_password']")).SendKeys("*****");
            driver.FindElement(By.XPath("//input[@id='loginbutton']")).Click();
            Thread.Sleep(5_000);
            //etc
            var js = driver as IJavaScriptExecutor;
            var result = js.ExecuteScript("return document.getElementById('LLInnerContainer').textContent");
            var elements2 = driver.FindElements(By.Id("LLInnerContainer"));
            var result2 = js.ExecuteScript("return document.getElementById('historyFormLocatorDiv').outerHTML");
            var elements3 = driver.FindElements(By.Id("historyFormLocatorDiv"));

            driver.FindElement(By.XPath("//tr[@data-tnode='Post']//a[text()='Post']")).Click();
```

### Relevant log output

```shell
OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//tr[@data-tnode='Post']//a[text()='Post']"}
  (Session info: MicrosoftEdge=113.0.1774.50)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<.ctor>b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebDriver.FindElement(By by)
   at OT_problems.UnitTest1.TestMethod1() in C:\Users\AO619610\source\repos\rechtsbijstand.GRiP\Selenium\OT_problems\UnitTest1.cs:line 35

Locals during test (see how both results are filled, we can interect with website, however elements are not found?):

		this	{OT_problems.UnitTest1}	OT_problems.UnitTest1
+		driver	{OpenQA.Selenium.Edge.EdgeDriver}	OpenQA.Selenium.Edge.EdgeDriver
+		js	{OpenQA.Selenium.Edge.EdgeDriver}	OpenQA.Selenium.IJavaScriptExecutor {OpenQA.Selenium.Edge.EdgeDriver}
		result	"\r [placeholder for very long text] \n"	object {string}
+		elements2	Count = 0	System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.IWebElement>
		result2	"<div id=\"historyFormLocatorDiv\"></div>"	object {string}
+		elements3	Count = 0	System.Collections.ObjectModel.ReadOnlyCollection<OpenQA.Selenium.IWebElement>
```

### Operating System

Windows 10

### Selenium version

C# 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Edge 113.0.1774.50 and Chrome 113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 113.0.1774.50

### Are you using Selenium Grid?

-

**Comment by rickbreemer** [comment]
We have the same issue, also with a OpenText Content Server system. 

We have traced the issue to ../img/core/**ajax_dhtml_util.js** and specifically to the custom **JSON.stringify** implementation in that file:

```
var JSON = {
    org: 'http://www.JSON.org',
    copyright: '(c)2005 JSON.org',
    license: 'http://www.crockford.com/JSON/license.html',

    stringify: function (arg) { 
      //... etc
    }
}
```   

As a work-around, you can add the following code to the global appearance (header section):

```
<script>
    // ../img/core/ajax_dhtml_util.js messes up JSON.stringify, so reset it to a working version
    JSON.stringify = undefined;
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/json2/20160511/json2.min.js"></script>
```

**Comment by cliese1313** [comment]
We have the same issue on Chrome 113, Chrome 114 and Edge 113.
More than 50% of our automated tests that were working on 112 are failing on 113 with this error.
Rollback of Selenium WebDriver MSEdge to 112 is working for now running tests on Edge only

**Comment by diemol** [comment]
>Rollback of Selenium WebDriver for Edge to 112 is working for now

How do you rollback Selenium WebDriver to Edge 112?

**Comment by cliese1313** [comment]
> > Rollback of Selenium WebDriver for Edge to 112 is working for now
> 
> How do you rollback Selenium WebDriver to Edge 112?

Visual Studio>Tools>NuGet package manager 
under Installed click  Selenium.WebDriver.MSEdgeDriver
in the pane that displays select the solutions that have it installed
click the dropdown under version and select the most recent 112 version (112.0.1722.39) and click Install

**Comment by titusfortner** [comment]
That's the 3rd party driver management solution by [jsakamoto](https://www.nuget.org/profiles/jsakamoto)

So you are keeping v113 browser version and using v112 driver version? The driver will complain when the browser v114 is installed.

**Comment by titusfortner** [comment]
Does this error only happen with XPath? 

If changing the driver version fixes it, then it sounds like it is something for Google to fix.

**Comment by cliese1313** [comment]
> Does this error only happen with XPath?
> 
> If changing the driver version fixes it, then it sounds like it is something for Google to fix.

no happens with both xpath and id
yes, right now v113 Edge browser and v112 driver version is working

**Comment by cliese1313** [comment]
> Hi, @IMeijSAR. This issue has been determined to require fixes in [ChromeDriver](https://chromedriver.chromium.org/home).
> 
> You can see if the feature is passing in the [Web Platform Tests](https://wpt.fyi/results/webdriver/tests).
> 
> If it is something new, please [create an issue](https://bugs.chromium.org/p/chromedriver/issues/list) with the ChromeDriver team. Feel free to comment the issues that you raise back in this issue. Thank you.

For me it is happening with both ChromeDriver and MSEdge driver now since v113 - there are open tickets with bugs\Chromium.org

**Comment by titusfortner** [comment]
Yeah, Edgedriver is based on Chromedriver, so we file the bugs with Google and Microsoft helps out as necessary. If there are open tickets in the chromium tracking system, then that's where this issue belongs, there isn't anything Selenium project can do to fix it.

**Comment by anurag-rohilla** [comment]
> Does this error only happen with XPath?
> 
> If changing the driver version fixes it, then it sounds like it is something for Google to fix.

Do we know the ticket number raised with Google?

**Comment by cliese1313** [comment]
> > Does this error only happen with XPath?
> > If changing the driver version fixes it, then it sounds like it is something for Google to fix.
> 
> Do we know the ticket number raised with Google?

I have been watching this and there are a couple duplicate issues
 https://bugs.chromium.org/p/chromedriver/issues/detail?id=4440
