### ISSUE TITLE
org.openqa.selenium.TimeoutException when Navigate to Url 

### ISSUE THREAD

**Issue by ninhktran** [SeleniumHQ/selenium#12086]
### What happened?

Our web automations start failing with the new Chrome 112, 113 update around May 5th. This seems to happen when navigating directly to a URL multiple times in one session (as in many test cases in one test suite), with only one session it seems to run fine and caused no errors. We run all our jobs in jenkins. Let me know if any additional information is needed.

### How can we reproduce the issue?

```shell
This is what I have for my arguments:

                options.addArguments("start-maximized");
		options.addArguments("--no-sandbox");
		if (ignoreSSL.isPresent() && ignoreSSL.get()) {
			options.addArguments("--ignore-certificate-errors");
		}
		options.addArguments("--disable-gpu");
		options.addArguments("disable-quic");
		options.addArguments("--disable-browser-side-navigation");
		options.addArguments("--disable-dev-shm-usage");
		options.addArguments("enable-automation");
```

### Relevant log output

```shell
org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException

Other than that, no other log errors from webdriver or browser
```

### Operating System

Windows 10 amd 64

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.63

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Are you running in parallel or in series? You might see this error when the page isn't loading, which can happen if you are putting too much strain on either Jenkins or the system under test.

Selenium is correctly sending the commands to the driver and issue is that the browser isn't doing what the driver needs to see before the timeout, so there's nothing for us to change in the Selenium code.

**Comment by ninhktran** [comment]
I see. We run these tests in series. I was looking at it while it navigating to different pages and clicking on elements. But when it navigate to URL, visually, I can see that it successfully navigated to the page but it seems that Selenium does not recognize that it is already at the page. Not sure if anyone run into the same issue

Regarding not putting too much strain on Jenkins, are there any arguments you would suggest adding to the driver options to mitigate this timing out since it is very consistent? Or any related suggestions would help.

Thank you

**Comment by titusfortner** [comment]
Might there be something that hasn't finished loading even though the page looks ready? You might try setting page load strategy to eager in options and it won't wait for everything.
