### ISSUE TITLE
[🚀 Feature]: Serial Port Device Selection

### ISSUE THREAD

**Issue by albwrekt** [SeleniumHQ/selenium#12098]
### Feature and motivation

When testing web applications that require a device plugged into the computer/browser, currently there is no method (that I can see) to choose the COM Port/Device to connect the device to the browser, through the browser interface. The menu pops up with listed devices, but you can’t select/list the items programmatically.

### Usage example

If developing a device similar to home security devices/Alexa that require manual firmware updates by the end user, testing of these products would include plugging them into your computer, and then doing an update over browser. This process should be tested using automation because it is lengthy time, and is critical to the function of the device so it is important to have detailed test cases to approach these problems. Having browser access to select the device is the first step to kicking that process off.

**Comment by diemol** [comment]
There is a mix of something needed in WebDriver and testing strategies, I believe. WebDriver focuses on web applications on browsers. If you want to test the application that updates the firmware, you should be able to mock what the application needs to allow you test the workflow. On the other hand, you have the firmware update process, which I believe is out of the scope of WebDriver. 

However, that is just my opinion. If you think this is something that WebDriver should support, please create a feature request highlighting more clearly why this is needed. https://github.com/w3c/webdriver-bidi
