### ISSUE TITLE
Browsers won't open

### ISSUE THREAD

**Issue by hintonaac** [SeleniumHQ/selenium#1209]
I upgraded Selenium from 1.0 to 2.47.1 and now my automated test scripts are failing due to my browser not opening.

**Comment by titusfortner** [comment]
If you need assistance getting your tests to work, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

If you believe you have found a problem in the code, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
