### ISSUE TITLE
[🐛 Bug]: Error while trying to load a Firefox extension

### ISSUE THREAD

**Issue by willdurand** [SeleniumHQ/selenium#12094]
### What happened?

I am reporting an issue on behalf of someone else so bear with me. Loading an extension used to work with the same code but no longer works. The error message from Firefox is:

```
addons.xpi-utils	WARN	addMetadata: Add-on EvalVillain@2.8 is invalid: Error: Invalid addon ID: expected addon ID EvalVillain@2.8, found dennis@hurricanelabs.com in manifest(resource://gre/modules/addons/XPIDatabase.jsm:3105:15) JS
```

Now, what that means is that the extension ID is invalid and the reason is simple: Selenium reads the `manifest.json` file and look at the `applications` key in the manifest: https://github.com/SeleniumHQ/selenium/blob/9e165e5929a54e79a7adba8cd46aa58ab78ddc33/java/src/org/openqa/selenium/firefox/FileExtension.java#L135

That is a problem because this key is deprecated for some time now, and in fact, it isn't even recognized with Manifest Version 3. The code above should look for `browser_specific_settings` first, then `applications` (for backward compatibility). The rest won't change, i.e. the extension ID will be found in `browser_specific_settings.gecko.id`.

Why was that working before then? AMO, Mozilla's extensions portal, signs all add-ons. As part of the signing process, there is a "manifest normalization" step, which injects the extension ID into the `manifest.json` file if it isn't already present in the file.

### How can we reproduce the issue?

Not sure, try installing https://addons.mozilla.org/en-US/firefox/addon/eval-villain/ with Selenium/Firefox? Sorry that I cannot be more helpful.

### Relevant log output

```shell
n/a
```

### Operating System

n/a

### Selenium version

latest, I'd say

### What are the browser(s) and version(s) where you see this issue?

Firefox Release (latest)

### What are the browser driver(s) and version(s) where you see this issue?

unknown

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Is this how you are trying to install the add-on? https://www.selenium.dev/documentation/webdriver/browsers/firefox/#add-ons

This is the only way to do it as of Firefox ~47

**Comment by willdurand** [comment]
No idea, this is coming from https://github.com/zaproxy/zap-extensions but the information about the manifest.json keys is still relevant nonetheless, unless this code is no longer called.

**Comment by titusfortner** [comment]
I think that class is only used by profile class, which we are looking to deprecate. I'm not at my laptop to dig into it right now.

**Comment by psiinon** [comment]
ZAP project lead here - we're the originator of this issue 😁 
We're using `FirefoxProfile.addExtension` as per https://github.com/zaproxy/zap-extensions/blob/main/addOns/selenium/src/main/java/org/zaproxy/zap/extension/selenium/ExtensionSelenium.java#L962-L972

We are on selenium-server 3.141 which doesnt seem to have `driver.installExtension(xpiPath);` 
Is the recommended option that we update to the latest?
That is planned...

**Comment by titusfortner** [comment]
Well, yes, I'm always going to recommend updating to the latest, but that method existed in 3.x - https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L220

I am kind of curious when the existing code stopped working for you.

**Comment by psiinon** [comment]
Ha! I was trying `WebDriver` instead of `FirefoxDriver` - my bad!
Good question.
We only heard about it yesterday: https://github.com/zaproxy/zaproxy/issues/7878
We should really cover that in our daily integration tests, but too much to do, not enough time...

**Comment by psiinon** [comment]
@titusfortner `driver.installExtension(xpiPath);` works for us using the version we are on, so many thanks for that!
We will be upgrading to the latest selenium version as soon as we can.
I'm happy for this issue to be closed now...

**Comment by titusfortner** [comment]
Sounds good. Let us know if we can help with anything.
