### ISSUE TITLE
[🐛 Bug]: selenium-driver 4.9.1 causes chrome crashes in Capybara tests

### ISSUE THREAD

**Issue by ngan** [SeleniumHQ/selenium#12095]
### What happened?

After upgrading the `selenium-webdriver` gem from `4.9.0` => `4.9.1`, we're seeing frequent chrome crashes in our capybara tests.

### How can we reproduce the issue?

I'm not sure. It happens on 50% of our builds. Chrome logs don't give much information just has:
```shell
[1685009372.742][INFO]: [300ea01057ea3631a42446a81fb172a7] RESPONSE ExecuteScript ERROR unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=113.0.5672.126)
```

Please let me know how else I can be more helpful here.

### Relevant log output

```shell
unknown error: session deleted because of page crash
  | from unknown error: cannot determine loading status
  | from tab crashed
  | (Session info: headless chrome=113.0.5672.126)
  |  
  | invalid session id
```

### Operating System

Ubuntu 20.04

### Selenium version

Ruby 3.2.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.126

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.63

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Duplicate of #12013

**Comment by ngan** [comment]
Hi @titusfortner I don't think this is a duplicate of #12013. I've already upgraded to `capybara 3.39.1` which solves that argument error. This is intermittent crashes in chrome after upgrading to `selenium-driver 4.9.1`.

**Comment by titusfortner** [comment]
Oh, yes, triaging too quickly.

**Comment by titusfortner** [comment]
But. We need to be able to reproduce it to troubleshoot. Intermittent issues make it hard.

You can set the log level to debug to get more info.
Are you using the new or the old headless mode?
Does it happen in chrome 112?

**Comment by ngan** [comment]
Some more information. We downgraded to `4.9.0` and are still experiencing the issue. We just downgraded to `4.8.6` and will report back.

> You can set the log level to debug to get more info.

Will give this a try

> Are you using the new or the old headless mode?

Hm, how can I tell? Can you point me to docs 😄 

> Does it happen in chrome 112?

Yes, I tried downgrading chrome and chromedriver to 112 and still see the crash.

**Comment by titusfortner** [comment]
So it isn't just that you upgraded to 4.9.1... Any idea what else might have changed?

Was typing on my phone before; this is what turns on all the logging:
```
Selenium::WebDriver.logger.level = :debug
```
There are two headless modes now - https://www.selenium.dev/blog/2023/headless-is-going-away/

**Comment by titusfortner** [comment]
Hmm, and you're using headless gem, not headless mode, so that isn't in common. :-/ 
I don't see how this can be caused by Selenium and not an issue with Chrome, but if you find a signal that we can use to troubleshoot, let us know.

**Comment by ngan** [comment]
Hi there. Just an update. We found out the Os was killing chrome due to memory issues.

**Comment by brucruz** [comment]
> Hi there. Just an update. We found out the Os was killing chrome due to memory issues.

How did you discover that was the issue? And how did you fix it? Just upgraded the OS?

**Comment by adis-io** [comment]
> How did you discover that was the issue? And how did you fix it? Just upgraded the OS?

+1

PS We are using docker

**Comment by titusfortner** [comment]
There is a bug that was fixed in 117 that causes this error, so it might be that.

**Comment by ngan** [comment]
@titusfortner would you happen to have the link to that bug?

**Comment by ngan** [comment]
> How did you discover that was the issue? And how did you fix it? Just upgraded the OS?

We haven't done anything to fix the issue. Although, I've been seeing less occurrences. 🤷 I think there might have been something else running on the host that was memory intensive that we eventually moved off.

**Comment by titusfortner** [comment]
I lied, I mixed up another bug fix with this one. Ignore me.
