### ISSUE TITLE
[🐛 Bug]: INFO: Applicable driver not found; attempting to install with Selenium Manager (Beta

### ISSUE THREAD

**Issue by fayeniz211** [SeleniumHQ/selenium#12097]
### What happened?

Hello,

I am a beginner in software testing and I just observed a somewhat change in pattern in my test result after attempting to invoke a browser. Even though the chrome browser was successfully opened, yet I had like to know the meaning of the following line in the result; Applicable driver not found; attempting to install with Selenium Manager (Beta).

What might have caused this to happen and is it going to have an impact on my project as I progress further?

NB: I have the latest stable release of Selenium driver and my chromdriver is compatible with my updated chrome browser.

Thanks

### How can we reproduce the issue?

```shell
WebDriver driver=new ChromeDriver();
```

### Relevant log output

```shell
May 26, 2023 8:10:08 AM org.openqa.selenium.manager.SeleniumManager getDriverPath
INFO: Applicable driver not found; attempting to install with Selenium Manager (Beta)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912}) on port 44472
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

### Operating System

Windows 10

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

113.0.5672.127

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
You see that because Selenium sees you need a compatible browser driver version. 

This describes your situation https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/#use-the-latest-version-of-selenium

More info about Selenium Manager https://www.selenium.dev/documentation/selenium_manager/

**Comment by fayeniz211** [comment]
> compatible browser driver version.

I have an updated and compatible browser driver version. That as captured in my earlier response

**Comment by diemol** [comment]
Selenium tries to find the browser driver, but when it is not possible to find it, fallback to Selenium Manager, which is why you see that message.

If you have more questions, please join our Slack or IRC channel.

**Comment by fayeniz211** [comment]
> Selenium tries to find the browser driver, but when it is not possible to find it, fallback to Selenium Manager, which is why you see that message.
> 
> If you have more questions, please join our Slack or IRC channel.

Thank you
