### ISSUE TITLE
Switching Windows using Edge and Remote

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1210]
For switching windows, [JSON Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidwindow) requires a 'name' parameter, but [w3c protocol](http://www.w3.org/TR/webdriver/#switch-to-window) requires a 'handle' parameter. 

The Ruby bindings are using 'handle' for Microsoft Edge and it works when running locally, but the Remote WebDriver is only accepting 'name.'

I can add another conditional to the Ruby code, but I think the server should be accepting 'handle' here.

**Comment by InstyleVII** [comment]
As of our November update we should support switching to handle by either Name or Handle. Either way you must use the window handle though. We are working on adding support for window name.
