### ISSUE TITLE
unable to get saucelabs chrome browser DevTools when executing the code from Local[🐛 Bug]: 

### ISSUE THREAD

**Issue by TarunSandupatla** [SeleniumHQ/selenium#12101]
### What happened?

I'm unable to Execute or get saucelabs chrome browser devtools, but the same code works well when I execute if with local webdriver (instead of RemoteWebDriver)- I've already went through "https://github.com/SeleniumHQ/selenium/issues/9803" but the solutions did not work for sauce labs Remote webdriver. Please find the code below:

driver = new RemoteWebDriver(new URL(HTML.properties.getProperty("RemoteURL")), options);
Augmenter augmenter=new Augmenter();
driver=augmenter.augment(driver);
DevTools devTools=((HasDevTools)driver).getDevTools();
devTools.createSession();
                driver=augmenter.
                        addDriverAugmentation("chrome",HasAuthentication.class,(caps,exec)->(whenThisMatches,useTheseCredentials)->devTools.getDomains().network().addAuthHandler(whenThisMatches,useTheseCredentials)).augment(driver);
                        
 As on I execute "driver=augmenter.augment(driver);" I get below error but test does not fail.
 And, as on I execute next line " DevTools devTools=((HasDevTools)driver).getDevTools();" - test fails without any error message.

**Error Message when i execute driver=augmenter.augment(driver):**
 May26, 2023 10:47:44 PM org.openqa.selenium.devtools.CdpEndpointFinder getCdpEndPoint WARNING: Unable to connect to determine websocket url: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:

**More details:**
 Tried executing with both Java version: 11 and 17.
Selenium version: 4.8.3,
 Remote server: saucelabs

Kindly help with solution.

Thanks in Advance.

### How can we reproduce the issue?

```shell
I'm sure if you use above code snippet and try to get the devtools from saucelabs chrome browser you would be able to reproduce the issue.
```

### Relevant log output

```shell
May26, 2023 10:47:44 PM org.openqa.selenium.devtools.CdpEndpointFinder getCdpEndPoint WARNING: Unable to connect to determine websocket url: java.net.ConnectException: Connection refused: no further information: localhost/0:0:0:0:
```

### Operating System

windows10

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

chrome 113

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 

### Are you using Selenium Grid?

NO

**Comment by titusfortner** [comment]
Sauce Labs does not provide access to websockets from their network, so DevTools is not supported, yet.
