### ISSUE TITLE
[🐛 Bug]: IEDriverServer opens internet explorer instead of Edge on Windows Server 2016

### ISSUE THREAD

**Issue by olbapgv** [SeleniumHQ/selenium#12119]
### What happened?

I am trying to access a page that requires IE5 to function. When I am using a windows laptop, I can access it by using the IEDriverServer and a script like the one below. However, I have to do it in windows server 2016, where selenium works well, but it seems like the IEDriverServer does not manage to find Edge (it always opens internet explorer, which cannot be used since it cannot run scripts)

Is there a way to indicate the IEDriverServer where to find msedge? Or is there anything that I may be missing?

Thank you in advance!

### How can we reproduce the issue?

```shell
import selenium
from selenium import webdriver

options = webdriver.IeOptions()
options.ignore_zoom_level = True
options.ensure_clean_session = True
options.require_window_focus = True

service = webdriver.edge.service.Service( r'C:\Users\user\Downloads\IEDriverServer_Win32_4.8.1\IEDriverServer.exe' )
driver = webdriver.Edge( options = options, service=service  )
```

### Relevant log output

```shell
I was not able to find any relevant log for the webdriverserver. I will update this once I find it.
```

### Operating System

Windows Server 2016

### Selenium version

Python - 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Edge 113.0.1774.57 (on compatibility mode)

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer 4.8.1.0

**Comment by titusfortner** [comment]
For IE, even in Edge mode, everything is still IE Classes.

You need to pass 2 flags to IE Options:
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/ie/options.py#L284
and
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/ie/options.py#L298

Then you use `ie.WebDriver` class, not edge

You also shouldn't need to specify the Service class because Selenium 4.9 should download the right IE Driver if it doesn't find it already on the machine.

**Comment by olbapgv** [comment]
Hi Titus!

Whilst it opens the site, no scripts can be run nor can I inspect elements (this happens across two computers and the server).
Is there any way to sort that out?

**Comment by olbapgv** [comment]
> For IE, even in Edge mode, everything is still IE Classes.
> 
> You need to pass 2 flags to IE Options: https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/ie/options.py#L284 and https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/ie/options.py#L298
> 
> Then you use `ie.WebDriver` class, not edge
> 
> You also shouldn't need to specify the Service class because Selenium 4.9 should download the right IE Driver if it doesn't find it already on the machine.

Hi Titus!
This would not work, since it does not allow me to run scripts nor inspect elements. Is there any other way around?
The current snippet works perfectly as long as it is not bein run from the server

**Comment by titusfortner** [comment]
You are not passing the correct arguments to the right classes. If you have it working it's only because you are tricking the wrong classes into having the same state as the right classes. You should get the right behavior using the right classes. Why would you be prevented from running JavaScript?

(Note that the capabilities parameter has been deprecated for years and is finally going away in the next release).

**Comment by olbapgv** [comment]
> You are not passing the correct arguments to the right classes. If you have it working it's only because you are tricking the wrong classes into having the same state as the right classes. You should get the right behavior using the right classes. Why would you be prevented from running JavaScript?
> 
> (Note that the capabilities parameter has been deprecated for years and is finally going away in the next release).

Hi Titus!
I understand. The updated script would then be the following

```
import selenium
from selenium import webdriver

options = webdriver.IeOptions()
options.attach_to_edge_chrome = True
options.ignore_protected_mode_settings = True 

options.edge_executable_path = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
browser = webdriver.Ie( options = options )

browser.get('https://google.com/') # Kernel seems to freeze here
```

Before the issue with the scripts (some buttons stop working when moving the browser manually), I noticed that the process seems to get frozen when loading any website

**Comment by titusfortner** [comment]
That sounds like it could be an issue with protected mode settings. Can you make sure everything is set to the same? 

Here's some info on IE Configuration - https://www.selenium.dev/documentation/ie_driver_server/#required-configuration

And for what it is worth, IE Mode isn't guaranteed to work for sites that require IE < 10; We've removed quite a few conditionals from IE Driver that related to outdated and unsupported versions.

**Comment by olbapgv** [comment]
> That sounds like it could be an issue with protected mode settings. Can you make sure everything is set to the same?
> 
> Here's some info on IE Configuration - https://www.selenium.dev/documentation/ie_driver_server/#required-configuration
> 
> And for what it is worth, IE Mode isn't guaranteed to work for sites that require IE < 10; We've removed quite a few conditionals from IE Driver that related to outdated and unsupported versions.

Indeed, they were protection, permissions and active scripting related problems.
I had to open regedit and modify some values. But it is all good now

Thank you Titus!
