### ISSUE TITLE
[🚀 Feature]: Custom timeout message

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#12111]
### Feature and motivation

I'm using FluentWait class and in some cases want to provide a custom message to attach to a report. For now it's hardcoded in the `public <V> V until(Function<? super T, V> isTrue)` method:

```
String timeoutMessage = String.format(
    "Expected condition failed: %s (tried for %d second(s) with %d milliseconds interval)",
    message == null ? "waiting for " + isTrue : message,
    timeout.getSeconds(), interval.toMillis());
```

It's possible to override the `protected RuntimeException timeoutException(String message, Throwable lastException)` method, but this results in the need to provide full messages in each case the until  method is used.

It would be great to be able to customize the message template.

### Usage example

The simplest example that satisfies the request:

```
String messageTemplate = "%s is not loaded";

FluentWait<WebDriver> wait = new FluentWait<>(driver)
    .withMessageTemplate(messageTemplate);
```

```
String message = "Login page";

wait.withMessage(message).until(...
```

**Comment by titusfortner** [comment]
We are not currently working on features in support class code.
