### ISSUE TITLE
[🐛 Bug]: Issue with Grid with latest Selenium server and --selenium-manager true

### ISSUE THREAD

**Issue by pranesh517** [SeleniumHQ/selenium#12112]
### What happened?

I started a grid with Selenium server 4.9.1 and added extra parameter --selenium-manager true.
Provided only 2 capabilities - Platform name and browser name.

When tried to execute the test case via remote driver, I could see only Queues are getting pilled up. And then failing with http.status_code": 500

Syntax used to up grid  ```java -jar selenium-server-4.9.1.jar standalone --selenium-manager true```

### How can we reproduce the issue?

```shell
1. Up the grid with selenium 4.9.1 and selenium manager as true using java -jar selenium-server-4.9.1.jar standalone --selenium-manager true
2. Execute any testNG test setting remote web driver with 2 capabilities - Platform and Browser
```

### Relevant log output

```shell
09:59:43.863 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "ea513050ab5e00bb857b4df367720577","eventTime": 1685420983817018200,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "264","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession","http.user_agent": "selenium\u002f4.9.1 (java windows)"}}
```

### Operating System

Windows 10

### Selenium version

Java 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

All browsers

### Are you using Selenium Grid?

4.9.1

**Comment by krmahadevan** [comment]
@pranesh517 - Please share the sample test that you are trying to run against the standalone server (You are NOT running the Grid, but just running the selenium standalone server)

**Comment by pranesh517** [comment]
That is correct, it's a Standalone server. Tried with setting distributed hub and node as well. Facing same issue there. Can not share test code as its not public. But you can try with any UI test with testNG.

**Comment by krmahadevan** [comment]
@pranesh517 

> Facing same issue there. Can not share test code as its not public. But you can try with any UI test with testNG.

Wouldnt you be able to even create a sample that runs against a public website? It is absolutely important that we get to see what exactly does your webdriver instantiation code look like (so that we understand the URL, capabilities etc., that you are using). 

> But you can try with any UI test with testNG.

That would defeat the purpose of requesting for a reproducible test.

**Comment by pranesh517** [comment]
@krmahadevan here is the example

```
@Test
    public void TC01() throws MalformedURLException {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.WINDOWS);
        desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, Browser.CHROME);

        WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444"), desiredCapabilities);
        driver.get("https://www.selenium.dev/documentation/grid/getting_started/");
        driver.manage().window().maximize();

        driver.quit();
    }
```

**Comment by krmahadevan** [comment]
@pranesh517 

Can you please update your test and try with 

```java
desiredCapabilities.setCapability(CapabilityType.PLATFORM_NAME, Platform.WINDOWS.name());
desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, Browser.CHROME.browserName());
```

I was able to run the test on a mac (without the platform ofcourse) with the above changes.

**Comment by pranesh517** [comment]
Yes working with this for me as well. Do we always need to use .name() and .browserName()?

**Comment by krmahadevan** [comment]
@pranesh517 - I think so bcoz these are enums and not string constants. Do u remember getting this to work in Selenium 3.x series ? I dont remember using the enums directly in the capabilities (I think earlier it was a string constant).

**Comment by pranesh517** [comment]
Thank you @krmahadevan
