### ISSUE TITLE
selenium ide 记录的按钮不能实现点击

### ISSUE THREAD

**Issue by weitaifu** [SeleniumHQ/selenium#12110]
### What happened?

点击https://www.zxx.edu.cn/syncClassroom/classActivity?activityId=5e93ebf7-a955-49d6-9d52-2533f03ee528的播放按钮不能实现点击播放。css=.vjs-big-play-button > .vjs-icon-placeholder，不行。css=.vjs-big-play-button > .vjs-control-text也不行，不会播放。在我这个外行看来，可能的原因是页面代码<span aria-hidden="true" class="vjs-icon-placeholder"></span>后面有::before。但是在selenium ide运行期间可以真实地由人点击生效，才播放。

### How can we reproduce the issue?

```shell
导出JavaScript mocha时，不知道selenium ide存储的路径。所以我无法贴出代码。
```

### Relevant log output

```shell
Trying to find xpath=//div[2]/div[2]/div/div/div/div[2]/div[2]/div... Failed:
15:44:38
Implicit Wait timed out after 30000ms
'课程教学' ended with 1 error(s)
```

### Operating System

Windows10

### Selenium version

4.5.0

### What are the browser(s) and version(s) where you see this issue?

edge 113.0.1774.57 

### What are the browser driver(s) and version(s) where you see this issue?

edgefriver.exe 113.0.1774.50

**Comment by diemol** [comment]
Please create the issue in the IDE repository https://github.com/SeleniumHQ/selenium-ide
