### ISSUE TITLE
[🐛 Bug]: selenium-remote-driver contains misconfigured io.netty:netty-transport-native-kqueue dependency

### ISSUE THREAD

**Issue by dgulen** [SeleniumHQ/selenium#12128]
### What happened?

`selenium-remote-driver `contains misconfigured `io.netty:netty-transport-native-kqueue` dependency. It is defined with an invalid scope of osx-x86_64 (which is a valid classifier value, not a scope).

To reproduce this, you can add this dependency to any kind of pom and run `mvn dependency:tree `you will get `io.netty:netty-transport-native-kqueue:jar:4.1.89.Final:osx-x86_64`

```

<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-remote-driver</artifactId>
  <version>4.9.1</version>
</dependency>
```
I detected the problem with version 4.5.3 but it is also visible in the latest version 4.9.1

`selenium-remote-driver-4.9.1.pom` contains the following dependencies where **scope** contains a **classifier** value (invalid scope). 
```

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>4.1.91.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>4.1.91.Final</version>
            <scope>osx-aarch_64</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>4.1.91.Final</version>
            <scope>osx-x86_64</scope>
        </dependency>
```

### How can we reproduce the issue?

```shell
To reproduce this, you can add this dependency to any kind of pom

<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-remote-driver</artifactId>
  <version>4.9.1</version>
</dependency>

run mvn dependency:tree
```

### Relevant log output

```shell
io.netty:netty-transport-native-kqueue:jar:4.1.89.Final:osx-x86_64
```

### Operating System

windows, linux

### Selenium version

4.1.91.Final

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by joerg1985** [comment]
@dgulen These dependencies have been removed, i think this issue is outdated now.
