### ISSUE TITLE
[🐛 Bug]: selenium grid Message:Timed out waiting driver server to start

### ISSUE THREAD

**Issue by JackieShangJie** [SeleniumHQ/selenium#12120]
### What happened?

selenium-server-standalone 3.1.41.59
jdk 1.8.0_181
1、selenium grid 1 hub 100 nodes , 8000 cases total  , use 100 threads for test
8000case, pass 85%; 
 500 about occurs selenium.common.exceptions.WebDriverException:Message:Timed out waiting driver server to start
2、check 26 windows servers cpu and memory is health

### How can we reproduce the issue?

```shell
can you give some idea how to check solve
```

### Relevant log output

```shell
only have pictures
```

### Operating System

Windows10

### Selenium version

3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 85.0.4183.102

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDrver 85

### Are you using Selenium Grid?

3.1.41.59

**Comment by diemol** [comment]
We only support the most recent version. Please use the links to join out chat and ask questions about older versions.

**Comment by JackieShangJie** [comment]
> We only support the most recent version. Please use the links to join out chat and ask questions about older versions.

okay thank you for reply
