### ISSUE TITLE
[🐛 Bug]: get_attribute() changes in webelement.py doesnt work

### ISSUE THREAD

**Issue by JaazopFIN** [SeleniumHQ/selenium#12121]
### What happened?

The problem encountered when I was updating our test system to use latest and stable versions of Selenium, python, robot framework, ubuntu and so on. The problem itself is  at least in the webelement.py in get_attribute method in the Selenium 4.9.1 version. 

Currently the version of the code is (without documentation):
```
def get_attribute(self, name) -> str:
        if getAttribute_js is None:
            _load_js()
        attribute_value = self.parent.execute_script(
            f"/* getAttribute */return ({getAttribute_js}).apply(null, arguments);", self, name
        )
        return attribute_value
```
And before in Selenium version 3.4.3 and Python 2.7 the code was like this:
```
def get_attribute(self, name):
        attributeValue = ''
        if self._w3c:
            attributeValue = self.parent.execute_script(
                "return (%s).apply(null, arguments);" % getAttribute_js,
                self, name)
        else:
            resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
            attributeValue = resp.get('value')
            if attributeValue is not None:
                if name != 'value' and attributeValue.lower() in ('true', 'false'):
                    attributeValue = attributeValue.lower()
        return attributeValue
```
In the older version when we run in Get Value Robot framework keyword it works as intended, you get the value of the element but in the 4.9.1 version of Selenium it doesn't give the value and "TimeoutException: Message: script timeout" happens.
After adjusting the source code (just to test it out) like this:
```
def get_attribute(self, name) -> str:
        if getAttribute_js is None:
            _load_js()
        attribute_value = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name}).get('value')
        return attribute_value
```
Then the Get Value Robot Framework keyword works with the Selenium 4.9.1 and I get the value of the element. 

### How can we reproduce the issue?

This is hard to reproduce because I dont know where this happens other than in our devices WebUI. And I am not in the position to give this information but with Robot Framework it goes something like this:
```shell
Open Browser with chrome to the webUI of the device. We use Docker Standalone Selenium Grid for this also.  
Go to page where is a input field.
Input a value (like 432956346, just normal numbers in this case) and save the new value.
!PROBLEM Happens next!
Get the new value with "Get value" keyword.
TimeoutException: Message: script timeout happens.
```
I tried this with Google.com Search Bar and that works with the 4.9.1 Selenium so I cant say for certain where people could reproduce this but I would assume that the problem occurs with some older websites. Maybe. But the solution for this problem would be to just go back to this version of the code:
https://github.com/SeleniumHQ/selenium/blob/9b3e08b21f1305fc9d3fdf7a0d4940cf67d5aa9f/py/selenium/webdriver/remote/webelement.py#L140-L150

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/test/.local/lib/python3.10/site-packages/SeleniumLibrary/__init__.py", line 517, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/test/.local/lib/python3.10/site-packages/robotlibcore.py", line 122, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/home/test/.local/lib/python3.10/site-packages/SeleniumLibrary/keywords/element.py", line 511, in get_value
    return self.get_element_attribute(locator, "value")
  File "/home/test/.local/lib/python3.10/site-packages/SeleniumLibrary/keywords/element.py", line 410, in get_element_attribute
    return self.find_element(locator).get_attribute(attribute)
  File "/home/test/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 178, in get_attribute
    attribute_value = self.parent.execute_script(
  File "/home/test/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 500, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/home/test/.local/lib/python3.10/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 795, in execute
    result = self._base_execute(driver_command, params)
  File "/home/test/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/test/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: script timeout
  (Session info: chrome=113.0.5672.63)
Stacktrace:
#0 0x55f7f610e133 <unknown>
#1 0x55f7f5e427f0 <unknown>
#2 0x55f7f5eb7e37 <unknown>
#3 0x55f7f5e9ebd2 <unknown>
#4 0x55f7f5eb71c7 <unknown>
#5 0x55f7f5e9e9a3 <unknown>
#6 0x55f7f5e7346a <unknown>
#7 0x55f7f5e7455e <unknown>
#8 0x55f7f60cdcae <unknown>
#9 0x55f7f60d18fe <unknown>
#10 0x55f7f60daf20 <unknown>
#11 0x55f7f60d2923 <unknown>
#12 0x55f7f60a5c0e <unknown>
#13 0x55f7f60f5b08 <unknown>
#14 0x55f7f60f5c97 <unknown>
#15 0x55f7f6106113 <unknown>
#16 0x7f5d2446f609 start_thread
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 113.0.5672.63

### What are the browser driver(s) and version(s) where you see this issue?

113.0.5672.63

### Are you using Selenium Grid?

4.9.1

**Comment by AutomatedTester** [comment]
could you reduce this down to just selenium?  We know that this feature is working from our tests in https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/selenium/webdriver/common/element_attribute_tests.py

**Comment by titusfortner** [comment]
Yeah, this sounds like it might be a Robot issue. @emanlove do you have insight on this?

The background:
In Selenium 3, `get_attribute()` called an endpoint on the driver that executed a complicated script which made a guess about whether the user likely wanted the attribute or the property value. It's a really good approach since most people don't know the difference, and the script is almost always right. But when the webdriver specification was created, there wasn't a definition for "guess what the user probably wants." So now we have 2 specified endpoints, one for property (accessible in Python with `get_property()`) and one for attribute (accessible in Python with `get_dom_attribute()`). To keep the `get_attribute()` method backwards compatible, the client code sends the same script that used to live in the drivers to the execute endpoint.

The key here is that what the driver returns from `Command.GET_ELEMENT_ATTRIBUTE` has changed, so you (and Robot) need to make sure you are calling the right method.

`get_attribute()` the method should do the exact same thing in Selenium 3 & 4
You probably actually want `get_property()`  to get the value of an element, though.

**Comment by emanlove** [comment]
I think Selenium is working as intended. The history of the get_attribute method and its change to using execute_javascript explains why the timeout error is there. I am checking with them to see if perhaps the timeout is coming sooner than expected. In addition we are just getting around to adding in the new get_dom_attribute and get_property methods. I was also noticing that we have a few spots where we are doing something like `element.get_attribute("value")` where we should be doing the newer get_property instead.

**Comment by JaazopFIN** [comment]
As @emanlove mentioned, it seems that this isnt a problem in Selenium. Personally this was the only difference in my old and new system so that is the reason I expected selenium to be the problem and not SeleniumLibrary for Robot Framework. 

I will close this now.
