### ISSUE TITLE
[🐛 Bug]: Invalid locator - GetShadowRoot and By.Xpath

### ISSUE THREAD

**Issue by jrod567** [SeleniumHQ/selenium#12123]
### What happened?

When working with the shadowdom, using the By.XPath locator strategy is throwing an invalid locator unexpectedly.

Using other locators works fine and this is only an issue when working with IWebElement.GetShadowRoot() searchcontext.

### How can we reproduce the issue?

```shell
IWebElement host = _driver.JH_FindElement(By.CssSelector("div[id='someid']"));
ISearchContext shadowRoot = host.GetShadowRoot();
IReadOnlyCollection<IWebElement> results = shadowRoot.FindElements(By.XPath(".//input"));
```

### Relevant log output

```shell
Message: 
OpenQA.Selenium.WebDriverArgumentException : invalid argument: invalid locator
  (Session info: chrome=113.0.5672.127)

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
ShadowRoot.FindElements(By by)
```

### Operating System

Windows 10

### Selenium version

4.8.1, 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome v113.0.5672.127

### What are the browser driver(s) and version(s) where you see this issue?

Latest 

### Are you using Selenium Grid?

Yes, 4.9.1

**Comment by diemol** [comment]
That error comes from Chrome directly, they need to support XPATH as well.

More context https://github.com/SeleniumHQ/selenium/pull/11893. Please raise this with the Chrome/ChromeDriver team.

**Comment by titusfortner** [comment]
Depending on your situation you might try:
```
shadowRoot.FindElement(By.CssSelector("*")).FindElements(By.XPath(".//input"))
```

**Comment by jrod567** [comment]
Thank you!!  Titus - that's helpful, much appreciated!
