### ISSUE TITLE
[🐛 Bug]: Close method in Remotewebdriver is not working

### ISSUE THREAD

**Issue by ShamsMuralidharan** [SeleniumHQ/selenium#12129]
### What happened?

We recently updated the version to 4.8.3 from 4.7.1
In 4.7.1 we are able to close the Android driver by using .Close() method inside remote webdriver class.
But after updating to 4.8.3 we are getting class cast exception while closing the  app with same method..We observed that from 4.8.0 we could see some new lines of code added in Remotewebdriver.java class Close method..It is failing in the line  where we are storing the list of window handles..Please let us know how to resolve this.While gettinge the response {error=Unknown  error,mesage=An unknown server side error occurred while processing the command :Original error:Could not proxy error:Could not proxy command to remot server.Original error  Error: ESOCKETTINEDOUT,stack race=unknown error at  getResponseForW3CError

### How can we reproduce the issue?

```shell
Please try to close the android driver in both 4.7.1 and 4.8.3 versions ..In both 4.7.1 it would work .and in. 4.8.3 it’s not
```

### Relevant log output

```shell
NA
```

### Operating System

Windows

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
What about using 4.9.1?

**Comment by titusfortner** [comment]
Can you send full stack trace?
I'm not looking at the code, but I'm guessing we added code to manage devtools connections or something and didn't take into account appium wouldn't always have window handles or something.

**Comment by diemol** [comment]
I am closing this as we have yet to get more information.
