### ISSUE TITLE
[🐛 Bug]: EDGE fails to launch in IE Mode in Windows 2016 Server

### ISSUE THREAD

**Issue by PraveenThirumoorthy** [SeleniumHQ/selenium#12126]
### What happened?

Am Trying to launch the Edge Browser in IE Compatibility mode . but am unable launch the browser.
In my Windows 2016 Machine i had IE and i have disabled it now . And now i have installed Edge 105 Version in Windows 2016 Machine. Am using Selenium 4. I have followed the coding giving in [Microsoft Website ](https://support.microsoft.com/en-us/microsoft-edge/internet-explorer-mode-in-microsoft-edge-6604162f-e38a-48b2-acd2-682dbac6f0de) but couldn't succeed though

Code used 

### How can we reproduce the issue?

```shell
System.setProperty("webdriver.ie.driver", GlobalSettings.IE_DRIVER_PATH);
        InternetExplorerOptions IEOptionsEdge = setInternetExlopererForEdge();
driver = new InternetExplorerDriver(IEOptionsEdge);

    private static InternetExplorerOptions setInternetExlopererForEdge() 
    {
        InternetExplorerOptions IEOptions  = new InternetExplorerOptions();
        IEOptions.attachToEdgeChrome();
        IEOptions.ignoreZoomSettings();
        IEOptions.withEdgeExecutablePath("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
        return IEOptions;
    }
```

### Relevant log output

```shell
Only local connections are allowed
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070002 ('The system cannot find the file specified.') for URL 'http://localhost:52310/'
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'ABCDEFGHIJ', ip: '12345678', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: internet explorer, se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr...}}], desiredCapabilities=Capabilities {browserName: internet explorer, ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr..., se:ieOptions: {ie.edgechromium: true, ie.edgepath: C:\Program Files (x86)\Micr...}}}]
Capabilities {}
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
```

### Operating System

Windows 2016

### Selenium version

Selenium 4

### What are the browser(s) and version(s) where you see this issue?

Edge

### What are the browser driver(s) and version(s) where you see this issue?

IEDriverServer

### Are you using Selenium Grid?

No

**Comment by PraveenThirumoorthy** [comment]
@titusfortner  your thoughts please

**Comment by diemol** [comment]
What happens when you use the latest versions of Selenium and the IEDriver?

**Comment by titusfortner** [comment]
Or just use the latest version of Selenium, it should download IE Driver for you.

**Comment by PraveenThirumoorthy** [comment]
Thanks @diemol  and @titusfortner  for your inputs. I have downloaded the latest IE Driver 32 bit and it worked now but am facing the error as below and launching the website
![image](https://github.com/SeleniumHQ/selenium/assets/122547514/bb80789a-9924-4a45-b870-d356ee56be71)

**Comment by diemol** [comment]
What's the error?

**Comment by PraveenThirumoorthy** [comment]
Its asking to Reinstall with Admin Previleages.? is it necessary and if so do you know how todo that

**Comment by diemol** [comment]
Not sure, I believe you should check that with the MS Edge folks.
