### ISSUE TITLE
[🚀 Feature]: Addition of a listener for org.openqa.selenium.support.ui.Select

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#12134]
### Feature and motivation

Similarly to `WebDriverListener`, could it be possible to have a listener for `org.openqa.selenium.support.ui.Select` ?

I would like to be able to intercept calls to methods: 
```
Select.selectAll
Select.selectByValue
Select.deselectByIndex
```
etc

### Usage example

```
   WebDriver original = new FirefoxDriver();
   WebDriverListener driverListener = new MyDriverListener();
   SelectListener selectListener = new MySelectListener();
   WebDriver decorated = new EventFiringDecorator(driverListener, selectListener).decorate(original);

   decorated.get("http://randompage.com/");
   Select sel = new Select(driver.findElement(By.id("randomID")));
   sel.selectByValue("randdomValue");
```

**Comment by titusfortner** [comment]
Essentially we're not actively maintaining the classes in the support module right now, and we're trying to decide our long term plans for them. Likely they will be moved and/or packaged separately.

You can create your own Custom Decorator that does whatever you want.
I created an example here - https://github.com/titusfortner/selenium-deep-dive/blob/seconf2023_final/src/test/java/com/titusfortner/deep_dive/decorators/CustomDecorator.java

Or... I *think you could have your `SelectListener` interface extend the `WebDriverListener` interface and you could still pass it in to `EventFiringDecorator` and it would still check the class for the applicable method. It's all reflection so it gets very non-static.

If you get something working, feel free to post back here with what you've done. I'm always interested to see how people are using these things in the real world.
