### ISSUE TITLE
Selenium Manager ca be even more friendly with single file publish or native AOT compilation in .Net

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#12140]
### Feature and motivation

Our consumers utilizes selenium nuget package in theirs applications Theirs application may be published as single file: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

Our package can be more friendly for this cases of usage.

### Usage example

Please check the link above.

**Comment by nvborisenko** [comment]
This feature request (or even bug?) is a continuation of #12045

**Comment by titusfortner** [comment]
I'm not following what this would do. You're suggesting generating Selenium itself as an executable?

**Comment by nvborisenko** [comment]
In .net there is possibility to publish user's project as single file. In this case selenium manager binaries will be missed in user's output. This is because specifics of nuget packages. We can address these cases, and put selenium manager binaries to user's output even if user:
- publich his project as a single file
- publish his project as native compiled

We have to options here:
- Easy: just copy all SM binaries to user's output despite a platform (win, unix) user is targeting
- Hard: determine a target platform (win, macos), and copy necessary SM binary

**Comment by diemol** [comment]
Did the merged fix the issue? Could we close this?

**Comment by nvborisenko** [comment]
I even think we will not do it, nobody will come to us with issue because it's not issue. This is just an enhancement. I even don't mind to close it without any action.

**Comment by diemol** [comment]
If I understand correctly, we can close this. But if you still think something is missing, let us work on it.
