### ISSUE TITLE
[🐛 Bug]: sendKeys() removing special characteres 

### ISSUE THREAD

**Issue by Correia87** [SeleniumHQ/selenium#12143]
### What happened?

Hi everyone,

I'm facing an issue while using Selenium with Java 11 and Unix system and Chrome version 110. When I send a special character '/', it seems to remove the forward slash. 
When a try in my local machine with the same keyboard than Unix System but with Chrome version 114 and Windows, that don't happens.
I've tried various approaches to handle this situation, including escaping the character and using different encoding methods, but none of them seem to work. The forward slash is essential for my application's functionality, so I need to find a solution.

Has anyone encountered a similar problem or have any suggestions on how to resolve this issue? Any help or insights would be greatly appreciated.

Thank you in advance!

### How can we reproduce the issue?

```shell
public static void fillInput(WebDriver driver, By inputSelector, String textToInput) {
		WebElement inputElement = driver.findElement(inputSelector);
		inputElement.sendKeys(textToInput);

		CommonWaiters.waitForDocumentToBeReady(driver);
	}
In unix System with Chrome driver 110.
```

### Relevant log output

```shell
This LosAngeles/USA will apears LosAngelesUSA
```

### Operating System

Unix

### Selenium version

4.8.0

### What are the browser(s) and version(s) where you see this issue?

Chorme 110

### What are the browser driver(s) and version(s) where you see this issue?

110.0.5481.77

**Comment by diemol** [comment]
Also, what happens when you use Firefox?

**Comment by Correia87** [comment]
> Also, what happens when you use Firefox?

Sorry, i forgot to mention that.. with Firefox i don't have problems, only with Chrome .
