### ISSUE TITLE
[🐛 Bug]: Chrome devtools is not connected when screenshot

### ISSUE THREAD

**Issue by pgi-jsanchez** [SeleniumHQ/selenium#12155]
### What happened?

I tried the demo code published in the https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/#override-device-mode but does not connect to the devtools,  I tried to debug anything that I could find, updated chrome version and installed the most recent version of chromedriver. 

There's something missing in the documentation or a chromium bug related to this? I couldn't find any.

Thanks.

### How can we reproduce the issue?

```shell
import logging
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)


options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
# options.add_argument("--headless=new")
#options.add_argument("window-size=1920,1080")
options.add_argument("--remote-debugging-port=9222")

# 1. create a web driver instance

service = Service(r"/usr/bin/chromedriver")
driver = webdriver.Chrome(options=options, service=service)

set_device_metrics_override = dict({
  "width": 375,
  "height": 812,
  "deviceScaleFactor": 50,
  "mobile": True
  })
driver.execute_cdp_cmd('Emulation.setDeviceMetricsOverride', set_device_metrics_override)
driver.get("https://google.com")
driver.save_screenshot("google-dev-save.png")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "devtools.py", line 35, in <module>
    driver.save_screenshot("google-dev-save.png")
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 917, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 893, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 927, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode("ascii"))
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 938, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/jsanchez/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
```

### Operating System

Ubuntu

### Selenium version

Python Selenium release 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Versión 114.0.5735.90 (Build oficial) (64 bits)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})

**Comment by titusfortner** [comment]
Few things here:
1. You don't need devtools for Mobile Emulation in Chrome; Chromedriver has you covered: https://chromedriver.chromium.org/mobile-emulation
2. `execute_cdp_cmd()` is just sending the class name and a map to the driver endpoint, which Selenium doesn't have any control over
3. The improved way to do this is with async; I think like this...

```
    async with driver.bidi_connection() as session:
        cdpSession = session.session
        await cdpSession.execute(
            devtools.emulation.set_device_metrics_override(
                "width": 375,  "height": 812,  "deviceScaleFactor": 50,  "mobile": True
            )
        )
```
You'll need to import this based on the version of Chrome:
```
import selenium.webdriver.common.devtools.v113 as devtools
```

**Comment by pgi-jsanchez** [comment]
@titusfortner Thanks for the reply.

Your response give me some hints to deal with that. 

1. i tried mobile emulation but that tides the driver to that mobile settings, and I want to change the resolution dynamically using the device toggle with the specific configurations as documented in https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/#override-device-mode
2. The code that you posted works but requires certain adjustmests and resizes the window as expected, heres the code that I tested: 

```
import trio

async def async_driver_cdp():
  async with driver.bidi_connection() as session:
    cdpSession = session.session
    await cdpSession.execute( devtools.emulation.set_device_metrics_override( width=375, height=812, device_scale_factor=50,  mobile=True ) )


driver.get("https://google.com")
trio.run( async_driver_cdp )
```

Now, demos that I saw certain videos written with Java, allows to send the "driver.get" after the metrics_override call and keep the overide setup, but on python if I do that, the settings are cleared, unable me to load the site with certain responsive design style and functionality. Is this an expected behavior?
3. Considering that your solution is different from the documentation, should change to include a demo similar of the code that you propose?

**Comment by titusfortner** [comment]
So, devtools is weird. The CDP endpoint was the first implementation, so there are still a bunch of examples out there with it. 

Generating the classes every release, tied to the specific version of Chrome is the current implementation, but it is not our long term plan.
We are implementing the new webdriver bidi specification that is still being developed. So, yes, would be good to update the docs, but it's also a lot of work for something that is going away soonish.

Also, if you'd like to make a PR to update the code, it certainly would be appreciated.

**Comment by diemol** [comment]
I am closing this as there is nothing for us to work on here based on the comments above.
