### ISSUE TITLE
selenium-webdriver/remote: SeleniumServer.start does not resolve

### ISSUE THREAD

**Issue by hankduan** [SeleniumHQ/selenium#1215]
SeleniumServer.start returns a promise that does not resolve if no option is provided to the `start` function. See below:

```javascript
var SeleniumServer = require('selenium-webdriver/remote').SeleniumServer;
var pathToSeleniumJar = '/workspace/protractor/selenium/selenium-server-standalone-2.48.2.jar';

var options = undefined;
// Uncomment the following and the test will work fine. 
// var options = {
//   port: 4444
// }
var server = new SeleniumServer(pathToSeleniumJar, options);

server.start().then(function(url) {
  console.log('Never reached');
});
```

**Comment by jleyba** [comment]
Mind building from source?  I'd like to hold off publishing 2.48.2 in case there are other issues.

**Comment by hankduan** [comment]
Yup, no problem. Thanks for the quick fix!

**Comment by hankduan** [comment]
@jleyba I just applied this commit to Protractor, and I don't see any issues as far as Protractor (at least right now). Do you know when this would go out into a release?

**Comment by jleyba** [comment]
Just pushed 2.48.2 to npm

**Comment by hankduan** [comment]
cool, thanks!
