### ISSUE TITLE
[🐛 Bug]: Selenium sdist does not contain LICENSE

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [SeleniumHQ/selenium#12166]
### What happened?

This was fixed previously, in https://github.com/SeleniumHQ/selenium/issues/6246 , however it has re-appeared. The 4.9.1 tarball on pypi does not contain a LICENSE file.

### How can we reproduce the issue?

```shell
tar ztf selenium-4.9.1.tar.gz | grep -i license
```

### Relevant log output

```shell
There are no logs.
```

### Operating System

openSUSE

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Not relevant

### What are the browser driver(s) and version(s) where you see this issue?

Not relevant

**Comment by symonk** [comment]
Thanks for reporting, i'll get it fixed, confirmed no license info in any pypi published artifacts
