### ISSUE TITLE
[🐛 Bug]: Sec-Ch-UA and Sec-Ch-Ua-Platform Headers are empty after passing User-Agent as browser option

### ISSUE THREAD

**Issue by Tzachc** [SeleniumHQ/selenium#12162]
### What happened?

Hello,
Using windows 10.
Selenium dotnet client.
Selenium 4.9.1.
The issue started with Chrome and Edge 114 versions.

Since the last versions of Chrome and Edge 114, when I pass User-Agent as Options on start browser, we noticed that Sec-Ch-Ua and Sec-Ch-Ua-Platforms Requests Headers are being empty.

On chrome/edge version 114:
![image](https://github.com/SeleniumHQ/selenium/assets/57837594/58a80ea3-fbe7-47ec-a061-a9f7c3eec448)

On previous versions: 

![image](https://github.com/SeleniumHQ/selenium/assets/57837594/f76d31b7-b316-4256-81db-a6c354b114cf)

We also noticed this issue opened on chromium, do you think it's also related?
https://bugs.chromium.org/p/chromium/issues/detail?id=1443649&q=User-Agent&can=2

### How can we reproduce the issue?

```shell
Pass User-Agent to Chrome/Edge browser as Options.
Check network request headers.
```

### Relevant log output

```shell
Sec-Ch-Ua:
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
X-Xsrf-Token:
ae47fvfeD_-V2Bej_Za00ToxNjg2MDYyNzY
```

### Operating System

Windows 10

### Selenium version

Selenium 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 114, Edge 114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113 & MSEdgeDriver 113

**Comment by titusfortner** [comment]
We need to know the exact code to run to see the behavior you do.

**Comment by diemol** [comment]
But if it happens after a Chrome/Edge update, shouldn't it be reported to those teams?

**Comment by titusfortner** [comment]
I thought maybe they weren't doing it the supported way, and getting more info we could see what is supposed to work.

**Comment by Dor-bl** [comment]
@Tzachc already asked if you think this issue seems relevant.

`We also noticed this issue opened on chromium, do you think it's also related?`
https://bugs.chromium.org/p/chromium/issues/detail?id=1443649&q=User-Agent&can=2

**Comment by diemol** [comment]
The linked bug talks about Headless. I would create a new one in their bug tracking list and let them decide if it is the same bug.
