### ISSUE TITLE
[🚀 Feature]: Manually invoke Selenium Manager to pre-install webdriver binary in Dockerfile

### ISSUE THREAD

**Issue by calebplum** [SeleniumHQ/selenium#12168]
### Feature and motivation

I need to build a custom docker image to run some Python Selenium tests in. I'd like to pre-install the webdriver from inside the Dockerfile to reduce resource consumption at runtime.

With the latest version of Selenium, the easiest way to download the webdriver is to let Selenium handle it via Selenium Manager. However, my understanding is that Selenium Manager is only invoked when a webdriver session is spawned, for example with `driver = webdriver.Chrome()`.

Is there any way to invoke Selenium Manager manually and instruct it to download the corresponding webdriver binary without spawning an instance of the webdriver? In my case this would be performed in my Dockerfile so any method using either Linux shell commands or Python would be suitable.

### Usage example

A solution involving either shell command or Python code to download the webdriver binary without actually instantiating the webdriver.

**Comment by titusfortner** [comment]
Right now it would run the first time you created a driver, then use the cached versions for everything after that.

Getting this sorted as part of docker setup is a use case we've talked about. If we release Selenium Manager as a standalone artifact it won't be until we have a stable 1.0 release.

Python code that will work without creating a session:

```python
webdriver.common.driver_finder.DriverFinder.get_path(
        webdriver.chrome.service.Service(),
        webdriver.chrome.options.Options()
)
```

**Comment by titusfortner** [comment]
This is possible now and will be more straightforward with #13022 so no need to track this explicitly here.
