### ISSUE TITLE
[🐛 Bug]: Selenium Manager should not remediate issues with Drivers on PATH

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12177]
### What happened?

I think so long as we're in beta we want to keep existing behavior when users have drivers on PATH, and just warn them things might fail and why. 

Users can choose to run old versions of a driver with `ignoreBuildCheck()`. If we are going to auto-remediate we'll want to check for that value.

The value add here is that the bindings no longer need to manage looking for things on PATH (huge win), and users will get more insight in the console into why things aren't working.

#### Old Driver on PATH with internet

* Currently without SM: Use driver on PATH (which will error unless ignoreBuildCheck set)
* Currently with SM: Log warning about old driver on PATH, then download and use updated driver
* Selenium 4.11 : Log warning about old driver on PATH and use it (which will error unless ignoreBuildCheck set)

We could check if ignoreBuildCheck is set and error if not, but I don't think that's necessary for the next release.

#### Old Driver on PATH without internet

* Currently without SM: Use driver on PATH (which will error unless ignoreBuildCheck set)
* Currently with SM: Errors when it can't connect to url
* Selenium 4.11: Same behavior as with internet

#### Current Driver on PATH without Internet

* Currently without SM: Use driver on PATH (which works)
* Currently with SM: Errors when it can't connect to url
* Selenium 4.11: Use driver on PATH

#### Current Driver on PATH with internet but invalid proxy

* Currently without SM: Use driver on PATH (which works)
* Currently with SM: Errors when it can't connect to url via proxy
* Selenium 4.11: Use driver on PATH

Logs for each of these scenarios found here — https://gist.github.com/titusfortner/4dadee2f185af4b04d14b105d1b92322

**Comment by diemol** [comment]
I tend to think that if the user has something on the PATH, that is what should prevail and Selenium 5 is using Selenium Manager by default, with an env var to disable it disable fetching things from the internet.

**Comment by fenchu** [comment]
Yet another bloat. it is trivial to manage browsers and webdriver and put them into path.

We have the excellent seleniumBase if you like it to automatically download webdrivers for you.

**Comment by diemol** [comment]
@fenchu if it was trivial, people would have not requested it as a feature. 

Also, what is the point of your comment? How would you like to contribute?

**Comment by titusfortner** [comment]
All languages have 3rd party driver managers that each do things differently from each other. Integrating this logic into Selenium allows for common behavior across the project and allows us to more easily debug problems users have. Further, we're going to be able to pull a source complexity out of existing code (finding things on PATH) and allow the Selenium Manager binary to do that for us.

**Comment by diemol** [comment]
On [June 8th, TLC meeting](https://www.selenium.dev/meetings/2023/tlc-06-08/):
  * It was decided that if a user has a browser driver on their PATH, that is what should prevail.
  * However, this behaviour will change with Selenium 5, where Selenium Manager will be used by default.
    * There will be an environment variable to disable Selenium Manager if needed.
    * An environment variable to disable internet access in Selenium Manager.
    * But if there is an old or incompatible browser driver on the PATH, Selenium Manager will fix that.

**Comment by fenchu** [comment]
I do not care as long as it is not intrusive, but yesterday selenium_manager.py corrupted our tests because it forced downloaded an older chromedriver. I only have a service object because we need to set log_path.

before it I had never heard of it. There are lots of modules out there that solves this, and google has a api that match browser and chromedriver for canary to prod

**Comment by diemol** [comment]
Can you share the issue link to verify what you are saying? Also, feel free to drop by our chat so we can understand better what you are describing https://www.selenium.dev/support/

**Comment by titusfortner** [comment]
Ah, yes selenium manager does not yet support canary builds. When we update to using the new testing releases it will be easier. 

But, selenium manager only gets used if your tests would otherwise fail, which means selenium did not find the driver you installed yourself.
