### ISSUE TITLE
[🐛 Bug]: extendedDebugging option no longer works in 4.10.0.

### ISSUE THREAD

**Issue by markp2** [SeleniumHQ/selenium#12178]
### What happened?

Just upgraded to  4.10.0 and the option extendedDebugging is invalid:

selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: unrecognized capability: extendedDebugging

### How can we reproduce the issue?

```shell
python 3.10:

options.set_capability('extendedDebugging', True)
```

### Relevant log output

```shell
E       selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: unrecognized capability: extendedDebugging

test/browser.py:95: in setUp
    self.driver = Driver(options=options)
/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:49: in __init__
    super().__init__(
/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:54: in __init__
    super().__init__(
/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute
    self.error_handler.check_response(response)
```

### Operating System

Mac OSX Catalina  10.15.7 (19H2026

### Selenium version

 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Version 114.0.5735.106 (Official Build) (x86_64)

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 114

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
This is not a valid W3C capability. How are you using this? With a cloud vendor?

**Comment by markp2** [comment]
Thankyou for confirming that. I suspect we added this option some time back believing that it was providing some additional debug info, but it may be that it never did anything.
We have removed this from our code - so  feel free to close the issue if you wish.

**Comment by diemol** [comment]
Thank you for letting us know.
