### ISSUE TITLE
[🚀 Feature]: Slow down removal of CDP

### ISSUE THREAD

**Issue by hazendaz** [SeleniumHQ/selenium#12179]
### Feature and motivation

Big firms are slow to update at scale browsers, when CDP is needed such as chrome the removal is far too fast if we want to keep in sync with Selenium.  It would be better if we could keep these a bit longer than the current policy seems here.

### Usage example

Currently we are using 4.9.1 which has support for chrome CDP 111.  With 4.10.0, that is now gone.  So we have to stay on selenium 4.9.1.  I don't off hand see any reason other that aligning with chrome practices.  It would be nice to keep say 2-3 additional ones at a time so wider audience does not get stuck on older versions for longer periods of time.  Things happen and its not always easy for a firm to jump so fast on recent updates but we can on libraries such as this but then cannot do that either.  Some balance would help.

So for my usage and I'm sure many others, we want to be lock step with Selenium updates.  But removal so fast is making it more difficult to do so at speed we want to.  For example, due to appium java already heavy handing a force to 4.10.0, our bots are already flagging us to upgrade this.  We want to but we cannot yet.  Maybe by end of the month.  So keeping the older items around just a bit longer would go a long way.

**Comment by titusfortner** [comment]
We do keep 2 additional ones. We support the current version (114) and the two previous versions (113 & 112). Ruby & Java package the artifacts separately, which allows users to specify older versions. Python, JS & .NET bundle it all together, though. We could do the work to change that, but we'd prefer to work on the long-term solution which is adopting WebDriver-BiDi, which will provide the functionality without the limitations of version management.
