### ISSUE TITLE
[🐛 Bug]: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

### ISSUE THREAD

**Issue by rotorrest** [SeleniumHQ/selenium#12180]
### What happened?

I try to create an object driver
```
driver = uc.Chrome(options=options)
```
using the undetected chrome driver lib

and the error happends

Its fix if the selenium version is selenium = "4.9.1".

### How can we reproduce the issue?

```shell
driver = uc.Chrome(options=options)
```
```


### Relevant log output

```shell
File "/my_folder/myfile.py", line 43, in init_driver
     driver = uc.Chrome(options=options)
   File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 453, in __init__
     super(Chrome, self).__init__(
 TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
```

### Operating System

Linux python:3.10-bullseye

### Selenium version

selenium 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  114.0.5735.90

### What are the browser driver(s) and version(s) where you see this issue?

Chrome  114.0.5735.90

**Comment by diemol** [comment]
Duplicate of #12176 

Probably you need to reach out to that project so they fix that in their code.

**Comment by Darkmoner** [comment]
Helo, i got the same issue, also in Linux Ubuntu

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy


selenium.__version__
'4.10.0'



Python 3.10.6

**Comment by Abdelrahman-Hekal** [comment]
I have faced this issue when upgraded to selenium 4.10, the quick workaround is to downgrade selenium to 4.9

**Comment by diemol** [comment]
@Abdelrahman-Hekal Please note that those arguments were deprecated for over 1.5 years. Downgrading is not ideal as it will make your code harder to migrate.

**Comment by titusfortner** [comment]
It's also worth noting that most people don't even need execute_path any more, now that Selenium manages the drivers.

**Comment by Shah13079** [comment]
same problem, scrapy selenium configuration only for GeckDriver ?
