### ISSUE TITLE
pageLoadTimeout does not work

### ISSUE THREAD

**Issue by arnomonitis** [SeleniumHQ/selenium#1218]
in the site test I'm using this code. 
 
`this.driver.manage().timeouts().pageLoadTimeout(30L, TimeUnit.MILLISECONDS);
this.writer.append("\ntest89732_11490:23 OK " + getRunTime(System.currentTimeMillis() - l1));
l1 = System.currentTimeMillis();`

but test shows more then 88 sec every time, and does not fail. I tried to us `findElement` and even JS code, but the result is the same. Any idea how can it be fixed ?

**Comment by lukeis** [comment]
which browser are you using? not all of them support page load timeout

**Comment by arnomonitis** [comment]
firefox 41, selenium 2.48

**Comment by arno86** [comment]
after some investigation  I found out,  that during the  page load there is a request which waits for a response 42 -43 s, how this can influence on selenium work ?
![load](https://cloud.githubusercontent.com/assets/10438969/11027113/8277944c-86cb-11e5-976a-c8aae3d04c91.png)

**Comment by arnomonitis** [comment]
after some investigation  I found out,  that during the  page load there is a request which waits for a response 42 -43 s, how this can influence on selenium work ?
![load](https://cloud.githubusercontent.com/assets/10438969/11027113/8277944c-86cb-11e5-976a-c8aae3d04c91.png)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
