### ISSUE TITLE
[🐛 Bug]: WebDriver.__init__() got an unexpected keyword argument 'service_log_path'

### ISSUE THREAD

**Issue by Fserver** [SeleniumHQ/selenium#12185]
### What happened?

I am running atomatized tests in RobotFramework and I was doing it without problems until selenium 4.9.1 version
From selenium 4.10 onwards atomatized tests do not run and it generates an error like the following:

WebDriver.__init__() got an unexpected keyword argument 'service_log_path'.

### How can we reproduce the issue?

```shell
you must install the libraries that come with pip install robotframework-seleniumlibrary and try to set up a simple test like opening Google:

*** Settings ***
Library SeleniumLibrary

*** Keywords ***
Open Google
    Open Browser https://www.google.com/ chrome

*** Test Cases ***
Test1
    Open Google
```

### Relevant log output

```shell
WebDriver.__init__() got an unexpected keyword argument 'service_log_path'
```

### Operating System

Windows 10

### Selenium version

Python 3.11.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

**Comment by diemol** [comment]
The cause is the same as #12176, please check the [reply](https://github.com/SeleniumHQ/selenium/issues/12176#issuecomment-1581428934) and reach out to the Robot framework. Thanks!
