### ISSUE TITLE
[🐛 Bug]: selenium_manager.py overides path

### ISSUE THREAD

**Issue by fenchu** [SeleniumHQ/selenium#12196]
### What happened?

As you see both google-chrome and chromedriver are in path, but 
```
 google-chrome --version
Google Chrome 115.0.5790.24 beta

$ chromedriver --version
ChromeDriver 115.0.5790.24 (c608bafd9e2fcf320ad776392c8029dc2d701664-refs/branch-heads/5790@{#432})

$ bash -c -l "cd /test/headless-selenium-test; export WEBDRIVER='chromeheadless'; ./headless-test.py"
20230613120841.771|DEBUG|/test/headless-selenium-test/./headless-test.py:26|WEBDRIVER=chromeheadless
20230613120841.772|DEBUG|/test/headless-selenium-test/./headless-test.py:112|ChromeHeadless -> Chromedriver
20230613120842.769|WARNING|/root/.pyenv/versions/base/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py:125|Error getting version of chromedriver 115. Retrying with chromedriver 114 (attempt 1/5)
20230613120842.769|WARNING|/root/.pyenv/versions/base/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py:125|Incompatible release of chromedriver (version 115.0.5790.24) detected in PATH: /drivers/chromedriver
20230613120843.275|ERROR|/test/headless-selenium-test/./headless-test.py:150|Message: Service /root/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 1
Cleaning up project directory and file based variables
```

Why do this download a older version of chromedriver?

### How can we reproduce the issue?

```shell
my settings:

        elif os.environ['WEBDRIVER'].lower()=='chrome':
            log.debug("Chrome -> Chromedriver")
            options = webdriver.ChromeOptions()
            options.add_argument('--no-sandbox')
            options.add_argument('--disable-gpu')
            options.add_argument('--log-level=3')
            options.add_argument('--default-shm-size=32m')
            options.add_argument('--disable-translate')
            options.add_argument('--disable-extensions')
            #options.add_argument('--incognito')
            options.add_argument("--proxy-server='direct://'")
            options.add_argument("--proxy-bypass-list=*")
            options.set_capability('acceptInsecureCerts', True)
            s = Service(log_path="./chromedriver.log")
            driver = webdriver.Chrome(service=s, options=options)
```
```


### Relevant log output

```shell
selenium==4.10.0

if I test on windows11 with chrome114 and chromedriver114, I just get this output:
`Message: Unable to find a matching set of capabilities`
```

### Operating System

ubuntu 22.04LTS

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 115.0.5790.24 beta

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 115.0.5790.24 (c608bafd9e2fcf320ad776392c8029dc2d701664-refs/branch-heads/5790@{#432})

**Comment by diemol** [comment]
@bonigarcia is this the bug you were talking about?

**Comment by bonigarcia** [comment]
Yes. As discussed in Slack, the Chrome team is doing recently relevant changes related to [Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/) (CfT). In particular, the metadata for discovering [chromedriver](https://chromedriver.chromium.org/downloads) as of version 115 is now different. This means that Selenium Manager needs to be updated to continue supporting chromedriver 115+ downloads. I'll send a fix as soon as possible.

**Comment by fenchu** [comment]
So if I use service this will trigger selenium_manager.py:
```
from selenium.webdriver.chrome.service import Service
s = Service(log_path="./chromedriver.log")
driver = webdriver.Chrome(service=s, options=options)
```
I believed I had to explicitly write:
```
from webdriver_manager.chrome import ChromeDriverManager
s = Service(ChromeDriverManager().install(), log_path=".chromedriver.log") 
```

**Comment by titusfortner** [comment]
Yes, but if there is a chromedriver on PATH, it shouldn't even hit the Selenium Manager logic.
You shouldn't need to specify anything in the service, let me look.

**Comment by titusfortner** [comment]
Yup, I screwed up this logic in the last release. Thank you for reporting it.

**Comment by titusfortner** [comment]
I take it back, I did not.

This code means that Selenium Manager will not be used if `shutil.which('chromedriver')` locates the driver. Unless for some reason it doesn't show as 'chromedriver'?

https://github.com/SeleniumHQ/selenium/blob/selenium-4.10.0/py/selenium/webdriver/common/driver_finder.py#L40-L42

Was that the full output of [turning on logging](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/)? 
```
logging.getLogger('selenium').setLevel(logging.DEBUG)
```

**Comment by titusfortner** [comment]
This should be fixed now. Please open a new ticket if it has not.
