### ISSUE TITLE
[🐛 Bug]: Selenium - VSCode - Java - Chromebook Linux Penguin Virtual Machine: Chromedriver always invalid

### ISSUE THREAD

**Issue by backupmachiavelli** [SeleniumHQ/selenium#12192]
### What happened?

First of all: I don't know if this is a bug. But I have looked everywhere, even in the Selenium Documentation, which says that when the NoSuchDriverException happens, one should file a bug report if the newest version of Selenium is used. Also, neither StackOverflow, the Selenium chat room, nor Google could help me with this one, so I guess this is a bug since I am not an experienced programmer, but an experienced googler.

Some side data:

My Selenium version: [4.10.0 (June 07, 2023)]

My Setup: It is Visual Studio Code installed on a Chromebook by installing it on the default Linux Virtual Machine which comes with the newer versions of ChromeOS. Chrome is installed on the VM. The ChromeOS version of Chrome is 114 and the LinuxVM version of Chrome is 112. I have tried using the externally downloaded Chromedriver in the code with both versions and still both give me this error. For some reason, I have no ability to check the chromedriver version in the terminal because it always gives me the permission denied error. 

Due to the import statements at the beginning failing in VSCode, I had to deactivate the Java Language Support by George Fraser to make it work.

The PATH has also been exported to the externally downloaded chromedriver however it still gives the same error. 

If this isn't a bug (I hardly know Selenium to be fair) but a Layer 8 error or something I would be really thankful if you could explain to me what to do in this case. After hours of googling and not finding any solution, I have given up.

### How can we reproduce the issue?

```shell
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.logging.Logger;

public class App {
    public static void main(String[] args) throws Exception {
        System.setProperty("webdriver.chrome.driver", "~/selenium/testing/bin/chromedriver");
        System.out.println("Hello, World!");
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.google.com/");
    }
}
```

### Relevant log output

```shell
stanleysearles@penguin:~/selenium/testing$  cd /home/stanleysearles/selenium/testing ; /usr/bin/env /usr/lib/jvm/java-11-openjdk-amd64/bin/java @/tmp/cp_7r9xyq3157ogcvar0i6oijr33.argfile App 
Hello, World!
Jun 12, 2023 12:26:05 AM org.openqa.selenium.remote.service.DriverService$Builder getLogOutput
INFO: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: chromedriver located at ~/selenium/testing/bin/chromedriver, but invalid
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.95-16525-g33e57601bd30', java.version: '11.0.18'
Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:45)
        at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:98)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:87)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
        at App.main(App.java:10)
```

### Operating System

ChromeOS - Linux Penguin Virtual Machine

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112 (not starting at all with Selenium)

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver Linux64 for Chrome Versions 112 and 114, as well as the automatically downloaded versions by the newest versions of Selenium

### Are you using Selenium Grid?

No.

**Comment by titusfortner** [comment]
Thank you for filing this. Can you please turn on logging and provide the results? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by backupmachiavelli** [comment]
@titusfortner the result saved in the xml doesn't really say anything, even with logger levels ALL: 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2023-06-12T08:04:59.784582Z</date>
  <millis>1686557099784</millis>
  <nanos>582000</nanos>
  <sequence>0</sequence>
  <logger>org.openqa.selenium.remote.service.DriverService</logger>
  <level>INFO</level>
  <class>org.openqa.selenium.remote.service.DriverService$Builder</class>
  <method>getLogOutput</method>
  <thread>1</thread>
  <message>Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output</message>
</record>
</log>
```

**Comment by titusfortner** [comment]
Ok, looking at this from my laptop instead of my phone is helpful.

The error is: 
```
chromedriver located at ~/selenium/testing/bin/chromedriver, but invalid
```

Which means the driver was found, but wasn't executable. `chmod +x` and try again.

**Comment by backupmachiavelli** [comment]
@titusfortner Okay that was embarrassing to forget, thank you. Sadly, it still didn't work. checked in the terminal by using ./chromedriver and now it can execute in the terminal and show the version, however it still gives the error message you mentioned above without any log messages. I tried it again with both version 112 and 114 (the last one shouldn't work anyway since I don't think the VM can start the chrome version installed on Chrome OS)

**Comment by titusfortner** [comment]
`~/selenium/testing/bin/chromedriver --version` works, but you still get a `NoSuchDriverException` with that message?

You definitely need Chrome installed where chromedriver can find it, but that should give a different error.

**Comment by backupmachiavelli** [comment]
@titusfortner Yes. chromedriver can be executed from the terminal without problems. Chrome is installed in usr/bin/ where I think it's always installed on linux when downloading chrome with the wget command. 

I have also run a listing of the user permissions of the google chrome and google chrome stable apps to be sure and the user permissions allow a complete execution for both chrome versions as well. Both chrome versions are on 114 now. So I downloaded chromedriver externally again, and it's still giving the ```NoSuchDriverException``` driver invalid error.

I kind of have the feeling the problem has something to do with the missing user interface of the linux penguin virtual machine on ChromeOS. The virtual machine can only be controlled via the terminal, executed apps open up in seperate windows on the ChromeOS user interface. Also, apps which are installed on the Penguin VM can be started from the start menu in ChromeOS. Do you have the possibility to test this with a terminal only Linux VM? (On a Windows OS for example)

**Comment by titusfortner** [comment]
Oh, try specifying the full path for the location of the driver without the tilda.

**Comment by backupmachiavelli** [comment]
It worked! Thank you very much!
