### ISSUE TITLE
Memory leak in session creation

### ISSUE THREAD

**Issue by mikewrighton** [SeleniumHQ/selenium#1219]
I'm seeing an increase in memory consumption as I create and delete browser sessions. The increase is small - if I had to guess I'd say it's in the order of a few MBs per session - but large enough to mean I can't run my Selenium Grid Nodes for more than a few hours. 

I took some heap dumps and one thing I noticed is that each Session instantiates a TemporaryFilesystem which registers an inner class as a shutdown hook - this means the JVM will hold on to the TemporaryFilesystem until it terminates (I think). I don't know if this is related to the memory increase I'm seeing, but it doesn't look right.

I've seen various articles about Selenium Grid clusters describing the need to periodically restart the nodes. Is this actually recommended, or is it intended that sessions are fully cleaned up on deletion?

(For the avoidance of doubt, I'm calling WebDriver.quit() each time.)

**Comment by ddavison** [comment]
one thing you could try, is removing everything in the temp directories, on a regular basis.  that's worked very well for me.. never had to restart a node.

**Comment by ambirag** [comment]
@mikewrighton i am seeing similar issue after moving to 2.48.2 from 2.43.1,  can you confirm the version of selenium webdriver you are using ?

**Comment by mikewrighton** [comment]
False alarm. As far as I can tell, the problem was just that I wasn't setting max heap, and I had a lot of physical memory on the machine meaning that garbage collection wasn't happening. I'm now setting it to 2G per node and it appears to be stable. (I was using version 2.47.1 fwiw).

**Comment by ddavison** [comment]
cool, thanks for sharing your experience @mikewrighton
