### ISSUE TITLE
[🐛 Bug]:  unable to allow clipboard permission popup using desiredCapabilities

### ISSUE THREAD

**Issue by pkc221992** [SeleniumHQ/selenium#12204]
### What happened?

unable to allow clipboard permission popup using desired capabilities when setting is set to 1

setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 0 }
}); -> popup is shown
setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 1 }
}); -> nothing happens
setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 2 }
}); -> popup is blocked

### How can we reproduce the issue?

```shell
setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 0 }
}); -> popup is shown
setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 1 }
}); -> nothing happens
setProperty(testOptions, 'desiredCapabilities/goog:chromeOptions/prefs/profile.content_settings.exceptions.clipboard', { '*':

{ setting: 2 }
}); -> popup is blocked
```

### Relevant log output

```shell
logs not available
```

### Operating System

windows 10

### Selenium version

^4.5.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

All browser driver versions

### Are you using Selenium Grid?

no

**Comment by pkc221992** [comment]
https://stackoverflow.com/questions/76034562/allow-enable-clipboard-permission-popup-using-selenium-with-javascript

**Comment by titusfortner** [comment]
answered on SO
