### ISSUE TITLE
Client certificate authentication with selenium server fails

### ISSUE THREAD

**Issue by hintonaac** [SeleniumHQ/selenium#1221]
Client certificate authentication with selenium server fails

**Comment by ddavison** [comment]
there is not even close to enough information for us to do anything.  what browser are you using? version?  

we'll at least need some information like that, including a short concise reproducible test case to help you

**Comment by hintonaac** [comment]
I just updated it. Client certificate authentication with selenium server fails...Using Selenium Server 2.47.1 and Firefox 41.0.1
