### ISSUE TITLE
[🐛 Bug]: Expected to read a START_MAP but instead have: END. Last 0 characters

### ISSUE THREAD

**Issue by bchhabra** [SeleniumHQ/selenium#12217]
### What happened?

 private FirefoxDriver prepareFirefoxWebDriver () {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("--headless=new");
        return new FirefoxDriver(options);
    }

<selenium.version>4.10.0</selenium.version> 
Issue happens only in jenkins while launching the browser in headless mode.

not able to reproduce in macos Ventura 13.4 or Windows.

### How can we reproduce the issue?

```shell
launch Firefox as headless on RHEL 7.9

NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### Relevant log output

```shell
Error Message

Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [--headless=new]}}

Stacktrace

org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {args: [--headless=new]}}
	at com.sample.test.ratePayTest(PPRTest.java:41)
Caused by: org.openqa.selenium.json.JsonException: Unable to parse: 
	at com.sample.test.ratePayTest(PPRTest.java:41)
Caused by: org.openqa.selenium.json.JsonException: 
Expected to read a START_MAP but instead have: END. Last 0 characters read: 
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.92.1.el7.x86_64', java.version: '1.8.0_361'
Driver info: driver.version: FirefoxDriver
	at at com.sample.test.ratePayTest(PPRTest.java:41)
```

### Operating System

RHEL 7.9

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 

### What are the browser driver(s) and version(s) where you see this issue?

firefox-102.11.0-2.el7_9  geckodriver-0.29.1-2

### Are you using Selenium Grid?

NO

**Comment by bchhabra** [comment]
@joerg1985 FYR

**Comment by joerg1985** [comment]
@bchhabra thanks, so this happens while the driver session is starting. I think this is not related to the other issues.

I see a NoSuchDriverException, did you try to set the path to the driver via `System.setProperty("webdriver.gecko.driver","absolut/path/to/execurable");`?

**Comment by titusfortner** [comment]
Headless=new isn't valid for Firefox, only chrome. Try with just -headless

But that shouldn't give you a no such driver exception, so I'm curious what the log output would show. Take a look at https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

Also, the geckodriver version you referenced is old. Can you delete that and let selenium get the right driver for you?

**Comment by joerg1985** [comment]
I think this might be a issue in the SeleniumManager, the output of the command is parsed before the status code of the command is checked. The check `code  > 0` to find out if the command failed could also be wrong, is this really true for all systems? I would expect something like `code != 0`

**Comment by titusfortner** [comment]
They also said it only happens when setting headless which should only matter after getting the driver. Either way, I really want to see what the logs show.

**Comment by joerg1985** [comment]
The PR will not fix the root issue it will only help to have a better error message in this cases.

**Comment by diemol** [comment]
Closing as we did not get more information. I will leave some links below where you can ask more questions.
