### ISSUE TITLE
[🐛 Bug]: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No node with given id found"}

### ISSUE THREAD

**Issue by Geobm** [SeleniumHQ/selenium#12221]
### What happened?

Hi, first of all thank you for the great project.

I'm trying to perform real-time file downloading of websites using Selenium and the Requests library. The goal is to send a GET request and download every file that is being loaded. However, I encountered an issue specifically when downloading files from the CNN website. I discovered that several users have also encountered the same problem, as discussed in this [Google Groups thread](https://groups.google.com/g/chromedriver-users/c/jzB5FBvZaog). It's possible that this issue is related to compatibility between the Chrome driver and the CNN website?. I would greatly appreciate any guidance or suggestions. TIA

Basically this two functions does the aforementioned file-downloading

### How can we reproduce the issue?

```python3

from selenium import webdriver
import selenium
import requests
import logging 
import logging
import os
import urllib.parse
import subprocess
from colorama import Fore
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")
logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
chrome_driver_path = '/home/asset/Downloads/chromedriver'
driver = webdriver.Chrome(executable_path=chrome_driver_path, options=chrome_options)

def download_website_files_selenium(url, save_directory):
    driver.get(url)

    # Download all resources
    resource_tags = driver.find_elements_by_css_selector('img, video, audio, source, link[rel="stylesheet"], script[src]')
    for resource_tag in resource_tags:
        try:
            src = resource_tag.get_attribute('src')
            if not src:
                src = resource_tag.get_attribute('href')
            if src:
                download_file(src, save_directory)
        except selenium.common.exceptions.StaleElementReferenceException:
            print(Fore.YELLOW + "StaleElementReferenceException: Skipping a stale element.")

    # Download all linked files
    anchor_tags = driver.find_elements_by_tag_name('a')
    for anchor_tag in anchor_tags:
        try:
            href = anchor_tag.get_attribute('href')
            if href:
                download_file(href, save_directory)
        except selenium.common.exceptions.StaleElementReferenceException:
            print(Fore.YELLOW + "StaleElementReferenceException: Skipping a stale element.")

    driver.quit()

def download_file(url, save_directory):
    # Normalize the URL to handle relative paths correctly
    url = urllib.parse.urljoin(driver.current_url, url)
    
    # Handle query parameters and fragments
    parsed_url = urllib.parse.urlparse(url)
    filename = os.path.basename(parsed_url.path)
    if parsed_url.query:
        filename += '?' + parsed_url.query
    if parsed_url.fragment:
        filename += '#' + parsed_url.fragment

    # Truncate the filename if it exceeds the limit
    max_filename_length = 255  # Adjust as per your file system's limit
    if len(filename) > max_filename_length:
        filename = filename[:max_filename_length]

    file_path = os.path.join(save_directory, filename)

    try:
        # Use requests library to download the file
        response = requests.get(url, stream=True)
        response.raise_for_status()

        if filename.endswith('/'):
            # Create the corresponding directory
            directory_name = filename.rstrip('/')
            directory_path = os.path.join(save_directory, directory_name)
            os.makedirs(directory_path, exist_ok=True)
            download_website_files_selenium(url, directory_path)
        else:
            # Save the file
            with open(file_path, 'wb') as file:
                for chunk in response.iter_content(chunk_size=1024):
                    if chunk:
                        file.write(chunk)
    except (requests.exceptions.RequestException, IOError) as e:
        print(Fore.YELLOW + f"Error downloading file from" + Fore.RESET, f"{url}: {e}")

# Usage
website_url = "https://edition.cnn.com"
save_directory = "/home/asset/Desktop/Selenium/Chap_6/cnn"

download_website_files_selenium(website_url, save_directory)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "scrap.py", line 85, in <module>
    download_website_files_selenium(website_url, save_directory)
  File "scrap.py", line 23, in download_website_files_selenium
    src = resource_tag.get_attribute('src')
  File "/home/asset/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 141, in get_attribute
    self, name)
  File "/home/asset/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/asset/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/asset/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No node with given id found"}
  (Session info: headless chrome=114.0.5735.106)
```

### Operating System

Ubuntu 18.04.1

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.106

**Comment by diemol** [comment]
A couple of things. 
- Please upgrade to the latest Selenium, so we can see if the issue is in Selenium or the browser driver.
- Try with Firefox and see if you get the same error.

**Comment by parhedberg** [comment]
We also see this problem as of last week when we did an update on our grid.

We run Selenium 4.10 on the grid, selenium-webdriver 4.10.0 in ruby and chrome latest docker image..
Strange thing is that it only appears in 2 of our projects.. So they must be doing something that the others don't. 

I have now been trying to run the same project in chrome, edge and firefox, and with firefox there is no issues. So. A Chromedriver issue?

**Comment by diemol** [comment]
That was my thought, @parhedberg. If you have a way to reproduce it then it can be reported to the Chrome team.

**Comment by Geobm** [comment]
Indeed @diemol, I tried with selenium 4.10.0 with geckodriver from firefox with the same code from above and there is no problem. Might be a chromedriver issue then

**Comment by adis-io** [comment]
100% chromedriver bug: https://groups.google.com/g/chromedriver-users/search?q=No%20node%20with%20given%20id%20found

**Comment by parholmdahl** [comment]
I found, that for us this issue was due to multiple redirects, and at the same time, trying to find a text on page.. Then when it redirected, it got lost.. I fixed it with a sleep, so that the redirects have their time to finish, and the error is gone.. 

But, something has happened in the last chromedriver version because the code is not changed on our part..

Maybe something for you to think about @Geobm, if this is the case with your issue also?

**Comment by Geobm** [comment]
@parholmdahl To be honest I didn't try anymore with chromedriver because I was getting the expected behavior with geckodriver from firefox. Will try with chromedriver by adding some sleep functions to test my specific case, but it will be nice to have a response from chrome the to see what is the specific issue.
