### ISSUE TITLE
[🐛 Bug]: RemoteWebDriver DevTools fails session creation

### ISSUE THREAD

**Issue by Auto81** [SeleniumHQ/selenium#12224]
### What happened?

Trying to setup DevTools with RemoteWebDriver on Java. Discussed with @diemol on slack.

Locally everything runs as expected (chrome and firefox). But when using a remote grid, the browser does open on the grid, but various errors happen.

I have tried multiple permutations, documented in the java test below.

Anymore combinations I can try, please let me know

Grid is using JDK11
Java/Test Runner is JDK11

### How can we reproduce the issue?

```shell
//String GRID_IP_PORT_ADDRESS = "ddd.ddd.d.dd:dddd";
  //String GRID_IP_ADDRESS = "ddd.ddd.d.dd";

  @Test
  public void devtools() throws MalformedURLException {
    //Test runner on a different machine than the grid. Hub + Node on same machine
    RemoteWebDriver driver = new RemoteWebDriver(new URL(String.format("http://%s", GRID_IP_PORT_ADDRESS)), new ChromeOptions());

    driver = (RemoteWebDriver)new Augmenter().augment(driver);
    DevTools devTools = ((HasDevTools)driver).getDevTools();
    devTools.createSession();
  }

  //grid - hub  : java -jar selenium-server-4.10.0.jar hub --port 4455 --host GRID_IP_ADDRESS
  //WITH //grid - node : java -jar selenium-server-4.10.0.jar node --grid-url <GRID_IP_PORT_ADDRESS>
  // OR  //grid - node : java -jar selenium-server-4.10.0.jar node --grid-url localhost
  // OR  //grid - node : java -jar selenium-server-4.10.0.jar node --grid-url <GRID_MACHINE_NAME>
  //RESULT : java.lang.IllegalArgumentException: ws:/session/GUID/se/cdpws:/session/GUID/se/cdp could not be parsed into a proper Uri, missing host
  //------------
  //------------
  //grid - hub  : java -jar selenium-server-4.10.0.jar hub --port 4455 --host GRID_IP_ADDRESS
  //WITH //grid - node : java -jar selenium-server-4.10.0.jar node --grid-url http://<GRID_IP_PORT_ADDRESS>
  // OR  //grid - node : java -jar selenium-server-4.10.0.jar node --grid-url http://<GRID_MACHINE_NAME>
  //RESULT : org.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://<GRID_IP_PORT_ADDRESS/MACHINE_NAME>/session/GUID/se/cdp
```

### Relevant log output

```shell
Examples included above
```

### Operating System

MacOS for test runner and grid machine

### Selenium version

java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114

### Are you using Selenium Grid?

4.10.0

**Comment by Auto81** [comment]
When running the grid without the `--port 4455` flag and repointing the RemoteWebDriver `GRID_IP_ADDRESS:4444 `, everything works as expected. Maybe the custom/overridden port isn't being propagated everywhere?

**Comment by diemol** [comment]
`--grid-url <GRID_IP_PORT_ADDRESS>` this needs to be the full URL. If you are using the port 4455, then it is `http://yourHost:4455`.

**Comment by Auto81** [comment]
Will double check on Monday but i think that was one of the options tried. Will try with the http:// prefix as per your example

java -jar selenium-server-4.10.0.jar node --grid-url http://<GRID_IP_PORT_ADDRESS>

**Comment by Auto81** [comment]
Looks to be working with no host on the hub, and the full address on the node, thanks

Hub  - `java -jar selenium-server-4.10.0.jar hub --port 4455`
Node - `java -jar selenium-server-4.10.0.jar node --grid-url http://<<IP>>:4455`

**Comment by diemol** [comment]
Great!
