### ISSUE TITLE
Using Selenium Server 2.47.1 and Firefox 41.0.1...Client certificate authentication with selenium server fails...

### ISSUE THREAD

**Issue by hintonaac** [SeleniumHQ/selenium#1222]
Using Selenium Server 2.47.1 and Firefox 41.0.1...Client certificate authentication with selenium server fails

**Comment by lukeis** [comment]
@hintonaac what server is using this type of certificate? and do you have an example website to point us at?

Otherwise I'm a bit confused by what you mean. A reproducible test case would go a long way here (and why the previous issue was closed)

**Comment by lukeis** [comment]
no further details have been provided... going to close this for now.
