### ISSUE TITLE
[🐛 Bug]: Selenium 4.9 Chromedriver is invoked with 88 version but browser version is 114

### ISSUE THREAD

**Issue by Menaga110** [SeleniumHQ/selenium#12222]
### What happened?

I am using selenium 4.9 version. 
I am trying to run scripts in chrome browser where as my default browser is chrome. my browser version is 114 but chrome driver is invoking with 88. i am not sure where i have to check driver version i didn't pass any driver version in the scripts as part of selenium 4 update we don't need to give the browserdriver.
![DriverInvoke](https://github.com/SeleniumHQ/selenium/assets/75593771/157f315d-6c88-4020-b8d6-9f5db14d10dd)

### How can we reproduce the issue?

```shell
ChromeOptions options1=new ChromeOptions();
options1.addArguments("--remote-allow-origins=*");
WebDriver driver1= new ChromeDriver();
```

### Relevant log output

```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}) on port 37625
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Copied


1 Scenarios (1 failed)
13 Steps (1 failed, 12 skipped)
0m16.118s

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 114.0.5735.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: '', ip: ''
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
```

### Operating System

Windows 10

### Selenium version

Java 4.9

### What are the browser(s) and version(s) where you see this issue?

Chrome - 114.0.5735.111

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 88

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Selenium will use the ChomeDriver binary you have on your `PATH`. The easiest will be to find that binary and delete it, and let Selenium handle the ChromeDriver configuration for you.

**Comment by Menaga110** [comment]
@diemol Thanks for the response.
When i delete the chrome binary path getting below error,

```bash
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary 
Host info: host: '', ip: ''
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:94)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:165)
```

**Comment by diemol** [comment]
That means you don't have Chrome installed. Make sure you have it on the machine.

**Comment by Menaga110** [comment]
Hi @diemol,
No , before i had the chrome in my machine as per you comments have deleted the binary path.

**Comment by diemol** [comment]
I meant the ChromeDriver binary.

**Comment by Menaga110** [comment]
I could see chrome binary only, couldn't find the chromedriver binary path.

**Comment by krmahadevan** [comment]
@Menaga110 - I am currently on Mac. 

When I open up a terminal and run `which chromedriver` I will see an output such as below

```bash
➜  ~ which chromedriver
chromedriver not found
```

Similarly I think you can use the `where` command on windows, open up a command prompt and run `where chromedriver`. This will try to search for the existence of `chromedriver.exe` on any of the directories in your PATH variable.
Once you find it, you can delete the `chromedriver.exe`

**Comment by Menaga110** [comment]
Hi @krmahadevan 
I tried with which command in my machine, getting below resposne.

>where chromedriver
INFO: Could not find files for the given pattern(s).

and I couldn't find any other way to find the chromedriver.

**Comment by krmahadevan** [comment]
@Menaga110 - Ok. One last thing. If you open up the command prompt and then type `chromedriver` do you see anything or do you get an error message ?

Basically we are trying to figure out where in your system does chromedriver exist (are you using some sort of framework which behind the scenes is setting this up via some `System.setProperty()` ) ?

The error message is clearly saying that there's a mismatch between your `chrome.exe` and `chromedriver.exe`

```bash
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 114.0.5735.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: '', ip: ''
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_281'
```
Since we dont have access to your machine, you would need to figure out where is this old `chromedriver.exe` being resolved from.
