### ISSUE TITLE
Selenium returning wrong Platform/OS name when executed from local machine

### ISSUE THREAD

**Issue by YatheeshKumar** [SeleniumHQ/selenium#1223]
Hi,

To display the os name(on which test executes) in the final report we have used the following code in the selenium-java test

Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
		System.out.println(cap.getPlatform());

When the above code executes

OS is displayed as ‘XP’ when script runs in Chrome browser on Win 7 desktop
OS is displayed as ‘Windows’ when script runs in Firefox browser on Win 7 desktop

Please let us know if we can do something to get the correct platform/os name.

Thanks,
Yatheesh.

**Comment by barancev** [comment]
Selenium returns the platform that the browser returns.
