### ISSUE TITLE
[🐛 Bug]: Not selecting the correct option from auto suggest dropdown list

### ISSUE THREAD

**Issue by letskodeit** [SeleniumHQ/selenium#12238]
### What happened?

On a website, I am trying to select an option from the autosuggest dropdown list.
Selenium is finding the correct element but when clicking it is always selecting the first option.

Website Name: https://www.letskodeit.com/practice
Element: Autosuggest Example Text Box. This element can be found with XPath `//input[@id='autosuggest']`

### How can we reproduce the issue?

```shell
import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.letskodeit.com/practice")

driver.find_element(By.ID, "autosuggest").send_keys('auto')

time.sleep(2)
# Finding the option directly by XPath, Selenium found this element and click action succeeded but it selected the first option instead
driver.find_element(By.XPATH, "//li[@class='ui-menu-item' and normalize-space()='API Automation']").click()

# Then, I tried with finding element list, found the option that I wanted to select. Selenium found the correct option and clicked on it but again the first option from the list was selected.
element_list = driver.find_elements(By.XPATH, "//li[@class='ui-menu-item']")
for element in element_list:
    if element.text == "API Automation":
        print(element.text)
        element.click()
        break

time.sleep(5)
driver.quit()
```

### Relevant log output

```shell
There are no logs as Selenium was successful in the click but it is clicking the first option instead of the one provided in the XPath.
```

### Operating System

MacOS Ventura

### Selenium version

Python 4.10

### What are the browser(s) and version(s) where you see this issue?

Version 114.0.5735.133 

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 114.0.5735.133 

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
It works for me. You need to be careful because if you interact with the browser manually at all while running the script, it will cause the elements in the list to disappear and Selenium won't be able to interact with them.

**Comment by letskodeit** [comment]
@titusfortner 
I have not interacted with the browser at all while running the script.
If the element will disappear, then Selenium will not be able to interact with them and hence will throw an exception.

But please read the original issue. Selenium is interacting with the list and always selecting the first option.

Please run the code again and carefully check which option is getting selected.

**Comment by titusfortner** [comment]
I'm not sure what to say. This passes just fine for me (Mac Ventura, Chrome v114):

```
    driver = webdriver.Chrome()
    driver.get("https://www.letskodeit.com/practice")

    autosuggest = driver.find_element(By.ID, "autosuggest")
    autosuggest.send_keys('auto')

    time.sleep(1)
    driver.find_element(By.XPATH, "//li[@class='ui-menu-item' and normalize-space()='API Automation']").click()
    assert autosuggest.get_property("value") == "API Automation"
```

Regardless, Selenium code is sending the right commands to the driver. If there's an issue it isn't with what the Selenium code is doing.

**Comment by letskodeit** [comment]
@titusfortner 
I debugged a little more. It actually works fine the first time but fails the second time.

Can you please quickly checkout this?
https://www.loom.com/share/03d778a3f71242fbaa0f75666fc4d09e

Here is the updated code:

```
import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.letskodeit.com/practice")

autosuggest = driver.find_element(By.ID, "autosuggest")
autosuggest.send_keys('sel')
time.sleep(1)
driver.find_element(By.XPATH, "//li[@class='ui-menu-item' and normalize-space()='Selenium WebDriver Java']").click()
time.sleep(1)

autosuggest.clear()
autosuggest.send_keys('auto')

time.sleep(1)
driver.find_element(By.XPATH, "//li[@class='ui-menu-item' and normalize-space()='API Automation']").click()
time.sleep(5)
assert autosuggest.get_property("value") == "API Automation"

time.sleep(2)
driver.quit()

```
