### ISSUE TITLE
[🐛 Bug]: [Question] is it expected that some of the classes use DefaultSlotMatcher

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/selenium#12234]
### What happened?

Hello, 

In my grid, I defined a custom SlotMatcher. 
But, I see that some classes "LocalNodeFactory", and "Slot" are using the DefaultSlotMatcher. So when checking if a slot has the capacity to handle some request, its response will be based on DefaultSlotMatcher instead of the custom matcher

Is it an expected feature ?

Thanks for your reply

### How can we reproduce the issue?

```shell
Not an issue, just a question for now
```

### Relevant log output

```shell
no logs
```

### Operating System

linux

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 115

### Are you using Selenium Grid?

4.10.0

**Comment by diemol** [comment]
That seems to be a bug, actually.

**Comment by bhecquet** [comment]
Do you want I try to provide a PR ?

**Comment by diemol** [comment]
That'd be great!
