### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

### ISSUE THREAD

**Issue by kingrapha** [SeleniumHQ/selenium#12245]
### What happened?

Python language bindings for selenium WebDriver raises a selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id. The browser is closed without triggering driver.quit() or driver.close() yet. 

This on selenium grid 4.9.1 configured in kubernetes cluster using helm chart selenium-grid-0.18.0 with keda auto scaling.
In values.yaml file:
ChromeNode:
  extraEnvironmentVariables:
      - name: SE_NODE_SESSION_TIMEOUT
         value: “900”

  terminationGracePeriodSeconds: 30
  lifecycle: {}
    preStop:
       exec:
         command:
          - bash
          - -c
          - |
             curl -X POST 127.0.0.1:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
    while curl 127.0.0.1:5555/status; do sleep 1; done

### How can we reproduce the issue?

```shell
options = Options()
options.add_argument(—-no-sandox’)
options.add_argument(—-disable-infoxbars’)
options.add_argument(—-disable-hang-monitor’)
options.add_argument(—-disable-setuid-sandbox’)
options.add_argument(—-disable-dev-shm-usage’)

caps = {‘browserName’: ‘chrome’, ‘platformName’: ‘LINUX’, ‘acceptInsecureCerts’: True}

driver = webdriver.remote(command_executor= https://selenium-grid-url, desired_capabilities=caps, options= options)
try:
   driver.get(“testing application url”)
   wait = WebDriverWait(driver, 60)
   element = wait.until(EC.element_to_be_clickable((By.ID,”locator”)
   element.click()
   wait.until(EC.invisibility_of_element_located((By.ID, “loading-bar”)
   ………more test code……
finally:
   driver.quit()
```

### Relevant log output

```shell
raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

### Operating System

Linux

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome, 113

### What are the browser driver(s) and version(s) where you see this issue?

Chrome webdriver version 113

### Are you using Selenium Grid?

4.9.1

**Comment by diemol** [comment]
This has been several times reported and most of the time is the lack of configuration, please read https://www.selenium.dev/blog/2022/scaling-grid-with-keda/ and check your settings. We are merging a PR with Keda integration soon so this should be more straightforward.
