### ISSUE TITLE
[🐛 Bug]: Getting blank or black screenshot while running the test scripts on azure self hosted agent in service mode for Edge in IE mode

### ISSUE THREAD

**Issue by AbhiAuto** [SeleniumHQ/selenium#12247]
### What happened?

We gets a blank or black screenshot while running test automation scripts on Azure Self Hosted agents (Windows 2019 server 64 Bit) in service mode on Edge in IE mode. The execution is flawless, with no errors. 

**Note :** While working on the local machine on Windows 10 for debugging and development, as well as in the interactive mode on Windows 2019 64 bit, the screenshot does not seem blank or black.

![image](https://github.com/SeleniumHQ/selenium/assets/26138640/6367aad4-0cef-41cb-9c53-e6939a648148)

### How can we reproduce the issue?

```shell
Run the sample test scripts on Azure Self Hosted agents (Windows 2019 server 64 bit) in service mode on Edge in IE mode and capture a snapshot with the code below. We will afterwards attach the screenshot to the Extent Report(5.0.9) as media.

public Media takeScreenshot() {
Media media = null;
try {
TakesScreenshot scrShot = ((TakesScreenshot) BrowserDriver.getDriver());
String screenBase = scrShot.getScreenshotAs(OutputType.BASE64);
media = MediaEntityBuilder.createScreenCaptureFromBase64String(screenBase).build();	
} catch (Exception e) {
e.printStackTrace();
}
return media;
}
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows Server 2019 64 bit

### Selenium version

Java 4.7.2

### What are the browser(s) and version(s) where you see this issue?

Edge(114) in IE mode 

### What are the browser driver(s) and version(s) where you see this issue?

IE Driver 4.10.0

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Right, using the IEDriver as a service has been known to show issues, I think screenshots is one of those. Probably the same thing happens with the IE Mode. In addition, screenshots need a display and also a user logged in. 

Probably you can ask in the https://github.com/MicrosoftEdge/EdgeWebDriver repo in case something can be done.
