### ISSUE TITLE
[🚀 Feature]: browsingContext.setViewport has been added to webdriver-bidi

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#12242]
### Feature and motivation

The feature browsingContext.setViewport has been added to webdriver-bidi in this PR: https://github.com/w3c/webdriver-bidi/pull/425

### Usage example

It is a command to emulate the viewport of the top-level browsing context

**Comment by pujagani** [comment]
I am closing this issue since tracking everything in one place is easier. Please refer to the [Selenium BiDi tracker](https://docs.google.com/document/d/1PwRUs9fKuPctyqtICJpiaGabWy0TDKDbmMfpSKszdpA/edit?usp=sharing) to see the current status.
