### ISSUE TITLE
[🐛 Bug]: TypeScript definition of `setSize()` differs from JavaScript implementation

### ISSUE THREAD

**Issue by marvinruder** [SeleniumHQ/selenium#12243]
### What happened?

The JavaScript function `webdriver.js:Window.setSize()` at https://github.com/SeleniumHQ/selenium/blob/a04a22f4490da1b9576f251a5f16fa34e8898645/javascript/node/selenium-webdriver/lib/webdriver.js#L2273-L2276 requires an object containing `x`, `y`, `width` and `height` entries as the first and a string `windowHandle` as the second argument. 

The type definition of the same function at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8878eece703d9abf41cce1e9fbfe699b7969f798/types/selenium-webdriver/index.d.ts#L1252 requires a number `width` and a number `height` as arguments.

### How can we reproduce the issue?

1. In a TypeScript project using packages `selenium-webdriver` and `@types/selenium-webdriver`, type `await driver.manage().window().setSize(`
2. Observe that TypeScript provides the following information for that function:

```
(method) Window.setSize(width: number, height: number): Promise<void>

Resizes the current window.
@param width — The desired window width.
@param height — The desired window height.
@return
A promise that will be resolved when the command has completed.
```

3. Type `await driver.manage().window().setSize(1920, 1080);` and run the code.
4. Observe the warning message `Only 'current' window is supported for W3C compatible browsers.`.
5. Repeat with a debugger attached and enter the function `setSize(…)`.
6. Observe that `1080` was interpreted as the `windowHandle` string and that `x`, `y`, `width` and `height` are set to 0.

### Relevant log output

```
Only 'current' window is supported for W3C compatible browsers.
```

### Operating System

Docker Desktop 4.20.1 (110738) on macOS 13.5 (build 22G5038d)

### Selenium version

selenium-webdriver: 4.10.0, @types/selenium-webdriver: 4.1.15

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

chromedriverVersion: 114.0.5735.106

**Comment by titusfortner** [comment]
This is something that needs to be fixed in another repo? I just asked this elsewhere, but I think we should be managing this repo, and whoever wants to use definitely typed needs to make PRs to that repo.
As such I'm going to close this, but I'm open to re-opening this and other similar if it is agreed that we should be maintaining both.

**Comment by marvinruder** [comment]
Ah, I assumed the folks at @SeleniumHQ would be maintaining the type definitions to their package as well, just in a different repository. If not, this issue is better reported at @DefinitelyTyped, that’s right.

**Comment by titusfortner** [comment]
We're understaffed in the JavaScript bindings right now, so there are a bunch of things we aren't able to keep up on (hence the 6 months of no response to the issue). So, I'm just trying to be realistic about what we're actually going to be able to get to, and if it is something that we can easily ask for help from other people, I'm looking to do that. But definitely appreciate the communication, and we would also appreciate any help you can provide. Thanks.
