### ISSUE TITLE
Cannot open upload File in Selenium 2.48

### ISSUE THREAD

**Issue by elrenatom** [SeleniumHQ/selenium#1224]
Hi,

After update Selenium 2.48.0, not open Windows Dialog select file after click FileUpload.
In this version Selenium 2.47.0, it's ok.

I used :
- Firefox 41.0.2
- Windows 7 Professional
- .Net Framework 4.5

Thanks,

**Comment by ddavison** [comment]
hi @elrenatom Could you give us a [SSCCE](http://sscce.org) please, so we can reproduce this issue?

**Comment by elrenatom** [comment]
Hi ddavison.

I could not put together a test case.

But I think it's something he lost in the click of the button input with some images above.
It follows a model I made, but without success.

<html>
	<body>		
		<form>
		  <div style="position: relative; width=100px;height=300px; background-color:#CCC"; >
			  teste<br>
			  <br>
			  <br>
			  <br>
  
			<input type="file" name="file" style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 18px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0;"/>
		  </div>
		</form>		
	</body>
</html>

---------------------------------------------------
.NET

        [TestMethod]
        public void TestMethod2()
        {
            FirefoxDriver firefox = new FirefoxDriver();

            firefox.Navigate().GoToUrl(@"file:///C:/Users/xxx/Desktop/teste.html");

            System.Threading.Thread.Sleep(new TimeSpan(0, 0, 5));
            //firefox.FindElement(By.Name("file")).Click();

            firefox.FindElement(By.XPath("html/body/form/div/input")).Click();



            SendKeys.SendWait(@"C:\selenium-dotnet-2.47.0.zip");

            System.Threading.Thread.Sleep(new TimeSpan(0, 1, 0));
            SendKeys.SendWait(@"{Enter}");
        }

------------------------------------------------------------
Down strech with a problem in the application



<div class="content">
           <input id="Nome" name="Nome" value="" type="hidden">
                     

<div id="Arquivo_file-upload"><div class="qq-uploader"><div style="display: none;" class="qq-upload-drop-area"><span>Arraste arquivos até aqui e solte para fazer o upload</span></div><div style="position: relative; overflow: hidden; direction: ltr;" class="qq-upload-button">Anexar<input style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0;" name="file" type="file"></div><div class="qq-maxsize-warning">Tamanho máximo <span id="qq-upload-max-file-size-message">150.0 MB</span></div><ul class="qq-upload-list"></ul></div></div>

<input id="Arquivo_NomeArquivo" name="Arquivo.NomeArquivo" value="" type="hidden">
<input id="Arquivo_NomeArquivoUnico" name="Arquivo.NomeArquivoUnico" value="" type="hidden">
<input id="Arquivo_UrlArquivo" name="Arquivo.UrlArquivo" value="" type="hidden">
<input id="Arquivo_HasArquivo" name="Arquivo.HasArquivo" value="False" type="hidden">
<input id="Arquivo_TamanhoMaximoUpload" name="Arquivo.TamanhoMaximoUpload" value="157286400" type="hidden">
<input id="Arquivo_MimeType" name="Arquivo.MimeType" value="" type="hidden">
<input id="Arquivo_ParamDOMId" name="Arquivo.ParamDOMId" value="TipoRepositorio" type="hidden">
<input id="Arquivo_FieldPrefix" name="Arquivo.FieldPrefix" value="Arquivo" type="hidden">
    
    <div style="display: none;" id="Arquivo_containerArquivo">

            <div id="Arquivo_fileDisplayName" class="file-uploader-display-name"></div>    
        
                <script type="text/javascript">
                    $(document).ready(function ()
                        {
                            $('#' + 'Arquivo_containerArquivo').hide();
                        });
                </script>
                            <a id="Arquivo_removerArquivo" class="removerArquivo" href="#">Remover</a>
        
    </div>
    


<script type="text/javascript">
    // Carrega os scripts para ativar o upload da imagem
    $(document).ready(function () {

        var fieldPrefix = 'Arquivo';
        

            
            var uploadElemContainer = document.getElementById('Arquivo_file-upload');
            var urlAction = '/contratos/arquivosEmpresa/UploadAnexo';
            var allowedExtensions = ["exe","pif","application","gadget","msi","msp","com","scr","hta","cpl","msc","jar","shs","bat","cmd","vb","vbs","vbe","js","jse","ws","wsf","wsc","wsh","ps1","ps1xml","ps2","ps2xml","psc1","psc2","msh1","msh2","msh","mshxml","msh1xml","msh2xml","scf","lnk","inf","reg","php","aspx","cshtml","cs","asp","asmx"];
            var sizeLimit = 157286400;
            var isArquivoGenerico = true;
            var domId;
            var alertOnLeave;
            var excludeExtensions;
            var tituloBotaoUpload;
            var funcaoCallbackInicioUpload = 'inicioUploadArquivo';
            var funcaoCallbackTerminoUpload = 'uploadArquivoConcluido';
            
                
                domId = 'TipoRepositorio';
                alertOnLeave = false;
                excludeExtensions = true;
                tituloBotaoUpload = 'Anexar';                                        
                
            configureFileUploader(uploadElemContainer, urlAction, allowedExtensions, sizeLimit, isArquivoGenerico, domId, alertOnLeave, excludeExtensions, tituloBotaoUpload, fieldPrefix, funcaoCallbackInicioUpload, funcaoCallbackTerminoUpload);
        
        $('#' + 'Arquivo_removerArquivo').click(function (e) {
            if ($.browser.msie && $.browser.version == '8.0')
                e.returnValue = false;
            else 
                e.preventDefault();

            $('#' + 'Arquivo_containerArquivo').hide(200);            
            $('#' + 'Arquivo_file-upload' + ' .qq-upload-list').empty();
            getElementByIdAndPrefix('HasArquivo', fieldPrefix).val('false');
            getElementByIdAndPrefix('NomeArquivo', fieldPrefix).val('');
        });
    });
</script>


        </div>

**Comment by barancev** [comment]
One should never 'Click' file input fields, just 'SendKeys' to them much like any other input fields.
