### ISSUE TITLE
[🐛 Bug]: webdriver

### ISSUE THREAD

**Issue by zbximo** [SeleniumHQ/selenium#12260]
### What happened?

mac arm 上运行webdriver,不管是chrome、firefox还是edge都非常的卡顿
Running webdriver on Mac arm, whether it's Chrome, Firefox, or Edge, is very sluggish

### How can we reproduce the issue?

```shell
11
```

### Relevant log output

```shell
11
```

### Operating System

macos

### Selenium version

python 4.10.1

### What are the browser(s) and version(s) where you see this issue?

chrome  114.0.5735.133

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver114.0.5735.90

**Comment by titusfortner** [comment]
There's nothing really actionable here. Are you used to it being faster on another architecture? Is there something that is breaking as a result of the speed not being what you want? Plenty of people are successfully using Selenium on Mac ARM architecture.

**Comment by zbximo** [comment]
The code is simple, but it takes 7 seconds to open this web. 
"""
from selenium import webdriver
from selenium.webdriver.common.by import By

import time

url = "https://www.baidu.com/"
options = webdriver.ChromeOptions()
options.add_argument('--user-data-dir=/Users/zbximoy/temp/selenium')
driver = webdriver.Chrome(options=options)
driver.get(url)
"""

**Comment by diemol** [comment]
Make sure all the installed binaries (Python, Chrome, etc) are for arm. Several people have installed x86 binaries by mistake and run into this issue.

**Comment by titusfortner** [comment]
It could also be downloading the driver, (or at least making network calls to verify the latest driver), which can add some time.

**Comment by zbximo** [comment]
> Make sure all the installed binaries (Python, Chrome, etc) are for arm. Several people have installed x86 binaries by mistake and run into this issue.

Chrome version:  114.0.5735.133 (arm64)
Driver:http://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.16/   [chromedriver_mac_arm64.zip](http://chromedriver.storage.googleapis.com/114.0.5735.16/chromedriver_mac_arm64.zip)

**Comment by zbximo** [comment]
> It could also be downloading the driver, (or at least making network calls to verify the latest driver), which can add some time.

When I use Safari, it's ok. But Safari cannot perform manual operations during automation operations.

**Comment by titusfortner** [comment]
Turn on logging and see what might be taking a long time - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

It might be Selenium Manager related because Safaridriver doesn't have to be downloaded

**Comment by diemol** [comment]
Closing as we did not get more input.
