### ISSUE TITLE
[🐛 Bug]: with protractor test SeleniumGrid is not seeing capabilities

### ISSUE THREAD

**Issue by StellarNear** [SeleniumHQ/selenium#12267]
### What happened?

Hello all, i was using selenium grid version 4.2.x and wanted to bump into the new version 4.10.0 with it i have one small problem doing a dummy test with a simple js protractor test with a simple configuration : 

`exports.config = {
	seleniumAddress: 'http://mycluster.com/selenium',
	  // add more browsers to this array for more parallel tests!!
	  capabilities: [{
		browserName: 'chrome'
	  }],
	specs: ['spec.js']
  }
`
The grid receive the session request nicely but the capabilities are empty (as you can see in the image below). 
![image](https://github.com/SeleniumHQ/selenium/assets/31210322/2861e022-704b-413a-ad4b-d342a8b74027)
My java projects work perfectly when requesting browsers tough only the protractor command seems not to be processed nicely in the queue session manager.

Please note that i use a kubernetes environement and i redirect the ingress to a subpath /selenium (thanks to your new feature --sub-path /selenium)

Any idea of what might be the problem ? 

### How can we reproduce the issue?

```shell
Create a simple js project that use a command "protractor config.js" as a test command trying to give some capabilities in that config file
```

### Relevant log output

```shell
- no error message found in the selenium pods -
```

### Operating System

linux / kubernetes

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

### Are you using Selenium Grid?

4.10.0

**Comment by diemol** [comment]
Most likely Protractor is not sending W3C caps? Since 4.8.0 or 4.9.0 Grid only support W3C capabilities. Please check if Protractor is able to send those.

**Comment by StellarNear** [comment]
THanks for your quick answer it seems indeed that proctractor is too old for this ...
