### ISSUE TITLE
[🐛 Bug]: Intermittent Issue - SessionNotCreatedException: session not created from no such execution context: context has changed while resolving nodes

### ISSUE THREAD

**Issue by ajaylamba-provar** [SeleniumHQ/selenium#12266]
### What happened?

We are trying to create ChromeDriver session using Selenium. The Selenium version which we are using is 3.4.0 and unfortunately we cannot upgrade that in short term.

We are getting below exception intermittently and we have not found the exact steps to recreate the issue.

```
[SessionNotCreatedException: session not created
from no such execution context: loader has changed while resolving nodes
 (Session info: chrome=114.0.5735.134)
 (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Windows NT 10.0.19044 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32.96 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System
```

### How can we reproduce the issue?

```shell
Issue is occurring intermittently and no exact steps are defined as of now. One thing is that we are initializing the chrome driver using new ChromeDriver()
```

### Relevant log output

```shell
[SessionNotCreatedException: session not created
from no such execution context: loader has changed while resolving nodes
 (Session info: chrome=114.0.5735.134)
 (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Windows NT 10.0.19044 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32.96 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System
```

### Operating System

Windows 10

### Selenium version

3.4.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.134

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

### Are you using Selenium Grid?

No

**Comment by ajaylamba-provar** [comment]
It works if we delete the chrome profile and fails intermittently in subsequent runs.

**Comment by titusfortner** [comment]
That's an extremely old version of Selenium. We only support the latest (4.10); please update and let us know if your issue remains.

**Comment by ajaylamba-provar** [comment]
Unfortunately we cannot update the version in short term, any help to resolve the issue would be appreciated. Or maybe any clues on why this issue might occur.

**Comment by diemol** [comment]
The problem is that Chrome has evolved quite a bit and I believe 3.4.0 did not have all the W3C code in yet? 

This is a long way of saying that it is hard for us to troubleshoot two versions so distant in time. Maybe you can extract the single test you are getting the error to a newer version and see how that goes. If it is related to Profiles, you can also extract the values set in the profile and set them through browser preferences. 

In any case, I will leave some links below where you can ask questions related to troubleshooting this old version. The link for our chat is there as well, so you can join it.

**Comment by diemol** [comment]
If after upgrading to 4.10.0, you still have the issue, we'd be happy to revisit.

**Comment by ajaylamba-provar** [comment]
Thanks, I will try to extract the values set in chrome profiles. 

Will wait for the links related to troubleshooting this version.
