### ISSUE TITLE
driver.FindElement().getAttributte() returns wrong (lower-cased?) value

### ISSUE THREAD

**Issue by rnnr** [SeleniumHQ/selenium#1227]
I found that for this element : 
```html
<img style="border: 4px solid currentColor;" src="" alt="bug?" width="150" height="126">
```

FirefoxDriver returns value ""border: 4px solid currentcolor;" , while HtmlDriver works OK.

Document: 
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">

<html>
<head>
<body>

<img style="border: 4px solid currentColor;" src="" alt="bug?" width="150" height="126">

</body>
</html>
```

Code:
```java
WebElement element = driver.findElement(By.xpath("//img"));
String style = element.getAttribute("style");
```

Dependencies: only selenium-java

**Comment by rnnr** [comment]
I have complete Maven mini-project with the issue for quick start, unfortunately zip files are not supported as attachments.

**Comment by barancev** [comment]
'style' is a special kind of attribute, Selenium returns element.style.cssText property instead of the row attribute value.

**Comment by BhuvaneshMani** [comment]
barancev, how about 'title' tag? But i have strange issue with img tag. When chrome driver is used, i can get what i need, but not with IE driver. Whats the problem with img tags?

http://stackoverflow.com/questions/39234557/selenium-ie-driver-not-working-with-img-element
