### ISSUE TITLE
[🐛 Bug]: element.FindElements() is waiting the ImplicitWait time before returning

### ISSUE THREAD

**Issue by mooragor** [SeleniumHQ/selenium#12278]
### What happened?

I want to check if a row in a table does NOT have a 'remove icon', but without waiting for the implicitWait timeout (default at 10 seconds) (because it often won't be there).

From reading around, the way to do this is with FindElements(By...) and then check the size of the list.

Because I'm doing this within a specific row, I'm doing  myelement.FindElements(), rather than driver.FindElements(), but am finding it's waiting the full implicitWait (10s) before returning an empty list. I was expecting it to return immediately.

I've confirmed this by setting the implicitWait down to 3 seconds, now it waits 3s before returning the empty list.
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(3);

### How can we reproduce the issue?

```shell
var rows = driver.FindElements(By.CssSelector("tr.dp-clickable"));
foreach (var row in rows)
{
    // the next line is taking the full ImplicitWait time to complete, but I believe it shouldn't be.
    if (row.FindElements(By.CssSelector("span.glyphicon-remove")).Count < 1) 
        {
```

### Relevant log output

```shell
C# - no selenium logging implemented
```

### Operating System

Windows 10

### Selenium version

C# 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.134 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.9000

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment]
This is one of the main reasons why implicit waits can be a bad choice for synchronization.

Implicit waits are intended to apply to find elements calls as well as find element calls. You would need to turn off implicit waits and turn them back on again, but that gets noisy.
