### ISSUE TITLE
[🚀 Feature]: Support Flutter web pages

### ISSUE THREAD

**Issue by pandoras-toolbox** [SeleniumHQ/selenium#12288]
### Feature and motivation

Currently Selinium cannot be used to automate Flutter web pages because most of the web elements cannot be located with Selenium.

Flutter web apps can be inspected nicely with the official Flutter Inspector. And with Dart programming language the web elements can be found and interacted with. But you have to use Dart, you cannot use Java for example.

The good thing about Selenium is that it can be used with many programming languages.

My suggestion is that Selenium supports locating Flutter web elements and to interact with them.

Is tehre any chance for this?

### Usage example

By using somethings like a FlutterFinder we could find flutter widgets.

**Comment by diemol** [comment]
Please use Appium and https://github.com/appium-userland/appium-flutter-driver for this.

**Comment by pandoras-toolbox** [comment]
I think this works only for Flutter mobile apps but not for Flutter web apps. The more Flutter web apps will be created, the more people will stop using Selenium, and Appium cannot be used for that, only for Flutter mobile apps.

**Comment by diemol** [comment]
Why can't you use Selenium if it is a web app? What errors are you bumping into?

**Comment by pandoras-toolbox** [comment]
Here is an official Flutter web sample: https://gallery.flutter.dev/#/

When you try to locate a web element with Chrome development tools you will see what the problem is.

As far as I understand Flutter renders the page in its very own way so that it resembles more an image. Behind the renderer is a model with all the widgets, but Selenium does not access it, it only sees the rendered output.

Some companies use Flutter for web pages although its mostly used for mobile apps. I need to automate such a web page. I tried to make use of Appium for that Flutter web pages scenario, but I did not find any way.

I am still learning a lot about how Flutter works, but I will try to explain it a bit more tomorrow, as far as I understand it.

**Comment by titusfortner** [comment]
Selenium only works with HTML / DOM. If it doesn't output that, Selenium can't work with it. I believe Flutter created a driver for Appium to work with Native Apps, most likely they would also need to implement something that works for mobile web.

**Comment by pandoras-toolbox** [comment]
There is this: https://github.com/ashwithpoojary98/javaflutterfinder
But I could not connect a web page to the Appium Server, tried it with different Capabilities, always resulted in strange errors, for instance that it cannot find the geckodriver although I use browserName Chrome.
The Appium server might only work with mobile apps and not with browsers on the desktop.

**Comment by pandoras-toolbox** [comment]
Whoever has to automate E2E tests for Flutter web apps is in a very bad situation I think. The only way which seems to work is to use Flutter's native tools for it, which has a lot of drawbacks (long story).

I think the best would be if Selenium would support to automate Flutter web apps directly, meaning without having to use Appium or any special drivers. In my short experience with Appium I think it is far away from the quality of Selenium, a colleage who worked with it in the past confirmed that impression. I would like to rule out any solution requiring Appium to automate Flutter web apps. I also even do not consider Appium being good for automating Flutter mobile apps.

It could work by using the Flutter finders via JavaScript. These finders are in Dart and a test package. This package can be made to be part of the web sources. There is a two-way interoperability of Dart with JavaScript. I have not verified that this part of the idea works. This means that (in theory) the Flutter's own finders can be used with JavaScript and thus from Selenium, how exactly would become clear when doing it.

If Selenium contributers do not want to add this feature then I think someone will do it, because this seems to be the best way for me to automate Flutter web apps on a E2E level, making it work with Selenium directly.

**Comment by titusfortner** [comment]
We'd love to speak with anyone interested in undertaking that initiative.

**Comment by pandoras-toolbox** [comment]
I think I need to walk back from that idea because it seems that only in certain circumstances the Dart code is contained within the web app's code. But usally a Flutter web app seems to contains only JavaScript code.

They [write](https://docs.flutter.dev/platform-integration/web):

> We implemented the core drawing layer completely in Dart and used Dart’s optimized JavaScript compiler to compile the Flutter core and framework along with your application into a single, minified source file that can be deployed to any web server.

So the test automation can only be done with the Dart/Flutter way (which I prefer) or with image-based test automation tools.

**Comment by pandoras-toolbox** [comment]
After I spent more time with Flutter's integration_test package I discovered a lot more of disadvantages compared to Selenium.

I believe that Selenium can automate Flutter web apps in nearly the same way like Flutter does with its integration_test package and with its webdriver package.

If something like the code below is added to the app under tests main Dart file then the app in the browser will contain the JavaScript test code needed to find and interact with widgets. There is no need to access Dart through JavaScript for that purpose, because Flutter converts it to JavaScript, that was a misunderstanding from me.

```
void main() {
  enableFlutterDriverExtension(handler: (request) async {
    return const String.fromEnvironment('DEVICE');
  });
  runApp(const MyApp());
}
```

The Flutter integration tests need a browser webdriver, so it is the same basically like how Selenium works. The driver communicates with the browser in JavaScript or with REST calls I think. If Flutter can pull this off, then it can be solved for Selenium as well I think.

But it would be quite some effort to implement.

The advantages would be many, for example you can code the tests in different programming languages, you can use Selenium Grid and services like Browserstack, you would be able to run tests in parallel and with virtually any framework you want, you would get a test report and it would work well with not too much effort needed to write automated tests.
