### ISSUE TITLE
[🐛 Bug]: selenium-server-*.jar is corrupted

### ISSUE THREAD

**Issue by david-jng** [SeleniumHQ/selenium#12285]
### What happened?

I am using the selenium-server-4.10.0.jar in a project. The console printed an error, that the .jar is not a JAR file. 
I tried to open the .jar-file with 7-zip and received the attache error message.

If I use the .jar file out of the selenium-server-4.10.0.zip, it is working as expected.

The same error happens to the selenium-server-4.11.0-SNAPSHOT.jar.

![image](https://github.com/SeleniumHQ/selenium/assets/41423063/ff6f39c3-5c18-4696-9914-ab1385924b9c)
![image](https://github.com/SeleniumHQ/selenium/assets/41423063/84fe5087-f0a5-4103-84d3-78c6839439c3)

### How can we reproduce the issue?

```shell
Download the highlighted .jar-file and open it with 7-zip.
```

### Relevant log output

```shell
CLASSPATH element <path-to-selenium-server-0.4.10.jar> is not a JAR.
```

### Operating System

Windows

### Selenium version

0.4.10, 0.4.11-snapshot

### What are the browser(s) and version(s) where you see this issue?

Chrome, but not relevant

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 114, but not relevant

**Comment by diemol** [comment]
I know that several websites say that you can extract a jar with 7zip, but in the official [website](https://www.7-zip.org/) `jar` is not under the supported extensions.

I just tried WinRAR and it worked.
