### ISSUE TITLE
Selenium opening Developer-Firefox and crashing when automating.

### ISSUE THREAD

**Issue by Luke-SF** [SeleniumHQ/selenium#1228]
I updated selenium the other day with pip, yet it opens Firefox developer edition instead of the normal Firefox for some reason, and it crashes shortly after:

``
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py",
line 328, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py",
line 454, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", l
ine 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py"
, line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: cross-process JS call fa
iled
Stacktrace:
    at Utils.keyEvent (file:///c:/users/username/appdata/local/temp/tmptx2smx/extens
ions/fxdriver@googlecode.com/components/command-processor.js:9074)
    at Utils.type (file:///c:/users/username/appdata/local/temp/tmptx2smx/extensions
/fxdriver@googlecode.com/components/command-processor.js:9050)
    at WebElement.sendKeysToElement/< (file:///c:/users/username/appdata/local/temp/
tmptx2smx/extensions/fxdriver@googlecode.com/components/command-processor.js:119
99)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///c:/users/username/appda
ta/local/temp/tmptx2smx/extensions/fxdriver@googlecode.com/components/driver-com
ponent.js:621)
``

**Comment by lukeis** [comment]
Selenium isn't tested against the Developer edition of firefox. We do test against the Beta version.

But in the very near future we will be needing to switch to marionette / wires to execute automation against Firefox.

If you'd like to try it out, please download wires: https://github.com/jgraham/wires/releases/tag/v0.4.2
and put it on your system path, like you do for chromedriver.

And then start your python Firefox like this:

    from selenium import webdriver
    driver = webdriver.Firefox(capabilities={'marionette':True})

**Comment by Luke-SF** [comment]
Okay.. but why does Selenium start the experimental developer-Firefox instead of normal Firefox? I changed no setting that I remember that should have changed this.

**Comment by lukeis** [comment]
Because on windows, selenium looks in your Registry keys for the installed firefox location. You may have installed the dev channel last and set it as the default?

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_binary.py#L110-L139

**Comment by lukeis** [comment]
(otherwise it looks in a couple of common locations - https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_binary.py#L162-L169  )
