### ISSUE TITLE
Selenium IDE click fails on pages that include Polymer's platform.js

### ISSUE THREAD

**Issue by mattpr** [SeleniumHQ/selenium#1229]
When testing a page that includes Polymer's platform.js with selenium IDE 2.9.0, click events fail with the following error:

> Unexpected Exception: TypeError: Argument 4 of MouseEvent.initMouseEvent does not implement interface Window.. 

I am guessing that this has to do with a combination of polymer event wrappers combined with how selenium tries to simulate click event.

Example page:  http://geelen.github.io/x-gif/#/http://i.imgur.com/iKXH4E2.gif
## Selenium IDE (2.9.0)

![Selenium IDE Screenshot](http://i.imgur.com/CXywftN.png)
## Firefox breakpoint on exception

![Firefox Screenshot](http://i.imgur.com/XGzsJ5b.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
