### ISSUE TITLE
[🐛 Bug]: Selenium Manager and.NET

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12301]
### What happened?

Unlike other languages, .NET is doing the first part of the location outside of the "driver finder." So the Driver verification class is not distinguishing between the default behavior and what a user might be passing in.

If the user is passing in something incorrect, we need to raise an exception for that, rather than try to remediate it the way we would if the default isn't working.

Also, unlike other languages .NET has you specify the directory the driver is in, not the full path to the file itself. We may want to be more accommodating of this possibility by checking if it is a full path or if it is the directory.

### How can we reproduce the issue?

```shell
var service = ChromeDriverService.CreateDefaultService();
service.DriverServicePath = "definitely/not/a/driver/path.exe";

driver = new ChromeDriver(service);
```

### Relevant log output

oh .NET and logging...

### Operating System

any

### Selenium version

trunk

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

### Are you using Selenium Grid?

no

**Comment by NCLnclNCL** [comment]
use this will working   ChromeDriverService service = ChromeDriverService.CreateDefaultService(@"D:\chromedriver new", "chromedriver.exe");

**Comment by titusfortner** [comment]
Yes, but right now if the driver doesn't exist in that directory, Selenium will ignore it and use the Manager to download a new one, when it should error instead.

**Comment by NCLnclNCL** [comment]
> Yes, but right now if the driver doesn't exist in that directory, Selenium will ignore it and use the Manager to download a new one, when it should error instead.

Yes it is bad

**Comment by titusfortner** [comment]
Fixed with referenced PRs
