### ISSUE TITLE
[🐛 Bug]: Selenium Manager creates incorrect geckodriver subdirectory within the user cache

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#12302]
### What happened?

Selenium Manager creates incorrect geckodriver subdirectory within the user cache. 

While the latest geckodriver being **[geckodriver-v0.33.0-win32.zip](https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win32.zip)** being Windows 32 bit release

![geckodriver33](https://github.com/SeleniumHQ/selenium/assets/26503213/acada606-f972-4c29-93e7-14835668dc55)

 [Selenium Manager](https://www.selenium.dev/blog/2022/introducing-selenium-manager/) creates **win64** subdirectory within `.cache` directory.

![win64](https://github.com/SeleniumHQ/selenium/assets/26503213/8aaa186d-4edb-4458-8c4c-c587e71d52b2)

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Chrome(options=options)
```

### Relevant log output

```shell
Applicable driver not found; attempting to install with Selenium Manager (Beta)
Executing process: C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser firefox --output json --browser-path C:\Program Files\Mozilla Firefox\firefox.exe --debug
Using shell command to find out firefox version
Running command: "wmic datafile where name='C:\\Program Files\\Mozilla Firefox\\firefox.exe' get Version /value"
Output: "\r\r\n\r\r\n\r"
The version of firefox cannot be detected. Trying with latest driver version
Required driver: geckodriver 0.33.0
Running command: "geckodriver --version"
Output: ""
geckodriver 0.33.0 already in the cache
C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
Using driver at: C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
Started executable: `C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe` in a child process with pid: 10308
```

### Operating System

Windows 10 Home

### Selenium version

Python 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 114.0.2 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver through Selenium Manager

### Are you using Selenium Grid?

N/A

**Comment by DanMcNamee42** [comment]
Any idea when that may be fixed?  We don't often fun Firefox tests, but we have some to run now, and this is causing issues.  Thanks!

**Comment by titusfortner** [comment]
@bonigarcia is the way we are grabbing the bit size not working?

**Comment by bonigarcia** [comment]
Many things have changed in Selenium Manager since Selenium 4.10.0. 

@Debanjan-B Can you please update to the latest Selenium Python version (4.14.0) and have a try?

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP.
