### ISSUE TITLE
[🐛 Bug]: Selenium is unable to detect the version of firefox

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#12300]
### What happened?

Selenium generates the following log message:

`The version of firefox cannot be detected. Trying with latest driver version`

but finally opens the Firefox browser.

### How can we reproduce the issue?

```shell
import sys
print ("Python Version: " +sys.version)
print ("Python version: "+str(sys.version_info))
from platform import python_version
print("Python Version: " +python_version())
import selenium
print("Selenium Version: " +selenium.__version__)
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Firefox(options=options)
driver.get("https://www.tripadvisor.com/Attraction_Products-g28922-t21629-zfg21594-Alabama.html")
```

### Relevant log output

```shell
Python Version: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Python version: sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
Python Version: 3.10.10
Selenium Version: 4.10.0
The version of firefox cannot be detected. Trying with latest driver version
```

### Operating System

Windows 10 Home

### Selenium version

Python 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 114.0.2 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver through Selenium Manager

### Are you using Selenium Grid?

N/A

**Comment by Debanjan-B** [comment]
Enabling the logs following [test_logging.py](examples/python/tests/troubleshooting/test_logging.py):
```
from selenium import webdriver
import logging
from selenium.webdriver.firefox.options import Options

log_path = "C:/Users/User/Desktop/My Documents/Python Programs/geckodriverlogs.log"
logger = logging.getLogger('selenium')
logger.setLevel(logging.INFO)
handler = logging.FileHandler(log_path)
logger.addHandler(handler)

logging.getLogger('selenium.webdriver.remote').setLevel(logging.WARN)
logging.getLogger('selenium.webdriver.common').setLevel(logging.DEBUG)
options = Options()
options.binary_location = r'C:\Program Files\Mozilla Firefox\firefox.exe'
driver = webdriver.Firefox(options=options)
driver.get("https://www.tripadvisor.com/Attraction_Products-g28922-t21629-zfg21594-Alabama.html")
```
geckodriverlogs.log:
```
Applicable driver not found; attempting to install with Selenium Manager (Beta)
Executing process: C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser firefox --output json --browser-path C:\Program Files\Mozilla Firefox\firefox.exe --debug
Using shell command to find out firefox version
Running command: "wmic datafile where name='C:\\Program Files\\Mozilla Firefox\\firefox.exe' get Version /value"
Output: "\r\r\n\r\r\n\r"
The version of firefox cannot be detected. Trying with latest driver version
Required driver: geckodriver 0.33.0
Running command: "geckodriver --version"
Output: ""
geckodriver 0.33.0 already in the cache
C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
Using driver at: C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
Started executable: `C:\Users\User\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe` in a child process with pid: 10308
```

**Comment by titusfortner** [comment]
Unlike Chrome, Firefox can operate with the latest version of the driver for many versions.

That said, it indicates the way we are checking version of the executable is not working for this context.
@bonigarcia is it obvious why it can't get the version for this one?

**Comment by Debanjan-B** [comment]
@titusfortner _Firefox can operate with the latest version of the driver for many versions_, agreed. 

Can't say not working for this context, as it does opens the Firefox browser but trace level log shows there are some loopholes which needs to be plugged.

**Comment by bonigarcia** [comment]
This issue happens because Selenium Manager is very sensitive to using back-slash symbols in Windows paths. The command to discover the browser version in Windows internally uses WMIC, which has some very restrictive behavior regarding paths. In your case, @Debanjan-B, you should be able to avoid that log trace by using double quotes in your Firefox path:

```
options.binary_location = r'C:\\Program Files\\Mozilla Firefox\\firefox.exe'
```

Nevertheless, this can be improved in Selenium Manager. In fact, we have already talked about improving it on the Rust side, although the code was pending. So, I have done PR #12304 to enhance the user experience regarding browser paths for the next Selenium release.

**Comment by titusfortner** [comment]
should be addressed by linked PR, and will be available in next release
