### ISSUE TITLE
[🐛 Bug]: Error: Failed to import atoms module

### ISSUE THREAD

**Issue by Proziam** [SeleniumHQ/selenium#12308]
### What happened?

I'm working on a desktop application using Tauri (https://tauri.app) with Svelte (https://svelte.dev/).

If I try to import anything `{By, Builder, etc}` from selenium-webdriver I get the following error: 
```
Error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run `bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js` from the projectroot: Error: Dynamic require of "./atoms/get-attribute.js" is not supported
```

If I try to use require rather than import I run into:
```
ReferenceError: Can't find variable: require
```

In trying to follow the error message's instructions, I installed and ran Bazel which seems to expect workspace setup.

It seems in 2019 there was someone who had an identical error - https://9to5tutorial.com/selenium-webdriver-does-not-work-in-webpack-environment

### How can we reproduce the issue?

```shell
Steps to reproduce:
1. Use `cargo create-tauri-app` to create a new project
2. install `selenium-webdriver`
3. Try to import something from selenium
4. Run app with `cargo tauri dev`
```

### Relevant log output

```shell
Error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run `bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js` from the projectroot: Error: Dynamic require of "./atoms/get-attribute.js" is not supported
```

### Operating System

Ubuntu 22.04 

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

*

### What are the browser driver(s) and version(s) where you see this issue?

*

### Are you using Selenium Grid?

No

**Comment by atultiwaree** [comment]
Any solution ??

**Comment by Proziam** [comment]
No solution, and since I didn't get any response I ended up having to build a sidecar application to handle that side of the functionality. It's a pretty ugly workaround, but it got the job done for my specific use-case at least.

**Comment by titusfortner** [comment]
There are common artifacts built with Bazel and used in the packaging process for each of the languages. I'm not familiar with the projects you are referring to or what exactly they are trying to import, but to get things built, you have to follow the build instructions for the project — https://github.com/SeleniumHQ/selenium/blob/trunk/README.md#requirements

**Comment by Proziam** [comment]
We're using Selenium without issue in a standalone binary, we just aren't able to import it in the context described.

**Comment by titusfortner** [comment]
I don't know what you're trying to import or from where.

This doesn't sound like a bug with the project, but an interesting use case that assumes a different build system than the one Selenium uses. If there is a workaround to it, it seems outside the scope of this project.

**Comment by atultiwaree** [comment]
@titusfortner  and @Proziam  I was trying to bundle executable from nodejs using pkg library of my selenium and nodejs project after build exe on running I get ther error

**Comment by atultiwaree** [comment]
> @titusfortner and @Proziam I was trying to bundle executable from nodejs using pkg library of my selenium and nodejs project after build exe on running I get ther error

Below is my error output


Error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run `bazel build //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js` from the projectroot: Error: Cannot find module './atoms/get-attribute.js'
Require stack:
- C:\snapshot\coolautobet\node_modules\selenium-webdriver\lib\http.js
- C:\snapshot\coolautobet\node_modules\selenium-webdriver\http\index.js
- C:\snapshot\coolautobet\node_modules\selenium-webdriver\index.js
- C:\snapshot\coolautobet\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at requireAtom (C:\snapshot\coolautobet\node_modules\selenium-webdriver\lib\http.js:65:13)
    at Object.<anonymous> (C:\snapshot\coolautobet\node_modules\selenium-webdriver\lib\http.js:37:22)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\snapshot\coolautobet\node_modules\selenium-webdriver\http\index.js:29:17)

**Comment by titusfortner** [comment]
Ah, here's the code generating the error — https://github.com/SeleniumHQ/selenium/blob/selenium-4.12.0/javascript/node/selenium-webdriver/lib/http.js#L55

Looks like you may be able to build the atoms and put them in `./atoms/`?

I don't spend any time in the JS code. @AutomatedTester does it make sense for us to have the Bazel references in the lib code here? This feels like a hack, but several JS devs have seemed to think this is the right way to do it looking at git history.

**Comment by diemol** [comment]
We need to find out how your build environment with Tauri (https://tauri.app/) and Svelte (https://svelte.dev/) consumes dependencies. 

For the general use case, users are doing fine with `npm install` and then regular `import`. However, this can be different in your use case. 

Please figure out how the dependencies are consumed and if you need anything, we'd be happy to help you out in our Slack channel. I will the links to join below.
