### ISSUE TITLE
[🐛 Bug]: unable to create session in version 4.9.0+ 

### ISSUE THREAD

**Issue by amosnothing** [SeleniumHQ/selenium#12303]
### What happened?

The runtime environment and parameters are exactly the same. The grid 4.8.3 version can return normally, but the grid 4.9.0+version cannot.

### How can we reproduce the issue?

```shell
ubuntu 22 + JDK 17 + selenium-server-4.9.0(or higher version)

NODE:
java -XX:ActiveProcessorCount=6 -Dwebdriver.chrome.driver=/data/services/chromedriver -Dwebdriver.chrome.whitelistedIps= -Dwebdriver.chrome.allowedOrigins=* -jar /data/services/selenium-server-4.9.0.jar node --hub http://your_hub_ip:4444 --allow-cors true --override-max-sessions true --session-timeout 120 --log-level FINER --log selenium-node.log --plain-logs true --log-timestamp-format HH:mm:ss.SSS --config ./conf/config.toml --tracing false

config.toml
[node]
detect-drivers = false
[[node.driver-configuration]]
max-sessions = 6
display-name = "Chrome114"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"114\", \"platformName\": \"LINUX\"}"
webdriver-executable = '/data/services/chromedriver'


HUB:
java -Dwebdriver.chrome.driver=/data/services/chromedriver -Dwebdriver.chrome.whitelistedIps= -Dwebdriver.chrome.allowedOrigins=* -jar /data/services/selenium-server-4.9.0.jar hub --log-level FINER --log selenium-hub.log --allow-cors true --tracing false

Then post create new session to http://your_node_ip:4444/session. Enter the grid UI management page and click on the session menu. The Capabilities configuration of the session is displayed as empty JSON ("{}").
```

### Relevant log output

<img width="1131" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/24653016/89465c22-189c-4573-95fd-c00bdddbbeee">

BUT: 4.9.0+version always returns a timeout. 

**All the conditions are the same, except for the different version numbers of the selenium grid.**

### Operating System

ubuntu 22 + JDK 17

### Selenium version

selenium-server-4.9.0.jar

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114

### Are you using Selenium Grid?

selenium-server-4.9.0.jar

**Comment by diemol** [comment]
You are sending a JWP payload, and support for that in Grid was removed in 4.9.0. We have been announcing this for a while https://www.selenium.dev/blog/2022/legacy-protocol-support/
