### ISSUE TITLE
[🚀 Feature]: Add support for clipping screenshots

### ISSUE THREAD

**Issue by ollie-iterators** [SeleniumHQ/selenium#12317]
### Feature and motivation

Clipping screenshots was added to webdriver-bidi in https://github.com/w3c/webdriver-bidi/pull/454

### Usage example

It would allow for clipping screenshots by using coordinates relative to the viewport, or by providing an element, and using its bounding rect as the coordinates to clip

**Comment by titusfortner** [comment]
We're tracking the BiDi work elsewhere now. Thanks.
