### ISSUE TITLE
[🐛 Bug]: `Selenium.Support.StrongNamed` depends on `Selenium.WebDeriver` instead of strong name signed version

### ISSUE THREAD

**Issue by harunurhan** [SeleniumHQ/selenium#12316]
### What happened?

`Selenium.Support.StrongNamed` package (available [here](https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.8.0/selenium-dotnet-strongnamed-4.8.2.zip))depends on `Selenium.WebDeriver` instead of strong name signed version: `Selenium.WebDeriver.StrongNamed`.

Also this may cause build issues when a project references both of them, such as `warning MSB3243: No way to resolve conflict...` since the ``Selenium.WebDeriver` comes with `Selenium.Support.StrongNamed` and  `Selenium.WebDeriver.StrongNamed` might have a name collision.

### How can we reproduce the issue?

```shell
- Download [selenium-dotnet-strongnamed](https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.8.0/selenium-dotnet-strongnamed-4.8.2.zip)
- Unpack `Selenium.Support.StrongNamed.nupkg`
- Inspect `.nuspec` file
- You will see that the package depends on `Selenium.WebDeriver`, not `Selenium.WebDeriver.StrongNamed`
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows

### Selenium version

4.8.2

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by nvborisenko** [comment]
I think we can ship signed assemblies by default, I don't see reason to build different versions. I mean `Selenium.WebDriver` package can be signed with strong name.
