### ISSUE TITLE
[🐛 Bug]: Unable to Close Selenium Instances using .quit() Using all Disk Space

### ISSUE THREAD

**Issue by jakubbester** [SeleniumHQ/selenium#12313]
### What happened?

We have developed a scraping application using Selenium, and have been testing it on our local machines as well as our on Google Cloud Platforms. We have run into a major issue in which we are attempting to .quit() our Selenium session, however it is not working resulting in massive build up of temporary files that end up taking a lot of disk space and crashing the system.

Below, we can see some analytics behind the disk space utilization, and it is constantly growing until we manually go in and delete the files, so as to get the system back up and running after it crashes.

![image](https://github.com/SeleniumHQ/selenium/assets/45968528/c87c93b5-9b80-495a-b4c9-9e9d0433da43)
![3af13aff-a048-4e52-a45b-f86faefd207a](https://github.com/SeleniumHQ/selenium/assets/45968528/55afc8f4-254e-4507-a59d-fdebaa559db5)

### How can we reproduce the issue?

```shell
A code snippet to reproduce the issue and how we're running it can be found above. It is entirely possible we implemented it incorrectly, however we are not sure.
```

### Relevant log output

```shell
Here is some more information on the temporary files that we are receiving.

![image](https://github.com/SeleniumHQ/selenium/assets/45968528/d29f6617-95e4-46a0-85fd-8a0f18027d27)
```

### Operating System

Ubuntu 20.04

### Selenium version

Python 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.198

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 114.0.5735.16

**Comment by diemol** [comment]
You do not have any error control or exception handling in your code, which means that if an unexpected error happens, most likely the browser and the files it creates will stay open. No proper clean up will be done.
