### ISSUE TITLE
[🐛 Bug]: Could not determine server status when attempting to open browser

### ISSUE THREAD

**Issue by jfhahn2** [SeleniumHQ/selenium#12329]
### What happened?

When I try to open a new driver for a Chrome browser in R, I get the following error message:

Could not open chrome browser.
Client error message:
Undefined error in httr call. httr output: Failed to connect to localhost port 4567 after 0 ms: Couldn't connect to server
Check server log for further details.
Warning message:
In rsDriver(browser = "chrome") : Could not determine server status.

I have double checked that my chrome driver and browser are up to date, but am still getting this same error. I tried accessing the server log but there is nothing there.

### How can we reproduce the issue?

```shell
rdriver <- rsDriver(browser = "chrome")
```

### Relevant log output

```shell
> rdriver$server$log()
$stderr
[1] ""

$stdout
[1] ""
```

### Operating System

macOS Ventura 13.4.1

### Selenium version

RSelenium 1.7.9

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.198 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Please report that to the corresponding project.

**Comment by jfhahn2** [comment]
What do you mean by corresponding project?

**Comment by diemol** [comment]
Selenium does not support R. Probably you are using https://github.com/rstudio/webdriver?
