### ISSUE TITLE
[🐛 Bug]: selenium-manager webdriver doesn't support Edge browser version is 114.0.1823.67

### ISSUE THREAD

**Issue by rprakash648** [SeleniumHQ/selenium#12322]
### What happened?

I am using selenium version 4.10.0.0 and recently Edge version updated from 112 to 114 and now getting an error - 
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 112 Current browser version is 114.0.1823.67.

however when i have edge version 112 its working fine.

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Edge()
driver.get('https://www.google.com/')
driver.maximize_window()
```

### Relevant log output

```shell
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 112
Current browser version is 114.0.1823.67 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00007FF6E358E022+60274]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E351EC82+818786]
	(No symbol) [0x00007FF6E319DFAE]
	(No symbol) [0x00007FF6E31CE378]
	(No symbol) [0x00007FF6E31C8D24]
	(No symbol) [0x00007FF6E31C440A]
	(No symbol) [0x00007FF6E3207341]
	(No symbol) [0x00007FF6E31FF343]
	(No symbol) [0x00007FF6E31D1796]
	(No symbol) [0x00007FF6E31D0975]
	(No symbol) [0x00007FF6E31D1F04]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF6E3427167+1678103]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF6E32CEEBD+268397]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E345FE77+36951]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E3457F85+4453]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6E3758163+1318403]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E3526D3C+851740]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E3522DA4+835460]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E3522EFC+835804]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6E3518AD1+793777]
	BaseThreadInitThunk [0x00007FF8363F7614+20]
	RtlUserThreadStart [0x00007FF8383426A1+33]
```

### Operating System

Window10

### Selenium version

Rust

### What are the browser(s) and version(s) where you see this issue?

Edge version 114

### What are the browser driver(s) and version(s) where you see this issue?

Using Selenium Manager

**Comment by diemol** [comment]
Please share the logs after enabling this https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by titusfortner** [comment]
Most likely you have an old version of the driver on your system. Selenium Manager doesn't get used at all if Selenium finds a driver already on your system.

**Comment by rprakash648** [comment]
As I know  Selenium Manager manage the driver self and There is no old driver in my system. when i was using edge browser version 112, getting no error with this code. I am facing an issue with [Edge browser version 114.0.1823.67] getting an error.
I pasted below the whole error.

"C:\Program Files\Python311\python.exe" C:\Users\PycharmProjects\pythonProject\Automation\InTesting\abb.py 
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\pythonProject\Automation\InTesting\abb.py", line 14, in <module>
    driver = webdriver.Edge()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\edge\webdriver.py", line 51, in __init__
    super().__init__(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 112 Current browser version is 114.0.1823.67 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00007FF7D045E022+60274]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03EEC82+818786]
	(No symbol) [0x00007FF7D006DFAE]
	(No symbol) [0x00007FF7D009E378]
	(No symbol) [0x00007FF7D0098D24]
	(No symbol) [0x00007FF7D009440A]
	(No symbol) [0x00007FF7D00D7341]
	(No symbol) [0x00007FF7D00CF343]
	(No symbol) [0x00007FF7D00A1796]
	(No symbol) [0x00007FF7D00A0975]
	(No symbol) [0x00007FF7D00A1F04]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D02F7167+1678103]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D019EEBD+268397]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D032FE77+36951]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D0327F85+4453]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7D0628163+1318403]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F6D3C+851740]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2DA4+835460]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2EFC+835804]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03E8AD1+793777]
	BaseThreadInitThunk [0x00007FF934577614+20]
	RtlUserThreadStart [0x00007FF9355226A1+33]


Process finished with exit code 1

**Comment by diemol** [comment]
> Please share the logs after enabling this https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

Can you please share the logs after enabling this? ⬆️

**Comment by rprakash648** [comment]
```
"C:\Program Files\Python311\python.exe" C:\Users\PycharmProjects\pythonProject\Automation\InTesting\Base.py 
DEBUG:selenium.webdriver.common.service:Started executable: `C:\Users\AppData\Local\Microsoft\WindowsApps\msedgedriver.EXE` in a child process with pid: 2412
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:50333/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "MicrosoftEdge", "pageLoadStrategy": "normal", "ms:edgeOptions": {"extensions": [], "args": []}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:50333
DEBUG:urllib3.connectionpool:http://localhost:50333 "POST /session HTTP/1.1" 500 1711
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=500 | data={"value":{"error":"session not created","message":"session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 112\nCurrent browser version is 114.0.1823.67 with binary path C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","stacktrace":"Backtrace:\n\tGetHandleVerifier [0x00007FF7D045E022+60274]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03EEC82+818786]\n\t(No symbol) [0x00007FF7D006DFAE]\n\t(No symbol) [0x00007FF7D009E378]\n\t(No symbol) [0x00007FF7D0098D24]\n\t(No symbol) [0x00007FF7D009440A]\n\t(No symbol) [0x00007FF7D00D7341]\n\t(No symbol) [0x00007FF7D00CF343]\n\t(No symbol) [0x00007FF7D00A1796]\n\t(No symbol) [0x00007FF7D00A0975]\n\t(No symbol) [0x00007FF7D00A1F04]\n\tMicrosoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D02F7167+1678103]\n\tMicrosoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D019EEBD+268397]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D032FE77+36951]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D0327F85+4453]\n\tMicrosoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7D0628163+1318403]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F6D3C+851740]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2DA4+835460]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2EFC+835804]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03E8AD1+793777]\n\tBaseThreadInitThunk [0x00007FF934577614+20]\n\tRtlUserThreadStart [0x00007FF9355226A1+33]\n"}} | headers=HTTPHeaderDict({'Content-Length': '1711', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\pythonProject\Automation\InTesting\Base.py", line 10, in <module>
    driver = webdriver.Edge()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\edge\webdriver.py", line 51, in __init__
    super().__init__(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 112
Current browser version is 114.0.1823.67 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00007FF7D045E022+60274]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03EEC82+818786]
	(No symbol) [0x00007FF7D006DFAE]
	(No symbol) [0x00007FF7D009E378]
	(No symbol) [0x00007FF7D0098D24]
	(No symbol) [0x00007FF7D009440A]
	(No symbol) [0x00007FF7D00D7341]
	(No symbol) [0x00007FF7D00CF343]
	(No symbol) [0x00007FF7D00A1796]
	(No symbol) [0x00007FF7D00A0975]
	(No symbol) [0x00007FF7D00A1F04]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D02F7167+1678103]
	Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF7D019EEBD+268397]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D032FE77+36951]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D0327F85+4453]
	Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF7D0628163+1318403]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F6D3C+851740]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2DA4+835460]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03F2EFC+835804]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF7D03E8AD1+793777]
	BaseThreadInitThunk [0x00007FF934577614+20]
	RtlUserThreadStart [0x00007FF9355226A1+33]
```

**Comment by diemol** [comment]
Did you share the whole log? We should be seeing the information from the `selenium_manager.py` class, but there is nothing there. 

Either you did not put all the log information or you are using an old Selenium version. What version are you using?

**Comment by rprakash648** [comment]
Yes this is whole log. Currently I am using Selenium version 4.10.0

**Comment by rprakash648** [comment]
Now I got the issue and resolved self. Thank You so much for your quick response and for the guidance.

**Comment by diemol** [comment]
What was the issue?

**Comment by rprakash648** [comment]
I again installed the selenium current version and delete all the previous old files and reboot the system.

**Comment by diemol** [comment]
👍
