### ISSUE TITLE
[🚀 Feature]: Integration of some command in LibreOffice Calc formula

### ISSUE THREAD

**Issue by prrvchr** [SeleniumHQ/selenium#12324]
### Feature and motivation

This is not a feature proposal but just to point out that it is possible thanks to Selenium to control your browser by formulas in a LibreOffice Calc spreadsheet.

### Usage example

If you are under Windows only version 7.x of LibreOffice is supported.
Just install the [OAuth2OOo](https://prrvchr.github.io/OAuth2OOo/) extension...

A small example is available in the OpenOffice forum in: [Driving Firefox with Calc formulas](https://forum.openoffice.org/en/forum/viewtopic.php?t=110202)

**Comment by diemol** [comment]
Thank you, if you have a blog post or something indicating how to do that, please share it here so the rest of the community can see that. For now I will close this because there is nothing actionable.
