### ISSUE TITLE
Selenium IDE pluggins SeLite Run All Favorites error

### ISSUE THREAD

**Issue by Tazz07** [SeleniumHQ/selenium#1232]
Hello, i have some problems about installation of Selenium IDE & some pluggins, on a new machine Windows7, with Firefox 42.0 & Selenium IDE 2.9.0. My first one machine works with no problem, with all plugins i want. I make the same steps for the 2nd one so an error appear.

When i begin selenium, an error poping. I think it's in link with incompatibility of plugins : Favorites & SeLite Run All Favorites error (see linked picture). Perhaps with some recent upgrades of firefox or pluggins, makes appear this conflict or perhaps the order of  set up concerning pluggins. 
Result the option "Run all favorites", use for chain some tests series is not present.
Perhaps i do something wrong, someone can help me ?

For information the error (text):
" There was an unexpected error. Msg: Error: Root folders of parameter file and folderRelativeTo don't match.
Url: chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514, line: 47, column: 1
getRelativePath@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:47:1
getRelativePathToHome@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:73:20
@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:112:32"

![pb selenium module slraf2](https://cloud.githubusercontent.com/assets/15731738/11037969/f823e486-8700-11e5-951e-64a3d2a7ccbf.png)

**Comment by ddavison** [comment]
considering the stacktrace states "selite" all over the place, I am going to close this issue and defer you to the plugin creator: http://selite.github.io/

**Comment by ddavison** [comment]
looks like their repository is here: https://github.com/SeLite/SeLite/issues

**Comment by Tazz07** [comment]
ok so i go in the good place, ty for redirection
