### ISSUE TITLE
[🐛 Bug]: Getting WebDriverException while running the Robot Test scripts 

### ISSUE THREAD

**Issue by SuchismitaPadh** [SeleniumHQ/selenium#12323]
### What happened?

I  am using selenium version 4.9.0 and chrome version is 114 and now i am getting an below error in few of my robot scripts, when i am running the scripts(Robot Framework) -

Setup failed:
WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from no such window
  (Session info: chrome=114.0.5735.199)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0051A813+48355]
	(No symbol) [0x004AC4B1]
	(No symbol) [0x003B5220]
	(No symbol) [0x003A88E2]
	(No symbol) [0x003A7138]
	(No symbol) [0x003A77AA]
	(No symbol) [0x003BEC59]
	(No symbol) [0x003B959A]
	(No symbol) [0x003B9377]
	(No symbol) [0x003B0DDC]
	(No symbol) [0x003B122C]
	(No symbol) [0x003A8B81]
	(No symbol) [0x003A92EC]
	(No symbol) [0x003A8FBD]
    [ Message content over the limit has been removed. ]
	(No symbol) [0x003B03E5]
	(No symbol) [0x003BC668]
	(No symbol) [0x003BF566]
	(No symbol) [0x003A7BC3]
	(No symbol) [0x003BC37A]
	(No symbol) [0x0040CB1F]
	(No symbol) [0x003FA536]
	(No symbol) [0x003D82DC]
	(No symbol) [0x003D93DD]
	GetHandleVerifier [0x0077AABD+2539405]
	GetHandleVerifier [0x007BA78F+2800735]
	GetHandleVerifier [0x007B456C+2775612]
	GetHandleVerifier [0x005A51E0+616112]
	(No symbol) [0x004B5F8C]
	(No symbol) [0x004B2328]
	(No symbol) [0x004B240B]
	(No symbol) [0x004A4FF7]
	BaseThreadInitThunk [0x74B405C9+25]
	RtlGetAppContainerNamedObjectPath [0x770077AD+237]
	RtlGetAppContainerNamedObjectPath [0x7700777D+189]

Below are the combination version . 
 robotframework==6.0.2
 robotframework-pythonlibcore==4.1.2
robotframework-seleniumlibrary==6.1.0

### How can we reproduce the issue?

```shell
Try to install above combination version and execute below robot scripts like to launch an application .

*** Settings ***
Library SeleniumLibrary

*** Variables ***
${Browser} chrome
${URL} [www.google.com](http://www.google.com/) (As of reference added [www.google.com](http://www.google.com/)) we are providing project application url .
*** Test Cases ***
Login Application
[Arguments] ${LoginURL}
Open Browser ${LoginURL} ${Browser} options=add_argument("--ignore-certificate-errors")
Maximize Browser Window
${Title}= Get Title
Log ${Title}
wait until keyword succeeds 50s 10s input text ${Locator for Username} UserName
wait until keyword succeeds 50s 10s input text ${Locator for Password} Password
wait until keyword succeeds 50s 10s click element ${Locator for Login Button}

*** Test Cases ***
launch Browser and open url
Login Application ${URL}
```

### Relevant log output

```shell
Status:	FAIL
Message:	Setup failed:
WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from no such window
  (Session info: chrome=114.0.5735.199)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0051A813+48355]
	(No symbol) [0x004AC4B1]
	(No symbol) [0x003B5220]
	(No symbol) [0x003A88E2]
	(No symbol) [0x003A7138]
	(No symbol) [0x003A77AA]
	(No symbol) [0x003BEC59]
	(No symbol) [0x003B959A]
	(No symbol) [0x003B9377]
	(No symbol) [0x003B0DDC]
	(No symbol) [0x003B122C]
	(No symbol) [0x003A8B81]
	(No symbol) [0x003A92EC]
	(No symbol) [0x003A8FBD]
    [ Message content over the limit has been removed. ]
	(No symbol) [0x003B03E5]
	(No symbol) [0x003BC668]
	(No symbol) [0x003BF566]
	(No symbol) [0x003A7BC3]
	(No symbol) [0x003BC37A]
	(No symbol) [0x0040CB1F]
	(No symbol) [0x003FA536]
	(No symbol) [0x003D82DC]
	(No symbol) [0x003D93DD]
	GetHandleVerifier [0x0077AABD+2539405]
	GetHandleVerifier [0x007BA78F+2800735]
	GetHandleVerifier [0x007B456C+2775612]
	GetHandleVerifier [0x005A51E0+616112]
	(No symbol) [0x004B5F8C]
	(No symbol) [0x004B2328]
	(No symbol) [0x004B240B]
	(No symbol) [0x004A4FF7]
	BaseThreadInitThunk [0x74B405C9+25]
	RtlGetAppContainerNamedObjectPath [0x770077AD+237]
	RtlGetAppContainerNamedObjectPath [0x7700777D+189]
```

### Operating System

Windows 10

### Selenium version

4.9.0

### What are the browser(s) and version(s) where you see this issue?

114

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

### Are you using Selenium Grid?

No

**Comment by SuchismitaPadh** [comment]
Updated comment after adding few more code to reproduce .

**Comment by diemol** [comment]
Can you reproduce this only using Selenium? We cannot troubleshoot another library

**Comment by diemol** [comment]
Closing as we did not get more input.
