### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by brlawrence** [SeleniumHQ/selenium#12338]
### What happened?

I migrated to Java 11 and in Maven I have selenium 4.10.0 which is the stable version. After installing and running I am getting the error Unknown HttpClient factory jdk-http-client
In other posts, I find the solution written as install the maven-shade-plugin, but I am not sure how this is done and how it resolves the issue. Can I get help in getting this issue resolved ?

### How can we reproduce the issue?

```shell
This happens after migration to java 11 and Chrome driver update to 114 version. 
My base class has this option System.setProperty("webdriver.http.factory", "jdk-http-client");
This is where the error happens
```

### Relevant log output

```shell
Unknown HttpClient factory jdk-http-client
```

### Operating System

Windows 10

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 114

**Comment by krmahadevan** [comment]
@brlawrence - Please check if you have this in your dependency https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-http-jdk-client/4.10.0

**Comment by diemol** [comment]
Thanks for triaging, @krmahadevan!

**Comment by brlawrence** [comment]
@krmahadevan Yes it worked ! Thank you so much!
