### ISSUE TITLE
[🐛 Bug]: The unhandledPromptBehavior capability is not working in  Chrome Browser

### ISSUE THREAD

**Issue by Rabindra184** [SeleniumHQ/selenium#12332]
### What happened?

Issue: The Alert prompt is not accepted automatically when I set the setUnhandledPromptBehaviour() to UnexpectedAlertBehaviour.ACCEPT in chrome.

### How can we reproduce the issue?

```shell
Please run the below program to reproduce this issue

Program:
@Test
    public void test(){

        ChromeOptions options=new ChromeOptions();
        options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT);
        driver=new ChromeDriver(options);
        driver.get("https://demo.guru99.com/test/delete_customer.php");
        driver.findElement(By.xpath("//input[@name='submit']")).click();
    }
```

### Relevant log output

```shell
The alert generated is not getting accepted automatically.
```

### Operating System

Mac OS Ventura(13.3.1 (22E261))

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Version 114.0.5735.198 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

Using Selenium Manager to get the driver as I am using latest selenium Version

**Comment by titusfortner** [comment]
The alert does not get accepted or dismissed automatically. 

The unhandled prompt behavior is how the driver should respond when a non-alert action is taken when an alert is present. You still have to take that action (any selenium command will work) to trigger the unhandled prompt condition which will execute the specified behavior.
