### ISSUE TITLE
Bad release?

### ISSUE THREAD

**Issue by lloydwatkin** [SeleniumHQ/selenium#1233]
See error @ https://travis-ci.org/lloydwatkin/jquery.autocomplete/builds/90267460#L227-L229

Version 2.48.2 (https://travis-ci.org/lloydwatkin/jquery.autocomplete/builds/90267460#L114)

**Comment by lukeis** [comment]
relevant bit:

/home/travis/build/lloydwatkin/jquery.autocomplete/node_modules/selenium-webdriver/_base.js:104
        vm.runInContext(opt_srcText, closure, src);
           ^
SyntaxError: Unexpected token )

@jleyba ?

**Comment by jleyba** [comment]
Unsupported version of node (0.10.40).

You need to use at least 0.12.x, but I'd recommend using 4.2.x so you don't have to run with the --harmony flag.

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2480

**Comment by lloydwatkin** [comment]
Ahh thanks for clearing that up!
