### ISSUE TITLE
[🐛 Bug]: Appium node refused to connect to  - Selenium hub

### ISSUE THREAD

**Issue by jacop5676** [SeleniumHQ/selenium#12341]
### What happened?

When I connect Grid to to hub in same machine I get no issues but when I try to add another appium node from another machine I get some issues .

issue on logs from node machine 
  "value": {
    "ready": false,
    "message": "Selenium Grid not ready.",
    "nodes": [
    ]
  }
}

### How can we reproduce the issue?

```shell
java -jar C:\seleniumgrid\selenium-server-4.10.0.jar hub(on hub)

On the Node machine 

appium --config C:\seleniumgrid\appium1.yml
java -jar C:\seleniumgrid\selenium-server-4.10.0.jar node --config C:\seleniumgrid\node1.toml

Toml file ==

[server]
port = 6065

 

[node]
detect-drivers = false

 

[relay]
url = "http://hubUrl:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"windows\", \"appium:automationName\": \"windows\"}"
]


Yaml file= 
server:
  port: 4723
  use-drivers:
    - appium-windows-driver
```

### Relevant log output

```shell
C:\seleniumgrid>java -jar C:\seleniumgrid\selenium-server-4.10.0.jar node --config C:\seleniumgrid\node2.toml
16:28:02.749 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
16:28:02.757 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
16:28:03.026 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://0.0.0.0:4442 and tcp://0.0.0.0:4443
16:28:03.105 INFO [UnboundZmqEventBus.<init>] - Sockets created
16:28:04.112 INFO [UnboundZmqEventBus.<init>] - Event bus ready
16:28:04.382 INFO [NodeServer.createHandlers] - Reporting self as: http://1---------:
16:28:04.463 INFO [NodeOptions.getSessionFactories] - Detected 2 available processors
16:28:04.489 INFO [RelayOptions.getSessionFactories] - Adding relay configs for http://1---------:4733
16:28:04.497 INFO [RelayOptions.lambda$getSessionFactories$1] - Mapping Capabilities {appium:automationName: windows, platformName: windows}, 1 times
16:28:04.522 INFO [Node.<init>] - Binding additional locator mechanisms: relative
16:28:04.768 INFO [NodeServer$1.start] - Starting registration process for Node http://1------:6065
16:28:04.769 INFO [NodeServer.execute] - Started Selenium node 4.10.0 (revision c14d967899): http://1-------:6065
16:28:06.146 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://1-----------:4733/status. java.net.ConnectException: Connection refused: no further information: /1--------:4733
16:28:06.148 ERROR [NodeServer$1.lambda$start$1] - Node is not alive: http://1--------- is DOWN
16:28:17.156 WARN [RelaySessionFactory.isServiceUp] - Error checking service status http://1---------:4733/status.
```

### Operating System

Windows10

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

No Browser

### What are the browser driver(s) and version(s) where you see this issue?

Node connection issue 

### Are you using Selenium Grid?

4.10.0

**Comment by diemol** [comment]
```
[relay]
url = "http://hubUrl:4723"
```

Why are you using the Hub url here? You need the url of the Appium server. If you have more questions, I will leave some links below/

**Comment by jacop5676** [comment]
Then how do I connect my appium node to the hub then  ?

**Comment by diemol** [comment]
You connect it to the Node, and the Node to the Hub

**Comment by jacop5676** [comment]
but I am doing that from node machine not hub machine . if I need to use node url here how do I give command to my node machine to connect hub then .

**Comment by diemol** [comment]
Relay section needs to be like the docs https://www.selenium.dev/documentation/grid/configuration/toml_options/#relaying-commands-to-a-service-endpoint-that-supports-webdriver and the server section needs to have the information from the host where the Node runs. 

Please ask more questions on the links above.

**Comment by jacop5676** [comment]
I have put that in the one of the links above but for some reason I dont see my conversation so I am putting here as well .

Hi guys we are using Selenium 4 , we are trying add a node to Selenium hub from different machine. We are having connection issue. When I am adding node on the same machine with hub I am having no issues. I am only getting issue when node and hub on different machines. I use toml and yaml files to start grid and connect the node as below.

TOML FILE:

[server]
port = 5556

[node]
detect-drivers = false

[relay]
url = "http://localhost:4733"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"windows\", \"appium:automationName\": \"windows\"}"
]


YAML FILE :

server:
  port: 4733
  use-drivers:
    - appium-windows-driver

Here are my steps to do set up node 

1) java -jar C:\seleniumgrid\selenium-server-4.10.0.jar hub
2) appium --config C:\seleniumgrid\appium1.yml
3) java -jar C:\seleniumgrid\selenium-server-4.10.0.jar node --config C:\seleniumgrid\node1.toml

Please advise what I am doing wrong. Based on the suggestion on the selenium ticket I opened (https://github.com/SeleniumHQ/selenium/issues/12341), I am getting confused about the part which says "  server section needs to have the information from the host where the Node runs." How do I add host information into server section.

**Comment by diemol** [comment]
Join the slack channel and we can help you there.
