### ISSUE TITLE
[🐛 Bug]: Grid closeed not wrigh, when click close button just close the remot desk page,but not disconnect the vnc.

### ISSUE THREAD

**Issue by flowclouds** [SeleniumHQ/selenium#12358]
### What happened?

when click close button， just close the remot desk page,but not disconnect the vnc.

### How can we reproduce the issue?

```shell
1.connect remot desk window over grid session page.
2.open chrome develped tools,watch the network tab.
3.you can see new request over grid.
4.click close button.
5.you can see always request over grid vnc.
```

### Relevant log output

```shell
blank
```

### Operating System

linux

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

chrome 111

### What are the browser driver(s) and version(s) where you see this issue?

use grid docker

### Are you using Selenium Grid?

4.8.3

**Comment by diemol** [comment]
Does this still happen in 4.10.0?

**Comment by flowclouds** [comment]
ofcourse, i test it also in 4.10.0,  appear it the same bug.

**Comment by flowclouds** [comment]
> Does this still happen in 4.10.0?


ofcourse, i test it also in 4.10.0, appear the same bug.

**Comment by titusfortner** [comment]
@diemol I don't understand this one, is there something we need to do for it?

**Comment by VietND96** [comment]
I guess the user wants to point to the session NoVNC live preview. He opened the session live preview, and after that he closed it. He expected the request would be finished when clicking close button, but actually it was still not finished even after the session ended.
![image](https://github.com/SeleniumHQ/selenium/assets/23253546/4683f580-0a1d-44bd-95cc-41b87870a772)

**Comment by diemol** [comment]
It seems the WebSocket that connects to the noVNC instance is not closed when the user closes the window or when the session stops. This is something that needs to be checked and solved on the UI.
