### ISSUE TITLE
[🚀 Feature]: Selenium 4 Grid config: Add ability to retrieve lists of tables instead of flattened lists

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#12357]
### Feature and motivation

The Grid [Config](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/config/Config.java) interface provides a `getAll` method that returns all of the settings associated with the specified section/option coordinate. If the specified coordinate returns multiple matches, all of the settings from all of matching option instances are combined into a flat list of associated settings. For example, if a Grid configuration defines multiple `node.driver-configuration` options, all of the settings from all of specified drivers will be returned in a flat list. By convention, the batch of settings for each driver are sorted ASCII-betically, which currently places the `display-name` setting at the head of each setting group. However, these settings must then be extracted from the flat list into a batch that once again only applies to the one specific driver.

Using the `display-name` setting as a record delimiter is risky, because a completely valid update could easily add another setting that sorts earlier in the collection. Access to the settings for each driver should not be vulnerable to failures of this sort. I'm sure there are many ways to implement a more robust method for extracting each group of settings.

* Add a specific record delimiter to the combined list of settings. This minor revision to the list structure would facilitate reliable retrieval of the settings for each driver, regardless of changes to the composition of the groups themselves.
* Add a specific `getArray` method specifically returning a list of lists, with each item containing the settings for a single driver. Depending on the approach, this revision could be quite complex, or it could simple be a convenient way for clients to acquire the groups of driver-specific settings without needing to deal with the delimiters themselves.
* Add a scanner or iterator to extract the individual settings groups. This is less convenient than providing the driver settings groups as a collection.

To minimize effort and risk, I suggest a combination of the first and second options. The method to retrieve the list of lists could be implemented as a default method in the **Config** interface; the existing implementation of **Config** would require only minor revisions.

### Usage example

The benefit of this feature is primarily internal to the Selenium 4 Grid implementation. The community would benefit from the reduction of risk that Grid installation get broken by seemingly minor updates to supported driver settings.

**Comment by diemol** [comment]
I understand the concern how the configuration is read. And these days we are very short of time and folks who can contribute to the project. Unless you help us with a concrete code change, it'll be challenging for us to get to a place where we will have time to rework how the configuration is read.

**Comment by sbabcoc** [comment]
@diemol I'll be happy to help. I have a [PR](https://github.com/krmahadevan/selenium/pull/1#discussion_r1262134238) in progress already in the same area and will gladly tackle this issue next.

**Comment by diemol** [comment]
@sbabcoc your PR was merged, can this be closed?

**Comment by sbabcoc** [comment]
@diemol My PR addressed the first point, but the `getArray` method has not yet been added. Should I assemble a PR that adds this interface?

**Comment by diemol** [comment]
Sure, if you believe that is needed, please raise a PR.

**Comment by sbabcoc** [comment]
https://github.com/SeleniumHQ/selenium/pull/12703/files

**Comment by diemol** [comment]
Closed via #12703, thank you @sbabcoc.
