### ISSUE TITLE
[🐛 Bug]: Docker: Setting container hostname breaks Node to child networking

### ISSUE THREAD

**Issue by mooreja-zia** [SeleniumHQ/selenium#12359]
### What happened?

Setting a node-docker container's hostname in a docker-compose.yml file appears to break the lookup of container info that is used to determine what network the node container is part of, and the child containers are created in the default network instead.

[These lines appear to be the issue](https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/grid/node/docker/DockerOptions.java#L147-L151)

This results in the Node container being unable to communicate with the children as they're not on the same Docker network. Strangely, this doesn't throw an error - it instead attempts to connect to the container using http://127.0.0.1:12345 (where 12345 is a randomly assigned port) for 60 seconds before timing out.

### How can we reproduce the issue?

```shell
version: '3'

services:
  selenium-hub:
    image: selenium/hub:latest
    hostname: selenium-hub
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    logging:
      driver: local

  selenium-node:
    image: selenium/node-docker:latest
    hostname: selenium-node
    restart: always
    volumes:
      - ./assets:/opt/selenium/assets
      - ./selenium-config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    logging:
      driver: local

networks:
  default:
    name: test_network
```

### Relevant log output

```shell
14:19:20.441 INFO [DockerSessionFactory.apply] - Creating container, mapping container port 4444 to 24712
14:19:20.484 INFO [Container.<init>] - Created container a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90
14:19:20.485 INFO [Container.start] - Starting container a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90
14:19:20.899 INFO [Container.inspect] - Inspecting container a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90
14:19:20.960 INFO [DockerSessionFactory.apply] - Waiting for server to start (container id: a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90, url http://127.0.0.1:24712/wd/hub)
14:20:21.167 INFO [Container.stop] - Stopping container a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90
14:20:25.404 WARN [DockerSessionFactory.apply] - Unable to connect to docker server (container id: a0e572c1774bbab811a3a4ab3924ed5626704dae19433f184cd9462aa94b5a90)
14:20:25.404 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to connect to docker server. Stopping container: Expected condition failed: waiting for org.openqa.selenium.grid.node.docker.DockerSessionFactory$$Lambda$705/0x0000000840347c40@23e27b57 (tried for 60 second(s) with 500 milliseconds interval)
```

### Operating System

Ubuntu 22.04.2

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

4.10.0

**Comment by diemol** [comment]
Why do you need to set the host name in the container?

**Comment by mooreja-zia** [comment]
I believe that we were using a hostname because another container in our stack required the hostname set, so someone manually set the hostname for all containers. It works correctly if we remove the hostname from this container, so that's what we'll do.

If this is the only way for Selenium node to work, then it may be worth just adding that to some documentation somewhere to avoid others running into the same issue.

**Comment by krmahadevan** [comment]
@mooreja-zia - Perhaps you could raise a PR against https://github.com/SeleniumHQ/docker-selenium enriching the documentation based on your experience ?

**Comment by diemol** [comment]
I will close this, and we will have this issue as documentation. In any case, we would be happy to get a PR for the Docker Selenium project.
