### ISSUE TITLE
[🐛 Bug]: unable to use multiple ports on different machines

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#12350]
### What happened?

We are using Selenium Grid 4.10 with hub and nodes functionalities.
On the server default ports has been used.
On some machines default ports (5555) are used and everything works fine :)
On one machine we want to use different ports for different test users, but when the node send the registering request to the hub but hub dose'nt respond to the request.
Many commands/different ports has been tested without any success. According to documentaion we shoud use this:
 java  -jar selenium-server-4.10.0.jar  node --detect-drivers True --publish-events tcp://<hub_ip>:4442 --subscribe-events tcp://<hub_ip>:4443 --port 7777
But the same command works without port or with port 5555 (default port)
Is it possible to use different ports on anaother machine?
Many thanks in advance

### How can we reproduce the issue?

```shell
On the hub server:
C:\Tools\jdk-20\bin\java -jar C:\Tools\SeleniumGrid\selenium-server-4.10.0.jar hub --newsession-threadpool-size 30 --log C:/Tools/SeleniumGrid/gridHubLog.log --log-level "CONFIG"

On the node:
java  -jar selenium-server-4.10.0.jar  node --detect-drivers True --publish-events tcp://<hub_ip>:4442 --subscribe-events tcp://<hub_ip>:4443 --port 7777 (or any other port)
```

### Relevant log output

```shell
09:45:48.508 INFO [NodeServer$1.start] - Starting registration process for Node http://x.x.x.x:7777
09:45:48.508 INFO [NodeServer.execute] - Started Selenium node 4.10.0 (revision c14d967899): http://x.x.x.x:7777
09:45:48.524 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:45:58.553 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:08.562 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:18.577 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:28.609 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:38.630 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:48.643 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:46:58.663 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:47:08.686 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:47:18.709 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
09:47:28.720 INFO [NodeServer$1.lambda$start$1] - Sending registration event...
```

### Operating System

Windows 10/11

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome/Edge

### What are the browser driver(s) and version(s) where you see this issue?

latest chromedriver and  msedgedriver

### Are you using Selenium Grid?

4.10.0

**Comment by titusfortner** [comment]
What is the network policy. Are you sure that port is open for external connections?

**Comment by ghost** [comment]
Hi,
No. The port is not open but I didn't open the default port either. It works for port 5555 but   not the other port 7777.  
![image](https://github.com/SeleniumHQ/selenium/assets/139330445/0ff51a7e-d2ea-4e19-bf18-7d4964c327ab)

**Comment by diemol** [comment]
You need to check with the folks who manage the network policies on the machines you are using, there is not much we can do to fix that in Grid.
