### ISSUE TITLE
[🐛 Bug]: SE_CACHE_PATH doesn't work as documented

### ISSUE THREAD

**Issue by TWiStErRob** [SeleniumHQ/selenium#12383]
### What happened?

https://www.selenium.dev/documentation/selenium_manager/ shows `SE_CACHE_PATH` as a possible override.
I set it in global Windows environment variables, and locally on the `Test` task in Gradle too. Neither takes effect:
```
2023-07-19T13:26:51,624 DEBUG [Test worker] org.openqa.selenium.manager.SeleniumManager(SeleniumManager.java:103) Executing Process: [C:\Users\TWiStEr\AppData\Local\Temp\selenium-manager594205563192960017222114206782450930\selenium-manager.exe, --browser, chrome, --output, json, --debug]
```
will always create `c:\Users\<me>\.cache\selenium\selenium-manager.json` and `chromedriver` folders.

### How can we reproduce the issue?

Unless I'm missing some Rust magic, these lines calculate the folder:

https://github.com/SeleniumHQ/selenium/blob/selenium-4.10.0/rust/src/files.rs#L147-L159

https://github.com/SeleniumHQ/selenium/blob/c14d9678990942b93cb421c5567d0da7fb29c7bd/rust/src/files.rs#L147-L159

and it's all hard-coded.

### Relevant log output

```shell
N/A could find some lines if relevant.
```

### Operating System

Windows 10 x64

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

auto

### Are you using Selenium Grid?

no

**Comment by bonigarcia** [comment]
That configuration flag (`SE_CACHE_PATH`) is still not available, sorry. It is [planned](https://github.com/SeleniumHQ/selenium/issues/11688), but it is not yet implemented. Also, it is on the top of my priorities to update that documentation page.

**Comment by titusfortner** [comment]
Hmm, I would have sworn I left a comment on this issue... Are there 2 issues floating around? I already removed the line of documentation for clarity.

**Comment by TWiStErRob** [comment]
Even with a release going out 2 days ago, the line is still in the docs table.

Note: instead of removing the line, maybe you want to link to the issue, so people can upvote it?

**Comment by titusfortner** [comment]
Oh, it was an issue for a different not-yet-implemented feature that I commented on and removed from docs (`SE_DRIVER_MIRROR`) that would explain things. Boni will get to it. Thanks.

**Comment by bonigarcia** [comment]
The [Selenium Manager page](https://www.selenium.dev/documentation/selenium_manager/) is fixed now. Besides, I plan to update and improve this content soon.
