### ISSUE TITLE
[🚀 Feature]: Run tests on Mac in CI

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12397]
### Feature and motivation

Something (maybe Ruby) needs to run on Mac. We don't have any coverage for Safari or for Selenium Manager actually working properly on Mac.

I happened to hit a selenium manager bug trying to do something before the upcoming release; we need CI to catch this.

### Usage example

n/a

**Comment by karenhernandeze** [comment]
Can i work in this?

**Comment by titusfortner** [comment]
Sure.
