### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by gymshoe** [SeleniumHQ/selenium#12392]
### What happened?

I was previously using ChromeDriver 113.0.5672.63 (downloaded on to my computer) with Chrome and had no problems using Selenium 4.2.
When Chrome auto-updated (now: 115.0.5790.98), ChromeDriver no longer matched.  Based on the new "Chrome for Testing" scheme and lack of ChromeDriver v115 download-ability, I switched to using the Selenium Manager to auto-load the appropriate ChromeDriver: (https://stackoverflow.com/questions/76724939/there-is-no-such-driver-by-url-https-chromedriver-storage-googleapis-com-lates/76725006#76725006).  This required me to update my Selenium to 4.10 (which went without problems using Anaconda).

Now when I run `driver = webdriver.Chrome()`, I get the following error:

> Message: Unable to obtain chromedriver using Selenium Manager; Message: **Unable to obtain working Selenium Manager binary**; /Users/djs21/opt/anaconda3/envs/pyBot/lib/python3.9/site-packages/selenium/webdriver/common/macos/selenium-manager
> ; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

I can see why the program MIGHT not be finding any Selenium Manager, because my directory structure does not match what it is searching for:
Specifically, if I check my directory structure, 
this DOES NOT exist: .../selenium/webdriver/common/macos/selenium-manager.py
(there is no macos subdirectory at all...)
but this DOES exist:  .../selenium/webdriver/common/selenium-manager.py
(Although this isn't the selenium manager binary, just the .py file....)

### How can we reproduce the issue?

```shell
{on a Mac M1 processor with MacOS}

from selenium import webdriver
driver = webdriver.Chrome()
```

### Relevant log output

```shell
Message: Unable to obtain chromedriver using Selenium Manager; Message: Unable to obtain working Selenium Manager binary; /Users/djs21/opt/anaconda3/envs/pyBot/lib/python3.9/site-packages/selenium/webdriver/common/macos/selenium-manager
; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

(MacOS 12.6.2, ARM-64)

### Selenium version

python 3.9.13; selenium 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115.0.5790.98

### What are the browser driver(s) and version(s) where you see this issue?

theoretically ChromeDriver 115.0.5790 (but the ChromeDriver is never found)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Please update to latest Selenium and set `SE_MANAGER_PATH` environment variable to the location of your selenium manager executable.
