### ISSUE TITLE
[🐛 Bug]: Latest Chromedriver version issue

### ISSUE THREAD

**Issue by brennacodes** [SeleniumHQ/selenium#12390]
### What happened?

**System:** Mac M1 Pro / Ventura 13.3.1 (a)

**Framework:** Ruby 3.2.2, Rails 7.0.6

**Chrome version:** 115.0.5790.98 

**Selenium version**: 4.10.0
**Webdriver version**: 5.2.0

# **Issue:** 
Rspec system tests running with Selenium are failing. Webdriver is unable to locate the latest version. Below is the Webdriver error:
```ruby
     Webdrivers::VersionError:
       Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
     # ./spec/rails_helper.rb:102:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Webdrivers::NetworkError:
     #   Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
     #   ./spec/rails_helper.rb:102:in `block (2 levels) in <top (required)>'
```

It seems like the latest version (115.0.5790) isn't available at the [index](https://chromedriver.storage.googleapis.com/index.html) where Webdriver is looking for it.

An issue has already been submitted to chromedriver maintainers [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4508).

# **Temporary fix**: 
Uninstall Chrome. Reinstall older Chrome version.

<img width="1656" alt="Screenshot 2023-07-20 at 12 21 49 PM" src="https://github.com/SeleniumHQ/selenium/assets/98294995/82cf5b0a-c05f-4c06-9c43-97b0a4e0ad1c">

### How can we reproduce the issue?

```shell
On Mac Ventura, using the latest versions of Selenium, Ruby, Rails, Chrome broswer, run an RSpec system test that depends on Selenium. The test should fail.
```

### Relevant log output

```shell
Webdrivers::VersionError:
       Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
     # ./spec/rails_helper.rb:102:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Webdrivers::NetworkError:
     #   Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
     #   ./spec/rails_helper.rb:102:in `block (2 levels) in <top (required)>'
```

### Operating System

Mac M1 Ventura 13.3.1 (a)

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115.0.5790

### What are the browser driver(s) and version(s) where you see this issue?

Chromium 115.0.5790.98

### Are you using Selenium Grid?

no(?)

**Comment by titusfortner** [comment]
Hi @brennacodes 
This is a webdrivers gem issue and we've been discussing it here - https://github.com/titusfortner/webdrivers/issues/247
Thanks.
