### ISSUE TITLE
[🐛 Bug]: Basic Auth not working on child windows

### ISSUE THREAD

**Issue by iamsarathbaskaran** [SeleniumHQ/selenium#12396]
### What happened?

Below my scenario
1. Launch application url on Chrome (can use edge too)
2. Authentication with windows credential
3. Click on one of the menu link
4. Child window opens for the sub menu
5. Authenticate with windows crednential

I tried the Selenium Basic Auth and it successfully bypassed the basic auth on main window, but basic auth prompting on child window. Below the code to reproduce the issue.

### How can we reproduce the issue?

```shell
driver = new ChromeDriver();

            NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
            {
                UriMatcher = (d)=>true,
                Credentials = new PasswordCredentials("admin", "admin")
            };

            INetwork networkInterceptor = driver.Manage().Network;
            networkInterceptor.AddAuthenticationHandler(handler);
            networkInterceptor.StartMonitoring();

            driver.Navigate().GoToUrl("http://the-internet.herokuapp.com/");

            Actions act = new Actions(driver);
            act.KeyDown(Keys.Shift).Click(BasicAuthLink).KeyUp(Keys.Shift).Build().Perform();
```

### Relevant log output

```shell
The page doesn't load as the Authentication has not happened
```

### Operating System

Windows 10

### Selenium version

C# Selenium 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 114.0.5735.9000 (think is happening on any version)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 114.0.5735.9000

### Are you using Selenium Grid?

4.10.0

**Comment by titusfortner** [comment]
By design the network module is encapsulated by the browser context, which means a new window needs a new handler.
https://w3c.github.io/webdriver-bidi/#type-network-BaseParameters

**Comment by iamsarathbaskaran** [comment]
Thanks for quick response. Its the same driver instance that has second window opened. Also I could see the authentication details on the driver when switch to the new window.

And I tried open the basic auth once on the main driver and navigate to the url again and then when I open the basic auth link on new window it works. Why is it not working on the first attempt is the issue.

           public void BasicAuthNewWindow()
           {
           var driver = new ChromeDriver();
            NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
            {
                UriMatcher = (d)=>true,
                Credentials = new PasswordCredentials("admin", "admin")
            };

            INetwork networkInterceptor = driver.Manage().Network;
            networkInterceptor.AddAuthenticationHandler(handler);
            networkInterceptor.StartMonitoring();

            driver.Navigate().GoToUrl("http://the-internet.herokuapp.com/");

            BasicAuthLink.Click();
            Thread.Sleep(1000);
            driver.Navigate().Back();
            //driver.Navigate().GoToUrl("http://the-internet.herokuapp.com/");
            Thread.Sleep(2000);
            Actions act = new Actions(driver);
            act.KeyDown(Keys.Shift).Click(BasicAuthLink).KeyUp(Keys.Shift).Build().Perform();
            }

            public IWebElement BasicAuthLink => driver?.FindElement(By.LinkText("Basic Auth"));

**Comment by titusfortner** [comment]
The driver instance doesn't matter. When you register the handler it is assigned to the current browser context. Switching to a different window or frame changes the context and the original handler won't work.

I'm also not sure how it works if you navigate somewhere that doesn't require auth and you use `UriMatcher = (d)=>true` don't have time to dig into it right now, but based on what I've said does the behavior you are seeing make sense?

**Comment by iamsarathbaskaran** [comment]
No worries, can understand the issue and limitations on selenium basic auth.
