### ISSUE TITLE
[🐛 Bug]: There seems to be some confusion in the ChromiumDriver when checking the CDP version.

### ISSUE THREAD

**Issue by 666asd** [SeleniumHQ/selenium#12406]
### What happened?

In the [ChromiumDriver.java](https://github.com/SeleniumHQ/selenium/blob/2879d3e0a66787b5500360c5b39a42aab8778089/java/src/org/openqa/selenium/chromium/ChromiumDriver.java#L162) file of Selenium, the check for the CDP version is performed using the `originalCapabilities`, while the logging statement utilizes the `capabilities`.

### How can we reproduce the issue?

I'm unsure about the intended usage of either `originalCapabilities` or `capabilities` in this specific context of checking the CDP version in ChromiumDriver. However, if you wish to specify the version of selenium-devtools by specifying the `BrowserVersion` in `capabilities`, you may achieve that.

### Relevant log output

```shell
七月 24, 2023 4:20:06 下午 org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
警告: Unable to find CDP implementation matching 115
七月 24, 2023 4:20:07 下午 org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
警告: Unable to find version of CDP to use for 110. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.8.1` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
```

### Operating System

all

### Selenium version

java

### What are the browser(s) and version(s) where you see this issue?

all

### What are the browser driver(s) and version(s) where you see this issue?

all

**Comment by diemol** [comment]
The content is the same for the code purpose. I made an update to use the same variable.
