### ISSUE TITLE
[🐛 Bug]: wpewebkit and webkitgtk pass `desired_capabilities` to super which will never work.

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#12408]
### What happened?

I don't think instantiating any of these `Webdriver` instances for both:

 - `wpewebkit`
 - `webkitGTK`

Has been working for a while on the grounds of:

 * Selenium Manager exploding
 * They are passing `desired_capabilities=` to the `RemoteWebDriver`.

### How can we reproduce the issue?

```shell
from selenium.webdriver import WebKitGTK

driver = WebKitGTK()
```
```


### Relevant log output

```shell
NoSuchDriverException: Message: Unable to obtain WebKitWebDriver using Selenium Manager; Message: Unsuccessful command executed: /home/${USER}/.local/lib/python3.8/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MiniBrowser --output json.
Invalid browser name: MiniBrowser
```

### Operating System

Ubuntu 20.04

### Selenium version

4.10

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by titusfortner** [comment]
I don't think these are general purpose browsers/drivers that are needed beyond the people developing these tools?
I think rather than just deleting them, can we create a super basic project, put it [here](https://github.com/seleniumhq-community) with just these classes in them, do one release and then slap a README on it that says it's looking for a maintainer?

**Comment by symonk** [comment]
@diemol I have no scope to look at this before 4.12 I think - it's been broken for a long time already so happy to drop the milestone on it, I am busy after work for a few days

**Comment by diemol** [comment]
No worries, @symonk. Glad you are back 🤗

**Comment by titusfortner** [comment]
I think we just had a PR updating this, so I'm closing it.
