### ISSUE TITLE
[🐛 Bug]: javascript error: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by oldwizard1010** [SeleniumHQ/selenium#12415]
### What happened?

I updated chromium to 115 version, and my old scripts, using driver.find_element(By.XPATH, ...)  no longer work 
(driver.find_element(By.ID, ...) still works)

### How can we reproduce the issue?

```shell
install python selenium with chromium 114+
try using driver.find_element(By.XPATH, ...) or driver.find_element(By.CSS_SELECTOR, ...)
```

### Relevant log output

```shell
Message: javascript error: Object.hasOwn is not a function
  (Session info: chrome=115.0.5790.102)
```

### Operating System

Arch Linux

### Selenium version

Python 3.11.3, selenium==4.10.0

### What are the browser(s) and version(s) where you see this issue?

chromium 114, chromium 115, chromium 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 115.0.5790.102

**Comment by titusfortner** [comment]
Duplicate of #12078 

Need to open a ticket with chromedriver, but they'll also want to see something they can reproduce.
