### ISSUE TITLE
[Grid Bug]: Can not delete Session with grid API

### ISSUE THREAD

**Issue by pppppino** [SeleniumHQ/selenium#12420]
### What happened?

My selenium grid(4.10.0) status:

<img width="500" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/129264630/3829b310-2be9-4186-981b-c9ce7ef79823">

Then I try to call 
`cURL --request DELETE 'http://10.100.64.248:5000/se/grid/node/session/8d683eca-103e-456b-a39d-bd247c05ed66' --header 'X-REGISTRATION-SECRET;'`

I got a response:
```
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (DELETE) \u002fse\u002fgrid\u002fnode\u002fsession\u002f8d683eca-103e-456b-a39d-bd247c05ed66",
    "stacktrace": ""
  }
}
```

So why can't delete session with the grid API

### How can we reproduce the issue?

```shell
Relay
```

### Relevant log output

```shell
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (DELETE) \u002fse\u002fgrid\u002fnode\u002fsession\u002f8d683eca-103e-456b-a39d-bd247c05ed66",
    "stacktrace": ""
  }
}
```

### Operating System

win10

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

Relay -Appium2.0(windows2.9.1)

### What are the browser driver(s) and version(s) where you see this issue?

Relay

### Are you using Selenium Grid?

Yes

**Comment by diemol** [comment]
You are using the Node endpoint to delete sessions. If you want to do that through the Hub/Router, you just need to do a `DELETE` on `http://10.100.64.248:5000/session/8d683eca-103e-456b-a39d-bd247c05ed66`.
