### ISSUE TITLE
[🐛 Bug]: ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### ISSUE THREAD

**Issue by bwomsm1** [SeleniumHQ/selenium#12447]
### What happened?

System:
webdriver_manager == 4.0.0 (latest)
Chrome driver == 115.0.5790.110 (latest)
Windows 11 & 10
Description:
webdriver_manager can't automatically pull the latest chrome driver and it raises this error

ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### How can we reproduce the issue?

```shell
chrome_options = Options()
            chrome_options.add_argument('--log-level=3')
            chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
            driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
            driver.get("https://www.youtube.com/")
```

### Relevant log output

```shell
File "c:\Users\malak\Desktop\Projects\Python\YoutubeController\src\YouTubeController\youtubecontroller.py", line 53, in __setup
  driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 32, in install
  driver_path = self._get_driver_path(self.driver)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
  driver_version = driver.get_version()
                   ^^^^^^^^^^^^^^^^^^^^
File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 40, in get_version
  return self.get_latest_release_version()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 74, in get_latest_release_version
  validate_response(resp)
File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\utils.py", line 80, in validate_response
  raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
```

### Operating System

Mac OS

### Selenium version

python  4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 115

### Are you using Selenium Grid?

No

**Comment by Alex-J-W** [comment]
Hello @bwomsm1 ,
the webdriver for version 115.0.5790.110 is not build yet, as can be seen here:
https://googlechromelabs.github.io/chrome-for-testing/

I ran into the same problem and the solution, i guess, would be to either wait or use a older version

**Comment by bwomsm1** [comment]
Thanks for the response @Alex-J-W , the thing is that my computer did a force update to Chrome 115.

Do you know if these days it is possible to disable that mandatory chrome update?

**Comment by Alex-J-W** [comment]
Hey,
you can change policies as stated here: https://support.google.com/chrome/a/answer/6350036?hl=en#zippy= as well as doing a rollback on the browser version.
Cheers

**Comment by omkarkhatavkar** [comment]
will this change affect the Remote web driver (grid 4)?

**Comment by msasnaviksm** [comment]
Having the same issue :( 
Hope the new build is coming soon!

**Comment by titusfortner** [comment]
The problem here is the 3rd party driver manager, not Selenium. Remove webdriver manager dependency and update to the latest version of Selenium.

Selenium 4.10 will use chromedriver v114 for Chrome v115 which will work, but throw a warning
Selenium 4.11 (should be out shortly) will use chromedriver v115 for Chrome v115

**Comment by bwomsm1** [comment]
@titusfortner thanks for the update.
I will wait for `4.11`

The webdriver manager guys are saying that the issue is not on their side but on `selenium` lib side, not sure what to say.
Basically the error is raised on `Chriome(service)` allocation

**Comment by titusfortner** [comment]
4.11 is out now. Give it a try.

**Comment by bwomsm1** [comment]
@titusfortner The error I get now is
`Message: unknown error: cannot find Chrome binary`


```
Name: selenium
Version: 4.11.2
Summary:
Home-page: https://www.selenium.dev
Author:
Author-email:
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: certifi, trio, trio-websocket, urllib3
Required-by: Appium-Python-Client, robotframework-seleniumlibrary
```

**Comment by titusfortner** [comment]
What is your code? You removed webdriver manager?

**Comment by bwomsm1** [comment]
> What is your code? You removed webdriver manager?

`Chrome(service=Service(ChromeDriverManager().install()))`

**Comment by bwomsm1** [comment]
> > What is your code? You removed webdriver manager?
> 
> `Chrome(service=Service(ChromeDriverManager().install()))`

Without the `Service` and the `ChromeDriverManager` it works fine, but guys, where the problem is? 
driver manager team tells me that the issue is on `selenium` side

**Comment by diemol** [comment]
The root cause is ChromeDriver 115 expecting a Chrome for Testing binary. You can go around that by setting the browser binary location yourself. Google folks expect to fix that in ChromeDriver 115 soon.

In Selenium 4.11 we are doing that for you, we are setting the browser binary path so you can continue using it usually. This feature relies on Selenium Manager, so you do not need any other driver manager tool. If you have more questions, I will leave some links above.

**Comment by bwomsm1** [comment]
Thanks @diemol, gotcha.

**Comment by bwomsm1** [comment]
> The root cause is ChromeDriver 115 expecting a Chrome for Testing binary. You can go around that by setting the browser binary location yourself. Google folks expect to fix that in ChromeDriver 115 soon.
> 
> In Selenium 4.11 we are doing that for you, we are setting the browser binary path so you can continue using it usually. This feature relies on Selenium Manager, so you do not need any other driver manager tool. If you have more questions, I will leave some links above.

@FattyMango

**Comment by titusfortner** [comment]
Yes, 4.11 automatically adds the binary path to the options for you to avoid that problem.

**Comment by titusfortner** [comment]
If Selenium sees an already-downloaded chromedriver 115, it will use it and not manage drivers/browsers. 
chromedriver 115 for Mac has a bug that only looks for "Chrome for Testing" and not "Chrome"

If you remove the existing chromedriver 115 from your computer, then Selenium 4.11.2 will "just work"

**Comment by titusfortner** [comment]
When Selenium manages the driver/browser installs, it does that for you.
Delete chromedriver and use 4.11.2 and it will work.

**Comment by titusfortner** [comment]
On a separate note, is Python still sending `desiredCapabilities`? @symonk do you have bandwidth to delete that? We should only be sending `capabilities` now.

**Comment by titusfortner** [comment]
Yeah, the cool thing about selenium is that it can:
1. locate the browser and/or download it
2. locate the driver and/or download it
3. Tell the options class to tell that driver the location of that browser

None of the other driver managers can do the 3rd thing, which is going to make everything much easier going forward.

**Comment by bwomsm1** [comment]
> Thank you so much, it does work on Mac! selenium==4.11.2 chrome : 115.0.5790.114 python 3.11
> 
> Here is the code :
> 
> # selenium 4.11.2 from selenium import webdriver from selenium.webdriver.chrome.service import Service
> 
> chrome_options = webdriver.ChromeOptions()
> 
> service = Service()
> 
> driver = webdriver.Chrome(service=service, options=chrome_options)
> 
> I was using webdriver_manager module, but I no longer see the need of it since selenium now downloads the drivers automatically.

Why you are exampling here an allocation of `Service()` and `ChromeOptions()` if it remains empty into `Chrome(...)`?
