### ISSUE TITLE
Usage examples in javascript/node/selenium-webdriver document incorrect flag

### ISSUE THREAD

**Issue by jonmiles** [SeleniumHQ/selenium#1245]
The usage examples in under the node package states incorrectly.

```javascript
 * Usage: node --harmony-generators \
 *     selenium-webdriver/example/google_search_generator.js
```

I'm using v0.12.1 and I found that the correct usage is actually.

```javascript
 * Usage: node --harmony \
 *     selenium-webdriver/example/google_search_generator.js
```

Basically you need to replace flag `--harmony-generators` with `--harmony` otherwise various different ES6 errors are thrown.

**Comment by jleyba** [comment]
Obsolete as of c9caf53c8f5a9a2ed45bda272482c372694973b4
