### ISSUE TITLE
[🐛 Bug]: Getting error when using version 4.10

### ISSUE THREAD

**Issue by flow235** [SeleniumHQ/selenium#12453]
### What happened?

Using with `watir` gem
simply running the below code makes the mentioned error appear.
Was working fine until Google Chrome version 115 came out.
Does the ruby version supports the downloading of chrome-driver after restructuring ??

### How can we reproduce the issue?

```shell
Watir::Browser.new :chrome
```

### Relevant log output

```shell
Unable to obtain chromedriver using Selenium Manager; Unsuccessful command executed: ["/home/dev/.rvm/gems/ruby-3.1.3/gems/selenium-webdriver-4.10.0/bin/linux/selenium-manager", "--browser", "chrome", "--output", "json", "--proxy", nil]; no implicit conversion of nil into String; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Ubunutu and macOS

### Selenium version

Ruby 3.1.3

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 115.0.5790.110 

### What are the browser driver(s) and version(s) where you see this issue?

Thats the issue

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Oh, try Selenium 4.11 I might have fixed this yesterday by accident.

**Comment by titusfortner** [comment]
If it still doesn't work in 4.11, it's a watir bug, and it'd be great if you could open this on the watir repo instead.

**Comment by diemol** [comment]
4.11 is out. Please let us know how it went and if we need to reopen this.

**Comment by flow235** [comment]
Hey guys, thanks for the quick replies yesterday!
Just an update, even with version `4.11.0` still facing the same error.

`Unable to obtain chromedriver using Selenium Manager; Unsuccessful command executed: ["/home/dev/.rvm/gems/ruby-3.1.3/gems/selenium-webdriver-4.11.0/bin/linux/selenium-manager", "--browser", "chrome", "--proxy", nil, "--output", "json"]; no implicit conversion of nil into String; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location`

Also, @titusfortner will open this on watir repo too.
