### ISSUE TITLE
[🐛 Bug]: driver.Quit kill Browser but did not kill console app

### ISSUE THREAD

**Issue by MGabala** [SeleniumHQ/selenium#12452]
### What happened?

driver.Quit is killing chrome browser, but not kill console app. 

### How can we reproduce the issue?

```shell
public void Quit()
    {
        driver.Quit();
        driver = null;
    }
```

### Relevant log output

```shell
Before killing
Message: Object reference not set to an instance of an object.. Inner message:
RefreshOffers
Message: Object reference not set to an instance of an object.. Inner message:

and then it goes again:

Before killing
Message: Object reference not set to an instance of an object.. Inner message:
RefreshOffers
Message: Object reference not set to an instance of an object.. Inner message:

and again..
```

### Operating System

Windows 10

### Selenium version

C# 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Wersja 115.0.5790.110 (Oficjalna wersja) (64-bitowa)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114.0.5735.90

**Comment by diemol** [comment]
What is "itself"?

**Comment by MGabala** [comment]
> What is "itself"?

I mean console app.

**Comment by diemol** [comment]
You need to exit the console app launched by Visual Studio either manually or programmatically. That is out of the scope of Selenium.
