### ISSUE TITLE
[🐛 Bug]: selenium-webdriver js mutates passed in capabilities without cloning

### ISSUE THREAD

**Issue by toddtarsi** [SeleniumHQ/selenium#12467]
### What happened?

When running tests in selenium-ide with the selenium-webdriver js bindings, I noticed every test after the first crashes. Each test builds a new driver, and uses it to do a flow. Every flow after the first stopped working. The log output below I think will clarify the issue. This only occurs if you're building multiple drivers in a process. To workaround this, I'm just passing my capabilities through `JSON.parse(JSON.stringify(capabilities))` each time.

### How can we reproduce the issue?

```shell
You can use selenium-side-runner x.54 to test.
selenium-side-runner x.55 has resolved this by cloning capabilities before passing them into the driver.
```

### Relevant log output

```shell
info: Building driver for chrome
  console.debug
    Driver path: /usr/bin/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)

  console.debug
    Browser path: "/opt/google/chrome/google-chrome"

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)

info: Running test abc
debug: Playing state changed prep for test abc
info: Building driver for chrome
  console.debug
    Driver path: /usr/bin/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)

  console.debug
    Browser path: ""/opt/google/chrome/google-chrome""

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)

info: Running test def
debug: Playing state changed prep for test def
info: Building driver for chrome
  console.debug
    Driver path: /usr/bin/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)

  console.debug
    Browser path: """/opt/google/chrome/google-chrome"""

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:142:15)
```
```


### Operating System

macOS

### Selenium version

js - 4.11.1

### What are the browser(s) and version(s) where you see this issue?

Chrome - latest

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver - latest

### Are you using Selenium Grid?

No

**Comment by toddtarsi** [comment]
Honestly, you can just do what I do and JSON.parse JSON.stringify somewhere in there

**Comment by titusfortner** [comment]
We want selenium manager to mutate the capabilities so that the right browser is used by the driver. Can discuss on slack.

**Comment by toddtarsi** [comment]
@titusfortner - That works too. I'm not opposed to that, but it also doesn't work. In the above logs, you can see it keeps mutating itself to add more double quotes. That's what happens if you instantiate more than one driver in the same host process.

**Comment by titusfortner** [comment]
There is a reason I avoid writing javascript. 😂

Any ideas on the right way to address? @harsha509?

**Comment by titusfortner** [comment]
@toddtarsi is this an IDE specific issue, or something that needs to be addressed in JS bindings? Do we know what needs to be done to fix it?

**Comment by toddtarsi** [comment]
@titusfortner - Its something that will occur in any tool that instantiates multiple drivers without creating new capabilities. So like any tests that instantiate two drivers from one capability object will have this issue. The fix is pretty simple. We just look at where the capabilities object goes into the driver, and then we do that `JSON.parse(JSON.stringify(inputCapabilities))` thing, so the mutated capabilities are written to a clone instead of the outside object.
