### ISSUE TITLE
[🐛 Bug]: CFT chrome Binary (version 115.x) is not getting downloaded with Selenium 4.11.0

### ISSUE THREAD

**Issue by naveenanimation20** [SeleniumHQ/selenium#12461]
### What happened?

CFT chrome Binary (version 115.x) is not getting downloaded with Selenium 4.11.0.

I am able to download 113, 114, 116, 117 etc... but not able to download CFT chrome binary (115.x) version.

Please refer attached screenshot:
It's having the chrome browser versions: 114.0.5735.133 116.0.5845.49  117.0.5922.0 
But not having 115.x version. 

<img width="1343" alt="Screenshot 2023-08-01 at 10 28 50 AM" src="https://github.com/SeleniumHQ/selenium/assets/6771652/99df4a6b-3c55-4dfe-b1f0-42e67f424f39">

---Note: chromedriver.exe (115.x) is getting downloaded in .cache.
refer screenshot:

<img width="948" alt="Screenshot 2023-08-01 at 10 30 13 AM" src="https://github.com/SeleniumHQ/selenium/assets/6771652/50e03596-f1bb-427b-819e-16c7021f785b">

### How can we reproduce the issue?

```shell
Using this sample code:

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.manager.SeleniumManager;

public class BrowserLaunch {
	public static void main(String[] args) {
		ChromeOptions co = new ChromeOptions();
		co.setBrowserVersion("115"); //not downloading 115 CFT chrome browser version
		co.setBrowserVersion("stable"); //with "stable" also, not downloading 115 CFT chrome browser version

		String browserPath = SeleniumManager.getInstance().getDriverPath(co, false).getBrowserPath();
		String driverPath = SeleniumManager.getInstance().getDriverPath(co, false).driverPath;
		System.out.println(browserPath);
		System.out.println(driverPath);
		WebDriver driver = new ChromeDriver(co);//here, launching regular chrome, not CFT chrome
		driver.get("https://www.google.com");
		System.out.println(driver.getTitle());
	}

}

--After running this code, its launching regular chrome browser not the CFT chrome browser.
Note: chromedriver.exe (115) is getting downloaded in the .cache directory.
```

### Relevant log output

```shell
When I try to print:
=========================
String browserPath = SeleniumManager.getInstance().getDriverPath(co, false).getBrowserPath();
		String driverPath = SeleniumManager.getInstance().getDriverPath(co, false).driverPath;
		System.out.println(browserPath);
		System.out.println(driverPath);
=========================
This is console output:

/Applications/Google Chrome.app/Contents/MacOS/Google Chrome
/Users/naveenautomationlabs/.cache/selenium/chromedriver/mac-x64/115.0.5790.102/chromedriver
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Google
```

### Operating System

MAC OS

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome CFT 115.x

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 115.x

**Comment by titusfortner** [comment]
If you have chrome 115 installed, that's what gets used. Cft is only used if you don't already have it installed.

**Comment by naveenanimation20** [comment]
So to launch cft 115 chrome, do I need to download cft 115 chrome browser manually and set the Binary path with ChromeOptions setBinary?

**Comment by titusfortner** [comment]
What is the perceived importance of the cft build? It's the version that matters.

**Comment by swathik-tech** [comment]
This issue is been seen in my windows machine as well, it couldn’t start a session though and not downloaded

**Comment by diemol** [comment]
Selenium won't download a browser you have already installed. If you want to have Chrome 115, the CfT flavor, then download it and set the path in the options. It does not make sense since you already have that version, but I assume you want to do a demo or something similar.

**Comment by naveenanimation20** [comment]
@diemol thanks for clearing it, that makes sense.

**Comment by soumyajit0905** [comment]
thanks @diemol @titusfortner @naveenanimation20 for these updates.

**Comment by soumyajit0905** [comment]
@naveenanimation20 I tried it on my machine. 
It opens the default Chrome browser installed on the machine. If it's 115. x then it does not download the Chrome binary file in the cache folder instead it uses the default binary.

![image](https://github.com/SeleniumHQ/selenium/assets/32562194/0606b4fc-6d37-4e77-a46b-12e1a237e515)

cc @titusfortner  @diemol

**Comment by titusfortner** [comment]
@soumyajit0905 yes, that is the correct, desired behavior.
