### ISSUE TITLE
[🐛 Bug]: mypy error for action_chains

### ISSUE THREAD

**Issue by MarcelWilson** [SeleniumHQ/selenium#12469]
### What happened?

mypy (1.4.1) is erroring on a incompatible type for `ActionChains(driver)`

As far as I can tell `ActionChains` should allow for all of the `WebDriver` subclasses not just a subset, shouldn't it?

### How can we reproduce the issue?

```shell
from selenium.webdriver.remote.webdriver import WebDriver

driver: WebDriver
ActionChains(driver)
```

### Relevant log output

```shell
Argument 1 to "ActionChains" has incompatible type "selenium.webdriver.remote.webdriver.WebDriver"; expected "selenium.webdriver.chrome.webdriver.WebDriver | selenium.webdriver.firefox.webdriver.WebDriver | selenium.webdriver.safari.webdriver.WebDriver | selenium.webdriver.ie.webdriver.WebDriver | selenium.webdriver.edge.webdriver.WebDriver"  [arg-type]
```
```


### Operating System

macOS

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

_No response_

**Comment by symonk** [comment]
Thanks @MarcelWilson types are a bit messy at the moment, we need a plan to address and it's been raised in the selenium TLC, hope to improve it in the near future,

https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py#L138 Exists too; I won't have any capacity today to look at changes

**Comment by MarcelWilson** [comment]
I also noticed the mypy action seems to always show it's passing and yet if you look at the step 'Test with tox' in any log, it is filled with mypy errors.

https://github.com/SeleniumHQ/selenium/blob/fbfa5d26ce96ca067d62b6921915e640498e3b09/.github/workflows/ci-python.yml#L73

If I'm not mistaken the mypy check is set to always pass regardless of the output

**Comment by bandophahita** [comment]
I submitted a PR  - https://github.com/SeleniumHQ/selenium/pull/12477
