### ISSUE TITLE
[🐛 Bug]: Selenium Manager not downloading the latest version

### ISSUE THREAD

**Issue by joergschiller** [SeleniumHQ/selenium#12468]
### What happened?

We're using CircleCI for our automated test suite and moving away from [webdrivers](https://github.com/titusfortner/webdrivers) and want to use selenium-webdriver. We used to download the latest Chrome on CI with [a tool from CircleCI](https://circleci.com/developer/orbs/orb/circleci/browser-tools).

The docker image contains Chrome 112.0.5615.49 at the moment. We want to run our tests with the latest Chrome version (115). It seems that Selenium Manager doesn't download the latest stable version.

### How can we reproduce the issue?

I expect `selenium-manager --browser chrome --browser-version stable` it to find Chrome 112 on the system and download 115 because it's the latest stable version.

Instead it finds Chrome 112 but claims the "Online stable chrome version (115) is the same as the one installed in the system".

But `selenium-manager --browser chrome --browser-version stable --force-browser-download` works. It downloads 115.

### Relevant log output

```shell
$ selenium-manager --browser chrome --browser-version stable --debug
DEBUG	Checking chromedriver in PATH
DEBUG	Running command: chromedriver --version
DEBUG	Output: ""
DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at /opt/google/chrome/google-chrome
DEBUG	Using shell command to find out chrome version
DEBUG	Running command: /opt/google/chrome/google-chrome --version
DEBUG	Output: "Google Chrome 112.0.5615.49 "
DEBUG	Detected browser: chrome 112.0.5615.49
DEBUG	Online stable chrome version (115) is the same as the one installed in the system
DEBUG	Required driver: chromedriver 112.0.5615.49
DEBUG	chromedriver 112.0.5615.49 already in the cache
INFO	Driver path: /home/circleci/.cache/selenium/chromedriver/linux64/112.0.5615.49/chromedriver
INFO	Browser path: /opt/google/chrome/google-chrome


$ selenium-manager --browser chrome --browser-version stable --force-browser-download --debug
DEBUG	Checking chromedriver in PATH
DEBUG	Running command: chromedriver --version
DEBUG	Output: ""
DEBUG	chromedriver not found in PATH
DEBUG	Required browser: chrome 115.0.5790.102
DEBUG	chrome 115.0.5790.102 already in the cache
DEBUG	chrome 115.0.5790.102 has been downloaded at /home/circleci/.cache/selenium/chrome/linux64/115.0.5790.102/chrome
DEBUG	Required driver: chromedriver 115.0.5790.102
DEBUG	chromedriver 115.0.5790.102 already in the cache
INFO	Driver path: /home/circleci/.cache/selenium/chromedriver/linux64/115.0.5790.102/chromedriver
INFO	Browser path: /home/circleci/.cache/selenium/chrome/linux64/115.0.5790.102/chrome
```

### Operating System

Ubuntu 22.04.1 LTS

### Selenium version

Ruby Gem selenium-webdriver-4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112/115

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112.0.5615.49/115.0.5790.102

**Comment by diemol** [comment]
We must improve the logged messages in the first case, however, the behavior is correct. Selenium won't download a browser if you already have one installed. 

The second case works because you are forcing the download. 

@bonigarcia what do you think about the log messages?

**Comment by joergschiller** [comment]
Thanks for the fast response! So using `--force-browser-download` is what I want/need.

I also think the logged message could be improved. Thanks again for your help.

**Comment by titusfortner** [comment]
Thanks for the logs, very helpful. This looks like a bug. 
What if you set browser version to "115" instead of "stable"?

We added stable as an option just before release, we may have missed a scenario with the logic for it.

**Comment by titusfortner** [comment]
That was a delayed post from when I didn't have internet, lol.

@diemol if you specify a version it should download it rather than using what is on the machine. Using what is on the machine should only happen if the versions match or the browserVersion is empty. Somehow, it is saying that what is installed matches stable. This might be related to the last change we made before release.

**Comment by bonigarcia** [comment]
Indeed this is a bug in Selenium Manager, introduced in the last change before the release. When specifying `stable` but the local browser is other, the CfT stable version should be downloaded without the need for `--force-browser-download`. Thanks a lot, @joergschiller, for reporting and the complete description. 

I have just sent a [PR](https://github.com/SeleniumHQ/selenium/pull/12472) to fix this. Also, I have compiled Selenium Manager with this change.

@joergschiller, can you please have a try with the new Selenium Manager binary? You can download it from [here](https://github.com/SeleniumHQ/selenium/actions/runs/5736124983). Thanks again.

**Comment by joergschiller** [comment]
Thanks again for your help!

It works with the new Selenium Manager binary from [the build](https://github.com/SeleniumHQ/selenium/actions/runs/5736124983):

```
$ ./selenium-manager --browser chrome --browser-version stable --debug
DEBUG	Checking chromedriver in PATH
DEBUG	Running command: chromedriver --version
DEBUG	Output: ""
DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at /opt/google/chrome/google-chrome
DEBUG	Using shell command to find out chrome version
DEBUG	Running command: /opt/google/chrome/google-chrome --version
DEBUG	Output: "Google Chrome 112.0.5615.49 "
DEBUG	Detected browser: chrome 112.0.5615.49
DEBUG	Online stable browser version (115) different to detected browser version (112)
DEBUG	Reading metadata from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG	Required browser: chrome 115.0.5790.102
DEBUG	Downloading chrome 115.0.5790.102 from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chrome-linux64.zip
DEBUG	chrome 115.0.5790.102 has been downloaded at /home/circleci/.cache/selenium/chrome/linux64/115.0.5790.102/chrome
DEBUG	Reading metadata from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG	Required driver: chromedriver 115.0.5790.102
DEBUG	Driver URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.102/linux64/chromedriver-linux64.zip
INFO	Driver path: /home/circleci/.cache/selenium/chromedriver/linux64/115.0.5790.102/chromedriver
INFO	Browser path: /home/circleci/.cache/selenium/chrome/linux64/115.0.5790.102/chrome
```

**Comment by titusfortner** [comment]
Thanks for bringing the bug to our attention!
