### ISSUE TITLE
[🐛 Bug]: Selenium-Java 4.11 not in Mvn Repository

### ISSUE THREAD

**Issue by Brett-kla** [SeleniumHQ/selenium#12465]
### What happened?

4.11 was not uploaded to the Maven repo: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java

### How can we reproduce the issue?

```shell
n/a
```

### Relevant log output

```shell
n/a
```

### Operating System

n/a

### Selenium version

4.11

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
It is here https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/4.11.0/ and it needs some hours or a couple of days to be shown at the URL you share.
