### ISSUE TITLE
[🚀 Feature]: Provide human readable name for a session

### ISSUE THREAD

**Issue by maxnitze** [SeleniumHQ/selenium#12478]
### Feature and motivation

In the overview sessions could display a human readable name, that was configured when the selenium test/job was started. That would make it way easier to find a running session for a specific job.

### Usage example

For local development one could configure something like `username-local`. On Jenkins (or any other CI) the job name and build number could be encoded in some kind of "human readable id", so that users of the CI can find sessions working on the tests that are executed for their CI jobs right now.

This should of course not replace the id. Since it is set by each test config individually, there might be duplicates. The developer should be responsible to make it as unique as necessary.

**Comment by titusfortner** [comment]
@diemol do we have a list of what `se:` capabilities are supported? Would be nice to have a `se:name` capability that can be provided and display it on Grid?

**Comment by diemol** [comment]
We have this https://www.selenium.dev/documentation/grid/getting_started/#metadata-in-tests
And others are useful for Dynamic Grid https://github.com/SeleniumHQ/docker-selenium#video-recording-screen-resolution-and-time-zones-in-a-dynamic-grid

In short, use `se:name` to see that displayed in the Grid UI.

**Comment by maxnitze** [comment]
Ah! I did not know about that! No idea how I could slip past that part of the docs. Thanks! That's exactly what I was looking for.
