### ISSUE TITLE
[🚀 Feature]: selenium manager option to ignore local chrome install in favor of CFT

### ISSUE THREAD

**Issue by aledipas** [SeleniumHQ/selenium#12476]
### Feature and motivation

Hello!, for quite some time my team has experienced issues with python + selenium + chrome v111 and higher where the locally installed retail version of chrome simply does not work (tab opens to data;, in the address bar but orchestration never works). The code, platform and chrome automation worked on v110 and older (and continues to work only headlessly) however today I was testing using the new CFT release and noticed that it is actually working. The problem still though is that if I request selenium manager to use the "stable" release, it will continue trying to use my locally installed chrome.

What I am effectively requesting is the ability to tell selenium to ignore locally installed chrome instances, and have it prefer to always use CFT. This way I can be sure we have consistency across different platforms (windows/mac/linux) without worrying about a situation where a user or developer may have a problematic chrome installation. 

### Usage example

This would allow us to ensure we always have a functional version of chrome pulled down and avoid problematic existing installations of chrome.

**Comment by titusfortner** [comment]
The whole point of CfT is that it is the "same" as Chrome, but with identifiable versions. If there was a regression in the browser that is keeping things from working for you, you should raise a bug with Google. We do not want to download something new if it is already on the machine.

Hmmm, we could possibly implement a method in the options class (similar to what we do with Safari Technology Preview) to toggle Chrome for Testing ([or Chromium](#12466)). That might be more trouble than it is worth, but maybe we can scope it out. @diemol / @bonigarcia what do you think?

**Comment by diemol** [comment]
@aledipas What is the version of your locally installed Chrome?

**Comment by aledipas** [comment]
Version 115.0.5790.110 (Official Build) (64-bit)

Since January with the release of chrome v111 we've been unable to use non-headless automation on Windows 11 with python/selenium. I haven't been able to find any solution in all of that time but discovering today that CFT is working is my primary reason for trying to pursue this as a replacement for our local development workflow. Hope that helps

**Comment by aledipas** [comment]
I also figured that since we can still specify `options.browser_version = 'stable'` this allows us to ensure CFT is from the stable branch without needing to specify an exact version which is good enough for us.

**Comment by diemol** [comment]
If I understand correctly, if you use your local Chrome 115, you cannot do non-headless browser automation on Windows 11. If you use CfT, it works. 

I am still trying to convince myself about this feature because the Chrome binaries should work the same for automation. Have you reported that issue to the Chrome folks?

**Comment by titusfortner** [comment]
"stable" is equivalent to: "make sure I'm using the latest," we still don't want it to download anything it doesn't have to.

I'm curious what the bug is and if it is already being tracked by Google. I don't know what you mean by "orchestration never works."

**Comment by aledipas** [comment]
Sure, what I meant was that the automated steps simply don't ever execute. In doing some further testing it actually appears that the issue the whole time has been related to some organizational management of my chrome browser... Doing a quick reinstall before the policies were re-applied and things seem be working, and as a matter of fact it seems to continue to be working after policies are applied... Sorry for the confusion but I had no clue since the start of the year what was happening - despite reinstalling my browser several times since the issue began.

**Comment by titusfortner** [comment]
Whew, glad to hear you have a solution. I think there's a potential feature here, but I'm going to wait for more people to request it before adding it to our list.

Thanks.
