### ISSUE TITLE
Script doesnot run

### ISSUE THREAD

**Issue by Shivamt** [SeleniumHQ/selenium#1247]
Unexpected modal dialog (text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue. Script: resource://gre/modules/commonj…nsion/data/jquery-2.1.0.min.js:2) The alert could not be closed. The browser may be in a wildly inconsistent state, and the alert may still be open. This is not good. If you can reliably reproduce this, please report a new issue at https://github.com/SeleniumHQ/selenium/issues with reproduction steps. Exception message: TypeError: a.document.getElementsByTagName(...)[0].getButton is not a function: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

My code is fine but unable to run it on mozilla firefox

**Comment by cgoldberg** [comment]
please share a code example that causes this.

**Comment by ddavison** [comment]
yes.. there's nothing we can do @Shivamt without source code that reproduces this issue.  we also need versions that you are using, and a browser version and language binding.

we can reopen the issue if you specify this information
