### ISSUE TITLE
[🐛 Bug]: Selenium Manager proxy management issue

### ISSUE THREAD

**Issue by jay14687se** [SeleniumHQ/selenium#12481]
### What happened?

When trying to run scripts under vpn, Selenium manager requires proxy to be set for it to download the necessary drivers through capabilities. This, if I'm not wrongly concluding, is setting the proxy for the entire framework/session which fails my scripts since it needs to run without proxy. 

Is there a way to avoid around this?

### How can we reproduce the issue?

```shell
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setCapability("proxy", <proxy-url>);
chromeOptions.addArguments("--disable-dev-shm-usage");
chromeOptions.addArguments("--no-sandbox");
chromeOptions.setBrowserVersion("113");
```

### Relevant log output

```shell
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, browserVersion: 113, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-dev-shm-usage, --no-sandbox], extensions: []}}, error Command failed with code: 65, executed: [<path>\selenium-manager2136117563690013775312814197890619\selenium-manager.exe, --browser, chrome, --output, json, --browser-version, 113]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
```

### Operating System

Windows 10

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115, Firefox 102.14 esr

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 115, geckodriver 113

**Comment by titusfortner** [comment]
That first line of the log shows that `--proxy` was not set in Selenium Manager, so if a proxy is needed, it will fail.

In general, do not use `setCapability` unless working with vendor namespaced settings.
The right code to set a proxy can be found here: https://www.selenium.dev/documentation/webdriver/drivers/options/

Give that a go and see if things work from there.

**Comment by jay14687se** [comment]
@titusfortner Sorry The logs was my mistake. Those were the logs that i get when i don't set the proxy using capabilities but set it at the system level.

Regarding the documentation on setting the proxy I don't any other method other that setCapability to set proxy. Please let me know if I'm missing somthing.

Couple of observations regarding the current behavior of Selenium Manager :
On local machine/windows pc:
 - When i run my code without vpn everything run smooth. No issues.
 - When I switch on my vpn, my test does not launch any browser without setting proxy using setCapability. But once I set the proxy, since the proxy is set at the browser level my URL doesn't launch since it requires the proxy not set. Ideally there needs to be a way where Selenium Manager downloads the necessary drivers by using the proxy(maybe receiving it as a parameter somewhere) and not setting at the browser level.

On Jenkins Docker instance:
Since this behaves like an external machine the proxy is set at the container level so the entire code runs smoothy without needing to set proxy using setCpabilities or anywhere in the framework. 

Both these are currenlty tested for Chrome browser alone.

**Comment by titusfortner** [comment]
I'm assuming it's failing because it isn't using a proxy. It isn't using a proxy because you are passing a string instead of the object it is expecting.

Sorry, I didn't realize that code example wasn't updated. It needs to look like:

```java
        Proxy proxy = new Proxy();
        proxy.setHttpProxy("http://localhost:1234");
        options.setProxy(proxy);
        driver = new ChromeDriver(options);
```

**Comment by jay14687se** [comment]
@titusfortner I did try this as well. Also in setCapabilities i was passing the proxy object. In both cases the driver is getting downloaded and the browser is launching, but it is setting the browser session under proxy which is causing my tests to fails. Webdrivermanager worked differently without setting proxy for the browser session if i'm not wrong. Below is how I used to use WebDriverManager:
`WebDriverManager.chromedriver().proxy(proxyURL).setup();`

**Comment by titusfortner** [comment]
The idea is that if the browser needs a proxy to load traffic, then selenium will also need that proxy to download the drivers.

In your situation, you need the proxy for the drivers, but requesting browser traffic through the proxy fails? I guess that makes sense for testing localhost, etc. 

You can set an environment variable for SE_PROXY to the proxyUrl or create a config file.
https://github.com/SeleniumHQ/seleniumhq.github.io/tree/trunk/examples

**Comment by jay14687se** [comment]
@titusfortner Yes that right. But even if I set environment  variable or setup a config file, the only way Selenium Manager downloads drivers is by setting chromeoptions which again results in the same issue. 
In the documentation you provided i'm not finding the right examples. Can you direct to the exact script or let me know if i'm missing something?

**Comment by titusfortner** [comment]
I thought you said you didn't need a proxy for your browser traffic? Just don't include the proxy information in the Options class, only in the environment variable or config file.

**Comment by titusfortner** [comment]
The point is that you shouldn't need to configure "extra" things, everything SM should need to know it can get from what is provided in Options class. Your use case is an exception to this.

@diemol / @bonigarcia when I was suggesting (a long time ago) that Java support System Properties for Selenium Manager this is the use case I meant. Java does not let you set environment variables in code, so there is no code solution for this. The user has to set an environment variable or create a config file.

Might be nice to be able to do:
```java
System.setProperty("SE_PROXY", proxyURL)
WebDriver driver = new ChromeDriver();
```

But more overhead. Depends on how common this is I guess.

**Comment by jay14687se** [comment]
@titusfortner Yes for my browser traffic I do not need proxy. But for Selenium Manager I need proxy. Unfortunately there currently no solution in 4.11.0 for my scenario unless I download and set the binaries and drivers manually. I'm pretty sure many in enterprise setting with run into this issue. 

> I thought you said you didn't need a proxy for your browser traffic? Just don't include the proxy information in the Options class, only in the environment variable or config file.

**Comment by jay14687se** [comment]
> The point is that you shouldn't need to configure "extra" things, everything SM should need to know it can get from what is provided in Options class. Your use case is an exception to this.
> 
> @diemol / @bonigarcia when I was suggesting (a long time ago) that Java support System Properties for Selenium Manager this is the use case I meant. Java does not let you set environment variables in code, so there is no code solution for this. The user has to set an environment variable or create a config file.
> 
> Might be nice to be able to do:
> 
> ```java
> System.setProperty("SE_PROXY", proxyURL)
> WebDriver driver = new ChromeDriver();
> ```
> 
> But more overhead. Depends on how common this is I guess.

Feature Request: Ideally downloading driver needs to be decoupled from ChromeDriver instantiation so that the necessary downloads can be accomplished with or without proxy depending on requirement. The user should have the ability to decide this based on their use cases. 
Also reading the system proxy would also better since we can set and unset the proxy before and after instantiation rather than it getting baked into the browser instance which cannot be changed

**Comment by titusfortner** [comment]
I can't tell if we are talking past each other. This works right now in Selenium 4.11
1. Set environment variable for `SE_PROXY` or create a config file with `proxy`  to equal your proxy location (https://www.selenium.dev/documentation/selenium_manager/#configuration)
2. Do not set a proxy on the options instance

**Comment by jay14687se** [comment]
@titusfortner Very sorry for wasting your time. It was my mistake. I had set my browser as FIREFOX. 
Set environment variable for SE_PROXY is working fine for Chrome. But FIREFOX doesn't seem to work.

**Comment by titusfortner** [comment]
No problem, just trying to make sure we have an answer for your situation. What isn't working for Firefox?

Turning on logging is helpful if it isn't obvious - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by jay14687se** [comment]
For firefox it doesn't download the drivers. Currently i have SE_PROXY and no firefoxOptions proxy is set. 

`org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}, error Command failed with code: 65, executed: [<path>\selenium-manager792556716365005334276342175303427\selenium-manager.exe, --browser, firefox, --output, json]
error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'`

**Comment by titusfortner** [comment]
Oh, it's not getting the proxy from the environment variable? Hmm. If you turn on logging we can see each step that Selenium Manager takes. 

@bonigarcia any idea why proxy as environment variable would be different based on which browser is passed in?

**Comment by bonigarcia** [comment]
The proxy setup is the same for Chrome, Firefox, or any other supported browser in Selenium Manager. The proxy flag seems missing in the CLI command:

```
[<path>\selenium-manager792556716365005334276342175303427\selenium-manager.exe, --browser, firefox, --output, json]
```

**Comment by jay14687se** [comment]
I have enabled logging, but how do I turn on logging specific to Selenium Manager?

**Comment by jay14687se** [comment]
@titusfortner @bonigarcia 
The issue seems to be resolved. I removed SE_PROXY from environment variable and added the proxy to selenium-manager-config.toml file and both browser are working correctly for now. I will continue to monitor this for sometime and then update.

Setting SE_PROXY environment variable did not actually work for both Chrome and Firefox. I have noticed this a couple of times that once the driver is downloaded the tests run successfully for few times an then stops when I turn off proxy. I am guessing it is because if getting it from some sort of cache. Not sure. 

So currently for me the solution is to set the proxy in selenium-manager-config.toml.

**Comment by titusfortner** [comment]
@bonigarcia he's setting it with Environment Variable, so it won't show up in the command itself.

**Comment by titusfortner** [comment]
Maybe the terminal executing the test hadn't been reset to read from where you set the environment variable? Regardless, I'm glad you have it working with the toml file. That's probably the best way to do this for now.

**Comment by jay14687se** [comment]
@titusfortner Thanks a lot for your patience and help.

**Comment by titusfortner** [comment]
No problem at all, I'm not a proxy person, so I always get nervous when people have proxy issues. 😁

**Comment by sudheer1437** [comment]
> @titusfortner @bonigarcia The issue seems to be resolved. I removed SE_PROXY from environment variable and added the proxy to selenium-manager-config.toml file and both browser are working correctly for now. I will continue to monitor this for sometime and then update.
> 
> Setting SE_PROXY environment variable did not actually work for both Chrome and Firefox. I have noticed this a couple of times that once the driver is downloaded the tests run successfully for few times an then stops when I turn off proxy. I am guessing it is because if getting it from some sort of cache. Not sure.
> 
> So currently for me the solution is to set the proxy in selenium-manager-config.toml.

Hi @jay14687se , i have exactly the same issue. can you tell me where to place this selenium-manager-config.toml?

**Comment by titusfortner** [comment]
`~/.cache/selenium` directory. We should have new documentation out soon that will make this more clear.

**Comment by Dietmar1963** [comment]
Hello - I run in a similar issue.
Using Chrome Browser it works, but using Firefox I run into errors.

**Selenide 6.16.0**
This code used to work well to configure the proxy.

        FirefoxOptions options = new FirefoxOptions();
        if(PROXY_ENABLED){
        WebDriverManager.firefoxdriver()
                .proxy("10.10.10.20:3456")
                .setup();
		....		


But now in				
**Selenide 6.17.2**

        FirefoxOptions options = new FirefoxOptions();
        if(PROXY_ENABLED){
            String ph = "10.10.10.20:3456";
            Proxy proxy = new Proxy()
                    .setAutodetect(false)
                    .setHttpProxy(ph)
                    .setSslProxy(ph)
                    .setNoProxy("127.0.0.1");
            options.setProxy(proxy);
        }
		...

**ERROR**
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {browser.download.dir: C:\Repositories\demo\test..., browser.download.folderList: 2, browser.helperApps.neverAsk.saveToDisk: video/3gpp;video/3gpp2;appl..., network.automatic-ntlm-auth.allow-non-fqdn: true, network.automatic-ntlm-auth.trusted-uris: http://,https://, network.http.phishy-userpass-length: 255, network.negotiate-auth.delegation-uris: http://,https://, network.negotiate-auth.trusted-uris: http://,https://, network.proxy.allow_hijacking_localhost: true, network.proxy.no_proxies_on: , pdfjs.disabled: true, security.csp.enable: false}}, pageLoadStrategy: normal, unhandledPromptBehavior: accept}, error Command failed with code: 65, executed: [C:\Users\DRP123~1\AppData\Local\Temp\selenium-manager1673324833771009296696657649355549\selenium-manager.exe, --browser, firefox, --output, json]
error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: driver.version: SelenideDriver


Thanks

**Comment by titusfortner** [comment]
That error appears to not have the proxy included in the options. Ate your sure you're adding that instance to the driver constructor?

**Comment by Dietmar1963** [comment]
ups sorry, disregard my issue.

I forgot to set "Configuration.browserCapabilities = options;"
