### ISSUE TITLE
Cannot disable a command from the Selenium IDE GUI

### ISSUE THREAD

**Issue by SomeHub** [SeleniumHQ/selenium#1249]
I often have the need (when extending or debugging my scripts) to disable commands (temporary).
I would like to see a new context menu item "Disable Command". This would then out-comment the command, thus it will be skipped during execution.

**Comment by mirao** [comment]
I agree, it would be handy.

**Workaround:** Create a comment above the command, switch to Source and move the command between the comment's tags.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
