### ISSUE TITLE
Selenium IDE on FF 42.0

### ISSUE THREAD

**Issue by bindutr** [SeleniumHQ/selenium#1250]
Hi,
After installing a new version of IDE (2.9.0) on FF 42.0 on a windows seven machine, I'm am getting the following errors "Table view is not available with this format" and unable to record any scripts.
Also getting the following errors. Tried uninstalling all plugins and still getting these errors. 
1. Clicking on the option button produced the error
There was an unexpected error. Msg: TypeError: editor.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 949, column: 75
Editor.prototype.onPopupOptions@chrome://selenium-ide/content/editor.js:949:75
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1
2. Clicking on the format button produced the error
There was an unexpected error. Msg: TypeError: this.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 701, column: 1
Editor.prototype.showFormatsPopup@chrome://selenium-ide/content/editor.js:701:1
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1
3. clicking on the Clipboard produced the error
There was an unexpected error. Msg: TypeError: window.editor.app is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1
4. closing the IDE window produced the following error
There was an unexpected error. Msg: TypeError: this.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 466, column: 7
Editor.prototype.confirmClose@chrome://selenium-ide/content/editor.js:466:7
onclose@chrome://selenium-ide/content/selenium-ide.xul:1:8

Any help is really appreciated.

Thanks
Bindu

**Comment by akshat62** [comment]
Update Firefox.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
