### ISSUE TITLE
[🐛 Bug]: Starting the driver more than once may fail

### ISSUE THREAD

**Issue by corrideat** [SeleniumHQ/selenium#12504]
### What happened?

Consider the following snippet:

```
var driver = await new webdriver.Builder()
	.forBrowser('firefox')
	.build();

await driver.quit();

driver = await new webdriver.Builder()
	.forBrowser('firefox')
	.build();
```

It may give the following output:

```
Selenium Manager binary found at /home/user/project/node_modules/selenium-webdriver/bin/linux/selenium-manager
The geckodriver version (0.31.0) detected in PATH at /usr/bin/geckodriver might not be compatible with the detected firefox version (102.14.0); currently, geckodriver 0.33.0 is recommended for firefox 102.*, so it is advised to delete the driver in PATH and retry
Driver path: /usr/bin/geckodriver
Browser path: /usr/lib/firefox-esr/firefox.sh
The geckodriver version (0.31.0) detected in PATH at /usr/bin/geckodriver might not be compatible with the detected firefox version (102.14.0); currently, geckodriver 0.33.0 is recommended for firefox 102.*, so it is advised to delete the driver in PATH and retry
Driver path: /usr/bin/geckodriver
Browser path: "/usr/lib/firefox-esr/firefox.sh"
```

Then, that would fail with the following stack trace:

```
     InvalidArgumentError: binary is not a Firefox executable
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:525:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Note that the second browser path has quotes (`"`) around the name. While `/usr/lib/firefox-esr/firefox.sh` is a valid path to Firefox, `"/usr/lib/firefox-esr/firefox.sh"` isn't.

### How can we reproduce the issue?

```shell
See above.

The fix seems to be removing the quotes in line 73 of `seleniumManager.js`, so that it looks like this.


    args.push('--browser-version', options.getBrowserVersion())


The error appears to happen only when a potential incompatibility between the browser version and the driver is shown.
```

### Relevant log output

```shell
See above.
```

### Operating System

Windows Server 2022, macOS 13, Ubuntu 22.04

### Selenium version

JavaScript selenium-webdriver 4.11.1

### What are the browser(s) and version(s) where you see this issue?

Chrome, Edge, Firefox 102.14.0

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.31.0

**Comment by corrideat** [comment]
Note: selenium-webdriver 4.10.x seems unaffected, because of a recent change made to 4.11.x to "remember" the browser path. Likely, the quotes are still wrong, but the issue was not triggered the way described in this report.

**Comment by titusfortner** [comment]
@harsha509 this one is JS! 😂

**Comment by diemol** [comment]
@harsha509 was this fixed by https://github.com/SeleniumHQ/selenium/commit/ec2f0fb156259c0cb18f09e5031506f245b5fa37?

**Comment by harsha509** [comment]
HI @diemol, 

Yes!

**Comment by harsha509** [comment]
Fixed with commit https://github.com/SeleniumHQ/selenium/commit/ec2f0fb156259c0cb18f09e5031506f245b5fa37!
