### ISSUE TITLE
[🐛 Bug]: Ruby 4.11.0 breaks ability to use local chromedriver or Chrome

### ISSUE THREAD

**Issue by gaffneyc** [SeleniumHQ/selenium#12515]
### What happened?

There are really two issues here which manifest because of a non-standard development environment. It looks like 4.11.0 made it so Selenium Manager (in #12345) is used to look up the path for chrome and chromedriver. This causes versions to be downloaded which do not run locally due to missing libraries. It doesn't appear that I can default back to the local install of chrome and chromedriver since Selenium Manager insists on using its versions which are broken on my system.

I do all of my development on a Linux server which doesn't run a Window environment. It also doesn't have many of the libraries (such as libnss and CUPS) that Chrome and Chrome Driver depend on installed. To get around this I've been using a Docker image with Chrome and Chrome Driver installed with simple scripts in `/usr/bin/google-chrome` and `/usr/bin/chromedriver` to launch Chrome / Chrome Driver through Docker. This has been working great for the last couple of years without issue.

### How can we reproduce the issue?

```shell
I'm not sure of a good way to make this easily reproducible as it is dependent on the system that selenium-webdriver is being run on.
```

### Relevant log output

```shell
$ /home/gaffneyc/.cache/selenium/chrome/linux64/115.0.5790.170/chrome
/home/gaffneyc/.cache/selenium/chrome/linux64/115.0.5790.170/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

### Operating System

Gentoo Linux

### Selenium version

Ruby 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 115.0.5790.170

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
How are drivers being managed before latest release?
If a driver or browser is found on the system it won't download something new. If you set Selenium::WebDriver.logger.level = :debug you can see what it's detecting.

**Comment by gaffneyc** [comment]
Thanks for the suggestion. It is looking for a local binary correctly but `/usr/bin/google-chrome --version` was returning an error instead of printing the version. So it looks like it was an issue with my setup that was surfaced due to selenium-manager checking versions (at least I didn't see any version checks with 4.10.0).
