### ISSUE TITLE
[🚀 Feature]: support ignoring driver on PATH in favor of downloaded version

### ISSUE THREAD

**Issue by technicalpickles** [SeleniumHQ/selenium#12512]
### Feature and motivation

After a recent upgrade of selenium, I started seeing this warning in local development:

```
2023-08-04 08:38:32 WARN Selenium [:selenium_manager] The chromedriver version (115.0.5790.102) detected in PATH at /opt/homebrew/bin/chromedriver might not be compatible with the detected chrome version (115.0.5790.114); currently, chromedriver 115.0.5790.170 is recommended for chrome 115.*, so it is advised to delete the driver in PATH and retry
```

I'm on macOS, and this `/opt/homebrew/bin/chromedriver` comes from having run `brew install chromedriver`. I don't know when I did this, but it has been kicking around for awhile. The easiest fix is `brew uninstall chromedriver`, but that wouldn't prevent accidental reinstallation later either explicitly, or implicitly as a manual.

I think it'd be preferred to let a project configure this to get a consistent experience across people using it.

### Usage example

I'm using selenium via [capybara](https://github.com/teamcapybara/capybara) and the [selenium-webdriver gem](https://github.com/SeleniumHQ/selenium/tree/trunk/rb), so I'm not sure how to do this at a low level...

At a high level, I'd expect to be able to, [similar to what capybara does](https://github.com/teamcapybara/capybara/blob/08f5d47c54a5f70a92749973bbf64ca776defd6d/lib/capybara/registrations/drivers.rb#L7-L9):

```ruby
Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :options => {ignore_path_driver: true)
end
```

**Comment by titusfortner** [comment]
The current intended behavior is to warn when things aren't optimal and fix things if it would otherwise error. It's essentially opt in. In the future (selenium 5?), we will automatically update things that aren't optimal. Having something on path is the equivalent of specifying a driver. 

If the driver was not on path, selenium would automatically download the best version for you and use it which is the currently recommended way. 

selenium is using the driver in path and warning that it isn't the best version. That's good in case you had an old version of the driver that wouldn't work. We've removed the warning for the next release for patch version differences, so you wouldn't see that warning in 4.12. 

I don't see where capybara supports ignore_path_driver?

**Comment by technicalpickles** [comment]
> The current intended behavior is to warn when things aren't optimal and fix things if it would otherwise error. It's essentially opt in. In the future (selenium 5?), we will automatically update things that aren't optimal. Having something on path is the equivalent of specifying a driver.

Phrased that way, I believe what I'm requesting is: being able to always download the optimal driver, and not look at the PATH.

> We've removed the warning for the next release for patch version differences, so you wouldn't see that warning in 4.12.

That will help with the warning I'm getting right now, thanks!

> I don't see where capybara supports ignore_path_driver?

Sorry, I wasn't clear. It doesn't, but it can pass options to the selenium driver. I was proposing having an option like that for selenium

**Comment by titusfortner** [comment]
That's planned for the future, but not what we want right now.

**Comment by stanhu** [comment]
Could we reopen this issue? I'd also like this feature. Currently we have a few workarounds:

1. Dropping `/opt/homebrew/bin` from the `PATH` before Selenium runs.
2. Asking developers to uninstall the Homebrew `chromedriver`.
3. Prepending the latest cached driver into the `PATH`.

I'd be happy to submit an upstream pull request if this would help.

**Comment by titusfortner** [comment]
For all Selenium versions from the beginning to now, if a driver is found on PATH it will be used. We are unlikely to be changing that behavior during Selenium 4, and we still need to discuss expectations for Selenium 5.
