### ISSUE TITLE
[🐛 Bug]: Selenium 3.141.59 and Google chrome v 115

### ISSUE THREAD

**Issue by mudit7126** [SeleniumHQ/selenium#12517]
### What happened?

I was working with Selenium 3.141.59 in my project. Last week my project stopped working as the Google chrome in my machine got to version 115. Today again i see that Selenium version 3.141.59 is working with Google chrome version 115. Have they made it compatible to Google chrome 115?

### How can we reproduce the issue?

```shell
I was working with Selenium 3.141.59 in my project. Last week my project stopped working as the Google chrome in my machine got to version 115. Today again i see that Selenium version 3.141.59 is working with Google chrome version 115. Have they made it compatible to Google chrome 115?
```

### Relevant log output

```shell
I was working with Selenium 3.141.59 in my project. Last week my project stopped working as the Google chrome in my machine got to version 115. Today again i see that Selenium version 3.141.59 is working with Google chrome version 115. Have they made it compatible to Google chrome 115?
```

### Operating System

Win10

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

Chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 115

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
We only support the latest version of Selenium.

There was a chromedriver bug that was recently fixed that might be what you saw.
