### ISSUE TITLE
[🐛 Bug]: RoR system tests : Unable to obtain chromedriver using Selenium Manager, Bad CPU type in executable

### ISSUE THREAD

**Issue by Pepan** [SeleniumHQ/selenium#12516]
### What happened?

I removed `gem 'webdrivers'` from Gemfile and updated `gem 'selenium-webdriver'` to latest version. 
I started system test by `rails test:system` and it fails with mentioned error.

### How can we reproduce the issue?

```shell
I removed `gem 'webdrivers'` from Gemfile and updated `gem 'selenium-webdriver'` to latest version. 
I started system test by `rails test:system` and it fails with mentioned error.
```

### Relevant log output

```shell
Minitest::UnexpectedError: Selenium::WebDriver::Error::NoSuchDriverError: Unable to obtain chromedriver using Selenium Manager; Unsuccessful command executed: ["/Users/josefchmel/.rvm/gems/ruby-3.2.2/gems/selenium-webdriver-4.11.0/bin/macos/selenium-manager", "--browser", "chrome", "--output", "json"]; Bad CPU type in executable - /Users/josefchmel/.rvm/gems/ruby-3.2.2/gems/selenium-webdriver-4.11.0/bin/macos/selenium-manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

macOS 13.4.1 (c) (22F770820d)

### Selenium version

selenium-webdriver (4.11.0)

### What are the browser(s) and version(s) where you see this issue?

Chrome I guess

### What are the browser driver(s) and version(s) where you see this issue?

don't know

### Are you using Selenium Grid?

nope

**Comment by davidcornu** [comment]
@Pepan any chance you're running on an M-series mac? 

I ran into what I think is the same issue. The `selenium-manager` binary that the `selenium-webdriver` gem sets up is compiled for `x86_64`:

```
$ file "$(bundle show selenium-webdriver)/bin/macos/selenium-manager"
/Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.11.0/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64
```

A short term solution that seems to be working for me is to install [Rosetta](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment) (`softwareupdate --install-rosetta`), which does x86_64 to arm64 translation, but ideally `selenium-manager` should be native.

**Comment by Pepan** [comment]
Yes. I am using M1  pro. From iPhoneJosef Chmelcompany directorJchSoft s.r.o.Internet Application ***@***.***: http://www.jchsoft.cz/7. 8. 2023 v 22:19, David Cornu ***@***.***>:﻿
@Pepan any chance you're running on an M-series mac?
I ran into what I think is the same issue. The selenium-manager binary that the selenium-webdriver gem sets up is compiled for x86_64:
$ file "$(bundle show selenium-webdriver)/bin/macos/selenium-manager"
/Users/david/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.11.0/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64

A short term solution that seems to be working for me is to install Rosetta (softwareupdate --install-rosetta), which does x86_64 to arm64 translation, but ideally selenium-manager should be native.

**Comment by titusfortner** [comment]
Rosetta is required for 4.11, 4.12 will have native support.

**Comment by leipert** [comment]
This is the PR which added universal binary builds, for reference: https://github.com/SeleniumHQ/selenium/pull/12455
