### ISSUE TITLE
[🚀 Feature]: NetworkManager (c#) - Add Response Time to network events

### ISSUE THREAD

**Issue by nicpinson** [SeleniumHQ/selenium#12538]
### Feature and motivation

Using the NetworkManager (c#), which is new to Selenium 4.8+, you are able to track network events via NetworkRequestSentEventArgs and NetworkResponseReceivedEventArgs. These events have properties like the Request Id, Response URL, Response Status Code, the Response Body, etc. However, one property they are lacking is anything to do with time. In the Chrome Dev Tools - Network tab, one of the columns is Time and you are able to see what requests are Pending and ones that have completed and how long it took. 

My proposition is to implement three additional properties between the NetworkRequestSentEventArgs and NetworkResponseReceivedEventArgs events. NetworkRequestSentEventArgs would have the new property e.SentTime. NetworkResponseReceivedEventArgs would have the new properties e.ReceivedTime and e.ResponseTime. 

This would allow the user to track how long a request took and whether or not it was successful. Both e.ReceivedTime and e.ResponseTime would need an implementation that allows them to indicate that, while a request was sent, one has not been received yet. 

Currently I am accomplishing the above by having the ResponseHandlers initialize classes for both the received and sent network response events and storing the properties I care about. When these classes are initialized, I am passing in and saving a Stopwatch (stopwatch.Elapsed.TotalMilliseconds) that was created when I initially started the network logging. These objects containing sent requests and received requests are then added to a Dictionary with e.RequestId as the key. Then I compare the two dictionaries for matching values and do some math to determine the response time. 

The resulting response time is fairly accurate, compared to the information in the Chrome Network tab; usually within a tenth of a second. I am concerned though that it could become less accurate the more requests that are added to the dictionaries. It could also add a ton of time to the end of every test, having to compare thousands of logs against each other. Additionally, I am only able to compare the dictionaries at the end of my tests, which means if for some reason there is an issue in the UI that prevents me from getting to that final comparison step, I won't get any logging at all. I know I can output reporting while the test is still running, but that wouldn't get me the difference between time sent and time received.

### Usage example

As a Test Automation Engineer, I would like to add reporting to pipeline runs that shows which Network requests took a long time or timed out so I can...
- Report that information to the devs
- Supplement existing reporting and screenshots on test failures to identify what is causing a test to fail
- Include better information in Bugs created so they can be investigated and fixed quicker

**Comment by nvborisenko** [comment]
@titusfortner I am wondering whether it's available in others bindings. From one point of view this feature request looks reasonable, but from another view it would make selenium more and more over cdp wrapping. Given that BiDi is on road...

**Comment by titusfortner** [comment]
I don't know. @p0deje / @TamsilAmani what is in Ruby/Java/JS for this right now?

But, bottom line is that this will be low priority because we will hopefully delete it all as soon as browsers support and we implement it with BiDi spec.

**Comment by jimevans** [comment]
Also, W3C Bidi protocol network events have a timestamp, so when that is available, it will be easier to add.

**Comment by EdwinVanVliet** [comment]
You can all calculate these by combining the RequestWillBeSent, ResponseReceived, DataReceived, LoadingFinished and LoadingFailed events. 

You have the walltime on RequestWillBeSent which is a arbitrary timestamp since epoch. From there you can calculate all the timings using the ResponceReceived response timing field.

**Comment by titusfortner** [comment]
I'm going to close this as not-planned because we want to devote our focus to implementing the bidi solution.
