### ISSUE TITLE
[🐛 Bug]: Unable to obtain driver after update to Selenium 4.11.2 on MacOS

### ISSUE THREAD

**Issue by MarcGruener** [SeleniumHQ/selenium#12543]
### What happened?

I was using Selenium 4.10.0 for a Python 3.11.4 project on MacOS Ventura 13.4.1 successfully.
However, after updating Selenium to 4.11.2 with the Safari Driver, I would always get the following error:

`selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for safari using Selenium Manager.`

When debugging with `safaridriver --version`, I would always get:

`Included with Safari 16.5.2 (18615.2.9.11.10)`

I also manually checked $PATH and it was included so it should be working.
After downgrading to Selenium 4.10.0 again, everything works perfectly again.

### How can we reproduce the issue?

```shell
from selenium import webdriver

browser = webdriver.Safari()
browser.get('http://selenium.dev/')
```

### Relevant log output

```shell
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for safari using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

macOS Ventura 13.4.1

### Selenium version

Python 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Safari 16.5.2

### What are the browser driver(s) and version(s) where you see this issue?

Safari 16.5.2 (18615.2.9.11.10)

**Comment by Atharvaaat** [comment]
It seems like you've encountered an issue with the Selenium 4.11.2 update when using the Safari driver on macOS Ventura 13.4.1. Here are a few steps you can take to troubleshoot and potentially resolve the issue:
1) Check Safari Version: Make sure that your Safari browser is indeed on version 16.5.2 as you mentioned. If it's not, ensure that you're using a supported version for the Safari driver you're trying to use.
2) Check WebDriver Configuration: Ensure that the Safari driver is correctly installed and available in your system's PATH. You mentioned that you've manually checked the PATH, but double-check to confirm that there are no conflicts or discrepancies.
3) Check Browser Security Settings: Safari often has strict security settings that could interfere with WebDriver. Make sure that Safari's developer mode or automation mode is enabled in its preferences. You might need to enable "Allow Remote Automation" in Safari's Develop menu.
4)Update Selenium and WebDriver: While you mentioned that you updated Selenium to 4.11.2, also make sure that you're using the corresponding Safari driver version. Sometimes, updating both Selenium and the WebDriver together can help resolve compatibility issues.
5) Downgrade or Wait: If none of the above steps work, and you need to continue your work, you might need to revert to Selenium 4.10.0 for the time being until the compatibility issue is resolved in future updates.

**Comment by diemol** [comment]
Looks like a ChatGPT answer 😂

**Comment by titusfortner** [comment]
Can you turn on logging and provide the output so we can see what Selenium Manager is doing?
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by MarcGruener** [comment]
I tried but I can't quite figure out how to activate the logging/its not working as expected:

1. Created conda environment
2. Activated conda environment (Python 3.11.4)
3. Installed `selenium` with `conda install -c conda-forge selenium`
4. Created `test_selenium.py`
```python
# test_selenium.py
import logging

logging.basicConfig(filename='selenium.log', encoding='utf-8', level=logging.DEBUG)
logger = logging.getLogger('selenium')

logging.info('<--- Started --->')

from selenium import webdriver

browser = webdriver.Safari()
browser.get('http://selenium.dev/')

logging.info('<--- Finished --->')
```

--> Getting the `selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for safari using Selenium Manager.` error

5. Run `python test_selenium.py` and open selenium.log:
```
INFO:root:<--- Started --->

```


If I follow the same steps as above but use `conda install -c conda-forge selenium=4.10.0` during step 3. instead, everything works as expected and this is what `selenium.log` looks like:

```
INFO:root:<--- Started --->
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/bin/safaridriver` in a child process with pid: 33094
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:51207/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "safari", "platformName": "mac", "pageLoadStrategy": "normal"}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:51207
DEBUG:urllib3.connectionpool:http://localhost:51207 "POST /session HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"sessionId":"283B1A64-9B8F-4AE4-A9D0-F584A6A55218","capabilities":{"safari:platformVersion":"13.4.1","safari:automaticInspection":false,"webkit:WebRTC":{"DisableICECandidateFiltering":false,"DisableInsecureMediaCapture":false},"browserVersion":"16.5.2","strictFileInteractability":false,"browserName":"Safari","safari:useSimulator":false,"safari:platformBuildVersion":"22F82","setWindowRect":true,"acceptInsecureCerts":false,"safari:automaticProfiling":false,"pageLoadStrategy":"normal","platformName":"macOS","safari:diagnose":false}}} | headers=HTTPHeaderDict({'Server': 'safaridriver [18615.2.9.11.10]', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Mon, 14 Aug 2023 13:01:07 GMT', 'Accept-Ranges': 'bytes', 'Content-Length': '546', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:51207/session/283B1A64-9B8F-4AE4-A9D0-F584A6A55218/url {"url": "http://selenium.dev/"}
DEBUG:urllib3.connectionpool:http://localhost:51207 "POST /session/283B1A64-9B8F-4AE4-A9D0-F584A6A55218/url HTTP/1.1" 200 0
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Server': 'safaridriver [18615.2.9.11.10]', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Mon, 14 Aug 2023 13:01:08 GMT', 'Accept-Ranges': 'bytes', 'Content-Length': '14', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive'})
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
INFO:root:<--- Finished --->

```

**Comment by titusfortner** [comment]
Oh, Conda. That's different.

Conda does not currently support Selenium Manager, you'll need to continue to manage your own drivers until we can determine a work-around. https://github.com/SeleniumHQ/selenium/issues/11234
