### ISSUE TITLE
[🐛 Bug]: Selenium-Manager not getting in stalled with selenium-java 4.11.0

### ISSUE THREAD

**Issue by speedy1096** [SeleniumHQ/selenium#12541]
### What happened?

When upgrading to selenium-java 4.11.0 from selenium-java 4.4.0 selenium-manager isn't installed automatically as shown in a few demo videos I found:
* https://www.youtube.com/watch?v=CH2YShFfv-M
* https://www.youtube.com/watch?v=M3RyBvUTOpk

I also see that selenium browser drivers are still version 4.1.4. When I run the program I get the error:  org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 90
Current browser version is 115.0.1901.203 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
![image](https://github.com/SeleniumHQ/selenium/assets/28935416/8f5c781e-f35c-47ff-911b-9e56d326ce7f)

### How can we reproduce the issue?

```shell
ThreadTestApplication.javav

package com.example.demo;

import java.util.Set;
import org.openqa.selenium.*;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class ThreadTestApplication {


	public static void main(String[] args) throws InterruptedException {
		SpringApplication.run(ThreadTestApplication.class, args);
		

	    WebDriver driver = new EdgeDriver();

	    driver.get("http://www.google.com/");
	    Thread.sleep(10000);
	    driver.quit();

	}

}






Thread_Test/pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.3</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>Thread_Test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Thread_Test</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>18</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.11.0</version>
		</dependency>

		<!-- <dependency> <groupId>org.seleniumhq.selenium</groupId> <artifactId>selenium-manager</artifactId> 
			<version>4.10.0</version> </dependency> -->
	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

### Relevant log output

```shell
2023-08-13 14:54:19.188  INFO 13424 --- [           main] com.example.demo.ThreadTestApplication   : Starting ThreadTestApplication using Java 15.0.1 on DESKTOP-G2GRHTT with PID 13424 (C:\Users\cgon5\Documents\Test\Thread_Test\target\classes started by cgon5 in C:\Users\cgon5\Documents\Test\Thread_Test)
2023-08-13 14:54:19.190  INFO 13424 --- [           main] com.example.demo.ThreadTestApplication   : No active profile set, falling back to 1 default profile: "default"
2023-08-13 14:54:19.621  INFO 13424 --- [           main] com.example.demo.ThreadTestApplication   : Started ThreadTestApplication in 0.697 seconds (JVM running for 1.359)
Starting MSEdgeDriver 90.0.818.62 (0fca3b62331f6fe9a9b27f34c02690655a8c06a2) on port 49323
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping MSEdgeDriver safe.
MSEdgeDriver was started successfully.
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of MSEdgeDriver only supports MSEdge version 90
Current browser version is 115.0.1901.203 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'DESKTOP-G2GRHTT', ip: '10.101.21.75', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}], desiredCapabilities=Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [], extensions: []}}}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:52)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:44)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:41)
	at com.example.demo.ThreadTestApplication.main(ThreadTestApplication.java:21)
```

### Operating System

Windows 10.0.19045 Build 19045

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

msedge version 115.0.1901.203

### What are the browser driver(s) and version(s) where you see this issue?

msedge version 90

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Looks like you have an old version of the driver on your system. There should be a warning message saying where it is, but maybe it isn't turned on by default. Find the old driver and delete it, then try again.

**Comment by speedy1096** [comment]
@titusfortner I found the drivers in my C:\bin folder. Now I have the error:

java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/. The latest version can be downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:311)
	
Shouldn't Selenium-manager be installed with selenium-java and take care of the drivers?

**Comment by titusfortner** [comment]
Ah, you have a dependency conflict. Only reference selenium-java in your pom and set it to 4.11

**Comment by speedy1096** [comment]
This is my pom.xml. I removed the commented out code for the web driver manager and did a maven > update project. Selenium manager still didn't show.

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.11.0</version>
		</dependency>

	</dependencies>

**Comment by titusfortner** [comment]
I don't know what you mean about selenium manager not showing.
What error did you get about the drivers?

**Comment by speedy1096** [comment]
From this tutorial at 12:15 it shows that upgrading to selenium-java 4.6.0 installs the selenium-manager dependency. https://www.youtube.com/watch?v=CH2YShFfv-M


The error that I get is 
IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.edge.driver system property; for more information, see https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/. The latest version can be downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by speedy1096** [comment]
I am trying to use selenium manager. Do I have to add it in my pom.xml?

**Comment by diemol** [comment]
You should be using the latest (4.11.0 in Java at the time), and if something does not work, create an issue or ask in our chat https://www.selenium.dev/support/

**Comment by speedy1096** [comment]
Thanks!
