### ISSUE TITLE
[🚀 Feature]: Hide back the console window in 4.11 like in 4.10 and older

### ISSUE THREAD

**Issue by ShoodEver** [SeleniumHQ/selenium#12542]
### Feature and motivation

This issue started to appear in 4.11.0 only, it was fine in 4.10 and older.
ChromeDriverService.CreateDefaultService(); shows a console window once it executed

I hope to add an option to hide it
In version 4.10 and older, it was hidden by default

I'm using .Net6 / C# 10.0 on Windows 10

![image](https://github.com/SeleniumHQ/selenium/assets/30406099/930b1e57-1c2a-46b1-b607-d33d8aa448d3)

### Usage example

            var service = ChromeDriverService.CreateDefaultService(); // shows the black window here //same with ChromeDriverService, FirefoxDriverService or any driver service

            service.HideCommandPromptWindow = true; //i'm not talking about this, it's fine

            var options = new ChromeOptions();
            options.AddArguments("--headless=new");
            var driver = new ChromeDriver(service, options);

            var driver = new ChromeDriver(service, option);
            driver.Navigate().GoToUrl(url);

**Comment by goldcanyon340** [comment]
I have the same issue. Have had to fall back to v4.10.0

.NET7 C#11.0 on Win10
