### ISSUE TITLE
save_screenshot function shot 2 times pixel than real browser in Macbook and chrome

### ISSUE THREAD

**Issue by danbao** [SeleniumHQ/selenium#1255]
test code
```python
#!/usr/bin/env python
# coding: utf-8

import cv2
from selenium import webdriver

print cv2.__version__
print webdriver.__version__
browser = webdriver.Chrome()
browser.maximize_window()
browser.get('https://www.google.com/')
browser.save_screenshot('testshot.png')
img = cv2.imread('testshot.png')
print browser.get_window_size()
print img.shape[1],img.shape[0]
browser.quit()
```
*result:*
2.4.12
2.48.0
{u'width': 1050, u'height': 777}
2100 1410

real browser
![qq20151115-0 2x](https://cloud.githubusercontent.com/assets/4090783/11166931/8b03f608-8b87-11e5-93b6-5e39e735a0ef.png)

browser_save_screenshot function

![testshot](https://cloud.githubusercontent.com/assets/4090783/11166916/0f4ac3a2-8b87-11e5-9feb-04bec0ba98de.png)

**Comment by lukeis** [comment]
this isn't actually an issue the project is going to solve. Rendered OS Pixels are different than DOM Pixels. This could potentially be scaled by the OS. Good thing you're not working on mobile? Where there's a zoom function with webviews and the DOM pixel is almost never the same as the screen pixel.

Going to close as this is more something to do with the OS settings and scale and nothing really for the project to do. Also chrome driver has it's own separate issue tracker.
