### ISSUE TITLE
[🐛 Bug]: [rb] - SM doesn't play nicely with array of `capabilities`

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#12560]
### What happened?

When using the SM instead of `webdrivers` gem, it does not play nicely when using a 2-itemed array of `capabilities`. This is still needed (I believe), because locally / remotely you may want to provide both options and capabilities.

Some examples are.... (From my gem): https://github.com/site-prism/automation_helpers/blob/main/lib/automation_helpers/drivers/v4/local.rb#L39-L51

### How can we reproduce the issue?

```shell
Generate a driver (I used capybara), whereby the capabilities is a 2-object array. This then passes `options` to SM as follows


[#<Selenium::WebDriver::Remote::Capabilities:0x00007ff68d454d50 @capabilities={}>, #<Selenium::WebDriver::Chrome::Options:0x00007ff68d408770 @options={:args=>[], :prefs=>{}, :emulation=>{}, :local_state=>{}, :exclude_switches=>[], :perf_logging_prefs=>{}, :window_types=>[], :browser_name=>"chrome"}, @profile=nil, @logging_prefs={}, @encoded_extensions=[], @extensions=[]>]
```
```


### Relevant log output

```shell
Solution is to add a small "shim" here on line 59 of `selenium_manager.rb`: https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/common/selenium_manager.rb#L59

        def generate_command(binary, options)
          options = options.last
```

Obviously this won't work for everyone, so maybe some detection logic is needed?
```


### Operating System

Ubuntu 20

### Selenium version

Ruby 4.11

### What are the browser(s) and version(s) where you see this issue?

chrome v115

### What are the browser driver(s) and version(s) where you see this issue?

v115 chrome

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
What about a PR that has the fix and a test?

**Comment by titusfortner** [comment]
Ruby Selenium intentionally no longer supports using capabilities class in local drivers. It can still be used for remote drivers, but it is recommended to use Options instance.
