### ISSUE TITLE
[🚀 Feature]: JavaScript errors are checked by driver.executeScript

### ISSUE THREAD

**Issue by anasouardini** [SeleniumHQ/selenium#12568]
### Feature and motivation

This is not a feature but a feature removal.

I have this very long script that I'm injecting into the browser, the script might have tons of complicated errors. When selenium intercepts the script and tries to check for those errors, in my use case it nothing more than a wall in my face.

CLI is not the best way to debug JS code nor selenium is better than a browser with a set of debugging tools.

I want to be able to get my code to the browser whether it works or not, the error message selenium shows only prevents me from doing a proper debugging.

While not everyone writes a view with JSX and uses selenium to inject it, I think this feature should either be improved somehow or an option should be provided to skip checking those scripts.

Thanks for considering my proposal.

### Usage example

Everything is explained above.

**Comment by titusfortner** [comment]
Is the error message coming from Selenium or the driver? Can you provide logs (https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/) or a stack trace?

**Comment by joerg1985** [comment]
Did you try to [Listen to JS Exceptions](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#listen-to-js-exceptions) with the new BiDi?

**Comment by anasouardini** [comment]
@titusfortner Sorry for the late response.

Here is an instance of the Error:
```bash
{
  Err: JavascriptError: javascript error: exports is not defined
    (Session info: chrome=114.0.5735.198)
      at Object.throwDecodedError (/home/venego/home/dev/selenium/projects/dreamjob/node_modules/.pnpm/selenium-webdriver@4.10.0/node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (/home/venego/home/dev/selenium/projects/dreamjob/node_modules/.pnpm/selenium-webdriver@4.10.0/node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (/home/venego/home/dev/selenium/projects/dreamjob/node_modules/.pnpm/selenium-webdriver@4.10.0/node_modules/selenium-webdriver/lib/http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (/home/venego/home/dev/selenium/projects/dreamjob/node_modules/.pnpm/selenium-webdriver@4.10.0/node_modules/selenium-webdriver/lib/webdriver.js:745:17) {
    remoteStacktrace: '#0 0x558cebd4d133 <unknown>\n' +
      '#1 0x558ceba81966 <unknown>\n' +
      '#2 0x558ceba86126 <unknown>\n' +
      '#3 0x558ceba88070 <unknown>\n' +
      '#4 0x558cebaf6e02 <unknown>\n' +
      '#5 0x558cebaddbd2 <unknown>\n' +
      '#6 0x558cebaf61c7 <unknown>\n' +
 ```
 
 I think it's the driver, I have a shallow understanding of how it works.
 
 I would appreciate if there's an option to disable checking for JS errors in the Driver (if my guess is correct).

**Comment by anasouardini** [comment]
> Did you try to [Listen to JS Exceptions](https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#listen-to-js-exceptions) with the new BiDi?

Well, that's not the problem, I want the script to make it to the browser whether it's a valid JS or not.

**Comment by titusfortner** [comment]
I asked because of it is an error coming back from the driver, which it looks like it is in this case, then you need to raise the issue with Google.
I tried to look over the spec for this to see what was required, etc, but I can't figure out of it's even supposed to be allowed or not. https://w3c.github.io/webdriver/#executing-script
