### ISSUE TITLE
[🐛 Bug]: Getting following issue with Chrome-116.0.5845.97 and Selenium 4.11.0 

### ISSUE THREAD

**Issue by gauravbhasinudaipur** [SeleniumHQ/selenium#12569]
### What happened?

After the Chrome is updated to 116.0.5845.97 and using selenium 4.11.0 when trying to launch the Chrome browser getting following issue.
OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

I am using   Webdrivermanager

  new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);

The opened browser windows just shows ;data and doesn't open the supplied URL

The tests run fine when I add --headless options to the arguments and run the tests

The same tests were running fine before the Chrome got updated to version 116.0.5845.97

### How can we reproduce the issue?

```shell
Just update the Chrome browser version to latest 116.xxx and try to launch the browser using Selenium 4.11.0
```

### Relevant log output

```shell
Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
ChromeDriver.ctor(String chromeDriverDirectory, ChromeOptions options)
```

### Operating System

Windows 10

### Selenium version

 selenium 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.97

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 116.0.5845.97

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Selenium does not support Webdrivermanager. Try deleting it and seeing if it works.

Regardless, this is a chromedriver error and it is being tracked here - https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403
