### ISSUE TITLE
[🐛 Bug]: Unable to obtain MicrosoftEdge using Selenium Manager

### ISSUE THREAD

**Issue by Pique7** [SeleniumHQ/selenium#12577]
### What happened?

Yet another "Unable to obtain ... using Selenium Manager" **after upgrading to version 4.11.0**.

In my case the error occurs when I call `CreateDefaultService()` without passing the webdriver location path parameter (in .NET project).

It **works only  on the development machine** but not when deployed by ClickOnce. It also works when I pass the location of the webdriver executable to `CreateDefaultService()`, e.g. `CreateDefaultService("C:\\webdriver\\msedgedriver.exe"); `.

Context:
- Visual Studio 2022
- .NET / C# / VSTO (MS Office 2010)
- x86 build (MS Office Add-In)
- x64 machine
- ClickOnce deployment

I have tried to build the latest nightly pre-release but this was not successful at all. So I couldn't say, whether the bug has been fixed meanwhile.  

### How can we reproduce the issue?

```shell
EdgeOptions edgeOptions = new EdgeOptions() { };
edgeOptions.AddArgument("no-sandbox");
edgeOptions.AddArgument("--disable-dev-shm-usage");
EdgeDriverService edgeService = EdgeDriverService.CreateDefaultService();
EdgeDriver edge = new EdgeDriver(EdgeService, edgeOptions);
```

### Relevant log output

```shell
Unable to obtain MicrosoftEdge using Selenium Manager (...)

at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
at OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService(EdgeOptions options)
at OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService()
```

### Operating System

Windows 10

### Selenium version

4.11.0, 4.12.3

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge v115.0.1901.203

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver v115.0.1901.203

**Comment by titusfortner** [comment]
I fixed this for next release.

**Comment by Pique7** [comment]
I have just updated to version 4.12.3, but I still got the same error as in version 4.11.0. 

Maybe it is related to running a 32-bit application on a 64-bit system.
Or the cause is somewhere in the ClickOnce deployment of MS Office Add-Ins.

As already mentioned, it worked with Selenium versions up to 4.10.0.

**Comment by titusfortner** [comment]
This didn't actually work before 4.11
```
CreateDefaultService("C:\\webdriver\\msedgedriver.exe")
```
The constructor with a string was only for the directory of the driver.
If it wasn't a directory or no driver existed at the provided directory, selenium would just ignore it and look for a driver on PATH.
4.11 fixed this by parsing the string to see if it included a filename. Instead of ignoring problems, selenium now errors.

I don't know why it isn't working for you with a default service class, though.

You shouldn't need to use a service class at all any more. Selenium will automatically locate or obtain the correct driver for you.

**Comment by Pique7** [comment]
OK, is there a "simple" way to debug this by myself?

**Comment by titusfortner** [comment]
Update to Selenium 4.12.4 and provide the errors/logs you get

This method is now obsolete and not getting used, so it isn't in 4.12
```
at OpenQA.Selenium.Edge.EdgeDriverService.CreateDefaultService(EdgeOptions options)
```

**Comment by Pique7** [comment]
I am getting this error with version 4.12.4:
```
NoSuchDriverException: Unable to obtain MicrosoftEdge using Selenium Manager (...)
Stack Trace:
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   ...
```

**Comment by nvborisenko** [comment]
@Pique7 please share full exception output without trimming (you can hide sensitive data).

**Comment by Pique7** [comment]
> please share full exception output without trimming (you can hide sensitive data).

I think I have not trimmed anything important. I don't have much more information about the exception, because this is **not** from the debugger but from a log file / dialog box. The full error message is:
```
NoSuchDriverException: 
Unable to obtain MicrosoftEdge using Selenium Manager; 
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

The stack trace just continues with:
```
   at MyFunctions() ...
```
... which does the following:
```
EdgeOptions edgeOptions = new EdgeOptions() { };
edgeOptions.AddArgument("no-sandbox");
edgeOptions.AddArgument("--disable-dev-shm-usage");
EdgeDriverService edgeService = EdgeDriverService.CreateDefaultService();
EdgeDriver edge = new EdgeDriver(EdgeService, edgeOptions);
```

As this does not happen on the development machine, I will have to improve the logging function to get more information. 
What additional data would be helpful that I can write to the log file when the exception is thrown?

**Comment by nvborisenko** [comment]
You missed `InnerException`. It is better to put `exception.ToString()` in your logs, in this way we can see where it came from.

**Comment by Pique7** [comment]
OK, `exception.ToString()` gave me:
```
OpenQA.Selenium.NoSuchDriverException: Unable to obtain MicrosoftEdge using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location 
---> System.TypeInitializationException: The type initializer for "OpenQA.Selenium.SeleniumManager" threw an exception. 
---> OpenQA.Selenium.WebDriverException: Unable to locate or obtain Selenium Manager binary at C:\Users\MyTestUser\AppData\Local\Apps\2.0\DANKMJEK.9RL\H6EW7P2D.H5C\outl..vsto_9..1.0..9\selenium-manager/windows/selenium-manager.exe
   at OpenQA.Selenium.SeleniumManager..cctor()
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.DriverPath(DriverOptions options)
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.DriverFinder.FullPath(DriverOptions options)
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeDriverService service, EdgeOptions options)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)
   at OutlookTestAddIn.MySeleniumTest()
```
I have checked the given path. The **subdirectory** `selenium-manager` does not exist, so also the executable `selenium-manager.exe` does not exist at the expected location. The parent directory `outl..vsto...` contains all files of the deployed Outlook Add-In. I have noticed, that the path string contains backslashes in the existing part and forward slashes in the non-existing part. I think that this should be not a problem, but I don't know.
I have searched for the mentioned file `selenium-manager.exe`, but neither found it in the User's profile path nor in `C:\ProgramData`. I haven't searched other locations yet.

**Comment by Pique7** [comment]
> I have checked the given path. The subdirectory `selenium-manager` does not exist, so also the executable `selenium-manager.exe` does not exist at the expected location. The parent directory `outl..vsto...` contains all files of the deployed Outlook Add-In. 

In previous Selenium releases the `selenium-manager.exe` was directly placed in this parent directory `C:\Users\MyTestUser\AppData\Local\Apps\2.0\DANKMJEK.9RL\H6EW7P2D.H5C\outl..vsto_9..1.0..9\` where all the other add-in files are located, not in sub directories.

**Comment by nvborisenko** [comment]
I reproduced the issue locally. To fix it we can change `None` type in our `*.targets` file to `Content`. Then VS will pack selenium-manager into installer as additional files.

**Comment by Pique7** [comment]
Confirmation: The problem seems to be solved in version 4.13.1.

**Comment by mcsilver** [comment]
I know this is closed, but I don't know where else to ask. Feel free to redirect me to a more appropriate forum.

I need to automate accessing `http://localhost` while the firewall restricts the computer's Internet access almost completely, but on 4.15.0, I get the "Unable to obtain MicrosoftEdge using Selenium Manager" error. If I allow full Internet access on the same computer, then the problem goes away.

Is this by design? What is reaching out to where, and is it necessary? Can that traffic be circumvented, and what functionality is lost if so?

Thanks!

UPDATE:

I installed Microsoft Network Monitor and got the following information:

process: selenium-manager.exe
destination host: part-0042.t-0009.t-msedge.net
destination IP: 13.107.213.70
destination port: 443

But, the remaining questions are: What is it doing? Is it necessary? Can it be turned off? What am I losing if it is turned off?

**Comment by titusfortner** [comment]
@mcsilver you can read about this binary here: https://www.selenium.dev/documentation/selenium_manager/

Essentially it is trying to make sure you have the right browser & driver on your system by default.

If you already have Microsoft Edge and msedgedriver installed on the computer you shouldn't get this error.
Feel free to discuss with us on irc/slack if you'd like: https://www.selenium.dev/support/#ChatRoom

**Comment by mcsilver** [comment]
Thank you, @titusfortner. Makes sense, and it's a nice feature. I'll definitely try poking a hole in my firewall to accommodate it, and I'll follow up on the Slack channel for more info.
