### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by sudheer1437** [SeleniumHQ/selenium#12570]
### What happened?

Current Chrome browser version is Version=116.0.5845.97
When using selenium manager to download the driver, the connection is timed out.

### How can we reproduce the issue?

```shell
Below is the command used to download the Chrome driver

` ./selenium-manager.exe --browser chrome --debug --trace
`
```

### Relevant log output

```shell
DEBUG   Checking chromedriver in PATH
DEBUG   Running command: chromedriver --version
DEBUG   Output: ""
DEBUG   chromedriver not found in PATH
DEBUG   chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
TRACE   Original path: C:\Program Files\Google\Chrome\Application\chrome.exe - Escaped path: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG   Output: "\r\r\n\r\r\nVersion=116.0.5845.97\r\r\n\r\r\n\r\r\n\r"
TRACE   The version of chrome is 116.0.5845.97
DEBUG   Detected browser: chrome 116.0.5845.97
TRACE   Reading metadata from C:\Users\BalivadaS\.cache\selenium\selenium-manager.json
TRACE   Driver version used to request CfT: 116
DEBUG   Reading metadata from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
ERROR   error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed bec
ause the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
```

### Operating System

Windows 10

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.97

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by titusfortner** [comment]
It's obviously a network error and not a Selenium issue, so we can't really troubleshoot it for you.

Is there a proxy on the machine that you're running this on? If so add the proxy information to the Chrome Options class you send to the driver.

**Comment by sudheer1437** [comment]
> It's obviously a network error and not a Selenium issue, so we can't really troubleshoot it for you.
> 
> Is there a proxy on the machine that you're running this on? If so add the proxy information to the Chrome Options class you send to the driver.

Thank you for responding @titusfortner 

When i use the proxy, 

`./selenium-manager.exe --browser chrome --debug --trace --proxy http://xxx.xxx.xxx.xxx:8080`

proxy needs authentication.. and i am not sure how to pass creds... i tried below way

`./selenium-manager.exe --browser chrome --debug --trace --proxy username@password:http://xxx.xxx.xxx.xxx:8080`

but it does not recognize it..

**Comment by titusfortner** [comment]
@bonigarcia does it work with authentication? The drivers themselves do not, so you might need another proxy in the middle to add the credentials.

**Comment by bonigarcia** [comment]
`username@password:http://xxx.xxx.xxx.xxx:8080` seems incorrect to me. I would try `username:password@proxy:port` or `http://username:password@proxy:port`

**Comment by sudheer1437** [comment]
> `username@password:http://xxx.xxx.xxx.xxx:8080` seems incorrect to me. I would try `username:password@proxy:port` or `http://username:password@proxy:port`

I did try this too

` ./selenium-manager.exe --browser chrome --debug --trace --proxy username:password@http://xxx.xxx.xxx.xxx:8080`
and below is the log
```
DEBUG   Using proxy: username:passwordhttp://xxx.xxx.xxx.xxx:8080
ERROR   builder error: builder error for url (username:passwordhttp://xxx.xxx.xxx.xxx:8080): URL scheme is not allowed
```

please note i had special character in my password... and the observe the log, there is no colon (:) between password and proxy url. i am not sure if that is the way it should be or not. 

i am trying now without special characters in my password and keep you posted

**Comment by sudheer1437** [comment]
> > `username@password:http://xxx.xxx.xxx.xxx:8080` seems incorrect to me. I would try `username:password@proxy:port` or `http://username:password@proxy:port`
> 
> I did try this too
> 
> ` ./selenium-manager.exe --browser chrome --debug --trace --proxy username:password@http://xxx.xxx.xxx.xxx:8080` and below is the log
> 
> ```
> DEBUG   Using proxy: username:passwordhttp://xxx.xxx.xxx.xxx:8080
> ERROR   builder error: builder error for url (username:passwordhttp://xxx.xxx.xxx.xxx:8080): URL scheme is not allowed
> ```
> 
> please note i had special character in my password... and the observe the log, there is no colon (:) between password and proxy url. i am not sure if that is the way it should be or not.
> 
> i am trying now without special characters in my password and keep you posted

@titusfortner I had special character at the end of my password, removing the special character at the end of the password and tried again... now back to square one with same error as below

```
DEBUG   Using proxy: username:password@http://xxx.xxx.xxx.xxx:8080
DEBUG   Checking chromedriver in PATH
DEBUG   Running command: chromedriver --version
DEBUG   Output: ""
DEBUG   chromedriver not found in PATH
DEBUG   chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
TRACE   Original path: C:\Program Files\Google\Chrome\Application\chrome.exe - E
scaped path: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
DEBUG   Using shell command to find out chrome version
DEBUG   Running command: wmic datafile where name='C:\\Program Files\\Google\\Ch
rome\\Application\\chrome.exe' get Version /value
DEBUG   Output: "\r\r\n\r\r\nVersion=116.0.5845.97\r\r\n\r\r\n\r\r\n\r"
TRACE   The version of chrome is 116.0.5845.97
DEBUG   Detected browser: chrome 116.0.5845.97
TRACE   Reading metadata from C:\Users\xxxxxxx\.cache\selenium\selenium-manage
r.json
TRACE   Metadata file does not exist. Creating a new one
TRACE   Driver version used to request CfT: 116
DEBUG   Reading metadata from https://googlechromelabs.github.io/chrome-for-test
ing/known-good-versions-with-downloads.json
ERROR   error sending request for url (https://googlechromelabs.github.io/chrome
-for-testing/known-good-versions-with-downloads.json): error trying to connect:
tcp connect error: A connection attempt failed because the connected party did n
ot properly respond after a period of time, or established connection failed bec
ause connected host has failed to respond. (os error 10060)
```

**Comment by ccea-dev-team** [comment]
I think I'm having the same kind of issue after chrome 116 and using selenium-manager.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 

Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_345'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:203)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 54 more

Is there something I have to add to my firewall to allow a connection and if so what is it?

**Comment by titusfortner** [comment]
@ccea-dev-team for Java you can turn on logging and get more info about what is happening — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

@sudheer1437 can you take a look at the proxy logs and see why it was rejected? There's really nothing Selenium or Selenium Manager can do to get more information from the server.

**Comment by bonigarcia** [comment]
@sudheer1437 It seems you keep using bad syntax for your proxy with credentials. As I said before, you can try `username:password@proxy:port` or `http://username:password@proxy:port`:

```
./selenium-manager --browser chrome --debug --proxy username:password@xxx.xxx.xxx.xxx:8080
```

**Comment by sudheer1437** [comment]
> @sudheer1437 It seems you keep using bad syntax for your proxy with credentials. As I said before, you can try `username:password@proxy:port` or `http://username:password@proxy:port`:
> 
> ```
> ./selenium-manager --browser chrome --debug --proxy username:password@xxx.xxx.xxx.xxx:8080
> ```

thank you @bonigarcia  @titusfortner  this setting worked. and all good now.
