### ISSUE TITLE
[🐛 Bug]: Unable to Access Chrome's Remote Debugging Port

### ISSUE THREAD

**Issue by h-nakao** [SeleniumHQ/selenium#12575]
### What happened?

I am a beginner. I'm sorry if I was saying something strange. 

I got a timeout error after I raised the version. 
> Error:   The HTTP request to the remote WebDriver server for URL http://localhost:56649/session timed out after 60 seconds.
- Chrome version 115.XXX → 116.XXX
- Chrome driver version 115.XXX → 116.XXX
- Selenium version  4.10.0 → 4.11.1

### How can we reproduce the issue?

```shell
1.Start Chrome with the following arguments
--profile-directory = "default" -remote-debugging-port = 9222

2.I used to operate it with the code below, but I get an error. 

    ChromeDriverService = ChromeDriverService.CreateDefaultService( );
    service.HideCommandPromptWindow = false;

    ChromeOptions options = new ChromeOptions
    {
        DebuggerAddress = "127.0.0.1:9222"
    };

    webDriver = new ChromeDriver(service, options);
```

### Relevant log output

```shell
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/ says ".NET does not currently have a Logging implementation".
```

### Operating System

Windows10

### Selenium version

DotNet 4.11.0

### What are the browser(s) and version(s) where you see this issue?

116.0.5845.97

### What are the browser driver(s) and version(s) where you see this issue?

116.0.5845.96

**Comment by titusfortner** [comment]
I think this is going to fix that: https://github.com/SeleniumHQ/selenium/pull/12534
It'll get merged for 4.12 and hopefully released soon.

**Comment by h-nakao** [comment]
Thank you very much. 
I will wait for the release of 4.12.

**Comment by h-nakao** [comment]
I was able to confirm that it moved normally.
