### ISSUE TITLE
[🐛 Bug]: Tag version not updated after fixing bug with mypy

### ISSUE THREAD

**Issue by M1troll** [SeleniumHQ/selenium#12572]
### What happened?

The ["mypy error for action_chains" issue](https://github.com/SeleniumHQ/selenium/issues/12469) has already been closed. The [PR fixing this issue](https://github.com/SeleniumHQ/selenium/pull/12477) has been merged, but the changes are now only [stored in the `trunk` branch](https://github.com/SeleniumHQ/selenium/blob/1104c8f876011fc3fe11eb56d112a10312822866/py/selenium/webdriver/common/action_chains.py#L35-L36). The [4.11.2 tag](https://github.com/SeleniumHQ/selenium/blob/3718b8c89bc2022353435c89d23520e9b48b4441/py/selenium/webdriver/common/action_chains.py#L35-L42) for python doesn't have these changes.

### How can we reproduce the issue?

```shell
pip install selenium


```python
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.common.action_chains import ActionChains

driver: WebDriver
ActionChains(driver)
```

```bash
mypy
```
```


### Relevant log output

```shell
error: Argument 1 to "ActionChains" has incompatible type "selenium.webdriver.remote.webdriver.WebDriver"; expected "selenium.webdriver.chrome.webdriver.WebDriver | selenium.webdriver.firefox.webdriver.WebDriver | selenium.webdriver.safari.webdriver.WebDriver | selenium.webdriver.ie.webdriver.WebDriver | selenium.webdriver.edge.webdriver.WebDriver"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

### Operating System

ManjaroLinux 23.0.0

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

Chromium Web Browser 116.0.5845.96

**Comment by titusfortner** [comment]
Yes, please wait for 4.12 to be released.

**Comment by M1troll** [comment]
Okay, when should this be expected?

**Comment by titusfortner** [comment]
as soon as we can get it out.

**Comment by M1troll** [comment]
Okay, Thanks!
