### ISSUE TITLE
[🐛 Bug]: season not created if use headless=new

### ISSUE THREAD

**Issue by NCLnclNCL** [SeleniumHQ/selenium#12587]
### What happened?

if i dont use headless, it will dont errors or very rare
if i use headless, appear quite often

### How can we reproduce the issue?

```shell
Use --headless=new and open multi threads
```

### Relevant log output

```shell
season not created
```

### Operating System

win 10

### Selenium version

4.1.10

### What are the browser(s) and version(s) where you see this issue?

115

### What are the browser driver(s) and version(s) where you see this issue?

115

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
If it happens on headless but not without headless, then it is likely an issue with chromedriver. Without more logs or reproducible information, there's nothing we can help track down. I'd prepare the things Google requests and file a ticket with them.
