### ISSUE TITLE
[🐛 Bug]: Port Collision on Windows Server with ChromeDriver

### ISSUE THREAD

**Issue by yasin-uohyd** [SeleniumHQ/selenium#12585]
### What happened?

The chrome driver is used to run our UI tests and below are the statements to instantiate the ChromeDriver. 
During the test run multiple test scenarios will be executed parallelly. Each Scenario will have its own Port Number.
`var driverService = ChromeDriverService.CreateDefaultService();`
`return new ChromeDriver(driverService, chromeOptions, TimeSpan.FromSeconds(maxDriverCommandTimeout));` 

This will create a driverservice on the available free port and creates ChromeDriver object.  This has been working for longtime. But, one of the test runs we have observed that same port was assigned to two scenarios and one of the scenarios got failed. I have added the log output in the logout section.
Referring to the logs: 49793, 49794 are given to multiple scenarios (two scenarios for each port)
### How can we reproduce the issue?

```shell
This issue has occurred only once.
```

### Relevant log output

```shell
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49794
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49793
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49793
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49792
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
IPv6 port not available. Exiting...
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49795
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 49794
Only local connections are allowed.Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
IPv6 port not available. Exiting...
```

### Operating System

Windows Server 2012

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 73.0.3683.68

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
We do not support Selenium 3. If it is reproducible in Selenium 4.11 we can reopen. Thanks.
