### ISSUE TITLE
[🐛 Bug]:  invalid session id in ubuntu 18 / docker environment

### ISSUE THREAD

**Issue by jaemanc** [SeleniumHQ/selenium#12583]
### What happened?

hi im check the session id in my source code 

<img width="1087" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/104718153/846b7333-2bf4-450a-b277-ae2669476602">

the session id of run projects 
<img width="451" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/104718153/d71bad10-8969-437f-9b15-79e8766c834d">

and i called login api , that printed driver session ids 

<img width="465" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/104718153/6fda2cf8-9e09-44b9-943c-20f5ef9cc5a8">

i think the session id was same.. at run server and call login api 

but why occured invalid session id errors??

<img width="909" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/104718153/30aa5f29-550b-462c-99f0-5e44d76d891f">

this is my requirement.txt   

--- 

asgiref==3.7.2
attrs==23.1.0
backports.zoneinfo==0.2.1
certifi==2023.7.22
charset-normalizer==3.2.0
Django==4.2.4
djangorestframework==3.14.0
exceptiongroup==1.1.2
h11==0.14.0
idna==3.4
outcome==1.2.0
packaging==23.1
PySocks==1.7.1
python-dotenv==1.0.0
pytz==2023.3
requests==2.31.0
selenium==4.11.2
sniffio==1.3.0
sortedcontainers==2.4.0
sqlparse==0.4.4
trio==0.22.2
trio-websocket==0.10.3
typing_extensions==4.7.1
urllib3==2.0.4
webdriver-manager==4.0.0
wsproto==1.2.0

---

error : 

 v1/login error: Traceback (most recent call last):
  File "/app/macro/login.py", line 27, in login_to_website
    pages = login(request)
  File "/app/macro/login.py", line 48, in login
    go_to_login_page_button = login_page.find_element(By.XPATH, '//img[@src="/images/gnb_login.gif"]')
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 739, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

### How can we reproduce the issue?

```shell
driver config  :

import logging

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

logger = logging.getLogger()

customService = Service(ChromeDriverManager().install())
customOptions = Options()
customOptions.add_argument("disable-infobars")
customOptions.add_argument("--disable-extensions")
customOptions.add_argument('--headless')
customOptions.add_argument('--no-sandbox')

# 연속성을 위해 전역으로 세팅
# 성능 향상을 위해 쓰지 않는 옵션은 끄는게 좋지만 그렇게 큰 차이가 나지 않음.
driver = webdriver.Chrome(service=customService, options=customOptions)
driver.execute_script("window.open('');")

logger.info(f'driver session id :  {driver.session_id}')

def get_web_site_crawling(**kwargs):

    global driver

    # 로컬 환경 버전이 아닌 드라이버 버전에 맞는 객체를 설치하고 가져오도록 수정.
    # 단점은 크롬이 이미 설치되어야 한다는 점, 장점은 크롬이 업데이트 되면 자동으로 버전을 맞춰준다는 점.
    try:
        url = kwargs['url']
        # 웹사이트 URL 설정
        website_url = url  # 대상 웹사이트 URL
        driver.get(website_url)

        alert = driver.switch_to.alert
        alert.dismiss()

        return driver

    except Exception as err:
        # URL 요청 없을경우
        # 기존 driver의 정보를 그대로 리턴한다.
        return driver




login api code : 
def login(request):

    login_web_site_url = "https://www.letskorail.com"
    login_page = get_web_site_crawling(url=login_web_site_url)
    req_membershipNum = request.data['membershipNum']
    req_password = request.data['password']

    logger.info(f'driver session id :  {login_page.session_id}')

    # 로그인 페이지 이동.
    go_to_login_page_button = login_page.find_element(By.XPATH, '//img[@src="/images/gnb_login.gif"]')
    go_to_login_page_button.click()

    member_numbs = login_page.find_element(By.ID, "txtMember")
    member_numbs.send_keys(req_membershipNum)

    password = login_page.find_element(By.ID, "txtPwd")
    password.send_keys(req_password)
    login_btn = login_page.find_element(By.XPATH, '//img[@src="/images/btn_login.gif"]')
    login_btn.click()

    return login_page
```

### Relevant log output

```shell
2023-08-22 02:39:16,739 DEBUG [root] [login.py:33] [login_to_website()] - v1/login error: Traceback (most recent call last):
  File "/app/macro/login.py", line 27, in login_to_website
    pages = login(request)
  File "/app/macro/login.py", line 48, in login
    go_to_login_page_button = login_page.find_element(By.XPATH, '//img[@src="/images/gnb_login.gif"]')
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 739, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
```

### Operating System

oci / ubuntu 18

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

webdriver

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
Few things:
* You no longer need `customService`. Selenium 4.11 will manage drivers for you.
* `--disable-infobars` argument was removed in 2014
* `--headless` should be updated to `--headless=new`

Most likely the session has been ended already. Are you running multiple scripts in parallel? Might some code have quit the global driver while other code is trying to use it?

Maybe turning on Selenium logging will show you more details?
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by jaemanc** [comment]
hi

i finally catch the error of my project 


thanks for you're support

this is my finall settings. 

 ver :
 python = 3.8

 selenium==4.11.2
 Django==4.2.4
 djangorestframework==3.14.0



setting codes : 

custom_options = Options()
custom_options.add_argument("--disable-extensions")
custom_options.add_argument('--headless=new')
custom_options.add_argument('--no-sandbox')
custom_options.add_argument('--lang=ko-KR')
custom_options.add_argument('--disable-dev-shm-usage')

driver = webdriver.Chrome(options=custom_options)

driver.execute_script("window.open('');")

**Comment by diemol** [comment]
Thank you for letting us know.
