### ISSUE TITLE
[🐛 Bug]: chromedriver can't connect to chrome

### ISSUE THREAD

**Issue by jschmied** [SeleniumHQ/selenium#12588]
### What happened?

Version 116.0.5845.96 (chromedriver and chrome)
chromedriver-linux64 on ubuntu

chromedriver does not connect anymore to chrome instance

[1692341920,969][DEBUG]: DevTools HTTP Request: http://localhost:36257/json/version
[1692341920,970][DEBUG]: DevTools HTTP Request failed

the url http://localhost:36257/json/version is accessible with a browser:

{
   "Browser": "Chrome/116.0.5845.96",
   "Protocol-Version": "1.3",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
   "V8-Version": "11.6.189.18",
   "WebKit-Version": "537.36 (@1a391816688002153ef791ffe60d9e899a71a037)",
   "webSocketDebuggerUrl": "ws://localhost:36257/devtools/browser/4f5600a0-6378-48e5-997c-aa219faa80a7"
}

### How can we reproduce the issue?

```shell
just do a 

driver = new ChromeDriver();
```

### Relevant log output

```shell
[1692341920,606][INFO]: Launching chrome: /opt/google/chrome/chrome --allow-pre-commit-input --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-logging --ignore-certificate-errors --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.5D4c12 --v=1 data:,

DevTools listening on ws://127.0.0.1:36257/devtools/browser/4f5600a0-6378-48e5-997c-aa219faa80a7
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[1692341920,916][DEBUG]: DevTools HTTP Request: http://localhost:36257/json/version
[1692341920,917][DEBUG]: DevTools HTTP Request failed
[1692341920,969][DEBUG]: DevTools HTTP Request: http://localhost:36257/json/version
[1692341920,970][DEBUG]: DevTools HTTP Request failed
```

### Operating System

ubuntu 20.04.6 LTS

### Selenium version

4.11

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

local

**Comment by jschmied** [comment]
I found by wireshark: chromedriver tries to reach chrome by ipv6, chrome serves only ipv4
chromedriver tries to connect to [::1] and chrome sends [RST,ACK] back.

curl http://[::1]:38407/json/version
curl: (56) Recv failure: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt

curl http://localhost:38407/json/version
{
"Browser": "Chrome/116.0.5845.96",
"Protocol-Version": "1.3",
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[116.0.0.0](http://116.0.0.0/) Safari/537.36",
"V8-Version": "11.6.189.18",
"WebKit-Version": "537.36 (@1a391816688002153ef791ffe60d9e899a71a037)",
"webSocketDebuggerUrl": "ws://localhost:38407/devtools/browser/259b1b9c-e987-4175-bed1-66f723c049b3"
}

why is chromedriver using ipv6 for connecting? How can I force ipv4?

disabling ipv6 on os level fixes the problem

**Comment by jschmied** [comment]
Thats a follow up to https://github.com/SeleniumHQ/selenium/issues/12574 after upgrading to 4.11

**Comment by titusfortner** [comment]
Please turn on logging and provide output:
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by jschmied** [comment]
```
Aug. 22, 2023 8:24:30 NACHM. org.openqa.selenium.remote.RemoteWebDriver log
FEIN: Executing: newSession [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--no-sandbox, --disable-dev-shm-usage, --enable-logging, --v=1, --whitelisted-ips='', --remote-allow-origins=*], extensions: []}}]}]
Aug. 22, 2023 8:24:30 NACHM. org.openqa.selenium.remote.service.DriverService start
FEIN: Starting driver at ChromeDriver/chromedriver-linux64 with [--port=22227, --log-path=/home/jschmied/git/acceptance-test/acceptanceTests/chromedriver.log, --log-level=ALL]
Aug. 22, 2023 8:24:30 NACHM. org.openqa.selenium.net.UrlChecker waitUntilAvailable
FEIN: Waiting for [http://localhost:22227/status]
Aug. 22, 2023 8:24:30 NACHM. org.openqa.selenium.net.UrlChecker lambda$waitUntilAvailable$1
FEIN: Polling http://localhost:22227/status
Aug. 22, 2023 8:24:30 NACHM. sun.net.www.protocol.http.HttpURLConnection writeRequests
FEIN: sun.net.www.MessageHeader@f0e8dcb35 pairs: {GET /status HTTP/1.1: null}{User-Agent: Java/11.0.20}{Host: localhost:22227}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Aug. 22, 2023 8:24:30 NACHM. sun.net.www.protocol.http.HttpURLConnection getInputStream0
FEIN: sun.net.www.MessageHeader@9b6a19e34 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 251}{Content-Type: application/json; charset=utf-8}{cache-control: no-cache}
Aug. 22, 2023 8:25:31 NACHM. org.openqa.selenium.net.UrlChecker waitUntilUnavailable
FEIN: Waiting for http://localhost:22227/shutdown
Aug. 22, 2023 8:25:31 NACHM. org.openqa.selenium.net.UrlChecker lambda$waitUntilUnavailable$2
FEIN: Polling http://localhost:22227/shutdown
Aug. 22, 2023 8:25:31 NACHM. sun.net.www.protocol.http.HttpURLConnection writeRequests
FEIN: sun.net.www.MessageHeader@d33b314d5 pairs: {GET /shutdown HTTP/1.1: null}{User-Agent: Java/11.0.20}{Host: localhost:22227}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Aug. 22, 2023 8:25:31 NACHM. sun.net.www.protocol.http.HttpURLConnection getInputStream0
FEIN: sun.net.www.MessageHeader@b961dc3b3 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 40}{Content-Type: application/json; charset=utf-8}
Aug. 22, 2023 8:25:31 NACHM. org.openqa.selenium.net.UrlChecker lambda$waitUntilUnavailable$2
FEIN: Polling http://localhost:22227/shutdown
Aug. 22, 2023 8:25:31 NACHM. sun.net.www.protocol.http.HttpURLConnection writeRequests
FEIN: sun.net.www.MessageHeader@a50ec43a5 pairs: {GET /shutdown HTTP/1.1: null}{User-Agent: Java/11.0.20}{Host: localhost:22227}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
Aug. 22, 2023 8:25:31 NACHM. org.openqa.selenium.remote.RemoteWebDriver log
FEIN: Exception: newSession Could not start a new session. Response code 500. Message: chrome not reachable 
Host info: host: '1062-LAP', ip: '10.0.0.45'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-156-generic', java.version: '11.0.20'
Driver info: driver.version: ChromeDriver
```

**Comment by diemol** [comment]
The log shows how Selenium connects with ChromeDriver, and then Chrome fails to start. That might be what you are saying about IPv4 vs. IPv6. 

Could you try to start ChromeDriver manually and post a payload to see if the same thing happens? 
```json
{
  "capabilities": {
		"alwaysMatch": {
			"browserName": "chrome"
		},
    "firstMatch": [{}]
  }
}
```

**Comment by jschmied** [comment]
chromes does start and is even answering on http://localhost:12345/json/version but only with ipv4. 

Chromedriver is trying to use ipv6 for talking to chrome and fails. Think his is a problem chromedriver<-> chrome and has nothing to do with selenium.
Since chromedriver has no option to force ipv4 I switched ipv6 off on host. Works for now and I wait for next chrome version.

At least its documented here now if somebody has the same problem. Took me a few hours to find out.

**Comment by diemol** [comment]
Thank you for trying it out. I don't know how ChromeDriver chooses IPv6 or IPv4. Maybe it is a system setting, but I am not sure. I will leave some links below where you can contact the ChromeDriver team to report this.
