### ISSUE TITLE
HtmlUnitDriver with DefaultCredentialsProvider sends credentials to every endpoint

### ISSUE THREAD

**Issue by flyrev** [SeleniumHQ/selenium#1259]
Using
    @Override
    protected WebClient modifyWebClient(WebClient client) {
        DefaultCredentialsProvider credentials = new DefaultCredentialsProvider();
        credentials.addCredentials(username, password, domain, port, realm);
        client.setCredentialsProvider(credentials);
        return client;
    }

it will still send credentials to other pages that does not match the realm. In fact it will send it on pages that do not send a challenge in the first place.

It seems that the credentials are chosen the first time they are needed, and then they are used forever.

**Comment by flyrev** [comment]
You can test it using Wireshark. Use the modifyWebClient as above with an appropriate endpoint. Then request that page. Then request any other page, and you will see that there will still be an Authorization: header.

**Comment by lukeis** [comment]
you're overriding the driver, modifying the client and then logging a bug for us against your modification?

Also, this feels more like a bug with htmlUnit itself not respecting the 'domain' aspect of the credentials. Please log a bug with the HtmlUnit project.
