### ISSUE TITLE
[🐛 Bug]:  Could not instantiate class org.openqa.selenium.chrome.ChromeDriver

### ISSUE THREAD

**Issue by Joanri20** [SeleniumHQ/selenium#12595]
### What happened?

Error occurs while downloading ChromeDriver version 116.
We use the libraries
serenity-screenplay-webdriver:3.3.4
and
bonigarcia:webdrivermanager:5.4.1
to automatically download the latest version of the webdriver.
It worked correctly with Chromedriver version 115.
When upgrading webdriver to 116, it doesn't work anymore.
show message of
"Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114 "

File serenity.properties
chrome.switches= --window-size=1920,1080; --start-maximized; --remote-allow-origins=*;....
(This setting worked with issues in version 110 onwards, but doesn't work now)

### How can we reproduce the issue?

```shell
Locally there are times it works fine, but when played on a cloud server it doesn't work.

serenity.properties
chrome.switches= --window-size=1920,1080; --start-maximized; --remote-allow-origins=*;....
(This setting worked with issues in version 110 onwards, but doesn't work now)

build.gradle
serenity-screenplay-webdriver:3.3.4
or
bonigarcia:webdrivermanager:5.4.1
```

### Relevant log output

```shell
"Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114 "
```

### Operating System

Windows server 2016 OS.version:10.0

### Selenium version

3.3.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.97

**Comment by titusfortner** [comment]
If you upgrade to Selenium 4.11 you do not need webdriver manager. Selenium will manage the drivers for you directly, including v115+

**Comment by diemol** [comment]
Yes, please remove WebDriverManager and try again. If you still face this issue, please comment below with logging enabled https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
