### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mohiniB-cyber** [SeleniumHQ/selenium#12616]
### What happened?

Please help me resolve this issue:
![error](https://github.com/SeleniumHQ/selenium/assets/143270037/28c23dc7-5e5f-46d8-9a30-fe5ff024a142)

### How can we reproduce the issue?

```shell
package introduction;

public class Selenium {

	public static void main(String[] args) {
		System.setProperty("webdriver.chome.driver","C://Drivers/chromedriver.exe");
		WebDriver driver = new ChromeDriver();
	}

}
```

### Relevant log output

```shell
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	WebDriver cannot be resolved to a type
	ChromeDriver cannot be resolved to a type

	at introduction/introduction.Selenium.main(Selenium.java:7)
```

### Operating System

Windows 10

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
You need to import those libraries.

This is minimum code to get a Selenium session: https://www.selenium.dev/documentation/

We discuss pom and gradle options here - https://www.selenium.dev/documentation/webdriver/getting_started/install_library/#requirements-by-language
