### ISSUE TITLE
[🐛 Bug]: implicitly wait and WebDriverWait do not work in both java and python just on my computer

### ISSUE THREAD

**Issue by LynnWang1031** [SeleniumHQ/selenium#12611]
### What happened?

There is a very simple test script that use  implicitly wait . But it not work as expect. Here is the python script.

```
import time

from selenium import webdriver

def print_hi(name):
    print(f'Hi, {name}')  

if __name__ == '__main__':
    print_hi('PyCharm')
    CHROMEDRIVER_PATH = 'chromedriver'
    options = webdriver.ChromeOptions()
    driver = webdriver.Chrome(options)

    driver.get("https://www.google.com/")

    driver.implicitly_wait(10)
    print("wait end")
    # time.sleep(10)
    driver.quit()
```

Actual: Open the homepage of google and quit immediately without waiting 10s. But it works when I use time.sleep(10).
What have I done to resolve it?
1.I checked my chrome and webdriver version, it's right. And I even updated my chrome from 114 to 116.
2.I tried to user safari , it's the same with chrome.
3.I created a script in java, both implicitly wait and WebDriverWait  not work.
4.I tried to update selenium from 3.141.x to 4.x, and it does not work.

### How can we reproduce the issue?

```shell
computer:macOS Ventura 13.3.1
chrome:114-116(the latest version)
selenium:3.141.59 - 4.11.2
```

### Relevant log output

```shell
no errors
```

### Operating System

macOS Ventura 13.3.1

### Selenium version

4.11.2

### What are the browser(s) and version(s) where you see this issue?

chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

just the newest one

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
That is not the purpose of waits, the purpose is to wait for elements. 

Please check the documentation https://www.selenium.dev/documentation/webdriver/waits/
