### ISSUE TITLE
Without headleas mode script is working fine in selenium 4.11.0 But while running script in headless mode, using chrome options, getting no such element exception. If using explicit wait then getting timeout exception. Previously i was using In selenium 3.141.59 , here not getting any exception in headless mode[🐛 Bug]: 

### ISSUE THREAD

**Issue by Shakir001** [SeleniumHQ/selenium#12615]
### What happened?

Without headleas mode script is working fine in selenium 4.11.0 But while running script in headless mode, using chrome options, getting no such element exception while picking date from calender. If using explicit wait then getting timeout exception. Previously i was using In selenium 3.141.59 , here not getting any exception in headless mode[🐛 Bug]: 

### How can we reproduce the issue?

```shell
If you try to handle any calender in  headless mode, you will get No such element exception
```

### Relevant log output

```shell
No such element exception, timeout exception getting in headless
```

### Operating System

Ubuntu

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome- 116 version

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by diemol** [comment]
Most likely, you need to adjust your wait strategy https://www.selenium.dev/documentation/webdriver/waits/

Aside from that, we can only do something if there is a way to reproduce your issue. 

Also, if it works well when the browser opens normally but fails in headless, you can report the issue to Chrome.

Below, I will be sure to leave some links where you can ask more questions and where to report issues to Chrome.

**Comment by titusfortner** [comment]
Also, try the new headless mode

`--headless=new`
