### ISSUE TITLE
[🐛 Bug]: Chromedriver not found for LATEST_RELEASE_116 https://chromedriver.storage.googleapis.com

### ISSUE THREAD

**Issue by ChandrasekarGenesys** [SeleniumHQ/selenium#12621]
### What happened?

**Dockerfile**

FROM maven:3.8.6-jdk-11

ARG CHROME_VERSION="google-chrome-stable"
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
        && apt-get update -qqy \
        && apt-get -qqy install \
        ${CHROME_VERSION:-google-chrome-stable} \
        && rm /etc/apt/sources.list.d/google-chrome.list \
        && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
        && sed -i 's/"$HERE\/chrome"/"$HERE\/chrome" --no-sandbox/g' /opt/google/chrome/google-chrome

# ChromeDriver
ARG CHROME_DRIVER_VERSION
RUN if [ -z "$CHROME_DRIVER_VERSION" ]; \
        then CHROME_MAJOR_VERSION=$(google-chrome --version | sed -E "s/.* ([0-9]+)(\.[0-9]+){3}.*/\1/") \
        && CHROME_DRIVER_VERSION=$(wget --no-verbose -O - "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}"); \
        fi \
        && echo "Using chromedriver version: "$CHROME_DRIVER_VERSION \
        && wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip \
        && rm -rf /opt/chromedriver \
        && unzip /tmp/chromedriver_linux64.zip -d /opt \
        && rm /tmp/chromedriver_linux64.zip \
        && mv /opt/chromedriver /opt/chromedriver-$CHROME_DRIVER_VERSION \
        && chmod 755 /opt/chromedriver-$CHROME_DRIVER_VERSION \
        && ln -fs /opt/chromedriver-$CHROME_DRIVER_VERSION /usr/local/sbin/chromedriver

**Error:**
 ---> Running in 2b6b9bcf22af
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116:
2023-08-24 09:37:26 ERROR 404: Not Found.

### How can we reproduce the issue?

```shell
Go to the link: https://chromedriver.storage.googleapis.com

There is no release for 116 chromedriver.
```

### Relevant log output

```shell
**Error:**
 ---> Running in 2b6b9bcf22af
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116:
2023-08-24 09:37:26 ERROR 404: Not Found.
```

### Operating System

Amazon Linux 2

### Selenium version

Selenium 3.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver

**Comment by diemol** [comment]
We don't control those URLs. Please check the changes Chrome has made to the resource where you can download ChromeDriver.

https://developer.chrome.com/blog/chrome-for-testing/

**Comment by SandeshJ09** [comment]
I believe the bug is valid, as I am getting following error when I am using below code , previously it would download latest release in \systemprofile.cache\

_var options = new ChromeOptions();
var CrPath = SeleniumManager.DriverPath("chromedriver");                                
var driverService = ChromeDriverService.CreateDefaultService(CrPath);
webDriver = new ChromeDriver(driverService,  options)_


{"session not created: This version of ChromeDriver only supports Chrome version 114
 \nCurrent 
browser version is 116.0.5845.111 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe (SessionNotCreated)"}

**Comment by titusfortner** [comment]
Do not use the Selenium manager class directly. Selenium uses it properly for you in the background
