### ISSUE TITLE
doesNot supports Chrome 116.xx [🐛 Bug]: 

### ISSUE THREAD

**Issue by KirillZ07** [SeleniumHQ/selenium#12629]
### What happened?

I know this issue been reported but Im facing it after updating to Selenium 4.11

### How can we reproduce the issue?

```shell
WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.get("google.com");
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
Host info: host: 'DESKTOP-Q2E4FSD', ip: '192.168.50.60'
Build info: version: '4.11.0', revision: '040bc5406b'
```

### Operating System

Win 10

### Selenium version

4.11

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

Version 116.0.5845.111 (Official Build) (64-bit)

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
You have an old version of the driver on your system, and Selenium assumes that it is the one you want to use. Turn on logging and it should show you where it is so you can delete it.

https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
