### ISSUE TITLE
TestNG version with selenium standalone jar 2.48.2 does not execute onTestFailure method

### ISSUE THREAD

**Issue by jineshkenandy** [SeleniumHQ/selenium#1263]
TestNG version 6.9.6, current version included with selenium jar has a bug which got resolved in 6.9.9. I have created another issue with testng team, you can refer to the same https://github.com/cbeust/testng/issues/857. Could you kindly update the testng version to latest?

Thanks,
Jinesh

**Comment by AJ-72** [comment]
@jineshkenandy You can make your project refer to a different testNG.jar file. You don't have to always use the one that comes bundled with selenium.

**Comment by jineshkenandy** [comment]
@AJ-72 For some reason, my code picks the testng version inside the selenium jar. As of now I built my own jar and put it in the project.

**Comment by jineshkenandy** [comment]
Thanks @barancev.

**Comment by smccarthy** [comment]
Thanks !
