### ISSUE TITLE
Fluent or customize wait is not working in selenium 4 versions in c#, it throwing exceptions instead of ignoring [🐛 Bug]: 

### ISSUE THREAD

**Issue by vijayakumar471585** [SeleniumHQ/selenium#12634]
### What happened?

Fluent or customize wait is not working in selenium 4 versions in c#, it throwing exceptions instead of ignoring excpetions,

Platform: windows 10

browser used : chrome 116
snippet:
protected void waitForElement(IWebElement element)
        {

            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(300))
            {
                PollingInterval = TimeSpan.FromSeconds(5),
            };
            wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(NoSuchWindowException), typeof(WebDriverException), typeof(WebDriverTimeoutException), typeof(NotFoundException), typeof(DriverServiceNotFoundException), typeof(ElementNotVisibleException), typeof(ElementNotInteractableException));

            wait.Until(d => element.Displayed);
        }

### How can we reproduce the issue?

```shell
Using customized wait using above code
```

### Relevant log output

```shell
-
```

### Operating System

windows 10

### Selenium version

c# 4.11

### What are the browser(s) and version(s) where you see this issue?

All browsers with latest versions

### What are the browser driver(s) and version(s) where you see this issue?

All browsers with latest versions

### Are you using Selenium Grid?

-

**Comment by titusfortner** [comment]
This code is working as expected in our examples:
https://github.com/SeleniumHQ/seleniumhq.github.io/blob/a6b704a4dc36d73b9bcf86f7610b0624c4187051/examples/dotnet/SeleniumDocs/Waits/WaitsTest.cs#L64

I modified it to what you have (which isn't the recommended way of using the waits class), and it is still working correctly.

```
            driver.Url = "https://www.selenium.dev/selenium/web/dynamic.html";
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(2))
            {
                PollingInterval = TimeSpan.FromMilliseconds(300),
            };
            wait.IgnoreExceptionTypes(typeof(NoSuchElementException), typeof(NoSuchWindowException), typeof(WebDriverException), typeof(WebDriverTimeoutException), typeof(NotFoundException), typeof(DriverServiceNotFoundException), typeof(ElementNotVisibleException), typeof(ElementNotInteractableException));

            wait.Until(d => driver.FindElement(By.Id("revealed")).Displayed ); 
```

I'll add a link for where you can ask additional questions
