### ISSUE TITLE
[🐛 Bug]: Selenium Webdriver - EdgeDriverService Not supporting multiple Embedded Edge browser access

### ISSUE THREAD

**Issue by MadhuKush** [SeleniumHQ/selenium#12638]
### What happened?

Hi Team

I am using Selenium Beta v4.0 WebDriver for Edge browser related application. 
This application is built upon multiple embedded edge browsers. 

Selenium webDriver with EdgeDriver Service is working perfectly when only single edge browser is opened and trying to access. However when multiple embedded edge browser windows are opened, service is not able to create the session and thus not able to access the windows

### How can we reproduce the issue?

```shell
EdgeDriver remoteEdgeWebDriver = null;
EdgeDriverService driverService = EdgeDriverService.CreateChromiumService(@"WebDriver.dll Path");
                    driverService.HideCommandPromptWindow = true;
                    EdgeOptions edgeOptions = new EdgeOptions();
                    edgeOptions.BinaryLocation = @"Application exe Path";
                    edgeOptions.DebuggerAddress = "localhost:9222";
                    edgeOptions.UseChromium = true;                    
                    remoteEdgeWebDriver = new EdgeDriver(driverService, edgeOptions);

                    IWait<IWebDriver> driverWait = new WebDriverWait(remoteEdgeWebDriver, TimeSpan.FromSeconds(30.00));
                    var jsDriver = (IJavaScriptExecutor)remoteEdgeWebDriver;
                    driverWait.Until(drv => (jsDriver.ExecuteScript("return document.readyState").Equals("complete")));

                    remoteEdgeWebDriver.Navigate();
```

### Relevant log output

```shell
session not created
from disconnected: unable to connect to renderer
  (Session info: MicrosoftEdge=98.0.1108.62) (SessionNotCreated)
```

### Operating System

Windows 10

### Selenium version

C# 4.0.0.0

### What are the browser(s) and version(s) where you see this issue?

Edge 98.0.1108.62

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 98.0.1108.62

**Comment by diemol** [comment]
It might be that the embedded application cannot be opened concurrently.

In any case, we only support the latest version of Selenium, so you'd need to update before we have a look at this.

**Comment by diemol** [comment]
I will leave some links below in case you have more questions.
