### ISSUE TITLE
[🚀 Feature]: Selenium Manager resources usage improvement (Chrome driver)

### ISSUE THREAD

**Issue by Andreito95** [SeleniumHQ/selenium#12642]
### Feature and motivation

Hello, 

i noticed that running 25 processes, so 25 drivers (headless) created with Selenium Managers use an insane amount of resources (using Chrome driver).
Instead, third party lib webdriver-manager, for example, supports with 25 drivers (headless) without any problem.
As resources i am talking about CPU usage, stuck at 100% when webdriver-manager turns it around 60% usage (same environment, same processes, same amount of parallel processes)

Is it a known issues? Is it possible to lower down the resources usage?
I know that Selenium Manager is still in tests so, it may be just this beta version and it will be improved soon :)

### Usage example
```
from seleniumwire import webdriver

driver = webdriver.Chrome(
    options=set_properties(logger, browser_options)
    )
```

**Comment by titusfortner** [comment]
The issue is that each process is storing Selenium Manager in temp directory and using from there. This PR will address your issue by putting the binary in one place and executing it from there — #12539
