### ISSUE TITLE
Webdriver Getting Started page, GoogleSuggest example class, gets compile error

### ISSUE THREAD

**Issue by bbrecken** [SeleniumHQ/selenium#1264]
1. Go to https://code.google.com/p/selenium/wiki/GettingStarted
2. run java code in the 2nd example, GoogleSuggest class

Result:
Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"class name","selector":"gssb_e"}

Expected:
Build Successful, results in Console
Attached is a fixed version of this code that builds successfully and prints results to the Console:
[GoogleSuggestFixed.txt](https://github.com/SeleniumHQ/selenium/files/36249/GoogleSuggestFixed.txt)

**Comment by AJ-72** [comment]
@ddavison Is the wiki content managed in github? I couldn't find it in doc or selenium repo

**Comment by lukeis** [comment]
This wiki page is in github now:
https://github.com/SeleniumHQ/selenium/wiki/Getting-Started

you can clone the repo with this location:

https://github.com/SeleniumHQ/selenium.wiki.git

**Comment by ddavison** [comment]
sorry - didn't see that comment :)  thanks @lukeis

**Comment by AJ-72** [comment]
@lukeis @ddavison I can't find a way to create a PR for the wiki update. I tried what's mentioned here - https://gist.github.com/larrybotha/10650410 . You can see the change in the above line.

**Comment by ddavison** [comment]
fixed https://github.com/SeleniumHQ/selenium/wiki/Getting-Started - thanks @AJ-72
