### ISSUE TITLE
[🚀 Feature]: Do you have an any logic to download the particular version of chromedriver or Is it already exists means specify the path of folder.

### ISSUE THREAD

**Issue by sandi-init** [SeleniumHQ/selenium#12645]
### Feature and motivation

For now, You are downloading the latest version of chrome .

I have to understand how do you download the chromedriver latest version and which folder is the code present to download the version? and Any provision for download the particular version of chromedriver.

I need some response from your side .

Please ,Let me know If you noticied?

### Usage example

Webdriver.Chrome() - launches Chrome with latest browser version available in local machine.

But If we specify the webdriver.Chrome(service=Service(executable_path="any_version")),options = options) - It will not launch the browser that assign the driver to the browser.

We have any provision to download particular version like webdriver-manager does like,

ChromeDriverManager().install() -> download the latest.

ChromeDriverManager(driver_version="version").install() -> download particular version.

Because , we can avoid using some other library inside the another library.

**Comment by diemol** [comment]
This is how Selenium does it https://www.selenium.dev/documentation/selenium_manager/

`ChromeDriverManager` is a 3rd party tool not managed by the Selenium project.

**Comment by sandi-init** [comment]
Which file you are downloading the Chromedriver and stored it in cache.?

**Comment by sandi-init** [comment]
Webdriver.Chrome() - launches Chrome with latest browser version available in local machine.

But If we specify the webdriver.Chrome(service=Service(executable_path="any_version")),options = options) - It will not launch the browser that assign the driver to the browser.

how the above line works?
