### ISSUE TITLE
press and hold Key via Actions.keyDown(Keys.SHIFT);

### ISSUE THREAD

**Issue by Basti890** [SeleniumHQ/selenium#1265]
After update from Selenium (with Maven) 2.47.1 to 2.48.2 (latest) the action which shall provide pressing a key and holding it down seems to fail.
here my Code:
        WebDriver webDriver = getDriver();
        WebElement row1 = webDriver.findElement(MyBy.byTextIgnoreCSS("perthes_1855_0001.jpg")).findElement(
            By.xpath("ancestor::td"));
        Actions selectRows = new Actions(webDriver);
         WebElement row15 = webDriver.findElement(MyBy.byTextIgnoreCSS("perthes_1855_0015.jpg")).findElement(
             By.xpath("ancestor::td"));
        selectRows.keyDown(Keys.SHIFT);
        selectRows.click(row1);
        selectRows.click(row1);
        selectRows.click(row15);
        selectRows.keyUp(Keys.SHIFT);
        selectRows.perform();
with that 15 rwos are selectet by using version 2.47.1 but with version 2.48.2 only row 15 is selectet.

**Comment by AJ-72** [comment]
@Basti890 Please provide the url against which the above code can be executed?

**Comment by Basti890** [comment]
the url is from a local jetty server of http://server.mycore.de/svn/maven/mets-editor-frontend/trunk when updating the version of Selenium and selenium-utils (an own project as we use selenium and many projects for testing)
[pom.txt](https://github.com/SeleniumHQ/selenium/files/36656/pom.txt) and replacing the pom.xml with my attached one (had to rename it as XML-Files are not supportet for upload.) than building it with maven (or just start the jetty server with mvn jetty:run).

Then you'll have the testing enviorment. the URL will be: http://localhost:9301/classes/META-INF/resources/module/mets/example/mets-editor.html

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
