### ISSUE TITLE
Schedule time is not working

### ISSUE THREAD

**Issue by Barthomeus** [SeleniumHQ/selenium#1267]
I've got problem with schedule the time when Selenium should start work. When I click on Play current test case everything works fine, but when I set up starting time at Scheduler nothing happen :/ Any idea why ?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
