### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.NoSuchDriverException: on Raspberry Pi 4B with Python

### ISSUE THREAD

**Issue by unterguru** [SeleniumHQ/selenium#12679]
### What happened?

I try to run selenium on a Raspi via Python, and don't manage to startup using "webdriver.ChromeOptions()".

I can run Selenium like this:

```
browser_driver = Service('/usr/lib/chromium-browser/chromedriver')
page_to_visit = webdriver.Chrome(service=browser_driver)
```
and it works fine. 

Now, I try to include a proxy, and try to run like this:

```
from selenium import webdriver
from selenium.webdriver.common.proxy import Proxy, ProxyType

chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=chrome_options)
```

I already added this: like described in Troubleshooting page:

pi@pi-vgw:~ $ echo $PATH
/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/**usr/lib/chromium-browser/chromedriver** 

But it didn't help.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.proxy import Proxy, ProxyType

chrome_options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=chrome_options)
```

### Relevant log output

```shell
pi@pi-vgw:~ $ env -i DISPLAY=:0.0 /usr/bin/python3 /home/pi/try3.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/selenium_manager.py", line 73, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/selenium_manager.py", line 57, in get_binary
    raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
selenium.common.exceptions.WebDriverException: Message: Unable to obtain working Selenium Manager binary; /usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/linux/selenium-manager


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/try3.py", line 31, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Raspbian GNU/Linux 11 bullseye

### Selenium version

selenium          4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chromium 113.0.5672.95 Built on Raspbian , running on Raspbian 11

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.95 (917deeefba48411c7b40ba19aef7b229bf48acd7-refs/branch-heads/5672_63@{#13})

**Comment by diemol** [comment]
>Message: Unable to obtain working Selenium Manager binary;

Selenium Manager does not support your architecture. See #12651 for more details.

Please follow your initial approach for your use case:
```python
browser_driver = Service('/usr/lib/chromium-browser/chromedriver')
page_to_visit = webdriver.Chrome(service=browser_driver)
```

and then add a proxy to it.

**Comment by JoGro-code** [comment]
what imports are you doing to get this run? 

browser_driver = Service('/usr/lib/chromium-browser/chromedriver')
page_to_visit = webdriver.Chrome(service=browser_driver)

**Comment by titusfortner** [comment]
Just webdriver. Like this now:

service = webdriver.ChromeService()
    driver = webdriver.Chrome(service=service)
