### ISSUE TITLE
[🐛 Bug]: In 4.12.0 unable to download Firefox Browser, In case Firefox is not installed

### ISSUE THREAD

**Issue by prnbtr09** [SeleniumHQ/selenium#12670]
### What happened?

Steps to Reproduce:
1. Uninstall Firefox browser from windows machine
2. Provide Firefox option and provide browserVersion let us say 115
3. Initialize Firefox driver using above firefox options
4. Trigger the execution

Actual Result:
Unable to download firefox browser 115

Expected Result:
As per latest functionality Browser binary should be downloaded alongside geckodriver and execution should take place

Additional Details:
I tried running Selenium Manager in Debug mode: there I saw browser is getting downloaded in cache section but it is unable to locate gecko driver which is also available in .cache

### What browsers and operating systems are you seeing the problem on?

os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.20.1'

Framework:
Selenium with Java and JDK used 11 and 17 both.

Error:
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: Optional.empty, moz:debuggerAddress: true, moz:firefoxOptions: {}}, error Command failed with code: 65, executed: [--browser, firefox, --output, json, --browser-version, 115]
firefox 115 cannot be downloaded

**Comment by titusfortner** [comment]
Firefox does not work when capabilities sent to the driver include `"beta"` or `"nightly"`, so we have to remove the capability after Selenium Manager gets the requested version. The way we did it does not work in Java. We're working on an updated release.

**Comment by prnbtr09** [comment]
@titusfortner actually If I don't have Firefox in my machine, I am unable to run stable one as well. In fact I should have Firefox browser stable one needs to be installed.

I got following exception:
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}, error Command failed with code: 65, executed: [--browser, firefox, --output, json]
firefox 117 cannot be downloaded

**Comment by titusfortner** [comment]
If you set `browserVersion` right now, it won't work, because Firefox is complaining about how we are trying to delete it.
If you don't set a value, it will do everything as expected.

**Comment by titusfortner** [comment]
If you think there is a different error, turn on logging and see what Selenium Manager is doing — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by diemol** [comment]
This should work. The error was when using `browserVersion` and Grid. 

Can you share the debug log output to see what the issue is?

**Comment by prnbtr09** [comment]
Hello,

Sure following is the log:


2023-09-04 23:17:43 FINE - Selenium Manager binary found at: C:\Users\PRINCE~1\AppData\Local\Temp\selenium-manager18310702451170010240031449025511412\selenium-manager.exe 
2023-09-04 23:17:43 FINE - Executing Process: [--browser, firefox, --output, json, --debug] 
2023-09-04 23:17:58 FINE - geckodriver not found in PATH 
2023-09-04 23:17:58 FINE - firefox not found in PATH 
2023-09-04 23:17:58 FINE - Running command: REG QUERY HKCU\Software\Mozilla\Mozilla Firefox /v CurrentVersion 
2023-09-04 23:17:58 FINE - Output: "" 
2023-09-04 23:17:58 FINE - firefox not found in the system 
2023-09-04 23:17:58 FINE - Required browser: firefox 117.0 
2023-09-04 23:17:58 FINE - Downloading firefox 117.0 from https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe 
2023-09-04 23:17:58 WARNING - firefox 117 cannot be downloaded 
Exception in thread "main" org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {}}, error Command failed with code: 65, executed: [--browser, firefox, --output, json, --debug]
firefox 117 cannot be downloaded


My code to initalize Firefox driver is as follows:


new SeleniumLogger().setLevel(Level.FINE);
        WebDriver driver=new FirefoxDriver();
        driver.get("https://www.saucedemo.com/");
        driver.quit();
        
Regards,
PrinceAutomationDestination

**Comment by diemol** [comment]
@bonigarcia what is the meaning of `failed with code: 65`?

**Comment by titusfortner** [comment]
It's like connection reset or 403 error. It means it can't access the url. It seems like there should be more information in this error, though.  Oh, I wonder if using ftp is going to break things for people.

**Comment by titusfortner** [comment]
We might need to provide more/different proxy support...

**Comment by bonigarcia** [comment]
> @bonigarcia what is the meaning of `failed with code: 65`?

Error code 65 means "data error" and is the error code Selenium Manager uses for something unexpected. It is typically due to some bad input, but it might also be due to other issues (e.g., connectivity).

My first impression about this issue was caused by a connectivity problem, as we have seen before in other reported issues (e.g., when executing Selenium Manager behind a proxy). But I don't know why these logs are incomplete. When Selenium Manager fails, an `ERROR` log should also be displayed. But in the logs reported by @prnbtr09, there is only a `WARNING`.

@prnbtr09 Can you please download Selenium Manager from here?

https://github.com/SeleniumHQ/selenium/tree/trunk/common/manager/linux

With that binary, using the shell, please execute the following commands:

```
./selenium-manager --browser firefox --debug
```

```
./selenium-manager --browser firefox --trace
```

**Comment by bonigarcia** [comment]
Sorry, you are using Windows. Then your binary is the following:

https://github.com/SeleniumHQ/selenium/tree/trunk/common/manager/windows

**Comment by bonigarcia** [comment]
@prnbtr09 Also, please try to download directly the Firefox installer: https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe

**Comment by prnbtr09** [comment]
sure please find below the logs:

1st command: .\selenium-manager.exe --browser firefox --debug
Log:
```
DEBUG   geckodriver not found in PATH
DEBUG   firefox not found in PATH
DEBUG   Running command: REG QUERY HKCU\Software\Mozilla\Mozilla Firefox /v CurrentVersion
DEBUG   Output: ""
DEBUG   firefox not found in the system
DEBUG   Required browser: firefox 117.0
DEBUG   Downloading firefox 117.0 from https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe
```

2nd Command: .\selenium-manager.exe --browser firefox --trace
Log:
```
TRACE   Checking geckodriver in PATH
DEBUG   geckodriver not found in PATH
TRACE   Original path:  - Escaped path:
TRACE   Checking firefox in PATH
DEBUG   firefox not found in PATH
TRACE   Using shell command to find out firefox version
DEBUG   Running command: REG QUERY HKCU\Software\Mozilla\Mozilla Firefox /v CurrentVersion
DEBUG   Output: ""
DEBUG   firefox not found in the system
TRACE   Reading metadata from C:\Users\Prince Batra\.cache\selenium\se-metadata.json
TRACE   Browser with valid TTL. Getting firefox version from metadata
DEBUG   Required browser: firefox 117.0
DEBUG   Downloading firefox 117.0 from https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe
TRACE   Downloading https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe to temporal folder "C:\\Users\\PRINCE~1\\AppData\\Local\\Temp\\selenium-managerHr1VyQ"
TRACE   File to be downloaded: Firefox%20Setup%20117.0.exe
TRACE   File downloaded to temporal folder: C:\Users\PRINCE~1\AppData\Local\Temp\selenium-managerHr1VyQ\Firefox%20Setup%20117.0.exe
TRACE   The detected extension of the compressed file is exe
TRACE   Uncompress C:\Users\PRINCE~1\AppData\Local\Temp\selenium-managerHr1VyQ\Firefox%20Setup%20117.0.exe to C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0
TRACE   Running command: robocopy C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0\core C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0 /e /move
ERROR   firefox 117 cannot be downloaded
```

Note: for chrome it is working fine without any issues. Also, this is my personal laptop so nothing as such firewall or all are turned on

**Comment by prnbtr09** [comment]
Also, I am able to download firefox from this location manually, by directly hitting the url in browser:
Also, please try to download directly the Firefox installer: https://ftp.mozilla.org/pub/firefox/releases/117.0/win64/en-US/Firefox%20Setup%20117.0.exe

**Comment by bonigarcia** [comment]
There are several unexpected things here.

First, the first command should end in `ERROR` as well. Is that a copy-paste mistake?

Second, the following log is weird (maybe this is the cause of the problem):

```
TRACE Uncompress C:\Users\PRINCE~1\AppData\Local\Temp\selenium-managerHr1VyQ\Firefox%20Setup%20117.0.exe to C:\Users\Prince Batra.cache\selenium\firefox\win64\117.0
```

The second path, i.e., the target, has a missing backslash between the home and the `.cache` path. In other words, it should be `C:\Users\Prince Batra\.cache\...` but not `C:\Users\Prince Batra.cache\...`.

Can you please verify the content of these folders in your local system (although the second one should not exist, in theory):

`C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0`
`C:\Users\Prince Batra.cache\selenium\firefox\win64\117.0`


Third, it is unclear if the `robocopy` command works on your machine. I believe this utility is available in Windows (on `C:\windows\system32`) out of the box, but maybe I am wrong. Can you please run the following in the shell:

```
robocopy
```

**Comment by bonigarcia** [comment]
I see now the path is correct. Please embed the traces using three backtick symbols (```) since otherwise, they are not rendered correctly. I have edited your comment accordingly.

The log I mentioned is as follows, which is correct:

```
TRACE   Uncompress C:\Users\PRINCE~1\AppData\Local\Temp\selenium-managerHr1VyQ\Firefox%20Setup%20117.0.exe to C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0
```

This way, I see two possible causes for this problem:

1. You don't have `robocopy` in your machine (please run the command before to check it)
2. The 7z uncompression is not working properly in your machine for some reason I don't know. To check it, please let me know the content of this folder:

```
C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0
```

**Comment by bonigarcia** [comment]
Just in case the execution of `robocopy` is problematic, I have prepared an alternative version of Selenium Manager that avoids it.

@prnbtr09 Please download the new Selenium Manager binary from here: [selenium-manager_windows-x32](https://github.com/SeleniumHQ/selenium/suites/15832206183/artifacts/903307532)

Uncompress it, and run the following command with that binary:

```
selenium-manager --browser firefox --trace
```

**Comment by prnbtr09** [comment]
Please find below the content for `C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0`
@bonigarcia 

![image](https://github.com/SeleniumHQ/selenium/assets/46184458/21537e8e-b36d-4a39-a3e7-2ad103d10d0c)
![image](https://github.com/SeleniumHQ/selenium/assets/46184458/225af464-0329-476e-9b3e-84a377c1fab7)
![image](https://github.com/SeleniumHQ/selenium/assets/46184458/34f43653-c669-45df-b36a-0c0f41d81c51)

**Comment by prnbtr09** [comment]
Robocopy result:
![image](https://github.com/SeleniumHQ/selenium/assets/46184458/33cf5e2b-5dbb-43dd-b44a-419a8f529f5e)

**Comment by prnbtr09** [comment]
@bonigarcia 
result of running following command:
selenium-manager --browser firefox --trace

![image](https://github.com/SeleniumHQ/selenium/assets/46184458/d20ccd7d-7bc4-45ae-bf85-df19bd42708c)

**Comment by bonigarcia** [comment]
The content of `C:\Users\Prince Batra\.cache\selenium\firefox\win64\117.0` is correct. You have Firefox in your machine, downloaded with Selenium Manager. And you have `robocopy`, as expected.

Therefore, the only thing I imagine now is a race condition between the execution of `robocopy` and the line in which the Firefox binary is checked (since `firefox.exe` is already there correctly).

In any case, the second time you execute your original test (without removing the cache), the Firefox binary should be found in the cache since it is already there, and it might be found by Selenium Manager.

About the execution of the new binary, it may be failing since that folder already has content. Please use that binary (the one in your downloads folder) to execute the following:

```
selenium-manager --browser firefox --trace --clear-cache
```

**Comment by prnbtr09** [comment]
@bonigarcia 
This time I got this response which does not have error:
![image](https://github.com/SeleniumHQ/selenium/assets/46184458/f6da8635-16d1-4fd6-b5db-b76db3cac377)

**Comment by prnbtr09** [comment]
@bonigarcia 
so is there some issue in Selenium Manager of 4.12.0 or what is the error?

**Comment by bonigarcia** [comment]
I'm not sure about this. As I said, maybe it is a race condition in the execution of `robocopy`. In any case, and since it seems it is working better without it (the last execution is correct), I am going to remove it for the next version of Selenium Manager.

Now that Firefox is in the cache, your original test (using selenium-java 4.12.x) should work, even with the former Selenium Manager binary.

**Comment by prnbtr09** [comment]
Yes @bonigarcia you are correct:
After running following command:
selenium-manager --browser firefox --trace --clear-cache

I am able to execute test case through 4.12.0

Next, when I am manually removing and rerunning with 4.12.0, then same issue.

You are right you will have to remove it, thanks for same.

We will get the change in next release or as as patch for 4.12.0

**Comment by bonigarcia** [comment]
In any case, the `--clear-cache` should not be necessary. To confirm it, please do the following (again, with the Selenium Manager in your downloads folder). First:
```
selenium-manager --browser firefox --trace --clear-cache
```

And then, the same command, but without the `--clear-cache`, which should reuse the Firefox binary already in the cache:

```
selenium-manager --browser firefox --trace
```

Please let me know if both commands work.

**Comment by prnbtr09** [comment]
Done @bonigarcia 

![image](https://github.com/SeleniumHQ/selenium/assets/46184458/82b191ee-98a0-45ca-b336-dd4ed60da566)

**Comment by bonigarcia** [comment]
Ok, it works as expected. Thanks a lot for your help debugging this, @prnbtr09. I am going to prepare a PR with that change. It will be available for next Selenium release.

**Comment by prnbtr09** [comment]
Thanks for taking the action on it @bonigarcia . It would be with multiple people so let us get it fixed, thanks for such a prompt response

**Comment by KartikGavhale** [comment]
hi @bonigarcia  , Im facing similar issue but with flacky results , on some system its working fine and on other systems is showing me the following error . 
[ERROR] Failures: 
[ERROR]   openBrowser.launchChrome:12 » NoSuchDriver Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}, error Command failed with code: 65, executed: [--browser, chrome, --output, json]
error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip): error trying to connect: dns error: failed to lookup address information: Try again
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.2.0-26-generic', java.version: '17.0.8'
Driver info: driver.version: ChromeDriver

Also i have observed that when it trys to download the driver its taking unusually longer time then throwing these kind of error. I have tried with various system in our organisation even in virtual environment.
![Screenshot from 2023-09-11 20-30-11](https://github.com/SeleniumHQ/selenium/assets/107868328/49718a2a-66c9-4b74-a971-ddf42aa8d530)

**Comment by titusfortner** [comment]
@KartikGavhale that is a different issue. You can turn on logging to get more details https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
But the error points to a DNS issue. Are you behind a proxy or on a corporate network that might be affecting this?

**Comment by KartikGavhale** [comment]
@titusfortner  thank you for the responce . It was a DNS issue thanks for pointing out it has been resolved.

**Comment by YashUmredkar** [comment]
Try updating all the software updates and install the latest selenium version

**Comment by titusfortner** [comment]
This was fixed.
