### ISSUE TITLE
[🐛 Bug]: NoSuchDriverException in upgrade 4.10 to 4.12

### ISSUE THREAD

**Issue by beliaev-maksim** [SeleniumHQ/selenium#12681]
### What happened?

Using latest stable snap of firefox `installed:          117.0-2                 (3068) 248MB -` receive an error in the code that worked fine in 4.10

I think this is because now there is a check for `Path(path).is_file()`. While Linux executable can be called without a full path

### How can we reproduce the issue?

```shell
import pytest
from selenium import webdriver

from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service


@pytest.fixture(scope='session')
def driver(request):
    """Set up webdriver fixture."""
    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    service = Service(executable_path="firefox.geckodriver")
    driver = webdriver.Firefox(options=options, service=service)
    driver.set_window_size(1920, 1080)
    driver.maximize_window()
    driver.implicitly_wait(10)

    yield driver
    driver.quit()
```

### Relevant log output

```shell
test setup failed
request = <SubRequest 'driver' for <Function test_1>>

    @pytest.fixture(scope='session')
    def driver(request):
        """Set up webdriver fixture."""
        options = Options()
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
    
        service = Service(executable_path="firefox.geckodriver")
>       driver = webdriver.Firefox(options=options, service=service)

conftest.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py:59: in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

service = <selenium.webdriver.firefox.service.Service object at 0x7f537b2fc5b0>
options = <selenium.webdriver.firefox.options.Options object at 0x7f537b2fc370>

    @staticmethod
    def get_path(service: Service, options: BaseOptions) -> str:
        path = service.path
        try:
            path = SeleniumManager().driver_location(options) if path is None else path
        except Exception as err:
            msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
            raise NoSuchDriverException(msg) from err
    
        if path is None or not Path(path).is_file():
>           raise NoSuchDriverException(f"Unable to locate or obtain driver for {options.capabilities['browserName']}")
E           selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py:44: NoSuchDriverException
```

### Operating System

Ubuntu 22.04

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 117

### What are the browser driver(s) and version(s) where you see this issue?

preinstalled in snap 0.33.0

**Comment by titusfortner** [comment]
With 4.11+ you shouldn't need to use the Service class and specify the driver. If there is a geckodriver on PATH Selenium will use it, and if it can't find it, it can download it for you.

If you have a driver you want to force Selenium to use, and it is not named geckodriver and/or it is not on PATH, I think it is actually good to require specifying the full path, even if this is a change from 4.10. The parameter name is "executable_path" not "executable".

I think things are working as desired.

**Comment by beliaev-maksim** [comment]
@titusfortner thanks for the clarification

could the error message be updated to include a bit more details ? At least for transition period

**Comment by titusfortner** [comment]
I think everything I explained here is already in the link that was printed. The only difference being, yes it needs to be a full path, but then we'd have to parse that was the issue and add a custom message. I think what we have is sufficient for now.
