### ISSUE TITLE
[🚀 Feature]: How to directly open a running session window for preview through URL requests in selenium grid 4.8

### ISSUE THREAD

**Issue by Evan-LY** [SeleniumHQ/selenium#12686]
### Feature and motivation

How to directly open a running session window for preview through URL requests in selenium grid 4.8

### Usage example

![微信截图_20230905114548](https://github.com/SeleniumHQ/selenium/assets/37667883/944adc2d-17cb-48e5-bd3d-6ea8910683cf)

**Comment by diemol** [comment]
Duplicate of #12075
