### ISSUE TITLE
Edge browser throws not implemented exception with special character in Selenium Grid

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#1268]
I am using Selenium Gird, version 2.48.2. When I execute the test, I get a strange error message, like:

> org.openqa.selenium.WebDriverException: ၐݳ▘ӳtor not implemented (WARNING: The server did not provide any stacktrace information)

or

> org.openqa.selenium.WebDriverException: ၐ݈▘tor not implemented (WARNING: The server did not provide any stacktrace information)

The error is here:
`WebElement loginBtn = webDriver.findElement(By.xpath("//button[contains(., 'Einloggen')]"));`

I don't know what's wrong with that.

I register the node like this:

`java -Dwebdriver.edge.driver=C:\Selenium\MicrosoftWebDriver.exe -jar selenium-server-standalone-2.48.2.jar -role node -browser browserName=MicrosoftEdge,platform=WINDOWS -hub http://10.0.50.34:4444/grid/register/ -trustAllSSLCertificates`

and in my java code:

`capabilities = DesiredCapabilities.edge();`
`webDriver = new RemoteWebDriver(new URL("http://10.0.50.34:4444/wd/hub"), capabilities);`

Is there something wrong with EdgeDriver?

**Comment by ddavison** [comment]
The Selenium project does not maintain the Edge driver, Microsoft does..  Go ahead and see their [status page](https://dev.modern.ie/platform/status/webdriver/details/) and bring it up with them.

**Comment by louis57** [comment]
Oh ok, thank you

**Comment by ddavison** [comment]
no problem!

**Comment by nadavhala** [comment]
hey guys, 

I encountered the same issue and didn't understand what needs to be done here exactly...

thanks!
