### ISSUE TITLE
[🚀 Feature]: Configure Selenium Grid as Windows Service

### ISSUE THREAD

**Issue by devqaio** [SeleniumHQ/selenium#12683]
### Feature and motivation

Currently, to configure Selenium Grid as windows service, we require a third party tool like nssm. To onboard these tools in organisations is a cumbersome process as it has to go through multiple security approvals and the security impact on the design of such tolls are generally not available.

If there could be a capability available with in the grid to configure it as a service using built-in processes with in the OS, it would be helpful and easy to on-board with in the organisation. For an on-premise non docker grid, this will be helpful as it doesn't require any manual intervention during a server maintenance/server fail safe recovery, where the service will start automatically bringing the grid up and live.

### Usage example

If there could be a capability available with in the grid to configure it as a service using built-in processes with in the OS, it would be helpful and easy to on-board with in the organisation. For an on-premise non docker grid, this will be helpful as it doesn't require any manual intervention during a server maintenance/server fail safe recovery, where the service will start automatically bringing the grid up and live.

E.g., for Windows, we can use the built-in capability/tool SC.exe to configure a service that will execute the jar for a specified role. Also, it will take the CLI parameters as defined to make the maintenance easier.

I tried with winsw, but when multiple services run using winsw, it gives issues with restart of one or the other service.

**Comment by diemol** [comment]
What issue are you running into? Why can't it be configured as a service?

**Comment by devqaio** [comment]
Most of the processes I could find asks to use nssm. However, org security is not approving this tool as the publisher detail is not available and it doesn't have any security design diagram available to understand it's components and their impact on security.

Another option available to use WinSW, but there is a catch. Some of the other services uses winsw and they don't require any action like start, stop etc. on those. However, for the on premise grid, we have to stop/restart the services frequestly as part of maintenance like jar upgrade or driver exe upgrades or jdk upgrade etc. I tried configuring with WinSW, but that doen't allow me to stop it. Every time, I have to delete the service and recreate. And this impacts the automated jobs we have to handle the maintenance.

Moreover, I tried the option to utilize the built-in utility SC.exe from Windows to configure the service, but it doesn't start the service. While starting it, it ends up with error and the hub doesn't spin up. Once it works for the hub, we will implement the same in all the nodes we have. As we are not expecting huge number of test cases for execution, the hub-node model is the best fit over full distributed one.

If the grid jar ships with some solution to configure it as a service, it will be helpful to set up an in-house grid for firms with a very complex security requirement. As it's not very complex to get approval for Selenium from info-sec team, based on a business case and detailed architecture, the grid jar gets auto approved as part of Selenium package.

**Comment by diemol** [comment]
You are also asking the same question in our Slack channel, and we have been replying to help you figure it out. We are not going to implement something specific to run Grid as a Windows service, but we can help you debug the errors and eventually, we can together document how to do it.

>While starting it, it ends up with error and the hub doesn't spin up.

Therefore, as I commented in Slack, what are the errors you are getting? What have you tried?

**Comment by devqaio** [comment]
@diemol - I will keep the discussion on in Slack. Based on a successful closure, I will update the details here to close the ticket.

**Comment by diemol** [comment]
Is there something you'd like to add or can we close this?

**Comment by diemol** [comment]
I will close this as there is nothing for us to do. But feel free to add more comments if you want to document your solution.
