### ISSUE TITLE
[🐛 Bug]: Version 4.12 doesn't support chrome 116

### ISSUE THREAD

**Issue by federicomartinlara1976** [SeleniumHQ/selenium#12680]
### What happened?

The 4.12 version of the Java driver doesn't support chrome version 116.

And I've updated the chromedriver version to BETA 117.0.5938.35

I think that the Java driver has not updated.

### How can we reproduce the issue?

```shell
Launch a Java application that uses the selenium chrome driver
```

### Relevant log output

```shell
10:46:33.820 [http-nio-9093-exec-9] ERROR n.b.c.s.s.w.ChromeWebDriverFactory - Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /opt/google/chrome/chrome 
Host info: host: 'discovery', ip: '192.168.1.135'
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-159-generic', java.version: '17.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless], binary: /opt/google/chrome/chrome, extensions: []}}]}]
```

### Operating System

Ubuntu

### Selenium version

Java 4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver BETA 117.0.5938.35

**Comment by diemol** [comment]
You have a ChromeDriver binary on the PATH, and this is what is getting used. You can use [debug logging](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/) to understand better the message. 

The solution is to fix that ChromeDriver binary, delete it, and let Selenium handle the browser <-> driver match.

If you have questions, I will leave some links below you can use to ask them.

**Comment by federicomartinlara1976** [comment]
The bug persists.

**Comment by diemol** [comment]
Come to the Slack or Matrix channel, and we will be happy to help you debug.

**Comment by federicomartinlara1976** [comment]
Now the error is:

Could not start a new session. Response code 500. Message: unknown error: no chrome binary at /opt/google/chrome/chrome 

And chrome is the binary.

**Comment by federicomartinlara1976** [comment]
Solved!.

I've used the Firefox driver. It seems that the Chrome drived is not stable.

Thanks!

**Comment by diemol** [comment]
If you wish, share the output of https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
