### ISSUE TITLE
[🐛 Bug]: Selenium Manager evaluating TTL too early

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12691]
### What happened?

This may be a bug, or this may be an issue of differing order of principles, so I'll recap mine in case that's the issue:

1. If a user tells Selenium to do something specific, it has to do it (they pass in a specific version of browser or a location of a driver or a browser, and while in beta Selenium treats having a driver on PATH as a user telling it to do something specific). If it can't do it, it errors.
2. If user doesn't specify, then Selenium does whatever it takes to execute. Even if it isn't the ideal driver version, even if they haven't run a session in forever, even if they are offline or behind a proxy. Selenium can throw a warning message explaining why something isn't ideal, but it runs the session. (Note: if the driver complains, that's a separate issue).
3. Selenium ensures that the "right" browser and driver versions are used by locating or downloading as necessary
4. Selenium improves the performance of step 3 by only looking for updates when necessary or after a certain period of time has transpired. But this is performance enhancement only, not something to prohibit functionality..

The log is below, but extra info:

```
titusfortner@SL-1837 code % ls -al ~/.cache/selenium/chromedriver/mac-x64 
drwxr-xr-x@ 4 titusfortner  staff  128 Sep  3 07:29 .
drwxr-xr-x@ 3 titusfortner  staff   96 Aug 30 07:58 ..
drwxr-xr-x@ 3 titusfortner  staff   96 Aug 30 07:58 116.0.5845.96
```

It's just that the ttl is expired:
```
titusfortner@SL-1837 code % cat ~/.cache/selenium/se-metadata.json 
{
  "browsers": [],
  "drivers": [
    {
      "major_browser_version": "116",
      "driver_name": "chromedriver",
      "driver_version": "116.0.5845.96",
      "driver_ttl": 1693797814
    }
  ]
}
```

### How can we reproduce the issue?

```shell
set ttl to a value in the past and run with `--browser chrome --output json --offline`
```

### Relevant log output

```shell
2023-09-05 08:48:43 FINE - [SeleniumManager getBinary] Selenium Manager binary found at: /var/folders/rh/25cw4qq10_157fjpztk0psx80000gn/T/selenium-manager18251076474367938167165495520198471/selenium-manager 
2023-09-05 08:48:46 FINE - [SeleniumManager runCommand] Executing Process: [--browser, chrome, --output, json, --debug, --offline] 
2023-09-05 08:48:47 FINE - [SeleniumManager] Using Selenium Manager in offline mode 
2023-09-05 08:48:47 FINE - [SeleniumManager] chromedriver not found in PATH 
2023-09-05 08:48:47 FINE - [SeleniumManager] chrome detected at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
2023-09-05 08:48:47 FINE - [SeleniumManager] Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version 
2023-09-05 08:48:47 FINE - [SeleniumManager] Output: "Google Chrome 116.0.5845.140 " 
2023-09-05 08:48:47 FINE - [SeleniumManager] Detected browser: chrome 116.0.5845.140 
2023-09-05 08:48:47 WARNING - [SeleniumManager] Unable to discover proper chromedriver version in offline mode 
2023-09-05 08:48:47 FINE - [SeleniumManager getDriverPath] Using driver at location: , browser at location
```

### Operating System

Ventura

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

116

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
After reading the issue several times and chatting with Titus, the issue is that the ChromeDriver in the cache is not being used, even if the TTL expired, and SM is offline. 

>if the offline flag is true then it needs to check the cache
>or, always check cache, then check if ttl expired, and then check if offline or not

**Comment by diemol** [comment]
@bonigarcia could you please check?

**Comment by bonigarcia** [comment]
This is not a bug, it's a feature :)

The drivers in the cache are used without asking remote endpoints during the TTL (1 hour currently). Then, the metadata is considered *stale* and need to be refreshed (i.e., Selenium Manager needs to ensure what is the *proper* driver version for a given browser).

But we can do something different for the offline mode if you want. Selenium Manager can detect and report the latest version of a given driver available in the cache when operating in offline mode. I believe it would work in most cases.

**Comment by titusfortner** [comment]
Right, this is why I listed my priorities. I don't believe in staleness. TTL should only be for performance improvement.

**Comment by diemol** [comment]
We should try to get the session working for the user. In this case, try to use the driver in the cache, given that it matches the browser.

**Comment by titusfortner** [comment]
I want to go further and use it even if it doesn't match the browser. Throw a warning that it isn't what we want but it's the best available.

**Comment by diemol** [comment]
> I want to go further and use it even if it doesn't match the browser. Throw a warning that it isn't what we want but it's the best available.

I am not sure if that would be confusing for the user when an error due to browser - driver mismatch happens.

**Comment by titusfortner** [comment]
Selenium logs a warning to console, and the driver errors if it is a problem (> 1 version different for Chrome). We used to do this with the driver checking for previous versions if it couldn't find the latest, it's weird to approach looking in cache dramatically differently.

**Comment by titusfortner** [comment]
@bonigarcia can we make this change for 4.13?

**Comment by titusfortner** [comment]
I'll add a "needs decision" for matching any driver version, but if a valid driver exist in cache it needs to be used in offline mode even if ttl has expired.

**Comment by bonigarcia** [comment]
Ok, I'll add some logic to get the best possible driver from the cache when the regular algorithm does not work (e.g., in offline mode or other error).

**Comment by titusfortner** [comment]
This is good, thank you.
