### ISSUE TITLE
[🚀 Feature]: use lowercase header names

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#12697]
### Feature and motivation

I would suggest to convert all header names to lowercase in the [`HttpMessage`](https://github.com/SeleniumHQ/selenium/blob/938058d969de2d2512eb8e3a47acea022927c4f2/java/src/org/openqa/selenium/remote/http/HttpMessage.java).
It might be [helpful in the future](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2) to have only lower case header names. 

The header names should be in general treated case-insensitive, but there might be code somewhere not aware of this, so i would see this in Selenium 5.

### Usage example

There is currently a hidden issue due to the case-sensitive map used in the HttpMessage.
The order of headers set depends currently on the map implementation and not on the [order of adding them](https://www.rfc-editor.org/rfc/rfc2616#section-4.2), this can be observed here:
https://github.com/SeleniumHQ/selenium/blob/938058d969de2d2512eb8e3a47acea022927c4f2/java/test/org/openqa/selenium/remote/http/HttpMessageTest.java#L53-L57
`message.getHeader("Content-Length")` should actually return `"1024"`

**Comment by diemol** [comment]
Makes sense to me.

**Comment by VAIBHAVPANT07** [comment]
assign me

**Comment by titusfortner** [comment]
We don't assign specific issues, but if you make a PR we'll happily review it. Thanks.

**Comment by manuelsblanco** [comment]
@diemol  Is this still a issue? Can I take it?

**Comment by diemol** [comment]
@joerg1985 is this still pending?

**Comment by joerg1985** [comment]
@diemol yes this is still open, as it is in milestone selenium 5.0.
I think this could be implemented earlier, but there is a risk for e.g. appium to run into troubles.

**Comment by iampopovich** [comment]
@diemol @titusfortner What should we do with the [HttpMessageTest](https://github.com/SeleniumHQ/selenium/blob/65e5ce78ae2bbb9ea325fea0e813cb6bce1301f9/java/test/org/openqa/selenium/remote/http/HttpMessageTest.java#L29) class after the changes?
If the header names become case-insensitive, all tests will fail. Should we modify the logic of the existing tests or write new ones?
