### ISSUE TITLE
[🐛 Bug]: DeprecationWarning: Firefox will soon stop logging to geckodriver.log by default

### ISSUE THREAD

**Issue by uri-rodberg** [SeleniumHQ/selenium#12698]
### What happened?

I upgraded Selenium to 4.12.0

I received this warning:

```
DeprecationWarning: Firefox will soon stop logging to geckodriver.log by default; Specify desired logs with log_output
```

I would expect Selenium to run without any deprecation warnings. I don't care if it uses a log file or doesn't. But I don't need to see warnings when I run Selenium.

My solution: I downgraded to 4.10.0

### How can we reproduce the issue?

```shell
Run Selenium with Firefox
```

### Relevant log output

```shell
DeprecationWarning: Firefox will soon stop logging to geckodriver.log by default; Specify desired logs with log_output
```
```


### Operating System

Ubuntu

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

I don't know

### Are you using Selenium Grid?

_No response_

**Comment by titusfortner** [comment]
We don't practice SemVer, so we can release breaking changes whenever we want. Our policy is to do warnings for a couple releases before making the change. 

We describe how to turn off logging here — https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
