### ISSUE TITLE
[🚀 Feature]: Publish release notes in Nuget packages

### ISSUE THREAD

**Issue by rgroenewoudt** [SeleniumHQ/selenium#12709]
### Feature and motivation

There are no release notes for the nuget packages [Selenium.WebDriver](https://www.nuget.org/packages/Selenium.WebDriver) and [Selenium.Support](https://www.nuget.org/packages/Selenium.Support)

This requires a <PackageReleaseNotes> property in the .csproj files, which most likely can be automated to:
`
<PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../CHANGELOG"))</PackageReleaseNotes>
`

**Comment by nvborisenko** [comment]
I prefer to provide static link to changelog instead of including entire changelog file (which is continuously increasing) into each package.

**Comment by titusfortner** [comment]
Is there a way to reference just the changes in the most recent release?

Also, can we do this with bazel, yet?

**Comment by nvborisenko** [comment]
Everything here is for bazel certainly. Let's wait until Simon reworks this area, and then will see.

**Comment by nvborisenko** [comment]
I don't want to post a separate issue, we also can include `readme.md`, and then our users will see nice introduction about library and how to use it. Relevant to `release notes`.
