### ISSUE TITLE
[🚀 Feature]: make Selenium Manager configurable

### ISSUE THREAD

**Issue by visko-sc** [SeleniumHQ/selenium#12706]
### Feature and motivation

I want to be able to decide what Chrome version to use or Selenium Manager should find the matching (latest, corresponding - so major version matching) chromedriver.

### Usage example

After upgrading to Selenium 4.11 or 4.12, Selenium tests fail to run. Python webdriver-manager (SergeyPirogov) and webdrivermanager (MarketSquare) stopped working after Chrome's download path changed. Selenium Manager apparently tried to download the latest Chrome but my company is supposed to manage Chrome's version (not the latest). The CI run also failed, Alpine 3.18 is shipped with Chromium 115 with the corresponding chromedriver but the browser was also overridden without adjusting the chromedriver so the tests failed here, too.
Also chromedriver 114 was downloaded by the manager (old download URL) so nothing matched.  
I cannot use Selenium 4.11+.

**Comment by diemol** [comment]
If Chrome is already installed, Selenium Manager will use that and not download a new one. However, it will download a matching driver if one is not present.

Chromium is not fully supported yet (right, @bonigarcia?), but you can always pass the browser binary path in the Chrome options. 

In short, what you ask as a feature already exists. Nevertheless, you seem to be having some issues or facing a bug. Please report this as a bug and add all the information required. I will also leave some links below where you can join our chat or ask more questions.

**Comment by bonigarcia** [comment]
> If Chrome is already installed, Selenium Manager will use that and not download a new one. However, it will download a matching driver if one is not present.
> 
> Chromium is not fully supported yet (right, @bonigarcia?), but you can always pass the browser binary path in the Chrome options.

That's correct. Besides, as of Selenium 4.11, you can pass the Chrome version you want to use through the `browserVersion` (Chrome options). If that version is not installed in your system, Selenium Manager will download the Chrome for Testing release. More info [here](https://www.selenium.dev/documentation/selenium_manager/#automated-browser-management).

**Comment by GVuncs** [comment]
With Selenium 4.12, the following happened: Chrome 116.0.5845.179 is installed, no chrome driver installed.
Selenium get chrome driver 114.0.5435.90 (latest driver on the old chromedriver download page: https://chromedriver.chromium.org/downloads) but the correct driver can be found on this page https://googlechromelabs.github.io/chrome-for-testing/

![image](https://github.com/SeleniumHQ/selenium/assets/108872301/e7b99d32-6b4f-4cb2-85ce-953243725f33)
