### ISSUE TITLE
[🐛 Bug]: Screenshot has different behavior on `driver` and `IWebElement` on HighDPI screen

### ISSUE THREAD

**Issue by huaxing-yuan** [SeleniumHQ/selenium#12710]
### What happened?

Contexte:

I would like to mark the element contains issue on the screen.
So I use `driver.GetScreenshot()` to capture a screenshot of the browser and use ILocatable.Coordinates to get location and size of the element in order to draw a red rectangle. It works well on Windows with screens configured with 100% dpi.

But when tested under another monitor scaled at 175%, the red rectangle is smaller than expected. If the element does not start on top-left corner, the coordinate returned has a huge displacement.
After investigation, I found that:
- When doing `driver.GetScreenshot`, the image has the size of 175%.
- but when working with webElement, the Coordinates, Size and even the screenshot are calculated `as if the screen is 100% dpi`.

I have tested this on Firefox, Edge and Chrome with Java and .NET, they all have this unexpected behavior.

please note following image that the navigation banner is much larger in reality than the calculated size (red rectangle)
![image](https://github.com/SeleniumHQ/selenium/assets/37816968/bee94883-7928-4d7f-b44c-7b621dae2694)

> Note
> The dpi mode 175% is set on Windows, Browser itself is set to 100%.

### How can we reproduce the issue?

```shell
1. Go to Windows settings and scale the screen to 175%.
2. Start selenium driver on any browser: Firefox, Chrome or Edge
3. Goto any webpage, for example : http://webengine-test.azurewebsites.net/home-insurance/
4. Use `driver.getScreenShot()` to capture the whole view port, save as png
5. Identify any element on the web page, and use `element.GetScreenshot()` to capture the element, save as png

We can see that the first screenshot is made with 175% and the second screenshot is made with 100%. Also the location and the size of the element are wrong.
```

### Relevant log output

```shell
C# library does not contain log.
`.NET does not currently have a Logging implementation`
```

### Operating System

Windows 10

### Selenium version

.NET 4.9

### What are the browser(s) and version(s) where you see this issue?

Chrome 116, Firefox 116, Edge 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96, EdgeDriver 116.0.1938.69, GeckoDriver 0.30.0

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Sorry for not triaging this earlier. If all of the browsers are implementing it the same, then it is an issue of what the specification is suggesting the drivers do. As such this change will need to be handled by w3c.
