### ISSUE TITLE
[🐛 Bug]: I am using Java Selenium 4.12.1 and facing issues just with chromedriver

### ISSUE THREAD

**Issue by harikrishnan1694** [SeleniumHQ/selenium#12714]
### What happened?

I started observing this issue post chrome browser update from **114** -> **116** (direct update).

Initially I explored WebDriverManager by bumping up the version to latest 5.5.3, but that just could not download the appropriate driver. It kept downloading 114.0.5735.90 driver in ".cache/selenium..." location.

So I updated the selenium java maven dependency to "4.12.1" hoping Selenium Manager would solve the driver problem.. it didn't get solved for me.

### How can we reproduce the issue?

```shell
Unlike https://github.com/SeleniumHQ/selenium/issues/12093, I am on open network, no proxy involved. Also I am connected to my personal network.

Not able to narrow down the possible cause of issue
```

### Relevant log output

```shell
FOR Chrome (Issue is faced)

PS C:\Users\ABCDE\.m2\repository\org\seleniumhq\selenium\selenium-manager\4.12.1\org\openqa\selenium\manager\windows> ./selenium-manager --browser chrome --debug --cache-path D:\
DEBUG   chromedriver not found in PATH
DEBUG   chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG   Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG   Output: "\r\r\n\r\r\nVersion=116.0.5845.180\r\r\n\r\r\n\r\r\n\r"
DEBUG   Detected browser: chrome 116.0.5845.180
DEBUG   Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG   Required driver: chromedriver 116.0.5845.96
DEBUG   Downloading chromedriver 116.0.5845.96 from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip
ERROR   request or response body error: error reading a body from connection: An existing connection was forcibly closed by the remote host. (os error 10054)


For IE (No issues faced)

PS C:\Users\ABCDE\.m2\repository\org\seleniumhq\selenium\selenium-manager\4.12.1\org\openqa\selenium\manager\windows> ./selenium-manager --browser iexplorer --debug --cache-path D:\
DEBUG   IEDriverServer not found in PATH
DEBUG   iexplorer detected at C:\Program Files\Internet Explorer\iexplore.exe
DEBUG   Running command: wmic datafile where name='C:\\Program Files\\Internet Explorer\\iexplore.exe' get Version /value
DEBUG   Output: "\r\r\n\r\r\nVersion=11.0.19041.1566\r\r\n\r\r\n\r\r\n\r"
DEBUG   Detected browser: iexplorer 11.0.19041.1566
DEBUG   Required driver: IEDriverServer 4.11.0
DEBUG   Downloading IEDriverServer 4.11.0 from https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.11.0/IEDriverServer_Win32_4.11.0.zip
INFO    Driver path: D:\IEDriverServer\win32\4.11.0\IEDriverServer.exe
INFO    Browser path: C:\Program Files\Internet Explorer\iexplore.exe
```

### Operating System

Windows 10

### Selenium version

Java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome (116.0.5845.180)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver v116

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Can you `wget` / `curl` that URL from command line?
What happens if you turn off the cache-path?
What happens if you specify a different version of Chrome?

**Comment by harikrishnan1694** [comment]
Hi @titusfortner Thanks for looking into this issue. Appreciate your help.

1. curl command didn't go as expected for chrome driver, however iexplorer driver downloaded properly. Please find the screenshot.
![image](https://github.com/SeleniumHQ/selenium/assets/34878995/2d7eb628-293a-476a-b62a-132bc6fc35ab)


2. I believe you wanted to see if I can download the driver without custom cache-path. If so, the results were same.
![image](https://github.com/SeleniumHQ/selenium/assets/34878995/2b9dba69-fdb1-486a-8654-c97a78f2ad03)


3. Same goes for different version of chrome driver. Tried downloading 117.0.5938.48 chrome driver (Beta), but no luck from curl command. 

Also on a additional note the same behavior is seen on downloading from browser.

**Comment by titusfortner** [comment]
Huh, looks like it downloads 99% then gives up. This is either a "your computer" or a "your network" problem. Try running curl with `--retry-all-errors`. Maybe try updating curl?

**Comment by diemol** [comment]
Closing this as we did not get more information.
