### ISSUE TITLE
[🐛 Bug]: incorrect path in showModalDialog in web/alerts.html 

### ISSUE THREAD

**Issue by eaccmk** [SeleniumHQ/selenium#12713]
### What happened?

initially this bug was raised https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1469

### What happened?

Go to https://www.selenium.dev/selenium/web/alerts.html
Click : `test dialog` in  This is a test of showModalDialog: [test dialog](https://www.selenium.dev/selenium/web/alerts.html#)

Expected: It should show/pop up a `Modal Dialog` however its redirected to `{page_url}./#` https://www.selenium.dev/selenium/web/alerts.html#

### What browsers and operating systems are you seeing the problem on?

All browsers, as its a HTML path issue see the element info where its supposed to call `showModalDialog()` onclick however ` href="#"`

```html
<a href="#" id="dialog" onclick="showModalDialog('javascriptPage.html')">test dialog</a>
```

### How can we reproduce the issue?

```shell
`test dialog` in  This is a test of showModalDialog: [test dialog](https://www.selenium.dev/selenium/web/alerts.html#)
```

### Relevant log output

```shell
N/A
```

### Operating System

All

### Selenium version

Latest

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by titusfortner** [comment]
Looks like it is only used for IE tests in .NET code, and that test is commented out for some reason. 

If you want to make a PR to delete it and the .NET test that uses it, I'll merge it. But I'm closing this issue because it really doesn't matter. We have a bunch of other alerts on that page that can be used for examples.
