### ISSUE TITLE
[🐛 Bug]: 4 tests failing on trunk branch for JavaScript

### ISSUE THREAD

**Issue by apupier** [SeleniumHQ/selenium#12727]
### What happened?

4 tests are failing on trunk branch

[last launched jobs](https://github.com/SeleniumHQ/selenium/actions/workflows/ci-javascript.yml) on CI is 3 months old:
![image](https://github.com/SeleniumHQ/selenium/assets/1105127/b4a13f92-16e3-489f-9ffd-343a285c153d)

### How can we reproduce the issue?

Launch test suite for JavaScript

I reproduced locally and on my own fork:

https://github.com/apupier/selenium/actions/runs/6144637027/job/16670803501?pr=4

Note that one other tests is failing on Chrome too https://github.com/apupier/selenium/actions/runs/6144637027/job/16670803734?pr=4#step:14:891

### Relevant log output

```shell
Failures:
1) [firefox] Browsing Context can navigate to a url with readiness state
  Message:
    AssertionError: '821b6eb6-9270-4362-9241-c975ddaac0a6' == null
  Stack:
    error properties: Object({ generatedMessage: true, code: 'ERR_ASSERTION', actual: '821b6eb6-9270-4362-9241-c975ddaac0a6', expected: null, operator: '==' })
        at UserContext.<anonymous> (javascript/node/selenium-webdriver/test/bidi/bidi_test.js:366:16)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

2) [firefox] Browsing Context can navigate to a url
  Message:
    AssertionError: '3d7d8d7d-c703-44e3-973b-27791487d31b' == null
  Stack:
    error properties: Object({ generatedMessage: true, code: 'ERR_ASSERTION', actual: '3d7d8d7d-c703-44e3-973b-27791487d31b', expected: null, operator: '==' })
        at UserContext.<anonymous> (javascript/node/selenium-webdriver/test/bidi/bidi_test.js:351:16)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

3) [firefox] Integration Tests can navigate and listen to errors
  Message:
    AssertionError: '9cc56e7c-3d1b-49db-a710-e8ee3fdb8404' == null
  Stack:
    error properties: Object({ generatedMessage: true, code: 'ERR_ASSERTION', actual: '9cc56e7c-3d1b-49db-a710-e8ee3fdb8404', expected: null, operator: '==' })
        at UserContext.<anonymous> (javascript/node/selenium-webdriver/test/bidi/bidi_test.js:1965:16)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

4) [firefox] Network Inspector can request cookies
  Message:
    AssertionError: {
      type: 'string',
      value: 'biryani'
    } == 'biryani'
  Stack:
    error properties: Object({ generatedMessage: true, code: 'ERR_ASSERTION', actual: Object({ type: 'string', value: 'biryani' }), expected: 'biryani', operator: '==' })
        at UserContext.<anonymous> (javascript/node/selenium-webdriver/test/bidi/bidi_test.js:1806:16)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Operating System

Ubuntu

### Selenium version

trunk
reproduced with 4.12.0 tag

### What are the browser(s) and version(s) where you see this issue?

firefox

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

**Comment by apupier** [comment]
Similar failing tests with:
* [4.12.0](https://github.com/apupier/selenium/actions/runs/6156819494/job/16706547363#step:14:1247)
* [4.11.1](https://github.com/apupier/selenium/actions/runs/6156822080/job/16706898962#step:14:1398)
* [4.10.0](https://github.com/apupier/selenium/actions/runs/6156823348/job/16706946187#step:14:1100)
* [4.9.2](https://github.com/apupier/selenium/actions/runs/6156824700/job/16706845385#step:12:547)
* [4.8.2](https://github.com/apupier/selenium/actions/runs/6156826066/job/16706822972#step:12:489)


last [successful build ](https://github.com/SeleniumHQ/selenium/actions/runs/5164318135)on CI is on 3rd June
[4.8.2](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.8.2-javascript) and [4.9.2](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.9.2-javascript) are older than the last successful build.

So would mean that it is caused to an external incompatibility? Maybe an update of Ubuntu?

**Comment by diemol** [comment]
This is a change in Firefox which needs to be addressed. Probably that build works because the test was different or the browser version was different.

**Comment by pujagani** [comment]
+1 to Diego's comment. Similar test failures are seen locally in Java bindings too.

**Comment by titusfortner** [comment]
I'm going to close this because we don't need an open ticket to tell us that the CI isn't passing. We make sure things pass or are understood before a release. If you have time or availability to help us debug the errors, that would be greatly appreciated, our resources are a little thin right now.
