### ISSUE TITLE
[🚀 Feature]: Support Node 18 as latest LTS for Selenium JS

### ISSUE THREAD

**Issue by apupier** [SeleniumHQ/selenium#12723]
### Feature and motivation

Latest Node LTS is claimed as supported in the documentation

https://github.com/SeleniumHQ/selenium/blob/ce876402e812c5b7a380c7dc38adcb7ece865a91/javascript/node/selenium-webdriver/README.md?plain=1#L130-L131

Found 2 places where the node version is specified and not on latest LTS:

* [18.12.0](https://github.com/SeleniumHQ/selenium/blob/ce876402e812c5b7a380c7dc38adcb7ece865a91/WORKSPACE#L219) for Bazel WORKSPACE config
* [16](https://github.com/SeleniumHQ/selenium/blob/ce876402e812c5b7a380c7dc38adcb7ece865a91/.github/workflows/ci-javascript.yml#L60) for Grid UI tests

Node 16 [has reached end of life today](https://nodejs.dev/en/about/releases/).

More context:
- I tried to use Node 18 for Grid UI tests on my own fork to force trigger of tests but unfortunately tests are failing [even with Node 16](https://github.com/apupier/selenium/pull/4). Reported https://github.com/SeleniumHQ/selenium/issues/12727
- It seems the CI Javascript tests were not launched in 3 months on CI:
![image](https://github.com/SeleniumHQ/selenium/assets/1105127/57096f7c-83d7-4a2b-ad2a-c8da92f38efd)

- On [our own extension](https://github.com/redhat-developer/vscode-extension-tester/issues/851), Selenium tests are no more working when moving from Node 18.15.0 to Node 18.16.0 (and not working neither with latest LTS 18.7.1)

### Usage example

Can use latest LTS

**Comment by pranil25** [comment]
Try reinstalling the node version with "npm install -g npm"

**Comment by diemol** [comment]
I believe this can be closed, thanks @apupier!
