### ISSUE TITLE
[🐛 Bug]: Selenium-manager unable to download driver behind proxy.

### ISSUE THREAD

**Issue by shinobi01** [SeleniumHQ/selenium#12728]
### What happened?

Our testing is behind proxy, so when we start testing, selenium-manager is trying to download chrome drivers from public internet via proxy.
Before chrome v114, the driver was downloaded successfully from: 
e.g. https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip, which was in whitelist of proxy.
But after chrome v115, the driver was trying to download from:
e.g. https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/win64/chromedriver-win64.zip
which is not in whitelist and IT is not going to add it due to some reasons.

So is there a way to download the chrome driver without proxy, and execute with the proxy in java?

### How can we reproduce the issue?

```shell
I was able to download chrome driver with same code without proxy.

I'm using selenide to start driver:
public void set_up_for_all() {
        Configuration.proxyHost = "test.proxy.host.com";
        Configuration.proxyPort = 9090;
        Configuration.proxyEnabled = true;
        Configuration.holdBrowserOpen = true;
        Configuration.timeout = 60000;
        SelenideLogger.addListener("allure", new AllureSelenide());
        Configuration.reportsFolder = "allure-results";
        System.setProperty("chromeoptions.args", "--remote-allow-origins=*");
}
```

### Relevant log output

```shell
Caused by: org.openqa.selenium.WebDriverException: Command failed with code: 65, executed: [/var/folders/s6/vkjgvrns3qxbsxg8vh5q30d94vf_5z/T/selenium-manager411491232376251414158329650246541/selenium-manager, --browser, chrome, --output, json, --proxy, test.proxy.host.com:9090]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: unsuccessful tunnel
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.5.1', java.version: '19'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:151)
	at org.openqa.selenium.manager.SeleniumManager.getDriverPath(SeleniumManager.java:273)
	at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:22)
	... 51 more
```

### Operating System

Mac

### Selenium version

Java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v116

### What are the browser driver(s) and version(s) where you see this issue?

None

**Comment by diemol** [comment]
Starting from ChromeDriver 115, that is the new location where all binaries will be placed.

For more information, check: https://developer.chrome.com/blog/chrome-for-testing/.

So, yes, you must check with your IT area to add that domain to your allowlist.
