### ISSUE TITLE
[🚀 Feature]: Move away from deprecated @build_bazel_rules_nodejs

### ISSUE THREAD

**Issue by apupier** [SeleniumHQ/selenium#12731]
### Feature and motivation

https://github.com/SeleniumHQ/selenium/blob/b9e416460c90cd337fcc803d33b373964d270cf2/WORKSPACE#L209

https://bazelbuild.github.io/rules_nodejs/#deprecated-modules

from https://github.com/bazelbuild/rules_nodejs#maintenance-update , it recommends to move to https://github.com/aspect-build/rules_js

I expect that it will allow to use latest Node LTS 18.17.1 (currently rules_nodejs 5.9 allows to use only 18.17.0

### Usage example

only internal

**Comment by titusfortner** [comment]
@apupier thank you. Do you have availability to help us with this, or work on a pull request?

**Comment by titusfortner** [comment]
Update: thanks Simon for working on this one.

**Comment by harsha509** [comment]
Thank you @shs96c for transitioning `build_bazel_rules_nodejs` to `aspect_rules_js` 🙇 

Closing as resolved.
