### ISSUE TITLE
[🚀 Feature]: Extend know issues section in the Selenium Manager doc

### ISSUE THREAD

**Issue by bonigarcia** [SeleniumHQ/selenium#12743]
### Feature and motivation

Extend the [know issues](https://www.selenium.dev/documentation/selenium_manager/#known-limitations) detected in Selenium Manager, e.g.:

- Library required in Firefox (as reported in Slack):
```
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

- Connectivity issues to connect CfT endpoints (e.g., when behind proxies)

**Comment by bonigarcia** [comment]
Moved to https://github.com/SeleniumHQ/seleniumhq.github.io/issues/1478

**Comment by titusfortner** [comment]
for future reference, there is a fun little "transfer issue" link on the right hand side and Github will do it all for you.
