### ISSUE TITLE
[🐛 Bug]: Selenium Manager (Webdriver v4.12.4) not working with Chrome version 117

### ISSUE THREAD

**Issue by MartinK-68** [SeleniumHQ/selenium#12740]
### What happened?

Since Chrome Web Browser auto updated to v117 the Chromedriver session is not being created. Updated to Selenium Webdriver 4.12.4 and still the same.

> System.InvalidOperationException: 'session not created: This version of ChromeDriver only supports Chrome version 107
> Current browser version is 117.0.5938.63 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (SessionNotCreated)'

### How can we reproduce the issue?

```shell
//new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.Latest); <--no longer used.
var options = new ChromeOptions();
options.AddUserProfilePreference("disable-popup-blocking", "true");
var service = ChromeDriverService.CreateDefaultService();
return new ChromeDriver(service, options); 

Visual Studio 22
Chrome browser 117
Selenium Webdriver nuget 4.12.4
```

### Relevant log output

```shell
System.InvalidOperationException: 'session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 117.0.5938.63 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe (SessionNotCreated)'
```

### Operating System

Windows 10

### Selenium version

C# 4.12.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

Driver version 107 but should upgrade to match 117 on browser?

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
>This version of ChromeDriver only supports Chrome version 107

You have a ChromeDriver binary on your PATH, please delete it an let Selenium handle it.

**Comment by MartinK-68** [comment]
Thank you! found it in ProgramData\chocolatey
