### ISSUE TITLE
[🐛 Bug]: Using Selenium Manager on the Intranet.

### ISSUE THREAD

**Issue by puatrap** [SeleniumHQ/selenium#12742]
### What happened?

I use Edge as my web browser, and my company only allows me to download WebDriver from Microsoft's domain. Therefore, I always encounter failures when trying to automatically download WebDriver using Selenium Manager. However, I can successfully do so using the third-party library webdriver-manager. Is there any way to resolve this issue? I'm considering switching to Selenium Manager because it's faster.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.edge.service import Service

service = Service()
service.creation_flags = CREATE_NO_WINDOW
options = webdriver.EdgeOptions()
driver = webdriver.Edge(service=service, options=options)
driver.get(www.google.com)
```

### Relevant log output

```shell
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium 
Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Windows 10

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Edge 116.0.1938.81

### What are the browser driver(s) and version(s) where you see this issue?

Edge 116.0.1938.81

**Comment by titusfortner** [comment]
Selenium is downloading it from the official domain. Can you turn on logging so we can see what it is doing?

https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by diemol** [comment]
Closing this as we did not get more information.
