### ISSUE TITLE
[🐛 Bug]: Can't display SeleniumManager logs at any level when switching from 4.12.0 to 4.12.1

### ISSUE THREAD

**Issue by Tristan107** [SeleniumHQ/selenium#12749]
### What happened?

I've found a strange behavior about this log change switching from 4.12.0 to 4.12.1, it's like nothing is logged at any level in 4.12.1 (probably related to https://github.com/SeleniumHQ/selenium/pull/12673)

I'm using a [jul-to-slf4j](https://javadoc.io/doc/org.slf4j/jul-to-slf4j/latest/org/slf4j/bridge/SLF4JBridgeHandler.html) conversion which works perfecty until 4.12.0, but no more logs in 4.12.1

Using a "TRACE" log level which includes FINEST, FINER and FINE : 

 FINEST  -> TRACE
 FINER   -> DEBUG
 FINE    -> DEBUG
 INFO    -> INFO
 WARNING -> WARN
 SEVERE  -> ERROR

logback.xml :
`    <logger name="org.openqa.selenium.manager" level="TRACE" />`

Using selenium-java 4.12.0, I see this : 

```
12:08:36.961 [Timer-0] INFO  o.o.selenium.manager.SeleniumManager - Driver path: C:\Users\PC\.cache\selenium\chromedriver\win64\116.0.5845.96\chromedriver.exe
12:08:36.962 [Timer-0] INFO  o.o.selenium.manager.SeleniumManager - Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
```

when upgrading to 4.12.1, I see no SeleniumManager log when I would expect to see :

```
12:08:36.961 [Timer-0] DEBUG  o.o.selenium.manager.SeleniumManager - Driver path: C:\Users\PC\.cache\selenium\chromedriver\win64\116.0.5845.96\chromedriver.exe
12:08:36.962 [Timer-0] DEBUG  o.o.selenium.manager.SeleniumManager - Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
```
after this change : https://github.com/SeleniumHQ/selenium/pull/12673

Switching back to 4.12.0 (with no other change) restores the logs.

### How can we reproduce the issue?

```shell
To reproduce, just try to display SeleniumManager logs from a calling program having this dependency :

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.12.0</version>
        </dependency>

Then upgrade to 4.12.1 and see the logs are no more displayed.
```

### Relevant log output

```shell
12:08:36.961 [Timer-0] INFO  o.o.selenium.manager.SeleniumManager - Driver path: C:\Users\PC\.cache\selenium\chromedriver\win64\116.0.5845.96\chromedriver.exe
12:08:36.962 [Timer-0] INFO  o.o.selenium.manager.SeleniumManager - Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
```
```


### Operating System

Windows 10

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

Pb in SeleniumManager, present for all browsers and all versions

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

no

**Comment by Tristan107** [comment]
Ok, it's not a selenium problem, but for anyone bridging with this same standard way, if for any reason u need these log displayed from selenium-java 4.12.1, you can't only chose "DEBUG" level, u also need to activate the "bridging" for levels below INFO with : 

        java.util.logging.LogManager.getLogManager().getLogger("").setLevel(Level.FINE);

This issue can be closed imo.

**Comment by titusfortner** [comment]
@Tristan107 thanks for providing the solution you found.

I wrote a selenium-logger jar to try to make it easier for users to get selenium log info: https://github.com/titusfortner/selenium-logger

I'm not a Java logging expert, just trying to get info to people more easily, so if you have any feedback or suggestions for it, I'd greatly appreciate it. Thanks.

**Comment by Tristan107** [comment]
Hi @titusfortner, I'm afraid you are reimplementing features people can already find in standard (= commonly used) java libs, like log4j (1 or 2) and logback (see https://www.baeldung.com/logback for quick catchup, https://mvnrepository.com/open-source/logging-frameworks). The options u provide are already configurable declaratively using a property or xml file (like logback.xml) in a way ppl already know and don't need to learn.

A standard way to configure selenium logs in a client program would be : 

* depend on selenium + a logging framework you are familiar with (mostly log4j or logback) + slf4j common facade to avoid coupling to a particular framework implementation.
* bridge "JUL" (java.util.logging) used by selenium to slf4j
* configure all logs in one place for all your classes and libs (src/main/resources/logback.xml)

For example, if I want to do what you provide to "set a specific level (e.g., you want to avoid info logs and just see warnings)" : 
```
SeleniumLogger seleniumLogger = new SeleniumLogger();
seleniumLogger.setLevel(Level.WARNING);
```
I add this line to "logback.xml" instead : 
`<logger name="org.openqa.selenium" level="WARN" />`

If I want to "create a list of specific classes to turn on logs for" and chose the log level for each, I do (FINE is mapped to DEBUG by the bridge) :
```
<logger name="org.openqa.selenium.manager.SeleniumManager" level="DEBUG" />
<logger name="org.openqa.selenium.remote.RemoteWebDriver" level="DEBUG" />

```

**Comment by titusfortner** [comment]
Thanks for the feedback on it.

My use case is for people to get logs specifically for Selenium with one package and one line of code placed somewhere before there is a problem. Ideally it wouldn't conflict with what other packages/solutions are doing, though, which is partly what I'm curious about.

> in a way ppl already know

I think you *vastly overestimate the general knowledge of most Selenium users. 😄  (especially the ones who come here asking for help). You just listed 3 packages plus a config file that users need to include. The idea of trying to walk users through all of that in order to help them troubleshoot their code is daunting.

**Comment by titusfortner** [comment]
(for what it's worth I spent at least a dozen hours trying to figure out how to combine the things you mentioned to get something to output Selenium logs, and couldn't figure it out; I read dozens of blogs, tutorials, SO posts, docs for all the libraries). 😂

**Comment by Tristan107** [comment]
Oups, here is a few more precise hints/steps if u need :
* Add these dependencies to your client project : 
![image](https://github.com/SeleniumHQ/selenium/assets/12673099/779ecd47-9717-4b29-b602-9635a4dec75e)
* Activate the "bridge" mechanism as explain [here](https://javadoc.io/doc/org.slf4j/jul-to-slf4j/latest/org/slf4j/bridge/SLF4JBridgeHandler.html) (I copy/paste the "Programmatic installation" lines).
* Now the little trick : add         `java.util.logging.LogManager.getLogManager().getLogger("").setLevel(Level.FINE);`
right after
`SLF4JBridgeHandler.install();`
to make all "java.util.logging" logs available to the "bridge" mechanism

From there, you can configure logs in "logback.xml" to be placed in src/main/resources, basic example :  

```
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="org.openqa.selenium.manager" level="INFO" />

    <root level="INFO">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

P.S. : I'm not saying it's "easier" than what you provide, but it has been the way to configure logs in java since the creation of "log4j" 20+ years ago, and it has not changed much, so once u know how it works, u can reuse it forever, for any java project...  :)

**Comment by titusfortner** [comment]
Thanks for walking me through it.

**Comment by titusfortner** [comment]
@Tristan107 your code isn't working for me.

It doesn't seem like the logger name in the xml file is recognized. Everything gets logged at the root level.

https://github.com/saucelabs-training/scalable_tests/commit/9574de

**Comment by Tristan107** [comment]
Not sure what you mean here by "Everything gets logged at the root level".

First, u need to use : 
`        LogManager.getLogManager().getLogger("").setLevel(Level.FINE);`
not : 
`        LogManager.getLogManager().getLogger("").setLevel(Level.INFO);`
to activate java.util.logging logs at DEBUG/FINE level

Then, the first logger to activate to see what is available as logs from Selenium : 
`<logger name="org.openqa.selenium" level="DEBUG" />`  (more inclusive than "org.openqa.selenium.manager")

Then you may see various selenium classes logging at DEBUG/FINE level and u can restrict your logger to these classes : 

```
08:24:15.355 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.RemoteWebDriver - Executing: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: latest, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}, platformName: Windows 10, sauce:options: {accessKey: null, name: completeCheckout(), username: null}}]}]
08:24:16.253 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.tracing.opentelemetry.SeleniumSpanExporter - SpanData{spanContext=ImmutableSpanContext{traceId=3736086470449bd72ca4da4ab5e0693b, spanId=c4d150050f09ae4a, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=3736086470449bd72ca4da4ab5e0693b, spanId=add2c73a6c836d8e, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.19.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.26.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=httpclient.execute, kind=INTERNAL, startEpochNanos=1694931855438126700, endEpochNanos=1694931856252077500, attributes=AttributesMap{data={http.method=POST, span.kind=client, http.target=/session, http.status_code=401}, capacity=128, totalAddedValues=4}, totalAttributeCount=4, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=ERROR, description=Kind: UNAUTHENTICATED Description:}, hasEnded=true}
08:24:16.284 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.tracing.opentelemetry.SeleniumSpanExporter - SpanData{spanContext=ImmutableSpanContext{traceId=3736086470449bd72ca4da4ab5e0693b, spanId=add2c73a6c836d8e, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.19.0, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.26.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=default, version=null, schemaUrl=null, attributes={}}, name=command, kind=INTERNAL, startEpochNanos=1694931855367406000, endEpochNanos=1694931856283585100, attributes=AttributesMap{data={parameter.capabilities=[Capabilities {browserName: chrome, browserVersion: latest, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}, platformName: Windows 10, sauce:options: {accessKey: null, name: completeCheckout(), username: null}}], command=newSession}, capacity=128, totalAddedValues=2}, totalAttributeCount=2, events=[], totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
08:24:16.285 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.RemoteWebDriver - Exception: newSession Could not start a new session. Response code 401. Message: failed serving request POST /wd/hub/session: Unauthorized 
```

After seeing this, u can restrict to : 
`<logger name="org.openqa.selenium.remote.RemoteWebDriver" level="DEBUG" />`
and you will see only : 

```
08:31:18.817 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.RemoteWebDriver - Executing: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, browserVersion: latest, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}, platformName: Windows 10, sauce:options: {accessKey: null, name: completeCheckout(), username: null}}]}]
08:31:19.823 [Forwarding newSession on session null to remote] DEBUG org.openqa.selenium.remote.RemoteWebDriver - Exception: newSession Could not start a new session. Response code 401. Message: failed serving request POST /wd/hub/session: Unauthorized 
```

**Comment by titusfortner** [comment]
@Tristan107 aha, of course I couldn't see selenium manager output when I'm running tests on a remote server. 😳 

Got it working, and then went down another rabbit hole of implementations vs interfaces and now looking at `java.lang.System.Logger` 😄 

Thanks.

**Comment by Tristan107** [comment]
If I were you, I would stick to "org.slf4j.Logger" in my test classes  ;)

**Comment by titusfortner** [comment]
No, from a library perspective we should not be using or requiring users to use slf4j.

I think it is likely that Selenium will switch from JUL to System Logger after we remove support for Java 8 in Selenium 4.14, and then there won't be any additional module dependencies in Selenium code. Users can then use whatever they want to with their own implementations.

**Comment by titusfortner** [comment]
I updated the information in my library's README based on what I learned from this conversation. Thank you.
https://github.com/titusfortner/selenium-logger#readme

**Comment by Tristan107** [comment]
> No, from a library perspective we should not be using or requiring users to use slf4j.

Well, you're right to think a lib should not force a dependency to any implementation, but slf4j is not an implementation, it's an api and it's a standard one everyone should use regardless of their choice of logging system (log4j 2, java.util.logging, logback, ...). "java.lang.System.Logger" on the other hand is a quite new thing, not yet a "standard", and which is not designed to be used by libraries : 

"It is not a goal to define a general-purpose interface for logging. The service interface contains only the minimal set of methods that the JDK needs for its own usage."

source : https://openjdk.org/jeps/264
