### ISSUE TITLE
[🐛 Bug]: Following the Getting started guide results in error (OSX)

### ISSUE THREAD

**Issue by EliasToftHansen** [SeleniumHQ/selenium#12747]
### What happened?

I followed the getting started guide for selenium using node on OSX.

It seems like selenium browser manager attempts to download microsoft edge, even though I never refer to it in the code (Using the basic example in getting started guide).

I have no idea how to make it stop.

`const {By, Builder, Browser} = require('selenium-webdriver');
const {suite} = require('selenium-webdriver/testing');
const assert = require("assert");

suite(function (env) {
  describe('First script', function () {
    let driver;

    before(async function () {
      driver = await new Builder().forBrowser('chrome').build();
    });

    after(async () => await driver.quit());

    it('First Selenium script', async function () {
      await driver.get('https://www.selenium.dev/selenium/web/web-form.html');

      let title = await driver.getTitle();
      assert.equal("Web form", title);

      await driver.manage().setTimeouts({implicit: 500});

      let textBox = await driver.findElement(By.name('my-text'));
      let submitButton = await driver.findElement(By.css('button'));

      await textBox.sendKeys('Selenium');
      await submitButton.click();

      let message = await driver.findElement(By.id('message'));
      let value = await message.getText();
      assert.equal("Received!", value);
    });
  });
}, { browsers: [Browser.CHROME, Browser.FIREFOX]});
`

### How can we reproduce the issue?

```shell
Follow the getting started guide for node on OSX.
```

### Relevant log output

```shell
[INFO] Searching for WebDriver executables installed on the current system...
Selenium Manager binary found at /Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/bin/macos/selenium-manager
Driver path: /Users/elias.hansen/.cache/selenium/chromedriver/mac-arm64/116.0.5845.96/chromedriver
Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
/Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/common/driverFinder.js:35
    throw Error(
    ^

Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/bin/macos/selenium-manager with --browser,MicrosoftEdge,--output,json: edge cannot be downloaded
    at getPath (/Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at getAvailableBrowsers (/Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/testing/index.js:122:6)
    at init (/Users/elias.hansen/Sites/drupal-selenium-tests/node_modules/selenium-webdriver/testing/index.js:230:59)
    at suite (/../node_modules/selenium-webdriver/testing/index.js:380:5)
    at Object.<anonymous> (/../index.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

### Operating System

OSX

### Selenium version

4.12.0 (node)

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

mac-arm64/116.0.5845.96/chromedriver, Chrome 116.0.5845.140

**Comment by codespearhead** [comment]
Do you have Google Chrome installed on your machine?

**Comment by titusfortner** [comment]
Closing as we did not hear back. I believe this was fixed by allowing using the linux based selenium manager on Unix OS in case it has linux binary support enabled.
