### ISSUE TITLE
[🐛 Bug]: The same method, Python can execute successfully, but Java fails to execute.

### ISSUE THREAD

**Issue by jaychoubaby** [SeleniumHQ/selenium#12748]
### What happened?

When I was implementing the function of saving the PDF file generated by the method window.print() to my local machine, I found that the same method can be executed correctly in Python, but it fails in Java. I hope to get some help.

**The following is my code.**

**java:**
`System.setProperty("webdriver.chrome.driver", path);
        ChromeOptions options = new ChromeOptions();

        Map<String, Object> settings = new HashMap<>();
        List<Map<String, Object>> recentDestinations = new ArrayList<>();
        Map<String, Object> recentDestinationsMap = new HashMap<>();
        recentDestinationsMap.put("id", "Save as PDF");
        recentDestinationsMap.put("origin", "local");
        recentDestinationsMap.put("account", "");
        recentDestinations.add(recentDestinationsMap);
        settings.put("recentDestinations", recentDestinations);
        settings.put("selectedDestinationId", "Save as PDF");
        settings.put("version", "2");
        settings.put("isHeaderFooterEnabled", false);
        // landscape横向，portrait 纵向，若不设置该参数，默认纵向
        settings.put("isLandscapeEnabled", true);
        settings.put("isCssBackgroundEnabled", true);
        Map<String, Object> mediaSize = new HashMap<>();
        mediaSize.put("height_microns", 297000);
        mediaSize.put("name", "ISO_A4");
        mediaSize.put("width_microns", 210000);
        mediaSize.put("custom_display_name", "A4");
        settings.put("mediaSize", mediaSize);

        options.addArguments("--enable-print-browser");
//        options.addArguments("--headless");

        Map<String, Object> prefs = new HashMap<>();
        prefs.put("printing.print_preview_sticky_settings.appState", new Gson().toJson(settings));
        prefs.put("savefile.default_directory", "E:\\pdftest");
        // 静默打印，无需用户点击打印页面的确定按钮
        options.addArguments("--kiosk-printing");
        options.setExperimentalOption("prefs", prefs);

        WebDriver webDriver =  new ChromeDriver(options);
        webDriver.get(uri);
        webDriver.manage().window().maximize();

        // 使用 JavaScript 调用 window.print() 方法
        if (webDriver instanceof JavascriptExecutor) {
            JavascriptExecutor jsExecutor = (JavascriptExecutor) webDriver;
            jsExecutor.executeScript("document.title='my_test_file3.pdf';window.print();");
            try {
                Thread.sleep(60000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        } else {
            System.err.println("This driver does not support JavaScript execution.");
        }`

**python:**
`import json
import time

from selenium import webdriver

# 设置打印机的纸张大小、打印类型、保存路径等
chrome_options = webdriver.ChromeOptions()
settings = {
    "recentDestinations": [{
        "id": "Save as PDF",
        "origin": "local",
        "account": ""
    }],
    "selectedDestinationId": "Save as PDF",
    "version": 2,
    "isHeaderFooterEnabled": False,

    # "customMargins": {},
    # "marginsType": 2,#边距（2是最小值、0是默认）
    # "scaling": 100,
    # "scalingType": 3,
    # "scalingTypePdf": 3,
    # "isLandscapeEnabled": True,  # 若不设置该参数，默认值为纵向
    "isCssBackgroundEnabled": True,
    "mediaSize": {
        "height_microns": 297000,
        "name": "ISO_A4",
        "width_microns": 210000,
        "custom_display_name": "A4"
    },
}

chrome_options.add_argument('--enable-print-browser')
# chrome_options.add_argument('--headless') #headless模式下，浏览器窗口不可见，可提高效率
prefs = {
    'printing.print_preview_sticky_settings.appState': json.dumps(settings),
    'savefile.default_directory': 'E:\pdftest'  # 此处填写你希望文件保存的路径,可填写your file path默认下载地址
}

chrome_options.add_argument('--kiosk-printing')  # 静默打印，无需用户点击打印页面的确定按钮
chrome_options.add_experimental_option('prefs', prefs)

driver = webdriver.Chrome(executable_path='E:\chromedriver_win32\chromedriver.exe', options=chrome_options)
driver.get('http://a.canpoint.com.cn/question-template/ques.html')
driver.maximize_window()  # 浏览器最大化
driver.execute_script(
    'document.title="my_test_file3.pdf";window.print();')  # 利用js修改网页的title，该title最终就是PDF文件名，利用js的window.print可以快速调出浏览器打印窗口，避免使用热键ctrl+P
# driver.close()#关闭当前页
time.sleep(5)
driver.quit();
`

### How can we reproduce the issue?

```shell
I have already posted the code for Java and Python mentioned above. When executed, it can be seen that Python correctly saves the PDF file to the specified directory. However, when Java is executed, it automatically closes the page after displaying the PDF printing page without any results.
```

### Relevant log output

```shell
No error log output.
```

### Operating System

Windows10

### Selenium version

java 3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.188

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

selenium-java 3.141.59

**Comment by jaychoubaby** [comment]
https://github.com/SeleniumHQ/selenium/assets/26641387/eb36acc6-fad7-4f18-8751-418d70e23f73


https://github.com/SeleniumHQ/selenium/assets/26641387/8409e531-4555-4b77-b36f-737023f0cae9



I have added my presentation video.

**Comment by titusfortner** [comment]
We only support the most recent version of Selenium, which is 4.12 right now.

There is native support for printing pages:

```java
        driver = new ChromeDriver();
        driver.get("https://www.selenium.dev");

        String content = driver.print(new PrintOptions()).getContent();
        byte[] bytes = Base64.getDecoder().decode(content);
        Files.write(Paths.get("selenium.pdf"), bytes);
```

**Comment by jaychoubaby** [comment]
> 我们仅支持 Selenium 的最新版本，目前为 4.12。
> 
> 对打印页面有本机支持：
> 
> ```java
>         driver = new ChromeDriver();
>         driver.get("https://www.selenium.dev");
> 
>         String content = driver.print(new PrintOptions()).getContent();
>         byte[] bytes = Base64.getDecoder().decode(content);
>         Files.write(Paths.get("selenium.pdf"), bytes);
> ```

![image](https://github.com/SeleniumHQ/selenium/assets/26641387/0befa039-dd58-4e66-9f60-4ad6a4c1ce65)
![image](https://github.com/SeleniumHQ/selenium/assets/26641387/8e737d66-671b-4c4a-bcc1-7931bb5edfbf)


I used the latest v4.12.1, and it seems that there is no method called print().

**Comment by titusfortner** [comment]
let's continue in 12763
