### ISSUE TITLE
[🐛 Bug]: Remote browser stops responding after opening certain amount of tabs

### ISSUE THREAD

**Issue by ParanoikCZE** [SeleniumHQ/selenium#12745]
### What happened?

I have a few tests working with several tabs. It works since some point (exactly 5 tabs for the testing page) when the communication starts to stall and the whole communication with the browser stops, so it's not even able to close it or perform any other operation. It eventually fails with "The HTTP request to the remote WebDriver timed out after 60 seconds". I'm not even able to close the whole Chrome manually, it requires closing the first tab before the close event is fired.

(The only known workaround to this is to watch the execution and close older tabs. If I keep them below 5, the test passes just fine. Please don't suggest updating tests to close the unused tabs as it's not possible due to the used architecture.)

I've tried to reproduce it with several other web pages (to create proper STR), but it looks like some combination of our testing website and Chrome/ChromeDriver. I'm using window.open() to create a new tab and then switch to the last handle and check that the page is loaded which passes fine. It starts to fail a few operations later (like navigating and inserting data) randomly, I wasn't able to find any common reason or time. But every time, the first tab (which is the possible problem here) is a white screen even when the page was fully loaded before. Memory optimization is disabled.

Using Grid 4.12.1 with Chrome 117 and I have had this issue since ~like 10 or 15 versions back. However, it was pretty random and easily resolvable by rerunning affected tests for few times when it happened. Since Chrome/Driver 116, I'm able to reproduce it in maybe 95% of cases and I feel like the situation is getting worse with each new version.

Basically, my only idea here was that I'm enabling performance logs with:
browserOptions.SetLoggingPreference(LogType.Performance, LogLevel.All)
and due to the amount of data exchanged between our BE and FE, it might just be clogging something.

Is there anything I could check or improve to know where exactly the issue is coming from?

### How can we reproduce the issue?

```shell
It's 100% reproducible from my grid against our testing site, which is private. So .. 

no known STR (yet)
```

### Relevant log output

```shell
there is no logging in cs
```

### Operating System

W10

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117

### Are you using Selenium Grid?

4.12.1

**Comment by titusfortner** [comment]
As you suspected, there's not much we can do to help you determine what might be wrong without something we can reproduce.

Even if we could reproduce it, the culprit is almost certainly the the way chromedriver is communicating with the browser, in which case it would be up to Google to help address the problem. They will also need some kind of reproducible example, though.
