### ISSUE TITLE
[🚀 Feature]:  Enable control of tabs without focus

### ISSUE THREAD

**Issue by cursedgrape** [SeleniumHQ/selenium#12759]
### Feature and motivation

The feature would enable simultaneous access and control of multiple tabs without the current behavior which requires switching to execute anything. This would save a lot of time wasted in sequential requests which could benefit from a thread queue which handles requests and any JS work needed.

### Usage example

Given `n` urls in `a`:

    a = [url1, url2, url3, ...]

It is possible to open the urls simultaneously using the following approach:

    call_threads(a)

where each thread sends a request in a new tab:

    driver.execute_script(f"window.open('{url}','_blank');")
    # do other work

The current behavior requires:

    for handle in driver.window_handles:
        driver.switch_to.window(handle)
        # do other work

Having this would be nice:

    driver.do_stuff(handle=handle)  # shouldn't require switching anymore

`do_stuff` could be any of the existing `WebDriver` methods ex: `driver.get(url, handle=handle)`

**Comment by diemol** [comment]
That is not an ideal API design because it would mean that you need to know the window handle for every single call. In addition, the everyday use case is to have a single active tab; therefore, this type of interface would be unpractical for most users. 

You are welcome to join our chat if you think this is a valuable use case for most Selenium users. https://www.selenium.dev/support/#ChatRoom

**Comment by titusfortner** [comment]
This really comes down to how webdriver specification requires it. Some frameworks, like Watir, wrap the windows functionality to be able to do things like this with an easy API, but under the hood they still have to use Selenium to do the switching.

**Comment by cursedgrape** [comment]
> That is not an ideal API design because it would mean that you need to know the window handle for every single call. In addition, the everyday use case is to have a single active tab; therefore, this type of interface would be unpractical for most users.
> 
> You are welcome to join our chat if you think this is a valuable use case for most Selenium users. https://www.selenium.dev/support/#ChatRoom

What if it's an optional argument that defaults to the first window handle if not specified? A situation where a similar feature would be beneficial is when you have an IO bottleneck possibly caused by `n` urls that have to be visited sequentially and repeating the same JS work over and over. I'm not sure if this feature would be as beneficial for testing multiple features simultaneously on a local server, since JS is fast enough for most testing purposes, and I don't think the tab generation overhead is worth it unless it fixes another IO bottleneck.

**Comment by cursedgrape** [comment]
> This really comes down to how webdriver specification requires it. Some frameworks, like Watir, wrap the windows functionality to be able to do things like this with an easy API, but under the hood they still have to use Selenium to do the switching.

I haven't checked the associated code yet, should many use cases get mentioned here, where a similar feature could be beneficial, I will examine it further to see how it can be done. However, I think there's a way of wrapping some JS code that controls other tabs, same as [here](https://stackoverflow.com/questions/2614520/call-a-javascript-function-across-browser-tabs).

**Comment by titusfortner** [comment]
Selenium wants to avoid relying on client side Java Script as much as possible. Ideally everything we provide is implemented as a w3c compliant endpoint. This is where wrapper libraries and frameworks can be very useful, though. Selenium provides the execute script methods so you can build out whatever classes and behaviors you want on top of Selenium.

**Comment by cursedgrape** [comment]
> Selenium wants to avoid relying on client side Java Script as much as possible. Ideally everything we provide is implemented as a w3c compliant endpoint. This is where wrapper libraries and frameworks can be very useful, though. Selenium provides the execute script methods so you can build out whatever classes and behaviors you want on top of Selenium.

Why do you avoid relying on JS? What negative outcomes that could result otherwise? I'm asking because I often find myself in situations where calling `driver.execute_script(...)` is much faster than relying on selenium methods. One example is using `driver.find_elements`,  many times I found that using `document.getElementsBySomething` is way faster. Another example is using selenium `element.text` vs JS `element.textContent`. Are these related / relevant to what you mentioned?

**Comment by titusfortner** [comment]
It's a matter of scope for this project. This project is focused on being the toolkit that allows others to write their own library or to create an open source [framework in the ecosystem](https://www.selenium.dev/ecosystem/#frameworks) to add the specific functionality they want.

If you'd like to create a wrapper library that does what you suggest, we'd love to promote it to our users, but it isn't compatible with what we're focused on in this project.

I can't speak to the speed of JavaScript methods; I suspect it varies by browser. The nice thing about the driver commands is that the implementation is what the browser vendor itself thinks is best for that functionality. Additionally, we're going to be working on replacing the direct method implementation with the new WebDriver-BiDi specification over the next few years, so just using JS won't always do the same thing.
