### ISSUE TITLE
Clicks to Internet Explorer not responding with WebDrive Plus and Python

### ISSUE THREAD

**Issue by sreastman** [SeleniumHQ/selenium#1276]
There is an issue involving InternetExplorerDriver and WebDriver plus. The IE browser is not responding to clicks when I run my scripts, but Firefox and Chrome work just fine. I’ve searched the literature and found a good answer for a similar problem involving WebDriver (no Plus) at https://code.google.com/p/selenium/issues/detail?id=4403:

DesiredCapabilities d = DesiredCapabilities.internetExplorer();
//d.setCapability("nativeEvents", false);
webdriver = new InternetExplorerDriver(d);

I have been unable to find a similar approach for WebDriver Plus with Python where the driver is instantiated by:

self.driver = WebDriver("ie", wait=5)

**Comment by lukeis** [comment]
we do not support webdriverplus here, i don't know where that project is hosted either.
