### ISSUE TITLE
Download popup doesnt gets turned off

### ISSUE THREAD

**Issue by murtuzak01** [SeleniumHQ/selenium#12769]
Hi, I want to disable the downloads popup on chrome whenever a file is downloaded, but it doesn't work in incognito mode. I have added the chrome options to turn if off . same works if I disable incognito mode. Chrome version: 117.0.5938.89 . 

Selenium Version: 3.14

please find below chrome option
HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
chromePrefs.put("profile.default_content_settings.popups", 0);
chromePrefs.put("download.default_directory", downloadFilepath);
chromePrefs.put("download.prompt_for_download", false);
chromePrefs.put("safebrowsing.enabled", "false"); 
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("useAutomationExtension", false);
options.setExperimentalOption("prefs", chromePrefs);
options.addArguments("test-type");
options.addArguments("disable-popup-blocking");
DesiredCapabilities cap = DesiredCapabilities.chrome();
cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
cap.setCapability(ChromeOptions.CAPABILITY, options);
driver = new ChromeDriver(cap);

[Slack Message](https://seleniumhq.slack.com/archives/C0ABCS03F/p1694866456902119?thread_ts=1694866456.902119&cid=C0ABCS03F)

**Comment by titusfortner** [comment]
I believe this is a known issue. I'd check the chromedriver bugs list.
