### ISSUE TITLE
[🐛 Bug]:  v4.12.1 Unable to find the print() method.

### ISSUE THREAD

**Issue by jaychoubaby** [SeleniumHQ/selenium#12763]
### What happened?

https://github.com/SeleniumHQ/selenium/issues/12748

In accordance with the instructions, upgrade this version to 4.12.1 for the previous issue, but the print() method is missing.

![image](https://github.com/SeleniumHQ/selenium/assets/26641387/7d01ee7b-6850-4fd2-bb53-ac3c267f13cc)
![image](https://github.com/SeleniumHQ/selenium/assets/26641387/4b6b4718-8aa7-46c8-bc0c-dde3d9d0926d)

### How can we reproduce the issue?

```shell
Version 4.12.1 is being used.

WebDriver webDriver =  new ChromeDriver();
webDriver.get(uri);
String content = webDriver.print(new PrintOptions()).getContent();
```

### Relevant log output

```shell
Cannot resolve method 'print' in 'WebDriver'
```

### Operating System

Windows10

### Selenium version

java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.188

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

selenium-java 4.12.1

**Comment by titusfortner** [comment]
It isn't on the `WebDriver` interface, you need to cast to `ChromeDriver` or `RemoteWebDriver` class.

@diemol do you know why it isn't in the interface? It's a w3c specified method.

It probably should be in the interface.

**Comment by jaychoubaby** [comment]
> `RemoteWebDriver`

I found it in RemoteWebDriver, thank you very much for your help. It seems that the new version has become very powerful, and the code is also much more elegant and concise. Thank you for your efforts.

**Comment by jaychoubaby** [comment]
> It isn't on the `WebDriver` interface, you need to cast to `ChromeDriver` or `RemoteWebDriver` class.
> 
> @diemol do you know why it isn't in the interface? It's a w3c specified method.
> 
> It probably should be in the interface.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/print/PrintOptions.html
![image](https://github.com/SeleniumHQ/selenium/assets/26641387/ae4293fa-dc1e-4a13-a21b-2b129186bf8c)

I have reviewed the source code and documentation, but it seems that I cannot find a way to set `--print-header-template` in PrintOptions. According to my search on Python methods, it appears that this can only be set in `ChromeOptions`. Is there a better way for me to set this property in `PrintOptions `or `RemoteWebDriver`?

Also, I have another question. Currently, I am using `springboot `integrated with `selenium`. Here is my code:


```
@Configuration
public class WebDriverConfig {
    @Value("${chromedriver.path}")
    private String path;

    @Bean
    public WebDriver webDriver() {
        log.info(">>>>> 加载webdriver环境：{}", path);
        // 设置WebDriver路径
        System.setProperty("webdriver.chrome.driver", path);
        // 配置ChromeOptions为无界面模式
        ChromeOptions options = new ChromeOptions();
        // 启用无界面模式
        options.addArguments("--headless");
        options.addArguments("--remote-allow-origins=*");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--disable-gpu");
        return new ChromeDriver(options);
    }
}
```

In order to quickly invoke the driver and save memory, I initialized ChromeDriver when the project started so that I can use it quickly in subsequent work. I'm not sure if this usage is correct or if I need to re-create a `new ChromeDriver()` where it is used. Can you help me answer this? Thank you very much.

**Comment by jaychoubaby** [comment]
> > `RemoteWebDriver`
> 
> I found it in RemoteWebDriver, thank you very much for your help. It seems that the new version has become very powerful, and the code is also much more elegant and concise. Thank you for your efforts.

```
@Data
public class CpPrintOptions extends PrintOptions {


    public Map<String, Object> toMap() {
        final Map<String, Object> options = new HashMap<>(7);
        options.put("page", getPageSize());
        options.put("orientation", getOrientation().toString());
        options.put("scale", getScale());
        options.put("shrinkToFit", getShrinkToFit());
        options.put("background", getBackground());
        final String[] effectivePageRanges = getPageRanges();
        if (effectivePageRanges != null) {
            options.put("pageRanges", effectivePageRanges);
        }
        options.put("margin", getPageMargin());
        options.put("displayHeaderFooter", true);
        options.put("headerTemplate", "<span style=\"font-size:8px; margin-left: 5px\">Page <span class=pageNumber></span> of <span class=totalPages></span></span>");
        options.put("footerTemplate", "<span style=\"font-size:8px; margin-left: 5px\">Generated on {datetime.now().strftime(\"%m/%d/%Y at %H:%M\")} - url = <span class=url></span></span>");
        return options;
    }
}
```

I tried to integrate `PrintOptions()` and specify the properties, but it seems not to work.

**Comment by titusfortner** [comment]
What is supported is specified here: https://w3c.github.io/webdriver/#print-page

If you would like to see additional functionality, it needs to be agreed to be supported there; you can open a ticket: https://github.com/w3c/webdriver

**Comment by jaychoubaby** [comment]
> What is supported is specified here: https://w3c.github.io/webdriver/#print-page
> 
> If you would like to see additional functionality, it needs to be agreed to be supported there; you can open a ticket: https://github.com/w3c/webdriver

Thank you for your response. I have found that everything seems to be supported except for the header and footer. I have already raised the issues.:

https://github.com/w3c/webdriver/issues/1761

![image](https://github.com/SeleniumHQ/selenium/assets/26641387/d3a9b27f-e462-4756-a61c-b9b0075dc151)

**Comment by jaychoubaby** [comment]
> What is supported is specified here: https://w3c.github.io/webdriver/#print-page
> 
> If you would like to see additional functionality, it needs to be agreed to be supported there; you can open a ticket: https://github.com/w3c/webdriver

I really want to know why it is so convenient in Python to specify the parameters `displayHeaderFooter`, `headerTemplate`, and `footerTemplate`.

https://github.com/JavaScriptDude/Selenium2Pdf/blob/main/Selenium2Pdf.py

![image](https://github.com/SeleniumHQ/selenium/assets/26641387/2eac1257-8ad7-4223-8ae7-558d37b1c674)

**Comment by titusfortner** [comment]
Oh that's using Chrome devtools. You can do that in Java.
Check out https://github.com/SeleniumHQ/selenium/blob/3a126babc77dd5af4cd8fb0c45d8c0eb172c7b8c/java/src/org/openqa/selenium/chromium/AddHasCdp.java

**Comment by jaychoubaby** [comment]
> Oh that's using Chrome devtools. You can do that in Java. Check out https://github.com/SeleniumHQ/selenium/blob/3a126babc77dd5af4cd8fb0c45d8c0eb172c7b8c/java/src/org/openqa/selenium/chromium/AddHasCdp.java

👍 Thank you again. I implemented it using CDP and look forward to the native support for setting `printOption()` in the future.

**Comment by titusfortner** [comment]
Make sure what you want is defined here - https://w3c.github.io/webdriver-bidi/#command-browsingContext-print

If it isn't, please raise an issue to request it.
