### ISSUE TITLE
[🚀 Feature]: Node-Chrome 117 version needed

### ISSUE THREAD

**Issue by minorling** [SeleniumHQ/selenium#12765]
### Feature and motivation

Chrome's new stable version is now version 117, could you please help to add the node-chrome for tag 117 version?

### Usage example

node-chrome for 117

**Comment by crystal-williams-brown** [comment]
Not sure if this is related but my app is using selenium-webdriver 4.12.0 and encounters an error when downloading chrome 
```
Selenium::WebDriver::Error::NoSuchDriverError: Unable to obtain chromedriver using Selenium Manager; Unsuccessful command executed: ["/usr/local/bundle/gems/selenium-webdriver-4.12.0/bin/linux/selenium-manager", "--browser", "chrome", "--output", "json"]
```
Not sure if I should pin the chrome version to the last working version until there is a fix. Or perhaps there is something I can do currently to add selenium in downloading the chrome driver.

**Comment by crystal-williams-brown** [comment]
Note: this failure happens in CI not locally. It was alerted on  by Rollbar.

**Comment by titusfortner** [comment]
@crystal-williams-brown this issue is related to node. Your issue is ruby and the error indicates that your CI can not access the url. Is there a proxy on that machine that you need to use, or an allow list that needs to be updated?

**Comment by crystal-williams-brown** [comment]
I've opened a new issue for my problem. The app is hosted on Heroku. It's a client that app and I don't have access to their Heroku yet. So my information on the error come from Rollbar. I don't get the error locally. I will inquire about the proxy and allow list.

**Comment by titusfortner** [comment]
I believe this has been addressed as necessary.
