### ISSUE TITLE
[🐛 Bug]: Selenium::WebDriver::Error::NoSuchDriverError: Unable to obtain chromedriver using Selenium Manager

### ISSUE THREAD

**Issue by crystal-williams-brown** [SeleniumHQ/selenium#12770]
### What happened?

Rollbar is producing the same error repeatedly. Selenium Webdriver is not successfulling downloading chrome.
Stack Trace
```
Selenium::WebDriver::Error::NoSuchDriverError Unable to obtain chromedriver using Selenium Manager; Unsuccessful command executed: ["/usr/local/bundle/gems/selenium-webdriver-4.12.0/bin/linux/selenium-manager", "--browser", "chrome", "--output", "json"]
{"code"=>65, "message"=>"error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json): operation timed out", "driver_path"=>"", "browser_path"=>""}; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```
Code that triggers the error
```
class Scraper::WatirJob < ApplicationJob
  private

  def configure_watir_browser
    if (chromedriver_path = ENV.fetch("CHROMEDRIVER_PATH", nil))
      Selenium::WebDriver::Chrome::Service.driver_path = chromedriver_path
    end

    options = {
      args: %w[--no-sandbox --headless --disable-dev-shm-usage --disable-gpu]
    }
    if (chrome_bin = ENV.fetch("GOOGLE_CHROME_SHIM", nil))
      options[:binary] = chrome_bin
    end

    Watir::Browser.new(:chrome, options: options)
  end
end
```

### How can we reproduce the issue?

```shell
Using selenium-webdriver 4.12.0 and watir 7.3.0, try to create a new Watir browser. Note this is happening in CI. Locally I don't get the issue so I can't reproduce it.
```

### Relevant log output

```shell
No log output since this happens in CI not locally.
```

### Operating System

linux

### Selenium version

selenium-webdriver 4.12.0 for Ruby on Rails

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromdriver latest stable

**Comment by titusfortner** [comment]
As I said in the other thread, it's a matter of the machine executing the code not having access to that location on the network.

Alternative is to download the driver yourself and pass the key value pair into the browser constructor with a service argument

**Comment by crystal-williams-brown** [comment]
I added the download of the chromedriver to the Dockerfile. Its in a PR. Once it's merged I'll see if this resolves the issue

**Comment by titusfortner** [comment]
If you put it in a directory on PATH, it'll find it.
Or you can use Watir and specify it:

```rb
Watir::Browser.new(options: options, service: {path: '/path/to/chromedriver' }
```

**Comment by crystal-williams-brown** [comment]
One of the team members with access to Heroku checked if the issue is still happening and it appears to not be. My change wasn't merged yet. We're going to wait and see if it was a temporary glitch.

Thank you for your help. If the issue resurfaces I will follow your advice regarding path.
