### ISSUE TITLE
[🐛 Bug]: Read-only file system (os error 30)

### ISSUE THREAD

**Issue by PulseBeat02** [SeleniumHQ/selenium#12774]
### What happened?

While using Selenium in my application in a Java closed environment, Selenium outputted just the following error (there was no Java error involved)
`[org.openqa.selenium.manager.SeleniumManager] Read-only file system (os error 30)`

After doing some further research, this is because the tool which is used to install drivers for users, `SeleniumManager` requires a cache path that has permissions for it to modify. In my case, I can't give it permissions. I have to create a new cache folder which can give it the sufficient permissions.

Upon looking at the [Wiki](https://www.selenium.dev/documentation/selenium_manager/#examples) page for documentation, it has an argument for `--cache-path` which allows the user to change the cache path.

However, the issue is that the Java API doesn't have any flexibility for the users to change arguments. The Java class is [here](https://github.com/SeleniumHQ/selenium/blob/8a8120cc4e89d253dba9a772cbd06d08ec150c6f/java/src/org/openqa/selenium/manager/SeleniumManager.java#L252), and the function that gets the path just accepts a `Capabilities` and boolean `offline` as arguments. The actual arguments that are used to execute the program is contained by an `ArrayList` that is only created within the function. Users can't modify the list of arguments otherwise.

Please make an API change which will allow users to implement other arguments when executing the Selenium Manager.

### How can we reproduce the issue?

```shell
To reproduce, just host a file system where there are insufficient permissions for the default cache folders Selenium Manager uses.
```

### Relevant log output

```shell
None (Above)
```

### Operating System

Ubuntu

### Selenium version

Java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Not sure (it didn't download the driver)

### What are the browser driver(s) and version(s) where you see this issue?

Not sure (it didn't download the driver)

**Comment by titusfortner** [comment]
@PulseBeat02 you can either set an environment variable `SE_CACHE_PATH` with the location of a directory that Selenium has permission to write to, or you need to manually download the drivers and set the path in a service class — https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location
