### ISSUE TITLE
[🐛 Bug]: Click event `screenX` and `screenY` coordinates are 0 since Chrome Driver 115

### ISSUE THREAD

**Issue by xavier-villelegier** [SeleniumHQ/selenium#12771]
### What happened?

Hey hey !

We just bumped ChromeDriver from 112.0.5615.165 to 117.0.5938.62 and found a weird behavior:

When clicking using Selenium on the latest ChromeDriver, the HTML event `screenX` and `screenY` coordinates are alway equal to 0 (all the other coordinates like pageX/Y, clientX/Y are correct). This does not happen when clicking manually.

This was not happening with ChromeDriver 112.0.5615.165, and I don't see any issue opened on ChromeDriver about this. Would it be possible that something changed in ChromeDriver on the event handling and Selenium needs to be updated to reflect that ? Or do you think it's a ChromeDriver bug ?

### How can we reproduce the issue?

Have a basic html page with a div logging the click event

```html
<div
  id="click-me"
  style={{ width: '100%', height: '100%' }}
  onClick={(e) => console.log(e)}
>
  Click here
</div>
```

Click on the element using Selenium:
```rb
find('#click-me').click
```

As you can see the `event.screenX` and `event.screenY` are equal to 0, but if you manually click on the div, they have the good values. All other values `clientX/Y`, `pageX/Y` are correct

### Relevant log output

Event when clicking with Selenium:

```
{
  …
  "screenX": 0,
  "screenY": 0
}
```

Event when clicking manually:
```
{
  …
  "screenX": 122,
  "screenY": 75
}
```

### Operating System

macOS Big Sur

### Selenium version

4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 117.0.5938.88

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.62

**Comment by titusfortner** [comment]
This sounds like a Chromedriver bug then. Do you know which version of Chrome it broke in?

**Comment by xavier-villelegier** [comment]
Hey @titusfortner, I just did a few tests and looks like it started to break since v115

**Comment by xavier-villelegier** [comment]
@titusfortner Just to make sure I understand correctly, can you give me any hint on why it would be a ChromeDriver's bug if it works fine when clicking manually without Selenium ? Because they will probably ask this on their side

**Comment by AutomatedTester** [comment]
The issue is that Selenium asks ChromeDriver to do click it should click on the middle of the element. I think they have either regressed in step 8/9 of the [click spec](https://w3c.github.io/webdriver/#element-click) where we set it to 0 for the move or just not doing the clicks in the same way.
