### ISSUE TITLE
[🐛 Bug]: Selenium server connected to with driver.Remote() hangs on set_window_size

### ISSUE THREAD

**Issue by CalebKierum** [SeleniumHQ/selenium#12783]
### What happened?

I have a Selenium instance I am running in one process. That process just exists to keep that Selenium driver alive.

Another process occasionally spins up and connects to that driver with 
```
    options = webdriver.ChromeOptions()
    driver = webdriver.Remote(command_executor=stateDict['url'],options=options)
    driver.close()   # this prevents the dummy browser
    driver.session_id = stateDict['session_id']
```
And then runs `driver.set_window_size(1080, 962)`

This works great for awhile but eventually this call to set_window_size just freezes. It doesn't return an error it doesn't do anything really. Just freezes.
Even calls like `performance_log = driver.get_log('performance')` simply hang without returning anything.

The window is still open and the original process is still going so I am not sure what is happening here or how to diagnose further. Happy to dig if I know what to look for.

### How can we reproduce the issue?

```shell
Create a Selenium Chrome Driver in a background process in VNC.
Leave it sit for hours.

In another process over SSH connect to it remotely. Periodically call set_window_size and see if it finishes that call. At some point it won't.
```

### Relevant log output

```shell
None unfortunately.
```

### Operating System

PiOS

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chromium 113.0.5672.95 Built on Raspbian , running on Raspbian 11

### What are the browser driver(s) and version(s) where you see this issue?

113.0.5672.95-rpt1) ChromeDriver (917deeefba48411c7b40ba19aef7b229bf48acd7-refs/branch-heads/5672_63@{#13})

**Comment by CalebKierum** [comment]
If it helps something I did notice about driver.set_window_size is that it's just temporary. Right after I do that I take a screenshot. And the screenshot has the webpage rendered the proper size. However if I look in VNC its as though the browser was never that size.

**Comment by titusfortner** [comment]
This is a driver issue. I would send you to Google, but Google doesn't have a driver for that architecture, so they may not be looking to debug it, either.

**Comment by CalebKierum** [comment]
@titusfortner ah! Good to know. Is there a recommended driver for that architecture?

**Comment by CalebKierum** [comment]
And is there any way to detect that that driver issue had occurred so I can recover from it? I can of course observe if the process hangs for too long but something more concrete would be useful.
