### ISSUE TITLE
The microsoft edge driver executable window remains open after executing a test.

### ISSUE THREAD

**Issue by dbenoit** [SeleniumHQ/selenium#1278]
Successfully execute script to launch google and verify google title. The edge browser close, however the Microsoft Edge driver executable window remains open. Use driver.close() the window remains opened. Tried driver.quit() get HTTPError: HTTP Error 400: Bad Request and the window did not close. Tried both - still get the HTTPError: HTTP Error 400: Bad Request.
Code used:
from selenium import webdriver
from selenium.webdriver  import edge

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class TestVersion(unittest.TestCase):
    def setUp(self):
        self.driver =  webdriver.Edge() 
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.google.com"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_version(self):
        driver = self.driver
        # open |  | 
        driver.get(self.base_url )
        time.sleep(5)
        # assertTitle | Google | 
        self.assertEqual("Google", driver.title)

    def tearDown(self):
        self.driver.close() # driver close closes the browser but the driver exe window remains opened.
        #self.driver.quit() # driver quit cause an error

**Comment by lukeis** [comment]
for bugs with the Edge Driver please log them with microsoft here:
http://connect.microsoft.com/
