### ISSUE TITLE
[🐛 Bug]: Download of chromedriver fails with socket exception 10054

### ISSUE THREAD

**Issue by olafrose** [SeleniumHQ/selenium#12788]
### What happened?

After the latest chrome update selenium manager can't download the correct chrome webdriver anymore. 
While trying to diagnose the problem I found the following:

Running 
`./selenium-manager.exe --browser chrome --debug`
in a powershell on windows 11 i get the following output:
`DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG	Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG	Output: "\r\r\n\r\r\nVersion=117.0.5938.89\r\r\n\r\r\n\r\r\n\r"
DEBUG	Detected browser: chrome 117.0.5938.89
DEBUG	Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG	Required driver: chromedriver 117.0.5938.88
DEBUG	Downloading chromedriver 117.0.5938.88 from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.88/win64/chromedriver-win64.z
ip
ERROR	error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.88/win64/chromedriver-win64.zip): error tr
ying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
`

As this looked like a proxy config issue to me at first glance i tried to wget the chromedriver zip and - targetting the exact same URI where selenium manager failed  wget downloaded the file without issues.

### How can we reproduce the issue?

```shell
`./selenium-manager.exe --browser chrome --debug`
```

### Relevant log output

```shell
DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
DEBUG	Running command: wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG	Output: "\r\r\n\r\r\nVersion=117.0.5938.89\r\r\n\r\r\n\r\r\n\r"
DEBUG	Detected browser: chrome 117.0.5938.89
DEBUG	Discovering versions from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
DEBUG	Required driver: chromedriver 117.0.5938.88
DEBUG	Downloading chromedriver 117.0.5938.88 from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.88/win64/chromedriver-win64.z
ip
ERROR	error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.88/win64/chromedriver-win64.zip): error tr
ying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
```

### Operating System

Windows 11

### Selenium version

.Net 4.12.4

### What are the browser(s) and version(s) where you see this issue?

Chrome 117.0.5938.89

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117.0.5938.88

**Comment by titusfortner** [comment]
Is it a problem from the last Chrome update or from a Selenium update? Selenium Manager isn't downloading from a different location.

Is it always failing, or intermittent?
Are you using the same user/permissions for wget as for running the Selenium code?

**Comment by nvborisenko** [comment]
It might be related to proxy settings: https://www.selenium.dev/documentation/selenium_manager/#configuration

**Comment by olafrose** [comment]
The machine running the tests is behind an autoproxy, so if selenium manager doesn't automatically respect these settings i need a way to configure it to use the autoproxy. I don't see that option in the CLI parameters, so any hints there would be appreciated.

**Comment by olafrose** [comment]
> Is it a problem from the last Chrome update or from a Selenium update? Selenium Manager isn't downloading from a different location.

I haven't noticed the error before updating selenium, but then i haven't ran the tests in quite some time because our test manager was away...

> Is it always failing, or intermittent? Are you using the same user/permissions for wget as for running the Selenium code?

Right now it is always failing and the same user that runs the wget also is used to execute the tests.

**Comment by titusfortner** [comment]
Ah, I know selenium supports with setProxyAutoconfigUrl
We need to investigate for rust implementation.

**Comment by titusfortner** [comment]
The fix for this has been merged. If 4.17 does not address it, please open a new ticket with updated information.
