### ISSUE TITLE
[🐛 Bug]: Unable to use enableVNC option with selenium 4.11.2 while it is working for Selenium 4.1.0

### ISSUE THREAD

**Issue by imasadansari** [SeleniumHQ/selenium#12786]
### What happened?

I am using selenium and python 3.9.6 to automate the tests on GUI. I have enabled 'enableVNC' option for chrome for viewing virtual machine and its working fine for Selenium 4.1.0 and chrome 116 well. But now on upgrading selenium to 4.11.2 this option I am unable to set to True. Current code

from selenium import webdriver
from selenium.webdriver.remote.webdriver import WebDriver

webdriver.DesiredCapabilities.CHROME['enableVNC']=True 
driver = webdriver.Remote(self.hub_url, options=option)

Does someone know how to set it to "True" or is this option changes or deprecated ? Also can you help how to set screen resolution to "1920*1080" for headless chrome ?

I tried all the setting the it using add_options, experimental options and all but it crashes the code. This time it didnt crashed the code but neither it started the VNC.

### How can we reproduce the issue?

```shell
This is easily reproducible.
```

### Relevant log output

```shell
With the logs, we cannot see anything as the code is running fine but on connecting to remote browser we cannot see The remote automated screen. While we were able to view that when "enableVNC" was set to true.
```

### Operating System

Mac OS Ventura

### Selenium version

Selenium 4.11.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 116 and 114

### What are the browser driver(s) and version(s) where you see this issue?

Selenium 4.11.2

**Comment by diemol** [comment]
That option does not belong to this project. You should reach out to your Grid provider asking how to use that option with your service.
