### ISSUE TITLE
Clicking zero-area element with nonzero-area children has unexpected results

### ISSUE THREAD

**Issue by MCGallaspy** [SeleniumHQ/selenium#1279]
Using `Python 3.4.3 :: Anaconda 2.3.0 (64-bit)` with package [selenium 2.48.0](https://pypi.python.org/pypi/selenium/2.48.0) and Firefox 40.0.3 on Windows 8.1.

I expect that calling [click](http://selenium-python.readthedocs.org/api.html#selenium.webdriver.remote.webelement.WebElement.click) on a zero-area element should either raise an exception or click a nonzero-area child element. ~~The latter behavior mirrors what "actually" happens. Clicking the child element below myself triggers the onclick event for the parent element -- but with WebDriver it does not!~~ Edit: that's not true.

To test copy the contents below into two files, amend `test.py` script to enter the path to `test.html`, then run `test.py`.

`test.html`:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zero area test case</title>
    <style type="text/css">
        .nonzero_child {
            position: absolute;
        }
        .zero_area {
            display: inline;
        }
    </style>
    <script type="text/javascript">
        function do_something() {
            alert("Hi ho!");
        }
    </script>
</head>
<body>
<div onclick="do_something()" class="zero_area">
    <div class="nonzero_child">Foo</div>
</div>
</body>
</html>
```

`test.py`:

``` python
from selenium import webdriver
from selenium.webdriver.common.alert import Alert

driver = webdriver.Firefox()

driver.get("file:///path/to/test.html")  # Put in the appropriate value here.

element = driver.find_element_by_class_name("nonzero_child")
element.click()
Alert(driver).accept()  # Works ok


element = driver.find_element_by_class_name("zero_area")
element.click()
Alert(driver).accept()  # Throws an error

```

**Comment by barancev** [comment]
It's not a Selenium issue, but a Firefox one.

Position of .zero_area element is (x:-7, y:8), according to the browser.
Selenium can't click because the element is out of view.
