### ISSUE TITLE
[🚀 Feature]: let me configure a "CDN url" for downloading the Chromedriver

### ISSUE THREAD

**Issue by RaHehl** [SeleniumHQ/selenium#12793]
### Feature and motivation

Hi, 

i'm behind a corporate proxy and we have cache mirrors for external dependencies.

I would like to specify my internal cache mirrors like here https://www.npmjs.com/package/chromedriver with chromedriver_cdnurl and chromedriver_cdnbinariesurl,

I couldn't find anything about this in the documentation or in the Selenium manager code.

### Usage example

as example via env variables

**Comment by titusfortner** [comment]
This is planned with #11687
