### ISSUE TITLE
[🐛 Bug]: I am getting version error

### ISSUE THREAD

**Issue by Ankit-Jakhmola** [SeleniumHQ/selenium#12790]
### What happened?

ERROR: Could not find a version that satisfies the requirement webdriver (from versions: none)
ERROR: No matching distribution found for webdriver

### How can we reproduce the issue?

```shell
Install latest python 0r any version of it.
open cmd and write pip install webdriver
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement webdriver (from versions: none)
ERROR: No matching distribution found for webdriver
```

### Operating System

windows 10 , 11

### Selenium version

selenium 4.12 , python 3.9, 3.11.5 , pip 23.2.1

### What are the browser(s) and version(s) where you see this issue?

for all browser

### What are the browser driver(s) and version(s) where you see this issue?

all browser

**Comment by AutomatedTester** [comment]
Hey

To install you need to do `pip install selenium` and it will install Selenium WebDriver for you.

**Comment by Ankit-Jakhmola** [comment]
yes I have tried pip install selenium and it is successfully installed Selenium but when I write webdriver in my code it is not importing the Webdriver package

**Comment by titusfortner** [comment]
here's working code to demonstrate - https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/python/tests/getting_started/test_first_script.py#L6
