### ISSUE TITLE
[🐛 Bug]: https://chromedriver.storage.googleapis.com/LATEST_RELEASE does not return the latest version of ChromeDriver

### ISSUE THREAD

**Issue by SvetlaNorka** [SeleniumHQ/selenium#12806]
### What happened?

My framework uses WebDriverManager.DriverConfigs.Impl and the following URL to get the latest version and download it.
https://chromedriver.storage.googleapis.com/LATEST_RELEASE
It returns 114.0.5735.90 but the latest version of ChromeDriver is 117.0.5938.88
according to https://googlechromelabs.github.io/chrome-for-testing/#stable
![image](https://github.com/SeleniumHQ/selenium/assets/143695583/3dfca69a-7bed-4a67-b833-3214c203d36a)
![image](https://github.com/SeleniumHQ/selenium/assets/143695583/19a4e58e-d784-49b7-aa8e-51615a2a840f)

### How can we reproduce the issue?

```shell
Open https://chromedriver.storage.googleapis.com/LATEST_RELEASE
```

### Relevant log output

```shell
Open https://chromedriver.storage.googleapis.com/LATEST_RELEASE
```

### Operating System

Windows 11

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114, 115, 117

**Comment by diemol** [comment]
Upgrade to the latest Selenium version, drop `WebDriverManager`, and let Selenium handle the browser driver configuration.
