### ISSUE TITLE
[🐛 Bug]: Returned value cannot be converted to Boolean

### ISSUE THREAD

**Issue by Duez-Yoan** [SeleniumHQ/selenium#12803]
### What happened?

Hi, 

Since i updated my framework to Serenity BDD 4.0.0 with Selnium 4.12 include and cucumber 7.14, i have an error on the website i test.

org.openqa.selenium.WebDriverException: Returned value cannot be converted to Boolean: {_wrapped=[org.openqa.selenium.remote.RemoteWebElement@9fa216dc -> unknown locator], after={}, all={}, allKeys={}, any={}, assign={}, before={}, bind={}, bindAll={}, chain={}, chunk={}, clone={}, collect={}, compact={}, compose={}, concat={}, constant={}, contains={}, countBy={}, create={}, debounce={}, default={}, defaults={}, defer={}, delay={}, detect={}, difference={}, drop={}, each={}, escape={}, every={}, extend={}, extendOwn={}, filter={}, find={}, findIndex={}, findKey={}, findLastIndex={}, findWhere={}, first={}, flatten={}, foldl={}, foldr={}, forEach={}, functions={}, get={}, groupBy={}, has={}, head={}, identity={}, include={}, includes={}, indexBy={}, indexOf={}, initial={}, inject={}, intersection={}, invert={}, invoke={}, isArguments={}, isArray={}, isArrayBuffer={}, isBoolean={}, isDataView={}, isDate={}, isElement={}, isEmpty={}, isEqual={}, isError={}, isFinite={}, isFunction={}, isMap={}, isMatch={}, isNaN={}, isNull={}, isNumber={}, isObject={}, isRegExp={}, isSet={}, isString={}, isSymbol={}, isTypedArray={}, isUndefined={}, isWeakMap={}, isWeakSet={}, iteratee={}, join={}, keys={}, last={}, lastIndexOf={}, map={}, mapObject={}, matcher={}, matches={}, max={}, memoize={}, methods={}, min={}, mixin={}, negate={}, noop={}, now={}, object={}, omit={}, once={}, pairs={}, partial={}, partition={}, pick={}, pluck={}, pop={}, property={}, propertyOf={}, push={}, random={}, range={}, reduce={}, reduceRight={}, reject={}, rest={}, restArguments={}, result={}, reverse={}, sample={}, select={}, shift={}, shuffle={}, size={}, slice={}, some={}, sort={}, sortBy={}, sortedIndex={}, splice={}, tail={}, take={}, tap={}, template={}, throttle={}, times={}, toArray={}, toJSON={}, toPath={}, toString={}, transpose={}, unescape={}, union={}, uniq={}, unique={}, uniqueId={}, unshift={}, unzip={}, value={}, valueOf={}, values={}, where={}, without={}, wrap={}, zip={}}

This is only since i update, with the previous version it still work fine.
I can't understand why, but i cannot check for the visibility of the element, i have this error when i used isDisplayed();

When i try to interact with element with some click, it works fine.

I tried a lot of solution but nothing works.
I tried with edge, chrome, firefox, i have the same error.

I have read that it could be an issue with the JS of the website wich is in conflict with the driver, but we don't know what could be in conflict.

i have exclude Selnium from the Serenity import, and import it in a porper import for selenium.
When i imported V4.12 i have the error, when i change for V4.11, i don't have the error.

### How can we reproduce the issue?

```shell
This is on a spécifique page of my company website wich is log.

If you want you can create an account on https://www.fnac.com

when this is done try this scenario :
- go to https://www.fnac.com
- click on the button "Me connecter"
- enter your login and password 
- you are redirected on the home page
- go to https://secure.fnac.com/account/dashboard

This is on this page that i have the error, only in this page, not the other page of the website.
When the cookie box appear, i check if the button "Accepter" is display and i have the error.

If you don't see the cookie box it can be because you already accept this earlier.
you can delete the cookie "OptanonConsent" and reload the page
In my case i have an url that let me go on this page directly connecter but i can't give this.
```

### Relevant log output

```shell
org.openqa.selenium.WebDriverException: Returned value cannot be converted to Boolean: {_wrapped=[org.openqa.selenium.remote.RemoteWebElement@9fa216dc -> unknown locator], after={}, all={}, allKeys={}, any={}, assign={}, before={}, bind={}, bindAll={}, chain={}, chunk={}, clone={}, collect={}, compact={}, compose={}, concat={}, constant={}, contains={}, countBy={}, create={}, debounce={}, default={}, defaults={}, defer={}, delay={}, detect={}, difference={}, drop={}, each={}, escape={}, every={}, extend={}, extendOwn={}, filter={}, find={}, findIndex={}, findKey={}, findLastIndex={}, findWhere={}, first={}, flatten={}, foldl={}, foldr={}, forEach={}, functions={}, get={}, groupBy={}, has={}, head={}, identity={}, include={}, includes={}, indexBy={}, indexOf={}, initial={}, inject={}, intersection={}, invert={}, invoke={}, isArguments={}, isArray={}, isArrayBuffer={}, isBoolean={}, isDataView={}, isDate={}, isElement={}, isEmpty={}, isEqual={}, isError={}, isFinite={}, isFunction={}, isMap={}, isMatch={}, isNaN={}, isNull={}, isNumber={}, isObject={}, isRegExp={}, isSet={}, isString={}, isSymbol={}, isTypedArray={}, isUndefined={}, isWeakMap={}, isWeakSet={}, iteratee={}, join={}, keys={}, last={}, lastIndexOf={}, map={}, mapObject={}, matcher={}, matches={}, max={}, memoize={}, methods={}, min={}, mixin={}, negate={}, noop={}, now={}, object={}, omit={}, once={}, pairs={}, partial={}, partition={}, pick={}, pluck={}, pop={}, property={}, propertyOf={}, push={}, random={}, range={}, reduce={}, reduceRight={}, reject={}, rest={}, restArguments={}, result={}, reverse={}, sample={}, select={}, shift={}, shuffle={}, size={}, slice={}, some={}, sort={}, sortBy={}, sortedIndex={}, splice={}, tail={}, take={}, tap={}, template={}, throttle={}, times={}, toArray={}, toJSON={}, toPath={}, toString={}, transpose={}, unescape={}, union={}, uniq={}, unique={}, uniqueId={}, unshift={}, unzip={}, value={}, valueOf={}, values={}, where={}, without={}, wrap={}, zip={}}
```

### Operating System

Windows 10

### Selenium version

4.12

### What are the browser(s) and version(s) where you see this issue?

chrome 117, edge 117  Firefox 117

### What are the browser driver(s) and version(s) where you see this issue?

selenium manager is using V115 or V116 sometime

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
This is related to #12659.
Will be fixed in 4.13
