### ISSUE TITLE
EnableMobileEmulation Method is not working when passing Apple device name.

### ISSUE THREAD

**Issue by Yash1067** [SeleniumHQ/selenium#12818]
### What happened?

**Expected Behaviour** 
The method **EnableMobileEmulation(string deviceName)** should open the browser in mobile compatibility mode. This means that when you browse a website, it should automatically redirect to the mobile version of the site. Let's experiment with Facebook.com.

**Actual Behaviour**
The **EnableMobileEmulation** method works correctly with Android devices. However, when you specify an Apple device name, Facebook's site does not automatically redirect to the mobile website. I also explored an alternative method:

**public void EnableMobileEmulation(ChromiumMobileEmulationDeviceSettings deviceSettings);**

This alternative method works consistently in all cases when you provide custom device information. Upon investigation, it appears that the user agent string is incorrect when using the **EnableMobileEmulation(string deviceName)** method.

### How can we reproduce the issue?

```shell
The following function should allow me to pass a device name which enable mobile emulation.

options.EnableMobileEmulation("iPhone 4");

In case of Apple device useragentstring is incorrect which is created by selenium internally
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 11

### Selenium version

Selenium 4

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 117

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment]
This is working for me with Selenium 4.12

```
var options = new ChromeOptions();
options.EnableMobileEmulation("iPhone 4");
var driver = new ChromeDriver(options);
```

Maybe it does not work from a Windows machine?
I don't have one hand to reproduce, but if that is true, it is a Chromedriver issue, not a Selenium one.

**Comment by ornichola** [comment]
[Created an issue (4603)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=4603)
