### ISSUE TITLE
[🐛 Bug]: SessionNotCreatedError 

### ISSUE THREAD

**Issue by ZeldaFlower** [SeleniumHQ/selenium#12811]
### What happened?

I’m just trying to build a test which will hit my website and verify it, but I can’t even get chrome to start up. 

Tried to post [Here](https://groups.google.com/g/selenium-users/search?q=Session%20not%20created) but it doesn’t look very active.

The official documentation [Here](https://www.selenium.dev/selenium/docs/api/javascript/index.html) has two issues:  
- one being a syntax error on the second await:  ` await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN); `
- The second is nothing is required to download now that selenium downloads chrome for you. 

However, since I can’t get it to work maybe there is an issue and/or more documentation needed. I have tried installing chromedriver with npm as well. I’ve also tried passing the port and instantiating it differently, but to me the “simple” example should work as is. The PATH variable has the /usr/bin which contains chromedriver.

### How can we reproduce the issue?

https://github.com/ZeldaFlower/Trivia/actions/runs/6267226699/job/17019829951

```shell

let driver = await new Builder().forBrowser('chrome').build();
try {
	await driver.get('http://www.google.com/ncr');
	await driver.findElement(By.name('q')).sendKeys('webdriver', Key.RETURN);
	await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
} finally {
	await driver.quit();
}

```

### Relevant log output

https://github.com/ZeldaFlower/Trivia/actions/runs/6267226699/job/17019829951

```shell

at Object.<anonymous> (source/utils/__tests__/html.test.js:25:11)

    console.debug
      Selenium Manager binary found at /home/runner/work/Trivia/Trivia/node_modules/selenium-webdriver/bin/linux/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

    console.debug
      Driver path: /usr/bin/chromedriver

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

    console.debug
      Browser path: /opt/google/chrome/google-chrome

      at logOutput (node_modules/selenium-webdriver/common/seleniumManager.js:148:15)

  ● html › test html

    SessionNotCreatedError: session not created: Chrome failed to start: exited normally.
      (session not created: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)

```

### Operating System

ubuntu-latest GitHub action

### Selenium version

4.12.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 114,116

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 114.0.2

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
DevToolsActivePort bug is a known issue that Google is working on.

**Comment by ZeldaFlower** [comment]
@titusfortner , thanks so much for the info! Is there a link to Google's ticket?

**Comment by titusfortner** [comment]
Not on my laptop right now, can search chromedriver bug tracker. There are several and to be honest I'm a little confused as to actual status of it.

**Comment by ZeldaFlower** [comment]
Sad I can't use chrome until this is fixed. Maybe I could use previous version of selenium? Also looking into firefox instead...

**Comment by ZeldaFlower** [comment]
I got firefox to work! https://groups.google.com/g/selenium-users/c/xNVh8F3UNRY/m/CcV4MImwAgAJ

@titusfortner , how do I ask for the documentation to be updated?

> The official documentation [Here](https://www.selenium.dev/selenium/docs/api/javascript/index.html) has two issues:
>
> - one being a syntax error on the second await: await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
> - The second is nothing is required to download now that selenium downloads chrome for you.

**Comment by titusfortner** [comment]
That documentation has a lot more than 2 issues. 😁 

We used to have a tool that would do automatic updates, but it is no longer working, and we haven't created a new one.

@diemol what do you think about our just deleting these files rather than keep them in their 2+ year old status?

**Comment by diemol** [comment]
Not sure. I think most of it should still be correct.

**Comment by ZeldaFlower** [comment]
Ok, can we fix the two issues I mentioned in documentation? Is it committed in the code vase here? Can I help?

**Comment by diemol** [comment]
The problem is https://github.com/SeleniumHQ/selenium/issues/10185, the docs generation is broken.

**Comment by titusfortner** [comment]
"DevToolsActivePort not found" bug fix: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
