### ISSUE TITLE
[🐛 Bug]: the internal method `EscapeCssSelector` Replace error.

### ISSUE THREAD

**Issue by ZhaoYis** [SeleniumHQ/selenium#12819]
### What happened?

<img width="923" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/22954818/801faed4-98b0-47fe-9fb1-47585c154249">

### How can we reproduce the issue?

```shell
[Fact]
    public void Test_EscapeCssSelector()
    {
        string s = EscapeCssSelector("s-container");
        s.ShouldBe("s-container");
        
        string EscapeCssSelector(string selector)
        {
            string str = Regex.Replace(selector, "([ '\"\\\\#.:;,!?+<>=~*^$|%&@`{}\\-/\\[\\]\\(\\)])", "\\$1");
            if (selector.Length > 0 && char.IsDigit(selector[0]))
                str = "\\" + (30 + int.Parse(selector.Substring(0, 1), (IFormatProvider) CultureInfo.InvariantCulture)).ToString((IFormatProvider) CultureInfo.InvariantCulture) + " " + selector.Substring(1);
            return str;
        }
    }
```

### Relevant log output

```shell
rt.
```

### Operating System

macOS

### Selenium version

C# Selenium.WebDriver 4.12.4

### What are the browser(s) and version(s) where you see this issue?

版本 109.0.5414.149（正式版本） （64 位）

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 109.0.5414.74

**Comment by nvborisenko** [comment]
It's not supposed to be used publicly. Can you please elaborate more about how you use it in real case?

PS. This is issue, but we should understand how it impacts you.

**Comment by ZhaoYis** [comment]
Yes, I am getting this error when using the FindElement method like below `webDriver.FindElement(By.ClassName("s-container"))`

**Comment by ZhaoYis** [comment]
To add to this, the program received the following error：
<img width="642" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/22954818/5d3e86ec-b931-4315-9b6f-fe2f9fc9080d">

**Comment by titusfortner** [comment]
The escape works as expected for locating elements by CSS Selector. 

Most likely the element you are looking for is not actually there. You can see this by trying:
```
webDriver.FindElement(By.CssSelector(".s-container"))
```

**Comment by ZhaoYis** [comment]
The style name `s-container` actually exists on my page,but I'll try the `CssSelector` method
![image](https://github.com/SeleniumHQ/selenium/assets/22954818/6b209079-5b29-42f4-a2d0-189067649095)

**Comment by nvborisenko** [comment]
I verified exactly the same code:
```csharp
webDriver.FindElement(By.CssSelector(".s-container"))
```

It found expected element.

**Comment by nvborisenko** [comment]
I double-checked exact code:
```csharp
webDriver.FindElement(By.CssSelector(".s-container"))
```

It found correct web element.

**Comment by titusfortner** [comment]
I'm going to guess it's either on the wrong page, or a race condition with the element not loading when the findElement is called. I can reopen if there is still an issue.
