### ISSUE TITLE
java: User-friendly description for By* classes (in error case)

### ISSUE THREAD

**Issue by ddemin** [SeleniumHQ/selenium#1282]
**Description**
1) It would be great to have opportunity for adding of user-friendly description for By locators:
// Some page object class
// Section with web-elements locators (as example)
private By someLocator = By.id("id123").description("Element Foo on page Bar");
// or
private By someLocator2 = By.id("id123", "Element Foo on page Bar");

2) For FindBy annotation need to add new attribute "description"

3) Need to change toString() method in ById and others By\* classes (add "description" output)

**Benefits**
More readable errors (element not found and etc). _Both_ locator and _user-friendly description_ (for problem element) will be present in test report (in stack-trace if error occured)

**Comment by AJ-72** [comment]
@lukeis @dimand58 Having this description in stacktrace would require changes at all driver implementations. The error message - Unable to locate element using {method: , selector :} comes from corresponding browser side implementation. Selenium doesn't use the By.toString() for stacktrace error message.

**Comment by diemol** [comment]
I think the comment above makes a good point, where this would imply changes in many places and the overall benefit would not be higher than the effort needed for its implementation.
