### ISSUE TITLE
[🐛 Bug]: java.lang.runtimeexemption : unable to find open port

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#12827]
### What happened?

I'm using selenium WebDriver for java on my Android app but the app crashes everytime I try to use it
the app logs indicate that there is a java.lang.runtimeexemption : unable to find an open port
I have tried using two different version of the WebDriver (4.12.1 and 4.13.0 )but the error is still the same

### How can we reproduce the issue?

```shell
WebDriver webDriver = new ChromeDriver();

webDriver.get("https://"+url);

String title = webDriver.getTitle();

Snackbar.make(binding.getRoot(),title,Snackbar.LENGTH_LONG).show();
```

### Relevant log output

```shell
ERROR: 09-27 00:20:44.154 9134 E AndroidRuntime: FATAL EXCEPTION: main ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: Process: my.webdriver.app2, PID: 9134 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: java.lang.RuntimeException: Unable to find a free port 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at org.openqa.selenium.net.PortProber.findFree Port (PortProber.java:61) 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at org.openqa.selenium.remote.service.DriverSe rvice$Builder.build(DriverService.java:488) 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at org.openqa.selenium.chrome.ChromeDriverServ e.java:137) ice.createDefaultService(ChromeDriverService)
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at org.openqa.selenium.chrome.ChromeDriver.<in it>(ChromeDriver.java:51)
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E = my.webdriver.app2.MainActivity$1.onClick(Ma inActivity.java:32) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E android.view.View.performClick(View.java:74 55) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E com.google.android.material.button.Material Button.performClick (MaterialButton.java:120 2) 
ERROR: 09-27 00:20:44.154 9134 AndroidRuntime: at 9134 E android.view.View.performClickInternal(View .java:7428) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E android.view.View.access$3600 (View.java:813)
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at android.view.View$PerformClick.run(View.jav a:28495)
ERROR: 09-27 00:20:44.154 AndroidRuntime: at android.os.Handler.handleCallback(Handler.j ava:938) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E android.os.Handler.dispatchMessage(Handler. java:99) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E android.os.Looper.loop(Looper.java:223) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E android.app.ActivityThread.main(ActivityThr ead.java:7740) 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 
ERROR: 09-27 00:20:44.154 9134 9134 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodA ndArgsCaller.run(RuntimeInit.java:612) 
ERROR: 09-27 00:20:44.154 AndroidRuntime: at 9134 9134 E com.android.internal.os.ZygoteInit.main(Zyg oteInit.java:997)
```

### Operating System

Android 11

### Selenium version

Java 4.13.0 and Java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by briangits** [comment]
> Hi, @briangits. Please follow the issue template, we need more information to reproduce the issue.
> 
> Either a complete code snippet and URL/HTML (if more than one file is needed, provide a GitHub repo and instructions to run the code), the specific versions used, or a more detailed description to help us understand the issue.
> 
> Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.
> 
> Reply to this issue when all information is provided, thank you.

the url i used is google.com
it does not even for wait a second once i try to get() the website,the just app crashed

**Comment by ghost** [comment]
the url i used is google.com
it does not even for wait a second once i try to get() the website,the just app crashed

**Comment by diemol** [comment]
Without code to reproduce the issue, there is not much we can do 🤷

**Comment by ghost** [comment]
> Without code to reproduce the issue, there is not much we can do 🤷

[app_source_code.zip](https://github.com/SeleniumHQ/selenium/files/12735722/app_source_code.zip)
this is my app source code
all selenium 4.13.0 jars were in my libs folder but i did not upload them

**Comment by krmahadevan** [comment]
@briangits - From the sample, it looks like you are trying to build an android app that internally uses selenium webdriver for launching a browser on the device. Is that what you are doing ? (My knowledge on android app development is limited and hence this naive question).

If that's the case, it would be good if you could please also help elaborate as to what is the use case that you are trying to solve here. That would help provide @diemol a bit more context on what you are trying to do.

**Comment by ghost** [comment]
> looks

I'm actually working on a different projects but the app crashed when i added selenium
So i decided to make the app whose source code i sent to test and see if it would work but it still crashed
The app is supposed to automate a my company's website such that it fills forms,clicks buttons,etc,
That is ,make an app version of the webpage
Can you help me please, I've tried using the Gradle depedancy and even adding the liblaries manually but it still doesn't work

**Comment by diemol** [comment]
We cannot troubleshoot your company's project, sorry. If you can reproduce the issue only using Selenium, we will be happy to look at it.

In the meantime, we could answer questions and help if you come to our community chat. Check the links below.
