### ISSUE TITLE
[🐛 Bug]: While downloading file from UI, UI pops up with Save Window even with the download location is already setup in chrome options.

### ISSUE THREAD

**Issue by rakeshkumarpanda** [SeleniumHQ/selenium#12829]
### What happened?

Code used to launch the chrome incognito:
Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("intl.accept_languages", "qps-ploc,en-us,en");
prefs.put("profile.default_content_settings.popups", 0);
prefs.put("download.prompt_for_download", false);
prefs.put("download.default_directory", map.get("downloadlocation"));
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("prefs", prefs);
options.addArguments("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36");
options.addArguments("enable-automation");
options.addArguments("--dns-prefetch-disable");
options.addArguments("--remote-allow-origins=*","ignore-certificate-errors");//Allowing for remote access
options.addArguments("–disable-site-isolation-trials");
options.addArguments("disable-features=DownloadUI");
options.addArguments("disbale-infobars");
options.addArguments("start-maximized");
options.addArguments("--incognito");
options.setPageLoadStrategy(PageLoadStrategy.EAGER);
return new ChromeDriver(options);

<img width="1720" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/32265155/ee413edd-baf2-4ceb-88eb-9b2105da7976">

Note: If I remove the option to set the incognito then the same code executes well and not getting save as an option

### How can we reproduce the issue?

```shell
Code snippet given above
```

### Relevant log output

```shell
In both incognito and normal mode, if the download option is already set in Chrome options then it should work consistently.
```

### Operating System

Mac OS 13, 14

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Incognito 117

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 117

### Are you using Selenium Grid?

No

**Comment by RodrigoZepeda** [comment]
I'm having the same issue with Chrome 117.0.5938.92 in Ubuntu 22.04.3 LTS
