### ISSUE TITLE
[🐛 Bug]: Hardcoded version 85 causes warnings on quit/close in firefox driver

### ISSUE THREAD

**Issue by Pe-te** [SeleniumHQ/selenium#12825]
### What happened?

I thought it would be a good idea to close the firefox window using driver.close() or driver.quit().

But this triggers a warning in the FirefoxDriver class, see below.

I was able to track the problem down to here, where it uses a hardcoded value of 85.0:

https://github.com/SeleniumHQ/selenium/blob/a0354265ea2eac1c6a3b55d3ba2940079d9c0682/java/src/org/openqa/selenium/firefox/FirefoxDriver.java#L335

My guess is that it should be a variable value depending on the browser version, so for example currently 118?

### How can we reproduce the issue?

```shell
FirefoxOptions firefox_options = new FirefoxOptions();
if (headless) {
    firefox_options.addArguments("--headless");
} else if (devtools) {
    firefox_options.addArguments("--devtools");
}
firefox_options.setLogLevel(FirefoxDriverLogLevel.ERROR); // this seems to be ignored
WebDriverManager.firefoxdriver().setup();
RemoteWebDriver driver = FirefoxDriver(firefox_options);
                driver.close(); // or driver.quit();
```

### Relevant log output

```shell
Sept. 26, 2023 4:20:27 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 85
```

### Operating System

MacOS, probably others too

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

Firefox 118.0.1 (64 bit)

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.33.0

### Are you using Selenium Grid?

no, local execution

**Comment by titusfortner** [comment]
No, Mozilla did not implement the changes from CDP 86, so Firefox will continue to be set to 85.

The browser vendors are actively working on the CDP replacement (WebDriver-Bidi) which will allow us to get away from Chrome specific version support entirely, so any future implementations will come from there.

We can try to reproduce this, though.

**Comment by Pe-te** [comment]
Thanks for the information!
If it is expected behaviour, maybe info level or even debug might make sense?

**Comment by pujagani** [comment]
Thank you for sharing the details. However, using the code snippet above, I am not able to reproduce the error. I tried with both headless and dev tools option passed. The test was using Selenium 4.12.1. Firefox version 118.0.1

**Comment by titusfortner** [comment]
Is there an error, or just a confusing warning message?

**Comment by Pe-te** [comment]
@titusfortner 
It's just a confusing warning and when you have many windows you miss the important logs.

@pujagani 
 This code can reproduce it:
```
    public static void main(String[] args) throws InterruptedException {
        WebDriverManager.firefoxdriver().setup();
        RemoteWebDriver driver = new FirefoxDriver();
        driver.get("https://github.com/SeleniumHQ/selenium/issues/12825");
        driver.close(); // or driver.quit();
    }
```
You can even omit the get-call, but i wanted to be sure it works.

Okay, after some testing, it looks like the message does not appear when I run the code directly (run or debug in IntelliJ).

I only see the message when I run it through "gradle runShadow" with this plugin:
```    
id 'com.github.johnrengelman.shadow' version '7.1.2'
```
Also when I run the jar from the command line, I get the same warning.
```
java -jar xy.jar
```
So probably something gets lost when is run inside a jar?
If I find out why, I will let you know, but so far the ticket can be closed I think.

Thank you for your support!

**Comment by titusfortner** [comment]
Weird. Couple notes in passing.

`close()` is for closing a browser window; it just happens to also close the session if it is the final window, but it sometimes doesn't do all the expected things in all the expected ways, so it is generally better to call `quit()` to end the session.

You shouldn't need `WebDriverManager.firefoxdriver().setup()`, Selenium does this natively now.

**Comment by Pe-te** [comment]
The message is gone as soon as you setup a real logger in the project and it gets included in the jar file.
Thanks again for all the help!
