### ISSUE TITLE
[🚀 Feature]: Improve dotnet-WebDriver's INetwork's usability

### ISSUE THREAD

**Issue by sbakharev** [SeleniumHQ/selenium#12821]
### Feature and motivation

Hello!

The current WD's `INetwork` interface (and it's surrounding types) is IMO quite weird and this dramatically limits the ways of using it:

1. It allows us to add multiple request handlers. Though each of those handlers has a `RequestMatcher` function, all this intuitively looks like you may have a chain of handlers and those of them who match the request would be sequentially applied to it. [In reality](https://github.com/SeleniumHQ/selenium/blob/707dc0c560272de02893ca7df5ed36111329372d/dotnet/src/webdriver/NetworkManager.cs#L229C27-L229C27) as soon as the first matching handler is found - others are ignored. The same applies to handlers of other types.
2. The `AddRequestHandler` method accepts only `NetworkRequestHandler` - a **class**-typed instance. The same applies to `AddResponseHandler` and `AddAuthenticationHandler`. So you cannot have a single class which is for example a request and response handler at the same time.
3. The `NetworkRequestHandler` class has two different routines - `RequestTransformer` and `ResponseSupplier`. But if `RequestTransformer` is defined then `ResponseSupplier` never gets called, so having both in one class makes no sense - and this basically violates the single responsibility principle.

Imagine a relatively simple use case:

- We need to add custom headers to **all** requests
- We also need to log requests and responses **only in "/api" subpath** (to avoid flooding the logs)

To achieve this you currently end up with a quite ugly implementation:

- A `NetworkRequestHandler` whose `RequestMatcher` returns `true` for virtually any request, then adds headers, and then performs logging _but only if the request path starts with "/api"_
- A `NetworkResponseHandler` whose `ResponseMatcher` returns `true` for "/api" requests and logs the response data
- A separate logger class whose instance will be shared between two handlers because both requests and responses shall naturally reside in a single log

Overall we're now stuck with poor flexibility and reusablility. The handlers in this model are eventually pretty much project- or even situation-specific. You can't, for example, have a set of small reusable handlers which you then may combine via [composite pattern](https://en.wikipedia.org/wiki/Composite_pattern).

### Usage example

If we think of a more conventional approach to interface/class modeling then we would have something like this:

- Handlers interfaces: `INetworkRequestTransformer`, `INetworkResponseSupplier`, `INetworkResponseTransformer` and `INetworkAuthenticationHandler`.
  - If `ContinueWithAuth`, `ContinueRequest` and `ContinueRequestWithResponse` are not too expensive to always call for all of the handlers (even those of them that will do nothing) then request matchers are not needed at all - implementations may incapsulate their own "bypass" logic when they need to. In case of response supplier and authentication handler a bypass may be indicated by simply returning null or with a more explicit indication such as [null object](https://en.wikipedia.org/wiki/Null_object_pattern).
  - It's also worth noting that there is no sense in making things like `RequestMatcher`, `RequestTransformer` etc. be `Func<>`-typed properties. This leads to less readable code while giving no advantages. Good old OOP (interfaces, virtual methods) is still viable and this is one of the tasks it has long ago specifically been designed for.
- `NetworkManager`'s `Add{*}Handler` methods take interfaces' instances instead of classes.
- `NetworkManager` calls the provided handlers sequentially. In case of response suppliers/authentication handlers only the first handler which returns an actual response/credentials counts and the rest are ignored.

In our example above we will now be able to do the same things way simpler:

- An `AddHeadersRequestTransformer: INetworkRequestTransformer` which adds custom headers
- A `RequestLogger: INetworkRequestTransformer, INetworkResponseTransformer` which incapsulates a single log both for requests and responses and accepts a list of paths in constructor to filter requests by URL

Voila! Those classes are small, simple and perfectly reusable between projects.

Why not?

**Comment by titusfortner** [comment]
Sorry for not triaging this earlier. @nvborisenko can you provide feedback on this one? Thank you.

**Comment by nvborisenko** [comment]
All points look valid, there is a wide field for improvements. Given that any improvement here will be considered as a breaking change, and current API design doesn't block you (just confuses little bit), this issue is minor.

We should consider all points when we will be designing BiDi.

**Comment by titusfortner** [comment]
@nvborisenko so we should close this as CDP related and implement it with BiDi?

**Comment by titusfortner** [comment]
@nvborisenko is there a specific action we should be taking on this one in the near term? Or is this part of the BiDi overhaul?

**Comment by nvborisenko** [comment]
If we rework it, then it will be a big breaking change. I would classify this issue as an improvement rather a bug. If we want to address it without re-designing API, then we can improve inline documentation to add more clarity how things are implemented.

If BiDi will bring new API (for end user), then we should consider concerns here and design new API very well.

**Comment by titusfortner** [comment]
Ok, I'm going to close this, then because it is something we know we need as part of what we end up doing for BiDi.
