### ISSUE TITLE
[🐛 Bug]: grid standalone max-sessions not honored when using --config

### ISSUE THREAD

**Issue by webtoman** [SeleniumHQ/selenium#12836]
### What happened?

When using a `standalone` grid, `max-sessions` is not honored if a `--config file` is provided. It does not work when setting it in the config file or on the command line. I can not set it to anything less or more than the number of CPUs, in this case 16.

It works fine when not using a `--config file`.

Using `selenium-server-4.12.1.jar`

### How can we reproduce the issue?

config.toml file:
```shell

[node]
detect-drivers = false
override-max-sessions = true
max-sessions = 32

[[node.driver-configuration]]
display-name = "my browser"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"108\", \"platformName\": \"Linux\"}"
webdriver-executable = '/path/to/selenium/chromedriver_108'
```

Command line:
`java -jar selenium-server.jar standalone --port 4567 --config config.toml`

### Relevant log output

```shell
14:53:34.010 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:53:34.014 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:53:34.599 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors
14:53:34.600 WARN [NodeOptions.getSessionFactories] - Overriding max recommended number of 16 concurrent sessions. Session stability and reliability might suffer!
14:53:34.600 WARN [NodeOptions.getSessionFactories] - One browser session is recommended per available processor. Safari is always limited to 1 session per host.
14:53:34.601 WARN [NodeOptions.getSessionFactories] - Overriding this value for Internet Explorer is not recommended. Issues related to parallel testing with Internet Explored won't be accepted.
14:53:34.601 WARN [NodeOptions.getSessionFactories] - Double check if enabling 'override-max-sessions' is really needed
14:53:34.601 WARN [NodeOptions.getSessionFactories] - Max sessions set to 32 
14:53:34.631 INFO [NodeOptions.report] - Adding my browser for {"browserName": "chrome","browserVersion": "108","platformName": "linux","se:webDriverExecutable": "\u002fpath\u002fto\u002fselenium\u002fchromedriver_108"} 16 times
14:53:34.674 INFO [Node.<init>] - Binding additional locator mechanisms: relative
14:53:34.690 INFO [GridModel.setAvailability] - Switching Node d7f1d49b-33fa-48a5-bc07-18c0cda7f84f (uri: http://<my-ip>:4567) from DOWN to UP
14:53:34.690 INFO [LocalDistributor.add] - Added node d7f1d49b-33fa-48a5-bc07-18c0cda7f84f at http://10.47.36.71:4567. Health check every 120s
14:53:34.799 INFO [Standalone.execute] - Started Selenium Standalone 4.12.1 (revision 8e34639b11): http://<my-ip>:4567
```

### Operating System

Ubuntu 

### Selenium version

java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

chrome 108

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 108

### Are you using Selenium Grid?

4.12.1

**Comment by webtoman** [comment]
Found a workaround(?) after I reported this. Setting `max-sessions` is needed both in the `[node]` and `[[node.driver-configuration]]` sections, like below. This is normally not required, as all drivers will inherit the max-sessions if you don't use a --config file.

```
node]
detect-drivers = false
override-max-sessions = true
max-sessions = 32

[[node.driver-configuration]]
max-sessions = 32
display-name = "my browser"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"108\", \"platformName\": \"Linux\"}"
webdriver-executable = '/path/to/selenium/chromedriver_108'
```

**Comment by titusfortner** [comment]
@diemol / @pujagani is there a way to change the defaults here, or is this what is expected?

**Comment by pujagani** [comment]
This is what is expected as per my understanding. Using 
```
[node]
detect-drivers = false
override-max-sessions = true
max-sessions = 32
```
works as expected for drivers it picks up on its own if `detect-drivers` is set to true.

But if we are specifying a `driver-configuration`, then we need to specify the driver-specific max session value as well else it picks up the default.

**Comment by diemol** [comment]
When we wrote this, the idea was to take the `max-sessions` value from the `[node]` section, and in case a `max-session` was found under `[[node.driver-configuration]]` then use that one.

Somehow the code was not reflecting that, it was using the one from `[node]`or the general default one.

I just made a fix that should improve this situation.
