### ISSUE TITLE
[🐛 Bug]: Log is spammed with "Unable to find an exact match for CDP version 117"

### ISSUE THREAD

**Issue by Artur-** [SeleniumHQ/selenium#12831]
### What happened?

Whenever a test is run and Selenium is not the very latest, or sometimes even the very latest version has not yet been released, each and every test logs
```
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
```

It is not useful to have 100s or 1000s of these in the build logs.

Instead of logging them as a warning, maybe log them as debug info? So far I have never seen a test fail because there was a mismatch of 1 in the version so maybe a "small" differences could be logged as debug and a "large" difference as a warning

### How can we reproduce the issue?

```shell
Run a Java test with any older Selenium version than the latest
```

### Relevant log output

```shell
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
Sep 28, 2023 1:35:29 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 117, so returning the closest version found: 116
```

### Operating System

macOs Big Sur

### Selenium version

4.12.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver

**Comment by titusfortner** [comment]
The mismatch can cause potentially undesired behavior, and (usually) there is an action that can be taken to fix this, so it should be flagged. The fix right now is to update to Selenium 4.13.

You can adjust what gets logged if you are using slf4j in logback.xml

```
    <logger name="org.openqa.selenium.devtools.CdpVersionFinder" level="OFF" />
```

Or, if you want to use my [Selenium Logger](https://github.com/titusfortner/selenium-logger)
```
new SeleniumLogger().filterOut("CdpVersionFinder")
```

**Comment by aevans-mms** [comment]
Thanks @titusfortner 

Is there any source for "potentially undesirable behavior" so users can see if their CDP / Driver version missmatch is causing specific issues?  Or is this just the normal lag between Chrome / ChromeDriver versions that should be less of an issue as Chrome for Testing becomes more widely adopted?

**Comment by titusfortner** [comment]
Selenium generates classes and methods for direct Chrome DevTools support. Google updates their DevTools code every release, so we need to regenerate everything on each release, and sometimes signatures of methods and parameters change and we have to fix it in the Selenium code. So you may have a method that Selenium is using that worked for an old version of Chrome, but will not work for the new version of Chrome.

But you're right we should change something, I'll make a PR with options
