### ISSUE TITLE
[🐛 Bug]: Removal of headless option

### ISSUE THREAD

**Issue by yanniszark** [SeleniumHQ/selenium#12837]
### What happened?

Was using the `headless` field in `Options`, which was removed.
Code was failing without any clue as to why.
Please consider failing loudly (for example, by keeping the property method and throwing an error).

### How can we reproduce the issue?

```shell
Set `headless` in `Options` for Chrome.
```

### Relevant log output

```shell
session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559a7afac6b3 <unknown>
#1 0x559a7ac821e7 <unknown>
#2 0x559a7acb5526 <unknown>
#3 0x559a7acb169c <unknown>
#4 0x559a7acf423a <unknown>
#5 0x559a7aceae93 <unknown>
#6 0x559a7acbd934 <unknown>
#7 0x559a7acbe71e <unknown>
#8 0x559a7af71cb8 <unknown>
#9 0x559a7af75bf0 <unknown>
#10 0x559a7af8019c <unknown>
#11 0x559a7af76808 <unknown>
#12 0x559a7af4327f <unknown>
#13 0x559a7af9ae88 <unknown>
#14 0x559a7af9b059 <unknown>
#15 0x559a7afab843 <unknown>
#16 0x7f0cbfb7a609 start_thread
.
Stack Trace: Traceback (most recent call last):
  File "projects/dev-container/scripts/extend_cloudlab_experiments.py", line 138, in main
    extend_experiments(username, password, args.notify_slack)
  File "projects/dev-container/scripts/extend_cloudlab_experiments.py", line 77, in extend_experiments
    cloudlab_client = CloudlabClient()
  File "/usr/local/lib/python3.8/dist-packages/cloudlab_client/client.py", line 104, in __init__
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559a7afac6b3 <unknown>
#1 0x559a7ac821e7 <unknown>
#2 0x559a7acb5526 <unknown>
#3 0x559a7acb169c <unknown>
#4 0x559a7acf423a <unknown>
#5 0x559a7aceae93 <unknown>
#6 0x559a7acbd934 <unknown>
#7 0x559a7acbe71e <unknown>
#8 0x559a7af71cb8 <unknown>
#9 0x559a7af75bf0 <unknown>
#10 0x559a7af8019c <unknown>
#11 0x559a7af76808 <unknown>
#12 0x559a7af4327f <unknown>
#13 0x559a7af9ae88 <unknown>
#14 0x559a7af9b059 <unknown>
#15 0x559a7afab843 <unknown>
#16 0x7f0cbfb7a609 start_thread
```

### Operating System

Ubuntu

### Selenium version

4.13

### What are the browser(s) and version(s) where you see this issue?

Latest Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Latest Version

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
It's frustrating to get unexpected behavior. Python is interesting in how it lets you assign anything to anything regardless of whether it does anything. `DevToolsActivePort` bug is known and Google is working on it.

As for headless, we threw deprecation warnings that it was going to be removed for most of the past year and wrote a [blog post](https://www.selenium.dev/blog/2023/headless-is-going-away/) explaining why.

At the same time, we don't want to maintain code that just throws error messages about what all things we don't support. It should be obvious that you aren't getting a headless session and hopefully easy to find out why with a Google search or a code inspection.

**Comment by yanniszark** [comment]
> As for headless, we threw deprecation warnings that it was going to be removed for most of the past year and wrote a [blog post](https://www.selenium.dev/blog/2023/headless-is-going-away/) explaining why.

That's great practice. In this case, I missed it since my code is running in an automated and pulling the latest selenium.

>  It should be obvious that you aren't getting a headless session and hopefully easy to find out why with a Google search or a code inspection.

Neither is obvious unfortunately. Googling / ChatGPTing the error wasn't very helpful (hopefully now it is, since Google will index this issue).

I would propose adding a third phase to your deprecation plan, which is to throw deprecation errors (not warnings).
I understand this is an open-source project with limited resources, so this is just my honest feedback.
Thanks for your effort, this is a great piece of software.

**Comment by titusfortner** [comment]
"DevToolsActivePort not found" bug fix: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35
