### ISSUE TITLE
[🐛 Bug]: The driver is created but can not use in mobile automation while using the Selenium version 4.8.3 upwards.

### ISSUE THREAD

**Issue by HasiniRangana** [SeleniumHQ/selenium#12845]
### What happened?

After I've upgraded Selenium version to 4.9.0 I'm no longer able to run my tests as I receive the following error.

**java.lang.ClassCastException: class com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to class org.openqa.selenium.WebElement (com.google.common.collect.Maps$TransformedEntriesMap and org.openqa.selenium.WebElement are in unnamed module of loader 'app')**

Below are the dependencies I have in pom for selenium and appium.

<dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.12.1</version>
</dependency>

<dependency>
      <groupId>io.appium</groupId>
      <artifactId>java-client</artifactId>
      <version>8.3.0</version>
</dependency>

### How can we reproduce the issue?

```shell
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.remote.AndroidMobileCapabilityType;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class MobileAutomationTest {

    private AndroidDriver<AndroidElement> driver;

    @BeforeTest
    public void setUp() throws MalformedURLException {
        // Set up desired capabilities
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "your_device_name");
        desiredCapabilities.setCapability(MobileCapabilityType.APP, "path/to/your/app.apk");

        // Optional: Set other capabilities such as appPackage and appActivity

        // Initialize the AndroidDriver
        driver = new AndroidDriver<>(new URL("http://localhost:4723/wd/hub"), desiredCapabilities);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Test
    public void mobileAppTest() {
        // Your test steps here
        MobileElement element = driver.findElementById("your_element_id");
        element.click();

        // Perform other actions and assertions as needed
    }

    @AfterTest
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
```

### Relevant log output

```shell
java.lang.ClassCastException: class com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to class org.openqa.selenium.WebElement (com.google.common.collect.Maps$TransformedEntriesMap and org.openqa.selenium.WebElement are in unnamed module of loader 'app')
```

### Operating System

Windows

### Selenium version

Java 11

### What are the browser(s) and version(s) where you see this issue?

Chrome 74 (Android Device)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 74.0.3729.185

**Comment by joerg1985** [comment]
@HasiniRangana i think you have a incompatible combination of versions, to use selenium 4.12.1 you should use appium 8.5.0 or 8.5.1
https://github.com/appium/java-client#compatibility-matrix

**Comment by HasiniRangana** [comment]
> @HasiniRangana i think you have a incompatible combination of versions, to use selenium 4.12.1 you should use appium 8.5.0 or 8.5.1 https://github.com/appium/java-client#compatibility-matrix

Tried with those two versions of appium. But same issue happened.

**Comment by titusfortner** [comment]
Looks like it is probably failing on `findElementById` which isn't a Selenium method. @mykola-mokhnach do you know what might be causing this and/or what Selenium broke this time? :)

**Comment by HasiniRangana** [comment]
> Looks like it is probably failing on `findElementById` which isn't a Selenium method. @mykola-mokhnach do you know what might be causing this and/or what Selenium broke this time? :)

I tried with 'driver().findElement(By.id("locator")).click()' also. Not worked for me. Same thing works with selenium java 4.8.3 version.

**Comment by mykola-mokhnach** [comment]
If both version from the compatibility matrix match then there should be no issues. Maybe some dependency was cached or there is a local misconfiguration.

**Comment by titusfortner** [comment]
@HasiniRangana check out this - https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

Also, the most recent version of Appium does not use generics with the driver any more, so your IDE should be complaining about this: `new AndroidDriver<>`

**Comment by HasiniRangana** [comment]
Issue resolved. This issue was caused by Chrome driver version 74.0.3729.185.

Thank you!
