### ISSUE TITLE
[🐛 Bug]: Unable to launch browser even after using Selenium 4.13 in a C# project

### ISSUE THREAD

**Issue by nairdinesh04** [SeleniumHQ/selenium#12856]
### What happened?

I upgraded my selenium nuget packages from 3.141 to 4.13 in a C# Project as I wanted to get rid of referring driver path in my code.
I thought to use the enhanced features of Selenium Manager.
After upgrade the browser does not launch and the error that I see is :

Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location =->
 The type initializer for 'OpenQA.Selenium.SeleniumManager' threw an exception. =->
 Unable to locate or obtain Selenium Manager binary at C:\Care Director\Automation\.......\selenium-manager/windows/selenium-manager.exe 

### How can we reproduce the issue?

```shell
case BrowserType.Chrome:
                    
                        
                       ChromeOptions chromeOptions = new ChromeOptions();
                      
                    chromeOptions.AddArguments(
                                                "--no-sandbox",
                                            "--disable-dev-shm-usage",
                                            //"--disable-gpu",
                                            "--window-size=1920,1080");
                    chromeOptions.AddExcludedArgument("enable-automation");
                    WebDriver = new ChromeDriver(chromeOptions);
                    WebDriver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(60);
                    break;
```

### Relevant log output

```shell
Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location =->
 The type initializer for 'OpenQA.Selenium.SeleniumManager' threw an exception. =->
 Unable to locate or obtain Selenium Manager binary at C:\Care Director\Automation\.......\selenium-manager/windows/selenium-manager.exe
```

### Operating System

Windows 10

### Selenium version

4.13

### What are the browser(s) and version(s) where you see this issue?

Tried with Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome - 117

### Are you using Selenium Grid?

No

**Comment by nvborisenko** [comment]
@nairdinesh04 can you verify manually where is `C:\Care Director\Automation.......\selenium-manager/windows/selenium-manager.exe`. It should be located in project's output directory (bin/Debug).

**Comment by nairdinesh04** [comment]
Hi Thanks for replying. I do see the selenium-manager.exe under ....\bin\Debug\selenium-manager\windows folder.

**Comment by nvborisenko** [comment]
Seems strange, it throws exception that file is not located at `C:\Care Director\Automation.......\selenium-manager/windows/selenium-manager.exe` when actually it is there.

Please create simple project for us to reproduce the issue.

**Comment by nairdinesh04** [comment]
I tried at might end with a new project and it worked fine. 
We use a proprietary automation framework in which when I run a test case using VS, its trying to find exe at a location, which is ....../TestResults\xxxxxx_xxxxxxxxx-10-02 23_55_27\Out\selenium-manager/windows/selenium-manager.exe . As per my understanding the exe should get copied to this location automatically which is not happening.

**Comment by nvborisenko** [comment]
Good finding. Please elaborate more about your VS version and how you execute tests to get `TestResults` folder.

**Comment by nairdinesh04** [comment]
VS-2017. As of now I am running the testcase using Test Explorer window in Visual Studio which creates TestResults folder automatically.

**Comment by nvborisenko** [comment]
Just to double check: do you use Selenium.WebDriver 4.13.0 or 4.13.1?

**Comment by nairdinesh04** [comment]
4.13.1 - Thanks for asking.

**Comment by nvborisenko** [comment]
We need simple test project to reproduce your issue.

**Comment by nairdinesh04** [comment]
Let me see how can I do this, might need a day or two. The challenge is to replicate the framework but I will try.

**Comment by nairdinesh04** [comment]
I tried to see how can I share the project but we have an installer in place to install the Automation framework which cannot be shared publicly. And I am suspecting the issue to be with the framework part of the world, I guess I am stuck.

**Comment by nvborisenko** [comment]
The core point here is that VS executes your tests assembly from `.../Out` foder rather than `bin/Debug` folder. If you can share a knowledge how to reproduce this behavior it would be much helpful.

I remember this is something related to `DeploymentItem`, but I would like to see it in action on my computer.

**Comment by nairdinesh04** [comment]
I would be really happy to share but I have my limitations in sharing. However what exactly you meant by "DeploymentItem"?

**Comment by nvborisenko** [comment]
The key point here we should understand how VS ran your tests from `/Out` folder rather than normally from `bin/Debug` folder. As soon as you can provide steps how to reproduce this behavior, I will take a look. Hopefully it would be easy fix.

**Comment by nairdinesh04** [comment]
Ya I got that, let me see if I can provide any code snippet. 
I will try from my side also to put up a fix.

**Comment by nairdinesh04** [comment]
Update - I was able to fix this by adding a way to deploy selenium-manager.exe in Out folder through code.
Thanks you for your time and effort @nvborisenko
