### ISSUE TITLE
2.48.x: WebDriver#getCurrentUrl doesn't change when switching to another frame 

### ISSUE THREAD

**Issue by pkaul** [SeleniumHQ/selenium#1285]
For Selenium version 2.47.x (and before), switching to another frame (using webDriver.switchTo().frame(String)) has caused webDriver#getCurrentUrl() to be changed correctly the the frame's URL. Since 2.48.x this does not happen any longer. Instead the parent frame's URL is returned. 

As a result it is no longer possible to determine the URL of a page that is currently displayed in an iframe.

**Comment by lukeis** [comment]
This is per specification:
http://www.w3.org/TR/webdriver/#get-current-url

"The Get Current URL command returns the URL of the current top-level browsing context."

If you need the url of the current frame you can do something like:  driver.executeScript("return window.location.toString()")
