### ISSUE TITLE
[🐛 Bug]: Script Pinning does not work on Augmented driver 

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12854]
### What happened?

Script pinning is defined in `JavaScriptExecutor` interface. 
This interface is only implemented in RemoteWebDriver.
It needs a separate class that implements `AugmenterProvider` in order to be used.

I took a stab at it, but lots of complexity to it, and I wasn't sure I was even going about it the right way.

### How can we reproduce the issue?

Does not work:

```
WebDriver driver = new RemoteWebDriver(url, new ChromeOptions());
driver = new Augmenter().augment(driver);
JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
jsExecutor.pin(isDisplayedScript);
```

Works:
```
WebDriver driver = new RemoteWebDriver(url, new ChromeOptions());
JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
driver = new Augmenter().augment(driver);
jsExecutor.pin(isDisplayedScript);
```

### Relevant log output

Local and Grid logs:
https://gist.github.com/titusfortner/6ba9aaafb54bffa1623c510678984b58

### Operating System

Mac

### Selenium version

Trunk

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

Trunk

**Comment by joerg1985** [comment]
@titusfortner the provided logs show `2023-10-02 20:45:56 WARNING Selenium [WebSocket onError] Unexpected frame CONTINUATION (fin=false) ` this should be fixed in 5d44d12. Could you check if the issue is still valid? thanks in advance

**Comment by titusfortner** [comment]
The issue as I recall is you have to cast to javascript executor to access the interface with the method, but then you have to cast to has devtools for it to work in remote webdriver

**Comment by joerg1985** [comment]
Thank you for the clarification, so the 'Does not work:' is more like will throw a ClassCastException / not compile

**Comment by titusfortner** [comment]
Remote webdriver does a check for instance of has devtools to determine if it can use bidi, so it just uses the backup path

**Comment by titusfortner** [comment]
Simon fixed this in London
