### ISSUE TITLE
[🚀 Feature]: RelativeBy locators to be able to filter out already found WebElements

### ISSUE THREAD

**Issue by MykolaGolubyev** [SeleniumHQ/selenium#12850]
### Feature and motivation

**Feature**
Given acquired list of WebElements, filter them down to the ones that are near/below/above/etc another element

**Motivation**
A list of WebElements can be acquired using various means. Near/below/above/etc locators currently require you to re-acquire them using `By` semantics. It may not be possible, or it can be repeating the routing again.   

### Usage example

```
WebElement myDivider = findAnchor();
List<WebElement> listToFilter = findWebElements(customOptions);
List<WebElement> RelativeLocators.with(listToFilter).above(myDivider);
```

**Comment by diemol** [comment]
I do not understand the feature proposal. You mean to retrieve a locator but ignore other ones.

Can you expand more and maybe give an example?

**Comment by MykolaGolubyev** [comment]
Hi @diemol, sorry for the delay in my response. 
Current API let me find all elements that match passed `By` and that are `above` a certain element.
I already have a list of `WebElement` and want to reduce that list to only elements that are `above` a certain element. 
Here is the example from before 
```
WebElement myDivider = findAnchor(); // element to use as above target
List<WebElement> listToFilter = findWebElements(customOptions); // list of web elements that I already acquired
List<WebElement> RelativeLocators.with(listToFilter).above(myDivider); // filter my elements using new Selenium 4 API
```

**Comment by titusfortner** [comment]
We are not currently actively working on updates to the support classes. We will be doing a review of these in the future, but for now we're not tracking them. Thanks.
