### ISSUE TITLE
[🐛 Bug]: Unable to obtain browser driver

### ISSUE THREAD

**Issue by xaliander** [SeleniumHQ/selenium#12859]
### What happened?

On raspberry Pi 4 with Debian GNU/Linux 11 (bullseye) aarch64 I installed chromium-browser, then Selenium webdriver. 

`sudo apt-get install chromium-browser`

```
$ chromium-browser --version
/etc/chromium.d/README: line 1: Any: command not found
dpkg-query: no packages found matching bluealsa
Chromium 113.0.5672.95 Built on Debian , running on Debian 11
```

`sudo apt-get install chromedriver`
```
$ chromedriver -v
ChromeDriver 113.0.5672.95 (917deeefba48411c7b40ba19aef7b229bf48acd7-refs/branch-heads/5672_63@{#13})
$ chromedriver
Starting ChromeDriver 113.0.5672.95 (917deeefba48411c7b40ba19aef7b229bf48acd7-refs/branch-heads/5672_63@{#13}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

This shows that the webdriver is working and that the chromium and webdriver versions align. When using the chromedriver with NodeJS however, I receive the error message below.

### How can we reproduce the issue?

```shell
Here is a Gist, that contains the code:
https://gist.github.com/xaliander/33c65256d65b44ff0eb5d1aeeff9352f
```

### Relevant log output

```shell
/home/user/folder/node_modules/selenium-webdriver/common/driverFinder.js:35
    throw Error(
    ^

Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/.
        Error: Error executing command for /home/user/folder/node_modules/selenium-webdriver/bin/linux/selenium-manager 
        with --browser,chrome,--output,json: /home/user/folder/node_modules/selenium-webdriver/bin/linux/selenium-manager:
        1: Syntax error: "(" unexpected

    at getPath (/home/user/folder/node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at thenableWebDriverProxy.createSession (/home/user/folder/node_modules/selenium-webdriver/chromium.js:696:45)
    at thenableWebDriverProxy.createSession (/home/user/folder/node_modules/selenium-webdriver/chrome.js:223:13)
    at createDriver (/home/user/folder/node_modules/selenium-webdriver/index.js:152:33)
    at Builder.build (/home/user/folder/node_modules/selenium-webdriver/index.js:680:16)
    at Object.<anonymous> (/home/user/folder/test.js:6:4)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
```

### Operating System

Raspberry Pi OS

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chromium 113.0.5672.95

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 113.0.5672.95

### Are you using Selenium Grid?

No?

**Comment by xaliander** [comment]
Also, I want to mention that I found [this Bug report](https://github.com/SeleniumHQ/selenium/issues/12456
) by [Pauan](https://github.com/Pauan) if it is of any relevance.

This issue should have been solved in 4.12 as [titusfortner](https://github.com/titusfortner) commented [last month](https://github.com/SeleniumHQ/selenium/issues/12456#issuecomment-1706481150).
 
Unfortunately, the error seems to persist, at least on the Raspberry Pi setup that I have.

**Comment by titusfortner** [comment]
1. #12456 is unrelated to your issue.
2. Selenium project does not maintain either of those npm packages.
3. The standard chromedriver install won't work on raspberry pi because Google does not support it

You would need to find a custom install of the driver that works on your architecture and reference it in your selenium code.

**Comment by xaliander** [comment]
Thank you for your reply Titus, point 3 is quite helpful. 👍
Likely this is why I ended up with npm packages that are not maintained by the Selenium project.
Cheers!
