### ISSUE TITLE
[🚀 Feature]: Configurable user export of OpenTelemetry data

### ISSUE THREAD

**Issue by cartersocha** [SeleniumHQ/selenium#12864]
### Feature and motivation

Hi, I'm from the OpenTelemetry community. We've recently added synthetic ping testing as part of the Collector with the http check receiver. It would be great to take the pre-existing Selenium OTel integration and expose that data to other backends besides Jaeger. Ideally a user could configure a custom exporter or at least send the data to a Collector of their choice. 

### Usage example

Most enterprises already have an Observability vendor for traces and would prefer their synthetic data to be in the same place as their other monitoring signals. Jaeger is great for local development but limits the applicability of Selenium tests for scaling the testing suite and correlating results.

**Comment by diemol** [comment]
I think this is already possible. @pujagani, do you know?

**Comment by pujagani** [comment]
Thank you for reaching out. We are using the OpenTelemetry autoconfiguration. Any exporter that can configured via that is supported. I have not looked into collectors. But I assume it is possible to configure sending data to a collector in a similar manner. I will need to check. But I understand why it might a good idea to have this ability.

**Comment by cartersocha** [comment]
Okay thanks for following up! I’m hoping to write a blog on this integration for the OTel website

**Comment by pujagani** [comment]
That's great! What is the blog focused on? Any way we can help? 
Our OpenTelemetry usage is documented here: https://www.selenium.dev/documentation/grid/advanced_features/observability/ Let me know if that helps or needs refining.

**Comment by cartersocha** [comment]
Following up on this [blog](https://opentelemetry.io/blog/2023/synthetic-testing/)  to show it’s possible to do more complex tests too

**Comment by titusfortner** [comment]
So what does Selenium need to do? Is the request to investigate implementing collectors?

**Comment by cartersocha** [comment]
Hi @titusfortner just getting back from the holidays. From what I can tell Selenium already uses the java agent for tracing but relies on the jaeger exporter instead of the native OTLP exporter. Our ask would be to update to the OTLP format. @tylerbenson please chime in

**Comment by tylerbenson** [comment]
I recently [contributed a PR](https://github.com/manoj9788/tracing-selenium-grid/pull/8) to help streamline that repo.  I think that demonstrates reasonably well how to report OTLP tracing data via OpenTelemetry.  Preferably you should have public documentation somewhere that defines how to officially do this.

I think the main ask is to ensure the process is streamlined and as easy as it can be.  Please also conform to [OpenTelemetry Semantic Conventions](https://opentelemetry.io/docs/specs/semconv/) as much as possible.  When there are areas that don't have existing semantic conventions, please consider contributing some.

Finally, when testing we noticed there was a root span being generated but not reported. I haven't dug into the source of this span yet, but would be willing to collaborate if someone is available to troubleshoot.

![image](https://github.com/SeleniumHQ/selenium/assets/734411/aca43624-afed-446d-b62c-fce96e93e45b)

**Comment by pujagani** [comment]
I appreciate your contribution however that is not a Selenium-owned repo. 
Selenium has its documentation regarding tracing and how users can set it up. If OLTP exporter is the recommended way,  we will be more than happy to add that bit to our documentation.

"Finally, when testing we noticed there was a root span being generated but not reported. I haven't dug into the source of this span yet, but would be willing to collaborate if someone is available to troubleshoot."
If this is a concern, it might a good idea to report this as a bug so we can track and address it separately.

**Comment by titusfortner** [comment]
So, the recommendation is for the users to parse what this project provides in a specific way. Our documentation for observability is here: https://www.selenium.dev/documentation/grid/advanced_features/observability/

Any suggested changes/updates can be tracked in our docs repo.

If there is a bug in the implementation, please open a new ticket with the details.

Thanks!

**Comment by tylerbenson** [comment]
@pujagani I realize it's not selenium owned, but it is [linked to directly from your docs repo](https://www.selenium.dev/documentation/grid/advanced_features/observability/#visualizing-traces).

You suggest using Jaeger on your doc site.  [The Jaeger exporter is actually deprecated.](https://github.com/open-telemetry/opentelemetry-java/issues/5096)
I'm trying to suggest that you update your docs to use OTLP and consider adding a more in depth tutorial.

**Comment by titusfortner** [comment]
Yes, those docs are ours. The source is here — https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/website_and_docs/content/documentation/grid/advanced_features/observability.en.md?plain=1

If you can help with a PR there, we would greatly appreciate it.
We'd also love to host a [blog post](https://www.selenium.dev/blog/) about this if you're interested.
I find the topic fascinating, but personally do not have time to dig into any of it, unfortunately.

Thanks!

**Comment by pujagani** [comment]
@tylerbenson Thank you for this. I understand this better now. Adding OTLP seems right, I can help do that from the Selenium side inspired by the work you have already done. 
You have more knowledge and insights in this domain, as Titus mentioned, we would love to host a blog post about it if you would like to contribute in that form. 

Thank you!
