### ISSUE TITLE
[🐛 Bug]: Multiple Firefox instances error: session is already started

### ISSUE THREAD

**Issue by searchexplore** [SeleniumHQ/selenium#12862]
### What happened?

I'm using Python, Selenium and Ubuntu 22.04. I can open multiple Chrome windows, but when I try to do the same using Firefox I just get this error after opening the first window:
`selenium.common.exceptions.SessionNotCreatedException: Message: Session is already started`

### How can we reproduce the issue?

I tried to open multiple Firefox windows using the same method I used to open Chrome windows: make a driver with a different profile for each instance:

```
geckodriver_path = "/snap/bin/geckodriver"
driver_service = Service(executable_path=geckodriver_path)
options = [] * 10
drivers = [] * 10

for x in range(0, 10):
    options[x] = Options()
    options[x].add_argument('-profile')
    options[x].add_argument(dir + profile[x])
    drivers[x] = webdriver.Firefox(service = driver_service, options=options[x])
```

The profiles seems to be working, because I can open one Firefox window for each one and its respective folder gets filled. The problem is when I try to open more than one instance.
Also, I've tried to use `options[x].profile = FirefoxProfile(dir + perfil[x])` instead of
```
options[x].add_argument('-profile')
options[x].add_argument(dir + profile[x])
```
but I still get the same error.

### Relevant log output

```shell
selenium.common.exceptions.SessionNotCreatedException: Message: Session is already started
```

### Operating System

Ubuntu 22.04

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 118.0.1

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.33.0

**Comment by titusfortner** [comment]
When you start a chromedriver on a given port, you can create multiple sessions from that driver on that port. You cannot do this with geckodriver. But, I'm not seeing where you are doing this in your code, a new geckodriver instance should be starting on a new port.

Turn on logging and we can see what you are passing in - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by searchexplore** [comment]
Oh, I see. Thank you very much, Titus. I managed to open multiple sessions passing a different port for each instance to the Service.
