### ISSUE TITLE
[🐛 Bug]: step definition that is not reconized in feature files

### ISSUE THREAD

**Issue by DomZZ** [SeleniumHQ/selenium#12885]
### What happened?

I added a step definition with a param (regular expression that should accept 2 different strings (collapse or expand)
then in the C# method I know how to behave depending on the param value.

But the step definition that is not reconized in feature files...

### How can we reproduce the issue?

```csharp
[When(@"I click on summary card ""(expand|collapse)"" button")]
public void WhenIClickOnSummaryCardCollapseExpandButton(string cardAction)
{
   throw new PendingStepExpception();
}
```

But I've observed that if there is other params it works : 
```csharp
[When(@"I click on summary card ""(expand|collapse)"" button with label ""([^""]*)""")]
public void WhenIClickOnSummaryCardCollapseExpandButton(string cardAction, string label)
{
   throw new PendingStepExpception();
}
```

### Relevant log output

```shell
nothing relevant, check feature file
```

### Operating System

Windows 11

### Selenium version

4.13.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 117

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
This looks like a cucumber or specflow issue, not something for Selenium. I'll add some links for where else to ask questions in case someone else might be able to help.
