### ISSUE TITLE
[🐛 Bug]: Selenium Manager is no longer a native Apple Silicon binary

### ISSUE THREAD

**Issue by MrSerth** [SeleniumHQ/selenium#12884]
### What happened?

With the newest version 4.13.1 of selenium manager for Ruby, the binary no longer ships as a Universal binary containing native x86_64 and arm64 code. Instead, it only contains x86_64 instructions. 

Previous versions, such as 4.13.0 and 4.12.0, were Universal binaries with native support for both architectures. Since I don't have Rosetta installed, running Selenium Manager fails:

```
bad CPU type in executable: selenium-webdriver-4.13.1/bin/macos/selenium-manager
```

This bug report is probably linked to #12423

### How can we reproduce the issue?

On any Mac:
```
$ file selenium-manager
Mach-O 64-bit executable x86_64
```

On an Apple Silicon Mac **without Rosetta**:
```
$ ./selenium-manager
bad CPU type in executable: ./selenium-manager
```

### Relevant log output

```shell
$ file selenium-webdriver-4.*/bin/macos/selenium-manager

selenium-webdriver-4.8.6/bin/macos/selenium-manager:  Mach-O 64-bit executable x86_64
selenium-webdriver-4.9.0/bin/macos/selenium-manager:  Mach-O 64-bit executable x86_64
selenium-webdriver-4.9.1/bin/macos/selenium-manager:  Mach-O 64-bit executable x86_64
selenium-webdriver-4.10.0/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64
selenium-webdriver-4.11.0/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64
selenium-webdriver-4.12.0/bin/macos/selenium-manager: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
selenium-webdriver-4.12.0/bin/macos/selenium-manager (for architecture x86_64):      Mach-O 64-bit executable x86_64
selenium-webdriver-4.12.0/bin/macos/selenium-manager (for architecture arm64):       Mach-O 64-bit executable arm64
selenium-webdriver-4.13.0/bin/macos/selenium-manager: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
selenium-webdriver-4.13.0/bin/macos/selenium-manager (for architecture x86_64):      Mach-O 64-bit executable x86_64
selenium-webdriver-4.13.0/bin/macos/selenium-manager (for architecture arm64):       Mach-O 64-bit executable arm64
selenium-webdriver-4.13.1/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64
```

### Operating System

macOS Sonoma 14.0 (23A344)

### Selenium version

Ruby 4.13.1

### What are the browser(s) and version(s) where you see this issue?

all browsers

### What are the browser driver(s) and version(s) where you see this issue?

any driver

**Comment by titusfortner** [comment]
Wow, yes, looking at the binaries and I'm guessing I forgot to stamp the build when I did the 4.13.1 release, which made the binary that got released the testing version for my old mac rather than the production one. 🤦 

The goal is to release 4.14 early next week. Please use 4.13.0 in the meantime.

**Comment by titusfortner** [comment]
Should be correct now, thanks.
