### ISSUE TITLE
[🚀 Feature]:  Create a "switch to dom" method to select/unselect a shadow dom

### ISSUE THREAD

**Issue by joseajunior** [SeleniumHQ/selenium#12891]
### Feature and motivation

I think it will be very beneficial to create a method in which we can select a shadow dom and treat it as the document and use all the methods available without having to always find the element before doing something.

Maybe treat a shadow DOM the same way it does for the frames.

### Usage example

Using python as example
```
driver.switch_to.shadow_dom([WebElement or ShadowRoot])
element = driver.find_element(By, <indicator for an element inside the shadow dom>)
driver.switch_to.default_context() # To go back to default DOM
```

**Comment by titusfortner** [comment]
On the merits, I find switching into and out of frames to be a huge pain. I'm a big fan of Watir's approach to avoid that entirely. The Selenium solution to Shadow content is much more aligned with what I like.  It's even fewer lines of code:

```python
shadow_host = driver.find_element(By.ID, 'shadow_host')
shadow_root = shadow_host.shadow_root
shadow_content = shadow_root.find_element(By.ID, 'shadow_content')
bright_element = driver.find_element(By.ID, 'noshadow')
```
vs
```python
shadow_host = driver.find_element(By.ID, 'shadow_host')
driver. switch_to.shadow_dom(host)
shadow_content = driver.find_element(By.ID, 'shadow_content')
driver.switch_to.default_context()
bright_element = driver.find_element(By.ID, 'noshadow')
```

Regardless, the main issue is that Selenium only wants to provide one way to do something, and generally follow the way that the w3c spec presents it.

That said, you can create your own solution for doing this in Python that has the behavior you want by wrapping the driver class and storing the desired search context in a way that you can change it as desired.
