### ISSUE TITLE
[🐛 Bug]: How to use proxy with --selenium-manager flag?

### ISSUE THREAD

**Issue by raja-anbazhagan** [SeleniumHQ/selenium#12908]
### What happened?

I'm setting up automatic driver download for Selenium nodes. However, our firewalls only allow internet access through proxy. Is there a way to set the proxy settings for the nodes to use?

### How can we reproduce the issue?

```shell
Try using a selenium node to access the internet through a http proxy server behind a corporate firewall.
```

### Relevant log output

```shell
URLs like https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json are not accessible as we cannot specify proxy settings anywhere
```

### Operating System

Windows 10

### Selenium version

Java 17 with selenium 3. But it doesn;t matter for this issue.

### What are the browser(s) and version(s) where you see this issue?

Chrome 117

### What are the browser driver(s) and version(s) where you see this issue?

all

### Are you using Selenium Grid?

Selenium 4.13

**Comment by titusfortner** [comment]
How are you specifying the proxy for your browser tests? Selenium Manager is using the same proxy as the proxy value in the options class.

**Comment by raja-anbazhagan** [comment]
@titusfortner , this is not related to proxy set-up for tests. 

The issue is mainly for nodes to download chromedrivers from internet when --selenium-manager flag was enabled. At this point I have not even setup a single node. So no scripts have run yet.

**Comment by titusfortner** [comment]
ah, right, the flag is in the command line list here — https://www.selenium.dev/documentation/selenium_manager/#configuration
