### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mestami-eksponat** [SeleniumHQ/selenium#12910]
### What happened?

I want to use socks5 proxy, here are my usage attempts:

1 attempt:
```
ChromeOptions options = new ChromeOptions();
        String host = "xxx.xxx.xxx.xxx";
        String port = "xxx";
        String socks5User = "xxx";
        String socks5Pass = "xxx";
        Proxy proxy = new Proxy();
        proxy.setSocksProxy(host+":"+port);
        proxy.setSocksPassword(socks5Pass);
        proxy.setSocksUsername(socks5User);
        proxy.setSocksVersion(5);
        options.setCapability("proxy",proxy);
        options.addArguments("--window-size=1920x1080");
        WebDriver driver = new ChromeDriver(options);
        driver.get("http://checkip.amazonaws.com");
```
2 attempt: 
```
ChromeOptions options = new ChromeOptions();
        String host = "xxx.xxx.xxx.xxx";
        String port = "xxx";
        String socks5User = "xxx";
        String socks5Pass = "xxx";
        options.addArguments("--proxy-server=socks5://"+socks5User+":"+socks5Pass+"@"+host+":"+port);
        options.addArguments("--window-size=1920x1080");
        WebDriver driver = new ChromeDriver(options);
        driver.get("http://checkip.amazonaws.com");
```
But none of the interfaces worked, although the proxies are fully working, and when receiving a request they work fine, Selenium error:
`Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: net::ERR_PROXY_CONNECTION_FAILED
        `

### What browsers and operating systems are you seeing the problem on?

**Operating System**
Windows 10 & Ubuntu 20.04 LTS

**Selenium version**
4.13.0

**What are the browser(s) and version(s) where you see this issue?**
Chrome

**What are the browser driver(s) and version(s) where you see this issue?**
117.0.5938.149

**Are you using Selenium Grid?**
No response

**Comment by titusfortner** [comment]
The first way is the suggested approach for Selenium, but the fact that the second way doesn't work either, points to this being a chromedriver issue.
