### ISSUE TITLE
[🐛 Bug]: Selenium4 not working with Octopus

### ISSUE THREAD

**Issue by andrei-z** [SeleniumHQ/selenium#12925]
### What happened?

I recently upgraded my automation solution to use Selenium4. Locally everything works OK, but the tests are also running in an Octopus pipeline where they are failing.

When the tests are running from Octopus this is the error I get:
![image](https://github.com/SeleniumHQ/selenium/assets/57134052/11c9269b-95d4-4c61-8581-c0b9549eefbd)

In order to debug the issue I've run manually on the machine where the tests are deployed the command line that was failing and it works ok:
![image](https://github.com/SeleniumHQ/selenium/assets/57134052/f152bc70-725a-4ce5-b80d-5537a701c2e1)

Another step I did was to add the same line in an Octopus "Run script" step and got his result:
![image](https://github.com/SeleniumHQ/selenium/assets/57134052/01b50e06-fdb8-4517-89cc-3923c39b449f)

I've spoke to the guys taking care of It and they said that the issue is not related to user rights, firewalls, network issues etc.
Si my only guess is that there might be some issue on Selenium4 working together with Octopus? Did anyone else had the same issue?

Thank you!

### How can we reproduce the issue?

```shell
Run automated tests using Selenium4 from Octopus pipeline.
```

### Relevant log output

```shell
No output available.
```

### Operating System

N/A

### Selenium version

Selenium 4.12.4

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by diemol** [comment]
If you want to use Selenium Manager with Grid, you must allow the user and machine to reach that URL. It would be best if you also tried to upgrade to 4.14.0.

I will leave a link below where you can ask more questions.

**Comment by andrei-z** [comment]
I'm not using Selenium Manager with Grid. Also, as you can see from my second screenshot when running the process under the same user as it is from Octopus the driver is downloaded correct, meaning that it can reach that URL.

**Comment by diemol** [comment]
You should come to our community chat and we can figure it out.

**Comment by andrei-z** [comment]
Where can I join the community? Thank you!

**Comment by diemol** [comment]
The links from the comment above.

**Comment by nvborisenko** [comment]
You can reach me out in Slack. If we will not be able to resolve environment issue, then we can ask octopus guys.

**Comment by titusfortner** [comment]
Nikolay wants to be in charge of tracking this issue down. I'll open it back up while he's investigating.

**Comment by nvborisenko** [comment]
@andrei-z only one ask: on that machine, where you execute tests, can you kind of ping the 
![image](https://github.com/SeleniumHQ/selenium/assets/22616990/6dcf0c23-f923-4aca-8296-d2f7b8a023d6)

exactly using the same pipeline/actions/flow as you use for tests execution.

**Comment by andrei-z** [comment]
Thank you for you suggestion! I've tried to ping googlechromelabs.github.io and google.com from both octopus pipeline and directly from the machine where the tests are deployed and got time out, even though he urls are accessible via browser. Now we are investigating in this direction.

**Comment by nvborisenko** [comment]
Most likely you are under proxy, this why web sites are accessible for browsers. AFAIK selenium manager still doesn't respect configured system-widely proxy.

**Comment by titusfortner** [comment]
In the normal course of things, Selenium Manager uses the same proxy information that is passed into the options class for the browser to use. If something else needs to be used an environment variable or config file can be used.

**Comment by nvborisenko** [comment]
It is good, but not always work for all cases. Let's say I am testing internal web application, which is accessible only internally (without proxy). But I am under corporate proxy to reach out internet. In this sooo popular case:
- WebDriver should not use proxy
- Selenium Manager should use proxy

Selenium Manager's proxy can be configured via environmental variables: https://www.selenium.dev/documentation/selenium_manager/#configuration

I am closing this issue. @andrei-z when you figure out what is blocking internet network and will not be able to mitigate it, please create a new issue.
