### ISSUE TITLE
[🐛 Bug]: Selenium Manager should support latest Firefox ESR browser

### ISSUE THREAD

**Issue by elliottj** [SeleniumHQ/selenium#12926]
### What happened?

Running with Selenium-java bindings 4.14.0 and, as no browsers installed, using Selenium Manager.

Create a firefox webdriver session with any of the following:
```
FirefoxOptions options = new FirefoxOptions();
options.setBrowserVersion("115");
```

or 
```
FirefoxOptions options = new FirefoxOptions();
options.setBrowserVersion("115.3");
```

or 
```
FirefoxOptions options = new FirefoxOptions();
options.setBrowserVersion("115.3.1");
```

These pull Firefox 115.0.3 not the current latest ESR of 115.3.1.

### How can we reproduce the issue?

```shell
See above.
```

### Relevant log output

```shell
n/a
```

### Operating System

Windows 10

### Selenium version

Java 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 115

### What are the browser driver(s) and version(s) where you see this issue?

Gecko 0.33.0

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
We do not support ESR, just the regular browser release. I will leave this issue open for a while and see the community's interest in this.

**Comment by titusfortner** [comment]
Ideally we're getting the latest version of the requested number, though.
And we should absolutely support `setBrowserVersion("esr")` the same way we do "beta" and "dev"

**Comment by elliottj** [comment]
Agreed 'ESR' would be a better label to use in this instance.

**Comment by titusfortner** [comment]
@bonigarcia did we look at supporting "ESR?" I can't remember if we did and there was a reason we can't do it.

**Comment by bonigarcia** [comment]
We currently don't support Firefox ESR. But adding a new label (`setBrowserVersion("esr")`) to support it should be easy. I can do it for the next release.

**Comment by titusfortner** [comment]
Thank you!

**Comment by bonigarcia** [comment]
Completed via #12946.
