### ISSUE TITLE
[🐛 Bug]: selenium-http-jdk-client missing 4.14.0

### ISSUE THREAD

**Issue by TWiStErRob** [SeleniumHQ/selenium#12927]
### What happened?

Trying to [upgrade Selenium from 4.13.0 to 4.14.0](https://github.com/TWiStErRob/net.twisterrob.healthcheck/pull/148) and got an error not finding the POM, and indeed the version is missing:
https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-http-jdk-client

I don't see anything relevant at a quick glance at release notes:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.14.0/java/CHANGELOG#L1-L18

### How can we reproduce the issue?

Try to use 4.14.0 of the above artifact.

### Relevant log output

https://github.com/TWiStErRob/net.twisterrob.healthcheck/actions/runs/6471424930/job/17569820257?pr=148#step:5:223

```text
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.seleniumhq.selenium:selenium-http-jdk-client:4.14.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-http-jdk-client/4.14.0/selenium-http-jdk-client-4.14.0.pom
     Required by:
         project :
```

### Operating System

N/A

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Selenium 4.14.0 requires Java 11 and that is why you do not need to include the client explicitly in the dependencies. 

https://www.selenium.dev/blog/2023/selenium-4-14-released/#highlights

**Comment by TWiStErRob** [comment]
Thank you! Makes sense. Would it make sense to update the changelog file to make this explicit?
