### ISSUE TITLE
[🐛 Bug]: Selenium cannot draw inner document for page with complicated structure (html->body->etc.->iframe->html->body->etc.)

### ISSUE THREAD

**Issue by IvanRastamanov** [SeleniumHQ/selenium#12922]
### What happened?

Selenium cannot draw page with complicated structure.
There is html->body->etc. of page
Then there an iframe for modal window.
And then inside this iframe there is another html->body->etc.
And this inner html document content is invisible for selenium.

### How can we reproduce the issue?

```shell
Cannot share code due to NDA
```

### Relevant log output

```shell
Actually no log available, just standard "element not found" error for elements from inner html.
```

### Operating System

Windows 10

### Selenium version

C# 7.2

### What are the browser(s) and version(s) where you see this issue?

MSEdge 117.0.2045.60

### What are the browser driver(s) and version(s) where you see this issue?

MSEdgeDriver 117.0.2045.35

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
We cannot triage anything until we get a way to reproduce the issue.

**Comment by titusfortner** [comment]
Selenium only handles one browsing context at a time. To work with a different frame on the page, you must explicitly switch into that frame.

https://www.selenium.dev/documentation/webdriver/interactions/frames/

**Comment by IvanRastamanov** [comment]
Hey, @titusfortner ,
Yes, I know about handling iframes, but even if I switch, elements inside are not drawn by engine, so I cannot interact with them.

**Comment by titusfortner** [comment]
It's working as expected in our tests (and for everyone else), so we would need to figure out what is different in your specific context that might keep it from working. There's nothing we can do if you can't provide some kind of example that reproduces the problem you're seeing.
