### ISSUE TITLE
[🐛 Bug]: Does selenium 4.14.0 require the user selenium-http-jdk-client?

### ISSUE THREAD

**Issue by vicozohili** [SeleniumHQ/selenium#12923]
### What happened?

Does selenium 4.14.0 require the user selenium-http-jdk-client?

Selenium 4.13.0 required selenium-http-jdk-client 4.13.0, however selenium-http-jdk-client 4.14.0 is not in maven repository.
Can we use selenium-http-jdk-client 4.13.0 with selenium 4.14.0?

### How can we reproduce the issue?

```shell
.
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome v117

### Are you using Selenium Grid?

4.14.0

**Comment by diemol** [comment]
Selenium 4.14.0 requires Java 11 and `selenium-http-jdk-client` is used by default, you do not need to add it.

Check the release notes at https://www.selenium.dev/blog/2023/selenium-4-14-released/#highlights
