### ISSUE TITLE
[🐛 Bug]: Selenium Manager not using se-config.toml file

### ISSUE THREAD

**Issue by elliottj** [SeleniumHQ/selenium#12939]
### What happened?

Selenium-manager 0.4.14 does not use the se-config.toml file

`C:\Users\aftadmin\.cache\selenium\se-config.toml` exists and I've tried these values, separately, to set a cache path:

```
cache-path = C:\AFT\sm
cache-path = "C:\AFT\sm"
cache-path=C:\AFT\sm
cache-path="C:\AFT\sm"
```

But browser downloads use the default path:
```
C:\AFT>selenium-manager.exe --browser firefox --browser-version stable --debug
DEBUG   geckodriver not found in PATH
DEBUG   firefox not found in PATH
DEBUG   Running command: REG QUERY HKCU\Software\Mozilla\Mozilla Firefox /v CurrentVersion
DEBUG   Output: ""
DEBUG   firefox stable not found in the system
DEBUG   Required browser: firefox 118.0.2
DEBUG   Downloading firefox 118.0.2 from https://ftp.mozilla.org/pub/firefox/releases/118.0.2/win64/en-US/Firefox%20Setup%20118.0.2.exe
DEBUG   firefox 118.0.2 is available at C:\Users\aftadmin\.cache\selenium\firefox\win64\118.0.2\firefox.exe
DEBUG   Required driver: geckodriver 0.33.0
DEBUG   Downloading geckodriver 0.33.0 from https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-win64.zip
INFO    Driver path: C:\Users\aftadmin\.cache\selenium\geckodriver\win64\0.33.0\geckodriver.exe
INFO    Browser path: C:\Users\aftadmin\.cache\selenium\firefox\win64\118.0.2\firefox.exe
```
It does work when I used the inline flag (--cache-path) or an evnt variable (SE_CACHE_PATH=CACHE_PATH)

### How can we reproduce the issue?

```shell
See above
```

### Relevant log output

```shell
See above
```

### Operating System

Windows 10

### Selenium version

Selenium-manager 0.4.14

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
@bonigarcia, do you know what might be the issue?

**Comment by bonigarcia** [comment]
See: https://github.com/SeleniumHQ/selenium/issues/12782#issuecomment-1729668712

**Comment by elliottj** [comment]
Ahh my mistake using this:
`cache-path = 'C:\\AFT\\sm'`

it's working as expected in 0.4.14. Possibly worth adding to docs as an example?

**Comment by bonigarcia** [comment]
Yes, it can be added to the Selenium Manager doc as an example of cache-path in Windows.
