### ISSUE TITLE
IEDriver - Can't Delete Specific Cookies Only All

### ISSUE THREAD

**Issue by kmgilbert100** [SeleniumHQ/selenium#1293]
In IEDriver I cannot delete specific cookies, I can only delete all.

https://github.com/webdriverio/webdriverio/issues/884#issuecomment-158337510

**Comment by jimevans** [comment]
Unfortunately, this _isn't_ a universal bug in the IE driver, others' opinions notwithstanding. There are tests in the WebDriver test suite testing exactly this functionality (proof available at [this link](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/CookieImplementationTest.java#L154)). Furthermore, those tests are running without fail on no less than 5 versions of Internet Explorer on every commit into the project (7, 8, 9, 10, 11) as seen on our [continuous integration server](http://ci.seleniumhq.org:8080/).

The full extent of the issue report is "this feature doesn't work," but the feature demonstrably _**does**_ work. If there is other information unique to the execution environment that causes this feature not to work with IE, that information should be added to the report. Unless and until that happens, however, there is no action that can be taken on this issue.
