### ISSUE TITLE
Collect Network Response Headers

### ISSUE THREAD

**Issue by Aditi729** [SeleniumHQ/selenium#12936]
### Feature and motivation

The motivation behind is to interact with the chrome dev tools and interact with the details under Network Tab. For ex- Headers, Response for the website visited

### Usage example

I would use this feature by collecting the data from response and evaluating and storing all the details for better interaction on different websites. To analyze the response and behaviour of the UI.

**Comment by titusfortner** [comment]
This is already possible https://www.selenium.dev/documentation/webdriver/bidirectional/bidi_api/#intercept-responses

**Comment by Aditi729** [comment]
What I need to fetch is these details using Selenium CSharp:
![image](https://github.com/SeleniumHQ/selenium/assets/71227373/385b8e4c-41d8-4876-b078-fc90699e7ebf)

**Comment by pujagani** [comment]
As Titus mentioned, it is possible. Please have a look at https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk//examples/dotnet/SeleniumDocs/Bidirectional/BidiApiTest.cs#L33-L48.

**Comment by Aditi729** [comment]
The code snippet doesn't provide any help to what I am asking for. Would be helpful if explained with example how this code snippet will help in my query.

**Comment by nvborisenko** [comment]
```csharp
var network = _webDriver.Manage().Network;

network.NetworkResponseReceived += (sender, e) => Console.WriteLine(e.ResponseHeaders);

await network.StartMonitoring();
```

**Comment by Aditi729** [comment]
@nvborisenko I am writing this following piece of code but still not able to get any value in response: something is not right with the way network variable is getting created I guess


//IWebDriver webDriver = new ChromeDriver(driverPath);
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.AddHttpProxy("proxy.com", 8011, "bdc77fbfe16e417cb3e75627c2c4c816", "");


chromeOptions.AddArgument("--start-maximized");

IWebDriver webDriver = new ChromeDriver(driverPath, chromeOptions);
webDriver.Navigate().GoToUrl("https://whatismyipaddress.com/");
Thread.Sleep(10000);
var network = webDriver.Manage().Network;


network.NetworkResponseReceived += (sender, e) =>
{
    var response = e.ResponseHeaders;
   
};

**Comment by nvborisenko** [comment]
Subscribe on the event: network.NetworkResponseReceived += (sender, e) =>
Start monitoring of network requests: await network.StartMonitoring();
Navigate to web page: webDriver.Navigate().GoToUrl("https://whatismyipaddress.com/");
Profit.

**Comment by Aditi729** [comment]
This didn't help either. Could you help with the entire code step-wise you are trying to explain please?

**Comment by Aditi729** [comment]
I am trying to implement this certain code now to fetch ResponseBody but getting this error, any idea which can help to remove this error and get my expected response?
![image](https://github.com/SeleniumHQ/selenium/assets/71227373/f6e4bf59-eee3-49b7-b1a9-322822a6008f)

**Comment by titusfortner** [comment]
You already have the response body: `e.Response.ResponseBody` you don't want to nest devtools commands here.

You either create a handler that lets you transform or you use the information in the response as it is received.

This issue tracker is not the right place to discuss how to use the code that is available. I'll add some links below for where you can ask more questions.
