### ISSUE TITLE
Python Firefox RemoteWebDriver doesn't flush profile to disk

### ISSUE THREAD

**Issue by erikbeerepoot** [SeleniumHQ/selenium#1294]
The Python Firefox remote WebDriver does not flush the FF profile to disk. Thus, if the user updates the profile by calling `set_preference(...)`, the profile that is sent over is just an empty zip file, with no feedback that this is the case. 

I'm curious if this is by design, as it can lead to some length debugging sessions when you are running the remote driver - locally, this does not appear to be an issue, as the preferences are kept in memory. Hence, you get unexpected results when you run tests on, say, a CI server via Selenium Grid. Locally tests that rely on settings changes will pass, remotely they will fail.

**Comment by lukeis** [comment]
Can you show some sample code that demonstrates the problem?

I'm assuming you mean that you are using a pre-existing firefox profile and creating your python FirefoxProfile object with specifying a profile_directory?

**Comment by erikbeerepoot** [comment]
Sure. Though it's a little tricky. Locally, we would do:
```
>>> from selenium import webdriver
>>> ffProfile = webdriver.firefox.firefox_profile.FirefoxProfile()
>>> ffProfile.path
'/var/folders/zk/79j88k_s2s14wvtm7fcbwzdxy8x651/T/tmpkLY7ui'
>>> ffProfile.set_preference("network.cookie.cookieBehavior",2)
>>> ffProfile.default_preferences["network.cookie.cookieBehavior"]
2
>>>driver = webdriver.firefox.webdriver.WebDriver(firefox_profile=ffProfile)
```
This will launch firefox. Type `about:config` in the address bar, and search for `network.cookie.cookieBehavior`, you will see that it is set to 2:

![screen shot 2015-11-20 at 3 12 49 pm](https://cloud.githubusercontent.com/assets/2739381/11314327/61410d7c-8f99-11e5-8b7c-88618ce45519.png)

Now, I have selenium running in one of the provided docker containers. We create a new profile, and open a remote session using that profile:
```
>>> cleanffProfile = webdriver.firefox.firefox_profile.FirefoxProfile()
>>> cleanffProfile.set_preference("network.cookie.cookieBehavior",2)
>>> cleanffProfile.path
'/var/folders/zk/79j88k_s2s14wvtm7fcbwzdxy8x651/T/tmppJmhvV'
>>> driver = webdriver.firefox.webdriver.RemoteWebDriver(desired_capabilities=webdriver.DesiredCapabilities.FIREFOX.copy(),browser_profile=cleanffProfile)
```
VNC into the machine, type `about:config`, and search for `network.cookie.cookieBehavior`. You find:

![screen shot 2015-11-20 at 3 23 43 pm](https://cloud.githubusercontent.com/assets/2739381/11314493/d26418cc-8f9a-11e5-9406-f87c3d118f60.png)

Note that if you use the same profile (the one you used locally), it is written to disk and it is then communicated properly. If you flush the profile using `update_preferences()` it will also end up on the disk and be communicated properly. 

This happens because the profile is read from disk, zipped and base64 encoded before being sent along in the `desired_capabilities` object. See here:

Init the remote webdriver init:
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L127
```
       self.start_client()
        self.start_session(desired_capabilities, browser_profile)
        self._switch_to = SwitchTo(self)
        self._mobile = Mobile(self)
        self.file_detector = LocalFileDetector()
```

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L127

Which calls start session, which retrieves an encoded version of the profile:
```
def start_session(self, desired_capabilities, browser_profile=None):
        if browser_profile:
            desired_capabilities['firefox_profile'] = browser_profile.encoded
        response = self.execute(Command.NEW_SESSION, {
            'desiredCapabilities': desired_capabilities,
        })
        self.session_id = response['sessionId']
        self.capabilities = response['value']

        # Quick check to see if we have a W3C Compliant browser
        self.w3c = "specificationLevel" in self.capabilities
```

Which itself goes to disk. However, that folder is still empty, as nothing has been actually written to disk, and thus, the below code just generated an empty zip file (we can clearly tell by the header):

```
>>> base64.b64decode(cleanffProfile.encoded)
'PK\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_profile.py#L162

```
    @property
    def encoded(self):
        """
        A zipped, base64 encoded string of profile directory
        for use with remote WebDriver JSON wire protocol
        """
        fp = BytesIO()
        zipped = zipfile.ZipFile(fp, 'w', zipfile.ZIP_DEFLATED)
        path_root = len(self.path) + 1  # account for trailing slash
        for base, dirs, files in os.walk(self.path):
            for fyle in files:
                filename = os.path.join(base, fyle)
                zipped.write(filename, filename[path_root:])
        zipped.close()
        return base64.b64encode(fp.getvalue()).decode('UTF-8')
```

**Comment by lukeis** [comment]
yeah... i think that 'encoded' should call _write_user_prefs at the start of it and i think that would solve the issue described.

**Comment by erikbeerepoot** [comment]
+1
