### ISSUE TITLE
[🐛 Bug]: printOptions.setOrientation()  Doesn't seem to work.

### ISSUE THREAD

**Issue by jaychoubaby** [SeleniumHQ/selenium#12945]
### What happened?

 I have set it to portrait mode, but the generated PDF file seems to still be in landscape mode.

`ChromeDriver chromeDriver = (ChromeDriver) webDriver;`
`PrintOptions printOptions = new PrintOptions();`
`printOptions.setOrientation(PrintOptions.Orientation.PORTRAIT);`

### How can we reproduce the issue?

```shell
The code is provided above.
```

### Relevant log output

```shell
non
```

### Operating System

Windows10

### Selenium version

java 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 116.0.5845.188

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

### Are you using Selenium Grid?

selenium-java 4.12.1

**Comment by jaychoubaby** [comment]
I understand, I need to set `pageSize` at the same time for it to take effect.
`PageSize pageSize = new PageSize();`
`printOptions.setPageSize(new PageSize(pageSize.getWidth(),pageSize.getHeight()));`

But I feel like it shouldn't be done this way, because I see that the pageSize default has width and height. If I change the direction, I should just swap the width and height.

**Comment by pujagani** [comment]
Can you try the latest version 4.14.1? The default width and height values needed to be swapped and those changes we landed recently. I wonder if that fixes things.

**Comment by jaychoubaby** [comment]
> Can you try the latest version 4.14.1? The default width and height values needed to be swapped and those changes we landed recently. I wonder if that fixes things.

ok , i will try.

**Comment by jaychoubaby** [comment]
> Can you try the latest version 4.14.1? The default width and height values needed to be swapped and those changes we landed recently. I wonder if that fixes things.

version 4.14.1 Doesn't it support JDK 8 anymore?We still mainly use JDK8. Unfortunately, I am unable to test it.

**Comment by titusfortner** [comment]
Java 8 is almost ten years old.
Continuing to support it was causing problems (specifically security issues with http client dependency), and Java 11 is required as of Selenium 4.14 — https://www.selenium.dev/blog/2023/java-8-support/

Now is a good time to look into upgrading.

**Comment by jaychoubaby** [comment]
> Java 8 is almost ten years old. Continuing to support it was causing problems (specifically security issues with http client dependency), and Java 11 is required as of Selenium 4.14 — https://www.selenium.dev/blog/2023/java-8-support/
> 
> Now is a good time to look into upgrading.

Okay, I understand, but there are dependencies in my program that do not support versions higher than JDK 8, so I cannot upgrade temporarily. I will work with manually setting the `pagesize `for now. Thank you for your answer.
