### ISSUE TITLE
[🐛 Bug]: MicrosoftEdgeDriver cannot send requests: "error sending request for url (https://edgeupdates.microsoft.com/api/products): error trying to connect: dns error: failed to lookup address information: Name does not resolve"

### ISSUE THREAD

**Issue by foshesss** [SeleniumHQ/selenium#12949]
### What happened?

I'm attempting to use the Microsoft Edge driver with Selenium but am getting an error message that's telling me I cannot send requests. Selenium is raising a NoSuchDriverException, but I assume that the driver is being found because the error seems specific to Edge.

My PATH variables seem to be correct as well-- typing `msedgedriver.exe` in my terminal starts the Microsoft Edge driver. 

For those curious about the PATH, 'edgedriver_win32' is the folder that contains the driver executable, and that is located in my C drive:
`/mnt/c/edgedriver_win32:/mnt/c/edgedriver_win32/msedgedriver.exe`

As you can see, I added the executable to the PATH just for good measure (thought maybe adding it might miraculously fix something-- it did not).

EDIT: Wanted to add that I also tried setting the selenium logger to DEBUG. I got no additional logs about the problem.

### How can we reproduce the issue?

```shell
Not sure if this happens on every machine, but the steps to reproduce on mine are:
1. Install the msedgedriver.exe
2. Set the PATH variables to point at the folder that contains it.
3. Add these two lines to a Python script:

from selenium import webdriver

edgeBrowser = webdriver.Edge()

4. Run the Python script.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 98, in driver_location
    output = self.run(args)
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 146, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MicrosoftEdge --output json.
{'code': 65, 'message': 'error sending request for url (https://edgeupdates.microsoft.com/api/products): error trying to connect: dns error: failed to lookup address information: Name does not resolve', 'driver_path': '', 'browser_path': ''}


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/will/chess/bot.py", line 4, in <module>
    edgeBrowser = webdriver.Edge()
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/edge/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/home/will/chess/venv/lib/python3.10/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Windows 11

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge

### What are the browser driver(s) and version(s) where you see this issue?

MicrosoftEdgeDriver 118.0.2088.46

**Comment by titusfortner** [comment]
Do you have Microsoft Edge installed in the normal place on your computer? v114 now manages the browser as well, and if it can't find it, then it is going to try to download it, and it appears your machine is behind a proxy in some fashion so it can not download it, either.

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP.
