### ISSUE TITLE
[🐛 Bug]: logs dont generate on 4.14

### ISSUE THREAD

**Issue by devinschumacher** [SeleniumHQ/selenium#12953]
### What happened?

geckodriver.log files dont generate on selenium 4.14

it took like 2 hours to figure out why but eventually i found an older project that was still generating them (4.10)

i donwgraded to that and got the log file.

### How can we reproduce the issue?

```shell
make an error on 4.14
```

### Relevant log output

```shell
lol
```

### Operating System

mac

### Selenium version

4.14

### What are the browser(s) and version(s) where you see this issue?

firefox

### What are the browser driver(s) and version(s) where you see this issue?

gecko

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Since 4.10 or 4.11 for some languages, browser driver logs are not sent to the console anymore, with the idea of reducing noise in most cases. 

Check https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output

**Comment by titusfortner** [comment]
Details for how to work with driver logs are in the docs.
https://www.selenium.dev/documentation/webdriver/drivers/service/#logging

**Comment by devinschumacher** [comment]
ty guys!
