### ISSUE TITLE
[🐛 Bug]: not possible to force download of matching chromedriver version

### ISSUE THREAD

**Issue by fippo** [SeleniumHQ/selenium#12957]
### What happened?

In the [WebRTC samples repository](https://github.com/webrtc/samples) we test a lot against unstable Chrome versions. Sometimes this leads to an incompability between the chromedriver version and the chromeversion unless both match (or are close enough).

Currently this fails in Chrome 120+ when run in github workflows [here](https://github.com/webrtc/samples/actions/runs/6536523341/job/17748415684?pr=1631) (relevant bits of the log below, [PR here](https://github.com/webrtc/samples/pull/1631)) because the chromedriver version (117) [preinstalled by the github image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) is found in `/usr/bin/chromedriver` has an interop issue with Chrome 120.

On machines which don't have chromedriver in such a widely known path this *just works*  by downloading a matching chromedriver 🎉 

Deleting `/usr/bin/` from the path is a bit hard. I have not yet tried adding a workflow step to remove the chromedriver (or symlink) which might require elevated privileges.

[selenium-manager](https://www.selenium.dev/documentation/selenium_manager/)  which I presume handles this behind the scenes does offer options to force a browser download but nothing for the driver download (or that would allow excluding a directory from the search path)

@bonigarcia any ideas how to fix that?

### How can we reproduce the issue?

```shell
https://github.com/webrtc/samples
```

### Relevant log output

```shell
Selenium Manager binary found at /home/runner/work/samples/samples/node_modules/selenium-webdriver/bin/linux/selenium-manager

      at getBinary (node_modules/selenium-webdriver/common/seleniumManager.js:56:13)

  console.warn
    The chromedriver version (117.0.5938.92) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (120.0.6062.2); currently, chromedriver 120.0.6070.0 is recommended for chrome 120.*, so it is advised to delete the driver in PATH and retry
```

### Operating System

Ubuntu 20 (22) on github actions

### Selenium version

Javascript 5.x

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 117

**Comment by titusfortner** [comment]
This is expected behavior right now. While Selenium Manager is in beta, the long-time behavior will be respected, which is if a driver is found on the system it will be used. You can remove the directory with the driver in GitHub actions.

We'll be discussing plans for how we transition it to selenium 5 in the near future.

**Comment by bonigarcia** [comment]
Including a new Selenium Manager argument for not using the drivers found in PATH (e.g., `--skip_driver_in_path`) would be pretty straightforward. As usual, this option could be enabled using an environment variable (`SE_SKIP_DRIVER_IN_PATH=true`), which could be a solution for skipping drivers in GH Actions workers. I can prepare a PR about it.
