### ISSUE TITLE
[🐛 Bug]:  Dotnet devtools session does not support WSS?

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#12950]
### What happened?

On a distributed selenium grid with separate node machines with a HTTPS Node grid url parameter (--grid-url), when trying to create a devtools session (WSS) using C# getting an error.  The same setup work fine for Java. The grid supports both http and https.

Note: when the grid is deployed with a HTTP Node grid url parameter (--grid-url) (WS) the example works fine.

### How can we reproduce the issue?

```shell
Run this example

using System.Threading.Tasks;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.DevTools;
// Replace the version to match the Chrome version
using OpenQA.Selenium.DevTools.V117.Emulation;

namespace dotnet_test {
  class Program {
    public static void Main(string[] args) {
      GeoLocation().GetAwaiter().GetResult();
    }

    public static async Task GeoLocation() {
      ChromeOptions chromeOptions = new ChromeOptions();
      RemoteWebDriver driver = new RemoteWebDriver(new Uri(https://example.com/wd/hub), chromeOptions);
      DevToolsSession devToolsSession = driver.CreateDevToolsSession();
      var geoLocationOverrideCommandSettings = new SetGeolocationOverrideCommandSettings();

      geoLocationOverrideCommandSettings.Latitude = 51.507351;
      geoLocationOverrideCommandSettings.Longitude = -0.127758;
      geoLocationOverrideCommandSettings.Accuracy = 1;

      await devToolsSession
        .GetVersionSpecificDomains<OpenQA.Selenium.DevTools.V117.DevToolsSessionDomains>()
        .Emulation
        .SetGeolocationOverride(geoLocationOverrideCommandSettings);

        driver.Url = "https://my-location.org/";
        }
    }
}
```

### Relevant log output

```shell
Message: 
OpenQA.Selenium.WebDriverException : Unexpected error creating WebSocket DevTools session.
  ----> System.Net.Http.HttpRequestException : No such host is known. (wss:80)
  ----> System.Net.Sockets.SocketException : No such host is known.

  Stack Trace: 
RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
RemoteWebDriver.GetDevToolsSession()
Tests.Test1Async() line 38
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass4_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
<16 more frames...>
DevToolsSession.InitializeProtocol(Int32 requestedProtocolVersion)
DevToolsSession.StartSession(Int32 requestedProtocolVersion)
<<GetDevToolsSession>b__0>d.MoveNext()
--- End of stack trace from previous location ---
RemoteWebDriver.GetDevToolsSession(Int32 protocolVersion)
--SocketException
AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
IValueTaskSource.GetResult(Int16 token)
Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

### Operating System

Linux, windows 10

### Selenium version

dotnet 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 117

### Are you using Selenium Grid?

4.14.1

**Comment by csgbn** [comment]
Still seeing this in 4.15.0. Is there an updated selenium grid RemoteWebDriver example available?

**Comment by nvborisenko** [comment]
It works on my end with local standalone grid. I think the issue here is that client cannot understand where connect to. It tries to use `wss:80` which is taken from capabilities by `se:cdp` name.

@diemol probably you can help here to understand what is `wss:80`.

PS: we really need logging for .net bindings.

**Comment by diemol** [comment]
@csgbn how are you launching the Grid?

**Comment by csgbn** [comment]
So, it works for Java so I do not think its something in our network environment. These are the capabilities:

Capabilities{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "118.0.5993.70",
  "chrome": {
    "chromedriverVersion": "118.0.5993.70 (e52f33f30b91b4ddfad649acddc39ab570473b86-refs/branch-heads/5993@{#1216})",
    "userDataDir": "/tmp/.org.chromium.Chromium.yhlPy1"
  },
  "fedcm:accounts": true,
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:41517"
  },
  "networkConnectionEnabled": false,
  "pageLoadStrategy": "normal",
  "platformName": "linux",
  "proxy": {},
  "se:bidi": "wss://example.com/session/7ef551353ab7396274fbd2f2ad777933/se/bidi",
  "se:cdp": "wss://example.com/session/7ef551353ab7396274fbd2f2ad777933/se/cdp",
  "se:cdpVersion": "118.0.5993.70",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webSocketUrl": "ws://localhost:16717/session/7ef551353ab7396274fbd2f2ad777933",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:extension:minPinLength": true,
  "webauthn:extension:prf": true,
  "webauthn:virtualAuthenticators": true
}

a node is assigned and the test starts and browser is launched and then it just crashes, no error in the logs on the node.

The node is started with --host <IP of the HUB VM> --grid-url https://example.com

**Comment by diemol** [comment]
Hm, if it works in Java and it also looks like the Grid is appropriately started using the `--grid-url` flag. Seems it might be something in the .NET bindings.

**Comment by nvborisenko** [comment]
@csgbn Can I ask you to repeat exception without any trimming, just copy it as is (you can mask something sensitive, but don't delete it)?

I am asking because this one, provided by you, looks strange:
```
OpenQA.Selenium.WebDriverException : Unexpected error creating WebSocket DevTools session.
  ----> System.Net.Http.HttpRequestException : No such host is known. (wss:80)
  ----> System.Net.Sockets.SocketException : No such host is known.
```

Also the following would be helpful:
- Node driver capabilities
- Your .net target framework (like .net 6)

**Comment by diemol** [comment]
>Note: when the grid is deployed with a HTTP Node grid url parameter (--grid-url) (WS) the example works fine.

Wait, in the initial description, you say that if the flag is used, the example works fine. Then, I do not understand what the issue is.

(Thanks @nvborisenko for pointing this out!)

**Comment by diemol** [comment]
Oh, the `WS` example works well, not the `WSS`

**Comment by nvborisenko** [comment]
There is no diff for us between `ws` and `wss`.

Keeping here a link https://github.com/SeleniumHQ/selenium/blob/e4d31f2dba0c131f8d3b4faeaf3ac0519187214c/dotnet/src/webdriver/DevTools/DevToolsSession.cs#L336C17-L336C17 which explains why we see `HttpRequestException`, not `WebSocketException`.

So waiting an answer from topic starter.

**Comment by csgbn** [comment]
We are using .NET 6 and visual studio 2022 and a simple test in Nunit.

Also found this ticket reference with similar problem for Ruby that was fixed, but C# error was also reported in same ticket with almost the same issue as we have, https://github.com/SeleniumHQ/selenium/issues/10017

**Comment by csgbn** [comment]
Thanks, looking forward to test this fix at the next release.

We are though seeing the same for Ruby, WSS does not work but when deploying the grid with http (WS) it works, just like for this ticket C# issue

Looking at the code https://github.com/SeleniumHQ/selenium/blob/selenium-4.15.0/rb/lib/selenium/webdriver/devtools.rb

How is WSS handled? 

We are supposed to test Python WSS next, is it supported?

**Comment by titusfortner** [comment]
Socket connection has its own class:
https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/common/websocket_connection.rb#L141

Do you have a reproducible example for ruby? Can you raise a new issue for the problem you are having?
