### ISSUE TITLE
[🐛 Bug]: Selenium Manager refuses to download chromedriver claiming to be in offline mode

### ISSUE THREAD

**Issue by leopom** [SeleniumHQ/selenium#12963]
### What happened?

Selenium manager was not able to download a proper chromedriver binary and a warning message about being in offline mode appeared

"Exception managing chrome: Unable to discover proper chromedriver version in offline mode"

The selenium manager we used is the one that is packaged with Python Selenium 4.14.0
We tried running it from within a docker container that we installed latest google-chrome on, the docker image we used is selenium/standalone-firefox:latest (yes, we used the firefox one, the chrome one is only working because it has a prepackaged chromedriver binary that can be found in the PATH)

As a workaround we downloaded the chromedriver ourselves from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/linux64/chromedriver-linux64.zip, extracted it and added its directory to PATH environment variable after doing that we still saw the warning about being in offline mode, but this time the json output had the path of the chromedriver it found in the PATH.

### How can we reproduce the issue?

```shell
Run:
/home/seluser/.local/share/virtualenvs/automation-3tbyT_2c/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager --browser chrome --debug --output json
```

### Relevant log output

```shell
{
  "logs": [
    {
      "level": "DEBUG",
      "timestamp": 1697618928,
      "message": "chromedriver not found in PATH"
    },
    {
      "level": "DEBUG",
      "timestamp": 1697618928,
      "message": "chrome detected at /opt/google/chrome/google-chrome"
    },
    {
      "level": "DEBUG",
      "timestamp": 1697618928,
      "message": "Running command: /opt/google/chrome/google-chrome --version"
    },
    {
      "level": "DEBUG",
      "timestamp": 1697618929,
      "message": "Output: \"Google Chrome 118.0.5993.88 \""
    },
    {
      "level": "DEBUG",
      "timestamp": 1697618929,
      "message": "Detected browser: chrome 118.0.5993.88"
    },
    {
      "level": "WARN",
      "timestamp": 1697618929,
      "message": "Unable to discover proper chromedriver version in offline mode"
    }
  ],
  "result": {
    "code": 0,
    "message": "",
    "driver_path": "",
    "browser_path": ""
  }
}
```

### Operating System

ubuntu 20.04 (docker image: selenium/standalone-firefox:latest)

### Selenium version

Python 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 118.0.5993.70

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.70

**Comment by diemol** [comment]
Those Docker images set an environment variable to avoid Selenium Manager being online.

https://github.com/SeleniumHQ/docker-selenium/blob/trunk/NodeBase/Dockerfile#L181
