### ISSUE TITLE
[🐛 Bug]: Chrome driver fails to start with WebDriverException : no such execution context

### ISSUE THREAD

**Issue by cdutton1** [SeleniumHQ/selenium#12967]
### What happened?

Starting chrome driver fails to start and gives the following error message
 Message: 
OpenQA.Selenium.WebDriverException : no such execution context
  (Session info: chrome=118.0.5993.72)

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
Window.Maximize()

I am using Selenium v4.14.1  & 1118v chromedriver.
With had this issue for a while now and its random can be when running 2 or 3 tests or a larger number.

### How can we reproduce the issue?

```shell
ChromeOptions options = BrowserIsChrome();
ChromeDriver webDriver = new ChromeDriver(options);
                
webDriver.Manage().Window.Maximize();                
webDriver.Manage().Timeouts().PageLoad = _pageLoadTimeOut;
webDriver.Manage().Timeouts().AsynchronousJavaScript = _asynchronousJavaScriptTimeOut;
webDriver.Manage().Timeouts().ImplicitWait = _implicitWaitTimeOut;
return webDriver;
```

### Relevant log output

```shell
Message: 
OpenQA.Selenium.WebDriverException : no such execution context
  (Session info: chrome=118.0.5993.72)

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
Window.Maximize()
```

### Operating System

Windows11

### Selenium version

C# 4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome v118

### What are the browser driver(s) and version(s) where you see this issue?

Chrome v118

### Are you using Selenium Grid?

No

**Comment by cdutton1** [comment]
```cs
public class TestBase
    {
        private static readonly List<RunningTest> ListOfRunningTests = new List<RunningTest>();

        private readonly TimeSpan _pageLoadTimeOut = TimeSpan.FromSeconds(Convert.ToInt32(ConfigurationManager.AppSettings["PageLoadTimeOut"]));
        private readonly TimeSpan _asynchronousJavaScriptTimeOut = TimeSpan.FromSeconds(Convert.ToInt32(ConfigurationManager.AppSettings["AsynchronousJavaScriptTimeOut"]));
        private readonly TimeSpan _implicitWaitTimeOut = TimeSpan.FromSeconds(Convert.ToInt32(ConfigurationManager.AppSettings["ImplicitWaitTimeOut"]));

        protected internal LoginPage LoginPage()
        {
            IWebDriver webDriver = StartDriver();
            LoginPage loginPage = new LoginPage(webDriver, ConfigurationManager.AppSettings["Url"]);
            ListOfRunningTests.Add(new RunningTest
            {
                TestContext = TestContext.CurrentContext,
                LoginPage = loginPage
            });
            return loginPage;
        }

private IWebDriver StartDriver()
        {
            if (ConfigurationManager.AppSettings["BrowserName"].Equals("chrome"))
            {
                ChromeOptions options = BrowserIsChrome();
                ChromeDriver webDriver = new ChromeDriver(options);
                
                webDriver.Manage().Window.Maximize();                
                webDriver.Manage().Timeouts().PageLoad = _pageLoadTimeOut;
                webDriver.Manage().Timeouts().AsynchronousJavaScript = _asynchronousJavaScriptTimeOut;
                webDriver.Manage().Timeouts().ImplicitWait = _implicitWaitTimeOut;
                return webDriver;
            }
       }

 private ChromeOptions BrowserIsChrome()
        {
            ChromeOptions options = new ChromeOptions();
            options.AcceptInsecureCertificates.Equals(true);
            options.BrowserVersion = ConfigurationManager.AppSettings["BrowserVersion"];

            if (ConfigurationManager.AppSettings["ChromeFlags"] != null)
            {
                IList<string> chromeArguments = ConfigurationManager.AppSettings["ChromeFlags"]
                    .Split(',')
                    .Select(arg => $"--{arg}")
                    .ToList();
                options.AddArguments(chromeArguments);
            }
            return options;
        }

}
```

**Comment by diemol** [comment]
The code has env vars and values that are not visible, what should we use instead? What is the url you are using? How can we execute the code?

**Comment by cdutton1** [comment]
Cant give you the url as not available outside of my organisation.
I will try and simplify the code so it doesn't reply on any variables not available to you and test to see it still causes the issue.

**Comment by MichalKuracina** [comment]
@cdutton1 how did you solve it? What was the issue?

**Comment by cdutton1** [comment]
I haven't really, its still happening but not as often at the moment.  I have stopped passing in any chrome options at all and that has seem to slowed the frequency of the error.

**Comment by jensakejohansson** [comment]
This issue should not be closed. There definitely seems to be a realiability issue somewhere in the implementation. I use Selenium/C# together with selenium/standalone-chrome:latest. 
The first API-call I do after the Driver/Chrome-session is started results in:

no such execution context
  (Session info: chrome=118.0.5993.70)
  
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at OpenQA.Selenium.Navigator.GoToUrl(String url)
   
It seems like the navigation actually takes place (a screenshot indicates the page was actually loaded), but the driver crashes. It seems to happen in few percent of the cases, let's say I run 100 tests 1-3 gets this issue, seemingly "random". 

So difficult to easily reproduce, for sure, but a real problem none the less.

**Comment by diemol** [comment]
This seems to be a Chrome 118 bug. Do you see that in Chrome 117?

**Comment by cdutton1** [comment]
Yeah seen it for a while as we have to be on the latest version of chrome all the time.  Tbh cant say what version we started having it.

**Comment by diemol** [comment]
What happens if you try Edge and Firefox, does it happen as well?

**Comment by cdutton1** [comment]
Apologies for closing it, just dont have the time at the moment to give a code snippet that shows how I am running selenium. Though now just starting the driver and I send a command to maximise the browser and before it can send that command it goes.  So nothing to do with url i am passing in or the chrome options, as got rid of them now. 
So quickly
IWebDriver webDriver = StartDriver();
private IWebDriver StartDriver()
        {
                ChromeDriver webDriver = new ChromeDriver();//Fails here!!!
                
                webDriver.Manage().Window.Maximize();                
                webDriver.Manage().Timeouts().PageLoad = _pageLoadTimeOut;
                webDriver.Manage().Timeouts().AsynchronousJavaScript = _asynchronousJavaScriptTimeOut;
                webDriver.Manage().Timeouts().ImplicitWait = _implicitWaitTimeOut;
                return webDriver;
            }

When the an instant of the driver is created this is where it fails!

**Comment by cdutton1** [comment]
> What happens if you try Edge and Firefox, does it happen as well?

Tbh with hardly run on these. But at some point I can try.

**Comment by jensakejohansson** [comment]
Nor do I do anything 'special'. Yes, I throw in some options, like:

chromeOptions.AddArguments("--lang=" + Context.FWCfg.Locale.Name);
chromeOptions.AddArguments("chrome.switches", "--disable-extensions");
chromeOptions.AddArguments("disable-popup-blocking");
chromeOptions.AddUserProfilePreference("autofill.profile_enabled", false);
chromeOptions.AddUserProfilePreference("credentials_enable_service", false);
chromeOptions.AddUserProfilePreference("profile.password_manager_enabled", false);
chromeOptions.AddArguments("disable-notifications");
chromeOptions.AddArguments("ignore-certificate-errors");
chromeOptions.AddArguments("--disable-dev-shm-usage");

Maybe somthing more, depending on different runtime configurations, then the code starts a RemoteWebDriver instance that connects to the selenium-docker container. Then the next WebDriver action fails....

We normally only run Chrome, could of try to run Edge maybe. If we run against this old(!) version:
selenium/standalone-chrome:4.1.0-20211123 it is stable (not checked myself, but according to our QA people).

**Comment by diemol** [comment]
I do suspect a Chrome bug and the easiest way to check is by running the test in a different browser.

**Comment by MichalKuracina** [comment]
When did it start to happen? Me 13th Oct

**Comment by PatrickJordanCongenica** [comment]
For what it's worth, we have started encountering this after upgrading our tests to start using the [Chrome for Testing versions](https://googlechromelabs.github.io/chrome-for-testing/) (away from [this older URL](https://chromedriver.storage.googleapis.com/LATEST_RELEASE)). We're using the following versions:

- Chrome: `118.0.5993.70`
- Python: `3.11.5`
- Selenium: `4.14.0`

Of ~580 tests, it happened 3 times, so it's an intermittent issue or race condition that's hard to reproduce. I can see [others are reporting this issue](https://groups.google.com/g/chromedriver-users/c/rDR5RA0SLdA?pli=1) as well.

Our tests are configured to setup and teardown identically, so the 3 times it did happen was the very first use of any method in the `WebDriver` class. In our case, this was when we used the following method:

```
driver.get(<internal_url>)
```

For transparency, these are the configuration options we're using when running our tests:

```python
chrome_options.add_experimental_option(
    "prefs",
    {
        "intl.accept_languages": "en-GB",
        "credentials_enable_service": False,
        "download.default_directory": self.downloads_root.as_posix(),
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "profile.password_manager_enabled": False,
        "plugins.always_open_pdf_externally": True,
    },
)

chrome_options.page_load_strategy = "normal"
chrome_options.add_argument("--start-maximized")
chrome_options.add_argument(f"--window-size=1920,1080")
chrome_options.add_argument("--disable-browser-side-navigation")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-setuid-sandbox")
chrome_options.add_argument("--dns-prefetch-disable")
chrome_options.add_argument("--force-device-scale-factor=1")
chrome_options.add_argument("--no-sandbox")

chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option("useAutomationExtension", False)

if self.run_headless:
    chrome_options.add_argument("--headless=new")
```

**Comment by diemol** [comment]
That could be used to report this issue to Google, I will leave the link below.
