### ISSUE TITLE
[🐛 Bug]: Both get_attribute("value") and get_property("value") return a fake filepath for file-upload inputs

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#12961]
### What happened?

Using Selenium for Python

I am manipulating this file-upload input element:

`<input class="form-control" type="file" name="my-file">`

I set its value via send_keys method (ex: `/home/user/.profile` using Linux)

I print the value property of the webelement:
```
print(element.get_attribute("value"))
print(element.get_property("value"))
```

Actual result :
`C:\fakepath\.profile`

Expected result:
`/home/user/.profile`

### How can we reproduce the issue?

```shell
element = driver.find_element(by, value)
element.send_keys("/home/user/.profile")
print(element.get_attribute("value"))
print(element.get_property("value"))
```

### Relevant log output

```shell
none
```

### Operating System

Linux

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

Firefox, Chrome

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.33.0 chromedriver 117

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
https://stackoverflow.com/a/4851614
