### ISSUE TITLE
[🐛 Bug]: PrintOptions default for pageSize appear incorrect

### ISSUE THREAD

**Issue by bratwurzt** [SeleniumHQ/selenium#12969]
### What happened?

In selenium-api in java/src/org/openqa/selenium/print/PageSize.java there is the default:
this.height = 27.94;
this.width = 21.59;

But googling the A4 size gives:
this.height = 29.70;
this.width = 21.00;

Is this intentional?

### How can we reproduce the issue?

```shell
/
```

### Relevant log output

```shell
/
```

### Operating System

ubuntu

### Selenium version

selenium-4.14.1

### What are the browser(s) and version(s) where you see this issue?

Selenium sets the versions with manager

### What are the browser driver(s) and version(s) where you see this issue?

Selenium sets the versions with manager

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
Hey! Selenium follows standards defined in https://www.w3.org/TR/webdriver2/#print-page. We are adhering to the default values mentioned in the spec that is implemented by all major browsers for automation.

> Let pageWidth be the result of [getting a property with default](https://www.w3.org/TR/webdriver2/#dfn-getting-the-property-with-default) named width and with a default of 21.59 from page.
> 
> Let pageHeight be the result of [getting a property with default](https://www.w3.org/TR/webdriver2/#dfn-getting-the-property-with-default) named height and with a default of 27.94 from page.

**Comment by bratwurzt** [comment]
@pujagani thank you!
