### ISSUE TITLE
[🐛 Bug]: Cannot set SlotMatcher on Node

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/selenium#12964]
### What happened?

Hello

Following PR https://github.com/SeleniumHQ/selenium/pull/12240 (make user defined SlotMatcher available for both distributor and node), the node option for setting a SlotMatcher is not available whereas NodeOptions class tries to read it

https://github.com/SeleniumHQ/selenium/blob/b008e15cfb21559c360175bd66ae8cdfbf40b9dc/java/src/org/openqa/selenium/grid/node/config/NodeOptions.java#L177-L179

The only way to set it is to provide it through a TOML file but documentation does not mention it

@diemol : I saw you removed the options just before merging: https://github.com/SeleniumHQ/selenium/pull/12240/commits/4fcb806b26103a7a07df7501c7de65315e561a46. 
Maybe it was not a good idea 😄 

Or documentation should be updated, but I think that in this state `--slot-matcher` may be useless because of inconsistency between distributor and node behaviour when testing if capabilities match

### How can we reproduce the issue?

```shell
Start a node with --slot-matcher option
```

### Relevant log output

```shell
Was passed main parameter '--slot-matcher' but no main parameter was defined in your arg class
```

### Operating System

Windows / Linux

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

not related to browser

### What are the browser driver(s) and version(s) where you see this issue?

not related to browser

### Are you using Selenium Grid?

4.14.0

**Comment by diemol** [comment]
Documentation should be updated. Having the same flag in two different places does not make sense.

**Comment by bhecquet** [comment]
Hello @diemol , I agree with you, but, configuring the same feature in 2 differents ways may not be the best option
Anyway, choose your way 😃

**Comment by diemol** [comment]
The Distributor and the Node need to know what will be used to match slots.

How would you do it?

**Comment by bhecquet** [comment]
I see 3 options (there may be others)
- leave it as it => not a good option as it forces to create a toml file for the node
- put the same option in the node => As you said, not a good option to have the same flag in 2 components
- create an other "section" (e.g: "matcher") with this option inside, that would apply to both node and distributor

**Comment by diemol** [comment]
You are right, I missed this and I needed a few minutes to understand better what was missing. The ideal solution was to bring the flag to the Node as well, under the `distributor` section. Like that we avoid duplicates.

**Comment by diemol** [comment]
Reverted the fix as it broke the Standalone role.
