### ISSUE TITLE
[🐛 Bug]: Is the Chromedriver download link incorrect?

### ISSUE THREAD

**Issue by Mo0rBy** [SeleniumHQ/selenium#12971]
### What happened?

I'm coming here from the Serenity Github. Serenity uses Selenium as a dependency and does all of it's webdriver management through it. You can see my original issue on the Serenity Github [here](https://github.com/serenity-bdd/serenity-core/issues/3292).

The basics of the issue that I am getting timeout error when I am attempting to get the Chrome webdriver. In my terminal, here is the WARNING:
```
WARNING: There was an error managing chrome (error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/mac-arm64/chromedriver-mac-arm64.zip): error trying to connect: tcp connect error: Operation timed out (os error 60)); using driver found in the cache
```

Looks closely at the download URL. It ends with `...../118.0.5993.70/mac-arm64/chromedriver-mac-arm64.zip` (it says "chromedriver-mac")

And the URL on the Chrome for Testing dashboard ends with: `......./118.0.5993.70/mac-arm64/chrome-mac-arm64.zip` (it says "chrome-mac")

Here is a screenshot as some proof:
<img width="1587" alt="Screenshot 2023-10-19 at 15 55 42" src="https://github.com/SeleniumHQ/selenium/assets/88185573/c470ff5e-59cc-41e9-adee-dd72fc26f7b7">

### How can we reproduce the issue?

wakaleo (John Ferguson Smart) the creator of Serenity says that they use the latest version of Selenium so all you need to do is attempt to run some FE tests using Selenium.

### Relevant log output
This is my Serenity output:

```shell
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider - Starting Chrome driver instance with capabilities:
[main] INFO net.serenitybdd.core.webdriver.driverproviders.ChromeDriverProvider - Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 118, goog:chromeOptions: {args: [no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, remote-allow-origins=*], extensions: []}, pageLoadStrategy: normal, timeouts: {implicit: 5000, pageLoad: 5000, script: 5000}}
Oct 19, 2023 3:51:12 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
WARNING: There was an error managing chrome (error sending request for url (https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.70/mac-arm64/chromedriver-mac-arm64.zip): error trying to connect: tcp connect error: Operation timed out (os error 60)); using driver found in the cache
.............
feature:8)
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: WebDriver was unable to create a new instance of type class org.openqa.selenium.chrome.ChromeDriver
WebDriver reported the following message: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 118.0.5993.88 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'UK-FVFHR0LNQ6LW', ip: '172.21.17.21'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.6', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, remote-allow-origins=*], binary: /Applications/Google Chrome..., extensions: []}, pageLoadStrategy: normal, timeouts: {implicit: 5000, pageLoad: 5000, script: 5000}}]}]
See below for more details.
.............
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 118.0.5993.88 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
Host info: host: 'UK-FVFHR0LNQ6LW', ip: '172.21.17.21'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.6', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, no-sandbox, ignore-certificate-errors, --window-size=1920,1080, incognito, remote-allow-origins=*], binary: /Applications/Google Chrome..., extensions: []}, pageLoadStrategy: normal, timeouts: {implicit: 5000, pageLoad: 5000, script: 5000}}]}]
```

### Operating System

macOS Ventura 13.6

### Selenium version

Java 4.14

### What are the browser(s) and version(s) where you see this issue?

Chrome 118 (but I'm trying to work with any version above 115)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118, 117, 116

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Selenium downloads both the driver and the browser as necessary, so both chromedriver and chrome.

You need to see if there are network issues preventing the internet connection:
https://www.selenium.dev/documentation/selenium_manager/#connectivity-issues

**Comment by Mo0rBy** [comment]
I've looked already and the found that the download URL stated in my terminal and the actual download URL on the Chrome for Testing dashboard are different. 

From my original post:

-----
Looks closely at the download URL. It ends with `...../118.0.5993.70/mac-arm64/chromedriver-mac-arm64.zip` (it says "chromedriver-mac")

And the URL on the Chrome for Testing dashboard ends with: `......./118.0.5993.70/mac-arm64/chrome-mac-arm64.zip` (it says "chrome-mac")

-----
I don't have any network issues where my machine is unable to download from the Chrome for Testing dashboard.

**Comment by Mo0rBy** [comment]
I've tried again now and the Chromedriver downloads and runs successfully, but I'm getting a different error now. I think it is to do with permissions with the Chrome for Testing Chrome binary, so not related to this.

Maybe I just caught Google out in the middle of a change and the JSON used to list all the download links was different to the actual download links.
