### ISSUE TITLE
[🚀 Feature]: Java: let me configure SeleniumManager on creating Driver Object

### ISSUE THREAD

**Issue by RaHehl** [SeleniumHQ/selenium#12970]
### Feature and motivation

Hello,

According to #12793 #11687 #12914 I want to configure SeleniumManager via the driver constructors.

As far as I currently know, I need to create a configuration file or set an environment variable to configure Selenium Manager https://www.selenium.dev/documentation/selenium_manager/

I would like to configure it via code, like in my "Usage example"

I wanted to create a PR for this, but I haven't managed to get my Intelij running with Bazel on my Windows developer client.

### Usage example
```java
ChromeOptions chromeOptions = new ChromeOptions();
List<String> managerArguments = new ArrayList<>();
managerArguments.add("--driver-mirror-url");
managerArguments.add("https://MyDriverMirror");
managerArguments.add("--browser-mirror-url");
managerArguments.add("https://myBrowserMirror");
WebDriver driver = new ChromeDriver(chromeOptions, managerArguments);
```

**Comment by titusfortner** [comment]
I do not want to add new constructors.

We have options for making adjustments in the code, but I think the right way for these system level issues is to make use of the configuration file.

**Comment by RaHehl** [comment]
ok, what about a config singleton as an alternative? In my usecase, file is also ugly, 

As I understand it, the Selenium Manager was actually intended not to have to deal with client-specific configs again

**Comment by titusfortner** [comment]
We want to make it so you don't have to rely on additional libraries, and we want to make it easy to get the right browser/driver combination. The more edge cases we bake in the more complicated the code, the harder it is to maintain it. 

There is something we might do code-wise, but only if it makes it easier to maintain, not harder, and we're still discussing it.

The answer right now is either a config file or environment variables.

**Comment by RaHehl** [comment]
That was my approach, which I originally wanted to do as a PR. I don't think this is that complex. But of course I understand that people are a bit cautious when it comes to changing the constructors.

![image](https://github.com/SeleniumHQ/selenium/assets/7577984/90673a15-5c18-4591-b788-c4b759ad62ab)

**Comment by titusfortner** [comment]
You proposed a new constructor for the driver to take advantage of this, though, which means you end up needing to add the parameter as an option for all the current driver constructors for all the drivers which is prohibitive.

**Comment by titusfortner** [comment]
We aren't going to do this, but if we implement #13022 it address your needs.
