### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally. (chrome not reachable) (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

### ISSUE THREAD

**Issue by saif8983ansari** [SeleniumHQ/selenium#12973]
### What happened?

when I try to open a html file using headless chrome. this issue comes intermittently. I am using selenium 4.13 and webdriver manager 5.5.3

### How can we reproduce the issue?

```shell
I dont have exact steps to reproduce as I said this issue is intermittent.
my code snippet:-
WebDriverManager.chromedriver().clearDriverCache().setup();
	WebDriver driver = new ChromeDriver(options);
	String screenshotFilePath;
	Dimension currentDimension = driver.manage().window().getSize();
	int defaultHeight = currentDimension.getHeight();
	int defaultWidth = currentDimension.getWidth();
	
		logger.info("default driver size "+defaultWidth+" * "+defaultHeight);

		driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
		driver.get("file://"+htmlFilePath+".html");
```

### Relevant log output

```shell
stack_trace
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
(chrome not reachable)
(The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: '1511da2b56a5', ip: '172.17.0.5'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.322-246.539.amzn2.x86_64', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=new, --disable-dev-shm-usage, --remote-debugging-port=9222, --user-data-dir=/home/sassr..., --ignore-certificate-errors, --silent, --no-sandbox], binary: /usr/bin/google-chrome-stable, extensions: []}}]}]
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:163)
at org.openqa.selenium.chromium.ChromiumDriver.(ChromiumDriver.java:108)
... 5 frames truncated
... 2 common frames omitted
Wrapped by: java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
(chrome not reachable)
(The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Host info: host: '1511da2b56a5', ip: '172.17.0.5'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.322-246.539.amzn2.x86_64', java.version: '17.0.8.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless=new, --disable-dev-shm-usage, --remote-debugging-port=9222, --user-data-dir=/home/sassr..., --ignore-certificate-errors, --silent, --no-sandbox], binary: /usr/bin/google-chrome-stable, extensions: []}}]}]
```

### Operating System

amazon linux 2

### Selenium version

4.13

### What are the browser(s) and version(s) where you see this issue?

chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

webdrivermanager 5.5.3

**Comment by titusfortner** [comment]
turn on logging and see what the output is - https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

Also, we recommend not using WebDriverManager at this point as well since Selenium handles it all for you now.

**Comment by satya081** [comment]
I am also facing same error.

**Comment by titusfortner** [comment]
Need a reproducible example or log output.

**Comment by AlexParan** [comment]
Hi all,

I am new to GitHub and trying to get around it, but I am facing the same issue as peeps above.
I am trying to code a automatic app for my work to create tickets automatically but can't access the snow link as chrome is crashing.
ChromeOptions options = new ChromeOptions();
options.AddExcludedArgument("ignore-certifcate-errors");
options.AddArgument("disable-infobars");
var driverService = ChromeDriverService.CreateDefaultService();
driverService.HideCommandPromptWindow = true;
var driver = new ChromeDriver(driverService, options); // it crashes here states that it thinks that chrome has crashed and it doesn't create the session 
           
driver.Manage().Window.Maximize();
driver.Navigate().GoToUrl(snow);
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);


Any advice?

**Comment by AlexParan** [comment]
This is the exact error I get : 

[11:01 AM] Paranosic, Aleksa
System.InvalidOperationException: 'session not created: Chrome failed to start: exited normally.

  (session not created: DevToolsActivePort file doesn't exist)

  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)'

**Comment by titusfortner** [comment]
`DevToolsActivePort` is a different issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35

**Comment by AlexParan** [comment]
that doesn't resolve my issue, it just times out

**Comment by titusfortner** [comment]
Unfortunately, it is still a Chromedriver issue and there's nothing we can do about it in this code base.
