### ISSUE TITLE
[🐛 Bug]: When trying to run scripts under vpn, Selenium manager requires proxy to be set for it to download the necessary drivers through capabilities. But after setting Proxy also ,I am getting Proxy authentication required.

### ISSUE THREAD

**Issue by SripriyaPKulkarni** [SeleniumHQ/selenium#12983]
### What happened?

Below is the code which I have used once i got the proxy authentication required error even though I have set Proxy.

ChromeOptions chromeOptions = new ChromeOptions();

Proxy proxy = new Proxy();
proxy.setHttpProxy("http_proxy-url:port"); 
proxy.setSslProxy("https_proxy-url:port");
proxy.setNoProxy("no_proxy-var");

chromeOptions.setCapability("proxy", proxy); 
driver = new ChromeDriver(chromeOptions);

### How can we reproduce the issue?

```shell
Code Used:
ChromeOptions chromeOptions = new ChromeOptions();

Proxy proxy = new Proxy();
proxy.setHttpProxy("http_proxy-url:port"); 
proxy.setSslProxy("https_proxy-url:port");
proxy.setNoProxy("no_proxy-var");

chromeOptions.setCapability("proxy", proxy); 
driver = new ChromeDriver(chromeOptions);


Operating System
Windows 10

Selenium version
4.11.0

What are the browser driver(s) and version(s) where you see this issue?
Chromedriver 118
```

### Relevant log output

```shell
Relevant log output
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, browserVersion: 118, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-dev-shm-usage, --no-sandbox], extensions: []}}, error Command failed with code: 65, executed: [<path>\selenium-manager2136117563690013775312814197890619\selenium-manager.exe, --browser, chrome, --output, json, --browser-version, 118]
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '8'
```

### Operating System

Windows 10

### Selenium version

4.11

### What are the browser(s) and version(s) where you see this issue?

Chrome 118 and 117

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Check https://www.selenium.dev/documentation/selenium_manager/#configuration, you can use the `SE_PROXY=PROXY` environment variable for authentication. If you have more questions, please head to our Slack channel, links below.

**Comment by titusfortner** [comment]
Update to latest version of Selenium. We may not have implemented proxy yet in 4.11

**Comment by SripriyaPKulkarni** [comment]
I have tried updating also but still the same issue

**Comment by titusfortner** [comment]
If you are passing in a proxy to the options class, you should be seeing proxy information in the logs here:
```
Unable to obtain: Capabilities {browserName: chrome, browserVersion: 118, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-dev-shm-usage, --no-sandbox], extensions: []}}
```
