### ISSUE TITLE
[🐛 Bug]: Using Firefox profile path argument on Remote setup prevents driver from being created

### ISSUE THREAD

**Issue by dvorst** [SeleniumHQ/selenium#12984]
### What happened?

Run standalone Firefox in Docker
``` BASH
docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-firefox
```

Start/stop driver
``` PYTHON
from selenium import webdriver

docker_url = "http://localhost:4444/wd/hub"
profile_path = '/home/seluser/'

options = webdriver.FirefoxOptions()
options.add_argument(f'-P "{profile_path}"')
driver = webdriver.Remote(
    command_executor=docker_url,
    options=options
)

driver.quit()
```

Visit [http://localhost:7900/](http://localhost:7900/) with password `secret`

You should be able to see that the browser opened, but is never shut down, the python script will remain stuck at creating the driver. When omitting the `options.add_argument` line from the Python code, the browser will start & close as expected.

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

docker image "selenium/standalone-firefox:118.0"

### What are the browser driver(s) and version(s) where you see this issue?

docker image "selenium/standalone-firefox:118.0"

### Are you using Selenium Grid?

Don't know

**Comment by titusfortner** [comment]
The driver receives that argument and looks for the profile at that location on the local machine. You have to use the profile property on the options class to specify a pre-existing profile on remote. (though I've had some issues with it based on size of the zip, either way).

**Comment by dvorst** [comment]
So the profile path is not added as an argument to the Firefox command on the remote machine?

Setting the profile of the options class results in an error on the host machine (not the remote machine):
``` PYTHON
options.profile = profile_path
```
``` BASH
[WinError 3] The system cannot find the path specified: '/home/seluser/rust_mozprofilevwEwCA'
```

Is there a guide somewhere that explains how to do this?

EDIT: I realized that the profile has to be located on the host machine, not on the remote machine. The code below works, i guess the issue can thus be considered closed.
``` PYTHON
from selenium import webdriver

docker_url = "http://localhost:4444/wd/hub"
profile = webdriver.FirefoxProfile(profile_directory='profiles/blank-profile')
options = webdriver.FirefoxOptions()
options.profile = profile
driver = webdriver.Remote(
    command_executor=docker_url,
    options=options
)

driver.quit()
```

**Comment by titusfortner** [comment]
My explanation there wasn't the greatest. I knew what I meant in my mind it just didn't come out on the page super well. 😁
