### ISSUE TITLE
Jenkins Selenium Grid Plugin::Couldn't register this node: The hub is down or not responding

### ISSUE THREAD

**Issue by skmvali** [SeleniumHQ/selenium#1301]
Hi,

When I configure grid hub, node in the same machine, everythings looks fine. But when i try to register to Machine-A where hub is running from Machine-B where i need to configure node to the Machine-A hud..I am getting below error..please help me on this

21:22:13.982 INFO - Couldn't register this node: The hub is down or not respondi
ng: Connect to 10.76.176.120:4444 [/10.76.176.121] failed: Connection timed out: con
nect

Thanks
Sunny

**Comment by skmvali** [comment]
Steps to Reproduce:

1. Installed Selenium grid Plug-in Jenkins on Machine A
2. By default automatically hub will be started and running on Port #4444 when we start jenkins
3. Start the node from a diff machcine B to register the Hub[Jenkins HUB] running on Machine A.

**Comment by lukeis** [comment]
We don't maintain the Jenkins plugin here. You'll need to log a bug with them.
