### ISSUE TITLE
[🚀 Feature]: Release Selenium Manager with Bazel

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13019]
### Feature and motivation

Right now bazel is built and released with Cargo. It would be much better for our build if what is built by bazel matches exactly for that architecture what is built for release. This may not be possible since I'm not sure bazel supports doing different things depending on architecture, which means it would actually require cross-compilation that we've determined we can't do. Would be nice to document this either way.

### Usage example

```
cargo build --release
```
should do the same thing as
```
bazel build //rust:selenium-manager
```

**Comment by diemol** [comment]
Didn't @shs96c try this and could not do it due to the cross-compile issues?

**Comment by titusfortner** [comment]
I wasn't sure if it was an absolute impossibility or a roadblock that was more trouble than it was worth that day. Either way I want to have documented what doesn't work. :)

**Comment by titusfortner** [comment]
I'm going to close this one. It seems like if we can't cross-compile, the current solution is good enough, and we are probably more likely to re-implement SM in Go than to improve this.
