### ISSUE TITLE
[🚀 Feature]: Make Selenium Manager classes thin wrappers

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13022]
### Status
* Java — #13385 
* Ruby — #13386 
* .NET — #13833
* Python — #13387
* JS — #13853

### Feature and motivation

Make Selenium Manager class only responsible for locating the correct binary, and executing that binary with the provided arguments.

The DriverFinder class parses any options and service class details required and sends them to Selenium Manager.

This allows:
* better separation of concerns between DriverFinder and Selenium Manager (see https://github.com/SeleniumHQ/selenium/pull/12554)
* creating a Server class to get the grid with Selenium Manager (see https://github.com/SeleniumHQ/selenium/pull/12299)
* [releasing SM as a separate package](https://github.com/SeleniumHQ/selenium/issues/13021) (would be an alternative to https://github.com/SeleniumHQ/selenium/issues/11694, and would provide support for projects to use [older versions of Selenium](https://github.com/titusfortner/webdrivers/#update-future-of-this-project).

**Comment by diemol** [comment]
Do you mean having something like `DriverService` but for SM?

**Comment by titusfortner** [comment]
Yes, I guess it's essentially that.

**Comment by diemol** [comment]
Implemented in all bindings.
