### ISSUE TITLE
[🚀 Feature]: Stop storing Selenium Manager in Repo

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13020]
### Feature and motivation

Can we run `build-selenium-manager.yml` and then use bazel to download those assets from GitHub to use in testing/releasing rather than storing the files in the repo?

This wouldn't be necessary if we could cross compile, and might make for a workable alternative to #13019

### Usage example

https://www.stevenengelhardt.com/2023/05/23/practical-bazel-downloading-private-release-assets-from-github/

**Comment by diemol** [comment]
This is what I have been suggesting for a long time.

**Comment by titusfortner** [comment]
Yup, just trying to document all the things.

**Comment by titusfortner** [comment]
Oh brother, I opened my own duplicate. I'm leaving that one open (#13150) and closing this one.
