### ISSUE TITLE
selenium-webdriver 2.48.2 cannot set webStorageEnabled for phantomjs

### ISSUE THREAD

**Issue by wlmzfx** [SeleniumHQ/selenium#1302]
selenium-webdriver: 2.48.2
phantomjs: 1.9.18

This is the code I am using:
	
     var driver = new webdriver.Builder()
		.withCapabilities({webStorageEnabled: true, proxy: {type:'system'}})
		.forBrowser('phantomjs')
		.build();
	driver.getCapabilities().then(function(caps){
		console.log('meeeeee: ', caps);
	});

It prints: 

meeeeee:  { caps_: 
   { browserName: 'phantomjs',
     version: '1.9.8',
     driverName: 'ghostdriver',
     driverVersion: '1.1.0',
     platform: 'linux-unknown-32bit',
     javascriptEnabled: true,
     takesScreenshot: true,
     handlesAlerts: false,
     databaseEnabled: false,
     locationContextEnabled: false,
     applicationCacheEnabled: false,
     browserConnectionEnabled: false,
     cssSelectorsEnabled: true,
     webStorageEnabled: false,
     rotatable: false,
     acceptSslCerts: false,
     nativeEvents: true,
     proxy: { type: 'system' } } }

And the phantomjsdriver.log file says:

5-11-22T07:31:40.341Z] GhostDriver - Main - running on port 34767
[INFO  - 2015-11-22T07:31:40.402Z] Session [1254f4a0-90eb-11e5-bfc0-8fc80e582c68] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2015-11-22T07:31:40.402Z] Session [1254f4a0-90eb-11e5-bfc0-8fc80e582c68] - page.customHeaders:  - {}
[INFO  - 2015-11-22T07:31:40.402Z] Session [1254f4a0-90eb-11e5-bfc0-8fc80e582c68] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"type":"system"}}
[INFO  - 2015-11-22T07:31:40.402Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 1254f4a0-90eb-11e5-bfc0-8fc80e582c68

I should be setting the capabilities correctly by using withCapabilities({webStorageEnabled: true})
but it is not working at all.

Is this a bug? or I am using it wrong?

------------------------
But chromedriver can set webStorageEnabled=true by default, is this because that phantomjs does not support webstorage?

**Comment by jleyba** [comment]
webStorageEnabled is a readonly capability. The driver sets it to true if the corresponding WebDriver APIs are supported. Those APIs, by the way, are not available in the JS client. Just access storage using `executeScript`:

```
driver.executeScript('return localStorage.getItem(arguments[0])', 'storageKey')
    .then((value) => console.log('storageKey = ' + value));
```

**Comment by wlmzfx** [comment]
Thanks!
Seems that phantomjs webdriver does not support webStorage.
