### ISSUE TITLE
[🚀 Feature]: Make selenium manager be offline

### ISSUE THREAD

**Issue by Zubastic** [SeleniumHQ/selenium#13029]
### Feature and motivation

I use selenium in intranet without access to internet. But selenium manager wants to access to url for checking updates (I dont need it). I could add enviroment variable, but I want to do this directly with code.

### Usage example

1) Add option to add args directly for selenium manager (now it applyes only proxy and browser methods)
2) Add option equaling '--offline' option

**Comment by titusfortner** [comment]
If you don't have internet access, you need drivers already installed. If you have drivers already installed and referenced, selenium manager won't try to download anything.

**Comment by diemol** [comment]
It still connects to the internet even if you have the drivers and browsers configured because it checks if a better driver version exists for the available browser. @bonigarcia can clarify. 

@Zubastic, however, we will not add that option to the bindings because we are evaluating if the flag is needed per se or if the behavior should happen depending on the binaries available on PATH. Therefore, if you need this, you must set the environment variable.

**Comment by titusfortner** [comment]
Bindings should be kept completely backwards compatible if users have valid driver in path. Which means no internet calls.

**Comment by titusfortner** [comment]
Compatibility should be judged based on browser located not what is found online

**Comment by Zubastic** [comment]
> If you don't have internet access, you need drivers already installed. If you have drivers already installed and referenced, selenium manager won't try to download anything.

But it did it :) I had msedgedriver.exe in folder with binary and selenium manager executed instead of use default driver.

> It still connects to the internet even if you have the drivers and browsers configured because it checks if a better driver version exists for the available browser. @bonigarcia can clarify.

How to disable this feature? I have standalone installation and don't need to check version of driver/browser/network connection.

> @Zubastic, however, we will not add that option to the bindings because we are evaluating if the flag is needed per se or if the behavior should happen depending on the binaries available on PATH. Therefore, if you need this, you must set the environment variable.

But I want to distribute app to another users and modify PATH at all computers is pain. Also problem that modifying PATH u change behavior for all selenium based software.

Here example:
```c#
    public static string DriverPath(DriverOptions options)
    {
      StringBuilder stringBuilder = new StringBuilder();
      stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " --browser \"{0}\"", (object) options.BrowserName);
      stringBuilder.Append(" --output json");
      if (!string.IsNullOrEmpty(options.BrowserVersion))
        stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " --browser-version {0}", (object) options.BrowserVersion);
      string binaryLocation = options.BinaryLocation;
      if (!string.IsNullOrEmpty(binaryLocation))
        stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " --browser-path \"{0}\"", (object) binaryLocation);
      if (options.Proxy != null)
      {
        if (options.Proxy.SslProxy != null)
          stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " --proxy \"{0}\"", (object) options.Proxy.SslProxy);
        else if (options.Proxy.HttpProxy != null)
          stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " --proxy \"{0}\"", (object) options.Proxy.HttpProxy);
      }
      Dictionary<string, object> dictionary = SeleniumManager.RunCommand(SeleniumManager.BinaryFullPath, stringBuilder.ToString());
      string str1 = (string) dictionary["browser_path"];
      string str2 = (string) dictionary["driver_path"];
      try
      {
        options.BinaryLocation = str1;
        options.BrowserVersion = (string) null;
      }
      catch (NotImplementedException ex)
      {
      }
      return str2;
    }
```

and here from selenium-manager docs https://www.selenium.dev/documentation/selenium_manager/#configuration :
![img](https://klikr.org/ac770c214d46c4ac012591b863e9.png)

5 params in selenium vs 17 in selenium-manager.

**Comment by diemol** [comment]
>How to disable this feature? I have standalone installation and don't need to check version of driver/browser/network connection.

Use the environment variable.

>But I want to distribute app to another users and modify PATH at all computers is pain. Also problem that modifying PATH u change behavior for all selenium based software.

So you do not want to let SM access the internet but you do not want to set the drivers on your own? How would this work?

**Comment by Zubastic** [comment]
> So you do not want to let SM access the internet but you do not want to set the drivers on your own? How would this work?

SM has different settings (not about offline): such as debug, trace, cache-path etc. And all of them apply only to environment variable.

**Comment by diemol** [comment]
I am not following, sorry. I do not understand how your comment answers my question.

The bottom line is that SM is in beta, which allows us to experiment and try different directions before we commit to support the different features and flags available. The only way to do what you want is through environment variables. We still have pending a conversation to define which flags we will keep and which ones we will remove.

**Comment by titusfortner** [comment]
If you want to entirely avoid Selenium Manager using code, you can set the location of the driver in the Service class. Selenium will completely skip Selenium Manager class.

**Comment by diemol** [comment]
I will close this as there are two different ways to have Selenium Manager offline, either by setting the driver path or setting the environment variable.
