### ISSUE TITLE
[🐛 Bug]: Webdriver not working on Selenium 4.14 but working on 3.8

### ISSUE THREAD

**Issue by lucamcwood** [SeleniumHQ/selenium#13038]
### What happened?

Hello,
I was trying to test Selenium 4.14 by simply opening a page in Chrome and I always get a 10054 error. I tried to install a more recent version of drivers, tried switching to other browsers, tied changing the path and also the proxy, but nothing worked.
The only solution that made the issue go away was to uninstall the 4.14 version and install the old 3.8.
I am using Python 3.11.

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Chrome()
```

### Relevant log output

```shell
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host


urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

### Operating System

10

### Selenium version

Python selenium-4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome, Firefox, IE, Edge

### What are the browser driver(s) and version(s) where you see this issue?

All versions I tried

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Adjust the log output and please share the result https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by xpcosmos** [comment]
I might be facing the same problem. My Chrome version is 118.0.5993.117, and less than 2 weeks ago, the code was running normally. Today, I tried to run the code:

```
driver = webdriver.Chrome()
```

But the code runs infinitely. I don't know if our problems are somehow related, but I would like to know if you are experiencing the same issue as me.

**Comment by diemol** [comment]
I will close this as we did not get more information from the OP. We can reopen it in case more information is provided.
