### ISSUE TITLE
An options in a drop-down can't be click although they are clickable.

### ISSUE THREAD

**Issue by zyovcheva-rms** [SeleniumHQ/selenium#1303]
I try to perform these two test steps with Selenium Chromedriver (2.15.322488) and Mozilla Webdriver (Selenium 2.48.2) 
1/Click on a dropdown
2/Click on an option from this dropdown

I click on a dropdown (a WebElement "methodOfTestStep") but can't click on some option in it (WebElement e).
The error message is not available. The test is passed though the option is not selected.
The dropdown and the options in the dropdown are not defined as 'select' and 'options' tags. The part of html is posted below:

 ```html
<div class="button tertiary dropdown-trigger" data-reactid=".0.1.1.0.0.2.0.0.0.2.7.0.0.0.1.0" data-asf-instance-name="Button" data-asf-component="com.RMS.Button@0.1.0">
<ul class="dropdown" data-reactid=".0.1.1.0.0.2.0.0.0.2.7.0.0.0.1.1">
<li class="dropdown-item" data-reactid=".0.1.1.0.0.2.0.0.0.2.7.0.0.0.1.1.0" data-asf-instance-name="DropdownItem" data-asf-component="com.RMS.Dropdown.DropdownItem@0.1.0">
<li class="dropdown-item" data-reactid=".0.1.1.0.0.2.0.0.0.2.7.0.0.0.1.1.$POST" data-asf-instance-name="DropdownItem" data-asf-component="com.RMS.Dropdown.DropdownItem@0.1.0">
<li class="dropdown-item" data-reactid=".0.1.1.0.0.2.0.0.0.2.7.0.0.0.1.1.$GET" data-asf-instance-name="DropdownItem" data-asf-component="com.RMS.Dropdown.DropdownItem@0.1.0">...
```

And here is a part of my testing code:

```java
methodOfTestStep.click();
List<WebElement> li = driver.findElements(By.cssSelector("div.dropdown-wrapper.full-width.test-step-method>div.button.tertiary.dropdown-trigger+ul"));

for (WebElement e : li) {
  if(e.getText().equals("GET")){
    e.click();
  }
  System.out.println(e.getText());
}
```

**Comment by mentholi** [comment]
Hello, 
How did you figure out that the option was not actually selected?
Did you see it was not selected or did you try to check it with selenium? I'm pretty sure that if you are checking it with selenium right after clicking you need to first get the element again from page in order the attribute change to visible. 

Another thing is that it might be that you need to click element inside the `LI` tag. For example if it is bootstrap dropdown menu then you click anchor tag in real life and not the `LI`. 

See: http://getbootstrap.com/components/#btn-dropdowns

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
