### ISSUE TITLE
[🐛 Bug]: unable to generate the NuGet package with 4.14.1

### ISSUE THREAD

**Issue by MaggieKro** [SeleniumHQ/selenium#13030]
### What happened?

When updating Selenium.Webdriver  and Selenium.Support to the version 4.14.1 we received the warning ".nuget\packages\selenium.webdriver\4.14.1\manager\macos\selenium-manager' is not added because the package already contains file 'content\selenium-manager" which prevent us from building the package and running the tests. 

### How can we reproduce the issue?

```shell
install 4.14.1
with packages installed below
  <ItemGroup>
<PackageReference Include="DotNetSeleniumExtras.PageObjects" Version="3.11.0" />
<PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
<PackageReference Include="Microsoft.CodeAnalysis" Version="4.4.0" />
<PackageReference Include="Selenium.Support" Version="4.14.1" />
<PackageReference Include="Selenium.WebDriver" Version="4.14.1" />
<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
</ItemGroup>
```

### Relevant log output

```shell
Warning As Error: File 'C:\Users\.nuget\packages\selenium.webdriver\4.14.1\manager\macos\selenium-manager' is not added because the package already contains file 'contentFiles\any\netstandard2.0\selenium-manager'


Warning As Error: File 'C:\Users\.nuget\packages\selenium.webdriver\4.14.1\manager\macos\selenium-manager' is not added because the package already contains file 'content\selenium-manager' 
```

### Operating System

Windows 11

### Selenium version

Selenium 4.14.1

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

yes, 4.12.1 (revision 8e34639b11)

**Comment by titusfortner** [comment]
Are you building with bazel?

**Comment by nvborisenko** [comment]
It is already fixed in trunk by https://github.com/SeleniumHQ/selenium/commit/4b3238fc8fab6cba60a5fa5389df83df10915689, should be included in the next release. Thanks for bug report, stay tuned.

As a workaround you can suppress this warning.
