### ISSUE TITLE
Add Some Useful Helper Functions

### ISSUE THREAD

**Issue by opticyclic** [SeleniumHQ/selenium#1304]
I often find that my elements aren't visible immediately due to JS latency.
Therefore I I have written a click method like this:

    public void click(By locator) {
      new WebDriverWait(driver, 15).until(ExpectedConditions.elementToBeClickable(locator));
      driver.findElement(locator).click();
    }

I then found myself repeating a lot of XPaths to find buttons and click them so I wrote a helper for that too:

    public void clickButton(String buttonText) {
      click(By.xpath("//button[contains(.,'" + buttonText + "')]"));
    }

Helper methods like this would be useful in the framework to remove a lot of boilerplate from the test code and make the tests a lot more readable.

**Comment by ddavison** [comment]
we won't be doing this as Selenium is the API that *allows* you to write helper methods like that.  we provide the base functionality, and you can extend on Selenium to fit your own desires.

thanks for the recommendation though! :+1: :)
