### ISSUE TITLE
browse files with edge browser does not work

### ISSUE THREAD

**Issue by cppga** [SeleniumHQ/selenium#1305]
using selenium grid 2.48.2 with edge browser (windows 10 build 10586.11, WebDriver for Windows Insiders 1.1)

1. open url "http://demo.vaadin.com/sampler/#ui/data-input/other/upload"
2. send keys to element : wdw.getWait().until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@class='gwt-FileUpload']")))	.sendKeys("C:\\Users\\user\\Desktop\\test.txt");

actual: nothing happens.
expected: next to the browse button the file name should appear. This is working for FF and IE11

**Comment by jimevans** [comment]
The driver for Microsoft Edge is not maintained by the Selenium project. Please contact Microsoft at https://connect.microsoft.com.
