### ISSUE TITLE
[🚀 Feature]: Use a custom function to access shadow-roots in xpath?

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13060]
### Feature and motivation

**Disclaimer** 
I just wanted to share the basic idea, this might be technically not possible or total nonsense.
But it might be a nice addon to selenium framework if it is possible.

**Context**
The shadow-roots are more and more used in UI frameworks and these generic frameworks are starting to create nested shadow-roots. This makes it harder to automate this with the current approach, as each level has to be found and than the next level needs to be accessed. My personal highscore is 4 nested shadow-roots and i allready created a java implementation to split the xpath and resolve it one by one.

**Crazy idea**
If a [custom function](https://www.w3.org/MarkUp/Forms/wiki/Custom_XPath_functions) could be registered to get the children of the #shadow-root or a empty list if it has no children it might be possible to build a XPath that could enter a #shadow-root. Browsers do not support to register a custom javascript function, but i do not know what way Selenium is handling the xpaths.

This would have several limitations, like it would be not possible to leave these elements again, but most of the time the search direction inside the dom is down. But it would make it mutch easier to search different levels and could be opt-in if it is somehow problematic.

### Usage example

the xpath: `div[@id='owner']/ShadowRoot(.)/div[@id='child']/ShadowRoot(.)/div[@id='sub-child']`

the callback:
```
function ShadowRoot(node) {
    return (node && node.shadowRoot && node.shadowRoot.children) ? node.shadowRoot.children : [];
}
```

**Comment by titusfortner** [comment]
I do not think this belongs in Selenium core, but I really want to find a way for us to highlight useful snippets like this that people can use, maybe in a community maintained utilities package?

fwiw, Watir's approach is to do: `driver.find_element(id: 'shadow_host').find_element(css: '*').find_element(xpath: my_relative_xpath)`.

**Comment by joerg1985** [comment]
@titusfortner To implement something like this outside from selenium, a little help from selenium would be needed. 
At least to register the custom xpath function needs to be supported by selenium to make this possible, if it is technically possible at all.

**Comment by titusfortner** [comment]
Ah, maybe I'm misunderstanding. Isn't this just a way to inject JS to get the element? JS that can be executed in its own custom locator class?

Otherwise, it seems like this would need to be supported by the drivers?

**Comment by joerg1985** [comment]
The XPath engine of the browsers do not support callbacks, therefore a complete javascript base XPath engine would be needed to make this work with javascript. But in theory this could be done with javascript if there is a JS bease XPath engine supporting callbacks.

I was hoping this could be done in a central place so all the drivers would pick this up?
e.g. in the [Atoms](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/selenium-atoms) but i am not aware how the atoms are working and if they are really used by all browsers / bindings.

**Comment by titusfortner** [comment]
The atoms were more important when Selenium implemented all of the drivers itself. What the drivers implement now is all based on what is in the w3c spec. Browser vendors can choose to use the atoms or do their own thing, but if it isn't in the spec they don't have to support it.

**Comment by joerg1985** [comment]
Okay in this case i will close this, i was hoping there might be a way.

@titusfortner thanks for your input on this
