### ISSUE TITLE
sendKeys div content editable extra space

### ISSUE THREAD

**Issue by nsanden** [SeleniumHQ/selenium#1306]
When sending a value to a content editable div the value prepends a space.

For example:
I send "test" and div becomes `<div> test</div>`

**Comment by lukeis** [comment]
can you provide a complete reproducible test case? We can reopen this issue when provided.

I just tried this on a simple ```<div id="ed1" contentEditable="true"> </div>```  and it did not add a space:

    from selenium import webdriver
    driver = webdriver.Firefox()
    driver.execute_script("document.body.innerHTML = '<div id=\"ed1\" contentEditable=\"true\"> </div>';")
    driver.find_element_by_id("ed1").send_keys("test")
    assert driver.find_element_by_id("ed1").text = 'test'
