### ISSUE TITLE
[🐛 Bug]: After update to selenium 4.14.1 from selenium 4.13.0 maven-cucumber-reporting stopped generating reports

### ISSUE THREAD

**Issue by SeleniumNinja** [SeleniumHQ/selenium#13063]
### What happened?

After update to selenium 4.14.1 from selenium 4.13.0 cucumber reporting masterthought maven-cucumber-reporting stopped generating reports with a use of maven command: mvn verify -Dcucumber.filter.tags=@desktop. On selenium 4.13.0 everything was fine.

For sure selenium 4.14.1 has some new requirements and other libraries that are needed, but which ?
After update to selenium 4.14.1 from selenium 4.13.0 cucumber reporting masterthought maven-cucumber-reporting stopped generating reports with a use of maven command: mvn verify -Dcucumber.filter.tags=@desktop. On selenium 4.13.0 everything was fine.

For sure selenium 4.14.1 has some new requirements and other libraries that are needed, but which ?

I get the following error:
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input

After update to selenium 4.14.1 from selenium 4.13.0 cucumber reporting masterthought maven-cucumber-reporting stopped generating reports with a use of maven command: mvn verify -Dcucumber.filter.tags=@desktop. On selenium 4.13.0 everything was fine.

For sure selenium 4.14.1 has some new requirements and other libraries that are needed, but which ?

I get the following error:

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input

In target folder /jsonReport both files are empty:
cucumber-report.html
cucumber-report.json

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(features="src/test/java/features",
        plugin = {"pretty", "json:target/jsonReports/cucumber-report.json",
                "html:target/jsonReports/cucumber-report.html"},
        glue= {"stepDefs"},
        stepNotifications = true,
        monochrome = true
        )
public class TestRunner {
}

 <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.14.1</version>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-chrome-driver</artifactId>
    <version>4.14.1</version>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>7.14.0</version>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>7.14.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-jvm</artifactId>
    <version>7.14.0</version>
    <type>pom</type>
</dependency>
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.13.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>31.1-jre</version>
</dependency>
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0</version>
</dependency>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-core</artifactId>
    <version>7.14.0</version>
</dependency>
<dependency>
    <groupId>net.masterthought</groupId>
    <artifactId>maven-cucumber-reporting</artifactId>
    <version>5.7.6</version>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>gherkin</artifactId>
    <version>26.2.0</version>
</dependency>
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.11.0</version>
</dependency>
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.3.1</version>
</dependency>
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0</version>
    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit47</artifactId>
            <version>3.0.0</version>
        </dependency>

    </dependencies>

    <configuration>
        <includes>
            <include>**/*TestRunner.java</include>
        </includes>

    </configuration>
</plugin>
<plugin>
    <groupId>net.masterthought</groupId>
    <artifactId>maven-cucumber-reporting</artifactId>
    <version>5.7.5</version>
    <executions>
        <execution>
            <id>execution</id>
            <phase>verify</phase>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <projectName>Cucumber</projectName>
                
                <skip>false</skip>
                
                <outputDirectory>${project.build.directory}</outputDirectory>
                
                <inputDirectory>${project.build.directory}/jsonReports</inputDirectory>
                <jsonFiles>
                    
                    <param>**/*.json</param>
                </jsonFiles>
                

                
                <mergeFeaturesById>false</mergeFeaturesById>
                
                <mergeFeaturesWithRetest>false</mergeFeaturesWithRetest>
                
                <checkBuildResult>false</checkBuildResult>
            </configuration>
        </execution>
    </executions>
</plugin>

### How can we reproduce the issue?

```shell
Take a look at the code.
```

### Relevant log output

```shell
I get the following error:

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
```

### Operating System

Windows 10

### Selenium version

4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 118

### Are you using Selenium Grid?

4.14.1

**Comment by titusfortner** [comment]
> For sure selenium 4.14.1 has some new requirements and other libraries that are needed, but which ?

Selenium declares all of its dependencies and they are loaded by maven

The error is coming from other packages, so you need to check with them to see why they might be getting that error. 

You can also double check this to make sure that the right version of packages are specified in all the places: https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html
