### ISSUE TITLE
[🐛 Bug]: Third party vendors cannot integrate to selenium grid directly without adding nodes

### ISSUE THREAD

**Issue by uman3951** [SeleniumHQ/selenium#13073]
### What happened?

[Requirement]

We are trying to integrate Selenium Grid with thirds party vendors like Browser Stack , Lambda Test, Source Labs 

[Use Case]
- if user want to execute the test in a browser Stack / Source Labs/ Lambda Test , that test should be execute in those vender machine with out creating nodes with the use of distributors 

### How can we reproduce the issue?

```shell
-Create an Event Bus (java -jar selenium-server-4.14.0.jar event-bus)
-Create a new Session Queue (java -jar selenium-server-4.14.0.jar sessionqueue)
-Create a new Session map (java -jar selenium-server-4.14.0.jar sessions)
-Create a new Distributor interreacting  new session queue, new session map and event bus (java -jar selenium-server-4.14.0.jar distributor --sessions https://192.168.1.9:5556 --sessionqueue https://192.168.1.9:5559 --bind-bus false
)
-Create a router interreacting with New Session Queue, Session Map, and Distributor (java -jar selenium-server-4.14.0.jar router --sessions http://192.168.1.9:5556 --distributor http://192.168.1.9:5553 --sessionqueue http://192.168.1.9:5556)

After setting up the services as mentioned above I pointed by scripts to the hub but got the log as described in the log output 

Call from the remote webdriver

RemoteWebDriver driver;
driver = new RemoteWebDriver(new URL("http://192.168.1.9:4444"), browserOptions);
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '342-NB7D39NN3', ip: '192.168.1.9'
```

### Operating System

Windows10

### Selenium version

selenium-server-4.14.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

4.14

**Comment by diemol** [comment]
You can use the Standalone role and relay all calls.

**Comment by kherath17** [comment]
@diemol how we can achieve this while still using hub/node concept since my hub is spawned up on a K8 cluster which gets auto scaled dynamically additionally I'm more focused in the ability to run the nodes on different configurations as well

**Comment by diemol** [comment]
Then add the configuration to the existing Nodes.

**Comment by kherath17** [comment]
@diemol  sorry I didn't catch, if we keep the nodes aside of this topic and if I want to route the incoming requests to hub to  browserstack/saucelabs , without using nodes through the hub itself , how can I achieve this? Appreciate if you can guide through few steps

**Comment by diemol** [comment]
The only way to do that is by using Nodes or Standalone.

**Comment by kherath17** [comment]
@diemol  Okay if Im to use Standalone , can you provide some insights on how to achieve it?

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/grid/configuration/toml_options/#relaying-commands-to-a-service-endpoint-that-supports-webdriver

Create the config file and supply it to the Standalone server.

**Comment by diemol** [comment]
I left some links above where you can ask more questions. There is also a Slack channel link above.

**Comment by titusfortner** [comment]
Are you looking for something like this?
https://saucelabs.com/resources/blog/extending-your-selenium-grid-with-sauce

**Comment by kherath17** [comment]
thank you @diemol  I will check on that

yes @titusfortner this approach of routing via a node is already implemented and working as expected, but what I wanted was to find a way so that we dont need nodes the hub itself (distributor) handles it and routes the request to saucelab or browserstack directly.
