### ISSUE TITLE
[🐛 Bug]: Selenium look for selenium-manager only from %ANACONDAPATH%\bin\

### ISSUE THREAD

**Issue by Fradhyle** [SeleniumHQ/selenium#13076]
### What happened?

I'm using Selenium 4.14.0 with selenium-manager 4.14.0 
I've tried to obtain WebDrive with selenium-manager, but Selenium look for selenium-manager only from 'bin' folder under Anaconda path. 
But my selenium-manager is in 'Scripts' folder. 
I don't know which one is right location but I think it should be fixed. 
I've already added C:\ProgramData\Anaconda3, C:\ProgramData\Anaconda3\Library\bin, C:\ProgramData\Anaconda3\Scripts to my system variable PATH

### How can we reproduce the issue?

Just run this code 
```python
driver = webdriver.Edge()
```

### Relevant log output

```shell
WebDriverException                        Traceback (most recent call last)
File C:\ProgramData\Anaconda3\Lib\site-packages\selenium\webdriver\common\driver_finder.py:38, in DriverFinder.get_path(service, options)
     37 try:
---> 38     path = SeleniumManager().driver_location(options) if path is None else path
     39 except Exception as err:

File C:\ProgramData\Anaconda3\Lib\site-packages\selenium\webdriver\common\selenium_manager.py:81, in SeleniumManager.driver_location(self, options)
     79 browser = options.capabilities["browserName"]
---> 81 args = [str(self.get_binary()), "--browser", browser]
     83 if options.browser_version:

File C:\ProgramData\Anaconda3\Lib\site-packages\selenium\webdriver\common\selenium_manager.py:65, in SeleniumManager.get_binary()
     64 if not path.is_file():
---> 65     raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
     67 logger.debug("Selenium Manager binary found at: %s", path)

WebDriverException: Message: Unable to obtain working Selenium Manager binary; C:\ProgramData\Anaconda3\bin\selenium-manager.exe
```

### Operating System

Windows 10 Enterprise 22H2

### Selenium version

Python 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge for Business 118.0.2088.76 (Stable) (64 bit)

### What are the browser driver(s) and version(s) where you see this issue?

EdgeDriver 118.0.2088.76 (Stable) (64 bit)

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Please set the location of Selenium Manager executable in the `SE_MANAGER_PATH` environment variable.

**Comment by Fradhyle** [comment]
Hi, @titusfortner 
What I remember is I don't need to set selenium manager path when I used previous version.
Can you tell me why it was changed like current way, and are there any possibilities that it could be changed like previous version?

**Comment by titusfortner** [comment]
Selenium should not be managing special environment variables for Anaconda, but we added something because there was no other solution for users. Now that we have a general solution that works for any package manager or situation where the file does not end up in the default location, it is no longer necessary to have custom code for a specific situation.

When the Anaconda dev replied to a PR here a while back, it was suggested that they may be able to set this environment variable in their package manager so you would not need to set the path yourself. I would ask them about doing that.

**Comment by Fradhyle** [comment]
> Selenium should not be managing special environment variables for Anaconda, but we added something because there was no other solution for users. Now that we have a general solution that works for any package manager or situation where the file does not end up in the default location, it is no longer necessary to have custom code for a specific situation.
> 
> When the Anaconda dev replied to a PR here a while back, it was suggested that they may be able to set this environment variable in their package manager so you would not need to set the path yourself. I would ask them about doing that.

@titusfortner 
Thanks :)
