### ISSUE TITLE
[🐛 Bug]: Unable to obtain Selenium Manager Binary

### ISSUE THREAD

**Issue by dammie12** [SeleniumHQ/selenium#13077]
### What happened?

While running my test, i do get this message and when it pops up, all the remaining tests fails from that point. I mean, sometimes, it runs for over 30mins before encountering this issue. Unfortunately, it happens anywhere in the list of test. I happen to have about 30 testcases in the suite.

error Unable to obtain Selenium Manager Binary at: C:\Users\USER~1\AppData\Local\Temp\selenium-manager13842424259427006952094714289847755\selenium-manager.exe
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: driver.version: EdgeDriver

After this error shows up, finding elements results in this error - Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null

### How can we reproduce the issue?

```shell
try {
		this.driver = BrowserFactory.getDriver(browserName);//BrowserFactory retu
		this.driver.manage().timeouts().implicitlyWait(Duration.ofMillis(10000));
		this.elementWait = new WebDriverWait(this.driver, waitTimeOut);
		this.driver.manage().deleteAllCookies();
		Methods.pause(5);
		this.driver.get(baseURL);
		Entry.logs.info("Setting up driver");

		/* Tries to reset browser zoom to default - 100% */
		this.driver.manage().window().maximize();
		this.driver.findElement(By.tagName("html")).sendKeys(Keys.chord(Keys.CONTROL, "0"));
	} catch (Exception e) {
		ResultLog.testFail(e.getMessage());
	}

WebDriver getDriver(String browser) {
	WebDriver driver;
	if (browser.toLowerCase().equalsIgnoreCase("chrome")) {
		ChromeOptions chromeOptions = new ChromeOptions();
		chromeOptions.addArguments("--remote-allow-origins=*", "ignore-certificate-errors");
		driver = new ChromeDriver(chromeOptions);
	} else {
		EdgeOptions edgeOptions = new EdgeOptions();
		edgeOptions.addArguments("--remote-allow-origins=*", "ignore-certificate-errors");
		driver = new EdgeDriver(edgeOptions);
	}
	return driver;
}
```

### Relevant log output

```shell
error Unable to obtain Selenium Manager Binary at: C:\Users\DOLUBA~1\AppData\Local\Temp\selenium-manager13842424259427006952094714289847755\selenium-manager.exe
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: driver.version: EdgeDriver

After this error shows up, finding elements results in this error - Cannot invoke "org.openqa.selenium.SearchContext.findElement(org.openqa.selenium.By)" because "this.searchContext" is null
```

### Operating System

Windows 11 Pro

### Selenium version

4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.70,  msedgedriver 118.0.2088.76

**Comment by diemol** [comment]
@bonigarcia do you remember what this error was?

**Comment by bonigarcia** [comment]
@diemol Sorry, I don't see any relevant log of the Rust side here. The message `"this.searchContext" is null` seems related to Java.

@dammie12 I would do the following:

1. Bump to Selenium 4.15.0
2. Capture the Selenium Manager logs. See [logging doc](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/). See [example](https://github.com/bonigarcia/selenium-examples/blob/main/src/test/java/io/github/bonigarcia/selenium/logging/ChromeLoggingTest.java).

**Comment by diemol** [comment]
I meant the unable to find Selenium Manager binary message

**Comment by titusfortner** [comment]
I think it was getting deleted from temp directory after a time somehow. The saving the binary to cache directory in 4.15 should be the fix.

**Comment by NagaLakshmiE** [comment]
Getting the same exception using Selenium Manager 4.15.0 version with CSharp automation. On few machines it is working fine but on few it is failing with the above exception.

**Comment by titusfortner** [comment]
This issue was specific to Java and fixed in 4.15. If there is a different issue, please open a new ticket. Thank you.

**Comment by dammie12** [comment]
Thanks Titus, upgrading to 4.15 resolved the issue. I noticed that the selenium manager exe file is created in the cache. I assume that every upgrade to selenium would generate its own folder, correct?

**Comment by titusfortner** [comment]
> every upgrade to selenium would generate its own folder

Yes, we want to make sure we are keeping functionality correct for the versions without needing to figure out backwards compatibility while this feature is still in beta.
