### ISSUE TITLE
It would be nice, if selenium had a test status of: Manual Validation Required

### ISSUE THREAD

**Issue by bryancoxdish** [SeleniumHQ/selenium#13075]
### Feature and motivation

This would be useful if execution can be done, but there needs to be manual validation.  An example, verify data got entered into a database.

### Usage example

This would be useful if execution can be done, but there needs to be manual validation.  An example, verify data got entered into a database.

**Comment by titusfortner** [comment]
Selenium does not have any test status at all.
This seems to be a request of a test runner?

If you are interested in making sure the browser stays open after the session has finished to do a manual verification, the behavior is different in the different languages: https://github.com/SeleniumHQ/selenium/issues/11303#issuecomment-1327851415
For Java & .NET just don't call quit. For Ruby & Python you can use chrome and set `detach: true`

**Comment by bryancoxdish** [comment]
Then where is Status.PASS coming from?  There is a Status.class.

**Comment by titusfortner** [comment]
There is a Status class for managing Observability tracing. There is no `PASS` in Selenium
