### ISSUE TITLE
[🚀 Feature]: Allow "stable" as browser version

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13089]
### Feature and motivation

I added this to trunk already with this commit: c020b03b
But I'm raising this issue for us to decide if it is a good idea and we should keep it.

The big picture idea is that Selenium Manager will allow using the latest stable version of the browser is used on the end-node, without needing to specify it in a stereotype when starting a grid node.

My specific current use case is that the Ruby bindings do not use pinned browsers, and I cannot guarantee what browser is on the machine, so I cannot guarantee I'm testing with the latest chrome as it is released.
My solution was to do this: 770796ca198edf60eecb50adf9d760511e109903 but that fails for remote tests. Creating stereotypes for the test suite seems like a huge overkill.

Reasons for this behavior:
1. Discussed here — https://github.com/SeleniumHQ/selenium/issues/12530
2. This matches the behavior of what Selenium Manager happens when no browser is installed
3. Most Sauce Labs users use "latest" as their browser version, and this matches it
4. I noticed from this issue that an old version was being used which could have caused problems: https://github.com/SeleniumHQ/selenium/issues/13079

Reasons against this behavior:
1. Infrastructure should always be locked down and in a known state (note that Selenium Manager already makes this not quite true).

### Usage example

```
options.browser_version = "stable"
```

**Comment by diemol** [comment]
That should work with the Grid since we remove the browser version before talking to the browser driver. 

Why don't we also allow `beta` and `dev`? How should we treat other browsers (Safari).

**Comment by mooragor** [comment]
Hi there,  I don't know if this is totally related, but I've recently had an issue with Selenium Manager where I had specified options.browser_version = "stable", however I think that Chrome had newer version than the manager had a driver for.

It would be really great if, when delegating to Selenium Manager to download both the browser and driver, that it would always get a compatible pairing, even if that meant not getting quite the latest browser.

https://github.com/SeleniumHQ/selenium/issues/13081#issuecomment-1792153478

**Comment by titusfortner** [comment]
I didn't add dev/beta/canary/etc because I only need stable to get my tests passing, and it works for all browsers. 

Safari:
```
titusfortner@SL-1837 selenium % ./common/manager/macos/selenium-manager --browser safari --browser-version stable --debug
DEBUG	safari detected at /Applications/Safari.app
DEBUG	Running command: /usr/libexec/PlistBuddy -c "print :CFBundleShortVersionString" /Applications/Safari.app/Contents/Info.plist
DEBUG	Output: "16.5.2"
DEBUG	Required driver: safaridriver (local)
INFO	Driver path: /usr/bin/safaridriver
INFO	Browser path: /Applications/Safari.app/Contents/MacOS/Safari
```

There are certainly other solutions that are more correct, but would require a much bigger change and have its own overhead.

**Comment by diemol** [comment]
I think this makes sense. Is there something left to implement?

**Comment by titusfortner** [comment]
No, if you're good with the change we can close this.
