### ISSUE TITLE
[🐛 Bug]: Not work when move total vs project directory.

### ISSUE THREAD

**Issue by skeksk91** [SeleniumHQ/selenium#13086]
### What happened?

"Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location"  

### How can we reproduce the issue?

```shell
Move whole vs c# Window Forms project folder and execute .sln, build & run 

Chrome119 WebDriver 4.15.0 (It can reproduce > WebDriver 4.10.0)
```

### Relevant log output

```shell
"Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location"   string
```

### Operating System

Windows

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 119

**Comment by diemol** [comment]
@nvborisenko do you know?

**Comment by nvborisenko** [comment]
@skeksk91 try use `Rebuild` instead of `Build`, and then please provide entire exception raised by selenium (with stacktrace).

**Comment by titusfortner** [comment]
Closing as we did not hear back.
