### ISSUE TITLE
[🐛 Bug]: Zombie processes and post-test junk file accumulation

### ISSUE THREAD

**Issue by wild-love** [SeleniumHQ/selenium#13083]
### What happened?

I have made a ticket before about these problems, but we have since learned more about the issue, and the previous ticket was unresolved. That ticket is here: https://github.com/SeleniumHQ/selenium/issues/12732

To recap: We run many test suites through selenium daily as part of our application. The selenium nodes docker containers we use are usually running 24/7. Each test suite has many tests, sometimes of vastly different sizes (25-10000+). It seems that we run into problems when there are large numbers of tests in a test suite.

We experience two main issues;
1. There are leftover junk files in `/tmp` after running test suites with higher numbers of tests
2. Sometimes Selenium spawns zombie browsers that suck up a ton of system resources

I've tried several different ways to reproduce the zombie browsers: failing tests, passing tests, tests that don't finish due to code errors in the tests. The smaller the test suite, the less likely the zombie processes will appear. I have trouble reproducing the issue with small test suites. The best way I've reproduced it is with our larger test suites that use a fair number of tests. This issue appears to affect all nodes we use (firefox, chrome, and edge).

![image (2)](https://github.com/SeleniumHQ/selenium/assets/22314258/6a9e31c0-36c4-4914-bfc5-c02caba613da)

This is a screenshot showing our selenium node processes. Note that we were not running any tests at the time this screenshot was taken.

### How can we reproduce the issue?

```shell
Run large test suites (250+ tests) that are comprised of large tests (500+ LOC with a wide variety such as steps, waits, element retrieval, etc).
```

### Relevant log output

```shell
See screenshot above.
```

### Operating System

Ubuntu 22.04.03 and Ubuntu 16.04

### Selenium version

Selenium Grid 4.12, Docker version

### What are the browser(s) and version(s) where you see this issue?

Chrome/Edge/Firefox docker nodes 4.12

### What are the browser driver(s) and version(s) where you see this issue?

Chrome/Edge/Firefox docker nodes 4.12

### Are you using Selenium Grid?

Selenium Grid 4.12, Docker version

**Comment by diemol** [comment]
The leftover open browsers are usually due to wrongly closed sessions. For example, the test fails in the middle of the execution, and there is code that rescues that error, which leaves the browser open. Could you let me know if you've already checked that? Do all your tests clean the environment when they fail? Are you running multiple browser instances in a single container? What happens when you only run one per container?

**Comment by wild-love** [comment]
@diemol Thanks for the debugging prompts.
1. `"Could you let me know if you've already checked that?"` We've scrutinized the code base and can't find any smoking guns in regards to buggy error handling during testing. Are there any particular examples you can think of where rescuing an error results in zombie browsers?
2. `"Do all your tests clean the environment when they fail?"` I spoke with my team and none of us knew what you mean. Would you explaining that a bit more?
3. `"Are you running multiple browser instances in a single container?"` Yes. Typically we will have 15 node containers running (5 each of firefox/chrome/edge), and our test suite will queue up 200+ tests for the nodes.
4. `"What happens when you only run one per container?`" We have tested a single-browser container setup that did not resolve the problem. The Grid with one browser session at a time per container took longer to get unhealthy (which seems to correlate to the zombie browsers), but it still did eventually.

**Comment by titusfortner** [comment]
So depending on the test framework, there's typically a before hook, a test method and an after hook.
If there's a failure in the test method, then the after hook will run to clean things up (like quitting the driver).

Sometimes people put a bunch of things in the after hook. When something in the after hook fails, if it is before driver.quit call then the browser will stay open. If you are doing multiple things, consider using a try/catch/finally to make sure the driver.quit is always called.

**Comment by wild-love** [comment]
@titusfortner We use the following code in our `after` hook. We didn't use `finally` here, though the team all agree the code seems solid. Do you see any glaring errors, or any improvements to be made?
```
cucumber.After({ "timeout": 120000 }, async function (scenario_ctx) {
    let errors = [];

    // clear the step counter so any attachments we create are not misattributed
    this.step = null;

    if (this.driver) {
        // take a screenshot on error
        // for some reason scenario_ctx's result status is sometimes a string and sometimes a number
        if ((scenario_ctx.result.status === 6) || (scenario_ctx.result.status === "FAILED")) {
            try {
                let test_id = scenario_ctx.testCaseStartedId,
                    ss_path = path.join(this.result_set_id, test_id);

                await this.takeScreenshot("failed", ss_path);
            } catch (err) {
                errors.push(err);
            } // end try
        } // end if

        // shut down the webdriver instance
        await this.driver.quit();
    } // end if

    for (let data of this.res_attachments) {
        let message = { "attachment": { "testCaseStartedId": scenario_ctx.testCaseStartedId, data } };

        console.log(JSON.stringify(message));
    } // end for-of

    if (errors.length) {
        throw new Error(errors.map((err) => err.toString()).join("\n"));
    } // end if
}); // end cucumber.After closure```

**Comment by titusfortner** [comment]
Yes, this is generally the approach I recommend. I'm not sure the likelihood/frequency of taking screenshots failing and preventing the driver from quitting which leaves browsers open, but it is good to make sure that there is protection.

**Comment by wild-love** [comment]
@titusfortner  This is actually the code we already had in place, no modifications have been made, so we're getting these zombie browers/junk files even with this try/catch safety net. Is there anything else you can think of for us to try? We've tried everything we can think of, and the best "solution" we could come up with is to manually clear that junk file directory after every test, but thats a half measure at best since it only alleviates the disk space usage and does nothing for the system memory hoarding.

**Comment by diemol** [comment]
>"What happens when you only run one per container?" We have tested a single-browser container setup that did not resolve the problem. The Grid with one browser session at a time per container took longer to get unhealthy (which seems to correlate to the zombie browsers), but it still did eventually.

This did not resolve the issue, but it improved the situation. Wouldn't it be a good idea to follow this path to identify the points where browsers are left open? Also, the idea of a Docker Grid is to throw it away now and then to have a clean environment.

**Comment by diemol** [comment]
I believe that keeping this matter open may not be the most beneficial or constructive approach. If you require additional assistance or tips for troubleshooting, we warmly invite you to join our supportive chat – the links are provided below for your convenience.
