### ISSUE TITLE
[🐛 Bug]: incorrect type hint to WebDriverWait init

### ISSUE THREAD

**Issue by luketudge** [SeleniumHQ/selenium#13087]
### What happened?

A recent PR added some type hints to WebDriverWait:
https://github.com/SeleniumHQ/selenium/pull/13070/files

The hint here in the init definition says that the driver argument should be of type WebDriver:
https://github.com/SeleniumHQ/selenium/blob/1c9e702b8686f04d9fe69824f3bdd171fa523df1/py/selenium/webdriver/support/wait.py#L38

But the docstring says that WebElement is also a permissible type for this argument:
https://github.com/SeleniumHQ/selenium/blob/1c9e702b8686f04d9fe69824f3bdd171fa523df1/py/selenium/webdriver/support/wait.py#L46

The workings of the class also allow for web elements as an init input, so the type hint is incorrect. Static type checking (for example with mypy) will fail even for functional and type-safe code that uses a wait with a web element.

### How can we reproduce the issue?

```shell
'''example.py'''

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait

driver = webdriver.Firefox()
driver.get("http://example.com")
heading1 = driver.find_element(By.TAG_NAME, 'h1')

WebDriverWait(heading1, 10)

driver.quit()
```

### Relevant log output

```shell
>> mypy example.py 
example.py:11: error: Argument 1 to "WebDriverWait" has incompatible type "WebElement"; expected "WebDriver"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

### Operating System

Ubuntu

### Selenium version

Python 4.15.0

### What are the browser(s) and version(s) where you see this issue?

not applicable

### What are the browser driver(s) and version(s) where you see this issue?

not applicable

**Comment by titusfortner** [comment]
Can you make a PR? Thanks.

**Comment by luketudge** [comment]
> Can you make a PR? Thanks.

Ok. Is here: https://github.com/SeleniumHQ/selenium/pull/13088

**Comment by pinterior** [comment]
here's another one #13108 also checking parameter type of `until` and `until_not`
