### ISSUE TITLE
semver compliance for node.js

### ISSUE THREAD

**Issue by grawk** [SeleniumHQ/selenium#1308]
I've noticed that there are arguably "breaking" changes in minor and even patch releases. For example, between `2.46` and `2.48` support becomes deprecated/broken for `node@v0.12.x`:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#v2480

This has probably been noted by others previously. But I'd like to know the rationale for it. Can you point me to a previously closed ticket, etc

**Comment by jleyba** [comment]
npm versions are tied to match those of the Selenium project as a whole, not strict semver. If we didn't keep the versions in sync, yes we'd be on 3.x now, but Selenium 3.0 has a special meaning with this project so we can't use that just for npm semver.

Note there is precedence for this type of breaking change in the Selenium as a whole: on the java side, `2.47.0` dropped support for Java 6. In fact, the supported versions of Firefox change with every minor release (using a shifting window of ESR-1, ESR, N-1, N, where actual Firefox versions depends on what the current version is at the time of the Selenium release).

**Comment by ddavison** [comment]
how about patch versioning, @jleyba ?

**Comment by jleyba** [comment]
@ddavison What about them? They're used to push bug fixes between Selenium releases.

**Comment by ddavison** [comment]
answered my own question :) .. it sounded like from the issue creator's standpoint, that you weren't doing patch revisions.  they only included `MAJOR.MINOR`.

**Comment by jleyba** [comment]
Keep in mind that even patch revisions are misleading. The Selenium project uses trunk based development: every release we push is just a snapshot of master `@HEAD` at the time of release.
