### ISSUE TITLE
[🐛 Bug]: Missing git tag for 4.15.2

### ISSUE THREAD

**Issue by mgorny** [SeleniumHQ/selenium#13099]
### What happened?

A 4.15.2 release has been uploaded to PyPI but there's no corresponding git tag here.

### How can we reproduce the issue?

```shell
n/a
```

### Relevant log output

```shell
n/a
```

### Operating System

n/a

### Selenium version

4.15.2

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

**Comment by titusfortner** [comment]
Fixed
https://github.com/SeleniumHQ/selenium/tags

**Comment by mgorny** [comment]
Thank you!
