### ISSUE TITLE
[🚀 Feature]: Allow SeleniumManager to ignore what's on the system

### ISSUE THREAD

**Issue by mooragor** [SeleniumHQ/selenium#13094]
### Feature and motivation

SeleniumManager should be able to completely ignore what is currently on the system it's running on. 

When you don't know exactly what will be on the systems you run the tests on, or may have to run the same tests on multiple systems (some which have browser/browserdriver pre-installed and on the system PATH, and some which don't), it would be great to tell SeleniumManager that you want a specific version of the browser (or 'stable'), and have it completely ignore anything it finds in the system path.

For the whole sordid story, see: https://github.com/SeleniumHQ/selenium/issues/13081

### Usage example

My failing scenario had some machines where there was already a chromedriver in the system PATH, but it was old and incompatible with the latest 'stable' chrome I had requested (chromeOptions.BrowserVersion).  Other than modifying the system PATH to remove the driver, or not requesting 'stable' I ended up with a mismatch of driver/browser.

**Comment by titusfortner** [comment]
I would like for the fix to be: #12985 
This should be the default opt-in behavior.

1. Specify the desired browser version
2. If it doesn't match what is on the system, get it
3. Make sure the best driver to go with it gets used

The checking for driver on the system is only a Selenium 4 thing to maintain backwards compatibility.

**Comment by bonigarcia** [comment]
This feature request seems equivalent to #13110.

**Comment by titusfortner** [comment]
So, the root error of #13081 was that the user specified "stable" as the `browserVersion` and it did not match the drivers that were located on the System. The real issue is the mismatch, not whether something should or shouldn't be downloaded.

So the correct fix, and one that I think can be the default behavior is #13128

**Comment by titusfortner** [comment]
With #13159 Selenium will ignore what is on the system if it does not match the version. That should be sufficient for now, and if it is not we need to figure out how it fits in with expected Selenium 5 behavior. Thanks.
