### ISSUE TITLE
[🐛 Bug]: Chrome Driver Crashing on Windows -Selenium C#

### ISSUE THREAD

**Issue by BinBk12** [SeleniumHQ/selenium#13105]
### What happened?

I tried all possible ways but I am always getting chrome crash issue
Note : Versions are same across everywhere. Tried in selenium 4.8.2/4.15 no luck :(

**My Code:**

 ChromeOptions options = new ChromeOptions();
  options.AddArgument("test-type");
            options.AddArgument("--ignore-certificate-errors");
            options.AddArgument("no-sandbox");
            options.AddArgument("disable-infobars");
            options.AddArgument("--start-maximized");
            options.AddArguments("--incognito");
            options.AddArguments("--disable-dev-shm-usage");
            options.AddArguments("--remote-allow-origins=*");
            options.AddArguments("--remote-debugging-port=9222");
            options.AddArgument(@"user-data-dir=C:\Users\Cabbk\AppData\Local\Google\Chrome\User Data");
            //var service = ChromeDriverService.CreateDefaultService();
            //service.HideCommandPromptWindow = true;
            //service.SuppressInitialDiagnosticInformation = true;
            options.BinaryLocation = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe";
            var chdriverPath = @"C:\TFS\chromedriver-win64";
            driver = new ChromeDriver(chdriverPath, options);
            driver.Url = "https://www.aps.com/en/residential/home";

**Error Message**
  Message: 
System.InvalidOperationException : session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)
TearDown : System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromeDriver.ctor(String chromeDriverDirectory, ChromeOptions options)
launch_StepDefinition.launchfocuschrome(String browser, String username, String password) line 81
lambda_method(Closure , IContextManager , String , String , String )
BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration) line 68
TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments, TimeSpan& duration) line 567
TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance) line 480
<4 more frames...>
--TearDown
Dictionary`2.get_Item(TKey key)
SpecFlowContext.Get[T](String key) line 68
HookInitialization.AfterScenario() line 80
lambda_method(Closure , IContextManager )
TestExecutionEngine.FireEvents(HookType hookType) line 351
TestExecutionEngine.FireScenarioEvents(HookType bindingEvent) line 311
TestExecutionEngine.OnScenarioEnd() line 243
TestRunner.OnScenarioEnd() line 64
LaunchFeature.TestTearDown()

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
options.AddArgument("test-type");
            options.AddArgument("--ignore-certificate-errors");
            options.AddArgument("no-sandbox");
            options.AddArgument("disable-infobars");
            options.AddArgument("--start-maximized");
            options.AddArguments("--incognito");
            options.AddArguments("--disable-dev-shm-usage");
            options.AddArguments("--remote-allow-origins=*");
            options.AddArguments("--remote-debugging-port=9222");
            options.AddArgument(@"user-data-dir=C:\Users\Cabbk\AppData\Local\Google\Chrome\User Data");
            //var service = ChromeDriverService.CreateDefaultService();
            //service.HideCommandPromptWindow = true;
            //service.SuppressInitialDiagnosticInformation = true;
            options.BinaryLocation = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe";
            var chdriverPath = @"C:\TFS\chromedriver-win64";
            driver = new ChromeDriver(chdriverPath, options);
            driver.Url = "https://www.aps.com/en/residential/home";
```

### Relevant log output

```shell
Message: 
System.InvalidOperationException : session not created: Chrome failed to start: exited normally.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (SessionNotCreated)
TearDown : System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities desiredCapabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromeDriver.ctor(String chromeDriverDirectory, ChromeOptions options)
launch_StepDefinition.launchfocuschrome(String browser, String username, String password) line 81
lambda_method(Closure , IContextManager , String , String , String )
BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration) line 68
TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments, TimeSpan& duration) line 567
TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance) line 480
<4 more frames...>
--TearDown
Dictionary`2.get_Item(TKey key)
SpecFlowContext.Get[T](String key) line 68
HookInitialization.AfterScenario() line 80
lambda_method(Closure , IContextManager )
TestExecutionEngine.FireEvents(HookType hookType) line 351
TestExecutionEngine.FireScenarioEvents(HookType bindingEvent) line 311
TestExecutionEngine.OnScenarioEnd() line 243
TestRunner.OnScenarioEnd() line 64
LaunchFeature.TestTearDown()
```

### Operating System

Windows 10

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome version 119

### What are the browser driver(s) and version(s) where you see this issue?

Chrome  Version 119.0.6045.106

**Comment by diemol** [comment]
The error comes directly from Chrome. You should play with the different flags that you are using to find what might be causing the error.

If the issue persists, you should report it to Chrome.

**Comment by nvborisenko** [comment]
Special attention to `user-data-dir=C:\Users\Cabbk\AppData\Local\Google\Chrome\User Data` flag, it contains whitespace. Most likely you should escape it somehow.

**Comment by BinBk12** [comment]
Thanks all for your support .
