### ISSUE TITLE
[🐛 Bug]: Inconsistent Input Behavior with PointerInput on iOS 17 using Selenium 4.9.1 

### ISSUE THREAD

**Issue by Deceptio** [SeleniumHQ/selenium#13103]
### What happened?

I am currently working with iOS 17 and the Selenium-Api 4.9.1 JAR. My goal is to enter three numbers into a numeric field by simulating key presses using the PointerInput class.

Here's the scenario: I'm attempting to use the keyboard to click the numbers 1, 2, and 3, which correspond to the following coordinates on the screen:

Number 1: Button at position (0,561)
Number 2: Button at position (125,561)
Number 3: Button at position (262,561)
However, I'm experiencing inconsistent input behavior. Instead of obtaining the expected sequence of '123', the output I'm getting is '11122'. This occurs despite having experimented with different durations for the pauses between inputs.

No matter how I adjust the pauses, there seems to be no improvement, and the issue persists where the input is erratic and includes more numbers than intended. It's unclear whether the issue lies with the PointerInput implementation or if there's a specific iOS 17.0.3 interaction that I'm not accounting for.

### How can we reproduce the issue?

```shell
public void fasterPINLogin(String numbersText) {
    PointerInput finger = new PointerInput(PointerInput.Kind.TOUCH, "finger");
    Sequence tap = new Sequence(finger, 0);

    if (isIOS()) {
        clicks(finger, tap,0,561);
        clicks(finger, tap,128,561);
        clicks(finger, tap,262,561);
        iosDriver.perform(List.of(tap));
    }
}

private void clicks(PointerInput finger, Sequence tap, int x, int y) {
    tap.addAction(finger.createPointerMove(ofMillis(10), PointerInput.Origin.viewport(), x, y));
    tap.addAction(finger.createPointerDown(LEFT.asArg()));
    tap.addAction(new Pause(finger, ofMillis(500)));
    tap.addAction(finger.createPointerUp(LEFT.asArg()));
    tap.addAction(new Pause(finger, ofMillis(500)));
}`
```

### Relevant log output

```shell
The input in the number field is 11122
```

### Operating System

iOS

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

App

### What are the browser driver(s) and version(s) where you see this issue?

Appium

**Comment by diemol** [comment]
Our iOS 17 knowledge is very little. I think you should post this to the Appium project or as a question on one of the forums linked below.
