### ISSUE TITLE
Dead link in wiki

### ISSUE THREAD

**Issue by yb66** [SeleniumHQ/selenium#1310]
Hi,

On the wiki's [ChromeDriver page](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver) it states:

> For Linux systems, the ChromeDriver expects /usr/bin/google-chrome to be a symlink to the actual Chrome binary. See also the section on [overriding the Chrome binary location](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#Overriding_the_Chrome_binary_location.md)

That link https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#Overriding_the_Chrome_binary_location.md is dead. I'd also like to know a way to override the default location, but I may have found it at [https://selenium.googlecode.com/svn/wiki/ChromeDriver.wiki](https://selenium.googlecode.com/svn/wiki/ChromeDriver.wiki)

Regards,
yb

**Comment by lukeis** [comment]
fixed... here's a more appropriate link:

https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location

**Comment by yb66** [comment]
Thanks.
