### ISSUE TITLE
[🐛 Bug]: (ChromeDriver version  119)While in incognito mode and downloading file from UI, UI pops up with Save Window even with the download location is already setup and also disabled in chrome options.

### ISSUE THREAD

**Issue by jawad-arshad-khan97** [SeleniumHQ/selenium#13104]
### What happened?

Code used to launch the chrome incognito:

 var choptions = new ChromeOptions();
                    choptions.PageLoadStrategy = PageLoadStrategy.Normal;
                    if (RunInHeadlessMode())
                    {
                        choptions.AddArguments("--headless");
                        choptions.AddArguments("--disable-gpu");
                        choptions.AddArguments("--window-size=1920,1080");
                    }
                    choptions.AddArgument("--start-maximized");
                    choptions.AddArguments("incognito");
                    choptions.AddArguments("--no-sandbox");
                    choptions.AddUserProfilePreference("download.default_directory", Selenium.UserActions.FileInteractions.DownloadFolderPath);
                    choptions.AddUserProfilePreference("download.prompt_for_download", false);
                    choptions.AddUserProfilePreference("profile.default_content_settings.popups", 0);
                    choptions.AddUserProfilePreference("download.prompt_for_download", false);
                    choptions.AddUserProfilePreference("download.directory_upgrade", true);

                    var experiments = new List<string>();
                    experiments.Add("download-bubble@2");
                    experiments.Add("download-bubble-v2@2");
                    choptions.AddLocalStatePreference("browser", new { enabled_labs_experiments = experiments});
                    ChromeOptions = choptions;
                    Capable = choptions;

### How can we reproduce the issue?

```shell
Code snippet given above

And this happens only in incognito mode
```

### Relevant log output

```shell
In both incognito and normal mode, if the download option is already set in Chrome options then it should work consistently.
```

### Operating System

Windows 10

### Selenium version

3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome incognito 119

### What are the browser driver(s) and version(s) where you see this issue?

Chrome incognito 119

### Are you using Selenium Grid?

Yes we are using both for CI pipeline and local

**Comment by XavierYuste-Atos** [comment]
Hi,
We have detected this problem in our scenarios in our Selenium cucumber Java project.
We have created the issue: 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4619&q=download&can=2
It was detected in chromedriver version 117, but adding the following lines it was solved:
        List<String> enabledLabsExperiments = new ArrayList<>();
        enabledLabsExperiments.add("download-bubble@2");
        enabledLabsExperiments.add("download-bubble-v2@2");
        chromeOptions.setExperimentalOption("localState",prefs);

But now in the version 119 the problem happens again and the previous workaround is not working.

Please, there is some workaround to solve this problem in the incognito mode???
I hope that it can be solved faster
Thanks
Xavier

**Comment by VietND96** [comment]
Hi, can you try to add this args to ChromeOptions, it works at my end with Chrome v119
```java
ChromeOptions options = new ChromeOptions();
options.addArguments("--incognito")
options.addArguments("disable-features=DownloadBubble,DownloadBubbleV2")
```
For who is using Katalon Studio, it would be
```groovy
import com.kms.katalon.core.configuration.RunConfiguration

args = ['--incognito', 'disable-features=DownloadBubble,DownloadBubbleV2']
RunConfiguration.setWebDriverPreferencesProperty('args', args)
```

**Comment by XavierYuste-Atos** [comment]
Hi vietnd96
Many thanks! 
It works for me
Xavi

**Comment by chik145** [comment]
Many Thanks Bro @vietnd96
