### ISSUE TITLE
[🚀 Feature]: Java 21 Virtual Threads

### ISSUE THREAD

**Issue by giuliohome** [SeleniumHQ/selenium#13100]
### Feature and motivation

With Java 21, many frameworks are exploring the adoption of Virtual Threads executors to enhance resource efficiency. 

For example, take a look at Helidon 4. 

It appears that Selenium Executors could also benefit from being ported to Virtual Threads.

### Usage example

Ideally, there should be no change from a usage perspective, given that Virtual Threads leverage preemptive runtime features, in contrast to cooperative coroutines. It appears that under the hood, you should be able to simplify the implementation with a non-blocking style, without encountering the so-called 'color problem' if using async/await.

**Comment by diemol** [comment]
How can we use them when we support Java 11 as minimum version? It'll take at least a year until we move to Java 17 or 21.

**Comment by giuliohome** [comment]
> How can we use them when we support Java 11 as minimum version? It'll take at least a year until we move to Java 17 or 21.

Yes, sure, I think that's expected, of course. 
Thank you.

**Comment by titusfortner** [comment]
Thank you for raising this as a feature request.

Our general policy in most of the bindings is to support a language version until EOL. Java 8 was a little special because of just how many people were avoiding moving off of it, and then we announced we would supporting Java 11 for another year. Since Java 17 does not hit end of life until 2026, though, we aren't going to require 21 before then. When we do, we'll absolutely be implementing the main new feature of Java 21 that will have a positive impact the project, so there is no need to have an open issue reminding of this.

**Comment by giuliohome** [comment]
Cool.
I've wasted too much of my time supporting selenium while working.


Of course I'll remember your answer and I swear I will no longer waste a minute of my time for this project. As far as I'm concerned migrating to a more modern testing framework like Playwright is the only reasonable option.

**Comment by diemol** [comment]
I don't see how our reply could have triggered that reaction from your side. We are happy to understand and listen more to our users so we can learn better what people expect from Selenium.

One important thing to note, Selenium is not a test automation framework, it is a browser automation base library which is normally used for testing. That's an important difference to take into account when thinking about tools that are full fledged testing frameworks. If you are looking for a testing framework, we recommend Selenide.

**Comment by titusfortner** [comment]
I'm confused, was the right answer to leave this issue open for 3 years so you get credit for suggesting it? Or is the expectation that we change our language support policies?

**Comment by titusfortner** [comment]
And because I was curious...
Playwright still supports Java 8 https://github.com/microsoft/playwright-java/blob/main/pom.xml#L46

**Comment by giuliohome** [comment]
> And because I was curious...
Playwright still supports Java 8 https://github.com/microsoft/playwright-java/blob/main/pom.xml#L46

I was not speaking about the client part. We don't even use Java there.

>  so you get credit for suggesting it?

You don't pay me for my time. I don't work for you. In my company with my colleagues, managers and consultants I will say that using selenium for test automation is completely wrong and that playwright is one of the surely much better options. You instead have the power to close my ticket here and more importantly to write ironic comments to insult my efforts to collaborate and suggest with your sarcasm. As I said I have wasted many days to  implement test automation with selenium in my company and to support it till now but now I'm sure that it has been an error and I will remain against the use of this software.
