### ISSUE TITLE
Chrome - Preserve logs upon navigation

### ISSUE THREAD

**Issue by danielagreen** [SeleniumHQ/selenium#1311]
How to capture browser logs after a page navigation?

The test:
Click button trigger writing to browser console + does page navigation

In chrome, there is the option in the Dev Tools: Preserve log upon navigation

![screen shot 2015-11-24 at 5 42 55 pm](https://cloud.githubusercontent.com/assets/8258044/11373109/59fc7568-92d9-11e5-83b7-a484088f4d1c.png)

How to do it in an automation tests with chrome and protractor?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by dexstakker** [comment]
You know what would have rocked?  If YOU had posted the question to the forum on her behalf and linked to it here. Then I wouldn't get excited by seeing the EXACT same question she had and then watch it dead end into another abstract search.
