### ISSUE TITLE
[🐛 Bug]: getting "ConnectionFailedException: JdkWebSocket initial request execution error" while trying to connect selenium grid using proxy configuration

### ISSUE THREAD

**Issue by satya081** [SeleniumHQ/selenium#13118]
### What happened?

My selenium code is in a machine(corporate laptop) and standalone selenium grid is set up in another machine(aws ec2 ubuntu machine)
when i am trying to connect  my selenium grid using proxy configuration from my corporate laptop i am getting ConnectionFailedException: JdkWebSocket initial request execution error

### How can we reproduce the issue?

```shell
try {
                    ChromeOptions options = new ChromeOptions();
                    options.addArguments("--disable-gpu");
                    options.addArguments("--no-sandbox");
                    options.addArguments("--disable-browser-side-navigation");
                    options.addArguments("--disable-dev-shm-usage");
                    options.setAcceptInsecureCerts(true);
                    options.setPageLoadStrategy(PageLoadStrategy.EAGER);
                    Map<String, Object> prefs = new HashMap<>();
                    prefs.put("credentials_enable_service", false);
                    prefs.put("profile.password_manager_enabled", false);
                    prefs.put("profile.default_content_settings.popups", 0);
                    prefs.put("download.prompt_for_download", false);
                    prefs.put("download.default_directory", config.getProperty("path.remote.download"));
                    options.setExperimentalOption("prefs", prefs);
                    options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});
                    capability.setCapability(ChromeOptions.CAPABILITY, options);
                    capability.setBrowserName(CHROME);
                    options.merge(capability);
                    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy-url", portnumber));
                    ClientConfig config = ClientConfig.defaultConfig()
                            .baseUrl(new URL(gridUrl))
                            .authenticateAs(new UsernameAndPassword("username", "pswd"))
                            .proxy(proxy);
                    driver = RemoteWebDriver.builder()
                            .oneOf(options)
                            .config(config)
                            .build();
                }
               catch (Exception e) {
                    logger.error(e.getMessage(), e);
                }
```

### Relevant log output

```shell
2023-11-08 16:18:19 ERROR WebDriverFactory:183 - JdkWebSocket initial request execution error
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'
Driver info: driver.version: unknown
org.openqa.selenium.remote.http.ConnectionFailedException: JdkWebSocket initial request execution error
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.7'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.openSocket(JdkHttpClient.java:256)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:84)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:36)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$3(SeleniumCdpConnection.java:103)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:103)
	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:49)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:191)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:162)
	at org.openqa.selenium.remote.RemoteWebDriverBuilder.build(RemoteWebDriverBuilder.java:371)
	at europa.edit.util.WebDriverFactory.remoteDriver(WebDriverFactory.java:181)
```

### Operating System

Windows 10

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 112.0.5615.49

### Are you using Selenium Grid?

4.15.0

**Comment by pujagani** [comment]
Thank you for the details. https://github.com/SeleniumHQ/selenium/commit/e8c3e9db75b9881eb306cc7830b6638014f4f0c8 might have fixed the issue you are facing. Please try to set your proxy by using the system property `http.proxyHost` and `http.proxyPort`. That will solve the issue you are facing.

**Comment by satya081** [comment]
Could you please send me sample code for this? As i see https://github.com/SeleniumHQ/selenium/commit/e8c3e9db75b9881eb306cc7830b6638014f4f0c8 this is not deployed yet as the latest version is showing 4.15.0 you fixed it in 4.15.2

**Comment by pujagani** [comment]
Selenium 4.15.2 release was done for python only. For Java, it is available in 4.15.0. Please set the system property in Java. One way to do is : 
```
       System.setProperty("http.proxyHost", "localhost");
       System.setProperty("http.proxyPort", "8080");

```

**Comment by satya081** [comment]
> Selenium 4.15.2 release was done for python only. For Java, it is available in 4.15.0. Please set the system property in Java. One way to do is :
> 
> ```
>        System.setProperty("http.proxyHost", "localhost");
>        System.setProperty("http.proxyPort", "8080");
> ```

I am getting same error even doing what you have mentioned. my code snippet.

               try {
                    ChromeOptions options = new ChromeOptions();
                    options.addArguments("--disable-gpu");
                    options.addArguments("--no-sandbox");
                    options.addArguments("--disable-browser-side-navigation");
                    options.addArguments("--disable-dev-shm-usage");
                    options.setAcceptInsecureCerts(true);
                    options.setPageLoadStrategy(PageLoadStrategy.EAGER);
                    Map<String, Object> prefs = new HashMap<>();
                    prefs.put("credentials_enable_service", false);
                    prefs.put("profile.password_manager_enabled", false);
                    prefs.put("profile.default_content_settings.popups", 0);
                    prefs.put("download.prompt_for_download", false);
                    prefs.put("download.default_directory", config.getProperty("path.remote.download"));
                    options.setExperimentalOption("prefs", prefs);
                    options.setExperimentalOption("excludeSwitches", new String[]{"enable-automation"});
                    capability.setCapability(ChromeOptions.CAPABILITY, options);
                    capability.setBrowserName(CHROME);
                    options.merge(capability);
                    System.setProperty("http.proxyHost", "proxyurl");
                    System.setProperty("http.proxyPort", "portnumber");
                    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxyurl", portnumber));
                    ClientConfig config = ClientConfig.defaultConfig()
                            .baseUrl(new URL(gridUrl))
                            .authenticateAs(new UsernameAndPassword("username", "pswd"))
                            .proxy(proxy);
                    driver = RemoteWebDriver.builder()
                            .oneOf(options)
                            .config(config)
                            .build();
                } catch (Exception e) {
                    logger.error(e.getMessage(), e);
                }

Could you please investigate the issue and reopen this ticket please

**Comment by pujagani** [comment]
The system properties point only to the proxy. Please ensure the proxy supports sockets.

**Comment by satya081** [comment]
@pujagani yes proxy supports sockets. the same code was working earlier but not now. could you please investigate and fix the issue. and request you to reopen this ticket. as we don't see any button to reopen it.

**Comment by pujagani** [comment]
I have reverted the changes that caused this. Turns out it was not needed. Setting system property is sufficient to proxy all connections including websocket. Apologies for the regression. The changes reverted will be part of the next release.

**Comment by valfirst** [comment]
@pujagani do you know when the next release is planned? is there a chance to publish a bug-fix release?

**Comment by titusfortner** [comment]
Chrome 120 comes out next week, we are trying to do new releases before production release of Chrome.
