### ISSUE TITLE
[🚀 Feature]: Selenium Manager, add `--force-driver-download` 

### ISSUE THREAD

**Issue by MarcelWilson** [SeleniumHQ/selenium#13110]
### Feature and motivation

In cases where a chromedriver exists in the path, and yet scripts require a specific version (that doesn't match), it would be handy to have the option `--force-driver-download`.

Consider the following...
```
$ ./selenium-manager --browser chrome --browser-version 116.0.5845.96 --debug --force-browser-download
DEBUG	Found chromedriver 117.0.5938.149 in PATH: /Users/me/.local/bin/chromedriver
DEBUG	Required browser: chrome 116.0.5845.96
DEBUG	chrome 116.0.5845.96 already exists
DEBUG	chrome 116.0.5845.96 is available at /Users/me/.cache/selenium/chrome/mac-arm64/116.0.5845.96/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
DEBUG	Required driver: chromedriver 116.0.5845.96
WARN	The chromedriver version (117.0.5938.149) detected in PATH at /Users/me/.local/bin/chromedriver might not be compatible with the detected chrome version (116.0.5845.96); currently, chromedriver 116.0.5845.96 is recommended for chrome 116.*, so it is advised to delete the driver in PATH and retry
INFO	Driver path: /Users/me/.local/bin/chromedriver
INFO	Browser path: /Users/me/.cache/selenium/chrome/mac-arm64/116.0.5845.96/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
```
In the above, we see that the version we want doesn't match the chromedriver found in the `path`.

When there isn't a chromedriver in the `path`, the above command would return the driver found in `.cache` as expected.
However, there isn't an option to force using the `.cache` versions without completely removing `chromedriver` from the `path`.

I propose a switch like `--force-driver-download` could be added that works similar to `--force-browser-download` and return the cached driver.

### Usage example

```
./selenium-manager --browser chrome --browser-version 116.0.5845.96 --debug --force-driver-download

DEBUG	Required driver: chromedriver 116.0.5845.96
DEBUG	chromedriver 116.0.5845.96 already in the cache
INFO	Driver path: /Users/me/.cache/selenium/chromedriver/mac-arm64/116.0.5845.96/chromedriver
INFO	Browser path: /Users/me/.cache/selenium/chrome/mac-arm64/116.0.5845.96/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing

```

**Comment by bonigarcia** [comment]
I agree with this feature request. In fact, I already created an equivalent PR for this some weeks ago (see #12960).

**Comment by titusfortner** [comment]
This will also fix it, without requiring additional configuration: https://github.com/SeleniumHQ/selenium/issues/13128

(and will match the expected behavior for Selenium 5)

**Comment by titusfortner** [comment]
#13159 will address this scenario by default for the next release.
