### ISSUE TITLE
Opera display pop up Console Window Host

### ISSUE THREAD

**Issue by zura44** [SeleniumHQ/selenium#1312]
Hi, 
Currently I am working with webdriver for all browsers. The code & execution is fine in may own local machine. But after I transfer the project bin folder to testing machine, execute Opera will pop up Console Window Host. Is there any difference Opera setting between local machine & server? How to override the pop up as per attachment?

Note : Testing machine
- Windows Server 2012 R2
- 64-bit OS

Thanks.

![image](https://cloud.githubusercontent.com/assets/11734645/11386831/4440cdc8-9360-11e5-90cc-c3034130f30e.png)

![consolewindowhost](https://cloud.githubusercontent.com/assets/11734645/11388456/6f7950b2-9371-11e5-8916-c9b4dd3ddf01.png)

![consolewindowhost2](https://cloud.githubusercontent.com/assets/11734645/11388500/f0c7655a-9371-11e5-9a84-c7bd09cd220b.png)

![consolewindowhost3](https://cloud.githubusercontent.com/assets/11734645/11388503/f5484464-9371-11e5-874a-7d00d9cd94d5.png)

**Comment by barancev** [comment]
Please report this issue to the operadriver tracker.
