### ISSUE TITLE
[🚀 Feature]: Add new locator strategies (ex: by JQuery) and locator functions

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#13138]
### Feature and motivation

Is it possible to add new locator strategies ?

For example, we could have a locator by **JQuery** expression, like it is done by **Cypress** or **Playwright**
`cy.get('.pass-input-placeholder > .input-wrapper > .error-msg > .msg-body > span')`

Also add locator functions, like the ones used by **Cypress**:

```
- parent()
- first()
- next()
- last()
- sibblings()
- children()
```

### Usage example

```
elem = driver.find_element(By.JQUERY, ".pass-input-placeholder > .input-wrapper > .error-msg > .msg-body > span")

parent = elem.parent()
parent.click()
```

**Comment by titusfortner** [comment]
Really what we need is to have examples in each of the bindings for how to extend the locators in whatever way users want.

**Comment by harmin-parra** [comment]
Consider this HTML code with 4 buttons with the same CSS class.

![image](https://github.com/SeleniumHQ/selenium/assets/16239820/e7000d6f-a345-4e62-ac48-cc36eafc82d2)
```
<div class="traversal-buttons">
        <a class="btn btn-default" href="[#](https://example.cypress.io/commands/traversal#)" role="button">Link</a>
        <button class="btn btn-default" type="submit">Button</button>
        <input class="btn btn-default" type="button" value="Input">
        <input class="btn btn-default" type="submit" value="Submit">
</div>
```
This will bring the first button
`elem = driver.find_elements(By.CLASS_NAME, "xxxx").first()`

This will bring the next button()
`elem = driver.find_elements(By.CLASS_NAME, "xxxx").first().next()`

This will bring the last button
`elem = driver.find_elements(By.CLASS_NAME, "xxxx").last()`

This will return the 3 siblings of a button
`siblings = driver.find_elements(By.CLASS_NAME, "xxxx").last().siblings()`

**Comment by titusfortner** [comment]
This specific functionality exists if you use XPATH Axis values, but you would have to implement a wrapper or do metaprogramming to get the methods.
