### ISSUE TITLE
[🐛 Bug]: MSXML2.XMLHTTP60.send results in error

### ISSUE THREAD

**Issue by dcooke570** [SeleniumHQ/selenium#13146]
### What happened?

![Screenshot 2023-11-13 part 1](https://github.com/SeleniumHQ/selenium/assets/150743080/2c3622cd-25d5-4c35-aa1a-bea83b3c9a65)
The code in Yellow per attached screenshot results in Run-time error 80070005. Access is denied in VBA code that is trying to get the latest edge driver version from the Edge URL "https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/"
This routine has worked flawlessly for over the past few years... what happened in the past week?

### How can we reproduce the issue?

```shell
Public Sub UpdateDriver(ByVal DriverType As dType)
Dim EdgeVersion As String
    
    'URLs to the drivers' home pages to which we can grab the curr versions
    Dim URLPath As String
    Select Case DriverType
    Case dType.Chrome
        URLPath = "https://chromedriver.chromium.org/home"
    Case dType.Edge
        URLPath = "https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/"
    End Select
    
    'Grab the current Version # from the driver's webpage
    Dim Doc As New HTMLDocument, DriverVer As String
    With New MSXML2.XMLHTTP60
        .Open "GET", URLPath
        .send
        Doc.body.innerHTML = .responseText
    End With
    DriverVer = getCurrentVersion(Doc, DriverType)
    EdgeVersion = getEdgeCurrentVersion
    
    'DownloadUpdatedDriver DriverVer, DriverType
    If DriverVer <> EdgeVersion Then
        DownloadUpdatedDriver EdgeVersion, DriverType
        ExtractZipAndCopy DriverType
    End If

End Sub
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 10

### Selenium version

v2.0.9.0

### What are the browser(s) and version(s) where you see this issue?

MS Edge Version 119.0.2151.58 

### What are the browser driver(s) and version(s) where you see this issue?

Edge Driver Version 119.0.2151.58

### Are you using Selenium Grid?

no

**Comment by dcooke570** [comment]
Using Microsoft 365 Excel version 2310 (Build 16924.20124)

**Comment by diemol** [comment]
We do not maintain the VBA project, you are probably looking for https://github.com/florentbr/SeleniumBasic
