### ISSUE TITLE
Error: ETIMEDOUT connect ETIMEDOUT

### ISSUE THREAD

**Issue by rafis** [SeleniumHQ/selenium#1314]
I'm receiving following error:

    'Error: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:8190',
    '    at ClientRequest.<anonymous> (/home/dev/selenium-learning/node_modules/selenium-webdriver/http/index.js:174:16)',
    '    at emitOne (events.js:77:13)',
    '    at ClientRequest.emit (events.js:169:7)',
    '    at Socket.socketErrorListener (_http_client.js:259:9)',
    '    at emitOne (events.js:77:13)',
    '    at Socket.emit (events.js:169:7)',
    '    at emitErrorNT (net.js:1253:8)',
    '    at doNTCallback2 (node.js:441:9)',
    '    at process._tickCallback (node.js:355:17)',
    'From: Task: WebDriver.findElements(By.cssSelector("#atfResults"))',
    '    at webdriver.WebDriver.schedule (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)',
    '    at webdriver.WebDriver.findElements (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1002:17)',
    '    at until.elementLocated (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/webdriver/until.js:216:23)',
    '    at /home/dev/selenium-learning/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:720:12',
    '    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)',
    '    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)',
    '    at goog.async.run.processWorkQueue (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)',
    '    at process._tickCallback (node.js:368:9)',
    'From: Task: <anonymous>',
    '    at pollCondition (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2233:16)',
    '    at promise.ControlFlow.goog.defineClass.getSchedule.indent.wait (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2229:9)',
    '    at promise.Promise.goog.defineClass.constructor (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1056:7)',
    '    at new wrappedCtr (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/base.js:2468:26)',
    '    at eval (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2228:14)',
    '    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)',
    '    at promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)',
    '    at goog.async.run.processWorkQueue (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)',
    '    at process._tickCallback (node.js:368:9)',
    'From: Task: Waiting for element to be located By.cssSelector("#atfResults")',
    '    at promise.ControlFlow.goog.defineClass.getSchedule.indent.wait (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2226:17)',
    '    at webdriver.WebDriver.wait (/home/dev/selenium-learning/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:716:21)',
    '    at Object.<anonymous> (/home/dev/selenium-learning/test_webdriver.js:136:8)',
    '    at Module._compile (module.js:435:26)',
    '    at Object.Module._extensions..js (module.js:442:10)',
    '    at Module.load (module.js:356:32)',
    '    at Function.Module._load (module.js:311:12)',
    '    at Module.runMain [as _onTimeout] (module.js:467:10)',
    '    at Timer.listOnTimeout (timers.js:92:15)' ]

How to accomplish with this issue? I'm using
nodejs v4.4.2 64-bit
selenium-webdriver v2.48.2
PhantomJS 1.9.8 Linux 64-bit

I was searching how to increase timeout time, but haven't found solution. Issues can also be on PhantomJS GhostDriver side...

**Comment by vikas23** [comment]
+1 Same for me

**Comment by barancev** [comment]
Please report this issue to the Ghostdriver tracker. As soon as it's not responding the issue must be on the driver side.
