### ISSUE TITLE
[🐛 Bug]: Can't start Live View option with MacOS build in VNC beause PasswordDialog doesn't have username field visible.

### ISSUE THREAD

**Issue by tom17031** [SeleniumHQ/selenium#13144]
### What happened?

I managed to overcome the issue by modyfing the JS file inside the selenium-server.jar file (selenium grid hub 4.13.0).
I found the text: 
`username:"" `
and replaced it with:
`username:"MY_USERNAME"`

So when i am asked for password during live view connection attempt i can type in the password and get authenticated.

The authentication method returned from rfb.js for a MacOS VNC build in server requires two things :
- HTTPS context for selenium grid hub UI because of window.crypto.subtle is not available in HTTP context and subtle.importKey method is used during authorization phase
- username needs to be provided (but there is no username field in PasswordDialog)

Please add username to the password dialog in future selenium grid hub versions at least for authentication method used for MacOS.

### How can we reproduce the issue?

```shell
Run selenium grid hub with HTTPS certificate.

Prepare selenium node which connects to selenium grid with --registration-secret (because when HTTPS is enabled this param is required) and SE_XVFB_START=true env variable set.
The selenium node also need to have websockify setup done.

Run any test with use of the selenium grid hub to point to a MacOS selenium node.
Try to open live view - it will ask for password, even when password is properly put it won't authenticate as username is "" in selenium grid-ui code.
```

### Relevant log output

```shell
I modify this part of code to setup username in order to get properly connected to MacOS VNC.

In line 62:
`newRfb.addEventListener('credentialsrequired', handleCredentials)`

The handleCredentials method fire the PasswordDialog.
PasswordDialog doesnt have username option: https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/grid-ui/src/components/LiveView/PasswordDialog.tsx

I overcome the issue by setting up hardcoded value of my username in line 107:

https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/grid-ui/src/components/LiveView/LiveView.tsx (line 107)

    `rfb.sendCredentials({ username: '', password: password })`
```

### Operating System

Grid started on Ubuntu 22.04, MacOS as selenium node Ventura 13.6 (22G120)

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

Its not relevant, the problem is in grid-ui not able to put username

### Are you using Selenium Grid?

4.13.0

**Comment by diemol** [comment]
Happy to receive a pull request to improve this.

**Comment by tom17031** [comment]
Thank you for quick reaction. 
Basically i think the basic fix could be quite easy to add a input field and property in PasswordDialog file and propagate this data further to the connection. 

I think the MacOS VNC auth falls into ARDauth code on the noVNC side (i can see when event is emitted there is some data that might be needed (username, password))

<img width="603" alt="Screenshot 2023-11-14 at 08 28 29" src="https://github.com/SeleniumHQ/selenium/assets/70779121/b4b3b5ad-a103-4fbf-be43-297c0d2cd40e">

**Comment by diemol** [comment]
@tom17031 would you like to send a PR?

**Comment by tom17031** [comment]
@diemol thanks but I am not very experienced in web development. I can analyse issues but would prefer someone else to fix it.
