### ISSUE TITLE
[🐛 Bug]: Find child elements by xPath

### ISSUE THREAD

**Issue by SidArtem** [SeleniumHQ/selenium#13155]
### What happened?

I try to get children elements with **xPath**=`"//test2"` from elements with **xPath**=`"//test1"`.
Second search returns all elements by **only second xPath**, the first criterion is not taken into account.

I tries to launch code with Css selectors - no problems.

### How can we reproduce the issue?

```shell
var elements1 = driver.FindElements(By.XPath("//test1"));

var elements2 = elements.SelectMany(e => e.FindElements(By.XPath("//test2"))).ToList();
```
```


### Relevant log output

```shell
Returns all elements only with the second search criterion. (not from first finded elements)
```

### Operating System

Windows 10

### Selenium version

.NET 6

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 119.0.6045.124

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105

**Comment by nvborisenko** [comment]
`.//test2` is a correct variant. Seems strange for me as well, but it is how it works.
