### ISSUE TITLE
ExecuteJavaScript does not handle Nullable<T> very well

### ISSUE THREAD

**Issue by chrisblock** [SeleniumHQ/selenium#1316]
*This is an issue in the WebDriver.Support library for .NET.*

Almost immediately after my pull request last time (#1258), I realized that the ```Nullable<T>``` type is a struct, and thus also a value type. One of the checks I added via the pull request will throw when any value type is used. This check should be modified to exclude the ```Nullable<T>``` type, since it does support null values.

**Comment by lukeis** [comment]
it's adequate to just open the pull request and not an issue at the same time :)

(going to close this just so we don't have to when the PR gets merged)
