### ISSUE TITLE
[🐛 Bug]: GeoLocation API does not work when using proxy.

### ISSUE THREAD

**Issue by zubairkhakwani** [SeleniumHQ/selenium#13164]
### What happened?

I have created a test in selenium in which if I set proxy and then try to check my geoLocation thorough any website it fails to get the location and in console I found this error, **mylocation.org/:1 Network location provider at 'https://www.googleapis.com/' : ERR_TUNNEL_CONNECTION_FAILED.
**

and if I remove the proxy it works, also it is only in case on chrome driver, it is working fine on edgeDriver.****

### How can we reproduce the issue?

```shell
Create a test in which use a proxy and try to check geoLocation from any of the website.

https://gps-coordinates.org/my-location.php
https://mylocation.org/

or any other
```

### Relevant log output

```shell
[1700164613.670][DEBUG]: DevTools WebSocket Event: Log.entryAdded (session_id=301C18C9DE1129354DF84D48D27B70BE) D49DF07C461A6E01B8FF26BAE2FA625F {
   "entry": {
      "level": "error",
      "source": "network",
      "text": "Network location provider at 'https://www.googleapis.com/' : ERR_TUNNEL_CONNECTION_FAILED.",
      "timestamp": 1.7001646136687778e+12,
      "url": "https://mylocation.org/"
   }
}
```

### Operating System

Windows 10

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

119.0.6045.160

### What are the browser driver(s) and version(s) where you see this issue?

119.0.6045.105

### Are you using Selenium Grid?

No

**Comment by zubairkhakwani** [comment]
new DriverManager().SetUpDriver(new ChromeConfig(), VersionResolveStrategy.MatchingBrowser);
                    ChromeOptions options = new ChromeOptions();

                    Proxy proxy = new Proxy();
                    proxy.Kind = ProxyKind.Manual;
                    proxy.HttpProxy =
                    proxy.SslProxy = credential.Proxy;

                    options.Proxy = proxy;

                    //stoping WEBRTC from leaking public ip
                    options.AddArguments("--webrtc-ip-handling-policy=disable_non_proxied_udp");
                    options.AddArguments("--force-webrtc-ip-handling-policy=disable_non_proxied_udp");


                    options.AddArguments("enable-strict-powerful-feature-restrictions");
                    options.AddArguments("--start-maximized");

                    var profilePath = credential.UseRemoteSettings ? credential.ProfileDisk : applicattionSettings.Path.BrowserProfile;

                    options.AddArgument(@$"user-data-dir={profilePath}\{email}");
                    options.AddArgument(@$"profile-directory={email2}");

                    options.AddArgument("--disable-blink-features=AutomationControlled");
                    options.SetLoggingPreference(LogType.Driver, LogLevel.All);

                    var driverService = ChromeDriverService.CreateDefaultService();
                    driverService.HideCommandPromptWindow = true;

                    driverService.EnableVerboseLogging = true;

                    driverService.LogPath = @$"D:\logwithproxy.log";
                    driverService.EnableVerboseLogging = true;

                    Driver = new ChromeDriver(driverService, options);

                    NetworkAuthenticationHandler handler = new NetworkAuthenticationHandler()
                    {
                        UriMatcher = d => true,
                        Credentials = new PasswordCredentials(credential.ProxyUserName, credential.ProxyPassword)
                    };

                    var networkInterceptor = Driver.Manage().Network;
                    networkInterceptor.AddAuthenticationHandler(handler);
                    networkInterceptor.StartMonitoring();

                    Driver.Navigate().GoToUrl("https://www.google.com/");

This is the code I am using to start my browser as you see I am using Proxy class to set proxy to my browser. after starting the browser go to this website to under Browser GeoLocation (Collapsibles/Accordion)  click start test, and Allow the permission to check you geo location, the test will be failed and you can see this exception in console `Network location provider at 'https://www.googleapis.com/' : ERR_TUNNEL_CONNECTION_FAILED.`.

If I don't apply the proxy, it works fine.

**Comment by titusfortner** [comment]
Turn on logging and provide the output so we can see what is getting sent to the driver: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by zubairkhakwani** [comment]
> Turn on logging and provide the output so we can see what is getting sent to the driver: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

[logwithproxy.log](https://github.com/SeleniumHQ/selenium/files/13684642/logwithproxy.log)
Log is big, so i attached the file.

**Comment by titusfortner** [comment]
The proxy setup looks correct from the Selenium code standpoint, so I think this has to be an issue with your proxy. I don't think there's anything more we can do in Selenium code for this. I'd check with your proxy documentation, and I'll add some links for where you might ask more information.
