### ISSUE TITLE
[🐛 Bug]: Selenium Manager not working on FreeBSD

### ISSUE THREAD

**Issue by gdonald** [SeleniumHQ/selenium#13161]
### What happened?

I have selenium-webdriver 4.15.0 installed in a Rails application.  I have RSpec configured to use :selenium, which I understand to mean firefox/geckodriver, not chromedriver:

```
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driver = :selenium
    driven_by(driver)
  end
end
```

When I remove the selenium cache, and re-run my system spec, a new chromedriver is downloaded instead of the geckodriver.

```
> tree ~/.cache/selenium
/Users/gd/.cache/selenium
├── chromedriver
│   └── mac-arm64
│       └── 119.0.6045.105
│           └── chromedriver
└── se-metadata.json

4 directories, 2 files

> rm -rf ~/.cache/selenium

> tree ~/.cache/selenium
/Users/gd/.cache/selenium  [error opening dir]

0 directories, 0 files
```

When I run this spec Chrome opens, even though I configured my RSpec for Firefox:

```
> be rspec spec/system/home_spec.rb
.

Finished in 4.49 seconds (files took 2.95 seconds to load)
1 example, 0 failures
```

At this point selenium-webdriver has reinstalled chromedriver even though I configured my RSpec for geckodriver:

```
> tree ~/.cache/selenium
/Users/gd/.cache/selenium
├── chromedriver
│   └── mac-arm64
│       └── 119.0.6045.105
│           └── chromedriver
└── se-metadata.json

4 directories, 2 files
```

How do I get selenium-webdriver to download and use geckodriver instead of chromedriver?

### How can we reproduce the issue?

```shell
Make a Rails app and configure it to use geckodriver.  Please follow the example above.
```

### Relevant log output

```shell
I have no logs, all output is shown above.
```

### Operating System

macOS 14.0

### Selenium version

selenium-webdriver 4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119 

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 119

### Are you using Selenium Grid?

no

**Comment by gdonald** [comment]
Here's a git repo with a README that describes how to reproduce the issue:

https://github.com/gdonald/selenium-webdriver-bug

**Comment by titusfortner** [comment]
Your `driven_by` code is right here:
https://github.com/gdonald/selenium-webdriver-bug/blob/main/test/application_system_test_case.rb#L4

**Comment by gdonald** [comment]
I'm not running the tests in `test`.  As described in my README, I am running `https://github.com/gdonald/selenium-webdriver-bug/blob/main/spec/system/home_spec.rb`.

I have deleted the entire `tests` directory from my repo, and the issue I've described persists.

https://github.com/gdonald/selenium-webdriver-bug

**Comment by titusfortner** [comment]
Turn on `Selenium::WebDriver.logger.level = :debug` and it should show where the request for Chrome is coming from.

**Comment by titusfortner** [comment]
This is why for as much as I like Ruby, I get really frustrated with the Rails approach...

```ruby
    driven_by(driver)
```

is calling
```ruby
RSpec::Rails::SystemExampleGroup#driven_by
```
which calls from `actionpack`:
```ruby
ActionDispatch::SystemTestCase#driven_by
```
which defaults to:
```ruby
    def self.driven_by(driver, using: :chrome, screen_size: [1400, 1400], options: {}, &capabilities)
      driver_options = { using: using, screen_size: screen_size, options: options }

      self.driver = SystemTesting::Driver.new(driver, **driver_options, &capabilities)
    end
```

**Comment by gdonald** [comment]
Ok, so this `using:` argument is new to me.  When I use that I again have control over which browser I invoke.  I've not seen that in any documentation yet, sorry for missing it.

Thanks for the help.

**Comment by gdonald** [comment]
> Turn on `Selenium::WebDriver.logger.level = :debug` and it
> should show where the request for Chrome is coming from.

This works great on Mac and Linux, but not on FreeBSD.

**Comment by titusfortner** [comment]
Can you turn on logging and provide the output?

**Comment by gdonald** [comment]
That's what I'm saying, `Selenium::WebDriver.logger.level = :debug` provides no additional output on FreeBSD like it does on other systems.

I do get this error:

```
Failure/Error: driven_by(:selenium, using: :firefox)

     Selenium::WebDriver::Error::NoSuchDriverError:
       Unable to obtain geckodriver using Selenium Manager; Unable to locate or obtain Selenium Manager binary;  is not a valid file object; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

My geckodriver is in my $PATH:

```
> which geckodriver
/usr/local/bin/geckodriver

> geckodriver --version
geckodriver 0.26.0
```

And I don't see the directory Selenium makes for itself when it downloads the driver for me:

```
> tree ~/.cache/selenium
/home/gd/.cache/selenium  [error opening dir]

0 directories, 0 files
```

**Comment by titusfortner** [comment]
I just looked at the Selenium code, this makes sense, we don't have an "else" statement for non-Linux/Windows/Mac builds.

Are you using custom compiled binaries, or relying on linux binary compatibility mode? Selenium probably should default to linux and leave it up to the user to set compatibility mode if it is a unix system.

You can set an environment variable for `SE_MANAGER_PATH` to the full path equivalent for this on your machine: `~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.15.0/bin/linux/selenium-manager`

**Comment by gdonald** [comment]
I'm using a compiled binary for geckodriver.  I installed it using `pkg install geckodriver`.

I enabled linux binary compatibility mode, but it did not provide any noticeable improvement.

Adding `SE_MANAGER_PATH` gives me a new error message:

```
> SE_MANAGER_PATH=~/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.15.0/bin/linux/selenium-manager be rspec spec/system/home_spec.rb

Selenium::WebDriver::Error::InvalidArgumentError:
            Unrecognised option moz:debuggerAddress
          # ./spec/system/home_spec.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by titusfortner** [comment]
We need to get this sorted still
