### ISSUE TITLE
[🐛 Bug]: DevTools regression. Target.getTargets() returns LinkedHashMap instead of TargetInfo

### ISSUE THREAD

**Issue by vlad8x8** [SeleniumHQ/selenium#13163]
### What happened?

In old devtools versions (e.g. v102) Target.getTargets() was returning proper `List<TargetInfo>`. 
```     
return new Command<>("Target.getTargets", params.build(), ConverterFunctions.map("targetInfos", new com.google.common.reflect.TypeToken<java.util.List<org.openqa.selenium.devtools.v102.target.model.TargetInfo>>() {}.getType()));
```
Currently, it returns `List<LinkedHashMap>`
```
return new Command<>("Target.getTargets", Map.copyOf(params), ConverterFunctions.map("targetInfos", java.util.List.class));
```

we are getting ClassCastException

### How can we reproduce the issue?

```java
package org.example;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.v119.target.Target;
import org.openqa.selenium.devtools.v119.target.model.TargetInfo;

import java.util.Optional;

public class Main {
    public static void main(String[] args) {
        TargetInfo targetInfo = new ChromeDriver().getDevTools().send(Target.getTargets(Optional.empty())).get(0);
    }
}
```

### Relevant log output

```shell
Exception in thread "main" java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.openqa.selenium.devtools.v119.target.model.TargetInfo (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.openqa.selenium.devtools.v119.target.model.TargetInfo is in unnamed module of loader 'app')
```

### Operating System

Windows 10

### Selenium version

Java 4.15

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

se:cdpVersion -> 119.0.6045.160

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
@joerg1985 this came from your Guava work I believe, I had a similar problem with Selenium examples repo code. I don't remember if I raised an issue for it.

**Comment by vlad8x8** [comment]
Thanks for reply @titusfortner 
Can we just roll back back `return` statement to the previous version?

**Comment by joerg1985** [comment]
@vlad8x8 could you check agains the nightly version? I think this should be fixed in feece00

@titusfortner i do not remember there was an issue to this. I saw this could happen while fixing #13109.

**Comment by vlad8x8** [comment]
Yes, fixed in the current Nightly.
When could this be released?

**Comment by titusfortner** [comment]
I'm trying to make sure we get releases between the early stable and the stable release dates for each version of Chrome: https://chromiumdash.appspot.com/schedule

I'm closing since it is fixed in trunk. Thanks for reporting this.
