### ISSUE TITLE
[🐛 Bug]: Net core 6 C# Selenium.WebDriver not working

### ISSUE THREAD

**Issue by Y2KMAX3000** [SeleniumHQ/selenium#13168]
### What happened?

Hi, When I run the project, It showed this error could not copy the file selenium-manager.exe

### How can we reproduce the issue?

```shell
- Created a project in NetCore 6 C# 
- Implemented a functionality for to open a browser with Selenium.WebDriver.Driver.Navigate().GoToUrl("www.google.com");
```

### Relevant log output

```shell
could not copy the file selenium-manager.exe
```

### Operating System

Windows 11

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Firefox

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver.exe

### Are you using Selenium Grid?

no

**Comment by nvborisenko** [comment]
@Y2KMAX3000 during project's build stage this file is being copied to your output directory. There are many reasons why a file couldn't be copied to destination.

Can you please run `dotnet build -bl:build.binlog`? And then share `build.binlog` file?

**Comment by Y2KMAX3000** [comment]
> @Y2KMAX3000 during project's build stage this file is being copied to your output directory. There are many reasons why a file couldn't be copied to destination.
> 
> Can you please run `dotnet build -bl:build.binlog`? And then share `build.binlog` file?

Hi @nvborisenko I run the command dotnet build -bl:build.binlog c:\tmp\ddd.binlog, but It returns the error
Versión de MSBuild 17.8.3+195e7f5a3 para .NET
Excepción al leer el archivo de registro: Unable to read beyond the end of the stream.

**Comment by nvborisenko** [comment]
You ran `dotnet build -bl:build.binlog c:\tmp\ddd.binlog`, try this: `dotnet build -bl:c:\tmp\ddd.binlog`

**Comment by Y2KMAX3000** [comment]
OK I hace the file, How can I pass It?

**Comment by Y2KMAX3000** [comment]
<img width="706" alt="SeleniumConsoleError" src="https://github.com/SeleniumHQ/selenium/assets/26634367/a3dfad9e-38b1-42f6-b2bc-39e02cb07d7e">
@nvborisenko I captured this image.

**Comment by nvborisenko** [comment]
@Y2KMAX3000 you can copy the file to clipboard, and paste here as you did it with image.

**Comment by nvborisenko** [comment]
Doesn't matter, the issue is:

```
MSB3030: Could not copy the file 'file' because it was not found.
```

Somebody doesn't like `selenium-manager.exe` at `C:\Users\.....\selenium-manager.exe` path, and just deleted it. Most likely it is antivirus.

Related to: https://github.com/SeleniumHQ/selenium/issues/12935

**Comment by Y2KMAX3000** [comment]
> Doesn't matter, the issue is:
> 
> ```
> MSB3030: Could not copy the file 'file' because it was not found.
> ```
> 
> Somebody doesn't like `selenium-manager.exe` at `C:\Users\.....\selenium-manager.exe` path, and just deleted it. Most likely it is antivirus.
> 
> Related to: #12935

Ok, in this case for the moment it doesn´t solution, thank for your help

**Comment by nvborisenko** [comment]
So you can prove that the `C:\Users\.....\selenium-manager.exe` doesn't exist on you machine? And did somebody delete it by some reason?

**Comment by Y2KMAX3000** [comment]
Correct the file doesn´t exist in the path, I do it nothing for delete this file

**Comment by nvborisenko** [comment]
Then somebody else deleted it (antivirus?). We are sure that exe file is a part of nuget package: https://nuget.info/packages/Selenium.WebDriver/4.15.0

https://github.com/SeleniumHQ/selenium/issues/12935 should help to be more friendly to antiviruses. As temporary solution you can add this file to exceptions in your antivirus.

You also can try cleaning nuget cache and download the package again. Just delete `C:\Users\...\.nuget\packages\selenium.webdriver` directory and build a project.

The following content you should see after the package restoring:
```
│   .nupkg.metadata
│   .signature.p7s
│   icon.png
│   README.md
│   selenium.webdriver.4.15.0.nupkg
│   selenium.webdriver.4.15.0.nupkg.sha512
│   selenium.webdriver.nuspec
│
├───build
│       Selenium.WebDriver.targets
│
├───buildTransitive
│       Selenium.WebDriver.targets
│
├───lib
│   └───netstandard2.0
│           WebDriver.dll
│           WebDriver.xml
│
└───manager
    ├───linux
    │       selenium-manager
    │
    ├───macos
    │       selenium-manager
    │
    └───windows
            selenium-manager.exe
```
