### ISSUE TITLE
[🚀 Feature]: Ability to unsubscribe from CDP events

### ISSUE THREAD

**Issue by boris-petrov** [SeleniumHQ/selenium#13160]
### Feature and motivation

Right now we can subscribe for events which is awesome!

```rb
devtools = Capybara.current_session.driver.browser.devtools
devtools.network.enable
devtools.network.on(:web_socket_frame_sent) { |params| puts params }
```

However, it's not possible to unsubscribe from these events (something like an `off` method).

### Usage example

Perhaps an `off` method similar to `on`:

```rb
devtools = Capybara.current_session.driver.browser.devtools
devtools.network.enable
callback = lambda { |params| puts params }
devtools.network.on(:web_socket_frame_sent, lambda)
devtools.network.off(:web_socket_frame_sent, lambda)
```

**Comment by titusfortner** [comment]
@pujagani does Java support unsubscribing from events, yet?

**Comment by boris-petrov** [comment]
@titusfortner sorry, I should have mentioned - in my case the language is Ruby. I don't know if the rest of the languages have support for unsubscription.

**Comment by titusfortner** [comment]
@boris-petrov yes I know, but Puja has been the one working the most on our upcoming BiDi implementations in Java and I'm curious how (if) Java is handling this. We may not add support for it in Ruby to Chrome DevTools, but I do think we need to be able to support it for the WebDriver BiDi spec implementation.

**Comment by pujagani** [comment]
This is where the closeable part comes in from the Java end. Where we unsubscribe from the events of the module when `close()` gets called. Also, if the user has access to the BiDi object (which handles the underlying command sending etc), there is an unsubscribe method which internally calls the W3C BiDi unsubscribe method https://w3c.github.io/webdriver-bidi/#command-session-unsubscribe.

**Comment by joerg1985** [comment]
I think it would be nice to unsubscribe from single events. The `BiDi` has a `public <X> void clearListener(Event<X> event) {` which is missing for the `DevTools`. So are there any reasons not to add this method to the `DevTools` too?

Another option would be to return a `Closable` when calling `DevTools.addListener` to detach the listener, when `Closable.close` is called. This would allow to remove the added listener instead of all for a specific event.

What option would you prefere?

**Comment by pujagani** [comment]
I think for Java, we can do something similar to what BiDi already has. But it depends on what the user is looking for.

**Comment by titusfortner** [comment]
@p0deje how hard would it be to implement this in Ruby? I'm more interested in our BiDi implementation than CDP, obviously.

**Comment by p0deje** [comment]
@titusfortner It should be fairly straightforward, we just need to clear `@devtools.callbacks` properly which is simply a hash of event => listeners. I'm not sure what the API should look like for this. Which looks more reasonable?

**Option 1**

```ruby
listener = devtools.network.on(:web_socket_frame_sent) { |params| puts params }
listener.close
```

**Option 2**

```ruby
callback = ->(params) { puts params }
devtools.network.on(:web_socket_frame_sent, &callback)
devtools.network.off(:web_socket_frame_sent, &callback)
```

**Option 3**

```ruby
callback = ->(params) { puts params }
devtools.network.on(:web_socket_frame_sent, &callback)
devtools.network.events[:web_socket_frame_sent].delete(callback)
devtools.network.events[:web_socket_frame_sent].clear # remove all
```
