### ISSUE TITLE
[🐛 Bug]: There are still some leftovers from the HtmlUnit removal

### ISSUE THREAD

**Issue by rbri** [SeleniumHQ/selenium#13171]
### What happened?

Looks like there are some leftovers from [java] remove the unused htmlunit-driver from the unit tests (#12849).

* "net.sourceforge.htmlunit:htmlunit-core-js:2.70.0" is still referenced from some bzl scripts as dependency
* java\test\org\openqa\selenium\atoms\CompiledAtomsNotLeakingTest.java is base on core-js but the referenced RESOURCE_PATH = "/org/openqa/selenium/atoms/execute_script.js" no longer exists
* java\test\org\openqa\selenium\atoms\InputAtomsTest.java is base on core-js but the referenced RESOURCE_PATH = "/org/openqa/selenium/atoms/atoms_inputs.js" no longer exists

### How can we reproduce the issue?

```shell
* verify if the tests (CompiledAtomsNotLeakingTest.java, InputAtomsTest.java) are still part of the test suite and passing
```

### Relevant log output

```shell
nothing
```

### Operating System

any

### Selenium version

any

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
Thank you for reporting and providing the issue. Would you like to send a PR and help contribute? :)

**Comment by rbri** [comment]
Sorry i really have no time to work on that - maybe @joerg1985 who did the original pr for removing has an idea why we still have this dependency.

**Comment by joerg1985** [comment]
I will take care of this, as soon as i find the time.

**Comment by titusfortner** [comment]
@diemol did that PR fix this issue?

**Comment by rbri** [comment]
@titusfortner sorry but the pr updates the htmlunit dependencies instead of removing it

And btw: Happy new year to you all

**Comment by joerg1985** [comment]
@rbri i think these files are generated by bazel at build time and should be in place as soon as the tests are running:

https://github.com/SeleniumHQ/selenium/blob/b2a84481940925193f5fb544385b28f58f272ace/java/test/org/openqa/selenium/atoms/BUILD.bazel#L4-L16

After running `bazel test --cache_test_results=no --test_size_filters=small grid java/...` they are generated:

![image](https://github.com/SeleniumHQ/selenium/assets/16140691/ee3fa9ca-bf3b-44e8-a704-93ab50c27a2d)

**Comment by rbri** [comment]
@joerg1985 can you please attach a version of the two files - to give me a chance to understand what is inside

**Comment by rbri** [comment]
ok, i see having this dependency to htmlunit-core-js still makes sense.
I think we can close this.

@joerg1985 / @diemol do you like to close or should i do?
