### ISSUE TITLE
[🐛 Bug]: Nothing happens after a click

### ISSUE THREAD

**Issue by JanardhanGN91** [SeleniumHQ/selenium#13178]
### What happened?

After upgrading to the new version of selenium from 4.10.0 to 4.13.0, noticed that some of the clicks are not working in the automation suite. Click is shown as successful but nothing happens i.e. dialog box which has to be opened after a click is not opened.
Tried upgrading to 4.14 and 4.15 but it didn't help. Also, I tried clicking multiple times but that doesn't help too.

### How can we reproduce the issue?

```shell
With the new versions of selenium, I am hoping that others also would have faced this strange issue.
```

### Relevant log output

```shell
I get No such element exception after click is made. as the element is not appearing after a click
```

### Operating System

Windows 10 Enterprise for Virtual Desktops

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

119.0.6045.160

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 119

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Most likely this is an issue with an updated chromedriver version, not a Selenium version, can you rule that out for us?

**Comment by JanardhanGN91** [comment]
Yes, same code runs fine in edge... It doesn't in Chrome...   I also tried using different versions of CFT binary and corresponding chrome drivers but same problem persists..
