### ISSUE TITLE
[🐛 Bug]: Setting download directory confilicts with options.enable_downloads

### ISSUE THREAD

**Issue by sarushili0430** [SeleniumHQ/selenium#13170]
### What happened?

I wanted to set my download directory arbitrarily by using options.add_experimental_option, but it conflicts with options.enable_downloads and disables the download.

### How can we reproduce the issue?

```shell
##Everything is same besides as below:
options = Options()
options.enable_downloads = True
prefs = {'download.default_directory' : DOWNLOAD_DIR}
options.add_experimental_option('prefs', prefs)
```

### Relevant log output

```shell
POST http://localhost:60156/session/bb272c262dfa5f9468948d7efd94746a/element {"using": "css selector", "value": "[id=\"pkx02201:ch:appendList:0:j_idt588\"]"}
Remote response: status=200 | data={"value":{"element-6066-11e4-a52e-4f735466cecf":"93B65B9ABD8910DD7A3F9CEEA177D8C4_element_11555"}} | headers=HTTPHeaderDict({'Content-Length': '98', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:60156/session/bb272c262dfa5f9468948d7efd94746a/element/93B65B9ABD8910DD7A3F9CEEA177D8C4_element_11555/click {}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```

### Operating System

Windows 11

### Selenium version

4.15.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 119.0.6045.160

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105	

### Are you using Selenium Grid?

No

**Comment by titusfortner** [comment]
Yes, you can pick the location and manage the files yourself, or you can enable downloads and let Selenium do it, you can't have both.

Also note that downloads only work when used with the Grid and a remote webdriver.
