### ISSUE TITLE
file upload not stable on Windows

### ISSUE THREAD

**Issue by haonoy** [SeleniumHQ/selenium#1318]
Selenium-server: 2.48.2
Hub OS : Mac 10.10.5
Node OS : Windows 10
Browser : Firefox v42, Chrome v46

I remote browser from Mac to Mac for testing file upload - it's ok. And I try to remote browser from Mac to Windows 10 - have a problem, the first scenario file upload is ok but next scenario file upload does nothing.

I use the following code:
<pre>
Capybara.register_driver driver_type do |app|
    config = {
        :browser => :remote, 
        :url => "http://localhost:4444/wd/hub", 
        :desired_capabilities => cap
    }
    driver = Capybara::Selenium::Driver.new(app, config)
    driver.browser.file_detector = lambda do |args|
        str = args.first.to_s
        str if File.exist?(str)
    end
end
</pre>

Step definition:

<pre>
Then (/^add file "([^"]*)"$/) do |file|
    page.attach_file(locator, example_path_file)
end
</pre>

Example feature:

<pre>
Feature: Test

Scenario: Add file
    Given login by username with password
    Then add file "abc.pdf"
    Then logout

Scenario: Remove file
    Given login by username with password
    Then add file "123.pdf"
    Then remove file "123.pdf"
    Then logout
</pre>

**Comment by p0deje** [comment]
Can you provide a test script using plain selenium-webdriver gem that shows the error?

**Comment by haonoy** [comment]
@p0deje this error:

<pre>
Then add file "123.pdf"

    unknown error: path is not absolute: /Users/test/file/123.pdf
    (Session info: chrome=46.0.2490.86)
    (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 9 milliseconds
    Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
    System info: host: ‘……...', ip: ‘……...', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_66'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\test\AppData\Local\Temp\scoped_dir2592_8273},
    takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false,
    version=46.0.2490.86, platform=XP, browserConnectionEnabled=false, nativeEvents=true,
    acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, 
    takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 46726f914aa41dccc50c784246646e17 (org.openqa.selenium.WebDriverException) (Selenium::WebDriver::Error::UnknownError)
    [remote server] sun.reflect.GeneratedConstructorAccessor17():-1:in `newInstance'
    [remote server] sun.reflect.DelegatingConstructorAccessorImpl():-1:in `newInstance'
    [remote server] java.lang.reflect.Constructor():-1:in `newInstance'
    [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):206:in `createThrowable'
    [remote server] org.openqa.selenium.remote.ErrorHandler(ErrorHandler.java):158:in `throwIfResponseFailed'
    [remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):647:in `execute'
    [remote server] org.openqa.selenium.remote.RemoteWebElement(RemoteWebElement.java):326:in `execute'
    [remote server] org.openqa.selenium.remote.RemoteWebElement(RemoteWebElement.java):121:in `sendKeys'
    [remote server] sun.reflect.GeneratedMethodAccessor24():-1:in `invoke'
    [remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
    [remote server] java.lang.reflect.Method():-1:in `invoke'
    [remote server] org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1(EventFiringWebDriver.java):334:in `invoke'
    [remote server] com.sun.proxy.$Proxy2():-1:in `sendKeys'
    [remote server] org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement(EventFiringWebDriver.java):357:in `sendKeys'
    [remote server] sun.reflect.GeneratedMethodAccessor24():-1:in `invoke'
    [remote server] sun.reflect.DelegatingMethodAccessorImpl():-1:in `invoke'
    [remote server] java.lang.reflect.Method():-1:in `invoke'
    [remote server] org.openqa.selenium.remote.server.KnownElements$1(KnownElements.java):64:in `invoke'
    [remote server] com.sun.proxy.$Proxy3():-1:in `sendKeys'
    [remote server] org.openqa.selenium.remote.server.handler.SendKeys(SendKeys.java):50:in `call'
    [remote server] org.openqa.selenium.remote.server.handler.SendKeys(SendKeys.java):1:in `call'
    [remote server] java.util.concurrent.FutureTask():-1:in `run'
    [remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):176:in `run'
    [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
    [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
    [remote server] java.lang.Thread():-1:in `run'
</pre>

**Comment by p0deje** [comment]
How do you calculate `example_path_file`? The paths are should be different for Unix-based systems and Windows (e.g. `/Users/test/file/123.pdf` for Unix and `C:\\Users\test\file\123.pdf` for Windows).

Can you provide a test script to reproduce the issue?

**Comment by haonoy** [comment]
@p0deje I use <code>page.attach_file(locator, Dir.pwd + filename)</code> but why the first scenario can upload file and passed? if I run test by scenario name (cucumber -n) - it's ok.

**Comment by p0deje** [comment]
@haonoy I have no idea, but I cannot say anything specific until there is some test script that I can run locally to reproduce the issue.

**Comment by haonoy** [comment]
@p0deje Thank you for your answer. I try using path of file for Windows, it passed all.

**Comment by GreatFireWall** [comment]
Hello, the same problem to me.
my c# code:
`var upload = driver.FindElement(By.XPath("//*[@id=\"upload-profile-picture\"]"));
 upload?.SendKeys("‪E:\\images\\20130608233759.png");`

it throw exception "unknown error: path is not absolute"
And what's the right format for windows absolute path ?
