### ISSUE TITLE
[🐛 Bug]: NoSuchElementException in Chrome Version 119.

### ISSUE THREAD

**Issue by manikumarnune123** [SeleniumHQ/selenium#13180]
### What happened?

I am encountering an issue with the FindElement function in Selenium after upgrading to Chrome version 119. Previously, the automation worked seamlessly in Chrome 105, and even with the latest Selenium version (4.15.0), the problem persists in Chrome 119. The issue is specific to an internal website, as automating Google Search with Chrome 119 functions properly. I am in the process of reporting this bug on the Selenium community channel. Unfortunately, I cannot provide details about the specific website due to confidentiality reasons.

<ItemGroup>
  <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
  <PackageReference Include="NUnit" Version="3.12.0" />
  <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
  <PackageReference Include="Selenium.Support" Version="3.141.0" />
  <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
</ItemGroup>

### How can we reproduce the issue?

```shell
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System;
using System.Threading;

namespace TestCode
{
    [TestFixture]
    public class TestRunner
    {
        IWebDriver driver = new ChromeDriver();
        static WebDriverWait wait;

        [Test]
        public void SampleTest()
        {
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(20));
            var TestPageUrl = "https://" + System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).HostName.ToString() + "/WebRH?TraceMode=15";
            driver.Navigate().GoToUrl(TestPageUrl);
            driver.Manage().Window.Maximize();
            Thread.Sleep(5000);
            wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementIsVisible(By.XPath("//iframe")));
            driver.SwitchTo().Frame(0);
            driver.FindElement(By.Id("username")).SendKeys("JohnDoe");
            driver.FindElement(By.Id("password")).SendKeys("Password");
            driver.FindElement(By.Id("loginFormSubmit")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.CssSelector("[data-tif-id='Button_21']")).Click();
        }
      
    }
}
```

### Relevant log output

```shell
Message: 
OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"[data-tif-id='Button_21']"}
  (Session info: chrome=119.0.6045.160)

  Stack Trace: 
RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
RemoteWebDriver.FindElement(String mechanism, String value)
```

### Operating System

All

### Selenium version

Any

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome - 119

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Does it happen in Chrome 118? What if you try Firefox?

**Comment by manikumarnune123** [comment]
@diemol Same issue observed in Firefox 119 as well. But issue got resolved with a page refresh(**_driver.Navigate().Refresh();_**). I think still this is an issue in chrome 119 version.

**Comment by diemol** [comment]
OK. You should verify if it really is an issue with Chrome 119 and that it works with Chrome 118. Then you should report it to the Chrome folks. I will leave you the link for that below.
