### ISSUE TITLE
[🚀 Feature]: make Json (de-)serialization more strict

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13189]
### Feature and motivation

The Json (de-)serialization is currently using reflection to access the toJson / fromJson methods.
Instead of reflection two interfaces could be used ensure these methods are in place.
In Java 9 these methods can be `protected` to have them not externally visible.

### Usage example

This should show a compiler error in cases where we call the Json serialization for object that do not support it e.g. #13184.
As a bonus the use of reflection for Json (de-)serialization could be removed.

**Comment by vlad8x8** [comment]
> In Java 9 these methods can be protected

Java 11 is Selenium's minimum version now
https://www.selenium.dev/blog/2023/java-8-support/
