### ISSUE TITLE
[🐛 Bug]: face "not connected to DevTools"

### ISSUE THREAD

**Issue by Chieh123** [SeleniumHQ/selenium#13185]
### What happened?

when set chrome-options --headless=new,  --disable-gpu, and --single-process together, will get error `WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)`

### How can we reproduce the issue?

```shell
# use chrome(119.0.6045.105), chrome driver(119.0.6045.105), selenium(4.15.2), and python(3.11) in mac(13.5)

from selenium import webdriver
from selenium.webdriver.chrome import options

opt.add_argument("--disable-gpu")
opt.add_argument("--single-process")
opt.add_argument("--headless=new")
driver = webdriver.Chrome(options=opt)
driver.get("https://www.google.com/")
# Getting current URL source code
get_title = driver.title

# Printing the title of this URL
print(get_title)
driver.quit()
```

### Relevant log output

```shell
this is useful information
this is a warning
this is detailed debug information
Selenium Manager binary found at: /Users/xxx/python_virtualenvs/oath_tools/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager
Executing process: /Users/xxx/python_virtualenvs/oath_tools/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug --output json
Found chromedriver 119.0.6045.105 in PATH: /usr/local/bin/chromedriver
chrome detected at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Output: "Google Chrome 119.0.6045.159 "
Detected browser: chrome 119.0.6045.159
Required driver: chromedriver 119.0.6045.105
Driver path: /usr/local/bin/chromedriver
Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Using driver at: /usr/local/bin/chromedriver
Started executable: `/usr/local/bin/chromedriver` in a child process with pid: 86336
```

### Operating System

mac(13.5)

### Selenium version

4.15.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 119.0.6045.105

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105

### Are you using Selenium Grid?

NO

**Comment by diemol** [comment]
The code provided does not match the log.

**Comment by Chieh123** [comment]
only add log setting in the code, the following are the code i ran, and the logs i get
```
from selenium import webdriver
# from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome import options

import logging


logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)

handler = logging.FileHandler("/Users/llin01/Desktop/selenium.txt")
logger.addHandler(handler)

logging.getLogger('selenium.webdriver.remote').setLevel(logging.WARN)
logging.getLogger('selenium.webdriver.common').setLevel(logging.DEBUG)

logger.info("this is useful information")
logger.warning("this is a warning")
logger.debug("this is detailed debug information")
opt = options.Options()
opt.add_argument("--disable-gpu")
opt.add_argument("--single-process")
opt.add_argument("--headless=new")
driver = webdriver.Chrome(options=opt)

driver.get("https://www.google.com/")
# Getting current URL source code
get_title = driver.titlep

# Printing the title of this URL
print(get_title)
driver.quit()
```
<img width="930" alt="Screenshot 2023-11-24 at 4 49 11 PM" src="https://github.com/SeleniumHQ/selenium/assets/18227899/91736729-6747-4182-b49f-69b8ef3f99f7">
<img width="1660" alt="Screenshot 2023-11-24 at 4 49 59 PM" src="https://github.com/SeleniumHQ/selenium/assets/18227899/b9beba52-d1fa-435b-8d90-7edcf7fbb08d">

**Comment by titusfortner** [comment]
Hmm, these logs do not include the place where the exception happens, though

* You do not need to disable gpu (https://bugs.chromium.org/p/chromium/issues/detail?id=737678)
* Does it work if you do not set single-process? Is there a reason you have to set single process?

**Comment by Chieh123** [comment]
hi, thank you for your suggestions.
Actually, my case is take a screenshot in container. I want the setting in container and local.
your suggestion is worked. However, i face another problem related to `DevToolsActivePort` in the container.
I follow https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35 to fix this, but i face 
```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: crashed.
  (timeout: Timed out receiving message from renderer: 60.000)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'luckycat-green--development-tp2-5c9987cbf7-xx9vs', ip: '10.238.120.85'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-477.21.1.el8_8.x86_64', java.version: '11.0.19'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--start-maximized, --start-fullscreen, --window-size=1200,1440, --disable-gpu, --disable-extensions, --no-sandbox, --force-device-scale-factor=1, --disable-dev-shm-usage, --disable-setuid-sandbox, --disable-gpu-sandbox, --headless=new, --remote-debugging-pipe], binary: /usr/bin/google-chrome, extensions: []}, goog:loggingPrefs: org.openqa.selenium.logging..., pageLoadStrategy: eager}]}]
```
do you have any suggestion?

**Comment by diemol** [comment]
This is confusing because the error you post now is different. It also shows that you are running now on Linux instead of macOS. You are now probably facing the issue shown on the Chromium bugs link. There is not much we can do there. 

I suggest going to the Chromium bug link and sharing a way to reproduce the issue so they can give you instructions to get it working.

I will leave a few links below where you can ask questions.

**Comment by titusfortner** [comment]
Duplicate of #12841
