### ISSUE TITLE
[🐛 Bug]: Unable to obtain chromedriver using Selenium Manager

### ISSUE THREAD

**Issue by gurdahari** [SeleniumHQ/selenium#13188]
### What happened?

i cannot enter to google with chromedriver i didnt find any answer selenium site 

### How can we reproduce the issue?

```shell
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
s = Service(r'C:\Users\gurda\Desktop\chromedriver-win64')
driver = webdriver.Chrome(service=s)
driver.get("https://www.google.co.il/")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\selenium_manager.py", line 96, in driver_location
    result = self.run(args)
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\selenium_manager.py", line 121, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json.
The chromedriver version cannot be discovered
```

### Operating System

windows 10

### Selenium version

python / pycharm community 2021

### What are the browser(s) and version(s) where you see this issue?

119.0.6045.160 chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 119.0.6045.160 

### Are you using Selenium Grid?

4.15.2

**Comment by diemol** [comment]
Could you please add logging and share the output?
https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by gurdahari** [comment]
> Could you please add logging and share the output? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

How i do it?

**Comment by diemol** [comment]
Well, please check the link and instructions for every language are there.

**Comment by gurdahari** [comment]
> Well, please check the link and instructions for every language are there.

ididnt understand what to do i just saw  a code but i dont know how it connect to my problem, sorry im new here im just want to know how open the website with selenium

**Comment by titusfortner** [comment]
Is there a reason you are downloading and specifying the location of the driver? Selenium should work without your needing to do that.

Once you have downloaded & specified it in the service class, though, the error does not make sense, because it shouldn't be calling Selenium Manager.

Run this and send results:
```py
import logging
from selenium import webdriver

logging.getLogger('selenium').setLevel(logging.DEBUG)
driver = webdriver.Chrome()
driver.quit()
```

**Comment by Maytham-MJ** [comment]
The issue you're encountering seems to be related to an incorrect setup or invocation of the ChromeDriver with Selenium. Here are a few steps and the corrected code to address this issue:

Steps to Fix the Issue:
Ensure ChromeDriver Compatibility: Verify that the ChromeDriver version you are using is compatible with the Chrome browser version installed on your system. In your case, both are version 119.0.6045.160, which should be compatible.

Correct Path to ChromeDriver: Ensure the path to the ChromeDriver executable is correctly specified. If you've placed chromedriver.exe directly on your desktop, the path should include the executable name.

Update Selenium if Needed: Make sure you have a recent version of Selenium installed, as older versions may not support the latest browser and driver versions.

Check Execution Permissions: Ensure that the chromedriver.exe file has the necessary execution permissions.


```import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

# Ensure the path includes the 'chromedriver.exe' at the end
chromedriver_path = r'C:\Users\gurda\Desktop\chromedriver-win64\chromedriver.exe'
service = Service(chromedriver_path)

driver = webdriver.Chrome(service=service)
driver.get("https://www.google.co.il/")```




Additional Tips:
If you're still encountering issues, try downloading the ChromeDriver again from the [official site](https://sites.google.com/a/chromium.org/chromedriver/).
Make sure no antivirus or firewall settings are blocking the execution of the ChromeDriver.

**Comment by titusfortner** [comment]
@Maytham-MJ please do not paste Chat-GPT answers to issues in this repo..

**Comment by gurdahari** [comment]
> Is there a reason you are downloading and specifying the location of the driver? Selenium should work without your needing to do that.
> 
> Once you have downloaded & specified it in the service class, though, the error does not make sense, because it shouldn't be calling Selenium Manager.
> 
> Run this and send results:
> 
> ```python
> import logging
> from selenium import webdriver
> 
> logging.getLogger('selenium').setLevel(logging.DEBUG)
> driver = webdriver.Chrome()
> driver.quit()
> ```
Here the result for the code you sent : 

```shell
Traceback (most recent call last):
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\selenium_manager.py", line 96, in driver_location
    result = self.run(args)
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\selenium_manager.py", line 121, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json --debug.
The chromedriver version cannot be discovered
```

During handling of the above exception, another exception occurred:

```shell
Traceback (most recent call last):
  File "C:/Users/gurda/AppData/Roaming/JetBrains/PyCharmCE2021.2/scratches/scratch_33.py", line 5, in <module>
    driver = webdriver.Chrome()
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unsuccessful command executed: C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json --debug.
The chromedriver version cannot be discovered
; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

```

**Comment by gurdahari** [comment]
Someone can help ?

**Comment by diemol** [comment]
>The chromedriver version cannot be discovered

@bonigarcia do you know if that message comes from Selenium Manager?

**Comment by bonigarcia** [comment]
Yes, that error message comes from Selenium Manager. It happens when the driver (chromedriver, in this case) version discovered by Selenium Manager is empty. This version is found by requesting the CfT endpoints. So, I'm guessing there is some kind of connectivity issue here. Having the complete Selenium Manager logs would help to trace it.

**Comment by gurdahari** [comment]
so, what 




> Yes, that error message comes from Selenium Manager. It happens when the driver (chromedriver, in this case) version discovered by Selenium Manager is empty. This version is found by requesting the CfT endpoints. So, I'm guessing there is some kind of connectivity issue here. Having the complete Selenium Manager logs would help to trace it.

so what can i do now?

**Comment by gurdahari** [comment]
> Yes, that error message comes from Selenium Manager. It happens when the driver (chromedriver, in this case) version discovered by Selenium Manager is empty. This version is found by requesting the CfT endpoints. So, I'm guessing there is some kind of connectivity issue here. Having the complete Selenium Manager logs would help to trace it.

now the error code changed to 

Traceback (most recent call last):
  File "C:\Users\gurda\AppData\Roaming\JetBrains\PyCharmCE2023.2\scratches\scratch_34.py", line 2, in <module>
    from selenium import webdriver
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\__init__.py", line 19, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\chrome\webdriver.py", line 20, in <module>
    from selenium.webdriver.common.driver_finder import DriverFinder
  File "C:\Users\gurda\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\common\driver_finder.py", line 5, in <module>
    driver = webdriver.Chrome()
AttributeError: partially initialized module 'selenium.webdriver' has no attribute 'Chrome' (most likely due to a circular import)

**Comment by titusfortner** [comment]
Well, we know debug is getting set because the command is sent to Selenium Manager with `--debug`, but it isn't displaying in the console:

Are you running this inside of PyTest? Sometimes it swallows the selenium manager console output; you would need to tweak things: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/?tab=python#logger-level

Or try running that command in a standalone file

**Comment by TheWham** [comment]
hey man, I have a problem similar to yours, I can open the web page but crash, maybe the version of chromedriver,Where did you download the chromedriver, please. I cannot find it( 119.0.6045.160);

**Comment by Krushant17** [comment]
Also Found the same  but as warning : 

**WARNING: Unable to obtain driver using Selenium Manager: Error running command: [C:\Users\LENOVO\AppData\Local\Temp\selenium-manager20604373543678006013227161373087945\selenium-manager.exe, --driver, chromedriver]**
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: driver.version: ChromeDriver

java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads

**Comment by titusfortner** [comment]
@Krushant17 that's an old version of Selenium, you need to update to the latest version.

**Comment by philipday** [comment]
I had a similar problem, in PyCharm, just bumped the Selenium version 4.9 -> 4.16 (highest available in PyCharm) and it worked.

**Comment by chai-dev682** [comment]
I am using selenium 4.16.0, and chrome (120.0.6099.110)
but got error that says "unable to obtain driver for chrome using selenium manager"
So I got chrome driver (120.0.6099.109) and it is in PATH
but still same error

**Comment by diemol** [comment]
I believe that keeping this matter open may not be the most beneficial or constructive approach. If you require additional assistance or tips for troubleshooting, we warmly invite you to join our supportive chat – [the links are provided below for your convenience](https://www.selenium.dev/support/#ChatRoom).

@enthusiastica can you please open a new issue and share all the details requested in the template?
