### ISSUE TITLE
[🐛 Bug]:  The HTTP request to the remote WebDriver server for URL http://localhost:61704/session/3b662b0a-4b3a-423f-aa67-3b11572aa560/url timed out after 120 seconds.

### ISSUE THREAD

**Issue by pnowocinLX** [SeleniumHQ/selenium#13197]
### What happened?

I have  The HTTP request to the remote WebDriver server for URL http://localhost:61704/session/3b662b0a-4b3a-423f-aa67-3b11572aa560/url timed out after 120 seconds.   This bug show random, not always

C#

### How can we reproduce the issue?

```shell
.        /// <summary>
        /// Utworzenie nowego WebDriver do testu
        /// </summary>
        /// <returns> WebDriver </returns>
        public static (WebDriver WebDriver, string BrowserName ) CreateNewFirefoxWebDriver()   //string FirefoxProfilePath
        {
            try
            {
                var tempFiles = new List<FileInfo>();


                try
                {
                    var ffInfo = GetFirefoxInfoFromRegistry();
                    var options = new FirefoxOptions
                    {
                        AcceptInsecureCertificates = true,
                        BrowserExecutableLocation = ffInfo.File.FullName
                    };

                    var webDriver = new FirefoxDriver(FirefoxDriverService.CreateDefaultService(), options, TimeSpan.FromMinutes(2));
                    webDriver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(40));///
                    webDriver.Manage().Window.Size = new Size(1608, 994);
                    return (webDriver, ffInfo.FullBrowserName); 
                }
                finally
                {
                    tempFiles.ForEach(fi => fi.Delete());
                }
            }
            catch (Exception exception)
            {
                throw new WebDriverFactoryException("Nie udało się utworzyć instancji WebDriver.", exception);
            }
        }
```

### Relevant log output

```shell
.
```

### Operating System

Windows 10

### Selenium version

Selenium 4.9.1

### What are the browser(s) and version(s) where you see this issue?

Firefox  115.4.0esr

### What are the browser driver(s) and version(s) where you see this issue?

Geckodriver 0.33

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
What happens if you do not configure the browser driver binary and let Selenium manage that?

**Comment by NCLnclNCL** [comment]
> ### What happened?
> I have The HTTP request to the remote WebDriver server for URL http://localhost:61704/session/3b662b0a-4b3a-423f-aa67-3b11572aa560/url timed out after 120 seconds. This bug show random, not always
> 
> C#
> 
> ### How can we reproduce the issue?
> ```shell
> .        /// <summary>
>         /// Utworzenie nowego WebDriver do testu
>         /// </summary>
>         /// <returns> WebDriver </returns>
>         public static (WebDriver WebDriver, string BrowserName ) CreateNewFirefoxWebDriver()   //string FirefoxProfilePath
>         {
>             try
>             {
>                 var tempFiles = new List<FileInfo>();
> 
> 
>                 try
>                 {
>                     var ffInfo = GetFirefoxInfoFromRegistry();
>                     var options = new FirefoxOptions
>                     {
>                         AcceptInsecureCertificates = true,
>                         BrowserExecutableLocation = ffInfo.File.FullName
>                     };
> 
>                     var webDriver = new FirefoxDriver(FirefoxDriverService.CreateDefaultService(), options, TimeSpan.FromMinutes(2));
>                     webDriver.Manage().Timeouts().PageLoad.Add(TimeSpan.FromSeconds(40));///
>                     webDriver.Manage().Window.Size = new Size(1608, 994);
>                     return (webDriver, ffInfo.FullBrowserName); 
>                 }
>                 finally
>                 {
>                     tempFiles.ForEach(fi => fi.Delete());
>                 }
>             }
>             catch (Exception exception)
>             {
>                 throw new WebDriverFactoryException("Nie udało się utworzyć instancji WebDriver.", exception);
>             }
>         }
> ```
> 
> ### Relevant log output
> ```shell
> .
> ```
> 
> ### Operating System
> Windows 10
> 
> ### Selenium version
> Selenium 4.9.1
> 
> ### What are the browser(s) and version(s) where you see this issue?
> Firefox 115.4.0esr
> 
> ### What are the browser driver(s) and version(s) where you see this issue?
> Geckodriver 0.33
> 
> ### Are you using Selenium Grid?
> no

I found out that this error is caused by the overloaded client device continuously running at 100% cpu, you need increase timeout to 300

**Comment by diemol** [comment]
Thanks for pointing that, @NCLnclNCL! 

>This bug show random, not always

That makes sense then, if the load is higher, processes will take longer to start. Try to increase the timeout. If you have more questions, I will leave some links below that you can use, including our Slack channel.

**Comment by pnowocinLX** [comment]
I add 320 second ...and dont have this problem :) Thansk alll
