### ISSUE TITLE
[🐛 Bug]: I am facing unable to find an exact match for CDP version 119, so returning the closest version found 115

### ISSUE THREAD

**Issue by GaganVaidya** [SeleniumHQ/selenium#13193]
### What happened?

While executing the TestNG 7.8.0 test cases during that time I am facing a CDP version issue. The same code I have tried with Java Application and it was run perfectly. I don't know I am facing an issue with TestNG. Has anyone solved this issue before? Please guide me on it. It has already wasted my 2 days. 

### How can we reproduce the issue?

```shell
I am afraid, I can't share my code. This issue we are getting from the client side.
But I got this response in console,

[RemoteTestNG] detected TestNG version 7.8.0

SLF4J: No SLF4J providers were found.

SLF4J: Defaulting to no-operation (NOP) logger implementation

SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.

Nov 23, 2023 11:05:08 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch

WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 115
```

### Relevant log output

```shell
Not Yet.
```

### Operating System

windows 11

### Selenium version

java 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119.0.6045.160

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105

**Comment by baflQA** [comment]
It's just a warning, so as long as you do not use the CDP, you dont have to worry. But if You want to use the CDP, you would have to update selenium to 4.15, as it supports Chrome versions 117-119

**Comment by diemol** [comment]
What @baflQA says is correct. Please upgrade to 4.15.0 to avoid the warning.
