### ISSUE TITLE
[🐛 Bug]: By.id returns incorrect By.Remotable.Parameters

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13191]
### What happened?

Calling  `((By.Remotable) By.id("test")).getRemoteParameters().using()` will return `id`, this is not a valid W3C locator strategy.
Internally the `By.id` is using a `css selector` and should return this on calling `.using()` to have a valid W3C locator strategy.

### How can we reproduce the issue?

```shell
see above
```

### Relevant log output

```shell
N/A
```

### Operating System

win 10 x64

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
This has been kept in the project to simplify when users moved from JWP to W3C. In addition, it is still widely used. I know `id` is not a W3C locator strategy, and I am not sure if the effort is worth removing it. 

I wonder what the others think.

**Comment by nvborisenko** [comment]
Then the entire internet becomes outdated. And knowledge, used by AI, becomes wrong.

**Comment by joerg1985** [comment]
For clarification my intention was not to remove `By.id`, only to return the actual `using`.

**Comment by diemol** [comment]
I think I've seen a couple of issues where people have pointed that out, and I remember we replied the same... They use ID, and under the hood, we translate it to CSS.

**Comment by joerg1985** [comment]
Sorry the statement about the value was not correct...

However, if this is intentionally this can be closed.

**Comment by titusfortner** [comment]
What's the use case of using?
If it is querying the implementation detail, it seems to make sense that it returns the translated value?

**Comment by joerg1985** [comment]
I stumbled into this in unit tests, i replace the `CommandExecutor` to have no external processes running and speed things up.

Calling `locator.findElement(driver)` and `driver.findElement(locator)` will have different parameters in the `Command` set. e.g.
`driver.findElement(locator)` => `[0c0b60ab8b700bf4ad09a153086db1e0, findElement {using=id, value=test}]`
`locator.findElement(driver)` => `[0c0b60ab8b700bf4ad09a153086db1e0, findElement {using=css selector, value=#test}]`

The `W3CHttpCommandCodec` does the needed translation in the `driver.findElement(locator)` case, before sending it to the browser. This looked like a outdated workaround to me, therefore i raised this ticket.

**Comment by diemol** [comment]
Maybe we need to update the locator to return `id`?

**Comment by titusfortner** [comment]
I think the current implementation is correct. Driver is the user facing API which displays "id" because that's what the user specified and locator is the implementation detail which is sending css selector to the driver. 

If we decide they need to match for some reason, then I think we should be displaying the translation rather than the user input value.

**Comment by titusfortner** [comment]
Thanks for raising this, I can see how it seems weird that these are different, but we agreed in TLC meeting 1/18 to keep things as they are.
