### ISSUE TITLE
[🚀 Feature]: Remote webdriver init with existing session id 

### ISSUE THREAD

**Issue by rrr2rrr** [SeleniumHQ/selenium#13202]
### Feature and motivation

In python library in [`selenium/webdriver/remote/webdriver.py`](https://github.com/SeleniumHQ/selenium/blob/59b8f23033b39b5934e42e64257af82fddcaf1e8/py/selenium/webdriver/remote/webdriver.py#L207) you starting new webdriver and don't give ability to use existing one 

The only possibility showed [here](https://stackoverflow.com/a/52003231/21920723) using extra one session of webdriver

```
driver = webdriver.Remote(command_executor=the_known_url)  

driver_copy = copy.copy(driver)
driver.quit()

driver_copy.session_id = session_id

# do something with the now hijacked session:
driver.get('https://www.bing.com/')
```

### Usage example

In my project i use microservice architecture. I divided flow into several small steps.
I each small step I need to use the same connection, that I used before (including auth, cookies, history, etc.)
I am using Selenoid and for me it isn't a problem to store session_id and use this hack

**Comment by titusfortner** [comment]
There is a way to use an existing session by specifying the debugging port. That approach allows you to set valid capabilities. If you just use the existing session id, the capabilities are not guaranteed to match, so we do not want to support it in Selenium.
