### ISSUE TITLE
[🐛 Bug]: "Get Text" atom ignores slot value for web component without custom text

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#13206]
### What happened?

The Selenium atom `Get Text` should not only return the value from a slot when it is used but also it's default value when it has not been used. In the example below the value `foobar` is visible as text but the atom `Get Text` returns just `bar`.

### How can we reproduce the issue?

```shell
With the following testcase it can be reproduced:


    <head>
      <script>
        class TestContainer extends HTMLElement {
          connectedCallback() {
            this.attachShadow({ mode: 'open' });
            this.shadowRoot.innerHTML = `<slot><span>foo</span></slot>bar`;
          }
        }

        customElements.define('test-container', TestContainer);
      </script>
    </head>

    <body>
      <test-container></test-container>
    </body>
```

CC @43081j in case you are interested.
```


### Relevant log output

```shell
No log output available.
```

### Operating System

MacOS 13.6

### Selenium version

Latest

### What are the browser(s) and version(s) where you see this issue?

Firefox (not tested with others)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver (not tested with others)

### Are you using Selenium Grid?

No

**Comment by 43081j** [comment]
good catch, i did actually wonder this when you and i were reading through the source recently 😬 

here:
https://github.com/SeleniumHQ/selenium/blob/c806757cc1ebd2c64f30bfcd5c0d1432b78e54f4/javascript/atoms/dom.js#L1328-L1331

we probably just want to conditionally traverse the `childNodes` of the slot itself if there are no assigned nodes.

i.e.

```ts
const childrenToTraverse = shadowChildren.length > 0 ? shadowChildren : contentElem.childNodes;
// existing logic but using `childrenToTraverse` instead
```

**Comment by AutomatedTester** [comment]
Sounds good to me @whimboo, are you able to submit a PR for this?

**Comment by whimboo** [comment]
I could do once the changes on https://github.com/SeleniumHQ/selenium/pull/13211 are landed.

**Comment by whimboo** [comment]
Thanks @43081j. Looks like it fixes this case but now we have another problem with the following test:

```
    function testTextForSlotAndExtraValueInShadowDOM() {
      setCustomElement('<slot><span>full</span></slot> text');

      let customEl = findElement({ id: 'custom-text' });
      let text = getText(customEl);
      assertEquals('custom text', text);
    }

    ..
    <open-shadow-element id="custom-text">custom</open-shadow-element>
```

Here we have an additional text outside of the slot element, which is not taking into account. Instead of `custom text` it retrieves `custom`. Not sure if that's easy enough as well. Happy to file another issue for that.

**Comment by whimboo** [comment]
In case you want to run the code yourself locally I've created https://github.com/SeleniumHQ/selenium/pull/13218 which contains the still broken test.
