### ISSUE TITLE
[🐛 Bug]: Network.setBlockedURLs not working with the tab that open by the click

### ISSUE THREAD

**Issue by jokeaa** [SeleniumHQ/selenium#13203]
### What happened?

i try to block same css file and img file during the test,
since i set the setBlockedURLs list using the Network.setBlockedURLs,it works on the main page,but when i click a url with the target="_blank" that open a new tab,the blocklist just can not work
I know i can set the target to null or just get the url and Manual open a new tab ,then set the blocklist and go to page,but it is not simple enough.
Is there some global blocklist that  take effect with all the tabs?

### How can we reproduce the issue?

```shell
from selenium import webdriver
import logging
from selenium.webdriver.common.by import By
logger = logging.getLogger('selenium')
def main():

    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument('--auto-open-devtools-for-tabs')
    driver = webdriver.Chrome(options=chrome_options)
   
    driver.execute_cdp_cmd('Network.setBlockedURLs',{
        "urls":[
        '*.jpg',
        '*.gif',
        '*.png',
        '*.jpeg'
        ]}
        )
    driver.execute_cdp_cmd('Network.enable', {})
   

    driver.get('https://www.amazon.com/')


    driver.find_element(By.XPATH,'//a[@target="_blank"]').click()
    #with this click,the new tab don`t block anything.
    
    print('over')


main()
```

### Relevant log output

```shell
DevTools listening on ws://127.0.0.1:7738/devtools/browser/a898b634-e1b5-49a3-b2ed-1da72bbac0b9
```

### Operating System

windows 10

### Selenium version

Python 4.9.1

### What are the browser(s) and version(s) where you see this issue?

chrome 118

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 118.0.5993.70

**Comment by diemol** [comment]
IIRC, CDP needs a connection per tab, so the blocked URLs filter keeps working on the original but not the new one. Try to set the command again after switching to the new tab.

**Comment by jokeaa** [comment]
> IIRC, CDP needs a connection per tab, so the blocked URLs filter keeps working on the original but not the new one. Try to set the command again after switching to the new tab.

the tab open by the click is loading very fast,so there is no time to switch to the new tab and set the command

**Comment by diemol** [comment]
Why don't you grab the URL and open the tab yourself?

**Comment by diemol** [comment]
I'm kindly closing this issue as we haven't received additional information. If you have further details to share or if there's anything else we can assist you with, please feel free to reach out.
