### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by ij-23** [SeleniumHQ/selenium#13209]
### What happened?

I'm trying to run Selenium tests with Azure DevOps and I'm getting this error message:

[Failed] [disconnected: Unable to receive message from renderer (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: headless MicrosoftEdge=119.0.2151.72)] [Details at 1 below]
Exceptions:

disconnected: Unable to receive message from renderer (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: headless MicrosoftEdge=119.0.2151.72)
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebDriver.set_Url(String value)
at OpenQA.Selenium.Navigator.GoToUrl(String url)
Microsoft Edge WebDriver 119.0.2151.72
Microsoft Edge Version 119.0.2151.72 (Official build)

From a different build agent with the same Edge WebDriver and Version it works fine, it happens only in one on my build agents.

### How can we reproduce the issue?

```shell
-
```

### Relevant log output

```shell
[Failed] [disconnected: Unable to receive message from renderer (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: headless MicrosoftEdge=119.0.2151.72)] [Details at 1 below]
Exceptions:

disconnected: Unable to receive message from renderer (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: headless MicrosoftEdge=119.0.2151.72)
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.WebDriver.set_Url(String value)
at OpenQA.Selenium.Navigator.GoToUrl(String url)
Microsoft Edge WebDriver 119.0.2151.72
Microsoft Edge Version 119.0.2151.72 (Official build)
```

### Operating System

Windows Server 2016

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge Version 119.0.2151.72 (Official build)

### What are the browser driver(s) and version(s) where you see this issue?

Microsoft Edge WebDriver 119.0.2151.72

**Comment by diemol** [comment]
If that happens in one of your Azure agents and not in another one, there is not much we can do. You need to check them both and see what's different between them. Or even better, dump the failing agent and create a new one with the same setup from the working one.

There's not much we can do to troubleshoot Azure agents.
