### ISSUE TITLE
[🐛 Bug]: download.default_directory does not prevent popup when running in non-headless mode

### ISSUE THREAD

**Issue by bennyvw** [SeleniumHQ/selenium#13208]
### What happened?

When running with Robot Framework, the download file popup appears, while it did not before.

### How can we reproduce the issue?

```shell
I started my browser with the options
Set To Dictionary    ${prefs}    download.default_directory=${DOWNLOAD_DIR}
Set To Dictionary    ${prefs}    download.prompt_for_download=False

When running in headless mode, everything is still fine, the file is downloaded.
But, when running non-headless (headful?) the download file is shown, which is not expected.
```

### Relevant log output

```shell
No log output
```

### Operating System

Windows 11

### Selenium version

RF SeleniumLibrary 6.1.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 119.0.6045.105

### What are the browser driver(s) and version(s) where you see this issue?

119.0.6045.105

**Comment by titusfortner** [comment]
Duplicate #13104
