### ISSUE TITLE
JavaScript: Array of keys must be converted to string before using sendKeys

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#1320]
Based on the documentation of the sendKeys function, it should be possible to use an array or a string but (for example) the following array leads to wrong results when expanding the '4.5' string in an edit control:

```
element.sendKeys([webdriver.Key.CONTROL, 'a', webdriver.Key.CONTROL, webdriver.Key.BACK_SPACE, '4.5', webdriver.Key.BACK_SPACE]);
```

where converting the array to a single straing leads to the expected results:

```
element.sendKeys([webdriver.Key.CONTROL, 'a', webdriver.Key.CONTROL, webdriver.Key.BACK_SPACE, '4.5', webdriver.Key.BACK_SPACE].join(''));
```

Do I use the API wrongly or is there something wrong with the implementation?

**Comment by IronGremlin** [comment]
```
var anArray = [webdriver.Key.CONTROL, 'a', webdriver.Key.CONTROL, webdriver.Key.BACK_SPACE, '4.5', webdriver.Key.BACK_SPACE];
var sameArrayAsString = [webdriver.Key.CONTROL, 'a', webdriver.Key.CONTROL, webdriver.Key.BACK_SPACE, '4.5', webdriver.Key.BACK_SPACE].join('')

Array.prototype.call.slice(anArray) // [ '', 'a', '', '', '4.5', '' ]
Array.prototype.call.slice(sameArrayAsString) // [ '', 'a', '', '', '4', '.', '5', '' ]
```

The 4.5 is a single element in your array.
When passed as a string, `Array.prototype.slice`  recognizes `'4.5'` as three indexes, and so structures the array appropriately.
4.5 is not a single key, but it is a number, so it passes the `sendKeys` type check.

**Comment by IronGremlin** [comment]
I was a off base here.

It looks like the case of a single array arg isn't covered by `Array.prototype.slice.call` when assigning a value to the `keys` variable in the sendKeys.
`then`-ing off of Promise.all to slice results in a length 1 array containing the array, which short circuits the loop that's supposed to split the '4.5' value into its constituent chars.

Rereading both the functions and the docs, it's unclear to me whether or not this case is supposed to be supported, or, if it is, exactly what the case of passing in an array of keys is supposed to support, so I'm reticent to submit a pull request, but if the intent is to essentially flatten any combination of arrays or additional arguments into a thenable that will resolve to an array of characters, the following would accomplish this: 

```
function Flatten(a,b){
    if (b.constructor === Array){
        b = b.reduce(Flatten,[])
    }
    if (typeof b == 'number'){
        b = String(b)
    }
    if (typeof b == 'string'){
        b = b.split('')
    }
    if (b.constructor !== Array){
        throw TypeError(
                  'each key must be a number of string; got ' + type);
            }
    }
    return a.concat(b)
};
function FlattenArgs(){return Array.prototype.reduce.call(arguments,Flatten,[])}
 
let keys = Promise.all(var_args).then(FlattenArgs)
```

This has the side effect of supporting arbitrarily nested arrays of key sequences in a fairly straightforward way, which is of dubious benefit, but little harm.

**Comment by diemol** [comment]
Closing this as it has been stale for over 3.5 years, which either means it is not an issue anymore (OP found a solution or it was solved in a release) or it is not relevant anymore.

If this is still an issue, please open a new one and provide all the required information.
