### ISSUE TITLE
[🚀 Feature]: [selenium grid web hub page] grid sorted by platform

### ISSUE THREAD

**Issue by pppppino** [SeleniumHQ/selenium#13216]
### Feature and motivation

Version: selenium grid 4.12.0

In overview page, there are many grids, so, could you give a button, which could sorted by platform name, or just sorted by platform name by default. 

In addition, I found that the icon of MacOS is same as iPhone, which is not convenient.

<img width="1881" alt="image" src="https://github.com/SeleniumHQ/seleniumhq.github.io/assets/129264630/102ccbd9-a19f-4712-bd93-09990247c44e">

**Comment by titusfortner** [comment]
Oh this is just a duplicate. Should have closed instead of transferring.
