### ISSUE TITLE
[🚀 Feature]: [selenium grid] grid web page sorted by platform

### ISSUE THREAD

**Issue by pppppino** [SeleniumHQ/selenium#13215]
### Feature and motivation

Version: selenium grid 4.12.0

In overview page, there are many grids, so, could you give a button, which could sorted by platform name, or just sorted by platform name by default.

In addition, I found that the icon of MacOS is same as iPhone, which is not convenient.

![image](https://github.com/SeleniumHQ/selenium/assets/129264630/236c4348-bdf2-46f7-8ab8-9e51c37ed403)

### Usage example

I could find my grid config quickly

**Comment by VietND96** [comment]
Here is the preview

![image](https://github.com/user-attachments/assets/358c8087-229a-4b3a-b6a6-9cb80a7752b7)
