### ISSUE TITLE
[🚀 Feature]: Check Options and Servece type in class WebDriver()

### ISSUE THREAD

**Issue by tinyhare** [SeleniumHQ/selenium#13213]
### Feature and motivation

I copy codes from the web, and I made a mistake that made a firefox service for Chrome webdriver：
```
from selenium import webdriver
from selenium.webdriver.firefox.service import Service # the problem is here，this is firefox service，but I use Chrome

options = webdriver.ChromeOptions()
options.binary_location = r".\chrome-win64\chrome.exe"

service = Service(executable_path=r".\chromedriver-win64\chromedriver.exe")

driver = webdriver.Chrome(options=options, service=service)
```

and get this information：

`selenium.common.exceptions.WebDriverException: Message: Service .\chromedriver-win64\chromedriver.exe unexpectedly exited. Status code was: 1`

I know this is my mistake, but to solve this problem I waste  a lot of time.

So I advise to check the Service and Option type in class WebDriver(): 
```
        service = service if service else Service()
        options = options if options else Options()
        try:
            assert type(service) == Service
            assert type(options) == Options
        except AssertionError:
            raise AssertionError(f"Service or Options type is wrong, please use {Service} and {Options}")
```

### Usage example

When use wrong object type, will get this information: 

`AssertionError: Service or Options type is wrong, please use <class 'selenium.webdriver.chrome.service.Service'> and <class 'selenium.webdriver.chrome.options.Options'>`

 people can solve it quickly

**Comment by titusfortner** [comment]
I'm reluctant to force typing in dynamic languages. The python type hints should catch this kind of thing.

**Comment by titusfortner** [comment]
@symonk / @isaulv / @AutomatedTester should we be throwing errors based on types in addition to the type hints we have now? I though type hints were a way to avoid doing this. I figured I'd ask instead of just closing. Thanks.

**Comment by titusfortner** [comment]
I didn't hear back, so I'm going to say we don't want to do this; if the type hints aren't correct we should fix them.
Thanks for raising the suggestion.
