### ISSUE TITLE
[🐛 Bug]: selenium java jar empty

### ISSUE THREAD

**Issue by jramirezmorales** [SeleniumHQ/selenium#13225]
### What happened?

the https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/4.15.0 artifact has no java classes
![image](https://github.com/SeleniumHQ/selenium/assets/121830872/36a1c627-971e-40e7-b3ca-32cd0231eada)

### How can we reproduce the issue?

```shell
add as dependency in pom or build bazel project
```

### Relevant log output

```shell
none
```

### Operating System

macOS ventura 13.5

### Selenium version

java21

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by titusfortner** [comment]
selenium-java is there to manage all of the dependencies, it doesn't need any of its own classes.

**Comment by jramirezmorales** [comment]
So why I cannot se the ClientConfig class?

**Comment by titusfortner** [comment]
I don't know what you are trying to do. You mention maven and bazel. Do you have a pom dependency and some code that isn't working together?

**Comment by krmahadevan** [comment]
@jramirezmorales - Are you looking for the class `org.openqa.selenium.remote.http.ClientConfig` ? If yes, then this class is part of the maven artifact [selenium-http](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-http/4.15.0) which is available to you as a transitive dependency as seen in below screenshot

<img width="526" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/909773/f2d4dd45-2367-400c-b405-f9d14a835687">

If you are experiencing some sort of class not found errors, there's a very good chance that perhaps your maven dependency resolution didn't go through fine. You can try retriggering it using the command `mvn -U dependency:resolve`
