### ISSUE TITLE
[🐛 Bug]: python wrapper: selenium-manager not installed on RaspberryPi (ARMv7)

### ISSUE THREAD

**Issue by sfavazza** [SeleniumHQ/selenium#13231]
### What happened?

Hello, 

running few tests with pytest on a test-setup involving a RaspberryPi, I realized that no selenium-manager is installed with the classic command `python -m pip install selenium`.

To give a visual of the observation have a look at the screenshots below:
![image](https://github.com/SeleniumHQ/selenium/assets/36377461/3298dd74-7ff4-482c-ab43-06ddcfbba986)

I wonder the following:
- is this intended?
- is there a way to manually install the drivers and be recognized by the `selenium` Python package?

### How can we reproduce the issue?

```shell
on a RaspberryPi (or ARMv7 platform) execute:
python -m pip install selenium
```

### Relevant log output

```shell
n.a.
```

### Operating System

Raspbian GNU/Linux 10 (buster)

### Selenium version

Python 4.15.2

### What are the browser(s) and version(s) where you see this issue?

n.a.

### What are the browser driver(s) and version(s) where you see this issue?

n.a.

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
There are no official drivers available for that architecture, so nothing for selenium to manage for you.
The error message should have a link to our documentation for how to use drivers you have downloaded yourself.

**Comment by seidnerj** [comment]
https://github.com/SeleniumHQ/selenium/issues/13287 relevant for this.
