### ISSUE TITLE
[🚀 Feature]: Add enum for `_PageLoadStrategyDescriptor`

### ISSUE THREAD

**Issue by M1troll** [SeleniumHQ/selenium#13236]
### Feature and motivation

Hi!

In my project, I've encountered a situation where I need to change the default page load strategy, but the only way to find the names of the available strategies is by searching the documentation or looking at the descriptor implementation.

I think it would be convenient to have an enum for these names. This would help with hints of available strategy names and save us from having to remember their full names. It would also be great to add info about difference between these strategies in the docstring of this class, as [is done in the documentation](https://www.selenium.dev/documentation/webdriver/drivers/options/#pageloadstrategy).

Thanks!

### Usage example

If enum is named `PageLoadStrategy`, I can easily use strategy name as follows:

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options, PageLoadStrategy

options = Options()
options.page_load_strategy = PageLoadStrategy.EAGER
```

**Comment by diemol** [comment]
Would you like to send a PR for this?

**Comment by M1troll** [comment]
> Would you like to send a PR for this?

Yes, I can
