### ISSUE TITLE
[🐛 Bug]: DragAndDrop doesn't work in some cases.

### ISSUE THREAD

**Issue by dmitryyu** [SeleniumHQ/selenium#13230]
### What happened?

Original Drag and Drop from Actions class doesn't work in some cases and it's necessary to use workarounds for it.
Please see the code in "How can we reproduce the issue?" to reproduce the issue.

After execution the following line:
`actions.dragAndDrop(element1Before, element2Before).perform();`

we can see that webdriver tries to move the element correctly (it uses mouse down, moving, and mouse up) but an issue  that ExtJs (in that case) still do not get a final state of the action - when release button can be used. 
for example, if I try to use original method without releasing mouse button (last line):
```
  public Actions dragAndDrop(WebElement source, WebElement target) {
    return moveInTicks(source, 0, 0)
        .tick(getActivePointer().createPointerDown(LEFT.asArg()))
        .moveInTicks(target, 0, 0)
        .tick(getActivePointer().createPointerUp(LEFT.asArg())); 
  }
```
we can see the following state in browser: 
<img width="622" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/11774103/65b88a32-b3a9-4a38-8374-de24cd2586df">

it means ExtJs still doesn't allow to do release by some reasons.

But if we try to execute move action twice - everything is ok, so the code below works ok: 
```
 public Actions dragAndDrop(WebElement source, WebElement target) {
    return moveInTicks(source, 0, 0)
        .tick(getActivePointer().createPointerDown(LEFT.asArg()))
        .moveInTicks(target, 0, 0)
        .moveInTicks(target, 0, 0) 
        .tick(getActivePointer().createPointerUp(LEFT.asArg())); 
  }
```

I thought it's related to duration in createPointerMove(Duration...) constructor, but no it works with Zero duration as well:

```
actions.moveInTicks(element1Before, 0, 0)
		.tick(actions.getActivePointer().createPointerDown(PointerInput.MouseButton.LEFT.asArg()))
		.tick(actions.getActivePointer().createPointerMove(Duration.ZERO, PointerInput.Origin.fromElement(element2Before), 0, 0))
		.tick(actions.getActivePointer().createPointerMove(Duration.ZERO, PointerInput.Origin.fromElement(element2Before), 0, 0))
		.tick(actions.getActivePointer().createPointerUp(PointerInput.MouseButton.LEFT.asArg()))
		.perform();

```

### How can we reproduce the issue?

```shell
public static void main(String[] args) {
 WebDriver driver = new ChromeDriver();
 driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(2));
 driver.get("https://docs.sencha.com/extjs/6.5.0/classic/Ext.grid.plugin.DragDrop.html");
 WebElement runBtn = driver.findElement(By.xpath("//span[@class='fiddle-icon-wrap']"));
 runBtn.click();
 WebElement iframe = driver.findElement(By.xpath("//iframe[@name='e-0']"));
 driver.switchTo().frame(iframe);

 WebElement element1Before = driver.findElement(By.xpath("//table[1]//td[contains(@class,'gridcolumn-1011')]//div"));
 WebElement element2Before = driver.findElement(By.xpath("//table[3]//td[contains(@class,'gridcolumn-1011')]//div"));
 String originalText = element2Before.getText();
 Actions actions = new Actions(driver);
 actions.dragAndDrop(element1Before, element2Before).perform();
 WebElement element2After = driver.findElement(By.xpath("//table[3]//td[contains(@class,'gridcolumn-1011')]//div"));

 Assert.assertNotEquals(element2After.getText(), originalText, " Text was not changed");
 driver.quit();
}
```

### Relevant log output

```shell
No errors here - webdriver execute these steps without issues. (or it's failed by assrtion)
```

### Operating System

MacOs Ventura

### Selenium version

Java 4.10.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105 (38c72552c5e15ba9b3117c0967a0fd105072d7c6-refs/branch-heads/6045@{#1103})

### Are you using Selenium Grid?

-

**Comment by diemol** [comment]
This is a known issue among drivers right now. None of them seem to be able to get this to work, unfortunately.

https://github.com/SeleniumHQ/selenium/issues/10601
