### ISSUE TITLE
[🐛 Bug]: fedcm with PingFederate using ChromeNode on SeleniumGrid

### ISSUE THREAD

**Issue by StellarNear** [SeleniumHQ/selenium#13239]
### What happened?

Hi dear Selenium team, i was using chrome-node v114 connected to a selenium grid (4.10) and i wanted to udpate my environment (going to grid 4.15 and chrome-node 119).

While doing this i can see that all my automated tests were crashing due to an authentication failing :
I use pingfederate and it return 
![image](https://github.com/SeleniumHQ/selenium/assets/31210322/6d75affa-7b2d-4cdf-9bcb-6ea5294d52b8)

where the same test on chrome 114 was working 

I did a lot of digging and i'm seeing that the only difference between the two version of the node is "fedcm:accounts: true"
So i tryed to use a chromeOptions.setCapability("fedcm:accounts",false); but it seems that it's not a recognized capability (since the node crash saying it's not a known capability).

### How can we reproduce the issue?

```shell
Using pingfederate to oauth2
```

### Relevant log output

```shell
(can't access the log on pingfederate side)
```

### Operating System

linux / kubernetes

### Selenium version

4.15.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

119.0.6045.199

### Are you using Selenium Grid?

4.15.0

**Comment by StellarNear** [comment]
I want to say thanks bot but i can't find the concerned bug reported on the chromedriver side, i hope that's true though :)

**Comment by titusfortner** [comment]
> If it is something new, please [create an issue](https://bugs.chromium.org/p/chromedriver/issues/list) with the ChromeDriver team.

**Comment by StellarNear** [comment]
I'm not sure that this is a ChromeDriver team's fault. Selenium is pushing an error 500

`Capabilities {acceptInsecureCerts: true, browserName: chrome, fedcm:accounts: false, goog:chromeOptions: {args: [], extensions: []}, requester:project-id: cicd_regression_tests_python}
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 86 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: No matching capabilities found `

**Comment by diemol** [comment]
That comes when you add something like `fedcm:accounts",false`

You probably need to report the bug to the Chrome team.

**Comment by StellarNear** [comment]
FYI : https://bugs.chromium.org/p/chromedriver/issues/detail?id=4655&q=4655&can=2

**Comment by StellarNear** [comment]
Fixed with chrome 120
