### ISSUE TITLE
[🐛 Bug]: Cannot connect to remote host with version 4.14.1 but can with 4.3.0

### ISSUE THREAD

**Issue by bryancoxdish** [SeleniumHQ/selenium#13247]
### What happened?

[RemoteWebDriver4.14.0 Bug.docx](https://github.com/SeleniumHQ/selenium/files/13572483/RemoteWebDriver4.14.0.Bug.docx)

### How can we reproduce the issue?

```shell
Sample request where getting the issue:
driver_original = new RemoteWebDriver(new URL("https://dish-public.perfectomobile.com/nexperience/perfectomobile/wd/hub"), capabilities);

Capabilities being passed in: {capabilities=[Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}]}]
Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}

NOTE: I noticed that in 4.14.0 - platformName is being passed in as mac (getting the issue), but in 4.3.0 - platformName is being passed in as: MAC (not getting the issue and connection is being made and test is being executed).
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'FVFHNP5JQ6L4', ip: 'fe80:0:0:0:189b:7c37:3e7a:4e06%en0'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.2', java.version: '20.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}]}]
Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}
```

### Operating System

macOS Venura

### Selenium version

Java 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Safari

### What are the browser driver(s) and version(s) where you see this issue?

RemoteWebDriver

### Are you using Selenium Grid?

No

**Comment by bryancoxdish** [comment]
In both cases, platformName that I am passing in for the capability is: "Mac", but in 4.14.1 the capability is being set to: mac, and in 4.3.0 it is being set to: MAC.  In 4.14.1, what do I need to pass in for the platformName capability so that it is set to: MAC?  When I brought this up with Perfecto, they stated that it looked like there was not an attempt to reach them.

**Comment by titusfortner** [comment]
Please include the code you are using. Note that there are a bunch of non-compliant capabilities there. You are only allowed these 10: https://w3c.github.io/webdriver/#capabilities or a namespaced extension.

**Comment by bryancoxdish** [comment]
Hi Selenium,

Here is sample code:
private void setUpSelRemoteHost() throws Exception {
		DesiredCapabilities capabilities = new DesiredCapabilities("", "", Platform.ANY);

		// set platformName, and platformVersion
		capabilities.setCapability("platformName", "Mac");
		capabilities.setCapability("platformVersion", "macOS Ventura");
		capabilities.setCapability("browserName", "Safari");
		capabilities.setCapability("browserVersion", "16");
		capabilities.setCapability("location", "NA-US-BOS");
		capabilities.setCapability("resolution", "800x600");
		capabilities.setCapability("securityToken", "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5OGQzMWI0OC1mODUyLTQ4ZTItOTgwMy03MmRhM2UyZDc3N2EifQ.eyJpYXQiOjE3MDAyMjY5MDEsImp0aSI6IjQwODRjYzBlLWQ5ZjQtNGVlMC05NzlmLWRiMWQwZmE4NDNiMiIsImlzcyI6Imh0dHBzOi8vYXV0aDgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2Rpc2gtcHVibGljLXBlcmZlY3RvbW9iaWxlLWNvbSIsImF1ZCI6Imh0dHBzOi8vYXV0aDgucGVyZmVjdG9tb2JpbGUuY29tL2F1dGgvcmVhbG1zL2Rpc2gtcHVibGljLXBlcmZlY3RvbW9iaWxlLWNvbSIsInN1YiI6IjZlM2NiNDc4LWIzMTktNGZlZS05N2ZjLTcxYTU0NjE1YTk5MiIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJvZmZsaW5lLXRva2VuLWdlbmVyYXRvciIsIm5vbmNlIjoiNDIwYTcxM2MtMjk0My00NDY3LThlZmMtMTMyOWJkYzg3YTQxIiwic2Vzc2lvbl9zdGF0ZSI6Ijg4NTM4MmFmLWNlYjYtNDJmYy1iZTNjLTI2ZGM5MjZhYmQzYSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgb2ZmbGluZV9hY2Nlc3MgZW1haWwifQ.ItELD77rkH-ecq9PLAsEIUQsP9YaCU2vIngakcRhXPg");

		driver_original = new RemoteWebDriver(new URL("https://dish-public.perfectomobile.com/nexperience/perfectomobile/wd/hub"), capabilities);
	}

NOTE: Due to security reasons, I had to provide an old securityToken value.  In versions 4.3.0 and 4.4.0, I get: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 401. Message: Failed 3 attempts to create access token in keycloak (took 21ms): com.perfecto.error.PerfectoAuthenticationException: Failed getting access token using token 'RhXPg'. Status:400 Error: Request POST https://auth8.perfectomobile.com/auth/realms/dish-public-perfectomobile-com/protocol/openid-connect/token failed with status 400. Status: Bad Request. Errors: [PerfectoError[{'error':'invalid_grant','error_description':'Offline user session not found'}]]. Status: Unauthorized. Status: Unauthorized
Build info: version: '4.4.0', revision: 'e5c75ed026a'
System info: host: 'FVFHNP5JQ6L4', ip: 'fe80:0:0:0:14b8:6d6a:d3e0:9f3b%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.2', java.version: '20.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: MAC, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}], desiredCapabilities=Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: MAC, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}}]
Capabilities {}

This is good.

In version 4.14.1, I get:
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'FVFHNP5JQ6L4', ip: 'fe80:0:0:0:14b8:6d6a:d3e0:9f3b%en0'
Build info: version: '4.14.1', revision: '03f8ede370'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.2', java.version: '20.0.2'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}]}]
Capabilities {browserName: Safari, browserVersion: 16, location: NA-US-BOS, platformName: mac, platformVersion: macOS Ventura, resolution: 800x600, securityToken: eyJhbGciOiJIUzI1NiIsInR5cCI...}

NOTE: A number of the capabilities that I provide are required by Perfecto so that their system can determine which web session to open up(location, resolution).

I hope this helps.

**Comment by titusfortner** [comment]
Your capabilities are not specification compliant. Check with Perfecto to see what namespace you need to use for their custom capabilities. Also, please use a browser options class rather than `DesiredCapabilities`.
