### ISSUE TITLE
[🐛 Bug]: add extension in headless=new not working

### ISSUE THREAD

**Issue by jramirezmorales** [SeleniumHQ/selenium#13244]
### What happened?

trying to add an extension to chromedriver with headless=new(supporting extension) is not working

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
      options.addArguments(
          "--no-sandbox",
          "--disable-gpu",
          "--headless=new",
          "--start-maximized",
          "--incognito",
          "--disable-dev-shm-usage",
          "--verbose",
          "--remote-debugging-port=0",
          "--user-data-dir=/app/tmp/chromeDataDir/",
          "--user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.96 Safari/537.36"
      );
      LoggingPreferences logPrefs = new LoggingPreferences();
      logPrefs.enable(LogType.BROWSER, Level.ALL);
      options.setCapability(ChromeOptions.LOGGING_PREFS, logPrefs);
      options.addExtensions(new File("proxy.crx"));
      options.setBinary("/usr/bin/google-chrome-stable");
      System.setProperty("webdriver.chrome.driver", KUBERNETES_CHROMEDRIVER);
      driver = new ChromeDriver(options);
```

### Relevant log output

```shell
{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (unknown error: DevToolsActivePort file doesn\u0027t exist)\n  (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

### Operating System

oracle/linux el8

### Selenium version

java21

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by jramirezmorales** [comment]
setting a specific port for debugging like "--remote-debugging-port=9222", it passes the DevToolsActivePort file error, but now it throws another error:
`{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: failed to wait for extension background page to load: chrome-extension://bplnjlbniaohahnllbncnbiaejoelikl/_generated_background_page.html\nfrom unknown error: page could not be found: chrome-extension://bplnjlbniaohahnllbncnbiaejoelikl/_generated_background_page.html
`

**Comment by NCLnclNCL** [comment]
> setting a specific port for debugging like "--remote-debugging-port=9222", it passes the DevToolsActivePort file error, but now it throws another error: `{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: failed to wait for extension background page to load: chrome-extension://bplnjlbniaohahnllbncnbiaejoelikl/_generated_background_page.html\nfrom unknown error: page could not be found: chrome-extension://bplnjlbniaohahnllbncnbiaejoelikl/_generated_background_page.html `

because extension is not allowed in --incognito if you do not allow it and use --load-extension to load extension folder

**Comment by diemol** [comment]
Looks like this might be related to Chrome exclusively.

**Comment by diemol** [comment]
These are the docs to add extensions https://www.selenium.dev/documentation/webdriver/browsers/chrome/#add-extensions, if after double checking the code it still fails, please report this to the Chrome team.

**Comment by jramirezmorales** [comment]
after removing the --incognito flag: 
`{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`

**Comment by NCLnclNCL** [comment]
> after removing the --incognito flag: `{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n (chrome not reachable)\n (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.)`

Use --no-sanbox and --load-extension=" extension folder"

**Comment by jramirezmorales** [comment]
same error, this is is not working
`{"success":false,"title":null,"message":{"resourceBundleName":"com.squareup.webservice.WebserviceMessages","key":"there.was.a.problem.processing.this.request","arguments":[]},"debugInfo":"org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location /usr/bin/google-chrome-stable is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Driver info: org.openqa.selenium.chrome.ChromeDriver\nCommand: [null, newSession {capabilities\u003d[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-sandbox, --headless\u003dnew, start-maximized, --disable-dev-shm-usage, --verbose, load-extension\u003d/playpen/, --remote-debugging-port\u003d9222, --user-agent\u003dMozilla/5.0 (X...], binary: /usr/bin/google-chrome-stable, extensions: [Q3IyNAMAAABFAgAAEqwECqYCMII...]}, goog:loggingPrefs: org.openqa.selenium.logging...}]}]\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)\n\tat org.openqa.selenium.remote.RemoteWebDriver.\u003cinit\u003e(RemoteWebDriver.java:168)\n\tat org.openqa.selenium.chromium.ChromiumDriver.\u003cinit\u003e(ChromiumDriver.java:108)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:89)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:84)\n\tat org.openqa.selenium.chrome.ChromeDriver.\u003cinit\u003e(ChromeDriver.java:73)`
