### ISSUE TITLE
[🚀 Feature]: Encrypt password for proxy in the se-config.toml file

### ISSUE THREAD

**Issue by Kalste** [SeleniumHQ/selenium#13241]
### Feature and motivation

In the "se-config.toml" file the password for the user for the proxy is not encrypted, please see screenshot.
This is a security problem, someone can look in the file and read the password.
![selenium-manager](https://github.com/SeleniumHQ/selenium/assets/33020490/e9201fb6-4dfe-4335-baa4-5b6d11bbee95)

### Usage example

The password for the proxy user is encrypted and no one can steal the password.

**Comment by diemol** [comment]
Who created the file? 

I mean, even if you paste there an encrypted password, Selenium Manager needs to read it and have it unencrypted. Given that Selenium Manager's code is public, it will be clear how to do that.

If you have security concerns, I recommend to treat that value as an environment variable.

**Comment by titusfortner** [comment]
@diemol you can just use `SE_PROXY` for this, right?
I don't think there's anything we should be doing here.

**Comment by diemol** [comment]
Yes, `SE_PROXY` is what I would use and keep those values in the system environment.

**Comment by Kalste** [comment]
It worked, thanks for your help.
Here is the documentation, https://www.selenium.dev/documentation/selenium_manager/
