### ISSUE TITLE
[🐛 Bug]: Selenium.Support 4.16.0 nuget is not valid

### ISSUE THREAD

**Issue by MaceWindu** [SeleniumHQ/selenium#13250]
### What happened?

`NU1202	Package Selenium.Support 4.16.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Selenium.Support 4.16.0 supports: supportnetstandard20`

cause: `lib` contains unknown TFM folder `supportnetstandard2.0` instead of `netstandard2.0`

### How can we reproduce the issue?

```shell
try to update nuget to 4.16.0
```

### Relevant log output

```shell
-
```

### Operating System

irrelevant

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

irrelevant

### What are the browser driver(s) and version(s) where you see this issue?

irrelevant

**Comment by NCLnclNCL** [comment]
> ### What happened?
> `NU1202 Package Selenium.Support 4.16.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Selenium.Support 4.16.0 supports: supportnetstandard20`
> 
> cause: `lib` contains unknown TFM folder `supportnetstandard2.0` instead of `netstandard2.0`
> 
> ### How can we reproduce the issue?
> ```shell
> try to update nuget to 4.16.0
> ```
> 
> ### Relevant log output
> ```shell
> -
> ```
> 
> ### Operating System
> irrelevant
> 
> ### Selenium version
> 4.16.0
> 
> ### What are the browser(s) and version(s) where you see this issue?
> irrelevant
> 
> ### What are the browser driver(s) and version(s) where you see this issue?
> irrelevant
> 
> ### Are you using Selenium Grid?
> _No response_

i see webdrivernetstandard2.0  instead of supportnetstandard2.0

**Comment by nvborisenko** [comment]
Will be a part of `v4.16.1`.
