### ISSUE TITLE
[🐛 Bug]: Nuget package version 4.16.0 is broken

### ISSUE THREAD

**Issue by andrei-mu** [SeleniumHQ/selenium#13254]
### What happened?

If I change my C# solution to use the newest package from NuGet, which is 4.16.0, I will get compile errors.
The reason is that the package is not correctly configured because of a naming issue: WebDriver.dll is placed in `.nuget\packages\selenium.webdriver\4.16.0\lib\webdrivernetstandard2.0\WebDriver.dll`, but should be placed in `.nuget\packages\selenium.webdriver\4.16.0\lib\netstandard2.0\WebDriver.dll` instead.

As proof, you can see the number of downloads is 0 for 4.16.0 in Nuget Galery: https://www.nuget.org/packages/Selenium.WebDriver/#versions-body-tab

### How can we reproduce the issue?

```shell
Everything is explained in the description.
```

### Relevant log output

```shell
error CS0246: The type or namespace name 'OpenQA' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'OpenQA' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'OpenQA' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'OpenQA' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IWebDriver' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'By' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IWebElement' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IWebDriver' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'IWebDriver' could not be found (are you missing a using directive or an assembly reference?)
```

### Operating System

Windows NuGet

### Selenium version

C# 11

### What are the browser(s) and version(s) where you see this issue?

Not aplicable

### What are the browser driver(s) and version(s) where you see this issue?

Not aplicable

### Are you using Selenium Grid?

no

**Comment by erxbout** [comment]
I also have a problem here (just as I wanted to get started with this library)

This error caught my eye:
```
NU1202: Package Selenium.Support 4.16.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Selenium.Support 4.16.0 supports: supportnetstandard20 (supportnetstandard2.0,Version=v0.0)
```

supportnetstandard20 seems sus to me, maybe its something in the build process?

Will change to 4.15 as it seems to work fine

**Comment by andrei-mu** [comment]
indeed @erxbout, it seems to be the same issue for a different package. A part of the name of the package is added to the dotnet version folder.

**Comment by ms6073** [comment]
Raising my hand as we are also observing this issue when trying to update Nuget package references for a framework that targets net 7.

> Package Selenium.Support 4.16.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Selenium.Support 4.16.0 supports: supportnetstandard20 (supportnetstandard2.0,Version=v0.0)

**Comment by nvborisenko** [comment]
This issue is already fixed (in scope of https://github.com/SeleniumHQ/selenium/issues/13250), will be shipped in `v4.16.1` soon. The team is working on it, sorry for inconvenience.

**Comment by ms6073** [comment]
Thanks for the quick follow-up and resolution.

**Comment by nvborisenko** [comment]
`4.16.1` is released, please confirm whether the issue is resolved. Thanks for your patience.

**Comment by ms6073** [comment]
Thanks. Was able to update a net 7 project to 4.16.1 without issue.

**Comment by diemol** [comment]
Thanks for confirming.

**Comment by erxbout** [comment]
Can also confirm, works now :D
Thank you for the fast resolution!
