### ISSUE TITLE
Selenium Web Application is not opening any Browser after deployment to iss

### ISSUE THREAD

**Issue by gsampath127** [SeleniumHQ/selenium#1325]
Hi I have created ASP>NET MVC Project for selenium.When I run the code in Visual Studio i can open all Browsers using selenium. But when I deploy the project to iis, no browser is opening. Please respond asp. Here, I am using WebDriver

**Comment by barancev** [comment]
It's working as intended. IIS runs as a service, it has no access to the desktop and can't run GUI programs (that a browser is).
