### ISSUE TITLE
[🐛 Bug]: selenium-manager regression downloading geckodriver when --avoid-browser-download option used

### ISSUE THREAD

**Issue by ktmcgrat** [SeleniumHQ/selenium#13267]
### What happened?

The 4.16.0 release  fails to download geckodriver 

```
selenium-manager --driver geckodriver --avoid-browser-download
ERROR	Not valid geckodriver version found for firefox 0
```

dropping the --avoid-browser-download works, but a full browser is also download too.  We connect to a hub and do not need the browser copy.  

4.15.0 for the same command works.

### How can we reproduce the issue?

```shell
To reproduce:

docker run -it python bash
python3 -m pip install selenium==4.16.0
/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/linux/selenium-manager --driver geckodriver --avoid-browser-download
```
```


### Relevant log output

```shell
TRACE	Checking geckodriver in PATH
DEBUG	geckodriver not found in PATH
TRACE	Checking firefox in PATH
DEBUG	firefox not found in PATH
TRACE	Using shell command to find out firefox version
DEBUG	firefox not found in the system
TRACE	Reading metadata from /root/.cache/selenium/se-metadata.json
TRACE	Metadata file does not exist. Creating a new one
DEBUG	Valid geckodriver versions for firefox 0: []
ERROR	Not valid geckodriver version found for firefox 0
```

### Operating System

linux

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

chrome 

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver

### Are you using Selenium Grid?

na

**Comment by diemol** [comment]
>DEBUG	firefox not found in PATH
TRACE	Using shell command to find out firefox version
DEBUG	firefox not found in the system

Seems you do not have Firefox installed on the expected locations, therefore Selenium Manager cannot find a matching GeckoDriver. If Firefox is installed via snap, you need to pass the browser binary location.

**Comment by titusfortner** [comment]
Where is your Firefox located? Geckodriver is picking it up?
