### ISSUE TITLE
Firefox requests Proxy for localhost / local network connections

### ISSUE THREAD

**Issue by Harinus** [SeleniumHQ/selenium#1326]
Hi,

i am experiencing the following issue:

Firefox requests Proxy for localhost / local network connections

How to reproduce:

-Use a localhost Proxy e.g. OWASP ZAP
-Use a local adress as base URL e.g. WebGoat
-Optional: (use empty profile with about:blank)

Code-Example:

```
import static org.junit.Assert.assertEquals;

import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class caseIDE {
    private WebDriver driver;
    private String baseUrl;

    @Before
    public void setUp() throws Exception {

        Proxy p = new Proxy();
        p.setHttpProxy("localhost:8080");
        p.setSslProxy("localhost:8080");
        p.setFtpProxy("localhost:8080");

        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability(CapabilityType.PROXY, p);

        FirefoxProfile fp = new FirefoxProfile();
        fp.setPreference("browser.startup.homepage", "about:blank");
        fp.setPreference("startup.homepage_welcome_url", "about:blank");
        fp.setPreference("startup.homepage_welcome_url.additional", "about:blank");
        driver = new FirefoxDriver(null, fp, cap);

        baseUrl = "http://localhost:9999";
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

    }

    @Test
    public void testIpw() throws Exception {
        driver.get(baseUrl + "/WebGoat");
        Thread.sleep(5000);
        assertEquals("1", "1");
    }

    @After
    public void tearDown() throws Exception {
        driver.quit();
    }
}
```

Expected: The WebGoat call gets proxied through OWASP ZAP.
Actual Result: A Proxy Authentication Pops up for the proxy that is set in IE. After dismissing it, the execution continues
Further info:
Firefox makes some automated calls to Mozilla which are supposed to happen. But they are not proxied through the Proxy set by WebDriver!? When using regular Firefox the behaviour does not occur

UPDATE:
Replacing `driver = new FirefoxDriver(null, fp, cap);`
with 

```
fp.setPreference("network.proxy.type", 1);
fp.setPreference("network.proxy.http", "localhost");
fp.setPreference("network.proxy.http_port", 8080);
driver = new FirefoxDriver(null, fp);
```

is a workaround which works.. so i assume that the issue is somewhere in the handling of the Capabilities

UPDATE2:
I had a more detailed look on the sources: (RemoteWebDriver.java and FirefoxDriver.java)

1.) startClient -> starts Firefox with the specified Profile
2.) startSessions -> submits the Capabilities to the Webdriver created in 1.)

There are a few Milliseconds delay where the Profile (if not using any preconfigured one) is set to "Use system proxy settings" because it is the default of Firefox: http://kb.mozillazine.org/Network.proxy.type. When the Driver receives the command to switch to localhost the proxy-popup caused by the automated request was already done.
-> Conclusion: Proxy settings must be set directly in the Profile and Capabilities should not be used for Proxy settings
Is there any way to make the Capabilities work?

**Comment by barancev** [comment]
As soon as there is a known workaround, this issue will never be fixed in legacy Firefox driver (unless someone provides a pull request). If geckodriver suffers of this issue, it should be reported to https://github.com/mozilla/geckodriver/issues
