### ISSUE TITLE
[🚀 Feature]: [rust] Stream Selenium Manager logs to console

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#13260]
### Feature and motivation

Selenium manager process can be executed with `--debug` flag, and then process output can be redirected to internal logs. Each time, when the process outputs a message in json format, we can translate it to .net logs.

### Usage example

User will be able to see SM output in his log handlers (Console, File).

**Comment by titusfortner** [comment]
@nvborisenko this is the same as what the other bindings are doing, correct? Thanks.

**Comment by nvborisenko** [comment]
I guess no. Here I am expecting that each log event, produced by SM, can be routed to the internal logging in binding, real-time.

I also observed that SM doesn't output log messages in real-time..

**Comment by titusfortner** [comment]
Yeah, I think we decided that it was more trouble than it was with to try to do it real time.

**Comment by titusfortner** [comment]
Should we close this and revisit if we decide to change SM?

**Comment by nvborisenko** [comment]
Up to you, I just proposed a feature.

**Comment by titusfortner** [comment]
Hmm, it's worth being tracked I think. I'm not sure I understood the STDOUT/STDERR differentiation until Simon explained it a few weeks ago. There is probably an improvement here that SM can make.

**Comment by titusfortner** [comment]
This would be fixed by #13414
