### ISSUE TITLE
[🐛 Bug]: Issues running tests on Windows 11 VM

### ISSUE THREAD

**Issue by Klarahov** [SeleniumHQ/selenium#13269]
### What happened?

I am setting up to run my automated Windows app tests in a new VM (Windows 11). They have been running green for months in another VM (Windows 10), but in the new VM, I’m getting an error "xpath locator strategy not supported" , when using FindElements(). On my own physical Win 11 PC, they also run green, so the issue is with my Win 11 VM (I tried two different VMs).
I am using Appium 2.x, Appium.WebDriver 4.4.5, and have the Windows driver installed. 
![image](https://github.com/SeleniumHQ/selenium/assets/79255275/98175fbf-1d20-4a3d-91ea-83f88e11a43c)
![image](https://github.com/SeleniumHQ/selenium/assets/79255275/a7016f5d-2b9b-49ad-89f1-650311516e02)

I also have other issues, like attributes not being fetched:
https://discuss.appium.io/t/no-attributes-are-being-recognized/40625
https://discuss.appium.io/t/action-sendkeys-command-not-recognized/40646

What could be the issue?

### How can we reproduce the issue?

```shell
Run a test in a Windows 11 VM.
```

### Relevant log output

```shell
See image above.
```

### Operating System

Windows 11

### Selenium version

Appium.WebDriver" Version="4.4.5"

### What are the browser(s) and version(s) where you see this issue?

Windows app

### What are the browser driver(s) and version(s) where you see this issue?

Windows app

**Comment by titusfortner** [comment]
Please update to the latest versions, Selenium 3.141.0 is now 5 years old.
If you still see a problem, I think this needs to be reported to https://github.com/appium/java-client/issues

**Comment by klarahovstadius** [comment]
Hi, thank you for the fast reply. I am using the latest Appium Webdriver nuget package, should this one make sure the Selenium version is up to date?

**Comment by Klarahov** [comment]
Hi, thank you for the fast reply. Appium WebDriver is not compatible with Selenium 4.x from my understanding.

**Comment by titusfortner** [comment]
Oh. .NET
Use Appium v5 beta

**Comment by klarahovstadius** [comment]
Hi,
Upgrading to Appium 5 beta works fine on my local PC. On the Win 11 VM, I'm getting another Selenium error message when creating the driver:
![image](https://github.com/SeleniumHQ/selenium/assets/79255275/4ee7900d-fdd3-4f7a-9fc9-c0e29b809eea)


![image](https://github.com/SeleniumHQ/selenium/assets/79255275/43e0bd26-aaae-45eb-83d5-697091f210d8)

**Comment by Klarahov** [comment]
Hi,
After upgrading to Appium 5 beta, I'm still encountering the same issue:
![image](https://github.com/SeleniumHQ/selenium/assets/79255275/33219673-2521-491e-b41e-4108e78743b7)

**Comment by diemol** [comment]
I think that was already fixed in Selenium Grid a while ago. You'd need to use the latest (4.16.1), but also you should report this to https://github.com/appium/dotnet-client if you still have issues.

**Comment by Klarahov** [comment]
I'm using Appium beta rc2 (latest Appium webdriver version) and it's the same error appearing. I am not sure which Selenium version is referenced but it's only 1 month old. I reported it a while back in an Appium forum but no one is replying (therefore I was so happily surprised by the fast responses here). If you think it's purely an Appium problem then I guess there is not much more to discuss here, but I was thinking that maybe it was a Selenium issue as well.
![image](https://github.com/SeleniumHQ/selenium/assets/79255275/a8267252-504e-4471-9284-7548d7d650d0)

**Comment by titusfortner** [comment]
Yes, this looks like an issue with windows driver specifically. The driver itself is not recognizing XPath as a valid way to locate elements.

**Comment by Klarahov** [comment]
Thanks very much for the clarification
