### ISSUE TITLE
[🐛 Bug]: setCapability does not work properly after upgrading Selenium version

### ISSUE THREAD

**Issue by HasiniRangana** [SeleniumHQ/selenium#13279]
### What happened?

When we create the driver object we set capability values as follows with selenium version 4.8.3. 

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("hub.url", "");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("browserName", "chrome");

But after updating the selenium version to 4.12.1 or 4.15.0, it doesn't work.

I found way to do it as follows.

        DesiredCapabilities capabilities = new DesiredCapabilities();
        ChromeOptions chromeOptions = new ChromeOptions();
        HashMap<String,String> chromeCapabilityMap = new HashMap<>();
        chromeCapabilityMap.put("browserName", "chrome");
        chromeCapabilityMap.put("hub.url", "");
        chromeOptions.setExperimentalOption("prefs", chromeCapabilityMap);

I need to know is this a bug or any proper solution for set capabilities.

### How can we reproduce the issue?

```shell
Add selenium 4.12.1 or 4.15.0 dependency to pom.xml file.
Then create driver object and set capability as follows.

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("hub.url", "");
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("browserName", "chrome");

After that run the test case and check.
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: '342-NB6SY9NN3', ip: '192.168.1.5'
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '19.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [], binary: C:\Program Files\Google\Chr..., extensions: []}, hub.url: }]}]
```

### Operating System

Windows

### Selenium version

4.15.0 or 4.12.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 119.0.6045.200

**Comment by diemol** [comment]
Since Selenium 4.10, only W3C WebDriver compliant [capabilities are supported](https://www.selenium.dev/blog/2022/legacy-protocol-support/).

If a capability is not in the [supported set](https://www.w3.org/TR/webdriver1/#capabilities), it needs to be prefixed.
