### ISSUE TITLE
[🐛 Bug]:  connecting to iOS device

### ISSUE THREAD

**Issue by af6140** [SeleniumHQ/selenium#13273]
### What happened?

When connecting to iOS device with selenium, it failed to acquire session, same error as described in https://github.com/SeleniumHQ/selenium/issues/12565

Tried two difference devices, it failes consistently on my iPhone 8 Plus(iOS 16.7.2).  Also tried both python and ruby version, same failure.

While troubleshooting the issue, looks like it successed in debug mode, so looks like with some old devices there are timing issue.

So when i tried to put a sleep after start safaridriver process like following and it starts working.

```python
self.process = subprocess.Popen(
                cmd,
                env=self.env,
                close_fds=close_file_descriptors,
                stdout=self.log_output,
                stderr=self.log_output,
                stdin=PIPE,
                creationflags=self.creation_flags,
                startupinfo=start_info,
                **self.popen_kw,
            )
            sleep(5)
```

### How can we reproduce the issue?

```shell
python code

from selenium import webdriver
from selenium.webdriver.safari.options import Options
from time import sleep
import logging

logging.basicConfig(encoding='utf-8', level=logging.DEBUG)


options = Options()
options.set_capability("platformName", "iOS")
options.set_capability("browserName", "safari")
options.set_capability("safari:deviceType", "iPhone")
options.set_capability('safari:useSimulator', False)

print(options.capabilities)
driver = webdriver.Safari(options=options)

#
driver.get("https://medium.com")
#
# # your further automation steps here
#
driver.quit()
``
```

### Relevant log output

```shell
As desribed in https://github.com/SeleniumHQ/selenium/issues/12565
```

### Operating System

macOS 14.1.2

### Selenium version

python 4.16.0

### What are the browser(s) and version(s) where you see this issue?

Safari 16.x

### What are the browser driver(s) and version(s) where you see this issue?

safaridriver Included with Safari 17.1.2 (19616.2.9.11.12)

**Comment by titusfortner** [comment]
This tracker is to identify things we can improve in this codebase.

If the log output is the same, then it looks like you need to enable automation on the Phone, which is something that you need to ask elsewhere about. If you're doing what you're supposed to for it, and it isn't working, then it is an issue for safaridriver, which is the resolution in the issue you previously linked. Either way, there isn't anything we can do in this repo to help you.
