### ISSUE TITLE
[🐛 Bug]: pom file missing devtools 119

### ISSUE THREAD

**Issue by jramirezmorales** [SeleniumHQ/selenium#13274]
### What happened?

seems like you forgot to publish the pom file in the latest release v4.16.0 for https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-devtools-v119/4.16.0/

### How can we reproduce the issue?

```shell
no code needed, just add the maven dependency and it will fail to download
```

### Relevant log output

```shell
ERROR: Error while fetching artifact with coursier: OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Resolution error: Error downloading org.seleniumhq.selenium:selenium-devtools-v119:4.16.0
  not found: https://maven.***/artifactory/org/seleniumhq/selenium/selenium-devtools-v119/4.16.0/selenium-devtools-v119-4.16.0.pom
```

### Operating System

macOS ventura 13.5

### Selenium version

java21

### What are the browser(s) and version(s) where you see this issue?

Chrome 116

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116.0.5845.96

**Comment by diemol** [comment]
Which is why 4.16.1 was released.
