### ISSUE TITLE
[🐛 Bug]: Unpredictable nuget package structure while releasing a package

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#13272]
### What happened?

`v4.16.0` was released with critical issue.

### How can we reproduce the issue?

```shell
You cannot install nuget package v4.16.0
```

### Relevant log output

```shell
https://github.com/SeleniumHQ/selenium/issues/13254
https://github.com/SeleniumHQ/selenium/issues/13250
```

### Operating System

any

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

any

### What are the browser driver(s) and version(s) where you see this issue?

any

### Are you using Selenium Grid?

no

**Comment by nvborisenko** [comment]
It happens:

![image](https://github.com/SeleniumHQ/selenium/assets/22616990/48ec8b7b-4bed-42bd-89f7-63446247174c)

**Comment by titusfortner** [comment]
What things do we need to include & exclude? We should be able to specify it all here, right?
