### ISSUE TITLE
[🐛 Bug]: Selenium-Java 4.16.1 cannot start in Spring Boot

### ISSUE THREAD

**Issue by yakup** [SeleniumHQ/selenium#13270]
### What happened?

I got the error when I started the project with Selenium-Java 4.16.1

Starting ChromeDriver 119.0.6045.105 (38c72552c5e15ba9b3117c0967a0fd105072d7c6-refs/branch-heads/6045@{#1103}) on port 64173
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1702042241.365][WARNING]: This version of ChromeDriver has not been tested with Chrome version 120.
2023-12-08 16:30:41.542  INFO 53239 --- [ null to remote] o.o.selenium.remote.ProtocolHandshake    : Detected dialect: W3C
2023-12-08 16:30:41.602  INFO 53239 --- [           main] o.o.selenium.devtools.CdpVersionFinder   : Found exact CDP implementation for version 120
2023-12-08 16:30:41.612  WARN 53239 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonCrawlerProviderApplication': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
2023-12-08 16:30:41.614  INFO 53239 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-12-08 16:30:41.617  INFO 53239 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-12-08 16:30:41.622  INFO 53239 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-12-08 16:30:41.623  INFO 53239 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-12-08 16:30:41.636  INFO 53239 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-12-08 16:30:41.659 ERROR 53239 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.openqa.selenium.devtools.v120.target.Target.getTargets(Target.java:153)

The following method did not exist:

    'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'

The calling method's class, org.openqa.selenium.devtools.v120.target.Target, was loaded from the following location:

    jar:file:/~/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v120/4.16.0/selenium-devtools-v120-4.16.0.jar!/org/openqa/selenium/devtools/v120/target/Target.class

The called method's class, org.openqa.selenium.devtools.ConverterFunctions, is available from the following locations:

    jar:file:/~/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.1.4/selenium-remote-driver-4.1.4.jar!/org/openqa/selenium/devtools/ConverterFunctions.class

The called method's class hierarchy was loaded from the following locations:

    org.openqa.selenium.devtools.ConverterFunctions: file:/~/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.1.4/selenium-remote-driver-4.1.4.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.openqa.selenium.devtools.v120.target.Target and org.openqa.selenium.devtools.ConverterFunctions

Disconnected from the target VM, address: '127.0.0.1:64413', transport: 'socket'

Process finished with exit code 1

### How can we reproduce the issue?

```shell
Use the dependency on Java 11 and Spring Boot 2.7.10

<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>4.16.1</version>
</dependency>
```

### Relevant log output

```shell
The log is defined above
```

### Operating System

MacOS Ventura 13.6.1

### Selenium version

Java 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 119.0.6045.105

### Are you using Selenium Grid?

No

**Comment by joerg1985** [comment]
Looks like there is a jar from Selenium version 4.1.4 on your classpath.

`jar:file:/~/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.1.4/selenium-remote-driver-4.1.4.jar`

I would suggest to check the dependencies, why this is not from version 4.16.1

**Comment by titusfortner** [comment]
This was written by one of our contributors:
https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

**Comment by boaty82** [comment]
I also get the issue that the dependent packages being downloaded are the wrong older version

4.16.1 results in 4.14.1 for all dependencies, and then during compilation it complains that `org.openqa.selenium.HasDownloads` cannot be found

**Comment by titusfortner** [comment]
please see the previous link for how to manage dependency conflicts.
@yakup can you verify your issue was a dependency conflict?

**Comment by diemol** [comment]
I think the issue is that Spring Boot [includes Selenium](https://github.com/spring-projects/spring-boot/blob/v3.2.0/spring-boot-project/spring-boot-dependencies/build.gradle#L1449). Please report the issue to them.

**Comment by yakup** [comment]
I refreshed dependencies in Maven window at Intellij IDEA and it worked ok. I guess it's about maven cache problem

**Comment by 712660518** [comment]
我也有同样的问题
感觉是maven仓库的原因，依赖已经是4.16.1.但是 Maven 搭建的环境还存在4.14.1

**Comment by zliang01** [comment]
springboot version，<selenium.version>4.16.1</selenium.version>

**Comment by ryshi** [comment]
same problem with a little difference

OS:  MacOS Sonoma 14.3
JDK: 21
Springboot: 3.1.8

dependencies:
```
    implementation 'org.seleniumhq.selenium:selenium-java:4.17.0'
    implementation 'io.github.bonigarcia:webdrivermanager:5.6.3'
```

error log:
```
java.lang.NoSuchMethodError: 'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'
	at org.openqa.selenium.devtools.v121.target.Target.getTargets(Target.java:153) ~[selenium-devtools-v121-4.17.0.jar!/:na]
	at org.openqa.selenium.devtools.v121.v121Target.getTargets(v121Target.java:55) ~[selenium-devtools-v121-4.17.0.jar!/:na]
	at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:160) ~[selenium-remote-driver-4.8.3.jar!/:na]
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:124) ~[selenium-remote-driver-4.8.3.jar!/:na]
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:109) ~[selenium-remote-driver-4.8.3.jar!/:na]
```

source code:
```java
        DevTools devTools = driver.getDevTools();
        devTools.createSession();
```

**Comment by titusfortner** [comment]
* You shouldn't need webdriver manager any longer
* I think this is most likely a guava dependency conflict —> https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html

**Comment by ryshi** [comment]
thx for replying
actually `webdrivermanager ` is used for locating local chrome. 
I tried to remove this part of code, but the problem is still there

btw, I found 2 possible conflict as below, I'll try to find a way out later.
<img width="515" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/1818419/1b9f83dc-478b-404f-9c52-7636f5a0485a">
<img width="528" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/1818419/02cc2587-b14c-45a2-8bf9-654a11eba46f">

**Comment by maguop** [comment]
> springboot version，<selenium.version>4.16.1</selenium.version>

it works for me,thanks

**Comment by titusfortner** [comment]
> actually webdrivermanager  is used for locating local chrome.

Yes, Selenium does this natively now.

**Comment by ryshi** [comment]
> > actually webdrivermanager  is used for locating local chrome.
> 
> Yes, Selenium does this natively now.

👍 got `webdrivermanager` removed
it seems hard to figure out the conflicts, so I choose downgrade back to 4.12.0

**Comment by yakup** [comment]
> please see the previous link for how to manage dependency conflicts. @yakup can you verify your issue was a dependency conflict?

It was a dependency conflict.

In Spring Boot's effective pom.xml, the Selenium version was defined as "4.1.4" and it was overriding the Selenium version I wrote in the pom.xml. After writing the code below everything worked perfectly.

`<properties>
      <selenium.version>4.16.0</selenium-version>
</properties>`

Sorry for my late reply.
