### ISSUE TITLE
[dotnet] Avoid temp file when download file

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#13276]
https://github.com/SeleniumHQ/selenium/blob/0d204d63111ab4e52eab6e226a17b1ddfa421c33/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L511C13-L511C13

We can extract zip file in memory, avoiding creation of temp file.

**Comment by titusfortner** [comment]
There was some issue I had getting that to work, but I can't remember now what it was.
