### ISSUE TITLE
does not recognise the driver exe which is already installed and is added in the PATH. [🐛 Bug]: 

### ISSUE THREAD

**Issue by enterashutosh** [SeleniumHQ/selenium#13284]
### What happened?

i was trying to run selenium in google colab,  for brave browser,
i followed tutorial of a professional and his .ipynb file (which itself is presently not working),

parallel to the code i've given, i've also:
>installed selenium 4.6 from command prompt
>downloaded chromedriver manually from website
>put the driver exe in the PATH by going through control panel (system environment variables)

chatGPT and Colab AI was used in troubleshooting but they keep me in a loop of same remedy over and over again.

### How can we reproduce the issue?

```shell
!pip install selenium==4.6.0
!apt-get update
!apt-get install -y chromium-chromedriver

from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

chrome_driver_path = r'C:\Program Files\ChromeDriver\chromedriver.exe'
brave_options = Options()
brave_options.binary_location = 'C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe'

driver = webdriver.Chrome(service=ChromeService(chrome_driver_path), options=brave_options)
```

### Relevant log output

```shell
---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py in start(self)
     96                 try:
---> 97                     path = SeleniumManager.driver_location(browser)
     98                 except WebDriverException as new_err:

7 frames
/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/selenium_manager.py in driver_location(browser)
     67         args = (str(SeleniumManager.get_binary()), "--browser", browser)
---> 68         result = SeleniumManager.run(args)
     69         command = result.split("\t")[-1].strip()

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/selenium_manager.py in run(args)
     84         if not re.match("^INFO\t", result):
---> 85             raise WebDriverException(f"Unsuccessful command executed: {args}")
     86 

WebDriverException: Message: Unsuccessful command executed: ('/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/linux/selenium-manager', '--browser', 'chrome')


During handling of the above exception, another exception occurred:

WebDriverException                        Traceback (most recent call last)
<ipython-input-62-8f906c96dc18> in <cell line: 1>()
----> 1 driver = webdriver.Chrome(service=ChromeService(chrome_driver_path), options=brave_options)
      2 driver.get('https://www.google.com')

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py in __init__(self, executable_path, port, options, service_args, desired_capabilities, service_log_path, chrome_options, service, keep_alive)
     79             service = Service(executable_path, port, service_args, service_log_path)
     80 
---> 81         super().__init__(
     82             DesiredCapabilities.CHROME["browserName"],
     83             "goog",

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py in __init__(self, browser_name, vendor_prefix, port, options, service_args, desired_capabilities, service_log_path, service, keep_alive)
    101 
    102         self.service = service
--> 103         self.service.start()
    104 
    105         try:

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py in start(self)
     98                 except WebDriverException as new_err:
     99                     logger.debug("Unable to obtain driver using Selenium Manager: " + new_err.msg)
--> 100                     raise err
    101 
    102                 self._start_process(path)

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py in start(self)
     89         """
     90         try:
---> 91             self._start_process(self.path)
     92         except WebDriverException as err:
     93             if "executable needs to be in PATH" in err.msg:

/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py in _start_process(self, path)
    201         except OSError as err:
    202             if err.errno == errno.ENOENT:
--> 203                 raise WebDriverException(
    204                     f"'{os.path.basename(self.path)}' executable needs to be in PATH. {self.start_error_message}"
    205                 )

WebDriverException: Message: 'C:\Program Files\ChromeDriver\chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
```

### Operating System

Windows 11

### Selenium version

Python 4.6.0

### What are the browser(s) and version(s) where you see this issue?

Brave 1.61.101 Chromium: 120.0.6099.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 99.0.4844.51

### Are you using Selenium Grid?

_No_

**Comment by diemol** [comment]
I don't know how Collab works, but what message do you get when using the latest selenium? We cannot fix old versions.

**Comment by titusfortner** [comment]
Chat GPT is really bad with driver management code because there are approximately 100,000 blogs and tutorials out there talking about manually setting up drivers when it is no longer needed...

**Comment by enterashutosh** [comment]
> I don't know how Collab works, but what message do you get when using the latest selenium? We cannot fix old versions.

cannot declare driver object, says, "WebDriverException: Message: 'C:\Program Files\ChromeDriver\chromedriver.exe' executable needs to be in PATH."

but the executable is very much in the PATH, i've tried both command line method and the control panel method, i've checked, it is in the path, i can see it.

**Comment by enterashutosh** [comment]
> Chat GPT is really bad with driver management code because there are approximately 100,000 blogs and tutorials out there talking about manually setting up drivers when it is no longer needed...

i did manual installation just in case the autoinstall was not executing some key parts of the process because of maybe the permissons factor, but i've done both.

**Comment by diemol** [comment]
Are you following a tutorial or something like that? If so, can you share the link? I am curious to see how it works there.

**Comment by enterashutosh** [comment]
> Are you following a tutorial or something like that? If so, can you share the link? I am curious to see how it works there.

it's a paid course so no i can't share the link sorry 😅

**Comment by diemol** [comment]
> > Are you following a tutorial or something like that? If so, can you share the link? I am curious to see how it works there.
> 
> it's a paid course so no i can't share the link sorry 😅

OK, if it is a paid course you should ask them why it is not working. We have not used Google Collab for this. Please share the solution they provide for you.

**Comment by titusfortner** [comment]
Wait chromedriver 99 with chromium 120? That won't work. Need to match versions.

**Comment by titusfortner** [comment]
We can't fix old versions, so if you need help getting an old version to work, you need to look elsewhere on the internet.
Please try with 4.16 and we can help if that doesn't resolve your issue. Also, seeing logging would help.

**Comment by diemol** [comment]
I was curious about Google Colab, so I went and tried it. A few comments:

- The environment is Linux based, and you are trying to use Windows binaries for the browser and driver. You need to find Linux binaries. 
- The following script worked for me.

```python
! pip3 install selenium

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import logging

logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)

options = Options()
options.add_argument('--headless=new')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome(options=options)
driver.get("http://www.google.com")
print(driver.title)
driver.quit()
```

It lets Selenium handle the browser and driver installation. You want to use Brave, so you should check how to install the browser there and find the appropriate driver, and set both in the options.

Here is a screenshot showing that Selenium works fine, so I am closing this issue.

![image](https://github.com/SeleniumHQ/selenium/assets/5992658/729583bb-c353-430a-ad63-eec062548d3a)

**Comment by enterashutosh** [comment]
> I was curious about Google Colab, so I went and tried it. A few comments:
> 
> * The environment is Linux based, and you are trying to use Windows binaries for the browser and driver. You need to find Linux binaries.
> * The following script worked for me.
> 
> ```python
> ! pip3 install selenium
> 
> from selenium import webdriver
> from selenium.webdriver.chrome.options import Options
> import logging
> 
> logger = logging.getLogger('selenium')
> logger.setLevel(logging.DEBUG)
> 
> options = Options()
> options.add_argument('--headless=new')
> options.add_argument('--no-sandbox')
> options.add_argument('--disable-dev-shm-usage')
> driver = webdriver.Chrome(options=options)
> driver.get("http://www.google.com")
> print(driver.title)
> driver.quit()
> ```
> 
> It lets Selenium handle the browser and driver installation. You want to use Brave, so you should check how to install the browser there and find the appropriate driver, and set both in the options.
> 
> Here is a screenshot showing that Selenium works fine, so I am closing this issue.
> 
> ![image](https://private-user-images.githubusercontent.com/5992658/289867205-729583bb-c353-430a-ad63-eec062548d3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODc2NDAsIm5iZiI6MTcwMjM4NzM0MCwicGF0aCI6Ii81OTkyNjU4LzI4OTg2NzIwNS03Mjk1ODNiYi1jMzUzLTQzMGEtYWQ2My1lZWMwNjI1NDhkM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTMyMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM4ZDFmNjA3N2Q4MmEzMzY0ODk0ODAzODdiYzMwOWM2YTJkM2U1MGNiMjE1ZWZhMWM4ZTM0YjU5Njg2ZmViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e2SNO_m1Fwey--2m-DPFI8b4P3is9qUAqqEDpL713GQ)

thanks, it worked for me too, there's a lot to unpack here but thankyou very much, i've been looking for something like this for days
