### ISSUE TITLE
[🚀 Feature]: Selenium Manager to track language usage

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13288]
### Feature and motivation

With #11211 Selenium Manager will send basic usage data to Plausible. One of the things it will send is language info. Each binding needs to implement sending `--language-binding <language>`

### Usage example

Internal implementation:
```
seleniumManagerPath --browser chrome --language-binding java
```

**Comment by diemol** [comment]
Implemented in all languages, and also added `SE_AVOID_STATS=true` to our CI builds.
