### ISSUE TITLE
Selenium IDE is not installing in Firefox

### ISSUE THREAD

**Issue by Abhijeetchitransh** [SeleniumHQ/selenium#1329]
Getting "500 Internal Server Error
nginx/1.8.0"

while trying to install Selenium IDE from http://www.seleniumhq.org/download/

**Comment by AJ-72** [comment]
@Abhijeetchitransh Pls update the FF version and IDE version you tried

**Comment by stupidnetizen** [comment]
can you please check if this is not related to #1382 . What version of the Firefox you are using?

**Comment by wolftian** [comment]
After input “About:config” and close the addon signature of Firefox, the selenium works well.
While Firefox will drop the setting from Firefox 44, and the solution will not work.
Then as a result, we may need to sign the Firefox Webdriver from Firefox. 
Do we have a plan to do that?

**Comment by Abhijeetchitransh** [comment]
Issue is resolved when downgraded Firefox.

**Comment by lukeis** [comment]
this should be fixed by installing Selenium IDE from addons.mozilla.org (which is now what is linked from seleniumhq.org/download )
