### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by Trippixyz** [SeleniumHQ/selenium#13296]
### What happened?

I get an error whenever I try to compile Selenium.Net.

I precisely followed these 2 tutorials but they didn't work out:
[Guide 1 (Blogpost)](https://jimevansmusic.blogspot.com/2020/04/setting-up-windows-development.html)
[Guide 2 (Github Markdown)](https://gist.github.com/titusfortner/aec103e9b02709f771497fdb8b21154c)

The error can be found in the log output tab!

### How can we reproduce the issue?

```shell
Follow the steps that from any of the 2 tutorials.
```

### Relevant log output

```shell
PS C:\users\Trippi\source\libraries\selenium> bazel build //dotnet/test/common:chrome
Starting local Bazel server and connecting to it...
ERROR: Skipping '//dotnet/test/common:chrome': no such target '//dotnet/test/common:chrome': target 'chrome' not declared in package 'dotnet/test/common' defined by C:/users/trippi/source/libraries/selenium/dotnet/test/common/BUILD.bazel (Tip: use `query "//dotnet/test/common:*"` to see all the targets in that package)
WARNING: Target pattern parsing failed.
ERROR: no such target '//dotnet/test/common:chrome': target 'chrome' not declared in package 'dotnet/test/common' defined by C:/users/trippi/source/libraries/selenium/dotnet/test/common/BUILD.bazel (Tip: use `query "//dotnet/test/common:*"` to see all the targets in that package)
INFO: Elapsed time: 10.265s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
PS C:\users\Trippi\source\libraries\selenium>
```

### Operating System

Windows 11

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

Chrome?

### What are the browser driver(s) and version(s) where you see this issue?

None

**Comment by titusfortner** [comment]
Yes, those docs need to be updated.
We recently got a lot of .NET things working in Bazel, so the endpoint are all udpated.
Try: ` bazel test //dotnet/test/common:AllTests` or just `bazel test //dotnet/...`

**Comment by titusfortner** [comment]
I'm actually hoping that bazel figured out it's C++ toolchain issues and all those steps aren't actually necessary any more.

Come find us on Selenium Slack (selenium-tlc channel) if you want to discuss more: https://www.selenium.dev/support/#ChatRoom
