### ISSUE TITLE
[🚀 Feature]: Node.js version with firefox missing full page screenshot option

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#13301]
### Feature and motivation

I have tried python version with firefox driver, it has a extra method for firefox `driver.save_full_page_screenshot(screenshot_path)`.
Samething is missing for Node.js version.

We can use `const image = await body.takeScreenshot(true)` to take screenshot of whole page but it not same as `save_full_page_screenshot`. `body.takeScreenshot` it will scroll to the bottom when taking screenshot and if you have fixed header, header will be at the end of the page. `driver.takeScreenshot` does not take screenshot of whole page.

I assume it is a firefox only feature and uses built-in firefox screenshot tool. It works well with floating button and fixed header.

### Usage example

```
await firefoxDriver.saveFullPageScreenshot(screenshot_path);
```

**Comment by ghost** [comment]
I have added example code with screenshot at the end

python

```

import time
import selenium.webdriver


options = selenium.webdriver.FirefoxOptions()
options.add_argument('--headless')


with selenium.webdriver.Firefox(options=options) as driver:
    page_url = 'https://chenzhihao.github.io/sticky-Nav/'
    driver.get(page_url)
    time.sleep(1)
    screenshot_path = 'screenshot.png'
    driver.save_full_page_screenshot(screenshot_path)
```

Node.js

```

import fs from 'fs';
import { Builder, By } from 'selenium-webdriver';


const driver = await new Builder().forBrowser("firefox").build();

await driver.get('https://chenzhihao.github.io/sticky-Nav/');

const body = driver.findElement(By.css('body'));

await new Promise(resolve => setTimeout(resolve, 1000));

const image = await body.takeScreenshot(true)
fs.writeFile('screenshot2.png', image, 'base64', console.log);

const image3 = await driver.takeScreenshot()
fs.writeFile('screenshot3.png', image3, 'base64', console.log);

await driver.quit();

```


<details>
<summary>Python Screenshot</summary>
<img src="https://github.com/SeleniumHQ/selenium/assets/138362200/b7538f80-9c65-4261-b1c6-94228c6f6b70"/>
</details>


<details>
<summary>Node.js Screenshot with body (navbar header is at bottom)</summary>
<img src="https://github.com/SeleniumHQ/selenium/assets/138362200/57643978-7262-481b-ab09-a97c3ab5287c"/>
</details>


<details>
<summary>Node.js Screenshot with driver (not full page)</summary>
<img src="https://github.com/SeleniumHQ/selenium/assets/138362200/7a186d90-a872-44b9-bb42-1520139e6b8e"/>
</details>

**Comment by harsha509** [comment]
Landed changes with commit https://github.com/SeleniumHQ/selenium/commit/111941bd3ceaceed44985e22b00f4eab44a69a5d !

Closing as resolved.
