### ISSUE TITLE
[🐛 Bug]: Using CDP in multiple tabs

### ISSUE THREAD

**Issue by grayglj** [SeleniumHQ/selenium#13300]
### What happened?

Hi,To inspect network traffic, i use AttachToTarget to switch session between multiple tabs in chome, but the newly created session 
always be bound with the last opened tab.

### How can we reproduce the issue?

```shell
//fist: open google manually
//second:open manual stackoverflow
public void Test(ChromeDriver currentDriver)
{
    DevToolsSession originalSession = currentDriver.GetDevToolsSession();

    //google's taregetId xxxxxx1(ex) 
    //stackoverflow targetId: xxxxxx2(ex) 
    var allTargets = originalSession.Domains.Target.GetTargets().Result.Where(t => t.Type == "page").ToList();

    foreach (var target in allTargets)
    {
        currentDriver.CloseDevToolsSession();

        //newSession's ActiveSessionId and attachedTargetid are null now.
        var newSession = currentDriver.GetDevToolsSession();

        var attachResult = newSession.Domains.Target.AttachToTarget(target.TargetId).Result;

        //here,newSession's ActiveSessionId and attachedTargetid have value.
        //but the attachedTargetid always be same as xxxxxx2 which last opened in Chrome.
        string fordebug = "";
    }
}
```

### Relevant log output

```shell
no logs.
```

### Operating System

Windows 10

### Selenium version

4.16.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.71 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.71

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
I know that you need to create a new DevTools session per tab, I just do not know how to do that in C#. 

@nvborisenko do you know how to do that?

**Comment by nvborisenko** [comment]
Session implementation supposed to be initialized before creating new tabs in the browser. Behind of scene it attaches some unpredictable `target` (probably the latest one, hopefully the active one), and use auto-attach CDP feature. So then Session can "track" newly created targets.

More details about initialization: https://github.com/SeleniumHQ/selenium/blob/5b1b4490979a579716381a42f77ac5e4cf8f5e7b/dotnet/src/webdriver/DevTools/DevToolsSession.cs#L367C9-L367C9

```csharp
                var targets = await this.domains.Target.GetTargets().ConfigureAwait(false);
                foreach (var target in targets)
                {
                    if (target.Type == "page")
                    {
                        this.attachedTargetId = target.TargetId;
                        LogTrace("Found Target ID {0}.", this.attachedTargetId);
                        break;
                    }
                }
```

@EdwinVanVliet tries to improve it, especially your case (network event monitoring for different tabs https://github.com/SeleniumHQ/selenium/pull/10603).

**Comment by titusfortner** [comment]
@nvborisenko does #13330 fix this, then?

**Comment by nvborisenko** [comment]
Potentially, not 100% sure. That PR brings a possibility to "pause" newly opened tab in browser. Will see.

**Comment by titusfortner** [comment]
@nvborisenko is there something we know we want to do here beyond what we've done for 4.17?

**Comment by diemol** [comment]
The referenced PR was merged, and if something is still needed we can always reopen this issue.
