### ISSUE TITLE
[🐛 Bug]: POM file missing for selenium-devtools-v119 4.16.0

### ISSUE THREAD

**Issue by vijay0850** [SeleniumHQ/selenium#13320]
### What happened?

Hi,

We using selenium devtools v119 artifact version:4.16.0 for our automation project, we keep getting no POM file/POM file missing error so we checked the path and understool it was not available.

https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-devtools-v119/4.16.0/

<img width="854" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/10095173/34a0d4b4-6ced-4ff3-9495-e11b8756704b">

### How can we reproduce the issue?

```shell
Please see the below link for missing pom file

https://repo.maven.apache.org/maven2/org/seleniumhq/selenium/selenium-devtools-v119/4.16.0/
```

### Relevant log output

```shell
[WARNING] The POM for org.seleniumhq.selenium:selenium-devtools-v119:jar:4.16.0 is missing, no dependency information available
```

### Operating System

Windows 11

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

**Comment by baflQA** [comment]
Hey - update to 4.16.1.
https://github.com/SeleniumHQ/selenium/commit/9b4c83354e69bea04078ceb3a37d69ebf38f3ad5

**Comment by diemol** [comment]
What @baflQA, said. Thank you!
