### ISSUE TITLE
FirefoxDriver: trying to upload an non-existant file fails silently

### ISSUE THREAD

**Issue by lqc** [SeleniumHQ/selenium#1332]
The following code:

https://github.com/SeleniumHQ/selenium/blob/6e1e6c1fed3674815c16048dbbd32cb0c1db84cc/javascript/firefox-driver/js/wrappedElement.js#L137

triggers a `change` event even if the file with given path does not exists an the `element.value =` is a noop. This can be confusing for application code and (with recent enhancements in IEDriverServer) is inconsistent with other driver implementations 

PS. The W3C spec seems to be completely ignore the existance of `<input type="file">`.

**Comment by barancev** [comment]
Closing this issue because we'll hardly fix it in legacy xpi-based Firefox driver.

The new geckodriver-based driver does not fail silently, it throws `org.openqa.selenium.InvalidArgumentException` with `File not found` message.
