### ISSUE TITLE
[🐛 Bug]: "getSize" method only return layout(setting) size instead of viewport (actually displayed) issue

### ISSUE THREAD

**Issue by Erix377** [SeleniumHQ/selenium#13337]
### What happened?

Here is the situation: My target element has a parent element which covers this target element. For the parent element, it has been scaled twice, which leads to my target element has also been scaled twice and increases the view size in the browser.

For example, the original target size is (40,21),which is also written in the html file, since its parent has been scaled twice, thus currenntly its view size become (80,42). And if we use "getSize" method on the target element, it returned the original setting size (40,21). So if I want to get the scaled size(actually displayed size), what other methods can selenium provide? 

I have already tried "getRect" method, which also only returns original setting size rather than actually displayed size.

Besides, there is a feasible way, which is using javascript method "element.getBoundingClientRect()" can return the acutally view size.
<img width="1423" alt="Screenshot 2023-12-06 at 11 40 39 AM" src="https://github.com/SeleniumHQ/selenium/assets/111478885/8b35c06e-c98b-42fe-875d-aefd1a166a7c">

<img width="1217" alt="Screenshot 2023-12-06 at 11 41 11 AM" src="https://github.com/SeleniumHQ/selenium/assets/111478885/308a50a2-0e17-4541-989b-502bc1be12d3">

### How can we reproduce the issue?

```shell
You can create an element and add a parent element outside the target element. Set the scale attribute of parent element as 2 and then observe in browser. You can see the target element has also been scaled. Besides, if you click the target element with dev mode in browser and you will find the current displayed size is twice as settings. 

And then use "getSize" or "getRect" methods on the target element only returns the original setting size rather than current view size. 

But if you use "element.getBoundingClientRect()" method, which will return the scaled size.
```

### Relevant log output

```shell
None
```

### Operating System

Mac, Windows, Linux 

### Selenium version

Java 4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  119.0.6045.159 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver-v0.33.0-macos-aarch64, chromedriver

**Comment by titusfortner** [comment]
This is going to be a request of the spec, because Selenium is requesting/returning what is currently specified.
