### ISSUE TITLE
[🚀 Feature]: The ability to change the client timeout of Selenium Grid to more than 3 minutes

### ISSUE THREAD

**Issue by tking16** [SeleniumHQ/selenium#13340]
### Feature and motivation

My test setup requires more time to get started as it involves multiple iOS Simulators (at least four), but the tests will timeout due it's 3 minute default as stated [here](https://github.com/SeleniumHQ/selenium/issues/11881#issuecomment-1519637131) this is currently non-configurable but would be great to be able to make this timeout longer.

### Usage example

To actually reproduce the issue it's best to start testing with no emulators currently running. Create 4-6 `appium.yaml` files and the same amount of `node.toml` files and use pytest-xdist to setup parallel testing within Selenium Grid. 

After a while You should see the error:
```
E       selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. java.net.http.HttpTimeoutException: request timed out
```

**Comment by diemol** [comment]
That is the timeout [this client](https://github.com/SeleniumHQ/selenium/blob/fea3ddd3af9dad2b576e12fedf37c3f6ce1920c3/java/src/org/openqa/selenium/grid/node/remote/RemoteNode.java#L92) should use. 

The ideal solution would be to add the configured `session-timeout` from the Node to the `NodeStatus` and use that one when the `RemoteNode` object is created.
