### ISSUE TITLE
[🚀 Feature]: Add integration with WebBLE API of Google Chrome for Test Automation purpose

### ISSUE THREAD

**Issue by ShinjiruPP** [SeleniumHQ/selenium#13346]
### Feature and motivation

Hello everyone,

I am writing this feature proposal for the Selenium project because Chromium has introduced APIs to interact with BLE device connections to the browser automatically.

The request is to integrate the call to these APIs within the Selenium project in order to automate the pairing process between devices and the browser.

Following the link to the bug resolved by chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1410257

Thank you very much!

### Usage example

This could be really useful for web Test Automation where instead of simulate the keyboard in order to select the device from scan list of near device via BLE, the selenium library can call directly the WebBLE API in order to pair device.

**Comment by titusfortner** [comment]
You need to request this of Google to implement endpoints as necessary in chromedriver. Once that happens we can add the functionality to Selenium.
