### ISSUE TITLE
[🐛 Bug]: When trying to run scripts in Saucelabs through Jenkins, unable to run tests on MAC OS -Safari Browser

### ISSUE THREAD

**Issue by shriganesh1987** [SeleniumHQ/selenium#13355]
### What happened?

Below is the code snippet used for MAC OS -Safari Browser to run the tests on Saucelabs through Jenkins:
if(null != strBrowserName && strBrowserName.equalsIgnoreCase("Safari")){
			
				log.info(USERNAME);
				log.info(ACCESS_KEY);
				
				System.out.println("In Safari");
				SafariOptions browserOptions = new SafariOptions();
                                browserOptions.setPlatformName("macOS 10.15");
                                browserOptions.setBrowserVersion("13.1");
                                browserOptions.setCapability("acceptInsecureCerts", true);
                                browserOptions.setCapability("unhandledPromptBehavior", "accept");
				
				
				Map<String, Object> sauceOptions = new HashMap<>();
				sauceOptions.put("username",USERNAME);
                                sauceOptions.put("accessKey",ACCESS_KEY);
                                sauceOptions.put("build", System.getenv("JENKINS_BUILD_NUMBER"));
				sauceOptions.put("idleTimeout", 1000);
				sauceOptions.put("screenResolution", "1280x960");
                                browserOptions.setCapability("sauce:options", sauceOptions);
				
				try {
					System.out.println(URL);
					this.driver = new RemoteWebDriver(new URL(URL), browserOptions);
					this.sessionId = (((RemoteWebDriver) this.driver)
							.getSessionId()).toString();
					System.out.println(sessionId);
					log.info("DRIVER SUCCESSFULLY CREATED");
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				System.out.println("In Safari 2");
				
			}
			
			//code for test
			this.driver.get(getConfigLocator("appurl"));'

### How can we reproduce the issue?

```shell
Code Used:
if(null != strBrowserName && strBrowserName.equalsIgnoreCase("Safari")){
			
				log.info(USERNAME);
				log.info(ACCESS_KEY);
				
				System.out.println("In Safari");
				SafariOptions browserOptions = new SafariOptions();
                                browserOptions.setPlatformName("macOS 10.15");
                                browserOptions.setBrowserVersion("13.1");
                                browserOptions.setCapability("acceptInsecureCerts", true);
                                browserOptions.setCapability("unhandledPromptBehavior", "accept");
				
				
				Map<String, Object> sauceOptions = new HashMap<>();
				sauceOptions.put("username",USERNAME);
                                sauceOptions.put("accessKey",ACCESS_KEY);
                                sauceOptions.put("build", System.getenv("JENKINS_BUILD_NUMBER"));
				sauceOptions.put("idleTimeout", 1000);
				sauceOptions.put("screenResolution", "1280x960");
                                browserOptions.setCapability("sauce:options", sauceOptions);
				
				try {
					System.out.println(URL);
					this.driver = new RemoteWebDriver(new URL(URL), browserOptions);
					this.sessionId = (((RemoteWebDriver) this.driver)
							.getSessionId()).toString();
					System.out.println(sessionId);
					log.info("DRIVER SUCCESSFULLY CREATED");
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				System.out.println("In Safari 2");
				
			}
			
			//code for test
			this.driver.get(getConfigLocator("appurl"));
			
Operating System
MAC OS
Selenium version
4.11.0
What are the browser driver(s) and version(s) where you see this issue?
Safari macOS 10.15
```

### Relevant log output

```shell
org.openqa.selenium.UnsupportedCommandException:
The command 'POST /session/09C90313-E5AC-44FC-BA57-6BFAE81453C5/se/log' was not found.

Could not start a new session. Response code 500. Message: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://docs.saucelabs.com/dev/error-messages 
Host info: host: 'hvnplcbjwa02', ip: '10.34.44.142'
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.102.1.el7.x86_64', java.version: '11.0.21'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
```

### Operating System

MacOS

### Selenium version

4.11

### What are the browser(s) and version(s) where you see this issue?

10.15

### What are the browser driver(s) and version(s) where you see this issue?

Safari macOS 10.15

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
What's the full stack trace? Are you calling the log method?
Add `seleniumVersion` to your `sauce:options`.  MacOS 15 is 4 years old, Sauce might default it to Selenium 3 grid.

**Comment by diemol** [comment]
I'll close this because we did not get more information. You should probably reach out to the Sauce Labs support.
