### ISSUE TITLE
[🚀 Feature]: Appium like direct connections

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13357]
### Feature and motivation

Appium does support to set a capability to allow direct access to the public endpoint of the node instead of routing through the grid.

https://www.headspin.io/blog/connecting-directly-to-appium-hosts-in-distributed-environments

### Usage example

This can help to reduce latency and improve throughput when using a distributed service.

There are some points that could be improved over the appium way, e.g. use a single capability for the node endpoint. But in general i think this is something good that could be upstreamed.

**Comment by diemol** [comment]
I do not see a lot of value here. This feature was built for Headspin because that is how they handle their architecture. I would invest in this if this is something commonly requested by users with Grids that would benefit similarly. I would not work on this to make a single cloud provider; it would need to be something that benefits most of them.

**Comment by titusfortner** [comment]
I'm confused. How is this different from starting a standalone server and allowing remote connections?

**Comment by joerg1985** [comment]
@titusfortner in this configuration the grid acts like a loadbalancer over multiple node servers. After a session is assigned to a single node a direct connection will handle the traffic and not route it over the grid server.

**Comment by diemol** [comment]
Right, but this was a feature built specifically for a company, rather than having something that helps the community in general, which is why I do not see the value here.

**Comment by joerg1985** [comment]
I did expect this would be interesting for some cloud providers (like BrowserStack), to reduce the traffic / latency.

But it looks like this is not the case, so this can be closed.
