### ISSUE TITLE
[🐛 Bug]:  file upload did not work with Firefox 120

### ISSUE THREAD

**Issue by qb90** [SeleniumHQ/selenium#13365]
### What happened?

It's impossible to use file upload with Firefox ver. 120 image.
selenium/standalone-firefox:120.0
Selected file is not visible in uploader.
![up1](https://github.com/SeleniumHQ/selenium/assets/16085506/03ea5217-7579-4499-ac4f-a40c83d8833a)

It works with Firefox 114.
selenium/standalone-firefox:114.0

Path to the file : 
project_root/selenium/tests/_data/file_example.xml

About the project :
PHP and Codeception
https://github.com/Codeception/Codeception/tree/4.1.20
(right now it's impossible to upgrade PHP and framework version)

Related issue:
[12780](https://github.com/SeleniumHQ/selenium/issues/12780)

### How can we reproduce the issue?

```shell
Try to upload a file with Firefox 120 and 114
Part of the form
`<input id="uploadedFile" type="file" name="uploadedFile">`
```

### Relevant log output

```shell
Caps: Capabilities 
{acceptInsecureCerts: false, browserName: firefox, browserVersion: 120.0.1, 
moz:accessibilityChecks: false, moz:buildID: 20231129155202, moz:geckodriverVersion: 0.33.0, moz:headless: false,
 moz:platformVersion: 5.15.133.1-microsoft-standa..., moz:processID: 192, moz:profile: /tmp/rust_mozprofileJ3kdFj, 
moz:shutdownTimeout: 60000, moz:webdriverClick: true, 
moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, 
se:cdp: ws://172.17.0.2:4444/sessio..., se:noVncPort: 7900, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, 
se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, 
timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}

ABOUT SELENIUM GRID
`OS Version: 5.15.133.1-microsoft-standard-WSL2
Grid version: 4.16.1 (revision 9b4c83354e)
```

### Operating System

Win10

### Selenium version

Webdriver

### What are the browser(s) and version(s) where you see this issue?

Firefox 120

### What are the browser driver(s) and version(s) where you see this issue?

geckodriverVersion: 0.33.0

### Are you using Selenium Grid?

4.16.1

**Comment by ksingha161** [comment]
In selenium grid, are you using `((RemoteWebElement) webelement).setFileDetector(new LocalFileDetector());` to upload a file?

**Comment by qb90** [comment]
How I run docker with selenium
`docker run -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-firefox:120.0`

In PHP and Codeception it looks like this
https://codeception.com/docs/modules/WebDriver#attachFile
example from this site
`// file is stored in 'tests/_data/prices.xls'
$I->attachFile('input[@type="file"]', 'prices.xls');`

Part of my form:
`<input id="uploadedFile" type="file" name="uploadedFile">`
so I have
`$I->attachFile('input[name="uploadedFile"]', $fileName);`

PHP and framework version are the same - only Firefox version is higher.

**Comment by titusfortner** [comment]
I can't reproduce this, and I'm also not sure how to troubleshoot the php code, you might need to raise the issue with codeception to see if they can show you how to get logs or verify which version of Firefox broke things..
