### ISSUE TITLE
[🐛 Bug]: Selenium 4.16: Unable to obtain driver for chrome using Selenium Manager (Mac OS 10.13.6 Chrome 116.0.5845.187 Python 3.11)

### ISSUE THREAD

**Issue by jim6301** [SeleniumHQ/selenium#13367]
### What happened?

Error when running the following Python code in Pycharm 2022.3.3

from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://www.amazon.com/")
driver.quit()

Error shown:
Message: Unable to obtain driver for chrome using Selenium Manager.

### How can we reproduce the issue?

```shell
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("https://www.amazon.com/")
driver.quit()
```

### Relevant log output

```shell
/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/bin/python /Users/jimhaysmm/PycharmProjects/SSAutomation2/main.py 
Traceback (most recent call last):
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 137, in run
    output = json.loads(stdout)
             ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 103, in driver_location
    output = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 140, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}") from err
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/main.py", line 3, in <module>
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location


Process finished with exit code 1
```

### Operating System

Macintosh OS 10.13.6 (High Sierra)

### Selenium version

Selenium 4.16 (Python)

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 116.0.5845.187

### What are the browser driver(s) and version(s) where you see this issue?

built-into Selenium?

**Comment by titusfortner** [comment]
What do you get when you execute this from terminal:
```
/Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug
```

**Comment by jim6301** [comment]
Titus:

Thanks for trying to help me with this issue; below is the result of executing the command you provided in the terminal.

Jims-Mac-Mini:~ jimhaysmm$ /Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --debug
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager
  Reason: Incompatible library version: selenium-manager requires version 10.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6

Jim

**Comment by titusfortner** [comment]
So, you need to update that library on your system. This isn't a Selenium issue, but I'm pasting chat-gpt response:

## Chat GPT Says...

The error message is indicating that the `selenium-manager` binary requires a newer version of the `liblzma` library, specifically version `10.0.0` or later, but the one that it finds in the library path `/usr/local/opt/xz/lib` is an older version, `6.0.0`.

This is a classic dynamic linking issue on macOS, where a binary is linked against a shared library, and the system cannot find the correct version of that library at runtime.

Here's how you can try to fix the issue:

1. **Update the `xz` package** that provides `liblzma`:
   
   If you have Homebrew installed, you can update all your packages, which should include `xz`, and thus `liblzma`. Open a terminal and run:

   ```bash
   brew update
   brew upgrade
   ```

   If you specifically want to update just `xz`, run:

   ```bash
   brew update
   brew upgrade xz
   ```

2. **Checking the Installation**:

   After updating, check if the correct version of `liblzma` is now available:

   ```bash
   ls -l /usr/local/opt/xz/lib/liblzma.5.dylib
   ```

3. **Check your shared library cache**:

   You can update the dynamic linker cache with the following command:

   ```bash
   sudo update_dyld_shared_cache
   ```

4. **Check for multiple `liblzma` installations**:

   It's possible to have multiple versions of `liblzma` installed, which can confuse the dynamic linker. You can locate all versions of `liblzma.5.dylib` with:

   ```bash
   find / -name liblzma.5.dylib 2>/dev/null
   ```
   
   To see which `liblzma` would load by default, run:

   ```bash
   otool -L /Users/jimhaysmm/PycharmProjects/SSAutomation2/venv/lib/python3.11/site-packages/selenium/webdriver/common/macos/selenium-manager
   ```

5. **If necessary, set your library path**:

   If `liblzma` is installed in a non-standard directory, you may need to add it to the `DYLD_LIBRARY_PATH` environment variable, or install the library in a location where the dynamic linker will find it.

   ```bash
   export DYLD_LIBRARY_PATH=/path/to/custom/liblzma:$DYLD_LIBRARY_PATH
   ```
   
   Replace `/path/to/custom/liblzma` with the path to the directory containing the updated `liblzma.5.dylib`. However, use this cautiously, as changing `DYLD_LIBRARY_PATH` can affect dynamic linking for all processes and lead to system instability. 

Before you proceed with library path changes, it's recommended to ensure that your system is backed up to prevent any misconfiguration. If you're uncomfortable making these changes or unsure about the consequences, consider asking for help from someone more familiar with macOS systems and library management.

**Comment by jim6301** [comment]
Hi Titus:

Sorry, what you (and Chat GPT) suggested is all beyond my capabilities. However I was able to solve the problem by installing the "Webdriver Manager for Python" (4.0.1) package and then changing the Python code to the following:

from selenium import webdriver

from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

driver.get("https://www.amazon.com/")
For some reason this works.

Thanks for your help. Take care,
Jim
