### ISSUE TITLE
FF IDE Flashes "welcome to Mozilla" page before loading test URL on FF 42

### ISSUE THREAD

**Issue by pbasin** [SeleniumHQ/selenium#1336]
When launching script runs on FF IDE with FF 42, before the test URL loads page, I see a quick flash of  "welcome to mozzilla" page you get when you download a new version of FF the first time.  Each new URL flashes the Mozilla welcome page before each load.  I went back to previous version of FF and no problem.

**Comment by davehunt** [comment]
This was fixed in https://github.com/SeleniumHQ/selenium/commit/cc0647aa5092aa46df6118999a24a5dc4623b966 and will be included in the next release.
