### ISSUE TITLE
[🐛 Bug]: Documentation test example - Severity 4

### ISSUE THREAD

**Issue by thecircleoflifefree** [SeleniumHQ/selenium#13369]
### What happened?

On the following link: 
[example](https://www.selenium.dev/selenium/docs/api/javascript/index.html)

This code will not run:

`const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();`

Line 7 will return: 
`SyntaxError: Unexpected token '.'`

**FIX**

Remove _';'_ to use the sendKeys method accordingly.

### How can we reproduce the issue?

```shell
Copy/Paste the code as given on the website and test.
```

### Relevant log output

```shell
testfile.js:7
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
                                           ^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
```

### Operating System

NA

### Selenium version

node

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

NA

**Comment by titusfortner** [comment]
Those api documents are out of date and we can't fix them #10185
@diemol can we just remove what is there now to avoid confusion? 

@thecircleoflifefree just remove the semicolon before the period,or doesn't belong there. 

Check out the examples in our website https://www.selenium.dev/documentation/webdriver/getting_started/?tab=javascript

**Comment by diemol** [comment]
Sure, we should remove them.

**Comment by titusfortner** [comment]
Lol, and I did extra work on the build automaton to not overwrite them.

**Comment by diemol** [comment]
I mean, I have the JS docs in my TODO list, I can then work on it so you do not need to modify your scripts.

**Comment by titusfortner** [comment]
Current scripts work either way, just have more lines of code. 😄
