### ISSUE TITLE
[🚀 Feature]: Arc Browser support

### ISSUE THREAD

**Issue by scout0773** [SeleniumHQ/selenium#13374]
### Feature and motivation

Now, please correct me if I'm wrong, but I use Arc browser on my MacOS device and it doesn't have support for it's own method inside of Selenium. All I'm calling for is support so you can use `driver = webdriver.Arc()`.

### Usage example

Would be the exact same with other browsers where you launch the browser's webdriver.

**Comment by diemol** [comment]
If I understand correctly, Arc is based on Chromium, so you should be able to use ChromeDriver to automate it. You need to pass the binary location in the ChromeOptions object. If that does not work, you need to reach out to the Arc browser project and let them know an adequate browser driver is needed to automate the browser.

**Comment by diemol** [comment]
Please use the links below to ask more questions.
