### ISSUE TITLE
Add W3C Error Descriptions

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13378]
Right now our Errors Documentation only refers to 3 errors, but there are a couple dozen listed in the w3c spec — https://w3c.github.io/webdriver/#errors

It would be good to describe each of these, and include when someone may get them and what the solution may be.
https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/

I think we want a separate page for each of these errors to make it easier to link to them.

**Comment by nvborisenko** [comment]
Or use anchors like https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
