### ISSUE TITLE
Could the NuGet packages ship strong-named binaries?

### ISSUE THREAD

**Issue by amihalcin** [SeleniumHQ/selenium#1337]
The major Selenium packages on nuget.org (https://www.nuget.org/packages/Selenium.WebDriver/) contain only the unsigned binaries, while seleniumhq.org has both unsigned and strong-named binaries.  Is there a way to provide the strong-named binaries in NuGet?  A separate NuGet package for strong-named binaries would be fine to keep the download size small for users of the existing package.

**Comment by jimevans** [comment]
We will not be providing these binaries via NuGet at this time. We may revisit this decision at a later time.
