### ISSUE TITLE
ETIMEDOUT error on Grid 4 while executing testcases [🐛 Bug]: 

### ISSUE THREAD

**Issue by aniketkumar2012** [SeleniumHQ/selenium#13371]
### What happened?

Currently, we are using Selenium Grid 3.141.59v(deployed on AWS Ecs Fargate) for our daily test cases execution build. We have around 2000 test cases which are taking 1 hour to get executed. 

Now, are planning to switch to Grid 4 latest version. We have deployed on AWS Farageta and it is working fine for couple of test cases, but the main issue occour when we use parallel execution with the 95 instances configure in our NightwatchJs FW.

Getting below error ETIMEDOUT
session===="1a63cdfc544134e1ffacb165f0fc1e48"
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/window/maximize - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  ℹ Loaded url https://mywebsite/login/default in 2205ms
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/0CC5951EE10D85C884533431A4FDD6BF_element_12/value - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/0CC5951EE10D85C884533431A4FDD6BF_element_15/clear - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/0CC5951EE10D85C884533431A4FDD6BF_element_15/value - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  ⠇ Loading url: https://mywebsite.com/rfa/jsp/main/Main.jsp 
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/url - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
  ℹ Loaded url https://mywebsite.com/rfa/jsp/main/Main.jsp  in 24047ms
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/execute/sync - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/execute/sync - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/execute/sync - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/B0D463D020776D17F33BFCD786F0CB51_element_61/click - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/B0D463D020776D17F33BFCD786F0CB51_element_61/click - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      GET http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/B0D463D020776D17F33BFCD786F0CB51_element_62/css/max-height - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      GET http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element/B0D463D020776D17F33BFCD786F0CB51_element_63/css/max-height - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element - ETIMEDOUT
Error: connect ETIMEDOUT 10.238.196.249:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
  Error
      POST http://mygridserver4:4444 /session/1a63cdfc544134e1ffacb165f0fc1e48/element - ETIMEDOUT

### How can we reproduce the issue?

```shell
Execute the test cases in parallel it should be more than 30 instances. 
After 20 to 30 minutes we start seeing the error.
```

### Relevant log output

```shell
Selenium node logs, will provide later. once confirm with my team
```

### Operating System

Linux

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

4.16.1

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.71

### Are you using Selenium Grid?

yes

**Comment by titusfortner** [comment]
We can't do anything here without logs or a way to reproduce it.

**Comment by diemol** [comment]
We will reopen this when we get more information.
