### ISSUE TITLE
[🐛 Bug]: When using screenshot_as_base64 to obtain the screenshot of an element, the page will shrink to the upper left corner

### ISSUE THREAD

**Issue by meteorlin** [SeleniumHQ/selenium#13382]
### What happened?

I hope to use the `screenshot_as_base64` method to obtain the rendering result of the target element (for some reasons, I cannot use the "headless" setting). However, once the program calls the `screenshot_as_base64` method, the page will immediately zoom to the upper left corner (as shown in the gif below), making it very unfriendly to humans. What methods are there to take screenshots of specific elements while avoiding such scaling issues?
Thank you in advance!

![screenshot](https://github.com/SeleniumHQ/selenium/assets/49402403/aeb58bee-2d95-44bf-a28d-6da44e88a62f)

Here is the code of `index.html`:
```html
<body>
    <textarea id="text_area_1" cols="30" rows="10"></textarea>
    <div>0.00</div>
</body>
```

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep

driver = webdriver.Chrome()
driver.get('http://localhost:8000/')
while True:
    # Note that "text_area_1" is the id of the target element in the index.html
    element = driver.find_element(By.ID, "text_area_1").screenshot_as_base64
    sleep(0.05)
```

### Relevant log output

```shell
None
```

### Operating System

Windows 10

### Selenium version

Python 4.16.0

### What are the browser(s) and version(s) where you see this issue?

any browser

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 120.0.6099.71

**Comment by titusfortner** [comment]
The effect should be temporary and you end up with the proper screenshot of just the element. 

Either way, this isn't managed by Selenium code, but an implementation detail of the driver, so you can raise an issue with Google if you think this is something that needs to be addressed.

**Comment by meteorlin** [comment]
Thank you for your quick answer. I have replaced Chrome with FireFox or webkit and this issue will no longer occur.
