### ISSUE TITLE
[🐛 Bug]: Selenium Manager info for downloading Grid confusing/incorrect

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13383]
### What happened?

Looks like we're making some assumptions as to what info is where. This shouldn't refer to "driver" anywhere

Also, when using `--output json` we get this, when I think Result should use `grid_path` where applicable.
```
  "result": {
    "code": 0,
    "message": "/Users/titusfortner/.cache/selenium/grid/4.16.1/selenium-server-4.16.1.jar",
    "driver_path": "/Users/titusfortner/.cache/selenium/grid/4.16.1/selenium-server-4.16.1.jar",
    "browser_path": ""
  }
```

### How can we reproduce the issue?

```shell
selenium-manager --grid --debug
```

### Relevant log output

```shell
DEBUG   grid not found in the system
DEBUG   Required driver: selenium-server 4.16.1
DEBUG   Downloading selenium-server 4.16.1 from https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
INFO    Driver path: /Users/titusfortner/.cache/selenium/grid/4.16.1/selenium-server-4.16.1.jar
```

### Operating System

n/a

### Selenium version

trunk

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
During the May 2024 Selenium Summit, we decided not to implement this.
