### ISSUE TITLE
[🚀 Feature]: Python Service class Properties

### ISSUE THREAD

**Issue by gauravgandhi1315** [SeleniumHQ/selenium#13391]
### Feature and motivation

Python Driver Services can only have parameters set in the constructor

### Usage example

service = webdriver.ChromeService()
service.service_args = ['--log', 'debug']

**Comment by iampopovich** [comment]
@titusfortner it seems like a duplicate of https://github.com/SeleniumHQ/selenium/issues/12760

**Comment by titusfortner** [comment]
huh, and it uses the same wording and examples... weird. Thanks for pointing it out.
