### ISSUE TITLE
[🐛 Bug]: Can not support perform gestures on SVGgraphices line element, whose width or height is 0. 

### ISSUE THREAD

**Issue by Erix377** [SeleniumHQ/selenium#13394]
### What happened?

When I try to perform a hover action on an horizontal svg line element, it returns the following errors:
- “Error: element is not a valid mouse target element.”
- “Element has less than 1 px height, and is therefore not a valid mouse target.”

And I use "getSize()" method on svg line element, which returns “(10, 0)”, which matches the context the error message indicates. However, the line element has a length of 10px (width) and stroke-width of 3px (height) in viewport sight.

![image](https://github.com/SeleniumHQ/selenium/assets/111478885/f8ad276f-b0d0-41eb-8986-40c4f70f3c5c)

And I believe it should be an product issue, since I investigated more on why height is ‘0’. This is seems to be happening because my target is a line element in SVG.
 
For line elements height is calculated based on the ‘y’ co-ordinate of both the end points. But since the line in my case is horizontal (same ‘y’), the height is coming as ‘0’. Even dom APIs like ‘getBBox()’ are giving ‘0’ height.
 
This is kind of an exception that in case of line, height ‘0’ not necessarily means that the element is not a valid hover/click target. Maybe something to be handled in the ‘mouseOver’ API.
 
Is there an alternate method you can suggest for hovering the mouse pointer over the horizontal line element in my test case? 

### How can we reproduce the issue?

```shell
1. create a svg horizontal line element.
2. get that element and perform hover or click action on that element.
3. it will throw the error: as described above.
```

### Relevant log output

```shell
Error message:

“Error: element is not a valid mouse target element.”
“Element has less than 1 px height, and is therefore not a valid mouse target.”
```

### Operating System

Mac, Windows, Linux 

### Selenium version

Java 4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  119.0.6045.159 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver-v0.33.0-macos-aarch64, chromedriver

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
That error originates from Chrome. Does it work in Firefox?
It will either need to be fixed in the driver or the spec, so figuring out if it is chrome-specific will help us determine that.

**Comment by titusfortner** [comment]
I'll add the links below for both of them in case you want to follow up.
