### ISSUE TITLE
[🐛 Bug]: When attempting to select an option from a menu, the item displays as selected but js doesn't fire an event

### ISSUE THREAD

**Issue by ocmyhome** [SeleniumHQ/selenium#13395]
### What happened?

I'm running into an issue where I try to select an option from a menu, the option appear selected, but nothing is triggered w/ in the web app.  The menu is part of a filter, and when selected should filter a list.  The list isn't filtered.  I've tried everything I can think of (Using the SelectElement class, Manually clicking the item, executing javascript) but nothing works.

My thought is that it perhaps has something to do with the Blazor web app that it's not fully supported.

Any work arounds to this would be appreciated as well.

This is the select element I'm working with:

<img width="807" alt="000253" src="https://github.com/SeleniumHQ/selenium/assets/24324485/b9906b51-060f-40aa-aedb-e049cc1b0d2b">

### How can we reproduce the issue?

```shell
I can't share the web app code, but below is what I use to attempt to select the option.

public static void SelectElementOptionByValue(IWebElement elem, string val)
      {
            var select = new SelectElement(elem);
            select.SelectByValue(val);
        }
```

### Relevant log output

```shell
No output log available
```

### Operating System

Windows 10

### Selenium version

C# 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.10900

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
`SelectElement` is just a convenience class that wraps the underlying element calls. You can try working with it the same way that you do other elements, with the exception that you don't actually have to open the dropdown to interact with the option element.

I'll include some links below for where you can get more assistance.

**Comment by ocmyhome** [comment]
Thanks for the reply.  I tried this approach before and the list wasn't updated (nothing triggered).  I'll bring this question to one of the links provided.  thanks
