### ISSUE TITLE
Making Selenium Undetectable

### ISSUE THREAD

**Issue by Chetan11-dev** [SeleniumHQ/selenium#13401]
### Feature and motivation

I am the creator of the [Botasaurus](https://github.com/omkarcloud/botasaurus) Web Scraping Framework, a popular Selenium-based tool used for building web scrapers. My current focus is on enhancing its stealth capabilities to avoid detection by bot detectors.

The challenge with Selenium is that its launch process introduces various options and 'automation noise', which bot detectors easily identify. I'm exploring ways to initiate Selenium using a bare Chrome setup, free from any automation flags, to remain undetectable.

One strategy I'm considering is similar to the approach used in [Real Chrome launch as demonstrated in Puppeteer](https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/index.js). The idea is to start a real instance of Chrome and then attach Selenium to it using the `browserWSEndpoint`. I'm seeking advice or pointers on how to successfully achieve this.

Any guidance or tips would be greatly appreciated. Thanks in advance for your help!

### Usage example

Not Applicable

**Comment by NCLnclNCL** [comment]
selenium use http GET POST to chromedriver, dont use websocket

**Comment by titusfortner** [comment]
The Selenium project's vision of being a responsible participant in the Open Web includes being transparent about what it is — a browser automation tool. Helping people to circumvent ToS of various sites is not what we are about.
