### ISSUE TITLE
[🐛 Bug]: Selenium is not handling the geo location permission in headless mode

### ISSUE THREAD

**Issue by siddiquiakram84** [SeleniumHQ/selenium#13409]
### What happened?

In the headless mode when I am running python selenium script it is not able to handle the location permission alert as allow.
whereas script is handling in the non-headless mode.
I am using this script '''
![image](https://github.com/SeleniumHQ/selenium/assets/85447181/0e821bf2-e52b-46ac-8eb2-d9bccbdc4fbe)
<img width="940" alt="homescreen" src="https://github.com/SeleniumHQ/selenium/assets/85447181/672826a5-1c95-43ae-8848-754487f57ffb">

'''

### How can we reproduce the issue?

```shell
launch this URL  https://automation-testing1.hyperzodshop.dev/?via=admin
there would be a locateme button where you have to perform click to redirect to the home page.

since location permission is not handled as allow, I am not able to go on the discovery page.
```

### Relevant log output

```shell
Timeoutexception
```

### Operating System

Ubuntu

### Selenium version

selenium           4.15.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver Version: 120.0.6099.109

### Are you using Selenium Grid?

Selenium WebDriver API

**Comment by diemol** [comment]
Selenium just forwards commands and parameters to ChromeDriver. You need to report this to them.
