### ISSUE TITLE
[🐛 Bug]: Selenium Should Error if cannot match browserVersion

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13418]
### What happened?

Similar to #13352 — if a user passes in an explicit browserVersion and it cannot be matched for some reason, Selenium should fail instead of using a browser it can find.

### How can we reproduce the issue?

```shell
selenium-manager", "--browser", "chrome", "--browser-version", "bad", "--language-binding", "ruby", "--output", "mixed", "--debug"]
```

### Relevant log output

```shell
DEBUG	chromedriver not found in PATH
DEBUG	chrome detected at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
DEBUG	Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
DEBUG	Output: "Google Chrome 120.0.6099.199 "
DEBUG	Detected browser: chrome 120.0.6099.199
DEBUG	Discovered chrome version (120) different to specified browser version (bad)
WARN	There was an error managing chromedriver (chrome bad not available for download (minimum version: 113)); using driver found in the cache
INFO	Driver path: /Users/titusfortner/.cache/selenium/chromedriver/mac-x64/120.0.6099.109/chromedriver
INFO	Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
```

### Operating System

Mac

### Selenium version

sm_mixed_output branch

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by diemol** [comment]
How would it work in this case when SM is logging errors to `stderr` and they are not being returned to the main process launched from the bindings? How can we show a good error to the user?

**Comment by titusfortner** [comment]
SM is logging to stderr. If there is an error (status code > 0), the error message is in stdout, and Selenium throws with this info the way it normally does.
~This is how SM in the mixed branch works currently~
I lied, I was looking at the wrong thing

**Comment by diemol** [comment]
The decision to implement this was made during the Selenium Dev Summit in May 2024.

**Comment by Delta456** [comment]
I can work on this issue.

**Comment by Delta456** [comment]
Please close this issue as #14511 has been merged.
