### ISSUE TITLE
[🚀 Feature]: [dotnet] Improve performance of internal logging

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#13411]
### Feature and motivation

Before:

```csharp
logger.Trace("abc");
```

The problem is `abc` is always allocated in memory despice that logging is turned off.

What we can do:
```csharp
if (logger.IsEnabled(LogEventLabel.Trace))
{
  logger.Trace("abc");
}
```

Interesting what else we can do to improve logging..

CC: @YevgeniyShunevych 

### Usage example

Purely internal stuff.

**Comment by YevgeniyShunevych** [comment]
@nvborisenko, I think that adding and using `IsEnabled` method should be enough.

**Comment by nvborisenko** [comment]
we also can play with https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimplattribute?view=net-8.0, not yet investigated where it can be applied in our case.
