### ISSUE TITLE
[🐛 Bug]: setPermission() is not available on the driver intance

### ISSUE THREAD

**Issue by zerosdev** [SeleniumHQ/selenium#13428]
### What happened?

I want to enable clipboard permission. I've searched Stackoverflow and found a thread mentioning about `setPermission()` method but i can't get it to work
The `setPermission()` doesn't exists on the driver instance

<img width="781" alt="Screenshot at Jan 11 21-17-38" src="https://github.com/SeleniumHQ/selenium/assets/33526722/204ef7e5-344c-4a8f-b416-66f2e0d3cf25">

### How can we reproduce the issue?

```shell
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('chrome').build();
  try {
    await driver.get('http://www.google.com');
    await driver.setPermission('clipboard-read', 'granted');
    await driver.setPermission('clipboard-write', 'granted');
  } finally {
    await driver.quit();
  }
})();
```
```


### Relevant log output

```shell
No output
```

### Operating System

MacOS X

### Selenium version

Javascript 4.7.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 120

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
I just executed:

```js
    it('Using setPermission test', async function () {
      const Options = new Chrome.Options();
      let driver = await env
        .builder()
        .setChromeOptions(Options)
        .build();

      await driver.get('http://www.google.com');
      await driver.setPermission('clipboard-read', 'granted');
      await driver.setPermission('clipboard-write', 'granted');
      await driver.quit();
    });
```

and it worked.

`setPermission` is available, I am not sure why it does not show on your autocomplete.
