### ISSUE TITLE
[🐛 Bug]: Error communicating with the remote browser. It may have died. in sel 4.x version where as the same code is workign selenium 3.X versions

### ISSUE THREAD

**Issue by Afrina-Alam** [SeleniumHQ/selenium#13426]
### What happened?

We have automation code where we have runtime Java Class placed where it picks the driver and run the actions ..
All the code has been working in sel 3.x version but in 4.x version ... the base automation code is working fine as soon as the control goes to runtime java class it gives the error - Error communicating with the remote browser. It may have died. when tries to perform any action on the driver .The we tried printing the driver class so driver class is being passed . 
And note the same code works perfeclty fine when the build of the project used selenium 3.x jars 
The environment used is docker for the grid as well as the automation code 

### How can we reproduce the issue?

```shell
There is no particular code .. but still sharing the runtime class method that causes issues -
public String testMethod(WebDriver driver, String[] argumentArray) {
try {
logger = createLogFile();
logger.info(driver.getTitle()); --- Error is thrown as soon as we invoke methods on driver.
return driver.getTitle();
}
```

### Relevant log output

```shell
Caused by: java.lang.RuntimeException: Custom code failed : Error communicating with the remote browser. It may have died.
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'XXXXXX', ip: 'X.X.X.X', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-372.32.1.el8_6.x86_64', java.version: '1.8.0_351'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [8e3f598ad0db77d854692e511eb9e51d7fc94f52, getTitle {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 120.0.6099.63, chrome: {chromedriverVersion: 120.0.6099.62 (93ab19d804d4..., userDataDir: C:\Windows\proxy\scoped_dir...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:3006}, networkConnectionEnabled: false, pageLoadStrategy: eager, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 8e3f598ad0db77d854692e511eb...}
Session ID: 8e3f598ad0db77d854692e511eb9e51d7fc94f52
```

### Operating System

Linux

### Selenium version

Java 4.x

### What are the browser(s) and version(s) where you see this issue?

All Browsers

### What are the browser driver(s) and version(s) where you see this issue?

Browser drivers are compatible as we are abel to run the action withint the automation code classed and not the runtime class

### Are you using Selenium Grid?

Yes

**Comment by diemol** [comment]
I am closing this because we did not get more information. We can reopen if more information is provided.

**Comment by Afrina-Alam** [comment]
Just wanted to update that we were able to figure out the root cause and fix the issue -
Since Selenium uses OpenTelemetry to instrument tracing and event logs, This was blocked in the new docker server and hence disable telemetry to false we were able to continue .
Thanks for Selenium documentation that we were able to find the clue .
