### ISSUE TITLE
[🐛 Bug]: Unable to obtain chrome using Selenium Manager when using DeploymentItem tag at class level

### ISSUE THREAD

**Issue by pravinshinde222** [SeleniumHQ/selenium#13423]
### What happened?

In current dot net project i was using selenium version 4.8.1, in which I was using WebDriverManager to download compatible ChromeDriver.exe into project path 'bin\Debug\Chrome\120.0.6099.109\X64'  but after doing below steps I am getting error as "Unable to locate or obtain Selenium Manager binary at C:\Practice\TestResults\Deploy_PrShinde 2024-01-09 20_16_03\Out\selenium-manager\windows\selenium-manager.exe"

Steps i perform: 
1) Removed webdrivermanager nuget
2) Upgraded selenium webdriver and selenium support to 4.16.2 version

When TestClass has Deployment Tag then it is finding selenium-manager.exe in Deployment path instead of bin/debug path so 
but it is unable to get selenium-manager.exe from deployment path.

Is there a way to look selenium-manager.exe into bin/debug path when using DeploymentItem tag 
Because we are using this tag to deploy some files which are required for project purpose.

### How can we reproduce the issue?

```shell
Steps to reproduce the issue 
1) Create a class library project in .net framework
2) Install below nuget package
   i) Seleniu.Support 4.16.2
   ii) Selenium.Webdriver 4.16.2
3) Copy paste below code

using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Chrome;
using System;
using System.IO;
using System.Reflection;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager.Helpers;
namespace Selenium_2
{
    [TestClass]
    [DeploymentItem("Files\\")]
    public class Class2_WithDeployment
    {
       
        [TestMethod]
        public void TestSelenium()
        {
            try
            {
                var driver = new ChromeDriver();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception occured , Inner exception :  {ex.InnerException.InnerException.Message}");
            }
        }
    }
}
```

### Relevant log output

```shell
stacktrace: 
Unable to obtain chrome using Selenium Manager; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

Unable to locate or obtain Selenium Manager binary at C:\Practice\TestResults\Deploy_PrShinde 2024-01-09 20_16_03\Out\selenium-manager\windows\selenium-manager.exe
```

### Operating System

Windows 10 enterprises

### Selenium version

4.16.2

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.109

### Are you using Selenium Grid?

No

**Comment by pravinshinde222** [comment]
Please find attach file having working selenium code with  4.8.1 selenium version & webdrivermanager for reference.
[Selenium code with 4.8.1.txt](https://github.com/SeleniumHQ/selenium/files/13888912/Selenium.code.with.4.8.1.txt)

**Comment by nvborisenko** [comment]
@pravinshinde222 I cannot reproduce this issue (.net 8 target framework) based on code you provided. Can you please create very simple project to reproduce it, including steps how you execute tests. Thank you.

**Comment by pravinshinde222** [comment]
@nvborisenko Thank you for your response. 
I have attached sample project for reproducing the issue. Please let me know if you need more information. 

**Steps to reproduce the issue**
1) Create class library project targetting .net 8 in VS2022.
2) Install selenium-support 4.16.2  (it will also installed selenium-webdriver 4.16.2)
3) Copy paste above code 
4) Run the test.

[
[SeleniumDeploymentIssueDemo.zip](https://github.com/SeleniumHQ/selenium/files/13897911/SeleniumDeploymentIssueDemo.zip)
](url)

**Comment by nvborisenko** [comment]
Seems `Selenium Manager` binaries are missed in the location where tests are executed from. Usually it is project output folder (bin/Debug), but not in this case.

@pravinshinde222 you can help tests runner copy missing files:
```csharp
[DeploymentItem("selenium-manager", "selenium-manager")]
```

> [!NOTE]
> For selenium team:
> **AppContext.BaseDirectory** C:\Users\nikol\Downloads\SeleniumDeploymentIssueDemo\SeleniumDeploymentIssueDemo\TestResults\Deploy_nikol 2024-01-11 12_33_25\Out
> **Environment.CurrentDirectory** C:\Users\nikol\Downloads\SeleniumDeploymentIssueDemo\SeleniumDeploymentIssueDemo\TestResults\Deploy_nikol 2024-01-11 12_33_25\Out
> **Assembly.GetExecutingAssembly().Location** C:\Users\nikol\Downloads\SeleniumDeploymentIssueDemo\SeleniumDeploymentIssueDemo\TestResults\Deploy_nikol 2024-01-11 12_33_25\Out\SeleniumDeploymentIssueDemo.dll

**Comment by pravinshinde222** [comment]
@nvborisenko : Thanks for your suggesstion. We did below steps.
  i) Added selenium-manager.exe in current project [SeleniumFiles-> selenium-manager-> windows-> selenium-manager.exe
  ii) Added deployment Tag as [DeploymentItem("SeleniumFiles\\"]

This way selenium-manager.exe got copied to Deployment Item and i was able to overcome this issue, But in our test solution we have 10+ selenium test project, So keeping selenium-manager.exe in each project will add maintenance work if we again upgrade selenium version from 4.16.2 to higher version. 

Earlier with 4.8.1 version, WebDriverManager nuget used to download ChromeDriver.exe into Deployment folder path. Can't we have same behaviour with 4.16.2 as well if deployment tag is added ?

**Comment by nvborisenko** [comment]
I didn't propose to add a reference to the executable file, I just proposed add one more attribute to the class:
```csharp
[DeploymentItem("selenium-manager", "selenium-manager")]
``` 

Full fixed code based on your example:
```csharp
[TestClass]
[DeploymentItem("selenium-manager", "selenium-manager")]
[DeploymentItem("Files\\")]
public class Class1
{
    [TestMethod]
    public void Test1()
    {
        var driver = new ChromeDriver();

        driver.Quit();
    }
}
```

Nothing more. It will work even if you will upgrade selenium package to the newest version in future.

In my opinion this solution doesn't look great, you still need to add this line of code in each class which is tagged as deployable. You can ask https://github.com/microsoft/testfx team relying on similar issue https://github.com/microsoft/testfx/issues/1582.

**Comment by titusfortner** [comment]
@nvborisenko is there something Selenium can do for this, or does it depend on the user code?

**Comment by nvborisenko** [comment]
Particularly in this case user utilized some sort of legacy feature of MsTest framework. If I understand correctly `DeploymentItem` attribute was designed to be able to execute tests remotely, and instead of copying all files to the remote end, user can specify what files are necessary for specific test. I am not sure Microsoft is still supporting remote execution. (I may totally wrong)

> Visual Studio no longer supports [Microsoft Test Manager and Lab Management](https://learn.microsoft.com/en-us/previous-versions/azure/devops/test/mtm/reference-tcm?view=tfs-2017&viewFallbackFrom=azure-devops&preserve-view=true) for automated testing.

I don't think selenium should resolve it. Tons of nuget packages has additional packed files that should be treated by test runners somehow.

Good news that we have plan B :) Let's see how many users will come with the same problem before revealing this.

**Comment by pravinshinde222** [comment]
Thanks for your quick response, With above solution, though i have to add 1 deploymentItem line in each class, but it will resolve my issue. Thank you once again .
