### ISSUE TITLE
[🐛 Bug]: Selenium or Webdriver is setting cookies weirdly

### ISSUE THREAD

**Issue by emilhem** [SeleniumHQ/selenium#13427]
### What happened?

I tried creating a basic Python test for loading one page using Selenium in both ChromeDriver and GeckoDriver. The issue is that when using the drivers they set cookies really weirdly making the website refuse subsequent page loads due to these weird cookies (yes, the web page should have handled the cookies better, but still).

I expected the page to load similar or the same way as a regular user access it, setting the same cookies.

The interesting part is that it happens in both drivers on Linux and Windows.

### How can we reproduce the issue?

```shell
https://github.com/emilhem/selenium-cookie-issue
```

### Relevant log output

```shell
no real logs
```

### Operating System

NixOS 23.11 and Windows 11

### Selenium version

Python 4.15.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.217, Chromium 120.0.6099.199, Firefox 121.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.109, geckodriver 0.33.0

**Comment by titusfortner** [comment]
I don't know what you mean by weird cookies, and your reproduction example doesn't do anything weird. The site just asks to allow cookies, if you click accept everything works as expected.

Note that Selenium only works with cookies on the domain the browser has navigated to, so it does not make sense to delete cookies after starting a browser and before navigation.

I'll attach links below for follow up questions.
