### ISSUE TITLE
[🚀 Feature]: Add timestamps / labels to Selenium Manager logs

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13421]
### Feature and motivation

Now that we are looking to stream the logs, it would be useful to get time stamps as well.
Would also be nice to label what it is since it'll be mixed in with other logs.

### Usage example

For reference:
default Java pattern:
Jan 09, 2024 4:48:38 PM SeleniumManager DEBUG	chromedriver not found in PATH

default Ruby pattern:
2024-01-09 16:47:59 DEBUG SeleniumManager chromedriver not found in PATH

**Comment by bonigarcia** [comment]
Closed via #13554.
