### ISSUE TITLE
[🐛 Bug]: AL2023 Unable to Locate Driver (Chrome,Firefox)

### ISSUE THREAD

**Issue by Xdomen** [SeleniumHQ/selenium#13434]
### What happened?

I'm attempting to upgrade from Selenium 4.7.2 (Python 3.11) to 4.16.0 latest on Amazon Linux 2023 inside Docker container, while doing so, we receive the following exception for driver path even though both geckodriver and chromedriver are in $PATH and both binaries are located in /usr/local/bin with appropriate permissions.

```
echo $PATH
/usr/local/bin/chromedriver:/usr/local/bin/geckodriver
``` 
I receive an exception as seen in the log output when attempting to initialise the browser
```
>>> from selenium import webdriver
>>> webdriver.Firefox()
```

The following code does seem to work, although it would be great if we wouldn't need to specify the path to binary executable:
```
from selenium import webdriver
firefox_executable_path = '/usr/local/bin/geckodriver'
firefox_service = webdriver.firefox.service.Service()
firefox_options = webdriver.FirefoxOptions()
driver = webdriver.Firefox(service=firefox_service, options=firefox_options)
``` 

### How can we reproduce the issue?

```shell
- Build docker container with Amazon Linux 2023
- Download and unarchive driver binaries and browsers
    && tar -xvf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz -C /usr/local/bin/ \
    && unzip chromedriver-linux64.zip -d /usr/local/bin
- Install python3 dependencies
- Open python3 shell

>>> from selenium import webdriver
>>> webdriver.Firefox()
```

### Relevant log output

```shell
>>> from selenium import webdriver
>>> webdriver.Firefox()
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 86, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
                ^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 70, in get_binary
    raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
selenium.common.exceptions.WebDriverException: Message: Unable to obtain working Selenium Manager binary; /opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Amazon Linux 2023

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 121.0.1, Chrome 120.0.6099.109 

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.34.0, ChromeDriver 120.0.6099.109

### Are you using Selenium Grid?

None

**Comment by titusfortner** [comment]
Selenium now uses a separate binary to locate things on PATH instead of doing it in Python. For some reason it isn't finding the selenium-manager binary on your system. As indicated in the error message, it should exist here: `selenium/webdriver/common/linux/selenium-manager`
Are you loading Selenium with a package manager or doing something other than a pypi install?

**Comment by Xdomen** [comment]
@titusfortner thanks for prompt reply. You're absolutely right, were using a custom package manager that pre builds the dependency, which doesn't seem to contain the necessary files. Thanks!
