### ISSUE TITLE
[🐛 Bug]: Unable to obtain browser driver error while running on jenkins

### ISSUE THREAD

**Issue by zshig235** [SeleniumHQ/selenium#13438]
### What happened?

I'm trying to run a docker image in a pipeline script in jenkins of nodejs19 but once i get to the end stage of running my test script, i get this error 
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/.
        
**Error: Error executing command for /home/user123/node/community-one/workspace/com.abc.testing/ANDI_2/node_modules/selenium-webdriver/bin/linux/selenium-manager**

Some background: My automation application is built on nodejs19 and it has a dependency on selenium webdriver (chromedriver). This is my first time using jenkins so im not to sure about all the details. 

What i noticed is that the error is pointing to a linux folder, but my machine is windows and on my machine, selenium manager application is located in the windows folder. What i have learned is the agent that is running the job in jenkins is linux based. 

I have some questions, 
Would this issue be because its an agent that is linux based? 
Do i need a different setup that contains selenium and nodejs as images? 
Or should this just work on a nodejs19 image and i just need a windows agent? 

And if theres a workaround available please lmk. 

### How can we reproduce the issue?

```shell
Here is how im opening the browser which works fine on my local
const webdriver = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
driver = new webdriver.Builder()
    .forBrowser(webdriver.Browser.CHROME)
    .setChromeOptions()
    .build();

Not sure if you can reproduce it
```

### Relevant log output

```shell
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/.
        
**Error: Error executing command for /home/user123/node/community-one/workspace/com.abc.testing/ANDI_2/node_modules/selenium-webdriver/bin/linux/selenium-manager**
```

### Operating System

windows 10

### Selenium version

4.16

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 120

**Comment by diemol** [comment]
This is most of the time related to the environment where the test is running. You can use one of the links below to ask questions, or join our chat where we can help you understand your issue.

**Comment by titusfortner** [comment]
Also turning on logging might give you more information on the cause: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
