### ISSUE TITLE
[🐛 Bug]: [rb] Either declare or remove dependency on `base64`

### ISSUE THREAD

**Issue by Earlopain** [SeleniumHQ/selenium#13447]
### What happened?

Ruby 3.3 shows a warning if the base64 gem is required without it being declared in the gemspec, Ruby 3.4 will throw an error.
 See https://github.com/ruby/ruby/blob/master/doc/NEWS/NEWS-3.3.0.md#stdlib-updates

Many gems have opted to inline the base64 implementation, however this gem makes use of the urlsafe variants which are a bit more complex and not just a wrapper over `pack`/`unpack`. You would need to inline the entirety of https://github.com/ruby/base64/blob/9669a7d3b0e3b9a739969404daf58f912c58c6b3/lib/base64.rb, similar to https://github.com/newrelic/newrelic-ruby-agent/pull/2378

### How can we reproduce the issue?

```shell
Use `selenium-webdriver` on Ruby 3.3
```

### Relevant log output

```shell
base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
```

### Operating System

Irrelevant

### Selenium version

Ruby master

### What are the browser(s) and version(s) where you see this issue?

Irrelevant

### What are the browser driver(s) and version(s) where you see this issue?

Irrelevant

**Comment by titusfortner** [comment]
@Earlopain would you like to PR the change?

**Comment by Earlopain** [comment]
Sure, I can do that. In which direction would you like this to go though? Add `base64` to the gemspec or inline it instead?

I've already played with inlining it in a fork of mine here https://github.com/SeleniumHQ/selenium/compare/trunk...Earlopain:selenium:rb-base64-dep and that seems to work fine. But I'm not sure about the license thing I did there.

**Comment by titusfortner** [comment]
I don't have strong opinions either way, so whatever you think is best.

Sounds like...

Gemspec
* it's maintained by ruby org, so unlikely to stop being maintained
* we need all of the code

Inline
* minimize dependencies
* unlikely to change

My general inclination is that I'd rather manage a dependency than maintain code unrelated to my repo, but other people balance that calculus differently, and this is not a hill I would die on. 😁

**Comment by Earlopain** [comment]
As a consumer, I would prefer a minimal dependency tree. However I'm also not the one having to maintain it in the end.

I have already removed base64 from a bunch of gems already so my opinion on this is heavily biased. Most times, there were only one or two usages of the trivial wrapper methods.

I will defer to your decision on this. I don't think my opinion as a random passerby holds much weight.
