### ISSUE TITLE
[🚀 Feature]: Java test guarding by version

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13459]
### Feature and motivation

We want to run beta versions of browsers to catch problems earlier, but if something has been fixed or breaks on a later version, then we can't mark both versions as passing.

### Usage example

```
  @Ignore(value = FIREFOX_BETA, reason="New regression")
```

**Comment by naseemx** [comment]
can you assign me

**Comment by titusfortner** [comment]
We generally don't assign issues explicitly, but I'm looking forward to seeing what you come up with and if you want to discuss anything come find us on [Selenium Chat](https://www.selenium.dev/support/#ChatRoom)
