### ISSUE TITLE
[🐛 Bug]:   File "/usr/python/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 137, in run     stdout = completed_proc.stdout.decode('utf-8').rstrip("\n") AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by liupan0371** [SeleniumHQ/selenium#13455]
### What happened?

I integrated Selenium into the FastAPI framework,An error occurred during program execution.But it's normal to only run the functions below,
![image](https://github.com/SeleniumHQ/selenium/assets/141121376/d344a98d-3347-41d4-af84-c06769c65396)

### How can we reproduce the issue?

```shell
def get_content_by_url(url: str):
    chrome_options = Options()
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('blink-settings=imagesEnabled=false')
    chrome_options.add_argument('--ignore-certificate-errors')
    chrome_options.add_argument('--no-sandbox')
    driver = webdriver.Chrome(options=chrome_options)
    driver.set_page_load_timeout(60)
    driver.get(url)
    time.sleep(3)
    body_element = driver.find_element(by=By.TAG_NAME, value="body")
    children = body_element.find_elements(by=By.XPATH, value="./*")
    content = ""
    for child in children:
        if child.tag_name == "div":
            content += child.text
    return content.replace("\n", "").replace("\t", "")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/python/lib/python3.10/site-packages/selenium/webdriver/common/selenium_manager.py", line 137, in run
    stdout = completed_proc.stdout.decode('utf-8').rstrip("\n")
AttributeError: 'str' object has no attribute 'decode'
```

### Operating System

centos7

### Selenium version

4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome120.0.6099.217

### What are the browser driver(s) and version(s) where you see this issue?

120.0.6099.109

**Comment by titusfortner** [comment]
Those are intended as internal classes and private API. The method names and the response values will be changing in the next release. 
That said said, please turn on logging so you can see what the underlying issue is.

**Comment by diemol** [comment]
I will close this issue because we did not get more information.
