### ISSUE TITLE
Python. Execute JS with element

### ISSUE THREAD

**Issue by hexum** [SeleniumHQ/selenium#1347]
I found two problems with python selenium.

First.
There is not direct way to get driver from element uses it.
It would be nice to have `element._driver` attribute.

Second.
There is no way to execute script with specific element.
```python
element = driver.find_element_by_id("scrollable")
driver.execute_script("e = arguments[0]; return e.scrollHeight", element)
```
This case is complicated by first.
I'd like to see code like below.
```python
element.execute_script("return e.scrollHeight")
```

Thank you for any advice.

**Comment by ddavison** [comment]
the last script removes the ability for the programmer to name their own element.  you are arbitrarily saying

> the element is `e`

**Comment by hexum** [comment]
`driver.execute_script` packs argument to array `arguments` and so brings restrictions too.
We can add extra argument to specify js variable name.
For example
```python
element.execute_script("return e.scrollHeight", var_name="e")
```

**Comment by AutomatedTester** [comment]
Unfortunately this is not possible.

We generate a javascript function and inject that into the page. `Arguments` is a Javascript construct that allows us to create a function without named parameters and allows us to access everything that is passed in. I suggest reading the [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) about it.

Thanks for the suggestion though.
