### ISSUE TITLE
[🚀 Feature]: PyPI classifiers for 3.11 and 3.12

### ISSUE THREAD

**Issue by jamesbraza** [SeleniumHQ/selenium#13472]
### Feature and motivation

https://pypi.org/project/selenium/ only lists 3.8 to 3.10.

I believe selenium supports 3.11 and 3.12 too, so can we add classifiers for this?

### Usage example

https://github.com/SeleniumHQ/selenium/blob/selenium-4.16.0/py/setup.py#L51-L53

Add more versions here, and possibly make a test matrix for different Python versions

**Comment by titusfortner** [comment]
Thanks, can you make a PR for it?
