### ISSUE TITLE
[🐛 Bug]: Python distribution package does not include license files 

### ISSUE THREAD

**Issue by stevecj** [SeleniumHQ/selenium#13484]
### What happened?

Attempt to collect license files from its Python distribution package dependencies fails for `selenium` because its distribution package does not include license files.

### How can we reproduce the issue?

```shell
1. After installing the selenium Python package, run `pip show selenium` and check the value of "Location" in the output.
2. Change to the `selenium-4.7.2.dist-info` subdirectory.
3. List the files and see that no license files are present.
4. View the contents of the METADATA file in that location, and see that it has no `License-File` entries.
```

### Relevant log output

```shell
n/a
```

### Operating System

rhel8

### Selenium version

4.7.2-python

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

no, n/a

**Comment by titusfortner** [comment]
Duplicate #12166
Will be released hopefully today
