### ISSUE TITLE
[🐛 Bug]: Typo in setup.py

### ISSUE THREAD

**Issue by EwaMarek** [SeleniumHQ/selenium#13486]
### What happened?

Dependency not installed because of typo introduced in https://github.com/SeleniumHQ/selenium/commit/f83765d173e057e85062129f0b0c805f2b4fce90, "typing_extension" vs "typing_extension**s**"

### How can we reproduce the issue?

```shell
Try to install the latest selenium with pip install on system that doesn't have typing_extensions installed and run `from selenium import webdriver`
```

### Relevant log output

```shell
E   ModuleNotFoundError: No module named 'typing_extensions'
```

### Operating System

Ubuntu 20.04

### Selenium version

4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.224

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

**Comment by diemol** [comment]
Would you like to send a PR to fix this?

**Comment by EwaMarek** [comment]
Sure, I'll do that ;)

**Comment by Jakub-CZ** [comment]
It's still bugged. The package name is `typing-extensions`, not `typing_extensions`.

**Comment by benoitheintz** [comment]
I still have the issue with the wheel file. When opening the selenium-4.17.1.dist-info/METADATA file, I don't see the requirement of `typing_extensions`.
```
Requires-Python: >=3.8
Requires-Dist: urllib3[socks]>=1.26,<3
Requires-Dist: trio~=0.17
Requires-Dist: trio-websocket~=0.9
Requires-Dist: certifi>=2021.10.8
Version: 4.17.1
```

**Comment by Jakub-CZ** [comment]
@benoitheintz That's because the package name is still wrong. I'm about to open a PR with a proper fix for this issue.
