### ISSUE TITLE
[🐛 Bug]: Setting local storage item with backslashes gives different string in local storage

### ISSUE THREAD

**Issue by SpyMachine** [SeleniumHQ/selenium#13496]
### What happened?

I am finding Selenium's behavior here dealing with escaped backslashes confusing. In the test below, you can see that we open up a page and try and set a local storage item to a JSON string which has one key/value pair, the value being it's own JSON string so it's escaped.

When I print this in Ruby I get exactly what I'd expect:
`{"Test":"{\"Something\":true}"}`

However, this is not the value I get in Chrome local storage. Instead I get:
`{"Test":"{"Something":true}"}`

This is no longer valid JSON because the escapes are gone.

After some debugging, I believe what is happening is that selenium is executing JS that is setting the local storage and adding my key and value as part of that Javascript to run. However, Javascript handles escaping backslashes differently than Ruby does and thus the backslash actually just gets removed in JS.

To me, the implementation detail that JS is used to set local storage should not be something I should know when using Selenium. I would expect the String I set to be what I expect. I fear that if the implementation ever changed and JS is no longer used, the behavior would change.

If this is not something Selenium will handle, could we at least add documentation clarifying the need to further escape your String's. I've worked around the issue by using gsub to add more backslashes but I'm not even 100% clear that's the appropriate solution.

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'

test = '{"Test":"{\\"Something\\":true}"}'
puts test
driver = Selenium::WebDriver.for(:chrome)
driver.get('https://www.google.com')
local_storage = driver.local_storage
local_storage['test'] = test
sleep 300000
```

### Relevant log output

```shell
2024-01-23 10:54:09 DEBUG Selenium [:command] -> POST session/48b736ef0bac2362050a7824826209b5/execute/sync 
2024-01-23 10:54:09 DEBUG Selenium [:command]    >>> http://127.0.0.1:9531/session/48b736ef0bac2362050a7824826209b5/execute/sync | {"script":"localStorage.setItem('test', '{\"Test\":\"{\\\"Something\\\":true}\"}')","args":[]} 
2024-01-23 10:54:09 DEBUG Selenium [:header]      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.16.0 (ruby macosx)", "Content-Length"=>"94"} 
2024-01-23 10:54:09 DEBUG Selenium [:header]    <<<  {"content-length"=>["14"], "content-type"=>["application/json; charset=utf-8"], "cache-control"=>["no-cache"]} 
2024-01-23 10:54:09 DEBUG Selenium [:command] <- {"value":null}
```

### Operating System

macOS Sonoma

### Selenium version

Ruby 3.1.3 selenium-webdriver 4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 120.0.6099.109

**Comment by diemol** [comment]
Can you please check with Firefox and see if this still happens?

**Comment by titusfortner** [comment]
The other piece of this is that all of this code should have been deprecated long ago (#10397). 😂 

Please use `#execute_script` directly:
```
            execute_script("localStorage.setItem('#{key}', '#{value}')")
```
