### ISSUE TITLE
[🐛 Bug]: selenium crashing without a proper message

### ISSUE THREAD

**Issue by humpataa** [SeleniumHQ/selenium#13499]
### What happened?

So I have installed python 3.8, selenium 4.16 and chromedriver on my web server with root ssh access. I can run chromedriver in terminal, looking good.

When I try a simple python script it crashes with error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/common/selenium_manager.py", line 84, in driver_location
    browser = options.capabilities["browserName"]
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sel.py", line 7, in <module>
    driver = webdriver.Chrome('chromedriver')
  File "/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
AttributeError: 'str' object has no attribute 'capabilities'
```

This is the script causing the crash:

```
#! /usr/bin/python3.8
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome('chromedriver')
driver.get("https://www.python.org")
print(driver.title)
```

It looks like it cannot find something, tries to check "capabilities" but they obviously don't exist for something "unknown". Instead of checking for type and existance of appropriate item & giving a useful message, it let's Python throw a message that doesn't help. This is very bad. Why not check and throw proper messages?

I have also downloaded ChromeLinux64 but don't really know what to do with it. Where to put it? Does it have to be in PATH? Somewhere in the directories of Selenium? Not needed at all? Not a single installation guide mentions it. My Linux server is a remote webserver, it does not have a GUI or something.

Any help is appreciated.

### How can we reproduce the issue?

```shell
I don't know because I don't know what the cause is.
```

### Relevant log output

```shell
See above.
```

### Operating System

Linux

### Selenium version

/usr/local/lib/python3.8/dist-packages/selenium-4.16.0

### What are the browser(s) and version(s) where you see this issue?

Chrome for Linux64

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 114

**Comment by titusfortner** [comment]
The first parameter expected by `Chrome()` is an options instance, not a string.
https://www.selenium.dev/documentation/webdriver/browsers/chrome/?tab=python#options

**Comment by titusfortner** [comment]
Also, Selenium manages both drivers and browsers now, so if you specify a browser, Selenium will make sure it gets used and find the right driver for it automatically.

**Comment by humpataa** [comment]
Thank you for the quick reply.

I have reinstalled selenium as there didn't seem to be a selenium-manager directory.
Unfortunately, it now crashes with another message:

```
Traceback (most recent call last):
  File "sel3.py", line 3, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/selenium/selenium-4.16.0/chrome-linux64/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x559b08e22f83 <unknown>
#1 0x559b08adbcf7 <unknown>
#2 0x559b08b1360e <unknown>
...
```

Please advise.

**Comment by humpataa** [comment]
Checked the path:

`/usr/local/lib/python3.8/dist-packages/selenium-4.16.0-py3.8.egg/selenium/webdriver/common/linux/selenium-manager
`

Indeed, there is no manager. There is not even a directory linux?!

**Comment by humpataa** [comment]
Okay, after turning on logging I saw a message saying that version of chromedriver and chrome mismatch.
And running Chrome as root DOES NOT WORK unless you set option "--headless" ... 
HOWEVER:
I can now run my python script from SSH terminal, but I it breaks when I try to run the same script from a system or exec command from a PHP script (the user then being web or php, apache or someone NOT being root).
I don't understand this: had to add "headless" to get Chrome to run as root, but running the script NOT as root gives the same error message "DevToolsActivePort file doesn't exist" which means NOT to run it as root.
Why?

**Comment by titusfortner** [comment]
I don't have a good answer for you, but I'll add some links that might help.

**Comment by humpataa** [comment]
I had to set "--no-sandbox" option to get it working. I have no idea why and what this means. Setting the whole thing up is so freakingly complicated. Now working with it doesn't seem to be easier. There seem to be no complete documentation, examples are missing or rare and short, mostly not explaining just showing, many things you find online are deprecated – a trial and error marathon. Holy!

**Comment by titusfortner** [comment]
For most people the defaults are exactly what they need, but some systems and setups are more complicated. Our [Chrome Documentation](https://www.selenium.dev/documentation/webdriver/browsers/chrome/) includes two links to pages discussing the various optional arguments. But I agree, knowing which ones you need can be trial and error and not obvious. 

We'd love help improving our documentation site if there are things you'd like to see or that can be made more clear.

**Comment by humpataa** [comment]
Well, it now almost breaks with "tab crashed" meassage.
So I have tried Firefox instead. Manager seems to do his job well, but it also crashes with another message giving no clue:

```
Selenium Manager binary found at: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager
Executing process: /usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/linux/selenium-manager --browser firefox --debug --language-binding python --output json
geckodriver not found in PATH
firefox not found in PATH
firefox not found in the system
Required browser: firefox 122.0
firefox 122.0 already exists
firefox 122.0 is available at /var/www/vhosts/***/.cache/selenium/firefox/linux64/122.0/firefox
Required driver: geckodriver 0.34.0
geckodriver 0.34.0 already in the cache
Driver path: /var/www/vhosts/***/.cache/selenium/geckodriver/linux64/0.34.0/geckodriver
Browser path: /var/www/vhosts/***/.cache/selenium/firefox/linux64/122.0/firefox
Using driver at: /var/www/vhosts/***/.cache/selenium/geckodriver/linux64/0.34.0/geckodriver
Started executable: `/var/www/vhosts/***/.cache/selenium/geckodriver/linux64/0.34.0/geckodriver` in a child process with pid: 18590 using 0 to output -3
POST http://localhost:52881/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'firefox', 'acceptInsecureCerts': True, 'moz:debuggerAddress': True, 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'moz:firefoxOptions': {'binary': '/var/www/vhosts/***/.cache/selenium/firefox/linux64/122.0/firefox'}}}}
Remote response: status=500 | data={"value":{"error":"unknown error","message":"Process unexpectedly closed with status 255","stacktrace":""}} | headers=HTTPHeaderDict({'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-cache', 'content-length': '107', 'date': 'Mon, 29 Jan 2024 09:47:58 GMT'})
Finished Request
```

Can one really work with all this?
I mean, the code is very simple, it doesn't make any difference what URL I use:

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import logging
import time

logger = logging.getLogger('selenium')
handler = logging.FileHandler('log.txt')
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

driver = webdriver.Firefox()
driver.get("https://www.google.com")
print(driver.current_url)
print(driver.title)

driver.quit()
```

Sorry, I am so very annoyed of this. Wth is the problem?
Any idea?

**Comment by titusfortner** [comment]
https://stackoverflow.com/questions/67090130/webdriverexception-process-unexpectedly-closed-with-status-255-selenium-ge

There's no way for selenium to make sure that all libraries required by Firefox driver in your setup are installed. It's part of the pain of trying to get things working in a dockerized setup.
