### ISSUE TITLE
[🚀 Feature]: Replacement for arguments of Selenium Grid 3 for Selenium Grid 4 (SE_OPTS)

### ISSUE THREAD

**Issue by Obitotski** [SeleniumHQ/selenium#13509]
### Feature and motivation

To work with **Selenium Grid 3** I used custom servlets and other options to setup custom Node container with docker-compose fle (**_chrome-node:3.141.59_**)
`- SE_OPTS=-servlets io.app.selenium.DownloadsServlet,io.app.selenium.UploadsServlet,io.app.selenium.ClipboardServlet,io.app.selenium.DeleteServlet -custom username=seluser,platform=LINUX,userHome=/home/seluser,downloads=/home/seluser/Downloads`

Now I face (when starting container with image of **chrome-node:latest**)
`Was passed main parameter '-servlets' but no main parameter was defined in your arg class`

How can I use this option (if it is possible) or replace it with something new and relevant in Selenium 4?

Thank you for help!

### Usage example

To work with the file system (download, upload, delete files) and clipboard on Nodes in Selenium Grid 4

**Comment by diemol** [comment]
What is your use case for Servlets?

**Comment by Obitotski** [comment]
Uploading, downloading and deleting files from the file system and also to work with clipboard

**Comment by diemol** [comment]
Selenium has supported remote file upload for a long time, and recently remote file downloads as well. I need to check the clipboard part, but I believe one can use JS for that.

Have you tried remote file uploads and downloads?

**Comment by Obitotski** [comment]
Do you mean Selenium 4 supports it (uploads and downloads) for remote Grid Nodes?

**Comment by diemol** [comment]
Selenium 3 already supports remote uploads, and Selenium 4 supports downloads for Grid Nodes as well.

**Comment by Obitotski** [comment]
Thank you a lot, everything works fine!

**Comment by diemol** [comment]
Great!
