### ISSUE TITLE
[🐛 Bug]: Selenium Bidi with Chromedriver CDP Throws Exception

### ISSUE THREAD

**Issue by RhamaDaragaaz** [SeleniumHQ/selenium#13500]
### What happened?

Been trying to implement the examples for Bidi functionality in Selenium, rough code as shown in the how to reproduce the issue section. 

Again, roughly, there's some navigation occurring before I actually use the select there but it's probably excessively verbose and specific to my org. And the methods are abstracted a bit but basically TestStep contains variables and methods to parse the arguments and capabilities for when the browser get created in setDriverChrome(path) and is used to get the driver object and set the page it navigates to. Underneath the driver is being assigned as a new RemoteWebDriver with the ChromeOptions passed in.

This is put together from two sources:
https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/bidi_api/
https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/cdp_api/

The first is on the Mutation Observation for the Bidi API and the second goes over what's needed to setup an event listener for CDP, since the two seemed related I combined them in troubleshooting but for reference the error below occurs without the second link code, so without the DevTools creation or session portion.

When I run this code the browser opens, navigates to the selected page, sets the Select value by id to a specified value attribute and then it should wait, print mutations counted over the sleep period, and end the session.

However, immediately after selecting the value for the select, many errors are logged in the console as shown below in relevant log output. 

Note: This does NOT end the run, the test continues and sleeps, logs the output, and ends the session. I'm trying to figure out how I avoid the tens of thousands of lines of error text this generates in the console log every time it starts logging mutations after this point.

What is causing the the Connection Unable to process error at the start of the message, like I see that it's eventually down to a ClosedChannelException, am I missing something here? Or should this be caught and maybe not logged excessively if it's expected to occur when a event is being tracked/logged this way? Or is there something else underneath this I haven't set yet that's required for the Bidi functionality to work correctly? I've looked for similar errors but they've largely been unhelpful or unrelated entirely. 

### How can we reproduce the issue?

```shell
getTestStep().withBinaryPath("C:\\bin\\chrome\\chrome.exe")
.withBrowserArguments("--no-proxy-server", "--remote-debugging-port=9222")
.withBrowserCapability("pref:download.default_directory", System.getProperty(Common.LOCAL_PATH),					"webSocketUrl", true)
.setDriverChrome(getData(TestRun.OPTION_DRIVER_PATH));
DevTools dt = ((HasDevTools)getTestStep().getDriver()).getDevTools();
dt.createSession();
dt.send(Runtime.enable());
	getTestStep().setPage(getData(TestRun.OPTION_START_PAGE));

List<DomMutationEvent> mutations = Collections.synchronizedList(new ArrayList<>());
((HasLogEvents)getTestStep().getDriver()).onLogEvent(domMutation(mutation -> {
			mutations.add(mutation);
		}));
        
Select test = new Select(getTestStep().getDriver().findElement(By.id("price_fact.rate_type_code::0")));
test.selectByValue("FIXED");

Thread.sleep(1000);
System.out.println("Mutations: " + mutations.size());

getTestStep().getDriver().quit();
```

### Relevant log output

```shell
[2024-01-24 00:07:44.143] - 25572 WARNING [CDP Connection] --- org.openqa.selenium.devtools.Connection: Unable to process: {"method":"Runtime.bindingCalled","params":{"name":"__webdriver_attribute","payload":"{\"target\":\"ii98x8xfi5elrrg0qif\",\"name\":\"disabled\",\"value\":\"disabled\",\"oldValue\":null}","executionContextId":8},"sessionId":"BEBBE32FED58DAF57378FFBD8EC15435"}
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [4712cf89cde5020185336bd362837a82, findElements [using, value]]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 119.0.6045.105, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: C:\Users\user\AppData\Lo...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:9222}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:9222/devtool..., se:cdpVersion: 119.0.6045.105, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 500, pageLoad: 60000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://localhost:9302/session..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4712cf89cde5020185336bd362837a82
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:550)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:182)
	at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:103)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:373)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:367)
	at org.openqa.selenium.devtools.events.CdpEventTypes$2.lambda$initializeListener$0(CdpEventTypes.java:109)
	at org.openqa.selenium.devtools.idealized.Javascript.lambda$addBindingCalledListener$2(Javascript.java:95)
	at org.openqa.selenium.devtools.Connection.lambda$handle$5(Connection.java:345)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openqa.selenium.devtools.Connection.handle(Connection.java:308)
	at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:236)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.UncheckedIOException: java.net.ConnectException
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:442)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:358)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:188)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:523)
	... 22 more
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1047)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:198)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:230)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:206)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	... 3 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195)
	at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:760)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:848)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:183)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:185)
	... 9 more
```

### Operating System

Windows 10

### Selenium version

4.16.1 and using Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome for Test/Chrome v119.0.6045.105

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver v119.0.6045.105

### Are you using Selenium Grid?

Not for this issue

**Comment by diemol** [comment]
Is there a way you can provide a piece of code that only uses Selenium? Without the wrappers of your test code.

**Comment by titusfortner** [comment]
You don't want to mix methods from those pages.
 
We are working to switch the current implementation (Chrome DevTools Protocol) to the new WebDriver BiDi specification. The "BiDi API" is designed to be implementation agnostic, so whether it happens with CDP or BiDi spec it will just work. As such your this:

```
List<DomMutationEvent> mutations = Collections.synchronizedList(new ArrayList<>());
((HasLogEvents)getTestStep().getDriver()).onLogEvent(domMutation(mutation -> {
			mutations.add(mutation);
		}));
```

this is already starting the session and enabling the domains. Start by removing this piece:
```
DevTools dt = ((HasDevTools)getTestStep().getDriver()).getDevTools();
dt.createSession();
dt.send(Runtime.enable());
	getTestStep().setPage(getData(TestRun.OPTION_START_PAGE));
```

Second step would be to turn on logging to see what is happening when the error occurs: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by RhamaDaragaaz** [comment]
Ok, took some troubleshooting to replicate this without any of our wrappers but this produces the error intermittently, every few runs or so it'll throw the errors in my OP, pretty sure it's when clicking the first element using the JavascriptExecutor click. It occurs also on the select I think, it's harder to tell when running it as in debug mode different warnings come up. Tried to replicate two different scenarios in which I see the error in my original code.

```
        Logger logger = Logger.getLogger("");
		logger.setLevel(Level.FINE);
		Arrays.stream(logger.getHandlers()).forEach(handler -> {
            handler.setLevel(Level.INFO);
        });
		ChromeOptions options = new ChromeOptions();
		
		options.setBinary("C:\\bin\\chrome\\chrome.exe");
		
		options.setImplicitWaitTimeout(Duration.ofMillis(500));
		options.setPageLoadTimeout(Duration.ofSeconds(60));
		options.setScriptTimeout(Duration.ofSeconds(30));
		
		options.addArguments("--start-maximized");
		
		options.addArguments("--no-proxy-server", "--remote-debugging-port=9222");
		options.setAcceptInsecureCerts(true);
		options.setCapability("pref:download.default_directory", System.getProperty(Common.LOCAL_PATH));
		options.setCapability("webSocketUrl", true);
		
		System.setProperty("webdriver.chrome.driver", "C:\\bin\\chrome\\chromedriver.exe");
		ThreadLocal<WebDriver> driver = new ThreadLocal<WebDriver>();
		driver.set(new ChromeDriver(options));
		try {
			driver.get().get("www.mywebsite.net");
			
			List<DomMutationEvent> mutations = Collections.synchronizedList(new ArrayList<>());
			((HasLogEvents) driver.get()).onLogEvent(domMutation(mutation -> {
				mutations.add(mutation);
			}));
			
			((JavascriptExecutor) driver.get()).executeScript("arguments[0].click();", driver.get().findElement(By.id("form_heading")));
			
			driver.get().findElement(By.id("username")).sendKeys("super-user");
			driver.get().findElement(By.id("password")).sendKeys("PASSWORD");
			driver.get().findElement(By.id("Login")).click();
			
			Thread.sleep(5000);
			
			driver.get().switchTo().frame(driver.get().findElement(By.id("Fake ID")));
			
			List<WebElement> testList = driver.get().findElements(By.id("Fake ID"));
			WebElement testElement = testList.get(0);
			
			Select test = new Select(testElement);
			test.selectByVisibleText("Fake Element");

	        	System.out.println("Total Mutations: " + mutations.size());
                        System.out.println("Mutations Complete: Refreshed Page");
		}catch(Exception e) {
			e.printStackTrace();
		}finally {
			driver.get().quit();
		}
```

In the process of replicating it it seems like it's probably the implementation of ThreadLocal on the WebDriver that's causing the issue, but we utilize it similarly in our wrapper to ensure parallel test execution doesn't have issues with logs or data objects being shared across threads.

**Comment by titusfortner** [comment]
Ah, each frame/window has its own context, so you need to create a new listener after switching to the new frame.

**Comment by RhamaDaragaaz** [comment]
I could see that for the Select statement. However, what about the click occurring for the JavascriptExecutor, that occurs immediately after creating the listener and generates the error.

**Comment by titusfortner** [comment]
ah, I assumed the error wasn't until the find Element call.

@pujagani is our Java & BiDi expert. Any ideas whether/how ThreadLocal usage should impact this?

**Comment by RhamaDaragaaz** [comment]
Following up a bit in this. Further testing and debugging shows a DevTools exception is occurring in some of the CDP Connection threads that generates the error in my OP. The question I have is whether it's normal for hundreds of those CDP Connection threads to be spawned when Bidi is enabled and you start one of these domMutation listeners. As its the initialization of these many threads that appear to fail and generate the errors. 

Based on your above comment about needing new listeners for new frames being set I tried clearing and creating a new one before necessary changes and it seems to affect performance, if you try to track changes occurring the initial change is quick to be detected but further changes are slow to be detected. I was printing out when mutations occurred in the lambda expression and with just setting 3 fields by the third field set it would take between 5 and 10 seconds for the observer to print that the change had occurred. Working with just one listener across multiple frame changes and pages seemed to work better but when a large number of changes occurs, say 100+ detected it takes a while to respond. From debugging it seems like clearing listeners requires that the many threads it spawns respond back from the find elements to session request it makes, and they seem to frequently be stuck and time out after a set period, delaying the clear listeners until every single one times out in that state.

Is this expected behavior? Seems like clearing listeners ought not block like that at least. And the number of threads seems excessive, does it track Dom mutations by spawning a thread to track every node in the Dom or something?

**Comment by pujagani** [comment]
I appreciate the details shared here. I will require a reproducible test script/code snippet to look into this further. 
 https://github.com/SeleniumHQ/selenium/issues/13500#issuecomment-1908728620 - The code is not reproducible because the website under test is not valid. Please provide an updated code example to triage this further.

Meanwhile, I am trying to use a local sample to see if BiDi and CDP together throw the error.

To Titus's point, ThreadLocal is useful yet tricky. If used with ThreadPools and if the value is not removed at the end of thread execution, then the thread might be using an older value of the driver, which might cause the error (basing my thought process on "`org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.`" However, I don't know how the code shared is run, so not sure if this is valid in your case.

**Comment by pujagani** [comment]
The example below enabled BiDi and used CDP and this does not reproduce the error : 
 ```
   ChromeOptions options = new ChromeOptions();
    options.setImplicitWaitTimeout(Duration.ofMillis(500));
    options.setPageLoadTimeout(Duration.ofSeconds(60));
    options.setScriptTimeout(Duration.ofSeconds(30));

    options.addArguments("--start-maximized");
    options.setAcceptInsecureCerts(true);
    options.setCapability("webSocketUrl", true);
    WebDriver driver = new ChromeDriver(options);
    AtomicReference<DomMutationEvent> seen = new AtomicReference<>();
    CountDownLatch latch = new CountDownLatch(1);

    DevTools devTools = ((HasDevTools) driver).getDevTools();
    devTools.createSession();

    driver.get("https://www.google.com");
    WebElement span = driver.findElement(By.cssSelector("span"));

    ((HasLogEvents) driver).onLogEvent(domMutation(mutation -> {
      seen.set(mutation);
      System.out.println(mutation.getAttributeName());
      System.out.println(mutation.getCurrentValue());
      latch.countDown();
    }));

    ((JavascriptExecutor) driver)
      .executeScript("arguments[0].setAttribute('cheese', 'gouda');", span);

    latch.await();
    driver.quit();
```
This might not replicate the error you are facing, because the test is different or the scale of mutation received is different. I can help triage further with the updated reproducible code. I understand, that it might not be possible to share website under test , but any website that can help reproduce the issue should suffice. Thank you!

**Comment by RhamaDaragaaz** [comment]
I'll see if I can get a sample site working in the morning with that code, it occurs in many places on the internal site I'm testing so I figured the example would be enough to reproduce elsewhere if replacing the site with a valid one.

I'm not sure how the driver object could be old for the first element interacted with when using threadlocal though to generate the error. For reference I'm running this as a JUnit 5 test with a bare run configuration, no ThreadPoolExecutors or anything at the moment. I've stripped out any of our normal configurations for the test as well, such as the before/after annotations in order to reproduce the issue.

**Comment by pujagani** [comment]
Thank you for the details. Why are you using ThreadLocal? Just trying to understand.

**Comment by pujagani** [comment]
I have tried reproducing the error using JUnit5 with BiDi enabled but was unable to reproduce the error.

**Comment by RhamaDaragaaz** [comment]
Here's another code example, pretty much identical to my previous one but with a public demo site and it just clicks one element, I get it pretty consistently but not always so it might take a couple tries.

```
@Test
	public void mutationObserverTestSite() {
		Logger logger = Logger.getLogger("");
		logger.setLevel(Level.FINE);
		Arrays.stream(logger.getHandlers()).forEach(handler -> {
            handler.setLevel(Level.INFO);
        });
		ChromeOptions options = new ChromeOptions();
		
		options.setBinary("C:\\bin\\chrome\\chrome.exe");
		
		options.setImplicitWaitTimeout(Duration.ofMillis(500));
		options.setPageLoadTimeout(Duration.ofSeconds(60));
		options.setScriptTimeout(Duration.ofSeconds(30));
		
		options.addArguments("--start-maximized");
		
		options.addArguments("--no-proxy-server", "--remote-debugging-port=9222");
		options.setAcceptInsecureCerts(true);
		options.setCapability("pref:download.default_directory", System.getProperty(Common.LOCAL_PATH));
		options.setCapability("webSocketUrl", true);
		
		System.setProperty("webdriver.chrome.driver", "C:\\bin\\chrome\\chromedriver.exe");
		ThreadLocal<WebDriver> driver = new ThreadLocal<WebDriver>();
		driver.set(new ChromeDriver(options));
		try {
			driver.get().get("https://demoqa.com/books");
			
			List<DomMutationEvent> mutations = Collections.synchronizedList(new ArrayList<>());
			((HasLogEvents) driver.get()).onLogEvent(domMutation(mutation -> {
				mutations.add(mutation);
			}));
			
			((JavascriptExecutor) driver.get()).executeScript("arguments[0].click();", driver.get().findElement(By.xpath("//span[@id='see-book-Git Pocket Guide']//a")));
			
			Thread.sleep(3000);
			
	        System.out.println("Total Mutations: " + mutations.size());
            System.out.println("Mutations Complete: Refreshed Page");
		}catch(Exception e) {
			e.printStackTrace();
		}finally {
			driver.get().quit();
		}
	}
```

We're using ThreadLocal because it mimics my original test configuration in which I got the error. We use ThreadLocal to make sure our data, logger, and driver objects are not shared across threads. This was happening to us previously, particularly during TestFactory annotated tests for JUnit 5, where a last one in race condition was occurring for the driver, data, and logger objects. ThreadLocal stopped the object sharing that was occurring.

**Comment by pujagani** [comment]
Thank you for sharing this. I can reproduce the error locally. I will now triage this further and provide updates here.

**Comment by pujagani** [comment]
It turns out that enabling BiDi while using CDP does not cause the issue, it occurs when multiple mutations occur. 
For each mutation, our code has a listener. This calls `findElements` after which it uses the result to create a DomMutationEvent.  A call to  `findElements` in the listener is where the error ("`org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died."`) happens.

I tried to cut down any excess code to narrow it down to ensure nothing else impacts this. Simplest reproducible code snippet is below:
```
public class ChromeDevToolsDOMMutationWithBiDi {

    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i <= 10; i++) {
            WebDriver driver = new ChromeDriver();

            List<DomMutationEvent> mutations = Collections.synchronizedList(new ArrayList<>());

            ((HasLogEvents) driver).onLogEvent(domMutation(mutations::add));

            driver.get("https://www.google.com");

            Thread.sleep(3000);

            System.out.println("Mutations  -->" + mutations.size());

            driver.quit();
        }
    }
}
```
I tried to run the above example using Junit 5 and it is reproducible. On way way to identify the root cause behind the failing call.

**Comment by pujagani** [comment]
This issue is strange. I have tried many things to identify or fix the root cause and haven't figured it out yet. But the key issue is that any web driver command from within the listener causes the same error https://github.com/SeleniumHQ/selenium/blob/trunk/java/src/org/openqa/selenium/devtools/events/CdpEventTypes.java#L109. The error is ` Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes)`.  This indicates that maybe the server is temporarily down or unable to handle the request and has sent nothing back not even headers . Trying to see how we can sort this out.

**Comment by pujagani** [comment]
One solution that has worked is retrying the request. In that process, I discovered an underlying thread safety issue in the listener block. When multiple `Runtime.bindingCalled` events are fired, the listener registered was not thread-safe when calling the WebDriver related commands, in this case `findElements`. I have fixed that locally and run the code snippet shared above for over 400 runs and things look good. Will land the fix tomorrow and try to get a test for our codebase too.

**Comment by titusfortner** [comment]
We have a couple other open issues referencing parser received no bytes; not sure if related, but wanted to link them since this seems like a recent thing.

https://github.com/SeleniumHQ/selenium/issues/13481
https://github.com/SeleniumHQ/selenium/issues/13536

**Comment by RhamaDaragaaz** [comment]
That's great news that you have a potential solution. I've been working to implement this in my test framework and it works, albeit there appears to be a problem where the driver is blocked by the findElements method on the listeners you've mentioned. If the original error occurs it's particularly noticeable. You can call driver.switchTo().defaultContent() or driver.getWindowHandles() for example to reload the dom after many mutations occur (such as through a page change), and before the driver is able to execute these actions it waits for all the findElements threads in the listener to respond or timeout before proceeding. When debugging you can see the method called in the thread; step over the call to the driver and you can see all the individual findElements threads time out one by one and the driver doesn't do anything until the last one finishes what it was doing.

Hopefully the fix implemented helps alleviate this issue as well, otherwise it might be a problem for another thread. The functionality is exciting and I hope to use it more frequently.

**Comment by pujagani** [comment]
Thank you, Titus! The issues shared are facing the same error. However, the fix I have will only fix things for this particular use case (domMutation listener). I am sensing there could be an underlying Java 11 HttpClient bug that needs further investigation. 

@RhamaDaragaaz I appreciate the solution recommended. The solution I have is simple and uses a synchronized block. I have spent sufficient time eliminating other root causes that I thought were causing this error for this use case. Our long-term goal is to support the same functionality but using the W3C BiDi protocol and investing time in that space. So goal is to ensure this error does not occur but does not necessarily improve performance.
