### ISSUE TITLE
[🐛 Bug?]: class: 'OpenQA.Selenium.Remote.RemoteWebElement' is missing

### ISSUE THREAD

**Issue by ElektroStudios** [SeleniumHQ/selenium#13504]
### What happened?

I'm using Visual Studio. I've updated **Selenium.Support** and **Selenium.WebDriver** nuget packages from version 4.16.2 to 4.17.0, and now the class `OpenQA.Selenium.Remote.RemoteWebElement` is missing.

I can't find any info about what happened to `RemoteWebElement` class, so I decided to open this issue.

Is this change intentional or it is a bug / design issue?. 

If the change was intentional: was the class moved to another namespace, or it was just removed?. Could you give details about this decision and/or the new namespace?.

----------------------

This simple helper extension method written in VB.NET that casts a `IWebElement` to `RemoteWebElement` is not working anymore:

```
<Extension>
Public Function AsRemoteWebElement(element As OpenQA.Selenium.IWebElement) _
    As OpenQA.Selenium.Remote.RemoteWebElement

    Return DirectCast(element, OpenQA.Selenium.Remote.RemoteWebElement)
End Function
```

What would be the alternative to the code without the `RemoteWebElement `class?.

### How can we reproduce the issue?

```shell
1. In a C# or VB.NET project in Visual Studio, 
   Install Selenium.Support and Selenium.WebDriver nuget packages version 4.17.0.

Note: I can ensure that from version 4.13.0 to 4.16.2 the `RemoteWebElement` class is still there.
```

### Relevant log output

```shell
Not relevant to the issue.
```

### Operating System

Not relevant to the issue.

### Selenium version

dotnet

### What are the browser(s) and version(s) where you see this issue?

Not relevant to the issue.

### What are the browser driver(s) and version(s) where you see this issue?

Not relevant to the issue.

**Comment by ElektroStudios** [comment]
I'm very sorry, I just have found the official changelog for v4.17.0:

https://github.com/SeleniumHQ/selenium/blob/b5259d8a4bcef7114733e269aaa4fce743e88c29/dotnet/CHANGELOG#L15

As per what I've seen in the search results of this repository, this change was NOT made in java version for example, the `RemoteWebElement` class was removed in dotnet version.

But then, there is an alternative and totally equivalent class to `RemoteWebElement` for dotnet version?. If not, then now what will happen with all the users that needs (or prefer) to cast an `IWebElement` interface to `RemoteWebElement` type for use?.

Thanks in advance.

**Comment by titusfortner** [comment]
Yes, it's been marked Obsolete for a while, and we just finally removed it:

https://github.com/SeleniumHQ/selenium/blob/selenium-4.16.0/dotnet/src/webdriver/Remote/RemoteWebElement.cs#L26

**Comment by ElektroStudios** [comment]
> Yes, it's been marked Obsolete for a while, and we just finally removed it:
> 
> https://github.com/SeleniumHQ/selenium/blob/selenium-4.16.0/dotnet/src/webdriver/Remote/RemoteWebElement.cs#L26

Thanks for support. 

Would it be too much to ask before closing this thread permanently, if someone could clarify for me that the `WebElement` class is an 100% equivalent replacement for the `RemoteWebElement` class?.

**Comment by titusfortner** [comment]
You can see from the code that all `RemoteWebElement` did was inherit from `WebElement`
