### ISSUE TITLE
[🐛 Bug]: Possibly a huge memory leak?

### ISSUE THREAD

**Issue by iotanum** [SeleniumHQ/selenium#13510]
### What happened?

I've noticed that my automation tool started throwing `tab crashed` a few weeks ago. After doing some troubleshooting I've concluded it's something that selenium is doing behind the scenes.

I've tried the same scenario with `playwright` and I didn't have any memory leaks whatsoever.
Browsing the site in a "normal" Chrome browser has no issues.

What I mean by memory leaks - **just refreshing the page makes the tab have a 2GB+ memory footprint (looking at the Chrome task manager) in just a few minutes**.

**UPDATE 2024/01/25:**
Tried reproducing this on other pages (in my case **9gag.com**).
Just refreshing the page makes the memory footprint go up by +-50mb. And the footprint doesn't go down. Even after waiting 2 minutes, it stays up in the high 600s. 
Trying this on a normal Chrome browser doesn't do that. Goes up to +-500mb and instantly goes down to 300mb.

### How can we reproduce the issue?

```shell
from selenium import webdriver
import time

driver = webdriver.Chrome()
driver.get("9gag.com")

time.sleep(3600)
```

### Relevant log output

```shell
Nothing I've seen in debug logs is relevant to this issue.
```

### Operating System

Windows 11, Sonoma 14.2.1

### Selenium version

Python 3.11.5, Python 3.9.5, Selenium 4.17.2

### What are the browser(s) and version(s) where you see this issue?

Chrome 121 (this issue appeared since 119)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121.0.6167.85  (this issue appeared in 119)

**Comment by peppelongo96** [comment]
@iotanum i can confirm all mate. Same situation here!
Did you find a fix or something? Can't find a way to downgrade too.

**Comment by titusfortner** [comment]
You can specify the browser version in the options class and if it isn't on the computer, selenium will download it for you

**Comment by peppelongo96** [comment]
@titusfortner using UC here. Any way to use Selenium Manager with it?

**Comment by iotanum** [comment]
@peppelongo96 hey, I've just gone with the beta (v122) at this moment. Specify binary_location, get the beta chromedriver and you should be fine.

**Comment by peppelongo96** [comment]
@iotanum same problem here with beta. Also i have more and more InvalidSessionIdException causing driver to be restarted by new. But I don't know if it caused by high memory usage.

**Comment by iotanum** [comment]
hmm, strange. The beta fixed the issues for me.

I've also had a memory leak from `lxml` lib. Maybe check your app with `memray` or smth?

**Comment by titusfortner** [comment]
No, selenium manager will not support UC. I recently discovered its usage is likely illegal in at least California.

**Comment by peppelongo96** [comment]
@titusfortner okay thanks for the response
@iotanum just tested now with chromedriver v122 + chrome v122 and seems resolved.
Anyway something strange happened since I have a lot of InvalidSessionIdExceptions from the drivers and they are not related to RAM usage since there are like 2gb still free.

**Comment by peppelongo96** [comment]
@iotanum not related to lxml for sure.
And I can confirm problem persist here also wirh v122 beta...
Can't find nonthing on the internet. Seems it is only an our issue...

**Comment by iotanum** [comment]
@peppelongo96 sorry, can't help you with anything else :(. My issues were fixed with v122.

Double confirm if what you're experiencing is a memory leak (chrome task manager tool, memray).
If possible I'd suggest turning on selenium debug logs and finding a way to reproduce your issue.
Also, try other browsers and/or try `playwright` with a similar setup to what you have with selenium.
Good luck!

**Comment by peppelongo96** [comment]
@iotanum test already done with memray and all related to chrome clearly.
Yep i'll try with different browser thank you!

**Comment by dickinr** [comment]
There's a bug opened for this for the chromedriver project https://bugs.chromium.org/p/chromedriver/issues/detail?id=4696

**Comment by sparrowt** [comment]
Sadly that has been closed as WontFix due to lack of a repro. I'll try adding the repro steps from https://github.com/SeleniumHQ/selenium/issues/13533 and see if they will reopen.

EDIT: now reopened

**Comment by sparrowt** [comment]
See https://issues.chromium.org/issues/41494493
