### ISSUE TITLE
Where can I find the webdriver.xpi code ?

### ISSUE THREAD

**Issue by syjzwjj** [SeleniumHQ/selenium#1352]
When I look into the py code of selenium, I cant' find the code of webdriver.xpi . How can I get this plugin code ? Thank you!

**Comment by lukeis** [comment]
It's 'mostly' in here:
https://github.com/SeleniumHQ/selenium/tree/master/javascript/firefox-driver

Some of it is also in the javascript/atoms folder. Best to clone the whole selenium repo and open it up in IntelliJ or Eclipse.

**Comment by syjzwjj** [comment]
ok , and also one question ,I'm not very familiar with the development of firefox extensions.and  xpi files in selenium/javascript/firefox-driver/prebuilt/firefox-driver/ directory are the components library of firefox and these doesn't belong to the selenium it self ?  I am wrong?

**Comment by lukeis** [comment]
They do belong to selenium. They are Linux binaries, source of which is in the cpp/ folder. We check in prebuilts for anything that can't be built on all platforms.

**Comment by syjzwjj** [comment]
thank you!
