### ISSUE TITLE
[🐛 Bug]: ImportError: cannot import name 'deprecated' from 'typing_extensions' 

### ISSUE THREAD

**Issue by cwegener** [SeleniumHQ/selenium#13520]
### What happened?

Selenium have published a broken release (4.17.1) to PyPI which makes it impossible to for any application that depends on selenium to install successfully. And the application will get "stuck" at the broken version 4.17.1 because the version has not been yanked from PyPI.

### How can we reproduce the issue?

```shell
1. Create new python application that imports selenium webdriver
2. Add selenium as dependency
3. Add typing-extensions as another dependency and include an upper version constraint for typing-extensions like so: `typing-extensions>=3.10,<4`
4. Install the dependencies with `pip install`
5. Try and run the application
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/cwegener/Code/seleniumbroken/app.py", line 1, in <module>
    from selenium import webdriver
  File "/home/cwegener/Code/seleniumbroken/venv/lib/python3.10/site-packages/selenium/webdriver/__init__.py", line 29, in <module>
    from .firefox.firefox_profile import FirefoxProfile  # noqa
  File "/home/cwegener/Code/seleniumbroken/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 31, in <module>
    from typing_extensions import deprecated
ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/cwegener/Code/seleniumbroken/venv/lib/python3.10/site-packages/typing_extensions.py)
```
```


### Operating System

Linux

### Selenium version

4.17.1 ... it must be yanked from PyPI because of this bug

### What are the browser(s) and version(s) where you see this issue?

All browsers

### What are the browser driver(s) and version(s) where you see this issue?

All Drivers

### Are you using Selenium Grid?

_No response_

**Comment by diemol** [comment]
Please use 4.17.2

**Comment by cwegener** [comment]
> Please use 4.17.2

But I can't use 4.17.2 due to an incompatible `typing-extensions` version. I need to be able to use a version prior to `4.17.x`

**Comment by titusfortner** [comment]
Then how does it matter that it gets yanked?

**Comment by cwegener** [comment]
> Then how does it matter that it gets yanked?

Because 4.17.1 is a faulty release (unless one supplies something like `--no-binary :all:`  or `--no-binary selenium` to pip install as a workaround for the faulty 4.17.1 binary wheel package), and the pip dependency resolver will choose to install that faulty binary release even though the app dependency has a constraint of `typing-extensions>=3.10,<4` and therefore, 4.17.1 should not be chosen as an install candidate, but it will because of the broken wheel meta-data in 4.17.1.

And the selenium project used to yank broken builds from PyPI in the past.

The workaround for me is to update my application dependencies from:

`typing-extensions>=3.10,<4` to `typing-extensions>=3.10` which will allow me to start using `4.17.2` (but doesn't change the fact that `4.17.1` binary wheels on PyPI have been left in a broken state)

**Comment by titusfortner** [comment]
I'm not saying we shouldn't do it; I actually did try to do this when we first noticed it was a problem and did the re-release, but @AutomatedTester apparently I don't have full admin privileges on pypi to manage this package.

Other package management systems don't even allow for yanking, so it is not the end of the world for something to exist out there that can't be used when there is an update available. I would expect most setups to automatically update to the latest patch release without it being an issue.

**Comment by cwegener** [comment]
> so it is not the end of the world for something to exist out there that can't be used when there is an update available. I would expect most setups to automatically update to the latest patch release without it being an issue.

Yup. Any application that *only* depends on `selenium` will be fine, because `pip`'s resolver will successfully resolve to 4.17.2 or higher.

But in my example that I've given (and I think the GH bug template makes that example a bit hard to read due to strange formatting in the code block), the situation was that my application had an explicit dependency on `typing-extensions` in addition to the dependency on `selenium` **and** my dependency on `typing-extensions` had the upper version constraint (`<4`) which is what causes pip to be "forever" stuck on the broken release `4.17.1`  (this actually caused real world outages in pre-prod and is not a hypothetical scenario)

Ultimately, my top-level dependency constraint of `typing-extensions<4` was arbitrary and the `<4` constraint was easily removable for me as a workaround to resolve my outage.

**Comment by titusfortner** [comment]
Oh, right, that makes sense. Hmm, can we relax the typing extensions requirement? I'm not sure I looked at how strict it needs to be.

**Comment by cwegener** [comment]
> Oh, right, that makes sense. Hmm, can we relax the typing extensions requirement? I'm not sure I looked at how strict it needs to be.

Maybe? But probably not?  ... Your patch that introduced the change (including the original typo that causes 4.17.1 to be broken) is very difficult for me to understand. I suspect that the patch needs to be read in conjunction with another patch that actually starts making use of the `deprecated` decorator from the `typing-extensions` package?

The `@deprecated` decorator was first introduced in 4.5.0 and then in 4.9.0 the decorator was improved to:

> Changed in version 4.9.0: Inheriting from a deprecated class now also raises a runtime [DeprecationWarning](https://docs.python.org/3.12/library/exceptions.html#DeprecationWarning).

https://typing-extensions.readthedocs.io/en/latest/#deprecated

So, using 4.9.0 as the lower constraint seems correct to me.
