### ISSUE TITLE
[🚀 Feature]: Selenium Manager decrease frequency of statistics reporting

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13521]
### Feature and motivation

Currently making a call every time Selenium Manager is called. We should set it to only check once a day. I think we can re-use TTL? Or create a new TTL just for statistics.

### Usage example

n/a

**Comment by bonigarcia** [comment]
We must decide when the statistics are sent from SM to plausible. Here is my proposal.

I suppose we want to send statistics only once a day (we can reuse TTL for this or create a new parameter, as you prefer) each time SM receives a request with equal values of the following custom properties: lang, browser, browser_version, os, arch. The latter (os, arch) will be typically automated using the host's nature.

This way, for instance, if bindings call SM with the following equivalent command:

```
./selenium-manager --lang java --browser chrome
```

The first time, statistics will be sent. But second and successive equivalent commands within a day will not send stats to Plausible. But if the same host now requests another browser (e.g., firefox) or browser version (e.g., chrome beta), stats will be sent again (the first time in a day).

Also, we can include an exception regarding lang. If it is empty, maybe we should not send the statistics.

**Comment by diemol** [comment]
I think that is a good proposal. I like it. Once a day grouping by lang and browser. I would still send the stats even if lang is empty, that would point SM usage outside of the Selenium toolkit.

**Comment by bonigarcia** [comment]
Closed via https://github.com/SeleniumHQ/selenium/pull/13555.
