### ISSUE TITLE
[🐛 Bug]: running Builder() always opens 4 instances of Firefox

### ISSUE THREAD

**Issue by AdamDSherman** [SeleniumHQ/selenium#13529]
### What happened?

I hope this is the right place to post this.

I am running Selenium Webdriver 4.14.0 on Node 20.4.0 (on MacOS) and using Firefox as my browser.

All is well but for one thing: when I run `new Builder()` 4 instances of Firefox open.

### How can we reproduce the issue?

```shell
I have stripped back my code to the following fundamentals. Running this code reproduces the issue for me.


const { Builder, By, until, Key } = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');

let options = new firefox.Options();
    options.setPreference('geo.enabled', false);
    options.setAlertBehavior('dismiss');

const driver = new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build();
```
```


### Relevant log output

```shell
NA
```

### Operating System

macOS Monterey 12.4

### Selenium version

4.14.0

### What are the browser(s) and version(s) where you see this issue?

Firefox 104.0 (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Geckdriver 0.34.0

### Are you using Selenium Grid?

NA

**Comment by diemol** [comment]
I used version 4.17.0 to reproduce this, but I could not. 

I notice you are not quitting the browser. Maybe that is the issue. 

This is the code I used:

```js
const { Builder, By, until, Key } = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');

let options = new firefox.Options();
    options.setPreference('geo.enabled', false);
    options.setAlertBehavior('dismiss');

const driver = new Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(options)
    .build();

driver.quit();
```

**Comment by diemol** [comment]
I will close this for now, as we have not gotten any updates. I can reopen as soon as more information is provided.

**Comment by AdamDSherman** [comment]
Hi, sorry @diemol,

I did find the issue. It was not to do with Selenium but with Cucumber JS which amalgamated all my tests into 1 JS file. Hence, if I had 4 test .js files that had

``` 
const driver = new Builder()
    .forBrowser('firefox')
    .build();
```

in them, they would run 4 times and Firefox would open 4 times.

The work around is to put the driver build for each in your tests first Cucumber functions, eg:

**Do this:**
```
Given('I am on the About Us page', async function () {
    this.driver = new Builder()
        .forBrowser('firefox')
        .build();
        this.driver.wait(until.elementLocated(By.className('h1')));

    await this.driver.get('https://www.mywebsite.com/about');
});
```

**Don't do this:**

```
const driver = new Builder()
    .forBrowser('firefox')
    .build();

Given('I am on the About Us page', async function () {
        driver.wait(until.elementLocated(By.className('h1')));
        await driver.get('https://www.mywebsite.com/about');
});
```

Alternatively, I'm sure there is a way to implement

```
const driver = new Builder()
    .forBrowser('firefox')
    .build();
```
once for all test files, but I have not done that yet.
