### ISSUE TITLE
[🚀 Feature]: Replace https://github.com/asafh/jtoml as it has been abandoned

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/selenium#13538]
### Feature and motivation

This TOML parser is used to read the configuration file in Grid, the code has been abandoned and it might have vulnerabilities. 

### Usage example

We could replace it with https://github.com/tomlj/tomlj, and it is the only one with recent releases.

Worst case, fork the one we use and update it.

**Comment by Delta456** [comment]
I can work on this issue. Let's go with the `tomlj/tomlj` parser.

**Comment by Delta456** [comment]
A warning for the upcoming change was added in https://github.com/SeleniumHQ/selenium/commit/6b4c39c19e9ac3f63bbf8827cfd26aa782e77042 and `Tomlj` PR #14470  will be added after next two releases

**Comment by Delta456** [comment]
It is finally implemented with the help of @pujagani!
