### ISSUE TITLE
[🐛 Bug]: download.default_directory does not prevent popup when running in non-headless mode

### ISSUE THREAD

**Issue by lanzi8** [SeleniumHQ/selenium#13535]
### What happened?

Our automated tests including file downloads fail, because file popup appears in non-headless mode, using newest chrome version. It seems the bugfix mentioned here is not working in newest chrome version 121.0.6167.140 https://github.com/SeleniumHQ/selenium/issues/13208

### How can we reproduce the issue?

```shell
Start automated tests with following chrome options


            args: [
                // '--headless',
                '--disable-gpu',
                '--window-size=1920x1080',
                'lang=en-EN',
                'incognito',
                'disable-features=DownloadBubble,DownloadBubbleV2'
            ],
            prefs: {
                'download.directory_upgrade': true,
                'download.default_directory': downloadDir,
                'download.prompt_for_download': false,
                'safebrowsing.enabled': true
            }
`
```

### Relevant log output

```shell
No relevant output
```

### Operating System

Windows 11

### Selenium version

JavaScript webdriverio 7.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 121.0.6167.140

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121.0.6167.140

**Comment by nileshach** [comment]
@titusfortner : Could you please help with this issue. this issue is happening only incase of incognito mode Chrome 121.0.6167.140

**Comment by diemol** [comment]
@nileshach you need to report this to the Chrome folks using the links above, we have no control over that behavior.
