### ISSUE TITLE
[🐛 Bug]: mypy detects incompatible types

### ISSUE THREAD

**Issue by kellypilot** [SeleniumHQ/selenium#13544]
### What happened?

When checking types with mypy v1.8.0, incompatible types are detected

url_to_be is declared as 
`def url_to_be(url: str) -> Callable[[WebDriver], bool]:`

but any_of requires other argument type
`def any_of(*expected_conditions: Callable[[D], T]) -> Callable[[D], Union[Literal[False], T]]:`

### How can we reproduce the issue?

```shell
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

self.__waiter: WebDriverWait
self.__data_url: str

elements = self.__waiter.until(
    EC.any_of(
        EC.visibility_of_any_elements_located((
            By.CSS_SELECTOR,
            "p.3yeW3"
        )),
        # mypy error: Argument 2 to "any_of" has incompatible type
        # "Callable[[WebDriver], bool]";
        # expected "Callable[[Any], Literal[False] | list[WebElement] | WebElement]"
        EC.url_to_be(self.__data_url)
    )
)
```

### Relevant log output

```shell
error: Argument 2 to "any_of" has incompatible type "Callable[[WebDriver], bool]"; expected "Callable[[Any], Literal[False] | list[WebElement] | WebElement]"  [arg-type]
```

### Operating System

Ubuntu

### Selenium version

4.17.2

### What are the browser(s) and version(s) where you see this issue?

does not matter

### What are the browser driver(s) and version(s) where you see this issue?

does not matter

**Comment by titusfortner** [comment]
Thanks for reporting. Please feel free to submit a PR.

**Comment by navin772** [comment]
@titusfortner I have raised a PR for this issue, can you please review it?

**Comment by navin772** [comment]
@kellypilot can you give the full executable code to reproduce the error? If I run `mypy` on the above code, I just get 
`error: Name "self" is not defined` error.

**Comment by payalgupta0123** [comment]
> @kellypilot can you give the full executable code to reproduce the error? If I run `mypy` on the above code, I just get `error: Name "self" is not defined` error.

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
