### ISSUE TITLE
[🚀 Feature]: Requesting support for linux aarch64 for Selenium Manager

### ISSUE THREAD

**Issue by DashwoodIce9** [SeleniumHQ/selenium#13542]
### Feature and motivation

Hi Selenium team,

Thanks for the awesome project! My team intends to run Web UI tests with Selenium with multiple servers in the cloud. ARM64 based server offerings from AWS provide better value for us and we are in the process of migrating our applications from x86_64 to aarch64. Currently the `selenium-manager` binaries shipped do not have support for Linux aarch64. And therefore we are unable to move our tests to ARM based platform. Requesting support to build an aarch64 binary for Selenium Manager.

Thanks!

### Usage example

`./selenium-manager` works as expected on Linux aarch64. Currently it fails with error code 126 with the message -
```
zsh: exec format error: ./selenium-manager
```

**Comment by diemol** [comment]
There are no official ARM browser driver binaries for Chrome and Edge. When they are available, we'll look into this.
