### ISSUE TITLE
[🐛 Bug]: The documentation for the JavaScript selenium-webdriver API is currently unavailable due to a "page not found" error.

### ISSUE THREAD

**Issue by chandrahaswtw** [SeleniumHQ/selenium#13541]
### What happened?

I'm encountering a "page not found" error when attempting to access the [URL](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/) provided for the Selenium JavaScript API documentation mentioned on the [GitHub page](https://github.com/SeleniumHQ/selenium/tree/trunk/javascript/node/selenium-webdriver#documentation). Has the URL been updated or changed? If so, could you kindly provide the new URL? Thank you for your assistance.

<img width="1040" alt="Screenshot 2024-02-03 at 6 48 28 PM" src="https://github.com/SeleniumHQ/selenium/assets/40623790/bec807fa-4456-457f-8640-0ef2f7d4eec6">

### How can we reproduce the issue?

```shell
Selenium-webdriver javascript documentation page is not accessible.
```

### Relevant log output

```shell
Selenium-webdriver javascript documentation page is not accessible.
```

### Operating System

All OS - Page not found error.

### Selenium version

Javascript 4.17.0

### What are the browser(s) and version(s) where you see this issue?

All browsers

### What are the browser driver(s) and version(s) where you see this issue?

All browsers

**Comment by titusfortner** [comment]
We don't have a way to update the documentation so we removed it. Being tracked with #7242 
If you'd like to make a PR to remove the reference it would be appreciated.

**Comment by CarterFendley** [comment]
o.0

Ummmm, it would be really nice to have an API reference.
