### ISSUE TITLE
[🐛 Bug]: "no loaderId found for the current frame" after opening a bookmark

### ISSUE THREAD

**Issue by Parsee1** [SeleniumHQ/selenium#13543]
### What happened?

It occurs to me just after my Chrome updated from 112 to 121 recently. It was fine before the update.

### How can we reproduce the issue?

```shell
1. Open Chrome with a new ChromeDriver.
2. Go to any url with driver.get(url).
3. Open any bookmark within current window.
4. Boom! Find any element and see the exception. Try switching window or frame won't help.
```

### Relevant log output

```shell
no such execution context: no loaderId found for the current frame
  (Session info: chrome=121.0.6167.140)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6bfea55179b7e4e1b95d68fe6ab38cb4, findElements {using=xpath, value=//*[contains(@class,'product_table_list')]//*[contains(@class,'product_box')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 121.0.6167.140, chrome: {chromedriverVersion: 121.0.6167.85 (3f98d690ad7e..., userDataDir: C:\Users\Parsee\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50795}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50795/devtoo..., se:cdpVersion: 121.0.6167.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6bfea55179b7e4e1b95d68fe6ab38cb4
org.openqa.selenium.WebDriverException: no such execution context: no loaderId found for the current frame
  (Session info: chrome=121.0.6167.140)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6bfea55179b7e4e1b95d68fe6ab38cb4, findElements {using=xpath, value=//*[contains(@class,'product_table_list')]//*[contains(@class,'product_box')]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 121.0.6167.140, chrome: {chromedriverVersion: 121.0.6167.85 (3f98d690ad7e..., userDataDir: C:\Users\Parsee\AppData\Loc...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50795}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50795/devtoo..., se:cdpVersion: 121.0.6167.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6bfea55179b7e4e1b95d68fe6ab38cb4
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:134)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:182)
	at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:103)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:369)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:363)
	at amiami.BrowsePreowned.readProducts(BrowsePreowned.java:90)
	at amiami.BrowsePreowned.lambda$main$0(BrowsePreowned.java:246)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Operating System

Windows 10 Home 20H2 19042.1526

### Selenium version

selenium-java 4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 121.0.6167.140 64-bit

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121.0.6167.85 Win64

**Comment by Parsee1** [comment]
My code:
`package amiami;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import utils.Utils;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.time.Period;
import java.util.*;

public class BrowsePreowned1 {

    private static WebDriver driver = null;
    private static final String userDataDir =
            "C:\\Users\\Parsee\\AppData\\Local\\Google\\Chrome\\User Data\\Selenium1\\Selenium2";

    private static int tabIndex = 0;
    public static void switchTab(){
        try{
            List<String> tab = new ArrayList<>(driver.getWindowHandles());
            tabIndex++;
            if(tabIndex >= tab.size())
                tabIndex = 0;
            driver.switchTo().window(tab.get(tabIndex));
            driver.switchTo().defaultContent();
        }
        catch (Exception e) {
            System.err.println(e.getLocalizedMessage());
            e.printStackTrace();
        }
    }

    public static boolean readProducts(){
        boolean has_data = false;
        try {
            List<WebElement> list = driver.findElements(By.xpath(   //  商品列表页面
                    "//*[contains(@class,'product_table_list')]//*[contains(@class,'product_box')]"));
            has_data = true;
        }
        catch (Exception e) {
            System.err.println(e.getLocalizedMessage());
            e.printStackTrace();
            if(e.getLocalizedMessage().contains("no loaderId found for the current frame")){
                switchTab();    //  not working
                Utils.Sleep(1f);
            }
        }
        return has_data;
    }


    public static void main(String[] args){

        ChromeOptions options = new ChromeOptions();
        options.addArguments("user-data-dir=" + userDataDir);
        options.addArguments("allow-file-access-from-files");
        options.addArguments("start-maximized");
        driver = new ChromeDriver(options);
        driver.get("https://slist.amiami.jp/top/search/list3" +
                "?s_cate2=459&s_condition_flg=1&s_st_condition_flg=1&s_sortkey=preowned&pagemax=60");

        driver.manage().timeouts()
                .pageLoadTimeout(Duration.ofSeconds(30))
                .implicitlyWait(Duration.ofSeconds(3));
        Utils.Sleep(3);

        driver.switchTo().defaultContent();

        Thread t = new Thread(() -> {
            while(true){
                if(readProducts()){
                    Utils.Sleep(1);
                }
                Utils.Sleep(1);
            }
        });
        t.setDaemon(true);
        t.setName("Selenium query thread");
        t.start();

        Scanner in = new Scanner(System.in);
        for(boolean loop = true; loop;){
            String cmd = in.nextLine().toLowerCase();
            System.out.println(">>" + cmd);
            switch(cmd){
                case "exit":
                    loop = false;
                    break;
                default:
                    break;
            }
        }

        t.interrupt();
        driver.quit();
    }
}`

My bookmarks involved:
1. https://slist.amiami.jp/top/search/list3?s_cate1=8551&s_condition_flg=1&s_sortkey=preowned&s_st_condition_flg=1&pagemax=60&s_cate_tag=1
2. https://slist.amiami.jp/top/search/list3?s_cate2=459&s_condition_flg=1&s_st_condition_flg=1&s_sortkey=preowned&pagemax=60

Try switching between the 2 bookmarks above and you'll see the exception.

@diemol  Please re-label the issue.

**Comment by diemol** [comment]
Before trying this, can you tell me what happens if you use Firefox?

**Comment by Parsee1** [comment]
> Before trying this, can you tell me what happens if you use Firefox?

@diemol  Just tried Firefox 122.0 with geckodriver 0.34.0, it works fine.

**Comment by diemol** [comment]
That is good to know. Then you should report this to the Chrome folks.

**Comment by SmartManoj** [comment]
Workaround: Don't open bookmarks.

Also, bookmarks containing chrome internals URLs like chrome://version are not affected.
