### ISSUE TITLE
Chrome 121 incognito mode the dialogue file appears when download file[🐛 Bug]: 

### ISSUE THREAD

**Issue by XavierYuste-Atos** [SeleniumHQ/selenium#13550]
### What happened?

Chrome 121 incognito mode the dialogue file appears when download file
It's working inthis way from chrome 117, but until now we are using this chrome option when the driver is created:
chromeOptions.addArguments("disable-features=DownloadBubble,DownloadBubbleV2");
but in the new chrome 121 this chromeOption is not working

### How can we reproduce the issue?

```shell
using chrome 121 and chromedriver 121 a java project with selenium and cucumber trying to execute a scenario which access to a web page, and tries to download a file, the file dialogue appears.
Until now we are using the chrome option:
chromeOptions.addArguments("disable-features=DownloadBubble,DownloadBubbleV2");
And the file dialogue was not displayed, but with the new chrome version is not working
Thanks
Xavier
```

### Relevant log output

```shell
there are not log, the problem is about the dialogue file is displayed
```

### Operating System

windows 10

### Selenium version

4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 121

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 121

### Are you using Selenium Grid?

4.1.1

**Comment by VietND96** [comment]
@xyuste, this change in Chrome 121 seems to impact test automation much. For now, via ChromeOptions in Selenium (https://github.com/SeleniumHQ/selenium/issues/13104#issuecomment-1805331380) it doesn't work anymore.
As I see, we can workaround by setting the policy for Chrome at the level OS/Platform.
For example I tried on Windows, via Windows Registry set Chrome Policy.
To simplify the steps, let's create a bat file e.g `Set_Chrome_Policy.cmd` file, put commands REG there, and you can transfer it to different machines and execute bat script (it requires Run as Administrator) for updating entirely.

_If test machines joined the same domain and Chrome browser displayed `Your browser is managed by your organization`, I think you can ask IT for help setting those policies at level domain and enforce to all machines in the domain._

```cmd
@echo off
reg add "HKEY_CURRENT_USER\Software\Policies\Google\Chrome" /v PromptForDownloadLocation /t REG_DWORD /d "00000000" /f
reg add "HKEY_CURRENT_USER\Software\Policies\Google\Chrome" /v DownloadBubbleEnabled /t REG_DWORD /d "00000000" /f
reg add "HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome" /v PromptForDownloadLocation /t REG_DWORD /d "00000000" /f
reg add "HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome" /v DownloadBubbleEnabled /t REG_DWORD /d "00000000" /f
pause
```

After set that to platform, via `chrome://policy` in incognito mode, we will see

![image](https://github.com/SeleniumHQ/selenium/assets/23253546/eae7e03c-b346-4d60-8e7d-042e0dcad742)

When trying to download, it will not prompt for download location and display like this

![image](https://github.com/SeleniumHQ/selenium/assets/23253546/618bf073-249c-4055-9428-4c79e8dc565a)

For other platforms e.g Ubuntu, MacOS, I have not checked yet. If anyone can configure the Chrome policy on these platforms then confirm if it works.

Btw, the issue raised to Chrome team https://support.google.com/chrome/thread/255918298/download-panel-gone-forever?hl=en - looks like they expected `millions of people complain` for the considering to bring it back :))

**Comment by XavierYuste-Atos** [comment]
Hi VietND96,

Many thanks for your workaround !!!!!!!!!!
I have applied your suggested changes in the Windows Registry in my selenium Grid machine, and it works for me!!!
My test automation is working again :-)

Regards!!!!!!
Xavier
