### ISSUE TITLE
sendKeys does not work with FirefoxDriver 2.48.2

### ISSUE THREAD

**Issue by eichenschild** [SeleniumHQ/selenium#1357]
We try to set the value of an input element using selenium-firefox-driver 2.48.2 and Firefox ESR 38.0.1.
But the input element remains empty.
Please find a testcase below.

	@Test
	public void standalone() {
		final WebDriver driver = new FirefoxDriver();
		driver.get("https://www.theice.com");

		final WebElement login = driver.findElement(By
				.cssSelector("a[href*='login']"));
		login.click();

		final WebElement options = driver
				.findElement(By
						.xpath("//div[@class='selectbox-main']/a/span[text() = 'Select an Option']"));
		options.click();

		final WebElement option = driver.findElement(By
				.xpath("//ul/li/a[text()='Deal Reports']"));
		option.click();

		final WebElement username = driver.findElement(By
				.xpath("//input[@placeholder='Username']"));
		username.sendKeys("test");
		// input field in browser remains empty!
		
		driver.close();
	}

**Comment by ddavison** [comment]
Are you sure that you are selecting the element you think you are?  Is there any JavaScript in the web application preventing you from setting the text?  Is the text box in question, disabled?  If so, it needs to be enabled.

There are a lot of variables here, and if `sendKeys` truly _broke_, then we'd probably see more issues, but this is the first one i've seen regarding this.

I'd recommend bringing this up with the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
