### ISSUE TITLE
[🚀 Feature]: Add public constructors for ChromiumDriver

### ISSUE THREAD

**Issue by harmin-parra** [SeleniumHQ/selenium#13574]
### Feature and motivation

Hi, Their isn't a **Discussion** tab in this project, so I am opening this issue.

Can anybody explain to me how to use chromium driver with Java?

I realize that the **ChromiumDriver** doesn't have public constructors.

Could you add the following constructors ?

```
public ChromiumDriver()
public ChromiumDriver(ChromiumDriverService service,)
public ChromiumDriver(ChromiumOptions options)
public ChromiumDriver(ChromiumDriverService service, ChromiumOptions options)
```

### Usage example

```
ChromiumOptions options = new ChromiumOptions();
options.addArguments("--headless");
Webdriver driver = new ChromiumDriver(options);
```

**Comment by diemol** [comment]
You need to set the [browser binary location](https://www.selenium.dev/documentation/webdriver/browsers/chrome/#start-browser-in-a-specified-location) and the [browser driver binary location](https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location). You can use ChromeDriver for that, no need to use the ChromiumDriver class.
