### ISSUE TITLE
[🚀 Feature]: Make checking for updates and sending statistics optional

### ISSUE THREAD

**Issue by burrizza** [SeleniumHQ/selenium#13573]
### Feature and motivation

Hello there,

thanks for the great work you are doing here! I am using selenium very sporadically and since I updated the modules to the last version, I ran into troubles because of connections to the sites **github.com**, **githubusercontent.com** and **plausible.io**. Maybe I missed the option, but I have found no way yet to disable these requests. For the case that there is no option, it would be good to have one in my opinion. 
In my case, the computer is not connected to the internet and the request just taking time to fail anyway. 
Using an opt out could be necessary (depending on what information is stored) due GDPR.

Maybe someone which is deeper into that topic could correct me.

Have a great time!

### Usage example

Sorry, my example is only specific to the Python bindings and surely far away from optimum. 
```
from selenium import webdriver

fox_options = webdriver.FirefoxOptions()
fox_options.driver_send_stats = False
fox_options.driver_check_update = False

fox_driver = webdriver.Firefox(options = fox_options)
```

**Comment by diemol** [comment]
You can see all the information on how to do that in our [docs](https://www.selenium.dev/documentation/selenium_manager/#data-collection).

**Comment by burrizza** [comment]
Sorry, I really don't know how I missed that. Thank you!
