### ISSUE TITLE
[🐛 Bug]: For custom WebDriver while i try to using EventFiringDecorator getting ClasscastException

### ISSUE THREAD

**Issue by aruninfoseek** [SeleniumHQ/selenium#13584]
### What happened?

Hi, I have created a Custom webdriver class for webdriver, in selenium 3 i have used eventFiringWebdriver to extent my customdrvier class and i'll pass my customerwebdriver in constructor which was working fine,
 now i'm trying to migrate my framework from selenium 3 to 4 and i have updated my code as mentioned below

```
class MyCustomeDriver extends EventFiringDecorator{

 public MyCustomeDriver(Environment env) throws MalformedURLException {
        super.decorate(getDriver(env));  <--- this getDriver method will return webDriver
    }

```
for this above code snippet I'm not getting any compile time error where as, when i try to call my driver instance its not returning webdriver instance instead its returning MyCustomeDriver instance, so to get the webdriver I tried to cast it but i'm getting ClassCastException while executing it please help me to fix it 

I'm using java 17 and selenium 4.16.1
[https://github.com/appium/java-client/issues/1694](url)

### How can we reproduce the issue?

```shell
similar to below issue 
https://github.com/appium/java-client/issues/1694
```

### Relevant log output

```shell
getting ClassCastException
```

### Operating System

Windows 10

### Selenium version

4.16.1

### What are the browser(s) and version(s) where you see this issue?

chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

Webdriver manager

**Comment by pujagani** [comment]
The issue shared was an older issue. Can you please provide a reproducible test script using Selenium 4.17?

**Comment by aruninfoseek** [comment]
Hello @pujagani thanks for the suggestion, i tried with selenium-java 4.17.0 still i'm facing the same issue, please find below the code snippet 

`public class MyCustomDriver extends EventFiringDecorator {
    /**
     * Constructor
     *
     * @param env
     */
    public MyCustomDriver(Environment env) throws MalformedURLException {
        super.decorate(getDriver(env));
    }
}
`

Invoking my driver using Bean 

```
 @Lazy
    @Bean(destroyMethod = "quit")
    @Scope("cucumber-glue")
    @Conditional(NotIOS.class)
    public MyCustomDriver myCustomDriver() throws MalformedURLException {
        try {
            return new MyCustomDriver(environment);
        } catch (BeanCreationException e) {
            throw new MyCustomDriverException("Failed to create the MyCustomDriver instance");
        }
    }
```

where ever i try to call MyCustomDriver instance its not returning Webdriver instead its returning MyCustomDriver instance and asking me to cast to webdriver even after casting its still not working, getting below error 

```
io.cucumber.core.exception.CucumberException: 
Could not invoke hook defined at 'com.org.runner.RunnerIT.beforeTest(io.cucumber.java.Scenario)'.
It appears there was a problem with the hook definition.
Caused by: io.cucumber.core.backend.CucumberBackendException: Error creating bean with name 'boots.uk.runner.RunnerIT': Unsatisfied dependency expressed through field 'MyCustomDriver': Error creating bean with name 'MyCustomDriver' defined in com.org.MyCustom.config.MyCustomConfig: Invalid destruction signature
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.org.runner.RunnerIT': Unsatisfied dependency expressed through field 'MyCustomDriver': Error creating bean with name 'MyCustomDriver' defined in com.org.myCustomDriver.config.MyCustomConfig: Invalid destruction signature
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MyCustomDriver' defined in com.org.MyCustom.config.MyCustomConfig: Invalid destruction signature
Caused by: org.springframework.beans.factory.support.BeanDefinitionValidationException: Could not find a destroy method named 'quit' on bean with name 'MyCustomDriver'
```

**Comment by diemol** [comment]
We cannot do much with that code snippet. We need a complete test script only using Selenium to work on this.

**Comment by aruninfoseek** [comment]
apologies i can't share the full code its it client environment @diemol

**Comment by diemol** [comment]
Just like the bot replied:

>Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.

**Comment by aruninfoseek** [comment]
[EventFiringDemo.zip](https://github.com/SeleniumHQ/selenium/files/14297363/EventFiringDemo.zip)
Here I'm attaching sample project, the similar issue i'm getting in my framework as well, please help to fix this issue @diemol

**Comment by diemol** [comment]
Can you remove all the non-Selenium dependencies and provide an example **only** using Selenium?

**Comment by krmahadevan** [comment]
@aruninfoseek - In your `Main.java` you need to obtain the WebDriver as below

```java
WebDriver mydirver = (WebDriver) new myCustomDriver4().getDecoratedDriver().getOriginal();
```

This is because the EventFiringDecorator works on the `composition` principle (which means it has a `WebDriver` and it's NOT a webdriver

**Comment by aruninfoseek** [comment]
Thank you @krmahadevan its working now
