### ISSUE TITLE
[🚀 Feature]: 

### ISSUE THREAD

**Issue by SavvasNicoleCandiotti** [SeleniumHQ/selenium#13588]
### Feature and motivation

As a developer, I work on an internal UI component library where we have a lot of custom CSS variables that are exposed to our customers (for example, we may have a CSS with : 
UI Library CSS : 
```
display: flex;
flex-direction: var(--component-flex-direction, row);
```
so in this way, the customer can change the direction if they so chose in there project, for example
Customer CSS
```
--component-flex-direction: column;
```

In our UI Library project, I do not know of any way we can test with the framework if a custom CSS Var exists, only the end value, and we would like to know in our automation if the variable is exposed to the customer. Is there anyway we can achieve this feature ? 

### Usage example

For example, in this code, I would like a way to test that color and position cannot be modified but that width and height are exposed with css variables
```
.ui-library-container {
    color: green;
    position: relative;
    width: var(--ui-library-width, 100%);
    height: var(--ui-library-height, 25px);
```

Apologies if this feature already exists, and if so, could someone please direct me to the proper documentation

**Comment by titusfortner** [comment]
This is probably what you are looking for:
https://www.selenium.dev/documentation/webdriver/elements/information/#get-css-value

**Comment by SavvasNicoleCandiotti** [comment]
@titusfortner Not really, that is returning the final value of 13px, we need a way to get more details about whether or not there is also a custom variable name included, like --font-size, 13px. We already use this way and it does not give all of the information we need. Can you re-open this issue.

**Comment by diemol** [comment]
Selenium can get what the browser is rendering, not what the CSS tooling is offering.

I wouldn't use Selenium or a tool that needs to open a browser. Maybe component testing fits better.

**Comment by SavvasNicoleCandiotti** [comment]
@diemol so you are saying that a feature request to add what the CSS tooling is offering to Selenium is not something to entertain at this point in time?

**Comment by titusfortner** [comment]
Yes, that's out of scope for Selenium which is focused on how a user interacts with the browser specifically.
To a certain extent new features make sense to get added if they fit into the specification: https://w3c.github.io/webdriver/

**Comment by diemol** [comment]
I didn't say that. I said that opening a browser to test that is not the approach I would use.
