### ISSUE TITLE
[🐛 Bug]: Session deleted because of page crash

### ISSUE THREAD

**Issue by abhishek96negi** [SeleniumHQ/selenium#13581]
### What happened?

While running a selenium script in the keda after some point of time script is break due to this error:
`from the website i am getting this error:
Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed`

### How can we reproduce the issue?

```shell
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium import webdriver

options = webdriver.ChromeOptions()
chrome_service = ChromeService(
  executable_path='CHROME_EXECUTABLE_PATH'
)
driver = webdriver.Chrome(service=chrome_service, options=options)
driver.get('https://us04web.zoom.us/j/7791292XXXX')
join() # call join function
mute() # mute mic
```

### Relevant log output

```shell
from the website i am getting this error:
Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed
```

### Operating System

Linux OS

### Selenium version

selenium=4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 121

### What are the browser driver(s) and version(s) where you see this issue?

121

**Comment by diemol** [comment]
That means the browser crashed, most of the time it is related to the resources available to the container. There is not much we can do on the Selenium side towards that. You need to monitor CPU and RAM in order to determine what you need to provision depending on how heavy the tested apps are.

**Comment by abhishek96negi** [comment]
Hi @diemol I checked the CPU usage; it is within acceptable levels and not exhausted.
<img width="1282" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/64316612/64c614a3-227b-4a25-a5fa-ff83a01a11f0">

**Comment by diemol** [comment]
Are those values extracted in the exact same moment when the crash happened? What about the RAM?

**Comment by abhishek96negi** [comment]
Yes, RAM usage is 37%

**Comment by diemol** [comment]
Then maybe record a video and understand better when the page crashes and why.
