### ISSUE TITLE
Question: Is there a remote method to retrieve downloaded files?

### ISSUE THREAD

**Issue by JemiloII** [SeleniumHQ/selenium#1358]
I have test that validate file contents that are downloaded from my service. Running locally, I can set the download directory and read from it. However, with the remote selenium server, such as saucelabs, I do no know how to retrieve any of downloaded files with selenium.

**Comment by lukeis** [comment]
any other file transfer system? ftp? scp?

As for saucelabs, you'll need to ask them.

Please use our users mailing list for questions, github issues are for reproducible issues with the selenium product.
https://groups.google.com/forum/#!forum/selenium-users

**Comment by JemiloII** [comment]
Alright, thanks for the heads up!
