### ISSUE TITLE
[🐛 Bug]: Selenium.WebDriver version 4.17.0 does not support browser version is 121.0.2277.128 when browser is embedded web control

### ISSUE THREAD

**Issue by budcribar** [SeleniumHQ/selenium#13593]
### What happened?

Getting the error "Initialization method WebdriverTestProject.TestLocalEmbeddedBlazorWpf.Setup threw exception. System.InvalidOperationException: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 119
Current browser version is 121.0.2277.128 with binary path RemoteBlazorWebViewTutorial.WpfApp.exe (SessionNotCreated)." after updating my embedded web browser control

### How can we reproduce the issue?

```shell
embed web browser control that uses version 121 of webview2
 var options = new EdgeOptions
 {
     UseWebView = true,
     BinaryLocation = executable
 };
 driver = new EdgeDriver(options);
```

### Relevant log output

```shell
"Initialization method WebdriverTestProject.TestLocalEmbeddedBlazorWpf.Setup threw exception. System.InvalidOperationException: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 119
Current browser version is 121.0.2277.128 with binary path RemoteBlazorWebViewTutorial.WpfApp.exe (SessionNotCreated)." after updating my embedded web browser control
```

### Operating System

Windows 11

### Selenium version

C#  Selenium.WebDriver" Version="4.17.0" 

### What are the browser(s) and version(s) where you see this issue?

Embedded web browser control 121 from Microsoft.AspNetCore.Components.WebView.Wpf" Version="7.0.101"

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver" Version="4.17.0" 

### Are you using Selenium Grid?

n/a

**Comment by budcribar** [comment]
Here is the log output 
2024-02-17 18:00:49.673 TRACE SeleniumManager: Driver path: C:\Users\budcr\.cache\selenium\msedgedriver\win64\119.0.2151.72\msedgedriver.exe
2024-02-17 18:00:51.356 DEBUG HttpCommandExecutor: Executing command: []: newSession {"capabilities":{"firstMatch":[{"browserName":"webview2","ms:edgeOptions":{"binary":"RemoteBlazorWebViewTutorial.WpfApp.exe"}}]}}
2024-02-17 18:00:51.359 TRACE HttpCommandExecutor: >> Method: POST, RequestUri: 'http://localhost:55536/session', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
{
  Accept: application/json; charset=utf-8
  Content-Type: application/json; charset=utf-8
}
2024-02-17 18:00:52.247 TRACE HttpCommandExecutor: << StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Content-Length: 1638
  Content-Type: application/json; charset=utf-8
}
2024-02-17 18:00:52.250 DEBUG HttpCommandExecutor: Response: ( SessionNotCreated: System.Collections.Generic.Dictionary`2[System.String,System.Object])


as you see in the log, it is trying to load version 119. 
I am using 4.17.0 of Selenium.WebDriver and also version 121.0.2277.71-pre or Selenium.WebDriver.MSEdgeDriver 

	<PackageReference Include="Selenium.WebDriver" Version="4.17.0" />
	<PackageReference Include="Selenium.WebDriver.MSEdgeDriver" Version="121.0.2277.71-pre" />

**Comment by Vishwas-web** [comment]
have you downloaded the latest version of your browser? Change the path of the driver and see if its works or not

**Comment by budcribar** [comment]
My options are set as follows:
 var options = new EdgeOptions
 {
     UseWebView = true,
     BinaryLocation = executable
 };

UseWebView = true means that BinaryLocation is set to my executable which has the embedded web browser control, not to my Edge browser. but, yes my browser is up to date. Everything works normally on my tests which use the web browser only the tests which use the Executable with the embedded web browser am i having problems with

**Comment by nvborisenko** [comment]
First of all the `Selenium.WebDriver.MSEdgeDriver` package is not required, now selenium manages webdrivers automatically.

It determines that your edge version is:
> C:\Users\budcr.cache\selenium\msedgedriver\win64\119.0.2151.72\msedgedriver.exe

while your executable is `121`.

Probably you can help manager to understand what webdriver version to use via `EdgeOptions`:
```csharp
var options = new EdgeOptions
 {
     BrowserVersion = "121.0",
     UseWebView = true,
     BinaryLocation = executable
 };
```

**Comment by budcribar** [comment]
yeah... that works.. thank you

**Comment by nvborisenko** [comment]
@bonigarcia @titusfortner, interesting whether SM is able to determine edge browser automatically in this case.

**Comment by bonigarcia** [comment]
Yes, Selenium Manager is able to detect webview2, discover its version and manages the proper msedgedriver.
