### ISSUE TITLE
[🚀 Feature]: setCachePath(String cachePath) to copy the SM binary into customized directory instead of using temp folder

### ISSUE THREAD

**Issue by TamiWang** [SeleniumHQ/selenium#13599]
### Feature and motivation

I'm having issue running Selenium Manager with company's laptop due to the error:

> Caused by: java.io.IOException: Cannot run program "C:\Users\xxx.xxx\.cache\selenium\manager\0.4.17\selenium-manager.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator

I saw a similar issue was raised https://github.com/SeleniumHQ/selenium/issues/11770, and the suggestion was to get the group policy changed. However, our company has very strict policy, it's impossible to get it whitelisted, also it's not possible to add environment variable  SE_MANAGER_PATH to the system.

Would it be ok to introduce method **setCachePath(String cachePath)** to set the cache path, just like the one supported by WebDriverManager earlier? 

### Usage example

Just use it similar way in WebDriverManager to download the SM to a customized directory.

>                 WebDriverManager.getInstance(browserType).cachePath(WEBDRIVER_CACHE_PATH)
>                         .resolutionCachePath(WEBDRIVER_CACHE_PATH)
>                         .architecture(arch).setup();

**Comment by diemol** [comment]
The configuration options are environment variables or the `se-config.toml` file. We do not plan to add every option into the bindings, as it is possible to do that through the mechanisms mentioned before. 

https://www.selenium.dev/documentation/selenium_manager/#configuration

**Comment by TamiWang** [comment]
Ok, got it. Thank you @diemol.
