### ISSUE TITLE
[🐛 Bug]: BinaryLocation does not accept full path to executable with embedded web browser control

### ISSUE THREAD

**Issue by budcribar** [SeleniumHQ/selenium#13594]
### What happened?

 before Selenium.WebDriver" Version="4.11.0" you could specify the absolute path to the executable containing an embedded web browser control and use this option
 var options = new EdgeOptions
 {
     UseWebView = true,
     BinaryLocation = C:\program files\myexe.exe"
 };  
however after 4.11.0 you will get this error 
OpenQA.Selenium.WebDriverException: unknown error: no msedge binary at C:\program files\myexe.exe"

the workaround is to set the working directory and just give the name of the .exe as follows
  Directory.SetCurrentDirectory(Path.GetDirectoryName(BinaryLocation()) ?? string.Empty);
var options = new EdgeOptions
{
    UseWebView = true,
    BinaryLocation = executable
};

### How can we reproduce the issue?

```shell
Create a test program with an embedded web browser control and set the BinaryLocation to an absolute path
```

### Relevant log output

```shell
Initialization method WebdriverTestProject.TestLocalEmbeddedBlazorWpf.Setup threw exception. OpenQA.Selenium.WebDriverException: unknown error: no msedge binary at C:\Users\budcr\source\repos\RemoteBlazorWebViewTutorial\RemoteBlazorWebViewTutorial.WpfApp\bin\publishEmbedded\..\..\..\..\..\..\RemoteBlazorWebViewTutorial\RemoteBlazorWebViewTutorial.WpfApp\bin\publishEmbedded\RemoteBlazorWebViewTutorial.WpfApp.exe.

  Stack Trace: 
WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
WebDriver.StartSession(ICapabilities capabilities)
WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
EdgeDriver.ctor(EdgeDriverService service, EdgeOptions options, TimeSpan commandTimeout)
EdgeDriver.ctor(EdgeDriverService service, EdgeOptions options)
EdgeDriver.ctor(EdgeOptions options)
TestLocalBlazorForm.Setup() line 42
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Operating System

Windows 11

### Selenium version

C#  Selenium.WebDriver" Version="4.11.0" or later

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by titusfortner** [comment]
Please make sure you are using Selenium 4.17 and re-run with logging turned on so we can see what is getting sent to the selenium manager binary.

**Comment by budcribar** [comment]
2024-02-17 18:12:06.264 TRACE SeleniumManager: Driver path: C:\Users\budcr\.cache\selenium\msedgedriver\win64\119.0.2151.72\msedgedriver.exe
2024-02-17 18:12:07.940 DEBUG HttpCommandExecutor: Executing command: []: newSession {"capabilities":{"firstMatch":[{"browserName":"webview2","ms:edgeOptions":{"binary":"C:\\Users\\budcr\\source\\repos\\RemoteBlazorWebView\\testassets\\NUnitTestProject\\bin\\Debug\\net8\\..\\..\\..\\..\\..\\..\\RemoteBlazorWebViewTutorial\\RemoteBlazorWebViewTutorial.WpfApp\\bin\\publishEmbedded\\RemoteBlazorWebViewTutorial.WpfApp.exe"}}]}}
2024-02-17 18:12:07.943 TRACE HttpCommandExecutor: >> Method: POST, RequestUri: 'http://localhost:55716/session', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:
{
  Accept: application/json; charset=utf-8
  Content-Type: application/json; charset=utf-8
}
2024-02-17 18:12:09.764 TRACE HttpCommandExecutor: << StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Content-Length: 1851
  Content-Type: application/json; charset=utf-8
}
2024-02-17 18:12:09.767 DEBUG HttpCommandExecutor: Response: ( SessionNotCreated: System.Collections.Generic.Dictionary`2[System.String,System.Object]) 

Here is my log file. Looks different than the error I got last so I'm not sure what is going on.

**Comment by titusfortner** [comment]
Hmm, what is getting sent to the driver looks correct. Without more information I'd think it's an issue with edge driver. Maybe trying to turn on logs for the driver, but I dont have good examples for that in dotnet.

**Comment by nvborisenko** [comment]
@budcribar is this issue still actual?

**Comment by budcribar** [comment]
I believe so.

**Comment by diemol** [comment]
Do you get the same error when you follow the tutorial from Microsoft?
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by budcribar** [comment]
I'll try it again to see if specifying the whole path works.

**Comment by diemol** [comment]
I am closing this because we have yet to get more information.
