### ISSUE TITLE
[🚀 Feature]: Support for desktop PWA applications

### ISSUE THREAD

**Issue by jpx100** [SeleniumHQ/selenium#13592]
### Feature and motivation

Our team needs to test PWA application on desktop. We can test in in browser as normal web page but we have not find any way how to install it and test is when it is started as native application. 

### Usage example

We'd like to cover following scenario
- check install prompt is available
- install application
- open as native application
- test the application
- uninstall application

**Comment by diemol** [comment]
That is out of the scope of Selenium. Please check with https://github.com/appium/appium
