### ISSUE TITLE
[🚀 Feature]: Selenium Manager support mac_arm64

### ISSUE THREAD

**Issue by bhanu288** [SeleniumHQ/selenium#13590]
### Feature and motivation

Currently selenium manager only supports x64 build on macbook which sometimes intermittently results in slower download of chrome-driver. This could be due to the involvement of Rosetta 2 in between. 

As mentioned [here](https://github.com/SeleniumHQ/selenium/issues/11517#issuecomment-1411530798), there was a limitation due to Github action initially but now they support [M1 MacOS](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) 

Are we planning to ship arm64 bundles shortly?

### Usage example

Expecting improvement specifically in the below command:
`./selenium-manager --browser chrome --debug`

**Comment by krmahadevan** [comment]
@bhanu288 - I thought I would toss around these points so that you can share inputs from your side to add extra context to this issue

* Are you using any MacOS on your CI machines? I ask this because I believe that chrome and firefox for that matter should behave the same way across platforms and so it shouldn't really matter as to if you are running your UI test on chrome+osx or chrome +non osx.
* Given the fact that chromedriver binary download happens ONLY when the selenium manager determines that a newer version was published and requires to be downloaded, what is the frequency of your intermittent slowness and is there any time that you have noticed that to happen? Could there be a network lag that may also be contributing to this slowness ? (especially if you are behind a VPN or a corporate proxy) ?

**Comment by bhanu288** [comment]
@krmahadevan PFB the response:

**Comment by bhanu288** [comment]
@krmahadevan 

- Nope. It is my personal M1 laptop. One thing that I noticed once while using the `./selenium-manager --browser chrome --debug` command manually, was that download happened pretty fast but it was stuck at a previous step. I don't have the trace at the moment and it is not easily reproducible as well.
- That's correct it only happens when smeone install a newer version of chrome or using selenium-manager for the first time which requires a new driver download. It is not related to VPN or corporate proxy as there are team members without access to VPN who have faced the same issue. One pattern that we have seen frequently is that the chances of happening this are much higher when someone tries it for the first time on their laptop and most of the time subsequent downloads are pretty smooth so it doesn't look like a Network-related related to this. Another thing is that anyone with an Intel laptop never faced this issue.

**Comment by krmahadevan** [comment]
@bhanu288 - Since you are saying that you see this happen the first time, maybe you could do the following:

1. Create a `~/.cache/selenium/se-config.toml` configuration file for the selenium manager as explained [here](https://www.selenium.dev/documentation/selenium_manager/#configuration)
2. Delete the folders `chromedriver`, `geckodriver`, `manager`, `msedgedriver` under `.cache/selenium`
3. Update the configuration file to enable debug/trace logging 
4. Run your sample test case.
5. Share the logs so that @diemol or @titusfortner @bonigarcia can review it to find out if there's something that stands out.

These information will help the dev folks to determine if there is something that stands out and needs to be taken care of.

**Comment by bhanu288** [comment]
@krmahadevan  Tried this command `selenium-manager --browser chrome --debug --trace --clear-cache` 

Observed delay at this step, last time also it was the same step where we observed the delay but this doesn't happen every time. Chances are higher after a major version upgrade or using selenium-manager for the first time on the machine

`DEBUG	Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version`

Here is the full output. Let me know if this help? 

```
DEBUG	Clearing cache at: /Users/bhanu/.cache/selenium
DEBUG	Checking chromedriver in PATH
DEBUG	Running command: chromedriver --version
DEBUG	Output: "ChromeDriver 118.0.5993.70 (e52f33f30b91b4ddfad649acddc39ab570473b86-refs/branch-heads/5993@{#1216})"
DEBUG	Running command: which chromedriver
DEBUG	Output: "/opt/homebrew/bin/chromedriver"
DEBUG	Found chromedriver 118.0.5993.70 in PATH: /opt/homebrew/bin/chromedriver
DEBUG	chrome detected at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
TRACE	Original path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome - Escaped path: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
DEBUG	Using shell command to find out chrome version
DEBUG	Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
DEBUG	Output: "Google Chrome 121.0.6167.184 "
TRACE	The version of chrome is 121.0.6167.184
DEBUG	Detected browser: chrome 121.0.6167.184
TRACE	Reading metadata from /Users/bhanu/.cache/selenium/selenium-manager.json
TRACE	Metadata file does not exist. Creating a new one
TRACE	Driver version used to request CfT: 121
DEBUG	Reading metadata from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
TRACE	URLs for CfT: [PlatformUrl { platform: "mac-arm64", url: "https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/mac-arm64/chromedriver-mac-arm64.zip" }]
TRACE	Writing metadata to /Users/bhanu/.cache/selenium/selenium-manager.json
DEBUG	Required driver: chromedriver 121.0.6167.85
WARN	The chromedriver version (118.0.5993.70) detected in PATH at /opt/homebrew/bin/chromedriver might not be compatible with the detected chrome version (121.0.6167.184); currently, chromedriver 121.0.6167.85 is recommended for chrome 121.*, so it is advised to delete the driver in PATH and retry
INFO	Driver path: /opt/homebrew/bin/chromedriver
INFO	Browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
``` 

cc @diemol @titusfortner @bonigarcia

**Comment by diemol** [comment]
I still do not understand what the issue is.

**Comment by bhanu288** [comment]
**Issue**: on arm64 MacOS, the below command takes more time (almost a minute sometimes) which results in a slower download of Chromedriver via selenium-manager

`DEBUG	Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version`

**Request**:  Are we planning to ship a separate arm64 bundle of selenium manager?

**Comment by diemol** [comment]
Why would an arm64 bundle fix that? What is the reasoning behind that?

**Comment by bhanu288** [comment]
We are not certain but this hunch is based on the observation of the last 6 months, we have only observed this on M1/ M2 machines and never on Windows and Intel.

We tried this command `chrome --version` independently as well but were not able to reproduce the same behavior in the past as well. Hence the guess is that Rosetta's translation might be impacting the performance. That said there is no concrete supporting log to confirm the same.

**Comment by bhanu288** [comment]
@diemol if there is anything we can try in addition to the above-mentioned commands that can help in identifying the root cause, I'm happy to try that and provide the required info here.

**Comment by bonigarcia** [comment]
The Selenium Manager binary in macOS is compiled to both x64 and ARM64 architectures, and it is bundled as a universal binary using lipo:

https://github.com/SeleniumHQ/selenium/blob/trunk/.github/workflows/ci-rust.yml#L183

So, I suppose the issue related to long-time running commands is not caused by the binary architecture.

**Comment by bhanu288** [comment]
@bonigarcia Ack. anything you can think of that we can try to pin point the root cause?

**Comment by bonigarcia** [comment]
I don't know, sorry.

However, ensure that the latest Selenium Manager binary is used. You can get it from here:

https://github.com/SeleniumHQ/selenium_manager_artifacts/releases

**Comment by bhanu288** [comment]
@diemol please see if you can suggest anything to be checked in this or if there is any known reason for the same? 

https://github.com/SeleniumHQ/selenium/assets/11213709/575363f5-bbee-44ba-994a-6b612c6c980d

**Comment by titusfortner** [comment]
Please go off of the links here — https://github.com/SeleniumHQ/selenium/blob/trunk/common/selenium_manager.bzl

The latest release in the artifacts repo may not always be compatible with the current selenium bindings.

**Comment by bhanu288** [comment]
The issue is that the below command takes longer to identify the correct browser version during driver management in arm64 mac os:

`DEBUG	Running command: /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version`

This happens majority of the time post major chrome browser version updates. Have not tested with other browsers.

**Comment by suryart** [comment]
@bonigarcia - Thank you, this clears things on the `selenium-manager` arch.

> The Selenium Manager binary in macOS is compiled to both x64 and ARM64 architectures, and it is bundled as a universal binary using lipo:
> 
> https://github.com/SeleniumHQ/selenium/blob/trunk/.github/workflows/ci-rust.yml#L183
> 
> So, I suppose the issue related to long-time running commands is not caused by the binary architecture.

As suggested I tried this:

```
➜ file  ./node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager
./node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
./node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager (for architecture x86_64):	Mach-O 64-bit executable x86_64
./node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager (for architecture arm64):	Mach-O 64-bit executable arm64

➜ ls -lah  node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager
-rwxr-xr-x  1 surya  staff   8.1M Feb 15 19:51 node_modules/my-app/node_modules/selenium-webdriver/bin/macos/selenium-manager
```
Which is something expected as suggested by OP.

It seems like something is going wrong when the module is included as part of the electron app dependency. Post building the electron app, it seems to remove the arm64 arch as well as reduce its size by half:

```
➜ file /Applications/My-Electron-App.app/Contents/Resources/app/node_modules/selenium-webdriver/bin/macos/selenium-manager
/Applications/My-Electron-App.app/Contents/Resources/app/node_modules/selenium-webdriver/bin/macos/selenium-manager: Mach-O 64-bit executable x86_64

➜ ls -lah /Applications/My-Electron-App.app/Contents/Resources/app/node_modules/selenium-webdriver/bin/macos/selenium-manager
-rwxr-xr-x  1 surya  admin   4.0M Feb 22 19:17 /Applications/My-Electron-App.app/Contents/Resources/app/node_modules/selenium-webdriver/bin/macos/selenium-manager
```

**Comment by diemol** [comment]
@bhanu288 is this happening in all M1 machines you have in your org? Do all of them have Rosetta installed?

@suryart I am not sure how we could help. Bundling Selenium inside an electron app is out of our scope.

**Comment by bhanu288** [comment]
Closing this issue as this was related to the Electron itself
