### ISSUE TITLE
[🐛 Bug]: Could not start a new session on latest chrome browser 121.0.6167.185 (Official Build) (Windows 64-bit). 

### ISSUE THREAD

**Issue by sritejarusum** [SeleniumHQ/selenium#13591]
### What happened?

Could not start a new session on latest chrome browser 121.0.6167.185 (Official Build) (Windows 64-bit). 
Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114.

Maven Dependencies:

```
<!-- https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.6.3</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.17.0</version>
        </dependency>
```

Chrome version : 121.0.6167.185

### How can we reproduce the issue?

```shell
1. Update chrome browser to 121.0.6167.185, released on 13 February 2024, 
2. Use Selenium 4.17 and try to start browser session.



webdrivermanager - 5.6.3
selenium-java -4.17.0
```

### Relevant log output

```shell
below exception thrown in runtime:

Exception Occurred : Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 121.0.6167.185 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 

Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.5'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: [], prefs: {download.default_directory:
```

### Operating System

Windows 10 (64 -bit)

### Selenium version

selenium-java -4.17.0

### What are the browser(s) and version(s) where you see this issue?

Chrome -121.0.6167.184/185

### What are the browser driver(s) and version(s) where you see this issue?

webdrivermanager - 5.6.3

**Comment by diemol** [comment]
We do not maintain `webdrivermanager`, so I recommend to remove that dependency and let [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) handle it for you. 

If you still have the same issue after doing that, please comment and we can reopen the issue.

**Comment by diemol** [comment]
If you need help, please use one of the links below.
