### ISSUE TITLE
NS_ERROR_NOT_IMPLEMENTED nsIRequest.status in command-processor.js

### ISSUE THREAD

**Issue by rajatjindal83** [SeleniumHQ/selenium#1359]
Selenium Server standalone: 2.48.2
Firefox 41.0.2
Cent OS 6.5
xVfb

We are seeing the following error in Firefox browser logs from Firefox driver extension:

{"level":"INFO","message":"[Exception... \"Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIRequest.status]\"  nsresult: \"0x80004001 (NS_ERROR_N
OT_IMPLEMENTED)\"  location: \"JS frame :: file:///tmp/anonymous8176013423208898586webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js ::
PatientListener.prototype.onStateChange :: line 5072\"  data: no]","timestamp":1449610853942,"type":""}

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long period.
