### ISSUE TITLE
[🚀 Feature]: Add chrome-headless-shell to the browser options of selenium-manager.

### ISSUE THREAD

**Issue by sudoudaisuke** [SeleniumHQ/selenium#13600]
### Feature and motivation

I want to set chrome-headless-shell as browser in selenium-manager. 

https://github.com/SeleniumHQ/selenium/pull/13271

### Usage example

```sh
$ selenium-manager --browser chrome-headless-shell --driver chromedriver
```

Create a cache for chrome-headless-shell instead of google chrome from the Chrome for testing definition.

**Comment by titusfortner** [comment]
chrome-headless-shell is the stripped down part of Chrome that chromedriver uses when it starts in the old headless mode.
There's nothing separate to download, it's part of the Chrome installation, and there's not a good reason to support this independently.

**Comment by sudoudaisuke** [comment]
@titusfortner Thank you for reply.

I respect the project's policy, but I'm a little disappointed.
For the following reasons
1. "Chrome for Testing" and "Puppeteer" separates "chrome" and "chrome-headless-shell" downloads
   - https://developer.chrome.com/blog/chrome-headless-shell
   - https://googlechromelabs.github.io/chrome-for-testing/
2. There is a difference between "chrome" and "chrome-headless-shell" zip files and their size after decompression
   - chrome-linux64
       - zip file size: 143MB
       - decompression size: 354MB
   - chrome-headless-shell-linux64
       - zip file size: 88MB
       - decompression size: 185MB
