### ISSUE TITLE
Support for Message Sequencing changes in Marionette protocol

### ISSUE THREAD

**Issue by ldiary** [SeleniumHQ/selenium#1360]
I was playing around with Marionette and subsequently raised a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1231119) which received this response:

```
Bug 1211489 introduced message sequencing in the Marionette protocol and it appears this change is not reflected in the Selenium implementation.  Please file a bug with the Selenium project to update the Marionette protocol to support level 3.

See this thread to tools-marionette@ for further explanation: https://groups.google.com/d/msg/mozilla.tools.marionette/ZVWNINCjrTQ/hGtMg26oBgAJ
```

I have no idea what this level 3 support means, but if anyone can guide me somehow I might be able to help.

**Comment by AutomatedTester** [comment]
The bug in BMO has been reopened as we need to fix it there. Thanks for raising this bug.
