### ISSUE TITLE
[🐛 Bug]: Selenium.WebDriver version 4.16.1 does not support browser version is 121.0.2277.112 and getting error only support to browser version 119

### ISSUE THREAD

**Issue by Vishwas-web** [SeleniumHQ/selenium#13606]
### What happened?

Getting this error  "org.openqa.selenium.SessionNotCreatedException": could not start a new session. Response code 500. Message: Session not created: this version of Microsoft Edge WebDriver only supports Microsoft Edge Version 119.
The current browser version is 121.0.2277.112

### How can we reproduce the issue?

```shell
WebDriver driver = new EdgeDriver();
driver.get("url");
```

### Relevant log output

```shell
"org.openqa.selenium.SessionNotCreatedException": could not start a new session. Response code 500. Message: Session not created: this version of Microsoft Edge WebDriver only supports Microsoft Edge Version 119.
```

### Operating System

10

### Selenium version

Java selenium 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Edge 121.0.2277.112

### What are the browser driver(s) and version(s) where you see this issue?

Edgedriver version 4.16.1

### Are you using Selenium Grid?

no

**Comment by Vishwas-web** [comment]
I Cannot provide the full code or URL/html because I'm running it on  remote desktop

**Comment by diemol** [comment]
At least provide the logs, please.

**Comment by Vishwas-web** [comment]
I change the path of the edge with the new version and it works fine now
thanks!!
