### ISSUE TITLE
[🚀 Feature]: Add WaitForAPI response wait feature

### ISSUE THREAD

**Issue by sulaimaan26** [SeleniumHQ/selenium#13611]
### Feature and motivation

Most of the applications built today are webapps rather than the webpage where selenium is not so efficient to handle it, we need to concentrate more on handling waits it will be good if we had this feature where we can wait until some API call response. This feature is currently available in playwright.

### Usage example

I am automating a download scenario here I need to manually check respective directory whether file is downloaded or not rather than this if we have this feature, it will be easy to handle using "WaitForAPI" function. This is sample one it has more usage

**Comment by titusfortner** [comment]
This can be done by using DevTools right now, and will be available with the BiDi spec when it is completed.
https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/cdp_api/#download-complete
