### ISSUE TITLE
[🐛 Bug]: Drivers are not downloading automatically into ./cache/selenium when clear the cache. 

### ISSUE THREAD

**Issue by Suma123c** [SeleniumHQ/selenium#13617]
### What happened?

Steps to reproduce:
1. Previously I have selenium version 3+ and webdriver manager latest version where I am able to launch browser.(I have drivers in ./cache/selenium
2. Update version of selenium 4.17 and removed webdriver dependency and also deleted drivers from cache folder.
3. When I ran script to Pom.xml, Selenium Manager jar is downloaded in cache folder and script got failed due to unable to find driver.
can  you please help me to resolve the issue
Note: Unable to run on scale set agents through pipeline.

### How can we reproduce the issue?

```shell
Public static synchronised initiateDrive(RemoteWebDriver driver)
{
ChromeOptions options = new ChromeOptions();
options.addArguments(“—disabled-infobars”);
options.addArguments(“—headless”);
driver=new ChromeDriver(options)
}

Note: I have added some other options like enable-automation, —disable-dev-shm-usage, —disable-gpu etc.
```

### Relevant log output

```shell
org.openqa.selenium.remote.NoSuchDriverException
Unable to obtain: Capabilities {browserName: chrome, goog:ChromeOptions: {rags: [disable-infobars, —headless, —disabled-gpu, —disable-dev-shm-usage], extension:[]}, error Command failed with code: 65, executed: [—browser, chrome, —language-binding, java, —output, json]
error sending request for url(https://Google chrome labs.GitHub.io/chrome-for-testing/known-good-versions-with-downloads.json)
```

### Operating System

Windows 10

### Selenium version

Java and Sel ver 4.17

### What are the browser(s) and version(s) where you see this issue?

Chrome 121

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 121

### Are you using Selenium Grid?

No

**Comment by Suma123c** [comment]
Updated the log. As I am clearing the cache folder where drivers are available. Unable to find the driver

**Comment by diemol** [comment]
You cannot reach the Chrome URL where ChromeDriver information is put. 

Check the known issues and how to fix them at https://www.selenium.dev/documentation/selenium_manager/#known-limitations
