### ISSUE TITLE
[🚀 Feature]: Supporting custom capabilities mutators for Grid

### ISSUE THREAD

**Issue by Purus** [SeleniumHQ/selenium#13628]
### Feature and motivation

This is similar to the feature proposed in https://github.com/SeleniumHQ/selenium/issues/7478. But it was closed due to lack of user feedback and it was Selenium 3 Grid. 

Currently we have an option to provide a custom slot matcher via mode config. Similarly there should be an option to specify custom capabilities mutators via configuration. 

SlotMatchrer can only return a boolean after performing custom matching logic and the actual capabilities does not really understand any change.

The above closed issue highlights `SessionCapabilitiesMutator` but there are no way to provide custom capabilities mutators. 

In my use case, when capabilities have certain values I want to update them.

### Usage example

As part of mode config, both slot matcher and capabilities mutators can also be specified.

```
slot-matcher = "com.CustomSlotMatcher"
capabilities-mutator = "com.CustomMutator"
```

It will help to configure the grid without customising the node just for this feature.

**Comment by diemol** [comment]
What is the use case to override that class?

**Comment by Purus** [comment]
The grid gets updated often with new version of browsers.. But the users may have used old capabilities during the test execution. 

Instead of failing the request, we would like to enforce the version and update the incoming enrichment to the actual version..

**Comment by diemol** [comment]
So the user would be testing with a different browser instead of the one they requested. I don't think that makes sense.

**Comment by Purus** [comment]
Ok.. let me give some different use case used..

The grid will be updated frequently. Users can use the "browserName"
capability as "default" and the grid has to have an option to update the
browserName to actual version number( 121 or so).

Currently we have created a new custom node implementation and have made
changes to update the capabilities.

If this feature is out of box, it will avoid creating custom node
implementation.

**Comment by diemol** [comment]
I theory, Grid supports `stable`, and it should match the recent browser release. @titusfortner worked on it.

**Comment by Purus** [comment]
Above use case is just one example and our grid is evolving.

Another use case is enforcing 2 different proxies by updating the
capabilities.

It would be good to support such mutations out of box.

**Comment by diemol** [comment]
Would you like to send a PR for it?

**Comment by Purus** [comment]
Yes. I am interested..I will create a PR and would need your support for
review.

**Comment by Purus** [comment]
@diemol  can you please help with the review of the PR? This is my first contribution to selenium.
