### ISSUE TITLE
[🐛 Bug]: Firefox is starting instead of TOR after upgrading Selenium.WebDriver.dll to version 4.18.1

### ISSUE THREAD

**Issue by Rombersoft** [SeleniumHQ/selenium#13624]
### What happened?

I just upgraded libraries in Nuget PM and now Firefox starts instead of Tor.

### How can we reproduce the issue?

```shell
FirefoxDriverService firefoxDriverService = FirefoxDriverService.CreateDefaultService();
firefoxDriverService.FirefoxBinaryPath = settings.TorBinaryPath;
firefoxDriverService.BrowserCommunicationPort = 2828;
FirefoxOptions firefoxOptions = new FirefoxOptions
{
     Profile = null,
     LogLevel = FirefoxDriverLogLevel.Trace
};
firefoxOptions.AddArguments("-profile", settings.TorProfilePath);
FirefoxDriver driver = new (firefoxDriverService, firefoxOptions, TimeSpan.FromSeconds(120));
```
```


### Relevant log output

```shell
Try my code, maybe see logs
```

### Operating System

Debian 11

### Selenium version

NetStandard 4.18.1

### What are the browser(s) and version(s) where you see this issue?

TOR

### What are the browser driver(s) and version(s) where you see this issue?

13.0.9 (based on Mozilla Firefox 115.7.0esr

### Are you using Selenium Grid?

What is it?

**Comment by Rombersoft** [comment]
1708789213757   geckodriver     INFO    Listening on 127.0.0.1:43687
1708789213885   geckodriver::browser    DEBUG   Backing up prefs to "/home/destructor/Applications/tor-browser/Browser/TorBrowser/Data/Browser/profile.default/user.geckodriver_backup_65"
1708789213895   mozrunner::runner       INFO    Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/usr ... rionette" "-profile" "/home/destructor/Applications/tor-browser/Browser/TorBrowser/Data/Browser/profile.default" "-no-remote"
1708789213895   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1
1708789213895   geckodriver::marionette TRACE   Retrying in 100ms
1708789213996   geckodriver::marionette TRACE   Retrying in 100ms
1708789214096   geckodriver::marionette TRACE   Retrying in 100ms
1708789214196   geckodriver::marionette TRACE   Retrying in 100ms
1708789214296   geckodriver::marionette TRACE   Retrying in 100ms
1708789214397   geckodriver::marionette TRACE   Retrying in 100ms
1708789214497   geckodriver::marionette TRACE   Retrying in 100ms
1708789214598   geckodriver::marionette TRACE   Retrying in 100ms
1708789214698   geckodriver::marionette TRACE   Retrying in 100ms
1708789214798   geckodriver::marionette TRACE   Retrying in 100ms
1708789214898   geckodriver::marionette TRACE   Retrying in 100ms
1708789214999   geckodriver::marionette TRACE   Retrying in 100ms
1708789215099   geckodriver::marionette TRACE   Retrying in 100ms
1708789215199   geckodriver::marionette TRACE   Retrying in 100ms
1708789215300   geckodriver::marionette TRACE   Retrying in 100ms
1708789215400   geckodriver::marionette TRACE   Retrying in 100ms
1708789215500   geckodriver::marionette TRACE   Retrying in 100ms
1708789215601   geckodriver::marionette TRACE   Retrying in 100ms
1708789215701   geckodriver::marionette TRACE   Retrying in 100ms
1708789215801   geckodriver::marionette TRACE   Retrying in 100ms
1708789215901   geckodriver::marionette TRACE   Retrying in 100ms
1708789216002   geckodriver::marionette TRACE   Retrying in 100ms
1708789216102   geckodriver::marionette TRACE   Retrying in 100ms
1708789216202   geckodriver::marionette TRACE   Retrying in 100ms
1708789216303   geckodriver::marionette TRACE   Retrying in 100ms
1708789216403   geckodriver::marionette TRACE   Retrying in 100ms
1708789216503   geckodriver::marionette TRACE   Retrying in 100ms
1708789216604   geckodriver::marionette TRACE   Retrying in 100ms
1708789216704   geckodriver::marionette TRACE   Retrying in 100ms
1708789216805   geckodriver::marionette TRACE   Retrying in 100ms
1708789216905   geckodriver::marionette TRACE   Retrying in 100ms
1708789217005   geckodriver::marionette TRACE   Retrying in 100ms
1708789217106   geckodriver::marionette TRACE   Retrying in 100ms
1708789217206   geckodriver::marionette TRACE   Retrying in 100ms
1708789217306   geckodriver::marionette TRACE   Retrying in 100ms
1708789217407   geckodriver::marionette TRACE   Retrying in 100ms
1708789217507   geckodriver::marionette TRACE   Retrying in 100ms
1708789217607   geckodriver::marionette TRACE   Retrying in 100ms
1708789217708   geckodriver::marionette TRACE   Retrying in 100ms
1708789217808   geckodriver::marionette TRACE   Retrying in 100ms
1708789217909   geckodriver::marionette TRACE   Retrying in 100ms
1708789218009   geckodriver::marionette TRACE   Retrying in 100ms
1708789218109   geckodriver::marionette TRACE   Retrying in 100ms
1708789218210   geckodriver::marionette TRACE   Retrying in 100ms
1708789218310   geckodriver::marionette TRACE   Retrying in 100ms
1708789218410   geckodriver::marionette TRACE   Retrying in 100ms
1708789218511   geckodriver::marionette TRACE   Retrying in 100ms
1708789218611   geckodriver::marionette TRACE   Retrying in 100ms
1708789218711   geckodriver::marionette TRACE   Retrying in 100ms
1708789218812   geckodriver::marionette TRACE   Retrying in 100ms
1708789218912   geckodriver::marionette TRACE   Retrying in 100ms
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
1708789219012   geckodriver::marionette TRACE   Retrying in 100ms
1708789219112   geckodriver::marionette TRACE   Retrying in 100ms
1708789219213   geckodriver::marionette TRACE   Retrying in 100ms
1708789219313   geckodriver::marionette TRACE   Retrying in 100ms
1708789219319   Marionette      INFO    Marionette enabled
1708789219320   RemoteAgent     DEBUG   Setting recommended pref browser.tabs.unloadOnLowMemory to false
1708789219320   RemoteAgent     DEBUG   Setting recommended pref browser.urlbar.suggest.searches to false
1708789219320   RemoteAgent     DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1708789219320   RemoteAgent     DEBUG   Setting recommended pref dom.max_chrome_script_run_time to 0
1708789219320   RemoteAgent     DEBUG   Setting recommended pref network.http.prompt-temp-redirect to false
1708789219320   RemoteAgent     DEBUG   Setting recommended pref privacy.trackingprotection.enabled to false
1708789219320   Marionette      TRACE   Received observer notification final-ui-startup
1708789219365   Marionette      INFO    Listening on port 2828
1708789219365   Marionette      DEBUG   Marionette is listening
1708789219456   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:50900
1708789219467   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:2828.
1708789219507   Marionette      DEBUG   0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox"}]
1708789219509   Marionette      DEBUG   Waiting for initial application window
console.error: ({})
1708789220213   Marionette      TRACE   Received observer notification browser-idle-startup-tasks-finished
1708789220216   RemoteAgent     TRACE   [3] ProgressListener Start: expectNavigation=false resolveWhenStarted=false unloadTimeout=5000 waitForExplicitStart=false
1708789220216   RemoteAgent     TRACE   [3] ProgressListener Setting unload timer (5000ms)
1708789220216   RemoteAgent     TRACE   [3] Document already finished loading: about:blank
1708789220216   RemoteAgent     TRACE   [3] ProgressListener Stop: has error=false
1708789220220   Marionette      DEBUG   0 <- [1,1,null,{"sessionId":"5d1ea14b-a220-4c4a-979d-3dbe85c7ee32","capabilities":{"browserName":"firefox","browserVersion":"115.7.0","platformName":"linux","acceptInsecureCerts":false,"pageLoadStrategy":"normal","setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"strictFileInteractability":false,"unhandledPromptBehavior":"dismiss and notify","moz:accessibilityChecks":false,"moz:buildID":"20240115170312","moz:headless":false,"moz:platformVersion":"5.10.0-16-amd64","moz:processID":21542,"moz:profile":"/home/destructor/Applications/tor-browser/Browser/TorBrowser/Data/Browser/profile.default","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"moz:windowless":false,"proxy":{}}}]
1708789220221   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"5d1ea14b-a220-4c4a-979d-3dbe85c7ee32","capabilities":{"acceptInsecureCerts":false,"browserNa ... ctability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
console.error: "update.locale" " file doesn't exist in either the application or GRE directories"
1708789249331   addons.xpi      ERROR   System addon update list error SyntaxError: The URI is malformed.
JavaScript error: resource://gre/modules/PromiseWorker.sys.mjs, line 102: Error: Could not get children of file(/home/destructor/Applications/tor-browser/Browser/TorBrowser/Data/Browser/profile.default/thumbnails) because it does not exist

**Comment by titusfortner** [comment]
Those are the driver logs. Can you turn on the .NET client binding logs from the link in the previous post?
We need to see what is getting sent to the driver as part of capabilities.

**Comment by diemol** [comment]
I will close this issue because we have yet to get more information.

**Comment by Rombersoft** [comment]
I can not give you more information. I've rollback to previous version
where it works better.

сб, 6 квіт. 2024 р., 17:13 користувач Diego Molina ***@***.***>
пише:
