### ISSUE TITLE
[🐛 Bug]: Function evaluation failed on debug in Visual Studio Code

### ISSUE THREAD

**Issue by algot** [SeleniumHQ/selenium#13629]
### What happened?

When I tried to debug a simple code snippet from the Selenium Getting Started page I was not able to evaluate functions because of an error

`To prevent an unsafe abort when evaluating the function 'OpenQA.Selenium.WebElement.ComputedAccessibleLabel.get' all threads were allowed to run`

### How can we reproduce the issue?
Create simple Selenium project
Add following test snippet:

```csharp
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace selenium_temp;

public class Tests
{
    [Test]
    public void Test1()
    {
        var driver = new ChromeDriver();
        driver.Navigate().GoToUrl("https://www.selenium.dev/selenium/web/web-form.html");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(500);
        var textBox = driver.FindElement(By.Name("my-text"));
        var submitButton = driver.FindElement(By.TagName("button"));

        textBox.SendKeys("Selenium");
        submitButton.Click();

        driver.Quit();
    }
}
```
Run it in VS Code in debug mode

### Relevant log output

```shell
To prevent an unsafe abort when evaluating the function 'OpenQA.Selenium.WebElement.ComputedAccessibleLabel.get' all threads were allowed to run

Evaluation timed out
Cannot evaluate expression because a previous function evaluation timed out. You must continue execution to reenable function evaluation.
```

### Operating System

macOS 14.3.1

### Selenium version

C# 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122.0.6261.6901

### What are the browser driver(s) and version(s) where you see this issue?

122.0.6261.6901

**Comment by diemol** [comment]
@nvborisenko do you know?

**Comment by nvborisenko** [comment]
@algot what exactly you do in debugger? I ran the same code on my local - no issues. In debugger there are also no issues. Any screenshots will be useful.

One thing I may suppose you hover over the element to see its properties. Please provide some screenshots, and I will answer "It is normal, not selenium related" :)

**Comment by algot** [comment]
@nvborisenko 

Steps to reproduce:

- `dotnet new nunit`
- `dotnet add package Selenium.WebDriver`
- `dotnet add package Selenium.WebDriver.ChromeDriver`
- insert code snippet inside `UnitTest1.cs`

I just run default command 'debug test' from text editor window to run test code to breakpoint.
When debug stops on breakpoint error appears in debug console and only high-level values of variables are displayed in Locals window.
Please see screen recording
https://imgur.com/a/drDg8wS

**Comment by nvborisenko** [comment]
In Visual Studio I see the same:
![image](https://github.com/SeleniumHQ/selenium/assets/22616990/9c3e903b-deb8-457a-b3a5-d647a664032b)
  
but VS provides small icon to re-evaluate an expression:
![image](https://github.com/SeleniumHQ/selenium/assets/22616990/541a09de-99c4-4656-b257-641db8cdfa1c)

It is normal. To evaluate a property selenium should run background "thread", which is "not allowed" by debugger. All threads are "paused" once you hit breakpoint. VS can re-evaluate, VS Code doesn't provide this functionality. So, it is not selenium related. Please find some tips in area of .Net for VS Code.

PS: Probably, in Selenium v5, properties will represent a state of an object, I hope it will not be "calculated properties with underlying sync-over-async operations".
