### ISSUE TITLE
[🐛 Bug]: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error tying to connect: proxy authentication required

### ISSUE THREAD

**Issue by cyndihu** [SeleniumHQ/selenium#13630]
### What happened?

I am using the proxy with webdrivermanager 5.5.3, it works, the chrome driver can be downloaded successfully.

now I want to use selenium manager directly, I am using selenium 4.13, set chrome option with proxy username:password@proxy:8080, I am getting the error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error tying to connect: proxy authentication required

I tried configuration with selenium-manager-config.toml as well, it doesn't work.

there is special character comma(,) in my password, not sure if it affects.

![image](https://github.com/SeleniumHQ/selenium/assets/44665141/024a6158-b261-4b77-8676-cd9daea93158)

### How can we reproduce the issue?

```shell
Proxy proxy = new Proxy()
proxy.setHttpProxy("username:password@proxy:8080");
options.setCapalibilty(CapalibiltyType.PROXY,proxy);
SeleniumManager.getInstance().getDriverPath(options,false);
```

### Relevant log output

```shell
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error tying to connect: proxy authentication required
```

### Operating System

Windowns 10

### Selenium version

4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 121.0.6167.86

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 121.0.6167.86

**Comment by diemol** [comment]
Please upgrade to 4.18.1 and let us know how it goes.
