### ISSUE TITLE
Input text is entered in reverse order in Internet Explorer

### ISSUE THREAD

**Issue by premsvmm** [SeleniumHQ/selenium#1363]
while i try to input the text in the text field after clear the value .. the input which is entered after clear is in reverse order or some time it shuffle the text.

I use Internet Explore 10 
Selenium version 2.48.2
IEdriverserver 64 bit

**Comment by mentholi** [comment]
Can you show the code you were using to enter the text so it could be possible to test that and maybe figure out what's wrong.

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long period.
