### ISSUE TITLE
[🚀 Feature]: Java WebDriver should extend AutoCloseable

### ISSUE THREAD

**Issue by tandraschko** [SeleniumHQ/selenium#13637]
### Feature and motivation

The close method is already available (WebDriver#close) but adding AutoClosable interface would a allow easier closing

### Usage example

```
try (WebDriver driver = new HtmlUnitDriver())
{
    ....
}
```

vs

```
WebDriver driver = null;
try 
{
    driver = new HtmlUnitDriver();
    ....
}
finally {
    if (driver != null) {
        driver.close();
    }
}
```

**Comment by diemol** [comment]
The thing is that `close()` is meant to close the browser window, not to end the session. So, using `close()` does not terminate the session, you need to do `quit()`.

**Comment by tandraschko** [comment]
ahh damn, this also means that we cant use `#quit` as AutoCloseable as the current `#close` has the same signature as this from `AutoCloseable `. I think its not worth to make a change here?
thats a shame

**Comment by krmahadevan** [comment]
@tandraschko - You should be easily able to build this abstraction at your end no? Perhaps something like this ?

```java
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.Closeable;

public class CloseableDriverSample {

    public static void main(String[] args) {

        try (CloseableWebDriver closeable = closeableWebDriver()) {
            closeable.driver().get("https://www.selenium.dev");
            System.err.println(closeable.driver().getCurrentUrl());
        }
    }

    private static CloseableWebDriver closeableWebDriver() {
        return new CloseableWebDriver(new ChromeDriver());
    }

    record CloseableWebDriver(WebDriver driver) implements Closeable {

        @Override
        public void close() {
            driver.quit();
        }
    }
}
```

**Comment by krmahadevan** [comment]
I believe that the `AutoCloseable` WebDriver may not be something that is going to be useful to a lot of people because usually the `WebDriver` clean up part is done after screenshots are taken (incase of failures for e.g.,) and that is done via callbacks (or listeners in the TestNG lingo for e.g.,). So a Webdriver that gets autoclosed via `try..resources` is going to cause problems.

**Comment by tandraschko** [comment]
yeah, you are propably right

i just have a tons of tests here and only some use selenium, i thought to not write a "deep integration" with junit extensions and so on, just a very very basic usage

**Comment by diemol** [comment]
Yeah, it's probably not worth a change. This existed long before `AutoCloseable. '
