### ISSUE TITLE
Python WebDriver: driver.execute_script() executes scripts in previous pages context sometimes after calling driver.get()

### ISSUE THREAD

**Issue by mentholi** [SeleniumHQ/selenium#1364]
## Issue
Sometime when you first open page with `driver.get` and navigate to another page using `driver.get` again and then call `driver.execute_script` the script is executes in previous pages context. I would assume `driver.get` to block until the page has actually changed and only then return control to test script.

For example if you set some javascript variable on first page and then check that using `driver.execute_script` after calling `driver.get` it may still return the value even it should not.

## Expected behaviour
I expect `driver.get` to block test script from executing until page has changed. If `driver.execute_script` is called right after page load it should fail if javascript is not executed yet. It should not never use previous pages context.

## Test case that I'm able to reproduce the issue.
```python
def test_script_is_called_in_correct_context(self):
    # First open some test page and call scripts
    self.driver.get("/first_page.html")
    self._wait_for_engine_started(self.driver)
    self.driver.execute_script("window.ourNameSpace.engine.refreshAll();")
    WebDriverWait(self.driver, 10).until(
        lambda driver: driver.execute_script('return window.SELENIUM_TEST_PASSES;')
    )

    # Now change to another page
    self.driver.get("/second_page.html")

    #
    # NOTE: If line below are uncommented then the test seems to always pass.
    #
    #WebDriverWait(self.driver, 1).until(
    #    lambda driver: driver.execute_script('return window.location.href.indexOf("second_page") > -1;')
    #)

    # If I uncomment below line it also sometimes prints previous page url.
    # print self.driver.execute_script('return window.location.href;')

    # Command below always execute successfully which indicates that they get called before 
    # browser has actually changed page.
    self._wait_for_engine_started(self.driver)
    self.driver.execute_script("window.ourNameSpace.engine.refreshAll();")
    
    # 
    # NOTE: This line sometimes randomly cause error: "WebDriverException: Message: window.ourNameSpace is undefined".
    # This happens even the previous line accesses window.ourNameSpace just fine!
    # This makes me believe that the context is flushed randomly between these lines and the 
    # new pages javascript is not executed yet.
    #
    self.driver.execute_script('console.log(window.ourNameSpace.engine);')

    # 
    # NOTE: Or if the line above passes then below line may cause same error.
    #
    WebDriverWait(self.driver, 10).until(
        lambda driver: driver.execute_script('return window.ourNameSpace.engine._getStates();')[0]['state'] == 'passive'
    )

    def _wait_for_engine_started(self, driver):
        WebDriverWait(driver, 10).until(
            lambda driver: driver.execute_script(
                'return window.ourNameSpace && window.ourNameSpace.engine && window.ourNameSpace.engine.isStarted;'
            )
        )


```

**Comment by lukeis** [comment]
what is your 'self.open' function?  Can you provide a website or test pages to reproduce this issue?

Otherwise... this is actually working as expected. The selenium project has thus far failed to solve [the halting problem](https://en.wikipedia.org/wiki/Halting_problem) and as such we can't 100% guarantee a call to driver.get nor element.click will result in the 'next' page being loaded. So your commented out code that waits for the next page to load is actually an appropriate thing to do (also waiting for an element to go stale that was on the previous page is a common solution too.)

Unless you can provide a completely reproducible test script, there's nothing we can do. Also this is highly browser specific and isn't a bug in python at all, rather could potentially be an issue in whatever browser driver you are using.

**Comment by cgoldberg** [comment]
> The selenium project has thus far failed to solve the halting problem

slackers! :)

**Comment by mentholi** [comment]
@lukeis: Thank you for your reply. 

`self.open` was just a shortcut to `driver.get` and I also corrected that to example test case.

I understand that it is impossible to know if for example click to link will actually take the browser to next page or if it is handled by javascript. I also understand that it is not Selenium's task to decide when the page is ready for testing and when page has loaded. 

However I think it should not be possible to call execute_script after calling driver.get and before the page has changed. I think I could provide complete test project but I need to consider if it is worth it. Your proposed workaround is easy enough to implement when you know that this issue exists. it's bad when you don't realise that. :)

**Comment by lukeis** [comment]
understandable that we want that behavior as best as we can get. But simple cases are already covered and yours is certainly an edge case not considered yet. A reproducible script would allow us to look into it further, also knowing what browser you were using too :)

(note that I know that appium against safari iOS does not guarantee the page has even started loading before it returns from the driver.get call... but that is a bug for appium and not here)
