### ISSUE TITLE
[🐛 Bug]: No scroll_from_origin attribute from ActionChains class 

### ISSUE THREAD

**Issue by rena9155** [SeleniumHQ/selenium#13645]
### What happened?

I was trying to use Selenium to scroll part of a webpage by following an example provided here: https://www.selenium.dev/documentation/webdriver/actions_api/wheel/
And then I got an AttributeError: 'ActionChains' object has no attribute 'scroll_from_origin'

### How can we reproduce the issue?

```shell
element = driver.find_element(By.ID,"xxx")
scroll_origin = ScrollOrigin.from_element(element)
ActionChains(driver).scroll_from_origin(scroll_origin, 0, 200).perform()
```

### Relevant log output

```shell
AttributeError: 'ActionChains' object has no attribute 'scroll_from_origin'
```

### Operating System

macOS Ventura

### Selenium version

Python 3.141.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 122.0.6261.94

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 113.0.5672.63

**Comment by diemol** [comment]
The documentation works with Selenium 4, and you need to update your version to use those recent features.
