### ISSUE TITLE
[🐛 Bug]: Scoping Issue When Locating Web Element Within Another Web Element

### ISSUE THREAD

**Issue by Abhisheky55** [SeleniumHQ/selenium#13651]
### What happened?

I have encountered an issue while working with Selenium WebDriver, where I first retrieve a list of web elements. As I iterate through this list, my intention is to find additional, nested web elements within each element of the initial list. However, the process does not work as expected. Instead of identifying unique nested element within each parent element, the method repeatedly identifies and returns the same element—specifically, the one associated with the first parent element in the list.

The core of the problem seems to lie in the scoping mechanism of the WebDriver. When conducting a search from a parent web element to find its child elements, the search should be constrained to the descendants of that specific parent element. This would ensure that each iteration through the parent list results in the identification of child elements unique to each parent. However, the observed behavior indicates a flaw in maintaining this scope. Despite the expectation that the search context changes with each parent element in the iteration, it erroneously maintains the context of the first parent element encountered, leading to repetitive and incorrect outcomes.

This issue suggests a significant bug in how Selenium WebDriver handles element scoping within nested searches. The expected functionality is for each search to be isolated and constrained to the descendants of the current element in the iteration, ensuring that the returned child elements are unique to each parent element in the list. The deviation from this expected behavior indicates a problem with the scoping logic in the WebDriver's implementation, potentially affecting a wide range of automated testing scenarios that rely on precise element hierarchy navigation.

### How can we reproduce the issue?

```shell
Retrieve the list of web elements, for instance, from the product page of the Myntra website, containing meta-information about each product. Then, iterate through the web elements of the list and attempt to fetch an additional web element from each. However, each iteration consistently returns the same element, as there are distinct elements present within the descendants.

public List<WebElement> getAllTShirts() {
        return webDriver.findElements(By.className("product-productMetaInfo"));
    }

public void printDiscountedProducts() {
        List<WebElement> numbers = webDriver.findElements(By.xpath("//li[@class='pagination-number']"));

        List <WebElement> products = getAllTShirts();
        printProductDetails(products);
    }

private void printProductDetails(List<WebElement> discountedProducts) {
        java.util.Iterator<WebElement> program = discountedProducts.iterator();
        while (program.hasNext()) {
            WebElement element = program.next();
            WebElement price = element.findElement(By.xpath("//span[@class='product-discountedPrice']"));
            if (price!=null)
                System.out.println("Price: " + price.getText());
            WebElement discount = element.findElement(By.xpath("//span[@class='product-discountPercentage']"));
            if (price!=null)
                System.out.println("Discount: " + discount.getText());
            WebElement link = element.findElement(By.xpath("//a"));
            if (price!=null)
                System.out.println("Link: " + link.getAttribute("href") + "\n");

        }
    }
```

### Relevant log output

```shell
[1709629645.190][INFO]: Waiting for pending navigations...
[1709629645.190][INFO]: Done waiting for pending navigations. Status: ok
[1709629645.193][INFO]: Waiting for pending navigations...
[1709629645.193][INFO]: Done waiting for pending navigations. Status: ok
[1709629645.193][INFO]: [51c5bbb44b44251ae43ea8980a30474a] RESPONSE GetElementText "Rs. 329"
[1709629645.194][INFO]: [51c5bbb44b44251ae43ea8980a30474a] COMMAND FindChildElement {
   "id": "f.643640E68943467FE8BB86A8B2E394E5.d.60E25EB4BABC7B6CABEF18E99E2C4F4B.e.216",
   "using": "xpath",
   "value": "//span[@class='product-discountPercentage']"
}
[1709629645.194][INFO]: Waiting for pending navigations...
[1709629645.194][INFO]: Done waiting for pending navigations. Status: ok
[1709629645.197][INFO]: Waiting for pending navigations...
[1709629645.197][INFO]: Done waiting for pending navigations. Status: ok
[1709629645.197][INFO]: [51c5bbb44b44251ae43ea8980a30474a] RESPONSE FindChildElement {
   "element-6066-11e4-a52e-4f735466cecf": "f.643640E68943467FE8BB86A8B2E394E5.d.60E25EB4BABC7B6CABEF18E99E2C4F4B.e.218"
}
```

### Operating System

macOS Monterey

### Selenium version

selenium-java 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122

### What are the browser driver(s) and version(s) where you see this issue?

https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.94/mac-arm64/chromedriver-mac-arm64.zip

**Comment by nvborisenko** [comment]
@Abhisheky55 you should use `.//a` rather than `//a` (added `.` symbol) in all your xpath locators to make it scoped.

**Comment by Abhisheky55** [comment]
@nvborisenko  (adding  . symbol) .//a  it is not proper syntax for xapth locator. This will lead to NoSuchElementException

org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//a"}
  (Session info: chrome=122.0.6261.111)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.1', java.version: '17.0.9'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7e5eb29c5b0ea3f65615f778c2b0130a, findChildElement {id=f.38792047DF445A4E4D50832FC8CBFAFD.d.7243C30B39AE6F4B94C4FC540D613B40.e.161, using=xpath, value=.//a}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 122.0.6261.111, chrome: {chromedriverVersion: 122.0.6261.94 (880dbf29479c..., userDataDir: /var/folders/nv/vwk2yvvn5zv...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50658}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:50658/devtoo..., se:cdpVersion: 122.0.6261.111, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7e5eb29c5b0ea3f65615f778c2b0130a

**Comment by nvborisenko** [comment]
@Abhisheky55 and this is absolutely another story? You are getting new behavior... something has been changed. Kind of success?

**Comment by nvborisenko** [comment]
I am closing it. `.//` is a correct xpath syntax if you want to scope search related to a parent. You are getting `NoSuchElementException` error, which means an element, you want to find, is not represented in DOM.

If you think it is still an issue in selenium codebase, please raise new one.
