### ISSUE TITLE
[🚀 Feature]: Selenium Manager - Can delete previous versions of chrome binaries from .cache folder when we have new version of chrome driver

### ISSUE THREAD

**Issue by NagaLakshmiE** [SeleniumHQ/selenium#13657]
### Feature and motivation

Going forward we will be having more chrome new versions and for each there will be a folder created in .cache as below.
![image](https://github.com/SeleniumHQ/selenium/assets/54025551/2f59cb3e-ca84-4d6f-a244-fd276cabc31e)
With this the old version should be deleted when we have a new version of chrome.

### Usage example

We will not have hickup of deleting the previous version downloads this way.

**Comment by diemol** [comment]
This makes sense. We need to find a way to expire the cache.

**Comment by diemol** [comment]
I was unaware Selenium Manager already has a way to expire the cache.

It is either: `--clear-cache` or as an environment variable `SE_CLEAR_CACHE`.

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/selenium_manager/#caching
