### ISSUE TITLE
Actions drag and drop method

### ISSUE THREAD

**Issue by oflores7** [SeleniumHQ/selenium#1365]
org.openqa.selenium.interactions.Actions
When using the above class from the selenium library, the method dragAndDrop(WebElement source, WebElement target) does not work. I have tried executing it multiple times with no luck. Attached is my code to use the drapAndDrop method.
[DragAndDropIssue.txt](https://github.com/SeleniumHQ/selenium/files/58478/DragAndDropIssue.txt)

**Comment by vveliev** [comment]
dragAndDrop 

you may need to run it 2 times , 1st it will focus on the elements second time it will do drag and drop

**Comment by oflores7** [comment]
I did what you instructed, and ran it twice but still no drag and drop action was performed.

**Comment by abdullam** [comment]
having the same problem here. please post the solution here once you find it.

**Comment by tvdberk** [comment]
I've got the same issue here, unable to use the dragAndDrop method nor the clickAndHold + moveToElement + release combination

**Comment by G-JShaw** [comment]
I'm having a similar issue using Selenium.WebDriver v2.53.0 and Firefox v45.0.1 using the C# code below. This is moving Backgrid table columns around. Was working in v2.44.0.

Anyone experiencing something similar?

```csharp
var actionBuilder = new Actions(Browser);
var dragAction = actionBuilder
    .ClickAndHold(columnToDragElement)
    .MoveToElement(dragToColumnElement)
    .Release()
    .Build();
dragAction.Perform();
```

**Comment by matt-romero00** [comment]
I believe that the issue is related to [HTML5](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6315). This is a solution that I found so far: http://elementalselenium.com/tips/39-drag-and-drop

**Comment by lukeis** [comment]
also this is the old original issue logged in google code:

https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3604

**Comment by Mogost** [comment]
Is there any workaround for moving in coordinates, not to the element?

**Comment by llmartinll** [comment]
> Is there any workaround for moving in coordinates, not to the element?

Have you tried triggering the mouseMove command twice? That seems to do the trick for me. Although FirefoxDriver works as aspected so my workaround is issuing the move-command if a non-firefox driver is detected.

var actionBuilder = new Actions(Browser);
var dragAction = actionBuilder
    .ClickAndHold(columnToDragElement)
    .moveByOffset(xOff, yOff)
    .moveByOffset(xOff, yOff)
    .Release()
    .Build();
dragAction.Perform();

**Comment by ffMathy** [comment]
What is the status on implementing this in Selenium?

**Comment by Herst** [comment]
@ffMathy Do you mean Drag and Drop using the HTML5 drag and drop API or Drag and Drop using a particular JS library? In any case, it's hardly something which has to do with Selenium (the WebDriver client) but rather the browsers interacted with (or in the case of HTML5 DnD the WebDriver protocol standard).

**Comment by jasonex7** [comment]
> Have you tried triggering the mouseMove command twice? That seems to do the trick for me. 
The same works for me on Chrome 77. Thanks!

**Comment by Wonderio619** [comment]
@jasonex7 @llmartinll 
I tried may be all solutions discovered, including yours, but for me drag and drop works only if I move mouse during auto-test execution )
Chrome 76

**Comment by llmartinll** [comment]
@Wonderio619 What are you trying to do, and what do you mean by 'auto-test execution'? 

I think I remember a couple of months ago something got changed/fixed so you don't have to issue the move command, however, looking at my own code it seems the drag and drop by offset might stil cause problems for chrome.

Can you try if something like this works for you?
```
var actionBuilder = new Actions(Browser);
var dragAction = actionBuilder
    .ClickAndHold(columnToDragElement)
    .moveByOffset(10, 0)
    .moveByOffset(-10, 0)
    .moveByOffset(xOff, yOff)
    .Release()
    .Build();
dragAction.Perform();
```

**Comment by Wonderio619** [comment]
@llmartinll 
I'm trying to drag n drop element on another element, and only if I physically moving mouse during drag n drop part, only then this drag n drop code works
With your code I have "move target out of bounds" exception

str```
ing selector = AttachmentPageSelector.Replace("NUMBER", pageId);
                var currentPageElement = WebBrowser.WebDriver.FindElement(By.XPath(selector));
                int xOff = LinkedPagesContainer.Element.Location.X;
                int yOff = LinkedPagesContainer.Element.Location.Y;
                var dragAction = actions.ClickAndHold(currentPageElement).MoveByOffset(10, 0).MoveByOffset(-10, 0).MoveByOffset(xOff, yOff).Release().Build();
                dragAction.Perform();
```

**Comment by llmartinll** [comment]
You are using the destination's X,Y coordinates as an offset, that won't work. You would need the difference between the currentPageElement and the targetElement. But, I would use the `.MoveToElement` functionality. And maybe trigger it twice.
I think you're having 'general' issues getting your code to work. Maybe I'm wrong, but it seems more like a stackoverflow question and less like a 'selenium doesn't work as expected question'.

**Comment by Wonderio619** [comment]
@llmartinll 
"You would need the difference between the currentPageElement and the targetElement"
Can you please advice how can I calculate or get this difference ?

**Comment by Naumansh** [comment]
Is there any fix to this issue? The drag and drop does not work both on chrome and firefox. i have tried all suggested solutions but nothing works.

**Comment by glundgren93** [comment]
Any news? 😢🤞

**Comment by diemol** [comment]
Apologies for the late reply.

I tried to reproduce the original issue and I got the code to work. I pushed the code to this repository in case someone wants to have a look: https://github.com/diemol/selenium-issues/blob/master/selenium/issue-1365/src/test/java/DragAndDropActions.java

Here is the code running:
![issue-1365](https://user-images.githubusercontent.com/5992658/85908183-60233c00-b814-11ea-8be5-1c134486b554.gif)

I also saw that the issue has several comments reporting other different issues. Therefore, if you are still having an issue with the most recent version of Selenium and/or the Selenium 4 Alphas, please create a new issue and provide all the required information.
