### ISSUE TITLE
[🐛 Bug]: Cache Folder isn't Updated by Environmental Variable

### ISSUE THREAD

**Issue by PulseBeat02** [SeleniumHQ/selenium#13658]
### What happened?

This is related to my previous issue [here](https://github.com/SeleniumHQ/selenium/issues/12774), where I got a `[WARN] [org.openqa.selenium.manager.SeleniumManager] Cache folder (/.cache/selenium) cannot be created: Read-only file system (os error 30)` error. The strange issue is that even after specifying the environmental variable, it doesn't seem to function as intended either, and I still receive the same error.

In my code, I set the `SE_CACHE_PATH` environmental variable at runtime by using `Unsafe` to modify the `System.env()` map as seen [here](https://github.com/PulseBeat02/Neon/blob/e1d92b31d17e3166239294b384d0314605fddd0a/neon/src/main/java/io/github/pulsebeat02/neon/browser/SeleniumBrowser.java#L83). Upon testing this `Unsafe` method, I made sure that the variable is added, and it does get added. In fact, the `SeleniumManager` class does manage to read the updated variable at this specific [line](https://github.com/SeleniumHQ/selenium/blob/b9a95a32a2897b3d939ec96e6083ef3b812f75e6/java/src/org/openqa/selenium/manager/SeleniumManager.java#L326) here. The external Selenium Manager program is installed into the new cache directory I set, but the program itself doesn't catch these environmental variables for some reason, causing it to default to `/.cache/selenium` for some odd reason. Digging deeper, I noticed that that the execution uses `ProcessBuilder`, which copies all the environmental variables of the current environment to the external process environment, so it shouldn't be an issue.

I've tried setting other variables like `SE_DEBUG` or `SE_OUTPUT`, but they don't work either. I even tried creating a configuration file `se-config.toml` that reflects these values, which isn't read either for some reason. I'm not entirely sure what causes this issue.

On a separate note, it would be useful for developers to allow the `Capabilities` class have a cache path, or other arguments that developers may want to use for Selenium Manager. It's hard to change environmental variables at runtime and it's easier and more intuitive to just modify the `ProcessBuilder` environment instead.

### How can we reproduce the issue?

```shell
1) Host a file system with limited permissions to modify the original cache folder.
2) At Java runtime, set the environmental variable of `SE_CACHE_PATH` to a different path.
3) Run the Selenium Manager installation class that downloads the external program and runs it.
4) The Selenium Manager external program ends up being installed in the `SE_CACHE_PATH` you specified, but chromium itself isn't installed there and throws a `Read-only file system (os error 30)` error.
```

### Relevant log output

```shell
I'm not able to get any log output as I can't specify any environmental variables or values in `se-config.toml` that can change the program. This includes logging output of Selenium Manager.
```

### Operating System

Ubuntu

### Selenium version

Java 4.18.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
In Java, you need to set the env var outside the code. Unfortunately, Java does not provide a good way to do that.

**Comment by PulseBeat02** [comment]
That's not the issue however. I did set the environment variable but selenium manager isn't catching the variable for some reason.

**Comment by diemol** [comment]
Most likely the env var does not persist. Which is why you should set it outside of the Java process, or in the Selenium Manager config file.
