### ISSUE TITLE
[🐛 Bug]: New version 'chrome-4.18.1-20240224-automaticDownloads' is blocking the download of files

### ISSUE THREAD

**Issue by victoria-iriusrisk** [SeleniumHQ/selenium#13652]
### What happened?

With the latest version `chrome-4.18.1-20240224-automaticDownloads`, if you try to download a file with a TestCafe test, the chrome browser is blocking the automatic download of files.
![image](https://github.com/SeleniumHQ/selenium/assets/135114059/b0b9994a-34f0-4bfa-9ce8-cf0cb0689e9c)

### How can we reproduce the issue?

Create a test with TestCafe framework to download a file (i.e. a xml file).
Execute test with `chrome-4.18.1-20240224-automaticDownloads` browser.

### Relevant log output

Chrome is blocking the automatic download of files with the following message on 'Downloads' Chrome tab: 'This file can't be downloaded securely'.
With the previous version '4.18.0-20240220' the automatic download is working without blocking the download of files.
Also, if you try to the following options on `capabilities.json` file, the download is not working:
```
 "chrome": {
    "chromeOptions": {
      "args": [
        "--enable-features=EnableManagedDownloads"
      ]
    }
```
Or
```
 "chrome": {
    "goog:chromeOptions": {
      "args": ["--disable-web-security"]
    }
  }
```
Also, if you try to set up secure domains, the browser is always up with this option disable.

### Operating System

Ubuntu

### Selenium version

Selenium 4.18.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

node-chrome-4.18.1-20240224-automaticDownloads

### Are you using Selenium Grid?

Yes

**Comment by diemol** [comment]
We do not publish any image with a `-automaticDownloads` tag. 

If you are looking for managed downloads in Grid, this should help https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node.

**Comment by jhernandez-iriusrisk** [comment]
Hi @diemol, 
Please, take a look at some information below.
`-automaticDownloads` tag is our internal tag, no worries, there are no changes.
We tried using your instructions, but we faced the same issue:
- We triggered the docker (node-chrome:4.18.1) with these settings:
- - SE_OPTS=--enable-managed-downloads true
- We execute the test with chrome options ("se:downloadsEnabled": true)
Could you help with this?? The same test works properly with 4.18.0 or earlier

![image](https://github.com/SeleniumHQ/selenium/assets/117631552/5fe35ae7-c65f-4000-8bc3-9a4a4be433dc)

**Comment by diemol** [comment]
That is a Chrome feature itself, not something Selenium control. There is probably a flag to disable it. 4.18.1 has Chrome 122, 4.18.0 has Chrome 121.

**Comment by ccea-dev-team** [comment]
There are a few issues with downloads blocked and password data breach popups in chromedriver v122 causing test failures and it's not clear what prefs need set.  https://bugs.chromium.org/p/chromedriver/issues/detail?id=4730&sort=-id https://bugs.chromium.org/p/chromedriver/issues/detail?id=4731&sort=-id
