### ISSUE TITLE
[🐛 Bug]: (with FIX) Selenium leaks memory by creating thousands of small zombie processes

### ISSUE THREAD

**Issue by IzydorDPS** [SeleniumHQ/selenium#13656]
### What happened?

Hi,
for a long time, I have battled memory leak in my software and I finally found a fix.
### Software quick desc:
for many hours my software opens chromeDriver do sth and close it (driver.quit())
that's translates to hundreds of chromeDriver instances (max 20 concurrent) created and closed during end of day.

### Problem:
Software/OS crash due to exhaust of machine(64gb ram) memory.

Stopping and executing command like bellow does nothing because still memory usage is about 90%
```cmd
taskkill /F /IM chrome.exe
taskkill /F /IM chromedriver.exe
```
task manager shows nothing that could indicate what eats all memory, shows just IntelliJ and windows standard bg processes, 
memory column don't sum up to 90%
It's clean Windows install.
No memory cleaning software helps 
only machine restart helps.

### Discovery of error:
Windows tool [RAMMAP.exe](https://learn.microsoft.com/pl-pl/sysinternals/downloads/rammap) shows thousands of zombie processes that are not in task manager and user in unable to interact with them, for example to execute **taskkill /F /PID <PID>**
because process will not be found
![image](https://github.com/SeleniumHQ/selenium/assets/35769682/45d1292f-efae-4ee7-931c-5afee3cc4567)

### FIX:
[FindZombieHandles](https://github.com/randomascii/blogstuff/tree/main/FindZombieHandles) search for zombie processes and reports which process keeps them alive
![image](https://github.com/SeleniumHQ/selenium/assets/35769682/4f011598-fa4d-4d9e-b7b4-283982835851)

after killing that **svchost.exe** by its PID (253912) all ram gets released 🎉🎉🎉🎉🎉

Could that issue be fixed in Selenium library, or maybe is there something I can do to fix it?
My code should be fine as I don't see any stranded chrome processes, everything is closed by quit(); and temp folder don't overflow my drive
All I can think of is to write some script that automates that FIX, executing it every hour or so.

### How can we reproduce the issue?

```shell
for many hours my software opens chromeDriver do sth and close it (driver.quit())
that's translates to hundreds of chromeDriver instances (max 20 concurrent) created and closed during end of day.
```

### Relevant log output

```shell
task manager shows nothing that could indicate what eats all memory, shows just IntelliJ and windows standard bg processes,
memory column don't sum up to 90%
```

### Operating System

Windows 11

### Selenium version

java 21/ Selenium 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 122.0.6261.94

**Comment by diemol** [comment]
`driver.quit()` should have as a result a driver and browser stopped. Does this happen with Firefox? In any case, we need a way to reproduce this using the latest Selenium version.

**Comment by joerg1985** [comment]
I have the same issue here and a different way to detect and kill the zombies with Java:
 1. get all ProcessHandle instances: `ProcessHandle.allProcesses()`
 2. filter `ProcessHandle.info().command()` ends with `/chrome.exe`
 3. filter `ProcessHandle.parent()` is empty
 4. call `ProcessHandle.destroyForcibly` for all matching 


But i could not find a way to reproduce the issue ...

**Comment by nvborisenko** [comment]
The issue is reproducible for Chrome/Edge, not reproducible for Firefox. I removed `--no-sandbox` browser argument, and now I don't see zombie processes.
