### ISSUE TITLE
[🐛 Bug]: I am unable to use all the new bidirectional features. getBidi throwing error

### ISSUE THREAD

**Issue by Omoalfa** [SeleniumHQ/selenium#13666]
### What happened?

when I try using the logInspector as refrenced in the documentation [here](https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk//examples/javascript/test/bidirectional/logInspector.spec.js#L23-37) 

I keep getting this an error something related to cannot read property of undefined (reading 'replace')

while trying to make sense of the same error when i run driver.getBidi() function too.

### How can we reproduce the issue?

```shell
const inspector = await LogInspector(this.driver);

      await inspector.onLog(log => {
        console.log("JS Console log:", log);
      })

just try running this:
```

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'replace')
   at Driver.getBidi (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:1260:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LogInspector.init (/usr/src/app/node_modules/selenium-webdriver/bidi/logInspector.js:41:17)
   at getLogInspectorInstance (/usr/src/app/node_modules/selenium-webdriver/bidi/logInspector.js:259:3)
```

### Operating System

Ubuntu

### Selenium version

4.12.0 and 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Firefox Beta, Chrome 114

### What are the browser driver(s) and version(s) where you see this issue?

not sure, I am using the selenium docker browser nodes

### Are you using Selenium Grid?

latest

**Comment by diemol** [comment]
Can you try using the latest Selenium and Chrome/Firefox? Probably those features were not implemented in the versions you are using.

**Comment by Omoalfa** [comment]
> Can you try using the latest Selenium and Chrome/Firefox? Probably those features were not implemented in the versions you are using.

I did updated all of my packages include the selenium-webdriver npm packages

**Comment by diemol** [comment]
What about the browser versions? Are you using Chrome 122 and Firefox 123?

**Comment by Omoalfa** [comment]
> What about the browser versions? Are you using Chrome 122 and Firefox 123?

I just did and the error is the same

**Comment by diemol** [comment]
I am not sure how to triage this as it is working for me locally, plus our CI with that example is passing: https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/8195812613.

Can you clone the repository and run the examples? https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/javascript/README.md

**Comment by Omoalfa** [comment]
> I am not sure how to triage this as it is working for me locally, plus our CI with that example is passing: https://github.com/SeleniumHQ/seleniumhq.github.io/actions/runs/8195812613.
> 
> Can you clone the repository and run the examples? https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/javascript/README.md

I am getting this error from the examples, 
`Uncaught Error: connect ECONNREFUSED 127.0.0.1:25324`

**NOTE**
I am using a selenium grid I am running locally using docker and I am using the latest tag for the selenium hub container as a result I had to add this line to all instance of driver initiation in the test files:
`.usingServer("http://localhost:4444/wd/hub")`

**Comment by diemol** [comment]
That is an important detail you missed sharing. Check https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#grid-url-and-session-timeout.

**Comment by Omoalfa** [comment]
but I did mentioned I was using selenium grid in the first instance of creating the issue. I even stated this `I am using the selenium docker browser nodes` as the response regarding the which driver I was using.

**Comment by diemol** [comment]
You are right, my apologies.

**Comment by Omoalfa** [comment]
> That is an important detail you missed sharing. Check https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#grid-url-and-session-timeout.

setting this environment variable didn't solve the problem though

**Comment by diemol** [comment]
How are you starting the Grid?

**Comment by Omoalfa** [comment]
docker-compose:

`
version: '3'

networks:
  grid_network:
    name: grid_network

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - grid_network
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - HUB_SERVER=http://selenium-hub:4444
      - BACKEND_SERVER=${BACKEND_SERVER}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIS_SERVER=redis://cache:6379 
    depends_on:
      - selenium-hub
      - cache
    dns:
      - 8.8.8.8
    volumes:
      - shared_data:/usr/src/app/src/cloud-runner/services/files

  chrome:
    image: selenium/node-chrome:122.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - web
    networks:
      - grid_network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes_from:
      - web:ro

  edge:
    image: selenium/node-edge:beta
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - web
    networks:
      - grid_network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
    volumes_from:
      - web:ro

  firefox:
    image: selenium/node-firefox:123.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - web
    networks:
      - grid_network
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_SESSION_REQUEST_TIMEOUT=10
    volumes_from:
      - web:ro

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - grid_network
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  cache:
    image: redis:latest
    restart: always
    networks:
      - grid_network
    ports:
      - "6380:6380"

volumes:
  shared_data:
    name: shared_data
`

**Comment by diemol** [comment]
`SE_NODE_GRID_URL=http://selenium-hub:4444/` needs to be the URL you use to reach the Grid from your tests.

**Comment by Omoalfa** [comment]
> `SE_NODE_GRID_URL=http://selenium-hub:4444/` needs to be the URL you use to reach the Grid from your tests.

that exactly is what I am using. check the environment variables configured in the web service there is this line `- HUB_SERVER=http://selenium-hub:4444/` in it.

**Comment by diemol** [comment]
You said above you are using `localhost:4444`
>.usingServer("http://localhost:4444/wd/hub")

**Comment by Omoalfa** [comment]
that is when I test with the official test examples you shared earlier because that is not inside my docker compose network hence it doesn't have access to that "selenium-hub" host name which docker compose resolves automatically inside my web service because it is also inside the docker network

**Comment by diemol** [comment]
Where are your tests running? Inside a Docker container that runs in that Docker network?

**Comment by Omoalfa** [comment]
yes

**Comment by diemol** [comment]
Which container? I do not see it in the compose file you shared.

Can you share all Grid logs as well?

**Comment by Omoalfa** [comment]
the thing is I have two tests I am running:

1. My actual test run
this is running inside the docker network and uses the docker container name as the hub server value i.e. http://selenium-hub:4444/wd/hub

2. The official test examples
this is the repo you shared with me which I am running locally (not inside any docker container) and this is the one I am using localhost to run

> Both cases are giving the same error by the way.

as regard the complete grid logs here it is:

14:08:10.932 INFO [Node.<init>] - Binding additional locator mechanisms: relative
14:08:11.167 INFO [GridModel.setAvailability] - Switching Node d3ffdcd2-a917-4bc5-837f-ff7a4605775a (uri: http://172.21.0.7:5555) from DOWN to UP
14:08:11.167 INFO [LocalDistributor.add] - Added node d3ffdcd2-a917-4bc5-837f-ff7a4605775a at http://172.21.0.7:5555. Health check every 120s
14:08:11.172 INFO [Node.<init>] - Binding additional locator mechanisms: relative
14:08:11.383 INFO [GridModel.setAvailability] - Switching Node c20bd9d0-b8a1-414e-9b89-1263f26dcec3 (uri: http://172.21.0.6:5555) from DOWN to UP
14:08:11.383 INFO [LocalDistributor.add] - Added node c20bd9d0-b8a1-414e-9b89-1263f26dcec3 at http://172.21.0.6:5555. Health check every 120s
14:08:21.069 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: firefox, goog:loggingPrefs: {browser: ALL}, webSocketUrl: true}]
14:08:24.970 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 78993a30-021d-45c8-9814-ad7112acab86 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 123.0, goog:loggingPrefs: {browser: ALL}, moz:accessibilityChecks: false, moz:buildID: 20240213221259, moz:debuggerAddress: 127.0.0.1:29494, moz:geckodriverVersion: 0.34.0, moz:headless: false, moz:platformVersion: 6.5.0-14-generic, moz:processID: 165, moz:profile: /tmp/rust_mozprofileXb51WQ, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:bidi: ws://selenium-hub:4444/sess..., se:cdp: ws://selenium-hub:4444/sess..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://selenium-hub:4444/sess..., se:vncEnabled: true, se:vncLocalAddress: ws://172.21.0.7:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://127.0.0.1:29494/sessio...}

**Comment by diemol** [comment]
You would need to run them both from the same place.

**Comment by frankie-frank-frank** [comment]
The issue has been closed without a solution. I am running LogInspector normally and still face the same issues.

    const inspector = await LogInspector(driver)
    await inspector.init()
    await inspector.onConsoleEntry(function (log) {
       console.log('javascript console log: ', log)
    })
