### ISSUE TITLE
[🐛 Bug]: When doing automated testing with node.js, using pkg to package exe will cause ""Error: Failed to import atoms module get-attribute.js.

### ISSUE THREAD

**Issue by Skylar0628** [SeleniumHQ/selenium#13665]
### What happened?

[🐛 Bug]: When doing automated testing with node.js, using pkg to package exe will cause ""Error: Failed to import atoms module get-attribute.js.

### How can we reproduce the issue?

```shell
Error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run 'bazel build' //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js from the projectroot: Error: Cannot find moule './atoms/get-attribute.js'
```

### Relevant log output

```shell
Error: Failed to import atoms module get-attribute.js. If running in dev mode, you need to run 'bazel build' //javascript/node/selenium-webdriver/lib/atoms:get-attribute.js from the projectroot: Error: Cannot find moule './atoms/get-attribute.js'
```

### Operating System

win11

### Selenium version

javascript

### What are the browser(s) and version(s) where you see this issue?

版本 122.0.6261.111 (正式版本) (64 位元)

### What are the browser driver(s) and version(s) where you see this issue?

版本 122.0.6261.111 (正式版本) (64 位元)

### Are you using Selenium Grid?

^4.18.1

**Comment by diemol** [comment]
I will close this as we have yet to get more information.
