### ISSUE TITLE
[🚀 Feature]:    Provide some prompt information when downloading a new chromeDriver

### ISSUE THREAD

**Issue by shengrihui** [SeleniumHQ/selenium#13689]
### Feature and motivation

When downloading a new ChromeDriver, I hope you can provide some prompt information. Otherwise, if there is no message prompt due to network issues, I don't know what happened.

### Usage example

I am using Python and Chrome, and when running Selenium, I hope that the terminal can prompt me that it is downloading a new ChromeDriver

**Comment by diemol** [comment]
You can set a different log level to see all details https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

If you are running Selenium Manager itself, you can configure the log level https://www.selenium.dev/documentation/selenium_manager/#configuration
