### ISSUE TITLE
IDE records selectWindow instead of selectFrame

### ISSUE THREAD

**Issue by Laerten** [SeleniumHQ/selenium#1368]
When I click on a field in a iFrame and then click elsewhere, Selenium IDE records `selectWindow` command in all cases instead of `selectFrame`.

In the editor.js file (`addCommand` function) the `LastWindow.prototype.isSameTopWindow` method currently returns false whenever the current window is not the top window, even if the two frames are under the same top window.

``` javascript
Editor.prototype.addCommand = function (command, target, value, window, insertBeforeLastCommand) {
   [...]
   if (!this.safeLastWindow.isSameWindow(window)) {
      if (this.safeLastWindow.isSameTopWindow(window)) {
        // frame
         [...]
      } else {
        // popup
         [...]
      }
   }
   [...]
}

LastWindow.prototype.isSameTopWindow = function (window) {
  if (this.window == null || window == null) {
    return false;
  }
  if (this.isTopLevel && window.top == window.top.parent) {
    // top level window
    return this.topName == window.top.name;
  } else if (this.parent == window.parent) {
                return this.window.top === window;
  }
  return false;
};
```

**Comment by samitbadle** [comment]
Thanks Laerten, I will look into it.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
