### ISSUE TITLE
[🐛 Bug]: [Selenium Grid 4] I'm unable to distribute my script to all registered nodes

### ISSUE THREAD

**Issue by phatle1** [SeleniumHQ/selenium#13690]
### What happened?

Let's say I'm already finished my configuration for selenium grid 4 as below:
appium1.yml
```
server:
  port: 4723
  keep-alive-timeout: 80
  session-override: true
  use-drivers:
    - uiautomator2
```

appium2.yml
```
server:
  port: 4724
  keep-alive-timeout: 80
  session-override: true
  use-drivers:
    - uiautomator2
```

node1.toml (for android emulator)
```
[server]
port = 5559

[node]
detect-drivers = false
override-max-sessions = true
max-sessions = 3

[relay]
url = "http://127.0.0.1:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\",\"appium:deviceName\": \"emulator-5554\", \"appium:automationName\": \"UiAutomator2\"}"
]
```

node2.toml(for android real device)
```
[server]
port = 5561

[node]
detect-drivers = false
override-max-sessions = true
max-sessions = 3

[relay]
url = "http://127.0.0.1:4724"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\",\"appium:deviceName\": \"l769lfxc8d\", \"appium:automationName\": \"UiAutomator2\"}"
]
```
hub
```
java -jar path-to-jar hub
```

here is my conftest.py
```
@pytest.fixture(scope="function")
def appium_driver(request):
    service_device = AppiumService()
    # service_device.start(args=['-p', '4723', '--base-path', '/', '--session-override'])

    parent_path = Path(__file__).resolve().parents[1]
    config_path = f'{parent_path}/configuration_data/devices_config.json'
    device_caps: dict[str, any] = config_reader.load_devices_config(config_path)

    device = device_caps['device_caps']['device1']
    url = 'http://127.0.0.1:4444'
    logger.info(f"appPackage :{device['appium:appPackage']}")
    logger.info(f"device_id  :{device['appium:deviceName']} ")
    driver = webdriver.Remote(command_executor=url, options=AppiumOptions().load_capabilities(device))
    request.cls.driver = driver
    driver.implicitly_wait(5)
    yield driver
    driver.quit()
    service_device.stop()
```

after run all config files
![Screenshot 2024-03-14 at 16 01 39](https://github.com/SeleniumHQ/selenium/assets/48046252/2b4d12e0-3b02-48a3-8ba2-122e80358a4b)

and after running the script, I see that the script is distributed to 1 node only.
![Screenshot 2024-03-14 at 16 03 29](https://github.com/SeleniumHQ/selenium/assets/48046252/89f4f9cf-7d73-4d4b-b658-44efc55db9d4)

I expect that I can run the script on all nodes at the same time(parallel)

Appreciate for your help here

### How can we reproduce the issue?

```shell
run 2 nodes and hub as mentioned above

run pytest

```

### Relevant log output

```shell
I didn't receive any error log so far
```

### Operating System

Mac OS 14.0 (23A344)

### Selenium version

Selenium 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Appium android

### What are the browser driver(s) and version(s) where you see this issue?

Appium android

### Are you using Selenium Grid?

4.18.1

**Comment by diemol** [comment]
I am going to close this because we never got an answer.
