### ISSUE TITLE
[🐛 Bug]: popover attribute is not handled

### ISSUE THREAD

**Issue by toy** [SeleniumHQ/selenium#13700]
### What happened?

I was testing using capybara interaction with buttons that are in an element with [popover attribute](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API) which is inside an element with overflow hidden. Capybara doesn't handle visibility of elements inside an element with popover attribute, but after fixing that I am getting `Selenium::WebDriver::Error::ElementNotInteractableError`.

Related issue: https://github.com/teamcapybara/capybara/issues/2755

### How can we reproduce the issue?

HTML to show the problem:

```html
<div style="position: relative; overflow: hidden;">
  <button popovertarget="show">Show popover</button>
  <button style="position: absolute; top: 30px;">Can not be clicked</button>
  <button popover id="show" style="position: absolute; top: 60px;">Should be clickable</button>
</div>
```

After clicking the «Show popover»:
![image](https://github.com/teamcapybara/capybara/assets/18144/054ed283-ab52-4777-b79e-393d6d1525d0)

It should not be possible to click the «Can not be clicked» button, but it should be possible to click the «Should be clickable» button.

### Relevant log output

```shell
Selenium::WebDriver::Error::ElementNotInteractableError:
       element not interactable
         (Session info: chrome-headless-shell=121.0.6167.85)
     # 0   chromedriver                        0x0000000104d1e814 chromedriver + 4040724
     # 1   chromedriver                        0x0000000104d16a18 chromedriver + 4008472
     # 2   chromedriver                        0x00000001049896a8 chromedriver + 284328
     # 3   chromedriver                        0x00000001049ce330 chromedriver + 566064
     # 4   chromedriver                        0x00000001049c34b8 chromedriver + 521400
     # 5   chromedriver                        0x00000001049c2ee8 chromedriver + 519912
     # 6   chromedriver                        0x0000000104a07048 chromedriver + 798792
     # 7   chromedriver                        0x00000001049c174c chromedriver + 513868
     # 8   chromedriver                        0x00000001049c2044 chromedriver + 516164
     # 9   chromedriver                        0x0000000104ce3a3c chromedriver + 3799612
     # 10  chromedriver                        0x0000000104ce7f1c chromedriver + 3817244
     # 11  chromedriver                        0x0000000104ccc298 chromedriver + 3703448
     # 12  chromedriver                        0x0000000104ce8a64 chromedriver + 3820132
     # 13  chromedriver                        0x0000000104cbf054 chromedriver + 3649620
     # 14  chromedriver                        0x0000000104d05e74 chromedriver + 3939956
     # 15  chromedriver                        0x0000000104d05fec chromedriver + 3940332
     # 16  chromedriver                        0x0000000104d16698 chromedriver + 4007576
     # 17  libsystem_pthread.dylib             0x0000000182092034 _pthread_start + 136
     # 18  libsystem_pthread.dylib             0x000000018208ce3c thread_start + 8
```

### Operating System

macOS Sonoma

### Selenium version

selenium-webdriver 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 121.0.6167.85

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121.0.6167.184 (057a8ae7deb3374d0f1b04b36304d236f0136188-refs/branch-heads/6167@{#1818})

**Comment by titusfortner** [comment]
Visibility is typically managed by Selenium, though Capybara has an optimized version that it maintains independently.
interactibiity, though, is managed by chromedriver, not by Selenium.

You might also try `--headless=new`, since it is possible it works with Chrome, but not chrome-headless-shell

**Comment by toy** [comment]
@titusfortner Thank you for looking into the issue. I have checked that it is there also for Chrome and not only for headless browser
