### ISSUE TITLE
[🐛 Bug]: driver.quit() and driver.close() are both throwing errors NoSuchSession: Invalid session id

### ISSUE THREAD

**Issue by Omoalfa** [SeleniumHQ/selenium#13703]
### What happened?

I have a testRunner class in that I use to manage my test runs... the problem occurs inside the run method which is in the format:

run = async () => {
 try {
   /// the tests is run in here
  } catch (e) {
  // I catch error inside here
  } finally {
    await this.driver.quit() //quitting the selenium browser...
  }
}

note: the this.driver is initialized insde another function before the run method is called.

I have two entry points to run this tests:
1. api route: so I call the testRunner from inside an api request - everything works well here.
2. cli route: I call the testRunner using a cli tool I create - and this is where the error occurs

if I should remove the line (await this.driver.quit()) everything seems to be fine but the problem is the session never closes hence it is difficult to run a new testcase.

### How can we reproduce the issue?

```shell
run = async () => {
 try {
   /// the tests is run in here
  } catch (e) {
  // I catch error inside here
  } finally {
    await this.driver.quit() //quitting the selenium browser...
  }
}
```

### Relevant log output

```shell
/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/error.js:521
    let err = new ctor(data.message)
              ^

NoSuchSessionError: invalid session id
    at Object.throwDecodedError (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/error.js:521:15)
    at parseHttpResponse (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/http.js:510:13)
    at Executor.execute (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/http.js:443:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WebDriver.execute (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/webdriver.js:740:17)
    at async Select.isMultiple (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/select.js:296:13)
    at async Select.selectByValue (/home/omoalfa/Desktop/Omoalfa/Node/cloud-runner/node_modules/selenium-webdriver/lib/select.js:217:19) {
  remoteStacktrace: '#0 0x557394a22ad3 <unknown>\n' +
    '#1 0x5573946e0c15 <unknown>\n' +
    '#2 0x5573947188a1 <unknown>\n' +
    '#3 0x557394719cbe <unknown>\n' +
    '#4 0x5573949f426f <unknown>\n' +
    '#5 0x5573949f7477 <unknown>\n' +
    '#6 0x5573949f6efb <unknown>\n' +
    '#7 0x5573949f7965 <unknown>\n' +
    '#8 0x5573949e64bb <unknown>\n' +
    '#9 0x5573949f7d68 <unknown>\n' +
    '#10 0x5573949d2d65 <unknown>\n' +
    '#11 0x557394a12498 <unknown>\n' +
    '#12 0x557394a1261f <unknown>\n' +
    '#13 0x557394a21326 <unknown>\n' +
    '#14 0x7f7f616e2ac3 <unknown>\n'
}
```

### Operating System

Ubuntu

### Selenium version

4.12.0 and 4.18.1

### What are the browser(s) and version(s) where you see this issue?

Firefox latest, chrome latest

### What are the browser driver(s) and version(s) where you see this issue?

not sure, I am using the selenium docker browser nodes

### Are you using Selenium Grid?

latest

**Comment by diemol** [comment]
>NoSuchSessionError: invalid session id
This means the session has already been closed. 

Could you check how those async tasks are working together?

**Comment by diemol** [comment]
I am closing this because we never got more information.
