### ISSUE TITLE
Selenium PhantomJS/Firefox https proxy not working(Python)

### ISSUE THREAD

**Issue by Mortix15** [SeleniumHQ/selenium#1371]
i'm trying to setup selenium driver to work with proxy that requires authentication. i managed to set it with PhantomJS and selenium:
service_args = [
    '--proxy=https://IP:PORT',
    '--proxy-type=http',
    '--proxy-auth=USERNAME:PASSWORD',
    '--ssl-protocol=any',
    '--ignore-ssl-errors=true'
    ]
br = webdriver.PhantomJS(PATH,service_args=service_args)
br.get('https://www.gmail.com/')

it worked fine, the issue https not working(yes the proxy support https)

UPDATE: the problem is only with https://www.gmail.com , might be some redirect issue?

Firefox issue:
can't authenticate to the proxy automatically, http://username:password@ip not working,
alert = driver.switch_to_alert()
alert.send_keys('balbla')
not working as well.

i must find a solution to run one of the drivers with authenticated proxy and ssl.
** Python

**Comment by hello-world-wanghui** [comment]
Hello, I have the same problem. Have you solved it
