### ISSUE TITLE
Selenium PhantomJS https redirect with proxy(Python)

### ISSUE THREAD

**Issue by Mortix15** [SeleniumHQ/selenium#1372]
ok so after few days of trying everything i figured the problem,
phantomjs and selenium isn't redirecting https://www.gmail.com when using proxy.

code:
service_args = [
    '--proxy=https://IP:PORT',
    '--proxy-type=http',
    '--proxy-auth=USERNAME:PASSWORD',
    '--ssl-protocol=any',
    '--ignore-ssl-errors=true'
    ]
br = webdriver.PhantomJS(PATH,service_args=service_args)
br.get('https://www.gmail.com/')

i get empty page,
br.current_url return about:blank

br.get('https://www.google.com') or any other https site working fine.

**Comment by barancev** [comment]
Please report this issue to the PhantomJS driver tracker:
https://github.com/detro/ghostdriver
