### ISSUE TITLE
[🐛 Bug]: Webdriver get can not navigate to  local site being served by Bokeh http://localhost:56275

### ISSUE THREAD

**Issue by jj-github-jj** [SeleniumHQ/selenium#13721]
### What happened?

The bowser opens and webdriver can navigate to any sites like www.google.com just fine but hangs in a forever wait with
driver.get ('http://localhost:56275') . Copy paste this URL in the browser window and browser reponds correctly and displays the web page- only if driver.get is used to navigate to the page, the browser goes into end less wait .

### How can we reproduce the issue?

```shell
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
time.sleep(2)
url1='http://www.google.com'
url2='http://localhost:56275' # this is generated by a script pasted later 
driver.set_script_timeout(20)
 
driver.get(url1) # this will work just fine
time.sleep(1)
driver.get(url2) # this will cause browser to wait endlessly until a stop is hit 

#-----------------
# script that generates the localhost page
import panel as pn
pn.extension()

# Show the Panel in the browser
bokeh_server = pn.pane.Markdown('## Hello, World!').show()
# this will start a server and show you the local host port to use - port changes every time
# so you have to use the port printed out in the localhost:port_number
```

### Relevant log output

```shell
Started executable: `C:\Users\user\.wdm\drivers\chromedriver\win64\123.0.6312.58\chromedriver-win32/chromedriver.exe` in a child process with pid: 10476 using 0 to output -3
POST http://localhost:63236/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'goog:chromeOptions': {'extensions': [], 'args': []}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"123.0.6312.58","chrome":{"chromedriverVersion":"123.0.6312.58 (6b4b19e9dfbb93aa414dc045bd445287977d8d7a-refs/branch-heads/6312_46@{#3})","userDataDir":"C:\\Users\\user\\AppData\\Local\\Temp\\scoped_dir10476_1885155778"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:63242"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"3b455b00ebb33c9f4ba86c8f20b1506c"}} | headers=HTTPHeaderDict({'Content-Length': '883', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63236/session/3b455b00ebb33c9f4ba86c8f20b1506c/timeouts {'script': 20000}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63236/session/3b455b00ebb33c9f4ba86c8f20b1506c/url {'url': 'http://www.google.com'}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63236/session/3b455b00ebb33c9f4ba86c8f20b1506c/url {'url': 'http://localhost:56275'}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
```

### Operating System

 windows 10

### Selenium version

4.17.2

### What are the browser(s) and version(s) where you see this issue?

tried ms edge and chrom

### What are the browser driver(s) and version(s) where you see this issue?

using  driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

**Comment by diemol** [comment]
I cannot replicate this. I can open a local server without any issues. I assume you are not running the server in the same process where WebDriver is instantiated.

Can you provide a complete GitHub repository with instructions we can use to reproduce the issue?

**Comment by jj-github-jj** [comment]
> I cannot replicate this. I can open a local server without any issues. I assume you are not running the server in the same process where WebDriver is instantiated.
> 
> Can you provide a complete GitHub repository with instructions we can use to reproduce the issue?

Thanks for the quick response. I was actually doing both a) running the server from within VSCODE jupyter notebook and then  b) in the next cell trying to use WebDriver to navigate to the server url . Based on your question, I just tried  starting the local server from outside of VSCode (from cmd terminal in windows 10) and WebDriver still in VSCode is now working fine in terms of opening the web page gettering served by local server at localhost:60606 (as an example) as you also indicated so you must have initiated the server from another process as well.
I was not aware that running the server and WebDriver both from within the same python kernel in VSCode would not work.
Can you please comment on that reason?

**Comment by diemol** [comment]
I assume they block each other if they run in the same process. 

I will close this as it is not a Selenium issue.
