### ISSUE TITLE
Message: unknown error: cannot connect to chrome at 127.0.0.1:9222 from session not created: This version of ChromeDriver only supports Chrome version 121 Current browser version is 123.0.6312.59[🐛 Bug]: 

### ISSUE THREAD

**Issue by AlphabetGitHub** [SeleniumHQ/selenium#13720]
### What happened?

My chrome browser has updated yesterday and ended up with this error. I have tried to redownload chrome at version 121, but it seems that official website does not provide that version. I've also tried to download a new version of chromedriver at: https://googlechromelabs.github.io/chrome-for-testing/#stable, but it ended up with the same error...

### How can we reproduce the issue?

```shell
What should I do to fix this bug? Your help will be sincerely appreciated!
```

### Relevant log output

```shell
WebDriverException
Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from session not created: This version of ChromeDriver only supports Chrome version 121
Current browser version is 123.0.6312.59
```

### Operating System

Windows 10

### Selenium version

Python 3.9.13 64-bit

### What are the browser(s) and version(s) where you see this issue?

The browser version 123.0.6312.59

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 121.0.6167.184

### Are you using Selenium Grid?

No

**Comment by ryokugyu** [comment]
@AlphabetGitHub Either downgrade your Chrome browser version or upgrade to latest chromedriver as we can see both the browser and chromedriver version is different.

**Comment by AlphabetGitHub** [comment]
@ryokugyu 
 I've tried to upgrade chromedriver to Version: 123.0.6312.58 (r1262506) through https://googlechromelabs.github.io/chrome-for-testing/#stable, but it didn't work. It seems like there is no chromedriver corresponding to chrome version 123.0.6312.59...

**Comment by thomaskast** [comment]
Its here, but I do not think that it will help you; it seems that selenium is not supporting chrome 123 yet, I get all kinds of failed selectors
![image](https://github.com/SeleniumHQ/selenium/assets/62110489/f824c620-f731-4a64-b1d0-c729e298d44a)

**Comment by diemol** [comment]
@ryokugyu delete your local drivers and let Selenium Manager handle the browser driver configuration. Check https://www.selenium.dev/documentation/selenium_manager/

**Comment by SamsPatel** [comment]
I have used the below dependencies for  but getting an exception my chrome version is 123.0.6312.59
 org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*], extensions: []}}

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.10.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>3.3.1</version>
                </dependency>
