### ISSUE TITLE
[🚀 Feature]: Selenium build project Docker script update

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#13731]
### Feature and motivation

This Docker script seems out of date https://github.com/SeleniumHQ/selenium/blob/trunk/scripts/dev-image/Dockerfile

It is using java 11 but the selenium build instructions is using java 17 as minimum?

### Usage example

This is a very useful script and it would be great to have it current, thanks.

**Comment by diemol** [comment]
@csgbn could you please help us with a pull request?
