### ISSUE TITLE
Defining custom commands

### ISSUE THREAD

**Issue by adrigzr** [SeleniumHQ/selenium#1374]
Hi,

In order to implement some missing messages from mjsonWire protocol, I need to define some custom commands when using remote server. How can it be achieved?

I've tried using private executors from webdriver instance, but they does not give the defineCommand method.

The commands I need to implement are the ones related of manipulating session context:

```
GET /session/:sessionId/context
Get the current context (mjsonWire).
POST /session/:sessionId/context
Set the current context (mjsonWire).
GET /session/:sessionId/contexts
Get a list of the available contexts (mjsonWire).
```

https://github.com/admc/wd/blob/master/doc/jsonwire-full-mapping.md

I'm currently using javascript implementation of selenium-webdriver.

Thank you!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
