### ISSUE TITLE
[🐛 Bug]: session not created: DevToolsActivePort file doesn't exist (SessionNotCreated)

### ISSUE THREAD

**Issue by shankargv87** [SeleniumHQ/selenium#13749]
### What happened?

I'm facing this issue for a long time. Initially I got the timeout error (**The HTTP request to the remote WebDriver server for URL http://localhost:60300/session timed out after 60 seconds**). Later I found an article saying increasing the timeout value to 180 secs solved the issue. After increasing the timeout value to 180 secs I'm getting the below error

**session not created: DevToolsActivePort file doesn't exist (SessionNotCreated)**

Same selenium script is working fine for Microsoft Edge. 

### How can we reproduce the issue?

```shell
ChromeDriverService chromeService = ChromeDriverService.CreateDefaultService( AppDomain.CurrentDomain.BaseDirectory, "WebDrivers\\chromedriver.exe" );
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.AddArguments( "--no-sandbox" );
IWebDriver Driver = new ChromeDriver( chromeService, chromeOptions, TimeSpan.FromSeconds( 180 ) );
```

### Relevant log output

```shell
Message: 
  System.InvalidOperationException : session not created: DevToolsActivePort file doesn't exist (SessionNotCreated)

Stack Trace: 
  WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
  WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
  WebDriver.StartSession(ICapabilities desiredCapabilities)
  WebDriver.ctor(ICommandExecutor executor, ICapabilities capabilities)
  ChromiumDriver.ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
  ChromeDriver.ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
  BrowserDriver.CreateWebDriver(BrowserType input) line 54
```

### Operating System

Windows 10

### Selenium version

.NET Selenium.WebDriver 4.11.0

### What are the browser(s) and version(s) where you see this issue?

Version 123.0.6312.86 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver - win64 - 123.0.6312.86

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
You need to upgrade to the most recent version first and then report back on how it went.

**Comment by shankargv87** [comment]
It is working now after adding the below chrome options.

chromeOptions.AddArguments( "--remote-debugging-pipe" );

Reference - https://bugs.chromium.org/p/chromedriver/issues/detail?id=4403#c35

**Comment by diemol** [comment]
You need to upgrade because later versions better handle how ChromeDriver expects to know the browser binary location. If you need more help, please use the links below.

**Comment by shankargv87** [comment]
> You need to upgrade because later versions better handle how ChromeDriver expects to know the browser binary location. If you need more help, please use the links below.

I tried using latest Selenium.WebDriver **4.18.1** getting the same error without adding chrome options "--remote-debugging-pipe". It is working fine with chrome options "--remote-debugging-pipe".
