### ISSUE TITLE
[🐛 Bug]: ActionChains  - tap element on Windows app fails 'REQUEST FAILED WITH STATUS CODE 501'/'object has no attribute 'execute''

### ISSUE THREAD

**Issue by Anna-Ku** [SeleniumHQ/selenium#13748]
### What happened?

Appium-Python-Client==4.0.0  removed TouchAction so I trying to tap element with ActionChains.

**Code - option 1**(removed loop, because each time he fails on 'actions.perform()' with error **'REQUEST FAILED WITH STATUS CODE 501'** ):
        _# touch_input = PointerInput(interaction.POINTER_TOUCH, 'touch')
        # actions = ActionChains(self.driver_.base_driver())
        # actions.w3c_actions = ActionBuilder(self, mouse=touch_input)
        # actions.w3c_actions.pointer_action.move_to(element)
        # actions.w3c_actions.pointer_action.pointer_down()
        # actions.w3c_actions.pointer_action.pause(0.1)
        # actions.w3c_actions.pointer_action.release()
        # actions.perform()_

Code - option 2 (fails with error **'object has no attribute 'execute''**)
        _action = ActionChains(self.driver_.base_driver())
        action.click_and_hold(element)
        action.perform()
        sleep(0.1)
        action.release(element)_

![image](https://github.com/SeleniumHQ/selenium/assets/83170245/5c527dae-9dc9-4be3-ad39-2b9aaf374578)

**Environment details:**
OS - Windows 10 Pro
Python 3.12
selenium==4.18.1
windows driver - windows@2.12.18 [installed (npm)]

Please assist on how this issue can be resolved.

Thanks,
Anna

### How can we reproduce the issue?

```shell
---
```

### Relevant log output

```shell
---
```

### Operating System

Windows 10 Pro

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by diemol** [comment]
What was the issue?

**Comment by Anna-Ku** [comment]
@diemol this issue related to Appium not Selenium.. still not found the problem, waiting for response from Appium.
