### ISSUE TITLE
[🐛 Bug]: most BiDi packages are missing in v4.19.0 release

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13754]
### What happened?

After updating to the v4.19.0 release most BiDi packages are gone:
![image](https://github.com/SeleniumHQ/selenium/assets/16140691/35609067-b318-4765-93bd-337774ade768)

vs v4.18.0:
![image](https://github.com/SeleniumHQ/selenium/assets/16140691/8fc0d022-5553-439f-8a80-46e857920ddd)

### How can we reproduce the issue?

```shell
Look at the jars :D
```

### Relevant log output

```shell
COMPILATION ERROR ...
```

### Operating System

Win 10 x64

### Selenium version

4.19.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by joerg1985** [comment]
@pujagani could you have a look at this one please?

**Comment by pujagani** [comment]
Yes! Right away. Thank you so much. I think I made a big breaking change that might have introduced this. Let me go take a look.

**Comment by pujagani** [comment]
https://github.com/SeleniumHQ/selenium/commit/acd9d0e77dc5a5a39c3a95a5aa0e94a6c4161fe7 - I think this should fix it. I tested it locally by importing the jar build into another project and was able to see the BiDi folders as expected.  Sincere apologies for introducing the error and missing out on updating the Bazel files correctly. I was operating under the wrong assumptions. 
<img width="461" alt="Screenshot 2024-03-29 at 12 11 27 PM" src="https://github.com/SeleniumHQ/selenium/assets/10705590/d9cd97c9-0bb2-4fd0-b720-b6282cffafc7">

**Comment by diemol** [comment]
Thank you, @pujagani!

**Comment by joerg1985** [comment]
@pujagani thanks for fixing this
