### ISSUE TITLE
LGPL v2.1 license of JBoss-logging

### ISSUE THREAD

**Issue by Christudoss** [SeleniumHQ/selenium#1376]
We want to distribute selenium as part of our product. But selenium has an LGPL license for JBoss-logging which prevents us from shipping due to legal issues.

\selenium-server-standalone-2.48.2.jar: META-INF/license/LICENSE.jboss-logging.txt 

JBoss-logging moved to Apache license in 2012. Here is the link:
https://github.com/jboss-logging/jboss-logging/blob/master/src/main/resources/META-INF/LICENSE.txt

But the netty 3.5.7 (bundled in selenium jar files) has this jboss-logging which is still having this license. The latest versions of netty doesn't have LGPL. 

Can you upgrade the netty or use jboss-logging under apache license. This will help us overcome legal hurdle in distributing selenium with our product.

**Comment by Christudoss** [comment]
Can netty version be bumped to 4.x? It will resolve legal issues in bundling selenium for us as jboss-logging used in the current version of netty (3.57) has LGPL (viral license).

**Comment by lukeis** [comment]
This is a non-trivial upgrade. Care to take a stab at it and submit a pull request?

**Comment by Christudoss** [comment]
Thanks for the reply. I'll see if some of my colleagues can try this.

**Comment by barancev** [comment]
Netty upgraded to version 4.1.14.Final in Selenium 3.5
