### ISSUE TITLE
[🐛 Bug]: Chrome session not starting with grid 4.19.0

### ISSUE THREAD

**Issue by ksingha161** [SeleniumHQ/selenium#13760]
### What happened?

We just upgraded to selenium 4.19.0. Our grid infra is setup as 6 windows remote desktops. After updating, chrome session is not starting and it throws the following exception.

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 123.0.6312.86 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe 
```

We have deleted all previous chrome drivers present in selenium manager cache but it does not work.

This issue is only happening in case of grid.

### How can we reproduce the issue?

```shell
Command to start grid - 

java -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.19.0.jar hub &

sleep 5

java -Dwebdriver.http.factory=jdk-http-client -jar selenium-server-4.19.0.jar node --config nodetom.toml &

toml file - 
[node]
override-max-sessions = true
max-sessions = 15
drivers = ["chrome"]
selenium-manager = true
detect-drivers = false
enable-managed-downloads = true
grid-url = "urlHere"
session-timeout = 1800
[[node.driver-configuration]]
max-sessions = 15
display-name = "Chrome"
stereotype = '{"browserName": "chrome", "platformName": "WIN10", "networkname:applicationName":"node_1", "nodename:applicationName":"app_1"}'
```

### Relevant log output

```shell
Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
```

### Operating System

windows 10

### Selenium version

selenium - 4.19.0, java - 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 123.0.6312.86

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 123

### Are you using Selenium Grid?

4.19.0

**Comment by diemol** [comment]
>This version of ChromeDriver only supports Chrome version 114
You need to upgrade your ChromeDriver version on the Node or let Selenium Manager handle it (flag `--selenium-manager true` on the Node).

**Comment by karanjeetbirdeye** [comment]
Hi @diemol Chrome version is updated to 123 and ChromeDriver is being handled by selenium manager. It is set to true in toml config. Is there any other place selenium manager needs to be set?

**Comment by diemol** [comment]
If you have a ChromeDriver on your path, that takes a higher priority.

**Comment by karanjeetbirdeye** [comment]
Thanks. We don't have ChromeDriver on path. Previously we were on 4.12.1 and same config was working without any issues.

**Comment by diemol** [comment]
You can also increase the log level and see where the ChromeDriver is being picked up from.

**Comment by karanjeetbirdeye** [comment]
This is the driver path selenium manager is logging
`SeleniumManager.getInstance().getDriverPath(chromeOptions, false).getDriverPath();`
` C:\Users\Administrator\.cache\selenium\chromedriver\win64\123.0.6312.86\chromedriver.exe`

**Comment by diemol** [comment]
I would need to see the whole log in debug mode to understand better the issue.

**Comment by karanjeetbirdeye** [comment]
Can you guide me how I can get the logs?

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/grid/configuration/cli_options/#logging
