### ISSUE TITLE
[🐛 Bug]:  Chrome Driver issue. Not able to handle window based popup with chrome options. Popup not getting disabled.

### ISSUE THREAD

**Issue by AnilMohnani** [SeleniumHQ/selenium#13761]
### What happened?

Scripts fail because window popup is not handled.

### How can we reproduce the issue?

```shell
Windows popup not getting disabled using chrome options. Downloading files popup is not getting disabled.
```

### Relevant log output

```shell
Code fails
```

### Operating System

Windows

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome latest 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver latest

### Are you using Selenium Grid?

No

**Comment by AnilMohnani** [comment]
Hi Team,

SCENEARIO

1. login to app
2. Click on download button
3. On cliking 2 files gets downloaded but during automation in chrome
We get a pop up of where to save the file.
4. We tried to handle the windows popup by directly defaulting the
downloads to a specified downloads folder.
5. This we did using chrome options
6. But popup was not getting disabled
7. We found out its because the latest version of chrome driver and browser.
8. Pls guide us.

**Comment by diemol** [comment]
We need the actual code to reproduce the issue. Without that we cannot triage this.

**Comment by AnilMohnani** [comment]
String downloadFilepath = "/path/to/download";
HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
chromePrefs.put("profile.default_content_settings.popups", 0);
chromePrefs.put("download.default_directory", downloadFilepath);
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("prefs", chromePrefs);
options.addArguments(
   "--verbose",
   "--headless",
   "--disable-web-security",
   "--ignore-certificate-errors",
   "--allow-running-insecure-content",
   "--allow-insecure-localhost",
   "--no-sandbox",
   "--disable-gpu"
  );

Please let me know

**Comment by joerg1985** [comment]
@AnilMohnani There is a GPO to control this and this will overwrite the capabilities set. I raised an [chromedriver issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3306) regarding this, some time ago and it was rejected.

Could you check the GPO is set on your system?

**Comment by diemol** [comment]
The preference in Chrome is `download.prompt_for_download: false`
