### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.WebDriverException: Unable to route (POST) /session/0405a24bf1d06c6ae8402b8d12027934/...

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13769]
### What happened?

When executing a command on a just timedout session a `WebDriverException: Unable to route ...` is raised.

### How can we reproduce the issue?

For some seconds after the session timedout there is a inconsistent state, until the `sessionCleanupNodeService` of the `LocalNode` did run. The `LocalSessionMap` still tells the session does exist, but the `Node.isSessionOwner` does return false. This will prevent the route inside the `Node` is matched and lead to the `WebDriverException: Unable to route ...`.

### Relevant log output

```shell
N/A
```

### Operating System

Win 10 x64

### Selenium version

4.17.1

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
How do you think Grid should behave in this case? Should the exception be more clear?

**Comment by joerg1985** [comment]
@diemol At this time the exception is raised the session is allready timed out.
So i would expect a NoSuchSessionException and not something that indicates an grid bug.

**Comment by diemol** [comment]
Do you know where this exception was shown? I can tweak the response we send to the user.

**Comment by joerg1985** [comment]
It is raised here:
https://github.com/SeleniumHQ/selenium/blob/2b5999625744adccf2a0ad30cdd18d503044603b/java/src/org/openqa/selenium/grid/web/RoutableHttpClientFactory.java#L60-L68

Here the session map still returns the session, but the following ownership check fails:
https://github.com/SeleniumHQ/selenium/blob/2b5999625744adccf2a0ad30cdd18d503044603b/java/src/org/openqa/selenium/grid/node/Node.java#L149-L151

**Comment by VietND96** [comment]
@joerg1985, do you have a test on which command can return that error when session just timed out?
Since I tried to reproduce but could not see that error, only saw `selenium.common.exceptions.InvalidSessionIdException: Message: Cannot find session with id: 05592d304812288f6c153de8529b0b28
`

**Comment by joerg1985** [comment]
@VietND96 i could reproduce the issue with the code below.

One solution might be to extend the `org.openqa.selenium.grid.data.Session` with the node id.
This could be used to check the ownership of the session instead of calling `Node.isSessionOwner`.
And might be helpful in other areas too, e.g. processing a slightly delayed `NodeRestartedEvent`, this could be the root cause of #14322
But i have not tried so far and there might be side effects.

```
public static void main(String[] args) throws Exception {
        org.openqa.selenium.grid.Bootstrap.main(("hub --host 127.0.0.1 --port 4444").split(" "));
        org.openqa.selenium.grid.Bootstrap.main(("node --host 127.0.0.1 --port 5555 --session-timeout 20 --selenium-manager true").split(" "));

        try {

            ClientConfig config = ClientConfig.defaultConfig()
                    .baseUri(URI.create("http://localhost:4444"));

            var options = new ChromeOptions();

            options.addArguments("--disable-search-engine-choice-screen");

            for (int i = 0; i < 10; i++) {

                WebDriver driver = new RemoteWebDriver(URI.create("http://localhost:4444").toURL(), options);//RemoteWebDriver.builder().config(config).oneOf(options).build();

                // ensure the session reached it's timeout
                Thread.sleep(20000);

                try {
                    driver.getTitle();
                } catch (NoSuchSessionException e) {
                    // the correct exception, the internal cleanup of LocalNode.currentSessions has been
                    // run between the session timeout and the getTitle command.
                    continue;
                } catch (WebDriverException e) {
                    /**
                     * this is the not expected state
                     */
                    throw e;
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // kill the server
            System.exit(0);
        }

    }
```

**Comment by VietND96** [comment]
Adding NodeId to `org.openqa.selenium.grid.data.Session` would be a huge update, and it also adds a reverse dependency between Session <-> Node

**Comment by joerg1985** [comment]
You are right, the Node is currently not aware of the other Grid components.
Another option might be to replace the Guava Cache, as it makes entries unreachable before they are handled by the cleanup.

@diemol is it a long term goal to remove Guava from the server, like [from the client](https://github.com/SeleniumHQ/selenium/issues/12737)?

**Comment by diemol** [comment]
I believe we did not think about the server, but I would not be opposed to that. 

What would be the alternative?

**Comment by VietND96** [comment]
After walkthrough implementation, I see the event `SessionClosedEvent` is sent and listened by components properly.
I also added a fix by calling `getSession()`, which should return nonNull before going to check `isSessionOwner()`. Then we can get the right exception `NoSuchSessionException`. I added a unit test to verify it in PR #14628

**Comment by joerg1985** [comment]
@diemol One option would be to allow the node to answer with a "NoSuchSessionException" as proposed by @VietND96 as soon as a sessionId is set and the session is unkown or not owned by the node. Currently the node does answer with `WebDriverException: Unable to route` in this case.

To implement this i would move the `.map(this::isSessionOwner)` to the `ForwardWebDriverCommand` and drop the `NodeTest.shouldOnlyRespondToWebDriverCommandsForSessionsTheNodeOwns` test as it is useless now.

**Comment by VietND96** [comment]
I tried to update it as you suggested, move it to `ForwardWebDriverCommand`, and update the unit test without random UUID. Please check if it makes sense to you.
