### ISSUE TITLE
[🐛 Bug]: `--sub-path` does not disable the default routes to the Hub/Router/Standalone

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#13765]
### What happened?

When using the `--sub-path` CLI the expected behaviour should be: [A sub-path that should be considered for all user facing routes on the Hub/Router/Standalone.](https://www.selenium.dev/documentation/grid/configuration/cli_options/#router).

In my mind this should disable the default URLs, is this correct or is my expectation incorrect?

### How can we reproduce the issue?

```shell
java -jar selenium-server-4.17.0.jar standalone --host 127.0.0.1 --port 4567 --selenium-manager true --sub-path sub/path

Both URLs are working:
http://127.0.0.1:4567/sub/path/status
http://127.0.0.1:4567/status
```

### Relevant log output

```shell
N/A
```

### Operating System

Win 10 x64

### Selenium version

4.17.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

N/A

**Comment by diemol** [comment]
We never planned to block the default routes, but rather enable new ones. This is expected.

**Comment by joerg1985** [comment]
@diemol thanks for clarification
