### ISSUE TITLE
[🐛 Bug]: OpenQA.Selenium.WebDriverException: unknown error:  unable to discover open pages

### ISSUE THREAD

**Issue by AkshayBamne** [SeleniumHQ/selenium#13776]
### What happened?

Getting this "OpenQA.Selenium.WebDriverException: unknown error:
 unable to discover open pages" on azure pipelines with the MsEdge driver with C#.
Using the latest (Version 123.0.2420.65 (Official build) (64-bit) edge browser as well as edge driver on pipeline machine. I have tested the same configuration test work on the local machine but failing on the remote pipeline machine. So kindly help me with solution if I have to disable some edgeOptions or something like that. Thanks

### How can we reproduce the issue?

```shell
Create selenium test with C# and execute it on MsEdge browser on pipeline machine.
```

### Relevant log output

```shell
NA
```

### Operating System

Windows 11

### Selenium version

3.141.0.0

### What are the browser(s) and version(s) where you see this issue?

MsEdge 123.0.2420.65

### What are the browser driver(s) and version(s) where you see this issue?

MsEdge 123.0.2420.65

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Please note we do not support old versions of Selenium. You should provide more information (logs, etc.) when using the latest version.

**Comment by diemol** [comment]
I will close this because we didn't get any more information.
