### ISSUE TITLE
[🐛 Bug]: The 'duration' argument of 'performActions' API does not affect on Android WebView ( Appium 1.22.*, Appium 2.5.1 )

### ISSUE THREAD

**Issue by kimduquan01** [SeleniumHQ/selenium#13777]
### What happened?

The control is slide but the 'duration' does not affect so that the slide action is perform too fast.

### How can we reproduce the issue?

```shell
1. on Android device, open an application that use embedded WebView
 2. call 'switchToContext' API to switch to a web view context
 3. call the 'performActions' API with the follow JSON input:
    { "actions": [ { "id": "touch", "type": "pointer", "parameters": { "pointerType": "touch" }, "actions": [ { "duration": 0, "x": 0, "y": 0, "type": "pointerMove", "origin": "viewport" }, { "duration": 0, "x": 180, "y": 378, "type": "pointerMove", "origin": "viewport" }, { "button": 0, "type": "pointerDown" }, { "duration": 500, "x": -90, "y": -189, "type": "pointerMove", "origin": "pointer" }, { "button": 0, "type": "pointerUp" } ] } ] }
```

### Relevant log output

```shell
There no log.
```

### Operating System

Window, Android

### Selenium version

Selenium 4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 122

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0.6312.86

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Please report this to the Appium project.
