### ISSUE TITLE
[🐛 Bug]: Unable to use headless with chrome

### ISSUE THREAD

**Issue by frankie-frank-frank** [SeleniumHQ/selenium#13788]
### What happened?

Chrome's Options now lacks the headless() method.

### How can we reproduce the issue?

```shell
import { Options } from "selenium-webdriver/chrome";
const options = new Options();
options.setChromeBinaryPath("/usr/bin/chromium");
options.addArguments('--enable-logging=ALL');
options.headless();
```

### Relevant log output

```shell
Property 'headless' does not exist on type 'Options'.
```

### Operating System

MacBook Pro (Retina, 15-inch, Mid 2015)

### Selenium version

    "selenium-webdriver": "^4.19.0"

### What are the browser(s) and version(s) where you see this issue?

Chrome/119.0.0.0

### What are the browser driver(s) and version(s) where you see this issue?

Chrome/119.0.0.0

**Comment by diemol** [comment]
https://www.selenium.dev/blog/2023/headless-is-going-away/
