### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by Amanyadav12345** [SeleniumHQ/selenium#13787]
### What happened?

Hello Team,

Please find below mentioned details for the issue encountered in which the chrome / edge is not getting launched on

VM running: Windows Server 2016 datacenter
Maven version : 3.6.2
JAVA: 17.0.8

Each time I try to execute the test case using below mentioned code to launch chrome browser :

ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("platformName", "Windows");
        chromeOptions.setAcceptInsecureCerts( true );
        chromeOptions.addArguments( "window-size=1920,1080"/*, "--disable-features=VizDisplayCompositor"*/ );
        chromeOptions.addArguments( "--disable-notifications" );
        chromeOptions.addArguments("--enable-javascript");
        chromeOptions.setBrowserVersion("stable" );
        if( isHeadless )
        {
          chromeOptions.addArguments( "--headless" );
        }
        if( !System.getProperty( "os.name" ).toLowerCase().contains( "windows" ) )
        {
          chromeOptions.addArguments( "--no-sandbox", "--disable-dev-shm-usage" );
        }
        Map<String, Object> preferences = new HashMap<>();
        preferences.put( "download.default_directory", System.getProperty( "user.dir" ) + "\\target\\surefire-reports\\downloads" );
        preferences.put( "download.prompt_for_download", false );
        preferences.put( "download.directory_upgrade", true );
        preferences.put( "behavior", "allow" );
        preferences.put( "profile.default_content_settings.popups", 0 );
        preferences.put( "profile.managed_default_content_settings.javascript", 1);
        // can add more prefs here before adding the Map to the chrome options
        chromeOptions.setExperimentalOption( "prefs", preferences );
        String remoteUrl = "https://xxxx.xxxx.xxxxxx.com"; // replace with the actual URL

        return new RemoteWebDriver(new URL(remoteUrl), chromeOptions);

I encounter below mentioned error on the console:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

java.lang.IllegalStateException: No webdriver is bound to current thread: 103. You need to call open(url) first.

### How can we reproduce the issue?

```shell
Each time I try to execute the test case using below mentioned code to launch chrome browser :

ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setCapability("platformName", "Windows");
        chromeOptions.setAcceptInsecureCerts( true );
        chromeOptions.addArguments( "window-size=1920,1080"/*, "--disable-features=VizDisplayCompositor"*/ );
        chromeOptions.addArguments( "--disable-notifications" );
        chromeOptions.addArguments("--enable-javascript");
        chromeOptions.setBrowserVersion("stable" );
        if( isHeadless )
        {
          chromeOptions.addArguments( "--headless" );
        }
        if( !System.getProperty( "os.name" ).toLowerCase().contains( "windows" ) )
        {
          chromeOptions.addArguments( "--no-sandbox", "--disable-dev-shm-usage" );
        }
        Map<String, Object> preferences = new HashMap<>();
        preferences.put( "download.default_directory", System.getProperty( "user.dir" ) + "\\target\\surefire-reports\\downloads" );
        preferences.put( "download.prompt_for_download", false );
        preferences.put( "download.directory_upgrade", true );
        preferences.put( "behavior", "allow" );
        preferences.put( "profile.default_content_settings.popups", 0 );
        preferences.put( "profile.managed_default_content_settings.javascript", 1);
        // can add more prefs here before adding the Map to the chrome options
        chromeOptions.setExperimentalOption( "prefs", preferences );
        String remoteUrl = "https://xxxx.xxxx.xxxxxx.com"; // replace with the actual URL

        return new RemoteWebDriver(new URL(remoteUrl), chromeOptions);
```

### Relevant log output

```shell
java.lang.IllegalStateException: No webdriver is bound to current thread: 103. You need to call open(url) first.
com.codeborne.selenide.impl.WebDriverThreadLocalContainer.lambda$currentThreadDriver$1(WebDriverThreadLocalContainer.java:180)
java.base/java.util.Optional.orElseThrow(Optional.java:403)
com.codeborne.selenide.impl.WebDriverThreadLocalContainer.currentThreadDriver(WebDriverThreadLocalContainer.java:179)
com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getWebDriver(WebDriverThreadLocalContainer.java:142)
com.codeborne.selenide.WebDriverRunner.getWebDriver(WebDriverRunner.java:112)
com.codeborne.selenide.impl.StaticDriver.getWebDriver(StaticDriver.java:51)
com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:40)
com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:33)
com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:122)
com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:21)
com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:15)
com.codeborne.selenide.commands.Commands.execute(Commands.java:163)
com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:132)
com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:84)
jdk.proxy2/jdk.proxy2.$Proxy16.isDisplayed(Unknown Source)
pageObjects.modals.NotificationModal.isDisplayed(NotificationModal.java:29)
utilities.testng.WebDriverTestNGTest.closeNotificationsAndModals(WebDriverTestNGTest.java:139)
```

### Operating System

Windows server 2016 datacenter

### Selenium version

selenium version 4.11.0

### What are the browser(s) and version(s) where you see this issue?

chrome browser 123.0.6312.106

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 123.0.6312.86    

### Are you using Selenium Grid?

4.17.0

**Comment by diemol** [comment]
>504 Gateway Time-out

This error comes from the Grid you are using. Could you check the timeout configured or the components placed on top (such as nginx)? That is why you are getting the error Selenide reports.
