### ISSUE TITLE
WebDriverWait not firing timeout exception

### ISSUE THREAD

**Issue by ahmetax** [SeleniumHQ/selenium#1378]
I am using Python 3.4 on ubuntu 14.04.3 LTS and Python 3.5 on windows 10.
In my script, I am using webdriver.Firefox().
WebDriverWait() function does not fire timeout. When there is a problem o a web page loading, it waits forever.
In order to overcome that issue I am using socket timeout with the function RemoteConnection.set_timeout(180)
My script is at   https://github.com/ahmetax/avare/blob/master/avare_50.py
Ahmet Aksoy

**Comment by ahmetax** [comment]
https://github.com/ahmetax/avare/blob/master/avare_50.py
https://github.com/ahmetax/avare/blob/master/visits.tx
https://github.com/ahmetax/avare/blob/master/proxy.txt

**Comment by barancev** [comment]
Yes, WebDriverWait is not designed to handle page loading timeouts.

One should use less strict page loading strategy or set page loading timeout:
driver.set_page_load_timeout(30)
