### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by martodvo** [SeleniumHQ/selenium#13797]
### What happened?

I was running some scripts in python with Selenium and now when I try I get an error.

`runfile('C:/Users/Adduntia/Downloads/Sin título1.py', wdir='C:/Users/Adduntia/Downloads')
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\adduntia\downloads\sin título1.py:3
    driver = webdriver.Chrome()

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py:45 in __init__
    super().__init__(

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py:50 in __init__
    self.service.start()

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py:98 in start
    self._start_process(self._path)

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py:208 in _start_process
    self.process = subprocess.Popen(

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\customize\spydercustomize.py:109 in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File ~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1026 in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File ~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1538 in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

OSError: [WinError 1392] El archivo o directorio está dañado o es ilegible
`

### How can we reproduce the issue?

```shell
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://www.google.com/")
```

### Relevant log output

```shell
runfile('C:/Users/Adduntia/Downloads/Sin título1.py', wdir='C:/Users/Adduntia/Downloads')
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\adduntia\downloads\sin título1.py:3
    driver = webdriver.Chrome()

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py:45 in __init__
    super().__init__(

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py:50 in __init__
    self.service.start()

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py:98 in start
    self._start_process(self._path)

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py:208 in _start_process
    self.process = subprocess.Popen(

  File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\spyder_kernels\customize\spydercustomize.py:109 in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File ~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1026 in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File ~\AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1538 in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

OSError: [WinError 1392] El archivo o directorio está dañado o es ilegible
```

### Operating System

windows 11

### Selenium version

4.17

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

**Comment by diemol** [comment]
>runfile('C:/Users/Adduntia/Downloads/Sin título1.py', wdir='C:/Users/Adduntia/Downloads')

It looks like you are running the code from another Python file. 

>OSError: [WinError 1392] El archivo o directorio está dañado o es illegible

The error is about the file integrity, and nothing is related to Selenium. 

If you need help with this, please use one of the links below.
