### ISSUE TITLE
[🐛 Bug]: Selenium Manager | beta version of edge is not downloaded

### ISSUE THREAD

**Issue by reWireByAutomation** [SeleniumHQ/selenium#13794]
### What happened?

Hi Team,

I have given specific versions like "120" or "beta" in the options for edge browser execution. Selenium Manager has not downloaded the "beta" version of Edge instead used the latest version installed in the host machine. This exercise is done in the personal system and not in the corporate network.

it is working for the installed edge browser V123.

### How can we reproduce the issue?

```shell
Simple java-based gradle project as below

public class BetaVersion {

    //Beta version check
    //browseroption in the label format
    // https://www.microsoft.com/en-us/edge/download
    public static void main(String[] args) throws InterruptedException {
        EdgeOptions edgeOptions = new EdgeOptions();
        edgeOptions.setPlatformName("Windows");
        edgeOptions.setBrowserVersion("beta");
        WebDriver driver = new EdgeDriver(edgeOptions);
        driver.get("https://www.selenium.dev/selenium/web/web-form.html");
        Thread.sleep(2000);
        driver.quit();
    }
}
```

### Relevant log output

```shell
> Task :BetaVersion.main()
Apr 09, 2024 11:13:21 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
WARNING: Expected MicrosoftEdge path does not exists: C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe
WARNING: Expected MicrosoftEdge path does not exists: C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe

Apr 09, 2024 11:13:21 PM org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1
WARNING: There was an error managing msedgedriver (MicrosoftEdge 124 cannot be downloaded); using driver found in the cache
WARNING: There was an error managing msedgedriver (MicrosoftEdge 124 cannot be downloaded); using driver found in the cache

Similar error is observed when I given version as "120"
```

### Operating System

Windows 11 Home 64bit

### Selenium version

JDK 11 , Gradle and Selenium latest version 4.19.1

### What are the browser(s) and version(s) where you see this issue?

edge browser (beta and version less than current version)

### What are the browser driver(s) and version(s) where you see this issue?

edge

### Are you using Selenium Grid?

No

**Comment by reWireByAutomation** [comment]
Hi Team,

Thanks for the update and response.
I have enabled logger in my code for the Edge browser. Below are my
findings on the results initial analysis.

Edge browser, we need to provide a browser option as "*Beta*" and
downloaded the beta version (124). Earlier I gave browserOption as "*beta*",
so it is not downloaded. I found the below link from the log and discovered
the correct label.
edgeupdates.microsoft.com/api/products

Same for the next version, we should provide "*Dev*" and "*Canary*".
Earlier I was trying it as "dev" and "canary".

Below are the new issues I found-
*Beta & Dev:* The driver is downloaded but unable to create a driver session
*Canary*: The edge driver is not downloaded instead it uses the existing
version
*Specific version*: I have given version as "121", it is not downloaded.
Can you mention specific syntax to provide older versions? I found
the below link from the log, though the version is available in the repo,
it is not downloaded.
edgeupdates.microsoft.com/api/products/?view=enterprise

PFA attached log files for further analysis and provide your inputs on
above mentioned "edge driver" issues.

In the selenium blog (
https://www.selenium.dev/blog/2023/status_of_selenium_manager_in_october_2023/),
it is mentioned as "beta", if you can correct it in future blogs for
edgedirver that would be great. Chrome and Firefox, "beta" is working fine.

This exercise is on Windows env.

*Kiran Edupuganti, PMP*
***@***.***
<https://www.youtube.com/channel/UC6sujnWmnjfymbp2TqXr0HQ>
*Medium Blogging:* reWireByAutomation Blog
<https://rewirebyautomation.medium.com/>

**Comment by diemol** [comment]
@bonigarcia do you know if the upper or lower casing matters in Edge?

**Comment by bonigarcia** [comment]
The labels `beta`, `dev`, `canary`, etc, referred to browser versions, are not case sensitive in Selenium Manager. But managing Edge in Windows is an special case, since due to the nature of the Edge MSI distribution, it requires administrator permissions to be installed. More info in [doc](https://www.selenium.dev/documentation/selenium_manager/#edge-in-windows).

**Comment by diemol** [comment]
Thank you both for the input and resolution!

**Comment by reWireByAutomation** [comment]
Hi Team,

I am aware of 'Edge" scenarios in Windows, it needs admin privileges. I am
trying this in my system though the driver is downloaded, and the session
is not created. I have shared log files. I still need to do a deep analysis
of the logs.

*Kiran Edupuganti*
***@***.***
<https://www.youtube.com/channel/UC6sujnWmnjfymbp2TqXr0HQ>
*Medium Blogging:* reWireByAutomation Blog
<https://rewirebyautomation.medium.com/>

**Comment by reWireByAutomation** [comment]
I will update you if I get any resolution on the "*Edge*" session issue.

*Kiran Edupuganti*
***@***.***
<https://www.youtube.com/channel/UC6sujnWmnjfymbp2TqXr0HQ>
*Medium Blogging:* reWireByAutomation Blog
<https://rewirebyautomation.medium.com/>

**Comment by bonigarcia** [comment]
I would need see more details in your logs. As requested previously:

> We need more information about this issue in order to troubleshoot.
> 
> Please turn on logging and re-run your code. Information on how to adjust logs for your language can be found in our [Troubleshooting documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/).

See [example](https://github.com/bonigarcia/selenium-examples/blob/main/src/test/java/io/github/bonigarcia/selenium/logging/EdgeLoggingTest.java).
