### ISSUE TITLE
[🐛 Bug]: Selenium download pop-up window does not get disabled with the latest chrome versions

### ISSUE THREAD

**Issue by Akkasim46** [SeleniumHQ/selenium#13801]
### What happened?

I have been using selenium-java for my automation tests. Recently, tests that involve downloading file started failing due to the download pop-up window. I have seen this issue before and this code was the fix for it.

chromeOptions.addArguments("disable-features=DownloadBubble,DownloadBubbleV2");

Then also I used something like this 

  SessionId sessionId = ((RemoteWebDriver) driver).getSessionId();
        String downloadsEndpoint = String.format("/session/%s/se/files", sessionId);
        String fileToDownload;

        try (org.openqa.selenium.remote.http.HttpClient client = org.openqa.selenium.remote.http.HttpClient.Factory.createDefault().createClient(gridUrl)) {
            // To list all files that are were downloaded on the remote node for the current session we trigger GET request.
            HttpRequest request = new HttpRequest(GET, downloadsEndpoint);
            org.openqa.selenium.remote.http.HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            
           ...

They ^ both don't help now.

### How can we reproduce the issue?

```shell
Just have a selenium-java test with the latest versions of these dependencies. And have a test that does download a file.
```

### Relevant log output

```shell
If you have the both solutions above, you will get NullPointerException. And also when you monitor running that test, you will see the test will get stuck when the download pop-up window appears.
```

### Operating System

MacOS

### Selenium version

Java-4.18 ...

### What are the browser(s) and version(s) where you see this issue?

chrome 120...

### What are the browser driver(s) and version(s) where you see this issue?

Google Chrome	123.0.6312.124 (Official Build) (x86_64)

### Are you using Selenium Grid?

yes and it occurs on local machine too

**Comment by Akkasim46** [comment]
where can we follow when chrome fixes this issue? like coming up with a new argument for solution.

**Comment by diemol** [comment]
You can check this issue tracker https://bugs.chromium.org/p/chromedriver/issues/list and if you do not find one, please create one and share the link here.

**Comment by Akkasim46** [comment]
Yes I found the issue in the list that's been created already. 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4582
Thank you so much for the help!

**Comment by Akkasim46** [comment]
I found one that looks similar but not actually what we see. So I created one for the issue I see. 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4750
