### ISSUE TITLE
[🚀 Feature]: execute_cdp_cmd allow retrieval of all requests

### ISSUE THREAD

**Issue by RobDBob** [SeleniumHQ/selenium#13812]
### Feature and motivation

I'm looking for a way to utilize Chrome DevTools protocol via selenium to enhance test automation.  My main goal is to identify any outstanding / unfinished API requests to know if  browser is still waiting for response from a server.

There are few available methods but most of them require a requestId without providing a way to retrieve it (unless i'm missing something for which i do apologise)
https://chromedevtools.github.io/devtools-protocol/tot/Network/ 

### Usage example

requestIds = webdriver.execute_cdp_cmd('Network.getRequests', {'status': 'inProgress'})
Then this perhaps could be used with responseReceived event and other methods?

**Comment by diemol** [comment]
We enable the use of CDP but cannot make changes to CDP itself. You'll need to contact the Chrome folks and ask for this.
