### ISSUE TITLE
[🐛 Bug]: PrintsPage method fails on Safari

### ISSUE THREAD

**Issue by cocchiarocarl** [SeleniumHQ/selenium#13815]
### What happened?

Calling the PrintsPage method on the Safari Browser throws the following exception:

Cause = org.openqa.selenium.UnsupportedCommandException: The command 'POST /session/CBC6BACD-874B-48FD-8434-5B76D8D46BB9/print' was not found.

Is the method supported on Safari?

### How can we reproduce the issue?

```shell
WebDriver driver = MyDriverClass.getInstance().getDriver();
PrintOptions printOpts = new PrintOptions();
printOpts.setPageRanges("1-2");

PDF pdf = ((PrintsPage) driver).print(printOpts);
```

### Relevant log output

```shell
Cause = org.openqa.selenium.UnsupportedCommandException: The command 'POST /session/CBC6BACD-874B-48FD-8434-5B76D8D46BB9/print' was not found.
```

### Operating System

macOS Sonoma 14.4.1

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Safari 17.4.1

### What are the browser driver(s) and version(s) where you see this issue?

Built-in Safari Driver

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
This is similar to #11578. The print feature is defined in the [W3C WebDriver standard](https://w3c.github.io/webdriver/#print), but Safari still needs to implement it. We do not plan to block or remove methods that should work in all browsers. Please report this to the Apple folks using the links below.
