### ISSUE TITLE
[🐛 Bug]: close method on Mobile Browser iPhone15/Safari does not close the browser window

### ISSUE THREAD

**Issue by cocchiarocarl** [SeleniumHQ/selenium#13814]
### What happened?

When testing on Mobile Browsers using iOS/iPhone 15 and Safari Browsers, if the close method is called on the Browser, it does not close.

### How can we reproduce the issue?

```shell
Call the close method on the Safari Browser on iOS Simulator using an iPhone 15.
```

### Relevant log output

```shell
None
```

### Operating System

iOS 17.2

### Selenium version

Selenium 4.18.1 and Appium 2.5.0 (Appium 9.1.0 client)

### What are the browser(s) and version(s) where you see this issue?

Safari 17

### What are the browser driver(s) and version(s) where you see this issue?

Safari 17 Built-in Driver

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
You should report this to the Appium project because Selenium helps Appium send the command. They can help clarify if it is an actual bug in Appium or Selenium or an issue in the Apple Simulator.
