### ISSUE TITLE
Safari unable to establish a connection with the SafariDriver 2.48 extension

### ISSUE THREAD

**Issue by roshanhadal** [SeleniumHQ/selenium#1381]
Hi,

I am new to this so excuse my ignorance. I am running the selenium web driver withing my angular-seed project through protractor-jasmine tests. It works fine with Chrome and Firefox drivers. I am not able to run the same with Safari. I even installed latest 2.48 Safari extension but I still get the connection issue. (screenshot attached). Following is my system info:
OS: OS X El Capitan 10.11.2
Safari: Version 9.0.2 (11601.3.9)
Not sure if this is a security issue or the driver issue as I have updated to latest OS X. I have looked at older issues which were on older versions of Safari/OS X. Any pointers will help.

<img width="739" alt="safari_extn" src="https://cloud.githubusercontent.com/assets/8522615/11840885/5908c434-a41f-11e5-8a83-aefc2be17499.png">
<img width="1006" alt="safari_wd_issue_2_48_2" src="https://cloud.githubusercontent.com/assets/8522615/11840886/5910b75c-a41f-11e5-9cb5-52a69e490fae.png">

**Comment by vveliev** [comment]
it does not look like you have extension installed correctly, check  #1315

**Comment by pi4r0n** [comment]
@roshanhadal I am running exact same OS, Safari and same plugin version and it works for me, so I would advise to reinstall plugin.

**Comment by roshanhadal** [comment]
@pi4r0n great to know that. Just to eliminate any missing step, can you describe the steps to install and enable the plugin? I believe I am missing something here as I am new to Mac OS X. Btw I have upgraded to OS X 10.11.3.

**Comment by pi4r0n** [comment]
- Go to this URL http://selenium-release.storage.googleapis.com/index.html?path=2.48/ and save SafariDriver.safariextz
- Open Safari and drag and drop this plugin into it
- Safari will ask you **Are you sure you want to install the extension “WebDriver”?** Trust
- If you use SSL webpage it will keep asking you to trust the certificate so just save it permanently.

that all I had to do @roshanhadal

**Comment by roshanhadal** [comment]
It's not working for me still. Does it depend on Java version or anything else?

**Comment by pi4r0n** [comment]
@roshanhadal I have just updated to below versions, tried above steps and it works fine

> **OS:** OS X El Capitan 10.11.3
> **Safari:** Version 9.0.3 (11601.4.4)

Do you want to try upgrading as we;; and see if that fixes your problem

**Comment by roshanhadal** [comment]
Is it possible that we get on a skype call and you look at it? I may be missing something very silly and you can catch me.

**Comment by pi4r0n** [comment]
@roshanhadal, sure I can have quick look send me contact request on skype **pi4r0n**

**Comment by KevvvvyP** [comment]
Hi @roshanhadal , did you ever find a fix? I'm having the same issue, followed the steps above with no success.

**Comment by ddavison** [comment]
@KevvvvyP weirdly enough, i was getting this issue too.  after I restarted the browser, it worked fine (to the point where I right click Safari in the dock, click `Quit`, then restart Safari.

**Comment by roshanhadal** [comment]
@KevvvvyP sorry! I was away and couldn't respond in time. No, this problem hasn't gone away for me. Maybe you, I and @pi4r0n can get on with a Skype call and discuss this issue. Let me know your timezones and suitable time for the call. I am in IST. @KevvvvyP send me your Skype id.

**Comment by ramesh1588** [comment]
@roshanhadal I am facing the same issue, did you find any fix for the same? thanks, Ramesh.

**Comment by roshanhadal** [comment]
@ramesh1588 Nope. I am still having issues.

**Comment by pi4r0n** [comment]
@roshanhadal / @KevvvvyP I am available this Sunday to have quick Skype session if you still want to look at it ??

**Comment by divyaef16** [comment]
Am also facing the same issue unable to establish the connection with safari.I tried ut all possible things.
i am using selenium with C#.Included the safari extz in safari browser still facing the issue.Browser is getting opened that it gets opened from c:\\file......
Please give me some solution to this

**Comment by divyaef16** [comment]
hi @roshanhadal  did u find a fix for the same

Thanks divya

**Comment by roshanhadal** [comment]
@divyaef16 No, I haven't found the fix yet. In my case, Chrome and Firefox are my primary browsers. Currently, I am manually testing for Safari. I keep trying this but haven't seen success so far. Will update the day I find a fix for this problem.

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
