### ISSUE TITLE
[🐛 Bug]: deleteAllCookies method fails on Safari Driver

### ISSUE THREAD

**Issue by cocchiarocarl** [SeleniumHQ/selenium#13816]
### What happened?

While creating the Safari WebDriver instance, if you call the method deleteAllCookies() right after the driver is created, the script hangs, no exception is thrown though.

### How can we reproduce the issue?

```shell
webDriver.get().manage().deleteAllCookies();
```

### Relevant log output

```shell
None
```

### Operating System

macOS Sonoma 14.4.1

### Selenium version

4.18.1

### What are the browser(s) and version(s) where you see this issue?

Safari 17.4.1

### What are the browser driver(s) and version(s) where you see this issue?

Builtin Safari Driver

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
Yes, I can reproduce this in Safari, but not in any of the other browsers. Please report this to Apple.
