### ISSUE TITLE
[🐛 Bug]: [Guice/ErrorInjectingConstructor]: SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.

### ISSUE THREAD

**Issue by sumitsg004** [SeleniumHQ/selenium#13828]
### What happened?

Hi Team, 

I am unable to run selenium tests in jenkins pipeline because of below error. 

1) [Guice/ErrorInjectingConstructor]: SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
12:42:35    (session not created: DevToolsActivePort file doesn't exist)
12:42:35    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 

Other details - 

12:42:35  Host info: host: 'java-11-xlarge-4zcsb', ip: '172.27.227.15'
12:42:35  Build info: version: '4.19.1', revision: 'abe0ee07dc'
12:42:35  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.198-187.748.amzn2.x86_64', java.version: '11.0.16'
12:42:35  Driver info: ChromeDriver
12:42:35  Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-proxy-server, --no-sandbox, --test-type, --window-position=0,0, chrome.switches, ignore-certificate-errors, --remote-allow-origins=*, --disable-dev-shm-usage], binary: /usr/bin/google-chrome, excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, download.default_directory: /root/workspace/SSK-Test-Pi..., download.prompt_for_download: false, profile.default_content_settings.geolocation: 2, profile.default_content_settings.location: 2, profile.default_content_settings.popups: 2}}}]}]

The code runs fine on local windows system. Only on linux system facing this issue

Even with latest selenium version facing this issue. 
[4.19.1](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/4.19.1)

Can someone help with this issue? this has been a blocker issue of us as unable to run any regression suites. Really appreciate if we get any help on this.  

### How can we reproduce the issue?

```shell
Code is pretty straight forward. 

driver = new ChromeDriver(options);
LOGGER.info("Chrome Driver launched successfully");
```

### Relevant log output

```shell
12:42:35  [[1;31mERROR[m] RunCukesTest.runScenario["Verify Favourites functionality", "Optional[BO user Test cases]"](1)  Time elapsed: 2.605 s  <<< FAILURE!
12:42:35  com.google.inject.ProvisionException: 
12:42:35  Unable to provision, see the following errors:
12:42:35  
12:42:35  1) [Guice/ErrorInjectingConstructor]: SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
12:42:35    (session not created: DevToolsActivePort file doesn't exist)
12:42:35    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
12:42:35  Host info: host: 'java-11-xlarge-4zcsb', ip: '172.27.227.15'
12:42:35  Build info: version: '4.19.1', revision: 'abe0ee07dc'
12:42:35  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.198-187.748.amzn2.x86_64', java.version: '11.0.16'
12:42:35  Driver info: ChromeDriver
12:42:35  Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--no-proxy-server, --no-sandbox, --test-type, --window-position=0,0, chrome.switches, ignore-certificate-errors, --remote-allow-origins=*, --disable-dev-shm-usage], binary: /usr/bin/google-chrome, excludeSwitches: [enable-automation], extensions: [], prefs: {credentials_enable_service: false, download.default_directory: /root/workspace/SSK-Test-Pi..., download.prompt_for_download: false, profile.default_content_settings.geolocation: 2, profile.default_content_settings.location: 2, profile.default_content_settings.popups: 2}}}]}]
```

### Operating System

System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.198-187.748.amzn2.x86_64', java.version: '11.0.16'

### Selenium version

4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver latest version

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
It has to be an environment setup issue if it works on your Windows machine but not on Linux. Most of the time, it is related to the browser not having an active display.

You should try to run the test with a headless browser. If it works, it will confirm the absence of a display. 

Check https://elementalselenium.com/tips/38-headless on how to install Xvfb and use it with your script. 

If you have more questions, please use the links below.
