### ISSUE TITLE
I have tried to run a node on the same machine as the hub and it connects fine

### ISSUE THREAD

**Issue by keesbosch1996** [SeleniumHQ/selenium#13826]
I have tried to run a node on the same machine as the hub and it connects fine

_Originally posted by @MaxxRK in https://github.com/SeleniumHQ/selenium/issues/10890#issuecomment-1195865879_
            
            
            Hi Maxx,
            
            I saw this topic, seems like I'm running into the exact same issue, did you manage to fix it?

**Comment by diemol** [comment]
If you face a problem, please create a new issue and fill out the template. Thank you.
