### ISSUE TITLE
Firefox 43.0 Auto-disables Selenium IDE

### ISSUE THREAD

**Issue by kojiromike** [SeleniumHQ/selenium#1382]
Firefox 43 [automatically disables unsigned add-ons](http://mzl.la/1J7Lcsp), including the Selenium IDE itself. The [wiki says](https://wiki.mozilla.org/Addons/Extension_Signing)

> Mozilla will begin requiring all extensions to be signed in order for them to be installable in Release and Beta versions of Firefox. Signing will be done through addons.mozilla.org (AMO) and will be mandatory for all extensions, regardless of where they are hosted.

That same wiki article describes the process for signing an add-on. Please sign the add on so that I can continue using it without workarounds.

**Comment by barancev** [comment]
Please upgrade Selenium IDE from the official Mozilla addon repository:
https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/

**Comment by kojiromike** [comment]
Thanks. Might I suggest that this isn't clear from reading http://docs.seleniumhq.org/projects/ide/ at the moment?
