### ISSUE TITLE
[🐛 Bug]: Selenium is not opening chrome version 123.0.6312.124; error: could not start a new session. Response code: 500. Message: Session not created: This version of chromedriver only supports  chrome version 114

### ISSUE THREAD

**Issue by pardhyumanbagga10** [SeleniumHQ/selenium#13824]
### What happened?

Unable to run script as browser is throwing 500

### How can we reproduce the issue?

```shell
install the chrome browser version 123.0.6312.124
Run the selenium script (selenium version 4.3.0)
```

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 123.0.6312.124 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Build info: version: '4.3.0', revision: 'a4995e2c09*'
```

### Operating System

macOS

### Selenium version

4.3.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 123.0.6312.124

### What are the browser driver(s) and version(s) where you see this issue?

Selenium use to get the current chrome version and run over it but in this case its not running

**Comment by diemol** [comment]
You need to upgrade to the latest Selenium version to get your drivers managed automatically.

**Comment by pardhyumanbagga10** [comment]
@diemol Issue is still there post updating selenium to newest version i.e 4.19.1
