### ISSUE TITLE
[🐛 Bug]: driver.quit doesn't kill all Chrome processes

### ISSUE THREAD

**Issue by nikitakovaliov92** [SeleniumHQ/selenium#13837]
### What happened?

there are a lot of chrome processes in the task manager tab. This is a reason why test-suite hangs and even can't be ended

### How can we reproduce the issue?

```shell
open task manager processes tab and run your tests-suite
bug: driver.quit doesn't kill chrome processes
```

### Operating System

Windows 10+

### Selenium version

latest

### What are the browser(s) and version(s) where you see this issue?

Chrome 124+

### What are the browser driver(s) and version(s) where you see this issue?

latest

**Comment by nikitakovaliov92** [comment]
[selenium.zip](https://github.com/SeleniumHQ/selenium/files/15024057/selenium.zip)
Run tests from attached project several times and look at the task manager Processes tab. There are a lot of Google Chrome items

**Comment by diemol** [comment]
@asolntsev, what does  `Selenide.closeWebDriver();` do?

**Comment by nikitakovaliov92** [comment]
@diemol  from javadoc

```
Close the browser if it's open.
NB! Method quits this driver, closing every associated window.
See Also:
WebDriver. quit()

**Comment by diemol** [comment]
Does this happen in any machine? 
I am trying to understand better because if this was an issue, I can imagine many more people reporting it.

**Comment by nikitakovaliov92** [comment]
> Does this happen in any machine? I am trying to understand better because if this was an issue, I can imagine many more people reporting it.

in my case it reproduces on Windows

>I can imagine many more people reporting it.

chrome 124 was released 4/16 so maybe not a lot of users have updated it yet

**Comment by diemol** [comment]
What happens if you try with Chrome 123? Or Chrome for Testing?

**Comment by nikitakovaliov92** [comment]
Chrome 123 works good

**Comment by vibes121** [comment]
I am facing same issue with v123 .

**Comment by asolntsev** [comment]
Just for the record, I cannot reproduce this problem in MacOS. Both Chrome 123 and 124 work well.

**Comment by diemol** [comment]
@nikitakovaliov92, could you please report this to the Chrome folks?

**Comment by nikitakovaliov92** [comment]
created issue for chrome team: https://issues.chromium.org/issues/336164423

@asolntsev i'm not sure about this comment because another users have the same issue as me on the Chrome 124+......
> Just for the record, I cannot reproduce this problem in MacOS. Both Chrome 123 and 124 work well.

**Comment by ashustovsky** [comment]
Works for me (Win 11, Chrome 124.0.6367.92, Driver: 124.0.6367.91)
1. Added argument: "disable-renderer-backgrounding"
2. Make this: Driver.Close(); Driver.Quit(); Driver.Dispose();

**Comment by RileyXX** [comment]
You need to call `driver.close()` before `driver.quit()` otherwise you get lingering chrome processes with high resource usage. This is an issue with recent chrome versions (124+).

**Comment by titusfortner** [comment]
According to the Chrome bug report, seems like only an issue when using `'--no-sandbox`?
Hopefully they fix this because you really shouldn't need to call both `close()` and `quit()` (and actually doing so should result in an error)

**Comment by Chihitempclaims** [comment]
Can you tell me which window version you are using?? i am using Windows 11 Pro edition and working fine in both single instances and multiple instances.
As i am using these chrome options:
op.add_argument('--disable-dev-shm-usage')
      op.add_argument("--disable-extensions")
        op.add_argument('--disable-gpu')
        op.add_argument('--no-sandbox')
        # op.add_argument('--headless')
        op.add_argument('--start-maximized')
        op.add_argument('--window-size=1920x1080')

**Comment by Chihitempclaims** [comment]
**Can you tell me which window version you are using?? i am using Windows 11 Pro edition and working fine in both single instances and multiple instances(multiprocessing). I didnt encounter any chrome background processes.
As i am using these chrome options:
op.add_argument('--disable-dev-shm-usage')
op.add_argument("--disable-extensions")
op.add_argument('--disable-gpu')
op.add_argument('--no-sandbox')
op.add_argument('--start-maximized')
op.add_argument('--window-size=1920x1080')

**Comment by titusfortner** [comment]
You shouldn't need most of those arguments unless you are also running headless, and even then you probably don't want --no-sandbox. Please read - https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md

**Comment by Chihitempclaims** [comment]
> According to the Chrome bug report, seems like only an issue when using `'--no-sandbox`? Hopefully they fix this because you really shouldn't need to call both `close()` and `quit()` (and actually doing so should result in an error)

in 124+ its working fine but as I remember for the previous versions it results in an error. I mostly encounter multiple chrome's background process in mostly VM's with (Windows 10 Enterprise). In linux systems it is working fine.

**Comment by ENY66** [comment]
I've been having this problem on Windows 10 with v125. The solution described by others here to call driver.close() before driver.quit() improved the situation, but did not solve it completely. Instead, removing chrome_options.add_argument("--no-sandbox") seems to have solved it.
