### ISSUE TITLE
[🐛 Bug]: Selenium 4 grid execution shows different user's execution even when clicked using the correct session name

### ISSUE THREAD

**Issue by rummitta** [SeleniumHQ/selenium#13831]
### What happened?

Hi Team,
We are using Selenium 4 grid for running our automation tests. Grid version we use is 4.15. We set up the execution session id as a combination of feature file name, scenario name, user name etc - so as to ensure that it is unique. However, when we have many parallel executions, the same selenium node spins up multiple chrome browser tabs (which is fine so that it can support multiple parallel executions). However, when the user clicks on the particular session by checking the correct session name, then the most currently active chrome tab's execution is visible - instead of the tab that the user has initiated. This is causing issues during monitoring of the execution when many executions run in parallel.
Attached is the screenshot of multiple tabs (marked as 1 and 2 in the screenshot) in the same node and also in the same screenshot, the session name is visible.
![image](https://github.com/SeleniumHQ/selenium/assets/142016616/33762c19-17a9-472e-a51c-1557903a3b87)
Please suggest how to deal with this issue.

Regards,
Rumki

### How can we reproduce the issue?

```shell
We can reproduce the issue by running more number of parallel executions than the number of replicas set for that grid.
```

### Relevant log output

```shell
No particular log needed because there is no issue during the execution. All executions run fine as expected. The issue is only during monitoring.
```

### Operating System

Selenium 4 Grid is on Linux amd64

### Selenium version

Selenium Java 4.6.0 for the code base and Selenium Grid version is 4.15

### What are the browser(s) and version(s) where you see this issue?

Client is testing mostly using Chrome browser

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Browser and driver version 119

### Are you using Selenium Grid?

4.15

**Comment by rummitta** [comment]
Additional Info:
For the grid that we r using, max sessions is 2 and replica is 8. This issue is observed when we trigger more scenarios in parallel - for example, if we trigger 28 scenarios together

**Comment by diemol** [comment]
Each Docker container has VNC and noVNC installed so that you can see the Live View. However, the Live View can only show one desktop at a time. If you have more than one browser running on the same container, several browsers will be seen on the same Live View. As you can see at the bottom of the Live View, other browsers are present, and one has the session you are looking for.

The solution for this is to use one container per session.
