### ISSUE TITLE
Unable to switch to embedded object

### ISSUE THREAD

**Issue by pcchandru3** [SeleniumHQ/selenium#1383]
We are having an HTML document embeded into object tag. I am not able to switch to this object to perform actions on the embeded document.

Code:
....
.
.
.
.
<object data="https://user.xxx.com/Account/Login/" />
<!DOCTYPE html
<html lang="en"
<head.........</head
<body
....
.
.
<input class="xxx" dname="yyy" type="text" value="" /
.
.
.

When I try to locate the element its not working, as I am unable to switch to this frame/object.
This works in Firefox, not working in chrome

**Comment by lukeis** [comment]
this is not reproducible the way described. please provide a test script and a real sample html file that can reproduce the issue.

Also chrome issues should be logged on the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by ddavison** [comment]
looksl ike it might be a dupe of #1333
