### ISSUE TITLE
[🐛 Bug]: Delete Cookies removes all cookies with the same name instead of deleting a provided Cookie

### ISSUE THREAD

**Issue by dmitryyukhnovets** [SeleniumHQ/selenium#13840]
### What happened?

RemoteWebDriver class has the following method:
```
 public void deleteCookie(Cookie cookie) {
            this.deleteCookieNamed(cookie.getName());
        }
```
It means that cookies are deleted by name, so if we have two cookies with the same name (but different other attributes) - we cannot remove only one of them.

**WebDriver version** 4.17.0
**Browser** Chrome
To reproduce the issue please see the code below.

### How can we reproduce the issue?

```shell
public static void main(String[] args) {

		ChromeDriver driver = new ChromeDriver();
		driver.get("https://google.com");
		int defaultCookiesSize = driver.manage().getCookies().size();
		System.out.println("Default cookies size :" + defaultCookiesSize);
		driver.manage().addCookie(new Cookie("test", "test"));
		System.out.println("Add one cookie:" + driver.manage().getCookies().size());
		Calendar c = Calendar.getInstance();
		c.add(Calendar.DAY_OF_YEAR, 2);
		Date date = c.getTime();
		Cookie cookie2 = new Cookie("test", "test2", "google.com", "/",date, true);
		driver.manage().addCookie(cookie2);
		System.out.println("Add another cookie:" + driver.manage().getCookies().size());
		Set<Cookie> cookies = driver.manage().getCookies();
		for (Cookie cookie : cookies) {
			if (cookie.getValue().equals("test2")){
				driver.manage().deleteCookie(cookie);
				System.out.println("Removed one cookie");
			}
		}
		int actualCookieSize = driver.manage().getCookies().size();
		System.out.println("Finally :" + actualCookieSize);
		System.out.println(actualCookieSize == defaultCookiesSize + 1);
		driver.quit();
	}
```

### Relevant log output

```shell
Default cookies size :2
Add one cookie:3
Add another cookie:4
Removed one cookie
Finally :2
false
```

### Operating System

MacOs

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 123.0.6312.124

### What are the browser driver(s) and version(s) where you see this issue?

The chromedriver version (122.0.6261.128)

### Are you using Selenium Grid?

no

**Comment by pujagani** [comment]
Hello! Thank you for sharing the details. 
I am not sure this is possible with W3C WebDriver specification https://www.w3.org/TR/webdriver2/#delete-cookie. I think this is possible in Selenium 5, using the W3C WebDriver BiDi specification https://w3c.github.io/webdriver-bidi/#command-storage-deleteCookies.

**Comment by diemol** [comment]
It seems BiDi will also match cookies only by name: https://w3c.github.io/webdriver-bidi/#match-cookie

You should raise this issue with https://github.com/w3c/webdriver-bidi and/or https://github.com/w3c/webdriver

**Comment by pujagani** [comment]
Thank you for checking!
I think this is the confusing part and the reason is because the one-liner and detailed description say different things.
However, 'https://w3c.github.io/webdriver-bidi/#get-matching-cookies' bit is mentioned in the details and that is what is implemented by the browsers too. This reminds me to add a test in our implementation as well.

![Screenshot 2024-05-07 at 6 40 24 PM](https://github.com/SeleniumHQ/selenium/assets/10705590/b85195eb-60d5-4064-be0a-29682101a21b)

It should be supported by browsers based on the WPT Tests https://github.com/web-platform-tests/wpt/blob/32fdd84c40/webdriver/tests/bidi/storage/delete_cookies/filter.py
