### ISSUE TITLE
Selenium 2.48.2 click does not work in Firefox 43.0

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#1384]
The click functionality does work for an element, when scroll to is required. 

by default click does not work when selenium need to scroll to the element.
 - if Browser is maximized it simed to be working.
 - if I manually scroll to the element so that it becomes visible it also works ....

I had to switch selenium version due to the Browser version. But the same code was working just fine in selenium 2.47.1

**Comment by jtwarrensr** [comment]
I think the issue is with Firefox 43.0 because I am having similar issues with Se IDE 2.9.0.  Firefox has disabled my controls completely.

**Comment by vveliev** [comment]
click does work... when you scroll to the element .... and it does scroll but it's "overscroll" ....

**Comment by hobson42** [comment]
To add to this, Firefox 43 under Ubuntu 14.04 appears to work fine, when loaded manually. If I load it using the Python selenium driver  I cannot click into a textarea within a form. 
Another surprise - I have Firebug (2.1.13) installed. If this is open, when I load the page, the clicks work fine. If I close Firebig, they still work - until I reload the page. Then they don't work, until I open Firebug again.

**Comment by JoaquinFB** [comment]
I have the same error that vveliev. after upgrade firefox browser versión to 43.0, I have needed update my selenium to 2.48, but the click function doesn't work.

**Comment by titusfortner** [comment]
@jtwarrensr, your issue is: #1399
Everyone else, your issue is: #1202
