### ISSUE TITLE
[🐛 Bug]:  org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash from unknown error: cannot determine loading status

### ISSUE THREAD

**Issue by Alex-Reif** [SeleniumHQ/selenium#13843]
### What happened?

Error during open the page.
Using selenium-grid in the docker.

selenium-hub: 4.19.1
selenium/node-chrome:123

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      
     chrome:
    image: selenium/node-chrome:latest
    container_name: node-chrome
    shm_size: 3gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=20

### How can we reproduce the issue?

```shell
ChromeOptions options = new ChromeOptions();
    options.addArguments("--no-sandbox");
    options.addArguments("--disable-dev-shm-usage");
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), (Capabilities) options);
    driver.get("any page");
```
```


### Relevant log output

```shell
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=123.0.6312.86)
Build info: version: '4.19.1', revision: 'abe0ee07dc'
```

### Operating System

macOS

### Selenium version

4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 123

### Are you using Selenium Grid?

Yes

**Comment by diemol** [comment]
Are you using an M1? Or an ARM machine?

**Comment by Alex-Reif** [comment]
Hi @diemol , I'm using ARM

**Comment by diemol** [comment]
You need to use the ARM images https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#experimental-mult-arch-aarch64armhfamd64-images

**Comment by Alex-Reif** [comment]
Hi @diemol , I have intel architecture and using SeleniumHQ/docker-selenium repository to run selenium-grid. But I anyway receive the following error:
org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
