### ISSUE TITLE
[🐛 Bug]: Selenium4 Microsoft Edge WebDriver unable to attach to existing webview2

### ISSUE THREAD

**Issue by MagdelineNg** [SeleniumHQ/selenium#13851]
### What happened?

 I am using Selenium Edge webdriver to connect to my existing WebView2 instance(already set system variable on my local machine for remote-debugging-port for the webview2 before webview2 launch and can confirm that the webview can be inspected in `edge://inspect`) launched by my Windows application, and am receiving the error below:

I have seen similar issues related to compatibility issues between the browser and edge driver, so I have set the edge options' `binary_location` to be ` "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\msedge.exe"`. 
![image](https://github.com/SeleniumHQ/selenium/assets/85625305/829057b7-794c-48a4-a5c3-3fb37308141c)

> selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: MicrosoftEdge=123.0.2420.97)

Raised this issue on https://learn.microsoft.com/en-us/answers/questions/1658689/selenium4-microsoft-edge-webdriver-unable-to-attac?page=1&orderby=Helpful&comment=answer-1510487#newest-answer-comment , but still facing same error for automating the webview

### How can we reproduce the issue?

```shell
import selenium
import subprocess
from selenium import webdriver
from selenium.webdriver.edge.options import Options as EdgeOptions

def run_cmd(cmd, **kwargs):
    try:
        return subprocess.run(f'cmd /c "{cmd}"', **kwargs)
    except Exception as e:
        print(f"Failed to run command:\n{cmd}")
        raise


def terminate_process(process_name):
    run_cmd(f'taskkill /IM "{process_name}" /F')
    
#Terminate all ms edge browsers
for app in ["msedge.exe"]:
    terminate_process(app)

    
edge_options = EdgeOptions()
edge_options.binary_location = r"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\msedge.exe" #not sure if the binary location is "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\msedgewebview2.exe" ?
edge_options.debugger_address = "localhost:9222"
edge_options.use_webview = True
edge_driver = webdriver.Edge(options=edge_options)  #throws error here
print(edge_driver.page_source)   #does not print
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\Users\mnxl\source\repos\id-desktop-sdk\source\automateWebView.py", line 62, in <module>
    edge_driver = webdriver.Edge(options=edge_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 207, in __init__
    self.start_session(capabilities)
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mnxl\source\repos\id-desktop-sdk\source\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: MicrosoftEdge=123.0.2420.97)
Stacktrace:
        GetHandleVerifier [0x00007FF6C4175B82+59842]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C4104AB2+220434]
        (No symbol) [0x00007FF6C3F2DCD7]
        (No symbol) [0x00007FF6C3F17F9F]
        (No symbol) [0x00007FF6C3F18E1F]
        (No symbol) [0x00007FF6C3F2E1CA]
        (No symbol) [0x00007FF6C3F0A801]
        (No symbol) [0x00007FF6C3F9DF60]
        (No symbol) [0x00007FF6C3F93B93]
        (No symbol) [0x00007FF6C3F6960E]
        (No symbol) [0x00007FF6C3F687CC]
        (No symbol) [0x00007FF6C3F691C1]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6C43258FC+1052188]
        (No symbol) [0x00007FF6C3FDFFC6]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6C408150C+37916]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6C4078E95+3493]
        Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6C4324865+1047941]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C410D2C1+255265]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C41085B4+235540]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C41086EB+235851]
        Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6C40FFEE1+201025]
        BaseThreadInitThunk [0x00007FF96C74257D+29]
        RtlUserThreadStart [0x00007FF96E7CAA58+40]
```

### Operating System

Windows 11 Version 22H2 (Build 22621.3296)

### Selenium version

selenium 4.15.0

### What are the browser(s) and version(s) where you see this issue?

Webview2 Edge browser - 123.0.2420.97 ; Local Edge browser - 124.0.2478.51 (Official build) (64-bit) 

### What are the browser driver(s) and version(s) where you see this issue?

Not sure where webdriver.edge() is getting my browser since I set binary_location

### Are you using Selenium Grid?

No.

**Comment by diemol** [comment]
Has this worked before or are you trying to figure out how to do it?

Why is the binary location the browser binary itself? Shouldn't it be the desktop app that contains the webview?

**Comment by MagdelineNg** [comment]
@djbrown I tested attaching Selenium webdriver on another app(Microsoft Teams) and it could print the page source. 
![image](https://github.com/SeleniumHQ/selenium/assets/85625305/63de08bc-eee0-40db-84f4-14ef920abf5d)


However, it does not work on the webview2 launched from my Windows application. 

For the browser binary, I followed https://learn.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?source=recommendations&tabs=python#choose-specific-browser-binaries and set it to `msedge.exe`

**Comment by diemol** [comment]
But that is to "Use WebDriver to automate Microsoft Edge", and you should check these docs: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver.

If you have more questions please use the links below.

**Comment by djbrown** [comment]
@MagdelineNg I guess you meant to Tag @diemol instead? 😅
