### ISSUE TITLE
OperaOptions class doesn't work in Opera 34

### ISSUE THREAD

**Issue by eugene159** [SeleniumHQ/selenium#1386]
C#

OperaOptions options = new OperaOptions();
options.AddUserProfilePreference("turbo.enabled", true);
options.AddUserProfilePreference("download.default_directory", "C:\\Downloads");
OperaDriver driver = new OperaDriver(options);
driver.Navigate().GoToUrl("http://www.google.com");

preferences file is not affected by the code
http://stackoverflow.com/questions/34254510/enable-opera-turbo-in-selenium-opera-webdriver

**Comment by barancev** [comment]
Please report this issue to the Opera driver tracker.
