### ISSUE TITLE
[🐛 Bug]: delete session from grid-url is not working

### ISSUE THREAD

**Issue by krishtoautomate** [SeleniumHQ/selenium#13864]
### What happened?

When session is deleted using grid url, it is not working.

`cURL --request DELETE 'http://localhost:5555/se/grid/node/session/<session-id>' --header 'X-REGISTRATION-SECRET;'
`

only working for node URI is used: `cURL --request DELETE 'http://<node-URL>/se/grid/node/session/<session-id>' --header 'X-REGISTRATION-SECRET;'
`

Im able to drain nodes using grid url but delete session api is not working for grid url

### How can we reproduce the issue?

```shell
create session and use below url to delete session:

`cURL --request DELETE 'http://localhost:5555/se/grid/node/session/<session-id>' --header 'X-REGISTRATION-SECRET;'
`

note: make sure to replace session-id
```

### Relevant log output

```shell
"value": {
    "message": "Unable to find handler for (DELETE) \u002fse\u002fgrid\u002fnode\u002fsession\u002f17e258ea-88aa-4ddd-9a86-45b2d8375a54",
    "error": "unknown command",
    "stacktrace": ""
  }
```

### Operating System

macOS Ventura

### Selenium version

4.19.0

### What are the browser(s) and version(s) where you see this issue?

NA

### What are the browser driver(s) and version(s) where you see this issue?

NA

### Are you using Selenium Grid?

4.19.0

**Comment by krmahadevan** [comment]
@krishtoautomate - If you would like to delete a session, then the correct URL would be (I am not using any registration secret here)

```shell
 cURL --request DELETE 'http://localhost:4444/session/a7b9b25e-0e9f-4d40-919c-874072d799b1' --header 'X-REGISTRATION-SECRET;'
```

**Comment by krishtoautomate** [comment]
The curl command i posted above is from selenium documentation grid end points page

**Comment by krmahadevan** [comment]
The curl command in the documentation page requires you to know the node to which the session was routed to. If that's not known and you would like to kill a session (without having to know where it was running on) then you would need to use the URL that I shared (This is the same URL that the `driver.quit()` when invoked via the `RemoteWebDriver` also uses)

**Comment by diemol** [comment]
I updated the docs to show how to delete the session using the main Grid URL.
