### ISSUE TITLE
[🚀 Feature]: Ability to overwrite files when using FileLogHandler

### ISSUE THREAD

**Issue by MJB222398** [SeleniumHQ/selenium#13860]
### Feature and motivation

I want to make use of FileLogHandler to output driver logs to the filesystem for the testing suite (one file per test). Currently this only supports appending logs to the file. I do not need to keep logs from previous test runs and would prefer to create new files each time so that I only have the relevant logs.

### Usage example

The solution could be as simple as having an overload constructor for the FileLogHandler:

`public FileLogHandler(string filePath, bool overwriteExisting)`

**Comment by nvborisenko** [comment]
It is good idea.

I am curious whether reserving `public FileLogHandler(string filePath, bool overwrite)` method signature is a good choice. What if in the future we will need one more boolean flag? For instance `deleteIfExists`, or `alwaysAppendNewLine`. We can make this configuration as a property, but usually properties reflect a state of an object... bad choice.

I vote for optional argument:
```csharp
public FileLogHandler(string filePath, bool overwrite = false)
```

In this case we should double-check whether introducing new optional argument is breaking change (it is not at compilation level, I am not sure about binary level).

@YevgeniyShunevych your input is highly appreciated.

**Comment by MJB222398** [comment]
Or the constructor could take an "options" object that could be extended whenever more configuration is required and then that way the constructor signature won't change after this point.

**Comment by YevgeniyShunevych** [comment]
Agree, that can be a useful ability.

Adding an extra optional parameter, such as `FileLogHandler(string filePath, bool overwrite = false)` is a breaking change at a binary level. But it can be avoided by overloading constructor, leaving old constructor `FileLogHandler(string filePath)` and adding a new one `FileLogHandler(string filePath, bool overwrite)`.

But if we really expect some other parameters in the future, then options class looks a better way. But anyway I would add the second constructor, considering a binary breaking change. 

```cs
public class FileLogHandler
{
    public FileLogHandler(string filePath)
        : this(filePath, FileLogHandlerOptions.Default)
    {
    }

    public FileLogHandler(string filePath, FileLogHandlerOptions options)
    {
        //...
    }
}

public sealed class FileLogHandlerOptions
{
    public static FileLogHandlerOptions Default { get; } = new FileLogHandlerOptions();

    public bool Override { get; init; }
}
```

**Comment by nvborisenko** [comment]
Thank you guys!

In summary, we should choose between:

1.
```csharp
ctor FileLogHandler(string filePath);
ctor FileLogHandler(string filePath, bool overwrite = false);
```
2.
```csharp
ctor FileLogHandler(string filePath);
ctor FileLogHandler(string filePath, FileLogHandlerOptions options);
```

The second option dictates to apply this good **pattern** (how to avoid breaking changes) anywhere! I don't think it is good idea, at least this pattern is not spread widely in BCL. Our class is pretty simple, we don't expect new "flags" (at least how I feel it). But the second option is CLS-compliant (lol, should we).

In any case user is able to implement his own `ILogHandler`. I prefer to be as simpler as possible here.

Just to confirm, is the following is a breaking change?
Before:
```csharp
ctor FileLogHandler(string filePath);
ctor FileLogHandler(string filePath, bool overwrite = false);
```
After:
```csharp
ctor FileLogHandler(string filePath);
ctor FileLogHandler(string filePath, bool overwrite = false, bool someOtherArg = false);
```
