### ISSUE TITLE
WebDriver.Timeouts setScriptTimeout for SYNCHRONOUS scripts?

### ISSUE THREAD

**Issue by sascanagl** [SeleniumHQ/selenium#1387]
We are having issues of the JavaScriptExecutor (WebDriver/RemoteWebDriver) not returning from executeScript if an action results in a new page during a synchronous script call.  Timeouts.setScriptTimeout says it only applies to asynchronous scripts with a registered callback function.  Can we not get timeouts built-in for synchronous javascript calls, too?  Currently, we have to implement our own timeout running in a separate thread.

**Comment by jleyba** [comment]
Can you provide a sample script that is triggering a new page to load before the script finishes?

One possibility is there's a race and the navigation is being triggered from an action prior to the executeScript command.

**Comment by sascanagl** [comment]
I cannot easily provide a script due to the nature of our data-driven framework.   But I can provide more details that might provide enough hints.   Though the question really is--can we not have built-in support for synchronous timeouts on executeScript?

The gory details are:
We do not use Selenium in most cases to perform the click.  Most often we use the Java AWT Robot.
First, we inject a javascript mouse event listener on the element to be clicked.  When the mouse-up or click listener is notified we set a global variable.  In our  Java code we have a waitForClick loop thread that  performs executeScript to read the state of that global variable.  If the global variable does not indicate "fired",  the Java thread sleeps a short while til we check again.  The problem arises when we call executeScript to check the global variable value and the click has been performed resulting in the page transition.  executeScript does not return and it does not throw an exception. Yes, there is likely some race condition happening internally that allows the script to get started,  but not finish. 
So,  without a settable timeout option like exists for asynchronous calls, we are forced to generate another thread to wrap the executeScript calls to catch these scenarios.. 
I can provide the snippets of javascript code for the listeners,  and for the global variable checker,  but I cannot do that until Friday or later as I am away from the office until then.

**Comment by sascanagl** [comment]
Actually,  some of this might help.  This is the code we use:
https://github.com/SAFSDEV/Core/blob/master/src/org/safs/selenium/util/DocumentClickCapture.java

Above to add event listeners and waitFor Click

https://github.com/SAFSDEV/Core/blob/master/src/org/safs/selenium/webdriver/lib/SearchObject.java

To executeScript.

This version of executeScript does NOT have our synchronous timeout wrapper on it as we are currently still testing it in another branch.

**Comment by barancev** [comment]
Sorry, it's close to impossible to understand thousands lines of your code :(

Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sascanagl** [comment]
I have tried to create a concise reproducible test case using public domain web content but have not been able to in a reasonable amount of time.  The issue seems to be that there needs to be some unknown amount of in-browser javascript processing resulting from the onClick event that allows this issue to occur.  We see it in the complex applications we are testing, but these are not available for external consumption.  

Also, I'm starting to think this may be a Chrome-only issue.  More long-running tests on the other browsers need to occur to confirm that.  

Independent of any of that, is there a specific reason for the pushback on the suggestion to provide an additional API call that supports timeouts on synchronous javascript calls?  That is really the intent of this issue/request.

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long period.
