### ISSUE TITLE
[🐛 Bug]: please re-open unsolved issue

### ISSUE THREAD

**Issue by trance-babe** [SeleniumHQ/selenium#13889]
### What happened?

Please re-open unsolved issue:

https://github.com/SeleniumHQ/selenium/issues/13885

### How can we reproduce the issue?

```shell
/
```

### Relevant log output

```shell
/
```

### Operating System

See other issue

### Selenium version

See other issue

### What are the browser(s) and version(s) where you see this issue?

See other issue

### What are the browser driver(s) and version(s) where you see this issue?

See other issue

**Comment by diemol** [comment]
We replied in the other comment, please read our replies and avoid opening new issues.
