### ISSUE TITLE
[🐛 Bug]: selenium exception: OpenQA.Selenium.WebDriverArgumentException: 'binary is not a Firefox executable'

### ISSUE THREAD

**Issue by trance-babe** [SeleniumHQ/selenium#13885]
### What happened?

Hi

When specifying a path to the geckodriver in Selenium in C# code like this:

```
FirefoxOptions options = new FirefoxOptions();
options.BrowserExecutableLocation = Application.StartupPath + "\\geckodriver\\geckodriver.exe";
IWebDriver driver = new FirefoxDriver(options);
```

I get following exception:

`OpenQA.Selenium.WebDriverArgumentException: 'binary is not a Firefox executable'`

The geckodriver developers say it's an issue in Selenium:

https://github.com/mozilla/geckodriver/issues/2178

Selenium installed package:

![afbeelding](https://github.com/SeleniumHQ/selenium/assets/166885027/126683ba-fab4-458d-acad-ba30a76204ee)

### How can we reproduce the issue?

```shell
Use the following code which will throw the exception. Copy geckodriver to "geckodriver" subfolder of the program executable and call it using the following code.


FirefoxOptions options = new FirefoxOptions();
options.BrowserExecutableLocation = Application.StartupPath + "\\geckodriver\\geckodriver.exe";
IWebDriver driver = new FirefoxDriver(options);
```

I get following exception:

`OpenQA.Selenium.WebDriverArgumentException: 'binary is not a Firefox executable'`

Visual Studio information:

Microsoft Visual Studio Community 2022
Version 17.9.6
VisualStudio.17.Release/17.9.6+34728.123
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA905
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.9.199.22661
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.9.199.22661
Azure App Service Tools v3.0.0

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.9.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
```


### Relevant log output

```shell
N/A
```

### Operating System

Windows 10 22H2

### Selenium version

Selenium.WebDriver 4.20.0 for C#

### What are the browser(s) and version(s) where you see this issue?

Firefox 125.0.2 (64-bits)

### What are the browser driver(s) and version(s) where you see this issue?

GeckoDriver 0.34.0

**Comment by nvborisenko** [comment]
@trance-babe you should use `options.BinaryLocation` property instead of `options.BrowserExecutableLocation`.

Moreover, selenium is able to manage webdriver binaries automatically via [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/).

**Comment by diemol** [comment]
What @nvborisenko says, `options.BrowserExecutableLocation` is to set the browser binary location.

**Comment by diemol** [comment]
Please read what we recommended above...

>options.BrowserExecutableLocation

Is to set the browser binary location. You need to use `options.BinaryLocation`.

**Comment by nvborisenko** [comment]
Please repeat the same with Trace log level. It would be helpful.

**Comment by nvborisenko** [comment]
I have executed the same code on my machine:

```csharp
FirefoxOptions options = new FirefoxOptions();
options.BinaryLocation = @"C:\Users\Nick\.cache\selenium\geckodriver\win64\0.34.0\geckodriver.exe";
using IWebDriver driver = new FirefoxDriver(options);
```

And it works, in logs I see:
```
11:36:45.878 TRACE SeleniumManager: Driver path: C:\Users\Nick\.cache\selenium\geckodriver\win64\0.34.0\geckodriver.exe
11:36:45.898 TRACE SeleniumManager: Browser path: C:\Users\Nick\.cache\selenium\firefox\win64\125.0.3\firefox.exe
```

As you can see `Browser path` is correct in my case, in comparison with yours:
```
2024-05-02 01:35:15.029 TRACE SeleniumManager: Driver path: C:\Users\gebruiker\.cache\selenium\geckodriver\win64\0.34.0\geckodriver.exe
2024-05-02 01:35:15.045 TRACE SeleniumManager: Browser path: F:\VISUAL STUDIO PROJECT\Lost In Trance\Lost In Trance\bin\Debug\geckodriver\geckodriver.exe
```

I assume you set browser path somehow else, may be via environment variables?..

**Comment by diemol** [comment]
I was having a look at the `FirefoxOptions` code, and both [`BinaryLocation` and `BrowserExecutableLocation`](https://github.com/SeleniumHQ/selenium/blob/5a7272eec98dfc5c4bc542956076804de8690056/dotnet/src/webdriver/Firefox/FirefoxOptions.cs#L103-L118) do the same:
`Gets or sets the path and file name of the Firefox browser executable.`. 

To set the GeckoDriver location, you need to set it in the service:
```csharp
var service = FirefoxDriverService.CreateDefaultService("path/to/your/gecko/binary"); 
IWebDriver driver = new FirefoxDriver(service);
```

**Comment by diemol** [comment]
Don't set the `BinaryLocation` nor the `BrowserExecutableLocation`, unless you want to use a specific browser binary. In your example, you are setting a GeckoDriver binary, and not a Firefox binary. So just don't set it. 

Just use the `FirefoxDriverService` example I provided above.

**Comment by diemol** [comment]
> And why can you set BinaryLocation to a chrome driver but not to a gecko driver? It doesn't make sense. There should be a standard way of doing things. This is really confusing.
> 
> For example, this code works:
> 
> ```
> ChromeOptions chromeOptions = new ChromeOptions();
> chromeOptions.BinaryLocation = Application.StartupPath + "\\chrome-headless-shell-win64\\chrome-headless-shell.exe";
> IWebDriver driver = new ChromeDriver(chromeOptions);
> ```

That is not ChromeDriver. It is the Chrome Headless browser. 
They are both working in the same way, `BinaryLocation` expects the browser binary path.

**Comment by diemol** [comment]
What happens if you only do:

```csharp
IWebDriver driver = new FirefoxDriver();
```

I don't know why your GeckoDriver local binary is returning that error.

**Comment by trance-babe** [comment]
FUCK YOU STUPID LOSER
THIS SOFTWARE IS A PIECE OF SHIT
NOTHING WORKS
