### ISSUE TITLE
[🐛 Bug]: InvalidArgumentException when clicking a standard file input web element.

### ISSUE THREAD

**Issue by PatrickFlaherty** [SeleniumHQ/selenium#13883]
### What happened?

I receive the following exception:
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=124.0.6367.78)

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
import time


# Initialize the WebDriver (e.g., ChromeDriver)
driver = webdriver.Chrome()

# Navigate to the webpage with the file upload button
driver.get("https://www.w3schools.com/howto/howto_html_file_upload_button.asp")

# Locate the file upload button (replace 'file-upload-button-id' with the actual ID or other attribute)
file_upload_button = driver.find_element(By.ID, "myFile")

# Simulate a click event on the button
file_upload_button.click()

time.sleep(10)
```

### Relevant log output

```shell
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=124.0.6367.78)
```

### Operating System

Windows 11

### Selenium version

Python

### What are the browser(s) and version(s) where you see this issue?

Chrome 124.0.6367.78

### What are the browser driver(s) and version(s) where you see this issue?

124.0.6367.78

**Comment by PatrickFlaherty** [comment]
Some debug:
Found chromedriver 124.0.6367.91 in PATH: C:\Python311\chromedriver.exe
chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
Output: "\r\r\n\r\r\nVersion=124.0.6367.91\r\r\n\r\r\n\r\r\n\r"
Detected browser: chrome 124.0.6367.91
Required driver: chromedriver 124.0.6367.91
Driver path: C:\Python311\chromedriver.exe
Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
Using driver at: C:\Python311\chromedriver.exe
Started executable: `C:\Python311\chromedriver.exe` in a child process with pid: 37556 using 0 to output -3
POST http://localhost:63150/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'args': []}}}}
Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"124.0.6367.91","chrome":{"chromedriverVersion":"124.0.6367.91 (51df0e5e17a8b0a4f281c1665dbd1b8a0c6b46af-refs/branch-heads/6367@{#984})","userDataDir":"C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\scoped_dir37556_530935752"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:63160"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"722f465dcdd8363009f5d9e02f33b7f5"}} | headers=HTTPHeaderDict({'Content-Length': '883', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63150/session/722f465dcdd8363009f5d9e02f33b7f5/url {'url': 'https://www.w3schools.com/howto/howto_html_file_upload_button.asp'}
Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63150/session/722f465dcdd8363009f5d9e02f33b7f5/element {'using': 'css selector', 'value': '[id="myFile"]'}
Remote response: status=200 | data={"value":{"element-6066-11e4-a52e-4f735466cecf":"f.6423CAD48C5C4730014F53EE0AF3696F.d.E76ACAFECAA5C6F06AAA27F105EC2F0F.e.29"}} | headers=HTTPHeaderDict({'Content-Length': '126', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request
POST http://localhost:63150/session/722f465dcdd8363009f5d9e02f33b7f5/element/f.6423CAD48C5C4730014F53EE0AF3696F.d.E76ACAFECAA5C6F06AAA27F105EC2F0F.e.29/click {}
Remote response: status=400 | data={"value":{"error":"invalid argument","message":"invalid argument\n  (Session info: chrome=124.0.6367.91)","stacktrace":"\tGetHandleVerifier [0x0049C113+48259]\n\t(No symbol) [0x0042CA41]\n\t(No symbol) [0x003208A3]\n\t(No symbol) [0x00357C63]\n\t(No symbol) [0x00380D9C]\n\t(No symbol) [0x00356E25]\n\t(No symbol) [0x00381034]\n\t(No symbol) [0x00399B9C]\n\t(No symbol) [0x00380B36]\n\t(No symbol) [0x0035570D]\n\t(No symbol) [0x003562CD]\n\tGetHandleVerifier [0x00756533+2908323]\n\tGetHandleVerifier [0x00793B4B+3159739]\n\tGetHandleVerifier [0x0053505B+674763]\n\tGetHandleVerifier [0x0053B21C+699788]\n\t(No symbol) [0x00436244]\n\t(No symbol) [0x00432298]\n\t(No symbol) [0x0043242C]\n\t(No symbol) [0x00424BB0]\n\tBaseThreadInitThunk [0x76B47BA9+25]\n\tRtlInitializeExceptionChain [0x771CBE3B+107]\n\tRtlClearBits [0x771CBDBF+191]\n"}} | headers=HTTPHeaderDict({'Content-Length': '841', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
Finished Request

**Comment by diemol** [comment]
I should have seen that you want to upload a file. I believe you need to add a line before clicking on the element:
```python
driver.find_element(By.ID, 'myFile').send_keys('file-path')
```

You can see a complete example at: https://elementalselenium.com/tips/1-upload-a-file

**Comment by PatrickFlaherty** [comment]
I added the line:
driver.find_element(By.ID, 'myFile').send_keys('file-path') (I see the file name next to the 'Choose Files' button)
I get the same failure: selenium.common.exceptions.InvalidArgumentException: Message: invalid argument

**Comment by diemol** [comment]
Did you use the actual file path? The code shown in the link I shared is working as it runs daily in GitHub Actions.

**Comment by PatrickFlaherty** [comment]
# Navigate to the webpage with the file upload button
driver.get("https://www.w3schools.com/howto/howto_html_file_upload_button.asp")

driver.find_element(By.ID,
'myFile').send_keys('c:\\awdsupport\\pdf\\pdf-sample.pdf')
driver.find_element(By.ID, 'myFile').click()

[image: image.png]


On Tue, Apr 30, 2024 at 9:30 AM Diego Molina ***@***.***>
wrote:

> Did you use the actual file path? The code shown in the link I shared is
> working as it runs daily in GitHub Actions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SeleniumHQ_selenium_issues_13883-23issuecomment-2D2085341245&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=TCOcQWIQwMcHpBnp41m5a2vzYoQNRkgcT6BsEHx9yCQ&m=hHPkLh-DokHbf7uvrZGj9Myll3nqcsHD-EITEGsrI1BzetYrzk2XJ3FoPQgYZrXW&s=9EAiS1zZb3Skl7w4v06s2e0LbPh2k0sGNO3ByibCQ0E&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHF35FC4UWAC3UHJJ2GUONDY76MGFAVCNFSM6AAAAABG5DG5T6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBVGM2DCMRUGU&d=DwMCaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=TCOcQWIQwMcHpBnp41m5a2vzYoQNRkgcT6BsEHx9yCQ&m=hHPkLh-DokHbf7uvrZGj9Myll3nqcsHD-EITEGsrI1BzetYrzk2XJ3FoPQgYZrXW&s=0hycwfE08019c0v0EWVKc4njdanZH-aZ777Roc2b95I&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

-- 


*For more information on how and why we collect your personal 
information, please visit our Privacy Policy 
<https://www.motorolasolutions.com/en_us/about/privacy-policy.html?elqTrackId=8980d888905940e39a2613a7a3dcb0a7&elqaid=2786&elqat=2#privacystatement>.*
