### ISSUE TITLE
[🚀 Feature]: `TracedCommandExecutor` better span name

### ISSUE THREAD

**Issue by felixscheinost** [SeleniumHQ/selenium#13905]
### Feature and motivation

We are trying to use OTel tracing to find bottlenecks in the integration tests in our codebase.

We are looking for example for inefficient traversal off large DOM structures, which could be improved using better XPath queries.

Currently all spans generated by Selenium look the same, they all have "command" as the span name. (https://github.com/SeleniumHQ/selenium/blob/17d927b596898f666b0377ab40afe05434c6d8df/java/src/org/openqa/selenium/remote/TracedCommandExecutor.java#L38) You have to click on them (in most GUIs) to view the command name in the span attributes which isn't very nice to quickly go through a big trace to find inefficiencies.

The [guide](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.31.0/specification/trace/api.md#span) says:

> The span name concisely identifies the work represented by the Span, for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation. The span name SHOULD be the most general string that identifies a (statistically) interesting class of Spans, rather than individual Span instances while still being human-readable. That is, "get_user" is a reasonable name, while "get_user/314159", where "314159" is a user ID, is not a good name due to its high cardinality. Generality SHOULD be prioritized over human-readability.

My read is that if following this guide making the span name more special would be a good idea. E.g. "screenshot", "setCurrentWindowSize", "findElement", ...

### Usage example

Make spans more readable. Instead of having:

 - command
 - command
 - command
 - command

I imagine

 - open
 - findElement
 - executeScript
 - screenshot

as an example.

**Comment by pujagani** [comment]
Hello!
Thank you for details. I agree with your suggestion here and I am glad that will help you use the OTel bit in Selenium better. Would be open to sending a PR? We are more than happy to receive contributions on this front! :)
