### ISSUE TITLE
Unable to launch browser

### ISSUE THREAD

**Issue by kumar7259** [SeleniumHQ/selenium#1390]
Unable to launch the browser with Selenium 2.48.2 with FF V42 & getting below error. Using JRE 1.8.
Is this compatible issue?
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1450315781398,"updateDate":1450315781398,"applyBackgroundUpdates":1,"skinnable":true,"size":24166,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0","maxVersion":"43.0"}],"targetPlatforms":[]}
1450322330421	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1450322330422	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"tFdw5wAh31By","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1444305949403,"updateDate":1444305949403,"applyBackgroundUpdates":1,"bootstrap":false,"size":2090442,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1450322330423	DeferredSave.extensions.json	DEBUG	Save changes
1450322330423	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1450322330423	addons.xpi-utils	DEBUG	Updating add-on states
1450322330429	addons.xpi-utils	DEBUG	Writing add-ons list
1450322330444	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1450322330444	addons.manager	DEBUG	Provider finished startup: XPIProvider
1450322330444	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1450322330445	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Starting provider: GMPProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: GMPProvider
1450322330454	addons.manager	DEBUG	Starting provider: PluginProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: PluginProvider
1450322330455	addons.manager	DEBUG	Completed startup sequence
1450322330915	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1450322330915	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1450322330915	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1450322331156	DeferredSave.extensions.json	DEBUG	Starting write
1450322331433	addons.repository	DEBUG	No addons.json found.
1450322331434	DeferredSave.addons.json	DEBUG	Save changes
1450322331440	DeferredSave.addons.json	DEBUG	Starting timer
1450322331454	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1450322331456	DeferredSave.extensions.json	DEBUG	Write succeeded
1450322331456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1450322331497	DeferredSave.addons.json	DEBUG	Starting write
1450322331510	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at Test.localStation.main(localStation.java:17)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1450315781398,"updateDate":1450315781398,"applyBackgroundUpdates":1,"skinnable":true,"size":24166,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0","maxVersion":"43.0"}],"targetPlatforms":[]}
1450322330421	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1450322330422	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"tFdw5wAh31By","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1444305949403,"updateDate":1444305949403,"applyBackgroundUpdates":1,"bootstrap":false,"size":2090442,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1450322330423	DeferredSave.extensions.json	DEBUG	Save changes
1450322330423	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1450322330423	addons.xpi-utils	DEBUG	Updating add-on states
1450322330429	addons.xpi-utils	DEBUG	Writing add-ons list
1450322330444	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1450322330444	addons.manager	DEBUG	Provider finished startup: XPIProvider
1450322330444	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1450322330445	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Starting provider: GMPProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: GMPProvider
1450322330454	addons.manager	DEBUG	Starting provider: PluginProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: PluginProvider
1450322330455	addons.manager	DEBUG	Completed startup sequence
1450322330915	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1450322330915	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1450322330915	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1450322331156	DeferredSave.extensions.json	DEBUG	Starting write
1450322331433	addons.repository	DEBUG	No addons.json found.
1450322331434	DeferredSave.addons.json	DEBUG	Save changes
1450322331440	DeferredSave.addons.json	DEBUG	Starting timer
1450322331454	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1450322331456	DeferredSave.extensions.json	DEBUG	Write succeeded
1450322331456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1450322331497	DeferredSave.addons.json	DEBUG	Starting write
1450322331510	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52'
System info: host: 'IE3BLT3VB2N62', ip: '192.168.6.19', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:117)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at Test.localStation.main(localStation.java:17)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1450315781398,"updateDate":1450315781398,"applyBackgroundUpdates":1,"skinnable":true,"size":24166,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0","maxVersion":"43.0"}],"targetPlatforms":[]}
1450322330421	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1450322330422	addons.xpi	DEBUG	Updating XPIState for {"id":"{D19CA586-DD6C-4a0a-96F8-14644F340D60}","syncGUID":"tFdw5wAh31By","location":"winreg-app-global","version":"15.1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":"chrome://vscore/content/ScriptFF.gif","icon64URL":null,"defaultLocale":{"name":"McAfee ScriptScan for Firefox","description":null,"creator":"McAfee, Inc.","homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","installDate":1444305949403,"updateDate":1444305949403,"applyBackgroundUpdates":1,"bootstrap":false,"size":2090442,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"1.5","maxVersion":"9.9"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1450322330423	DeferredSave.extensions.json	DEBUG	Save changes
1450322330423	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1450322330423	addons.xpi-utils	DEBUG	Updating add-on states
1450322330429	addons.xpi-utils	DEBUG	Writing add-ons list
1450322330444	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1450322330444	addons.manager	DEBUG	Provider finished startup: XPIProvider
1450322330444	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1450322330445	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1450322330445	addons.manager	DEBUG	Starting provider: GMPProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: GMPProvider
1450322330454	addons.manager	DEBUG	Starting provider: PluginProvider
1450322330454	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1450322330454	addons.manager	DEBUG	Provider finished startup: PluginProvider
1450322330455	addons.manager	DEBUG	Completed startup sequence
1450322330915	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1450322330915	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1450322330915	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1450322331156	DeferredSave.extensions.json	DEBUG	Starting write
1450322331433	addons.repository	DEBUG	No addons.json found.
1450322331434	DeferredSave.addons.json	DEBUG	Save changes
1450322331440	DeferredSave.addons.json	DEBUG	Starting timer
1450322331454	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1450322331454	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1450322331456	DeferredSave.extensions.json	DEBUG	Write succeeded
1450322331456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1450322331497	DeferredSave.addons.json	DEBUG	Starting write
1450322331510	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	... 7 more

**Comment by TeodorVasile** [comment]
I have the same problem with FFv 43.0 selenium webdriver 2.46.0

**Comment by jkervine** [comment]
For me this broke after firefox upgraded itself to 43.0 - using latest webdriver...

**Comment by TeodorVasile** [comment]
I've made it work now by updating to version 2.48.2 for selenium server standalone, selenium java.jar and selenium java srcs.jar

**Comment by kumar7259** [comment]
Worked fine after downgrade FF to 41

On Thursday 17 December 2015, TeodorVasile <notifications@github.com> wrote:

> I've made it work now by updating to version 2.48.2 for selenium server
> standalone, selenium java.jar and selenium java srcs.jar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/1390#issuecomment-165464825>
> .
>


-- 
Sent from iPhone 6+

**Comment by jkervine** [comment]
Also replacing firefox with firefox developer edition is one option.

**Comment by barancev** [comment]
Selenium 2.48.2 works well with Firefox 43:
![12 23 2015-14 16 10](https://cloud.githubusercontent.com/assets/617090/12004317/19f95cb0-ab61-11e5-8c90-19b3ca5070b2.png)
