### ISSUE TITLE
[🚀 Feature]: You should create real API documentation for WebDriverJS

### ISSUE THREAD

**Issue by kupietools** [SeleniumHQ/selenium#13915]
### Feature and motivation

I would like working documentation for WebDriverJS.

Looking for the WebDriverJS API, I clicked the link https://www.selenium.dev/selenium/docs/api/javascript/index.html found on https://github.com/SeleniumHQ/selenium/wiki.

It leads to a 404 error. 

So do https://www.selenium.dev/selenium/docs/api/, https://www.selenium.dev/selenium/docs/, https://www.selenium.dev/selenium/.

I can find no examples covering what I need to implement, and no documentation so I can write my own code. For instance, I can't find a code example of the type of wait I need. I found some that are close but they all use drastically different parameters in `driver.wait()` and I don't know how to adapt them to my purposes. Where is the documentation for what parameters `driver.wait()` accepts? Where is the list of methods I can use? Every google search simply returns a page with limited examples, not complete documentation, and none of the examples anyone chooses to provide is what I need. 

The "documentation" at https://www.selenium.dev/documentation/ does not provide a comprehensive list of methods or parameters available for use, and is in many place completely lacking Node code examples for the general areas it does cover. 

### Usage example

Ideally, I would be able to click on the link for WebDriverJs API documentation on https://github.com/SeleniumHQ/selenium/wiki, and it would lead to a usable page of documentation instead of a 404 error. I would use this to write the code that I need.

**Comment by pujagani** [comment]
@harsha509 might be able you guide you better regarding your concerns and possibly contribute too. Thank you!

**Comment by diemol** [comment]
Duplicate of #10185
