### ISSUE TITLE
Selenium  Firefox driver comes up in -silent instead -foreground mode in Linux

### ISSUE THREAD

**Issue by selenium-user1** [SeleniumHQ/selenium#1392]
Setup: selenium-server-standalone-2.40.0, Firefox v27.0, Linux

        FirefoxProfile fp = new FirefoxProfile();
        fp.setAcceptUntrustedCertificates(true);
        fp.setEnableNativeEvents(false);  
        driver = new FirefoxDriver(fp);  <-- Seems to be hanging here
        driver.manage().timeouts().implicitlyWait(TIMEOUT, TimeUnit.MILLISECONDS);

Automation would go fine for awhile and then intermittently don't see Firefox browser come up.  When look for the process on Linux, firefox is trying to come up in -silent instead -foreground.  If anybody has seen the above issues, please advise.  Thanks.

**Comment by barancev** [comment]
Selenium 2.40 is out of date. Please retest with 2.49 and request reopen if the issue is still actual.
