### ISSUE TITLE
[🐛 Bug]: setRect() or getRect()  does not work correctly

### ISSUE THREAD

**Issue by gkozien** [SeleniumHQ/selenium#13939]
### What happened?

In case user wants to set window size that is over maximum resolution size of the screen it is not setting it properly.
But if screen size is higher than desired size it's working as expected.

driver.manage().window().setRect({width: 1900, height: 970});
or:
await driver.manage().window().setRect({x:0, y:0, width: 1900, height: 970});

### How can we reproduce the issue?

```shell
Try to run same test without any external displays with Windows display scale set to 100% and then to 150%.

        it("Test window size after driver initialized", async () => {
            const driver: WebDriver = new Builder().forBrowser(Browser.CHROME).build();
            await driver.manage().window().setRect({x:0, y:0, width: 1900, height: 970});
            const sampleUrl: string = "https://www.google.com/";
            await driver.get(sampleUrl);
            const size: IRectangle = await driver.manage().window().getRect();
            const expectedWidth: number = 1900;
            const expectedHeight: number = 970;
            console.info(`actual width: ${size.width}`);
            console.info(`actual height: ${size.height}`);
            expect(size.width).to.equal(expectedWidth);
            expect(size.height).to.equal(expectedHeight);
        });

when working on external display it's passing:
actual width: 1900
actual height: 970

but when working just on laptop (without external displays) it's failing:
AssertionError: expected 1298 to equal 1900
Expected :1900
Actual   :1298

It's probably related with Windows -> Display Options -> Scale settings.
If set to other than 100%, for example - recommended 150% -> this problem was revealed.
```

### Relevant log output

```shell
AssertionError: expected 1298 to equal 1900
Expected :1900
Actual   :1298
```

### Operating System

Windows 10

### Selenium version

typescript "@types/selenium-webdriver": "4.1.1",

### What are the browser(s) and version(s) where you see this issue?

Chrome  Version 124.0.6367.158 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 124.0.6367.60

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
According to the [specification](https://w3c.github.io/webdriver/#set-window-rect), that behavior is expected.
