### ISSUE TITLE
[🐛 Bug]: Can't execute selenium-manager with npx

### ISSUE THREAD

**Issue by ylecuyer** [SeleniumHQ/selenium#13938]
### What happened?

selenium-manager isn't exposed in package.json bin and thus can't be executed with npx

### How can we reproduce the issue?

```shell
npx --package=selenium-webdriver@4.20.0 -c 'selenium-manager'
sh: 1: selenium-manager: not found
```
```


### Relevant log output

```shell
sh: 1: selenium-manager: not found
```

### Operating System

Linux

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

CLI

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
This would be eventually covered in https://github.com/SeleniumHQ/selenium/issues/11378
