### ISSUE TITLE
[🐛 Bug]: input.readArray is not find

### ISSUE THREAD

**Issue by danchaobing** [SeleniumHQ/selenium#13933]
### What happened?

In Java17, using selenium devtools, it was found that the input.readArray method does not exist.

<img width="1368" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/28771148/e11ccae1-93df-4cd9-aa5c-25e0ceb25644">

My pom.xml only import selenium-java 4.20.0 for selenium

<img width="669" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/28771148/f75dec5f-294a-42b9-9410-215f219e080a">

<img width="481" alt="image" src="https://github.com/SeleniumHQ/selenium/assets/28771148/aa294e42-74b7-409d-8ba6-4b3c19319149">

### How can we reproduce the issue?

```shell
1. Create java workspace, use java 17.0.9
2. Use Selenium 4.20.0
3. Create ChromeDevTools
3.1 this.chromeDevTools.createSession();
3.2 this.chromeDevTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
3.3 this.chromeDriver.get("https://www.google.com");
4. Run java workspace
```

### Relevant log output

```shell
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.openqa.selenium.devtools.v124.target.Target.getTargets(Target.java:150)

The following method did not exist:

    'java.util.function.Function org.openqa.selenium.devtools.ConverterFunctions.map(java.lang.String, java.util.function.Function)'

The calling method's class, org.openqa.selenium.devtools.v124.target.Target, was loaded from the following location:

    jar:file:/Users/user/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v124/4.20.0/selenium-devtools-v124-4.20.0.jar!/org/openqa/selenium/devtools/v124/target/Target.class

The called method's class, org.openqa.selenium.devtools.ConverterFunctions, is available from the following locations:

    jar:file:/Users/user/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.1.4/selenium-remote-driver-4.1.4.jar!/org/openqa/selenium/devtools/ConverterFunctions.class

The called method's class hierarchy was loaded from the following locations:

    org.openqa.selenium.devtools.ConverterFunctions: file:/Users/user/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.1.4/selenium-remote-driver-4.1.4.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.openqa.selenium.devtools.v124.target.Target and org.openqa.selenium.devtools.ConverterFunctions
```

### Operating System

macOS

### Selenium version

4.20.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 124

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 124.0.6367.201

**Comment by diemol** [comment]
You need to explicitly add Selenium's version to overwrite the version given by Spring.

See a [duplicated issue](https://github.com/SeleniumHQ/selenium/issues/13589#issuecomment-1951645955).

**Comment by danchaobing** [comment]
thank you! it's worked
