### ISSUE TITLE
Cookies use 'None' for session cookies and for permanent cookies

### ISSUE THREAD

**Issue by bringingheavendown** [SeleniumHQ/selenium#1393]
I am using python bindings for selenium webdriver.  The cookie dict uses None for the 'expiry' field for both session cookies and for permanent cookies.

**Comment by lukeis** [comment]
What's the issue? What would you expect the vale to be?

**Comment by bringingheavendown** [comment]
I expect the value to be different between session cookies and permanent
cookies because i want to throw out session cookies every session but want
to maintain permanent cookies from session to session

**Comment by lukeis** [comment]
can you provide a script / site to reproduce this with and which browser? This works fine for me (I see cookies with and without expiry appropriately).

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long period.
