### ISSUE TITLE
Cannot find elements of a iOS app page in appium inspector for Mac

### ISSUE THREAD

**Issue by sanatzzz** [SeleniumHQ/selenium#1394]
Hi all!
I am automating an iOS app using appium.
I can find most of all the elements in the app pages but there are certain pages that appium inspector cannot find. Instead the appium inspector shows elements of the previous page.

I can see the page i want to detect but cannot see the element names on the left hand side
![screen shot 2015-12-18 at 10 46 26 am](https://cloud.githubusercontent.com/assets/10496932/11890009/b736f9a2-a575-11e5-93a8-9c4c1940e889.png)
![screen shot 2015-12-18 at 10 47 34 am](https://cloud.githubusercontent.com/assets/10496932/11890010/b78dba62-a575-11e5-9e7d-5c6636ae8393.png)

If you see the first screenshot you will see table cells of electricity, gas, landline etc. I can see and find properties for all of this page's elements but when i go for the next page, lets say I click on electricity, i cannot see any property for any element(you can see it the second screenshot).

I tried providing the name of the Bill Pay button as it is the only element I want to use in the page but to no avail. I have tried giving various xpaths again to no success.

What is the problem here? is it the appium inspector? is it the app? or am i missing something?

**Comment by ddavison** [comment]
this should be filed with the [Appium team](https://github.com/appium/appium/issues) :smiley:
