### ISSUE TITLE
[🚀 Feature]:  Better compatibility with Appium

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#13949]
### Feature and motivation

We would like to improve the compatibility between Appium and Selenium java clients. As the first step it would make sense to avoid using reflection to access various private properties of selenium classes and only rely on public or protected interfaces.

### Usage example

Here is the list of changes needed to be done in order to enhance the compatibility:

### Increase the scope of private properties of the below classes to 'protected':

RemoteWebDriver -> capabilities

HttpCommandExecutor -> commandCodec

HttpCommandExecutor -> responseCodec

FluentWait -> clock
FluentWait -> timeout
FluentWait -> interval
FluentWait -> sleeper
FluentWait -> ignoredExceptions
FluentWait -> messageSupplier
FluentWait -> input

### Make public accessor for the property:

HttpCommandExecutor -> client

DriverService.Builder -> exe

**Comment by iampopovich** [comment]
@pujagani @diemol Is it sufficient within the scope of this task to only change access modifiers? For backward compatibility and to maintain the logic in the getter and setter methods for the protected fields of the classes, they need to be left unchanged

**Comment by pujagani** [comment]
I think so that should suffice.

**Comment by Delta456** [comment]
I think the issue can be closed as the PR which did the changes suggested here is now merged.

**Comment by mykola-mokhnach** [comment]
Thank you @pujagani 
Could you please inform us which selenium release includes (or will include) the above changes?

**Comment by Delta456** [comment]
The next monthly release should have the above changes.

**Comment by diemol** [comment]
@mykola-mokhnach you can also try out the nightly build https://www.selenium.dev/downloads/#nightly
