### ISSUE TITLE
[🚀 Feature]: =chromedriver is no longer running, so ChromeDriver is assuming that Chrome has crashed

### ISSUE THREAD

**Issue by jarven-he** [SeleniumHQ/selenium#13955]
### Feature and motivation

System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.3.1'
selenium-java:4.21.0
ChromeDriver： 125.0.6422.60
Chrome Browser：125.0.6422.61
I use the java - Dwebdriver. Chrome. Driver = / Users/hejiawen/app/chrome/chromedriver - jar / Users/hejiawen/app/firefox/selenium - server - standalone - 4.0.0 - alpha - 2. Jar access 127.0.0.1:4444 can create Chrome Session, Note that the chromedriver and Chrome versions match, but using code causes the following error: (The process started from chrome location /Users/hejiawen/app/chrome/chromedriver is no longer running,  so ChromeDriver is assuming that Chrome has crashed.)

### Usage example

        System.setProperty("webdriver.chrome.driver", "/Users/hejiawen/app/chrome/chromedriver");
        ChromeOptions options = new ChromeOptions();
        options.setBinary("/Users/hejiawen/app/chrome/chromedriver");
        options.addArguments("no-sandbox");
        options.addArguments("disable-dev-shm-usage");
        options.addArguments("disable-extensions");
        options.addArguments("disable-gpu");
        options.addArguments("remote-debugging-port=9222");
        var driver = new ChromeDriver(options);
        driver.get(loginUrl);

**Comment by joerg1985** [comment]
I think you should add -- to the argument name.
```
    options.addArguments("--no-sandbox");
    options.addArguments("--disable-dev-shm-usage");
    options.addArguments("--disable-extensions");
    options.addArguments("‐-disable-gpu");
    options.addArguments("--remote-debugging-port=9222");
```

**Comment by pujagani** [comment]
Also, "disable-gpu" option is not necessary (Refer https://issues.chromium.org/issues/40527919). You might want to use headless mode instead.

**Comment by diemol** [comment]
You are using a very old version of Selenium, please use the latest (4.21 at the moment), and let [Selenium Manager handle things](https://www.selenium.dev/documentation/selenium_manager/). 

If you still have issues, please open a new issue and fill out the template information.
