### ISSUE TITLE
Unable to navigate to site after firefox update to V43

### ISSUE THREAD

**Issue by simist** [SeleniumHQ/selenium#1395]
Hello Team , 

I was using selenium 2.46 and firefox 42 (Windows 7/8)  for my automation works. Today my firefox got updated to 43. After this my automation scripts are not working. Browser gets launched but the navigation to the site is not working. I tried the same after updating  with Selenium 2.48.2. But no response. 

Could anyone help.

Regards,

**Comment by jpmi1** [comment]
Hey what do you mean by site? As for me when I upgraded to Firefox 43 I had to do this to continute using Selenium IDE
>Override add-on signing (advanced users): You can override this setting by changing the xpinstall.signatures.required preference to false in the Firefox Configuration Editor (about:config page). Support is not available for any changes made with the Configuration Editor so please do this at your own risk.

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by aprabu2000** [comment]
Hello Team,

I'm also facing same problem after upgrading to FF43. Unable to navigate to any site either .net or Java or .Net using selenium protractor.
Same site loading directly from firefox, not loading only if we call from Selenium protractor. 
Hello @jpmi1 .. I override add-on signing as steps mentioned in your posts, but the firefox instance opened by selenium has "xpinstall.signatures.required preference to true".. 

Can someone help.

Thanks in advance..

**Comment by molsky** [comment]
Same here with RF & Selenium2Library with FF43, had to upgrade selenium python module to version 2.48.0 but then there is this issue #1202

**Comment by wolftian** [comment]
So do I encounter the same issue when I upgrade Firefox to 43.
It seems that Firefox Signature Checking may result in this.
Will we have any update for support Firefox 43?

**Comment by wolftian** [comment]
The issue does not exists after disable signature checking on Firefox.
While Firefox 44 will drop the setting and force enable addon signature, and then the solution may not work.

Then do we have a plan to sign the firefox webdriver?

**Comment by lukeis** [comment]
@wolftian the plan is to use Mozilla's driver:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

But since it is not a 1.0 yet, we're likely going to not have the ability to use webdriver with Firefox versions 44 - 46(?). That is *if* the require addon signature does ship in 44, but even if it doesn't ship there's other breaking changes in that release for the current SeleniumHQ driver.  Basically be prepared to freeze the version of firefox you have installed to 43 and then upgrade later after announcements are made that Marionette is GA with the release channel.

**Comment by barancev** [comment]
Selenium 2.48.0 does work well with Firefox 43.
![25-12-2015 23-33-48](https://cloud.githubusercontent.com/assets/617090/12004311/678be9da-ab60-11e5-966b-a7c1073805fb.png)
