### ISSUE TITLE
Selenium IDE Export Capybara/RSpec

### ISSUE THREAD

**Issue by xevix** [SeleniumHQ/selenium#1396]
Howdy.

I was wondering if it makes sense to add Capybara/RSpec export support to Selenium IDE. This would lower the barrier to entry for non-technical folks to write tests for our setup at work, which uses Capybara rather than standard Webdriver. There's a great similarity in Capybara and Webdriver, since Capybara just wraps Webdriver (I believe), and converting standard rspec `it` to `feature` is fairly trivial.

If this makes sense, I'd like to work on it. Please let me know what you think. Thanks!

**Comment by samitbadle** [comment]
Hi Alejandro,

Please do so. If you need help, feel free to poke me.

Cheers,
Samit

**Comment by xevix** [comment]
Great! Thanks for getting back to me. I'll start having a look at the general codebase. If you have any good hints or appropriate links, please help me by sharing them.

**Comment by xevix** [comment]
@samitbadle Took me a while to clone the repo due to timeouts. Ended up doing a shallow clone, then unshallowing:

```
git clone --depth 1 git@github.com:SeleniumHQ/selenium.git
cd selenium
git pull --unshallow
```

I don't know how to specifically build the IDE, but I tried:

```
$ ./go //ide:selenium-ide-multi

Building: //ide/main:ide-auto-complete as build/ide/main/SeleniumIDEGenericAutoCompleteSearch.xpt
Falling back to ide/main/prebuilt/main/SeleniumIDEGenericAutoCompleteSearch.xpt
Preparing: //ide/main:selenium-ide as build/ide/main/selenium-ide.xpi
Preparing: //ide/plugins/csharp-format:csharp-format as build/ide/plugins/csharp-format/csharp-format.xpi
Preparing: //ide/plugins/java-format:java-format as build/ide/plugins/java-format/java-format.xpi
Preparing: //ide/plugins/python-format:python-format as build/ide/plugins/python-format/python-format.xpi
Preparing: //ide/plugins/ruby-format:ruby-format as build/ide/plugins/ruby-format/ruby-format.xpi
Preparing: //ide:selenium-ide-multi as build/ide/selenium-ide-multi.xpi
```

I wasn't really sure where to start with https://github.com/SeleniumHQ/selenium/wiki/Building-SeIDE. I've never developed a Firefox extension before, so should I just go through that first? The wiki page mentions SVN, so I figure it has not been updated in quite some time, is there newer information available?

Thanks!

**Comment by xevix** [comment]
Additionally, I tried adding the proxy as specified in the wiki instructions, but when I start Firefox as the dev profile, the extension doesn't seem to be installed nor prompt for installation, though it's getting picking up in the console.

```
1452154887061	addons.xpi	INFO	Mapping {a6fd85ed-e919-4a43-a5af-8da18bda539f} to /Users/myuser/selenium/ide/main/src
```

**Comment by dunban1** [comment]
Was any more work done on this? You could just create a formatter (example: http://elementalselenium.com/tips/6-export-from-selenium-ide) and add that to the prepackaged formatters in the project (https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/ruby-format/src/content/formats/ruby-wd-rspec.js) or you contribute to this project https://github.com/davehunt/selenium-ide-webdriver-backed-formatters
If you're looking for an example of someone who created their own formatter, I recommend looking at what this guy did:
http://www.techdarkside.com/generating-rspec-tests-with-selenium-ide

**Comment by xevix** [comment]
@dunban1 I wasn't able to make any progress because I wasn't able to get answers to my questions above.

Thanks for the links to the formatters. The company I was working for that wanted this feature I no longer work for, so it may be some time before I work on this.

**Comment by henrytseng** [comment]
+1

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
