### ISSUE TITLE
[🐛 Bug]: Running chrome driver with --remote-debugging-pipe makes dev_tools unavailable in ruby

### ISSUE THREAD

**Issue by tubaxenor** [SeleniumHQ/selenium#13979]
### What happened?

Passing `--remote-debugging-pipe` as chrome driver options removes `debuggerAddress` setting and cause `driver.devtools` to raise error.

This is expected behavior in chromedriver: https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/test/run_py_tests.py#5959

### How can we reproduce the issue?

```shell
require 'selenium-webdriver'
require 'selenium/devtools'

options = Selenium::WebDriver::Chrome::Options.new
options.add_argument('--headless')
options.add_argument('--remote-debugging-pipe')
driver = Selenium::WebDriver.for :chrome, options: options

driver.devtools

# => undefined method `[]' for nil (NoMethodError)
# "http://#{capabilities['goog:chromeOptions']['debuggerAddress']}"
# ^^^^^^^^^^^^^^^^^^^
```

### Relevant log output

```shell
3.3.1 :011 > options = Selenium::WebDriver::Chrome::Options.new
3.3.1 :012 > options.add_argument('--headless')
3.3.1 :013 > options.add_argument('--remote-debugging-pipe')
 => ["--headless", "--remote-debugging-pipe"]
3.3.1 :014 > driver = Selenium::WebDriver.for :chrome, options: options
 => #<Selenium::WebDriver::Chrome::Driver:0xf9e36fa01383a60 browser=:chrome_headless_shell>
3.3.1 :015 > driver.devtools
(irb):15:in `<main>': undefined method `[]' for nil (NoMethodError)

          "http://#{capabilities['goog:chromeOptions']['debuggerAddress']}"
                                                      ^^^^^^^^^^^^^^^^^^^
3.3.1 :016 >
```
```


### Operating System

macOS

### Selenium version

selenium-webdriver v4.21.0, selenium-devtools v0.125.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 125.0.6422.61

### What are the browser driver(s) and version(s) where you see this issue?

Same as chrome

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
@tubaxenor, then do not add the flag? If it is the expected behavior, we cannot do much about it.

**Comment by tubaxenor** [comment]
I see, but still wondering if there a way to obtain devtools connection from pipe...

The best I can get is the source code here: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_pipe_handler.cc

Which seems like it's using internal thread to make the connection but would like to have some 👀 to double check there is not much we can do before closing this issue 🙇

**Comment by diemol** [comment]
You should probably reach out to the Chrome team to find out if there is a way to do that.
