### ISSUE TITLE
Unable to use IEdriver on windows 10

### ISSUE THREAD

**Issue by zlepper** [SeleniumHQ/selenium#1398]
command I use to start selenium IEdriver:
```
java -jar selenium-server-standalone-2.48.2-ie.jar -port 4445 -Dwebdriver.ie.driver=.\IEDriverServer.exe
pause
```
This works on fine on windows 7, and my tests executes as they are supposed to. 
However on windows 10 it's a bit more odd. 

IE opens
IE loads page
IE fails at clicking button

I have checked:
Security settings are correct
Zoom is 100%
Reg key is set
Chromedriver on the windows 10 computer works.

**Comment by jimevans** [comment]
I run literally hundreds of tests every day using the IE driver on Windows 10. The problem you're describing is not a global issue, encountered by every user of the IE driver on Windows 10. You'll need to provide more information about the page being automated.

**Comment by zlepper** [comment]
The button that fails at being clicked is bound using the knockout tap event like such:
```
data-bind="tap: helpers.openAuthenticateBox"
```

There are no errors in the console when ti happens, and the test doesn't crash, but seems to actually execute the click event. Except it just doesn't propagate to the page. 


If you could tell me what more info you need I will be glad to provide it.

**Comment by jimevans** [comment]
A link to a page demonstrating the issue would be the best option. It would also be helpful to know what capabilities you've requested when instantiating the driver. Remember that, by default, the IE driver is very sensitive to window focus issues. As additional data points, you could also try using the `requireWindowFocus` capability, or turning off native events. See your language bindings' documentation for how to set those settings.

**Comment by jimevans** [comment]
Four weeks since last contact with original issue reporter. Closing due to no response.
