### ISSUE TITLE
Selenium IDE blocked by Firefox 43.0.1 because it is not signed.

### ISSUE THREAD

**Issue by git-hub-user** [SeleniumHQ/selenium#1399]
Today, my installation of Firefox was upgraded to 43.0.1.

After restart, Selenium IDE (and some other add-ons) had been disabled, because of a missing add-on signature, referring to [Add-on signing in Firefox](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox). Developers are directed to [Signing and distributing your add-on](https://developer.mozilla.org/en-US/Add-ons/Distribution) from there.

An attempt to install the latest version from the [Selenium IDE add-on page](https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/?src=search#id=2079) is also blocked. The "+ Add to Firefox" button has an alarming yellow/orange color and clicking it will invoke a pop-up message from the address bar stating that Firefox has prevented this website from asking me to install software on my system (the actual message is in Dutch, so I have translated it.)

Please, provide a signed release of the Selenium IDE add-on, as I want to use is, but do not want to swith of the xpinstall.signatures.required preference in about:config.

**Comment by lukeis** [comment]
please install the latest version in AMO:
https://addons.mozilla.org/en-us/firefox/addon/selenium-ide/

**Comment by stefanoborini** [comment]
This is apparently not solved when using python to run selenium tests. It is my understanding that the webdriver.xpi is shipped within the selenium package, and gets installed in the profile on startup (see `selenium.webdriver.firefox.firefox_profile.py`)
