### ISSUE TITLE
[🚀 Feature]: Convenience methods for BiDi

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#13991]
### Feature and motivation

Java & Python are missing convenience methods for enabling BiDi.

Right now we have....
.NET — options.UseWebSocketUrl = true
Ruby — options.web_socket_url = true
Python — options.enable_bidi = True
JS — enableBidi()
Java - enableBidi()

Should we update everything to use `enableBiDi()` name?

### Usage example

```
options.enableBiDi(true)
```

**Comment by titusfortner** [comment]
@pujagani I'm guessing we don't have a good reason for not adding it to java, yet?

**Comment by pujagani** [comment]
Thank you for bringing this up. Actually we can add it.

**Comment by pujagani** [comment]
"options.enableBiDi(true)" - @titusfortner  Should the user need to pass in true? Isn't `enableBidi()` sufficient?

**Comment by titusfortner** [comment]
@pujagani  I thought the other methods in Java Options that are boolean require passing in true/false.
So, we should do whatever matches the rest of our code.

**Comment by pujagani** [comment]
That is a fair point. Though the naming, in that case, is like ` setEnableDownloads(boolean enableDownloads)`. I was thinking if the name is `enableBiDi`, then that means just enable it. But if we want to set a value then the name should be such. What do you think?

**Comment by titusfortner** [comment]
If setXX(boolean) is the pattern, then we should follow that, though I agree it seems a bit much. @diemol any opinions on our conventions here?

**Comment by diemol** [comment]
I am not sure. If we want to set a property or a value, I like the `setXYZ` pattern, but if we want to enable a feature, I prefer the `enableXYZ` pattern.

This is to be said, I saw `setEnableDownloads` too late; it was already released. I would have done `enableDownloads`.

**Comment by pujagani** [comment]
Thank you folks. I think I will go with `enableBiDi`.

**Comment by pujagani** [comment]
Present in python https://github.com/SeleniumHQ/selenium/commit/a51ddee3b10e4e0708f6f936668420bfccc72275
