### ISSUE TITLE
Decode JSON error when accepting alert

### ISSUE THREAD

**Issue by KevanLocqus** [SeleniumHQ/selenium#1401]
Python : 3.4.3
Browser: Phantomjs 2.0
Selenium 2.48.0
OS: Ubuntu 15.10

    File ".../python3.4/site-packages/selenium/webdriver/common/alert.py", line 80, in accept
        self.driver.execute(Command.ACCEPT_ALERT)
    File ".../site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
        self.error_handler.check_response(response)
    File ".../site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
        value = json.loads(value_json)
    File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
        return _default_decoder.decode(s)
    File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)

and the Value of value_json in errorhandler.py

    Invalid Command Method - {"headers":{"Accept":"application/json","Accept-          Encoding":"identity","Connection":"close","Content-Length":"53","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:40849","User-Agent":"Python-urllib/3.4"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"d92b7540-a842-11e5-a4fd-77f9d4726c54\"}","url":"/accept_alert","urlParsed":{"anchor":"","query":"","file":"accept_alert","directory":"/","path":"/accept_alert","relative":"/accept_alert","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/accept_alert","queryKey":{},"chunks":["accept_alert"]},"urlOriginal":"/session/d92b7540-a842-11e5-a4fd-77f9d4726c54/accept_alert"}

In the error handler [this line](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L99) doesn't always return a valid json string

**Comment by barancev** [comment]
Please report this issue to the PhantomJS driver tracker:
https://github.com/detro/ghostdriver
