### ISSUE TITLE
[🐛 Bug]: Selenium - Java: driver.getWindowHandles() - Timeout exception

### ISSUE THREAD

**Issue by MobinSelenium** [SeleniumHQ/selenium#14024]
### What happened?

Unable to retrieve the window handle IDs of the chrome browser tabs.

### How can we reproduce the issue?

```shell
I have tried below code in intelliJ tool and getwindowhandles() is not working at below system configuration. The same code in windows 10 machine is working fine. 

I have tried with driver.switchTo().window(1) but no luck. It is getting struck at getwindowhandles() and after sometime, it is throwing timeout exception.

In below code, please launch any url where you can try to open another tab and try to get the windowhandleid of 2nd tab. Below code will launch the url(initially launched Google.com & in the same tab, opening the YouTube.com) but will not open another tab.

Main.java:
package org.example;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.Set;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
public class Main {
    public static void main(String[] args) throws InterruptedException {
        //TIP Press <shortcut actionId="ShowIntentionActions"/> with your caret at the highlighted text
        // to see how IntelliJ IDEA suggests fixing it.
        System.out.println("Hello and welcome!");

        // Replace with your WebDriver implementation (e.g., ChromeDriver)
        System.setProperty("webdriver.chrome.driver", "/pathofchromedriver/Downloads/chromedriver");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("user-data-dir=" + "/pathofchromedriver/Pictures/Profile");
        options.addArguments("--remote-allow-origins=*");
        WebDriver driver = new ChromeDriver(options);

        // Open a website (optional, for demonstration)
//      driver.get("https://www.google.com/");
        driver.navigate().to("https://www.google.com/");
        Thread.sleep(5000);
        // Simulate opening a new window (optional, for demonstration)
        driver.navigate().to("https://www.youtube.com/");
        Thread.sleep(5000);
        System.out.println("Number of open single window: " + driver.getWindowHandle());

//        // Get all window handles
        Set<String> windowHandles = driver.getWindowHandles();
        System.out.println("Number of open windows: " + windowHandles.size());

        // Close the browser (optional)
        driver.quit();
    }

    private static Object driver() {
        return null;
    }

}

pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>windowhandlesTest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.141.59</version>
        </dependency>
    </dependencies>

</project>

System details:
Linux name.c.googlers.com 6.6.15-2rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2rodete2 (2024-03-19) x86_64 GNU/Linux
```

### Relevant log output

```shell
/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin/java -javaagent:/usr/local/google/home/mobinpeer/Documents/ideaIC-2023.3.1/idea-IC-233.11799.300/lib/idea_rt.jar=37907:/usr/local/google/home/mobinpeer/Documents/ideaIC-2023.3.1/idea-IC-233.11799.300/bin -Dfile.encoding=UTF-8 -classpath /usr/local/google/home/mobinpeer/IdeaProjects/windowhandlesTest/target/classes:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-api/3.141.59/selenium-api-3.141.59.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.141.59/selenium-chrome-driver-3.141.59.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.141.59/selenium-remote-driver-3.141.59.jar:/usr/local/google/home/mobinpeer/.m2/repository/net/bytebuddy/byte-buddy/1.8.15/byte-buddy-1.8.15.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/squareup/okhttp3/okhttp/3.11.0/okhttp-3.11.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar org.example.Main
Hello and welcome!
Starting ChromeDriver 124.0.6367.60 (8771130bd84f76d855ae42fbe02752b03e352f17-refs/branch-heads/6367@{#798}) on port 6112
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1716375059.848][WARNING]: This version of ChromeDriver has not been tested with Chrome version 125.
May 22, 2024 10:51:01 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Number of open single window: 4179F12C0467FFF0B1C9E7938C2CB6A0
[1716384702.513][SEVERE]: Timed out receiving message from renderer: 600.000
Exception in thread "main" org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=125.0.6422.76)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'mobincloud123.c.googlers.com', ip: '192.168.14.19', os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.15-2rodete2-amd64', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.76, chrome: {chromedriverVersion: 124.0.6367.60 (8771130bd84f..., userDataDir: /usr/local/google/home/mobi...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:38631}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 51be48a158288b1506c89eae41dfae6c
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:460)
	at org.example.Main.main(Main.java:35)

Process finished with exit code 1
```

### Operating System

Linux

### Selenium version

Selenium Java 3.141.59

### What are the browser(s) and version(s) where you see this issue?

Chrome 125.0.6422.76

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
We cannot address any issues in old versions. Please update to Selenium 4.21

**Comment by MobinSelenium** [comment]
Thanks for your quick response. I will update to 4.21 and will keep you posted.

**Comment by MobinSelenium** [comment]
Updated to Selenium 4 version:
 <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-java</artifactId>
        <version>4.21.0</version>
    </dependency>

Same issue as mentioned above.
**Error log:**

/usr/lib/jvm/java-1.17.0-openjdk-amd64/bin/java -javaagent:/usr/local/google/home/mobinpeer/Documents/ideaIC-2023.3.1/idea-IC-233.11799.300/lib/idea_rt.jar=44557:/usr/local/google/home/mobinpeer/Documents/ideaIC-2023.3.1/idea-IC-233.11799.300/bin -Dfile.encoding=UTF-8 -classpath /usr/local/google/home/mobinpeer/IdeaProjects/windowhandlesTest/target/classes:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-api/4.21.0/selenium-api-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-java/4.21.0/selenium-java-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/4.21.0/selenium-chrome-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/auto/service/auto-service-annotations/1.1.1/auto-service-annotations-1.1.1.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-chromium-driver/4.21.0/selenium-chromium-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-json/4.21.0/selenium-json-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-manager/4.21.0/selenium-manager-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v123/4.21.0/selenium-devtools-v123-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v124/4.21.0/selenium-devtools-v124-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v125/4.21.0/selenium-devtools-v125-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v85/4.21.0/selenium-devtools-v85-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/4.21.0/selenium-edge-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/4.21.0/selenium-firefox-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-http/4.21.0/selenium-http-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/dev/failsafe/failsafe/3.3.2/failsafe-3.3.2.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/4.21.0/selenium-ie-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.21.0/selenium-remote-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/guava/guava/33.2.0-jre/guava-33.2.0-jre.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/checkerframework/checker-qual/3.42.0/checker-qual-3.42.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/errorprone/error_prone_annotations/2.26.1/error_prone_annotations-2.26.1.jar:/usr/local/google/home/mobinpeer/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/semconv/opentelemetry-semconv/1.25.0-alpha/opentelemetry-semconv-1.25.0-alpha.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-api/1.38.0/opentelemetry-api-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-context/1.38.0/opentelemetry-context-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-exporter-logging/1.38.0/opentelemetry-exporter-logging-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-common/1.38.0/opentelemetry-sdk-common-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.38.0/opentelemetry-sdk-extension-autoconfigure-spi-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure/1.38.0/opentelemetry-sdk-extension-autoconfigure-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-api-incubator/1.38.0-alpha/opentelemetry-api-incubator-1.38.0-alpha.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-trace/1.38.0/opentelemetry-sdk-trace-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk/1.38.0/opentelemetry-sdk-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-metrics/1.38.0/opentelemetry-sdk-metrics-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/io/opentelemetry/opentelemetry-sdk-logs/1.38.0/opentelemetry-sdk-logs-1.38.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/net/bytebuddy/byte-buddy/1.14.15/byte-buddy-1.14.15.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-os/4.21.0/selenium-os-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/apache/commons/commons-exec/1.4.0/commons-exec-1.4.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/4.21.0/selenium-safari-driver-4.21.0.jar:/usr/local/google/home/mobinpeer/.m2/repository/org/seleniumhq/selenium/selenium-support/4.21.0/selenium-support-4.21.0.jar org.example.Main
Hello and welcome!
Number of open single window: 32668866B0007EA9C4266807A002E8DA
Exception in thread "main" org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.15-2rodete2-amd64', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [0cedf81fe4b2eb341434f90f93c29778, getWindowHandles {}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.76, chrome: {chromedriverVersion: 124.0.6367.60 (8771130bd84f..., userDataDir: /usr/local/google/home/mobi...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:38775}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:38775/devtoo..., se:cdpVersion: 125.0.6422.76, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 0cedf81fe4b2eb341434f90f93c29778
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:399)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute(JdkHttpClient.java:355)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:187)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:591)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:442)
	at org.example.Main.main(Main.java:35)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:382)
	... 11 more

Process finished with exit code 1

**Comment by MobinSelenium** [comment]
Absolutely, I can share the execution report along with the associated logs. Thanks!
