### ISSUE TITLE
[🐛 Bug]: Stack Trace printing out gibberish and spamming the console

### ISSUE THREAD

**Issue by Drygord** [SeleniumHQ/selenium#14047]
### What happened?

For months now this has been happening, even various versions of selenium and on different machines and operating systems.

Error messages print out non-nonsensical gibberish such as the following:

Couldn't find expand stack button. Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\Selenium\SPOTIFY.py", line 1334, in gmail_spotify_link_fetch
    expand_stack_button = Wait(d, stack_wait).until(EC.presence_of_element_located(("xpath",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6A73F12D2+311426]
	(No symbol) [0x00007FF6A725B572]
	(No symbol) [0x00007FF6A6F40A29]
	(No symbol) [0x00007FF6A6F814C1]
	(No symbol) [0x00007FF6A6F816F5]
	(No symbol) [0x00007FF6A6FB5FA7]
	(No symbol) [0x00007FF6A6F9D82F]
	(No symbol) [0x00007FF6A6F78910]
	(No symbol) [0x00007FF6A6FB3F75]
	(No symbol) [0x00007FF6A6F9D043]
	(No symbol) [0x00007FF6A6F76CAE]
	(No symbol) [0x00007FF6A6F763DA]
	(No symbol) [0x00007FF6A6F77BCB]
	GetHandleVerifier [0x00007FF6A741BDF2+486306]
	sqlite3_dbdata_init [0x00007FF6A7616F2B+595003]
	sqlite3_dbdata_init [0x00007FF6A7616104+591380]
	sqlite3_dbdata_init [0x00007FF6A7611831+572737]
	sqlite3_dbdata_init [0x00007FF6A7618615+600869]
	(No symbol) [0x00007FF6A7278EF9]
	(No symbol) [0x00007FF6A7269A27]
	(No symbol) [0x00007FF6A7269DA8]
	(No symbol) [0x00007FF6A724702A]
	BaseThreadInitThunk [0x00007FFE14AB7AC4+20]
	RtlUserThreadStart [0x00007FFE14FBA4E1+33]
	
This is completely useless information. I don't want it spamming my console. Make it optional, or better yet, disable it completely. This is not even useful for proper debugging.

### How can we reproduce the issue?

```shell
Just run the most recent version of selenium on any machine.
```

### Relevant log output

```shell
Couldn't find expand stack button. Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\Selenium\SPOTIFY.py", line 1334, in gmail_spotify_link_fetch
    expand_stack_button = Wait(d, stack_wait).until(EC.presence_of_element_located(("xpath",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF6A73F12D2+311426]
	(No symbol) [0x00007FF6A725B572]
	(No symbol) [0x00007FF6A6F40A29]
	(No symbol) [0x00007FF6A6F814C1]
	(No symbol) [0x00007FF6A6F816F5]
	(No symbol) [0x00007FF6A6FB5FA7]
	(No symbol) [0x00007FF6A6F9D82F]
	(No symbol) [0x00007FF6A6F78910]
	(No symbol) [0x00007FF6A6FB3F75]
	(No symbol) [0x00007FF6A6F9D043]
	(No symbol) [0x00007FF6A6F76CAE]
	(No symbol) [0x00007FF6A6F763DA]
	(No symbol) [0x00007FF6A6F77BCB]
	GetHandleVerifier [0x00007FF6A741BDF2+486306]
	sqlite3_dbdata_init [0x00007FF6A7616F2B+595003]
	sqlite3_dbdata_init [0x00007FF6A7616104+591380]
	sqlite3_dbdata_init [0x00007FF6A7611831+572737]
	sqlite3_dbdata_init [0x00007FF6A7618615+600869]
	(No symbol) [0x00007FF6A7278EF9]
	(No symbol) [0x00007FF6A7269A27]
	(No symbol) [0x00007FF6A7269DA8]
	(No symbol) [0x00007FF6A724702A]
	BaseThreadInitThunk [0x00007FFE14AB7AC4+20]
	RtlUserThreadStart [0x00007FFE14FBA4E1+33]
```

### Operating System

Windows 10

### Selenium version

python selenium version 4.21.0

### What are the browser(s) and version(s) where you see this issue?

both

### What are the browser driver(s) and version(s) where you see this issue?

most recent

### Are you using Selenium Grid?

no

**Comment by diemol** [comment]
You can always turn it off 
https://www.selenium.dev/documentation/webdriver/browsers/chrome/#log-level

You can also reach out to the Chrome team and ask for a more useful output in those cases.
