### ISSUE TITLE
ERROR:gl_surface_glx.cc(343)] glxQueryVersion failed - webdriver hangs

### ISSUE THREAD

**Issue by c0rnflex** [SeleniumHQ/selenium#1404]
Hi,
I'm running selenium grid 2.48.0 with centos7 nodes using xvfb, and latest chromedriver and stable chrome.

It seems like sometimes the chrome sessions fail to start and the webdriver is hung forever.
I found out it's related to these log entries:

> ./.com.google.Chrome.q72lh9/chrome_debug.log:[1:1:1208/140317:ERROR:image_metadata_extractor.cc(111)] Couldn't load libexif.
> ./.com.google.Chrome.q72lh9/chrome_debug.log:[18804:18804:1208/140317:ERROR:gl_surface_glx.cc(343)] glxQueryVersion failed
> ./.com.google.Chrome.q72lh9/chrome_debug.log:[18804:18804:1208/140317:ERROR:gl_surface_x11.cc(56)] GLSurfaceGLX::InitializeOneOff failed.
> ./.com.google.Chrome.q72lh9/chrome_debug.log:[18804:18804:1208/140317:ERROR:gpu_child_thread.cc(235)] Exiting GPU process due to errors during initialization

Couldn't find a resolution online.

Thanks

**Comment by lukeis** [comment]
for issues with chrome / chromedriver please log them with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
