### ISSUE TITLE
There is a bug in selenium webdriver/remote/index.js

### ISSUE THREAD

**Issue by debbiesrain** [SeleniumHQ/selenium#1405]
I was trying to make an instance of the integrated Selenium Server object inside the out-of-the-box Selenium Webdriver during run time. As I was studying the code I found this code written behind the scenes: 

File path &name: /node_modules/selenium-webdriver/remote/index.js
  
var serverUrl = url.format({
        protocol: 'http',
        hostname: !self.loopbackOnly_ && net.getAddress() || 
                      net.getLoopbackAddress(),  <---------------- this is the part that seems buggy to me
        port: port,
        pathname: self.path_
      });

Here's my server object instantiation:
var SeleniumServer = require('selenium-webdriver/remote').SeleniumServer;
var server = new SeleniumServer("../seleniumServer/selenium-server-standalone-2.48.2.jar", { loopback: false, port: 7055 });

QUESTION: the hostname logical && and || is vague, and therefore always results to the loopbackAddress? Can somebody clarify this or even agree?

Thanks.
Debbie

**Comment by jleyba** [comment]
`x && y || z` is like the ternary operator. If `x` is truthy, it evaluates to the value of `y`, otherwise `z`

**Comment by debbiesrain** [comment]
Thanks for the answer. I have to realize that this is Javascript and is very different from Java principles, However, even if I set the loopback=false then I am expecting for the net.getAddrëss() but yet it's always returning me the loopback 127.0.0.1

This is my instance:
var server = new SeleniumServer("../seleniumServer/selenium-server-standalone-2.48.2.jar", { loopback: false, port: 7055 });

In my console log, i can see that getAddress() is the IP address of my machine and is therefore the same as the loopback 127.0.0.1.

However, if I use a Linux machine, and the server is running in run time and set the builder to this:

$browser = new $driver.Builder()
            .usingServer(server.address())
            .withCapabilities($driver.Capabilities.firefox())
            .build();

My server.address() url is "http://10.1.26.60:4444/wd/hub" but I get the same error of "Unable to connect to host 127.0.0.1"

Can you please give me a suggestion what to do or check in the Linux machine? I appreciate it. Thanks.

Debbie
