### ISSUE TITLE
[🐛 Bug]: Getting error ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by AjinkyaMarathe7** [SeleniumHQ/selenium#14055]
### What happened?

I am accessing my application URL from RemoteWebdriver using selenium grid but getting error as Site Can't be reached we have tried opening the firewall port as well but still issue persists.
Browser used is Chrome.The nodes are linux machines.I have no access to grid server since it is maintained by other team.Any help would be appreciated.

### How can we reproduce the issue?

```shell
_driver.Value = new RemoteWebDriver(new Uri(TestContext.Parameters["remoteDriverUrl"]), chromeOptions.ToCapabilities(), TimeSpan.FromSeconds(600));
```

### Relevant log output

```shell
This Site can't be reached.
ERR_CONNECTION_REFUSED
```

### Operating System

Linux

### Selenium version

Selenium 4.1.0

### What are the browser(s) and version(s) where you see this issue?

Chrome v122.0

### What are the browser driver(s) and version(s) where you see this issue?

RemoteWebDriver Selenium Webdriver v4.1.0

### Are you using Selenium Grid?

4.18.1

**Comment by titusfortner** [comment]
Unfortunately, there's nothing for Selenium to fix here. There is some kind of issue on your network and you'll need to figure out who to talk to at your company to get it sorted.
