### ISSUE TITLE
[🐛 Bug]: `chrome`/`chromium` type break as of `@types/selenium-webdriver@4.1.23` 

### ISSUE THREAD

**Issue by Zidious** [SeleniumHQ/selenium#14068]
### What happened?

As of updating to use the `@latest` release of the `@types/selenium-webdriver` package [4.1.23](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69487). This appears to have introduced a type break. This issue doesn't appear on 4.1.22

Just curious if this was an intentional change?

### How can we reproduce the issue?

```ts
import webdriver from "selenium-webdriver";
import { Options } from "selenium-webdriver/chrome";

(async () => {
  const driver = await new webdriver.Builder()
    .forBrowser("chrome")
    .setChromeOptions(new Options().addArguments("--headless"))
    .build();

  await driver.get("https://www.google.com");
  //...
  await driver.quit();
})();
```

### Relevant log output

```
sandbox.ts:7:23 - error TS2345: Argument of type 'import("/Users/XXX/sandbox/node_modules/@types/selenium-webdriver/chromium").Options' is not assignable to parameter of type 'import("/Users/XXX/sandbox/node_modules/@types/selenium-webdriver/chrome").Options'.
  Type 'Options' is missing the following properties from type 'Options': setChromeBinaryPath, androidChrome, setChromeLogFile, setChromeMinidumpPath

7     .setChromeOptions(new Options().addArguments("--headless"))
```

Specifically: 

`Type 'Options' is missing the following properties from type 'Options': setChromeBinaryPath, androidChrome, setChromeLogFile, setChromeMinidumpPathts(2345)`

### Operating System

macOS Sonoma 14.4.1 

### Selenium version

4.21.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

124

**Comment by titusfortner** [comment]
For good or bad, we don't maintain the type definitions in this project. You'll want to discuss on DefinitelyTyped repo
