### ISSUE TITLE
[🐛 Bug]: Failure to receive the log of the network section from another tab

### ISSUE THREAD

**Issue by majidys** [SeleniumHQ/selenium#14063]
### What happened?

To test a web application, I need to open this application in two tabs.
I want to compare the network log sent in the first tab and the network log received in the second tab.
But when I use the `browser.get_log('performance')` command to get the network section log of the **second tab**, invalid values ​​are returned !

Meanwhile, if I open two separate browsers and use this command to receive the log, the sent and received values ​​are similar and the test result works correctly.

### How can we reproduce the issue?

```python
for indx in range(2):
        print('\n', colored(
            f" Operator {indx+1} : ", 'black', 'on_light_yellow', ['bold']), '\n')

        # 1 : May be in another tab because of another test so we have to go back to the first Tab
        browser.switch_to.window(tabs[indx])
        if indx==0 :
            # Open boarder and Draw a line
            try:
                ....

        network = browser.get_log('performance')
        for itm in network:
            Msg = itm['message']
            if "object-added" in Msg and "push" in Msg:
                if indx==0 :
                    drawnـdesigns.append(Msg)
                else :
                    designs_seen.append(Msg)
                
if drawnـdesigns==designs_seen :
        print(f"✅ 🎯 {doneFormat(f' The drawn shape (⬜) was ➡️sent and ⬅️received 👌 ')}")
```

### Relevant log output

```shell
--
```

### Operating System

win 10

### Selenium version

4.20

### What are the browser(s) and version(s) where you see this issue?

chrome 125.0.6422.141

### What are the browser driver(s) and version(s) where you see this issue?

last

### Are you using Selenium Grid?

-

**Comment by titusfortner** [comment]
I'm not looking at the code, but our browser logging implementations are not consistent right now, and we need to deprecate them when we move to bidi implementations. I'm pretty sure this method is just grabbing what chromedriver has collected, and I'm not sure how Google is managing browsing contexts within the driver. It'll need to be more explicit by the user in the future.

**Comment by diemol** [comment]
I am closing this due to the lack of activity.
