### ISSUE TITLE
[🐛 Bug]: It does not read the console log completely

### ISSUE THREAD

**Issue by majidys** [SeleniumHQ/selenium#14079]
### What happened?

When I use the `driver.get_log('browser')` command to read the console log. Cannot get the json values ​​displayed in the console.
And instead of that, it puts the word **object** in the output file or vscode console.
Sample log that the `driver.get_log('browser')` command cannot read:
![image](https://github.com/SeleniumHQ/selenium/assets/99164978/9b6b0bbd-8810-44a1-91ab-7f739d514f41)

### How can we reproduce the issue?

```shell
-
```

### Relevant log output

```shell
-
```

### Operating System

win 10

### Selenium version

4.20

### What are the browser(s) and version(s) where you see this issue?

chrome 125.0.6422.141

### What are the browser driver(s) and version(s) where you see this issue?

last

**Comment by majidys** [comment]
In other words, I need to be able to read the log marked in the picture, but this section cannot be read with the `driver.get_log('browser')`command.

![image](https://github.com/SeleniumHQ/selenium/assets/99164978/e24de606-b7c1-4b7c-99be-1d92a5fd093d)

**Comment by titusfortner** [comment]
The get log method right now is just reporting what the driver is providing so any issues are going to be from Google. 

We'll have a more robust approach available soon using webdriver bidi.
