### ISSUE TITLE
[🐛 Bug]: [rb] Dependency on the `logger` gem which will be removed in Ruby 3.5

### ISSUE THREAD

**Issue by Earlopain** [SeleniumHQ/selenium#14081]
### What happened?

Ruby is continuing its journey of bundling gems (see `base64`). Next on the chopping block: `logger` https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c

The easiest thing here would again to add it to just add it to the gemspec, I can make a PR for that if you wish. With `base64` there was an alternative solution but can't really do that here.

### How can we reproduce the issue?

```shell
Run with 3.4-dev
```

### Relevant log output

```shell
N/A
```

### Operating System

N/A

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by titusfortner** [comment]
PR would be great, thanks!
