### ISSUE TITLE
[🐛 Bug]: NoSuchDriverException for Windows app execution aliases

### ISSUE THREAD

**Issue by vlad8x8** [SeleniumHQ/selenium#14088]
### What happened?
The default way to run MS Teams desktop client (which is MSEdge-based app) is a Windows app execution aliass located at UserFolder\\AppData\Local\Microsoft\WindowsApps\ms-teams.exe)
Selenium Manager is failing on this file.
The issue started on Selenium 4.20 because of https://github.com/SeleniumHQ/selenium/blob/4ecc1033caa9995427c25d36befb70b8faae96d7/java/src/org/openqa/selenium/internal/Require.java
No issue with Selenium 4.19

`org.openqa.selenium.internal.Require.FileStateChecker#isFile` throws errors for Windows app execution aliases

### How can we reproduce the issue?
https://github.com/vlad-velichko/selenium-bug-14088

### Relevant log output

```shell
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: msedgedriver, error MicrosoftEdge must exist: C:\Users\me\AppData\Local\Microsoft\WindowsApps\ms-teams.exe
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21-ea'
Driver info: driver.version: SelenideDriver

	at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:121)
	at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
	at org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:71)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:60)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:56)
```

### Workaround

Get the app execution alias link from Windows registry

### Operating System

Windows 10

### Selenium version

Java 4.21.0

### What are the browser(s) and version(s) where you see this issue?

MS Teams based on MS Edge based on Chrome 125

### What are the browser driver(s) and version(s) where you see this issue?

msedgedriver 125.0.2535.85

**Comment by vlad8x8** [comment]
added link to the repo with a project to reproduce the issue

**Comment by vlad8x8** [comment]
@titusfortner is there a chance to remove file checks added in https://github.com/SeleniumHQ/selenium/blob/4ecc1033caa9995427c25d36befb70b8faae96d7/java/src/org/openqa/selenium/internal/Require.java#L265
for browser path?
What is the reason for those checks?

**Comment by titusfortner** [comment]
We check the validity of the output so that we can provide better error messaging about why things aren't working. I see that Windows aliases do not like this code. The right answer I believe is to also check for `Files.isSymbolicLink(file.toPath()`. Would you be interested in making a PR for it?

**Comment by vlad8x8** [comment]
@titusfortner After exploring this I realized, that this is not a symbolic link, it's an app execution alias. 
I can try to add a method isAppExecutionAlias(), but not sure if it won't fail on some non-Windows systems.

**Comment by vlad8x8** [comment]
the method can be like this:
```
boolean isAppExecutionAlias() {
    final int WINDOWS_FILE_ATTRIBUTE_REPARSE_POINT = 0x400;
    if (FileSystems.getDefault().supportedFileAttributeViews().contains("dos")) {
        int fileAttrs = (int) Files.getAttribute(path, "dos:attributes", LinkOption.NOFOLLOW_LINKS);
        return (fileAttrs & WINDOWS_FILE_ATTRIBUTE_REPARSE_POINT) != 0;
    }
}
```
can I add it to Require.java or there is a better place?

**Comment by titusfortner** [comment]
Wow, that gets ugly. Please PR it to Require so we can check as part of isFile, we can discuss (with the more Java experts on the team) if this is the best way to do it.

Thank you!

**Comment by vlad8x8** [comment]
I found another issue with non-default-easy-browser-config:
Selenium manager returns Edge path although the custom browser path was sent in parameters.
![image](https://github.com/SeleniumHQ/selenium/assets/111522705/de132714-917c-4894-b8a1-6cf172826cda)
Is there a test for browser path?
I understand it's another problem, but v4.20 broke these things :(

**Comment by joerg1985** [comment]
This has been fixed in 2a7ddf1fdeb724bb5f4bd6cd64867894aa485add by checking the executable state using the newer `java.nio` methods. I have deprecated the `java.io` stuff, so this can be removed in the future, if everything is working as expected.

**Comment by vlad8x8** [comment]
@joerg1985 your commit doesn't use java.nio.file.LinkOption.NOFOLLOW_LINKS which is critical

are you guys pushing to master? omg

**Comment by joerg1985** [comment]
@vlad8x8 i have missed to update the existence check, i did not expect this to fail in this case.
I am using `Files.notExists` now to avoid a broken symlink to pass the check.


Small and limited changes are happening on trunk, bigger / complex in PRs.
