### ISSUE TITLE
Unable to check disabled status of object having class=af_goLink p_AFDisabled by isEnabled() method

### ISSUE THREAD

**Issue by MeghaPrakash1992** [SeleniumHQ/selenium#1408]
case "enabled":	Func_FindObj(ORvalname, ORvalue);
				boolval = elem.isEnabled();
				System.out.println(boolval);
				actval = boolval.toString();
				System.out.println(actval);
				break;
verification object having class=af_goLink p_AFDisabled

I am doing keyword driven automation testing using selenium open to test frame work. I write the web page elements and their path in one file and the actions to be performed on them in the other. I am supposed to check if the link is enabled for a particular kind of user or not. I am using this method to check that. But 'boolval' always returns 'true' for any given link no matter it is enabled or disabled. Is there any other way to check if the link is enabled. If not in-built can we write our own method to check?
The only difference between the enabled and disabled element is the presence of 'href' in the anchor tag and the name of the class.

**Comment by JustinPhlegar** [comment]
As how it was explained to you in #1377, the W3C states that links are not included in elements that will return enabled or disabled. Instead, try using the getAttribute("href"). If it returns a value, then by your description it should be enabled, correct? 

In any case, you will have to create your own method for determining if your links are enabled or not.
