### ISSUE TITLE
[🐛 Bug]: Not able to disable chrome prompt through chromeOptions for chrome version 125.0.6422.142 

### ISSUE THREAD

**Issue by jain29varun** [SeleniumHQ/selenium#14098]
### What happened?

tried using below chromeOptions but not working

options.AddUserProfilePreference("download.default_directory", USER_DIR);
options.AddUserProfilePreference("download.prompt_for_download", false);

### How can we reproduce the issue?

```shell
options.AddUserProfilePreference("download.default_directory", USER_DIR);
options.AddUserProfilePreference("download.prompt_for_download", false);
```

### Relevant log output

```shell
Save As prompt still display while above chromeOptions already set.
```

### Operating System

Windows 10

### Selenium version

specflow

### What are the browser(s) and version(s) where you see this issue?

chrome version 125.0.6422.142 

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 125.0.6422.6000

### Are you using Selenium Grid?

not using

**Comment by titusfortner** [comment]
Look at
https://stackoverflow.com/a/77235931/4072371

**Comment by jain29varun** [comment]
Thanks titusfortner for reply - i tried the options given in the  https://stackoverflow.com/a/77235931/4072371 but still chrome browser prompts are opening.

**Comment by diemol** [comment]
The reach out to the Chrome team using the links above.

**Comment by RodrigoZepeda** [comment]
This is also happening to me on OSX when using `option.add_argument("-incognito")`. Doesn't happen when out of incognito mode. 

ChromeDriver 126.0.6478.61
Chrome Version 126.0.6478.62 (Official Build) (x86_64)
Not using selenium grid. 
selenium.__version__ 4.21.0

Seems to be the same issue as #13104
