### ISSUE TITLE
[🐛 Bug]: Selenium Using Css Selector with tilde signature is throwing org.openqa.selenium.InvalidSelectorException: invalid selector: 

### ISSUE THREAD

**Issue by vlaks85** [SeleniumHQ/selenium#14102]
### What happened?

[🐛 Bug]: Selenium Using Css Selector with tilde signature is throwing org.openqa.selenium.InvalidSelectorException: invalid selector: 
Below is the locator I'm using with CSS Selector but its throwing Invalid or illegal selector - div[data-testid^='Item_asin'], ~ span[data-testid^='Item_asin']

org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=108.0.5359.124) for the locator {Using=css selector, value=div[data-testid^='Item_asin'], ~ span[data-testid^='Item_asin']}

I want use CSS selector for my use Case. Any way to handle the ~ or + to get the siblings using CSS Selector. 

### How can we reproduce the issue?

```shell
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

public class Main {
    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");
        WebDriver driver = new ChromeDriver();
        
        driver.get("http://yourwebsite.com");

        // Adjust the selector based on your HTML structure
        List<WebElement> elements = driver.findElements(By.cssSelector("div.lineitem-container ~ span[data-testid^='item']"));
        
        for (WebElement element : elements) {
            System.out.println(element.getText());
        }
        
        driver.quit();
    }
}
```

### Relevant log output

```shell
org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=108.0.5359.124) for the locator {Using=css selector, value=div[data-testid^='Item_asin'], ~ span[data-testid^='Item_asin']}
```

### Operating System

Ubuntu

### Selenium version

Java 11

### What are the browser(s) and version(s) where you see this issue?

108 Chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome=108.0.5359.124

**Comment by titusfortner** [comment]
What version of selenium? Turn on logging and we can see which component complains.

**Comment by vlaks85** [comment]
Build info: version: '3.141.59'

**Comment by titusfortner** [comment]
We can't do anything about older versions, please try with Selenium 4.21
