### ISSUE TITLE
I am unable to handle the OS popup using FF V41 profiling

### ISSUE THREAD

**Issue by kumar7259** [SeleniumHQ/selenium#1413]
Refer the below code..input/suggestions plz.

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;

import java.util.concurrent.*;

public class BackupStn4 {

 
 public static void main(String[] args) throws InterruptedException {
 FirefoxProfile pro=new FirefoxProfile();
 pro.setPreference("browser.downLoad.folderList", 0);
 pro.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/zip");
 WebDriver driver=new FirefoxDriver(pro);
       
            driver.manage().timeouts().implicitlyWait(15,TimeUnit.SECONDS);
            driver.get("https://localhost");
            WebElement uswb = driver.findElement(By.xpath("//input[@class='login-input']"));
            uswb.sendKeys("admin");
            driver.findElement(By.xpath("//input[@id='login-submit']")).click();
            WebElement pswd = driver.findElement(By.id("password"));
            pswd.sendKeys("Admin123");
            driver.findElement(By.xpath("//input[@id='login-submit']")).click();
            driver.findElement(By.xpath("//a[@href='/ord?station:%7Cslot:/Services']")).click();
            driver.findElement(By.xpath("//a[@href='/ord?station:%7Cslot:/Services/BackupService']")).click();
            driver.switchTo().frame("servletViewWidget");
            driver.findElement(By.xpath("//input[@value='Backup']")).click();
 }

}

Here is the Screen shot:
![savingzipfile](https://cloud.githubusercontent.com/assets/16330648/11969673/e2e1a840-a8ea-11e5-9f8d-c166449fefc3.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
