### ISSUE TITLE
[🐛 Bug]:error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)

### ISSUE THREAD

**Issue by c469591** [SeleniumHQ/selenium#14131]
### What happened?

This error occurs in some restricted network environments when using selenium 4.9.
error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE): error trying to connect: The remote host forced an existing connection to close. (os error 10054)
When this error occurs, selenium becomes completely unusable.
And I've already manually specified the exe paths for chrome and chrome driver, so he shouldn't have to visit the specified url.
Here's the code I used to specify the chrome and chrome driver

```
                self.chrome_options = Options()
                self.chrome_options.binary_location = r'.\chrome-win64\chrome.exe'
                self.ser = Service(executable_path=r'.\chrome-win64\chromedriver.exe')
        self.browser = webdriver.Chrome(service=self.ser, options=self.chrome_options)
```

### How can we reproduce the issue?

```shell
It may be necessary to change the firewall settings so that the firewall blocks access to https://chromedriver.storage.googleapis.com/LATEST_RELEASE, which should reproduce the issue
```

### Relevant log output

```shell
error sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE): error trying to connect: The remote host forced an existing connection to close. (os error 10054)
```

### Operating System

windows10

### Selenium version

4.9

### What are the browser(s) and version(s) where you see this issue?

chrome115

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver115

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
You're right if you have specified the path of a driver, Selenium should not be trying to locate one for you. Can you turn on logging to debug mode and see what logic is executing?

**Comment by c469591** [comment]
hi, I reinstalled selenium when I was writing debugging code, and found that after installing version 4.21, I don't have the problem I mentioned before. thank you!

**Comment by diemol** [comment]
Great, thanks for letting us know!

**Comment by titusfortner** [comment]
🤦 I can't believe I missed the older version in the initial report. Selenium Manager has come a long way since then. Thanks.
