### ISSUE TITLE
[🐛 Bug]: ChromiumOptions: android-specific options are removed after merge

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/selenium#14133]
### What happened?

1. Create ChromiumOptions (ChromeOptions) and set android-specific properties (activity/package/sn/process)
2. Create MutableCapabilities  (empty one)
3. Merge ChromiumOptions with Mutable capabilities
Expected: result contain the chromiumOptions
Actual: all android-related options (from 
the `ChromiumOptions.androidOptions field`) are removed
![scr_20240614T01_18_10](https://github.com/SeleniumHQ/selenium/assets/4625317/7c4fe852-bdd7-47cb-ab85-95d359a34131)

### How can we reproduce the issue?

```shell
var original = new ChromeOptions();
		original.setAndroidActivity("co_activity");
		original.setAndroidPackage("co_package");
		original.setExperimentalOption("experimental", "co_experimental");
		original.addArguments("--co_argument");

		System.out.println("Original :: " + original.asMap());

		var caps = new MutableCapabilities();
		var merged = original.merge(caps);

		System.out.println("Merged   :: " + merged.asMap());
```

### Relevant log output

```shell
Original :: {browserName=chrome, goog:chromeOptions={androidActivity=co_activity, androidPackage=co_package, args=[--co_argument], experimental=co_experimental, extensions=[]}}
Merged   :: {browserName=chrome, goog:chromeOptions={args=[--co_argument], experimental=co_experimental, extensions=[]}}
```

### Operating System

windows 10

### Selenium version

java 4.21.0

### What are the browser(s) and version(s) where you see this issue?

n/a

### What are the browser driver(s) and version(s) where you see this issue?

n/a

### Are you using Selenium Grid?

n/a

**Comment by iampopovich** [comment]
I suspect that the issue lies in the `ChromiumOptions.mergeInPlace` method. I am trying to understand in detail how it copies capabilities and whether the name affects their copying in our case.
