### ISSUE TITLE
[🐛 Bug]: Getting unwanted script error randomly while running selenium script with  CRM dynamics 365

### ISSUE THREAD

**Issue by jaydjana87** [SeleniumHQ/selenium#14149]
### What happened?

We are running automation script with Selenium Java  in CRM DYnamics 365 new look. We are getting unwanted Script error while running script but if we do same with manually we can't reproduce the issue. Laos sometime Save button is getting disappear from screen if we are running Selenium scrip
![Save button issue](https://github.com/SeleniumHQ/selenium/assets/171400624/3e8c6dd2-4c3c-4f80-8790-790db4be9289)
![Script Error](https://github.com/SeleniumHQ/selenium/assets/171400624/ec0859b3-cdae-4bc3-9dda-d8a14207384c)

### How can we reproduce the issue?

```shell
Run Selenium script with Dynamics 365 new look (latest version)
```

### Relevant log output

```shell
Error in Dynamics:
One of the scripts for this record has caused an error. For more details, download the log file.
Web resource method does not exist: Person.GetSetMaritalStatus. However the closest object we found is Person that contains these properties: _namespace,OnSave,OnChange,Common,ValidateExpectedGraduationDate,EducationPlanIEPDate,TriggerAZTECSWebJob,onLoad,setNotificationOnSubordinateRecord,ShowHidePersonNameReason,ShowHideTribalAffiliation,PartOfACPNotification,openArtifactForm,PersonMissingNotification,ShowHideNonCitizenType,CreateProviderVisibility,CreateProviderButtonVisibility,CreateProvider,CreatePersonSuccess,CreatePersonError,PopulateIEPDate,ViewSSNButtonClick,EnableDisableStaff,ShowPersonSummary,openRecordSummary,getPersonAddress,enableACPStatus,ShowHideBulkAddUpdateBtn. Please verify this object is not corrupt and is not an object of the same name defined elsewhere, such as another script.
Session Id: ad047f58-ba06-4e4b-ae10-78054c1ea8bb
Correlation Id: 376c36a7-87ca-4cf3-a98b-bb91b239c85d
Event Name: onchange
Function Name: Person.GetSetMaritalStatus
Web Resource Name: mcshhs_/Scripts/mcshhs_Person_OnLoad.js
Solution Name: Active
Publisher Name: DefaultPublisherguardianaz
Time: Thu Jun 06 2024 22:26:33 GMT+0530 (India Standard Time)
```

### Operating System

Windows 11

### Selenium version

Selenium 4.18.1 /Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 125.0.6422.113 (Official Build) (64-bit)

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
I am closing this because we have yet to get more information.
