### ISSUE TITLE
[🐛 Bug]: getAttribute and GetDomAttribute returns null

### ISSUE THREAD

**Issue by jpeasysoft** [SeleniumHQ/selenium#14141]
### What happened?

I'm trying to retrieve the aria-owns attribute from the following element

`<input autocomplete="off" placeholder="Bitte auswählen" class="dx-texteditor-input" aria-haspopup="listbox" aria-autocomplete="list" type="text" readonly="" spellcheck="false" tabindex="0" role="combobox" aria-expanded="false" aria-controls="dx-d7e01400-e540-860e-cba9-eda8f83eb789" aria-owns="dx-866ecb84-71b9-f0e9-4037-7412cc24303d">`

but when i use 
    element.GetAttribute("aria-owns");
or
     element.GetDomAttribute("aria-owns");

the result is always null.  aria-expanded  for example is working fine.

### How can we reproduce the issue?

```shell
Create an HTML page with the mentioned element
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 11

### Selenium version

4.19.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 126.0.6478.61

### Are you using Selenium Grid?

No

**Comment by AutomatedTester** [comment]
Can you help us debug this a little further. Can you, on the page, open devtools and execute the following JS?

```js
document.querySelector('input'/*use a better selector if you know it*/).getAttribute('aria-owns')
```

**Comment by jpeasysoft** [comment]
Hi,
sorry my fault.  Everything works great.
I just noticed that the  aria-owns element will be inserted after the element was clicked.
I used the GetDomAttribute before the click.

**Comment by jpeasysoft** [comment]
Closed
