### ISSUE TITLE
[🐛 Bug]: Python, Pytest - download.default_directory is not working when --headless=new

### ISSUE THREAD

**Issue by petrisorureche** [SeleniumHQ/selenium#14150]
### What happened?

When we set the --headless=new argument for Chrome options and download.default_directory prefs, download is not working, file is not downloaded in default directory.

```
prefs = {"download.default_directory": os.path.join(ROOT_DIR, DYNAMIC_FILES_DIR),
                 "savefile.default_directory": os.path.join(ROOT_DIR, DYNAMIC_FILES_DIR),
                 "download.prompt_for_download": False,
                 "download.directory_upgrade": True}
        options.add_experimental_option("prefs", prefs)`

```
options.add_argument("--headless=new")`

### How can we reproduce the issue?

```shell
Every basic test with --headless=new argument for Chrome options.
```

### Relevant log output

```shell
-
```

### Operating System

Windows 10, Debian 11

### Selenium version

selenium==4.21.0

### What are the browser(s) and version(s) where you see this issue?

google-chrome-stable 125.0.6422.112-1

### What are the browser driver(s) and version(s) where you see this issue?

google-chrome-stable 125.0.6422.112-1

### Are you using Selenium Grid?

no

**Comment by petrisorureche** [comment]
@diemol can you explain why with "--headless=old" is working?

**Comment by diemol** [comment]
You can find more information here https://developer.chrome.com/docs/chromium/new-headless

This is out of the scope of Selenium, it is how Chrome behaves.
