### ISSUE TITLE
How to send email with attachment using selenium ?

### ISSUE THREAD

**Issue by SanattheMenace** [SeleniumHQ/selenium#1415]
Is there a simple function through which I can send an email with an attachment?

**Comment by ddavison** [comment]
unless you are automating a UI, Selenium won't do the job for you.  you should google "how to send an email using ____" where `____` is the language you are using.

If you "are" automating a UI with selenium and trying to send the email, you need to do your own research first, and/or post a question the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.  we reserve these GitHub issues for actual issues with Selenium.
