### ISSUE TITLE
[🐛 Bug]: selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

### ISSUE THREAD

**Issue by Davidgithub1** [SeleniumHQ/selenium#14159]
### What happened?

I followed the instruction on https://www.selenium.dev/documentation/webdriver/getting_started/first_script/
using ubuntu on AWS EC2
I got the error: selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

Are you able to get this to work on Ubuntu on AWS EC2?

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Firefox()

driver.get("https://www.selenium.dev/selenium/web/web-form.html")

title = driver.title

driver.implicitly_wait(0.5)

text_box = driver.find_element(by=By.NAME, value="my-text")
submit_button = driver.find_element(by=By.CSS_SELECTOR, value="button")

text_box.send_keys("Selenium")
submit_button.click()

message = driver.find_element(by=By.ID, value="message")
text = message.text

driver.quit()
```

### Relevant log output

```shell
I got the error: selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

### Operating System

Ubuntu

### Selenium version

4.21.0

### What are the browser(s) and version(s) where you see this issue?

Firefox and Chrome

### What are the browser driver(s) and version(s) where you see this issue?

tutorial doesnt mention these? What am I supposed to do?

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is having this issue, please feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.
