### ISSUE TITLE
[🚀 Feature]: image-comparison

### ISSUE THREAD

**Issue by huemach78** [SeleniumHQ/selenium#14165]
### Feature and motivation

I'm looking to compare two images, identify any differences between them, and visually highlight those differences with red rectangles. Unfortunately, the open-source library I was considering seems no longer actively maintained.

I'm looking for the built-in feature in Selenium to support this
For Example:
https://github.com/romankh3/image-comparison
OR https://github.com/appium/appium/blob/master/packages/images-plugin/docs/image-comparison.md

### Usage example

Compare the expected result and actual result and visually highlight those differences with red rectangles.

**Comment by MJB222398** [comment]
This wouldn't make sense for Selenium to do. Selenium drives browsers or android devices. This would be far outside of its remit. I do perform some image comparison in my solution. For that I use https://github.com/Codeuctivity/ImageSharp.Compare

**Comment by titusfortner** [comment]
Yeah, this is outside our scope of browser automation. Much better to find someone with this specific expertise to create/improve existing solutions. Looks like wdio is using https://github.com/rsmbl/Resemble.js (which is also in low maintenance mode).
