### ISSUE TITLE
error when trying to use selenium ide

### ISSUE THREAD

**Issue by sirishapotluri** [SeleniumHQ/selenium#1417]
I get the below error with my selenium ide 2.9.1
There was an unexpected error. Msg: TypeError: editor.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 1007, column: 75
Editor.prototype.onPopupOptions@chrome://selenium-ide/content/editor.js:1007:75
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
