### ISSUE TITLE
[🐛 Bug]: bug not fixed for "selenium seems to override _", issue 12659

### ISSUE THREAD

**Issue by Jabbar2010** [SeleniumHQ/selenium#14181]
### What happened?

just report a bug from code level, no demo here, but can look at this issue: https://github.com/appium/appium-remote-debugger/issues/383#issuecomment-2165253340

### How can we reproduce the issue?

```shell
if a website used loadash, it will be reproduced
```

### Relevant log output

```shell
_.clone is not a function
```

### Operating System

Mac OS 14.5

### Selenium version

4.19.0

### What are the browser(s) and version(s) where you see this issue?

the latest

### What are the browser driver(s) and version(s) where you see this issue?

the latest

### Are you using Selenium Grid?

no

**Comment by titusfortner** [comment]
We made a change to our code so Appium could build the atoms it needs. That change caused some problems for Selenium users, so we restored the previous code. But Appium is still using the atoms generated during that period, so if there is a conflict, I'm pretty sure it is in the Appium atoms. If there is a bug here, it's that we can't build the atoms Appium needs with the current code after rolling back the last change, but that's getting tracked elsewhere
