### ISSUE TITLE
Selenium Grid installation Issue

### ISSUE THREAD

**Issue by alwaysmohn** [SeleniumHQ/selenium#1418]
Opened a command prompt and navigate to the directory the selenium-server-standalone file. And typed the following command:

java -jar selenium-server-standalone-2.48.2.jar -role hub

When I use "http://localhost:4444/grid/console" in chrome browser, I'm getting an error

"HTTP ERROR: 403

Forbidden for Proxy
RequestURI=/grid/console

Powered by Jetty://"

![install_grid](https://cloud.githubusercontent.com/assets/3737494/11991581/026ab2da-aa42-11e5-94a7-03d1eef4a745.png)

**Comment by alwaysmohn** [comment]
use -port at the end

**Comment by GoldenScrew** [comment]
I have same problem, what is solution?

**Comment by lukeis** [comment]
it means something else is already running on the port... either another service or a previous selenium server that wasn't shut down all the way. As the previous user mentioned, one option is to specify an alternate port to run the server on.

**Comment by GoldenScrew** [comment]
I tried it, but didn't work. I just KILL the process and restart the program and it work! Thank you.
