### ISSUE TITLE
[🐛 Bug]: Selenium 4.22.0 breaks Appium

### ISSUE THREAD

**Issue by agray** [SeleniumHQ/selenium#14182]
### What happened?

Upgrading to 4.22.0 gives this error on newing up an AndroidDriver object:

```{"Method 'ExecuteAsync' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'Appium.Net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"OpenQA.Selenium.Appium.Service.AppiumCommandExecutor"}```

Downgrading to 4.21.0 and the issue does not occur.

### How can we reproduce the issue?

```shell
Project with dependencies:

Appium.WebDriver Version 5.0.0-rc.8 and Selenium 4.22.0 do not play together.
Appium.WebDriver Version 5.0.0 and Selenium 4.22.0 do not play together.
Appium.WebDriver Version 5.0.0 and Selenium 4.21.0 work fine
Appium.WebDriver Version 5.0.0-rc.8 and Selenium 4.21.0 work fine.
```

### Relevant log output

```shell
{"Method 'ExecuteAsync' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'Appium.Net, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"OpenQA.Selenium.Appium.Service.AppiumCommandExecutor"}```
```

### Operating System

Windows 11

### Selenium version

4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Latest

### What are the browser driver(s) and version(s) where you see this issue?

AndroidDriver

### Are you using Selenium Grid?

SauceLabs

**Comment by titusfortner** [comment]
Yes, Selenium added methods to a couple interfaces that Appium does not implement. We'll work with Appium .NET devs to try to keep these in sync better, but the fix for this is in Appium not Selenium.

**Comment by VitaliiDolotov** [comment]
Related Appium issue: https://github.com/appium/dotnet-client/issues/798
