### ISSUE TITLE
[🐛 Bug]: org.openqa.selenium.SessionNotCreatedException: Could not start a new session

### ISSUE THREAD

**Issue by smilinrobin** [SeleniumHQ/selenium#14196]
### What happened?

We are trying to run a simple script as attached and getting org.openqa.selenium.SessionNotCreatedException: Could not start a new session exception. The same script is working fine locally, but fails consistently on the Windows server 2022. Logs, environment details attached below:
![log](https://github.com/SeleniumHQ/selenium/assets/7482112/6ac1fbf8-4dcc-4d83-8a49-d61db439a074)
![Untitled](https://github.com/SeleniumHQ/selenium/assets/7482112/6efcf33a-b2cf-4d7c-8c73-8e80c726989f)
![image](https://github.com/SeleniumHQ/selenium/assets/7482112/63ee72de-0166-4e14-82ee-0dfd88c813c5)

### How can we reproduce the issue?

Kindly run the GoogleSearch file with Selenium Java 4.20.0 on a Windows server 2022 edition. Reference here : 

```java

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class GoogleSearch {
  public static void main(String[] args) {
    // Set the path to the chromedriver executable
    System.setProperty("webdriver.chrome.driver", "chromedriver.exe");

    // Create a new instance of the Chrome driver
    WebDriver driver = new ChromeDriver();

    // Open Google
    driver.get("https://www.google.com");

    // Find the search box element by name
    WebElement searchBox = driver.findElement(By.name("q"));

    // Type something to search for
    searchBox.sendKeys("Selenium Java");

    // Submit the form
    searchBox.submit();

    // Wait for the search results page to load
    // (You may need to add some waiting time or use explicit waits here)

    // Print the title of the search results page
    System.out.println("Page title is: " + driver.getTitle());

    // Close the browser
    driver.quit();
  }
}
```

### Relevant log output

```shell
C: \Users \Centralsqtp\Downloads \selenium\SeleniumProject>java -cp ".;selenium-java-4.20.0\*; -" GoogleSearch Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible cause s are invalid address of the remote server or browser start-up failure.
Host info: host:
at org-openqa.selenium. remote.RemoteWebDriver.execute(RemoteWebDriver.java: 536)
at org-openqa.selenium. remote.RemoteWebDriver.startSession(RemoteWebDriver-java: 232) at org.openqa.selenium. remote.RemoteWebDriver. <init>(RemoteWebDriver.java:161)
at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver-java:114)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java: 88)
at org-openqa.selenium. chrome.ChromeDriver.<init>(ChromeDriver-java: 83) at org.openqa.selenium. chrome.ChromeDriver.<init>(ChromeDriver-java: 51)
at GoogleSearch.main(GoogleSearch.java: 12)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to bind the port.
Build info: version: '4.20.0', revision: '866c76a80*
System info: os.name: "Windows Server 2022', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.22'
Driver info: driver-version: ChromeDriver
at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:249)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:117)
at org.openqa.selenium.remote.RemoteWebDriver execute(RemoteWebDriver.java: 518)
```

### Operating System

Microsoft Windows Server Version 21H2 (OS Build 20348.2402)

### Selenium version

selenium-java-4.20.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 125.0.6422.60

**Comment by krmahadevan** [comment]
@smilinrobin - What happens when you get rid of this below line from your code and try again ?

```java
System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
```

Selenium internally uses the selenium manager to manager the correct version of the driver binaries that should be used for a given browser. So you don't need to be explicitly setting this up.

**Comment by smilinrobin** [comment]
Sure @krmahadevan . Will check and revert..

**Comment by titusfortner** [comment]
You would also need to opt in to that behavior with `--selenium-manager true`

**Comment by titusfortner** [comment]
yeah, this needs to be the full path to the driver: `System.setProperty("webdriver.chrome.driver", "chromedriver.exe")`

So, opting in to use selenium manager with detect drivers would fix it as well.
