### ISSUE TITLE
sendKeys() will not append to the existing text in Rich Text Editor

### ISSUE THREAD

**Issue by adam-zjy** [SeleniumHQ/selenium#1419]
Hi All,

I tried to type some text in the Rich Text Editor with sendKeys() function, but I found this method won't append to the existing text, and it will always type in the first label

HTML:
<iframe src="javascript:&quot;loading...&quot;;" title="Rich text editor" onload="juic.fire(&quot;24:&quot;,&quot;_ifload&quot;,event);" style="height:169px;width:100%;-moz-box-sizing:border-box;border:0px; " id="24:"></iframe>
	<html>
		<head></head>
		<body contenteditable="true" style="padding: 5px; margin: 0px; background: white none repeat scroll 0% 0%;">
			<br _moz_editor_bogus_node="TRUE">
		</body>
	</html>

====================================================================

JAVA Code:

WebDriver driver = ....;
driver.switchTo().frame(...);
driver.findElement(...);

String text = "Test B I U Number Hyperlink";

String[] singleCharacters = str.split("");

        // Interval is 0.3 second between each type of character, this is to
        // simulate real human action
for (int i = 0; i < singleCharacters.length; i++)
{
     if (!StringUtils.isEmpty(singleCharacters[i]))
     {
         driver.sendKeys(singleCharacters[i]);
         Thread.sleep(300);
     }
}

Selenium: 2.48.2
Browser: Firefox 41
Java Version: JDK 1.7

Attached:
screenshot using selenium 2.47
screenshot using selenium 2.48
![selenium 2-48](https://cloud.githubusercontent.com/assets/16423729/11991644/9e012138-aa57-11e5-83c9-3b5a41f5f7cf.png)
![selenium 2-42](https://cloud.githubusercontent.com/assets/16423729/11991645/9e2d591a-aa57-11e5-819f-fd32692bc554.png)

**Comment by adam-zjy** [comment]
More information:

We've tried with Selenium 2.47.1 and it works fine, so we are sure that it's a regression issue in 2.48 version and from its changelog, it's very like due to the change "* Firefox: fixing sendKeys for contentEditable elements, it should append to the existing text.".

**Comment by barancev** [comment]
Fixed by commit f5daf207fa21e0135f5588402bf72c7905f97ece
