### ISSUE TITLE
[🐛 Bug]: selenium-server-standalone-2.53.0.jar fails to extract on Windows using Java 21 jar.exe

### ISSUE THREAD

**Issue by chuckdumont** [SeleniumHQ/selenium#14202]
### What happened?

When running `jar --extract` to extract the contents of selenium-server-standalone-2.53.0.jar on Windows, it fails because the META-INF folder contains both a `LICENSE` file and a `license` folder.  This results in a name collision on Windows systems.  Older versions of Java would just silently overwrite the duplicate files/folders, but recent versions of Java (not sure when this change was introduced but it fails with JDK21) fail instead.

This problem causes all kinds of issues.  For me it shows up in Eclipse as project build errors for projects that have a dependency on this file.

Please update selenium-server-standalone-2.53.0.jar to avoid the name collision.

### How can we reproduce the issue?

```shell
On a Windows system using JDK21 or above, run `jar --extract --file selenium-server-standalone-2.53.0.jar`.
```

### Relevant log output

```shell
N/A
```

### Operating System

Windows 11

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
That version of Selenium is old and never meant to work flawlessly with Java 21. We don't go back and fix old versions, so I recommend unpacking it with an earlier version of Java.
