### ISSUE TITLE
[🐛 Bug]: Timeout error when trying to capture screenshot using DevTools

### ISSUE THREAD

**Issue by Eth3rnit3** [SeleniumHQ/selenium#14209]
### What happened?

I'm experiencing a timeout error when trying to capture a screenshot using the DevTools API in Selenium with Ruby. Below are the steps to reproduce the issue and the relevant code snippets.

### How can we reproduce the issue?

1. Initialize the Chrome driver:
    ```ruby
    driver = Selenium::WebDriver.for :chrome
    ```
2. Navigate to a web page:
    ```ruby
    driver.navigate.to "http://www.google.com"
    ```
3. Initialize DevTools:
    ```ruby
    devtools = driver.devtools
    ```
4. Attempt to capture a screenshot again (times out):
    ```ruby
    devtools.page.capture_screenshot
    ```

### Relevant log output

```shell
timed out after 30 seconds (Selenium::WebDriver::Error::TimeoutError)
```

**Additional Information:**
I have tried initializing DevTools both before and after navigating to a web page, but the timeout error persists in both cases. Any guidance on how to resolve this issue would be greatly appreciated.

Thank you for your assistance.

### Operating System

macOS Monterey 12.7.5

### Selenium version

4.21.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 126.0.6478.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 126.0.6478.63

### Are you using Selenium Grid?

No

**Comment by Vishwas-web** [comment]
Hey @Eth3rnit3, have you tried checking if the DevTools are enabled? If not, try using this code and see if it works.
```
driver = Selenium::WebDriver.for :chrome
devtools = driver.devtools
devtools.page.enable
driver.navigate.to "http://www.google.com"
screenshot_data = devtools.page.capture_screenshot
File.open("screenshot.png", "wb") { |f| f.write(screenshot_data) }
```

**Comment by diemol** [comment]
Thank you for troubleshooting, @Vishwas-web!

@Eth3rnit3 If you are still facing this issue, please share your code snippet and logs, and we can reopen this issue.
