### ISSUE TITLE
[🐛 Bug]: Unable to close the browser driver and unable to do parallel run in ADO pipeline

### ISSUE THREAD

**Issue by MonicaKannian** [SeleniumHQ/selenium#14214]
### What happened?

Chrome driver using selenium does not kill/close/quit properly. Which leads to the connectivity issue to the host for parallel execution

### How can we reproduce the issue?

```shell
Yes, with respect to any pipeline execution chrome driver does not close
```

### Relevant log output

```shell
OpenQA.Selenium.WebDriverException: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL.
The exception message was: No connection could be made because the target machine actively refused it.
```

### Operating System

Windows 10

### Selenium version

selenium 4.14.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 123 to latest

### What are the browser driver(s) and version(s) where you see this issue?

chrome

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
I am closing this because we have yet to get more information.
