### ISSUE TITLE
[🐛 Bug]:  raise WebDriverException( selenium.common.exceptions.WebDriverException)

### ISSUE THREAD

**Issue by skybird2022** [SeleniumHQ/selenium#14213]
### What happened?

Hi Support Team,

After I upgraded selenium version from 4.6.0 to 4.22.0 in Pycharm, it encountered following errors ( Please refer to attached screen captures with bugs) . I checked my local  environment variable setting is no problem, and chromedriver version match with Google Chrome. I also open selenium-manager.exe, there is a error too. Can you help to check the root cause of these errors ?  Thanks for support !  

In order not to affect my daily work, I uninstall 4.22.0, and re-install temporarily 4.6.0 for workaround. 

![2](https://github.com/SeleniumHQ/selenium/assets/109964366/e344ec4d-0dd5-4484-9168-fbb622047aff)
![1](https://github.com/SeleniumHQ/selenium/assets/109964366/3e2ce38b-5a69-456a-b31f-eb3c80f53d84)
![3](https://github.com/SeleniumHQ/selenium/assets/109964366/15fd19af-30ae-47e3-93fa-3a75ed6cadf8)

### How can we reproduce the issue?

```shell
for example: 

from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://www.baidu.com/')
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "G:\Python\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
  File "G:\Python\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 53, in binary_paths
    return self._run(args)
  File "G:\Python\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 118, in _run
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: G:\Python\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --language-binding python --output json; code: 3221225477
{}

The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "F:/Pycharm/Projects/aaa.py", line 8, in <module>
    driver = webdriver.Chrome()
  File "G:\Python\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "G:\Python\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__
    if finder.get_browser_path():
  File "G:\Python\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "G:\Python\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Window 7

### Selenium version

4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome - 109.0.5414.120

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver - 109.0.5414.25

### Are you using Selenium Grid?

No

**Comment by skybird2022** [comment]
> We need more information about this issue in order to troubleshoot.
> 
> Please turn on logging and re-run your code. Information on how to adjust logs for your language can be found in our [Troubleshooting documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/).

Hi Support Team,  please refer to above "Relevant log output" details.

**Comment by diemol** [comment]
Check the link; it has instructions on how to enable debug logging. 

[Troubleshooting documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/).

**Comment by skybird2022** [comment]
> Check the link; it has instructions on how to enable debug logging.
> 
> [Troubleshooting documentation](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/).

Hi Diemol,  I try to logging it according to your advise,  it's not workable.  I have find out the solution from official document.  For higher version(4.6.0 or above ), I tested by using Service object to dedicate the path of chromedriver, it's workable. Therefore, seems there is no relationship between high-version and setting-driven environment variables. 

Anyway, thanks for your support and prompt reply.

**Comment by diemol** [comment]
Thanks for letting us know.

**Comment by jparrai** [comment]
Happened to me too. It seems like Windows 7 is not supported from 4.20 onwards.
