### ISSUE TITLE
IE11: Failed to navigate using IEdriver on windows 7

### ISSUE THREAD

**Issue by pnswamy** [SeleniumHQ/selenium#1421]
Hi,
I am getting this error "call to the COM method IWebBrowser2::Navigate.failed()" while running rpsec. The browser launches but its unable to go to the url "This is the initial start page for the WebDriver server." This is the same problem I am seeing as mentioned in https://code.google.com/p/selenium/issues/detail?id=4825&pli=1 but I couldn't add a comment there, so opening a new issue. 

The url I am trying to launch is something like -> http://username:pwd@hostname:port/xxx
I am using IEDriverServer_Win32_2.48.0 (32-bit installation) and browser is IE11 on windows 7.

Things done:
- Set the registry
- Zoom level is 100%
- Disabled protection mode as per suggestions is https://code.google.com/p/selenium/wiki/InternetExplorerDriver#Required_Configuration
- Rebooted machine

Any help would be appreciated.

**Comment by jimevans** [comment]
Internet Explorer explicitly disabled the ability to pass user name and password via the URL. Note **this is a browser limitation**, not a driver limitation. What happens when you omit the user name and password?

**Comment by pnswamy** [comment]
@jimevans  Thanks alot for the response. When I omit the username and password, it redirects to the url but prompts for username and password.

**Comment by jimevans** [comment]
Then the driver is working as expected.
