### ISSUE TITLE
[🐛 Bug]: ChromeDriver and ChromeDriverService Do Not Work

### ISSUE THREAD

**Issue by dnya0** [SeleniumHQ/selenium#14227]
### What happened?

The test server worked well, but when you try to deploy it to another server, it stops working at `chromeDriverService = ChromeDriverService.createDefaultService();` even if you remove the ChromeDriverService and immediately use `driver = new ChromeDriver(options);` the code stops without executing it.

Both servers are the same except for the version and memory. Changing the size of the thread pool from 10 to 1 doesn't work because I was wondering if it was a memory problem.

It stopped before it was initialized, so the log is not even taken.

Main Server
~~~
              total        used        free      shared  buff/cache   available
Mem:          7.5Gi       5.5Gi       926Mi       178Mi       1.1Gi       1.6Gi
Swap:         2.0Gi       1.7Gi       303Mi
~~~

Test Server
```
              total        used        free      shared  buff/cache   available
Mem:           15Gi       6.6Gi       2.4Gi       477Mi       6.4Gi       8.0Gi
Swap:         2.0Gi       843Mi       1.2Gi
```

### How can we reproduce the issue?

```shell
--
```

### Relevant log output

```shell
Nonexistent
```

### Operating System

Test Server: Rocky Linux release 8.9 (Green Obsidian), Main Server: Rocky Linux release 8.10 (Green Obsidian)

### Selenium version

Java 4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 126

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 126

**Comment by diemol** [comment]
If it works in one server but not the other one, something is missing in the configuration of the new server. 

Use the links below to ask questions.

**Comment by dnya0** [comment]
I think the chromedriver not working on Rocky Linux release 8.10
