### ISSUE TITLE
[🐛 Bug]: `a.tagName.toUpperCase is not a function` when input id or name is 'tagName'

### ISSUE THREAD

**Issue by yoshitaka-ogata** [SeleniumHQ/selenium#14229]
### What happened?

`node.tagName.toUpperCase()` may throw the error because the form tagName returns a child input element instead of the tag name if the input element id or name is 'tagName'.

The error was raised at 
https://github.com/SeleniumHQ/selenium/blob/c5f314670396b04e92b32500bd6e0dfac31e841f/javascript/atoms/domcore.js#L173

FYI Playwright fixed the same issue. https://github.com/microsoft/playwright/pull/30636

### How can we reproduce the issue?
HTML
```html
<form id="aaa">
  <input type="text" name="tagName">
</form>
```

Python
```python
elm = driver.find_element(by=By.ID, value="aaa")
displayed = elm.is_displayed()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "xxxxxx/selenium/xxxxxx.py", line 20, in <module>
    displayed = elm.is_displayed()
  File "xxxxxx/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 252, in is_displayed
    return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
  File "xxxxxx/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 414, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "xxxxxx/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "xxxxxx/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: a.tagName.toUpperCase is not a function
  (Session info: chrome=126.0.6478.127)
```

### Operating System

macOS

### Selenium version

Python selenium 4.22.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 126.0.6478.126.0

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 126.0.6478.126.0

**Comment by diemol** [comment]
I am not sure if the atom is being used by ChromeDriver. I think they have their own implementation.

However, can you help us with a fix through a PR, and we can give you a nightly build to test it? Adding a test to the PR would be ideal. Thank you!

**Comment by yoshitaka-ogata** [comment]
Thank you for your comment.

According to the Chromium project's [read me](https://source.chromium.org/chromium/chromium/src/+/main:third_party/selenium-atoms/README.chromium), Chrome Driver clones the Selenium repository and builds it by bazel. Therefore, I think it needs to be fixed to resolve the Chrome Driver error. 

I'll prepare a PR later.

**Comment by shbenzer** [comment]
Can be closed with the above merge

**Comment by yoshitaka-ogata** [comment]
@shbenzer Thank you. I'll close this issue and PR.
