### ISSUE TITLE
Java selenium threads are not getting destroyed on driver.quit

### ISSUE THREAD

**Issue by Togin** [SeleniumHQ/selenium#14223]
### What happened?

I'm encountering some unusual issues with the Selenium driver in Java. Our application collects and stores data from the user interface using Selenium automation scripts. This automated process runs about 300 to 400 times per day, executing correctly and storing data in the database as expected.

However, after the Java service has been running for more than a week, it begins to throw the error "Unable to create a new thread," eventually leading to an out-of-memory exception on the server. To resolve this, I have to restart the Java service. After a restart, it works for a few more days before the same thread error and out-of-memory exception occur again.

Through debugging, I've observed that Selenium-related threads remain in the thread chain even after being closed with the driver.quit() statement in the finally block. Despite attempts to interrupt these threads, they persist, appearing as sleeping or zombie threads in the live threads list.

Has anyone faced similar issues or know of any fixes?

Java version: 17
Selenium version: 4.16.0

### How can we reproduce the issue?

```shell
Even with basic chrome driver launch and quit will reproduce the thread issue. Threads details can be tracked through using JVisualVm or Jconsole
```

### Relevant log output

```shell
Unable to create a thread
```

### Operating System

Windows and unix

### Selenium version

Java 17.0, Selenium 4.16 .0

### What are the browser(s) and version(s) where you see this issue?

Chrome 123

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 123

### Are you using Selenium Grid?

4.16.0

**Comment by pujagani** [comment]
Can you try out the latest version and confirm if this error is still persistent?
Thank you!

**Comment by Togin** [comment]
> Can you try out the latest version and confirm if this error is still persistent?
> Thank you!

I tried fixing the issues with multiple selenium versions,  but it's not fixing the thread issues. 
Tried with selenium 4.14, 4.15, 4.16 and 4.18

**Comment by joerg1985** [comment]
Please try with 4.22.0, this latest release had e.g. a fix for leaking threads from the UrlChecker (this is not in the changelog for what ever reason).  If the issue still is present, try to provide more infos, e.g. the names of the leaking threads and if possible code to reproduce.

**Comment by Togin** [comment]
The "httpclient-X-selectormanager" is the thread name that is created twice while launching the Selenium driver, and only one thread gets closed during the driver. quit statement. 

Somehow,using thread interrupt,I was able to close both the httpclient-X-selectormanager threads.But still, the zombie threads persist in the thread loop.

This issue we can replicate using simply launch selenium driver . Please use the jconsole or JVisualVm to check the thread list.


![291619620-da3b27af-49b8-4119-abd5-e10202caedd5.png](https://github.com/SeleniumHQ/selenium/assets/33391523/3205cc91-42e6-441a-ba2e-220742a0e16a)

**Comment by joerg1985** [comment]
@Togin from what version is this? There have been several fixes to the selector threads. If i remember correctly it might help to update the JDK to 21.

**Comment by Togin** [comment]
I'm using Java 17 and selenium 4.16.0

**Comment by joerg1985** [comment]
@Togin you might run into this: https://github.com/SeleniumHQ/selenium/issues/13246

**Comment by Togin** [comment]
> @Togin you might run into this: https://github.com/SeleniumHQ/selenium/issues/13246

I have seen this issue , but unfortunately, that is not resolving the issues that im facing.

**Comment by diemol** [comment]
Do we need to do something here? Why are you not using the latest version?

**Comment by Togin** [comment]
> Do we need to do something here? Why are you not using the latest version?

I'm facing this issue for the past few months, and we can't change the dependencies for each patch release due to the tight couing with other dependencies in the service.

I believe this issue has been with selenium for a long time. Maybe it's not discovered by many developers , the usecase I'm having with  selenium automation is a bit different from the normal project requirement. 

The driver issue will only cause memory exception problems when it's running at least 400,500 times without a java-service restart.

**Comment by diemol** [comment]
The point is that @joerg1985 has made improvements related to this in the last 2-3 releases. In addition, we cannot fix old versions. 

We can leave this issue open, but there is not much we can do until you try with the latest version.

**Comment by Togin** [comment]
> The point is that @joerg1985 has made improvements related to this in the last 2-3 releases. In addition, we cannot fix old versions. 
> 
> We can leave this issue open, but there is not much we can do until you try with the latest version.

Ok, that's great. 
Could you please share the exact version details . I will try that version and confirm back.

**Comment by diemol** [comment]
Feel free to check the changelog.

**Comment by Togin** [comment]
> Feel free to check the changelog.

I have tested with the latest selenium  4.23.0 , but the thread related issues are still there .

Please see the attached screenshot. The even number httpclient-X-selectormanager threads are still in live status even after the driver.quit()


![20240724_120713.jpg](https://github.com/user-attachments/assets/92a3b3ca-4095-49ef-befe-37bc5bfa8778)

**Comment by joerg1985** [comment]
Could you try to trigger GC several times in this state and check the threads again? If the threads are released on GC everything is working as expected. In JDK21 this has been addressed by adding new methods to close the client, but we are currently at language level 17.

**Comment by Togin** [comment]
> Could you try to trigger GC several times in this state and check the threads again? If the threads are released on GC everything is working as expected. In JDK21 this has been addressed by adding new methods to close the client, but we are currently at language level 17.

Triggered the GC multiple times and multiple runs, but always the odd number httpclient-X-selectormanager only getting closed or destroyed after the driver.quit().

The threads having even numbers are still in the thread array. 
Even number thread means , httpclient-2-selectormanager , httpclient-4-selectormanager , httpclient-6-selectormanager ,...etc.

**Comment by joerg1985** [comment]
@Togin I was currently debugging something else and stumbled into a case where the httpclient is not closed. Do you see errors while creating sessions (log message is: "Error while creating session with the driver service")? In this case the httpclient is leaked.

**Comment by joerg1985** [comment]
https://github.com/SeleniumHQ/selenium/commit/97d56d04e1b4ab4f8e527f8849b777c1e91d13f7 is the promised commit @Togin could you update to the next nightly and check?

**Comment by Togin** [comment]
> @Togin I was currently debugging something else and stumbled into a case where the httpclient is not closed. Do you see errors while creating sessions (log message is: "Error while creating session with the driver service")? In this case the httpclient is leaked.

No,I'm not. 
I was facing error with the message " Failed to start thread "unknown thread" pthread_creare  failed for attributes stack size:1024 k ,guard size:4k detached".

**Comment by Togin** [comment]
Do you want me to check the issue is still persist afer the latest  selenium patch update (after ur current commit fix) ?
> https://github.com/SeleniumHQ/selenium/commit/97d56d04e1b4ab4f8e527f8849b777c1e91d13f7 is the promised commit @Togin could you update to the next nightly and check?

**Comment by joerg1985** [comment]
@Togin it would be great if you could check after the patch, perhaps the patch helps.

**Comment by Togin** [comment]
> @Togin it would be great if you could check after the patch, perhaps the patch helps.

Sure, I will check.  If possible,  please share the path or version number.

**Comment by joerg1985** [comment]
Have a look at [Selenium Nightly Builds](https://www.selenium.dev/downloads/) how to enable the Snapshots Repo, the version tag is `4.24.0-SNAPSHOT`

**Comment by joerg1985** [comment]
I just pushed another fix a5de3775db76dde54b9c6a94fbe3f2b816eacb80, in case you are using a distributed (hub / node and not standalone) setup and a client does not properly terminate the websocket. I run into this when i kill my client jvm using `System.exit(1)` instead of a graceful shutdown some time ago and finally had the time to fix it.

**Comment by Togin** [comment]
> I just pushed another fix a5de3775db76dde54b9c6a94fbe3f2b816eacb80, in case you are using a distributed (hub / node and not standalone) setup and a client does not properly terminate the websocket. I ran into this when i kill my client jvm using `System.exit(1)` instead of a graceful shutdown some time ago and finally had the time to fix it.

My selenium is running inside a linux machine on headless mode and im only using a driver.quit statement to kill the Selenium driver related threads. 
Anyway,  i will try to re-produce or test out my use case with the latest version

**Comment by Togin** [comment]
> I just pushed another fix a5de3775db76dde54b9c6a94fbe3f2b816eacb80, in case you are using a distributed (hub / node and not standalone) setup and a client does not properly terminate the websocket. I run into this when i kill my client jvm using `System.exit(1)` instead of a graceful shutdown some time ago and finally had the time to fix it.

I tried with the latest version of 4.23.1, and still, the memory issue is there.  Please see the observations below.

In windows : As you mentioned, httpclient-X-selectormanager threads are getting destroyed with the driver.quit() statement. Before this version,  threads were not properly closed or destroyed. But even after the threads are getting properly closed, I can see the Chrome jobs or processes are still in the background process of the task manager. Please see the attached screenshot .![20240813_163750.jpg](https://github.com/user-attachments/assets/943e6aa8-e9e3-430c-a0ac-953eb34ac33e)


In Linux :- Like expected, the httpclient-X-selectormanager threads are getting destroyed, but there are zombie threads still persist in the background.Please see the attached screens I run the selenium driver launch almost ten times, and exactly the same number of chrome processors are still in the background. In the case of zombie threads, in linux, each driver launches   leftover, almost eight zombie threats into the background process![20240813_163601.jpg](https://github.com/user-attachments/assets/73ba1500-0944-4d23-a5ed-599ea7ae3d85)


It means the threats are getting closed properly, but still some existence of the driver leftover without properly destroying.

**Comment by joerg1985** [comment]
@Togin thanks for checking the threads.

The processes might be related to this https://github.com/SeleniumHQ/selenium/issues/13656#issuecomment-2001945604 

Are you using the sandbox flag?

**Comment by Togin** [comment]
> @Togin thanks for checking the threads.
> 
> The processes might be related to this https://github.com/SeleniumHQ/selenium/issues/13656#issuecomment-2001945604 
> 
> Are you using the sandbox flag?
> 
> 

Using --no-sandbox , please see the rest of the configurations
![20240813_170921.jpg](https://github.com/user-attachments/assets/52d6e5e9-8476-4f89-b199-050cbb39aa76)

**Comment by joerg1985** [comment]
Could you try to drop `--no-sandbox` and `----disable-dev-shm-usage`? They should only be needed for running in containers (and `----disable-dev-shm-usage` looks broken in any case)

**Comment by Togin** [comment]
> Could you try to drop `--no-sandbox` and `----disable-dev-shm-usage`? They should only be needed for running in containers (and `----disable-dev-shm-usage` looks broken in any case)

The live running version of my application is running or deployed inside the docker container .

**Comment by joerg1985** [comment]
Why not adding a if/else statement around these two?
They are problematic outside a container.

**Comment by Togin** [comment]
> Why not adding a if/else statement around these two?
> They are problematic outside a container.

Ok, I can keep these arguments excluded for the local run. 
But, still, this is required when it's running inside Docker container , my major concern is in this part.  Because the running live version from the Linux box is facing this memory issues due to the undestroyed threads .

What could be the solution for running inside the container?

**Comment by Togin** [comment]
> Could you try to drop `--no-sandbox` and `----disable-dev-shm-usage`? They should only be needed for running in containers (and `----disable-dev-shm-usage` looks broken in any case)

As you suggested, I tried without the --no-sandbox and --disable-dev-shm-usage arguments and in windows/in my local it's working as expected.  ie, it properly killed all the chrome running processes , but in Linux, the issue is still there. 

I can still see the zombie threads in the Linux process list. Before removing these arguments,  each of the selenium launches creates 8 zombie threads.  But after removing the arguments, it creates 7 zombie threads for each selenium launch instead of 8 zombie threads. 

Please see the screenshot ![20240814_144038.jpg](https://github.com/user-attachments/assets/5fc0cd7d-0e13-4aef-b816-c08bd6c1d459)

**Comment by joerg1985** [comment]
I think this should be addressed at https://issues.chromium.org/issues 
The original issue is fixed, so i wil close this.

**Comment by Togin** [comment]
> I think this should be addressed at https://issues.chromium.org/issues 
> The original issue is fixed, so i wil close this.

This shared link is not working .

**Comment by Togin** [comment]
> I think this should be addressed at https://issues.chromium.org/issues 
> The original issue is fixed, so i will close this.

But your previous fixes resolved the regular thread issues, and rightnow it's only has the zombie thread issues . 
Also, after removing the sandbox argument, it reduces 1 zombie thread instance for the driver launch.
