### ISSUE TITLE
Selenium WebDirver Firefox document.readyState always return complete when pageLoadStrategy as none

### ISSUE THREAD

**Issue by knights92** [SeleniumHQ/selenium#1422]
I am trying to automate a web application in Firefox to check the page rendering and network time of the application. I don't want to use any timeout function since it affect the purpose of my test so i decided to use document.readyState property for page navigation also for measuring the page rendering and network time (PR/Ntwk) i ll be waiting till the readyState gets complete. So i ll be measuring the PR/Ntwk time using stopwatch from the readyState loading to Complete.

When i am using default pageLoadStrategy for Firefox the readyState property is working as expected but when i am changed the pageLoadStrategy to none for some application which has signalR request (longpolling) the readyState property always returning the state as "complete" even when the page is still loading.

Can any one help me regarding this issue or any other solution would be helpful?

Firefox version : V43.0.2
Selenium Webdriver version : V2.48.2

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
