### ISSUE TITLE
[🚀 Feature]: Expose Selenium Version in Node.js npm Package

### ISSUE THREAD

**Issue by bukowa** [SeleniumHQ/selenium#14222]
### Summary:
Add a feature to the Selenium Node.js npm package that exposes the Selenium version in the source code.

### Proposal:
Introduce a constant or method to retrieve the Selenium version.

### Benefits:

Simplifies peer dependency checks.
Eases debugging and compatibility validation.

### Usage example

```js
const seleniumVersion = require('selenium-webdriver').VERSION;
````

### Example from npmjs.com:
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies
```js
try {
  var foo = require("foo");
  var fooVersion = require("foo/package.json").version;
} catch (er) {
  foo = null;
}
if (notGoodFooVersion(fooVersion)) {
  foo = null;
}

// .. then later in your program ..

if (foo) {
  foo.doFooThings();
}
```

**Comment by pujagani** [comment]
Hey! What is the motivation behind this feature request?

**Comment by bukowa** [comment]
This already exists in `python`:
https://github.com/SeleniumHQ/selenium/blob/5e8d6a1f93c51a719c13d7dc263097bec707b11f/py/selenium/__init__.py#L19

**Comment by iampopovich** [comment]
#14325 is merged 
@diemol could you please close the issue🙏
