### ISSUE TITLE
[🚀 Feature]: wait for networkidle

### ISSUE THREAD

**Issue by liudongmiao** [SeleniumHQ/selenium#14221]
### Feature and motivation

In RUM (Real User Monitoring), the `sendBeacon` is called when page is loaded. If we wait for element, then we cannot make sure the monitor data is sent out completely.

So, we need to wait for network idle to make sure RUM data is sent out.

@joerg1985 has a similiar issue https://github.com/SeleniumHQ/selenium/issues/11800, however, I don't know whether is implemeted or not.

### Usage example

puppeteer has `waitForNetworkIdle`, and playwright has `waitForLoadState('networkidle')`.

**Comment by diemol** [comment]
This will be available through [network interception](https://github.com/SeleniumHQ/selenium/issues/11800#issuecomment-1490400532). Please follow the future releases and check for this feature.

**Comment by liudongmiao** [comment]
Currently, we use `executeAsyncScript` to fetch a custom wait-network-idle request in mitmproxy.
