### ISSUE TITLE
[🐛 Bug]: Relative Locators do not work on java

### ISSUE THREAD

**Issue by jbalooka** [SeleniumHQ/selenium#14241]
### What happened?

java.lang.IllegalArgumentException: Context does not provide a mechanism to execute JS (ChromeDriver etc.....)

at org.openqa.selenium.By.getJavascriptExecutor(By.java:153)

	at org.openqa.selenium.support.locators.RelativeLocator$RelativeBy.findElements(RelativeLocator.java:190)

	at org.openqa.selenium.By.findElement(By.java:122)

	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:139)

	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:81)

	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)

	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:211)

### How can we reproduce the issue?

```shell
Use RelativeBy with Java


Solution: 

the getJavaScriptExecutor check for the Original Context instead of the found Driver.
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Context does not provide a mechanism to execute JS (ChromeDriver etc.....)



at org.openqa.selenium.By.getJavascriptExecutor(By.java:153)

	at org.openqa.selenium.support.locators.RelativeLocator$RelativeBy.findElements(RelativeLocator.java:190)

	at org.openqa.selenium.By.findElement(By.java:122)

	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElement(ElementLocation.java:139)

	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:81)

	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)

	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:211)
```

### Operating System

Windows 10

### Selenium version

Java 4.20.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 90+

### What are the browser driver(s) and version(s) where you see this issue?

ChromDriver 90+

**Comment by iampopovich** [comment]
@jbalooka Could you please provide an example of code that causes an error? I will try to figure out what the problem is and, after fixing it, I will add a test case for it.

**Comment by jbalooka** [comment]
We have something simialr to this, the Driver is JavascriptSupported:


```java
WebElement relativeElem = getSomeWebElem();
RelativeLocator.RelativeBy relativeLocator = RelativeLocator.with(By.xpath("my-baseItem")).below(relativeElem);

getDriver().findElements(relativeLocator);
```

The Problem is that when the Locator tries to figure out it's driver, it's okay, but the Check is done against the SearchContext and not the Driver

**Comment by iampopovich** [comment]
@jbalooka I have created a test to check this scenario. Tell me, is the test valid?

```java
@Test
void fix14241() {
  driver.get(appServer.whereIs("relative_locators.html"));
  WebElement rect3 = driver.findElement(By.id("rect3"));
  RelativeLocator.RelativeBy relativeLocator = RelativeLocator.with(By.id("rect4")).near(rect3);
  driver.findElements(relativeLocator);
}
```
```
INFO: Found 1 test target...
Target //java/test/org/openqa/selenium/support/locators:RelativeLocatorTest up-to-date:
  bazel-bin/java/test/org/openqa/selenium/support/locators/RelativeLocatorTest
  bazel-bin/java/test/org/openqa/selenium/support/locators/RelativeLocatorTest.jar
INFO: Elapsed time: 39.101s, Critical Path: 12.17s
INFO: 3 processes: 1 internal, 1 local, 1 worker.
INFO: Build completed successfully, 3 total actions
INFO: 
//java/test/org/openqa/selenium/support/locators:RelativeLocatorTest     PASSED in 8.3s

Executed 1 out of 1 test: 1 test passes.

```
I quickly checked the test on macOS 14 + Chrome 126.0.6478.127 - the test passed. Now I will try to run it on Windows 10.

**Comment by iampopovich** [comment]
> Chrome 90+

These are releases from 2021 and later. I doubt these are relevant browser versions after almost 3 years. Is it necessary to reproduce the issue specifically on these versions? Can we find out the exact version where the bug was encountered?

**Comment by jbalooka** [comment]
Not Relevant, some of our Old Kiosks still use it, but generally is version independent

**Comment by iampopovich** [comment]
hm... 
I set up the environment for running the tests: `Windows 11 / Selenium Java 4.22 / OpenJDK 22.0.1`

I ran the same test on Chrome 95.0.4638.54 - the test passed successfully.
I ran the same test on Chrome 103.0.5060.66 - the test passed successfully.
I ran the same test on Chrome 105.0.5195.127 - the test passed successfully.
I also ran the test on Chrome 126.0.6478.127 - the test passed successfully.
So far, I cannot reproduce the bug as described in the above scenario.
```
@Test
void fix14241() {
  driver.get(appServer.whereIs("relative_locators.html"));
  WebElement rect3 = driver.findElement(By.id("rect3"));
  RelativeLocator.RelativeBy relativeLocator = RelativeLocator.with(By.id("rect4")).near(rect3);
  driver.findElements(relativeLocator);
}
```
@jbalooka, can you suggest if there is anything else I might have missed while reproducing the issue?
<img width="1536" alt="Screenshot 2024-07-11 at 16 06 59" src="https://github.com/SeleniumHQ/selenium/assets/23129441/0d05574e-d0e7-4fd6-a4ec-da9151ca7f69">

**Comment by jbalooka** [comment]
This Looks Good. Thank You!

**Comment by diemol** [comment]
Thank you for troubleshooting, @iampopovich!
