### ISSUE TITLE
[🐛 Bug]: \

### ISSUE THREAD

**Issue by Erix377** [SeleniumHQ/selenium#14246]
### What happened?

I have noticed below issue while executing below sample JavaScript code using ‘executeScript’ function.

Issue: The ‘else’ block is not getting executed when the ‘if-elseif’ block is not enclosed within curly braces. As there are one-line statements I didn’t add curly braces and I think it’s a valid syntax in JavaScript.

Sample JavaScript code that I have tried: 

   var a = 20;
   var b;
 
   if (a == 10)
       b = 5;
   else if (a < 5)
       b = 10;
   else
       b = 30;

   console.log("Printing b");
   console.log("b=" + b);
   console.log("end");

In the above case, since a=20, the else block should get executed and should set b=30. But for some reason the else block is not getting executed, b sets to undefined. See attached screenshot for the same "Else_block_issue.png".

Also attached screenshot for If and Else-if blocks -

"If_block_workingFine.png",  "Else_If_block_workingFine.png".

However, when enclosed ‘if-elseif’ block with curly braces it’s working fine. See attached screenshot - "Else_block_workingFine.png"

Knowing the fact it’s always best practice to add curly braces even in case of one-line statements.

Out of curiosity asking why it didn’t work when no curly braces were added though it’s a valid syntax..?

Note: When executed the same code in JavaScript compiler, it worked as expected (Else block gets executed).

![Else_block_issue](https://github.com/SeleniumHQ/selenium/assets/111478885/624a1e46-7043-436f-ba50-712773ad8704)
![Else_block_workingFine](https://github.com/SeleniumHQ/selenium/assets/111478885/d802df6b-c95c-4f35-9879-f8537e3c63b5)
![If_block_workingFine](https://github.com/SeleniumHQ/selenium/assets/111478885/1728b1af-fc17-483d-9fa1-21e4934dbbc9)
![Else_If_block_workingFine](https://github.com/SeleniumHQ/selenium/assets/111478885/0a7ed998-09a1-411b-ad84-a2b31e1ddc71)

### How can we reproduce the issue?

```shell
1. Create a js script with code below:

var a = 20;
var b;

if (a == 10)
    b = 5;
else if (a < 5)
    b = 10;
else
    b = 30;

return b;

2. Use a webdriver to call ‘executeScript’ function to execute this file and you will see b is undefined
```

### Relevant log output

```shell
b=undefined
```

### Operating System

Mac, Windows, Linux 

### Selenium version

Java 4.13.0

### What are the browser(s) and version(s) where you see this issue?

Chrome  119.0.6045.159 (Official Build) (arm64)

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver-v0.33.0-macos-aarch64, chromedriver

**Comment by diemol** [comment]
Does the code work when you run it on your own without Selenium? Have you tried that?

**Comment by diemol** [comment]
This does not look like a Selenium issue, and if it were urgent, they would have replied already. Please use the links shown below to ask more questions.
