### ISSUE TITLE
[🐛 Bug]: 'RejectedExecutionException' during Thread Local Test Execution after Selenium Java 4.14.0

### ISSUE THREAD

**Issue by HasiniRangana** [SeleniumHQ/selenium#14269]
### What happened?

When performing thread local test execution using Selenium Java 4.14.0, the following error occurs.

`java.io.IOException: java.util.concurrent.RejectedExecutionException: Task jdk.internal.net.http.common.SequentialScheduler$SchedulableTask@6de2a772 rejected from java.util.concurrent.ThreadPoolExecutor@6c1e56ca[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]`

### Additional Information
In Selenium Java 4.14.0 CHANGELOG, there is a point as 'Shutdown executors created for a single tasks'. I think this causes issues for thread local test executions.

### How can we reproduce the issue?

```shell
1. Initialize a Thread Local driver instance.
2. Submit multiple Selenium tasks for parallel execution.
3. Each task initializes a ChromeDriver and performs a simple operation.
4. Quit the Driver at the end of each task.
5. The RejectedExecutionException occurs intermittently during execution.
```

### Relevant log output

```shell
java.io.IOException: java.util.concurrent.RejectedExecutionException: Task jdk.internal.net.http.common.SequentialScheduler$SchedulableTask@6de2a772 rejected from java.util.concurrent.ThreadPoolExecutor@6c1e56ca[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
```

### Operating System

Windows

### Selenium version

Java 4.14.0

### What are the browser(s) and version(s) where you see this issue?

Chrome Version 126.0.6478.127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 126.0.6478.126

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
We cannot fix old versions. Please try 4.22 and let us know how it goes. If you still find an issue, we need an automated script to reproduce it.

**Comment by HasiniRangana** [comment]
I tried with version 4.22.0. It had the same issue.

**Comment by diemol** [comment]
That's fine. We need a way to reproduce the issue. Please provide one.

**Comment by HasiniRangana** [comment]
Actually this is running on selenium grid. And I have drill down the issue and found out that initializing the driver by below way causes the said issue when quitting. 

```driver.set((RemoteWebDriver) RemoteWebDriver.builder().address(GRID_URL).oneOf(capabilities).config(ClientConfig.defaultConfig().readTimeout(Duration.ofSeconds(CONNECTION_TIMEOUT))).build());```

**Reproducible code -** 
```@Test
public void sample_test() throws MalformedURLException {
    ThreadLocal<RemoteWebDriver> driver = new ThreadLocal<>();
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setBrowserName("chrome");
    driver.set(new RemoteWebDriver(new URL("Grid URL"),capabilities));
    driver.get().get("https://www.google.com");
    driver.get().quit();
has context menu```
            
**Note - Initializing it like below doesn't causes this issue**

RemoteWebDriver driver = new RemoteWebDriver(new URL("Grid URL"),capabilities)

**Comment by HasiniRangana** [comment]
Hi @diemol , Are you able to look on this?

**Comment by diemol** [comment]
Not really. 

If the issue happens when you use `ThreadLocal<RemoteWebDriver> driver = new ThreadLocal<>();`, isn't it more related to the way you are handling those threads?

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is having this issue, please feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.
