### ISSUE TITLE
In Firefox, execution of javascript to get 'tagName' will stuck.

### ISSUE THREAD

**Issue by leiwang008** [SeleniumHQ/selenium#1426]
Environment: webdriver-standalone2.47.1 and Firefox42.0 on windows7.
To get a bunch of properties value, we execute javascript to put the properties [name, value] into a map. For other properties, the execution runs finely, but for property 'tagName', it will stuck. Below is a simple test to reproduce this problem.

		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		//DesiredCapabilities capabilities = DesiredCapabilities.chrome();//No problem with CHROME
		//DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();//No problem with IE

		capabilities.setJavascriptEnabled(true);
		//We should start the standalone driver on port 4444 manually.
		WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);

		driver.get("http://www.google.com");
		WebElement searchbox = driver.findElement(By.id("lst-ib"));

		String script = "function getHtmlProperties(domNode){\n"+
				"  var propMap={}; \n"+
				"  if( domNode!=undefined ){\n"+
				//"  propMap['tagname']=domNode.tagName;"+ //with 'tagname' as map key, execution will pass
				"  propMap['tagName']=domNode.tagName;"+ //with 'tagName' as map key, execution will stuck
				"  }\n"+
				"  return propMap;\n"+
				"}\n"+
				"\n return getHtmlProperties(arguments[0]); \n";
		
		Object result = ((JavascriptExecutor) driver).executeScript(script, searchbox);
		System.out.println(result);

		driver.close();

**Comment by barancev** [comment]
Fixed by commit d1e9b2760c1beb602d8b4071ab1aa2abcf825732
