### ISSUE TITLE
[🐛 Bug]: 4.22 on Server 2019

### ISSUE THREAD

**Issue by dodyryda** [SeleniumHQ/selenium#14261]
### What happened?

Error running selenium 4.22.0 on Win Server 2019 application crashes and webdriver fails to open with error reported in console Error starting process selenium-manager.exe. Rolling back to v 4.21.0 selenium runs normally. No error shown in window logs

### How can we reproduce the issue?

```shell
Run a V4.22.0 selenium app on Windows server 2019. I'm using chrome for testing latest stable release 126.0.6478.126
```

### Relevant log output

```shell
Error starting process selenium-manager.exe.
```

### Operating System

Win Server 2019

### Selenium version

V4.22.0 C#

### What are the browser(s) and version(s) where you see this issue?

CFT 126.0.6478.126

### What are the browser driver(s) and version(s) where you see this issue?

Chrome driver 126.0.6478.126

### Are you using Selenium Grid?

n/a

**Comment by dodyryda** [comment]
Windows version 1809 build 17763.5936

**Comment by nvborisenko** [comment]
@dodyryda please reproduce the same with logging enabled to capture more detailed report: https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by dodyryda** [comment]
I've rolled back the driver now so I can't. Just wanted to advise you of the issue..
________________________________

**Comment by nvborisenko** [comment]
> Error starting process selenium-manager.exe.

This is not enough even to start an investigation of root cause.

**Comment by dodyryda** [comment]
ok . i'll update the driver again and enable logging and upload the results here
________________________________
