### ISSUE TITLE
[🐛 Bug]: When I open this URL ("https://www.selenium.dev/") and scroll down upto "Donate to Selenium with PayPal" near footer then I find PayPal Images not displayed to me.

### ISSUE THREAD

**Issue by kunal-qaengineer** [SeleniumHQ/selenium#14264]
### What happened?

[🐛 Bug]: When I open this URL ("https://www.selenium.dev/") and scroll down upto "Donate to Selenium with PayPal" near footer then I find PayPal Images not displayed to me.

For more details please the image:

![Screenshot 2024-07-16 142558](https://github.com/user-attachments/assets/6fb74651-0908-449b-b19f-f444dc979c9e)

### How can we reproduce the issue?

```shell
Test Steps:
1. Open URL : https://www.selenium.dev/
2. Navigate to "Donate to Selenium with PayPal" at footer
3. see the PayPal image displayed or not.
4. You will not able to see Images.
```

### Relevant log output

```shell
Image should be displayed to users.
```

### Operating System

OS Name	Microsoft Windows 11 Pro Version	10.0.22631 Build 22631

### Selenium version

Java 21

### What are the browser(s) and version(s) where you see this issue?

Chrome 

### What are the browser driver(s) and version(s) where you see this issue?

Chrome

### Are you using Selenium Grid?

NO

**Comment by AutomatedTester** [comment]
Can you try in another browser? These are working for me. If it is working, can you see if disabling something like ublock fixes it?

**Comment by kunal-qaengineer** [comment]
@AutomatedTester,
It is only working in Firefox, I have check Window edge, Chrome [(Version 126.0.6478.127 (64 Bit)] , Brave Browser.


![image](https://github.com/user-attachments/assets/926c1a69-6fe7-41d8-b5b3-9b639693fc42)

**Comment by diemol** [comment]
That was leftover from the change we made in our sponsorship tiers. I have removed it. Thank you for reporting it.
