### ISSUE TITLE
[🐛 Bug]: Too tight dependency on typing-extensions

### ISSUE THREAD

**Issue by nijel** [SeleniumHQ/selenium#14278]
### What happened?

Upgrade from selenium 4.22.0 to 4.23.0 is impossible because of tightened dependencies on typing-extensions as observed in https://github.com/WeblateOrg/weblate/pull/12090:

> Because django-stubs==5.0.2 depends on typing-extensions>=4.11.0 and
> selenium==4.23.0 depends on typing-extensions>=4.9.0,<4.10.dev0, we can
> conclude that django-stubs==5.0.2 and selenium==4.23.0 are incompatible.

It seems to be used only for:

```py
from typing_extensions import deprecated
```

This is very unlikely to break between versions, so could the dependency be relaxed a bit? I think `typing-extensions>=4.9.0,<5` would work well in this case (this is basically the same as `typing-extensions=~4.9` used in 4.22.0).

This was changed by https://github.com/SeleniumHQ/selenium/pull/14187/commits/f69260d204f8c1722a5c07519e1ecb062c15d46a in https://github.com/SeleniumHQ/selenium/pull/14187.

### How can we reproduce the issue?

```shell
pip install django-stubs==5.0.2 selenium==4.23.0
```

### Relevant log output

```shell
The conflict is caused by:
    django-stubs 5.0.2 depends on typing-extensions>=4.11.0
    selenium 4.23.0 depends on typing_extensions~=4.9.0
```

### Operating System

Linux

### Selenium version

4.23.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by nijel** [comment]
I've made https://github.com/SeleniumHQ/selenium/pull/14279 with a proposed fix.

**Comment by devkral** [comment]
Additional note for the maintainers as they are likely more familiar with JS:

In python version resolving works quite different. It is not possible to have multiple versions of a package, so relaxed dependencies are normally used.

If you want to hard limit dependencies for tests it is maybe better to use hatch, poetry or pdm for having a test environment.
Except hatch all suggestions support lockfiles.

**Comment by mdmintz** [comment]
I created https://github.com/SeleniumHQ/selenium/pull/14297, to handle all dependencies that needed to be updated.
