### ISSUE TITLE
[🐛 Bug]: HAR (HTTP Archive) data is not being generated correctly

### ISSUE THREAD

**Issue by fmrahman** [SeleniumHQ/selenium#14281]
### What happened?

HAR data is not correct with selenium-webdriver@4.23.0 which comes as part of the [selenium-side-runner@4.0.8](https://www.npmjs.com/package/selenium-side-runner/v/4.0.8). It used to come correct with earlier version of selenium-side-runner@3.17.0. Raised issue in selenium-side-runner [1835](https://github.com/SeleniumHQ/selenium-ide/issues/1835). The HAR data does not reflect the expected structure and content, resulting in incomplete or malformed HAR files. It used to work fine in selenium-side-runner@3.17.0. I am using the API [chrome.devtools.network.getHAR()](https://developer.chrome.com/docs/extensions/reference/api/devtools/network#method-getHAR) to capture the HAR from my Chrome plugin. I am dumping the HAR data during the onLoad and onClick events.

Attached complete HAR files for reference.

[Selv3.17.0_HAR.txt](https://github.com/user-attachments/files/16314219/Selv3.17.0_HAR.txt)
[Selv4.0.8_HAR.txt](https://github.com/user-attachments/files/16314221/Selv4.0.8_HAR.txt)

Issue: 
Sample output of HAR captured in 4.0.8:
`{ "version": "1.2", "creator": { "name": "WebInspector", "version": "537.36" }, "pages": [], "entries": [ {`

Sample output of HAR captured in 3.17.0
`{"log":{ "version": "1.2", "creator": { "name": "WebInspector", "version": "537.36" }, "pages": [ { "startedDateTime": "2024-05-23T12:25:18.448Z", "id": "page_1", "title": "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login", "pageTimings": { "onContentLoad": 6203.97699996829, "onLoad": 6204.739999957383 } } ], "entries": [ {`

The difference is that 'pages' object is empty in the 4.0.8 version. Also, the number of entries in the 4.0.8 HAR file is lesser when compared with the 3.17.0 HAR file.

### How can we reproduce the issue?

```shell
Configuration: {
    baseUrl: 'https://www.google.com',
    capabilities: {
      browserName: 'chrome',
      acceptInsecureCerts: false,
      'goog:chromeOptions': {
        args: [Array],
        excludeSwitches: [Array],
        extensions: [Array],
        prefs: [Object]
      },
      proxy: {
        proxyType: 'manual',
        httpProxy: 'http://www-proxy.us.com:80',
        sslProxy: 'http://www-proxy.com:80',
        noProxy: []
      }
    },
    debug: true,
    debugConnectionMode: undefined,
    debugStartup: true,
    filter: '.*',
    force: undefined,
    maxWorkers: 4,
    screenshotFailureDirectory: undefined,
    projects: [
      '/runtime/proj1/.defaultSuite.side'
    ],
    proxyOptions: {
      http: 'http://www-proxy.us.com:80',
      https: 'http://www-proxy.com:80',
      bypass: []
    },
    proxyType: 'manual',
    retries: 0,
    runId: 'd2282489618d403ae237be668fa37afa',
    path: '/usr/lib/node_modules/',
    server: '',
    jestTimeout: 60000,
    timeout: 30000
  } 


bash-4.2$ npm ls -g selenium-webdriver
/usr/lib
`-- selenium-side-runner@4.0.8
  `-- @seleniumhq/side-runtime@4.0.12
    `-- selenium-webdriver@4.23.0
```

### Relevant log output

```shell
Sample HAR output where pages is empty.

{
  "version": "1.2",
  "creator": {
    "name": "WebInspector",
    "version": "537.36"
  },
  "pages": [],
  "entries": [
    {
      "_initiator": {
        "type": "script",
        "stack": {
          "callFrames": [
            {
```

### Operating System

Oracle Linux 7

### Selenium version

selenium-webdriver@4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 120.0.6099.224

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 120.0.6099.109

### Are you using Selenium Grid?

NA

**Comment by diemol** [comment]
Please create this issue at https://github.com/SeleniumHQ/selenium-ide

**Comment by fmrahman** [comment]
Already created the issue [1835](https://github.com/SeleniumHQ/selenium-ide/issues/1835) at  https://github.com/SeleniumHQ/selenium-ide and they said the issue is in selenium-webdriver. Will provide more information if required. Please check the [comment](https://github.com/SeleniumHQ/selenium-ide/issues/1835#issuecomment-2198058239) from the contributor.
@toddtarsi please explain the problem.

**Comment by diemol** [comment]
What is missing from the data? If you generate it directly using CDP, does it work properly? The IDE and Selenium just forward back and forth the commands.

**Comment by fmrahman** [comment]
The pages section is empty in HAR. Ideally it shouldn't be empty if there are entries. Attached the HAR data with missing pages in the bug description, please check.
`{ "version": "1.2", "creator": { "name": "WebInspector", "version": "537.36" }, "pages": [], "entries": [ { "_initiator": {`

What is CDP? Please help. May be I have not used.

**Comment by diemol** [comment]
https://chromedevtools.github.io/devtools-protocol/

I will comment on the other issue.
