### ISSUE TITLE
getOptions is not working when testing a web app with Selenium webdriver and Javascript

### ISSUE THREAD

**Issue by Ashok-Athens** [SeleniumHQ/selenium#1428]
I am testing a web app using selenium webdriver and Javascript.Here,I am trying yo use getOptions to get the number of options of a select element displayed.But it is not giving the result.I would be happy if anyone resolves this problem.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
