### ISSUE TITLE
[🐛 Bug]: Firefox JS Alert is closed automatically?

### ISSUE THREAD

**Issue by adeherdt-r7** [SeleniumHQ/selenium#14290]
### What happened?

Hello,

I'm working on a test suite in Ruby on Rails using Selenium, Capybara and Firefox as test browser.
At some point during the tests, the browser is supposed to click on a button, see the alert and accept it.
The problem is, this is not happening in firefox.

When I click the button manually, the alert actually shows, but when the test-framework tries it, nothing happens.
However, when I set a breakpoint on the step, where the button is clicked, I can see the alert appearing.
But as soon as the framework proceeds to the next step, the alert disappears and the step responsible for clicking it fails.

### How can we reproduce the issue?

```shell
* Write a simple page that triggers an alert on button click
* Have a step to trigger the alert
* Have a step to dismiss/accept the alert
* Run with firefox
```

### Relevant log output

```shell
-
```

### Operating System

macOS Sonoma 14.5

### Selenium version

selenium-webdriver (4.22.0)

### What are the browser(s) and version(s) where you see this issue?

Firefox 128.0

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by adeherdt-r7** [comment]
Additional information : https://github.com/serenity-bdd/serenity-core/issues/2470
The linked issue is exactly the same behavior I am running into.

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is having this issue, please feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.

**Comment by kkonopelko** [comment]
I have the same problem but only with chrome browser.
Writing automation tests with Selenium web driver(4.22), running on Windows 11, C#/.NET 8.

I had Selenium.WebDriver" Version="4.22.0" and Selenium.WebDriver.ChromeDriver" Version="126.0.6478.12600" in the solution of autotests. My Chromebrowser that installed on Windows had same version.

But 5 days ago my Chome browser on Windows got updated to the v = 127.0.6533.73 and tests start failed with issue: OpenQA.Selenium.NoAlertPresentException : no such alert (Session info: chrome=127.0.6533.73).

So, I did not change packages versions of selenium or ChromeDriver, updated only Chrome browser (not intentionally).

Test steps:

1. Open application
2. Go to some forms - make changes - try to refresh page
Expected: browser alert is shows up
Actual: no browser alert.

When I do same steps manually, the browser alert appears.

Also, I tried to update packages locally to selenium v 4.23 and driver = 127.0.6533.73. But it did not help.

Also I have anothe branch with tests, where I am trying new approach. And for that tests I run in the docker and with chrome-node 126 version. And no problem at all.

**Comment by GuillaumeBenini** [comment]
The issue seems to originate from here https://issuetracker.google.com/issues/42323796 and here https://github.com/w3c/webdriver/issues/1294#issuecomment-2176602474 where the W3C standard for user prompts wasn't applied correctly on Chromium and Firefox. 

This is in reference to this spec https://w3c.github.io/webdriver/#user-prompts 

> Whenever [active sessions](https://w3c.github.io/webdriver/#dfn-active-sessions) is a list containing exactly one item, and that item is a [HTTP session](https://w3c.github.io/webdriver/#dfn-http-session), but is not a [BiDi session](https://w3c.github.io/webdriver-bidi/#bidi-session), then in the [steps to fire beforeunload](https://w3c.github.io/webdriver/#dfn-steps-to-fire-beforeunload), implementations must act as if showing an unload prompt is likely to be annoying, deceptive, or pointless.
> NOTE
> This means that beforeunload prompts are never shown when there's an active HTTP-only session.
