### ISSUE TITLE
[🐛 Bug]: Unable to start chrome when enabling BiDi and setting custom user-data-dir

### ISSUE THREAD

**Issue by bonniotl-bpk** [SeleniumHQ/selenium#14299]
### What happened?

*I am not sure if I should post this issue in Selenium or ChromeDriver, but a pure Selenium workaround is available, see below.*

When enabling the Chrome BiDi API *and* setting a custom user-data-dir, Chrome closes unexpectedly with the following message:

```
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to initialize BiDi Mapper: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
```

This is because ChromeDriver tries to inject the "BiDi-CDP Mapper" in the first tab, and this first tab is actually different:
- With no user-data-dir specified, the first tab is set to `data:,`
- With a user-data-dir specified, the first tab is set to the default Chrome page (`chrome://new-tab-page`)

In the second case, the Content-Security-Policy is too strict and forbids BiDi Mapper injection.

**Workaround**

It is possible to force ChromeDriver to open on `data:,`, even when using a custom user-data-dir. Example in Python:

```python
prefs = {
  'session.restore_on_startup': 4,
  'session.startup_urls': ['data:,']
}
options.add_experimental_option('prefs', prefs)
```

### How can we reproduce the issue?

```shell
from selenium import webdriver
import time

options = webdriver.ChromeOptions()
options.add_argument('user-data-dir=/tmp/test-profile')
options.enable_bidi = True

driver = webdriver.Chrome(options=options)
time.sleep(10)
driver.quit()
```

### Relevant log output

```shell
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to initialize BiDi Mapper: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at generatePage (<anonymous>:872:1056)
    at <anonymous>:890:295
    at <anonymous>:890:1106
  (Session info: chrome=127.0.6533.72)
```

### Operating System

Ubuntu 22.04

### Selenium version

Python 4.22.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 127.0.6533.72

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 127.0.6533.72

**Comment by pujagani** [comment]
This sounds like a ChromeDriver issue.
