### ISSUE TITLE
Using selenium RC with selenium 2.48.2 opens 2 tabs in Firefox 43.0.3 

### ISSUE THREAD

**Issue by suprinder** [SeleniumHQ/selenium#1430]
When I do selenium.start() I see 2 tabs open on firefox and it does not open the testURL. I am using latest selenium 2.48.2 with firefox 43.0.3

So 2 issues
1. Opening of 2 tabs
2. Unable to open the test url specified. Below is the excerpt of my code

@Before
	public void setUp() throws Exception {
		selenium = new DefaultSelenium("localhost", 4444, "*chrome", "https://www.yahoo.com/");
		selenium.start();
	}

Anyone please help

Thanks

**Comment by antiphp** [comment]
See https://github.com/SeleniumHQ/selenium/issues/1385

**Comment by suprinder** [comment]
I am not clear. Issue 1385 talks about the webDriver. This issue has nothing to do with web driver. I am running Selenium RC. Maybe I am missing. Can you specific pinpoint the issue

Thanks

**Comment by cryptton2004** [comment]
I am encountering the same issue with selenium RC. First tab is: https://www.mozilla.org/en-US/firefox/43.0.1/firstrun/learnmore/

**Comment by osmirin** [comment]
I'm seeing the same issue on firefox 43.0 with Selenium RC described by suprinder and cryptton2004. 
Any idea when to expect a fix?

**Comment by rdc5174PSU** [comment]
I had this same problem and fixed it by using FireFox 28. It's likely your version of Selenium RC doesn't support your FireFox version.

**Comment by lukeis** [comment]
this was fixed recently:
289d28dc33788a475fc11b601aed6399466e292b

the next release of selenium will have the fix (no eta on a release)... or you can downgrade your browser to Firefox 42.
