### ISSUE TITLE
Selenium 2.48.x WebDriver#switchTo().frame() does not set driver.currentUrl

### ISSUE THREAD

**Issue by detlef-brendle** [SeleniumHQ/selenium#1432]
I upgraded to selenium 2.48.2 due to the fact that current firefox is not compatible with version 2.47.

Within my tests I have the following code:

 browser.driver.switchTo().frame('gwt-debug-pdfpreview-panel')
File pdf = new File(browser.getReportGroupDir(), "${filename}.pdf")
pdf.bytes = downloadStream().bytes

This does not work anymore with version 2.48.x

Investigation a bit seems that the switchTo().frame() does not update the driver.currentUrl variable anymore.

Is there a workaround for this issue ?

Thanks,
Detlef

**Comment by barancev** [comment]
The W3C standards demands this new semantics.

To get the current frame source URL you can use JavascriptExecutor:
```
String frameUrl = ((JavascriptExecutor) driver).executeScript("return window.location.href").toString();
```
