### ISSUE TITLE
[🐛 Bug]: [dotnet][Appium]The 'value > error' property was not found in the response

### ISSUE THREAD

**Issue by limuyuan** [SeleniumHQ/selenium#14335]
### What happened?

Not sure if it's good to submit an issue here, it's actually an Appium-related issue, however, the only place I can Googled is a recent change (5 months ago) in this repo.
https://github.com/SeleniumHQ/selenium/commit/3fab5fa261ac4ff3e8326c86649e7df2455e4b91#r144969175

We have a customized Appium server.
If user wants to test an iOS app, and the apps was signed with an untrusted enterprise certificate, there will be a pop-up on the device when launching an Appium session:
![image](https://github.com/user-attachments/assets/289f2efc-5ce9-4b9e-8faf-52f2bf8169a6)

We handled this situation, and return a 500 error on the API `/wd/hub/session` with the following response:
```
{"status":20999,"value":{"message":"The application could not be launched. You may first need to trust this app on the device."}}
```

If testing with the Appium inspector (version: 2022.1.2), the error message is properly displayed.
![image](https://github.com/user-attachments/assets/a361a811-a7d7-460e-a3b8-e04e1f76695c)

But when running the Appium test with dotnet, the exception message is always like:
```
    System.Exception : 'The 'value > error' property was not found in the response:
    {"status":20999,"value":{"message":"The application could not be launched. You may first need to trust this app on the device."}}'
     Failed to create iOS driver
```

It looks like it's expecting an "error" property from the response, but there is only a "message" property.

Maybe it's not a good idea to always expect this "error" property...

### How can we reproduce the issue?

```shell
Maybe trigger some error with Appium server
```

### Relevant log output

```shell
System.Exception : 'The 'value > error' property was not found in the response:
    {"status":20999,"value":{"message":"The application could not be launched. You may first need to trust this app on the device."}}'
     Failed to create iOS driver
```

### Operating System

Windows 11

### Selenium version

dotnet 4.20.0

### What are the browser(s) and version(s) where you see this issue?

Appium v2.11.2

### What are the browser driver(s) and version(s) where you see this issue?

Appium v2.11.2

**Comment by diemol** [comment]
You need to report this to the Appium project.

**Comment by limuyuan** [comment]
@diemol why Appium? Nothing was changed there, it's the changes here adding some extra lines of exception...

But I'm still okay with closing this issue, after reading the PR, the response should always contain `error` based on https://www.w3.org/TR/webdriver2/#errors

The impact is minor, but I still put it here in case someone has the same question.

**Comment by diemol** [comment]
Because the downstream needs to adapt to these changes. We also communicated the changes to them, if I remember correctly.
