### ISSUE TITLE
Actions.doubleClick() is not working correctly in Java Selenium WebDriwer 2.48.2

### ISSUE THREAD

**Issue by AlexanderArendar** [SeleniumHQ/selenium#1433]
Looks like something happened to Actions.doubleClick() in 2.48.2 version.
I had this util method working with 2.46:
> protected void doubleClickByXPath(String xpath){
> waitUntilVisibleByXPath(xpath);
> WebElement e = driver.findElement(By.xpath(xpath));
>Actions a = new Actions(driver);
>a.doubleClick(e);
>a.perform();
>}

So it stopped working after I've upgraded to 2.48.2.
If I comment last 3 lines and instead add
>e.click();
>e.click();

then it works.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is not reproduction case provided.
