### ISSUE TITLE
[🐛 Bug]: Fly.io

### ISSUE THREAD

**Issue by Adilmrqureshi** [SeleniumHQ/selenium#14339]
### What happened?

I started a selenium stand alone (selenium) server in fly.io using the docker container. However, when I send requests to the url the test are stuck in the queue and are not run.

![Screenshot 2024-08-03 153613](https://github.com/user-attachments/assets/0c11a51f-38f9-407d-9245-fc5d1c1bd91d)
![Screenshot 2024-08-03 153635](https://github.com/user-attachments/assets/c99e862e-66d1-4ed2-9e9e-38e0bb3f4a59)

### How can we reproduce the issue?

```shell
Create a folder with a dockerfile in it with the following contents: 

FROM selenium/standalone-edge:latest
WORKDIR /app

Then run fly launch, which will launch the docker container to fly.io.

Then make a connect to the server remotely programmatically. I do did so via the following code: 

$serverUrl = env('SELENIUM_URL', false);
$driver = RemoteWebDriver::create($serverUrl, DesiredCapabilities::chrome());
$driver->get('[any website of choice]');
$text = $driver->findElement(WebDriverBy::tagName('tbody'))->getText();
```

### Relevant log output

```shell
n/a
```

### Operating System

Windows 11

### Selenium version

selenium/standalone-chrome (image)

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome

### Are you using Selenium Grid?

4.23.0

**Comment by joerg1985** [comment]
@Adilmrqureshi you are trying to run a chrome session inside a edge container. Therefore there is no matching free slot and the session does stay in the que until the timeout is hit.

@diemol do you think it does make sense to set the `reject-unsupported-caps` for the standalone server? There should no new nodes register to the server, so these sessions could be instantly rejected.

**Comment by diemol** [comment]
I created a PR for this. I will be available in the next Docker Selenium release. 

Thanks for triaging, @joerg1985!
