### ISSUE TITLE
[🚀 Feature]: Disable search engine selection screen

### ISSUE THREAD

**Issue by skyhirider** [SeleniumHQ/selenium#14343]
### Feature and motivation

Chrome 127 shows a search engine selection screen (at least in Europe) every time the driver starts in non headless mode.

```
options.addArguments("--disable-search-engine-choice-screen");
```

The argument to override this should be on by default when launching the driver.

Resources
https://www.ghacks.net/2023/12/09/google-chrome-to-display-choose-your-search-engine-prompt/
https://stackoverflow.com/a/78788229/1341887

### Usage example

Add it to all Chrome sessions. User would not need to do anything and would not be surprised not being able to see the UI of what the bot is doing.

Would save time for everyone having to research the issue and add the override to their own config.

**Comment by joerg1985** [comment]
If this is done, a `removeArguments` method should be added in case someone must select the search engine.

**Comment by skyhirider** [comment]
Yes, thou I am not sure if you can do that via automation as pages were controlled normally I could just not see what was happening due do the popup.

I assume the search engine could be set by another command if needed or perhaps via the dev tools protocol.

**Comment by diemol** [comment]
We should not disable things in Chrome by default, which is why we have the method to add arguments ad hoc. 

An option would be to do a small blog post informing users about this. Would you like to contribute to that? (Together with the other one you created).

I will close this issue now, but we can continue the conversation.
