### ISSUE TITLE
Problem with Safari driver - timeouts

### ISSUE THREAD

**Issue by alexr1978** [SeleniumHQ/selenium#1434]
We always get timeouts when we try to login this site: automation.playbuzz.com
here are the details:
http://screencast.com/t/BxTwYjWH2xuD

Thanks!

**Comment by 5hawnknight** [comment]
what version of Safari? what version of Selenium?
in addition, what happens if you would use selenium to find and click your button instead of using JS?

**Comment by alexr1978** [comment]
5hawnknight ,
Thank you for your answer.
1. Safari - it happened for versions 6.0, 7.0, 8.0 and 9.0
2. Selenium - version 2.48
3. When I click instead of using Javascript, the behavior is inconsistent. Sometimes I get the same timeout and sometimes I get the error message that Safari cannot open the page because Safari can't establish a secure connection.


![safari](https://cloud.githubusercontent.com/assets/13927515/12423198/fac40df6-bed2-11e5-8185-3f64523895f0.GIF)

**Comment by alexr1978** [comment]
By the way, I'm not trying to go to "localhost"

**Comment by 5hawnknight** [comment]
in addition, could you share your code example?

**Comment by alexr1978** [comment]
Sure,
  WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));
            driver.Url = "http://alpha.playbuzz.com/userlogin";
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("elogin_email_field")));
            driver.FindElementById("elogin_email_field").SendKeys("share@playbuzz.com");
            driver.FindElementById("elogin_pass_field").SendKeys("playbuzz1");
            Thread.Sleep(3000);
            string command = "document.getElementsByClassName('elogin_submit_button')[0].click()";
            driver.ExecuteScript(command);
            Thread.Sleep(3000);
            wait.Until(ExpectedConditions.InvisibilityOfElementLocated(By.Id("login_popup_cover")));
            wait.Until(ExpectedConditions.ElementIsVisible(By.ClassName("create_button_wrapper")));

driver is instance of RemoteWebDriver

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
