### ISSUE TITLE
[🚀 Feature]: Disable downloading of 60+MB language crx files

### ISSUE THREAD

**Issue by skyhirider** [SeleniumHQ/selenium#14342]
### Feature and motivation

When initializing Chrome, every instance downloads over 60MB of language files.

This not only wastes bandwidth, but also disk space as if you're quickly starting and closing Chrome sessions these files tend to be left over as they are silently downloaded into your default downloads folder.

https://www.reddit.com/r/chrome/comments/u78vd0/chrome_has_constantly_been_downloading_something/

This behavior can be manually disabled via
```
--disable-features=OptimizationGuideModelDownloading,OptimizationHintsFetching,OptimizationTargetPrediction,OptimizationHints
```

I would recommend having this on by default for all sessions created.

Resources
https://github.com/cypress-io/cypress/issues/22622
https://issues.chromium.org/issues/40220332
chrome://download-internals/

### Usage example

I would run the driver as always, but Chrome would not download these files by default.

It would be transparent to the user.

**Comment by diemol** [comment]
We should not disable things in Chrome by default, which is why we have the method to add arguments ad hoc. 

An option would be to do a small blog post informing users about this. Would you like to contribute to that?

I will close this issue now, but we can continue the conversation.

**Comment by skyhirider** [comment]
If you tell me where and how to publish I can see if I can create an example that replicates it and write about it.

**Comment by diemol** [comment]
This is where the blog posts go https://github.com/SeleniumHQ/seleniumhq.github.io/tree/trunk/website_and_docs/content/blog/2024

**Comment by skyhirider** [comment]
@diemol here is the pull https://github.com/SeleniumHQ/seleniumhq.github.io/pull/1853
