### ISSUE TITLE
[🐛 Bug]: docker image selenium-edge container crash

### ISSUE THREAD

**Issue by arf27** [SeleniumHQ/selenium#14346]
### What happened?

I am creating a docker image from the selenium/standalone-edge:latest image, I have to add more things to this image but that is not the case at this moment, I am creating it with a dockerfile whose content is: 

FROM selenium/standalone-edge:latest

When I run a selenium test against this image, the edge browser closes without finding the reason, I have tried security things, etc...

If instead of creating my own image I use the official one, the browser never closes, I understand that docker does something that I don't know what it is, which causes the unexpected closure

### How can we reproduce the issue?

```shell
Create a dockerfile with the following content:

DE selenium/edge standalone: ​​latest

configure selenium:

RemoteWebDriver remoteDriverCH = null;

			ChromeOptions options = new ChromeOptions();
			options.addArguments("--start-maximized");		
			options.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
			options.addArguments("--remote-allow-origins=*");
			options.setPageLoadStrategy(PageLoadStrategy.EAGER);
		options.getCapability("--disable-dev-shm-usage");
			options.getCapability("--no-sandbox");

remoteDriverCH = new RemoteWebDriver(new URL(...), options);

controller = remotecontrollerCH;
			driver.manage().deleteAllCookies();
			controller.navigate().to(...);
			controller.manage().window().maximize();

I am using Selenium 4 so there is no need to download the driver for the browser.
```

### Relevant log output

```shell
22593001.584][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
[1722593003.908][SEVERE]: CreatePlatformSocket() failed: Address family not supported by protocol (97)
```

### Operating System

Ubuntu

### Selenium version

4

### What are the browser(s) and version(s) where you see this issue?

Edge

### What are the browser driver(s) and version(s) where you see this issue?

There is no specific driver, I understand that with Selenium 4 it creates the appropriate driver for the browser

**Comment by VietND96** [comment]
Is there typo in sample code snippet? It should be `addArguments` instead of `getCapability`
```
		options.addArguments("--disable-dev-shm-usage");
		options.addArguments("--no-sandbox");
```

**Comment by arf27** [comment]
Hello, that was it, I changed it and it worked, I tried with the selenium/standalone-chrome image and it worked fine, it only happened with the edge, I changed what you told me and it worked.

Thank you so much

**Comment by diemol** [comment]
Thanks for triaging, @VietND96!
