### ISSUE TITLE
[🚀 Feature]: Add Method to RemoteWebDriver for Downloading Files as Byte Array

### ISSUE THREAD

**Issue by Vei0vis** [SeleniumHQ/selenium#14347]
### Feature and motivation

I am proposing the addition of a new method to the Selenium `RemoteWebDriver` that allows for the downloading of files directly into memory as a `byte[]`. Currently, the `downloadFile` method in the `RemoteWebDriver` class requires specifying a target directory to save the file, which then needs to be read back into memory if in-memory processing is needed. This additional step of saving to and reading from a temporary directory adds unnecessary complexity and I/O overhead.

The motivation behind this feature is to streamline workflows where immediate in-memory processing of downloaded files is needed. By providing the file content as a `byte[]` directly, it will eliminate the need for temporary storage and make the process more efficient and straightforward. This is particularly useful in scenarios where downloaded files need to be processed or validated on the fly.

### Usage example

Here is how the proposed feature could be used in a Java code snippet:

```
// Current method requires specifying a target directory
((HasDownloads) driver).downloadFile(downloadableFile, targetDirectory);

// Proposed new method to get the file as byte array
byte[] fileData = ((HasDownloads) driver).downloadFile(downloadableFile);
```

**Comment by diemol** [comment]
You can still get the content from the `HttRespose` directly. There is an example in the documentation that allows you to do that.

https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node

We won't add the requested feature, as you can manipulate it in the example shown above.
