### ISSUE TITLE
chromedriver.cmd fails to launch with newer nodejs versions[🐛 Bug]: 

### ISSUE THREAD

**Issue by benm071** [SeleniumHQ/selenium#14353]
### What happened?

Trying to use selenium-webdriver against chrome instances fails  to launch chromedriver.cmd and thus chrome for testing when run on Windows 11 against newer nodejs instances (such as 18.20.2) due to a security patch made in nodejs that prevents spawn/spawnSync from launching .cmd or .bat without { shell: true }

See https://github.com/nodejs/node/issues/52681 for example

### How can we reproduce the issue?

```shell
Try to run any nodejs based test script using chrome/chromedriver on a Windows system with one of the security-patched nodes.  chromedriver.cmd will never launch because it fails internally to selenium-webdriver with a node EINVAL error (which is eaten and never displayed)
```

### Relevant log output

```shell
No output
```

### Operating System

Windows 11

### Selenium version

4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

chromdriver 127.x

### Are you using Selenium Grid?

No

**Comment by harsha509** [comment]
Hi @benm071,

Thank you for raising the issue.

I wasn’t able to reproduce it with the provided configuration (Windows 11, Node.js versions 18.20.2 and 20.16.0 LTS, Selenium WebDriver 4.23.0).

You can find the repo here: https://github.com/harsha509/issue-14353.

If the issue persists, could you please provide a **Short, Self-Contained, Correct (Compilable) Example** to help us investigate further?

Thanks,
Sri

**Comment by zlatinejc** [comment]
> Hi @benm071,
> 
> Thank you for raising the issue.
> 
> I wasn’t able to reproduce it with the provided configuration (Windows 11, Node.js versions 18.20.2 and 20.16.0 LTS, Selenium WebDriver 4.23.0).
> 
> You can find the repo here: https://github.com/harsha509/issue-14353.
> 
> If the issue persists, could you please provide a **Short, Self-Contained, Correct (Compilable) Example** to help us investigate further?
> 
> Thanks, Sri

Hi,
I have to reignite this issue as it is not working.

I reran your tests and they fail the same as mine.

![image](https://github.com/user-attachments/assets/8fa7e4bd-de2c-474f-8366-1435d9ba3277)

I am running:
- Node 18.17.1
- selenium-webdriver: 4.23.0
- Chrome: 127.0.6533.120 (Official Build) (64-bit)

**Comment by Delta456** [comment]
Does the issue still persists?

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
