### ISSUE TITLE
type or sendKeys commands not working on Rich Text Format 

### ISSUE THREAD

**Issue by lokeshreddy1706** [SeleniumHQ/selenium#1435]
I want to type some text in Rich Text Format. Both type or sendKeys commands didn't work for me.
sendKeys Throw an error saying   "Unexpected Exception: TypeError: a.value is undefined. "
can anyone help me to resolve  the issue.
![screenshot from 2015-12-30 13 19 31](https://cloud.githubusercontent.com/assets/8534808/12047835/2eb557cc-aef8-11e5-9faf-6d08f50819ca.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
