### ISSUE TITLE
[🐛 Bug]: Not able to open the devtools session twice in ruby selenium

### ISSUE THREAD

**Issue by Mohanram3012** [SeleniumHQ/selenium#14350]
### What happened?

The dev tools session is opened and i'm using it for intercepting the network request and response . I'm using ruby selenium for the above . After intercepting the driver is stuck since we are capturing the request and responses. To get the value of the intercepted request we need to close the dev tools session . We tried several ways and finally `driver.devtools.close` is closing the session and i'm able to move further . But with the same driver instance when i try to reopen the dev tools session i'm getting IO connection closed error . Need to reopen the dev tools session 

### How can we reproduce the issue?

```shell
driver.intercept do |request, &continue|
            @intercepted_logs << {request: {
             method: request.method,
             url: request.url,
             post_data: request.post_data,
             headers: request.headers
           }}
           continue.call(request)
        end
        // some code 
       driver.devtools.close
       // trying to reopen the connection with the same driver
       driver.intercept
```

### Relevant log output

```shell
IOError: closed stream
from /Users/mok/.rvm/gems/ruby-3.2.2@rubyupgrade/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/websocket_connection.rb:61:in `write'
```

### Operating System

Macos

### Selenium version

Selenium 4.10 seleniumdevtools 0.126

### What are the browser(s) and version(s) where you see this issue?

Chrome 126

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 126.0

### Are you using Selenium Grid?

No

**Comment by Mohanram3012** [comment]
The ruby version for the above issue is ruby 3.2.2

**Comment by pujagani** [comment]
I suspect that calling close closes the underlying websocket and hence the error. We added a check in Java, to open the websocket again if it is closed when a devtools session is created again for the same driver. Maybe that needs to be added to Ruby. Though, we are focusing to transitioning to W3C BiDi implementation, so not sure if it is the best use of resources to add this bit.

**Comment by pujagani** [comment]
@p0deje @titusfortner What do you think?

**Comment by p0deje** [comment]
You should not really close the connection manually. This is concerning to me:

> After intercepting the driver is stuck since we are capturing the request and responses

Can you elaborate on the issue? As long as you properly use `continue.call(...)` the driver should not stuck and you should be able to inspect the request/response accordingly.

**Comment by Mohanram3012** [comment]
HI @p0deje  yeah the continue call is allowing the next line of code to execute and the request and responses are captured but we don't have any way to reopen the connection or reuse the driver.intercept . For a single driver instance we are not able to intercept twice . our assumption here is we need to capture and validate the request and upon continuing we need to capture and validate the response . This gets a hit when we use driver.intercept twice or using it after closing the devtools session again

**Comment by p0deje** [comment]
@Mohanram3012 I see what you are saying. The thing with `intercept` is that it won't work with 2 calls - you have to call it only once, otherwise, all sorts of weird issues like that can happen. Is there any specific reason why you need to call it twice and cannot consolidate these 2 calls within a single one?

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.

**Comment by Mohanram3012** [comment]
hi @diemol  i'm reopening this issue as we have to find a solution

**Comment by diemol** [comment]
I can reopen it if you continue giving feedback, if not then it does not make sense.

**Comment by Mohanram3012** [comment]
Yeah i gave the code which i used while calling the driver. intercept again its throwing issue . 

Why do i need to have the call twice ? 

Ans : We have POM structure as we need to have the intercept in many cases to ensure that the request and responses are sent & received properly 

We can open once and use the same variable many times but the log is overloaded and requires a considerable amount to save 
If i have to use it separately then i can assign to temp variables and trash it whenever needed

**Comment by p0deje** [comment]
The problem with mulitple network intercepts is the following - if we have 2 blocks that intercept ALL requests, which one has to continue them (call `continue.call`)? If it's the first one, the second one will crash when attempting to continue it. Also, there is no guarantee of the order these 2 will be called because it all happens asynchronously.

With that said, your best shot is to consolidate request intercepting in a singleton class and use it across all POMs.
