### ISSUE TITLE
[🐛 Bug]: "selenium-devtools" ruby gem v0.127.0 is not publised

### ISSUE THREAD

**Issue by sudoudaisuke** [SeleniumHQ/selenium#14360]
### What happened?

Hello.

On the rubygems site, the latest version of "selenium-devtools" is 0.126.0 as of August 9, 2024.
The release notes for selenium-webdriver indicate that Chrome v127 is supported.

https://rubygems.org/gems/selenium-devtools

Looks to me like you are ready to release v0.127.0 with the github documentation.
- https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/devtools/README.md
- https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/devtools/BUILD.bazel
- https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/devtools/version.rb

### How can we reproduce the issue?

```shell
see rubygems website.

https://rubygems.org/gems/selenium-devtools
```

### Relevant log output

```shell
.
```

### Operating System

Ubuntu

### Selenium version

Ruby 4.23.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 127.0.6533.99

**Comment by diemol** [comment]
Thank you for reporting this. We did miss to publish it, but it is now there: https://rubygems.org/gems/selenium-devtools/versions/0.127.0
