### ISSUE TITLE
Opera webdriver: Quit() lets the browser running

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#1436]
There is a problem in the Opera webdriver :

Calling driver.Quit() shuts down correctly the webdriver but may let the Opera browser running.

Important:
This happens ONLY if you set the path to the executable with:
OperaOptions.BinaryLocation = "C:\Program Files\Opera\launcher.exe";

while when setting the path to
OperaOptions.BinaryLocation = "C:\Program Files\Opera\34.0.2036.25\opera.exe";

it will work correctly.

Selenium users will not understand what is wrong there: The browser starts, all tests execute correctly but at the end the browser keeps running forever.

SOLUTION:
The Selenium driver should throw an exception if the user passes a path to "....\launcher.exe" instead of the "....\opera.exe".

**Comment by lukeis** [comment]
for issues with Opera driver please log them with the OperaDriver project:

https://github.com/operasoftware/operachromiumdriver
