### ISSUE TITLE
[🐛 Bug]: Running Selenium inside AWS Lambda function - unable to obtain driver for Chrome

### ISSUE THREAD

**Issue by jennyd77** [SeleniumHQ/selenium#14361]
### What happened?

I am using Selenium to interact with a website. The code is python and runs in an AWS Lambda function.
Note that when I run the code outside of Lambda (natively on my macbook), it works fine.
I have packaged selenium 4.23.1 as a Lambda layer and all selenium imports work as expected in Lambda, however the following line "browser = webdriver.Chrome(options=options)", throws error "Message: Unable to obtain driver for chrome"

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--headless=new')
options.add_argument('--no-sandbox')
options.add_argument('--single-process')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--remote-debugging-port=9222')
options.add_argument('--disable-infobars')
options.add_argument("--disable-dev-tools")

browser = webdriver.Chrome(options=options)
```

### Relevant log output

```shell
{"errorMessage": "Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n", "errorType": "NoSuchDriverException", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n", "  File \"/var/task/app.py\", line 36, in <module>\n    browser = webdriver.Chrome(options=options)\n", "  File \"/opt/python/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n", "  File \"/opt/python/selenium/webdriver/chromium/webdriver.py\", line 50, in __init__\n    if finder.get_browser_path():\n", "  File \"/opt/python/selenium/webdriver/common/driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n", "  File \"/opt/python/selenium/webdriver/common/driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"]}
```

### Operating System

macos arm64

### Selenium version

Python 3.12

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Don't know - my understanding is that Selenium handles the provision of Chromedriver

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Selenium uses [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) to configure the driver and browser for your session. 

There might be a network issue or a resource problem inside the function. To better understand the error and adjust your environment, you can enable [debug logging](https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/). 

If you need more help getting it working, we recommend using one of the links below.
