### ISSUE TITLE
Firefox (installed by the Mac's homebrew) has a different path

### ISSUE THREAD

**Issue by ph-hs** [SeleniumHQ/selenium#1437]
~/Applications/Firefox.app/

That should be check in addition to /Applications/Firefox.app/ in my opinion. As a fallback obviously.

> # to install
> 
> brew cask install firefox

**Comment by lukeis** [comment]
@ph-hs we could possibly add this fallback... we'd need to add it to each of the language bindings too, any in particular you cared about? (java, python, ruby, javascript, .NET)

**Comment by ph-hs** [comment]
I checked out the source, and started working on the Java one (tried to break a test first), but CrazyFun was hanging as it went through the tests :-(  My intention was to work it though for all applicable clients. 

In answer to your Q, Java is most important to me.

**Comment by lukeis** [comment]
added to java and python:  21bbdf51b8b1ed35926887f51933a5f6256beaa5

I'll leave this open for ruby, .NET, javascript.

**Comment by lukeis** [comment]
ruby apparently by default explores all of someone's PATH by default... so it just needs to be set there for ruby people

**Comment by ph-hs** [comment]
Ruby on Mac still needs to do ~/Applications/Firefox.app/Contents/MacOS/firefox and /Applications/Firefox.app/Contents/MacOS/firefox as not everyone sets their path:

    Pauls-MacBook-Pro:Foo phammant$ firefox 
    -bash: firefox: command not found

**Comment by lukeis** [comment]
@titusfortner see previous comment :)

**Comment by titusfortner** [comment]
Honestly, I'm reluctant to add code that is only used by an application that recognizes that [it is doing it wrong](https://github.com/caskroom/homebrew-cask/issues/13201) and plans to change. 
Symlinks should work, or ```Selenium::WebDriver::Firefox::Binary.path = '~/Applications/Firefox.app/Contents/MacOS/firefox'```
That being said, it is only one line of code, and [you are not the only one](http://stackoverflow.com/questions/28130038/selenium-webdriver-cant-find-firefox-when-installed-with-homebrew-cask).

**Comment by titusfortner** [comment]
This should do it for Ruby: https://github.com/SeleniumHQ/selenium/commit/b76925dc98a86e885aac243e763a35aea846e593

**Comment by jleyba** [comment]
By default, the JS bindings will check the default installation directory for each platform. Users that install Firefox elsewhere must specify that location through the API. This is an intentional design decision.

**Comment by ph-hs** [comment]
Well if their going to change to /Applications, then fine.

**Comment by BertLamb** [comment]
dotnet driver already is checking `/Applications/Firefox.app/Contents/MacOS` as well as `~/Applications/Firefox.app/Contents/MacOS` so if this is the only driver that is outstanding for this issue, then I believe it can be closed.

https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Firefox/Internal/Executable.cs#L167

**Comment by barancev** [comment]
Closing the issue after the last comment (left unnoticed for long time)
