### ISSUE TITLE
[🐛 Bug]: Error starting process: C:\chrome_bot\selenium-manager\windows\selenium-manager.exe

### ISSUE THREAD

**Issue by deathking6180** [SeleniumHQ/selenium#14382]
### What happened?

Hi, I'm having difficulty creating my first Selenium Chrome bot. Anytime I run the reproducible code, I get the same error. I've also just tried running ```C:\chrome_bot\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json``` which also fails with the same result.

This is my first selenium bot so I'm just trying to do some testing of it to get familiar with it.

I've got the latest chromedriver.exe within the C:\chrome_bot directory.

### How can we reproduce the issue?

```c#
using OpenQA.Selenium.Chrome;
namespace chrome_bot
{
    public class Program
    {
        private static void Main(string[] args)
        {
            ChromeDriver driver = new ChromeDriver();
            driver.Url = args[0];
            Console.ReadKey();
            driver.Quit();
        }
    }
}
```

### Relevant log output

```shell
C:\chrome_bot>.\chrome_bot.exe "https://facebook.com"
Unhandled exception. OpenQA.Selenium.WebDriverException: Error starting process: C:\chrome_bot\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
 ---> OpenQA.Selenium.WebDriverException: Selenium Manager process exited abnormally with 65 code: C:\chrome_bot\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
  "logs": [
    {
      "level": "ERROR",
      "timestamp": 1723488178,
      "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)"
    }
  ],
  "result": {
    "code": 65,
    "message": "error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)",
    "driver_path": "",
    "browser_path": ""
  }
}

<<

   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments)
   at OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   at OpenQA.Selenium.DriverFinder.BinaryPaths()
   at OpenQA.Selenium.DriverFinder.GetDriverPath()
   at OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor()
   at chrome_bot.Program.Main(String[] args) in C:\Users\Jack Pinkerton\source\repos\bot_repo\chrome_bot\Program.cs:line 10
   at chrome_bot.Program.<Main>(String[] args)
```

### Operating System

Windows 10

### Selenium version

.NET 4.23.0

### What are the browser(s) and version(s) where you see this issue?

Google Chrome 127.0.6533.100

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 127.0.6533.99

### Are you using Selenium Grid?

N/A

THANKS FOR THE SUPPORT

**Comment by nvborisenko** [comment]
@deathking6180 please make sure https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json is available on the environment where you execute your program.

@bonigarcia do you think error message can be improved to include exact cause why network request failed?

**Comment by deathking6180** [comment]
Hello @nvborisenko thank you very much for the quick response. How can I ensure it's available on the machine?
I can manually go to it within Google Chrome and receive the expected output of all the chrome driver versions.

**Comment by nvborisenko** [comment]
On the environment (machine) where the code is executing.

**Comment by deathking6180** [comment]
Correct on the environment (machine) where the code is executing, I can open google chrome and go to that URL and view all the expected output. I've also ensured that my proxy settings for the machine are off since the code I provided does not use a proxy either.

Correction - I've turned the proxy off but didn't seem to take effect until after reboot. I may need to enable the proxy for selenium.

I've just researched and found different methods for this either by doing chrome_options.Proxy = ... or chrome_options.AddArgument()

Which is the correct method?

**Comment by nvborisenko** [comment]
Proxy... Probably it helps: https://www.selenium.dev/documentation/selenium_manager/ - you should let Selenium Manager know that remote endpoint is behind of proxy. Most likely `SE_PROXY` env variable is your friend.

**Comment by deathking6180** [comment]
Adding proxy solved issue. Thank you @nvborisenko

**Comment by nvborisenko** [comment]
@bonigarcia please pay attention on the error message, it can be really improved. Thank you!

**Comment by deathking6180** [comment]
@nvborisenko one more question related to firewalls. I noticed this line ```Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 55774```

The port changes on each run. For inbound firewall rules, do I have to always allow inbound connections on the port the driver is running on to have successful driver execution.

In this example, will my firewall have to allow inbound connections on port 55774 to successfully work?

**Comment by nvborisenko** [comment]
Port is always "random". I guess you can configure your firewall to allow connections for `selenium-manager.exe` program.

**Comment by bonigarcia** [comment]
> do you think error message can be improved to include exact cause why network request failed?

That error message comes from the dependency that Selenium Manager uses to handle network requests, which is called reqwest. I looked for some way to display the error cause, and I discovered an easy way to include it (as reported by reqwest). This way, an error message like the following:

```
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
```

... will be expanded to something like:

```
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)

    Caused by:
        0: client error (Connect)
        1: dns error: No such host is known. (os error 11001)
        2: No such host is known. (os error 11001)
```

I can prepare a PR about that.
