### ISSUE TITLE
typo on download website

### ISSUE THREAD

**Issue by lferro9000** [SeleniumHQ/selenium#1439]
http://docs.seleniumhq.org/download/

Has a superfulous "ru" in the middle of the html.

**Comment by ddavison** [comment]
fixed in https://github.com/SeleniumHQ/www.seleniumhq.org/commit/26d7897e995762309f689317df800f6d3aebbbd9

For any future issues with the website, please write issues to https://github.com/seleniumhq/www.seleniumhq.org  .  thanks for reporting this!
