### ISSUE TITLE
[🐛 Bug]: proxy capabilities not retained after mering into options

### ISSUE THREAD

**Issue by turnitin-rshanker** [SeleniumHQ/selenium#14404]
### What happened?

after merging capabilities into options , capabilities lost partially especially the proxy caps

### How can we reproduce the issue?

```shell
creating proxy caps:    
DesiredCapabilities capabilities = new DesiredCapabilities();
    ChromeOptions options = new ChromeOptions();

      Proxy seleniumProxy = new Proxy();
      seleniumProxy.setHttpProxy("localhost:" + proxyServer.getPort());
      seleniumProxy.setSslProxy("localhost:" + proxyServer.getPort());

      capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
merging into options:
    options.merge(capabilities);
```

### Relevant log output

```shell
see the screenshots attached
```

### Operating System

macos sonoma

### Selenium version

java 17 and selenium 4.23.1

### What are the browser(s) and version(s) where you see this issue?

chrome 127.0.0

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 127.0.6533.119 

### Are you using Selenium Grid?

no

**Comment by turnitin-rshanker** [comment]
capabilities = {proxy=Proxy(manual, http=localhost:64680, ssl=localhost:64680)}
after merging into options:
Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --disable-dev-shm-usage, --no-sandbox, --disable-infobars, --test-type, --disable-extensions, --disable-web-security, --allow-running-insecure-co..., --ignore-certificate-errors, --disable-popup-blocking, --disable-prompt-on-repost, --window-size=1920,1200, --headless=new, --disable-background-networ..., --disable-client-side-phish..., --disable-features=TranslateUI, --metrics-recording-only, --password-store=basic, --use-mock-keychain], binary: /Applications/Google Chrome..., excludeSwitches: [disable-popup-blocking], extensions: [], prefs: {credentials_enable_service: false, plugins.always_open_pdf_externally: true, profile.default_content_setting_values.automatic_downloads: 1, profile.default_content_settings.popups: 0, profile.password_manager_enabled: false, safebrowsing.enabled: true}}, pageLoadStrategy: eager}

I see no proxy section in here

**Comment by pujagani** [comment]
Merge returns a new instance, that will have all the merged capabilities. Please use the returned value. 

Example working snippet:

```
    DesiredCapabilities capabilities = new DesiredCapabilities();
    ChromeOptions options = new ChromeOptions();

    Proxy seleniumProxy = new Proxy();
    seleniumProxy.setHttpProxy("localhost:" + 4444);

    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

    options = options.merge(capabilities);

    System.out.println(options);
```

**Comment by turnitin-rshanker** [comment]
@pujagani thanks
