### ISSUE TITLE
[🚀 Feature]: extend interface HttpHandler with `executeAsync` method

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#14403]
### Feature and motivation

This will allow to write none blocking methods in the backend without spawning threads in these places and handle this, e.g. `Node.touchSessionAsync`.

### Usage example

Everytime a websocket message is proxied between the node and the driver the implementation waits until the session map has performed the touch to keep the session alive. This delay could be removed by touching the session async.

When BiDi is in place and alot of websocket message are proxied this might get a bottleneck in interception of network traffic or other frequent browser events.

**Comment by joerg1985** [comment]
I could create a PR for this in case you think this makes sense, but i do not want to waste time on it in case you think this is not needed.

**Comment by diemol** [comment]
Thank you, @joerg1985. This makes sense.

**Comment by joerg1985** [comment]
I have create a PR for this with one change, i have extended the HttpClient interface.
The HttpHandler is used in a lot of areas that do not benefit from this change.

**Comment by joerg1985** [comment]
The HttpClient has been extended with the new method.
