### ISSUE TITLE
[🐛 Bug]: [WinError 50] The request is not supported

### ISSUE THREAD

**Issue by zuzell** [SeleniumHQ/selenium#14419]
### What happened?

Running this code failed with the error presented above.

```
    options = webdriver.ChromeOptions()
    options.add_argument("--remote-debugging-port=9222")
    driver = webdriver.Chrome(options=options)
    driver.get(url)
```
  
 Webdriver and chrome versions are compatible (127).   
    

### How can we reproduce the issue?

```shell
options = webdriver.ChromeOptions()
    options.add_argument("--remote-debugging-port=9222")
    driver = webdriver.Chrome(options=options)
    driver.get(url)
```
```


### Relevant log output

```shell
Exception managing chrome: error sending request for url (
https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
[WinError 50] The request is not supported
```

### Operating System

Windows 10

### Selenium version

selenium==4.23.1, Python 3.9

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

 Chromedriver 127.0.6533.119

**Comment by diemol** [comment]
Are you behind a proxy? Check https://www.selenium.dev/documentation/selenium_manager/#known-limitations

**Comment by zuzell** [comment]
Thank you for the advice. I added a proxy settings and it works now :)
