### ISSUE TITLE
my record button is not working and i am getting error messages 

### ISSUE THREAD

**Issue by kanesh83** [SeleniumHQ/selenium#1441]
selenium ide version 2.9.1
firefox version 43.0.3

*_issue *_
i am not able to click on record and i get this error wheni try to open my test suite 
"There was an unexpected error. Msg: TypeError: window.editor.app is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1"

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
