### ISSUE TITLE
[🐛 Bug]: After webdriver.close and quit(), reinstantiating ChromeDriver throws SessionNotCreatedException(JAVA)

### ISSUE THREAD

**Issue by Serimert90** [SeleniumHQ/selenium#14435]
### What happened?

I instantiate my driver as below;
```
options.setExperimentalOption("excludeSwitches", new String[] { "enable-automation" });
options.setExperimentalOption("useAutomationExtension", false);
options.addArguments("--disable-blink-features");
options.addArguments("--disable-blink-features=AutomationControlled");
options.addArguments("--disable-dev-shm-usage");
options.addArguments("--no-sandbox");
options.addArguments("--start-maximized");
options.addArguments("--user-agent=" + userAgent);
options.addArguments("--disable-web-security");
options.addArguments("--user-data-dir=" + dataDir);
FileUtils.deleteDirectory(dataDirFile); // i always empty the datadir folder at options part
driver = new ChromeDriver(chromeService, options);
```
then i quit as below;
```
driver.close();
driver.quit();
driver = null;
```

After quitting like above, when i try to reinstantiate **with same options** i get **_SessionNotCreatedException_**

> Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

What i tried both with or without below;
```
options.setExperimentalOption("detach", true);
options.addArguments("--remote-debugging-port=" + stealthBotOptions.getRemoteDebuggingPortNext());

// tried stopping service too
chromeService.stop();
chromeService.close();
```
Note: I also tried to give different port everytime i "**instantiate**"

I also tried killing all chrome related processes (in quit as above) as below
```
Process process = Runtime.getRuntime().exec("cmd.exe /c taskkill /im chromedriver.exe /f & ver > nul");
process.waitFor();
process.destroy();
process = Runtime.getRuntime().exec("cmd.exe /c taskkill /im chrome.exe /f & ver > nul");
process.waitFor();
process.destroy();
```

### How can we reproduce the issue?

```shell
Try my instantiating code like above.
```
When i start in debug mode in intellij, **_THIS bug never happens_**. It only happens in fat jar or normal run in idea.
**Found the culprit**: Try instantiating chrome driver object **with** chromeService. Still it is weird that idea debug mode is healthier than normal mode? 
**---> Broken**
```
if (chromeService != null)
            driver = new ChromeDriver(chromeService, getChromeOptions());
```  

 **---> Ok**
```
else
           driver = new ChromeDriver(getChromeOptions());
```
**Verdict**: After chromeService or driver.stopped, the chromeservice also needs to be reinstantiated with its builder before given to Driver such as `new ChromeDriverService.Builder().build();`

### Relevant log output

```shell
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'Some pc', ip: '******' (192 ip not localhost)
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--start-maximized, --disable-web-security, --disable-blink-features, --disable-blink-features=Au..., --disable-dev-shm-usage, --no-sandbox, --user-agent=Mozilla/5.0 (W..., user-agent=Mozilla/5.0 (Win..., --remote-debugging-port=9402, --user-data-dir=C:/DEV/sele...], excludeSwitches: [enable-automation], extensions: [], useAutomationExtension: false}, pageLoadStrategy: normal, proxy: Proxy(manual, http=14a19aaf...}]}]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
	at
```

### Operating System

Windows 10

### Selenium version

4.23.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 128

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 128

**Comment by pujagani** [comment]
Thank you for the details. If you are instantiating a ChromeDriverService and then stopping it. The expectation would be to manage its lifecycle if you want to reuse it again. So once you stop it, and reinstantiate the same ChromeDriver instance with the same service that is stopped, it won't work. You will need to start the ChromeDriverService again and pass that. 

Your verdict is correct. 

I might have misunderstood so please help me understand your concern here.

**Comment by Serimert90** [comment]
Thanks for clarifying. If it is expected, i have nothing to say. 

Best Regards

**Comment by Serimert90** [comment]
.
