### ISSUE TITLE
Firefox can't find the file at chrome://src/content/RemoteRunner.html?

### ISSUE THREAD

**Issue by apmanol** [SeleniumHQ/selenium#1444]
Hello all, 

recently I updated my linux distribution to the latest version and suddenly all my selenium tests stopped working. Still I can't identify what is the difference in the setup so as to spot the cause of the problem. 

The problem is that the Firefox spawns, but it doesn't proceed with the selenium test execution with the following error:

```
Firefox can't find the file at chrome://src/content/RemoteRunner.html?sessionId=3ea54ef0e48e4861b1cdcda73af2fdbf&multiWindow=true&baseUrl=http://192.168.171.193/login.html&debugMode=false&driverUrl=http://localhost:4444/selenium-server/driver/.
```

The selenium server version is  *2.48.2*
Firefox version: *43.0.3*
robotoframework/seleniumlibrary: *2.9.2*

Any tip to help identify the problem, will be more than welcome.

**Comment by lukeis** [comment]
Sorry, Selenium RC is deprecated and no longer supported. You can try to solicit the Selenium-users mailing list: https://groups.google.com/forum/#!forum/selenium-users

We no longer accept issues for Selenium RC (but pull requests may be considered)

**Comment by lukeis** [comment]
but looks like @barancev fixed it ;)

289d28dc33788a475fc11b601aed6399466e292b

**Comment by barancev** [comment]
Unfortunately Firefox 44 is going to break it again...

**Comment by apmanol** [comment]
You rock guyz! Thanks a lot!

**Comment by muraliMohanT** [comment]
I have also got the same problem and the following procedure has solved the issue.

check firefox version on ubuntu using the following command.
firefox --version
Only firefox  prior to version 42 only supports selenium.
If the version of firefox on ubuntu is greater than 42, then follow the commands below to install firefox42.

Open Terminal and run the following commands to install Firefox on 32 bit Linux Ubuntu Systems:

 $ wget https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/42.0/linux-i686/en-US/firefox-42.0.tar.bz2
 $ tar -xjvf firefox-42.0.tar.bz2
 $ sudo rm -rf /opt/firefox*
 $ sudo mv firefox /opt/firefox
 $ sudo ln -sf /opt/firefox/firefox /usr/bin/firefox
 

Open Terminal and run the following commands to install Firefox on 64 bit Linux Ubuntu Systems:

 $ wget https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/42.0/linux-x86_64/en-US/firefox-42.0.tar.bz2
 $ tar -xjvf firefox-42.0.tar.bz2
 $ sudo rm -rf /opt/firefox*
 $ sudo mv firefox /opt/firefox
 $ sudo ln -sf /opt/firefox/firefox /usr/bin/firefox

---- Murali Mohan T

**Comment by unyo** [comment]
This is occurring again on Firefox 48.

Possibly related, for those trying to upgrade to the latest standalone jar: https://github.com/seleniumhq/selenium/issues/2616

**Comment by ramoraes** [comment]
# @

- [ ] 

- [1. ](

> _**## url**_

)
