### ISSUE TITLE
Slowness reported with selenium 2.45.0

### ISSUE THREAD

**Issue by santoshkothapalli** [SeleniumHQ/selenium#1445]
We are investigating the slowness with the driver and our investigations lead to the defect in the code in cpp/webdriver-interactions/interactions.cpp , we are forced to wait upto 5 seconds for every keystroke. can this time be reduced for faster execution.

Also the pressed is always false and is not been reset to true any where. 

209     clock_t maxWait = clock() + 5000; 
210     while (!pressed) { 
211       wait(5); 
212       if (clock() >= maxWait) { 
213         LOG(WARN) << "Timeout awaiting keypress: " << keyCode; 
214         break; 
215       } 
216     } 
217 }

**Comment by jimevans** [comment]
The proper fix to this is to use the 32-bit IE driver, even on 64-bit Windows. For IE 10 and 11, the content process where keys are being typed is almost always 32-bit, even when you assume you're using 64-bit IE.

**Comment by santoshkothapalli** [comment]
This is reported when we are using 32 bit driver

**Comment by jimevans** [comment]
Then you've managed to (incorrectly) configure IE in such a way that you're getting a 64-bit content process. What happens if you use the 64-bit IE driver?

**Comment by santoshkothapalli** [comment]
Do we have any link which explains about how to configure IE
