### ISSUE TITLE
[🚀 Feature]: Make a separate patch release for the patch release artifacts

### ISSUE THREAD

**Issue by chenrui333** [SeleniumHQ/selenium#14458]
### Feature and motivation

From the downstream packaging perspective, we are use a generic livecheck to consume the version information, but it would be disrupted when the version info is not consistent between the tag and the release artifact, hence it would be good to also create releases for the patches releases. Let me know if that makes sense.

relates to:
- https://github.com/Homebrew/homebrew-core/pull/182960
- https://github.com/SeleniumHQ/selenium/issues/12074

**Comment by diemol** [comment]
Unfortunately, we cannot commit to this due to the team's small size. 

We are trying to simplify and automate the release process, and we might revisit this after we are done with that.
