### ISSUE TITLE
[🐛 Bug]: Node not registering on Hub in the same machine for Client in their office N/W

### ISSUE THREAD

**Issue by adas05** [SeleniumHQ/selenium#14462]
### What happened?

Hi! We have a client setup where HUB and NODE are running in the same machine. For few users this set up is working fine, but for few others the NODE keeps sending the "sending registration event..." and the HUB do not registers.

We have taken these steps to identify the issue:

1. Checking if the following ports are opened or not for Ports: 4442, 4443, 4444, 5555
                        using this command **netstat -ano | find "PORT"**
For PORT 4442 we found that we get the status as **SYN_SENT**, so this made us check for all the above PORTS to be opened in these IP ranges for the clients.
2. The client connects to their office n/w and then they start the HUB and NODE. 
3. They have their firewall setup using Gamma and not Windows default firewall.
4. On checking with the infra team they have informed us that the ports are opened for all IPs generated for the clients.

Note: we have tested the same HUB and NODE config with different PORTs range from 7777, 7778, 7779 (HUB related) and 8888 for NODE - this also did not work (which is understandable)
We have asked the infra team to re-check the IP ranges in which the above PORTS are opened and waiting for their response.

Could anyone pls suggest if we are missing some other config related changes?

Thanks

Anirban

![image](https://github.com/user-attachments/assets/ea9f3a6f-234b-44d9-99af-81bbdae42d0c)

### How can we reproduce the issue?

```shell
Starting HUB:  java -jar selenium-server-4.9.0.jar hub

Starting NODE: java -Dwebdriver.chrome.driver=%DIR_HOME%\chromedriver.exe -Dwebdriver.edge.driver=%DIR_HOME%\msedgedriver.exe -Dwebdriver.edge.verboseLogging=true -jar selenium-server-4.9.0.jar node --detect-drivers true
```

### Relevant log output

```shell
Sending registration event...
```

### Operating System

Windows 10

### Selenium version

Java

### What are the browser(s) and version(s) where you see this issue?

Chrome 127

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 127.0.6533.88

### Are you using Selenium Grid?

Selenium 4.9.0

**Comment by sbabcoc** [comment]
Are the affected machines running with VPN connections? It may be insufficient to specify `localhost`; you may need to use a strategy like this to identify the proper internal address:

https://github.com/sbabcoc/Selenium-Foundation/blob/master/src%2Fmain%2Fjava%2Fcom%2Fnordstrom%2Fautomation%2Fselenium%2Futility%2FNetIdentity.java

To use this class:

```
new NetIdentity().getHostAddress();
```

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
