### ISSUE TITLE
IEDriver isDisplayed not catching Hidden attribute

### ISSUE THREAD

**Issue by kdillon** [SeleniumHQ/selenium#1447]
Hi Selenium contributors,

I recently discovered that isDisplayed returns TRUE in IE9, IE10 & IE11 for elements that have the hidden attribute.

So there are 4 ways to hide nodes that I know of. CSS styles... Opacity:0, Display:none, Visibility:hidden , and all of these seem to work. But if you use the hidden attribute ...

For example: 

\<select name="joe" id="dropdown" onchange="disappearances()" hidden=""\>
...
\</select\>

...this returns isDisplayed = true. However, it is not displayed and should return FALSE. It correctly returns false for Chrome and Firefox.

**Comment by kdillon** [comment]
Blarg. The HTML in my example above is getting hidden  :(  How does one escape HTML characters in git?

**Comment by jimevans** [comment]
I have a couple of quick comments. First, the `hidden` attribute is supposed to be [only supported in IE11](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden). As such, I might expect this to happen for IE versions less than 11. Second, if you're using IE11, and the document mode it selects is less than 11 (you'll need to check using the F12 Developer Tools to see this), then IE will use the DOM as if the version was _that_ version of the browser. I'm not sure there's much the driver can do, without misrepresenting the actual browser's behavior.

**Comment by kdillon** [comment]
Hi Jim,

You're right. I verified it does not actually disappear when the hidden attribute is set in both IE9 and 10, so it is correct that isDisplayed would return true for these cases.

The IE11 error I saw is likely unrelated.

Please feel free to close this and I apologize for taking up your time with this mistake. Thanks for the response!
