### ISSUE TITLE
[🐛 Bug]: Invalid version returned by selenium.__version__

### ISSUE THREAD

**Issue by Nyakutka** [SeleniumHQ/selenium#14475]
### What happened?

`selenium.__version__` returns "4.31.1" instead of current version 4.24.0

### How can we reproduce the issue?

```shell
Python:
print(selenium.__version__)
```

### Relevant log output

```shell
'4.31.1'
```

### Operating System

Windows 10

### Selenium version

4.24.0

### What are the browser(s) and version(s) where you see this issue?

-

### What are the browser driver(s) and version(s) where you see this issue?

-

**Comment by diemol** [comment]
There was a typo in a previous release. I have fixed it for the next release. Thank you for reporting this.
