### ISSUE TITLE
[🐛 Bug]:unable to connect to Chrome

### ISSUE THREAD

**Issue by sociallistening** [SeleniumHQ/selenium#14472]
### What happened?

i unable to connect to Chrome after update version.the code it used to work,but does'n.
![Screenshot 2024-09-04 225956](https://github.com/user-attachments/assets/e8d3b88f-112f-400a-92b2-4eb41cfc061f)

### How can we reproduce the issue?

```shell
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--remote-debugging-port=9222')
chrome_options.add_argument('--window-size=1920x1080')
chrome_options.add_argument('--disable-software-rasterizer')
chrome_options.add_argument('--lang=th')

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
```

### Relevant log output

```shell
win32/chromedriver.exe] found in cache
```

### Operating System

Microsoft Windows10

### Selenium version

python 3.10.9 ,selenium 4.31.1

### What are the browser(s) and version(s) where you see this issue?

chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver version: 128.0.6613.119

**Comment by diemol** [comment]
Use https://www.selenium.dev/documentation/selenium_manager/ instead of `ChromeDriverManager`

**Comment by sociallistening** [comment]
> Use https://www.selenium.dev/documentation/selenium_manager/ instead of `ChromeDriverManager`

i got 
---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
Cell In[20], line 50
     47 chrome_options.add_argument('--lang=th')
     49 # Use Selenium Manager to handle the driver
---> 50 driver = webdriver.Chrome(options=chrome_options)
     52 def login(email, password):
     53     logging.info("Attempting to log in...")

File ~\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py:45, in WebDriver.__init__(self, options, service, keep_alive)
     42 service = service if service else Service()
     43 options = options if options else Options()
---> 45 super().__init__(
     46     browser_name=DesiredCapabilities.CHROME["browserName"],
     47     vendor_prefix="goog",
     48     options=options,
     49     service=service,
     50     keep_alive=keep_alive,
     51 )

File ~\anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py:66, in ChromiumDriver.__init__(self, browser_name, vendor_prefix, options, service, keep_alive)
     57 executor = ChromiumRemoteConnection(
     58     remote_server_addr=self.service.service_url,
     59     browser_name=browser_name,
   (...)
     62     ignore_proxy=options._ignore_local_proxy,
     63 )
     65 try:
---> 66     super().__init__(command_executor=executor, options=options)
     67 except Exception:
     68     self.quit()

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:212, in WebDriver.__init__(self, command_executor, keep_alive, file_detector, options)
    210 self._authenticator_id = None
    211 self.start_client()
--> 212 self.start_session(capabilities)
    214 self._websocket_connection = None
    215 self._script = None

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:299, in WebDriver.start_session(self, capabilities)
    292 """Creates a new session with the desired capabilities.
    293 
    294 :Args:
    295  - capabilities - a capabilities dict to start the session with.
    296 """
    298 caps = _create_caps(capabilities)
--> 299 response = self.execute(Command.NEW_SESSION, caps)["value"]
    300 self.session_id = response.get("sessionId")
    301 self.caps = response.get("capabilities")

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:354, in WebDriver.execute(self, driver_command, params)
    352 response = self.command_executor.execute(driver_command, params)
    353 if response:
--> 354     self.error_handler.check_response(response)
    355     response["value"] = self._unwrap_value(response.get("value", None))
    356     return response

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
	GetHandleVerifier [0x00007FF6E0B9B5D2+29090]
	(No symbol) [0x00007FF6E0B0E689]
	(No symbol) [0x00007FF6E09CB1CA]
	(No symbol) [0x00007FF6E0A0CE6D]
	(No symbol) [0x00007FF6E0A078E9]
	(No symbol) [0x00007FF6E0A01E0A]
	(No symbol) [0x00007FF6E0A5236D]
	(No symbol) [0x00007FF6E0A51A20]
	(No symbol) [0x00007FF6E0A46493]
	(No symbol) [0x00007FF6E0A109B1]
	(No symbol) [0x00007FF6E0A11B11]
	GetHandleVerifier [0x00007FF6E0EB8C5D+3295277]
	GetHandleVerifier [0x00007FF6E0F04843+3605523]
	GetHandleVerifier [0x00007FF6E0EFA707+3564247]
	GetHandleVerifier [0x00007FF6E0C56EB6+797318]
	(No symbol) [0x00007FF6E0B1980F]
	(No symbol) [0x00007FF6E0B153F4]
	(No symbol) [0x00007FF6E0B15580]
	(No symbol) [0x00007FF6E0B04A1F]
	BaseThreadInitThunk [0x00007FF875F7257D+29]
	RtlUserThreadStart [0x00007FF877D2AF28+40]

**Comment by sociallistening** [comment]
> Use https://www.selenium.dev/documentation/selenium_manager/ instead of `ChromeDriverManager`

i got 
![Uploading Screenshot 2024-09-04 233854.png…]()

**Comment by sociallistening** [comment]
> Use https://www.selenium.dev/documentation/selenium_manager/ instead of `ChromeDriverManager`

i got 
---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
Cell In[20], line 50
     47 chrome_options.add_argument('--lang=th')
     49 # Use Selenium Manager to handle the driver
---> 50 driver = webdriver.Chrome(options=chrome_options)
     52 def login(email, password):
     53     logging.info("Attempting to log in...")

File ~\anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py:45, in WebDriver.__init__(self, options, service, keep_alive)
     42 service = service if service else Service()
     43 options = options if options else Options()
---> 45 super().__init__(
     46     browser_name=DesiredCapabilities.CHROME["browserName"],
     47     vendor_prefix="goog",
     48     options=options,
     49     service=service,
     50     keep_alive=keep_alive,
     51 )

File ~\anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py:66, in ChromiumDriver.__init__(self, browser_name, vendor_prefix, options, service, keep_alive)
     57 executor = ChromiumRemoteConnection(
     58     remote_server_addr=self.service.service_url,
     59     browser_name=browser_name,
   (...)
     62     ignore_proxy=options._ignore_local_proxy,
     63 )
     65 try:
---> 66     super().__init__(command_executor=executor, options=options)
     67 except Exception:
     68     self.quit()

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:212, in WebDriver.__init__(self, command_executor, keep_alive, file_detector, options)
    210 self._authenticator_id = None
    211 self.start_client()
--> 212 self.start_session(capabilities)
    214 self._websocket_connection = None
    215 self._script = None

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:299, in WebDriver.start_session(self, capabilities)
    292 """Creates a new session with the desired capabilities.
    293 
    294 :Args:
    295  - capabilities - a capabilities dict to start the session with.
    296 """
    298 caps = _create_caps(capabilities)
--> 299 response = self.execute(Command.NEW_SESSION, caps)["value"]
    300 self.session_id = response.get("sessionId")
    301 self.caps = response.get("capabilities")

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:354, in WebDriver.execute(self, driver_command, params)
    352 response = self.command_executor.execute(driver_command, params)
    353 if response:
--> 354     self.error_handler.check_response(response)
    355     response["value"] = self._unwrap_value(response.get("value", None))
    356     return response

File ~\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py:229, in ErrorHandler.check_response(self, response)
    227         alert_text = value["alert"].get("text")
    228     raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
--> 229 raise exception_class(message, screen, stacktrace)

SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
	GetHandleVerifier [0x00007FF6E0B9B5D2+29090]
	(No symbol) [0x00007FF6E0B0E689]
	(No symbol) [0x00007FF6E09CB1CA]
	(No symbol) [0x00007FF6E0A0CE6D]
	(No symbol) [0x00007FF6E0A078E9]
	(No symbol) [0x00007FF6E0A01E0A]
	(No symbol) [0x00007FF6E0A5236D]
	(No symbol) [0x00007FF6E0A51A20]
	(No symbol) [0x00007FF6E0A46493]
	(No symbol) [0x00007FF6E0A109B1]
	(No symbol) [0x00007FF6E0A11B11]
	GetHandleVerifier [0x00007FF6E0EB8C5D+3295277]
	GetHandleVerifier [0x00007FF6E0F04843+3605523]
	GetHandleVerifier [0x00007FF6E0EFA707+3564247]
	GetHandleVerifier [0x00007FF6E0C56EB6+797318]
	(No symbol) [0x00007FF6E0B1980F]
	(No symbol) [0x00007FF6E0B153F4]
	(No symbol) [0x00007FF6E0B15580]
	(No symbol) [0x00007FF6E0B04A1F]
	BaseThreadInitThunk [0x00007FF875F7257D+29]
	RtlUserThreadStart [0x00007FF877D2AF28+40]
	
![Uploading Screenshot 2024-09-04 233854.png…]()

**Comment by diemol** [comment]
We are closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/) that includes the page required to execute the scenario (a sample page or a public site).

If you have any questions or need help, join us in the [IRC/Slack channel](https://www.selenium.dev/support/), where the community can also assist you.

**Comment by OsicKwon** [comment]
Hello,

Same error has happened to me. Please see image and error message below. Thank you for your time!!

![image](https://github.com/user-attachments/assets/e095f337-e95a-4b3b-a4f1-ae5d5a63a45d)

DevTools listening on ws://127.0.0.1:53107/devtools/browser/6099cf25-d145-4d5a-9525-1770182adab3
Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "c:\Coding\Python\Project\EDI\test.py", line 3, in <module>
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created   
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00007FF6F4B79412+29090]
        (No symbol) [0x00007FF6F4AEE239]
        (No symbol) [0x00007FF6F49AB009]
        (No symbol) [0x00007FF6F49976D4]
        (No symbol) [0x00007FF6F49EC558]
        (No symbol) [0x00007FF6F49E72AC]
        (No symbol) [0x00007FF6F49E1E1A]
        (No symbol) [0x00007FF6F4A3233D]
        (No symbol) [0x00007FF6F4A319F0]
        (No symbol) [0x00007FF6F4A26493]
        (No symbol) [0x00007FF6F49F09D1]
        (No symbol) [0x00007FF6F49F1B31]
        GetHandleVerifier [0x00007FF6F4E9871D+3302573]
        GetHandleVerifier [0x00007FF6F4EE4243+3612627]
        GetHandleVerifier [0x00007FF6F4EDA417+3572135]
        GetHandleVerifier [0x00007FF6F4C35EB6+801862]
        (No symbol) [0x00007FF6F4AF945F]
        (No symbol) [0x00007FF6F4AF4FB4]
        (No symbol) [0x00007FF6F4AF5140]
        (No symbol) [0x00007FF6F4AE461F]
        BaseThreadInitThunk [0x00007FFFCEA17614+20]
        RtlUserThreadStart [0x00007FFFCED026A1+33]

---


- OS: Windows 10 Enterprise; 10.0.19044 Build 19044 
- Chrome Browser: Version 128.0.6613.85 (Official Build) (64-bit)
- Selenium: 4.13.1

**Comment by sociallistening** [comment]
https://googlechromelabs.github.io/chrome-for-testing/#dev
use stable version for chrome and chromedriver
chrome_options = Options()
chrome_options.binary_location = r"....../chrome.exe"

**Comment by OsicKwon** [comment]
Thank you so much for your solution!
However, unfortunately, it doesn't still work for me with same error message out.
So, I should try to use Firefox rather than Chrome. Thank you again!!
![image](https://github.com/user-attachments/assets/0b1bd7a7-0fa0-46b8-8754-f98c95cc10f3)

![image](https://github.com/user-attachments/assets/fd701350-fc66-4433-a4de-787fbed3386e)


```python
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
import time

options = Options()
options.binary_location = r"C:\\chrome-win64\\chrome.exe"
driver = webdriver.Chrome(options=options)
time.sleep(3)
driver.get("https://www.goggle.com")
```
