### ISSUE TITLE
[🐛 Bug]:org.openqa.selenium.NoSuchWindowException: Window is closed

### ISSUE THREAD

**Issue by shenkaibo** [SeleniumHQ/selenium#14498]
### What happened?

The step for Selenium is doubleClick to select information and auto close the current window handle 

### How can we reproduce the issue?

```shell
the step is doubleClick to select information and auto close the current window handle
```

### Relevant log output

```shell
I have set Protected mode = On for all security zones like this issue https://github.com/seleniumhq/selenium/issues/5061  bug no effect
```

### Operating System

windows2012 R2

### Selenium version

4.10.0

### What are the browser(s) and version(s) where you see this issue?

IE 11.0.9600.18921

### What are the browser driver(s) and version(s) where you see this issue?

IE dirver win32_4.14.0

### Are you using Selenium Grid?

no

**Comment by shbenzer** [comment]
We will need more information in order to replicate - please provide us with an executable use case in the language the error was found in.

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
