### ISSUE TITLE
I downloaded the source code,and running go.bat script,but compiling failed

### ISSUE THREAD

**Issue by hackereye** [SeleniumHQ/selenium#1449]
Building: //javascript/firefox-driver:command-processor-xpt as build\javascript\
firefox-driver\nsICommandProcessor.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsICommandProc
essor.xpt
Building: //javascript/firefox-driver:coordinates-xpt as build\javascript\firefo
x-driver\wdICoordinate.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdICoordinate.
xpt
Compiling: //javascript/firefox-driver:modifier-keys as build\javascript\firefox
-driver\modifier-keys.js
Building: //javascript/firefox-driver:modifier-keys-xpt as build\javascript\fire
fox-driver\wdIModifierKeys.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIModifierKey
s.xpt
Compiling: //javascript/firefox-driver:driver-component as build\javascript\fire
fox-driver\driver-component.js
Building: //javascript/firefox-driver:httpd-xpt as build\javascript\firefox-driv
er\nsIHttpServer.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsIHttpServer.
xpt
Building: //javascript/firefox-driver:mouse-xpt as build\javascript\firefox-driv
er\wdIMouse.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIMouse.xpt
Compiling: //javascript/firefox-driver:prompt-service as build\javascript\firefo
x-driver\prompt-service.js
Building: //javascript/firefox-driver:response-handler-xpt as build\javascript\f
irefox-driver\nsIResponseHandler.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/nsIResponseHan
dler.xpt
Building: //javascript/firefox-driver:status-xpt as build\javascript\firefox-dri
ver\wdIStatus.xpt
The system cannot find the specified path.
Falling back to javascript/firefox-driver/prebuilt/firefox-driver/wdIStatus.xpt
Compiling: //javascript/firefox-driver:synthetic-mouse as build\javascript\firef
ox-driver\synthetic-mouse.js
 my os is window7

**Comment by barancev** [comment]
This means that you have no Visual Studio compiler configured and the builder can't compile C/C++ code, so it just falls back to the precompiled binaries stored to the repository.
