### ISSUE TITLE
[🚀 Feature]: Drivers for ARM processors or offical work around

### ISSUE THREAD

**Issue by RobertEdwardes** [SeleniumHQ/selenium#14500]
### Feature and motivation

This error, I understand ARM and Raspberry Pi isn't a priority 

WebDriverException                        Traceback (most recent call last)
File ~/demo/notebookenv/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py:67, in DriverFinder._binary_paths(self)
     66 else:
---> 67     output = SeleniumManager().binary_paths(self._to_args())
     68     if Path(output["driver_path"]).is_file():

File ~/demo/notebookenv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py:47, in SeleniumManager.binary_paths(self, args)
     40 """Determines the locations of the requested assets.
     41 
     42 :Args:
     43  - args: the commands to send to the selenium manager binary.
     44 :Returns: dictionary of assets and their path
     45 """
---> 47 args = [str(self._get_binary())] + args
     48 if logger.getEffectiveLevel() == logging.DEBUG:

File ~/demo/notebookenv/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py:94, in SeleniumManager._get_binary()
     93 if location is None:
---> 94     raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
     96 path = Path(__file__).parent.joinpath(location)

WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64

### Usage example

Low energy agents. Same thing now but on raspberry pi

**Comment by diemol** [comment]
We don't offer support for ARM on Linux because, at least last time we checked, there are no official binaries from Chrome, Edge, and Firefox for that platform.

**Comment by RobertEdwardes** [comment]
Yea but even if I use older binaries locally the manager tries to download
a new one and throws an error that why I was wondering if there could be a
way to work around the manager

**Comment by diemol** [comment]
You can skip Selenium Manager by configuring the driver service or putting a driver binary on the PATH.

https://www.selenium.dev/documentation/selenium_manager/#usage
