### ISSUE TITLE
[🐛 Bug]: vertical size not matching

### ISSUE THREAD

**Issue by ludodul** [SeleniumHQ/selenium#14509]
### What happened?

Hello, 
I need to take some screenshots from a document, so I resize the screen size then take a screenshot.
The problem is that the vertical size is lower than the size I asked for.
If I ask for 900x300, I only have 884 x 153 screen size. 
I did not have this problem some weeks or months ago.

### How can we reproduce the issue?

```shell
driver.Manage().Window.Size = new System.Drawing.Size(900, 300);
 Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot();
```

### Relevant log output

```shell
no logs
```

### Operating System

Wibdows 10

### Selenium version

c# 4.24

### What are the browser(s) and version(s) where you see this issue?

chrome 128

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 128.0.6613.13700

**Comment by shbenzer** [comment]
I am unable to replicate.

this passes for me:

```
[Test]
public void TestWindowSizeAndScreenshot()
{
    // Navigate to a webpage
    driver.Navigate().GoToUrl("https://www.example.com");

    // Set the window size to 900x300
    driver.Manage().Window.Size = new System.Drawing.Size(900, 300);

    // Take a screenshot
    Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot();
    
    // Save the screenshot
    string screenshotPath = Path.Combine(Directory.GetCurrentDirectory(), "screenshot.png");
    ss.SaveAsFile(screenshotPath, ScreenshotImageFormat.Png);

    // Check if the screenshot file exists
    Assert.IsTrue(File.Exists(screenshotPath), "Screenshot was not saved correctly.");

    // check dimensions of the file
    using (var image = Image.FromFile(screenshotPath))
    {
        Assert.AreEqual(900, image.Width);
        Assert.AreEqual(300, image.Height);
    }
}
```
