### ISSUE TITLE
[🐛 Bug]:  Selenium Manager is encountering an issue with the setProxyAutoconfigUrl() method.

### ISSUE THREAD

**Issue by dineshkumar-kanniyammal** [SeleniumHQ/selenium#14503]
### What happened?

**An error occurs when trying to set a proxy auto-configuration URL using setProxyAutoconfigUrl() in a FirefoxOptions object. The geckodriver is not able to launch, and the following error is thrown:**

org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: geckodriver, error Command failed with code: 2, executed: [--browser, firefox, --browser-version, 129.0, --proxy, --language-binding, java, --output, json]
error: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.

### How can we reproduce the issue?

```shell
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setBrowserVersion("129.0");

Proxy proxy = new Proxy();
proxy.setProxyAutoconfigUrl("http://web-proxy/proxy.pac");
			
firefoxOptions.setProxy(proxy);

new FirefoxDriver(firefoxOptions);
```

### Relevant log output

```shell
org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: geckodriver, error Command failed with code: 2, executed: [--browser, firefox, --browser-version, 129.0, --proxy, --language-binding, java, --output, json]
error: a value is required for '--proxy <PROXY>' but none was supplied

For more information, try '--help'.
```

### Operating System

Macos

### Selenium version

selenium-server-4.23.0.jar

### What are the browser(s) and version(s) where you see this issue?

Firefox version 130.0

### What are the browser driver(s) and version(s) where you see this issue?

geckodriver 0.35.0

**Comment by pujagani** [comment]
Thank you for sharing the details. I will be able to reproduce the issue. I am trying to now figure out the best way to address this.
