### ISSUE TITLE
[🐛 Bug]: headless mode error of chrome 129

### ISSUE THREAD

**Issue by magdev2022** [SeleniumHQ/selenium#14514]
### What happened?

Today, I updated the Chrome browser to the latest version (129). 
After the update, running Chrome in headless mode produces an unusual result: a blank white window appears, matching the size of the browser.
![image](https://github.com/user-attachments/assets/421ce012-8771-40d0-ac61-29502ad385f4)

### How can we reproduce the issue?

```shell
//simple code
var driverService = ChromeDriverService.CreateDefaultService();
driverService.HideCommandPromptWindow = true;
var chromeoptions = new ChromeOptions();
chromeoptions.AddArgument("headless");
var botdriver= new ChromeDriver(driverService, chromeoptions);
botdriver.Url = "https://google.com";
```

### Relevant log output

```shell
I will send later.
```

### Operating System

Windows 11

### Selenium version

dotnet selenium 4.24.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 129

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 129.0.6668.58

### Are you using Selenium Grid?

No

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/79006406/chrome-browser-latest-version-129-in-headless-mode-produces-a-blank-white-wind/79006697#79006697

**Comment by mdmintz** [comment]
It was already answered 2 days ago:
https://stackoverflow.com/questions/78996364/chrome-129-headless-shows-blank-window/78999088#78999088

Temporary fix to move the window off-screen:
`--window-position=-2400,-2400`

```python
chrome_options.add_argument("--window-position=-2400,-2400")
```

**Comment by Rayrsn** [comment]
this was posted on the issue tracker for chromedriver [issue #367755364](https://issues.chromium.org/issues/367755364)
