### ISSUE TITLE
[🐛 Bug]: HTTP exception thrown

### ISSUE THREAD

**Issue by BrianHamil** [SeleniumHQ/selenium#14517]
### What happened?

This function often throws an exception. Looking at the code, I am confused as to the purpose of a second response when it's not returned and does not modify what is returned. 

private async Task<HttpResponseInfo> MakeHttpRequest(HttpRequestInfo requestInfo)

![image](https://github.com/user-attachments/assets/7bb4c92f-8a96-4af5-bb99-704f8158f1b0)

### How can we reproduce the issue?

```shell
Make any call that uses MakeHttpRequest(), the exception is not consistent but is rather frequent.
```

### Relevant log output

```shell
no log
```

### Operating System

Windows 10

### Selenium version

C#

### What are the browser(s) and version(s) where you see this issue?

no browser needed to get exception

### What are the browser driver(s) and version(s) where you see this issue?

most recent

### Are you using Selenium Grid?

no

**Comment by nvborisenko** [comment]
You said:
```
This function often throws an exception
```

What exception? Please come back with details when you are ready. We will be glad to investigate it.
