### ISSUE TITLE
When I compile Selenium on ubuntu 15.04, it gives me this output. I have ibus lib installed. I think that I use different version. I am right, how can I solve it?

### ISSUE THREAD

**Issue by hackereye** [SeleniumHQ/selenium#1451]
Compiling: //cpp:noblur64 as build/cpp/amd64/libnoblur64.so
Compiling: //cpp:imehandler64 as build/cpp/amd64/libimehandler64.so
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual std::string IBusHandler::GetActiveEngine() const’:
cpp/imehandler/linux/src/ibushandler.cpp:70:37: error: ‘IBusEngineDesc’ has no member named ‘name’
     engine_name = std::string(desc->name);
                                     ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘IBusInputContext* IBusHandler::GetCurrentInputContext() const’:
cpp/imehandler/linux/src/ibushandler.cpp:88:3: error: ‘IBusConnection’ was not declared in this scope
   IBusConnection* conn = ibus_bus_get_connection(bus_);
   ^
cpp/imehandler/linux/src/ibushandler.cpp:88:19: error: ‘conn’ was not declared in this scope
   IBusConnection* conn = ibus_bus_get_connection(bus_);
                   ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual bool IBusHandler::IsActivated() const’:
cpp/imehandler/linux/src/ibushandler.cpp:110:47: error: ‘ibus_input_context_is_enabled’ was not declared in this scope
   return ibus_input_context_is_enabled(context);
                                               ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual void IBusHandler::Deactivate()’:
cpp/imehandler/linux/src/ibushandler.cpp:127:37: error: ‘ibus_input_context_disable’ was not declared in this scope
   ibus_input_context_disable(context);
                                     ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual std::vector<std::basic_string<char> > IBusHandler::GetAvailableEngines() const’:
cpp/imehandler/linux/src/ibushandler.cpp:149:36: error: ‘IBusEngineDesc’ has no member named ‘name’
     loaded_engines.push_back(desc->name);
                                    ^
cpp/imehandler/linux/src/ibushandler.cpp: In member function ‘virtual std::vector<std::basic_string<char> > IBusHandler::GetInstalledEngines() const’:
cpp/imehandler/linux/src/ibushandler.cpp:167:20: warning: ‘GList* ibus_bus_list_active_engines(IBusBus*)’ is deprecated (declared at /usr/include/ibus-1.0/ibusbus.h:693) [-Wdeprecated-declarations]
   GList* engines = ibus_bus_list_active_engines(bus_);
                    ^
cpp/imehandler/linux/src/ibushandler.cpp:167:53: warning: ‘GList* ibus_bus_list_active_engines(IBusBus*)’ is deprecated (declared at /usr/include/ibus-1.0/ibusbus.h:693) [-Wdeprecated-declarations]

**Comment by lukeis** [comment]
this should not fail your build... it should have messaging below this saying it's falling back to the prebuilt version.

This code is now very much dead, it doesn't work on the latest versions of firefox (we exclude 'native events' in them now). And our webdriver.xpi will cease to work in near future versions of firefox, all effort should be spent on enhancing Marionette / Wires:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

There's no action for us to take here. If you'd like more real time support building selenium, I suggest joining the #selenium channel in irc.freenode.net
