### ISSUE TITLE
WebDriver holds many TCP ports

### ISSUE THREAD

**Issue by Marrowbones** [SeleniumHQ/selenium#1452]
Hello,

Apologies if this isn't the right way to ask this, but I can't find much more information elsewhere.

We have written a Java WebDriver application that we run many concurrent instances of, each of which runs many multi-step Selenium tests.  As the number of concurrent tests has inreased, we've occassionally been hitting "java.net.SocketException: No buffer space" exceptions.  We've applied relevant OS level patches for similar problems, so it's not (just) that.

On further investigation, it seems that each WebDriver test holds dozens of ports open... and even after the driver has shut down cleanly, these are held in TIME_WAIT for some time.  

Is this expected behaviour?  It's causing us quite a few resource problems, with thousands of sockets stuck in TIME_WAIT.

For info, there seems to be many java > browser/driver and browser/driver connections, as well as (the more expected) browser > webpage sockets.  Chrome seems to have less of the driver > Java connections than Firefox, but still has lots of the others.  But generally it seems that every WebDriver interaction results in at least 3 sockets being hogged (Java > browser, browser > Java, browser <> webpage), sometimes more (example below)

Is this all expected?  Might it be amended in future?

Cheers,
Marc
# 

 ...
 TCP    127.0.0.1:7055         COMPUTERNAME:64378        TIME_WAIT
 TCP    127.0.0.1:7055         COMPUTERNAME:64380        TIME_WAIT
 TCP    127.0.0.1:7055         COMPUTERNAME:64385        TIME_WAIT
 TCP    127.0.0.1:7055         COMPUTERNAME:64409        ESTABLISHED
[firefox.exe]

  ...
  TCP    127.0.0.1:64384        COMPUTERNAME:7055         TIME_WAIT
  TCP    127.0.0.1:64386        COMPUTERNAME:7055         TIME_WAIT
  TCP    127.0.0.1:64387        COMPUTERNAME:7055         TIME_WAIT
  TCP    127.0.0.1:64409        COMPUTERNAME:7055         ESTABLISHED
 [java.exe]

 ...
  TCP    10.111.34.81:56076     webserver-02:8080       TIME_WAIT
  TCP    10.111.34.81:56079     webserver-02:8080       ESTABLISHED
 [firefox.exe]
  TCP    10.111.34.81:56080     webserver-02:8080       ESTABLISHED
 [firefox.exe]
  TCP    10.111.34.81:56081     webserver-02:8080       ESTABLISHED
 [firefox.exe]
#

**Comment by barancev** [comment]
This issue has been resolved in Java binding by migration to OkHttp library (if target driver supports keep-alive).

For other bindings see #5758
