### ISSUE TITLE
[🐛 Bug]: inconsistent tagging for the release versions 

### ISSUE THREAD

**Issue by ajayk** [SeleniumHQ/selenium#14522]
### What happened?

https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.25.0

The above tag has moving commits 

### How can we reproduce the issue?

```shell
N/A
```

### Relevant log output

```shell
related to release process
```

### Operating System

N/A

### Selenium version

N/A

### What are the browser(s) and version(s) where you see this issue?

N?A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by ajayk** [comment]
@diemol : ^^

**Comment by diemol** [comment]
Release is not complete, 4.25.0 has not been released.
