### ISSUE TITLE
[🐛 Bug]: On linux OS, while using chrome in headless mode, Css properties of screen are changing (screenshot of popup window is getting truncated)

### ISSUE THREAD

**Issue by chaitrasalian9** [SeleniumHQ/selenium#14531]
### What happened?

While capturing screenshots using a headless **Chrome browser version 128** on a **Linux OS**, I've observed that popup messages within a frame are truncated. This issue is evident in the screenshots, but on Windows OS and/or chrome normal(non-headless) on Linux OS, the display appears normal. I’m working with **Selenium version 4.19.1** and **Java 8**. Notably, the popup maintains a fixed width in the application. Attempts to modify the popup's DOM properties haven't affected its width. Additionally, I've noticed that the **CSS properties behave differently when running Selenium in chromedriver in headless mode.**
Attaching screenshots:
Linux with headless mode :
![image](https://github.com/user-attachments/assets/6f062cb3-6db0-461d-a564-7e0c708fcd9f)

Linux with non-headless mode :
![image](https://github.com/user-attachments/assets/8d716b8e-b068-41dd-a8e5-c9edeaf1ba61)

Windows OS with headless mode :
![image](https://github.com/user-attachments/assets/10928906-7cb2-4307-ae70-dc9c97ad086d)

### How can we reproduce the issue?

```shell
By Executing any application on Linux OS using Chrome version 128 in both headless and non-headless modes with Selenium 4 and Java 8.
```

### Relevant log output

```shell
no logs
```

### Operating System

Linux

### Selenium version

Java 8 , Selenium 4.19.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 128

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 128

### Are you using Selenium Grid?

No

**Comment by diemol** [comment]
Check https://www.selenium.dev/blog/2023/headless-is-going-away/, and if you continue to have an issue, please report it to the Chrome folks.
