### ISSUE TITLE
[🐛 Bug]: Unable to find match for CDP version 129 - SELENIUM IS 4.25.0

### ISSUE THREAD

**Issue by Tennessene** [SeleniumHQ/selenium#14538]
### What happened?

When I run my program with Selenium 4.25.0 as the dependency and chromeDriver/Chrome 129.0.6668.58 (seems to be any 128 or 129 version), I get the message saying it can't find a match for CDP version 129 when I'm using _Selenium 4.25.0_

### How can we reproduce the issue?

```shell
The repo is at https://github.com/Tennessene/SampleSeleniumProject
Run the "Test Run" workflow
The log should print the error
```

### Relevant log output

```shell
Sep 25, 2024 5:43:28 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 129, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 129
```

### Operating System

macOS Sequoia / Windows 11 / Ubuntu 22.04

### Selenium version

Java 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 129.0.6668.58

### What are the browser driver(s) and version(s) where you see this issue?

chromeDriver 129.0.6668.58

### Are you using Selenium Grid?

No

**Comment by joerg1985** [comment]
@Tennessene the linked repo is not visible to me. Are you using a fat jar for your project? This might break the ServiceLoader.

**Comment by Tennessene** [comment]
I forgot to make it visible. Yes, I’m using the fat jar because I don’t
know how to run it otherwise.

**Comment by Tennessene** [comment]
@joerg1985 I've edited my post to point to a [simpler project](https://github.com/Tennessene/SampleSeleniumProject) created just for this issue. Please use it instead

**Comment by joerg1985** [comment]
The fat jar does break the ServiceLoader, you could exclude the v127 & v128 dependency to fix this.

When a fat jar is build the files inside the META-INF folder are not merged correctly, so only one of the implementations is loaded, see #13791.

**Comment by Tennessene** [comment]
Okay, so it's just a problem on my end, not a bug. Thank you
