### ISSUE TITLE
Console logs returned as zero using .NET Selenium even though there are errors

### ISSUE THREAD

**Issue by sponnusamyneogov** [SeleniumHQ/selenium#14537]
### What happened?
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);
var Driver = new ChromeDriver(options);
 Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";
 Driver.FindElement(By.Id("consoleLog")).Click();
 Driver.FindElement(By.Id("consoleError")).Click();

Console logs returned as zero using .NET Selenium even though there are errors

Issue:
When trying to capture browser console logs using the following code in .NET Selenium:

csharp
Copy code
var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
the returned log shows zero entries, even though errors are clearly present in the browser's console.

### How can we reproduce the issue?

```shell
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);
var Driver = new ChromeDriver(options);
 Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";
 Driver.FindElement(By.Id("consoleLog")).Click();
 Driver.FindElement(By.Id("consoleError")).Click();

How to capture console logs using selenium and c#
```

### Relevant log output

```shell
The following code:

csharp

jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);

returns no errors, even though there are errors present in the browser console.
```

### Operating System

Windows 10

### Selenium version

Selenium Version 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

129.0.6668.7

### Are you using Selenium Grid?

No

**Comment by nvborisenko** [comment]
I should advertise BiDi here:

```csharp
var context = await driver.AsBiDiContextAsync();

await context.Log.OnEntryAddedAsync(Console.WriteLine);

driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

driver.FindElement(By.Id("consoleLog")).Click();
driver.FindElement(By.Id("consoleError")).Click();
```

And in output I see:
```
Console { BiDi = OpenQA.Selenium.BiDi.BiDi, Level = Info, Source = Source { Realm = OpenQA.Selenium.BiDi.Modules.Script.Realm, Context = OpenQA.Selenium.BiDi.Modules.BrowsingContext.BrowsingContext }, Text = Hello, world!, Timestamp = 9/25/2024 8:09:27 PM +00:00, StackTrace = StackTrace { CallFrames = System.Collections.Generic.List`1[OpenQA.Selenium.BiDi.Modules.Script.StackFrame] }, Method = log, Args = System.Collections.Generic.List`1[OpenQA.Selenium.BiDi.Modules.Script.RemoteValue] }
Console { BiDi = OpenQA.Selenium.BiDi.BiDi, Level = Error, Source = Source { Realm = OpenQA.Selenium.BiDi.Modules.Script.Realm, Context = OpenQA.Selenium.BiDi.Modules.BrowsingContext.BrowsingContext }, Text = I am console error, Timestamp = 9/25/2024 8:09:27 PM +00:00, StackTrace = StackTrace { CallFrames = System.Collections.Generic.List`1[OpenQA.Selenium.BiDi.Modules.Script.StackFrame] }, Method = error, Args = System.Collections.Generic.List`1[OpenQA.Selenium.BiDi.Modules.Script.RemoteValue] }
```

**Comment by sponnusamyneogov** [comment]
I tried this and received the below error 

System.ArgumentOutOfRangeException : The byte array must have a length of at least '24740' bytes.  
Parameter name: internalBuffer

  Stack Trace: 
 System.ArgumentOutOfRangeException : The byte array must have a length of at least '24740' bytes.  
Parameter name: internalBuffer

  Stack Trace: 
WebSocketBuffer.Validate(Int32 count, Int32 receiveBufferSize, Int32 sendBufferSize, Boolean isServerBuffer)
ClientWebSocketOptions.SetBuffer(Int32 receiveBufferSize, Int32 sendBufferSize, ArraySegment`1 buffer)
<ConnectAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<ConnectAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<ConnectAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<AsBiDiAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
<AsBiDiContextAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter`1.GetResult()
<ConsoleLogs>d__0.MoveNext() line 59
--- End of stack trace from previous location where exception was thrown ---
ExceptionDispatchInfo.Throw()
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter`1.GetResult()
GenericAdapter`1.GetResult()
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

**Comment by nvborisenko** [comment]
Thanks for highlighting this issue, already fixed.

BTW your code snippet works good for me:
![image](https://github.com/user-attachments/assets/c0b25021-d6bb-4bd5-98d1-84d4dafefc14)

**Comment by sponnusamyneogov** [comment]
Thank you so much! Could you let me know where I can find the new jar file with your fixes?

**Comment by nvborisenko** [comment]
Fix for BiDi implementation will be included in upcoming nightly build: https://github.com/SeleniumHQ/selenium/pkgs/nuget/Selenium.WebDriver

But your code works good for me, the original issue cannot be reproduced

```csharp
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, LogLevel.All);

using var Driver = new ChromeDriver(options);

Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

Driver.FindElement(By.Id("consoleLog")).Click();
Driver.FindElement(By.Id("consoleError")).Click();

var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
```

I am using `ChromeDriver 129.0.6668.70`.

**Comment by sponnusamyneogov** [comment]
Works with latest version.

Thanks !

 Output: 
[2024-09-26T15:53:38Z] [Severe] https://platform.twitter.com/js/button.b059c0eb61ea902a882e5c5b3c66a17a.js 0:0 Uncaught ReferenceError: __twttrll is not defined
TearDown : NUnit.Framework.AssertionException : [2024-09-26T15:53:38Z] [Severe] https://platform.twitter.com/js/button.b059c0eb61ea902a882e5c5b3c66a17a.js 0:0 Uncaught ReferenceError: __twttrll is not defined

  Stack Trace: 
CommandFactory.LogFailure(String message) line 11272
ConsoleErrorLogger.LogJavaScriptErrors() line 127
CheckForJavascriptError.LogJavascriptErrors() line 40

**Comment by sponnusamyneogov** [comment]
This code is not functioning correctly when using RemoteWebDriver with Selenium Grid.

[Test]
public void ConsoleLogsGridRun()
{
    var options = new ChromeOptions();
    options.SetLoggingPreference(LogType.Browser, OpenQA.Selenium.LogLevel.All);
    var Driver = new RemoteWebDriver(
                    new Uri("http://10.0.0.37:8888/"),
                    new RemoteSessionSettings(options), TimeSpan.FromSeconds(100));
    Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

    Driver.FindElement(By.Id("consoleLog")).Click();
    Driver.FindElement(By.Id("consoleError")).Click();

    var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
}

These are the capabilities 
![image](https://github.com/user-attachments/assets/f0cb0750-c2b9-40fc-ab9d-40c7c4954709)

Please advise
