### ISSUE TITLE
[🐛 Bug]: Console logs returned as zero using  RemoteDriver (SeleniumGrid) .NET Selenium 

### ISSUE THREAD

**Issue by sponnusamyneogov** [SeleniumHQ/selenium#14545]
### What happened?

This code is not functioning correctly when using RemoteWebDriver with Selenium Grid.

[Test]
public void ConsoleLogsGridRun()
{
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, OpenQA.Selenium.LogLevel.All);
var Driver = new RemoteWebDriver(
new Uri("http://10.0.0.37:8888/"),
new RemoteSessionSettings(options), TimeSpan.FromSeconds(100));
Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

Driver.FindElement(By.Id("consoleLog")).Click();
Driver.FindElement(By.Id("consoleError")).Click();

var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
}

Please advise

### How can we reproduce the issue?

```shell
[Test]
public void ConsoleLogsGridRun()
{
var options = new ChromeOptions();
options.SetLoggingPreference(LogType.Browser, OpenQA.Selenium.LogLevel.All);
var Driver = new RemoteWebDriver(
new Uri("http://10.0.0.37:8888/"),
new RemoteSessionSettings(options), TimeSpan.FromSeconds(100));
Driver.Url = "https://www.selenium.dev/selenium/web/bidi/logEntryAdded.html";

Driver.FindElement(By.Id("consoleLog")).Click();
Driver.FindElement(By.Id("consoleError")).Click();

var jsErrors = Driver.Manage().Logs.GetLog(LogType.Browser);
}
```

### Relevant log output

```shell
jsErrors returned as null
```

### Operating System

Windows 10

### Selenium version

Selenium Version 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

129.0.6668.71

### Are you using Selenium Grid?

Selenium Grid 4.25.0

**Comment by nvborisenko** [comment]
Confirmed, `Driver.Manage().Logs.GetLog(LogType.Browser);` even doesn't make http call to a remote.

**Comment by nvborisenko** [comment]
![image](https://github.com/user-attachments/assets/3db4f63a-dc8d-40dd-88c9-9cc0e6b71391)

@diemol @pujagani do you know whether it should be supported by remote?

**Comment by nvborisenko** [comment]
I found this one: https://github.com/w3c/webdriver/issues/406 where it is recommended to use BiDi implementation.

Now the correct question is: should we be silent here? And don't throw exception? In my opinion we should always throw if something is not supported.

@sponnusamyneogov your way is only trying out BiDi (already available as nightly build or wait next release).

**Comment by pujagani** [comment]
Java supports in remote so probably it should be supported too. One use case that I can think of is, users also use the Appium server with the Selenium client libraries and they will not be able to use BiDi in this case.

**Comment by nvborisenko** [comment]
Then it should be implemented for RemoteWebDriver too, thanks for the info.
