### ISSUE TITLE
[🚀 Feature]: Queue size 

### ISSUE THREAD

**Issue by lopezSebas** [SeleniumHQ/selenium#14548]
### Feature and motivation

Currently I monitoring nodes and slots in prometheus and grafana, but I need see total Queue size: 0, I need value be in json :4444/status to want catch and see on grafana.

### Usage example

![image](https://github.com/user-attachments/assets/5f65140b-8cec-443f-b29a-7d119236a114)
![image](https://github.com/user-attachments/assets/93185355-7e8e-44e6-a918-bf2409acea49)

**Comment by VietND96** [comment]
Why don't you extract more metrics via GraphQL endpoint?

![image](https://github.com/user-attachments/assets/2bfbe640-1b00-40da-aedd-d1eab0e59a5a)

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
