### ISSUE TITLE
In Linux, org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host localhost.localdomain on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by xupx12** [SeleniumHQ/selenium#1454]
selenium-firefox-driver-2.48.2
Firefox: 43. (I also try version  38.5.0, has the same issue)
OS: Linux  Red hat

       public WebDriver getLinuxDriver() throws UnknownHostException {	
		WebDriver driver = null;        ///-----from here-------
        String seleniumGridHubURL = "http://localhost:4444/wd/hub";
	DesiredCapabilities cap=DesiredCapabilities.firefox();  		
        System.out.println("/usr/bin/firefox...");
        cap.setCapability(CapabilityType.PLATFORM, "LINUX");
        System.out.println("testing 1 ...");
        FirefoxBinary ffb = new FirefoxBinary(new File("/usr/bin/firefox"));
        cap.setCapability(FirefoxDriver.BINARY, ffb);  
        System.out.println("testing 2 ...");
        driver = new FirefoxDriver(cap);     //// Always fail at here!!! why
        System.out.println("FirefoxDriver...");
        driver.get("http://www.baidu.com/"); 
		
        return driver;
	}

-------------
Output log:
/usr/bin/firefox...
testing 1 ...
testing 2 ...

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host localhost.localdomain on port 7055 after 45000 ms. Firefox console output:
Error: no display specified

How to fix this? It's OK when running on Windows 7 OS.

**Comment by barancev** [comment]
The root cause is "Error: no display specified"

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
