### ISSUE TITLE
[🐛 Bug]: From Selenium Grid 4.8.0 onwards, certain clicks are not registered

### ISSUE THREAD

**Issue by jgfmachado** [SeleniumHQ/selenium#14554]
### What happened?

Using any Selenium Grid past version 4.8.0, very occasionally but very consistently in the sense that the bug happens always at the same point in the test script, sometimes the click method isn't registered/doesn't happen.

I've turned on the logs on the Selenium Grid console for both version 4.8.0 (which is okay) and for 4.8.1 (which is not okay), then break pointed the script right before the problematic elements that were to be clicked, and recorded the logs right after the click method attempt.

I've tested multiple Grid Versions and multiple Chrome browser versions. I just didn't test multiple Browsers because that is not relevant for my case.
The issue also occurs on our Linux server machine, if we upgrade past version 4.8.0.

### How can we reproduce the issue?

```shell
Unfortunately I can't share the app that I'm testing for you guys to reproduce the issue, and I wasn't able to reproduce it elsewhere.
```

### Relevant log output

```shell
Logs for grid version 4.8.0
https://pastebin.com/3VG53tnT

Logs for grid version 4.8.1
https://pastebin.com/MwCBgyQW
```

### Operating System

Windows 11

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 108.0.5359.0

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 108.0.5359.0

### Are you using Selenium Grid?

4.8.1

**Comment by diemol** [comment]
I understand this is an issue for you. However, please consider our position. What can we do with the information you give us and two sets of log, and no context? It is really hard to give advice and even less triage this as a bug.

What would you do if you got a similar report? How would you triage it without a way to reproduce it?

**Comment by jgfmachado** [comment]
Hi @diemol. Don't worry, I understand your position. Was just hopeful that there was something different in those logs that could be helpful to you.
I'll keep digging into it more and see what else I can find. I'll also try to reproduce the issue using a free testing website or something similar.
In the meantime if you want to close the ticket or keep it open for a while, it's up to you.

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
