### ISSUE TITLE
[🐛 Bug]: Headless Chrome leaves a blank window open

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#14550]
### What happened?

When I open headless Chrome in Windows 11 with Python, it leaves blank window visible in desktop. Blank here means window without buttons or frames, example like this one: 
![image](https://github.com/user-attachments/assets/fcd3c7c2-2d1d-4085-b44a-f67d2c626eea)
The window remains blank for the duration of the execution, but it does not affect test execution. 

### How can we reproduce the issue?

```shell
import time

from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument("--headless")
print("Starting Chrome")
driver = webdriver.Chrome(options=options)
print("Sleep")
time.sleep(10)
print("Get URL")
driver.get("https://github.com/SeleniumHQ/selenium/issues")
driver.quit()
```

### Relevant log output

```shell
Starting Chrome

DevTools listening on ws://127.0.0.1:61296/devtools/browser/fe646dbc-1d4b-4526-a25e-b968904f7921
Sleep
Get URL
[17012:16848:1002/105511.364:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -3
```

### Operating System

Windows 11

### Selenium version

4.24.0 and 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 129.0.6668.71

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 129.0.6668.70 

### Are you using Selenium Grid?

Not using

**Comment by dtopuzov** [comment]
Duplicate of https://github.com/SeleniumHQ/selenium/issues/14514, https://github.com/SeleniumHQ/selenium/issues/14438 and https://github.com/SeleniumHQ/selenium/issues/14544

**Comment by aaltat** [comment]
Yes, looks like a duplicate. Closing.
