### ISSUE TITLE
[WebDriver - Java] selenium-java-2.48.2.jar can't support forech

### ISSUE THREAD

**Issue by bluejiaxie** [SeleniumHQ/selenium#1455]
After update the jar file from selenium-java-2.47.1.jar to 2.48.2, can't run my code below:

#####
...
static final String[] APPS = new String[] {"A", "B", "C"...};
...
for (String app : APPS) {...}
...
#####

the program stop after run the first app "A".

**Comment by barancev** [comment]
Selenium can't affect how Java works

**Comment by bluejiaxie** [comment]
but if use selenium-java-2.47.1.jar, the for{} works. After change to 2.48.2, it does not work.

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
