### ISSUE TITLE
[🐛 Bug]: Java Selenium - I cannot disable "Save as" pop up download in incognito mode - Selenium 4.25.0

### ISSUE THREAD

**Issue by SeleniumNinja** [SeleniumHQ/selenium#14568]
### What happened?

The following code still shows "Save as" pop up in incognito mode. 

```
HashMap<String, Object> chromePrefs = new HashMap<>();
chromePrefs.put("download.default_directory", downloadDir); 
chromePrefs.put("profile.default_content_settings.popups", 0);
chromePrefs.put("download.prompt_for_download", false);
chromePrefs.put("profile.default_content_setting_values.notifications", 2);
chromePrefs.put("profile.content_settings.exceptions.automatic_downloads.*.setting", 2);
chromePrefs.put("safebrowsing.disable_download_protection", true);
chromePrefs.put("profile.managed_default_content_settings.popups", 0);
chromePrefs.put("profile.default_content_setting_values.automatic_downloads", 1);

ChromeOptions options = New ChromeOptions();
options.addArguments("disable-features=DownloadBubble,DownloadBubbleV2");
options.addArguments("disable-features=DownloadUI");
options.addArguments("--safebrowsing-disable-download-protection");

options.setExperimentalOption("prefs" chromePrefs);

options.addArguments("--start-maximized");
options.addArguments("--disable-popup-blocking");
options.addArguments("--incognito");
options.addArguments("--disable-search-engine-choice-screen");
```

### How can we reproduce the issue?

```shell
I am using Selenium 4.25.0 and Chrome 129.
```

### Relevant log output

```shell
Is there any Selenium or Chrome official documentation how to do this properly ? Because everyone in the internet is doing different things, none of them work.
```

### Operating System

windows 10

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 129

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver 129

**Comment by Vishwas-web** [comment]
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;

public class DisableSaveAsPopup {

    public static void main(String[] args) {
        // Set the path to your ChromeDriver
        System.setProperty("webdriver.chrome.driver", "path/to/chromedriver");

        // Create a HashMap for Chrome preferences
        HashMap<String, Object> chromePrefs = new HashMap<>();
        // Set download preferences
        chromePrefs.put("download.default_directory", "path/to/download/directory");
        chromePrefs.put("profile.default_content_settings.popups", 0);
        chromePrefs.put("download.prompt_for_download", false);
        chromePrefs.put("safebrowsing.enabled", "true");

        // Set ChromeOptions
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--incognito"); // Open in incognito mode
        options.addArguments("--disable-popup-blocking"); // Disable pop-ups
        options.setExperimentalOption("prefs", chromePrefs); // Set preferences

        // Initialize ChromeDriver
        ChromeDriver driver = new ChromeDriver(options);
        
        // Your test code to trigger the download goes here
        
        // Quit the driver
        driver.quit();
    }
}
