### ISSUE TITLE
Playback result didn't match with each other using Selenium IDE and Selenium engine(java)

### ISSUE THREAD

**Issue by waynewang1989** [SeleniumHQ/selenium#1456]
1) Script created by using selenium IDE failed to playback with selenium engine.
2) Script with urls that will connect timeout(like google.com in China mainland) will playback successfully with selenium engine.

**Comment by samitbadle** [comment]
Have you tried increasing the timeout in Selenium IDE?

- Samit

**Comment by waynewang1989** [comment]
Hi Samit. We haven't use timeout in the script. We used "clickAndWait" which I don't think will cause the problem

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
