### ISSUE TITLE
[🐛 Bug]: navigating to different url

### ISSUE THREAD

**Issue by ranjiths234** [SeleniumHQ/selenium#14560]
### What happened?

my selenium web driver is always navigating to git hub url even i give different url

### How can we reproduce the issue?

```shell
package com.SeleniumPractice;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class highlight {
    public static void main (String[] args) {
    	
    	WebDriverManager.chromedriver().setup();
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://www.facebook.com/");
        
        JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
       WebElement element = (WebElement) jsExecutor.executeScript("document.getElementById('email');");
        element.sendKeys("Ranjith");
        
}
}
```

### Relevant log output

```shell
my selenium web driver is always navigating to git hub url even i give different url
```

### Operating System

Windows 11

### Selenium version

java 2.24.0

### What are the browser(s) and version(s) where you see this issue?

chrome 115

### What are the browser driver(s) and version(s) where you see this issue?

chrome driver 4.0

### Are you using Selenium Grid?

4.0

**Comment by diemol** [comment]
Please upgrade to the latest Selenium version and remove `WebDriverManager` because Selenium is now taking care of this.

If the issue is still present, create a new issue, and please provide a way to reproduce it.
