### ISSUE TITLE
[🐛 Bug]: Unable to register selenium node to remote selenium hub 4 

### ISSUE THREAD

**Issue by capnand** [SeleniumHQ/selenium#14573]
### What happened?

I'm using selenium grid 4.22.0
I'm running selenium hub in a k8 cluster and all required ports like 4444, 4442, 4443 are correctly exposed and working.
So when Im trying to register my local windows as a node to remote selenium hub, Im a having issues
I tried in two ways
1. java -jar selenium-server-4.22.0.jar node --publish-events tcp://<hubip>:4442 --subscribe-events tcp://<hubip>:4443 
it is sending multiple registration requests to hub
![image](https://github.com/user-attachments/assets/5e7d16c9-466f-468d-a39f-43f86f908dbe)

2. java -jar selenium-server-4.22.0.jar node --publish-events tcp://<hubip>:4442 --subscribe-events tcp://<hubip>:4443  --host <public ip of node>
Im getting Caused by: java.net.BindException: Cannot assign requested address: bind
![image](https://github.com/user-attachments/assets/2352ad0c-1161-44cb-afe7-3e9bf99fb444)

### How can we reproduce the issue?

```shell
note use selenium grid 4
1.run selenium hub in k8 cluster or run selenium hub in different machine
2. try connecting selenium node to remote selenium hub
```

### Relevant log output

```shell
1. java -jar selenium-server-4.22.0.jar node --publish-events tcp://<hubip>:4442 --subscribe-events tcp://<hubip>:4443 
it is sending multiple registration requests to hub
![image](https://github.com/user-attachments/assets/5e7d16c9-466f-468d-a39f-43f86f908dbe)

2. java -jar selenium-server-4.22.0.jar node --publish-events tcp://<hubip>:4442 --subscribe-events tcp://<hubip>:4443  --host <public ip of node>
Im getting Caused by: java.net.BindException: Cannot assign requested address: bind
![image](https://github.com/user-attachments/assets/2352ad0c-1161-44cb-afe7-3e9bf99fb444)
```

### Operating System

windows 10

### Selenium version

4.22.0

### What are the browser(s) and version(s) where you see this issue?

nothing

### What are the browser driver(s) and version(s) where you see this issue?

nothing

### Are you using Selenium Grid?

4.22.0

**Comment by pujagani** [comment]
Thank you for sharing the details. 

1. If you are starting multiple nodes, ensure each uses a different port. The default node uses port 5555. So if you have a node running on it and you try to run a different node then you will get the exception you shared. Use the option: --port to pass in a port exclusively.  Example: java -jar selenium-server-4.25.0.jar node --port 5556
2. Pass in the public URI of the Hub using the option --hub. Refer https://github.com/SeleniumHQ/selenium/blob/40bfc5e2bd473737d89aa1d47f64d3d67d23dd14/java/src/org/openqa/selenium/grid/node/config/NodeFlags.java#L132.

**Comment by capnand** [comment]
Hi Puja
I'm not running multiple nodes. I'm trying to connect single node with
default port and also Im passing public url in --hub
I'm able to connect to hub within its connect but when Im trying to connect
I'm facing issue

**Comment by pujagani** [comment]
I am not sorry I did not understand what you meant. Can you please elaborate? You are able to connect to the Hub but the registration is not happening. Are you passing the correct parameters for the event bus?
The link I shared points to this comment:
```
"The address of the Hub in a Hub-and-Node configuration. This can "
              + "be a plain hostname or IP address (`hostname`), in which case the Hub will be "
              + "assumed to be `http://hostname:4444`, the `--grid-url` will be the same, "
              + "`--publish-events` will be `tcp://hostname:4442` and `--subscribe-events` "
              + "will be `tcp://hostname:4443`. If `hostname` contains a port number, that "
              + "will be used for `--grid-url` but the URIs for the event bus will remain "
              + "the same. Any of these default values may be overridden but setting the "
              + "correct flags. If the hostname has  a protocol (such as `https`) that will "
              + "be used too."
```

**Comment by VietND96** [comment]
I think you have to explicit define the IP (or at least localhost if it is exposed in same machine) instead of e.g --publish-events tcp://:4442

**Comment by diemol** [comment]
I will close this as the issue has not had any more activity.
