### ISSUE TITLE
Getting exception on Webelement.Click() though it clicks object in firefox

### ISSUE THREAD

**Issue by bhagyamulay** [SeleniumHQ/selenium#1457]
I am getting the exception when i tried to click an object on webpage. This happens when a link is clicked and it opens a modal dialog. Webelement.click() function clicks on the link and the modal dialog is opened but Click() takes time to return and finally logs exception as 'The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/1c7fbb96-1c1a-4717-8208-25b5193de2df/element/%7B04f6c3b3-16ae-4352-879b-ff79ccd5713a%7D/click timed out after 60 seconds.' 
I am using Selenium webdriver 2.48 for dotnet and using C#. I searched this topic and tried all the below solutions available but it behaves the same. 
1. Use Sendkeys instead of CLICK()
2. Update the webdriver code and disable the redirection
3. Used firefoxProfile.SetPreference("dom.ipc.plugins.flash.disable-protected-mode", true);
4. Use below line to reduce the 60 sec
FirefoxDriver(new FirefoxBinary(@"C:\Program Files (x86)\Mozilla Firefox\Firefox.exe"), fp, TimeSpan.FromSeconds(2));
But this reduced to some extent ~30 sec. It waits in Click() method.

The issue is occurring only on firefox in both C# as well as Java. For IE browser, its working fine.
Please let me know the solution.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bhagyamulay** [comment]
My code snippet:
firefoxDriver = new FirefoxDriver(new FirefoxBinary(@"C:\Program Files (x86)\Mozilla Firefox\Firefox.exe"), fp, TimeSpan.FromSeconds(1));
firefoxDriver.Navigate().GoToUrl("application url");
WebDriverWait wait = new WebDriverWait(firefoxDriver, TimeSpan.FromSeconds(30));
                wait.Until(ExpectedConditions.ElementIsVisible(By.XPath(".//span[@aria-label='New']"))); 

                webElement = firefoxDriver.FindElement(By.XPath(".//span[@aria-label='New']"));
                webElement.Click();
                webElement = firefoxDriver.FindElement(By.LinkText("Contract"));
                webElement.Click();

The last click() is throwing exception as 'The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/1c7fbb96-1c1a-4717-8208-25b5193de2df/element/%7B04f6c3b3-16ae-4352-879b-ff79ccd5713a%7D/click timed out after 1 seconds'

Currently i have reduced the time which was 60 sec previously to 1 sec by setting it while initializing Firefoxdriver. But it logs exception as below.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
