### ISSUE TITLE
selectWindow issue in Selenium IDE 2.9.1

### ISSUE THREAD

**Issue by Yaazi** [SeleniumHQ/selenium#1458]
Hi - I'm using the selectWindow command but not able to switch to the new window in Selenium IDE 2.9.1 for Firefox. It fails to find the title of the newly opened window after the Click event that opens the link in a new window. What am I doing wrong? I know the title is correct and it should recognize the new window. Help please!!

**Comment by seanv507** [comment]
I have a similar problem.  I cannot select window by name.
in below I looked at the log and used the randomised name and it didn't find the window.
also if I create a name in the open window, it doesn't find the window.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://www.roboform.com/" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/filling-test-all-fields</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>name=01___title</td>
	<td>abcde</td>
</tr>
<tr>
	<td>openWindow</td>
	<td>http://www.roboform.com//filling-test-all-fields</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td>name=selenium_blank83125</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>name=01___title</td>
	<td>ghij</td>
</tr>

</tbody></table>
</body>
</html>

```

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
