### ISSUE TITLE
sendKeys() on input [type=file] works on Firefox but not on Chrome

### ISSUE THREAD

**Issue by g0rd** [SeleniumHQ/selenium#1459]
firefox: 43.0.4
chrome: 47.0
chromedriver: 2.20
selenium-server: 2.48.2
```javascript
browser.executeScript('document.querySelector(\'input[type=file]\').style.display="inline";');
var inputElement = element(by.css('input[type="file"]'));
inputElement.clear();
inputElement.sendKeys(absolutePath);
````
A lot of users have this issue and I could not find a definitive answer. Any help appreciated!

**Comment by lukeis** [comment]
for chromedriver issues please log them on the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

Also provide a complete reproducible test case, which includes html of the page that is showing the issue and file you're attempting to upload.
