### ISSUE TITLE
[🚀 Feature]: Firefox-beta

### ISSUE THREAD

**Issue by mortenb-buypass** [SeleniumHQ/selenium#14603]
### Feature and motivation

Can you please add firefox beta, it is by far the easiest to upgrade, it is all here: 
https://ftp.mozilla.org/pub/firefox/releases sorted under <version>b<betanumber> it uses the same geckodriver as released.
```
playwright install help    
Failed to install browsers
Error: Invalid installation targets: 'help'. Expecting one of: chromium, chrome, chrome-beta, msedge, msedge-beta, msedge-dev, firefox, webkit
```

### Usage example

In selenium we test mainly on firefix beta. since this is the most w3c compliant webdriver and the javascript engine crashes far more than on chromium, so we mainly develop here and it runs fine on all other browsers.

**Comment by diemol** [comment]
This is already supported:
https://www.selenium.dev/documentation/selenium_manager/#automated-browser-management

**Comment by diemol** [comment]
https://www.selenium.dev/documentation/selenium_manager/#automated-browser-management
