### ISSUE TITLE
JS confirm() Defaulting to True After Selenium IDE Script Run in Same Firefox Session

### ISSUE THREAD

**Issue by rmbrntt** [SeleniumHQ/selenium#1460]
# Description

Our team was running scripts to enter data in one page that will be queried on another page for a manual test. After the data entry scripts were run, in the same Firefox session the user navigated to the page to manually test and selected a radio button that should present a confirm dialog when selected. The confirm dialog was not displayed. Investigating further led to a reference note about Selenium IDE and confirm():

> By default, the confirm function will return true, having the same effect as manually clicking OK. This can be changed by prior execution of the chooseCancelOnNextConfirmation command. 

If the user were to run the script, then close down Firefox/Selenium IDE (or open private browsing), and then navigate to the page for manual testing, the radio button confirm prompt will display. 

It appears that once Selenium IDE is used at all to run a script, default behavior for confirm() is injected into the Firefox session. The expectation would be that once a selenium script is run, Selenium IDE cleans up any browser overrides in that session.
# (Expected) Steps to reproduce

Given I have run a Selenium IDE script
And no active script or recording is running
When I enter 'confirm("test")' in the Firefox dev tools console 
Then I expect a confirmation dialog with "test" to display
# (Actual) Steps to reproduce

Given I have run a Selenium IDE script
And no active script or recording is running
When I enter 'confirm("test")' in the Firefox dev tools console 
Then the console is returning true
<img width="141" alt="2016-01-11 14_49_32-js confirm defaulting to true after selenium ide script run" src="https://cloud.githubusercontent.com/assets/2506649/12244619/9da3e0ee-b872-11e5-9723-5595382a5d96.png">

In the below gif I first run a script, then enter the confirm("test") command in the console. Dialog is suppressed auto defaulting to true. I then switch to a new tab and enter confirm("test") in console, dialog is displayed.
![20160111-selenium-1460](https://cloud.githubusercontent.com/assets/2506649/12244868/9fbb7c9c-b873-11e5-94b3-00063228f096.gif)

**Comment by murphy83** [comment]
This issue is still open.
I ran into similar issues when using assertConfirmationPresent => The test will run once but the second time it will fail with an error indicating, that no Confirmation was triggered.
Strange thing is: Sometimes waiting in the same session helps to solve the problem (no other user interaction in between).

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
