### ISSUE TITLE
[🐛 Bug]: SendKeys is sometimes not sending to the right InputBox

### ISSUE THREAD

**Issue by phuot** [SeleniumHQ/selenium#14612]
### What happened?

I do have an XUnit automated test case that interact with a logging screen using chrome browser.
The test does the following:
- wait for the `email` input box to be visible and send email address to it
- make sure the `pwd` input box is displayed and send pwd to it
- wait for the `submit` button is enabled and click on it.

Most of the times this test pass, but from time to time the test fails.
When it fails, the test taking a screenshot and we can see that the PWD (or part of it) is added to the email text input box.

ie:
![image](https://github.com/user-attachments/assets/35aff586-01e9-44f2-a127-3e60efa869f9)

### How can we reproduce the issue?

```shell
// wait for the email field to be ready and submit email address
 _wait.Until(d => _driver.FindElement(By.Id("email")).Displayed);
 _driver.FindElement(By.Id("email")).SendKeys(emailAddress);

// make sure the pwd field is visible and submit pwd
 _wait.Until(d => _driver.FindElement(By.Id("password")).Displayed);
 _driver.FindElement(By.Id("password")).SendKeys(password);

// wait for the submit buttont to be enabled and click on it
_wait.Until(d => _driver.FindElement(By.Id("submit")).Displayed);
_wait.Until(d => _driver.FindElement(By.Id("submit")).Enabled);
_driver.FindElement(By.Id("submit")).Click();
```

### Relevant log output

```shell
refer to the screenshot.
```

### Operating System

windows 11 (dev machine), Microsoft Windows Server 2022 (azure build agent)

### Selenium version

Selenium.WebDriver V4.25.0  (C# .NetCore)

### What are the browser(s) and version(s) where you see this issue?

Chrome 130.0.6723.58

### What are the browser driver(s) and version(s) where you see this issue?

Selenium.WebDriver.ChromeDriver v130.0.6723.5800, Selenium.WebDriver.MSEdgeDriver v129.0.2792.65

**Comment by nvborisenko** [comment]
@phuot  I think it is auto-focus on email input when you open login page. I guess, if you wait until email input is in focus and then fill in your fields, then the typing process is not interrupted by auto-focus feature.

**Comment by phuot** [comment]
> @phuot I think it is auto-focus on email input when you open login page. I guess, if you wait until email input is in focus and then fill in your fields, then the typing process is not interrupted by auto-focus feature.

@nvborisenko, what would be your recommended way to wait that auto-focus is completed (other than using sleeps)?

**Comment by nvborisenko** [comment]
@phuot no problem:

![image](https://github.com/user-attachments/assets/3e53db4b-d5fe-4c6d-8762-9394ccfa7f71)

**Comment by phuot** [comment]
thanks @nvborisenko I will try this and monitor my tests for the next few days to see if that helps, but it looks to make a lot of sense.

**Comment by nvborisenko** [comment]
Will be happy to see you here again 😁 Closing it for now, feel free to reopen.
