### ISSUE TITLE
Clues about a Bug causing instability in DriverService in selenium-java

### ISSUE THREAD

**Issue by binodpanta** [SeleniumHQ/selenium#1461]
Referring to this issue I created a while back, https://github.com/SeleniumHQ/selenium/issues/676  , I think the source of the issue is that waitUntilAvailable() is too quick to check status code of the process, before it has even completed or had a chance to return a status code. When I used apache commons libs with a tool called jscover, I had this same issue and it got completely fixed when I added a 1s pause before the first attempt to check status.

Can something like this be done for this code too? It seems to be causing sporadic failures quite frequently for me, with just about any driver (since the bug is in the selenium-java layer code)

The code I am referring to is here:

https://github.com/SeleniumHQ/selenium/blob/9c1b1e66c9326c8d7c38cc7fb8814877210a4388/java/client/src/org/openqa/selenium/remote/service/DriverService.java

**Comment by barancev** [comment]
I can "reproduce" the exception described in the issue #676, but it's a legit case when the timeout expected. For example, if you try to start a hundred of Chromes it takes more that 20 seconds, and the exception occurs (many times):
https://gist.github.com/barancev/bd42983a3a7e595b6573

But, I want to reiterate, it's a legit case, there is nothing to fix there.

**Comment by binodpanta** [comment]
Thanks for the reproduction steps and explanation!

How do you suggest I deal with this? I am the tooling provider so my consumers are frustrated on seeing this as you can imagine. I can think of a retry strategy where I check this condition and start-over, do you think that will have a chance of stabilizing the test base?

**Comment by barancev** [comment]
Just don't start too many browsers at once. Manage driver initialzation queue.

**Comment by snpanigrahi9** [comment]
Hi Barancev..
I am invoking chrome driver only once but still getting the issue.

I have created a method called Launch and inside that method i have used ChromeDriverService to invoke chrome driver and the method name Launch is a keyword for me..i am writting this keyword in excel to invoke that Launch method..sometimes its launching the browser sometimes does not.

	public AFTEventResult Launch() {
		try {
			objWebDriver = null;
			DesiredCapabilities caps;

			strBrowser = "";
			// Handling Android Application
			if (this.strParam2.toUpperCase().equals("ANDROID")) { // Through
																	// Appium
				caps = new DesiredCapabilities();
				String AppiumServerURL = "http://127.0.0.1:4723/wd/hub";
				/*
				 * strBrowser = ""; caps = DesiredCapabilities.android();
				 * caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
				 * caps.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR,
				 * org.openqa.selenium.UnexpectedAlertBehaviour.IGNORE);
				 * objWebDriver = new AndroidDriver(caps);
				 */
				if (this.strParam3.equals("")) {
					this.strParam3 = "4.4.2"; // Default version for Android
				}

				// Set Capabilities
				caps.setCapability("platformName", "Android");
				caps.setCapability("platformVersion", this.strParam3);
				if (this.strParam4.equals("")
						|| this.strParam4.equalsIgnoreCase("EMULATOR")) {
					caps.setCapability("newCommandTimeout", "300");
					caps.setCapability("browserName", "browser");
					caps.setCapability("deviceName", "Android Emulator");
					caps.setCapability("ignoreUnimportantViews", true); // To
																		// Improve
																		// Performance
				} else {
					caps.setCapability("deviceName", "Android");
					caps.setCapability("newCommandTimeout", "120");
					caps.setCapability("browserName", "Chrome");
					caps.setCapability("udid", this.strParam4);
				}
				objWebDriver = new RemoteWebDriver(new URL(AppiumServerURL),
						caps);

				// Set Page Default Page Load time
				if (this.strParam4.equals("")
						|| this.strParam4.equalsIgnoreCase("EMULATOR")) {
					try {
						objWebDriver.manage().timeouts()
								.pageLoadTimeout(5, TimeUnit.SECONDS);
						objWebDriver
								.navigate()
								.to("https://10.100.12.152:9106/web/neworgciqa/login");
					} catch (Exception e) {
						// Do Nothing
					} finally {
						objWebDriver.manage().timeouts()
								.pageLoadTimeout(100, TimeUnit.SECONDS);
					}

					// Run Batch File to manage SSL Security Certificate Popup
					File f = new File(SharedResource.strRootFolder
							+ "\\Batch\\");
					ProcessBuilder pb = new ProcessBuilder("cmd", "/c",
							"start", "HandelSecurityCertificate.bat");
					pb.directory(f);
					try {
						Process process = pb.start();
					} catch (IOException e3) {
						// TODO Auto-generated catch block
						// e3.printStackTrace();
					}
				} else {
					objWebDriver.manage().timeouts()
							.pageLoadTimeout(20, TimeUnit.SECONDS);
				}
			}
			// Handling Iphone Application
			else if (this.strParam2.toUpperCase().equals("IPHONE")) {
				strBrowser = "";
				URL strURL = null;
				caps = DesiredCapabilities.iphone();
				caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
				caps.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR,
						org.openqa.selenium.UnexpectedAlertBehaviour.IGNORE);
				if (this.strParam3.equals("")) {
					System.out
							.println("Please give IP Adress of the Iphone WebDriver");
					System.exit(0);
				} else if (this.strParam3.contains("http")
						&& this.strParam3.contains("hub")) {
					strURL = new URL(this.strParam3);
				} else {
					strURL = new URL("http://" + this.strParam3.trim()
							+ ":3001/hub/");
				}
				objWebDriver = new RemoteWebDriver(strURL,
						DesiredCapabilities.iphone());
				// objWebDriver = new IPhoneDriver(strURL);
			}
			// Handling Chrome Browser
			else if (this.strParam2.toUpperCase().equals("CHROME")) {
				strBrowser = "CHROME";
				ChromeDriverService service = new ChromeDriverService.Builder()
						.usingDriverExecutable(
								new File(SharedResource.strRootFolder
										+ "\\Selenium\\chromedriver.exe"))
						.usingAnyFreePort().build();
				service.start();
				caps = DesiredCapabilities.chrome();
				caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

				ChromeOptions options = new ChromeOptions();
				options.addArguments("chrome.switches", "--disable-extensions");
				caps.setCapability(ChromeOptions.CAPABILITY, options);

				// Commented because we want to ON Multiple Instances of chrome
				// caps.setCapability("chrome.switches",
				// Arrays.asList("--disable-extensions"));
				/*
				 * caps.setCapability("chrome.binary",
				 * "C:/Documents and Settings/"+System.getProperty("user.name")+
				 * "/Local Settings/Application Data/Google/Chrome/Application/chrome.exe"
				 * ); ChromeOptions options = new ChromeOptions();
				 * options.addArguments
				 * ("user-data-dir=C:/Documents and Settings/"
				 * +System.getProperty("user.name")+
				 * "/Local Settings/Application Data/Google/Chrome/User Data/Default"
				 * ); caps.setCapability(ChromeOptions.CAPABILITY, options);
				 * caps.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR,
				 * org.openqa.selenium.UnexpectedAlertBehaviour.IGNORE);
				 */
				objWebDriver = new RemoteWebDriver(service.getUrl(), caps);
				SharedResource.dictRTVarCollection.put(strParam3, strParam2);
			}
