### ISSUE TITLE
[🐛 Bug]: WebDriverWait polling consistency between Java and Python implementations

### ISSUE THREAD

**Issue by guillaumepichenot** [SeleniumHQ/selenium#14623]
### What happened?

I have noticed that on my Python-based Seleniums runs, when using a `WebDriverWait` to check (let's say by CSS selector) for a **non** existing element in the DOM, the call never takes less than 500ms, whereas I consistently  get <100ms for existing elements.

The behavior does not arise in Java implementations of the same scenario.

My best guess is that the Java and Python implementation have different `sleep` strategy orchestration.

 Current python loop : 
https://github.com/SeleniumHQ/selenium/blob/1b647987bafcdf0297edbafa543c84caf5623201/py/selenium/webdriver/support/wait.py#L94-L105

Current java loop : 
https://github.com/SeleniumHQ/selenium/blob/1b647987bafcdf0297edbafa543c84caf5623201/java/src/org/openqa/selenium/support/ui/FluentWait.java#L201-L237

Note that the Python orchestration is : 
1. Timestamp the timeout end
2. Perform the lookup
3. sleep
4. Check now vs. timeout to exit

The Java implementation is : 
1. Timestamp the timeout end
2. Perform the lookup
3. Check new vs. timeout to exit
4. Sleep

The inversion of steps 3 and 4 is manifest IMO.
The Java version looks more sensible to me, as it allows for effectively having `timeout=0` checks, while python implementations in practice will never get a sub `pollingInterval` check (for non-existing elements).

### How can we reproduce the issue?

```shell
WebDriverWait(driver, 0).until(
  visibility_of_any_elements_located((By.CSS_SELECTOR, "#anyIdThatDoesNotExist"))
);


Notice you will never get <500ms (`POLL_FREQUENCY`) results.
```

### Relevant log output

```shell
N/A
```

### Operating System

macOs, Linux

### Selenium version

4.0.25

### What are the browser(s) and version(s) where you see this issue?

Chrome 129

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 129

**Comment by navin772** [comment]
Hi @guillaumepichenot, I tried reproducing this and indeed the time is never less than 500ms as the `POLL_FREQUENCY` is set to [0.5s](https://github.com/SeleniumHQ/selenium/blob/d922168d801e5a468ae3edbc68cb1055f04c9f41/py/selenium/webdriver/support/wait.py#L32) if not provided as a parameter.
You can set the `poll_frequency` parameter to 0.1 to see sub 500ms time. 
Something like this:

```py
WebDriverWait(driver, 0, poll_frequency=0.1).until(
  visibility_of_any_elements_located((By.CSS_SELECTOR, "#anyIdThatDoesNotExist"))
);
```

But regardless, I think the python bindings should be like Java ones as you suggested. I will open a PR for the same!

Thanks for reporting this issue!

**Comment by guillaumepichenot** [comment]
@navin772 thanks for confirming.

We can indeed work-around the issue as you highlighted.

(By the way, the bug template looked more appropriate than feature request but anyway, I guess we all agree consistency is the key argument here).
