### ISSUE TITLE
[🐛 Bug]: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

### ISSUE THREAD

**Issue by alibdaer** [SeleniumHQ/selenium#14630]
### What happened?

This Warning appear:

Oct 21, 2024 10:55:20 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

please not i have the latest versions for all dependencies

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.25.0</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.9.2</version>
        </dependency>

Because of that and after this warning started appearing, I have errors while running the test case, it no longer waits for the **Iframe** to finish fully loading.

### How can we reproduce the issue?

```shell
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.25.0</version>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.9.2</version>
        </dependency>
```

### Relevant log output

```shell
Oct 21, 2024 10:55:20 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130
```

### Operating System

Windows 10

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chorme (Latest Version: 130.0.6723.59) 

### What are the browser driver(s) and version(s) where you see this issue?

webdrivermanager - 5.9.2 (chromedriver - 130.0.6723.58)

**Comment by mrankin32** [comment]
I have almost the same specs and versions as the author but with Windows 11 instead of Windows 10 with the same error:

[10/21/2024 21:54:57] WARN : org.openqa.selenium.devtools.CdpVersionFinder : Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

Later I found out the root of my problem was because I had the following in my build.gradle making me feel stupid:
```
configurations {
    all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details->
            if (details.requested.group == 'org.seleniumhq.selenium') {
                details.useVersion('4.25.0')
            }
        }
    }
}
```
I updated details.useVersion('4.25.0') to details.useVersion('4.27.0') and all is well and warning is gone.

**Comment by LloyDee** [comment]
Same issue here:
```
<dependencies>
        <!-- https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.25.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.9.2</version>
        </dependency>
</dependencies>
```

Oct 21, 2024 11:32:23 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

**Comment by alibdaer** [comment]
The problem is not only the warning, but some of the written commands are now working illogically, and some pages and frames are now being dealt with without waiting for them to load. Something has changed. I have test cases that have been working properly for more than a year, now after this warning they are broken and not working. We are waiting for the problem to be solved, either by a new version of selenium, or for the issue to be fixed by the browsers.

**Comment by SerhiiYesychko** [comment]
using the same versions 
<dependencies>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.25.0</version>
        </dependency>
        
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>5.9.2</version>
        </dependency>
</dependencies>

I test started failing on Friday with
NoSuchSession Session ID is null.  randomly at some moment during test run

**Comment by krish-tcc** [comment]
Same - literally just started happening to me right in the middle of using selenium. 

Please update to a Selenium version that supports CDP version 130

**Comment by miteshkumat** [comment]
Same issue happen to me. I literally try to hard solve this problem . Please update Selenium version that supports CDP version 130.This is my error.

Oct 22, 2024 8:20:58 P.M. org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

**Comment by eftewuer** [comment]
Confirmed. This warning started to appear when running existing selenium tests with Chrome 130.x.

**Comment by SerhiiVoloshchenko** [comment]
Thats because in 4.25.0 you have only selenium-devtools-v129 but there is no selenium-devtools-v130. Thats mean you not supporting Chrome v130

**Comment by alibdaer** [comment]
> Thats because in 4.25.0 you have only selenium-devtools-v129 but there is no selenium-devtools-v130. Thats mean you not supporting Chrome v130

Well, how can supporting the chrome v130?

**Comment by AnushanVamathevan** [comment]
I’m facing the same problem, and I’ve been struggling to fix it. The error says I need to update Selenium to a version that supports CDP version 130.
This is my error:
Oct 23, 2024 3:49:37 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 130, returning the closest version; found: 129; Please update to a Selenium version that supports CDP version 130

**Comment by anilreddy** [comment]
Guys the warning is not bug or anything it will go when new version of selenium is released. You are seeing this warning because current selenium version only supports V129 not V130.

**Comment by SerhiiYesychko** [comment]
So I tried few options
like java 11-17
selenium and driver 4.23-25
chrome and chrome driver 127-130
everything works fine locally if I run using Intelijj Idea and maven
but when I try to run it in docker

FROM maven:3.6.3-openjdk-17-slim or FROM maven:3.6.3-openjdk-11

randomly at some point I get 

[ERROR]   SlideDeckV5Test>BaseTest.setUp:524 » NoSuchSession Session ID is null. Using WebDriver after calling quit()?
Build info: version: '4.23.0', revision: '4df0a231af'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.6.51-0-virt', java.version: '17-ea'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, get {url=*here goes my url*/}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 127.0.6533.119, chrome: {chromedriverVersion: 127.0.6533.119 (bdef6783a05..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:37051}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:37051/devtoo..., se:cdpVersion: 127.0.6533.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}

BaseTest.setUp:524  here I have method that created webdriver as usual
        if (driver == null) {
            driver = DriverFactory.getInstance().getWebDriver();
            driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(Constants.WAITING_TIMEOUT));
            driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(Constants.WAITING_TIMEOUT));
        }
        return driver;
        
        also it happens when it call driver.quit();
        
        have no idea what happened with docker runs, there was no changes

**Comment by alibdaer** [comment]
**Here is the temporary solution, until Selenium supports version 130, delete Google Chrome completely and reinstall the older version which is 129, this way the problem will be solved temporarily**

You can **download Chrome V129** from this link: [https://www.filepuma.com/download/google_chrome_64bit_129.0.6668.101-41911/](https://www.filepuma.com/download/google_chrome_64bit_129.0.6668.101-41911/)

**Comment by MuratTopcu** [comment]
I use Selenium Manager and I tell it to download and use version 129

https://www.selenium.dev/documentation/selenium_manager/

**Comment by diemol** [comment]
> Guys the warning is not bug or anything it will go when new version of selenium is released. You are seeing this warning because current selenium version only supports V129 not V130.

Exactly what @anilreddy says. 

It is a WARNING that does not stop you from using Chrome 130. 

We will release a new version of Selenium next week.

**Comment by alibdaer** [comment]
> > Guys the warning is not bug or anything it will go when new version of selenium is released. You are seeing this warning because current selenium version only supports V129 not V130.
> 
> Exactly what @anilreddy says.
> 
> It is a WARNING that does not stop you from using Chrome 130.
> 
> We will release a new version of Selenium next week.

Yes it does not stop me from using chrome 130, but there are errors in recognizing the element and sendKey and some problems waiting for pages to load and iframes and others,

Thank you for your response and we are waiting for the new release of Selenium

**Comment by diemol** [comment]
The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.

**Comment by alibdaer** [comment]
> The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.

I did it: https://issuetracker.google.com/issues/375343406

**Comment by anilreddy** [comment]
@

> > The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.
> 
> I did it: https://issuetracker.google.com/issues/375343406

@alibdaer your bug will not be accepted anywhere if you don't provide reproducible code or logs where the issue happens.
How can any one knows where the bug is actually happening.

Regarding chrome V130 all my scripts are working as expected. I didn't observe any issues as you posted like identifying elements or switching to iframes.

Once posting a bug please check if you are writing proper code which has explicit waits before doing element interactions incase of please waits or there is a loading.

**Comment by alibdaer** [comment]
> @
> 
> > > The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.
> > 
> > 
> > I did it: https://issuetracker.google.com/issues/375343406
> 
> @alibdaer your bug will not be accepted anywhere if you don't provide reproducible code or logs where the issue happens. How can any one knows where the bug is actually happening.
> 
> Regarding chrome V130 all my scripts are working as expected. I didn't observe any issues as you posted like identifying elements or switching to iframes.
> 
> Once posting a bug please check if you are writing proper code which has explicit waits before doing element interactions incase of please waits or there is a loading.

I appreciate your advice, but it is naive of me to complain about a problem when I am not sure about the quality of my code.

Yes, my code is written accurately and professionally and I have been using it for more than two years for the server we work with.

After the latest updates, this problem appeared. I do not think it is magic or sorcery, but there is indeed a problem after the latest Google Chrome update.

It is not that simple. How can I attach a report that shows me that it does not recognize Element while before the update it recognized it without problems? How can I convince people like you that it is a problem with the update and not with the code?

Why when I downgrade Google Chrome to version 129 the code works successfully and without problems?

Specialists should review this matter, not me

Thank you, dear professional

**Comment by anilreddy** [comment]
> > @
> > > > The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.
> > > 
> > > 
> > > I did it: https://issuetracker.google.com/issues/375343406
> > 
> > 
> > @alibdaer your bug will not be accepted anywhere if you don't provide reproducible code or logs where the issue happens. How can any one knows where the bug is actually happening.
> > Regarding chrome V130 all my scripts are working as expected. I didn't observe any issues as you posted like identifying elements or switching to iframes.
> > Once posting a bug please check if you are writing proper code which has explicit waits before doing element interactions incase of please waits or there is a loading.
> 
> I appreciate your advice, but it is naive of me to complain about a problem when I am not sure about the quality of my code.
> 
> Yes, my code is written accurately and professionally and I have been using it for more than two years for the server we work with.
> 
> After the latest updates, this problem appeared. I do not think it is magic or sorcery, but there is indeed a problem after the latest Google Chrome update.
> 
> It is not that simple. How can I attach a report that shows me that it does not recognize Element while before the update it recognized it without problems? How can I convince people like you that it is a problem with the update and not with the code?
> 
> Thank you, dear professional

Sorry to say but they will close the bug simply check after some days

**Comment by alibdaer** [comment]
> > > @
> > > > > The errors seem related to the browser version, not Selenium itself. In that case, you should create an issue in the Chrome bug tracker.
> > > > 
> > > > 
> > > > I did it: https://issuetracker.google.com/issues/375343406
> > > 
> > > 
> > > @alibdaer your bug will not be accepted anywhere if you don't provide reproducible code or logs where the issue happens. How can any one knows where the bug is actually happening.
> > > Regarding chrome V130 all my scripts are working as expected. I didn't observe any issues as you posted like identifying elements or switching to iframes.
> > > Once posting a bug please check if you are writing proper code which has explicit waits before doing element interactions incase of please waits or there is a loading.
> > 
> > 
> > I appreciate your advice, but it is naive of me to complain about a problem when I am not sure about the quality of my code.
> > Yes, my code is written accurately and professionally and I have been using it for more than two years for the server we work with.
> > After the latest updates, this problem appeared. I do not think it is magic or sorcery, but there is indeed a problem after the latest Google Chrome update.
> > It is not that simple. How can I attach a report that shows me that it does not recognize Element while before the update it recognized it without problems? How can I convince people like you that it is a problem with the update and not with the code?
> > Thank you, dear professional
> 
> Sorry to say but they will close the bug simply check after some days

I have no problem closing it, as it will be resolved after the new release of Selenium next week according to Team Lead.

As you can see many of the comments before you are suffering from the same problem, I am not the only one suffering from this, we are not complaining about the presence of a warning only. We are complaining about the problems that started to appear after the update

**Comment by bartlomiejfydrych** [comment]
I confirm this issue is occurring.

It looks like there was an update to Chrome Dev Tools and now we need to wait for Selenium to release an update that supports this version.

**Comment by joerg1985** [comment]
Are you using a fat jar? See https://github.com/SeleniumHQ/selenium/issues/14538#issuecomment-2377444594

**Comment by jain0nikhil** [comment]
> > Guys the warning is not bug or anything it will go when new version of selenium is released. You are seeing this warning because current selenium version only supports V129 not V130.
> 
> Exactly what @anilreddy says.
> 
> It is a WARNING that does not stop you from using Chrome 130.
> 
> We will release a new version of Selenium next week.

do we have any update on new version (v130) release?

**Comment by jiacheng-0** [comment]
Hi @diemol are you at Selenium Dev team? 
I am working on stack that requires me to update browser drivers every month. 
May I ask if Selenium source course from selenium-java:jar:4.25.0+ will ensure that driver versions are updated accordingly every month? 

In my software testing team, we realise that we just have to ensure that our chromedriver versions are n-1 version at most. 
n being the current latest version (v130 at the time of writing)
n -1 means v129 for example.

mvn dependency:tree of my project
[INFO] +- org.seleniumhq.selenium:**selenium-java:jar:4.25.0**:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:4.25.0:compile
[INFO] |  |  \- org.jspecify:jspecify:jar:1.0.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.25.0:compile
[INFO] |  |  +- com.google.auto.service:auto-service-annotations:jar:1.1.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v127:jar:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v128:jar:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:**selenium-devtools-v129:jar**:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.25.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.25.0:compile

**Comment by diemol** [comment]
Selenium 4.26.0 has been released.

We try to release every month, but sometimes things get in the way. Most of us do this in our free time as volunteers.

If you want to be part of the team and help ensure monthly releases, come talk to us: https://www.selenium.dev/support/#ChatRoom

**Comment by coderextreme** [comment]
Waiting for something later than 4.26.0 for Java to so I can run in Chrome v131.  I'm getting:
```
Nov 20, 2024 6:28:56 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 130; Please update to a Selenium version that supports CDP version 131
Driver is org.openqa.selenium.chrome.ChromeDriver
```

But everything is working great, I just upgraded to 4.26.0

**Comment by coderextreme** [comment]
Well, except for launching from maven with the following plugin:

```
<plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.3</version>
                <configuration>
                    <mainClass>net.coderextreme.main.App</mainClass>
                    <commandlineArgs>src/main/resources/net/coderextreme/motion/contact.data target/classes/net/coderextreme/motion/gedda/</commandlineArgs>
                </configuration>
            </plugin>
```

I use:

```
$ mvn javafx:run
```

Hint:  Try to launch the ChromeDriver...

**Comment by Senjutsuqp** [comment]
Чтобы избавиться от проблемы, укажите в pom.xml версию Selenium 4.27.0

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.27.0</version>
        </dependency>
    </dependencies>

**Comment by estherwangyusu** [comment]
Same here:
WARNING: Unable to find version of CDP to use for 131.0.6778.86. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.21.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.

on macOS x86, and I also tried to manually download matching CDP and it didn't work.

**Comment by coderextreme** [comment]
It looks like you need selenium 4.21.0 (for v86) or 4.27.0 (for v131). I
recommend updating your classpath, particularly the
selenium-devtools-v###-4.2#.0 jar.  Note that the 4.2#.0 should match your
other selenium jars.

I didn’t have much success with gradle, but upgrading dependencies in
build.gradle, pom.xml or build.xml may be necessary.

If anyone has a clean build.gradle, let me know.  Part of my problem was
including an unnamed module.

**Comment by HanselCream** [comment]
I need help, using IntelliJ.

Nov 27, 2024 10:23:14 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 131
Nov 27, 2024 10:23:14 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$5
WARNING: Unable to find version of CDP to use for 131.0.6778.86. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.21.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.

**Comment by coderextreme** [comment]
You probably need a needle version of selenium, like this:
https://github.com/coderextreme/abstractionmapper/blob/master/selenium-java/selenium-devtools-v131-4.27.0.jar

**Comment by coderextreme** [comment]
Sorry, I meant a new version of selenium.

John

**Comment by zielinskikamil** [comment]
the 4.27v seems to not introducing support for 131 .
My setup:
`ChromeDriver 131.0.6778.85 (3d81e41b6f3ac8bcae63b32e8145c9eb0cd60a2d-refs/branch-heads/6778@{#2285})`
`Google Chrome 131.0.6778.86`

implementation 'org.seleniumhq.selenium:selenium-chrome-driver:4.27.0'

When init ChromeDriver it throws: 

```
Nov 28, 2024 9:12:16 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find CDP implementation matching 131
Nov 28, 2024 9:12:16 PM org.openqa.selenium.chromium.ChromiumDriver lambda$new$5
WARNING: Unable to find version of CDP to use for 131.0.6778.86. You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.27.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's the 4.27 was suppose to add CDP
```

**Comment by coderextreme** [comment]
Do you have this:


https://github.com/coderextreme/abstractionmapper/blob/master/selenium-java/selenium-devtools-v131-4.27.0-sources.jar

in your CLASSPATH?  I don’t think it will work if you just replaced the
4.2#.0 with 4.27.0.  You have to change the v### to v131.

Good luck, and Happy Thanksgiving!

**Comment by coderextreme** [comment]
Sorry, wrong link!

https://github.com/coderextreme/abstractionmapper/blob/master/selenium-java/selenium-devtools-v131-4.27.0.jar

Not the sources, lol!

John
