### ISSUE TITLE
[🐛 Bug]: Regression in closed shadow root access with Chrome Beta 131

### ISSUE THREAD

**Issue by GaurangTandon** [SeleniumHQ/selenium#14631]
### What happened?

Here's a video showing the issue: https://www.loom.com/share/1101be1e1c1a4770a439cf0041c5c882

Plain text output log for your convenience:

```text
(venv) venv➜  test-selenium python runtest.py
Chrome 130.0.6723.59 (Official Build) (arm64)
Got exception while accessing inside closed shadow root
(venv) venv➜  test-selenium python runtest.py
Chrome 131.0.6778.3 (Official Build) beta (arm64)
Got text from inside closed shadow root inner text
```

Based on how Selenium has always behaved, I believe this new behavior on Chrome 131 is a regression. Running `document.getElementById('root').shadowRoot` still returns `null` in Chrome 131, so I think this might be a Selenium issue rather than Chrome issue. Please do let me know if it's otherwise and I will report it on bugs.chromium.org/p/chromedriver

### How can we reproduce the issue?

Python code:

```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
 
options = webdriver.ChromeOptions()
options.add_argument("--disable-features=ChromeWhatsNewUI,PrivacySandboxSettings4")
options.add_argument("--disable-search-engine-choice-screen")
options.binary_location = '/Applications/Google Chrome Beta.app/Contents/MacOS/Google Chrome Beta'

driver = webdriver.Chrome(service=ChromeService(), options=options)

driver.get('chrome://version')
try:
  print('Chrome', driver.find_element(By.ID, 'version').text)
  driver.get('file:///Users/blazegt/test-selenium/test.html')
  root = driver.find_element(By.ID, 'root')
  shadow_root = root.shadow_root
  inner = shadow_root.find_element(By.ID, 'inner')
  print('Got text from inside closed shadow root', inner.text)
except:
  print('Got exception while accessing inside closed shadow root')
```

HTML file:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shadow root</title>
</head>

<body>
    <div id="root"></div>
    <script>
        const shadow = root.attachShadow({ mode: 'closed', });
        const inner = document.createElement('inner');
        inner.id = 'inner';
        inner.textContent = 'inner text';
        shadow.appendChild(inner);
    </script>
</body>

</html>
```

Install selenium and run `python runtest.py` two times, once with the `binary_location` set to Chrome beta (as it is right now) and other without it (so it runs stable version). The video shows the step clearly.

### Relevant log output

When I put 

```python
logger = logging.getLogger('selenium')
logger.setLevel(logging.DEBUG)
```

at the top of the Python file above, I don't get any logs output on the terminal.

### Operating System

macOS

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 131 beta

### What are the browser driver(s) and version(s) where you see this issue?

(automatically downloaded by Selenium)

**Comment by navin772** [comment]
Hi @GaurangTandon, I am not able to reproduce this issue. I have tried with the Chrome Beta/ stable and both 130, 131 chromedriver versions.

Here is the output I get:

```
(selenium-py311) ➜  python py_14631.py
Chrome 130.0.6723.59 (Official Build) (x86_64)
Got exception while accessing inside closed shadow root

(selenium-py311) ➜  python py_14631.py
Chrome 131.0.6778.3 (Official Build) beta (x86_64)
Got exception while accessing inside closed shadow root
```

Maybe you can reinstall the drivers and Chrome Beta and try again.

**Comment by navin772** [comment]
@GaurangTandon thanks for reporting this issue.

I was able to reproduce this issue with Google Chrome Beta (131), but since this issue doesn't occurs in Chrome stable with selenium, we cannot currently say that it's a selenium issue.
I think you should go ahead and post this in chromedriver issues. I will recheck this again when Chrome 131 stable is launched.

**Comment by GaurangTandon** [comment]
Sure I have posted it on Chromedriver bugs now also: https://issues.chromium.org/issues/375892677

**Comment by navin772** [comment]
This is the intended behaviour since Chrome 131. Webdriver can now search for closed shadow roots as per - https://chromium-review.googlesource.com/c/chromium/src/+/5923865

**Comment by diemol** [comment]
@whimboo helped me to understand that returning something when the shadow root is null is an error, as step 5 says: https://w3c.github.io/webdriver/#get-element-shadow-root

I will comment on the Chromium bug report as it is still valid.
