### ISSUE TITLE
[🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain

### ISSUE THREAD

**Issue by bicycleali** [SeleniumHQ/selenium#14644]
### What happened?

I am working with visual studio 2019. In the development area the new feature of my website works verry well. 
After publishing to the domain, I am getting the error message:
"Selenium Manager process exited abnormally with 65 code: D:\var\www\vhosts\unsertrainingstagebuch.de\httpdocs\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>"

So far, I tried to find a solution or a workaround for my problem, without success.
Therefore, I would be happy to get help from your **side.**
[2024_10_24_Selenium Manager process exited abnormally with 65 code.docx](https://github.com/user-attachments/files/17507790/2024_10_24_Selenium.Manager.process.exited.abnormally.with.65.code.docx)
[2024_10_24_Selenium Manager process exited abnormally with 65 code.docx](https://github.com/user-attachments/files/17508129/2024_10_24_Selenium.Manager.process.exited.abnormally.with.65.code.docx)
****

### How can we reproduce the issue?

```shell
You can ease reproduce the issue

https://unsertrainingstagebuch.de/login.aspx?ReturnUrl=%2fFahrrad%2f01_Fahrten%2fEF_INSERT_SIGMA_URL.aspx

Please open the requested site with Userid: Brägel Passwort: brägel

If you are logged in please copy the following URL into the text box and klick the yellow button.
Maybe you must klick twice to start the functionality which runs into the error issue.

https://sigma-sharing.com/view/activity/a4bf0d4bd23b37e450484de1770fc91629a31bd9
```

### Relevant log output

```shell
Serverfehler in der Anwendung /.
Selenium Manager process exited abnormally with 65 code: D:\var\www\vhosts\unsertrainingstagebuch.de\httpdocs\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
 "logs": [
   {
     "level": "WARN",
     "timestamp": 1729777641,
     "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
   },
   {
     "level": "WARN",
     "timestamp": 1729777641,
     "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
   },
   {
     "level": "ERROR",
     "timestamp": 1729777650,
     "message": "Zugriff verweigert (os error 5)"
   }
 ],
 "result": {
   "code": 65,
   "message": "Zugriff verweigert (os error 5)",
   "driver_path": "",
   "browser_path": ""
 }
}

<<
Beschreibung: Unbehandelte Ausnahme beim Ausführen der aktuellen Webanforderung. Überprüfen Sie die Stapelüberwachung, um weitere Informationen über diesen Fehler anzuzeigen und festzustellen, wo der Fehler im Code verursacht wurde.

Ausnahmedetails: OpenQA.Selenium.WebDriverException: Selenium Manager process exited abnormally with 65 code: D:\var\www\vhosts\unsertrainingstagebuch.de\httpdocs\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
 "logs": [
   {
     "level": "WARN",
     "timestamp": 1729777641,
     "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
   },
   {
     "level": "WARN",
     "timestamp": 1729777641,
     "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
   },
   {
     "level": "ERROR",
     "timestamp": 1729777650,
     "message": "Zugriff verweigert (os error 5)"
   }
 ],
 "result": {
   "code": 65,
   "message": "Zugriff verweigert (os error 5)",
   "driver_path": "",
   "browser_path": ""
 }
}

<<


Quellfehler:

Beim Ausführen der aktuellen Webanforderung wurde einen unbehandelte Ausnahme generiert. Informationen über den Ursprung und die Position der Ausnahme können mit der Ausnahmestapelüberwachung angezeigt werden.

Stapelüberwachung:


[WebDriverException: Selenium Manager process exited abnormally with 65 code: D:\var\www\vhosts\unsertrainingstagebuch.de\httpdocs\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json
Standard Output >>
{
  "logs": [
    {
      "level": "WARN",
      "timestamp": 1729777641,
      "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
    },
    {
      "level": "WARN",
      "timestamp": 1729777641,
      "message": "Metadata cannot be written in cache (): Zugriff verweigert (os error 5)"
    },
    {
      "level": "ERROR",
      "timestamp": 1729777650,
      "message": "Zugriff verweigert (os error 5)"
    }
  ],
  "result": {
    "code": 65,
    "message": "Zugriff verweigert (os error 5)",
    "driver_path": "",
    "browser_path": ""
  }
}

<<
]
   OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments) +766

[WebDriverException: Error starting process: D:\var\www\vhosts\unsertrainingstagebuch.de\httpdocs\selenium-manager\windows\selenium-manager.exe  --browser "chrome" --language-binding csharp --output json]
   OpenQA.Selenium.SeleniumManager.RunCommand(String fileName, String arguments) +852
   OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments) +140
   OpenQA.Selenium.DriverFinder.BinaryPaths() +78
   OpenQA.Selenium.DriverFinder.GetDriverPath() +8
   OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout) +85
   OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options) +146
   OpenQA.Selenium.Chrome.ChromeDriver..ctor() +50
   Fahrrad_01_Fahrten_EF_INSERT_SIGMA_URL.BTnwebload_Click(Object sender, EventArgs e) +86
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9797046
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +211
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1696

Versionsinformationen: Microsoft .NET Framework-Version:4.0.30319; ASP.NET-Version:4.8.4676.0
```

### Operating System

PLESKWINDOWS

### Selenium version

Selenium.WebDriver 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Selenium.WebDriver.Chrome 130.0.6723.6900

### What are the browser driver(s) and version(s) where you see this issue?

Google Chrome Version 130.0.6723.70 (Offizieller Build) (64-Bit)

### Are you using Selenium Grid?

I don't know

**Comment by nvborisenko** [comment]
Summary:
```
Metadata cannot be written in cache (): Access Denied (os error 5)
```

@bicycleali your application is denied writing to some specific file path.

You can specify `SE_CACHE_PATH` environment variable where you have permissions and [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) can write to.

PS: @bonigarcia would be great if error contains info about where SM is trying to write to.

**Comment by bicycleali** [comment]
Thank you verry much for your fast answer. To be honest I am not a professional programmer. My profession is more bicycling.
Anyway. Where could I specify SE_CACHE_PATH environment variable. Do I have to do it in the "aspx.file" where the use of selenium-manager is defined? Those part is visible in the attached file.
[2024_10_24_VisualStudio2019_EF_INSERT_SIGMA_URL.aspx.docx](https://github.com/user-attachments/files/17511465/2024_10_24_VisualStudio2019_EF_INSERT_SIGMA_URL.aspx.docx)

**Comment by bicycleali** [comment]
PS: @bonigarcia would be great if error contains info about where SM is trying to write to.

How can I find it out? In the browser?

**Comment by bonigarcia** [comment]
> would be great if error contains info about where SM is trying to write to.

The cache path is displayed between the parenthesis in that error message. In this case, it seems that cache path is empty for some reason, and that seems to be cause of the problem:

```
Metadata cannot be written in cache (<cache_path>)
```

**Comment by bicycleali** [comment]
Do I have to do anything in my code to get it fixed or is it a bug? I am just wondering that everything works fine in the development environment,

**Comment by nvborisenko** [comment]
Your code is right, but an environment, where your is executing, is not "friendly" with Selenium. I suppose your Web App is ran under IIS with special permissions which prevents SM to determine User's cache folder (most likely because of there is no user account, probably some service account).

Main question: "did it work before with some previous version of Selenium?".

BTW: I see your task is just getting web page source and that's it? In this case I recommend using other tools, which don't require real browser. Like https://github.com/AngleSharp/AngleSharp. Selenium is more about automating real browser as real user is interacting with it, in your case it may be overhead.

**Comment by bicycleali** [comment]
I am just started with the new feature of my side. Therefore I can not answer your question really, because I didn’t use earlier versions of Selenium.


Thanks for your proposal. I don’t know what “AngleSharp/AngleSharp” is doing. I started my new feature reading a website with using the “HTMLAgilityPack”. Unfortunately with this alone it was not possible to read the whole side.
<app-root…></app-root> In this section all the info’s I am interested in are sitting in this section which was not readable without selenium. Now it works perfect. I am storing the selected info’s in my sql database (Insert a new record with nearly twenty fields.

I was verry happy to get it done. Therefore I would be happy you could find a workaround for me to make it running in the my environment.

Maybe it would be possible to create a User's cache folder outside of selenium, because I have all rights if I publish my side.  In the attached file you can see the file structure of my project and it give you a view from a technical perspective to my side.

My bicycle friends are waiting for an interface between some cycling sites and our together used “Our training diary”.

Regardless of this, I will analyse “AngleSharp/AngleSharp” to find an alternative of my dream to realize an interface.

Many thanks for your understanding and help.




Von: Nikolay Borisenko ***@***.***>
Gesendet: Freitag, 25. Oktober 2024 18:34
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; Mention ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)


Your code is right, but an environment, where your is executing, is not "friendly" with Selenium. I suppose your Web App is ran under IIS with special permissions which prevents SM to determine User's cache folder (most likely because of there is no user account, probably some service account).

Main question: "did it work before with some previous version of Selenium?".

BTW: I see your task is just getting web page source and that's it? In this case I recommend using other tools, which don't require real browser. Like https://github.com/AngleSharp/AngleSharp. Selenium is more about automating real browser as real user is interacting with it, in your case it may be overhead.

**Comment by nvborisenko** [comment]
You should determine directory path where your app is able to write to. As soon as you get it, then you can use:

```csharp
Environment.SetEnvironmentVariable("SE_CACHE_PATH", "/path/to/the/folder");
```

**Comment by bicycleali** [comment]
Unfortunately it doesn’t work. Did I make any mistake? Sorry for that.

In the attached file you can see the details I did:

First I created via ftp (filezilla)  a cache dictionary on the server

Second I set the environment variable

   'SET Environment Variable "SE_CACHE_PATH", "~/.cache/SE-Cache"
        Environment.SetEnvironmentVariable("SE_CACHE_PATH", "~/.cache/SE-Cache")


It still works in the development environment but unfortunately not on the iis server


Von: Nikolay Borisenko ***@***.***>
Gesendet: Freitag, 25. Oktober 2024 21:15
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; Mention ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)




You should determine directory path where your app is able to write to. As soon as you get it, then you can use:

Environment.SetEnvironmentVariable("SE_CACHE_PATH", "/path/to/the/folder");

**Comment by nvborisenko** [comment]
Then seems IIS is special case. Can you please try the following: https://learn.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/environmentvariables/

**Comment by nvborisenko** [comment]
And also seems SM doesn't have proper permissions to write to "~/.cache/SE-Cache"

**Comment by bicycleali** [comment]
No chance for me to get it done. Tried it and  run into problems.

For me it is not clear why there is a difference between development and productive environment. In both scenarios IIS is working, or?

Does it mean Selenium Manager isn’t working on productive IIS Web Apps? Could it make sense to use another browser instead of chrome?

I am so short of the goal – what can I do more?


[Ein Bild, das Text, Screenshot, Schrift, Zahl enthält.  Automatisch generierte Beschreibung]


Von: Nikolay Borisenko ***@***.***>
Gesendet: Samstag, 26. Oktober 2024 22:10
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; Mention ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)


Then seems IIS is special case. Can you please try the following: https://learn.microsoft.com/en-us/iis/configuration/system.applicationhost/applicationpools/add/environmentvariables/

**Comment by nvborisenko** [comment]
In your dev env you have permissions to write files to SM cache directory. Obviously in your domain provider you are denied to do it.

I propose doble check it again and find out the directory where you are allowed to write to. In Web App area usually it is `Data` directory.

**Comment by bicycleali** [comment]
How can I find out in which directory the SM is writing the reeded page? Do I got it right the reeded Page is written in the cache?

***@***.***

Von: Nikolay Borisenko ***@***.***>
Gesendet: Samstag, 26. Oktober 2024 23:23
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; Mention ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)


In your dev env you have permissions to write files to SM cache directory. Obviously in your domain provider you are denied to do it.

I propose doble check it again and find out the directory where you are allowed to write to. In Web App area usually it is Data directory.

**Comment by bicycleali** [comment]
Hi, I still need your help. In the meantime, i have analyzed lots of thinks. I am using  'Forms Authenticacation' with Membership in my website. Normally everything works fine. Only selenium together with chrome doesn't work after publishing on the iisserver.
As already mentioned, in the development environment it works verry well. 
In the attached file I have described my settings on the website. 

On the iis webserver who is hosting the published website., I have the possibility to use a software to analyze terrorlists.
They are attached in the zipfile. Unfortunately it doesn't help me to find a solution. Maybe you can have alook to it.

Could you recommend to me another forum where I can post my issue to get maybe help too?
Thanks again for your help.
[2024_11_28_Selenium Manager process exited abnormally with 65 code.pdf](https://github.com/user-attachments/files/17961973/2024_11_28_Selenium.Manager.process.exited.abnormally.with.65.code.pdf)

[failed-requests.zip](https://github.com/user-attachments/files/17961958/failed-requests.zip)

**Comment by bicycleali** [comment]
Hi, I still need your help. In the meantime, i have analyzed lots of thinks. I am using  'Forms Authenticacation' with Membership in my website. Normally everything works fine. Only selenium together with chrome doesn't work after publishing on the iisserver.
As already mentioned, in the development environment it works verry well. 
In the attached file I have described my settings on the website. 

On the iis webserver who is hosting the published website., I have the possibility to use a software to analyze terrorlists.
They are attached in the zipfile. Unfortunately it doesn't help me to find a solution. Maybe you can have alook to it.

Could you recommend to me another forum where I can post my issue to get mybe help too?

[2024_11_28_Selenium Manager process exited abnormally with 65 code.pdf](https://github.com/user-attachments/files/17961973/2024_11_28_Selenium.Manager.process.exited.abnormally.with.65.code.pdf)

[failed-requests.zip](https://github.com/user-attachments/files/17961958/failed-requests.zip)

**Comment by leemul** [comment]
If this helps, I had the same issue, and found the clue in this thread. If your hosting this in IIS, then there's no user profile loaded, and therefore no env vars for the user. In IIS, open the apppool thats running your site, > advanced settings > Load User Profile: True, and a quick IISReset did the job for me,

**Comment by bicycleali** [comment]
Many thanks for your advice. I forwarded it directly to my service provider and will keep you informed.



Von: leemul ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 09:47
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; State change ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)


If this helps, I had the same issue, and found the clue in this thread. If your hosting this in IIS, then there's no user profile loaded, and therefore no env vars for the user. In IIS, open the apppool thats running your site, > advanced settings > Load User Profile: True, and a quick IISReset did the job for me,

**Comment by bicycleali** [comment]
slowly the squirrel feeds itself, a German proverb

I hope you can help me again – I published the whole website again with visual studio and tried to use the new functionality, again I am running into new problem. Below you can see the error message:

Attached you con find the error message of the aborted request.

Kind regards
bicycleali
***@***.***

Von: Alois Weber
Gesendet: Mittwoch, 4. Dezember 2024 10:50
An: SeleniumHQ/selenium ***@***.***>
Betreff: AW: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)

Many thanks for your advice. I forwarded it directly to my service provider and will keep you informed.



Von: leemul ***@***.******@***.***>>
Gesendet: Mittwoch, 4. Dezember 2024 09:47
An: SeleniumHQ/selenium ***@***.******@***.***>>
Cc: bicycleali ***@***.******@***.***>>; State change ***@***.******@***.***>>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: Selenium Manager process exited abnormally with 65 code - it is only the case after publishing my website to the domain (Issue #14644)


If this helps, I had the same issue, and found the clue in this thread. If your hosting this in IIS, then there's no user profile loaded, and therefore no env vars for the user. In IIS, open the apppool thats running your site, > advanced settings > Load User Profile: True, and a quick IISReset did the job for me,
