### ISSUE TITLE
[🐛 Bug]: After adding an extra node to the grid I am seeing 5 on the browsers instead it should be 8

### ISSUE THREAD

**Issue by abhi-iac** [SeleniumHQ/selenium#14641]
### What happened?

I have today added an extra node to the hub and on the UI I am seeing the extra node but the problem is I am not seeing 8 onto of browsers stereotype, I am seeing only 5. Attaching screenshot for reference
![image](https://github.com/user-attachments/assets/7c84f2c3-23d6-4f61-a6bf-857f90810380)

### How can we reproduce the issue?

```shell
Not sure how you can replicate the issue but if you add an extra node to hub you might see.
```

### Relevant log output

```shell
Attached screenshot for reference
```

### Operating System

Windows server 2019 Datacenter

### Selenium version

openjdk 11.0.16.1 2022-08-12 LTS

### What are the browser(s) and version(s) where you see this issue?

Chrome 130.0.1

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 129.6668.89

### Are you using Selenium Grid?

Selenium grid 4..24.0

**Comment by VietND96** [comment]
What is TOML config that you provided to Node

**Comment by VietND96** [comment]
Also, by default, `--override-max-sessions` is `false`. Without enabling it, max sessions will not take effect. And max sessions will be detected based on number of processors by default. Read this https://www.selenium.dev/documentation/grid/configuration/cli_options/#node

**Comment by abhi-iac** [comment]
Yes, just realized that max-session in the TOML to 5, it suppose to be 8. Thanks for your reply :)
