### ISSUE TITLE
IE driver server 64 bit is typing very slowly using Sendkeys

### ISSUE THREAD

**Issue by rameshnss** [SeleniumHQ/selenium#1464]
Win 7 using IEdriverserver 64 bit vesrion exe.

IE driver server 64 bit is typing very slowly using Sendkeys. Protected Mode is ON for all zones and zoom level set to 100%

Is below statement true?
The driver supports running 32-bit and 64-bit versions of the browser. The choice of how to determine which "bit-ness" to use in launching the browser depends on which version of the IEDriverServer.exe is launched. If the 32-bit version of IEDriverServer.exe is launched, the 32-bit version of IE will be launched. Similarly, if the 64-bit version of IEDriverServer.exe is launched, the 64-bit version of IE will be launched.
***Copied from "https://code.google.com/p/selenium/wiki/InternetExplorerDriver"

**Comment by ajayk** [comment]
@rameshnss  please see http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html is explained here  , please close the issue 

@lukeis i am back !!

**Comment by lukeis** [comment]
@ajayk welcome back! :)

Closing issue as explained in Jim's blog

**Comment by rameshnss** [comment]
@lukeis @ajayk  So there is no solution yet for 64 bit IE 10 or greater versions.

**Comment by jimevans** [comment]
You've entirely missed the point of the provided link. There is no such thing as "64-bit IE 10 or later." Even on 64-bit Windows, the process that renders content inside the tab in IE 10 and 11 is still a 32-bit process, and thus requires the 32-bit driver to drive it.

**Comment by rameshnss** [comment]
@jimevans  Thanks for the response. Got it now
