### ISSUE TITLE
[Java][Client]Driver command "[Get]/status" required session id

### ISSUE THREAD

**Issue by Evit15** [SeleniumHQ/selenium#1465]
Step to reproduce:
1. Start WebDriver server.
2. Execute command "[Get]/status" => throw exception "Session id not found".

I see this command in this document which doesn't require Session id ("https://github.com/seleniumhq/selenium/wiki/jsonwireprotocol")

Please help me to check this issue

**Comment by lukeis** [comment]
if you're started a selenium-standalone-server, the context set (beginning url) is /wd/hub. You should be attempting to GET at  http://<host>:<port>/wd/hub/status

please follow up with questions like this on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by Evit15** [comment]
Thank for your reply! But i start Microsoft Edge Driver server, don't use  "/wd/hub"

**Comment by jimevans** [comment]
Then the issue is with the driver provided and maintained by Microsoft. You'll need to take the issue up with them.

**Comment by Evit15** [comment]
My problem is i cannot send this command to Server because Java Client throw exception to require Session Id for this command. It isn't bug of server because this command didn't send to server.

I read code of Java Client, i see in "HttpCommandExecutor" class, we ignore session id for 2 command "GET_ALL_SESSIONS" and "NEW_SESSION". I read document about "status" command, i see i doesn't require session id, i think we should ignore session id for "status" command.

Please help me to review this issue.

Thanks.

**Comment by Evit15** [comment]
hi all,

Can you update this issue?

Thanks.
