### ISSUE TITLE
Python bindings for Firefox should correct permissions for copied profile dir

### ISSUE THREAD

**Issue by datakurre** [SeleniumHQ/selenium#1466]
I'm using Selenium Python bindings with RobotFramework Selenium2Libary, which provides its own  Firefox profile directory skeleton. If I have Selenium2Library installed as a read only package, a read only profile directory from Selenium2Library gets copied and later a permission exception is raised when Selenium bindings try to add additional user.js into that directory:

```
IOError: [Errno 13] Permission denied: '/var/folders/b1/mld_r9wj1jbfwf2jcfl_d61sc6kdnb/T/tmpBjsYCj/webdriver-py-profilecopy/user.js'
```

To fix the issue, I have needed to make the copy of profile dir writable after copy:

```
--- a/py/selenium/webdriver/firefox/firefox_profile.py  2016-01-13 11:32:42.000000000 +0200
+++ b/py/selenium/webdriver/firefox/firefox_profile.py  2016-01-13 11:32:12.000000000 +0200
@@ -76,6 +76,7 @@
             shutil.copytree(self.profile_dir, newprof,
                             ignore=shutil.ignore_patterns("parent.lock", "lock", ".parentlock"))
             self.profile_dir = newprof
+            os.chmod(self.profile_dir, 0755)
             self._read_existing_userjs(os.path.join(self.profile_dir, "user.js"))
         self.extensionsDir = os.path.join(self.profile_dir, "extensions")
         self.userPrefs = os.path.join(self.profile_dir, "user.js")
```

**Comment by joshbruning** [comment]
We observe this issue at Google as well, and so have not yet accepted:
https://github.com/SeleniumHQ/selenium/commit/7c97c37525d561e2963e86265c1b664456c0c86e

**Comment by joshbruning** [comment]
For what it's worth, the suggested fix did not fix the problem for us, but:

...
self.userPrefs = os.path.join(self.profile_dir, "user.js")
os.chmod(self.userPrefs, 0755)
...

does.

**Comment by datakurre** [comment]
@barancev Thank you once more for fixing this. Only now tested the latest versions on the environment with this issue and everything run as expected.

**Comment by lmtierney** [comment]
@datakurre  thanks for the update!
