### ISSUE TITLE
[🐛 Bug]: Install Selenium-Webdriver with clickonce (Framework 4.8.1)

### ISSUE THREAD

**Issue by Martin63500** [SeleniumHQ/selenium#14693]
### What happened?

Hallo,
i have the following message in my error-log:
Unable to locate or obtain Selenium Manager binary at R:\SETUP\FIMAN.net48\Application Files\FIMAN_Professional_24_10_30_2126\selenium-manager\windows\selenium-manager.exe
WebDriver
I create a windowsform-software withe .net framework 4.8.1

When I package the software via ClickOnce, the directory “selenium-manager\*” is not integrated.
How can I integrate this into Visual Studio 2022?
Info: Selenium Webdriver is integrated in a subproject. Runs perfectly on the development computer, but not directly from the ClickOnce directory.
How do I integrate the missing files?

Selenium is installed with Nuget, Update from 30.10.2024: Version 4.26

### How can we reproduce the issue?

```shell
visual studio 2022
publish
application files
-> there are no files for selenim-manager, only webdriver.dll
```

### Relevant log output

```shell
30.10.2024;23:45;Privat;2024;ERROR;ScrapingSBrokerDe:SBrokerDe_Liste_laden
Me:Unable to locate or obtain Selenium Manager binary at R:\SETUP\FIMAN.net48\Application Files\FIMAN_Professional_24_10_30_2126\selenium-manager\windows\selenium-manager.exe
So:WebDriver
ST   bei OpenQA.Selenium.SeleniumManager.<>c.<.cctor>b__5_0()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   bei OpenQA.Selenium.DriverFinder.BinaryPaths()
   bei OpenQA.Selenium.DriverFinder.GetDriverPath()
   bei OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   bei OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   bei FIMAN.FIMANSelenium.INetReadFile(String LStr_Link, Int32 LInt_WarteDauerSekunden, Boolean LBoo_UserAgent, Int32 LInt_ExtraWait)
   bei FIMAN.ScrapingSBrokerDe.Liste_laden(String LStr_Link, FIMANMandant LMandant)
30.10.2024 23:45;Privat;2024;ERROR;Unable to locate or obtain Selenium Manager binary at R:\SETUP\FIMAN.net48\Application Files\FIMAN_Professional_24_10_30_2126\selenium-manager\windows\selenium-manager.exe
Unable to locate or obtain Selenium Manager binary at R:\SETUP\FIMAN.net48\Application Files\FIMAN_Professional_24_10_30_2126\selenium-manager\windows\selenium-manager.exe
WebDriver
   bei OpenQA.Selenium.SeleniumManager.<>c.<.cctor>b__5_0()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei OpenQA.Selenium.SeleniumManager.BinaryPaths(String arguments)
   bei OpenQA.Selenium.DriverFinder.BinaryPaths()
   bei OpenQA.Selenium.DriverFinder.GetDriverPath()
   bei OpenQA.Selenium.Chromium.ChromiumDriver.GenerateDriverServiceCommandExecutor(DriverService service, DriverOptions options, TimeSpan commandTimeout)
   bei OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   bei FIMAN.FIMANSelenium.INetReadFile(String LStr_Link, Int32 LInt_WarteDauerSekunden, Boolean LBoo_UserAgent, Int32 LInt_ExtraWait)
   bei FIMAN.ScrapingSBrokerDe.Liste_laden(String LStr_Link, FIMANMandant LMandant)
   bei FIMAN.Internet_Kurs_Modul.KursDownload_SBrokerDe(FIMANProtokoll Protokoll, ImportFenster LInt_ImportFenster, Boolean LBoo_Protokoll_sichern, Boolean LBoo_Kurse_ueberschreiben, ListView LvGitter_ImportListe, Boolean LBoo_UebernahmeInStammdaten, SQLDatenbank LSQLServer, String LStr_Pfad_Zwischenablage, Boolean LBoo_EOD, FIMANMandant LMandant)
;KursDownload_SBrokerDe1
```

### Operating System

Windows11/WindowServer 20222

### Selenium version

4.26

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Version 130.0.6723.70 (Offizieller Build) (64-Bit)

### Are you using Selenium Grid?

only webdriver

**Comment by nvborisenko** [comment]
@Martin63500 did it work for you with some previous selenium version? Or this is the first your experience to use selenium in ClickOnce?

**Comment by Martin63500** [comment]
in the previos version 4.25, i had other problems. That was the reason for update to 4.26.
When i copy the files from folder "selenium-manager" to the target-folder, i can use webdriver.
But: at the next update of my own software, the copied files are deleted and i must copy again.
It is possible, to integrate to visual studio-click-once-system?

**Comment by nvborisenko** [comment]
I hope it would be useful: https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-specify-which-files-are-published-by-clickonce?view=vs-2022

**Comment by Martin63500** [comment]
i can add the files with your instruction, but the file for selenium-manager is in ...\bin\x86\Release\selenium-manager\windows
and not in ...\selenium-manager\windows
I have the following error:
Unable to locate or obtain Selenium Manager binary at R:\SETUP\FIMAN.net48\Application Files\FIMAN_Professional_24_10_30_2126\selenium-manager\windows\selenium-manager.exe
WebDriver

**Comment by Martin63500** [comment]
![grafik](https://github.com/user-attachments/assets/9e8d1ccd-c3b9-4090-992e-3858375c4762)

the selenium-manager is only autmatic intragrate in \bin\... (debug and release), it is not in the correct folder of the solution and then, in can not intagrate it correctly with clickonce

**Comment by nvborisenko** [comment]
I created win forms app, published via ClickOnce, installed, executed. Works fine.

This is default publish profile:

![image](https://github.com/user-attachments/assets/f56f79f1-38dd-492e-a724-41176a0306f6)

**Comment by Martin63500** [comment]
it is framework 4.8.1, not 6 or 8

**Comment by nvborisenko** [comment]
Then please share simple project how to reproduce this issue, my IDE doesn't know what is net481.

**Comment by Martin63500** [comment]
[SeleniumTest_Setup.zip](https://github.com/user-attachments/files/17651956/SeleniumTest_Setup.zip)

here is a test-solution:
SeleniumTest_Code.zip: Code in C#, .net Framework 4.8.1
SeleniumTest_Setup.zip: Setup with ClickOnce

**Comment by nvborisenko** [comment]
@Martin63500 seems you missed attachment for source code.

**Comment by Martin63500** [comment]
I've just realised. The C# code is over 75 MB in size. That is not possible here, max. 25 MB. How else can I transfer it?

**Comment by nvborisenko** [comment]
Remove `bin` and `obj` folders, it is unnecessary.

**Comment by Martin63500** [comment]
[SeleniumTest_Code.zip](https://github.com/user-attachments/files/17652600/SeleniumTest_Code.zip)
ok, it is packed:
1. with 7z
2. renamed in *.zip. Change the filename to *.7z

**Comment by nvborisenko** [comment]
OK, the issue is related to transitive dependencies by your current set of tools. Below is my current understanding of the issue, I might be wrong and sorry.

The project A uses "old" packages reference style, when packages are managed in `packages.config` file. This style is kind of obsolete, and it is recommended to upgrade it: https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference. I guess NuGet tool doesn't honor transitive content items, so upgrading the project will help you (I verified).

If you are not able to migrate the project by some reasons, then the easiest workaround can be just installing `Selenium.WebDriver` package directly into your Project B.

**Comment by Martin63500** [comment]
ok, your first ideas, to change the pachaging, was not successfully.
The second idea, to integrate selenium.driver to add in the first-project, it is successfully:
![grafik](https://github.com/user-attachments/assets/4115fd04-046c-4f38-91f5-e72794b175bd)

It seems to be working

**Comment by Martin63500** [comment]
the setup with click-once:
![grafik](https://github.com/user-attachments/assets/2253f02e-6577-4e3b-9f20-16a0db9f80f8)

**Comment by nvborisenko** [comment]
Glad to hear!
