### ISSUE TITLE
[🐛 Bug]: Unable to obtain Chrome driver using Selenium Manager

### ISSUE THREAD

**Issue by RamnathRangaswamy** [SeleniumHQ/selenium#14704]
### What happened?

This is the python code -
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
driver =webdriver.Chrome(service=service, options=options)
driver.quit()

This is the error message
raise SeleniumManagerException(f"{path} is missing.  Please open an issue on {tracker}")
selenium.common.exceptions.SeleniumManagerException: Message: C:\Users\310080332\Anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe is missing.

### How can we reproduce the issue?

```shell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
service = Service()
options = webdriver.ChromeOptions()
driver =webdriver.Chrome(service=service, options=options)
driver.quit()
```

### Relevant log output

```shell
Unable to obtain driver using Selenium Manager: C:\Users\310080332\Anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues
```

### Operating System

Windows10

### Selenium version

Selenium 4.9.0 pyhd8ed1ab_0 conda-forge

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

I am unable to download the Chrome driver

### Are you using Selenium Grid?

No

**Comment by Balaji028** [comment]
Hi @RamnathRangaswamy,I have tried this in the latest version , but not getting any error ,Can you try to upgrade to latest version and try once ,or you can try installing minimum version of 4.12 since stable version of selenium manager got shipped.

**Comment by RamnathRangaswamy** [comment]
Hello Balaji
Thank you for your support. Let me try and get back.
Regards,
Ramnath

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 3 Nov 2024 at 19:29, Balaji ***@***.***> wrote:   


Hi @RamnathRangaswamy,I have tried this in the latest version , but not getting any error ,Can you try to upgrade to latest version and try once ,or you can try installing minimum version of 4.12 since stable version of selenium manager got shipped.

**Comment by diemol** [comment]
When you grab Selenium from a different package manager, Selenium Manager is omitted. You need to configure the driver on your own. 

https://www.selenium.dev/documentation/selenium_manager/#custom-package-managers
