### ISSUE TITLE
Selenium 2.48.0 and 2.49.0 with FireFox failing

### ISSUE THREAD

**Issue by jerry57** [SeleniumHQ/selenium#1472]
For our testing we have been using RobotFramework-selenium2library
we were on selenium 2.47.3 and FireFox 42.0 with all working normally
FireFox released 43.0 so we upgraded our selenium to 2.48.0 to work with it and started noticing failures in our tests.
Today I worked with different combinations and narrowed it down to anything newer than Selenium 2.47.3 and FireFox 42.0

Here is our testcases showing the problems:

Open Applications Window
    [Documentation]    This test suite opens the Applications window.
    [Tags]    GUI    smoke
    Comment    Logging into the DE
    DE GUI Login
    Comment    Opening the Apps window.
    DE GUI Open Apps Window
    Page Should Contain Element    //div[text() = 'Apps']

Open CACE
    [Documentation]    This test case opens CACE.
    [Tags]    GUI    smoke
    Comment    Variables to run my key words.
    Set Suite Variable    ${Analysis}    CACE
    Set Suite Variable    ${Category}    Comparative Methods
    Comment    Open CACE.
    DE GUI Select Analysis    ${Analysis}    ${Category}
    Wait Until Page Contains Element    xpath=//div[text()='Analysis Name:CACE_analysis1']    ${GUIWaitShort}

The first testcase passes without issue, but on the newer FF and Selenium, the second testcase always fails right at the DE GUI Select Analysis keyword.

Here is the contents of that keyword:
DE GUI Select Analysis
    [Arguments]    ${Analysis}    ${Category}
    [Documentation]    Combines steps for selecting an analysis by first clicking the Public Apps category, then selecting the subcategory specified in the test case, and then selecting the application specified in the test case.
    ...
    ...    Allows the user to select an analysis without having to go through all the little CSS annoyances.
    Comment    Wait for the category to appear.
    Wait Until Page Contains Element    xpath=//span[contains(text(), "${Category}")]    ${GUIWaitShort}
    Click Element    xpath=//span[contains(text(), "${Category}")]
    Wait Until Page Contains Element    xpath=//span[text()="${Analysis}"]    ${GUIWaitShort}
    Comment    Select the App row.
    Click Element    xpath=//span[text()="${Analysis}"]/../../../td[3]
    Comment    Open the Apps window Apps dropdown (to expose the Use App button).
    Click Element    //div[@id='gwt-debug-appsWindow.appsView.menuBar.apps']/div/table/tbody/tr[2]/td[2]/div/div/table/tbody/tr/td/div
    Wait Until Page Contains Element    //div[@id='gwt-debug-appsWindow.appsView.menuBar.apps.useApp']/span    ${GUIWaitShort}
    Comment    Click the Use App button.    This has proven more stable than clicking the link text to open the app.
    Click Element    //div[@id='gwt-debug-appsWindow.appsView.menuBar.apps.useApp']/span
    Wait Until Page Contains Element    xpath=//div[text()="Launch Analysis"]    ${GUIWaitShort}
    Comment    Close the Apps window.
    Click Element    css=div[id="gwt-debug-appsWindow.close"]
    Page Should Not Contain Element    xpath=//div[@id='gwt-debug-desktop.deTaskBar']/div/div/div/table/tbody/tr/td/div/div/table/tbody/tr/td/div[text()="Apps"]

Unfortunately we do not use Selenium directly.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.

**Comment by jerry57** [comment]
Sorry I can't leave you a more explicit example than above.  As stated, I am a Robotframework & Selenium2Library user NOT a direct selenium/selenium2 user.  I guess the problem is solely ours then.
