### ISSUE TITLE
can't access dead object / Current window or frame is closed

### ISSUE THREAD

**Issue by Andy7777** [SeleniumHQ/selenium#1475]
Hi Selenium :)

First I'd like to say what a great bit of software Selenium IDE is!! It can do a lot more than people realize!

I am having an issue which seems to have got a bit worse recently. I have searched for a solution but have had no luck fixing it. I don't think this is a new problem but I either need someone to point me in the right direction or perhaps this is a bug.

Some of my test cases are failing with one of the following errors:

[error] isNewPageLoaded found an old pageLoadError: TypeError: can't access dead object
[warn] Stack is: BrowserBot.prototype._handleClosedSubFrame@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1251:1 
BrowserBot.prototype.getCurrentWindow@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1229:18 
BrowserBot.prototype.pollForLoad@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:961:38 
BrowserBot.prototype.reschedulePoller/pollerFunction@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1099:9 
BrowserBot.prototype.runScheduledPollers@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1109:9 
TestLoop.prototype.resume@chrome://selenium-ide/content/selenium-core/scripts/selenium-executionloop.js:77:13 
fnBind/retval@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:60:12
[error] can't access dead object

OR

[error] isNewPageLoaded found an old pageLoadError: Error: Current window or frame is closed!
[warn] Stack is: SeleniumError@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:778:17 
BrowserBot.prototype._handleClosedSubFrame@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1266:27 
BrowserBot.prototype.getCurrentWindow@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1229:18 
BrowserBot.prototype.pollForLoad@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:961:38 
BrowserBot.prototype.reschedulePoller/pollerFunction@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1099:9 
BrowserBot.prototype.runScheduledPollers@chrome://selenium-ide/content/selenium-core/scripts/selenium-browserbot.js:1109:9 
TestLoop.prototype.resume@chrome://selenium-ide/content/selenium-core/scripts/selenium-executionloop.js:77:13 
fnBind/retval@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:60:12
[error] Current window or frame is closed!

Please could you help me out.

Thanks 

Andy Wilder

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Andy7777** [comment]
Unfortunately I can't give you the test case. However I think I may have discovered the problem.

It appears to be around a clickAndwait that happens just after the test case fails with one of the error messages. Changing it to a click followed by a pause seems to clear the issue. The only issue with doing this is it seems the error comes back later in the test case and the only way to get rid of it is to change a lot of clickAndwait to click and pause. It's like I have to chase it to the end of the test case and then it will run without falling over. 

This isn't the first time I have encountered a problem with the clickAndwait command. It seems in certain instances it can't be used because of how it's interacting with a web site. It seems as it will execute the click but then is waiting for something to happen and it never does.

While I'm here and in the interest of being helpful there is also a small problem with setting break points. If the test case is running quickly it can sometimes not see these break points and skips over them. Other than that, Selenium is a great bit of kit.

Thanks :)

**Comment by barancev** [comment]
Sorry, we hardly can do anything about the issue without a reproduction case :(
