### ISSUE TITLE
[🐛 Bug]: Some Feature file skipped(in between) during parallel execution

### ISSUE THREAD

**Issue by mmuthum** [SeleniumHQ/selenium#14753]
### What happened?

When I run regression with more that 12 threads one or two feature file got skipped in between(Like if it has 20 scenarios, till 5 executed but 6th didn't complete). 

As per my analysis Basically Test started in a feature is not completed of no where feature file is skipped. And no tests from that file is not displaying in the serenity report as well

But When I run my regression test with 5 threads no issues all feature files are running properly

### How can we reproduce the issue?

```shell
Not able to share due to compliance
```

### Relevant log output

```shell
Not able to share due to compliance
As per my analysis Basically Test started is not completed of no where feature file is skipped
```

### Operating System

Ubuntu

### Selenium version

4.8.3

### What are the browser(s) and version(s) where you see this issue?

Chrome 121

### What are the browser driver(s) and version(s) where you see this issue?

Remotedriver

### Are you using Selenium Grid?

4.25.0

**Comment by diemol** [comment]
If you cannot share, then please join the community channels where you can ask and get help diagnosing your issue.
