### ISSUE TITLE
[🐛 Bug]: Some tests in py/test/selenium/webdriver using 'dead battery' library imghdr

### ISSUE THREAD

**Issue by tijuca** [SeleniumHQ/selenium#14765]
### What happened?

Not a really bug report, just to mentioning an potential upcoming incompatibility.

The Debian Python Team discovered that several upstream project tarballs, which are used as base for building Debian packages, still use some modules that are not being available in Python 3.13+ anymore.

The tests
https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/selenium/webdriver/common/takes_screenshots_tests.py#L19
https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/selenium/webdriver/firefox/ff_takes_full_page_screenshots_tests.py#L19
https://github.com/SeleniumHQ/selenium/blob/trunk/py/test/selenium/webdriver/remote/remote_connection_tests.py#L18

using the imghdr module, that will be a so called dead battery starting with Python 3.13. https://peps.python.org/pep-0594/#deprecated-modules

The tests will need some rework to be functional with 3.13+

The related bug report in Debian is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1084692

### How can we reproduce the issue?

```shell
n.a.
```

### Relevant log output

```shell
n.a.
```

### Operating System

Debian 13 Trixie

### Selenium version

Python 4.24.4

### What are the browser(s) and version(s) where you see this issue?

n.a.

### What are the browser driver(s) and version(s) where you see this issue?

n.a.

**Comment by navin772** [comment]
Thanks @tijuca for reporting this, I will discuss with the TLC on what new dependency to use and open a PR for the same.

Possible alternatives:
- `python-magic` - it has an external dep - `libmagic`
- `filetype` - lightweight, deps free
- `puremagic` 
- `Pillow` - large and overkill for the use-case

Personally, I think `filetype` is great for the current use-case.
