### ISSUE TITLE
[🚀 Feature]: Expose Chromium commands API in Remote

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/selenium#14799]
### Feature and motivation

Currently there is a number of custom methods that expose Chromium commands in Chromium driver:

```python
from selenium.webdriver import Chrome

driver = Chrome()
driver.execute_cdp_cmd('Page.enable')                                     # <-- custom method that calls command below
driver.execute("executeCdpCommand", {"cmd": "Page.enable', "params": {}}) # <-- custom command execution
```

The same commands should be accessible via Remote driver as well since Grid provides the endpoints and the underlying command executor actually already supports the commands:

```python
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import Remote

driver = Remote(options=Options())
driver.execute_cdp_cmd('Page.enable')                                     # <-- this method is not available
driver.execute("executeCdpCommand", {"cmd": "Page.enable', "params": {}}) # <-- this still works!
```

The same approach is implemented in other bindings (Java, Ruby), where instances of Remote driver are augmented to support custom methods and commands specific to browsers.

### Usage example

See above for usage example.

**Comment by Delta456** [comment]
I will try to work on this.

**Comment by dkjha52** [comment]
Yes. Its working fine. However it gives the below warning message - 
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732776810.702445 5115107 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.

**Comment by Delta456** [comment]
This issue can be closed now.
