### ISSUE TITLE
FindElement(By.ClassName("X Y Z")  Doesn't work...

### ISSUE THREAD

**Issue by AcousticGuitar** [SeleniumHQ/selenium#1480]
**Problem**
Elements with multiple classes are not found using By.ClassName as shown in title.

**Solution**
Add iterator to that function that will allow multiple classnames separated by spaces to be used.

**Comment by lukeis** [comment]
the solution is to use a CssSelector:  By.cssSelector(".X.Y.Z")

**Comment by AcousticGuitar** [comment]
That's not a solution, it's a circumvention.....

**Comment by ddavison** [comment]
`By.ClassName` is singular.  it only expects one class.  A better solution if you wanted to implement this @AcousticGuitar is to put in a method called `By.ClassNames`

**Comment by AcousticGuitar** [comment]
I can do this in C# by writing an Extension method easily enough, by why not have the function in the base?  Doesn't make sense in today's many faceted ClassName world....

**Comment by lukeis** [comment]
the W3C spec for WebDriver does not include finding by Class Name. The language bindings delegate to a css selector anyways:

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L479

**Comment by ddavison** [comment]
because that's not what the definition of `By.ClassName` is.  even grammatically.  Classes are inherently plural.  `class="a b c"` has three classes attached.  `By.ClassName("a b")` wouldn't make sense because there are two classes we are trying to match.

again, if you wanted something like this, feel free to make a pull request to add `By.ClassNames` so we could have a thorough discussion within the team

**Comment by lukeis** [comment]
c# has it to:
https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L606-L609

**Comment by AcousticGuitar** [comment]
Solution is not dependent on W3C spec for webdriver as it's obviously outdated.  In C# the solution is simple...

**Comment by AcousticGuitar** [comment]
**C# solution?**
***Wouldn't this do it?***

        `public List<IWebElement> FindElementsByClassName(string className)
        {
            // Element finding mechanism is not allowed by the W3C WebDriver
            // specification, but rather should be implemented as a function
            // of other finder mechanisms as documented in the spec.
            // Implementation after spec reaches recommendation should be as
            // follows:
            // return this.FindElement("css selector", "." + className);
            if (this.IsSpecificationCompliant)
            {
                return this.FindElements("css selector", "." + EscapeCssSelector(className));

            }

            return this.FindElements("class name", className);
        }`

**Comment by engrasma1991** [comment]
"Find Element by class is not working"

public void pricing() throws Exception{

//**Add Pricing Plan**

driver.findElement(By.className("addbutton tooltips")).click();
}
