### ISSUE TITLE
[🐛 Bug]: `element.get_dom_attribute("checked")` for a checked checkbox element is not returning True

### ISSUE THREAD

**Issue by mdmintz** [SeleniumHQ/selenium#14800]
### What happened?

`element.get_dom_attribute("checked")` for a checked checkbox element is not returning True

In `4.27.0`, `element.get_attribute()` was deprecated in favor of `element.get_dom_attribute()`. However, the new method does not get the correct results, as in the following example where I was determining whether or not a checkbox was checked:

```python
(Pdb+) element.tag_name
'input'
(Pdb+) attribute
'checked'
(Pdb+) element.get_attribute(attribute)
'true'
(Pdb+) element.get_dom_attribute(attribute)
(Pdb+) element.get_dom_attribute(attribute)
(Pdb+)
```

### How can we reproduce the issue?

```shell
Call `element.get_dom_attribute(attribute)` for an `input` element of `type="checkbox"`, where the checkbox is checked.

There's no output.

The deprecated method, `element.get_attribute(attribute)`, correctly returns `true`.
```

### Relevant log output

```shell
(Pdb+) element.tag_name
'input'
(Pdb+) attribute
'checked'
(Pdb+) element.get_attribute(attribute)
'true'
(Pdb+) element.get_dom_attribute(attribute)
(Pdb+) element.get_dom_attribute(attribute)
(Pdb+)
```

### Operating System

Any

### Selenium version

Python - 4.27.0

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

Latest

### Are you using Selenium Grid?

No

**Comment by mdmintz** [comment]
<img width="638" alt="Screenshot 2024-11-25 at 1 58 26 PM" src="https://github.com/user-attachments/assets/63dfffdb-b63b-4559-846b-86e60b0718bf">

**Comment by AutomatedTester** [comment]
Can I see the exact HTML for this? What happens when you do this in other browsers?

**Comment by joerg1985** [comment]
To read the checked state `getDomProperty` should be used. Some words on why i think this depreation is something good:
- the implementation did not return false in case the element was not checkable at all, so you might check the wrong element and do not realize it
- on page javascript could lead to incorrect results, in case someone did set a property named like the attribute
- the behavoiur was inconsistent, e.g. reading the `src` of an img returned null if not defined, `lowsrc` did return an empty string
- the implementation did things not documented, e.g. for the spellcheck attribute and ignored the element does support spellcheck at all
-  the javascript is multiple kb big, so people complained about the slowness

and these are only the points i can recall, without even beeing in the discussion at the tlc meeting.

**Comment by AutomatedTester** [comment]
What @jimevans  said is oversimplified (his words). Most of the times attributes and properties are mirrored so won't matter.

**Comment by mdmintz** [comment]
It's still being used in Selenium `4.27.0`:

https://github.com/SeleniumHQ/selenium/blob/b50158997e81d57ee6a8dfd7af767ce499c58b3f/py/selenium/webdriver/support/select.py#L97

https://github.com/SeleniumHQ/selenium/blob/b50158997e81d57ee6a8dfd7af767ce499c58b3f/py/selenium/webdriver/support/select.py#L185

``Select(element).select_by_index(option)``

``
...python3.13/site-packages/selenium/webdriver/support/select.py:97: DeprecationWarning: using WebElement.get_attribute() has been deprecated. Please use get_dom_attribute() instead.
    if opt.get_attribute("index") == match:
``

----

So either the deprecation must be removed, or all instances of `get_attribute()` in Selenium must be replaced.

**Comment by mdmintz** [comment]
Lots of places where `get_attribute()` can still be found being used in `selenium` `4.27.0`:
https://github.com/search?q=repo%3ASeleniumHQ%2Fselenium%20get_attribute&type=code

Perhaps removing the deprecation is the best option for the time being.

**Comment by Delta456** [comment]
We can also update the instances of `get_attribute()` in Selenium as the release is already done.

**Comment by diemol** [comment]
We are going to revert this. Thanks, @VietND96, for creating the PR.

For 4.28, we will put back the deprecation code AND replace all the usages of `get_attribute()` to avoid the warnings.

**Comment by diemol** [comment]
https://pypi.org/project/selenium/4.27.1/

**Comment by diemol** [comment]
Thank you, @VietND96!
