### ISSUE TITLE
[🚀 Feature]: Better compatibility with Appium #2

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#14811]
### Feature and motivation

This is the addition to https://github.com/SeleniumHQ/selenium/issues/13949, whose implementation allowed us to get rid of reflection usage in multiple places.

### Usage example

Increase the scope of private properties of the below classes to `protected`:

HttpCommandExecutor -> additionalCommands

**Comment by Delta456** [comment]
I will work on this.
