### ISSUE TITLE
[dotnet] [🚀 Feature]: Consider using the new `Base64Url`

### ISSUE THREAD

**Issue by RenderMichael** [SeleniumHQ/selenium#14813]
### Feature and motivation

With the recent release of .NET 9, the `Base64Url` type was released. This type fills a common need that .NET developers have, and up until recently, has been implemented, re-implemented, and polyfilled in many projects.

Selenium .NET has its own implementation: found here:
https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Internal/Base64UrlEncoder.cs

As the links in that file show, this was ripped from the Azure Active Directory implementation. They recently migrated to using the `Base64Url` type as well: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2817/

Luckily for us, the .NET team released the `Base64Url` type as a .NET Standard 2.0 NuGet package, found here: https://www.nuget.org/packages/Base64Url

We can take this dependency unconditionally for now, and if/when we support a .NET 9+ TFM, we can conditionally remove the dependency there.

### Usage example

The polyfill type `Base64UrlEncoder` is `public` (should it be `internal`?). Anyone currently relying on it should not be affected though.

As noted in the linked PR on Azure AD, there are minor differences in behavior between the `Base64Url` type and the `Base64UrlEncoder` type. For Azure AD, it seems like that requires them to keep the type around.

For us, we should investigate what exactly those differences are and if it would be acceptable to just use `Base64Url` directly.

**Comment by nvborisenko** [comment]
No dependencies please for simple tasks! I stole this code in part of the https://github.com/SeleniumHQ/selenium/pull/12777. Thanks for highlighting that it is shipped in .net 9. It is not yet clear, what we will do with it. At this moment, maximum what I can propose: just mention that it is available in .net 9 in source code near with link, and... that's it.

**Comment by nvborisenko** [comment]
It should be `internal`, I already tried it, but there is technical limitation: https://github.com/SeleniumHQ/selenium/pull/13331. The worst feeling is that I am closing this issue because of it's partially resolved - we cannot fix it because of bazel. It is as is. Thanks for understanding.

**Comment by RenderMichael** [comment]
Can we add the `[EditorBrowsable(EditorBrowsableState.Never)]` attribute to these types, so they don’t pop up in people’s IDEs even if they are publicly accessible?

**Comment by nvborisenko** [comment]
It is more workaround rather than a proper solution, internal classes should be `internal`. It is pity that we cannot do it.

**Comment by RenderMichael** [comment]
I opened #14833 to make these types invisible to IDEs.

Alternatively, we can add `<Compile Include="Path/To/Base64UrlEncoder.cs" />` in the test projects. I have never used this advanced feature, but it's a way to specify arbitrary files in the build. I think we only need to add it to the Common project?

If that's preferable, I can start experimenting.

**Comment by nvborisenko** [comment]
It should be `internal`.
