### ISSUE TITLE
[🐛 Bug]: After downloading the source code, unable to extract it from Zip folder.

### ISSUE THREAD

**Issue by SREEPADHAGK** [SeleniumHQ/selenium#14815]
### What happened?

After downloading the source code, unable to extract it from Zip folder.

### How can we reproduce the issue?

```shell
After downloading the source code, unable to extract it from Zip folder.
```

### Relevant log output

```shell
After downloading the source code, unable to extract it from Zip folder.
```

### Operating System

All platforms

### Selenium version

All the browsers

### What are the browser(s) and version(s) where you see this issue?

All the browsers

### What are the browser driver(s) and version(s) where you see this issue?

All the browsers

### Are you using Selenium Grid?

All versions

**Comment by VietND96** [comment]
Do you mean the source is downloaded from this GitHub repository?
I guess due to the way that you extracted it. At least you have to mention the command used and error logs

**Comment by SREEPADHAGK** [comment]
> Do you mean the source is downloaded from this GitHub repository? I guess due to the way that you extracted it. At least you have to mention the command used and error logs

Unable to extract the source code after I downloaded it to my local drive.  Attached the error message
<img width="434" alt="image" src="https://github.com/user-attachments/assets/120757b3-9e4a-4a90-a3e3-13ed5f0702f0">

**Comment by VietND96** [comment]
Can you share the link to source that you downloaded?

**Comment by VietND96** [comment]
Are you download from here? https://pypi.org/project/selenium/#files
If yes, try to use another tool e.g `7zip` to extract it, instead of the default of Windows.
