### ISSUE TITLE
Test with SVG Elements on IE 11 are slow

### ISSUE THREAD

**Issue by dbenoit** [SeleniumHQ/selenium#1481]
Python selenium version 2.49, IE11 Windows 10. webdriver IE 32 bit or 64 bit.

My test with SVG elements on IE 11 are running very slowly. The same test on Chrome and Firefox runs as expected. Completing in 60 seconds. On IE11 runs successfully but the execution time is 10 minutes!

Selenium launches the app fairly quickly and then proceeds to test. Elements are located quickly until it gets to the SVG component in the application; using the action chain methods it moves quickly to the first g element and then slows to a crawl to the others.

I have tried both 32 and 64bit versions of IE webdriver. Version 2.48
This is a locally run script.( Not remote. I have no results for that test.)

Expected: to execute as successfully in IE 11 as it does on chrome or firefox. Find and assert the SVG g elements.

Actual: Find and assert the SVG g elements but is painfully slow. May as well be done manually.

Any ideas?

**Comment by GajendraKSahu** [comment]
Any updates on this issue?

**Comment by barancev** [comment]
Sorry it was not properly addressed on time, but we need a [concise reproducible test case](http://sscce.org/) for this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided. Feel free to reopen it if you have one.
