### ISSUE TITLE
[🐛 Bug]: can you pls remove my issues here

### ISSUE THREAD

**Issue by black-bitter** [SeleniumHQ/selenium#14824]
### What happened?

i put credential regarding my company policies on this issue
https://github.com/SeleniumHQ/selenium/issues/11795

can you help me to remove or edit the sensitive information on that thread above?

### How can we reproduce the issue?

```shell
if you want to keep the issues, please remove the specific information
```

### Relevant log output

```shell
if you want to keep the issues, please remove the specific information
```

### Operating System

windows 10

### Selenium version

Java 17

### What are the browser(s) and version(s) where you see this issue?

Chrome 110

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver

**Comment by diemol** [comment]
I've deleted the issue for you. However, the content might be present in mailboxes owned by watchers of this repository.

**Comment by black-bitter** [comment]
thanks for your help! @diemol it's okay as long as not appear on public..
