### ISSUE TITLE
[🐛 Bug]: Unable to perform actions like doubleClick(), moveTo(), closeWindow() through webdriver io

### ISSUE THREAD

**Issue by Bjb20** [SeleniumHQ/selenium#14827]
### What happened?

Hi, i am running webdriver io typescript test automation scripts in remote browser session hosted in selenium grid version 4.25.0. Here i am getting errors in calling some inbuild webdriverio actions like doubleClick(), moveTo(), closeWindow(). It was working fine till grid version 4.23. Now its giving error as unknown and in the debugger logs its giving error in the releaseActions() as request failed due to missing body. But in local browser its working fine.

### How can we reproduce the issue?

```shell
Eg of code is await element.doubleClick() or await element.moveTo()
```

### Relevant log output

```shell
INFO webdriver: COMMAND performActions (<object>)
INFO webdriver: [POST] https://selenium-hub:4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
INFO webdriver: DATA {
actions: [
{
id: 'action',
type: 'pointer',
parameters: [object],
actions: [Array]
}
]
}
1
INFO webdriver: RESULT null
INFO webdriver: COMMAND releaseActions()
INFO webdriver: [DELETE] https://selenium-
hub: 4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
DEBUG webdriver: request failed due to missing body
INFO webdriver: Retrying 1/1
INFO webdriver: [DELETE] https://selenium-
hub: 4444/selenium/session/b15ae585ffa48420978647e279eb8b8c/actions
WARN webdriver: Request failed with status 404 due to unknown error
DEBUG webdriver: request failed due to missing body
ERROR webdriver: Request failed with status 404 due to Not Found: unknown еггог
```

### Operating System

Linux

### Selenium version

4.25.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 130

### What are the browser driver(s) and version(s) where you see this issue?

Chrome 130.0.6723.69

### Are you using Selenium Grid?

Yes, 4.25.0

**Comment by diemol** [comment]
I believe you are using an old version of WebdriverIO. Please report it to their project or check their docs for upgrade paths.
