### ISSUE TITLE
Selenium IDE 2.9.1 is getting disabled in Firefox 43.0.4

### ISSUE THREAD

**Issue by machtyn** [SeleniumHQ/selenium#1483]
I have read other comments which state "Reinstall the latest version from AMO". I followed the link, installed the latest version, restarted Firefox, then after some amount of time, I get the yellow bar which states, "One or more installed add-ons cannot be verified and have been disabled." And I see that Selenium has been disabled, again.

![2016-01-15 23_25_17-add-ons manager](https://cloud.githubusercontent.com/assets/16729235/12370448/532a163a-bbdf-11e5-9278-e86bb8a0fd9d.png)

System settings:
Windows 7 and then again in Windows 10 after uprade, both 64 bit and fully updated.
Firefox 43.0.1 - 43.0.4
Selenium IDE 2.9.1

**Comment by samitbadle** [comment]
Getting Selenium IDE signed easily on AMO is a massive effort and I am working on it as my first priority. From the next version onwards, there will be two releases, one unsigned and one released for signing. However, it may take a long time for AMO to sign. In the meanwhile, you can use Firefox 42 for testing purposes. On Windows, portable Firefox allows multiple versions to be installed easily. Another option will be to try the developer edition of Firefox.

Cheers,
Samit

**Comment by barancev** [comment]
https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/
2.9.1.1-signed
