### ISSUE TITLE
Mobile application testing automation.

### ISSUE THREAD

**Issue by Panda-Srujan** [SeleniumHQ/selenium#1484]
Hello everyone,

Could someone suggest me the best way to deal with the automation of mobile applications using Selenium.

Thanks in advance.

**Comment by Vanilton18** [comment]
Hello,

I suggest you work with Appium, it is integrated with Selenium and uses the same syntax.

Check in http://appium.io/

Regards

**Comment by Panda-Srujan** [comment]
Hello Vanilton,

Thanks for the information. I'll go through the documentation.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
