### ISSUE TITLE
[dotnet] Future-proof for NUnit 4.x upgrade

### ISSUE THREAD

**Issue by RenderMichael** [SeleniumHQ/selenium#14852]
### Feature and motivation

With the release of NUnit 4.x, a few major breaking changes have been added. We want our test suite to be able to be prepared for NUnit 4, even if we're not going to upgrade for a while yet.

- [x] **Classic Assert** #14853 #14870
 The "classic assert" model has been depreciated. In order to continue using them, the tests would need to jump through some hoops.

  A better solution would be to migrate to modern NUnit assertions. The `NUnit.Analyzers` nuget package has useful features to accomplish this. Examples include:
  - `Assert.AreEqual("Testing Alerts", driver.Title)` -> `Assert.That(driver.Title, Is.EqualTo("Testing Alerts"))`
  - `Assert.AreEqual(1, allWindows.Count)` -> `Assert.That(allWindows, Has.One.Items)`

- [x] String format messages #14878
  NUnit 3.x has methods such as `Assert.That(x, Is.EqualTo(y), "Value {0} is {1}", x, y)`. These overloads have been removed, in order to make room for caller argument expression parameters. We will have to go through and turn these all into interpolated strings. Same For `Assert.Ignore(string message, string[] args)`.

- [x] The handful of uses of `StringAssert` or `CollectionAssert` should be changed to `Assert.That`. #14870

**Comment by nvborisenko** [comment]
Thanks, it is good initiative.

PS: I edited the goal to be achievable.

**Comment by nvborisenko** [comment]
@RenderMichael  Will it make sense to create one big PR? I will approve changes like `Assert.Equal(...)` -> `Assert.That(...)`.

**Comment by RenderMichael** [comment]
@nvborisenko I can make a massive PR, if that's preferable. I'll start adding more changes to #14853

**Comment by nvborisenko** [comment]
If we can agree some rules before big boom. I expect **ONLY** `Assert.That(...)`, no more new constructions (like Assert.Multiple).

**Comment by RenderMichael** [comment]
The PR which migrates us to `Assert.That` is ready.

However, there are a few other things which block NUnit 4.x besides that. For example, the `(..., string message, params string[] args)` has been removed. I will have to go over a few other things after the big PR lands. Can this issue be renamed to something like "prepare for NUnit 4"?
