### ISSUE TITLE
[🐛 Bug]: Running automation testing with Chrome and Selenium causing unusual increase in network traffic

### ISSUE THREAD

**Issue by dhtt663** [SeleniumHQ/selenium#14855]
### What happened?

**Steps to reproduce the problem**

1. Set up the automation test project with the following:

- Selenium version 4.8.1

- Java version 17

- Chrome version 130.0.6723.116

- Run tests in parallel using 4 threads

- About 750 scenarios (around 30,000 steps)

2. Integrate the project with Jenkins using this setup:

- Jenkins version 2.462.3

3. After the tests finish running on Jenkins, check how much server bandwidth was used
**Problem Description**
We have Chrome (version 130.0.6723.116) and Jenkins (version 2.462.3) installed on our server running CloudLinux v8.10.0 STANDARD for running automation testing with Selenium. Daily network traffic is around 55GB to 70GB per day (we monitor using vnstat tool on Linux). But when we ran automation testing from Jenkins with Chrome it caused an increase in the total network traffic to over 150GB per day. More details from vnstat as below:

 ```
      day        rx      |     tx      |    total    |   avg. rate     
 ------------------------+-------------+-------------+---------------     
 2024-12-01   122.80 GiB |    2.25 GiB |  125.06 GiB |   12.43 Mbit/s     
 2024-12-02   148.36 GiB |    2.90 GiB |  151.25 GiB |   15.04 Mbit/s     
 2024-12-03    80.06 GiB |    1.93 GiB |   81.99 GiB |    8.15 Mbit/s     
 2024-12-04    79.93 GiB |    1.90 GiB |   81.83 GiB |    8.14 Mbit/s     
 ------------------------+-------------+-------------+---------------      
 sum of 4    431.15 GiB  |    8.98 GiB |  440.13 GiB |

```
The first two lines are the network traffic we running automation testing and the last two are when not running.

However, the issue does not happen on the previous Chrome version. For example, Chrome version 130.0.6723.116
 which we are using for current automation testing.

**Summary**
Running automation testing with Chrome and Selenium causing unusual increase in network traffic

**Additional Data**
Category: Network / Downloading
Chrome Channel: Stable
Regression: N/A

### How can we reproduce the issue?

```shell
We have 2 console log runs with 2 versions of Chrome: 130.0.6723.116 and 127.0.6533.119.
https://github.com/dhtt663/Selenium-with-Chrome-version.git
```

### Relevant log output

```shell
1. The console log output when run with Chrome version: 130.0.6723.116
2. The network traffic when run with Chrome version: 130.0.6723.116
3. The console log output when run with Chrome version: 127.0.6533.119
4. The network traffic when run with Chrome version: 127.0.6533.119 
Please refer to the following to view the log details:
https://github.com/dhtt663/Selenium-with-Chrome-version.git
```

### Operating System

CloudLinux v8.10.0 STANDARD

### Selenium version

selenium-java version: 4.8.1

### What are the browser(s) and version(s) where you see this issue?

Chrome version: 130.0.6723.116

### What are the browser driver(s) and version(s) where you see this issue?

Chromedriver 130.0.6723.116

**Comment by VietND96** [comment]
Did you try to disable this feature in Chrome? https://www.selenium.dev/blog/2024/chrome-browser-woes/

**Comment by pujagani** [comment]
Can you please confirm if this occurs with the latest version of Selenium? We only triage the latest versions since we don't do patch releases for older versions. Thank you!
