### ISSUE TITLE
[🐛 Bug]: [Win32Exception (0x80004005): Die angegebene ausführbare Datei ist keine gültige Anwendung für diese Betriebssystemplattform.] The specified executable file is not a valid application for this operating system platform.]

### ISSUE THREAD

**Issue by bicycleali** [SeleniumHQ/selenium#14867]
### What happened?

I am working with visual studio 2019. In the development area the new feature of my website works verry well.
After publishing to the domain, I am getting now the error message:

[Win32Exception (0x80004005): Die angegebene ausführbare Datei ist keine gültige Anwendung für diese Betriebssystemplattform.] The specified executable file is not a valid application for this operating system platform.]
<failedRequest url="https://unsertrainingstagebuch.de:443/Fahrrad/01_Fahrten/EF_INSERT_SIGMA_URL.aspx"
               siteId="466"
               appPoolId="unsertrainingstagebuch.de(domain)(4.0)(pool)"
               processId="59356"
               verb="POST"
               remoteUserName="Brägel"
               userName="Brägel"
               tokenUserName="V24478\IWPD_523(s818317)"
               authenticationType="Forms"
               activityId="{800017BB-000A-8D00-B63F-84710C7967BB}"
               failureReason="STATUS_CODE"
               **_statusCode="500"_**
               triggerStatusCode="500"
               timeTaken="1625"
               xmlns:freb="http://schemas.microsoft.com/win/2006/06/iis/freb"
               >
So far, I tried to find a solution or a workaround of my problem, without success. I asked again my service profider but without success.
Therefore, I would be happy to get help again from your side.

### How can we reproduce the issue?

```shell
You can ease reproduce the issue

https://unsertrainingstagebuch.de/login.aspx?ReturnUrl=%2fFahrrad%2f01_Fahrten%2fEF_INSERT_SIGMA_URL.aspx

Please open the requested site with Userid: Brägel Passwort: brägel

If you are logged in please copy the following URL into the text box and klick the yellow button.
Maybe you must klick twice to start the functionality which runs into the error issue.

https://sigma-sharing.com/view/activity/71978657907f61796c8f68087c51a13d0d1bc3b3
```

### Relevant log output

```shell
Host: unsertrainingstagebuch.de

Referer: https://unsertrainingstagebuch.de/Fahrrad/01_Fahrten/EF_INSERT_SIGMA_URL.aspx

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"

sec-ch-ua-mobile: ?0

sec-ch-ua-platform: "Windows"

Origin: https://unsertrainingstagebuch.de
```

### Operating System

IIS 

### Selenium version

Selenium.WebDriver 4.25.0

### What are the browser(s) and version(s) where you see this issue?

Selenium.WebDriver.Chrome 130.0.6723.6900

### What are the browser driver(s) and version(s) where you see this issue?

Google Chrome Version 130.0.6723.70 (Offizieller Build) (64-Bit)

### Are you using Selenium Grid?

I don't know

**Comment by bicycleali** [comment]
Many thanks for looking after my issue.

Attached you can find more details to make you able to reproduce my problem and hopefully to find a solution for my problem.

Many thanks again.


Von: github-actions[bot] ***@***.***>
Gesendet: Donnerstag, 12. Dezember 2024 06:58
An: SeleniumHQ/selenium ***@***.***>
Cc: bicycleali ***@***.***>; Mention ***@***.***>
Betreff: Re: [SeleniumHQ/selenium] [🐛 Bug]: [Win32Exception (0x80004005): Die angegebene ausführbare Datei ist keine gültige Anwendung für diese Betriebssystemplattform.] The specified executable file is not a valid application for this operating system platfo...


Hi, @bicycleali<https://github.com/bicycleali>.
Please follow the issue template, we need more information to reproduce the issue.

Either a complete code snippet and URL/HTML (if more than one file is needed, provide a GitHub repo and instructions to run the code), the specific versions used, or a more detailed description to help us understand the issue.

Note: If you cannot share your code and URL/HTML, any complete code snippet and URL/HTML that reproduces the issue is good enough.

Reply to this issue when all information is provided, thank you.

**Comment by diemol** [comment]
We don't see anything attached. We prefer if you copy & paste the code here as a comment or provide a GitHub repository with the code to reproduce the issue.

**Comment by bicycleali** [comment]
Sorry, but here again my comments and the files I announced already.

Principal considerations

We use Selenium with the HTMLAgilityPack to read dynamically built website

the Chrome browser is not installed on the web server where the application is published

It should be worked with a 32bit chromedriver.exe, which is available on the web server

ideally, this should be possible in the development environment as well as in the production environment, if the Chrome driver is not suitable for this, another driver can also be used,
I'm grateful for any suggestion that works in both environments
[2024_12_12_Selenium_HTMLAgilityPack_Setup.pdf](https://github.com/user-attachments/files/18111115/2024_12_12_Selenium_HTMLAgilityPack_Setup.pdf)
[EF_INSERT_SIGMA_URL.aspx.pdf](https://github.com/user-attachments/files/18111284/EF_INSERT_SIGMA_URL.aspx.pdf)
[EF_INSERT_SIGMA_URL.aspx.vb.pdf](https://github.com/user-attachments/files/18111285/EF_INSERT_SIGMA_URL.aspx.vb.pdf)

**Comment by bicycleali** [comment]
It was a mistake by me to close it; hopefully, you have all the needed information in the shared files please let me know if I can do more.

**Comment by diemol** [comment]
We need a way to reproduce the issue. Please provide the code we can use to do so.

**Comment by diemol** [comment]
By the code, I meant the Selenium code you are using and bumping into the issue.

**Comment by bicycleali** [comment]
Attaced you can find the used code, wich works on the development environment, but not after publishing on the iis server
[2024_12-29_[Win32Exception (0x80004005).pdf](https://github.com/user-attachments/files/18271078/2024_12-29_.Win32Exception.0x80004005.pdf)

Also attached a view which packages I have installed in my project
[2024_12_29 Installed packages.pdf](https://github.com/user-attachments/files/18271083/2024_12_29.Installed.packages.pdf)

You can also use the functionality on my website: 
https://unsertrainingstagebuch.de/Fahrrad/01_Fahrten/EF_INSERT_SIGMA_URL.aspx
User is Brägel PW is brägel

https://sigma-sharing.com/view/activity/debaac6c19595da842ea5dbdc99eccfc54fdf0dc

Please input above url into the textbox.

I hope with the information of me you can work now. Please let me know if I can do more for you.

**Comment by diemol** [comment]
I am sorry but we are not going to build a project from the PDFs you are attaching, either provide a GitHub repository or paste the formatted code as comments.

**Comment by bicycleali** [comment]
Thankyou for your help, as I earlier mentioned I am a hobby programmer, but i did what you suggested

https://github.com/bicycleali/20_10_UTTB
In the folder Fahrrad/01_Fahrten you can find the used EF_INSERT_SIGMA_URL.aspx files

Please let me know again if I can do more to support you

**Comment by diemol** [comment]
This is what I get when I click on your link

![image](https://github.com/user-attachments/assets/4848f964-faa1-42b2-9ef4-d553c673d4ed)

**Comment by bicycleali** [comment]
https://github.com/bicycleali/20_10_UTTB

Doi habe to make it pubic?
I See the whole project.

**Comment by diemol** [comment]
Yes, otherwise we cannot see it.

**Comment by bicycleali** [comment]
I made it pubic now

**Comment by diemol** [comment]
You can make it private again.

OK, so you are sharing the whole app. I had to read the whole thread again to see the phrase that indicates you want to run this in an IIS server. You probably run into issues because when a browser opens, it needs to have a Window Manager to open, and I guess IIS is a headless process. My suggestions are:
- Try to run the browser headless
- Or check these links https://www.michael-whelan.net/testing-mvc-application-with-iis-express-webdriver/ - https://stackoverflow.com/questions/11654038/can-we-run-selenium-webdriver-test-case-with-iis-instead-of-visual-studio-devel.

This is not an issue in Selenium per se, but rather an environment configuration issue or just how you want to solve your challenge. If you need more help, feel free to join the community chat (links below).
