### ISSUE TITLE
Unable to select ajax element in Selenium.

### ISSUE THREAD

**Issue by Panda-Srujan** [SeleniumHQ/selenium#1488]
Hi everyone,

I'm new to Selenium testing automation tool. I'm facing issue while selecting element in dropdown list which is automatically generated (<i>Ajax dropdownlist</i>) on entering some keywords and trying to select a list item in google search.

I'm facing an error that says, "unable to find the element". Please suggest me a way to sort this out.

Thanks in advance.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by Panda-Srujan** [comment]
Thanks Barancev for your response.
