### ISSUE TITLE
[🚀 Feature]: Do not enable CDP for Firefox

### ISSUE THREAD

**Issue by thc202** [SeleniumHQ/selenium#14885]
### Feature and motivation

Selenium now (4.27+) warns when Firefox CDP is enabled:
https://github.com/SeleniumHQ/selenium/blob/19fc2179855d0f70b7241a6c4cfbd9152e023609/java/src/org/openqa/selenium/firefox/FirefoxDriver.java#L168-L172

but at the same time it is enabling it:
https://github.com/SeleniumHQ/selenium/blob/9d6824578d8f814c7528bcab0a765fae1923328b/java/src/org/openqa/selenium/firefox/FirefoxOptions.java#L66-L69

requiring the user to set the Firefox preference to just enable BiDi and suppress the deprecation warning.

Since CDP is deprecated I think Selenium should stop enabling that protocol and remove the preference.

**Comment by diemol** [comment]
Our policy is to add the deprecation and then wait for two releases to remove the feature. This should be removed around February. However, some coordination is needed with the Firefox team because they are also removing CDP from Firefox.

As it is, there is nothing to do for the team for now.

**Comment by thc202** [comment]
It would have been better that the deprecation warn was only enabled if the user was actually using CDP rather than warn all users even the ones that are not using CDP at all (as is the case now since BiDi is what's being used internally), but fair if it's the policy.

**Comment by diemol** [comment]
That is a good point. We should improve that for the next time.
