### ISSUE TITLE
.clear();  on <input type="number"> does not work if the value is invalid

### ISSUE THREAD

**Issue by mittt** [SeleniumHQ/selenium#1489]
.clear();  on <input type="number"> does not work if the value is invalid. 

In FF you can enter any text in this input. In Chrome you can enter something like this "eee123ee".

Maybe the problem comes from the fack that .value on such field returns empty string - ''.

I think you should check if the field is valid, or just clear it everytime:
if ((element.validity) && (!element.validity.valid)){ ...
[more info on validity](http://stackoverflow.com/questions/18852244/how-to-get-the-raw-value-an-input-type-number-field)

**Comment by barancev** [comment]
Please upgrade Selenium to 2.49
