### ISSUE TITLE
[🐛 Bug]: NoSuchDriverException in selenium 4 (raspberry pi)

### ISSUE THREAD

**Issue by javixeneize** [SeleniumHQ/selenium#14909]
### What happened?

I am using selenium in a raspberry pi 4, and, while using with selenium 3.8.0, it works, but, if i upgrade to selenium 4, (4.26.1), i have a NoSuchDriverException as it cant find the driver

### How can we reproduce the issue?

```shell
just start the webdriver for chrome in a raspberry pi 4 using selenium 4
```

### Relevant log output

```shell
File "/home/javi/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

### Operating System

Raspberry PI OS

### Selenium version

python 4.26.1

### What are the browser(s) and version(s) where you see this issue?

chromium latest

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver latest

**Comment by diemol** [comment]
The latest version of Selenium uses [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/), but we do not support it on Rasperri Pi, therefore you need to download the browser driver and configure it on your own.

**Comment by javixeneize** [comment]
Hi. I have the driver @diemol, as it works with selenium 3, but with selenium 4, the same driver does not work, selenium cant find it in the default path, so it is not a matter of using the selenium manager or not

Can you please advise?

Thanks

**Comment by diemol** [comment]
From the link:

>If you are running Linux on arm64/aarch64, 32-bit architecture, or a Raspberry Pi, Selenium Manager will not work for you. The biggest issue for people is that they used to get custom-built drivers and put them on PATH and have them work. Now that Selenium Manager is responsible for locating drivers on PATH, this approach no longer works, and users need to use a Service class and [set the location directly](https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location). There are a number of advantages to having Selenium Manager look for drivers on PATH instead of managing that logic in each of the bindings, so that’s currently a trade-off we are comfortable with.

Is this something you have already tried?

**Comment by javixeneize** [comment]
Yes, thats exactly what i. am doing, both with the system chromedriver location, and with the version downloaded with webdriver manager - https://pypi.org/project/webdriver-manager/#use-with-chrome

**Comment by diemol** [comment]
webdriver manager is not controlled by us, so I am not sure what is being done there.

If you are doing that, can you share the code you are using for your ServiceClass?

**Comment by javixeneize** [comment]
Thats the one in the example

```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.os_manager import ChromeType

driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))

```

**Comment by diemol** [comment]
That is slightly different. Your code is using webdriver manager, a 3rd party project we do not control and I am not sure what it is doing internally. 

The docs recommend to set it directly https://www.selenium.dev/documentation/webdriver/drivers/service/#driver-location

If you still want to use that 3rd party tool, then you need to check with the authors.

**Comment by javixeneize** [comment]
I tried as well using the selenium service itself

  service = webdriver.ChromeService(executable_path='/usr/bin/chromedriver') and have the same error

**Comment by diemol** [comment]
Can you share the whole code, please?

**Comment by javixeneize** [comment]
not much more code, just starting the webdriver makes it crash

`
from selenium import webdriver


if __name__ == '__main__':

    service = webdriver.ChromeService(executable_path='/usr/bin/chromedriver')
`

**Comment by diemol** [comment]
That code is creating the service, but it is not using it anywhere. 

In theory you pass the service when creating the ChromeDriver instance.

**Comment by javixeneize** [comment]
Well, yes the rest of the code would be

```
driver = webdriver.Chrome(service=service)
driver.get('https://www.google.com')
```

it fails when initialising the driver

**Comment by diemol** [comment]
Why don't you post the complete code? You are sharing information bit by bit. This is taking longer than it should. Please join our Slack channel and others can help as well. See link below.

**Comment by javixeneize** [comment]
Thats the whole code, there is nothing else there

```
from selenium import webdriver

if name == 'main':

  service = webdriver.ChromeService(executable_path='/usr/bin/chromedriver')
  driver = webdriver.Chrome(service=service)
  driver.get('https://www.google.com')

```

Can you replicate that from your end?
