### ISSUE TITLE
[C#]Cant't get wrappedDriver from an element using PageFactory

### ISSUE THREAD

**Issue by BartWojtala** [SeleniumHQ/selenium#1490]
When elements are located using PageFactory there seems to be an issue with casting element to IWrapsDriver, although it works pretty good with elements found by FindElement(s).

In my case I'm trying to get wrappedDriver inside following extension method <br> `public static bool SelectDropdownOptionByText(this IWebElement element, string optionText)`.

Here to be more specific:
`        private static IWebDriver GetDriverFromElement(IWebElement element)
        {
            return ((IWrapsDriver)element).WrappedDriver;
        }`

Error says: 
> Additional information: Unable to cast transparent proxy to type 'OpenQA.Selenium.Internal.IWrapsDriver'.

BTW:Is this NOT implemented or as designed?

**Comment by jimevans** [comment]
The proxy object created by the .NET `PageFactory` implementation does not proxy the `IWrapsDriver` interface. It's unclear how that interface would be useful from a page object, which should have a reference to the driver anyway.

**Comment by robertfaheymoonpig** [comment]
It's useful for IWebElement extension methods

E.g.

public static IWebElement WaitForElement(this IWebElement element)
        {
            var driver = ((IWrapsDriver)element).WrappedDriver;

            new WebDriverWait(driver, TimeSpan.FromSeconds(60)).Until((d) => element.Displayed);

            return element;
        }

**Comment by DalSoft** [comment]
I'm having this exact problem I wrote a element extension that needs to use the the driver. This extension method fails only when I call it on an element that is populated using the PageFactory. Now I have to take the driver as a extra param in the extension method which makes my API harder to read and use.

**Comment by dpupek** [comment]
IMO, The driver should be exposed somehow.

**Comment by tajyoder** [comment]
Agreed. I'm encountering the same issue cited by @DalSoft  and @robertfaheymoonpig - I'd like to add some IWebElement extension methods, but their usefulness is limited due to the fact that they can't be called on elements generated by PageFactory.

**Comment by jimevans** [comment]
One should expect that the .NET `PageFactory` implementation will be marked deprecated at some point in the future, and eventually be moved to a companion project, one not produced or maintained by the Selenium project. At that point (or now, if anyone is so inclined), a search for a new maintainer of the .NET `PageFactory` will be open. The .NET `PageFactory` was intended as sample code of something one might want to build on one's own, and may not be suitable for production use to meet every developer's needs.
