### ISSUE TITLE
[🚀 Feature]: we are facing issues regarding memory usage when running selenium testcases on chrome and as 4.2Gb memory is utilized the chrome driver shuts off and we see NoSessionException

### ISSUE THREAD

**Issue by Amanyadav12345** [SeleniumHQ/selenium#14911]
### Feature and motivation

we might need a flag so that we can reduce the memory issue of chrome maybe GC calls at random Chrome

### Usage example

![image](https://github.com/user-attachments/assets/7022e786-0395-4560-a27a-2cb95011eb4a)
![image](https://github.com/user-attachments/assets/99dbfb88-58b3-4692-ac4e-86c59d5e13f9)
continuous increase in memory usage which will lead to failed testcases

**Comment by diemol** [comment]
That is something that only Chrome can control. Not the Selenium code.

**Comment by Amanyadav12345** [comment]
As per [comment #1](https://issues.chromium.org/issues/384844008#comment1), the issue is related to Selenium Java, which is out of scope for TE to triage. Hence, adding the TE-NeedsTriageHelp label and requesting assistance from the Dev team for further inputs on this issue.

this is the comment I received from google issue services
https://issues.chromium.org/issues/384844008

**Comment by diemol** [comment]
You do need to provide them with much more information. Screenshots are not enough. They get many reports per day, so if you want them to pay attention to it, you need to provide code to reproduce the issue and more detailed information.
