### ISSUE TITLE
[🐛 Bug]: serverErrorPolicy does retry on `Exception` / `Error`

### ISSUE THREAD

**Issue by joerg1985** [SeleniumHQ/selenium#14917]
### What happened?

The `serverErrorPolicy` inside the `org.openqa.selenium.remote.http.RetryRequest` does not only handle the server errors.
It basically handles all `Exception`s / `Error`s, i guess this is due tue a missunderstanding of the API of the library used here.
This increases the retries on `ConnectException` to 5, instead of only 3.

In general i think the use of this library is problematic, due to:
- A miss match between the naming of method / things inside the javadoc and what is actually happening (this is also the reason for this issue...).
   e.g. `ExecutionAttemptedEvent.getLastException` does return a `Throwable`, so we have a potential class cast exception in https://github.com/SeleniumHQ/selenium/blob/825b0406e0842992e4dd37c06b2dc9bafa27a37c/java/src/org/openqa/selenium/remote/http/RetryRequest.java#L87
   e.g. the javadoc of `RetryPolicy.handleIf` speaks about "exception" but meant is "throwable"
- It implies handling failues is super easy, just put it inside a retry and don't think about it.
  This will probably lead to leaks, e.g. leaking `sub` in case `pub` failes in https://github.com/SeleniumHQ/selenium/blob/825b0406e0842992e4dd37c06b2dc9bafa27a37c/java/src/org/openqa/selenium/events/zeromq/UnboundZmqEventBus.java#L134-L145
- I have debugged into to the code and it makes things complex compared to a simple loop. And complexity does bring bugs with it e.g. before PR #12838 the responses of concurrent failed request could get mixed.
- No response to most issues raised in the issue tracker, including one related to selenium https://github.com/failsafe-lib/failsafe/issues/386

So i would like to ask: Glue some patches on the code and hope the code does what it should or remove the library with a custom implementation aka. a simple loop?

### How can we reproduce the issue?

```shell
Run `RetryRequestTest.canThrowUnexpectedException` in debug mode to see the unexpected retries in the logs.

Or run the code below to see the 5 retries instead of 3.
HttpHandler handler =
        new RetryRequest()
            .andFinally(
                (HttpRequest request) -> {
                  throw new WebDriverException("oops", new ConnectException("Testing"));
                });
```

### Relevant log output

```shell
Dez. 19, 2024 11:50:53 AM org.openqa.selenium.remote.http.RetryRequest lambda$static$4
INFORMATION: Failure due to server error #1. Retrying.
Dez. 19, 2024 11:50:56 AM org.openqa.selenium.remote.http.RetryRequest lambda$static$4
INFORMATION: Failure due to server error #2. Retrying.
```

### Operating System

Win 10 x64

### Selenium version

4.27.0

### What are the browser(s) and version(s) where you see this issue?

N/A

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by joerg1985** [comment]
@pujagani @diemol @shs96c what do you think about this?

**Comment by diemol** [comment]
We used the library because it made sense at the moment. 

If you think a custom implementation is enough, I would be okay with that. I would not replace it all in a single PR, I would do the custom implementation, and remove the library bit by bit.

**Comment by joerg1985** [comment]
I did not wanted to judge about using it in the past, i only wanted to show my currenty view on it.

**Comment by diemol** [comment]
I did not mean it like that. We did not oversee any of the current issues.

**Comment by pujagani** [comment]
If the custom implementation can help fix it, we can go that route. If we think it leads to a higher potential of possible bugs, we can replace it with a simpler implementation too in iterations as long as we are not re-inventing the wheel. Ideally, any library we use should make our lives easier.
