### ISSUE TITLE
[🚀 Feature]: Remote WebDriver - Check if the file download has finished.

### ISSUE THREAD

**Issue by limuyuan** [SeleniumHQ/selenium#14915]
### Feature and motivation

On this page: https://www.selenium.dev/documentation/webdriver/drivers/remote_webdriver/#list-downloadable-files

It said:
List Downloadable Files
Be aware that **_Selenium is not waiting for files to finish downloading_**, so the list is an immediate snapshot of what file names are currently in the directory for the given session.

Is it possible that Selenium can natively support the function of "wait for files to finish downloading"?

I found a similar issue #10884 but it was closed.

### Usage example

I'm using the sample code here: https://github.com/SeleniumHQ/seleniumhq.github.io/blob/trunk/examples/dotnet/SeleniumDocs/Drivers/RemoteWebDriverTest.cs#L69
```csharp
WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
wait.Until(d => ((RemoteWebDriver)d).GetDownloadableFiles().Contains(downloadFileName));
```
However, the target file was generated immediately as a 0KB file, and there is another `.part` file, which is making the `wait.Until` useless.
![image](https://github.com/user-attachments/assets/3c8a8bc3-60e8-4c2c-8d27-d5e4cde6ad1e)

Is it possible to provide a feature so we can know the file was completely downloaded?

**Comment by limuyuan** [comment]
With Edge 131.0.2903.99, there is only one `Unconfirmed 645092.crdownload` tmp file.
With Chrome 131.0.6778.140, there is only one file `<filename>.crdownload` tmp file.
With Firefox 133.0.3, there is a 0KB file and another `<filename>.part` tmp file, which is causing the issue.

Maybe I can edit the wait condition to exclude the `.part` file to solve this problem...

**Comment by diemol** [comment]
We don't plan to implement that method natively because we only expose the feature, and users can do what fits them best. We recommend using a framework built on top of that feature, for example [Selenide](https://github.com/selenide/selenide/issues/2789).
