### ISSUE TITLE
[🚀 Feature]: Permission to collect data

### ISSUE THREAD

**Issue by vinefeeder** [SeleniumHQ/selenium#14932]
### Feature and motivation

As I understand European data collection rules, the General Data Protection Regulations (GDPR) make it unlawful to collect data without first securing a user's permission. Selenium opts every user in, and allows opt-out by only by editing files or setting environment variables. This approach is unlawful

### Usage example

Remove automatic data collection and provide an easy way to opt in/out

**Comment by diemol** [comment]
Please reach out to pono [at] sfconservancy.org for this matter.
