### ISSUE TITLE
[🐛 Bug]: Set default download directory doesn't work in headless mode.

### ISSUE THREAD

**Issue by zhengyuan-public** [SeleniumHQ/selenium#14939]
### What happened?

I have created a project to download all cloud videos from zoom for my company. My program only run into problem when running in headless mode: the files are downloaded into the system's default download directory (I'm using MacBook Air and the default download dir is the `Download` folder in my home folder). I set default download directory via the following code.

### How can we reproduce the issue?

```shell
def creat_options(self):
    base_options = Options()

    base_options.add_argument('--no-sandbox')
    base_options.add_argument('--disable-dev-shm-usage')
    base_options.add_argument('--disable-extensions')
    base_options.add_argument('--disable-gpu')
    base_options.add_argument('--log-level=3')  # Reduce log verbosity
    base_options.add_argument('--blink-settings=imagesEnabled=false')   # Disable Image Loading
    base_options.add_argument(
        'user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
        '(KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    )

    # Change download behavior
    download_dir = str(Path(self.args.zoom['download_dir']).absolute())
    logging.info(f"Default download directory is set to {download_dir}.")
    prefs = {
        "download.default_directory": download_dir,
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "profile.default_content_setting_values.automatic_downloads": 1
    }
    base_options.add_experimental_option("prefs", prefs)

    full_options = Options()
    full_options.arguments.extend(base_options.arguments)
    full_options.add_argument('--headless')

    return base_options, full_options
```

### Relevant log output

```shell
There is no relevent logging about this problem.
```

### Operating System

macOS 15.2 (24C101)

### Selenium version

Python 3.12.8; Selenium 4.27.1

### What are the browser(s) and version(s) where you see this issue?

ChromeDriver 131.0.6778.204

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 131.0.6778.204

### Are you using Selenium Grid?

Not using

**Comment by diemol** [comment]
Please try these other options https://www.selenium.dev/blog/2023/headless-is-going-away/

If the issue is still present, please report it to the Chrome folks.
