### ISSUE TITLE
[🐛 Bug]: Expected to read a STRING but instead hava : START_MAP last.

### ISSUE THREAD

**Issue by z654893465** [SeleniumHQ/selenium#14940]
### What happened?

json analysis

### How can we reproduce the issue?

```shell
json analysis
```

### Relevant log output

```shell
json analysis
```

### Operating System

windows11

### Selenium version

4.2.1

### What are the browser(s) and version(s) where you see this issue?

chrom 133

### What are the browser driver(s) and version(s) where you see this issue?

chromDriver 133.0.6905.0

**Comment by z654893465** [comment]
help ,  please!

**Comment by diemol** [comment]
You are using a very old version of Selenium where that error was present. Please update to the latest and if it still happens, open a new issue with all bug details.
