### ISSUE TITLE
[🐛 Bug]: selenium-manager.exe bug

### ISSUE THREAD

**Issue by dl2458697735** [SeleniumHQ/selenium#14941]
### What happened?

I have another question. When creating an instance based on the driver, this program is called. Why does it sometimes get results quickly and sometimes slowly
selenium-manager.exe --browser chrome --language-binding javascript --output json

### How can we reproduce the issue?

```shell
const {Browser, Builder, By, Key, until} = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const {getBinaryPaths} = require("selenium-webdriver/common/driverFinder");

async function getDriver(driverName = Browser.CHROME) {
    try {

        let options = new chrome.Options();
        //options.setBrowserVersion("stable");
        options.addArguments('--start-maximized');

        let paths = getBinaryPaths(options)
        console.log(paths)
        let driverPath = paths.driverPath;
        let browserPath = paths.browserPath;

        options.setChromeBinaryPath(browserPath);

        let service = new chrome.ServiceBuilder("D:/DL/dsy/dsy_client/rpa/chromedriver.exe");

        let driver = await new Builder()
            .forBrowser(driverName)
            .setChromeOptions(options)
            .setChromeService(service)
            .build();

        return driver;
    } catch (error) {
        throw error;
    }
}
```

### Relevant log output

```shell
no log
```

### Operating System

win11

### Selenium version

js

### What are the browser(s) and version(s) where you see this issue?

chrome 131

### What are the browser driver(s) and version(s) where you see this issue?

chromedriver131

### Are you using Selenium Grid?

"selenium-webdriver": "^4.27.0"

**Comment by diemol** [comment]
It depends on your network connection and the latency between your location and the endpoints being called.

**Comment by dl2458697735** [comment]
I can still return normally even when the network is turned off. I believe this is not simply a network issue. Usually, when it is re executed after a certain period of time or the next day, it will be very slow. Is this related to caching or is there any way to skip the execution of this exe and let me manually specify these addresses, because I want to ensure that it can be opened quickly every time? Here are the commands I tested
selenium-manager.exe --browser chrome --language-binding javascript --output json

**Comment by dl2458697735** [comment]
> It depends on your network connection and the latency between your location and the endpoints being called.这取决于您的网络连接以及您的位置与被调用的终端节点之间的延迟。

I can still return normally even when the network is turned off. I believe this is not simply a network issue. Usually, when it is re executed after a certain period of time or the next day, it will be very slow. Is this related to caching or is there any way to skip the execution of this exe and let me manually specify these addresses, because I want to ensure that it can be opened quickly every time? Here are the commands I tested
selenium-manager.exe --browser chrome --language-binding javascript --output json
