### ISSUE TITLE
[New Feature] Need support to automate push notifications using Selenium WebDriver

### ISSUE THREAD

**Issue by talktokets** [SeleniumHQ/selenium#1501]
Hi,

Currently Selenium does not support the push notifications which are sent to the browser. How that can be done? Is there any way to implement it? If not can we have this feature in upcoming Selenium WebDriver version?

**Comment by lukeis** [comment]
What is a push notification on a desktop browser? Sounds like you're asking something related to mobile. I suggest trying to clarify your needs on the mailing list first:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by talktokets** [comment]
Looks like you are not aware about this technology. Now a days push notifications are being delivered to desktop browsers as well. If you want to know more check this: https://pushcrew.com/

Also I am clear with my needs and on mailing list I couldn't find anything related to it.

**Comment by dandv** [comment]
@lukeis: [Push notifications have been available since Chrome 42](https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web?hl=en). Would be great for Selenium to have capabilities to test them. Any chance of reopening this issue?

**Comment by lukeis** [comment]
@dandv sounds like something that should be brought up with the W3C working group -
https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by rahuln04** [comment]
How to handle/automate web browser push notifications received using selenium ?

**Comment by akit009** [comment]
do we have any method to allow browser notification in selenium??  Please help I'm in a great need

**Comment by AnuKadloor** [comment]
@lukeis Any update on this ?

**Comment by piotr-madry** [comment]
@lukeis - this is really needed feature. Are there any plans to add it to Selenium?
