### ISSUE TITLE
Python: clean-up error in Chrome / IE "Service" in selenium 2.49

### ISSUE THREAD

**Issue by robsan00** [SeleniumHQ/selenium#1504]
In Selenium 2.49 the Service objects were refactored to use a common base class. This common base class now contains a "__del__" method (which is not a bad thing in itself). However if the driver was quit before this "__del__" fails.

Try to execute the following Python script:
```python
import os
from selenium import webdriver
from time import sleep

def spam():
    webDriver = webdriver.Chrome(chrome_options=None)
    webDriver.get("http://www.google.com")
    sleep(1)
    webDriver.quit()

os.environ['no_proxy'] = '127.0.0.1,localhost'
spam()
sleep(1)
```

With selenium 2.49 this returns an URLError in the "send_remote_shutdown_command". With 2.48 this works fine.

What is happening (if I am not completely mistaken) is that webDriver.quit() already called the "stop" method in the Service class. After the "spam" method is finished garbage collection comes into effect and the "__del__" method is called which calls this method again. Of course the port is already closed and the request fails.

**Comment by levi-rs** [comment]
I am also seeing this same error, using version 2.49.2 of the python selenium bindings, in code that had no problem previously. Here is an example script:

```
import time
from selenium import webdriver

print("Creating driver")
driver = webdriver.Chrome()

print("sleeping first time")
time.sleep(5)

print("quiting driver")
driver.quit()

print("sleeping second time")
time.sleep(5)
```

Produces this output:
```
(.venv35)➜  driver_test  python test.py
Creating driver
sleeping first time
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x108b63cf8>>
Traceback (most recent call last):
  File "/Users/levinoecker/tmp/driver_test/.venv35/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 141, in __del__
  File "/Users/levinoecker/tmp/driver_test/.venv35/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 120, in stop
  File "/Users/levinoecker/tmp/driver_test/.venv35/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 95, in send_remote_shutdown_command
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

**Comment by robsan00** [comment]
This commit does not solve my issue that if quit and then the destructor are called that you get an URLError.
From my point of view the cleanest way to solve this would be to set self.process to None at the very end of the stop method. Either that or ignoring the URLError as well.

**Comment by lukeis** [comment]
this fixed it for me with the sample code(s) provided and only presented itself to me in py 3.5

**Comment by robsan00** [comment]
I forgot to mention that I used python 2.7, sorry.

**Comment by robsan00** [comment]
I updated my original post with the output of the script.

**Comment by lukeis** [comment]
@robsan00 thanks, d57afc1 should take care of this now

**Comment by robsan00** [comment]
That works, thanks.

A short review comment: at least on Windows "self.process = None" is not reached due to an (handled) OSError in "self.process.terminate()" (I guess the shutdown request closes the process which leads to an "Access is denied" error when trying to kill the process).
