### ISSUE TITLE
[Python] WebDriverException message is not returned in Chrome after upgrade to 2.49.1

### ISSUE THREAD

**Issue by adamreyher** [SeleniumHQ/selenium#1505]
Environment: chromedriver 2.20 // Python 2.7.11 // Windows 7

Since upgrading Selenium to 2.49.1, we're seeing an issue when WebDriverExceptions (or items which inherit it) are raised, the exception message is being returned as an empty string. I'm also seeing the issue in 2.49.2

The behavior we're seeing is the response is being passed to check_response in errorhandler.py as a dictionary in Chrome, but (for example) in Firefox, it's being passed as a a string (so it hits the json parsing block). Chrome does not return a message, Firefox does.

Example to Reproduce

    driver = webdriver.Firefox()
    driver.get("http://www.python.org")
    elem = driver.find_element_by_name("NameDoesNotExist")

Exception on Firefox

    elenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: {"method":"name","selector":"NameDoesNotExist"}

Repeat code, but with Chrome: Exception on Chrome:

    selenium.common.exceptions.NoSuchElementException: Message:

**Comment by barancev** [comment]
Fixed by commit ab99cb6
