### ISSUE TITLE
getWindowHandles() returns wrong value when open link with ctrl/cmd + click

### ISSUE THREAD

**Issue by rovner** [SeleniumHQ/selenium#1508]
Environment: selenium 2.49.0, firefox/ie11 osx/linux/windows 7

test case to reproduce
```(java)
DesiredCapabilities capabilities = new DesiredCapabilities("firefox", null, ANY);
capabilities.setCapability(CapabilityType.HAS_NATIVE_EVENTS, true);
driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
driver.get("https://yandex.ru/search/?text=pain");
((JavascriptExecutor) driver).executeScript("$('.serp-list').hide()");
new Actions(driver)
//            .keyDown(Keys.CONTROL)
            .keyDown(Keys.COMMAND)
            .click(driver.findElements(By.cssSelector("div.related a")).get(0))
//            .keyUp(Keys.CONTROL)
            .keyUp(Keys.COMMAND)
            .build()
            .perform();
Thread.sleep(5000);
assertEquals(2, driver.getWindowHandles().size());
```

Expected: ```getWindowHandles``` - return handles for both new tab and the old one
Actual: ```getWindowHandles``` - return handle only for old tab

**Comment by barancev** [comment]
Tabs are not supported (and never will be) in FirefoxDriver

**Comment by rovner** [comment]
It sounds really strange, because we use this api with firefox for a long time and for other cases it works fine. For example, if you just click on link that will open new tab, driver return correct amount of window handles.
Also, note that issue is reproducible for ie11 driver.
