### ISSUE TITLE
Firefox driver can't click anything after redirect with window.location and opening popup in one click

### ISSUE THREAD

**Issue by piohen** [SeleniumHQ/selenium#1509]
I'm creating tests for application which behaviour is reflected by attached HTML files. After clicking a button, two things happen with JS:
1. the main window is redirected to another location,
2. a popup window is opened.
After 1. users can do other things in the main window.

The issue is that this is working "manually" in Firefox, but somehow Firefox driver can't click any more in the main window, because the button still seems to be pressed. Everything works fine with Chromium.
The test fails with 
org.openqa.selenium.WebDriverException: UnknownError: Cannot press more then one button or an already pressed button.
I'm attaching HTML files and test cases so this can be replicated.
[seleniumPopup.zip](https://github.com/SeleniumHQ/selenium/files/97430/seleniumPopup.zip)
I'm using Selenium 2.49.0, Firefox 41.0.2, Chromium 47.

**Comment by lukeis** [comment]
thanks for the reproducible test!

I'm not sure how to fix this... but as a workaround on the page (after switching back, but before clicking) if you do this:

    new Actions(driver).release().perform();

you then will be able to click on the element.

**Comment by piohen** [comment]
Hi Luke

I tried releasing immediately after click and it didn't seem to work. Thanks!

**Comment by barancev** [comment]
Fixed by commit aac8e08
