### ISSUE TITLE
Mouse drag yields undefined behaviour?

### ISSUE THREAD

**Issue by DaveCTurner** [SeleniumHQ/selenium#1512]
[The protocol spec has this to say on the `buttonDown` action](https://github.com/seleniumhq/selenium/wiki/JsonWireProtocol#sessionsessionidbuttondown) (emphasis mine):

> Click and hold the left mouse button (at the coordinates set by the last `moveto` command). Note that the next mouse-related command that should follow is `buttonup`. **Any other mouse command (such as click or another call to `buttondown`) will yield undefined behaviour.**

It seems reasonable that `buttonDown` then `click` should result in undefined behaviour, but the common use case for `buttonDown` is to follow it with a `moveto` to simulate a drag. I'd count `moveto` as a mouse command which isn't `buttonUp` and therefore this also results in undefined behaviour.

Is this just poor wording or is `buttonDown` then `moveto` not a legal sequence?

**Comment by lukeis** [comment]
That's just poor wording... and not likely to be updated, since we've been working on the W3C spec -
https://www.w3.org/TR/webdriver/

the JSONWireProtocol document is essentially just left there for historical reference.
