### ISSUE TITLE
Using Page Object, cannot work on the IWebElements loaded on the page

### ISSUE THREAD

**Issue by sam22blr** [SeleniumHQ/selenium#1514]
When debugged the objects show a value as "{System.Runtime.Remoting.Proxies.__TransparentProxy}	System.Collections.Generic.IList<OpenQA.Selenium.IWebElement> {System.Runtime.Remoting.Proxies.__TransparentProxy}"

For example the element is, 
[FindsByAttribute(How = How.TagName, Using = "label")]
        private IList<IWebElement> SelectRole;

**Comment by jimevans** [comment]
Duplicate of #1114

**Comment by sam22blr** [comment]
@jimevans, how to fix the existing page classes (there are many), can you give me some example code to show?

**Comment by sam22blr** [comment]
@jimevans , Can you give an example on how to workaround this issue?

**Comment by jimevans** [comment]
There is no workaround. You could implement your own classes to do so, one class implement the `IPageObjectMemberDecorator` interface, and your own proxy objects that would be created that don't use the .NET `RealProxy`. Or you could petition Microsoft to allow `TransparentProxy` object to evaluate their properties when using Intellisense in Visual Studio.

**Comment by sam22blr** [comment]
Thanks @jimevans. I would really appreciate if you can give me some example code on how to implement using IPageObjectMemberDecorator, google yields about 10 results without any example code?

**Comment by jimevans** [comment]
How about the [code in the .NET bindings](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/support/PageObjects/DefaultPageObjectMemberDecorator.cs) itself?

**Comment by sam22blr** [comment]
@jimevans not helpful, do you mind giving some real example code?

**Comment by jimevans** [comment]
I'm sorry that's not helpful. As far as I know, that's the only implementation in existence. I know of no other samples of how to do this, and no, I do not have the time to create an example as I'm struggling with a pretty nasty bout of influenza at the moment.

**Comment by sam22blr** [comment]
@jimevans, hope u feel better soon!
