### ISSUE TITLE
Javascript error on click to any option

### ISSUE THREAD

**Issue by testansh** [SeleniumHQ/selenium#1515]
Url: chrome://selenium-ide/content/editor.js - in Firefox now it is not working, on click to any option , error is coming for java-script.
For eg on click to option in menu this error is coming -
There was an unexpected error. Msg: TypeError: editor.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 1007, column: 75
Editor.prototype.onPopupOptions@chrome://selenium-ide/content/editor.js:1007:75
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1

Similar errors are coming even on click to close button, now please tell how to run Selenium again in firefox

**Comment by ArmanSadvakasov** [comment]
I have a similar mistake. Is this issue resolved?
![default](https://cloud.githubusercontent.com/assets/17117298/12878464/98cf4340-ce4f-11e5-812e-e0639613be22.jpg)

**Comment by piglovesyou** [comment]
I cannot represent that error with [one from add-on page](https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/) and one built from the recent source (7d0624) .

> now please tell how to run Selenium again in firefox
How about reinstalling the add-on?

And I want to know if it worked previously before the error occured.

**Comment by testansh** [comment]
yeah this issue is resolved but only on re-installation of ADD-ON did not
work, i reinstalled complete FIREFOX after that again add that ADD-ON

**Comment by samitbadle** [comment]
So, it is working now after re-installation?

**Comment by testansh** [comment]
It was working fine before error occurred, then due to error it was
allowing to run the script, after reinstallation, the problem is solved, it
is running fine.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Comment by testansh** [comment]
please start selenium ide in new update of firefox also, that was very
useful tool.
Kindly think over this issue
