### ISSUE TITLE
Firefox Driver(.NET) won't select option if the size of the options is greater than the select

### ISSUE THREAD

**Issue by Cervej4** [SeleniumHQ/selenium#1519]
Hi,
I was having a problem with a specific select(dropdown) in one page when i was calling SelectElement.SelectByValue :
Unexpected error. Element is not clickable at point (635.6666870117188, 256.5). Other element would receive the click: [div class="col-sm-10"][/div]
That's the div the select is in.
I found out that if i reduce the length of the options the problem won't appear anymore.
I'm using Firefox 43.0.4 and Selenium WebDriver 2.49.0
Thank You

**Comment by lukeis** [comment]
this has been very recently fixed b21a4f52d37588d2938aace2f47c93d442cd052e

next release will include the fix
