### ISSUE TITLE
Selenium node - create session and refresh session is disabled on selenium 2.49.1

### ISSUE THREAD

**Issue by alamsz** [SeleniumHQ/selenium#1521]
# Issue
After updating the selenium to version 2.49.0/2.49.1, now the selenium node create session and refresh session button is disabled. Thus I could not check whether my node responding well, usually I create session with  the browser chosen to see whether it spawning the browser well

My setup as below
OS : Linux
Selenium grid
Selenium node

selenium node 

## before 2.49.0 (example 2.48.2)
<img width="1031" alt="before 2 49" src="https://cloud.githubusercontent.com/assets/1900931/12530779/6398125e-c21c-11e5-9cad-3371d183c9ed.png">

## after 2.49.0
<img width="1029" alt="after 2 49" src="https://cloud.githubusercontent.com/assets/1900931/12530780/64dd4a76-c21c-11e5-9081-c35bf7363821.png">

Additional information, notice the server info not available in 2.49.1

**Comment by barancev** [comment]
It's not Selenium Grid, but some extension (the Grid itself has no UI).
Please report the issue to the tracker of this extension.

**Comment by lukeis** [comment]
This is in the standalone server, run the standalone jar with no parameters and then go here:  (redirected from /wd/hub).

http://localhost:4444/wd/hub/static/resource/hub.html

**Comment by alamsz** [comment]
yeah, forgot to mentioned that this is the standalone jar. Usually we could check the progress of tests, take screenshots, by acessing the 
`http://nodeip:nodeport/wd/hub`

This is the jar http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.1.jar

And this is how i start the grid
### HUB
`java -jar /usr/local/src/selenium-server-standalone-2.49.1.jar -role hub -port 5555 &`

### NODE
`java -jar /usr/local/src/selenium-server-standalone-2.49.1.jar -role node -port 5556 -hub http://myhubip:5555/grid/register &`




We could also use this to check node health, like spawning browsers that we wanted, to see whether the spawning process is successful or not, it is useful for me, since I usually spawn the browser in Xvfb, and this very helpful to check whether my setup correct or not.
