### ISSUE TITLE
safe_alert() fails at UI element startup in Selenium IDE

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1535]
If you have a UI-Element definition with test case(s) (as per https://selenium.googlecode.com/git/javascript/selenium-core/scripts/ui-doc.html > UI-Element Shorthand > testcase*), and the test case(s) fail, then Selenium IDE shows an ugly error, but not even a hint of the failed test case(s).

UI-Element calls safe_alert() twice from UIElement's test(), once from UIElement's init(), twice from UIMap's addPageset(), three times from UIMap's addElement(). The only other call is in getLocator(), which should work since that's when Selenium IDE window is already shown.

This may be caused by Firefox change in 2013 mentioned at https://forums.mozilla.org/viewtopic.php?f=7&t=14917, or related to https://bugzilla.mozilla.org/show_bug.cgi?id=912655, or who knows....

What steps will reproduce the problem?
0. Download a file attached to https://code.google.com/p/selenium/issues/detail?id=8428
1. Selenium IDE > Options > Options > Selenium Core extensions > select the downloaded  ui_element_with_brokent_testcase.js
2. Restart Selenium IDE
3. You get an error popup: "Cannot call openModalWindow on a hidden window".

There may be similar problems elsewhere in Selenium IDE, if it uses safe_alert() before its window is displayed.

Selenium version: 2.9.1 IDE
OS: Fedora 20
Browser: Firefox 44
For streamlining, I suggest implementing together with https://github.com/SeleniumHQ/selenium/issues/1536.
(See the below original issue for call stack, but based on IDE 2.8.0)
Migrated from https://code.google.com/p/selenium/issues/detail?id=8428

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
