### ISSUE TITLE
UI element test cases should be run even after Selenium IDE startup

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1536]
If you have a UI-Element definition with test case(s) (as per https://selenium.googlecode.com/git/javascript/selenium-core/scripts/ui-doc.html > UI-Element Shorthand > testcase*), and the test case(s) fail, and you re-load that Core extension, then Selenium IDE doesn't re-run the test cases().

What steps will reproduce the problem?
0. Download a file attached to https://code.google.com/p/selenium/issues/detail?id=8429 (or Download a file attached to https://code.google.com/p/selenium/issues/detail?id=8428)
1. Selenium IDE > Options > Options > Selenium Core extensions > select the attached ui_element_with_brokent_testcase.js
2. Restart Selenium IDE
3. The custom ui element definition is loaded, its test case is run and if it fails it's reported (side note: the error doesn't currently show up well, see https://github.com/SeleniumHQ/selenium/issues/1535)
4. Selenium IDE > Options > Options > click at Reload button right of 'Selenium Core extensions'
5. The custom ui element definition is re-loaded, but its test case is not run (and any failures in it are not reported).

Please, modify UIMap's addElement() in chrome://selenium-ide/content/selenium-core/scripts/ui-element.js, around line 886, from

```
    // run the element's unit tests only for the IDE, and only when the
    // IDE is starting. Make a rough guess as to the latter condition.
    if (is_IDE() && !editor.selDebugger && !uiElement.test()) {
```

to

```
    // run the element's unit tests only for the IDE.
    if (is_IDE() && !uiElement.test()) {
```

To streamline, I suggest you implement it together with https://github.com/SeleniumHQ/selenium/issues/1535.

Selenium version: 2.9.1
OS: Fedora 20
Browser: Firefox 44

(Originally reported at https://code.google.com/p/selenium/issues/detail?id=8429)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
