### ISSUE TITLE
Refactor TestCase.debugContext to have a class on its own

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1537]
No bug. Simple/trivial enhancement of Se IDE that
- makes the code more structured readable
- allows easier maintenance of 3rd part flow control plugins (like SelBlocks/SelBlocks Global/Control Flow)
- backwards compatible

This is Se IDE-specific. Basically, currently TestCase class uses an anonymous object for its object field debugContext. The code of that anonymous debugContext object refers back to the TestCase via a closure variable 'testCase'.

I propose a new class TestCaseDebugContext. TestCase.debugContext will be an instance of that class. Its constructor and object field 'testCase' will link to the given TestCase instance (the owner of debugContext). That way references between them are clear and over the board.

That allows 3rd party to tail-extend prototype methods of TestCaseDebugContext, if needed. It is backwards compatible with Se IDE.

Attached is a git diff (against current master). Following is the suggested code - for ide/main/src/content/testCase.js

function TestCaseDebugContext( testCase ) {
    this.testCase= testCase;
}

TestCaseDebugContext.prototype.reset= function() {
    this.failed = false;
    this.started = false;
    this.debugIndex = -1;
};

TestCaseDebugContext.prototype.nextCommand= function() {
    if (!this.started) {
        this.started = true;
        this.debugIndex = this.testCase.startPoint
            ? this.testCase.commands.indexOf(this.testCase.startPoint)
            : 0;
    } else {
        this.debugIndex++;
    }
    for (; this.debugIndex < this.testCase.commands.length; this.debugIndex++) {
        var command = this.testCase.commands[this.debugIndex];
        if (command.type == 'command') {
            return command;
        }
    }
    return null;
};

TestCaseDebugContext.prototype.currentCommand= function() {
    var command = this.testCase.commands[this.debugIndex];
    if (!command) {
        this.testCase.log.warn("currentCommand() not found: commands.length=" + this.testCase.commands.length + ", debugIndex=" + this.debugIndex);
    }
    return command;
};

function TestCase(tempTitle) {
    ....
    this.debugContext= new TestCaseDebugContext( this );
}

See a .diff file attached to https://code.google.com/p/selenium/issues/detail?id=5495.

Selenium version: 2.9.1
Browser: Firefox 
Browser version: 44.0
(Originall reported as https://code.google.com/p/selenium/issues/detail?id=5495)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
