### ISSUE TITLE
verify* should show the diff

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1538]
It appears that if you do an assert\* it puts an error message in the log on failure, but there is nothing comparable for verify\* failures. I think there should be an 'info' level log that shows the diff.

To narrow down the issue a bit:
verify\* puts a message in the log, but only if you run the whole test case (or the whole test suite). If you run a single Selenese verify\* command (by double-clicking at it) and it fails, then the command gets highlighted in pink/reddish, but it doesn't put anything in the log. However, that may not be so obvious and is confusing. So, please make it add the message to the log, so it is consistent.

That's per Selenium IDE 2.9.1, Firefox 44.0.
(Originally reported at https://code.google.com/p/selenium/issues/detail?id=1092 and starred by seven people)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
