### ISSUE TITLE
Stuck at installation step 1 on Windows

### ISSUE THREAD

**Issue by ifijit** [SeleniumHQ/selenium#1539]
As per https://www.npmjs.com/package/selenium-webdriver/tutorial I am trying to install the selenium-webdriver JavaScript bindings

Extract from screenshot "Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?" 

I do have the C++ 2008 Redistributables installed and I thought msbuild might be part of Windows 7.1 SDK. Running Windows 10; Visual Studio 2015 CE with update 1***; node.js 4.2.6; python 2.7.11
*** with Windows XP Support for C++ (Windows 7.1 SDK), Universal Tools, Windows 8.0/8.1 Tools
![2016-01-26 1](https://cloud.githubusercontent.com/assets/5959935/12606461/8b67431e-c482-11e5-85f1-c2a50796df15.png)

**Comment by jleyba** [comment]
See the npm warning messages in your screenshot - these are failures installing optional transitive dependencies and should not impact selenium-webdriver's functionality (especially for windows since these deps are only used for safari)
