### ISSUE TITLE
Handling pop up in Firefox

### ISSUE THREAD

**Issue by sangeetaagarwal** [SeleniumHQ/selenium#1541]
I am executing a script in firefox. Before displaying response message a pop up is displayed with 2 options:Continue, Cancel. I want to click on COntinue and proceed. But selenium IDE is unable to recognize as it is not browser based pop up.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
