### ISSUE TITLE
Clear() number inputs doesn't work

### ISSUE THREAD

**Issue by amwill1** [SeleniumHQ/selenium#1544]
this is still an issue for me. (I just updated to Selenium Standalone 2.49.1) I've tried the suggestions in this [question](http://stackoverflow.com/questions/32326978/the-clear-function-does-not-work-on-input-of-type-number) and did

numInput.click();
browser.sleep(1000);
numInput.clear().sendKeys('5);

but this solution only seems to work sometimes. often what happens is the input gets cleared but then fills in the previous value before sending the new value. i'm not sure what to do. I'm using Protractor 3.0.0 as well but they directed me over here

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by amwill1** [comment]
I've tried making a minimal example but I can't reproduce it there.  :( Here's the [url](http://amwill1.github.io/numberInputIssue/) just in case. It's a big problem in my project.

**Comment by barancev** [comment]
We have a special regression test for this case that passes in all main browsers:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/TypingTest.java#L697-L707
