### ISSUE TITLE
Selenium IDE chrome/content/formats/html.js to preserve indented Selenese command names

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1546]
Selenium IDE 2.5.0 (and most likely the recent dev/trunk) allows Selenese commands (the 1st column) to be indented with spaces. It saves such spaces as &nbsp;. However, when a user loads a test case, it doesn't parse such commands. They only show up in the 'Source' tab, and once the user saves the test suite again, they're deleted.

Indeed, one may argue that there's not much need for indented Selenese when having plain linear test cases. But even then a user can type space(s) left of Selenese by mistake. The test case works for him or her then, but it won't work when he or she reloads it later. Hence this is a bug. 

Furthermore, Selenese can be structured through if/else, loop and script statements using SeLite, SelBlocks or FlowControl. Their users would greatly benefit from such indentation being preserved.

A fix is to change [content/formats/html.js](https://github.com/SeleniumHQ/selenium/blob/master/ide/main/src/content/formats/html.js) to use the following (incorporating https://github.com/SeleniumHQ/selenium/issues/1636):

``` javascript
this.options = {
    commandLoadPattern:
    "<tr\s*[^>]*>" +
    "\\s*(<!--[\\d\\D]*?-->)?" +
    "\\s*<td\s*[^>]*>\\s*([\\w]*?)\\s*</td>" +
    "\\s*<td\s*[^>]*>([\\d\\D]*?)</td>" +
    "\\s*(<td\s*/>|<td\s*[^>]*>([\\d\\D]*?)</td>)" +
    "\\s*</tr>\\s*",

to

this.options = {
    commandLoadPattern:
    "<tr\\s*[^>]*>" +
    "\\s*(<!--[\\d\\D]*?-->)?" +
    "\\s*<td\\s*[^>]*>\\s*((?:&nbsp;)*[\\w]*?)\\s*</td>" +
    "\\s*<td\\s*[^>]*>([\\d\\D]*?)</td>" +
    "\\s*(<td\\s*/>|<td\\s*[^>]*>([\\d\\D]*?)</td>)" +
    "\\s*</tr>\\s*",
```

I'm willing to provide a github pull request.

This depends on and could be implemented together with https://github.com/SeleniumHQ/selenium/issues/1636.

(Originally reported as https://code.google.com/archive/p/selenium/issues/6903. However, Google Code misformatted the suggested code fix in that issue.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
