### ISSUE TITLE
Report user extension/plugin error stack

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1548]
This is an enhancement suggestion.

What steps will reproduce the problem?
1. Have a custom/third party extension/plugin for Se IDE, which fails on load
2. Se IDE shows the error message and line number, but not the file name.
3. Se IDE lists all user-provided files, but there may be several extensions (incl. 3rd party), so it's not clear to the developer which is broken.

What is the expected output? What do you see instead?
- in addition to the current error details, the stack trace is very needed.

Selenium version: 2.9.1
Firefox 44.0
Suggested change in chrome/content/editor.js:
from
      this.showAlert(Editor.getFormattedString('user.extensions.failed', [error.toString()]));
to
      this.showAlert(Editor.getFormattedString('user.extensions.failed', [error.toString()+ '\n' +error.stack]));

(Originally reported as https://code.google.com/p/selenium/issues/detail?id=5423.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
