### ISSUE TITLE
Core extensions are loaded 2x - document this, or prevent it

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1549]
1. Have Selenium IDE 2.4.0 in Firefox 25
2. Have a Core extension in a ,js file, specify it at IDE > Options > Options > core extensions (and restart Selenium)
3. The file will be loaded/processed (at least) twice
4. first, at IDE startup
5. second, the first time I run any Selenese command
   See stacktraces below.

This may not affect simple usage. But it is badly confusing if your Core extension creates objects via XPCOM or JS component, SQLite connection, a file etc. - objects that need to be tracked or released, or that are book kept somehow.

Action needed: Either
- preferred: change the behaviour, so that Core extension(s) are loaded only once
- or: document this at http://www.seleniumhq.org/docs/02_selenium_ide.jsp#user-extensions

Example of stack trace in Selenium IDE 2.9.1:

At srtart of Selenium IDE:
@chrome://selenium-ide/content/tools.js -> file:///tmp/core-extension.js?1453953484869:3:6
ExtensionsLoader.loadSubScript/<@chrome://selenium-ide/content/tools.js:206:11
ExtensionsLoader.loadSubScript@chrome://selenium-ide/content/tools.js:203:5
Editor.prototype.loadSeleniumAPI@chrome://selenium-ide/content/editor.js:1128:7
Editor@chrome://selenium-ide/content/editor.js:164:3
StandaloneEditor@chrome://selenium-ide/content/standalone-editor.js:22:5
onload@chrome://selenium-ide/content/selenium-ide.xul:1:1

First Selenese command run:
@chrome://selenium-ide/content/tools.js -> file:///tmp/core-extension.js?1453953493781:3:6
ExtensionsLoader.loadSubScript/<@chrome://selenium-ide/content/tools.js:206:11
ExtensionsLoader.loadSubScript@chrome://selenium-ide/content/tools.js:203:5
Debugger/this.init@chrome://selenium-ide/content/debugger.js:66:9
Debugger.prototype.executeCommand@chrome://selenium-ide/content/debugger.js:171:3
.executeCurrentCommand@chrome://selenium-ide/content/treeView.js:523:21
.initialize/controller.doCommand@chrome://selenium-ide/content/treeView.js:84:55
goDoCommand@chrome://global/content/globalOverlay.js:96:7
ondblclick@chrome://selenium-ide/content/selenium-ide.xul:1:1

(Originally reported as https://code.google.com/p/selenium/issues/detail?id=6697.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
