### ISSUE TITLE
Base URL Should Allow Path

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1550]
1. Open the IDE.
2. Enter https://code.google.com/p/selenium/ (where /p/selenium is the path) as the base URL.
3. Insert a new "open" command with a target of /w/list. This is a path relative to https://code.google.com/p/selenium/. (That is, https://code.google.com/p/selenium/w/list is a valid page.)
4. Right click the open command and execute it.

What is the expected output? What do you see instead?

Expectation: Selenium should send a command to the browser that it should open https://code.google.com/p/selenium/w/list.

Actual Result: Selenium commands the browser to open https://code.google.com/w/list, which is invalid and results in a 404 page.

Selenium IDE 2.9.1, Firefox 44.0
(Originally reported as https://code.google.com/p/selenium/issues/detail?id=3116.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
