### ISSUE TITLE
.getText() function is not woking in Firefox

### ISSUE THREAD

**Issue by sangeetaagarwal** [SeleniumHQ/selenium#1551]
I need to read the text displayed in element. I am using xpath to read the element.It is working fine in Chrome . I am getting the value displayed in element when I run in chrome. But in firefox the same is displaying null. Please do give the solution ASAP.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
