### ISSUE TITLE
Running test scripts in IE browser. But it is not able to click on elements on the 2nd page

### ISSUE THREAD

**Issue by sangeetaagarwal** [SeleniumHQ/selenium#1552]
My script runs properly in Google chrome. But when I run the same script in IE it is not recognizing the element on the second page i.e After launching the portal, it is performing all the actions and after clicking on submit, next page is displayed. It is not performing any actions on that page. Folowing error message is displayed. (Unable to find element on closed window (WARNING: The server did not provide any Unable to find element on closed window (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 4 milliseconds Build info: version: '2.)

I am using link property to identify the objects on the second page.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sangeetaagarwal** [comment]
the script in IE is running but it is not performing any actions on the second page

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
