### ISSUE TITLE
Safari 9.0.3 - Unable to install Selenium Extension in this version of Safari

### ISSUE THREAD

**Issue by manjunathscp** [SeleniumHQ/selenium#1553]
Kindly advice what all should I have to Check for this.

Previously I had Safari version 9 and it had Selenium 2.45 extension installed. On update of Safari to 9.0.3, I uninstalled old extension and tried to install Selenium 2.48 extension. I'm getting the pop up if this extension is from trusted source or not. But on clicking Trust, nothing happens - no extension is installed.

**Comment by AdamAJeng** [comment]
+1

**Comment by markozz** [comment]
+1 
This does seem a issue with OSX safari though, since I am also not able to install other 3rd party plugins such as "ClickToPlugin". 

Already tried to remove all cache and library data like suggested over here:
http://www.hawkdive.com/2015/12/unable-to-install-safari-extension.html
but to no avail..

I found alot of people having similar problems with different Safari extensions

**Comment by DV3D** [comment]
I found a workaround for installing Webdriver on Safari 9.0.3!

The problem is the click on 'trust' doesn't seem to be registered, so now I hit 'trust' by keyboard: **tab, space**.

For this you first have to enable the Full Keyboard Access option in OSX preferences:
![keyboardprefsallcontrols](https://cloud.githubusercontent.com/assets/10705173/13392325/eea4a036-ded9-11e5-9f6d-340072e7ea89.png)

**Comment by dimashabalin** [comment]
@DV3D Hi, your method didn't worked for me, still nothing happens on clicking 'trust' either way

**Comment by DV3D** [comment]
Sorry to hear it's not working for you, I got it working on multiple MacBooks this way.
Just to double check: did you highlighted 'trust' with tab-key, then pressed spacebar (**not** enter)?

**Comment by dimashabalin** [comment]
Sure, doing it exactly like you said - tab to highlight 'trust' then space (enter not even working). Popup disappears leaving me with empty extensions dialog. Extensions from market installs ok, but not this selenium webdriver extension

**Comment by manjunathscp** [comment]
Yes. I tried the solution suggested above. No luck. Still I'm ending up
with empty extension box.

**Comment by mstrelex** [comment]
I can confirm that indeed the solution that @DV3D proposed works well, however not when using remote access (for example I was using NoMachine and it didn't work, however when doing it with a physical keyboard attached to the computer it worked and extension got installed.

**Comment by dimashabalin** [comment]
@DV3D @mstrelex Thanks guys, now its worked. One more point to hate Safari =) @manjunathscp you should try to do the trick physically not using remote access

**Comment by manjunathscp** [comment]
@DV3D @mstrelex  @dimashabalin Thanks a lot guys. Took a lot of time to coordinate and get this done. But the solution worked. :8ball:

**Comment by churey** [comment]
@DV3D @mstrelex  Hi guys, i can't install safaridriver extension too. and i press trust with no extension installed. i tried to use the solution which you guys pointed out and it still not working for me. Besides, i can only doing the operation using remote access. is there other workaround for me? The issue has been confusing me for a long time. Many thanks in advance!

**Comment by churey** [comment]
BTW, i tried to use the virtual keyboard of the remote mac machine and press tab and  space key to install the extension. it still not working for me.

**Comment by vania-pooh** [comment]
Updated Safari to 9.1 - same stuff.

**Comment by dbrack** [comment]
For me the proposed workaround did not work on OSX 10.11.5 and Safari 9.1.1.
I was able to install it just fine when I started OSX in safe mode (hold down shift key during boot)

Hope this helps someone else

**Comment by gpetrov-jensen** [comment]
@dbrack any thoughts how to make it work woth remote desktop? I have OSX Virtual machine and issuing the same issue from the original note.

**Comment by dbrack** [comment]
@gpetrov-jensen I haven't tried that. From what I've experienced, though, I would say it's not going to work.

**Comment by zhaihm** [comment]
@gpetrov-jensen Did you get it work for remote desktop? I'm facing same problem...

**Comment by cafshari** [comment]
Plugging a mouse directly into the Mac machine, then clicking 'Trust' did in fact work for me. Thanks for the tip
