### ISSUE TITLE
driver.manage().getCookieNamed() return incorrect cookie in ie

### ISSUE THREAD

**Issue by rovner** [SeleniumHQ/selenium#1554]
Environment: ie11 on windows7
iedriver.exe 2.45.0.5

Simple test:
```
DesiredCapabilities caps = new DesiredCapabilities("internet explorer", "11", Platform.WINDOWS);
driver = new RemoteWebDriver(url, caps);
driver.get("https://www.yandex.com/search/?text=cats");
Cookie z = driver.manage().getCookieNamed("z");
Assert.assertEquals("/search/", z.getPath());
Assert.assertThat(z.getDomain(), CoreMatchers.notNullValue());
Assert.assertThat(z.getExpiry(), CoreMatchers.notNullValue());
```
Expected: cookie contains correct path, domain and expiration date, the same you could get with help of developer tools in browser.

**Comment by jimevans** [comment]
What version of IEDriverServer.exe are you using? Also, what type of cookie is being set? If it's a session cookie, I would expect it to have no expiration time.

**Comment by rovner** [comment]
I've updated description with iedriver.exe version.
No, it isn't a session cookie, in developer tools it have expiration time.

**Comment by jimevans** [comment]
Please update to the latest IE driver. Cookie handling was rewritten to provide that information for server-side cookies after 2.46.
