### ISSUE TITLE
Mac OS X 10.7 Lion is missing from platforms

### ISSUE THREAD

**Issue by JurgenR** [SeleniumHQ/selenium#1555]
The MacOSX 10.7 platform is missing from the list of platforms:

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/Platform.java

**Comment by shs96c** [comment]
OS X 10.7 usage is vanishingly small, and java 8 requires OS X 10.8 and above. There's no need for this value.
