### ISSUE TITLE
Timeout issue from 2.49.0 may be re-introduced in 2.50.0 - new version is timing out

### ISSUE THREAD

**Issue by lindavz28** [SeleniumHQ/selenium#1558]
Hi there,

Just upgraded our Selenium grid to use 2.50.0 and noticed our tests consistently failing a few seconds into the tests.  Reproduced on local machine by replacing my current version of selenium - 2.49.1 with 2.50.0 and restart the services - the tests start up, login to my web application and then almost immediately the browser gets shut down.

The only change to the test is the version of selenium being used.

I think the node is timing out too fast - which may be a re-introduction of the 2.49 bug that was fixed in 2.49.1.

**Hub log :**
C:\Selenium>java -jar C:\Selenium\selenium-server-standalone-2.50.0.jar -role hub -port 2021
08:55:36.274 INFO - Launching Selenium Grid hub
2016-01-29 08:55:37.243:INFO::main: Logging initialized @1175ms
08:55:37.261 INFO - Will listen on 2021
08:55:37.333 INFO - Will listen on 2021
2016-01-29 08:55:37.338:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-01-29 08:55:37.385:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletC
ontextHandler@cb0ed20{/,null,AVAILABLE}
2016-01-29 08:55:37.415:INFO:osjs.ServerConnector:main: Started ServerConnector@
7276c8cd{HTTP/1.1}{0.0.0.0:2021}
2016-01-29 08:55:37.416:INFO:osjs.Server:main: Started @1348ms08:55:37.416 INFO - Nodes should register to http://10.53.30.87:2021/grid/register/
08:55:37.417 INFO - Selenium Grid hub is up and running
08:55:38.294 INFO - Registered a node http://10.53.30.87:5555
08:55:54.812 INFO - Got a request to create a new session: Capabilities [{browse
rName=chrome, javascriptEnabled=true, chromeOptions={args=[--start-maximized, --
no-sandbox]}, version=, platform=ANY}]
08:55:54.813 INFO - Available nodes: [http://10.53.30.87:5555]
08:55:54.813 INFO - Trying to create a new session on node http://10.53.30.87:5555
08:55:54.814 INFO - Trying to create a new session on test slot {seleniumProtoco
l=WebDriver, browserName=chrome, maxInstances=5, platform=VISTA}
**08:56:08.288 WARN - session ext. key 6a3b060a-0133-43c3-999b-68e6ca9fbff5 has TIMED OUT due to client inactivity and will be released.**

**Node:**
08:56:03.800 INFO - Executing: [find element: By.linkText: Login])
08:56:07.227 WARN - Exception thrown
org.openqa.selenium.NoSuchElementException: no such element
  (Session info: chrome=47.0.2526.111)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.01 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.50.0', revision: '1070ace', time: '2016-01-27 18:43:24'
System info: host: 'XLW-CNU4059YDR', ip: '10.53.30.87', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, chrome={userDataD
ir=C:\Users\LINDA~1.VAN\AppData\Local\Temp\scoped_dir6912_24457}, takesHeapSnaps
hot=true, databaseEnabled=false, handlesAlerts=true, version=47.0.2526.111, plat
form=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true,
 locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesS
creenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 4292d74f8555213584d256d7632f547b
*** Element info: {Using=link text, value=Login}
      ....
08:56:07.242 WARN - Exception: no such element
  (Session info: chrome=47.0.2526.111)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.01 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/
no_such_element.html
**08:56:07.827 INFO - Done: [execute script: return document.readyState == 'complete', []]
08:56:08.292 INFO - Executing: [delete session: 6a3b060a-0133-43c3-999b-68e6ca9f
bff5])**
08:56:08.336 INFO - Executing: [get title])
08:56:09.587 INFO - Done: [delete session: 6a3b060a-0133-43c3-999b-68e6ca9fbff5]

08:56:09.846 WARN - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?

**Node config being used:**
"configuration":
  {
	"maxSession":5,
        "port": 5555,
        "host": ip,
        "hubPort": 2021,
        "hubHost": ip,
	"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
	"nodeTimeout": 120,
	"nodePolling": 2000,
	"cleanUpCycle": 2000,
	"timeout": 100000
  }

**Comment by derinbay** [comment]
https://github.com/SeleniumHQ/selenium/commit/bf66042eb2aee6d95d5987b1704b52f1260382e6

**Comment by barancev** [comment]
Fixed in 2.50.1
