### ISSUE TITLE
.NET Bindings: proposal to standardize "localWebDriver" /RemoteWebDriver capabilities management

### ISSUE THREAD

**Issue by dzharii** [SeleniumHQ/selenium#1559]
I am not sure if I am using a correct term, for me there are "LocalWebDriver" bindings, which represent FirefoxDriver, ChromeDriver, InternetExplorerDriver classes and RemoteWebDriver binding implementation. 

The thing is "LocalWebDriver" and RemoteWebDriver use different ways to pass the desired capabilities to the driver. What is even worse, every driver uses it's own class, such as FirefoxOptions, ChromeOptions etc. to customize the capabilities. 

Eventually, "LocalWebDrivers" and RemoteWebDriver capabilities are being serialized to same JSON-wired data structure, so why do we have those multiple ways to set the capabilities inside the "LocalWebDrivers". 

The issue: 
* Having different capability implementations, I am not able to use the same Capability list for the local run (the run on the local machine, using "LocalWebDrivers") and RemoteWebDriver for same browser type. I have to implement the capability configuration individually for each browser type (e.g. Local Chrome and RemoteWebdriver). 

Proposal: 

1.Allow LocalWebDrivers to accept ICapabilities as a constructor parameters. Now only FirefoxDriver supports this, so I can use same list of capabilities for FirefoxDriver and for Firefox started via RemoteWebDriver. It is not possible to pass  ICapabilities to ChromeDriver or InternetExplorerDriver

```
        public FirefoxDriver(ICapabilities capabilities)
            : this(ExtractBinary(capabilities), ExtractProfile(capabilities), capabilities, RemoteWebDriver.DefaultCommandTimeout)
        {
        }
```

2.Remove runtime checks such as: 

```
        public void AddAdditionalCapability(string capabilityName, object capabilityValue, bool isGlobalCapability)
        {
            if (capabilityName == ChromeOptions.Capability ||
                capabilityName == CapabilityType.Proxy ||
                capabilityName == ChromeOptions.ArgumentsChromeOption ||
                capabilityName == ChromeOptions.BinaryChromeOption ||
                capabilityName == ChromeOptions.ExtensionsChromeOption ||
                capabilityName == ChromeOptions.LocalStateChromeOption ||
                capabilityName == ChromeOptions.PreferencesChromeOption ||
                capabilityName == ChromeOptions.DetachChromeOption ||
                capabilityName == ChromeOptions.DebuggerAddressChromeOption ||
                capabilityName == ChromeOptions.ExtensionsChromeOption ||
                capabilityName == ChromeOptions.ExcludeSwitchesChromeOption ||
                capabilityName == ChromeOptions.MinidumpPathChromeOption ||
                capabilityName == ChromeOptions.MobileEmulationChromeOption ||
                capabilityName == ChromeOptions.PerformanceLoggingPreferencesChromeOption ||
                capabilityName == ChromeOptions.WindowTypesChromeOption)
            {
                string message = string.Format(CultureInfo.InvariantCulture, "There is already an option for the {0} capability. Please use that instead.", capabilityName);
                throw new ArgumentException(message, "capabilityName");
            }
...
}
```
 which artificially prevent to set the capability and implement merging with ICapabilities. 

I believe this changes may reduce the configuration complexity for the WebDriver users and make the capability management more consistent. 

You can count on me for making the code changes and conducting the experiments. 
But, before doing anything, I would like to know what are @jimevans thoughts regarding this issue. 

Thank you, 
Dmytro

**Comment by jimevans** [comment]
In a word, no. We will not be doing this. The various Options classes exist for a reason: to create a type-safe way for users to be able to configure drivers for specific browsers. The Firefox case is an exception, but will be brought into line in a future version. Every Options class has a method by which one can add an additions capability that does not yet have a type-safe option; the runtime checks for capability names ensure that the type-safe properties and methods are used. Additionally, the Options classes can be used in the Remote case, as each one has a `ToCapabilities` method that can be used to generate a properly formed capabilities object.

I try not to exercise executive authority over language bindings very often, but this is one time I will do so. Pull requests attempting to remove the use of type-safe classes for setting driver options will be rejected.

**Comment by dzharii** [comment]
@jimevans  roger that. 
Thank you
