### ISSUE TITLE
firefox opening multiple tabs

### ISSUE THREAD

**Issue by osaidahmad** [SeleniumHQ/selenium#1560]
Hi,

I am using :
Selenium Stand alone : 2.50.0
OS:Windows 7-32 bit 
Browser:Firefox
Browser version:35.0.1 
in Test Complete 11.10 (supports this version of firefox).

Function Test
  set driver=JavaClasses.org_openqa_selenium_firefox.FirefoxDriver.newInstance
End Function

It is opening 2 tabs, 1 blank and one with some other skype extension URL

Regards 
Osaid

**Comment by osaidahmad** [comment]
Is this some extension issue or something else 

PS: not facing this issue in other machine with 64-bit Win7

**Comment by ddavison** [comment]
it's most likely because you are using a shared profile.  though it's hard to tell with the environment you have - I'm not sure anybody here uses Test Complete

**Comment by barancev** [comment]
It is recommended to use vanilla Firefox with Selenium.

**Comment by JMVM** [comment]
Try removing Skype add-on in your Firefox browser
