### ISSUE TITLE
no JSON object could be decoded becomes string indices must be integers after update

### ISSUE THREAD

**Issue by abioneperhobby** [SeleniumHQ/selenium#1563]
i created this issue starting from https://github.com/SeleniumHQ/selenium/issues/1478

Click Element  |  link=anchorText normally works but in this case return

ValueError: No JSON object could be decoded.

i upgraded selenium by pip from 2.49.0 to 2.50.0

i got a new error 

TypeError: string indices must be integers

this is the html code

<a data-bind="'css': $parent.withIcon() ? 'block ' : '', 'html': displayLabel()">Permissions</a>

due the css selector $('.loaded > a:nth-child(2)') works by jquery $('.loaded > a:nth-child(2)').click() , i tried to use the same with selenium

Click Element                       jquery=.loaded > a:nth-child(2)

and i obtain the same error : string indices must be integers

how i can give other informations?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Should be fixed in 2.50.1 (released today)

**Comment by abioneperhobby** [comment]
it's very difficult for me to give a reproducible test case because this is a private dashboard that need authentication .

i think the problem is my html because the click on the third element works, but i will give other information and i will THANKS you @barancev  for attention and upgrade

after upgrading from 2.50.0 to 2.50.1 error related to

Click Element  |  css=#tab-container1>a

(i also tried with link=Permissions)

changed to

WebDriverException: Message: Element is not clickable at point (510.133331298828
1, 137.8000030517578). Other element would receive the click: <div class="fake-b
g"></div>

if i use

$('#tab-container1>a').click() , with the same browser, click works.

For now as workaround i use Execute Javascript $('#tab-container1>a').click()

with the attachment i show the html structure

![click](https://cloud.githubusercontent.com/assets/2149815/12744140/cd9d24dc-c992-11e5-8ede-9ac00f9ea8a9.jpg)

**Comment by barancev** [comment]
So the original issue (related to error handling) has been resolved.

For a clickability issue please create a separate report is you have a [concise reproducible test case](http://sscce.org/)
