### ISSUE TITLE
Selenium 2.50.0 in grid mode failing with an exception - 2.49.1 works fine

### ISSUE THREAD

**Issue by pi4r0n** [SeleniumHQ/selenium#1564]
Hello everyone

I have just got 2.50.0 version and running it in grid mode (see configs below) each time I start my test I failed with below exception. Please note previous version 2.49.1 works perfectly fine.

**EXCEPTION**
`16:21:54.858 INFO [1] org.openqa.grid.selenium.GridLauncher - Launching a Selenium Grid node
16:21:55.234 INFO [1] org.openqa.selenium.server.SeleniumServer - Writing debug logs to D:\SELENIUM\logs\win7_node_config.log
16:21:55.234 INFO [1] org.openqa.selenium.server.SeleniumServer - Java: Oracle Corporation 25.71-b15
16:21:55.234 INFO [1] org.openqa.selenium.server.SeleniumServer - OS: Windows 7 6.1 amd64
16:21:55.237 INFO [1] org.openqa.selenium.server.SeleniumServer - v2.50.0, with Core v2.50.0. Built from revision 1070ace
16:21:55.266 INFO [1] org.openqa.selenium.remote.server.DefaultDriverProvider - Driver class not found: com.opera.core.systems.OperaDriver
16:21:55.267 INFO [1] org.openqa.selenium.remote.server.DefaultDriverFactory - Driver provider com.opera.core.systems.OperaDriver is not registered
16:21:55.270 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
16:21:55.294 INFO [1] org.openqa.grid.selenium.GridLauncher - Selenium Grid node is up and ready to register to the hub
16:21:55.310 INFO [19] org.openqa.grid.internal.utils.SelfRegisteringRemote - Starting auto registration thread. Will try to register every 5000 ms.
16:21:55.310 INFO [19] org.openqa.grid.internal.utils.SelfRegisteringRemote - Registering the node to the hub: http://10.1.12.19:4444/grid/register
16:21:55.325 INFO [19] org.openqa.grid.internal.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
16:22:02.578 INFO [17] org.openqa.selenium.remote.server.DriverServlet - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2c24f7b3, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]])
16:22:02.584 INFO [24] org.openqa.selenium.remote.server.FirefoxDriverProvider - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2c24f7b3, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]
16:22:08.197 INFO [17] org.openqa.selenium.remote.server.DriverServlet - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2c24f7b3, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]]
16:22:08.686 INFO [28] org.openqa.selenium.remote.server.DriverServlet - Executing: [maximise window])
16:22:08.687 INFO [17] org.openqa.selenium.remote.server.DriverServlet - Executing: [get: https://10.1.12.19/])
16:22:08.687 INFO [16] org.openqa.selenium.remote.server.DriverServlet - Executing: [implicitly wait: 3000])
16:22:08.725 INFO [28] org.openqa.selenium.remote.server.DriverServlet - Done: [maximise window]
16:22:10.327 INFO [28] org.openqa.selenium.remote.server.DriverServlet - Executing: [delete session: b87a8bfe-9683-47a2-9368-392b3471e979])
16:22:10.949 INFO [17] org.openqa.selenium.remote.server.DriverServlet - Done: [get: https://10.1.12.19/]
16:22:10.960 INFO [16] org.openqa.selenium.remote.server.DriverServlet - Done: [implicitly wait: 3000]
16:22:10.964 INFO [16] org.openqa.selenium.remote.server.DriverServlet - Executing: [find elements: By.xpath: //html[1]/body[1]/app[1]])
16:22:11.848 INFO [28] org.openqa.selenium.remote.server.DriverServlet - Done: [delete session: b87a8bfe-9683-47a2-9368-392b3471e979]
16:22:12.122 WARN [16] org.openqa.selenium.remote.server.DriverServlet - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.50.0', revision: '1070ace', time: '2016-01-27 18:43:24'
System info: host: 'PC-1063', ip: '10.1.12.19', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_71'
Driver info: driver.version: EventFiringWebDriver
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:377)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:504)
	at org.openqa.selenium.By$ByXPath.findElements(By.java:356)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy1.findElements(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElements(EventFiringWebDriver.java:177)
	at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:50)
	at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
16:22:12.124 WARN [16] org.openqa.selenium.remote.server.DriverServlet - Exception: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.50.0', revision: '1070ace', time: '2016-01-27 18:43:24'
System info: host: 'PC-1063', ip: '10.1.12.19', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_71'
Driver info: driver.version: EventFiringWebDriver
16:22:18.912 INFO [18] org.openqa.selenium.server.SeleniumServer - Shutting down...
`
**HUB AND NODE**

> SET version=2.49.1
start cmd /c "java -jar %~dp0\selenium_lib\selenium-server-standalone-%version%.jar -role hub -hubConfig %~dp0\configs\hub_config.json

> start cmd /c "java -jar %~dp0\selenium_lib\selenium-server-standalone-%version%.jar -role webdriver -nodeConfig %~dp0\configs\win7_node_config.json -Dwebdriver.chrome.driver=%~dp0\drivers\chromedriver.exe -Dwebdriver.opera.driver=%~dp0\drivers\operadriver.exe -Dwebdriver.ie.driver=%~dp0\drivers\IEDriverServer.exe -log %~dp0\logs\win7_node_config.log"

**HUB CONFIG**
`{
  "host": IP,
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,

  "cleanUpCycle": 5000,
  "timeout": 300000,
  "maxSession": 5
}`

**NODE CONFIG**
`{
  "capabilities":
      [
        {
          "browserName": "firefox",
          "maxInstances": 1,
          "version": 42,
          "platform": "WINDOWS",
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "chrome",
          "maxInstances": 1,
          "version": 47,
          "platform": "WINDOWS",
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "opera",
          "maxInstances": 1,
          "version": 12,
          "platform": "WINDOWS",
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "internet explorer",
          "maxInstances": 1,
          "version": 11,
          "platform": "WINDOWS",
          "seleniumProtocol": "WebDriver"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 5,
    "port": 4455,
    "host": "HOST IP",
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "HUB IP"
  }
}`

**Comment by barancev** [comment]
Fixed in 2.50.1
