### ISSUE TITLE
Exclude tests per browser not working in Selenium 2.49.1 with Mocha and Gulp

### ISSUE THREAD

**Issue by pi4r0n** [SeleniumHQ/selenium#1566]
Hello everyone

I am running my server in grid mode with WebdriveriIO lib and notice that exclude test per browser is not handled by Selenium. As you can see from below Selenium receives message with exclude test but for some reason it still actioned it. If you required any more info please let me know and I will be happy to provide

`17:16:25.585 INFO [1] org.openqa.grid.selenium.GridLauncher - Launching a Selenium Grid node
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - Writing debug logs to logs/mac_node_config.log
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - Java: Oracle Corporation 25.65-b01
17:16:28.349 INFO [1] org.openqa.selenium.server.SeleniumServer - OS: Mac OS X 10.11.3 x86_64
17:16:28.400 INFO [1] org.openqa.selenium.server.SeleniumServer - v2.49.1, with Core v2.49.1. Built from revision 7203e46
17:16:28.591 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform MAC
17:16:28.591 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform MAC
17:16:28.592 INFO [1] org.openqa.selenium.remote.server.DefaultDriverProvider - Driver class not found: com.opera.core.systems.OperaDriver
17:16:28.592 INFO [1] org.openqa.selenium.remote.server.DefaultDriverFactory - Driver provider com.opera.core.systems.OperaDriver is not registered
17:16:28.931 INFO [1] org.openqa.jetty.http.HttpServer - Version Jetty/5.1.x
17:16:28.946 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/selenium-server,/selenium-server]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started org.openqa.jetty.jetty.servlet.ServletHandler@dd3b207
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/wd,/wd]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
17:16:29.009 INFO [1] org.openqa.jetty.util.Container - Started HttpContext[/,/]
17:16:29.028 INFO [1] org.openqa.jetty.http.SocketListener - Started SocketListener on 0.0.0.0:4477
17:16:29.028 INFO [1] org.openqa.jetty.util.Container - Started org.openqa.jetty.jetty.Server@1877ab81
17:16:29.028 INFO [1] org.openqa.grid.selenium.GridLauncher - Selenium Grid node is up and ready to register to the hub
17:16:29.222 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - Starting auto registration thread. Will try to register every 5000 ms.
17:16:29.222 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - Registering the node to the hub: http://10.1.12.19:4444/grid/register
17:16:29.284 INFO [16] org.openqa.grid.internal.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
17:16:54.914 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@69531aa9, browserName=safari, javascriptEnabled=true, exclude=[Automation_Tests/suite_Logon/tst_LH_L_0006.js, Automation_Tests/suite_Logon/tst_LH_L_0007.js, Automation_Tests/suite_Logon/tst_LH_L_0008.js, Automation_Tests/suite_Logon/tst_LH_L_0009.js], handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]])
17:16:55.026 INFO [21] org.openqa.selenium.remote.server.DefaultDriverProvider - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@69531aa9, browserName=safari, javascriptEnabled=true, exclude=[Automation_Tests/suite_Logon/tst_LH_L_0006.js, Automation_Tests/suite_Logon/tst_LH_L_0007.js, Automation_Tests/suite_Logon/tst_LH_L_0008.js, Automation_Tests/suite_Logon/tst_LH_L_0009.js], handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]`

**WDIO CONFIG**
`    specs: [
        'Automation_Tests/suite_Logon/**',
    ],
    // Patterns to exclude.
    // exclude: [
    // ],
    capabilities: [
        {
            browserName: 'safari',
            exclude: [
                'Automation_Tests/suite_Logon/tst_LH_L_0006.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0007.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0008.js',
                'Automation_Tests/suite_Logon/tst_LH_L_0009.js'
            ]
        }
    ],`

**Comment by barancev** [comment]
Webdriver.io is a third-party product not developer by the Selneium team. Please report this issue to the webdriver.io tracker.
