### ISSUE TITLE
Feature Docker images more prominently

### ISSUE THREAD

**Issue by alexpdp7** [SeleniumHQ/selenium#1567]
Hi,

While trying to set up our continuous integration environment to run Protractor tests we were somewhat stuff setting up Selenium- we try to have all of our infrastructure as code and for Selenium that's not trivial. However, after banging our heads for a while, we found out that you provide some official Docker images which work beautifully out-of-the-box and which we could add to our infrastructure trivially.

We would like to suggest featuring them more prominently, as they can be immensely helpful for newcomers- perhaps on the download page?

Cheers,

Álex

**Comment by barancev** [comment]
It's a good issue to discuss on https://groups.google.com/forum/#!forum/selenium-developers
