### ISSUE TITLE
Hi,I am new to selenium webdriver,I have written sample code for opening google website in eclipse.It executed.But now what to do next,how I can create automation scripts and do practice

### ISSUE THREAD

**Issue by truptigsv3** [SeleniumHQ/selenium#1570]

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by truptigsv3** [comment]
How to post question on given link-selenium user group?
