### ISSUE TITLE
Allow peristent profile for FirefoxProfile

### ISSUE THREAD

**Issue by serphacker** [SeleniumHQ/selenium#1572]
You can specify a profile template when you create a new FirefoxProfile and FirefoxProfile.layoutOnDisk() return a temporary files which is a copy of the profile.

It is good for isolated unit testing. But selenium may be used for other things than unit testing, and one wants to use persistent profile so data like sessions, cookies, caching and local storage may be saved in the profile after selenium shutdown.

**Comment by lukeis** [comment]
we won't be changing this behavior, you can certainly subclass FirefoxProfile and change the behavior of the methods though.

Also you might want to look into how Marionette handles the profiles (I'm not certain, i haven't checked)
