### ISSUE TITLE
Selenium IDE does not mouseMove or mouseOver elements

### ISSUE THREAD

**Issue by ajavalera** [SeleniumHQ/selenium#1576]
This is a known issue, but nobody seems to be addressing it and it renders Selenium IDE virtually useless.

When adding a mouseMove/mouseOver command(s), the hidden elements that should become visible on hover remain hidden.

Using the same command in PHPSelenium works just fine.

How can we fix this??

Thanks.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
