### ISSUE TITLE
EventFiringWebDriver's interaction with Navigating/Nagivated when clicking

### ISSUE THREAD

**Issue by joshuaduffy** [SeleniumHQ/selenium#1577]
Afternoon,

I'm using the [EventFiringWebDriver](https://github.com/SeleniumHQ/selenium/blob/75b9300def2854cb1ab01bab6a15206b665da5ad/dotnet/src/support/Events/EventFiringWebDriver.cs#L32) to listen for navigation events via the use of Navigating and Navigated event handlers.

When I `.click()` on a `WebElement` that causes navigation, then none of the `Navigating` or `Navigated` events are triggering.

It is my understanding that `.click()` is a non-blocking event when it is a native event, [This](https://code.google.com/p/selenium/wiki/AdvancedUserInteractions) seems to go into a lot of detail around native and synthetic events, so in my example below I tried out `ChromeDriver`, `FirefoxDriver` and `InternetExplorerDriver` as all three seem to handle this differently - however, all three drivers exhibit the same result.

In my example below I am using the `ElementClicking` and `ElementClicked` events, they seem to trigger (I assume its because the event is fired before and after the blocking phase?)

Am I going about this the wrong way, or are the `Navigated` and `Navigating` events just not available if it was a `.click()` that caused the navigation?

	using System;
	using System.Drawing;
	using OpenQA.Selenium;
	using OpenQA.Selenium.Chrome;
	using OpenQA.Selenium.Firefox;
	using OpenQA.Selenium.IE;
	using OpenQA.Selenium.Support.Events;
	using OpenQA.Selenium.Support.PageObjects;
	using Xunit;

	namespace EventFiringExample
	{
		public class EventFiringTest
		{
			[FindsBy(How = How.Id, Using = "menu-item-11")]
			public IWebElement AboutElement;

			[FindsBy(How = How.Id, Using = "menu-item-10")]
			public IWebElement ProjectsElement;

			private EventFiringWebDriver EventDriver { get; }

			public EventFiringTest()
			{
				EventDriver = new EventFiringWebDriver(new InternetExplorerDriver());

				EventDriver.ElementClicking += EventDriverOnElementClicking;
				EventDriver.ElementClicked += EventDriverOnElementClicked;
				EventDriver.Navigating += EventDriverOnNavigating;
				EventDriver.Navigated += EventDriverOnNavigated;

				EventDriver
					.WrappedDriver
					.Navigate()
					.GoToUrl("https://joshuaduffy.org");

				EventDriver.WrappedDriver.Manage().Window.Size = new Size(1024, 768);

				PageFactory.InitElements(EventDriver, this);
			}

			private void EventDriverOnElementClicking(object sender, WebElementEventArgs e)
			{
				Console.WriteLine("Clicking");
			}

			private void EventDriverOnElementClicked(object sender, WebElementEventArgs e)
			{
				Console.WriteLine("Clicked");
			}

			private void EventDriverOnNavigating(object sender, WebDriverNavigationEventArgs e)
			{
				Console.WriteLine("Navigating");
			}

			private void EventDriverOnNavigated(object sender, WebDriverNavigationEventArgs e)
			{
				Console.WriteLine("Navigated");
			}

			[Fact]
			public void Main()
			{
				AboutElement
					.Click();
			}
		}
	}

**Comment by jimevans** [comment]
The `Navigated` and `Navigating` events are only fired when you explicitly navigate using the API. They are not fired when the navigation is caused by a click on an element.

**Comment by joshuaduffy** [comment]
Understood, cheers. Thank you for the quick response!
