### ISSUE TITLE
C# implementation of RemoteWebDriver fails to install browser extensions

### ISSUE THREAD

**Issue by jarekb84** [SeleniumHQ/selenium#1578]
Installing and configuring an extension works when using a local driver as described [here](https://support.saucelabs.com/customer/en/portal/articles/2200902-creating-custom-firefox-profiles-and-chrome-instances-for-your-automated-testing). Doing the same using the C# implementation of RemoteWebDriver does not. Tested this with both Firefox and Chrome. 

In my test case, the remote execution was done against SauceLabs. Contacted their support and they verified that installing extensions via RemoteWebDriver works in the JAVA implementation, but fails using the C# implementation. #To quote from their support ticket:

> I was able to verify this by running a sample test to load the Modify Headers and Firebug extensions in a custom Firefox profile locally(with C#/Selenium) as well as through a C# and Java test. Both the local test which uses the Firefox Driver and the Java Sauce test using RemoteWebDriver passed and adds the extensions to the FF browse. But the C# Sauce test using RemoteWebDriver doesn’t load the profile despite using the same code as the local test.

**Setup**
Tested with Selenium.WebDriver v2.48.2, v2.49.0, and v2.50.1, against Windows 7 and 10, using Firefox 43 and Chrome 47.

Here's the C# test setup for Firefox using this [extension](https://addons.mozilla.org/firefox/downloads/latest/967/addon-967-latest.xpi)

	private static FirefoxProfile CreateFirefoxProfile()
	{
		FirefoxProfile profile = new FirefoxProfile();
		profile.AddExtension("Tools/modify_headers-0.7.1.1-fx.xpi");
		profile.SetPreference("general.useragent.override", "UA-STRING");
		profile.SetPreference("extensions.modify_headers.currentVersion", "0.7.1.1-signed");
		profile.SetPreference("modifyheaders.headers.count", 1);
		profile.SetPreference("modifyheaders.headers.action0", "Add");
		profile.SetPreference("modifyheaders.headers.name0", "SampleHeader");
		profile.SetPreference("modifyheaders.headers.value0", "test1234");
		profile.SetPreference("modifyheaders.headers.enabled0", true);
		profile.SetPreference("modifyheaders.config.active", true);
		profile.SetPreference("modifyheaders.config.alwaysOn", true);
		profile.SetPreference("modifyheaders.config.start", true);

		return profile;
	}

	private static IWebDriver GetRemoteDriver()
	{
		var capabilities = new DesiredCapabilities();

		var profile = CreateFirefoxProfile();

		capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile);

		capabilities.SetCapability("name", buildContext);
		capabilities.SetCapability(CapabilityType.BrowserName,"firefox");
		capabilities.SetCapability(CapabilityType.Version,"");
		capabilities.SetCapability(CapabilityType.Platform, "Windows 10");
		capabilities.SetCapability("screen-resolution", "1280x1024");
		capabilities.SetCapability("username", "SaucelabsUserName");
		capabilities.SetCapability("accessKey", "SaucelabsAccessKey");
		capabilities.SetCapability("build", "BuildNumber");

		return new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com/wd/hub"), capabilities);
	}

**Comment by jimevans** [comment]
In the `RemoteWebDriver` case for .NET, you need to use the `ToBase64String()` method. Thus, changing your `GetRemoteDriver` method above to the following:
```
private static IWebDriver GetRemoteDriver()
{
    var capabilities = new DesiredCapabilities();

    var profile = CreateFirefoxProfile();

    // Note the change here, calling .ToBase64String()
    capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile.ToBase64String());

    capabilities.SetCapability("name", buildContext);
    capabilities.SetCapability(CapabilityType.BrowserName,"firefox");
    capabilities.SetCapability(CapabilityType.Version,"");
    capabilities.SetCapability(CapabilityType.Platform, "Windows 10");
    capabilities.SetCapability("screen-resolution", "1280x1024");
    capabilities.SetCapability("username", "SaucelabsUserName");
    capabilities.SetCapability("accessKey", "SaucelabsAccessKey");
    capabilities.SetCapability("build", "BuildNumber");

    return new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com/wd/hub"), capabilities);
}
```
This should resolve the issue. Note that this is one of the reasons that other drivers have type-safe options classes instead of passing raw capabilities. Future versions of the .NET bindings should extend this pattern to Firefox as well, removing this as an issue in the future.

**Comment by jarekb84** [comment]
Thanks @jimevans that resolved the problem for me.

**Comment by nadvolod** [comment]
What about for Chrome, I'm running into the same issue with Chrome and I don't see the ToBase64String() method on the ChromeOptions. Here is what I'm trying

        private IWebDriver GetSauceLabsDriver()
        {
            var outPutDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            ChromeOptions options = new ChromeOptions();
            options.AddExtensions(outPutDirectory + @"\3.1.3_0.crx");

            var caps = new DesiredCapabilities();
            caps.SetCapability(ChromeOptions.Capability, options.ToString());

            caps.SetCapability(CapabilityType.BrowserName, "chrome");
            caps.SetCapability(CapabilityType.Version, "53.0");
            caps.SetCapability(CapabilityType.Platform, "Windows 10");
            caps.SetCapability("deviceName", "");
            caps.SetCapability("deviceOrientation", "");
            caps.SetCapability("username", "na");
            caps.SetCapability("accessKey", "-9cd6-438e-8d58-a9635b70953d");
            caps.SetCapability("name", TestContext.CurrentContext.Test.Name);

            return new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com:80/wd/hub"), caps,
                TimeSpan.FromSeconds(600));
        }
