### ISSUE TITLE
Export browsers memory profilers via webdriver

### ISSUE THREAD

**Issue by evilaliv3** [SeleniumHQ/selenium#1579]
It would be valuable if selenium could export the memory profilers of the different browsers and possibly would try to uniform their API.

This would make possible for users to track memory allocations verifying memory leaks and other issues while doing automatic testing.

Probably what would be simple to be impleneted trting to get support in all the various browsers is to have simply an API like Node ```process.memoryUsage()``` that exports rss and heapUsage: https://nodejs.org/api/process.html#process_process_memoryusage

This would make possible to implement retesting on critical applications like we are trying to do in [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) and [OpenPGP.js](https://github.com/openpgpjs/openpgpjs): https://github.com/openpgpjs/openpgpjs/issues/403

**Comment by barancev** [comment]
Feature proposals are welcome to selenium developer list
https://groups.google.com/forum/#!forum/selenium-developers
