### ISSUE TITLE
Proposal for using github releases to provide the latest .jar

### ISSUE THREAD

**Issue by javigomez** [SeleniumHQ/selenium#1580]
Hi,

Right now the .jar are uploaded to http://selenium-release.storage.googleapis.com/index.html, but I would  suggest to use (not as alternative but as a second possibility) to upload the JAR to the release:

![capture 2016-02-03 at 13 44 42](https://cloud.githubusercontent.com/assets/1375475/12782555/4dfb1c76-ca7c-11e5-90c0-982ea8f7214e.png)

That way we could easily download with:

https://github.com/SeleniumHQ/selenium/releases/releases/latest

or with the Github Releases API https://developer.github.com/v3/repos/releases/#get-the-latest-release

how does it sound?

**Comment by ddavison** [comment]
I like the idea of it.  i had thought about implementing this as well, but i'm too unfamiliar with github releases.  are you able to upload files arbitrarily to a release?

**Comment by ddavison** [comment]
looks like you can!  
<img width="890" alt="screenshot at feb 03 11-19-18" src="https://cloud.githubusercontent.com/assets/2972876/12788578/023231e4-ca68-11e5-9d43-65d2224abcee.png">

I like it.  @SeleniumHQ/selenium-committers  ?

**Comment by lukeis** [comment]
not everyone wants (or even likes, or reads) github issues as a forum for decisions ;)

can we move this discussion to the mailing list:

https://groups.google.com/forum/#!forum/selenium-developers

**Comment by ddavison** [comment]
@javigomez , go ahead and put a new forum post on that link luke had mentioned.  I'll +1 it.

**Comment by javigomez** [comment]
Thanks :smile:  @ddavison and @lukeis. I have just created at the forum. Is pending moderation.
