### ISSUE TITLE
Webdriver Issues With Firefox since v2.48.0

### ISSUE THREAD

**Issue by pataky** [SeleniumHQ/selenium#1581]
Since the 2.48 version of webdriver we are experienceing a lot of issues in the behaviour.
- On the site we test there is a mouse over drop-down menu which opens when we try to click near to that on an element. WebDriver throws an WebDriverException because the elemet is not clickable at this point. (I see this is because a change). It's a really strang behaviour there is nothing on the code which triggers the drop-down should be opened. I am not fully aware how webdriver works and what has changed since v2.47 but we don't faced with this earlier. 
- Besides we have a lot of failing tests because WebDriver doesn't wait for the page to be completly loaded. E.g. we want to check the presence of an error message after clicked on a button. In the 2.47 version it worked properly but know it fails.

**Comment by barancev** [comment]
1) Try the latest that is 2.50.1 at the moment.

2) For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
try again with the latest 2.51 most cases should be fixed now. If not, please provide a reproducible test case and we can reopen the issue.
