### ISSUE TITLE
Issue with frameToBeAvailableAndSwitchToIt function in IE

### ISSUE THREAD

**Issue by g-one** [SeleniumHQ/selenium#1583]
Using ExpectedConditions.frameToBeAvailableAndSwitchToIt("framename") works well in Chrome and Firefox  but on IE 8, its throwing the following error:

*_org.openqa.selenium.WebDriverException: A JavaScript error was encountered executing the findElements atom.
*_\* Element info: {Using=css selector, value=frame[name='docBodyIframe'],iframe[name='docBodyIframe']} **

**Verison WebDriver: 2.48.2**

Thanks,
Jeevan

**Comment by jimevans** [comment]
What version of `IEDriverServer.exe`? If it's less than 2.50.0, please update and retry.

**Comment by g-one** [comment]
I'm using 2.50 only but still getting the same issue.

**Comment by jimevans** [comment]
Please post a log file from `IEDriverServer.exe` from a simple case reproducing your issue. To be most effective, the log should use the `TRACE` logging level.

**Comment by g-one** [comment]
Well i ran it again and it did passed but other test cases which was passed earlier failed for the same reason(findElements Atom issue) though not for the **switchtowindow** but unable to find simple element By.id
 
Error
Message 
**A JavaScript error was encountered executing the findElement atom. (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 2.09 seconds Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:55:52' System info: host: 'qatest9', ip: '10.206.147.23', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_66' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=8, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:10073/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}] Session ID: ffe72c91-2da7-459b-a72d-0e829a5d2c5f 
# *** Element info: {Using=id, value=timeTrack} **


Unable to log the iedriver log since we are using the API's from the other teams, working on that. 
Once i get that i will post the same.

Thanks,
Jeevan

**Comment by jimevans** [comment]
No comment in a year. Closing.
