### ISSUE TITLE
Selenium with chrome hangs because it is using too much ports

### ISSUE THREAD

**Issue by ABFonseca** [SeleniumHQ/selenium#1585]
Hi,

I am dealing with a issue that really seems to be the same as https://code.google.com/p/selenium/issues/detail?id=2492 which is mentioned as fixed since Oct 2011.

I am using Apache nutch (1.11) with selenium (2.48.2) using chrome driver (with chrome on version 48.0.2564.103) to crawl a list of specific URLs.
It all works fine for a while and I see for each page fetched the line:
Starting ChromeDriver 2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a) on port X

where the port keeps changing. after a while all the fetch threads hung and it seems to be related to errors on ports being in use:
[0.491][SEVERE]: bind() returned an error, errno=98: Address already in use

I can't see any more issues/errors/exceptions so I really hope this information can lead us somewhere.
Am I doing something wrong with my setup? 
Do you know of this issue?
Is there a way to go around it?

Thank you
António

**Comment by ABFonseca** [comment]
Hi, 

I noticed the code.google issue page is not available but the code change in github is the following: https://github.com/SeleniumHQ/selenium/commit/7d8d45c6ddaf6fdc2291ea150cc07555982da2d2

Best regards

**Comment by barancev** [comment]
This issue has been resolved in Java binding by migration to OkHttp library.

For other bindings see #5758
