### ISSUE TITLE
The webElement is not passed to the listener on beforeFindBy and afterFindBy on WebDriverEventListener interface

### ISSUE THREAD

**Issue by tdcristian** [SeleniumHQ/selenium#1589]
When implementing beforeFindBy and afterFindBy methods on  WebDriverEventListener interface
we obtain NullPointerException. The webElement is not passed to the listener. by object is correctly passed.

   @Override
    public void afterFindBy(By by, WebElement webElement, WebDriver webDriver) {
        System.out.println("After Find By: "+by.toString()+" "+webElement.getText());
    }

**Comment by lukeis** [comment]
http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/events/WebDriverEventListener.html#afterFindBy-org.openqa.selenium.By-org.openqa.selenium.WebElement-org.openqa.selenium.WebDriver-

"element - will be null, if a find method of WebDriver is called."

The intent of the WebElement parameter is to show the element used as a reference to findBy, not the found element(s).

**Comment by KrishnB** [comment]
Code Snippet from EventFiringWebDriver.java class

`public WebElement findElement(By by) {
    dispatcher.beforeFindBy(by, null, driver);
    WebElement temp = driver.findElement(by);
    dispatcher.afterFindBy(by, null, driver);
    return createWebElement(temp);
 }`

I can see that "null" value is passed for WebElement in dispatcher.afterFindBy method instead of "temp", which causes the element to be null. Could this be the reason?

**Comment by lukeis** [comment]
Other snippet in the same class, except for the WebElement wrapper:

    public WebElement findElement(By by) {
      dispatcher.beforeFindBy(by, element, driver);
      WebElement temp = element.findElement(by);
      dispatcher.afterFindBy(by, element, driver);
      return createWebElement(temp);
    }

    public List<WebElement> findElements(By by) {
      dispatcher.beforeFindBy(by, element, driver);
      List<WebElement> temp = element.findElements(by);
      dispatcher.afterFindBy(by, element, driver);
      List<WebElement> result = new ArrayList<>(temp.size());
      for (WebElement element : temp) {
        result.add(createWebElement(element));
      }
      return result;
    }

Please re-read my previous comment @KrishnB

**Comment by KrishnB** [comment]
I get it now Thank you. WebElement is not null when we use findElement apart from WebDriver,  such as using findElement method of WebElement?

Is my understanding correct @lukeis ?
