### ISSUE TITLE
Wrong option name for tracing categories in dotnet bindings

### ISSUE THREAD

**Issue by madelh** [SeleniumHQ/selenium#1591]
When trying to add tracing categories I have the error : unrecognized performance logging option: tracingCategories in the logs

to reproduce this issue : 
```
ChromePerformanceLoggingPreferences perfLogPrefs = new ChromePerformanceLoggingPreferences(); 
perfLogPrefs.AddTracingCategory("devtools.timeline");
options.PerformanceLoggingPreferences = perfLogPrefs;

ChromeDriverService service = ChromeDriverService.CreateDefaultService();
service.LogPath = "chromedriver.log";
service.EnableVerboseLogging = true;
service.SuppressInitialDiagnosticInformation = true;
ChromeDriver driver = new ChromeDriver(service, options);
```

In the ChromeOption.cs at line 667 the option added in the dictionnary is  "tracingCategories" and I think it should be "traceCategories".
See the code example [https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log](url) under "Tracing and Custom Logging".
I was able to make tracing work with this code before the last update.
The documentation here [https://sites.google.com/a/chromium.org/chromedriver/capabilities](url) seems wrong.

**Comment by jimevans** [comment]
Fixed in d57f406
