### ISSUE TITLE
Opening hyperlink in new Tab working intermittently (Actions class)

### ISSUE THREAD

**Issue by mrunalgosar** [SeleniumHQ/selenium#1599]
Hi Team
Use case / Scenario:
I am trying to open hyperlinks in new tab using Actions class
Code:
`actions.keyDown(Keys.SHIFT).click(webElement).keyUp(Keys.SHIFT).build().perform();`
Expected:
Hyperlink should open in new Tab.
Actual:
Hyperlinks open in new tab intermittently. The above functionality is not giving consistent results. At times the link just gets selected and does not opens in new Tab.

Unit Test: Repeat below code multiple times and failure can be re-created.
```
import java.util.List;
import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

public class FFStackTest {
	public static void main(String[] args) {
		WebDriver driver=new FirefoxDriver();
		Actions actions=new Actions(driver);
		driver.manage().window().maximize();
		driver.get("http://stackoverflow.com");
		List<WebElement> elements = driver.findElements(By.xpath(".//*[text()='javascript']//ancestor::div[@class='summary']/h3/a"));
		String originalWindow=driver.getWindowHandle();
		for (WebElement webElement : elements) {
			webElement.sendKeys("");
			actions.keyDown(Keys.SHIFT).click(webElement).keyUp(Keys.SHIFT).build().perform();
			Set<String> windowHandles=driver.getWindowHandles();
			windowHandles.remove(originalWindow);
			driver.switchTo().window(windowHandles.toArray(new String[windowHandles.size()])[0]);
			System.out.println(driver.getTitle());
			driver.close();
			driver.switchTo().window(originalWindow);
		}
		driver.close();
	}
}
```

Webdriver - Firefox combinations tried so far:
Selenium Webdriver: 2.48.2.. till latest selenium 2.51.0
Firefox version: 41.0.2 till 44.

**Comment by barancev** [comment]
Tabs are explicitly not supported.

**Comment by mrunalgosar** [comment]
Hi Barancev..Agreed that opening new tabs is not supported in selenium..but then what about the sequence of actions command that I am trying to run..which is giving inconsistent behavior..lets say if in future such sequence of action needs to be invoked..then this inconsistent behavior would appear again

**Comment by barancev** [comment]
We can't (or wan't) disable sending any key sequences. Just be careful :)
