### ISSUE TITLE
Error in findElements after upgrading ie driver from 2.50

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1600]
When using findelements command got below exception

elements  = dr.findElements(By.id("one"));

iedriver version -  2.51, issue also observed with 2.50
Issue is not observed with 2.49

Below is log:-

org.openqa.selenium.WebDriverException: A JavaScript error was encountered executing the findElements atom. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 359 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'HAIND-AUTO6', ip: '192.168.136.255', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
*** Element info: {Using=id, value=auto-idTabUser}
Session ID: 19ac3ea0-b0bf-46c4-8b6c-7b4213eca52a
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=false, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=accept, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=true, requireWindowFocus=false, initialBrowserUrl=http://localhost:41531/, handlesAlerts=true, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
2016-02-08 13:02:20 INFO  REP_DYN_1039_UpdateProcessCube:52 - A JavaScript error was encountered executing the findElements atom. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 359 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'HAIND-AUTO6', ip: '192.168.136.255', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
*** Element info: {Using=id, value=auto-idTabUser}
Session ID: 19ac3ea0-b0bf-46c4-8b6c-7b4213eca52a
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=false, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=accept, version=11, pageLoadStrategy=normal, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=true, requireWindowFocus=false, initialBrowserUrl=http://localhost:41531/, handlesAlerts=true, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsById(RemoteWebDriver.java:421)
	at org.openqa.selenium.By$ById.findElements(By.java:210)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:351)

**Comment by jimevans** [comment]
Thanks for providing a stack trace here. However, this is not universally broken for all usage of finding elements in the IE driver. You'll need to provide code, executing against either a public page or an HTML page that you provide, that reproduces the error for us to have any hope of fixing this.

**Comment by jimevans** [comment]
After further reviewing the stack trace, I see you're using the `INTRODUCE_FLAKINESS` capability. We can do no further diagnosis on this issue while you're using that setting. Please remove it, and provide the required repro case (including page to test against).
