### ISSUE TITLE
Unable to upload file using fileUpload command in IE

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1601]
dr.fileUpload(By.id("one"))

In IE 
when executing above command "Browse" dialog is opened and path is not entered it stays upto 360 mins (6 hrs)
Provided correct file path and after execution of about 360 mins(6 hrs) no error is displayed
and to close(or quit) the driver it takes 180 min(3 hrs) showing unreachablebrowser exception for closing the driver.

For Browser dialog - no error displayed - 6 hrs
after 6 hrs
To quit or close - unreachablebrowser exception displayed - 3hrs

**Comment by jimevans** [comment]
What is the `fileUpload` method you're referring to here? There is no such method in the documented Java API, nor can I find it in the [source code](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java).
