### ISSUE TITLE
Website added under compatibility view settings lost when launching IE by setting clean session capability

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1602]
Manually launched IE and set compatibility for website under test

ie.ensureCleanSession , true
after setting above capability and run the test , observed that
Website added under Compatibility view settings also removed.
Provide a work around so that website under Compatibility view settings retained
with inclusion on ensurecleansession capability

**Comment by jimevans** [comment]
Sites added under Compatibility Mode is one piece of data that is explicitly cleared by the browser when browser history is deleted. This is part of what you've asked for when specifying a clean session. The driver won't be modified to allow users to control this with any more granularity than is already available. However, as a workaround, you're welcome to execute 

    rundll32.exe inetcpl.cpl, ClearMyTracksByProcess <flagValue>

Values for `flagValue` can be found in the [IE driver source code](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/BrowserFactory.h).
