### ISSUE TITLE
System.InvalidOperationException in PageFactory.InitElements

### ISSUE THREAD

**Issue by darthKwisatzHaderach** [SeleniumHQ/selenium#1607]
In my project I use C#, Selenium WebDriver with Support classes and NUnit 3.0 framework.
I have many tests and these tests uses pages. I create instances of pages in SetUp section of my tests. 

```
	[SetUp]
	public void SetUpBaseProjectTest()
	{
		_projectsPage = new ProjectsPage(Driver);
		_deleteDialog = new DeleteDialog(Driver);
    }

    [Test]
    public void CreateProjectTest()
    {
         _projectsPage.CreateProject();
```

Each page have a constructor where I placed initialization of page elements (PageFactory.InitElements).

```
	public class ProjectsPage
	{
		public WebDriver Driver { get; protected set; }

		public ProjectsPage(WebDriver driver)
		{
			Driver = driver;
			PageFactory.InitElements(Driver, this);
		}

```
When I run my tests in parallel using NUnit 3.0, I get an error:

> System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
>  at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>  at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateTypeForASingleElement()
>  at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.get_InterfaceProxyType()
>  at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.CreateProxyObject(Type memberType, IElementLocator locator, IEnumerable`1 bys, Boolean cache)
>  at OpenQA.Selenium.Support.PageObjects.DefaultPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
>  at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)

I think the error occurs due to the parallel tests execution. It is a bug in a Selenium framework or in my test project? How to avoid this error?

Selenium Webdriver DotNet 2.47.0

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by LuisMiguelFilipe** [comment]
@darthKwisatzHaderach, @ronaldkroon I have just created a PR aimed at solving the problem stated in this unfortunately-closed-issue
