### ISSUE TITLE
JQuery Mobile Checkbox click issue with Selenium WebDriver DotNet 2.51.0 for Firefox

### ISSUE THREAD

**Issue by bencovington** [SeleniumHQ/selenium#1608]
To reproduce the issue, go to the following url: 

http://demos.jquerymobile.com/1.4.5/checkboxradio-checkbox/

and try to click the checkbox named: "checkbox-0 " with Selenium WebDriver DotNet 2.51.0 for Firefox.

Code:

            driver.Navigate().GoToUrl("http://demos.jquerymobile.com/1.4.5/checkboxradio-checkbox/");

            WaitUntilExists("Minisize", driver);

            driver.FindElement(By.Name("checkbox-0 ")).Click();

            Assert.IsTrue(driver.FindElement(By.Name("checkbox-0 ")).Selected, "Error: the checkbox is not checked.");

Error:

OpenQA.Selenium.WebDriverException : Unexpected error. Element is not clickable at point (34.44999694824219, 504.70001220703125). Other element would receive the click: `<label class="ui-btn ui-corner-all ui-btn-inherit ui-btn-icon-left ui-checkbox-off"></label>`

The code runs as expected with version 2.48.1 of Selenium WebDriver DotNet for Firefox

Thanks.

**Comment by barancev** [comment]
Yes, the checkbox is entirely overlapped by a label. It is not clickable. One should click the label instead.

**Comment by bencovington** [comment]
Oh I see... so I guess I must tell my users that what they see and what they are trying to click is NOT a checkbox but a label! :D

Is there a way to get back to the previous behaviour or do I have to rewrite all my tests because "fancy checkboxes" are not clickable anymore?

**Comment by barancev** [comment]
You'll be wondered, but your uses click the label BUT not the checkbox :)

Just try to set the checkbox style to "display:none" and watch the page -- there will be no visual changes, and you'll be able to click something that looks like a checkbox, but why, it's hidden! It's the lable that mimic the checkbox view, and confused users click the label instead of the checkbox.

No, we're not going to revert the behaviour. Clicking invisible elements is not allowed.

**Comment by bencovington** [comment]
Alright, could you at least consider giving the choice to your users to "disable" this specific error and make WebDriver click the label instead? Me (for sure) and many other WebDriver users (I guess) would be eternally grateful to you! :D

**Comment by barancev** [comment]
The requested behavior was implemented in Selenium 2.49 and many-many users demanded to get rid of it and throw an exception instead :) They were not grateful.

Yes, there is a plan to implement a switch. But there is a chance FirefoxDriver will be totally destroyed by FF45 and we'll all of a sudden be forced to use MarionetteDriver instead.

**Comment by bencovington** [comment]
My point is that the simple code example I provided you stopped working because a requested behavior was implemented without giving the chance to other users to disable it and keep their existing code unchanged.

I know it's impossible to please everyone... but breaking changes like that are a bit frustrating.

So, until a switch (or a new version based on MarionnetteDriver) is implemented, i'll keep using version 2.48.1 while it works with the latest versions of Firefox.

Thank you for your time and your valuable explanations.

**Comment by barancev** [comment]
Done: ab994066135f81b43d6ebed93bb398e7c7d064c1

**Comment by bencovington** [comment]
You have my eternal gratitude... but you already knew it! ;))
