### ISSUE TITLE
Selenium webdriver v.246.0 doesn't work with firefox v44.0.x

### ISSUE THREAD

**Issue by anapsousa** [SeleniumHQ/selenium#1609]
Selenium webdriver stopped working after firefox made me update the version on the browser. It used to work ok when I used version 35.x of firefox, now it doesn't handle the window after it is opened.

**Comment by gssatcc** [comment]
Current version is 2.51.0. Please update.

**Comment by anapsousa** [comment]
Thank you! I didn't noticed the update. Sorry for that

**Comment by santosh1890** [comment]
Hello,

I have updated the current version of web driver 2.51.0 and also I have updated the latest firefox versio to 44,it doesn't handle the window after it is opened.

Can any body plz help me out in solving the issue.

**Comment by gssatcc** [comment]
OS, code example?
