### ISSUE TITLE
Maximise browser window on Linux has no effect

### ISSUE THREAD

**Issue by peterwippermann** [SeleniumHQ/selenium#1610]
I'm maximising the browser window during my tests:
`myDriver.manage().window().maximize();`

This works fine on my local Windows machine, but doesn't work on our CI machine, which runs Linux.

I found an old bug report for this, which has been closed for no real reason:
https://code.google.com/p/selenium/issues/detail?id=6775

Could we please try to get this problem solved?
Resizing the window to the screen's size isn't exactly the same as maximise and brings new problems.

**Comment by lukeis** [comment]
please provide more details for us to reproduce the problem. Which browser(s) and version(s)? What's the OS version? Are you using Xvfb or what is the X software you're using?

**Comment by peterwippermann** [comment]
I thought the information of the old bug ticket might be enough. But yes of course, here are my details:

- OS: Cent OS 6.5
- Browser: Firefix 43.0.4

I'm starting the display with the following command: `Xvfb :99 -screen 0 1920x1080x24 &`
I guess it's not important, but I'm watching the execution remotely by running x11vnc and connecting via the RealVNC viewer.

**Comment by molsky** [comment]
> I'm starting the display with the following command: Xvfb :99 -screen 0 1920x1080x24 &
I guess it's not important, but I'm watching the execution remotely by running x11vnc and connecting via the RealVNC viewer.

Have you any window manager set up for XVFB? We had once similar problem and found out that window manager is needed so we installed Fluxbox and configured our project to use XVFB with Fluxbox.

**Comment by peterwippermann** [comment]
Thanks for the advice, @molsky . Indeed this also worked for us.

So my xfvb call looks like this:

> Xvfb :99 -screen 0 1920x1080x24 & fluxbox &
