### ISSUE TITLE
Firefox does not list tabs in getAllWindowHandles

### ISSUE THREAD

**Issue by juliemr** [SeleniumHQ/selenium#1614]
If a test opens up a new tab (or a new tab is opened manually), it will not be listed in the return from `getAllWindowHandles` in FireFox. Chrome correctly lists all tabs.

Here's a repo showing a reproduction: https://github.com/prbaron/protractor-demo-tab

Note that FireFox will correctly return handles for new *windows*. 

The spec says that window handles should be returned for each "top level browsing context." I'm not a spec expert, but I would think that a new tab would qualify.

**Comment by juliemr** [comment]
Firefox version: 43.0.4

Selenium standalone version: 2.51.0

**Comment by titusfortner** [comment]
Yes, tabs are explicitly not supported in the current Firefox driver.

**Comment by jimevans** [comment]
A little further explanation. In the context of the specification, "top level browsing context" would, in fact, refer to a new tab or a new window, as long as the driver was responsible for creating the browsing context. In the case of clicking on a link that opens a new window (via `target=_blank` or a similar mechanism, the driver will know about those windows or tabs. The case of attempting to control+click (or command+click) a link to open it in a new tab circumvents the driver's mechanism for creating new top-level browsing contexts. Thus, such new tabs or windows are not managed by the driver.

**Comment by juliemr** [comment]
Thanks @jimevans for the full explanation!

**Comment by jleyba** [comment]
Stop command clicking to force a new tab.

@andreastt @AutomatedTester do you know what extra preferences we need to set to prevent users from opening new tabs?

**Comment by andreastt** [comment]
At a conceptual level it would be nice if all drivers could handle new top-level browsing contexts (windows+tabs), either accidental or deliberate. Certainly from the specification point of view, the assumption is that drivers are supposed to be able to deal with unknown top-level browsing context. It doesn’t currently describe restrictions for what windows can be interacted.

@jleyba I haven’t tried it yet, but maybe `browser.link.open_newwindow.restriction` or something similar could be used to prevent accidental opening in drivers that don’t support this.

**Comment by jleyba** [comment]
I agree, but the FirefoxDriver explicitly only handles windows. At this point, trying to change that will likely require changes throughout the driver and isn't worth the cost. On the other hand, if we can completely disable tabs with preferences, that's just a few extra lines.

**Comment by andreastt** [comment]
I’m in agreement, for FirefoxDriver it definitely makes sense to impose such a restriction.

It looks like setting `browser.link.open_newwindow` to 1 partially solves the problem: `_target="blank"` is is stopped from creating a new window. According to [ancient tales](http://kb.mozillazine.org/Browser.link.open_newwindow.restriction) it can be tweaked further with the `browser.link.open_newwindow.restriction` preference I mentioned above.

**Comment by writetocynthia** [comment]
ok i found a workaround which works for both firefox and chrome. Please NOTE : This is specifically if you are clicking on a link to open a tab. My problem got solved when I opened in a new window. I really didnt mind a tab or a window.  I used 
```
browser.actions()
                                  .keyDown(protractor.Key.SHIFT)
                                  .click(element(by.linkText(text)))
                                  .keyUp(protractor.Key.SHIFT)
                                  .perform()
```

instead of 
```
browser.actions()
                                  .keyDown(protractor.Key.COMMAND)
                                  .click(element(by.linkText(text)))
                                  .keyUp(protractor.Key.COMMAND)
                                  .perform()
```

**Comment by shs96c** [comment]
The only reason the FirefoxDriver doesn't support tabs is because I couldn't figure out how to make it do that. As such, I just forced the browser to open new tabs in all cases because there was a firefox option to make that happen.

Really, all drivers should treat all top-level browsing contexts (be they windows or tabs) identically and indistinguishably. Because, that's what a user does.

**Comment by sumitsharma15** [comment]
Hi,

I have one issue with IEDriver. In my application when multiple window opened with IE driver and when i am trying to get all window handles, it is returning only 1 value in Set<String>. I am using the latest version of IEDriver.exe file 64-bit. Latest Selenium Server and IE11 browser. Please help me in this as i am stuck to automate application.

**Comment by writetocynthia** [comment]
@sumitsharma15  did you try to add a wait and then try getting the windowhandles? Sometimes it takes a while for the window to open and your getwindowhandles might return only 1 value. add a wait and let us know if that resolved.

**Comment by anish-sekar** [comment]
@writetocynthia ,Im facing the same issue and we tried adding wait after invoking the new window.
- below the snippet what we tried,
> var handlePromise = browser.driver.getAllWindowHandles();
> handlePromise.then(function (handles) { 
 >           console.log('Length='+handles.length);
> });
- below was the output we got
> Length=1
- Steps to reproduce the bug
Run the protractor test using the IE Driver, try to use the function **getAllWindowHandles()**

. However when the same snippet is run using Chrome Driver, it returns the correct number of windows.  (I'm pretty sure that this is an issue with the IE Driver, but could someone tell me how to fix this?)
