### ISSUE TITLE
WebDriver Promises Sealed

### ISSUE THREAD

**Issue by ajaykodali** [SeleniumHQ/selenium#1615]
Is there a reason why WebDriver promises are sealed in the 2.48.x versions? This essentially breaks chai-as-promised functionality around "assert.eventually" calls. We now see an error,

"TypeError: Can't add property notify, object is not extensible"

Can also refer to this discussion here - https://github.com/domenic/chai-as-promised/pull/138

**Comment by jleyba** [comment]
Won't be an issue in the next release.

**Comment by ajaykodali** [comment]
@jleyba Thank you. Is there a timeline as to when the next release might happen?

**Comment by jleyba** [comment]
Either tonight or tomorrow depending on the final round of testing

**Comment by ajaykodali** [comment]
Awesome! Thanks.
