### ISSUE TITLE
homebrew install of chromedriver is into /usr/local/bin/

### ISSUE THREAD

**Issue by ph-hs** [SeleniumHQ/selenium#1618]
Hardcore Mac devs can install chromedriver through regular (non cask) homebrew, and stay abreast of releases through standard `brew upgrade`. The binary goes into /usr/local/bin/ 

WebDriver could well look there, if paths are not inherited by launching processes.

```bash
$ which chromedriver 
$ brew install chromedriver
==> Downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_ma
Already downloaded: /Library/Caches/Homebrew/chromedriver-2.21.zip
==> Caveats
To have launchd start chromedriver at login:
  ln -sfv /usr/local/opt/chromedriver/*.plist ~/Library/LaunchAgents
Then to load chromedriver now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.chromedriver.plist
==> Summary
🍺  /usr/local/Cellar/chromedriver/2.21: 3 files, 11M, built in 2 seconds
$ which chromedriver 
/usr/local/bin/chromedriver
```

**Comment by lukeis** [comment]
"Hardcore Mac devs" should know to properly export a PATH :)

I don't think we're going to make such accommodations for homebrew. More things will continue to be added to homebrew (maybe 'wires' aka marionette for firefox). It seems reasonable for homebrew users to properly export their PATH or log a bug with homebrew to do it for them (which I wonder why it doesn't?)
