### ISSUE TITLE
elementeScrollBehavior does not work with actions

### ISSUE THREAD

**Issue by oligee80** [SeleniumHQ/selenium#1619]
I successfully tested the elementScrollBehavior capability and it works, but only if you don't use Actions!

webElement.click(); >>> scrolls to bottom if it is set to 1
new Actions(driver).click(webElement).build().perform(); >>> scrolls always to the top

If you try this code you will see that it will always scroll to the top if you use actions:

```
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, 1);
FirefoxDriver driver = new FirefoxDriver(desiredCapabilities);
WebElement webElement = driver.findElement(By.cssSelector("div.selenium-sponsors a"));

// always scrolls to the top
new Actions(driver).click(webElement).build().perform();

// scrolls to the bottom
//webElement.click();
```

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
