### ISSUE TITLE
SELECTing an item not working in FF-42.0 with Selenium Standalone & JAVA - JAR 2.50.1 and above

### ISSUE THREAD

**Issue by ififthelement** [SeleniumHQ/selenium#1626]
There is a script that worked pretty well with Selenium Standalone/JAVA JAR v 2.48 and FF-42.0. In this combination It Selects the item in the list correctly. 
Used a very simple command selectbyVisibleText("text to be selected") , of SELECT element , found by ID 

Now that we have FF v 44 and Selenium Standalone & JAVA - JAR 2.50.1 and 2.52 .The same has stopped selecting the item in the list, after upgrading to the new combination. I have tried the new Updates with FF v 42.0, still doesnt work.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
