### ISSUE TITLE
selenium-webdriver for Node.js gives an error when using standalone Selenium server

### ISSUE THREAD

**Issue by denvned** [SeleniumHQ/selenium#1628]
The latest version (2.52.0) of [selenium-webdriver](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver) for Node.js produces the following error when used with different versions (I tried 2.51.0 and 2.52.0) of standalone Selenium server.

**Selenium server log:**

> 08:29:49.522 WARN - Exception thrown
> java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
> 	at org.openqa.selenium.remote.server.handler.NewSession.setJsonParameters(NewSession.java:53)
> 	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:99)
> 	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
> 	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:202)
> 	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:164)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:130)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
> 	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
> 	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
> 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
> 	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
> 	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
> 	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
> 	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
> 	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
> 	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
> 	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
> 	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)

***selenium-webdriver* log:**

> WebDriverError: java.util.ArrayList cannot be cast to java.util.Map
> at WebDriverError (node_modules/selenium-webdriver/error.js:27:10)
> at Object.checkLegacyResponse (node_modules/selenium-webdriver/error.js:580:13)
> at node_modules/selenium-webdriver/lib/webdriver.js:64:13
> at Promise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1329:14)
> at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2790:14)
> at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2773:21)
> at node_modules/selenium-webdriver/lib/promise.js:2652:27
> at node_modules/selenium-webdriver/lib/promise.js:639:7
> at run (node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:104:47)
> at node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:115:28
> at flush (node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:19:5)
> From: Task: WebDriver.createSession()
> at acquireSession (node_modules/selenium-webdriver/lib/webdriver.js:62:22)
> at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:295:12)
> at Builder.build (node_modules/selenium-webdriver/builder.js:458:24)
> at Context.initWebDriver (init/web/driver.js:11:6)
> at ChildProcess.<anonymous> (init/common/server.js:28:7)
> at handleMessage (internal/child_process.js:686:10)
> at Pipe.channel.onread (internal/child_process.js:440:11)
> From: Task: WebDriver.navigate().to(http://localhost:3000)
> at WebDriver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:344:17)
> at Navigation.to (node_modules/selenium-webdriver/lib/webdriver.js:998:25)
> at WebDriver.get (node_modules/selenium-webdriver/lib/webdriver.js:771:28)
> at Context.<anonymous> (test/web/header.js:5:27)
> From: Task: WebDriver.quit()
> at WebDriver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:344:17)
> at WebDriver.quit (node_modules/selenium-webdriver/lib/webdriver.js:419:23)
> at Context.shutdownWebDriver$ (init/web/driver.js:16:18)
> at tryCatch (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:61:40)
> at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:328:22)
> at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
> at invoke (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:136:37)
> at callInvokeWithMethodAndArg (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:172:16)
> at previousPromise (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:194:19)
> at new Promise (node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:197:7)
> at AsyncIterator.enqueue (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:193:13)
> at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:94:21)
> at Object.runtime.async (node_modules/babel/node_modules/babel-core/node_modules/regenerator/runtime.js:215:14)
> at Context.shutdownWebDriver (init/web/driver.js:14:43)
> at ChildProcess.<anonymous> (init/common/server.js:47:7)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by jleyba** [comment]
How are you creating your driver? I am unable to reproduce this against 2.51 or 2.52

**Comment by denvned** [comment]
@jleyba, I create the driver using this code:
```js
var webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();
```
Also I set `SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub`.

**Comment by jleyba** [comment]
This has the same root cause as #1627
