### ISSUE TITLE
Consider removing multi_json dependency of ruby gem

### ISSUE THREAD

**Issue by yob** [SeleniumHQ/selenium#1632]
Hi,

JSON has been part of the ruby stdlib since 1.9.0 (see https://github.com/ruby/ruby/commit/af1c4167), and the latest version of selenium-webdriver requires ruby 1.9.2 or better.

Would you consider removing multi_json as a dependency, and just using `require 'json'` instead? Rails recently made a similar change (https://github.com/rails/rails/pull/23453), which has prompted other libraries to consider the same issue (like [simplecov](https://github.com/colszowka/simplecov/issues/458) and [stripe](https://github.com/stripe/stripe-ruby/pull/379)).

See also this recent [blog post](http://www.mikeperham.com/2016/02/09/kill-your-dependencies/).

Thanks for a great library!

**Comment by p0deje** [comment]
Thanks for a great issue report and all the links you provided! Fixed now!
