### ISSUE TITLE
IDE should use MutationObserver instead of Mutation Events which is deprecated

### ISSUE THREAD

**Issue by piglovesyou** [SeleniumHQ/selenium#1634]
Launching Selenium IDE shows a warning on debugger as such:

```
Use of Mutation Events is deprecated. Use MutationObserver instead.
```

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events), Mutation Events will be removed in the future. Selenium IDE is now depending on three Mutation Events: `DOMAttrModified` `DOMNodeInserted` `DOMNodeRemoved` which are replasable with MutationObserver + `subtree` option.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
