### ISSUE TITLE
Documentation and handling of Selenium.prototype.getXYZ functions - Se IDE

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1635]
http://release.seleniumhq.org/selenium-core/1.0/reference.html#extending-selenium > 'Automatic availability...' gives an example:
Selenium.prototype.getTextLength = function(locator, text) { return this.getText(locator).length; };

The problem:
- have Selenium IDE 1.5 (and potentially earlier), up to Selenium IDE 2.9.1 (inclusive)
- have a Selenium IDE core extension file, add such a function there
- call the functions as an action in Se IDE script
- i.e. getTextLength or storeTextLength
- if the function definition has 1 parameter, then its value is passed OK.
- If I define it with 2 parameters, then none of the parameters get their value - their typeof() will be undefined. That's contrary to the documentation.

This defect/undocumented feature/restriction is caused by the following line in registerAllAccessors() in selenium-commandhandlers.js (and in remote-selenium-commandhandlers.js):

var requiresTarget = (accessMethod.length == 1);

To make this more robust, that line should be:

var requiresTarget = (accessMethod.length >= 1);

Also, after loading Core extensions, IDE should generate a warning if any getXyz() or isXyz() method on Selenium.prototype expects two parameters (i.e. generate a warning if accessMethod.length>1).

(This issue is imported from https://code.google.com/archive/p/selenium/issues/3202.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
