### ISSUE TITLE
Selenium IDE chrome/content/formats/html.js has an incorrect regex

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1636]
Selenium IDE 2.5.0 (and potentially earlier) up to 2.9.1 (inclusive) and also current https://github.com/SeleniumHQ/selenium/blob/master/ide/main/src/content/formats/html.js has an incorrect regular regex for commandLoadPattern.

Current source code:

``` javascript
this.options = {
    commandLoadPattern:
    "<tr\s*[^>]*>" +
    "\\s*(<!--[\\d\\D]*?-->)?" +
    "\\s*<td\s*[^>]*>\\s*([\\w]*?)\\s*</td>" +
    "\\s*<td\s*[^>]*>([\\d\\D]*?)</td>" +
    "\\s*(<td\s*/>|<td\s*[^>]*>([\\d\\D]*?)</td>)" +
    "\\s*</tr>\\s*",
...

Bug: every \s should be \\s
Change to:

this.options = {
    commandLoadPattern:
    "<tr\\s*[^>]*>" +
    "\\s*(<!--[\\d\\D]*?-->)?" +
    "\\s*<td\\s*[^>]*>\\s*([\\w]*?)\\s*</td>" +
    "\\s*<td\\s*[^>]*>([\\d\\D]*?)</td>" +
    "\\s*(<td\\s*/>|<td\\s*[^>]*>([\\d\\D]*?)</td>)" +
    "\\s*</tr>\\s*",...
```

I'm willing to provide a github pull request for this, if you indicate the issue as accepted.

This could be implemented together with https://github.com/SeleniumHQ/selenium/issues/1546, which depends on this issue and it changes the same regex.

(Originally reported as https://code.google.com/archive/p/selenium/issues/6901. However, Google Code misformatted the suggested code fix in that issue.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
