### ISSUE TITLE
UnsupportedCommandException when using  new RemoteWebDriver(new URL(Node), capability);

### ISSUE THREAD

**Issue by santhoshmaereddy** [SeleniumHQ/selenium#1637]
Hi,

I am trying to launch a new Remote Wed Driver instance from SAP HCP Server and I get an exception of UnsupportedCommandException. PFB details for the same

Detail error and exception screenshot is available at Stackoverflow

http://stackoverflow.com/questions/35290638/org-openqa-selenium-unsupportedcommandexception

http://stackoverflow.com/questions/35268282/selenium-webdriver-chrome-exception/35269834?noredirect=1#comment58294660_35269834

**Comment by barancev** [comment]
It's the server configuration issue. The server blocks outcoming connections that Selenium attempts to establish.
