### ISSUE TITLE
Microsoft Edge WebDriver doesn't send "backslash" under german keyboard layout 

### ISSUE THREAD

**Issue by mseele** [SeleniumHQ/selenium#1639]
When i try to send a backslash via Microsoft Edge WebDriver, the backslash is not been send under german keyboard layout. Under english keyboard layout it works.

e.g.: sending keys via

```
15/2/2016 13:15:27 - Request POST http://localhost:17556/session/SESSION_ID/element/ELEMENT_ID/value
{
    "value": [
        "x\\Sx"
    ]
}
```
will result in `"xSx"` instead of `"x\Sx"` if german keyboard layout is selected. If english keyboard layout is selected, everything works fine.

I've opened a bug at microsoft: https://connect.microsoft.com/IE/feedbackdetail/view/2361895

**Comment by lukeis** [comment]
Thanks for opening the bug with Microsoft. There's nothing more we can do on his side.
