### ISSUE TITLE
Upgrade HtmlUnit to version 2.20

### ISSUE THREAD

**Issue by jako512** [SeleniumHQ/selenium#1640]
There is newer version of HtmlUnit 2.19 (see [changelog](http://htmlunit.sourceforge.net/changes-report.html#a2.19))

It notably implements [css media queries](https://sourceforge.net/p/htmlunit/bugs/1498/)

**Comment by mkurz** [comment]
There is version 2.20 already which adds support for jQuery 2.20.

**Comment by lukeis** [comment]
HtmlUnit-driver 2.20 and now 2.21 have since been released. Any new htmlunit driver issues, please log them on the separate project:

https://github.com/SeleniumHQ/htmlunit-driver
