### ISSUE TITLE
TargetLocator no longer exported

### ISSUE THREAD

**Issue by DanielHeath** [SeleniumHQ/selenium#1642]
Upgrading from `2.48.2` to `2.52.0`; `TargetLocator` was previously exported as `WebDriver.TargetLocator`, but now we need to `require("selenium-webdriver/lib/webdriver").TargetLocator`.

Was this an intentional breaking API change or a regression? 

Should I expect semver?

**Comment by jleyba** [comment]
It's an oversight that this wasn't included in the changelog.

I'm curious why you need to import this class directly - you should always obtain an instance from a WebDriver object with `driver.switchTo()`. The API is actually designed to be fluent: `driver.switchTo().frame(0)`.

With respect to semver: node releases use the same version numbers as the rest of the Selenium project, which is not full semver and may include breaking API changes between minor releases (although we try to keep those to a minimum).
