### ISSUE TITLE
Selenium Node not getting connected to Hub while on VPN

### ISSUE THREAD

**Issue by Nirmal-Shah** [SeleniumHQ/selenium#1644]
Problem description is like..

System configuration :

Windows 7 64 bit, Java version 1.8.0_73 , Selenium Grid Jar 2.52.0.

1.This issue observed only when I am connected to VPN and using Java version >1.6
2.Selenium Node getting exception Java.net.socketException : could not register this node.Permission denied.
3.This scenario is observed when using java version >1.6.
4.Everything works fine when I am not connected to VPN.
5.When I am connected to VPN and using Java 1.6 then everything works fine.
6.I have tried using different port but nothing works.
![gridissue](https://cloud.githubusercontent.com/assets/12989516/13074106/88ce5786-d4c8-11e5-89e1-d2c0672ff326.JPG)

**Comment by lukeis** [comment]
typically when you're on a VPN your IP address is actually modified and you'll need to use your VPN IP address to connect to.

For further follow up, please post questions to the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by Nirmal-Shah** [comment]
Hi lukeis,
I am using VPN IP address. Both Hub and Node are on same machine that is connected to VPN.
As I said this behavior not observed when using Java version<=1.6 with VPN **or** without VPN with Java version>1.6.

**Comment by sbabcoc** [comment]
This is still an issue in Selenium Grid 3. My code is able to communicate with the Hub and Node servers, but the Node can't communicate with the Hub. The core issue appears to be in the method being use to determine the IP address of `localhost`. I don't know is this is a bug in the Java HTTP stack, but the typical implementation fails gloriously when running in a VPN configuration. The code I use to get the IP address of `localhost` looks like this:

```
/**
 * Get Internet protocol (IP) address for the machine we're running on.
 * 
 * @return IP address for the machine we're running on (a.k.a. - 'localhost')
 */
public static String getLocalHost() {
    try (final DatagramSocket socket = new DatagramSocket()) {
        // use Google Public DNS to discover preferred local IP
        socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
        return socket.getLocalAddress().getHostAddress();
    } catch (SocketException | UnknownHostException eaten) {
        return "localhost";
    }
}
```
As indicated by the code comment, this implementation uses Google Public DNS to acquire the IP address of `localhost`. In my current configuration. this code reports the IP address of `localhost` as 10.228.225.83 (Ethernet adapter), but the Selenium Grid servers insist on trying to use IP address 100.64.24.68 (wireless LAN adapter). With a browser, I'm able to open pages with the IP address I generate with this code. The IP address reported by the Grid servers themselves is non-functional.
