### ISSUE TITLE
'ElementToBeSelected' and 'ElementSelectionStateToBe' have identical behavior

### ISSUE THREAD

**Issue by zyrconium13** [SeleniumHQ/selenium#1645]
Hi guys,

Maybe it's just me but it seems the expected conditions 'ElementToBeSelected' and 'ElementSelectionStateToBe' seem to have the same behavior. Is this intended? Because if it is it seems rather confusing. It makes the API look like it is offering more functionality, when in fact it is not.

P.S.: I'm concerned with .Net implementation.

Thank you.

**Comment by Mobrockers** [comment]
The documentation seems to be copy pasted and slightly wrong.
ElementToBeSelected calls ElementSelectionStateToBe with value true.
ElementSelectionStateTobe takes a boolean.
So you can use ElementSelectionStateToBe to check if an element is selected or NOT selected, while you can only use ElementTobeSelected to check if a value is selected.

It's basically just a fancy named method wrapper to declare intent in the method name only, and not need the boolean value.
