### ISSUE TITLE
Screenshots not getting captured intermittently

### ISSUE THREAD

**Issue by ilangv** [SeleniumHQ/selenium#1652]
Our selenium grid setup using 2.52 has an issue with capturing screenshots intermittently with the below exception:

`net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException--\u003enull
\tat net.sf.cglib.proxy.Enhancer.setCallbacksHelper(Enhancer.java:622)
\tat net.sf.cglib.proxy.Enhancer.setThreadCallbacks(Enhancer.java:609)
\tat net.sf.cglib.proxy.Enhancer.createUsingReflection(Enhancer.java:631)
\tat net.sf.cglib.proxy.Enhancer.firstInstance(Enhancer.java:538)
\tat net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:231)
\tat net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
\tat net.sf.cglib.proxy.Enhancer.create(Enhancer.java:285)
\tat org.openqa.selenium.remote.Augmenter.performAugmentation(Augmenter.java:149)
\tat org.openqa.selenium.remote.Augmenter.create(Augmenter.java:57)
\tat org.openqa.selenium.remote.BaseAugmenter.augment(BaseAugmenter.java:110)
...

....
\tat java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
\tat sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.lang.reflect.Method.invoke(Method.java:606)
\tat net.sf.cglib.proxy.Enhancer.setCallbacksHelper(Enhancer.java:616)
\t... 29 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.openqa.selenium.remote.RemoteWebDriver$$EnhancerByCGLIB$$7b96e3ce
\t... 33 more`

This is the code snippet generating the screenshot:

`WebDriver augmentedDriver = new Augmenter().augment(driver);
                    byte[] screenShot;
                    screenShot = ((TakesScreenshot)augmentedDriver).
                        getScreenshotAs(OutputType.BYTES);`

**Comment by barancev** [comment]
I understand that we're too late, but...

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment]
cglib replaced by bytebuddy in 07b7b540a7f4e6ebb7c3c4715e6fd791dd8aa082, so this issue is not actual anymore.
