### ISSUE TITLE
Selenium IDE garbles relative paths to test cases when saving a suite

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [SeleniumHQ/selenium#1653]
Hello :)

I'm experiencing the issue described [here](http://everythingsqa.tumblr.com/post/1367487846/selenium-relative-path-issues).

When saving a suite in the IDE, if it contains test cases that reside in a parent or sibling folder, it'll save garbled relative paths that'll make the IDE throw an exception when you try to re-open the suite later.

Example:

The suite:
`/Users/daniel/Projects/some-project/test/browser/suites/create-user/create-user.html`

References the (shared) test case:
`/Users/daniel/Projects/some-project/test/browser/suites/lib/log-in-as-admin.html`

Expected test case href when saving (and required when opening) the suite:
`<tr><td><a href="../lib/log-in-as-admin.html">log in as admin</a></td></tr>`

Actual href when saving:
`<tr><td><a href="../../../../../../../../../lib/log-in-as-admin.html">log in as admin</a></td></tr>`

It looks like every folder in the path is simply replaced by two dots? Seems like an easy bug to fix :)

I can correct this manually, but it's a short-lived fix, because the next time I save the suite in the IDE, it'll re-garble the paths.

The work-around using absolute paths suggested by the blogger in the link referenced above is not viable here, as we are a number of people sharing these tests via git and creating and running them on different setups. 

Selenium IDE 2.9.1 in Firefox 44.0.2 on Mac OS X 10.11.3

Cheers :)

**Comment by andrewlorien** [comment]
This issue is more recent, but has had more discussion and is assigned : https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1683

**Comment by peter-kehl** [comment]
Daniel,

I occasionally get this issue. However, now, when I want to replicate, it didn't happen. From memory it happened when I re-opened and then re-saved an existing test suite.

In case you start with a new simple test suite and the issue happens again, please would you describe the circumstances (whether it was after you re-opened an existing test suite, saved the test suite under new name...), please.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
