### ISSUE TITLE
"An invalid or illegal selector was specified" returned by InternetExplorerDriver if selector contains minus sign

### ISSUE THREAD

**Issue by lakitutu** [SeleniumHQ/selenium#1656]
Selenium version 2.51.0
IEDriverServer.exe 2.51.0.0 32-bit

I am getting error every time I use "-" in css selector at the beginning of class name:
"
(org.openqa.selenium.InvalidSelectorException: An invalid or illegal selector was specified (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.51.0', revision: '1af067dbcaedd7d2ab9af5151fc471d363d97193', time: '2016-02-05 11:20:57'
System info: host: 'x0075-pc', ip: '10.123.10.85', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_60'
*** Element info: {Using=css selector, value=div.side-menu div.--menu-projects}
Session ID: 7b06ea4c-f9fa-477c-af4a-51430dc88756
"
In case of changing my selector to "div.side-menu div[class$='menu-projects']" it works fine.
Usually I am testing with Firefox and of course both that selectors works perfectly fine.

**Comment by jimevans** [comment]
This is an issue with IE's CSS selector engine, not the IE driver. In the Console tab of the F12 Developer Tools in IE 11, if I attempt to execute the following:

    document.querySelector("div.side-menu div.--menu-projects")

I receive a response of `SyntaxError`. Incidentally, it's the double-hyphen (`--`) that's the issue. Using a single hyphen yields a correct response from the JavaScript interpreter (a `NodeList` if an element with that class exists; `null` if it does not).

**Comment by twalpole** [comment]
Technically IE is following the spec - https://www.w3.org/TR/CSS21/grammar.html#scanner  - since class is defined as  . IDENT,  ident is -?{nmstart}{nmchar}*  and nmstart is [_a-z]|{nonascii}|{escape}  

This means two -s at the beginning unescaped aren't grammar compliant.  To be compliant the second one would need to be escaped when specified   `document.querySelector('div.side-menu div.-\-menu-projects')`

**Comment by lakitutu** [comment]
@jimevans thank you for clarification.
@twalpole thank you for your further clarification and your suggestion how to properly handle classes begins from "--". It works like a charm:)
