### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by safrrhmn** [SeleniumHQ/selenium#1657]
I have been using Selenium 2.48 with Firefox 38 and was having similar issue in grid. Yesterday I decided to upgrade to 2.52.0 and firefox 44 to see if this issue is somehow related to the version I was using. At least couple of post on SO suggests the compatibility issue which I can confirm is not. I am getting the following on Jenkins

`org.openqa.selenium.WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output: oglecode.com","installDate":1455596830287,"updateDate":1455596830287,"applyBackgroundUpdates":1,"bootstrap":false,"size":3236332,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"47.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0} 1455596837349 addons.xpi DEBUG getModTime: Recursive scan of fxdriver@googlecode.com 1455596837375 addons.xpi DEBUG Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"fJru4ZU2iC5a","location":"app-global","version":"44.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1455582992487,"updateDate":1455582992487,"applyBackgroundUpdates":1,"skinnable":true,"size":24166,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"44.0","maxVersion":"44.0"}],"targetPlatforms":[]} 1455596837375 addons.xpi DEBUG getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd} 1455596837383 DeferredSave.extensions.json DEBUG Save changes 1455596837384 addons.xpi DEBUG Updating database with changes to installed add-ons 1455596837385 addons.xpi-utils DEBUG Updating add-on states 1455596837389 addons.xpi-utils DEBUG Writing add-ons list 1455596837430 addons.manager DEBUG Registering shutdown blocker for XPIProvider 1455596837431 addons.manager DEBUG Provider finished startup: XPIProvider 1455596837432 addons.manager DEBUG Starting provider: LightweightThemeManager 1455596837432 addons.manager DEBUG Registering shutdown blocker for LightweightThemeManager 1455596837433 addons.manager DEBUG Provider finished startup: LightweightThemeManager 1455596837436 addons.manager DEBUG Starting provider: GMPProvider 1455596837460 addons.manager DEBUG Registering shutdown blocker for GMPProvider 1455596837462 addons.manager DEBUG Provider finished startup: GMPProvider 1455596837463 addons.manager DEBUG Starting provider: PluginProvider 1455596837464 addons.manager DEBUG Registering shutdown blocker for PluginProvider 1455596837465 addons.manager DEBUG Provider finished startup: PluginProvider 1455596837467 addons.manager DEBUG Completed startup sequence 1455596858981 addons.manager DEBUG Starting provider: 1455596858981 addons.manager DEBUG Registering shutdown blocker for 1455596858983 addons.manager DEBUG Provider finished startup: 1455596873428 DeferredSave.extensions.json DEBUG Starting write 1455596874900 addons.repository DEBUG No addons.json found. 1455596874902 DeferredSave.addons.json DEBUG Save changes 1455596874912 DeferredSave.addons.json DEBUG Starting timer 1455596874962 addons.manager DEBUG Starting provider: PreviousExperimentProvider 1455596874962 addons.manager DEBUG Registering shutdown blocker for PreviousExperimentProvider 1455596874963 addons.manager DEBUG Provider finished startup: PreviousExperimentProvider 1455596874970 DeferredSave.extensions.json DEBUG Write succeeded 1455596874971 addons.xpi-utils DEBUG XPI Database saved, setting schema version preference to 17 1455596875013 DeferredSave.addons.json DEBUG Starting write`

Platform:
Windows machines hosting Node and Hub
Jenkins on Linux
Grid version: 2.52.0 Firefox 44.0

**Comment by barancev** [comment]
1) When you see a browser window open please check the Extensions list if Selenium WebDriver is enabled and has the proper version number (2.52)

2) If all the above is true you must be facing a network configuration issue. Either connections to 127.0.0.1:7055 are blocked by some third-party sofware (AV, proxy, port-mapper etc) or you have a non-standard default host name for 127.0.0.1

**Comment by safrrhmn** [comment]
Still having the same issue intermittently. #1 always true. #2 there was av and I removed. There is nothing possible that I can see which causes this. Any other option I can try?

![capture](https://cloud.githubusercontent.com/assets/7663722/13612572/277384d8-e536-11e5-8510-b8e76c900290.PNG)

**Comment by lukeis** [comment]
closing as the issue has gone a bit stale, the latest release 2.53.1 should be working with 47.0.1, 46, 45 ESR, 38 ESR. Also these are likely the last versions of firefox to be supported by the selenium project and future versions will require [GeckoDriver](https://github.com/mozilla/GeckoDriver).
