### ISSUE TITLE
2.52.0 download corrupt

### ISSUE THREAD

**Issue by hath123** [SeleniumHQ/selenium#1658]
Hi,

I am trying to download and install Selenium IDE, I used to have this installed however after lack of use and updates to firefox the tool no longer works.

I have uninstalled and tried to re-install Selenium IDE 2.852.0 from the downloan section of their site. But when i download and try to install i getting a message stating the file is corrupt. I have tried uninstalling firefox and reinstalling completely but I still get the same issue with Selenium IDE.

Is this a known issue as I cannot find any reference to it online.

Thanks

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by hath123** [comment]
Apologies but a corrupt download file is surely an issue not a question? This doesn't just happen for myself so it is not a local issue

**Comment by hath123** [comment]
Hi,

The issue is your download file is corrupted. This happens every time a download is attempted and it is not local to myself as others are having the same issue.

Thanks
Joe




Joseph Woolley - Test Analyst


E: Joseph.Woolley@ninegroup.co.uk



[Nine Group Logo]












Nine Group
The Hub
Stonehouse Business Park
Stonehouse
Gloucestershire
GL10 3UT

Main office:
T: 0800 970 2999
ninegroup.co.uk<http://ninegroup.co.uk>


Nine Wholesale
The Hub
Stonehouse Business Park
Stonehouse
Gloucestershire
GL10 3UT

Main office:
T: 0800 068 5939
ninewholesale.co.uk<http://ninewholesale.co.uk>


Nine Telecom
Victory House
Chobham Street
Luton
Bedfordshire
LU1 3BS

Main office:
T: 0800 970 2999
ninetelecom.co.uk<http://ninetelecom.co.uk>


[Investors in People Silver - ISO Accreditation]


Nine Group is a trading style of Nine Telecom Group Ltd. Nine Wholesale is a trading style of Club Communications Ltd.


Nine Telecom Group Ltd is a limited company registered in England and Wales.
Registered No: 06524769 Registered Office: Pegasus House, Unit 602, Sperry Way, Stonehouse Business Park, Stonehouse GL10 3UT


No employee or agent is authorised to conclude any binding agreement on behalf of Nine Telecom Group Ltd with another party by email without the express written confirmation of an authorised representative of Nine Telecom Group Ltd.


This email contains proprietary information, some or all of which maybe legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail. If you are not the intended recipient you must not use, disclose, distribute, copy, print or rely upon this e-mail. Copyright in this e-mail and attachments created by us belongs to Nine Telecom Group Ltd. The author also asserts the right to be identified as such and to object to any misuse. Nine Telecom Group Ltd may monitor email traffic data and also the content of email for the purpose of security and staff training.


Nine Telecom Group Ltd cannot accept liability for any damage sustained as a result of any software viruses contained in this email or any attachments to it and advise you to carry out your own virus check before opening the email or any attachment. Furthermore, we do not accept responsibility for any change made to this message after it was sent by the sender.

**Comment by lukeis** [comment]
Care to share the link to the supposed corrupt download and from which page you are finding the link?

**Comment by hath123** [comment]
Hi,

The link is http://www.seleniumhq.org/download/  and is the 2.52.0 download version.

Link selected directly from a ‘download selenium IDE’ google search.

Thanks




Joseph Woolley - Test Analyst


E: Joseph.Woolley@ninegroup.co.uk



[Nine Group Logo]












Nine Group
The Hub
Stonehouse Business Park
Stonehouse
Gloucestershire
GL10 3UT

Main office:
T: 0800 970 2999
ninegroup.co.uk<http://ninegroup.co.uk>


Nine Wholesale
The Hub
Stonehouse Business Park
Stonehouse
Gloucestershire
GL10 3UT

Main office:
T: 0800 068 5939
ninewholesale.co.uk<http://ninewholesale.co.uk>


Nine Telecom
Victory House
Chobham Street
Luton
Bedfordshire
LU1 3BS

Main office:
T: 0800 970 2999
ninetelecom.co.uk<http://ninetelecom.co.uk>


[Investors in People Silver - ISO Accreditation]


Nine Group is a trading style of Nine Telecom Group Ltd. Nine Wholesale is a trading style of Club Communications Ltd.


Nine Telecom Group Ltd is a limited company registered in England and Wales.
Registered No: 06524769 Registered Office: Pegasus House, Unit 602, Sperry Way, Stonehouse Business Park, Stonehouse GL10 3UT


No employee or agent is authorised to conclude any binding agreement on behalf of Nine Telecom Group Ltd with another party by email without the express written confirmation of an authorised representative of Nine Telecom Group Ltd.


This email contains proprietary information, some or all of which maybe legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail. If you are not the intended recipient you must not use, disclose, distribute, copy, print or rely upon this e-mail. Copyright in this e-mail and attachments created by us belongs to Nine Telecom Group Ltd. The author also asserts the right to be identified as such and to object to any misuse. Nine Telecom Group Ltd may monitor email traffic data and also the content of email for the purpose of security and staff training.


Nine Telecom Group Ltd cannot accept liability for any damage sustained as a result of any software viruses contained in this email or any attachments to it and advise you to carry out your own virus check before opening the email or any attachment. Furthermore, we do not accept responsibility for any change made to this message after it was sent by the sender.

**Comment by lukeis** [comment]
there are many links on the page. Can you please right click on it and "copy link address" and paste it here. Also the link text that is displayed.

Your original issue report references Selenium IDE. But now you mention 2.52.0, which is the standalone-server. Selenium IDE's current version is 2.9.1

The link "2.52.0" is http://goo.gl/qTy1IB  and it is not corrupt.
