### ISSUE TITLE
Selenium grid with chrome node hangs on Centos7

### ISSUE THREAD

**Issue by devscons** [SeleniumHQ/selenium#1659]
Chrome node hangs with simple setup - selenium grid hub with one node on Centos7
### Steps to reproduce
- OS: centos7
- Selenium hub 2.52.0 with config:
  {
  "host": null,
  "port": 4444,
  "throwOnCapabilityNotPresent": True,
  "newSessionWaitTimeout": -1,
  "capabilityMatcher": "io.sterodium.extensions.capability.CustomCapabilityMatcher",
  "prioritizer": null,
  "servlets" : ['io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet'],
  "browserTimeout": 300000,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 300000,
  "maxSession": 5,
  "jettyMaxThreads": -1
  }
- Selenium node 2.52.0 with config
  {
  "capabilities":
      [
          {
              "browserName": chrome,
              "maxInstances": 1,
              "extension.sikuliCapability": True
          } ],
  "configuration": {
  "host":127.0.0.1,Google Chrome 48.0.2564.109
  "port":5566,
  "cleanUpCycle":2000,
  "timeout":30000,
  "register": True,
  "registerCycle": 5000,
  "browserTimeout":60000,
  "hubHost":localhost,
  "hubPort":4444,
  "proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession":1,
  "registerCycle":5000,
  "nodePolling":2000,
  "unregisterIfStillDownAfter":60000,
  "downPollingLimit":10,
  "nodeStatusCheckTimeout":10000
  }
  }
- Chromedriver 2.21
- Google Chrome 48.0.2564.109

also was noticed with earlier versions of selenium-server, chromedriver and chrome

On the following setup run simple code: 

```
public static void main(String[] args) throws Exception {

    DesiredCapabilities capability = DesiredCapabilities.chrome();
    WebDriver driver = null;
    try {
        for (int i=0;i<100000;i++) {

            System.out.println("creating driver number: " + i);
            driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capability);
            System.out.println("driver created");

            System.out.println("doing quit");
            driver.quit();
            System.out.println("quit done");        
        }

    } catch (MalformedURLException e) {
        e.printStackTrace();
    }
}
```

At some moment test sporadically hangs  at 
new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capability);

**Note**: Execution hangs not because of previous session wasn't quit. It was tested that there is neither chrome processes before new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capability) that causes hanging nor console shows that some request waits for slot to be free
### What happens on Centos7 server

There are 4 threads that start on driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capability); and die on driver.quit(); at normal circumstances, but issue occur and test hangs these 4 threads live forever 

![threads](https://cloud.githubusercontent.com/assets/15073570/13114957/73904966-d59e-11e5-96d2-480e2be0eb7a.jpg)

As I've got so far one thread that calls chromedriver hangs:
![forwarding-new-session](https://cloud.githubusercontent.com/assets/15073570/13115007/b7ed9910-d59e-11e5-87e4-b09c244d401e.jpg)

Watchdog that waits for chrome process to end waits forever:
![watchdog](https://cloud.githubusercontent.com/assets/15073570/13115034/d738ff44-d59e-11e5-8285-5b54ea816df8.jpg)
### Not enough memory hypothesis

It was an idea to notice whether giving unix (Centos7) VM less memory could cause test to be failing quicker. The idea was failed and correlation with memory wasn't noticed
### Running on Windows

Running same test for a long time on windows issue was never experienced.

**Comment by delie84** [comment]
any update on this, we're seeing same issue

**Comment by barancev** [comment]
Is this issue still actual? We need more info on what's happening on the node side. Does it start chromedriver process? Does chromedriver start chrome?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
