### ISSUE TITLE
The Python distribution of Selenium 2.52.0 reports itself as 2.51.0

### ISSUE THREAD

**Issue by lddubeau** [SeleniumHQ/selenium#1660]
Pip reports version 2.52.0 is installed:

```
$ pip show selenium
---
Name: selenium
Version: 2.52.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

But Selenium's init contains 2.51.0:

```
$ grep __version__ /usr/local/lib/python2.7/dist-packages/selenium/__init__.py
__version__ = "2.51.0"
```

Init should also contain 2.52.0

**Comment by lukeis** [comment]
opps... and damn... Thanks for pointing it out, will be fixed in the next release (assuming someone remembers to bump the version numbers as they should!)

**Comment by lddubeau** [comment]
Thanks.

I strongly recommend having a single source for the version number so that nobody has the opportunity to forget to update it. I know if I rely on me not forgetting to update, there are going to be mistakes.

A good example for Python is how [Scrapy](https://github.com/scrapy/scrapy) does it. Both its `setup.py` and its `scrapy/__init__.py` take their version number from a `scrapy/VERSION` file. I do something similar for my own Python packages.

**Comment by cgoldberg** [comment]
I agree that having a single place for version number would be a great idea.

As for remembering...  this could probably be a part of the release itself.  A post-release task would bump the version number in master (either a manual task, or an automated script run by the release job).

For example, Immediately after release of 2.5.1 goes out, the version string in master would get incremented, and master becomes the 2.5.2 development branch.  (you can still tweak versions manually when you need to do a release of major revision or hotfix)

just $.02
