### ISSUE TITLE
JsonWireProtocol API web page not available?

### ISSUE THREAD

**Issue by Kreny** [SeleniumHQ/selenium#1663]
## Expected Behavior -
Every reference to JsonWireProtocol API on Internet goes to  https://code.google.com/p/selenium/wiki/JsonWireProtocol
## Actual Behavior -
browser is redirected to https://github.com/seleniumhq/selenium
## Steps to reproduce -
try to open https://code.google.com/p/selenium/wiki/JsonWireProtocol

//sorry for kind of dumb error but for me it seems links are broken

**Comment by barancev** [comment]
Sorry, we can neither fix Internet nor revert Google's decision to retire googlecode.

The new page address is https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

And it's deprecated all in all superceded by W3C WebDriver standard:
https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by Kreny** [comment]
Hi,

Thanks for quick reply and sorry for this report but I was not able to navigate to that page from Selenium homepage at all (but maybe just my bad)

**Comment by barancev** [comment]
If there is a broken link please tell us where it is.
