### ISSUE TITLE
Windows authentication/NTLM - settings ignored?

### ISSUE THREAD

**Issue by djjohnjosephuk** [SeleniumHQ/selenium#1665]
Hi,

Does the driver server respect any of the settings set in Internet Options -> Security?

I have set within 'Intranet zone' that the browser should automatically logon as the current machine username and password. When I log into that machine, and launch IE manually, I don't get the authentication prompt and IE correctly uses that setting to log me in as the windows machine login.

When firing off web tests through selenium, I get errors that a modal dialog is present, indicative that the driver server fires up IE without taking that setting into consideration, and doesn't log me in.

I'm aware of the fact that we can't interact with the dialog, etc so don't expect that but just wondered if that setting is being ignored or perhaps I am missing something in the startup config to get that to work?

**Comment by jimevans** [comment]
The IE driver does nothing special to ignore browser settings by default. Those settings should be respected. However, depending on the account you manually log in with vs. the account the tests run under, you may be encountering a permissions issue, especially if the process starting the tests is a Windows service. Nevertheless, your assertion that "we can't interact with the dialog" is incorrect. The IE driver may be able to handle the authentication dialog[1], and this capability is exposed in the Java through the `Alert` interface's `authenticateUsing` method.

[1] The Basic authentication dialog is handled and well tested. Though it hasn't been tested in this particular scenario, may be able to handle the NTLM authentication dialog as well.

**Comment by djjohnjosephuk** [comment]
Thanks for the reply. It's definitely something to do with how the grid kicks off the driver server on the nodes, as running a standalone selenium off the .jar file locally/on the same machine it works fine, respecting the value set in the configuration for automatic logon. Not sure where to dig next in terms of a solution to that one.

I'll look into the `authenticateUsing`, though I don't think that's supported in the library I use (phpunit). Thanks again.

**Comment by diemol** [comment]
Closing this issue as it was a question and no action item came out of it.
