### ISSUE TITLE
JsonWireProtocol wiki page has broken internal links

### ISSUE THREAD

**Issue by paulirish** [SeleniumHQ/selenium#1667]
* Click a linked command from the table in https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#command-summary (e.g. "	/session/:sessionId/screenshot")
* It should resolve to the actual command details, but it doesnt.

The screenshot link points to `#GET_/session/:sessionId/screenshot.md` but the actual anchor link is `#sessionsessionidscreenshot`

This isn't hard to fix, but I didn't have the time this morning to tackle it. Cheers.

**Comment by barancev** [comment]
This document is obsolete. It is superceded by W3C WebDriver standard https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by lukeis** [comment]
although the W3C document is the new living standard... i went ahead and fixed those links ;)

**Comment by paulirish** [comment]
@lukeis thanks for the edits. appreciated. :)

maybe an obsolescence notice should be added to the top of the wiki page as well?

**Comment by lukeis** [comment]
@paulirish done
