### ISSUE TITLE
Page Can't be displayed is shown when running tests in suite from IE driver

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1669]
## Steps to reproduce - Please refer attached iedriver logs and screenshot
1.with page can't be displayed [Refer attached log 
[pagecantbedisplayed.txt](https://github.com/SeleniumHQ/selenium/files/137656/pagecantbedisplayed.txt)

]
2.without page can't be displayed [Refer attached log 
[Uploading withoutpagecantbedisplayed.txt…]()
]

**Comment by YeRaghuRam** [comment]
![pagecantbedisplayed](https://cloud.githubusercontent.com/assets/17119289/13171230/a74ae9da-d717-11e5-83b2-eb73f971dbaf.PNG)

**Comment by jimevans** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
