### ISSUE TITLE
Internet explorer not launched when running tests in suite

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#1670]
## Steps to reproduce - 
Refer attached iedriver logs and screeshot
![abouttobegin](https://cloud.githubusercontent.com/assets/17119289/13171652/fd491468-d719-11e5-8225-b8c1bab34e86.PNG)
[abouttobegin.txt](https://github.com/SeleniumHQ/selenium/files/137680/abouttobegin.txt)

**Comment by jimevans** [comment]
There is no information here that is actionable.
