### ISSUE TITLE
Selenium grid not respecting the requested chrome version

### ISSUE THREAD

**Issue by stenver** [SeleniumHQ/selenium#1671]
## Expected Behavior -
When I have a grid set up with 1 node connecting to it with chrome version 29 and another node connecting to the grid with chrome version 33, then when I run the test and request version 29, I expect to get access to node thats labeled with version 29.

## Actual Behavior -

The GRID hands out a node which has 'chrome' node, regardless of the version of the 'chrome'. I.e. When I create a test which requires chrome version 29, I might get chrome 33.

## Steps to reproduce -
1. Bring up the grid
2. Register a node with random version of chrome(config.json below)
```json
{
  "capabilities": [
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "version": "random",
      "seleniumProtocol": "WebDriver"
  ...
```
3. Register a node with chrome 29(config.json below)
```json
{
  "capabilities": [
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "version": 29,
      "seleniumProtocol": "WebDriver"
   }
  ...
```
4. Create a test which registers chrome version 29
```
    def include_chrome29_driver(
      conf = {}
      conf[:http_client] = client_with_increased_timeout
      conf[:browser] = local_browser
      conf[:desired_capabilities] = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"args" => args})
      conf[:desired_capabilities].version = "29"
      Capybara.register_driver :"chrome29" do |app|
        Capybara::Selenium::Driver.new(app, conf)
      end
    end
```
5. Run the test - most likely you will get the node with chrome version "random", because it was registered first. Version is ignored

**Comment by csotaky** [comment]
The same is true with Firefox.

**Comment by stenver** [comment]
Is this intentional? How are multiple different versions of firefoxes and chromes meant to be tested in a grid? Only way is to put up multiple grids?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by stenver** [comment]
So you are saying this is not a bug and is meant to be like this by design?

**Comment by barancev** [comment]
Like what? The question is "how to configure grid to be able to run various browser versions". This is a question.

To reproduce the issue I've created two node configs.

node1.json:
```
{
  "capabilities":
      [
        {
          "browserName": "chrome",
          "version": "random",
          "maxInstances": 1,
          "seleniumProtocol": "WebDriver"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 5,
    "port": 5555,
    "host": ip,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": ip
  }
}
```

node2.json:
```
{
  "capabilities":
      [
        {
          "browserName": "chrome",
          "version": "48",
          "maxInstances": 1,
          "seleniumProtocol": "WebDriver"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 5,
    "port": 5555,
    "host": ip,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": ip
  }
}
```

Then I've started the grid hub and registered two nodes to the hub (the "random" one was registered first):
`java -jar selenium-server-standalone-2.52.0.jar -role node -port 5555 -hub http://localhost:4444/wd/hub -nodeConfig node1.json`
`java -jar selenium-server-standalone-2.52.0.jar -role node -port 6666 -hub http://localhost:4444/wd/hub -nodeConfig node2.json`

Then I've run the following script in python:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

for _ in range(10):
    driver = webdriver.Remote(command_executor='http://127.0.0.1:4444/wd/hub',
                              desired_capabilities={'browserName': 'chrome', 'version': '48'})
    driver.quit()
```

All session were opened on the second node, see the screenshot for the witness.
![20-02-2016 20-44-25](https://cloud.githubusercontent.com/assets/617090/13198165/de671960-d812-11e5-9f0b-5f2831733ac0.png)

If you think there is an issue here please provide a more detailed description how to reproduce it.

**Comment by stenver** [comment]
Thank you.. I will look through my code 1 more time, if I am doing something incorrectly

**Comment by stenver** [comment]
Thanks @barancev , finally had a chance to work on this again. So it turns out that you cannot use integers in `version` and that was the problems. Switching to strings everywhere solved it.
