### ISSUE TITLE
I am not able to find Webdriver.apk (android-server) file

### ISSUE THREAD

**Issue by SohitKanwar** [SeleniumHQ/selenium#1680]
Can anyone please send me the location from where i can download **Webdriver.apk (android-server) file**?

I need to perform a test for compatibility of a web application on Mobile platform. I have downloaded the Android SDK and now i need to install the webdriver apk into the emulator(virtual device).

I have searched many links and found that the location of **android-server.apk ** is under the following link:-
http://code.google.com/p/selenium/downloads/list

But I am not able to find the same. Appreciate any help on this.

Regards,
Sohit

**Comment by lukeis** [comment]
This was long ago deprecated and removed from the selenium source tree. I recommend taking a look at using Selendroid or appium. 

If you insist on finding this apk, Google code has an archive for projects now.
