### ISSUE TITLE
Safari Browser quits immediately working with Hub on Mac

### ISSUE THREAD

**Issue by Mansik8** [SeleniumHQ/selenium#1682]
I am facing same issue. Safari browser gets closed immediately after launching the browser with java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

Selenium 2.52.0
Mac OS X 10.11
Safari:9.0

Details are:

Feb 22, 2016 11:05:08 AM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 28534
Feb 22, 2016 11:05:08 AM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Launching Safari
Feb 22, 2016 11:05:08 AM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Waiting for SafariDriver to connect
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping Safari
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Feb 22, 2016 11:05:18 AM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
org.apache.maven.surefire.booter.SurefireExecutionException: 
An error occurred while instantiating class com.apple.mqm.pfa.Tests.SmokeTests: null; nested exception is org.testng.TestNGException: 
An error occurred while instantiating class com.apple.mqm.pfa.Tests.SmokeTests: null
org.testng.TestNGException: 
An error occurred while instantiating class com.apple.mqm.pfa.Tests.SmokeTests: null

**Comment by JurgenR** [comment]
I had a similar issue, rebooting the machine after installation of the Webdriver plugin worked for me.

**Comment by 5hawnknight** [comment]
can you provide a code example and the command(s) that start your testing process?

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
