### ISSUE TITLE
unreachable code after return statement

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1685]
Run Selenium IDE based on current master of https://github.com/SeleniumHQ/selenium in Firefox 44. You'll get 'unreachable code after return statement' in JS debugger console.

Fix: pull https://github.com/SeleniumHQ/selenium/commit/b0783b8ab4fabeab8df0adfc77f9e509b8762364 I would create a pull request, but I don't see a way to create a selective pull request on Github.

**Comment by cgoldberg** [comment]
@peter-kehl create a branch with only the commits you want to merge, and then create a pull request to merge that branch into selenium master.

**Comment by peter-kehl** [comment]
https://github.com/SeleniumHQ/selenium/pull/1701

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
