### ISSUE TITLE
Command "pause" does not pause on Selenium IDE 2.9.0 when running a script with "pause" in the last line

### ISSUE THREAD

**Issue by wuyybj** [SeleniumHQ/selenium#1686]
## Expected Behavior -

The command "pause" should pause even if it stays in the last line of a script.
## Actual Behavior -

The command "pause" does not pause when it stays in the last line of a script.
## Steps to reproduce -

Browser: Firefox 38.6.0
Selenium IDE: 2.9.0
1. I run a simple script which opens a page and pause 5 seconds.
![script on ide](https://cloud.githubusercontent.com/assets/17423521/13243424/ad8bdd0c-da39-11e5-9901-ec1d92a4d26e.png)
2. But I observed that "pause" command did not pause even if it showed passed.
![running result on ide](https://cloud.githubusercontent.com/assets/17423521/13243497/2f60a100-da3a-11e5-8bc1-6cfdabe6e0f1.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
