### ISSUE TITLE
[Python] Opening Chrome (Incognito mode) with default Extension: Not working [Severe Bug]

### ISSUE THREAD

**Issue by MarcM28** [SeleniumHQ/selenium#1689]
## Expected Behavior -
Opening google chrome (**Incognito mode**) with default **extension** already installed then go to site: http://google.com

## Actual Behavior -
After opened the chrome (Incognito mode) with extension but not working the `driver.get("http://google.com")` This code is doing nothing.

## Steps to reproduce -
    import time, os
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options

    executable_path = "C:\chromedriver_win32\chromedriver"

    chrome_options = Options()

    # Private browsing
    chrome_options.add_argument("--incognito")

    # To use my default extension
    chrome_options.add_argument(r"user-data-dir=C:\Users\Mika\AppData\Local\Google\Chrome\User Data")

    driver = webdriver.Chrome(executable_path=executable_path, chrome_options=chrome_options)

    driver.get("http://google.com") # This code is not working

    time.sleep(60)  # 60 seconds sleep/delay
    driver.quit()

Please help me, I want to automate my google chrome.

**Comment by lukeis** [comment]
for issues with chromedriver please log them with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
