### ISSUE TITLE
selenium switches not support proxy with username && password?

### ISSUE THREAD

**Issue by seaify** [SeleniumHQ/selenium#1691]
```ruby
Watir::Browser.new :chrome, :switches => proxy_switches
```
if passed proxy_switches is localhost:8888, it works.
if it contains username&password, then the driver it shows
```
ERR_NO_SUPPORTED_PROXIES
```

Actually use curl 'xx' --proxy http://username:password@xx.yy, it works. 

Why the driver didn't support it?

**Comment by p0deje** [comment]
This is a ChromeDriver issue, not a Selenium one. Please report it to [ChromeDriver bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
