### ISSUE TITLE
DLLs aren't signed

### ISSUE THREAD

**Issue by armhil** [SeleniumHQ/selenium#1696]
## Expected Behavior -
Dll for the Selenium WebDriver as well as the Support aren't signed, which would create issues for consuming from the signed dlls.
## Actual Behavior -
They should be signed.
## Steps to reproduce -
To verify the behaviour you can use the sn.exe tool (https://msdn.microsoft.com/en-us/library/k5b5tt23.aspx) and check the dll with this tool.

**Comment by jimevans** [comment]
The project releases strong-named binaries along with the unsigned. Please see http://selenium-release/storage.googleapis.com/index.html. However, these strong-named binaries are not (and will not be) distributed via NuGet.

**Comment by Qhero** [comment]
I was looking for strong-named binaries when i found this issue. However the link is not good, it's :
[http://selenium-release.storage.googleapis.com/index.html](http://selenium-release.storage.googleapis.com/index.html)
Cheers

**Comment by lmtierney** [comment]
@Qhero you need to check within the version directory that you need at that link
