### ISSUE TITLE
ExecuteJavascript errors when the javascript returns an empty array

### ISSUE THREAD

**Issue by distinctdan** [SeleniumHQ/selenium#1699]
### Expected Behavior
This is the failing scenario. I would expect this to work and return an empty List:
    `var thisFails = driver.ExecuteJavaScript<List<Object>>("return [];");`

It throws the error: "OpenQA.Selenium.WebDriverException : Script returned a value, but the result could not be cast to the desired type"

I'm running Selenium version 2.52.0 with the Chrome webdriver version 2.21.371459, which I believe is the latest. 

I see there was a bug related to this not too long ago: https://github.com/SeleniumHQ/selenium/issues/1257

**Comment by jimevans** [comment]
The .NET bindings do not return `List<object>` when returning arrays from JavaScript. Rather, it returns `object[]`. The following code is what should work:

    var foo = driver.ExecuteJavaScript<object[]>("return [];");

**Comment by distinctdan** [comment]
Hmm, I just tried that and it's still throwing the error.

I'm also having trouble finding any official docs on ExecuteJavascript. Most seem to be for ExecuteScript. Should I be using that instead? This is what I found, but it doesn't list any return types or examples: https://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_Support_Extensions_WebDriverExtensions_ExecuteJavaScript__1.htm

**Comment by distinctdan** [comment]
The ExecuteScript method says it returns List<T> in it's docs, so perhaps those need to be updated as well? https://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_IJavaScriptExecutor_ExecuteScript.htm

**Comment by jimevans** [comment]
I apologize. I'm incorrect. It's not `object[]`; it's `ReadOnlyCollection<object>`. Mea culpa. Here's the correct code:
    var foo = driver.ExecuteJavaScript<ReadOnlyCollection<object>>("return [];");

**Comment by distinctdan** [comment]
Awesome, that was it, thanks for the help.

**Comment by distinctdan** [comment]
Actually, I found `ReadOnlyCollection<object>` errors if the array has IWebElements in it. However, using `IReadOnlyCollection<object>` works fine.

**Comment by jimevans** [comment]
Right, because returning a list of `IWebElement` objects is a special case. In that instance it explicitly returns `ReadOnlyCollection<IWebElement>`.
