### ISSUE TITLE
As of Selenium 2.48.0, the findElement method on iOS driver no longer respects implicit timeout

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#1700]
## Expected Behavior -
When I search for an element that doesn't exist, the findElement method call should terminate after the implicit timeout interval has expired, throwing NoSuchElementException.

## Actual Behavior -
The findElement method call does not time out directly. Instead, the driver ends up shutting itself down with WebDriverException (timeOutBetweenCommand)

## Steps to reproduce -
Assemble an iOS automation configuration with the latest driver and Selenium Java 2.48.0 or newer.
Run a test that acquires an iOS driver session and searches for an element that doesn't exist.
The findElement method call will not time out as expected.

Revise your configuration to specify Selenium Java 2.47.0 and run your test again.
The findElement method call now times out as expected.

**Comment by lukeis** [comment]
"iOS driver" is not maintained here, you're either taking about ios-driver or appium. Either case you should log a bug with that project. 

Also when you do log a bug provide an actual reproducible test case

**Comment by sbabcoc** [comment]
This isn't an iOS bug. It's a core Selenium API bug. The driver is the driver - release 0.6.6-SNAPSHOT. If I run with this driver and Selenium Java 2.47.0, everything works as expected. If I run with this driver and Selenium 2.48.0, the implicit timeout is ignored.

**Comment by lukeis** [comment]
then please provide a reproducible test case
