### ISSUE TITLE
Make Actions.resetCompositeAction() overridable

### ISSUE THREAD

**Issue by phoenix384** [SeleniumHQ/selenium#1702]
Class org.openqa.selenium.interactions.CompositeAction.java can be extended. Even the class variables of org.openqa.selenium.interactions.Actions.java are protected and therefore made for Inheritance.
But there is no way to make Actions.java replace its internal CompositeAction object with an object of a class that extends CompositeAction, because Actions.resetCompositeAction() is private.
Would it be possible to raise its visibilty level to protected?

Use case:
I want every Actions chain to execute some code (waiting for Ajax) after its perform() method.
So I extended CompositeAction to override perform(). But I also have to extend Actions to make it use my class.

**Comment by barancev** [comment]
Actions implementation has been changed drastically, new W3C conformant implementation sends the whole bunch of actions to the driver all at once. Also, there is no resetCompositeAction method anymore.

Please look if the current implemetation is extendable in the way you need.

**Comment by barancev** [comment]
Closing the issue as not relevant to the current API.
