### ISSUE TITLE
Throw specific exception if element is not clickable

### ISSUE THREAD

**Issue by phoenix384** [SeleniumHQ/selenium#1704]
The exception introduced with #1202 that is thrown when an element is not clickable unfortunately is a WebDriverException. It would be great if it could be a subtype of WebDriverException (or e.g. even a subtype of InvalidElementStateException.
In cases where you want to handle those errors you don't want to catch all WebDriverExceptions.

**Comment by oceanchow** [comment]
good point, i agree

**Comment by barancev** [comment]
ElementNotInteractableException serves this purpose, there is no need in another exception.

**Comment by shs96c** [comment]
Closed in bd9d415b3f91b6f6cec29e155e875ccbae289c9f

**Comment by barancev** [comment]
Note that ElementNotInteractableException is a subclass of InvalidElementStateException
