### ISSUE TITLE
Firefox not loading profile correctly

### ISSUE THREAD

**Issue by zoro25** [SeleniumHQ/selenium#1706]
## Steps to reproduce -
First create new Firefox Profile Win+R and then type Firefox -P enter new profile details
Run code below.  (C#)

private IWebDriver driver;
  public void SetupTest()
        {
            string path = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + @"\Mozilla\Firefox\Profiles";
                     string[] pathsToProfiles = Directory.GetDirectories(path, "*.NewfolderName",                  SearchOption.TopDirectoryOnly);

              if (!allProfiles.ExistingProfiles.Contains("NewfolderName"))
            {
                throw new Exception("NewfolderName firefox profile does not exist, please create it first.");
                //to create a FF profile press win+R and the type in FireFox -p
            }
           
            if (pathsToProfiles.Length != 0)
            {
                FirefoxProfile profile = new FirefoxProfile(pathsToProfiles[0]);
            profile.SetPreference("browser.tabs.loadInBackground", false);
            driver = new FirefoxDriver(profile);

            }
            else
            {
                driver = new FirefoxDriver();
            }

}

The workflow is fairly simple, 
1. Check profiledir paths and store as strings
2. check if profiledir we want to use exists? , if not prompt user to create
4. Now we know profiledir exists we want to create a new Webdriver profile with the dir of choice "NewfolderName"
4.  If not then create standard Firefox Driver using normal temp profile.

**Comment by jimevans** [comment]
I'm not sure exactly what you're asking for. If the Firefox driver is passed an existing profile directory, it should use that profile as a template and copy its contents into a new anonymous profile. It will not use the existing profile in situ so as to support multiple simultaneous instances of Firefox. This is by design.

**Comment by zoro25** [comment]
Hi Jim 
Thanks for your quick reply. 
It would seem in this case that the Firefox driver is as you say working as expected. 

I had misunderstood the logic behind the templating of profiles. 
I had thought that Webdriver would use the existing profile directory  (in situ)  if using FirefoxDriver and would create a new version using the main profile as a template if it was called using RemoteWebDriver which I had assumed would have been used if the user wanted to run their tests using the same profile template on another machine for example.

What you have said in your answer above makes perfect sense,
 once again thanks.
