### ISSUE TITLE
Offset Locators

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#1714]
## Expected Behavior -

Offset locators in UI Elements should be as abstract as UI Elements are. An UI Element should be given the chance to parse these offsets locators and find the actual web element.
## Actual Behavior -

Only xpath is supported spoiling the effort of creating abstract UI Elements

**Comment by ygmarchi** [comment]
I propose something like this in function `locateElementByUIElement`

```
            var uiSpecifier = new UISpecifier(uiSpecifierString);
	        var uiElement = this.getUIElement(uiSpecifier.pagesetName, uiSpecifier.elementName);
	        if (uiElement.resolveOffsetLocator) {
	        	var resolvedOffsetLocator = uiElement.resolveOffsetLocator (locators[1]);
	        	if (resolvedOffsetLocator) {
	        		locators[1] = resolvedOffsetLocator;
	        	}
	        }
```

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
