### ISSUE TITLE
Firefox 38.0.1 WebDriverException: java.lang.reflect.InvocationTarget with selenium 2.52.0

### ISSUE THREAD

**Issue by bhavicool** [SeleniumHQ/selenium#1715]
## Steps to reproduce -

Open FirefoxDriver class using selenium 2.52.0 version with FF 38.0.1 version...
Getting org.openqa.selenium.WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ll,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"DG Extension","description":null,"creator":null,"homepageURL":null},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files\\DGAgent\\firefox","installDate":1438171374298,"updateDate":1438171374298,"applyBackgroundUpdates":1,"bootstrap":true,"size":682318,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"17.0","maxVersion":"30.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":0}
1456744894303	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"b_Dr64UxgJTW","location":"app-global","version":"44.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1456742087369,"updateDate":1456742087369,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"44.0.2","maxVersion":"44.0.2"}],"targetPlatforms":[]}
1456744894303	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}

**Comment by barancev** [comment]
When you see a browser window open please check the Extensions list if Selenium WebDriver is enabled and has the proper version number (2.52)

**Comment by bhavicool** [comment]
How to check the extensions list..I have added selenium 2.52.0 in my pom.xml & running scripts using hub(2.52 selenium standalone server jar) & node. Also it loads slowly with that green loader but then Launching fails with unable to connect error message..

**Comment by barancev** [comment]
Can you see the browser window? As soon as it appears on the screen open the browser extension page and check Selenium WebDriver addon version and status.

**Comment by bhavicool** [comment]
No I am not able to see browser window..using Selenium 2.52.0 & FF 44.0.2 and getting Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. error message on console...

**Comment by lukeis** [comment]
please upgrade to selenium 2.53.1 if you are still encountering an issue with that version, log a new issue.
