### ISSUE TITLE
simpleXPathOffsetLocatorStrategy should unwrap results

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#1716]
## Expected Behavior -

core.firefox.unwrap should be used to verify the result:

```
    if (results.length > 0 && core.firefox.unwrap(results[0]) == pageElement) {
        return xpath;
    }
```
## Actual Behavior -

the code is instead:

```
    if (results.length > 0 && results[0] == pageElement) {
        return xpath;
    }
```

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
