### ISSUE TITLE
Selenium 2.51.0 compatibility issues with Mozilla Firefox 44.0.2

### ISSUE THREAD

**Issue by pro1oh1** [SeleniumHQ/selenium#1717]
Hi, 
I'm seeing some weird behaviour when trying to run protractor tests with the latest versions.
 
## Expected Behavior -
element.all(by.repeater('tab in $mdTabsCtrl.tabs')).get(1).click()

Should change to tab a position 1.
Works fine in chrome.

## Actual Behavior -
Nothing happens, and no error is displayed. Tests just move on to whatever comes next.

Everything appears to be working fine, until we try to interact with elements that should be visible, the tests fail with the error 'Element is not currently visible and so may not be interacted with'.

## Steps to reproduce -
Set up a simple html - angularjs app try to switch between tabs with protractor test.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by pro1oh1** [comment]
I think this is actually protractor related issue, I have logged an issue with the appropriate team and I'm closing this one.

Thanks.
