### ISSUE TITLE
FF 44, Webdriver 2.52: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. 

### ISSUE THREAD

**Issue by gsaimadhu** [SeleniumHQ/selenium#1719]
## Environment:
FF 44.0.2
Webdriver 2.52.0

## Expected Behavior -
Selenium should be able to work on the browser opened
## Actual Behavior -
Error. details below.
## Steps to reproduce -
FirefoxProfile firefoxProfile = new FirefoxProfile();
				    firefoxProfile.setPreference("xpinstall.signatures.required", false);				   
				    selenium = new FirefoxDriver(firefoxProfile);

Error details:

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
59226	addons.xpi	DEBUG	Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1456753859226	addons.xpi	DEBUG	Existing add-on {D19CA586-DD6C-4a0a-96F8-14644F340D60} in winreg-app-global
1456753859227	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\ganma05\\AppData\\Local\\Temp\\anonymous1960215169683480990webdriver-profile\\extensions\\fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1456753855693,"mt":1456753855603}},"winreg-app-user":{"ocplugin@webex.com":{"d":"D:\\webex\\ProductivityTools","e":false,"v":"2.0","st":1440999139845,"mt":1423665358000}},"app-global":{"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi","e":true,"v":"8.0.0.9103","st":1452090606000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"44.0.2","st":1456751668798,"mt":1455153612000}},"winreg-app-global":{"{D19CA586-DD6C-4a0a-96F8-14644F340D60}":{"d":"C:\\Program Files (x86)\\Common Files\\McAfee\\SystemCore","e":false,"v":"IDS_SS_VERSION","st":1376930652359,"mt":1376930652250}}}
1456753859228	addons.xpi	DEBUG	No changes found
1456753859232	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1456753859233	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1456753859236	addons.xpi	DEBUG	Calling bootstrap method startup on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 8.0.0.9103
1456753859267	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1456753859267	addons.manager	DEBUG	Provider finished startup: XPIProvider
1456753859267	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1456753859267	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1456753859268	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1456753859268	addons.manager	DEBUG	Starting provider: GMPProvider
1456753859271	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1456753859272	addons.manager	DEBUG	Provider finished startup: GMPProvider
1456753859272	addons.manager	DEBUG	Starting provider: PluginProvider
1456753859272	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1456753859272	addons.manager	DEBUG	Provider finished startup: PluginProvider
1456753859272	addons.manager	DEBUG	Completed startup sequence
1456753859355	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\ganma05\AppData\Local\Temp\anonymous1960215169683480990webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1456753859433	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1456753859433	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1456753859433	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1456753859514	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1456753859514	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1456753859515	addons.xpi-utils	DEBUG	Successfully read XPI database
1456753859570	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1456753859570	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1456753859570	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: file:///C:/Users/ganma05/AppData/Local/Temp/anonymous1960215169683480990webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:99)

**Comment by phoenix384** [comment]
I'm getting a similar error when using an existing Firefox profile via Grid. May have the same cause.

**Comment by barancev** [comment]
Accoring to the log, you're using Selenium 2.43.1

**Comment by gsaimadhu** [comment]
Thanks for the finding. I am surprised, Maven dependency is 2.52 but Appium
is of old version. There is a conflict.

*dependency that caused the issue:*
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-server</artifactId>
<version>2.52.0</version>
</dependency>

<dependency>
<groupId>io.appium</groupId>
<artifactId>java-client</artifactId>
<version>*2.1.0*</version> //using older version of selenium 2.43
</dependency>


*After modifying to the below way, the issue is resolved:*
<dependency>
<groupId>io.appium</groupId>
<artifactId>java-client</artifactId>
<version>3.3.0</version>
<exclusions>
<exclusion>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
</exclusion>
</exclusions>
</dependency>

<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
<version>2.52.0</version>
</dependency>
