### ISSUE TITLE
EnableMobileEmulation does not work when passing custom device settings.

### ISSUE THREAD

**Issue by maikerucouk** [SeleniumHQ/selenium#1722]
## Expected Behavior -

EnableMobileEmulation should enable mobile emulation including pixel ratio and touch screen abilities.

## Actual Behavior -
EnableMobileEmulation does nothing when a custom device settings object is passed. It does work when a Chrome supported device string is passed in ("Samsung Galaxy Note 3" for example).

I've peeked into the .dll at ChromeOptions.cs and it appears that dictionary2 is created within the following function but it not actually returned anywhere. It looks like only the user-string is being passed to dictionary1 which is being returned from the function.

---

`private Dictionary<string, object> GenerateMobileEmulationSettingsDictionary()
{
    Dictionary<string, object> dictionary1 = new Dictionary<string, object>();
    if (!string.IsNullOrEmpty(this.mobileEmulationDeviceName))
        dictionary1["deviceName"] = (object) this.mobileEmulationDeviceName;
    else if (this.mobileEmulationDeviceSettings != null)
    {
        dictionary1["userAgent"] = (object) this.mobileEmulationDeviceSettings.UserAgent;
        Dictionary<string, object> dictionary2 = new Dictionary<string, object>();
        dictionary2["width"] = (object) this.mobileEmulationDeviceSettings.Width;
        dictionary2["height"] = (object) this.mobileEmulationDeviceSettings.Height;
        dictionary2["pixelRatio"] = (object) this.mobileEmulationDeviceSettings.PixelRatio;
        if (!this.mobileEmulationDeviceSettings.EnableTouchEvents)
            dictionary2["touch"] = (object) (bool) (this.mobileEmulationDeviceSettings.EnableTouchEvents ? 1 : 0);
    }
    return dictionary1;
}`

---

## Steps to reproduce -

The following function should allow me to pass in custom device settings which enable mobile emulation.

`internal static IWebDriver GetWebDriver(this MobileDevice currentDevice)
{
	ChromeMobileEmulationDeviceSettings deviceSettings = new ChromeMobileEmulationDeviceSettings();

	deviceSettings.Width = 360;
	deviceSettings.Height = 640;
	deviceSettings.PixelRatio = 3;
	deviceSettings.UserAgent = "Mozilla/5.0 (Linux; U; Android 4.3; en-us; SM-N900T Build/JSS15J) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30";
	deviceSettings.EnableTouchEvents = true;

	ChromeOptionsFixed chromeOptions = new ChromeOptionsFixed();
	chromeOptions.EnableMobileEmulation(deviceSettings);

	IWebDriver driver = new ChromeDriver(chromeOptions);
	driver.Manage().Window.Size = new Size((int)deviceSettings.Width, (int)deviceSettings.Height);

	return driver;
}`

**Comment by jimevans** [comment]
Fixed in 306f16d
