### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms when using an existing profile via Grid

### ISSUE THREAD

**Issue by phoenix384** [SeleniumHQ/selenium#1725]
After upgrading from 2.47.1 to 2.52.0 Firefox 44 cannot be started with an existing profile via Grid. With 2.47.1 this worked fine.

## Expected Behavior -
Firefox should start on the remote machine using the existing profile.

## Actual Behavior -
Firefox starts but nothing happens after that. After some time a WebDriverException is thrown. I attached the complete log output as a file because it's quite lengthy. 
[log.txt](https://github.com/SeleniumHQ/selenium/files/153093/log.txt)

## Steps to reproduce -
```
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class Test {
	@org.junit.Test
	public void test() throws MalformedURLException {
		FirefoxProfile profile = new FirefoxProfile(new File("path/to/profile"));
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability(FirefoxDriver.PROFILE, profile);
		RemoteWebDriver driver = new RemoteWebDriver(new URL("http://grid.url:4444/wd/hub"), capabilities);
		driver.quit();
	}
}
```

**Comment by phoenix384** [comment]
> With 2.47.1 this worked fine.
To clarify: 2.47.1 with Firefox 38 ESR worked fine. Now it is 2.52.0 with Firefox 44.0.2.

Omitting the profile path (`new FirefoxProfile(null)`) works.
Instantiating a local FirefoxDriver instead of the RemoteWebDriver also works.

**Comment by lukeis** [comment]
Can you provide the profile in question?

Also have you tried to manually start the profile in Firefox 44?

**Comment by phoenix384** [comment]
You think there is a problem with the profile? Hmm, but why does it work with 2.47.1?
I can start Firefox with that profile on my local computer. Sending it to the remote machine fails.

**Comment by phoenix384** [comment]
Just created a fresh profile and tested again - same error. So it's not the profile.

**Comment by barancev** [comment]
It's related to profile because you told that
"Omitting the profile path (new FirefoxProfile(null)) works."

**Comment by phoenix384** [comment]
Yeah but it's not caused by my specific profile - it's not corrupt or something, because a fresh profile also causes this error.

**Comment by lukeis** [comment]
@phoenix384 but this is not broken in the general case. Here's an example where I start up a grid hub and a node that has Firefox (using 2.52.0)

    FirefoxProfile fp = new FirefoxProfile();
    DesiredCapabilities caps = DesiredCapabilities.firefox();
    caps.setCapability(FirefoxDriver.PROFILE, fp);
    WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4448/wd/hub"), caps);
    try {
      driver.get("http://google.com");

      Truth.assertThat(driver.getTitle()).contains("Google");
    } finally {
      driver.quit();
    }

this passes successfully for me. So you'll need to provide a way for us to reproduce your error

**Comment by phoenix384** [comment]
Your example code does not use an existing profile. It just creates a new one...

**Comment by divmgl** [comment]
This is happening to me as well. It's even worse with the Node driver. First, Selenium refuses to find Firefox even though it's installed in the right path (`/Applications`) and the correct folder is exported in `PATH`.

```
UnknownError: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
```

If I specify the binary directly, it refuses to even run.

```
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
```

**Comment by krmahadevan** [comment]
@phoenix384 
Maybe you could help share your firefox profile in question. That way we can recreate the same problem that you are experiencing. Best would be that you create a sample project on github, wherein you add your firefox profile to src/test/resources folder and just share the project here so that someone can try running it and see what is causing the problem.

**Comment by phoenix384** [comment]
As I already said, my specific Firefox profile is not causing the error since even a fresh Firefox profile does not work.
I started Firefox with with "firefox.exe --profileManager" and created a fresh brand-new profile.
After that I tried
```
FirefoxProfile profile = new FirefoxProfile(new File("path/to/brand/new/profile"));
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability(FirefoxDriver.PROFILE, profile);
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://grid.url:4444/wd/hub"), capabilities);
```
which fails.

**Comment by lukeis** [comment]
[issue1725_profile.zip](https://github.com/SeleniumHQ/selenium/files/384177/issue1725_profile.zip)

can reproduce the problem by following the proceedure described in previous comment. Attached is the profile that selenium generates that causes a crash to firefox.

Unzip the archive and execute the following command:

    XRE_PROFILE_PATH=/absolute/path/to/profile/anonymous8304245343301862188webdriver-profile MOZ_CRASHREPORTER_DISABLE=1 MOZ_NO_REMOTE=1 DYLD_LIBRARY_PATH=: NO_EM_RESTART=1 /Applications/Firefox.app/Contents/MacOS/firefox-bin -foreground

example was running firefox on OSX, change path to firefox-bin as appropriate.

@AutomatedTester

**Comment by lukeis** [comment]
actually, turns out my firefox wasn't up to date and I had multiple installed... cleaned up my local computer to only have one install and made sure it was up to date... can no longer reproduce the crash / problem.

**Comment by phoenix384** [comment]
Why do you close this issue? The error still exists.
I just replaced hub and nodes with a freshly installed Ubuntu 16.04. So everything is new, up to date and there is definitely only one Firefox installation.
But the problem from my initial comment still persists.
