### ISSUE TITLE
getCurrentURL of current frame not return the URL of the frame

### ISSUE THREAD

**Issue by gssatcc** [SeleniumHQ/selenium#1727]
## Expected Behavior -
Until recent releases of chromedriver it was possible to get the current URL of selected frame
## Actual Behavior -
At the moment the method there is no way to getCurrentURL of the frame but only on the main window.
## Steps to reproduce -
1. Go to URL with some iframe
2. Select the iframe
3. Use method like:
  currentUrl() {
        return browser.driver.getCurrentUrl();
    }
to get current URL

**Comment by AutomatedTester** [comment]
This is expected behaviour. If you require that frames url use `executeScript('return document.location.href');`
