### ISSUE TITLE
Python Selenium Client is by default resolving ip adresses and not sending domain names

### ISSUE THREAD

**Issue by aluedeke** [SeleniumHQ/selenium#1729]
## Expected Behavior -

If the configured endpoint is app.testobject.com the HTTP request should got to app.testobject.com and not the ip address behind app.testobject.com
## Actual Behavior -

when setting the selenium endpoint to a domain the outgoing http request is going to the ip adress. That confuses WebServers which are proxying commands to the selenium backend, as they usually use domain names and not ip addresses to find the right config.
## Steps to reproduce -

Initiate a session to an non local endpoint (e.g. one of the cloud testing providers like sauce and browserstack). Record the http requests using Charles Proxy (or Wireshark). The request is send to an ip instead to the domain.

The problem can be found here:

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L165

I would recommend to change the default behaviour to false.

**Comment by Dude-X** [comment]
It seems this commit added the resolve_ip flag:
https://github.com/SeleniumHQ/selenium/commit/d4af5ecfa22642713162d0e87c4b198ff259ba25
to support the Edge driver.

**Comment by aluedeke** [comment]
i am actually fine with resolving the ip (why ever this is needed, don't know any software doing something like that), i just believe the default should be not resolving the ip, like e.g. any web browser in the world does it.

**Comment by mehmetg** [comment]
This is causing #2509. Is there a reason why one would want to resolve the ip first? 

Disabling that solves #2509.

**Comment by Ceyaje** [comment]
+1

**Comment by windmgc** [comment]
+1 for this, the default behavior of resolving urls into ips will be confusing and hard to debug when you are using some techniques like nginx reverse proxy.

**Comment by beastea** [comment]
+1
