### ISSUE TITLE
Unable to launch Chrome with option "AddTracingCategory" .NET

### ISSUE THREAD

**Issue by nessou** [SeleniumHQ/selenium#1731]
Hello, 

**## Expected Behavior -**# 
Start Chrome driver using the option "PerformanceLoggingPreferences" to collect events from Network domain.  It seems like the issue  #1591 was not fixed.

**## Actual Behavior -**#
I am trying to launch Chrome using the option "PerformanceLoggingPreferences" but i got this error : 
unknown error: cannot parse capability: chromeOptions

from unknown error: cannot parse perfLoggingPrefs

from unknown error: unrecognized performance logging option: tracingCategories

  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64)

**## Steps to reproduce -**#
Selenium DLL : 2.52
Chrome version : 48
ChromeDriver version : 2.21.371459

`ChromePerformanceLoggingPreferences perfLogPrefs = new ChromePerformanceLoggingPreferences();
ChromeOptions options = new ChromeOptions();
perfLogPrefs.AddTracingCategories(new string[] { "devtools.timeline" });
options.PerformanceLoggingPreferences = perfLogPrefs;

IWebDriver driver = new ChromeDriver(options);`

Thank you.

**Comment by jimevans** [comment]
If you'd looked at the diff for the commit attached to #1591 (d57f406), you'd have seen what the fix actually was, and why the "incorrect" (though documented) value was still being sent. Nevertheless, this is fixed in revision 13510db.
