### ISSUE TITLE
Firefoxdriver is still hardcoding a port, for internal use, causing collisions in concurrent runs

### ISSUE THREAD

**Issue by binodpanta** [SeleniumHQ/selenium#1732]
## Expected Behavior -

I expected to see that the SocketLock uses a random port or a port based on the webdriver_firefox_port I pass in as a profile preference. But it seems it is using a hardcoded port-1 which always gives it port 7054, causing collisions in concurrent sessions.

https://github.com/SeleniumHQ/selenium/blob/ab1e647d0fc8fc39e6b00ae94321ab228b6728f2/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L304
## Actual Behavior -

you will see that webdriver_firefox_port does honor this value, but if you inspect the SocketLock under these objects, it still uses 7054 all the time! I think that should be either based on this port or another randomly selected port
## Steps to reproduce -

Run any Firefoxdriver test, but pass in a profile prefernce of    profile.setPreference(FirefoxProfile.PORT_PREFERENCE, openPort);

**Comment by binodpanta** [comment]
Any updates on this? Is this already addressed by Marionette or should we expect this bug fix in Selenium java bindings for Firefox too?

**Comment by binodpanta** [comment]
We are using code like this now using reflection to avoid the hardcoded 7054 port. Basically we are forcing firefoxdriver to use a port other than 7054, (randomly chosen in a range), so that we can run multiple firefox sessions in our system, without causing race conditions

Can someone verify that Marionette won't have this issue? We are still using Firefoxdriver since Marionette is not ready with all the features, so we have to work around this issue somehow.

134	    private void modifyFirefoxDriverSocketLock(){
135	        PortFinder portfinder = new PortFinder.Builder().withRange(10000, 20000).build();
136	        int port = portfinder.getOpenPort();
137	        String host = "localhost";
138	        String classVariable = "localhost";
139	        String className = "org.openqa.selenium.internal.SocketLock";
140	        
141	        logger.info("Firefox driver uses port 7054 as a mutex while starting up. Lets avoid that and use port [{}]", port);
142	        final Field field;
143	        final Field modifiersField;
144	                        
145	        try {
146	                        field = Class.forName(className).getDeclaredField(classVariable);
147	                        modifiersField = Field.class.getDeclaredField("modifiers");                   
148	                        modifiersField.setAccessible(true);
149	                        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
150	                        field.setAccessible(true);
151	                Object oldValue = field.get(Class.forName(className));
152	                field.set(oldValue, new InetSocketAddress(host, port));
153	                } catch (NoSuchFieldException | SecurityException
154	                                | ClassNotFoundException |IllegalArgumentException | IllegalAccessException e) {
155	                        logger.info("Not able to modify firefox driver'ss behavior, will revert back to port 7054");
156	                }  catch (Exception ex){
157	                        logger.info("unexpected behavior occured when trying to modify firefoxdriver socketlock port, will revert back to port 7054");
158	                }
159	    }

**Comment by barancev** [comment]
SocketLock is not used anymore (and recently deleted from the code tree)
