### ISSUE TITLE
How to open new window (OpenWindow command) in iphone devices using selenium webdriver

### ISSUE THREAD

**Issue by angalavamshi** [SeleniumHQ/selenium#1734]
I am unable to open new window in devices using below code which is working as expected in FF, CH and IE browsers.
I am using below javacsript code to open new window:
((JavascriptExecutor)driver).executeScript("window.open("http://www.gmail.com");");

## Expected Behavior -
With the above code it has to open a new window with the given url.
## Actual Behavior -
New window is not opening with above code and it is not throwing any error.
## Steps to reproduce -
Step 1: Open a window using below code:
   driver.get("http:www.google.com");
Step 2: Do some operations on opened window
Step 3: Try to open another window using below code:
  ((JavascriptExecutor)driver).executeScript("window.open("http://www.gmail.com");");
Step 4: switch focus to newly opened window

But i was unable to open new window in devices with below mentioned capabilities:

DesiredCapabilities caps = DesiredCapabilities.iphone();
            caps.setCapability("platform", "OS X 10.10");
            caps.setCapability("version", "9.0");
            caps.setCapability("deviceName","iPhone Simulator");
            caps.setCapability("deviceOrientation", "portrait");
I am using selenium version 2.48.2

Please provide any solution.

**Comment by lukeis** [comment]
This bug belongs with either appium or ios-driver, whichever one you are using, log a bug there.
