### ISSUE TITLE
Maven Download Corrupted Jar Files From SeleniumHq

### ISSUE THREAD

**Issue by Reijiruo** [SeleniumHQ/selenium#1735]
## Expected Behavior -
Maven to download correct jar files of seleniumhq

## Actual Behavior -
Maven download corrupted jar files
Contents of the corrupted jar files contains html tag:
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style type="text/css">
            html, body, #partner, iframe {
                height:100%;
                width:100%;
                margin:0;
                padding:0;
                border:0;
                outline:0;
                font-size:100%;
                vertical-align:baseline;
                background:transparent;
            }
            body {
                overflow:hidden;
            }
        </style>
        <meta content="NOW" name="expires">
        <meta content="index, follow, all" name="GOOGLEBOT">
        <meta content="index, follow, all" name="robots">
        
        <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport">
    </head>
    <body>
        <div id="partner"></div>
        <script type="text/javascript">
            document.write(
                    '<script type="text/javascript" language="JavaScript"'
                            + 'src="//sedoparking.com/frmpark/'
                            + window.location.host + '/'
                            + 'tierraexpired'
                            + '/park.js">'
                    + '<\/script>'
            );
        </script>
    </body>
</html>
![attempttoopenjarfile](https://cloud.githubusercontent.com/assets/17617343/13497136/dca10538-e121-11e5-8aed-a69c799d1714.png)
![contentsofjarfile](https://cloud.githubusercontent.com/assets/17617343/13497137/dca1a632-e121-11e5-8e49-d8870f7cd978.png)

## Steps to reproduce -
Add org.selenium.seleniumhq as a dependency in the pom.xml file:
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-ie-driver</artifactId>
            <version>2.52.0</version>
</dependency>

Run a mvn -skipTests=true clean install against the pom.xml file
Go to the repository -> org -> seleniumhq -> selenium -> selenium-ie-driver -> 2.52.0
Attempt to open the jar file -> Error complaining about the file being corrupt or invalid
Attempt to open the jar file with Notepad++ -> see html tag

**Comment by lukeis** [comment]
It would appear you have some kind of proxy between yourself and maven central. And it appears malicious. Please check your ~/.m2/settings.xml or if you have a generic proxy set on your machine or if you have some kind of virus on your host. 


I've verified the jar in question is not corrupt:
http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-ie-driver/2.52.0/selenium-ie-driver-2.52.0.jar

**Comment by Reijiruo** [comment]
Thanks Lukeis,

Found out that my artifactory is pulling it from somewhere else, codehaus...
