### ISSUE TITLE
TxTexTControl is not resolved in Selenium Webdriver C#. TxTexTControl  is Active X control.

### ISSUE THREAD

**Issue by Aravind27** [SeleniumHQ/selenium#1742]
## Expected Behavior -

The Id Should resolve in IWebElement object or it should be resolved in " Var " or " object " types.

## Actual Behavior -

It throws exception.

## Steps to reproduce -
We have a TxTexTControl - " Active x Control" which resides in out Asp.Net page. when we try access the element  by the following lines . It thorws exception

here TxTexTControl is ID of the control.

driver.FindElement(By.Id("TxTextControl"));  or 
((IJavaScriptExecutor)driver).ExecuteScript("return document.getElementById('TxTextControl');")
Exceptions :  threw an exception of type 'OpenQA.Selenium.StaleElementReferenceException'

**Comment by lukeis** [comment]
we don't support active x controls with webdriver
