### ISSUE TITLE
Provide raw HTML file and request the rendering output

### ISSUE THREAD

**Issue by pedro93** [SeleniumHQ/selenium#1745]
Is it possible to provide selenium with a raw HTML file and receive the corresponding rendered screenshots as well as any HTML correction that might have occurred in the browser?
I am not sure if this is the correct place to ask this question, any help would be greatly appreciated!

**Comment by lukeis** [comment]
you can ask on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

But to answer the question, selenium webdriver has a getPageSource method. Although it will not be the raw HTML sent from the server, rather how the DOM is represented after javascript may have manipulated it. If you want / need the raw HTML then you'll need to use a Proxy to record the traffic and then fetch the raw html from the proxy (I would recommend checking out [browsermob-proxy](https://github.com/lightbody/browsermob-proxy) )
