### ISSUE TITLE
 i want use selenium action ,mouse move to some element,the first is success but second is fail

### ISSUE THREAD

**Issue by Huowenbin** [SeleniumHQ/selenium#1748]

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Huowenbin** [comment]
thanks,i finished this problem;
