### ISSUE TITLE
DNS Resolution

### ISSUE THREAD

**Issue by pankaj-sukale** [SeleniumHQ/selenium#1752]
This is an improvement ticket. Please have a look.
## Expected Behavior -
Remaps host file entries for Selenium automation.
If you have application running on multiple servers(like primary, secondary etc.) and you want to run your selenium automation suite against a specific server you can achieve it but by adding DNS host mapping in your host file located at following windows box location
**windows/system32/drivers/etc/**. 
This is done manually by most of the automation tester. Can be automated with no manual intervention using BrowserMob Proxy. BrowserMob Proxy a free utility to help web developers.
## Actual Behavior -

Request here is can Selenium team incorporate it internally.
https://github.com/lightbody/browsermob-proxy#dns-resolution

## Steps to reproduce -
Following is a demo URL with steps to achieve this.
http://switchhostinselenium.blogspot.in/2016/03/dns-resolution-in-selenium-automation.html

**Comment by lukeis** [comment]
We don't have interest in maintaining a DNS utility like this in the selenium project. It seems like you've shown a nice blog on how one would achieve this using browsermob proxy. I would recommend that approach (or any other third party library that achieves this) for those wanting this feature too.

**Comment by pankaj-sukale** [comment]
Thanks Lukies, Sound good to me. :+1:
