### ISSUE TITLE
fail to click button control in ie11 browser on windows 8.1 

### ISSUE THREAD

**Issue by xianhoublog** [SeleniumHQ/selenium#1755]
## Expected Behavior -
button clicked ,new page show up
## Actual Behavior -
after click the button, page not jump
## Steps to reproduce -
public class CopyOftestClick {

	public WebDriver driver;

	@Test
	public void tabbar_actions_s1() throws Exception {
		
		System.setProperty("webdriver.ie.driver",
				"c:\\tools\\IEDriverServer.exe");

		driver =new InternetExplorerDriver();
		driver.manage().window().maximize();
	    driver.get("http://www.google.com");
    System.out.println("Page title is: " + driver.getTitle());
    Assert.assertEquals("Google", driver.getTitle());
    WebElement element = driver.findElement(By.name("q"));
    element.sendKeys("Browser Stack");
    element.submit();
Thread.sleep(5000)
		
	}

selenium 25.2+java+ junit

**Comment by xianhoublog** [comment]
I resolved this issue via add following arguments ,
but whether could build a new ieDriver what doesn't need add those arguments?
		
		System.setProperty("webdriver.ie.driver",
				"c:\\tools\\IEDriverServer.exe");
		
		DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();

		ieCapabilities.setCapability("nativeEvents", false);    
		ieCapabilities.setCapability("unexpectedAlertBehaviour", "accept");
		ieCapabilities.setCapability("ignoreProtectedModeSettings", true);
		ieCapabilities.setCapability("disable-popup-blocking", true);
		ieCapabilities.setCapability("enablePersistentHover", true);

		driver = new InternetExplorerDriver(ieCapabilities);

**Comment by green-mdoerflinger** [comment]
I tried doing the same, in Windows 10 using IE11 setting *nativeEvents* to *false* does not solve the issue. Clicks still don't work.

**Comment by lukeis** [comment]
if this issue is occurring for you, then please provide a complete reproducible script with sample page where it occurs (or jsfiddle.net creation of a page that shows the issue).

closing as original reporter resolved their issue
