### ISSUE TITLE
Node configuration with JSON

### ISSUE THREAD

**Issue by Buzz2Buzz** [SeleniumHQ/selenium#1756]
Hi,

I didn't really know where to post it, so I think an issue might be ok.
When configuring a node with a JSON file, we've got:
```
{"browserName": "firefox",
  "platform": "WINDOWS"}
```

For Chrome and IE, we need to provide the custom path to driver. But, the driver property key is in the form `webdriver.BROWSER.driver`

Shouldn't it be better to be something like `driver` or `webdriver` to properly match a POJO class for example ?
Because we can face:
```
{"browserName": "chrome",
"webdriver.chrome.driver": "chrome",
  "platform": "WINDOWS"}

{"browserName": "internet explorer",
"webdriver.ie.driver": "chrome",
  "platform": "WINDOWS"}
```

**Comment by lukeis** [comment]
There's lots of things to configure on a node, some of which I believe should be agnostic to the grid architecture. 

Where the browser is or the driver executable is should be one of those things. 

In this case, I consider it best practice to put that on each node itself, in the command line to launch the selenium server. The node is the place that has it installed and should be the (only) thing responsible for telling selenium where it is. 

This sort of discussion is better suited on a mailing list. Either selenium-users or selenium-developers (Google groups)
