### ISSUE TITLE
Slow/incomplete page load in the browser launched by selenium

### ISSUE THREAD

**Issue by vinaybond** [SeleniumHQ/selenium#1760]
I am using selenium WebDriver using RobotFramework. The major problem we are facing is, my tests are timing out even after setting timeout as high as 10 minutes. It happen with any browser I use. These thing works much faster If I run test manually (with all browser cache/data/cookie cleared). These are the other things I have observing for few months.

- Some component are never loaded (I check the call trace using BrowserMob Proxy and we found nothing unusual)
-  "Click Element" does not work in many cases. Clicking on element triggers some action but that action is not always trigerred in automation. Manually it works all the time. 

Notes: 
- This is happening on FF and Chrome. (IE is not working for me at all)
- App server and automation suite is in LAN so latency is not an issue
- No other heavy process is running at this time
- This is not an application issue as we spent 2 month confirming that. 
- Issue persist even if with firefox default profile 
- I tried it with different selenium versions. (2.45 - 2.52)
- I took latest driver for chrome. Broweser: FF 40+ and GC 48

Let me know if you need any other detail.

**Comment by lukeis** [comment]
please provide a way to reproduce the issues you are seeing. That includes code / selenium scripts and example website or create one using jsfiddle.net if you can't provide a public link.

when this is provided we can reopen the issue and attempt to investigate further

**Comment by vinaybond** [comment]
Hi Luke,
Thank for offering the help. For now, I cant share a link and also not sure what details to put in the jsfiddle. Its a robotframework's simple command which look like this.

Click Element   ${myLocator}

- About "Click not working", I posted that question separately and got to know that Selenium wait for element in present in the dom but it cant identify if the required JS file is loaded or not 
- About Timeout, I wanted to know if someone is facing similar issue and found something.
