### ISSUE TITLE
Link not working: Selenium Downloads - Previous Releases

### ISSUE THREAD

**Issue by sdettmer** [SeleniumHQ/selenium#1764]
## Expected Behavior -
When clicking "Previous Releases", browser should show some list of old versions allowing the user to download previous (old) releases from some archive server.

## Actual Behavior -
Browser is redirected to https://github.com/seleniumhq/selenium-google-code-issue-archive, where not old releases, but old issues are show.

## Steps to reproduce -
Load URL "https://code.google.com/p/selenium/downloads/list?can=1&q=" or navigate to "Selenium Downloads" - "Previous Releases".

**Comment by lukeis** [comment]
fixed in seleniumhq/www.seleniumhq.org@e7f94adbd56baa3b77fab2b4fad778e7cfdc11bd
