### ISSUE TITLE
IDE: alert() fails in a modified test case

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1768]
Open and modify an existing test case, or create a new test case, with one following Selenese command. (Do not open a saved test case with the following command. If you do, then modify the test case - e.g. by adding whitespace - before running it.)

getEval | alert('hi')

Run by 'Play current test case' button. As expected, the alert shows up (saying 'hi'). However, the test case fails.

The problem only happens when you have a new test case, or you modify a test case (regardless of whether you then save it or not), and if it calls getEval | alert(...). However, if you load such a test case and you run it without any modification, then the problem doesn't show up.

Runs: 1
Failures: 1

Log:

```
[info] Playing test case Untitled
[info] Executing: |getEval | alert('h') | |
[info] script is: alert('h')
[error] Threw an exception: 
[info] Test case failed 
```

---

Test with a blank Firefox profile, Selenium IDE 2.9.1 and following versions of Firefox:

Firefox 44.0
"E:\SW\Mozilla Firefox 45.0\firefox.exe" -no-remote -P alert
"C:\Program Files\Mozilla Firefox 46.0b1\firefox.exe" -no-remote -P alert
"E:\SW\Mozilla Firefox Nightly 2016-03-07\firefox.exe"  -no-remote -P alert
(e10s Multiprocessing turned off)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
