### ISSUE TITLE
IDE: a subsequent call to open() fails with multiprocessed Firefox (e10s)

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#1769]
Test case with two subsequent _open_ commands fails. The URL may be the same. The problem doesn't seem to be specific to the file being opened.

open | file:///E:/mine/tmp/case_e10s_2.html
open | file:///E:/mine/tmp/case_e10s_2.html

(Change timeout setting to e.g. 1500, so you don't wait for a minute.)

```
    [info] Playing test case case_e10s_2
    [info] Executing: |open | file:///E:/mine/tmp/case_e10s_2.html | |
    [error] Timed out after 1500ms
    [info] Executing: |open | file:///E:/mine/tmp/case_e10s_2.html | |
    [error] modifyWindow: Window was closed!
    [error] Current window or frame is closed!
    [info] Test case failed 
```

Blank Firefox profile with Selenium IDE 2.9.1. Either
- "E:\SW\Mozilla Firefox Nightly 2016-03-07\firefox.exe"  -no-remote -P alert
- "E:\SW\Mozilla Firefox Nightly 2016-02-25\firefox.exe"  -no-remote -P alert
  with e10s - multiprocessing - turned on.

Please, would you confirm this. Then I'm willing to report it in Mozilla's bugzilla.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
