### ISSUE TITLE
Cannot build master at 6bef2c6e55997b6da158ad4ac74b44e2523ef849

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#1772]
## Expected Behavior -
`./go //javascript/atoms:test:run`
... success
<success!> 
## Actual Behavior -
```
./go //javascript/atoms:test:run
(in /work/selenium)
Preparing: //java/client/src/org/openqa/selenium/firefox:amd64 as build/java/client/src/org/openqa/selenium/firefox/amd64
Preparing: //java/client/src/org/openqa/selenium/firefox:x86 as build/java/client/src/org/openqa/selenium/firefox/x86
Writing: build/java/server/src/org/openqa/grid/selenium/selenium.classpath
Testing: //javascript/atoms:test_ff 
Testing: //javascript/atoms:test_marionette 
go aborted!
org.apache.tools.ant.BuildException: Test org.openqa.selenium.javascript.ClosureTestSuite failed
```

## Steps to reproduce -
Linux 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

fresh git clone 
`./go //javascript/atoms:test:run`

**Comment by lukeis** [comment]
I get the same... the error is in the junit results xml files the tests generate (in build/test_logs )

java.lang.NullPointerException at org.openqa.selenium.testing.drivers.DefaultDriverSupplier.get(DefaultDriverSupplier.java:60)


Which looks like something is missing form the default setup to get the atoms tests running with marionette

**Comment by johnjbarton** [comment]
`./go test_chrome` also fails with many "java.lang.RuntimeException: Exception creating driver" messages.

**Comment by jleyba** [comment]
`./go test_chrome` worked for me at 9665dd7d4bc0e521adb20bff2ce18501ae78289a.

Do you have the chromedriver on your PATH?

**Comment by johnjbarton** [comment]
> Do you have the chromedriver on your PATH?

No.

**Comment by johnjbarton** [comment]
After adding the directory containing chromedriver from https://sites.google.com/a/chromium.org/chromedriver/downloads,
to my PATH, `./go test_chrome` passes, thanks!

**Comment by johnjbarton** [comment]
Any news?  How can there be pull requests if devs can't test master?  Should I be doing something other than what the doc says?

**Comment by gerixx** [comment]
I have the same problem with today's fork. I'm a newbie in building Selenium, is any expert out there who can shed some light on that, thanks!

**Comment by lukeis** [comment]
the travis config file has what you should be using as targets -

https://github.com/SeleniumHQ/selenium/blob/master/.travis.yml

we're mostly passing in travis now :) just getting some intermittent failures still on the slow hardware

If you're still having troubles, please come chat with us on IRC or slack
