### ISSUE TITLE
Grid V3 Hub needs to be able to accept 2.X nodes / forward sessions appropriately

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/selenium#1774]

**Comment by krmahadevan** [comment]
@lukeis 
If you could please help add some context to this in terms of what is the expectation, I could try to work on this and raise a PR to address this issue.

**Comment by lukeis** [comment]
I checked on this the other day... and I think everything is in place as is... I'm going to close and I'll just watch to make sure no one deletes the required classes :)
