### ISSUE TITLE
browser.manage().logs().get('browser') omits arguments after the first

### ISSUE THREAD

**Issue by mitar** [SeleniumHQ/selenium#1775]
When processing the log messages using `browser.manage().logs().get('browser')`, it seems that `message` property only contains the first argument to the `console.log` in the browser (using Chrome driver) and not all arguments.

See https://github.com/angular/protractor/issues/2390 for a related issue.

**Comment by jleyba** [comment]
This is an issue with the ChromeDriver itself:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=669

**Comment by mitar** [comment]
It seems Chrome exposes `ConsoleMessage.parameters`, but just that gets lost somewhere.

**Comment by dlants** [comment]
This should now be possible, since this issue will be fixed in ChromeDriver 2.42 https://bugs.chromium.org/p/chromedriver/issues/detail?id=669#c22

**Comment by mitar** [comment]
Hm, but it is now separated by spaces, you cannot really get original parameters back?

**Comment by dlants** [comment]
According to comment 5 https://bugs.chromium.org/p/chromedriver/issues/detail?id=669#c5 that should already be possible.

**Comment by mitar** [comment]
I think the comment you are liking shows that in the past it was not possible.
