### ISSUE TITLE
verifyLocation is not working in S.IDE 2.9.1 version

### ISSUE THREAD

**Issue by varshanihanth** [SeleniumHQ/selenium#1778]
## Steps to reproduce -Kindly see the below screen shot,  at ABC it should show error message but it didn't, Please help me how to resolve this issue

Environment :
OS: Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

![screenshot from 2016-03-10 16 02 03](https://cloud.githubusercontent.com/assets/14229099/13666930/0e94f384-e6da-11e5-842d-4ac0efc7348a.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
