### ISSUE TITLE
Caught org.openqa.selenium.WebDriverException: Exposing privileged or cross-origin callable is prohibited

### ISSUE THREAD

**Issue by nmcconom** [SeleniumHQ/selenium#1779]
## Expected Behavior -
Using firebug addon in Firefox I try to export har files using a JavascriptExecutor like below from the webdriver:

```
JavascriptExecutor js = (JavascriptExecutor) driver;

js.executeScript("window.NetExport.triggerExport('abcd')");
```

This used to work but in recent Firefox versions I get the following error:

`Caught org.openqa.selenium.WebDriverException: Exposing privileged or cross-origin callable is prohibited
`
I tried to get around this by setting a preference:

`profOpt.setPreference("security.fileuri.strict_origin_policy", false);
`

but it doesn't help.  I can see it work in Firefox versions up to version 33 but not the more recent ones

**Comment by jleyba** [comment]
This is an error from Firefox itself. Please direct questions to the user forum if you need help configuring Firefox for your use case.
