### ISSUE TITLE
delete_all_cookies and multiple workers

### ISSUE THREAD

**Issue by hwkongsgaard** [SeleniumHQ/selenium#1783]
## Expected Behavior -
Hi, when I run selenium with phantomjs, python celery using multiple workers. There seems to be conflict between the different sessions, or that sessions interfere with each other. 

Does driver.delete_all_cookies() delete cookie for all sessions?

Simple code example

```
class browser(Task):
    def __init__(self):
        dcap = dict(DesiredCapabilities.PHANTOMJS)
        dcap["phantomjs.page.settings.userAgent"] = (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53 "
            "(KHTML, like Gecko) Chrome/15.0.87"
        )
        self.driver = webdriver.PhantomJS(desired_capabilities=dcap)
        self.driver.set_window_size(1024, 768) # optional

    def get_data(self,x):
        x = json.loads(x)

        if True:
            self.driver.delete_all_cookies()
            self.driver.get('http://www.mysite.com')
            sbtn = self.driver.find_element_by_id( "ctl00_ctl00_MainWrap_MainContent_FullRegion_ContentLeftRegion_ContentLeftMenuRegion_RekoFilter_ctl00_tbVIN")
            sbtn.send_keys(x['key'])
            self.driver.find_element_by_id( "ctl00_ctl00_MainWrap_MainContent_FullRegion_ContentLeftRegion_ContentLeftMenuRegion_RekoFilter_ctl00_btnSearch").click()
            car_info = self.driver.find_element_by_class_name("carInfo")
        

@app.task(name='hent_bilnummer_biltema', base=browser)
def get_something(_):
    get_something.get_data(_)
```

## Actual Behavior -

Browser cannot find element, wrong page.

## Steps to reproduce -

It works with just one worker not multiple

**Comment by lukeis** [comment]
would appear that phantomjs stores all cookies in a default cookie file -
http://phantomjs.org/api/command-line.html ```--cookies-file```

as a workaround you can make sure that each session gets its own cookie file:

    import tempfile
    webdriver.PhantomJS(desired_capabilities=caps, service_args=["--cookies-file="+tempfile.mkstemp()[1]])

**Comment by hwkongsgaard** [comment]
Thanks, should be in the docs ;)

**Comment by lukeis** [comment]
it's in the phantomjs docs where i found it ;)
