### ISSUE TITLE
Python selenium tab feature works fine in Firefox but not in Chrome

### ISSUE THREAD

**Issue by mohanrajkumarplus** [SeleniumHQ/selenium#1786]
## Steps to reproduce -

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

browser = webdriver.Chrome('C:\\data\\books oae\\apex library\\chromedriver') #Firefox() 

browser.get('https://trello.com/login')
time.sleep(10)
emailElem = browser.find_element_by_id('user')
emailElem.send_keys('test123@gmail.com')
passwordElem = browser.find_element_by_id('password')
passwordElem.send_keys('test12345')
passwordElem.submit()

body = browser.find_element_by_tag_name("body")
body.send_keys(Keys.CONTROL + 't')

browser.get('https://todoist.com/Users/showLogin')
time.sleep(10)
emailElem = browser.find_element_by_id('email')
emailElem.send_keys('test123@gmail.com')
passwordElem = browser.find_element_by_id('password')
passwordElem.send_keys('test12345')
passwordElem.submit()

body = browser.find_element_by_tag_name("body")
body.send_keys(Keys.CONTROL + 't')

browser.get('https://asana.com/#login')
time.sleep(10)
emailElem = browser.find_element_by_id('login-email-login-modal')
emailElem.send_keys('test123@gmail.com')
passwordElem = browser.find_element_by_id('login-password-login-modal')
passwordElem.send_keys('test12345')
passwordElem.submit()

**Comment by lukeis** [comment]
first, selenium doesn't explicitly support tabs, you should just open a new window instead ```execute_script("window.open")```

second, chromedriver issues are tracked on the chromedriver project here:
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by mohanrajkumarplus** [comment]
Thank you for your detailed reply @lukeis :+1:
