### ISSUE TITLE
Python bindings firefox 44.0 certificate error

### ISSUE THREAD

**Issue by vyasgiridhar** [SeleniumHQ/selenium#1788]
## Expected Behavior -

profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True

should allow untruted certificate.
## Actual Behavior -

browser produces ssl_error_no_cypher_overlap error
## Steps to reproduce -

try opening any older server.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
