### ISSUE TITLE
Se3 server needs to collect logs in the same way as the Se2 standalone server

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#1790]
So that people can continue tracking sessions and getting good log data.

**Comment by lukeis** [comment]
I've started refactoring how hub/node/standalone configuration and command line args are passed in... I'll try to get a commit in to a branch for review later tonight (my time), it has some minor backwards compatibility with 2.X, so I won't push to master till after Tuesday.

**Comment by lukeis** [comment]
also, looks like this is already there...
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/selenium/GridLauncherV3.java#L123

closing for now :)

**Comment by shs96c** [comment]
We need an automated test to verify this. It should collect the same server logs as the current implementation, not just the ones from the driver.

**Comment by shs96c** [comment]
Good news: logging of commands and sessions is currently the same between an old 2.x server and the current 3.x standalone server.

Bad news: This is because it's hopelessly broken.

I'm going to spend a few cycles attempting to get it working again, then I'm going to abandon hope and say that this works in the same way, though not as intended.

**Comment by shs96c** [comment]
Good news: got basic logging working again. 

Bad news: I need to figure out how much memory this takes up, and then mitigate it if necessary.

**Comment by shs96c** [comment]
Landed f1daf662a0622b87918b389885f4016f8c81f867. I'm going to call that victory.
