### ISSUE TITLE
Firefox Driver sendKeysToActiveElement

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1792]
This is on Firefox 45 on OSX, with the Firefox Driver. I'm seeing this behavior both local & via remote server.
I tested with FF 45 before it was released and didn't see this behavior, and I'm pretty sure we're testing this in the CI. So, I'm not sure why I'm seeing this right now. Can anyone duplicate?
## Expected Behavior -

Post to session/:session_id/keys should type into body of page
## Actual Behavior -

Opening a page and sending key command is putting the text into the url bar:
<img width="382" alt="screen shot 2016-03-12 at 5 03 11 pm" src="https://cloud.githubusercontent.com/assets/777185/13725863/57493b8a-e874-11e5-8411-0be4fb343b4b.png">
## Steps to reproduce -

``````
-> POST session/942089a8-b772-4c9a-9a14-78ce2a76c5f8/url
   >>> http://127.0.0.1:4444/wd/hub/session/942089a8-b772-4c9a-9a14-78ce2a76c5f8/url | {"url":"http://ci.seleniumhq.org:2310/common/javascriptPage.html"}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"66"}17:02:30.845 INFO - Done: [new session: Capabilities [{rotatable=false, nativeEvents=false, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, version=, platform=ANY, cssSelectorsEnabled=true}]]
17:02:30.851 INFO - Executing: [get: http://ci.seleniumhq.org:2310/common/javascriptPage.html])
17:02:31.169 INFO - Done: [get: http://ci.seleniumhq.org:2310/common/javascriptPage.html]
<- {"state":"success","sessionId":"942089a8-b772-4c9a-9a14-78ce2a76c5f8","hCode":512158199,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}
-> POST session/942089a8-b772-4c9a-9a14-78ce2a76c5f8/keys
   >>> http://127.0.0.1:4444/wd/hub/session/942089a8-b772-4c9a-9a14-78ce2a76c5f8/keys | {"value":["ab"]}
     > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"16"}
17:02:31.174 INFO - Executing: [send keys to active: [ab]])
17:02:31.234 INFO - Done: [send keys to active: [ab]]
<- {"state":"success","sessionId":"942089a8-b772-4c9a-9a14-78ce2a76c5f8","hCode":31064293,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}```
``````

**Comment by dalelotts** [comment]
Seeing the same issue here. Any fix or workaround available?

**Comment by p0deje** [comment]
I've checked this using latest Firefox and GeckoDriver and I cannot reproduce this issue:

```
irb(main):001:0> require 'selenium-webdriver'
irb(main):002:0> driver = Selenium::WebDriver.for(:firefox)
irb(main):003:0> driver.get "http://google.com"
irb(main):005:0> driver.action.send_keys("foo").perform
=> nil
```

The code above fills "foo" in search form.

**Comment by barancev** [comment]
Let's think it has been fixed :)

**Comment by BillalPatel** [comment]
I am getting this same issue now. Works fine in Chrome but not in FF. Also works manually so it's not a bug with the environment on FF.
`$('.CompetitionSubscription-input.CompetitionSubscription-input--email').sendKeys('tester@testing.com);
action.keyEnter();`

**Comment by p0deje** [comment]
@BillalPatel Please create a new issue with a test case to reproduce the problem. Also, it would be better if you can have a test case that uses pure Selenium, not with Protractor.

**Comment by BillalPatel** [comment]
@p0deje Hi there, thanks for responding so soon. I think I have found a way around this so I am for it to be closed. Thanks!

**Comment by Y--** [comment]
@BillalPatel would you mind sharing your work around? Thanks!

**Comment by BillalPatel** [comment]
@Y-- I just changed it to:
`.sendKeys(protractor.Key.ENTER)`
I hope this helps you :)
