### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by dg-ratiodata** [SeleniumHQ/selenium#1802]
## Background

I'm using  `capybara` (2.6.2) to build an `rspec`-extension called [`proxy_rb`](https://github.com/fedux-org/proxy_rb) to do TDD of our HTTP proxy environments. Setting the proxy without any proxy authentication works fine. Authentication against proxies using the `BASIC`-scheme does not work.

This is a followup to https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/5209. Hope there's no other issue about this issue. I found none.
## Expected Behavior -

Selenium enters Username + Passwort for Proxy Authentication in Firefox.
## Actual Behavior -

Firefox shows Username + Passwort-Form which is closed after a short time span.

**Comment by stevenmccord** [comment]
Having this same issue trying to add a proxy that requires authentication.  I am utilizing Chrome but it still doesn't allow me to pass in a proxy with authentication.

**Comment by crownpku** [comment]
Hi, I'm using chromedriver with selenium python. I still cannot find a way to correctly handle proxy authentication, and all the methods I find through googling fail on my case. Any suggestions?

**Comment by Nolski** [comment]
I'm using geckodriver and also having issues when trying to use a proxy with basic auth.

```python
profile.set_preference("network.proxy.type", 1)
profile.set_preference("network.proxy.http", ip)
profile.set_preference("network.proxy.http_port", port)
profile.set_preference("network.proxy.ssl", ip)
profile.set_preference("network.proxy.ssl_port", port)
credentials = '{}:{}'.format(proxy_info['username'], proxy_info['password'])
credentials = b64encode(credentials.encode('ascii')).decode('utf-8')
# b64 encode username and password as is required by the `Proxy-Authentication` header
profile.set_preference("extensions.closeproxyauth.authtoken", credentials) 
```

**Comment by oleksiivasylenko** [comment]
2018, still facing proxy auth issues. 
![2018-08-10_105603](https://user-images.githubusercontent.com/28143505/43945870-2ea96938-9c8c-11e8-8189-c06d5fdc92d3.png)

C#, chromedriver 2.41. 

Would it be fixed? It's 877 days already behind :)

**Comment by scottie** [comment]
2019 still same issue....

**Comment by XcomegaX** [comment]
Still no way to enter Username and password....

**Comment by viseth** [comment]
Please it looks like, we all need this feature. Any expected delivery date or workaround ?
Most of companies requires a proxy authentication.
Feedback most appreciated. I keep trusting Selenium !

**Comment by viseth** [comment]
@cgoldberg any hints ? 
Here's the version I use selenium-server-standalone 3.141.59 , jdk-11.0.2. firefox:  60.6.1esr, geckodriver-v0.24.0.

I have tried:

> profile.SetPreference("network.proxy.http", "http://<someDOmain>\<user>:<pwd>@<proxy>:<port>")

OR 

>         String PROXY = "<proxy>:<port>"
>         Proxy proxy = new Proxy()
>         proxy.setProxyType(Proxy.ProxyType.MANUAL)
>         proxy.setHttpProxy(PROXY)
>         proxy.setSslProxy(PROXY)
>         proxy.setSocksProxy(PROXY)
>         proxy.setSocksVersion(5)
>         proxy.setSocksUsername("<someDOmain>\<user>")
>         proxy.setSocksPassword("<pwd>")
> 
>         options.setCapability(CapabilityType.PROXY, proxy)


Nothing works,

Thanks

**Comment by adiohana** [comment]
As a workaround, you can install any proxy add-on for firefox and send the basic authorization as a header - Basic {username:password}
We made our own light weight add-on and using it in FF.

**Comment by viseth** [comment]
@adiohana thanks for your feedback. I'll check that workaround. So no straightforward way to do it... since I need to check for other webbrowser (IE, Chrome).

**Comment by adiohana** [comment]
@viseth I'm sure there is a proper way to do it and fix the issue. I will try to dig deeper but it will take some time.
As for other browsers, in Chrome and FF you can use the same extension as long as you follow the API's. One more note, if you want to use an extension in Chrome Headless, this may not be possible (at least for Chrome v.63 so you will have to use a different workaround (Devtools API for example). 
Let me know if you need more examples.

**Comment by viseth** [comment]
@adiohana definitly if you can me to some example, it will be great and save me time. Thanks a lot !

**Comment by adiohana** [comment]
Code for extension is:

`browser.webRequest.onBeforeSendHeaders.addListener(
    handler,
    {urls: ["<all_urls>"]},
    ['requestHeaders', 'blocking']
);`

I'm using the localStorage to pass the username and password because I need it to be dynamic. If your's is always the same, you can state the value in the extension itself.

`function handler(details) {
    details.requestHeaders.push({name: "Proxy-Authorization", value: getAuthHeaderVal()});
    return {requestHeaders: details.requestHeaders};
};
function getAuthHeaderVal() {
    var res = localStorage.getItem('auth_header_value');
    if (res) {
        return res;
    } else {
        return "";
    }
}`

Then, when you launch your WebDriver, you can install the extension, get it's uuid and add values to localStorage like this:
`driver.get("moz-extension://" + uuid);
  driver.executeScript("localStorage.setItem('auth_header_value', 'Basic " + proxyHeaderValue + "')");
`

**Comment by viseth** [comment]
@adiohana all the given lines of code should go in the selenium java code ? To be honest I'm not acquainted with the browser exetension code as well as the handler (as this look more like a JS things).

**Comment by jclusso** [comment]
This is crazy that this is still broken :(

**Comment by luke-hill** [comment]
@shs96c should we close this in favour of https://github.com/SeleniumHQ/selenium/issues/6644 - As the main discussion about the complexities are being done there?

**Comment by oleksiivasylenko** [comment]
@adiohana, I've used that trick as far as I don't need headless, but now I need headless and it is not possible in that mode :(

**Comment by adiohana** [comment]
@oleksiivasylenko 
which browser you are using?
FF headless should work with extension.
Chrome headless will not work with extension and there is a workaround to use DevTools API to add headers for all requests. It will be available in Selenium 4 (https://github.com/SeleniumHQ/selenium/issues/6667). If you want, I can guide you how to do it manually until Selenium 4 will be released.

**Comment by oleksiivasylenko** [comment]
Thank you @adiohana! 
I remember I used Chrome. 
Please give me articles about workaround you mentioned.

**Comment by diemol** [comment]
Closed in favour of #6644, thanks for pointing it out @luke-hill

**Comment by limsammy** [comment]
> Code for extension is:
> 
> `browser.webRequest.onBeforeSendHeaders.addListener( handler, {urls: ["<all_urls>"]}, ['requestHeaders', 'blocking'] );`
> 
> I'm using the localStorage to pass the username and password because I need it to be dynamic. If your's is always the same, you can state the value in the extension itself.
> 
> `function handler(details) { details.requestHeaders.push({name: "Proxy-Authorization", value: getAuthHeaderVal()}); return {requestHeaders: details.requestHeaders}; }; function getAuthHeaderVal() { var res = localStorage.getItem('auth_header_value'); if (res) { return res; } else { return ""; } }`
> 
> Then, when you launch your WebDriver, you can install the extension, get it's uuid and add values to localStorage like this:
> `driver.get("moz-extension://" + uuid); driver.executeScript("localStorage.setItem('auth_header_value', 'Basic " + proxyHeaderValue + "')"); `

Hey there, attempting to use this solution for my Selenium app. How are you grabbing the internal UUID after loading the extension?

**Comment by adiohana** [comment]
i recently answered in SO
https://stackoverflow.com/q/56288424/3141682

**Comment by limsammy** [comment]
> i recently answered in SO
> https://stackoverflow.com/q/56288424/3141682

@adiohana mind if I take a quick peek at your maifest.json?

**Comment by adiohana** [comment]
@limsammy 

`{
  "name": "Name",
  "version": "1.0.31",
  "manifest_version": 2,
  "description": "Description",
  "background":  {
    "scripts": [ "background.js"]
  },
  "browser_action": {
    "default_icon": "startup.png",
    "default_title": "Title"
  },
  "icons": {
    "48": "startup.png"
  },

  "permissions": [
    "storage",
    "webRequest",
    "webRequestBlocking",
    "<all_urls>"
  ]
}`
