### ISSUE TITLE
Mouse Cursor position is locked when using "Action...Perform();"

### ISSUE THREAD

**Issue by espaciomore** [SeleniumHQ/selenium#1803]
## Expected Behavior -

Mouse Cursor must follow any Mouse input.
## Actual Behavior -

Mouse Cursor is getting locked at a particular position whenever I'm using *\* Action...Perform();**
## Steps to reproduce -

**Win 7** | **IE**
Use any Mouse input with *\* Action...Perform();*\* then try to Hover over any other element.

**Comment by espaciomore** [comment]
Opened this issue because I couldn't comment on another [related issue](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/1835)

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information.
