### ISSUE TITLE
Thousands of "Error: ConnectFailure" with SuppressInitialDiagnosticInformation = true (C#)

### ISSUE THREAD

**Issue by alfsb** [SeleniumHQ/selenium#1805]
## Expected Behavior -

No output.
## Actual Behavior -

Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
Error: ConnectFailure (Connection refused)
## Steps to reproduce -

var serv = OpenQA.Selenium.PhantomJS.PhantomJSDriverService.CreateDefaultService();
serv.SuppressInitialDiagnosticInformation = true;

this.Driver = new OpenQA.Selenium.PhantomJS.PhantomJSDriver( serv );

**Comment by barancev** [comment]
PhantomJS is not supported anymore
