### ISSUE TITLE
Selenium fetching wrong system info using os.arch

### ISSUE THREAD

**Issue by hvardhan89** [SeleniumHQ/selenium#1811]
## Steps to reproduce - In a project which use Selenium API, try to print the OS architecture of current machine.
e.g System.out.println(System.getProperty("os.arch"));
This display the bit which JDK architecture use.
I have 64 bit Window 7 and 32 bit JDK. The above line of code print the 32 bit.

**Comment by lukeis** [comment]
This is not a selenium issue, rather with Java itself
http://stackoverflow.com/a/2110847

**Comment by hvardhan89** [comment]
When I run the same code independently, it fetch the correct info,
e.g.
```
psvm{
System.out.println(System.getProperty("os.arch"));
}
```
but when I want get that property anywhere inside the selenium project it return the JVM architecture rather than OS.
