### ISSUE TITLE
IEDriverServer 2.52.2 throws "Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'OpenQA.Selenium.Proxy'"

### ISSUE THREAD

**Issue by sophiaatif** [SeleniumHQ/selenium#1812]
## Expected Behavior -
As stated in Changelog, it should resolve the issue of not finding element, in my case IE failed to find elements when it opens a new tab/window in IE11.

## Actual Behavior -
IE is launched but crashes with this exception :	"Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'OpenQA.Selenium.Proxy'."

## Steps to reproduce -
I have just replaced IEDriverServer to 2.52.2, on hub, test server and node where i is running, if I try it only on local it throes the same error. 
Is there something that Im missing? the same code works with previous versions.

**Comment by jimevans** [comment]
Please supply the .NET code that produces the error.

**Comment by sophiaatif** [comment]
`    public T GetCapability<T>(String type)
    {
      var h = this.Capabilities;
      object c = this.Capabilities.GetCapability(type);
      return c == null ? default(T) : (T)c;
    }`
`    public void LogCapabilities()
    {
      Log.Info("Browser.................{0}", GetCapability<String>(CapabilityType.BrowserName));
      Log.Info("Browser version.........{0}", GetCapability<String>(CapabilityType.Version));
      Log.Info("Platform................{0}", GetCapability<OpenQA.Selenium.Platform>(CapabilityType.Platform).PlatformType);
      Log.Info("JavaScriptEnabled.......{0}", GetCapability<Boolean>(CapabilityType.IsJavaScriptEnabled));
      Log.Info("AcceptSslCertificates...{0}", GetCapability<Boolean>(CapabilityType.AcceptSslCertificates));
      Log.Info("Native Events...........{0}", GetCapability<Boolean>(CapabilityType.HasNativeEvents));
      Log.Info("Rotatable...............{0}", GetCapability<Boolean>(CapabilityType.Rotatable));
      Log.Info("SupportsFindingByCss....{0}", GetCapability<Boolean>(CapabilityType.SupportsFindingByCss));
      Log.Info("Takes screenshots.......{0}", GetCapability<Boolean>(CapabilityType.TakesScreenshot));
      if (GetCapability<Proxy>(CapabilityType.Proxy) != null)
        Log.Info("Browser Proxy...........{0}", GetCapability<Proxy>(CapabilityType.Proxy).HttpProxy);`

and this is where it fails, while fetching the proxy from capabilities: (Im pasting the local variable values from debugger)
-	OpenQA.Selenium.ICapabilities.GetCapability returned	Count = 1	System.Collections.Generic.Dictionary<string, object>
+		[0]	{[proxyType, ]}	System.Collections.Generic.KeyValuePair<string, object>

**Comment by jimevans** [comment]
This is entirely expected. When getting returned capabilities, the language bindings do not deserialize proxy information into a `Proxy` object. It returns a `Dictionary<string, object>`, which you can then use to check for a key of `httpProxy`.

**Comment by liaeb** [comment]
i have a same problem ,i need help

that is my code
`  [OneTimeSetUp]

        public void SetupTest()
        {

            var capabilities = DesiredCapabilities.Chrome();
            ChromeOptions options = new ChromeOptions();
            options.AddArguments("test-type");
            options.BinaryLocation = @"C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\bin\Debug\chro‌​medriver.exe";
            capabilities.SetCapability("chrome.binary", @"C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\bin\Debug\chro‌​medriver.exe");
            capabilities.SetCapability(ChromeOptions.Capability, options);
            System.Environment.SetEnvironmentVariable("webdriver.chrome.‌​driver",
                @"C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\bin\Debug\chro‌​medriver.exe");
            driver = new ChromeDriver(@"C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\bin\Debug");
            capabilities.SetCapability(ChromeOptions.Capability, options.ToString());
            capabilities.SetCapability(capabilities.Platform.ProtocolPlatformType, "WebDriver");
            capabilities.SetCapability(CapabilityType.BrowserName, "chrome");
            capabilities.SetCapability(capabilities.Version, "57");
            capabilities.SetCapability(CapabilityType.Platform, "WinNT");
            capabilities.SetCapability(ChromeOptions.Capability, options);
            if (driver != null)
            {
                driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444/wd/hub"), capabilities,
                    TimeSpan.FromSeconds(200));
            }
            baseURL = "http://192.168.10.173:8080/";
            // driver.Manage().Window.Maximize();
            verificationErrors = new StringBuilder();
        }`

and my stacktrace is 

>    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at FirstPackage.Methods.SetupTest() in C:\Users\ebrahimpour.l\Documents\Visual Studio 2015\Projects\FirstPackage\FirstPackage\Methods.cs:line 83

error message:
Unable to cast object of type 'System.String' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.
