### ISSUE TITLE
Click element didn't take effect after the element did be hovered

### ISSUE THREAD

**Issue by fangting0622** [SeleniumHQ/selenium#1819]
## Meta -
OS: Windows 7
Browser: Google Chrome

## Expected Behavior -
Click element then take action.

## Actual Behavior -
Click element but it didn't take effect. But from the screenshot we can see that the element did be hovered. 

The main code are(target is a By parameter):
WebDriverWait wait = new WebDriverWait(driver, timeout);
element = wait.until(ExpectedConditions.elementToBeClickable(target));
element.click();

## Steps to reproduce -
This happens occasionally which can't be reproduced every time.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could reproduce the problem and act upon it. Without it, there is nothing we can really do about it. Please, re-open the issue if you have a test case.

**Comment by jdmarshall** [comment]
The only critical issues that I'm aware of with WebDriver are intermittent failures due to timing issues like click() failing or navigate().to() not actually changing the location.

Of course we can't give you reproduction steps. They're race conditions.

**Comment by cgoldberg** [comment]
@jdmarshall 

> Of course we can't give you reproduction steps. They're race conditions.

of course you could create a concise test setup to trigger the race condition intermittently.  without that, it is ridiculous to think someone would spend time guessing your test setup.  Without input from you, the behavior is unknown and fixing it is obviously not feasible.
