### ISSUE TITLE
chromedriver can't run.

### ISSUE THREAD

**Issue by lv7777** [SeleniumHQ/selenium#1824]
## Meta -
OS: Windows 10
Selenium Version:2.52
Browser:Google Chrome
Browser Version: 51.0.2679.0 dev-m (64-bit)

## Actual Behavior -
chromedriver was not run.
## Steps to reproduce -

when I ran follow code using eclipse,chromedriver was not run.

and this behavior was also occur using DesiredCapabilities. 

```JAVA
ChromeOptions options = new ChromeOptions();
File ext =new File("bin\\about_travis\\textlint--Proofreader_v1.3.0.crx");
System.out.println(ext.exists());//true
options.addExtensions(ext);
ChromeDriver driver = new ChromeDriver(options);

```

**Comment by lv7777** [comment]
when
```
ChromeOptions options = new ChromeOptions();
//File ext =new File("bin\\about_travis\\textlint--Proofreader_v1.3.0.crx");
//System.out.println(ext.exists());//true
//options.addExtensions(ext);
ChromeDriver driver = new ChromeDriver(options);
```
this code correct run.

**Comment by lv7777** [comment]
When I install follow chrome extension then not running
https://chrome.google.com/webstore/detail/textlint-proofreader/hdongmdneapmhfblomidbafplpanpdmm

but,I download https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?hl=ja

chromedriver running.

**Comment by lukeis** [comment]
for chromedriver issues, please log a bug with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
