### ISSUE TITLE
Selenium 2.53.0 is released, but on official site it still says 2.52.0

### ISSUE THREAD

**Issue by g-tiwari** [SeleniumHQ/selenium#1826]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Expected Behavior -
On the site seleniumhq.org, it should be 2.53.0 against java
## Actual Behavior -
 it is 2.52.0 against java
## Steps to reproduce -

1. go to seleniumhq.org

**Comment by lukeis** [comment]
fixed... in the future please log issues for the website on the website's repo:
https://github.com/SeleniumHQ/www.seleniumhq.org
