### ISSUE TITLE
profilePath_ property is undefined

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#1827]
I use this property because I need to copy some files from a profile to another. It used to work in 2.52.0.

I know it's an internal property and I shouldn't use it, but I'm filing this bug anyway because it's used in a test: https://github.com/SeleniumHQ/selenium/blob/f4a8391eb464d3762eab098fb7cf6aa90347e377/javascript/node/selenium-webdriver/test/firefox/firefox_test.js#L145

**Comment by jleyba** [comment]
I'm not going to expose the profile path because it is an implementation detail. Plus, when the FirefoxDriver is replaced with Mozilla's Marionette, we won't have this information, so best not add a dependency on it now.

**Comment by marco-c** [comment]
Fair enough. I'll try to find another way to implement my test, or drop it (when Marionette will be used instead of FirefoxDriver).
