### ISSUE TITLE
Encoding fails on umlauts in HTMLRunner Test report 

### ISSUE THREAD

**Issue by computerlyrik** [SeleniumHQ/selenium#1833]
## Meta -

OS: Windows 7
Selenium Version: 2.52.0
Browser: Firefox
## Expected Behavior -

Display umlauts ä ö ü correctly
## Actual Behavior -

Some weird encoding error. Pull Request #1832 fixes this in html code
## Steps to reproduce -
- clone testproject at https://github.com/computerlyrik/selenium-spring-boot-example
- run `mvn spring-boot:run` => this should open http://google.com and exit.
- open the resulting `results_htmlrunner_suite.html` in firefox browser

**Comment by swarmshine** [comment]
Fixing HEADER in report is not enough in common scenario.
Could you please check out Pull Request  https://github.com/SeleniumHQ/selenium/pull/1794 
We should fix both report encoding and also HTTP Request parsing with correct encoding.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
