### ISSUE TITLE
web driver is entering characters very slow even with IE driver server 32 bit

### ISSUE THREAD

**Issue by sandhyajakku** [SeleniumHQ/selenium#1845]
Hi,
I am using IE-64 bit and IE driver server as 32 bit.Previously i was using IE-64 bit and driver server also 64 bit.Based some articles i have changed the IE driver server to 32 bit for fast execution.After changing also i did not see any difference.To enter one character it is taking 2-3 seconds time.Any one help me with this issue..

**Comment by jimevans** [comment]
Please provide a log from `IEDriverServer.exe` demonstrating the problem with a complete test case.

**Comment by meenakshidembi** [comment]
I am also facing the same issue with selenium-java-2.53.0, i tried using IE-64 bit and IE-32 bit server. with both I am facing similar issue. Please provide ur comments.
Thanks in advance.

**Comment by marleitao** [comment]
Hi Jim,
Can you help to find the issue.
Attached TRACE and DEBUG logs and a test.

[IE32Error.txt](https://github.com/SeleniumHQ/selenium/files/327609/IE32Error.txt)
[IEDriver_DEBUG.txt](https://github.com/SeleniumHQ/selenium/files/327610/IEDriver_DEBUG.txt)
[IEDriver_TRACE.txt](https://github.com/SeleniumHQ/selenium/files/327611/IEDriver_TRACE.txt)

**Comment by jimevans** [comment]
@marleitao Thank you for the logs. Please repeat the test using a recent version of `IEDriverServer.exe`. You're using 2.46, which is a bit outdated, and later versions have better logging around the areas where this might be an issue.

**Comment by marleitao** [comment]
@jimevans 
Attached logs for same test script with 2.53 (32bit) version.

[IEDriver_DEBUG.txt](https://github.com/SeleniumHQ/selenium/files/334693/IEDriver_DEBUG.txt)
[IEDriver_TRACE.txt](https://github.com/SeleniumHQ/selenium/files/334695/IEDriver_TRACE.txt)

Thanks

**Comment by kiodou** [comment]
I'm having a similar problem, was using 3.0 and 2.53, but they were really slow, now i'm using 2.50 and its a little bit more faster.

[slow_IEDRIVER.log.txt](https://github.com/SeleniumHQ/selenium/files/605009/slow_IEDRIVER.log.txt)

**Comment by Mithun048** [comment]
Even I have this Issue.. But if i run 32 bit IEDriverServer.exe for a 64 bit Windows Machine it works.
But My Question here **how do i npm install selenium-webdriver specifying 32 bit IE Driver File.**

**Comment by diemol** [comment]
Is this issue still valid if the most recent versions are used?
(If so, please provide a way to reproduce the issue, avoiding narratives please)

**Comment by AutomatedTester** [comment]
Closing as no response
