### ISSUE TITLE
IE11 Unable to find element

### ISSUE THREAD

**Issue by SeifBenayed** [SeleniumHQ/selenium#1852]
## Meta -
OS: 
Selenium Version: 
Browser: IE 11.0.28 X64 -->

Hey everybody 

I have a problem with selenium 

I try to run selenium on IE 11 but the problem is I have 2 Pc.
the same coden selenium and I upgrade IE 11.
on the first PC (let's call it PC 1 ) all the block is work but on the second(PC 2 ) not.
the error is that they tell me Unable to find element on closed window or other similar like noSuchWindow Exception on this line for example : " IWebElement element = driver.FindElement(By.XPath("//div[@id='smenu4']/input[@value='Chercher (FIN)']"));" 
but if I run it on PC 1 it work fine. that's make me crazy

Thank you

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
