### ISSUE TITLE
webdriver/phantomjs/service.py  OS-level handle needs to be closed

### ISSUE THREAD

**Issue by palacinka** [SeleniumHQ/selenium#1854]
in webdriver/phantomjs/service.py
on line 45
`self._cookie_temp_file = tempfile.mkstemp()[1]`
^^ OS-level handle is ignored here

OS-level handle to an open file needs to be closed during  driver.quit() or it will throw Exception to Windows users 

`WindowsError: [Error 32] The process cannot access the file because it is being used by another process:`

exception is raised  on line 68 in selenium\webdriver\phantomjs\service.py", line 68, in send_remote_shutdown_command
`os.remove(self._cookie_temp_file)`

**Comment by zyq001** [comment]
The same problem. UP!

**Comment by rfusik** [comment]
Yup, just upgraded selenium and getting it !

**Comment by mahrous78** [comment]
I am facing this issue too on Windows 7, selenium-2.48.0

**Comment by jonatascastro12** [comment]
I got the same problem too! Selenium 2.53.1
