### ISSUE TITLE
What happened to documentation on Grid Node/Hub JSON Settings? 

### ISSUE THREAD

**Issue by testerwest** [SeleniumHQ/selenium#1857]
Since Selenium was ported to Github, it looks like the documentation for all the various different hub & node JSON settings has disappeared.  If I do a search on seleniumhq.org for Json settings many result links still points to the old Google Code site (which of course now redirects to Github).

There is some documentation on seleniumhq.org but not the important details on how the various timeout settings work (which are critical to understanding and operating a healthy grid).  

Is the old documentation archived somewhere and if not can it be restored?   Thanks!

**Comment by titusfortner** [comment]
Is this what you are looking for? https://seleniumhq.github.io/docs/grid.htm
Regardless, this is a question not an issue. If this link does not address your specific concern, please ask on our mailing list.
