### ISSUE TITLE
IEBrowser hangs indefinitely when RequireWindowFocus sets true

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [SeleniumHQ/selenium#1859]
## Meta -

OS:  Windows 7 and Windows 8.1
Selenium Version: 2.49
Browser: <Internet Explorer>
Browser Version: <IE 11>
## Actual Behavior -  When user switches focus from the Selenium launched IE browser, Browser Hanged indefinitely even though user returns back to the browser again. Browser is completely unresponsive. It just hanged.

Snippet from IEDriver Server log file:
T 2016-03-22 13:00:53:844 IECommandExecutor.cpp(569) Entering IECommandExecutor::GetCurrentBrowser
T 2016-03-22 13:00:53:844 IECommandExecutor.cpp(575) Entering IECommandExecutor::GetManagedBrowser
T 2016-03-22 13:00:53:844 InputManager.cpp(59) Entering InputManager::PerformInputSequence
**D 2016-03-22 13:00:53:844 InputManager.cpp(80) Mutex acquired for user interaction.**
T 2016-03-22 13:00:53:844 InputManager.cpp(232) Entering InputManager::SetFocusToBrowser
T 2016-03-22 13:00:53:844 Browser.cpp(175) Entering Browser::GetWindowHandle
T 2016-03-22 13:00:53:844 Browser.cpp(380) Entering Browser::GetTopLevelWindowHandle 
## Steps to reproduce -
1. Create IE Driver instance as follows...
   System.setProperty("webdriver.ie.driver",WorkingEnvironment.getWebdriverIEServerEXEPath());
   DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
   **ieCapabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true);**
   ieCapabilities.setCapability("enablePersistentHover", false);
   ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
   
   ```
   if (ignoreCertificateErrors) {
           ieCapabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
   }
   ```
   
   InternetExplorerDriverService.Builder service = new  InternetExplorerDriverService.Builder();
       service = service.withLogLevel(InternetExplorerDriverLogLevel.TRACE);
       service = service.withLogFile(new File("c:\logs\selenium.log"));  
   webDriver = new InternetExplorerDriver(service.build(), ieCapabilities);

[IEDriverServerLogfile.txt](https://github.com/SeleniumHQ/selenium/files/183682/IEDriverServerLogfile.txt)

**Comment by Prasannajnaeyulu** [comment]
Require window focus must be set to true for my application. Otherwise, some IE Actions are not working for me. Hence, I enabled this capability. I Suspect some deadlock is happening with inputmanager.cpp or Browser.cpp which makes the browser hang forever.

Can someone please help me on this issue. Your quick help is much appreciated.

**Comment by salgadonikka** [comment]
I'm experiencing the same issue. I also need the property RequireWindowFocus set to true, however, IE hangs when I switch focus to other applications. Have you found the solution/workaround for this?

**Comment by barancev** [comment]
Is this issue still actual in latest IE driver versions (3.14+)?

**Comment by barancev** [comment]
Closing the issue, it's related to antique IE driver versions and seems to be not relevant anymore.
