### ISSUE TITLE
HTMLRunner report could not display text properly if encoding of test case different from ISO_8859_1 

### ISSUE THREAD

**Issue by swarmshine** [SeleniumHQ/selenium#1864]
## Meta -

OS: Any
Selenium Version: 2.52.0
Browser: Any
Browser Version: Any
## Expected Behavior -

![report-good](https://cloud.githubusercontent.com/assets/17738390/13958624/d5a072ce-f061-11e5-8679-646df4df5bb7.png)
## Actual Behavior -

![report-bed](https://cloud.githubusercontent.com/assets/17738390/13958264/825f4f82-f060-11e5-8218-4cbaba764666.png)
## Steps to reproduce -

Scenario
`open http://ru.wikipedia.org/wiki/Selenium`
`assertText id=content *инструмент*`

Target page
http://ru.wikipedia.org/wiki/Selenium
![target-page](https://cloud.githubusercontent.com/assets/17738390/13958435/1d1e8254-f061-11e5-875b-e70e510494fc.png)
## Description

If test case contains non ISO_8859_1 characters html report could not display them correctly.

Pull request https://github.com/SeleniumHQ/selenium/pull/1794 fix this issue.

**Comment by swarmshine** [comment]
issue with umlauts https://github.com/SeleniumHQ/selenium/issues/1833 will be fixed by this patch too.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
