### ISSUE TITLE
Scrolling down to the page's bottom

### ISSUE THREAD

**Issue by foxrafi** [SeleniumHQ/selenium#1865]
## Meta 
OS: Windows 8
Selenium Version:  2.21.371459
Browser: Google Chrome
Browser Version: 49.0.2623.87 (64-bit) 

## Expected Behavior 
actions.keyDown(Keys.CONTROL).sendKeys(Keys.END).keyUp(Keys.CONTROL).perform();
should take me to the page's bottom

## Actual Behavior -
Nothing happens.

First I need to click somewhere to get this result, as for instance :
actions.click(numberLabel).keyDown(Keys.CONTROL).sendKeys(Keys.END).keyUp(Keys.CONTROL).perform();

Do you know why it works in this way ?

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
