### ISSUE TITLE
Critical IE (10,11)Issue:Exception: A JavaScript error was encountered executing the findElement atom

### ISSUE THREAD

**Issue by Lannois** [SeleniumHQ/selenium#1868]
## Meta -
OS: <Windows 7>
Selenium Version: <IDE 2.9.1>
Browser: <IE>
Browser Version: <IE 11.0.9600.18230>

## Expected Behavior -
Ability to launch and run IE using webdriver coe.

## Actual Behavior -
Unable to find element with id == userid (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.21 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'
System info: host: 'istx305', ip: '129.97.244.177', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:48140/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 7ee539cf-57cd-4922-88ab-3b444670010c
*** Element info: {Using=id, value=userid}

## Steps to reproduce -

I wanted to add my comments to the previous thread, but it appears to be closed:
https://github.com/seleniumhq/selenium/issues/1590

I also experienced this error when trying to run the IE webdriver. The code worked from Firefox and Chrome, but not for IE. I investigated and tried numerous solutions, including a newer version of the IE Webdriver executable, then eventually found success by following a colleague's suggestion to change the security settings in IE.

In the Internet Options dialog box, I checked on Enable Protected Mode in all categories (Internet, Local internet, Trusted Sites and Restricted Sites). This solved the problem.

Hope this helps!

Regards,
Lannois

**Comment by jimevans** [comment]
Please don't treat the issue tracker as a discussion board. It's not. Properly configuring IE for use with the IE driver (including properly setting Protected Mode) is another way to solve the issue.
