### ISSUE TITLE
Sporadic issues with FF click() 

### ISSUE THREAD

**Issue by sahas-** [SeleniumHQ/selenium#1869]
## Meta -
OS: Win 7 (Saucelabs)
Selenium Version: 2.52.0
Browser: Firefox
Browser Version: 44.0

## Expected Behavior -
element click
## Actual Behavior -
element click isn't working
## Steps to reproduce -
very similar to issues discussed in below tickets. element click works sometime and fails randomly. we run exactly the same tests in chrome as well, no issues with chrome. 
is there any suggestion?

https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/7031
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6112

**Comment by p0deje** [comment]
Please provide [concise reproducible test cases](http://sscce.org/)
so that we could deal with this issue.
