### ISSUE TITLE
driver.quit does not kill IE

### ISSUE THREAD

**Issue by punams** [SeleniumHQ/selenium#1872]
## Meta -
OS:  Windows 7 
Selenium Version: 2.52.0
Browser: IE11
Browser Version: 11.0.9600.18163

## Expected Behavior -
driver.quit should close IE

## Actual Behavior -
All other browsers behave as expected upon using driver.quit except IE

## Steps to reproduce -
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using System.Collections.ObjectModel;

namespace UnitTestProject1
{
    [TestClass]
    public class diffbrowser
    {
        [TestMethod]
        public void TestInFirefox()
        {
            IWebDriver driver = new FirefoxDriver();
            driver.Navigate().GoToUrl("http://google.com");
            System.Threading.Thread.Sleep(1000);
            driver.Quit();
        }
        [TestMethod]
        public void TestInChrome()
        {
            IWebDriver driver = new ChromeDriver("C:\\Users\\myname\\Downloads\\chromedriver_win32");
            driver.Navigate().GoToUrl("http://google.com");
            System.Threading.Thread.Sleep(1000);
            driver.Quit();
        }
        [TestMethod]
        public void TestinIE()
        {
            IWebDriver driver = new InternetExplorerDriver("C:\\Users\\myname\\Downloads\\IEDriverServer_x64_2.53.0");
            driver.Navigate().GoToUrl("http:/google.com");
            System.Threading.Thread.Sleep(10000);
            driver.Quit();
                   }
    }
}

**Comment by jimevans** [comment]
Please provide a log file from `IEDriverServer.exe` at the `TRACE` level. This is not a universal issue, as there are a [number of tests](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/test/common/DriverDisposalTest.cs) in the .NET bindings' test suite that exercise exactly this functionality, and do not exhibit this behavior.

**Comment by lukeis** [comment]
closing due to no reply
