### ISSUE TITLE
Viewport unexpectedly scroll up to the top of web page after getScreenshotAs() execution

### ISSUE THREAD

**Issue by MSauchanka** [SeleniumHQ/selenium#1874]
## Meta -
OS: Windows 7 x64
Selenium Version: 2.52.0 (2.53.0) (x32 ie driver 2.48 and upper)
Browser: IE
Browser Version: 11

## Expected Behavior -
Viewport should not change position after getScreenshotAs() and method should returns screenshot of bottom part of web page

## Actual Behavior -
Viewport unexpectedly scroll up to the top of web page and getScreenshotAs() returns top part of web page

## Steps to reproduce -
1. Create IE driver instance
2. Navigate to any web page with scroll bar
3. Scroll down page to bottom part
4. Take screenshot using ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE)

**Comment by jimevans** [comment]
Given that the IE driver attempts to take screenshots of the full page, and must resize the window to do so, this is entirely expected behavior. The alternative is to set the `ie.enableFullPageScreenshot` capability to `false`, which will capture only the current view port.

**Comment by MSauchanka** [comment]
Thanks for your answer. getScreenshotAs() do not provide full page screenshot on IE11 if If ie.enableFullPageScreenshot=true. Driver trying to maximize window and return screenshot of view port only. If ie.enableFullPageScreenshot=false web page do not scroll up to the top.
