### ISSUE TITLE
Firefox 45 disbale firefox webdriver?

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#1875]
OS: OSX Capitan
Selenium Version: 2.48.0
Browser: Firefox
Browser Version: 45.0.1

I updated to Firefox 45.0.1 few days ago, and selenium webdriver doesn't work anymore. I got these messages when created new FirefoxDriver() 

> 1458829658940	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1458829658941	DeferredSave.extensions.json	DEBUG	Save changes
1458829658941	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1458829658941	addons.xpi-utils	DEBUG	Updating add-on states
1458829658947	addons.xpi-utils	DEBUG	Writing add-ons list
1458829658948	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1458829658949	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 0.1
1458829658964	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1458829658964	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1458829658964	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1458829658978	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1458829658978	addons.manager	DEBUG	Provider finished startup: XPIProvider
1458829658978	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1458829658978	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1458829658978	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1458829658979	addons.manager	DEBUG	Starting provider: GMPProvider
1458829658985	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1458829658986	addons.manager	DEBUG	Provider finished startup: GMPProvider
1458829658986	addons.manager	DEBUG	Starting provider: PluginProvider
1458829658986	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1458829658986	addons.manager	DEBUG	Provider finished startup: PluginProvider
1458829658986	addons.manager	DEBUG	Completed startup sequence
1458829659395	DeferredSave.extensions.json	DEBUG	Starting write
1458829659563	addons.repository	DEBUG	No addons.json found.
1458829659564	DeferredSave.addons.json	DEBUG	Save changes
1458829659566	DeferredSave.addons.json	DEBUG	Starting timer
1458829659700	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1458829659700	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1458829659701	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1458829659704	DeferredSave.extensions.json	DEBUG	Write succeeded
1458829659704	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1458829659705	DeferredSave.addons.json	DEBUG	Starting write
1458829659733	DeferredSave.addons.json	DEBUG	Write succeeded

When I try new version of Selenium 2.52.0, it works agains, but since then, some elements with ID don't work anymore, like with 2.48.0.

**Comment by lukeis** [comment]
if you want to run with Firefox 45, you'll need to use newer versions of selenium (2.52 or 2.53).  If you want to continue using 2.48, then you'll need to downgrade your version of firefox.

The "some elements with ID don't work anymore" sounds like an issue to log... as long as you provide a reproducible test case for us to look into.

Otherwise, there's no way for us to "fix" the old version of selenium.
