### ISSUE TITLE
file upload not stable in Internet Explorer 11

### ISSUE THREAD

**Issue by xlenz** [SeleniumHQ/selenium#1877]
## Meta -
OS: win2008
Selenium Version: 2.53
Browser: ie 2.53.0 32bit
Browser Version: ie11

## Expected Behavior -
proper work with input type="file"

## Actual Behavior -
ie hanging with file choose menu opened

## Steps to reproduce -
fill multiple inputs with type="file"

driver capabilities:
        capabilities.setCapability("ie.ensureCleanSession", true);
        capabilities.setCapability("enablePersistentHover", false);
        capabilities.setCapability("requireWindowFocus", true);
        capabilities.setCapability("unexpectedAlertBehaviour", "accept");

similar issue, closed with no explanation: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3858

**Comment by jimevans** [comment]
Please retry setting the `ie.fileUploadDialogTimeout` capability to a larger value. Note that it defaults to 3000 milliseconds. If that still does not resolve the issue, please provide a log file from `IEDriverServer.exe`, with the log level set to at least `DEBUG`, and more properly, `TRACE`.

**Comment by xlenz** [comment]
capabilities.setCapability("ie.fileUploadDialogTimeout", 90000);
resolved my issue!
Thank you @jimevans so much!!
