### ISSUE TITLE
Application home page is cropped in screenshot

### ISSUE THREAD

**Issue by abhinavm88** [SeleniumHQ/selenium#1878]
OS: Windows 7
Selenium Version: WebDriver 2.50.1
Browser: IE11
Browser Version: 11.0.9600.18204
## Expected Behaviour -

Page should load completely and selenium webdriver should be able to input the patient name to be searched and should be able click the search button.
## Actual Behaviour -

Page is not loaded completely. Search button is cropped so clicking the search button is failed.
## Steps to reproduce -
1. Launch the application
2. Input the user name and password and click on Login button
3. Input the patient to be searched and click on the search button
   ![capture](https://cloud.githubusercontent.com/assets/17078099/14039063/07fcd76c-f27e-11e5-9b3c-03b5cc007a59.JPG)

**Comment by barancev** [comment]
Is this issue is still actual in version 3.13?

**Comment by barancev** [comment]
Closing the issue as the version 2.50 is out of date.
