### ISSUE TITLE
Jenkins plugin

### ISSUE THREAD

**Issue by thibaut-sticky** [SeleniumHQ/selenium#1879]
Hi,

Sorry to post this here, but I don't know where exactly to post this.
So, like a lot of people here, I use Jenkins to launch my tests. Today, I launch manually my hub and my nodes (host on openstack). Which is painful.
I have two questions:
* How do you manage your grid?
* Why the [jenkins plugin](https://github.com/jenkinsci/selenium-plugin) is not handle by the Selenium team itself? This one is not anymore maintained but it could be really useful if used with a jenkins slave.

**Comment by lukeis** [comment]
Questions like this are better suited for the mailing list:
https://groups.google.com/forum/m/#!forum/selenium-users

As to why we don't maintain it? We try not to maintain most extensions / integrations with third party components in this repo. And all of these projects are open source / volunteer basis I think that it's just that none of us use that plugin.

**Comment by thibaut-sticky** [comment]
I will bookmark your link. Thx. I understood your pov.
