### ISSUE TITLE
Missing Package org.openqa.selenium.htmlunit in selenium-server-standalone-2.53.0

### ISSUE THREAD

**Issue by tanugandhi10** [SeleniumHQ/selenium#1882]
OS: <Windows 10>
Selenium Version: <2.53.0>
Browser: < Firefox >
Browser Version: <45.0.1>

## Steps to reproduce -
I tried to use HtmlUnitDriver class but it seems Package org.openqa.selenium.htmlunit is missing in Selenium 2.53.0 jar
Although Package org.openqa.selenium.htmlunit is present in selenium-server-standalone-2.52.0

**Comment by mstankovic86** [comment]
You should add htmlunit driver separate. If you are using maven, add dependency

<groupId>org.seleniumhq.selenium</groupId>
<artifactId>htmlunit-driver</artifactId>
<version>2.20</version>

**Comment by ddavison** [comment]
the HTMLUnit Driver is no longer bundled with the standalone jar file.

as @mstankovic86 had mentioned, you need to add the dependency manually.

see: https://github.com/SeleniumHQ/htmlunit-driver

**Comment by tanugandhi10** [comment]
Thank you guys for the solution.

**Comment by jbellCR** [comment]
WHat if I want to run them as a windows service using NSSM how do I load them?

**Comment by DanielGGordon** [comment]
Omg so that's why...

Anyone know what the import statement would look like for an sbt project?
