### ISSUE TITLE
Selenium webdriver  analyse table bug  with By.xpath

### ISSUE THREAD

**Issue by javadevelopuser** [SeleniumHQ/selenium#1888]
## Meta -
OS: Windows 10
Selenium Version: selenium-java-2.52.0
Browser:  Firefox 
Browser Version: 45.0.1

## Expected Behavior -

程序代码       
407：log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th[1]")).get(0).getText());
408：log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th[1]")).get(1).getText());
409：log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th[1]")).get(2).getText());
410：        List<WebElement> tbs = mainWindow.findElements(By.xpath("//table[@class='detailsList']"));
411：        log.info("股东信息 tbs length=" + tbs.size());
412：        for (WebElement tb : tbs) {
413：           String th_text = tb.findElements(By.xpath("//tbody/tr[1]/th[1]")).get(0).getText();
414：            log.info("股东信息 th_text=" + th_text);

输出：
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:407) - - 基本信息
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:408) - - 股东信息
股东的出资信息截止2014年2月28日。2014年2月28日之后工商只公示股东姓名，其他出资信息由企业自行公示。
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:409) - - 变更信息
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:411) - - 股东信息 tbs length=3
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:414) - - 股东信息 th_text=基本信息
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:414) - - 股东信息 th_text=基本信息
2016-03-28 21:51:58 INFO  ZhejiangCompanyInfoForFireFox  (ZhejiangCompanyInfoForFireFox.java:414) - - 股东信息 th_text=基本信息

--------------------------------------------------------------------------------------------
前面三行代码能够解析出对应的标题文字，在批处理循环中就是只能显示同样的内容，解析网址如下：
http://gsxt.zjaic.gov.cn/zhejiang.jsp#
输入：浙江浙能电力股份有限公司
搜索后看“登记信息”TAB页。

**Comment by ddavison** [comment]
There's not enough information here to determine what the issue is.

This issue however, looks more like a user-error, and should be brought up in the [selenium-users group](groups.google.com/forum/#!forum/selenium-users)

thanks!

**Comment by javadevelopuser** [comment]
demo.htm : 
-----------------------------------------------------------------------------------------------------------
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>啊啊</title>

<body>
<table id="baseinfo" class="detailsList">
<tbody>
<tr><th>test 1</th></tr>
<tr>
	<th>11</th>
	<td>22</td>
</tr>
</tbody>
</table>
 <table id="baseinfo" class="detailsList">
 <tbody>
<tr><th>test 2</th></tr>
<tr>
	<th>aa</th>
	<td>bb</td>
</tr>
</tbody>
</table>
<table id="baseinfo" class="detailsList">
<tbody>
<tr><th>test 3</th></tr>
<tr>
	<th>aa</th>
	<td>bb</td>
</tr>
</tbody>
</table>
</body>
</html>
-----------------------------------------------------------------------------------------------------------

java code :
-----------------------------------------------------------------------------------------------------------
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.io.IOException;
import java.util.List;

public class DemoForFireFox {
    private static Log log = LogFactory.getLog(DemoForFireFox.class);

    public static void main(String[] args) throws IOException {
        // 如果你的 FireFox 没有安装在默认目录，那么必须在程序中设置
        System.setProperty("webdriver.firefox.bin", "D:\\Program Files\\Mozilla Firefox\\firefox.exe");
        // 创建一个 FireFox 的浏览器实例
        WebDriver mainWindow = new FirefoxDriver();
        // 让浏览器访问
        mainWindow.get("file:///F:/demo.html");
        //get three tables first tr/th value by xpath from demo.html, it's ok
        log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th")).get(0).getText());
        log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th")).get(1).getText());
        log.info(mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody/tr[1]/th")).get(2).getText());

        //
        List<WebElement> tbs = mainWindow.findElements(By.xpath("//table[@class='detailsList']/tbody"));
        log.info("tbs length = " + tbs.size());
        for (WebElement tb : tbs) {
            String th_text = tb.findElements(By.xpath("//tr[1]/th")).get(0).getText();
            log.info("th_text=" + th_text);
            //判断
            if (th_text.contains("test 3")) {
                //do something
            }
        }

        //关闭浏览器
        mainWindow.quit();
    }
}
-----------------------------------------------------------------------------------------------------------
do and out information:
-----------------------------------------------------------------------------------------------------------
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:26) - - test 1
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:27) - - test 2
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:28) - - test 3
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:32) - - tbs length = 3
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:35) - - th_text=test 1
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:35) - - th_text=test 1
2016-03-30 16:23:37 INFO  DemoForFireFox  (DemoForFireFox.java:35) - - th_text=test 1
-----------------------------------------------------------------------------------------------------------
Could not get the results I wanted.
Can you help me?

**Comment by ddavison** [comment]
if you looked at my message @javadevelopuser , i had mentioned that this type of question can be answered in the [selenium-users group](https://github.com/SeleniumHQ/selenium/issues/groups.google.com/forum/#!forum/selenium-users) .  they should be able to help you!

:+1:
