### ISSUE TITLE
Mocha tests hang when a failed test is encountered using --reporter doc

### ISSUE THREAD

**Issue by christopherliu** [SeleniumHQ/selenium#1896]
## Meta -
OS: Windows 7 64-bit
Selenium Version: 2.53.0
Browser: Chrome
Browser Version: 49.0.2623.110 m

## Expected Behavior -
I'm using a batch file that executes a Mocha test with the following command:
`start "Mocha tests" mocha .\test\WebDriverJS.js --reporter doc --timeout 10000 1^>^> testing-results.html`

**If I do not use the `--reporter doc` flag**:
When I run a passing test, the Chrome window closes and the command line environment running Mocha finishes.
When I run an intentionally erroneous test (line 46 is off by one character), the Chrome window opened will close, and the command line environment invoked to run Mocha finishes, reporting a failed test error ("Wait timed out").

## Actual Behavior -

**If I do use the `--reporter doc` flag**:
When I run a passing test, the Chrome window closes and the command line environment running Mocha finishes. The doc reporter produces a complete HTML snippet.
When I run an intentionally erroneous test, the Chrome window opened will **remain open**, and the command line environment invoked to run Mocha **hangs** until I manually close it. The doc reporter never finishes producing HTML (tags are unclosed, etc.).

## Steps to reproduce -
Attached is the [text of WebDriverJS.js](https://github.com/SeleniumHQ/selenium/files/195931/WebDriverJs.txt) file used in this test. You'll need to include selenium-server-standalone-2.53.0.jar as well as the latest [chromedriver](http://chromedriver.storage.googleapis.com/2.21/chromedriver_win32.zip)  (though I had the exact same problems with PhantomJS tests).

**Comment by jleyba** [comment]
This is a bug in mocha. Should be fixed by mochajs/mocha#2307
