### ISSUE TITLE
JavaScript webdriver does not support HTTPS

### ISSUE THREAD

**Issue by gregjhogan** [SeleniumHQ/selenium#1897]
I want to run a selenium grid in the cloud and use the javascript web driver (more specifically [protractor](https://angular.github.io/protractor/)) to execute tests against the grid.  To protect usernames and passwords I put a reverse proxy in front of the grid hub which does SSL offloading.  I found, however, that this does not work because a HTTP CONNECT is never issued.  It looks like the [webdriver only uses the nodejs http library](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/http/index.js#L25)?  It should look at the URL and use the https library when needed.

**Comment by gregjhogan** [comment]
@jleyba thanks for fixing this!  I need this to work through a proxy (via`usingWebDriverProxy`).  I think there would be additional changes to get this working?  HTTPS through a proxy in nodejs is kind of a pain ...
http://blog.vanamco.com/proxy-requests-in-node-js/
http://codingmiles.com/node-js-making-https-request-via-proxy/

Thanks!

**Comment by jleyba** [comment]
Sorry, I've never had to setup a ssl proxy in node

**Comment by gregjhogan** [comment]
Should I open a new issue for `usingWebDriverProxy` support since this issue was closed?  Thanks!

**Comment by jleyba** [comment]
New issue for what? `usingWebDriverProxy()` goes through the HttpClient class fixed in my previous commit, so it should be covered.

Actually setting up the https proxy is outside the scope of this project. Have you tried asking if anyone has done this on selenium-users@googlegroups.com?

**Comment by gregjhogan** [comment]
Previously (before your change) HTTPS through a proxy wasn't even a possibility.  Now that you have added support for HTTPS, additional changes are needed to make it work through a proxy (specified by calling `usingWebDriverProxy()`).  Simply changing the host and port for the request to be the proxy host and port does not work for HTTPS.

A common solution is to leverage this `http.Agent` implemenation, but I am not sure if you want to take on a dependency like this:
https://www.npmjs.com/package/https-proxy-agent

Read this article for more info:
http://blog.vanamco.com/proxy-requests-in-node-js/

Currently your code does not go through the steps necessary to first establish the TLS session through the proxy to the destination (the hub), and then send the original request through the tunnel.  Here is an example using the above agent:
```javascript
var https = require('https');
var HttpsProxyAgent = require('https-proxy-agent');

var proxy = 'http://localhost:8888' // fiddler
var opts = {
  hostname: 'www.google.com',
  port: 443,
  path: '/',
  method: 'GET',
  agent: new HttpsProxyAgent(proxy)
}

https.request(opts, function (res) {
  res.pipe(process.stdout);
});
```
