### ISSUE TITLE
selenium IDE not recording anything

### ISSUE THREAD

**Issue by mksakeesh** [SeleniumHQ/selenium#1898]
## Meta -

OS: windows 10
Selenium Version: selenium IDE 2.9.1
Browser: Firefox 
Browser Version: 45.0.1
## Steps to reproduce -

try to record website above

**Comment by lalith2378** [comment]
Hi,

Me too facing same issue, Selenium IDE is not recording anything. Did u find solution for it? If yes, please post it.

Currently, I'm using FF55 version.

Also when I use webdriver , it is not interacting with the browser.


Thanks

**Comment by p0deje** [comment]
@lalith2378 This is probably #4406.

In regards to the original issue, can you provide more details?

**Comment by k15roberts** [comment]
I am having the same issue and I have refreshed my Firefox and not sure what to do now

**Comment by saradhit** [comment]
Hi,
#4406 and this #1898 are not yet assigned to anyone. Any idea about an ETA of these!!!

**Comment by saradhit** [comment]
Hello,
In case if someone got stuck with it...here is the temporary solution that worked for me and should work for all. 
"Uninstall latest version of Firefox browser (v55) and install older version". I installed v45 and is working fine for me.
Make sure you uncheck "Automatic Install updates" of the browser under "Advanced->Update" Settings. Otherwise it will again update the browser to the most recent version.

**Comment by aczn** [comment]
I did the same (reverted to the earlier FF version (54.0b9 in my case) and it's working again

**Comment by xiangyucao** [comment]
Please help! I am using FF 55 and it stop working!!! Everywhere!!! Where can I get old version of FF safely?

**Comment by k15roberts** [comment]
I went to FF 54 and it finally worked for me

**Comment by aczn** [comment]
https://ftp.mozilla.org/pub/firefox/releases/54.0b9/win64/en-US/

**Comment by xiangyucao** [comment]
Thanks. I need to use selenium. Just disable auto upgrade and use 54 for now. Hope this get fixed soon.

**Comment by hiroshitoda** [comment]
I recommend to use Selenium IDE with Firefox ESR 52, based Firefox 52 and supported until June 2018.
https://www.mozilla.org/en-US/firefox/organizations/all/
Firefox 54 has some critical vulnerability.
https://www.mozilla.org/en-US/security/advisories/mfsa2017-18/

**Comment by xiangyucao** [comment]
When will this be fixed?

**Comment by barancev** [comment]
Closing the issue as the original report provides no details to act on.
Regarding FF55 please watch #4406
