### ISSUE TITLE
After update of Webdriver 2.53.0 and Firefox 45.0.1, firefox taking long time to launch on remote machine

### ISSUE THREAD

**Issue by svaze** [SeleniumHQ/selenium#1900]
## Meta -

OS:  Any
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version:  64
## Expected Behavior -

Firefox should launch quickly as earlier before update to Firefox 45.0.1 and Webdriver 2.53.0
## Actual Behavior -

Firefox takes long time to launch on remote machine and sometimes timesout after default 60 sec
## Steps to reproduce -

Try to launch firefox on remote machine using remoteWebdriver, firefox fails to launch within 60 sec

**Comment by randersen** [comment]
Not sure if it's related, but since updating to 2.53 and 45.01 running four FF browsers on a xlarge ec2 Instance takes up 95-99% of the cpu, i used to run 6 FF instances with no cpu issues.

**Comment by barancev** [comment]
Closing the issue, there is no information to act on.
