### ISSUE TITLE
Incomplete documentation for Webdriver Js after GitHub migration

### ISSUE THREAD

**Issue by cgadam** [SeleniumHQ/selenium#1903]
Webdriver JS former documentation is incomplete. Or at least, very hard to find :S

A very extensive and educational wiki used to be placed here:
https://code.google.com/p/selenium/wiki/WebDriverJs

Now, I'm being redirected to this new project as the previous one seems to be archived.

Among other things, that documentation used to have a very nice explanation on how "Webdriver JS" queues actions using the "Control Flow".

This is a very interesting concept to be developed as it's the way webdriver js deals with actual async operations that occur underneath.

Can someone please include that documentation again somewhere so that those valuable explanations are not lost?

Thanks!!

**Comment by jleyba** [comment]
From the [wiki](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs) (emphasis added):

> WebDriver's JavaScript API is entirely asynchronous and every command results in a promise. Promise-heavy APIs will be a lot easier to work with once Node supports [ES2017's async functions](http://www.2ality.com/2016/02/async-functions.html), but in the meantime, WebDriverJS uses a custom promise library with a promise manager called the ControlFlow. The ControlFlow implicitly synchronizes asynchronous actions, making it so you only have to register a promise callback when you want to catch an error or access a return value. **Detailed information on the ControlFlow and WebDriverJS's [promise library](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html) is included with the API docs.**
