### ISSUE TITLE
Add feature: with webdriver.Firefox as browser

### ISSUE THREAD

**Issue by lcd1232** [SeleniumHQ/selenium#1906]
OS: any
Selenium Version: 2.52.0
Browser: any

Add feature that this code will work:
```
with webdriver.Firefox() as browser:
	browser.get('http://www.google.com')
	browser.save_screenshot('screenie.png')
```

**Comment by p0deje** [comment]
Well, that's not really a feature requests, it doesn't say why you want this and how is it different from current approach. Can't you just use usual variables or wrap it by yourself?

**Comment by lukeis** [comment]
I think they are just asking us to implement the __enter__ and __exit__ methods in python

**Comment by lukeis** [comment]
in the most common cases of using the selenium library while running tests... one normally uses a test framework and would handle the creation and destruction of the driver object(s) in before / after methods... why this isn't normally asked for.

**Comment by AutomatedTester** [comment]
No answer in a long time, closing.
