### ISSUE TITLE
Invalid proxy type error with IEServerDriver version 2.52.1 and above

### ISSUE THREAD

**Issue by rclawson** [SeleniumHQ/selenium#1909]
## Meta -
OS: Windows 7 
Selenium Version: 2.52.1
Browser: Internet Explorer 11 
Browser Version: 11.0.9600.18230 
Setup: Cucumber 2.3.3, Ruby 2.1.5p273, Capybara 2.6.2

## Expected Behavior -
I have reduced my project to a simple cucumber test with only 1 test which brings up the Google home page.  Using IEServerDriver.exe version 2.52.0 and before the test passes fine.  Starting with version 2.52.1, the test fails.

## Actual Behavior -
The test fails with the following output.
  ```
Scenario: Run a simple test              # features/sample.feature:9
    Given that I'm on the Google home page # features/step_definitions/sample_steps.rb:1
      invalid proxy type: :"", expected one of [:direct, :manual, :pac, :auto_detect, :system] (ArgumentError)
      ./features/step_definitions/sample_steps.rb:2:in `/^that I'm on the Google home page$/'
      features/sample.feature:10:in `Given that I'm on the Google home page'

Failing Scenarios:
cucumber features/sample.feature:9 # Scenario: Run a simple test

1 scenario (1 failed)
1 step (1 failed)
0m1.560s

```
## Steps to reproduce -
I've included a small zip file that contains the test.  Using bundler, you would just need to run "bundle exec cucumber" in the root of the project.
[IEServerDriverError.zip](https://github.com/SeleniumHQ/selenium/files/200035/IEServerDriverError.zip)

**Comment by titusfortner** [comment]
This is a known issue between the Ruby bindings and IEDriver 2.52.1+ and is in the process of being fixed. Thanks for reporting it to us.

**Comment by rclawson** [comment]
Awesome!  I didn't see an open issue for it, so I went ahead and created one.

**Comment by jimevans** [comment]
Fixed in 19c0c17, released in 2.53.1 of `IEDriverServer.exe`

**Comment by 552366** [comment]
Hi, I am facing the same issue with following combination:
Ruby: 2.0
IE 10
Cucumber 2.3.3
And downloaded latest Selenium gem and ie driver 2.53

**Comment by nirvdrum** [comment]
@552366 Have you tried IE Driver 2.53.1? That's the version reportedly with the fix.

**Comment by 552366** [comment]
The url: "http://www.seleniumhq.org/download/", does not have the 2.53.1 version to download.

Can you please refer me to the alternate download link.

**Comment by lukeis** [comment]
@552366 http://selenium-release.storage.googleapis.com/index.html?path=2.53/

**Comment by 552366** [comment]
Thanks so much...this worked.

**Comment by lukeis** [comment]
http://www.seleniumhq.org/download/ has been updated now.
