### ISSUE TITLE
ReadMe for Python is incorrect

### ISSUE THREAD

**Issue by uchuugaka** [SeleniumHQ/selenium#1910]
## Meta -

OS: 
Selenium Version: 
Browser: 
Browser Version: 

The ReadMe for for Python is misleading as it does not call out that the Java server is still required for Safari, as it simply wraps the RemoteWebDriver class.

**Comment by cgoldberg** [comment]
@uchuugaka 

> The ReadMe for for Python is misleading as it does not call 
> out that the Java server is still required for Safari, as it simply 
> wraps the RemoteWebDriver class.

the SafariDriver wiki page doesn't mention this either: https://github.com/SeleniumHQ/selenium/wiki/SafariDriver

However, you might find it more disconcerting that the documentation for the Python SafariDriver is not included in the API docs at all.  That is a more serious issue that should probably be attended to. 

@uchuugaka,
As to making the README.rst less misleading, pull requests are free :)

**Comment by uchuugaka** [comment]
> 
> As to making the README.rst less misleading, pull requests are free :)

Fair enough. 
I'll take a stab at it. 
I used the WayBack Machine to collect the old docs on the SafariDriver implementation as the old Google code repo redirects. 

I will take a stab at reconstituting it.

**Comment by lukeis** [comment]
It's just missing the auto doc generation folder/files in here:

https://github.com/SeleniumHQ/selenium/tree/master/py/docs/source

I think the doc is pretty clear about needing the standalone server:
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/safari/webdriver.py#L38-L48

but additional wording wouldn't be refused if you felt it added more clarity or you needed that information in another place

**Comment by lmtierney** [comment]
Safari API docs were added with 4b3bfa7615d31a5b978f884918055111952fb7e3
