### ISSUE TITLE
Some new browser logs are not captured

### ISSUE THREAD

**Issue by juliemr** [SeleniumHQ/selenium#1914]
## Meta -

OS: OSX 10.11.3
Selenium Version: v2.52.0
Browser: Chrome
Browser Version: 49.0.2623.87
## Behavior

I have a sample site which logs an error to the browser console using `console.error('foo')` once on load and once two seconds later.

``` js
console.error('first');
setTimeout(function() {
  console.error('second');
}, 2000);
```

I run webdriver against it and capture browser logs once right away and once ten seconds later. I expect the second error to show up in the second captured logs, but instead it is empty:

``` js
driver.manage().logs().get('browser').then(function(logs) {
  console.log('------ first logs:');
  console.log(logs); // This has the first error, as expected.
});

driver.sleep(10000);

driver.manage().logs().get('browser').then(function(logs) {
  // The page logs a second error in the past 10 seconds, but these are emtpy.
    console.log('------ second logs:');
    console.log(logs); // This is empty - the second error is lost.
});
```
## Steps to reproduce -

Script showing the issue at: https://github.com/juliemr/webdriver-bugs/blob/master/no-new-logs.js
The site it's testing against is: https://github.com/juliemr/webdriver-bugs/blob/gh-pages/index.html

**Comment by amrsh** [comment]
+1: after each test we check for errors in the log; we get an empty log if the test itself calls browser.manage().logs().get('browser'), thus missing errors.

**Comment by MihailStopnik** [comment]
+1, got the same issue when trying to clear logs with ' browser.manage().logs().get('browser');'
Next attempts to get logs fails

**Comment by ElPsyCongro** [comment]
+1

**Comment by barancev** [comment]
There is nothing here we can fix on Selenium side, the issue should be reported to browser vendors (that implement driver executables)
