### ISSUE TITLE
Permission to include Selenium type stubs in python/typeshed

### ISSUE THREAD

**Issue by wittekm** [SeleniumHQ/selenium#1917]
As of [PEP 0484](https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo), the Python community is building a statically-typed annotation layer for Python 2 and 3. 

For third-party libraries (like Selenium), we can include type hints in stub files that collect class/method type annotations. These stubfiles are collected in a GitHub repository [python/typeshed](https://github.com/python/typeshed). However, according to the PEP, we need the third party library's permission to do so. 

So, Selenium team - would it be okay if we included typehint stubs for your library? This would require no code changes to your own repository.

**Comment by lukeis** [comment]
@AutomatedTester @andreastt @davehunt @Dude-X comments? concerns?

**Comment by andreastt** [comment]
@wittekm @lukeis None whatsoever from me.

**Comment by Dude-X** [comment]
@lukeis @wittekm I am in favor of this. SInce it's a a 'sidecar' file, it doesn't affect anything. We should probably review it though, it seems execute_script is not marked as returning any type though.

**Comment by wittekm** [comment]
If you'd like to review it, please feel free. One of the nice things about MyPy and TypeShed is that you can incrementally add more types over time, so I only annotated some of the quick-n-easy targets.

**Comment by andreastt** [comment]
@Dude-X It should be marked as returning all JSON serialisable types, that is arbitrary objects of numbers, strings, booleans, arrays, sequences, and null.

**Comment by lukeis** [comment]
seems like we're missing a lot of return types for webdriver.pyi that webelement.pyi has (looking at the find_element* methods) and there's plenty more that don't. I'd be happy to put the proper comments in place in the selenium library to make it more well defined.

So, in general @wittekm i think we're :+1: 

I'll close, but feel free to continue the conversation if need be :)  (also we're often on IRC #selenium in freenode)

**Comment by wittekm** [comment]
Thanks for the quick turnaround guys! 

And yeah, I can recycle some of the find_element* stuff in webdriver. I'll see if I can do some type hackery so I don't repeat myself :)

Thanks!
