### ISSUE TITLE
Add support for Edge in JavaScript language bindings

### ISSUE THREAD

**Issue by InstyleVII** [SeleniumHQ/selenium#1919]
I was looking to contribute and add support for Edge to the JavaScript language bindings (hoping to get to others later). Somewhat overwhelmed by the JavaScript directory alone and was wondering if anyone could give me 15 minutes just to overview/get ramped up. Was also wondering if there is a chat platform people normally are on for questions and the like.

It looks like the JDK is needed if I'm actually building any of the servers (didn't realize chrome/ie/firefox drivers were built from here, pretty cool!) but is it required for the language bindings? Also if I do need to do a build should I be using Crazy-Fun or Buck? Looks like Buck support is spread out and ongoing. Lastly working on Windows and while I could test the new Linux subsystem would it just be best to use Cygwin for most of the sample commands (as ./go isn't recognized in cmd and I've no idea what syntax that is from).

**Comment by InstyleVII** [comment]
Should note that I've started to parse the documentation but there is a lot of it and trying to figure out what I need for my specific task isn't apparent in any of it (so far). Will keep reading. Just hoping someone has some time to help me get spun up.

**Comment by lukeis** [comment]
@InstyleVII we're on IRC (freenode.net #selenium) or also on slack (signup url): http://seleniumhq.herokuapp.com/

But also... Edge bindings exist for the node package :)

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/edge.js
