### ISSUE TITLE
[java] SessionNotFoundException deprecated?

### ISSUE THREAD

**Issue by SirLenz0rlot** [SeleniumHQ/selenium#1920]
## Meta -
OS: Ubuntu 14.04
Selenium Version: 2.53 java API
Browser: Any
Browser Version: Any

## Expected Behavior -
My compiler not to raise warnings or a clear explanation why `SessionNotFoundException` is deprecated
## Actual Behavior -
Found `SessionNotFoundException` deprecated without a documentation

## Steps to reproduce -
`import org.openqa.selenium.remote.SessionNotFoundException;`
And notice the deprecation warning

**Comment by barancev** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/SessionNotFoundException.java#L24

**Comment by SirLenz0rlot** [comment]
Sorry, should have looked there!
Thanks for the link,
@barancev shouldn't this be up-to-date?
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/SessionNotFoundException.html
