### ISSUE TITLE
Browser wont close while running multiple testcases on multiple browser parallely

### ISSUE THREAD

**Issue by poojagadekar89** [SeleniumHQ/selenium#1921]
## Meta -
OS: Windows
Selenium Version: latest
Browser: chrome n firefox
Browser Version: 64bit

## Steps to reproduce -

1.Followed keyword driver framwork
2.hub, 1 node - chrome , 2 -node -firefox initialized using selenium grid concept
3.Running 2 testcases on chrome and firefox browser
4.
->result folder statement
1st  testcase - firefox 

->result folder statement
1st  testcase - chrome 

->execution of 1st testcase complets and close chrome browser

->execution of 1st testcase  still processing on firefox

->result folder statement
Start 2nd testcase on chrome

->Wont display result folder statement

->Start 2nd testcase on firefox(1st testcase process goes to idle state and start processing 2nd testcase)

->Complete 2nd testcase on chrome(close the browser)

->Complete 2nd testcase on firefox(close the browser)

->result folder statment
Start  2nd testcase on firefox(as new browser)

->complete process and close firefox browser(2nd testcase)

finally----
1st testcase (which is idle on firefox browser) still available, it wont close

Any solution we have ?
Any gird problem ?

**Comment by cgoldberg** [comment]
your steps to reproduce are totally confusing (nearly nonsensical)..  Can you just state in a few sentences what is actually happening?  

also, how are you attempting to close the browser?  are you calling the `quit()` method?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by poojagadekar89** [comment]
hi cgoldberg,

I am using driver.quit() only.

Main problem is while running 2 testcases on chrome and firefox browser ,

After starting 1st testcase on browsers ,once completed 1st testcase in any one browser start with 2nd testcase on both browsers mean time one browser(chrome) completed 1st testcase execution and other  browser (firefox) execution will be idle

once completed 2nd testcase on both browser , start new session for 2nd testcase in one browser(firefox)).

finally one browser(firefox) which is idle wont close the browser.

This is the issue .If you require still more information let me know.

**Comment by poojagadekar89** [comment]
Hi lukeis,

Sure next time onwards i will post in question section .
