### ISSUE TITLE
Firefox:: ScreenShot : shows overlapped ui [ for single page application]

### ISSUE THREAD

**Issue by shahp00ja** [SeleniumHQ/selenium#1926]
## Meta -

OS: Ubuntu ( EC2 AWS instance) / Macbook
Selenium Version: 2.52.0
Browser: Firefox 39.0 / 44.0.2
## Actual Behaviour -

Observe the Top Header bar is coming in between of the page (notice the breadcrumb icon on left), there is a long page with scroller
![image](https://cloud.githubusercontent.com/assets/12966925/14312119/703ea786-fc08-11e5-83c7-aa545b1d13a8.png)
## Expected Behaviour -

Should save screenshot as it is (no additional overlapping)
observe the header is on top
![image](https://cloud.githubusercontent.com/assets/12966925/14312170/b1de87f6-fc08-11e5-9949-44551000ad74.png)

Note: when same is checked physically, its all fine and top header at top itself on its place (ran test and viewed physically) + for chrome also,  appropriate screenshot is being taken.
Its necessary to get right screenshot because if test fails for some reason Ex. the header is hiding an element behind ( screenshot) and on click of it, it fails with:
Element is not clickable at point (572.6500244140625, 14.949996948242188). Other element would receive the click: <div class="top-nav" style="background-color:#ffffff;"></div> ]
But in actual, the top header never came on the way so it gives wrong impression of the cause of failure. [the reason of failure is different]
## Steps to reproduce -

Its an angular application (material design-single page application with vertical & horizontal scrollbar),  the page is containing multiple tabs, there are checkboxes( Android, Windows): on ticking, respective tabs gets enabled down.
![image](https://cloud.githubusercontent.com/assets/12966925/14308539/6c596a02-fbf4-11e5-8c6f-6fb161f6adce.png)

**Comment by AlberTajuelo** [comment]
Hi, did you resolve this bug?

**Comment by p00j4** [comment]
no, has to do with screenshottaker for firefox, because it works for chrome

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
