### ISSUE TITLE
Firefox WebDriver.get(url) returns before page is loaded

### ISSUE THREAD

**Issue by dmand** [SeleniumHQ/selenium#1927]
## Meta

OS: Ubuntu 14.04
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0 (also 44 and 43)
## Expected Behavior

Given Python script with two consecutive calls to `WebDriver.get(url)`, Firefox should open first url, fully load webpage, then open another page, and wait for it to load. 
## Actual Behavior

Firefox closes after loading the first page. More precisely, second call to `WebDriver.get(url)` returns almost immediately and doesn't wait for page to fully load.
## Steps to reproduce

It is actually a bit of a heisenbug, but i was able to reproduce it more or less reliably with the following python script:

``` python
from selenium import webdriver

driver=webdriver.Firefox()
driver.get('https://youtube.com/')
driver.get('https://github.com/')
driver.quit()
```
## Possible workarounds

``` python
from contextlib import contextmanager
from selenium import webdriver
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.support.ui import WebDriverWait

@contextmanager
def wait_for_page_load(driver, timeout=30.0):
    source = driver.page_source
    yield
    WebDriverWait(driver, timeout, ignored_exceptions=(WebDriverException,)).until(lambda d: source != d.page_source)

driver=webdriver.Firefox()
with wait_for_page_load(driver):
    driver.get('https://youtube.com/')
with wait_for_page_load(driver):
    driver.get('https://github.com/')
driver.quit()
```

**Comment by cgoldberg** [comment]
it depends on what you mean by "fully loaded".  AFAIK, the `get()` method returns when the page's `DOMContentLoaded` event fires... which may be different than what you consider loaded.

from MDN:
"The DOMContentLoaded event is fired when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading."

**Comment by dmand** [comment]
Yeah, i understand that AJAX requests are tricky and relying on `load` DOM event is good for most cases.

However, i'm pretty sure it is still a bug, because if you reverse the order of `get()` calls (see the following script) — Firefox will open and load both pages with no issues.

```
from selenium import webdriver

driver=webdriver.Firefox()
driver.get('https://github.com/')
driver.get('https://youtube.com/')
driver.quit()
```

P.S. I wanted to clarify that by "second call to `get()` returns almost immediately" i meant that it returns in 0.15s, while the first call can take up to 10s. So it doesn't seem like second call to `get()` was loading anything at all (except for maybe HTML).

P.P.S I also discovered that if i force driver to open blank page (`driver.get('about:blank')` in between of two other page loads — Firefox will load both pages and wait for full loading (which takes about 10s on my laptop).

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
