### ISSUE TITLE
Selecting Input Element to Enter Text not working in IE11 Microsoft Windows Server 2008 R2 Standard Service Pack 1

### ISSUE THREAD

**Issue by C0deS1ayer** [SeleniumHQ/selenium#1931]
## Meta -
OS: Microsoft Windows Server 2008 R2 Standard Service Pack 1
Selenium Version: 2.53 tried and 2.44.0 tried using jar
Browser: Remote IE
Browser Version: IE11 11.0.9600.18230 (32 bit)
Task Manager: FireDaemon Pro Service Manager v3.7 GA

Task Manager is running every 3000 milliseconds:
"C:\Program Files (x86)\Java\jre1.8.0_25\bin\java" -jar C:\\seleniumserver\\selenium-server-standalone-2.44.0.jar -Dwebdriver.ie.driver="C:\\seleniumserver\\IEDriverServer.exe" -Dwebdriver.firefox.bin="C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe"

## Expected Behavior -
For the send keys to work in the input.  I'm able to select an element to click (tested), select and element and confirm the right text is there.  But I am unable to select and element and have it input text either by class or id. I am running this via a task manager and firing my python to work in remote IE. I've run through all the security permissions make sure it's on Medium or lower.  Turned of EPM to ensure I'm on 32 bit.  I'm using the 32 bit windows driver.  And I have fixed the registry for the FEATURE_BFCACHE "iexplore.exe"=dword:00000000.  found here: http://heliumhq.com/docs/internet_explorer

## Actual Behavior -
It doesn't select element to input the text.  Although clicks a button so I know the click is working. I changed my url to google.com and saw that the send_keys were firing because google puts the keys in the input even if the input is not selected.  So still not working with google's input.  It is not selecting the input for google.com as well. 

## Steps to reproduce -

        Test = self.driver.find_by_id('Search')  **input element
        Test.clear() **removed and kept
        Test.click()  **removed and kept
        Test.send_keys('ITWORKS')
        Test.send_keys('BATMAN')
        time.sleep(10)

**Comment by jimevans** [comment]
As you acknowledge, this is not a global problem with the IE driver (you mentioned it works with Google.com). Without an HTML page to test this against, there is very, very little action that can be taken on this issue report.

**Comment by C0deS1ayer** [comment]
My apologies.  I was stating that the send_keys work and that the select input is not working.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
