### ISSUE TITLE
Server Grid breaks PhantomJS

### ISSUE THREAD

**Issue by fpiesche** [SeleniumHQ/selenium#1932]
## Meta -

OS: OSX
Selenium Version: 2.53.0
Browser: PhantomJS
Browser Version: 2.1.1
## Expected Behavior -

Getting a RemoteWebDriver for phantomjs from a Grid hub with connected nodes opens a phantomJS instance on an available node and returns a webdriver object to Python.
## Actual Behavior -

The hub receives the session request. Nothing further is logged on the hub or either node; however Python throws a `WebDriverException` with the message `Error forwarding the new session cannot find : Capabilities [{browserName=phantomjs}]`.

I have verified this with the hub and node running on the same machine as well as on different hosts on the same network.
## Steps to reproduce -
- run selenium server standalone
- get remote webdriver for phantomjs from server
- stop standalone server, start hub and node on same host or two separate ones
- get remote webdriver for phantomjs from server

[Python script for testing](https://github.com/SeleniumHQ/selenium/files/207004/seleniumbug.txt)
[WebDriverException stack trace](https://github.com/SeleniumHQ/selenium/files/207006/stacktrace.txt)

**Comment by nextofsearch** [comment]
I think #[2431] is related to this issue.

**Comment by barancev** [comment]
PhantomJS support discontinued. It is recommended to use Chrome or Firefox in headless mode.
