### ISSUE TITLE
How.XPath, Using=""

### ISSUE THREAD

**Issue by minoseah629** [SeleniumHQ/selenium#1936]
## Meta -
OS: Windows 10
Selenium Version: 
Browser: Firefox
Browser Version: 45.0.1 64b

## Expected Behavior -

When using FindsBy(How = How.XPath, Using = "//a[contains(@href,\"Summary\")]")],
I expect to have a IWebElement available to use.  

## Actual Behavior -

I receive a null object reference when I try to access this property on my page class.  

## Steps to reproduce -

My Page class is below:

[Fact]
        public void _4530_U_V_Career_Field_Code_by_Career_Field()
        {
            Login("automationuser1@automation.com");
            Repo.LandingPage.ExperienceLink.Click(); //This found using Driver.FindElement(By)
            Assert.Contains("Duty History", Repo.SharedElements.H2Text.Text);
            PageFactory.InitElements(Driver, Repo.ExperiencePage);
            **//At this point, ExperienceSummary should be initialized.  But is not. **
        }

public class SeeMyExperiencePage : Page
{
     [FindsBy(How = How.XPath, Using = "//a[contains(@href,\"Summary\")]")]
     public IWebElement ExperienceSummary;
     public SeeMyExperiencePage(IWebDriver driver): base(driver)
     {
          Driver = driver;
     }
}
public class Page
{
     public IWebDriver Driver { get; set; }
     public Page(IWebDriver driver)
        {
            Driver = driver;
        }
    }

public class ElementsRepository
{
     public string user;        
     public SeeMyExperiencePage ExperiencePage => new SeeMyExperiencePage(driver);
     public SharedElements SharedElements => new SharedElements(driver);
     public ElementsRepository(IWebDriver Driver)
      {
          driver = Driver;
      }
}

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by minoseah629** [comment]
I attached an example project to show what might be a problem.  

I put a short ui test to navigate to http://www.seleniumhq.org/ and then validates that using How.XPath, Using //a[contains(@href,\"#testing-frameworks\")]" should not be null.  

[XPath (2).zip](https://github.com/SeleniumHQ/selenium/files/209364/XPath.2.zip)
