### ISSUE TITLE
Timeout exception when element is not found on a page.

### ISSUE THREAD

**Issue by username9876** [SeleniumHQ/selenium#1937]
## Meta -
OS: Win 8.1
Selenium Version I tested with:  2.51.0, 2.52.0, 2.53.0
Browser: Firefox
Browser Version: 45.0.1
Webdriver: C#

## Expected Behavior -
WebDriver.FindElement() and WebDriver.FindElements() functions should return an empty collection/null/NoSuchElementException if the element is not found found on a page.
## Actual Behavior -
It will throw an exception after the configured wait time.
Exception:
"An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code

Additional information: The HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/19e937df-9d51-4624-a700-33f0ec6be98c/element timed out after 60 seconds."

## Steps to reproduce -
I tested it with multiple functions (By.Xpath, By.ClassName, By.CssSelector, etc.)

var webDriver = new FirefoxDriver();
webDriver.Manage().Timeouts().ImplicitlyWait(new TimeSpan(0, 0, 0, 60));
webDriver.Navigate().GoToUrl("http://google.com");
var resultElement = webDriver.FindElement(By.ClassName("NonExistingClass"));

However if I search for an element that exists the code works fine.

**Comment by username9876** [comment]
Is someone experiencing the same issue or am I doing something wrong?

**Comment by gurkini** [comment]
I have same issue. It appears randomly in different parts of code when using driver.FindElement([myLocator]). At screenshot on fail, target element is present on the page.
I'm using webdriver 2.53.0 + nunit 3.2.1 + firefox + jenkins.

**Comment by username9876** [comment]
I resolved this issue by simply removing the  `webDriver.Manage().Timeouts().ImplicitlyWait(new TimeSpan(0, 0, 0, 60));` 
now it simply throws a NoSuchElementException, and this can be handled correctly in a catch-block.
