### ISSUE TITLE
Selenium IDE does not record type input field (using autonumeric.js)

### ISSUE THREAD

**Issue by antonio-bakula** [SeleniumHQ/selenium#1940]
## Meta -

OS: Windows 10
Selenium Version: 2.9.1 IDE
Browser: Firefox
Browser Version: 45.0.1
## Expected Behavior -

IDE should record typing in input field
## Actual Behavior -

Nothing happens
## Steps to reproduce -

1. Record test on page [http://www.decorplanit.com/plugin/](http://www.decorplanit.com/plugin/)
2. Enter something in any of numeric fields, for example in Euro- Germany field
3. Nothing is recorded
4. Paste number in that same field, IDE recorded that as a type command

Here is a short video:[http://screencast.com/t/j2sI0RjTNv4](http://screencast.com/t/j2sI0RjTNv4)

**Comment by antonio-bakula** [comment]
I managed to find what is the root couse of this, autonumeric stops event bubbling of keypress event, and I commented this:
[http://screencast.com/t/tk6V45Mu87kp](http://screencast.com/t/tk6V45Mu87kp)
in autonumeric code and Selenium IDE records input in this field as expected. But I am  not confortable doing this because I don't know how would that influence on autonumeric and probably will cause bugs who knows where.

So I need a workaround for this issue, surely I am not first to stumble on such case, but searching for Selenium IDE and bubbling of keypress all I can find is some tips for selenese commands, so please HELP !

btw. here is the link to autonumeric git issue: [https://github.com/BobKnothe/autoNumeric/issues/199](https://github.com/BobKnothe/autoNumeric/issues/199)

**Comment by samitbadle** [comment]
Hi Antonio,

When JavaScript stops events from reaching Selenium IDE, the actions related to those events cannot be recorded as Selenium IDE does not know they happened. The solution is usually to change the JavaScript to pass on the events or to manually add in the test step in Selenium IDE. It is potentially possible to put in a workaround for a specific library, however with the number or such libraries out there, it will be unmaintainable for us to do so.

Cheers,
Samit

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
