### ISSUE TITLE
Concurrent Drivers in standalone server

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#1941]
[This spec is failing](https://github.com/SeleniumHQ/selenium/blob/master/rb/spec/integration/selenium/webdriver/spec_support/shared_examples/concurrent_driver.rb) when using the jar built from: `./go selenium-server-standalone-v3`

I've verified it passes with the latest 2.53 jar.

Here is [the debug information](https://gist.github.com/titusfortner/227ffdc815c271fdd5127b292d907d9f).

**Comment by lukeis** [comment]
@titusfortner is this still failing, also, how do you run this?

**Comment by lukeis** [comment]
and can you show the output of the run? cause I don't understand what is failing by the debug info

**Comment by titusfortner** [comment]
Fixed! Good job @lukeis! :)
