### ISSUE TITLE
Grid node does not register extra servlets

### ISSUE THREAD

**Issue by Rincewind77** [SeleniumHQ/selenium#1944]
## Expected Behavior -

When I start the grid node using "-role node -servlets my.test.Servlet" my test Servlet is registered.

## Actual Behavior -

I try to register extra servlets with Selenium 2.53.0 in role node. This does not work.
It works fine for role hub.
I had a look to the code and the required registration is missing for role node.

## Steps to reproduce -

Run org.openqa.grid.selenium.GridLauncher with arguments -role node -servlets my.test.Servlet

**Comment by lukeis** [comment]
this has been refactored in the latest code in master and should be working now, you can give it a try by either building from master or using the latest jar from our CI:
http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

note that this is the new 3.0 and pre-beta version :)
