### ISSUE TITLE
Documentation inconsistency - "assertAlertNotPresent" and "assertAlertPresent"

### ISSUE THREAD

**Issue by rst1** [SeleniumHQ/selenium#1948]
## Meta -

OS: Windows 10 Pro, X64
Selenium Version: IDE 2.9.1
Browser: Firefox
Browser Version: 44.0.2

Documentation inconsistency
## Expected Behavior -

Documentation for "assertAlertNotPresent" and "assertAlertPresent" 
is expected to differ
## Actual Behavior -

Documentation for two functions is the same
## Steps to reproduce -

in IDE, select a test case.
Add new command with reference tab visible in bottom pane
in turn select  "assertAlertNotPresent" and "assertAlertPresent" on command selection line
while observing reference tab in bottom pane.

![screen1](https://cloud.githubusercontent.com/assets/18352032/14390787/0c01dcd8-fd76-11e5-9fb3-dfc250a067cf.png)
![screen2](https://cloud.githubusercontent.com/assets/18352032/14390788/0c032fca-fd76-11e5-8d37-f67207ffd749.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
