### ISSUE TITLE
IE Driver fails input digit

### ISSUE THREAD

**Issue by Buzz2Buzz** [SeleniumHQ/selenium#1956]
## Meta -

OS: Windows 7 Enterprise
Selenium Version: 2.52.0
Browser: IE
Browser Version: 11.0.9600.18230
## Expected Behavior -

Types the right text in an input.
## Actual Behavior -

In my case, it happened when typing `3/`, and got `"/`.
I'm using a French keyboard, and `3` needs `Shift` to be pressed, so do `/`.
## Steps to reproduce -

Cannot reproduced it. It happens randomly.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
