### ISSUE TITLE
With PhantomJS cookies are always enabled, can't disable it

### ISSUE THREAD

**Issue by jamb0ss** [SeleniumHQ/selenium#1959]
In PhantomJS cookies can be disabled like this:

`phantom.cookiesEnabled = false;`

(see: http://phantomjs.org/api/phantom/property/cookies-enabled.html)

But in Selenium this settings are ignored.

Is there any way to disable cookies?

## Meta -
OS: Linux
Selenium Version: 2.53.1
Browser: PjantomJS
Browser Version: 2.1.1

## Expected Behavior -

Cookies can be disabled

## Actual Behavior -

Cookies cannot be disabled

## Steps to reproduce -

This PhantomJS script works just fine (first we set a cookie, then disable cookies at all, finally we don't see any cookies in the response from website):

```
var page = require('webpage').create();

phantom.addCookie({
	'name': 'testme',
	'value': 'testme',
	'domain': 'httpbin.org',
	'path': '/'
});

phantom.cookiesEnabled = false;

console.log('Cookies: ' + JSON.stringify(phantom.cookies));
console.log('cookiesEnabled: ' + JSON.stringify(phantom.cookiesEnabled));


page.open('http://httpbin.org/cookies', function (status) {
	console.log(page.plainText);
	phantom.exit();
});

```

But the same trick doesn't work with Selenium/GhostDriver/PhantomJS.
Cookies are always enabled.

Test:

```
from json import dumps
from selenium.webdriver import PhantomJS

driver = PhantomJS()
driver.command_executor._commands['executePhantomScript'] = ('POST', '/session/$sessionId/phantom/execute')
exec_script = lambda script: driver.execute('executePhantomScript', {'script': 'var page = this; ' + script, 'args': []})

cookie = {
    'name': 'testme',
    'value': 'testme',
    'domain': 'httpbin.org',
    'path': '/'
}

exec_script('page.addCookie(%s)' % dumps(cookie))
exec_script('phantom.cookiesEnabled = false')

# check that everything is set
print 'Cookies: ', str(exec_script('return page.cookies')['value'])
print 'cookiesEnabled: ', exec_script('return phantom.cookiesEnabled')['value']

driver.get('http://httpbin.org/cookies')

# cookie will be there...
print driver.page_source
```

**Comment by lukeis** [comment]
for phantomjs, please log bugs here:

https://github.com/detro/ghostdriver

I haven't tried, but I think you could disable cookies with the desired capabilities:

    driver = PhantomJS(desired_capabilities={'cookiesEnabled':False})

and without an enhancement, i think you can't toggle it.
