### ISSUE TITLE
Issue with Chrome Browser communication with selenium script

### ISSUE THREAD

**Issue by RaviVadhava** [SeleniumHQ/selenium#1960]
## Meta -
OS: 
Selenium Version: 
Browser: 

## Actual Behavior -

Hi,

I am using the code mentioned below,I am using selenium server 2.53 and chrome driver 2.21 ,both are latest according to selenium.org.
The issue is Chrome browser opens but nothing displays it keeps on running,Just the message in console is

"Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 54702
Only local connections are allowed".

public class first {
public static void main(String[] args) {

		
{
		System.setProperty("webdriver.chrome.driver","D:\\chromedriver_win32\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.navigate().to("http://www.msn.com");

		}

	}
}

I was previously using 2.48 selenium server for chrome browser but still it was same.

**Comment by QATester1** [comment]
Are you using at the beginning of your class?
` private WebDriver driver;`

If yes you may want to change your constructor to `driver = new ChromeDriver();`
I don't know what test runner you are using. I am using JUnit and my code for opening chrome and navigating to a url looks like this:

`public class Test1 {
     private WebDriver driver;
       
  @Before
  public void setUp() {
     System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
     driver = new ChromeDriver();
     }

  @Test
   public void testOne() {
	 driver.get("http://www.msn.com");
}`

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
