### ISSUE TITLE
Please Stop Firefox Driver Opening Firefox First Run Page - Do We Really Have To Live With This?

### ISSUE THREAD

**Issue by QATester1** [SeleniumHQ/selenium#1962]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 
IDE 
Language 
Test Runner 

## Expected Behavior -

Firefox driver will open Firefox to requested web url.

## Actual Behavior -

Firefox driver opens Firefox First Run page and test cannot continue.
I have tried various methods now to overcome this issue and I am just sick of it. Can you not just fix Selenium so it doesn't do this? With Selenium being tightly binded to Firefox you would think this issue would not exist.

I have tried:
- Create firefox profile and call it in the c# code - Does Not Work

`string path = @"C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles\w0izu99q.Test Profile";
FirefoxProfile ffprofile = new FirefoxProfile(path);
driver = new FirefoxDriver(ffprofile);`

- In c# code force Firefox to open to blank page - Does Not Work

`FirefoxProfile prof = new FirefoxProfile();
            prof.SetPreference("browser.startup.homepage_override.mstone", "ignore");
            prof.SetPreference("startup.homepage_welcome_url.additional", "about:blank");
            driver = new FirefoxDriver(prof);`

- Rolled back to older version of Firefox - Does Not Work
- Used older version of web driver - Does Not Work

## Steps to reproduce -

1) Create Selenium test in Visual Studio with C# that implements Firefox web driver
2) Run test
3) Observe Firefox always opens first run page

**Comment by lukeis** [comment]
Are you using the latest version of selenium? It should be fixed there

**Comment by pcbbc** [comment]
Just ran into this one after Firefox updated and my automation no longer launched the require page.  Downloaded latest selenium build and all better now.  Thanks.

**Comment by peterwippermann** [comment]
This is a problem with the browser, not with the driver.

Here's how I solved it for me:
`		FirefoxProfile profile = new FirefoxProfile();
		profile.setPreference("browser.startup.page", 0); // Empty start page
		profile.setPreference("browser.startup.homepage_override.mstone", "ignore"); // Suppress the "What's new" page

		return new FirefoxDriver(profile);`

**Comment by davehunt** [comment]
`browser.startup.page` is already set to `0` in the default profile, but we don't set `browser.startup.homepage_override.mstone` at all. This shouldn't matter unless we're reusing an old profile with an old value for this preference though. It shouldn't be a problem to just set this explicitly to `ignore` in the defaults though.

**Comment by davehunt** [comment]
Closing based on comments and https://github.com/SeleniumHQ/selenium/commit/f5b2ab52ca25b7b4e455de22fca60d3ee8844922

**Comment by peterwippermann** [comment]
That's great, thank you @davehunt !
I think `browser.startup.homepage_override.mstone` is especially important for new profiles. Old profiles would only be affected when updating to a new FF version.

**Comment by ShakeyDave** [comment]
I'm having this problem with the Selenium NuGet package published on the 29th June 2016, and setting up a browser profile doesn't fix it. Does anyone know if the version discussed above, in which this problem was fixed, is the version that's distributed via NuGet?

(If possible, I'd like to keep using NuGet as I've experienced issues relating to keeping Selenium in line with Firefox releases pretty much constantly for years... So a world in which I can just update a NuGet package when Firefox stops playing nicely would be a good one...)
