### ISSUE TITLE
DropDown selection doesn't work in IE 

### ISSUE THREAD

**Issue by phoenixcz** [SeleniumHQ/selenium#1963]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Description -
Tests using DropDown.SelectByVule() or DropDown.SelectByIndex(), that works fine in FF and Chrome are not working in IE causing the exception.

## Expected Behavior -
Drop downs should work fine in IE

## Actual Behavior -
Tests fail with following error:
`System.InvalidOperationException : Cannot click on option element. Executing JavaScript click function returned an unexpected error, but no error could be returned from Internet Explorer's JavaScript engine. (UnexpectedJavaScriptError)`

**Comment by lukeis** [comment]
You need to provide a reproducible test case, we can't do anything without one. We can reopen this issue when one is provided.
