### ISSUE TITLE
sendkeys ctrl-C does not work

### ISSUE THREAD

**Issue by seanv507** [SeleniumHQ/selenium#1964]
## Meta -

OS: Windows 7
Selenium Version: IDE 2.9.1
Browser: Firefox
Browser Version: 45.0.2
sendKeys
${KEY_HOME}${KEY_SHIFT}${KEY_END}${KEY_SHIFT}${KEY_CTRL}C${KEY_CTRL}
## Expected Behavior -

copy text in form to clipboard eg Name: BBC 
expect to copy BBC
## Actual Behavior -

original text is overwritten with C

it seems like ${KEY_CTRL} is recognised but not acted upon ( same behaviour with ctrl-V,... just get V
## Steps to reproduce -

[don't know suitable website]

**Comment by banu2016** [comment]
@seanv507   we dont have any operation command for CTL+c , CTRL+V, and dont have (a-z) alphabets
i you want to achieve please follow the below mentioned steps:
Use Actions Class > 
 double click and context click(Right Click), select the copy option from clipboard.
Try this way, i hope this will work

**Comment by seanv507** [comment]
Am trying that, how do I select copy from context menu without using CTRL-C
I tried ${KEY_DOWN}${KEY_DOWN}${KEY_DOWN}${KEY_ENTER}

but why is there this blog post by samit ?
http://blog.reallysimplethoughts.com/2013/09/25/using-special-keys-in-selenium-ide-part-1/

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
