### ISSUE TITLE
A call to the COM method IWebBrowser2::Navigate2() failed only in Jenkins

### ISSUE THREAD

**Issue by kesavaraojr** [SeleniumHQ/selenium#1966]
@lukeis 

OS: Windows 2008 R2
Selenium Version:  2.47.1, Eclipse IDE
Browser: IE 11 in Windows 2008 R2
Browser Version: 11.0.9600.18230 (64-bit)

## Expected Behavior -
- IEDriverServer should start and should navigate to given url

## Actual Behavior -
- WebDriverException: Failed to navigate to http://www.google.com This usually means that a call to the COM method IWebBrowser2::Navigate2() failed. 
Stack trace shows error on RemoteWebDriver : line 306)

## Steps to reproduce - 
Code as below:
`RemoteWebDriver driver;
<< capabality code >>
driver = new InternetExplorerDriver(capabality);
driver.get("http://www.google.com");`

## Issue:
Able to run above code in Eclipse IDE
Converted this code into executable JAR 
Able to run executable JAR from local (file system)
BUT
When we try to run this executable JAR in Jenkins getting error above error. 
Note: this executable JAR worked well on 7th April 2016 in Jenkins

## Tried:
Tried with Selenium 2.53.0 JARs and IEDriverServer_2.53.0_32_bit and IEDriverServer_2.53.0_64_bit - still the same issue

**Comment by kesavaraojr** [comment]
This is no longer happening in Jenkins - not sure how it got resolved

**Comment by RPsingh22** [comment]
I am facing the same Issue. Can anyone help, How to resolve.

**Comment by edisonan** [comment]
I am facing the same Issue.

**Comment by JKeetman** [comment]
I am facing the same issue, @edisonan, did you already found a solution?
