### ISSUE TITLE
Selenium 2.53 is typing wrongly in edit box with IE 11 actual text: tesus@0422.com typed as "t0422.com@sutes"

### ISSUE THREAD

**Issue by ashishpu** [SeleniumHQ/selenium#1970]
Selenium 2.53 is typing wrongly in edit box with IE 11 actual text: tesus@0422.com typed as "t0422.com@sutes"

OS:Windows 7
IE:11
Selenium : 2.53
IE Driver : 2.48 or 2.53.

Sometimes it doesn't even click on the object or fails to recognize object with given identifier.

**Comment by pavelpp** [comment]
I've seen similar behaviour with ChromeDriver on OSX

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided. Most probable reason is a field with a custom keypress handler, but it's impossible to make any decision without a reproduction sample.
