### ISSUE TITLE
When trying to open a URL containing some parameters, IE is not able to open it using webdriver

### ISSUE THREAD

**Issue by goyalvipul** [SeleniumHQ/selenium#1972]
## Meta -
OS: <Windows>
Selenium Version: <2.52.0, Webdriver, -->
Browser: 
Browser Version: 

## Steps to reproduce -

I am trying to open a url: "http://localhost:8000/qconsole/?qa=1" in Internet Explorer using driver.get() command, but not able to open the same.
If i go to URL panel, select it and hit enter - page opens.

Instead I am able to open page: "http://localhost:8000/qconsole" without any issues,

Please help
## Expected Behavior -

Page should open

## Actual Behavior -

Page not opening

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
