### ISSUE TITLE
clickandwait / selectwindow fails to find newly opened window

### ISSUE THREAD

**Issue by seanv507** [SeleniumHQ/selenium#1974]
## Meta -

OS:windows 7 64 bit-->
Selenium Version: selenium ide 2.9.1
Browser:firefox
Browser Version:45.02
## Expected Behavior -

I use click  which opens a new window
then I try selectwindow with nothing in the target field

I expect to then be  'moved' to the new window so that I can access fields (using storetext)
## Actual Behavior -

however, selectwindow 'works' (green) but doesn't go to the new window
and store text fails because I am still on the original window.
[this is with single stepping through the code]
If i try clickandwait then it times out

I am happy to provide an example if you can suggest a suitable website with click opening new window

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
