### ISSUE TITLE
Unable to launch Chromedriver while running my testng test suite through command prompt

### ISSUE THREAD

**Issue by Manceee** [SeleniumHQ/selenium#1975]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Expected Behavior -
Chromedriver process should be launched and Chrome browser should be opened , while running my testng test suite through command prompt

## Actual Behavior -
1. The testng.xml is instantiated, but Chromedriver is not instantiated while running through the command prompt
2. I do not see chrome.exe appear in the task manager when running the test through command prompt and testng
The test runs fine while running them through Eclipse IDE with TestNG

## Steps to reproduce -
1.Download appropriate prebuilt server as instructed on the webdriver wiki page.http://code.google.com/p/selenium/wiki/ChromeDriver
2.specified its location via the webdriver.chrome.driver system property
3. Instantiate the driver
4. I have also added the chromedriver exe path and the Chrome browser exe path on my OS "PATH" Environment variable
this is my "Path"
PATH=C:\ProgramData\Oracle\Java\javapath;%JAVA_HOME%\bin;C:\Program Files\Java\jdk1.8.0_77\bin;C:\Users\mbr9\workspace\FinalAutomation\lib;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files\Microsoft MPI\Bin\;c:\PROGRA~1\ds_shell\code\bin\ds_shell;C:\Oracle11gR2_32bCli\client_1\bin;C:\Oracle11gR2_64bCli\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Progr
am Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;c:\Program Files\ThinkPad\Bluetooth Software\;c:\Program Files\ThinkPad\Bluetooth Sof
tware\syswow64;
![testngchromedrivecommandprompt](https://cloud.githubusercontent.com/assets/18446660/14561997/6eda2708-031a-11e6-86af-fe160f5be0d6.png)

5. able to run C:\Program Files (x86)\Google\Chrome\Application\chrome.exe manually
6. My testng tests run well with Eclipse IDE using Chromedrive, issue is when running them though commandprompt. these testng test run great on Firefox while running through command prompt
6.Chromedriver process is opened by typing  "chromedriver" through the command prompt , i.e. I get this message "Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed."

Here is my code;

public class TestNGMyClass {
	
  public static WebDriver driver1;

@BeforeMethod //@BeforeTest
	public void setup() {
System.setProperty("webdriver.chrome.driver", "C:\\Users\\mbr9\\workspace\\FinalAutomation\\lib\\chromedriver.exe");
driver1 = new ChromeDriver();
driver1.manage().window().maximize();
		driver1.navigate().refresh();
		driver1.manage().deleteAllCookies();
driver1.navigate().to("https://www.google.com");
}
}

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
