### ISSUE TITLE
Firefox regression: No scrolling to partially displayed button anymore

### ISSUE THREAD

**Issue by OLibutzki** [SeleniumHQ/selenium#1981]
## Meta -
OS: Windows 7
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 38.5.1
Property focusmanager.tetsmode = true

## Expected Behavior -
The partially displayed button is clicked

## Actual Behavior -
The partially displayed button is not clicked, obviously because the footer covers most of the button.

## Regression in WebDriver 2.50.0
Obviously there's a regression in WebDriver 2.50.0. In 2.49.1 Firefox scrolls down a little in order to display the whole button. In 2.50.0 Firefox doesn't scroll and obviously the click is sent to the footer instead of the button.

## Steps to reproduce
* You need a button (in our case an image) which is partially convered (80%) by the footer.
* Call "click()" on the button's WebElement
* The click is not performed

I read #1202 entirely. The issue is highly related to this one, but this problem seems to be introduced by a fix caused by #1202. Maybe f3dc828ef04e971519d60251c73aa3933734ac6b or 65dbe9a154469fcad6318fba82452805281d6159 ?

**Comment by lukeis** [comment]
We can't help here unless you provide a sample html page that reproduces your issue

**Comment by lukeis** [comment]
Also, please use the latest 2.53. Can reopen when repro is provided and confirmed an issue on the latest version

**Comment by OLibutzki** [comment]
I use 2.53.0 which is the latest version. I just went to back to version where the error occurred for the first time which is 2.50.0.

**Comment by lukeis** [comment]
Ah, ok. Then please provide a reproducible html page + script
