### ISSUE TITLE
selenium/standalone-chrome:latest docker image does not work as of 2.53.0

### ISSUE THREAD

**Issue by gedkins** [SeleniumHQ/selenium#1984]
## Meta -
OS: Linux (Ubuntu 15.10) with Docker 1.10.2
Selenium Version: 2.53.0 (selenium/standalone-chrome:latest docker image as of 2016-04-18)
Browser: Google Chrome
Browser Version: Unknown (whatever is in the docker image)

## Expected Behavior -
Assuming docker is installed correctly, running
docker run -d -P selenium/standalone-chrome

should start Selenium with Google Chrome in a docker container.

## Actual Behavior -
The container immediately dies with a message saying it can't find /opt/bin/functions.sh

## Steps to reproduce -
$ docker run -d -P selenium/standalone-chrome
3b17acfa1613ee153d9ff980e7727335d5eb77562a618061d446976e75cb1c2f
$ docker logs 3b17acfa1613ee153d9ff980e7727335d5eb77562a618061d446976e75cb1c2f 
/opt/bin/entry_point.sh: line 3: /opt/bin/functions.sh: No such file or directory
/opt/bin/entry_point.sh: line 16: get_server_num: command not found

## Notes
selenium/standalone-chrome:2.53.0 seems to work correctly. It's only the image currently tagged "latest" which fails in this way.

**Comment by lukeis** [comment]
please log docker issues on the docker-selenium repo:
https://github.com/SeleniumHQ/docker-selenium
