### ISSUE TITLE
Setting ACCEPT_SSL_CERTS CapabilityType using remoteDriver and marionette

### ISSUE THREAD

**Issue by pembertonrw** [SeleniumHQ/selenium#1998]
## Meta -
OS: Windows 7
Selenium Version: Java / selenium-standalone-server 2.53.0
Browser: Firefox
Browser Version: 45.0.2

I am currently writing my webdriver tests to use the remoteDriver in Java.

I am looking at changing my Webdriver tests to use marionette instead of the firefoxDriver to see how much rework I might need to do if any to swap them over as it works with both Chrome and Firefox. As we use self-sign certs previously I was using the following code to turn off the certificate warnings in firefox:

        capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

I can see in the standalone selenium driver that the test is sending the right capabilities but when it is being passed to marionette/wires is is being passed with the value of false. Does anyone know why this value is not being sent over?

**Comment by AutomatedTester** [comment]
Unfortunately we have not implemented the unsigned cert feature in Marionette yet, there is an outstanding bug on https://bugzilla.mozilla.org/show_bug.cgi?id=1103196. I suggest following there for to see when it fixed.

Thanks for raising the bug. Also, could you, if you are on twitter, complete the poll at https://twitter.com/AutomatedTester/status/723097743053324288 to help me prioritise this work

**Comment by pembertonrw** [comment]
Hi, 

Awesome I kinda thought that might be the case but didn't know how to ask the question without raising a bug :)

**Comment by AutomatedTester** [comment]
No Problem! If you find more issues with Marionette, feel free to raise them against https://bugzilla.mozilla.org/enter_bug.cgi?product=Testing&component=Marionette&cc=dburns@mozilla.com
