### ISSUE TITLE
It is taking too long just to find element by id

### ISSUE THREAD

**Issue by nmorado** [SeleniumHQ/selenium#1999]
## Meta -
OS: OSX 10.11.4
Selenium Version: 2.53.0
Browser: Firefox
Browser Version: 45.0.2

## Steps to reproduce -
Just run a simple findElement test. With my configure above just a simple find element takes about 462778ms

**Comment by lukeis** [comment]
These are not steps to reproduce, it simply does not do this on most sites. Please provide a reproducible test case and we can reopen this bug

**Comment by nmorado** [comment]
The test case is simply below:


`
WebDriver driver - new FirefoxDriver();
driver.get(aUrl);
driver.findElement(By.id(anId));
`

Launch this using the configurations I specified above.

Thanks

**Comment by lukeis** [comment]
@nmorado that does not cause the issue you described... provide the URL and maybe we can look into the issue

**Comment by nmorado** [comment]
url = https://www.godaddy.com
element id = sign-in

Can you confirm if this looks good from your side?

**Comment by lukeis** [comment]
OSX 10.11.4, Firefox 45.0.2

    @Test
    public void testGodaddy() throws Exception {
      WebDriver driver = new FirefoxDriver();
      driver.get("https://www.godaddy.com");
      long startTime = System.currentTimeMillis();
      driver.findElement(By.id("sign-in"));
      System.out.println("Time delta: " + (System.currentTimeMillis() - startTime));
      driver.quit();
    }

outputs:
Time delta: 2391

Granted that is a substantial amount of time to find the element (2 seconds)

**Comment by nmorado** [comment]
something weird on my end - any ideas where/what I should look for to diagnose this one? Thanks

**Comment by lukeis** [comment]
obligatory:
![it_crowd](https://cloud.githubusercontent.com/assets/926454/14719059/e382824c-07ae-11e6-8d77-625c0969669b.gif)
