### ISSUE TITLE
Grid2 wiki page has invalid link

### ISSUE THREAD

**Issue by sishbi** [SeleniumHQ/selenium#2001]
The Grid2 wiki page:
https://github.com/SeleniumHQ/selenium/wiki/Grid2
has a link to the default node json config file:
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNode.json
which should actually be:
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json

**Comment by mach6** [comment]
this is now fixed.  
@lukeis fyi
