### ISSUE TITLE
Unable to launch Mozilla browser-43.0.2

### ISSUE THREAD

**Issue by abhinavm88** [SeleniumHQ/selenium#2002]
## Meta -
OS:  Windows Server 2008 R2
Selenium Version: 2.52.0
Browser: Firefox
Browser Version:  43.0.2

## Expected Behavior -
Selenium Webdriver should be able to open browser window and navigate to application URL.

## Actual Behavior -
Selenium throws an exception while opening FF browser

## Steps to reproduce -
I am automating the application which will close and open the browser multiple times during the execution. It will then navigate to the application URL. Opening and navigating is working fine for three times then suddenly on fourth time when browser is opened the below error is thrown.

Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7067; process output follows: 
talled' for fxdriver@googlecode.com
1461271073860	addons.xpi-utils	DEBUG	Make addon app-profile:fxdriver@googlecode.com visible
1461271073861	DeferredSave.extensions.json	DEBUG	Save changes
1461271073861	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1461271073861	DeferredSave.extensions.json	DEBUG	Save changes
1461271073862	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"NTVFpd8jlLxx","location":"app-profile","version":"2.53.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Users\\PNAGAR~1\\AppData\\Local\\Temp\\2\\anonymous3948280881312400475webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1461271054533,"updateDate":1461271054533,"applyBackgroundUpdates":1,"bootstrap":false,"size":3249525,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"47.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1461271073862	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1461271073874	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"msh1vqrl2Qm8","location":"app-global","version":"43.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1459489083081,"updateDate":1459489083081,"applyBackgroundUpdates":1,"skinnable":true,"size":24172,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"43.0.2","maxVersion":"43.0.2"}],"targetPlatforms":[]}
1461271073877	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1461271073880	DeferredSave.extensions.json	DEBUG	Save changes
1461271073880	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1461271073880	addons.xpi-utils	DEBUG	Updating add-on states
1461271073884	addons.xpi-utils	DEBUG	Writing add-ons list
1461271073913	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1461271073914	addons.manager	DEBUG	Provider finished startup: XPIProvider
1461271073914	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1461271073914	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1461271073915	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1461271073916	addons.manager	DEBUG	Starting provider: GMPProvider
1461271073937	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1461271073937	addons.manager	DEBUG	Provider finished startup: GMPProvider
1461271073938	addons.manager	DEBUG	Starting provider: PluginProvider
1461271073938	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1461271073938	addons.manager	DEBUG	Provider finished startup: PluginProvider
1461271073939	addons.manager	DEBUG	Completed startup sequence

**Comment by lukeis** [comment]
Please follow up on https://groups.google.com/forum/#!forum/selenium-users  if you are still having issues, selenium can reliably start firefox version 43 for me.
