### ISSUE TITLE
C# phantomjs fails to submit.

### ISSUE THREAD

**Issue by Zeioth** [SeleniumHQ/selenium#2005]
Hi, I'm trying to login into Google using phantomjs and C#, but when I click the next button nothing happens. Just the field lost the focus. Why is this? 

```csharp
using OpenQA.Selenium;
using OpenQA.Selenium.PhantomJS;
using OpenQA.Selenium.Support.Extensions;
using System.Drawing.Imaging;

// Goto url
webDriver.Navigate ().GoToUrl (
    "https://accounts.google.com/ServiceLogin#identifier");

// Write email
IWebElement emailField = webDriver.FindElementById("Email");
emailField.SendKeys ("john@gmail.com");

//Take a screenshot before and after submit.
webDriver.TakeScreenshot().SaveAsFile("./screenshot.png", ImageFormat.Png);
IWebElement btnNext btnNext = webDriver.FindElementById("next");
btnNext.Click ();
webDriver.TakeScreenshot().SaveAsFile("./screenshot2.png", ImageFormat.Png);
```
**BEFORE**
![screenshot](https://cloud.githubusercontent.com/assets/3357792/14764243/42d797ce-09b1-11e6-8fa0-783c92cc8cf4.png)

**AFTER**
![screenshot2](https://cloud.githubusercontent.com/assets/3357792/14764242/42cfece0-09b1-11e6-8285-b098d69c0cb1.png)

-Phantomjs version: 2.2.1
-Selenium version: 2.53

**Comment by lukeis** [comment]
issues with phantomjs (for webdriver) should be logged with the ghostdriver project:

https://github.com/detro/ghostdriver

**Comment by BellaBellaLi** [comment]
Try to construct WebDriver with this option:

            PhantomJSOptions options = new PhantomJSOptions();
            options.AddAdditionalCapability("acceptSslCerts", true);
            options.AddAdditionalCapability("applicationCacheEnabled", true);
