### ISSUE TITLE
Editing formatter source doesn't change the way it behaves

### ISSUE THREAD

**Issue by pudlovich** [SeleniumHQ/selenium#2007]
## Meta -

OS: Ubuntu 14.04
Selenium Version: IDE 2.9.1
Browser: Firefox
Browser Version: 45.0.2
One plugin installed - Selblocks
## Steps to reproduce -
1. Go into formats section of options.
2. Click "add"
3. Give it a title (e.g. "simpleformat")
4. Give it simple content - this.configForm = '<description>It doesn't work</description>'
5. Close and open the options panel, see that the format has the provided text in it
6. Edit the formatter's source - this.configForm = '<description>It works!</description>'
7. Close and open the options panel - the text hasn't changed
8. Open the formatter's source - it shows the correct, edited text

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
