### ISSUE TITLE
java.lang.NoSuchFieldError: INSTANCE (Selenium 2.53.0)

### ISSUE THREAD

**Issue by aroonseena** [SeleniumHQ/selenium#2011]
**META**

OS: Windows 7
Selenium Version: 2.53
Browser: Firefox
Browser Version: Not Available

Here is another team's issue I am trying to resolve. I have tried multiple suggestions out there on the web to remove the httpclient/httpcore jar, lower its version and the rest of the fixes including clean .m2 repo but still running into below stacktrace. I have tried most of the routine fixes but still not luck. Any help would be greatly appreciated!!!

**Stacktrace:**
java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConne
ctionSocketFactory.java:144)
        at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnec
tionManager(HttpClientFactory.java:71)
        at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClie
ntFactory.java:57)
        at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClie
ntFactory.java:60)
        at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.getDefau
ltHttpClientFactory(ApacheHttpClient.java:252)
        at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.<init>(A
pacheHttpClient.java:229)
        at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactor
y(HttpCommandExecutor.java:96)
        at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExec
utor.java:70)
        at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExec
utor.java:58)
        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.st
art(NewProfileExtensionConnection.java:87)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.j
ava:271)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav
a:119)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:2
16)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:2
11)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:2
07)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:1

**Dependency Tree**
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ someProject ---
[INFO] com.someproject:jar:0.0.1-SNAPSHOT
[INFO] +- org.testng:testng:jar:6.9.9:compile
[INFO] |  +- com.beust:jcommander:jar:1.48:compile
[INFO] |  +- org.apache.ant:ant:jar:1.7.0:compile
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.7.0:compile
[INFO] |  +- org.yaml:snakeyaml:jar:1.15:compile
[INFO] |  \- org.beanshell:bsh:jar:2.0b4:compile
[INFO] +- com.oracle:ojdbc7:jar:12.1.0.1:system
[INFO] +- apache-log4j:log4j:jar:1.2.15:system
[INFO] +- com.mercury.qualitycenter:otaclient:jar:9.2:system
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:2.53.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.53.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:2.53.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.53.0:compile
[INFO] |  |  +- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  |  \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:2.53.0:compile
[INFO] |  |  \- io.netty:netty:jar:3.5.7.Final:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:2.53.0:compile
[INFO] |  \- org.seleniumhq.selenium:selenium-leg-rc:jar:2.53.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:2.53.0:compile
[INFO] |  |  +- cglib:cglib-nodep:jar:2.1_3:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:2.53.0:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.1:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.3:compile
[INFO] |  |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  \- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  \- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] +- org.apache.poi:poi:jar:3.10.1:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.5:compile
[INFO] +- mysql:mysql-connector-java:jar:5.1.35:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:3.10.1:compile
[INFO] |  +- org.apache.poi:poi-ooxml-schemas:jar:3.10.1:compile
[INFO] |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |  \- dom4j:dom4j:jar:1.6.1:compile
[INFO] |     \- xml-apis:xml-apis:jar:1.0.b2:compile
[INFO] +- com.google.code.gson:gson:jar:2.3.1:compile
[INFO] \- junit:junit:jar:4.12:compile
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:compile

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by aroonseena** [comment]
I have posted this in the Selenium User Group.Thank You!
