### ISSUE TITLE
Consider returning Task<TResult> in IWait<TResult>

### ISSUE THREAD

**Issue by ohadschn** [SeleniumHQ/selenium#2012]
Generally speaking it is more efficient to do ```await Task.Delay(sleepInterval)``` than it is to do ```Thread.Sleep(sleepInterval)``` (as is currently done in ```DefaultWait<T>.Until()```).

MSTest for example supports async tests, so one could write code such as ```await wait.Until(d => d.Title.Equals("cheese"))```.

**Comment by jimevans** [comment]
The .NET bindings must still support .NET 3.5, and thus cannot support the `async/await` construct. Moreover, since the library is not multithreaded, it's unclear what benefits supporting the Task Parallel Library will achieve.

**Comment by ohadschn** [comment]
I didn't realize .NET 3.5 was supported, my mistake. You could take a dependency on something like [this](https://www.nuget.org/packages/TaskParallelLibrary/) but I suppose it's not worth the trouble.

The benefit will be freeing up the thread that is currently tied up by ```Thread.Sleep``` (e.g. put it back in the thread pool to potentially do other things), but I suppose in testing context it will typically be minor.
