### ISSUE TITLE
Chrome driver crashes (works in FF driver)

### ISSUE THREAD

**Issue by 2426021684** [SeleniumHQ/selenium#2015]
## Meta -
OS:  OSX
Selenium Version: 2.53.0
Browser: Google Chrome
Browser Version: 50.0.2661.86 (64-bit)
Library: Webdriver-io

## Expected Behavior -
It works

## Actual Behavior -
{ [Error: disconnected: Unable to receive message from renderer]
  message: 'disconnected: Unable to receive message from renderer',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'disconnected: Unable to receive message from renderer\n  (Session info: chrome=50.0.2661.86)\n  (Driver info: chromedriver=2.21.371459 (36d3d07f66
0ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.4 x86_64)

## Steps to reproduce -

```ts
const client = wd.remote(options).init()
client.url(test.url)
await client.execute(parseScript /* String of script */) // <-- Crashes here
var result = await client.execute(function (){
	var returnValue
	window.ExtensionPreprocessingJS.run({
		completionFunction: function(result) {
			console.log(result)
			returnValue = result
		}
	})
	return returnValue
})
```

**Comment by lukeis** [comment]
please log chromedriver issues with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
