### ISSUE TITLE
Element is not clickable for selecting drop down with Firefox driver 2.53 and FF version 46

### ISSUE THREAD

**Issue by indiamithu** [SeleniumHQ/selenium#2016]
## Meta -
OS: OSX os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4'
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version: 46

## Expected Behavior -
select an element from drop down list.

## Actual Behavior -
Not selecting element from the drop down list

## Steps to reproduce -
Clicked on the drop down, then clicked on the element that displayed.
org.openqa.selenium.WebDriverException: Element is not clickable at point (849.86669921875, 11). Other element would receive the click: <div class="fix-width"></div>
Command duration or timeout: 71 milliseconds

**Comment by lukeis** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided
