### ISSUE TITLE
Discussion about propably incorrect webdriver behavior

### ISSUE THREAD

**Issue by sergeychipiga** [SeleniumHQ/selenium#2018]
I would like to discuss about selenium behavior, which I consider as incorrect for web2.0 javascript saturated applications.

I have a test, that clicks submit at form. After click form hides and notification message (about data submitting) is shown. I want selenium to get notification message element after submit. But due to page in reloading state after submit, my selenium request waits until page will be reloaded. But after reloading notification message isn't shown.

I suppose these situations can be present often for modern web applications with angularjs, backbonejs, etc. And it's very simple to reproduce locally. You need run flask app:

```python
#! python /usr/bin/python
from time import sleep

from flask import Flask

app = Flask(__name__)


@app.route("/")
def hello():
    return """
    <html>
    <script>
    function reload() {
    setTimeout(function(){window.location.href = "http://localhost:5000/goodbye"}, 2000)
    }
    </script>
    <title>Hello world</title><body>
    <button onclick="reload()">Click</button></body>
    </html>
    """


@app.route("/goodbye")
def goodbye():
    sleep(60)
    return "<html><title>Goodbye</title><body>Goodbye</body></html>"


if __name__ == "__main__":
    app.run()
```

Then in interactive python console (for ex. ipython) need to execute next commands:

```python
from selenium.webdriver import Firefox
ff = Firefox()
ff.get('http://localhost:5000')
button = ff.find_element_by_tag_name('button')
button.click()
```
Wait a bit, until page will be in reloading state and then try to execute:
```python
button = ff.find_element_by_tag_name('button')
```

As you see, now your request is waiting until page will be reloaded. It means that selenium doesn't garantee, that you can get and check page (or element properties) status immediatelly when you need, and it can leads to flaky tests.

I used firefox webdriver. In forefox it happens because there is a code extensions/fxdriver@googlecode.com/components/command-process.js#L12604

```js
DelayedCommand.prototype.execute = function(a) {
  this.response_.session.getWaitForPageLoad() && !this.yieldedForBackgroundExecution_ && (this.yieldedForBackgroundExecution_ = !0, fxdriver.profiler.log({event:"YIELD_TO_PAGE_LOAD", startorend:"start"}));
  var b = this;
  this.driver_.window.setTimeout(function() {
    b.executeInternal_();
  }, a);
};
```

As we see, before execution webdriver waits for ```this.response_.session.getWaitForPageLoad()```. I think this problem is actual for all webdrivers for universality.

It's easy to understand why it is doing that: to prevent any actions to change page, when page is already in reloading state.

But **my proposition** is to separate selenium commands to get page state and to change page state. And commands to get page state must be executed immediatelly even page is in reloading state. But commands to change page state (open url, set element text, execute js script, etc) must work as before. It will allow us to get DOM info at any time and make selenium as realtime testing system.

**Comment by jleyba** [comment]
This is possible by changing the page load strategy (part of the w3c spec).
IIRC this has been implemented in Firefox.

Sorry for brevity - sent from my iPhone

**Comment by JosephCastro** [comment]
I use the `wait.until` functions for catch that elements

**Comment by lukeis** [comment]
this sort of discussion should be done on the mailing list(s) for selenium. But as pointed out the w3c spec will have a way to set timeouts, like page load timeout:
https://w3c.github.io/webdriver/webdriver-spec.html#dfn-session-page-load-timeout

and you should also be using the WebDriverWait / ExpectedConditions classes.
