### ISSUE TITLE
PhantomJS webdriver fails to instantiate with Selenium.

### ISSUE THREAD

**Issue by Kshitij9210** [SeleniumHQ/selenium#2020]
Hi,

I am trying to use PhantomJs with Selenium in my following method but my webdriver is failing to instantiate-

 def seat_counter(self, base_URL):
        path_to_phantomJS = 'C:\Program Files (x86)\phantomjs-2.1.1-windows\bin'
        driver = webdriver.PhantomJS(executable_path=path_to_phantomJS)
        driver.get(base_URL)

However I am repeatedly getting this error -
Error in executing trigger_seat_counter at time 1461834949.2
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Service object at 0x0340A910>> ignored

Selenium version is 2.53.2 and PhantomJS version is 2.1.1
OS : Windows
Have added the phantom executable to my path variable.

I tried to ignore the attribute error by implementing a try, except as recommended in the post -
http://stackoverflow.com/questions/27674088/scrapy-with-selenium-webdriver-failing-to-instantiate

However this does not work for me as the method execution still nontheless stops.

Any help would be much appreciated :)

Thanks a lot,
Kshitij

**Comment by srinin0470** [comment]
You can try the below code :

path_to_phantomJS = 'C:\Program Files (x86)\phantomjs-2.1.1-windows\bin' u can add phantomjs.exe after bean to intialise
or u can use below:
 DesiredCapabilities caps=new DesiredCapabilities();
       caps.setJavascriptEnabled(true);
       caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY, "path\\phantomjs.exe");
		WebDriver driver=new PhantomJSDriver();
       
		driver.get("http://www.gmail.com");

**Comment by lukeis** [comment]
PhantomJS launches reliably for the selenium project in Travis-CI. There may be an issue with your environment. Try to launch phantomjs manually without selenium first.

Also for issues with phantomjs or the selenium implementation there, please log them with that github project instead.
