### ISSUE TITLE
selenium submit , select and etc functions

### ISSUE THREAD

**Issue by mr-lks** [SeleniumHQ/selenium#2023]
## Meta -
OS: 
Selenium Version: 
Browser: 
Browser Version: 

## Expected Behavior -
just need to find out to run simple script well.
## Actual Behavior -
example script :  <?php
// An example of using php-webdriver.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once  'C:\xampp\vendor\..\vendor\autoload.php';
// start Firefox with 5 second timeout
$host = 'http://localhost:4444/wd/hub'; // this is the default

$desired_capabilities = DesiredCapabilities::Chrome();
$desired_capabilities->setCapability('acceptSslCerts', false);
$driver = RemoteWebDriver::create($host, $desired_capabilities);
// navigate to 'http://docs.seleniumhq.org/'
$driver->get('http://localhost');

// adding cookie
$driver->manage()->deleteAllCookies();
$driver->manage()->addCookie(array(
  'name' => 'cookie_name',
  'value' => 'cookie_value',
));
$cookies = $driver->manage()->getCookies();
print_r($cookies);

// click the link 'About'
$link = $driver->findElement(
  WebDriverBy::id('menu_about')
);
$link->click();

// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";

// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";

// Search 'php' in the search box
$input = $driver->findElement(
  WebDriverBy::id('q')
);
$input->sendKeys('php')->submit();

// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
  WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
    WebDriverBy::className('gsc-result')
  )
);

// close the Firefox
$driver->quit();
***********************************************************
Just having this problem after i call example script with phpunit 
20:53:22.841 INFO - Session c9a91749-8f53-4c6d-8442-cc4174377276 deleted due to client timeout
20:53:26.592 INFO - Session 635f9f22-feb0-4044-98cc-d2da04a06155 deleted due to client timeout
21:33:46.870 INFO - Executing: [new session: Capabilities [{acceptSslCerts=false, browserName=chrome, platform=ANY}]])
21:33:46.877 INFO - Creating a new session for Capabilities [{acceptSslCerts=false, browserName=chrome, platform=ANY}]
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 17607
Only local connections are allowed.
21:34:04.255 INFO - Done: [new session: Capabilities [{acceptSslCerts=false, browserName=chrome, platform=ANY}]]
21:34:04.281 INFO - Executing: [get: http://localhost])
21:34:05.114 INFO - Done: [get: http://localhost]
21:34:05.197 INFO - Executing: [delete all cookies])
21:34:05.202 INFO - Done: [delete all cookies]
21:34:05.209 INFO - Executing: [add cookie: cookie_name=cookie_value; path=/])
21:34:05.224 INFO - Done: [add cookie: cookie_name=cookie_value; path=/]
21:34:05.229 INFO - Executing: [get all cookies])
21:34:05.241 INFO - Done: [get all cookies]
21:34:05.309 INFO - Executing: [find element: By.id: menu_about])
21:34:05.339 INFO - Done: [find element: By.id: menu_about]
21:34:05.407 INFO - Executing: [click: null null])
21:34:05.408 WARN - Exception thrown
java.lang.NullPointerException
        at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:30)
        at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
21:34:05.421 WARN - Exception: null
HOW CAN I SOLVE THIS?

**Comment by ddavison** [comment]
Two things:

1. We aren't the maintainers of the PHP bindings
2. This looks like a user issue rather than an issue with selenium itself.  Please open up a thread in the selenium-users group here: http://groups.google.com/forum/#!forum/selenium-users

**Comment by mr-lks** [comment]
aight thx
