### ISSUE TITLE
selenium cause many hung chrome processes issue

### ISSUE THREAD

**Issue by leoforever** [SeleniumHQ/selenium#2025]
## Meta -
OS:  linux red hat 

Selenium Version:  2.47.1

Browser:  Google Chrome

Browser Version:  google-chrome-stable-50.0.2661.75-1

## Expected Behavior -
we run some scripts every five minutes in remote selenium mode , the results are usually good . But some times there will occur some hang process of chrome and they will never end . In the end it will never start session successful .
## Actual Behavior -
the hang process after selenium runs two days
 ps -eo pid,tty,comm,user,lstart,etime |grep -i chrome
24153 ?        chrome          root     Wed Apr 20 09:55:00 2016  2-20:09:29
24229 ?        chrome          root     Wed Apr 20 09:55:00 2016  2-20:09:29
24859 ?        chrome          root     Wed Apr 20 09:55:02 2016  2-20:09:27
24875 ?        chrome          root     Wed Apr 20 09:55:02 2016  2-20:09:27
25034 ?        chrome          root     Wed Apr 20 09:55:03 2016  2-20:09:26
25344 ?        chrome          root     Wed Apr 20 09:55:12 2016  2-20:09:17
## Steps to reproduce -

run 40 scripts  every 5 minutes in remote mode   for two days , and i think  it will occurs a lot of hang chrome process.
the example of our scripts , you can run it via selenese runner
[Jack-bing-com.zip](https://github.com/SeleniumHQ/selenium/files/241986/Jack-bing-com.zip)

**Comment by jjYBdx4IL** [comment]
can we please have some stress tests? chrome is failing badly at startup/shutdown via chromedriver lately (last 1-2 years or so) in some CI environments.

**Comment by lukeis** [comment]
feel free to provide a stress test of some kind (Pull Requests gladly accepted). Also are you sure it's a problem with Selenium Standalone server and not chromedriver itself? Has anyone provided a reproducible test suite to help reproduce this? And logged that with the chromedriver project?

**Comment by jjYBdx4IL** [comment]
The bug is known by the chromium developers, but they don't care because they think it's glib's responsibility: crbug.com/309093

**Comment by jjYBdx4IL** [comment]
I have set up a test case here: https://github.com/jjYBdx4IL/selenium-start-stop-stresstest

It reproduces the problem inside travis CI.

**Comment by lukeis** [comment]
it seems the bug lies with chrome/chromedriver? (Which means just logging bugs for them)

Unless there's a way to kill these hung processes? which we could possibly do, except we only track the chromedriver process, not chrome itself, chromedriver does that. So if it's hung chrome we'll need to log a bug with chromedriver, otherwise if it's a hung chromedriver process we can try to handle a more forceable kill.

**Comment by jjYBdx4IL** [comment]
Just set a random value for the DBUS_SESSION_BUS_ADDRESS environment variable when starting chromedriver. That should fix it.

**Comment by jjYBdx4IL** [comment]
We should maybe set this env var when start the chromedriver process.

**Comment by jjYBdx4IL** [comment]
https://cs.chromium.org/chromium/build/scripts/slave/runtest.py?q=DBUS_SESSION_BUS_ADDRESS&sq=package:chromium&dr=C&l=93

**Comment by lukeis** [comment]
Did setting that help your test suite?

**Comment by jjYBdx4IL** [comment]
yes. look at the travis built results https://travis-ci.org/jjYBdx4IL/selenium-start-stop-stresstest

**Comment by lukeis** [comment]
bug logged with chrome, should be tracked there
