### ISSUE TITLE
IEDriverServer fails to extract and launch on 

### ISSUE THREAD

**Issue by sebastianhoe** [SeleniumHQ/selenium#2026]
## Meta -

OS:  Windows Server 2008 r2

Selenium Version:  2.53

Browser:  IE

Browser Version:  11

## Expected Behavior -

IEDriverServer launches
## Actual Behavior -

Failed to launch with:
Failed to load the library from temp directory: C:\Users\MERLIN~1.USE\AppData\Local\Temp\1Apr 29, 2016 9:22:26 AM org.openqa.selenium.os.UnixProcess checkForError

Probably caused by deleted temp folder. When trying to run the IEDriverServer, it creates a file "1" instead of a folder "1" in the temp folder. Manually creating the folder in the temp folder solved the issue, but it probably should be fixed in the code.

**Comment by barancev** [comment]
Is this issue still actual? It looks like an environment issue, there is no knows way to reproduce it and there is no debug log, so it's not actionable in its current state.

**Comment by sebastianhoe** [comment]
Don't think so, sorry, I didn't observe it recently. Closing it.
