### ISSUE TITLE
driver.getWindowHandles() is inconsistent

### ISSUE THREAD

**Issue by dratnakar** [SeleniumHQ/selenium#2028]
## Meta -
OS:  
Win 7
Selenium Version:  
2.53.0
Browser:  
IE
Browser Version:  
11

## Expected Behavior -

driver.getWindowHandles() should return correct size

## Actual Behavior -

driver.getWindowHandles() always returning 1

## Steps to reproduce -
Hi Team,
 When I click on one link on my application a new window will open with "Certificate Error" , there I need to click on "Continue this website" link. But this window is not identified during run time. I have used driver.getWindowHandles() but its size is always returning 1 only. I got correct size only first time after updating the registry settings (as mentioned in IE 11 prerequisite settings), but second time onwards its returning 1 only.

Win OS: Win 7
 IE : 11
 Selenium webdriver : selenium-2.53.0 with IE Driver 2.53.0

Here is my code as below:

import java.text.SimpleDateFormat;
 import java.util.Date;
 import java.util.Set;
 import java.util.concurrent.TimeUnit;
 import org.openqa.selenium.By;
 import org.openqa.selenium.WebDriver;
 import org.openqa.selenium.WebDriverException;
 import org.openqa.selenium.WebElement;
 import org.openqa.selenium.ie.InternetExplorerDriver;
 import org.openqa.selenium.remote.DesiredCapabilities;
 import org.openqa.selenium.support.ui.ExpectedCondition;
 import org.openqa.selenium.support.ui.ExpectedConditions;
 import org.openqa.selenium.support.ui.Select;
 import org.openqa.selenium.support.ui.WebDriverWait;

public class PolicyGenerate {
 public static WebDriver objDriver;
public static void main(String[] args) {
    try {
        System.setProperty("webdriver.ie.driver", "C:\\selenium-2.53.0\\IEDriverServer_Win32_2.53.0\\IEDriverServer.exe");

        loginLogin();
    }
    catch(Exception objEx) {
        objEx.printStackTrace();
    }
    // TODO Auto-generated method stub

}

public static void waitForNewWindowAndSwitchToIt(WebDriver driver, String cHandle, String strTitle) throws InterruptedException {

    String newWindowHandle = null;

    //Wait for 20 seconds for the new window and throw exception if not found
    for (int i = 0; i < 20; i++) {
        Set<String> allWindowHandles = driver.getWindowHandles(); 
        if (allWindowHandles.size() > 1) {
            for (String allHandlers : allWindowHandles) {                   
                if (!allHandlers.equals(cHandle))
                    newWindowHandle = allHandlers;
            }
            driver.switchTo().window(newWindowHandle);
            if(driver.getTitle().startsWith(strTitle)) {
                cHandle = driver.getTitle();
                break;
            }
            else {
                Thread.sleep(1000);
            }
        } else {
            Thread.sleep(1000);
        }
    }
    if (cHandle == newWindowHandle) {
        throw new RuntimeException(
                "Time out - No window found");
    }
}

static void loginLogin() {
    WebElement objElement;

    try {

        DesiredCapabilities objCap = DesiredCapabilities.internetExplorer();
        objCap.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        objCap.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);

        //  Accept unexpected alerts
        objCap.setCapability("requireWindowFocus", true);
        objCap.setCapability("enablePersistentHover", false);

        objDriver = new InternetExplorerDriver(objCap);

        objDriver.manage().timeouts().pageLoadTimeout(180,TimeUnit.SECONDS);
        objDriver.manage().timeouts().implicitlyWait(180, TimeUnit.SECONDS);

        objDriver.get("https://www.test.com/home.html"); 

        objDriver.manage().window().maximize();

        objElement = objDriver.findElement(By.cssSelector("a[class='loginBtn medium']"));
        objElement.click();

        (new WebDriverWait(objDriver, 90)).until(new ExpectedCondition<Boolean>() {
            public Boolean apply(WebDriver d) {
                return d.findElement(By.id("loginId")).isDisplayed();
            }
        });
        Thread.sleep(2000);
        objElement.sendKeys("");
        Thread.sleep(2000);
        objElement = objDriver.findElement(By.id("loginId"));
        objElement.sendKeys("scindex2");
        Thread.sleep(2000);
        objElement = objDriver.findElement(By.id("loginPassword"));
        objElement.sendKeys("");
        objElement.sendKeys("Life1234");
        Thread.sleep(2000);

        objElement = objDriver.findElement(By.xpath("//*[@id='loginPanel']/div[2]/form/div/div/fieldset/div[2]/div[1]/button"));
        objElement.click();
        (new WebDriverWait(objDriver, 90)).until(new ExpectedCondition<Boolean>() {
                public Boolean apply(WebDriver d) {
                    return d.getTitle().startsWith("Test");
                }
            });
        (new WebDriverWait(objDriver, 90)).until(ExpectedConditions.elementToBeClickable(By.linkText("TOOLS")));
             objElement = objDriver.findElement(By.linkText("TOOLS"));
             objElement.click();
             Thread.sleep(2000);
        (new WebDriverWait(objDriver, 90)).until(new ExpectedCondition<Boolean>() {
                public Boolean apply(WebDriver d) {
                    return d.getTitle().startsWith("Test");
                }
            });
        Thread.sleep(2000);
        (new WebDriverWait(objDriver, 90)).until(ExpectedConditions.elementToBeClickable(By.linkText("nbA - Life 2012")));
            objElement = objDriver.findElement(By.linkText("auto"));
            objElement.click();
            Thread.sleep(2000);
        (new WebDriverWait(objDriver, 90)).until(new ExpectedCondition<Boolean>() {
                public Boolean apply(WebDriver d) {
                    return d.findElement(By.tagName("Font")).isDisplayed();
                }
            });
        Thread.sleep(2000);
        String cHandle = objDriver.getWindowHandle();

        objElement = objDriver.findElement(By.linkText("QA5"));
        objElement.click();

        Thread.sleep(5000);

        objDriver.manage().timeouts().implicitlyWait(90, TimeUnit.SECONDS);

            waitForNewWindowAndSwitchToIt(objDriver, cHandle, "Certificate Error");         

            objElement = objDriver.findElement(By.name("overridelink"));
            objElement.click();
            Thread.sleep(5000);
            objDriver.manage().timeouts().implicitlyWait(90, TimeUnit.SECONDS);

            waitForNewWindowAndSwitchToIt(objDriver, cHandle, "Certificate Error");

            objElement = objDriver.findElement(By.name("overridelink"));
            objElement.click();

    } catch (Exception e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }   

}

**Comment by velanbabu** [comment]
Even I'm facing same issue. Please provide solution for this

**Comment by JustinPhlegar** [comment]
Try removing this line and see if you get the same behavior.
```java 
objCap.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
```

**Comment by dratnakar** [comment]
Tried. But same issue.

**Comment by dratnakar** [comment]
do we have any solution for this..? Its blocking our development activity..
Tried with full admin rights to the machine and without full rights. Even removed "INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS", but same issue. Tried with IE webdriver with older versions also.

**Comment by dratnakar** [comment]
Finally I got the solution for this issue. I made a setting in IE by Enabling "Override automatic cookies handling". It solved my issue window handler issue.
To set goto, Tools > Internet Options > Privacy > Click on Advanced > Check Override Automatic cookie Handling and Click on Ok button

We need to restart the machine to work this setting. 

velanbabu could you try this, if it works we can close this issue...

**Comment by rahnaroker** [comment]
@dratnakar your desicision doesn't work
