### ISSUE TITLE
getting exception with chromedriver 2.21

### ISSUE THREAD

**Issue by Sourabh25** [SeleniumHQ/selenium#2034]
I am getting the below exception

org.openqa.selenium.WebDriverException: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
(Session info: chrome=49.0.2623.110)
 Kindly update on this

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by Sourabh25** [comment]
Hi, Actually i got the issue resolved. I have to configure jdk with eclipse and it start working fine. Thanks
