### ISSUE TITLE
Firefox beta (47.0b1) crashes when opened through Webdriver

### ISSUE THREAD

**Issue by nirp1981** [SeleniumHQ/selenium#2036]
## Meta -
OS:  
Windows 7 
Selenium Version:  
2.53
Browser:  
Firefox
Browser Version:  
47.0b1

## Expected Behavior -
Browser loads.
## Actual Behavior -
Browser crashes.
## Steps to reproduce -
Run:
		FirefoxBinary b  = new FirefoxBinary(new File("C:\\FirefoxBeta\\firefox.exe"));
		 FirefoxDriver f = new FirefoxDriver(b, new FirefoxProfile());

http://sscce.org/ -->

**Comment by willyaranda** [comment]
Same here on MacOS

**Comment by p0deje** [comment]
Selenium does not support beta versions of Firefox - tt may or may not work.

You can also try to use Marionette - it's the future of Firefox driver.
