### ISSUE TITLE
Selenium Chrome Mobile Emulator testing with specific phone resoultion

### ISSUE THREAD

**Issue by chandrasekhar4u** [SeleniumHQ/selenium#2039]
## Meta -
OS:  WINDOWS 7

Selenium Version:  2.53.0 for java

Browser:  CHROME

Browser Version:  49.0.2623.110 m

## Expected Behavior -
I am writing selenium script for testing different mobile views,
I used below code to run the script for "Apple iPhone 5" for the instance.

```
static DesiredCapabilities  capabilities;
	 static String deviceName;
	 public static void main(String[] args) {
	  //some Sample Devices. Complete list can be found here: https://code.google.com/p/chromium/codesearch#chromium/src/chrome/test/chromedriver/chrome/mobile_device_list.cc
	  //pick any of the device
	  
	//  deviceName = "Google Nexus 5";
	//  deviceName = "Samsung Galaxy S4";
	//  deviceName = "Samsung Galaxy Note 3";
	//  deviceName = "Samsung Galaxy Note II";
	//  deviceName = "Apple iPhone 4";
	  deviceName = "Apple iPhone 5";
	//  deviceName = "Apple iPad 3 / 4";

	  System.setProperty("webdriver.chrome.driver", "C:\\path\\to\\driver\\chromedriver.exe");
	  
	  Map<String, String> mobileEmulation = new HashMap<String, String>();
	  mobileEmulation.put("deviceName", deviceName);
	  
	  Map<String, Object> chromeOptions = new HashMap<String, Object>();
	  chromeOptions.put("mobileEmulation", mobileEmulation);

	  capabilities = DesiredCapabilities.chrome();
	  capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
	  WebDriver driver = new ChromeDriver(capabilities);
	  
	  driver.manage().window().maximize();
	  driver.navigate().to("http://www.google.com");

	 }
```

When I run this I am getting error like `unknown error: unrecognized chrome option: mobileEmulation`

> Please help me to get proper reference to write selenium script for mobile emulation(mobile height and width should be changed based on device),
> and let me know the issue with the existing code.

## Actual Behavior -
Getting error like `unknown error: unrecognized chrome option: mobileEmulation`

## Steps to reproduce -
please compile code given in expected result.

**Comment by lukeis** [comment]
for chromedriver issues please log reproducible test cases with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

For questions / user help, please post on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users
