### ISSUE TITLE
verifySelectedLabel and verifySelectOptions omit Values when exported to Python

### ISSUE THREAD

**Issue by smithnuc** [SeleniumHQ/selenium#2042]
## Meta -

OS:  Windows 7
Selenium Version:  IDE 2.0.1
Browser:  Firefox 
Browser Version:  45.0.2 
## Expected Behavior -

Then the following IDE code is entered:

```
<tr>
    <td>verifySelectedLabel</td>
    <td>id=panelid</td>
    <td>MyStuff</td>
   </tr>
   <tr>
    <td>verifySelectOptions</td>
    <td>id=panelid</td>
    <td>item1,item2</td>
   </tr>
```

  Then that code is Exported via the "Python 2 / unittest / webdriver" option, expected results are:
   (the appropriate python-compatable command)
## Actual Behavior -

> ```
>     # ERROR: Caught exception [ERROR: Unsupported command [getSelectedLabel | id=panelid | ]]
>     # ERROR: Caught exception [ERROR: Unsupported command [getSelectOptions | id=panelid | ]]
> ```
## Steps to reproduce -
1. Type in the two commands above
2. File
3. Export Test Case As...
4. Python 2 / unittest / webdriver
5. (send to appropriate filename, then display in editor)

Note that the Values in the Selenese code above have been omitted in the exported python code.  One of two options would be better:
1.  Export this to operational python code
2.  Include the Values in the error messages.
Any suggestions on how we might achieve one of those two sought results?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
