### ISSUE TITLE
Not able to handle Multiple windows in IE using Selenium Webdriver

### ISSUE THREAD

**Issue by Ajantasy** [SeleniumHQ/selenium#2045]
## Meta -
OS:  windows 7 64 BIt

Selenium Version:  2.53

Browser:  IE

Browser Version:  11

## Steps to reproduce -We have a scenario where Clicking on button it will open another  window, i want to perform some action on newly opened window  using Selenium Web driver
but somehow IE is not able to find that and driver.getWindowHandles() is returning a set with size 1 (only original window).
Note :This issue is not observing in Chrome

**Comment by lukeis** [comment]
Please provide a reproducible test case that includes html or link to a page and a test script that shows the behavior. 

When that is provided we can reopen the issue.
