### ISSUE TITLE
return browser process id to client

### ISSUE THREAD

**Issue by gouchaoer** [SeleniumHQ/selenium#2056]
client only knows session id of browser process.
in my case, i need to know the process id of a browser session to check cpu usage and terminate it if selenium failed to clean session(return browser process id to client).

so i hope selenium expose the process id to client.

**Comment by gouchaoer** [comment]
selenium sometimes failed to close session such as(https://github.com/SeleniumHQ/selenium/pull/2031)

**Comment by lukeis** [comment]
this depends on which language you're using of selenium.  But if you're using the standalone-server, no it does not expose the pid of either the browser nor the driver service it may have started.

We have no intention of exposing the pid with the capabilities back to the client, it's a level of abstraction that shouldn't be necessary. (Thus I will close this issue).

If you have a particular scenario that often leads to the browser process not being terminated, please log that as a bug, be sure to include the relevant information for us to help, like OS version, Browser version, Selenium client binding languages used, if you're using the standalone server. Also if you're able to a test case (script) that demonstrates the issue you're seeing (even if intermittent).

**Comment by adanhawthorn** [comment]
This is braindamage: if you don't support some basic handling of browser functionality (ie opening a print dialog) then why not allow us to *easily and rationally* do it (via a pid) in some other way?  Honestly, this level of obfuscation will help to obsolete--not complete your software.  Playing nicely in the school yard will go a long way for adoption.
