### ISSUE TITLE
Many network connections to port 7055

### ISSUE THREAD

**Issue by yoongu** [SeleniumHQ/selenium#2058]
## Meta -

OS:  Windows Server 2008 R2

Selenium Version:  2.53.0

Browser:  Firefox

Browser Version:  45.0.x

## Actual Behavior -

I am running Firefox tests on a Windows Server VM hosted on Amazon EC2. Everything was fine for the past couple of months until several days ago, when I started seeing a large number of network related exceptions in Selenium. Here are two such examples that I see:

```
OpenQA.Selenium.WebDriverException: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7055/hub/session/1296d801-c6bb-4452-84d5-67f2abbad5b3/element/%7Bea57d4ac-5b8d-499b-8bc6-fff24e995d8d%7D/attribute/value. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
```

```
OpenQA.Selenium.WebDriverException: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted 127.0.0.1:7055
```

These exceptions go away for several hours if the VM is rebooted, but they eventually come back. And when they do, I see a large number of connections involving port 7055. Using Window's "netstat" tool, I see **thousands upon thousands** of connections to/from port 7055 that are left in the "TIME_WAIT" state. Is this normal?

**Comment by cgoldberg** [comment]
each socket will stay in a TIME_WAIT for a few minutes after a connection closes.  It's only an issue if you exhaust your usable ports.

**Comment by bboe** [comment]
We are running into a similar problem with exhausted ephemeral ports. While we can increase the ephemeral range, it seems like it should be unnecessary. Is there a reason that selenium doesn't use persistent HTTP connections, that is, reuse the TCP connection for subsequent requests?

**Comment by drauch** [comment]
We experience the same problem - please reuse ports or keep the connection alive.

**Comment by shs96c** [comment]
Do you see this problem if you use the geckodriver provided by Mozilla?

**Comment by krosenvold** [comment]
Isnt this just httpd.js As usual ?

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
