### ISSUE TITLE
I've found a setting to activate webdriver native events in IE11

### ISSUE THREAD

**Issue by bobafetthotmail** [SeleniumHQ/selenium#2064]
Internet Options -> Security tab -> Custom Level (button) -> enable "allow scripting of Microsoft Web Browser Control"

Now I don't need to disable native events with capabilities.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);
to get it to click things at all.

nor do any custom configuration when invoking IE11 webdriver.

(the other IE11 configurations and windows system configurations of course still apply, I mean "no capabilities of the driver")

Please update the documentation with it

**Comment by jimevans** [comment]
I'm not sure I understand what you're trying to accomplish with this documentation update. Changing this setting in IE will not magically disable native events in the driver. The only way to disable native events is to set the capability.

**Comment by bobafetthotmail** [comment]
I had to use the capabilities.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);
to use IE at all as without that setting it was not clicking anywhere.

With native events disabled it's not very usable on my sites anyway.

With this setting enabled, I don't need to disable native events to force the use of javascript clicking, it clicks correctly (natively?).
