### ISSUE TITLE
IEDriver get stuck when loading special web pages

### ISSUE THREAD

**Issue by kid551** [SeleniumHQ/selenium#2068]
## Meta -

OS:  Windows 7

Selenium Version:  selenium-server-standalone-2.52.0

Browser:  IE (I used the latest IEDriver.exe file.)

Browser Version:  11.0.9600.18282 (64-bit)

## Expected Behavior -

When loading 3 different special web pages, the whole testing will be stuck. But it can work fine when load other web page URL.
## Actual Behavior -

The 3 different web pages should be opened successfully first. And then, they can be closed correctly.
## Steps to reproduce -

**Java code:**

```
void seStartWebBrowser() throws Exception{
    System.setProperty("webdriver.ie.driver", "C:/SeleniumPlus/extra/IEDriverServer.exe");      
    DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
    capabilities.setCapability("nativeEvents", true);
    capabilities.setCapability("requireWindowFocus", true);
    capabilities.setJavascriptEnabled(true);
    capabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);

    org.openqa.selenium.WebDriver wd1 = new InternetExplorerDriver(capabilities);   
    org.openqa.selenium.WebDriver wd2 = new InternetExplorerDriver(capabilities);
    org.openqa.selenium.WebDriver wd3 = new InternetExplorerDriver(capabilities);

    String url1 = "http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert";
    String url2 = "http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm";
    String url3 = "http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt";

    wd1.get(url1);
    wd2.get(url2);
    wd3.get(url3);

    wd1.quit();
    wd2.quit();
    wd3.quit();
}
```

When calling this method about 12 times,

```
for (int i = 0; i < 6; i++) {
    seStartWebBrowser();
}
```

It may get stuck at about 3rd or 4th calling.

But if we use another group of URLs, like:

```
url1 = "https://www.google.com";
url2 = "https://www.baidu.com";
url3 = "http://www.bing.com";

```

It won't get stuck with 12 times calling.

**Comment by Tarbej** [comment]
@kid551  : Try for below solution:
Go to Internet Explorer -> Tools -> Internet Options -> Trusted sites -> Site -> Add the url of your site (URLs which you are opening in browser in your automations).

After this, please re run your test case and let me know.

**Comment by kid551** [comment]
Hi @Tarbej ,

Thanks for your reply. 

I've tried to add _http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert_ in the Site, but it only added _http://www.w3schools.com_.

So I added _http://www.w3schools.com_ or _http://*.w3schools.com_ in the Site. But they all don't help. My test will still get stuck.

**Comment by kid551** [comment]
Hi @Tarbej ,

Are there some progress about this issue? My testing automation is always stuck with this issue. Could you give me some feedback about this problem?

Thank you very much.

**Comment by barancev** [comment]
Is this issue still actual? I tried the provided example with IEDriverServer 3.141.5.13, it passed 50 iterations successfully.

**Comment by barancev** [comment]
Closing the issue, it's related to antique IE driver versions and seems to be not relevant anymore.
