### ISSUE TITLE
Feature Request - Node : Prepare to shutdown / Accept no more sessions

### ISSUE THREAD

**Issue by timothyclarke** [SeleniumHQ/selenium#2070]
Currently if I call http://node:port/selenium-server/driver/?cmd=shutDownSeleniumServer the node shuts down. currently running connections are killed etc.

I'd like to request a feature to instruct the node to not accept any new sessions. That way existing sessions are able to complete and the node in question can be removed from the grid with minimal impact. 
For extra functionality there should be a "Return To Service" function. 
## Background -

On a busy grid it's hard to decommission a node without impacting some tests.
## Expected Behavior -

http://node:port/selenium-server/driver/?cmd=prepareToShutdown
New sessions are rejected.

**Comment by ThomWilhelm** [comment]
Hi @timothyclarke I've come across this same issue recently, I'm trying to shutdown a node on a grid without killing the tests currently running on the node.

Have you figured out any workarounds for this issue?

**Comment by mach6** [comment]
The way to do this is to write your own `-proxy` class which stops forwarding new sessions to the node once you are in the "shutting down" state.

**Comment by timothyclarke** [comment]
@ThomWilhelm No sorry. I'm not a java dev or I'd submit a pull request.
@mach6 I was under the impression that once you're in the "shutting down" state things are too late. You're already shutting down, and running tests will be killed by the node as it shuts down. In that case the tests will fail. This request is for an option to stop sending requests to a specified node. Once no more tests are running on that node we can enter the "shutting down" state.

IIRC when a new request comes in it goes through https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/ProxySet.java. I think asking for a way of removing a node from being compared in 
{code}
private Comparator<RemoteProxy> proxyComparator = new Comparator<RemoteProxy>() {
{code}

I'm not sure if simply removing it from the list of proxies would cause existing connections to fail.

**Comment by krmahadevan** [comment]
@barancev @shs96c - This seems like a valid request (ability to detach a node dynamically without affecting inflight sessions). Its kind of what a self healing grid would do. If such an API exists, the grid maintenance can be made seamless via observability wherein we detect a nodes' dwindling health via different parameters such as CPU load (or) memory load etc.,

Even though we can detect all these parameters, there's currently no way to instruct the hub in a proper way to detach a node (I mean out of the box).

If you are fine with this, I would like to take a jab at this and raise a pull request.

**Comment by timothyclarke** [comment]
A further point related to this (possibly beyond scope of the original request).
If I just shutdown a node the hub seems to become unresponsive for a while. A desirable outcome would allow the grid to be scaled up and down in a much more dynamic way.

**Comment by krmahadevan** [comment]
@timothyclarke - I believe the original ask here was to just for a mechanism to unhook a node and not route any more new sessions to it. But I guess that doesn't do a lot of good because only the grid's registry kind of knows as to when has the last session in the unhooked node run to completion. On the node side its now literally an orphan because the grid will not route any more sessions to it, and the end user (who is managing the grid) wouldn't know when to kill the node.

A much more holistic implementation would be to provide for the following:

1. Expose an end-point on the hub which when invoked would basically mark a node for maintenance and refrain from sending out any more new sessions to it.
2. Once the last in-flight test case has ended it would basically send an instruction to the node to shutdown by invoking 
http://node:port/selenium-server/driver/?cmd=shutDownSeleniumServer

But the question remains, should this be provided in the grid out of the box, or should we let end users basically build this customization into the grid (because the grid is customizable in every way) which is what @mach6 has called out as well.

That is where I was hoping I would get some pointers from @barancev and @shs96c to hear their inputs as well before moving further. If the decision is not to have this mechanism built into the grid out of the box, then I guess this issue should be closed with perhaps a sample implementation that shows how to do it from outside of the selenium grid.

**Comment by timothyclarke** [comment]
@krmahadevan If you go to http://grid:port/grid/console you can see if there are sessions to the node so while it's an orphan, an end user can use that to decide when to kill the node. As such the original request still stands. 
If this change removes the node from the url given above can you not see the sessions by going to the node directly ?
Either way I think unhooking the node is viable / desirable.

As a background to this. When I raised this one we were using a standard multiple servers, very stable grid size. where one would be the hub and multiple clients. I'm now using kubernetes and so have the ability to alter the grid size in a very dynamic way. 
Having better tooling to adjust the grid size, out of the box without the need for custom plugins would be very useful. One of the biggest pain points in both configurations have been at scale down. Currently, when a node is removed the hub takes a while to recover, it is typically quicker and less impacting to kill the hub and let the remaining nodes re-register when taking one or more nodes out of service

**Comment by krmahadevan** [comment]
@timothyclarke 

> If this change removes the node from the url given above can you not see the sessions by going to the node directly ?

That would be an implementation specific detail and can be taken care of by adding a flag that marks a node as `down for maintenance`.

> I'm now using kubernetes and so have the ability to alter the grid size in a very dynamic way.
Having better tooling to adjust the grid size, out of the box without the need for custom plugins would be very useful. One of the biggest pain points in both configurations have been at scale down. 

Yes I kind of figured out that part from the ask :)

**Comment by krmahadevan** [comment]
@timothyclarke - FYI, I have raised a pull request to address this ask.

**Comment by timothyclarke** [comment]
Thank you

**Comment by wjordan** [comment]
> One of the biggest pain points in both configurations have been at scale down. Currently, when a node is removed the hub takes a while to recover, it is typically quicker and less impacting to kill the hub and let the remaining nodes re-register when taking one or more nodes out of service

I faced this same issue, traced it down to a bug in the `nodeStatusCheckTimeout` option (it currently sets timeout in seconds, not msec as documented- see #7194), and found that it can be worked around by setting `-nodeStatusCheckTimeout 1` cli argument. Hope this helps.

**Comment by barancev** [comment]
@shs96c I think this feature is worth to be implemented in the new grid version.

**Comment by krmahadevan** [comment]
@barancev - Is there a scope for this to be considered worth merging if I were to work on raising a PR for this? Just thought I would get a confirmation before I spend time trying to add this as a PR.

**Comment by mmerrell** [comment]
Does your PR also include fixing the underlying issue (#7194)? Asking because I was considering looking into fixing that one. 
MM

**Comment by krmahadevan** [comment]
@mmerrell - No I was just thinking of reviving the functionality that I built as part of https://github.com/SeleniumHQ/selenium/pull/6220 and make it compliant to Grid 4.

**Comment by AutomatedTester** [comment]
PR in https://github.com/SeleniumHQ/selenium/pull/8442

**Comment by diemol** [comment]
Closed in PR #8699
