### ISSUE TITLE
Selenium and firefox version compatible 

### ISSUE THREAD

**Issue by naveenabt** [SeleniumHQ/selenium#2071]
HI,

I am using below version of Firefox and selenium.

Firefox: 45.0
selenium: selenium-server-standalone-2.48.0

is it selenium-server-standalone-2.48.0 compatible with Firefox: 45.0?

Thanks,

**Comment by naveenabt** [comment]
Thanks Lanken.

I am not getting that error. i am getting time out error.
Please check the [https://github.com/magento/mtf/issues/30](url) 

Thanks,

**Comment by rlloyd2001** [comment]
According to the change log, up to FireFox 41
https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG

**Comment by rlloyd2001** [comment]
i think this can be closed
