### ISSUE TITLE
FireFox WebDriver does not accept javascript alert

### ISSUE THREAD

**Issue by AxelBeckert** [SeleniumHQ/selenium#2072]
## Meta -

OS:  OS: Mac OS X 10.11.4 x86_64

Selenium Version:  v2.53.0, with Core v2.53.0. Built from revision 35ae25b

Browser:  Firefox

Browser Version:  46.0.1

## Expected Behavior -

unexpectedAlertBehaviour: 'ignore'

Javascript alert pops up 
Using the text of alert and assert the text
accept alert
## Actual Behavior -

Javascript alert pops up 
closes immidiately 
throw [Facebook\WebDriver\Exception\UnexpectedAlertOpenException] 
## Steps to reproduce -

StartSession (using codeception)

$driver->executeJS('alert(\'text\')');

**Comment by sbos61** [comment]
I see the same behavior with 
Windows 10, 
FF 45.1.1 ESR, 
selenium-webdriver (2.53.0)
watir-webdriver (0.9.1)

What I actually see is that teh cancel button is pressed, no matter the option you select (ignore/ accept/ dismiss).
![http___localhost_testpages_testpages_test_modal html1465038860](https://cloud.githubusercontent.com/assets/1700298/15799257/849ca422-2a56-11e6-83c7-69a1cd33474e.png)

**Comment by barancev** [comment]
Selenium dismisses unexpected alerts by default, it's conscious design decision. Ignoring alerts by default can cause domino effect -- all commands will fail on an unexpected alert unless it's explicitly closed.
