### ISSUE TITLE
Edge webdriver not included in nuget packages?

### ISSUE THREAD

**Issue by DanielSundberg** [SeleniumHQ/selenium#2075]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.0
Browser:  
Edge
## Expected Behavior -
I would expect Webdriver for the Edge browser to be included in the nuget package? According to http://www.clemensreijnen.nl/post/2015/07/28/Run-your-Automated-UI-Tests-on-the-new-Microsoft-Edge-Browsere280a6-Windows10 Selenium itself is updated to support Edge?

Is it correct that Edge is not supported by in nuget packages or am I doing something wrong?

![2016-05-10 16_47_39-search](https://cloud.githubusercontent.com/assets/1454200/15150802/03ccea36-16cf-11e6-88d2-2e8e014607ed.png)

**Comment by ddavison** [comment]
with all due respect, please read the article 😃 

It clearly says

> Not in the Nuget Packages yet, so you have to build it yourself…

**Comment by jimevans** [comment]
I've just downloaded 2.53.0 using the NuGet Package Manager in a new solution, and `OpenQA.Selenium.Edge` is one of the namespaces available.

**Comment by DanielSundberg** [comment]
@jimevans, yes it seems like my project have pulled the webdriver reference from an old package. Will try to remove the reference and add a newer one.

**Comment by DanielSundberg** [comment]
Now it looks correct, closing.
