### ISSUE TITLE
Element is not clickable at point (x,y). Other element would receive the click...

### ISSUE THREAD

**Issue by TheDeveloperInTest** [SeleniumHQ/selenium#2077]
OS:  Windows 7 Pro
Selenium Version:  2.53.0
Browser:  Firefox 46.0.1
## Expected Behavior -

Should click the Checkbox
## Actual Behavior -

Getting an error message :
org.openqa.selenium.WebDriverException: Element is not clickable at point (x, y). Other element would receive the click: <label id=some label></label>
## Steps to reproduce -

I have an object that is a checkbox invoking pop up. 

CheckBox HTML:
<input id="id_agree_nyse" class="checkboxinput" type="checkbox" name="agree_nyse" checked="checked"/>
![image](https://cloud.githubusercontent.com/assets/19291215/15157616/6703541a-16ba-11e6-8e71-058d1931bcbd.png)

Pop-Up HTML:
<div id="modal__nyse" class="modal fade in" role="dialog" tabindex="-1" style="display: block;">

Inside this pop up I have numerous radio buttons, and some checkboxes that I invoke action upon using mydriver.
![image](https://cloud.githubusercontent.com/assets/19291215/15157652/8f6efa80-16ba-11e6-967f-1078f221ee57.png)

Once I am done with all actions inside the pop-up, I click a button to close the popup: 
<button id="modal__nyse--agree" class="btn btn-primary" type="button">Agree</button>

In my next step, I try to click another  similar checkbox on the same page as the previous checkbox.

Code to click checkbox: 
mydriver.findElement(By.xpath(".//*[@id='id_agree_opra']")).click();

However this is when I get the error "org.openqa.selenium.WebDriverException: Element is not clickable at point (x, y). Other element would receive the click: <label id=some label></label>

I have tried all of the suggestions from #1202 , but the issue remained, hence I am reaching out to the community.

Methods tried: JavaScript Executor, ExpectedConditions, Actions, Scroll

**Comment by bjhiltbrand** [comment]
We used to run into this all the time at work. We realized that, when leaving the pop-up (or any time there was a post on change to the webpage), there was a class attribute set on the DOM ("x-masked") if I remember right. We had to implement a wait that would wait until that attribute was no longer on the DOM before we continued test execution. I would check the DOM and watch for changes as you interact with the page. For us, the class attribute appeared at the bottom of the DOM as we clicked around. The big problem was that it only lasted 1 or 2 seconds, so it took us a bit to figure out what attribute it was adding that caused the "element not clickable" exception. Just a thought.

**Comment by bjhiltbrand** [comment]
Also, looking at your screenshots, it looks like you are dealing with a modal window. After closing the pop-up, can you implement a wait for that modal tag to no longer exist in the DOM before continuing?

**Comment by TheDeveloperInTest** [comment]
I managed to find a solution thanks to your advice. The modal tag still existed but with one less attribute. Hence I included the  wait order with the extra attribute. Once it no longer existed, wait order concluded, and the test moved on. 

Thanks a bunch, now I can finish building my auto suite.

**Comment by xirsoi** [comment]
I am experiencing this issue intermittently on [this page](http://69wns28k.50belowcommerce.com/2009-American-IronHorse-Bandera-111-cu-in-inventory.htm?ID=7421154&Brand=292&Type=1786&fm=1). If you click on the Value Your Trade button (right hand side) a modal dialog opens with a form.

My script fills out this form from top to bottom, entering data in all fields. 30-50% of runs will throw this error when trying to click on the element [id=receiveOffers]. Several times it has claimed that the parent <p> of the checkbox will be clicked instead.

I experience this exception very frequently, and 99% of the time it is a completely worthless exception that is being thrown on operations that once worked. I've had to create an extension method (JSClick(By)) to execute js that clicks on the element, which is less than ideal.

**Comment by shs96c** [comment]
How are you passing the CAPTCHA on that page?

**Comment by xirsoi** [comment]
I'm sorry, but I can't tell you that. It would undermine the captcha itself.

**Comment by barancev** [comment]
"Element is not clickable at point (x, y)" is a legit case, Selenium throws this exception when you attempt to cllick an element covered by some other element. You should avoid clicking overlapped elements.
