### ISSUE TITLE
Python: webdriver.firefox.logfile ignored?

### ISSUE THREAD

**Issue by d33tah** [SeleniumHQ/selenium#2078]
## Meta -
OS:  
Linux
Selenium Version:  
selenium==2.53.1 (according to `pip`)
Browser:  
Firefox
Browser Version:  
Mozilla Firefox 45.1.0

## Expected Behavior -

The following code put before the selenium test results in stderr being captured:

```
    profile = webdriver.FirefoxProfile()
    profile.set_preference("webdriver.firefox.logfile",
                           "/tmp/firefox_console")
    self.browser = webdriver.Firefox(profile)
```

## Actual Behavior -

`/tmp/firefox_console` doesn't even get run

## Steps to reproduce -

(skipped in hope that the bug report will be reproducible without them)

**Comment by lukeis** [comment]
the preference is "webdriver.log.file"  is the preference to set the browser to log to (which will log messages from the firefox driver code itself)

If you want to capture the stdout of the firefox process, then you'll want to set that on the FirefoxBinary object and pass it in.

"webdriver.firefox.logfile" is the system property name used by java (and the standalone server) to redirect the stdout of the firefox process.

**Comment by d33tah** [comment]
@lukeis: so basically, `webdriver.firefox.logfile` won't work on Python version?

**Comment by lukeis** [comment]
setting it as a firefox profile preference won't work anywhere (python or otherwise). I don't know what you intend to do, so I don't know how to advise on what the correct action for you is.

**Comment by d33tah** [comment]
@lukeis: Basically my Firefox instance crashes intermittently and I'd like to know why, so I'd like to be able to get a stdout log and print it when the crash is detected - as verbose as possible.

**Comment by lukeis** [comment]
Ok, then I would suggest doing both logs:

    profile = webdriver.FirefoxProfile()
    profile.set_preference("webdriver.log.file", "/tmp/firefox_console")
    binary = webdriver.FirefoxBinary(log_file=open("/tmp/firefox_output", "wb"))
    driver = webdriver.Firefox(profile, binary)

**Comment by elgalu** [comment]
We are trying to retrieve Firefox console logs from [Zalenium](https://github.com/zalando/zalenium) but it seems that `webdriver.log.file` is no longer available since geckodriver, do you know an alternative? Since Zalenium provides a grid we don't control how users set the Firefox profile so this setting, if it exists, should be able to be set in a similar way we are setting `webdriver.firefox.logfile` it while starting the Firefox nodes, i.e.:

```sh
-Dwebdriver.firefox.logfile="/var/log/firefox_driver.log"
```

Any ideas?
