### ISSUE TITLE
Problems with resolving hostname in Python webdriver

### ISSUE THREAD

**Issue by sankha93** [SeleniumHQ/selenium#2079]
Currently the Python Webdriver's Remote interface resolves the domain name to an IP and this is causing some issues with our users. Can the Python webdriver behaviour be made consistent with other drivers/browsers/curl, ie: request on a domain name rather than IP address.

The current `RemoteConnection` implementation already has `resolve_ip` parameter, that can be toggled to change the behaviour. This option isn't exposed on the Remote Webdriver API. Are there any drawbacks to making the HTTP request by hostname that I am missing?

If this change sounds feasible, I will be giving a PR to do it!

**Comment by lukeis** [comment]
you can pass in your own RemoteConnection with the resolve_ip set to false:

    driver = webdriver.Remote(RemoteConnection("http://host:port/wd/hub", resolve_ip=False), capabilities)

**Comment by sankha93** [comment]
@lukeis: What I meant was would it be possible to change the default behaviour of Remote Webdriver to have `resolve_ip=False`?

Or alternatively, a backward compatible way would be to include the `Host` HTTP header in the request as it is a part of the spec. This would prevent problems even if we do the request with the IP as we would have the Host header to fallback on.
