### ISSUE TITLE
Everything under //javascript/webdriver (except the atoms) needs to be deleted.

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#2080]
Hi, can you help me understand why the javascript tree has two versions of WebDriver source code?

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L259

https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/webdriver.js#L82

They seem very much the same functionality but ... different.

**Comment by lukeis** [comment]
issues aren't really a support or a question forum. This is more suited for discussion on irc (#selenium on freenode.net) or on the dev mailing list - https://groups.google.com/forum/#!forum/selenium-developers

of course I don't really know the answer... but likely @jleyba does :)

**Comment by jleyba** [comment]
Everything under //javascript/webdriver (except the atoms) needs to be deleted. I'll do it as soon as I remove references from //javascript/remote and //javascript/safari-driver. TBH this isn't a very high priority for me at the moment (I forgot it was still there)

**Comment by johnjbarton** [comment]
`selenium/javascript/webdriver/http/corsclient.js` seems only to live under `javascript/webdriver`

**Comment by johnjbarton** [comment]
I changed the title. Please reopen, thanks.
