### ISSUE TITLE
windows in IE

### ISSUE THREAD

**Issue by mkobylan** [SeleniumHQ/selenium#2081]
## Meta -

OS:  windows 7
Selenium Version:  2.53.0
Browser:  IE
Browser Version:  11.0.9600.18282 (64bit)
## Expected Behavior -

When opening new window through click on page the new window should be opened and switched to and manipulated (with findElement) or closed.
## Actual Behavior -

New window is opened but can't be correctly switched to and after a while it's not managed by selenium and can't be manipulated nor closed.
## Steps to reproduce -

setup simple project with selenium 2.53 library in path and start IE driver
java -jar selenium-server-standalone-2.53.0.jar -Dwebdriver.ie.driver=C:\IEDriverServer.exe

create file c:\x.html and c:\y.html as in attachment

start these 2 example tests from attachment file 

and see comments in test

full exception is also in attachment

attachment: [files.zip](https://github.com/SeleniumHQ/selenium/files/258765/files.zip)

I checked also other ways to create new window or tab (ctrl+N, ctrl+T) and I couldn't manipulate them anyway.

**Comment by Tarbej** [comment]
@mkobylan : Try for below solution:
Go to Internet Explorer -> Tools -> Internet Options -> Trusted sites -> Site -> Add the url of your site (URL which you are opening in browser in your automation).

After this, please re run your test case and let me know.

**Comment by JustinPhlegar** [comment]
@mkobylan Please remove INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS and ensure IE settings match what is stated in the Wiki [InternetExplorerDriver-Required Configuration](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration)

Usually, nothing is looked at until the INTRODUCE_FLAKINESS capability is removed and the scenario is retried. Though it is an option to use, you are indeed "Introducing Flakiness" into your scripts and IE. It should only be used as a final option in the case you do not have access to modify Protected Zone settings. You can read this blog for more info: http://jimevansmusic.blogspot.com/2012/08/youre-doing-it-wrong-protected-mode-and.html

**Comment by jimevans** [comment]
@mkobylan Also, please note that using the `file://` schema for URLs is unreliable in IE. IE places special sandbox restrictions on local file system resources, including execution of JavaScript (upon which the IE driver relies), and there's no guarantee that Protected Mode settings will resolve the issue. What happens when you host the HTML files on a web server (even one running locally, accessed through `http://localhost`) and browse them using the IE driver?

**Comment by mkobylan** [comment]
Thanks for the answers.
@Tarbej I work on virtual computer without access to change internet options.
@JustinPhlegar I have to use company library which creates driver for me. I will inform library owner but I doubt the setting is there for no reason.
@jimevans The file:// example is made specifically to simplify and demonstrate my problem without publishing any classified information. http://localhost is what I really use. I will try to get application URL from jenkins which will not be localhost.

**Comment by jimevans** [comment]
No reply in 10 months. Closing.
