### ISSUE TITLE
InvalidOperationException when clicking a button inside a frame that pops an alert

### ISSUE THREAD

**Issue by arnonax** [SeleniumHQ/selenium#2082]
## Meta -
OS:  Windows 8.1 Enterprise
Selenium Version:  2.21
Browser:  Google Chrome Version 50.0.2661.94 m

## Expected Behavior -
The call to Click should succeed

## Actual Behavior -
The call to Click fails with the following exception:
Test method SeleniumDemo.FramesDemoWithoutEssentials.TestMethod1 threw exception: 
System.InvalidOperationException: unknown error: cannot determine loading status
from unknown error: unhandled inspector error: {"code":-32000,"message":"Can not access given context."}
  (Session info: chrome=50.0.2661.94)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.3 x86_64)

## Steps to reproduce -
1. Create a page that contains an iframe with name="frame1"
2. Inside the iframe add a button with id="inner" and onclick="alert('bla')"
3. Create a test (using Selenium WebDriver of course) that navigates to the outer page
4. Swtich().ToFrame("name1")
5. var button = FindElement(By.Id("inner"))
6. button.Click()

[SeleniumBug.zip](https://github.com/SeleniumHQ/selenium/files/258880/SeleniumBug.zip)

See attached files

**Comment by lukeis** [comment]
For issues with chromedriver please log them with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
