### ISSUE TITLE
' > a' IS NOT WORK

### ISSUE THREAD

**Issue by gMan1990** [SeleniumHQ/selenium#2091]
## Meta -
OS:  OSX
Selenium Version:  2.53.0
Browser:  Chrome
Browser Version:  41 (64-bit) 

BUG: ' > a' IS NOT WORK
$('body > div.wrapper > div.container > div.content-wrapper > div > table > tbody > tr:nth-child(2) > td.first.nsb').find(' > a');

org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
*** Element info: {Using=css selector, value= > a}

**Comment by AutomatedTester** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided

**Comment by gMan1990** [comment]
the URL http://www.proxy4free.com/list/webproxy1.html

JAVA
List<WebElement> tds = driver.findElements(By.cssSelector("body > div.wrapper > div.container > div.content-wrapper > div > table > tbody > tr > td"));
for (int m = 0, n = tds.size(); m < n; m += 11) {
	String s = tds.get(m + 1).findElement(By.cssSelector(" > a")).getAttribute("href");
}

**Comment by p0deje** [comment]
`> a` is not a valid CSS selector. Child combinator (`>`) should always be prepended with parent, but it's missing in your case.

See [CSS selector spec](http://www.w3.org/TR/css3-selectors/#child-combinators) for reference.

**Comment by gMan1990** [comment]
but the js is right:
$('body > div.wrapper > div.container > div.content-wrapper > div > table > tbody > tr:nth-child(2) > td.first.nsb').find(' > a');

Element , Selenium how to find the child elements, not descendant elements???

**Comment by lukeis** [comment]
that is a jQuery / sizzle construct that enables that sort of selector.

In your case of wanting only the immediate children based on the context of another WebElement, I would recommend using xpath:

    element = driver.findElement(By.cssSelector("<your complex long one here>")
    element.findElement(By.xpath("./a"))

**Comment by lukeis** [comment]
btw... this sort of selector is extremely brittle and should be avoid, any change in the DOM structure all the way up to the body will make the selector invalid.

**Comment by jleyba** [comment]
XPath is not needed to find immediate children.

```java
WebElement parent = driver.findElement(By.cssSelector("div"));
WebElement child = parent.findElement(By.cssSelector("a"));
```

Behavior is just like `querySelector` in JS:

```js
var parent = document.querySelector('div');
var child = parent.querySelector('a');
```

**Comment by lukeis** [comment]
@jleyba i don't agree :) I didn't make an assumption about their dom... imagine:

    <div id="parent">
      <div class="child"><a href="dontgohere">no</a></div>
      <a href="iwantthis">yes</a>
    </div>

then the parent.findElement(By.cssSelector("a")) would return the first one, not the second, immediate child node.

**Comment by ddavison** [comment]
have you tried the construct using WebElement#findElement?

```java
WebElement element = driver.findElement(By.id("some_div"));
WebElement theA = theA.findElement(...)
```

**Comment by gMan1990** [comment]
I agree with @lukeis 
the parent how to find the iwantthis A? (not descendant elements)
parent.findElement(By.(???))
