### ISSUE TITLE
No Selenium Command to Verify Addition/Deletion of Table Rows

### ISSUE THREAD

**Issue by AlanRashid** [SeleniumHQ/selenium#2097]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.9.0
Browser:  
Firefox
Browser Version:  
43.0.3

## Steps to reproduce -
  The sensitivity of the data precludes including a compilable example.

The option list would look like the following:

<option value="001"> 9619  |  Key Field 01  |  VA  |  01/05/2001  </option>
<option value="001"> 9625  |  Key Field 02  |  MD  |  11/25/2009  </option>
<option value="001"> 9633  |  Key Field 03  |  DE  |  09/12/2012  </option>
<option value="001"> 9621  |  Key Field 04  |  DC  |  07/08/2010  </option>
<option value="001"> 9640  |  Key Field 05  |  VA  |  04/30/2006  </option>

Delete the row with "Key Field 03", label=regexp:[\\d\\D]*Key Field 03[\\d\\D]*
Verify that there is no "Key Field 03" row
Add a "Key Field 07" row
Verify that the table includes a "Key Field 07" row

**Comment by jleyba** [comment]
This would be an unnecessary expansion of the API. You can write your own helper function to analyze the DOM structure (e.g find the table, check number of rows, delete row, check row is no longer present)
