### ISSUE TITLE
Missing javadoc and sources artifacts from selenium-java

### ISSUE THREAD

**Issue by psufoxman** [SeleniumHQ/selenium#2098]
## Meta -
OS:  

Selenium Version:  
2.53
Browser:  

Browser Version:  

## Expected Behavior -
The selenium-java artifacts should include javadoc and sources
## Actual Behavior -
The selenium-java project does not include javadoc and sources
see http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.53.0/

**Comment by lukeis** [comment]
there is no javadoc/sources for that particular maven artifact because, well, there is no java sources in that artifact :)  Check any of the dependencies and they'll all have them.

For example:
http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-firefox-driver/2.53.0/
