### ISSUE TITLE
selenium grid hub can't clean unavailable node

### ISSUE THREAD

**Issue by fengkingcheng** [SeleniumHQ/selenium#2099]
If one node is down,I find the hub has the node in its console list all the time even the node has been offline for one day.I think console list should  clean unavailable node,but the node still display in console page.
maybe need to set some parameters while start the hub?

**Comment by mach6** [comment]
see `-cleanUpCycle`

**Comment by mach6** [comment]
closing this.. please comment back, if needed -- we can re-open it.
