### ISSUE TITLE
question on the firefox webdriver

### ISSUE THREAD

**Issue by wangzhih** [SeleniumHQ/selenium#2107]
OS:  
Windows 7
Selenium Version:  
 2.48.2
Browser:  
Firefox
Browser Version:  
41.0.2

I enalbed firebug/netexport add-ons when playback the selenium script to visit a web page, for instance, www.google.com. The entries in the HAR dump from the firebug alway does not contain the first initial GET request to http://www.google.com. This is not consistant to the HAR dump by open a firefox browser directly to visit the page.Why?

**Comment by jleyba** [comment]
Questions should be directed to the [selenium-users list](https://groups.google.com/forum/#!forum/selenium-users) or the \#selenium IRC channel.

This issue tracker is reserved for reporting bugs against the Selenium project.
