### ISSUE TITLE
Shall we get float from WebElement.getSize or WebElement.getLocation?

### ISSUE THREAD

**Issue by Handsome2734** [SeleniumHQ/selenium#2111]
Hi guys,
I wrote a test case, to check whether some elements in the page is correctly aligned, which means they're all at the same size & height as well as share the same gap width.
However, I found that WebElement.getLocation() will return a Point, which contains two **int** type. This may lead to a mis-calculate in the case, for the element's position in JS is presented in **float**.
So any chance we get a float version of WebElement.getLocation() and WebElement.getSize()?

**Comment by lukeis** [comment]
the spec seems a bit ambiguous, only referring to reference pixels.

https://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect

please log a bug with the w3c spec if you'd like to see this implemented in the future.
