### ISSUE TITLE
TypeKeys types wrong characters when trying to type "blöööööööööööööööä"

### ISSUE THREAD

**Issue by FrankBorland** [SeleniumHQ/selenium#2114]
## Meta
OS: Android 6.0
Selenium Version:  2.52.0
Appium version: 1.5.1

## Expected Behavior
The string "blöööööööööööööööä" should be typed into the text field.

## Actual Behavior
The string "bl&APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA9gD2AM-" is typed into the text field.

It doesn't seem to be an issue with character encoding, as strings like "blööööööööööööööö" and "blöä" or Japanese characters are typed correctly.

With "blöööööööööööööööä" however the string "bl&APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA9gD2AM-" is typed into the text field.
Variations of the string with two less ö or an Ä instead of ä at the end don't work either.
The problem only occurs with Android Apps. It works correctly for Android web pages/elements and on iOS (Apps and web elements).

After more testing I found out that it doesn't seem to matter if the last charactr is an ö or ä, but the number of characters is relevant. 
Working: blööööööööööööööö (uneven number of ö)
Not working: blöööööööööööööööö, blöööööööööööööö (both with an even number of ö)

## Steps to reproduce

WebDriver driver = new AndroidDriver<>(serverUrl, capabilities);
WebElement textField = driver.findElement(By.name("TextFieldName")); 
textField.sendKeys("blööööööööööööööö");  //Correct behaviour
textField.sendKeys("blöööööööööööööööö");  //Incorrect behaviour
textField.sendKeys("blöööööööööööööö");  //Incorrect behaviour

**Comment by lukeis** [comment]
Android Driver in this project has long since been deprecated, either you need to upgrade to Selendroid or Appium, or you are using one of those projects and the bug belongs one there. So, please log a new issue with them accordingly.
