### ISSUE TITLE
Utility to check element present or not

### ISSUE THREAD

**Issue by chandrasekhar4u** [SeleniumHQ/selenium#2115]
## Meta -
OS:  Any

Selenium Version: 2.53

Browser:  chrome

Browser Version:  50.0.2661.94 m

## Expected Behavior - 
It's better to have an utility method (inside selenium api) which will allow us to check particular web element is present or not. Please let me know if there is any api available already.

## Actual Behavior -
we need to get elements(instead of element) then we need to check the size of the elements, like below.
```
List<WebElement> elements=driver.findElements(By.className("myCSS"));
		if(elements.size()>=1){
			--do some operation
		}
```
## Steps to reproduce -
Get an element, and check whether it exists or not.

**Comment by ddavison** [comment]
we have the ExpectedConditions utility class to do just this.

**Comment by lukeis** [comment]
http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-waits

**Comment by chandrasekhar4u** [comment]
There is no handy API which will only check for particular element and give the flag(element present or not) instead of checking the size of the elements list?
could you please help to find if any such API...?

`ExpectedCondition<WebElement> elementz= ExpectedConditions.elementToBeClickable(By.className("backLink"));`

**Comment by chandrasekhar4u** [comment]
@lukeis Or @ddavison  any update on this?

**Comment by manoj9788** [comment]
@chandrasekhar4u did you try 
`WebDriver driver = new FirefoxDriver();
driver.get("http://somedomain/url_that_delays_loading");
WebElement myDynamicElement = (new WebDriverWait(driver, 10))
  .until(ExpectedConditions.presenceOfElementLocated(By.id("myDynamicElement")));`
