### ISSUE TITLE
Inconsistent definition of sessionId in webdriver.js

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#2116]
## Meta -
OS:  All

Selenium Version:  2.53

Browser:  All

Browser Version:  All

## Expected Behavior -
execute resolves parameters
## Actual Behavior -
fail in http POST because of a bad URL path:
/session/[object Object]/window/current/maximize
## Steps to reproduce -

```js
  var executor = Executors.createExecutor(selServer);
  var browser = webdriver.WebDriver.attachToSession(executor, selId);
  browser.manage().window().maximize().then(function() { ... never gets here
```
When we get to 

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/http/index.js#L462

The command for window().maximize() still contains a promise for a sessionId. That is a result of setting the sessionId in 
https://github.com/SeleniumHQ/selenium/blob/a368fca55fe5e8d202face6cd0f505bffc38d319/javascript/node/selenium-webdriver/lib/webdriver.js#L357
to `this.sessionId_` which is a promise:
https://github.com/SeleniumHQ/selenium/blob/a368fca55fe5e8d202face6cd0f505bffc38d319/javascript/node/selenium-webdriver/lib/webdriver.js#L270

**Comment by johnjbarton** [comment]
Actually this issue isn't what I thought ;-)

Compare:
https://github.com/SeleniumHQ/selenium/blame/master/javascript/node/selenium-webdriver/lib/webdriver.js#L295

where `sessionId` is a string argument to `attachToSession()` to 

https://github.com/SeleniumHQ/selenium/blame/master/javascript/node/selenium-webdriver/lib/webdriver.js#L357

where `sessionId` is a `Session` object (`this.sessionId`).

I don't understand how this code could work, so I must be missing something...

**Comment by jleyba** [comment]
`attachToSession()` [expects session ID to be a string](https://github.com/SeleniumHQ/selenium/blame/master/javascript/node/selenium-webdriver/lib/webdriver.js#L286), so it doesn't preprocess the command. This function should probably be deprecated as all it does is attempt to fetch the session's capabilities - something supported by the wire protocol but not in w3c.

`WebDriver#schedule()` always [preprocesses commands](https://github.com/SeleniumHQ/selenium/blame/master/javascript/node/selenium-webdriver/lib/webdriver.js#L372). This catches any embedded WebElements as well as the Session.

**Comment by johnjbarton** [comment]
Thanks, but the line I don't understand is before the preprocessing of parameters:
https://github.com/SeleniumHQ/selenium/blame/master/javascript/node/selenium-webdriver/lib/webdriver.js#L357
```js
command.setParameter('sessionId', this.session_);
```
Is `sessionId` a string -- I think it must be -- or a `Session` object like `this.session_`?

**Comment by johnjbarton** [comment]
Ok I think I see what is going on.

When `WebDriver#schedule()`  preprocesses commands, one path calls toJSON:
```js
  if (typeof value[Symbols.serialize] === 'function') {
    return toWireValue(value[Symbols.serialize]());
  } else if (typeof value.toJSON === 'function') {
    return toWireValue(value.toJSON());
  }
``
https://github.com/SeleniumHQ/selenium/blob/a368fca55fe5e8d202face6cd0f505bffc38d319/javascript/node/selenium-webdriver/lib/webdriver.js#L154

In Session.toJSON() we extract the string id:
```js
  toJSON() {
    return this.getId();
  }
```
https://github.com/SeleniumHQ/selenium/blob/a368fca55fe5e8d202face6cd0f505bffc38d319/javascript/node/selenium-webdriver/lib/session.js#L72

So the indirect effect of
```js
command.setParameter('sessionId', this.session_);
...
var prepCommand = toWireValue(command.getParameters());
```
is to convert the `Session` object to a string.
