### ISSUE TITLE
Why are these prefs still being set in Firefox

### ISSUE THREAD

**Issue by dylanb** [SeleniumHQ/selenium#2117]
Looking at the source code, I see here

https://github.com/SeleniumHQ/selenium/blob/f5b2ab52ca25b7b4e455de22fca60d3ee8844922/javascript/firefox-driver/webdriver.json#L43

these lines of code
```
    "security.warn_entering_secure": false,
    "security.warn_entering_secure.show_once": false,
    "security.warn_entering_weak": false,
    "security.warn_entering_weak.show_once": false,
    "security.warn_leaving_secure": false,
    "security.warn_leaving_secure.show_once": false,
    "security.warn_submit_insecure": false,
    "security.warn_viewing_mixed": false,
    "security.warn_viewing_mixed.show_once": false
```

These preferences seem to be causing some problems in a scenario that we have. I downloaded the Firefox source code and I cannot find these preferences anywhere in that source code. I think they should be removed.

**Comment by lukeis** [comment]
true, they're all gone now -

https://hg.mozilla.org/integration/mozilla-inbound/file/tip/browser/app/profile/firefox.js

relevant thread - https://support.mozilla.org/en-US/questions/976134

**Comment by dylanb** [comment]
Awesome!!!! Is there an estimate for a release that will include this?
