### ISSUE TITLE
Grid-Safari-Selenium is getting stuck on SafariDriver Launcher page[second Tab] by not closing it and NOT switching back to first Tab where actual URL opens

### ISSUE THREAD

**Issue by praveenashok** [SeleniumHQ/selenium#2119]
## Meta -
OS: OSX El capitan
Selenium Version: 2.53.0 
Browser: Safari
Browser Version: 9.1 
SafariDriver version: 2.48.0 which is latest as per SeleniumHQ site.
## Expected Behavior -
SafariDriver Launcher page/tab should get closed automatically and get switched to first tab where my URL is getting opened.
## Actual Behavior -
Selenium is getting stuck on SafariDriver Launcher page[Tab] by not closing it and switching back to first Tab

## Steps to reproduce -
Trying to execute n number of test cases from TestNG.xml, but few TCs are getting executed properly by closing SafariDriver Launcher page[tab].
But for few cases Selenium is getting stuck on SafariDriver Launcher page[Tab] by not closing it and switching back to first Tab where my URL will get opened.

## Required Solution -
I wanna first check how many tabs are currently opened by:-
if(browser.equals("safari")){
			capability=DesiredCapabilities.safari();
			capability.setBrowserName("safari");
			capability.setPlatform(Platform.MAC);
			capability.setVersion("9.1");
			capability.setJavascriptEnabled(true);
			driver=new RemoteWebDriver(new URL(grid_url),capability);
			driver.get(url);
			Thread.sleep(2000);
			String windowHandle = driver.getWindowHandle();
			ArrayList<String> tabs = new ArrayList<String> (driver.getWindowHandles());
			if(tabs.size()>0){

			<***Need a solution here to close second tab and switch to first tab***>
                        driver.switchTo().window(tabs.get(0));
			}
}

**Comment by praveenashok** [comment]
@lukeis are you there to help me with this?

**Comment by raghupokuri9035** [comment]
Even I'm facing the same issue. Some times safari instance open with application url in one tab along with default tab. 

Environment:
OS: OSX El capitan
Selenium Version: 2.53.0 
Browser: Safari
Browser Version: 9.1

**Comment by praveenashok** [comment]
Anybody have any solution for this ???
Please please look into this issue.

**Comment by jleyba** [comment]
The SafariDriver currently does not have a maintainer on the project. I would not expect anyone to look at this any time soon

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
