### ISSUE TITLE
Poor performance in Firefox on pages with constant Ajax requests (2.53.0; FF45)

### ISSUE THREAD

**Issue by rokkknrollla** [SeleniumHQ/selenium#2123]
## Meta -
OS:  
Grid 2.53.0 runs on Debian Linux; Nodes 2.53.0 on Windows Server 2003 SP2
Selenium Version:  
2.53.0 (tried 2.52.0 and 2.42.2 as well)
Browser:  
Firefox
Browser Version:  
45.1.1 and 38.0.0

## Expected Behavior -

Normal work as usual

## Actual Behavior -

With multiplay ajax requests running in background (15 to 20 per second) Firefox takes up a minute to perform a single action on element (findElement, click, sendKeys etc.) 
If we have multiple instances of Firefox experiencing this issue on one Grid (i.e. Grid + 4 Nodes + 2 Firefox instances on each node - 8 in total) it eventually leeds to complete shutdown of nodes and Grid Hub - all actions are stuck until we manually close browser windows

## Steps to reproduce -

Unfortunately, we do not have open public page. But I can mention services which causes all those background requests - due to an issue in test env Salesforce Live Agent started spamming background requests on client side pages which led to performance issues in Firefox running under Selenium (Google Chrome continues to work fine though)

![screen shot 2016-05-18 at 11 30 49](https://cloud.githubusercontent.com/assets/5063579/15354194/baf19f68-1cec-11e6-8a3c-75f37827d672.png)

**Comment by lukeis** [comment]
Sorry you're encountering a performance issue, but there's nothing the open source project can do without a way to reproduce (even intermittently) the issue you're hitting. Until a way to reproduce it is provided I have to close the issue.
