### ISSUE TITLE
Double click does not work on Firefox with selenium 2.53

### ISSUE THREAD

**Issue by kmcsekar** [SeleniumHQ/selenium#2128]
## Meta -

OS:  
Linux
Selenium Version:  
2.53
Browser:  
Firefox 
Browser Version:  
36.0.1
## Expected Behavior -

Double Click on SVG Element should work
## Actual Behavior -

Double click does not work on SVG element
It use to work on selenium 2.48
## Steps to reproduce -

Double click on SVG DOM.  
For example, double click on a node in following URL using selenium
http://mbostock.github.io/d3/talk/20111018/tree.html

**Comment by kmcsekar** [comment]
Can you please update me on the status of double click issue.
I could not double click on SVG DOM elements using selenium 2.53.
Am able to preform click at particular pixel location, but not double click.

**Comment by lefty1975** [comment]
I'm also experiencing this issue in Chrome, works fine for my in FF with 2.53.3. Chrome version = Version 51.0.2704.103 (64-bit)

**Comment by lefty1975** [comment]
@kmcsekar I was able to get your example working with capybara using:
page.find('text', text: 'analytics', match: :first).double_click in FF v.46.0.1

And I'm not very efficient in all the classes and methods for straight selenium-webdriver, but maybe this could work:
el = driver.find_element(:name, "analytics")
driver.action.double_click(el).perform

**Comment by barancev** [comment]
Retested again in Selenium 3.8 + geckodriver 0.19 + Firefox 59 (nightly) and Selenium 3.8 legacy mode + Firefox ESR 52, this sample works:
```
driver.navigate().to("http://mbostock.github.io/d3/talk/20111018/#15");
driver.switchTo().frame(driver.findElement(By.id("current")));
WebElement line = driver.findElement(By.cssSelector("svg"));
new Actions(driver).doubleClick(line).perform();
```

Feel free to reopen if the issue is still actual, and provide a reproduction scenario,
