### ISSUE TITLE
[REQUEST] Add support for setting request headers 

### ISSUE THREAD

**Issue by ch0wdan** [SeleniumHQ/selenium#2131]
**TL/DR: +1 on this if you support the ability to set request headers**
This is I know has been a huge debate among the community. This request is to bring the topic back up for discussion, to show support that this is a feature that is in need and should be prioritized for upcoming release. 

For one to actually set request headers we need to operate a proxy which then injects the headers for us. This is a very poor workaround as it is far more complex than it should be. 

We allow tests to add cookies, but yet we lack the ability to set headers on our requests.

**Comment by jleyba** [comment]
This can be accomplished using a proxy. Our position has been firm on this issue for several years now.

For full context, see SeleniumHQ/selenium-google-code-issue-archive#141

**Comment by jleyba** [comment]
Sorry for being rude, but I'm locking this thread to prevent others from piling on about an issue we won't budge on. Again see 141 for context.
