### ISSUE TITLE
Very slow loading of browser using phantomjs proxy

### ISSUE THREAD

**Issue by rebatov** [SeleniumHQ/selenium#2133]
## Meta -

OS:  Linux (Ubuntu 15.10)

Selenium Version:  

Browser:  phantomjs

Browser Version:  2.1.1

## Expected Behavior -

Loading of page early 
## Actual Behavior -

Doesn't load and if it loads takes around 5 minutes
And my code is:

 for (var i = 0; i < array.length; i++) {
        var webdriver = require('selenium-webdriver'),
            proxy = require('selenium-webdriver/proxy');
        var By = webdriver.By,
            until = webdriver.until;
        var driver = new webdriver.Builder()
            .withCapabilities(webdriver.Capabilities.phantomjs())
            .setProxy(proxy.manual({ http: array[i] }))
            .build();
        driver.manage().window().setSize(1920, 1080);
        driver.get('http://example.com/') 
       driver.wait(webdriver.until.elementLocated(webdriver.By.tagName('h1')), 9000);
        driver.findElement(webdriver.By.tagName('h1')).getInnerHtml().then(function(data){console.log(data);});

---- In array i have sent array of working proxies

**Comment by jleyba** [comment]
Have you enabled logging to get a better idea of what's going on? This would indicate if the slow down was in the webdriverjs client (a bug for us) or with phantomjs/your proxy

```javascript
webdriver.logging.installConsoleHandler();
webdriver.logging.getLogger('webdriver.http')
    .setLevel(webdriver.logging.Level.ALL);
```

See https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/logging.js#L28

**Comment by rebatov** [comment]
Yea I tried logging; no problem with the proxy, I checked using firefox; no issues but when I plugin in phantomjs in the driver code, unusual timing of output occurs.

**Comment by jleyba** [comment]
Is it possible to provide the log output? My tests show phantomjs is ignoring proxy settings.

I'm starting phantomjs with `--proxy-type=http --proxy=127.0.0.1:62367`

Here's my log output (notice the capabilities reported by phantomjs include the proxy):

```
[INFO  - 2016-05-24T03:39:31.100Z] GhostDriver - Main - running on port 59978
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] >>>
GET /status HTTP/1.1
accept: application/json; charset=utf-8

{}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 133
content-type: application/json;charset=UTF-8

{"sessionId":null,"status":0,"value":{"build":{"version":"1.2.0"},"os":{"name":"mac","version":"10.11 (El Capitan)","arch":"64bit"}}}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"phantomjs","proxy":{"proxyType":"manual","httpProxy":"127.0.0.1:62367"}}}
[INFO  - 2016-05-24T03:39:31.145Z] Session [1fdb7840-2161-11e6-8241-c105f113debe] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2016-05-24T03:39:31.145Z] Session [1fdb7840-2161-11e6-8241-c105f113debe] - page.customHeaders:  - {}
[INFO  - 2016-05-24T03:39:31.145Z] Session [1fdb7840-2161-11e6-8241-c105f113debe] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"manual","httpProxy":"127.0.0.1:62367"}}
[INFO  - 2016-05-24T03:39:31.145Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 1fdb7840-2161-11e6-8241-c105f113debe
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 575
content-type: application/json;charset=UTF-8

{"sessionId":"1fdb7840-2161-11e6-8241-c105f113debe","status":0,"value":{"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"manual","httpProxy":"127.0.0.1:62367"}}}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] >>>
POST /session/1fdb7840-2161-11e6-8241-c105f113debe/url HTTP/1.1
accept: application/json; charset=utf-8

{"url":"http://127.0.0.1:54989"}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 74
content-type: application/json;charset=UTF-8

{"sessionId":"1fdb7840-2161-11e6-8241-c105f113debe","status":0,"value":{}}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] >>>
GET /session/1fdb7840-2161-11e6-8241-c105f113debe/title HTTP/1.1
accept: application/json; charset=utf-8

{}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 79
content-type: application/json;charset=UTF-8

{"sessionId":"1fdb7840-2161-11e6-8241-c105f113debe","status":0,"value":"Hello"}
      1) can configure HTTP proxy host
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] >>>
DELETE /session/1fdb7840-2161-11e6-8241-c105f113debe HTTP/1.1
accept: application/json; charset=utf-8

{}
[2016-05-24T03:39:31Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 74
content-type: application/json;charset=UTF-8

{"sessionId":"1fdb7840-2161-11e6-8241-c105f113debe","status":0,"value":{}}
      - can bypass proxy for specific hosts
    pac proxy settings
      - can configure proxy through PAC file


  0 passing (686ms)
  2 pending
  1 failing

  1) [phantomjs] manual proxy settings can configure HTTP proxy host:

      AssertionError: 'Hello' === 'Proxy page'
      + expected - actual

      -Hello
      +Proxy page
      
      at javascript/node/selenium-webdriver/testing/assert.js:342:14
      at ManagedPromise.invokeCallback_ (javascript/node/selenium-webdriver/lib/promise.js:1379:14)
      at TaskQueue.execute_ (javascript/node/selenium-webdriver/lib/promise.js:2913:14)
      at TaskQueue.executeNext_ (javascript/node/selenium-webdriver/lib/promise.js:2896:21)
      at javascript/node/selenium-webdriver/lib/promise.js:2775:27
      at javascript/node/selenium-webdriver/lib/promise.js:639:7
  From: Task: [phantomjs] manual proxy settings can configure HTTP proxy host
      at Context.ret (javascript/node/selenium-webdriver/testing/index.js:137:10)
```

**Comment by rebatov** [comment]
**Here is my log output..**.


//log

{}
[2016-05-24T04:40:48Z] [FINER] [webdriver.http.Executor] >>>
GET /status HTTP/1.1
accept: application/json; charset=utf-8

{}
[2016-05-24T04:40:48Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 124
content-type: application/json;charset=UTF-8

{"sessionId":null,"status":0,"value":{"build":{"version":"1.2.0"},"os":{"name":"linux","version":"unknown","arch":"64bit"}}}
[2016-05-24T04:40:48Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"phantomjs","proxy":{"proxyType":"manual","httpProxy":"59.78.160.248:8080"}}}
[2016-05-24T04:40:48Z] [FINER] [webdriver.http.Executor] <<<
HTTP/1.1 200
cache: no-cache
content-length: 569
content-type: application/json;charset=UTF-8

{"sessionId":"af9b6be0-2169-11e6-9460-39e1addc9cf0","status":0,"value":{"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"manual","httpProxy":"59.78.160.248:8080"}}}
[2016-05-24T04:40:48Z] [FINER] [webdriver.http.Executor] >>>
POST /session/af9b6be0-2169-11e6-9460-39e1addc9cf0/url HTTP/1.1
accept: application/json; charset=utf-8

{"url":"http://www.google.com/ncr"}

**Comment by jleyba** [comment]
PhantomJS support has been removed from `selenium-webdriver`. You can now configure Chrome and Firefox to run in headless mode. The benefits of headless testing with a browser users acutally use.
