### ISSUE TITLE
contextClick not working on safari browser

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#2134]
OS:  Windows

Selenium Version:  2.52

Browser:  Safari

Browser Version:  5.1.7

## Actual Behavior - Getting org.openqa.selenium.WebDriverException: Unknown command: error

Details:

Error Cause : org.openqa.selenium.WebDriverException: Unknown command:
{"id":"q0m46jdszbl7","name":"mouseMoveTo","parameters":{"element":":wdc:1463465694082"}}
(WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'RapidValue-PC', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64',
os.version: '6.1', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=5.1.7,
cssSelectorsEnabled=true, platform=WINDOWS, secureSsl=true}]
Session ID: null

**Comment by jleyba** [comment]
See #1837
