### ISSUE TITLE
Canceled mousedown events causing blur

### ISSUE THREAD

**Issue by plynchnlm** [SeleniumHQ/selenium#2136]
## Meta -

OS:  
RedHat Enterprise Linux 6.8
Selenium Version:  
2.53
Browser:  
Firefox ESR
Browser Version:  
45.1.1
## Expected Behavior -

If a mousedown on another element is canceled, it should not cause the currently focused field to blur.
## Actual Behavior -

It does blur, in Firefox (but not Chrome).
## Steps to reproduce -
1. Create the following test script, which uses the JavaScript API.   Filename "wd_test.js":
   
   ```
   var assert = require('assert');
   var webdriver = require('selenium-webdriver'),
   By = webdriver.By,
   until = webdriver.until;
   
   var driver = new webdriver.Builder()
   .forBrowser('firefox')
   .build();
   
   driver.get('https://jsfiddle.net/vkdt0uu4/');
   driver.switchTo().frame(driver.findElement(By.css('iframe[name="result"]')));
   driver.findElement(By.id('testfield')).click();
   driver.switchTo().activeElement().getAttribute('id').then(function(elID) {
   assert.equal(elID, 'testfield');
   });
   driver.findElement(By.id('testbutton')).click();
   driver.switchTo().activeElement().getAttribute('id').then(function(elID) {
   assert.equal(elID, 'testfield');
   });
   driver.quit();
   ```
2. Start selenium server:  java -jar selenium-server-standalone-2.53.0.jar &
3. Run the above test script:  node ./wd_test.js

The test script opens a JSFiddle which displays an input field and a button.  There is a listener on the button that cancels mouse down events.  The test script focuses the field and then clicks on the button.  It tests to make sure the input field still has focus, but that test fails (for Firefox):

```
AssertionError: 'testbutton' == 'testfield'
    at /.../wd_test.js:18:10
```

I don't know if this is a bug with Selenium or with Firefox.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
