### ISSUE TITLE
HtmlUnitDriver PageLoadTimeOut not working

### ISSUE THREAD

**Issue by minhhoangvn** [SeleniumHQ/selenium#2146]
## Meta 
OS:  
Windows 10
Selenium Version:  
2.53.0
## Expected Behavior 
HtmlunitDriver should throw TimeOut exception when using driver.manage().timout().setPageLoadTimeOut()
## Actual Behavior 
Application will hang on all time
## Steps to reproduce 
This method i tried to use API pageloadtimeout but it not working:
HtmlUnitDriver driver = new HtmlUnitDriver();
driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.SECONDS);
driver.get(" http://us.24h.com.vn/");
I change to override directly to WebClient in com.gargoylesoftware.htmlunit.WebClient in code below but it still not working:
HtmlUnitDriver driver = new HtmlUnitDriver(){
        @Override
        protected WebClient getWebClient() {        	
            WebClient webClient = super.getWebClient();
            webClient.getCache().setMaxSize(0);
            webClient.getOptions().setUseInsecureSSL(true); //ignore ssl certificate
            webClient.getOptions().setThrowExceptionOnScriptError(false);
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.getOptions().setPrintContentOnFailingStatusCode(false);
            webClient.getOptions().setJavaScriptEnabled(false);           
            webClient.getOptions().setCssEnabled(false);
            webClient.setCssErrorHandler(new SilentCssErrorHandler()); 
            webClient.getOptions().setRedirectEnabled(true);	
            webClient.getOptions().setTimeout(10000);
            return webClient;
        }
    };
       	    driver.get(" http://us.24h.com.vn/");

**Comment by lukeis** [comment]
Can you please log this issue in the htmlunit-driver project instead:
https://github.com/SeleniumHQ/htmlunit-driver
