### ISSUE TITLE
IE WebDriver with enabled desired capability "Allow blocked content" opens local page with "Allow blocked content" prompt

### ISSUE THREAD

**Issue by Alfira** [SeleniumHQ/selenium#2148]
## Meta -
OS:  Windows 7

Selenium Version:  2.52.0

Browser:  Internet Explorer 11

Browser Version:  11.0.9600.18314CO

## Expected Behavior -
IE WebDriver opens local page without "Allow blocked content" prompt when desired capability "Allow blocked content" is enabled
## Actual Behavior -
IE WebDriver with enabled desired capability "Allow blocked content" opens local page with "Allow blocked content" prompt
## Steps to reproduce -
**Setup**: In the java code:
```
DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
capabilities.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);
capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
capabilities.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);
capabilities.setCapability("allow-blocked-content", true);
capabilities.setCapability("allowBlockedContent", true);
System.setProperty("webdriver.ie.driver", Log.gsAutomationAutoPath + "IEDriverServer.exe");
WebDriver driver = new InternetExplorerDriver(capabilities);
```

**Step**: Run simple test step checking any widget presence on the page.

**Result**:

1. IE browser is opened with 'Allow blocked content' prompt
![allowblockedcontentie11](https://cloud.githubusercontent.com/assets/19341020/15469641/41820ca6-20f4-11e6-8063-905662d1344a.PNG)

2. Exception in the code with message:

14:21:19 - 00:01:21.809 - FAIL - org.openqa.selenium.TimeoutException: Timed out after 10 seconds waiting for visibility of element located by By.xpath: //input[@name='firstname']
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'DD-3900783', ip: '10.60.216.87', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_71'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=false, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=true, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, proxy={proxyType=}, nativeEvents=false, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:4386/, javascriptEnabled=true, ignoreProtectedModeSettings=true, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 61670229-0edf-476f-baf3-cc4c2b233fdd

**Pay attention**: Capabilities doesn't have neither "allow-blocked-content" nor "allowBlockedContent". I don't know should they be.

**Comment by jimevans** [comment]
The IE driver does not now, nor has it ever supported a capability with either name. You would need to manually configure the browser to allow this behavior.

**Comment by shamras** [comment]
How do i manaully configue the browser my error i get is:  Unable to create new remote session. desired capabilities = Capabilities [{ensureCleanSession=true, nativeEvents=false, allowBlockedContent=true, allow-blocked-content=true, browserName=internet explorer, ignoreZoomSetting=true, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
