### ISSUE TITLE
selenium window().setSize beyond current resolution

### ISSUE THREAD

**Issue by biaggi** [SeleniumHQ/selenium#2150]
## Meta -
OS:  Ubuntu 16.04
Selenium Version:  2.53.0
Browser:  Chrome
Browser Version:  49.0.2623.110 (64-bit)

## Expected Behavior -
driver.manage().window().setSize(new Dimension(width, height));
This line should resize the browser to any dimension, but if you use a height beyond your pc resolution, it just maximizes the browser instead of using the desired size.

## Actual Behavior -
Now the browser just resize to your pc resolution

## Steps to reproduce -

package com.bbva.crawler.selenium;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.Point;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class App1 {
	public static WebDriver driver;
	public static String seed = "http://www.google.com";

	private final static int DEFAULT_WIDTH = 1280;
	private final static int DEFAULT_HEIGHT = 500;

	public static void main(String[] args) throws IOException {
		driver = new FirefoxDriver();
		driver.manage().window().setSize(new Dimension(DEFAULT_WIDTH, DEFAULT_HEIGHT));

		driver.get(seed);
		visit(seed);
		takeScreenShoot(url);

		driver.close();
		// let the gc kill this item
		driver = null;
	}

	public static void takeScreenShoot(String fileName) throws IOException {
		System.out.println("taking screenshoot");
		int newHeight = 3000;
		driver.manage().window().setSize(new Dimension(DEFAULT_WIDTH, newHeight));
		
		File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
		// Now you can do whatever you need to do with it, for example copy
		// somewhere
		fileName = fileName.replace("/", "-");
		fileName = fileName.replace(":", "");
		FileUtils.copyFile(scrFile, new File("/tmp/screenshoots/" + fileName + ".png"));
	}

}

**Comment by lukeis** [comment]
This is an OS / browser limitation. Selenium basically just uses the resizeTo API -
https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo

It's up to the browser vendor to implement that how they choose. If you'd like them to change that, I suggest logging a bug with the respective browser vendor, but I highly doubt they will change it.

With firefox in particular, we won't be attempting to fix this issue on the Selenium project's FirefoxDriver. You might have luck logging a bug against GeckoDriver (aka marionette) with Mozilla -
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver
https://github.com/mozilla/geckodriver/issues

**Comment by biaggi** [comment]
Thank you for your answer, @lukeis. resizeTo is also not doing what I expected and I also doubt that any browser developer is up to modify such function on time for my project, so I think I'll just try to zoom out or to create a xfvb with a lot of height ;-)
