### ISSUE TITLE
Element found several seconds after displayed in browser

### ISSUE THREAD

**Issue by petemyron** [SeleniumHQ/selenium#2155]
## Background:

I use selenium to test the quality of experience and performance of websites. On this particular page, there's an asset that I'm looking for that is useful to an end-user--the page may or may not be completely loaded. For some reason, selenium doesn't detect the css selector for several seconds after I can see it on the screen. I assume this is due to javascript bogarting the DOM or something similar.
## Meta -

OS: Windows (by test requirement...) Python 3.5.1 and Ruby 2.1.5p273, OSX 10.9.5 Python 2.7.11

Selenium Version:  2.53.2

Browser:  Firefox 46.0.1, Chrome 50.0.2661.102 m
## Expected Behavior -

The element ID should be found as soon as I can see it visually, or after some small interval (500ms, for example)
## Actual Behavior -

Several seconds pass between the element displayed visually and selenium identifying the element by ID
## Steps to reproduce -

[see gist here](https://gist.github.com/petemyron/bca964bac4a409c806fb6acbb44c8ec9)
- download and run this [gist](https://gist.github.com/petemyron/bca964bac4a409c806fb6acbb44c8ec9)
- enter your own credentials if you've got 'em!
  - Yes, this requires you to have a T-Mobile account... 

``` python
#!/usr/bin/python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def test_my_tmo_login():
    try: 
        driver = webdriver.Firefox()
        wait = WebDriverWait(driver, 15)

        driver.get("https://my.t-mobile.com/")

        elem = driver.find_element_by_id("username")
        elem.clear()
        elem.send_keys("1234567890\t")
        # time.sleep(2)

        elem = driver.find_element_by_id("password")
        elem.send_keys("password\n")

        elem = wait.until(EC.element_to_be_clickable((By.ID,'di_balDueAmount')))
        print("found")

    except Exception as e:
        print(str(e))

    finally:
        driver.quit()

if __name__=='__main__':
    test_my_tmo_login()
```

**Comment by jleyba** [comment]
The behavior you are seeing is probably the driver detecting network activity and waiting for that to settle before executing another command. Have you tried adjusting the page load strategy?

**Comment by payamazadi** [comment]
Looks like you're not submitting the form before looking for the balance amount due.. when I go to that page I see a basic login prompt. I manually enter a 10 digit string of digits and a 4 digit password, and the login button lights up. Your wait is probably just hitting some internal timeout and dying.

**Comment by petemyron** [comment]
Can you elaborate on what you mean by page load strategy? I've also tried disabling javascript on Chrome and Firefox with no success.

**Comment by petemyron** [comment]
@payamazadi adding the `\n` to the send_keys command bypasses or otherwise satisfies that check. We had some problems with that particular javascript and this is what I landed on and definitely works on the specific machines running the tests, but you can also set an explicit/implicit (I always forget which is which) to wait for a while to make sure.

BTW, thanks for your comments, folks!

**Comment by JustinPhlegar** [comment]
I believe he may be referencing the load strategy profile preference. Sorry, for the java syntax, don't know py

```java 
   DesiredCapabilities capabilities = DesiredCapabilities.firefox();
   FirefoxProfile firefoxProfile = new FirefoxProfile();
   firefoxProfile.setPreference("webdriver.load.strategy", "eager"); // Supported values are "normal", "eager" and "none"
   capabilities.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
   WebDriver driver = new FirefoxDriver(capabilities);
```

If this doesn't work, this seems like it is a better discussion for the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by cgoldberg** [comment]
> The element ID should be found as soon as I can see it visually

I don't think that assumption is correct.  Modern browsers don't necessarily block the critical rendering path while fetching resources, but webdriver's page load strategy blocks until after they are received.

so, consider this scenario that you may be observing:

* browser receives page content and the resources necessary to construct the DOM.
* first paint is rendered and you can visually see the element
* browser finishes fetching resources and fires an event when completed
* the event listener that webdriver is waiting on gets triggered and webdriver considers the page to be loaded.
* element selectors are now available to use



executed and you

**Comment by barancev** [comment]
Yes, WebDriver by default uses page load strategy that waits for fetching resources, this explains the delay.
