### ISSUE TITLE
UI Issuese on Linux and Firefox 46,

### ISSUE THREAD

**Issue by lokeshreddy1706** [SeleniumHQ/selenium#2157]
Hi All,

I'm facing UI changes on combination of  Linux and Firefox 46, we are facing some UI Issuses. I think all these is because of Firefox is deprecating  XUL or XPOM based addons.
Since Selenium IDE is XUL based addon, what is it's impact on a long run. Even though Firefox support these addons upto End of 2017, after that is it possible to build a addon like selenium IDE with the new avaliable API's??

Can you please share your comments and future of Selenium IDE.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
