### ISSUE TITLE
Unable to locate drop down element

### ISSUE THREAD

**Issue by chandra078272** [SeleniumHQ/selenium#2161]
## Meta -
OS:  Windows 7

Selenium Version: 2.53.0 

Browser: Chrome,IE,Firefox

Browser Version: Chrome Version 50.0.2661.102 m (64-bit), Firefox(38.2.0) ,IE 9.0.8112.16421 64 bit edition,

## Actual Behavior -step 1 and 2 is working fine. getting issue in Step 3 with below error :+1: 
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 26597
Only local connections are allowed.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"country"}
  (Session info: chrome=50.0.2661.102)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'LT-00006212', ip: '10.0.0.234', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=C:\Users\CRuhidas\AppData\Local\Temp\scoped_dir16984_21672}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=50.0.2661.102, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f77b20d7809273f2eff97c28256cecb0
*** Element info: {Using=id, value=country}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at formpf.test.LaunchMDBapplication.main(LaunchMDBapplication.java:25)

## Steps to reproduce -

Code :+1: 

package New.test;
import java.io.IOException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.*;

public class LaunchMDBapplication {

	public static void main(String[] args) throws InterruptedException, IOException {
		System.setProperty("webdriver.chrome.driver", "C:/Users/cruhidas/Downloads/Path_chromedriver_win32/chromedriver.exe");
		//System.setProperty("webdriver.ie.driver", "C:/IEDriverServer/IEDriverServer.exe");
		WebDriver driver = new ChromeDriver();
		//driver.quit();
		//driver =new ChromeDriver();
		//WebDriver driver =new InternetExplorerDriver();
		//WebDriver driver = new FirefoxDriver();
		Thread.sleep(4000);
		driver.get("http://jsfiddle.net/bdhacker/eRv2W/");
		Thread.sleep(4000);
		driver.findElement(By.id("country")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[@id='country']/option[14]")).click();
}
}

**Comment by manoj9788** [comment]
Please post these kind of question in the support channel like google groups or in irc.

**Comment by lukeis** [comment]
@chandra078272 you first have to switch to the frame, before the find of 'country':

    driver.switchTo().frame(driver.findElement(By.cssSelector("iframe[name='result']"));
