### ISSUE TITLE
WebDriver Actions class method contextClick works when nativeEvents capability is set to false and dragAndDrop works when nativeEvents capability is set to true for IE11

### ISSUE THREAD

**Issue by sameer-ss** [SeleniumHQ/selenium#2170]
## Meta -

OS:  
Windows 7
Selenium Version:  
2.53
Browser:  
IE
Browser Version:  
11.0.9600.18314
## Actual Behavior -

Looks Webdriver Actions class behaves differently depends on Desired Capability type InternetExplorerDriver.NATIVE_EVENTS. In my case, Method contextClick on a particular element works only if InternetExplorerDriver.NATIVE_EVENTS is set to  false and dragAndDrop works when InternetExplorerDriver.NATIVE_EVENTS is set to  true.

Tester needs to perform these actions in same scenario and I guess we can't dynamically toggle web driver capability for a single webdriver instance.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided, just an unfounded statement.
