### ISSUE TITLE
It's impossible to disable images in Firefox 

### ISSUE THREAD

**Issue by emaks** [SeleniumHQ/selenium#2171]
## Meta -

OS: Windows
Selenium Version:  2.53
Browser: Firefox
Browser Version:  46.0.1
## Steps to reproduce -

create driver instance using this capabilities 

```
DesiredCapabilities capabilities = new DesiredCapabilities();
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("permissions.default.image", 2);
capabilities.setCapability("firefox_profile", profile);
```

_Note_ if I use exist FF profile `FirefoxProfile  profile = new ProfilesIni().getProfile("existProfile")` images are disabled
## Expected Behavior -

Images are disabled in broswer
## Actual Behavior -

Images aren't disabled in broswer

**Comment by sujay88** [comment]
Issue is genuine. Able to reproduce it.

**Comment by emaks** [comment]
Are there any updates?

**Comment by oozzal** [comment]
👍 definitely an issue

**Comment by lukeis** [comment]
I would recommend attempting to use a proxy to filter out images rather than relying on this. Also since GeckoDriver is now default and will soon be the only means to automate the latest versions of Firefox, this is not likely to be fix.

**Comment by jquacinella** [comment]
@lukeis This is super easy to do in chrome. Why is this not able to be done via geckodriver?

**Comment by barancev** [comment]
```
FirefoxOptions options = new FirefoxOptions()
    .addPreference("permissions.default.image", 2);
driver = new FirefoxDriver(options);
```

Works well in Selenium 3.7.0, tested in Firefox 57 + geckodriver 0.19 and Firefox ESR 52 with legacy driver.
