### ISSUE TITLE
[SafariDriver] Parallel execution with TestNG safari driver not able to click certain elements sometimes

### ISSUE THREAD

**Issue by sethisandeepsethi** [SeleniumHQ/selenium#2172]
## Meta -
OS: OSX 

Selenium Version:  2.53

Browser:  Safari

Browser Version:  latest 64 bit

## Actual Behavior -
Parallel execution with TestNG safari driver not able to click certain elements sometimes.
Please note that parallel execution with chrome, firefox and IS is working fine in my framework but only with Safari click() command is sometime working sometimes not working in parallel execution. In sequenctial execution safai is working fine but this issue occurs only when i run it in multithreading environment. I have tested in Mac machine and Saucelabs also, both hasve same results.

## Steps to reproduce -

I am using TestNG and maven to execute tests in parallel. 
For parallelixation i am also using TestNG dataProvider with parallel = true

**Comment by jleyba** [comment]
The SafariDriver does not support concurrent sessions.
