### ISSUE TITLE
Flex - Load Flex-Pilot-x

### ISSUE THREAD

**Issue by fredoprobtp** [SeleniumHQ/selenium#2175]
## Meta -

OS: Win7  

Selenium Version:  

Browser: Firefox 

Browser Version: 2.27.0  

## Expected Behavior -

Load and activate Flex-pilot-X
## Actual Behavior -

No activae pluging
## Steps to reproduce -

O Selenium IDE, select in Option|Option men,  fill the field extension in adding flexpilotx.js with ";" separator

When i try to record sequence, i obtain an bug in selenium console
[info] Failure to activate flex movie: id=FLEX_APPLICATION

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
