### ISSUE TITLE
Selenium not throwing error when browser is not navigated to url or loading

### ISSUE THREAD

**Issue by YeRaghuRam** [SeleniumHQ/selenium#2180]
## Meta -
OS:  Windows 7 x64

Selenium Version:  2.49.0.0 

Browser:  Internet explorer 

Browser Version:  
 IE 11

## Steps to reproduce -
Refer IEdriver server logs 
[HA.TestExecute.Reporting.REP_CPM_7267.txt](https://github.com/SeleniumHQ/selenium/files/289206/HA.TestExecute.Reporting.REP_CPM_7267.txt)

Issue observed for about 3 - 4 hrs after that killed iexplorer.exe maually for selenium to throw an error

**Comment by im-zeeshan** [comment]
Issue also exists for ChromeDriver.

If the initial homepage's HTTP response is not received, Selenium does not timeout and waits indefinitely.

**Comment by YeRaghuRam** [comment]
Any solutions to set the timeout or retry until the http response come?

**Comment by sri85** [comment]
AFAIK selenium waits for `document.readystate()` to be reached before interacting with the page , if that state is not reached selenium waits for ever.
One possible solution could be (possibly a hack) set a timer for the page load , if the page does not automatically exit the tests.

**Comment by cgoldberg** [comment]
The timeout is handled in the individual language bindings.  which are you using?

**Comment by YeRaghuRam** [comment]
iam using java language bindings

**Comment by YeRaghuRam** [comment]
@sri85  can you let me know how can i set time for the page load?

**Comment by sri85** [comment]
@YeRaghuRam I am not that familiar with `java` , possibly what you need is a `HTTP` library using which you can make a request for a webpage and set timeout .

**Comment by sujay88** [comment]
@cgoldberg  I checked code of Java bindings, code does not have any time-out. Ultimately _HttpClient_ is getting called to load the URL.  I am stuck at how to check timeout after _httpclient.execute_() method  is called.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
