### ISSUE TITLE
Getting element text <Python>

### ISSUE THREAD

**Issue by remcowesterhoud** [SeleniumHQ/selenium#2183]
## Meta -
OS:
OSX
Selenium Version:
2.53.0
Browser:
Chrome
Browser Version:
Version 50.0.2661.102 (64-bit)

I've got a simple HTML strong tag with some text in it. However I am unable to extract the text from using WebElement.text.

```html
<a href="javascript:;" class="select-all">
    Select all 
    <strong>
        <span>203</span>
    </strong>
</a>
```

## Expected Behavior -
When I get the span element using:
```py
element = driver.find_element_by_css_selector("a[class='select-all'] > strong > span")
x = element.text
```
I expect x to be '203'
## Actual Behavior -
When I get the span element and text using:
```py
element = driver.find_element_by_css_selector("a[class='select-all'] > strong > span")
x = element.text
```
The value of x is ''

Note:
- WebElement.get_attribute('innerText') works
- WebElement.get_attribute('innerHTML') works
- WebElement.get_attribute('textContent') works

What is the command that get performed when calling WebElement.text?

**Comment by ddavison** [comment]
using the latest python bindings available (`2.53.2`) and using the same html you gave, and the same code you gave, i couldn't reproduce the issue.

```python
#!/usr/bin/env python

from selenium import webdriver

driver = webdriver.Firefox()
driver.get('http://codepen.io/ddavison/full/PzwmPY/')

driver.switch_to.frame('result')

element = driver.find_element_by_css_selector("a[class='select-all'] > strong > span")
x = element.text

print x

driver.quit()
```

the stdout has `203`

**Comment by remcowesterhoud** [comment]
@ddavison I just figured out what the problem is. The element isn't visible and apparently it is not possible to get the text of a hidden element.

**Comment by ddavison** [comment]
cool! glad you figured it out :)

**Comment by jasartp** [comment]
my_url = 'https://techolution.app.param.ai/jobs/'

uclient = ureq(my_url)
page_html = uclient.read()
uclient.close()


page_soup = soup(page_html,"html.parser")
driver = webdriver.Firefox()   
driver.get(my_url)
results  = driver.find_elements_by_xpath('//*[@id="joblist"]')
# loop over results
for result in results:
    print(result.text)

hear i got all the information in a list like the below 

Engineering
Big Data Intern
Internship · Hyderabad · 0 - 2 Years
7 days ago
Consulting
Senior Cloud Specialist
Full-time · Singapore · 5 - 10 Years
11 days ago
Information Technology
Cloud Native Developer
Full-time · Hyderabad · 2 - 5 Years
12 days ago

how i store the data according to the date of posting(Most old first) as a DataFrame in CSV.
