### ISSUE TITLE
Using selenium standalone server jar v2.48.0 & up fails to click buttons in firefox on ppc64le

### ISSUE THREAD

**Issue by vaibhavsood** [SeleniumHQ/selenium#2184]
## Meta -

OS:  Ubuntu 15.10, ppc64le

Selenium Version: 2.48 & up, selenium standalone server jar (from here: http://selenium-release.storage.googleapis.com/index.html)

Browser:  Firefox 

Browser Version:  39

## Expected Behavior -

The issue is with the selenium standalone server jar for versions 2.48.0 & up on ppc64le machines. HTML buttons do not get clicked in the spawned browser via the Firefox WebDriver API. 

Issue affects run of Kibana test cases on ppc64le (separate issue created there referencing this issue), Kibana uses intern test framework (https://github.com/theintern/intern)

Steps below are using a sample intern tutorial app https://github.com/theintern/intern-tutorial, the app has a submit button which is clicked through intern apis (which are ultimately wrappers over the selenium apis)
## Actual Behavior -

In step 8 below, using selenium-server-standalone-2.48.0.jar does not correctly click the submit button, using selenium-server-standalone-2.47.0.jar does. Below are the log snippets:

<<<2.48.0>>>

13:45:57.106 INFO - Done: [find child element: 15 [[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded], By.cssSelector: #loginForm input[type=submit]]
13:45:57.111 INFO - Executing: [click: 17 [[[[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded]] -> css selector: #loginForm input[type=submit]]])
13:45:57.174 INFO - Done: [click: 17 [[[[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded]] -> css selector: #loginForm input[type=submit]]]
13:46:07.193 INFO - Executing: [find child element: 15 [[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded], By.id: greeting])
13:46:07.209 INFO - Done: [find child element: 15 [[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded], By.id: greeting]
13:46:07.214 INFO - Executing: [get text: 18 [[[[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded]] -> id: greeting]])
13:46:07.225 INFO - Done: [get text: 18 [[[[FirefoxDriver: firefox on LINUX (a3c20537-6728-470e-8c70-abe7ca41b248)] -> css selector: body.loaded]] -> id: greeting]]
× firefox on any platform - index - greeting form (11.024s)
AssertionError: Greeting should be displayed when the form is submitted: expected 'Please enter your name' to equal 'Hello, Elaine!'
  at Assertion.assertEqual  <node_modules/intern/browser_modules/chai/chai.js:776:12>
  at Assertion.ctx.(anonymous function) [as equal]  <node_modules/intern/browser_modules/chai/chai.js:4192:25>
  at Function.assert.strictEqual  <node_modules/intern/browser_modules/chai/chai.js:2329:32>
  at Command.<anonymous>  <tests/functional/index.js:24:28>
  at runCallback  <node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:543:11>
  at <node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  timers.js:330:15
  at Command.then  <node_modules/leadfoot/Command.js:542:10>
  at Test.registerSuite.greeting form [as test]  <tests/functional/index.js:23:18>
  at start.then.finally.self.timeElapsed  <node_modules/intern/lib/Test.js:181:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  timers.js:330:15
No unit test coverage for firefox on any platform
firefox on any platform: 1/1 tests failed

13:46:07.303 INFO - Executing: [execute script: return (function getCoverageData(coverageVariable) {
        var coverageData = (function () { return this; })()[coverageVariable];
        return coverageData && JSON.stringify(coverageData);
    }).apply(this, arguments);, [__internCoverage]])
13:46:07.312 INFO - Done: [execute script: return (function getCoverageData(coverageVariable) {
        var coverageData = (function () { return this; })()[coverageVariable];
        return coverageData && JSON.stringify(coverageData);
    }).apply(this, arguments);, [__internCoverage]]
13:46:07.317 INFO - Executing: [delete session: 6a5d81f4-1346-4ac8-8b47-bcd721abfc09])
13:46:07.388 INFO - Done: [delete session: 6a5d81f4-1346-4ac8-8b47-bcd721abfc09]

-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 app/      |       50 |        0 |       50 |       50 |                |
  hello.js |       50 |        0 |       50 |       50 |           8,10 |
-----------|----------|----------|----------|----------|----------------|
All files  |       50 |        0 |       50 |       50 |                |
-----------|----------|----------|----------|----------|----------------|

TOTAL: tested 1 platforms, 1/1 tests failed

<<< 2.47.0 >>>
14:46:54.723 INFO - Done: [send keys: 16 [[[[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded]] -> id: nameField], [Elaine]]
14:46:54.729 INFO - Executing: [find child element: 15 [[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded], By.cssSelector: #loginForm input[type=submit]])
14:46:54.740 INFO - Done: [find child element: 15 [[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded], By.cssSelector: #loginForm input[type=submit]]
14:46:54.745 INFO - Executing: [click: 17 [[[[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded]] -> css selector: #loginForm input[type=submit]]])
14:46:54.829 INFO - Done: [click: 17 [[[[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded]] -> css selector: #loginForm input[type=submit]]]
14:47:04.848 INFO - Executing: [find child element: 15 [[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded], By.id: greeting])
14:47:04.865 INFO - Done: [find child element: 15 [[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded], By.id: greeting]
14:47:04.871 INFO - Executing: [get text: 18 [[[[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded]] -> id: greeting]])
14:47:04.883 INFO - Done: [get text: 18 [[[[FirefoxDriver: firefox on LINUX (0a8ab54a-5d08-49cc-b251-fcd417377f3d)] -> css selector: body.loaded]] -> id: greeting]]
✓ firefox on any platform - index - greeting form (10.887s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/1 tests failed

14:47:04.902 INFO - Executing: [execute script: return (function getCoverageData(coverageVariable) {
        var coverageData = (function () { return this; })()[coverageVariable];
        return coverageData && JSON.stringify(coverageData);
    }).apply(this, arguments);, [__internCoverage]])
14:47:04.915 INFO - Done: [execute script: return (function getCoverageData(coverageVariable) {
        var coverageData = (function () { return this; })()[coverageVariable];
        return coverageData && JSON.stringify(coverageData);
    }).apply(this, arguments);, [__internCoverage]]
14:47:04.921 INFO - Executing: [delete session: b707b2b5-d785-4645-be49-5cd073b814a5])
14:47:04.998 INFO - Done: [delete session: b707b2b5-d785-4645-be49-5cd073b814a5]

-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 app/      |      100 |       50 |      100 |      100 |                |
  hello.js |      100 |       50 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |       50 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|

TOTAL: tested 1 platforms, 0/1 tests failed
## Steps to reproduce -

Following are the steps to setup and run the sample tutorial intern app

1) git clone https://github.com/theintern/intern-tutorial
2) cd intern-tutorial
3) npm install --save-dev intern
4) mkdir tests
5) cp node_modules/intern/tests/example.intern.js tests/intern.js
6) Follow steps here to write a functional test: https://github.com/theintern/intern-tutorial#step-4-write-a-functional-test
7) Change the "tunnel" and "environments" options in tests/intern.js to use the local Selenium Server instead of BrowserStack, have the options as follows 
    tunnel: 'NullTunnel',
    environments: [
        { browserName: 'firefox' }
    ]
8) Start the selenium server: eg java -jar selenium-server-standalone-2.48.0.jar
9) Run the functional test: ./node_modules/.bin/intern-runner config=tests/intern

**Comment by vaibhavsood** [comment]
Hi, just wanted to post a gentle reminder, if could get some help with resolving this issue that would be great, thanks!

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
