### ISSUE TITLE
How to automate Chrome developer tools?

### ISSUE THREAD

**Issue by maninwindow** [SeleniumHQ/selenium#2186]
**What I want to do**
I want to open Chrome developer tools programmatically in Selenium for C#, navigate to the Console and execute certain commands.

**What I tried**
Related code I tried is below:

- This works for me to open Chrome developer tools.

`Action action = new Action(DriverFolder);`
`action.KeyDown(Keys.Control).KeyDown(Keys.Shift).SendKeys("i").Perform();`

- This piece of code suppose to work to navigate to the Console tab, but actually not.

`action.KeyDown(Keys.Control).SendKeys("]").Perform();`
`action.SendKeys("Console.log('Executes at Console!');");`

Have anyone tried similar approaches on similar issues?

**Thanks in advance!**

**Comment by lukeis** [comment]
You can't automate the dev console with chromedriver, it's a limitation of the architecture of chromedriver. 
https://sites.google.com/a/chromium.org/chromedriver/help/devtools-window-keeps-closing
