### ISSUE TITLE
MoveTargetOutOfBoundsException: Offset within element cannot be scrolled into view when scrolled for element

### ISSUE THREAD

**Issue by pradiipyadav** [SeleniumHQ/selenium#2187]
## Meta -
OS:  Windows 7 and MAC 10.10

Selenium Version: 2.52.0,  2.53.0

Browser:  Firefox only

Browser Version:  46.0.1 

## Actual Behavior - Getting error while scrolling to element
org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: Offset within element cannot be scrolled into view: (309, 752): [object HTMLDivElement]
Command duration or timeout: 16 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Pradeepy', ip: '192.168.10.0', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 596b1121-4c94-41ad-9679-1f755fe95322

## Steps to reproduce -

1. Open web application which has droppable elements. {Page has scroll bar visible}
2. Go to the top and select an element and scroll down and drop element to bottom.

I am using code;
WebElement DragElement = Driver.findElement(By.xpath("SomeXPATH"));

if(DragElement.isDisplayed){
	int	yPos = dropElement.getLocation().getY();

			((JavascriptExecutor)Driver).executeScript("window.scrollTo(0, "+yPos+");");
}
    		Actions builder = new Actions(Driver);
	      builder.moveToElement(DragElement,10, 10)
		.clickAndHold()
		.build()
		.perform();
		Thread.sleep(1000);
		
WebElement dropElement = Driver.findElement(By.xpath("SomeXPATH"));
if(dropElement.isDisplayed()){
	int yPos = dropElement.getLocation().getY();
((JavascriptExecutor)seleniumDriver).executeScript("window.scrollTo(0, "+yPos+");");
//Also used ((JavascriptExecutor) Driver).executeScript("arguments[0].scrollIntoView(true);", dropElement );

}		
	builder.moveToElement(dropElement,309,752)
		.release()
		.build()
		.perform();

Everything works fine on Chrome.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by eGavr** [comment]
@pradiipyadav 

Are you going to finish the description of this issue ?
