### ISSUE TITLE
IE WebDriver working too slow with 64 and just working in debug mode with 32 

### ISSUE THREAD

**Issue by jhenyffer** [SeleniumHQ/selenium#2192]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment]
The lack of detail here is not enough to go by... It is known that 64 bit IE driver is slower with respect to send_keys (and probably other items are known too). 32bit is recommended on the downloads page for this reason.

**Comment by jimevans** [comment]
For the technical reasons why this is so for IE 10 and IE 11, see [this blog post](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html).
