### ISSUE TITLE
NoSuchElementException calling PageFactory.InitElements when an element is not present on the page

### ISSUE THREAD

**Issue by sfauvel** [SeleniumHQ/selenium#2193]
## Meta -

OS:  Windows Server 2008 R2
Selenium Version:  2.53.0.0
Browser:  InternetExplorer
Browser Version:  8.0.7601.17514 (64-bit)
## Expected Behavior -

IWebElement, declared with FindsBy on page object, should not be loaded until they are used. The page object could be created and initialized even the driver is not on the page.`
## Actual Behavior -

When PageFactory.InitElements is called on a page object, if one of the IWebElement could not be found, a NoSuchElementException is thrown.
## Steps to reproduce -
- Create a simple PageObject class with one IWebElement not present on the page
- Call PageFactory.initElements
- A NoSuchElementException is thrown

```
public class MyPageObject
{
        [FindsBy(How = How.Id, Using = "somethingThatNotExist")]
        private IWebElement unknownElement;
}
class MyTest
{       
        [Test]
        public void initPageObjectTest()
        {
            IWebDriver driver = getDriver();           
            MyPageObject page = new MyPageObject();
            PageFactory.InitElements(driver, page); // An NoSuchElementException is thrown here
        }
        private static IWebDriver getDriver()
        {
            // Create your driver here
        }
}
```

I located the problem on the method PageFactory.InitElements when SetValue is called to set the field with the proxy. The method GetType is called on the WebElementProxy. Then the WebElementProxy.Invoke method is called. In the Invoke method, the Element is used, so the LocateElement method is called and the NoSuchElementException is thrown.

When I create myself the ReturnMessage when the method GetType is invoked and I return before the Element is used, that works. It's certainly not the fix it have to be done but it shows where the problem is. 

Here, the modifed code of WebElementProxy class

```
 public override IMessage Invoke(IMessage msg)
{
    IMethodCallMessage methodCallMessage = msg as IMethodCallMessage;
        // Specific treatment when GetType method is called
    if (methodCallMessage.MethodName == "GetType")
    {
        return new ReturnMessage(GetProxiedType(), null, 0, methodCallMessage.LogicalCallContext, methodCallMessage);
    }

    var element = this.Element;
    if (typeof(IWrapsElement).IsAssignableFrom((methodCallMessage.MethodBase as MethodInfo).DeclaringType))
    {
        return new ReturnMessage(element, null, 0, methodCallMessage.LogicalCallContext, methodCallMessage);
    }
    return WebDriverObjectProxy.InvokeMethod(methodCallMessage, element);
}
```

**Comment by jimevans** [comment]
This may be the proverbial straw that breaks the camel's back that causes me to deprecate and remove `PageFactory` support from the .NET bindings. Thank you for the issue report.

**Comment by sfauvel** [comment]
Thank you for the return. If you remove PageFactory, how should we instantiate the PageObject and populate all IWebElement ?

**Comment by Frannsoft** [comment]
Is this still an issue?  I've tested with Webdriver 3.1.0 using the above code snippet and no exception is thrown.

I realize it's been a while, but if there were/are plans to drop `PageFactory` support from the .NET bindings based on this I'd think it would be high priority.

**Comment by sfauvel** [comment]
I'am not working anymore on the project. I could not say if it still an issue.

**Comment by jimevans** [comment]
The .NET PageFactory has, indeed, been deprecated.
