### ISSUE TITLE
Selenium webdriver script using java is not executing on IE11

### ISSUE THREAD

**Issue by uddhavnaik** [SeleniumHQ/selenium#2194]
OS:  
Windows 7 
Selenium Version:  
WebDriver  
Browser:  
Internet Explorer
Browser Version:  
11.0.9 (64-bit)

Expected Behavior - IE should open and the script should run successfully

Actual Behavior - IE as well as the web application is opening but as soon as the script comes to '**driver.findElement()**' it throws this exception '**org.openqa.selenium.NoSuchElementException: Unable to find element with id == email (WARNING: The server did not provide any stacktrace information)**'

i have tried running the script using other locators such as xpath as well but with no luck. i also have the latest IEWebDriver installed.
The same script is running fine on Firefox and Chrome

**Comment by AutomatedTester** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided

**Comment by uddhavnaik** [comment]
This is the code i am trying to run

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class LoginFullFlow {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
	System.setProperty("webdriver.ie.driver", "E:\\Softwares\\IEDriverServer.exe");
	//System.setProperty("webdriver.chrome.driver", "E:\\Softwares\\chromedriver.exe");
	DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
	caps.setCapability("ignoreZoomSetting", true);
	caps.setCapability("nativeEvents",false);
	driver = new InternetExplorerDriver(caps);
	baseUrl = "http://google.com";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void testLoginFullFlow() throws Exception {
    driver.get(baseUrl + "/");
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.xpath("//*[@id='email']")).clear();
    driver.findElement(By.xpath("//*[@id='email']")).sendKeys("u.n@g.in");
    driver.findElement(By.id("pass")).clear();
    driver.findElement(By.id("pass")).sendKeys("uddhavnaik");
    driver.findElement(By.id("send2")).click();
    }

**Comment by JustinPhlegar** [comment]
This test case does not work because elements with the identifiers being used do not exist in the google login flow. Also, the xpath syntax is incorrect and you would get an invalid selector exception.

The below code works
```java
	driver.get(baseUrl + "/");
	driver.findElement(By.xpath("//a[text()='Sign in']")).click();
	driver.findElement(By.xpath("//input[@id='Email']")).clear();
	driver.findElement(By.xpath("//*[@id='Email']")).sendKeys("blah@blah.com");
	driver.findElement(By.id("next")).click();
	driver.findElement(By.id("Passwd")).clear();
	driver.findElement(By.id("Passwd")).sendKeys("uddhavnaik");
	driver.findElement(By.id("signIn")).click();
```

If the google code was just stand in code, could you provide the url/html being tested against and your test case for that url/html?
