### ISSUE TITLE
Selenium webdriver script using java is not executing on Edge

### ISSUE THREAD

**Issue by uddhavnaik** [SeleniumHQ/selenium#2195]
OS:  
Windows 10
Selenium Version:  
WebDriver
Browser:  
Edge
Browser Version:  
25+

Expected Behavior -
Edge should open and the script should run successfully

Actual Behavior - Edge is opening and closing immediately and throws this exception '**org.openqa.selenium.NoSuchElementException: (UnknownError: The server did not provide any stacktrace information)**'

i have tried running the script using other locators such as xpath as well but with no luck. i also have the latest Edge webdriver installed.
The same script is running fine on Firefox and Chrome

**Comment by AutomatedTester** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided
