### ISSUE TITLE
Misleading property name - Python

### ISSUE THREAD

**Issue by remcowesterhoud** [SeleniumHQ/selenium#2196]
In the Python WebElement class there is a property call [parent](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L419).
This property returns the WebDriver that was used to find this element. I feel this name is misleading as when I have an element and I call parent on it I'd expect it to return another element, wich is the parent of the element it was called on.

``` html
<div id='parent'>
    <div id='child'>
        <span>Text!</span>
    </div>
</div>
```

``` py
driver = webdriver.Chrome()
child_element = driver.find_element_by_id('child')
parent_element = driver.find_element_by_id('parent')
parent = child_element.parent
```

In this case the value of parent will be equal to driver.
My expectation would be that parent would be equal to parent_element

I'd create PR that adds a new property for getting the webelement parent but I can't decide on a proper name for it as parent is the only thing that makes sense to me.

**Comment by Mobrockers** [comment]
:+1:

**Comment by cgoldberg** [comment]
> I can't decide on a proper name for it
`parent_element` ?

**Comment by jleyba** [comment]
Wr have intentionally avoided adding DOM traversal APIs like parentNode etc. No such PRs will be accepted

**Comment by remcowesterhoud** [comment]
@jleyba May I ask what the reason for this decision is?

**Comment by andreastt** [comment]
@remcowesterhoud A DOM traversal API is something that can be implemented as an abstraction on top of WebDriver and thus considered out of scope. In my opinion it is something worthwhile to be worked on if you have the interest for it.

I can sympathise with the confusing naming for `parent` however.

**Comment by barancev** [comment]
Closing the issue, see the related PR #2338 for explanation.
