### ISSUE TITLE
Constantly jumps in 'log ' tab from the tab 'Reference 'постоянно  перепрыгивает на вкладку Reference из вкладки log 

### ISSUE THREAD

**Issue by selevo** [SeleniumHQ/selenium#2197]
Since some versions of Selenium IDE ...
When you double-click on comand Selenium IDE constantly jumps in 'Reference' tab from the tab 'log 
'
when switching back is listed in the beginning, rather than at the last step.
If it is at all so I can not understand for what purpose it is done?
It is not comfortable.
VIDEO:
https://vk.com/video?z=video70462960_456239038%2F649c5367168cd14748%2Fpl_updates

Начиная с какой-то версии Selenium IDE...
При двойном клике на команду происходит переход из вкладки log во вкладку Reference
при переходе обратно  листинг находится в самом начале ,а не  на последнем действии.
Если  это у всех так то я не могу понять с какой целью это сделано ?
Это неудобно.
Видео:
https://vk.com/video?z=video70462960_456239038%2F649c5367168cd14748%2Fpl_updates
Как это устранить
## Meta -

OS:  

Selenium Version:  

Browser:  

Browser Version:  
## Expected Behavior -

вкладка не долна перескакивать
## Actual Behavior -

перескакивает на вкладку Reference

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
