### ISSUE TITLE
Selenium continued perform on the element with click or move to action in IE browser

### ISSUE THREAD

**Issue by yisake** [SeleniumHQ/selenium#2199]
## Meta -
OS:  

Selenium Version:  2.53.1

Browser:  IE10/IE11/IE8

Browser Version:  

32bit

## Expected Behavior -
element.click() method should just perform once.

## Actual Behavior -
element.click() method perform continued. And I found the element was flashing on the IE browser.

I download the IEDriver from:
http://selenium-release.storage.googleapis.com/2.53/IEDriverServer_Win32_2.53.1.zip

## Steps to reproduce -

1.Just open a new IE browser instance.
from selenium import webdriver
a=webdriver.Ie()
a.get('http://www.xxx.com')

2.Perform a click method on a element
a.find_element_by_css_selector('[]').click()

**Comment by AutomatedTester** [comment]
Please can you give a working example? We have numerous click tests that are working at the moment.

**Comment by yisake** [comment]
@AutomatedTester Have you watch the IE browser all the time?

The element was focus and shining all the time if the element has css style with color.

**Comment by yisake** [comment]
@AutomatedTester Maybe you can see the move to(hover) action all the time.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
