### ISSUE TITLE
ie webdriver: change attribute order in a form tag

### ISSUE THREAD

**Issue by Alexhha** [SeleniumHQ/selenium#2200]
## Meta -
OS: Windows 7 SP1, EN x86_64
Selenium Version: 2.53.1.0
Browser: Internet Explorer
Browser Version: 11.0.9600.18314

## Expected Behavior -
I'm using codeception as a framework and my test is using seeInPageSource() function, which should found the text in the page source.

```seeInPageSource('<form action="check_user.php" name="f1"');```

## Actual Behavior -
The test is failed, because order of attributes has been changed from original ```action="check_user.php" name="f1" ``` to a new one ```name="f1" action="check_user.php"```

```
There was 1 failure:

---------
1) Failed to  *** check *** in localCept (tests/acceptance/localCept.php)

 Step  I see in page source "<form action="check_user.php" name="f1""
 Fail  Failed asserting that   /form.html
--> <html><head>
    <title>TEST</title>
</head>
<body>
<form name="f1" action="check_user.php" method="POST">
```

## Steps to reproduce -
simple html page, **form.html**
```
<html>
<head>
    <title>TEST</title>
</head>
<body>
<form action="check_user.php" name="f1" method="POST">
    <p>Enable: <input name='n_opt1' class='c_opt1' type='checkbox' id="id_1" /></p>
    <p>Option2: <input name='n_opt2' class='c_opt2' type='text' id="id_2" /></p>
    <p>Submit: <input name='n_opt3' class='c_opt3' type='submit' id="id_3" value="Submit" /></p>
</form>
</body>
</html>
```

codeception test, **localCept.php**
```
<?php
    $I = new AcceptanceTester($scenario);
    $I -> wantTo(' *** check ***');
    $I -> amOnUrl('http://localhost/form.html');
    $I -> fillField('#id_2', 'admin');
    $I -> seeInPageSource('<form action="check_user.php" name="f1"');
```

acceptance suite configuration, **acceptance.suite.yml**
```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver:
            capabilities:
                platform: XP
            browser: 'internet explorer'
            url: http://127.0.0.1/
            host: 192.168.88.176
            port: 4444
```

Run selenium server
```
> java.exe -jar selenium-server-standalone-2.53.0.jar -Dwebdriver.ie.driver=IEDriverServer.exe
13:41:25.895 INFO - Launching a standalone Selenium Server
Setting system property webdriver.ie.driver to IEDriverServer.exe
13:41:26.189 INFO - Java: Oracle Corporation 25.77-b03
13:41:26.189 INFO - OS: Windows 7 6.1 amd64
13:41:26.197 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
13:41:26.264 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:41:26.264 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:41:26.273 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
13:41:26.275 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
13:41:26.275 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
13:41:26.443 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
13:41:26.443 INFO - Selenium Server is up and running
13:41:32.970 INFO - Executing: [new session: Capabilities [{browserName=internet explorer, platform=XP}]])
13:41:33.058 INFO - Creating a new session for Capabilities [{browserName=internet explorer, platform=XP}]
Started InternetExplorerDriver server (32-bit)
2.53.1.0
```

Run the test
```
$ codecept run
```

The test works fine with chrome, firefox, phantomjs and htmluinit webdrivers.

**Comment by jleyba** [comment]
This is working as intended. Page source reflects the state of the DOM according to the _browser_. WebDriver does not adjust the source in any way.

**Comment by Alexhha** [comment]
But why only ie webdriver change the order? Any other drivers work correctly. And if I open the page in IE and view the source - the order is correct too.

**Comment by jimevans** [comment]
Because that's what [IHTMLElement::get_outerHTML](https://msdn.microsoft.com/en-us/library/aa752326%28v=vs.85%29.aspx) returns from the browser when called on the document element. The driver has no control over what it returns.

**Comment by Alexhha** [comment]
Could you clarify one thing. As I have understood at the moment I'm using the following chain

codeception -> Selenium -> iewebdriver -> internet explorer

So my question is - who could make the changes?

**Comment by jimevans** [comment]
As I said, internally, `IEDriverServer.exe` calls the `outerHTML` property on the document element in IE. The driver is simply reporting the output of that property. It's IE itself that makes the changes.
