### ISSUE TITLE
Browser timeout help documentation inconsistent with timeout behavior on Grid hub

### ISSUE THREAD

**Issue by alewang** [SeleniumHQ/selenium#2205]
OS:  Debian Linux
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version:  45.1.1

## Expected Behavior -

The browserTimeout value should either be treated as a value in terms of seconds or milliseconds, and this information should be documented clearly. Additionally, the behavior of Selenium Grid should use timeouts equivalent to the timeout value specified through browserTimeout.

## Actual Behavior -

The browserTimeout value is treated in terms of milliseconds in the TestSession class, as can be seen here: https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/java/server/src/org/openqa/grid/internal/TestSession.java#L196 This method constructs an HttpClient object by passing in the value of browserTimeout from the configuration object without converting the value to milliseconds. The getGridHttpClient() method subsequently uses that value to construct a SocketConfig object with the timeout set to "60", which the Apache Http library interprets as milliseconds. Thus, instead of waiting for 60 seconds to read a stream, the socket library will only wait for 60 milliseconds.

However, running `java -jar selenium-server-standalone -role hub -help` shows that the browserTimeout value is set in terms of seconds. This inconsistency between documentation and behavior has led to SocketTimeoutExceptions being thrown, causing tests that run over a network to fail unexpectedly.

## Steps to reproduce -
Here is my hub config file:

```
{
  "browserTimeout": 10
}
```

Here is my node config file:

```
{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 3,
      "version": "46",
      "platform": "MAC"
    }
  ],
  "configuration": {
    "maxSession": 1,
    "port": 6000,
    "register": true,
    "unregisterIfStillDownAfter": 10000,
    "hubPort": 4444,
    "hubHost": "127.0.0.1",
    "nodeStatusCheckTimeout": 10000,
    "downPollingLimit": 0
  }
}
```

Here is my Groovy script to demonstrate this error:
```
@Grab('org.seleniumhq.selenium:selenium-java:2.53.0')

import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

DesiredCapabilities caps = DesiredCapabilities.firefox();
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), caps);
driver.quit();
```

For the record, this is an excerpt of the output from running `java -jar selenium-server-standalone-2.53.0.jar -role hub -help` :

```
  -browserTimeout:
    The timeout in seconds a browser can hang
```

**Comment by lukeis** [comment]
So... here's a fun one. 'browserTimeout' is consumed in two places and one assumes seconds and the other assumes milliseconds!

The other place... 

https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/remote/server/SeleniumServer.java#L99-L101

which is read in DriverServlet.java and translates from seconds to milliseconds.
