### ISSUE TITLE
[SafariDriver] cleanSession=true desired capability is not working

### ISSUE THREAD

**Issue by tamarbuata** [SeleniumHQ/selenium#2208]
## Meta -
OS:  OSX 10.10.5

Selenium Version:  2.53.0

Browser:  Safari 

Browser Version: 9.0.3

## Expected Behavior -
Setting **cleanSession=true** clears the Safari browser cache and cookies, starting the test in a clean state (ie, without being logged in). 

## Actual Behavior -
The cleanSession property does not seem to have an effect. Browser cookies and cache remain.

## Steps to reproduce -
1. Set the cleanSession=true property for SafariDriver.
2. Run a test that requires you to login. Do not logout.
3. Rerun the test. Notice that you are still logged in. This is not a clean session. 

## Workaround - 
In the browser Preferences > General, set the 'Safari opens with' to 'A new private window'. This seems to resolve the issue. Why can't cleanSession=true be analogous to starting with a new private window or tab?

**Comment by 5hawnknight** [comment]
duplicate issue -- https://github.com/SeleniumHQ/selenium/issues/821
