### ISSUE TITLE
Selenium Version: 2.53.0 Browser:  Firefox-45 not compatible. Which version is compatible?

### ISSUE THREAD

**Issue by JMadhusri** [SeleniumHQ/selenium#2213]
## Meta -
OS:  - Windows 
Selenium Version:  2.53.0,
Browser:   Firefox 
Browser Version:  45(32bit)

## Actual Behavior -
When i try to launch firefox browser i am getting  below error
Could you please help me which firefox version is compatible for webdriver 2.53.0?

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ow you can chat about it on Skype by sharing the web page directly into your conversation using the Skype add-on.","creator":"Microsoft Corporation","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi","installDate":1452090606000,"updateDate":1452090606000,"applyBackgroundUpdates":1,"bootstrap":true,"size":326715,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"26.0","maxVersion":"30.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2}
1465123066728	addons.xpi	DEBUG	getModTime: Recursive scan of {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}
1465123066737	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1465123066744	addons.xpi	DEBUG	Calling bootstrap method install on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 8.0.0.9103
1465123066744	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1465123066756	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1465123066757	DeferredSave.extensions.json	DEBUG	Save changes
1465123066757	DeferredSave.extensions.json	DEBUG	Save changes
1465123066757	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"0CU4ISZdpKJh","location":"app-global","version":"42.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","installDate":1465122431257,"updateDate":1465122431257,"applyBackgroundUpdates":1,"skinnable":true,"size":24301,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"42.0","maxVersion":"42.0"}],"targetPlatforms":[]}
1465123066757	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1465123066759	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1465123066759	addons.xpi-utils	DEBUG	Updating add-on states
1465123066760	addons.xpi-utils	DEBUG	Writing add-ons list
1465123066763	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\extensions\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}.xpi
1465123066763	addons.xpi	DEBUG	Calling bootstrap method startup on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} version 8.0.0.9103
1465123066824	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1465123066825	addons.manager	DEBUG	Provider finished startup: XPIProvider
1465123066825	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1465123066825	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1465123066825	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1465123066826	addons.manager	DEBUG	Starting provider: GMPProvider
1465123066832	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1465123066833	addons.manager	DEBUG	Provider finished startup: GMPProvider
1465123066833	addons.manager	DEBUG	Starting provider: PluginProvider
1465123066833	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1465123066833	addons.manager	DEBUG	Provider finished startup: PluginProvider
1465123066833	addons.manager	DEBUG	Completed startup sequence

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.google.gmail.inbox.A.main(A.java:11)

**Comment by latysh** [comment]
+1

**Comment by TimvdLippe** [comment]
We are also encountering this problem for Firefox 47: https://travis-ci.org/Polymer/polymer/builds/136000685#L1310

**Comment by AutomatedTester** [comment]
@TimvdLippe the issue you have encountered in #2110

**Comment by AutomatedTester** [comment]
@JMadhusri are you sure you are using 2.53? The log above suggests it is an older version

**Comment by JMadhusri** [comment]
@AutomatedTester Yes i am using 2.53 version, see the attached screen shot for reference

![image](https://cloud.githubusercontent.com/assets/19759822/15897020/538b7f22-2db0-11e6-8de8-e96f0d77fb66.png)

**Comment by transoceanic2000** [comment]
Since upgrading to Firefox 47 I can no longer run tests on my Mac. I get a gatekeeper error that firefox-bin has not been signed and therefore isn't allowed to run. Selenium 2.53.0 installed and hasn't changed so suspect this might be a Firefox issue.

**Comment by davehunt** [comment]
@transoceanic2000 that's issue #2110

**Comment by kwoxer** [comment]
In https://github.com/SeleniumHQ/selenium/issues/2110 @AutomatedTester  has written: it is fixed by Mozilla. But that's wrong.

Today I upgraded Firefox to Version 47 and Selenium isn't working anymore. Before it worked.

So what I can do right now?

I just get the usual "Could not open Connection" you get when the versions of firefox and selenium are incompatible. Any idea?

**Comment by lukeis** [comment]
closing this issue in favor of tracking on #2110

**Comment by kwoxer** [comment]
Sorry but why closing an existing issue? I don't think without releasing a new Selenium Version there is nothing happening =/

**Comment by lukeis** [comment]
@kwoxer #2110 is still an open issue

**Comment by kwoxer** [comment]
Yes but it would make more sense to allow posting comments there. Maybe if someone has another idea. I don't know. Better close comments here instead of there you know :)

**Comment by schoolboy2** [comment]
firefox 46.0 is compatible with selenium-server-standalone-2.53.0
