### ISSUE TITLE
Backslashes get reduced to half

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#2215]
## Meta -

OS:  Windows
Selenium Version:   Selenium IDE 2.9.1 (and any since 31st Mar 2006)
Browser:  Firefox
Browser Version:  any
## Expected and Actual Behavior -

Enter a new command:

```
getEval | alert( '\\' )
```

If you type `alert( '\\' )` in 'Target' text box, then in read-only Target column it becomes `alert( '\' )`. Even worse, when running that command, it fails - because it executes the version with half amount of backslashes: `alert('\')`.

A backslash should stay a backslash. There is no need to escape them in HTML test cases.

This is not a theoretical problem. SeLite SelBlocks Global provides Selenium.download(). It accepts a filepath to store the download. Windows uses backslash, and then this problem kicks in.
## Steps to reproduce -

As above.

This is caused by encodeText() and decodeText in treeView.js. That was introduced at https://github.com/SeleniumHQ/selenium/commit/697e11e20a178e7a4685ec85bc8ac8406754eafd. The commit comment mentioned SIDE-36, but I can't find that jira issue online.

Is there any explanation why that was thought to be needed, and for what it was a fix/workaround? 

Was this for test cases exported to WebDriver - code Python, Java etc? If so, then would you refactor this to be be in the formatters (if at all), but not at for-all level, please.

**Comment by cgoldberg** [comment]
> Windows uses backslash, and then this problem kicks in.

possible workaround:  forward slashes are also valid path separators in WIndows

> (and any since 31st Mar 2006)

The commit you point to is 10 years old?  That doesn't sound right.

**Comment by peter-kehl** [comment]
This causes problems that are not Windows-specific. A user may want to escape characters passed to `getEval` (and similar commands in SeLite, such as `promise`).

That commit in 2016 was most likely imported from OpenQA/Googlecode SVN history. That commit introduced `decodeText()` and `encodeText()`. Later commits only slightly improved those functions. 

Is there any documentation on old jira SIDE-36, please?

**Comment by peter-kehl** [comment]
Dear Shinya @kasatani,

Thank you for Selenium IDE.

When Selenium IDE saves a test case, it replaces any two backslashes with one. When it opens a test case, it replaces \n with a new line, and any other backslash with two backslashes: https://github.com/SeleniumHQ/selenium/commit/697e11e20a178e7a4685ec85bc8ac8406754eafd#diff-9c7890d1bb929d9f0156c670856458dfR211.

Do you remember a reason for this? It's been ten years. However, you're the only one whom I could find. Would you shed a light, please.

**Comment by kasatani** [comment]
I cannot see the details of SIDE-36 either since the site is no longer online, but I think I made this change to allow editing the test case that contains newline characters. Maybe removing the following lines will fix the problem?

decodeText: text = text.replace(/\\\\/g, "\\");
encodeText: text = text.replace(/\\/g, "\\\\");

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
