### ISSUE TITLE
SafariDriver - Timed out awaiting response to command

### ISSUE THREAD

**Issue by ionpetrache** [SeleniumHQ/selenium#2220]
## Meta -
OS:  Mac OS X 10.11.3

Selenium Version:  
2.48.2

Browser:  
Safari

Browser Version:  
9.0.3

## Actual Behavior -
SafariDriver is failing with:

org.openqa.selenium.TimeoutException: Timed out awaiting response to command "findElement" after 30005 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.12 seconds

## Steps to reproduce -
The problem is that I don't have concrete steps to reproduce as this failure is intermittent. Roughly speaking if I run a suite of 20 tests, 2 - 3 test will fail with this TimeoutException.

The command that is actually failing is not only findElement. I got also the same error for clickElement.

**Below the stack trace of the error:**
Caused by: org.openqa.selenium.TimeoutException: Timed out awaiting response to command "clickElement" after 30007 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.01 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'macos02.servers.qanet.ecircle.de', ip: '10.40.0.155', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: '52cd9da1f321', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.5.0-coreos-r1', java.version: '1.8.0_72'
Driver info: driver.version: RemoteWebDriver
sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:334)
com.sun.proxy.$Proxy2.click(Unknown Source)
org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:347)
sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
com.sun.proxy.$Proxy3.click(Unknown Source)
org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:30)
org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:1)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**The second stack**

Caused by: org.openqa.selenium.TimeoutException: Timed out awaiting response to command "findElement" after 30005 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.12 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'macos02.servers.qanet.ecircle.de', ip: '10.40.0.155', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
*** Element info: {Using=name, value=srch_name}
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: '52cd9da1f321', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.5.0-coreos-r1', java.version: '1.8.0_72'
Driver info: driver.version: EventFiringWebDriver
sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:451)
org.openqa.selenium.By$ByName.findElement(By.java:303)
org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
com.sun.proxy.$Proxy1.findElement(Unknown Source)
org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by 5hawnknight** [comment]
can you provide a code that generates the error and the url of the site?

**Comment by ionpetrache** [comment]
I cannot give you the url as it is an internal application.

A snippet of the code that throws this exception is:

```
		new WebDriverWait(driver, 60).ignoring(NoSuchElementException.class)
				.pollingEvery(5, TimeUnit.SECONDS)
				.until(ExpectedConditions.visibilityOf(cmbBxSelectGroup));
```

It fails in the visibilityOf method.

**The stack:**



org.openqa.selenium.TimeoutException: Timed out awaiting response to command "findElement" after 30003 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.21 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'macos02.servers.qanet.ecircle.de', ip: '10.40.0.155', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
*** Element info: {Using=id, value=ec-gid-selection}
Command duration or timeout: 30.84 seconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: '52cd9da1f321', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.5.0-coreos-r1', java.version: '1.8.0_72'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{webdriver.remote.sessionid=dd1e6e25-3d03-4e50-a087-15bb5bda5c44, browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.0.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: dd1e6e25-3d03-4e50-a087-15bb5bda5c44
*** Element info: {Using=id, value=ec-gid-selection}
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)
org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:403)
org.openqa.selenium.By$ById.findElement(By.java:218)
org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:345)
sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:102)
com.sun.proxy.$Proxy9.findElement(Unknown Source)
org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
com.sun.proxy.$Proxy11.isDisplayed(Unknown Source)
org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:302)
org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:41)
org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:288)
org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:285)
org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
com.teradata.dmcauto.modules.SelectGroup.selectGroup(SelectGroup.java:71)
com.teradata.dmcauto.modules.SelectGroup.selectGroup(SelectGroup.java:65)
com.teradata.dmcauto.po.messages.outbox.PrepareSendout.selectGroup(PrepareSendout.java:98)
com.teradata.dmcauto.basic.EditSystemMessage.editSystemMessage(EditSystemMessage.java:43)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.
