### ISSUE TITLE
Webdriver can't click on Element which gets hidden beneath floating header after scroll.

### ISSUE THREAD

**Issue by rupam87** [SeleniumHQ/selenium#2225]
OS:  Windows 7
Selenium Version:  2.53 c# bindings using NUnit tests
Browser:  Firefox 46, IE 11

## Actual Behavior -  Webdriver.FindElement call scrolls to the element which hides beneath a floating header. Thus click call fails. I tried using Selenium Actions and also SendKeys but to no avail.
Below is the exception throws and attached is the solution with test cases to reproduce.

POC1.Tests.testLearnMore("firefox"):
System.InvalidOperationException : Element is not clickable at point (791.2000122070312, 32.26666259765625). Other element would receive the click: <a href="https://saucelabs.com/resources"></a>
Command duration or timeout: 73 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'CHAKRRUP7', ip: '192.168.0.2', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c8f83ba5-1346-447c-85dd-8acf0f37da79

[POC1.zip](https://github.com/SeleniumHQ/selenium/files/301904/POC1.zip)

**Comment by cgoldberg** [comment]
> Please refer to attached code

don't just zip your entire project and expect someone to go through it for you.  This isn't helpful to anyone.  You need to provide precise steps to reproduce, and only relevant code snippets.

**Comment by rupam87** [comment]
Here are the Steps to repro issues, let me know if more info is needed : 
1. download and install - Selenium 2.53 C# bindings, Nunit dlls, VS2015, IEdriverserver and Chrome driver
2. Run the below Test on the grid using Remote Webdriver instance - 
[Test, Sequential]
        public void testLearnMore([ValueSource("browsers")] string browserName)
        {
            try
            {
                TestSetup.initializeWebDriver(browserName, out webDriver);
                NavigateAndWaitForElementToAppear("https://saucelabs.com/", SaucePage.LearnMoreButton);
                safeClick(SaucePage.LearnMoreButton);
                WaitForElementToAppearAfterNavigation("https://saucelabs.com/features", SaucePage.AutomatedCrossBrowserButton);
            }
            finally
            {
                tearDown(webDriver);
            }
        }

3. Here's the Safeclick method implementation - 
   public void safeClick(By selector)
        {            
            Assert.IsNotNull(selector,"element with null css selector is not clickable.");
            
            WebDriverWait wait = new WebDriverWait(webDriver, new TimeSpan(0, 0, 5));
            IWebElement element = wait.Until(ExpectedConditions.ElementToBeClickable(selector));

            try
            { element.Click();   }
            catch (StaleElementReferenceException)
            {
                Assert.Fail("The webelement is not displayed or enabled");
            }
            catch (ElementNotVisibleException)
            {
                Assert.Fail("The webelement is not visible.");
            }            
        }

The issue is : The click on Learn More button happens fine on Chrome only. For IE and Firefox the button element gets hidden beneath the floating header due to the scrolling.

I have tried using Ijavascriptexecutor script and Selenium Actions MoveToElement ... but it did not work, rather using these, the test case fails on Chrome as well.

**Comment by lmtierney** [comment]
WebDriver uses scrollIntoView() to move the object into the _visible area of the browser_. Since scrollIntoView defaults to aligning the top of the object to the top of the window, Sauce's floating header happens to be over top of it.

Your best bet would be to move the button into view before calling the click() (staying away from clicking with javascript, which does work). Using `scrollIntoView(false)` puts the element at the bottom of the visible area and would allow you to then click using WebDriver.

Regardless, this is not an issue with WebDriver.

**Comment by rupam87** [comment]
Thanks , scrollintoview(false) did the trick!
