### ISSUE TITLE
Html unit driver is not working as expected.

### ISSUE THREAD

**Issue by SunilDangayach** [SeleniumHQ/selenium#2229]
Meta -
OS:   Widows 7

Selenium Version:  -selenium-java-2.52.0 

Browser:  anything

Browser Version:  
Headless browser

## Expected Behavior -
It should run
## Actual Behavior -
Getting this exception- 
I checked by seeing page source, its not loading next page at all.

``

- `

> org.openqa.selenium.NoSuchElementException: Returned node was not a DOM element
> For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
> Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'
> System info: host: 'IBM207-PC09G4SD', ip: '9.195.87.191', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
> Driver info: driver.version: HtmlUnitDriver
```

## Steps to reproduce -

`
```
driver = new HtmlUnitDriver();

driver.get("https://www.*********.com/home.html?product=testCard");

String strPageTitle = driver.getTitle();
System.out.println("Page title: - "+strPageTitle);

WebElement nameInputField = driver.findElement(By.id("card"));  
nameInputField.sendKeys("*************");

 driver.findElement(By.id("go")).click();

try{
        //WebDriverWait wait = new WebDriverWait(driver, 40);
        //WebElement tableElement = wait.until(ExpectedConditions.elementToBeClickable(By.className("reportTable")));
        WebElement tableElement = driver.findElement(By.className("reportTable"));
        System.out.println("taleElemen"+tableElement);
        java.util.List<WebElement> rows = tableElement.findElements(By.tagName("tr"));
        for (WebElement row : rows) {
            java.util.List<WebElement> cols = row.findElements(By.tagName("td"));
            for (WebElement col : cols) {
                testData.put(col.getText().split(":")[0],col.getText().split(":")[1]);
            }       
        }

        WebElement avlBalance = driver.findElement(By.xpath("//td[.='Card Balance']/../td[last()]"));
        testData.put("Available Gift Card Balance",avlBalance.getText());
        //lstSting.add(avlBalance.getText());
    }catch(Exception e){
        System.out.println(e);
    }`
```

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
