### ISSUE TITLE
Selenium  gives NoSuchDriverError when the tests  run more than 30 min

### ISSUE THREAD

**Issue by graman71** [SeleniumHQ/selenium#2230]
## Meta -
OS:  Linux 3.13

Selenium Version:  selenium-server-standalone-2.47.0.jar

Browser:  chromedriver=2.16.333243

Browser Version:  chromedriver=2.16.333243

## Expected Behavior -
Test should  run without  throwing this  exception
## Actual Behavior -
throws  exception
## Steps to reproduce -
It's hard to  explain. When the  tests run through jenkins it  throws the  exception as  follows and  failed all  tests.

Selenium::WebDriver::Error::NoSuchDriverError:         Selenium::WebDriver::Error::NoSuchDriverError: no such session
          (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Linux 3.13.0-43-generic x86_64)
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:232:in `setWindowSize'
            /var/lib/jenkins/.bundler/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/window.rb:78:in `resize_to'

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
