### ISSUE TITLE
[Node.js] webdriver.get not open browser window with promise.then

### ISSUE THREAD

**Issue by zixia** [SeleniumHQ/selenium#2233]
## Meta - driver.get not open the browser window

OS:  linux & win32

Selenium Version:  2.53.2

Browser:  chrome

Browser Version: 50.0.2661.102 m 

## Expected Behavior -

use the following javascript code to open browser window

``` javascript
const WebDriver     = require('selenium-webdriver')

var driver = new WebDriver.Builder()
.setAlertBehavior('ignore')
.forBrowser('chrome')
.build()

function bug() {
  console.log('bug: `driver.get` will hang\n' + '\n' + bug + '\n')
  Promise.resolve()
  .then(() => 'test')
  .then(() => driver.get('about:blank'))
}

bug()
```
## Actual Behavior -

after run, there's no window opened by webdriver. the program hang. 

I run this code under nodejs v6.0.0
## Steps to reproduce -

I had experienced a very strange bug with nodejs & selenium-webdriver recently. It looks related with nodejs event loop / promise / selenium-webdriver.

In short: **webdriver.get call will hang when use with some promise.then.**
### First, let's see a piece of javascript code which works well:

``` javascript
const WebDriver     = require('selenium-webdriver')

var driver = new WebDriver.Builder()
.setAlertBehavior('ignore')
.forBrowser('chrome')
.build()

function ok() {
  console.log('ok: driver.get will open a browser window\n' + '\n' + ok + '\n')
  driver.get('about:blank')
}

ok()
```

This code will open a browser window, which works as expected.

But all of the following code will show strange behaviour.
### Bug - driver.get will hang

after add a dummy .then(() => 'test')

``` javascript
function bug() {
  console.log('bug: `driver.get` will hang\n' + '\n' + bug + '\n')
  Promise.resolve()
  .then(() => 'test')
  .then(() => driver.get('about:blank'))
}
```
### Fix1 - delete the 1st then call

``` javascript
function fire1() {
  console.log('fix1: delete the `then` call\n' + '\n' + fire1 + '\n')
  Promise.resolve()
  .then(() => driver.get('about:blank'))
}
```
### Fix2 - or add a catch call

``` javascript
function fire2() {
  console.log('fix2: add a `catch` call\n' + '\n' + fire2 + '\n')
  Promise.resolve()
  .then(() => 'test')
  .catch(e => console.error(e))
  .then(() => driver.get('about:blank'))
}
```
### Fix3 - or resolve the promise with a setTimeout instead of resolve directly

``` javascript
function fire3() {
  console.log('fix3: resolve promise with a `setTimeout` call\n' + '\n' + fire3 + '\n')
  new Promise((resolve, reject) => {
    setTimeout(resolve, 0)
  })
  .then(() => 'test')
  .then(() => driver.get('about:blank'))
}
```

All of the above code is tested under nodejs v6.0.0.

Has there anybody met this kind of problem before? What's the reason behind this?

I thought it maybe related with the nodejs event loop, or native promise implementation... but I'm dont know how to dig deeper any more.

Code in Gist: https://gist.github.com/zixia/77896cbd446c7282f760c60a025fee17
Stackoverflow: https://stackoverflow.com/questions/37692364/selenium-webdriver-hang-in-very-simple-javascript-code-with-promise-then

**Comment by jleyba** [comment]
I haven't found the actual bug, but I did fix this specific instance of it with the cleanup in 03423099915fe6a2b0ddd89e63ab145149ad01ac

**Comment by zixia** [comment]
Wow, it's a lot of cleanups. I'll try the dev branch code later and post feedback here.

**Comment by jleyba** [comment]
I squashed 5 or 6 commits into one before pushing. The changes that actually "fixed" this were all in [lib/webdriver.js](https://github.com/SeleniumHQ/selenium/commit/03423099915fe6a2b0ddd89e63ab145149ad01ac#diff-8d08e47355ecd3bd4b7f70008552ebda)

**Comment by zixia** [comment]
aha~ I use the last version of lib/webdriver.js to replace it in my node_modules/selenium/lib/webdriver.js , then everything went ok.

looks this bug had gone. :+1: 

but I'm still want to know what is the root reason caused this bug, do you know which part of the old code is wrong?

**Comment by jleyba** [comment]
I haven't closed this bug because I haven't found the bug yet. I can see where the promise manager gets stuck in the logs, I just don't understand why yet.

**Comment by zixia** [comment]
looking forward to hear from you when you found this bug. thanks!

**Comment by jleyba** [comment]
This has the same underlying cause as #3037, so closing this to consolidate tracking.

**Comment by zixia** [comment]
@jleyba thank you for noticing me that, appreciate.
