### ISSUE TITLE
TypeLoad/NotImplemented exception thrown when calling SwitchTo() on EventFiringWebDriver

### ISSUE THREAD

**Issue by BeigeBadger** [SeleniumHQ/selenium#2234]
## Meta -
OS:  Windows 10
IDE: Visual Studio Professional 2015 Update 1

Selenium Version:  
2.53.0

Browser:  
Google Chrome

Browser Version:  
51.0.2704.84 m (64 bit)

## Expected Behavior -
Driver to switch to newly opened tab

## Actual Behavior -
Exception is thrown:
`at OpenQA.Selenium.Support.Events.EventFiringWebDriver.SwitchTo()
   at Admin.UITests.Admin.Reports.MonitoringReport.ReportsMonitoringReportTests`1.Reports_MonitoringReport_SmartrakUser_CrmHistoryLink_WorksCorrectly_Test() in C:\Users\matt\Documents\SVN\stkcore\Branches\MonitoringReport_SP_263\Admin\UITests\Admin\Reports\MonitoringReport\ReportsMonitoringReportTests.cs:line 807
Result1 Message:	System.TypeLoadException : Method 'ParentFrame' in type 'EventFiringTargetLocator' from assembly 'WebDriver.Support, Version=2.42.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

## Steps to reproduce -
`public void ThisFails()
		{
			ChromeDriverService chromeDriverService = ChromeDriverService.CreateDefaultService(@"C:\", "chromedriver.exe");
			chromeDriverService.HideCommandPromptWindow = true;

			EventFiringWebDriver driver = new EventFiringWebDriver(new ChromeDriver(chromeDriverService));

			driver.Navigate().GoToUrl("http://www.nzherald.co.nz/");

			Thread.Sleep(5000);

			driver.FindElement(OpenQA.Selenium.By.ClassName("bkt-WatchMe")).Click();

			Thread.Sleep(2000);

			driver.SwitchTo().Window(driver.WindowHandles.Last());
		}`

**Comment by Photonios** [comment]
Exact code used to attempt reproduction:

            ChromeDriverService chromeDriverService = ChromeDriverService.CreateDefaultService(@"F:\ChromeDriver\", "chromedriver.exe");
            chromeDriverService.HideCommandPromptWindow = true;

            EventFiringWebDriver driver = new EventFiringWebDriver(new ChromeDriver(chromeDriverService));

            driver.Navigate().GoToUrl("http://www.nzherald.co.nz/");

            Thread.Sleep(5000);

            driver.FindElement(OpenQA.Selenium.By.ClassName("bkt-WatchMe")).Click();

            Thread.Sleep(2000);

            driver.SwitchTo().Window(driver.WindowHandles.Last());

Could not reproduce on latest Git checkout `125dd354390836fbfb45907552447e7e901ec52d`. Works as expected.
