### ISSUE TITLE
Firefox 48.0a2 crashed after loading webdriver extension

### ISSUE THREAD

**Issue by ronkorland** [SeleniumHQ/selenium#2238]
## Meta -
OS:  OSX
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version:  48.0a2

## Steps to reproduce -
[webdriver.zip](https://github.com/SeleniumHQ/selenium/files/305258/webdriver.zip)

1. Open webdriver.xpi file and edit install.rdf file.
2. Change maxVersion from 47.0 to 49.0 and save.
3. Open Firefox 48.0a2 (developer edition) and load webdriver extension.

## Actual Behavior -
Firefox crashed with error:

AdapterDeviceID: 0x0d26
AdapterVendorID: 0x8086
Add-ons: fxdriver%40googlecode.com:2.53.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:48.0a2,e10srollout%40mozilla.org:1.0,firefox%40getpocket.com:1.0.3b1,loop%40mozilla.org:1.4.0
AddonsShouldHaveBlockedE10s: 1
BuildID: 20160601004014
CrashTime: 1464794063
DOMIPCEnabled: 1
E10SCohort: unsupportedChannel
EMCheckCompatibility: true
Email: 
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1464793833
MozCrashReason: MOZ_CRASH()
Notes: AdapterVendorID: 0x8086, AdapterDeviceID: 0x0d26FP(D000-L10000-W00000000-T0100) GL Layers? GL Context? GL Context+ GL Layers+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: aurora
SafeMode: 0
SecondsSinceLastCrash: 21
StartupTime: 1464794058
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20160601004014","version":"48.0a2","vendor":"Mozilla","platformVersion":"48.0a2","xpcomAbi":"x86_64-gcc3","hotfixVersion":null,"architecturesInBinary":"i386-x86_64"},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":16384,"virtualMaxMB":null,"cpu":{"count":8,"cores":4,"vendor":"GenuineIntel","family":6,"model":70,"stepping":1,"l2cacheKB":256,"l3cacheKB":6144,"speedMHz":2200,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2"]},"os":{"name":"Darwin","version":"15.4.0","locale":"en-IL"},"hdd":{"profile":{"model":null,"revision":null},"binary":{"model":null,"revision":null},"system":{"model":null,"revision":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"adapters":[{"description":null,"vendorID":"0x8086","deviceID":"0x0d26","subsysID":null,"RAM":null,"driver":null,"driverVersion":null,"driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1440,"screenHeight":900,"scale":2},{"screenWidth":1920,"screenHeight":1080,"scale":1}],"features":{"compositor":"none"}}},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sCohort":"unsupportedChannel","telemetryEnabled":true,"locale":"en-US","update":{"channel":"aurora","enabled":true,"autoDownload":true},"userPrefs":{"browser.cache.disk.capacity":358400,"browser.newtabpage.enhanced":true,"browser.shell.checkDefaultBrowser":false,"devtools.chrome.enabled":true,"devtools.debugger.remote-enabled":true,"xpinstall.signatures.required":false},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":false},"profile":{"creationDate":16945},"addons":{"activeAddons":{"e10srollout@mozilla.org":{"blocklisted":false,"description":"Staged rollout of Firefox multi-process feature.","name":"Multi-process staged rollout","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16945,"updateDay":16953,"isSystem":true},"firefox@getpocket.com":{"blocklisted":false,"description":"When you find something you want to view later, put it in Pocket.","name":"Pocket","userDisabled":false,"appDisabled":false,"version":"1.0.3b1","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16945,"updateDay":16953,"isSystem":true},"loop@mozilla.org":{"blocklisted":false,"description":"Web sharing for Firefox","name":"Firefox Hello","userDisabled":false,"appDisabled":false,"version":"1.4.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16945,"updateDay":16953,"isSystem":true},"fxdriver@googlecode.com":{"blocklisted":false,"description":"WebDriver implementation for Firefox","name":"Firefox WebDriver","userDisabled":false,"appDisabled":false,"version":"2.53.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":true,"installDay":16953,"updateDay":16953,"signedState":0,"isSystem":false}},"theme":{"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","blocklisted":false,"description":"The default theme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"48.0a2","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":16945,"updateDay":16953},"activePlugins":[{"name":"Default Browser Helper","version":"601","description":"Provides information about the default web browser","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/apple-default-browser"],"updateDay":16845},{"name":"Java Applet Plug-in","version":"Java 8 Update 77 build 03","description":"Displays Java applet content, or a placeholder if Java is not installed.","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-java-applet;deploy=11.77.2","application/x-java-applet;version=1.4","application/x-java-applet;version=1.2.1","application/x-java-applet;version=1.2.2","application/x-java-applet;version=1.3","application/x-java-applet;version=1.8","application/x-java-vm","application/x-java-applet;version=1.1.1","application/x-java-applet;version=1.2","application/x-java-applet;version=1.7","application/x-java-applet;version=1.4.1","application/x-java-applet;version=1.1.2","application/x-java-applet","application/x-java-applet;jpi-version=1.8.0_77","application/x-java-applet;javafx=8.0.72","application/x-java-applet;version=1.1","application/x-java-applet;version=1.1.3","application/x-java-applet;version=1.6","application/x-java-applet;version=1.4.2","application/x-java-applet;version=1.3.1","application/x-java-applet;version=1.5"],"updateDay":16881}],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.5.3","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"1.4.8.866","userDisabled":false,"applyBackgroundUpdates":1}},"activeExperiment":{},"persona":"firefox-devedition@mozilla.org"}}
TextureUsage: 121936896
Theme: classic/1.0
Throttleable: 1
URL: about:sessionrestore
UptimeTS: 5.15889829
Vendor: Mozilla
Version: 48.0a2
useragent_locale: en-US

**Comment by lukeis** [comment]
same problem with 47, duplicate issue of #2110
