### ISSUE TITLE
element click doesn't work after upgrading to 2.53

### ISSUE THREAD

**Issue by jpreddygithub** [SeleniumHQ/selenium#2239]
## Meta -
OS:  
10.10.5
Selenium Version:  
2.53
Browser:  
Fire fox

Browser Version:  
38.8.0

## Expected Behavior -
Click on element that displays popup doesn't work.
Ex:
Element xpath:
//a[contains(.,'EightyCharacterLengthGroupNameEightyCharacterLengthGroupNameEightyCharacterLengt')]/ancestor::tr//a[contains(@href,'javascript')]

## Actual Behavior -
It highlights the url though click doesn't throw error.

## Steps to reproduce -
a) Create an element with a href that executes a javascript to display a popup
b) Get the element and call click on it

Note:  
If we perform the same click using JavascriptExecutor it works.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
