### ISSUE TITLE
setPosition changes the window size in Linux

### ISSUE THREAD

**Issue by jbrower2** [SeleniumHQ/selenium#2242]
## Meta -

OS: Linux Mint 17.3 Cinnamon 64-Bit
Selenium Version: 2.53.0 (in Java)
Browser: Any
Browser Version: Any
## Expected Behavior -

the position would change
## Actual Behavior -

the window does not move
## Steps to reproduce -

driver.manage().window().setPosition(new Point(rect.x, rect.y))

**Comment by jbrower2** [comment]
Sorry for the incorrect titles. The issue I have now determined is that using setPosition changes the screen size. I believe the screen size that it is changing it to is the original size of the window. This size change usually prevents the screen from placing the window in the correct location. For example:
`// browser is started and takes up most of the screen`
`driver.manage().window().setSize(new Dimension(400, 400));`
`driver.manage().window().setPosition(new Point(200, 200)); // causes the window to resize`

**Comment by jbrower2** [comment]
Note that this same example works fine on Windows.

**Comment by lukeis** [comment]
we mostly delegate this call to the browser itself, calling window.moveTo and window.resizeTo.

Can you manually try to execute these methods to see if the browser itself is causing this incorrect behavior? This may be an issue in firefox itself on linux.

https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo
https://developer.mozilla.org/en-US/docs/Web/API/Window/moveTo

**Comment by jbrower2** [comment]
I did try that, and it works. [This example](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_moveto) successfully moves the window without changing the size (even if you manually change the size after opening it). I noticed that you can't move the window from the console inside the window itself, but this is not allowed in any browsers (except IE). If you have time, could you point me to where you actually perform this javascript command?

**Comment by lukeis** [comment]
moveTo -
https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/window.js#L331
called from firefoxDriver -
https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/js/firefoxDriver.js#L1218

resizeTo -
https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/window.js#L268
called from firefoxDriver -
https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/js/firefoxDriver.js#L1199

These are executed in a 'privileged' scope as an extension, which is not the same as executing in the browser console.

**Comment by jbrower2** [comment]
(Sorry, I meant Java) I located the issue. The problem is that calling "window.screenX = {x}" and "window.screenY = {y}" has no effect on the current window (in almost all modern browser versions, except some versions of IE), as it attempts to do [in RemoteWebDriver](https://github.com/SeleniumHQ/selenium/blob/cc6b93571b2ce8f4af9100df34f31acdee3bd7a3/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L911). I'm not familiar enough with Selenium to attempt to work on a fix. I suspect that you would need to structure the setPosition function to be equivalent to the structure of the setSize function, with a newly created DriverCommand.SET_CURRENT_WINDOW_POSITION if that is possible.

**Comment by jbrower2** [comment]
To clarify, your calls for `bot.window.moveTo` work fine because it is not the main window. If you simply called `window.moveTo` from within the test window (as you essentially do in RemoteWebDriver) it would not work. Most browsers block windows from resizing/moving themselves.

**Comment by jbrower2** [comment]
Another remark is that `window.screenX` and `window.screenY` are read-only so line 911 in RemoteWebDriver.java will definitely not have any effect. It works fine when getting the window position on line 939, however.

**Comment by lukeis** [comment]
I think you misunderstand some of the architecture in WebDriver. All client languages (java, c#, python, ruby, javascript, etc.) communicate with driver implementations over a REST-like api with HTTP. So the driver implementations are disjointed from the client language, in your case java.

The FirefoxDriver happens to be implemented in Javascript as a Firefox extension. Firefox extensions are run in a 'privileged' scope allowing the extension to perform actions on a main window that normal javascript on the page would not be able to, for example resizing the primary window.

**Comment by jbrower2** [comment]
Okay that makes sense. It still will not be able to resize the window using the script on line 911 of RemoteWebDriver because `window.screenX` and `window.screenY` [are read-only](https://developer.mozilla.org/en-US/docs/Web/API/Window/screenX). You should be able to use `window.moveTo(arguments[0], arguments[1])` if what you said is correct. Sorry for the misunderstanding.

**Comment by lukeis** [comment]
line 911 would only get executed if you were using GeckoDriver (aka marionette). Using FirefoxDriver from the selenium project will execute the lines above -
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L907-L909

which will go into the code i linked previously in the FirefoxDriver javascript code.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
