### ISSUE TITLE
org.openqa.selenium.TimeoutException: Timed out waiting for page load.

### ISSUE THREAD

**Issue by amitavmishra** [SeleniumHQ/selenium#2246]
Hi,  I am using 
OS:  Windows 7
Selenium Version:  2.52
Browser:  Firefox 42.0

While clicking one Tab in my application, it is clicking the element,but while the page is loading it is throwing the below error. Below is the log.

org.openqa.selenium.TimeoutException: Timed out waiting for page load.
Command duration or timeout: 1.04 seconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'MLBBT-A12032', ip: '192.168.9.59', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Session ID: ca99ad5d-c610-4ebd-9934-38917e121659
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=42.0}]

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
