### ISSUE TITLE
IDE: Test Case / Properties filename looks editable but it isn't

### ISSUE THREAD

**Issue by szabgab** [SeleniumHQ/selenium#2250]
## Meta -

OS:  OSX
Selenium Version:  2.9.1
Browser:  Firefox 
Browser Version:  47.0
## Expected Behavior -

Either allow the user to rename a test case by changing the name in the Properties window, or make it clear the field is read-only.
## Steps to reproduce -

Right click on the name of a Test case and the click on Properties...
You get a window with two text entry boxes, one with the name of the file and another one with the title of the script. The filename is not editable but there is no visual indications for this.
The two fields look the same and they both look editable.
See attached screenshot.
![screen shot 2016-06-10 at 9 02 57 am](https://cloud.githubusercontent.com/assets/48833/15955484/459f97dc-2eea-11e6-9386-dbc737bfdef5.png)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
