### ISSUE TITLE
IDE: Changed Test can be Deleted without any warning - loosing my changes

### ISSUE THREAD

**Issue by szabgab** [SeleniumHQ/selenium#2251]
## Meta -

OS: OSX
Selenium Version: 2.9.1
Browser: Firefox
Browser Version: 47.0
## Expected Behavior -

The IDE should ask if I would like to save my changes before closing a Test Case
## Actual Behavior -

Silently closes the Test Cases loosing my changes
## Steps to reproduce -

``````
* Open a Test Suite with at least one Test Case in it.
* Edit the 'Target' of one of the steps. (e.g. add a character).
* (Note, an asterisk ```*``` appears next to the name of the test in the 'Test Suite' pane.)
* Right click on the name of the Test Case and click on Delete

* Click in the Test Case pane and click on 'Add Test Case'
* Find and select the filename of the previously deleted Test Case and open it
* Find the step that was changed and see it returned to the original value
``````

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
