### ISSUE TITLE
IDE: Change in Base URL is not indicated in the Test Case pane

### ISSUE THREAD

**Issue by szabgab** [SeleniumHQ/selenium#2252]
## Meta -

OS: OSX
Selenium Version: 2.9.1
Browser: Firefox
Browser Version: 47.0
## Expected Behavior -

When changing the "Base URL" I'd expect some kind of indication that the 'Test Case' has changed. e.g. an Asterisk next to the name of the test case in the 'Test Case' pane.
## Actual Behavior -

No indication.
## Steps to reproduce -

```
* Open a Test Suite with at least on Test Case in it that has a 'Base URL'
* Change the 'Base URL'
* There is no Asterisk next to the test case name in the 'Test Case' pane.
```

Apparently even this indication does not protect me from data loss. See #2251

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
