### ISSUE TITLE
Find element by id on IE is not accurate

### ISSUE THREAD

**Issue by ckorakidis** [SeleniumHQ/selenium#2256]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.53.0, WebDriver
Browser:  
Internet Explorer

Browser Version:  
11.0.30 (https://support.microsoft.com/en-us/kb/3148198) 

## Expected Behavior -
Finds element by id

## Actual Behavior -
Does not always find the element

## Steps to reproduce -
is not always experienced.

`        try {
            return wait
                    .ignoring(StaleElementReferenceException.class)
                    .ignoring(NoSuchElementException.class)
                    .until(ExpectedConditions.presenceOfElementLocated(locator));
        } catch (TimeoutException e)`

Once the page containing the element with the given id is shown, it waits for the element to be shown (it's already shown but the webdriver returns 'Unable to find element with id == theGivenId') and when the wait limit passes, it fails.

Not any issues with not focusing on the right iframe etc because in most of the cases it works.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
