### ISSUE TITLE
CurrentWindowHandle Exception Error

### ISSUE THREAD

**Issue by danwan** [SeleniumHQ/selenium#2266]
Language: .net
Selenium: 2.53
Chrome: 51.0
Chromedriver: 2.22

Steps to reproduce:
Open Chrome via Selenium.
Open a new tab manually
Close the first tab

Now, the selenium driver should not be able to get the window handle of the open tab. Because that one was opened manually, and the original one was closed.

If I run:
var test = driver.CurrentWindowHandle;

It works fine. And doesn't trow an exception. Which is NOT correct.

Because if I run:
var test1 = driver.WindowHandles;
var test = driver.CurrentWindowHandle;

now the CurrentWindowHandle method will trow an exception:
NoSuchWindowException: no such window:target window already closed.

With FF I always get:
NoSuchWindowException: Window not found.
No matter if I run CurrentWindowHandle directly, or if I use
var test1 = driver.WindowHandles;
upfront.

**Comment by jleyba** [comment]
This is a bug in the chromedriver and should be reported here:

https://bugs.chromium.org/p/chromedriver/issues/list
