### ISSUE TITLE
Python Install/Setup

### ISSUE THREAD

**Issue by jmieleiii** [SeleniumHQ/selenium#2267]
## Meta -
OS:  OSX 10.11.4

Selenium Version:  2.53.5

Browser:  Firefox

## Expected Behavior -
Created virtualenv, activate, pip installed selenium
```shell
(selenium_python) ~/selenium_python $ pip list
pip (6.1.1)
selenium (2.53.5)
setuptools (15.0)
```
Running python python_test.py :
```shell
from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/')
```
Expected to launch browser.

## Actual Behavior -
```shell
(selenium_python) ~/selenium_python $ python python_test.py
Traceback (most recent call last):
  File "python_test.py", line 3, in <module>
    browser = webdriver.Firefox()
AttributeError: 'module' object has no attribute 'Firefox'
```

**Comment by AutomatedTester** [comment]
I just tried to do this and it worked for me (other than hitting a different bug with Firefox in #2110)

```python 
Python 3.5.1 (default, Jan  4 2016, 10:38:47)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> f=webdriver.Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dburns/.virtualenvs/selpy3/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 81, in __init__
    self.binary, timeout)
  File "/Users/dburns/.virtualenvs/selpy3/lib/python3.5/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Users/dburns/.virtualenvs/selpy3/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/Users/dburns/.virtualenvs/selpy3/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

>>> exit()
```

**Comment by jmieleiii** [comment]
Seems it was a bad python install. I was eventually able to clear it up

**Comment by chungheek** [comment]
Hello @jmieleiii I was wondering how you were able to clear this issue? When you say it was a bad python install, what do you exactly mean by that? Thank you!

**Comment by Kellogs** [comment]
I am getting the same issue, new to Python. I did read an article that Apple Python and HomeBrew Python by default try to install runnable scripts in user/local/bin. So whichever one you install second will overwrite the first. I have a suspicion this might be my issue. However I am unsure how to resolve it, any pointers would be appreciated. Thank you

**Comment by jmieleiii** [comment]
If I remember correctly it had to do with how I initially installed Python. I don't remember the specifics but it was essentially executing the wrong version of Python. I believe I was trying to have a version of 3.x installed/executed when I used `$ python ...` which would involve a lot of toying with PATH, etc.

I think to fix it I literally uninstalled all versions except for the system version and removed all changes from my bash_profile and started over fresh with Homebrew. Once I reinstalled everything it ran without issue.

**Comment by cgoldberg** [comment]
> Apple Python and HomeBrew Python by default try to install runnable scripts in user/local/bin.
> So whichever one you install second will overwrite the first.

Apple Python installs in `user/bin` ... Howebrew Python installs in `user/local/bin`... so there is no conflict or overwriting,   Whichever directory is listed first in your PATH environment variable will be executed.
