### ISSUE TITLE
phantomjs of the process is not completed on osx

### ISSUE THREAD

**Issue by TakesxiSximada** [SeleniumHQ/selenium#2272]
## Meta -

OS:  OSX

Selenium Version:  2.53.4

Browser:  phantomjs

Browser Version:  2.1.1

```
$ phantomjs --version
2.1.1
```

Python Version etc...:

```
$ python
Python 3.5.1 (default, Jun 11 2016, 19:40:49)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import selenium
>>> selenium.__version__
'2.53.4'
>>>
```
## Expected Behavior -

I hope that the process of phantomjs does not remain.

run.py

``` :run.py
from selenium.webdriver.phantomjs.webdriver import WebDriver
driver = WebDriver()
driver.close()
driver.quit()
```
## Actual Behavior -

However , there is a case that the process remains.
## Steps to reproduce -

```
$ ps -ef | grep phantomjs
  501 51810 15789   0  7:41PM ttys001    0:00.00 grep --color phantomjs
$ python run.py
$ ps -ef | grep phantomjs
  501 51826     1   0  7:42PM ttys001    0:01.35 /Users/sximada/.nvm/versions/node/v6.2.0/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs --cookies-file=/var/folders/hx/xp4thw0x7rj15r_2w57_wvfh0000gn/T/tmpci5a6uae --webdriver=62051
  501 51830 15789   0  7:42PM ttys001    0:00.00 grep --color phantomjs
$
```
## Details

First phantomjs is about, 
When we run "npm install phantomjs", npm create a file "node_modules/.bin/phantomjs".
"node_modules/.bin/phantomjs" is the following files .

```
$ cat node_modules/.bin/phantomjs
#!/usr/bin/env node

/**
 * Script that will execute the downloaded phantomjs binary.  stdio are
 * forwarded to and from the child process.
 *
 * The following is for an ugly hack to avoid a problem where the installer
 * finds the bin script npm creates during global installation.
 *
 * {NPM_INSTALL_MARKER}
 */

var path = require('path')
var spawn = require('child_process').spawn

var binPath = require(path.join(__dirname, '..', 'lib', 'phantomjs')).path

var args = process.argv.slice(2)

// For Node 0.6 compatibility, pipe the streams manually, instead of using
// `{ stdio: 'inherit' }`.
var cp = spawn(binPath, args)
cp.stdout.pipe(process.stdout)
cp.stderr.pipe(process.stderr)
process.stdin.pipe(cp.stdin)

cp.on('error', function (err) {
  console.error('Error executing phantom at', binPath)
  console.error(err.stack)
})

cp.on('exit', function(code){
  // Wait few ms for error to be printed.
  setTimeout(function(){
    process.exit(code)
  }, 20)
});

process.on('SIGTERM', function() {
  cp.kill('SIGTERM')
  process.exit(1)
})
```

A real phantomjs process be born using `spawn` function by childprocess ("node_modules/.bin/phantomjs" proccess).
It is the grandchild process.

Structure at this time , is the following structure .

```
[current process]        [child process]                                  [grandchild process]
selenium (python) ->  node_modules/.bin/phantomjs ->  node_modules/phantomjs/lib/phantomjs.js
```

Implementation of the termination process is the following (this is selenium python binding code).

https://github.com/SeleniumHQ/selenium/blob/051c8b110a1aec35247cd45fa4db85c6e522cdcb/py/selenium/webdriver/common/service.py#L151-L153

```
                self.process.terminate()
                self.process.kill()
                self.process.wait()
```

In Posix OS process.terminate () is SIGTERM, process.kill () is SIGKILL.
If child process before issuing the SIGTERM to grandchild process, parent process issued SIGKILL to child process...
A child process will die, but a grandchild process will continue to live as a zombie.
Actually, Stops correctly, sleep between "self.process.ternimate()" and "self.process.kill()"

In Windows OS process.terminate () is Win32 API TerminateProcess(), and  process.kill() s Win32 API TerminateProcess() too.
So it completed successfully, it work correctly child process's SIGTERM Handler.

node_modules/.bin/phantomjs

```
process.on('SIGTERM', function() {
  cp.kill('SIGTERM')
  process.exit(1)
})
```

The cause of this problem is that it does not properly close their phantomjs.

To fix it will be considered in three ways.

(1) Correctly to end the phantomjs ( using the shutdown API).
(2) Sleep between process.terminate() and process.kill().
(3) Only if the child process has not been completed in certain time, parent process call self.process.kill().

**Comment by TakesxiSximada** [comment]
Related pull request: https://github.com/SeleniumHQ/selenium/pull/2244 (Not merged)

**Comment by TakesxiSximada** [comment]
This case is occur when installed phantomjs in npm on Linux or OSX.

**Comment by ipinak** [comment]
I get the same issue. Is anyone working on a fix for this?

**Comment by kitamurakei** [comment]
pull requested #2543 .

**Comment by lmtierney** [comment]
Closing this as PhantomJS is deprecated in favor of headless Chrome or Firefox. Sorry we didn't get to this sooner
