### ISSUE TITLE
Unexpected Alert Open - WebDriver\Exception

### ISSUE THREAD

**Issue by mjamil4it** [SeleniumHQ/selenium#2274]
## Meta -
OS: Windows 7  

Selenium Version:  2.53.0

Browser:  Chrome v50, Firefox v46

Browser Version:  32 bit

Expected Behavior - complete the behat test
Actual Behavior -  getting following error

[WebDriver\Exception\UnexpectedAlertOpen]
Unexpected modal dialog (text: Not Found) The alert could not be closed. Th
e browser may be in a wildly inconsistent state, and the alert may still be
 open. This is not good. If you can reliably reproduce this, please report
a new issue at https://github.com/SeleniumHQ/selenium/issues with reproduct
ion steps. Exception message: TypeError: a.document.getElementsByTagName(..
.)[0].getButton is not a function: Not Found
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00
:58'
System info: host: 'localhost', ip: '169.254.52.152', os.name: 'Windows 7',
 os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts
=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents
=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled
=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, c
ssSelectorsEnabled=true}]
Session ID: 163596c8-f317-430a-88e6-1ef8a2d4870d

## Steps to reproduce -
Running behat test for moodle plugin called checklist. you can download from the following link. 
https://moodle.org/plugins/pluginversions.php?plugin=mod_checklist

Moodle v3.1
PHP 5.5.17

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by johnnylupino** [comment]
hi, this might be already a forgotten issue , but I have encountered the same problem running the full moodle behat tests (standard tests - nothing new written). 
Re-run it twice and on the last time, I ran with @mod_checklist tag only.
Here is the output from the file:
[behat_fails_on_std_checklist.txt](https://github.com/SeleniumHQ/selenium/files/3083643/behat_fails_on_std_checklist.txt)

The tests were run in moodle-docker environment, ubuntu, chromedriver

Let me know, in case you need more info

regards,
archie

**Comment by johnnylupino** [comment]
ok, so I've tried the firefox driver instead of chrome and it passed the test.
I hope this message will help others encountering the same or similar issue.
