### ISSUE TITLE
python: WebDriver capabilities argument not taken into account correctly

### ISSUE THREAD

**Issue by elessard1** [SeleniumHQ/selenium#2275]
## Meta -
OS:  Debian 8
Selenium Version:  2.53.5
Browser: Firefox
Browser Version: 47.0

## Expected Behavior -

The following code

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX.copy()
capabilities['marionette'] = True
capabilities['acceptSslCerts'] = True
driver = webdriver.Firefox(capabilities=capabilities)
driver.quit()
```

should result in the 'acceptSslCerts' capability to be pass to geckodriver as a desiredCapabilities but this is not always the case, because of a bug in the start_session method of selenium.webdriver.remote.webdriver.WebDriver.

The bug is:

* when start_session is called...
 * desired_capabilities is a dict looking like this (simplified): {'acceptSslCerts': True, 'desiredCapabilities': {'binary': '/usr/bin/firefox', 'firefox_profile': u'...', 'args': []}}
 * note that the 'desiredCapabilities' key has been added by the call to "capabilities.update(self.options.to_capabilities())" in the init method of selenium.webdriver.firefox.webdriver.WebDriver
 * capabilities is a dict: {'desiredCapabilities': {}}
* then the code iterates on desired_capabilities.items(). If the iteration "process" the key 'acceptSslCerts' *before* the key 'desiredCapabilities', then the 'acceptSslCerts' capability will be lost

## Actual Behavior -

Depending on the iteration order of the desired_capabilities dict in start_session, the capabilities you pass will be ignored.

## Steps to reproduce -

Have a setup with firefox and geckodriver.

Run this code:
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX.copy()
capabilities['marionette'] = True
capabilities['acceptSslCerts'] = True

driver = webdriver.Firefox(capabilities=capabilities)
driver.quit()
```

Look at the output of geckodriver.log: if you hit the bug, you'll see that the acceptSslCerts is not passed to newSession.

The bug is dependent on the iteration order of a python dictionary, so some people might not observe it depending on the python version and the content of the dictionary, etc.

**Comment by lukeis** [comment]
please log marionette bugs with mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

**Comment by elessard1** [comment]
As far as I understand, this is a bug in the start_session method of the selenim.webdriver.remote.webdriver.WebDriver class:

```
    def start_session(self, desired_capabilities, browser_profile=None):
        capabilities = {'desiredCapabilities': {}}
        for k, v in desired_capabilities.items():
            if k not in ('desiredCapabilities', 'requiredCapabilities'):
                capabilities['desiredCapabilities'][k] = v
            else:
                capabilities[k] = v
        ...
```

If the desired_capabilities argument (a dict) has both a key 'acceptSslCerts' and a key 'desiredCapabilities', then the key 'acceptSslCerts' will be ignored if the key 'desiredCapabilities' is processed _after_ the 'acceptSslCerts' key. This is the kind of situation that happens when you create a firefox WebDriver like in my example above.

Thank you

**Comment by AutomatedTester** [comment]
The issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1103196

Since we can't support it, we ignore the capability and return back what we can support when you create the session

**Comment by elessard1** [comment]
Thank you for the link.
