### ISSUE TITLE
Safari Extension Local Ruby

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2277]
## Meta -
OS:  OSX
Selenium Version:  3.0
Browser:  Safari

## Expected Behavior -
`client.js` file should allow Ruby's server to drive safari via extension

## Actual Behavior -
Safari starts but will not connect

If I comment out [this line](https://gist.github.com/titusfortner/f816a67d75091a34a3564ed117009fe9#file-client-js-L460), it works. 

My best guess is that there is something else that I need to build for my ruby bindings that is already present when building the server, but I can't figure out what it is. That being said, I can delete all of the `goog.DEPENDENCIES_ENABLED` code in client.js and all of my tests pass both locally and through the server, so does it need to be there at all?

**Comment by titusfortner** [comment]
@jleyba - I did more work to figure out the root cause of the issue we discussed last week, if this makes more sense.

**Comment by jleyba** [comment]
@titusfortner I think 212a5e7bcc617236519cfa7f5b3c32b17c71379e will fix this.

**Comment by titusfortner** [comment]
Verified good. Thanks!
