### ISSUE TITLE
Setting script timeout on Marionette driver throws Error

### ISSUE THREAD

**Issue by soulgalore** [SeleniumHQ/selenium#2279]
## Meta 
OS:  OSX
Selenium Version:  2.53.2 (NodeJS)
Browser:  Firefox 
Browser Version:  47
Marionette driver

## Expected Behavior 
Setting script timeout should set timeout and not throw an Error.

## Actual Behavior 
Setting a script timeout throws a Error. Using Firefoxdriver this works.

## Steps to reproduce
<code>
driver.manage().timeouts().setScriptTimeout(10000);
</code>

## Extra
Created an issue for the Geckodriver and they pointed me here and can help out, ping @andreastt

**Comment by andreastt** [comment]
The issue being referred to here is https://github.com/mozilla/geckodriver/issues/77. The [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) does not have individual endpoints for the different script timeouts, but instead features a single [_Set Timeout_](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-set-timeout) command that takes a dictionary of timeout values. The valid input fields are:

* `script`
* `page load`
* `implicit`

The different Selenium bindings need to be updated to use this data format when interacting with WebDriver-conformant remote ends.

**Comment by titusfortner** [comment]
Already implemented in Ruby. :)

**Comment by lukeis** [comment]
java / python / .NET  also already have it implemented, leaves just javascript :)

@jleyba

**Comment by jleyba** [comment]
This was fixed for js in 4e77374658d643efde0f589e8018ff89d8e3a75c

**Comment by lukeis** [comment]
ok then... all fixed (probably pending a release for JS)
