### ISSUE TITLE
Selenium IE driver not closing browser

### ISSUE THREAD

**Issue by pedro93** [SeleniumHQ/selenium#2282]
OS:  Windows 8
Selenium Version:  2.53.0
Browser:  Internet Explorer

Browser Version:  10.0.9200

Expected Behavior -
Given the following code, I am trying to render local files using a browser of my choice, this works for all browsers except IE. I expected that the following code would open a browser, access the file specified, execute the javascript query and close the browser.
```js
function renderSelenium(address, engine, opts){
	let deferred = Q.defer(),
	until = webdriver.until,
	driver = new webdriver.Builder()
	.forBrowser(engine)
	.build();

	driver.get(address);
	driver.executeScript("return document.querySelector('html').outerHTML;")
	.then((html) => {
		driver.close();
		return deferred.resolve(html);
	});
	return deferred.promise;
}
```
I execute this code for all files in a directory (80+)
```js
files.forEach((file)=>{
 renderSelenium(file, "ie", {file:true});
});
````
## Actual Behavior -
What happens is that IE does not close after executing each meaning that a stack of tabs remain in the computer and eventually the program crashes because of it.
![trace](https://cloud.githubusercontent.com/assets/3718654/16039657/6de5bffc-322b-11e6-96e1-1d5c0410167e.png)

## Steps to reproduce -
Install IE webdriver 2.53.1
Make sure IE 10 is installed
Create a folder of 20+ html files and execute the code above.

**Comment by jimevans** [comment]
Unfortunately, there's nothing that can be done about this issue. The IE driver does not support opening URLs using the `file://` scheme. Files on the local computer are relegated to a special Protected Mode zone, and when a local file is opened like that, the driver crosses a protected mode boundary, and loses connection to the COM object the driver uses to automate the browser. This is a technical limitation of IE, and cannot easily be remedied within the driver code. As a workaround, you can use a local web server, and browse the files using HTTP.

**Comment by pedro93** [comment]
Is this IE limitation consistent throughout all its version (IE8 up to IE11) including the new Edge browser?

**Comment by jimevans** [comment]
Yes, it's consistent for all versions of the IE driver. The IE driver doesn't drive Microsoft Edge, nor does the Selenium project produce or maintain the driver for Microsoft Edge, so I cannot answer that question.

**Comment by pedro93** [comment]
Thank you for your swift reply. A final question, is support for a Microsoft Edge Driver in Selenium's roadmap?

**Comment by jimevans** [comment]
There already _is_ a [Microsoft Edge driver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/), provided by Microsoft. It is supported by all language bindings provided by the Selenium project.
