### ISSUE TITLE
Select fields are not filled in

### ISSUE THREAD

**Issue by MarioStoilov** [SeleniumHQ/selenium#2283]
## Meta -
OS:  Windows 10
Selenium Version: 2.53.2 
Browser:  Firefox 47 with marionette 0.8
Browser Version:  

Request a dev instance here -> http://www.servicenow.com/
Running this code (ruby):
```
@driver = Selenium::WebDriver.for :firefox, marionette: true
@driver.manage.timeouts.implicit_wait = 30
@accept_next_alert = true
BASE_URL = *your instance url here*
@driver.get(BASE_URL + '/nav_to.do?uri=%2Fchange_request.do%3Fsysparm_stack%3Dchange_request_list.do%26sys_id%3D-1%26sysparm_query%3Dactive%3Dtrue')
@driver.switch_to().frame('gsft_main')
select_field_element = Selenium::WebDriver::Support::Select.new(@driver.find_element(:id, 'change_request.type'))
select_field_element.select_by(:text, 'Normal')
```
Does not select the given value in a select field and does not throw any exception.
This exact same code works with the old FF driver and with chrome

**Comment by lukeis** [comment]
for marionette bugs, please file issues against mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette
