### ISSUE TITLE
Latest Firefox version does not work with Selenium Firefox driver

### ISSUE THREAD

**Issue by abmadrigal** [SeleniumHQ/selenium#2287]
## Meta -
OS:  
OSX -->
Selenium Version:  
2.53.0
Browser:  
Firefox 

Test won't run
-->

Browser Version:  
Firefox 47.0

## Expected Behavior -
Test should run

## Actual Behavior -
Test won;t even start up the browser

## Steps to reproduce -
Run as TestNG

**Comment by lukeis** [comment]
duplicate #2110

**Comment by rajeevprabhakaran** [comment]
The issue seems to be fixed with 2.53.1 and with Firefox 47.01. Please use the same.
