### ISSUE TITLE
[Improvement] Configurable speed for dragging elements

### ISSUE THREAD

**Issue by Cipirel** [SeleniumHQ/selenium#2291]
## Meta -

OS:  
All
Selenium Version:  
next
Browser:  
All
## Expected Behavior -

I want to be able to set the element drag speed. In some cases it's too fast.
## Actual Behavior -

As far as I know the drag speed is hard-coded and I can't change it.

**Comment by lukeis** [comment]
This is spec'd in the w3c spec for new actions -

https://w3c.github.io/webdriver/webdriver-spec.html#dfn-process-a-pointer-move-action

Although no where has implemented the Actions api yet. This will need to be done for IE and Firefox (selenium's extension based webdriver, if we get to it).

Other driver implementations maintained externally to selenium will have to be tracked separately.

**Comment by yufengzjj** [comment]
if it can control drag speed,it then would be useful for many automated tests on web

**Comment by AutomatedTester** [comment]
This has been added in to the spec and into bindings.
