### ISSUE TITLE
Could not multiple options in multi select list via Select class , using Marionette driver

### ISSUE THREAD

**Issue by dragodr93** [SeleniumHQ/selenium#2292]
## Meta -
OS:  Lubuntu 14.04
Selenium Version:  2.53.0
Browser:  Firefox 47

Browser Version:  47.0

## Expected Behavior
Able to select multiple options in multi select list via Select class , using Marionette driver

## Actual Behavior
Only one value is selected.
Side note - using Chrome , everything is working as expected.

## Steps to reproduce 

       WebElement webElement = webDriver.findElement( By.name( "listbox1" ) );

        Select select = new Select( webElement );

        for( String value : values ) {

            select.selectByVisibleText( value );

        }

**Comment by lukeis** [comment]
please log bugs with mozilla for issues with marionette:

https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette
