### ISSUE TITLE
FirefoxDriver has a profile issue when using FirefoxDriverService

### ISSUE THREAD

**Issue by salirezam** [SeleniumHQ/selenium#2296]
## Meta -
OS:  
Windows 8.1
Selenium Version:  
2.53+ (.Net)
Browser:  
Firefox

Browser Version:  
47 (64bit)
## Expected Behavior -
I should be able to set profile for Firefox when I am using FirefoxDriver constructor with a FirefoxDriverService.
## Actual Behavior -
The profile doesn't set even if you add the firefox_profile as an additional capability. It seems the profile need to be set on line 185 of FirefoxDriver.cs after converting options to capability and extracting profile.
## Steps to reproduce -
set a profile in a FirefoxOptions object
options.AddAdditionalCapability("firefox_profile", GetProfile().ToBase64String());

call a FirefoxDriver constructor like below
new FirefoxDriver(service, options, DefaultCommandTimeout)

**Comment by abelfiore** [comment]
Since the Marionette driver does not currently support setting a Profile in .NET (as this issue suggests), does this mean we should continue using the older Firefox driver if we require profiles in our testing? Are there any other workarounds or suggestions?

**Comment by jimevans** [comment]
Fixed in 6d361a4
