### ISSUE TITLE
WebDriverException: Unrecognised locator type: 'css'

### ISSUE THREAD

**Issue by wangzhih** [SeleniumHQ/selenium#2297]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.53.0, Selenium standalone server
Browser:  
Firefox
Browser Version:  
42.0 (32-bit) 

## Expected Behavior -
I run a test script of the following:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://mail.yahoo.com" />
<title>cssselector</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">cssselector</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/</td>
	<td></td>
</tr>
<tr>
	<td>waitForText</td>
	<td>css=div.tsl-message</td>
	<td>To sign in, enter your email and tap &quot;Next&quot;</td>
</tr>

</tbody></table>
</body>
</html>

It can be run successfully in IDE. But when I run it with Selenium Firefox WebDriver, I got WebDriverException: Unrecognised locator type: 'css'. 

14:06:54.120 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Unrecognised locator type: 'css'
Command duration or timeout: 55 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'xxx', ip: 'x.x.x.x', os.name: 'Windows 7',
os.arch: 'x86', os.version: '6.1', java.version: '1.7.0'
Session ID: 8ba9b6f9-9050-48e3-9e1b-ef4509239937
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cs
sSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts
=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationCont
extEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=42.
0}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:58)

## Steps to reproduce -
As above.

Please investigate if this a bug. Thanks.

**Comment by lukeis** [comment]
in webdriver the locator name should be "css selector"

you don't show how you're running this selenese (html table) as webdriver or how you're converting to it. Closing, as webdriver is working as expected
