### ISSUE TITLE
WebDriverException for only one page, rest of the application works fine

### ISSUE THREAD

**Issue by BRAutomation** [SeleniumHQ/selenium#2298]
## Meta -
OS:Windows7 64bit  

Selenium Version:  2.47.0

Browser: Internet Explorer (11)

-->

Browser Version:  

## Expected Behavior -
Selenium should Successfully switch to Next Page.
## Actual Behavior -
Selenium Throwing WebDriverException
Test case failed : OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:50985/session/42936a5b-eed5-4e2f-9a8d-2cb40fc89ff4/window_handles timed out after 120 seconds.
  ----' System.Net.WebException : The operation has timed out
OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
     
     OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
     
     OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
     
     OpenQA.Selenium.Remote.RemoteWebDriver.get_WindowHandles()
     
     OpenQA.Selenium.Support.Events.EventFiringWebDriver.get_WindowHandles()

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
