### ISSUE TITLE
firefox 47 has been release, please update accordingly

### ISSUE THREAD

**Issue by shaharmor** [SeleniumHQ/selenium#2299]
## Meta -
OS:  OSX
Selenium Version:  2.53.2 JS
Browser:  Firefox 47

I know i am logging a duplicate of #2110, but the browser has been released a week ago the the WebDriver has not been updated accordingly.

It is still looking for a **development** version of firefox which is not the case anymore, and thus not working with normal Firefox 47 release.

**Comment by andreastt** [comment]
Duplicate of #2110.
