### ISSUE TITLE
Provide shim for getting attribute when talking to WebDriver conformant remote

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#2301]
To maintain Selenium 2 API compatibility when clients speak to W3C WebDriver conformant remote ends, client bindings should provide a shim that implements Selenium’s conflation of attributes and properties using the _Get Element Attribute_ and _Get Element Property_ commands.

Using Selenium with Marionette will cause `getAttribute` to not look at the property, if present. It is possible to patch this in the clients by implementing the conflation behaviour there.

This is exemplified in https://github.com/mozilla/geckodriver/issues/95.

**Comment by Toilal** [comment]
When using MarionetteDriver, getAttribute("textContent") works fine with Firefox 47, but returns ```null``` with Nightly 50.0a1 (2016-06-16).

**Comment by andreastt** [comment]
Yes, the spec compatible _Get Element Attribute_ and _Get Element Property_ commands were added quite recently in [bug 1272653](https://bugzilla.mozilla.org/show_bug.cgi?id=1272653). It is available in Firefox 48, Firefox 49, and Nightly.

**Comment by andreastt** [comment]
A rough pseudo code shim would be:

```py
def get_attribute(attr):
    if webdriver_conformant:
        rv = driver.get_property(attr)
        if rv is not None:
            rv = driver.get_attribute(attr)
    else:
        rv = driver.get_attribute(attr)
    return rv
```

**Comment by andreastt** [comment]
@jimevans 

Based on your input on IRC earlier this afternoon, I realised the above snippet is insufficient to provide a Selenium-compatible shim when speaking to WebDriver-conformant remote ends.

Armed with the [Selenium atom](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/atoms/element.js#L129) that @lukeis linked, I had another stab at this (pseudo code):

```go
func get_property(session, element, name) {
    return send_element_message(sprintf("/property/%s", name))["value"]
}

func get_attribute(session, element, name) {
        // return el.style.cssText if attr is "style"
        if name == "style" {
                return session.execute_script("return arguments[0].style.cssText", [element])
        }

        // <option>, <input type=checkbox>, and <input type=radio>
        // are handled by getting their property and returning as string later

        // with <a href> and <img src> we prefer the @src and @href as properties
        // because it gives us the full, non-relative URL
        // but we get that by looking at them as properties first
        // then falling back to getting them as attributes below

        // spellcheck is not a boolean attribute,
        // but exhibits many of the same traits:
        // because it cannot be changed to anything other than true or false,
        // we can request the property value and return it as a string.
        //
        // however, for unknown reasons,
        // Selenium always returns it as a "false" string
        // instead of null
        else if name == "spellcheck" {
                // note that there is no res != null check on this result
                res = get_property(session, element, "spellcheck")
                // coerce to string
                return string(res)
        }

        prop = get_property(session, element, name)
        if prop != null {
                // coerce to string
                return string(prop)
        }

        // Get Element Attribute in WebDriver conformant remote ends
        // handle boolean attributes internally,
        // returning "true" (string) when set
        // and null otherwise
        return element.send_message(sprintf("/attribute/%s", name))["value"]
}
```

If you [compare that with the `getAttribute` atom](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/atoms/element.js#L129) you can tell there’s a lot of redundancy in the atom, especially now that [Get Element Attribute](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-attribute) handles boolean attributes internally.

Let me walk you through the different code paths in the atom:

* "`style`" needs to be handled explicitly because Selenium returns an entirely different style property (`element.style.cssText`).
* `<option>`, `<input type=checkbox>`, `<input type=radio>` can all be handled by getting either the "`selected`" or "`checked"` property values and coercing them to strings.
* On `<a href=…>` and `<img src=…>` Selenium prefers the longer-form full URL when a relative URI is specified. But because `get_attribute` first looks at the property and later the attribute, these too are handled by the normal property/attribute preference near the bottom of the function.
* `spellcheck` is [famously strange](https://lists.w3.org/Archives/Public/public-whatwg-archive/2006Jun/0271.html) and the reason we cannot rely on the default behaviour here is because Selenium expects it to either return "`true`" or "`false`". Fortunately, because it is always a property on all elements, we get the property and simply coerce the return value—which is always either true or false—to a string.
* Finally we look up the property, which returns some value or null if undefined, and coerce it to a string if it isn’t null.
* If the property is null, that means we have to look for the attribute. This always returns a string or null.

**Comment by jleyba** [comment]
This LGTM and I can implement it for node once there's a consensus.

We should consider making this shim for 3.x only and adopting a proper split in the API for 4.x

**Comment by AutomatedTester** [comment]
I have done an initial implementation in https://github.com/seleniumhq/selenium/tree/getElementProperty if people want to rip it apart

**Comment by titusfortner** [comment]
Should this now be tracking whether each binding is using the getAttribute atom?

**Comment by andreastt** [comment]
Yes, so another obvious approach is to just use the _getAttribute_ atom, like @titusfortner suggests. That is probably the safer option. If bindings are happy to use that atom, we can close this issue and create one tracking that instead.

**Comment by Toilal** [comment]
I can't reproduce the issue with Firefox ```49.0.1``` and selenium ```3.0.0-beta4```. ```element.getAttribute("textContent")``` retrieves the text content properly.

**Comment by lukeis** [comment]
java, .net and python use the attribute atom for w3c implementations now. Only node remains :) @jleyba

**Comment by jleyba** [comment]
What are the long term plans for `WebElement.getAttribute()` in the client bindings? Is the atom here to stay, or will we split getAttribute/getProperty for 4.0?
