### ISSUE TITLE
Click doesn't work if global scaling is above 100%

### ISSUE THREAD

**Issue by yuri-kalinin** [SeleniumHQ/selenium#2303]
## Meta -
OS:  Windows 10
Selenium Version:  2.52.0
Browser:  Internet Explorer
Browser Version:  11 (32-bit)

## Expected Behavior -
element.click() should send click event to the element being clicked
## Actual Behavior -
element.click() does not work if global scaling in Windows is >100%
## Steps to reproduce -
1. Set global scaling in Windows to >100% (Desktop > rclick > Display Settings)
2. Do some clicking on any small elements (like a button, link, etc.)

An alternative fix would be to add 'The global zoom level must be set to 100%' point to the
https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

**Comment by jleyba** [comment]
The required configuration already states:

> The browser zoom level must be set to 100% so that the native mouse events can be set to the correct coordinates.
