### ISSUE TITLE
Se - Providing a custom Firefox profile to Marionette causes Firefox to hang on start (not crash)

### ISSUE THREAD

**Issue by Inglonias** [SeleniumHQ/selenium#2304]
## Meta -
OS:  Windows Server 2012 R2
Selenium Version:  2.53.0
Browser: Firefox 47

## Expected Behavior -
Providing a Firefox profile to Marionette Driver should allow Firefox to start up with that profile.
## Actual Behavior -
Firefox will launch and then hang.

## Steps to reproduce -
1. Create a Firefox profile called "Eliza"
2. Run the code below.
`import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.MarionetteDriver;
import org.openqa.selenium.firefox.internal.ProfilesIni;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Selenium2Example  {
    public static void main(String[] args) {

    	ProfilesIni profile = new ProfilesIni();
    	FirefoxProfile eliza = profile.getProfile("Eliza");
    	DesiredCapabilities dc=DesiredCapabilities.firefox();
    	dc.setCapability(FirefoxDriver.PROFILE, eliza);
        WebDriver driver = new MarionetteDriver(dc);
        
        driver.quit();
    }
}`

**Comment by lukeis** [comment]
please log marionette issues with mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette
