### ISSUE TITLE
org.openqa.selenium.remote.RemoteWebDriver.execute cannot get response intermittently

### ISSUE THREAD

**Issue by sunswei** [SeleniumHQ/selenium#2311]
## Meta -
OS:  Linux
Selenium Version: selenium-server-standalone-2.53.0.jar  
Browser: Firefox 44.0.2

## Expected Behavior -
After we call driver.get("<some url>"), it is supposed to launch Firefox and enter the url, from the debug log, we can get 200 OK from the browser side

	_Line 854959: FINE: http-outgoing-5300: set socket timeout to 10800000
	Line 854967: FINE: http-outgoing-5300 >> POST /hub/session HTTP/1.1
	Line 854969: FINE: http-outgoing-5300 >> Content-Type: application/json; charset=utf-8
	Line 854971: FINE: http-outgoing-5300 >> Content-Length: 105
	Line 854973: FINE: http-outgoing-5300 >> Host: 127.0.0.1:7058
	Line 854975: FINE: http-outgoing-5300 >> Connection: Keep-Alive
	Line 854977: FINE: http-outgoing-5300 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.7.0_79)
	Line 854979: FINE: http-outgoing-5300 >> Accept-Encoding: gzip,deflate
	Line 854981: FINE: http-outgoing-5300 >> "POST /hub/session HTTP/1.1[\r][\n]"
	Line 854983: FINE: http-outgoing-5300 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
	Line 854985: FINE: http-outgoing-5300 >> "Content-Length: 105[\r][\n]"
	Line 854987: FINE: http-outgoing-5300 >> "Host: 127.0.0.1:7058[\r][\n]"
	Line 854989: FINE: http-outgoing-5300 >> "Connection: Keep-Alive[\r][\n]"
	Line 854991: FINE: http-outgoing-5300 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.7.0_79)[\r][\n]"
	Line 854993: FINE: http-outgoing-5300 >> "Accept-Encoding: gzip,deflate[\r][\n]"
	Line 854995: FINE: http-outgoing-5300 >> "[\r][\n]"
	Line 854997: FINE: http-outgoing-5300 >> "{"desiredCapabilities":{"platform":"ANY","browserName":"firefox","version":""},"requiredCapabilities":{}}"
	Line 854999: FINE: http-outgoing-5300 << "HTTP/1.1 200 OK[\r][\n]"
	Line 855001: FINE: http-outgoing-5300 << "content-type: application/json; charset=UTF-8[\r][\n]"
	Line 855003: FINE: http-outgoing-5300 << "connection: close[\r][\n]"
	Line 855005: FINE: http-outgoing-5300 << "content-length: 422[\r][\n]"
	Line 855007: FINE: http-outgoing-5300 << "server: httpd.js[\r][\n]"
	Line 855009: FINE: http-outgoing-5300 << "date: Fri, 17 Jun 2016 01:11:19 GMT[\r][\n]"
	Line 855011: FINE: http-outgoing-5300 << "[\r][\n]"
	Line 855013: FINE: http-outgoing-5300 << HTTP/1.1 200 OK
	Line 855015: FINE: http-outgoing-5300 << content-type: application/json; charset=UTF-8
	Line 855017: FINE: http-outgoing-5300 << connection: close
	Line 855019: FINE: http-outgoing-5300 << content-length: 422
	Line 855021: FINE: http-outgoing-5300 << server: httpd.js
	Line 855023: FINE: http-outgoing-5300 << date: Fri, 17 Jun 2016 01:11:19 GMT
	Line 855025: FINE: http-outgoing-5300 << "{"name":"newSession","sessionId":"910ed11c-ea78-4865-9f3e-804bf2bc2d94","status":0,"value":{"cssSelectorsEnabled":true,"browserName":"firefox","handlesAlerts":true,"javascriptEnabled":true,"nativeEvents":false,"platform":"Linux","rotatable":false,"takesScreenshot":true,"version":"44.0.2","webStorageEnabled":true,"applicationCacheEnabled":true,"databaseEnabled":true,"locationContextEnabled":true,"acceptSslCerts":false}}"
	Line 855027: FINE: http-outgoing-5300: Close connection_

## Actual Behavior -
After we call driver.get("<some url>"),  intermittently it only launches Firefox but enters nothing, from the debug log, nothing is in response. As a result, the thread will hang there with the browser open, no url is entered, no session id is returned. 

	_Line 98671: FINE: http-outgoing-755: set socket timeout to 10800000
	Line 98679: FINE: http-outgoing-755 >> POST /hub/session HTTP/1.1
	Line 98681: FINE: http-outgoing-755 >> Content-Type: application/json; charset=utf-8
	Line 98683: FINE: http-outgoing-755 >> Content-Length: 105
	Line 98685: FINE: http-outgoing-755 >> Host: 127.0.0.1:7057
	Line 98687: FINE: http-outgoing-755 >> Connection: Keep-Alive
	Line 98689: FINE: http-outgoing-755 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.7.0_79)
	Line 98691: FINE: http-outgoing-755 >> Accept-Encoding: gzip,deflate
	Line 98693: FINE: http-outgoing-755 >> "POST /hub/session HTTP/1.1[\r][\n]"
	Line 98695: FINE: http-outgoing-755 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
	Line 98697: FINE: http-outgoing-755 >> "Content-Length: 105[\r][\n]"
	Line 98699: FINE: http-outgoing-755 >> "Host: 127.0.0.1:7057[\r][\n]"
	Line 98701: FINE: http-outgoing-755 >> "Connection: Keep-Alive[\r][\n]"
	Line 98703: FINE: http-outgoing-755 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.7.0_79)[\r][\n]"
	Line 98705: FINE: http-outgoing-755 >> "Accept-Encoding: gzip,deflate[\r][\n]"
	Line 98707: FINE: http-outgoing-755 >> "[\r][\n]"
	Line 98709: FINE: http-outgoing-755 >> "{"desiredCapabilities":{"platform":"ANY","browserName":"firefox","version":""},"requiredCapabilities":{}}"_

## Steps to reproduce -
Check the logic in this method
org.openqa.selenium.remote.RemoteWebDriver.execute(String, Map<String, ?>)

/*  772 */       if (response == null) {
/*      */         return null;
/*      */       }

If we intermittently cannot get response from the browser side, for example, when the browser side is busy  or some unexpected things happen.

1. Do we suppose to throw exception instead of doing nothing?
2. Is there any way we can avoid no response? Or retry to get the browser connected?
3. Is there any way we can see why the browser side has no response?

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
