### ISSUE TITLE
FirefoxDriver does not click on an element that disappears on click

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#2312]
## Meta -

OS:  Any, but I've reproduced on Linux and Mac
Selenium Version:  2.53
Browser:  Firefox
Browser Version:  46.0.1
## Expected Behavior -

In the test below, the driver should click the "Month" dropdown and then click "April" (language may vary depending on your location).
## Actual Behavior -

The `mousedown` event is fired, but `click` and `mouseup` are not fired on the `.goog-menuitem` div.

I'm aware that I should use Marionette instead, but we're trying to live with FirefoxDriver until FF48 arrives.

This click did work correctly before @barancev 's 0eec81da52ba4dfb16de590e6e82ebafa452416f and 5eb8c3ec6c16aeafc4aa57e02c62133821ef452a from 8 months ago. The latter commit addresses disappearing elements, but doesn't seem to solve this case for some reason.
## Steps to reproduce -

I'm sorry to say I haven't been able to reproduce this on a self-contained example. Hopefully seeing it reproduce on a public-facing site is somewhat helpful.

```
import selenium
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Remote(
    command_executor='http://localhost:4444/wd/hub',
    desired_capabilities=DesiredCapabilities.FIREFOX.copy())

try:
    driver.get('https://accounts.google.com/SignUp')

    month_div = driver.find_element_by_css_selector('#BirthMonth div')
    month_div.click()
    months = driver.find_elements_by_css_selector('.goog-menuitem')
    months[3].click()  # April
finally:
    raw_input('Press Enter to quit')
    driver.quit()
```

**Comment by juangj** [comment]
Oh yeah, fun addendum: if the Firefox window *does not* have focus when the click occurs, then the click actually succeeds, and "April" is displayed in the box, as it should be.

**Comment by juangj** [comment]
Ah, here we go. The problem occurs if a focusable parent of the click target hides itself (and its child) when blurred, like this:

```html
<html>
<body>
<div id="parent" tabindex="0" style="width: 100px; height: 100px; border: 1px solid blue">
  <div id="child" style="width: 40px; height: 40px; border: 1px solid red">
    child
  </div>
  parent
</div>

<script>
var parent = document.getElementById('parent');
parent.addEventListener("blur", function() {
  parent.style.display = "none";
});
</script>
</body>
</html>
```

In a real browser, `#parent` remains the active element, and no blur event is fired. [The browser atoms, however](https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/device.js#L454), blur `#parent` first before attempting to focus `#child`.

**Comment by swistak** [comment]
I'm not sure if it's related, but I'm having similar problem with the Marionette. I cannot select the option inside a select in any way.

**Comment by titusfortner** [comment]
@swistak your problem might be [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1255951)

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
