### ISSUE TITLE
Getting-Started is not advising to get htmlunit from its own repository, after 2.53

### ISSUE THREAD

**Issue by cpeosphoros** [SeleniumHQ/selenium#2313]
Sorry if it's not the correct place for this. It's about documentation and the contributing guidelines are not clear about where to post this kind of issue.

## Meta -
OS:  

Linux Mint 17.3

Browser:  Chrome

## Expected Behavior -
https://github.com/SeleniumHQ/selenium/wiki/Getting-Started should advise to get htmlunit from its own repository, after 2.53

## Actual Behavior -
https://github.com/SeleniumHQ/selenium/wiki/Getting-Started is not advising to get htmlunit from its own repository, after 2.53

## Steps to reproduce -

Not applicable.

**Comment by lukeis** [comment]
This has been fixed in 3.0.1 of selenium, htmlunit is bundled in the standalone again and available as a maven dependency.
