### ISSUE TITLE
Identifying elements

### ISSUE THREAD

**Issue by ponnusamybe** [SeleniumHQ/selenium#2314]
I am working on automating web application. Developers used angular js and protractor and single page concept. None of the elements has unique identifier. I tried using path, css, etc. but the test is not running consistent. 

I am here to check if there is any way to identify these kind of dynamic elements which are developed using angular js.

**Comment by im-zeeshan** [comment]
Share some examples.
1. What is element you are trying to perform action on?
2. It's DOM structure?
3. What have you already tried?
4. What errors are you getting?

Also I would suggest you ask such questions on StackOverflow.com as well.

**Comment by lukeis** [comment]
For questions please ask on selenium-users Google group.

**Comment by jleyba** [comment]
I believe Protractor provides a bunch of custom locators for finding
elements based on angular directive (not sure what the correct terminology
is here). Check their API docs/guides for more info
