### ISSUE TITLE
Chrome driver is not working in Jenkins build for Maven project

### ISSUE THREAD

**Issue by viv1ag** [SeleniumHQ/selenium#2315]
## Meta
OS:  Windows 8.1
Selenium Version:  2.53.0
Browser:  Chrome

## Problem
I have very simple script (in Maven project) that is to navigate url: google.com. Script is working fine on Firefox & IE using Jenkins build however it's not working with Chrome driver. However I am able to run same script on Chrome on my local system using Eclipse.

Project code: [https://github.com/viv1ag/gittest.git]

Please let me know if you need any other information to debug the issue.

## Jenkins build log
![testgithub 8 console jenkins 2016-06-20 11-10-57](https://cloud.githubusercontent.com/assets/878291/16184177/b7b749ec-36d7-11e6-9e92-83cc23f5d5a9.png)

**Comment by gollogly** [comment]
Hi there,

I have noticed the java version is java 7 in the jenkins job output. Have you tried with java 8 on Jenkins as the README on github specifices that JAVA 8 is required as a minimum. It might be worth comaring your local jdk to rule this out as a problem

Cheers

**Comment by lukeis** [comment]
we don't support Jenkins here, nor do we support chromedriver directly (that is done on the chromedriver project).
