### ISSUE TITLE
Expose the components of Color

### ISSUE THREAD

**Issue by billccn** [SeleniumHQ/selenium#2317]
The `org.openqa.selenium.support.Color` class currently only does conversion, but I want to use it to extract the colour components as well.

Can the RGB fields in this class be exposed? Better yet, can a method also be added to return a `java.awt.Color`?

**Comment by lukeis** [comment]
added in https://github.com/SeleniumHQ/selenium/commit/02e40f1aec655fdd9f5227c63a2533f0b38e1402
