### ISSUE TITLE
Unable to pass args to the ChromeDriverOptions binary

### ISSUE THREAD

**Issue by bharatp10** [SeleniumHQ/selenium#2322]
OS: Win server 2012 r2
Browser: Chrome

Issue: I am using ChromeDriverOptions to launch my executable file.  I am able to launch successfully and perform respective actions.

I am having issue in passing args ("-enableDevTools"), inorder to enable the menu itme ToggleDevTools for further debugging while testing the application transaction behavior.

Manually i could launch the application from command prompt by passing the respective args.
For ex: C:\Build>installer.exe -enableDevTools

But the same thing when i try passing the args through the ChromeDriverOptions, i dont see the respective option enabled. I feel that i am missing something here. Need some help on it.

Code which i am trying was:

System.setProperty("webdriver.chrome.driver", "C:\\Jar-Files\\chromedriver-2.20.exe");
					
			Map<String, Object> chromeOptions = new HashMap<String, Object>();
			chromeOptions.put("binary", "C:\\Build\\win32\\installer.exe");
						
			//chromeOptions.put("args", Arrays.asList("C:\\Build\\vcsa-ui-installer\\win32\\"));
			
			chromeOptions.put("-args", Arrays.asList("–enableDevTools"));
				

			DesiredCapabilities capabilities = new DesiredCapabilities();
			ChromeOptions options = new ChromeOptions();
			options.addArguments("enableDevTools");
			capabilities.setCapability("chromeOptions", chromeOptions);
			capabilities.setCapability("args", options);
			capabilities.setBrowserName("chrome");

The following doesn't throw any error for passing the args, and still doesnt enable the respective options.

-B

**Comment by lukeis** [comment]
you can not automate / have dev tools open when using chromedriver

https://sites.google.com/a/chromium.org/chromedriver/help/devtools-window-keeps-closing
