### ISSUE TITLE
#2110 ISSUE RETEST : Unable to open Firefox 47 using Marionette WebDriver

### ISSUE THREAD

**Issue by SharmaM25** [SeleniumHQ/selenium#2323]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.0
Browser:  
Firefox 
Browser Version:  
47(64-bit) 

## Steps to reproduce -
1) Download the latest version of your system compatible geckodriver executable file from path --> https://github.com/mozilla/geckodriver/releases
2) Extract and rename geckodriver executable file to wires.exe
3) Update the path variable on Windows os to add full directory path to the executable (In my case, i have updated path variable with - C:\Sharma\Study\Softwares\IE_GC_Updates  , where wires.exe file is present)
4) Updating the tests to use Marionette
<< I have updated my scripts as below-

        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
    	capabilities.setCapability("marionette", true);
    	WebDriver driver = new FirefoxDriver(capabilities);
    	driver.manage().window().maximize();
    	driver.get("http://www.ebay.com/");
    	driver.findElement(By.id("gh-ac")).sendKeys("Camera");
    	driver.findElement(By.id("gh-btn")).click();
    	driver.findElement(By.linkText("Daily Deals")).click();

**Comment by lukeis** [comment]
if you're using geckodriver / wires / marionette, then you'll likely need to log an issue with mozilla first:

https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If there's an issue in the selenium project (which I don't see one by what you've shown here) then they'll likely request a new issue made here again with details on what is wrong with the selenium project.

**Comment by rghetu** [comment]
PLease use latest webdriver selenium-webdriver.2.5.4 it is not available yet on seleniumhq but search for it.
