### ISSUE TITLE
My pictures

### ISSUE THREAD

**Issue by sassyjava-12** [SeleniumHQ/selenium#2326]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by sassyjava-12** [comment]
Cause my pictures  of my mother, that has past away are in those pictures and I would like to get all my pictures that's all I want are my pictures. Please And Thank you 

Amy Powers

**Comment by lukeis** [comment]
really don't know what you're asking here... but you've logged a selenium bug and what you've said so far is not an issue with the selenium project
