### ISSUE TITLE
scrollLeft is not working in internet explorer

### ISSUE THREAD

**Issue by eloraparija** [SeleniumHQ/selenium#2328]
## Meta -

OS:  Windows 7
Selenium Version:  2.35
Browser:   Internet Explorer 11

scrollLeft for customized scrollbar is not working in internet explorer .

((JavascriptExecutor)driver).executeScript("arguments[0].scrollLeft =200;",webElement);

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided, just an unfounded statement.
