### ISSUE TITLE
WebDriver: Firefox has stopped working

### ISSUE THREAD

**Issue by dfdf-santosh** [SeleniumHQ/selenium#2329]
## Meta -
OS:  
Windows 10

Selenium Version:  
With both the versions of Pytractor
Pytractor-0.2.1
pytractor-0.2.2.dev1-py2.7.egg-info
 
Browser:  
Mozilla Firefox - 47.0

Browser Version:  
47.0 and 41.0

## Expected Behavior -
Should open the browser and navigate to the url mentioned.

## Actual Behavior -
"Firefox has stopped working

A problem caused the program to stop working correctly. Windows will clos the program and notify you if a solution is available."

## Steps to reproduce -
1. Install pytractor in Anaconda 2 environment.
[Anaconda2] C:\Users\Santosh_2>pip install https://github.com/kpodl/pytractor/zipball/master

2. After successful installation of pytractor
[Anaconda2] C:\Users\Santosh_2>ipython

3. It will open a python prompt.
4. Run the below commands

In [1]: from pytractor.webdriver import Firefox
In [2]: driver = Firefox('https://www.google.co.in/')

**Result:-**
error                                     Traceback (most recent call last)
<ipython-input-2-0ec8181c9633> in <module>()
----> 1 driver = Firefox('https://www.google.co.in/')

**Comment by dfdf-santosh** [comment]
Anaconda 2 has installed Python 2.7 by default.

**Comment by p0deje** [comment]
Firefox 47 is not supported by old Selenium FirefoxDriver.

See http://www.theautomatedtester.co.uk/blog/2016/selenium-webdriver-and-firefox-47.html for details.
