### ISSUE TITLE
Code works fine locally, but gives error when executed on a linode server

### ISSUE THREAD

**Issue by mojoboss** [SeleniumHQ/selenium#2330]
OS:  Ubuntu 14.04.4 LTS (GNU/Linux 4.5.3-x86_64-linode67 x86_64)

Selenium Version:  2.53.5

Browser:  Firefox

Browser Version:  45.0

I'm getting the following error when I'm trying to run my script on this linode server. Everything works fine in my local environment. I've tried 'wait' in case elements of webpage appear late but nothing works. I'm running Firefox in headless mode.
<b>Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmp1nOSXC/extensions/fxdriver@googlecode.com/components/driver-component.js:10770)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmp1nOSXC/extensions/fxdriver@googlecode.com/components/driver-component.js:625)
</b>

**Comment by lukeis** [comment]
we don't support "headless" firefox. One needs to provide an X display of somekind (like xvfb). There's also not quire enough information for us to go on here. If there's still an issue, please provide some clear steps to reproduce. Probably including how to setup a VM in the same configuration you are using.

Also if you haven't already, please ask about this issue on the selenium-users list:
https://groups.google.com/forum/#!forum/selenium-users
