### ISSUE TITLE
Session expiry issue when clicked on login button through automation by webdriver

### ISSUE THREAD

**Issue by nitishk2016** [SeleniumHQ/selenium#2334]
## Meta -
OS:  
 Windows 7
Selenium Version:  
 Selenium Webdriver
Browser:  

Browser Version:  
 IE 11( 32 bit)

## Steps to reproduce -
 This code is attached in document
[Session expire issue.docx](https://github.com/SeleniumHQ/selenium/files/327136/Session.expire.issue.docx)
[Logs_Session expiry issue.txt](https://github.com/SeleniumHQ/selenium/files/327137/Logs_Session.expiry.issue.txt)

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
