### ISSUE TITLE
firfox getting crash just after opening once

### ISSUE THREAD

**Issue by AkhileshCh** [SeleniumHQ/selenium#2337]
## Meta -
OS:  
< OSX captain >
Selenium Version:  
< 2.53.0, Webdriver, etc >
Browser:  
<  Firefox >

Browser Version:  

## Steps to reproduce -
< try to run a Selenium webdriver script on mac os (captain) It is generated very easly>

**Comment by lukeis** [comment]
Likely a duplicate of #2110
