### ISSUE TITLE
Getting:

### ISSUE THREAD

**Issue by pgandarillas** [SeleniumHQ/selenium#2339]
## Meta -
OS:  
Windows 10
Selenium Version:  2.53.0, IDE: RubyMine
Browser:  Firefox

Firefox 47? Did you search for issues first? You're likely logging a duplicate bug of #2110 

I tried all what was suggested in #2110. I added marionette to my ruby bin path and follow the steps in this page here: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

Now I'm getting: unable to connect to Mozilla geckodriver 127.0.0.1:4444

Browser Version:  

## Steps to reproduce -
I just initialized my automated testing with cucumber command

**Comment by AutomatedTester** [comment]
a reproducible test case requires a sample url or html along with the code to generate the exception. We can try to help / reopen this issue when that is provided. We have been testing with Marionette so there are other details missing that can help us help you

**Comment by tk5446** [comment]
@pgandarillas could you please post the fix here if you found one? I am getting the same error.
