### ISSUE TITLE
Add IWebDriver instance reference to IWebElement

### ISSUE THREAD

**Issue by aedwill** [SeleniumHQ/selenium#2341]
## Meta -
OS:  Windows Server 2012
Selenium Version:  2.53.0
Browser:  N/A

Browser Version:  Any

## Expected Behavior -
Be able to get the IWebDriver instance from an IWebElement

## Actual Behavior -
There is no way to get to the IWebDriver instance from an IWebElement

**Comment by jimevans** [comment]
Of course there is.

    // Assume element is a valid IWebElement.
    // NOTE: Null check for failure of the cast omitted for brevity.
    IWrapsDriver wrapper = element as IWrapsDriver;
    IWebDriver driver = wrapper.WrappedDriver;
