### ISSUE TITLE
[Java] FirefoxDriver does not handle clicking multi-select options when using Action builder

### ISSUE THREAD

**Issue by jbrower2** [SeleniumHQ/selenium#2342]
## Meta -

OS:  Windows 10/Linux Mint
Selenium Version:  2.53.0
Browser:  Firefox

Browser Version:  46.0.1
## Expected Behavior -

Clicking on any `<option>` of a multi-select `<select>` element should select only that option (all others should not be selected). The behavior of Shift+Click also does not work.
## Actual Behavior -

Each subsequent option clicked simply toggles whether it is selected or not. For example, if you click on option A, then option C, both option A and C will be selected afterward, where only C should actually be selected. This observed behavior is what I would expect from performing a Ctrl+Click.
Note that the actual behavior is the same regardless of whether you add the SHIFT modifier or not.
## Steps to reproduce -

HTML example:
`<select multiple>`
`<option id="optA">A</option>`
`<option id="optB">B</option>`
`<option id="optC">C</option>`
`</select>`

For a normal click:
`new Actions(driver).click(optA).perform();`
`new Actions(driver).click(optC).perform();`
`// I would expect this to select A, then when it clicks on C, A becomes de-selcted and only C is selected`
`// It actually selects A and C (but not B)`

For a shift-click:
`new Actions(driver).click(optA).perform();`
`new Actions(driver).keyDown(Keys.SHIFT).click(optC).keyUp(Keys.SHIFT).perform();`
`// I would expect this to select A, then when it clicks on C, all three options become selected`
`// It actually selects A and C (but not B) like the normal click`

**Comment by jbrower2** [comment]
This is still an issue, and is not just in <select> elements, all modified clicking using Actions.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
