### ISSUE TITLE
'^', '+', and '|' not escaped in exported regex's

### ISSUE THREAD

**Issue by blaken** [SeleniumHQ/selenium#2343]
## Meta

OS:  Fedora 23
Selenium Version:  Selenium IDE 2.9.0
Browser:  Firefox 47
## Expected Behavior -

Exported Java/C#/Ruby/Python test cases should properly escape all special characters in a shell-style glob search patterns--as for verifyText() and similar commands.
## Actual Behavior -

Exported test cases in Java/C#/Ruby/Python do _not_ escape the characters `^`, `+`, or `|` in shell-style glob search patterns.
## Steps to reproduce -

In Selenium IDE, add the following command to a new Test Case:

**Command:** `verifyText`
**Target:** `css=p`
**Value:** `+|^*`

Now select `File > Export Test Case As...` and choose, for example, `Java / JUnit / WebDriver`. 

In the exported file, you will find the line

`assertTrue(driver.findElement(By.cssSelector("p")).getText().matches("^+|^[\\s\\S]*$"));`

which is incorrect and should be

`assertTrue(driver.findElement(By.cssSelector("p")).getText().matches("^\\+\\|\\^[\\s\\S]*$"));`

This same behavior can be observed with any of the export formats, with minor differences for language-specific syntax. 
### Python example

Exporting as `Python 2 / unittest / WebDriver` produces the following line:

`try: self.assertRegexpMatches(driver.find_element_by_css_selector("p").text, r"^+|^[\s\S]*$")`

which should be

`try: self.assertRegexpMatches(driver.find_element_by_css_selector("p").text, r"^\+\|\^[\s\S]*$")`

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
