### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

### ISSUE THREAD

**Issue by nivia88** [SeleniumHQ/selenium#2345]
I am having Firefox with version 48.0b1 and Selenium with version 2.53.
When I tried to open firefox browser with specified url. only the browser is getting opened without the url.

I am getting following error as
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

Please help how to resolve this issue

**Comment by nivia88** [comment]
I am running firefox and Selenium's latest version.

**Comment by nivia88** [comment]
No comments

**Comment by dPeS** [comment]
which java version?

**Comment by AutomatedTester** [comment]
We don't support beta versions unfortunately. I have approved the fix for #2110 and there will be a release _soon_

**Comment by nivia88** [comment]
I am using java version 8 update 91

Thanks,
Niveda

**Comment by dPeS** [comment]
ubuntu 16.04, kvm instance maybe?
