### ISSUE TITLE
Slow Sendkeys IE11 Windows Server 2012 R2 with 32bit IEDriverServer over Grid

### ISSUE THREAD

**Issue by neeasade** [SeleniumHQ/selenium#2347]
## Meta -
OS:  Windows Server 2012 R2 (64 bit)
Selenium Version:  2.53, .NET bindings via nuget
Browser:  Internet explorer via IEDriverServer 32bit
Browser Version:  11

## Expected Behavior -
Sendkeys speed be at normal speed/near equivalent to Firefox/Chrome webdrivers. 

## Actual Behavior -
Sendkeys speed is very slow, one key every ~8 seconds

## Steps to reproduce -
- Setup Windows Server 2012 R2 as per configuration instructions in https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver
    - This includes the registry values TabProcGrowth and BFCache
- Configure a selenium node/hub
    - Was using this node configuration (with IEDriverServer 32 bit in path): https://ptpb.pw/t_k4/json
        - edit: This bug was also present with this config.json: https://ptpb.pw/zV5H/json
    - default hub configuration.
- Launch IE driver on grid (I'm launching with ensureCleanSession)
- try to enter text at https://framework.civicplus.com/admin, in the username field, note slow input.
     - note: this issue is visible on any website/text field, this is just the one pertinent to our testing. 

Here's an attached log from the node: https://ptpb.pw/YTpH . I had stopped the driver/test after 3-4 characters were entered. 

edit: I intend to try and reproduce this in a windows 7 machine to see if it's a configuration issue that I've overlooked somehow -- I've done a fair amount of searching on this and seen that the accepted/reported solution is to use the 32bit version of IE/IEDriverServer. Filing this issue as a result of that not working.

**Comment by JustinPhlegar** [comment]
@neeasade Are you trying to run IE32 in private mode? What happens when you set TabProcGrowth to "medium"?

**Comment by neeasade** [comment]
@JustinPhlegar 
Currently launching with the following:
```cs
nodeTargetCapabilities = DesiredCapabilities.InternetExplorer();
nodeTargetCapabilities.SetCapability("ie.ensureCleanSession", true);
```

Also tried the above in combination with all combinations of these capabilities, just to see if that would change anything:
``` cs
nodeTargetCapabilities.SetCapability("ie.forceCreateProcessApi", true);
nodeTargetCapabilities.SetCapability("ie.browserCommandLineSwitches", "-private");
```

Ah, was not aware there were options for `TabProcGrowth` other than {0,1}. ([ref](https://blogs.technet.microsoft.com/doxley/2009/10/14/putting-iexplore-exe-on-a-diet/)). if I'm only running one tab in one instance of IE (as in the above), it shouldn't be relevant, right? I will set it to "medium" and check.

**Comment by neeasade** [comment]
Okay, so for both the approaches in wiki recommended for multiple IE instances: 

- If I go with approach one (the -private flag and forceCreateProcessApi, no ensureCleanSession, TabProcGrowth set to "medium" in this case), IE doesn't launch. node debug log: https://ptpb.pw/G47A

- If I go with approach two (ensureCleanSession) IE launches, and then I get initial issue mentioned above. 

This are both with the 32bit IEDriverServer in path with the node config: https://ptpb.pw/t_k4/json

**Comment by jimevans** [comment]
You'll want to provide a log file from `IEDriverServer.exe` on the node for anyone to be able to look further at this issue. But almost certainly this is because of a "bitness" mismatch between the executable and the browser "content process." See [this blog post]( http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html) for a technical explanation of what's almost certainly happening. If you use the 64-bit executable, what happens?

**Comment by neeasade** [comment]
>  If you use the 64-bit executable, what happens?

this with `ensureCleanSession` to true, sendkeys works at expected speeds.... I hadn't run the 64 bit IEServerDriver at any point in this (due to what I found searching about 32 bit I just assumed). agh, thank you @jimevans.
