### ISSUE TITLE
[NodeJS] adding experimental chrome options

### ISSUE THREAD

**Issue by m-sch** [SeleniumHQ/selenium#2349]
## Meta
OS: OSX 10.11.4
Selenium Version:  latest NodeJS selenium-webdriver/chrome
Browser: Chrome

I saw here:
https://github.com/seleniumhq/selenium/issues/1501
that notifications are in the feature request list, so I wanted to deactivate the notification feature in chrome using the chrome experimental options in NodeJS. Nevertheless it does show the notification. Perhaps this feature isn't supported atm.

## Expected Behavior
does not show notifications
## Actual Behavior
does show the notifications

I've tried the following:

```javascript
var options = new chrome.Options();
options.addArguments("profile.default_content_setting_values.notifications", "2");
var driver = new webdriver.Builder().withCapabilities(options.toCapabilities()).build();
```
The following code works in Java.
```java
Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("profile.default_content_setting_values.notifications", 2);
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("prefs", prefs);
WebDriver driver = new ChromeDriver(options);
```

**Comment by jleyba** [comment]
[addArguments](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Options.html#addArguments) sets command line switches for the browser.

I believe you want to use [setUserPreferences](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Options.html#setUserPreferences)

```javascript
var options = new chrome.Options();
options.setUserPreferences({'profile.default_content_setting_values.notifications': 2});
var driver = new webdriver.Builder().withCapabilities(options.toCapabilities()).build();
```

**Comment by carledriss** [comment]
I have this configuration
but it is not working.
```javascript
            var options = new chrome.Options()
                .setUserPreferences({'profile.default_content_settings.popups': '0'})
                .setUserPreferences({'profile.default_content_setting_values.notifications': '2'})
                .addExtensions('./myextension.crx');

            var driver = new webdriver.Builder()
                .withCapabilities(options.toCapabilities())
                .build();
```

![selection_027](https://cloud.githubusercontent.com/assets/3298869/17330800/42f54e98-5896-11e6-9817-b618d99cde29.png)

In my case I want to *allow*

Let me know if you know how to configure that.

**Comment by lucaswxp** [comment]
I believe the idiom has changed to:

```
    var caps = webdriver.Capabilities.chrome();

    caps.set('dns-prefetch-disable', '0')

    driver = new webdriver.Builder()
        .forBrowser('chrome')
        .withCapabilities(caps)
        .build();
```

Is that correct?

**Comment by Saurabh-Bishnoi** [comment]
****try this  works for me .****
var selenium = require('selenium-webdriver');
var capabilities = selenium.Capabilities.chrome();
            capabilities.set('chromeOptions',{
                'args': ['--headless', '--disable-gpu']
            })
var builder = new selenium.Builder().forBrowser("chrome").withCapabilities(capabilities).build();
