### ISSUE TITLE
3.0b - Incorrect version reported in Console

### ISSUE THREAD

**Issue by danielmaddern** [SeleniumHQ/selenium#2358]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.0b
Browser:  
N/A

Browser Version:  
NA

## Expected Behavior -
Grid console reports a version of  v3.0
## Actual Behavior -
Selenium Grid Console v.2.42.2
## Steps to reproduce -
java -jar selenium-server-standalone-3.0.0-beta-5d363.jar -role hub
Nav to localhost:4444 and click console.

**Comment by shs96c** [comment]
This is now fixed. Promise.
