### ISSUE TITLE
Selenium 3: Time and Version of Selenium 3 Beta Jar is Incorrect

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2359]
## Meta -
OS:  Win 7

Selenium Version:  Selenium

Browser:  

Browser Version:  

## Actual Behavior -
console displays version: '2.42.2', revision: '75f266f', time: '2014-07-30 09:11:33'
JAR METAINF also displays this information

**Comment by shs96c** [comment]
This has now been fixed as of f56924e5d6abac2e40065bf01b18174cb7a8d230
