### ISSUE TITLE
Selenium 3: Firefox(Marionette) Sessions doesn't run in Isolation

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2361]
## Meta -
OS:  Win 7 64

Selenium Version:  Selenium 3 Beta

Browser:  Firefox 47

Browser Version:  

## Expected Behavior -
Browser Sessions should run in isolation independent of each other
## Actual Behavior -
When we run new Test it reuses the previously opened Session and also launches another firefox session with only FireFox first use Page
## Steps to reproduce -

Run your Test
Stop your Test in between - Don't close Session
Re run Test 
it will use already opened Session and launches a browser session Firefox first use page

**Comment by lukeis** [comment]
I believe this is fixed within geckodriver. Please report a new issue with concise reproducible steps if still an issue.
