### ISSUE TITLE
Selenium 3 : Virtual - FileUtils class not supported in Selenium 3

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2362]
## Meta -
OS:  Win 8

Selenium Version:  Selenium 3 Beta

Browser:  NA

Browser Version:  NA

## Expected Behavior -
FileUtils class should be available in selenium jars.

## Actual Behavior -
FileUtils class not available in selenium jars.
## Steps to reproduce -

Try to use FileUtils class in any project

**Comment by lukeis** [comment]
I'm assuming you're talking about org.apache.commons.io.FileUtils ?

commons-io is a transitive dependency, you shouldn't be relying on selenium providing it for you and you should declare it as a separate library / dependency for your project.

it looks like htmlunit transitive dependencies aren't being included and we'll need to check on that.

**Comment by naukri-engineering** [comment]
Yes..org.apache.commons.io.FileUtils

**Comment by p00j4** [comment]
yes @lukeis I too see the same
![image](https://cloud.githubusercontent.com/assets/6470509/16355450/b92741fa-3ad4-11e6-8017-8f596c10730b.png)

**Comment by jleyba** [comment]
The HtmlUnitDriver is no longer published with the main Selenium artifact. Update your [maven dependencies](https://github.com/SeleniumHQ/htmlunit-driver):

```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>htmlunit-driver</artifactId>
    <version>2.21</version>
</dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-support</artifactId>
    <version>2.53.0</version>
</dependency>
```

Also, if you are using `org.apache.commons.io.FileUtils`, you should update your pom.xml to include commons-io directly instead of getting it transitively through Selenium.
