### ISSUE TITLE
Selenium 3 : Virtual - org.apache not compatible with selenium 3

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2363]
## Meta -
OS:  Win 8

Selenium Version:  Selenium Beta 3

Browser:  NA

Browser Version:NA  
 

## Expected Behavior -
org.apache should be compatible with selenium 3

## Actual Behavior -
org.apache not compatible with selenium 3
## Steps to reproduce -

Try to use org.apache in any project

**Comment by lukeis** [comment]
this implies you are using third party dependencies (apache commons libraries) and you should be explicitly including them in your project.

Closing this of favor of tracking the issue for not having htmlunit transitive dependencies included (which will likely fix this issue also) #2362
