### ISSUE TITLE
Selenium 3 : Virtual - org.bouncycastle class not compatible with selenium 3

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2364]
## Meta -
OS:  Win 8

Selenium Version:  Selenium 3

Browser:  NA

Browser Version:  NA

## Expected Behavior -
org.bouncycastle class not compatible with selenium 3

## Actual Behavior -
org.bouncycastle class should be compatible with selenium 3
## Steps to reproduce -
Try to use org.bouncycastle class in any project

**Comment by jleyba** [comment]
What do you mean by "not compatible"?

Not found on the classpath? Please provide more detail on the exact problem (this and other bugs you've filed)

**Comment by lukeis** [comment]
closing this as a duplicate issue of #2362
