### ISSUE TITLE
Selenium 3 : Virtual - Browser Window Restore's Down on execution of driver.manage().window().maximize(); function.

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2366]
## Meta -
OS:  Win 8.1

Selenium Version:  Selenium 3

Browser:  FF

Browser Version:  30

## Expected Behavior -
Browser Window should get maximized on execution of driver.manage().window().maximize(); function.

## Actual Behavior -
Browser Window Restore's Down on execution of driver.manage().window().maximize(); function.

## Steps to reproduce -
1) Try using driver.manage().window().maximize() function in any of your project.
2) Execute the script.

**Comment by lukeis** [comment]
are you really using Firefox 30?

I'm assuming that you're not using marionette / geckodriver.

**Comment by naukri-engineering** [comment]
Yes..FF 30.

We are using both marionette / geckodriver.

**Comment by lukeis** [comment]
FF 30 with marionette is not possible... can you come find me in the bug bash room?

**Comment by naukri-engineering** [comment]
Thanks for the info...Pls close the bug then.
