### ISSUE TITLE
Selenium 3: Proxy not working with Firefox Driver (Marionette)

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2368]
## Meta -
OS:  Win 7 64

Selenium Version:  3 Beta

Browser:  Firefox 47

Browser Version:  

## Expected Behavior -
Traffic should go through Specified Proxy
## Actual Behavior -
It is not using the Specified proxy and performing web Actions Directly
## Steps to reproduce -

Sample Code to reproduce

```
 String prx="localhost:3128";
	 
	  Proxy proxy = new Proxy();
	  proxy.setHttpProxy(prx).setFtpProxy(prx).setSslProxy(prx);
	  DesiredCapabilities des= new DesiredCapabilities();
	  des.setCapability(CapabilityType.PROXY,proxy);
	  
	driver = new FirefoxDriver(des);
```

**Comment by lukeis** [comment]
this would be a bug for mozilla / geckodriver. Please first try again with using [FirefoxNightly](https://nightly.mozilla.org/) to see if the problem still occurs, if it does you can then try to log a bug for a new issue with mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette
