### ISSUE TITLE
Click done but the related action never happens on phantomjs. Works with chrome.

### ISSUE THREAD

**Issue by bhuvnesh2703** [SeleniumHQ/selenium#2371]
## Problem:
A Button is selected correctly with the CSS selector used, and then a click is performed on it. The event is marked as done as seen in the selenium logs, however if successful a new page must be rendered which does not happen.
The same piece of code works in chrome.

## Environment:
WDIO version: v4.0.9
Node: 6.2.0
WDIO testrunning
Synchronous test.
selenium-server-standalone-2.53.0.jar

## Details
```bash
      CommonElements.clickNext();
      browser.saveScreenshot('test1.jpg');
      browser.pause(5000);
      CommonElements.clickConfirmationOk();
      browser.pause(5000);
      // On Page 3
      browser.saveScreenshot('test.jpg');
      CommonElements.clickComplete();
```

In the above code snippet
clickNext() opens up a popup which has 2 buttons Cancel and Ok.
clickConfirmationOk() should click on the Ok button and move on to the next page
clickComplete() marks the completion on the new page.

However, clickConfirmationOk() is succesful as per the logs and it moves on to clickComplete(). However it keeps waiting for the element to exist, but it never comes up as actually its still on the pop which shows Ok and Cancel.

The CSS selector used to identify the button is correct, as verified by getHTML and other css selectors tools online.

Code Snippet
```bash
    clickConfirmationOk: {
        value: function () {
            var okSelector = '.modal-footer .btn.btn-success';
            browser.waitForExist(okSelector);
            console.log(browser.getHTML(okSelector));
            browser.waitForEnabled(okSelector, 100000);
            browser.click(okSelector);
        }
    },
    clickComplete: {
        value: function () {
            var completeSelector = '#common-progress-page .btn.btn-success.pull-right';
            browser.waitForExist(completeSelector);
            console.log(browser.isEnabled(completeSelector));
            browser.waitForEnabled(completeSelector, 900000);
            browser.click(completeSelector);
        }
    }
```

## Logs
Selenium Logs https://gist.github.com/bhuvnesh2703/aec82bea06debf92f9a4f6e4da93c2ea:
Test Results Output: https://gist.github.com/bhuvnesh2703/076af36f5931c8fdae4a81db612bf4b7

**Comment by bhuvnesh2703** [comment]
any help is appreciated

**Comment by jleyba** [comment]
The ghostdriver (phantomjs' webdriver implementation) is not maintained by the Selenium project. This bug should be reported against ghostdriver directly:

https://github.com/detro/ghostdriver

**Comment by bhuvnesh2703** [comment]
Before the click on Ok
![before](https://cloud.githubusercontent.com/assets/10293569/16432381/88dc8458-3d39-11e6-9b9c-cf33dd7b0257.jpg)

**Comment by bhuvnesh2703** [comment]
After click on Ok. [Essentially stays on the same page]
![after](https://cloud.githubusercontent.com/assets/10293569/16432390/95db0b3e-3d39-11e6-97f5-e05c406a05b9.jpg)

Selenium logs says that the item is clicked.
```bash
14:05:36.810 INFO - Executing: [take screenshot])
14:05:37.053 INFO - Done: [take screenshot]
14:05:37.185 INFO - Executing: [find elements: By.cssSelector: .modal-footer .btn.btn-success])
14:05:37.197 INFO - Done: [find elements: By.cssSelector: .modal-footer .btn.btn-success]
14:05:37.206 INFO - Executing: [find element: By.cssSelector: .modal-footer .btn.btn-success])
14:05:37.217 INFO - Done: [find element: By.cssSelector: .modal-footer .btn.btn-success]
14:05:37.222 INFO - Executing: [click: 11 [[PhantomJSDriver: phantomjs on OS X 10.11 (0ce7b030-3d74-11e6-897d-cbd676d907c0)] -> css selector: .modal-footer .btn.btn-success]])
14:05:37.256 INFO - Done: [click: 11 [[PhantomJSDriver: phantomjs on OS X 10.11 (0ce7b030-3d74-11e6-897d-cbd676d907c0)] -> css selector: .modal-footer .btn.btn-success]]
14:05:37.266 INFO - Executing: [take screenshot])
14:05:37.389 INFO - Done: [take screenshot]
```

**Comment by joseph873** [comment]
WebElement element = driver.findElement(By.id("gbqfd"));
JavascriptExecutor executor = (JavascriptExecutor)driver;
executor.executeScript("arguments[0].click();", element);
