### ISSUE TITLE
Selenium 3: Information Request: org.openqa.selenium.server Class does not exist

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#2372]
## Meta -
OS:  Win 7 64

Selenium Version:  3 beta

Browser:  Firefox 47

Browser Version:  

## Actual Behavior -
org.openqa.selenium.server Class does not exist, Yes there is no Selenium Core but I think in the talk it was mentioned that Selenium core will be supported by emulators or something like that
This is more of a request how the Server part will be supported

**Comment by lukeis** [comment]
which class exactly?

**Comment by abhinav1708** [comment]
org.openqa.selenium.server.RemoteControlConfiguration
org.openqa.selenium.server.SeleniumServer

**Comment by lukeis** [comment]
in 3.0  the SeleniumServer was moved to:
org.openqa.selenium.remote.server.SeleniumServer

RemoteControlConfiguration is gone though. One now will need to configure a server if started up in-memory with a StandaloneConfiguration. There's also related classes depending on the mode you want to start your server up in: GridHubConfiguration, GridNodeConfiguration.
