### ISSUE TITLE
Selenium 3:Throwing error when running scripts with protractor-" Timed out waiting for the WebDriver server"

### ISSUE THREAD

**Issue by JeenaGeorge** [SeleniumHQ/selenium#2374]
![error_sel3](https://cloud.githubusercontent.com/assets/20137977/16355282/ec9e90ba-3acf-11e6-9aeb-7307995d7516.jpg)
## Meta -
OS:  
Windows 7 Enterprise 

Selenium webdriver used:  
selenium-server-standalone-latest (3).jar - Shared in the bug bash event

Test Tool - Protractor version:
Protractor 2.5.1

Browser:  
Google chrome

Steps to Reproduce

1. Place the latest selenium webdriver jar file under the Selenium folder of the protractor.
2. Enter the details in config also.
3. Now try running the Scripts. We are the below error 
Timed out waiting for the WebDriver server at http://xx.xx.xx.xx:xxxx/wd/hub

**Comment by jleyba** [comment]
Unable to reproduce with the latest build.
