### ISSUE TITLE
Selenium 3 : Virtual - FF version specified in FirefoxBinary should get opened while script execution

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2375]
## Meta -
OS:  Win 8.1

Selenium Version:  Selenium 3 Beta

Browser:  FF

Browser Version:  40

## Expected Behavior -
FF version specified in FirefoxBinary should get opened while script execution.

## Actual Behavior -
Script getting executed on Default/installed FF version instead of  FF version specified in FirefoxBinary.

## Steps to reproduce -

Used following code:

FirefoxProfile profile = new FirefoxProfile();
profile.setAcceptUntrustedCertificates(true); 
profile.setAssumeUntrustedCertificateIssuer(false);
System.setProperty("webdriver.gecko.driver", "D:\\jars\\geckodriver.exe");
driver = new FirefoxDriver(new FirefoxBinary(new File("D:\\MozillaVersions\\Mozilla Firefox40\\firefox.exe")), profile); 

## Stack Trace-
[TestNG] Running:
  
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
1466837249941 Marionette    DEBUG  Marionette enabled via build flag and pref
1466837250500 Marionette    INFO   Listening on port 2828
1466837251584 Marionette    DEBUG  Accepted connection conn0 from 127.0.0.1:50498
1466837251611 Marionette    TRACE  conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"browserName":"firefox","platform":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1466837251612 Marionette    CONFIG Changing capabilities: {"browserName":"Firefox","browserVersion":"47.0","platformName":"Windows_NT","platformVersion":"6.3","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160604131506","device":"desktop","version":""}
1466837252963 Marionette    DEBUG  loaded listener.js
1466837252966 Marionette    DEBUG  loaded listener.js
1466837253272 Marionette    TRACE  conn0 <- [1,1,null,{"sessionId":"22f7146d-4135-4223-a7d1-444260c2e660","capabilities":{"browserName":"Firefox","browserVersion":"47.0","platformName":"Windows_NT","platformVersion":"6.3","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160604131506","device":"desktop","version":"","command_id":1}}]
1466837253322 Marionette    TRACE  conn0 -> [0,2,"timeouts",{"ms":15000,"type":"implicit"}]
1466837253322 Marionette    TRACE  conn0 <- [1,2,null,{}]
1466837253335 Marionette    TRACE  conn0 -> [0,3,"maximizeWindow",{}]
1466837253352 Marionette    TRACE  conn0 <- [1,3,null,{}]
1466837253390 Marionette    TRACE  conn0 -> [0,4,"get",{"url":"https://testcompany.referralrecruit.com"}]
1466837255534 Marionette    TRACE  conn0 <- [1,4,null,{}]
1466837255548 Marionette    TRACE  conn0 -> [0,5,"findElement",{"using":"xpath","value":"//input[@id='emailId']"}]
1466837255554 Marionette    TRACE  conn0 <- [1,5,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"07ff304c-87a3-4eb4-a5dd-a004741e25f1","ELEMENT":"07ff304c-87a3-4eb4-a5dd-a004741e25f1"}}]
1466837255565 Marionette    TRACE  conn0 -> [0,6,"sendKeysToElement",{"id":"07ff304c-87a3-4eb4-a5dd-a004741e25f1","value":["a","n","k","u","r",".","g","u","p","t","a","1","@","n","a","u","k","r","i",".","c","o","m"]}]
1466837255567 Marionette    DEBUG  Element does not have an accessible object: id: emailId, tagName: INPUT, className: text-input ie7Fix width94
1466837255615 Marionette    TRACE  conn0 <- [1,6,null,{}]
1466837255630 Marionette    TRACE  conn0 -> [0,7,"findElement",{"using":"xpath","value":"//input[@id='pwd']"}]
1466837255633 Marionette    TRACE  conn0 <- [1,7,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"c73074ca-6912-461a-a9b2-086a96621afc","ELEMENT":"c73074ca-6912-461a-a9b2-086a96621afc"}}]
1466837255640 Marionette    TRACE  conn0 -> [0,8,"sendKeysToElement",{"id":"c73074ca-6912-461a-a9b2-086a96621afc","value":["1","2","3","4","5","6"]}]
1466837255642 Marionette    DEBUG  Element does not have a correct accessibility role and may not be manipulated via the accessibility API: id: pwd, tagName: INPUT, className: text-input ie7Fix width94
1466837255673 Marionette    TRACE  conn0 <- [1,8,null,{}]
1466837255678 Marionette    TRACE  conn0 -> [0,9,"findElement",{"using":"xpath","value":"//button[@id='loginBtn']"}]
1466837255680 Marionette    TRACE  conn0 <- [1,9,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"472d5d28-2443-4095-a650-dad1311beb41","ELEMENT":"472d5d28-2443-4095-a650-dad1311beb41"}}]
1466837255686 Marionette    TRACE  conn0 -> [0,10,"clickElement",{"id":"472d5d28-2443-4095-a650-dad1311beb41"}]
1466837255731 Marionette    TRACE  conn0 <- [1,10,null,{}]
JavaScript warning: https://normandy.cdn.mozilla.net/static/js/bundles/selfrepair-7575f6d27445b45bcffb.js, line 9825: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
1466837260750 Marionette    TRACE  conn0 -> [0,11,"refresh",{}]
1466837261908 Marionette    TRACE  conn0 <- [1,11,null,{}]
1466837265928 Marionette    TRACE  conn0 -> [0,12,"findElement",{"using":"xpath","value":"//div[@class='userDetails']//p"}]
1466837265944 Marionette    TRACE  conn0 <- [1,12,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"36955eed-550b-4909-876c-0e4165ee0dcc","ELEMENT":"36955eed-550b-4909-876c-0e4165ee0dcc"}}]
1466837265953 Marionette    TRACE  conn0 -> [0,13,"getElementText",{"id":"36955eed-550b-4909-876c-0e4165ee0dcc"}]
1466837265960 Marionette    TRACE  conn0 <- [1,13,null,{"value":"Test"}]
1466837265965 Marionette    TRACE  conn0 -> [0,14,"timeouts",{"ms":500,"type":"implicit"}]
1466837265965 Marionette    TRACE  conn0 <- [1,14,null,{}]
1466837265970 Marionette    TRACE  conn0 -> [0,15,"findElements",{"using":"xpath","value":"//nav[@id='navId']"}]
1466837265973 Marionette    TRACE  conn0 <- [1,15,null,[{"element-6066-11e4-a52e-4f735466cecf":"895f2b7a-1d71-4ec9-83bf-511263097d12","ELEMENT":"895f2b7a-1d71-4ec9-83bf-511263097d12"}]]
1466837265980 Marionette    TRACE  conn0 -> [0,16,"timeouts",{"ms":10000,"type":"implicit"}]
1466837265982 Marionette    TRACE  conn0 <- [1,16,null,{}]
1466837265991 Marionette    TRACE  conn0 -> [0,17,"quitApplication",{"flags":["eForceQuit"]}]
1466837265992 Marionette    TRACE  conn0 <- [1,17,null,{}]

**Comment by lukeis** [comment]
this would be a bug for mozilla, but as i noticed on other user's machines, if you attempt to launch the alternative firefox and check the version it will actually be the version of the 'installed firefox' on windows. You may need to uninstall firefox to get this to work appropriately.

**Comment by naukri-engineering** [comment]
Sure..will check and update.
