### ISSUE TITLE
Selenium 3 : Virtual - Webdriver unable to switchto iframe 

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2377]
## Meta -

OS:  Win 8.1

Selenium Version:  Selenium Beta 3

Browser:  FF

Browser Version:  45.0.2

## Expected Behavior -

Switchto iframe functionality should work.
## Actual Behavior -

Webdriver unable to switchto iframe and instead execute action on previous element.
## Steps to reproduce -

driver.switchTo().frame(driver.findElement(By.xpath(MailBody_Frame)));
try {
                  WebDriverWait wait = new WebDriverWait(driver, 10);
                  WebElement element = wait.until(ExpectedConditions
                              .visibilityOfElementLocated(mailBody_Txt));
            //    return element;
            } catch (Exception e) {
                  WebElement element = driver.findElement(mailBody_Txt);
                  safeJavaScriptClick(mailBody_Txt);
      //          return element;
            }
Element. getText();

**Comment by lukeis** [comment]
can you provide a way for someone else to reproduce the issue? example site? (jsfiddle?)

**Comment by naukri-engineering** [comment]
Iframe functionality can be checked on following url:-

http://toolsqa.com/iframe-practice-page/

On following locator path:-
//iframe[@id='IF1']

Code for same:-
driver.get("http://toolsqa.com/iframe-practice-page/");
driver.switchTo().frame(driver.findElement(By.xpath(("//iframe[@id='IF1']")));

driver.findElement(By.xpath(".//*[@id='branding']/a")).click();

**Comment by dragodr93** [comment]
Same for me with Firefox 50 and Selenium 3.0.1 on Ubuntu 16.04.

**Comment by himpush** [comment]
Any updates on this?

**Comment by p0deje** [comment]
I cannot reproduce the issue using:

* geckodriver 0.19.1
* Firefox 57.0
* selenium 3.8.0

Can anybody provide [concise reproducible test case](http://sscce.org/)?

**Comment by barancev** [comment]
Closing the issue as reported against outdated (beta) version.
