### ISSUE TITLE
Selenium 3 : Virtual - Debugging Issue with FF 40

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2379]
## Meta -
OS:  Win 8.1

Selenium Version:  Selenium 3 Beta

Browser: FF 

Browser Version:  40.0.3

Eclipse Version: Kepler Service Release 2

## Expected Behavior -
User should be able to use the “Display” and “Watch” feature while Debugging.

## Actual Behavior -
User not able to use the “Display” and “Watch” feature while Debugging.

## Steps to reproduce -

1)	Put debugger on  a Test Step in your case (using Eclipse) where you are finding an element
2)	Select that part of LOC
3)	Right click and Select “Display” option and observe that result is not shown.

Note: Same is working fine with Chrome 47

## Stack Trace -
1466847802291 Marionette    TRACE  conn0 -> [0,44,"findElement",{"using":"xpath","value":"//nav[@id='navId']//a[contains(text(),'My Referrals')]"}]
1466847802294 Marionette    TRACE  conn0 <- [1,44,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"4aea0203-13d8-4659-bbcb-fc14261693de","ELEMENT":"4aea0203-13d8-4659-bbcb-fc14261693de"}}]
1466847802301 Marionette    TRACE  conn0 -> [0,45,"getElementText",{"id":"4aea0203-13d8-4659-bbcb-fc14261693de"}]
1466847802306 Marionette    TRACE  conn0 <- [1,45,null,{"value":"My Referrals / IJPs"}]
1466847802390 Marionette    TRACE  conn0 -> [0,46,"findElement",{"using":"xpath","value":"//nav[@id='navId']//a[contains(text(),'My Referrals')]"}]
1466847802393 Marionette    TRACE  conn0 <- [1,46,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"4aea0203-13d8-4659-bbcb-fc14261693de","ELEMENT":"4aea0203-13d8-4659-bbcb-fc14261693de"}}]
1466847802408 Marionette    TRACE  conn0 -> [0,47,"findElement",{"using":"xpath","value":"//nav[@id='navId']//a[contains(text(),'My Referrals')]"}]
1466847802411 Marionette    TRACE  conn0 <- [1,47,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"4aea0203-13d8-4659-bbcb-fc14261693de","ELEMENT":"4aea0203-13d8-4659-bbcb-fc14261693de"}}]
1466847802426 Marionette    TRACE  conn0 -> [0,48,"findElement",{"using":"xpath","value":"//nav[@id='navId']//a[contains(text(),'My Referrals')]"}]
1466847802429 Marionette    TRACE  conn0 <- [1,48,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"4aea0203-13d8-4659-bbcb-fc14261693de","ELEMENT":"4aea0203-13d8-4659-bbcb-fc14261693de"}}]
1466847802444 Marionette    TRACE  conn0 -> [0,49,"getElementText",{"id":"4aea0203-13d8-4659-bbcb-fc14261693de"}]
1466847802454 Marionette    TRACE  conn0 <- [1,49,null,{"value":"My Referrals / IJPs"}]

**Comment by lukeis** [comment]
I'm uncertain what this issue is reporting. Seems like an issue with eclipse rather than with selenium. I currently have no issue debugging with 3.0 / marionette where I can't see variables or other debug information.

Closing, feel free to provide more information for us to understand where an issue may lie.
