### ISSUE TITLE
Selenium 3 : Virtual - Suggestion: Support for Windows Popup

### ISSUE THREAD

**Issue by naukri-engineering** [SeleniumHQ/selenium#2380]
## Meta -
OS:  Win 8.1

Selenium Version:  Selenium Beta 3

Browser:  FF

Browser Version:  40

## Expected Behavior -
We should allow support for Windows popUp's

## Actual Behavior -
No Support Available as of now.

**Comment by jigarladhava** [comment]
What do you mean by "Windows popUp's" ?
Browser's window ?
or Windows Form Application?

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
