### ISSUE TITLE
Selenium 3: HtmlUnitDriver does not exist (as complete package is not part of jar)

### ISSUE THREAD

**Issue by p00j4** [SeleniumHQ/selenium#2381]
## Meta -
```
OS:  MAC OSX
Selenium Version:  selenium 3.0 jar
```

## Expected Behaviour -
as backward compatibility should have htmlunitdriver as part of this package "org.openqa.selenium.htmlunit.HtmlUnitDriver"

## Actual Behaviour -
throws error: package org.openqa.selenium.htmlunit does not exist

## Steps to reproduce -
```
/Users/pooja/workspace/Robo/src/main/java/com/moe/webDriverHelper/UiUtilities.java:40: error: package org.openqa.selenium.htmlunit does not exist
import org.openqa.selenium.htmlunit.HtmlUnitDriver;
                                   ^
```

![image](https://cloud.githubusercontent.com/assets/6470509/16355682/cd41b59c-3adb-11e6-84ea-feb1f4bee911.png)
As its not found in the jar given at - https://github.com/bugbash/selenium3
![image](https://cloud.githubusercontent.com/assets/6470509/16355685/e72b6232-3adb-11e6-9a5e-b5cae9cb295a.png)

**Comment by blaken** [comment]
HtmlUnitDriver is now [packaged separately](https://github.com/SeleniumHQ/htmlunit-driver), as of Selenium 2.53. I reckon its separate packaging will continue for 3.0 and onward. The reasoning is explained on the linked project page:

> WARNING: HtmlUnitDriver was a part of Selenium main distribution package prior to Selenium version 2.53. If you are using Selenium 2.52 or earlier you don't need to download and install HtmlUnitDriver, it is already there.
>
> According to Selenium evolution strategy drivers should be separated from Selenium, and a driver release cycle should be synchronized with the target browser release cycle instead of Selenium release cycle. So this happened to HtmlUnitDriver too. It's not a part of the main Selenium distribution since version 2.53.

In other words, backward compatibility was intentionally broken.

Note, I'm not a Selenium developer. _Caveat lector._

**Comment by p00j4** [comment]
Not an issue, intetional separation of Drivers, closing it

**Comment by ProfessorTom** [comment]
How would one install HTMLUnit Driver on macOS Sierra for use with Selenium (Server?)?

**Comment by ProfessorTom** [comment]
Leaving this here for those who come behind: if you install the standalone Selenium Server (`brew install seleniumserver` on macOS Sierra) HTMLUnit comes along for "free". Once `seleniumserver` is installed, run the command`seleniumserver` in your command prompt. After the server has finished booting, you can then use this line from Python:

`driver = webdriver.Remote("http://localhost:4444/wd/hub", webdriver.DesiredCapabilities.HTMLUNITWITHJS.copy())`

and then use HTMLUnit as your `webdriver`

**Comment by Ricalsin** [comment]
I could have used some clarity on the htmlunit driver being a separate download - the absence of mentioning it [on this page][1] had me thinking incorrectly.  

FWIW, the ['Selenium WebDriver's-Drivers'][2] seems like it could use some verbiage upgrade.  Now that I get it, it makes sense - but I found it confusing to learn.  I realize 'WebDriver' is deeply embedded into the code vernacular. But what about switching that verbal reference to the Firefox,IE,Chrome,htmlunit 'drivers' to be 'engine'?  That would make the verbal reference be Selenium WebDriver Engine without affecting the code - which would remain (i.e.) webdriver.Firefox.  Then, your references to the 'engine' would not be co-mingled with Selenium's (Web)Driver reference.  My understanding gained a few steps when I understood the separation of  concerns - which the nomenclature didn't help to cement in my brain.  

Thanks for the work!


[1]:http://www.seleniumhq.org/docs/03_webdriver.jsp
[2]:http://www.seleniumhq.org/docs/03_webdriver.jsp#selenium-webdriver-s-drivers
