### ISSUE TITLE
Selenium automation problem-Browser opening with error Message

### ISSUE THREAD

**Issue by rohanricky** [SeleniumHQ/selenium#2382]
## Meta -
OS:  Windows 10
Selenium Version:  
2.53.5
Browser: Firefox

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
