### ISSUE TITLE
Edge WebDriver does not wait for "document.readyState == 'complete'"

### ISSUE THREAD

**Issue by SamuraiJack** [SeleniumHQ/selenium#2388]
## Meta -
OS:  Windows 10 (using the testing VM from the MS website)

Selenium Version:  
2.52.0
Browser:  
MS Edge

```
var webdriver = require('selenium-webdriver')

var edge            = require('selenium-webdriver/edge')
var edgeOptions     = new edge.Options()

edgeOptions.setPageLoadStrategy('normal')

var builder = new webdriver.Builder()
    .forBrowser('MicrosoftEdge')
    .setEdgeOptions(edgeOptions);

var driver = builder.build();
    
driver.get('http://lh/siesta/examples/index.html');

driver.executeScript(function () { return document.readyState }).then(function (res) {
    console.log(res)
})

driver.quit()
```

## Expected Behavior -
To always see the "complete" as the result of the script above

## Actual Behavior -
The results of running the script above 4 times in row:
```
L:\JavaScript\siesta>bin\binary\nodejs\win32\node.exe misc\edgebug\script.js
loading
^C
L:\JavaScript\siesta>bin\binary\nodejs\win32\node.exe misc\edgebug\script.js
loading

L:\JavaScript\siesta>bin\binary\nodejs\win32\node.exe misc\edgebug\script.js
complete

L:\JavaScript\siesta>bin\binary\nodejs\win32\node.exe misc\edgebug\script.js
loading

L:\JavaScript\siesta>
```
As you can see, the behavior is sporadically different.

As a side note - the script above also "hangs" at the end (also sporadically) and one need to stop it with CTRL+C (see the "^C" above).

## Steps to reproduce -
The url in the script should point to a website served from local webserver (the issue is noticed less frequently for http://google.com)

**Comment by jimevans** [comment]
The Selenium project does not maintain the Microsoft Edge driver; Microsoft does. Issues with the Edge driver should be [reported to Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).
