### ISSUE TITLE
Node.js client firefox tests do not pass

### ISSUE THREAD

**Issue by oddui** [SeleniumHQ/selenium#2390]
## Meta -
OS: OSX 10.9.5
Selenium Version: master branch
Node Version: v4.2.2
Firefox Version: tried 46.0.1, 47, dev
GeckoDriver Version: v0.8.0

## Expected Behavior -
Tests pass.

## Actual Behavior -
27 firefox tests fail. [output.txt](https://github.com/SeleniumHQ/selenium/files/336409/output.txt)

## Steps to reproduce -
`npm test`

I'm trying to make some changes to the node client but cannot get the tests pass. Is there a specific version of firefox that i need to run the tests? Thanks.

**Comment by jleyba** [comment]
Yeah, I haven't finished going through the failures with marionette.

If you have FF46 installed, try running with

```
SELENIUM_BROWSER=legacy-firefox npm test
```

You can set `SELENIUM_BROWSER` to a comma delimited list to run against multiple browsers:

```
SELENIUM_BROWSER=legacy-firefox,firefox,chrome,phantomjs npm test
```

**Comment by oddui** [comment]
I tried the listed browsers and it seems only chrome pass the tests.

- `chrome` ✅ 

- `phantomjs` 1.9
10 fails on `Error: Server terminated early with status 1`

- `phantomjs` 2.1
6 fails on some `InvalidCookieDomainError`

- `firefox` 46
27 fails as in the issue

- `legacy-firefox` 46
31 fails  [output.txt](https://github.com/SeleniumHQ/selenium/files/338363/output.txt)

Are the fails known issues? Just want to make sure my dependencies are setup correctly.

**Comment by jleyba** [comment]
```
SELENIUM_BROWSER=chrome,phantomjs npm test
```

The above passed for me. Well, phantomjs crashed a few times, but it was always a different point in the test suite each time I ran, so I consider it a phantomjs issue.

Looking at the Firefox tests on 47.0.1 and will spend time on getting the Marionette tests green today.

**Comment by oddui** [comment]
@jleyba thanks for fixing the tests. Is is possible to have a 3.0 preview released on npm? So that people can start using the libs. Thanks.
