### ISSUE TITLE
Using PhantomJS with a proxy

### ISSUE THREAD

**Issue by upn0rth** [SeleniumHQ/selenium#2397]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.0, C#

Browser: PhantomJSdriver 

Browser Version: 2.1.1

## Expected Behavior -

I want to connect via proxy.

## Actual Behavior -

It appears to be working fine, according to the console window my proxyType is set to "none" and the httpProxy to the ip of the proxy.
But I got suspicious to if it was acctually working so I had it connect to a random IP-checking website and take a screenshot. It showed my real IP.

## Steps to reproduce -

```
PhantomJSDriverService service = PhantomJSDriverService.CreateDefaultService();
service.IgnoreSslErrors = true;
service.SslProtocol = "any";

var options = new PhantomJSOptions();                        
options.AddAdditionalCapability(CapabilityType.Proxy, new Dictionary<string, string>
     {
           {"proxyType", "none"},
           {"httpProxy", proxyL}
     });

```

Any ideas? The console seems to show the correct settings.

**Comment by lukeis** [comment]
phantomjs bugs should be logged with the ghostdriver project:
https://github.com/detro/ghostdriver

But it seems you should be setting a proxy with phantomjs by passing in service args to the PhantomJSDriverService -
http://stackoverflow.com/a/16353584
