### ISSUE TITLE
Selenium unable to deal with disappearing iFrames

### ISSUE THREAD

**Issue by richardrl** [SeleniumHQ/selenium#2401]
Scenario: login form is in an iFrame. If you go into the iFrame (driver.switchTo().frame()) to enter details into the username, password fields and press submit, when you submit the login form the login iFrame disappears from the DOM and causes the WebDriver to crash. This means Selenium is unable to deal with these types of login forms.

Tested and confirmed in latest Selenium, PhantomJS and Firefox

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
