### ISSUE TITLE
Selenium 3 : Jar help is mission on the command prompt console 

### ISSUE THREAD

**Issue by YatheeshKumar** [SeleniumHQ/selenium#2402]
## Meta -
OS:  Windows 7 64bit
Selenium Version:  Selenium 3

## Expected Behavior - 
the following command should provide the help on the command prompt console 
"java -jar selenium-server-standalone-latest.jar -h" 
Help Ex:  -port <nnnn>: the port number the selenium server should use
   (default 4444)
 -timeout <nnnn>: an integer number of seconds we should allow a
   client to be idle
 -browserTimeout <nnnn>: an integer number of seconds a browser is
   allowed to hang
 -interactive: puts you into interactive mode.  See the tutorial for
   more details etc...

## Actual Behavior -
the above command throws the following error 
"Unknown role: NOT_GRID"

## Steps to reproduce -
Run the following command on the windows command prompt 
"java -jar selenium-server-standalone-latest.jar -h"

**Comment by lukeis** [comment]
this has since been fixed, download a newer version from here to try it out:
http://ci.seleniumhq.org:8080/job/Build_All_Java/
