### ISSUE TITLE
Marionette/Selenium start-up issue  - windows

### ISSUE THREAD

**Issue by inthegarage** [SeleniumHQ/selenium#2403]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.5.3
Browser:  
47.0.1 - using Marionette - marionette start up issue.

I am trying to start marionette via protractor on windows. I have added the gecko driver to my path and I've also added the following property to the environment:

webdriver.gecko.driver=C:\tools\gecko

I've also tried to add it here too:

        capabilities: {
            'browserName': 'firefox',
            marionette : true,
            "webdriver.gecko.driver" : "/tools/gecko",

And I've also added the \tools\gecko to the path variable (all users) too.

The env vars are printed correctly when I use windows "set".

I get the following error when trying to activate the driver:

c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\error.js:26
  constructor(opt_error) {
                         ^
WebDriverError: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/jgraham/wires. The latest version can be downloaded from https://github.com/jgraham/wires

The command I use is:

node.exe c:\work\node_modules\protractor\built\cli.js <test file>

What is actually needed so that this is picked up correctly? This doesn't seem to be working currently in Windows and appears bugged.

Your advice is appeciated.

**Comment by jleyba** [comment]
I think selenium-standalone-server, which protractor insists on using for some reason, still looks for the "wires" binary instead of "geckodriver" (the name was changed with the 0.8.0 release).

You'll have to talk to the protractor folk to determine how command line args for the server should be defined with their configuration files.

**Comment by oddui** [comment]
Trying starting selenium standalone manually and set `seleniumAddress` in protractor config file:
```
java -jar /path/to/selenium-server-standalone-2.53.0.jar -Dwebdriver.gecko.driver=/path/to/geckodriver
```

**Comment by inthegarage** [comment]
Many thanks for your input. The second one has certainly got around the problem of it finding the driver. It's not working properly (probably Marionette issue), but at least selenium has found the drivers now. Closing.
