### ISSUE TITLE
Tests crashed on Mac OS X in Firefox > 44.0

### ISSUE THREAD

**Issue by demshin** [SeleniumHQ/selenium#2404]
## Meta -
OS:  OSX 10.11
Selenium Version:  selenium-standalone 5.3.1
Framework: webdriver.io 3.4, 4.0.8
Browser:  Firefox 45.0, 46, 47

## Expected Behavior -
Tests successfully performed.
## Actual Behavior -
Firefox start & closed. Tests are failed.

## Steps to reproduce -
I used webdriver.io 4.0.9 (and lower versions) that run tests on selenum-standalone-server 5.3.1 (and lower versions) on Firefox > 44.0. Than browser crashed.

**Comment by ndeztea** [comment]
I hope it will be fixed as soon as possible :)

**Comment by lukeis** [comment]
there is no such version as 5.3.1 do you mean 2.53.1?

Also, there's nothing one can do with this issue report if you don't provide an example test case showing the failure... we are able to run firefox 47.0.1 (not 47.0.0) and 46 and below versions with 2.53.1

If you provide an example test case showing failures with 2.53.1, then we can reopen the issue.

**Comment by ndeztea** [comment]
i tested it on latest version and works great again!! thank you guys!
