### ISSUE TITLE
element.clear() and element-click() fail with exception [work fine in IE and Firefox]

### ISSUE THREAD

**Issue by charlesfradley** [SeleniumHQ/selenium#2409]
element.clear() and element-click() fail with exception [work fine in IE and Firefox]

First the exception from element.clear()

org.openqa.selenium.InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'charles-PC', ip: '10.150.100.39', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver

Now the element.click() exception:

org.openqa.selenium.ElementNotVisibleException: element not visible
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 26 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'

---------

The exceptions are reporting that the element is not clickable nor accessible.  This is not true.  The element can be clicked and cleared manually, and Selenium can access them using Firefox and IE with no problems.  this strange behavior is unique to the chromedriver, version 2.22 [latest] in use.

Here is the html involved:

<input aria-invalid="true" aria-label="Please enter username" class="loginentryInput ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" ng-model="LoginEntryView.userName" name="uUserName" required="true" type="text">

---------------------

I tried adding a wait with the following resulting exception:

org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for element to be clickable: [[ChromeDriver: chrome on XP (42ea63bfbe04b216c70dafeb53031694)] -> xpath: /html/body/div[2]/div[1]/lc-login/div[1]/login-entry/form/input[1]]
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'charles-PC', ip: '10.150.100.39', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.chrome.ChromeDriver

--------------

It appears that chromedriver does not realize that the element is really clickable, and falsely believes  that it is not ....

The element in question is a text field for entering a user name.   The web page is implemented with  node.js

**Comment by lukeis** [comment]
for chrome / chromedriver issues please log an issue with them, please include a way for them to reproduce the issue too, with a complete test script.

https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by charlesfradley** [comment]
I thought i did already....who are you ?
On Jun 30, 2016 6:41 PM, "Luke Inman-Semerau" <notifications@github.com>
wrote:

for chrome / chromedriver issues please log an issue with them, please
include a way for them to reproduce the issue too, with a complete test
script.

https://sites.google.com/a/chromium.org/chromedriver/help

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeleniumHQ/selenium/issues/2409#issuecomment-229809077>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALN79BKJiNM6o70DPwHLEAG61J-5a0xUks5qREYdgaJpZM4JBYZZ>
.

**Comment by charlesfradley** [comment]
ok sorry I logged this in the wrong place,  I had just followed links from the selenium/chromedriver page and this is where it dumped me .... after a considerable amount of searching I have found the chromedriver dev project which has its own issues page.  Thanks, CFR.

**Comment by charlesfradley** [comment]
ok sorry I logged this in the wrong place,  I had just followed links 
from the selenium/chromedriver page and this is where it dumped me .... 
after a considerable amount of searching I have found the chromedriver 
dev project which has its own issues page.  Thanks, CFR.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
