### ISSUE TITLE
Upgrade from selenium 2.48 to Selenium 2.53 has missing class 'org.apache.commons.lang3.StringUtils'

### ISSUE THREAD

**Issue by Preeti214** [SeleniumHQ/selenium#2413]
## Meta -
OS:  Windows
Selenium Version:  2.53
Browser:  Firefox ESR 38

## Expected Behavior -
Should not have thrown below exception after  upgrade
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
## Steps to reproduce -
I am using a java project with selenium stand alone jar 2.48 and just replaced the jar with latest 2.53

**Comment by lukeis** [comment]
commons-lang is a transitive dependency of htmlunit... we moved htmlunit to a separate project, but seemed to do maven a bit wrong in 2.53.0. 2.53.1 should be better, please upgrade to that.

But you shouldn't rely on a transitive dependency in a library, rather you should know your dependencies and explicitly include the ones you are using in your root pom file.
