### ISSUE TITLE
Switching between windows is not working as expected.

### ISSUE THREAD

**Issue by navin578** [SeleniumHQ/selenium#2415]
I am unable to switch between windows in devices getting an error saying "A request to switch to a different window could not be satisfied because the window could not be found."

Is this a bug ?

Please refer the code below for switching between windows.

DesiredCapabilities for IOS 6 Plus  
driver.get("http://toolsqa.com");
 WebElement ele = driver.findElement(By.xpath("//*[@id=\"mobile-menu\"]/span[1]"));
       ele.click();
       String parWin = driver.getWindowHandle();
       String target = "http://www.javatpoint.com/";
            String value = "javat";
            String args1 = String.format("window.open('%s', '%s'); null;", target, value);
            ((JavascriptExecutor) driver).executeScript(args1);
for (String winHandle : driver.getWindowHandles()) {
                if (winHandle != parWin) {
                    Thread.sleep(10000);
//getting error while using switchTo
                    driver.switchTo().window(winHandle);
   }
            }

**Comment by lukeis** [comment]
iOS?  so are you using appium or ios-driver or WebDriverAgent? if so, please log a bug with that project

**Comment by devendrapacharla** [comment]
I: JUJU:) is noti: working as respected I I. (#2415)
To: "SeleniumHQ/selenium" <selenium@noreply.github.com>
Cc:

> I am unable to switch between windows in devices getting an error saying
"A request to switch to a different window could noit be satis::: i ::)
ikfied because the j i ju could not be found."
>
> Is this a bug ?
>
> Please refer the code below for switching between windows.uij
>
> DesiredCapaybilities for JUJUIOS 6 Plus
> KimI
> driver.get("http://toolsqa.com");
> WebElement ele =
driver.findElement(By.xpath("//*[@id=\"mobile-menu\"]/span[1]"));
> ele.click();uuj
> String parWin = driver.getWindowHandle();
> String target = "http://www.javatpoint.com/";
> String value = "javat";
> String args1 = String.format("window.open('%s', '%s'); null;", target,
value);
