### ISSUE TITLE
Firefox WebDriver getting

### ISSUE THREAD

**Issue by maninwindow** [SeleniumHQ/selenium#2423]
`RemoteWebDriver WebDriver;`
`Actions actions = new Actions(WebDriver);`
`actions.ContextClick(searchItem).Perform();`

Right click action code is working well on Chrome and IE, but for Firefox getting exception below:

![firefoxexception](https://cloud.githubusercontent.com/assets/6553154/16556300/d87ca656-420b-11e6-809a-1d8feb5a73cb.PNG)

It seems method Perform(); is not implemented for Firefox.
Have anyone had similar issue?

**Comment by p00j4** [comment]
@maninwindow it works with firefox as well, just confirmed again on firefox 46 with webdriver 2.53 
which one is yours?

**Comment by maninwindow** [comment]
@p00j4 I am using Firefox 47.0.1 and WebDriver 2.54. Have you tried `Perform()` method in C#?  I am having exception like above as soon as my code executes that line. I am using [geckodriver](https://github.com/mozilla/geckodriver/releases),but i don't think there is anything wrong related to the geckodriver, it has been working well.

**Comment by lukeis** [comment]
This is a duplicate issue of #2285

**Comment by ranjprashant** [comment]
I am getting the same issue on using new Actions(driver).moveToElement(tempHeaderElement).perform();

Log:
org.openqa.selenium.UnsupportedCommandException: POST /session/58fec78f-ac07-4815-87ab-2bcd6686a200/moveto did not match a known command
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'DC4-QVM-TRBW-02', ip: '10.111.106.196', os.name: 'Windows Server 2012', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAFsjckkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc61XTW/jNhC991csfGqBmE023cv25F0nQIFgUyQbZA8BCJoaWYwpkuVQlv3vO6Ss+EuWnHZPlugZUjPz3pthheC585D/Opp5W9MbQ5FDelZmzkqha+GBgREzDdno4kMuNMJvf/5SbT0zEcjGWR+iSwFCh6J5Z2S0VHLAvz25AO3AT5xDFo9d4wQXLLdewtl+Bpb0RG4olvDdThUuyHcknNNKiqCs+b3E2vrs4sPumsTlxYcAq9A87f61NBkrcQwrCfr4H+vArEpNH1mKgGOb5xRtZmVVgqHo6TtFhgVAKDVLvxcdeztbg3dWmbB/gMvy/YXV+HAJ0x7Hhhr3F0pMAYz2E2ggUC4WrAjBMVcoLNbj+LcTiGMNZh4Kyt7HT5+68x6Do58MAsgA2a3yGCYEAqljwYKvDnFiSwLUisvC2xI4Sq9c4L4yPKgyulxfdh8UxAwZ4dDcm6/a4gAcMlsbbQWlVhgxj4gubP1cgHkkmEaIdrs7+igXMB7GS5sJPQB6WAZrNTLwniBKpbB6F+fH4aOaG2soayWUM/CP6RX7Y0FAjGUOlkjoAQlXPKcP5dILLPp9tTKLBFBOwAZvhI7FfDd181jWh8p0H1bDLPOKSMeFlEDlrAxFjgQHLsEH7M5EszUyXBvJ4trm8X+W8M1dodNiDdnN1eXjN0uIjJD5o9uYlrJ786wMHYpXl4xo6O3Tw13SjZmtwueZFmYxOsZykygutOavyCPBXOJkZ8wrp6iMZMvqQgXQCgNt8E+l/CmERXgtVGAblrapoOAixjoPeSu9oIITsfohjDGZlWMFsdHR3rwGLSMzKx+hMhoN8Cu3mvh/R5EcAytCziTossoRyoAZqkO+fiKTM+nbPkxV9BhNP7+8fH/4widVsGVStfS+fb31ooSYKf4N6peX1v2wcKcRX7lof9ObMpCVV2FNrNBATwyDVzJw69VcGe4sKe66Pz4DNUkM2+S4B2F7H9rszOLiYzUrVZKFv9PiJBHvvObcuU1vxG9KtAFLBApZnlDqreZQmHXi1DE2qEuSHYxF0+m1rflszTPIRaXDCcHYpF2i22D6nT2AbJ7bz+nwO4ZrL3NaahKPSc2DX7OmeyT7j0O2Zw1DRxHI2PmiBk6tGYj+5uluwq6Z2ALjOKWvYimaDtzbtA7L32pFP3aPY/bwmoaE3kMaasTt+3O0Uy1B9J82ivgoCXhRfK8uT/WoZlduSC+WwGlWNCc6VMfkcU+oPle5GijfJn38idq1E/dMW7lITeQsNCEIL4sNtoeiKFnDXJZVpTsLHdvIf6pWk0CcRcc93FsqtFdZd4M80u9D4b7unpAbEo5b5SI2hGpgdNvYnlDlzSg8PAPvDFiYxr/tgEXqXZ3qpjupixTpNtrRANuMLmnQ+st8bcbZ82reClRO1x4cHtJi6JsZhqdOkVEdzJyn+ndP5ln+iq3PmUDcHRwnmiZRujqQQmsYgj/d0mhGkwXIxbSh8Zfmn/fPUExkmYppFQOtvvPq/V+v3NrO53FxcyXpbe47gpIijikifs6Ujhwxal4EfWKc2XFtT3yXUrQFEk1xbn7cDAvsUbJbrtMtOjRdcRRvVR4OErwdvuMljLhLV6mB6XurnDrHyjUD4nYu/hdQSwcIZ7FvAMMEAAA5EQAAUEsBAhQAFAAICAgAWyNySWexbwDDBAAAOREAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA+AQAAAAA}, appBuildId=20161104212021, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=8104, browserVersion=50.0, platformVersion=6.2, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]

**Comment by maninwindow** [comment]
@ranjprashant  `Actions` class could not be used on Firefox. You should pick up some other approach to achieve it.
