### ISSUE TITLE
Nothing happens when execute script window.scrollTo in PhantomJS

### ISSUE THREAD

**Issue by zhaihm** [SeleniumHQ/selenium#2426]
## Meta -
OS:  Windows 7
Selenium Version:  2.48.0.0
Browser:  PhantomJS
Browser Version:  2.1.1

## Expected Behavior -
Page scrolled to specific position

## Actual Behavior -
Nothing happens

## Steps to reproduce -
Open a page with vertical scroll bar in PhantomJS, then execute below script:
`window.scrollTo(0, 300);`

**Comment by lukeis** [comment]
this would be a bug for phantomjs / ghostdriver please log an issue there, also please provide a reproducible test case for others to see to help troubleshoot the issue.
https://github.com/detro/ghostdriver
