### ISSUE TITLE
Unable to handle HTTP authentication popup when login with Facebook

### ISSUE THREAD

**Issue by clmathuriya** [SeleniumHQ/selenium#2428]
## Meta -
OS:  Ubuntu 14.04

Selenium Version:  
2.53.1
Browser: Firefox

Browser Version:  47.0

## Expected Behavior - When trying to login with Facebook on our dev environment  https://dev.preplane.com/ 
a HTTP authentication popup displayed, we tried below things but none worked:

1. Tried to switch on alert using 
`driver.switchTo().alert()` 
Unable to switch on alert.

## Actual Behavior -

We should be able to switch to alert and authenticate using credentials.

## Steps to reproduce -

1.  go to https://dev.preplane.com/
2.  click on Login 
3. click on login with Facebook
4. Enter valid credentials for Facebook and click on login
5. HTTP Authentication popup displayed but unable to switch on the alert.

Below is selenium web driver code in java:

update your facebook email and password for debugging.

`
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Main {

	public static void main(String[] args) {
		WebDriver driver = new FirefoxDriver();
		driver.get("https://dev.preplane.com/");
		driver.findElement(By.linkText("LOGIN")).click();
		driver.findElement(By.id("FbBtn")).click();
		// to login with facebook
		driver.findElement(By.id("email")).sendKeys("youremail@gmail.com");
		driver.findElement(By.id("pass")).sendKeys("Yourpassword");
		driver.findElement(By.id("loginbutton")).click();
		// http authentication popup displayed try to switch on it
		Alert alert = driver.switchTo().alert(); // this step not executed.
		alert.dismiss();// not working

	}

}
`

**Comment by lukeis** [comment]
basic http auth is tracked in this issue: #453

short answer: it's not implemented in FirefoxDriver... might be in the future for GeckoDriver (if it hasn't already? I don't know)

**Comment by clmathuriya** [comment]
Lukeis, 
Thank you for update,
As of now adding Authorization header in Firefox profile is working for me.

  `profile.setPreference("modifyheaders.headers.count", 1);
   profile.setPreference("modifyheaders.headers.action0", "Add");
   profile.setPreference("modifyheaders.headers.name0", "Authorization");
   profile.setPreference("modifyheaders.headers.value0", "Basic base64encodedtoken=");
   profile.setPreference("modifyheaders.headers.enabled0", true);
   profile.setPreference("modifyheaders.config.active", true);
   profile.setPreference("modifyheaders.config.alwaysOn", true);
`

**Comment by alexa-galileo-ae** [comment]
for which  version of firefox and webdriver version it is working? I tried for firefox 52.5 webdriver 3.8.1.  and driver.get(url) is hanged at execution.

**Comment by rchuqiao** [comment]
For which version of Firefox/webdriver and OS is this working? I have tried on Firefox 52.5.2 (64-bit) with Selenium 3.8.1 on MacOS. Thanks a lot!
