### ISSUE TITLE
Firefox profile is automatically downloaded when run from Jenkins server 

### ISSUE THREAD

**Issue by nitinsr013** [SeleniumHQ/selenium#2432]
Hi All

I am getting below error when I run from Jenkins Server
Silenium version:2.53.1
FirFox:47.1
Nunit3

1467802162971	addons.manager	DEBUG	Application has been upgraded
1467802163033	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1467802163037	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1467802163043	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1467802163046	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1467802163048	addons.manager	DEBUG	Starting provider: XPIProvider
1467802163048	addons.xpi	DEBUG	startup
1467802163050	addons.xpi	INFO	Mapping fxdriver@googlecode.com to C:\Users\jenkinsuser\AppData\Local\Temp\anonymous.44273d20cf514655988f92acc3df03ee.webdriver-profile\extensions\fxdriver@googlecode.com
1467802163051	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1467802163052	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1467802163053	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1467802163054	addons.xpi	INFO	Mapping loop@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1467802163056	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1467802163056	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1467802163057	addons.xpi	DEBUG	Skipping unavailable install location app-system-local
1467802163058	addons.xpi	DEBUG	checkForChanges
1467802163059	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1467802163059	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
1467802163060	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1467802163096	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1467802163097	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1467802163098	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1467802163099	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1467802163099	addons.xpi	DEBUG	New add-on loop@mozilla.org in app-system-defaults
1467802163099	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1467802163101	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1467802163101	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467802163101	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\jenkinsuser\\AppData\\Local\\Temp\\anonymous.44273d20cf514655988f92acc3df03ee.webdriver-profile\\extensions\\fxdriver@googlecode.com","st":1467802162077,"mt":1467195758000}},"app-system-defaults":{"e10srollout@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1467619964295},"firefox@getpocket.com":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1467619964290},"loop@mozilla.org"

**Comment by lukeis** [comment]
you haven't shown any error? just the console log from firefox... which only has DEBUG and INFO statements.

Also when logging issues please provide a way for someone to reproduce your issue.
