### ISSUE TITLE
Clicking inside iframe with webdriver on Firefox causing page scroll unexpectedly

### ISSUE THREAD

**Issue by wyhmichael** [SeleniumHQ/selenium#2434]
## Meta -

OS:  

Selenium Version:  2.53.0, 2.53.1

Browser:  Firefox 47, Firefox 48.0b4

Browser Version:  47, 48

## Expected Behavior -

Clicking inside iframe should not cause the unexpected scrolling
## Actual Behavior -

Clicking inside iframe caused the unexpected scrolling
## Steps to reproduce -

1. I made this sample page containing an iframe inside which there are 5 buttons with absolute positions
2. I used firefox webdriver to click buttons from right to left one by one, when clicking on the last one, page scrolled unexpectedly

```
FirefoxDriver driver = new FirefoxDriver();
driver.get("http://seleniumbug.rf.gd/");
driver.switchTo().frame("game-frame");
driver.findElement(By.id("myButton1")).click();
driver.findElement(By.id("myButton2")).click();
driver.findElement(By.id("myButton3")).click();
driver.findElement(By.id("myButton4")).click();
driver.findElement(By.id("myButton5")).click();
```
## Comment -
1. I only tried with latest 2 versions of selenium and firefox,  but I believe this is related to this commit: https://github.com/SeleniumHQ/selenium/commit/2f4a6d884e5a3eff6791b1006bb65f045c6d2494, 

I have to say it's very arguable to add scrollintoview in the click function; from my point of view scrollintoview is better to go as a separate function instead of modifying the existing click function, if it's badly needed, because click should be as simple as possible to do just clicking, and selenium should give flexibility to users to scroll or not, rather than brutally scroll regarless; besides, we as users of selenium are highly depending on the click function, I would prefer you don't add uncertain things to it unless you can test it properly, that would be highly appreciated

**Comment by wyhmichael** [comment]
[sample.zip](https://github.com/SeleniumHQ/selenium/files/351344/sample.zip)

**Comment by wyhmichael** [comment]
Just added the 2 html pages above that I used to reproduce the issue

**Comment by p00j4** [comment]
yes and no.
its debatable because as a user, I want my tests shouldn't fail because of the element wasn't in the view etc. and thats' where its good to have scrollIntoView first before performing any action. 
Even I find the need of having  same in ChromeDriver as well, as most tests where firefox auto-scrolls and test passes, they just keep failing in chrome with "can't scrollintoview" or "not clickable at this point" etc. exceptions where additional handling becomes a huge pain specially when you run them in CI behind xbuffer on different screen resolutions.
Having said that, yes I agree in this specific case of yours, this amount of scrolling doesn't look required, may be the scroll calculation has to be more precised

**Comment by wyhmichael** [comment]
Again，I'm saying scrolling function can be provided but leave the choice to user to decide when to use it, selenium is to provide a solution to make tests not making tests for users, and here adding scrolling to click is nothing but imposing the idea to users that this is for users' good which is not.
And yes, it definitely needs second even more reviews how to perform this scrolling properly. I went through several bugs which are related to the scrolling, they are not properly addressed so far. And this is another reason that this scroll should go separately instead of breaking the fundamental / core function of selenium, and this is more suitable to perfect the function along with evolvement of selenium.
And also it's good that Chrome driver didn't couple clicking with scrolling.

**Comment by oddui** [comment]
@wyhmichael it's defined in the [spec](https://www.w3.org/TR/webdriver/#element-click) clicking elements

I think ChromeDriver also does it.

You may try using the click action if you don't want scrolling.

**Comment by wyhmichael** [comment]
@oddui thanks for providing one of the workarounds and pointing me to the documentation, it's good that firefoxdriver and documentation are consistent, but it still cannot justify the above point.

and if ChromeDriver does the same thing in the click, then it works at least for this case, which is still good.

Version 51.0.2704.103 m
ChromeDriver 2.22.397933

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
