### ISSUE TITLE
Safari driver requires SELENIUM_SERVER_JAR to be set in the path env variables

### ISSUE THREAD

**Issue by VitoAlbano** [SeleniumHQ/selenium#2436]
OS:  
OSX 10.11.5
Selenium Version:  
2.53.5
Browser:  
Safari 
Browser Version:  
9.1.1 

## Expected Behavior -
As per https://github.com/robotframework/Selenium2Library/pull/247 , https://github.com/SeleniumHQ/selenium/wiki/SafariDriver and SeleniumHQ/selenium-google-code-issue-archive#5352 i was expecting to be able to use safaridriver without the need to set the SELENIUM_SERVER_JAR variable. 

## Actual Behavior -
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
1.Login Page Should Have User and Password Required | FAIL |
Parent suite setup failed:
No executable path given, please add one to Environment Variable 'SELENIUM_SERVER_JAR'

Is this as expected?

**Comment by lukeis** [comment]
Yes it is expected. The Java code (this standalone server) has the logic to start the safari driver, it wasn't implemented in Python. 

It will not be a requirement in future releases and when users are running macOS Sierra, since apple is now providing a driver implementation.

**Comment by VitoAlbano** [comment]
ok, Thanks :)
