### ISSUE TITLE
Selenium 3 -html runner

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/selenium#2438]
simon has been working on a new html test runner (for selenese in the 3.0 server that will run as WDBS).

This issue is to track that work.

Simon did say "If anyone wants to hook up the old HTMLTestResults class to the new CoreRunner, we can ship".

**Comment by lukeis** [comment]
lots of work done on this:

https://github.com/SeleniumHQ/selenium/compare/09820214c6da...4a80e2cdfbf435d1ff40fa005d06e3a954b42766

**Comment by shs96c** [comment]
Making progress. I've hooked up basic logging of results, but without colourisation. That'll come soon, once I add most of the missing commands to the runner.

**Comment by shs96c** [comment]
All commands exercised in the original Selenium Core tests, other than `rollup` and `addScript` have now been added. Time to focus on generating a might pretty report.

**Comment by shs96c** [comment]
With 3705de80e82b3c8c6882b948dbcd6928bae1c03e I think we now have enough of the new runner in place to go ahead with the beta. I expect there to be a flurry of bug reports about it, but it appears to be doing something approximating the Right Thing.

Closing this issue since the runner now exists.
