### ISSUE TITLE
One Specific WebElement does not Click or sendkeys(Keys.Enter) for FF or IE but works for Chrome

### ISSUE THREAD

**Issue by Aswilli4** [SeleniumHQ/selenium#2439]
OS:   Windows 7 Ultimate (64 bit)

Selenium Version:  Selenium WebDriver 2.53.1

Browser:  Internet Explorer, FireFox, Chrome

-->

Browser Version:  IE 10.0.9200.17609CO , FF 47.0.1  (32bit webdriver)  Chrome IE 10.0.9200.17609CO , FF 47.0.1 (32 bit)

## Steps to reproduce -
ts.getDriver().FindElement(By.XPath("myxpath"]")).SendKeys(Keys.Enter);

I am only seeing this on one button in my application. I have tried both the .click() and sendkeys methods and neither click on the button however i do see it briefly highlight the button. It is only happening on one button in my application.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
