### ISSUE TITLE
Firefox WebDriver is Very Slow

### ISSUE THREAD

**Issue by J-Phipps** [SeleniumHQ/selenium#2441]
## Meta -
OS:
Windows 10
Selenium Version:  
2.44.0 trough 2.53.1
Browser:  
Firefox (45 & 47)

Browser Version:  
45 through 47.0.1 maybe older versions too
31.4.0 (on a Mac) doesn't seem to have this issue.

## Expected Behavior -
I would expect the driver to be moderately performant.  A test that takes about 3 minutes with ChromeDriver or IEDriver takes about 7 minutes with the Firefox WebDriver (Selenium WebDriver).  Both local Selenium and RemoteWebDriver.

## Steps to reproduce -
I think the easiest way to uncover the issue is to open a Firefox browser and attempt to go to an intensive page (www.ace.com seems to cause the browser to crash).  Repeating the same exact steps with a native browser session has no performance issues.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
