### ISSUE TITLE
Skip failure scripts and proceed to next script

### ISSUE THREAD

**Issue by Sumathichn123** [SeleniumHQ/selenium#2445]
OS:  Windows 7
Selenium Version:  2.52
Browser:  chrome

I have 10 scripts to be executed one by one.
If login fails for 1st script, i want to skip that script and proceed to next script.
Is there any method available to do this.

**Comment by clmathuriya** [comment]
How are you executing those 10 scripts ?

1. If you are using TestNG test for each script you can add "alwaysRun = true " with @Test Annotation.

2. If you are using simple java with main method you need to handle assertion error for each script.

**Comment by lukeis** [comment]
This question has nothing to do with selenium, rather how you organize and run your tests with whichever test runner you are using. 

For questions please ask on the selenium-users Google group.
