### ISSUE TITLE
During creating a screenshot in Safari the active input loses focus

### ISSUE THREAD

**Issue by wswebcreation** [SeleniumHQ/selenium#2451]
**OS:** 
OSX 10.11.5
**Selenium Version:**  
2.48
**Browser:**  
Safari
**Browser Version:**  
9.1.1
**Automation tool**
Protractor 3.3.0 (NodeJS)

## Expected Behavior -
During / after taking a screenshot of a focussed input field, the input field should still have focus

## Actual Behavior -
The input field loses focus during / after creating the screenshot. The screenshot that has been created also has no focus
![Active empty input field](https://cloud.githubusercontent.com/assets/11979740/16756165/9bf32d7e-4803-11e6-824e-50f2fedc0171.png)
![Active filled input field](https://cloud.githubusercontent.com/assets/11979740/16756185/bb0b0c54-4803-11e6-997b-3a077b283a83.png)

## Steps to reproduce -
* set focus to the input field
* take a screenshot
* check the state of the inputfield + the screenshot

**Comment by lukeis** [comment]
when logging issues please provide a test script and corresponding html page with css & javascript (or link to publicly accessible page).

Also know that the SafariDriver has been deprecated and we are awaiting the new driver provided by apple to be released (scheduled to be in macOS Sierra, and is currently in the previews). We will no longer be supporting / fixing the SafariDriver that was provided by SeleniumHQ.
