### ISSUE TITLE
Pop up Child window and As well as Unable to Run Script on IE browser.

### ISSUE THREAD

**Issue by Sandeeppanigrahi** [SeleniumHQ/selenium#2454]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by Sandeeppanigrahi** [comment]
I unable to click on Element when i m in child window.

And i m unable to my Script on IE browser which i had kept IE Driver as 64 Bit as per my machine  and then also unable to Run script on my IE browser.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by Sandeeppanigrahi** [comment]
E.g: Web Page which have a button and it is clickable with same page Pop up window showing and same on that Pop up window i unable to click other button by XPATH or ID.
Thread.sleep(5000);
			addsensoragnt.click();
			Thread.sleep(2000);
			remsnr.click();-----------------this part not clickable .
			
			/*Set<String> winids = driver.getWindowHandles();
			String childWindow = winids.iterator().next();-----------------for that above i used child window which is not working.
			driver.switchTo().window(childWindow);*/
		
			Thread.sleep(2000);
			remcomment.sendKeys(dataInt.getComment());

**Comment by lukeis** [comment]
You're missing the "completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script"  still

**Comment by Sandeeppanigrahi** [comment]
ok leave it only u say me how to declare Child window in Same Window.
