### ISSUE TITLE
SELENIUM_BROWSER overrides set capabilities

### ISSUE THREAD

**Issue by halkeye** [SeleniumHQ/selenium#2455]
## Meta -
OS:  All
Selenium Version:  
selenium-webdriver@2.52.0 (though probably earlier)
Browser:  
All

## Expected Behavior -
When providing capabilities I expect them to be used. The saucelabs Jenkins plugin sets a bunch of env variables which are consumed by various frameworks. This includes SELENIUM_BROWSER, SELENIUM_VERSION and SELENIUM_PLATFORM which many users consume in their configs.

## Actual Behavior -
Selenium-webdriver javascript library silently overrides platform and version if SELENIUM_BROWSER is set.

## Steps to reproduce -

https://github.com/chris-broes/JS-Protractor-Selenium/blob/jenkins/conf.js

```
export SELENIUM_BROWSER=chrome
export SELENIUM_VERSION=51
export SELENIUM_PLATFORM='Mac 10.11'
```

Working code:
```
export SELENIUM_BROWSER="chrome:51:MAC 10.11"
```

## Comments -

With this behavior in place. I'd like to see it either documented clearly, or not override all 3 parts (unless colons are provided).

Is the SELENIUM_BROWSER variable documented somewhere?

**Comment by halkeye** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/builder.js#L435-L441 is the code in question

**Comment by jleyba** [comment]
Intended behavior. See builder documentation:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/builder.js#L57

**Comment by jleyba** [comment]
Also see the published API docs:

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Builder.html

**Comment by halkeye** [comment]
@jleyba this behavior is only defined for the javascript driver right? I couldn't see any indication of that behavior anywhere else.

**Comment by jleyba** [comment]
Yes, the js client is the only one with a centralized Builder class. I'd like to see the other languages adopt the same pattern.

BTW, you can disable the environment variables by calling `disableEnvironmentOverrides()`

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/builder_exports_Builder.html#disableEnvironmentOverrides
