### ISSUE TITLE
How do I prevent Selenium from catching an Error?

### ISSUE THREAD

**Issue by OptimisticLock** [SeleniumHQ/selenium#2457]
## Meta -
OS:  OS X 10.11.15
Selenium Version:  2.53.3
Browser:  Chrome

## Question

I am calling Selenium from Meteor (running on the server on top of Node.js), as follows:
```
var webdriver = require('selenium-webdriver')

function getPage(page) {

    driver = driver || new webdriver.Builder().forBrowser('chrome').build();

    driver.get(page).catch(function(error){
        throw new Meteor.Error("Can't get page " + page)
    })
}
```
When the page is not found and `Meteor.Error` is thrown, I am getting the following:

```
W20160712-12:49:40.093(-7)? (STDERR) 
W20160712-12:49:40.104(-7)? (STDERR) /Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:654
W20160712-12:49:40.104(-7)? (STDERR)     throw error;
W20160712-12:49:40.105(-7)? (STDERR)     ^
W20160712-12:49:40.105(-7)? (STDERR) Error: [Can't get page i]
W20160712-12:49:40.118(-7)? (STDERR)     at imports/somethingSel.js:35:15
W20160712-12:49:40.120(-7)? (STDERR)     at ManagedPromise.invokeCallback_ (/Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:1379:14)
W20160712-12:49:40.121(-7)? (STDERR)     at TaskQueue.execute_ (/Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:2913:14)
W20160712-12:49:40.123(-7)? (STDERR)     at TaskQueue.executeNext_ (/Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:2896:21)
W20160712-12:49:40.124(-7)? (STDERR)     at /Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:2775:27
W20160712-12:49:40.132(-7)? (STDERR)     at /Users/irinaapex/irina/meteor/selenium/node_modules/selenium-webdriver/lib/promise.js:639:7
W20160712-12:49:40.134(-7)? (STDERR)     at /Users/irinaapex/.meteor/packages/promise/.0.8.3-beta.9.1fbal0n++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:32:39
=> Exited with code: 1
W20160712-12:49:53.217(-7)? (STDERR) Debugger listening on port 49906
=> Meteor server restarted
```

Looks like Selenium is catching the Error and exiting. How do I suppress this behavior? I want to recover gracefully from a url not found.

Sorry if this is not an "issue", I could not find an answer elsewhere.

**Comment by jleyba** [comment]
selenium-webdriver uses a promise manager that requires you to handle all rejected promises. This behavior is covered in depth in the [promise module's documentation](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html).

For your limited example, log the error instead of throwing another error. Throwing a new error just creates another rejected promise you must handle.

```js
driver.get(page).catch(function(error) {
  console.error(error);
  return recoverFromFailedLoad();  // TODO: implement this
});
```

**Comment by OptimisticLock** [comment]
Thank you for the link. It says:

> Bottom line: you must handle rejected promises.

That does not work so well in case of Meteor, because Meteor automatically propagates any unhandled exceptions of type `Meteor.Error` to the client, which is the desired behavior. Is there any workaround at all, allowing to throw errors safely?

**Comment by jleyba** [comment]
How do you expect to propagate an unhandled promise rejection?

```js
Promise.reject(Error('boom'));  // Native promise: this goes nowhere
```

Anyway, WebDriver's managed promises will eventually bubble up to the global error handler, so you can atch them there. Just be warned, if you don't handle a rejected promise, the manager will cancel all pending actions scheduled in the queue.

```js
process.on('uncaughtException', doSomething);

driver.get(url);  // If this fails and is not handled, it will trigger an uncaughtException
driver.findElement(By.id('foo'));   // ... but this will be canceled as well
```
