### ISSUE TITLE
Element.Text doesn't include child text nodes

### ISSUE THREAD

**Issue by distinctdan** [SeleniumHQ/selenium#2463]
## Meta -
OS:  Windows 10

Selenium Version:  2.53

Browser:  Chrome

Browser Version:   51.0.2704.103

## Expected Behavior - 
Element.Text should return `Brown, Bob (bob.brown)`

## Actual Behavior -
It returns `Brown, Bob`

## Steps to reproduce -

Simply access the .Text property of the IWebElement in question. 
Here's the html for the element:
```
<li class="search-item unselectable ellipse ng-scope selected" ng-repeat="item in searchManager.results"
	ng-class="{selected: item._selected}" ng-click="itemClicked(item)" ng-mouseenter="searchManager.selectItem(item)">

    <i pow-object-icon="::item" class="hide-on-selected ng-isolate-scope"><i class="pow-object-icon">
	    <span class="pow-fc pow-user" title="User"><i ng-show="showInnerIcon" class=""></i></span>
	</i></i>
    <i pow-object-icon="::item" use-solid-color="::true" class="show-on-selected ng-isolate-scope"><i class="pow-object-icon">
	    <span class="pow pow-user" title="User"><i ng-show="showInnerIcon" class=""></i></span>
	</i></i>

    <!-- ngIf: item.objectType != Enums.ObjectType.User -->
    <!-- ngIf: item.objectType == Enums.ObjectType.User -->
    <span ng-if="item.objectType == Enums.ObjectType.User" title="Brown, Bob (bob.brown))" class="result-text ng-binding ng-scope">
        Brown, Bob <span class="username ng-binding">(bob.brown)</span>
    </span>
    <!-- end ngIf: item.objectType == Enums.ObjectType.User -->
</li>
```
My workaround for the moment is to use jquery for the lookup, and .innerText.trim() to get the normalized text content.

**Comment by lukeis** [comment]
please log chromedriver bugs with the chromedriver project, be sure to include a completely reproducible page, including css.

https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by distinctdan** [comment]
Figured it out, the nested span is getting pushed off to the right if the user's name is too long, which apparently causes Selenium not to return its text. I know you guys have talked about the hidden text thing before, but for a case like this, where the item isn't explicitly hidden, but is rather just outside its container, I think Selenium should still return it.

As it is right now, I still need to verify that the item in the dropdown is the one I'm expecting, regardless of whether selenium is willing to return it or not. So, I'm currently forced to use jquery to get the dropdown elements and run a javascript filter function to see if the text matches. Perhaps this functionality was well-intentioned to prevent offscreen text from coming back, but it's a pain in the butt to work with. For anything that can overflow, it makes the Text property useless.

**Comment by distinctdan** [comment]
Now, don't get me wrong, I love selenium and really appreciate all the work you guys do. Just feeling a little miffed about the text thing.

**Comment by jleyba** [comment]
IIRC if the element is an "overflow:hidden" region, it is not returned as text b/c it's not visible to the user.

Sounds like everything is working as intended for your use case. (And since you want the text regardless of whether a user can see it, falling back to executeScript is the way to go)
