### ISSUE TITLE
Firefox WebDriver fails randomly after upgrade to 2.53.1 on Travis CI

### ISSUE THREAD

**Issue by musketyr** [SeleniumHQ/selenium#2465]
OS:  
Travis CI running Ubuntu 12.04 Server

Selenium Version:  
2.53.1

Browser:  
Firefox

Browser Version:  
31.0esr

## Expected Behavior -
Tests only fails when conditions specified by the tests are not met. 

## Actual Behavior -
Tests randomly fails. When running a test suite sometimes the driver dies in the middle of running tests and all following tests fails as well. 

![failing-tests](https://cloud.githubusercontent.com/assets/660405/16828965/2689ecf6-4995-11e6-8e26-ef888094a8b4.png)

## Steps to reproduce -
Setup headless testing on Travis CI for a project with about 10 long running tests.
Do minor changes in the code to trigger new builds.
Most of the builds will fail as described above.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
