### ISSUE TITLE
Selenium IDE can`t  recognize "require" in rollup-rulles.js used for import JSON variable

### ISSUE THREAD

**Issue by VatslauX** [SeleniumHQ/selenium#2466]
1 Create json file for store variable - passed
2 Import json array in rollup-rulles.js to use as global variable - passed
3 Open seleniun ide with aatached rollup-rulles.js - error "require is undefined"

> const vars = require('./vars.json');
> console.log(**vars[0].user01**);
> 
> 
> manager.addRollupRule({
>     name : 'login as USER06 test Qweeeco gmail',
>     description : 'short login',
>     args : [],
>     commandMatchers : [],
>     getExpandedCommands : function(args) {
>         var commands = [];
> 
>         commands.push({
>             command : 'type',
>             target : loginField,
>             value: vars[0].user01
>         });
>    
>         return commands;
>     }
> });

**Comment by lukeis** [comment]
'require' is not defined... it's not apart of javascript in browsers. you'll have to include the function, usually it's included in various javascript libraries.

**Comment by VatslauX** [comment]
Thanks for the prompt answer! 
Please advise how can I workaround in this case?
It`s very inconvenient to duplicate variables in rollup-rulles.js

**Comment by lukeis** [comment]
you seem to be a more 'advanced' user, if you are injecting code into Selenium IDE.  Have you considered using WebDriver instead of IDE? It has much better support and can be used in a variety of programming languages.

As for how to do what you want to do... i don't know, you can try asking on the selenium-users google group

**Comment by VatslauX** [comment]
IDE for me like a fast debugging tool - Webdriwer need time to start, and then I can just see the checks.

In IDE I can make fast changes during the test and then python export code to make more robust tests.
I use JSON file for store all locators/credentials etc.- SelBloks extension allows this.
And use rollup rules for minimizing duplicate code in cycles like a while.

So my target - have the same meta-files to use in Webdriver and IDE.
Thanks for advice - I will ask in google group)
