### ISSUE TITLE
FirefoxDriver occassionally does not react to any commands after get and maximise

### ISSUE THREAD

**Issue by reconman** [SeleniumHQ/selenium#2468]
## Meta -

OS:  
Windows Server 2008 R2
Selenium Version:  
2.53.1
Browser:  
Firefox

Browser Version:  
24.0 ESR and 31.0 ESR
## Expected Behavior -

The Firefox window is maximized after loading the site and the driver responds to commands.
## Actual Behavior -

`10:29:34.397 INFO [13] org.openqa.selenium.remote.server.DriverServlet - Executing: [maximise window])`
is logged and the driver does not react to any commands anymore. The browser window shows the site but is not maximized.
## Steps to reproduce -

Start a hub and node with selenium-standalone-server-2.53.1.jar and use the RemoteWebDriver with Firefox capabilities.

Then execute the following commands

```
driver.get(...);
driver.manage().window().maximize();
```

 The site loads but in about 1 of 10 tries the error occurs.

**Comment by lukeis** [comment]
can you try with 38 ESR & 45 ESR. Technically we only attempt to support the last two ESR releases and will not attempt to reproduce / fix for older (24/31).

**Comment by reconman** [comment]
Happens with ESR 45 too. As I said it only happens in about 1 of 10 runs. I am trying to access a web application running on another server in the local network.

**Comment by reconman** [comment]
The error does not only occur with maximize. With window().setPosition() I get the same behaviour. It just says
16:06:03.454 INFO [1035] org.openqa.selenium.remote.server.DriverServlet - Executing: [set window position])
and doesn't react anymore.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
