### ISSUE TITLE
pause command executed problem

### ISSUE THREAD

**Issue by terrylao** [SeleniumHQ/selenium#2469]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.1

Browser:  Internet Explorer

Browser Version:  IE 11.0.9600.18349

## Expected Behavior -
continue execute command
## Actual Behavior -
the rest command those after pause command, will not wait, after clickAndWait execute,it will immediatly execute next command, not wait for page loaded
## Steps to reproduce -
record a clickAndWait command, and add pause command before it.

**Comment by lukeis** [comment]
Selenium RC is no longer supported by the project. Please migrate your test to use WebDriver and we can be of further assistance, please send questions to the selenium-users google group.

**Comment by terrylao** [comment]
actually i am using webdriver with IEDriverServer.exe

**Comment by lukeis** [comment]
Then please provide a complete script that shows you issue. The commands you are alluding to are RC based
