### ISSUE TITLE
Calling from CMD won't do anything

### ISSUE THREAD

**Issue by Jalax6** [SeleniumHQ/selenium#2470]
OS:  Windows 7
Selenium Version:  2.53.1
Browser:  Firefox
Browser Version:  47.0.1 (64-bit)

Just set-up my cmd to run a Selenium IDE script with Selenium Standalone, then open the firefox and run the test.

When running, firefox opens 2 windows, the TestSuite is loaded, the commands are show in the middle box, but then nothing happens. Nothing.

## Steps to reproduce -
I'm using this command:
java -jar C:\SeleniumTest\selenium-server-standalone-2.53.1.jar  -firefoxProfileTemplate "C:\profila" -htmlSuite "*firefox" "http://127.0.0.1" "C:\SeleniumTest\SeleniumTestcase.html" "C:\SeleniumTest\seleniumtestresult.html" -port 5555

**Comment by lukeis** [comment]
can you also provide the example "SeleniumTestcase.html" you are using?

**Comment by Jalax6** [comment]
Sure.

Somehow, I wasn't able to upload the zip file with the files in. There it goes a dropbox link:
   
https://www.dropbox.com/s/qs38vtv9gdklisi/SeleniumTestcase.zip?dl=0
Testcase + Suitcase

**Comment by lukeis** [comment]
zip is not very nice to send people... may contain evil :)  can you create a gist instead:

https://gist.github.com

**Comment by Jalax6** [comment]
Oh, my apologies.

There it goes: https://gist.github.com/Jalax6/cb8c8c0f3e3b3098e45c7c6111ce0219

**Comment by lukeis** [comment]
we're reworked the htmlrunner into a new standalone jar to use:

http://selenium-release.storage.googleapis.com/3.0/selenium-html-runner-3.0.1.jar

try using that. For me it successfully launches IDE test suites. Post back if you have issues and we can reopen this.

**Comment by jigyasa-at-git** [comment]
<div>Hello Jalax6,</div>
<div>&nbsp;</div>
<div>I also faced the same issue. While launching Firefox, 2 browsers (one blank and one with Skype) would open up and my tests would fail. To solve this problem, I created a new profile and launched Firefox with that profile. I created profile as explained in detail on the mozilla support site <strong><a href="https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles" target="_blank">here</a></strong>. I also made sure to select "Never check for updates (not recommended: security risk)" under Options --&gt; Advanced --&gt; Update</div>
<div>&nbsp;</div>
<div>This is how you launch Firefox with specific profile</div>
<div>&nbsp;</div>
<div>ProfilesIni profile = new ProfilesIni(); <br />FirefoxProfile myprofile = profile.getProfile("CreatedProfile"); <br />WebDriver driver = new FirefoxDriver("String profileName");</div>
<div>&nbsp;</div>
<div>Hope this helps you.</div>
