### ISSUE TITLE
Remote WebDriver and subclasses in Python fail methods if w3c is not defined

### ISSUE THREAD

**Issue by uchuugaka** [SeleniumHQ/selenium#2472]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

Apologies if the Github repo is not the right place for this yet, here is my observation.

## Expected Behavior -
All methods that check 
if self.w3c:
Should not fail, as the spec is still unfinished.

## Actual Behavior -
Methods such as get_window_size() that check 
if self.w3c:
Fail with a Remote WebDriver or subclass instance having no attribute w3c

**Comment by uchuugaka** [comment]
Seems like there should be a default attribute value assigned of False for now.

**Comment by lukeis** [comment]
@AutomatedTester

**Comment by lukeis** [comment]
@uchuugaka this wasn't in a pip release, was it?

**Comment by uchuugaka** [comment]
No it was not in a release to pypi.
