### ISSUE TITLE
Support for Apple's new Safari Driver

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2475]
I think this has only been done by @lukeis in Python so far?

**Comment by titusfortner** [comment]
Ruby - fd84a1bcc3a9b1b723c7164998236624f139f93f

**Comment by jleyba** [comment]
FYI I'm not planning on installing a macOS Sierra build, so this won't be implemented for nodejs for a while (unless someone else wants to submit a PR)

**Comment by oddui** [comment]
@titusfortner @jleyba I'd like to try putting together a PR for nodejs in the next few weeks, if that's ok.

**Comment by jleyba** [comment]
@oddui Go for it.

**Comment by titusfortner** [comment]
For what it is worth, getting Sierra set up on a VMWare Fusion instance was much easier than I expected.

**Comment by jleyba** [comment]
Support added for nodejs in 0718a9ad45f9fb6365b7b0e09a1b9ade828e6d0a (thanks @oddui!)

**Comment by lukeis** [comment]
this was added to .net in 9f5f45c78393402358b7c78cdcaa89f6d3226442
