### ISSUE TITLE
Ruby Capabilities

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2478]
Might split this up into multiple issues, but wanted to have a discussion with the Ruby community on this first:
1. Each Bridge class has duplicated code for creating capabilities that can be DRY'd up.
2. I'm not sure why Capabilities is name spaced under Remote, because we use them locally as well.
3. Ruby has a weird mix of how it handles capabilities. Some values are explicitly supported and are accessed by symbol, and some values are allowed by default and are accessed by strings, which leads to confusion. Perhaps we support these explicitly?
4. Ruby is supporting a number of different ChromeOption Capabilities that no longer exist
5. Some capabilities are allowed to be parameters when initializing the Bridge, and others are required to be passed in through the DesiredCapabilities object. One way or another, we should make this consistent
6. I also find it weird that we allow (some) values to be accessed by both `caps.foo` and `caps[:foo]` but there might not be a compelling reason to change that.

**Comment by llaskin** [comment]
In minor relation to this bug I have made https://github.com/SeleniumHQ/selenium/pull/3279 which should take care of (3), I think?

**Comment by luke-hill** [comment]
Note on this - From a Ruby Perspective. There is (I believe), issues with some of the ie capabilities which have a `.` in there name. such as `ie.ensureCleanSession`. This is hard to symbolise.

1) Is there a reason this is written as an ie parameter with ie in its name. Wouldn't it be better to pass a warning across along the lines of, capabilities passed in will not be used.

2) If you pass in wrong capabilities, there doesn't seem to be any catchers at the moment, I've tried passing in `caps['hellothere'] = true`, and this seems to work.

Wrt the Bridge class, I did notice some duplication, and mentioned this on Slack, but I would question why the js/css capabilities aren't default true for every class. In my eyes that would be better, still leaving the option to turn them off, but make them all default on.

**Comment by titusfortner** [comment]
As I'm rewriting these, I'm starting with what is accepted as a parameter when initializing the driver in the first place.

When doing:
```
Selenium::WebDriver::Driver.for browser_name, opt
```

The allowed values for keys in the `opt` are:
Any value passed in that is not one of these is going to throw a deprecation notice:
1. `:url`
2. `:port`
3. `:service_args`
4. `:driver_path`
5. `:http_client`
6. `:required_capabilities`
7. `:desired_capabilities`
8. `:options`
9. `:profile`
10. `:marionette`

Anything else that is currently being handled (IE specifically has a number of them) is going to have a deprecation notice specifying that they need to be passed in with the `Remote::Capabilities`.

Making `Options` classes for each driver and `Profile` classes for supported browsers will be done eventually (maybe we can do that in the 'become a committer' workshop at the Selenium Conference. For the time being these will continue to be supported as hashes with string keys that get passed along directly to the remote endpoint.

@twalpole - will this affect anything that Capybara is doing?
@cheezy - do you do any additional handling of parameters in Page Object?
@p0deje - we already discussed this in the Selenium Ruby Slack Channel, but including you in this thread as well.

**Comment by twalpole** [comment]
@titusfortner That shouldn't affect anything Capybara is doing.

**Comment by p0deje** [comment]
@titusfortner It's hanging for a year, let's close this?
