### ISSUE TITLE
Get element attributes

### ISSUE THREAD

**Issue by sandeep048** [SeleniumHQ/selenium#2483]
Should this not be a part of the core selenium API?

A work around is mentioned in [(http://stackoverflow.com/a/27307235/218857)](http://stackoverflow.com/a/27307235/218857) to display all element attributes. But this should be supported in the core API since many people rely on selenium for automation and testing.

`driver.execute_script('var items = {}; for (index = 0; index < arguments[0].attributes.length; ++index) { items[arguments[0].attributes[index].name] = arguments[0].attributes[index].value }; return items;', element)
`

**Comment by lukeis** [comment]
Please log a bug with the w3c spec to request this kind of feature, discussion can happen there if this should be included or not:

https://www.w3.org/Bugs/Public/enter_bug.cgi?comment=&blocked=20860&product=Browser+Test%2FTools+WG&component=WebDriver
