### ISSUE TITLE
Maven 3.0 - sources.jar contains more than it should

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/selenium#2485]
This is an issue with our version of Buck. It's bundling more than it should in the sources jar. Will also need to handle selenium-java artifact (which has no sources, this is already fixed for javadoc).

This is not a blocker for 3.0 beta, but we should fix it for the official 3.0 release.

**Comment by shs96c** [comment]
I'm going to start looking at this now. I suspect it'll be enough to change how the various java archiving rules collect their dependencies for packaging and then check those deps for sources. It'll also make the javadocs easier to generate.

**Comment by shs96c** [comment]
Fixed within Buck
