### ISSUE TITLE
Selenium IDE: Check Box action is recorded as Click action in IDE

### ISSUE THREAD

**Issue by arifullah** [SeleniumHQ/selenium#2486]
## Meta -

OS:  
 Windows 8.1
Selenium Version:  
IDE
## Steps to reproduce -

https://jsfiddle.net/gy972x2x/

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://jsfiddle.net/" />
<title>check Box</title>
</head>
<body>

<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">check Box</td></tr>
</thead><tbody>
<tr>
    <td>open</td>
    <td>/gy972x2x/</td>
    <td></td>
</tr>
<tr>
    <td>selectFrame</td>
    <td>result</td>
    <td></td>
</tr>
<tr>
    <td>click</td>
    <td>//input</td>
    <td></td>
</tr>

</tbody></table>

</body>
</html>

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
