### ISSUE TITLE
Unable to use existing Firefox profile

### ISSUE THREAD

**Issue by dirkbike** [SeleniumHQ/selenium#2487]
## Meta -
OS:  Windows
Selenium Version:  2.53.6
Browser:  Firefox
Browser Version:  46.0.1

## Expected Behavior -
Should be able to use an existing Firefox profile:
```
>>> from selenium import webdriver
>>> profile = webdriver.FirefoxProfile(r'C:\Users\Name\AppData\Local\Mozilla\Firefox\Profiles\df734jds.default')
>>> profile.path
'C:\\Users\\Name\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\df734jds.default'
```
## Actual Behavior -
Instead selenium will create a temporary profile anyway:
```
>>> from selenium import webdriver
>>> profile = webdriver.FirefoxProfile(r'C:\Users\Name\AppData\Local\Mozilla\Firefox\Profiles\df734jds.default')
>>> profile.path
'C:\\Users\\Name\\AppData\\Local\\Temp\\tmpa98ejaaa\\webdriver-py-profilecopy'
```
## Steps to reproduce -
The above commands were run in Python 3.4.3

**Comment by lukeis** [comment]
python (and any other selenium client) will always make a temporary profile, but it should be copying the profile specified to the temporary location. Is that not the case? All settings should be as specified in the temporary profile.

With that being said, I don't see any issue here. If you can update with a more accurate script showing unexpected behavior we can reopen the bug.

**Comment by dirkbike** [comment]
I see, then maybe the configuration I was expecting isn't carried as part of the profile to begin with. I had setup a custom Security Device in Firefox and was expecting it to be present when Firefox was launched via selenium.
