### ISSUE TITLE
Connection reset  On Connect with C# Driver on Windows Server 2012R2 - 2.53.1

### ISSUE THREAD

**Issue by Gentlehag** [SeleniumHQ/selenium#2488]
## Meta -
Windows Server 2012 R2
Selenium Version:   Tested with 2.52.0 2.53.1

Browser:  
FireFox: 47.0.1
When I Try to create the driver with c# code I get 

>  Selenium errorSystem.InvalidOperationException: Connection reset 
>    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) 
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) 
>    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) 
>    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) 
>    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities) 

It worked for monthes, no code changes done, no reconfigurations done (only windows and browser auto updates)
 any hint what can be wrong?

Here the startup log

> 06:39:38.612 INFO [1] org.openqa.grid.selenium.GridLauncher - Launching a standalone Selenium Server
> 06:39:38.663 INFO [1] org.openqa.selenium.server.SeleniumServer - Writing debug logs to selenium.log
> 06:39:38.663 INFO [1] org.openqa.selenium.server.SeleniumServer - Java: Oracle Corporation 25.73-b02
> 06:39:38.663 INFO [1] org.openqa.selenium.server.SeleniumServer - OS: Windows Server 2012 R2 6.3 x86
> 06:39:38.671 INFO [1] org.openqa.selenium.server.SeleniumServer - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
> 06:39:38.718 INFO [1] org.openqa.selenium.remote.server.DefaultDriverProvider - Driver class not found: com.opera.core.systems.OperaDriver
> 06:39:38.718 INFO [1] org.openqa.selenium.remote.server.DefaultDriverFactory - Driver provider com.opera.core.systems.OperaDriver is not registered
> 06:39:38.722 INFO [1] org.openqa.selenium.remote.server.DefaultDriverSessions - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
> registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN8
> 06:39:38.723 INFO [1] org.openqa.selenium.remote.server.DefaultDriverProvider - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
> 06:39:38.723 INFO [1] org.openqa.selenium.remote.server.DefaultDriverFactory - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
> 06:39:38.812 INFO [1] org.openqa.selenium.server.SeleniumServer - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
> 06:39:38.812 INFO [1] org.openqa.grid.selenium.GridLauncher - Selenium Server is up and running
>

**Comment by netzulo** [comment]
Tested, if working on my Server 2012 R2 like Hub and Node from C#, close this Issue ^^
