### ISSUE TITLE
Cookies are not served in spite of beeing in session

### ISSUE THREAD

**Issue by Gorgia** [SeleniumHQ/selenium#2489]
## Meta -
OS:  Linux Ubuntu
Selenium Version:  2.53.0
Browser:  Firefox
Browser Version:  45.0.2

## Expected Behavior -
Session cookies to be served also in from new RemoteWebDriver if it is created from the same session
## Actual Behavior -
Session cookies, in spite of beeing in the session, are not forwarded
## Steps to reproduce -

//login to a page
webdriver1 [login function]
String latesturl = webdriver1.getCurrentUrl()
//Retrieve the remote webdriver by session id with
 capabilities.setCapability("webdriver.remote.sessionid", sessionId) -> webdriver2
//get the cookies
Set cookies = webdriver2.manage.getCookies()
//so far so good...
//get the latest url 
webdriver2.get(latesturl)
//and you are logged out?!?!?!?!?!
//why?
//cookies are not server in spite of being in session!
Set<Cookies> cookies2 = webdriver2.manage().getCookies()
webdriver2.get(latesturl) //to set cookies
cookies2.forEach { cookie ->  newWebDriver.manage().addCookie(cookie) } 
newWebDriver.navigate().refresh()
//and you are loggedin again

I believe this is not a desired behaviour, cookies should be served from session

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
