### ISSUE TITLE
[safaridriver] right click doesn't work in safari

### ISSUE THREAD

**Issue by sophiecdd** [SeleniumHQ/selenium#2490]
## Meta -
OS:  OSX 10.11.6
Selenium Version:  2.53.0
Browser:  safari
Browser Version:  9.1.2

## Expected Behaviour -
intern framework is used, both cases below worked fine in Chrome on both windows and Mac
1> .findByCssSelector(elementSelector).clickMouseButton(2) should perform a right click on the element, which in my case will bring up a context menu
2> .findByCssSelector(elementSelector).pressKeys(keys.CONTROL).click().pressKeys(keys.CONTROL) should perform a right click

## Actual Behavior -
both cases perform a left click like action, context menu doesn't pop
based on the info in log, it seems worked fine and clicked button 2 in the first case, pressed CONTROL key + click in the second case, but on UI the popup didn't show.
1>
   {
        "level": "INFO",
        "message": "org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [execute script: return (function simulateMouse(kwArgs) {\n\tvar position = kwArgs.position;\n\n\tfunction dispatch(kwArgs) {\n\t\tvar event = document.createEvent('MouseEvents');\n\t\tevent.initMouseEvent(\n\t\t\tkwArgs.type,\n\t\t\tkwArgs.bubbles || true,\n\t\t\tkwArgs.cancelable || false,\n\t\t\twindow,\n\t\t\tkwArgs.detail || 0,\n\t\t\twindow.screenX + position.x,\n\t\t\twindow.screenY + position.y,\n\t\t\tposition.x,\n\t\t\tposition.y,\n\t\t\tkwArgs.ctrlKey || false,\n\t\t\tkwArgs.altKey || false,\n\t\t\tkwArgs.shiftKey || false,\n\t\t\tkwArgs.metaKey || false,\n\t\t\tkwArgs.button || 0,\n\t\t\tkwArgs.relatedTarget || null\n\t\t);\n\n\t\treturn kwArgs.target.dispatchEvent(event);\n\t}\n\n\tfunction click(target, button, detail) {\n\t\tif (!down(target, button)) {\n\t\t\treturn false;\n\t\t}\n\n\t\tif (!up(target, button)) {\n\t\t\treturn false;\n\t\t}\n\n\t\treturn dispatch({\n\t\t\tbutton: button,\n\t\t\tcancelable: true,\n\t\t\tdetail: detail,\n\t\t\ttarget: target,\n\t\t\ttype: 'click'\n\t\t});\n\t}\n\n\tfunction down(target, button) {\n\t\treturn dispatch({\n\t\t\tbutton: button,\n\t\t\tcancelable: true,\n\t\t\ttarget: target,\n\t\t\ttype: 'mousedown'\n\t\t});\n\t}\n\n\tfunction up(target, button) {\n\t\treturn dispatch({\n\t\t\tbutton: button,\n\t\t\tcancelable: true,\n\t\t\ttarget: target,\n\t\t\ttype: 'mouseup'\n\t\t});\n\t}\n\n\tfunction move(currentElement, newElement, xOffset, yOffset) {\n\t\tif (newElement) {\n\t\t\tvar bbox = newElement.getBoundingClientRect();\n\n\t\t\tif (xOffset == null) {\n\t\t\t\txOffset = (bbox.right - bbox.left) * 0.5;\n\t\t\t}\n\n\t\t\tif (yOffset == null) {\n\t\t\t\tyOffset = (bbox.bottom - bbox.top) * 0.5;\n\t\t\t}\n\n\t\t\tposition = { x: bbox.left + xOffset, y: bbox.top + yOffset };\n\t\t}\n\t\telse {\n\t\t\tposition.x += xOffset || 0;\n\t\t\tposition.y += yOffset || 0;\n\n\t\t\tnewElement = document.elementFromPoint(position.x, position.y);\n\t\t}\n\n\t\tif (currentElement !== newElement) {\n\t\t\tdispatch({ type: 'mouseout', target: currentElement, relatedTarget: newElement });\n\t\t\tdispatch({ type: 'mouseleave', target: currentElement, relatedTarget: newElement, bubbles: false });\n\t\t\tdispatch({ type: 'mouseenter', target: newElement, relatedTarget: currentElement, bubbles: false });\n\t\t\tdispatch({ type: 'mouseover', target: newElement, relatedTarget: currentElement });\n\t\t}\n\n\t\tdispatch({ type: 'mousemove', target: newElement, bubbles: true });\n\n\t\treturn position;\n\t}\n\n\tvar target = document.elementFromPoint(position.x, position.y);\n\n\tif (kwArgs.action === 'mousemove') {\n\t\treturn move(target, kwArgs.element, kwArgs.xOffset, kwArgs.yOffset);\n\t}\n\telse if (kwArgs.action === 'mousedown') {\n\t\treturn down(target, kwArgs.button);\n\t}\n\telse if (kwArgs.action === 'mouseup') {\n\t\treturn up(target, kwArgs.button);\n\t}\n\telse if (kwArgs.action === 'click') {\n\t\treturn click(target, kwArgs.button, 0);\n\t}\n\telse if (kwArgs.action === 'dblclick') {\n\t\tif (!click(target, kwArgs.button, 0)) {\n\t\t\treturn false;\n\t\t}\n\n\t\tif (!click(target, kwArgs.button, 1)) {\n\t\t\treturn false;\n\t\t}\n\n\t\treturn dispatch({\n\t\t\ttype: 'dblclick',\n\t\t\ttarget: target,\n\t\t\tbutton: kwArgs.button,\n\t\t\tdetail: 2,\n\t\t\tcancelable: true\n\t\t});\n\t}\n}).apply(this, arguments);, [{**button=2, action=click**, position={x=264.70899963378906, y=460.5}}]]",
        "timestamp": 1468959524610
    },
2>
    {
        "level": "INFO",
        "message": "org.openqa.selenium.remote.server.DriverServlet org.openqa.selenium.remote.server.rest.ResultConfig.handle Done: [execute script: return (function simulateKeys(keys) {\n\tvar target = document.activeElement;\n\n\tfunction dispatch(kwArgs) {\n\t\tvar event = document.createEvent('KeyboardEvent');\n\t\tevent.initKeyboardEvent(\n\t\t\tkwArgs.type,\n\t\t\tkwArgs.bubbles || true,\n\t\t\tkwArgs.cancelable || false,\n\t\t\twindow,\n\t\t\tkwArgs.key || '',\n\t\t\tkwArgs.location || 3,\n\t\t\tkwArgs.modifiers || '',\n\t\t\tkwArgs.repeat || 0,\n\t\t\tkwArgs.locale || ''\n\t\t);\n\n\t\treturn target.dispatchEvent(event);\n\t}\n\n\tfunction dispatchInput() {\n\t\tvar event = document.createEvent('Event');\n\t\tevent.initEvent('input', true, false);\n\t\treturn target.dispatchEvent(event);\n\t}\n\n\tkeys = Array.prototype.concat.apply([], keys.map(function (keys) {\n\t\treturn keys.split('');\n\t}));\n\n\tfor (var i = 0, j = keys.length; i < j; ++i) {\n\t\tvar key = keys[i];\n\t\tvar performDefault = true;\n\n\t\tperformDefault = dispatch({ type: 'keydown', cancelable: true, key: key });\n\t\tperformDefault = performDefault && dispatch({ type: 'keypress', cancelable: true, key: key });\n\n\t\tif (performDefault) {\n\t\t\tif ('value' in target) {\n\t\t\t\ttarget.value = target.value.slice(0, target.selectionStart) + key +\n\t\t\t\t\ttarget.value.slice(target.selectionEnd);\n\t\t\t\tdispatchInput();\n\t\t\t}\n\t\t\telse if (target.isContentEditable) {\n\t\t\t\tvar node = document.createTextNode(key);\n\t\t\t\tvar selection = window.getSelection();\n\t\t\t\tvar range = selection.getRangeAt(0);\n\t\t\t\trange.deleteContents();\n\t\t\t\trange.insertNode(node);\n\t\t\t\trange.setStartAfter(node);\n\t\t\t\trange.setEndAfter(node);\n\t\t\t\tselection.removeAllRanges();\n\t\t\t\tselection.addRange(range);\n\t\t\t}\n\t\t}\n\n\t\tdispatch({ type: 'keyup', cancelable: true, key: key });\n\t}\n}).apply(this, arguments);, [[]]]",
        "timestamp": 1468956901104
    },

**Comment by daluu** [comment]
For reference, probably related to this: https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4152

**Comment by lukeis** [comment]
With the release of Safari 10, Apple now offers official support WebDriver. Because of this, the Selenium project no supports the legacy implementation from 2.x.

Users are advised to switch to Apple's driver and file bugs at 
https://bugreport.apple.com/  

We are no longer tracking issues for Selenium's SafariDriver and thus closing this issue.

**Comment by daluu** [comment]
FYI, because Apple doesn't share reported bugs and their status updates to the public, only the reporter of the bug, it would be good for those who file bugs to also file a duplicate at

https://openradar.appspot.com/

and update the clone whenever there is an update to the filed bug, so that the rest of the community can check status and not need to file duplicate bugs.

It's unfortunate that Apple chose to have a closed bug reporting system. Confidential bugs may make sense, but many aren't.
