### ISSUE TITLE
facing selenium issues only in IE browser and the code is working fine in other browsers

### ISSUE THREAD

**Issue by NaveenJayaramaiah** [SeleniumHQ/selenium#2492]
## Meta -
OS:  Windows 7

Selenium Version:  2.50.1

Browser:   Internet Explore

When I open my application though automation its start blinking and because of these the element are not able to click or identify, these issues are seen only in Internet explorer browser.
I am using selenium 2.50.1 version and IE11. I am performing automation testing using junit-cucumber-selenium-java. My scripts are working 100% fine in other browsers expect in IE but there is a need to run my scripts in IE. I am setting  following desired capabilities for IE11:
DesiredCapabilities ieCapabilities=DesiredCapabilities.internetExplorer();
	ieCapabilities.setCapability("nativeEvents",false);       	ieCapabilities.setCapability("unexpectedAlertBehaviour","accept");
	ieCapabilities.setCapability("ignoreProtectedModeSettings",true);
	ieCapabilities.setCapability("disable-popup-blocking",true);
	ieCapabilities.setCapability("PersistentHover",false);
	ieCapabilities.setCapability("RequireWindowFocus ", true);
	ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGN ORING_SECURITY_DOMAINS,true);		ieCapabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS,true);

But when I am using these capabilities I am unable to perform MouseOver function in my application. when I won’t use these capabilities the jss code which is written in my application is not loading properly because of this I am getting some unexpected behaviors like my application is blinking when loaded because of this its giving error like elements not found, cannot click on element, cannot locate element and so on. Is there any other capabilities I need to add? I am not finding.

Browser Version:  IE11

**Comment by Harsha509** [comment]
Hi There,

I am acing a similar issue , where IE screen flickers when i execute my tests in IE 11. Please provide any workaround for this.

Thanks in advance,
Happy Tester

**Comment by timbru31** [comment]
Having issues to click on elements in IE10, too #2516

**Comment by ambikashri** [comment]
Having issues to fill form in IE 10 and IE 11 using selnium webdriver 2.53.1 and 32 bit version of IEWebdriver.

**Comment by Vittal89** [comment]
Having issues in executing robot framework tests in IE 11.Encountered followig errors

Error 1:
Error: [$rootScope:inprog] $digest already in progress http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24digest 
 
Error 2:
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: [] http://errors.angularjs.org/1.3.15/$rootScope/infdig?p0=10&p1=%5B%5D     
Tried with IE driver 2.53.1 
Robot framework 3.0
Python 2.7.11
Win 7
Note : Execution works fine in Chrome and Firefox browsers

**Comment by jimevans** [comment]
You have added this line in your code.
    ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);

By doing so, you invalidate the driver. Setting the protected mode settings for IE is required for proper functioning.

**Comment by NaveenJayaramaiah** [comment]
i have used the code which you have mentioned
