### ISSUE TITLE
Selenium web remote driver can be slow for some website

### ISSUE THREAD

**Issue by HackToday** [SeleniumHQ/selenium#2493]
## Meta -

OS:  CentOS 7

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  
47.0.1
## Expected Behavior -

Python unitest should run quickly
## Actual Behavior -

Python unittest run slow
## Steps to reproduce -

- Setup remote selenium server, suppose ip is `10.10.12.23`
- Install selenium client through pip
- Then run following python test

```
#encoding=utf8
import unittest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class PythonOrgSearch(unittest.TestCase):

    def setUp(self):
        print "Setup now"
        self.driver = webdriver.Remote(desired_capabilities=webdriver.DesiredCapabilities.FIREFOX, command_executor='http://10.10.12.23:4444/wd/hub')
    def test_search_in_python_org(self):
        print "running simple now"
        driver = self.driver
        driver.get("http://www.python.org")
        self.assertIn("Python", driver.title)
        print "find title here"
        elem = driver.find_element_by_name("q")
        elem.send_keys("pycon")
        elem.send_keys(Keys.RETURN)
        print "send search ops"
        assert "No results found." not in driver.page_source


    def tearDown(self):
        self.driver.quit()

if __name__ == "__main__":
    unittest.main()

```
- The running result is:

```
Setup now
running simple now


find title here
send search ops
.
----------------------------------------------------------------------
Ran 1 test in 187.743s

OK

```

I did not know why it would spend 187 seconds. It seems some default wait time was setting in selenium server.  I did not want one test run so long time

**Comment by HackToday** [comment]
@shs96c  Could you help it ? Thanks

**Comment by Lucasgermani** [comment]
got the same problem running on CentOS 7 and Selenium 2.53.1.

**Comment by lukeis** [comment]
something with CentOS then? does it occur only through the standalone server?

what happens if you use just python?

    self.driver = webdriver.Firefox()


(for what's it's worth on OSX the test runs in about 5 seconds ;) )

**Comment by cgoldberg** [comment]
fwiw, the example from the OP runs fine on Ubuntu 16.04.   I used python bindings 2.53.6 , java -jar selenium-server-standalone-2.53.1.jar, and FF 45

script output:
```
Setup now
running simple now
find title here
send search ops
.
----------------------------------------------------------------------
Ran 1 test in 3.439s
```

**Comment by HackToday** [comment]
hi @lukeis  run with 
```
self.driver = webdriver.Firefox()
```
Got the same issue, result as below:
```
Setup now
running simple now
find title here
send search ops
.
----------------------------------------------------------------------
Ran 1 test in 186.104s

OK
```

**Comment by Poojaya** [comment]
I am getting Invalid Server URL Error.  I gave the remote ip server address correctly.could u pls help me?

**Comment by richardbarabe** [comment]
I might have found the problem.  
I've been trying for weeks to find why our selenium (webdriver) test suite took around 6 hours in some environments and les than 3 hoursin others.

On slow environment, we saw firefox boot and go really fast, than slower and slower at some point where it took many seconds just to go from a page to another.  At the same time, asking a same pages on a different browser from the same running web server was super fast.

I managed to make the test suite les than 3 hours by downgrading the firefox version to 45.5.1 (esr version).
Some of my collegues had it fast with firefox 46 too.  But 46.0.1+ did run slow for us.

If you try, you can monitor cpu usage of firefox while running tests, slow vs fast versions had very different cpu usage graphs.

Tried on ubuntu 12.04 and 14.04.  Hope it help someone save time.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
