### ISSUE TITLE
Unable to run Selenium test with an Imporsenated context - IEWebdriver

### ISSUE THREAD

**Issue by anandacc** [SeleniumHQ/selenium#2494]
## Meta -

OS:  

Selenium Version:  

Browser:  Internet Explorer

When running Selenium tests under an Impersonated user context, Getting exception with IEWebdriver:
1. Cannot start the driver service on http://localhost:1878/

If we are running normallr (with out Impersonation) every thing is working as expected. 
Any clues?

**Comment by barancev** [comment]
Sorry for leaving this issue unanswered.

It's rather a question than an issue, for questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
