### ISSUE TITLE
SSL_ERROR_HANDSHAKE_FAILURE_ALERT

### ISSUE THREAD

**Issue by chantalv** [SeleniumHQ/selenium#2495]
## Meta -

OS:  windows 7 Enterprise x64

Selenium Version:  2.53.1

Browser:  Firefox 47.0.1

Browser Version:  

47.0.1
## Expected Behavior -

Trying to reach one page https .. associated to a certificate.
I don't get the popup 
"User identication request
Choose a certificate to present as identification"

Can you advise.. 
## Actual Behavior -

I directly get 
Secure Connection Failed

An error occurred during a connection to ................................ SSL peer was unable to negotiate an acceptable set of security parameters. Error code: SSL_ERROR_HANDSHAKE_FAILURE_ALERT
## Steps to reproduce -

Ive already tried different things like playing with
firefoxProfile.setAcceptUntrustedCertificates(true);
firefoxProfile.setAssumeUntrustedCertificateIssuer(true);
firefoxProfile.setPreference("network.automatic-ntlm-auth.trusted-uris", "TheURL");

or

//DesiredCapabilities dc = DesiredCapabilities.firefox();
 //dc.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
 //dc.setCapability("acceptSslCerts",true);
 //return new   FirefoxDriver(dc);

Current Code  : 

public static FirefoxDriver getFireFoxDriver (Config config, String pathFirefoxBinary) {
        try {
            File pathToBinary = new File(pathFirefoxBinary);
            FirefoxBinary ffBinary = new FirefoxBinary(pathToBinary);
             FirefoxProfile firefoxProfile = new FirefoxProfile();
                        return new FirefoxDriver(ffBinary,firefoxProfile);
        } catch (WebDriverException exc) {
            throw new SanityCheckException(config, "Technical Error with Firefox Driver",
                    "Could  not retrieve the firefox driver");
        }

```
}
```

---

The return driver is used later in the code ...
driver.get(config.getTheAppUrl());

=> Stays blocked on the following message 

Secure Connection Failed

An error occurred during a connection to ................................ SSL peer was unable to negotiate an acceptable set of security parameters. Error code: SSL_ERROR_HANDSHAKE_FAILURE_ALERT

Thanks

**Comment by AcousticGuitar** [comment]
Same thing happens to me I logged about it here...  showing a full communications trace and the fact that the server side certificate exchange times-out because the server doesn't finish the handshake. 

[The Stack Over Flow Question](http://stackoverflow.com/questions/38515256/firefox-webdriver-2-53-doesnt-work-with-firefox-47-0-1)

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
