### ISSUE TITLE
Click doesn't work if the element has border-radius set and it's partially covered by another element (2.51.0+)

### ISSUE THREAD

**Issue by aliaksandrbasau** [SeleniumHQ/selenium#2497]
## Meta -
OS: 
Windows 7

Selenium Version: 
2.51.0+

Browser: 
Firefox

Browser Version: 
Firefox 44.0.2+

## Expected Behavior -
An element should be click or an exception should be raised if it's partially covered.

## Actual Behavior -
The click was performed outside the element.

## Steps to reproduce -
The issue is probably caused by 65dbe9a154469fcad6318fba82452805281d6159 and is reproducible when the element has 'border-radius' set, its middle point is covered by another element, and some corner points are not covered. It clicks point that doesn't belong to the element. As a result the element is not clicked and the exception is not raised.

I have also seen the issue in cases when the element didn't have border-radius set. In that cases WebDriver clicked one pixel right from lower right corner.

jsfiddle - https://jsfiddle.net/aliaksandr_basau/tve0sf2w/
Code:
```
    [TestFixture]
    public class Tests
    {
        [Test]
        public void Verify()
        {
            using (var driver = new FirefoxDriver())
            {
                try
                {
                    driver.Navigate().GoToUrl("https://jsfiddle.net/aliaksandr_basau/tve0sf2w/embedded/result/");

                    driver.SwitchTo().Frame(0);

                    driver.ExecuteScript("window.scrollBy(0,990)");

                    var searchBtn = driver.FindElement(By.ClassName("btn"));

                    searchBtn.Click();

                    IAlert alert = null;
                    try
                    {
                        alert = driver.SwitchTo().Alert();
                    }
                    catch (NoAlertPresentException)
                    {
                    }

                    if (alert != null)
                    {
                        alert.Accept();
                    }

                    Assert.NotNull(alert, "The button was not clicked.");
                }
                finally
                {
                    driver.Close();
                    driver.Quit();
                }
            }
        }
    }
```

**Comment by lukeis** [comment]
thanks for the excellent reproduction script!

**Comment by aliaksandrbasau** [comment]
Many thanks for so quick fixing, @lukeis! Do you know when to expect a new release with the fix?

**Comment by lukeis** [comment]
not certain when, we're working toward a release of 3.0 beta... which you can try out an 'alpha' here:
http://ci.seleniumhq.org:8080/job/Build_All_Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar

keep in mind, GeckoDriver is default now in 3.0, you'll have to set the Capability "marionette": false if you want to use the 'old' Firefox Driver
