### ISSUE TITLE
Python test suite's webserver.py can hang the terminal when Ctrl-C in middle of test

### ISSUE THREAD

**Issue by burg** [SeleniumHQ/selenium#2498]
I think we need to set the webserver thread to be a "daemon" thread, so it can be terminated safely.

**Comment by lukeis** [comment]
@davehunt fyi... if you're in the middle of this with your pytest refactor and this seems easy for you to set, please do :)

**Comment by lukeis** [comment]
@burg dave's refactoring changed this stuff... is it still an issue?

https://github.com/SeleniumHQ/selenium/blob/master/py/conftest.py#L24-L29

**Comment by burg** [comment]
I will check on this the next time i do a re-import.

**Comment by barancev** [comment]
Let's suppose the issue has been fixed. Feel free to reopen if it is still actual.

**Comment by lmtierney** [comment]
I believe I fixed this with the latest change I made to the webserver. It would be good to know for sure though... You know where to find us @burg
