### ISSUE TITLE
network.http.max-connections-per-server doesn't exist in Firefox45 preferences

### ISSUE THREAD

**Issue by xmhubj** [SeleniumHQ/selenium#2500]
## Meta -
OS:  
Windows 7, Redhat 7(or more platforms)

Selenium Version:  
2.53.0

Browser:  
Firefox

Browser Version:  
Mozilla Firefox 45.2.0

## Expected Behavior -
The preference set in `webdriver_prefs.json` should exist in about:config

## Actual Behavior -
`network.http.max-connections-per-server` doesn't exist in Firefox45 preferences. Only a similar firefox preference `network.http.max-persistent-connections-per-server` in about:config.

## Steps to reproduce -
Look into the source code:  [selenium/javascript/firefox-driver/webdriver.json#L64](https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/webdriver.json#L64)

**Comment by xmhubj** [comment]
Not sure this preference should be update or not. It's a secret preference or something?

**Comment by lukeis** [comment]
appears this preference was removed from firefox and is no longer necessary for us to set.
