### ISSUE TITLE
Could remote webdriver support cookies as part of the RPC calls?

### ISSUE THREAD

**Issue by R3D4C73D** [SeleniumHQ/selenium#2505]
## Meta -
OS: Linux/Docker
Selenium Version:  2.53.6, Python
Browser:  phantomjs
Browser Version:  latest snapshot

## Expected Behavior -
Selenium remote webdriver should respect cookies for load balancing purposes
## Actual Behavior -
Selenium remote webdriver completely disregards cookies
## Steps to reproduce -
I'm attempting to run haproxy as a load balancer for a cluster of phantomjs webdriver servers.  Remote webdriver has its own setup for session ids where a new session id is sent in the body of the response when a `POST /session` request is made.  Then, subsequent requests use the session id in the URL, such as `GET /sessions/SESSION_ID/source`.  This is super inconvenient for systems like haproxy.  Haproxy can just send its own cookies along to handle session management (i.e. tying the session to which server it balanced the initial request to).  But, as it stands, the remote webdriver code disregards cookies, probably because the RPC API doesn't use them.  But adding support could only help things, right?

**Comment by AutomatedTester** [comment]
We support Selenium grid as a way of spreading the load of testing between nodes and won't be implementing this.
