### ISSUE TITLE
Ruby Event Listeners

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2506]
While trying to [implement Watir's After Hooks](https://github.com/watir/watir-webdriver/pull/433) with Selenium Event Listeners, it looks like not everything we would want to have as a Listener is implemented. The linked PR shows the monkey patches that were needed. 

There were also a number of places that required aliasing due to mismatching of camel case and snake case, so it might be best to [fix up the Ruby Commands](https://github.com/SeleniumHQ/selenium/issues/2479) first as well.

**Comment by titusfortner** [comment]
@Rodney-QAGeek - this might be a good place to start for your issues. Let me know if you want to pair on it.

**Comment by Rodney-QAGeek** [comment]
Totally! This is exactly what I was hoping to see soon.

**Comment by titusfortner** [comment]
Ok, I just realized that the latest the Ruby release 3.0.2 likely broke some of the Event Listeners. @Rodney-QAGeek do you have availability to help with this?

**Comment by Rodney-QAGeek** [comment]
@titusfortner Let's sync up this Monday night and work on this!

**Comment by lmtierney** [comment]
I suppose you didn't say **which** Monday night...

**Comment by p0deje** [comment]
@titusfortner It's hanging for a year, let's close this?
