### ISSUE TITLE
python client bindings do not support remote https selenium grid endpoints.

### ISSUE THREAD

**Issue by mehmetg** [SeleniumHQ/selenium#2509]
## Meta -
OS:  OSX
Selenium Version:  2.53.6 on Python 2.7.12
Browser:  NA
Browser Version:  NA

## Expected Behavior -
When specified a https grid location like `https://ondemand.saucelabs.com/wd/hub` user should be able to run tests the same as the http endpoint.
## Actual Behavior -
The python client throws the following error.
```
>               % (hostname, ', '.join(map(repr, dnsnames))))
E           CertificateError: hostname '66.201.41.7' doesn't match either of '*.browserstack.com', 'browserstack.com'

/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py:272: CertificateError
```
## Steps to reproduce -
Attempt to start any session using the `https://ondemand.saucelabs.com/wd/hub` url for command executor.

**Comment by lukeis** [comment]
to disable the host name to ip address resolution do this instead:

    from selenium.webdriver.remote.remote_connection import RemoteConnection
    hostname = "https://ondemand.saucelabs.com/wd/hub"
    executor = RemoteConnection(hostname, resolve_ip=False)
    driver = webdriver.Remote(executor, capabilities)

**Comment by koczkatamas** [comment]
This a bug IMHO and encourages using non-secure communication by default (without workarounds).

If the URL scheme is https then you should avoid using IP instead of hostname by default, because as long as the HTTPS certificate comes from a trusted CA, it will never contain an IP address instead of a hostname thus CertificateError will be raise for every HTTPS endpoint.

Adding `and parsed_url.scheme != "https"` here would suffice I think: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L170

**Comment by mehmetg** [comment]
@koczkatamas: I agree with the reasoning, but I would consider it an improvement rather than a bug.

**Comment by koczkatamas** [comment]
I would not.

By today's standards it should be a baseline criteria that a product supports - or if I may - defaults to the best security option available. I would say nowadays using HTTPS should not be such a difficulty as it is with selenium right now.

**Comment by mehmetg** [comment]
Do you of the top of your head know, if local instances of standalone See
server support HTTPS? I believe they do not. My vote is for default support
or better docs whichever.

I am not a contributor, so you probably open a new issue to he heard by the
contributors.

**Comment by koczkatamas** [comment]
I am aware that not everyone will use HTTPS. That's OK (although I would be happier if they were, but I understand their reasons).

I am saying that if somebody wants to use HTTPS, then it should work out-of-box, without using nasty workarounds. So if you decide that you will use HTTPS and you just change the URL from http to https then it should work (if the server supports HTTPS and the certificate is a valid, trusted cert, etc).

Yep, I am thinking about opening a new issue, thanks for the tip.

**Comment by cgoldberg** [comment]
> I am thinking about opening a new issue

@koczkatamas 
why not submit a pull request?
