### ISSUE TITLE
RemoteWebDriver throwing ClassCastException when switching to Alert

### ISSUE THREAD

**Issue by prashum2000** [SeleniumHQ/selenium#2510]
OS:  Windows 8.1 Pro
Selenium Version:  2.53.1
Browser: Firefox 47  

Browser Version:   47, 64 bit

## Expected Behavior -

- Switches to Alert and Accepts it

## Actual Behavior -

- throws below excption:
 java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

## Steps to reproduce -

- In my test, I have a functionality, which clicks on a link and the page opens in a new window. On the newly opened page, there is a javascript alert that comes up. I need to accept the alert to continue the test. The exception happening when trying to switch to the alert.

- this exception happens only when using RemoteWebDriver

- this exception doesn't happen with FirefoxDriver

Thanks
Prashant

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
