### ISSUE TITLE
Clickandhold , MoveToElement , MoveByoffset and Release chain action dosn't give desired output for dom which implemented with hammer.js

### ISSUE THREAD

**Issue by sujithsuresh05** [SeleniumHQ/selenium#2511]
## Meta -

OS:  windows 8

Selenium Version:  2.53

Browser:  Firefox 46.01

Browser Version:  46.01

## Expected Behavior - We have an website which developed using hammer.js  , where have an user action to draw the highlighter. We tried to automate those with selenium webdriver actions chain action code and that you can find below

```
Actions act = new Actions(chromeDriv);
 act.ClickAndHold(annotHolder).MoveToElement(annotHolder, 50, 50).MoveToElement(annotHolder).MoveByOffset(200, 150).Release().Perform();
```
we expected a result that draw an highlighter over an div area.

the above code works fine before implementing hammer support by developing team.
## Actual Behavior - it won't draw anything , and crashed if the area have scroll bar.

My assumption is that by default driver goes to center of the element.
## Steps to reproduce -

**below code is an example for drag drop a div element implemented using hammer.js . Try to drag and drop using webdriver action _using click and hold and release**_

```
<!DOCTYPE html>
<html>

<head>
   <title>Test</title>
    <script type="text/javascript" src="hammer.js"></script>
   <style type="text/css">
       #drag {
            background: blue;
            width: 100px;
            height: 100px;
            /*display: inline-block;*/
            position: absolute;
            z-index: 1;
            /*top:50px;
            left:50px;*/
        }
       #drop{
            background: gray;
            width: 400px;
            height: 400px;
            position: relative;
            top:127px;
        }
    </style>
</head>

<body>
    <div id="drag">Drag</div>

<script type="text/javascript">
    var stage = document.getElementById('drag');
    var manager = new Hammer.Manager(stage);
    var Pan = new Hammer.Pan();
    manager.add(Pan);

    var deltaX = 0;
    var deltaY = 0;
    var panstart = true;
    var offsetLeft,offsetTop;
    manager.on('panstart', function(event) {
        console.log(event)

    })
    manager.on('panmove', function(event) {
    console.log(event)
    stage.style.left =  100 + 'px';
      stage.style.top = 100+ 'px';

    });
    manager.on('panend', function(event) {
console.log(event)      
        console.log('end clientY:' + event.clientY +' clientX: '+ event.clientX + ' screenX :' + event.screenX+ 'screenY :' + event.screenY)

    });
</script>

</body>

</html>
```

**Comment by Paul167** [comment]
The hammer.js mouse input handler relies on the MouseEvent.which property, that is not defined for the events generated by the WebDriver. In other words the hammer.js is not able to determine that the left mouse button is pressed because the WebDriver's mouse event is not fully equivalent to the native mouse event. That was the source of the problems in my case. See the discussion under [#375](https://github.com/SeleniumHQ/selenium/issues/2191) and [hammer.js #976](https://github.com/hammerjs/hammer.js/issues/976) for details.

Personally I think that the MouseEvent.which property should also be added to the WebDriver events, to emulate the native browser behavior more accurately.

**Comment by diemol** [comment]
Is this issue still valid if the most recent versions are used?

**Comment by AutomatedTester** [comment]
closing as no reply from user
