### ISSUE TITLE
IE hangs when switching windows

### ISSUE THREAD

**Issue by BBinottoADC** [SeleniumHQ/selenium#2513]
## Meta -

OS:  Windows 7
Selenium Version:  2.53.1
Browser:  Internet Explorer
Browser Version:  11.0.9600.18349
## Expected Behavior -

The test consists of 3 pages. 
Step 1: The first page gets loaded and a button click opens page 2 in a new browser window. 
Step 2: The tests checks if the correct pages are loaded in each window.
Step 3: After a while, a page 3 gets loaded in the first window. 
## Actual Behavior -

When executing step 3, the whole test hangs forever.
Visually, every page is loaded correctly. 
No problems in chrome and FF, its only with IE.

In a small, isolated example, Step 3 gets executed successfully:
[Selenium_IEWebDriver_Bug.zip](https://github.com/SeleniumHQ/selenium/files/378448/Selenium_IEWebDriver_Bug.zip)

But in the real app, which runs with AngularJS, and the pageload of step 3 is initiated by a websocket event, the browser hangs forever.

When step 3 fails, the following log entries can be found in IEWebDrivers logfile:

I 2016-07-22 16:51:43:936 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:43:973 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:44:088 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:44:214 VariantUtilities.cpp(179) Unknown type of dispatch is found in result, assuming IHTMLElement
I 2016-07-22 16:51:44:225 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:44:267 Browser.cpp(124) No child frame focus. Focus is on top-level frame
W 2016-07-22 16:51:44:461 Browser.cpp(256) Unable to get window name, IHTMLWindow2::get_name failed or returned a NULL value
I 2016-07-22 16:51:44:630 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:44:744 Browser.cpp(124) No child frame focus. Focus is on top-level frame
I 2016-07-22 16:51:44:884 VariantUtilities.cpp(179) Unknown type of dispatch is found in result, assuming IHTMLElement
I 2016-07-22 16:51:44:910 Browser.cpp(124) No child frame focus. Focus is on top-level frame
W 2016-07-22 16:51:45:131 Browser.cpp(256) Unable to get window name, IHTMLWindow2::get_name failed or returned a NULL value
## Steps to reproduce -

I'm currently not able to reproduce it in an isolated example.

**Comment by BBinottoADC** [comment]
This the the minimal example for demonstration, it does work perfectly though.. Unfortunately, the bug only appears in the full app which uses websockets to load page3 in the first window.
[Selenium_IEWebDriver_Bug.zip](https://github.com/SeleniumHQ/selenium/files/378444/Selenium_IEWebDriver_Bug.zip)

**Comment by barancev** [comment]
Closing this issue as non-actionable.
