### ISSUE TITLE
Consider publishing a point release for 2.53.x containing the changes from #2406

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#2514]
It would be useful for our tests in https://github.com/web-push-libs/web-push.

**Comment by lukeis** [comment]
Closing as this isn't an "issue/bug", feel free to build from source if you need something right now.

**Comment by marco-c** [comment]
I opened the issue because @jleyba was planning to release a new version. I thought you used issues also to track these kinds of things.

**Comment by lukeis** [comment]
We normally don't track this sort of thing with issues

**Comment by jleyba** [comment]
I've published 3.0.0-beta-1 to npm
