### ISSUE TITLE
Support for CSS pseudo elements like :before and :after

### ISSUE THREAD

**Issue by renet** [SeleniumHQ/selenium#2517]
As many users state, for example here: https://github.com/galenframework/galen/issues/228 , Selenium does not support pseudo-elements.

These are pretty common today and so I request the support of selecting pseudo elements and testing them for visibility, size, position, etc.

Is there any way this feature is added anytime soon? Thank you very much! :)

**Comment by lukeis** [comment]
you're referring to support of ['text nodes'](https://dom.spec.whatwg.org/#text). Nothing in the w3c spec for webdriver precludes the ability to locate a text element DOM node, support may vary from browser to browser. You'll need to log bugs with a specific test case to demonstrate how they may not be working as intended.

The selenium project here only supports IE Driver and FirefoxDriver. The latter is quickly becoming deprecated in favor of GeckoDriver - provided by Mozilla, so in that case we're not likely to support DOM text nodes (it's not likely to work in FF 48+) and you should log a bug with mozilla for support in geckodriver.

All being said... i actually don't know what matrix of support you're looking for, so for now, going to close the bug :)

**Comment by lovish-jain** [comment]
In the screenshot below i want to click on radio button 50% and above. Locating this radio button is highlighting pseudo-element ::before. Please help how can i locate this element and select it.

![myntra](https://user-images.githubusercontent.com/23254432/36643986-57b1a538-1a79-11e8-8e84-2012cee7cd6e.jpg)

**Comment by Kinzal15** [comment]
Is there any way to locate pseudo elements other than Javascript?
