### ISSUE TITLE
Selenium firefox driver get hanged out 

### ISSUE THREAD

**Issue by Manibharathi007** [SeleniumHQ/selenium#2522]
OS:  Win7, Win8.1, Win10, OS X
Selenium Version:  Tried from 2.48 to 2.53.1
Browser:  Issue only in Firefox.
Logged bug in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1289456
Browser Version: Tried from 45 to 47
## Expected Behavior -

Should not throw any error message, it allow us to perform any action on the page.
## Actual Behavior -

Getting below error :

1469541521068   addons.productaddons    ERROR   Request failed certificate checks: [Exception... "Certificate checks failed. See previous errors for details."  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: validateCert :: line 113"  data: no]
JavaScript error: https://xxxxxxxx/js/lib/pouchdb.crypto.js, line 2230: TypeError: res.results is undefined
JavaScript error: https://xxxxxxxxx/js/lib/pouchdb.min.js, line 8: Error: ETIMEDOUT

**Comment by lukeis** [comment]
Beyond that they've said they would refuse to sign it. I did go through the process once and was declined. Feel free to attempt again (and again and again). All the sources are in the selenium repo. 


That being said, this bug appears unrelated to using FF48. Would appreciate not updating here further, rather this one seems appropriate to follow up on: #2559

**Comment by Manibharathi007** [comment]
I have tried this issue by adding marionette=true capability to firefox webdriver, as below:
    DesiredCapabilities firefoxCapabilities = DesiredCapabilities.firefox();
    firefoxCapabilities.setCapability("marionette", true);
    driver = new RemoteWebDriver(hubURL, firefoxCapabilities);

Now the script is working as executed without any "hung/interruption/web-driver no response" issue in Firefox browser. I tried this in FF46 ,47 and 48. But now we facing some other issues due to Marionette(https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status).  

So please fix this issue in firefox driver without marionette capability, since it is in-progress. 
if you wants more details please mail me(manisundhar07@gmail) with what are the logs/details you needs?

**Comment by barancev** [comment]
Closing this issue as the related Marionette issue has been closed as fixed.
