### ISSUE TITLE
Firefox Driver not working with Firefox version 47.0.1

### ISSUE THREAD

**Issue by mart44** [SeleniumHQ/selenium#2523]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.0
IDE: Visual Studio 2015, C#

Browser:  Firefox 

Browser Version: 47.0.1 (32 Bit) 

## Expected Behavior -
Browser window opens and runs application tests

## Actual Behavior -
Browser window opens, does not load website and provides following error;

OpenQA.Selenium.WebDriverException : Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

Uninstalling Firefox version 47.0.1 and installing 46.0.1 resolves issue.  All tests work as expected within older firefox version

**Comment by lukeis** [comment]
you need to use selenium 2.53.1 not 2.53.0
