### ISSUE TITLE
WebDriver 2.53.1 - Java8, Firefox 47 - empty user profile dir, browser does not start, timeout after 45000 ms

### ISSUE THREAD

**Issue by acolomitchi** [SeleniumHQ/selenium#2528]
## Meta -
OS:  ubuntu 14.04, 64 bit
Selenium Version:  2.53.1
Browser:  Firefox 47

Java bindings (maven dependency to selenium-java, version 2.53.1):

`acolomitchi@travel:~$ uname -a`
`Linux travel 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`acolomitchi@travel:~$ firefox -version`
`Mozilla Firefox 47.0`
`acolomitchi@travel:~$ java -version`
`java version "1.8.0_101"`
`Java(TM) SE Runtime Environment (build 1.8.0_101-b13)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)`

## Steps to reproduce -
 ` String home=System.getProperty("user.home");`
`  File profileDir=new File(home+File.separator+"deleteme"+File.separator+"googlemaps");`
`   profileDir.mkdirs();`
`  FirefoxDriver w=new FirefoxDriver(new FirefoxProfile(profileDir));`
`  w.navigate().to("https://maps.google.com");`

## Expected behavior -
Browser should open and maps.google.com page is shown.
This used to work about one month ago (pre-Firefox 47 and selenium-java v 2.53.0)

## Actual behaviour -
Browser does not show. The application throws an exception:
`org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["sv-SE"],"name":"Ubuntu Modifications","description":"Ubuntu-paket för Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["uk"],"name":"Ubuntu Modifications","description":"Убунтівські доповнення до Firefox.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-CN"],"name":"Ubuntu Modifications","description":"Ubuntu 火狐扩展包.","creator":"Canonical Ltd.","homepageURL":null},{"locales":["zh-TW"],"name":"Ubuntu Modifications","description":"Ubuntu Firefox 擴充包。","creator":"Canonical Ltd.","homepageURL":null}],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"9.0","maxVersion":"37.0a1"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}`
etc.
(console text attached
[selenium-console.txt](https://github.com/SeleniumHQ/selenium/files/385321/selenium-console.txt)
)

**Comment by acolomitchi** [comment]
The behaviour is insensitive to http or https - just tried the same with a http (non-secure) url, with the same result.

**Comment by lukeis** [comment]
closing for the same reason as #2527
