### ISSUE TITLE
WebDriver 2.53.1 - Mono/Linux, Firefox 47 - browser starts with empty page and no navigation 

### ISSUE THREAD

**Issue by acolomitchi** [SeleniumHQ/selenium#2530]
## Meta -
OS:  ubuntu 14.04
Firefox: 47
Selenium version: 2.53.1 (nuget package)
Mono: 4.4.1

`acolomitchi@black:~$ uname -a`
`Linux black 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`acolomitchi@black:~$ firefox -version`
`Mozilla Firefox 47.0`
`acolomitchi@black:~$ mono -V`
`Mono JIT compiler version 4.4.1 (Nightly 4.4.1.0/4747417 Wed Jun 22 11:14:49 UTC 2016)`
`Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com`
`	TLS:           __thread`
`	SIGSEGV:       altstack`
`	Notifications: epoll`
`	Architecture:  amd64`
`	Disabled:      none`
`	Misc:          softdebug` 
`	LLVM:          supported, not enabled.`
`	GC:            sgen`

If, after investigation, the root cause is found to be the same, feel free to mark this issue as a duplicate of #2527 (for what I know, the behaviour is slightly different, but it might be cause by the new Firefox version breaking compatibility with selenium).

## Steps to reproduce -
Similar with #2527
`      IWebDriver driver = new FirefoxDriver ();`
`      driver.Navigate ().GoToUrl ("https://maps.google.com");`

## Expected Behavior -
Self-evident (browser opens and navigates to maps.google.com
## Actual Behavior -
Browser start showing the home page (Ubuntu start page in this case), but no navigation.
After 45 seconds, a timeout exception with the trace attached.

[selenium-mono.txt](https://github.com/SeleniumHQ/selenium/files/385371/selenium-mono.txt)

**Comment by lukeis** [comment]
closing for the same reason as #2527

**Comment by acolomitchi** [comment]
Confirmed as working with 47.0.1 on the line of

`FirefoxBinary fBin = new FirefoxBinary ([your_path_here]);`
`IWebDriver driver = new FirefoxDriver (fBin,null);`
`driver.Navigate ().GoToUrl ("https://maps.google.com");`
