### ISSUE TITLE
Selenium sendkeys not inputting the text

### ISSUE THREAD

**Issue by abhinavm88** [SeleniumHQ/selenium#2531]
## Meta -

OS:  Windows 10
Selenium Version:  2.53.1
Browser:  IE11

Browser Version:  IE-11.306.10586.0
## Steps to reproduce -
1. Click on a button in window.
2. Current window closes and opens new window.
3. Switches to new window and input username and password.

Below is the code:

```
WebElement element=null;
        try {
            driver.getWindowHandles();
            for (String winHandle : driver.getWindowHandles()) {
                    driver.switchTo().window(winHandle);
                    try {
                            element = driver.findElement(By.xpath("//*[@id='username']"));
                    } catch (Exception e) {
                        continue;
                    }
                    if (element.isDisplayed()) {
                        windowFound = 1;
                        break;
                    }
                }
            }
element.sendKeys("Testingusername");

```

In chromedriver it works fine. 
When I tried to input using javascriptexecutor also this works. But I do not want use javascriptexecutor.

**Comment by bizmate** [comment]
I have a similar problem, maybe unrelated, with a file field. the php selenium drivers sends the keys to the element but I end up with a file field of empty size, correct name and type though.
I experience the same problem also in 2.53.1 anyway

**Comment by barancev** [comment]
Sorry it was not properly addressed on time, but we need a [concise reproducible test case](http://sscce.org/) for this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
