### ISSUE TITLE
Occasionally it hangs exact 1 hour to wait http response from IEDriverServer

### ISSUE THREAD

**Issue by tcwmj** [SeleniumHQ/selenium#2532]
## Meta -
OS:  Windows 7
Selenium Version:  2.53.1
Browser:  Internet Explorer
Browser Version:  9, 10, 11

## Steps to reproduce - we are trying to run serveral test scripts, and it will cost 50 minustes to finish, but sometime it costs more than 1 or 2 hour to finish it, we found that test execution was hang up for exact 1 hour after clicking some element, and it's not easy to reporudce every time.

I've set the timeout to 30 seconds by explicit waiting for each html actions:
wait = new WebDriverWait(driver,30, 500)
                .ignoring(StaleElementReferenceException.class)
                .ignoring(NoSuchElementException.class)
                .ignoring(UnreachableBrowserException.class)
                .ignoring(InvalidElementStateException.class);

Here is our test log: (you will see there is 1 hour between clicking search link and next action)
14:49:19.170 [pool-8-thread-1] DEBUG org.yiwan.webcore.web.InternetExplorerDriverWrapper - clicking search instrument (ag.frame.search) WebButton
14:49:22.977 [pool-8-thread-1] DEBUG org.yiwan.webcore.web.InternetExplorerDriverWrapper - clicking search instrument result (ag.frame.link) Link
15:49:26.867 [pool-8-thread-1] DEBUG org.yiwan.webcore.web.InternetExplorerDriverWrapper - switching to default content

Here is the debug log of selenium: (we found it returns response after exact 1 hour)
14:49:23.148 [Forwarding isElementEnabled on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
14:49:23.148 [Forwarding isElementEnabled on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 105][route: {}->http://172.20.30.107:4444] can be kept alive indefinitely
14:49:23.148 [Forwarding isElementEnabled on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 105][route: {}->http://172.20.30.107:4444][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]
14:49:23.148 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
14:49:23.148 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
14:49:23.148 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://172.20.30.107:4444][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]
14:49:23.148 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 105][route: {}->http://172.20.30.107:4444][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
14:49:23.148 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Stale connection check
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "[read] I/O error: Read timed out"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-105: set socket timeout to 10800000
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request POST /wd/hub/session/dc34c937-f105-4854-b362-c15ec61ad434/element/129/click HTTP/1.1
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> POST /wd/hub/session/dc34c937-f105-4854-b362-c15ec61ad434/element/129/click HTTP/1.1
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> Content-Type: application/json; charset=utf-8
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> Content-Length: 12
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> Host: 172.20.30.107:4444
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> Connection: Keep-Alive
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> User-Agent: Apache-HttpClient/4.5.2 (Java/1.7.0_17)
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 >> Accept-Encoding: gzip,deflate
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "POST /wd/hub/session/dc34c937-f105-4854-b362-c15ec61ad434/element/129/click HTTP/1.1[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "Content-Length: 12[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "Host: 172.20.30.107:4444[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "Connection: Keep-Alive[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.7.0_17)[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "Accept-Encoding: gzip,deflate[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "[\r][\n]"
14:49:23.164 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 >> "{"id":"129"}"
14:49:23.616 [LittleProxy-105-ProxyToServerWorker-7] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x38aa975a, L:/172.20.30.79:57340 - R:urs.microsoft.com/191.232.139.180:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
14:49:23.632 [LittleProxy-105-ProxyToServerWorker-0] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x1a301f20, L:/172.20.30.79:57341 - R:urs.microsoft.com/191.232.139.180:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
14:49:23.663 [LittleProxy-105-ClientToProxyWorker-4] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xd73d17bb, L:/172.20.30.79:57122 - R:/172.20.30.107:52849] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
14:49:23.663 [LittleProxy-105-ClientToProxyWorker-5] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xa5742613, L:/172.20.30.79:57122 - R:/172.20.30.107:52850] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
14:49:27.766 [LittleProxy-105-ProxyToServerWorker-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x8afd35f8, L:/172.20.30.79:57345 - R:urs.microsoft.com/191.232.139.180:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
14:49:27.797 [LittleProxy-105-ClientToProxyWorker-7] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x00b88154, L:/172.20.30.79:57122 - R:/172.20.30.107:52864] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:29:04.653 [LittleProxy-105-ProxyToServerWorker-5] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x984c1131, L:/172.20.30.79:58592 - R:urs.microsoft.com/40.68.222.212:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:29:04.653 [LittleProxy-105-ProxyToServerWorker-4] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xa722efea, L:/172.20.30.79:58591 - R:urs.microsoft.com/40.68.222.212:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:29:05.449 [LittleProxy-105-ClientToProxyWorker-4] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xeaf04e36, L:/172.20.30.79:57122 - R:/172.20.30.107:56442] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:29:05.449 [LittleProxy-105-ClientToProxyWorker-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xfd9a3d84, L:/172.20.30.79:57122 - R:/172.20.30.107:56441] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:46:26.261 [LittleProxy-105-ProxyToServerWorker-6] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xbd1ca7f5, L:/172.20.30.79:59014 - R:r20swj13mr.microsoft.com/93.184.221.200:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:46:28.055 [LittleProxy-105-ClientToProxyWorker-5] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xfc0a21f0, L:/172.20.30.79:57122 - R:/172.20.30.107:58009] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:46:28.960 [LittleProxy-105-ProxyToServerWorker-7] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x8f3ca740, L:/172.20.30.79:59015 - R:r20swj13mr.microsoft.com/93.184.221.200:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:46:28.991 [LittleProxy-105-ClientToProxyWorker-6] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x31cded91, L:/172.20.30.79:57122 - R:/172.20.30.107:58013] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:47:03.840 [LittleProxy-105-ProxyToServerWorker-0] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x3edbcb26, L:/172.20.30.79:59028 - R:iecvlist.microsoft.com/93.184.221.200:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:47:04.746 [LittleProxy-105-ClientToProxyWorker-7] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xb577848e, L:/172.20.30.79:57122 - R:/172.20.30.107:58068] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:47:05.700 [LittleProxy-105-ProxyToServerWorker-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x65d1f7a1, L:/172.20.30.79:59031 - R:iecvlist.microsoft.com/93.184.221.200:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:47:05.731 [LittleProxy-105-ClientToProxyWorker-0] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x3bb81652, L:/172.20.30.79:57122 - R:/172.20.30.107:58072] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "HTTP/1.1 200 OK[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Date: Tue, 26 Jul 2016 06:49:22 GMT[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Server: Jetty/5.1.x (Windows 7/6.1 amd64 java/1.7.0_17[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Expires: Thu, 01 Jan 1970 00:00:00 GMT[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Cache-Control: no-cache[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Content-Type: application/json; charset=utf-8[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "Content-Length: 158[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "[\r][\n]"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.wire - http-outgoing-105 << "{"status":0,"sessionId":"dc34c937-f105-4854-b362-c15ec61ad434","value":null,"state":"success","class":"org.openqa.selenium.remote.Response","hCode":857306300}"
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << HTTP/1.1 200 OK
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Date: Tue, 26 Jul 2016 06:49:22 GMT
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Server: Jetty/5.1.x (Windows 7/6.1 amd64 java/1.7.0_17
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Expires: Thu, 01 Jan 1970 00:00:00 GMT
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Cache-Control: no-cache
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Content-Type: application/json; charset=utf-8
15:49:26.477 [Forwarding clickElement on session dc34c937-f105-4854-b362-c15ec61ad434 to remote] DEBUG org.apache.http.headers - http-outgoing-105 << Content-Length: 158

**Comment by tcwmj** [comment]
I've always adding following statement to validate whether to proceed next actions, it seems the roor cause might be the javascript in IE.

wait.until(new ExpectedCondition<Boolean>() {
                        private String currentValue = null;

                        @Override
                        public Boolean apply(WebDriver driver) {
                            try {
                                currentValue = (String) executeScript("return document.readyState");
                                return currentValue.equals("complete");
                            } catch (WebDriverException e) {
                                logger.warn("javascript error while waiting document to be ready");
                                return true;
                            }
                        }

                        @Override
                        public String toString() {
                            return String.format("wait document to be ready, current value is %s", currentValue);
                        }
                    });

**Comment by tcwmj** [comment]
sometimes it happens with 1 hour suspension and get http response from IEDriverServer, sometimes it happens with 3 hour suspension and get READ I/O timeout.

It seems the same as the topic in https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3951

**Comment by tcwmj** [comment]
Resolved by changing socket timeout from 3 hours to 60 seconds, and retrying last action when UnreachedBrowserException occurrs in the automation framework.

**Comment by martinsefcik** [comment]
@tcwmj How did you change 3 hours timeout to 60 seconds ?

**Comment by scoderp** [comment]
@tcwmj How did you change that timeout
