### ISSUE TITLE
Random chrome session always hangs/stops responding in selenium node

### ISSUE THREAD

**Issue by ossa619** [SeleniumHQ/selenium#2537]
## Meta -
OS:  OSX

Selenium Version:  2.53.1

Browser:  Chrome

Browser Version:  52.0.2743.82 (64-bit)

## Expected Behavior -
A chrome session should open and navigate to the given url
## Actual Behavior -
Chrome session hangs and says Application not responding. It is not the same session that always hangs. A random session hangs when opening n number of sessions.
## Steps to reproduce -
Register 5 nodes to the hub
Open more than 5 sessions in each node and do some operation
A random session hangs during the automation run

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. Reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
