### ISSUE TITLE
Cannot select an option in select (FF47 Marionette)

### ISSUE THREAD

**Issue by swistak** [SeleniumHQ/selenium#2538]
## Meta -
OS:  Linux (Debian)

Selenium Version:  2.53.4 (Ruby driver)

Browser:  Firefox 47 (Marionette)

Browser Version:  
Firefox 47 (Marionette)

## Expected Behavior -

```
driver.find_element_by_css_selector('select[name="year"]').click()
driver.find_element_by_css_selector('select[name="year"] option[value="2017"]').click()
```
Should select an option in select.

## Actual Behavior -

`driver.find_element_by_css_selector('select[name="year"]').click()`
Does not "click" on select (the select does not show the options). As a result trying to:

`driver.find_element_by_css_selector('select[name="year"] option[value="2017"]').click()`

results in:

`Selenium::WebDriver::Error::ElementNotVisibleError: Element is not visible`

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by titusfortner** [comment]
@swistak - there are several options related bugs being tracked by Mozilla here - https://bugzilla.mozilla.org/show_bug.cgi?id=1255957
