### ISSUE TITLE
Issue in mouse hover and drag and drop in IE 11 in Selenium grid

### ISSUE THREAD

**Issue by prakashsarav7** [SeleniumHQ/selenium#2542]
I am facing the following issue :

> When native events is set to false, drag and drop is working fine but mouse hover does not work.
> When native events is not set or set to true, drag and drop is not working but mouse hover does.

Following is the DesiredCapabilities I am using:

```
DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
caps.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
caps.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);
caps.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);
caps.setCapability("ignoreProtectedModeSettings", true);
aps.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
caps.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
```

Platform : Windows 2008 (Windows 7) and Windows 2012 R2 (Windows 8.1)
Browser : Internet Explorer 11
Java Selenium : 2.48.2

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario, just an unfounded statement.
