### ISSUE TITLE
GridLauncher class is missing from selenium-server-3.0.0-beta1.jar

### ISSUE THREAD

**Issue by irusev** [SeleniumHQ/selenium#2545]
## Meta -
OS:  
Any
Selenium Version:  
3-beta
Browser:  
any

## Expected Behavior -
Node is registered against selenium hub

## Actual Behavior -
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher

## Steps to reproduce -
I have a folder with selenium jars that I'm pulling from maven. Then I use those to start selenium nodes against a grid. After selenium3 got released a few days ago, the node registration started to fail with the above error. Here is the command that I use:

java -cp "lib/*" org.openqa.grid.selenium.GridLauncher -nodeConfig node.json -role node -host <gridIp>

GridLauncher used to be in selenium-server.jar, but now it's not there.

**Comment by barancev** [comment]
It is org.openqa.grid.selenium.GridLauncherV3 now

**Comment by irusev** [comment]
That's what I initially thought, but it's still not in the selenium-server.jar

**Comment by irusev** [comment]
Any plans on fixing that? It's blocking my whole continuous integration, because I'm automatically using the latest released version of selenium jars. Please comment if that's not going to get fixed, so I can eventually roll back and use the old version.

**Comment by lukeis** [comment]
It's not going to be fixed, you should use the GridLauncherV3 class instead

**Comment by irusev** [comment]
I see GridLauncherV3 in selenium-server-3.0.0-beta2.jar (it wasn't present in beta1), so that's fine. Thanks!

**Comment by MrRahulR** [comment]
For selenium-server-3.4.0.jar, seems GridLauncherV3 is missing.
I've tried to import it as below. 
`import org.openqa.grid.selenium.GridLauncherV3;`
also as in past, we're importing it.
`import org.openqa.selenium.gridLauncheV3;`

**Comment by MrRahulR** [comment]
When running with Maven goal, Maven isn't able to find GridLauncherV3 class. 

I've added Selenium Grid command in Java class as below for running hub and node.
It's running as expected when I run it via Java.
But when I try to run it through Maven goal, **it throws an error for GridLauncherV3 as it can't find either the symbol or org.openqa.grid.selenium class.** 

```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ RemoteTest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to D:\Rahul_P-QA\MySpace\RemoteTest\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartNode.java:[3,32] package org.openqa.grid.selenium does not exist
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartHub.java:[3,32] package org.openqa.grid.selenium does not exist
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartNode.java:[13,17] cannot find symbol
  symbol:   variable GridLauncherV3
  location: class remotegrid.RemoteTest.StartNode
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartHub.java:[9,17] cannot find symbol
  symbol:   variable GridLauncherV3
  location: class remotegrid.RemoteTest.StartHub
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.161 s
[INFO] Finished at: 2017-06-19T15:02:40+05:30
[INFO] Final Memory: 24M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project RemoteTest: Compilation failure: Compilation failure:
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartNode.java:[3,32] package org.openqa.grid.selenium does not exist
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartHub.java:[3,32] package org.openqa.grid.selenium does not exist
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartNode.java:[13,17] cannot find symbol
[ERROR] symbol:   variable GridLauncherV3
[ERROR] location: class remotegrid.RemoteTest.StartNode
[ERROR] /D:/Rahul_P-QA/MySpace/RemoteTest/src/main/java/remotegrid/RemoteTest/StartHub.java:[9,17] cannot find symbol
[ERROR] symbol:   variable GridLauncherV3
[ERROR] location: class remotegrid.RemoteTest.StartHub
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
