### ISSUE TITLE
DefaultRemoteProxy Connection Timed out, trying to connect physical mac mini device to docker hub

### ISSUE THREAD

**Issue by kevinyu-ias** [SeleniumHQ/selenium#2548]
## Meta -
OS:  AWS, Docker, Mac Mini 10.11.5

Selenium Version:  selenium server 2.53.0 

Browser:  

Created a docker hub and able to connect other docker nodes to the docker hub 

When I attempt to connect a physical node (mac mini) 

java -jar selenium-server-standalone-2.53.0.jar -role node -hub hub_ip:4444/grid/register -browser browserName=firefox 
- I've also tried adding -remoteHost <mac_mini_ip>:port 

I get the output
INFO - The node is registered to the hub and ready to use

When I navigate to the grid/console it takes a significant amount of time to load and I receive the 
DefaultRemoteProxy unknown version, connect to <mac_mini_ip>:port / <mac_mini_ip> failed: Connection timed out

The docker hub is sitting on an AWS instance with openVPN installed. The openVPN configs exist on the node as well. 

From the physical node (mac mini) I am able to wget hub_ip:4444/grid/register and it returns a 200

When I ssh into the hub, I try to telnet mac_mini_ip:port I get  ERROR 403: Forbidden for Proxy

Not sure if this is causing the DefaultRemoteProxy, but as of now I'm unable to connect a physical node to a hub on AWS is there a solution for this?

**Comment by lukeis** [comment]
The aws instance needs to be able to connect to your node, likely if you were on the aws instance and tried to reach http://<mac mini host>:5555/wd/hub/status it won't be able to connect. 

If there really is an issue with the docker image please log it on the docker-selenium repo.

**Comment by kevinyu-ias** [comment]
when on the aws instance, i am able to reach http://mac_mini_host:5555/wd/hub/status with a response 200

**Comment by elhay-av** [comment]
There is any solution?
