### ISSUE TITLE
Add the ability to add data to the clipboard

### ISSUE THREAD

**Issue by xaircore** [SeleniumHQ/selenium#2549]
Quite often there is a situation where you want to insert some data from the clipboard. To put the data there, often have to come up with a variety of tricks for this. I would very much like to see this feature for it

**Comment by AutomatedTester** [comment]
Since this is not really a standard way of doing this and relies on interaction with the OS I don't think we can do this until the [Clipboard API](https://w3c.github.io/clipboard-apis/) is done and all browsers have implemented it.

At that point it would be fine to just use `executeScript`.
