### ISSUE TITLE
Active Element Marionette

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2555]
OS: OS X
Selenium Version: 3.0.0.beta
Browser: Firefox
Browser Version: 50

For Marionette it is giving an error from the /element/active endpoint
This works through local Ruby & fails through the Server.

The calls and responses for local & remote:
https://gist.github.com/titusfortner/9145c9086e9cd07f0d1e945f945f998c

**Comment by titusfortner** [comment]
This is probably a duplicate of / same issue as #1795

**Comment by semurgx** [comment]
I've found workaround for this issue after digging into selenium-webdriver js source code.

```driver.getExecutor().defineCommand(cmd.Name.GET_ACTIVE_ELEMENT, 'GET', '/session/:sessionId/element/active');```

**Comment by lukeis** [comment]
@titusfortner why is the remote a POST yet the local is a GET?

**Comment by titusfortner** [comment]
@lukeis - w3c uses GET, jwp uses POST.
@jimevans keeps telling me that I should only be sending jwp commands to the server. I've updated the gist with the error messages from both w3c & jwp commands.
