### ISSUE TITLE
Firefox / JQuery-layout: Button doesn't receive click

### ISSUE THREAD

**Issue by OLibutzki** [SeleniumHQ/selenium#2560]
## Meta -

OS:  Windows 7
Selenium Version:  2.53.1
Browser:  Firefox
Browser Version:  45.2.0
## Expected Behavior

The click() method call results in triggering the onclick event of the button.
## Actual Behavior

The onclick event is not triggered
## Steps to reproduce -

I created a sample page (https://olibutzki.github.io/selenium-jquery-layout-issue/sample.html) and a Maven project including a JUnit test to reproduce the behaviour: https://github.com/OLibutzki/selenium-jquery-layout-issue

Please read the [README.md](https://github.com/OLibutzki/selenium-jquery-layout-issue/blob/master/README.md) of the GitHub project for further information.

**Comment by OLibutzki** [comment]
Any ideas? Maybe I can modify the footer in order to solve this? I just don't understand why this issue happens, so any help is highly appreciated.

**Comment by OLibutzki** [comment]
The issue still occurs with Selenium WebDriver 3.0.0-beta1 (FirefoxDriver without using Marioenette).

**Comment by maeriens** [comment]
Hello from the distant future - I do not thing this is a Selenium issue. 

The html `onClick` attribute needs to receive a function inside of it, not an assignmen as you are doing.. It is easy to check having the developer tools open. [Here I recorded it](https://www.screencast.com/t/IGBK8zypgX).

**Comment by p0deje** [comment]
@maeriens Thank you for investigating the issue - I'll mark this as awaiting answer from reporter!

**Comment by barancev** [comment]
Closing the issue as working as intended.
