### ISSUE TITLE
Cannot upload file to selenium server on Win10

### ISSUE THREAD

**Issue by MrDefinite** [SeleniumHQ/selenium#2561]
## Meta -
OS:  Windows 10

Selenium Version:  2.52.1 and 3.0.0 beta1

Browser:  Chrome

Browser Version:  52.0.2743.82

## Case Description -
I need to upload a binary file with selenium python client.
Basically, I should be able to use 'element.send_keys' to begin the upload process.
But the upload failed.
After reading the code in '/py/selenium/webdriver/remote/webelement.py', I find selenium client will firstly try to upload file to the selenium server if it finds the file locally.
I think it is reasonable in most cases.
However it cannot work correctly on Windows 10 (Windows 7 is fine).
It always throws error 'Illegal base64 character'.
Looks like the root cause should be here: 
        content = base64.encodestring(fp.getvalue())
        if not isinstance(content, str):
            content = content.decode('utf-8')

## Expected Behavior -
selenium client should upload both text and binary file to selenium server.

## Actual Behavior -
1. selenium client can upload text file to selenium server.
2. selenium client cannot upload binary file to selenium server.

## Steps to reproduce -
1. Run a case which is using 'element.send_keys' to upload a binary file
2. This binary file is located on selenium client but not the selenium server
3. Upload failed.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by MrDefinite** [comment]
@lukeis The case can be easily reproduced.
See my code below:

HTML page:

```
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <title>bug</title>
</head>
<body>
   <input type="file" id="upload">
</body>
</html>
```

Test case code:

```
from selenium import webdriver

if __name__ == "__main__":

   driver = webdriver.Remote("you selenium server address here")
   driver.get("http://xxxx/index.html")
   e = driver.find_element_by_id("upload")
   e.send_keys("C:\\test.mp4")
```

Note:  
1. test.mp4 is stored in selenium client machine.
2. use selenium python API

Is these info OK for reopen the bug?

**Comment by lukeis** [comment]
please provide a real site to test this against and example file that causes the issue. You can create a temporary html page at jsfiddle.net and the file you're having issues uploading. again please provide a *complete* reproducible test case that includes web site and files uploading (in this case)

**Comment by tyd** [comment]
@MrDefinite were you able to find a solution? We are having same issue.
