### ISSUE TITLE
BrowserLocator class is no longer present in 3.0.0-beta2

### ISSUE THREAD

**Issue by wolfy027** [SeleniumHQ/selenium#2564]
## Meta -
OS:  
Any
Selenium Version:  
3.02 beta
Browser:  
Any

My current testing framework has BrowserLocator and its implementations usage, but with the upgrade to 3.0.0-beta2, I can no longer find BrowserLocator implementations with the latest release.

The following classes are no longer found with 3.02 beta
 org.openqa.selenium.browserlaunchers.locators.BrowserLocator;
org.openqa.selenium.browserlaunchers.locators.FirefoxLocator;
org.openqa.selenium.browserlaunchers.locators.GoogleChromeLocator;
org.openqa.selenium.browserlaunchers.locators.InternetExplorerLocator;
org.openqa.selenium.browserlaunchers.locators.SafariLocator;

**Comment by lukeis** [comment]
They were removed in this commit:
298fb4480708bfa0299fb1040cd4ce98d7c5ed8b

They weren't used in the Selenium code base, except for SafariLocator, which was moved. You'll need to use an alternative or create your own classes. I'm unsure what your use of them was. There are alternatives in the selenium project, but they are still all internal classes and not meant for consumption.

You'll have to be more clear on what you are requiring, as it stands there's nothing more we can do here, so I'm closing the issue.
