### ISSUE TITLE
[Selenium 3-beta] Server fails to start when launched with chromedriver v2.22

### ISSUE THREAD

**Issue by mehmetg** [SeleniumHQ/selenium#2566]
## Meta -
OS:  
OSX 10.11.6
Selenium Version:  
Se3 Beta 2
Browser:  
N/A

Browser Version:  
chromedriver v2.22
## Expected Behavior -
Selenium server should start
using the following command line
 `java -debug -jar /Users/mehmetgerceker/workspace/nerdytests/resources/selenium-server-standalone-3.0.0-beta2.jar -Dwebdriver.chrome.driver=/Users/mehmetgerceker/workspace/nerdytests/resources/chromedriver-2.22 -Dwebdriver.gecko.driver=/Users/mehmetgerceker/workspace/nerdytests/resources/geckodriver-0.10.0`
## Actual Behavior -
Selenium server throws the following error
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.chrome.driver=/Users/mehmetgerceker/workspace/nerdytests/resources/chromedriver-2.22
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:202)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:130)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:67)
```
## Steps to reproduce -
 `java -debug -jar /Users/mehmetgerceker/workspace/nerdytests/resources/selenium-server-standalone-3.0.0-beta2.jar -Dwebdriver.chrome.driver=/Users/mehmetgerceker/workspace/nerdytests/resources/chromedriver-2.22 -Dwebdriver.gecko.driver=/Users/mehmetgerceker/workspace/nerdytests/resources/geckodriver-0.10.0`

**Comment by lukeis** [comment]
Java command line usage requires system properties to be specified BEFORE the -jar

Please move all -D command line arguments before the -jar argument

**Comment by mehmetg** [comment]
Thank you. Oddly enough 2.53.1 was perfectly fine with it.

**Comment by lukeis** [comment]
Not too odd ;) we changed the command line argument parser to use Jcommander instead of maintaining our own. The old one did extra by accepting system property flags and then setting them with extra Java code. We have no interest in maintaining a command line parser in selenium.

**Comment by mehmetg** [comment]
Ah makes sense. Thank you for the explanation.  😄

**Comment by GaneshBalasubramanian15** [comment]
java -jar /selenium-server-standalone-3.0.0-beta4.jar -port 5555 
-Dwebdriver.gecko.driver=C:\Selenium3\geckodriver
i cant start this batch file with the above content and unable to debug. 
any suggestions guys?

**Comment by lukeis** [comment]
@GaneshBalasubramanian15 -D arguments in the command line should come *before* the '-jar'

**Comment by fayizkc** [comment]
Hi Lukeis,
Can you please assist us to re structure the below code to run Selenium Grid in Selenium 3.0.0-beta4
`java -jar selenium-server-standalone-3.0.0-beta4.jar -role webdriver -hub http://%$HubSystemName%:4444/grid/register -port 5566 -browser browserName="chrome", -Dwebdriver.chrome.driver=chromedriver.exe -browser browserName="ie", -Dwebdriver.ie.driver=IEDriverServer.exe`

**Comment by marcbaas** [comment]
I would love to know how this line should be structured under the new invocation rules:
`java -jar selenium-server-standalone-3.0.0-beta3.jar -host 192.168.63.178 -port 4444`

Currently that throws an error:
`Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -host`

**Comment by lukeis** [comment]
@marcbaas -host is only available when run with -role hub or -role node.

@fayizkc move all your -D... command line parameters *before* the -jar as i said before....  java -Dwebdriver....=...  -Dwebdriver....=...  -jar selenium-server....

**Comment by GaneshBalasubramanian15** [comment]
hello guys, hope ye all well, Im having this issue when i dont have the grid set up. this is the single batch file configured for all the browsers 

java -Dwebdriver.gecko.driver="geckodriver.exe" -jar selenium-server-standalone-2.53.1.jar -port 5555 -Dwebdriver.ie.driver="IEDriverServer2_53.exe" -Dwebdriver.chrome.driver="chromedriver2_25.exe" -debug

The service is up, but when i run the selenium im getting this error for latest FF 49.0.1

Error
org.openqa.selenium.WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

any suggestions please?

**Comment by ddavison** [comment]
@GaneshBalasubramanian15 , @lukeis gave the solution many times.  please move your `-D` arguments before your -jar option. 

locking conversation.
