### ISSUE TITLE
Enhancement: Add function support get current cursor style.

### ISSUE THREAD

**Issue by liyang0452** [SeleniumHQ/selenium#2567]
so some requirement, we need to get current browser cursor style.  so far there is a way use javascript get  element, and then get cursor style, but it must know the element, our testing need a interface get the current cursor style , no need to know the cursor in which element, thank you.

**Comment by lukeis** [comment]
There is currently no WebDriver API call to get this particular information. If you'd like to try to see it as apart of the WebDriver API please log a bug with the w3c spec:

https://w3c.github.io/webdriver/webdriver-spec.html

(link to create a bug in the top right corner).

For now, the best you can do is get the computed style of an element to see what the cursor style is, this likely will be troublesome to get when class pseudo-classes like :hover are used to change the style. But that's the best I can think of.
