### ISSUE TITLE
FF browser not open using 3.0 beta.....Help me. i am using FF browser 48

### ISSUE THREAD

**Issue by kuttyv** [SeleniumHQ/selenium#2568]
## Meta -
OS:  
 window 7 32bit 
Selenium Version:   3.0

Browser:  Firefox 48

Browser Version:   48

**Comment by AutomatedTester** [comment]
Duplicate of #2559

**Comment by kuttyv** [comment]
hello boss tell me the solution..wt is duplicate 2559

**Comment by rlebl21** [comment]
You need to get the gekko driver. Your error message should give you a link that directs you to where you can download this driver.
