### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

### ISSUE THREAD

**Issue by appunikki** [SeleniumHQ/selenium#2570]
****Using Selenium 3.0 beta 2 libs and Firefox 49 and Java 8
Kindly Help**** 
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi	DEBUG	Updating database with changes to installed add-ons
1470300098447	addons.xpi-utils	DEBUG	Updating add-on states
1470300098448	addons.xpi-utils	DEBUG	Writing add-ons list
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1470300098455	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1470300098456	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1470300098456	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1470300098457	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1470300098459	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1470300098460	addons.manager	DEBUG	Provider finished startup: XPIProvider
1470300098460	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1470300098460	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1470300098460	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1470300098461	addons.manager	DEBUG	Starting provider: GMPProvider
1470300098467	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: GMPProvider
1470300098468	addons.manager	DEBUG	Starting provider: PluginProvider
1470300098468	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1470300098469	addons.manager	DEBUG	Completed startup sequence
1470300100429	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1470300100429	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1470300100429	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1470300100861	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300100861	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1470300100862	DeferredSave.extensions.json	DEBUG	Starting timer
1470300100885	DeferredSave.extensions.json	DEBUG	Starting write
1470300100891	addons.repository	DEBUG	No addons.json found.
1470300100892	DeferredSave.addons.json	DEBUG	Save changes
1470300100929	DeferredSave.addons.json	DEBUG	Starting timer
1470300101040	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1470300101055	DeferredSave.addons.json	DEBUG	Starting write
1470300101206	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300101286	DeferredSave.addons.json	DEBUG	Write succeeded
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.0
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1470300119159	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1470300119723	addons.manager	DEBUG	shutdown
1470300119723	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1470300119723	addons.xpi	DEBUG	shutdown
1470300119724	addons.xpi-utils	DEBUG	shutdown
1470300119724	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1470300119725	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1470300119726	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1470300119727	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1470300119728	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1470300119730	addons.xpi	DEBUG	Notifying XPI shutdown observers
1470300119733	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:315)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at onlineOrder.OrderBooking.main(OrderBooking.java:16)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
xpi	DEBUG	Updating database with changes to installed add-ons
1470300098447	addons.xpi-utils	DEBUG	Updating add-on states
1470300098448	addons.xpi-utils	DEBUG	Writing add-ons list
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1470300098455	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1470300098456	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1470300098456	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1470300098457	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1470300098459	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1470300098460	addons.manager	DEBUG	Provider finished startup: XPIProvider
1470300098460	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1470300098460	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1470300098460	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1470300098461	addons.manager	DEBUG	Starting provider: GMPProvider
1470300098467	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: GMPProvider
1470300098468	addons.manager	DEBUG	Starting provider: PluginProvider
1470300098468	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1470300098469	addons.manager	DEBUG	Completed startup sequence
1470300100429	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1470300100429	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1470300100429	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1470300100861	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300100861	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1470300100862	DeferredSave.extensions.json	DEBUG	Starting timer
1470300100885	DeferredSave.extensions.json	DEBUG	Starting write
1470300100891	addons.repository	DEBUG	No addons.json found.
1470300100892	DeferredSave.addons.json	DEBUG	Save changes
1470300100929	DeferredSave.addons.json	DEBUG	Starting timer
1470300101040	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1470300101055	DeferredSave.addons.json	DEBUG	Starting write
1470300101206	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300101286	DeferredSave.addons.json	DEBUG	Write succeeded
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.0
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1470300119159	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1470300119723	addons.manager	DEBUG	shutdown
1470300119723	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1470300119723	addons.xpi	DEBUG	shutdown
1470300119724	addons.xpi-utils	DEBUG	shutdown
1470300119724	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1470300119725	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1470300119726	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1470300119727	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1470300119728	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1470300119730	addons.xpi	DEBUG	Notifying XPI shutdown observers
1470300119733	addons.manager	DEBUG	Async provider shutdown done

Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'Aparna', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:315)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:232)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at onlineOrder.OrderBooking.main(OrderBooking.java:16)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi	DEBUG	Updating database with changes to installed add-ons
1470300098447	addons.xpi-utils	DEBUG	Updating add-on states
1470300098448	addons.xpi-utils	DEBUG	Writing add-ons list
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1470300098455	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1470300098455	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1470300098456	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1470300098456	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1470300098457	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1470300098459	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1470300098460	addons.manager	DEBUG	Provider finished startup: XPIProvider
1470300098460	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1470300098460	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1470300098460	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1470300098461	addons.manager	DEBUG	Starting provider: GMPProvider
1470300098467	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: GMPProvider
1470300098468	addons.manager	DEBUG	Starting provider: PluginProvider
1470300098468	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1470300098468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1470300098469	addons.manager	DEBUG	Completed startup sequence
1470300100429	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1470300100429	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1470300100429	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1470300100861	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300100861	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1470300100862	DeferredSave.extensions.json	DEBUG	Starting timer
1470300100885	DeferredSave.extensions.json	DEBUG	Starting write
1470300100891	addons.repository	DEBUG	No addons.json found.
1470300100892	DeferredSave.addons.json	DEBUG	Save changes
1470300100929	DeferredSave.addons.json	DEBUG	Starting timer
1470300101040	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1470300101041	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1470300101055	DeferredSave.addons.json	DEBUG	Starting write
1470300101206	DeferredSave.extensions.json	DEBUG	Write succeeded
1470300101286	DeferredSave.addons.json	DEBUG	Write succeeded
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.0
1470300119158	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1470300119159	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1470300119723	addons.manager	DEBUG	shutdown
1470300119723	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1470300119723	addons.xpi	DEBUG	shutdown
1470300119724	addons.xpi-utils	DEBUG	shutdown
1470300119724	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1470300119725	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1470300119726	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1470300119727	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1470300119728	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1470300119730	addons.xpi	DEBUG	Notifying XPI shutdown observers
1470300119733	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 8 more

**Comment by lukeis** [comment]
for Firefox 48+ you must use GeckoDriver, not the old driver extension.

It doesn't look like you're using GeckoDriver, but if you are, please log a bug with them if you continue to see issues.

https://github.com/mozilla/geckodriver

**Comment by phoenix384** [comment]
It would be a compliment to call that GeckoDriver beta stadium. It's not even waiting for page loads apart from many other things that don't work.
I don't understand why they lock out a working WebDriver implementation when no suitable alternative is available.

**Comment by Manju2304** [comment]
Hi I had used gecko driver, but, i am getting same issue as mentioned above.
