### ISSUE TITLE
Firefox 46.0.1 not opening with correct profile on Selenium Grid 2.53.1

### ISSUE THREAD

**Issue by pennycurich** [SeleniumHQ/selenium#2576]
## Meta -
OS:  hub=OSX, node=Windows 10

## Selenium Version:  
2.53.1

## Browser:  
Firefox 

## Browser Version:  
46.0.1

## Expected Behavior -
Browser launches with firefox profile configuration (or copy of configuration) specified in nodeconfig.json.

## Actual Behavior -
Browser appears to be launching with default profile.

## Steps to reproduce -

Save a Firefox profile, "testprofile" via firefox.exe -P.  Set something specific via about:config such as general.useragent.override.

Create a nodeconfig.json similar to the following:
```
        "browserName": "firefox",
        "firefox_profile": "testprofile",
        "platform": "WIN10",
        "firefox_binary": "C:\\Program Files\ (x86)\\Mozilla\ Firefox\\firefox.exe"
```

Start hub, start node.  For node:

`java -cp selenium-server-standalone-2.53.0.jar org.openqa.grid.selenium.GridLauncher -role node -nodeConfig nodeconfig.json -hub http://xxx.xxx.xxx.xxx:4444/grid/register`

Launch code, similar to:
```
DefaultCapabilities capabilities = new DesiredCapabilities(BrowserType.FIREFOX, “”, Platform.ANY);
return new RemoteWebDriver(new URL(“http://xxx.xxx.xxx.xxx:4444/wd/hub”), capabilities);
```

Note that the launched browser does not reflect configuration settings of the requested profile.

**Comment by lukeis** [comment]
this is not a feature of grid, your test code needs to specify the profile to use. The node config is only used for matching (routing) the request from the hub to the appropriate node. Startup of the browser is reliant only on the desired capabilities passed in.

Your other option is to start your node with a system property:

    java -Dwebdriver.firefox.profile=testprofile -jar selenium-server-standalone-3.0.0-beta4.jar -role node ...
