### ISSUE TITLE
Not able to select element from a select list using Select class in firefox 48

### ISSUE THREAD

**Issue by deepaknik123** [SeleniumHQ/selenium#2586]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0-beta2

Browser:  Firefox (GECKODRIVER)

Browser Version:  48

## Steps to reproduce -
Code for selecting : 
Select select = new Select(driver.findElement(By.id("edit-turnaround-time")));
select.selectByVisibleText("Regular")

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
