### ISSUE TITLE
Not able to select element using SelectElement class in FireFox 48, Im using the latest drivers (marionette)

### ISSUE THREAD

**Issue by vmukunda** [SeleniumHQ/selenium#2587]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53
Browser:  
Firefox

I'm using the Gecko driver. My references to the project are,
  <package id="Selenium.Support" version="2.53.1" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="2.53.1" targetFramework="net452" />
  <package id="WebDriver.GeckoDriver" version="0.9.0" targetFramework="net452" /> 

Browser Version:  
Firefox 48

## Expected Behavior -

I have a dropdown which have the values 
Test1
Test2 
Test3 bo
Test4 

Of which Test3 is set as default selected. 

              FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
                 service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                  string localURL = "http://localhost:82/Home/";`
                 driver.Navigate().GoToUrl(localURL);
                 var div = driver.FindElement(By.Id("TestContainer"));
                 div.Click();
                 IWebElement dropDownListBox = div.FindElement(By.TagName("select"));
                 SelectElement demoSelect = new SelectElement(dropDownListBox);
                 demoSelect.SelectByText("Test2");
``

When i execute the above code, I'm expecting the selection to change to Test2 in the dropdown.

## Actual Behavior -
The value in the dropdown doesnt change.

## Steps to reproduce -

1. Create a select element with 4 entries as shown below in a view.

             <div id="TestContainer" class="col-md-4">
                           <select>
                                <option>Test1</option>
                                <option>Test2</option>
                               <option selected="selected">Test3</option>
                                <option>Test4</option>
                            </select>
             </div>

2. Execute the below code to changes the selected value of the above dropdown.
```
                FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
                 service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                 string localURL = "http://localhost:82/Home/";
               driver.Navigate().GoToUrl(localURL);
                var div = driver.FindElement(By.Id("TestContainer"));
                div.Click();
                IWebElement dropDownListBox = div.FindElement(By.TagName("select"));
                SelectElement demoSelect = new SelectElement(dropDownListBox);
                demoSelect.SelectByText("Test2");
```

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
