### ISSUE TITLE
RemoteWebDriver: missing dispose for StartSession timeouts

### ISSUE THREAD

**Issue by DirkRichter** [SeleniumHQ/selenium#2588]
## Meta -

OS:  Windows 7
Selenium Version:  2.49.0
Browser:  PhantomJS

The constructor RemoteWebDriver starts a new session (StartSession) executing DriverCommand.NewSession, which could result in DriverService.InitializationTimeout (20 sec. ) exception. In this case programmers do not have the ability to dispose the created process for loading the webdriver. The process exists forever.
## Expected Behavior -

Calling PhantomJSDriver contructor returns an object, where user can check initialization status and finally can do a dispose. Similar: all other WebDriver constructors.
## Actual Behavior -

DriverService.Start throws an Exception when WaitForServiceInitialization fails and access to DriverService.driverServiceProcess is lost. Thus user can not dispose the created webdriver process.
## Steps to reproduce -

Very high load (CPU+RAM) on host, then call  var res = new PhantomJSDriver(myPath);

**Comment by barancev** [comment]
PhantomJS is not supported anymore.
