### ISSUE TITLE
Selenium can't find/click a button randomly in Safari

### ISSUE THREAD

**Issue by addteq-roberto** [SeleniumHQ/selenium#2589]
## Meta -
OS:  OSX Yosemite
Selenium Version:  2.48
Browser:  Safari 8.0.8

We're doing UI tests through Atlassian's Confluence. One of the steps is to click the button "Create" to create a new page and it's in every page in Confluence. We randomly receive timeouts from selenium trying to find or click the button, as if it were not in screen. It goes too fast to notice if the button is drawn correctly, and the issue is not 100% sure to appear (can't determine the conditions when it will appear for a test run).

**Comment by lukeis** [comment]
SeleniumHQ's SafariDriver is deprecated / not being maintained. Your best bet will be to wait for macOS Sierra to be released and use the Safari Driver provided by apple.

Also without a reproducible test case (even if intermittent) no one can help you further.
