### ISSUE TITLE
Update netty version

### ISSUE THREAD

**Issue by ptahchiev** [SeleniumHQ/selenium#2591]
## Meta -

OS:  Any

Selenium Version:  Current

Browser:  No

Browser Version:  No

## Steps to reproduce -

Please update the netty version. The one you are using (3.5.2) is more than 4 years old:

http://repo1.maven.org/maven2/io/netty/netty/

I have elasticsearch in my classpath and it expects 3.10.5 so there are `ClassNotFound` exceptions. I have managed to come around it by excluding the netty that selenium brings, but still it would be nice if selenium would keep it's dependencies up-to-date

**Comment by lukeis** [comment]
it's only being used by the safaridriver... which has been deprecated and no one has worked on it in 4 years... so, yeah. Either it will be removed or you'll likely need to keep your workaround for a while.

**Comment by barancev** [comment]
Fixed by 6fc2f271ec3bf4d32b23a4d0eda384a808c48498
