### ISSUE TITLE
Unable to delete HTTPONLY cookie on IE 10 and IE 11 in iedriver v2.53.1

### ISSUE THREAD

**Issue by tamarbuata** [SeleniumHQ/selenium#2592]
## Meta -

OS:  Windows 10, Windows 8.1

Selenium Version:  iedriver 2.53.1

Browser:  IE 10, IE 11

Browser Version:  

11.0.9600.17801
10.0.9200.16580
## Expected Behavior -

Using the DELETE_COOKIE command should delete the specified HTTPonly cookie. According to the changelog for the IEdriver, v2.46.0.6 / v2.46.0.5 should afford this functionality. 
https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG
## Actual Behavior -

Using the DELETE_COOKIE command and then refreshing the page does not delete the cookie.

Using the DELETE_ALL_COOKIES command deletes all cookies including HTTPonly successfully.
## Steps to reproduce -

1. Start the IE driver. 
2. Login to a Gmail account.
3. Delete the 'NID' cookie with webdriver. (This is an HTTPonly cookie)
4. Refresh the page. Notice cookie is still present.

**Comment by lukeis** [comment]
can you please provide a script to demonstrate the issue, you don't need to provide credentials, but rather some selenium code so we know exactly what you're expecting.

**Comment by sduren** [comment]
I am also seeing this issue on IE 11.540.15063.0 on Windows 10 with IEDriverServer 3.6.0.

Below is a simple unittest per @lukeis' request. The delete_cookie() method is working in Chrome but failing in IE for the google.com 'NID' cookie:

```
import unittest
from selenium import webdriver


class CookieTest(unittest.TestCase):
    def tearDown(self):
        self.wd.quit()

    def test_cookie_chrome(self):
        # Chrome does delete the NID cookie
        self.wd = webdriver.Chrome()
        self.do_cookie_test()

    def test_cookie_ie(self):
        # IE does NOT delete the NID cookie
        self.wd = webdriver.Ie()
        self.do_cookie_test()

    def do_cookie_test(self):
        self.wd.get('http://www.google.com')
        c = self.wd.get_cookie('NID')
        self.assertIsNotNone(c)

        # delete_cookie() call does not actually delete the cookie in IE
        self.wd.delete_cookie('NID')
        c = self.wd.get_cookie('NID')
        self.assertIsNone(c)

if __name__ == "__main__":
    import unittest
    unittest.main()
```

**Comment by barancev** [comment]
The issue seems to be fixed by now, tested in IE 11 with the driver 3.141.5.13 using this scenario:
```
    InternetExplorerOptions options = new InternetExplorerOptions();
    //options.destructivelyEnsureCleanSession();
    WebDriver driver = new InternetExplorerDriver(options);
    driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

    driver.get("https://aws.amazon.com/ru/");
    driver.manage().deleteAllCookies();
    driver.navigate().refresh();

    driver.findElement(By.cssSelector("div[data-da-campaign=header_signup] a")).click();
    Thread.sleep(3000);
    Cookie c1 = driver.manage().getCookieNamed("JSESSIONID");
    assertTrue(c1.isHttpOnly());

    driver.manage().deleteCookieNamed("JSESSIONID");
    driver.navigate().refresh();
    Thread.sleep(3000);
    Cookie c2 = driver.manage().getCookieNamed("JSESSIONID");
    assertTrue(c2.isHttpOnly());

    assertNotEquals(c1.getValue(), c2.getValue());
```

**Comment by barancev** [comment]
Feel free to request reopening the issue if it is still actual.
