### ISSUE TITLE
FirefoxDriver: fireMouseEvent() rounds away precision in coordinates

### ISSUE THREAD

**Issue by yoongu** [SeleniumHQ/selenium#2593]
## Meta -

OS:  Windows 10

Selenium Version: 2.53.1  

Browser:  Firefox

Browser Version: 47.0.1

## Expected Behavior -

A button that's only **partially** covered by another element should still be clickable.
## Actual Behavior -

Depending on the button's exact coordinates, it may or may not be clicked.
## Steps to reproduce -

Here's a JSFiddle: https://jsfiddle.net/e17Ldm77/

Let's assume you have a fairly large button with `position: absolute` and `left: 0.1px`. Let's further assume that the exact center of the button happens to be covered by another element. It's only the center that's covered, the button's four edges and corners are not covered.

In this case, `utils.js::Utils.getClickablePoint()` determines that the center of the button is unclickable. Instead, it returns the upper-left corner of the button which is **not** covered by the other element.

But when `syntheticMouse.js::SyntheticMouse.EventEmitter.prototype.fireMouseEvent()` calls `utils.sendMouseEventToWindow()`, it **rounds down** the x coordinate of the upper-left corner from `0.1px` to `0px`. So the mouse-click happens at `0.1px` left of where the button actually starts.

**Comment by pumano** [comment]
i have problem with firefox click too. (same environment)
But I found sometimes element is selected but not clicked, due to (maybe?) coordinates mismatching?Investigation needed.

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
