### ISSUE TITLE
System.InvalidOperationException : unknown error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jigneshpatel1407** [SeleniumHQ/selenium#2594]
## Meta -
OS:  
Windows 7

Selenium Version:  
2.53.0

Browser:  
Google Chrome 

Browser Version:  
Version 52.0.2743.116 m

Version 52.0.2743.116 m

Actually we are getting this error during finding element using C#. Please see below code:

System.Threading.Thread.Sleep(20000);
            do
            {
                IWebElement e = driver.FindElement(By.XPath("//*[@id='ctl00_udpnlMasterPage']"));
                Console.WriteLine("Boolean:" + e.Displayed);
            } while (true);

Result Error:
Below error generate on "e.Displayed" console write line. error text mention as below:

Result Message:	
System.InvalidOperationException : unknown error: Cannot read property 'length' of undefined
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86)
Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.get_Displayed()

**Comment by lukeis** [comment]
chromedriver 2.24 is now available. Try upgrading. If you still see the issue, please log a new issue with the chromedriver project with a way for them to reproduce the issue:
https://bugs.chromium.org/p/chromedriver/issues/list
