### ISSUE TITLE
Unable to close the browser

### ISSUE THREAD

**Issue by suryaprusty** [SeleniumHQ/selenium#2595]
## Meta -
OS:  windows 7

Selenium Version:  3.0 beta 2

Browser:  firefox 

Browser Version:  
 48

## Expected Behavior -
when user driver.close(), the browser is not closed. when used driver.quit(), Error message is displayed.
## Actual Behavior -
when close() or quit() is used then the browser should be closed.

**Comment by kindut** [comment]
I'm running into an issue with driver.close() as well.  Except my window closes, but the memory is not released and ultimately crashes.

**Comment by abhishekroy2007** [comment]
driver.close(); is working..fine..

**Comment by OddDev** [comment]
Can confirm

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
