### ISSUE TITLE
"Open"ing URL with hash/anchor on same page causes timeout

### ISSUE THREAD

**Issue by dougmartin17** [SeleniumHQ/selenium#2599]
Originally **https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5165**

What steps will reproduce the problem?
1. "Open" a URL, e.g. http://en.wikipedia.org/wiki/Yiddish
2. "Open" the same URL but with an anchor/hash, e.g. http://en.wikipedia.org/wiki/Yiddish#20th_century

What is the expected output? What do you see instead?
I would expect Selenium to open that URL, recognize that the page has moved/changed,
and continue with the script. Instead, I see "[error] Timed out after 30000ms."

The example I've attached uses Wikipedia URLs, which is a bit contrived, but it demonstrates
the problem I'm having with a Backbone.js application I'm testing that navigates using
the hash, e.g.:
- http://foo.com/#/login
- http://foo.com/#/dashboard
- http://foo.com/#/user/foo123

Selenium version: IDE 1.10.0
OS: Windows 7
Browser: Firefox
Browser version: 18.0.2

IDE Workaround:
Ok, thanks to you responses I finally found a solution. 

In selenium IDE simply use the 'storeEval' command, for example : 
 Command = storeEval
 Target = window.location.hash='events/5000/participants/7011'

PHP Workaround (using javascript):
As a temp fix we just set the hash in JS

// PHP
protected function navigateHash($hash_url) {

  $this->getEval("window.location = window.location.href.split('#')[0] + '#/' + '$hash_url';");
}

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
