### ISSUE TITLE
Make it possible to choose Geckodriver for Firefox

### ISSUE THREAD

**Issue by soulgalore** [SeleniumHQ/selenium#2600]
## Meta -
OS:  OS X
Selenium Version: v3.0.0-beta-2
Browser:  Firefox 48
Javascript/NodeJS version

In the current version the Geckodriver is found searching the PATH. I would love to see the same implementation as for Chrome and Chromedriver where you can specify the Chromedriver using the ServiceBuilder. Or a simpler solution for now where you can specify the path to Geckodriver using a property. 

That would make it easier for us to automatically choose which Geckodriver to use, so the user doesn't need to be involved (in an embedded app).

**Comment by gauntface** [comment]
+1 with this feature.

On Node I managed to get around this by manipulating the path on `process.env.PATH += ':' + pathToGeckoDriver` and it seems to work on OS X and linux, but it feels pretty unstable and hacky.

**Comment by tobli** [comment]
Is there a way of using the Firefox ServiceBuilder when creating a driver via a Builder? For Chrome I use setDefaultService, but there's no equivalent for Firefox.

**Comment by kwa** [comment]
There is a somewhat detailed description of the underlying problem and grunt based solution here:
https://github.com/SeleniumHQ/selenium/issues/2577#issuecomment-305517214
