### ISSUE TITLE
Selenium chromedriver can not find element on Polymer website

### ISSUE THREAD

**Issue by huanleapp** [SeleniumHQ/selenium#2601]
Hi, 
I have automation project use Selenium Chrome webdriver.
When test on a website was made by Polymer framwork, I see Chromedriver can not find element or get text from site. 
Ex url: https://shop.polymer-project.org/
Chromedriver can not get element inner node "shadow-root". exit error is element is not found
 - Chrome Version 52.0.2743.116 m)
 - Selenium-server-standalone version 2.53
 - ChromeDriver version 2.23

I have use FirefoxDriver is working fine.  i user Firefox version 4.6

so are there anyway to run automation script by chromedriver for Polymer website ? 
Many Thanks

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
