### ISSUE TITLE
ElementNotVisibleException should not occur

### ISSUE THREAD

**Issue by kamleshmistry** [SeleniumHQ/selenium#2602]
I am creating tests for a public site, http://preview.harriscountyfws.org
This is very simple code and can be reproduced.
I get ElementNotVisibleException, but the element is clearly visible and should be selectable.
Create a blank class in a new application & copy paste the imports into that class, and copy paste the main method into that class, and set the start of the app as main.  You should notice the error.  You might also have to set the correct path of your chromedriver, but this problem is independent of driver (if you set up for a different driver, you will experience the same error).  Please assist:

Add this to your class:
    import org.openqa.selenium.By;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.WebElement;
    import org.openqa.selenium.chrome.ChromeDriver;
    import org.openqa.selenium.support.ui.Select;

Add this to your new class, and start execution on this class's main():
        public static void main(String[] args) {

           System.setProperty("webdriver.chrome.driver", "C:\\WebDrivers\\ChromeDriver\\chromedriver.exe");
            final WebDriver driver = new ChromeDriver();
            driver.get("http://preview.harriscountyfws.org/");
            driver.manage().window().maximize();
            String searchText;
            WebElement selection_element;
            WebElement listbox_element;
            Select selector;

            listbox_element = driver.findElement(By.cssSelector("span[aria-owns='ddlRegion_listbox']"));
            selection_element = driver.findElement(By.cssSelector("select[id='ddlRegion']"));

            listbox_element.click();
            Sleep(4);

            selector = new Select(selection_element);
            selector.selectByVisibleText("Fort Bend County");

            // driver.quit();

        }
        public static void Sleep(int i)
        {
            try { Thread.sleep(i * 300); }
            catch(InterruptedException ie) { System.out.println("Unexpected error in sleep"); }
        }

**Comment by lukeis** [comment]
The select element you are trying to manipulate is not a real select element... there is one in the source, but it is indeed not visible. You need to emulate what the user clicks, which are different html elements.

For futher help please follow up on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by kamleshmistry** [comment]
1a) I am looking at the select clause, and there is no "unselectable=on" clause for the select\option list.   However, if you say that there indeed is a different select statement (the "real select element"), even though it isn't visible, as you say, which one is it?  I would like to know.   (i.e., what would be my code logic, even though it wouldn't work)?
1b)Are you saying that the select option list is contained within a container listbox which is marked as unselectable?  (Is that the reason)?   So maybe the logic is right, but the underlying unselectable=on within the listbox parent is the culprit?
2) Is there a way to work with my developer to get whatever it is that is the problem to become un-invisiblized?  
3)Also, in general, is it possible to use code to automate testing in mutli-dropdown checkbox like the one I have?  Maybe the developer can assist by using a different control.  Or maybe its just a property setting.  If you have any guidance on this, then much appreciated.  I believe the code is generated from C#\asp.net code.
