### ISSUE TITLE
implicitly wait keyword is not working

### ISSUE THREAD

**Issue by abhishekroy2007** [SeleniumHQ/selenium#2604]
## Meta -
OS:  Windows 10 
Selenium Version:  3.0 
Browser:  crome

code:driver.manage().timeouts().implicitlyWait(10,TimeUnit.MINUTES);
## Steps to reproduce -1.open browser using selenium
2.open url using driver.get(" ....");
3.write driver.manage().timeouts().implicitlyWait(10,TimeUnit.MINUTES);
<!--

**Comment by lukeis** [comment]
that's not how implicit waits work, please read some of documentation on it:

http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits

Implicit waits will wait *up to* the time limit specified before throwing a timeout if an element is not found. It does not do a 'Thread.sleep' for your time specified. So if you have an element on the page that exists when you do your driver.findElement it will return immediately and not wait any extra time.

**Comment by abhishekroy2007** [comment]
Hi Luke,
Thanks for reply.Now the question is what is the use of explicitly wait.
As per my knowledge explicit wait is condition based...and implicit wait is
a time specified.please find the attachment.
Thanks

Abhishek kumar roy
New Delhi
ph no:8287947301
