### ISSUE TITLE
Firefoxdriver: Window/current/position did not match a known command

### ISSUE THREAD

**Issue by datatooldev** [SeleniumHQ/selenium#2609]
## Meta -
OS:  Windows 7
Selenium Version:  3.0 Beta 2
Browser:  Firefox
Browser Version:  48.0
## Expected Behavior - 
The driver should return a window position and size when driver.Manage().Window.Position is called.
## Actual Behavior -
Exception is raised:
driver.Manage().Window GET /session/e982ecfb-6557-461a-a68f-f00081fe8fe8/window/current/position did not match a known command
## Steps to reproduce -

var driver = new FirefoxDriver(new FirefoxOptions());
var position = driver.Manage().Window.Position;

**Comment by lukeis** [comment]
the driver should be calling  /session/<sessionId>/window/position  as per spec, need to adjust the java client library

**Comment by titusfortner** [comment]
Ruby needs to implement this as well since this was left off of the w3c spec the last time I looked at it & implemented things.

**Comment by shs96c** [comment]
Fixed in the java tree.

**Comment by harshg0910** [comment]
I'm facing same issue with C# client library 

OS: Windows 10
Selenium Version: 3.0 Beta 3
Browser: Firefox
Browser Version: 48.0

Has it been resolved with C# library ?

**Comment by agjaeger** [comment]
I have this issue with the Python library

OS: Windows 8
Selenium Version: 3.0.0b3
Browser: Firefox 49
