### ISSUE TITLE
Manage().Cookies.DeleteAllCookies() timeout

### ISSUE THREAD

**Issue by cherrr** [SeleniumHQ/selenium#2610]
## Meta -
OS: Windows server 2012 R2 Datacenter

Selenium Version:  2.53.0 IDE

Browser:  IE 11

## Expected Behavior -
At least not timeout
## Actual Behavior -
Timeout, then browser needs to be restarted
## Steps to reproduce -

Simply using Manage().Cookies.DeleteAllCookies() with an IWebDriver to IE.

Note that exactly the same configuration works fine on Windows 7.

If more details are needed, let me know.

**Comment by lukeis** [comment]
can you show the stacktrace you are receiving?

**Comment by lukeis** [comment]
and a simple script to reproduce the issue would be appreciated

**Comment by cherrr** [comment]
using System;
using System.Diagnostics;
using OpenQA.Selenium;
using OpenQA.Selenium.Remote;

namespace Github
{
    class Program
    {
        static void Main()
        {
            try
            {
                IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), DesiredCapabilities.InternetExplorer(), TimeSpan.FromSeconds(40));

                driver.Manage().Cookies.DeleteAllCookies();

                while (true) ;
            }
            catch (Exception)
            {
                StackTrace st = new StackTrace(true);
                string stackIndent = "";
                for(int i =0; i< st.FrameCount; i++ )
                {
                    // Note that at this level, there are four
                    // stack frames, one for each method invocation.
                    StackFrame sf = st.GetFrame(i);

                    Console.WriteLine();
                    Console.WriteLine(stackIndent + " Method: {0}",
                        sf.GetMethod() );
                    Console.WriteLine(  stackIndent + " File: {0}", 
                        sf.GetFileName());
                    Console.WriteLine(  stackIndent + " Line Number: {0}",
                        sf.GetFileLineNumber());
                    stackIndent += "  ";
                }
            }
            while (true) ;
        }
    }
}

**Comment by cherrr** [comment]
for the stack trace, I've never done it and lost quite time on tutorial which didn't provide the information I believe you want... so far I only obtain information relative to where it crashes in my program. Would you have a good tutorial or example I could use?

**Comment by lukeis** [comment]
A stack trace is just the exception that you'll get with running your program without the try/catch block. 

Your code is a bit confusing. First off any Cookie manipulation needs to be done when your browser is on a website. Delete all cookies doesn't removing from all domains, only the active one. So you must call driver.get(url) first. 

Until you provide a script to help reproduce an actual issue I'm going to close this one. If you need help with writing webdriver scripts or understanding the API, I suggest you ask on the selenium-users Google group:

https://groups.google.com/forum/#!forum/selenium-users

**Comment by cherrr** [comment]
I see, I though it cleared all of them. I will change the way I used it then, thanks.

I understand my usage was wrong, however even the code being wrong, isn't the fact that it timeouts in a specific case still a problem? I've been using it for quite a while and even being wrong, before that specific case it never made a timeout. I'm not gonna argue for it to be fixed, just suggesting.

Thanks again for your help
