### ISSUE TITLE
Can't run scripts on XUL pages

### ISSUE THREAD

**Issue by NHellFire** [SeleniumHQ/selenium#2613]
Similar to #1253 except I'm wanting to run some scripts on about:downloads. 

## Meta -
OS:  Ubuntu 16.10
Selenium Version:  2.53.6, Python
Browser:  Firefox
Browser Version:  48.0

## Expected Behavior -
Firefox shows alert with page title.
## Actual Behavior -
selenium.common.exceptions.WebDriverException: Message: waiting for doc.body failed

## Steps to reproduce -
```python
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("about:downloads")
driver.execute_script("alert(document.title);")
```

**Comment by AutomatedTester** [comment]
You need to use https://github.com/mozilla/geckodriver/ and the new `set_context('chrome')` command to be able to speak to Chrome pages. To return back to normal pages you do `set_context('content')`
