### ISSUE TITLE
Chrome v54 raises SessionNotCreatedError and exits

### ISSUE THREAD

**Issue by seanpoulter** [SeleniumHQ/selenium#2614]
## Meta -
OS: Windows 10 x64 build 10586

Selenium Version: selenium-webdriver (npm) v3.0.0-beta-2 **or** selenium-webdriver (gem) v2.53.4

Browser: Chrome (dev stream)

Browser Version:  54.0.2824.0

(related) Issue filed with the ChromeDriver project: [#1464](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1464)

## Expected Behavior -
A new session is created in Chrome.

## Actual Behavior -
Chrome opens displaying only a blank window (menu, frame, etc are white) then promptly closes. An error is logged to the console. The message is included below in the steps to reproduce:

## Steps to reproduce -
With the ChromeDriver v2.22 or 2.23 available, and dev stream for Chrome (now at v54):

### JavaScript
Edit and run the [google_search.js example](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/javascript/node/selenium-webdriver/example/google_search.js#L38) using `.forBrowser('chrome')`:
```.js
var webdriver = require('..'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```

Output is:
```
X:\node_modules\selenium-webdriver\lib\promise.js:654
    throw error;
    ^

SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"12656.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2824.0)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10586 x86_64)
    at WebDriverError (X:\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (X:\node_modules\selenium-webdriver\lib\error.js:214:5)
    at Object.checkLegacyResponse (X:\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (X:\node_modules\selenium-webdriver\lib\http.js:396:13)
    at doSend.then.response (X:\node_modules\selenium-webdriver\lib\http.js:328:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (X:\node_modules\selenium-webdriver\lib\webdriver.js:366:24)
    at Driver (X:\node_modules\selenium-webdriver\chrome.js:804:38)
    at Builder.build (X:\node_modules\selenium-webdriver\index.js:546:16)
    at Object.<anonymous> (X:\node_modules\selenium-webdriver\example\google_search.js:44:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
From: Task: WebDriver.navigate().to(http://www.google.com/ncr)
    at Driver.schedule (X:\node_modules\selenium-webdriver\lib\webdriver.js:414:17)
    at Navigation.to (X:\node_modules\selenium-webdriver\lib\webdriver.js:1042:25)
    at Driver.get (X:\node_modules\selenium-webdriver\lib\webdriver.js:832:28)
    at Object.<anonymous> (X:\node_modules\selenium-webdriver\example\google_search.js:46:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

### Ruby v2.2.3
*Apologies for hastily using the `watir-webdriver` gem that wraps `selenium-webdriver`.*
```.bat
gem install 'watir-webdriver'
ruby -e "require 'watir-webdriver; b = Watir::Browser.new :chrome; b.goto 'google.com';"
```

Output is:
```
c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': session not created exception (Selenium::WebDriver::Error::SessionNotCreatedError)
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"7784.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2824.0)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.10586 x86_64)
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:87:in `new'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:87:in `create_response'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:68:in `call'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:123:in `create_session'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/chrome/bridge.rb:48:in `initialize'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:64:in `new'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:64:in `for'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver.rb:84:in `for'
	from c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/browser.rb:46:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
```

## Additional Sightings -

  * On StackOverflow - [Protractor - Getting “Runtime.executionContextCreated has invalid 'context” error when i run Protractor](https://stackoverflow.com/questions/38918486/protractor-getting-runtime-executioncontextcreated-has-invalid-context-erro)
  * In CI logs on 2016-08-06 - [tastejs / todomvc - Build #1619](https://travis-ci.org/tastejs/todomvc/builds/150285315#L476)

**Comment by lukeis** [comment]
Thanks for logging the issue in the chromedriver project, there doesn't appear to be anything we can do from the selenium client side of things and you should track this issue there.

**Comment by markwheeler700** [comment]
Happening for me as well

**Comment by NiklasGollenstede** [comment]
Updating to ChromeDriver v2.24 fixed this for me.

**Comment by attila123** [comment]
@NiklasGollenstede wrote: "Updating to ChromeDriver v2.24 fixed this for me."

Even after installing chrome driver 2.24 I did not get webdriver-manager to use that, see my comment at https://github.com/angular/webdriver-manager/issues/93

**Comment by NiklasGollenstede** [comment]
I wasn't using the `webdriver-manager`, I downloaded v2.24 explicitly (on Windows 10 using chocolatey). So it was the only version present on my system.

If you want to use `webdriver-manager`, you could try to uninstall and then reinstall it. I guess that would remove old chromedriver versions.

**Comment by faminram** [comment]
I am using webdriver-manager, uninstall and then reinstall it does not remove the old chromedriver version. still pointing to chromedriver=2.22.397933.

**Comment by zixia** [comment]
I ran into this issue under win32, because there is a old `chromedriver` was in nodejs directory, and always use that version, no matter what I install in the node_modules/... 

so I deleted that version in nodejs directory.

**Comment by faminram** [comment]
Now my drivers are pointing to the latest chrome drivers which resolved the previous issue but still not able to run tests in chrome.

This time browser instance does started for couple of sec and than I get the following error.

Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:55999
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:55999
    at ClientRequest.<anonymous> (C:\Development\Series5\src\Ram.Series5.End2EndTests\node_modules\selenium-webdriver\http\index.js:381:15)

Any idea?

**Comment by kleeb** [comment]
I am having the same with chromedriver

**Comment by fengshuo** [comment]
@kleeb @faminram I had the same issue. I noticed that whenever I run selenium install/start, it will just automatically install the older version of chrome driver(2.21), but after I updated the `selenium-standalone` to `5.8.0` from `5.1.0`, it will install chrome driver(2.25) which solved the issue.

**Comment by kleeb** [comment]
I am using protractor on Mac and needed to uninstall and install once again all packages to get it working.

**Comment by faminram** [comment]
Its working for me as after I updates to chrome driver (2.25).

**Comment by ShriQ** [comment]
I have got similar issue 

FeatureSetup threw exception. System.InvalidOperationException: System.InvalidOperationException: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"7944.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.22.397933,platform=Windows NT 6.2.9200 x86_64) (33).

**Comment by hakehuang** [comment]
If you still have problem when upgrade to chromedriver2.25, most likely that you have a old chromdriver hiden in your system path. below is my debug trick
add below line in the 
 c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/chrome/service.rb
puts @executable_path 
before the 
server_command = [@executable_path, "--port=#{@port}", *@extra_args]
then you will know where to delete the old hidden chromedrive

**Comment by hakehuang** [comment]
If you still have problem when upgrade to chromedriver2.25, most likely that you have a old chromdriver hiden in your system path. below is my debug trick
add below line in the 
 c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/chrome/service.rb
puts @executable_path 
before the 
server_command = [@executable_path, "--port=#{@port}", *@extra_args]
then you will know where to delete the old hidden chromedrive

**Comment by hakehuang** [comment]
If you still have problem when upgrade to chromedriver2.25, most likely that you have a old chromdriver hidden in your system path. below is my debug trick
add below line in the 
 c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/chrome/service.rb
puts @executable_path 
before the 
server_command = [@executable_path, "--port=#{@port}", *@extra_args]
then you will know where to delete the old hidden chromedrive

**Comment by hakehuang** [comment]
If you still have problem when upgrade to chromedriver2.25, most likely that you have a old chromdriver hidden in your system path. below is my debug trick
add below line in the 
 c:/Ruby/Ruby223-x64/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/chrome/service.rb
puts @executable_path 
before the 
server_command = [@executable_path, "--port=#{@port}", *@extra_args]
then you will know where to delete the old hidden chromedrive

**Comment by nfagen** [comment]
Using puts @executable_path in the service.rb worked for me! Thanks. I use rbenv and the offending chromedriver was actually in the .rbenv/shims directory and not further down in the ruby version as it was on another machine that I run with rvm. Hope this helps someone else running rbenv!

**Comment by jjurek31** [comment]
+1

**Comment by pumbers** [comment]
Every hit I've found so far indicates updating chromedriver to >2.24 fixes this problem, but I,m on 2.25 and still can't get it to work:

```
SessionNotCreatedError: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=54.0.2840.59)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64)
    at WebDriverError (C:\Users\pumbers\Documents\workspace-OCI\oci-prototypes\node_modules\selenium-webdriver\lib\error.js:27:5)
    at SessionNotCreatedError (C:\Users\pumbers\Documents\workspace-OCI\oci-prototypes\node_modules\selenium-webdriver\lib\error.js:214:5)
    at Object.checkLegacyResponse (C:\Users\pumbers\Documents\workspace-OCI\oci-prototypes\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Users\pumbers\Documents\workspace-OCI\oci-prototypes\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\pumbers\Documents\workspace-OCI\oci-prototypes\node_modules\selenium-webdriver\lib\http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by faminram** [comment]
It work for me when updates to latest chrome version V55. I wonder if you give a try by removing node_modules and install everything again, should fix the problem.

**Comment by sbabupresidency1** [comment]
I am getting issue with my mac machine. 

1. MAC OS - EI Caption
2. Chrome version 55
3. Chromedriver - tried with 24, 25, 26 and 27
4. Selenium version - 2.53.1


But still I am getting the same issue. 
I am using framework using selenium and java conjunction.

Please help me guys.

**Comment by ratneshchandna** [comment]
I had a similar issue when connected via a coffee shop hotspot; the issue was resolved as soon when I switched to my cell phone's hotspot
