### ISSUE TITLE
NullPointerException being thrown in "main" thread for org.openqa.grid.selenium.GridLauncherV3.buildLauncher

### ISSUE THREAD

**Issue by JoshuaBurns** [SeleniumHQ/selenium#2616]
## Meta -
OS:  Windows 7 Professional N

Selenium Version:  IDE

Browser:  Firefox 

Browser Version:  47.0.1

## Expected Behavior -
Executing `java -jar C:\git\sniper-selenium\selenium.jar -timeout '70000' -htmlSuite '*chrome' 'http://devel.auctionsniper.com/' 'Regression_new_and_improved2.html' 'C:\git\sniper-selenium\report.html' -UserExtensions 'C:\git\sniper -selenium\user-extensions.js' -port 44760 -trustAllSSLCertificates` from the working directory would start the standalone server and run selenium ide script

## Actual Behavior - 
![sniperpowershell](https://cloud.githubusercontent.com/assets/19497855/17708342/6bf9aa4c-6399-11e6-90e3-703515d64c5e.PNG)

This is using the latest standalone server 
http://selenium-release.storage.googleapis.com/3.0-beta2/selenium-server-standalone-3.0.0-beta2.jar
I get the same results using standalone server 2.53.1

**Comment by lukeis** [comment]
@shs96c HTMLLauncher isn't included in the standalone jar, thus this NPE when trying to use htmlSuite

**Comment by everflux** [comment]
A better error message instead of crashing would be helpful, though.

**Comment by shs96c** [comment]
I've also broken out a single jar that can be downloaded that contains everything you need to run the html suites. We'll make this available when we ship 3.0.0-beta3

**Comment by b2k** [comment]
The "better error message" just committed mentions a 'selenium-leg-rc' jar, but gives no indication where to find it. It's not available on the SeleniumHQ.org download page. Where is it?

**Comment by lukeis** [comment]
we haven't released beta3 yet

**Comment by shs96c** [comment]
Beta 3 is out now 👍

Can you let me know if this is any better?

**Comment by b2k** [comment]
I'll add that to my schedule. I should be able to try it out later this week.






On Wed, Sep 7, 2016 at 6:33 AM -0500, "Simon Stewart" <notifications@github.com> wrote:












Beta 3 is out now 👍



Can you let me know if this is any better?

**Comment by shs96c** [comment]
Great. Thank you.

**Comment by shs96c** [comment]
Just checked with the latest standalone server. With that, you get the nicer error message. I've also just pushed f7f5d046161f83bf00d46aca61698531ac32ebf6 which does a far better job or parsing the original flags you could pass to the standalone server.

I believe that this closes this issue, but please feel free to reopen if necessary.
