### ISSUE TITLE
IWebdriver problems with avas?

### ISSUE THREAD

**Issue by cherrr** [SeleniumHQ/selenium#2620]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.0

Browser:  Firefox

Browser Version:  

## Steps to reproduce - With Avast 12.2.2276, just try to initiates a IWebdriver as such:

IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), DesiredCapabilities.Firefox(), TimeSpan.FromSeconds(80));

I get the following error (**however even closing Avast doesn't work**):

CBrowser.cs, startBrowser: RemoteWebDriver for Firefox couldn't be initialised. Following error: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":2,"seen":true}
1471442370018	addons.xpi	DEBUG	Updating XPIState for {"id":"sp@avast.com","syncGUID":"CFhLiGOAHaB9","location":"winreg-app-global","version":"10.3.5.39","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://sp/content/common/skin/img/logo-safeprice-48.png","icon64URL":null,"defaultLocale":{"name":"Avast SafePrice","description":"Safe shopping extension","creator":"AVAST Software","homepageURL":"http://www.avast.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files\\AVAST Software\\Avast\\SafePrice\\FF","installDate":1471146557689,"updateDate":1471146557689,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1877359,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"38.0a1","maxVersion":"43.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1471442370019	DeferredSave.extensions.json	DEBUG	Save changes
1471442370019	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1471442370019	addons.xpi-utils	DEBUG	Updating add-on states
1471442370020	addons.xpi-utils	DEBUG	Writing add-ons list
1471442370023	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1471442370024	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1471442370025	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1471442370025	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1471442370026	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1471442370027	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.4.3
1471442370054	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1471442370054	addons.manager	DEBUG	Provider finished startup: XPIProvider
1471442370054	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1471442370054	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1471442370054	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1471442370055	addons.manager	DEBUG	Starting provider: GMPProvider
1471442370065	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1471442370065	addons.manager	DEBUG	Provider finished startup: GMPProvider
1471442370065	addons.manager	DEBUG	Starting provider: PluginProvider
1471442370065	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1471442370066	addons.manager	DEBUG	Provider finished startup: PluginProvider
1471442370066	addons.manager	DEBUG	Completed startup sequence
1471442371500	DeferredSave.extensions.json	DEBUG	Starting timer
1471442371513	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1471442371513	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1471442371513	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1471442371558	DeferredSave.extensions.json	DEBUG	Starting write
1471442371725	addons.repository	DEBUG	No addons.json found.
1471442371726	DeferredSave.addons.json	DEBUG	Save changes
1471442371729	DeferredSave.addons.json	DEBUG	Starting timer
1471442371802	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1471442371802	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1471442371803	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1471442371976	DeferredSave.addons.json	DEBUG	Starting write
1471442371983	DeferredSave.extensions.json	DEBUG	Write succeeded
1471442372231	DeferredSave.addons.json	DEBUG	Write succeeded

**Comment by lukeis** [comment]
Sorry, we don't support AVAST here, you might have to contact them to see if they can help you
