### ISSUE TITLE
To add "IsChecked" property to checkbox objects

### ISSUE THREAD

**Issue by koreyba** [SeleniumHQ/selenium#2621]
It's very strange that Selenium webdriver is still can't check if a checkbox is checked or not.

For now it works only if a checkbox has "checked" attribute.

But there is a big need to be able to check any checkbox, not dependently on "checked" attribute.

In JS it's very easy to do by checking "checked" property of an object.

Why it can't be implemented in Webdriver? 

Property "Selected" doesn't work correctly if a checkbox doesn't have "checked" attribute.

So I want to have something like:

IWebelement  obj = driver.Findelement(By.id("checkbox"));
bool m = obj.IsChecked;

**Comment by lukeis** [comment]
http://seleniumhq.github.io/selenium/docs/api/dotnet/?topic=html/P_OpenQA_Selenium_IWebElement_Selected.htm

element.Selected  is the API you're looking for

**Comment by lukeis** [comment]
If it's not working properly, please show us a reproducible test case that demonstrates that
