### ISSUE TITLE
Selecting a command or executing a command/case/suite shouldn't switch to 'Log' tab

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#2624]
Essentially a follow up for https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3028. I suggest a solution as per https://github.com/SeLite/SeLite/commit/7a8850296d60a97defc77079d112d07ea7bf77de.

If you're willing to accept a pull request, I'll provide one.

**Comment by peter-kehl** [comment]
As a workaround, use [SeLite Clipboard And Indent](http://selite.github.io/SeleniumIDEtips#clipboard-and-indent).

Please vote for this issue. This could be easily fixed. It would make people's life easier.

(For implementation see https://github.com/SeLite/SeLite/commit/7a8850296d60a97defc77079d112d07ea7bf77de.)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
