### ISSUE TITLE
No way to wait for page change/load

### ISSUE THREAD

**Issue by atheros** [SeleniumHQ/selenium#2626]
## Meta -
OS:  Any
Selenium Version:  Any
Browser:  Any
Browser Version:  Any
## Steps to reproduce -
There is currently no way to check for a page load event.
Case:
- load page
- press a button that invokes AJAX call
-- as a result of AJAX call, javascript submits a form or just change location
- there is no way to wait for page load

In python there is expected_conditions, but the only way to use it in this case is to wait for some element on that page, not for the page itself.

Example code:

    action = webdriver.ActionChains(self.browser)
    action.send_keys(valid_card, Keys.ENTER).perform() # this invokes AJAX that on success will load an other page.

    wait = WebDriverWait(self.browser, 10)
    wait.until(expected_conditions.location_to_load(expected_url))

**Comment by gallak87** [comment]
I'm unfamiliar with the python APIs, but here is something you could do in C#. If your ajax call sets the document.readyState to 'loading' and then back to 'complete' you could do:

var wait = new WebDriverWait(webDriver, TimeSpan.FromSeconds(30));
wait.Until(driver => ((IJavaScriptExecutor) webdriver).ExecuteScript("return document.readyState").Equals("complete"));

**Comment by lukeis** [comment]
Selenium doesn't have the ability to understand when a page is loaded in every possible way that web pages render to a user. We attempt to do some waiting based on standard signals the browser provides, like onDOMReady. But that only does so much and we can't predict every JavaScript library that exists. This is why we have the WebDriverWait class. It's up to you, the user, to define what it means for the page to be loaded and wait for that condition. 

Sorry, but selenium still can't and won't solve the Halting Problem for the web.

**Comment by atheros** [comment]
You misunderstood me lukeis. What I want to wait for is the location change, not page load after some dynamic page initialization.

**Comment by lukeis** [comment]
Selenium only does it's best effort to wait... there's many ways a location can change. If it's more than just an `&lta href="new_location">` then selenium has a hard time determining if the click should or shouldn't invoke a location change, thus you have to do it yourself. Again this does speak to the Halting Problem I was referencing before.

If you believe there is a bug in the Selenium project that should be fixed, then you'll need to provide a reproducible test script along with a web page that shows the issue. If you can't provide a url to reproduce the issue, I recommend creating an example with jsfiddle.net
