### ISSUE TITLE
Chrome 54 Failing to connect

### ISSUE THREAD

**Issue by gauntface** [SeleniumHQ/selenium#2628]
## Meta -
OS:  OS X, Gnome Ubuntu 16.04
Selenium Version:  
3.0.0-beta-2
Browser:  
Chrome

Browser Version:  
54

## Expected Behavior -
To open browser and get page when calling get('https://google.com/')

## Actual Behavior -
The browser opens but the page is never navigated to

## Steps to reproduce -
Just try call get on a webdriver pointing at Chrome 54

Error Given: 

SessionNotCreatedError: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"17195.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2824.0)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64)

**Comment by tommywo** [comment]
try to update chromedriver to 2.23

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by frankmeza** [comment]
Using Chrome 54.0.28xxx, I ran into this same issue. I updated my version of chromedriver to 2.25 here: https://chromedriver.storage.googleapis.com/index.html?path=2.25/ , and replaced my older version. I changed nothing in the code, ran my tests, and it fired right back up.
