### ISSUE TITLE
selenium IE driver could not find element by xpath and can not execut javascript

### ISSUE THREAD

**Issue by zhuchuji** [SeleniumHQ/selenium#2629]
## Meta -
OS:  
windows 7

Selenium Version:  
2.53.1

Browser:  
internet explorer 11

Browser Version:  

## Expected Behavior -
1. find element by text with xpath: //*[text()='abc']
2. execute javascript by calling driver.executeScript()
## Actual Behavior -
1. can not find any element. And for many other xpath patterns driver can not find related element
2. call executeScript() method to execute javascript, but bring exception "unable to get browser"

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
