### ISSUE TITLE
 Selenium v3.0.0-beta2 Navigate().GoToUrl() do not work when I call that second time

### ISSUE THREAD

**Issue by Efusoft** [SeleniumHQ/selenium#2630]
OS:  
Windows 10 
Selenium Version:  
v3.0.0-beta2
Browser:  
Firefox 48.0.1

I use geckodriver. 

string url1 = "something1", url2 = "something2";

var profile = new FirefoxProfile();
DesiredCapabilities capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability("marionette", true);
FirefoxDriver driver = new FirefoxDriver(profile);
driver.Navigate().GoToUrl(url1);
driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));
driver.Navigate().GoToUrl(url2);
driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));

ERROR: driver open url1, but do not open url2. When open driver first time driver.Navigate().GoToUrl() method working success but second time it doesn't work.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
