### ISSUE TITLE
Surfacing stdout/stderr output from drivers

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#2632]
Selenium does a poor job at surfacing stdout/stderr output from drivers, as well as making it possible to increase verbosity in a consistent way.

One of the major productivity blockers we have when diagnosing issues in [geckodriver](https://github.com/mozilla/geckodriver) is that there’s no consistent way to surface the output as it is often swallowed by the language binding. geckodriver supports a `-vv` (let’s call it “very verbose”) setting that increases logging output from Firefox/Marionette. It is furthermore possible to set the environment variable `RUST_LOG=debug` to get additional logging from the geckodriver binary itself. It is possible that we can trigger that implicitly when `-vv` is set in the future to make things easier for Selenium and users.

Some bindings, i.e. for Node.js, supports exposing stdout/stderr but only by modifying a class constructor’s argument.  When we tell users “to run geckodriver with the `-vv` flag” they often have no idea where to start.

I don’t have any strong opinions on _how_ more verbose output should be triggered in Selenium, but it should probably be something consistent that can be propagated to the various bindings, drivers, and servers. Something like an environment variable would do, but there may be more sophisticated ways of solving this in Java that I’m not aware of:

```
% DEBUG=1 java -jar selenium-server.jar
```

A tangent, and this should probably be a separate issue altogether, it would be an interesting experiment to capture the last _N_ number of output when an error occurs and print it. The default “no additional logging information was provided by the driver” message is not useful and not true. We can probably make it work better.

(cc @jgraham @AutomatedTester)

**Comment by jleyba** [comment]
If you want a consistent way to enable logging across languages, that means either doing something with capabilities (and requires users to modify code when they want logging) or adding environment variables.

**Comment by andreastt** [comment]
I guess language binding-specific could also work, as long as they propagate their verbosity settings down to the drivers and enable stdout/stderr to surface.

**Comment by andreastt** [comment]
As @jgraham mentions in https://github.com/mozilla/geckodriver/issues/152#issuecomment-241050301 we’re also open to add a capability for enabling it. We will probably do that in the interim to ease debugging for our users. But it would still be useful to have a uniform way of enabling it Selenium.

**Comment by titusfortner** [comment]
Ruby currently implements `ENV['DEBUG'] = 'true'` and `$DEBUG = true` that will record to stdout all of the commands made to and from the driver/server, as well as the Marionette debug and info output. It also displays every single rescued error message the program encounters, which results in a lot of extra noise.

Is there something else that is needed from the Ruby implementation to address this Issue?

I'd actually like to switch Ruby to using the much more feature-rich Ruby `Logger` class to allow output to file and to be able to set the level of information being returned (e.g. just the commands to and from the server for easier copy/paste for filing bugs, etc).

**Comment by andreastt** [comment]
I think a DEBUG environmental variable to surface suppressed subprocess output to stdout would be a good improvement.

**Comment by titusfortner** [comment]
I don't believe Ruby is suppressing anything. Is there something more that geckodriver is outputting that needs to be captured?
https://gist.github.com/titusfortner/b71fd5633c68f7c35fde4cb0ed7cdbe3

**Comment by cgoldberg** [comment]
The ability to adjust output configuration without modifying code would be very handy.  Environment vars seem like a decent way to pass options... but I think a simple boolean flag will be too limited.  There are some complex output scenarios to consider.  For example, if setting `DEBUG=1` enables geckodriver verbose output, does it also affect other sources of output?  What if you want to enable just non-verbose output.  Or only see debug output from a different component.  Does this include output streams from both stdout and stderr?

some possible sources of output:

* selenium server
* selenium client bindings
* driver
* browser

besides the various sources, also consider that some streams can be set to different granularity levels (INFO, WARNING, ERROR, VERBOSE, etc)

With those things in mind, is there a good way to handle these complex output scenarios?

**Comment by titusfortner** [comment]
@cgoldberg this is what I'm planning to do with #2481. The [Ruby Logger class](http://ruby-doc.org/stdlib-2.3.3/libdoc/logger/rdoc/Logger.html) provides 6 different levels of granularity.

Is the purpose to expose the information in the first place, or to implement different levels of output? If it is the former, I believe we can remove the rb tag from this. Unless we decide we want something different from `ENV['DEBUG'] = true` in which case Ruby would just need to update what it is searching on.

**Comment by p0deje** [comment]
Actually, Ruby bindings do not support that. In Ruby, we enable full verbose output only when `$DEBUG` global variable is set. This variable is controlled by `-d` switch of Ruby. Do not confuse it with environment variable. 

This is not the same:

```
$ ruby -d test.rb
$ DEBUG=1 ruby test.rb
```

With that said, I've added support in Ruby bindings for environment variable as well (dab663db4a110f0bacc8eac826b9530c7a4e9073). An example of such output would be this:

```
$ env DEBUG=1 ruby -e "require 'selenium-webdriver'; Selenium::WebDriver.for(:firefox).quit"
2017-08-16 08:58:42 DEBUG Selenium Executing Process ["/usr/local/bin/geckodriver", "--binary=/Applications/Firefox.app/Contents/MacOS/firefox-bin", "--port=4444"]
2017-08-16 08:58:42 DEBUG Selenium polling for socket on ["127.0.0.1", 4444]
1502852322404	geckodriver	INFO	Listening on 127.0.0.1:4444
2017-08-16 08:58:42 INFO Selenium Skipping handshake as we know it is W3C.
2017-08-16 08:58:42 INFO Selenium -> POST session
2017-08-16 08:58:42 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{}},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{}}]}}
2017-08-16 08:58:42 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"201"}
1502852322661	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1502852325667	Marionette	INFO	Listening on port 60964
1502852326023	Marionette	DEBUG	loaded listener.js
2017-08-16 08:58:46 INFO Selenium <- {"value": {"sessionId":"bdadc9bb-c99d-8c4d-966b-20081de2d628","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"54.0","moz:accessibilityChecks":false,"moz:processID":79050,"moz:profile":"/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.EFgosXuOln07","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.7.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-08-16 08:58:46 INFO Selenium Detected W3C dialect.
2017-08-16 08:58:46 INFO Selenium -> DELETE session/bdadc9bb-c99d-8c4d-966b-20081de2d628
1502852326046	Marionette	INFO	New connections will no longer be accepted
2017-08-16 08:58:46.126 plugin-container[79051:1554740] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9c3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-08-16 08:58:46.131 plugin-container[79051:1554740] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9f03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
2017-08-16 08:58:46 INFO Selenium <- {"value": {}}
```

**Comment by andreastt** [comment]
If your programming language provide different levels of granularity, you might want to consider mapping those to the `--log <LEVEL>` flag of geckodriver as well.

**Comment by AutomatedTester** [comment]
We have improved the ability to do logging and have added observability to the server so this is greatly improved. I am closing as minor tweaks for each binding can happen separately
