### ISSUE TITLE
Python - Selenium won't start browser because it assumes port as closed

### ISSUE THREAD

**Issue by BrnoPCmaniak** [SeleniumHQ/selenium#2637]
## Meta -
OS: 4.6.4-301.fc24.x86_64
Selenium Version:  2.53.5
Browser:  Firefox (But the issue probably affect also Chrome and PhantomJS)
Browser Version:  48

## Expected Behavior -
Start Browser
## Actual Behavior -
Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 81, in __init__
    self.binary, timeout)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/vagrant/.virtualenvs/venv/lib/python3.5/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmp7h3kzj0f If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

## Steps to reproduce -
```
browser = webdriver.Firefox()
```
Not sure what causes this, but I found out where is the problem.

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/utils.py#L97-L113

Port is opened:
```
nmap -p T:42487 127.0.0.1

Starting Nmap 7.12 ( https://nmap.org ) at 2016-08-21 00:19 UTC
Nmap scan report for ### (127.0.0.1)
Host is up (0.00015s latency).
PORT      STATE SERVICE
47035/tcp open  unknown
```

I tried the function outside in shell:
```
>>> import socket
>>> socket_ = socket.create_connection(("127.0.0.1", "47035"), 1) # Works
>>> socket_ = socket.create_connection(("localhost", "47035"), 1) # Fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib64/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
>>> socket_ = socket.create_connection(("127.0.0.1", "47035"), 1) # Works
>>> 
```

**Comment by BrnoPCmaniak** [comment]
For phantomjs the same applies here:
https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.0-beta-2/py/selenium/webdriver/phantomjs/service.py#L63

**Comment by AutomatedTester** [comment]
The problem is you are using a version of Selenium that doesnt work on Firefox 48. You will need to set add `{"marionette": True}` as a capability and have https://github.com/mozilla/geckodriver/ on your path

**Comment by BrnoPCmaniak** [comment]
@AutomatedTester Well, I tried Firefox 46 and 47 with same issue. And hard editing functions I specified before makes Selenium now works like charm for Firefox and Phantomjs. So I'm not sure that's the problem. And suprisingly I was not able to make Selenium with geckodriver work.

**Comment by BrnoPCmaniak** [comment]
@AutomatedTester moreover using `{"marionette": True}`  won't fix Phantomjs which suffers the same issue

**Comment by AutomatedTester** [comment]
I see what the problem is... you must have localhost pointing to something that isn't a loopback address. This is a constant battle for us when people have non-standard setups. We have flip flopped between IP address and named address.

**Comment by BrnoPCmaniak** [comment]
@AutomatedTester Ohh well I have standard Fedora 24 Cloud Base in Vagrant and I have localhost pointing to
```
$ ping localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.018 ms
```

**Comment by Csunquan** [comment]
I don't know where the problme is .If you konw,please let me konw,i want konw more about this!
try install Firefox 47.0.1 and never update.then problem solved.
