### ISSUE TITLE
test case Dependency overwrites priority in TestNG

### ISSUE THREAD

**Issue by nirajsharma999** [SeleniumHQ/selenium#2641]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.0 WebDriver 

Browser:  Chrome

## Steps to reproduce - Please execute below mentioned simple Driver class.
package test.pack;

import org.testng.annotations.Test;

public class dependencyTest {

	@Test(priority = 1)
	public void testMethod001() {
		System.out.println("TC-1");
	}

	@Test(dependsOnMethods = { "testMethod001" }, priority = 1)
	public void testMethod002() {
		System.out.println("TC-2");
	}

	@Test(dependsOnMethods = { "testMethod002" }, priority = 1)
	public void testMethod003() {
		System.out.println("TC-3");
	}

	@Test(dependsOnMethods = { "testMethod001" }, priority = 2)
	public void testMethod004() {
		System.out.println("TC-4");
	}
}

######Output #######
TC-1
TC-2
TC-4
TC-3
PASSED: testMethod001
PASSED: testMethod002
PASSED: testMethod004
PASSED: testMethod003

===============================================
    Default test
    Tests run: 4, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 4, Failures: 0, Skips: 0
===============================================

**Comment by lukeis** [comment]
Please log a bug with TestNG. This has nothing to do with selenium

**Comment by nirajsharma999** [comment]
Thank you for you reply, I am going to log it with TestNG.
