### ISSUE TITLE
[Feature] Multi-thread parallel execution

### ISSUE THREAD

**Issue by ptahchiev** [SeleniumHQ/selenium#2644]
Hello,

the new JUnit5 is going to ship with parallel execution:

https://github.com/junit-team/junit5/issues/60

and this is something I'd really want to see in Selenium too. 

I have a lot of (more than 300) selenium tests and I have a very complex initialization process before running them:

 - first import SQL scripts
 - then import data into database from csv files.
 - then import some more data from rest API calls.
 - then perform some data manipulation in the database.
 - (we are now 10 minutes in the build)
 - now start executing the tests against the populated database.
 - Finish (usually takes ~ 2:20 minutes).

My problem is that CircleCI marks my build as timeout (they have a 2-hour limit) and I really can't have a green build :( I can't use selenium-grid because I have no access to CircleCI. I don't want to distribute the selenium tests to run on different machines because then I have to perform the same database initialization on each node and this means that the tests are executed against (potentially) different databases.

Is it possible to align with JUnit5 and provide some sort of parallel execution where tests run in separate tabs or separate browser windows?

**Comment by lukeis** [comment]
This is already possible with selenium, it's all about how you manage you test code. Selenium itself is not thread safe, you need to handle that in your code. Please follow up with questions to the selenium-users Google group
