### ISSUE TITLE
Switching between Log/Reference/UI-element/Rollup to use native Firefox tabs

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium#2646]
Say you're investigating a long log in Selenium IDE. You find the relevant part. You locate the command in the test case. You want to see target or value in detail, so you click at the command. That will switch to Reference tab.

When you switch back to Log tab, your position is gone.

A solution is to use native Firefox tab elements. See https://github.com/SeLite/SeLite/commit/c0d4ae7f223ef483ab456632d92440c906b2d621. I'm willing to provide a pull request.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
