### ISSUE TITLE
UnreachableBrowserException after completing the execution of @Test and @AfterTest. 

### ISSUE THREAD

**Issue by amodmahajan2016** [SeleniumHQ/selenium#2651]
## Meta -
OS:  Windows 10

Selenium Version:  3.0 Beta2

Browser:  Firefox 48.0.1

Browser Version:  48.0.1

## Actual Behavior -[Child 12164] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2046
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.071 sec <<< FAILURE!
afterTest(MavenDemo.MavenEx)  Time elapsed: 11.691 sec  <<< FAILURE!
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: '31c43c8', time: '2016-08-02 21:57:56 -0700'
System info: host: 'DESKTOP-G2E94QN', ip: '172.16.2.152', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160817112116, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 72bac1b6-1b15-42f6-aec9-604660ccd2ee
	at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:188)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID(UnixProcess.java:222)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$300(UnixProcess.java:201)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:132)

**Comment by lukeis** [comment]
For issue with GeckoDriver please log them with Mozilla: https://github.com/mozilla/geckodriver 

Please be sure to include a way to reproduce the issue that includes a test script and url, if you cannot provide a url I suggest creating one with jsfiddle.net
