### ISSUE TITLE
While taking screenshot, only part of the viewport is captured and remaining portion remains white.

### ISSUE THREAD

**Issue by 552366** [SeleniumHQ/selenium#2652]
## Meta -

OS:  Windows 7
Selenium Version:  3.0 (Java - Webdriver)

Browser:   Internet Explorer 11
## Expected Behavior -

Selenium should capture the screenshot gracefully.
## Actual Behavior -

While taking screenshot, only part of the viewport is captured and remaining portion remains white.
But this is intermittent.
## Steps to reproduce -

Take screenshot on any webpage.

**Comment by barancev** [comment]
The issue is not actionable, it contains no reproduction case, just an unfounded statement.
