### ISSUE TITLE
WebDriver Capability 'overlappingCheckDisabled' has no effect on IE & Chrome webdrivers

### ISSUE THREAD

**Issue by stestr82** [SeleniumHQ/selenium#2655]
## Meta -

OS:   Windows 7 - 64 bit

Selenium Version:  selenium-java 2.53.0 

Browser:  
(a) Firefox 45.3.0 (ESR)
(b) Internet Explorer 11.0.9600.18426
(c) Chrome 52.0.2743.116 m
## Expected Behavior -

I have a sample Webpage with two buttons: Button 1 completely overlaps Button 2.
The question of concern is what happens when Button 2 is clicked.

Case 1: By default - as I understand it from the Selenium Java Changelog - WebDriver should throw an WebDriverException, when Button 2 is clicked.
Message: "Element is not clickable at point (x, y). Other element would receive the click"

Case 2: When setting the WebDriver Capability 'overlappingCheckDisabled' to 'true', WebDriver should be able to click Button 2, without throwing an exception.
## Actual Behavior -

(a) Firefox:
works as expected

(b) Chrome & (c) Internet Explorer
Case 1: no Exception is thrown, i.e. Button 2 is clickable although being overlapped
Case 2: works as expected

Conclusion: 
It seems as if the default behavior of both Chrome & IE (unlike Firefox) is to allow for overlapped WebElements to be clicked, i.e.: 'overlappingCheckDisabled=true'
It is not possible to configure the respective web drivers via Capability 'overlappingCheckDisabled=false' not to accept clicks on the elements.

From the Selenkum Changelog, I concluded that the flag "overlappingCheckDisabled" is available for all WebDriver implementations. Was I wrong about this? Is it only available for Firefox?
Or am I setting the capabiltity wrong for IE & Chrome (see Code excerpts below).
## Steps to reproduce -

This is the example website with two overlaying buttons:

`<!DOCTYPE html>`
`<html>`
`<body>`
`<div>`
`<button id=button2 style="position:fixed;margin:2em;width:10px;height:10px" type="button"></button>`
`<button id=button1 style="position:fixed;bottom:0;top:0;width:100px;height:100px" type="button">Button 1</button>`
`</div>`
`</body>`
`</html>`

This is how I set the cabalitities (example for setting the cabalitity in question to 'true' for Firefox), setting it for IEDriver & Chrome the same way.

`DesiredCapabilities capabilities = ...`
`capabilities.setCapability("overlappingCheckDisabled", true);`
`return new FirefoxDriver(capabilities);`

**Comment by lukeis** [comment]
For Chrome, please log this issue with chromedriver:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by stestr82** [comment]
Dear Luke, thank you for taking up this issue so fast!
As requested, I create an issue with chromedriver:
[https://bugs.chromium.org/p/chromedriver/issues/detail?id=1480](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1480)

**Comment by jimevans** [comment]
As an aside, yes, you misinterpreted the information in the change log. The capability is only implemented for Firefox. It can not be easily implemented in IE, due to the native events implementation. Additionally, I would question whether geckodriver will allow this capability to be implemented.

**Comment by jimevans** [comment]
No further comment in over 6 months. Closing.
