### ISSUE TITLE
Add support for switch to (SVG/(X)HTML) object elements

### ISSUE THREAD

**Issue by ComFreek** [SeleniumHQ/selenium#2657]
<sub>This is strongly related to some closed issues at [selenium-google-code-issue-archive#3749](https://github.com/seleniumhq/selenium-google-code-issue-archive), see the end of this post.</sub>
## Meta -
OS:  All affected
Selenium Version: selenium-webdriver 3.0.0-beta2
Browser:  All affected
## Expected Behavior -
There shall be a function to switch to the context of SVG documents embedded in an object tag:
`<object data="file.svg" type="image/svg+xml">SVG not supported!</object>`

Apart from SVG documents, (X)HTML documents can be embedded as well using `type="text/html"`
or `application/xml+xhtml` (as mentioned [here](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3749#issuecomment-192006494)).

## Actual Behavior -
If one workarounds the missing switchTo function via `findElement(By.js(foo))` where foo returns the contentDocument property of an `<object>` DOM object, one gets:

> StaleElementReferenceError: stale element reference: element is not attached to the page document

## Steps to reproduce -
SSCCE: https://gist.github.com/ComFreek/e62e02d84165079a90cbd3bc97ad14ca

It was tested with

- Windows 10 64-bit
- selenium-webdriver 3.0.0-beta2 (NPM)
- Chrome 52.0.2743.116 m (64-bit)

## Related issues
- https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3749 - Never received a response
- https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4647 - Was denied in 2012. Have there been any fundamental changes which would allow a reconsideration?

**Comment by lukeis** [comment]
This sort of issue needs to be brought up with the W3C WebDriver spec -
https://w3c.github.io/webdriver/webdriver-spec.html

I would recommend logging a spec bug against it. From this project's perspective now we implement the W3C spec (or at least are on the path to doing so). If you want any browser interop with this feature it will need to be defined there. So, I'm going to close this issue until something gets defined on the spec level that we can implement.

**Comment by ComFreek** [comment]
I've filed an issue there. For future reference: https://www.w3.org/Bugs/Public/show_bug.cgi?id=29792
