### ISSUE TITLE
SendKeys not working

### ISSUE THREAD

**Issue by sivhaga** [SeleniumHQ/selenium#2658]
package FirstPackage;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;

public class Login {

	/**
	 * @param args
	 * @throws InterruptedException 
	 */
	public static void main(String[] args) throws InterruptedException {
		
		
		// TODO Auto-generated method stub
		System.setProperty("webdriver.chrome.driver", "C:\\Softwares for Selenium\\chromedriver.exe");
		WebDriver obj = new ChromeDriver();
		
		obj.get("https://www.sivhaga.co.za");
		obj.findElement(By.name("userId")).sendKeys("peter");
	}
}

I am getting the following error message and not sure what might be wrong:
Exception in thread "main" org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"name","selector":"userId"}
  (Session info: chrome=52.0.2743.116)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 47 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: '24088JNBITD701L', ip: '10.18.3.244', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129), userDataDir=C:\Users\sa93546\AppData\Local\Temp\scoped_dir7716_6696}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=52.0.2743.116, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 508b6b2375dc9559588a1945346969e3
*** Element info: {Using=name, value=userId}

**Comment by lukeis** [comment]
The error is pretty obvious: "Unable to locate element:"

Your locator doesn't work... and since I'm unable to resolve that domain no one here can help you further. Feel free to follow up with questions about webdriver on the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by sivhaga** [comment]
Hi Luke,


Locator does work because when using other site like facebook it is able to identify "email" element and why have you closed this  issue?

Regards

Sivhaga Peter
Cell: 0723804248






________________________________
