### ISSUE TITLE
Python: Error occurs when running WebDriver with Desired Capabilites ['marionette'] = True

### ISSUE THREAD

**Issue by arosszay** [SeleniumHQ/selenium#2660]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0b2 (python bindings)

Selenium Standalone Server Version: selenium-server-standalone-3.0.0-beta2.jar

Python Version: 3.5.1

Browser:  Ha, I feel like I've installed them all, not sure what else I can do. Here's the list that I installed and the order in which I installed:
- Firefox
- Firefox Dev Edition
- Firefox Beta

Browser Version:
Firefox = After installing Firefox Beta, the version number of this browser is no longer available (not sure why this browser disappeared). The version that was present immediatly prior to the Firefox Beta install = 46.0.1

Firefox Beta = 49.0b6

Firefox Dev Edition = 50.0a2 (2016-08-24)

## Expected Behavior -
After hitting run or debug in my Automation project in my PyCharm IDE, my tests should run successfully as they did prior to upgrading Selenium to use capabilities['marionette'] = True. 

Firefox should launch, the tests should run, and after the suite is finished, Firefox should close down.

## Actual Behavior -
The following error occurs:

> selenium.common.exceptions.WebDriverException: Message: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
E       Stacktrace:
E           at com.google.common.base.Preconditions.checkState (Preconditions.java:199)
E           at org.openqa.selenium.remote.service.DriverService.findExecutable (DriverService.java:109)
E           at org.openqa.selenium.firefox.GeckoDriverService.access$100 (GeckoDriverService.java:38)
E           at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable (GeckoDriverService.java:91)
E           at org.openqa.selenium.remote.service.DriverService$Builder.build (DriverService.java:296)
E           at org.openqa.selenium.firefox.MarionetteDriver.setupService (MarionetteDriver.java:91)
E           at org.openqa.selenium.firefox.MarionetteDriver.<init> (MarionetteDriver.java:69)
E           at org.openqa.selenium.firefox.MarionetteDriver.<init> (MarionetteDriver.java:47)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (None:-2)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance (None:-1)
E           at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (None:-1)
E           at java.lang.reflect.Constructor.newInstance (None:-1)
E           at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:90)
E           at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:66)
E           at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60)
E           at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222)
E           at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:209)
E           at java.util.concurrent.FutureTask.run (None:-1)
E           at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
E           at java.lang.Thread.run (None:-1)

## Steps to reproduce -
Here's my code that launches the browser. Am I doing something wrong in the code here, or did I find a bug?

````python
    import os
    from selenium.webdriver.remote.webdriver import WebDriver
    from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
    from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

    class Browser(metaclass=Singleton):
        """Encapsulates Selenium functionality regarding the web browser itself. Launching, Quiting, etc."""
        def __init__(self):
            self.driver = Browser.create_browser(self)

        def create_browser(self):
            """Creates and returns a web browser 'driver' object.

            This method launches a browser and creates the connections to remotely control it using Selenium.
            """
            os.environ["webdriver.gecko.driver"] = "C:\\Users\My_User\Downloads\Installs\geckodriver-v0.9.0-win64\wires.exe"

            capabilities = DesiredCapabilities.FIREFOX.copy()
            capabilities['platform'] = "WIN10"
            capabilities['marionette'] = True
            capabilities['binary'] = "C:\Program Files (x86)\Firefox Developer Edition\\firefox.exe"

            ff_profile_dir = "C:\\Users\My_User\PycharmProjects\Automation\FirefoxProfile"
            ff_profile = FirefoxProfile(profile_directory=ff_profile_dir)

            driver = WebDriver(command_executor='http://127.0.0.1:4444/wd/hub',
                               desired_capabilities=capabilities,
                               browser_profile=ff_profile)

            driver.implicitly_wait(30)
            return driver

**Comment by lukeis** [comment]
Did you read the error message? It tells you what to do. 

Just like chromedriver, with Firefox you need to download a separate binary

**Comment by arosszay** [comment]
@lukeis , yes, I did read the error message.

First let's make sure we are talking about the same message. The error message that I've read is this one:

> selenium.common.exceptions.WebDriverException: Message: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

Now that I have confirmed that I have read the error message, I must ask, have you read my bug report? I stated in there that I am using Selenium Version: 3.0.0b2 (python bindings). As far as I understand those are the "separate binary" files you are referring to. Can you please clarify what you think I'm doing wrong?

Additional Info: I have only ever used Selenium with Firefox. I have zero experience with the chromedriver or other ones.

**Comment by lukeis** [comment]
So, with future versions of FirefoxDriver you are now required to download and put on the system path (or provide the path via environment variable) to "geckodriver". The executable that you download from the link in the exception message.

So in total you need 3 things for running against Firefox with python selenium bindings. 1) Firefox (you've got that). 2) selenium-webdriver pip package (looks like you got that too) 3) GeckoDriver (this is what you still need to download)

**Comment by arosszay** [comment]
@lukeis , so I thought I did all that.

I have the following line added to my system path (I did this through the "Environment Variable..." menu from the Windows 10 System Properties menu, which is accessed through Control Panel):

> C:\Users\My_User\Downloads\Installs\geckodriver-v0.9.0-win64\wires.exe

Additionally, you can see that in my steps to reproduce, I have the following line, which, to my novice understanding, should programmatically add the geckodriver to the path:
```python
os.environ["webdriver.gecko.driver"] = "C:\\Users\My_User\Downloads\Installs\geckodriver-v0.9.0-win64\wires.exe"
```

I tried to run my tests, with the following combinations with no luck:
- just the path being added manually via Control Panel
- just the path being added programmatically via my Automation framework
- the path being added both ways, manually as well as programmatically, at the same time

I read that I needed to rename the file to "wires.exe", are you saying that this should now be renamed to "geckodriver.exe"? I am still confused as to what I'm doing wrong. If nothing, I may have found a legitimate bug. What do you think?
