### ISSUE TITLE
Cached proxy credentials

### ISSUE THREAD

**Issue by Ekultek** [SeleniumHQ/selenium#2662]
## Meta -
OS:  Windows 7

Selenium Version:  3.0.0.beta2.1

Browser:  Firefox Developer Edition

Browser Version:  50.0a2 (2016-08-24) (64 bit) 

## Expected Behavior - 
Use a proxy authentication such as cached credentials via C#
```
var webProxy = new WebProxy(WebRequest.DefaultWebProxy.GetProxy(new Uri({TheURLoftheService})));
webProxy.Credentials = CredentialCache.DefaultCredentials;
webProxy.UseDefaultCredentials = true;
service.Proxy = webProxy;
```

## Actual Behavior - 
Won't authenticate my proxy, proxy is script based, doesn't contain username or password.

## Steps to reproduce - 
Try to authenticate a script based proxy that has no username or password.

## Misc -
The above code will grab cached credentials from the proxy, and allow you to run through the proxy without actually inputting the information.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
