### ISSUE TITLE
Enabling javascript when interacting with Selenium to Google Translate website fails

### ISSUE THREAD

**Issue by davide1995** [SeleniumHQ/selenium#2665]
## Meta -
OS:  Mac OS X 10.11.6

Selenium Version:  3 beta (driver)

Browser:  All, Java language

Browser Version:  All

## Expected Behavior -
No exception must be reported

## Actual Behavior -
Exception:
`Caused by: java.lang.RuntimeException: com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot delete property "1" of undefined (https://translate.google.it/translate/releases/twsfe_w_20160822_RC00/r/js/desktop_module_main.js#16)`

## Steps to reproduce -
Simply try the following code:
```
WebDriver driver = new HtmlUnitDriver(true);
driver.get("https://translate.google.it");
```

**Comment by lukeis** [comment]
This is likely due to a bug in HtmlUnit's JavaScript parser. Please log a bug with the HtmlUnit project

**Comment by davide1995** [comment]
Thanks for your response. I will report the bug into HtmlUnit Project

**Comment by lukeis** [comment]
Also, just released htmlunit-driver 2.23 today, try with that first (uses 2.23 of htmlunit, the latest release too)

**Comment by davide1995** [comment]
Where can I find the standalone version? Because in this link https://sourceforge.net/projects/htmlunit/ seems that the class HtmlUnitDriver and WebDriver doesn't exist anymore

**Comment by lukeis** [comment]
HtmlUnitDriver has never been in htmlunit itself... it's here now:
https://github.com/SeleniumHQ/htmlunit-driver
