### ISSUE TITLE
NoSuchWindowError: Unable to get browser

### ISSUE THREAD

**Issue by KingAngus** [SeleniumHQ/selenium#2670]
## Meta -
OS:  

Selenium Version:  

Browser:  

## Expected Behavior -
"use strict"

const webDriver=require("selenium-webdriver"),
	fs=require("fs"),
	mkdirp=require("mkdirp");
let	driver=new webDriver.Builder()
				.withCapabilities(webDriver.Capabilities.ie())
				.build();
let htmlString="";
let url=process.argv[2];
let loopFlag=true;
mkdirp.sync("./html/");
setTimeout(function(){
	start();
},3000);
function start(){
	driver.get(url)
		.then(function(){
			setTimeout(function(){
				insertJS();
			});
		});
}

function insertJS(){
	driver.executeScript(function(){
		if(window.data){
			document.title="已经注入";
			if(window.data=="king"){
				return window.data;
			}else{
				var d=window.data;
				window.data="king";
				return d;
			}
			
		}else{
			document.title="未注入";
			window.copyTimes=0;
			window.data="king";
			document.onkeydown=function(event){ 
				var e = event || window.event || arguments.callee.caller.arguments[0]; 
				if(e && e.keyCode==119){//按F8
					window.data=document.documentElement.outerHTML;
				}
			};
			document.title="已经注入";
			return "new";
		}
	})
	.then(function(dataString){
		if(dataString=="king"){
			console.log("网页无刷新且无数据");
			/* if(loopFlag){
				loopFlag=false;
				setTimeout(function(){
					loop();
				});
			} */
			setTimeout(function(){
				insertJS();
			},3000);
		}else if(dataString=="new"){
			console.log("新网页");
			
			setTimeout(function(){
				insertJS();
			},3000);
		}else{
			console.log("网页无刷新且有数据");
			driver.takeScreenshot()
				.then(function(data){
					let base64Data=data.replace(/^data:image\/png;base64,/,"");
					fs.writeFile("./html/"+Date.now()+".png", base64Data, 'base64', function(err){
						if(err){
							console.log(err);
						}else{
							console.log("截图成功");
						}
					});
				})
				.then(function(){
					fs.writeFileSync("./html/"+Date.now()+".html",dataString);
				})
				.then(function(){
					driver.executeScript(function(){
						document.title="保存次数："+(++window.copyTimes)+","+new Date().toLocaleString();
					});
				})
				.then(function(){
					setTimeout(function(){
						insertJS();
					},3000);
				});
			/* fs.writeFileSync("./html/"+Date.now()+".html",dataString);
			driver.executeScript(function(){
				document.title="保存次数："+(++window.copyTimes)+","+new Date().toLocaleString();
			}); */
			/* setTimeout(function(){
				insertJS();
			},3000); */
		}
	});
}
## Actual Behavior -
NoSuchWindowError: Unable to get browser
    at WebDriverError (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\error.js:27:10)
    at NoSuchWindowError (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\error.js:192:10)
    at Object.checkLegacyResponse (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\error.js:505:15)
    at parseHttpResponse (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\http.js:396:13)
    at C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\http.js:328:11
    at process._tickCallback (node.js:369:9)
From: Task: WebDriver.executeScript()
    at Driver.schedule (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:414:17)
    at Driver.executeScript (C:\Users\king\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:563:16)
    at insertJS (C:\Users\king\Desktop\IEBrowser.js:95:9)
    at null._onTimeout (C:\Users\king\Desktop\IEBrowser.js:20:5)
    at Timer.listOnTimeout (timers.js:92:15)

help please!

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
