### ISSUE TITLE
SEC_ERROR_UNKNOWN_ISSUER error in 3.0.0 beta2

### ISSUE THREAD

**Issue by Takkaiscool** [SeleniumHQ/selenium#2671]
## Meta -
OS:  Windows7

Selenium Version:  3.0.0 Beta2

Browser:  Firefox V 

Browser Version:  48.0.2

## Steps to reproduce -
package test;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.internal.ProfilesIni;

public class T1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver", ".\\Driver\\geckodriver.exe");
		/*DesiredCapabilities cap=DesiredCapabilities.firefox();
		cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);*/
		/*FirefoxProfile pro=new FirefoxProfile();
		pro.setAcceptUntrustedCertificates(true);
		pro.setAssumeUntrustedCertificateIssuer(false);*/
		ProfilesIni prof=new ProfilesIni();
		FirefoxProfile pro=prof.getProfile("Selenium");
		pro.setAcceptUntrustedCertificates(true);
		pro.setAssumeUntrustedCertificateIssuer(true);
		pro.setPreference("setAcceptUntrustedCertificates","true");
		pro.setPreference("setAssumeUntrustedCertificateIssuer","false");
		WebDriver driver=new FirefoxDriver(pro);
		
		driver.get("Use SSL Certificate error website");
		
	}

}

**Comment by mohitora** [comment]
I am also facing the same issue with Linux and Windows 7

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by sakshisingla** [comment]
Hi,

I am facing same issue with Selenium-java 2.53.1 and firefox47.0.1.

Is there any solution found?

Thanks,
Sakshi Singla
