### ISSUE TITLE
UnreachableBrowserException on using driver.quit for Firefox 48.0.2 & selenium-java-3.0.0-beta2

### ISSUE THREAD

**Issue by saladisathish** [SeleniumHQ/selenium#2674]
## Meta -
OS:  
Windows 7
Selenium Version:  
selenium-java-3.0.0-beta2
Browser:  
Firefox 48.0.2

Browser Version:  
48.0.2 (64-bit) 

## Expected Behavior -
driver.quit() should quit the browser instead unreachableBrowserException is displayed
## Actual Behavior -
driver.quit() should quit the browser instead unreachableBrowserException is displayed
## Steps to reproduce -

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TesterFile {

	public static WebDriver wd;
	public static void main(String[] args) {
		
		System.setProperty("webdriver.gecko.driver","C:\\Users\\<User>\\tools\\geckodriver.exe");
		wd = new FirefoxDriver();
		wd.get("http://www.google.com");
		
		wd.close();
		wd.quit();
	}

}

**Comment by lukeis** [comment]
works as designed?  calling close first should close the window... since you had only one window, the quit will fail.

If the close is not working, then please log a bug with the geckodriver project.
