### ISSUE TITLE
 _driver.Navigate().GoToUrl("url") lost active window on remote IE

### ISSUE THREAD

**Issue by aravindmungara** [SeleniumHQ/selenium#2681]
## Meta -
OS:  
Windows 2012R2
Selenium Version:  2.5.2

Browser:  IE 11

Browser Version:  
IE 11

## Expected Behavior -
Remote web driver should not lost active window after navigate to url.
remote driver SHOULD NOT lost its active window and when trying to find  a element it should not throw window closed exception
## Actual Behavior -
remote driver losing active window after calling navigate go to url method. getting no window closed exception. 
## Steps to reproduce -
I did set up Selenium grid  and running selenium test  on hub. 
          
          DesiredCapabilities caps = DesiredCapabilities.InternetExplorer();
            caps.SetCapability("ignoreZoomSetting", true);
            caps.SetCapability("nativeEvents", true);
            caps.SetCapability("allow-blocked-content", true);
            caps.SetCapability("disable-popup-blocking", true);
            caps.SetCapability("allowBlockedContent", true);
            caps.SetCapability("ignoreProtectedModeSettings", true);
            caps.SetCapability("ie.browserCommandLineSwitches", true);
            caps.SetCapability("ie.ensureCleanSession", true);
            caps.SetCapability("ie.browserCommandLineSwitches", true);
             _driver = new RemoteWebDriver(new Uri(_serverUri), caps, TimeSpan.FromSeconds(1600));
             _driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(1600));
                _driver.Navigate().GoToUrl("hhttps://www.google.com/");
  _driver.FindElement(By.Id("lst-ib"));
throwing following
Unable to find element on closed window (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'

**Comment by jimevans** [comment]
You've set the `ignoreProtectedModeSettings` capability to `true`. If you haven't correctly set the IE Protected Mode settings for the browser, this is exactly the type of behavior I would expect to see. Also, when using the .NET bindings, please use the `InternetExplorerOptions` class to set the capabilities you wish to set. If you want to use the options object with `RemoteWebDriver`, use the `.ToCapabilities()` method to create the `ICapabilities` object that the constructor requires.
