### ISSUE TITLE
js: impossible to run parallel testing with built-in mocha on cloud providers such as browserstack

### ISSUE THREAD

**Issue by vitalets** [SeleniumHQ/selenium#2684]
Currently [javascript/node/selenium-webdriver/testing/index.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/testing/index.js#L70) always uses default controlFlow:

``` js
var flow = promise.controlFlow();
```

When I tried to run my tests on browserstack in parallel I've adopted [parallel flows example](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/parallel_flows.js) as following:

``` js
var webdriver = require('selenium-webdriver'),
  By = webdriver.By,
  until = webdriver.until,
  test = require('selenium-webdriver/testing');

var caps = [
  {
    'browserName' : 'chrome',
    'os' : 'Windows',
    'os_version' : '7',
  },
  {
    'browserName' : 'firefox',
    'os' : 'Windows',
    'os_version' : '7',
  }
];

for (var i = 0; i < caps.length; i++) {
  (function(i) {

    test.describe('Google Search (selenium compatible)'+i, function () {
      var driver;

      test.before(function () {

        var flow = new webdriver.promise.ControlFlow()
          .on('uncaughtException', function (e) {
            console.log('uncaughtException in flow %d: %s', i, e);
          });

        var capabilities = Object.assign({}, {
          'browserstack.user': '<user>',
          'browserstack.key': '<key>',
          'resolution': '1024x768',
        }, caps[i]);

        driver = new webdriver.Builder()
          .usingServer('http://hub-cloud.browserstack.com/wd/hub')
          .withCapabilities(capabilities)
          .setControlFlow(flow)  // Comment out this line to see the difference.
          .build();

      });

      test.it('should append query to title'+i, function() {
        driver.get('http://www.google.com');
        driver.findElement(By.name('q')).sendKeys('webdriver');
        driver.findElement(By.name('btnG')).click();
        driver.wait(until.titleContains('webdriver'), 2000);
      });

      test.after(function () {
        driver.quit();
      });
    });

  })(i);
}
```

But when I run it tests are not actually executed and stdout instantly shows:

```
  Google Search (selenium compatible)0
    ✓ should append query to title0

  Google Search (selenium compatible)1
    ✓ should append query to title1


  2 passing (60ms)
```

If I comment setting control flow for driver - tests are executed but in serial manner:

``` js
//  .setControlFlow(flow)  // Comment out this line to see the difference.
```

Maybe we should pass `flow` somehow into `test` instance before wrapping mocha globals.
Are there any plans for supporting cloud services?

Thx!

**Comment by jleyba** [comment]
Mocha doesn't support running tests in parallel. There are some packages that help with this, like [mocha-parallel-tests](https://www.npmjs.com/package/mocha-parallel-tests), but the `selenium-webdriver/testing` module won't work out-of-the-box for the issues you've already described.

`selenium-webdriver/testing` is only provided to ease ramp up speed, it's not meant to define a full-featured test framework. If you want to send a pull request adding support for parallel flows, I'll review it, but I won't be taking any action on this.

As for how to go about handling this, take a look at the [suite](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/test/index.js#L212) function used for `selenium-webdriver`'s own tests. Maybe you could do something similar with an option to use a unique flow per test.

**Comment by vitalets** [comment]
hi @jleyba thanks for reply!
I've discussed with [mocha-parallel-tests](https://www.npmjs.com/package/mocha-parallel-tests) author - the lib runs each `describe` in parallel and there is issue to support `selenium-webdriver/testing`:
https://github.com/mmotkina/mocha-parallel-tests/issues/47

It would be pretty solution, but requires integration with selenium wrappers over mocha.

Actually what I need is even less - I'd like to run the whole suite on win and osx in parallel. The same thing as webdriverio does with [multiremote feature](http://webdriver.io/guide/usage/multiremote.html).

> but the selenium-webdriver/testing module won't work out-of-the-box for the issues you've already described

why not? 
Having possibility to run scenarios in parallel via passing custom flow and not including this in running tests (what most people would like early or late) may be unconvenient for users. 
Our case: we already have written a number of tests using `selenium-webdriver` syntax and want to grow and run tests in browserstack parallel. But we blocked with that feature and don't want to move to webdriverio as it has own syntax.

I can try to investigate and make a pr on `selenium-webdriver/testing` to support custom flow but I'd like to know what is you future vision of `selenium-webdriver/testing`:
- if it is just quick start - it's better to write some plugin
- if it is planned to grow - it's better to have that feature buit-in.

**Comment by jleyba** [comment]
The promise manager has been removed and so have the wrappers for mocha hooks in `selenium-webdriver/testing`.

You should be able to use mocha, jasmine, or any other framework that supports promise (or async/await)

**Comment by timm-gs** [comment]
@jleyba In which version has it been removed?

From https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md is looks like this is only in v4.0.0-dev / scheduled for 4.0.

**Comment by jleyba** [comment]
Yes, that's correct. It will be in 4.0

**Comment by Kosmonaft** [comment]
Can anyone share an example of the parallel test for mocha in browserstack?
I found this repository: https://github.com/browserstack/mocha-browserstack
but the example is throwing a lot of errors.
