### ISSUE TITLE
Wrong element receiving .click() call

### ISSUE THREAD

**Issue by ejahns** [SeleniumHQ/selenium#2687]
## Meta -
OS:  OSX El Capitan

Selenium Version:  3.0.0-beta2

Browser:  Firefox

Browser Version:  46.0.1

## Expected Behavior -
In Selenium 2.53.1, attempting to click an element which is covered by another element would throw an exception: "org.openqa.selenium.WebDriverException: Element is not clickable at point.... Other element would receive the click: "

## Actual Behavior -
Attempting to click an element covered by another element results in the covering element being clicked and no exception is thrown.
## Steps to reproduce - 
Create a new instance of FirefoxDriver and navigate to "http://www.w3schools.com/css/css_navbar.asp":
`System.setProperty("webdriver.gecko.driver", "geckodriver");
WebDriver driver = new FirefoxDriver();
driver.get("http://www.w3schools.com/css/css_navbar.asp");`

Then manually scroll the page down so that the "<< Previous" link is behind the top navigation bar. Calling .click() on the "Previous" link results in the "JAVASCRIPT" link in the navigation bar being clicked:

`driver.findElement(By.partialLinkText("Previous")).click();`

**Comment by lukeis** [comment]
This is expected behavior. If the element you are attempting to click has another element covering it at the time, how is an end user expected to click it? This is why this check is done and this exception is thrown.

**Comment by pennycurich** [comment]
Luke, please re-read and re-open this ticket.  The original ticket is stating that the expected behavior is *not* occurring.

**Comment by lukeis** [comment]
@pennycurich just re-read the issue... and it's with geckodriver / firefox.

@ejahns Please log geckodriver issues with mozilla:
https://github.com/mozilla/geckodriver
