### ISSUE TITLE
Python, WebDriver, Firefox: option.click() call within Select(webelement).select_by_value(value) method does NOT do anything

### ISSUE THREAD

**Issue by arosszay** [SeleniumHQ/selenium#2695]
## Meta -
**OS:**  Windows 10
**Selenium Version:**  3.0.0b2 _(Note: I don't recall exactly the previous version number, but with 2.53 or whatever it was before the Selenium 3 beta release started, this bug did NOT occur for me, everything worked great.)_

**Browser:**  Firefox
**Browser Version:**  I've tried two versions, both resulting in same behavior: 46.0.1 and 48.0.2

## Expected Behavior -
The option contained within a select element with value = X should be selected on the screen when the method Select(webelement).select_by_value(X) is executed.

## Actual Behavior -
No selection occurs.  When debugging, I found that the click() that is called in the following private method that is defined in Selenium's Select Class doesn't actually select anything from the select element. No exceptions occur, the code just keeps going on assuming that the click() worked.
```
def _setSelected(self, option):
        if not option.is_selected():
            option.click()
```

## Steps to reproduce -
Use the following HTML to try and select the "Demo Site" option with value='79'
```
<select id="ctl00_Login_ddlOrganizationClient" class="modalDropdown" name="ctl00$Login$ddlOrganizationClient">
<option value="-1" selected="selected">Select one...</option>
<option value="79">Demo Site</option>
</select>
```

Here's my wrapper for the Select method written in Python:
```python
from Selenium.browser import Browser
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait as Wait
from selenium.webdriver.support.select import Select
from enum import Enum

def select(self, element, how='value', value=None):
        """Wrapper around Selenium Select class members.

        Selects an item from a dropDownList

        Parameters:
            element -- the dropDownList element to select from: type = WebElement
            how -- the HTML attribute used to identify the desired item in the dropDownList, can be 'value' or 'index'
                   (default='value'): type = str
            value -- the value of the HTML attribute used to identify the desired item in the dropDownList: type = str
        """
        if how == 'value':
            Select(element).select_by_value(value)
        elif how == 'index':
            Select(element).select_by_index(value)
        else:
            print("The value supplied for 'how' to select from a dropDownList is incorrect.")
```

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by arosszay** [comment]
I figured out the issue. Here's the problem. When searching for information about this whole transition to Selenium 3 online...specifically with the Firefox WebDriver....there's all sorts of conflicting information online. Even right here in the comments where Issues are being filed. I found multiple places stating that only Firefox version 48+ is the only version that works with GeckoDriver.

Based on my direct experience I can verify for the whole team right now that is NOT true. **Saying that geckodriver works with Firefox 48+ is a lie.**

What I did find out to be true though, was when I upgraded to the BETA version of Firefox...bringing me up to 49.0b8...that's what made things work. Specifically I'm calling out this bug that I filed right here. As soon as I upgraded to the BETA version of Firefox...this bug went away.

As a professional QA person that depends daily on Selenium...I hope that my feedback is valuable to the Selenium team and your efforts at helping the rest of us. Thank you!!

**Comment by cgoldberg** [comment]
> I hope that my feedback is valuable

TBH, I found your feedback to be rather derogatory and condescending.

**Comment by AutomatedTester** [comment]
> Saying that geckodriver works with Firefox 48+ is a lie.

Demonstrably not true. Just because you hit a bug doesnt mean it doesnt work for everything. As a QA engineer you would know that otherwise you would never ship stuff.

> I hope that my feedback is valuable to the Selenium team and your efforts at helping the rest of us

Your bug reports have been quite poor to be honest. As a professional QA person you should give steps that are reproducible from the start. Something that has been lacking. 

I suggest in the future you remove emotive language from the bugs as it just comes across as condescending, as has been mentioned, opening you up to comments like this.

**Comment by arosszay** [comment]
@cgoldberg @AutomatedTester , my apologies for that. I never conceived the thought that a person could find the truth of another human being's experience to be derogatory and condescending.

> Your bug reports have been quite poor to be honest. As a professional QA person you should give steps that are reproducible from the start. Something that has been lacking. 

If you are going to attack me like that, please at least provide evidence for your claim, so that I can address what you are specifically referring to. The way I read my reports, they do accurately and exactly describe the issue I was experiencing. If you sincerely read the bug report, including the previous two reports I filed, you should have at least found my steps to reproduce worthy of a follow-up question. At least that is generally my running assumption. As a professional QA person, knowing that communication is almost impossible to get 100% correct in translation to another human mind, when I read something in a bug report that is unclear I take it upon myself as my duty and responsibility to get clarity about the issue from the bug reporter. No ego about it. I just do my job.

If you asked me what my intentions were for writing my feedback in the way I did, I would have told you I was trying to be a participant in the open source community...but one who is very far removed from the core of it....so, just giving an off-hand remark about the difficulties in transitioning to the new geckodriver due to all the conflicting information available online. I was hoping in my heart that someone might pick up on the feedback and maybe generate an idea in their mind that can help someone like me. I don't know. I was just sharing my experience. Pretty innocent stuff the way I see it.

Lastly, and most importantly. To suggest to someone that they should remove their human emotion when communicating to another human being is what the term dehumanizing means. I rather not comment further on such a despicable suggestion.

**Comment by cgoldberg** [comment]
> To suggest to someone that they should remove their human emotion
> when communicating to another human being is what the term
> dehumanizing means. I rather not comment further on such a 
> despicable suggestion.

@arosszay 
I totally disagree... When reporting a bug, you should drop all human emotion, period.  It's not despicable at all to suggest that.  You want to convey the most precise set of steps to reproduce an issue and give any related technical details.  Injecting your emotions into the bug report just adds noise.  Bug reports are not the place for gripes or whining (or accusations of lying).

> Pretty innocent stuff the way I see it.

asserting that the maintainers are feeding you "lies" is paranoid and delusional, and is far from innocent.

>  I was trying to be a participant in the open source community

perhaps you should rethink your approach before engaging other projects.

**Comment by nirvdrum** [comment]
If the technical matter being reported on has been addressed, I suggest all parties just drop the issue. Both sides have said their piece.
