### ISSUE TITLE
The location of geckodriver.log in python implementation should to be customized by user.

### ISSUE THREAD

**Issue by triostones** [SeleniumHQ/selenium#2698]
## Meta -

OS:  Ubuntu 16.04

Selenium Version:  2.53.6

Browser:  Mozilla Firefox 49.0

Browser Version:  

## Expected Behavior -

The location of `geckodriver.log` should to be customized by user.
## Actual Behavior -

The location of `geckodriver.log`  is settled to current workspace, users can not modify it.
Seeing [L 76](https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/py/selenium/webdriver/firefox/webdriver.py#L76) in `webdriver.py`, it do not pass a file path to `Service` class when init the instance.

**Comment by AutomatedTester** [comment]
I agree and will get this sorted.

**Comment by barancev** [comment]
Fixed by commit 40a5d80e995071fb85f86e70e15e4b96cc692d11
