### ISSUE TITLE
Webdriver Sendkeys not inputting all spaces

### ISSUE THREAD

**Issue by angelmartin54** [SeleniumHQ/selenium#2702]
## Meta -
OS:  Windows 7

Selenium Version:  Java	3.0.0-beta2

Browser:  Chrome 

Browser Version:  Version 52.0.2743.116 m

## Expected Behavior -
 i am trying to type an address into a text box
EX. trying to imput "9910 sw 73rd st"

## Actual Behavior -
the actual behavior is random rearly does it actually input the actual address
what usally ends up happenig the test will eat some of the spaces resulting in something like "9910sw 73rd st" casusing my test to fail since im unable to validate that address.

## Steps to reproduce -
Below i have added the code used in test. you cant run it since this is an internal application but i beleave this is an issue with snedkeys or the way im using it has anyone else expecienced this issue.

all help and comments are appreciated thanks in advance,

@Test
	public void addressValidation() throws Exception {
			login();
			driver.findElement(
					By.cssSelector("#answer_hub > div:nth-child(1) > span > input.ic_field.h24.address_reset"))
					.sendKeys("9910 sw 73rd st");
			driver.findElement(By.cssSelector("#answer_hub > div:nth-child(1) > span > input.submit.h32.button.blue"))
					.click();
			Thread.sleep(3000);
			driver.findElement(By.cssSelector(
					"#answer_hub > div:nth-child(1) > span > input.ic_valid.button_icon.visibility_visible"))
					.isDisplayed();
		}
	}

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
