### ISSUE TITLE
Running `test_javascript` tests fails due to attempting to use the old WebDriver with Firefox 48

### ISSUE THREAD

**Issue by Standard8** [SeleniumHQ/selenium#2720]
## Meta -
OS:  OS X

Selenium Version:  Latest master (73b4d1c659d12e5012c92a009ab90f2dafedf7b9)
Browser:  Firefox 48 installed in /Applications/Firefox.app/

Browser Version:  48.0.1

## Expected Behavior -
`./go test_javascript` should pass after running tests.

## Actual Behavior -
`./go test_javascript` does a few things, and then hangs when Firefox starts up. Looking in Tools -> Add-ons shows that the old WebDriver extensions is installed but disabled due to not being signed.

## Steps to reproduce -

* Check out latest source
* Run `./go clean test_javascript`

**Comment by lukeis** [comment]
this appears to be "working" now... at least it doesn't install the extension and launches firefox with geckodriver.

Also know to run those tests you first need to run `./go calcdeps`
