### ISSUE TITLE
Settings supplied via json are not applied when starting hub & node using selenium-server-standalone-3.0.0-beta2.jar

### ISSUE THREAD

**Issue by nocomply78** [SeleniumHQ/selenium#2721]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0-beta2

Browser:  N/A

Browser Version:  

## Expected Behavior -
Settings from hubConfig.json & nodeConfig.json are applied when starting selenium-server-standalone as hub or node (the attached hubConfig.json is set to run the hub on port 7777 with timeout:15 & browserTimeout:15, and nodeConfig.json is set to run the node on port 6666 with fairly standard settings)
## Actual Behavior -
The hub runs on port 4444 with default timeouts set and the node on 5555.
There is no mention of the hubConfig.json settings under the 'the final configuration comes from' heading when viewing the Grid Console page
## Steps to reproduce -

1. Unpack the attached example.zip to any location on your machine
2. Run grid-hub.bat
3. Run grid-node.bat
4. Open http://localhost:4444/grid/console?config=true&configDebug=true

## Additional Info -
When swapping out selenium-server-standalone-3.0.0-beta2.jar for the 2.53.1 version (and changing the SELENIUM_VERSION value to 2.53.1 in both batch files), all settings in the json files are applied as expected when starting the hub & node
The same behaviour is also seen when running with selenium-server-standalone-3.0.0-beta1.jar

[example.zip](https://github.com/SeleniumHQ/selenium/files/455622/example.zip)

**Comment by mach6** [comment]
Try again in 3.0.0-beta3. This should be fixed with this commit - https://github.com/SeleniumHQ/selenium/commit/fbc82cdddf3267c11716815fb508bd0365aeb3a6

**Comment by nocomply78** [comment]
Thanks.
Updated to 3.0.0-beta3 and tried again:
However, I couldn't get the node to register using the port specified in the configuration section of nodeConfig.json - I set port to 5557, but it continued to register using the default port 5555

As for the rest, I didn't try _all_ settings, but _can_ confirm that the following updated with the values supplied in hubConfig.json:
debug, host, port, throwOnCapabilityNotPresent, nodePolling, cleanUpCycle, timeout, browserTimeout, maxSession & jettyMaxThreads.
... and the following were updated as per values set in nodeConfig.json:
proxy, maxSession, registerCycle, timeout & hubPort

Reattaching example zip after correcting mistake I made with hubPort in the original example (hub will be on http://localhost:4445 in the new example, node is expected to be registered using port 5557)
[example2.zip](https://github.com/SeleniumHQ/selenium/files/466262/example2.zip)

Would you prefer a separate issue raised for the node port number issue in beta3 and for this issue to be closed?

**Comment by mach6** [comment]
Thanks for the detailed reply. I'll look into today.

**Comment by mach6** [comment]
Confirmed. `port` is broken when specified in a `-nodeConfig` file. I will update this PR when a fix is merged.

**Comment by sandeepjain1987** [comment]
Is the issue #3992 related ? If so, is there a fix?
