### ISSUE TITLE
Chromedriver failed to start in Window Server 2012

### ISSUE THREAD

**Issue by avishek319** [SeleniumHQ/selenium#2722]
After Deploying compiled file on server the chrome driver while starting throws the following exception and stops -

System.InvalidOperationException: unknown error: chrome failed to start (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.2 x86_64) at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at remote_driver_demo.btnSubmit_Click(Object sender, EventArgs e) System.NullReferenceException: Object reference not set to an instance of an object. at remote_driver_demo.btnSubmit_Click(Object sender, EventArgs e)

Following is My C# Code 
`  ChromeOptions options = new ChromeOptions(); `
`      options.BinaryLocation = Server.MapPath(@".\bin");`
`driver = new ChromeDriver(options);`

The code is running on c# IDE on localhost but raises exception if running after deploying on Window Server 2012. 
Same code is running on Window Server 2008

**Comment by lukeis** [comment]
Seems from your exception message that you are running a very old version of chromedriver on that machine. Please try using the latest version. If it continues to fail, then please log your issue with the chromedriver project: 
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by avishek319** [comment]
ok thax
