### ISSUE TITLE
Selenium And Prebid V12 Header Bidding

### ISSUE THREAD

**Issue by pbasin** [SeleniumHQ/selenium#2730]
## Meta -
OS:  W7

Selenium Version:  2.53.1 , 2.53

Browser:  FF 47, FF 43

Browser Version:  

## Steps to reproduce -
 
[Selenium_Prebid.docx](https://github.com/SeleniumHQ/selenium/files/457783/Selenium_Prebid.docx)

**Comment by jleyba** [comment]
Post your steps in a bug report - do not expect us to open a docx file.
