### ISSUE TITLE
The SearchContext of the locator object cannot be null Parameter name: locator

### ISSUE THREAD

**Issue by MartinDudeDude** [SeleniumHQ/selenium#2734]
## Meta -
OS:  
Windows 7.
Selenium Version:  
2.53.1
Browser:  
Issue Seen in both  I.E. 11 and Chrome

Browser Version:  
Chrome 52.0.2743.116 m (64-bit)
I.E 11.0.9600.18426IS

## Actual : They give the following error message

System.ArgumentException : The SearchContext of the locator object cannot be null
Parameter name: locator
	
## Steps to reproduce -

1. Using Visual Studio create a new page object file
2. Write a simple test which uses the page object file and run it (Should run ok)
3. rename the page object file in V.S.
4. Try and run the tests (error message shows as follows)

System.ArgumentException : The SearchContext of the locator object cannot be null
Parameter name: locator

**Comment by lukeis** [comment]
Without the example script provide to reproduce the issue there's nothing one can do here. Please provide example code that demonstrate your issue, when it is provided we can reopen the issue
