### ISSUE TITLE
Attaching file results in a zero sized file

### ISSUE THREAD

**Issue by bizmate** [SeleniumHQ/selenium#2740]
## Meta -
OS:  Linux/Mac OSX 10.11.6

Selenium Version:  
2.53.1 standalone, 2.53.1 grid (docker images), 3 (beta)
Browser:  
Chrome

Browser Version:  
52.0.2743.116 (64-bit)

## Expected Behavior -
file is filled with a non zero sized file, correct file

## Actual Behavior -
File is attached with correct name, type, size

## Steps to reproduce -
Created a GIST with all files.
https://gist.github.com/nickrealdini/c8d0dd301680c2305e41e05ffedcd758

* Behat runs the selenium SendKeys with firefox/chrome. In the details of the GIST you can see the 
- page used/ just a simple page with a file input
- description of all the setup in behat and also a description of what selenium drivers and versions used. We usually use docker containers to run selenium and also tried a standalone version to see the page running.

1 - attach a file to the page
2 - the page should have a correct File object in the file input, with non zero sized value and also trigger the change event on the file element

I hope the description is comprehensive. If I have skipped something pls let me know

**Comment by lukeis** [comment]
Thanks for making a detailed report, unfortunately we don't support Behat here. You'll have to log the issue with them. Also if there's an actual issue with file upload and Chrome, you would log that with the chromedriver project. But I suspect it's an actual issue with Behat.

We could possibly help identify the issue if you were to show the REST api calls made to the selenium server. URL + POST data content.

**Comment by bizmate** [comment]
@lukeis thanks for the reply. are the requests something i can get from selenium logs? I ll look at documentation but maybe i need to run it with some flag for debugging?

**Comment by ddavison** [comment]
you can specify `-log <file>` to the server.  it defaults to STDOUT.
