### ISSUE TITLE
HOVER Issues

### ISSUE THREAD

**Issue by karthikeyanMani** [SeleniumHQ/selenium#2741]
## Meta -

OS:  Windows 7

Selenium Version:  
 3.0.0 Beta, Eclipse ,neon
Browser:  

Internet Explorer
Browser Version:  
11.0.9600
1. I have one web element/Control once i navigate to it it popups the MouseHOver Control.
2. In that Control I have to click on the Control which is listed in Mouseoverpanel.
   However in IE the MouseOVer Control started flickering and unable to click the control in MouseOVerpanel
## Steps to reproduce -

1. I have tried with all possible scenario I am unable to solve this issue.

Note: The same set of code is working fine (i..e Firefox and Chrome)

**Comment by karthikeyanMani** [comment]
Combination which tried to handle mouse over.

First Combination:

WebElement agent = driver.findElement(By.xpath("//*[@id='acContainer']/a"));
Actions action = new Actions(driver);
action.moveToElement(agent).build().perform();

WebElement accord =driver.findElement(By.xpath("//*[@id='tt_acContainer']/div/div[1]/ul[3]/li[3]/a"));
action.moveToElement(accord).build().perform();
action.click().perform();	


---------------------------------------------------------------------------------------------------------------------
Second Combination:


driver.findElement(By.xpath("//*[@id='acContainer']/a")).Click();


WebElement accord =driver.findElement(By.xpath("//*[@id='tt_acContainer']/div/div[1]/ul[3]/li[3]/a"));
Actions action = new Actions(driver);
action.moveToElement(accord).build().perform();
action.click().perform();

**Comment by jimevans** [comment]
Have you tried using the `requireWindowFocus` capability? Or, alternatively, turning persistent hovers off (also a capability).

**Comment by jimevans** [comment]
No answer in 6 months. Closing.
