### ISSUE TITLE
Event triggered by moveToElement incorrectly simulates left mouse button pressed

### ISSUE THREAD

**Issue by petrsimon** [SeleniumHQ/selenium#2746]
## Meta -

OS:  OSX

Selenium Version:  2.53.0
Browser:  Firefox

Browser Version:  44.0

I'm simulating `hover` using `moveToElement`. 
## Expected Behavior -

Event (`mousemove`, `mouseenter`) triggered by `moveToElement` should have the fields `event_.buttons` and `event_.which` set to 0.
## Actual Behavior -

Mentioned fields are set to 1.
## Steps to reproduce -

``` java
Actions action = new Actions(browser);
WebElement we = browser.findElement(By.cssSelector("someselector"));
action.moveToElement(we).perform();
```

**Comment by AutomatedTester** [comment]
This is all handled by Firefox and not by the atoms any more
