### ISSUE TITLE
When is the selenium 3.0.0b3-python release date?

### ISSUE THREAD

**Issue by strokirk** [SeleniumHQ/selenium#2749]
Hello, 

Commit 055325c09d78 fixes a bug that causes the Selenium python library to crash on startup. Is there a planned release date for this version?

Due to the size of this repository it is not feasible for us to install directly from Github.

**Comment by lukeis** [comment]
Soon? :)

We don't track releases as issues here. Feel free to chat with everyone one IRC. 

Also a shallow clone (--depth 1) is a much smaller footprint
