### ISSUE TITLE
RemoteWebDriver uses POST method for Get Active Element

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#2751]
As is shown by the stacktrace in https://github.com/mozilla/geckodriver/issues/223, Selenium uses the POST method when getting the current active element.  It should use GET according to the specification.

I think this is a problem in the RemoteWebDriver, but I’m not sure.

**Comment by mb73** [comment]
I  think I have found the Bug in [the source code of AbstractHttpCommandCodec](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/AbstractHttpCommandCodec.java):

`defineCommand(GET_ACTIVE_ELEMENT, post("/session/:sessionId/element/active"));`
should be 
`defineCommand(GET_ACTIVE_ELEMENT, get("/session/:sessionId/element/active"));`

not?

**Comment by andreastt** [comment]
That looks like it, yes. But it needs to be special cased for when speaking to a W3C conformant remote as not to break backwards compatibility with Selenium remotes.

**Comment by mb73** [comment]
My guess is that the other remotes just take anything, no matter if get or post. So I would suggest to just try it. If all of them are happy with “get”, then simply change it.

**Comment by andreastt** [comment]
I think that’s a bold assumption to make. I’m quite sure chromedriver is explicit about what HTTP methods it listens to, but I’m most willing to be proved wrong on this.

**Comment by mb73** [comment]
Really? It sounds so weird to me to expect someone to “post” for getting some information. However, thanks for the feedback :)

**Comment by andreastt** [comment]
It is weird as you say, because this command doesn’t have any state-altering behaviour. This is incidentally why we’ve rectified it in the specification.

I dug into this and it looks like chromedriver accepts only POST for `/session/{session id}/element/active`: https://cs.chromium.org/chromium/src/chrome/test/chromedriver/server/http_handler.cc?q=http+file:%5Esrc/chrome/test/chromedriver/&sq=package:chromium&dr=CSs&l=214

**Comment by jleyba** [comment]
It's post because it modifies server state. For w3c spec they decided to go
against http recommendations and use get as it's more descriptive of the
action

**Comment by mb73** [comment]
Now I’m curious. Which state is modified by “Get Active Element”?

**Comment by jleyba** [comment]
It's the same as find element: the server has to generate a web element
reference

**Comment by mb73** [comment]
And that reference exists beyond the request? If so: why? Thanks for your patience with me :)

**Comment by jleyba** [comment]
That's how you interact with dom elements with webdriver. You get a web
element reference with an opaque ID generated by the server. Subsequent
commands reference that ID so the server knows what DOM element you are
actually trying to interact with

**Comment by jleyba** [comment]
How does it not alter state? See my previous comments. The server has to
generate a new webelement if it's the first time the "active" element is
retrieved

**Comment by mb73** [comment]
It’s probably because I have no idea about how such a server works, but it sounds like an implementation detail to me if such reference / ID exists in the first place or is generated as a side effect of “Get Active Element”.

**Comment by andreastt** [comment]
To be clear, whether it alters state depends on the implementation. You could imagine an implementation that generates web element UUIDs for all DOM elements when it is under WebDriver control.

Does it alter state in existing implementations? Well the most correct answer is “maybe”. If you ask for the active element and it has not been fetched previously, most drivers will hash it and create a new web element reference as jleyba explains. If it already exists in the set of known web elements it does not alter any state and it is a straight table lookup operation.

However, I’m not sure I entirely agree that generating a web element reference amounts to “modifying server state”. The primitive that is accessed is `document.activeElement`, which is a getter.

**Comment by jleyba** [comment]
Look at it another way: get active element is equivalent to `executeScript("return document.activeElement");` (a POST). You can also use findElement with CSS (also a POST). For HTML, there doesn't even need to be a dedicated command for this (it's probably justified for mobile implementations like appium, but I have separate reservations about mapping WebDriver's API to native applications).

I'm not trying to argue that the w3c should change from GET, just pointing out that the wire protocol's use of POST isn't as off base as has been suggested.

**Comment by andreastt** [comment]
The reason finding an element and executing scripts require POST is because we need to send a body, which is not the case for getting the active element, though.

Of course I’m not arguing that any of this makes sense if you view this with RESTful goggles. I think it’s fair to say it’s an approximation to providing a “RESTish” API. 😄

**Comment by lukeis** [comment]
fixed in java... needs fixing in the other languages as well

**Comment by shs96c** [comment]
This is a w3c spec conformance issue. Moved to the 4.0 milestone

**Comment by mb73** [comment]
I’m confused. For me this is a **blocker**. How can anyone test with Firefox as long as this is not fixed?

**Comment by andreastt** [comment]
@mb73 Do note that the Java bindings were fixed in https://github.com/SeleniumHQ/selenium/commit/ed15c6c2e592301b523a62ce44dc3ccd5615f37e.

**Comment by titusfortner** [comment]
Ruby has been compliant from the beginning, and this is a duplicate: https://github.com/SeleniumHQ/selenium/issues/2555 :)

**Comment by mb73** [comment]
@andreastt Thank you! I’m happy to hear that postponing the issue doesn’t mean a rollback for the Java bindings.

**Comment by jimevans** [comment]
Fixed in .NET in 5e1d455
