### ISSUE TITLE
Please Expose checkedLocator (ie. check)

### ISSUE THREAD

**Issue by machineghost** [SeleniumHQ/selenium#2755]
## Meta -
Version: The Javascript Web Driver
OS:  Irrelevant,but Linux
Selenium Version:  the latest version on NPM
Browser:  Chrome (but that's not relevant)

## Expected Behavior -
I can create my own `until` functions, based off existing ones

## Actual Behavior -
I can't, because the existing ones depend on `elementLocated` (from by.js), and that function isn't exposed (`By.by` is exposed, but `By.checkedLocator` is not).

## Steps to reproduce -
Say you want to use `until.elementLocated`, but that function returns `true` when *any number* of matching elements is found, and you want a version that only returns `true` once `n` elements are found.  This sounds like something trivial (honestly I'm not sure why `until.elementLocated` doesn't just taken an optional argument for this very purpose, and then default it to the value it currently uses, ie. `0`).  However, it's actually impossible without copying chunks of webdriver code in to your own application, because there's no way to get `elementLocated`.

**EDIT**
Just realized the same problem applies to the Condition class from the (internal) webdriver.js.

**Comment by jleyba** [comment]
I don't understand what you're trying to do that requires this to be exposed.

You can easily define your own wait condition:

```javascript
const {By,  until} = require('selenium-webdriver');

function untilAbleToFind(n, locator) {
  return new until.Condition(`to be able to locate ${n} elements`, driver => {
    return driver.findElements(locator).then(elements => {
        return elements.length >= n ? elements : null;
    });
  });
}

driver.wait(untilAbleToFind(3, By.tagName('a')));
```

**Comment by machineghost** [comment]
TypeError: until.Condition is not a constructor

Do you mean the `Condition` from `webdriver.Condition`?

**Comment by jleyba** [comment]
Sorry, wrong type reference:

```javascript
const {Condition} = require('selenium-webdriver/lib/webdriver');
```

I will add it to the exports for the top level `selenium-webdriver` module.

**Comment by machineghost** [comment]
> I will add it to the exports for the top level selenium-webdriver module.

Awesome, thanks.
