### ISSUE TITLE
IE 11: Not able to switch/identify to frame when running from Jenkins

### ISSUE THREAD

**Issue by gauthampai13** [SeleniumHQ/selenium#2757]
## Meta -
OS:  
Windows Server 2012
Selenium Version:  
2.53.1.0
Browser:  
IE 11

Browser Version:  
11.0.34
## Expected Behavior -
Switch to Frame
## Actual Behavior -
Element not found.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
