### ISSUE TITLE
Include the version number in `BuildInfo`

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#2763]
We don't currently include the version number in the BuildInfo. This means that exceptions state the version is `unknown`, which isn't helpful in the slightest.

To make this work, we need to modify Buck to allow us to include a manifest file for every library, and not just for binaries.

**Comment by mach6** [comment]
👍  Yep, this was bothering me the other day. Was about to file it myself. Thanks for beating me to it!

**Comment by lukeis** [comment]
@shs96c seems like you fixed this in 5772b63b17cc79564c4a62e4dc391b65c66ccbfb ?

**Comment by shs96c** [comment]
Yup. This is now fixed.
