### ISSUE TITLE
Old preferences sent to the geckodriver for a local instance (Python client)

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#2767]
## Meta -

Windows 8.1, Firefox 48.0.2, Python 3.5.2, Selenium 3.0.0.b2
## Actual Behavior -

A local instance of the driver starts a different configuration of Firefox compared to a remote instance (with marionette enabled in both cases):

[local preferences vs remote preferences](https://github.com/SeleniumHQ/selenium/files/470085/diff.pdf)

The remote instance has the preferences defined by the geckodriver while the local instance has the preferences from the former driver (2.53). The local driver creates and sends a profile by default with the old preferences to the geckodriver.
## Expected Behavior -

The local driver shouldn't create and send a profile by default when the `marionette` capability is set to true.
## Local instance -

``` python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

DesiredCapabilities.FIREFOX['marionette'] = True
driver = webdriver.Firefox(executable_path='geckodriver.exe')
```
## Remote instance -

``` python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX
capabilities['marionette'] = True
driver = webdriver.Remote("http://localhost:4444/wd/hub", desired_capabilities=capabilities)
```

**Comment by barancev** [comment]
Triaging old issues whille preparing to 4.0 release.
```
DesiredCapabilities.FIREFOX['marionette'] = True
driver = webdriver.Firefox(executable_path='geckodriver.exe')
```
This code is not valid, it does not pass changed capabilities to the driver, that explains why there is no effect of this change.
