### ISSUE TITLE
[C#][Firefox] NoSuchElement exceptions turn into FormatExceptions due to "?" JS line numbers

### ISSUE THREAD

**Issue by TwelveBaud** [SeleniumHQ/selenium#2774]
## Meta -
OS:  Windows 10 Pro Anniversary Edition
Selenium Version:  2.53.1, using C# bindings
Browser:  Firefox
Browser Version:  50.0a2 (with signing enforcement, compat checking, and Electrolysis preffed off)

## Expected Behavior -
If a FindElement call cannot locate an element, a NoSuchElementsException is thrown.

## Actual Behavior -
FirefoxDriver generates a NoSuchElementsError in JavaScript, and marshals it to the client, but when the client is trying to unpack the browser-side call stack to throw the NoSuchElementsException, it throws a FormatException instead while parsing line numbers into integers. Specifically, "?" is not an integer.

Inspecting the Response object shows, among other more normal looking stack trace elements, this one:
```
methodName: "setTimeout handler*DelayedCommand.prototype.execute@[WebDriver profile directory]
        /extensions/fxdriver@googlecode.com/components/command-processor.js"
fileName: "?"
lineNumber: "?"
columnNumber: "?"
```

**Comment by jimevans** [comment]
Fixed in 60766a0
