### ISSUE TITLE
Inconsistent use of tabs and spaces error in safari drivers

### ISSUE THREAD

**Issue by Ctesias** [SeleniumHQ/selenium#2775]
## Meta -
OS:  Windows 7 Professional  

Selenium Version:   Selenium IDE 2.9.1

Browser: Chrome (but the errors are in the safari drivers)  

Python Version: 3.5.2

Bindings Version: 3.0.0b2

## Expected Behavior -
Selenium exported Python tests will run with latest selenium bindings 

## Actual Behavior -
Hit error during execution:

C:\git\acme_bowling>python bowling_selenium_test.py
Traceback (most recent call last):
  File "bowling_selenium_test.py", line 2, in <module>
    from selenium import webdriver
  File "C:\Users\dchadwell\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\selenium-3.0.0b2-py3.5.egg\selenium\webdriver\__init__.py", line 25, in <mod
ule>
    from .safari.webdriver import WebDriver as Safari  # noqa
  File "C:\Users\dchadwell\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\selenium-3.0.0b2-py3.5.egg\selenium\webdriver\safari\webdriver.py", line 49
    executable_path = os.environ.get("SELENIUM_SERVER_JAR")
                                                          ^
TabError: inconsistent use of tabs and spaces in indentation

C:\git\acme_bowling>python bowling_selenium_test.py
Traceback (most recent call last):
  File "bowling_selenium_test.py", line 2, in <module>
    from selenium import webdriver
  File "C:\Users\dchadwell\AppData\Local\Programs\Python\Python35\lib\site-packa
ges\selenium-3.0.0b2-py3.5.egg\selenium\webdriver\__init__.py", line 25, in <mod
ule>
    from .safari.webdriver import WebDriver as Safari  # noqa
ImportError: No module named 'selenium.webdriver.safari'

## Steps to reproduce -
Should always happen with 3.0.0b2

**Comment by lukeis** [comment]
was fixed with 055325c09d783b6b6c9cbdeaa0828384048b0222

pending b3 release for python - @AutomatedTester

**Comment by Ctesias** [comment]
ETA on b3 release?

**Comment by AutomatedTester** [comment]
just released... wasnt aware we were shipping
