### ISSUE TITLE
Native clicks do not work in internet explorer v 11

### ISSUE THREAD

**Issue by naissa12** [SeleniumHQ/selenium#2776]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.531
Browser:  
IE 11

FIREFOX 48+ IS ONLY COMPATIBLE WITH GECKODRIVER. Any issue logged here for 48+ will be closed as a duplicate of #2559

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  
v11

## Expected Behavior -
click function to click on element

## Actual Behavior -
When I set nativeEvents capability = true, clicks do not work in IE v 11.0. When I set nativeEvents = false, clicks on elements work. How can I get native clicks to work?

## Steps to reproduce -
Set desired capability nativeEvents -> true
Try using click function on elements
Native clicks do not work

**Comment by jimevans** [comment]
This is not a global problem with all users. I can confirm that clicks using native events are working, both with setting the `requireWindowFocus` capability and without.

**Comment by naissa12** [comment]
so why am I having issues then? What configuration works 100%?
