### ISSUE TITLE
Browser version compatibility checks!

### ISSUE THREAD

**Issue by aadrian** [SeleniumHQ/selenium#2777]
Please add browser version compatibility checks!

One of the biggest problems with errors regarding Selenium tests are browser compatibility issues (between the running browser and the used driver).

Users loose huge amount of time due to:
 - mismatch of the two due to poor setup or changes
 - browsers getting updated automatically
 - system and path changes

all these leading very often tests failures were they were working before (or on other user's computers).

Please add some checks so that these scenarios won't happen anymore (or not so often).
E.g. when instantiating the browser, the selenium drivers could know what browser versions are fully supported and could display a corresponding message.

It would save huge amount of time wasted by your users and also unnecessary bug reports.

Thank you.

**Comment by lukeis** [comment]
We do have an extensive test suite. If you have some scenarios that don't work on particular browsers, please do log those issues with the corresponding driver projects.

There's no realistic way to accomplish what you think we can do with complete cross browser compatibility, especially not with a volunteer-only open source project. Patches / bug fixes are very welcome!

**Comment by aadrian** [comment]
> If you have some scenarios that don't work on particular browsers, please do log those issues with the corresponding driver projects.

We have **all** the time problems when the scenarios mentioned above appear. It's useless to log issues every time. 

> There's no realistic way to accomplish what you think we can do with complete cross browser compatibility, 

Why not? Make the drivers to mandatory specify what browser versions they support, and than use this information at runtime.
