### ISSUE TITLE
Unable to run tests locally on chrome

### ISSUE THREAD

**Issue by sri85** [SeleniumHQ/selenium#2784]
I am trying to run chrome tests locally on MAC(El Capitan) , however i am unable to run the tests locally on chrome , i am able to invoke chrome using remote webdriver. But when i try to run the tests without the remote webdriver i.e invoking chrome directly I am getting error 

        driver/chrome/webdriver.py", line 62, in __init__
        self.service.start()
      File "/Users/testuser/practise/venv/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 92, in start
        raise WebDriverException("Can not connect to the Service %s" % self.path)
    WebDriverException: Message: Can not connect to the Service chromedriver

I have the chromedriver binary located in `/usr/local/bin` and i have the same in my **PATH** as well. 

    Selenium Version: selenium (2.53.6)
    Chromedriver Version: 2.24.417412
    Python Version: 2.7.10

MY sample script

   

    # Import unittest module for creating unit tests
    import unittest
    
    # Import time module to implement
    import time
    
    # Import the Selenium 2 module (aka "webdriver")
    from selenium import webdriver
    
    # For automating data input
    from selenium.webdriver.common.keys import Keys
    
    # For providing custom configurations for Chrome to run
    from selenium.webdriver.chrome.options import Options
    
    
    # --------------------------------------
    # Provide a class for the unit test case
    class PythonOrgSearchChrome(unittest.TestCase):
    
    	# Anything declared in setUp will be executed for all test cases
    	def setUp(self):
    		# Select which device you want to emulate by uncommenting it
    		# More information at: https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation
    		mobile_emulation = {
    			
    			"deviceName": "Google Nexus 5"
    			# Or specify a specific build using the following two arguments
    			#"deviceMetrics": { "width": 360, "height": 640, "pixelRatio": 3.0 },
    		    #"userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19" }
    		}
    
    		# Define a variable to hold all the configurations we want
    		chrome_options = webdriver.ChromeOptions()
    
    		# Add the mobile emulation to the chrome options variable
    		chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)
    
    		# Create driver, pass it the path to the chromedriver file and the special configurations you want to run
    		self.driver = webdriver.Chrome(chrome_options=chrome_options)
    
    	# An individual test case. Must start with 'test_' (as per unittest module)
    	def test_search_in_python_chrome(self):
    		# Assigning a local variable for the global driver
    		driver = self.driver
    
    		# Go to google.com
    		driver.get('http://www.google.com')
    
    		# A test to ensure the page has keyword Google in the page title
    		self.assertIn("Google", driver.title)
    
    		
    
    		# Find and select the search box element on the page
    		search_box = driver.find_element_by_name('q')
    
    		# Enter text into the search box
    		search_box.send_keys('Cat gif')
    
    		# Make sure the results page returned something
    		assert "No results found." not in driver.page_source
    
    		# Submit the search box form
    		search_box.submit()
    
    		# Can also use Keys function to submit
    		#search_box.send_keys(Keys.RETURN)
    
    		# Another pause so we can see what's going on
    		time.sleep(5)
    
    		# Take a screenshot of the results
    		driver.save_screenshot('screenshot-deskto-chrome.png')
    
    	# Anything declared in tearDown will be executed for all test cases
    	def tearDown(self):
    		# Close the browser.
    		# Note close() will close the current tab, if its the last tab it will close the browser. To close the browser entirely use quit()
    		self.driver.close()
    
    # Boilerplate code to start the unit tests
    if __name__ == "__main__":
    	unittest.main()

I am really not sure what is happening , because i am able to launch the browser using remote webdriver, Any help would be greatly appreciated.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Arcrammer** [comment]
@lukeis: This is definitely an issue. I'm running into the same problem. I've been searching for an answer for several hours. It's not an issue that everyone can reproduce. I set up a new VM and got a different unrelated error.

@sri85: Have a look at this: https://github.com/mozilla/geckodriver/issues/270#issuecomment-258152597. I believe this is a Selenium issue as well because the error message doesn't seem like something I can fix from my end. Kind of stuck. :/

**Comment by swUchicago** [comment]
Yes. I have the same problem. No sure what's going on here.

**Comment by cgoldberg** [comment]
> This is definitely an issue

fwiw, I just ran the sample script provided by the OP and it runs fine on this setup:

* python 2.7
* selenium 3.0.2
* chromedriver 2.26
* chrome 55
* el capitan

> I set up a new VM and got a different unrelated error.

then post the error.

**Comment by HappinessInAutism** [comment]
i was able to fix the same problem. win7x64, python 3.6
selenium and chromedriver up-to-date

the problem was that "localhost" name didn't resolve on my machine. new record in hosts file fixed the problem. i've faced this problem on two different machines(windows) hence this solution might be helpful for someone
