### ISSUE TITLE
get_attribute raise an exception (release 3.0.0-beta-3)

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#2785]
Windows 8.1, Python 3.5,2, Selenium 3.0.0-beta-3

## Actual Behavior -
Calling `get_attribute` on a web element raises an exception with version 3.0.0-beta-3:
```python
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 136, in get_attribute
    self, name)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: SyntaxError: missing ) in parenthetical
```
This issue was introduced by this commit: https://github.com/SeleniumHQ/selenium/commit/4c75ef025f3b0cae5b8462266370d015843bc3ac

The exception is raised because the loaded resource `getAttribute.js` is not properly decoded:
https://github.com/SeleniumHQ/selenium/blob/4c75ef025f3b0cae5b8462266370d015843bc3ac/py/selenium/webdriver/remote/webelement.py#L133

So a fix would be to decode the resource :

    raw = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')

I also noticed that the file is loaded each time `get_attribute` is called. It would be preferable to cache it on the first call.

**Comment by ZijianHe** [comment]
`Mac OSX` `Python 3.5.1`, `Selenium 3.0.0-beta-3`.

Same problem occur with the use of `isDisplayed.js`, which is also not properly decoded:
[https://github.com/SeleniumHQ/selenium/blob/4c75ef025f3b0cae5b8462266370d015843bc3ac/py/selenium/webdriver/remote/webelement.py#L350](url)

And also fix with the same way:
<pre>raw = pkgutil.get_data(__package__, 'isDisplayed.js').decode('utf8')</pre>
