### ISSUE TITLE
Separate language binding implementation to separate repositories

### ISSUE THREAD

**Issue by paazmaya** [SeleniumHQ/selenium#2788]
While there might be some reasons for keeping all different language implementation for the Selenium/Webdriver in this same repository, it makes finding information a bit hard.

Separating could perhaps be done by using a naming convention of having the environment in the first part and the project name as the second, for example `node-selenium` (or `node-webdriver`) or `python-selenium` (or `python-webdriver`).

This would make it easier to have issues and pull requests targeting certain language implementations in different places, as well as possible specification or such in its own.

**Comment by titusfortner** [comment]
The reasons are that each of the bindings require artifacts that are built from the project overall. 

Issues and pull requests can be filtered by the label dropdown for the programming language of your interest. 

The repo is also broken down by a top-level directory for each language, and each language indeed has its own tests as well. 

If there is specific information we can help you find, please ask in the mailing list or on our irc channel.
