### ISSUE TITLE
Selenium Webdriver not interacting with the elements on IE11 in Windows server 2008 R2

### ISSUE THREAD

**Issue by chanchow88** [SeleniumHQ/selenium#2790]
## Meta -

OS:  
Windows Server 2008 R2 
Selenium Version:  
2.53.0, IDE
Browser:  
 Internet Explorer 11 
## Expected Behavior -

Webdriver should interact with the elements on the page
## Actual Behavior -

Webdriver passes the url but not able to interact with any elements on the page.
## Steps to reproduce -

Launching the IE11 using the following code snippet.

```
try{System.setProperty("webdriver.ie.driver", "src/main/resources/bin/IEDriverServer.exe");
            }
            catch (Exception ex){
                Reporter.log("\nException in getting and setting the webdriver IE driver: "+ ex.getMessage() + ex.getClass(),true);
                ex.printStackTrace();
            }
            WebDriverManager.browser = browser;
            DesiredCapabilities desiredCapabilities = DesiredCapabilities.internetExplorer(); 
            desiredCapabilities.setCapability("ignoreZoomSetting", true);
            driver = new EventFiringWebDriver(new InternetExplorerDriver(desiredCapabilities));
            driver.manage().deleteAllCookies();
            driver.manage().window().maximize();
```

Now after launching the browser, it passes the URL but after that it complains not able to find element on the page. I tried to run the same on my Windows 7 machine and it works fine.

**Comment by hazmeister** [comment]
I had this previously. Try adding the site under test to the Trusted Sites.

**Comment by schmidtkp** [comment]
You may have to add this registry setting:

reg add "HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 0 /f

See this thread:
Windows update for IE11 breaks IEDriverServer
https://groups.google.com/forum/m/#!topic/selenium-users/TdY_rRNF-gw

I do this on all my Windows Server 2008 RC2 systems running IE11

**Comment by barancev** [comment]
Not enough information to act on. If the issue is still actual please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
