### ISSUE TITLE
Java Robot class on chrome browser

### ISSUE THREAD

**Issue by kritik-asg** [SeleniumHQ/selenium#2791]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by kritik-asg** [comment]
Please find the System configuration:
OS : Windows 10
Selenium Version: Selenium-java-2.53.0
Browser: Chrome
Browser Version: 53.0.2785.116m (64-bit)

URL showing the no support of Java Robot class on chrome browser(Same is attached as screenshot):
http://detectmybrowser.com/#plugin-check

Expected Behavior: 
Alike Edge Browser, on Chrome browser also the **Java Robot class** when used with selenium should not 'Click' on **core-icon/ SVG Element/ Paper-elements** on the Application designed in HTML5, CSS and JS.

Actual Behavior:
With the below lines of functionality using Robot class moves the mouse pointer on the respective co-ordinates on chrome browser and the element gets clicked.

Steps to reproduce:
1> Open the Application on Chrome browser.
2> Enter the text in the Search textbox.
3> Click on the core-icon(SVG button) with Java Robot class.

**Actions performed on Application with below functionality:**
(All the values are passed from excel sheet)

// **To Enter text in the search text-box**
 if (sh.getCell(2, i).getContents().equalsIgnoreCase("Text_Box_CSS"))
					{
						if (_driver.findElement(By.cssSelector(sh.getCell(0, i).getContents())).isDisplayed()) {
							Thread.sleep(4000);
							_driver.findElement(By.cssSelector(sh.getCell(0, i).getContents())).sendKeys(sh.getCell(j-2, i).getContents());
							res = "Pass";
							Thread.sleep(1000);
						}
					} 

//**Robot class functionality which works to click on core-icon element on Chrome browser**
else if (sh.getCell(2, i).getContents().equalsIgnoreCase("SVGButton_CSS"))
					{
						WebElement element = _driver.findElement(By.cssSelector(sh.getCell(0, i).getContents()));
						Point coordinates = element.getLocation();
						Robot robot = new Robot();
						int BUTTON1_MASK=InputEvent.BUTTON1_DOWN_MASK;
						robot.mouseMove(coordinates.getX() + 10, coordinates.getY() + 73);
						robot.mousePress(InputEvent.BUTTON1_MASK);
						robot.mouseRelease(InputEvent.BUTTON1_MASK);
						Thread.sleep(1000);
					}
![no-javasupport-chrome](https://cloud.githubusercontent.com/assets/17634946/18624182/1edcc34a-7e63-11e6-935f-3748f06886b9.png)


Note: The only thing want to understand "Is the Chrome browser starts supporting the Java Robot class and their functionalities as it works for me in my Application."

**Comment by lukeis** [comment]
Java Robots is a separate technology, we do not support it here in Selenium. Selenium has its own means to click on elements, if you have an issue with selenium clicking on something, then please log a new issue for that.

We do not attempt to do anything in Selenium to either allow or disallow Robots from interacting with the browser.

If you would like further help / clarification with using selenium please post on the mailing list:
https://groups.google.com/forum/#!forum/selenium-users
