### ISSUE TITLE
IE - Unable to access elements on 2nd window

### ISSUE THREAD

**Issue by kphilogene** [SeleniumHQ/selenium#2792]
OS: Microsoft 7
Selenium Version: 2.53.1
Browser: IE 11, 64 Bit

I am having a major issue running our automation scripts in IE. I am able to access the elements I need in the default IE window. In our application, I click a button, and a new window opens. In that new window I am not able to access ANY of the elements. I've never had this issue in the past as the code is the same and it works fine in FF.

I’m able to switch WebDriver to the new window and close that window so I know I’m where I’m supposed to be. I wrote a method to list all elements on the page but all 2,118 elements/html tags come back blank. The only thing that comes back correct is the title of that window. I executed the same method on the default window and everything comes back correctly.

**The web application is NOT public. I am unsure of how to use jsfiddle.net. Is there anyway we can set up a screenshare meeting so you can see the behavior?? This is a high priority**.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
