### ISSUE TITLE
WebDriverEventListener afterScript return value support

### ISSUE THREAD

**Issue by andrew-sumner** [SeleniumHQ/selenium#2797]
It would be nice if the afterScript event included the return value (if one is available) of the script execution.

It would aid in improving logging of actions performed by the browser.

**Comment by lukeis** [comment]
none of the other event firing methods pass in values returned from the method calls, they only describe the events occurring. It's up to your code to handle intercept the executeScript method if you want to do something with the return value.

Personally I don't use the event listener and am not aware of all the use cases of it, but in terms of keeping the current class consistent I'm going to decline the request.
