### ISSUE TITLE
Unable to find alert when I use binary chrome option.

### ISSUE THREAD

**Issue by thatb2** [SeleniumHQ/selenium#2801]
Issue : Unable to find alert when I use binary option for chrome.

We are launching the Electron App by using the chrome binary option. When there is an alert it is not finding the alert.
## Meta -
OS:  
Windows 7
Selenium Version:  
2.52.0, ruby
Browser:  
Chrome 
Browser Version:  
52.0.2743.116

Expected Behavior - Alert should be found.

Actual Behavior - Observed No alert error.

**Comment by lukeis** [comment]
issues with chromedriver should be logged with the chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list

I'm uncertain what their support is for embedded desktop apps are for things like electron.
