### ISSUE TITLE
Regular expressions doesnt work in Edge.

### ISSUE THREAD

**Issue by FrankieSingh** [SeleniumHQ/selenium#2807]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lukeis** [comment]
Please log Edge driver issues with Microsoft.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
