### ISSUE TITLE
selenium-server-standalone-3.0.0-beta3.jar does not accept -trustAllSSLCertificates as parameter

### ISSUE THREAD

**Issue by anttilaiti** [SeleniumHQ/selenium#2809]
## Meta -
OS:  
OS X 10.11.6 (most likely happens with any OS)
Selenium Version:  
3.0.0 beta3
Browser:  
N/A
Browser Version:  
N/A

## Expected Behavior -
selenium-server-standalone-3.0.0-beta3.jar should accept -trustAllSSLCertificates as a parameter. selenium-server-standalone-2.53.0.jar does accept that parameter and I've found no info about that been changed.

## Actual Behavior -
$ java -jar selenium-server-standalone-3.0.0-beta3.jar -trustAllSSLCertificates
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -trustAllSSLCertificates
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:210)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:138)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:67)

## Steps to reproduce -
Download selenium-server-standalone-3.0.0-beta3.jar run java -jar selenium-server-standalone-3.0.0-beta3.jar -trustAllSSLCertificates in shell

**Comment by gicoprasico** [comment]
I have the similar issue. I am using java, selenium driver 3.0.0beta3 and firefox 47.0.1. I am accessing an not-trusted  site and i am getting an exception. 

my code: 
```

FirefoxProfile ffprofile = profile.getProfile("default");
ffprofile.setAcceptUntrustedCertificates(true);

 DesiredCapabilities capabilities = DesiredCapabilities.firefox();
 capabilities.setCapability("marionette", true);
 capabilities.setCapability(FirefoxDriver.PROFILE, ffprofile);
 capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
                
```
I am getting a WebDriverException with the following Capabilities description: 
Capabilities => Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160623154057, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, **acceptSslCerts=false**, browserVersion=47.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop, firefox_profile=UEsDBBQACAgIAIJyNUkAAAAAAAAAA...}]

It's clear that I set on profile and on DesiredCapabilities that i want to acceptSslCertificates, but in Capabilities can be seen that this attribute has not been set.

**Comment by anttilaiti** [comment]
I can see using --help that a lot of command line options (including trustAllSSLCertificates) have been removed between 2.53.0 and 3.0.0-beta3. Are those still available somehow?

**Comment by rimvislt** [comment]
any update regarding trustAllSSLCertificates ?

**Comment by lukeis** [comment]
This was a command line option for Selenium RC server, which was deprecated in 2.X of selenium and removed in 3.0. I would recommend upgrading to using WebDriver.

**Comment by lukeis** [comment]
@gicoprasico marionette needs 48+ and works best with firefox nightly. I believe in nightly they have the certificates thing fixed.

@anttilaiti / @rimvislt any reason you can't use webdriver and set the capabilities as shown by @gicoprasico 's code sample? (namely setting the capability).

Until I hear otherwise, I'm assuming this issue is because you are still using the RC server, which as I previously said is deprecated and has been removed. You can still use the 'RC' API in 3.0, but with WebDriverBackedSelenium classes. And you should really be attempting to migrate your tests to webdriver. The only other solution is to peg old RC tests to using a 2.53.1 standalone server until you can migrate them accordingly.
