### ISSUE TITLE
Issue tracker link for safari driver provides Page not found after login

### ISSUE THREAD

**Issue by hemanthsridhar** [SeleniumHQ/selenium#2812]
## Steps to reproduce -
<!-- 
In the landing page of the selenium website http://www.seleniumhq.org/download/ 
Clicking on the issue tracker link associated to safari driver opens up the apple's bug reporter login page. Logging in provides page not found.  
**If this is not in the selenium's scope please close the issue.**

The bug I want to raise is I am still not able to handle alerts in Safari Driver.

Still getting the same exception 
org.openqa.selenium.UnhandledAlertException: A modal dialog was opened. The SafariDriver does not support interacting with modal dialogs. To avoid hanging your test, the alert has been dismissed. For more information, see http://code.google.com/p/selenium/issues/detail?id=3862: Please enter valid values

**Is there a way now to handle alerts?** 
->

**Comment by lukeis** [comment]
logging into apple's bug tracker works for me... and no, it's not in our purview to handle issues with apple.

I don't believe alert handling has been implemented there yet.

There's always the old work-around which is to driver.executeScript("window.alert = function(){}") before the alert would appear. To essentially suppress it from happening.

Seems though that you are using selenium's SafariDriver extension, make sure you upgrade to Safari 10 and that /usr/bin/safaridriver exists to use the latest.

**Comment by hemanthsridhar** [comment]
@lukeis : Upgraded. Followed the documentation that is present the selenium Website. 
Can you teach me how to get the alert text in safari if at all there is an option?

**Comment by jlipps** [comment]
@hemanthsridhar you could do this with a bit of executeScript hackery, essentially overwriting the alert method as @lukeis described, but storing the message in a variable for later retrieval.

(using python-ish pseudocode; adjust for your language)

```
driver.execute_script("window.alert = function(msg) {window.__alertMsg = msg;};")
# do action that triggers an alert
message = driver.execute_script("return window.__alertMsg");
self.assertEqual(message, "what the message should be")
```

**Comment by hemanthsridhar** [comment]
@jlipps thank you so much.
