### ISSUE TITLE
Microsoft Edge clicking session issues

### ISSUE THREAD

**Issue by naissa12** [SeleniumHQ/selenium#2813]
## Meta -
OS:  
 Windows 10
Selenium Version:  
2.531
Browser:  
Microsoft Edge 

I cannot click on elements in microsoft edge in selenium tests. Does anyone know why?
I am having the follow issues with Microsoft Edge v 13;

- Cannot click on elements using selenium click function
- Cannot find elements that are on top of other elements (waitForElement function does not work)
- Cannot open a new clean session every time I run a test using Edge driver

How can I resolve the issues above? Maybe my desired capabilities configuration is wrong? 
What are the desired capabilities needed to get Microsoft Edge working well?

-->

Browser Version:  
13

## Expected Behavior -

Expected click and new session every time open Microsoft Edge browser.

## Actual Behavior -
Cannot click on elements. Doesn't open new session each time.

## Steps to reproduce -
1. Try to click on an element that is on top of another element (like a menu that opens on top of other elements)
2. Try to open a new test using Microsoft Edge, session won't be cleared

**Comment by lukeis** [comment]
For questions, please ask on the selenium-users forum:
https://groups.google.com/forum/#!forum/selenium-users

For Edge issues, please log them with microsoft:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

Please be sure to include a reproducible test script that includes a link to a page to reproduce the issue. If you can not provide a public url, consider creating one with jsfiddle.net
