### ISSUE TITLE
Unable to click on checkbox if it covered by tag using Selenium 2.53.1 and Firefox 47

### ISSUE THREAD

**Issue by Mubat** [SeleniumHQ/selenium#2817]
System configuration

- OS:  Ubuntu MATE 14.04
- Selenium Version:  2.53.1
- Browser:  Firefox 47.0.1
- Language: PHP 5.6.25-2+deb.sury.org~trusty+1
- Test Framework: codeception/codeception:2.2.4

It's actualy described in [Click button does not work after upgrade to selenium 2.48.0](https://github.com/SeleniumHQ/selenium/issues/1202) #1202 

I can click on checkbox when it covered by another element on page.

![image](https://cloud.githubusercontent.com/assets/3623986/18750092/67583ca4-80e2-11e6-927f-e607ad572711.png)

Without header: 

![image](https://cloud.githubusercontent.com/assets/3623986/18750106/70566510-80e2-11e6-8c9a-ff4cd077589c.png)

If remove header, it will works. Checkbox will be clicked.
Using chrome browser it passed too.

## Expected Behavior -
It simple, checkbox should be clicked successfully.
## Actual Behavior -
Have an error while trying to click on checkbox
`[Facebook\WebDriver\Exception\UnknownServerException] Element is not clickable at point (72, 9.100006103515625). Other element would receive the click: <a class="navbar-brand" href="/"></a>
Command duration or timeout: 236 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'oleg-HP-Pro-3500-Series', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-34-generic', java.version: '1.7.0_80'
Session ID: 25d2934f-1af6-4873-bf23-17df368825cb
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=47.0.1}] `

## Steps to reproduce -
I`m use standart method for submit inputs  https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/WebDriver.php#L1354 

This is my [Page Source](https://jsfiddle.net/rx2Lxv9h/) (or [this](https://script.google.com/d/1OCXTwz40kQxJS-vh1k6863vojiYRRz4jGrRoLXbL03wrWHGka7sjJa_t/edit?usp=sharing))

**How to click on checkbox in firefox?**

**Comment by lukeis** [comment]
This is expected behavior, if the element is covered and unclickable by a user, then selenium also shouldn't be able to click it.

You can attempt to ensure your element is clickable by adjusting the scroll position in the browser before attempting the click.

If you're saying in the same situation when the element is covered it does actually do the click in chrome, then that is a bug for chromedriver. It should also be throwing an exception.

**Comment by Mubat** [comment]
Hi @lukeis.
I think, it's not a normal behavior when Selenium scroll to position when it don't see object. 

Generally, Selenium should do what user will do, isn`t right? User never will scroll to object in this way - he will scroll so that he could see object.

Is it possible to do **in firefox** how chrome do - scroll page util need object appeared at the bottom?

**Comment by lukeis** [comment]
You can set a capability
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/CapabilityType.java#L43

To change the behavior of scrolling to be to the bottom (1)

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/internal/ElementScrollBehavior.java#L23
