### ISSUE TITLE
Selenium and DevExtreme 16.1.6 Issues

### ISSUE THREAD

**Issue by TestEngineerFrom410** [SeleniumHQ/selenium#2818]
## Meta -
OS:  Windows 8.1

Selenium Version:  2.53.1

Browser:  Firefox, IE

Browser Version:  IE 11, Firefox 47.0.1

## Expected Behavior -

Hover menu items and cause drop down to display

## Actual Behavior -

Hovering menu item does not cause the drop down to display (if a dropdown is present). This occurs when testing again DevExtreme 16.1.6 navigation controls. Works fine in Google Chrome.
![capture](https://cloud.githubusercontent.com/assets/22375453/18756270/4e6efa54-80bd-11e6-9e6c-ead94755ac08.PNG)

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
