### ISSUE TITLE
Release prereleases of selenium-webdriver as @next, not @latest 

### ISSUE THREAD

**Issue by donaldpipowitch** [SeleniumHQ/selenium#2819]
When you call `npm install selenium-webdriver` you'll get `3.0.0-beta-3`. `npm install selenium-webdriver` is equivalent to `npm install selenium-webdriver@latest`. I'd expect to get the latest _stable_ release here. To publish unstable prereleases like `3.0.0-beta-3` you'd probably use the `@next` tag. If you want  `3.0.0-beta-3` you would call `npm install selenium-webdriver@next`. More information [here](https://docs.npmjs.com/cli/tag#purpose).

I struggled here, because I installed `selenium-webdriver` and got `Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.` Maybe it would be good too not just link to `geckodriver`, but also pass a link which explains the differences between 2.x and 3.x and the motivation behind the change.

While the stack trace of this error helped me to find out that it was thrown by `selenium-webdriver` in the first place, IMHO I prefer to use `throw 'foo'` here instead of `throw new Error('foo')` _when_ `"foo"` is descriptive enough to tell me _who_ throws the error and _why_ this error is thrown. I expect a stack trace for more "unintentional" errors.

**Comment by jleyba** [comment]
> When you call npm install selenium-webdriver you'll get 3.0.0-beta-3. npm install selenium-webdriver is equivalent to npm install selenium-webdriver@latest. I'd expect to get the latest stable release here. To publish unstable prereleases like 3.0.0-beta-3 you'd probably use the @next tag. If you want 3.0.0-beta-3 you would call npm install selenium-webdriver@next. More information here.

The versions used on npm are kept in sync with the Selenium project as a whole. That said, this project follows trunk based development. Every published release is considered stable and supported. If you want an "unstable" preview of the next release, simply build from source.

> I struggled here, because I installed selenium-webdriver and got Error: The geckodriver executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH. Maybe it would be good too not just link to geckodriver, but also pass a link which explains the differences between 2.x and 3.x and the motivation behind the change.

The error message is perfectly clear about the problem and what you need to do to fix it.

> While the stack trace of this error helped me to find out that it was thrown by selenium-webdriver in the first place, IMHO I prefer to use throw 'foo' here instead of throw new Error('foo') when "foo" is descriptive enough to tell me who throws the error and why this error is thrown. I expect a stack trace for more "unintentional" errors.

Simply put, this will never happen. Throwing Error captures the context of the program instead of having to grep for a string.

**Comment by donaldpipowitch** [comment]
If every release is stable why are beta releases used in the first place?

> The error message is perfectly clear about the problem and what you need to do to fix it.

It tells me about the "what", that is right. But it would be nice to here the "why", too.

> Throwing Error captures the context of the program instead of having to grep for a string.

Why would I ever want to grep a string or read the stack trace, if the error message is "perfectly clear"? :) I'd only want to do that, if it doesn't contain enough information.

Anyway... It is your decision. I just tried to make recommendations. And I still think that it would be better to use @next tags, if you use beta releases. I can't see why @latest would be better from a consumer point of view.
