### ISSUE TITLE
Ruby bindings start Chromedriver with logging enabled by default

### ISSUE THREAD

**Issue by abotalov** [SeleniumHQ/selenium#2821]
## Actual Behavior
Currently Ruby bindings by default start Chromedriver with logging enabled. With logging enabled Chromedriver memory  usage grows significantly as it runs. I reported this issue to Chromedriver [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1425) but they didn't fix it.

They said:
```I would suggest you to file a bug with selenium webdriver for ruby bindings. Ruby library should be changed so that it does not enable logs by default.```

## Expected Behavior
Two possible fixes:
* Ruby bindings don't start Chromedriver with logging enabled by default
* Chromedriver fixes an issue with memory growth if logging is enabled

## Steps to reproduce

Run the following script:
```ruby
require 'selenium-webdriver'
driver = Selenium::WebDriver.for :chrome
10000.times do |i|
  driver.navigate.to "about:blank"
end
```
[By the end of this "chromedriver.exe" will have ~200 MB taken](https://bugs.chromium.org/p/chromedriver/issues/attachment?aid=241600&inline=1)

**Comment by titusfortner** [comment]
While this is technically already configurable by setting `:logging_prefs` in a `Remote::Capabilities` instance, I agree that this shouldn't be on by default.
