### ISSUE TITLE
ChromeOptions mode configuration "Platform" parameter problem

### ISSUE THREAD

**Issue by mesoar** [SeleniumHQ/selenium#2830]
Try using JS modify "navigator.platform" open or change URL "navigator.platform" Fail...
I need to use the specified simulation mobile , use DesiredCapabilities Can not work...

Selenium version: 2.53
OS: Windows 7
Browser: Chrome
Browser version: 52.0.2743.82
::.NET ChromeOptions use platform

I have tried to resolve this problem by themselves, but two days did not progress...- -! 
Or there are other ways to solve this problem?
this problem Really anxious, not sleep at ease

Thank you help me solve this problem

**Comment by mesoar** [comment]
~~~****

**Comment by lukeis** [comment]
Try the Mobile Emulation that is documented:
https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation

If that is not working for you, please show example code you are using and log a new issue with the chromedriver project:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by mesoar** [comment]
Thank you for the reply 
sincere regards

This is the work code
```
ChromeMobileEmulationDeviceSettings deviceSettings = new ChromeMobileEmulationDeviceSettings();
deviceSettings.Width = 414;
deviceSettings.Height = 736;
deviceSettings.PixelRatio = 3;
deviceSettings.UserAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1";
deviceSettings.EnableTouchEvents = true;

ChromeOptions options = new ChromeOptions();
options.EnableMobileEmulation(deviceSettings);

driver = new ChromeDriver(options);
driver.Navigate().GoToUrl("http://www.google.com");
```
I must retain "MobileEmulation" At the same time I want to specify "navigator.platform" 
Until now I read any information not find a solution ...
i expect effective solutions which I am extremely grateful...

**Comment by lerebourx** [comment]
Why no body answer this question? @lukeis
