### ISSUE TITLE
FirefoxDriver Java binding does not pick up binary or profile in W3C mode

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#2835]
@krmahadevan pointed out in https://github.com/mozilla/geckodriver/issues/236 that the reason why people are having problems using Firefox profiles with geckodriver is that the profile passed to the Java bindings’ ctor is not being used when creating a _DriverCommandExecutor_ in https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L236-L245:

```java
private static final CommandExecutor createCommandExecutor(Capabilities desiredCapabilities,
                                                           FirefoxBinary binary,
                                                           FirefoxProfile profile) {
  if (isLegacy(desiredCapabilities)) {
    return new LazyCommandExecutor(binary, profile);
  }
  GeckoDriverService.Builder builder = new GeckoDriverService.Builder();
  builder.usingPort(0);
  return new DriverCommandExecutor(builder.build());
}
```

As far as I can tell, we need to:

1. Change _GeckoDriverService.Builder_ to accept the passed `profile` and `binary` arguments.
2. Create a method in _GeckoDriverService_ that accepts the capabilities and feeds in the `firefox_profile` and `firefox_binary` with a Base64-encoded version of _FirefoxProfile_ and a the full path to the browser binary, and which returns the modified set of capabilities.
3. Update _FirefoxDriver#createCommandExecutor_ to pass `binary` and `profile` to the _GeckoDriverService.Builder_.
4. Make [this ctor](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L217) modify the capabilities so that it takes the updated capabilities.

I suspect the _ChromeDriver_ class uses a similar approach, and it can be used for inspiration.

**Comment by lukeis** [comment]
this is essentially a duplicate of #2572 but with added request. Care to close this or that bug?

**Comment by krmahadevan** [comment]
@lukeis - So do you recommend that we just go ahead and deprecate the FirefoxDriver constructor that accepts a profile object (or) do you suggest that we make internal changes such that the firefox profile object that is passed via the constructor is injected into the capabilities object that gets created in the chain of constructor calls ?

**Comment by lukeis** [comment]
i wasn't suggesting anything... merely pointing out this is a duplicate issue already logged :)

**Comment by krmahadevan** [comment]
Lol @lukeis .. Ok, I was basically trying to figure out how do we fix this issue and seeking recommendations/guidance from you.

**Comment by andreastt** [comment]
Duplicate of https://github.com/SeleniumHQ/selenium/issues/2572.
