### ISSUE TITLE
Enhancement request: access to text nodes

### ISSUE THREAD

**Issue by acolomitchi** [SeleniumHQ/selenium#2840]
Select only the text nodes inside `<div id='one'>`, without the text in the  `<blockquote>` children

``` html
  <div id='one'>
    <blockquote id='two'>dolore ipsum</blockquote>
    Ah, the pain itself
    <blockquote id='three'>Ah, the pain</blockquote>
 </div>
```

Selector:

``` java
driver.findElement(By.xpath("//*[@id='one']/text()"));
```

Result:

```
org.openqa.selenium.InvalidSelectorException: invalid selector: 
The result of the xpath expression "//*[@id='one']/text()" is: [object Text].
It should be an element.
```

**Comment by acolomitchi** [comment]
Workaround (Java):

```Java
WebElement e=driver.findElement(By.xpath("//*[@id='one']"));
if(driver instanceof JavascriptExecutor) {
  String js=
      "var tw = document.createTreeWalker("
     +   "arguments[0],"
     +   "NodeFilter.SHOW_TEXT,"
     +   "{ acceptNode: function(node) { return NodeFilter.FILTER_ACCEPT;} },"
     +    "false"
     + ");"
     + "var ret=null;"
     + "while(tw.nextNode()){"
     +   "var t=tw.currentNode.wholeText.trim();"
     +   "if(t.length>0){" // skip over all-white text values
     +      "ret=(ret ? ret+'\t'+t : t);" // if many, tab-separate them
     +   "}"
     + "}"
     + "return ret;" // will return null if no non-empty text nodes are found
  ;
  Object val=((JavascriptExecutor) driver).executeScript(js, e);
  // -------------------------context node here -------------^

  String textNodesTabSeparated=(null!=val ? val.toString() : null);
}

**Comment by lukeis** [comment]
You will likely need to log a bug with each of the implementations for this (chromedriver, geckodriver, EdgeDriver, safaridriver, htmlunitdriver, etc.).

In this project we only maintain the (old) FirefoxDriver, where we're unlikely to make this enhancement, and the IEDriver.

As far as the w3c spec, i don't see anything that precludes a WebElement reference from being a Text Node, but the language specifically says 'element' here:
https://w3c.github.io/webdriver/webdriver-spec.html#dfn-web-element

Which according to whatwg spec is:
https://dom.spec.whatwg.org/#concept-element

Which is a separate definition than that of a text node:
https://dom.spec.whatwg.org/#text

So, there is some ambiguity here and if you'd like to ensure there isn't any and have implementations return text nodes, I suggest logging a bug with the WebDriver w3c spec also.

**Comment by lukeis** [comment]
I would also like to note that the Element Displayedness section explicitly lists text nodes, so I'm of the opinion it is included.

https://w3c.github.io/webdriver/webdriver-spec.html#element-displayedness

**Comment by acolomitchi** [comment]
Following the suggestion, I [raised an issue](https://github.com/w3c/webdriver/issues/340) against  WebDriver w3c spec. (assuming that if it will be addressed at the spec level, it will also be addressed by each of the individual projects).

**Comment by asevans48** [comment]
chromium has a node API that has text ability

**Comment by diemol** [comment]
Closing in favor of the issue raised in the W3C repo.
