### ISSUE TITLE
Send Tab key not working in Chrome Browser Version 53.0.2785.116 m

### ISSUE THREAD

**Issue by heyitsmesuraj** [SeleniumHQ/selenium#2843]
SendKeys(Keys.Tab) not working after chrome updated to latest version. Can you guys suggest alternative method for verifying tab to next input field by using js?

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by heyitsmesuraj** [comment]
Thanks Luke, I implemented and works great :)

**Comment by nvega-ms** [comment]
I observed the same problem using Firefox driver
