### ISSUE TITLE
Selenium Standalone: how to specify args to pass to underlying driver?

### ISSUE THREAD

**Issue by anula** [SeleniumHQ/selenium#2849]
ChromeDriver allows to specify a few command line flags. Among others there is "--adb-port" that allows to run tests against a browser on Android when adb server is not running on a default port. I don't see a way, though, to tell Selenium to pass the appropriate value with that flag when starting a ChromeDriver service. Is there such a way? I see that some of the flags can be controlled with system properties ([ChromeDriverService.java](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/src/org/openqa/selenium/chrome/ChromeDriverService.java)) but there is nothing to control that particular flag nor any more generic way that would allow to pass any flag.
Without that it is basically impossible to run anything against a browser on Android when adb is not running on default port. Am I missing something, or there is really no way to do this?

**Comment by lukeis** [comment]
This is a question for the chromedriver project. You can attempt to ask on the selenium-users google group or I would recommend logging a bug with the chromedriver project, but phrase your description as a bug, rather than a question. Include example scripts of what you've attempted to do.

https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by anula** [comment]
But the question is what should I pass to Selenium to make it pass it as a command line argument to underlying driver (for example ChromeDriver). So it is about Selenium, not ChromeDriver. ChromeDriver supports the functionality, I just don't know if Selenium does as well.
Nevertheless, thank you for the pointer to selenium-users group.
