### ISSUE TITLE
Incorrect/Superfluous argument validation in SingleKeyAction.java 

### ISSUE THREAD

**Issue by phiros** [SeleniumHQ/selenium#2850]
SingleKeyAction [1] only accepts modifier keys as arguments. As far as I can see this is an
artificial restriction which:
* serves no actual purpose 
* can be safely removed

Therefore, I would be happy if someone could either remove this validation or explain to me why this validation should stay in the code.

[1] https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/src/org/openqa/selenium/interactions/internal/SingleKeyAction.java

**Comment by lukeis** [comment]
Just want to first mention that Actions are being re-worked completely with the webdriver spec.

It does make a difference. The sendKeys, keyDown, keyUp(releaseKey) all call the same end point (literally the same call to the remote end):

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteKeyboard.java#L34-L45

The difference is modifier keys are special cases in the JSONWP implementations. First instance of each key is treated as a KeyDown, second instance of them is a KeyUp (or release). All other keys will have the keyDown, keyUp, keyPress events fired.

So, the way it is, still makes sense. And we provide no mechanism to actually individually trigger keyDown or keyUp events for any key other than the modifiers.

This will be changing in the new Actions API provided by the w3c spec -
https://w3c.github.io/webdriver/webdriver-spec.html#actions

We are intending to have the selenium library be w3c spec compliant with the 4.0 version, which will include a new Actions api (well, basically the same api, except using new endpoints and likely this restriction that you point out removed). Until then, we can't take action on this issue. I hope this is clear enough for now.
