### ISSUE TITLE
Provide shim for submitting form command

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#2854]
The W3C WebDriver specification does not specify a command for submitting a form. Many language bindings in Selenium provide a `webElement.submit()` function that no longer has a corresponding primitive in the remote end.

Selenium will need to provide a shim for submitting a form.

Given an HTML form,

```html
<form>
 <input>
 <input type=submit>
</form>
```

one could imagine the workaround looking at `element.form.submit()` through JavaScript.

**Comment by andreastt** [comment]
This was reported in https://github.com/mozilla/geckodriver/issues/247.

**Comment by AutomatedTester** [comment]
This has been done in all the clients from what I can see so closing

**Comment by mb73** [comment]
I had that problem with the very recent selenium-java 3.0.0-beta4.

**Comment by andreastt** [comment]
It does appear to be fixed in the Java bindings: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/W3CHttpCommandCodec.java#L175

**Comment by mb73** [comment]
But that is the version I am using. Without that commit I was not able to get the active element. You remember? Now I am one step further.
