### ISSUE TITLE
Element Position & Remote Server

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2857]
Remote Server on Master with latest Firefox & Geckodriver:

This returns "invalid argument"

`-> GET session/1f5dea04-a9cc-4d6b-8886-ddefb17b3106/element/0/rect`

[Full stack trace](https://gist.github.com/titusfortner/96b87437c662700a8be02d351036c594)

**Comment by shs96c** [comment]
There is still discussion on the correct format of the response from the w3c remote end. Waiting for that to be resolved before progressing on this bug.

**Comment by titusfortner** [comment]
This is working now
