### ISSUE TITLE
Wrong Error Closed Window

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#2858]
Current Master; latest Firefox / Geckodriver

After closing the window; this command:
`GET session/525325be-5c75-4b48-96f2-06f6a476ada8/window`

Is returning this:
`Selenium::WebDriver::Error::UnknownError: browser is undefined`

I'm expecting:
`Error::NoSuchWindow`

Debug Info: https://gist.github.com/titusfortner/d3e9a4bc02dd5439923cb8454b38b4dd

**Comment by titusfortner** [comment]
Well, this is fascinating. Turns out I got this error when using a built-from-master version of geckodriver, and it works just fine with 0.10.0, so I'm closing this, and preparing to re-open it when 0.11 is released. :)

**Comment by vladikoff** [comment]
Hm still having the same issue with 0.11... `browser is undefined`
