### ISSUE TITLE
[On Firefox] Able to hover but not click on a Dropdown:webElement (reactjs)

### ISSUE THREAD

**Issue by ruchikar** [SeleniumHQ/selenium#2861]
## Meta -
OS:  
MAC
Selenium Version:  
2.53.1
Browser:  
FF 45

Browser Version:  
45.0
## Actual Behavior -
Am able to hover over an element on FF but unable to click on it.

## Steps to reproduce -
It's a dropdown list of category, on clicking a category, list of sub category shows up within the dropdown. It's in reactjs.

Now am able to hover over the category but clicking on it closes the dropdown itself.
Works fine on Chrome. Only issue with FF, unable to upgrade FF > 45 bcoz am using Selenium 2.53.1.

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
