### ISSUE TITLE
It would be nice to integrate Selenium with the postman chrome plugin - to run webservice tests

### ISSUE THREAD

**Issue by EvelynGonz** [SeleniumHQ/selenium#2862]
It would be nice to integrate Selenium with the postman chrome plugin - to run webservice tests

**Comment by ddavison** [comment]
i don't think this is something we'll ever do.  Postman is for executing REST endpoints.. that's not what Selenium does, nor do I believe that the project will ever associate itself with that sort of functionality.  We automated front-end websites, not the backend like Postman would.

**Comment by lukeis** [comment]
chrome plugins are already automatable with chromedriver (selenium webdriver api)-
https://sites.google.com/a/chromium.org/chromedriver/extensions

If you have an issue attempting to automate something with chrome, please log an issue with the chromedriver project instead.

I would only recommend automating plugins that you are developing. As previous comments implies, there's plenty of other tooling that will help with testing REST api's.
