### ISSUE TITLE
WebDriver lacks HTTP response header and status code methods

### ISSUE THREAD

**Issue by smatei** [SeleniumHQ/selenium#2863]
Hi,

I would like to have the status code and response headers from WebDriver.

I can see that a lot of people are voting for this:

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141

+1 vote.

Is this the right place to submit my vote?

Best Regards,
Stefan Matei

**Comment by jimevans** [comment]
This will not happen for WebDriver, as this feature is outside the scope of the project. The accepted practice is to use a proxy to capture network traffic and extract the response information from it. I'm also locking this conversation to prevent it from becoming yet another list of rants.
