### ISSUE TITLE
chrome 53 disable developer mode extensions on Selenium node browser

### ISSUE THREAD

**Issue by qaquest** [SeleniumHQ/selenium#2864]
We run Selenium tests on a grid. With Chrome 53.0.2785.143 running in the Node & using Selenium 2.53.1, noticing the popup:
"disable developer mode extensions"
Env:
Windows 7
Chrome: 53.0.2785.143
Selenium: 2.53.1
ChromeDriver: 2.24
Any advice on disabling the popup?

**Comment by lukeis** [comment]
we don't track issue with chrome / chromedriver. Those are done on the chromedriver project.

But it seems you are asking a question, please do that on the selenium-users google group -
https://groups.google.com/forum/#!forum/selenium-users
