### ISSUE TITLE
PayPal Page HTML Not Matching Displayed HTML

### ISSUE THREAD

**Issue by ericcompassion** [SeleniumHQ/selenium#2865]
## Meta -
OS:  
Windows 7 x64 SP1

Selenium Version:  
2.53.4 in use with Ruby, rspec, and capybara 

Browser:  
Tested in Chrome and Firefox

Browser Version:  
ChromeDriver 2.24 / Chrome 53.0.2785.116 / Firefox 49.0.1 with Marionette

## Expected Behavior -
Input fields with the ids of 'email' and 'password' display on the page.

## Actual Behavior -
Only part of the page is captured in Selenium

## Steps to reproduce -
Use Selenium to automate a checkout process using PayPal as the payment type.  When you reach the PayPal login page, page.html doesn't contain the "#email" and "#password" fields even though they're displayed right there on the page in the browser selenium opened using Chrome / Firefox driver.

Here's a screenshot of what it looks like in the browser:

![paypal_html_in_browser](https://cloud.githubusercontent.com/assets/22548644/19044598/3ef7ede0-8952-11e6-8f93-5ea93b1f770c.png)
  
Here's a screenshot of the HTML that I retrieved using page.html (which I saved to an HTML file which I've also attached here):

![paypal_html_in_ruby_page_source](https://cloud.githubusercontent.com/assets/22548644/19044629/5eb48602-8952-11e6-93f6-42d87d4fcab6.png)

[current_page.zip](https://github.com/SeleniumHQ/selenium/files/506684/current_page.zip)

**Comment by lukeis** [comment]
can you provide a script or a way to navigate to that page?

Also, no one (should) open a random zip file. Please don't expect us to.

**Comment by ericcompassion** [comment]
Here's a script with a very basic example:

http://pastebin.com/fSNLVe0v

Opening a zip file usually won't do any damage.  It's running anything within it.  If you're worried, simply virus scan the file before opening.  A "random" zip file attached to a bug report most likely contains contents helpful to the report...  ![Tinfoil Bro?](https://theadminzone.com/styles/default/xenforo/smilies/foilhatcg3.gif)

**Comment by twalpole** [comment]
They're not in the page, because they're in an iframe, which you need to switch into before you can interact with its content.

**Comment by ericcompassion** [comment]
Twalpole is correct.  Thanks.  I didn't know I had to specifically tell it to look in various iframes.
