### ISSUE TITLE
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible using Chrome browser 53 and Chrome driver 2.24 and Selenium 2.53.1

### ISSUE THREAD

**Issue by gkashikar** [SeleniumHQ/selenium#2867]
## Meta -
OS: 
Win 10/Win 7 

Selenium version - 
Selenium 2.53.1

Browser - 
Chrome ver =53.0.2785.116

Chrome driver 2.24

Description - login button elements are not visible using ID or Xpath

Website - https://pas.arriswifi.net/pas/start?key=Mediacom_final-99e52f9d06784dcff03b555de596632b&command=track&track=MasterProducts

On the above website I was using Selenium web driver to find login button element on google chrome using inspect element

driver.find_element_by_id("btn_signin").click()

This was working till 10/2/2016. Today 10/3/2016 when i run the program i get below error 

## Expected Behavior -
No ELEMENT ERROR

## Actual Behavior -
Traceback (most recent call last):
  File "C:\GK_eclipse_workspace\hello\Python3Udemy\Head_First_progams\MediacomTests\Test.py", line 28, in <module>
    driver.find_element_by_id("btn_signin").click()
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=53.0.2785.116)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 10.0.14393 x86_64)

## Steps to reproduce -
Download Eclipse Mars 2
Download Python 3.5.2
Download JAVA JDK 8.0_1028u , JRE 8.0_1028u 102 packages
pip install selenium

Python Code - 

from selenium import webdriver
import time

chromedriverpath="c:\Chrome_driver\chromedriver.exe"
driver= webdriver.Chrome(chromedriverpath)

print("Open Mediacom Public Wi-Fi Portal page")
    
#driver.get("https://pas.arriswifi.net/pas/start?key=Mediacom_final-08f6fda2c2a80c782036c1489a15ba03&command=track&track=MasterProducts")
driver.get("https://pas.arriswifi.net/pas/start?key=Mediacom_final-6c0df5e7694dead2c02e9092ec6c516e&command=track&track=MasterProducts")
time.sleep(2)

print("\n\nUse case1 - Do not fill any field and click Login")

#Find Username field element and don't enter username as 
driver.find_element_by_id("username").send_keys("abcde")

#Find Password field element and don't enter password
driver.find_element_by_name("password").send_keys("")

#Find Terms checkbox and don't click
#driver.find_element_by_id("terms").click()

#Find Sign in button and click it
driver.find_element_by_id("btn_signin").click()

a= driver.find_element_by_id('demo1').text
print(a)

print("\nIf Username,password field is not filled and checkbox is not clicked the error displayed is = ", a)

---- 
Run Program and observe output

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
