### ISSUE TITLE
ExpectedConditions.presenceOfElementLocated: throws NoSuchElementException

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#2869]
I tried writing a simple test that would first simply wait for the presence of an element on the page but the first check using a `FluentWait<WebDriver>` throws `NoSuchElementException` (I expect no such exception to be thrown):

```java
new FluentWait(webDriver)
        .withTimeout(5, TimeUnit.MINUTES)
        .until(ExpectedConditions.presenceOfElementLocated(By.name("zipCode")))
```

I looked in [ExpectedConditionsTest.java](https://github.com/SeleniumHQ/selenium/blob/92cf77420dbc25a01a66dfe1d3b2572029a5424a/java/client/test/org/openqa/selenium/support/ui/ExpectedConditionsTest.java) but didn't find any tests for `ExpectedConditions.presenceOfElementLocated`. :disappointed: 

I then checked in [ExpectedConditions.java](https://github.com/SeleniumHQ/selenium/blob/92cf77420dbc25a01a66dfe1d3b2572029a5424a/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java) and it appears to catch the exception at one point but then re-throw it unlike `ExpectedCondtiions.presenceOfNestedElementLocatedBy`.

**Comment by lukeis** [comment]
You should be using WebDriverWait class instead of FluentWait.

If you choose to use FluentWait then you need to add `.ignoring(NotFoundException.class)`

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/WebDriverWait.java#L74

**Comment by lukeis** [comment]
note that NoSuchElement extends NotFound
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/NoSuchElementException.java#L24

**Comment by mfulton26** [comment]
I was not aware of `WebDriverWait`. Thank you. It looks like exactly what I was looking for.
