### ISSUE TITLE
Ruby 3.0.0.beta4 release

### ISSUE THREAD

**Issue by abraham-chan** [SeleniumHQ/selenium#2871]
It looks like beta4 for the ruby bindings [has been released](https://github.com/SeleniumHQ/selenium/commit/c92b7e29bd02009c4c6e2495d1d30b86d7948d0d), but I don't see it on [rubygems](https://rubygems.org/gems/selenium-webdriver/versions).

@titusfortner

**Comment by titusfortner** [comment]
Huh, I was certain I'd done this. Thanks for bringing it to my attention.
