### ISSUE TITLE
How to initiate Firefox Driver using 3.0 beta 4?

### ISSUE THREAD

**Issue by SrinivasanTarget** [SeleniumHQ/selenium#2872]
## Meta -
OS:  OSX

Selenium Version:  3.0 beta 4

Browser:  Firefox 49.0.1

Browser Version:  

## Expected Behavior - 

Not able to create object of FirefoxDriver in 3.0 beta 4 whereas the same works fine in 3.0 beta 3.(GeckoDriver path is set)

## Actual Behavior - 

I could not find the FirefoxDriver class in latest selenium beta version

Do we have any code sample to create FirefoxDriver object and set profile as well for GeckoDriver?

@lukeis Can you please help on this?

**Comment by lukeis** [comment]
How are you including the library? Maven or jar dependencies? Which ones explicitly?

**Comment by SrinivasanTarget** [comment]
@lukeis Using Maven,

```
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.0.0-beta4</version>
</dependency>
```

**Comment by SrinivasanTarget** [comment]
<img width="846" alt="screen shot 2016-10-04 at 9 56 14 pm" src="https://cloud.githubusercontent.com/assets/8896549/19082805/53346096-8a7d-11e6-84ed-6ac8fd79d135.png">

@lukeis please let me know if you need any more details

**Comment by lukeis** [comment]
I can't reproduce your issue. The org.seleniumhq.selenium:selenium-firefox-driver:jar:3.0.0-beta4 artifact does contain the FirefoxProfile.

Feel free to follow up on the selenium-users google group to troubleshoot your problem. You can open a new issue when you have a way for someone to reproduce the problem.
