### ISSUE TITLE
 load strategy unstable not working  selenium-driver 3.0.0-beta-2

### ISSUE THREAD

**Issue by kyle-ssg** [SeleniumHQ/selenium#2873]
## Meta -
OS:  OSX
Selenium Version:  3.0.0-beta-2
Browser:  Firefox 49.0.1

## Expected Behavior -
``driver.wait(until.elementLocated(By.className(`` should resolve as soon as it's visible.

## Actual Behavior -
driver.get resolves before any driver.waits

## Steps to reproduce -
```
    var profile = new firefox.Profile();
    profile.setPreference('webdriver.load.strategy', "unstable");
    var options = new firefox.Options().setProfile(profile);
    var driver = new firefox.Driver(options);

driver.get('https://google.com')
        .then(function () {
            console.log('Loaded')
        });

driver.wait(until.elementLocated(By.className('example')), 5000)
        .then(function () {
            console.log('Element found')
        });
```

**Comment by jleyba** [comment]
In your example, `driver.get()` will always resolve before `driver.wait()`. In fact, the `driver.wait()` won't even start executing until after driver.get resolves (see [promise manager](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html) docs)

**Comment by kyle-ssg** [comment]
@jleyba ```webdriver.load.strategy:"unstable"``` is intended to prevent this behaviour and actually does so successfully when used in conjunction with Firefox v0.46.0. I've settled for keeping this version of firefox on my server.

**Comment by jleyba** [comment]
Ok, to be clear: you expect the console output to be

```
Element found
Loaded
```

That will never happen. The promise returned by `driver.get()` will resolve when the command has completed, which is dependent on when webdriver thinks the page has "loaded", which depends on the load strategy.

The console output will always be

```
Loaded
Element found
```

**Comment by kyle-ssg** [comment]
Ah my apologies, you are correct. Loaded would always log out first in my example. Achieving my expected outcome was more about tricking the driver to resolve loaded earlier than the standard strategy.

As mentioned above using Firefox <= 46 does adhere to the webdriver.load.strategy preference solved my issue.
