### ISSUE TITLE
htmlunit c# is not working

### ISSUE THREAD

**Issue by heyitsmesuraj** [SeleniumHQ/selenium#2875]
Code
[Test]
Public Void Test()
{
IWebDriver driver = new RemoteWebDriver(DesiredCapabilities.HtmlUnitWithJavaScript());
driver.Navigate().GoToUrl("https://www.google.com.np/");
string pageInfo = driver.PageSource;
}

the value present in pageInfo 
<?xml version="1.0" encoding="UTF-8"?>

expected output:-
comple XML doM of the webpage

Selenium version:2.53.1
HtmlUnit version:2.21
OS:windows 7
Browser:htmlunit driver
dot net dll

Inorder to run selenium I use:
java -cp selenium-server-standalone-2.53.1.jar;htmlunit-driver-standalone-2.21.jar org.openqa.grid.selenium.GridLauncher -log selenium.log

I have also attached log file
[selenium.txt](https://github.com/SeleniumHQ/selenium/files/509128/selenium.txt)

**Comment by shs96c** [comment]
Wow. How did we miss that? Fixed in a60f0eea767d2e5c7d4cb8a8b255f90c9053f303
