### ISSUE TITLE
 How to solve "Trying to get property of non-object in WebDriverBase.php" for Selenium application in php 

### ISSUE THREAD

**Issue by Pinnacle0401** [SeleniumHQ/selenium#2878]
## Meta -
OS:  Windows 7 
Selenium Version:  2.53.0, IDE, 

Browser:   Internet Explorer  Firefox Chrome

## Actual Behavior -
Trying to get property of non-object in C:\wamp64\www\testApp\phpwebdriver\WebDriverBase.php

## Steps to reproduce -

`
use Ddeboer\Tesseract\Tesseract;
require_once "phpwebdriver/WebDriver.php";
require_once "Ddeboer/Tesseract/Tesseract.php"; 
// Run Selenium server
$output = shell_exec('java -jar "selenium-server-standalone-2.53.1.jar"');

//Load selenium webdriver
$webdriver = new WebDriver('localhost', 4444);
$webdriver->connect('firefox');  

//Get google content
$webdriver->get("http://www.google.com");

//Get search element
$search= $webdriver->findElementsBy(LocatorStrategy::name,  #"q");`

**Comment by lukeis** [comment]
Sorry, we don't support php here at all. You should log a bug with the php selenium client project you are using
