### ISSUE TITLE
Java.Net.ConnectionException  in IE Driver

### ISSUE THREAD

**Issue by SumathiChn** [SeleniumHQ/selenium#2879]
## Meta -
OS:  Windows 7
Selenium Version:  2.52
Browser:  IE 11

ISSUE : While clicking a link in IE, opens a PDF file in secondary window.
Selenium identifies the driver.getcurrenturl() method, after switching to the new driver.
But no element is getting identifed in the pdf file.
   I have tried apache pdfbox to interact with pdf, but getting Java.Net.ConnectionException while trying to open InputStream and connect.

Here is the code -

String strParentWindow1 = driver.getWindowHandle();
                Object[] strAllWindows = driver.getWindowHandles().toArray();
                int intTotalWindows = strAllWindows.length;
                for (int var = 0; var < intTotalWindows; var++) {
                    String strWindowAct = "" + strAllWindows[var];
                    driver.switchTo().window(strWindowAct);
                }

URL url = new URL(strURL);
BufferedInputStream file = new BufferedInputStream(url.openStream());  //Exception occurs here.
 PDFParser parser = new PDFParser(file);

please help

**Comment by ddavison** [comment]
closing we can't do anything about this.  Selenium doesn't automate PDF documents, and the code you provide - is not a problem with Selenium.  maybe try the [selenium-users group](https://groups.google.com/forum/#!forum/selenium-users)
