### ISSUE TITLE
createTempDir Problem

### ISSUE THREAD

**Issue by anonmu07** [SeleniumHQ/selenium#2883]
## Meta -

OS:  
Windows 10 x64
Selenium Version:  
3.0.0-beta4 + geckodriver
Browser:  
Firefox 49.0.1
## Expected Behavior -

can run ant build
## Actual Behavior -

ant build has error

> org.openqa.selenium.WebDriverException: Unable to create temporary file at C:\WINDOWS
> Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:30:04 -0700'
> System info: host: '_', ip: '_', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
> Driver info: driver.version: unknown
>     at org.openqa.selenium.io.TemporaryFilesystem.createTempDir(TemporaryFilesystem.java:99)
>     at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:416)
>     at org.openqa.selenium.firefox.FirefoxProfile.toJson(FirefoxProfile.java:386)
>     at nm_tracking.tracking_framework.NetmindTrackerTest.getBrowserDriver(NetmindTrackerTest.java:278)
>     at nm_tracking.tracking_framework.NetmindTrackerTest.setUp(NetmindTrackerTest.java:43)
> java.lang.NullPointerException
>     at nm_tracking.tracking_framework.NetmindTrackerTest.tearDown(NetmindTrackerTest.java:52)

I have tried to change temp folder as following:
-Djava.io.tmpdir=C:\temp
But the result is still the same, how can I set this folder?

**Comment by asevans48** [comment]
The same issue happens in Linux

**Comment by martingollogly** [comment]
Are you sure c:\temp exists?

Here is the code that's trying to create the temporary folder. It expects the folder to already exist.

https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/java/client/src/org/openqa/selenium/io/TemporaryFilesystem.java L80

The stack trace above looked like it was going to C;\WINDOWS and then I expect because it wasn't in quotes that it chopped off the rest of the path

**Comment by asevans48** [comment]
I have a folder on Linux that I specify through path and it is not used. this is definitely a multi-platform bug.

**Comment by cgoldberg** [comment]
@asevans48 @anonmu07 
post a minimal code snippet that reproduces this

**Comment by anonmu07** [comment]
Here is my sample project:
https://github.com/anonmu07/FirefoxSeleniumTest

**Comment by barancev** [comment]
It's configuration issue, Selenium uses standard Java means to create temp files in the system directory for temp files.
