### ISSUE TITLE
Selenium Slowdown with Multiple Tests and the Need to avoid Grid

### ISSUE THREAD

**Issue by asevans48** [SeleniumHQ/selenium#2884]
## Meta

OS:  Linux Ubuntu Xenial 16.04
RAM: 11g
CPU: 8 cores 
Code Base: Scala/Java
Hardware: Dell Laptop
Browser: Firefox 45 ESR and Firefox 49.0 and Chrome 53+
Selenium: 3.0 beta 4
## Update

I may have discovered where the issue lies using chrome driver. 

The page hangs when I call in Scala or Java:

var options = new ChromeOptions()
...
options.addArguments("----proxy-server=proxy:port") // the only way I can get proxies to work is with only options
browser.get("https://sors.doc.state.ok.us/svor/f?p=119:1:")

I then proceed to perform a  search and loop through the terms. It takes about 8 hours for complete and irreversible destruction to occur. With no OOM, way less then the given heap size reported by htop, and 25 % CPU, the error is likely in part of the pipeline (See my update).

The same error happens without a proxy. I am running with both incognito and non-incognito browsers as well as practically no cache size and most memory related features disabled. I tried with just a default chrome options as well.

The output stalls at the following:

Starting ChromeDriver 2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3) on port 19899
Only local connections are allowed.
Oct 12, 2016 1:37:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 12, 2016 1:37:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

With xvfb, I cannot see anything but when I run the 'test' or crawl without xvfb, the tool is stuck in an infinite loop trying to obtain the page data: before getting the specified url. Firefox stalls in the same way as well.

I set a pageLoadTimeout but never see an error for this. The timeout is between 30 and 240 seconds but never appears. At times, however, it will, and the tests can continue. 
## Expected Behavior

Running tests and crawls for thousands of terms completes using a rotating list of proxies utilizing xvfb. The specified temp directory is used. Not seeing a million empty GeckoChildDriverCrash files.
## Actual Behavior

A general slowdown occurs, freezing the system after 100 or so tests, 1-3 at a time, with rotating proxies no proxies. The specified temp directory is never used for Firefox files whether they are for the rust profiles or crash logs. I see one crash log per source which is manageable via rm -rf in the /tmp folder.

No java heap space leak was detected as memory usage denoted from the jvisualvm was consistently near 1g and CPU usage only maxed out around 70% for 3 proceses and 25% for 1 which is much better than for the previous Selenium version. Luckily, the files in /tmp now delete reliably but when things crash the number of rust profiles grows as I cannot just delete anything in /tmp with multiple jobs running from time to time. 
## Steps to reproduce
- Set xmx at 5g of which 2g is the most utilized even if I toy with heap space percentages.
- Fork a new slave process up to a specified number or the number of CPU cores with xvfb-run -a [options] jar [jar] [args] and setup the process
- Setup a new browser with proxy set in capabilities and a firefox profile with proxy and performance enhancing options such as no color management and no update downloading. I checked the options and everything sets up fine. Use the path to the desired /tmp file from the args. I enable webgl via firefox options to avoid certain errors apparently related to xvfb but this does not seem to be a problem as the same issue happens when I do not enable webgl. The browser is set to not cache anything. All SSL certificates are normally allowed with expect untrusted certifications sometimes set.
- Create a firefox browser using the DesiredCapabilities
- Run through the system using Apache Http Components where possible if this is a crawl or logging output for QA. Run javascript as necessary. The tests / scrapes attain 500 pages on average.
- exit with the quit() command
- clean out the GeckoChildDriver crash logs from /tmp, return exit status and code via Future to the main loop

I manage the processes in Scala using Futures and execute with Apache Command Exec so I can set a timeout. The processes work fine at first but the performance degrades over time.

The overall goal is to be able to incorporate everything with Apache Mesos to develop a large test system as well as a large streaming Acquisition + Scrape System. My selenium based acquisition code is available at https://github.com/asevans48/GoatGrazerSelenium where a general overview of the entire project can be found. The code works and can be used to solve any underlying problems if you wish as it is under a GPL license.

As there is only an empty crash log and no errors, there really is nothing to attach. The only useful information would be that crawlers and testers slow down to 1/100 of the time they first took despite no caching, decent network connectivity, and no detectable Java heap space problems.

Overall, great job as I hate messing with the very buggy JavaFX and increasingly outdated webkit of PyQt but this problem is really killing the progress made with the tool for me. I did see an eventual inclusion of a web engine in Qt though.

**Comment by diemol** [comment]
Apologies for the poor handling of this issue on our side. As so much time has passed (and the linked repo does not exist), perhaps this is not a valid issue anymore.

In any case, if the issue is still present, please create a new one and fill out the template completely, issues with reproduction scenarios providing simple automation scripts are preferred instead of narrative descriptions.
