### ISSUE TITLE
ChromeOptions Not Being Used

### ISSUE THREAD

**Issue by asevans48** [SeleniumHQ/selenium#2894]
OS:  Ubuntu Xenial 16.04
Selenium Version:  3 beta 4
Browser:  Chrome 53

I notice that I can set google chrome options from the command line such as --app=http://mysite.com but when I use addArguments with ChromeOptions and even with a DesiredCapabilities object, the arguments are ignored. Is there a way to fix this? This is with all command line options and not just those like --disable-images which is apparently flat out broken.

**Comment by lukeis** [comment]
For user questions please ask on our google group:
https://groups.google.com/forum/#!forum/selenium-users

For chromedriver issues, please log them with the chromedriver project and provide code to reproduce the issue.
https://bugs.chromium.org/p/chromedriver/issues/list
