### ISSUE TITLE
Issue while compiling with java 8 the v.3.0.0-beta4

### ISSUE THREAD

**Issue by dissennatore** [SeleniumHQ/selenium#2897]
## Meta -
OS:  Android

Selenium Version:    3.0.0-beta4

Browser:  -

Browser Version:  

## Steps to reproduce -

Hi, I've got a problem that has shocked me, and I think it's a bug because I should've done all well:
Basically, as we know since v3.0.0-beta1 it's necessary java 8; well, if I try to compile it (Android Studio, last release [2.2]) I got a message error and also it says me to put a target/source compatibility to java 1.7; I mean, what? I've got upset, why I got an error because of compiling with java 8 when I must use it?

For more details, here's the problem well described: http://stackoverflow.com/questions/39806585/compiling-compatibility-issue-external-libraries

Hope that I helped, or at least if I've done something wrong hope that you'll help me :)

**Comment by lukeis** [comment]
Sorry, your issue lies with android and not with selenium. Also you shouldn't be trying to include selenium in an android app. If you're trying to test with selenium, then make a separate project in your workspace for the selenium tests that use the standard java 8 jdk and not a jdk for android
