### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by shipragarg012** [SeleniumHQ/selenium#2901]
This is my code:
package preventive_maintenance;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class WOWF1PRG {
	public static void main(String[] args)throws Exception {
	     
		 WebDriver driver;
		    //String baseUrl;
		    //driver = new FirefoxDriver();
		    String exePath = "C:\\Users\\shipra\\Download\\chromedriver.exe";
			System.setProperty("webdriver.chrome.driver", exePath);
		    driver=new ChromeDriver();
		   // baseUrl = "http://maximo76:9080/";
		    driver.manage().timeouts().implicitlyWait(300, TimeUnit.SECONDS);
		    driver.manage().window().maximize();
	driver.get("http://10.0.0.14:9080/maximo/webclient/login/login.jsp");
	// Enter UserName and Password
	 driver.findElement(By.id("username")).clear();
	    driver.findElement(By.id("username")).sendKeys("KTQCPLANA");
	    driver.findElement(By.id("password")).clear();
	    driver.findElement(By.id("password")).sendKeys("password");
	    // Click on 'Sign In' button
	    driver.findElement(By.id("loginbutton")).click();
	    
	    // Goto WOTRACK application
	    driver.findElement(By.id("FavoriteApp_WOTRACK")).click();
	    // Click new workorder,Supervisor,Worktype
	    
	    driver.findElement(By.id("toolactions_INSERT-tbb_image")).click();
	    System.out.println("after 1");
	    Thread.sleep(1000);
	    driver.findElement(By.id("mad3161b5-tb2")).click();
	    Thread.sleep(1000);
	    driver.findElement(By.id("m7b0033b9-img")).click();
	    Thread.sleep(1000);
	    System.out.println("after 2");  
	    driver.findElement(By.id("LOCATIONS_locations0_a_tnode")).click();
	    Thread.sleep(1000);
	    System.out.println("after 2.1");
	    driver.findElement(By.id("lookup_page1_tdrow_[C:0]_ttxt-lb[R:1]")).click();
	    Thread.sleep(1000);
	    System.out.println("after 2.2"); 
	    driver.findElement(By.id("mb2eb834-img")).click();
	    Thread.sleep(1000);
	    System.out.println("after 3");
	    driver.findElement(By.id("NORMAL_normal0_a_tnode")).click();
	    Thread.sleep(2000);
	    System.out.println("after 3.1");
	    driver.findElement(By.id("lookup_page1_tdrow_[C:0]_ttxt-lb[R:7]")).click();
	    Thread.sleep(2000);
	    System.out.println("after 3.2");
	    driver.findElement(By.id("me2096203-img")).click();
	    Thread.sleep(2000);
	    System.out.println("after 4.1");
	    driver.findElement(By.id("lookup_page1_tdrow_[C:0]_ttxt-lb[R:2]")).click();
	    Thread.sleep(1000);
	    System.out.println("after 4.2");
	    driver.findElement(By.id("ROUTEWF__-tbb_image")).click();
	    System.out.println("after 5");
	    Thread.sleep(1000);
	    driver.findElement(By.id("m4280cc7e-img")).click();
	    System.out.println("after 5.1");
	    driver.findElement(By.id("menu0_WOWF1PRG_OPTION_a_tnode")).click();
	    System.out.println("after 5.2");
	    Thread.sleep(1000);
	    driver.findElement(By.id("m7ca62696-pb")).click();
	    System.out.println("after 5.3");
	    Thread.sleep(1000);
	    driver.findElement(By.id("ROUTEWF__-tbb_image")).click();
	    System.out.println("after 7");
	    Thread.sleep(1000);
	    driver.findElement(By.id("mc3331876-pb")).click();
	    System.out.println("after 8");
	    driver.findElement(By.id("mc1493e00-rb")).click();
	    System.out.println("after 9");
	    Thread.sleep(1000);
	    driver.findElement(By.id("m37917b04-pb")).click();
	  //for close the browser
	    //driver.quit();
	   System.out.println("successful");
	}
}
This is selenium error:
Starting ChromeDriver 2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf) on port 9197
Only local connections are allowed.
Oct 10, 2016 7:10:14 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 10, 2016 7:10:15 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
after 1
after 2
after 2.1
after 2.2
after 3
after 3.1
after 3.2
after 4.1
after 4.2
after 5
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (516, 278). Other element would receive the click: <div id="wait" width="100%" height="100%" class="wait" style="position: absolute; top: 0px; left: 0px; height: 666px; width: 1366px; display: block; cursor: wait;">...</div>
  (Session info: chrome=53.0.2785.143)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 89 milliseconds
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'ICDVM', ip: '10.0.0.11', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf), userDataDir=C:\Users\ADMINI~1\AppData\Local\Temp\scoped_dir16388_948}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.143, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 193050548a4ce328635b8eb6ef3b718d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:284)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at preventive_maintenance.WOWF1PRG.main(WOWF1PRG.java:66)

**Comment by lukeis** [comment]
This is expected. Please reach out to the selenium-users google group for help. I would recommend removing the Thread.sleeps and adding explicit waits after each click.

**Comment by shipragarg012** [comment]
How to use explicit in this code?

**Comment by ddavison** [comment]
[*explicit waits*](http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp).

please refer to the [selenium-users group](https://groups.google.com/forum/#!forum/selenium-users) for any further questions.  thanks!
