### ISSUE TITLE
Geckodriver fails to establish connection with selenium server if the test has failed for the first time

### ISSUE THREAD

**Issue by sri85** [SeleniumHQ/selenium#2907]
**OS:**  
**MAC (El Capitan) Version 10.11.6**
**Browser:  Firefox** 
Selenium Server Version: 2.52
Selenium python bindings version: 2.53.6

Browser Version:  
Version :49.0.1

## Expected Behavior -
Tests must run any number of times

## Actual Behavior -
After the first run (after it failed for the first time) any subsequent run the test fails to connect to the remote webdriver . The only way to reestablish the connection is by restarting the selenium server.

You can find the stacktrace here:
https://gist.github.com/sri85/c80fb114f790f8d2ee933b0569ed579b

## Steps to reproduce -
1. Start the selenium standalone server.
2. Run the test 👉  https://gist.github.com/sri85/e69bd55b6d981c23d1043431c2bab821
3. The test fails on purpose for the first time.
4. Run the same test again.

**Comment by lukeis** [comment]
you should be calling driver.quit() instead of close() at the end. But the server should allow you do do it multiple times.

Also, are you really using 2.52 standalone? I can't imagine that would even work with geckodriver. Please try again using 3.0.0-beta4

**Comment by lukeis** [comment]
I'm unable to reproduce the issue using 3.0.0-beta4, the server happily runs multiple instances of Firefox with GeckoDriver.

**Comment by sri85** [comment]
@lukeis I tried with `driver.close()`, and i was still able to reproduce the issue. i had a chat with @AutomatedTester as well on the same issue in the IRC  . Is there a reason that i need to use `3.0.0 beta4` when the changelog does not even mention it .  believe that this still an issue .

**Comment by cgoldberg** [comment]
> I tried with driver.close()

use `driver.quit()`.

**Comment by sri85** [comment]
Looks something similar https://github.com/mozilla/geckodriver/issues/270
