### ISSUE TITLE
NullPointerException when starting node

### ISSUE THREAD

**Issue by Noxxys** [SeleniumHQ/selenium#2909]
## Meta -
OS:  Windows 10 (virtual machines)
Selenium Version:  3.0.0 beta4
Browser:  N/A
Browser Version:  N/A

## Expected Behavior - 
able to start java -jar selenium-server-standalone-3.0.0-beta4.jar -role node -nodeConfig node.json

## Actual Behavior - 
Exception just after "Selenium Grid node is up and ready to register to the hub" and the usage appear:
java.lang.NullPointerException
at org.openqa.grid.internal.utils.SelfRegisteringRemote.startRegistrationProcess(SelfRegisteringRemote.java:175)
at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:271)
at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:86)

## Steps to reproduce -
hub.json:
{
	"port": 4444,
	"newSessionWaitTimeout": -1,
	"throwOnCapabilityNotPresent": true,
	"timeout": 1200000,
	"browserTimeout": 120000
}

node.json:
{
	"capabilities":
	[
		{
			"browserName": "firefox",
			"maxInstances": 10,
			"seleniumProtocol": "WebDriver"
		}
	],
	"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
	"maxSession": 10,
	"timeout": 1200000,
	"browserTimeout": 120000,
	"port": 5555,
	"hub": "http://IP_OF_HUB_MACHINE:4444"
}

Run this on 1st machine: 
java -jar selenium-server-standalone-3.0.0-beta4.jar -role hub -hubConfig hub.json

Run this on 2nd machine:
java -jar elenium-server-standalone-3.0.0-beta4.jar -role node -nodeConfig node.json

NOTE: this was working fine with Selenium 2.53.0, I just altered node.json to remove configuration { ... } as advised in the docs.

**Comment by Noxxys** [comment]
Problem solved, it was because "register": true was missing from node.json.
In my opinion, it should be the default, or it should at least not crash on a null pointer exception. I'm not closing this bug because the exception should be handled.

**Comment by lukeis** [comment]
thanks for the excellent bug report!
