### ISSUE TITLE
UnsupportedCommandException: POST /session/<sessionid>/log with Firefox

### ISSUE THREAD

**Issue by ronvanpol** [SeleniumHQ/selenium#2910]
## Meta -
OS: Windows 10
Selenium Version:  3.0.0-beta4
Browser:  Firefox
Browser Version:  48.0.2

## Expected Behavior -
Accessing the Firefox browser log

## Actual Behavior -

UnsupportedCommandException thrown

## Steps to reproduce -
// init the firefox driver with browser logging preferences
LoggingPreferences logs = new LoggingPreferences();
logs.enable(LogType.BROWSER, Level.ALL);
DesiredCapabilities desiredCapabilities = DesiredCapabilities.firefox();
desiredCapabilities.setCapability(CapabilityType.LOGGING_PREFS, logs);
WebDriver lDriver = new FirefoxDriver(desiredCapabilities);

...

// get the browser log entries
LogEntries logEntries = aDriver.manage().logs().get( LogType.BROWSER );

The last line throws an UnsupportedCommandException:

org.openqa.selenium.UnsupportedCommandException: POST /session/25891b0f-1f08-453a-89f9-827ab63c0ebd/log did not match a known command
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:30:04 -0700'
System info: host: 'PC-RON', ip: '169.254.80.80', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver

**Comment by lukeis** [comment]
The logging api isn't yet apart of the (w3c spec)[https://w3c.github.io/webdriver/webdriver-spec.html]. It has been deferred to level 2 and will be tracked here: https://github.com/w3c/webdriver/issues/406

GeckoDriver is following spec, so don't expect Mozilla to implement it until it is defined in the spec.
