### ISSUE TITLE
Selenium raises uninformative error when connection fails.

### ISSUE THREAD

**Issue by emil-petersen** [SeleniumHQ/selenium#2913]
When using Selenium with Appium, I received an error message which I found very uninformative. What had happened is that my code had a race condition. A script manually started the Appium server, and then immediately after, some tests ran using it. Raising an error here makes sense, and the fault was not with Selenium.

However, this is the error Selenium raised:

`INFO:remote_connection.py::__init__:Could not get IP address for host: 127.0.0.1`

It seems to be raised from here: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L189

I think this message is very uninformative. There was no difference in behaviour when substituting `127.0.0.1` for `localhost`. 

Reporting the above message when that makes sense is fine, however, in this case, since the issue is that Selenium couldn't connect on the port and IP, the error message should indicate that. 
## Meta -

OS:  
OSX Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
Selenium Version:  
2.53.6
Browser:  
N/A
## Expected Behavior -

An error message indicating that the connection is failed is raised, which helps a user to understand what the problem is.
## Actual Behavior -

Selenium raises the above error, which seems quite misleading.
## Steps to reproduce -

Create an Appium server instance, and connect to it immediately (within 1 second).

Thank you for your consideration.

**Comment by cgoldberg** [comment]
> It seems to be raised from here: 
>  https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/remote/remote_connection.html

that doc is outdated.. use git.

**Comment by emil-petersen** [comment]
Alright. Here is the link to where the message seems to be raised: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/remote_connection.py#L189

**Comment by mwangikinuthia** [comment]
Most likely you have changed your /etc/hosts file to a domain or something else from the default 'localhost'.

**Comment by emil-petersen** [comment]
@mwangikinuthia Yes, I have. The issue was solveable, what I perceive as the underlying issue is that the error was not a good indicator of what was going wrong.
