### ISSUE TITLE
"self" instead of "this" in remote-selenium-commandhandlers.js, line 376

### ISSUE THREAD

**Issue by shrodi** [SeleniumHQ/selenium#2916]
## Meta -

Selenium Version:  
 IDE 2.9.1.1-signed

There's a bug in selenium-ide\chrome\content\remote-selenium-commandhandlers.js: line 376 should be `this.result = arg;` instead of `self.result = arg;`. The latter generates an error whenever we use getEval with WebDriver Playback.

A diff file is attached.
[remote-selenium-commandhandlers.js.diff.txt](https://github.com/SeleniumHQ/selenium/files/528070/remote-selenium-commandhandlers.js.diff.txt)

**Comment by lukeis** [comment]
You would also need to bind that function to 'this' where it's defined. Or you could create the self variable like is done in the previous if clause. 

Would be nice to make a pull request for this.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
