### ISSUE TITLE
How much content can driver.page_source contain?

### ISSUE THREAD

**Issue by playwolf719** [SeleniumHQ/selenium#2917]
Considering that the url that I want to crawl is a single-page-web-app, I want to know How much content can driver.page_source contain? is 10GB ok? Is there any other solution for this situation?
![image](https://cloud.githubusercontent.com/assets/6240382/19376322/74ec890e-920f-11e6-9175-e0351c1a2106.png)

**Comment by playwolf719** [comment]
@andreastt @AutomatedTester @barancev Thxs

**Comment by lukeis** [comment]
you're most certainly going to run out of memory trying to load a 10GB page source that way. Also, the browser itself is likely to crash with that much data in the DOM. At least become completely unresponsive.

We don't offer a solution to this directly, if you know the page you are trying to load is massive you're going to need to come up with a different solution. 

I would recommend asking your question on the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users

Please log here only concrete issues with example reproducible test cases for us that are actionable.

**Comment by andreastt** [comment]
Luke is correct. You will experience OOM issues with the browser first, and browsers generally don’t offer any compelling solutions to this other than the “a script in this document has become unresponsible, do you wish to kill it?” dialogue.

**Comment by playwolf719** [comment]
@lukeis @andreastt Thx. guys, I figure out other way to solve the issue.
