### ISSUE TITLE
Ruby: `undefined method `executable_path='` for webdriver 3.0.0

### ISSUE THREAD

**Issue by ShockwaveNN** [SeleniumHQ/selenium#2919]
## Meta -
OS:  Ubuntu 16.10

Selenium Version:  ruby 3.0.0

Browser:  Chrome

Browser Version:  Version 54.0.2840.59 

## Steps to reproduce -
[Download](http://chromedriver.storage.googleapis.com/index.html?path=2.24/) latest chromedriver (2.24) and place it to /tmp/chromedriver
Create rb file with this content and run it:
```
require 'selenium-webdriver'
puts Gem.loaded_specs['selenium-webdriver'].version
Selenium::WebDriver::Chrome::Service.executable_path = '/tmp/chromedriver'
@driver = Selenium::WebDriver.for :chrome
```
## Expected Behavior -
On selenium-webdriver 2.53.4
```
2.53.4
```
Browser started
## Actual Behavior -
On selenium-webdriver 3.0.0
```
3.0.0
undefined method `executable_path=' for Selenium::WebDriver::Chrome::Service:Class (NoMethodError)
```

**Comment by ShockwaveNN** [comment]
Found the reaseon
In https://github.com/SeleniumHQ/selenium/commit/7652b576f3fd2564bd40d70573e4b49c56c3baaf#diff-f16d501db57640049fae197bc5610fd9
there was introduced warn about deprectation of `executable_path`
But on next day https://github.com/SeleniumHQ/selenium/commit/5e7041cd3ea0a388257804f6b0556c319aa65c28#diff-f16d501db57640049fae197bc5610fd9 this deprecation warn was removed at all.
I found this very strange, cause according to https://seleniumhq.wordpress.com/2016/10/13/selenium-3-0-out-now/ webdriver 3.0 shouldn't broke anything for users of webdriver 2

**Comment by titusfortner** [comment]
If you look at the [source code from 2.53](https://github.com/SeleniumHQ/selenium/blob/selenium-2.53.0/rb/lib/selenium/webdriver/chrome/service.rb#L24-L26), you'll see that the entire `Chrome::Service` class is marked private api, and is only intended to be used internally by other portions of the Selenium code. That is why the deprecation notice was removed as unnecessary; that code was not intended to be in users' code in the first place.

As you found, the correct public facing API which has not been changed  is `Selenium::WebDriver::Chrome.driver_path`

Thanks for filing the issue and let us know if you come across any more problems.
