### ISSUE TITLE
JS client no longer connects to an already launched standalone server

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#2921]
OS:  Windows 8.1
Selenium Version:   standalone server 3.0.0
Client: JavaScript selenium-webdriver@3.0.0-beta-3
Browser:  Chrome

For an instance of the standalone server launched with:

```shell
java -Dselenium.LOGGER.level=INFO -jar selenium-server-standalone-3.0.0.jar
```

Running this code :

```js
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder()
  .forBrowser('chrome')
  .usingServer('http://127.0.0.1:4444/wd/hub')
  .build();
```

Raise this exception:

```js
selenium-webdriver\lib\promise.js:2291
        throw error;
        ^

Error: Server terminated early with status 1
    at Error (native)
    at selenium-webdriver\remote\index.js:255:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (selenium-webdriver\lib\webdriver.js:366:24)
    at Driver (selenium-webdriver\chrome.js:716:38)
    at selenium-webdriver\index.js:86:17
    at Builder.build (selenium-webdriver\index.js:540:16)
    at Object.<anonymous> (suite.js:7:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

It looks like the client is trying to launch the standalone server where it should be connecting the server that is already launched.

The server doesn't show any connection attempt:

```
INFO - Selenium build info: version: '3.0.0', revision: '350cf60'
INFO - Launching a standalone Selenium Server
INFO::main: Logging initialized @409ms
INFO - Driver class not found: com.opera.core.systems.OperaDriver
INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
INFO - Driver class not found: com.opera.core.systems.OperaDriver
INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WI
N8_1
INFO:osjs.Server:main: jetty-9.2.15.v20160210
INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@15be6bb{/,null,AVAILABLE}
INFO:osjs.ServerConnector:main: Started ServerConnector@461048{HTTP/1.1}{0.0.0.0:4444}
INFO:osjs.Server:main: Started @660ms
INFO - Selenium Server is up and running
```

Note that I can successfully connect to the server with the Python client (3.0.0):

```python
from selenium import webdriver
capabilities = webdriver.DesiredCapabilities.CHROME
driver = webdriver.Remote("http://127.0.0.1:4444/wd/hub", desired_capabilities=capabilities)
```

**Comment by jleyba** [comment]
What environment variables do you have set? Specifically, is `SELENIUM_REMOTE_URL` or `SELENIUM_SERVER_JAR` set?

**Comment by florentbr** [comment]
@jleyba, yes I had the `SELENIUM_SERVER_JAR` environment variable defined.

I found out that the builder ignores the remote URL from the builder if the environment has the `SELENIUM_SERVER_JAR` variable.

It's kind of weird to override a behavior with an environment variable when the behavior is explicitly requested by the builder. Shouldn't it be the opposite :
* Take the url from `SELENIUM_REMOTE_URL` if the remote URL is not defined by the builder
* Take the path from `SELENIUM_SERVER_JAR` if the path is not defined by the builder

Note that it differs from the behavior of the other clients. So even though it's by design, I still think it's an issue.

**Comment by jleyba** [comment]
The overrides are working as expected and are right there in the [documentation](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/index.js#L97) (also [online](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Builder.html)):

```
/**
 * Creates new {@link webdriver.WebDriver WebDriver} instances. The environment
 * variables listed below may be used to override a builder's configuration,
 * allowing quick runtime changes.
```

If you want to ignore the environment variables and only use what is set through the API, call `disableEnvironmentOverrides()`.

Yes, this differs from the other clients b/c none of the other clients provide a builder interface
