### ISSUE TITLE
Actions.sendKeys(CharSequence[]) function takes only CharSequence[] and not a simple String object

### ISSUE THREAD

**Issue by arpit-agarwal91** [SeleniumHQ/selenium#2922]
## Meta -
OS:  

Selenium Version:  

/*Why does sendKeys function under Actions class , does not have a sendKeys function implementation that takes String object as input ?
Alternate solution is mentioned below, please recommend if it can contribute.*/

 public Actions sendKeys(String stringToBeSent) {
  CharSequence keysToSend[]=new CharSequence[stringToBeSent.length()];
for(int i=0;i<stringToBeSent.length();i++){
	keysToSend[i]= String.valueOf(stringToBeSent.charAt(i));

} 
 public Actions sendKeys(CharSequence... keysToSend) {
    return this.sendKeys(null, keysToSend);
  }
  }
/*please suggest if this can be done*/

**Comment by lukeis** [comment]
Actions(driver).sendKeys("something").perform();

that compiles and will work just fine

**Comment by arpit-agarwal91** [comment]
Hi lukeis,
Please mention that what I suggested would work or already Webdriver's Actions class supports String object as input.
 I mean, was I right or wrong ?
I am new at github so please clear my doubt. I would be grateful to you.

**Comment by lukeis** [comment]
webdriver actions already support strings for the sendKeys method
