### ISSUE TITLE
normal click() brings the contextual menu like if it was a right click

### ISSUE THREAD

**Issue by josepitateamcmp** [SeleniumHQ/selenium#2923]
## Meta -
OS:  macos sierra

Selenium Version:  2.52

Browser:  Firefox and Chrome

Browser Version:  Chrome Version 54.0.2840.59 (64-bit) & Firefox 45.0.1

## Steps to reproduce -

go to seekverify.com, scroll to the bottom of the page, try to click the about link.

@FindBy(xpath = "//ul[@class='fh5co-links']/li/a[@href = '/about']")
    protected WebElement aboutLink;
        aboutLink.click();

This only happens with this elements, maybe is something in the page DOM itself.

**Comment by lukeis** [comment]
I can't reproduce this.... Using chrome 54 and chromedriver 2.24 also with Firefox 43 (close enough to 45) on El Cap. Maybe an issue on Sierra?

>>> from selenium import webdriver as w
>>> d = w.Chrome()
>>> d.get('http://seekverify.com')
>>> d.execute_script("window.scrollTo(0, 5000)")
>>> d.find_element_by_link_text("About").click()

**Comment by josepitateamcmp** [comment]
Found the issue, only happens if I find the element with @FindBy 
`    @FindBy(xpath = "//a[@href = '/about']")
` 
 if I use driver.find it works fine.

Here u have a video of the issue (download the video to see in HD) just for the laugh.
https://drive.google.com/file/d/0BxCBtD_A8tMrblRrWVEyZnh3Wmc
