### ISSUE TITLE
((RemoteWebDriver) webDriver).setLogLevel(Level.OFF) - results in verbose logging

### ISSUE THREAD

**Issue by james-crocker** [SeleniumHQ/selenium#2925]
## Meta -
OS:
Ubuntu 16.04 x64

Selenium Version:
3.0.0 (final)

Browser:
Chrome, Firefox

Browser Version:  
- Chrome Version 53.0.2785.143 (64-bit)
- Firefox Version 49.0

## Expected Behavior -
Expect that setting webdriver log level to `Level.OFF` would produce no logging output.

## Actual Behavior -
Logging more verbose than at `Level.FINE`. All webdriver logging is prefixed with `OFF:`
If set to Level.SEVERE still aggressive logging; all prefixed with `SEVERE`. Same for `Level.WARNING`

## Steps to reproduce -
Both browser tests executed at Node and on Hub. (Hub is Ubuntu 16.04 x64, same browser versions)
### Node
Note: Treating the local webdriver instances as RemoteWebDriver
`webDriver =
                                new RemoteWebDriver(((ChromeDriverService) service).getUrl(), dc);`
and
`((RemoteWebDriver) webDriver).setLogLevel(Level.OFF)`
```
INFO [m: [main]; Testing started
Starting ChromeDriver 2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1) on port 32630
Only local connections are allowed.
Oct 14, 2016 1:38:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Oct 14, 2016 1:38:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Oct 14, 2016 1:38:07 PM org.openqa.selenium.remote.RemoteWebDriver log
OFF: Executing: setTimeout [7fb1cc5cf006fb6c13e7d396ee6cbb28, setTimeout {type=implicit, ms=5000}]
...
Oct 14, 2016 1:39:44 PM org.openqa.selenium.remote.RemoteWebDriver log
OFF: Executed: [904a4f2aca26b3637d7f1d682a74d200, quit {}]
```
### Hub
Note: logging is far far less than logging when executing tests locally on a node workstation.
`webDriver = new RemoteWebDriver(gridUrl, dc);`
and
`((RemoteWebDriver) webDriver).setLogLevel(Level.OFF)`
```
INFO : [main]; Testing started
Oct 14, 2016 1:32:54 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
```

**Comment by lukeis** [comment]
you need to configure you logging on the command line when starting the server (hub / node, i think normally people just redirect output to /dev/null). It is not configurable with the RemoteWebDriver. What you are using configures the driver itself for it's logging level. So then later you can fetch the browser logs (which what type of logging is available differs depending on driver type).

**Comment by james-crocker** [comment]
Will adjust. Thank you.
