### ISSUE TITLE
query :: need help in building latest code

### ISSUE THREAD

**Issue by p00j4** [SeleniumHQ/selenium#2930]
## Meta -
OS:  MAC OS X

## Actual Behavior -
On latest code from `master`
while trying build latest code from source, it fails using crazyfun and buck both ways
Stacktrace

**./go build fails with:** bad-cert deps
<img width="1152" alt="screen shot 2016-10-15 at 10 06 51 pm" src="https://cloud.githubusercontent.com/assets/6470509/19411680/a54d150e-9323-11e6-84bc-6361d4b27d81.png">

**Buck build fails with** java_library() got an unexpected keyword argument 'maven_pom_template'
<img width="1146" alt="screen shot 2016-10-15 at 10 08 43 pm" src="https://cloud.githubusercontent.com/assets/6470509/19411693/e7cb46e4-9323-11e6-964f-005efce428fe.png">

 **./go clean test** breaks too with no such files
<img width="1146" alt="screen shot 2016-10-15 at 10 17 39 pm" src="https://cloud.githubusercontent.com/assets/6470509/19411773/26c79e78-9325-11e6-9719-b48ea313688a.png">

**Tried investigating**
there are key sets in each rule in BUCK(/java/client/src/org/openqa/selenium/BUCK) file like this:
 ```
maven_pom_template = ':template-pom',
```
however even removing this doesn't solve the problem, it starts pointing "manifest_file = ':manifest'," as unexpected argument.
what settings i'm missing here. I'm on latest commit (9d984ac231549cd88be44a45475f0cff6e4e382d)
<img width="424" alt="screen shot 2016-10-15 at 10 10 52 pm" src="https://cloud.githubusercontent.com/assets/6470509/19411707/3427c1e8-9324-11e6-915f-f3a4abbca4ab.png">
is there different build system or for 3.0 to be built smoothly or its some silly miss from my side

**Comment by lukeis** [comment]
Something appears horribly wrong with your local repo. I suggest doing a 'git clean -xdf' and then trying ./go build again

**Comment by lukeis** [comment]
Also, don't do ./go clean at all anymore. It may screw things up :)

**Comment by p00j4** [comment]
thank you @lukeis 
 yes after clean, go build works now but buck still is not happy. where should I dig in to resolve this? do I need to change something here?
/java/client/src/org/openqa/selenium/BUCK

buck build //java/client/src/org/openqa/selenium:webdriver-api
<img width="1143" alt="screen shot 2016-10-16 at 11 22 09 am" src="https://cloud.githubusercontent.com/assets/6470509/19415613/db483ebc-9392-11e6-9952-b9e4a3934657.png">

**Comment by lukeis** [comment]
This is because you attempting to use buck directly? Don't do that unless you have Selenium's fork of buck. Just use the ./go commands only for now, it uses buck for everything java

**Comment by p00j4** [comment]
ok got it.  so does it mean if I want to use buck build then I need to be using it with "buck.pex" ?
./buck-out/crazy-fun/a ...................

**Comment by lukeis** [comment]
Yes, or your buck needs to point to SeleniumHQ/buck (if you are trying to make changes to buck)

Seems like this is resolved. Closing the issue, hope you can make it online to irc if you have more questions/ problems with building selenium itself
