### ISSUE TITLE
`gem 'selenium-webdriver', '~> 3.0'` Unable to find Mozilla geckodriver

### ISSUE THREAD

**Issue by gabayliran** [SeleniumHQ/selenium#2932]
`gem 'selenium-webdriver', '~> 3.0'` give an error on `ubuntu` with `firefox 49`
`/var/lib/gems/2.3.0/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/firefox.rb:58:in `driver_path':         Unable to find Mozilla geckodriver. Please download the server from        https://github.com/mozilla/geckodriver/releases and place it        somewhere on your PATH. More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver. (Selenium::WebDriver::Error::WebDriverError)
 `
can you please advice ?
thanks!

**Comment by lukeis** [comment]
did read the exception? it's pretty clear on what you should do.
