### ISSUE TITLE
TypeError: element.isDisplayed is not a function (Javascript driver)

### ISSUE THREAD

**Issue by matenadasdi** [SeleniumHQ/selenium#2935]
## Meta -
OS:  
OSX El Capitan
Selenium Version:  
3.0
Browser:  
Chrome & Safari

## Expected Behavior -
elementIsVisible should work

## Actual Behavior -
`TypeError: element.isDisplayed is not a function`

## Steps to reproduce -
This could should be fine based on the node module and specification.
```
var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('safari')
    .build();

driver.get('http://cnn.com');
driver.findElement(By.className('nav-menu')).click();
driver.wait(until.elementLocated(By.className('nav-menu'), 10000))
driver.wait(until.elementIsVisible(By.className('nav-menu')), 10000);
driver.quit();
```

**Comment by lukeis** [comment]
elementIsVisible takes a webelement reference, not a By object

**Comment by matenadasdi** [comment]
Ah sorry, thanks :)

**Comment by ChrisGrigg** [comment]
I'd also like to know:

Please Give example for that ?
What is webelement reference?

**Comment by artemv** [comment]
@ChrisGrigg, @KathiresanRamkumar95 - smth like this:
```
let by = By.className('nav-menu');
driver.wait(until.elementLocated(by, 10000));
let el = driver.findElement(by);
driver.wait(until.elementIsVisible(el), 10000);
```

**Comment by ChrisGrigg** [comment]
@artemv thanks! That's working better than all other things I've tried.

**Comment by gigouni** [comment]
Is there any shorter response ? It works btw

**Comment by ChrisGrigg** [comment]
@gigouni you can remove 1 line:

let by = By.className('nav-menu');
driver.wait(until.elementLocated(by, 10000));
driver.wait(until.elementIsVisible(driver.findElement(by)), 10000);

**Comment by gigouni** [comment]
Huum, waht about

```javascript        
driver.wait(until.elementLocated(By.className('foobar'), 10000));
driver.wait(until.elementIsVisible(firefox_driver.findElement(by)), 10000);
```

?

@ChrisGrigg I was hoping even shorter but that's cool, thanks

**Comment by kiragengis** [comment]
Hi, talking about that, I tried to locate in the code how you figure out when an element is displayed, can anyone guide me? Thanks

**Comment by gigouni** [comment]
@kiragengis 

```javascript
const ELEM_BY = BY.id("your-element-id")
driver.wait(UNTIL.elementLocated(ELEM_BY)).then(() => {
    driver.wait(UNTIL.**elementIsVisible**(driver.findElement(ELEM_BY)), 10000).then(() => {
        done()
    })
})
```

The elementIsVisible() might be your answer.

**Comment by machineghost** [comment]
Stupid question: instead of this unhelpful error message, why not throw one that says "elementIsVisible takes a webelement reference, not a By object"?

**Comment by mmerrell** [comment]
PRs are always welcome.. this one sounds somewhat easy to implement, so it might be a good place to learn about the code too. 
MM
