### ISSUE TITLE
AttributeError: 'Service' object has no attribute 'process'

### ISSUE THREAD

**Issue by mossygr** [SeleniumHQ/selenium#2937]
after installing selenium, i tryied to run example0 but it gives me a error. Can you please tell me how can i fix it? thank you

![screenshot_1](https://cloud.githubusercontent.com/assets/16163486/19421616/12cbbcb2-940e-11e6-8856-e0a1ecf08ca8.png)

**Comment by AutomatedTester** [comment]
You need to make sure that GeckoDriver is in your PATH. Follow details in https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver
