### ISSUE TITLE
Selenium Webdriver returns empty response even with --ssl-protocol=any and --ignore-ssl-errors=true

### ISSUE THREAD

**Issue by EuclidHeron** [SeleniumHQ/selenium#2938]
## Meta -
OS:  OSX
Selenium Version:  2.47.1
Browser:  PhantomJs

## Expected Behavior -
the page source is printed

## Actual Behavior -
the empty page is printed:
<html><head></head><body></body></html>

## Steps to reproduce -
from selenium import webdriver 

driver = webdriver.PhantomJS(service_args=['--ignore-ssl-errors=true', '--debug=true', '--ssl-protocol=any']) 
driver.get("https://tmp.org") 
print(driver.page_source)

I am seeing (in my logs):
2016-10-16T18:31:31 [DEBUG] Network - Resource request error: 2 ( "Connection closed" ) URL: "https://tmp.org/"

If I try the url 'https://www.americascarmuseum.org' I get 'Resource request error: 6 ( "SSL handshake failed" )'

**Comment by AutomatedTester** [comment]
PhantomJS WebDriver isnt supported by the Selenium project, please raise a bug with them
