### ISSUE TITLE
How to download Safari Driver?

### ISSUE THREAD

**Issue by lukasoppermann** [SeleniumHQ/selenium#2941]
Sorry for the question,

but the link in the wiki just opens a directory view. I did not find the mentioned file in it. Where can I find the SafariDriver? Thanks.

**Comment by oddui** [comment]
Hi, i can find it in the [`2.48`](http://selenium-release.storage.googleapis.com/index.html?path=2.48/) folder in the directory view.

However that driver is not supported and has been removed #2725 from the project. It's easier and better to use the `safaridriver` that comes with Safari 10.

**Comment by lukasoppermann** [comment]
Hey @oddui thanks for your answer. How do I use the Safari 10 driver?

**Comment by lukeis** [comment]
If you have safari 10 installed, the safaridriver will be installed in your OS too, nothing extra to install. Apple did it for you :)

Please post future questions to the selenium-users Google group

**Comment by lukasoppermann** [comment]
Okay, I do have safari 10, however I get an error that I am supposed to install the driver. I am using selenium through web-components-tester, maybe its related to that?

**Comment by lukeis** [comment]
selenium itself updated its library to handle the new safari driver, if there's an issue in the selenium library we can help.

I don't know what 'web-components-tester' is, perhaps you can log a bug with that?

**Comment by lukasoppermann** [comment]
Hey, thanks, I did: https://github.com/Polymer/web-component-tester/issues/411 I am not sure where the error lies.

**Comment by titusfortner** [comment]
@lukasoppermann Try this with Selenium 3.0 and see if you get the same error; it doesn't look like what you are using is trying to use the new safaridriver provided by Apple.

**Comment by sandeepjain1987** [comment]
Is there a latest safari webdriver extension available for safari 11 ?

**Comment by timsutton-sl** [comment]
@sandeepjain1987 Could you elaborate? I see that Safari 10 works with 2.48.0, but I'm wondering if this is officially documented, or if you've seen this discussed elsewhere. I can see that the 2.x versions are deprecated with Safari 10+..

**Comment by sandeepjain1987** [comment]
Yes. I agree that 2.x are depreciated with safari 10+ which works well, with 2.48.0 but it doesn't work with safari 11 (https://webkit.org/blog/6900/webdriver-support-in-safari-10/) 
Safari extn "SafariDriver.safariextz" is available for 2.48.0 in https://selenium-release.storage.googleapis.com/index.html?path=2.48/ but it is not released since then. I was wondering if there is going to be any safari extn driver (which might support safari 11) for the latest selenium standalone release.

**Comment by timsutton** [comment]
The SafariDriver extension isn't being developed anymore, so I wouldn't expect to see any updates to it. The only thing I've come across is [this user group post](https://groups.google.com/d/msg/selenium-users/8vu9QZx9FGg/jACxGMvoAAAJ) which references a branch for Selenium 3.5 which supposedly has support for the extension.
