### ISSUE TITLE
Firefox 49 works with my signed WebDriver but it does not with Selenium's unsigned one

### ISSUE THREAD

**Issue by andreicristianpetcu** [SeleniumHQ/selenium#2942]
Please read the issue an not mark it as duplicate of #2559
## Meta -

OS:  
Ubuntu 16.04
Selenium Version:  
2.53.1
Browser:  
Firefox

Browser Version:  
49.0 (64-bit)
## Expected Behavior -

Firefox 48+ should work with Selenium's WebDriver just as it works with [my signed WebDriver](https://my.owndrive.com/index.php/s/cEXRnP1Y6rLeDEV)
## Actual Behavior -

Selenium replaces my WebDriver which works with v49 with the unsigned one which does not work with Firefox v48+
## Steps to reproduce -

Install [my signed web driver](https://my.owndrive.com/index.php/s/cEXRnP1Y6rLeDEV) and start Protractor or Selenium.

**Comment by andreicristianpetcu** [comment]
Please read [this comment](https://github.com/SeleniumHQ/selenium/issues/2559#issuecomment-254062784) it explains how to sign your webdriver without passing Mozilla's code review.

Sorry for making another bug since I think that people don't look at closed issues.

**Comment by lukeis** [comment]
@andreicristianpetcu if you replace the webdriver.xpi in the standalone.jar (it's basically a zip file, you can unpack and re-zip up). You'll be able to run with your own customized extension instead.

@AutomatedTester @andreastt @davehunt  is this an acceptable method to bypass mozilla's extension signing and do it ourselves?

from the other issue comment:

You don't need Mozilla's review in order to get the addon signed. Change the UUID in install.rdf of the addon to a [new generated value](http://www.somacon.com/p113.php) and run JPM sign like so.

```xml
  <Description RDF:about="urn:mozilla:install-manifest" em:id="{681B9050-93CA-11E6-827B-DB5CC7AD2208}"
```
```bash
jpm sign --api-key $MY_AMO_API_KEY_COPIED_FROM_AMO --api-secret $MY_AMO_API_SECRET_COPIED_FROM_AMO --xpi firefox-driver.xpi
```

**Comment by andreicristianpetcu** [comment]
@lukeis replacing it does not work :( If I delete webdriver.xpi I get no error and each new run will still have it. It must be somewhere in some cache, profile or something. If I delete the file from node-modules I should get an error but I don't.

@davehunt I know time working on Free Software projects is very little and should not be wasted but this is a popular issue (it's put in the [template of all the new issues](https://github.com/SeleniumHQ/selenium/issues/new)) and it can be fixed in 10 minutes. This is not an API change. The file only needs to get signed, it's a trivial operation. From what I understand FirefoxDriver is the stable and GeckoDriver is the beta. Lots of people are using FirefoxDriver still.

This is not bypassing Mozilla's addons signature, it's using Mozilla's addon signature. This is not a trick or a hack.

**Comment by AutomatedTester** [comment]
If its using jpm then it should be fine to do. 

I want to make something explicitly clear on this though, since Mozilla has put a lot of effort into the specification and getting GeckoDriver up to speed, that if we do this and FirefoxDriver stops working, which could happen at the release of 50, Mozilla won't be putting any effort into fixing it and neither will the Selenium project. This will have to be wholly community driven.

**Comment by lukeis** [comment]
@andreicristianpetcu so... it's not working for me... getting a weird error:

jpm sign --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET --xpi build/javascript/firefox-driver/webdriver.xpi
JPM [error] FAIL
Error: EACCES, stat '/var/folders/r8/3v1w2db52gx3gjbs393990_910gc7h/T/tmp-extracted-xpi-32363vS8JAAYJcWCq/platform/WINNT_x86-msvc'
    at Error (native)

that temp folder doesn't exist... no idea where it's going wrong.

**Comment by andreicristianpetcu** [comment]
strange...... jpm is a nodejs tool..... try running it with node-debug or node-inspector. For me it worked fine. I signed several unmaintained addons this way

**Comment by lukeis** [comment]
i tried a few steps in with node debug... and I'm not familiar enough with jpm to understand where to step into. So, I logged a bug with them and hopefully someone there knows more. I'm hoping for some simple user error on my part :)

https://github.com/mozilla-jetpack/jpm/issues/600

**Comment by andreicristianpetcu** [comment]
Are you trying to sign v3.0.0? Why not try v2.53.x? I signed v2.53.0 I think and it worked....

**Comment by lukeis** [comment]
Why would I try signing the old version? Also there should be much / anything different with the one in 3.0

**Comment by andreicristianpetcu** [comment]
The current stable works with 2.53.0 right? 3.0 is beta. Am I wrong? This is a bug with the current issue, not a feature request.

**Comment by lukeis** [comment]
3.0 is not beta anymore , we released 3.0.0 (and 3.0.1)

**Comment by andreicristianpetcu** [comment]
I signed this [new extension](https://my.owndrive.com/index.php/s/QAxahDV7hHfPUAF/download) and [here](https://github.com/mozilla-jetpack/jpm/issues/600#issuecomment-254950355) is how I did it.

**Comment by andreicristianpetcu** [comment]
@lukeis if you manage to sign the extenssion, please put `em:maxVersion="*" `. You initially put v51 as maximum which makes it incompatible with my daily browser: Firefox Nightly v52. In November it would stop working with Firefox DevEdition also.

**Comment by andreicristianpetcu** [comment]
@lukeis I'm replying you here for [this comment](https://github.com/mozilla-jetpack/jpm/issues/600#issuecomment-255141887). Please create the initial xpi file with another tool. Or unzip it and rezip it again with something else. This worked for me. What zipping tool are you using? What OS?

**Comment by lukeis** [comment]
we are using java :) (well 'jar')

https://github.com/SeleniumHQ/selenium/blob/master/rake-tasks/zip.rb#L42

**Comment by lukeis** [comment]
oops, wrong one.. this is the one that's used for xpi's

https://github.com/SeleniumHQ/selenium/blob/master/rake-tasks/crazy_fun/mappings/common.rb#L195

**Comment by andreicristianpetcu** [comment]
Should I [guess the OS that are you using](https://github.com/SeleniumHQ/selenium/blob/aabb225fda151bd2d4095fe8e94d57d23fb8ac6b/rake-tasks/crazy_fun/mappings/common.rb#L193)?

**Comment by lukeis** [comment]
https://github.com/mozilla-jetpack/jpm/issues/600#issue-183572489

https://github.com/SeleniumHQ/selenium#requirements

**Comment by andreicristianpetcu** [comment]
So you are using rake, to call jar, to make a zip.
Why not make the zip [with rake](http://stackoverflow.com/a/31028818/1387563)? You will not need an external dependency.

I will investigate this when I have time. I'm no guru in rake :)

**Comment by lukeis** [comment]
the build system is called crazy-fun :)  which happens to be the former and much less the latter.

**Comment by andreicristianpetcu** [comment]
Is there any documentation on building the extension with the current rake build system? I want to try a ruby-native zipping instead of jar.

**Comment by andreicristianpetcu** [comment]
I created a rakefile that zips the contents of the folder using pure ruby. It's still a work in progress but I hope that I will be able to get rid of the jar dependency and have a working, signable archive.

```ruby
require 'rake/packagetask'
require 'zip/zip'
namespace :my_namespace do
  def zip(src, dest)
    path = src

    path.sub!(%r[/$],'')
    archive = File.join(path,File.basename(path))+'.zip'
    archive = dest
    FileUtils.rm archive, :force=>true

    puts "Making archive " + archive
    Zip::ZipFile.open(archive, 'w') do |zipfile|
      Dir["#{path}/**/**"].reject{|f|f==archive}.each do |file|
        zipfile.add(file.sub(path+'/',''),file)
      end
    end
  end
  desc "Make xpi"
  task :make_xpi do
    puts "Making a Firefox extension file"
    zip("firefox_webdriver-3.0.0-fx.xpi_FILES", "firefox_webdriver-3.0.0-fx.xpi")
  end
end
```
Right now signing fails with this error:
```bash
$jpm sign --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET --xpi firefox_webdriver-3.0.0-fx.xpi
JPM [info] Signing XPI: firefox_webdriver-3.0.0-fx.xpi
Server response: Invalid archive. (status: 400)
JPM [info] FAIL
```

**Comment by andreicristianpetcu** [comment]
I'm giving up. I see very little effort from Selenium devs to fix this. Your build process is too complicated for me. I signed 2 addons of yours to show you how and you can sign each new release manually. It takes 1 minute. It does not need to be part of the build system. Selenium devs have little interest for their Firefox users. I know, I know future versions will work with marionette or geckodriver or whatever but until then latest stable Firefox does not work with latest stable Selenium and it's a 1 minute manual job for each release in order for this to work. It has been so since August and there was very little effort to fix this. I know working on Free Software projects is hard and everybody wants you do implement their "very important" feature but I think this was quite important for a lot of people.

You can close this ticket if you want. Sorry I don't have more time to invest in this.

**Comment by davehunt** [comment]
@andreicristianpetcu following your lead I was able to get this working.

The patch for creating the XPI is:

```patch
diff --git a/rake-tasks/crazy_fun/mappings/common.rb b/rake-tasks/crazy_fun/mappings/common.rb
index 523d8e7..f267c22 100644
--- a/rake-tasks/crazy_fun/mappings/common.rb
+++ b/rake-tasks/crazy_fun/mappings/common.rb
@@ -1,4 +1,3 @@
-
 # Modify String to add start_with and end_with methods
 if (!"".methods.include? :start_with)
   class String
@@ -187,14 +186,20 @@ class Tasks
     end
   end
 
-  def zip(src, dest)
-    out = Platform.path_for(File.expand_path(dest))
-    Dir.chdir(src) {
-      # TODO(jari): something very weird going on here on windows
-      # the 2>&1 is needed for some reason
-      ok = system(%{jar cMf "#{out}" * 2>&1})
-      ok or raise "could not zip #{src} => #{dest}"
-    }
+  def zip(path, dest)
+    gem 'rubyzip'
+    require 'zip/zip'
+    require 'zip/zipfilesystem'
+
+    path.sub!(%r[/$], '')
+    archive = Platform.path_for(File.expand_path(dest))
+    FileUtils.rm archive, :force=>true
+
+    Zip::ZipFile.open(archive, 'w') do |zipfile|
+      Dir["#{path}/**/**"].reject{|f|f==archive}.each do |file|
+        zipfile.add(file.sub(path+'/', ''), file)
+      end
+    end
   end
 
   def to_filelist(dir, src)
```

I generated a unique UUID and use my own AMO credentials to then sign the extension:

```bash
$ jpm sign --api-key <KEY> --api-secret <SECRET> --xpi build/javascript/firefox-driver/webdriver.xpi
JPM [info] Signing XPI: build/javascript/firefox-driver/webdriver.xpi
Validating add-on [...............................................................................................................................................................................]
Validation results: https://addons.mozilla.org/en-US/developers/upload/7a9a98e5699a477392d247dd5881877c
Downloading signed files: 100% 
Downloaded:
    ./firefox_webdriver-3.0.1-fx.xpi
JPM [info] SUCCESS
```

I think it would be great to get this into the next release. I do think we should make it clear that this is not the recommended approach, and that any issues encountered using Firefox 48+ without geckodriver would likely not be resolved.

So what remains is:

- [ ] We would need to update the build to sign the XPI and then package the signed version.
- [ ] We would need an AMO account with credentials to sign the XPI, and these will need to be encrypted for Travis. We can probably use personal accounts for this, and whoever gets there first can encrypt theirs for CI.
- [ ] We would want to add a py27-firefox job in Travis that installs latest release to alert us if/when this breaks. We may ultimately want to test Firefox pre-releases for more notice.

I'm happy to help, however I'm not sure how much time I can commit.

**Comment by andreicristianpetcu** [comment]
Thank you @davehunt I'm glad you are interested in this. What makes you think this is not a recommended way? Is geckodriver stable and fully functional? My understanding is that webdriver is stable and geckodriver is beta.

Lastpass is a popular Firefox addon that is signed but unlisted, just as I propose webdriver should be until geckodriver has all the features that webdriver has. Mozilla [supports unlisted addons](https://blog.mozilla.org/addons/2015/12/01/de-coupling-reviews-from-signing-unlisted-add-ons/).

**Comment by davehunt** [comment]
I'm not questioning the approach of signing the unlisted add-on. I'm also not sure I'd call geckodriver beta, but it certainly is 'pre-release'. This is because it implements the WebDriver specification, which itself is yet to be finalized.

My point is more that if a Firefox release breaks compatibility with the unlisted add-on (it's happened before), then there's going to be very little effort made to fix it. This is because all focus is on geckodriver, and there is little resource or interest in maintaining the add-on. Also, the more people we have using and reporting their issues with geckodriver, the quicker we can improve the experience.

I'm curious to know what's currently preventing you from switching to geckodriver? Perhaps these are issues that are soon to be resolved.

**Comment by andreicristianpetcu** [comment]
I will try to use geckodriver so I did not actually test it since it seemed to be in beta while webdriver was stable.

The tutorial is for Windows, I'm on GNU/Linux, I don't use vanilla Selenium but I use Webdriver/Geckodriver behind Protractor. So I might have some issues there but I will test and report back if there are any issues. At this point it seems like Selenium forces me to change my workflow, not Firefox.

**Comment by andreicristianpetcu** [comment]
I tried Marionette and [I bumped into my first issue](https://github.com/angular/webdriver-manager/issues/52).

It's frustrating to try to use a beta software when this can be fixes so easily by signing the old extension.

**Comment by andreicristianpetcu** [comment]
At least please [stop blaming Firefox](https://github.com/SeleniumHQ/selenium/issues/new) for your lack of signed addons. Webdriver is the only addon that is not signed from all that I use. It's Selenium's fault for the fact that the latest Firefox does not work with the latest Selenium. I have to debug and report issues, do ugly hacks locally because Selenium devs can't do a 2 minute manual operation on each new release. I really appreciate your work but I think your time can be invested better in fixing a simple issue rather than pushing users to use a beta software.

**Comment by ryantrevisol** [comment]
@andreicristianpetcu I'm in the same boat as you. I understand the need to stick to standards, but not implementing Actions is a deal-breaker for me. This has forced my organization to move exclusively to Chrome for automation. 

This whole issue is politicized. Selenium devs (perhaps rightly) don't want to support an implementation for one browser, when they don't have to do so for Chrome, Edge, Safari, etc. Mozilla wants to improve browser security by requiring signed extensions. Marionette devs don't want to implement parts of the WebDriver spec that aren't finalized, even though Chrome Driver et al do support them, and FirefoxDriver supported them for ages. This brings us back around to the selenium devs, who are now either unable or unwilling to commit dev effort to fixing legacy code by finding a way to sign the WebDriver addon. 

The problem is, nobody is thinking of automation testers as customers who deserve a level of customer service. 

Firefox used to be the best-supported browser for automation, and many people made it their primary automation browser. Now we are invested in using the features of FirefoxDriver (like Actions). Neither Mozilla's marionette devs nor the Selenium devs see the need to provide a way to continue to fully use the FirefoxDriver's features regardless of the WebDriver standard's completeness. 

I understand everyone's motives and I value standards, but at this point, all parties involved are hurting your customers (us automators) by pointing the finger at other parties, and waving the banner of standards as a way to mask their unwillingness to fix issues. 

Sorry if this makes people uncomfortable, but I'm just a person who's spent the last 3 months trying to convince my IT department to let us use Firefox ESR, the last 2 weeks trying (and being unable) to excise all uses of Actions from my test code, trying to get Marionette/GeckoDriver to work around this limitation, and finally giving up and going to Chrome.

**Comment by davehunt** [comment]
I am in support of signing the unlisted add-on but this would require changes to our build system that I don't personally have time to work on. I listed the remaining tasks in [this comment](https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567). I'll also reiterate that if a Firefox release breaks support for the unlisted add-on, it's unlikely to get much attention.

**Comment by davehunt** [comment]
> At least please stop blaming Firefox for your lack of signed addons.

We'd welcome patches to the [issue template](https://github.com/SeleniumHQ/selenium/blob/master/.github/ISSUE_TEMPLATE.md) if you feel the current wording could be improved.

**Comment by AutomatedTester** [comment]
@ryantrevisol 

Thank you for your comment. 

> all parties involved are hurting your customers

From your comment you seem to think that the Selenium team is paid for the work that you can use. Unfortunately that is not true. This is not a politics issue, this is an issue about trying to spend the right amount of time on the right thing for a small group of people.

Both within Mozilla and Selenium, this group is tiny. There are other things that make need priority of work and items that need to be done in time.

Since this is a product that you consume for free from people who put their free time into it, perhaps it would be better if you treated it as such. If something isnt happening at the pace you would prefer you can always step up and submit some patches to get things fixed.

**Comment by andreicristianpetcu** [comment]
@davehunt I don't think I can send a pull request on that file. I see other changes but not that file in my pull request. Strange. I added this text:

CURRENTLY SELENIUM AND FIREFOX 48+ ONLY WORK WITH GECKODRIVER. Any issue logged here for 48+ will be closed as a duplicate of #2559 If you wish to add back support for WebDriver [please contribute](https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567) but just keep in mind that WebDriver will not be supported in the future.

Do you think a bountysource bounty might motivate somebody with the knowledge and credentials to fix this? Some of the things that need to be changed are related to the build server (Jenkins or Travis or whatever you are using) so outsiders might not be able to help out on this.

**Comment by davehunt** [comment]
> I don't think I can send a pull request on that file.

That's odd. I've tried to explain the situation a little better, while also trying not to be too verbose. Let me know what you think of my changes in https://github.com/SeleniumHQ/selenium/commit/6dbc73b7c1c7c27829a3888ae33a80e14ceee039.

> Do you think a bountysource bounty might motivate somebody with the knowledge and credentials to fix this?

Perhaps, though I'm not aware of this being done before in the Selenium project. I'm not sure there's any credentials requirements. We'd only need to sign the add-on for a release, and whoever is responsible for the release should be able to provide the necessary API key for signing.

> I really think Mozilla should try to fix this.

I agree that this would be ideal, but given the limited resources available and ongoing effort to make GeckoDriver robust and spec-compliant, I think it's unlikely to happen.

**Comment by indolering** [comment]
FWIW, a BountySource bounty would at least allow different vendors to pool resources to fix this.

**Comment by andreicristianpetcu** [comment]
**IT FREAKING WORKS NOW!**

I made it work with my own web driver.

```bash
$webdriver-manager status
webdriver-manager: using global installed version 12.0.2
[15:06:02] I/status - selenium standalone version available: 3.0.1 [last]
[15:06:02] I/status - chromedriver version available: 2.27 [last]
[15:06:02] I/status - geckodriver version available: v0.14.0 [last]
[15:06:02] I/status - android-sdk is not present
[15:06:02] I/status - appium is not present
```
```bash
$firefox --version
Mozilla Firefox 51.0.1
```
```bash
$protractor firefox-config.js
```
firefox-config.json
```json
exports.config = _.merge({}, baseConfig, {
     capabilities: {
        browserName: 'firefox'
    },
    seleniumArgs: ['-Dwebdriver.firefox.profile=protractor']
});
```
I have a protractor profile named `protractor` with my own custom webdriver that is SIGNED.
[firefox_webdriver-3.0.1-fx.xpi.zip](https://github.com/SeleniumHQ/selenium/files/777126/firefox_webdriver-3.0.1-fx.xpi.zip). You need to rename the file by removing the .zip at the end `firefox_webdriver-3.0.1-fx.xpi.zip` -> `firefox_webdriver-3.0.1-fx.xpi`. An install this web driver in the `protractor` profile. You can remove the old webdriver since it does not work anyway.

Geckodriver still does not work. I don't know why. I will not use it until it goes out of BETA.

I really am disappointed by the Selenium community :( This issue is opened since August in it's original form. I heard somebody at FOSDEM during a talk that WebDriver does not work anymore due to addon signing. I hate it how people blame addon signing for a lot of stuff that is unrelated to addon singing.

I'm sorry for the rant but I guess you understand me. This is a 1 minute job that can be done manually after each release that would bring support to Firefox. Now a lot of people don't test on Firefox at all because of this. I hope my instructions help other people until geckodriver gets into shape.

**Comment by andreicristianpetcu** [comment]
@phoenix384 You can't sign a new legacy addon. You can create a new WebExtension and "upgrade" it to a legacy addon :D. The most trivial webextension is a zipped manifest.json. It needs to have a new guuid. After you signed the webextension then upload a "new version" for signing that is the legacy one with the webextension's uuid and a different version.

If you have issues I can help. This is tested and it works.

**Comment by phoenix384** [comment]
That worked. Thank you

**Comment by andreicristianpetcu** [comment]
Do you happen to have a Selenium build that uses the signed addon? I managed to sign the addon but did not manage to use it inside Selenium.

**Comment by phoenix384** [comment]
Yes I do. I took the webdriver.xpi from the Java lib .jar, signed it to a folder of the project and started Firefox with
`FirefoxProfile profile = new FirefoxProfile();
profile.addExtension("webdriver", new FileExtension(new File(folder, "webdriver.xpi")));
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability(FirefoxDriver.MARIONETTE, false);
capabilities.setCapability(FirefoxDriver.PROFILE, profile);
FirefoxDriver driver = new FirefoxDriver(capabilities);`
or with parameter -Dwebdriver.firefox.driver='/path/to/xpi' via Grid.

**Comment by masterseo2000** [comment]
Hello,
I just noticed the that there is a little bot that appears in the address bar that says: browser is under remote control (Firefox) on Firefox (chrome is automated by a software)
I was wondering what is this exactly (I got the bot thing) I mean by that:
Is that just a client site indicator?
Is that something that that the actual website detects
Would it go away when you define a user agent
Is there a way to remove it / Control it
Thanks a lot!!

**Comment by davehunt** [comment]
@masterseo2000 this is to conform with the suggestion in the WebDriver specification's [security considerations](https://w3c.github.io/webdriver/webdriver-spec.html#security-considerations):

> It is also suggested that user agents make an effort to visually distinguish a user agent session that is under control of WebDriver from those used for normal browsing sessions. This can be done through a browser chrome element such as a “door hanger”, colorful decoration of the OS window, or some widget element that is prevalent in the window so that it easy to identify automation windows.
