### ISSUE TITLE
Issue with variable value on selenium grid execution

### ISSUE THREAD

**Issue by sachin6757** [SeleniumHQ/selenium#2944]
## Meta -

OS:  

Selenium Version:  2.471.1

Browser:  
Firefox 45

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  
45
## Expected Behavior -

It should enter correct value in the text field.
## Actual Behavior -

Incorrect value is getting entered in the text field. Below is the incorrect value:

/tmp/21fe989d-6c5d-413b-8365-cf6da42e92b9/upload957182740231871694file/1
## Steps to reproduce -

We are using selenium grid to all UI testcases execution. We are using robotframework.

We are facing issue when any variable having value 1 which is getting entered into any text field.

set test variable     ${data}     1
input text     xpath=//input[@name='floorValue']     ${data}

Above are the steps where I am assigning value to a variable and in next steps entering the text field identified by the xpath.

Below is the log from the test execution:

`6:56:00.882 INFO Typing text '1' into text field 'xpath=//input[@name='floorValue']'

16:56:00.883 DEBUG POST http://192.168.1.201:4444/wd/hub/session/e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e/elements {"using": "xpath", "sessionId": "e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e", "value": "//input[@name='floorValue']"} 16:56:00.905 DEBUG Finished Request

16:56:00.905 DEBUG POST http://192.168.1.201:4444/wd/hub/session/e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e/element/26/clear {"sessionId": "e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e", "id": "26"}

16:56:00.931 DEBUG Finished Request
16:56:00.933 DEBUG POST http://192.168.1.201:4444/wd/hub/session/e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e/file {"sessionId": "e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e", "id": "26", "file": "UEsDBBQAAAAIAGJU9Uhr90YTkgoAAF5CAAABAAAAMe1bbW/bOBL+HP8Kwf5g+dZRGvd6iwtOi3Ob\n9tBDui2SvuCQBAQtMTa7suQVqdTeX398lUhJfpHk7uWA+kMiUjMPh8OZ4QwlDR7SZOkEyXKZxCCj\nOMIUI+JdYUIvIYUOXq6SlDq63asnX6BohVJNnCIY0iTEAZXkaTJLqBfhWQpTTv0ywxF9G2ty1ezl\n3PqK0BTH87wfxmGy1C2KlzldQnKOTX4ZQooEkRBBt5yD747FECGK9KTlLOAKa6oomc9RKm/eoAjF\nOFtOrsQsN5qm3F9P/XpNUUxwEpNtfAVFj/0GDvHLFO6oNyBoUukvODmFk6WR4zv9BaWri7Oz858n\n3vnfvL96538/v5hMJmfT8F8Qx+/mS3r25fH36NNiEX96DOM/vK9k1edDBxEkxHnFlpiiD2kSZgF1\nRxe93kmIHhwAcIwpAC5B0QPrPTkZkIwZhvuSL947GEOmsLG46eW0I0ZG0w2nPhlYwIxmBgkiANw+\nu/dscE79gNlUIVs2n5mAt4J04X1NcOzqBpwR/j9vhzjl5C4AnBOA0Wg8fD/7igJ6jVbJUGBycC+Z\nfU1ZD8MtTNnVoxVkZMJ1qczXHXlzRIG08g2TlVAYB8gdlhfEGIetVwuAYkUFFFoHaEWF+gwvYC1p\nnx6OHxKXdXmMEIjGiLMNThrpWk/Y/zWJkTkB2aEMAIdgjmKUQpqkLsF/IP/F2AkWMCW+dGYPkgBj\nkK2YVQRsPOcn5eVsceaYEmE0KaJZGjvDD2+vTpV4p8OfhkO5ujIOeDcbQtHyWjSY6oJFgpmyDhul\naEvCKPkmCUfOQ5I6wMExDzdz5P7MdMUkkrNbSVmAMCI+/zGOVxkVMmv9eEGEg98AW7IliqlrmtNt\n/xW/p2b0KwPp349MVoEGKFrv51MjV0QLEQlSvKLMOqSERkc7OS8LgDbiWuyWNBXZCYJpsPgI50SK\nnreF4PjByTucf/ziDLndDYXZ8zXDzBj4suU04k7z6d5ofjnZptM12MdcpBLGKkWEgN/Q5kCI4d3d\n+fPhqGcrCoZsxkso5RjrltDSilk1dXRXzyn9mBL1PVOHZTL9g77DQo+bj7CVkOM6vzjPtkPpX4MF\nieAyYPc+JARr69uHblqClnq/TCcRjpFfL0Ig5NMyvGXY/XuxpopJhhHGw0ld3jfuf4ZRhq5lV98w\ng23WyLlGJ9wdmllsWbpLtppcS6WQgAmTZPMpjZRfFR3CZEydFbcueo1kucwZld8c6DYmX6Gpw/zF\n4tWewrh53uaRCKGV+6KsjIDtePMklXhj3RJ6gD639bxLhhxl1SdFitI8pLxSkDqi2PKdlAKYFuBi\np8nsH02GET3mIN+v2U7JMjwC2NbI/QPEyTe3bJ4HhbryQKahG1N8PjLdZS/ad/Sw8uoxuTVB07kK\nrEH7xdGeaknEEms8jwHLoWjSGGs8rOl+mVGaxMPyJsSycEAWSRaFIEhiyswhH+5wFLRGQUYR+Aof\nodzU3f43zLKxb16YBBlH4/nsawn8cvM23AnuMYwkit7GNPmMETPJfmW9WqvYyJBNyzx/1nGIHw79\nw6F/OPSf7NAyTaoUD9rLeAXEMANq7/B5t64lKjdKNYWdDRTsosw284Lu4aMuWOQDtokap7nKFIgd\nOhqEha1I7WNDBfL75tTVrPrAKLFHiUfZlyKCjmRDBwGUeF9xVUyvrqolQxbLKXM1E33SEbIAEYoe\n7UNm346S3CS7KMXZZZIRBJJHlO6Y7DTkR0l6qnv2nTc4oiglyqKaG9TODacnDco+tdBGrDTFNArE\nXAE/NB+z+aWAET/iEIUgYl1afdU7tTGoBoDfnImb9mA6OrkiPI0cGIf8mqHORtLQrCXzb+/zAPQI\nI75WNp4KPpgAVkcHC8d33kBms7KXc7HyjHNVRVScQhgO7fOjVDLS3SbkxzRTiNyk8n41Vg5kCO7B\n1QrFIQcuysV627XMVlk5lzKZhtJQwDS8zFJYHJi9w7HuGL+Da32tF824XVqtg1zwMx9bjsyQirEP\nrpq3A5iSq+rVkL+rsHDdUVgbwFJtTwXpkmdJt1dOJa71IshWrbcowuo2bSf+5q6gU2ggdHFwHNqf\nf29Rcn/Nn0b43tnZX27/iUN/CMPTLMaUDO/PCLfcJD4L8ePt5N789/z+bLUMgtNlFlEsTZz3q05y\nymIcP+7vV3MKKXbb8kNyt84gqhDdygqJ9TSLijpVtS0GJJYuBabhjWq1qAD2MbdJ/KuYR8v3zZmP\n8gSukvDrtMyMEnafjhZ2b23UKDEeIcm3Y4XpjvZYrfJ7paLO2X09Tofc3gZ8el66U3PdLLVjQl+3\ntxyWzktOM5mvbqX6rpHQX8EZirSLiEbJM4ylnwjMtZ+LxR9U73sSxsYiSppNI85pSOFcswrJzn3x\n7/bZfd41UV3n9+VyQ/SrbPfBWft+fxpFfZELcxJfMp5fVAxcnwe2eGjI5/reeEbaGqQZu8lZNoAi\nP2E5tXYN/jzlACnM0ywL5xETPItQC/6mijAh2DJutizj5MKprOOL8sCyyGT7WbzX6rYtooTIVq0B\nDo8DhvE3DQScdYsdNBbBWsP6aCIWqnjXpxwwWseLik92d8gu3tjRFY/ih52csLsHbjGAaZi/rVFr\nAe3jftmdu/pyN0fu5MVdXbij/5ZOq3KXHYvL/NUa3qhNjSVZOSMelE5d7JBQSmIOWrOaPbTJou1i\nb7MDD/bPz3rtiPe3LbEFaKcK20LoVmALqD8xc28ekVQ5mCfb7cCm8aY+V9YHiIarWF358a3ZWX9y\na7FZLqTmoF/Y6v8HwUXfVk2YZCzKgw45aLcU1DRvayatSla5gJ0r1lqYDgWrhfcE69Udauu8q9dU\nqw1tri7l7Zjxdkq2ehVnluD6RUl+rd1Xtmr9VhHuPEN+YYi7JS1qswvu1GjLIqTjitjvVPI77Y+S\nOXfHo2QToutRMsd6ek6/TVWdC7n2O6ZEUlvmjj0TGu5m95V3zYr7yf1wZm2ctiPOao5j//cBq26b\nbO8mp2rNjnC0W4fT6WjXBHx6XrNTc93PQP7vN8v60yHbjW/k00flwLqlXVe3a/fMnLi6azZPVBRW\nnYvpe61rLcXfrdwqgXSsuBRaN58aqFKCU33Xraleg60XovCx+ud7tk2We8vP+HbaaIX5O9tqebx2\nhZPWU/faaQtSl/KpBPkEt4Xd+juC2XZ56le2nkbVj+KtL4AC8XEn0N40E0/pi5PawyW1vhKVD/tN\ndy2NEzK16BcG9aeRW89yd40tl0kNWz5J3WrrZa7iM0nzmYKFte0TowpU8YVRjUeo+cMHilKhErHJ\n9xp4gRa0EGzHOx3aI9SXsoK51xsOhz3Mv8LmH6gCwN+h6wOw5Iygz1ai/jP2j4jQm4x5If8OOURp\n74Twll/ud0fejF+5/dcXd6tsdnrNkaYZTZZiug84htHdNLxB6SNKwRc0u3u/QjG4/vgSFFR3lwhG\nRP4FfAggxvDomvIXRsTQ3oN4ZczFcRBl/I1Cnrn4w+s3/+bqZ+uVRdTxHUmbZrGbZJQpwD+GYHeU\nyeStlxGTprdNZddChC8pG5+py2wdRTmGDN43DgvknInLjS2l/vBogyzoMhqOo2R+HEwGJCFH0hr/\nC1BLAQIUAxQAAAAIAGJU9Uhr90YTkgoAAF5CAAABAAAAAAAAAAAAAACkgQAAAAAxUEsFBgAAAAAB\nAAEALwAAALEKAAAAAA==\n"}
16:56:00.943 DEBUG Finished Request

16:56:00.944 DEBUG POST http://192.168.1.201:4444/wd/hub/session/e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e/element/26/value {"sessionId": "e8d83ee3-7a75-40cd-a079-bb2c83d6fb2e", "id": "26", "value": ["/", "t", "m", "p", "/", "e", "8", "d", "8", "3", "e", "e", "3", "-", "7", "a", "7", "5", "-", "4", "0", "c", "d", "-", "a", "0", "7", "9", "-", "b", "b", "2", "c", "8", "3", "d", "6", "f", "b", "2", "e", "/", "u", "p", "l", "o", "a", "d", "6", "0", "5", "4", "3", "8", "4", "5", "8", "0", "2", "8", "1", "8", "0", "7", "9", "3", "f", "i", "l", "e", "/", "1"]}"

`

**Comment by barancev** [comment]
It appears that you have a file with name '1' in the working directory, and Selenium python binding thinks you want to enter file name in the input fields. But you're running it remotely, so it sends the file to the remote side, stores it to a temporary file, and enters the path to this file. It's working as expected. Be careful with file names.
