### ISSUE TITLE
cookie.getExpiry() don't return the date

### ISSUE THREAD

**Issue by andreggcampos** [SeleniumHQ/selenium#2945]
## Meta -
OS:  
OSX Sierra 10.12
Selenium Version:  
3.0.0
Browser:  
Firefox 
Browser Version:  
46.0.1

## Expected Behavior -
We can get the expiry date using:
driver.manage().getCookieNamed(COOKIE_NAME).getExpiry();

## Actual Behavior -
driver.manage().getCookieNamed(COOKIE_NAME).getExpiry();
returns null!

## Steps to reproduce -
With a cookie that have an expiry date like "12/31/9999, 11:59:59PM"
Using Selenium 2.53.0 and Java 1.8
and executing:

driver.manage().getCookieNamed(COOKIE_NAME).getExpiry();

**Comment by p00j4** [comment]
@andreggcampos with same meta, it works for me. can you run this and share the output? if it gives the cookie details but not your code, then I doubt on auth and only way to resolve this is, you will have to show where its reproducible. 
 ```
Set<Cookie> cookies = driver.manage().getCookies();

        Iterator<Cookie> itr = cookies.iterator();
        while (itr.hasNext()){
            Cookie c = itr.next();
            System.out.println("-----Cookies Detail-----");
            System.out.println("Cookie Name: " + c.getName()  + "\n\tCookie Domain: " + c.getDomain() +  "\n\tCookie Value: " + c.getValue() +  "\n\tPath: " + c.getPath()+  "\n\tExpiry Date: " + c.getExpiry()+  "\n\tSecure: " + c.isSecure());
        }
        System.out.print("***************** Access directly  with keyname********* \n");
        System.out.print(driver.manage().getCookieNamed("OGPC").getExpiry());
```

**Comment by andreggcampos** [comment]
@p00j4 The result of your code was:

```
Cookie Name: XXX
	Cookie Domain: localhost
	Cookie Value: true
	Path: /
	Expiry Date: null
	Secure: false
***************** Access directly  with keyname********* 
null
```

But I updated to selenium version 3.0.1 and this issue was already fixed.

Thanks
