### ISSUE TITLE
FileUploading in sauce lab

### ISSUE THREAD

**Issue by mohanngs** [SeleniumHQ/selenium#2947]
OS:  Windows 7,Macos
Selenium Version: 2.53.0
Browser:  Chrome

I have my test script running in sauce lab..These script has a fileuploading scenario.When running this scenario it is displaying invalid file path..Filepath is of my local machine..

**Comment by lukeis** [comment]
please reach out to sauce labs support for use with their service

**Comment by mohanngs** [comment]
thank you @ lukeis..
