### ISSUE TITLE
nodeConfig json file firefox_binary entries not passed on to geckodriver

### ISSUE THREAD

**Issue by csgbn** [SeleniumHQ/selenium#2948]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.0.0
Browser:  
Firefox

Browser Version:  
any FF version

## Expected Behavior -
When using selenium grid and launching a grid node with -nodeConfig using a json file that contains a mapping of custom firefox locations like:

{
        "browserName": "firefox",
 		"version": "48", 
		"platform": "VISTA",
		"firefox_binary":"C:\\Program Files (x86)\\Mozilla Firefox\\firefox48\\firefox.exe",
        "maxInstances": 1,
        "seleniumProtocol": "WebDriver"
        },
{
        "browserName": "firefox",
 		"version": "47", 
		"platform": "VISTA",
		"firefox_binary":"C:\\Program Files (x86)\\Mozilla Firefox\\firefox47\\firefox.exe",
        "maxInstances": 1,
        "seleniumProtocol": "WebDriver"
        },

The geckodriver should receive this binary location, but it does not. Specifying custom firefox binary locations in the json file works for all previous selenium 2 versions.

## Actual Behavior -
The geckodriver never receives this json firefox binary location and instead looks for a binary location in client capabilities or default install location of firefox on the os.  If it cannot find it it throws an error. Tested this with Java and Python, same result.

## Steps to reproduce -
Launch a 3.0.0. selenium grid and for the grid node, install FF48 in a custom location and launch the node with -nodeConfig using a json file with the firefox_binary location. There should not be any Firefox installed in the default OS location. Then run a test with FF48 not specifying the FF48 firefox_binary in a capability.

**Comment by lukeis** [comment]
This is no longer an allowed practice. It's quite the loophole that was put into grid that the new session capabilities were munged with the node config capabilities. They are meant to be used for matching only.

Instead on the node, you should be starting it with `java -Dwebdriver.firefox.bin=:"C:\Program Files (x86)\Mozilla Firefox\firefox47\firefox.exe" -jar selenium-server-standalnone-3.0.0.jar -nodeConfig config.json`


@mach6 fyi
