### ISSUE TITLE
Unclear directions for building Selenium's Python package

### ISSUE THREAD

**Issue by burg** [SeleniumHQ/selenium#2949]
A few issues:

On https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings:
- The wiki references `./go py_prep_for_install_release`. Does this still do the right thing after the pytest refactor?
- An alternative that I have been told is to run `python setup.py sdist`. This creates a tarball, but is missing the atoms 'isDisplayed.js' and 'getAttribute.js'. I believe these need to be specifically built using `go`.

With the above in mind, it might be worth updating the instructions.

**Comment by AutomatedTester** [comment]
>A few issues:

> On https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings:

>    The wiki references ./go py_prep_for_install_release. Does this still do the right thing after the pytest refactor?

Yes, this documentation was added after that refactor
>    An alternative that I have been told is to run python setup.py sdist. This creates a tarball, but is >missing the atoms 'isDisplayed.js' and 'getAttribute.js'. I believe these need to be specifically built > using go.

The step above, `./go py_prep_for_install_release` puts those files in the python directories ready for zipping into a tarball. Doing `python setup.py sdist` means that you are zipping up something already.

The prep call does the following

`cp buck-out/gen/javascript/webdriver/atoms/getAttribute.js py/selenium/webdriver/remote/getAttribute.js`

and a similar one for `isElementDisplayed`.

> With the above in mind, it might be worth updating the instructions.

How could we make it better specifically? For the most part, people shouldn't worry/care about the movements of these files as long as they happen.

**Comment by AutomatedTester** [comment]
see output for `./go py_prep_for_install_release`


```
dburns in ~/development/selenium on master λ ./go py_prep_for_install_release
(in /Users/dburns/development/selenium)
Shutting down nailgun server...
Using watchman.
[-] PARSING BUCK FILES...FINISHED 0.6s [100%]
[-] BUILDING...FINISHED 3.6s [100%]
Shutting down nailgun server...
Using watchman.
[-] PARSING BUCK FILES...FINISHED 0.4s [100%]
[-] BUILDING...FINISHED 2.8s [100%]
Shutting down nailgun server...
Using watchman.
[-] PARSING BUCK FILES...FINISHED 0.5s [100%]
[-] BUILDING...FINISHED 2.8s [100%]
cp build/cpp/i386/libnoblur.so py/selenium/webdriver/firefox/x86/x_ignore_nofocus.so
cp build/cpp/amd64/libnoblur64.so py/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so
Shutting down nailgun server...
cp buck-out/gen/javascript/atoms/fragments/is-displayed.js py/selenium/webdriver/remote/isDisplayed.js
Shutting down nailgun server...
cp buck-out/gen/javascript/webdriver/atoms/getAttribute.js py/selenium/webdriver/remote/getAttribute.js
cp build/javascript/firefox-driver/webdriver.xpi py/selenium/webdriver/firefox/
cp build/javascript/firefox-driver/webdriver_prefs.json py/selenium/webdriver/firefox/
```

**Comment by davehunt** [comment]
I think `py_prep_for_install_release` could be renamed to make it clearer. Perhaps `py_dependencies` or similar? In fact, if we can get `setup.py` to call `./go py_prep_for_install_release` then we can probably even just remove that from the docs.

After running `py_prep_for_install_release`, you can use `setup.py` to `install`, [`develop`](http://setuptools.readthedocs.io/en/latest/setuptools.html#development-mode), or prepare a release for distribution. We don't currently cover releasing the package in the wiki, which is something else I think we should consider.

**Comment by stupidnetizen** [comment]
> After running py_prep_for_install_release, you can use setup.py to install, develop, or prepare a release for distribution. We don't currently cover releasing the package in the wiki, which is something else I think we should consider

I tried `py_prep_for_install_release` so that could use `develop` with `setup.py` after that. However, it doesn't link the egg properly. I get the below error when I try to import selenium using 
`python -c 'from selenium import webdriver;'`

error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named selenium

```
Am I missing something? 

`python setup.py` install works.

**Comment by davehunt** [comment]
I'm not sure why this isn't working, but I suspect it might be related to the fact we're packaging data files when we install. For now my recommendation would be to use `python setup.py install`. If you're interested in investigating this, I'd happy review/test a pull request.

**Comment by davehunt** [comment]
I believe the documentation is clear. Please feel free to raise a new issue regarding installing the package in editable mode, and we also welcome documentation updates if you feel we can make these clearer. Thank you for raising this issue.

**Comment by purgoufr** [comment]
The code I write is as follows
`from selenium import webdriver
browser = webdriver.Firefox()
browser.get('http://inventwithpython.com')
linkElem = browser.find_element_by_link_text('Read It Online')
type(linkElem)
linkElem.click() # follows the "Read It Online" link
`
The result of the console is as follows;

Traceback (most recent call last):
  File "C:\Users\Purgoufr\Documents\Eclipse Projects\Python\Web_Scraping\Control_browser_with_Selenium.py", line 50, in <module>
    from selenium import webdriver
  File "C:\Python27\lib\selenium\webdriver\__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "C:\Python27\lib\selenium\webdriver\firefox\webdriver.py", line 34, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "C:\Python27\lib\selenium\webdriver\remote\webdriver.py", line 25, in <module>
    from .webelement import WebElement
  File "C:\Python27\lib\selenium\webdriver\remote\webelement.py", line 40, in <module>
    getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
  File "C:\Python27\lib\pkgutil.py", line 591, in get_data
    return loader.get_data(resource_name)
  File "C:\Python27\lib\pkgutil.py", line 255, in get_data
    return open(pathname, "rb").read()
IOError: [Errno 2] No such file or directory: 'C:\\Python27\\lib\\selenium\\webdriver\\remote\\getAttribute.js'

I could not find the 'C:\\Python27\\lib\\selenium\\webdriver\\remote\\getAttribute.js'
Do you have any suggestions?

**Comment by stupidnetizen** [comment]
I think @purgoufr is facing something similar to what @burg was facing when he opened this issue. 
It is strange if this appears even after `./go py_prep_for_install_release`. I haven't tried using the `py` package using eclipse, though.

**Comment by purgoufr** [comment]
Yes it is strawberry. I did not understand why this happened.

**Comment by purgoufr** [comment]
I mean it is strange :) The phone keyboard has automatic word completion feature. Sorry :)
