### ISSUE TITLE
Using Curb client causes 'RuntimeError: can't modify frozen Array'

### ISSUE THREAD

**Issue by clarkenciel** [SeleniumHQ/selenium#2950]
## Meta -

OS: Ubuntu
Selenium Version:  3.0.0
## Expected Behavior -

Users should be able to use the Curb remote client in place of the standard Http client without any trouble.
## Actual Behavior -

Requiring `selenium/webdriver/remote/http/curb.rb` in a file causes a `RuntimeError`.
This is a result of style changes made in commit [cccc9fe4a7b4549bb6aa830397f437286b260f21](https://github.com/SeleniumHQ/selenium/commit/cccc9fe4a7b4549bb6aa830397f437286b260f21). Specifically, the `QUIT_ERRORS` constant in the `Bridge` class was frozen to fit with Rubocop's ["Style/MutableConstants" ](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/MutableConstant) setting. As a result, when `curb.rb` tries to push `Curl::Err::RecvError` into that constant, the `RuntimeError` is thrown.
## Steps to reproduce -

require `selenium/webdriver/remote/http/curb`.

**Comment by titusfortner** [comment]
fixed with #2951 
released in Selenium gem 3.0.4
