### ISSUE TITLE
Unable to setup Selenium Grid v3.0.0 in AWS EC2 using Docker Swarm Mode due to Unknown option: -remoteHost

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/selenium#2952]
## Meta -
OS:  Docker container (https://hub.docker.com/r/selenium/node-chrome/)

Selenium Version:  3.0.0

Browser:  Chrome

Browser Version:  53.0.2785.101-1

## Expected Behavior -
Selenium Grid is successfully setup and all nodes (containers) across hosts are able to talk to each other.
## Actual Behavior -
This set of commands below worked for 2.53.1.
```
docker network create -d overlay gridnet
docker service create --network gridnet --name hub -p 4444:4444 -e JAVA_OPTS='-Xmx512m -DPOOL_MAX=512' -e GRID_TIMEOUT=600000 \
            -e GRID_BROWSER_TIMEOUT=600000 selenium/hub:3.0.0-cerium
docker service create --network gridnet --endpoint-mode dnsrr --name nodes \
            --mount type=bind,source=/dev/shm,target=/dev/shm \
            -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 \
            --replicas 2 selenium/node-chrome:3.0.0-cerium bash -c 'HOSTIP=$(ip -4 addr show eth0 | grep -Po "inet \K[\d.]+") REMOTE_HOST=http://$HOSTIP:5555 /opt/bin/entry_point.sh'
```
Screen shot of working grid -
![image](https://cloud.githubusercontent.com/assets/10567800/19462124/3a7afaac-949f-11e6-90d3-74823d79844f.png)

But on v3.0.0 exited container has this log message when running the commands above -
```
REMOTE_HOST variable is set, appending -remoteHost
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -remoteHost
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:257)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
```
So I changed my command to set SE_OPTS instead of REMOTE_HOST for setting up the Swarm -
```
docker network create -d overlay gridnet
docker service create --network gridnet --name hub -p 4444:4444 -e JAVA_OPTS='-Xmx512m -DPOOL_MAX=512' -e GRID_TIMEOUT=600000 \
            -e GRID_BROWSER_TIMEOUT=600000 selenium/hub:3.0.0-cerium
docker service create --network gridnet --endpoint-mode dnsrr --name nodes \
            --mount type=bind,source=/dev/shm,target=/dev/shm \
            -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 -e NODE_MAX_INSTANCES=5 -e NODE_MAX_SESSION=5 \
            --replicas 2 selenium/node-chrome:3.0.0-cerium bash -c 'HOSTIP=$(ip -4 addr show eth0 | grep -Po "inet \K[\d.]+") SE_OPTS="-hubHost $HOSTIP" /opt/bin/entry_point.sh'
```
I see the following error - DefaultRemoteProxy unknown version,Connect to 172.18.0.3:5555 [/172.18.0.3] failed: Connection refused.
![image](https://cloud.githubusercontent.com/assets/10567800/19461761/5af6c728-949c-11e6-990c-695d42682f59.png)

So, I'd like to know if it's possible to still set the remoteHost in 3.0.0. If not what is the right setting to setup the grid in Swarm mode?

## Steps to reproduce -

1. Create 2 EC2 instances
2. Install latest Docker (1.12.2)
3. Have one instance join as manager and the other as worker in Swarm Mode.
4. Run the commands above to first create an overlay network, then create the hub and node services to setup the grid.

**Comment by mach6** [comment]
remoteHost is not a valid argument in Se3. So, this is a bug in the docker container startup script. The valid options for Se3 are -hub, -hubHost, and -hubPort. If you specify -hub, the other two are not needed. If you only specify -hubHost, port 4444 is assumed.

**Comment by mach6** [comment]
Note: remoteHost is a valid nodeConfig.json key still, however

**Comment by testphreak** [comment]
@mach6 it was indeed marked deprecated today in [entry_point.sh](https://github.com/SeleniumHQ/docker-selenium/blob/master/NodeBase/entry_point.sh). But I'm still not clear on how to get a grid up and running in Se3 using Swarm Mode with remoteHost no longer a valid option. The id for each node on the grid starts with 172.x in Se3 (hence the connection refused) with the commands above instead of 10.x in Se2.53.1 as shown in screen shots above.

**Comment by lukeis** [comment]
-remoteHost for a node is a composite of -host and -port on that node. 'remoteHost' will be generated based on the host / port of the node and will send that value to the hub when registering so the hub knows what host to connect back to.

**Comment by lukeis** [comment]
if you are doing special NATing due to your docker containers and the port the outside world would connect to the node on is different than the port selenium thinks it is running on, then you should use a nodeConfig.json.

If the ports are the same, but you need to have a different host name (or IP) than what selenium is assuming, then use the -host parameter on the node.

**Comment by lukeis** [comment]
based on your last comment, i think you just want to be able to adjust the -host option.

Looks like you need to have the docker project make an enhancement to the scripts for you to be able to specify that. Please log a bug there to allow you to pass a custom host to the entry_point.sh that would then be put in the command line arguments.

but the way it looks like @ddavison coded it... you could set REMOTE_HOST_PARAM to be any arbitrary command line option to do what you need :-D

**Comment by testphreak** [comment]
@lukeis When you say use the -host parameter, do you mean -hubHost(https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridNodeConfiguration.java#L82).

I don't think we have a special setup going on the EC2 instances. To my knowledge, these instances cannot be reached from the outside world and can only be reached by other hosts on the 10.x.x.x subnet.

Will try to set REMOTE_HOST_PARAM as suggested in your latest comment and get back.

**Comment by mach6** [comment]
no. see the `-host` command which tells Se (hub and node only) which IP to bind to when starting the server

```shell
   -host
       <String> IP or hostname : usually determined automatically. Most commonly
       useful in exotic network configurations (e.g. network with VPN)
```

**Comment by lukeis** [comment]
no, i mean `-host`

remoteHost is a composite:
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridNodeConfiguration.java#L194-L205

of the "host" and "port"

Those are defined on the base class that GridNodeConfiguration extends -
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridConfiguration.java#L55
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/StandaloneConfiguration.java#L104

**Comment by lukeis** [comment]
also... i re-read the script... don't use REMOTE_HOST_PARAM... you're supposed to be using SE_OPTS instead :)

**Comment by testphreak** [comment]
@mach6 and @lukeis, finally got it working! Thank you so much for the inputs.

Got the grid up and running by passing in the -host parameter into the nodes service creation command above and dynamically looking up the host name of the running container and passing it to entry_point.sh as SE_OPTS.

```
bash -c 'SE_OPTS="-host $HOSTNAME" /opt/bin/entry_point.sh'
```

**Comment by ddavison** [comment]
ok, yes @testphreak, I wasn't sure exactly what you were trying to get out.

Yes.. you can specify `-host <host> -port <port>` inside of `SE_OPTS` to specify the host and port of the NODE.
