### ISSUE TITLE
Dependency convergence issue in 3.0.0

### ISSUE THREAD

**Issue by mhardin** [SeleniumHQ/selenium#2956]
## Meta -
OS:  
OSX
Selenium Version:  
3.0.0
Browser:  
N/A

If you pull in selenium-server 3.0.0 as a dependency, note that multiple versions of selenium-support (3.0.0 and 3.0.0-beta2) are being pulled in:
```
Dependency convergence error for org.seleniumhq.selenium:selenium-support:3.0.0 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.0
    +-org.seleniumhq.selenium:selenium-java:3.0.0
      +-org.seleniumhq.selenium:selenium-support:3.0.0
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.0
    +-org.seleniumhq.selenium:htmlunit-driver:2.23
      +-org.seleniumhq.selenium:selenium-support:3.0.0-beta2

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.seleniumhq.selenium:selenium-support:3.0.0 paths to dependency are:
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.0
    +-org.seleniumhq.selenium:selenium-java:3.0.0
      +-org.seleniumhq.selenium:selenium-support:3.0.0
and
+-com.retailmenot:selenium-grid-scaler:0.9-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.0.0
    +-org.seleniumhq.selenium:htmlunit-driver:2.23
      +-org.seleniumhq.selenium:selenium-support:3.0.0-beta2
```

**Comment by lukeis** [comment]
i'm aware of the issue... going to need to enhance our version of BUCK to allow us to specify an exclusion in a dependency because we essentially have a circular dependency.

**Comment by lukeis** [comment]
for now, you should add exclusions in your dependencies and add the correct ones explicitly

**Comment by mhardin** [comment]
@lukeis I've handled it on my end, but just wanted to let the project know about this issue since selenium 3.0 was just released and its no longer in beta.

**Comment by shs96c** [comment]
Ohhh... this is interesting. The HTMLUnit driver wants the beta, but the selenium support wants the release version. Isn't this a bug in the way that Maven is resolving version conflicts?

**Comment by lukeis** [comment]
Maven doesn't consider it a bug in itself... would rather users include exclusion tags on dependencies. So we need to change the htmlunit dependency in the generated Pom to exclude selenium :)

**Comment by lukeis** [comment]
should be fixed and will be available in the next release with -

https://github.com/SeleniumHQ/htmlunit-driver/commit/34f5e96d8d4cefb7e2de9b23c51063bc2c07fceb

and 

https://github.com/SeleniumHQ/selenium/commit/7186e1a1d1c8fc5784c984433c3b1972ce935974
