### ISSUE TITLE
Potential Issue with Phantom JS or WebDriver 3.0

### ISSUE THREAD

**Issue by asevans48** [SeleniumHQ/selenium#2957]
OS:   Ubuntu Xenial 16.04
Selenium Version:   3.0
Browser:  PhantomJS (Apple Webkit)

I am going to reference this ticket because of relatively large issue with PhantomJS that occurs when an element is constantly attempted to be accessed. I am trying to run many concurrent tests in PhantomJS using Selenium 3 but continually get the cleanup error. Further inspection of the DEBUG log level output shows that selenium is constantly retrying to find an element which it says exists. The output and issue can be found at the Phantom JS page :  #https://github.com/ariya/phantomjs/issues/14588.

Perhaps you could take a look as well? There are now bugs open on detro/ghostdriver, ariya/phantomjs, and here. Thanks

**Comment by lukeis** [comment]
phantomjs issues should be tracked there, as you've done. If there's something more concrete you see that selenium is doing wrong, please raise an issue here. 

An initial look at the issue you reported, I see nothing that the selenium code is doing wrong.

**Comment by asevans48** [comment]
thanks
