### ISSUE TITLE
How to handle Browser Basic Authentication pop up window using Ruby gem 'selenium-webdriver', '~> 3.0'

### ISSUE THREAD

**Issue by gabayliran** [SeleniumHQ/selenium#2959]
Hi,
Can you please help me or suggest me how should I handle the basic auth pop up window?
I wrote my question in the below URL, seems no one know.

[http://stackoverflow.com/questions/40076112/how-to-handle-browser-basic-authentication-pop-up-window-using-ruby-gem-seleniu/40112317#40112317](url)

*The the basic auth pop up window not from the @driver.get 'url' in my script, first I go to a different website, then click on some link and I got this basic auth pop-up window.

Any help would be appreciated,
Thanks!

**Comment by lukeis** [comment]
Appears you are using firefox. Sorry to say basic auth support is not implemented there.

Geckodriver related bug -
https://github.com/mozilla/geckodriver/issues/273

Selenium bug for basic auth -
https://github.com/SeleniumHQ/selenium/issues/453


they are both still open. Closing this issue as a duplicate.

**Comment by gabayliran** [comment]
thank you @lukeis , I am not sure I understand what is the bug, is it only on firefox or also on chrome? can I send a keys in chrome to basic auth pop up window? is there a way to handle somehow the  basic auth pop up window?
thank you.
