### ISSUE TITLE
Selenium Grid Console unable to detect window OS

### ISSUE THREAD

**Issue by rarelam** [SeleniumHQ/selenium#2961]
## Meta -
OS:  Window 7
Selenium Version:  3
Browser:  not related 

FIREFOX 48+ IS ONLY COMPATIBLE WITH GECKODRIVER. Any issue logged here for 48+ will be closed as a duplicate of #2559

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  
Not related

## Expected Behavior -
Grid console able to detect the correct OS

## Actual Behavior -
Grid console is display mixed OS on a window 7 machine

## Steps to reproduce -
0. Having both selenium node and selenium server to connect in localhost
1. Navigate to grid console UI
2. Check on the OS value showed

![capture](https://cloud.githubusercontent.com/assets/1460421/19507154/90bcbe40-9603-11e6-8d8d-2ecc6d442b97.PNG)

**Comment by mach6** [comment]
"mixed OS" here comes from the capabilities of the node.. Are the hub and node both running on the same machine?

**Comment by rarelam** [comment]
yes, both hub and node run on same machine, and it is default capabilities.

**Comment by mach6** [comment]
Looking at what happens by default on Windows.. The node registers these capabilities;

```json
        "capabilities": [{
            "capabilities": {
                "browserName": "firefox",
                "seleniumProtocol": "WebDriver",
                "maxInstances": 5,
                "platform": "WIN10"
            }
        }, {
            "capabilities": {
                "browserName": "chrome",
                "seleniumProtocol": "WebDriver",
                "maxInstances": 5,
                "platform": "WIN10"
            }
        }, {
            "capabilities": {
                "browserName": "internet explorer",
                "seleniumProtocol": "WebDriver",
                "maxInstances": 1,
                "platform": "WINDOWS"
            }
        }],
```

So, given `platform = { WINDOWS, WIN10 }` (I tested on Windows 10), `mixed OS` is correct.

**Comment by mach6** [comment]
@rarelam thanks for reporting this.. fixed it!
