### ISSUE TITLE
Removing 'version' from capabilities breaks Selenium Hubs CapabilityMatcher

### ISSUE THREAD

**Issue by jabbrwcky** [SeleniumHQ/selenium#2964]
## Meta -

OS:  Windows/Linux Selenium Grid 
Selenium Version:  3.0.0
Browser:  Firefox
Selenium Client ruby 3.0.0
## Expected Behavior -

When requesting a specific version of a browser e.g. Firefox: 49 I expect the hub to forward the request to a node providing this version.
## Actual Behavior -

The Hub redirects the client to any firefox node disregarding the version specified in the desired capabilities.
## Steps to reproduce -

Make a request using the ruby client against a selenium grid requesting a specific firefox version with `marionette: true`

Participants in this issue: 

Specifying `marionette:true` causes the capabilities to call `W3CCapabilities.firefox(opts)`
in [Selenium::WebDriver::Remote::Capabilities#L75](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/capabilities.rb#L75).

`W3CCapabilites` replaces `version` with `browser_version` in [Selenium::WebDriver::Remote::W3CCapabilities#79](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/w3c_capabilities.rb#L79, dropping `version` from the Hash passed as argument.

The `CapabilitiesComparator` builds a [version comparator](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/remote/server/CapabilitiesComparator.java#L64) that uses the Capabilites key [`version`](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/CapabilityType.java#L28) when [retrieving the Version](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DesiredCapabilities.java#L100).

As this key has been deleted, the hub treats the request as a desired browser `firefox` with an unspecified version, resulting in an arbitrary node with any firefox being returned.

As I am not sure about the best approach how to fix it, I have not yet created any pull request. 
My approach to fixing would be to have `DesiredCapabilities.getVersion()` look both into `version` and `browserVersion`, but I am not really familiar with the current code base yet (i.e. is the removed version key really obsolete for all browsers?).

**Comment by mach6** [comment]
is the node registered with the `version` number as a capability for the slot type?

**Comment by titusfortner** [comment]
W3C [wants to see `browserVersion`](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities), not just `version`, which is what Ruby is sending for Marionette and Edge right now (through W3CCapabilities vs Capabilities class).
The standalone server recognizes this, does grid not? I guess I assumed it recognized the same things; do I need to run the tests against grid as well as the standalone server?
It would be possible for Ruby to send both, but I've been trying to keep Marionette W3C commands only.

**Comment by mach6** [comment]
@titusfortner I'm curious. Will you point me to where the server is `doing extra stuff` to the request?

**Comment by titusfortner** [comment]
@lukeis has talked about this before, so I'm mostly ignorantly parroting him. :)

**Comment by lukeis** [comment]
it doesn't do extra anymore :) but the hub does parse the new session request and only (if supplying the default matcher) only looks at 'version' and not 'browserVersion'
https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/DefaultCapabilityMatcher.java#L44

Until we figure out how to change that code to enable both 'version' and 'browserVersion' @titusfortner can you please update ruby to send both keys (with the value) in the new session request

**Comment by jabbrwcky** [comment]
Wouldn't it be a viable way to have the Hub look for 'browserVersion' with a fallback to 'version'?

**Comment by lukeis** [comment]
Yes, which I intend to do... but we weren't planning on needling to do that till 4.0 :)

**Comment by lukeis** [comment]
updated grid 3a616b09ad3094c27ffe9b9ce1599a55315dab5e

**Comment by lukeis** [comment]
@titusfortner i leave it up to you to decide what to do with ruby folk... either they'll need to use 3.0.2+ (and you don't do anything) or you let them still use 2.X and 3.0.0/1 servers with an update :)

**Comment by titusfortner** [comment]
Ruby 3.0.1 now sends JSON Wire Protocol to the Remote server now, so it should be backward compatible on any Grid.
