### ISSUE TITLE
platform.rb assumes stable file ordering -> geckodriver can not be found on TravisCI

### ISSUE THREAD

**Issue by mccalluc** [SeleniumHQ/selenium#2966]
## Meta -

OS:  Linux on TravisCI
Selenium Version:  3.0
Browser:  FF 49.0.1
## Expected Behavior -

Having the tar file in the same directory as the geckodriver executable should not cause problems.

```
TAR=geckodriver-v0.11.1-linux64.tar
wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/$TAR.gz
gunzip $TAR.gz
tar -xvf $TAR
chmod a+x geckodriver
export PATH=$PATH:`pwd`
```
## Actual Behavior -

But it can't find the executable for geckodriver: https://travis-ci.org/Caleydo/caleydo.github.io/builds/168922490#L621

For whatever reason, on Travis the tar file is returned in the listing before the executable file, but the glob matches both of them, and in the ruby code we only see the first one:

selenium/webdriver/common/platform.rb:

```
   116        def find_binary(*binary_names)
   117          paths = ENV['PATH'].split(File::PATH_SEPARATOR)
   118          binary_names.map! { |n| "#{n}.exe" } if windows?
   119          binary_names.each do |binary_name|
   120            paths.each do |path|
   121              full_path = File.join(path, binary_name)
   122              full_path.tr!('\\', '/') if windows?
   123              exe = Dir.glob(full_path).first # *** but for me the executable wasn't first in this list.
   124              next unless exe
   125              return exe if File.executable?(exe)
   126            end
   127          end
```

called from selenium/webdriver/firefox.rb:

```
    49        def self.driver_path
    50          @driver_path ||= begin
    51            path = Platform.find_binary('geckodriver*')
    52            raise Error::WebDriverError, MISSING_TEXT unless path
    53            Platform.assert_executable path
    54            path
    55          end
    56        end
```

By removing the tar file, I got it to work, but it wasn't obvious from the error message what needed to change: `which geckdriver` worked, so why wasn't the ruby code able to find it?

Thanks!

(I don't have a local reproducer: I'm guessing the file ordering is a function of the file system.)

**Comment by titusfortner** [comment]
I think I put the wildcard character there in case versions were specified, which shouldn't be necessary. I'll pull it out and run tests to make sure everything is good.
