### ISSUE TITLE
Selenium grid 3.0.1 hanging on post request forever when starting remote web driver

### ISSUE THREAD

**Issue by omerb4** [SeleniumHQ/selenium#2970]
## Meta -
OS:  Command running from windows 10
Grid is running on windows 7
Selenium Version:  3.0.1, IDE Pycharm
Browser:   Chrome
Browser Version:  53.0.2623.87 

## Expected Behavior -
Post request return status 200 and a browser will be opened
## Actual Behavior -
Post request with the capabilities is hanging forever
## Steps to reproduce -
Run the following python code
from selenium.webdriver import Chrome, Remote
from selenium.webdriver import DesiredCapabilities

selenium_server = env.instance().selenium_server()
capabilities = DesiredCapabilities.CHROME
repo = env.instance().chrome_download_path
capabilities["nativeEvents"] = True
capabilities['chromeOptions'] = {}
capabilities['chromeOptions']['prefs'] = {}
capabilities['chromeOptions']['prefs']['download.prompt_for_download'] = False
capabilities['chromeOptions']['prefs']['download.default_directory'] = repo
Remote(command_executor=selenium_server + "/wd/hub",desired_capabilities=capabilities)

To selenium grid version 3.0.1
(for version 2.53.1 it works)

**Comment by lukeis** [comment]
Can you elaborate more on your grid configuration. This works fine for me.

java -jar selenium-server-standalone-3.0.1.jar -role hub
java -jar selenium-server-standalone-3.0.1.jar -role node

d = w.Remote(desired_capabilities={'browserName':'chrome', 'nativeEvents':True, 'chromeOptions':{'prefs':{'download.prompt_for_download':False, 'download.default_directory':expanduser('~')}}})


If you can provide a way for me to reproduce the issue, we can reopen the issue

**Comment by omerb4** [comment]
I noticed it's not always reproduce but if you will try to run it in loop that at the end of it you quit the driver
you'll reached to a point that you'll be hanged

**Comment by Audace** [comment]
This is happening for me as well.
