### ISSUE TITLE
Navigate to other domain with anchor click

### ISSUE THREAD

**Issue by danielandross** [SeleniumHQ/selenium#2971]
## Meta -
OS:  
Windows Server 2012 R2
Selenium Version:  
selenium server standalone 3.0
Browser:  
Firefox (geckodriver)

Browser Version:  
48 32Bit

## Expected Behavior -
Click on anchor links refering to other domains should succeed.
## Actual Behavior -
Page load Error (even with Manual click done in a window created by selenium server). There is no Firewall / connectivity issue: When doing the test manually in a window not created by Selenium Server the click succeeds.
## Steps to reproduce -
WebDriver firefox = new RemoteWebDriver(
                new URL("http://"+IP_SELENIUM_SERVER+":4444/wd/hub"), DesiredCapabilities.firefox());
firefox.get("http://my.domain");
firefox.manage().timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);
List<WebElement> anchors = firefox.findElements(By.cssSelector("a"));
WebElement anchor = anchors.get(0);
anchor.click();
firefox.manage().timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
