### ISSUE TITLE
Firefox 49, get remote logs cause 'did not match a known command'

### ISSUE THREAD

**Issue by mariusbrn** [SeleniumHQ/selenium#2972]
## Meta -
OS:  Ubuntu 16
Selenium Version:  2.53.3
Browser:  Firefox 49 - GeckoDriver 0.9.0 - Protractor

## Steps to reproduce -
Not sure if it's the right place to post,
Trying to get the browser logs this way:

```
browser.manage().logs().get('browser').then(function(browserLog) { ... }));
```
but i get an error: 
```
WebDriverError: POST /session/36718c58-6808-4ba0-9600-3d33fffc0d30/log did not match a known command
```
NB: works with Chrome.

**Comment by jleyba** [comment]
This is not implemented in GeckoDriver b/c it is not part of the WebDriver spec.

**Comment by lukeis** [comment]
https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by stoich** [comment]
Why isn't this sort of thing handled a bit more gracefully?

**Comment by sjlawsonAL** [comment]
> This is not implemented in GeckoDriver b/c it is not part of the WebDriver spec.

If it's not implemented, shouldn't it throw a NotImplementedException?

**Comment by jimevans** [comment]
@sjlawsonAL Two things. First, the readthedocs.io documentation isn’t the official Selenium Python documentation. Second, the Selenium API may have methods that do not correspond to any documented by the [W3C WebDriver Specification](https://w3c.github.io/webdriver/). For remote ends that strictly implement the spec, and geckodriver is one of those, the logging APIs will not work.
