### ISSUE TITLE
[Selenium IDE] JavaScript format exporter

### ISSUE THREAD

**Issue by brylie** [SeleniumHQ/selenium#2985]
Are there any plans to create a JavaScript format for Selenium IDE?

**Comment by lukeis** [comment]
since no one has really touched the IDE code in 10 months... probably not? :)

**Comment by Heizer1971** [comment]
@lukeis But why is it like that? Selenium IDE dead?

**Comment by jleyba** [comment]
It's not dead, it just doesn't have an active maintainer (that I'm aware of). AFAIK, none of the core contributors use IDE

**Comment by brylie** [comment]
Cool. We are experimenting with the [selenium-html-js-converter](https://www.npmjs.com/package/selenium-html-js-converter). A direct JavaScript exporter would still be nice. :smiley_cat:

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
