### ISSUE TITLE
Selenium 3.0 - Cannot select item in the dropdown

### ISSUE THREAD

**Issue by nhhphuong** [SeleniumHQ/selenium#2988]
OS: Windows 10
Selenium Version: 3.0.0 (C# library) with geckodriver

Expected Behavior -
Select item in the dropdown

Actual Behavior -
Cannot select item in the dropdown

Steps to reproduce -
Start with Selenium WebDriver 3.0, try to use method: 
new SelectElement(driver.FindElement(By.Name("fromPort"))).SelectByText("London");

**Comment by AutomatedTester** [comment]
I am guessing you are not using Firefox 49, so upgrade. Otherwise, can you give proper steps to replicate. You can reopen with proper steps
