### ISSUE TITLE
Selenium 3 - Script does not run on IE11

### ISSUE THREAD

**Issue by nhhphuong** [SeleniumHQ/selenium#2989]
OS: Windows 10
Selenium Version: 3.0.0 (C# library) with geckodriver
IE: 11.321.14393.0

Expected Behavior -
Run script on IE

Actual Behavior -
It can open IE browser and open URL but it does not run script like as enter username, password,...

Steps to reproduce -
Start with Selenium WebDriver 3.0, try to run script with IEDriverServer 32/64 bit
- Open IE browser
- Set URL
- Script not run (it works fine on Firefox)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
