### ISSUE TITLE
Unable to open url in selenium 3.0.1 with firefox 49.0.2

### ISSUE THREAD

**Issue by raj284** [SeleniumHQ/selenium#2990]
## Meta -
OS:  
OSX 10.10.5 YOSEMITE

Selenium Version:  
3.0.1

Browser:  
Firefox 49.0.2

Code:
  System.setProperty("webdriver.firefox.marionette","/Users/user/Documents/workspace/testproject/res/geckodriver");
	   driver = new FirefoxDriver();
	   driver.manage().window().maximize();
	   driver.get("https://www.google.co.in");
	   driver.quit();

## Expected Behavior -
It should launch the browser

## Actual Behavior -
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1476898573000,"updateDate":1476898573000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.2","maxVersion":"49.0.2"}],"targetPlatforms":[],"seen":true}
1477199230136	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1477199230137	DeferredSave.extensions.json	DEBUG	Save changes
1477199230137	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477199230137	addons.xpi-utils	DEBUG	Updating add-on states
1477199230145	addons.xpi-utils	DEBUG	Writing add-ons list
1477199230147	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477199230148	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477199230149	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1477199230149	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477199230151	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477199230151	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477199230151	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477199230152	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Starting provider: GMPProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477199230160	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477199230160	addons.manager	DEBUG	Starting provider: PluginProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477199230161	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477199230161	addons.manager	DEBUG	Completed startup sequence
1477199230444	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477199230444	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477199230444	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477199230449	DeferredSave.extensions.json	DEBUG	Starting write
1477199230574	addons.repository	DEBUG	No addons.json found.
1477199230574	DeferredSave.addons.json	DEBUG	Save changes
1477199230577	DeferredSave.addons.json	DEBUG	Starting timer
1477199230601	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477199230602	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477199230603	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477199230607	DeferredSave.extensions.json	DEBUG	Write succeeded
1477199230608	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477199230629	DeferredSave.addons.json	DEBUG	Starting write
1477199230643	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at consult.google.openBrowser(google.java:16)
	at consult.google.main(google.java:28)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1476898573000,"updateDate":1476898573000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.2","maxVersion":"49.0.2"}],"targetPlatforms":[],"seen":true}
1477199230136	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1477199230137	DeferredSave.extensions.json	DEBUG	Save changes
1477199230137	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477199230137	addons.xpi-utils	DEBUG	Updating add-on states
1477199230145	addons.xpi-utils	DEBUG	Writing add-ons list
1477199230147	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477199230148	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477199230149	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1477199230149	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477199230151	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477199230151	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477199230151	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477199230152	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Starting provider: GMPProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477199230160	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477199230160	addons.manager	DEBUG	Starting provider: PluginProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477199230161	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477199230161	addons.manager	DEBUG	Completed startup sequence
1477199230444	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477199230444	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477199230444	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477199230449	DeferredSave.extensions.json	DEBUG	Starting write
1477199230574	addons.repository	DEBUG	No addons.json found.
1477199230574	DeferredSave.addons.json	DEBUG	Save changes
1477199230577	DeferredSave.addons.json	DEBUG	Starting timer
1477199230601	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477199230602	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477199230603	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477199230607	DeferredSave.extensions.json	DEBUG	Write succeeded
1477199230608	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477199230629	DeferredSave.addons.json	DEBUG	Starting write
1477199230643	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.

Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Rajeshs-MacBook-Pro-2.local', ip: '192.168.0.5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_65'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at consult.google.openBrowser(google.java:16)
	at consult.google.main(google.java:28)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1476898573000,"updateDate":1476898573000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.2","maxVersion":"49.0.2"}],"targetPlatforms":[],"seen":true}
1477199230136	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1477199230137	DeferredSave.extensions.json	DEBUG	Save changes
1477199230137	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477199230137	addons.xpi-utils	DEBUG	Updating add-on states
1477199230145	addons.xpi-utils	DEBUG	Writing add-ons list
1477199230147	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477199230148	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1477199230148	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477199230149	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1477199230149	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477199230151	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477199230151	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477199230151	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477199230152	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477199230152	addons.manager	DEBUG	Starting provider: GMPProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477199230160	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477199230160	addons.manager	DEBUG	Starting provider: PluginProvider
1477199230160	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477199230161	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477199230161	addons.manager	DEBUG	Completed startup sequence
1477199230444	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477199230444	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477199230444	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477199230449	DeferredSave.extensions.json	DEBUG	Starting write
1477199230574	addons.repository	DEBUG	No addons.json found.
1477199230574	DeferredSave.addons.json	DEBUG	Save changes
1477199230577	DeferredSave.addons.json	DEBUG	Starting timer
1477199230601	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477199230602	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477199230603	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477199230607	DeferredSave.extensions.json	DEBUG	Write succeeded
1477199230608	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477199230629	DeferredSave.addons.json	DEBUG	Starting write
1477199230643	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 9 more

**Comment by lukeis** [comment]
You are setting the wrong property to specify the path to GeckoDriver. The one you are using if not set to "true" will force the old webdriver extension instead of GeckoDriver. 

Use webdriver.gecko.driver instead of webdriver.firefox.marionette

**Comment by AkshitaJauhari** [comment]
I am using the Version Selenium 3.0  and  trying to launch Mozilla firefox 54 version using Geckodriver - V0.15 but the below error comes:
KeyError: 'sessionId'

Any Suggestions

**Comment by lmtierney** [comment]
@AkshitaJauhari You will need to update Selenium to 3.3+ to use that new of geckodriver/Firefox. For future questions, please ask the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
