### ISSUE TITLE
Facing issue with Selenium - Chrome on Macbook Pro

### ISSUE THREAD

**Issue by RishiChitransh** [SeleniumHQ/selenium#3004]
This is a duplicate of this issue:

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7094

but as that conversation is closed. Hence logging a new issue for the resolution.

**Comment by lukeis** [comment]
that issue was moved to chromedirver -

https://bugs.chromium.org/p/chromedriver/issues/detail?id=736

please follow up with the chromedriver project
