### ISSUE TITLE
Unable to send url data into Mozila browser.

### ISSUE THREAD

**Issue by gudu1994** [SeleniumHQ/selenium#3005]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0

Browser:  Mozila 49.0.2 

Browser Version:  

## Expected Behavior -
Url string should be send by get method.
## Actual Behavior -
Browser is opening but get() is unable to send URL string to browser.
## Steps to reproduce -
IDE: Eclipse Neon 0.1 
`public static void main(String[] args) {
                    System.setProperty("webdriver.firefox.marionette","F:\\Eclipse\\geckodriver.exe");
		   
		   WebDriver driver=new FirefoxDriver();
		   
		   driver.get("http://www.google.com");
		   
	       System.out.println("Application title is ============="+driver.getTitle());

	       driver.quit();

		}`
 Error Log:
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi	DEBUG	Updating database with changes to installed add-ons
1477418070470	addons.xpi-utils	DEBUG	Updating add-on states
1477418070472	addons.xpi-utils	DEBUG	Writing add-ons list
1477418070476	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477418070477	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477418070477	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477418070478	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477418070479	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477418070480	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477418070483	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477418070484	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477418070484	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477418070484	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477418070485	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477418070486	addons.manager	DEBUG	Starting provider: GMPProvider
1477418070501	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477418070501	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477418070503	addons.manager	DEBUG	Starting provider: PluginProvider
1477418070504	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477418070504	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477418070505	addons.manager	DEBUG	Completed startup sequence
1477418072076	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477418072077	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477418072080	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477418072455	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477418072456	DeferredSave.extensions.json	DEBUG	Starting timer
1477418072479	DeferredSave.extensions.json	DEBUG	Starting write
1477418072501	addons.repository	DEBUG	No addons.json found.
1477418072503	DeferredSave.addons.json	DEBUG	Save changes
1477418072509	DeferredSave.addons.json	DEBUG	Starting timer
1477418072563	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477418072563	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477418072564	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477418072570	DeferredSave.addons.json	DEBUG	Starting write
1477418072579	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072618	DeferredSave.addons.json	DEBUG	Write succeeded
1477418084775	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1477418084776	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1477418084777	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1477418085297	addons.manager	DEBUG	shutdown
1477418085298	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1477418085298	addons.xpi	DEBUG	shutdown
1477418085298	addons.xpi-utils	DEBUG	shutdown
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1477418085304	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1477418085305	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1477418085308	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1477418085315	addons.xpi	DEBUG	Notifying XPI shutdown observers
1477418085322	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at sel.com.cf.sel.main(sel.java:11)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
xpi	DEBUG	Updating database with changes to installed add-ons
1477418070470	addons.xpi-utils	DEBUG	Updating add-on states
1477418070472	addons.xpi-utils	DEBUG	Writing add-ons list
1477418070476	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477418070477	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477418070477	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477418070478	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477418070479	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477418070480	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477418070483	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477418070484	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477418070484	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477418070484	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477418070485	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477418070486	addons.manager	DEBUG	Starting provider: GMPProvider
1477418070501	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477418070501	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477418070503	addons.manager	DEBUG	Starting provider: PluginProvider
1477418070504	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477418070504	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477418070505	addons.manager	DEBUG	Completed startup sequence
1477418072076	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477418072077	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477418072080	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477418072455	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477418072456	DeferredSave.extensions.json	DEBUG	Starting timer
1477418072479	DeferredSave.extensions.json	DEBUG	Starting write
1477418072501	addons.repository	DEBUG	No addons.json found.
1477418072503	DeferredSave.addons.json	DEBUG	Save changes
1477418072509	DeferredSave.addons.json	DEBUG	Starting timer
1477418072563	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477418072563	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477418072564	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477418072570	DeferredSave.addons.json	DEBUG	Starting write
1477418072579	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072618	DeferredSave.addons.json	DEBUG	Write succeeded
1477418084775	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1477418084776	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1477418084777	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1477418085297	addons.manager	DEBUG	shutdown
1477418085298	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1477418085298	addons.xpi	DEBUG	shutdown
1477418085298	addons.xpi-utils	DEBUG	shutdown
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1477418085304	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1477418085305	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1477418085308	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1477418085315	addons.xpi	DEBUG	Notifying XPI shutdown observers
1477418085322	addons.manager	DEBUG	Async provider shutdown done

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'DESKTOP-HJP61AI', ip: '10.1.0.44', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at sel.com.cf.sel.main(sel.java:11)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi	DEBUG	Updating database with changes to installed add-ons
1477418070470	addons.xpi-utils	DEBUG	Updating add-on states
1477418070472	addons.xpi-utils	DEBUG	Writing add-ons list
1477418070476	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477418070477	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477418070477	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477418070478	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477418070479	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477418070480	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477418070483	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477418070484	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477418070484	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477418070484	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477418070485	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477418070486	addons.manager	DEBUG	Starting provider: GMPProvider
1477418070501	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477418070501	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477418070503	addons.manager	DEBUG	Starting provider: PluginProvider
1477418070504	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477418070504	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477418070505	addons.manager	DEBUG	Completed startup sequence
1477418072076	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477418072077	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477418072080	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477418072455	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072456	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477418072456	DeferredSave.extensions.json	DEBUG	Starting timer
1477418072479	DeferredSave.extensions.json	DEBUG	Starting write
1477418072501	addons.repository	DEBUG	No addons.json found.
1477418072503	DeferredSave.addons.json	DEBUG	Save changes
1477418072509	DeferredSave.addons.json	DEBUG	Starting timer
1477418072563	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477418072563	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477418072564	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477418072570	DeferredSave.addons.json	DEBUG	Starting write
1477418072579	DeferredSave.extensions.json	DEBUG	Write succeeded
1477418072618	DeferredSave.addons.json	DEBUG	Write succeeded
1477418084775	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1477418084776	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1477418084777	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1477418085297	addons.manager	DEBUG	shutdown
1477418085298	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1477418085298	addons.xpi	DEBUG	shutdown
1477418085298	addons.xpi-utils	DEBUG	shutdown
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1477418085300	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1477418085304	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1477418085305	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1477418085308	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1477418085315	addons.xpi	DEBUG	Notifying XPI shutdown observers
1477418085322	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by lukeis** [comment]
where did you find documentation that you should set "webdriver.firefox.marionette" ? I'd like to know, since you're not the first to log an issue with this problem.

If you set that to something other than 'true' it will default to NOT using geckodriver.

To set the geckodriver path you need to set the property "webdriver.gecko.driver"  But would be better to use the constant `GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY`

**Comment by gudu1994** [comment]
@lukeis 
Check this issue again...
`public static void main(String[] args) {
System.setProperty("GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY","F:\\Eclipse\\geckodriver.exe");
			 WebDriver driver=new FirefoxDriver();
		   driver.get("https://www.google.com");
	       driver.quit();
		}`

Error Log:
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
-app-global","version":"5.0.248.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://saff/content/siteadvisor.gif","icon64URL":null,"defaultLocale":{"name":"McAfee WebAdvisor","description":null,"creator":"McAfee Inc.","homepageURL":"http://www.siteadvisor.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\McAfee\\SiteAdvisor\\saffplg.xpi","installDate":1476667808985,"updateDate":1476667808985,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":296974,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"26.0","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1477421439012	DeferredSave.extensions.json	DEBUG	Save changes
1477421439012	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477421439012	addons.xpi-utils	DEBUG	Updating add-on states
1477421439014	addons.xpi-utils	DEBUG	Writing add-ons list
1477421439019	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477421439019	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477421439020	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477421439021	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477421439022	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477421439022	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477421439025	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477421439026	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477421439026	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477421439026	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477421439026	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477421439027	addons.manager	DEBUG	Starting provider: GMPProvider
1477421439042	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477421439043	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477421439044	addons.manager	DEBUG	Starting provider: PluginProvider
1477421439045	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477421439045	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477421439046	addons.manager	DEBUG	Completed startup sequence
1477421440797	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477421440798	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477421440801	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477421441732	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441732	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477421441732	DeferredSave.extensions.json	DEBUG	Starting timer
1477421441767	addons.repository	DEBUG	No addons.json found.
1477421441768	DeferredSave.addons.json	DEBUG	Save changes
1477421441786	DeferredSave.addons.json	DEBUG	Starting timer
1477421441915	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477421441919	DeferredSave.extensions.json	DEBUG	Starting write
1477421441926	DeferredSave.addons.json	DEBUG	Starting write
1477421441964	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441972	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at sel.com.cf.sel.main(sel.java:13)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
-app-global","version":"5.0.248.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://saff/content/siteadvisor.gif","icon64URL":null,"defaultLocale":{"name":"McAfee WebAdvisor","description":null,"creator":"McAfee Inc.","homepageURL":"http://www.siteadvisor.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\McAfee\\SiteAdvisor\\saffplg.xpi","installDate":1476667808985,"updateDate":1476667808985,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":296974,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"26.0","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1477421439012	DeferredSave.extensions.json	DEBUG	Save changes
1477421439012	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477421439012	addons.xpi-utils	DEBUG	Updating add-on states
1477421439014	addons.xpi-utils	DEBUG	Writing add-ons list
1477421439019	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477421439019	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477421439020	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477421439021	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477421439022	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477421439022	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477421439025	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477421439026	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477421439026	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477421439026	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477421439026	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477421439027	addons.manager	DEBUG	Starting provider: GMPProvider
1477421439042	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477421439043	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477421439044	addons.manager	DEBUG	Starting provider: PluginProvider
1477421439045	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477421439045	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477421439046	addons.manager	DEBUG	Completed startup sequence
1477421440797	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477421440798	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477421440801	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477421441732	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441732	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477421441732	DeferredSave.extensions.json	DEBUG	Starting timer
1477421441767	addons.repository	DEBUG	No addons.json found.
1477421441768	DeferredSave.addons.json	DEBUG	Save changes
1477421441786	DeferredSave.addons.json	DEBUG	Starting timer
1477421441915	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477421441919	DeferredSave.extensions.json	DEBUG	Starting write
1477421441926	DeferredSave.addons.json	DEBUG	Starting write
1477421441964	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441972	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'DESKTOP-HJP61AI', ip: '10.1.0.44', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at sel.com.cf.sel.main(sel.java:13)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
-app-global","version":"5.0.248.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://saff/content/siteadvisor.gif","icon64URL":null,"defaultLocale":{"name":"McAfee WebAdvisor","description":null,"creator":"McAfee Inc.","homepageURL":"http://www.siteadvisor.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\McAfee\\SiteAdvisor\\saffplg.xpi","installDate":1476667808985,"updateDate":1476667808985,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":296974,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"26.0","maxVersion":"44.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1477421439012	DeferredSave.extensions.json	DEBUG	Save changes
1477421439012	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1477421439012	addons.xpi-utils	DEBUG	Updating add-on states
1477421439014	addons.xpi-utils	DEBUG	Writing add-ons list
1477421439019	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1477421439019	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1477421439020	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1477421439021	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1477421439022	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1477421439022	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1477421439025	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1477421439026	addons.manager	DEBUG	Provider finished startup: XPIProvider
1477421439026	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1477421439026	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1477421439026	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1477421439027	addons.manager	DEBUG	Starting provider: GMPProvider
1477421439042	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1477421439043	addons.manager	DEBUG	Provider finished startup: GMPProvider
1477421439044	addons.manager	DEBUG	Starting provider: PluginProvider
1477421439045	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1477421439045	addons.manager	DEBUG	Provider finished startup: PluginProvider
1477421439046	addons.manager	DEBUG	Completed startup sequence
1477421440797	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1477421440798	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1477421440801	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1477421441732	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441732	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1477421441732	DeferredSave.extensions.json	DEBUG	Starting timer
1477421441767	addons.repository	DEBUG	No addons.json found.
1477421441768	DeferredSave.addons.json	DEBUG	Save changes
1477421441786	DeferredSave.addons.json	DEBUG	Starting timer
1477421441915	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1477421441916	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1477421441919	DeferredSave.extensions.json	DEBUG	Starting write
1477421441926	DeferredSave.addons.json	DEBUG	Starting write
1477421441964	DeferredSave.extensions.json	DEBUG	Write succeeded
1477421441972	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by lukeis** [comment]
Use the constant... don't make a string out of the variable...
