### ISSUE TITLE
Can not control multiple Internet Explorer instances simultaneously

### ISSUE THREAD

**Issue by jonnyaih** [SeleniumHQ/selenium#3010]
## Meta -

OS: Windows 10
Selenium Version: IDE 2.52.0,  IEDriverServer 32bit 2.53.1
Browser Version: Internet Explorer 11,  Firefox 45.4
## Expected Behavior -

testcase1 and testcase2 will be work simultaneously as in FirefoxDriver or ChromeDriver
## Actual Behavior -

testcase2 will be work afrer finishing testcase1
## Steps to reproduce -
1. Run selenium testcase1 in IEDriver in one thread
2. Run same selenium testcase2 in IEDriver in other thread at same time
3. Wait for starting testcase 2

**Comment by hazmeister** [comment]
Hi @jonnyaih ,

IEDriver is taking the safest option here, as Internet Explorer does not really support profiles like Firefox and Chrome.  The upshot of this is that separate tests would share the same browser session, cookies and some clicks would fail where browser focus is needed.  The full details are [here](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#multiple-instances-of-internetexplorerdriver).

The recommended workaround would be to setup Selenium grid and connect to multiple VMs.

**Comment by AutomatedTester** [comment]
Unfortunately this is by design of IE and not really something we can fix as the above comment suggests
