### ISSUE TITLE
Ajax calls are not triggered in Microsoft Edge 13 when we are automating the website with  Edge WebDriver

### ISSUE THREAD

**Issue by rohitbang2** [SeleniumHQ/selenium#3011]
Hi I am trying to automate an eCommerce Website on Microsoft edge 13, I am able to navigate till product display page, but when i click add to cart button , there are back end ajax calls which are triggered in the application , which we are not able to handle in Edge 13,  is there any resolution to handle ajax calls in Edge 13

**Comment by lukeis** [comment]
Please log Microsoft Edge issues with Microsoft -

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
