### ISSUE TITLE
selenium 2.53 ignores user.js for firefox profile specified at  -Dwebdriver.firefox.profile option

### ISSUE THREAD

**Issue by Andrei-Stepanov** [SeleniumHQ/selenium#3013]
Remote is: 
Linux RHEL 6.7.z 
firefox-38.0.1-1.el6_6.i686
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.4.el6-i386 u79-b14)
OpenJDK Client VM (build 24.79-b02, mixed mode, sharing)

java -Dwebdriver.firefox.profile=spiceqe -jar selenium-server-standalone.jar -port 55555 -trustAllSSLcertificates

FF profile was created with:
firefox -CreateProfile spiceqe

I have putted to "spiceqe" profile user.js with contents:
cat ~/.mozilla/firefox/3jyoevip.spiceqe/user.js 
user_pref("browser.helperApps.neverAsk.openFile","application/x-virt-viewer");

Selenium runs this FF with profile that doesn't have line from my  user.js:
cat /tmp/userprofile5138234491145127815copy/user.js 
user_pref("browser.helperApps.neverAsk.openFile","application/x-virt-viewer");

cat /tmp/anonymous331561482743872663webdriver-profile/user.js 
user_pref("extensions.update.notifyUser", false);
user_pref("devtools.errorconsole.enabled", true);
user_pref("security.csp.enable", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("datareporting.healthreport.logging.consoleEnabled", false);
user_pref("xpinstall.whitelist.required", false);
user_pref("dom.disable_open_during_load", false);
user_pref("offline-apps.allow_by_default", true);
user_pref("extensions.blocklist.enabled", false);
user_pref("browser.startup.page", 0);
user_pref("toolkit.telemetry.rejected", true);
user_pref("dom.max_chrome_script_run_time", 30);
user_pref("browser.usedOnWindows10.introURL", "about:blank");
user_pref("prompts.tab_modal.enabled", false);
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("toolkit.networkmanager.disable", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("network.manage-offline-status", false);
user_pref("browser.search.update", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("browser.link.open_newwindow", 2);
user_pref("extensions.autoDisableScopes", 10);
user_pref("browser.EULA.override", true);
user_pref("browser.EULA.3.accepted", true);
user_pref("security.warn_entering_weak", false);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("browser.safebrowsing.enabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("webdriver_accept_untrusted_certs", true);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("dom.max_script_run_time", 30);
user_pref("xpinstall.signatures.required", false);
user_pref("javascript.options.showInConsole", true);
user_pref("network.http.max-connections-per-server", 10);
user_pref("network.http.phishy-userpass-length", 255);
user_pref("extensions.logging.enabled", true);
user_pref("browser.offline", false);
user_pref("security.warn_leaving_secure", false);
user_pref("browser.link.open_external", 2);
user_pref("browser.laterrun.enabled", false);
user_pref("signon.rememberSignons", false);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", false);
user_pref("browser.newtab.url", "about:blank");
user_pref("javascript.enabled", true);
user_pref("webdriver_enable_native_events", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("security.fileuri.origin_policy", 3);
user_pref("security.fileuri.strict_origin_policy", false);
user_pref("webdriver_assume_untrusted_issuer", true);
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "about:blank");
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("security.warn_submit_insecure", false);
user_pref("webdriver_firefox_port", 7055);
user_pref("dom.report_all_js_exceptions", true);
user_pref("browser.selfsupport.url", "");
user_pref("security.warn_viewing_mixed", false);
user_pref("browser.displayedE10SNotice", 4);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_viewing_mixed.show_once", false);

As you can see there is no my option:
user_pref("browser.helperApps.neverAsk.openFile","application/x-virt-viewer");

**Comment by lukeis** [comment]
webdriver does not use user.js, that is an RC only construct.

**Comment by Andrei-Stepanov** [comment]
I am running:

http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar

@lukeis could you please provide more information ?

It is just not clear what you mean.

**Comment by Andrei-Stepanov** [comment]
I connect to selenium-server-standalone-2.53.1.jar from remote client using python bindings webdriver.Remote

**Comment by Andrei-Stepanov** [comment]
Okay, webdriver doesn't use user.js. 
In my case: user.js is a part of Firefox profile.
I specify Firefox profile for Webdriver.
Webdriver uses Firefox profile, but user.js is a part of Firefox profile!
It should not be ignored.

**Comment by lukeis** [comment]
user.js is just "an alternative method of modifying preferences" ? Why don't you just set the preferences using selenium? And if you want it pre-canned, create a profile with them set and then use that custom profile?

I don't think we want to support this.
