### ISSUE TITLE
Suddenly having multiple issues with Ruby selenium-webdriver ex.. ECONNREFUSED, browser window closing...

### ISSUE THREAD

**Issue by maxiedaniels** [SeleniumHQ/selenium#3020]
OS:  Mac 10.11.6
selenium-webdriver 3.0.0 (Ruby)
Browser:  Chrome, Firefox, Safari

Suddenly when I tried to use selenium-webdriver today to automate my browser, I'm getting all sorts of strange issues.

1) I'm getting ``rescue in block in connect': Failed to open TCP connection to 127.0.0.1:4444 (Connection refused - connect(2) for "127.0.0.1" port 4444) (Errno::ECONNREFUSED)`
This error has popped up with every browser I've tried... with Chrome, my ruby script crashes after the browser pops up, the browser window stays open (shows "data;" in the URL). When trying Firefox and Safari, the browser window pops up and my script freezes... when I ctrl+C, I get the above error.

2) In Firefox and Safari, I won't see any errors, including the one above, until I ctrl+C (after the browser window opens). After I hit ctrl+C, exceptions such as selenium not seeing a page link show up, but not until I hit ctrl+C... which has never been the case before. Normally I see exceptions straight away..

Sorry for posting this in the general selenium github, but I figure it's the best place since I'm experiencing problems on multiple browsers. Any thoughts on what caused this massive change in behavior?

**Comment by luke-hill** [comment]
Whilst I'm scared this could descend into generic comments. `data;` is not a concern, it is a "Holding page" Whilst Webdriver loads up the page. Typically you only see it on Internet_Explorer as that's a slower browser connection

**Comment by lukeis** [comment]
This isn't enough information to really go on. Something seems problematic on your machine. Could you please email the selenium-users google group for suggestions and then if you encounter a legitimate bug in the selenium code, post back here.

https://groups.google.com/forum/#!forum/selenium-users

I can say that our CI system shows that selenium isn't generically broken and is working for us.

**Comment by ayosuva** [comment]
@maxiedaniels ,I am also facing the same issue when pop up gets close then the browser window stays open and shows "data;" in the URL. Have you found any work around for the same?
