### ISSUE TITLE
Failed to launch multiple firefox instances

### ISSUE THREAD

**Issue by dnovikau** [SeleniumHQ/selenium#3021]
**Meta -**
OS:  Windows 10, OSX
Selenium Version:  
3.0.\* IDE
Browser:  
Firefox 47+ 
Java 1.8 + TestNg 6.9.13.6

Starting from Selenium 3.0 I'm getting the 'IllegalStateException' when trying to run multiple instances of firefox in different threads. 

**Expected Behavior -**
Two instances of firefox browser are started

**Actual Behavior -**
Driver in thread 1 starts normally but Driver in thread 2 faile to starts with the error: 
java.lang.IllegalStateException: Profile passed to options is different from existing profile that has been set.
at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at org.openqa.selenium.firefox.FirefoxOptions.setProfileSafely(FirefoxOptions.java:84)
at org.openqa.selenium.firefox.FirefoxDriver.populateProfile(FirefoxDriver.java:211)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)

**Steps to reproduce**
1. Create driver using the following code
String pathToBinary = "validPathToGekcoDriverExecutable";
Preconditions.checkNotNull(pathToBinary);
System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY, pathToBinary);
FirefoxProfile profile = new ProfilesIni().getProfile("validFirefoxProfileName");
FirefoxDriver firefoxWebDriver = new FirefoxDriver(new FirefoxBinary(), firefoxProfile, capabilities);
2. Run TestNg suite with the following example:
[smoke.txt](https://github.com/SeleniumHQ/selenium/files/555457/smoke.txt)

**Comment by nilols** [comment]
Not sure if you still have a problem with this, but if this is the same issue as I had, then the first thread will populate the capabilities with a `FirefoxOptions` object containing the profile used in the driver for the first thread, when the second thread creates a new driver, and if the same capabilities instance is reused, then the capabilities object already contain this `FirefoxOptions`object with the profile from the first thread, resulting in a `IllegalStateException`.

Try this
`FirefoxDriver firefoxWebDriver = new FirefoxDriver(new FirefoxBinary(), firefoxProfile, new DesiredCapabilities(capabilities));`

**Comment by barancev** [comment]
Should be fixed in version 3.5, please reopen the issue if it's not true.
(We have a regression test that proves it works)
