### ISSUE TITLE
Grid client times out waiting for browser, but a place in the queue and a browser still getting blocked

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [SeleniumHQ/selenium#3022]
## Meta -

OS:
Windows 7  

Selenium Version:
Grid: 2.53.1, Client: Selenium.WebDriver for .NET 3.0.0

Browser:
Remote Web Driver - (using Ghost Driver)
## Expected Behavior -

It is expected that when all the browsers are taken, and a timeout is thrown from the client's constructor: 
`new RemoteWebDriver(new Uri("http://127.0.0.1:4444/wd/hub/"), DesiredCapabilities.PhantomJS())`  
the client should disconnect from the http request that requested a browser, and that the grid, upon noticing this, should remove the request from the queue so that a browser is not needlessly held reserved without anyone using it.
## Actual Behavior -

`new RemoteWebDriver(...)` throws a timeout, but a place in the queue is still taken, and when the browser becomes available it's held reserved until some timeout.
This is especially severe when using [the default -1 newSessionWaitTimeout](https://github.com/SeleniumHQ/selenium/blob/b97704fa76678d540adbb9661ae2fda6789dc0c0/java/server/src/org/openqa/grid/internal/utils/configuration/GridHubConfiguration.java#L71), which makes all requests live forever to do this blocking. While changing this setting alleviates the issue, not removing the request from the queue still causes an unnecessary congestion of browsers reservations.

[This stackoverflow](http://stackoverflow.com/questions/7474345/grid-hub-http-client-timeout-if-waiting-for-a-slot-to-be-free/7477034#7477034) suggests that issue exists with Ruby client as well, so possibly is a problem with Grid itself.
## Steps to reproduce -
1. Spin up grid with 0 browsers.
2. Attempt to connect with client and observe timeout exception (`new RemoteWebDriver(..., ..., TimeSpan.FromSeconds(5))` will make it appear fast)
3. See how the requests are still in the queue

**Comment by barancev** [comment]
Can you please retest in Selenium version 3.13? I've found that it removes the new session request from the queue after timeout.

(Yes, default -1 value of -newSessionWaitTimeout is dangerous, but it's a different issue.)

**Comment by barancev** [comment]
Closing the issue as version 2.53 is out of date.
