### ISSUE TITLE
ChromeDriver proxy not working??

### ISSUE THREAD

**Issue by maxiedaniels** [SeleniumHQ/selenium#3025]
## Meta -

OS:  10.11.6
Selenium Version:  
3.0.0
Browser:  
## Chrome

I'm experiencing a very strange bug with ChromeDriver (using Ruby)...

```
@proxy = "proxy:port goes here"
Capybara.register_driver :selenium do |app|
        prefs = {"download" => {"default_directory" => DownloadHelpers::PATH.to_s, "directory_upgrade" => true, "extensions_to_open" => ""}}
        proxy = Selenium::WebDriver::Proxy.new(:type => :manual, :http => @proxy)
        caps = Selenium::WebDriver::Remote::Capabilities.chrome(:proxy => proxy)
        caps['chromeOptions'] = {'prefs' => prefs}
        Capybara::Selenium::Driver.new(app, :detach => false, :browser => :chrome, :desired_capabilities => caps)
    end
```

Here is my Ruby code. When I run the code, Chrome opens, but when I go to website to check my IP, it's not showing the proxy address. If I put in 'about:' in the URL and hit enter, I get the command list, which shows "--proxy-server=http=69.63.114.3:3128" in the list of commands, so it seems it is being inserted.. but it's not using it for some reason. If I go to preferences in that Chrome instance, it says it's using the system proxy and does _not_ say it's using a manual proxy, which could be part of the problem...

Any ideas?

**Comment by maxiedaniels** [comment]
Okay, I've narrowed it down.
A) There's definitely a bug, likely with ChromeDriver, where it's inserting the wrong command line option. It should be inserting "--proxy-server=IP:PORT", but it's inserting "--proxy-server=http=IP:PORT".

B) I've tried providing the argument directly instead, but Chrome isn't even using the argument. I can't see it in "about:"... Code below.
```
Capybara.register_driver :selenium do |app|
		# prefs = {"download" => {"default_directory" => DownloadHelpers::PATH.to_s, "directory_upgrade" => true, "extensions_to_open" => ""}}
		# proxy = Selenium::WebDriver::Proxy.new(:type => :manual, :http => @proxy)
		caps = Selenium::WebDriver::Remote::Capabilities.chrome("chromeOptions" => {"args" => ["--proxy-server=#{@proxy}"]})
		Capybara::Selenium::Driver.new(app, :detach => false, :browser => :chrome, :desired_capabilities => caps)
	end
```

**Comment by titusfortner** [comment]
You can run your Capybara code with $DEBUG=true to see the input and output
to the driver for creating the session. If it is an issue with what is
sent,  I'll have to fix it. If it is an issue with what is returned, then
we'll close this and you can file the bug with chromedriver.

**Comment by kramaricsgyorgy** [comment]
Hi All,
There's must be something. I'm using java, please see my issue:
http://stackoverflow.com/questions/40305669/selenium-webdriver-3-0-1-chromedriver-exe-2-25-whitelisted-ips

**Comment by titusfortner** [comment]
@maxiedaniels - are you still having this issue? I'm closing as a Chromedriver bug unless it can be demonstrated it is a Selenium problem.
