### ISSUE TITLE
Throws org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.

### ISSUE THREAD

**Issue by Bonsomer** [SeleniumHQ/selenium#3026]
## Meta -
OS:  Windows Server 2008 R2
Selenium Version:  
Selenium-standalone 3.0.0
Browser:  
Google Chrome
Browser Version:  
 v53.0.2785.116

## Expected Behavior -
Should throw NoSuchElementException or even found elements(it worked sometimes for me)
## Actual Behavior -
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:57 -0700'
os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
## Steps to reproduce -
Could reproduce it if search for element like:
button[data-id=something];
li[data-original-index=something];

Probably because it doesn't include ordinary quotes, cause this button[data-id='something']; format works and founds elements as it should.
## Backtrace
`
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:465)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:430)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
`

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
