### ISSUE TITLE
Appium not clicking on all element recieved from client, but returns success to client.

### ISSUE THREAD

**Issue by Ayoaudu** [SeleniumHQ/selenium#3031]
Dear team, i was creating an automated test using appium. However, after appium exits the for loop in the code below, it does not click on the login button, but it returns success to eclipse. see code below.

    import org.testng.annotations.Test;
    
    import java.io.IOException;
    import java.net.URL;
    
    import io.appium.java_client.AppiumDriver;
    import io.appium.java_client.android.AndroidDriver;
    import io.appium.java_client.remote.MobileCapabilityType;
    
    import org.openqa.selenium.WebElement;
    import org.openqa.selenium.remote.DesiredCapabilities;
    import org.testng.annotations.BeforeClass;
    
    public class NewTest {
      AppiumDriver<WebElement> dr;
    	
    @BeforeClass
    public void setup() throws IOException{
    	DesiredCapabilities first = new DesiredCapabilities();
    	first.setCapability(MobileCapabilityType.DEVICE_NAME, "donatello");
    	first.setCapability(MobileCapabilityType.APP_ACTIVITY,"com.myapplication.MainActivity");
    	first.setCapability(MobileCapabilityType.APP_PACKAGE,"com.myapplication");
    	dr=new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"),first);
    }
      
    	@Test
      public void launchapp() throws Throwable {
    	Thread.sleep(9000);
    	//insert pin
    	for (int i =0; i<5; i ++){
    	dr.findElementByXPath("//android.view.View[@content-desc='1']").click();
    	System.out.println("I clicked" + i );
    	Thread.sleep(1000);
    	}
    	//click login
    	Thread.sleep(4000);
    	dr.findElementByXPath("//android.view.View[@index='2']").click();
    	System.out.println("I clicked Login");
    	Thread.sleep(9000);
      }
    }

Kindly assist

**Comment by mach6** [comment]
please ask this question to appium java_client -- https://github.com/appium/java-client
