### ISSUE TITLE
How can I detect a GeoLocation Permission Request when using Selenium

### ISSUE THREAD

**Issue by TheFifthFreedom** [SeleniumHQ/selenium#3041]
I'd like to be able to tell when a given website I'm accessing through a Selenium-enabled browser is asking permission for my geolocation, like this [one](https://wtfsigfd.com/).

I'm aware that a number of issues have to do with how to handle the popups that are related to permissions requests, since they're not WebElements per se and so cannot be interacted with using Selenium, but I'm only interested in knowing whether a geolocation request was made to my browser as runtime - no need to clear the popup associated with that request.

![screen shot 2016-11-01 at 12 08 23 pm](https://cloud.githubusercontent.com/assets/6109621/19896809/f42c9efa-a02b-11e6-9efd-18b4472689b3.png)

OS:  macOS Sierra 10.12
Selenium Version:  2.53.1 w. ChromeDriver 2.25
Browser:  Chrome 54.0.2840.71 (64-bit)

**Comment by lukeis** [comment]
This isn't specified in our spec how to deal with geo location appropriately.

https://w3c.github.io/webdriver/webdriver-spec.html

I would recommend logging a bug with the w3c spec - 
https://github.com/w3c/webdriver/issues

I'm uncertain if chromedriver implemented anything not in the spec to allow you to deal with this. Feel free to ask on the selenium-users google group to see if anyone else knows.
https://groups.google.com/forum/#!forum/selenium-users
