### ISSUE TITLE
Click() does not return any response on Safari 10.0.1, selenium 3.0.1

### ISSUE THREAD

**Issue by vaggos2002** [SeleniumHQ/selenium#3045]
## Description
The click method does not return any response on the Safari 10.0.1, Python Selenium 3.0.1 on OS X El Capitan. 

## Meta
OS:  OSX El Capitan 10.11.6 (15G1108)
Selenium Version:  3.0.1 (installed from https://pypi.python.org/pypi/selenium)
Browser: Safari
Browser Version:  10.0.1 (11602.2.14.0.7) (64 bit)

## Expected Behavior
The button is clicked.

## Actual Behavior
No response is returned. No error message is returned

## Steps to reproduce
1. Initiate the Safari WebDriver
2. Find an element by ID
3. Execute the click() function

## Python script
```
from selenium import webdriver

driver = webdriver.Safari()
driver.get('http://localhost:8000')
element = driver.find_element_by_id("submit")
element.click()
```

**Comment by lukeis** [comment]
Please log Safari driver issues with Apple.

https://bugreport.apple.com/

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
