### ISSUE TITLE
WebElement cannot be wrapped in a Proxy

### ISSUE THREAD

**Issue by nebehr** [SeleniumHQ/selenium#3047]
Sometimes it is necessary to wrap a WebElement in a proxy - the most obvious choice could be java.lang.reflect.Proxy. However, existing implementation does not allow to use such proxied WebElements as arguments in the calls to JavascriptExecutor.executeScript().

Normally Proxy instance is created by specifying a set of interfaces that it should implement, but in WebElementToJsonConverter.apply() (https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/internal/WebElementToJsonConverter.java#L53) which is used from executeScript() there is a test for a RemoteWebElement concrete class which proxy obviously cannot model.

One way to circumvent this would be to have proxy implement WrapsElement, but it would require additional logic to distinguish between invocations of WrapsElement methods and everything else. Would it be possible in WebElementToJsonConverter to test for HasIdentity instead of RemoteWebElement? I am not sufficiently familiar with Selenium's internal API but it does not look unreasonable to me on first glance.

Pertains both to Selenium 3.0 and earlier versions.

**Comment by lukeis** [comment]
It would be helpful if you could show some example code of how you would expect the WebElement to be wrapped in a proxy and in that code demonstrate when the problem occurs. Even better would be a failing test for the selenium test suite.

**Comment by nebehr** [comment]
Here is a quick and dirty example: https://gist.github.com/nebehr/16de1e1742d9f70159d782fe2c5290cc. I do not propose to discuss this implementation which in this particular case is pretty much useless, but for demonstration purposes it will serve.

It will throw the following exception:

Exception in thread "main" java.lang.IllegalArgumentException: Argument is of an illegal type: com.sun.proxy.$Proxy0
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:80)

It is possible to include other interfaces in the proxy, such as WrapsElement but then one would have to add extra (and non-obvious) code in WebElementHandler.invoke() to specifically handle WrapsElement calls. The problem as I see it is in WebElementToJsonConverter.apply() which tests for RemoteWebElement which is a concrete class whereas judging by the code HasIdentity interface should be sufficient.
