### ISSUE TITLE
WebDriverException.getMessage() is sometimes very-very slooooooooooooow

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#3048]
## Meta -
OS:   Any
Selenium Version:   2.x, 3.0.0, 3.0.1
Browser:   Any

## Expected Behavior -
Method `WebDriverException.getMessage` must be fast! Always. It must not depend on system/network configuration.

## Actual Behavior -
Sometimes method `WebDriverException.getMessage` is very, very slow because it tries to resolve host name/IP and add this "system information" to the error message.

## Steps to reproduce -

Given a machine with `/etc/hosts` file that **does not contain its hostname**.
For example, my laptop currently has name:
```bash
>hostname 
Andreis-MacBook-Pro-3.local
```

But file `/etc/hosts` does not contain this name:
```bash
>cat /etc/hosts
127.0.0.1	localhost Andreis-MacBook-Pro-2.local
```

In this case, method `WebDriverException.getMessage` is very-very slow because it tries to resolve current host name:

```java
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:-1)
	  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	  at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	  - locked <0xbf3> (a java.lang.Object)
	  at org.openqa.selenium.WebDriverException.getSystemInformation(WebDriverException.java:72)
	  at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:63)
	  at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:53)
```

I believe it's **not needed**.
Selenium **should not** try to resolve host name. 
Selenium **should not** add host name to the exception message. It's **not a Selenium job**. 

It's responsibility of QA engineer who runs tests to configure proper logging and other infrastructure. 

## My proposal

I suggest to remove method `WebDriverException.getSystemInformation`, or at least remove host name resolving from it.

**Comment by asolntsev** [comment]
I prepared a pull request for resolving this issue: https://github.com/SeleniumHQ/selenium/pull/3049

**Comment by kenshir007** [comment]
I need to check that. I'll leave a feedback whether it worked.

**Comment by barancev** [comment]
Please check if f0f8def65c86f030c9bf54e810bb68e79cda6da7 fixes the issue, it's included in release 3.2

**Comment by asolntsev** [comment]
@barancev Thank you! I will try it.

**Comment by asolntsev** [comment]
@AutomatedTester Sorry, I could not try, because this issue is hardly reproducible. If I encounter this problem once more, I will create another issue. 

@barancev Thank you for fixing it!
