### ISSUE TITLE
Selenium doesn't work when browser language not in English.

### ISSUE THREAD

**Issue by sergentrif** [SeleniumHQ/selenium#3050]
## Meta -
OS:  OSX
Selenium Version:  3.10.8
Browser:  Google Chrome Version 54.0.2840.87

My e2e tests are not working when my browser is in French. Yet, when I set it up in English, everything works fine.

I had not this problem before.

Have a nice day.

**Comment by cgoldberg** [comment]
and what does "tests are not working" mean?

**Comment by sergentrif** [comment]
Browser is opening right, but instead of writing text in a login form, it waits until the timeout occurs.

I don't know Selenium so I won't be a great help. I just needed to execute tests in a project I joined recently and found this weird behavior.

**Comment by luke-hill** [comment]
That could be a multitude of issues. Firstly I would debug whether items such as, the page / the "box" and the "type" of box has loaded correctly. Sounds like a trip to the selenium docs are in order

**Comment by lukeis** [comment]
what is selenium 3.10.8?

Can you be more descriptive in your setup? Are you using standalone-server? Which programming language are your tests in? How do you launch the browser? What code can you show to reproduce the issue once the browser is started?

When you provide a way to reproduce this more clearly we can reopen the issue.
