### ISSUE TITLE
Selenium 3.0.0 does not wait for browser navigation with Firefox

### ISSUE THREAD

**Issue by FFLSH** [SeleniumHQ/selenium#3053]
Meta -
OS:  Windows 8
Selenium Version:  3.0.0
Browser:  Firefox 49.0.1

Expected Behavior -
When changing pages the Web Driver should wait until the browser has finished navigation.

Actual Behavior -
When changing pages the Web Driver does not wait until the browser has finished navigation.

Steps to Reproduce:

1. Clone the sample repository from https://github.com/FFLSH/Selenium3NoPageLoadWait
2. Uninstall any Firefox instances from your machine
3. Install Firefox 47.0.1
4. In the sample repository, open the SampleProject solution
5. In the Selenium2-53-1Sample project, open the UnitTest1 test class
4. Run the TestMethod1 test.
5. Note that the assertion correctly happens after the browser has navigated i.e. the web driver waits for navigation
6. Uninstall Firefox 47.0.1
7. Install Firefox 49.0.1
4. In the sample repository, open the SampleProject solution
5. In the Selenium-3-Sample project, open the UnitTest1 test class
4. Run the TestMethod1 test.
5. Note that the assertion incorrectly happens before the browser has navigated i.e. the web driver does not wait for navigation

This seems to be a regression between 2.53.1 and 3.0.0.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
