### ISSUE TITLE
Methods in actions class are not working. Ex: doubleclick

### ISSUE THREAD

**Issue by rajckumar38** [SeleniumHQ/selenium#3058]
## Meta -
OS:  Windows 8.1

Selenium Version:  3.0.0 C#

Browser:  Firefox
<!-- Internet Explorer?  Firefox? 
 
Methods in actions class are not working. Ex: doubleclick, sendkeys.

Steps to reproduce:

Actions ac=new Actions(dr);
ac.sendkeys(openqa.selenium.keys.home);

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.
