### ISSUE TITLE
Latest selenium-webdriver package requires Node.js 6.9.0, but Node.js 4 is still in its active LTS period

### ISSUE THREAD

**Issue by marco-c** [SeleniumHQ/selenium#3059]
https://github.com/nodejs/LTS/#lts-schedule

Node.js 4 will still be an active LTS release for some time.

**Comment by jleyba** [comment]
Our support window only covers the most recent LTS:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/README.md#node-support-policy

For background see #1280

**Comment by marco-c** [comment]
I see, why did you decide to de-support active LTS releases so quickly? Your initial decision in https://github.com/SeleniumHQ/selenium/issues/1280#issuecomment-158138538 looks much better to me.

**Comment by jleyba** [comment]
1. I want to be able to adopt new language features in a reasonable time frame.
2. I'm not interested in testing a wide range of node versions with each release. I'm the only one on the project working on the JS client and have a hard enough time keeping up with the main project (notice 3.0 shipped a month late)
3. The structure of the current support window plays into the (probably too generous) timetable outlined in #2969

**Comment by marco-c** [comment]
> I want to be able to adopt new language features in a reasonable time frame.

Fair enough, although there aren't so many new language features in 6.9 compared to 4. Holding off for a while could be worth it.
Have you considered using a transpiler?
