### ISSUE TITLE
Upgrading From 3.0.0 beta2 to 3.0.1 has broken my tests

### ISSUE THREAD

**Issue by dvngnt** [SeleniumHQ/selenium#3060]
## Meta -
OS:  Windows 7

Selenium Version:  3.0.1

Browser:  Chrome Firefox

Browser Version:  

Chrome Version 54.0.2840.87 m
Firefox Version 49.0.2

## Expected Behavior -
After creating a remote webdriver instance the test suite should continue to the test method without error
## Actual Behavior -
After creating a remote webdriver instance I receive the following message:

Nov 04, 2016 2:12:46 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Nov 04, 2016 2:12:48 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

The happens every time a new browser is created. The test will continue to run up until a certain point then the browser will fail to be created and all of the remaining tests will be skipped. 
## Steps to reproduce -

This is the part of the before method that seems to give me trouble.
@BeforeMethod(alwaysRun = true)
	@Parameters("myBrowser")
	public void beforemethod(String myBrowser, Method method) throws InterruptedException, MalformedURLException{
		RemoteWebDriver driver = null;
		if(myBrowser.equals("chrome")){
			new DesiredCapabilities();
			DesiredCapabilities capabilities = DesiredCapabilities.chrome();
			capabilities.setBrowserName("chrome");
			capabilities.setPlatform(Platform.WINDOWS);
		    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
			driver.manage().window().maximize();
		}
}

Console prints the info message at the new RemoteWebDriver line. 

**chrome_node.json:**
{
  "capabilities":
  [
    {
	  "platform": "WINDOWS",  		
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444"
}

**start_hub.bat** which is used to start the hub
c:
cd %userprofile%\automated-testing\src\grid
java -jar selenium-server-standalone-3.0.1.jar -role hub -hubConfig %userprofile%\automated-testing\src\grid\grid_hub.json
cmd /k

**grid_hub.json**
{
  "host": null,
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "browserTimeout": 0,
  "jettyMaxThreads":-1,
  "maxSessions":10
}

**start_chrome_node.bat** which is used to start the node and connect to the hub
c:
cd %userprofile%\automated-testing\src\grid
java -jar -Dwebdriver.chrome.driver=%userprofile%\automated-testing\src\grid\chromedriver.exe selenium-server-standalone-3.0.1.jar -role node -nodeConfig %userprofile%\automated-testing\src\grid\chrome_node.json 
cmd /k

**chrome_node.json**
{
  "capabilities":
  [
    {
      "platform": "WINDOWS",  		
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444"
}

**Comment by barancev** [comment]
INFO messages are just info. What's the actual error?

**Comment by dvngnt** [comment]
Sorry when I upgraded I was getting those messages for the first time and everything was red so I assumed that I misconfigured the grid. Everything is working. Thank You
