### ISSUE TITLE
Upgrade guide from selenium-webdriver for nodejs 2.53.2 to 3.0.0

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#3062]
Upgrading from  selenium-webdriver for nodejs 2.53.2 to version 3 seems to be quite a task and it would really help to have some upgrade guide that details where the breaking changes in the API and how to migrate the existing code.

**Comment by jleyba** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

**Comment by doberkofler** [comment]
@jleyba I did read the change log but with the amount of changes, I believe that an migration document explaining how to migrate existing code would be very helpful.

**Comment by jleyba** [comment]
Are you talking about the promise manager deprecation ( #2969)? Yeah, I can throw together a guide for that.

**Comment by doberkofler** [comment]
@jleyba I think this would be very helpful.

**Comment by jleyba** [comment]
I've updated the wiki with tips on migrating:

https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs

**Comment by manoj9788** [comment]
Speaking version of these changes could be found soon during the SeConf in April. Thanks Jason.
