### ISSUE TITLE
IE authentication does not work with Selenium 3.0.1

### ISSUE THREAD

**Issue by lorenlai** [SeleniumHQ/selenium#3068]
## Meta -
OS:  Windows 7
Selenium Version: 3.0.1
Browser:  IE 11

## Expected Behavior -
When I used Selenium 2.53 with IE 11 the code (see below) did work for IE popup authentication.
After upgrade to Selenium 3.0.1 it does not work anymore. I thought I can re-use this code.

## Actual Behavior -
IE popup authentication window does not work with Selenium 3.0.1

## Steps to reproduce -
CODE which worked in Selenium 2.53, but not in Selenium 3.0.1
         
        String username = "myUserID";
        String pwd = "myPWD";
        WebDriverWait wait = new WebDriverWait(driver, 10);
        Alert alert = wait.until(ExpectedConditions.alertIsPresent());
        alert.authenticateUsing(new UserAndPassword(username, pwd));

**Comment by jimevans** [comment]
The Selenium upgrade isn't the problem; an IE update is.

**Comment by diemol** [comment]
Closing as we didn't get more information from the OP
