### ISSUE TITLE
With Selenium v2.53.x and v3.x is the timeOut and browserTimeout in seconds or milliseconds?

### ISSUE THREAD

**Issue by testphreak** [SeleniumHQ/selenium#3071]
The [official documentation](https://github.com/SeleniumHQ/selenium/wiki/Grid2) seems to indicate that it's in seconds, but we are seeing some timeout errors in our runs, so I wanted to confirm.

On that page it says -

1. -timeout 30 (300 is default) The timeout in seconds before the hub automatically releases a node that hasn't received any requests for more than the specified number of seconds.
2.  On the hub you can also set -browserTimeout 60 to make the maximum time a node is willing to hang inside the browser 60 seconds.

Does [this](https://github.com/SeleniumHQ/selenium/blob/f1daf662a0622b87918b389885f4016f8c81f867/java/server/src/org/openqa/grid/internal/utils/configuration/StandaloneConfiguration.java#L77) and [this](https://github.com/SeleniumHQ/selenium/blob/f1daf662a0622b87918b389885f4016f8c81f867/java/server/src/org/openqa/grid/internal/utils/configuration/StandaloneConfiguration.java#L118) confirm that it is indeed in seconds and not milliseconds?

Also what is [newSessionWaitTimeout](https://github.com/SeleniumHQ/selenium/blob/f1daf662a0622b87918b389885f4016f8c81f867/java/server/src/org/openqa/grid/internal/utils/configuration/GridHubConfiguration.java#L68)?

Is StandaloneConfiguration.java the correct class to look for parameters that can be passed to the grid hub?

**Comment by testphreak** [comment]
Also, thinking aloud, should there be a grid3 page instead of having both grid v2 and grid v3 information on the same page?

**Comment by AutomatedTester** [comment]
@mach6 ?

**Comment by mach6** [comment]
Yes, the values should be specified in seconds. Internally, the code converts (multiplies by 1000) the specified values to milliseconds.

Note: when you see this message, the values are converted to/displayed as milliseconds
```shell
SessionCleaner initialized with insideBrowserTimeout ....
```

On the documentation front, I'm not sure there are enough differences (at least that was the goal -- we may have failed here) to warrant a separate Grid3 document. That said, pull requests are welcome  :)

**Comment by testphreak** [comment]
Thanks @mach6! So the default value set for `ENV GRID_TIMEOUT 30000` [here](https://github.com/SeleniumHQ/docker-selenium/blob/master/Hub/Dockerfile#L18), should in fact be `ENV GRID_TIMEOUT 300` since that's the default as per official wiki?

**Comment by mach6** [comment]
@testphreak The default from the code perspective is `1800` seconds (30 min). The wiki is currently wrong here for Se3. I'll have to cross check the default in Se2 and update the wiki accordingly

`300` would 5 min

**Comment by diemol** [comment]
Closing as there were no more replies to this thread.
