### ISSUE TITLE
IEDriverserver: "SetFocus API call failed" eror has been thrown while setting value in input element

### ISSUE THREAD

**Issue by sujayn105** [SeleniumHQ/selenium#3075]
While setting value in input element which is not in view port, the page scroll to top corner by moving all other element out of browser focus. 

The trace log has reported SetFocus API call failed" eror has been thrown while setting value in input element.

Environment details:

OS:Win7
Java: JDK 8
selenium-server-standalone-3.0.1
IEDriverserver 3.0.0

Below is the IE driver trace log.

T 2016-11-04 17:36:05:185 server.cc(174) Entering Server::ProcessRequest
T 2016-11-04 17:36:05:185 server.cc(238) Entering Server::ReadRequestBody
T 2016-11-04 17:36:05:185 server.cc(183) Process request with: URI: /session/6be4324f-0826-4b20-865d-1dd58656e8d9/element/3f0f24dc-1d1e-49d8-9734-77ee64325089/value HTTP verb: POST
body: {"id":"3f0f24dc-1d1e-49d8-9734-77ee64325089","value":["a"]}
T 2016-11-04 17:36:05:185 server.cc(272) Entering Server::DispatchCommand
T 2016-11-04 17:36:05:185 server.cc(579) Entering Server::LookupCommand
D 2016-11-04 17:36:05:185 server.cc(281) Command: POST /session/6be4324f-0826-4b20-865d-1dd58656e8d9/element/3f0f24dc-1d1e-49d8-9734-77ee64325089/value {"id":"3f0f24dc-1d1e-49d8-9734-77ee64325089","value":["a"]}
T 2016-11-04 17:36:05:185 server.cc(395) Entering Server::LookupSession
T 2016-11-04 17:36:05:186 IESession.cpp(212) Entering IESession::ExecuteCommand
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(165) Entering IECommandExecutor::OnSetCommand
T 2016-11-04 17:36:05:186 command.cc(31) Entering Command::Deserialize
D 2016-11-04 17:36:05:186 command.cc(36) Raw JSON command: { "name" : "sendKeys", "locator" : { "sessionid" : "6be4324f-0826-4b20-865d-1dd58656e8d9", "id" : "3f0f24dc-1d1e-49d8-9734-77ee64325089" }, "parameters" : {"id":"3f0f24dc-1d1e-49d8-9734-77ee64325089","value":["a"]} }
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(176) Entering IECommandExecutor::OnExecCommand
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(499) Entering IECommandExecutor::DispatchCommand
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(616) Entering IECommandExecutor::GetCurrentBrowser
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(622) Entering IECommandExecutor::GetManagedBrowser
T 2016-11-04 17:36:05:186 IECommandExecutor.cpp(572) Entering IECommandExecutor::IsAlertActive
T 2016-11-04 17:36:05:186 Browser.cpp(707) Entering Browser::GetActiveDialogWindowHandle
T 2016-11-04 17:36:05:186 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2016-11-04 17:36:05:186 IECommandExecutor.cpp(586) No alert handle is found
T 2016-11-04 17:36:05:187 IECommandExecutor.cpp(616) Entering IECommandExecutor::GetCurrentBrowser
T 2016-11-04 17:36:05:187 IECommandExecutor.cpp(622) Entering IECommandExecutor::GetManagedBrowser
T 2016-11-04 17:36:05:187 Browser.cpp(200) Entering Browser::GetContentWindowHandle
T 2016-11-04 17:36:05:187 Browser.cpp(410) Entering Browser::GetTopLevelWindowHandle
T 2016-11-04 17:36:05:187 IESession.cpp(233) Beginning wait for response length to be not zero
T 2016-11-04 17:36:05:189 IECommandHandler.cpp(40) Entering IECommandHandler::GetElement
T 2016-11-04 17:36:05:189 IECommandExecutor.cpp(713) Entering IECommandExecutor::GetManagedElement
T 2016-11-04 17:36:05:189 ElementRepository.cpp(31) Entering ElementRepository::GetManagedElement
T 2016-11-04 17:36:05:199 IECommandExecutor.cpp(616) Entering IECommandExecutor::GetCurrentBrowser
T 2016-11-04 17:36:05:199 IECommandExecutor.cpp(622) Entering IECommandExecutor::GetManagedBrowser
T 2016-11-04 17:36:05:199 Browser.cpp(120) Entering Browser::GetDocument
T 2016-11-04 17:36:05:199 Browser.cpp(607) Entering Browser::GetDocumentFromWindow
T 2016-11-04 17:36:05:201 Element.cpp(307) Entering Element::GetLocationOnceScrolledIntoView
T 2016-11-04 17:36:05:201 Element.cpp(438) Entering Element::GetLocation
T 2016-11-04 17:36:05:202 Element.cpp(574) Entering Element::IsInline
D 2016-11-04 17:36:05:203 Element.cpp(484) Element is a block element, using IHTMLElement2::getBoundingClientRect
T 2016-11-04 17:36:05:209 Element.cpp(595) Entering Element::RectHasNonZeroDimensions
T 2016-11-04 17:36:05:211 Element.cpp(611) Entering Element::GetFrameDetails
T 2016-11-04 17:36:05:211 Element.cpp(901) Entering Element::GetContainingDocument
D 2016-11-04 17:36:05:214 Element.cpp(636) Element is in a frame.
T 2016-11-04 17:36:05:214 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:220 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:224 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:228 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:231 Element.cpp(944) Entering Element::GetParentDocument
D 2016-11-04 17:36:05:233 Element.cpp(672) Located host frame. Attempting to get hosting element
T 2016-11-04 17:36:05:233 Script.cpp(44) Entering Script::Initialize
T 2016-11-04 17:36:05:233 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-11-04 17:36:05:233 Script.cpp(164) Entering Script::Execute
T 2016-11-04 17:36:05:233 Script.cpp(472) Entering Script::CreateAnonymousFunction
D 2016-11-04 17:36:05:234 Element.cpp(729) Successfully found frame hosting element
T 2016-11-04 17:36:05:234 DocumentHost.cpp(306) Entering DocumentHost::GetDocumentDimensions
T 2016-11-04 17:36:05:234 DocumentHost.cpp(285) Entering DocumentHost::IsStandardsMode
T 2016-11-04 17:36:05:238 Element.cpp(39) Entering Element::Element
T 2016-11-04 17:36:05:240 Element.cpp(438) Entering Element::GetLocation
T 2016-11-04 17:36:05:240 Element.cpp(574) Entering Element::IsInline
D 2016-11-04 17:36:05:241 Element.cpp(484) Element is a block element, using IHTMLElement2::getBoundingClientRect
T 2016-11-04 17:36:05:245 Element.cpp(595) Entering Element::RectHasNonZeroDimensions
T 2016-11-04 17:36:05:247 Element.cpp(611) Entering Element::GetFrameDetails
T 2016-11-04 17:36:05:247 Element.cpp(901) Entering Element::GetContainingDocument
D 2016-11-04 17:36:05:248 Element.cpp(561) Element is not in a frame
T 2016-11-04 17:36:05:248 Element.cpp(850) Entering Element::CalculateClickPoint
T 2016-11-04 17:36:05:248 Element.cpp(789) Entering Element::GetClickableViewPortLocation
T 2016-11-04 17:36:05:248 Element.cpp(876) Entering Element::IsLocationInViewPort
T 2016-11-04 17:36:05:248 Element.cpp(789) Entering Element::GetClickableViewPortLocation
W 2016-11-04 17:36:05:248 Element.cpp(892) Y coordinate is out of element area
D 2016-11-04 17:36:05:248 Element.cpp(328) Will need to scroll element into view
T 2016-11-04 17:36:05:250 Element.cpp(438) Entering Element::GetLocation
T 2016-11-04 17:36:05:250 Element.cpp(574) Entering Element::IsInline
D 2016-11-04 17:36:05:251 Element.cpp(484) Element is a block element, using IHTMLElement2::getBoundingClientRect
T 2016-11-04 17:36:05:253 Element.cpp(595) Entering Element::RectHasNonZeroDimensions
T 2016-11-04 17:36:05:255 Element.cpp(611) Entering Element::GetFrameDetails
T 2016-11-04 17:36:05:255 Element.cpp(901) Entering Element::GetContainingDocument
D 2016-11-04 17:36:05:264 Element.cpp(636) Element is in a frame.
T 2016-11-04 17:36:05:264 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:269 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:273 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:275 Element.cpp(944) Entering Element::GetParentDocument
T 2016-11-04 17:36:05:278 Element.cpp(944) Entering Element::GetParentDocument
D 2016-11-04 17:36:05:278 Element.cpp(672) Located host frame. Attempting to get hosting element
T 2016-11-04 17:36:05:278 Script.cpp(44) Entering Script::Initialize
T 2016-11-04 17:36:05:278 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-11-04 17:36:05:278 Script.cpp(164) Entering Script::Execute
T 2016-11-04 17:36:05:278 Script.cpp(472) Entering Script::CreateAnonymousFunction
D 2016-11-04 17:36:05:279 Element.cpp(729) Successfully found frame hosting element
T 2016-11-04 17:36:05:279 DocumentHost.cpp(306) Entering DocumentHost::GetDocumentDimensions
T 2016-11-04 17:36:05:279 DocumentHost.cpp(285) Entering DocumentHost::IsStandardsMode
T 2016-11-04 17:36:05:282 Element.cpp(39) Entering Element::Element
T 2016-11-04 17:36:05:283 Element.cpp(438) Entering Element::GetLocation
T 2016-11-04 17:36:05:283 Element.cpp(574) Entering Element::IsInline
D 2016-11-04 17:36:05:283 Element.cpp(484) Element is a block element, using IHTMLElement2::getBoundingClientRect
T 2016-11-04 17:36:05:286 Element.cpp(595) Entering Element::RectHasNonZeroDimensions
T 2016-11-04 17:36:05:287 Element.cpp(611) Entering Element::GetFrameDetails
T 2016-11-04 17:36:05:287 Element.cpp(901) Entering Element::GetContainingDocument
D 2016-11-04 17:36:05:288 Element.cpp(561) Element is not in a frame
T 2016-11-04 17:36:05:288 Element.cpp(850) Entering Element::CalculateClickPoint
T 2016-11-04 17:36:05:288 Element.cpp(789) Entering Element::GetClickableViewPortLocation
T 2016-11-04 17:36:05:288 Element.cpp(876) Entering Element::IsLocationInViewPort
T 2016-11-04 17:36:05:288 Element.cpp(789) Entering Element::GetClickableViewPortLocation
D 2016-11-04 17:36:05:288 Element.cpp(353) (x, y, w, h): 16, 164, 213, 19
T 2016-11-04 17:36:05:290 Element.cpp(86) Entering Element::IsDisplayed
T 2016-11-04 17:36:05:290 Element.cpp(901) Entering Element::GetContainingDocument
T 2016-11-04 17:36:05:291 Script.cpp(44) Entering Script::Initialize
T 2016-11-04 17:36:05:291 Script.cpp(94) Entering Script::AddArgument(IHTMLElement*)
T 2016-11-04 17:36:05:291 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-11-04 17:36:05:291 Script.cpp(83) Entering Script::AddArgument(bool)
T 2016-11-04 17:36:05:291 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-11-04 17:36:05:291 Script.cpp(164) Entering Script::Execute
T 2016-11-04 17:36:05:291 Script.cpp(472) Entering Script::CreateAnonymousFunction
T 2016-11-04 17:36:05:307 Element.cpp(130) Entering Element::IsEnabled
T 2016-11-04 17:36:05:307 Element.cpp(901) Entering Element::GetContainingDocument
T 2016-11-04 17:36:05:311 Script.cpp(44) Entering Script::Initialize
T 2016-11-04 17:36:05:311 Script.cpp(94) Entering Script::AddArgument(IHTMLElement*)
T 2016-11-04 17:36:05:311 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-11-04 17:36:05:311 Script.cpp(164) Entering Script::Execute
T 2016-11-04 17:36:05:311 Script.cpp(472) Entering Script::CreateAnonymousFunction
I 2016-11-04 17:36:05:318 c:\projects\webdriver\cpp\iedriver\CommandHandlers/SendKeysCommandHandler.h(343) Focus is on a UI element other than the HTML viewer pane.
W 2016-11-04 17:36:05:320 c:\projects\webdriver\cpp\iedriver\CommandHandlers/SendKeysCommandHandler.h(359)  [Windows Error 87]: SetFocus API call failed
W 2016-11-04 17:36:05:322 c:\projects\webdriver\cpp\iedriver\CommandHandlers/SendKeysCommandHandler.h(172) HTML rendering pane does not have the focus. Keystrokes may go to an unexpected UI element.
T 2016-11-04 17:36:05:330 InputManager.cpp(65) Entering InputManager::PerformInputSequence
D 2016-11-04 17:36:05:330 InputManager.cpp(86) Mutex acquired for user interaction.
T 2016-11-04 17:36:05:330 InputManager.cpp(532) Entering InputManager::SendKeystrokes
T 2016-11-04 17:36:05:330 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2016-11-04 17:36:05:331 InputManager.cpp(559) Using SendMessage method for sending keys
T 2016-11-04 17:36:05:331 HookProcessor.cpp(89) Entering HookProcessor::Initialize
T 2016-11-04 17:36:05:331 HookProcessor.cpp(99) Entering HookProcessor::Initialize
T 2016-11-04 17:36:05:331 HookProcessor.cpp(162) Entering HookProcessor::InstallWindowsHook
T 2016-11-04 17:36:05:453 HookProcessor.cpp(239) Entering HookProcessor::Dispose
T 2016-11-04 17:36:05:453 HookProcessor.cpp(192) Entering HookProcessor::UninstallWindowsHook
T 2016-11-04 17:36:05:455 HookProcessor.cpp(239) Entering HookProcessor::Dispose
T 2016-11-04 17:36:05:455 HookProcessor.cpp(89) Entering HookProcessor::Initialize
T 2016-11-04 17:36:05:455 HookProcessor.cpp(99) Entering HookProcessor::Initialize
T 2016-11-04 17:36:05:455 HookProcessor.cpp(162) Entering HookProcessor::InstallWindowsHook
T 2016-11-04 17:36:05:457 HookProcessor.cpp(239) Entering HookProcessor::Dispose
T 2016-11-04 17:36:05:457 HookProcessor.cpp(192) Entering HookProcessor::UninstallWindowsHook
T 2016-11-04 17:36:05:459 HookProcessor.cpp(239) Entering HookProcessor::Dispose
T 2016-11-04 17:36:05:459 HookProcessor.cpp(239) Entering HookProcessor::Dispose
T 2016-11-04 17:36:05:459 response.cc(63) Entering Response::SetSuccessResponse
T 2016-11-04 17:36:05:459 response.cc(69) Entering Response::SetResponse
T 2016-11-04 17:36:05:459 IECommandExecutor.cpp(616) Entering IECommandExecutor::GetCurrentBrowser
T 2016-11-04 17:36:05:459 IECommandExecutor.cpp(622) Entering IECommandExecutor::GetManagedBrowser
T 2016-11-04 17:36:05:459 response.cc(51) Entering Response::Serialize
T 2016-11-04 17:36:05:459 IESession.cpp(242) Found non-zero response length
T 2016-11-04 17:36:05:459 IECommandExecutor.cpp(199) Entering IECommandExecutor::OnGetResponse
T 2016-11-04 17:36:05:460 IECommandExecutor.cpp(328) Entering IECommandExecutor::OnIsSessionValid
D 2016-11-04 17:36:05:460 server.cc(355) Response: {"sessionId":"6be4324f-0826-4b20-865d-1dd58656e8d9","status":0,"value":null}

T 2016-11-04 17:36:05:460 server.cc(408) Entering Server::SendResponseToClient
T 2016-11-04 17:36:05:460 response.cc(36) Entering Response::Deserialize
T 2016-11-04 17:36:05:460 server.cc(462) Entering Server::SendHttpOk

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
