### ISSUE TITLE
Selenium IDE RSpec export broken

### ISSUE THREAD

**Issue by dunban1** [SeleniumHQ/selenium#3077]
## Meta
OS:  OSX 10.11.6
Selenium Version:  
IDE 2.9.1 FF plugin
Browser:  
FireFox

Browser Version:  
49.0.2 (64-bit)

## Actual Behavior - Export RSpec file and it runs with the following errors: 
1.)
${' is not allowed as a global variable name (SyntaxError)
(For example of how it is being used see this blog post: http://elementalselenium.com/tips/6-export-from-selenium-ide notice that they solve the issue by deleting the helper functions. This will not work with more advanced tests that use the helper functions)
2.)
"should" syntax is not supported (see: see:  http://rspec.info/blog/2012/06/rspecs-new-expectation-syntax/)
Exports RSpec file with deprecated syntax and does not replace ${receiver} token

## Description
Currently the Selenium IDE 2.9.1 add-on has an export formatter called Ruby / RSpec / WebDriver but it is broken. It does not properly replace the ${receiver} token (see previous issue https://groups.google.com/forum/#!topic/selenium-users/fLcO7qSFnCA) and it uses the RSpec 1.0 "should" syntax instead of the new RSpec 2.11 or greater "expect" syntax.

This file needs to be updated:
https://github.com/SeleniumHQ/selenium/blob/master/ide/plugins/ruby-format/src/content/formats/ruby-wd-rspec.js

## Steps to reproduce 
0.) Install RSpec (http://rspec.info/)
1.) Install Selenium IDE in FireFox - https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/
2.) Open FireFox
3.) Go to Menu -> tools -> Selenium IDE
4.) Select Selenium IDE window
5.) Create a Test Case
6.) Go to Menu -> File -> Export Test Case ... -> Ruby / RSpec / WebDriver
7.) Save File as test.rb in Rspec spec directory
8.) Run rspec spec/test.rb

**Comment by mayerm94** [comment]
This behavior is also observed when exporting as Ruby/Test::Unit/Webdriver as well

**Comment by ihsansatriawan** [comment]
Anyone have solved this problem ?

**Comment by Tuman829** [comment]
I am running into this issue as well

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
