### ISSUE TITLE
Moving from 3.0.0-beta2 to 3.0.1 breaks ability to run tests in parallel.

### ISSUE THREAD

**Issue by bradley8** [SeleniumHQ/selenium#3078]
## Meta -
OS:  Windows 7 Enterprise 64-bit
Selenium Version: 3.0.1
Browser:  Chrome
Browser Version:  54.0.2840.71 m

## Steps to reproduce -
----Start a Grid using Selenium 3.0.0-beta2 ---- 
java -jar selenium-server-standalone-3.0.0-beta2.jar -role hub -port 4444
java -jar selenium-server-standalone-3.0.0-beta2.jar -role node -hub http://localhost:4444/grid/register -browser "browserName=chrome,version=ANY,maxInstances=10,platform=WINDOWS"

---Start another grid using Selenium 3.0.1 ---
ava -jar selenium-server-standalone-3.0.1 -role hub -port 4445
java -jar selenium-server-standalone-3.0.1 -role node -hub http://localhost:4445/grid/register -browser "browserName=chrome,version=ANY,maxInstances=10,platform=WINDOWS"

---Point tests to Grid 3.0.0-beta2 and tests run in parallel---
var hubUri = new Uri("http://localhost:4444/wd/hub");

---Point exact same test suite to Grid 3.0.1 and tests do not run in parallel. They run, but they only run one at a time, not in parallel---
var hubUri = new Uri("http://localhost:4445/wd/hub");

**Comment by lukeis** [comment]
you haven't provided enough information here for us to troubleshoot what issue you may be having.

Please provide reproducible steps or ask questions on the selenium-users google group -
https://groups.google.com/forum/#!forum/selenium-users

When you provide reproducible steps we can reopen the issue

**Comment by bradley8** [comment]
Sorry, I had the steps to reproduce in the post but they were inside of "`<!--  -->`". 
Palm to Forehead!

**Comment by lukeis** [comment]
can confirm something is quite wrong right now...

<img width="743" alt="screen shot 2016-11-08 at 2 38 08 pm" src="https://cloud.githubusercontent.com/assets/926454/20120270/070b419e-a5c1-11e6-92b7-555a2a869eb1.png">

@mach6 !! :)

**Comment by mach6** [comment]
I have not ran into this but will certainly check. 

what version of chromedriver?

**Comment by mach6** [comment]
Nevermind, re: chromedriver.

Confirmed. This is a registration bug. It will be fixed soon.

**Comment by bradley8** [comment]
Awesome, thank you!

**Comment by lukeis** [comment]
there's a workaround if on the node you specify `-maxSession 10` it will work

**Comment by bradley8** [comment]
excellent, trying that now...
