### ISSUE TITLE
Selenium2Library fail to SELECT pop-uo window

### ISSUE THREAD

**Issue by waikchiu5** [SeleniumHQ/selenium#3079]
OS: Windows 7
Selenium Version:   2.47 and 2.53.1
Browser:   Internet Explorer
Browser Version:  11

I am using Selenium2Library to control the Browser(IE)
There is one button on the webpage. The ID is "confirm"
When the button is clicked, 3 stuff will show at the same time:
1. Alert with OK button
2. Pop-up window
3. Download bar (After closed the Alert)
![capture](https://cloud.githubusercontent.com/assets/15870347/20129286/922cdae4-a689-11e6-9453-44851935c9b9.PNG)

`Click Button          id=confirm`
`Sleep              2s`
`Alert Should Be Present                alert message`
`Sleep                            10s #the pop-up window will load some content`
`Select Window                        title=Reports`
`Sleep                                2s`
`Close Window                       #close the pop-up`

However, the robot will waiting on Select Window. Maybe still searching the target pop-up?
My pop-up will load around 15s at least. So it won't have title of pop-up window.
I cannot get the log.html. The robot won't stop.

**Comment by waikchiu5** [comment]
FYI:
I found that all the Windows Keyword will disabled or cannot use after 3 stuff shown up.
Eg. Log Window Titles...../Get window Titles....

**Comment by ddavison** [comment]
Selenium2Library belongs to [Robot](https://github.com/robotframework/Selenium2Library).  Please open your issue there.  until you can verify this is an issue with Selenium, please don't open issues here :)
