### ISSUE TITLE
Not able to generate Har file with new version of Selenium 3.0.1 and Firefox 49

### ISSUE THREAD

**Issue by satishgowda** [SeleniumHQ/selenium#3083]
## Meta -
OS:  
Windows
Selenium Version:  
3.0.1
Browser:  
Firefox 49

I was working with selenium 2.53 and Firefox 47 version with "netExport-0.9b7.xpi" and firebug version "firebug-2.0.17-fx.xpi" it was working fine to capture network traffic into HAR file
now with new version selenium 3.0.1 and firefox version 49  and i am using "netExport-0.9b7.xpi" and firebug version "firebug-2.0.18-fx.xpi" it is not working fine

I am not able to generate with new version of Selenium and Firefox 
could you please check on this

i referred https://eveningsamurai.wordpress.com/2013/06/29/capturing-network-traffic-using-selenium-webdriverfirebug/

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
