### ISSUE TITLE
Use `Nimbus Screenshot` Firefox plugin in a selenium test

### ISSUE THREAD

**Issue by richi235** [SeleniumHQ/selenium#3084]
## Usecase/Why
It doesn't have to be this special plugin. 
I'm more interested about  the general idea of using test cases for creating documentation screenshots. 

I know taking simple screenshots is possible via selenese too, but (currently) selenese lacks the features to: 

  * mark elements on the page via circles,arrows etc.
  * crop to special ranges of the page, based on the position of elements
  * crop arbitrarily selected rectangles

Additionally doing this "inline" with an existing screenshot plugin does reuse existing functionality and gives a noob-friendly way for doing this.

I suppose using "external" plugins doesn't work because selenium interacts with web elements and they are not web elements but "firefox-elements".

## Some questions
- I know it doesn't work with with firefox 45 and the "old" selenium driver. 
  - Does it work with a new firefox and Marionette?
- Will interaction with other plugins be developed some day in medium or long term?
- Is this "via screenshot plugin way (=A)" a good idea at all? 
  - or would it be better to implement such functionality directly into Selenium (IDE) (=B)
- Is something like this possible in chrome, or will it become possible with servo?
- If I wanted to implement A or B, how much effort would it take? Would A or B be realistic/sensible. (Since I get paid to create a auto-documentation tool, this could happen. And an OpenSource Project would benefit.)

**Comment by lukeis** [comment]
We don't use github issues for discussions, most are not following every issue here. We use issues to help track bugs in the project.

This would be more constructive as a conversation on the google groups:
https://groups.google.com/forum/#!forum/selenium-developers
https://groups.google.com/forum/#!forum/selenium-users

Also know that "selenese" is deprecated and you should be using WebDriver instead. IDE has also become unmaintained, there's no one working on it actively.
