### ISSUE TITLE
Selenium 3.0.1-Grid-Unable to load  IE browser

### ISSUE THREAD

**Issue by santoshchk** [SeleniumHQ/selenium#3088]
OS:  Windows 10

Selenium Version:  3.0.1

Browser:  Internet Explorer

Browser Version:  11

## Steps to reproduce -
1.Started Hub (java -jar selenium-server-standalone-2.53.1.jar -role hub)
2. Started node (java -jar selenium-server-standalone-2.53.0.jar -role node -hub http://10.129.160.54:4444/grid/register  -browser browserName="internet explorer -Dwebdriver.ie.driver=selenium3\iedriver.exe")
3. Executed simple test.

Note :Same script is working fine selenium 2.53.1 version.

**Comment by lukeis** [comment]
The exception message is fairly clear.

It can't find the the IEDriver.exe file. In Selenium 3.0 you will need to specify the java property before the -jar, for example:  `java -Dwebdriver.ie.driver=C:\selenium3\iedriver.exe -jar selenium-server-standalone-3.0.1.jar -role node -hub ....`
