### ISSUE TITLE
CTRL+SHIFT+TAB or CTRL+TAB doesn't switch the view in chrome browser.

### ISSUE THREAD

**Issue by heyitsmesuraj** [SeleniumHQ/selenium#3091]
[Test]
public void chrome()
{
//Create the reference for our browser
IWebDriver driver = new ChromeDriver("c:\\");

////Navigate to google page
driver.Navigate().GoToUrl("http:www.google.com");
IJavaScriptExecutor js = driver as IJavaScriptExecutor;
js.ExecuteScript("window.open()");

driver.SwitchTo().Window(driver.WindowHandles.Last());
driver.Navigate().GoToUrl("http://www.seleniumhq.org/");

//switch focus 
Actions newTab = new Actions(driver);
newTab.KeyDown(Keys.Control).KeyDown(Keys.Shift).SendKeys(Keys.Tab).KeyUp(Keys.Shift).KeyUp(Keys.Control).Build().Perform();
newTab.KeyDown(Keys.Control).SendKeys(Keys.Tab).KeyUp(Keys.Control).Build().Perform();

Console.WriteLine(driver.Url);

//Close the browser
driver.Quit();

}

Issue: 
newTab.KeyDown(Keys.Control).KeyDown(Keys.Shift).SendKeys(Keys.Tab).KeyUp(Keys.Shift).KeyUp(Keys.Control).Build().Perform();
This part of code should display previous tab but not working in chrome.

Selenium version:2.53.1
ChromeDriver version:2.24
OS:windows 7
Browser:Chrome
dot net dll

**Comment by lmtierney** [comment]
I believe this is a chromedriver issue https://bugs.chromium.org/p/chromedriver/issues/detail?id=1554

**Comment by heyitsmesuraj** [comment]
Yes Imtierney, ctrl+t will not work in chrome but that job has already done by this part of code open new tab in chrome "js.ExecuteScript("window.open()"); " Also I can switch handle between  tab but I could not switch the view to another tab by using ctrl+shift+tab key or ctrl+tab key.

**Comment by lmtierney** [comment]
Again, this is a chromedriver issue

**Comment by lmtierney** [comment]
Look at the issues that were merged into that issue as duplicates
