### ISSUE TITLE
Invalid usage of process.kill

### ISSUE THREAD

**Issue by arboreal84** [SeleniumHQ/selenium#3093]
## Expected
`process.kill(signal: Number)`

## Actual
`process.kill(signal: String)`

## Code
https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/javascript/node/selenium-webdriver/io/exec.js#L97
https://github.com/SeleniumHQ/selenium/blob/ba56ad1ae0b98a1fe1efdd2163c62fc847950178/javascript/node/selenium-webdriver/remote/index.js#L282

# Note
In newer versions of node, node will crash instead of implicitly casting the value.
See:
- https://github.com/nodejs/node/commit/832ec1cd507ed344badd2ed97d3da92975650a95
- https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4

**Comment by jleyba** [comment]
The code is calling `child_process.kill()`, which takes a string signal:

1. Node 6: https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_kill_signal
2. Node 7: https://nodejs.org/dist/latest-v7.x/docs/api/child_process.html#child_process_child_kill_signal

**Comment by arboreal84** [comment]
Argh... so `process` uses numbers and `child_process` uses strings? That sucks.
