### ISSUE TITLE
It is not clear how to upload multiple files via selenium

### ISSUE THREAD

**Issue by VitoAlbano** [SeleniumHQ/selenium#3096]
## Meta -
OS:  
OSX 10.11.6
Selenium Version:  
selenium (2.53.6)
Browser:  
Firefox 45.4.0

## Expected Behavior -
I'm trying to create an automate test for multiple file upload but actually it keeps on failing on this version of Firefox, so i would like to know which should be the correct way to do this in my firefox version.
I've tried with : 
1) Multiple send keys with different file path
2) Concatenate file path with a comma
3) Concatenate file path  with a space

## Steps to reproduce -
this is my html page
<html>
<head>
    <meta charset="utf-8"/>
    <title>(root)/forms/multiple_file_upload_form.html</title>
</head>
<body>
<script type="text/javascript">

function show_content_of_upload() {
   var file_list = document.getElementById("files").files;
   for (i = 0; i < file_list.length; i++) {
      append_element_to_list(file_list[i].name);
   }
}

function append_element_to_list(text_to_append){
  var ul = document.getElementById("result");
  var li = document.createElement("li");
  li.appendChild(document.createTextNode(text_to_append));
  ul.appendChild(li);
}

</script>
<form enctype="multipart/form-data" method="post">
    <input multiple="multiple" name="upload[files][]" id="files" type="file" />
    <input type="button" name="check_content" id="check_content" value="Check" onclick="show_content_of_upload()"/>
</form>
<ul id="result" />
</body>
</html>

================

this is my piece of code in python

    def choose_multiple_files(self, locator, basePath="",  *files):
        fileList = []
        selenium2Lib = BuiltIn().get_library_instance('Selenium2Library')
        for file in files:
            path_to_image = os.path.join(basePath, file)
            fileList.append(path_to_image)
            if self.browser not in ("googlechrome", "gc", "chrome"):
                selenium2Lib._element_find(locator, True, True).send_keys(path_to_image)
        if self.browser in ("googlechrome", "gc", "chrome"):
            logging.info(fileList)
            selenium2Lib._element_find(locator, True, True).send_keys("\n".join(fileList))

Thanks for the support

**Comment by lukeis** [comment]
It's currently undefined in the spec and is a shown as an issue - bullet point 11 in this section
https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys

related issue discussing this on the spec:
https://github.com/w3c/webdriver/issues/409

**Comment by VitoAlbano** [comment]
Is this scenario already fixed on marionette/geckodriver?

**Comment by twalpole** [comment]
@VitoAlbano   No - as @lukeis pointed out it's not defined in the webdriver spec currently, and firefox doesn't support it.  It also sounds like the current definition that is going to be used for the spec will actually be useless for testing user behaviors where multiple files are selected at once. Hopefully chromedriver keeps it's divergence from the spec when the spec is updated and continues to accept multiple files in one send_keys call otherwise testing multiple simultaneous file selection will become impossible on any browser.

**Comment by heyitsmesuraj** [comment]
Hello lukeis,

I have some confusion why multiple file upload working on local machine not in grid?

**Comment by omnipotentkrishna** [comment]
Hi,
I am using IE 3.14.0 version using Java, still unable to upload multiple files in IE. Whereas I am able to upload multiple files in Chrome. Can anyone please help me how to upload multiple files in IE without Robot or AutoIT. 
Regards,
Vinod

**Comment by Nakilon** [comment]
I guess it was not solved here: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2239

**Comment by diemol** [comment]
The linked W3C WebDriver issue got closed and solved by describing how to do it in the spec. The question is now, is this issue still valid? 
If it is still valid, could you please provide a way to reproduce it or at least provide the code you are using to do that?

**Comment by AutomatedTester** [comment]
Closing the issue as there was no response
