### ISSUE TITLE
Selenium 3.0 chromedriver 2.25 open new tab(Crtl+T) doesn't work

### ISSUE THREAD

**Issue by Chunk-Wang** [SeleniumHQ/selenium#3097]
OS:  WIN7

Selenium Version:  3.0

Browser:  Chrome

Browser Version:  54.0.2840.87 m (64-bit)

Selenium 3.0 chromedriver 2.25 open new tab doesn't work, but the same code could be worked on 2.53 version

Code:  JAVA

String selectLinkOpeninNewTab = Keys.chord(Keys.CONTROL, "t");
driver.findElement(By.tagName("body")).sendKeys(selectLinkOpeninNewTab);
swtichToOtherTabByTitle(driver, "New Tab");
driver.navigate().to(href);

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
