### ISSUE TITLE
Selenium Webdriver would not open some urls 

### ISSUE THREAD

**Issue by sau1983in** [SeleniumHQ/selenium#3103]
## Meta -
OS:  Windows10
Selenium Version:  2.45.0, IDE : IntelliJIdea
Browser:   Firefox 

Browser Version:  33.0

## Expected Behavior -

I am trying to execute a simple test case
        
       driver = new FirefoxDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.get("https://www.linkedin.com");

Firefix Should launch linkedin.com

## Actual Behavior -

Firefox is launched but linkedin.com website doesnt open, I dont even see url being passed to the firefox.

All other websites like: Google.com, CNN.com etc can be launched except linkedin.com

## Steps to reproduce -
Not sure how to reproduce the issue as it affects one website only

**Comment by AutomatedTester** [comment]
does this work in latest firefox and selenium? Firefox 33 is very old!

**Comment by lukeis** [comment]
I can't reproduce the issue using Firefox 45 esr using Selenium project's extension driver nor with using geckodriver.
