### ISSUE TITLE
Timeouts with selenium grid (Linux/Firefox)

### ISSUE THREAD

**Issue by ameyms** [SeleniumHQ/selenium#3104]
## Meta -
OS:  
* Local: OSX
* Hub & Node: Linux

Selenium Version:  
* selenium-java: 2.43.1
* hub, nodes: 2.43.1

## Expected Behavior -
Should not causes 'timeout'.

## Actual Behavior -
After executing test code correctly and printing results interim results to stdout, a timeout occurs.

```
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=33.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=3a85e91a-4175-4915-ae72-7895b1e477a9, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3a85e91a-4175-4915-ae72-7895b1e477a9
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.deleteAllCookies(RemoteWebDriver.java:685)
```
## Steps to reproduce -
``` 
        driver.manage().deleteAllCookies();
        proxy.stop();
```

**Comment by ameyms** [comment]
Duplicate of #2216.

**Comment by ameyms** [comment]
Reopening since #2216 is already closed

**Comment by lukeis** [comment]
you're missing key pieces of information for us to help you with this issue.

It would be helpful to have the full output of the hub and node when this issue occurs. You've clipped the stacktrace message, so we can't tell what the actual exception raise was. You haven't included what configuration options are used starting the hub nor the node. I can't reproduce this with the information given.

Also, you're using a very old version of selenium. Please upgrade and provide all relevant information when this occurs and we can help investigate the issue. When it is provided we can reopen the issue
