### ISSUE TITLE
Firefox SSL certificate 

### ISSUE THREAD

**Issue by Priya-Ram** [SeleniumHQ/selenium#3106]
## Meta -
OS:  Windows 7

Selenium Version:  selenium==3.0.1

Browser:  Firefox 

Browser Version:  47 (64-bit)

## Steps to reproduce - This is an intranet website, so this cant be shared or used by public.

![error](https://cloud.githubusercontent.com/assets/23473395/20299539/6bd55922-ab41-11e6-99f2-245e0a08ba4a.png)

**Comment by mstankovic86** [comment]
probably duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1103196

--
*Miloš Stanković*  |  *Team Lead*
Emisia Consulting, Kragujevac, Serbia

**Comment by NishilKumar** [comment]
I am also facing similar issue , the firefox is not accepting ssl certs using python with selenium - anyone knows any way in which i can disable ssl checks itself in firefox?

**Comment by AutomatedTester** [comment]
duplicate of #2495
