### ISSUE TITLE
IE alert interrupting selenium test case automation

### ISSUE THREAD

**Issue by shashidonthiri9** [SeleniumHQ/selenium#3107]
## Meta -
OS:  
Windows 10 
selenium-dotnet-3.0.0
Selenium Driver Version:   IEDriverServer_x64_2.53.1
Browser:   Internet Explorer 11

 public void Test_CreatNewReport(){
            IWebElement button_Create = null;
            IWebElement datamatrix_button = null;
            try
            {
                button_Create = driver.FindElement(By.XPath("//*[@id='create-new-workspace-icon']"));
                button_Create.Click();
                utils.WaitForPageLoading(driver);
                datamatrix_button = driver.FindElement(By.XPath("//*[@id='add-popular-widgets']/li[10]"));
                datamatrix_button.Click();
                Thread.Sleep(3090);
           //     IAlert alert = driver.SwitchTo().Alert();            
             //   alert.Accept();

            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                Clean_up(); //driver.Quit();
            }

## Expected Behavior -
The browser have to create a new widget followed as by the code given.

## Actual Behavior - The IE11 is throwing an alert :
 Are you sure you want to leave the page?
Message from Webpage : 
You have unsaved changes
Stay on this page
Leave this Page

## Steps to reproduce -
The alert should be comprimiz
![alert](https://cloud.githubusercontent.com/assets/6804126/20299593/9c09e7ac-ab41-11e6-95d9-3f206d8702b5.PNG)
ed to stay in the page and continue to work as per the code without interruption.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. This includes all the html that is needed to reproduce it.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
