### ISSUE TITLE
scroll to element does not work everytime in selenium , i used java executor , actions but nothing worked

### ISSUE THREAD

**Issue by akhouri19** [SeleniumHQ/selenium#3110]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.1
Browser:  Firefox

Browser Version:  
47.0.1

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
