### ISSUE TITLE
Login redirection immediately back to login page with Error

### ISSUE THREAD

**Issue by AmolSG** [SeleniumHQ/selenium#3111]
## Meta -
OS:  Windows 10
Selenium Version:  3.0.1
Browser:  Chrome
Browser Version:  54.0.2840.99 m (64-bit)

## Expected Behavior -
After valid login, redirection to the applications internal Home page should happen

## Actual Behavior -
Intermittently it is throwing back to the login page with error as "Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //*[@id='pt1:pgl3']/tbody/tr/td[2]/span' (tried for 20 second(s) with 500 MILLISECONDS interval)"

## Steps to reproduce -
1. Configuration: Windows 10, Selenium 3.0.1, Chrome 54.0.2840.99 m (64-bit), ChromeDriverwin32
2. Accessed the Application Login page
3. Entered valid login credentials and submitted
4. Redirection to internal home page and within a second its throwing back to the Login page
Note: Same script works fine on IE, FF, Safari. ONLY on Chrome the selenium sync is not consistent. Finding of the element is before the page is even getting loaded.
Have used Thread.sleep, waitforPagetoLoad, waitforelementvisible logic but nothing works

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. We can reopen when that infomation has been added.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
