### ISSUE TITLE
Selenium doesn't open URL

### ISSUE THREAD

**Issue by zakt4n** [SeleniumHQ/selenium#3113]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.0

Browser:  Google Chrome

Browser Version:  56.0.2914.3 beta (64-bit)

I'm trying  to open a URL using Selenium and chromedriver with a C# code and instead it opens a new tab in a existing window and the url textbox have only "data;." written in it and the page stays blank. I tried looking for this kind of problem and couldn't find anyone with a fix for it. I want to be able to open a new window with such URL. 

This is the error i get on CMD:
```
Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 50838
Only local connections are allowed.
[14264:2600:1115/190051:ERROR:cache_util_win.cc(20)] Unable to move the cache: 0
[14264:2600:1115/190051:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\<username>\AppData\Local\Google\Chrome\User Data\ShaderCache\GPUCache to C:\Users\<username>\AppData\Local\Google\Chrome\User Data\ShaderCache\old_GPUCache_001
[14264:2600:1115/190051:ERROR:cache_creator.cc(134)] Unable to create cache
[14264:2600:1115/190051:ERROR:shader_disk_cache.cc(570)] Shader Cache Creation failed: -2
```
## Expected Behavior -
open a new window with the URL i set it to open with.

## Actual Behavior -
open a tab in a existing window and the page looks blank with "data;." on the url textbox.

## Steps to reproduce -
open any URL with chromedriver and C# selenium code.

**Comment by luke-hill** [comment]
As an FYI (Whilst I'm not a contributor here), `data:;` is a temporary loading buffer screen. If you use `Internet_Explorer` as a browser it "should" tell you that this is a loading screen for the Webdriver.

If this is remaining, the first three things I would check (And expect you to post here for Devs are)
- Are other browsers affected?
- What commands you are using to 'set' your URL. These can vary even inside one coding language
- How you initiate the page / initialize your Webdriver Browser object. <- Whilst these methods are usually unique, you might have a slight syntax error for example

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. When you have added the details we can see about reopening the issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
