### ISSUE TITLE
Firefox option was set, but is not a FirefoxOption

### ISSUE THREAD

**Issue by iliakan** [SeleniumHQ/selenium#3115]
OS:  MacOS
Selenium Version:  3.0.1.
Browser:  Firefox.

Suddenly javascript code stopped working:

```js
/js/payments/node_modules/selenium-webdriver/lib/promise.js:2517
        throw error;
        ^

WebDriverError: Firefox option was set, but is not a FirefoxOption: {prefs={browser.download.folderList=2, browser.download.dir=/js/payments/tmp, browser.download.manager.showWhenStarting=false, browser.helperApps.neverAsk.saveToDisk=application/excel,application/octet-stream}}
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'MBP-Ilya-2', ip: '192.168.1.213', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_31'
Driver info: driver.version: FirefoxDriver
    at Object.checkLegacyResponse (/js/payments/node_modules/selenium-webdriver/lib/error.js:505:15)
```

Anything changed? 

How to build the most recent selenium-standalone-server.jar from github? I tried `./go selenium-server-standalone`, but then couldn't find the resulting .jar file to in the directory.

**Comment by gohelkiran** [comment]
Same issue for me after updating selenium-webdriver update.
any update on this?

**Comment by iliakan** [comment]
@gohelkiran what did you update? tried downgrading?

**Comment by gohelkiran** [comment]
I have selenium-webdriver installed via npm, and by mistake I removed it. I just installed it again and it stopped working with nodejs v4.6. Initially the error is different which is removed after upgrading nodejs to v6.0

I have posted the same on stackoverflow
http://stackoverflow.com/questions/40492582/nodejs-server-error-with-selenium-webdriver

I dont't know how to downgrade selenium-webdriver using npm
If you have any idea let me know and I will try it.

**Comment by iliakan** [comment]
answered on SO

**Comment by iliakan** [comment]
http://stackoverflow.com/a/40650113/815139

**Comment by gohelkiran** [comment]
So the problem is with latest selenium-webdriver update

**Comment by iliakan** [comment]
yeah
