### ISSUE TITLE
selenium-java 3.0.x has cyclical dependency

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/selenium#3118]
selenium-java 3.0.1 depends on phantomjsdriver 1.3.0 which in turn depends on selenium-java 2.53.0

This is causing problems when resolving.

Not sure whether selenium or phantomjs is in error. To fix selenium-java, I'd suggest an exclusion in the maven pom

```xml
<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>1.3.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

Though I'm not sure how to do that with selenium's build system.

**Comment by mach6** [comment]
This should be fixed in the next release. There is already a handful of commits on the `master` branch which aim to address it. 

Leaving this open until the release happens.

**Comment by tholu** [comment]
When will 3.0.2 be released on maven? According to the [CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG), 3.0.2 was already released ?

**Comment by lukeis** [comment]
@tholu we were merely preparing the changelog in anticipation of releasing 3.0.2... to which I never got around to, but should be "soon" :)

**Comment by paul-hammant** [comment]
Refer #3705 and #3771

**Comment by barancev** [comment]
selenium-java maven artifact will not have dependency on phantomjsdriver since version 3.6
