### ISSUE TITLE
Trojan in IE Driver Server?

### ISSUE THREAD

**Issue by jeconti** [SeleniumHQ/selenium#3119]
OS:  Win7

Selenium Version:  2.53.1

Browser:  Internet Explorer

Browser Version:  11

Prior to download, I scanned the 64-bit file (IEDriverServer_x64_2.53.1.zip) online using virustotal.com and found that the file contains **Win32.Trojan.WisdomEyes.16070401.9500.9543**

**Comment by jimevans** [comment]
This is a false positive from the antivirus scanner. They need to update their detection algorithm.
