### ISSUE TITLE
selenium in centos is missing certain dependencies. 

### ISSUE THREAD

**Issue by rohit-glassbeam** [SeleniumHQ/selenium#3122]
OS:  
centos 6.6
Selenium Version:  
webdriver-manager 2.53.1
Browser:  
chrome

As chrome doesn't support centos so I had installed it from [here](https://chrome.richardlloyd.org.uk/). My setup is like this. I have a job on remote server jenkins which uses Xvfb & Nodejs plugin(5.12). Selenium jar is ran from node_modules(I've tried running webdriver via cli). On ubuntu everything is perfect but on centos it tries to launch selenium instance but it fails. So after doing some research I found that centos 6.6 was missing new version of glibcxx3.1.14/15 and cxxabi libraries. And most of the threads online recommended to not update them as it might break the OS. If anyone faced this bug, please help.

**Comment by barancev** [comment]
What part of Selenium depends on this missing library?
