### ISSUE TITLE
Creating FirefoxDriver fails if log_path is not specified

### ISSUE THREAD

**Issue by JuryFrid** [SeleniumHQ/selenium#3128]
From https://github.com/mozilla/geckodriver/issues/349.

Found on selenium v.3.0.1 for python.

Code which fails:
`driver = webdriver.Firefox(log_path = "")`
I've just wanted to run FF driver and do not have some trash logs I didn't expected.

Crash in Selenium occurs in
`selenium/webdriver/firefox/service.py`
on line 48.
Snippet of code (doc ommited):
`class Service(service.Service):

    def __init__(self, executable_path, port=0, service_args=None,
            log_path="geckodriver.log", env=None):

        if log_path:
            log_file = open(log_path, "a+")

        service.Service.__init__(
            self, executable_path, port=port, log_file=log_file, env=env)
        self.service_args = service_args or []`

In my case variable log_path is empty string and variable log_file doesn't exist. Using this variable emits crash.

**Workaround:**
use `webdriver.Firefox(log_path = os.devnull)`

**Comment by davehunt** [comment]
(copied from the original issue):

Thanks for the issue, it indeed looks like we need to avoid passing a value for `log_file` if `log_path` is not specified. Would you be interested in writing a test and patch for this?

**Comment by JuryFrid** [comment]
Yes, but, unfortunately, I don't have experience in this. I'll be happy to help.

**Comment by davehunt** [comment]
@JuryFrid try [forking the repository](https://help.github.com/articles/fork-a-repo/) and [cloning it](https://help.github.com/articles/cloning-a-repository/) so you have a local copy. Then try running `./go py_prep_for_install_release`. Once you've done that, you can try [running the existing tests](https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings#tests). Let me know when you get to that point (or ask me questions here if you get stuck) and I'll help you to write a failing test for the current behaviour.
