### ISSUE TITLE
import  org.openqa.selenium.server.browserlaunchers.Sleeper; gives a cannot be resolved error

### ISSUE THREAD

**Issue by jagdish-sp** [SeleniumHQ/selenium#3130]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.0.0
Browser:  
Firefox 42.0

## Steps to reproduce -
1: Add selenium 3.0.0 jars
2:Add the statement import  org.openqa.selenium.server.browserlaunchers.Sleeper; to your test script

**Comment by lukeis** [comment]
This bit of code was removed from Selenium. Also it was just a wrapper for Thread.sleep. You are welcome to add it to your code base and use as seen fit. But we will no longer be packaging it in selenium as it was mainly for the previous selenium server which was re-written for 3.0.

https://github.com/SeleniumHQ/selenium/blob/leg-rc/java/server/src/org/openqa/selenium/server/browserlaunchers/Sleeper.java

**Comment by igorrodygin** [comment]
@lukeis , sorry, what the last version of selenium server where it presented?

> Also it was just a wrapper for Thread.sleep
