### ISSUE TITLE
Selenium Server Standalone ignore timeout setting

### ISSUE THREAD

**Issue by VincentRo** [SeleniumHQ/selenium#3131]
## Meta -
OS:  Red Hat
Selenium Version:  
 2.53.1, Selenium server standalone
Browser:  
Firefox 45
## Expected Behavior -
Our web application is not really fast and we need to define a higher timeout.
I try different combination to launch selenium-server-standalone and change the default timeout but nothing is working.

Here is my different try :

java -Dwebdriver.server.session.timeout=3600 -Dwebdriver.server.browser.timeout=600 -jar /home/jenkins/selenium/selenium-server-standalone-2.53.1.jar -userExtensions user-extensions.js -htmlSuite *firefox http://xxx..com "Testcmd/TS.html" "firefox-results.html"

java  -jar /home/jenkins/selenium/selenium-server-standalone-2.53.1.jar timeout 600 -browserTimeout 600 -userExtensions user-extensions.js -htmlSuite *firefox http://xxx..com "Testcmd/TS.html" "firefox-results.html"

If we haven't this problem, our test will work perfectly, it's a great tool but I begin to despair.
So please, if you can help me ?

**Comment by lukeis** [comment]
selenium has a multitude of timeouts that can be set. It's hard to tell exactly which timeout you need adjusted.

I'd recommend asking on the selenium-users mailing list:
https://groups.google.com/forum/#!forum/selenium-users

Try to describe what's going wrong and try provide a way for someone else to replicate the issue in order for others to give better suggestions on what you could be doing differently to solve the problem.

**Comment by VincentRo** [comment]
It's simple, the argument -timeout or -browserTimeout doesn't work. 
Doesn't matter what you launch.
