### ISSUE TITLE
remoteWebDriver improperly escaping escape characters in Firefox profile preference

### ISSUE THREAD

**Issue by breaks-software** [SeleniumHQ/selenium#3135]
## Meta -
OS:  Windows 7, Windows 10

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  42.0, 47 (32-bit)

## Expected Behavior -
set the firefox preference for browser.uiCustomization.state in my code should match the preference ending up in the "user.js" file for the firefox profile.

the value should look like this:
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"downloads-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"home-button\",\"loop-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");

Note that the local firefox webdriver works fine, it's just remoteWebDriver that's doing this.

## Actual Behavior -
the escape characters used in my Java string are further escaped in the preference in user.js, so that the value is ignored by firefox. 

it comes out as:
user_pref("browser.uiCustomization.state", "{\"placements\":{\\\"PanelUI-contents\\\":[\\\"edit-controls\\\",\\\"zoom-controls\\\",\\\"new-window-button\\\",\\\"privatebrowsing-button\\\",\\\"save-page-button\\\",\\\"print-button\\\",\\\"history-panelmenu\\\",\\\"fullscreen-button\\\",\\\"find-button\\\",\\\"preferences-button\\\",\\\"add-ons-button\\\",\\\"developer-button\\\",\\\"downloads-button\\\"],\\\"addon-bar\\\":[\\\"addonbar-closebutton\\\",\\\"status-bar\\\"],\\\"PersonalToolbar\\\":[\\\"personal-bookmarks\\\"],\\\"nav-bar\\\":[\\\"urlbar-container\\\",\\\"search-container\\\",\\\"bookmarks-menu-button\\\",\\\"pocket-button\\\",\\\"home-button\\\",\\\"loop-button\\\"],\\\"TabsToolbar\":[\\\"tabbrowser-tabs\\\",\\\"new-tab-button\\\",\\\"alltabs-button\\\"],\\\"toolbar-menubar\\\":[\\\"menubar-items\\\"]},\\\"seen\\\":[],\\\"dirtyAreaCache\\\":[\\\"PersonalToolbar\\\",\\\"nav-bar\\\",\\\"TabsToolbar\\\",\\\"toolbar-menubar\\\",\\\"PanelUI-contents\\\",\\\"addon-bar\\\"],\\\"currentVersion\\\":4,\\\"newElementCount\\\":0}");

## Steps to reproduce -

FirefoxProfile firefoxProfile = new FirefoxProfile();

firefoxProfile.setPreference("browser.download.animateNotifications", false);
// move the downloads-button from the nav-bar to PanelUI-contents in order to
// avoid the download progress pop up from blocking the ZoomInfo nav bar buttons
firefoxProfile.setPreference("browser.uiCustomization.state",
		"{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\","
		+ "\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\","
		+ "\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"downloads-button\"],"
		+ "\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],"
		+ "\"PersonalToolbar\":[\"personal-bookmarks\"],"
		+ "\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"home-button\",\"loop-button\",\"pocket-button\"]},"
		+ "\"seen\":[],"
		+ "\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\"],"
		+ "\"currentVersion\":4,\"newElementCount\":0}");

desiredCapabilities.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
driver = new RemoteWebDriver(new URL("http://selenium-grid:4444/wd/hub"), desiredCapabilities);

**Comment by breaks-software** [comment]
FWIW, I tried to come up with a way to pass that browser.uiCustomization.state value such that it would not have the escaped quote marks.  My approach was to save the String value in a txt file, then read that using FileReader to drop it into a String that's then passed as the value to the firefoxProfile.setPreference() call.  Interestingly, the result was that the browser.uiCustomization.state value was not set at all in the resulting user.js or prefs.js in the Firefox profile of the Grid node.

**Comment by diemol** [comment]
Apologies for the poor handling of this issue from our side, if this problem is still present with thee most recent version of Selenium and Firefox, could you please open a new issue and provide all the information required in the template?

**Comment by breaks-software** [comment]
OMG, this is some jobs ago.  I have no way of attempting to reproduce.
