### ISSUE TITLE
IDE: Drag and drop of test cases (and commands) not working anymore

### ISSUE THREAD

**Issue by ThomasLandauer** [SeleniumHQ/selenium#3139]
## Meta -
OS:  
Windows 10
Selenium Version:  
IDE 2.9.1
Browser:  
Firefox
Browser Version:  
50.0 (64 bit)

## Expected Behavior -
In the UI, I cannot drag and drop the test cases any more.
In the right pane, I also cannot drag the commands, but in this case Cut and Copy works to change the order. However, in the left pane (where the test cases are) Cut/Copy doesn't work - so at the moment I see no way to change their order.

**Comment by dannycarlsson** [comment]
When will they fix this?
Is there some other Selenium IDE that i can download????

**Comment by deo33169** [comment]
I encountered this issue on multiple machines and operating systems after a FireFox update 3 days ago. My machines worked fine using FireFox version 49.0.2 and below. The machines were recently updated to version 50.0 and I can no longer drag and drop "Test Cases" or "Commands" within Selenium IDE. After reverting to the previous version of FireFox that worked (49.0.2), I can drag and drop the "Test Cases" and "Commands" again.

**Comment by dannycarlsson** [comment]
Thank you so much. I really hope they fix this Issue very soon. Sorry that I bothered you with this, but I Googled and founded your post of this Issue. Thanks for helping me. i am from South Africa. Do you maybe know where I can download Mozilla Firefox 49.02...I am Google-ing

**Comment by dannycarlsson** [comment]
Never mind...I got it. 👍 YAY And I went into the settings of my browser and set off the Auto Updates. 💯

**Comment by harrallo** [comment]
same issue, please, fix this.

**Comment by DeeMusil** [comment]
Same problem on Linux Ubuntu 16.04,  FF version 50.0, IDE 2.9.1

**Comment by threeedie** [comment]
I am also having this issue. It started on 11/23/2016. I am using iOS El Captian 10.11.5 (15F34) and Selenium 2.9.1.1. This issue is very much hampering my work. Your investigation and hopefully a fix would be much appreciated. I consider this a High priority issue. Oh, I have also re-installed Selenium but it did not fix the issue.

**Comment by dsampson0** [comment]
I noticed this issue last week and am thankful for the workaround.  I have reverted to the previous version of Firefox and turned off automatic updates to allow organization of the test suites but am also eager to see this fixed.

**Comment by threeedie** [comment]
I have also reverted but we can't stay on the older version of Firefox forever so please fix soon. Thanks

**Comment by ThomasLandauer** [comment]
Workaround:
Locate the file (on your hard drive) in which your Test Suite is saved (should be a regular HTML file, but in my case it doesn't have an `.html` extension). Open it with a text editor an rearrange the `<tr>`'s containing the Test Cases.
Cumbersome, but better than nothing ;-)

**Comment by mnsymons** [comment]
Noticed the same issue recently. Thx, will try to use older FF version.

**Comment by afukuyama** [comment]
Using the workaround of editing the suite file method for now and it works.. but quite painful.
Please fix soon. Thank you.

**Comment by mnsymons** [comment]
As soon as anyone sees a later version update fixing this then please notify on here. Much appreciated ☺

**Comment by philGehlich** [comment]
Is this fix available in a download? If not, is there an estimate for when it will be?

**Comment by FDIM** [comment]
I am willing to contribute, @lukeis any pointers on how to set up extension development? I've tried to run local version of the extension from master branch in an unbranded version of FF v50 to no avail (popup/overlay opens, but nothing works) - signed xpi works just fine in v51.

**Comment by FDIM** [comment]
That seems to be true, I've got no response for my PR in a month (some edge case bug is not a biggie, but usability problem is kind of important...). se-builder that you referenced doesn't look like actively maintained either, and after making my PR I understand why (XUL is being deprecated and will be removed).

I guess it's time to build a chrome extension that can record actions and skip FF all together.

**Comment by FDIM** [comment]
as mentioned in the previous comment - I've made and extension for chrome. It is a subset of selenium ide features, but covers what I need. 

https://chrome.google.com/webstore/detail/e2e-test-builder/pamfkepooglpdkepmlopejpmcpggaobo

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
