### ISSUE TITLE
Selenium 3 with Firefox 49 Portable Edition doesn't start

### ISSUE THREAD

**Issue by Jonathan478** [SeleniumHQ/selenium#3141]
## Meta -
OS:  Windows 7
Selenium Version:  3.0.1
Browser:  Firefox 49.0.2 Portable Edition

## Expected Behavior -
Run Firefox Portable Edition and display the text message "test is executed" in my console.
## Actual Behavior -
Firefox is launched but nothing else after that. Just the following logs :
`1478965841203   geckodriver INFO    Listening on 127.0.0.1:45941
nov. 12, 2016 4:50:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1478965841598   mozprofile::profile INFO    Using profile path d:\Profiles\<username>\AppData\Local\Temp\rust_mozprofile.TisH4gXwlj3K
1478967041359   geckodriver::marionette INFO    Starting browser D:\firefox-portable\FirefoxPortablex64-48.0.2\FirefoxPortable.exe
1478967041388   geckodriver::marionette INFO    Connecting to Marionette on localhost:52702`
## Steps to reproduce -
Run the JUnit test.

`
public class SeleniumWithFirefoxPortableEditionTest {
  WebDriver webDriver = new FirefoxDriver();
  static {
    // 1) Work with native Firefox
    System.setProperty("webdriver.gecko.driver", ClassLoader.getSystemResource("webdriver/geckodriver_0.11.1.exe").getFile());

    // 2) Don't work when I add these 2 properties
    //        System.setProperty("webdriver.firefox.marionette", "true");
    //        System.setProperty("webdriver.firefox.bin", "D:\\firefox-portable\\FirefoxPortablex64-49.0.2\\FirefoxPortable.exe");`
  ` }
  @Test
  public void test() {
    System.out.println("test is executed");
   }
 }`

I precise I also added the  geckodriver executable path in system environment variable (but it changed nothing) like it mentionned here  : https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
