### ISSUE TITLE
[Question] How to kill many geckodriver.exe processes?

### ISSUE THREAD

**Issue by donhuvy** [SeleniumHQ/selenium#3142]
I am using Windows 10 pro x64, Firefox 50.x, Java 8, Selenium 3.0.1.

```
public RemoteWebDriver remoteWebDriver;
//...
System.setProperty("webdriver.gecko.driver", browserWebDriverFilePath);
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability("marionette", true);
remoteWebDriver = new FirefoxDriver(capabilities);
remoteWebDriver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
remoteWebDriver.manage().window().maximize();
//...
remoteWebDriver.quit();
```

![gecko](https://cloud.githubusercontent.com/assets/1328316/20461847/7b013cc2-af3d-11e6-8fae-993b4bb80d4b.PNG)

How to kill process of **geckodriver.exe** processes?

**Comment by donhuvy** [comment]
FYI: http://stackoverflow.com/questions/40702478/how-to-kill-many-geckodriver-exe-processes
But I think it is a temporary solution.

**Comment by ddavison** [comment]
A while ago I had issues with Eclipse and chromedriver.. it's hardly a solution, but it's certainly a workaround.  I'm very curious as to why this happens, but i'm pretty sure it has something to do with eclipse debugging

https://stackoverflow.com/questions/21320837/release-selenium-chromedriver-exe-from-memory/21320949#21320949

**Comment by donhuvy** [comment]
This solution is helpful: http://stackoverflow.com/a/40704072/3728901

**Comment by ddavison** [comment]
my answer literally says the same thing @donhuvy

**Comment by barancev** [comment]
Selenium kills geckodriver on quit. If a user forgot to call quit, or something prevented normal shutdown, Selenium does not attempt to kill orphaned geckodriver processes. It's out of its responsibility.

**Comment by hheexx** [comment]
@barancev  No it does not. It stops the firefox but geckodriver remains open.

**Comment by jmccoy11** [comment]
My apologies first as I'm a junior developer. I've noticed this as well and it certainly is that I'm hitting stop or closing the browser before it's finished. Is there a way, similar to a try/catch/finally block, that I can ensure the gecko driver process will be killed even after an abnormal shutdown?
