### ISSUE TITLE
Selenium IDE Drag and Drop not working at all in the Test cases and Test Suites

### ISSUE THREAD

**Issue by dannycarlsson** [SeleniumHQ/selenium#3146]
Selenium IDE Drag and Drop not working at all in the Test cases and Test Suites

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
