### ISSUE TITLE
SELENIUM IDE DRAG & DROP

### ISSUE THREAD

**Issue by dannycarlsson** [SeleniumHQ/selenium#3147]
## Meta -
OS:  

Selenium Version:  

Browser:  
OS:
Windows 10
Selenium Version:
IDE 2.9.1
Browser:
Firefox
Browser Version:
50.0 (64 bit)
Expected Behavior -

In the UI, I cannot drag and drop the test cases any more.
In the right pane, I also cannot drag the commands, but in this case Cut and Copy works to change the order. However, in the left pane (where the test cases are) Cut/Copy doesn't work - so at the moment I see no way to change their order.

-->

Browser Version:

**Comment by luke-hill** [comment]
As someone who at his previous job used IDE. It is worth once you have someone vaguely strong training you, that you migrate over to the full WebDriver.

Dependent on which language/s you know, this will not only improve test coverage but it will stop you being held back by the IDE interface.

On a side-note, I believe no-one is currently maintaining Selenium-IDE

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by dannycarlsson** [comment]
Is this Issue Fixed??

**Comment by dannycarlsson** [comment]
Can I drop and drag test cases in a Test Suite and in a Test Case itself on Selenium IDE on latest Mozilla Firefox.

**Comment by dannycarlsson** [comment]
When are you fixing this ISSUE?
