### ISSUE TITLE
I can't get selenium-webdriver (Javascript) with chromedriver working on Mac OSX

### ISSUE THREAD

**Issue by posti85** [SeleniumHQ/selenium#3148]
## Meta -
OS:  Mac OSX

Selenium Version:  3.0.1 (Javascript API)

Browser:  Google Chrome

Browser Version:  54.0.2840

## Expected Behavior -

Open Google's web page and write something in the input field.

## Actual Behavior -

Google's web page opens, but nothing is written (the get call doesn't finish).

## Steps to reproduce -

Copy & paste from my stackoverflow question: http://stackoverflow.com/questions/40664398

I'm trying to do some functional testing using selenium-webdriver in Google Chrome navigator on Mac OSX, but I have problems while trying to interact with the navigator.

I've simplified the problem into a similar one: I need to open the Google main page and write something in its input, so I execute this node script:

```
require('chromedriver');

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.name('q')).sendKeys('webdriver');
```

The npm dependencies are:

```
npm install selenium-webdriver chromedriver
```

The results of the execution are: the Google Chrome browser opens (so the chromedriver seems to work), but the input field isn't written, because the get call never finishes executing. So the browser can load a given web page but after that I can't interact with it.

Of course, I've also tried to download and install manually the chromedriver, locating the binary file in `/usr/local/bin` and `chmod +x` it, but the result is the same.

However, if I try the same in Safari (removing the first require line and using `'safari'` for browser instead of `'chrome'`) it works! But I need to test it in Google Chrome!

Also, I have tryied the same example using Java and Google Chrome, and it works! It's a problem related with the selenium webdriver Javascript implementation? Or its integration with chromedriver...?

**Comment by jleyba** [comment]
What version of chromedriver are you using? (The binary, not npm package)

**Comment by japostigo-atsistemas** [comment]
The last one at the moment: 2.25.

**Comment by posti85** [comment]
The last one at the moment: 2.25.

**Comment by im-fortech** [comment]
WebDriverJs uses promises in order to make dealing with async code.
Take a look here for a more in-depth clarification / example: http://www.codechewing.com/library/beginners-guide-to-selenium-webdriverjs/

    driver.get('http://www.google.com/ncr');
     
    driver.findElement({name: 'q'}).then(function(input) {
      input.sendKeys('webdriver');
      input.sendKeys(WebDriver.Key.ENTER);
    });

**Comment by jleyba** [comment]
I can't reproduce this. I ran our entire test suite against chrome on OSX with no problems (node 6.9 and 7.0).

This might be a problem with the chromedriver itself, but you'll need to file a bug against that project:

https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by chrisvfritz** [comment]
@posti85 If you're using Yarn, this might also be a problem with the install script not being run. You may want to try running it manually:

```
node node_modules/chromedriver/install.js
```
