### ISSUE TITLE
Table in the Building WebDriver wiki page is broken

### ISSUE THREAD

**Issue by robinwhittleton** [SeleniumHQ/selenium#3157]
## Expected Behavior -
Useful parameters table on https://github.com/SeleniumHQ/selenium/wiki/Building-WebDriver#useful-targets displays as a table.

## Actual Behavior -
Something’s wrong with the markdown.

## Steps to reproduce -
1. Visit https://github.com/SeleniumHQ/selenium/wiki/Building-WebDriver#useful-targets
2. Look below ‘Useful parameters’

**Comment by davehunt** [comment]
Thanks for the report! Fixed in https://github.com/SeleniumHQ/selenium/wiki/Building-WebDriver/8af9faf6d6ad83956de6dcaf2ac00cc41207acbd
