### ISSUE TITLE
ran used selenium Grid that was terminated due to FORWARDING_TO_NODE_FAILED with 2.53.1

### ISSUE THREAD

**Issue by Rajktha** [SeleniumHQ/selenium#3163]
## Meta -
OS:  
Windows 7 version 6.1
Selenium Version:  
2.53.1 - WebDriver
Browser:  
Chrome-54.0.2840.99 Version

Few sessions alone throwing error with FORWARDING_TO_NODE_FAILED error and also I can see my screenshot as blank page. It is occurring in between the steps execution even browser launched and started to execute. 

## Steps to reproduce -

If you can't provide a link to the page, consider creating a reproducible page on https://jsfiddle.net/
-->
![image](https://cloud.githubusercontent.com/assets/17195094/20615077/011b6fa0-b2fc-11e6-8493-865df85bdccf.png)

**Comment by barancev** [comment]
Is this issue still actual in Selenium Grid 3.8? If the answer is "yes" please provide node and hub logs for investigation.

**Comment by barancev** [comment]
Closing the issue as related to outdated version.
