### ISSUE TITLE
Unable to take screenshot of entire page by selenium 3.0.1

### ISSUE THREAD

**Issue by iamcodylee** [SeleniumHQ/selenium#3165]
## Meta -
OS:  Window 8
Selenium Version: 3.0.1
Geckodriver:   0.11.1
Browser:  Firefox 49.0.2

## Expected Behavior -
Capture the entire page

## Actual Behavior -
Capture the current window

## Steps to reproduce -
I upgraded my selenium from 2.42.2 to 3.0.1
find out that 
`File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);`
can only capture the current window
but before this version, I can capture the entire page.

**Comment by jimevans** [comment]
Geckodriver, like chromedriver, and like the W3C WebDriver Specification specifies, does not support taking "full-page" screenshots. If you feel strongly about this issue, you should file an issue against the W3C WebDriver Specification with the W3C Browser Testing and Tools working group.
