### ISSUE TITLE
 org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:38188 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700' System info: host:local', ip: '', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_65' Driver info: driver.version: ChromeDriver

### ISSUE THREAD

**Issue by abhisek9090** [SeleniumHQ/selenium#3168]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by gopij** [comment]
Make sure selenium server is up and running if your are trying to connect through remote driver, If you still find the same issue. Please specify version number, browser you used, and URL trying to connect if possible your code to reproduce please.

**Comment by abhisek9090** [comment]
i sure my selenium server is runnin,
eclipse version number-Mars.2 Release (4.5.2)
operating sytem-os x EI captain
browser you used- chrome (Version 54.0.2840.98 (64-bit))
URL-http://demos.telerik.com/kendo-ui/datetimepicker/index








Regards,
Abhisek Mohapatra
Skype: mohapatra.abhisek9090
Phone: 8763019531

**Comment by abhisek9090** [comment]
eclipse version number-Mars.2 Release (4.5.2) operating sytem-os x EI captain browser you used- chrome (Version 54.0.2840.98 (64-bit)) URL-http://demos.telerik.com/kendo-ui/datetimepicker/index

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by abhisek9090** [comment]
I want to Automate the date picker.Here is my codes  and console below..

  @org.testng.annotations.Test(priority = 1)
        public void datepicker() throws InterruptedException
        {

            //Date and Time to be set in text box

            String dateTime ="12/07/2014 2:00 PM";

            //WebDriver  chdriver = new SafariDriver();

           // WebDriver driver = new FirefoxDriver();
            File file = new File("/Applications/Google
Chrome.app/Contents/MacOS/Google Chrome");
             System.setProperty("webdriver.chrome.driver",
file.getAbsolutePath() );
             WebDriver chdriver = new ChromeDriver();




            chdriver.get("
http://demos.telerik.com/kendo-ui/datetimepicker/index");



            chdriver.manage().timeouts().implicitlyWait(10,
TimeUnit.SECONDS);



            //button to open calendar

            WebElement selectDate =
chdriver.findElement(By.xpath("//span[@aria-controls='datetimepicker_dateview']"));



        selectDate.click();

        //button to move next in calendar

        WebElement nextLink =
chdriver.findElement(By.xpath("//div[@id='datetimepicker_dateview']//div[@class='k-header']//a[contains(@class,'k-nav-next')]"));

        //button to click in center of calendar header

        WebElement midLink =
chdriver.findElement(By.xpath("//div[@id='datetimepicker_dateview']//div[@class='k-header']//a[contains(@class,'k-nav-fast')]"));

        //button to move previous month in calendar

        WebElement previousLink =
chdriver.findElement(By.xpath("//div[@id='datetimepicker_dateview']//div[@class='k-header']//a[contains(@class,'k-nav-prev')]"));


            //Split the date time to get only the date part

            String date_dd_MM_yyyy[] = (dateTime.split(" ")[0]).split("/");

            //get the year difference between current year and year to set
in calendar

            int yearDiff = Integer.parseInt(date_dd_MM_yyyy[2])-
Calendar.getInstance().get(Calendar.YEAR);

            midLink.click();

            if(yearDiff!=0){

                //if you have to move next year

                if(yearDiff>0){

                    for(int i=0;i< yearDiff;i++){

                        System.out.println("Year Diff->"+i);

                        nextLink.click();

                    }

                }

                //if you have to move previous year

                else if(yearDiff<0){

                    for(int i=0;i< (yearDiff*(-1));i++){

                        System.out.println("Year Diff->"+i);

                        previousLink.click();

                    }

                }

            }



            Thread.sleep(1000);

            //Get all months from calendar to select correct one

            List<WebElement> list_AllMonthToBook =
chdriver.findElements(By.xpath("//div[@id='datetimepicker_dateview']//table//tbody//td[not(contains(@class,'k-other-month'))]"));




list_AllMonthToBook.get(Integer.parseInt(date_dd_MM_yyyy[1])-1).click();



            Thread.sleep(1000);

            //get all dates from calendar to select correct one

            List<WebElement> list_AllDateToBook =
chdriver.findElements(By.xpath("//div[@id='datetimepicker_dateview']//table//tbody//td[not(contains(@class,'k-other-month'))]"));




list_AllDateToBook.get(Integer.parseInt(date_dd_MM_yyyy[0])-1).click();





            ///FOR TIME

            WebElement selectTime =
chdriver.findElement(By.xpath("//span[@aria-controls='datetimepicker_timeview']"));

            //click time picker button

            selectTime.click();

            //get list of times

            List<WebElement> allTime =
chdriver.findElements(By.xpath("//div[@data-role='popup'][contains(@style,'display:
block')]//ul//li[@role='option']"));



            dateTime = dateTime.split(" ")[1]+" "+dateTime.split(" ")[2];

         //select correct time

            for (WebElement webElement : allTime) {

                if(webElement.getText().equalsIgnoreCase(dateTime))

                {

                    webElement.click();

                }

            }

        }

    }


----------------------------------------------------------------------------------------------------------------------------------------------------------------------
[TestNG] Running:

/private/var/folders/kq/4cyw73y16wq4rddqk74xlwf40000gn/T/testng-eclipse--879790956/testng-customsuite.xml

FAILED: datepicker
org.openqa.selenium.WebDriverException: Timed out waiting for driver server
to start.
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18
09:49:13 -0700'
System info: host: 'Sushrees-MacBook-Pro.local', ip: '192.168.30.192',
os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6',
java.version: '1.8.0_65'
Driver info: driver.version: ChromeDriver
    at
org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:178)
    at
org.openqa.selenium.remote.service.DriverService.start(DriverService.java:166)
    at
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
    at
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
    at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
    at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
    at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:174)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:120)
    at
com.org.advanceselenium.com.mobiona.selenium.Test.datepicker(Test.java:623)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
    at org.testng.TestNG.run(TestNG.java:1031)
    at
org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out
waiting for [http://localhost:22896/status] to be available after 20005 ms
    at
org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:107)
    at
org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:175)
    ... 34 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException:
java.util.concurrent.TimeoutException
    at
com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
    at
org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:80)
    ... 35 more
Caused by: java.util.concurrent.TimeoutException
    at java.util.concurrent.FutureTask.get(FutureTask.java:205)
    at
com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
    ... 36 more













Regards,
Abhisek Mohapatra
Skype: mohapatra.abhisek9090
Phone: 8763019531
