### ISSUE TITLE
Confusing chrome driver download page

### ISSUE THREAD

**Issue by JetStream96** [SeleniumHQ/selenium#3169]
The download page [linked](http://chromedriver.storage.googleapis.com/index.html) on npm page is pretty confusing, at least for me. It took me half an hour to realize why it throws strange errors. It may make people to think 2.9 is the latest version, but in fact it's outdated and the latest one is 2.25. Maybe link to the [chrome driver site](https://sites.google.com/a/chromium.org/chromedriver/) where it clearly states the latest version?

Thanks

**Comment by cgoldberg** [comment]
which page are you referring to? (where are you seeing that link?)

 All docs I can find already link to the page you suggest and also explicitly state the latest version number.

**Comment by JetStream96** [comment]
The link is found on the [npm page](https://www.npmjs.com/package/selenium-webdriver#installation), the links text is "chromedriver(.exe)".

Yeah there is a "LATEST_RELEASE" file in that directory, but who would expect v2.25 is newer than v2.9.

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
