### ISSUE TITLE
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.firefox.bin=

### ISSUE THREAD

**Issue by nick2012** [SeleniumHQ/selenium#3170]
## Meta -
OS:  
Windows 7 x64
Selenium Version:  
selenium-server-standalone-3.0.1.jar
Browser:  
FirefoxPortable

Browser Version:  
45

## Expected Behavior -
everything to run ok
## Actual Behavior -

java -jar "C:/selenium/selenium-server-standalone-3.0.1.jar" -Dwebdriver.firefox.bin="C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe"

Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.firefox.bin=C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:219)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:147)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:73)
## Steps to reproduce -
java -jar "C:/selenium/selenium-server-standalone-3.0.1.jar" -Dwebdriver.firefox.bin="C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe"

**Comment by nick2012** [comment]
I've just found out that I had to run it like this instead:

` java -Dwebdriver.firefox.bin="C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe" -jar "C:/selenium/selenium-server-standalone-3.0.1.jar"`

**Comment by nick2012** [comment]
But now I receive this when running a perl script:

`Could not create new session: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases at (eval 31) line 352.`

**Comment by nick2012** [comment]
Downloaded the geckodriver, and used this command:

`java -Dwebdriver.gecko.driver="C:\selenium\geckodriver.exe" -Dwebdriver.firefox.bin="C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe" -jar "C:/selenium/selenium-server-standalone-3.0.1.jar" `


Tried this perl script:

```
use strict;
use warnings;
use Selenium::Remote::Driver;

my $driver = Selenium::Remote::Driver->new;
$driver->get('http://www.google.com');
print $driver->get_title . "\n"; # "Google"

my $query = $driver->find_element('q', 'name');
$query->send_keys('CPAN Selenium Remote Driver');

my $send_search = $driver->find_element('btnG', 'name');
$send_search->click;

# make the find_element blocking for a second to allow the title to change
$driver->set_implicit_wait_timeout(2000);
my $results = $driver->find_element('search', 'id');

print $driver->get_title . "\n"; # CPAN Selenium Remote Driver - Google Search
$driver->quit;
```

Firefox starts but it opens only this page:
`file:///C:/Users/Evo/AppData/Local/Temp/rust_mozprofile....../`

Selenium event log:

`> java -Dwebdriver.gecko.driver="C:\selenium\geckodriver.exe" -Dwebdriver.firefox.bin="C:/_portableapps/FirefoxPortable_selenium00/FirefoxPortable.exe" -jar "C:/selenium/selenium-server-standalone-3.0.1.jar"
13:15:08.807 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
13:15:08.808 INFO - Launching a standalone Selenium Server
2016-11-27 13:15:08.831:INFO::main: Logging initialized @225ms
13:15:08.879 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:15:08.879 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
13:15:08.880 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:15:08.880 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:15:08.886 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
2016-11-27 13:15:08.933:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2016-11-27 13:15:08.950:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@1fcfece{/,null,AVAILABLE}
2016-11-27 13:15:09.197:INFO:osjs.ServerConnector:main: Started ServerConnector@3884b2{HTTP/1.1}{0.0.0.0:4444}
2016-11-27 13:15:09.198:INFO:osjs.Server:main: Started @593ms
13:15:09.198 INFO - Selenium Server is up and running
13:15:15.386 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
13:15:15.446 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]])
13:15:15.454 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, browserName=firefox, javascriptEnabled=true, version=, platform=ANY}]
1480245315842   geckodriver     INFO    Listening on 127.0.0.1:8930
13:15:16.223 INFO - Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1480245316262   mozprofile::profile     INFO    Using profile path C:\Users\Evo\AppData\Local\Temp\rust_mozprofile.......
1480245316282   geckodriver::marionette INFO    Starting browser C:\_portableapps\FirefoxPortable_selenium00\FirefoxPortable.exe
1480245316289   geckodriver::marionette INFO    Connecting to Marionette on localhost:54190`

**Comment by nick2012** [comment]
Let's try chrome + chromedriver:

executing `java -Dwebdriver.chrome.driver="C:/selenium/chromedriver.exe" -Dwebdriver.chrome.bin="C:/_portableapps/GoogleChromePortable_selenium01/GoogleChromePortable.exe" -jar "C:/selenium/selenium-server-standalone-3.0.1.jar" `

returns:

Evo@EVO-PC I:\
> java -Dwebdriver.chrome.driver="C:/selenium/chromedriver.exe" -Dwebdriver.chrome.bin="C:/_portableapps/GoogleChromePortable_selenium01/GoogleChromePortable.exe" -jar "C:/selenium/selenium-server-standalone-3.0.1.jar"
13:41:34.155 INFO - Selenium build info: version: '3.0.1', revision: '1969d75'
13:41:34.156 INFO - Launching a standalone Selenium Server
2016-11-27 13:41:34.181:INFO::main: Logging initialized @277ms
13:41:34.236 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:41:34.237 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
13:41:34.237 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:41:34.238 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
13:41:34.245 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
2016-11-27 13:41:34.289:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2016-11-27 13:41:34.312:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@1fcfece{/,null,AVAILABLE}
2016-11-27 13:41:34.585:INFO:osjs.ServerConnector:main: Started ServerConnector@3884b2{HTTP/1.1}{0.0.0.0:4444}
2016-11-27 13:41:34.585:INFO:osjs.Server:main: Started @682ms
13:41:34.586 INFO - Selenium Server is up and running


Let's use the same script with the addition of browser => chrome parameter:

```
use strict;
use warnings;
use Selenium::Remote::Driver;

my $driver = Selenium::Remote::Driver->new('browser_name' => 'chrome');
$driver->get('http://www.google.com');
print $driver->get_title . "\n"; # "Google"

my $query = $driver->find_element('q', 'name');
$query->send_keys('CPAN Selenium Remote Driver');

my $send_search = $driver->find_element('btnG', 'name');
$send_search->click;

# make the find_element blocking for a second to allow the title to change
$driver->set_implicit_wait_timeout(2000);
my $results = $driver->find_element('search', 'id');

print $driver->get_title . "\n"; # CPAN Selenium Remote Driver - Google Search
$driver->quit;
```

Script returns error:
```
> perl test01.pl
Error while executing command: get: no such session
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Evo-PC', ip: '10.223.44.2', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64), platform=ANY}]
Session ID: 235186f843a29e4c50bdd5234ee95eea at C:/StrawberryPerlX64/perl/site/lib/Selenium/Remote/Driver.pm line 313.
 at C:/StrawberryPerlX64/perl/site/lib/Selenium/Remote/Driver.pm line 313.
```

Selenium server logs the following events:
`13:41:40.563 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
13:41:40.619 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]])
13:41:40.627 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]
Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 31178
Only local connections are allowed.
13:41:41.350 INFO - Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
13:41:41.406 INFO - Detected dialect: OSS
13:41:41.423 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, browserName=chrome, javascriptEnabled=true, version=, platform=ANY}]]
13:41:41.429 INFO - Executing: [get: http://www.google.com])
13:41:41.734 WARN - Exception thrown
org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Evo-PC', ip: '10.223.44.2', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64), platform=ANY}]
Session ID: 235186f843a29e4c50bdd5234ee95eea
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:322)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
        at com.sun.proxy.$Proxy4.get(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:162)
        at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
        at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:25)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
13:41:41.743 WARN - Exception: no such session
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'Evo-PC', ip: '10.223.44.2', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64), platform=ANY}]
Session ID: 235186f843a29e4c50bdd5234ee95eea
13:41:41.772 INFO - Executing: [delete session: 2505fbbb-7a74-45e5-9e9d-43b25230e638])
13:41:42.768 INFO - Done: [delete session: 2505fbbb-7a74-45e5-9e9d-43b25230e638]`

**Comment by lukeis** [comment]
This isn't a concise issue report, seems like you're looking for user support. Could you please ask on the selenium-users google group:

https://groups.google.com/forum/#!forum/selenium-users

A few things to note, I believe geckodriver doesn't work with firefox portable, you can check on the mozilla/GeckoDriver github issues list.

The error you show with chromedriver seems like it worked, but then the session was gone when driver.get command was executed. I'm not sure why and there's not enough information here to tell what happened. So, please follow up on the users mailing list and when you have a clearly reproducible test case that shows an issue, please log it again here.
