### ISSUE TITLE
Docs: several typos in promise.js

### ISSUE THREAD

**Issue by Marketionist** [SeleniumHQ/selenium#3171]
There are several typos in http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html - see the screenshot below

![minor-typo](https://cloud.githubusercontent.com/assets/534603/20649191/b28fab22-b4c1-11e6-96f9-44eef59f7660.png)

**Comment by barancev** [comment]
Merged as 2984b13b7c54a8b3f757edcca798b7c15404987f
