### ISSUE TITLE
After running a few days，chromedriver and chrome can not work

### ISSUE THREAD

**Issue by liuqiangsic** [SeleniumHQ/selenium#3175]
## Meta -
OS:  windows7 and windows8

Selenium Version:  

Browser:  chrome

i have a program to acess some websites using  chromedriver on one machine，it open webdriver， access some websites，and then close the driver.

i run the program every 10min，it works very well . But a few days later，it can not work：the program can open chrome，but  chrome can not open any website， look like the browser is hanging， it can not give any reponse。

i close all chrome  and chromedriver  instances，and open the chrome manually，  the same question still exists-the browser  reponse very slow，can not access any website，hanging。that means chrome can not work!

 i restart the machine and run the program， same days later，the problem appears again.......

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
