### ISSUE TITLE
Selenium ide double click manual test case not working

### ISSUE THREAD

**Issue by dannycarlsson** [SeleniumHQ/selenium#3176]

**Comment by barancev** [comment]
Do you mean Selenium IDE does not record doulble clicks? Or something else?

**Comment by dannycarlsson** [comment]
Yes it does not record when I double click on a test

**Comment by dannycarlsson** [comment]
When I want to see if the manual test is selecting the correct element - it does not Record.

**Comment by dannycarlsson** [comment]
On the latest Mozilla and There is another issue - I can not drop and drag test cases in a Test suite up or down or in a Test case itself....

**Comment by dannycarlsson** [comment]
Both Issues is on the latest Mozilla Firefox

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
