### ISSUE TITLE
Selenium 3.0 does not run on firefox on the grid

### ISSUE THREAD

**Issue by jagdish-sp** [SeleniumHQ/selenium#3180]
When I run my scripts using Selenium 3.0 on the grid, only firefox instances open and nothing happens.

My setup is like this: Selenium - 3.0.0

Selenium Grid - hub and node started using Selenium 3.0.0 and with below options:

hub - java -jar selenium-server-standalone.jar -role hub -timeout 300000

node - java -Dwebdriver.gecko.driver=C:\Grid2\geckodriver-v0.11.1-win64\geckodriver.exe -jar selenium-server-standalone.jar -role node -hub http://localhost:4444/grid/register -port 5556 -nodeConfig se2config.txt

se2config.txt contents -

{

  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5556,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
    }

Firefox version - 47.0.2

Added geckodriver.exe path to PATH variable and also in the code using:

    System.setProperty("webdriver.gecko.driver","<path>")

The scripts run fine locally, but when run on the grid, it just launches the firefox browser and does not do anything.

Following are the node logs:

Driver info: driver.version: FirefoxDriver
    at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)

02:22:31.173 WARN - Exception: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@268c4f21, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@268c4f21, version=, platform=ANY, firefox_profile=UEsDBBQACAgIAIx2eUkAAAAAAAAAA...}], required capabilities = Capabilities [{}] Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700' The scr

I run the scripts from my local system and it gets executed on the grid node.

1.So what other changes or additions do I make to run tests on the grid.

2.Also, if I were to run my tests using jenkins, so since the code will be built on the jenkins node, how can I set the -Dwebdriver path for node, does it have to be the path of geckodriver on the jenkins slave or of that of the grid node.

**Comment by lukeis** [comment]
GeckoDriver doesn't really work with FF 47. You should be using the latest release with GeckoDriver (or even ideally Firefox Nightly). If you want to use 47, then the 'old' webdriver extension from the selenium project should work find. To do that you should add this to your node command line when starting up: `-Dwebdriver.firefox.marionette=false`

If you have follow up questions I suggest asking on the selenium-users google group:
https://groups.google.com/forum/#!forum/selenium-users
