### ISSUE TITLE
Selenium Grid - Ruby Capaybara - File upload doesn't work on selenium Grid but works on Selenium local machine

### ISSUE THREAD

**Issue by achyuthgit** [SeleniumHQ/selenium#3184]
## Meta -
OS:   Windows 7 
Selenium Version:  2.52.0, IDE, etc
Selenium Grid Extras  3.0.1
Browser:   Chrome 
Browser Version:  54.0.2840.99  (64-bit)

## Expected Behavior -

Below code which clicks on "Browse File" and open windows popup to browse file and submit should work on Selenium & Selenium Grid

**HTML Code** 

`<div layout="row" layout-align="center center" class="layout-align-center-center layout-row"><input type="file" accept="text/csv,application/vnd.ms-excel,application/vnd.oasis.opendocument.spreadsheet,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" id="navigate-to-browse-file" class="input-box full-width ng-pristine ng-untouched ng-valid ng-empty" ngf-select="" ng-model="vm.uploadFiles" ngf-multiple="false" aria-invalid="false"><label class="md-primary md-raised md-button md-ink-ripple" md-ink-ripple="" for="navigate-to-browse-file"><span>Browse File</span><div class="md-ripple-container"></div></label></div>
`

_Ruby Capybara RAutomation Code_

And I click the tag "span" with text "Browse File" - Clicking the browse button works

_Code for the selecting file in the window popup_

```
file=$uploadfile_path
file = Dir::pwd + "#{file}"
file=file.gsub! "/", "\\"
window_handle = RAutomation::Window.new(:title => /#{window}/i)
window_handle.text_field(:class => field_input, :index => 0).set file

```           

## Actual Behavior -

Above code works with Selenium and doesn't work with SeleniumGrid

## Steps to reproduce -

1. Click on browse file functionality in any application (cannot provide link to our application) ex: https://uploadfiles.io/
2. In windows popup enter the file path
![browse file](https://cloud.githubusercontent.com/assets/17161941/20725854/4276d4f6-b641-11e6-9da4-02415f597df9.png)
![window popup](https://cloud.githubusercontent.com/assets/17161941/20725855/4276f7f6-b641-11e6-840a-93adda97eae5.png)

**Comment by lukeis** [comment]
It's either a bug with Selenium Grid extras - https://github.com/groupon/Selenium-Grid-Extras
or with Chromedriver - https://bugs.chromium.org/p/chromedriver/issues/list

please include a way to completely reproduce the issue when you log bugs with them. I would recommend creating the sample page that causes the issue using jsfiddle.net and provide a complete set of webdriver commands that reproduces the issue.
