### ISSUE TITLE
FirefoxWebElement.get_attribute('outerHTML')  throws exception

### ISSUE THREAD

**Issue by digiology** [SeleniumHQ/selenium#3185]
## Meta -
OS:  OSX 10.11.6

Selenium Version:  3.0.2   with python 3.5.1

Browser:  Firefox 

Browser Version:  50.0 

## Expected Behavior -

FirefoxWebElement.get_attribute('outerHTML') should return html content.

## Actual Behavior -

Throws exception:  

selenium.common.exceptions.WebDriverException: Message: TypeError: invalid 'in' operand b 
(seems to be a javascript error)

## Steps to reproduce -

```from selenium.webdriver import Firefox
driver = Firefox()
driver.get('http://www.bl.uk/events')  # happens with this webpage 

for node in driver.find_elements_by_xpath('//body//a'): 
     node.get_attribute('outerHTML')  # throws exception

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
