### ISSUE TITLE
Add icon for HtmlUnit as browserType in Selenium Grid

### ISSUE THREAD

**Issue by dreamsivaraj123** [SeleniumHQ/selenium#3190]
## Meta -
OS:  LINUX/WINDOWS
Selenium Version:  2.53 / 3.0.1
Browser:  HtmlUnit

Browser Version:  NA

## Expected Behavior -
Currently Hub in Selenium Grid display's icon for Firefox, IE, Chrome and PhantonJS. But it doesn't show any icon for HtmlUnit as browser.

## Actual Behavior -
Kindly add an icon for HtmlUnit as browserType

## Steps to reproduce -

1. Create a Hub by running java -jar selenium-server-standalone-3.0.1.jar -role hub
2. Create a node by running java -jar selenium-server-standalone-3.0.1.jar -role node -hub http://127.0.0.1:4444/grid/register -nodeConfig /home/sivarajr/Desktop/nodeConfig_3.0.json
3. Now check http://127.0.0.1:4444/grid/console where Firefox, IE, Chrome has icons. but HtmlUnit doesn't have any icon.
![htmlunit](https://cloud.githubusercontent.com/assets/17315088/20793737/9064363c-b7ee-11e6-955b-cb569291881c.png)

**Comment by lukeis** [comment]
What icon do you think it should be? I'm not aware of them having one
http://htmlunit.sourceforge.net/

**Comment by dreamsivaraj123** [comment]
![html-icon_new](https://cloud.githubusercontent.com/assets/17315088/20885890/3e46cfbc-bb19-11e6-8d8d-42ebc045a22f.png)

**Comment by dreamsivaraj123** [comment]
![html-icon_new](https://cloud.githubusercontent.com/assets/17315088/20885910/67a1cbe6-bb19-11e6-96dd-15b61667ede8.png)

**Comment by dreamsivaraj123** [comment]
![html-icon](https://cloud.githubusercontent.com/assets/17315088/20885930/74ce6392-bb19-11e6-869e-ad5e95c28496.png)

**Comment by dreamsivaraj123** [comment]
What about the attached one. I have created this.

**Comment by dreamsivaraj123** [comment]
![browser-icon1](https://cloud.githubusercontent.com/assets/17315088/20886321/882d930c-bb1b-11e6-89fb-9ac513b503eb.png)
