### ISSUE TITLE
IE screenshot returns as black image using selenium server standalone 2.53.1 and 3.0.1

### ISSUE THREAD

**Issue by ambikashri** [SeleniumHQ/selenium#3193]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.1,3.0.1
Browser:  
Internet Explorer 11

I am trying use the screenshot.save method to save the screenshot while running scripts in IE 11 browser.

But the image stored always is a black image

My browser capabilities are as below

if opts['browser_selection'] =~ /^(ie|internet explorer)$/i
                browser_capabilities[:browserName] = 'internet explorer'
                browser_capabilities[:platform] = 'WINDOWS'
                browser_capabilities[:ignoreProtectedModeSettings] = true
                browser_capabilities[:ignoreZoomSetting] = true
                browser_capabilities[:nativeEvents] = false
                browser_capabilities[:unexpectedAlertBehaviour] = 'accept'
                browser_capabilities[:enablePopups] = true
                browser_capabilities[:enablePersistentHover] = true
                browser_capabilities[:requireWindowFocus] = true
end

It seems to be working fine if selenium hub and node are run manually but when I make it run in the background the screenshot is black

**Comment by ambikashri** [comment]
I have tried the 32 bit IE driver as well as 64bit IE driver with selenium server stand 3.0.1

**Comment by lukeis** [comment]
what do you mean by "run in the background"? If you're running it as a service or otherwise detaching the user session from the windows machine... then that isn't supported.

**Comment by ambikashri** [comment]
We aren't running it as a service. We have configured the hub and node in the "Task Scheduler". So when the script is running, we can't see the browser instance.

**Comment by lukeis** [comment]
That won't work at all then, screenshotting only works if while logged into the windows host as a user and the browser is visible, this includes other applications that may be covering IE at the time. Which is why there's the requireWindowFocus capability. 

We have no intention of fixing this for IE as windows itself makes it basically impossible.

**Comment by Raj0301** [comment]
Ambi, Are you able to capture screenshots when GridHub and node is running in the TaskScheduler. Could you help us to know how to fix this issues.

we are also facing issues. get Black screen when we run the scripts.
