### ISSUE TITLE
Unexpected errors after some time. Msg: TypeError: pagesets[i].getUISpecifierStringStubs is not a function

### ISSUE THREAD

**Issue by SlitEye** [SeleniumHQ/selenium#3194]
## Meta -
**OS:**  Windows 7 Enterprise SP1 x64
**Selenium Version:**  Selenium IDE for Firefox v2.9.1.1-signed
**Browser:**  Firefox for Windows systems
**Browser Version:**  
from Firefox 49 up to Firefox 50.0.2 (32-bit) and also Firefox 50.0.2 (64-bit)
![2016-12-02_10h22_57_firefoxinfos](https://cloud.githubusercontent.com/assets/24313436/20831120/e523a2f8-b883-11e6-95db-9714c14047ea.png)
**Language (OS | Browser: Firefox | Selenium IDE addon):** english | german | german

**Currently installed firefox and Selenium IDE addons:**
- Selenium IDE: v2.9.1.1-signed
- Selenium IDE - SelBlocks: v2.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed

![2016-12-02_10h21_32_installedaddons](https://cloud.githubusercontent.com/assets/24313436/20831118/e5201c0a-b883-11e6-9362-33ac5e67eb3f.png)

**Installed addons before / in the past:**
- Selenium IDE: v2.9.1.1-signed
- Highlight Elements (Selenium IDE): v1.22.1-signed.1-signed
- File Logging (Selenium IDE): v3.0.1-signed
- Log Search Bar (Selenium IDE): v1.22.1-signed.1-signed
- Stored Variables (Selenium IDE): v2.0.1-signed.1-signed
- Test Results (Selenium IDE): v2.0.1-signed.1-signed
- Page Coverage (Selenium IDE): v1.15.1-signed.1-signed
- Screenshot on Fail (Selenium IDE): v1.14.1-signed.1-signed
- Selenium IDE: Selenium 2 Excel Converter: v1.0.1.1-signed.1-signed
- Selenium Wiki Formatter: v1.0.1-signed.1-signed
- Separated Values Formatter (Selenium IDE): v1.0.0.1-signed.1-signed
- WebDriver Backed Formatters: v1.0.4.1-signed.1-signed
- SeLite
-- SeLite AutoCheck: v0.12
-- SeLite Clipboard And Indent: v0.23
-- SeLite Commands: v0.98
-- SeLite DB Objects: v0.91
-- SeLite Exit Confirmation Checker: v0.14
-- SeLite Miscellaneous: v1.09
-- SeLite SelBlocks Global: v2.68
-- SeLite Settings: v0.65
-- SeLite SQLite Connection Manager: v0.77
-- SeLite TestCase Debug Context: v0.80
-- SeLite Bootstrap: v0.96
-- SeLite Extension Sequencer: v0.53
-- SeLite Run All Favorites: v0.15

**Aditions information about firefox ide:**
Installed firefox plugins:
![2016-12-02_10h22_32_installedplugins](https://cloud.githubusercontent.com/assets/24313436/20831119/e5217460-b883-11e6-8994-f4793cee85fb.png)

**Selenium IDE Configuration (Menu > Options):**
![2016-12-02_10h24_56_seleniumideconfig1](https://cloud.githubusercontent.com/assets/24313436/20831121/e52473ae-b883-11e6-9e46-8b1313cc4fff.png)

![2016-12-02_10h25_06_seleniumideconfig2](https://cloud.githubusercontent.com/assets/24313436/20831122/e52641ca-b883-11e6-8a97-63ebc03faf1f.png)

![2016-12-02_10h25_14_seleniumideconfig3](https://cloud.githubusercontent.com/assets/24313436/20831123/e526a2fa-b883-11e6-81b6-420064c1c83f.png)

![2016-12-02_10h25_20_seleniumideconfig4](https://cloud.githubusercontent.com/assets/24313436/20831125/e54d41ee-b883-11e6-97a4-b800f40e8e32.png)

![2016-12-02_10h25_44_seleniumideconfig5](https://cloud.githubusercontent.com/assets/24313436/20831126/e54d8e7e-b883-11e6-83f9-ba34eb8788b4.png)

**I have some JS snippets injected at the beginning of our test suites in a separate test case file:**
[ETC_Tenant_StdLib_Core.zip](https://github.com/SeleniumHQ/selenium/files/626985/ETC_Tenant_StdLib_Core.zip)

## Expected Behavior -
Proper functional Selenium IDE everytime.

## Actual Behavior -
For some time everything around the Selenium IDE works very well, but after some times later - with user actions and also without user actions - there are triggered several unexpected errors in the Selenium IDE for Firefox:

![2016-12-02_10h11_17](https://cloud.githubusercontent.com/assets/24313436/20831113/e5097a04-b883-11e6-8e2b-ddf4fbb027f3.png)

![2016-12-02_10h12_03](https://cloud.githubusercontent.com/assets/24313436/20831111/e508fa34-b883-11e6-99d0-3dcb8ed4d5f7.png)

If I click on any command line in Selenium IDE window:
![2016-12-02_10h12_25_onclick](https://cloud.githubusercontent.com/assets/24313436/20831112/e5092450-b883-11e6-8344-1600f92bf89c.png)

If I switch (key press) to the next or previously command line step with the keyboard arrow keys in Selenium IDE window:
![2016-12-02_10h13_16_keypress](https://cloud.githubusercontent.com/assets/24313436/20831115/e50c0904-b883-11e6-87bb-715160a79fab.png)

If I execute a command line in Selenium IDE window:
![2016-12-02_10h17_11_executecommand](https://cloud.githubusercontent.com/assets/24313436/20831114/e50bc3c2-b883-11e6-8d66-ba3de8ac123f.png)

After these such errors, the "Target" and "Value" field of command lines are empty and not editable, but the commands works well in browser window:
![2016-12-02_10h14_55](https://cloud.githubusercontent.com/assets/24313436/20831116/e50c6aa2-b883-11e6-9d57-d8803af69208.png)

**Error console of firefox:**
![2016-12-02_10h34_57_errorconsole](https://cloud.githubusercontent.com/assets/24313436/20831124/e54ca180-b883-11e6-9b88-29ddf0e702c9.png)

## Steps to reproduce -
For some time everything around the Selenium IDE works very well, but after some times later - with user actions and also without user actions - there are triggered several unexpected errors in the Selenium IDE for Firefox.

See also section "Actual Behavior" before. It's currently not possible for me to reproduce or provoke the described errors. 

I don't know really how I can reproduce or provoke the described errors. It seems to me, that the errors appears faster if I have executed my own JS injections in my test suites. But, my JS injections are only default ECMA JS.

## Workarounds -
Currently I must restart the Selenium IDE window and reload the last or new Selenium test suite.
Then I have some time to execute or developement without issues until the errors reappears.

Please start investigation an fix these errors, because the described errors are particularly disturbing in our productive operation (execution and also development of test cases).

There are also related tickets of me at other Selenium IDE / addons projects, see: 
https://github.com/SeLite/SelBlocksGlobal/issues/6
https://github.com/refactoror/SelBlocks/issues/31

Best regards

Kevin Marco Erler
QA at INTERSHOP Communications AG - FullService

**Comment by peter-kehl** [comment]
Dear Kevin,

Thank you for a detailed report.

The problem comes from ETC_Tenant_StdLib_Core.xhtml:
```
getEval | javascript:{ Object.prototype.GetAllProperties = function(){ return Object.getOwnPropertyNames(this); }; }
```
That upsets getPagesets() at https://github.com/SeleniumHQ/selenium/blob/master/javascript/selenium-core/scripts/ui-element.js#L984. The upset scenario is:

1. UIMap constructor sets instance field `pagesets` (https://github.com/SeleniumHQ/selenium/blob/master/javascript/selenium-core/scripts/ui-element.js#L835):
```
this.pagesets = new Object();
```

2. Later `pagesets` is used by
getUISpecifierStringStubs() (https://github.com/SeleniumHQ/selenium/blob/master/javascript/selenium-core/scripts/ui-element.js#L1153)

3. getUISpecifierStringStubs() calls `getPagesets`, which finds `GetAllProperties` as a key in  `this.pagesets` (https://github.com/SeleniumHQ/selenium/blob/master/javascript/selenium-core/scripts/ui-element.js#L984):
```
for (var pagesetName in this.pagesets) {
            pagesets.push(this.pagesets[pagesetName]);
        }
```

Selenium team,
- could you provide documentation on ETC_Tenant_StdLib_Core and similar files
- please follow Mozilla's suggestions and don't override prototypes of standard objects.

**Comment by peter-kehl** [comment]
Hello Kevin @SlitEye,

Has fixing your test case solved the problem?
