### ISSUE TITLE
Cannot start the driver service on http://localhost:

### ISSUE THREAD

**Issue by jishusharma** [SeleniumHQ/selenium#3195]
Steps to simulate the Issue  : 

var driverService = FirefoxDriverService.CreateDefaultService(@"D:\tools\Selenium dotnet\geckodriver-v0.9.0-win64", "geckodriver.exe");
                driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                driverService.HideCommandPromptWindow = true;
                driverService.SuppressInitialDiagnosticInformation = true;
                DriverInstance = new FirefoxDriver(driverService, new FirefoxOptions(), TimeSpan.FromSeconds(10));

Error: Cannot start the driver service on http://localhost:12879/

I tried to do driverService.Start(); just before creating new FirefoxDriver and found that it fails with the same exception. 

What I wish to know is why this particular code stopped working after upgrading to selenium-dotnet-3.0.1. 

If I revert back just the reference dlls WebDriver.dll and WebDriver.Support.dll to selenium-dotnet-2.53.1, then driverService.Start(); executes and everything works. 

Note: 
I started to use FirefoxDriverService after I found that FirefoxDriver constructor for DesiredCapabilities has become obsolete!

Specifications : 
Win7, Visual Studio, Firefox 50.0.2

**Comment by jishusharma** [comment]
Hi! 
Do we have any update on this?
P.S - We cannot update to the latest selenium :(

**Comment by barancev** [comment]
FYI: Latest geckodriver version is v0.11.1
If it does not work for you raise an issue in the geckodriver issue tracker.

**Comment by jishusharma** [comment]
Yes, thanks! It works now. I did raise the issue with gecko project but this is the response I got - 
https://github.com/mozilla/geckodriver/issues/372#issuecomment-265895954

**Comment by copavan** [comment]
jishusharma - May I know what was done to get the gecko working ?? I am getting an error - Cannot start the driver service on http://localhost:41992

**Comment by jishusharma** [comment]
Sorry for the late reply! As you can see, since I was not sure about where to raise this issue, with the Selenium or the Gecko team, I had reported at both the places and although Gecko team did not entertain this bug report earlier (mozilla/geckodriver#372 (comment), somehow their latest release at that time had fixed the issue.

**Comment by jishusharma** [comment]
@copavan 

Hello! Where you able to get a resolve for you? 
If not, then perhaps you can try this - 

1. Use the firefox driver service as mentioned below
2. Download the geckodriver-v0.11.1-win64 version for Gecko and reference this as mentioned below 
3. Strictly use the selenium version "selenium-dotnet-3.0.1". Because somehow the whole thing just starts to get messy with the latest selenium 3.3.0  release @barancev 

                var driverService = FirefoxDriverService.CreateDefaultService(@"D:\tools\Selenium dotnet\geckodriver-v0.11.1-win64", "geckodriver.exe");
                driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
DriverInstance = new FirefoxDriver(driverService, new FirefoxOptions(), TimeSpan.FromSeconds(10));

**Comment by copavan** [comment]
@jishusharma : Thanks much for your response. I followed exactly the same steps as you outlined but i am still getting the error "Cannot start the driver service on http://localhost:53251/". Can you pls help me fix this. Let me know if you need any info,

**Comment by jishusharma** [comment]
Well, I would suggest that you open a new bug with Selenium and Gecko projects! This will get their attention!
