### ISSUE TITLE
selenium-grid version 3.0+ support hub high availability？

### ISSUE THREAD

**Issue by jessyZu** [SeleniumHQ/selenium#3210]
did selenium-grid version 3.0+ support hub high availability？ I have many hubs , if one hub of them crashed,the nodes of it can't be found.

**Comment by lukeis** [comment]
grid wasn't designed to scale that way, it's only been intended to have one hub. With default configuration if a hub goes down, the nodes connected to it will attempt to re-register themselves to a hub at the same location (host / port). Bringing back online a hub at the same location will bring the nodes back on too.

A single hub on a host with nothing else running on it should be very stable. If you are seeing issues with that configuration, please let us know and provide as much detail as possible.

I would recommend having a separate server monitor the hub and then if/when the hub goes down it would know how to restore the hub.
