### ISSUE TITLE
Selenium 3 doesn't work/support WebDriverEventListener

### ISSUE THREAD

**Issue by melinda2424** [SeleniumHQ/selenium#3212]
Selenium 3 doesn't work/support WebDriverEventListener

**Comment by lmtierney** [comment]
Can you elaborate?

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by melinda2424** [comment]
Ah I see my issue for Selenium 3.0.1.
I implemented WebDriverEventListener.
2 implemented methods of this class had changed, they have additional parameter: CharSequence[]

public void beforeChangeValueOf(WebElement element, WebDriver driver)
public void beforeChangeValueOf(WebElement element, WebDriver driver, CharSequence[] keysToSend)

public void afterChangeValueOf(WebElement element, WebDriver driver)
public void afterChangeValueOf(WebElement element, WebDriver driver, CharSequence[] keysToSend)

No problem. Just updated with the changes.

Thanks!
