### ISSUE TITLE
window.focus() fails with 'JavaScript Error' on IE 11 under Jenkins

### ISSUE THREAD

**Issue by eulliot** [SeleniumHQ/selenium#3223]
## Meta -
OS:  Windows Server 2008 R2 Datacenter
Selenium Version:   2.53.0,
Browser:  Internet Explorer
Browser Version:  11.0.9600.18524 (32-bit) -->

## Background
In order to avoid loss of focus problems on IE, we include a line:
     **driver.execute_script("window.focus()")** 
in our test code. This works fine on all browsers when run in an interactive session. However, when we run the test code from Jenkins the call fails with:
      **selenium.common.exceptions.WebDriverException: Message: JavaScript error**
on IE11 (only). 

The code works fine on Chrome and Firefox and on IE9. The Jenkins job runs as the same user as  the interactive session. The iedriver.log doesn't seem to give anything helpful. 
Please find attached two iedriver.log files. One file was generated when running code in an interactive session and the second one when running code under Jenkins. See the difference on line 349 in iedriver.jenkins.log : **Specified element is not the active element. Keystrokes may go to an unexpected DOM element.**. And then in line 403 it crashes.
[iedriver.cmd_line.log.txt](https://github.com/SeleniumHQ/selenium/files/640093/iedriver.cmd_line.log.txt)
[iedriver.jenkins.log.txt](https://github.com/SeleniumHQ/selenium/files/640095/iedriver.jenkins.log.txt)

We're pretty stumped on this. Is there anything we can enable that would give more information on what is going wrong?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
