### ISSUE TITLE
Android Mobile Automation with selenium-server-standalone-3.0.1.jar and Appium

### ISSUE THREAD

**Issue by prasenjitnnd** [SeleniumHQ/selenium#3225]
OS:  Windows 7
Selenium Version:  3.0.1
Mobile with Appium

Current version of selenium ie 3.0.1 is not supporting Android device with appium.We can create androiddriver session and app is opening in device, but element not found exception is happening. After 2 days investigation with diff changes atlast found this is an issue with selenium-server-standalone-3.0.1.jar. I replaced with selenium-server-standalone-2.46.jar and its working perfectly.

**Comment by lukeis** [comment]
This sounds more like a bug for the appium project. This also provides no information on how to reproduce the problem and there doesn't appear anything we can do here. Please provide a reproducible test case and then we can reopen the issue, but first please log a bug with the appium project.
