### ISSUE TITLE
IE specific capabilities causing issues on Remote Browsers

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#3227]
A Variety of OS' all on Selenium Grid (All Windows 7/8 based)
Selenium Version:  2.53.4
Browser:  Grid IE
Browser Version:  
Variety of IE versions, from 10->11 not Edge

When assigning capabilities in the following way I get timeouts where I shouldn't.

```
capabilities = Selenium::WebDriver::Remote::Capabilities.internet_explorer(
      platform: platform,
      javascript_enabled: true,
      enable_persistent_hover: true,
      require_window_focus: true,
    )
```

It seems this way works fine though:

```
capabilities = Selenium::WebDriver::Remote::Capabilities.internet_explorer(
      platform: platform,
      javascript_enabled: true,
    )
    capabilities['ie.ensureCleanSession'] = true # Wipe all history and cookies
    capabilities['enablePersistentHover'] = true # Constantly fire mouseOver events
    capabilities['requireWindowFocus'] = true # Forces you to be focused for each interaction (Increases Accuracy)
```

The first way would be preferable and I believe is lighter at run-time

Thoughts?? I've searched the docs tirelessly for these values, and been told by previous workers setting these could speed up IE. I've also searched on the google-groups and not found much info on this (A secretive area so to speak)

Luke

**Comment by luke-hill** [comment]
As an update to this: I've found that require_window_focus appears to the the problematic capability.

Setting the other two and running them appears fine. The other one causes lots of timeouts on our IE runs. Circa 50% of all runs fail when adding in this capability

We checked this over about a weeks worth of runs (So over 100 runs, 40-50 failed)

**Comment by titusfortner** [comment]
I "fixed" this general problem the wrong way earlier this year. It should work if you are using the driver locally, but not via Remote Server / Grid. There are several methods that need to be removed from the individual Bridge classes and moved into the Capabilities class. Ruby also needs options classes for these browsers as well, instead of just hashes. This way we can move past the whole string/symbol confusions. We'll be discussing our approach on addressing this in the Ruby chat room on [Slack](https://seleniumhq.herokuapp.com/) if you want to join in, otherwise I'll update this issue when we've made progress. Thanks!

**Comment by luke-hill** [comment]
Cool, no problems. I'm now idling in that room all day today and tomorrow (As I'm UK working hours are roughly Midnight - 8am PST

**Comment by p0deje** [comment]
@titusfortner @luke-hill Have you guys figured out this problem?

**Comment by luke-hill** [comment]
I can take responsibility for this and re-triage. As the last issue state this was in was `2.53.4`

Once I get my local versions of grid running on my VM's (1-2 weeks). I can start retesting remote versions of Selenium up to 3.9 (Our current infrastructure is 3.4, and I'm having issues bumping past that).

Ask me again in April and I'll have an answer if this is broken (Is that ok?)

**Comment by p0deje** [comment]
Sure, looking forward to it.

**Comment by luke-hill** [comment]
Looking at this in "some" limited detail I observe the following (Note I'll need some help)

**Selenium 2.x series** _- Locally / Grid_
- This issue is still prevalent. However this is also with me capping the IEDriver at 2.53

**Selenium 3.0 - 3.2 series** _- Locally / Grid_
- This issue is still prevalent (Again capping the Driver at the requisite 3.0 - 3.2)

**Selenium 3.3 - 3.4 series** _- Locally / Grid_
- This issue is more intermittent. What I do notice is that when setting this capability (The one that seems to be flaky), the Operating System (Win8.1 / Win10), seems to affect the flaky rate (As does the commands sent through the driver to the Native Browser). I don't have enough info other than to say across around 1500 Scenario Runs (Cucumber) Across Scenarios varying from 10-100s in length. The fail rate was around 75% (Note that this IS an improvement)

**Selenium 3.5.0 ruby 3.5.0 IEDriver** _- Locally_
- Only ran locally as infrastructure not yet ready. Results largely similar to those observed in 3.3 / 3.4

**Selenium 3.6 - 3.8 series** _- Locally_
- Now is where things get interesting. As I upgraded the Driver through the 3.6 series (Noting that we aere now in W3C capable mode),  the failure rate seemed to "increase" slightly for The Win8.1 PC (Although note that this was not always observable).
Shortish Scenarios went down in failure rate to around 65%
Mediumish Scenarios stayed around 75%
Longish scenarios basically went back up to 100%

On Win10 roughly speaking the failure rate dropped slightly (Across the board)

Now in other news, I note that IEDriver 3.6 - 3.8 "seems" to have had some speed issues reported across a few tickets (Can't remember all the Issue request numbers). And Jim did some Speed optimisation work in 3.9 / 3.10. As far as I have observed from the stuff reported here and the fluctuation (Largely it seems down to the driver). **I want to close this Issue Request as a "nuance" of the Driver, and something which is still being largely worked on.**

I would however profess that given "what" happens when you touch `require_window_focus` that we either write some form of WARN Messages when you set it, or as part of Titus' work here: https://github.com/SeleniumHQ/selenium/issues/2478 (This piece of work starts to restrict "what" goes into a driver initialization) We begin to start phasing out some of these less desirable properties.

As for how to write those messages e.t.c. I'm not really sure how that works. Happy to look into something with some help.

**Comment by p0deje** [comment]
So you think we should be writing a warning when `require_window_focus` capability is requested? If so, I'd advise creating a separate issue because this needs to be implemented across all the bindings, if Jim and others think it makes sense.

Should we still keep this issue open?

**Comment by luke-hill** [comment]
We've actually got an issue at work where IE is blowing up (So we think upgrading might mitigate it, but thats a separate issue). But I know the driver is in a state of flux.

I remember being advised to set 2 new parameters to make IE "better", and in doing so it made it fail almost every time (On Se 2).

We've just dropped the capability from our driver instantiation. I can see what it does in the docs, but it just doesn't play nicely (In Ruby 2.53 - 3.8), better off without it I'd say. But again I don't have all the information.

**Comment by p0deje** [comment]
@luke-hill As we're approaching 4.x, I'm cleaning up issues/PR. What can we do to move forward with this issue?

**Comment by luke-hill** [comment]
Agreed. We need to clean this up. I am no longer at this company / nor do I use IE for testing at all now.

I remember when we discussed this April last year we said we should probably keep this open due to there maybe being a bug present in the IE Options.

What I would say is, IE Usage is definitely decreasing, so my gut is to look towards closing this soon if no-one comments on it.

As a hailmary... @jgs731 - Do you know if the situation with you guys is better / worse. Does IE work reliably, if so, does setting these capabilities in the driver cause issues still?

**Comment by jgs731** [comment]
@luke-hill Sorry for the delayed reply - we actually have phased out IEDriver usage in our tests a while ago, but we updated Selenium to a newer version that we'd hope it would run more reliably. It'll be some time until we have any update as this is a low-priority task ATM

**Comment by luke-hill** [comment]
Based on :point_up: I'm going to close this as "Present in IEDriver 2.53-3.5 and "probably fixed" in later versions.

If it's present going forward @p0deje it'll have to be raised against a 3.14 selenium or a 4.x version
