### ISSUE TITLE
does not read custom certificates installed globally in firefox. 

### ISSUE THREAD

**Issue by hossainelahi7** [SeleniumHQ/selenium#3231]
## Meta -
OS:  Windows 7
Selenium Version:  3.0.1
Browser:  Firefox
Browser Version:  50.0.2 (64-bit)
Programming Language: Java 7 or 8

## Expected Behavior -
Should start with browser certificates already installed in the browser of that system.

## Actual Behavior -
does not read custom certificates. As a result throws security warning and does not go to destination page. 

## Steps to reproduce -
1. Use a network that require a custom certificate to install in your system to connect to internet. 
2. Start Firefox 50.0.2 browser using geckoDriver
                                 			System.setProperty("webdriver.gecko.driver",System.getProperty("user.dir")+ "//driver//geckodriver.exe");
			DesiredCapabilities cap = DesiredCapabilities.firefox();
	        LoggingPreferences logPrefs = new LoggingPreferences();
	        logPrefs.enable(LogType.BROWSER, Level.SEVERE);
	        cap.setCapability(CapabilityType.LOGGING_PREFS, logPrefs);
	        cap.setBrowserName("firefox");
	        cap.setPlatform(Platform.ANY);
	        cap.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
	        cap.setCapability(CapabilityType.ENABLE_PROFILING_CAPABILITY, true);
			driver = new FirefoxDriver(cap);
3. Try to go to any URL, for example: "http://www.google.com" 
              driver.get(url);
4. See the warning that, you would see if the required certificate was not installed in your system.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
