### ISSUE TITLE
Unable to find Mozilla geckodriver in v3.0.3

### ISSUE THREAD

**Issue by mrjlynch** [SeleniumHQ/selenium#3236]
I upgraded `selenium-webdriver` from `2.53.4` to `3.0.3` and started getting the following error in Rspec tests:
```
Selenium::WebDriver::Error::WebDriverError:
             Unable to find Mozilla geckodriver. Please download the server from https://github.com/mozilla/geckodriver/releases and place it somewhere on your PATH. More info at https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver.
```

Any ideas? Thanks

**Comment by barancev** [comment]
Please read the error message again and do what it suggests.

**Comment by mrjlynch** [comment]
Thanks for the prompt response @barancev. 

Any chance you could provide some context about why this has presumably changed in v3? 

Thanks!

**Comment by barancev** [comment]
Drivers are provided by browser vendors now.

**Comment by natetech333** [comment]
If anyone comes across this post... you can use a gem to resolve downloading the driver.

https://github.com/flavorjones/chromedriver-helper

**Comment by titusfortner** [comment]
If anyone comes across this post...  the current maintainer for `chromedriver-helper` is looking to step down so its future is in doubt. 

Check out https://github.com/titusfortner/webdrivers/

**Comment by natetech333** [comment]
Hmmm. I realized today. Poltergeist with PhantomJS... and webkit driver...
both are deprecated. And selenium gem includes the drivers by default for
headless and non headless. Is there still a need for this chrome driver
helper gem? Or will it just be supporting legacy code?

**Comment by titusfortner** [comment]
As does webdrivers, which also helps install drivers for each of the other browsers.
