### ISSUE TITLE
Avoiding getting `'NoneType' object has no attribute 'path'` on selenium quit()?

### ISSUE THREAD

**Issue by ronbarak** [SeleniumHQ/selenium#3239]
## Meta -
OS:  Cygwin 32 bits on Windows 7

Selenium Version:  3.0.2

Browser:  Firefox

Browser Version:  

## Expected Behavior -
When running Selenium Webdriver Python script, one shouldn't get any exception related messages after executing self.driver.quit(). 

## Actual Behavior -
When running Selenium Webdriver Python script, one gets a 'NoneType' object has no attribute 'path' after executing self.driver.quit(). 

## Steps to reproduce -

$ cat demo_NoneType_attribute_error.py
# -*- coding: utf-8 -*-
from selenium import webdriver
import unittest

class TestPass(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()

    def test_pass(self):
        pass

    def tearDown(self):
        print("doing: self.driver.quit()")
        try:
            self.driver.quit()
        except AttributeError:
            pass

if __name__ == "__main__":
    unittest.main()

$ python demo_NoneType_attribute_error.py
doing: self.driver.quit()
'NoneType' object has no attribute 'path'
.
----------------------------------------------------------------------
Ran 1 test in 19.807s

OK

$

See https://stackoverflow.com/questions/40998945/how-to-avoid-getting-nonetype-object-has-no-attribute-path-on-selenium-qui/41011364?noredirect=1#comment69390283_41011364 for problem description and possible **solution**.

**Comment by gwerbin** [comment]
I'm able to reproduce reliably on macOS 10.11.6 under python 3.5.2.

**Comment by cgoldberg** [comment]
AFAICT, this was already fixed with a commit on Oct. 21: 
https://github.com/SeleniumHQ/selenium/commit/9157c7071f9900c2608f5ca40ae4f518ed373b96#diff-3ae9b88bbdc04edbf1ed5f6e78d10661L189

it was included in selenium 3.0.2.  
@ronbarak can you verify you are really running 3.0.2?  what's the output from:
`$ python -c "import selenium; print(selenium.__version__)"`

**Comment by barancev** [comment]
Closing as fixed
