### ISSUE TITLE
Attach to IE browser not spawned by selenium

### ISSUE THREAD

**Issue by rajsaggi** [SeleniumHQ/selenium#3240]
I wanted to automate the LoadRunner scripting as the workflows are large and needs changes with every build, my plan is to launch the IE brouswer using vugen and then start a selenium script for the same workflow and attach the webdriver with the running browser of vugen. This will help me record the flow in LoadRunner. I see a post that this is possible with Selenium2 but so far i could not able to do so, I tried with 

CODE:
for (String handle : driver.getWindowHandles()) {
driver.switchTo().window(handle);
}
but this is returning the connection key of the browser launched by WebDriver and not the browser which is already opened by LoadRunner.

Any help on this will be highly appreciated. Thanks.Rajarshee

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
