### ISSUE TITLE
Firefox Stopped Working Popup appears when calling webdriver.quit() method using Firefox V50.0.2.6177 (latest)

### ISSUE THREAD

**Issue by LirazShay** [SeleniumHQ/selenium#3241]
After upgrading to Firefox v50 a window now pops up and says Firefox
has stopped working when running my test cases. The test cases execute fine, but I
get the popup when trying to execute WebDriver.quit().

Environment information : Windows 7
Firefox : V50.0.2.6177
Firefox driver - local instance
geckodriver 
v0.11.1

Additional Windows output:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	50.0.2.6177
  Application Timestamp:	583e4bb4
  Fault Module Name:	mozglue.dll
  Fault Module Version:	50.0.2.6177
  Fault Module Timestamp:	583e4b91
  Exception Code:	80000003
  Exception Offset:	0000ed43
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by LirazShay** [comment]
![ff50 stopped working](https://cloud.githubusercontent.com/assets/16083652/21110605/809f4e2e-c0a6-11e6-9e2a-9f8aca6ec26c.png)

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net
