### ISSUE TITLE
Selenium-RC documentation page displayed encoded format text if we navigate from Sel-IDE help content in http://www.seleniumhq.org/ website

### ISSUE THREAD

**Issue by suneethanulu** [SeleniumHQ/selenium#3246]
## Meta -
OS:  
Windows8 , 64 bit 

Browser:  
 Internet Explorer,  Firefox , Chrome

Browser Version:   
IE11 , Forfox 50 , Chrome 55

## Expected Behavior -
Selenium-RC documentation text should displayed in English language 

## Actual Behavior -
Selenium-RC documentation text displayed in encoded format  language  instead of English language 

## Steps to reproduce -
1. Navigate to http://www.seleniumhq.org/
2. Click on Documentation tab
3.  click on "Executing Selenium-IDE Tests on Different Browsers" link under Selenium IDE section
4. Click on "Run Selenese tests"

Note  : Direct page navigation is working fine[ Documention -> Selenium RC ]
http://www.seleniumhq.org/docs/05_selenium_rc.jsp 

Selenium-RC documentation
![selenium-rc-documentation-page](https://cloud.githubusercontent.com/assets/24540827/21132622/d856dd80-c0c9-11e6-9bf2-c69e5cf5aafe.png)
 text displayed in encoded format  language  instead of English language

**Comment by lukeis** [comment]
You somehow found a link with /cn in it, remove that from your URL and you'll find the English version. 

I just tried on the link you described and it linked me appropriately to the English version. 
http://www.seleniumhq.org/docs/02_selenium_ide.jsp#executing-selenium-ide-tests-on-different-browsers

I'll double check the page later for any Chinese links in the English sections. Also please log bugs for the website in its own repo:
https://github.com/SeleniumHQ/www.seleniumhq.org

**Comment by lukeis** [comment]
fixed it now
