### ISSUE TITLE
supported firefox  version with ruby 

### ISSUE THREAD

**Issue by nnvnaveen** [SeleniumHQ/selenium#3253]
my ruby gem plugin selenium webdriver version is 3.0.3
browser version firefox 46
ruby version ruby 2.0.0p643 (2015-02-25) [i386-mingw32]
OS version Windows 7 Enterprise.

I am not able to spin firefox browser using my ruby script with selenium webdriver.

what is the correct mapping

**Comment by cgoldberg** [comment]
you need FF > 47.0.1

**Comment by titusfortner** [comment]
If you want to use Selenium 3 with Firefox 46, you need to pass in `marionette: false` into the desired_capability.

**Comment by nnvnaveen** [comment]
I got the below exception when I used selenium webdriver gem version 3.0.0.
Firefox 46.0.1


y200/lib/ruby/2.0.0/net/http/generic_request.rb:27:in `initialize': HTTP request path is empty (ArgumentError)
  from C:/Ruby200/lib/ruby/2.0.0/net/http/request.rb:14:in `initialize'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:91:in `new'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:91:in `new_request_for'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:56:in `request'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:84:in `request'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:647:in `raw_execute'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/common/driver.rb:57:in `new'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/common/driver.rb:57:in `for'
  from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver.rb:82:in `for'

My simple script

require 'selenium-webdriver'

Selenium::WebDriver::Firefox::Binary.path='C:/Users/nnalam/AppData/Local/Mozilla Firefox/firefox.exe'
caps = Selenium::WebDriver::Remote::Capabilities.internet_explorer
caps['marionette'] = false
driver = Selenium::WebDriver.for(:remote, :desired_capabilities => caps)
#driver = Selenium::WebDriver.for :firefox
driver.navigate.to "wwww.google.com"

element = driver.find_element(:name, 'q')
element.send_keys "Selenium Tutorials"
element.submit

driver.quit

**Comment by nnvnaveen** [comment]
I got the below error 

Ruby200/lib/ruby/2.0.0/net/http/generic_request.rb:27:in `initialize': HTTP request path is empty (ArgumentError)
     from C:/Ruby200/lib/ruby/2.0.0/net/http/request.rb:14:in `initialize'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:91:in `new'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:91:in `new_request_for'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:56:in `request'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/default.rb:84:in `request'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:647:in `raw_execute'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:109:in `create_session'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/remote/bridge.rb:69:in `initialize'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/common/driver.rb:57:in `new'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver/common/driver.rb:57:in `for'
     from C:/Ruby200/lib/ruby/gems/2.0.0/gems/selenium-webdriver-3.0.3/lib/selenium/webdriver.rb:82:in `for'
     from sel-1.rb:6:in `<main>'


----------- sample code
require 'selenium-webdriver'

Selenium::WebDriver::Firefox::Binary.path='C:/Users/nnalam/AppData/Local/Mozilla Firefox/firefox.exe'
caps = Selenium::WebDriver::Remote::Capabilities.internet_explorer
caps['marionette'] = false
driver = Selenium::WebDriver.for(:remote, :desired_capabilities => caps)
#driver = Selenium::WebDriver.for :firefox
driver.navigate.to "wwww.google.com"

element = driver.find_element(:name, 'q')
element.send_keys "Selenium Tutorials"
element.submit

driver.quit


And driver version selenium webdriver 3.03. and ff version 46.0.1

**Comment by titusfortner** [comment]
@nnvnaveen - This isn't the right place to discuss your issue. I've replied to your post on wtr-general. We'll get it figured out there.
