### ISSUE TITLE
Looking for selenium-java-2.37.0.zip

### ISSUE THREAD

**Issue by craneml** [SeleniumHQ/selenium#3254]
We've got multiple maintenance streams; some of our older ones use Selenium 2.37.0 as part of their testing.  I just noticed today that I can no longer download from:

http://selenium.googlecode.com/files/selenium-java-2.37.0.zip

In fact, there doesn't seem to be any versions pre-2.39 available now.  

Anyone know if this is temporary?  If not, I'd *love* to get my hands on that file and I'll host it myself for my pipeline.  (Upping the version of Selenium is out of the question - too much adoption work for older versions.)

Thanks.

**Comment by ddavison** [comment]
> In fact, there doesn't seem to be any versions pre-2.39

Not on selenium-release.storage.googleapis no.  what you can do, is see:

**Comment by lukeis** [comment]
yep, as previously said. Clone the selenium repo `git checkout selenium-$VERSION` and then run `./go release`.  The artifacts you're looking for will be in build/dist folder. Google code unfortunately shut down and no one copied the old artifacts that were uploaded there.

**Comment by cgoldberg** [comment]
@craneml 
http://central.maven.org/maven2/org/seleniumhq/selenium/selenium-java/

**Comment by craneml** [comment]
Thanks everyone.
