### ISSUE TITLE
chrome close browser elpased time more than 1 minute

### ISSUE THREAD

**Issue by brusand** [SeleniumHQ/selenium#3258]
## Meta -
OS:  
w7
Selenium Version:  
latest
Browser:  
chrome

Browser Version:  

## Actual Behavior -
Close browser take more than 1 minute
in the file https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/service.py

the call of this method took more than 1 minute : 
 try:
            self.send_remote_shutdown_command() // This line take more than 1 minute

**Comment by lmtierney** [comment]
I believe this may have been fixed while fixing a different issue. Please open a new issue if you are still experiencing it with the latest version.
