### ISSUE TITLE
Sendkeys isn't working on IE 11 when using capability as setCapability(InternetExplorerDriver.NATIVE_EVENTS, true);

### ISSUE THREAD

**Issue by sankritraj** [SeleniumHQ/selenium#3261]
Sendkeys isn't working on IE 11 when using capability as setCapability(InternetExplorerDriver.NATIVE_EVENTS, true);

When i remove this capability click functionality stopped working.

1.This is working fine on Chrome and firefox. 
2. I have tried IEDriverServer.exe from 2.51 to 3.0.0

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sankritraj** [comment]
here i am simply trying to login.
1.It is perfectly inputted to username. But once control moves on another element.Values which was inputed disappear.

Here is the capability i am using
System.setProperty("webdriver.ie.driver",Constants.InternetExplorerEPath);
			DesiredCapabilities caps = DesiredCapabilities.internetExplorer();
			caps.setCapability("ignoreZoomSetting", true);
			caps.setCapability(InternetExplorerDriver.NATIVE_EVENTS, true);  
			caps.setCapability("unexpectedAlertBehaviour", "accept");
			caps.setCapability("ignoreProtectedModeSettings", true);
			caps.setCapability("disable-popup-blocking", true);
			caps.setCapability("enablePersistentHover", true);
			driver = new InternetExplorerDriver(caps);

**Comment by jimevans** [comment]
This test case is far from concise, and is clearly related to the specific site being automated. There is nothing actionable in this report without the actual HTML, or a page that acts similarly.
