### ISSUE TITLE
IEDriverServer 2.53.1 crashing on Windows 7 with IE11

### ISSUE THREAD

**Issue by zdmeyers** [SeleniumHQ/selenium#3271]
## Meta -
OS:  Windows 7

Selenium Version:  2.53.1

Browser:  IE

Browser Version:  11

## Expected Behavior -
Code navigates to screen, clicks button.
## Actual Behavior -
Code navigates to screen, call to WebDriverWait.until(ExpectedConditions.elementToBeClickable(<locator>) passes the isEnabled check (I can see it passing when turning on TRACE level logging for IEDriverServer) but fails to click the element. This is the relevant information from the TRACE level logging of IEDriverServer:

> 10:39:03.218 INFO - Executing: [click: 24 [[InternetExplorerDriver: internet explorer on WINDOWS (ec60c027-20cd-4099-9467-32f1bf512fb0)] -> id: CREATE_SITE]])
T 2016-12-21 10:39:03:219 server.cc(174) Entering Server::ProcessRequest
T 2016-12-21 10:39:03:219 server.cc(238) Entering Server::ReadRequestBody
T 2016-12-21 10:39:03:219 server.cc(183) Process request with: URI: /session/ec60c027-20cd-4099-9467-32f1bf512fb0/element/ba2aee8c-89fa-4236-ad58-c02f1e66fc56/click HTTP verb: POST
body: {"id":"ba2aee8c-89fa-4236-ad58-c02f1e66fc56"}
T 2016-12-21 10:39:03:219 server.cc(272) Entering Server::DispatchCommand
T 2016-12-21 10:39:03:219 server.cc(579) Entering Server::LookupCommand
D 2016-12-21 10:39:03:219 server.cc(281) Command: POST /session/ec60c027-20cd-4099-9467-32f1bf512fb0/element/ba2aee8c-89fa-4236-ad58-c02f1e66fc56/click {"id":"ba2aee8c-89fa-4236-ad58-c02f1e66fc56"}
T 2016-12-21 10:39:03:219 server.cc(395) Entering Server::LookupSession
T 2016-12-21 10:39:03:219 IESession.cpp(212) Entering IESession::ExecuteCommand
T 2016-12-21 10:39:03:219 IECommandExecutor.cpp(165) Entering IECommandExecutor::OnSetCommand
T 2016-12-21 10:39:03:219 command.cc(31) Entering Command::Deserialize
D 2016-12-21 10:39:03:219 command.cc(36) Raw JSON command: { "name" : "click", "locator" : { "sessionid" : "ec60c027-20cd-4099-9467-32f1bf512fb0", "id" : "ba2aee8c-89fa-4236-ad58-c02f1e66fc56" }, "parameters" : {"id":"ba2aee8c-89fa-4236-ad58-c02f1e66fc56"} }
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(176) Entering IECommandExecutor::OnExecCommand
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(485) Entering IECommandExecutor::DispatchCommand
T 2016-12-21 10:39:03:220 IESession.cpp(233) Beginning wait for response length to be not zero
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(558) Entering IECommandExecutor::IsAlertActive
T 2016-12-21 10:39:03:220 Browser.cpp(707) Entering Browser::GetActiveDialogWindowHandle
T 2016-12-21 10:39:03:220 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2016-12-21 10:39:03:220 IECommandExecutor.cpp(572) No alert handle is found
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:220 IECommandHandler.cpp(40) Entering IECommandHandler::GetElement
T 2016-12-21 10:39:03:220 IECommandExecutor.cpp(699) Entering IECommandExecutor::GetManagedElement
T 2016-12-21 10:39:03:220 ElementRepository.cpp(31) Entering ElementRepository::GetManagedElement
T 2016-12-21 10:39:03:226 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:226 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:226 Browser.cpp(120) Entering Browser::GetDocument
I 2016-12-21 10:39:03:226 Browser.cpp(124) No child frame focus. Focus is on top-level frame
T 2016-12-21 10:39:03:237 Browser.cpp(607) Entering Browser::GetDocumentFromWindow
T 2016-12-21 10:39:03:244 InputManager.cpp(65) Entering InputManager::PerformInputSequence
D 2016-12-21 10:39:03:244 InputManager.cpp(86) Mutex acquired for user interaction.
T 2016-12-21 10:39:03:244 InputManager.cpp(409) Entering InputManager::MouseMoveTo
T 2016-12-21 10:39:03:244 ElementRepository.cpp(31) Entering ElementRepository::GetManagedElement
T 2016-12-21 10:39:03:244 Element.cpp(213) Entering Element::GetClickLocation
T 2016-12-21 10:39:03:244 Element.cpp(86) Entering Element::IsDisplayed
T 2016-12-21 10:39:03:244 Element.cpp(901) Entering Element::GetContainingDocument
T 2016-12-21 10:39:03:246 Script.cpp(44) Entering Script::Initialize
T 2016-12-21 10:39:03:246 Script.cpp(94) Entering Script::AddArgument(IHTMLElement*)
T 2016-12-21 10:39:03:246 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-12-21 10:39:03:246 Script.cpp(83) Entering Script::AddArgument(bool)
T 2016-12-21 10:39:03:246 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-12-21 10:39:03:246 Script.cpp(164) Entering Script::Execute
T 2016-12-21 10:39:03:246 Script.cpp(472) Entering Script::CreateAnonymousFunction
T 2016-12-21 10:39:03:305 Element.cpp(307) Entering Element::GetLocationOnceScrolledIntoView
T 2016-12-21 10:39:03:305 Element.cpp(438) Entering Element::GetLocation
T 2016-12-21 10:39:03:306 Element.cpp(574) Entering Element::IsInline
D 2016-12-21 10:39:03:307 Element.cpp(484) Element is a block element, using IHTMLElement2::getBoundingClientRect
W 2016-12-21 10:39:03:457 Element.cpp(499) -2147467259 [Unspecified error]: Cannot figure out where the element is on screen, client rect retrieval failed
T 2016-12-21 10:39:03:457 Element.cpp(850) Entering Element::CalculateClickPoint
T 2016-12-21 10:39:03:457 Element.cpp(789) Entering Element::GetClickableViewPortLocation
T 2016-12-21 10:39:03:457 Element.cpp(901) Entering Element::GetContainingDocument
T 2016-12-21 10:39:03:458 DocumentHost.cpp(267) Entering DocumentHost::GetDocumentMode
T 2016-12-21 10:39:03:463 Browser.cpp(90) Entering Browser::DocumentComplete
T 2016-12-21 10:41:13:929 Browser.cpp(294) Entering Browser::DetachEvents
10:41:14.228 INFO - Executing: [take screenshot])
10:41:16.271 INFO - Executing: [delete session: 68f90fd9-d638-4cbb-8861-939fc5eed09b])

A few lines from the bottom of the log, you can see a call into Element.cpp at line 499. This is where the error is coming from. For some reason, IHTMLElement2::getBoundingClientRect seems to be returning a negative value? As I watch the test case execute, I can see the button the code is trying to click on. It is visible and enabled on the screen.

## Steps to reproduce -

Unfortunately, I cannot provide exact code to reproduce the issue as the test case is for an internal piece of software. I can, however, explain to you what it is doing.
The code navigates to a screen on the UI and then attempts to click a button. The clicking of the button is done in this manner:
`WebElement ele = WebDriverWait.until(ExpectedConditions.elementToBeClickable(<locator>);
ele.click();`

Obviously that is more along the lines of pseudo-code, but you get the idea.

**Comment by zdmeyers** [comment]
And the relevant log from the isEnabled check showing that it is indeed passing:

> 10:39:03.150 INFO - Executing: [is enabled: 24 [[InternetExplorerDriver: internet explorer on WINDOWS (ec60c027-20cd-4099-9467-32f1bf512fb0)] -> id: CREATE_SITE]])
T 2016-12-21 10:39:03:151 server.cc(174) Entering Server::ProcessRequest
T 2016-12-21 10:39:03:151 server.cc(183) Process request with: URI: /session/ec60c027-20cd-4099-9467-32f1bf512fb0/element/ba2aee8c-89fa-4236-ad58-c02f1e66fc56/enabled HTTP verb: GET
body: {}
T 2016-12-21 10:39:03:151 server.cc(272) Entering Server::DispatchCommand
T 2016-12-21 10:39:03:151 server.cc(579) Entering Server::LookupCommand
D 2016-12-21 10:39:03:151 server.cc(281) Command: GET /session/ec60c027-20cd-4099-9467-32f1bf512fb0/element/ba2aee8c-89fa-4236-ad58-c02f1e66fc56/enabled {}
T 2016-12-21 10:39:03:151 server.cc(395) Entering Server::LookupSession
T 2016-12-21 10:39:03:151 IESession.cpp(212) Entering IESession::ExecuteCommand
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(165) Entering IECommandExecutor::OnSetCommand
T 2016-12-21 10:39:03:151 command.cc(31) Entering Command::Deserialize
D 2016-12-21 10:39:03:151 command.cc(36) Raw JSON command: { "name" : "isEnabled", "locator" : { "sessionid" : "ec60c027-20cd-4099-9467-32f1bf512fb0", "id" : "ba2aee8c-89fa-4236-ad58-c02f1e66fc56" }, "parameters" : {} }
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(176) Entering IECommandExecutor::OnExecCommand
T 2016-12-21 10:39:03:151 IESession.cpp(233) Beginning wait for response length to be not zero
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(485) Entering IECommandExecutor::DispatchCommand
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:151 IECommandExecutor.cpp(558) Entering IECommandExecutor::IsAlertActive
T 2016-12-21 10:39:03:151 Browser.cpp(707) Entering Browser::GetActiveDialogWindowHandle
T 2016-12-21 10:39:03:151 Browser.cpp(200) Entering Browser::GetContentWindowHandle
D 2016-12-21 10:39:03:152 IECommandExecutor.cpp(572) No alert handle is found
T 2016-12-21 10:39:03:152 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:152 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:152 IECommandHandler.cpp(40) Entering IECommandHandler::GetElement
T 2016-12-21 10:39:03:152 IECommandExecutor.cpp(699) Entering IECommandExecutor::GetManagedElement
T 2016-12-21 10:39:03:152 ElementRepository.cpp(31) Entering ElementRepository::GetManagedElement
T 2016-12-21 10:39:03:157 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:157 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:157 Browser.cpp(120) Entering Browser::GetDocument
I 2016-12-21 10:39:03:157 Browser.cpp(124) No child frame focus. Focus is on top-level frame
T 2016-12-21 10:39:03:166 Browser.cpp(607) Entering Browser::GetDocumentFromWindow
T 2016-12-21 10:39:03:172 Element.cpp(130) Entering Element::IsEnabled
T 2016-12-21 10:39:03:173 Element.cpp(901) Entering Element::GetContainingDocument
T 2016-12-21 10:39:03:175 Script.cpp(44) Entering Script::Initialize
T 2016-12-21 10:39:03:175 Script.cpp(94) Entering Script::AddArgument(IHTMLElement*)
T 2016-12-21 10:39:03:175 Script.cpp(100) Entering Script::AddArgument(VARIANT)
T 2016-12-21 10:39:03:175 Script.cpp(164) Entering Script::Execute
T 2016-12-21 10:39:03:175 Script.cpp(472) Entering Script::CreateAnonymousFunction
T 2016-12-21 10:39:03:208 response.cc(63) Entering Response::SetSuccessResponse
T 2016-12-21 10:39:03:209 response.cc(69) Entering Response::SetResponse
T 2016-12-21 10:39:03:209 IECommandExecutor.cpp(602) Entering IECommandExecutor::GetCurrentBrowser
T 2016-12-21 10:39:03:209 IECommandExecutor.cpp(608) Entering IECommandExecutor::GetManagedBrowser
T 2016-12-21 10:39:03:209 response.cc(51) Entering Response::Serialize
T 2016-12-21 10:39:03:213 IESession.cpp(242) Found non-zero response length
T 2016-12-21 10:39:03:213 IECommandExecutor.cpp(199) Entering IECommandExecutor::OnGetResponse
T 2016-12-21 10:39:03:213 IECommandExecutor.cpp(314) Entering IECommandExecutor::OnIsSessionValid
D 2016-12-21 10:39:03:213 server.cc(355) Response: {"sessionId":"ec60c027-20cd-4099-9467-32f1bf512fb0","status":0,"value":true}

T 2016-12-21 10:39:03:213 server.cc(408) Entering Server::SendResponseToClient
T 2016-12-21 10:39:03:213 response.cc(36) Entering Response::Deserialize
T 2016-12-21 10:39:03:213 server.cc(462) Entering Server::SendHttpOk
10:39:03.214 INFO - Done: [is enabled: 24 [[InternetExplorerDriver: internet explorer on WINDOWS (ec60c027-20cd-4099-9467-32f1bf512fb0)] -> id: CREATE_SITE]]

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/). Without it we can't debug and fix the issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
