### ISSUE TITLE
Unable to pass headers, cookies to selenium node

### ISSUE THREAD

**Issue by rahul6** [SeleniumHQ/selenium#3277]
OS:  OS X EL Capitan
Selenium Version:  3.0.1
Browser:  Chrome

I am running a Selenium Grid and a Node locally on my machine. I am trying to set some headers and cookies in the RemoteWebDriver Request. The same I can see in the grid logs but these values are not passed to the node and therefore I am unable to use this values during the test.

Is there any way to set headers, cookies , etc. before starting a test using RemoteWebDriver ?

Grid Log - 
19:04:18.790 DEBUG - http-outgoing-555 >> "POST /wd/hub/session/69056158-21a9-4fac-b0f6-4cfc13a3b326/url HTTP/1.1[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Authorization: Basic xxxxxxxxxxxxx==[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Cookie: $Version=1;testCookie=123[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Accept: application/json,application/json[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Cache-Control: no-cache[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "User-Agent: Jersey/2.17 (HttpUrlConnection 1.8.0_91)[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Connection: keep-alive[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Host: localhost:4444[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Pragma: no-cache[\r][\n]"
19:04:18.790 DEBUG - http-outgoing-555 >> "Content-Type: application/json[\r][\n]"
19:04:18.791 DEBUG - http-outgoing-555 >> "Content-Length: 35[\r][\n]"
19:04:18.791 DEBUG - http-outgoing-555 >> "Accept-Encoding: gzip,deflate[\r][\n]"
19:04:18.791 DEBUG - http-outgoing-555 >> "[\r][\n]"
19:04:18.791 DEBUG - http-outgoing-555 >> "{"url":"https://hookb.in/KAg5Wx1m"}"

Node Log -
19:04:19.037 DEBUG - Handling: POST /session/69056158-21a9-4fac-b0f6-4cfc13a3b326/url
19:04:19.038 INFO - Executing: [get: https://hookb.in/KAg5Wx1m])
19:04:19.038 DEBUG - Executing: get [2acb9ac757058e4c9bc9cbeb52fc1cd0, get {url=https://hookb.in/KAg5Wx1m}]
19:04:19.038 DEBUG - CookieSpec selected: default
19:04:19.038 DEBUG - Auth cache not set in the context
19:04:19.038 DEBUG - Connection request: [route: {}->http://localhost:29393][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
19:04:19.038 DEBUG - Connection leased: [id: 15][route: {}->http://localhost:29393][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
19:04:19.038 DEBUG - Opening connection {}->http://localhost:29393
19:04:19.039 DEBUG - Connecting to localhost/127.0.0.1:29393
19:04:19.039 DEBUG - Connection established 127.0.0.1:65288<->127.0.0.1:29393
19:04:19.039 DEBUG - http-outgoing-15: set socket timeout to 10800000
19:04:19.039 DEBUG - Executing request POST /session/2acb9ac757058e4c9bc9cbeb52fc1cd0/url HTTP/1.1
19:04:19.039 DEBUG - Target auth state: UNCHALLENGED
19:04:19.039 DEBUG - Proxy auth state: UNCHALLENGED
19:04:19.039 DEBUG - http-outgoing-15 >> POST /session/2acb9ac757058e4c9bc9cbeb52fc1cd0/url HTTP/1.1
19:04:19.039 DEBUG - http-outgoing-15 >> Content-Type: application/json; charset=utf-8
19:04:19.039 DEBUG - http-outgoing-15 >> Content-Length: 35
19:04:19.039 DEBUG - http-outgoing-15 >> Host: localhost:29393
19:04:19.039 DEBUG - http-outgoing-15 >> Connection: Keep-Alive
19:04:19.039 DEBUG - http-outgoing-15 >> User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_91)
19:04:19.040 DEBUG - http-outgoing-15 >> Accept-Encoding: gzip,deflate
19:04:19.040 DEBUG - http-outgoing-15 >> "POST /session/2acb9ac757058e4c9bc9cbeb52fc1cd0/url HTTP/1.1[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "Content-Length: 35[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "Host: localhost:29393[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "Connection: Keep-Alive[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_91)[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "Accept-Encoding: gzip,deflate[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "[\r][\n]"
19:04:19.040 DEBUG - http-outgoing-15 >> "{"url":"https://hookb.in/KAg5Wx1m"}"
19:04:20.306 DEBUG - http-outgoing-15 << "HTTP/1.1 200 OK[\r][\n]"
19:04:20.306 DEBUG - http-outgoing-15 << "Content-Length:72[\r][\n]"
19:04:20.306 DEBUG - http-outgoing-15 << "Content-Type:application/json; charset=utf-8[\r][\n]"
19:04:20.306 DEBUG - http-outgoing-15 << "Connection:close[\r][\n]"
19:04:20.306 DEBUG - http-outgoing-15 << "[\r][\n]"
19:04:20.306 DEBUG - http-outgoing-15 << "{"sessionId":"2acb9ac757058e4c9bc9cbeb52fc1cd0","status":0,"value":null}"
19:04:20.306 DEBUG - http-outgoing-15 << HTTP/1.1 200 OK
19:04:20.306 DEBUG - http-outgoing-15 << Content-Length:72
19:04:20.307 DEBUG - http-outgoing-15 << Content-Type:application/json; charset=utf-8
19:04:20.307 DEBUG - http-outgoing-15 << Connection:close
19:04:20.307 DEBUG - http-outgoing-15: Close connection
19:04:20.307 DEBUG - Connection discarded
19:04:20.307 DEBUG - Connection released: [id: 15][route: {}->http://localhost:29393][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
19:04:20.307 DEBUG - Executed: [2acb9ac757058e4c9bc9cbeb52fc1cd0, get {url=https://hookb.in/KAg5Wx1m}]
19:04:20.307 INFO - Done: [get: https://hookb.in/KAg5Wx1m]
19:04:20.307 DEBUG - Finished: POST /session/69056158-21a9-4fac-b0f6-4cfc13a3b326/url

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
