### ISSUE TITLE
Executing selenium-html-runner fails with "Test of browser failed: *firefox"

### ISSUE THREAD

**Issue by yaxv** [SeleniumHQ/selenium#3278]
## Meta -
OS:  
Windows Server 2008 R2 Standard Build 7601

Selenium Version:  
Selenium IDE 2.9.1

Browser:  
Firefox

Used Selenium IDE to create a small test script. The script runs fine in IDE but I'm having trouble running the script from the command line. I've tried version 45 which is the suggested version when opening an issue and I've tried the latest Firefox version which is 50. I see Firefox opened shortly but then it closes immediately. 

Using geckodriver-v0.11.1-win64.zip and also tried geckodriver-v0.11.1-win32.zip.

Error message output with Firefox version 45.

C:\Temp>java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*firefox" "http://127.0.0.1" "OpenGoogle.html" "PrintResults.html"

Multi-window mode is longer used as an option and will be ignored.
1482424271840   geckodriver     INFO    Listening on 127.0.0.1:46932
dec. 22, 2016 5:31:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1482424272449   mozprofile::profile     INFO    Using profile path C:\Users\[USERNAME_REMOVED]\AppData\Local\Temp\3\rust_mozprofile.IcKi3p6Y0gNx
1482424272465   geckodriver::marionette INFO    Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1482424272465   geckodriver::marionette INFO    Connecting to Marionette on localhost:55346
1482424272617   addons.manager  DEBUG   Application has been upgraded
1482424272646   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1482424272647   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1482424272650   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1482424272651   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1482424272651   addons.manager  DEBUG   Starting provider: XPIProvider
1482424272652   addons.xpi      DEBUG   startup
1482424272652   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1482424272653   addons.xpi      INFO    Mapping loop@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1482424272653   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1482424272654   addons.xpi      DEBUG   checkForChanges
1482424272655   addons.xpi      DEBUG   Loaded add-on state from prefs: {}
1482424272655   addons.xpi      DEBUG   New add-on loop@mozilla.org in app-system-defaults
1482424272656   addons.xpi      DEBUG   getModTime: Recursive scan of loop@mozilla.org
1482424272656   addons.xpi      DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1482424272656   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1482424272657   addons.xpi      DEBUG   getInstallState changed: true, state: {"app-system-defaults":{"loop@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\loop@mozilla.org.xpi","st":1
457052991000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1457052991000}}}
1482424272663   addons.xpi-utils        DEBUG   Opening XPI database C:\Users\[USERNAME_REMOVED]\AppData\Local\Temp\3\rust_mozprofile.IcKi3p6Y0gNx\extensions.json
1482424272665   addons.xpi-utils        DEBUG   New add-on loop@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1482424272674   DeferredSave.extensions.json    DEBUG   Save changes
1482424272674   addons.xpi-utils        DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1482424272677   DeferredSave.extensions.json    DEBUG   Starting timer
1482424272678   DeferredSave.extensions.json    DEBUG   Save changes
1482424272678   addons.xpi-utils        INFO    Hiding the updated system add-ons.
1482424272683   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1482424272696   addons.xpi      DEBUG   Calling bootstrap method install on loop@mozilla.org version 0.1
1482424272696   addons.xpi-utils        DEBUG   Make addon app-system-defaults:loop@mozilla.org visible
1482424272696   DeferredSave.extensions.json    DEBUG   Save changes
1482424272696   addons.xpi-utils        DEBUG   Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1482424272696   DeferredSave.extensions.json    DEBUG   Save changes
1482424272697   addons.xpi      DEBUG   Updating XPIState for {"id":"loop@mozilla.org","syncGUID":"XRPhpkOcIErw","location":"app-system-defaults","version":"0.1","type":"extension","internalName":null,"updateUR
L":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Hello Beta","description":"Web sharing for Firefox","cre
ator":"Mozilla","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\loop@mozilla.org.xpi","installDate"
:1457052991000,"updateDate":1457052991000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":3086125,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBin
aryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0a1","maxVersion":"45.0"},{"id":"xpcshell@tests.mozilla.org","
minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1482424272697   addons.xpi      DEBUG   getModTime: Recursive scan of loop@mozilla.org
1482424272697   addons.xpi      DEBUG   Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"3uxWe9aMQPC8","location":"app-global","version":"45.0","type":"theme","internalName":"cla
ssic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","desc
ription":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program File
s\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1457052991000,"updateDate":1457052991000,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":n
ull,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","m
inVersion":"45.0","maxVersion":"45.0"}],"targetPlatforms":[],"seen":true}
1482424272697   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1482424272698   DeferredSave.extensions.json    DEBUG   Save changes
1482424272698   addons.xpi      DEBUG   Updating database with changes to installed add-ons
1482424272698   addons.xpi-utils        DEBUG   Updating add-on states
1482424272699   addons.xpi-utils        DEBUG   Writing add-ons list
1482424272701   addons.xpi      DEBUG   Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1482424272702   addons.xpi      DEBUG   Calling bootstrap method startup on loop@mozilla.org version 0.1
1482424272713   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1482424272713   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1482424272713   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1482424272724   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1482424272724   addons.manager  DEBUG   Provider finished startup: XPIProvider
1482424272724   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1482424272724   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1482424272724   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1482424272724   addons.manager  DEBUG   Starting provider: GMPProvider
1482424272729   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1482424272729   addons.manager  DEBUG   Provider finished startup: GMPProvider
1482424272729   addons.manager  DEBUG   Starting provider: PluginProvider
1482424272729   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1482424272729   addons.manager  DEBUG   Provider finished startup: PluginProvider
1482424272730   addons.manager  DEBUG   Completed startup sequence
1482424273059   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1482424273059   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1482424273059   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1482424273061   DeferredSave.extensions.json    DEBUG   Starting write
1482424273179   DeferredSave.extensions.json    DEBUG   Write succeeded
1482424273179   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
dec. 22, 2016 5:31:13 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1482424273867   addons.xpi      DEBUG   Calling bootstrap method shutdown on loop@mozilla.org version 0.1
dec. 22, 2016 5:31:14 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
java.io.IOException: Invalid suite URL: http://127.0.0.1/OpenGoogle.html
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.verifySuiteUrl(HTMLLauncher.java:200)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:186)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

C:\Temp>

Browser Version:  
Version 45, 64-bit

## Expected Behavior -
Test script should start Firefox and open the page http://www.google.com

## Actual Behavior -

I get this error message:

WARNING: Test of browser failed: *firefox
java.io.IOException: Invalid suite URL: http://127.0.0.1/OpenGoogle.html
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.verifySuiteUrl(HTMLLauncher.java:200)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:186)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

## Steps to reproduce -

1) Create simple test script which opens http://www.google.com
2) Open command line
3) Type the command "java -jar selenium-html-runner-3.0.1.jar..." as shown above.

**Comment by yaxv** [comment]
I have moved over to chromedriver and the C# client so I don't need to use the selenium-html-runner jar anymore. I suppose this case can be closed as "Not Resolved".

**Comment by nammzzi** [comment]
i have the exact same issue on mac. any way to get around it. It just loads forefox and nothing happens

**Comment by mehrad-rafigh** [comment]
Same issue here. I built the testing script with selenium ide and wanted to run the suite with selenium html runner


```
WARNING: Test of browser failed: *firefox
java.io.IOException: Invalid suite URL: http://127.0.0.1:1990/~/Desktop/selenium/Small-Test
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.verifySuiteUrl(HTMLLauncher.java:200)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.determineSuiteUrl(HTMLLauncher.java:186)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:108)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
	at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)
```
