### ISSUE TITLE
Unable to set proxy for Safari and Edge

### ISSUE THREAD

**Issue by rahul6** [SeleniumHQ/selenium#3283]
OS:  
OS X EL Capitan
Browser:  
Safari 10

I am using the below code to set proxy on Edge and Safari but it is not working.
But the same code works for firefox/chrome/IE. Can you please help me this ?
How to set proxy on Edge and Safari using RemoteWebDriver ?

Proxy proxy = new Proxy();
proxy.setAutodetect(false);
proxy.setProxyType(ProxyType.MANUAL);
proxy.setHttpProxy("xxxx:443");
proxy.setFtpProxy("xxxx:443");
proxy.setSslProxy("xxxx:443");
proxy.setSocksProxy("xxxxxx:443");
 
DesiredCapabilities capabilities = DesiredCapabilities.safari();
capabilities.setCapability(CapabilityType.PROXY, proxy);

**Comment by lukeis** [comment]
for safari issues, please log them with apple.
for Edge log them with Microsoft
(links on seleniumhq.org download page)

relevant bit of the spec for them to reference - https://w3c.github.io/webdriver/webdriver-spec.html#proxy

**Comment by nikkosenko** [comment]
I tried to configure Edge Driver with proxy in Java.
My code is as follows:
`BrowserMobProxy proxy = new BrowserMobProxyServer();
proxy.start(0);

Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
DesiredCapabilities capabilities = DesiredCapabilities.edge();
capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

System.setProperty("webdriver.edge.driver", “path_to_Edge_driver”);
WebDriver driver = new EdgeDriver(capabilities);
System.out.println(((EdgeDriver)driver).getCapabilities().toString());
`
I see following in the output without any information for proxy:
Capabilities [{applicationCacheEnabled=true, acceptSslCerts=true, browserVersion=38.14393.1066.0, platformVersion=10, locationContextEnabled=true, webStorageEnabled=true, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]

In the case I use similar code for IE I see output below which contains information for proxy:
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, **proxy={httpProxy=HOSTNAME:62556, proxyType=manual, sslProxy=HOSTNAME:62556}**, nativeEvents=true, ie.ensureCleanSession=true, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:46295/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]

Microsoft marked appropriate issue on their side (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5468949/) as EXTERNAL.
