### ISSUE TITLE
 org.openqa.selenium.UnsupportedCommandException in selenium 3

### ISSUE THREAD

**Issue by Neeraj1610** [SeleniumHQ/selenium#3287]
## Meta -
OS:  
Windows 10
Selenium Version:  
3
Browser:  
Firefox 50.1.0

Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Any issue logged here for Firefox 48 or later will be closed as a duplicate of
#2559. Our recommendation is to switch to GeckoDriver, or to continue testing
on Firefox 45 until GeckoDriver is a viable option for you. If you are
interested in helping us to sign the add-on to restore support for later
Firefox versions, please see the following comment for what's needed:
https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  

## Actual Behavior -
Getting this exception:
Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/850091ec-1f85-4f72-a939-3f36d478499b/click did not match a known command
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'Salvatore-PC', ip: '192.168.0.107', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], prefs={}}, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=300, browserVersion=50.1.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 850091ec-1f85-4f72-a939-3f36d478499b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteMouse.click(RemoteMouse.java:59)
	at org.openqa.selenium.interactions.ClickAction.perform(ClickAction.java:37)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at com.se.MouseEvent.main(MouseEvent.java:26)

## Steps to reproduce -
Below is my code:

package com.se;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;

public class MouseEvent {

	public static void main(String[] args) {
		System.setProperty("webdriver.gecko.driver","C:\\Users\\Salvatore\\Desktop\\SeleniumT\\geckodriver-v0.11.1-win64\\geckodriver.exe");
		WebDriver driver=new FirefoxDriver();
		
		String baseUrl = "http://newtours.demoaut.com/";
		
		driver.get(baseUrl);
		WebElement link_home=driver.findElement(By.linkText("Home"));
		WebElement td_home=driver.findElement(By.xpath("html/body/div[1]/table/tbody/tr/td[1]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[1]"));
		
		Actions builder=new Actions(driver);
		
		Action moveOverHome=builder.click().moveToElement(link_home).build();
		
		String bgColor=td_home.getCssValue("background-color");
		System.out.println("Before hover : "+bgColor);
		moveOverHome.perform();
		bgColor=td_home.getCssValue("background-color");
		System.out.println("After hover : "+bgColor);
		driver.quit();
	}
}

**Comment by lukeis** [comment]
Actions class only recently has been implemented in geckodriver and requires a re-write of Selenium's client code in order to use it. Please follow issue #2611 marking this one as a duplicate. A future release of selenium will have the fix

**Comment by mukulsehra** [comment]
@lukeis : I am getting this issue on Safari-10.0.3, MAC OS X Sierra(v10.12.3) using selenium v3.0.1 (during **sendKeys()** and other interactions.) I am not using the Actions class in my code.
The browser opens and navigates to the URL but after that nothing happens on the screen but the tests get passed as per the testNG report. And the following exception appears in the console.
Here's the stack trace : 
**org.openqa.selenium.UnsupportedCommandException** : Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'admin', ip: '----', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12602.4.8, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: B8A966BA-6E7A-4D43-80BF-7CE9F8489DBF

**Invoked the driver instance using the capibilities mentioned in google group** : https://groups.google.com/forum/#!topic/selenium-users/xEGcK92rzVg


Even I have tried the **Safari Technology preview** and getting the following exception : 

org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:33406 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'admin', ip: '----', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
Driver info: driver.version: InitializeWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:53)


Please help me out.
Thanks!

**Comment by CrisAce** [comment]
I'm getting the same issue with MacOS X Sierra, Firefox 48.0, Selenium WebDriver 3.0.0 Beta, please share any opinion.

Thanks!

**Comment by VladyslavLopatynskyi** [comment]
Hi!
I'm having the same issue, but with a different version of firefox and type of action
POST /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXf05dec7c/moveto did not match a known command (WARNING: The server did not provide any stacktrace information).
MacOs 10.12, firefox 52.0, selenium 3.3.1, marionette 0.15

But it works with firefox legacy support passing to webdriver, by that case marionette driver has not been used.

**Comment by titudatta11370** [comment]
Same issue (org.openqa.selenium.UnsupportedCommandException: POST /session/27674581-31d1-b243-a776-c2107237ed0a/window/rect did not match a known command) my test cases works on PhantomJS or Chrome but having issues with FireFox

**Comment by twistedpair** [comment]
Same problem on 

* Debian Stretch `9`
* Firefox `58.0.2`
* geckodriver `0.19.1`

Event when logging capability level is set to `OFF`.
