### ISSUE TITLE
SeleniumIDE2.9.1_UnexpectedError_WindowsIsNull

### ISSUE THREAD

**Issue by vsureshk30** [SeleniumHQ/selenium#3288]
## Meta -
 Windows 10
Selenium Version:  2.9.1
Browser:  Firefox

I have downloaded selenium IDE. Whenever I am running test case using IDE Getting unexpected error : windows is null. attaching screenshot for the same.

However whenever i click on report issue option from Help - able to run test case
[SeleniumIde.docx](https://github.com/SeleniumHQ/selenium/files/671852/SeleniumIde.docx)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
