### ISSUE TITLE
Error Selenium directory

### ISSUE THREAD

**Issue by purgoufr** [SeleniumHQ/selenium#3290]
The code I write is as follows
`from selenium import webdriver`
`browser = webdriver.Firefox()`
`browser.get('http://inventwithpython.com')`
`linkElem = browser.find_element_by_link_text('Read It Online')`
`type(linkElem)`
`linkElem.click()`

The result of the console is as follows;

Traceback (most recent call last):
  File "C:\Users\Purgoufr\Documents\Eclipse Projects\Python\Web_Scraping\Control_browser_with_Selenium.py", line 50, in <module>
    from selenium import webdriver
  File "C:\Python27\lib\selenium\webdriver\__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "C:\Python27\lib\selenium\webdriver\firefox\webdriver.py", line 34, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "C:\Python27\lib\selenium\webdriver\remote\webdriver.py", line 25, in <module>
    from .webelement import WebElement
  File "C:\Python27\lib\selenium\webdriver\remote\webelement.py", line 40, in <module>
    getAttribute_js = pkgutil.get_data(__package__, 'getAttribute.js').decode('utf8')
  File "C:\Python27\lib\pkgutil.py", line 591, in get_data
    return loader.get_data(resource_name)
  File "C:\Python27\lib\pkgutil.py", line 255, in get_data
    return open(pathname, "rb").read()
IOError: [Errno 2] No such file or directory: 'C:\\Python27\\lib\\selenium\\webdriver\\remote\\getAttribute.js'

I could not find the 'C:\\Python27\\lib\\selenium\\webdriver\\remote\\getAttribute.js'
Do you have any suggestions?

**Comment by aneeshchandy** [comment]
I am not seeing this issue on Mac. Maybe an installation issue?

**Comment by purgoufr** [comment]
I ran other scripts and did not encounter any problems. I do not think it will be a problem of installation.

**Comment by lmtierney** [comment]
How did you install selenium? It doesn't appear that you did it via `pip`

**Comment by lmtierney** [comment]
`getAttribute.js` should be available as long as you used the installation instructions [as shown here](https://github.com/SeleniumHQ/selenium/tree/master/py#installing)

**Comment by purgoufr** [comment]
I used two way. Firstly I run pip install selenium but problem did not change. Then I removed selenium from Python and I copied selenium(not all folder just selenium folder which has common, webdriver,__init__.py file inside) folder and paste into Python library directly. So Python saw selenium function and I could built code. But again I took same error

**Comment by lmtierney** [comment]
If you installed with `pip` then you would not have had the problem. You must not have been trying to use the pip installed version of selenium. Just copying the python folder from this repo will absolutely cause the issue you're seeing

**Comment by aneeshchandy** [comment]
As @lmtierney said, try with pip. Check if setup.py ran successfully. If possible, could you also paste the response after running pip.

**Comment by purgoufr** [comment]
Command prompt like this;

> C:\Users\Purgoufr\AppData\Local\Programs\Python\Python35-32>python -m pip install selenium
> Collecting selenium
>  Using cached selenium-3.0.2-py2.py3-none-any.whl
> Installing collected packages: selenium
> Successfully installed selenium-3.0.2

Python code in Eclipse like this;
![python2](https://cloud.githubusercontent.com/assets/12126559/22609033/24e9a408-ea68-11e6-9c07-afae1271982f.JPG)

**Comment by lmtierney** [comment]
It's still using the one you manually extracted from selenium/py. You need to delete that out.

What does this show you:

    pip show selenium

**Comment by lmtierney** [comment]
Sounds like your eclipse isn't using the correct python version. Do you have multiple installed on your system?

Try using python from the command line

```
python
>>> from selenium import webdriver
```

If that works, it's eclipse at fault

**Comment by purgoufr** [comment]
Yes I have Python27 and Python35 on my eclipse but I prefer python35
![python6](https://cloud.githubusercontent.com/assets/12126559/22610864/41f5508a-ea70-11e6-87c9-0c9ef0ebf167.JPG)

I tried command and result like;
![python5](https://cloud.githubusercontent.com/assets/12126559/22610873/5333a73e-ea70-11e6-9898-69db5f9a56ed.JPG)

**Comment by lmtierney** [comment]
Right, so it's working correctly there, but you need to get geckodriver for
Firefox. See github.com/mozilla/geckodriver

This issue should be closed as it is not a selenium issue, if you require
further assistance please use the selenium users mailing list or the
#selenium channel on freenode
