### ISSUE TITLE
Grid Hub and Nodes stops after a node is turned off or cable unplugged

### ISSUE THREAD

**Issue by eliasnogueira** [SeleniumHQ/selenium#3300]
This issue is a duplication of one opened in appium
https://github.com/appium/appium/issues/6360#issuecomment-269289130

Hello guys!

I facing a problem that I presume could be a bug.
I have a lot of devices in a grid (12), but it occurs with two or more devices.

**Configs (for testing propouse)**
- Selenium/Appium grid with a hub and node in same machine
- Nodes correctly configured (udid, appium post and bp port always unique)

**Scenario**
- Same app executing in parallel through separated threads

**Action**
- After the test execution in the devices I can do two things to throw the error:
- *\* Power off the device
- *\* Unplug the USB cable
- *\* [For emulator] Close the window of emulator

**Versions**
- Selenium Server 2.53.0
- Appium 1.5.1

*_Error *_
_on console (Eclipse)_
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: UiAUtomator shut down unexpectedly (WARNING: The server did not provide any stacktrace information)`

_on node closed_
`Unhandled rejection Error: No device connected, cannot run adb shell command "am force-stop com.eliasnogueira.buttontest"`

_on the other nodes_
`Unhandled rejection Error: Error executing adbExec. Original error: Command '/Users/eliasnogueira/android-sdk/platform-tools/adb -P 5037 -s 192.168.56.102:5555 shell am force-stop com.eliasnogueira.buttontest' exited with code 255{"stdout":"","stderr":"error: device '192.168.56.102:5555' not found\n","code":255}`

**What I expect**
Not stop the Grid after the node stop (shutdown or unplug cable)

Full logs attached.

[console_eclipse.txt](https://github.com/SeleniumHQ/selenium/files/675681/console_eclipse.txt)
[node_closed.txt](https://github.com/SeleniumHQ/selenium/files/675683/node_closed.txt)
[other_nodes.txt](https://github.com/SeleniumHQ/selenium/files/675682/other_nodes.txt)

Any help would be much appreciated! 🙂 
I can help to debug this problem on grid with a little guidance...

Regards!

**Comment by mach6** [comment]
How is the selenium server booted in this issue? I don't see any evidence in the provided information that the selenium server (hub) process is being shutdown unexpectedly.

**Comment by krmahadevan** [comment]
@p0deje - I think we can close off this issue, because it looks like the problem is with the Appium server that plays the role of a selenium node and not with the Selenium standalone which plays the role of a node.

**Comment by p0deje** [comment]
@krmahadevan Thanks!

I also see this issue being inactive, so another reason to close.
