### ISSUE TITLE
PageFactory setup fails when running tests in multiple classes

### ISSUE THREAD

**Issue by SergioLeone** [SeleniumHQ/selenium#3302]
## Meta -
OS:  OSX
Selenium Version:  3.0.1
Browser:  Chrome
Browser Version:  55.0.2883.95 (64-bit)

## Actual Behavior -
I have a PageFactory setup and multiple test classes, i.e.
HomePageTests.class
SearchResultsTests.class
ProductDetailsTests.class
etc.

If I'm running tests in a single class everything is working as expected. However if I include both classes in the same suite in testng.xml file, then first class runs as expected, but when tests switch to second class it fails with NullPointerException. I've tried initializing page factory elements in various ways and places and still can not find a solution to using page factory with multiple test classes. 

## Steps to reproduce -
a sample of the code can be found here:
[pf_example.zip](https://github.com/SeleniumHQ/selenium/files/676685/pf_example.zip)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
