### ISSUE TITLE
Selenium IDE for Firefox does not record values in autoNumeric-managed inputs

### ISSUE THREAD

**Issue by AlexandreBonneau** [SeleniumHQ/selenium#3305]
## System Info
OS:  Linux
Selenium Version:  IDE v2.9.1.1
Browser:  Firefox
Browser Version:  45.6.0 (64-bit)

## Expected Behavior -
Some users have reported that Selenium IDE does not record any inputs when keys are entered into an input managed by autoNumeric.

In the few last comments on this issue https://github.com/BobKnothe/autoNumeric/issues/199, there is a test webpage that shows that bug.

I'm currently running Firefox 45.6.0 and 52.0a2 with Selenium IDE v2.9.1.1, but the bug appears in both version.

## Actual Behavior -
Input values are recorded for plain input, but not when those are managed with autoNumeric.

## Steps to reproduce -
1. Go to http://www.antoniob.com/easyedit/userfiles/autonumeric/index.html
2. Open Selenium IDE
3. Input some text into the *plain* input ; Selenium IDE record the values on `blur`
4. Input some numbers into the *autoNumeric* input ; Selenium IDE does not record the values on `blur`

Since autoNumeric change the `input.value` on-the-fly, how come Selenium does not pick up any value on blur? The `change` event is sent correctly too.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Comment by AlexandreBonneau** [comment]
Well, bummer!
