### ISSUE TITLE
Selenium-webdriver #enabled? is incorrect for inputs nested in disabled fieldsets

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#3308]
## Meta -
OS:  
OSX
Selenium Version:  
selenium-webdriver 3.0.5
Browser:  
Firefox

Given HTML like

    <fieldset disabled="disabled">
        <input name="form[disabled_fieldset_child]" id="form_disabled_fieldset_child"/>
    </fieldset>

and element referring to the input

Using selenium-webdriver with marionette disabled against Firefox 47 calling 

    element.enabled?  # returns false

Using selenium-webdriver with marionette enabled against Firefox 50.1.0

    element.enabled? # returns true

In both cases the input is disabled in the browser and I would expect `enabled?` to return false

**Comment by lukeis** [comment]
please log issues for geckodriver / marionette with mozilla:

https://github.com/mozilla/geckodriver/issues
