### ISSUE TITLE
Selenium 3.0.2 and Firefox 50.0.1 Still cannot work together?

### ISSUE THREAD

**Issue by teamblubee** [SeleniumHQ/selenium#3310]
## Meta -
OS:  
```FreeBSD 12-CURRENT```
Selenium Version:  
```./geckodriver -V
geckodriver 0.11.1

The source code of this program is available at
https://github.com/mozilla/geckodriver.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

```
me@blubee:~/bin % pip list | grep selenium
selenium (3.0.2)
```

Browser:  
```firefox-50.1.0_4,1    Web browser based on the browser portion of Mozilla```

## Expected Behavior -
launch Firefox, run tests?

## Actual Behavior -
Firefox fails to launch with this error message
```
d = webdriver.Firefox()
```
or
```
>>> caps = DesiredCapabilities.FIREFOX
>>> caps["marionette"] = True
>>> caps["binary"] = "/usr/home/blubee/bin/firefox"
>>> d = webdriver.Firefox(capabilities = caps)
```
both leads to this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blubee/.local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 150, in __init__
    keep_alive=True)
  File "/home/blubee/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/blubee/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/blubee/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/blubee/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
```

I downloaded the geckodriver from github and placed it in my path and I have one of the latest versions of firefox, I still get this error.

## Steps to reproduce -
try to create a firefox webdriver in python.

I've looked at the code, in line 192 of ```.../selenium/webdriver/remote/errorhandler.py``` and I don't see anything too unusual, so I am not sure what to do next.

**Comment by teamblubee** [comment]
I can guarantee that Firefox on my system does work as well as the gecko driver. I can control a firefox instance with these steps

install [Marionette Python](https://marionette-client.readthedocs.io/en/master/) python package, launch firefox ```firefox -marionette``` <-- this command gives you the port

start a python session and import the marionette python module
create a client, point the client to port you got from the firefox call above.

Control the firefox instance through marionette python.

That seems really convoluted though and rewriting tests already tested in selenium would be a real chore.

Is there a sane way to set this up with selenium?

**Comment by teamblubee** [comment]
```python
from marionette_driver.marionette import Marionette
from subprocess32 import call, Popen, PIPE
from random import randint
import os, signal, time

def create_marionette_dir():
    port_number = randint(1000,65535)
    folder_name = "marionette_%d"%(port_number)
    folder_path = "/tmp/%s/"%(folder_name)

    success = False

    while True:
        if success:
            break

        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            success = True
        else:
            continue

    return port_number, folder_name, folder_path

def create_marionette_instance():
    proc_port, folder, path = create_marionette_dir()


    marionette_prefs_path = path+"/prefs.js"
    marionette_prefs_enabled = "user_pref(\"marionette.defaultPrefs.is_enabled\", true);"
    marionette_prefs_port = "user_pref(\"marionette.defaultPrefs.port\", %d);"%(proc_port)
    profile_path = '-profile \"%s\"'%(path)


    with open(marionette_prefs_path, "w") as of:
        of.write(marionette_prefs_enabled)
        of.write("\n")
        of.write(marionette_prefs_port)
    of.close

    nette = Popen(["firefox -marionette -profile \"/tmp/marionette_%d/\" -new-instance"%(proc_port)], stdout=PIPE, stderr=PIPE, shell=True)
    print(nette.pid)
    # stdout, stderr = nette.communicate()
    # print(stdout, stderr)

    client = Marionette("localhost", port=proc_port)
    client.start_session()
    client.switch_to_window(client.window_handles[-1])
    client.close()
    client.switch_to_window(client.window_handles[0])
    return client, nette.pid


if __name__ == "__main__":
    driver, pid = create_marionette_instance()

    driver.navigate("http://google.com")
    sb = driver.find_element("name", "q")
    sb.clear()
    sb.send_keys("this is not a test\n")

    time.sleep(3)
    os.kill(pid, signal.SIGTERM)
```

I have to use kill to end the process because quitting, even on the last window never worked, it throws an Marionette error, close won't close all the windows.

I am not sure what's up with the latest webdriver but I took some time and figured out how to get Firefox working again. The Marionette driver does everything that I need. I would like to keep using selenium but I can't be forced to use Chromedriver when there are massive bugs that will kill a long running process. Leaving a project and have it dying 3 hours in is unacceptable, I haven't had such issues with Firefox.

Chrome/Chromium seems like a burning tire fire. If you guys can implement this back into Selenium I'll continue to use the project, if not I'll migrate my programs to use Marionette.

I bet it would be easier to wrap the Chrome webdriver api inside of this Marionette API.

Hope this contribution helps someone fix the issue.

**Comment by lukeis** [comment]
please log geckodriver issues with mozilla:

https://github.com/mozilla/geckodriver/issues

It would appear the executable is having a problem launching on your machine, so there's little to nothing selenium can do about it. They might discover an issue in the python bindings, but it works on other systems, so there might be something different about your setup and there could be an issue on your platform with geckodriver, so please check with mozilla first.

**Comment by manjeetsinghchahal** [comment]
Try this
System.setProperty("webdriver.gecko.driver", "E:\\Manjeet Testing\\Browser Driver\\geckodriver.exe");
		driver = new FirefoxDriver();
