### ISSUE TITLE
WebDriver cannot click an 'area' element 

### ISSUE THREAD

**Issue by amolkumar-khambe** [SeleniumHQ/selenium#3311]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.44
Browser:  
Chrome

My application have map/area element on the page for setting PIN.
On clicking of map/area image (which contains numbers only 0 to 9) text box is get populated as per number we have clicked. 
But map/area is not get clicking so no entry is going into respective text box.

**Comment by amolkumar-khambe** [comment]
Same issue happens in IE also. IE shows clicking on map/area image but not populating text box with clicked value.

**Comment by AutomatedTester** [comment]
Please can you upgrade to 3.* and try again. If it still doesnt work please can you provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
