### ISSUE TITLE
Unable to do automation on Opera Browser 

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#3312]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.0.1
Browser:  
 Opera 

Browser Version:  
 42.0.2393.94 

Issue:
====
I can launch Opera browser but unable to load the URL before that the opera browser got crashed. Following are my code for the execution and reproduce the issue:

System.setProperty("webdriver.opera.driver", operaChromiumDriver);
		ChromeOptions options = new ChromeOptions();
		options.setBinary(operaBrowserLocation);

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);

		System.out.println(capabilities);

		WebDriver browser = new OperaDriver(capabilities); //Got Crash in this step

		WebDriver driver = browser;
		driver.get("https://in.yahoo.com/");

**Comment by lukeis** [comment]
we don't support OperaDriver here, you can try to log a bug with the Opera:
https://github.com/operasoftware/operachromiumdriver/issues
