### ISSUE TITLE
[SafariDriver] Driver do not switch to window dafault content if a frame in which it was focused closes

### ISSUE THREAD

**Issue by tshkursk** [SeleniumHQ/selenium#3314]
**The issue**: After clicking a link / button in a frame using SafariDriver, it appears there is no switch to parent default content if this frame is closed. As a result those listeners on a click-event fail with NoSuchFrameException. 

**The Solution**: I'd like to have SafariDriver behavior similar to ChromeDriver in where switch to parent default content is performed and onclick-events can use driver in updated state.

OS:  macOS 10.12
Selenium Version:  2.48.0 
Browser:  Safari
Browser Version:  10.0

## Steps to reproduce -
driver.switchTo().frame(frame);
WebElement element = frame.findElements(...).get(0); // clickable element in a frame
element.click(); // click button inside a frame that leads to frame disappearance
driver.getCurrentUrl(); // this can be inside a listener actions

**SafariDriver log**:
Executing: [click: 28 [[SafariDriver: safari on MAC (null)] -> xpath: .//*[normalize-space(@class)='button button-yes']]])
03:58:48.422 INFO - Done: [click: 28 [[SafariDriver: safari on MAC (null)] -> xpath: .//*[normalize-space(@class)='button button-yes']]]
INFO - Executing: [get current url])
WARN - Exception thrown
org.openqa.selenium.NoSuchFrameException: The currently selected frame has been removed from the DOM; you must select another frame/window before continuing (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9 milliseconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=10.0.1, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]

**ChromeDriver log**:
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: RESPONSE FindElements [  ]
[INFO]: COMMAND ClickElement {"id": "0.5348571425056579-1"}
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: RESPONSE ClickElement
[INFO]: COMMAND GetUrl {}
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: Waiting for pending navigations...
[INFO]: Done waiting for pending navigations. Status: ok
[INFO]: RESPONSE GetUrl "http://example.com"

**Comment by lukeis** [comment]
The legacy safari driver is no longer supported, please attempt to use the driver provided by apple included in safari 10. Bugs for the Apple driver should be logged with Apple.
