### ISSUE TITLE
A switch to make  selenium return `None` instead of raising NoSuchElementException?

### ISSUE THREAD

**Issue by eromoe** [SeleniumHQ/selenium#3319]
## Meta -

Selenium Version:  
3.0 (python)

Browser:  
phantomjs

Detail:

I am using selenium as crawler, it would be much more convenient to let
```
driver.find_element_by_xpath('xxxx')
driver.find_element_by_css_selector('xxx')
```
return `None` instead of raising `NoSuchElementException` when nothing found.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lukeis** [comment]
use find_elements instead, it will return an empty list instead of raising an exception
