### ISSUE TITLE
Passwords not being sent

### ISSUE THREAD

**Issue by javixeneize** [SeleniumHQ/selenium#3320]
## Meta -
OS:  
Windows7
Selenium Version:  
2.9.1 IDE
Browser:  
Firefox

Hi

Note that the issue i am having is related to a "unsupported" firefox version, but i dont think the problem is related to the version itself

I have a screen that contains two inputs for passwords with different names. password and code. I have automated the script filling both inputs and clicking on the submit button.

IDE script looks correct, with both passwords populated, and when running it, i can see that both passwords are filled in the screen, but, capturing the request, i can see that only the first password is sent

Browser Version:  
50

## Expected Behavior -
When a screen contains two inputs with passwords, send both passwords in the request
## Actual Behavior -
Only the first password is sent
## Steps to reproduce -
1 - Use a page that contains two password in the same screen
2 - Record the execution, populate both passwords and submit the request
3 - Play the script. Only the first of the two passwords is being sent

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/).

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
