### ISSUE TITLE
Unable to open firefox in Selenium 3.0.1

### ISSUE THREAD

**Issue by aksh003** [SeleniumHQ/selenium#3322]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.0.1
Browser:  
 Firefox 49.0.2

Code:
public static void main(String[] args) throws InterruptedException {
				//Driver to trigger the launch of firefox. Utilized by setting system property
				System.setProperty("webdriver.gecko.driver", "C:\\Program Files\\Java\\Firefox launch Driver\\geckodriver.exe");
		
				// Create a new instance of the Firefox driver
				WebDriver driver = new FirefoxDriver();

		        //Launch the Online Store Website
				driver.get("http://www.store.demoqa.com");

		        // Print a Log In message to the screen
		        System.out.println("Successfully opened the website www.Store.Demoqa.com");
		 
		       
				//Wait for 5 Sec
				Thread.sleep(5);
				
		        // Close the driver
		        driver.quit();
	}

## Expected Behavior -
Should launch firefox
## Actual Behavior -
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
45459975	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1483545459975	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1483545459975	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1483545459976	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1483545459977	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1483545459978	addons.manager	DEBUG	Provider finished startup: XPIProvider
1483545459978	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1483545459979	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1483545459979	addons.manager	DEBUG	Starting provider: GMPProvider
1483545459986	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: GMPProvider
1483545459987	addons.manager	DEBUG	Starting provider: PluginProvider
1483545459987	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: PluginProvider
1483545459987	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545462823	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1483545462824	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1483545462824	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1483545464299	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545464299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1483545464300	DeferredSave.extensions.json	DEBUG	Starting timer
1483545464321	DeferredSave.extensions.json	DEBUG	Starting write
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=2.61125) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545464562	addons.repository	DEBUG	No addons.json found.
1483545464563	DeferredSave.addons.json	DEBUG	Save changes
1483545464566	DeferredSave.addons.json	DEBUG	Starting timer
1483545464827	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1483545464829	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1483545464830	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1483545465029	DeferredSave.addons.json	DEBUG	Starting write
1483545465918	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545466040	DeferredSave.addons.json	DEBUG	Write succeeded
1483545485877	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1483545485878	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1483545485879	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1483545486517	addons.manager	DEBUG	shutdown
1483545486518	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1483545486518	addons.xpi	DEBUG	shutdown
1483545486519	addons.xpi-utils	DEBUG	shutdown
1483545486521	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1483545486522	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1483545486530	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1483545486531	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1483545486535	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1483545486539	addons.xpi	DEBUG	Notifying XPI shutdown observers
1483545486542	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at ownPackage.shoppingSite.main(shoppingSite.java:14)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
45459975	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1483545459975	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1483545459975	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1483545459976	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1483545459977	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1483545459978	addons.manager	DEBUG	Provider finished startup: XPIProvider
1483545459978	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1483545459979	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1483545459979	addons.manager	DEBUG	Starting provider: GMPProvider
1483545459986	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: GMPProvider
1483545459987	addons.manager	DEBUG	Starting provider: PluginProvider
1483545459987	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: PluginProvider
1483545459987	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545462823	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1483545462824	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1483545462824	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1483545464299	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545464299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1483545464300	DeferredSave.extensions.json	DEBUG	Starting timer
1483545464321	DeferredSave.extensions.json	DEBUG	Starting write
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=2.61125) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545464562	addons.repository	DEBUG	No addons.json found.
1483545464563	DeferredSave.addons.json	DEBUG	Save changes
1483545464566	DeferredSave.addons.json	DEBUG	Starting timer
1483545464827	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1483545464829	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1483545464830	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1483545465029	DeferredSave.addons.json	DEBUG	Starting write
1483545465918	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545466040	DeferredSave.addons.json	DEBUG	Write succeeded
1483545485877	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1483545485878	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1483545485879	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1483545486517	addons.manager	DEBUG	shutdown
1483545486518	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1483545486518	addons.xpi	DEBUG	shutdown
1483545486519	addons.xpi-utils	DEBUG	shutdown
1483545486521	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1483545486522	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1483545486530	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1483545486531	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1483545486535	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1483545486539	addons.xpi	DEBUG	Notifying XPI shutdown observers
1483545486542	addons.manager	DEBUG	Async provider shutdown done

Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'DESKTOP-CG3TLHP', ip: '192.168.0.101', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at ownPackage.shoppingSite.main(shoppingSite.java:14)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
45459975	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1483545459975	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1483545459975	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1483545459976	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1483545459977	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1483545459978	addons.manager	DEBUG	Provider finished startup: XPIProvider
1483545459978	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1483545459978	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1483545459979	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1483545459979	addons.manager	DEBUG	Starting provider: GMPProvider
1483545459986	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: GMPProvider
1483545459987	addons.manager	DEBUG	Starting provider: PluginProvider
1483545459987	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1483545459987	addons.manager	DEBUG	Provider finished startup: PluginProvider
1483545459987	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545462823	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1483545462824	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1483545462824	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1483545464299	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545464299	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1483545464300	DeferredSave.extensions.json	DEBUG	Starting timer
1483545464321	DeferredSave.extensions.json	DEBUG	Starting write
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0 (t=2.61125) [GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1483545464562	addons.repository	DEBUG	No addons.json found.
1483545464563	DeferredSave.addons.json	DEBUG	Save changes
1483545464566	DeferredSave.addons.json	DEBUG	Starting timer
1483545464827	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1483545464829	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1483545464830	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1483545465029	DeferredSave.addons.json	DEBUG	Starting write
1483545465918	DeferredSave.extensions.json	DEBUG	Write succeeded
1483545466040	DeferredSave.addons.json	DEBUG	Write succeeded
1483545485877	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.3
1483545485878	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.4
1483545485879	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1483545486517	addons.manager	DEBUG	shutdown
1483545486518	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1483545486518	addons.xpi	DEBUG	shutdown
1483545486519	addons.xpi-utils	DEBUG	shutdown
1483545486521	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1483545486522	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1483545486530	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1483545486531	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1483545486535	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1483545486539	addons.xpi	DEBUG	Notifying XPI shutdown observers
1483545486542	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	... 8 more

**Comment by lukeis** [comment]
the stacktrace shows that the code is attempting to launch the old firefox webdriver xpi instead of using marionette / geckodriver.

Are you setting the system property webdriver.firefox.marionette = true ? Or specifying the DesiredCapability marionette = true?

Please follow up with questions / support on https://groups.google.com/forum/#!forum/selenium-users
