### ISSUE TITLE
ClickAndHold not Holding when followed by MoveByOffset or MoveToElement

### ISSUE THREAD

**Issue by KthProg** [SeleniumHQ/selenium#3323]
## Meta -
OS:  
Windows 7

Selenium Version:  
Version: 3.0.0.0
Runtime Version: v4.0.30319
Visual Studio 2013

Browser:  
Google Chrome

Browser Version:  
55.0.2883.87 m

## Expected Behavior -
ClickAndHold sets e.which to 1 on successive mouse events, until Release() is called.

## Actual Behavior -
e.which is set to 1 during the mousedown event, but is no longer 1 once the mousemove event is called.

## Steps to reproduce -
Create the following IAction and Perform() on any element:
```
string driverFolder = "folder/here";
IWebDriver driver = new OpenQA.Selenium.Chrome.ChromeDriver(driverFolder);
driver.Navigate().GoToUrl("http://www.google.com");
Actions builder = new Action(driver);
IWebElement body = driver.FindElement(By.TagName("body"));
IAction dragBottomCorner = builder
    .MoveToElement(body, body.Size.Width - 5, body.Size.Height - 5) // included this because it's part of my original code
    .ClickAndHold()
    .MoveByOffset(-5, -5)
    .Release()
    .Build();
dragBottomCorner.Perform();
```

You'll also have to attach events to mousedown and mousemove and log e.which to verify that it is being unset when the mouse moves after being set correctly during mouse down.

Here's the Chrome console output for that (each line is event + e.which):
mousemove 0
mousedown 1
mousemove 0
mouseup 1

The flag appears to always get cleared in mousemove. Maybe this is Chrome behavior, but when using the app myself, e.which is 1 while the mouse is moving.

**Comment by rickwebiii** [comment]
Ran into this same issue, but with e.buttons. I would expect e.buttons to be 1 as well.

**Comment by KardoseR** [comment]
Still not fixed, jesus christ

**Comment by jimevans** [comment]
@KardoseR I understand the frustration, but the language bindings have no control over the event objects generated by the browser. The language bindings (in modern browsers and drivers, anyway) the browser behavior for actions is determined entirely by the driver, which, in the case of Chrome, is created and maintained by the Chromium team. It’s likely this issue should be raised with them instead of expressing that frustration here, where nothing can be done about it.

**Comment by diemol** [comment]
Hi @KthProg @KardoseR
Is this issue still actual with the most recent versions of the different components (browser, driver, language bindings)?
As mentioned in the previous comment, have you raised the issue in the ChromeDriver repo?

**Comment by AutomatedTester** [comment]
closing as no reply and appears to be a bug in Chrome
