### ISSUE TITLE
Cooke import error when using phantomjs

### ISSUE THREAD

**Issue by joaqo** [SeleniumHQ/selenium#3325]
# Meta

OS:
MacOS Sierra
Selenium Version:
3.0.1
Browser:
Phantomjs version 2.1.1
Languague:
Python 2.7

# Expected Behavior

I should be able to import cookies exported from the driver without having to reformat them.

# Actual Behavior

If I dont make sure the `domain` of the cookie starts with a `.` i get the following error:
`WebDriverException: Message: {"errorMessage":"Unable to set Cookie", ...`
I only get this error when using phantomjs, chrome driver works perfectly.

# Steps to reproduce
```
    for cookie in driver.get_cookies():    
        driver.add_cookie(cookie)
```

# Hacky Solution
```
    for cookie in driver.get_cookies():
                # phantomjs cookies need to be prepended by a '.' for some strange reason
                if cookie['domain'][0] != '.':
                    cookie['domain'] = '.' + cookie['domain']
                driver.add_cookie(cookie)
```

**Comment by lukeis** [comment]
please log phantomjs driver issues with the ghostdriver project:
https://github.com/detro/ghostdriver
