### ISSUE TITLE
Select API not working with GeckoDriver

### ISSUE THREAD

**Issue by DestinationQA1** [SeleniumHQ/selenium#3329]
OS:  Windows 8
Selenium Version:  Selenium 3.0 standalone jar
Browser:  Firefox Browser
Browser Version:  Firefox ESR 45.3.0
## Steps to reproduce -
System.setProperty("webdriver.gecko.driver","D:\\Selenium\\geckodriver-v0.11.1-win64\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.get("http://facebook.com/");
		WebElement dayDD = driver.findElement(By.id("day"));
		Select Category = new Select(dayDD);
		//Category.selectByIndex(1);
		Category.selectByVisibleText("10");

**Comment by AutomatedTester** [comment]
could you try this with the current released version of Firefox instead of the ESR. I believe this has been fixed but might not be in the ESR.

**Comment by DestinationQA1** [comment]
I tried on latest ESR 45.6.0...not working

**Comment by lukeis** [comment]
GeckoDriver is more suited to be run with the latest releases, which is 50.1.0.  As previously stated, 45 ESR release is not receiving the fixes required here. If you wish to continue to use 45 ESR, I suggest using the Selenium project's FirefoxDriver and not GeckoDriver.

Also, we aren't tracking GeckoDriver issues here, rather they should be logged with mozilla.
