### ISSUE TITLE
Error in importing webdriver in selenium python

### ISSUE THREAD

**Issue by deepas393** [SeleniumHQ/selenium#333]
I have installed pip, selenium sucessfully but when I run python script, I am geeting erro on line "from selenium import webdriver" as ImportError: cannot import name 'webdriver'.

I recently started working on selenium python.

could you please help in resolving this issue?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the selenium user group [1]

[1] https://groups.google.com/forum/#!forum/selenium-users
