### ISSUE TITLE
Save downloads to shared storage

### ISSUE THREAD

**Issue by liornaar** [SeleniumHQ/selenium#3334]
## Meta -
OS:  
 Windows 7
Selenium Version:  
 2.53.1, IDE, etc
Browser:  
 Chrome
------------------------
Hello, 
I'm using Selenium Grid and been trying to download some files from different websites, zipping them and uploading to S3.. I was trying to understand how this can be possible since the hub sends the selenium tasks to a node where I don't have control over.

I've encountered this Issue: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5886

and on comment #5 the author of the comment writes: 
"Another option would be to save donwloads to some shared storage (NFS, S3, what have
you)." 

I've tried to search about saving the download to an S3 storage but with no luck of finding any refrences.. 
Any ideas?

Thanks.

**Comment by cgoldberg** [comment]
> I was trying to understand how this can be possible since 
> the hub sends the selenium tasks to a node where I don't have control over.

I'm not sure what you mean by "I don't have control over".  You are writing these tasks yourself, so they can do anything you want... including uploading saved assets to S3 buckets.

**Comment by liornaar** [comment]
I'm using selenium grid and when starting a task , a node runs on a remote server so when I download a file with chrome browser it downloads it locally to the node server but the code that doesn't use Selenium runs in a different server.. do you understand?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
