### ISSUE TITLE
If an input is disabled, WebElement.sendKeys() should throw InvalidElementStateException

### ISSUE THREAD

**Issue by h-rueda** [SeleniumHQ/selenium#3335]
## Meta -
OS: 

Selenium Version:  3.0.1

Browser:  Firefox

Browser Version:  50.1.0

## Steps to reproduce -

I have this form with **all its input elements disabled** :

```
<form id="form_1a" action="http://example.com">
Your name
  <input type="text" name="name" disabled>
  <input type="button" name="button" value="Click" disabled>
</form>
```

I have an EventListener class that implements WebDriverEventListener

```
public class EventListener implements WebDriverEventListener {
	public void onException(Throwable error, WebDriver driver) {
		if(error instanceof InvalidElementStateException)
			System.err.println("I've got an exception");
	}
}
```
 
I register my listener to my webdriver wrapped in an EventFiringWebDriver instance :

```
EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);
EventListener listener = new EventListener();
eventDriver.register(listener);
```

In my test script I have :

```
WebElement element;

element = eventDriver.findElement(By.name("name"));
element.sendKeys("xxxxx");

element = eventDriver.findElement(By.name("button"));
element.click();
```

## Expected Behavior -
Since both elements are disabled, I should get this message **twice** :
`I've got an exception`

## Actual Behavior -
I get the message only **once**. I get it when I try to click the disabled button.

The WebElement.click() method throws InvalidElementStateException. **(OK)**
The WebElement.sendKeys() method doesn't throw any exception. **(BUG)**

WebElement.sendKeys() should throw an exception if the element is disabled.

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by h-rueda** [comment]
Why is this a GeckoDriver issue ?

**Comment by barancev** [comment]
Because geckodriver should throw the exception. Selenium client library just propagates it.

**Comment by h-rueda** [comment]
I submitted the following GeckoDriver and ChromeDriver issues : 

https://github.com/mozilla/geckodriver/issues/912
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1963

Thank you
