### ISSUE TITLE
PhantomJS no longer works with standalone (on master)

### ISSUE THREAD

**Issue by lmtierney** [SeleniumHQ/selenium#3336]
Commit 3856302 removed a deprecated function that the PhantomJS bindings (stored in https://github.com/SeleniumHQ/selenium/tree/master/third_party/java/phantomjs-driver) rely on ([seen here](https://github.com/codeborne/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriverService.java#L232)).

I know this would probably be an issue for the ghostdriver project to handle themselves (now https://github.com/codeborne/ghostdriver), but I wanted to raise this issue since the binding are actually stored in the project

**Comment by barancev** [comment]
new ExecutableFinder().find("xxx") is a replacement for the removed deprecated static method

**Comment by lmtierney** [comment]
I understand that but who is going to update that? Do we wait for ghost driver to fix it and then pull in the new release to the repo?

**Comment by lmtierney** [comment]
Nevermind :)

**Comment by lmtierney** [comment]
For reference: https://github.com/codeborne/ghostdriver/pull/3
