### ISSUE TITLE
Server not returning JavascriptError for bad script

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#3337]
## Meta -
OS:  Mac OS
Selenium Version:  master
Browser:  Firefox
Browser Version:  53
Geckodriver 0.13.0

## Expected Behavior -
JavascriptError

## Actual Behavior -
Net::ReadTimeout (W3C return call never made)

## Steps to reproduce -
Part of Ruby specs:
https://gist.github.com/titusfortner/1f183432f72ba475756164ad7033e277

This works directly with geckodriver & legacy firefox driver, but gives the linked to error when going through standalone server. It was working the last time I did a full round of tests (a couple months ago).

Getting the same thing with `execute_async | {"script":"return 1 + 2;","args":[]}`

**Comment by barancev** [comment]
Is this issue still actual in geckodriver 0.18?

**Comment by barancev** [comment]
Let's suppose it's fixed.
