### ISSUE TITLE
Errors when element not present

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#3338]
## Meta -
OS:  Mac OS Sierra
Selenium Version:  Master
Browser:  Firefox / Chrome / PhantomJS

## Expected Behavior -
Return NoSuchElementError

## Actual Behavior -
Net::ReadTimeout (W3C Command never returned from server)

## Steps to reproduce -
`driver.find_element(id: 'nonexistant')`

Debug Info:
https://gist.github.com/titusfortner/dd28a3aa67c13b7b0dcb85b018565c66

**Comment by faizrr** [comment]
Any news? Got stuck into the same problem :(

**Comment by p0deje** [comment]
Cannot reproduce on latest master and GeckoDriver.
