### ISSUE TITLE
Getting Current Window when closed

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#3339]
## Meta -
OS:  MacOS Sierra
Selenium Version:  Master
Browser:  Firefox / Chrome

## Expected Behavior -
NoSuchWindowError

## Actual Behavior -
Net::ReadTimeout (No command returned)

## Steps to reproduce -
Open a second window, 
close the first window, 
call current window

https://gist.github.com/titusfortner/7d94e9a6fc0990673eb44ed4f83f4952

This works going directly to geckodriver, but not via standalone server

**Comment by titusfortner** [comment]
On Linux this is failing by returning `Selenium::WebDriver::Error::UnknownError: browser is undefined` --> https://travis-ci.org/SeleniumHQ/selenium/jobs/190181817

**Comment by p0deje** [comment]
The specs guarded with this issue now pass both locally and on CI, so I guess it somehow got fixed.
