### ISSUE TITLE
Add-ons page is breaking

### ISSUE THREAD

**Issue by savi-savanth** [SeleniumHQ/selenium#3342]
## Meta -
OS:  Windows 

Selenium Version:  https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/

Browser:  Chrome, Firefox

Browser Version:  

## Steps to reproduce -
1. Enter http://www.seleniumhq.org/
2. Click on Download
3. Click on Add-ons Download link
4. Observe the page

**Comment by lmtierney** [comment]
Site issues should be filed here https://github.com/SeleniumHQ/www.seleniumhq.org
