### ISSUE TITLE
Ruby bindings set matching capabilities to "any" when spealing to WebDriver conforming remotes

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#3345]
As can be seen from https://github.com/mozilla/geckodriver/issues/420#issuecomment-271284607, the Ruby bindings appear to set the capabilities that are _matched upon_, `browserName`, `browserVersion`, `platformName`, and `platformVersion` to "any". This is not conforming to the WebDriver specification and will as of https://bugzilla.mozilla.org/show_bug.cgi?id=1326534 fail to create a session when speaking to Firefox.

The matching capabilities should either be _left out completely_ (not defined), set to null, "*" (match anything), or the exact value the driver is providing.

Cc @titusfortner

**Comment by titusfortner** [comment]
I vote that the spec should be changed not the bindings.

**Comment by AutomatedTester** [comment]
The specification should really add in `any` as a valid item to go with `*`

**Comment by lmtierney** [comment]
closed with bda48e9 and ac31f00
