### ISSUE TITLE
Firefox 50.1.0 not able to launch with gecko driver (v0.11, .12, .13) in jenkins slave machine (run as windows service). 

### ISSUE THREAD

**Issue by srini20483** [SeleniumHQ/selenium#3349]
Firefox - 50.1.0
gecko driver - v0.11, 12, 13 (tried all the versions)
slave machine - windows server 2012 R2 standard
selenium - 3.0.1

**Note: when i connect the slave through command line it is working fine.** 

Error Message:

1484070019747	geckodriver	INFO	Listening on 127.0.0.1:40311
[INFO] Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1484070020162	mozprofile::profile	INFO	Using profile path C:\Windows\TEMP\rust_mozprofile.bcrUIqN6b6XS
1484070020200	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1484070020243	geckodriver::marionette	INFO	Connecting to Marionette on localhost:57820
1484070021354	Marionette	INFO	Listening on port 57820

###!!! [Parent][MessageChannel] Error: (msgtype=0x2E007D,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

JavaScript error: resource://app/modules/ContentCrashHandlers.jsm, line 75: TypeError: browser.permanentKey is not a non-null object

###!!! [Parent][MessageChannel] Error: (msgtype=0x2E007D,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

**Comment by maartenkuijpers** [comment]
Hi srini20483, I've got the same (or very similar) problem here using TeamCity instead of Jenkins. In our server setup we're using 32bits Firefox. On my local machine (also 32 bits Firefox) I cannot reproduce this. Hoping for a solution.

**Comment by AutomatedTester** [comment]
are you running anything as a service here related to teamcity/jenkins that the job could be running in that service user? 

It looks like the browser is failing to create the initial tab.

Also, this is an extremely poor bug as there is not much here to help us recreate the issue.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by tommywo** [comment]
@srini20483 @maartenkuijpers  try checking 'Allow service to interact with desktop' in service properties. You might need to set registry key HKLM\SYSTEM\CurrentControlSet\Control\Windows\NoInteractiveServices to 0

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by srini20483** [comment]
@tommywo if we used 'Allow service to interact with desktop' in service properties, it is working fine. 
thanks for the quick response.
