### ISSUE TITLE
java changelog is not available

### ISSUE THREAD

**Issue by dr29bart** [SeleniumHQ/selenium#335]
The changelog link for the java 2.45.0 release on the http://www.seleniumhq.org/download/ page leads to 404 page

**Comment by ddavison** [comment]
links work for me.. which link in particular are you talking about?  the one that says `CHANGELOG` links to the proper page for me

**Comment by andreastt** [comment]
Thanks, fixed in https://github.com/SeleniumHQ/www.seleniumhq.org/commit/e09a896ab4a3e7d6764dbb69bebbc60caf5a8773.
