### ISSUE TITLE
Send Keys not working on IE 11

### ISSUE THREAD

**Issue by Prudwi** [SeleniumHQ/selenium#3353]
## Meta -
OS:  Windows 10

Selenium Version:  2.53.1

Browser:  Internet Explorer

Browser Version:  11.576

## Steps to reproduce -Text area HTML code: 

"<textarea name="sr_essm_info_survey_comments_2" maxlength="500" rows="10" cols="50" onfocus="this.select()">automation</textarea>"

**Comment by LinuxSuRen** [comment]
select()这个函数做了什么操作呢？

**Comment by ddavison** [comment]
@LinuxSuRen `this.select()` selects all text within the field ([see an example](https://jsfiddle.net/caLwp134/)).

@Prudwi could you please share code that you are attempting to use?  we cannot help you if we cannot see the code you are using.

**Comment by Prudwi** [comment]
@ddavison 
Below is the code for  sendkeys in selenium:
checkWorkFlow = CommonFunctionsUUIv2.clickMyTasksOrAvailbleTasks(getDriver(), TasksPageLocators.tasks,
				"Available Tasks", wait);
		if (checkWorkFlow == false) {
			UUIv2WebDriver_Utill.print(getDriver(), "clicking available tasks failed", "Fail");
			Assert.fail("clicking available tasks failed");
		}
		checkWorkFlow = CommonFunctionsUUIv2.acquireTask(getDriver(), check.get(0), "Review Facilities", wait, 2);
		if (checkWorkFlow == false) {
			UUIv2WebDriver_Utill.print(getDriver(), "acquire task Failed", "Fail");
			Assert.fail("Acquire Task Failed");
		}

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
