### ISSUE TITLE
after set chrome deviceName, width height of the chrome did not show correctly

### ISSUE THREAD

**Issue by claudiax1101** [SeleniumHQ/selenium#3354]
## Meta -
OS:  
OSX：10.21.1

Selenium Version: 
 selenium-webdriver:3.10.3
 selenium-server-standalone-3.0.1.jar

Browser:  
chrome

Browser Version:  
chrome   55.0.2883.95 (64-bit)

## Expected Behavior -
open browser，show testurl，width and height match Apple iPhone 5 like in dev tools

## Actual Behavior -
open browser，show testurl，but width and height did match Apple iPhone 5 like in dev tools

## Steps to reproduce -

    var testUrl = "http://www.baidu.com";
    var webdriver = require('selenium-webdriver'),
         chrome = require('selenium-webdriver/chrome'),
         firefox = require('selenium-webdriver/firefox');

    var driver = new webdriver.Builder()
          .forBrowser('chrome')
          .setChromeOptions(new chrome.Options().setMobileEmulation({
              deviceName: 'Apple iPhone 5'}))
          .build();

    driver.get(testUrl);

**Comment by luke-hill** [comment]
Just as an FYI for Devs, This has been a bit buggy for me for a while (But we don't do much automated testing on mobile now as we have a responsive site were pushing)

For me it was also an iPhone 5, but we were using Selenium-Webdriver `2.53.4` gem on Ruby. Chrome was the latest version of Chrome (Current)

**Comment by claudiax1101** [comment]
@luke-hill  
which  responsive site? Can you give me the address? 
I want to run automated testing of my webview html in chrome under the  mobile emulation mode, but encounter the problem above , do not know how to solve this problem...     thanks~

**Comment by lukeis** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by claudiax1101** [comment]
@lukeis 
ok, thanks~~
