### ISSUE TITLE
Unable to open test case - Getting javascript error: Msg: TypeError: e is null

### ISSUE THREAD

**Issue by saadahmed42** [SeleniumHQ/selenium#3362]
## Meta
OS:

Windows 7 Home Premium

Selenium Version:  

Browser:  

Browser Version:  

Firefox 7.0 (64-bit)

## Actual Behavior - Getting this error.
There was an unexpected error. Msg: TypeError: e is null
Url: chrome://selenium-ide/content/treeView.js, line: 124

## Steps to reproduce -
Navigate to http://newtours.demoaut.com/mercurysignon.php
Create a New Test Case.
Click Record in the Selenium IDE
Type in an invalid user name and password on the website.
Stop Recording
Click on any of the tree items in the Command section.

You will get this JavaScript error.

![image](https://cloud.githubusercontent.com/assets/25123053/21957973/e2c61a2c-da70-11e6-985b-9a9c6781cecf.png)

There was an unexpected error. Msg: TypeError: e is null
Url: chrome://selenium-ide/content/treeView.js, line: 124

I also typed in 'about:config' but I don't see the two extensions mentioned in this post.

https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/8103

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
