### ISSUE TITLE
Firefox hangs longtime/forever in page loading state during execution of selenium tests

### ISSUE THREAD

**Issue by rajimitara** [SeleniumHQ/selenium#3364]
I have couple of selenium test code written in Java (run from cucumber), When I ran the test in jenkins using the firefox 45.0.1 the build gets through several tests and browser just hangs/stuck forever without timeout. It is widely reproducible in Jenkins and firefox hangs at random pages of a application during execution of testcase. Apparently there are no client-server comm problem and the firefox client has received the response and hangs internally before rendering the response.(We have no clues why firefox stays there longtime/forever as log, jstack, ps, server health has no weird behavior).

Issue persists even after changing selenium & firefox versions to avoid compatibility issues.

Jenkins version : 1.629
Selenium version: 2.53.1
OS: Cent-OS 6.5
Browser: Firefox
Browser version: 45.0.1

**Comment by gopij** [comment]
please share us link to same code to reproduce the same issue.

**Comment by rajimitara** [comment]
Thanks for response.
It occurs at very random testcases in a suite and on capturing screenshot from display set in jenkins we see that Firefox hangs longtime/forever in page loading state.

test are written in cucumber in
feature file
stepdefinition file
Page file (following page object model)
Gist of page file : 
    @FindBy(xpath = "//input[@value='Add local user']")
    private WebElement addLocalUser;

    @FindBy(name = "name_name_")
    private WebElement userName;

    @FindBy(name = "password_password_")
    private WebElement userPassword;

    @FindBy(name = "confirmedPassword_confirmedPassword_")
    private WebElement confirmPassword;

    @FindBy(name = "profile_profile_")
    private WebElement selectProfile;

    @FindBy(name = "buttons_ok_")
    private WebElement okButton;

 @Override
    protected URL getURL() throws MalformedURLException {
        return new URL(getRootURL() + "/appendtoURL");
    }

    public void goToUserManagementPage()
    {
        try {
            goToURL(getURL());
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
    }

    public void AddLocalUser(String name, String password, String profile) {
        addLocalUser.click();
        userName.sendKeys(name);
        userPassword.sendKeys(password);
        confirmPassword.sendKeys(password);
        selectDropDownOptionByVisibleText(selectProfile, profile);
        okButton.click();
    }

Please let me know if you need any more details. It would be great to know your predictions on root cause of this issue.

**Comment by cgoldberg** [comment]
that's way too vague for anyone to help with.

here are some tips:
start investigating by enabling verbose logging for webdriver and firefox.  That should give you some clues.  To cut down on the noise and target the issue, you should remove all extraneous code that is not helpful in reproducing (cucumber files, page files, helper functions, etc).  You need a minimal reproducible testcase that demonstrates the issue in isolation.  start with testcases that just contain a single line of code that does a pageload.  If you then can't reproduce the issue, start adding back bits of code and re-running tests until you can isolate it further

hth.

**Comment by rajimitara** [comment]
As you said, I will investigate by enabling verbose logging. 
BTW mentioned issue occurs in firefox only at random tests & reproducible by running with simple testcase. Right now I have a jenkins build thats stuck and from snapshot taken from Display I see that page is still in loading state with a message at bottom of firefox "Transfering data to server". (attaching jstack). 

I'd be glad to hear more from you in finding root cause for this issue. Thanks!.
[jstack.zip](https://github.com/SeleniumHQ/selenium/files/706786/jstack.zip)

**Comment by cgoldberg** [comment]
@rajimitara sorry, this issue tracker is specifically for issues about selenium itself... you haven't given any indication that you have encountered a selenium bug.

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
