### ISSUE TITLE
64 bit IE launched by 32-bit Driver (Documentation)

### ISSUE THREAD

**Issue by ksiv** [SeleniumHQ/selenium#3366]
## Meta -
OS:   Windows 2008 RC2 

Selenium Version:   '3.0.1', revision: '1969d75'
IEDriver 32 bit version 3.0.0.0
 Grid mode

Browser:  IE 11 Latest (autoupdate)
Node capabilities 
  "capabilities":
  [
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }

Browser Version:  11.0.9600.18537

## Expected Behavior -
"If the 32-bit version of IEDriverServer.exe is launched, the 32-bit version of IE will be launched."
as of "https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#internet-explorer-driver"
## Actual Behavior -
64-bit version of IE launched

**Comment by ksiv** [comment]
Localization: 32 bit version won't load in ,my setup, I suspect as in many others as well. 
Loading iexplore.exe from "C:\Program Files (x86)\Internet Explorer" causes system to change it on the fly. And in process tree iexplore exist but with image from 64-bit version. It' might be a good idea to discourage using 32-bit IEWebDriver on 64 bit systems (at least 2008 R2).

Why bother?
Bitness mismatch causes performance issue #3072 to appear.

**Comment by ksiv** [comment]
Take a look at MSDN article 
Understanding Enhanced Protected Mode
https://blogs.msdn.microsoft.com/ieinternals/2012/03/23/understanding-enhanced-protected-mode/

these settings are in charge of Browser bitness.  There is also explained why 64 bit version is run instead of 32 bit.
In a nutshell on 2008 R2 Server with EPM mode on 64 bit version starts. With EPM disabled 32-bit version. One had to place correct version of IEWebDriver into path according to settings are used.
Which version is up and running is simply could be found using Task Manager (path to image or *32suffix).
My previous suggestion "to discourage using 32-bit IEWebDriver " is a bad idea due to compatibility issues but understanding of how to configure IE is desirable or one might find IE too slow.

**Comment by jimevans** [comment]
This is expected and required behavior for IE and the IE driver. You've already linked to the Microsoft blog post explaining IE's architecture. [This blog post](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html) explains the driver's response to that architecture, and why it can't be easily changed.

**Comment by ksiv** [comment]
@jimevans ,  a was complaining on documentation which is misleading. Not implementation - which is ok. :-)
