### ISSUE TITLE
Getting connection refused exception with MarionetteDriver and selenium

### ISSUE THREAD

**Issue by gorv** [SeleniumHQ/selenium#3370]
I am trying to use Firefox with selenium where the I get the GeckoDriver something like this :
 
    String Xport = System.getProperty("lmportal.xvfb.id", ":1");
        final File firefoxPath = new File(System.getProperty("lmportal.deploy.firefox.path", firefoxBinaryPath));
        FirefoxBinary firefoxBinary = new FirefoxBinary();
        firefoxBinary.setEnvironmentProperty("DISPLAY", Xport);
        final int marionettePort = PortProber.findFreePort();
        final int webDriverPort = PortProber.findFreePort();
        GeckoDriverService.Builder builder = new GeckoDriverService.Builder() {
            @Override
            protected ImmutableList<String> createArgs() {
                ImmutableList.Builder<String> argsBuilder = ImmutableList.builder();
                argsBuilder.addAll(super.createArgs());
                argsBuilder.add(String.format("--marionette-port=%d", marionettePort));
                return argsBuilder.build();
            }
        };
        builder.usingPort(webDriverPort);
        builder.usingDriverExecutable(new File(geckoDriverPath));
        GeckoDriverService driverService = builder.build();
        try {
            driverService.start();
        } catch (IOException e) {
            logger.error(e);
        }
        waitUntilReady(webDriverPort, marionettePort, DEFAULT_GECKODRIVER_TIMEOUT);

But when I try to get RemoteWebDriver instance like this :

    try{
        RemoteWebDriver webDriver = new MarionetteDriver(driverService, desiredCapabilities);
    }catch (Exception ex) {
            logger.error("[MOZILLA BROWSER] Killing webdriver port:" + driverService.getWebDriverPort(), ex);
            releasePort(webDriverPort);
        }

 Then intermittently I start getting following error 
            

`org.openqa.selenium.WebDriverException: connection refused (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.57 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-48-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:206)
	at org.openqa.selenium.firefox.MarionetteDriver.run(MarionetteDriver.java:77)
	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:71)
	at org.openqa.selenium.firefox.MarionetteDriver.<init>(MarionetteDriver.java:59)`

I am using below maven dependencies :

    <dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.0-beta1-SNAPSHOT</version>
    </dependency>

For Gecko driver , Firefox and XVFB, the following version : 

    wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
    tar -xvf geckodriver-v0.11.1-linux64.tar.gz
    wget sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_50.0.2-0ubuntu1_amd64.deb
    sudo dpkg -i firefox-mozilla-build_50.0.2-0ubuntu1_amd64.deb
    sudo apt-get install Xvfb firefox
    Xvfb :1 -screen 0 1024x768x24 &
    export DISPLAY=:1 >> ~/.profile

**Comment by gorv** [comment]
Any help on this ?

**Comment by AutomatedTester** [comment]
Please upgrade to the latest selenium/geckodriver, it appears you are using a beta which is very old.  Also has this issue been solved by not using XVFB?

Closing until we get more info.
