### ISSUE TITLE
Session timeout doesn't work with Appium node

### ISSUE THREAD

**Issue by scotthsiao** [SeleniumHQ/selenium#3371]
## Meta -
OS:  
Ubuntu 14.04LTS

Selenium Version:  
selenium-server-standalone-3.0.1.jar

Browser:  
Appium

Browser Version:  
1.5.0

## Expected Behavior -
The test script does not call driver.quit at the end to simulate fault situation.
Selenium server should release the session after Appium client inactivity timeout is reached.
So the next test script can use the webdriver.Remote() again even without property shutdown.

## Actual Behavior -
Selenium server doesn't release the session after Appium client inactivity timeout is reached and keep queuing all request even the test script has been terminated.
The webdriver.Remote() call doesn't report fail or timeout and keep waiting unless user interrupts.

I try to fall back to 2.53.1 then everything works fine as I expected.

## Steps to reproduce -
Grid server: 
```
$ java -jar selenium-server-standalone-2.53.1.jar -role hub
```
Node (same as Grid server):
```
$ appium --session-override --nodeconfig node_zp1.json -p 4726 -bp 2252 --default-capabilities '{"udid":"E4AZCY066429", "fullReset":true}'
```
nodeconfig of node_zp1.json: 
```
{
    "capabilities": [
        {
            "applicationName": "Asus Zenphone",
            "browserName": "Asus Zenphone",
            "platformName": "ANDROID",
            "maxInstances": 1
        }
    ],
    "configuration": {
        "cleanUpCycle": 2000,
        "timeout": 30000,
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "host": "127.0.0.1",
        "port": 4726,
        "maxSession": 1,
        "register": true,
        "registerCycle": 5000,
        "hubPort": 4444,
        "hubHost": "192.168.57.1"
    }
}
```

Test script:
```python
from appium import webdriver
desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.2'
desired_caps['deviceName'] = 'Android' #devInfo['serial']
desired_caps['app'] = '/home/scotthsiao/workspace/selenium/' + devInfo['apk']
desired_caps['applicationName'] = "Asus Zenphone"
print "try to connect to remote"
driver = webdriver.Remote('http://localhost:4444/wd/hub', desired_caps)
print "connected"
```

**Comment by kool79** [comment]
It is an issue with timeout parameter in node config. (see reference above). To get it worked in v3.x you should use "timeout" : 30  (sec). For v2.x you should continue to use 30000 (ms)

Current issue can be closed.

**Comment by barancev** [comment]
Closing in favour of the abovementioned issue.
