### ISSUE TITLE
firefox specified userprofile not being used.

### ISSUE THREAD

**Issue by berdt** [SeleniumHQ/selenium#3373]
OS:  
w10 
Selenium Version:  
3.0.2 - python 3.6
Browser:  
Firefox 50.0
Geckodriver:
0.13

(latest versions as of writing)

```
from selenium import webdriver
profile = webdriver.FirefoxProfile(r'C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\o7nqiq0j.new')

ff = webdriver.Firefox(profile, firefox_binary=r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe")
```

This doesn't load the profile from the directory specified, it will act as if no profile folder has been given. It will act as expected without giving a profile folder, that is, a new userprofile with a random name somewhere in a tmp folder.

**Comment by digiboons** [comment]
Hello there ;

How could you solve this issue ? I have the same problem 

Selenium 3.1.4  
python 3.7
Geckodriver:
0.24
