### ISSUE TITLE
Selenium HTML Runner

### ISSUE THREAD

**Issue by xxcbzxx** [SeleniumHQ/selenium#3376]
## Meta -
OS:  Windows 10 64bit
Selenium Version:  3.0.1   + IDE 2.9.1
Selenium-HTML-Runner-3.0.1.jar
Browser:  Firefox

Issue: Linked to GeckoDriver 
Executed this command via cmd
java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*googlechrome" "https://www.packtpub.com" "C:/Users/DAVID/Desktop/Packt/packt.html" "C:/Users/DAVID/Desktop/Packt/packt-results.html"

Browser Version:  
Firefox 50.1.0

## Actual Behavior -
![image](https://cloud.githubusercontent.com/assets/3828765/22074918/2e5f2736-ddfe-11e6-8d23-53e9c7b8c46a.png)

## Steps to reproduce -
java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*googlechrome" "https://www.packtpub.com" "C:/Users/DAVID/Desktop/Packt/packt.html" "C:/Users/DAVID/Desktop/Packt/packt-results.html"

##Solution?
How to add geckoDriver to the html-runner.

##Alternatives
I've tried to embed the testscript to java, [Link](https://www.youtube.com/watch?v=zylSll8hsPs&t=635s) which returns similar error, is this a known issue? should I go back to 2.51.0?

**Comment by JackoLanternRz** [comment]
I've read this 
[https://github.com/SeleniumHQ/selenium/issues/2706](https://github.com/SeleniumHQ/selenium/issues/2706)

and figure out something with some other questions in this issue
[https://github.com/SeleniumHQ/selenium/issues/3467](https://github.com/SeleniumHQ/selenium/issues/3467)

hope can help you, I've just post my question and now hoping for someone to answer it.

**Comment by asheeshsoni** [comment]
java -Dwebdriver.gecko.driver="path\to\geckodriver.exe" -jar selenium-html-runner-3.4.0.jar -htmlSuite *firefox http://BaseUrl path\to\SeleniumIDE\TestSuite.html path\to\SeleniumIDE\TestOutput.html 

java -Dwebdriver.chrome.driver="path\to\chromedriver.exe" -jar selenium-html-runner-3.4.0.jar -htmlSuite *googlechrome http://BaseUrl path\to\SeleniumIDE\TestSuite.html path\to\SeleniumIDE\TestOutput.html

**Comment by p0deje** [comment]
As suggested in the comments above, you need to pass `-Dwebdriver.gecko.driver` switch.
