### ISSUE TITLE
ChromeDriver not taking full website screenshot (Selenium C#)

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [SeleniumHQ/selenium#3378]
Hello guys!. I'm using the ChromeDriver for Selenium in C# to obtain a full website screenshot. However, I'm only getting what's visible on the browser and not the entire site.
This is the code that I'm using:

IWebDriver driver = new ChromeDriver();
driver.Manage().Window.Maximize();
driver.Navigate().GoToUrl(MAIN_URL);
driver.TakeScreenshot().SaveAsFile(ROOT_FOLDER + "\Screenshots\" + "another-one.png", ImageFormat.Png);
driver.Quit();

Are there any workarounds or third party libraries that help you achieve what I'm actually trying to do?
Thanks, Lucas!.

**Comment by AutomatedTester** [comment]
This is going to be the default from now on as it is becoming increasingly hard to get this information from the browser. You can look for code to do image stitching to get a full page screenshot
