### ISSUE TITLE
FirefoxProfile fails remotely

### ISSUE THREAD

**Issue by rosariomgomez** [SeleniumHQ/selenium#3381]
I believe I'm experiencing this same issue (https://github.com/SeleniumHQ/selenium/issues/2810) with version: 3.0.1.

**Hub and nodes are running on:**
Linux Ubuntu Trusty 14.04 VMs
firefox-47.0.2 (linux-x86_64)

xvfb-run java -Dwebdriver.firefox.bin='firefox/firefox-bin' -jar selenium-server-standalone-3.0.1.jar -role node -hub http://<hub_ip>:4444/grid/register -port 5555 -maxSession 5 -browser browserName=firefox,maxInstances=5,seleniumProtocol=WebDriver

**Client:**
Python selenium bindings 2.53.6

**Python code:**
caps = webdriver.DesiredCapabilities.FIREFOX
caps["marionette"] = False
fp = webdriver.FirefoxProfile()
fp.set_preference("general.useragent.override", "Mozilla/5.0 (iPad; CPU OS 4_3_5 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8L1 Safari/6533.18.5")
driver_ = webdriver.Remote(desired_capabilities=caps, browser_profile=fp, command_executor=hub_ip)
set_browser_size(driver_, 1024, 768)

**Fails in:**
WebDriverException: Message: java.io.IOException: Unable to locate: /org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700' System info: host: '<host>', ip: '<ip>', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-47-generic', java.version: '1.8.0_111' Driver info: driver.version: FirefoxDriver Stacktrace: at org.openqa.selenium.firefox.FirefoxBinary.extractAndCheck (FirefoxBinary.java:169) at org.openqa.selenium.firefox.FirefoxBinary.modifyLinkLibraryPath (FirefoxBinary.java:130) at org.openqa.selenium.firefox.FirefoxBinary.startProfile (FirefoxBinary.java:91) at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start (NewProfileExtensionConnection.java:100) at org.openqa.selenium.firefox.FirefoxDriver.startClient (FirefoxDriver.java:347) at org.openqa.selenium.remote.RemoteWebDriver.<init> (RemoteWebDriver.java:116) at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:259) at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:247) at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:242) at org.openqa.selenium.firefox.FirefoxDriver.<init> (FirefoxDriver.java:135) at sun.reflect.GeneratedConstructorAccessor12.newInstance (None:-1) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance (Constructor.java:423) at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor (FirefoxDriverProvider.java:86) at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance (FirefoxDriverProvider.java:64) at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance (DefaultDriverFactory.java:60) at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:222) at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call (DefaultSession.java:209) at java.util.concurrent.FutureTask.run (FutureTask.java:266) at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176) at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617) at java.lang.Thread.run (Thread.java:745)

**Notes:**
Without specifying a profile, the error is not happening
caps = webdriver.DesiredCapabilities.FIREFOX
caps["marionette"] = False
driver_ = webdriver.Remote(desired_capabilities=caps, command_executor=hub_ip)
set_browser_size(driver_, 1920, 1080)

With the same exact configuration (browser and selenium server versions), but running on MacOS (OS X El Capitan) is also not happening.

Any hint on what the issue might be?

Thanks for helping!

**Comment by lmtierney** [comment]
hi @rosariomgomez can you try this now? I believe this was fixed with `3.2`

**Comment by barancev** [comment]
Let's believe it's fixed as @lmtierney said.
