### ISSUE TITLE
WebElement.getText() does not return the correct value in case of comma separated numbers.

### ISSUE THREAD

**Issue by i12bokay** [SeleniumHQ/selenium#3384]
## Meta -
OS: Windows 10 64-Bit
Selenium Version:  
selenium-remote-driver-3.0.1
Browser:  
Chrome

Browser Version:  
Version 55.0.2883.87 m (64-bit) 

## Expected Behavior -
We have an td html element containing the text 0,29. After finding it via driver.findElement(By.xpath("xpath")) the call of the method  WebElement.getText() should return 0,29 as string.

## Actual Behavior -

The method WebElement.getText() returns 0.29 as string.

## Steps to reproduce -

Try to find any html element containing a number as string (e.g 0,45) with the selenium remote driver. The call of WebElement.getText() will return a number as string separated with dots. Probably because of the internal framework conversion from json to  webElement

**Comment by barancev** [comment]
I've added tests for this case by d28fa64323fc729707fb60b3f55bab7285f1d491
Firefox passes them both locally and remotely.

So it must be related to environment. What's your locale?
