### ISSUE TITLE
Selenium GRID | Nodes with the same name cannot connect on the HUB

### ISSUE THREAD

**Issue by mstankovic86** [SeleniumHQ/selenium#3385]
I have a very big problem with selenium grid after updating to selenium 3.
I have 70+ win10 nodes created from one template (using VMware ESXi) and each of them has the same name 

![screen shot 2017-01-19 at 11 28 25 am](https://cloud.githubusercontent.com/assets/8803779/22103559/e832c504-de3b-11e6-9af5-917cc3eeecc3.png)

they are trying to connect on the HUB, but only ONE is able to connect on the HUB, all others are refused (500 Internal Server Error). I suppose because all have the same ID (computer name)

![screen shot 2017-01-19 at 11 31 07 am](https://cloud.githubusercontent.com/assets/8803779/22103786/c6f42a30-de3c-11e6-9693-d647714a248e.png)

before updating, with selenium 2.53.1, my nodes were able to connect successfully. they are connected with different IDs (IP+port)

![screen shot 2017-01-19 at 11 32 07 am](https://cloud.githubusercontent.com/assets/8803779/22103985/862a594c-de3d-11e6-9142-be1e835e2de5.png)

Please help.

**Comment by mstankovic86** [comment]
also my method for returning IP of node not working anymore 

method is implemented as it is described on https://gist.github.com/danggrianto/4607677

and now my object returning 

`{"msg":"slot found !","success":true,"session":"e8e0b6c4-6b3e-4838-8c7a-38237282c6b1","internalKey":"ad1c6634-32e3-4fb8-812a-f839799441ba","inactivityTime":22,"proxyId":"DESKTOP-RNBF0DD"}`

method fails with the

`<java.net.MalformedURLException: no protocol: DESKTOP-RNBF0DD>`

**Comment by mach6** [comment]
Regarding the same name (`id`) -- Check your node configuration (either the `-nodeConfig` json or the command line used). If you are specifying the same`id` on every node, you will encounter this issue. If you do not specify `id` it will assume the form of `http://{host}:{port}`

**Comment by mach6** [comment]
Note: you can also encounter this issue if your `-nodeConfig` json specifies the same `remoteHost` property on every node. You should not use the `remoteHost` config property in Selenium 3.

**Comment by manoj9788** [comment]
@mach6 do we have this documented anywhere?

**Comment by mach6** [comment]
```shell 
%> java -jar selenium-server-standalone-3.0.1.jar -role node -h
```

```
   -id
       <String> : optional **unique** identifier for the node. Defaults to the url
       of the remoteHost, when not specified.
```

**Comment by mstankovic86** [comment]
thanks a lot, I'll try later today and let you know if works for me.

**Comment by mstankovic86** [comment]
Thanks a lot! This is an issue on the Selenium Grid Extras. I tried to configure grid with selenium-server-standalone-3.0.1.jar and everything works as it is expected. You can close this one.

Thanks again!
