### ISSUE TITLE
WebDriverEventListener beforeScript/afterScript: do not provide args/result

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#3388]
I think the `EventFiringWebDriver` is a nice addition to the support lib but although `beforeScript` and `afterScript` provide the script being executed they do not provide the args or result object being used. Adding these would be very beneficial.

**Comment by diemol** [comment]
Would you like to help us with a PR @mfulton26?

**Comment by mfulton26** [comment]
it's been over 3 years since I reported this issue; I might have had time then but I'm no longer working with Selenium WebDriver at the moment and am busy with other projects so I sadly would not be interested at this time.

**Comment by diemol** [comment]
Fair enough. Apologies for the late reply. 
Since there has not been any more interest on this from other users, I will close it.
