### ISSUE TITLE
Can't run firefox in private mode.

### ISSUE THREAD

**Issue by berdt** [SeleniumHQ/selenium#3390]
OS:
w10
Selenium Version:
3.0.2 - python 3.6
Browser:
Firefox 50.0
Geckodriver:
0.13

Neither using 

```
profile = webdriver.FirefoxProfile()
profile.set_preference("browser.privatebrowsing.autostart", True)
dr = webdriver.Firefox(profile)
```

OR

```
b = FirefoxBinary(r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe")
b.add_command_line_options("-private")
ff = webdriver.Firefox(profile, firefox_binary=r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe")
```

the browser will be running in private mode.

**Comment by davehunt** [comment]
Try this, it worked for me:

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options
o = Options()
o.add_argument('-private')
f = Firefox(firefox_options=o)
```

**Comment by rlora** [comment]
@berdt were you able to achieve this?
I'm experiencing something similar, however when I inspect the properties (`about:config`) private browsing autostart is ON. So the flag seems to be working although FF doesn't seem to be in private mode.

I'm using FF 51, node webdriver 3.1.0, geckodriver 0.14, MacOS Sierra.
In this version a can't add arguments as @davehunt suggests. I can do it for Chrome but the FF Options instance does not have the `addArgument` method. Only `setProfile`, so I guess it has to be done through the profile.

Let me know if you got it working.

Thanks!

**Comment by berdt** [comment]
@rlora I have not tried, decided to downgrade to an earlier version of Firefox and selenium.

**Comment by barancev** [comment]
It should wors as @davehunt suggested. FF Options class definitely has add_argument method:
http://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.options.html#selenium.webdriver.firefox.options.Options.add_argument
