### ISSUE TITLE
Promise??

### ISSUE THREAD

**Issue by jxh150535011** [SeleniumHQ/selenium#3392]
var promise = require('./node_modules/selenium-webdriver/lib/promise.js');
var p1 = promise.Promise.resolve();
p1.then(function() {
console.log('A');
p1.then(() => console.log('B'));
});
p1.then(() => console.log('C'));

may be A C B,but is A B C

promise .fulfilled===promise .Promise .resolve

because code is ::
function fulfilled(opt_value) {
  return ManagedPromise.resolve(opt_value);
}

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html

title:ManagedPromise/A+ Compatibility>>Unhandled Rejection Events

**Comment by jleyba** [comment]
This is working as intended. Read the module docs for a detailed explanation of how the promise manager synchronizes callbacks:

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/promise.html

**Comment by jxh150535011** [comment]
i don't kown :
var p1 = promise.Promise.resolve();//ManagedPromise.resolve()
p1.then(function() {
console.log('A');
p1.then(() => console.log('B'));
});
p1.then(() => console.log('C'));

why? result is :A B C?
but document display results ： A C B

tks~~~~~~ @jleyba
