### ISSUE TITLE
Missing documentation of desiredCapablilites vs. requiredCapablities for RemoteWebDriver

### ISSUE THREAD

**Issue by vinogradoff** [SeleniumHQ/selenium#3395]
Is there any documentation regarding desiredCapabilites vs. requiredCapabilites for RemoteWebDriver (and e.g. FirefoxDriver etc.)?

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java

Please document the difference for parameters and behavior at least in JavaDoc.

**Comment by barancev** [comment]
requiredCapabilites are deprecated
