### ISSUE TITLE
support python asyncio async/await

### ISSUE THREAD

**Issue by graingert** [SeleniumHQ/selenium#3399]

**Comment by graingert** [comment]
provide a promisified/futures version of the Python selenium API.

**Comment by AutomatedTester** [comment]
since Selenium is designed as a blocking API, what benefit do we gain by moving to this model?

**Comment by graingert** [comment]
@AutomatedTester this allows selenium to be mixed in with other async apis, like aiohttp and various database APIs.

Also allows running across multiple browsers in parallel

**Comment by cgoldberg** [comment]
> Also allows running across multiple browsers in parallel

whether or not the python bindings have an async API wouldn't matter for that.

**Comment by graingert** [comment]
@cgoldberg not possible without threading

**Comment by cgoldberg** [comment]
@graingert who said you're not allowed to use threading or multiprocessing with a syncronous API to achieve concurrency?

**Comment by graingert** [comment]
It makes it more difficult

**Comment by mehmetkose** [comment]
you can use run_in_executor method with asyncio

**Comment by graingert** [comment]
Yes, but that's a waste of resources when Selenium could yield whenever it performs io

**Comment by davehunt** [comment]
[arsenic](https://github.com/HDE/arsenic) is a Python client for WebDriver built on asyncio. You may want to consider using or contributing to that project.

**Comment by graingert** [comment]
@davehunt ah glorious

**Comment by lmtierney** [comment]
Closing as there is already a solution for this in [arsenic](https://github.com/HDE/arsenic)
