### ISSUE TITLE
"Error communicating with the remote browser. It may have died." seen in eclipse console on launching Chromedriver: The browser crashes soon after opening without launching the URL

### ISSUE THREAD

**Issue by vikasalva** [SeleniumHQ/selenium#3402]
OS:  Windows 10
Selenium Version:   2.53.1
Browser:  
Chrome 55

Code: 
 {
	
	static WebDriver driver;
	public static void main(String[] args) {
		
		System.setProperty("webdriver.chrome.driver", "D:\\Selenium201\\Drivers\\chromedriver_win32\\chromedriver.exe");
		driver= new ChromeDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		driver.get("https://www.google.com");
		driver.get("https://www.gmail.com/");
		driver.findElement(By.id("gmail-sign-in")).click();
	    driver.findElement(By.id("Email")).clear();
	    driver.findElement(By.id("Email")).sendKeys("emailid");
	    driver.findElement(By.id("Passwd")).clear();
	    driver.findElement(By.id("Passwd")).sendKeys("password_gmail");
	    driver.findElement(By.id("signIn")).click();
	    driver.close();

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
