### ISSUE TITLE
Selenium webdriver hangs trying to get screenshot. 

### ISSUE THREAD

**Issue by Vadim-Kovrizhkin** [SeleniumHQ/selenium#3403]
## Meta -
OS:  Mostly on  OSX
Selenium Version:   2.53.6, 
Browser:  Chrome
Browser Version:  55.0.2883.87 m
ChromeDriver Version 2.27

Webdriver sometimes hangs trying to get a screenshot on AssertionError.
 `driver.save_screenshot(save_path)`

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
