### ISSUE TITLE
Ruby 2 and Selenium IDE 2.9.1 -- exported test cases (unit::testCase) broken for 2 reasons

### ISSUE THREAD

**Issue by Daij-Djan** [SeleniumHQ/selenium#3405]
## Meta -
OS:  
OSX 10.12.2

Selenium Version:  
IDE 2.9.1

Browser:  
Firefox

Ruby 2 and Selenium IDE 2.9.1 -- exported test cases (unit::testCase) broken for 2 reasons:

1. the export file writes the exported class as `class Test`
Test is a keyword and ruby fails to parse it as name ;)
=> FIX: rename it. e.g. SeleniumTest (more descriptive anyway)

2. the exported file still contains the ${receiver} placeholder 
This placeholder should have been replaced with `@driver`
=> FIX: replace ${receiver} with @driver

can we get these fixes in the code so we don't have to manually change it in the generated file? :)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
