### ISSUE TITLE
Crushing with Exception (unknown error)

### ISSUE THREAD

**Issue by noChamp** [SeleniumHQ/selenium#3406]
## Meta -
OS:  
win 7
Browser:  
Chrome Canary

## Expected Behavior -
running selenium without exceptions

## Actual Behavior -
I am getting exception. please see below

## Steps to reproduce -

I have installed latest Chrome Canary and latest ChromeDriver.exe.

I set the ChromeOptions like this:
options.BinaryLocation = @"C:\Users\XXX\AppData\Local\Google\Chrome SxS\Application\chrome.exe";

I have a test written in c# and when running the test using Selenium, I get:

An exception of type 'System.InvalidOperationException' occurred in WebDriver.dll but was not handled in user code

Additional information: unknown error: cannot get automation extension

from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html

  (Session info: chrome=58.0.2990.0)

  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64)

can anyone help?

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
