### ISSUE TITLE
How can i get all the data from datafile in a single call and start using them in testcase

### ISSUE THREAD

**Issue by seema-realforce** [SeleniumHQ/selenium#3407]
How can i load multiple values from dataset for one testcase. I am using ini4j wini to load the test data in testng testcase.
public class CrmTest {
	 WebDriver driver;
	BrowserFactory browser;
	ReadData crmdatafile;
@BeforeClass (alwaysRun=true)
	
	public void setup(ITestContext context) throws Exception{
		
		ClassLoader classLoader = getClass().getClassLoader();
		File file = new File(classLoader.getResource("datafile.txt").getFile());
	
		crmdatafile = new ReadData(file.getAbsolutePath());
              browser = new BrowserFactory(context.getCurrentXmlTest().getParameter("Selenium.browser"));
	
		driver=browser.getNewBrowser();
}
@Test(dependsOnGroups = "login")
  
		public void Contact() {
	  
	  	String title= crmdatafile.data.get("Contact_Buyer", "Title");
		String Contact_language= crmdatafile.data.get("Contact_Buyer", "Contact_language");
		String Visibility= crmdatafile.data.get("Contact_Buyer", "Visibility");
		String Last_name= crmdatafile.data.get("Contact_Buyer", "Last_name");
		String First_name= crmdatafile.data.get("Contact_Buyer", "First_name");
		String Mobile= crmdatafile.data.get("Contact_Buyer", "Mobile");
		String Email= crmdatafile.data.get("Contact_Buyer", "Email");
		String Type= crmdatafile.data.get("Contact_Buyer", "Type");
		String Label= crmdatafile.data.get("Contact_Buyer", "Label");
}
and my datafile looks like 
[Contact_Buyer]
Title = Madam
Contact_language = French
Visibility = Agency
Last_name = Test
First_name = Buyer
Mobile = 54646465454
Email = abc@gmail.com
Type = Buyer
Label = A rénover ok ! Avec nous + architecte.Surtout TRES CALME !!!!!

How can i get all the data from datafile in a single call and start using them in testcase

**Comment by mach6** [comment]
Closing this. This is not a selenium issue. Please as testng question in the appropriate channels.
