### ISSUE TITLE
error: Found argument '-f' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by JMVM** [SeleniumHQ/selenium#3410]
## Meta -
OS:  Windows 7 (64 bits)
Selenium Version:  3.0.1
Browser:  Firefox using GeckoDriver
Browser Version:  Firefox 50.1.0 GeckoDriver 0.13.0

## Expected Behavior -
Opening Firefox browser session as expected

## Actual Behavior -
Error when opening with error trace:

```
error: Found argument '-f' which wasn't expected, or isn't valid in this context


USAGE:
    geckodriver.exe [FLAGS] [OPTIONS]

For more information try --help

```

## Steps to reproduce -
After debugging, it can be reproduced by **geckodriver.exe -foreground**, which is the command executed

**Comment by lmtierney** [comment]
Can you share the code you're using to create this?

**Comment by JMVM** [comment]
With default Firefox capabilities:

```
DesiredCapabilities caps = DesiredCapabilities.firefox();
WebDriver driver = new FirefoxDriver(caps);
```

So when trying to start a connection with **startClient(Capabilities desiredCapabilities, Capabilities requiredCapabilities)**, then geckodriver process is started with profile and assigning flag **foreground**:

`process.startProfile(profile, profileDir, "-foreground");`

So it looks like latest versions for geckodriver are not using that flag anymore, and due to the error.

**Comment by JMVM** [comment]
Probably Selenium is not supporting latest versions of GeckoDriver, and changes in parameters and flags?

**Comment by davidgiga1993** [comment]
I also have this issue. Does anybody know which version of the GeckoDriver still has the `-foreground` flag?

**Comment by JMVM** [comment]
It's not working for me even trying that solution with property **webdriver.gecko.driver**

**Comment by JMVM** [comment]
Please could you modify to launch in **Windows OS case** the next command?

**start geckodriver.exe /F**

With that, it works as expected.

**Comment by AutomatedTester** [comment]
@JMVM 

Somehow you are setting geckoDriver as the firefox binary. I know this works for the majority of users. 

geckodriver is not the binary for firefox, geckodriver controls firefox. I suspect that code snippet you gave is too small for us to meaningfully help you.

**Comment by JMVM** [comment]
Yes, it was my fault.

As old documentation or code from somewhere, I was setting capability **firefox_binary** pointing to **geckodriver.exe**, and that was the problem.

I think it's not very clear compatibility issues in the past about.

Thanks
