### ISSUE TITLE
Executing window.scrollTo may not be firing JS Events.

### ISSUE THREAD

**Issue by jankcat** [SeleniumHQ/selenium#3412]
I apologize in advance if this is not a Selenium issue. I tried with several browsers to be sure it was not a browser-specific issue, and tried the exact same script that I am executing ("window.scrollTo(0,0);") directly through the browser's js consoles to ensure it was not a problem with the site I am trying this out with.

I have googled far and wide, and cannot find a solution. Any help is great!

## Meta -
OS:  Windows 10 - 64 Bit
Selenium Version:  2.53.1, JS SDK
Browser:  Edge, Chrome
Browser Version:  Edge 14/38.14393.0.0, Chrome 55.0.2883.75

## Expected Behavior -
Executing window.scrollTo(0,0); should fire javascript scroll events.
Example:

1. Browse to http://www.infinitiusa.com/suv/qx80/models-specs.html 
2. Scroll near the bottom of the page, so that the header looks as such:
![screen shot 2017-01-25 at 4 45 07 pm](https://cloud.githubusercontent.com/assets/7744158/22314208/aa91e34c-e31d-11e6-8611-ec1fbe190f5b.png)
3. Open the devtools console in your browser
4. Submit the command: window.scrollTo(0,0);
5. Notice you are returned to the top of the page, and it looks as it did when you were originally at the top:
<img width="1375" alt="screen shot 2017-01-25 at 4 29 31 pm" src="https://cloud.githubusercontent.com/assets/7744158/22314502/1915b8ba-e31f-11e6-8ff3-5385782a4ced.png">

The same behaviour is expected when running the following in webdriver:
`driver.executeScript("window.scrollTo(0,0);");`

## Actual Behavior -
Executing window.scrollTo(0,0); may not be firing javascript events. The expected behaviour works when testing directly in the browser (tested on a few browsers), but does not work as expected when running the same tasks through WebDriver.

## Steps to reproduce -
1. Browse to http://www.infinitiusa.com/suv/qx80/models-specs.html 
2. Scroll near the bottom of the page, so that the header looks as such:
![screen shot 2017-01-25 at 4 45 07 pm](https://cloud.githubusercontent.com/assets/7744158/22314208/aa91e34c-e31d-11e6-8611-ec1fbe190f5b.png)
3. Run the folllowing webdriver command: `driver.executeScript("window.scrollTo(0,0);");`
4. Notice you are returned to the top of the page, and the floating elements look funky:
<img width="1324" alt="screen shot 2017-01-25 at 4 28 47 pm" src="https://cloud.githubusercontent.com/assets/7744158/22314447/a86f21e6-e31e-11e6-93fd-9d7dd1e98d72.png">

**Comment by jankcat** [comment]
I must be going crazy. I added the following before doing the scroll to top: `driver.executeScript("window.addEventListener('scroll', function(){alert('scrolling!')});");`

<img width="1413" alt="screen shot 2017-01-25 at 5 26 30 pm" src="https://cloud.githubusercontent.com/assets/7744158/22315361/7818a6fc-e323-11e6-8691-fceb53b690d6.png">

As you can see, the events are still firing. I have no idea why the behaviour would differ when executing scripts in selenium vs executing scripts in chrome/edge directly in the console.

Ideas?

**Comment by hazmeister** [comment]
@jankcat have you tried using the actions class to moveToElement instead of using javascript to push the viewport around?

**Comment by jankcat** [comment]
@hazmeister From what I can see, there is no moveToElement in the JS SDK's actions.

Source: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/actions.js
Docs: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/actions_exports_ActionSequence.html

**Comment by jankcat** [comment]
Strangely, the same issue is present when I use Actions to press the Home button, like so: `driver.actions().sendKeys(webdriver.Key.HOME).perform();`
It also happens when I executeScript `arguments[0].scrollIntoView(false);` with the element set to the top logo on the page.

Once again, all these methods work fine manually in each of these browsers, just not when selenium performs the actions for some reason.

**Comment by jankcat** [comment]
I am at a loss. Even when doing a slow scroll up, as attached below, I am getting the unexpected results:

```
_scrollToTopLoop() {
    let _this = this;
    return _this.driver.executeScript("return window.scrollY;").then(function(yPos) {
      if (yPos <= 0) return Promise.resolve();
      return _this.driver.executeScript("window.scrollBy(0, -100);");
    }).then(function () {
      return _this._scrollToTopLoop();
    });
  }
```

**Comment by jankcat** [comment]
Furthermore, when running the tests locally with Chromedriver and Se2.53.1 (same versions as on node in grid), everything works fine... I am baffled.

**Comment by jankcat** [comment]
This is going to make me sound like a crazy person, but I tried it at like 40 different resolutions and the outcome works as expected a) in all browsers all the time at all resolutions when manually driven or through the dev console. b) in selenium with most resolutions. I found like 6-7 resolutions (listed below) where the actual results above happen.

Note that these resolutions were tested in Chrome (version listed in OP).

I will close the issue, as it is most likely an issue on my end, or maybe some crazy race condition from selenium being able to interact with the page many times faster than me. 

```
    // Broken At (width, outerHeight/innerHeight):
    // 1024, 1160/1086
    // 1190, 1080/1006
    // 1193, 1080/1006
    // 1194, 1081/1007
    // 1195, 1081/1007
    // 1195, 1060/986
    // 1920, 1060/986
    
    // Works At (width, outerHeight/innerHeight):
    // 1024, 1159/1085
    // 1190, 1076/1002
    // 1190, 1077/1003
    // 1190, 1078/1004
    // 1190, 1079/1005
    // 1193, 1079/1005
    // 1194, 1080/1006
    // 1195, 1059/985
    // 1920, 1059/985
```

**Comment by hazmeister** [comment]
@jankcat congrats on getting to the bottom of it!
