### ISSUE TITLE
JSON config default values is handled differently in Grid node compared to hub

### ISSUE THREAD

**Issue by opersson** [SeleniumHQ/selenium#3414]
## Meta -
OS:  Tested on Windows 10 and Linux

Selenium Version:  3.0.1

Browser:  Irrelevant

Browser Version:  -

Starting nodes with JSON config requires all configuration parameters to be present in the JSON file. 
If a parameter is missing the default value will not be used, instead it will be set to null.

This is not the case when running as hub. Then the default value will be used when a configuration parameter is missing from the JSON file.

## Expected Behavior -
Default configuration is used for grid nodes when using JSON config when a configuration parameter is not specified in the JSON file.

## Actual Behavior -
If a configuration parameter is missing from the node JSON config file the configuration parameter will be null.

## Steps to reproduce -
1. Download selenium-server-standalone-3.0.1.jar 
2. Download [DefaultNodeWebDriver.json](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json) 
3. Remove the line '"hub": "http://localhost:4444",' from the json file
4. Start node: "java -jar selenium-server-standalone-3.0.1.jar -role node -nodeConfig DefaultNodeWebDriver.json"
5. The following exception can be seen: 
    org.openqa.grid.common.exception.GridConfigurationException: You must specify either a hubHost or hub parameter

### Example of expected behavior
If something similar is done to the hub it still starts with default values:
1. Download [DefaultHub.json](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultHub.json)
2. Remove the line "port": "4444" from the json file.
3. Start hub: "java -jar selenium-server-standalone-3.0.1.jar -role hub -hubConfig DefaultHub.json"
4. The hub starts on the default port 4444.

**Comment by mach6** [comment]
This should already be fixed with this commit - https://github.com/SeleniumHQ/selenium/commit/705be71ce9ec7e3825cb1633d3da40ab75a8819f

Once the next release happens, the fix will be included.
