### ISSUE TITLE
log into selenium ide, there is code inthe source window 

### ISSUE THREAD

**Issue by jantraver** [SeleniumHQ/selenium#3418]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by jantraver** [comment]
JavaScript error
There was an unexpected error. Msg: TypeError: insertedCommand.line is undefined
Url: chrome://selenium-ide/content/sourceView.js, line: 34, column: 8
SourceView.prototype.rowInserted@chrome://selenium-ide/content/sourceView.js:34:8
Editor.prototype.addCommand@chrome://selenium-ide/content/editor.js:858:5
Editor.prototype.appendWaitForPageToLoad@chrome://selenium-ide/content/editor.js:885:7
Editor.prototype.onUnloadDocument/<@chrome://selenium-ide/content/editor.js:662:5

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
