### ISSUE TITLE
Firefox Bad performance.

### ISSUE THREAD

**Issue by Kurimatzu** [SeleniumHQ/selenium#3419]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.1

Browser:  Firefox

Browser Version:  51

## Steps to reproduce -

List<WebElement> appTwo = driver.findElements(By.className("infinite-list-item infinite-list-item-transition"));

Returns nothing, and also crashes. (It takes a lot to get the information).

I used https://github.com/MachinePublishers/jBrowserDriver, and loads much faster.

This is a bug of firefox?

**Comment by Cicko** [comment]
The problem is the function By.className because it split a string by spaces:

![image](https://cloud.githubusercontent.com/assets/16807198/22358359/54916a66-e436-11e6-973c-4d7b0882f9bb.png)

**Comment by Kurimatzu** [comment]
@Cicko 
I tried to put it this way:

.infinite-list-item.infinite-list-item-transition

However, didn't return anything.

**Comment by Kurimatzu** [comment]
@Cicko 
I used:

List<WebElement> appTwo = driver.findElements(By.cssSelector(replace("infinite-list-item infinite-list-item-transition")));

The secret is to modify the className, cssSelector.

And I also used this method to give replace.

public static String replace (String s) {
		return "." + s.replace(" ", ".");
}
