### ISSUE TITLE
OSS Capabilities not Respected in latest Firefox

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#3420]
## Meta -
Server 3.0.1 
Firefox 54
Geckodriver 0.13.0

## Expected Behavior -
Passing in OSS Desired Capabilities should be translated as necessary into W3C Capabilities to pass to geckodriver

## Actual Behavior -
In Ruby, OSS specific values are being ignored, while W3C values are being passed along correctly
In Java, OSS specific values prevent creating session

## Steps to reproduce -
Ruby & Java:
https://gist.github.com/titusfortner/2d1406aec842260bdd63dc8244b86d06

**Comment by barancev** [comment]
Is this issue still actual?

**Comment by barancev** [comment]
Definitely should be fixed.
