### ISSUE TITLE
Getting elements by className on Firefox only allows class names without spaces #3419

### ISSUE THREAD

**Issue by Cicko** [SeleniumHQ/selenium#3423]
## Meta -
OS:  Ubuntu 16.4

Selenium Version:  v3.8.6

Browser:  Firefox

Browser Version:  

## Expected Behavior -

Problem: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L137

![image](https://cloud.githubusercontent.com/assets/16807198/22358411/d8ea3d42-e436-11e6-87e0-f7a24d2ec190.png)

This function should accept a classname with spaces. 

## Actual Behavior -

the function _By.className_ dont accept spaces on classname. So classnames like ("hello how are you") will fail.

## Steps to reproduce -

I think just removing the split can make it work or making new method.

**Comment by twalpole** [comment]
Class names don't have spaces in them - `<div>class="hello how are you"</div>` is a div with 4 different class names.  The code you showed would break "hello how are you" into a CSS selector of `.hello.how.are.you`  which would match the previous element and also match an element with `class="hello how are you today"` or `class="you are how hello"`

**Comment by Cicko** [comment]
Well, the element I want is there:

![image](https://cloud.githubusercontent.com/assets/16807198/22372744/4aecc090-e496-11e6-896f-a3f920506413.png)

But when I did _driver.findElements(By.className("single_like_button btn3-wrap"))_ it returns me an exception because it can not search the element and the terminal told me that it converts the class to that: 

![image](https://cloud.githubusercontent.com/assets/16807198/22372822/c1d39f94-e496-11e6-9185-a15826502578.png)

It converts the class name like you said but it can't search it :cry:

**Comment by luke-hill** [comment]
That element @Cicko Is technically referenced by the following css selector (And can be found I presume using a similar search)

`.single_like_button.btn3-wrap`.

NB: If you use an inspector and hover over it, it will say. `a.single_like_button.btn3-wrap` Or any other ids / data attributes it may have

**Comment by AutomatedTester** [comment]
This is a question really. You should find by CSS Selector and not by class name.
