### ISSUE TITLE
Get elements with more speed.

### ISSUE THREAD

**Issue by Kurimatzu** [SeleniumHQ/selenium#3429]
## Meta -
OS:  Windows 10

Selenium Version:  3.0.1

Browser:  Firefox

Browser Version:  51

## Steps to reproduce -

List<WebElement> appTwo = driver.findElements(By.cssSelector(replace("infinite-list-item infinite-list-item-transition")));

Well, it works. However, when there's very element, the browser crashes.

You can load the elements in another Thread (not to hang the browser)?

**Comment by AutomatedTester** [comment]
Since this doesnt have the html to reproduce there is not much that we can do.

Since in Firefox we just `document.querySelectorAll('infinite-list-item infinite-list-item-transition')` I suggest raising a bug with Firefox or put the html to reproduce it here.
