### ISSUE TITLE
Not able to turn off the geckologs in selenium 3.0.1

### ISSUE THREAD

**Issue by sureshkumar-skc** [SeleniumHQ/selenium#3433]
## Meta -
OS:   Windows 10 x64

Selenium Version:  3.0.1

Browser: firefox

Browser Version:  50.1.0 (64-bit)

## Expected Behavior -
My custom logs only should be visible on my eclipse console 
## Actual Behavior -
All the logs including js warnings, info all others with my custom logs is displayed on console
## Steps to reproduce -
- Downloaded the geckodriver and selenium 3.0.1, set the system property to geckodriver 
- Created the FirefoxDriver()
- Some usefull logs were thrown which is not at all required for the end user

1485764084437	geckodriver	INFO	Listening on 127.0.0.1:26828
1485764085273	mozprofile::profile	INFO	Using profile path C:\Users\SURESH~2\AppData\Local\Temp\rust_mozprofile.jchFFtkfPkyz
1485764085301	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1485764085320	geckodriver::marionette	INFO	Connecting to Marionette on localhost:58701
1485764085895	addons.manager	DEBUG	Application has been upgraded
1485764086106	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1485764086111	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1485764086123	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1485764086129	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1485764086131	addons.manager	DEBUG	Starting provider: XPIProvider
1485764086132	addons.xpi	DEBUG	startup
1485764086134	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1485764086137	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1485764086137	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1485764086139	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1485764086140	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1485764086141	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1485764086143	addons.xpi	DEBUG	checkForChanges
1485764086144	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1485764086147	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1485764086150	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1485764086151	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
.........

How to turn off these logs ?

**Comment by skiaheliou** [comment]
I'm running:
- Firefox 51.0.1
- Windows 10
- Selenium 3.0.1
- TestNG 6.10

I've attempted to do the following:

    System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
    final DesiredCapabilities capabilities = DesiredCapabilities.firefox();
    capabilities.setCapability("marionette", true);
    capabilities.setCapability(CapabilityType.LOGGING_PREFS, "warn");

But get the following Failure Exception:

    java.lang.ClassCastException: java.lang.String cannot be cast to org.openqa.selenium.logging.LoggingPreferences
    at org.openqa.selenium.firefox.FirefoxDriver.populateProfile(FirefoxDriver.java:188)
    at org.openqa.selenium.firefox.FirefoxDriver.extractProfile(FirefoxDriver.java:168)
    at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135) ... (etc.)

Where the following is the offending line of FirefoxDriver:

    LoggingPreferences logsPrefs = (LoggingPreferences) capabilities.getCapability(LOGGING_PREFS);

Is this an issue with the cast, or my `setCapability` call, or...?

**Comment by sureshkumar-skc** [comment]
@shs96c Is there is any solution for the mentioned issue?

I can see in the gecko driver v0.12.0 log level has changed to info

- Default log level for debug builds of Firefox, which used to be DEBUG, changed to INFO-level

https://github.com/mozilla/geckodriver/releases

How to change these log level in selenium?

**Comment by lmtierney** [comment]
@sureshkumar-skc you can set the log level of geckodriver in the capabilities, [example here](https://github.com/mozilla/geckodriver#capabilities-examples)

**Comment by sureshkumar-skc** [comment]
@lmtierney How can I set log level in java? Is any example there?

**Comment by lmtierney** [comment]
@sureshkumar-skc via [desired capabilities](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#loggingpreferences-json-object)

**Comment by sureshkumar-skc** [comment]
I 've tried as mentioned but still, I am getting the log trace 
The sample code 
LoggingPreferences logs = new LoggingPreferences();
	logs.enable(LogType.BROWSER, Level.OFF);
        logs.enable(LogType.SERVER, Level.OFF);
        logs.enable(LogType.DRIVER, Level.OFF);
        logs.enable(LogType.PROFILER, Level.OFF);
        logs.enable(LogType.CLIENT, Level.OFF);
        System.out.println(logs.getEnabledLogTypes());
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability(CapabilityType.LOGGING_PREFS, logs);
	capabilities.setCapability("marionette", true);
	WebDriver driver = new FirefoxDriver(capabilities);

Please help @lmtierney

**Comment by sureshkumar-skc** [comment]
I got the reply from geckodriver team as The log API in Selenium is not part of the WebDriver specification and thus not supported by geckodriver. Sorry.

—

**Comment by sureshkumar-skc** [comment]
Here is the link https://github.com/mozilla/geckodriver/issues/456#issuecomment-277256588

**Comment by sureshkumar-skc** [comment]
@shs96c @lmtierney Any update on this?

**Comment by barancev** [comment]
It's implememted in 3.3:
```
FirefoxOptions options = new FirefoxOptions()
       .setLogLevel(Level.OFF);
WebDriver driver = new FirefoxDriver(options);
```

But take into accout this issue: https://github.com/mozilla/geckodriver/issues/619

**Comment by sureshkumar-skc** [comment]
Thanks for the update @barancev 
Stil I am notified with some javascript errors, Here the code snippet and output 

 FirefoxOptions options = new FirefoxOptions()
         .setLogLevel(Level.OFF);
	WebDriver driver = new FirefoxDriver(options);

Output as follows: 
1491803870541	geckodriver	INFO	Listening on 127.0.0.1:20614
Apr 10, 2017 11:28:01 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
selenium hq completed --- My custom logs 
JavaScript error: resource://gre/modules/InsecurePasswordUtils.jsm, line 106: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host]
JavaScript error: resource://gre/modules/InsecurePasswordUtils.jsm, line 106: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host]
vtiger completed  --- My custom logs

**Comment by barancev** [comment]
Yes, my previous comment refers to the corresponding geckodriver issue.

**Comment by akostadinov** [comment]
In ruby I couldn't figure out how to get these logging preferences. What I ended up with was:
```
options = Selenium::WebDriver::Firefox::Options.new
options.add_option :log, {"level"=> "trace"}
```
Which should set the log level for the GeckoDriver session. AFAICT the `add_option` method should be able to set any `moz:firefoxOptions` described in [GeckoGriver](https://github.com/mozilla/geckodriver#firefox-capabilities).

To see any of the output though I also had to set `Selenium::WebDriver.logger.level = :debug`.

**Comment by lmtierney** [comment]
@akostadinov there's also the shortcut within `Firefox::Options` for that... `options.log_level = 'trace'`

**Comment by akostadinov** [comment]
@lmtierney , doesn't work for me the way you describe (neither I could figure out what to set as value like I already wrote in my original comment). I think it expects some more complicated structure as explained in https://github.com/SeleniumHQ/selenium/issues/3433#issuecomment-292745294 and previous comments.

If you try my code, you can actually see the log messages from GeckoDriver and Marionette, with just `trace` I see nothing from them.

**Comment by lmtierney** [comment]
Well yes, you still need to enable logging through the logger, but what I gave was a shortcut for 

```
options = Selenium::WebDriver::Firefox::Options.new
options.add_option :log, {"level"=> "trace"}
```

**Comment by akostadinov** [comment]
@lmtierney, to my testing with geckodriver 0.18.0/selenium-webdriver (3.5.1) it is not.

**Comment by lmtierney** [comment]
@akostadinov 
Then I must be crazy, because this works for me. If it's not working for you then I'd like to see a trace with debug logging as well as your code

```
require "selenium-webdriver"
Selenium::WebDriver.logger.level = :debug

options = Selenium::WebDriver::Firefox::Options.new
options.log_level = 'trace'

driver = Selenium::WebDriver.for(:firefox, options: options)
sleep(10)
driver.quit
```


```
2017-09-08 09:44:10 DEBUG Selenium polling for socket on ["127.0.0.1", 4444]
1504881850982	geckodriver	INFO	geckodriver 0.18.0
1504881850986	geckodriver	INFO	Listening on 127.0.0.1:4444
2017-09-08 09:44:11 INFO Selenium Skipping handshake as we know it is W3C.
2017-09-08 09:44:11 INFO Selenium -> POST session
2017-09-08 09:44:11 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}}]}}
2017-09-08 09:44:11 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"247"}
1504881851304	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1504881851307	geckodriver::marionette	TRACE	  connection attempt 0/600
1504881851412	geckodriver::marionette	TRACE	  connection attempt 1/600
1504881851516	geckodriver::marionette	TRACE	  connection attempt 2/600
1504881851620	geckodriver::marionette	TRACE	  connection attempt 3/600
1504881851722	geckodriver::marionette	TRACE	  connection attempt 4/600
1504881851784	Marionette	DEBUG	Received observer notification "profile-after-change"
1504881851807	Marionette	DEBUG	Received observer notification "command-line-startup"
1504881851808	Marionette	INFO	Enabled via --marionette
1504881851827	geckodriver::marionette	TRACE	  connection attempt 5/600
1504881851930	geckodriver::marionette	TRACE	  connection attempt 6/600
1504881852031	geckodriver::marionette	TRACE	  connection attempt 7/600
1504881852136	geckodriver::marionette	TRACE	  connection attempt 8/600
1504881852238	geckodriver::marionette	TRACE	  connection attempt 9/600
1504881852339	geckodriver::marionette	TRACE	  connection attempt 10/600
1504881852444	geckodriver::marionette	TRACE	  connection attempt 11/600
1504881852547	geckodriver::marionette	TRACE	  connection attempt 12/600
1504881852652	geckodriver::marionette	TRACE	  connection attempt 13/600
2017-09-08 09:44:12.725 plugin-container[35978:1862307] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xab3b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-09-08 09:44:12.727 plugin-container[35978:1862307] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xae03, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1504881852755	geckodriver::marionette	TRACE	  connection attempt 14/600
1504881852856	geckodriver::marionette	TRACE	  connection attempt 15/600
1504881852913	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1504881852914	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1504881852960	geckodriver::marionette	TRACE	  connection attempt 16/600
1504881853039	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1504881853040	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1504881853040	Marionette	INFO	Listening on port 57381
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
1504881853065	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:57381
1504881853068	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:57426
1504881853068	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1504881853068	geckodriver::marionette	TRACE	-> 137:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1504881853069	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","timeouts":{}}},"timeouts":{}}]
1504881853072	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0","platformName":"darwin","platformVersion":"16.7.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":35977,"moz:profile":"/var/folders/lp/kxd1t1m9113fpq4fv8r2gyrw0000gq/T/rust_mozprofile.uvDtYJBVrZEq","moz:accessibilityChecks":false}
1504881853098	Marionette	DEBUG	loaded listener.js
1504881853106	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"975e7509-bb61-064d-9a69-231bc045f50f","capabilities":{"browserName":"firefox","browserVersion":"55.0","platformName":"darwin","platformVersion":"16.7.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":35977,"moz:profile":"/var/folders/lp/kxd1t1m9113fpq4fv8r2gyrw0000gq/T/rust_mozprofile.uvDtYJBVrZEq","moz:accessibilityChecks":false}}]
1504881853106	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"975e7509-bb61-064d-9a69-231bc045f50f","capabilities":{"browserName":"firefox","browserVersion":"55.0","platformName":"darwin","platformVersion":"16.7.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":35977,"moz:profile":"/var/folders/lp/kxd1t1m9113fpq4fv8r2gyrw0000gq/T/rust_mozprofile.uvDtYJBVrZEq","moz:accessibilityChecks":false}}]
1504881853106	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"975e7509-bb61-064d-9a69-231bc045f50f","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0","moz:accessibilityChecks":false,"moz:processID":35977,"moz:profile":"/var/folders/lp/kxd1t1m9113fpq4fv8r2gyrw0000gq/T/rust_mozprofile.uvDtYJBVrZEq","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.7.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-09-08 09:44:13 INFO Selenium <- {"value": {"sessionId":"975e7509-bb61-064d-9a69-231bc045f50f","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0","moz:accessibilityChecks":false,"moz:processID":35977,"moz:profile":"/var/folders/lp/kxd1t1m9113fpq4fv8r2gyrw0000gq/T/rust_mozprofile.uvDtYJBVrZEq","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.7.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
2017-09-08 09:44:13 INFO Selenium Detected W3C dialect.
```

**Comment by akostadinov** [comment]
Very strange, I apologize for incorrect info. It works now. I checked the other day and I only saw messages from Selenium. But obviously I made some mistake so I really have to stop late working to save mine and others time. Excuse me again!
