### ISSUE TITLE
Context Menu Selenium selection Issue

### ISSUE THREAD

**Issue by jtsmith0** [SeleniumHQ/selenium#3434]
## Meta -
OS:  Windows 7 (64bit)

Selenium Version:  2.9.1, IDE

Browser:  Firefox 

Browser Version:  51.0.1

![image](https://cloud.githubusercontent.com/assets/25435108/22432390/9bd5fe1a-e6c9-11e6-8d67-e6ce08dd51d9.png)

## Actual Behavior - Context menu is displayed but there are no selenium commands or sub-menu option:

![image](https://cloud.githubusercontent.com/assets/25435108/22431204/908c81ae-e6c5-11e6-9375-cdd0184dfd80.png)

## Steps to reproduce -
1.) Go to: https:/act.ucsd.edu/breathofhopewalk
2.) With the IDE not running or running (recording or not) right click on "Sponsorship Level" dropdown list (or any other field)
3.) Context menu displayed without Selenium selection  

I've uninstalled/reinstalled the Selenium plugin several times but the problem still persist. This was originally working without issue. When the problem started I noticed that the context menu seemed to work on correctly on some sites and not on others. Currently, it has stopped working altogether. I've searched the web and this site for possible related issue but could find nothing that help.

I'm stuck at this point. Any help would be highly appreciated.

Thanks in advance.

**Comment by benpbolton** [comment]
Confirmed on 

MacOS: 10.12
Firefox 51.0.1 (64-bit)
Selenium IDE 2.9.1.1-signed

**Comment by LaLaRocca** [comment]
We are seeing this issue as well on Firefox 50.0.2.  It started the week on 1/30/17.

**Comment by ThatRickGuy** [comment]
Also seeing this on FF 51.0.1. The OPS team is disinclined to rollback to FF 50 as there are numerous significant security vulnerabilities patched in this release.

**Comment by LaLaRocca** [comment]
Confirmed backing up to FF50 does resolve the issue.  Would be great to get a fix so IDE will work with the new versions.

**Comment by jtsmith0** [comment]
Like @ThatRickGuy mentioned, I was also disinclined to rollback to FF 50. So for several days I did some serious digging and I finally found a solution that works. As suggested by "Mariusz Purwin" via the selenium users group I installed the "SeleniumIDE: Flow Control" plugin and all was good. Here is the link to the add on:

https://addons.mozilla.org/pl/firefox/addon/flow-control/

Apologies for not pointing this out sooner but I wanted to be sure it actually worked. Been using it for a couple of days now and have not had any problems. All of my scripts, including the older ones, are running without issue. Hope this helps.

**Comment by dailytabs** [comment]
Running Firefox 54.0.1 (32-bit) and this started happening within the last week. In the context menu, I can see an extra horizontal separator where the commands used to be. When I close the IDE window, the separator goes away. Installing the "SeleniumIDE: Flow Control" plugin did not work for me.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
