### ISSUE TITLE
[error] Unexpected Exception: Error: cross-process JS call failed. 

### ISSUE THREAD

**Issue by jimlongo56** [SeleniumHQ/selenium#3435]
### Meta -
OS:  Mac OS 10.12.3 (16D32)
Selenium Version:   IDE 2.9.1
Browser:  Firefox 51.0.1 (64-bit)

This happens on the first step, type input 

`[error] Unexpected Exception: Error: cross-process JS call failed. `

**Comment by barancev** [comment]
Yes, this started to happen a lot after FF update to 51.

**Comment by Eugene10** [comment]
How we could change or fix it?

**Comment by arickers** [comment]
Same problem with 
OS: Windows 10 - 64-Bit
Selenium Version: IDE 2.9.1
Browser: Firefox 51.0.1 (64-Bit) 
... on clickAndWait   id=id-default-button

**Comment by Psappha** [comment]
I had the same problem, SeleniumIDE flow control fixed it:
https://addons.mozilla.org/en-US/firefox/addon/flow-control/?src=dp-dl-othersby

**Comment by RedRevenge94** [comment]
Thanks Psappha for your advice. It's working.

**Comment by Eugene10** [comment]
My issue is actual(

**Comment by edualuc** [comment]
It's working with SeleniumIDE flow. Thanks

(Funcionou com SeleniumIDE flow. Obrigado!)

**Comment by jimlongo56** [comment]
Yes, this fixed it for me.
The question is, does Selenium IDE now have a dependency on SeleniumIDE: Flow Control?

**Comment by luke-hill** [comment]
FlowControl (Assuming you use the Samit Badle one), is something which is essentially not packaged into the core SeleniumIDE interface. 

If you want to do any sort of complicated propositional logic then you need it (And perhaps other ones such as the logger)

**Comment by jimlongo56** [comment]
I don't think the Flow Control linked above is the one you speak of.

**Comment by Psappha** [comment]
The one I linked is by @davehunt, I can't find one by samit badle though..

**Comment by arickers** [comment]
All working fine with Selenium IDE: Flow Control - @Psappha, thanks for your help!

**Comment by mirao** [comment]
I can see the same issue in Ubuntu 16.04, FF 51.0.1. When I installed the addon Flow Control, the issue disappeared.

**Comment by TJohner** [comment]
I had the same problem and couldn't open the right-click context menu either. The Selenium IDE: Flow Control fixed it for me. thanks @Psappha

**Comment by Ranboz** [comment]
I didn't install Flow Control.  **_The problem also went away after installing the following extensions_:** Don't ask me why (or if you need both or just one).
   (From Mozilla: https://addons.mozilla.org/en-US/firefox/search/?q=selenium)
1. Highlight Elements (Selenium IDE)
2. Selenium IDE: Implicit Wait

I found this out because a friend had the error and I did not (I had the two extensions installed already).  Later, I installed Firefox fresh on Ubuntu, and the error appeared.  After installing the two extenstions, the error no longer presented.

**Comment by huynhkhanhduc** [comment]
It fixed it for me. Thanks

**Comment by dayze** [comment]
Works for me too when I installed flow control.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
