### ISSUE TITLE
Selenium WebDriver Double click function doesnt work on Safari 10

### ISSUE THREAD

**Issue by egmncyln** [SeleniumHQ/selenium#3436]
Hi everybody,

I have been trying to double click to a webelement on safari web browser but i didnt make it yet.

Actions actions = new Actions(myRemoteWebDriver);
actions.moveToElement(myWebElement).doubleClick().perform();

I used code above. It works on google chrome but it doesnt work on Safari.

I found following code on internet but it doesnt work too.

Actions action = new Actions(myRemoteWebDriver);
action.moveToElement(myWebElement);
action.clickAndHold();
action.moveByOffset(100,200).moveByOffset(-10, -20).moveByOffset(-10, -10).moveByOffset(-10,-20).build().perform();
action.release().build().perform();

Can someone help me about this issue ?

Note : I use java maven project with following dependency.

org.seleniumhq.selenium
selenium-server
3.0.1

Thanks and regards.

**Comment by titusfortner** [comment]
Ah, I already closed this one here: https://github.com/SeleniumHQ/selenium/issues/3436
