### ISSUE TITLE
Exception: connection refused (--marionette)

### ISSUE THREAD

**Issue by azhwani** [SeleniumHQ/selenium#3437]
# Meta
Selenium Version: 3.0.2
Geckodriver: 0.13.0
Python : 2.7
Centos : release 6.8
# My script
```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
binary = FirefoxBinary('/pwd/geckodriver')
browser = webdriver.Firefox(firefox_binary=binary)
browser.get('http://seleniumhq.org/')
print(browser.title)
```
When I execute my script, Selenium throws an exception (see below).
- selenium.common.exceptions.WebDriverException: Message: connection refused
- Geckodriver log : 
   error: Found argument '--marionette' which wasn't expected, or isn't valid in this context
        Did you mean --marionette-port?
  USAGE:
    geckodriver --marionette-port <PORT>
  For more information try --help

**Comment by AutomatedTester** [comment]
`binary = FirefoxBinary('/pwd/geckodriver')` should be the path to Firefox not geckodriver.

**Comment by azhwani** [comment]
thank u  @AutomatedTester for ur reply,
What do u mean by Firefox not geckodriver? geckodriver is the driver for Firefox ! can u please explain more about that ?

**Comment by AutomatedTester** [comment]
Driver not Browser. `FirefoxBinary` wants the **binary** for **Firefox** as the name implies.

**Comment by GenyDevelopeur** [comment]
I have the same issue . @AutomatedTester i haven't this binary driver . can you please send me a link to download it.
thanks

**Comment by AutomatedTester** [comment]
read https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by cgoldberg** [comment]
@azhwani @GenyDevelopeur to clarify, you need 2 binaries installed:

* **firefox** (the web browser)
* **geckodriver** (the driver for firefox)

**Comment by azhwani** [comment]
Thanks @AutomatedTester for your reply,
Hi @cgoldberg I tried to install Firefox in my Centos (6.8) but it failed : XPCOMGlueLoad error for file /pwd/firefox/libmozgtk.so.
Thanks

**Comment by cgoldberg** [comment]
@azhwani this the selenium issue tracker

**Comment by azhwani** [comment]
It works fine now thank u @cgoldberg & @AutomatedTester

**Comment by ngujdi** [comment]
I solved this problem by upgrading Firefox from 52 to 57

**Comment by Sunnysidedown916** [comment]
binary = FirefoxBinary('C:\TorBrowser\Browser\Firefox.exe')
