### ISSUE TITLE
Click on a button opens a new window which is giving login page

### ISSUE THREAD

**Issue by luckugupta72** [SeleniumHQ/selenium#3439]
I am logging into a website and in which there is a button which we have to click which will open a new window.
When we are clicking on the button through the script it is giving login page not the page I am expecting.
        WebDriverWait(driver, 90).until(EC.presence_of_element_located((By.CSS_SELECTOR, 'input[value="Legacy Reports"]')))
        driver.find_element_by_css_selector('input[value="Legacy Reports"]').click()

These are the lines of code which i am using to click on the button.

**Comment by mehmetg** [comment]
I do not think this is the appropriate place to ask questions. try stackoverflow.com

You should try to switch to the new window before you try to do anything on there: Look here as a starter: http://stackoverflow.com/questions/10629815/handle-multiple-window-in-python

**Comment by lukeis** [comment]
Please provide a completely reproducible test case for us that would include a link to a page or html (including css / javascript) along with a WebDriver script to reproduce the issue. Without this there is little to nothing one can do to help with your issue. Please do not expect others volunteering their time to work at reproducing your issue.

When a reproducible test case is provided we can reopen the issue.

**Comment by luckugupta72** [comment]
I am sorry unfortunately, I can not provide the script, can you please provide me some suggestions which I can try.
Issue is:
we are Logging in through the script on a website and after selecting some drop down and other controls there is a button called "Legacy Report" is getting clicked which is opening a pop-up window where we need to select few more dropdown. The new pop-up window is rendering to the login page, not the page which we are expecting.
If clicking on the button "Legacy Report"  manually it is opening the expected page in the new window.

I tried waiting for 15 minutes if there is an issue and then again click on the button but still, the issue is coming or start from the beginning.
