### ISSUE TITLE
Browser window stops responding after driver process dies

### ISSUE THREAD

**Issue by rd1992** [SeleniumHQ/selenium#344]
Hi Selenium Devs, 
I am using chromedriver and ran into  the problem of process dying which results in the browser window to stop responding. I filed a bug with the chromedriver project but they referred me here. To see the actual thread please go [here](https://code.google.com/p/chromedriver/issues/detail?id=1043)

To reproduce: 
fire up a chrome window via chromedriver
kill the chromedriver process manually
try navigating to another url

I tried to check for if driver == null or call driver.getUrl() but that does not seem to work either.

Ideally there should be an exception thrown if the driver process was killed

**Comment by andreastt** [comment]
Which language binding do you use?

**Comment by rd1992** [comment]
i used java

**Comment by Krishnanand-codewriter** [comment]
Hi rajan,

Can you correct me, if I'm wrong. Is killing chrome driver process manually
is similar to terminating script?

**Comment by ddavison** [comment]
investigating now.

**Comment by ddavison** [comment]
There **is** an exception that is thrown here.

`org.openqa.selenium.WebDriverException: chrome not reachable`

**Comment by ddavison** [comment]
I'm sorry no.. that exception is thrown if the **browser** is closed.  if you force close **chromedriver**, then I get this exception:

`org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.`

**Comment by rd1992** [comment]
@ddavison could you tell me what version of chromedriver you are using? 2.14 or earlier? Funny thing am not getting this exception. But am on 2.11

**Comment by ddavison** [comment]
I was using `2.14`

**Comment by ddavison** [comment]
actually.. I literally **just** realized that the windows are still open ... they were hidden in my dock.

They are by no means "not responding" I'm able to click through them, and close the windows.

If the driver process closes before the `quit()` method is called, then Selenium has **no** way of interacting with the window.

Selenium ->  Chromedriver -> Chrome

If the `Chromedriver` piece dies, Selenium can't do anything about the stray chrome window since that was "driven" by Chromedriver.

**Comment by barancev** [comment]
@rd1992 What do you get as the result of driver.getUrl() if you call it after killing chromedriver?

**Comment by rd1992** [comment]
@barancev that call does not return ever. Its just stuck there.
@ddavison yeah am getting the same behavior. what i meant was that since the chrome-driver process was killed, the desired behavior would be that the chrome window chrome-driver was handling should also close.

**Comment by ddavison** [comment]
then that indeed should go in the chromedriver issues. not here.

**Comment by lukeis** [comment]
please log chromedriver issues with the chromedriver project:

https://code.google.com/p/chromedriver/issues/list
