### ISSUE TITLE
error SSL_ERROR_BAD_CERT_DOMAIN when using FF51.x and new geckodriver

### ISSUE THREAD

**Issue by shadowDim** [SeleniumHQ/selenium#3441]
## Meta -
OS:  Win8 x64

Selenium Version:  python +Selenium WebDriver + geckodriver 3.0

Browser:  Firefox 

Browser Version:  51.1.x

## Expected Behavior - I get some problem when I used new geckodriver with Python 3.5.2

with old driver I used our test server (with bad sertificate and I added it to the exceptions)

I used FF 47.0.1 with old driver on my job and all work well

`def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(50)
        self.base_url = "https://......."
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_1(self):
        driver = self.driver
        driver.get(self.base_url + "/.........")`

## Actual Behavior -
I get an error 
`File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 248, in get self.execute(Command.GET, {'url': url})
  File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute self.error_handler.check_response(response)
  File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:certerror?e=nssBadCert&u=https%3A//
.........
SSL_ERROR_BAD_CERT_DOMAIN%22%3ESSL_ERROR_BAD_CERT_DOMAIN%3C/a%3E%0A`

## Steps to reproduce -

when I using Chrome with ChromeDriver or old driver (2.3) with FF 47.0.1 all work well

**Comment by aneeshchandy** [comment]
Is the SSL certificate valid for the website you are trying to hit? Could you try something site like: https://www.google.com and does it work?

**Comment by shadowDim** [comment]
with others sites all work.

we have bad sertificate on our test server, and when I first entered on site I add  in exception, and on old version (2.3) all this  work well (FF 47.0.1 + 2.3)

 when I add this site to exception in FF 51.x - I normally entered on site

but if I used new Geckodriver  I get  an error SSL_ERROR_BAD_CERT_DOMAIN

I think driver do not used this exception

**Comment by aneeshchandy** [comment]
Did you try something like this to accept the cert?

```
driver = webdriver.Firefox()
driver.accept_untrusted_certs = True
driver.assume_untrusted_cert_issuer=True
driver.get("https://....")
```

**Comment by MarcinJan** [comment]
Hello

@aneeshchandy it dod not help

Here is my code:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Firefox()
driver.accept_untrusted_certs = True
driver.assume_untrusted_cert_issuer=True
driver.accept_next_alert = True
driver.get("https://*")

It's big problem in my organization because we are many labs with differed hosts name. I can't imagine to add all this host to exception in my Firefox profile 

Marcin

**Comment by shadowDim** [comment]
Hello
If I used the code
` def setUp(self):
        #self.driver = webdriver.Chrome()
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(50)
        self.driver.accept_untrusted_certs = True
        self.driver.assume_untrusted_cert_issuer=True
        self.driver.get("https://................./")        
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_virt(self):`
I've get an error:
`  File "D:\......\bank_transf_virt.py", line
18, in setUp
    self.driver.get("https://......./")
  File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\webdriver
.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\webdriver
.py", line 236, in execute
    self.error_handler.check_response(response)
  File "D:\Python\python3x\lib\site-packages\selenium\webdriver\remote\errorhand
ler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: abou
t:certerror?e=nssBadCert&u=https%3A//....../&c=UTF-8&f=regular&d=.....
....
SSL_ERROR_BAD_CERT_DOMAIN%22%3ESSL_ERROR_BAD_CERT_DOMAIN%3C/a%3E%0A`

but I see what running 2 copies FF and one of them closed and in command promt I see that error
Second copies asks me about certifikate, I add it

**Comment by aneeshchandy** [comment]
Ok, it is a bug in FF and version 54 should fix it. This is set for a future date.
In the meantime, you can download the nightly build and test it out. Good luck!

**Code (in MacOS):**
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

caps = DesiredCapabilities.FIREFOX.copy()
caps['acceptInsecureCerts'] = True
ff_binary = FirefoxBinary('/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin')

driver = webdriver.Firefox(firefox_binary=ff_binary, capabilities=caps)

driver.get('https://cacert.org/')
driver.close()
```

**Download the nightly version here:**
https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly

**References:** 
- http://stackoverflow.com/questions/37868425/accept-ssl-cert-with-marionette-firefox-webdrive-python-splinter/41711649#41711649
- https://bugzilla.mozilla.org/show_bug.cgi?id=1103196
- https://www.hskupin.info/2017/01/23/using-selenium-and-webdriver-to-interact-with-insecure-ssl-pages-in-firefox/

**Comment by lmtierney** [comment]
See @aneeshchandy's solution. The capability is `acceptInsecureCerts`, see https://github.com/mozilla/geckodriver#webdriver-capabilities. This should be fixed in FF 52.
