### ISSUE TITLE
Failed to create instance of FirefoxProfile

### ISSUE THREAD

**Issue by alevideschi** [SeleniumHQ/selenium#3447]
## Meta -
OS:  Windows Server 2012 RT x64

Selenium Version:  Nuget Package Selenium.WebDriver 3.0.1

Browser:  Firefox

Browser Version:  49.0.2 (64-bit)

## Expected Behavior - 
Create a instance of FirefoxProfile to edit preferences with C# in embeded project

## Actual Behavior -
 When execute `var profile = new FirefoxProfile();` this give a exception "The path is not of a legal form", this exception is because my project is embeded in other project. So when execute the command `FileUtilities.GetCurrentDirectory()` in [line 161](https://github.com/SeleniumHQ/selenium/blob/selenium-3.1.0/dotnet/src/webdriver/Internal/FileUtilities.cs#L161) `string currentDirectory = Path.GetDirectoryName(executingAssembly.Location);` this throw exception because Location is null. Because my project is embeded. Here need get Entries Assembly.

## Steps to reproduce - 
Create a project, install nuget package Selenium.WebDriver and embed this a other project and try to Instantiate `new FirefoxProfile()` in C#

**Comment by JobaDiniz** [comment]
Shouldn't these [lines](https://github.com/SeleniumHQ/selenium/blob/selenium-3.1.0/dotnet/src/webdriver/Internal/FileUtilities.cs#L160-L161) query the actual executing assembly? As it is, it is assuming the executing assembly is the selenium driver.

Maybe `Assembly.GetExecutingAssembly()` is more appropriated and it will solve this issue.
