### ISSUE TITLE
Session [(null externalkey)] not available and is not among the last 1000 terminated sessions

### ISSUE THREAD

**Issue by ericomurtez** [SeleniumHQ/selenium#3448]
OSX 
Selenium Version:  
3
Browser:  
Chrome, safari (via appium)

I have posted this on appium github but looks like it is a selenium issue.
https://github.com/appium/appium/issues/7677

I start a test via selenium grid, everything is running smooth the browser starts on the device, and then the test stops with the error in the title.

Appium logs are all fine, as per comment on appium github.

Tried a lot of different things for this.

Steps to repro:
Start grid: java -jar selenium-server-standalone-3.0.1.jar -role hub
Start node:  appium --address localhost  --port 4801 --nodeconfig ./androidConfig.json
Config: Below
Start test - Error

  {
    "capabilities":[
      {
        "browserName": "chrome",
        "maxInstances": 1,
        "seleniumProtocol": "WebDriver",
        "deviceName": "xxxxxxx",
        "platform": "ANDROID"
      }
    ],
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 1,
    "port": 4801,
    "register": true,
    "registerCycle": 5000,
    "hub": "http://localhost:4444/grid/register",
    "host": "localhost",
    "nodeStatusCheckTimeout": 5000,
    "nodePolling": 5000,
    "role": "node",
    "hubPort": 4444,
    "hubHost": "localhost",
    "unregisterIfStillDownAfter": 60000,
    "downPollingLimit": 2,
    "debug": true,
    "servlets" : [],
    "withoutServlets": [],
    "custom": {}

  }

**Comment by cankahveci** [comment]
@dbashford 
https://github.com/appium/appium/issues/7677

**Comment by p0deje** [comment]
I'm not sure how to debug this as it involves Appium which I never even used. Can you provide [concise reproducible test case](http://sscce.org/) with Selenium only so that we could act on this issue.

**Comment by barancev** [comment]
Closing the issue due to inactivity, there is not enough information to act on.
