### ISSUE TITLE
Java client hasn't support of latest ChromeDriver commands

### ISSUE THREAD

**Issue by ragePowered** [SeleniumHQ/selenium#3450]
## Meta
OS:  All
Selenium Version:  3.0.1
Browser:  Chrome
Browser Version:  56.0.2924.87 (64-bit)

## Expected Behavior
All driver commands are supported

## Actual Behavior
GET_NETWORK_CONDITIONS, SET_NETWORK_CONDITIONS and DELETE_NETWORK_CONDITIONS doesn't presented is Java client

## Real world value
Simulating of weak/slow connection became possible with built-in browser capabilities instead of third party solutions.

## Description
ChromeDriver sources contain browser-specific commands that are not supported in Selenium Java client. They can be found here:
https://chromium.googlesource.com/chromium/src.git/+/41f6892aa7564234093ebbcea765990febf495e8/chrome/test/chromedriver/client/command_executor.py
and here:
https://chromium.googlesource.com/chromium/src.git/+/41f6892aa7564234093ebbcea765990febf495e8/chrome/test/chromedriver/client/chromedriver.py

Similar implementation was done in https://github.com/SeleniumHQ/selenium/commit/1b6febddd2986449aac5a957c85a9cb8903651dc

**Comment by ragePowered** [comment]
@sevaseva please advice

**Comment by lukeis** [comment]
why didn't they try to use the 'network_connection' api endpoint?

https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-modes

The data bits were purposely put in the front of the bit mask in order to allow high bits set to mean different network conditions.

@shs96c

**Comment by ragePowered** [comment]
@lukeis
I believe that they want to expose custom presets for network conditions (just like in their DevTools).
Plus, current implementation of Selenium Java client already contains implementation of ChromeDriver-specific commands (ChromeDriver.launchApp(String id)). All I propose - is only add several entries to ChromeDriverCommandExecutor.CHROME_COMMAND_NAME_TO_URL map that describes "new" commands. Such changes will influence only ChromeDriver.

@shs96c

**Comment by devoto13** [comment]
Just for the reference, these APIs were added for [JavaScript](https://github.com/seleniumhq/selenium/commit/d7bdd7cc42faafb1eba031c26b7c369cdea026d5) and [Python](https://github.com/seleniumhq/selenium/commit/7ba13118ace82f2f58073dc35ab05d3ca47eb0a0) in a same fashion as `launchApp` command.

**Comment by p0deje** [comment]
Ruby added support in 1103cb7e9e35e8bd22a5aea9b5455445baa6fb85

**Comment by anhquande** [comment]
+1

**Comment by tohaa** [comment]
+1

**Comment by Zap4ick** [comment]
+1

**Comment by ragePowered** [comment]
Fixed in #3479 
Closed
