### ISSUE TITLE
FluentWait should provide wait while semantics for code clarity.

### ISSUE THREAD

**Issue by Martin-Spamer** [SeleniumHQ/selenium#3454]
This issue is regarding the API, so not specific to a single platform or version.

## Actual Behaviour

Currently the interface to **FluentWait** provides _wait until_ semantics, e.g.

`wait.until(isTrue)`

In some situation this can lead to opaque semantics, and double negative conditions which reduces clarity and increases complexity.

`webDriverWait.until(!ExpectedConditionsvisibilityOf(webElement));`

`webDriverWait.until(ExpectedConditions.not(ExpectedConditions.visibilityOf(webElement)));`

## Desired Behaviour -

The could be easily be improved with `wait while` semantics, e.g.

wait.while(isTrue)

**Comment by jleyba** [comment]
`while` is a reserved word, so you can't have `wait.while(isTrue)`.  I suppose you could have `wait.whilst(isTrue)`, but that's just awkward :)

Also, keep in mind ExpectedConditions are expected to be used with static imports for improved readability:

```java
import static org.openqa.selenium.support.ui.ExpectedConditions.visibilityOf;
// ...
wait.until(visibilityOf(element));
```

You can also define helper functions to improve readability:

```java
wait.until(invisibilityOf(element));

private static Predicate<WebElement> invisibilityOf(WebElement element) {
  return not(visibilityOf(element));
}
```
