### ISSUE TITLE
Selenium documentation still specifies selenium is intended for testing purposes.

### ISSUE THREAD

**Issue by fake-name** [SeleniumHQ/selenium#3462]
So I recently ran into the fact that selenium provides no way to access the HTTP response code.

Apparently this is a WONTFIX issue, as specified here: https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141

However, https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/141 also notes that selenium is **NOT** a tool for testing web-pages, but rather a tool only intended to allow "emulating user actions", and "Selenium is a browser automation framework, not an HTTP recording framework".

Given this fact, that means that much of the documentation needs to be corrected, and apparently has been incorrect for several years.

If selenium is a framework for web testing, accessing the HTTP response code is a code part of many tests, and it's therefore an issue that selenium does not support this.

If automated testing is not a design target of selenium (as #141 states), the lack of HTTP response code is in-scope, but the great majority of the documentation is therefore incorrect, as it specifies functionality that is apparently intentionally not supported by the selenium webdriver protocol.

**Comment by cgoldberg** [comment]
which documentation is incorrect?

**Comment by fake-name** [comment]
On seleniumhq.com:

> Primarily, it is for automating web applications for testing purposes.

**Comment by fake-name** [comment]
I wrote this when I was really irritated at the inability to get HTTP response codes. Never mind.
