### ISSUE TITLE
IE Driver is getting Freezed after few runs

### ISSUE THREAD

**Issue by arunkumar468** [SeleniumHQ/selenium#3466]
## Meta -
OS:  Windows 7, 8 and 10

Selenium Version:  2.53.1

Browser:  Internet Explorer 11 (IE 11)

Browser Version:  
 IE 11 (64 Bit Machines)

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. Happy to reopen when we have that information.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by arunkumar468** [comment]
It's happening for all Test Cases and happening irregularly after few scripts ran.
