### ISSUE TITLE
Cannot use firefox to create commands for scripts in Selenium

### ISSUE THREAD

**Issue by DevinWEdmondson** [SeleniumHQ/selenium#3472]
## Meta -
OS:  Windows

Selenium Version:  2.9.1

Browser:  FireFox 51.0.1

Browser Version:  

## Expected Behavior -
I should be able to right click anywhere on a web page on firefox and create commands that can be used in my selenium scripts such as "verify text".  
## Actual Behavior -
Now what is happening is I right click and I see now selenium commands when using firefox.
## Steps to reproduce -
I'm not sure what is going on so I don't know how to reproduce this issue.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. If you can't reproduce it, chances are high that neither can we.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
