### ISSUE TITLE
IE driver giving Timeout expired waiting for async script  after changing the setScriptTimeOut also.

### ISSUE THREAD

**Issue by vivekbrahmadandi** [SeleniumHQ/selenium#3480]
We have developed our scripts using protractor framework because of Angular Web Pages.
When we run our scripts in chrome or firefox it runs perfectly , whereas in IE 32 bit driver we are getting an issue called Timeout expired waiting for async script after some time. Is it driver specific issue or else from the Webpage asynch scripts  behaviour.

Thanks

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
