### ISSUE TITLE
Form submit action not working on Python client with GeckoDriver

### ISSUE THREAD

**Issue by viniciusd** [SeleniumHQ/selenium#3483]
## Meta -
OS: Linux Debian 8.7
Selenium Version: Python API 3.0.2
Browser: Firefox

Browser Version:  50.1.0 (64-bit)
Python Version:  3.5.2

## Expected Behavior -
Submit action from a input field to actually submit a form

## Actual Behavior -
Exception thrown:

> Traceback (most recent call last):
>   ...
>   File ".../selenium/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 86, in submit
>     "if (arguments[0].dispatchEvent(e)) { arguments[0].submit() }", form)
>   File ".../selenium/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
>     'args': converted_args})['value']
>   File ".../selenium/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File ".../selenium/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: TypeError: Argument 1 of EventTarget.dispatchEvent does not implement interface Event.

## Steps to reproduce -
Create a virtual environment, pip install selenium on it, add the following file as form.html:
```
<html>
    <body>
        <form action="http://www.example.com">
            <input name="login"  type="text">
            <input name="password" type="password">
            <button name="submit" type="submit">Foo</button>
        </form>
    </body>
</html>
```
Then create the following python file:

```
import os


from selenium import webdriver

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException, WebDriverException

baseurl = "file://"+os.getcwd()+"/form.html"

credentials = { 'user': 'foo', 'pass': 'bar' }

for driver in (webdriver.Firefox(), webdriver.Chrome()):
    driver.get(baseurl)
    driver.maximize_window()
    driver.find_element_by_name('login').send_keys(credentials['user'])
    driver.find_element_by_name('password').send_keys(credentials['pass'])
    try:
        driver.find_element_by_name('login').submit()
    except WebDriverException:
        driver.find_element_by_name('submit').click()
        print(driver.name+' failed :(')
    else:
        print(driver.name+' succeeded!')
    driver.quit()  
```
It prints:

> firefox failed :(
> chrome succeeded!

**Comment by viniciusd** [comment]
I traced it back to the submit method:
```
    def submit(self):
        """Submits a form."""
        if self._w3c:
            form = self.find_element(By.XPATH, "./ancestor-or-self::form")
            self._parent.execute_script(
                "var e = arguments[0].ownerDocument.createEvent('Event');"
                "e.initEvent('submit', true, true);"
                "if (arguments[0].dispatchEvent(e)) { arguments[0].submit() }", form)
        else:
            self._execute(Command.SUBMIT_ELEMENT)
```
When using Firefox, a TypeError exception is raised on the execute_script method:

> TypeError: arguments[0].submit is not a function

I am not sure which other(s) browser(s) is(are) w3c true (not sure what this w3c means either) in a way that I could test if the same happens with them. This may be a Javascript issue.

**Comment by viniciusd** [comment]
I thought the code example I created was able to replicate the issue. It isn't, it threw WebDriverException because of another thing (submit button with a submit name tag). I haven't been able to create a minimal example, it may be something related to Angular, given that the original code uses Angular.

**Comment by viniciusd** [comment]
Manually typing the commands on the console worked with no problems:
```
form = document.getElementById("login-form")
e = form.ownerDocument.createEvent('Event')
e.initEvent('submit', true, true);
form.dispatchEvent(e)

```
Then it's either a Selenium or a Geckodriver issue. I don't know how to test further though

**Comment by lmtierney** [comment]
Closing as there is no easily reproducible scenario

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Note: file:// protocol has extra JS restrictions for this protocol as compared to http:// one.

**Comment by viniciusd** [comment]
I still see it as concise and I described the results. What is it lacking?

**Comment by lmtierney** [comment]
> I thought the code example I created was able to replicate the issue.

This is what you said, and we have tests for the submit functionality that are working. Can you provide your breaking scenario?

**Comment by lmtierney** [comment]
It's not concise if we don't have a page or html that allows us to reproduce it.

**Comment by murlock** [comment]
Just for history, I've encountered same issue:
```
<form method=get action='toto'>
<input type='text' id='search' name='q' />
<input type='submit' id='submit' value='Submit/>
```
By updating `id` of submit button, it works
```
 <input type='submit' id='submit' value='Submit/>
```


It look likes related to https://github.com/seleniumhq/selenium/issues/3398
