### ISSUE TITLE
Issue with Desired capabilities - REQUIRE_WINDOW_FOCUS

### ISSUE THREAD

**Issue by praveenkokku** [SeleniumHQ/selenium#3496]
## Meta -
OS:  Windows 7
Selenium Version:  2.53.0
Browser:  Internet Explorer

Browser Version:  IE11 32 bit

Steps: Added Desired capabilities REQUIRE_WINDOW_FOCUS as true for InternetExplorer to work effectively on Actions class methods.
driver.findElement(By.id("texboxId")).sendKeys("sample");

Expected: 
Should enter in small letter in text box as "sample".

Actual:
Entering in caps in text box as "SAMPLE".

How to overcome this issue without making REQUIRE_WINDOW_FOCUS  as false.
because if i am making it false method working with Actions are not working.

Thanks,
Praveen K

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reporoduction scenario provided.
