### ISSUE TITLE
Selenium 3.0.1 with Firefox 51.0.1 and Gecko Driver

### ISSUE THREAD

**Issue by Buzz2Buzz** [SeleniumHQ/selenium#3498]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.0.1
Browser:  
Firefox

Browser Version:  
51.0.1 (Portable)

## Expected Behavior -
Open browser and go to a specific page

## Actual Behavior -
Stuck on user profile page

## Steps to reproduce -
http://stackoverflow.com/q/42154400/4675568

I'm executing this code:  
```
public class Selenium {

        public static void main(String[] args) {
            WebDriver driver = createFFDriver();
            driver.navigate().to("http:....");
            System.out.println("Finished");
        }

        public static WebDriver createFFDriver(){
            System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY,SELENIUM_DRIVERS + "\\firefox\\foo\\geckodriver.exe");
            FirefoxProfile firefoxProfile = new FirefoxProfile();
            File pathToBinary = new File(SELENIUM_INSTALLS_DEV + "\\51.0.1\\FirefoxPortable.exe");
            FirefoxBinary ffBinary = new FirefoxBinary(pathToBinary);

            return new FirefoxDriver(ffBinary,firefoxProfile);
        }
}
```
In logs, I've got this:  
```
1486713046153   geckodriver INFO    Listening on 127.0.0.1:12466 
Feb 10, 2017 8:50:46 AM org.openqa.selenium.remote.ProtocolHandshake
createSession INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1486713046731   mozprofile::profile INFO    Using profile path foo\AppData\Local\Temp\rust_mozprofile.p25D0Gb1sBQm
1486713046752   geckodriver::marionette INFO    Starting browser foo\firefox\51.0\FirefoxPortable.exe
1486713046782   geckodriver::marionette INFO    Connecting to Marionette on localhost:52818
```

Browser is opened but stuck.
![ff_profile_stuck](https://cloud.githubusercontent.com/assets/6714374/22880732/9d603aaa-f1e3-11e6-95f8-1e8cd29ffc9c.png)

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by Buzz2Buzz** [comment]
Done. Posting the thread here just in case:
https://github.com/mozilla/geckodriver/issues/469
