### ISSUE TITLE
Screenshots Intermittently Fail

### ISSUE THREAD

**Issue by LusciousPear** [SeleniumHQ/selenium#3501]
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
3.0.1
Browser:  
Chrome
Browser Version:  
57.0.2987.13

## Expected Behavior -
A screenshot is taken and saved as a .png

## Actual Behavior -
The error message ``` [4.806][WARNING]: screenshot failed, retrying``` appears. No exceptions are thrown. A screenshot is not saved. 

## Steps to reproduce -
```
     driver.switchTo().window(targetwindow);
     TakesScreenshot yourScreenshot = (TakesScreenshot) driver;
     File tempfile = yourScreenshot.getScreenshotAs(OutputType.FILE);
```
   
This happens intermittently, not on certain sites. Maybe it has to do with multiple browser windows open? Or if one window has a blocking popup so it cannot switch? If so, is there a way to define a timeout/wait for the screenshot?

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
