### ISSUE TITLE
IEDriverServer.exe crash calling MoveToElement() action

### ISSUE THREAD

**Issue by Joey-JoeJoe** [SeleniumHQ/selenium#3502]
## Meta -
OS:  
Windoes 7 Pro
Selenium Version:  
3.0.1
Browser:  
Internet explorer 11.0.9600.18537

## Expected Behavior
Open and control two browser windows using a single instance of IEDriverServer.exe. Bring the first browser into focus, navigate to a particular url and scroll to an element (url and element are unimportant as long as they exist and are valid). Bring the second browser into focus, navigate to a particular url, scroll to an element and end the test.

## Actual Behavior
The first browser window is brought into focus, a url is loaded and page is scrolled to a particular element. The second browser window is brought into focus, a url is loaded and page is scrolled to a particular element but then IEDriverServer.exe crashes before the test can complete.

## Extra Notes
I believe this issue has been previously reported but until now there has been no public mention of code that can be used to easily replicate the issue as I provide below. I believe this open issue describes the same problem I am experiencing: [https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7198](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7198). 

Here is what I know:

- Both the 32 and 64 bit versions of the IE driver server are affected (v3.0.0 for both)
- The same code works fine with no crash in other browsers such as google chrome (when modified to replace internet explorer specific code with other browser equivalent)
- I have observed that this problem seems to be intermittent as the code can be run without a crash a very small percentage of the time (I can't be sure but I'm guessing 99.9% crash and 0.01% no crash)
- Using the javascript executor to scroll to the element instead of the MoveToElement() action works as expected without a crash and therefore can be used as a workaround until a proper fix is discovered

## Steps to reproduce

1. Create a new C# 'Windows Forms Application' project named 'SeleniumIEServerCrashTestApp'.

2. Add references to **WebDriver.dll** and **WebDriver.Support.dll**.

3. Place a copy of either the 32 or 64 bit IEDriverServer.exe in 'C:\IEServer' or else change the path of the sIEServerPath string variable in the below code to a path that contains IEDriverServer.exe.

4. Replace the code for Form1 with the following and run:

		using System;
		using System.Linq;
		using System.Windows.Forms;

		namespace SeleniumIEServerCrashTestApp
		{
			public partial class Form1 : Form
			{
				public Form1()
				{
					InitializeComponent();
				}

				private Int32 nPort = 7793;
				private IntPtr[] nBrowserHandle = new IntPtr[2];
				private OpenQA.Selenium.Remote.RemoteWebDriver oBrowser1 = null;
				private OpenQA.Selenium.Remote.RemoteWebDriver oBrowser2 = null;
				private string sIEServerPath = "C:\\IEServer\\IEDriverServer.exe";

				private void Form1_Load(object sender, EventArgs e)
				{
					// Code to reproduce crash in ie server when using MoveToElement action

					try
					{
						OpenQA.Selenium.By oBy = OpenQA.Selenium.By.XPath("//img[@id='footerLogo']");
						OpenQA.Selenium.IWebElement oElement = null;
						OpenQA.Selenium.Interactions.Actions oActions = default(OpenQA.Selenium.Interactions.Actions);

						// Start the IEDriverServer.exe as a hidden window

						System.Diagnostics.Process proc = new System.Diagnostics.Process();

						proc.StartInfo.UseShellExecute = false;
						proc.StartInfo.CreateNoWindow = true;
						proc.StartInfo.FileName = sIEServerPath;
						proc.StartInfo.Arguments = "/port=" + nPort;
						proc.Start();

						// Launch 2 browsers against the same ie server

						LaunchNewBrowser(ref oBrowser1);
						LaunchNewBrowser(ref oBrowser2);

						// Navigate to url in browser #1

						oBrowser1.Navigate().GoToUrl("http://docs.seleniumhq.org");

						// Bring the browser window into focus

						modGlobal.BringWindowToFront(nBrowserHandle[0]);

						// Find the footer element

						if (oBrowser1.FindElements(oBy).Count == 0)
						{
							OpenQA.Selenium.Support.UI.WebDriverWait oWait = new OpenQA.Selenium.Support.UI.WebDriverWait(oBrowser1, TimeSpan.FromSeconds(5));
							oWait.Until<OpenQA.Selenium.IWebElement>(x => x.FindElement(oBy));
						}

						oElement = oBrowser1.FindElement(oBy);

						// Scroll to the footer element using selenium actions class

						oActions = new OpenQA.Selenium.Interactions.Actions(oBrowser1);
						oActions.MoveToElement(oElement);
						oActions.Perform();

						// Navigate to url in browser #2

						oBrowser2.Navigate().GoToUrl("http://docs.seleniumhq.org/download/");

						// Bring the browser window into focus

						modGlobal.BringWindowToFront(nBrowserHandle[1]);

						// Find the footer element

						if (oBrowser2.FindElements(oBy).Count == 0)
						{
							OpenQA.Selenium.Support.UI.WebDriverWait oWait = new OpenQA.Selenium.Support.UI.WebDriverWait(oBrowser2, TimeSpan.FromSeconds(5));
							oWait.Until<OpenQA.Selenium.IWebElement>(x => x.FindElement(oBy));
						}

						oElement = oBrowser2.FindElement(oBy);

						// (Attempt to) scroll to the footer element using selenium actions class

						oActions = new OpenQA.Selenium.Interactions.Actions(oBrowser2);
						oActions.MoveToElement(oElement);
						oActions.Perform();     // <---------- Ie Server Crash
						//((OpenQA.Selenium.IJavaScriptExecutor)oBrowser2).ExecuteScript("arguments[0].scrollIntoView(true);", oElement);      // <---------- scroll to element using javascript = no crash
					}
					catch (Exception ex)
					{
						MessageBox.Show(ex.Message);
					}
					finally
					{
						// Cleanup

						if (oBrowser1 != null)
							oBrowser1.Close();
						if (oBrowser2 != null)
							oBrowser2.Close();

						CloseProcessByName("IEDriverServer");
					}
				}

				private void LaunchNewBrowser(ref OpenQA.Selenium.Remote.RemoteWebDriver oBrowser)
				{
					string sIEProcessName = "iexplore";
					string sBrowserTitle = "WebDriver";

					// Get all currently open browser handles

					System.Diagnostics.Process[] oProccesses = System.Diagnostics.Process.GetProcessesByName(sIEProcessName);
					IntPtr[] nSkipList = null;

					if (oProccesses.Length > 0)
					{
						// Add currently open browser handles to a skip list

						Array.Resize(ref nSkipList, oProccesses.Length);

						for (Int32 i = 0; i <= oProccesses.Length - 1; i++)
						{
							if (oProccesses[i].MainWindowHandle != IntPtr.Zero)
							{
								nSkipList[i] = oProccesses[i].MainWindowHandle;
							}
						}
					}

					// Spawn new browser

					oBrowser = new OpenQA.Selenium.Remote.RemoteWebDriver(new Uri("http://localhost:" + nPort), OpenQA.Selenium.Remote.DesiredCapabilities.InternetExplorer());

					// Ensure there is no wait time when checking for elements

					oBrowser.Manage().Timeouts().ImplicitlyWait(new TimeSpan(0, 0, 0));

					// Get the browser handle (hwnd)

					IntPtr nHandle = GetProcessHandle(sIEProcessName, sBrowserTitle, nSkipList);

					if (nHandle != IntPtr.Zero)
					{
						// Save handle for later

						if (object.ReferenceEquals(oBrowser, oBrowser1))
						{
							nBrowserHandle[0] = nHandle;
						}
						else
						{
							nBrowserHandle[1] = nHandle;
						}
					}
				}

				private IntPtr GetProcessHandle(string sProcessName, string sTitle, IntPtr[] nSkipList)
				{
					IntPtr nReturn = IntPtr.Zero;
					System.Diagnostics.Process[] oProccesses = System.Diagnostics.Process.GetProcessesByName(sProcessName);

					foreach (System.Diagnostics.Process oCurrentProcess in oProccesses)
					{
						if (oCurrentProcess.MainWindowHandle != IntPtr.Zero && (nSkipList == null || (nSkipList.Contains(oCurrentProcess.MainWindowHandle) == false && oCurrentProcess.MainWindowTitle.StartsWith(sTitle) == true)))
						{
							nReturn = oCurrentProcess.MainWindowHandle;
						}
					}

					return nReturn;
				}

				private void CloseProcessByName(string sProcessName)
				{
					System.Diagnostics.Process[] oProccesses = null;
					bool bFound = true;

					while (!(bFound == false))
					{
						bFound = false;
						oProccesses = System.Diagnostics.Process.GetProcessesByName(sProcessName);

						foreach (System.Diagnostics.Process oCurrentProcess in oProccesses)
						{
							bFound = true;

							try
							{
								oCurrentProcess.Kill();
							}
							catch (Exception ex)
							{
							}
							finally
							{
								Application.DoEvents();
							}
						}
					}
				}
			}
		}

		public static class modGlobal
		{
			[System.Runtime.InteropServices.DllImport("user32.dll")]
			[return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.Bool)]
			static extern bool SetForegroundWindow(IntPtr hWnd);
			public static void BringWindowToFront(IntPtr nHandle)
			{
				SetForegroundWindow(nHandle);
			}
		}

**Comment by jimevans** [comment]
What happens if you use separate instances of `IEDriverServer.exe` for each browser instance? Attempting to use one instance of the executable to automate multiple browsers isn't a scenario that's been tested for the driver.

**Comment by Joey-JoeJoe** [comment]
@jimevans using separate instances of the driver for each browser instance works as expected. I can understand that this scenario hasn't been tested, but multiple browser instances on a single driver works great for other browser drivers (ff and chrome). It would be nice if internet explorer could also one day be used the same way without buggy behavior as I very much prefer to optimize my tests by running multiple browser threads against a single driver instance concurrently.

**Comment by jimevans** [comment]
Since this works in the supported scenario, I'm going to close this issue. Thanks for submitting it. Unfortunately, it's going to be fairly low on the list of priorities to change this behavior. I would review a pull request that changed it, though again, getting that PR merged would rate fairly low on the priority list, given the very limited resources devoted to enhancing and maintaining the IE driver.
