### ISSUE TITLE
Running out of Java heap space during test

### ISSUE THREAD

**Issue by VivaLosDoyers** [SeleniumHQ/selenium#3503]
I've got a test that gets run via Selenium Grid on Linux to a Windows node. In this test, I use a Selenium file_detector to send a large file (about 1.6GB) from the running machine to the node:
```
    $browser.file_detector = lambda do |args|
      str = args.first.to_s
      str if File.exist?(str)
    end
```
I  can perform this test with small files no problem. But when I send this larger file, my heap runs out of space. 
```
[remote server] org.openqa.grid.web.servlet.handler.RequestHandler(RequestHandler.java):138:in `process': cannot forward the request Java heap space (org.openqa.grid.common.exception.GridException) (Selenium::WebDriver::Error::UnknownError)
	from [remote server] org.openqa.grid.web.servlet.DriverServlet(DriverServlet.java):83:in `process'
	from [remote server] org.openqa.grid.web.servlet.DriverServlet(DriverServlet.java):67:in `doPost'
```

On both the node and hub machines, I'm running Grid with an increased heap size:

`/usr/bin/java -d64 -Xms512m -Xmx24g blahblahblah`

While a 1.6GB file is large, I don't understand why with a 24GB heap space I'm still running out. It shouldn't need this much memory to base64 decode a file.

Please help!

OS:  
- Grid Hub: Ubuntu 16.04
- Grid Node: Windows 10
Selenium Version: 2.53
Browser: Chrome

**Comment by diemol** [comment]
Yes, I think this is a known issue in Grid 2.x where big file uploads clog the Grid. 
I will close this issue since Grid 2.x and 3.x are not under development anymore.
Please try the alphas of Selenium Grid 4, and report back in a new issue in case you bump into the problem again.
