### ISSUE TITLE
Drag and Drop is not working in chrome browser using jquery-1.9.1.js 

### ISSUE THREAD

**Issue by anilZycus** [SeleniumHQ/selenium#3504]
## Meta -
OS:   Windows 10

Selenium Version:  selenium-java-2.53.0.jar

Browser:  Chrome 

Browser Version:  56.0.2924.87

## Steps to reproduce -

Actions draganddrop = new Actions(driver);
			Actions action = draganddrop.dragAndDrop(element, target);
			action.build().perform();

OR 

Actions draganddrop = new Actions(driver);
			draganddrop.clickAndHold(element).moveByOffset(xOffset, yOffset).release().build().perform();

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
