### ISSUE TITLE
UnsupportedOperationError WebElement.isDisplayed

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3506]
## Meta -
OS:  macOS Sierra 10.12.3
Selenium Version:  selenium-webdriver@3.0.1
Browser:  Safari 10.0.3

## Expected Behavior -
WebElement.isDisplayed() should return true or false

## Actual Behavior -
UnsupportedOperationError WebElement.isDisplayed()

## Steps to reproduce -
driver.findElement(el).isDisplayed();

P.S.:
If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/ - empty bugtracker is opened :(

**Comment by lmtierney** [comment]
This is a known issue with current safaridriver, it is fixed if you use the safridriver from Safari Technology Preview. The bug tracker is empty because it only shows ones that you have created.

**Comment by zenonwch** [comment]
Good news. 
But how can I ask selenium-webdriver to run Technology Preview?

**Comment by lmtierney** [comment]
That would depend on the language bindings you're using. You should be able to pass the executable path somewhere and it would be `/Applications/Safari Technology Preview/Contents/MacOS/safaridriver`. Some language bindings allow a flag to automatically use the tech preview safaridriver.

**Comment by lukeis** [comment]
closing as we don't track safari driver issues here anymore.

**Comment by zenonwch** [comment]
But where users can see all bugs related to safari driver? 
https://bugreport.apple.com/ - shows only my issues.

**Comment by lmtierney** [comment]
Apple does not allow you to see other users' bugs, only your own. If you raise one then you can track it; but like I said this is a known issue and it has already been fixed in later versions so it would just be closed anyway.

**Comment by anthonyliuhao** [comment]
For those who have the same question, here is how I got Selenium WebDriver to run a test in Python:
`driver = webdriver.Safari(port=0, executable_path="/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver")`
