### ISSUE TITLE
Verify webelements on Machine 2 by executing scripts on Machine 1 without starting execution on Machine 2. Is it possible in Selenium or Serenity?

### ISSUE THREAD

**Issue by venunh** [SeleniumHQ/selenium#3509]
Assume that I have test scripts on Machine 1 where I have a step where i need to open browser and verify webelements. This webelements verification i have to do on both Machine1 and Machine2. But i have to execute script only from Machine1 and verification has to be performed on both Machine 1 and Machine 2.

Is it possible in Selenium or Serenity? 

Let me know if you dont get my requirement.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
