### ISSUE TITLE
Please add possibility to set technologyPreview flag for safariDriver in javascript version

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3511]
## Meta -
OS:  
masOS Sierra 10.12.3
Selenium Version:  
javascrip/node 3.0.1
Browser:  
safari 10.0.3

## Expected Behavior -
Need to run test in Safari Technology Preview. There is an Option "technologyPreview" in Java version https://github.com/SeleniumHQ/selenium/blob/selenium-3.0.1/java/client/src/org/openqa/selenium/safari/SafariOptions.java

## Actual Behavior -
Can't set technologyPreview option for safariDriver from javascript binding

**Comment by lmtierney** [comment]
This was just added yesterday with cb00152. @jleyba will this be in the `3.1` release?

**Comment by jleyba** [comment]
Yes, this will be in `3.1`
