### ISSUE TITLE
UnknownCommandError: GET /session/{sessionID}/element/{elementID}/location did not match a known command 

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3513]
## Meta -
OS:  
macOS Sierra 10.12.3
Selenium Version:  
javascript/node 3.0.1
Browser:  
Firefox 51.0.1 (64 bit)
Geckodriver Version:
0.14.0

## Expected Behavior -
WebElement.getLocation() returns element location 

## Actual Behavior -
UnknownCommandError: GET /session/e362d785-035c-4342-ae9b-cbd9c1ce88fd/element/f7e9090c-79c2-8249-b1df-8f080ce9b6e6/location did not match a known command

## Steps to reproduce -
Steps to reproduce -
driver.findElement(locator).then(el => el.getLocation())

https://github.com/mozilla/geckodriver/issues/471
@andreastt
Member
andreastt commented 20 hours ago
/{session id}/location isn’t a WebDriver command endpoint. You probably want /{session id}/rect, which returns a dictionary of x/y/width/height properties.

Are you sure you’re using the most up to date Node.js bindings? If so and the problem persists, please consider filing a bug on the Selenium project.

Thanks!

**Comment by andreastt** [comment]
This is the same as https://github.com/mozilla/geckodriver/issues/471, since Get Element Rect returns both the x/y position and the width/height dimensions.
