### ISSUE TITLE
Python: RemoteConnection with keepalive ignores HTTPS

### ISSUE THREAD

**Issue by kvdveer** [SeleniumHQ/selenium#3514]
## Meta -
OS:  All
Selenium Version:  3.0.2
Browser: Remote
Browser Version: N/A

## Expected Behavior -
`RemoteConnection('https://foo.bar/', keep_alive=True)` sends all its commands over a secure HTTPS connection.

## Actual Behavior -
`RemoteConnection('https://foo.bar/', keep_alive=True)` sends all its commands over an insecure HTTP connection.

## Steps to reproduce -
Use `RemoteConnection('https://foo.bar/', keep_alive=True)` to connect to a secured selenium server.

**Comment by GQAssurance** [comment]
Is this now solved by the switch to using ConnectionPool?

**Comment by AutomatedTester** [comment]
this has been solved by the move the `urllib3`
