### ISSUE TITLE
WindowHandles returns only one handle 

### ISSUE THREAD

**Issue by sgandhi77** [SeleniumHQ/selenium#3517]
Following cod in c# to switch between tabs does not work as WindowHandles returns only  one handle (which is a current window handle)

var currentWindow = driver.CurrentWindowHandle;
           var availableWindows = new List<string>(driver.WindowHandles);
        
        driver.SwitchTo().Window(availableWindows.First());
            driver.Navigate().GoToUrl("www.google.co.uk");
             
                

                foreach (string w in availableWindows)                {
                MessageBox.Show(w);
                    if (w != currentWindow)
                    {

                       
                        driver.SwitchTo().Window(w);
                        driver.Navigate().GoToUrl("www.google.co.uk");

                    }
                   
                }

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sgandhi77** [comment]
Hi

I want to open url in new tab but when I execute following code to open new tab and then try to capture window handles of all the open windows, it returns 1 instead of 2. It seems  it’s returning handle only for the active window.


public static void newtabopen(string url)
        {
            String browser = "IE";
            driver = Browser.OpenBrowser(browser);
            driver.Navigate().GoToUrl(url);
            System.Threading.Thread.Sleep(5000);
            element = driver.FindElement(By.TagName("body"));
            MessageBox.Show(element.ToString());
            System.Threading.Thread.Sleep(5000);
            element.SendKeys(OpenQA.Selenium.Keys.Control + "t"); ---- Opens new tab (works for IE but not for CHROME)
           System.Threading.Thread.Sleep(5000);

          var new9=  driver.WindowHandles;
            var availableWindows = new List<string>(driver.WindowHandles);
           var count=availableWindows.Count;
           MessageBox.Show(count.ToString()); ------ displays 1

Thanks
Simmi

**Comment by jimevans** [comment]
Opening new tabs with `SendKeys` of any kind is explicitly unsupported in the IE driver. The new tab or window will not be seen as a window that can be automated by the driver. This is a limitation of the driver.
