### ISSUE TITLE
[Suggestion]: Better support for containers

### ISSUE THREAD

**Issue by flah00** [SeleniumHQ/selenium#3518]
## Meta -
OS:  Linux (coreos)

Selenium Version:  2.53.1, 3.0.1

Browser:  Chrome

Browser Version:  53+ (64-bit)

## Problem -

I am trying to run Jenkins and Selenium in a kubernetes cluster. It's fairly easy to get them to talk to one another... But my tests make use of downloads and uploads. This leads to problems, because a test container will try to upload a file which the browser container doesn't have access to and vise versa. And thus, my tests fail.

My assumption was that I could create a single hub, and scale up or down the number of selenium nodes I needed... But, if there's no easy way to share files with selenium drivers, like watir, and the browsers, it seems like I would need to resume using selenium standalone. 
 
## Solution? -

In my ideal world, I think selenium should better support the distributed paradigm, by providing interfaces for file transmission. If I use watir to upload a file, it would be great if selenium could transmit the file to the browser container, and then allow the browser to perform the action. Similarly, it would be nice if, after downloading a file, selenium transmitted the file, from the browser container, to the watir driver.

I suppose other people work around this problem by using docker options like `volumes-from` (which kubernetes doesn't support), managing network file systems between containers, or colocating all processes in a single container, removing the need for network file systems. I think it would be nice if this were supported out of the box instead.

On the other hand, I might have missed something the community has already figured out?

**Comment by rjimgal** [comment]
For file uploads you can try `setFileDetector(new LocalFileDetector());` to your RemoteWebDriver instance.

When it comes to downloading files, what we have is a NFS share mounted in each container (we use Docker Swarm, I guess you can have a similar setup with Kubernetes). Then we configure the browser to download to that location (and a given uuid to avoid collisions).

Then after downloading the file to the container, we have a nginx server exposing that NFS share to the outside, so we can download the downloaded file.

I don't know if there's a better approach, but this one works for us.

**Comment by flah00** [comment]
@rjimgal @schmidtkp Thanks for the insight!
