### ISSUE TITLE
Implicitly wait in switching frame

### ISSUE THREAD

**Issue by Uckpa** [SeleniumHQ/selenium#3521]
OS:  
Ubuntu 16.04 LTS
Windows 8

Browser:  
firefox --version
Mozilla Firefox 51.0.1
Mozilla Firefox 51.0.1(Nigthly windows)

Selenium Version:  
geckodriver-v0.14.0-linux32
geckodriver-v0.13.0-linux32
geckodriver-v0.13.0-win32

I got one finding that if we use:

self.driver.implicitly_wait(30)

It works fine when to find and element, can take minimum 0 second to maximum 30 seconds. but in case of switching frame(window) it takes total maximum 30 seconds , means it always wait 30 before switching to frame.

e.g.
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.driver.get('https://somedomain.com')
        self.driver.switch_to.frame('main')
        self.driver.find_element_by_css_selector("[name=id]").send_keys('test')
        self.driver.find_element_by_css_selector("[name=password]").send_keys('test')
        self.driver.find_element_by_css_selector("[name=submit]").click()
        self.driver.switch_to_default_content()
 
Thanks,
Andrey

**Comment by barancev** [comment]
Please log this issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette
