### ISSUE TITLE
Issue - [error] locator not found: id=Email, error = TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element

### ISSUE THREAD

**Issue by NBS327** [SeleniumHQ/selenium#3522]
## Meta -
OS:  Windows 10
Selenium IDE:  2.9.1
Browser:  Firefox 51.0.1

I am learning Selenium and I am working on identifying web elements using Firebug in Selenium IDE. After entering the web elements in the Table tab of the IDE, I wanted to find them using the 'Find' button. I was trying to find the Email text box but when I click the find button, it displays the following error message "locator not found: id=Email, error = TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element".  But it enters the value  in the email textbox in the Google page that I have stored in the value row in the IDE after displaying the error message. This used to work so I verified the firefox version. it was 51.0.1.  Since I had downgraded the version due to another issue to 50.1.0, I was a little surprised and uninstalled and re-installed 50.1. And I do not get the mentioned error.

Also another issue in 51.0.1 is I do not get the option "Show available Commands" in the context menu. and here i got the temporary solution to downgrade from 51.0 to 50.1

Thanks for the support

**Comment by Waartd** [comment]
OS: Windows 7 (64 bit)
Selenium IDE: 2.9.1
Browser: Firefox 52.0 (64 bit)

Hi, maybe a bit stupid to ask but I have a similar problem as the one mentioned in the bottom of this issue. I am following the walk-through on http://www.guru99.com/first-selenium-test-script.html and I also do not get the "Show available Commands" option in the context menu (see below). I have already tried to reinstall Selenium IDE and also reinstalling Firefox but unfortunately to no avail. Woudl any one have a clue what I am doing wrong? Thanks!

![image](https://cloud.githubusercontent.com/assets/26481874/24039399/4ee8f8cc-0b05-11e7-9635-31dfbe0e6248.png)

**Comment by NCotler** [comment]
I had this problem after I updated my Firefox to the latest version: 52.0.2
Selenium Log said "...Window.getComputedStyle does not implement interface Element..." whenever I tried to click on the Find button in Selenium IDE's table tab. I reinstalled the latest version of Selenium IDE here:
 <https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/> and NOW IT WORKS!

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
