### ISSUE TITLE
don't execute a call to `java`, use $JAVA_HOME/bin/java

### ISSUE THREAD

**Issue by activedecay** [SeleniumHQ/selenium#3523]
If two different versions of java are required on the same machine, then calling `java` fails if the user doesn't setup something like etc alteratives in-between calls. 

Use indirection to find the java executable (behind an environment variable).

https://github.com/SeleniumHQ/selenium/blob/ba56ad1ae0b98a1fe1efdd2163c62fc847950178/javascript/node/selenium-webdriver/remote/index.js#L495

    - super('java', {

    + super(process.env.JAVA_HOME + '/bin/java', {

**Comment by Niceplace** [comment]
@activedecay @BeyondEvil @dibagga I think I have experienced a bizarre issue here.

```
OS : Ubuntu 16.04 LTS
Java version: 1.8.0_161
selenium version: standalone 3.8.1
selenium webdriver version: 2.53.43 (according to my yarn.lock)
```
I am using protractor to test an application and from time to time my tests would fail to start with a cryptic node error (ENOTDIR) somehow indicating that a directory was wrong. The stack trace indicated that the error was happening in `node_modules/selenium-webdriver/remote/index.js` so I did a little bit of digging and ended up logging a few things to try and replicate manually.

```
# Line start: 201
 start(opt_timeoutMs) {
    if (this.address_) {
      return this.address_;
    }

    var timeout = opt_timeoutMs || DriverService.DEFAULT_START_TIMEOUT_MS;
    var self = this;

    let resolveCommand;
    this.command_ = new Promise(resolve => resolveCommand = resolve);

    this.address_ = new Promise((resolveAddress, rejectAddress) => {
      resolveAddress(Promise.resolve(this.port_).then(port => {
        if (port <= 0) {
          throw Error('Port must be > 0: ' + port);
        }

        return resolveCommandLineFlags(this.args_).then(args => {
          console.log('############################################');
          console.log(`Executable is ${JSON.stringify(self.executable_)}`);
          console.log(`Args are ${JSON.stringify(args)}`);
          console.log(`Env is is ${JSON.stringify(self.env_)}`);
          console.log(`Stdio is ${JSON.stringify(self.stdio_)}`);
          console.log('############################################');

          var command = exec(self.executable_, {
            args: args,
            env: self.env_,
            stdio: self.stdio_
          });

          resolveCommand(command);
          [....] # Rest of the method code ...
```

I found out that the executable (self.executable_) was set to `/usr/bin/java/bin/java` when it should have been `/usr/bin/java/. Unsetting my JAVA_HOME variable fixed the issue.

Am I in the wrong or there is an actual issue ? I'd be happy to answer any questions, I'm sorry if I didn't provide a complete reproductible case, I'm having time constraints but I can try to do so if its really needed.

**Comment by cgoldberg** [comment]
JAVA_HOME is the root directory of a JDK/JRE

**Comment by Niceplace** [comment]
Oh no.
I might have to burn my diploma after that one.

**Comment by cgoldberg** [comment]
> I might have to burn my diploma after that one.

please post pics so we can verify it is sufficiently destroyed  ¯\_(ツ)_/¯
