### ISSUE TITLE
dependency convergense issue with 3.0.1

### ISSUE THREAD

**Issue by riuvshin** [SeleniumHQ/selenium#3524]
hey guys there is an issue with dependencies in 3.1.0 version
http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/3.0.1/selenium-java-3.0.1.pom
selenium-java using 
```
<dependency>
<groupId>com.codeborne</groupId>
<artifactId>phantomjsdriver</artifactId>
<version>1.3.0</version>
<classifier/>
</dependency>
```

and phantomjsdriver 1.3.0 http://search.maven.org/#artifactdetails%7Ccom.codeborne%7Cphantomjsdriver%7C1.3.0%7Cjar
is using:

```
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>2.53.0</version>
      <scope>compile</scope>
    </dependency>
```

this cause issues with maven build

```
[WARNING]
Dependency convergence error for org.seleniumhq.selenium:selenium-java:3.0.1 paths to dependency are:
+-com.mycompany.qa:qa:1.0.0-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:3.0.1
and
+-com.mycompany.qa:qa:1.0.0-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-java:3.0.1
    +-org.seleniumhq.selenium:selenium-java:2.53.0
```

**Comment by mach6** [comment]
This will be fixed in 3.1.0 once it is published to maven

**Comment by ricardf-cmp** [comment]
Something is really messed up with dependencies on maven. Starting at around 10:30 CET although I force gradle to 3.0.1 it still tries to download 3.1.0 version, despite that one not being published on maven central repository yet! Any idea? please?

**Comment by lmtierney** [comment]
Hi, can you try with `3.2.0`?

**Comment by rkesireddy** [comment]
Tried 3.2.0 getting following dependency convergence error 

+-com.xxxx.xxxx.xxxx.xxx-xxx-test-framework:acceptance-tests-common
  +-org.seleniumhq.selenium:selenium-java:3.2.0
and
+-com.xxxx.xxxx.xxxx.xxx-xxx-test-framework:acceptance-tests-common
  +-org.seleniumhq.selenium:selenium-java:3.2.0
    +-org.seleniumhq.selenium:selenium-java:3.1.0

**Comment by barancev** [comment]
Please report this issue to phantomjsdriver, request them to mark dependency on selenium-java as 'provided' instead of demanding a specific version.

**Comment by lmtierney** [comment]
I believe simon has already fixed this https://github.com/codeborne/ghostdriver/commit/67a31a11026098e82b39901336f16f6dbf09b2eb
