### ISSUE TITLE
64 bit FirefoxDriver does not launch the browser while running on 32 bit jdk

### ISSUE THREAD

**Issue by pradhan-v** [SeleniumHQ/selenium#3525]
## Meta -
OS:  Windows

Selenium Version:  3.0.1

Browser:  Firefox

Browser Version:  51 (and Any)

## Expected Behavior -
Firefox browser should launch.
## Actual Behavior -
Firefox browser does not launch and shows the following exception
```
Exception in thread "main" org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'agent100', ip: '101.102.103.104', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.Executable.<init>(Executable.java:75)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
	at com.abc.test.TestFF.main(TestFF.java:5)
```
## Steps to reproduce -
Run the following java program using a 32 bit jre on a machine with 64 bit Firefox browser.
```
package com.abc.test;
import org.openqa.selenium.firefox.FirefoxDriver;
public class TestFF {
	public static void main(String[] args) throws Exception {
		FirefoxDriver ff = new FirefoxDriver();
		ff.close();
		ff.quit();
	}
}
```

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by pradhan-v** [comment]
64 bit FirefoxDriver **does not launch** the browser while running on 32 bit jdk. This is not a question
This is an issue in selenium 3.0.1. The source has changed, FirefoxBinary.java (locateFirefoxBinariesFromPlatform method),  and WindowsUtils.java(getPathsInProgramFiles method). Ill update the issue if this is still reproducible in the latest release.

**Comment by pradhan-v** [comment]
Im able to reproduce this issue with selenium 3.2.0 as well.

`org.openqa.selenium.os.WindowsUtils`, `getPathsInProgramFiles` method, both the calls to `getProgramFilesPath()` and `getProgramFilesPath()` returns "C:\Program Files (x86)", when a 32bit jvm is used. (Firefox 64 bit is installed in "C:\Program Files\")

This method from `WindowsUtils` is called from `locateFirefoxBinariesFromPlatform` method in `org.openqa.selenium.firefox.FirefoxBinary`.

Workaround is to set the `"webdriver.firefox.bin"` system property.

**Comment by gouessej** [comment]
Why not simply using a 64-bit JVM with Mozilla Firefox 64-bit? When the "bitness" of the web browser differs from the bitness of the JVM, I don't see how Selenium can guess which directory to use and keep in mind that you could install 2 different versions of Firefox with 2 different bitnesses (32-bit and 64-bit). Therefore, your workaround is acceptable to me. In my humble opinion, this is a limitation, this isn't a bug... except if you consider that Selenium should look for Firefox binaries in all program files directories whatever the bitness of the JVM.
