### ISSUE TITLE
Unintended 3.1.0 release?

### ISSUE THREAD

**Issue by surma** [SeleniumHQ/selenium#3527]
Apologies for the informal issue:

A version 3.1.0 was tagged and published to npm but seems unintentional:
* There’s no release description on [GitHub](https://github.com/SeleniumHQ/selenium/releases)
* `By.css()` doesn’t seem to work with attribute selectors (I get `TypeError: Invalid locator`)
* as a result `By.id()` doesn’t work ever (as it uses `By.css(*[id=$id])`) which seems like something tests should have caught

**Comment by cgoldberg** [comment]
It seems like a legit release to me...  the release description on GitHub just hasn't been updated yet.

I didn't see a release announcement, but 3.1.0 was definitely released 2 days ago (Feb 15, 2017) for node.  (Interestingly, the 3.1.0 python bindings haven't been published to PyPI yet).  If you are seeing regressions, I would log issues for them.

for node, I just verified the following events happened on Feb 17:
  * the finalized changelog was committed to master branch with the version bumped to 3.1.0
  * version 3.1.0 was tagged in the repo
  * the 3.1.0 package was published to NPM registry by a core maintainer

3.1.0 changelog:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

**Comment by ddavison** [comment]
i'll publish it today. There is no SLA on "releasing to github" @surma.  our "legitimate" releases are housed in

https://selenium-release.storage.googleapis.com/index.html

And *this* is the tell-all location for all releases, not github.com/seleniumhq/selenium/releases

**Comment by surma** [comment]
My bad then. Sorry if I caused any confusion.

**Comment by ddavison** [comment]
no worries! :)  hope that shed some light
