### ISSUE TITLE
Python documentation should include info on drivers

### ISSUE THREAD

**Issue by Cephlin** [SeleniumHQ/selenium#3529]
## Meta -
OS:  Windows 7
Selenium Version:  3.0.2
Browser:  Firefox/Chrome

My issued is that the following information has only been known to me not through the python documentation where it should be. I eventually found the pypi documentation which suggested you need the webdrivers and then when I go to raise an issue, I finally find all the information I've spent hours looking for. Please just add this text into the documentation:

- here: http://selenium-python.readthedocs.io/
- and why not here: https://pypi.python.org/pypi/selenium

```
Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Any issue logged here for Firefox 48 or later will be closed as a duplicate of
#2559. Our recommendation is to switch to GeckoDriver, or to continue testing
on Firefox 45 until GeckoDriver is a viable option for you. If you are
interested in helping us to sign the add-on to restore support for later
Firefox versions, please see the following comment for what's needed:
https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver
```
## Expected Behavior -
The documentation has all the relevant information to get started using Selenium. This is my first experience with Selenium and I am severely disheartened and annoyed by the poor documentation. Within the space of around 3-4 hours, I was just about able to get Chrome working and then I finally found this information. This should be in the docs from the get go, I should not have to raise an issue to find what should be in the documentation.

## Actual Behavior -
Documentation has the code quoted bit attached so that no-one else has to go on a wild goose chase.

## Steps to reproduce -
Try to install, setup, and run a basic test as a beginner to Selenium. Good luck to you, might take you a while but I'm sure you'll eventually come to raise a GitHub issue and find the relevant information. Took me around 3 hours of Googling, tinkering, hacking, stack exchanging, reading blogs etc. before I found this information, I don't recommend trying to replicate this issue, I just recommend fixing it. Add the information into the docs and then it won't happen again.

**Comment by cgoldberg** [comment]
> Please just add this text into the documentation
> here: http://selenium-python.readthedocs.io/

That is not the official selenium documentation.  It was not created or updated by the Selenium maintainers.  It is simply a user guide created by an individual with no affiliation to the project.

> and why not here: https://pypi.python.org/pypi/selenium

That PyPI page already states things pretty clearly regarding use of drivers (IMHO).

The official docs for the selenium python bindings are here:  https://seleniumhq.github.io/selenium/docs/api/py/
The docs have info regarding drivers pretty prominently displayed:

```
Drivers

Selenium requires a driver to interface with the chosen browser. Firefox, for example, requires geckodriver, which needs to be installed before the below examples can be run. Make sure it’s in your PATH, e. g., place it in /usr/bin or /usr/local/bin.

Failure to observe this step will give you an error selenium.common.exceptions.WebDriverException: Message: ‘geckodriver’ executable needs to be in PATH.

Other supported browsers will have their own drivers available. Links to some of the more popular browser drivers follow.

Chrome:	https://sites.google.com/a/chromium.org/chromedriver/downloads
Edge:	https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
Firefox:	https://github.com/mozilla/geckodriver/releases
Safari:	https://webkit.org/blog/6900/webdriver-support-in-safari-10/
```

> Took me around 3 hours of Googling, tinkering, hacking, 
> stack exchanging, reading blogs etc. before I found this information

`¯\_(ツ)_/¯`

**Comment by Cephlin** [comment]
¯\_(ツ)_/¯
