### ISSUE TITLE
unable to use actual iOS device

### ISSUE THREAD

**Issue by kshitijnigam** [SeleniumHQ/selenium#353]
Hello as mentioned in the tutorial i cloned the git repo, however on doing the ./go iPhone ; i am unable to get the device. I made sure the device is in the network and is connected. is there a detailed tutorial for using actual physical devices?? if yes please share it with me screenshots will also be helpful . thanks in advance

**Comment by andreastt** [comment]
Do we support iPhone in Selenium?

**Comment by andreastt** [comment]
@barancev or @shs96c?

**Comment by lukeis** [comment]
this has long since been deprecated and removed. What tutorial? Those instructions are out of date.

Please use either ios-driver or appium.

**Comment by kshitijnigam** [comment]
yes , it has been deprecated but even with either iosdriver or appium ; i cant find a way to run it on actual device?? i can see it on simulators are there any tutorials for the same?

**Comment by andreastt** [comment]
This isn't a support forum.  Please refer to Appium's support channels.

**Comment by kshitijnigam** [comment]
ok THANKS
