### ISSUE TITLE
Web driver initialization failed, some tests hangs for 3h with 

### ISSUE THREAD

**Issue by riuvshin** [SeleniumHQ/selenium#3531]
OS:  
LInux
Selenium Version:  
3.0.1
Browser:  
Google Chrome

hey gus we are running selenium tests using selenium official images with hub.
here is our compose file:

```
version: '2'
services:
  selenium_hub:
    image: selenium/hub:3.0.1
    container_name: selenium_hub
    privileged: true
    volumes:
      - '/dev/urandom:/dev/random'
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=1800000
      - GRID_MAX_SESSION=6
      - GRID_BROWSER_TIMEOUT=1800000
      - GRID_NODE_POLLING=10000
      - GRID_CLEAN_UP_CYCLE=10000
      - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=60000
      - JAVA_OPTS=-Xmx1024m
    ulimits:
      nproc: 163840
      nofile:
        soft: 163840
        hard: 163840
    restart: always
    networks:
      - selenium_grid_internal

  chromenode:
    image: selenium/node-chrome:3.0.1
    privileged: true
    depends_on:
      - selenium_hub
    volumes:
      - '/dev/shm:/dev/shm'
      - '/dev/urandom:/dev/random'
    environment:
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - NODE_REGISTER_CYCLE=5000
      - NODE_PORT=5555
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    ports:
      - 5900
      - 5555
    networks:
      - selenium_grid_internal
    ulimits:
      nproc: 163840
      nofile:
        soft: 163840
        hard: 163840
    restart: always

networks:
    selenium_grid_internal:
```
we usually run 1 hub and 4 chrome nodes to parallelize our tests.

```
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
```

But due to some reasons many of tests just hangs for **3h**  each and fail with this:

```
10:07:26 2017-02-18 08:07:26,225[TestNG]           [INFO ] [com.company.BaseTest 148]        - Thread id:23. Running : com.company.ImportRecursiveSubmoduleTest
13:05:48 2017-02-18 11:05:48,335[TestNG]           [ERROR] [c.c.ide.utils.DriverInitUtil 93]     - Web driver initialization failed: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
13:05:48 Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
13:05:48 System info: host: 'slave4.company.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.28.2.el7.x86_64', java.version: '1.8.0_102'
13:05:48 Driver info: driver.version: RemoteWebDriver 
```

we have hundreds of tests and each iteration could take many days due to this huge **3h** hang or timeout.

Please help us to fix or workaround this issue somehow we will be really happy to try anything you may need or provide any info to solve this problem.

**Comment by Vrushabhh** [comment]
Hey,

These kinds of issues generally we face when the product is unstable. 

Solution:- Try using different browser in Grid i.e. Use 1 I.E. , 1 Firefox, 1 Safari or Opera and 1 Chrome. I hope due to this load on the Chrome driver may be reduced and failure chances will be less compared to initial one.

**Comment by riuvshin** [comment]
I've found issue it was hangs due to wrong documentation around timeouts. now my tests not hang but still fail in some rare cases with `session * was terminated due to TIMEOUT` it is absolutely not clear which exactly timeout it is so I keep investigate this.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by riuvshin** [comment]
That was actually issue  with wrong timeouts examples, fixed with https://github.com/SeleniumHQ/docker-selenium/commit/eb4ca24e039d8fc896cfcf84470623b20cfd56fe
