### ISSUE TITLE
PhantomjsDriver 'A exception with a null response was thrown sending an HTTP request to the remote WebDriver

### ISSUE THREAD

**Issue by rongthhieng1** [SeleniumHQ/selenium#3533]
OS:  Windows 10? OSX
Selenium Version:  3.1.0
Browser:  Phantomjs

I'm sorry, I'm newbie, But I'm don't know how to fix this
Maybe I login website have load time too long, but I don't know fix

This is full error
OpenQA.Selenium.WebDriverException: 'A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:62602/session/7d519250-f660-11e6-b4f4-9f4b5e95aa2a/execute. The status of the exception was ServerProtocolViolation, and the message was: The server committed a protocol violation. Section=ResponseStatusLine'

Inner Exception
WebException: The server committed a protocol violation. Section=ResponseStatusLine

**Comment by titusfortner** [comment]
See response in #3534. phantomjs is not currently compatible with selenium 3.1. You'll need to wait for next release of phantomjs.

**Comment by lmtierney** [comment]
@rongthhieng1 this should be fixed in server `3.2`
