### ISSUE TITLE
Java: parameter type conflict

### ISSUE THREAD

**Issue by dr29bart** [SeleniumHQ/selenium#3538]
## Meta -
OS:  
Windows 10
Selenium Version:  3.1.0

## Expected Behavior 

> Success complilation

## Actual Behavior 

> T.java:[10,59] no suitable method found for until(org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.Alert>)
>     method org.openqa.selenium.support.ui.FluentWait.until(java.util.function.Predicate<org.openqa.selenium.firefox.FirefoxDriver>) is not applicable
>       (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.Alert> cannot be converted to java.util.function.Predicate<org.openqa.selenium.firefox.FirefoxDriver>)
>     method org.openqa.selenium.support.ui.FluentWait.<V>until(java.util.function.Function<? super org.openqa.selenium.firefox.FirefoxDriver,V>) is not applicable
>       (cannot infer type-variable(s) V
>         (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.Alert> cannot be converted to java.util.function.Function<? super org.openqa.selenium.firefox.FirefoxDriver,V>))
> 

## Steps to reproduce -
Compile java class:

``` 
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;

public class T {

    public static void main(String[] args) {
        new FluentWait<FirefoxDriver>(new FirefoxDriver()).until(ExpectedConditions.alertIsPresent());
    }

}

**Comment by shs96c** [comment]
Update your version of Guava to 21 or later.

**Comment by NikolayStanoev** [comment]
Hello,

I am using jdk 1.8 and before making the changes below I had (selenium standalone 3.0.1 / guava 18.0). All tests which were using the following code fragment were running fine:

`(new WebDriverWait(this.webDriver, timeOutInSeconds)).until(ExpectedConditions.visibilityOfElementLocated(locator));`

Then I applied the changes below:

I have downloaded latest selenium standalone server version (3.2.0) from here - https://goo.gl/dR7Lg2
I have changed guava in my pom.xml file from 18.0 to 21.0 
Then I ran a the same tests just to ensure that everything is ok. Unfortunately, the tests failed on a step below:

`(new WebDriverWait(this.webDriver, timeOutInSeconds)).until(ExpectedConditions.visibilityOfElementLocated(locator));`

The result is the following error:
`java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;`

Can you have an look on this?
