### ISSUE TITLE
Chrome driver issue, worked until 4 days ago

### ISSUE THREAD

**Issue by tnimni** [SeleniumHQ/selenium#3543]
## Meta -
OS:  OS X 10.11.6
Selenium Version:  2.53.1 and 3.0.1 (I tried both)
Chrome driver version: 2.26 and 2.27 I tried both
Browser:  
Chrome 56.0.2924.87 

Starting today, I'm unable to press some button on the page. This script worked perfectly on Feb 16th 2017, meaning a few days ago.

link to page: dev.budgeta.com

after filling the email and password, I try to click on button login, I'm getting the following error

org.openqa.selenium.WebDriverException: unknown error: Element <button class="btn" type="submit" id="login-btn">...</button> is not clickable at point (800, 585). Other element would receive the click: <div class="main-content login-page  ">...</div>
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 78 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'Tsachis-MBP', ip: '10.0.0.2', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6), userDataDir=/var/folders/sx/799xnn2d5mb270n4ql0f24380000gn/T/.org.chromium.Chromium.lDtTk9}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 730f17172d09d87cf38e70ebf3070d18

Please assist

**Comment by ddavison** [comment]
when we tag, we don't overwrite the tags.. if you checked out 3.0.1 and it worked a while ago, and stopped working recently, that's something on your side, we didn't update anything for 3.0.1.. we were busy releasing 3.1.0.  

So, it looks as if your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.

We can reopen this issue if i'm wrong.  *(i've been wrong in the past.)*

**Comment by tnimni** [comment]
Hi,

I came to the office today, and It suddenly worked.

I tried to narrow down the problem and figured that when I run it on my laptop screen (mac book pro 13") it will fail, and when I run on external monitor (Dell 24") it works fine

on both cases the element appear on screen and visible

isn't it weird?
