### ISSUE TITLE
How to launch browser as non admin using Webdriver

### ISSUE THREAD

**Issue by furqanmlk** [SeleniumHQ/selenium#3549]
## Meta -
OS:  WIn 10x 64

Selenium Version:  2.52

Browser:  Firefox 51.0.1
               Chrome 52

## Expected Behavior - 
Should be able to launch browser as non admin, when editor (Eclipse/Visual studio) was launched as admin.

## Actual Behavior - 
Browser is launched as admin mode, some Add-Ons do not work on admin mode

## Steps to reproduce -
1. Launch Visual studio or Eclipse as admin
2:  // Create webDriver reference
        WebDriver driver;
        
        // Launch FirefoxDriver
        driver = new FirefoxDriver();
3: Notice that browser was launched as admin

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
