### ISSUE TITLE
Log level from FireFox options still not working for GeckoDriver

### ISSUE THREAD

**Issue by iamjamalkhan** [SeleniumHQ/selenium#3550]
## Meta -
OS:  
RHEL 7-64bit
Selenium Version:  
3.1.0
Browser:  
Firefox

Browser Version:  
51.1.0

## Expected Behavior -
Selenium log level control for GeckoDriver does not work.
DesiredCapabilities capabilities = new FirefoxOptions().setLogLevel(Level.OFF).addTo(DesiredCapabilities.firefox());
capabilities.setCapability("marionette", true);
_driver = new FirefoxDriver(capabilities);
After setting the log level to OFF , expected behavior is no logs should be seen on console.

## Actual Behavior -
Although an api to set the log level is added in 3.1.0 release, but it does not seem to turn off the logging on the console. 
1487713396994   geckodriver     INFO    Listening on 127.0.0.1:19566
    [junit] log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
    [junit] log4j:WARN Please initialize the log4j system properly.
    [junit] 1487713397322       mozprofile::profile     INFO    Using profile path /tmp/rust_mozprofile.hNjmFvFGhG0C
    [junit] 1487713397615       addons.manager  DEBUG   Application has been upgraded
    [junit] 1487713397635       addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
    [junit] 1487713397637       addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
    [junit] 1487713397642       addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
    [junit] 1487713397644       addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
    [junit] 1487713397645       addons.manager  DEBUG   Starting provider: XPIProvider
    [junit] 1487713397645       addons.xpi      DEBUG   startup
    [junit] 1487713397646       addons.xpi      INFO    SystemAddonInstallLocation directory is missing
    [junit] 1487713397647       addons.xpi      INFO    Mapping firefox@getpocket.com to /root/Jamal/firefox/browser/features/firefox@getpocket.com.xpi
    [junit] 1487713397647       addons.xpi      INFO    Mapping e10srollout@mozilla.org to /root/Jamal/firefox/browser/features/e10srollout@mozilla.org.xpi
    [junit] 1487713397647       addons.xpi      INFO    Mapping webcompat@mozilla.org to /root/Jamal/firefox/browser/features/webcompat@mozilla.org.xpi
    [junit] 1487713397648       addons.xpi      INFO    Mapping aushelper@mozilla.org to /root/Jamal/firefox/browser/features/aushelper@mozilla.org.xpi
    [junit] 1487713397648       addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /root/Jamal/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
    [junit] 1487713397649       addons.xpi      DEBUG   checkForChanges
    [junit] 1487713397650       addons.xpi      DEBUG   Loaded add-on state from prefs: {}
    [junit] 1487713397651       addons.xpi      DEBUG   New add-on firefox@getpocket.com in app-system-defaults
    [junit] 1487713397652       addons.xpi      DEBUG   getModTime: Recursive scan of firefox@getpocket.com
    [junit] 1487713397652       addons.xpi      DEBUG   New add-on e10srollout@mozilla.org in app-system-defaults
    [junit] 1487713397653       addons.xpi      DEBUG   getModTime: Recursive scan of e10srollout@mozilla.org
    [junit] 1487713397653       addons.xpi      DEBUG   New add-on webcompat@mozilla.org in app-system-defaults
    [junit] 1487713397654       addons.xpi      DEBUG   getModTime: Recursive scan of webcompat@mozilla.org
    [junit] 1487713397654       addons.xpi      DEBUG   New add-on aushelper@mozilla.org in app-system-defaults
    [junit] 1487713397654       addons.xpi      DEBUG   getModTime: Recursive scan of aushelper@mozilla.org
    [junit] 1487713397655       addons.xpi      DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
    [junit] 1487713397655       addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
## Steps to reproduce -
1. Initialize Firefox driver with marionette capability and try to set the log level to OFF.
2. At time of Initialization still all the logs are appearing on the console.

**Comment by iamjamalkhan** [comment]
Can someone please have a look at this issue?

**Comment by lmtierney** [comment]
Can you provide more of your debug info, specifically what capabilities are actually getting sent to geckodriver?

**Comment by iamjamalkhan** [comment]
Hi,
I am not setting too much capabilities, here is the code for the same
DesiredCapabilities capabilities = new FirefoxOptions().setLogLevel(Level.OFF).addTo(DesiredCapabilities.firefox());
capabilities.setCapability("marionette", true);
_driver = new FirefoxDriver(capabilities);

Once we set log level with the new API, it does not work as expected.

**Comment by lmtierney** [comment]
I want to see what is actually getting send though, not what you're setting

**Comment by lmtierney** [comment]
@iamjamalkhan which logs are you expected to not see out of your stacktrace? It looks like it is working as intended to me

**Comment by lmtierney** [comment]
I'll have to look more into it, it does appear that there may be an issue

**Comment by lmtierney** [comment]
Ok, selenium is in fact setting it correctly. Try setting the log level to `FINE` and you will see a lot more output from geckodriver. All the other addons tracing does appear to be coming from geckodriver, so that is an issue you would have to bring up with them. http://github.com/mozilla/geckodriver/issues

**Comment by dr29bart** [comment]
Please, re-open the ticket. There is definitely an issue with passing log level to gecko driver
![image](https://cloud.githubusercontent.com/assets/1547167/23410028/be2de778-fd9b-11e6-9e7a-7202029d04c7.png)

The first entry in logLevelToGeckoLevel appears AFTER geckodriver is started which is not correct. It makes impossible to disable gecko driver logs

**Comment by lmtierney** [comment]
The geckodriver service has to be started in order to send the desired capability which sets the log level. In order to get rid of that message from showing, you need to pass the log level at an argument level.

**Comment by dr29bart** [comment]
Are you talking about 
```
  DesiredCapabilities capabilities = new FirefoxOptions().addArguments("--log fatal")
.addTo(DesiredCapabilities.firefox());
        new FirefoxDriver(capabilities).quit();
```
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxOptions.java#L201

Those arguments are passing to Firefox browser instead of geckodriver server :(

**Comment by lmtierney** [comment]
I'm talking about the geckodriver service https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/GeckoDriverService.java#L54

**Comment by lmtierney** [comment]
Try this from the command line and you'll see it:

```
$ geckodriver
1488294543336	geckodriver	INFO	Listening on 127.0.0.1:4444
```
```
$ geckodriver --log fatal
```

**Comment by iamjamalkhan** [comment]
Hi,
Please give an example, how we can use it with Selenium Java bindings. Do you mean we have to use GeckoDriverService api to achieve the expected results.

**Comment by lmtierney** [comment]
If you want to stop this one single line of showing before you can change the log level via the desired capabilities, yes.

Something like this:
```
GeckoDriverService gecko =  new GeckoDriverService(new File("path/to/geckodriver"), 4444, ImmutableList.of("--log=fatal"), ImmutableMap.of());
gecko.start();
FirefoxOptions opts = new FirefoxOptions().setLogLevel(Level.SEVERE);
DesiredCapabilities capabilities = opts.addTo(DesiredCapabilities.firefox());
WebDriver driver = new FirefoxDriver(gecko, capabilities);
```

**Comment by spinning10** [comment]
`new FirefoxDriver(gecko, capabilities)` is deprecated in WebDriver 3.3.1

**Comment by ice1080** [comment]
One option that has worked for some is proposed [here](https://stackoverflow.com/a/42699197/7405767), and uses a batch file to pass in the command line arguments to the executable. Unfortunately, this oftentimes leaves extra processes open (geckodriver.exe, cmd.exe) and no solution to this next problem has been proposed as of yet...

**Comment by anantha-mg** [comment]
@ice1080 You can run below snippet during driver.quit to kill geckodriver process [command is for Linux - similar command can be found for windows]. A disadvantage of this approach is we cannot run multiple selenium-based program/processes in parallel as one can kill gecko process of other in that case.
```
driver.quit();
String command = "killall geckodriver";
Process p = Runtime.getRuntime().exec(command);
```

**Comment by timrsfo** [comment]
I followed the link in @ice1080 comment above and found an answer for windows. I added the below comment there. 

This is the linux version for @voji answer on stackoverflow. Note I don't believe the --log fatal does anything, at least not on linux. However the redirect to NULL works well enough for me

    "webdriver.gecko.driver": "/path-to-driver/geckodriver.sh

filename: geckodriver.sh (executable)

    #! /bin/bash
    echo " ARGS: " $@
    geckodriver --log fatal "$@" > /dev/null 2>&1

**Comment by timrsfo** [comment]
the following seems to work:
"webdriver.gecko.driver": "/usr/local/bin/geckodriver.sh",

    Filename: /usr/local/bin/geckodriver.sh
    #!/bin/bash
    echo "GECKO COMMANDLINE ARGS: " $@
    
    #geckodriver --log fatal "$@" > /dev/null 2>&1 # works because everything is redirected to null
    #geckodriver --log fatal "$@" &    # my testings shows the --log fatal doesn't do anything!

    geckodriver "$@" > /dev/null 2>&1 &  # works without --log fatal, again all redirected to null
    #geckodriver --log error "$@" &            # still get all DEBUGs, --log fatal doesn't work
    #geckodriver -vvvv  "$@" &                # new -v option didn't work for me

    
    pid="$!"
    
    echo "geckodriver.sh pid is: $$"
    echo "child geckodriver  pid is: $pid"
    
    trap 'echo I am going down, so killing off my processes..; kill $pid; exit' SIGHUP SIGINT SIGQUIT SIGTERM

    wait

NOTE: the 'trap' is needed, without it webdriver will kill the geckodriver.sh but leave the geckodriver running
