### ISSUE TITLE
Firefox maximize and sendKeys does not work with GeckoDriver on Selenium 3.1.0

### ISSUE THREAD

**Issue by iamjamalkhan** [SeleniumHQ/selenium#3551]
## Meta -
OS:  
RHEL7-64 bit
Selenium Version:  
3.1.0
Browser:  
Firefox

Browser Version:  
51.0.1

## Expected Behavior -
Once the driver is initialized with Geckodriver, the window loads the url and should maximize and accept keys F11 and F5. Here is the code 
_driver.get( url );
By by = get_element( "global_nav" );
_driver.manage().window().maximize();
_driver.findElement( by ).sendKeys( Keys.F11 );
sleep( 2000 );
_driver.findElement( by ).sendKeys( Keys.F5 );
## Actual Behavior -
Neither the Firefox window maximizes nor sendKeys is having any impact.
## Steps to reproduce -
1. Use Firefox with GeckoDriver to initialize the driver.
2. Load a url and try to maximize with above code.
3. Then send two keys F11 and F5 using the above code.

**Comment by iamjamalkhan** [comment]
Hi,

Can someone please reply to this issue.

**Comment by barancev** [comment]
PLease log the issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

**Comment by iamjamalkhan** [comment]
Hi,

I did file a bug with Mozilla, but seems like there has been some change in Web driver specification. Please refer to this reply on git hub 
https://github.com/mozilla/geckodriver/issues/475#issuecomment-282004271

Could you please let me know how can I access those command mentioned in the reply through Selenium Java api.

**Comment by iamjamalkhan** [comment]
Hi,

I did file a bug with Mozilla, but seems like there has been some change in Web driver specification. Please refer to this reply on git hub
mozilla/geckodriver#475 (comment)

Here is the bug id for reference too
https://bugzilla.mozilla.org/show_bug.cgi?id=1344299

Could you please let me know how can I access those command mentioned in the reply through Selenium Java api.

@barancev
