### ISSUE TITLE
When I execute multiple tests using Ant Build, only 40% result is passed and remaining are failing.

### ISSUE THREAD

**Issue by Vrushabhh** [SeleniumHQ/selenium#3557]
## Meta -
OS:  Windows 10

Selenium Version:  2.40 & 2.44

Browser:  Chrome

Browser Version:  54

## Steps to reproduce - Executing tests around 20 at a time.

**Comment by cgoldberg** [comment]
srsly?  (you can't expect anyone to actually help with a bug report like that)
