### ISSUE TITLE
Wrong description of Ruby Binding Wiki article

### ISSUE THREAD

**Issue by NozomiIto** [SeleniumHQ/selenium#3558]
I found the following samlpe script in the [Ruby Binding Wiki](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings).

```ruby
driver.switch_to.frame "some-frame" # name or id
```

But frame method for Ruby binding accepts only "id" arugment according to [the API document](http://www.rubydoc.info/gems/selenium-webdriver/0.0.28/Selenium%2FWebDriver%2FTargetLocator%3Aframe), and the sample script should be like the following:

```ruby
driver.switch_to.frame "some-frame" # id
```

**Comment by titusfortner** [comment]
updated
