### ISSUE TITLE
AlertsTest case expects AssertionError

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/selenium#3559]
Hi all,

In the test suite, AlertsTest.[testShouldNotHandleAlertInAnotherWindow()](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/AlertsTest.java#L372), there is an [expectation](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/AlertsTest.java#L383) of `AssertionError`, and the test case is ignored for all browsers.

During implementation of HtmlUnitDriver, I was able to throw WebDriverException, but I didn't see in [ErrorCodes](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/ErrorCodes.java) any chance to throw `AssertionError`.

I believe either the test expectation is wrong, or ErrorCodes should be changed to handle `AssertionError`.

Appreciate your feedback.

**Comment by barancev** [comment]
The test fixed.
