### ISSUE TITLE
Cannot pick up folder in the test

### ISSUE THREAD

**Issue by emilylai84** [SeleniumHQ/selenium#3562]
## Meta -
OS: Windows
Selenium Version:  Selenium.WebDriver.3.0.1
Browser:  Chrome

## Expected Behavior -
Selenium can support to identify folder in non-local machine.

## Actual Behavior -
It doesn't regconize the folder

## Steps to reproduce -
It seems "IAllowsFileDetection" only supports for file. Do we have any interface which supports for folder?

## Test code

var js = (IJavaScriptExecutor)Browser.WebDriver;
			var folderToUpload = string.Join("\n", path);
			Console.WriteLine("DragAndDropWithJQuery: " + folderToUpload);
			WaitForJquery();
			js.ExecuteScript(
				"$('body').append('<form><input id=\"dropInput\" type=\"file\" class=\"smoketestFileInput\" webkitdirectory directory multiple /></form>')");
			var element = Browser.WebDriver.FindElement(By.Id("dropInput"));
			var allowsDetection = Browser.WebDriver as IAllowsFileDetection;
			if (allowsDetection != null)
				allowsDetection.FileDetector = new LocalFileDetector();
			element.SendKeys(Path.Combine(Settings.SmokeTestAssetsLocation, @"BulkUploadTestData\DnDEmtyZipFileBulkUpload"));
			js.ExecuteScript(
				"(function() {" +
				"e = $.Event('drop'); " +
				"e.originalEvent = {dataTransfer : { files : $('#dropInput')[0].files } }; " +
				"$('body').trigger(e); console.log('file: ' + $('#dropInput')[0].files.length + ' name: ' + $('#dropInput')[0].files[0]);" +
				"})()");

**Comment by jimevans** [comment]
Unfortunately, this isn't supported by the API, and isn't likely to be implemented.
