### ISSUE TITLE
action.keyDown(Keys.CONTROL) is not working with IE11

### ISSUE THREAD

**Issue by anshulc55** [SeleniumHQ/selenium#3567]
Action class operation keyDown(Keys.CONTROL) is not working with IE11.

I have a scenario in our Test Case, Where I need to select the multiple rows in our UI Grid. So I am trying to do this by using Selenium Action Class. Code is below -

List empolyeeList = new ArrayList;
for (String employeeName : employeeNames) {
empolyeeList.add(driver.findElement(By.xpath("Xpath of employeename")))
}

Actions action = new Actions(driver);
action.keyDown(Keys.CONTROL);
for (String employee : empolyeeList ) {
employee.click();
}
action.keyUp(Keys.CONTROL).build().perform();

Above code is working fine with chrome and firefox but it's not selecting multiple elements on IE11.

Although it starts work if I add the IE driver capability "requireWindowFocus" true. But it will break if browser is minimized or OS is locked.

Browser(s): IE11
Operating System and Version: Window 7
Selenium: 2.53
IEDriverServer: IEDriverServer_Win32_3.1.0

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jimevans** [comment]
This is a known limitation of the IE driver when used with requireWindowFocus to be false. IE appears to ignore the key information passed in the WM_LBUTTONDOWN message. If you can get that to work with the SendMessage API, I will be happy to review a pull request.
