### ISSUE TITLE
Unable to Record the enter text in WYSIWYG or TINYMCE editor

### ISSUE THREAD

**Issue by ankitjain267** [SeleniumHQ/selenium#3569]
## Meta -
OS:  window 7

Selenium Version:  2.9

Browser:  firefox

Browser Version:  

## Expected Behavior -
when user enters something in the free text box(Editor box) then selenium ide should record the text, it should be work same as working for textbox

## Actual Behaviour -
Selenium ide does not record anything when user enters any text in editor

## Steps to reproduce -
Open any application which has editor
Open Selenium ide
Enter text in the editor textbox
Check the selenium ide script

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
