### ISSUE TITLE
Cannot Detect Brwoser Crash in selenium web Driver

### ISSUE THREAD

**Issue by momenimohammad23** [SeleniumHQ/selenium#3571]
Hi 
I want TO Open Some Html File in WebBrowsers with Selenium 
and if its Crashed Close The browser and Find Buggy html files 
But I cant Detect When Browser Crash ...

**Comment by lmtierney** [comment]
Hi, please read the [Bug Report Guide](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and update your issue accordingly
