### ISSUE TITLE
Unable to find WebDriverBackedSelenium in selenium-server-standalone-3.1.0.jar

### ISSUE THREAD

**Issue by deepakgees** [SeleniumHQ/selenium#3573]
I could not find WebDriverBackedSelenium class in selenium-server-standalone-3.1.0.jar.

Since some of my tests are still on RC, i am unable to upgrade to 3.1.0.

Can someone let me know if this class have been moved to a different package or jar.

**Comment by cgoldberg** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L979

**Comment by deepakgees** [comment]
I have already search for this class in package com.thoughtworks.selenium.webdriven but urfotunately this package is not present in selenium-server-standalone-3.1.0.jar 

I even tried searching for it in java client library for webdriver and there also it is not present.

**Comment by barancev** [comment]
Yes, it's a separate artifact now
http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-leg-rc%7C3.2.0%7Cjar

Selenium 3.0 main distribution contains no RC code anymore.

**Comment by deepakgees** [comment]
Thanks a lot, It really helped.

Maybe a link to this on the main selenium page would help others as well.
