### ISSUE TITLE
Selenium 3.1.0 node incorrectly detects own ip address

### ISSUE THREAD

**Issue by Szpadel** [SeleniumHQ/selenium#3577]
## Meta -
OS:  
Windows, Linux
Selenium Version:  
3.1.0
Browser:  
Chrome, Firefox, Edge

Browser Version:  
any

## Expected Behavior -
When selenium node connects to hub, it registers itself with the ip address bound to the same interface that was used to make connection.

## Actual Behavior -
Selenium uses different ip address when host contains more than one network address.
This results with selenium hub to time out when trying to connect back to node, workaround is to force using specific ip address by providing it as -host parameter

## Steps to reproduce -
1. Start selenium hub in on host one in network,
2. On node host make sure there is more that one network interface available (eg. virtualbox host only interface)
3. Start node connection
4. Node is able to register in hub, but it is listed with ip address bound to other interface (that one from virtualbox interface)

**Comment by krmahadevan** [comment]
@Szpadel - Per the documentation [here](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridConfiguration.java#L63-L67), I believe the parameter `-host` was provided for this very reason

**Comment by Szpadel** [comment]
Yes, I know about it, I'm using it as workaround, but in 2.x version it was detected correctly, also this issue was present on multiple machines where it previously worked fine, and now it always picking wrong interface even when I reconfigured interfaces to the other one, therefore a think that it is something induced with 3.0 release

**Comment by diemol** [comment]
For special use cases or topologies, the parameter `remoteHost` is enabled, which allows you to use any given IP/URL for the node to report to the hub.

I'll close this since there is a way to circumvent the described issue in the latest Grid 3.x release.
