### ISSUE TITLE
Exception when starting standalone server for Edge with webdriver.edge.driver option

### ISSUE THREAD

**Issue by zdmeyers** [SeleniumHQ/selenium#3578]
## Meta -
OS:  Win 10

Selenium Version:  3.1.0

Browser:  Edge

Browser Version:  38.14393.0.0

## Expected Behavior -
Like selenium version 2.53.1, be able to start the server standalone jar with the edge driver location included as a system property.
## Actual Behavior -
Exception is thrown when the -Dwebdriver.edge.driver=<path to exe> is included
## Steps to reproduce -

Start selenium-standalone-3.1.0.jar with the following command:
`java -jar selenium-server-standalone-3.1.0.jar -role node -hub <hub here> -browser "browserName=MicrosoftEdge,platform=Win10,maxInstances=1" -Dwebdriver.edge.driver=C:\Jenkins\MicrosoftWebDriver.exe`

See screenshot for crash output. I had to redact the hub URL for company security. This same command worked pefectly fine in selenium 2.53.1.

![selenium-crash](https://cloud.githubusercontent.com/assets/8092276/23372208/4c95b642-fce0-11e6-8bd6-a67782578574.jpg)

**Comment by lmtierney** [comment]
You need to put `-D` options before `-jar` so:

```
java -Dwebdriver.edge.driver=C:\Jenkins\MicrosoftWebDriver.exe -jar selenium-server-standalone-3.1.0.jar -role node -hub <hub here> -browser "browserName=MicrosoftEdge,platform=Win10,maxInstances=1" 
```

**Comment by zdmeyers** [comment]
Worked before with selenium 2.53.1 with the -D option at the end. Was not aware that the ordering of the options mattered for this particular case. Thanks for the information
