### ISSUE TITLE
Windows 7 - Selenium IDE - 2.9.0 - Table view is not available with this format

### ISSUE THREAD

**Issue by britton104** [SeleniumHQ/selenium#358]
I installed the latest server and client/webdriver today and now I am not able to use Selenium IDE. I get the following error message - 

"Table view is not available with this format"  I am not able to use Selenium IDE at all.

**Comment by andreastt** [comment]
Unable to reproduce.  Please provide clearer instructions on how to reproduce, and we might consider reopening.
