### ISSUE TITLE
how to build ios atoms?

### ISSUE THREAD

**Issue by jessyZu** [SeleniumHQ/selenium#3580]
so far as I know
./go //javascript/android-atoms:atoms  can build AndroidAtoms.java ,but how can I build IOSAtoms.java ?

**Comment by lmtierney** [comment]
This is a question and not an issue, please follow the [Bug Reports](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) guidelines when creating an issue. If you have a question, please use [selenium users mailing list](https://groups.google.com/forum/#!forum/selenium-users) or `#selenium` on freenode irc
