### ISSUE TITLE
playback stuck on clickandwait 

### ISSUE THREAD

**Issue by kasireddySedgwick** [SeleniumHQ/selenium#3586]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by kasireddySedgwick** [comment]
Hi there,

Is there any reason why this tkt is closed? perhaps I didn't provide enough details to reproduce this issue

I downloaded (fresh copy) IDE 2.9.1 on Firefox to play with , it records well but during playback  > the playback has been stuck on a input text box and throw this error in log

Unexpected Exception:Error: cross-process JS call failed.&

**Comment by lmtierney** [comment]
Yes, you left the entire issue template empty. Now that you've provided more I can tell you it's a duplicate of #3435
