### ISSUE TITLE
find_element_by_* hangs when element not found

### ISSUE THREAD

**Issue by javixeneize** [SeleniumHQ/selenium#3588]
## Meta -
OS:  
Windows7 (i assume will happens in all versions)
Selenium Version:  
chromedriver=2.27.440174
Browser:  
Chrome 54.0.2840.59

Driver crashes when tries to find an element that doesnt exist. For example:

self.driver.find_element_by_id("aa")

If there is no element called aa, then, the program will freeze until timeout condition is true

**Comment by lmtierney** [comment]
Sounds like you have a high implicit wait set. We'll need some more information in order to diagnose your issue.

**Comment by javixeneize** [comment]
Hi

Yes, the wait set is 30 seconds, but i think that find_element functions
should not wait for that. I think it should return an exception if the
id/name is not found or at least return null, but never wait for the
timeout condition

Thanks

**Comment by lmtierney** [comment]
That is exactly what the implicit wait is for. If you want it to return immediately then don't set an implicit wait
