### ISSUE TITLE
Edge not able to find element by XPath with embedded single-quote

### ISSUE THREAD

**Issue by zdmeyers** [SeleniumHQ/selenium#3589]
## Meta -
OS:  WIn 10

Selenium Version:  3.1

Browser:  Edge

Browser Version:  Latest

## Expected Behavior -
Like Chrome and IE 10+11, Edge should be able to find an element by XPath that contains an embedded single quote (see example).
## Actual Behavior -
Not able to find element.
## Steps to reproduce -

If I try to find an element by this XPath (this is an example that illustrates what the real code is trying to do):

`By.xpath("//a[@href=\"javascript:rs('Hello W\'orld');\"]")`

Edge is not able to find this element as the XPath that gets sent to the driver is looking for the actual text "Hello W\\'orld" instead of "Hello W'orld". This exact setup works in Chrome and IE 10+11. The way that we build an XPath like this in the code is like this:

`By.xpath("//a[@href=\"javascript:rs('Hello W\\'orld');\"]")` (since we have to escape the \ in Java strings) -> `By.xpath("//a[@href=\"javascript:rs('Hello W\'orld');\"]")`

**Comment by zdmeyers** [comment]
I have created a jsfiddle to illustrate the situation: [Fiddle](https://jsfiddle.net/1akh3gxa/)

This jsfiddle works in Edge as seen by the correct output in the dev console. However, the exact same type of XPath does not work when going from Selenium -> Edge for some reason.

**Comment by barancev** [comment]
Please log this issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
