### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds

### ISSUE THREAD

**Issue by prabu6689** [SeleniumHQ/selenium#3592]
C:\Users\Administrator>irb
irb(main):001:0>  require "watir-webdriver"
=> true
irb(main):002:0> $browser=Watir::Browser.new:firefox
Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/socket_lock.rb:38:in `locked'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/firefox/bridge.rb:41:in `initialize'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:50:in `new'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:50:in `for'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.9.9/lib/watir-webdriver/browser.rb:46:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from C:/Ruby193/bin/irb:12:in `<main>'
irb(main):003:0> $browser=Watir::Browser.new:firefox

irb(main):005:0* $browser=Watir::Browser.new:ie
Selenium::WebDriver::Error::WebDriverError: unable to connect to IE server withi
n 30 seconds
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/s
elenium/webdriver/ie/server.rb:68:in `start'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/s
elenium/webdriver/ie/bridge.rb:52:in `initialize'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/s
elenium/webdriver/common/driver.rb:54:in `new'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/s
elenium/webdriver/common/driver.rb:54:in `for'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.47.1/lib/s
elenium/webdriver.rb:86:in `for'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.9.9/lib/watir
-webdriver/browser.rb:46:in `initialize'
        from (irb):5:in `new'
        from (irb):5
        from C:/Ruby193/bin/irb:12:in `<main>'

**Comment by p0deje** [comment]
Please read this and update your issue accordingly: https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports

**Comment by titusfortner** [comment]
@prabu6689 - you need to update to using the latest code in order to file a bug report. Many things have changed or have been fixed (including support for Firefox 48+). The latest Watir code is in `watir` not `watir-webdriver`, and the latest `selenium-webdriver` gem is 3.2.2. Let us know if you have any issues after updating.

**Comment by prabu6689** [comment]
Thanks a lot...will update and confirm.

Regards,

John. A
