### ISSUE TITLE
Compilation error after update Function/Predicate imports from Guava to Java 8

### ISSUE THREAD

**Issue by evertones** [SeleniumHQ/selenium#3596]
I could not use the 3.1.0 and 3.2.0 versions. It breaks the compilation of this code from my tests (in Scala):

    def explicitWait[T](condition: ExpectedCondition[T], duration: Duration = Configuration.TIMEOUT_SHORT)(implicit driver: WebDriver): Unit = {
        val wait = new WebDriverWait(driver, duration.getSeconds)
        wait.until(condition)
    }

The error is:

    DomService.scala:100: type mismatch;
        found   : com.google.common.base.Function[org.openqa.selenium.WebDriver,T]
        required: java.util.function.Function[_ >: org.openqa.selenium.WebDriver, ?]
                wait.until(condition)

As far as I could see, recently there was a change in `FluentWait` class where the `Function`, `Predicate` and `Supplier` imports were changed to use Java 8, instead of Guava.

It seems that the `ExpectedCondition` class didn't have its imports updated for the class `Function`, which is still using Guava.

Once `WebDriverWait`extends `FluentWait`, this should be the reason I'm getting the error.

The change for `FluentWait` is [here](https://github.com/SeleniumHQ/selenium/commit/b2aa9fd534f7afbcba319231bb4bce85f825ef09#diff-84f235517bcdcf4ccd574208e8d02c9e).

**Comment by lmtierney** [comment]
Have you tried updating Guava to verison 21? https://github.com/SeleniumHQ/selenium/commit/8c03df6b79831c03bb1f9c13b6c5ee43008ebc03

**Comment by evertones** [comment]
@lmtierney, thank you for your response.

I haven't seen that comment before.
I'll try and tell you the results.

Thank you.

**Comment by evertones** [comment]
Updating Guava to version 21 solved the problem.
Thank you @lmtierney.
