### ISSUE TITLE
C#: FirefoxDriver in legacy mode demands geckodriver to be in the PATH

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#3597]
In C# binding, FirefoxDriver in legacy mode demands geckodriver to be in the PATH. It does not use it to drive the browser, but it fails if geckodriver is not available.

```
FirefoxOptions options = new FirefoxOptions();
options.UseLegacyImplementation = true;
driver = new FirefoxDriver(options);
```

**Comment by jimevans** [comment]
Fixed in 5b04ef6.
