### ISSUE TITLE
Cannot find FluentWait class in selenium 3.1.0

### ISSUE THREAD

**Issue by yanurag** [SeleniumHQ/selenium#3598]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -

Using selenium version of 3.1.0 with java.
Cannot find FluentWait class. Added latest version of guava 21.0 also but still it says it cannot be resolved to a type.

**Comment by barancev** [comment]
Where are you looking for this class and can't find it? What artifact exactly?

**Comment by lmtierney** [comment]
Sounds like a symptom of #3568

**Comment by barancev** [comment]
No response
