### ISSUE TITLE
screenshots file path separator not correct on Mac

### ISSUE THREAD

**Issue by ppzzss** [SeleniumHQ/selenium#3600]
## Meta -
OS:  
OSX
Selenium Version:  
3.2.0  (selenium-server-standalone-3.2.0.jar)
Browser:  
FireFox

Browser Version:  
45.4.0

## Expected Behavior -
screenshots file locate in test-output
## Actual Behavior -
screenshots file located in project root path with wrong file path separator, like:
eduCloud\test-output\html\screenshots\WebDrivertest31488667211537.png
\ is the file path separator on Windows,
/ is the file path separator on Mac.

## Steps to reproduce -
run any failed testcase, and check the screenshot file on Mac

**Comment by lmtierney** [comment]
`eduCloud\test-output\html\screenshots\` is coming from your end. Selenium does not know about your tests. The server does take screenshots on an exception but it does not save them to disk.
