### ISSUE TITLE
No window found

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#3601]
## Meta - Exception in thread "main" org.openqa.selenium.NoSuchWindowException: No window found (WARNING: The server did not provide any stacktrace information)
OS:  Windows 7
Selenium Version:  2.53.1
Browser:  Internet Explorer 
Browser Version:  11.0.9600.17843

## Actual Behavior - giving errorException in thread "main" org.openqa.selenium.NoSuchWindowException: No window found (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.01 seconds
Build info: version: '2.53.1', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'CTND1147', ip: '172.17.20.18', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:2578/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 645ff9d9-12ca-431b-af80-15ffa12d4f3a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:1015)
	at com.ssts.OpenBrowser.main(OpenBrowser.java:23)

## Steps to reproduce -
Open Url:-
               WebDriver driver = new InternetExplorerDriver();
		driver.get("http://www.cairnscentral.com.au/");
		Set<String> oldWindows = driver.getWindowHandles();
Click:- Contact Us (at button right side of the page)
		driver.findElement(By.xpath("//div[4]/ul/li[1]/a")).click();
		Thread.sleep(10000);
		Set<String> allWindows = driver.getWindowHandles();
		//allWindows.removeAll(oldWindows);
		for (String string : oldWindows) {
			System.out.println(string);
		}
		String newWindow = oldWindows.iterator().next();
		driver.switchTo().window(newWindow);
TypeText: On FirstName EditBox
		driver.findElement(By.xpath("(//*[@name='firstname'])")).sendKeys("ANY STRING");

**Comment by jimevans** [comment]
I'm confused by what you expect the behavior to be. In the pseudocode you posted in the steps to reproduce, you're looping through the set of original window handles, which doesn't include the new window after the click. Moreover, it looks like even if you were using the list of new window handles after the click, you're succumbing to the fallacy that the list of window handles are returned in some sort of order. They are not. There is no guarantee that windowHandles[0] will be the first window opened, nor will windowHandles[windowHandles.length - 1] necessarily be the last one opened. You'll need to be more clear about what you expect to happen here.

**Comment by jimevans** [comment]
Closing due to lack of response from reporter.
