### ISSUE TITLE
Can't find related product for selenium webdriver on the bugreport.apple.com

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3603]
Please explain the correct way to post bugs for safari webdriver.
There is no product webdriver (or selenium or safaridriver) on the bugreport.apple.com.

I posted an issue with webdriver to the "Safari Technology Preview" product on the 24th of February and it still in Open status without any comments. 
But here I got answer the same day https://github.com/SeleniumHQ/selenium/issues/3593. 

Thanks.

**Comment by lmtierney** [comment]
Safaridriver is part of Safari now, you would create bugs against Safari or Safari Technology Preview like you already did. We do not have any control over how Apple handles their bugs so you'd have to ask them about it.
