### ISSUE TITLE
Some sessions abandoned after loading the Log in page in Internet Explorer-11 using with Selenium 2.53.1 Grid version

### ISSUE THREAD

**Issue by Rajktha** [SeleniumHQ/selenium#3605]
## Meta -
OS:  
 Windows 7
Selenium Version:  
 2.53.1
Browser:  
Internet Explorer-11

I am using Selenium Grid with following configuration in pom.xml file:
parallel - classes
threadCount - 2
forkcount-0
 I have a 8 core machine with 16 GB RAM. There is no issue with IE sessions - opened 16 sessions at a time, but 3 or 4 sessions staying in Login page once it entered URL.

Browser Version:  
 IE-11 (64-bit)

## Expected Behavior -
All the sessions it should execute whatever story assigned to them

## Actual Behavior -
Some of the sessions staying in Log-in page
## Steps to reproduce -
Execute scripts with Selenium Grid using 2.53.1 Version in IE-11 browser

**Comment by Rajktha** [comment]
It is Executed fine with Chrome and Firefox using Selenium Grid

**Comment by krmahadevan** [comment]
@Rajktha - It would be great if you could please help add some debug information. With whatever you have provided so far, its a bit difficult to even take a wild guess at what could be wrong. Whatever you can think of as debug information (Node debug logs, IEDriverServer logs from the remote node, test logs etc.,) please help add them here.

**Comment by lmtierney** [comment]
Please read [Bug Reporting](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and update accordingly
