### ISSUE TITLE
Support W3C WebDriver Set Timeouts format

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#3607]
From what I can tell, all Selenium client bindings apart from C# use an incorrect data structure as a body when setting timeout durations:

```js
{
  type: "implicit",
  ms: 42,
}
```

* Node.js: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L1469
* Ruby: https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/w3c_bridge.rb#L138
* Java: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L834
* Python: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L676

The [Set Timeouts](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-set-timeouts) command expects a data format like this:

```js
{
  implicit: 42,
}
```

New in W3C WebDriver is that multiple timeout durations can be set at the same time:

```
{
  implicit: 123,
  pageLoad: 456,
  script: 789,
}
```

Note that driver implementations will enumerate the own properties of the dictionary, so an unknown field is likely to error. For example, if a client passes `{foo: 1, implicit: 2}`, this is considered an error scenario by the driver.

See https://github.com/mozilla/geckodriver/issues/511 filed on geckodriver.

**Comment by shs96c** [comment]
Assigned folks who are meant to look after this stuff to it

**Comment by jleyba** [comment]
@andreastt what version of geckodriver does this apply to?  I'm testing 0.14.0 and `{implicit:number}` fails while `{type:string, ms:number}` succeeds.

Here are some HTTP logs from my test:

```sh
[2017-03-08T05:49:23Z] [FINER] [webdriver.http.Executor] >>>
POST /session HTTP/1.1
accept: application/json; charset=utf-8

{"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{}}}
<<<
HTTP/1.1 200
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 483
date: Wed, 08 Mar 2017 05:49:23 GMT

{"sessionId":"23dbe72d-ffce-0144-aa2e-eec2c27edc1e","value":{"XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","acceptSslCerts":false,"appBuildId":"20170125094131","browserName":"firefox","browserVersion":"51.0.1","command_id":1,"platform":"DARWIN","platformName":"darwin","platformVersion":"16.4.0","processId":58064,"proxy":{},"raisesAccessibilityExceptions":false,"rotatable":false,"specificationLevel":0,"takesElementScreenshot":true,"takesScreenshot":true,"version":"51.0.1"}}
[2017-03-08T05:49:23Z] [FINEST] [webdriver.http] Translating command: setTimeout
[2017-03-08T05:49:23Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session/:sessionId/timeouts"}
[2017-03-08T05:49:23Z] [FINER] [webdriver.http.Executor] >>> POST /session/23dbe72d-ffce-0144-aa2e-eec2c27edc1e/timeouts
[2017-03-08T05:49:23Z] [FINER] [webdriver.http.Executor] >>>
POST /session/23dbe72d-ffce-0144-aa2e-eec2c27edc1e/timeouts HTTP/1.1
accept: application/json; charset=utf-8

{"implicit":1000}
<<<
HTTP/1.1 400
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 1071
date: Wed, 08 Mar 2017 05:49:23 GMT

{"error":"invalid argument","message":"Missing 'type' parameter","stacktrace":"stack backtrace:\n   0:        0x1063908be - backtrace::backtrace::trace::had1fe133e10f4f84\n   1:        0x106390ffc - backtrace::capture::Backtrace::new::hea6d366cd875d5b7\n   2:        0x1063808db - _$LT$webdriver..command..TimeoutsParameters$u20$as$u20$webdriver..command..Parameters$GT$::from_json::h1048d4c3b6715f73\n   3:        0x10633cc41 - _$LT$webdriver..command..WebDriverMessage$LT$U$GT$$GT$::from_http::h3808a0e4d9035e57\n   4:        0x10634d3af - _$LT$webdriver..server..HttpHandler$LT$U$GT$$u20$as$u20$hyper..server..Handler$GT$::handle::h6d174251ff71fe10\n   5:        0x1063278d1 - std::panicking::try::do_call::hba7b1bc2a6ca94e2\n   6:        0x10649ce4a - __rust_maybe_catch_panic\n   7:        0x10633a194 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h975d4e3beb5f6933\n   8:        0x10649b0c4 - std::sys::imp::thread::Thread::new::thread_start::ha102a6120fc52763\n   9:     0x7fffc07faaaa - _pthread_body\n  10:     0x7fffc07fa9f6 - _pthread_start"}
[2017-03-08T05:49:23Z] [FINEST] [webdriver.http] Translating command: setTimeout
[2017-03-08T05:49:23Z] [FINEST] [webdriver.http] Building HTTP request: {"method":"POST","path":"/session/:sessionId/timeouts"}
[2017-03-08T05:49:23Z] [FINER] [webdriver.http.Executor] >>> POST /session/23dbe72d-ffce-0144-aa2e-eec2c27edc1e/timeouts
[2017-03-08T05:49:23Z] [FINER] [webdriver.http.Executor] >>>
POST /session/23dbe72d-ffce-0144-aa2e-eec2c27edc1e/timeouts HTTP/1.1
accept: application/json; charset=utf-8

{"type":"implicit","ms":1000}
<<<
HTTP/1.1 200
connection: close
content-type: application/json; charset=utf-8
cache-control: no-cache
content-length: 2
date: Wed, 08 Mar 2017 05:49:23 GMT

{}
```

**Comment by AutomatedTester** [comment]
python landed in 01e76ca

**Comment by lmtierney** [comment]
ruby fixed in 32a8970

**Comment by jleyba** [comment]
Updated JS for the spec (which geckodriver _does not_ follow for page load, details added to mozilla/geckodriver#511)

**Comment by andreastt** [comment]
@jleyba Sorry for my late reply. The conforming Set Timeouts/Get Timeouts commands are in geckodriver 0.15.0.

Thanks for your issue on `{"page load": 1}`. I thought that was fixed, but I will look into it.

**Comment by lmtierney** [comment]
@andreastt I believe it works in Nightly but not current stable

**Comment by jafarshaikh** [comment]
I am not sure whether its internal communication or for public. But look like your page - your comment does not help user like me.  I am facing issue while launching the FF Browser. It launch but does not open the address provided. Not sure I am pasting correctly or not.

**Comment by andreastt** [comment]
The change to align Marionette with W3C WebDriver was backed out in https://bugzilla.mozilla.org/show_bug.cgi?id=1342162 due to test failures. I intend to fix it up soonish.

**Comment by fredrikholm** [comment]
For what it's worth: I get this error in my C# project using Firefox:
"Missing 'type' parameter (IndexOutOfBounds)"

**Comment by andreastt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1342162 has now landed and been uplifted to Firefox 53 and 54.

@fredrikholm That means you’re either using outdated C# bindings or that the C# bindings have not been updated to be spec compliant yet.

**Comment by andreastt** [comment]
@fredrikholm From reading https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteTimeouts.cs, it looks like the latest .NET bindings are in line with the specification. You should update.

**Comment by barancev** [comment]
Fixed in Java binding by 3c808f66757076fcbe658fc4f6d5934e1616156a
Fixed in server by ce06f68fb81162c4b028c3bcbf85b7a86249fc36

**Comment by prashant08** [comment]
When I use below code in C#, the test fail and below is the message when evaluating the value of driver.Manage().Timeouts().ImplicitWait 

 driver.Manage().Timeouts().ImplicitWait = waitTime;

* System.NotImplementedException: Driver instance must comply with the W3C specification to support getting timeout values.

**Comment by pianistprogrammer** [comment]
Use this, worked for me

`driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);`
