### ISSUE TITLE
Selenium 3.2.0 - IEDriverServer - Setting ignoringProtectedmode true from my driver is not working

### ISSUE THREAD

**Issue by pedkoz** [SeleniumHQ/selenium#3615]
## Meta -
OS:  
Windows
Selenium Version:  
3.2.0
Browser:  
Internet Explorer 11

Browser Version:  
11 (32 Bit)

## Expected Behavior -
I expect when i have enabled manually the protected mode in my Internet explorer and i set my driver for disabling this... it has to run fine and with this mode disabled...
 because i think that you don't need to depened of a manual setting... i understand if I disabled this mode from: ignoreProtectedModeSettings or ieOptions.IntroduceInstabilityByIgnoringProtectedModeSettings my driver is going to run with this feature disabled... 

## Actual Behavior -
However it is not so... I did so and when i run my driver with that setting for ignoring the protected mode settings when I run my driver, all my tests are failed, because the behaviour of the driver is not correct... it doesn't wait for the load page... but If I disabled manually the protected mode all works fine...

In the file attached you have my code for local and remote and the log when i send to remotedriver...

You can see two strange lines:
D 2017-03-07 15:26:49:607 BrowserFactory.cpp(146) Ignoring Protected Mode Settings: 1
D 2017-03-07 15:26:49:609 BrowserFactory.cpp(152) Has Valid Protected Mode Settings: 0

i am not sure, but i have the feeling i say ignore the protected mode, but it use the protected mode unless i disabled this manually from my Internet Explorer.

## Steps to reproduce -
Prerequirement:
Enable the protected mode in the IE11. It is necessary, for reproducing scenario.

1. Run IEDriverServer.exe from a console CMD.
2. Run your test by remotedriver to the http://127.0.0.1:5555 with the capability: 
            capabilities.SetCapability("ignoreProtectedModeSettings", true);
If you run in local i have the same trouble and the option is:
ieOptions.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
3- Run test.

[IEDriverserver.txt](https://github.com/SeleniumHQ/selenium/files/824707/IEDriverserver.txt)

**Comment by jimevans** [comment]
It sounds like the bug you are reporting is either (1) that you have to manually set the IE Protected Mode settings manually, or (2) if you don't set the Protected Mode settings, and use the capability, the driver doesn't behave exactly as you'd expect. This is entirely by design, for technical reasons, documented in the wiki and in blog posts all over the net. It cannot and will not be fixed.

**Comment by pedkoz** [comment]
Yes, when i disable it manually all execution work, the issue is related about the capabilities not work, if i send in capability for disabling the mode protected it is not used by the driver...

So if it is so by technical reason, i think we should not be able to send a capability disabling that mode to IEDriverServer, because they are not going to be used....

Regards,

**Comment by jimevans** [comment]
You've misunderstood the purpose of the capability. The capability doesn't set Protected Mode settings; it simply removes the check that they're correctly set. The manual configuration of the browser is required, as previously explained. In fact, early versions of the driver simply threw an exception if Protected Mode was not properly set, and no such capability existed. However, some overzealous IT departments do not allow users to modify the Protected Mode settings. What, then, would your solution be for those users? The project's solution is to disable its own check via a capability. The capability does not change the behavior of the browser one iota, nor was it ever intended to. Rather, it simply bypasses the driver's intrinsic check that the browser is properly configured.

**Comment by pedkoz** [comment]
Hi, jimevans,

Ok, i understand you. However, what i wanted to say too, it is related about what you say..." However, some overzealous IT departments do not allow users to modify the Protected Mode settings. What, then, would your solution be for those users? The project's solution is to disable its own check via a capability"

What i say, if i set to true the capability:
ignoreProtectedModeSettings or ieOptions.IntroduceInstabilityByIgnoringProtectedModeSettings

The result is that my driver fails giving to me an error about a wrong setting with protected mode included in that case > It doesn't ignore the setting for that.... and i am understanding to you that driver should not check that when capability is true... So i am not able to do that with capability, only way that i have is to set the browser correctly and not use the capabitliy, it is undifferent in my case.... 

And the trouble what i have in my company is when I restart the computer settings in browser come back to default... so by that i was interested in doing the setting by driver... if it is not possible not problem, however that capability not ignore the settings in my case...

Regards,

**Comment by pavoltravnik** [comment]
I completely agree with @pedkoz. It used to work, for me, but now, when I install it on different PC, exception is not ignored and it always close the IE browser.
