### ISSUE TITLE
selenium-webdriver 3.3 broken with the latest release of geckodriver (0.14)

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#3616]
https://github.com/SeleniumHQ/selenium/commit/ccc442ea1ecaacfdd71e5110cdd81976b76cacbe broke the use of selenium-webdriver with geckodriver 0.14 (latest current release) since the sessionId returned is not wrapped in `value` when creating a new session.

**Comment by twalpole** [comment]
@titusfortner  Seems like the tests should have failed, and 3.3 not have been released?

**Comment by lmtierney** [comment]
@twalpole mozilla refused to release geckodriver 0.15 until selenium released 3.3. We are waiting for them to do so today still

**Comment by twalpole** [comment]
@lmtierney Ah -- ok -- catch 22 then.

**Comment by titusfortner** [comment]
Chickens and Eggs: https://botbot.me/freenode/selenium/2017-03-06/?msg=81998419&page=3

**Comment by lmtierney** [comment]
@twalpole geckodriver release is pushed to tomorrow, they are fixing an issue with the cookie return value quick

**Comment by lmtierney** [comment]
Leaving this open until geckodriver `0.15` is released... sorry for the inconvenience!

**Comment by barancev** [comment]
0.15 is available

**Comment by twalpole** [comment]
geckodriver 0.15 fixed the sessionId issue but broke a few other things around select elements and the inability to call methods define in the page with execute_script - investigating
