### ISSUE TITLE
standalone server 3.3.0 /wd/hub/status is broken

### ISSUE THREAD

**Issue by mach6** [SeleniumHQ/selenium#3618]
## Meta -
OS:  All

Selenium Version:  3.3.0 

Browser:  NA

Browser Version:  NA

## Expected Behavior -
http://localhost:4444/wd/hub/status is returned without error

## Actual Behavior -
HTTP 500 and invalid status is returned

## Steps to reproduce -
launch selenium-server-standalone-3.3.0.jar with the default role
`java -jar selenium-server-standalone-3.3.0.jar`
hit `/status` on the `DriverServlet`
`curl -v http://localhost:4444/wd/hub/status`
observe the HTTP status code is 500 and the document body is 
```json
{"state":"unknown error","sessionId":null,"hCode":841816987,"value":{"localizedMessage":"wrong number of arguments","cause":null,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"suppressed":[],"message":"wrong number of arguments","hCode":1378782565,"class":"java.lang.IllegalArgumentException"},"class":"org.openqa.selenium.remote.Response","status":13}
```

**Comment by mach6** [comment]
@shs96c fyi broken due to the `ResultConfig.java` change in this commit - https://github.com/SeleniumHQ/selenium/commit/179bd935fe25a620186caa9674b6c2f75a4942a9#diff-252a75cbd6399f763ef50ec3965d3cbdR46

**Comment by mach6** [comment]
fixed with https://github.com/SeleniumHQ/selenium/commit/3fe26349b449824f2804cea06e1d7cd5d01c9e10 for the next release.

**Comment by nickcmaynard** [comment]
@mach6 Do we have an outlook for the next release?

**Comment by lmtierney** [comment]
@nickcmaynard Soon, hopefully today

**Comment by nickcmaynard** [comment]
@lmtierney TYVM
