### ISSUE TITLE
Responsive Design Bug?

### ISSUE THREAD

**Issue by rbolton240** [SeleniumHQ/selenium#362]
I am trying to screen capture a web page (www.constructionequipment.com) using PhantomJSDriver, which works fine locally on my development box but when ran from a web server (without a display) does not properly handle detection of the screen due to the responsive nature of the web page. 

What I am seeing happen (on the server) is the horizontal navigation bar at the top of the page always appears to display in a mobile mode (for responsive design) when screen captured, this is regardless of any width that I force the browser window to. 

What I am seeing happen (on my development box) is the responsive menu adjusts appropriately as I resize the window programmatically. No issue here. 

I was looking at the CSS for www.constructionequipment.com and found a media query being used ("@media" screen) which provides conditional logic for which CSS block to use based on the screen size.

I am thinking that the PhantomJS Driver is (in the case of running on the server) not properly detecting the screen width (since there is no display). 

It should be noted that other responsive websites like CNN.com for example, work fine. 

Has anyone else encountered this issue? 

Thanks in advance.

-----------------------------------------------------

Below is an attached screen capture of a dropdown menu in a wide browser window (which should be using a navigation bar instead). This was captured by my application running in a server environment and illustrates the problem I am seeing. My application works fine when ran locally.

You can go to constructionequipment.com and horizontally resize the window to see how it should behave. 

![wide with mobile menu](https://cloud.githubusercontent.com/assets/6028190/6803608/2f43c596-d20f-11e4-8319-0f86a71bda1c.Jpeg)

-----------------------------------------------------

Custom .NET/C# application using...

Selenium WebDriver API .NET Bindings
Runtime Version v4.0.30319
Version 2.44.0.0

phantomjs.exe

Development machine: Windows 7

Server machine: Win Server 2008 R2

.NET version v4.0.30319

-----------------------------------------------------

Information about CSS @Media queries
http://stackoverflow.com/questions/4189868/what-does-media-screen-and-max-width-1024px-mean-in-css

**Comment by lukeis** [comment]
This would be a bug for either the [phantomjs](https://github.com/ariya/phantomjs) project or it's webdriver implementation [ghostdriver](https://github.com/detro/ghostdriver)

There's nothing the "selenium" project can help with here.
