### ISSUE TITLE
Firefox maximize and sendKeys does not work with GeckoDriver on Selenium 3.1.0

### ISSUE THREAD

**Issue by iamjamalkhan** [SeleniumHQ/selenium#3623]
OS:
RHEL7-64 bit
Selenium Version:
3.1.0
Browser:
Firefox

Browser Version:
51.0.1

Expected Behavior -

Once the driver is initialized with Geckodriver, the window loads the url and should maximize and accept keys F11 and F5. Here is the code
_driver.get( url );
By by = get_element( "global_nav" );
_driver.manage().window().maximize();
_driver.findElement( by ).sendKeys( Keys.F11 );
sleep( 2000 );
_driver.findElement( by ).sendKeys( Keys.F5 );

Actual Behavior -

Neither the Firefox window maximizes nor sendKeys is having any impact.

Steps to reproduce -

Use Firefox with GeckoDriver to initialize the driver.
Load a url and try to maximize with above code.
Then send two keys F11 and F5 using the above code.

I already logged a bug with Mozilla Firefox please refer the below link for their response
mozilla/geckodriver#475 (comment)

Here is the bug id for reference too
https://bugzilla.mozilla.org/show_bug.cgi?id=1344299

Could you please let me know how can I access those command mentioned in the reply through Selenium Java api.

**Comment by iamjamalkhan** [comment]
Can SomeBody Please respond??

**Comment by barancev** [comment]
Responded in geckodriver tracker

**Comment by iamjamalkhan** [comment]
Hi ,

I am sorry but I don't see any response from your side in geckodriver tracker that I logged in. Could you please let me know which tracker are you talking about?
