### ISSUE TITLE
selenium-webdriver@3.3.0 doesn't support geckodriver@0.15.0

### ISSUE THREAD

**Issue by zenonwch** [SeleniumHQ/selenium#3625]
## Meta -
OS:  
Mac OS X Sierra
Selenium Version:  
3.3.0
Browser:  
Firefox
Browser Version:  
52.0
Geckodriver Version:
0.15.0

## Expected Behavior -
Session created.

## Actual Behavior -
Uncaught WebDriverError: Unable to parse new session response: {"value": {"sessionId":"bf9bc942-e313-7246-a54b-bb5f739b812b","value":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0","moz:accessibilityChecks":false,"moz:processID":30351,"moz:profile":"/var/folders/xd/x3tby4c909q849n44sflt82h0000gn/T/rust_mozprofile.4yiilqsDVBy0","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.4.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}}

**Comment by lmtierney** [comment]
What bindings are you using?

**Comment by zenonwch** [comment]
javascript

**Comment by lmtierney** [comment]
This is true, javascript has a couple updates needed to use geckodriver 0.15

**Comment by allspat** [comment]
is the same case with 0.16 as well. Does not seem its fixed yet !!

**Comment by amritay** [comment]
Facing the same issue with geckodriver 0.19.0.

Is there any update on this?

**Comment by rakeshkmr516** [comment]
Facing the same issue with geckodriver 1.10.0 version

Is there any update on this?
