### ISSUE TITLE
javascript interface not working with setTimeout

### ISSUE THREAD

**Issue by Soarez** [SeleniumHQ/selenium#363]
e.g.

```javascript
var fs = require('fs');
var webdriver = require('selenium-webdriver');

var remote = new webdriver
  .Builder()
  .withCapabilities({ browserName: 'phantomjs' })
  .build();

remote.manage().window().setSize(1024, 900);

remote.get('http://google.com');

setTimeout(function() {
  remote.executeScript('return true').then(log, onError);
}, 500);

function log(res) { console.log(res); }

function onError(e) { throw e; }
```

This small program gets stuck and never ends, but it we move the line `remote.executeScript('return true').then(log, onError);` out of the `setTimeout` callback then it starts working as expected.

Shouldn't the `executeScript` call schedule the operation regardless of when it is called?

I'm using selenium-webdriver@2.45.1

**Comment by GCheung55** [comment]
++

The same issue occurs if the setTimeout wraps `remote.get` in my scenario. I'm using selenium-webdriver@2.45.1 in Buster.JS's test runner, which is possible that webdriver code is executed in a setTimeout.

**Comment by GCheung55** [comment]
I did some digging and so far I've only determined that reverting back to https://github.com/SeleniumHQ/selenium/blob/ecfefd32aba140f79f62986b0c7944c197c3ff03/javascript/webdriver/promise.js allows the code to continue.

**Comment by jleyba** [comment]
Problem is the flow gets confused and deadlocks itself when a command is scheduled asynchronously when there's a dependency on the running task.  Basic repo case:

    var selenium = require('selenium-webdriver');
    var flow = selenium.promise.controlFlow();

    var task1 = flow.execute(function() {
      console.log('Inside task 1:\n' + flow);
      return selenium.promise.delayed(10);
    }, 'task 1');

    setTimeout(function() {
      flow.execute(function() {
        console.log('Inside task 2:\n' + flow);
        return task1;  // Create dependency on task 1 result.
      }, 'task 2');
      console.log('Scheduled task 2:\n' + flow);
    }, 0);

    flow.once('idle', function() {
      console.log('All done');
    });

Output:

    Inside task 1:
    ControlFlow::1
    | Frame::4
    | | (pending) Task::3<task 1>
    | | | (active) Frame::5
    Scheduled task 2:
    ControlFlow::1
    | Frame::4
    | | (pending) Task::3<task 1>
    | | | (active) Frame::5
    | | | | Task::12<task 2>
    Inside task 2:
    ControlFlow::1
    | Frame::4
    | | (pending) Task::3<task 1>
    | | | Frame::5
    | | | | (pending) Task::12<task 2>
    | | | | | (active) Frame::13

Need to update the flow to differentiate between this and legit sub-commands.
