### ISSUE TITLE
Selenium 3.3 is not mentioned on download page

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#3634]
The Selenium downloads page does not mention Selenium 3.3. This is quite crucial, since we are getting numerous issue reports on the geckodriver project about this. geckodriver 0.15.0 is incompatible with all earlier versions of Selenium.

http://www.seleniumhq.org/download/

**Comment by lmtierney** [comment]
I can update the site, but standalone users will have to wait for 3.3.1 (hopefully tomorrow) for a working version

**Comment by lmtierney** [comment]
@andreastt the site is updated

**Comment by andreastt** [comment]
@lmtierney Thanks!

**Comment by michelleXIE2014** [comment]
@lmtierney when will 3.3.1 be available to us on the seleniumHQ download page? thank you.

**Comment by lmtierney** [comment]
@michelleXIE2014 we're having issues updating the site, you can always get the latest by going directly to here: http://selenium-release.storage.googleapis.com/index.html (under 3.3)

**Comment by michelleXIE2014** [comment]
ha, thank you @lmtierney :)
