### ISSUE TITLE
Option at selenium console to clear hub queue. 

### ISSUE THREAD

**Issue by junalmeida** [SeleniumHQ/selenium#3637]
## Meta -
OS:  Windows 2012
Selenium Version:  3.2.0
Browser:  N/A

Selenium hub does not clear queue after crashed (or timed out) tests. 
So, provide a way to clear the queue without need to restart. 

If possible, provide a way to re-register node using its console.

**Comment by krmahadevan** [comment]
@junalmeida - It would be great if you could please help add a bit more of a context. When you say crashed (or) timed out tests, what do you mean ? Are you talking about those sessions for which a delete session never got called and those session Ids are still stuck in the Grid internals ?

> If possible, provide a way to re-register node using its console
Are you referring to just cleaning up the Grid internals with the node info and putting in a new registration request ? Or are you also referring to killing the node as well ?

**Comment by junalmeida** [comment]
Actually both. I saw both of session ids stuck in grid internals and delete session that never gets called.  
My scenario have only one node with only one allowed instance of browser, and I cannot start a new test session if the last test run has crashed (e.g never call driver.Quit())  

Yes, just clean up the grid hub internals. If its possible to clean up node internals and re-register without killing it I guess that its better.

I got a situation of a stuck node session, I use the node console to clean the  session, but it didn't inform  the hub that its not busy anymore (hub console still shows that its busy) 

My idea is to provide more control using hub and node console. Here at my test environment I schedule a batch file that kills hub and node every 3 hours because I have no way to reset it manually using the console if something odd happens at the last test run.

**Comment by krmahadevan** [comment]
@junalmeida - You can do this on your own today and don't need this to be implemented in the Grid.

* To start off, you create a Servlet that extends `org.openqa.grid.web.servlet.RegistryBasedServlet` (we need this because only then do we get access to the `org.openqa.grid.internal.Registry` object which maintains all the internals )
* You then built this servlet to look like something as below (The below code is just barebones, so please feel free to enhance it to add the UI components as well, for getting the session id from the user and also the session termination reason)
* Inject this servlet into the Hub as detailed [here](http://www.seleniumhq.org/docs/07_selenium_grid.jsp#customizing-the-grid)

That should do. You now have a servlet at the Hub end which when invoked would show you a UI wherein you can input the session id (which you can retrieve from `org.openqa.selenium.remote.RemoteWebDriver#getSessionId` ) and also the reason for the session termination and post this back into the same servlet (My example shows this as a GET, but it should give you he idea)

```java
package com.rationaleemotions.webdriver;

import org.openqa.grid.internal.ExternalSessionKey;
import org.openqa.grid.internal.Registry;
import org.openqa.grid.internal.SessionTerminationReason;
import org.openqa.grid.internal.TestSession;
import org.openqa.grid.web.servlet.RegistryBasedServlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class SessionTerminatingServlet extends RegistryBasedServlet {
    public SessionTerminatingServlet(Registry registry) {
        super(registry);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String sessionId = req.getParameter("sessionId");
        if (sessionId != null && !sessionId.trim().isEmpty()) {
            ExternalSessionKey key = new ExternalSessionKey(sessionId);
            TestSession sessionToDelete = getRegistry().getSession(key);
            //Here SessionTerminationReason can be chosen as anything. In fact you can have your console list
            //the reasons as a drop down and have this also fetched from the user.
            getRegistry().terminate(sessionToDelete, SessionTerminationReason.BROWSER_TIMEOUT);
        }
    }
}

```

**Comment by junalmeida** [comment]
Thank you for your suggestion, but still think that this should be a native feature. 
I'm not a java developer, and I use selenium to automate ui tests of a different platform. 

Guess that no matter what wrong code i use to connect to hub, it cannot go to an unrecoverable state. Don't think that this is the case of an extension, but a bug fix at selenium node/hub core.

**Comment by junalmeida** [comment]
Here is a more detailed report.  For some reason, a test has failed at the node due to some html element not found. Totally expected. The problem is: After that, the subsequent tests, that starts new sessions all started to fail reporting time out. See:

The C# test stacktrace: 
```
Initialization method Angular.Client.Planos.Tests.Features.TabuaBiometrica.AprovarTabuaBiometrica._AprovarTabuaBiometricaTest.SetUp threw exception. OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://ihmtzhubsell.drmtz.com.br:4444/wd/hub/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.
Stack Trace:
Failed   DeveReprovarTabuaBiometrica (Data Row 0)
at System.Net.HttpWebRequest.GetResponse()
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
--- End of inner exception stack trace ---
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
at IcatuSeguros.Infrastructure.Client.Tests.DriverManager.CriarDriver() in E:\a\b1a\_work\2\s\IcatuSeguros.Infrastructure.Client.Tests\DriverManager.cs:line 173
at IcatuSeguros.Infrastructure.Client.Tests.DriverManager.ResolverDriver() in E:\a\b1a\_work\2\s\IcatuSeguros.Infrastructure.Client.Tests\DriverManager.cs:line 94
at Angular.Client.Planos.Tests.Features.TabuaBiometrica.AprovarTabuaBiometrica._AprovarTabuaBiometricaTest.SetUp() in E:\a\b1a\_work\2\s\Angular.Client.Planos.Tests\Features\TabuaBiometrica\AprovarTabuaBiometrica\_AprovarTabuaBiometricaTest.cs:line 290
```

And this is the log of selenium hub console: 

```
33 requests waiting for a slot to be free.
Capabilities [{ie.ensureCleanSession=true, browserName=internet explorer, javascriptEnabled=true, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}]Capabilities [{ie.ensureCleanSession=true, browserName=internet explorer, javascriptEnabled=true, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}]Capabilities [{ie.ensureCleanSession=true, browserName=internet explorer, javascriptEnabled=true, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}]Capabilities [{ie.ensureCleanSession=true, browserName=internet explorer, javascriptEnabled=true, ignoreProtectedModeSettings=true, version=, platform=WINDOWS}]
```
(cut the rest) 

Node console shows a running session. The Take screenshot button does nothing, and deleting session apparently removes the session from node, but the hub shows it still as busy. 

No show :(

**Comment by raju249** [comment]
@junalmeida  - As of date, grid 4 does not have a queue implementation. 
This may be picked up as a feature request.
/cc - @diemol

**Comment by diemol** [comment]
@AutomatedTester, did we document how to do this?

**Comment by AutomatedTester** [comment]
@diemol It's on @pujagani todo. I've asked that we go through all docs to make sure that we have things properly documented.
