### ISSUE TITLE
Action doubleClick not working

### ISSUE THREAD

**Issue by SankySyS** [SeleniumHQ/selenium#3639]
## Meta -
OS:  Windows 7

Selenium Version: 3.3.1  

Browser:  Firefox

Browser Version:  52.0 (32-bit)

## Actual Behavior - Exception:
org.openqa.selenium.InvalidArgumentException: Expected 'id' default mouse to be mapped to InputState whose subtype is undefined, got: pointerMove
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'DL-R90G0MZM', ip: '172.19.200.157', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\AppData\Local\Temp\rust_mozprofile.JrYdrbQ2ul2H, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0, platformVersion=6.1, moz:processID=15868, browserName=firefox, platformName=windows_nt}]

## Steps to reproduce -

Sample web page:

```
<!DOCTYPE html>
<html>

<body>
Browsers:
<input list="browsers">
<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist> 
</body>
</html>
```
action: `new Actions(driver).doubleClick(element).build().perform();`

**Comment by SankySyS** [comment]
if i change action to 

```
element.click();
element.click();
```

it's work as doubleClick

**Comment by lmtierney** [comment]
What language bindings are you using? Are you going through standalone?

**Comment by SankySyS** [comment]
i use Java 1.8 and "selenium-java" as maven dependency

**Comment by AnthonyMDev** [comment]
I'm having this same issue currently.

**Comment by lmtierney** [comment]
This is an issue with geckodriver mozilla/geckodriver#661
