### ISSUE TITLE
Session was terminated due to PROXY_REREGISTRATION

### ISSUE THREAD

**Issue by nbogol** [SeleniumHQ/selenium#3640]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by nbogol** [comment]
opened by mistake

**Comment by jeitae** [comment]
org.openqa.selenium.WebDriverException: Session ["SESSION_ID"] was terminated due to PROXY_REREGISTRATION
Command duration or timeout: 474 milliseconds.


How i can take control of that? if i run 2 test all good but for more all fail by PROXY_REREGISTRATION
