### ISSUE TITLE
captureEntirePageScreenshot fails with TypeError

### ISSUE THREAD

**Issue by alan-oneill** [SeleniumHQ/selenium#3641]
## Meta -
OS:  Windows 7 and Ubuntu 16.04.2
Selenium Version:  IDE 2.9.1
Browser:  Firefox
Browser Version:  Linux: Firefox 52.0 (32-bit); Windows: Firefox 51.0.1 (32-bit)
## Expected Behavior -
captureEntirePageScreenshot command will take a screen shot and save it to a file.
## Actual Behavior -
This error is reported: [error] Unexpected Exception: TypeError: Argument 1 of CanvasRenderingContext2D.drawWindow does not implement interface Window.. 
## Steps to reproduce -
1. Start the Selenium IDE from Firefox (Tools -> Web Developer -> Selenium IDE)
2. Create a new script with a single command, using an appropriate file name for the target
Command: captureEntirePageScreenshot
Target: /home/username/myscreen.png
3. Run the script.
![image](https://cloud.githubusercontent.com/assets/12497730/23824392/de8fca9e-0643-11e7-9f68-d33a4d2764b7.png)

**Comment by josetepedino** [comment]
This error is also occurring on the following environment:
- Ubuntu 16.04 LTS;
- Firefox 54.0 (64-bit);
- Selenium IDE 2.9.0.

    [info] Playing test case Untitled
    [info] Executing: |captureEntirePageScreenshot | /home/fernando/a.png | |
    **[error] Unexpected Exception: TypeError: Argument 1 of CanvasRenderingContext2D.drawWindow does not implement interface Window..** 
    [info] Test case failed
    [info] Test suite completed: 1 played, 1 failed

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
