### ISSUE TITLE
Selenium 3.3.1 is not mentioned on download page

### ISSUE THREAD

**Issue by schmidtkp** [SeleniumHQ/selenium#3645]
The Selenium downloads page does not mention Selenium 3.3.1.

Also, the Internet Explorer Driver Server has yet to be sync'ed up with 3.3.1 release of Selenium.

http://www.seleniumhq.org/download/

**Comment by lukeis** [comment]
i've already made the commit to update the downloads page:
https://github.com/SeleniumHQ/www.seleniumhq.org/commit/258383fed1d56b7b8282102a4eaf7bbaedb157ce

but our jenkins ci ran out of disk space, so waiting for someone with access to clean up the machine.

I don't believe IE Driver has any deltas between the 3.3.0 and 3.3.1 tags, so rebuilding it would result in the same binary. We don't sync up the minor point release tags for all things, they are meant to be language (or driver) specific.

Also, for SeleniumHQ website related things, would appreciate bugs logged on that repo instead:
https://github.com/SeleniumHQ/www.seleniumhq.org
