### ISSUE TITLE
Selenium not working properly on Firefox v 51 nor 52

### ISSUE THREAD

**Issue by professorman** [SeleniumHQ/selenium#3646]
## Meta -
OS:  Windows 10 x64

Selenium Version:  2.9.1, IDE

Browser:  Firefox version 52.0

## Expected Behavior -
When recording a script, the script fails to click the login button
## Actual Behavior -
The script fails

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
