### ISSUE TITLE
Typo in documentation for python api for "save_screenshot" method. Want to fix it.

### ISSUE THREAD

**Issue by igauravsehrawat** [SeleniumHQ/selenium#3651]
I found a typo here: https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.save_screenshot

The method is `save_screenshot` and but it's usage is using `get_screenshot_as_file` as can be seen here
![screen shot 2017-03-14 at 2 46 33 pm](https://cloud.githubusercontent.com/assets/3696327/23893798/cd2b31a6-08c5-11e7-8a53-48d674dd2592.png)

I wanted to fix it by modifying the docs for `save_screenshot` method but `save_screenshot` is just an alias to `get_screenshot_as_file`. Therefore I could not change the docs for it.

How can I fix this typo?

Thanks

**Comment by AutomatedTester** [comment]
If you follow the steps in https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#code-contributions, since the docs are generated from the code, you can fix the issue and submit a pull request.

**Comment by igauravsehrawat** [comment]
@AutomatedTester Thanks for replying.

I figured out that code for `save_screenshot` is in [this line](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L812) but there is no docs for that method since it's a method assignment from another method.

Can you confirm if I am correct or not?

Thanks

**Comment by aneeshchandy** [comment]
@igauravsehrawat I believe it is in now [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L828)

As you said, you cannot just change the method name with breaking this part of the documentation, unless you come up with a better solution. Good luck!

<img width="831" alt="screen shot 2017-04-05 at 9 04 23 am" src="https://cloud.githubusercontent.com/assets/13005178/24709279/ffdf51b6-19de-11e7-840a-83353596365d.png">

**Comment by cgoldberg** [comment]
you could remove this line:
`save_screenshot = get_screenshot_as_file`

... and define a real `save_screenshot` method that just calls `get_screenshot_as_file`.  Then you can create a proper usage message for `save_screenshot`.
