### ISSUE TITLE
NetExport+FireBug+Firefox Har file Generation Issue In Selenium GRID

### ISSUE THREAD

**Issue by maninderjeet** [SeleniumHQ/selenium#3652]
## Meta -
OS:  Hub(Linux), Node (Windows)

Selenium Version:  2.53

Browser:  Firefox

Browser Version:  

To generate Har file in Selenium i'm using  Firefox+Firebug+NetExport_Extension.
Following the code which is setting profiles for firefox to generate har file.

profile.setPreference("extensions.firebug.netexport.alwaysEnableAutoExport", true);
profile.setPreference("extensions.firebug.netexport.autoExportToFile",	true);
profile.setPreference("extensions.firebug.netexport.autoExportToServer", false);
profile.setPreference("extensions.firebug.netexport.defaultLogDir",dirPath.toString());

dirPath= Pointing to Workspace in HUB machine, like -/var/lib/jenkins/workspace/Omniture-GRID/FileUpload/NetExport

So whenever tests are executing without Grid  i'm able to get HAR file generated in above mentioned dirPath.
But issue is coming when I'm running this code in Grid Environment. In Grid execution workspace is created in HUB machine and on the other hand browser is opened in Node machine thats why HAR file is not getting generated in Hub machine.
But as per our Implementation we are checking in dirPath(/var/lib/jenkins/workspace/Omniture-GRID/FileUpload/NetExport) if a har file is generated in the given path.

Needs a solution for this on early basis.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
