### ISSUE TITLE
getText() not working with selenium 3.3.1 + GeckoDriver 0.15.0

### ISSUE THREAD

**Issue by SergioLeone** [SeleniumHQ/selenium#3653]
## Meta -
OS:  Windows 7 x64

Selenium Version:  3.3.1

Browser:  Firefox 

Browser Version:  49.0.2 x64

## Expected Behavior -
`element.getText()` to return text value of the specified element

## Actual Behavior -
`getText()` returns null

## Steps to reproduce -
I'm not sure if this is an issue with Selenium or GeckoDriver, and I don't have access to test it in Chrome as of now, hence I'm logging it here. Please be considerate if this is not a Selenium issue and close the thread.

The only option that I've found to be working with my setup:
` element.getAttribute("textContent")`
Which is fine, but still using getText() is a bit faster.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
