### ISSUE TITLE
WebDriverException on set_page_load_timeout()

### ISSUE THREAD

**Issue by jwg4** [SeleniumHQ/selenium#3654]
## Meta
OS:  
Linux
Selenium Version:  
3.3.1 with Python 
Browser:  
Firefox, using geckodriver 0.15.0
Browser Version:  
52.0

## Expected Behavior -
Create a client and set page timeout.

## Actual Behavior -
A WebDriverException is thrown (without any message):
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    client.set_page_load_timeout(120)
  File "/home/jack/git/flask-prismfp/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 727, in set_page_load_timeout
    'pageLoad': int(float(time_to_wait) * 1000)})
  File "/home/jack/git/flask-prismfp/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/home/jack/git/flask-prismfp/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: 
```

## Steps to reproduce -
from selenium import webdriver
prof = webdriver.FirefoxProfile()
client = webdriver.Firefox(prof)
client.set_page_load_timeout(120)

The above seems to work correctly with version 3.3.0, with all other aspects of the environment the same.

**Comment by jwg4** [comment]
Thanks a lot! I assume that I can workaround this by doing:
```
from selenium.webdriver.remote.command import Command
...
client.execute(Command.SET_TIMEOUTS, {
    'ms': float(120) * 1000,
    'type': 'page load'}
    )
```
in place of the last line above.

**Comment by AutomatedTester** [comment]
For now, yes until there is  release

**Comment by ivyandnana** [comment]
i also have this question. now i can't use "set_page_load_timeout"

**Comment by youyanggu** [comment]
Unfortunately jwg4's code does not work. You can set the timeout to be 0 and nothing will happen. Is there an alternate way to set the timeout?

**Comment by ikeboy** [comment]
using set_page_load_timeout doesn't cause any errors but appears to have no effect. Should I open a new bug?

**Comment by bannima** [comment]
I meet the totally same problem with you when trying to set the max loading time for each page ,throws exception with nothing useful. Sadly, I also face the same problem after setting the firefox profile  as you did. My machine is mac and python version is 2.7 with selenium 3.3.1 and firefox 52.0.
Can anyone give me a hint to fix this problem or show me the old way of setting page load timeout?
Thanks in advance!

**Comment by jwg4** [comment]
My understanding is that the lack of a decent message is related to https://github.com/SeleniumHQ/selenium/issues/3683
