### ISSUE TITLE
Negative values for setScriptTimeout() not working as mentioned in the documentation. (node selenium-webdriver)

### ISSUE THREAD

**Issue by kaushik-evani** [SeleniumHQ/selenium#3655]
OS:  UBUNTU 16.04
Selenium Version: Node.js 3.3.0 
Browser: Chrome

The negative value for setScriptTimeout() don't seem to be working as it should for executeAsyncScript().
I'm trying to execute a script that can run for an indefinite amount of time and executeAsyncScript() is not working if I'm not giving it positive values, which I have no way of knowing.
```
var script = "
        var callback = arguments[arguments.length - 1];
        window.onbeforeunload = function(e){
          var confirmationMessage = "Are you sure you want to leave this page and close the app?";
          (e || window.event).returnValue = confirmationMessage;
          return confirmationMessage;
          callback('CLOSED!');
        }
     "
 driver.executeAsyncScript(script).then(function(val){
       console.log(val);
     })
```

## Expected Behavior -
I should get "CLOSED!" log after the window is closed.

## Actual Behavior -
timeout === 0
ScriptTimeoutError: asynchronous script timeout: result was not received in 0 seconds.

timeout ===  -1
ScriptTimeoutError: asynchronous script timeout: result was not received in -1 seconds

I do not want to give a specific timeout. Is this feature working? Is it a bug?
Most of the solutions for this online seem to have been solved by using a large enough estimate for a positive timeout.
But I haven't found anything on how to use negative timeout properly.

**Comment by jleyba** [comment]
The docs on `setScriptTimeout` were way out of date. For an indefinite timeout, set the value to null. Two important things to note:

1.  `driver.manage().timeouts().setScriptTimeout()` will be removed in 4.0; use [`driver.manage().setTimeouts()`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L1193)
2.  The W3C spec has inconsistent language for null timeouts (see w3c/webdriver#1137), so I'm not sure which driver implementations (if any) will permit an indefinite script timeout.
