### ISSUE TITLE
Ruby+Firefox52+selenium 3.3.0: "Your connection is not secure" 

### ISSUE THREAD

**Issue by Bindong18** [SeleniumHQ/selenium#3665]
## Meta -
OS:  windows 7

Selenium Version:  
3.3.0
Browser:  
firefox 52

-->

Browser Version:  
firefox 52

## Steps to reproduce -
code like below:
   @profile = Selenium::WebDriver::Firefox::Profile.new     
   @profile.assume_untrusted_certificate_issuer=false
   @profile.secure_ssl = true    
   driver = Watir::Browser.new :firefox, :profile => @profile
   driver.goto "https://www.google.com/" 

It fails at last due to "Your connection is not secure"
pls. see below:
<error message="Selenium::WebDriver::Error::UnknownError: ..." type="test"> Failure: test[C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:32]: Selenium::WebDriver::Error::UnknownError: C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:620:in `execute' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:126:in `get' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/navigation.rb:32:in `to' C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/watir-6.2.0/lib/watir/browser.rb:78:in `goto' 

Pls. help to fix.

BTW: if using python , selenium 3.3.1, the above issue doesn't occur. pls. see below
driver = webdriver.Firefox()
driver.get("https://www.google.com/")

**Comment by p0deje** [comment]
Profile settings don't have effect on Firefox 52 (I assume you use GeckoDriver).

What do you try to achieve using the profile options?

**Comment by Bindong18** [comment]
@p0deje Yes , I used GeckoDriver.

I want to open "https://www.google.com" successfully without encountering any security issue, pls. see the attached
![security](https://cloud.githubusercontent.com/assets/26452901/23988081/0e813590-0a03-11e7-89ff-2b1222beb172.png)

**Comment by p0deje** [comment]
So why do you change profile then? Just use plain driver:

```ruby
driver = Selenium::WebDriver.for(:firefox)
driver.get 'https://google.com'
```

**Comment by Bindong18** [comment]
@p0deje 
With your post, I still got the same error.
Have you tried ?

**Comment by p0deje** [comment]
I did, it loads fine.

**Comment by p0deje** [comment]
I think this is something on your side - ISP issue, website blocking, etc.

Can you open it correctly when using Firefox manually?

**Comment by Bindong18** [comment]
what about your firefox version?

**Comment by Bindong18** [comment]
when I manully open firefox, I got the following
![security](https://cloud.githubusercontent.com/assets/26452901/23988391/7119c02c-0a04-11e7-8a52-be94261acb49.png)

**Comment by p0deje** [comment]
Ok, so this is definitely something wrong on your side. There might be many reasons for this, so I suggest you to Google it.

Closing this as not a Selenium issue.

**Comment by Bindong18** [comment]
But I can successfully open with python code: if using python , selenium 3.3.1, pls. see below
driver = webdriver.Firefox()
driver.get("https://www.google.com/")

**Comment by Bindong18** [comment]
This is definitely selenium issues for ruby

**Comment by p0deje** [comment]
> when I manully open firefox, I got the following

You say that if you open browser manually and open Google, you still see an error. How is that Selenium Ruby issue?

**Comment by Bindong18** [comment]
WHen I manully open google, I can click advanced button to add exception and then google search shows

**Comment by Bindong18** [comment]
Can you tell me how to bypass "adding exception" in ruby ?

**Comment by Bindong18** [comment]
I don't need to by pass using python.

so for ruby , I tried to create a new profile like below to by pass
@profile = Selenium::WebDriver::Firefox::Profile.new
@profile.assume_untrusted_certificate_issuer=false
@profile.secure_ssl = true
driver = Watir::Browser.new :firefox, :profile => @profile
driver.goto "https://www.google.com/"

but it still can't work

**Comment by p0deje** [comment]
Try this:

```ruby
caps = Selenium::WebDriver::Remote::Capabilities.firefox
caps['acceptInsecureCerts'] = true
driver = Selenium::WebDriver.for(:firefox, desired_capabilities: caps)
browser = Watir::Browser.new(driver)
```

**Comment by Bindong18** [comment]
Ok let me try

**Comment by Bindong18** [comment]
This is working, thank you very much for your help
