### ISSUE TITLE
No implicit wait of loaded page in firefox

### ISSUE THREAD

**Issue by vicv21800** [SeleniumHQ/selenium#3666]
## Meta -
OS:  ubuntu 14

Selenium Version:   3.3.1

Browser:  Firefox/Chrome

Browser Version:  chrome 57.0.2987.98 , firefox 52

## Expected Behavior -
Selenium with chrome and firefox should have the same behavior
## Actual Behavior -
when doing an action  on a webelement with firefox, it does not implicitly wait for the page to be fully loaded
But when doing it on Chrome it wait for the page to be fully loaded before processing to the next command

## Steps to reproduce -
run this script on chrome and on firefox

from time import sleep

driver = webdriver.Firefox()

driver.get("https://www.youtube.com")

search_field = driver.find_element_by_xpath("//*[@id='masthead-search-term']")
search_field.send_keys("meaning of life")
search_field.submit()

for i in range(10):
    print(str(driver.execute_script("return document.readyState")))
    sleep(0.1)

driver.quit()

**Comment by lmtierney** [comment]
This is a known issue with geckodriver https://github.com/mozilla/geckodriver/issues/308
