### ISSUE TITLE
FirefoxDriver is incorrectly treated as remote

### ISSUE THREAD

**Issue by zackw** [SeleniumHQ/selenium#3670]
## Meta -
OS:  all
Selenium Version: 3.3.0
Browser:  Firefox
Browser Version: **all**

## Expected Behavior -

`selenium.webdriver.Firefox` runs a _local_ instance of the browser, ergo the internal property `_is_remote` should be False.  In 3.3.0, it isn't, due to a logic error in the constructor: `_is_remote` is set to False at the very beginning, but the superclass constructor (which is `RemoteWebDriver`, as the remoting _protocol_ is used) is called at the very end, which clobbers the value to True.

This breaks any script that attempts to upload files.

I suspect this bug was introduced with support for GeckoDriver (and thus the need to dynamically switch between FirefoxRemoteConnection and ExtensionConnection).

## Steps to reproduce -

```
>>> from selenium.webdriver import Firefox
>>> ff = Firefox()
>>> ff._is_remote
True
>>> ff.get('data:text/html,<input type="file" id="foo">')
>>> el = ff.find_element_by_id("foo")
>>> el.send_keys("/bin/ls")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/selenium/webdriver/remote/webelement.py", line 345, in send_keys
    value = self._upload(local_file)
  File ".../site-packages/selenium/webdriver/remote/webelement.py", line 548, in _upload
    raise e
selenium.common.exceptions.WebDriverException: Message: POST /session/59ac3c55-0ff1-4c1a-82b5-d08448db6caa/file did not match a known command
```

**Comment by lmtierney** [comment]
Hi, this is fixed in 557a114 and will be in the next release

**Comment by lmtierney** [comment]
As a workaround for now, you can set `_is_remote` after instantiating the driver (not ideal I know)

**Comment by zackw** [comment]
Good to hear, thanks.

**Comment by tboulogne** [comment]
Hello,

> _is_remote

, does not work for me :-(
