### ISSUE TITLE
firefox 45.8.0 + selenium 3.3.1 error : selenium.common.exceptions.WebDriverException: Message: ReferenceError:

### ISSUE THREAD

**Issue by virgile-thermo** [SeleniumHQ/selenium#3671]
## Meta -
OS:  
centos 6
Selenium Version:  
3.3.1
Browser:  
firefox
Browser Version:  
 45.8.0

## Expected Behavior -
10
## Actual Behavior -
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    print driver.execute_script("return roger;")
  File "/netShare/home/buildsystem/Desktop/virgile/TEST/SELENIUM/selenium/webdriver/remote/webdriver.py", line 467, in execute_script
    'args': converted_args})['value']
  File "/netShare/home/buildsystem/Desktop/virgile/TEST/SELENIUM/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/netShare/home/buildsystem/Desktop/virgile/TEST/SELENIUM/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: ReferenceError: roger is not defined
## Steps to reproduce -
// add firefox geckodriver folder to the path

// index.html
<!DOCTYPE html>
<html>
<head>
    <title>test</title>
    <script type="text/javascript">
        var roger = 10;
        function init() 
        {
           console.log("roger : "+roger);
        }
    </script>
</head>
<body onload="init()" bgcolor="silver">
    <div id="truc">toto</div> 
</body>
</html>

// test.py
from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.support.ui import WebDriverWait
from selenium.w

ebdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

import os
import subprocess
import time

driver = webdriver.Chrome()
driver.get("file:///path/to/index.html")
time.sleep(5)
print driver.execute_script("return roger;")

driver.close()

// commande 
python test.py

**Comment by lmtierney** [comment]
Your issue says Firefox, but your code says Chrome. Either way this is a driver issue so please file a bug with the respective driver vendor
