### ISSUE TITLE
getText() throws stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by Shengjian** [SeleniumHQ/selenium#3673]
## Meta -
OS:  MAC

Selenium Version:  3.0.1

Browser:  chrome

Browser Version:   56.0.2924.87

## Expected Behavior -
getText() can return the value

## Actual Behavior - 
it throws  stale element reference: element is not attached to the page document

## Steps to reproduce -

I have a case to console the progress for a task, and the cold is:
element(by.css(progressCss)).isPresent().then((isPresent) => {
   if (isPresent) {
        element(by.css(progressCss)).getText().then((progress) => {
             console.log(progress);
        });
   }
});

because the page has to auto refresh, sometimes it would throw error "stale element reference: element is not attached to the page document" on line "element(by.css(progressCss)).getText().then((progress) => {",
and how can resolve it?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
