### ISSUE TITLE
SafariDriver not connecting.

### ISSUE THREAD

**Issue by mroien** [SeleniumHQ/selenium#3674]
## Meta -
OS:  
MacOS 10.11.6 El Capitan
Selenium Version:  
Selenium 2.53.1
Browser:  
Safari

Browser Version:  
Safari 10.0.3

## Expected Behavior -
Safari driver to connect and run test.

## Actual Behavior -
Safari runs the test from time to time and other times the Safari driver closes right away or hangs on the connection.
## Steps to reproduce -
I think Safari driver is connecting where I'm not getting the error on the 4th line in red saying it's not connecting, but my test will fail with the error.
```
RuntimeError: Failed to connect to SafariDriver after 10114 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'LEFTOUT', ip: 'LEFTOUT', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_73'
Driver info: driver.version: SafariDriver
```
![safaridriver](https://cloud.githubusercontent.com/assets/9540417/24046822/de7d0ece-0af1-11e7-81d2-8604cbbe3c11.png)

I have tried to upgrade to Selenium 3.0.1 with Selenium-standalone, however it does not work for me. I had to roll back to Selenium 2.53.1.

**Comment by jleyba** [comment]
The extension-based SafariDriver is no longer supported. We dropped support in favor of Apple's safaridriver, which is included with Safari 10

**Comment by mroien** [comment]
I could not get Safari 10 to work with the Apple Safaridriver. I've followed the instructions in here https://webkit.org/blog/6900/webdriver-support-in-safari-10/ but I can run the new safaridriver in /usr/bin/safaridriver --port 0 but the tests fail right away after the browser spins up.
