### ISSUE TITLE
Unable to create Selenium 3 Firefox Profile

### ISSUE THREAD

**Issue by ShamylaS** [SeleniumHQ/selenium#3675]
## Meta -
OS:  Windows 2012

Selenium Version: 3.3.1  

Browser:   Firefox

Browser Version:  

51.0, 52.0

## Expected Behavior -
Firefox profile should spin up with Selenium 3

## Actual Behavior -
No Firefox profile is created.

## Steps to reproduce -

Selenium Version : 3.3.1

I am trying to start up a windows node using the following command

`    java -role node -nodeConfig <%=@selenium_node %> -Dwebdriver.firefox.profile <%=@firefox_profile_directory %> -jar <%=@selenium_jar %>`

I have put the `-D...` command line parameters before the `-jar` prompt as discussed here:

> https://github.com/SeleniumHQ/selenium/issues/2566

However, I get the error:

> Unrecoginized opton: -role Error: Could not creacte the Java Virtual
> Machine. Error: A fatal exception  has occurred.  Program will exit.

If I try the other way around e.g. 

`java -role node -Dwebdriver.firefox.profile <%=@firefox_profile_directory %> -nodeConfig <%=@selenium_node %>  -jar <%=@selenium_jar %>`

or

`java -Dwebdriver.firefox.profile <%=@firefox_profile_directory %> -jar <%=@selenium_jar %> -role node -nodeConfig <%=@selenium_node %>`

I get the error: 

> Could not find or load main class C:\...\firefox\profile

**Comment by barancev** [comment]
1) WebDriver options (-role, -nodeConfig) should go after -jar option
2) -Dxxx=yyy
