### ISSUE TITLE
Add case-insensitive option for `text_to_by_present_in_element` expected condition

### ISSUE THREAD

**Issue by birdsarah** [SeleniumHQ/selenium#3677]
This has come up because of what appears to be an inconsistency in Edge WebDriver implementation, but seems like it could be a useful feature.

I'd like to add an optional flag to `text_to_be_present_in_element` expected to condition, to match the text case-insensitively. By default, this would be off (current behavior).

My specific issue is that I have an element where the text has been upper-cased by CSS. 
* In Firefox, Chrome, Safari, and IE: the text returned by element.text is the uppercase text, 
* but edge webdriver returns the lowercase text

So, for my crossbrowser test to work I need to compare the text case insensitively.

**Comment by lmtierney** [comment]
I'd suggest creating your own Expected Condition or use a lambda to achieve this
