### ISSUE TITLE
How to enable chromedriver logging in from the selenium webdriver for nodejs

### ISSUE THREAD

**Issue by doberkofler** [SeleniumHQ/selenium#3678]
## Meta -
OS:  
Windows 7

Selenium Version:  
3.3.0

Browser:  
Chrome

Browser Version:  
57 (64-bit)

## Expected Behavior -
I need to enable the chromedriver logging from within a selenium webdriver nodejs test and this should be possible using the method `enableVerboseLogging`

## Actual Behavior -
Using `enableVerboseLogging` on the builder instance does work and I did not find any documentation that explains how to use `enableVerboseLogging`.

## Steps to reproduce -
```
require('chromedriver');
const webdriver = require('selenium-webdriver');

let capabilities = webdriver.Capabilities.chrome();
capabilities.setScrollBehavior(1);
let builder = new webdriver.Builder().withCapabilities(capabilities);
builder.enableVerboseLogging(); // fails!!!
let driver = builder.build();
```

**Comment by kaiyoma** [comment]
The answer here works for me: https://stackoverflow.com/questions/42803545/how-to-enable-chromedriver-logging-in-from-the-selenium-webdriver

**Comment by barancev** [comment]
Sorry for leaving this issue unanswered.

It's rather a question than an issue, for questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
