### ISSUE TITLE
Update KB3032359 breaking IE driver

### ISSUE THREAD

**Issue by florentbr** [SeleniumHQ/selenium#368]
The KB3032359 update from march 10 breaks the Internet Explorer driver.

Environment:
Windows 8.1 64bit, IE11, IEDriver 32bit 2.45

To reproduce:
```c#
var driver = new InternetExplorerDriver();
driver.Navigate().GoToUrl(@"http://www.google.com");
driver.FindElementByName("q").SendKeys("ok");
```

The last line throws ElementNotFoundException and the log indicates an "Access denied" error on IHTMLWindow2::execScript.
It seems to be related to execScript being deprecated:
https://connect.microsoft.com/IE/feedback/details/1062093/installation-of-kb3025390-breaks-out-of-process-javascript-execution-in-ie11

I have the registry key "FEATURE_DISABLE_INTERNAL_SECURITY_MANAGER" set to 1,
but this workaround for the kb3025390 doesn't work with this new update.

**Comment by jimevans** [comment]
This isn't globally broken. I can confirm that I have the referenced update installed, as shown here:
![windowsupdates](https://cloud.githubusercontent.com/assets/352840/6854973/0a93088e-d3cb-11e4-9816-e86169a2afb4.png)

Running the same code in my environment works perfectly fine. I'm closing this issue as unreproducible.

**Comment by florentbr** [comment]
I tried again on a new fresh installation with the same config and updates and it didn't fail.
I found that it is the "FEATURE_DISABLE_INTERNAL_SECURITY_MANAGER" registry key that is causing the failure.

So for the record, the IE driver doesn't work with this registy tweek since KB3032359:

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_DISABLE_INTERNAL_SECURITY_MANAGER]
"iexplore.exe"=dword:00000001

Thanks for your time.
