### ISSUE TITLE
Selenium IDE 2.9.1: single web action is recorded as two same commands.

### ISSUE THREAD

**Issue by xmhubj** [SeleniumHQ/selenium#3681]
## Meta -
OS:  
Windows 7 64-bit
Selenium Version:  
Selenium IDE 2.9.1
Browser:  
Firefox
Browser Version:  
ESR 45.8.0 (64-bit)

## Expected Behavior -
A single web action should be recorded as a single selenium command via Selenium IDE docked version(Ctrl+Shift+s).

## Actual Behavior -
A single web action, like, `click`, `type` are recorded twice with Selenium IDE docked/embedded version. Here is a screenshot:
![s-ide-2-9-1-docked](https://cloud.githubusercontent.com/assets/15373664/24089609/99c121ce-0d73-11e7-929d-11f157770dd4.jpg)

## Steps to reproduce -
1. Open Firefox
2. Press combination key `Ctrl+Shift+s` to launch Selenium IDE 2.9.1 in docked/embedded version.
3. Click "Click to Record" to start a new recording.
4. Enter "http://www.bing.com" in browser URL.
5. Click Bing search box.
6. Type "hello" into the search box.
7. Click search button

Script generated as:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://www.bing.com/" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=sb_form_q</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=sb_form_q</td>
	<td>hello</td>
</tr>
<tr>
	<td>type</td>
	<td>id=sb_form_q</td>
	<td>hello</td>
</tr>
<tr>
	<td>click</td>
	<td>id=sb_form_go</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>id=sb_form_go</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>

```

**Comment by xmhubj** [comment]
Any updates on this one?

**Comment by luaithrenn** [comment]
Any updates?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
