### ISSUE TITLE
Selenium doesn't display the stacktrace from geckodriver exceptions, because the key is cased differently

### ISSUE THREAD

**Issue by jwg4** [SeleniumHQ/selenium#3683]
## Meta -
OS:  Linux (Ubuntu 14.04)
Selenium Version:  
3.3.1
Browser:  
Firefox / geckodriver 0.15.0

## Expected Behavior -
If geckodriver throws an exception with a stacktrace, selenium should display that stacktrace in the message for the WebDriverException it generates.

## Actual Behavior -
The message is empty, even if a stacktrace is present.

It seems the selenium code looks for the key 'stackTrace' in an exception JSON passed from a webdriver. See https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L173 However geckodriver uses 'stacktrace', all lower case, as per the W3 spec: https://www.w3.org/TR/webdriver/

I haven't checked every single one, but other languages appear to do the same thing. Would a PR checking for both keys be accepted? If so, is it legit to just patch one language's code, or does this cause more problems than it solves? Thanks.

**Comment by Dude-X** [comment]
@AutomatedTester this needs attention.

**Comment by jwg4** [comment]
Any feedback on this issue?

**Comment by lmtierney** [comment]
Looks like a legitimate issue that we need to address in all languages, would like confirmation from one of the spec leads @AutomatedTester or @shs96c

**Comment by AutomatedTester** [comment]
We're going to have to update the spec to do `stackTrace`. We are also going to have to update the bindings for a short term to handle both `stacktrace` and `stackTrace`

**Comment by barancev** [comment]
Java handles both protocol versions.

**Comment by p0deje** [comment]
f4bd516 fixes in Ruby bindings.

**Comment by lmtierney** [comment]
b8af26b fixes in Python

**Comment by diemol** [comment]
Closing as the fix got implemented/merged in all bindings.
