### ISSUE TITLE
Firefox Profile is not working with remote services

### ISSUE THREAD

**Issue by sajidchingchong** [SeleniumHQ/selenium#3685]
## Meta -
OS:  
OSX
Selenium Version:  
3.2.0
Browser:  
Firefox

Browser Version:  
52.0.1

## Expected Behavior -

Preferences should take effect locally or with remote services like Sauce Labs.

## Actual Behavior -

Preferences work locally but don't work with remote services like Sauce Labs.

## Steps to reproduce -

var FirefoxProfile = require("selenium-webdriver/firefox").Profile;
var profile = new FirefoxProfile();
profile.setPreference("media.navigator.streams.fake", true);
profile.setPreference("media.navigator.permission.disabled", true);

var firefoxDriver = new webdriver.Builder().withCapabilities({ 'browserName': 'firefox', 'firefox_profile': profile }).build();

**Comment by barancev** [comment]
Can you reproduce this issue with regular Selenium Server?

Cloud grid providers like Sauce Labs can use customized versions of sever, that can disable some features for security of performance reasons.

**Comment by barancev** [comment]
Closing the issue assuming it's a SauceLabs issue unless there is a testimony of the opposite
