### ISSUE TITLE
error: "Package Selenium.WebDriver 3.3.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Selenium.WebDriver 3.3.0 supports:   - net35 (.NETFramework,Version=v3.5)   - net40 (.NETFramework,Version=v4.0)

### ISSUE THREAD

**Issue by 20070310test** [SeleniumHQ/selenium#3687]
## Meta -
OS:  Windows 10

Selenium Version:  3.3.0

Browser:  

**Error**: 
I am getting an error when using "Manage NuGet Packages for Solution" to include Selenium Libraries 3.3.0 to .Net Selenium Project in **Visual Studio 2017** (Community version). Actual message  as follows:

"**Package** **Selenium.WebDriver 3.3.0 is not compatible with netcoreapp1.1** ****(.NETCoreApp,Version=v1.1).** Package Selenium.WebDriver 3.3.0 supports:**
  **- net35 (.NETFramework,Version=v3.5)**
  **- net40 (.NETFramework,Version=v4.0)**
**One or more packages are incompatible with .NETCoreApp,Version=v1.1.**"

**Comment by jimevans** [comment]
That's right, the NuGet package isn't compatible with .NET Core. Support should be coming eventually, but likely not until .NET Standard 2.0.
