### ISSUE TITLE
Firefox and InternetExplorer doesn't perform action on initially opened window when multiple windows are opened

### ISSUE THREAD

**Issue by DestinationQA1** [SeleniumHQ/selenium#3689]
## Meta -
OS:  Windows 8
Selenium Version:  
3.2.0
Browser:  
Firefox 45.3.0, IE 11

Browser Version:  
Firefox 45.3.0, IE 11

## Expected Behavior -
steps should be performed with 1st window, since control is not switched to new window which is opened.
## Actual Behavior -
Step is not performed. No error is displayed
## Steps to reproduce -
driver.get("http://facebook.com");
		driver.manage().timeouts().implicitlyWait(4, TimeUnit.SECONDS);
		driver.findElement(By.linkText("Terms")).click();
		driver.findElement(By.linkText("Cookie Use Policy")).click();

Terms opens new window. So next action which is clicking a link in first window doesn't work and doesn't throw error in Firefox as InternetExplorer

**Comment by barancev** [comment]
In ie worls well with requireWindowsFocus option:
```
InternetExplorerOptions options = new InternetExplorerOptions();
options.requireWindowFocus();
InternetExplorerDriver driver = new InternetExplorerDriver(options);
```
I could not reproduce the issue in Firefox Nightly driven by geckodriver 0.18 and in Firefox ESR 52 driven by legacy Firefox driver included in Selenium 3.5.0.
