### ISSUE TITLE
Random firefox connection failuers org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7057 after 45000 ms.

### ISSUE THREAD

**Issue by dannygu** [SeleniumHQ/selenium#3690]
## Meta -
OS:  Windows 7 

Selenium Version:  2.53.1

Browser:  Firefox

Browser Version:  45.0.2 (32bit)

## Expected Behavior -

We are running several tests on 3 Firefox instances in parallel ,randomly from time to time tests fail with the following stack, this doesn't occur at all times, seems to be rather random.

Any assistance is appreciated, Thanks.

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7057; process output follows: 
e,"seen":true}
1490088525512	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1490088525513	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"fc-BepzaxfKm","location":"app-global","version":"45.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1460086235000,"updateDate":1460086235000,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.2","maxVersion":"45.0.2"}],"targetPlatforms":[],"seen":true}
1490088525513	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1490088525515	DeferredSave.extensions.json	DEBUG	Save changes
1490088525515	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1490088525515	addons.xpi-utils	DEBUG	Updating add-on states
1490088525517	addons.xpi-utils	DEBUG	Writing add-ons list
1490088525521	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1490088525522	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.1.14
1490088525548	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1490088525548	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1490088525549	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1490088525574	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1490088525574	addons.manager	DEBUG	Provider finished startup: XPIProvider
1490088525574	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1490088525575	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1490088525575	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1490088525576	addons.manager	DEBUG	Starting provider: GMPProvider
1490088525586	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1490088525586	addons.manager	DEBUG	Provider finished startup: GMPProvider
1490088525587	addons.manager	DEBUG	Starting provider: PluginProvider
1490088525587	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1490088525587	addons.manager	DEBUG	Provider finished startup: PluginProvider
1490088525588	addons.manager	DEBUG	Completed startup sequence
1490088528590	DeferredSave.extensions.json	DEBUG	Starting write
1490088529472	addons.repository	DEBUG	No addons.json found.
1490088529472	DeferredSave.addons.json	DEBUG	Save changes
1490088529475	DeferredSave.addons.json	DEBUG	Starting timer
1490088529498	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1490088529498	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1490088529498	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1490088529502	DeferredSave.extensions.json	DEBUG	Write succeeded
1490088529502	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1490088529551	DeferredSave.addons.json	DEBUG	Starting write
1490088529582	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'NIGHT2', ip: '10.90.17.69', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at com.jcda.accelerators.TestEngine.reportHeader(TestEngine.java:524)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7057 after 45000 ms. Firefox console output:
e,"seen":true}
1490088525512	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1490088525513	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"fc-BepzaxfKm","location":"app-global","version":"45.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1460086235000,"updateDate":1460086235000,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0.2","maxVersion":"45.0.2"}],"targetPlatforms":[],"seen":true}
1490088525513	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1490088525515	DeferredSave.extensions.json	DEBUG	Save changes
1490088525515	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1490088525515	addons.xpi-utils	DEBUG	Updating add-on states
1490088525517	addons.xpi-utils	DEBUG	Writing add-ons list
1490088525521	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1490088525522	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.1.14
1490088525548	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1490088525548	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1490088525549	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1490088525574	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1490088525574	addons.manager	DEBUG	Provider finished startup: XPIProvider
1490088525574	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1490088525575	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1490088525575	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1490088525576	addons.manager	DEBUG	Starting provider: GMPProvider
1490088525586	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1490088525586	addons.manager	DEBUG	Provider finished startup: GMPProvider
1490088525587	addons.manager	DEBUG	Starting provider: PluginProvider
1490088525587	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1490088525587	addons.manager	DEBUG	Provider finished startup: PluginProvider
1490088525588	addons.manager	DEBUG	Completed startup sequence
1490088528590	DeferredSave.extensions.json	DEBUG	Starting write
1490088529472	addons.repository	DEBUG	No addons.json found.
1490088529472	DeferredSave.addons.json	DEBUG	Save changes
1490088529475	DeferredSave.addons.json	DEBUG	Starting timer
1490088529498	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1490088529498	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1490088529498	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1490088529502	DeferredSave.extensions.json	DEBUG	Write succeeded
1490088529502	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1490088529551	DeferredSave.addons.json	DEBUG	Starting write
1490088529582	DeferredSave.addons.json	DEBUG	Write succeeded
JavaScript error: chrome://fxdriver/content/server.js, line 61: uncaught exception: [object Object]
JavaScript error: chrome://fxdriver/content/server.js, line 61: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

**Comment by radeesh** [comment]
I have a similar issue, its different tests each time, but the error is same. We run 19 in parallel.
`
Error: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: cannot open display: :99
Error: cannot open display: :99
(org.openqa.selenium.firefox.NotConnectedException) (Selenium::WebDriver::Error::UnknownError)
[remote server] org.openqa.selenium.firefox.internal.NewProfileExtensionConnection(NewProfileExtensionConnection.java):118:in `start'
[remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):246:in `startClient'
[remote server] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java):114:in `'
[remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):193:in `'
[remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):186:in `'
[remote server] org.openqa.selenium.firefox.FirefoxDriver(FirefoxDriver.java):104:in `'
[remote server] sun.reflect.GeneratedConstructorAccessor10():-1:in `newInstance'
[remote server] sun.reflect.DelegatingConstructorAccessorImpl(DelegatingConstructorAccessorImpl.java):45:in `newInstance'
[remote server] java.lang.reflect.Constructor(Constructor.java):526:in `newInstance'
[remote server] org.openqa.selenium.remote.server.DefaultDriverProvider(DefaultDriverProvider.java):59:in `callConstructor'
[remote server] org.openqa.selenium.remote.server.DefaultDriverProvider(DefaultDriverProvider.java):53:in `newInstance'
[remote server] org.openqa.selenium.remote.server.DefaultDriverFactory(DefaultDriverFactory.java):54:in `newInstance'
[remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):214:in `call'
[remote server] org.openqa.selenium.remote.server.DefaultSession$BrowserCreator(DefaultSession.java):1:in `call'
[remote server] java.util.concurrent.FutureTask(FutureTask.java):262:in `run'
[remote server] org.openqa.selenium.remote.server.DefaultSession$1(DefaultSession.java):168:in `run'
[remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1145:in `runWorker'
[remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):615:in `run'
[remote server] java.lang.Thread(Thread.java):745:in `run'`

**Comment by akshat62** [comment]
Provide code.

Looks like incorrect binary path has been provided.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by p0deje** [comment]
Actually, we're not going to fix issues from 2.x version, so please upgrade to the latest Selenium version and (if possible) - start using GeckoDriver. If the issue is still there, please post.
