### ISSUE TITLE
ElementSendKeys command sending 'value' property rather than 'text'

### ISSUE THREAD

**Issue by hurrikam** [SeleniumHQ/selenium#3696]
## Meta -
OS: OSX El Capitan

Selenium Version: 3.3.0, Selenium-Webdriver for NodeJS

Browser: Chrome 

Browser Version: 56.0.2924.87 (64-bit)

## Expected Behavior -

Based on the current W3C specs the text passed to WebElement.sendKeys() should send to the remote end as a property named 'text':

https://www.w3.org/TR/webdriver/#element-send-keys

"The remote end steps for Element Send Keys are:

If the current browsing context is no longer open, return error with error code no such window.

...

Let text be the result of getting a property text from the parameters argument"

## Actual Behavior -

The current selenium-webdriver implementation sends the text as a property called 'value'

## Steps to reproduce -

This is being tested in a custom WebDriver server implementation.

**Comment by lmtierney** [comment]
This will need to be updated in all language bindings once it's implemented in geckodriver/Firefox

**Comment by lmtierney** [comment]
Updated in ruby 08870d4

**Comment by hurrikam** [comment]
Hi @lmtierney,
Could you please update the post once this gets fixed and released?

Thanks

**Comment by jimevans** [comment]
.NET sends both in the W3C case (and has since 7c33c5cf), because of changing spec language, and to preserve backward-compatibility with earlier remote ends. The extra property will be removed in the future.

**Comment by hurrikam** [comment]
Looking forward to the fix for the JS bindings :)
