### ISSUE TITLE
contextClick() freezes in Microsoft Edge.

### ISSUE THREAD

**Issue by laishrametao** [SeleniumHQ/selenium#3697]
## Meta -
OS:  
 Windows 10 Version 1607 Build 14393.693
Selenium Version:  
 2.53.0
Browser:  
Microsoft Edge

Browser Version:  
38.14393.0.0

## Expected Behavior -
Right click action should finish and browser window should close.
## Actual Behavior -
Right click action is done, but the execution freezes. When I manually click somewhere else in the browser, it continues as expected.
## Steps to reproduce -
`System.setProperty("webdriver.edge.driver",	"C:\\Workspaces\\MicrosoftWebDriver.exe");`
 `WebDriver driver = new EdgeDriver();`
 `driver.navigate().to("http://www.google.com");`
 `new Actions(driver).contextClick(driver.findElement(By.id("lst-ib"))).build().perform();`
 `if (driver != null) {`
	`driver.close();`
  ` }`

**Comment by lmtierney** [comment]
Please report Edge issues to Microsoft https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
