### ISSUE TITLE
Unable to press Right/Left/Up/Down key more than once using send_keys(Keys.Right)

### ISSUE THREAD

**Issue by patelami** [SeleniumHQ/selenium#3698]
## Meta -
OS:  OSX 10.11.16(El Capitan)
Selenium Version:  3.0.2
Browser:  safari 10
Browser Version:  11602.1.50.0.10

Unable to perform same key press event in safari (i.e no repetitive action can be performed using key press ).

Example: Unable to enter right key three times using code bellow.

driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT)
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT)
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT)
      
There is no error present, just that the second key press event is not actioned. However if another direction key is sent in the sequence then that works, but once a key direction is used then the same direction key doesn't work in the same safari driver session. 

Example, if the following is executed in a sequence in a single safari driver session, then:

driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT) #Works
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT) #Doesn't Work
driver.find_element_by_xpath("//body").send_keys(Keys.LEFT) #Works
driver.find_element_by_xpath("//body").send_keys(Keys.LEFT) #Doesn't Work

Example 2:
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT) #Works
driver.find_element_by_xpath("//body").send_keys(Keys.LEFT) #Works
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT) #Doesn't Work
driver.find_element_by_xpath("//body").send_keys(Keys.UP) #Works
driver.find_element_by_xpath("//body").send_keys(Keys.LEFT) #Doesn't Works

## Expected Behavior -
Bellow code should move focus to 2nd postion
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT)
driver.find_element_by_xpath("//body").send_keys(Keys.RIGHT) 

## Actual Behavior -
focus is moved once.

Note: The above example and steps works fine with the Firefox.

**Comment by p0deje** [comment]
Does it work with Firefox/Chrome?

**Comment by patelami** [comment]
It works fine with Firefox.

**Comment by p0deje** [comment]
Then I guess it's SafariDriver bug. Please, report it to https://bugreport.apple.com/.
