### ISSUE TITLE
Firefox and IE won't allow popup notification to dissapear (Edge and Chrome works)

### ISSUE THREAD

**Issue by luis-cortina** [SeleniumHQ/selenium#3699]
## Meta
OS:  
Windows 10
Selenium Version:  
C# bindings 3.3.0
Browser:  
 Internet Explorer, Firefox

Browser Version:  
Firefox 49.0.2623.87 (64-bit)

## Expected Behavior
Notification bar should close after 5~6 seconds as it happens on Chrome and Edge
## Actual Behavior
The notification Never Closes
## Steps to reproduce
[TestMethod]
    public void TestMethod1()
    {
      //var driver = new ChromeDriver();
      var driver = new FirefoxDriver();
      //var driver = new InternetExplorerDriver();
      driver.Navigate().GoToUrl("http://demo.nopcommerce.com");
      driver.Manage().Window.Maximize();

      var button = driver.FindElementByCssSelector
        ("[data-productid=\"18\"] input[value=\"Add to cart\"]");

      button.Click();
      // green bar on top appears but doesn't go away
      var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
      wait.Until(
        ExpectedConditions.ElementIsVisible(By.CssSelector("#bar-notification")));
      wait.Until(
        ExpectedConditions.InvisibilityOfElementLocated(By.CssSelector("#bar-notification")));

      driver.Quit();
    }

**Comment by lmtierney** [comment]
This is not selenium related. Please file a bug with the appropriate driver vendors

**Comment by lmtierney** [comment]
Missed the part of this mentioning IE driver. I suspect this is not at all related to the driver, but I'll let another decide that

**Comment by barancev** [comment]
It's a feature of the application: if a user clicks the green bar it becomes persistant and does not disappear in 5-6 seconds.

By deault legacy Firefox driver and IE driver scroll elements to the top, and when it clicks the element it (unintentially) touches the bar too.

To change this behavior in IE you have to pass an option:
```
InternetExplorerOptions options = new InternetExplorerOptions();
options.elementScrollTo(ElementScrollBehavior.BOTTOM);
InternetExplorerDriver driver = new InternetExplorerDriver(options);
```

To change this behavior in legacy Firefox driver:
```
FirefoxOptions options = new FirefoxOptions();
options.setLegacy(true);
options.addCapabilities(new ImmutableCapabilities(
        ImmutableMap.of(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, ElementScrollBehavior.BOTTOM)));
options.setBinary("C:/Program Files/Mozilla Firefox/firefox.exe");
FirefoxDriver driver = new FirefoxDriver(options);
```
