### ISSUE TITLE
Selenium IDE - Scheduler icon tool tip a little confusing.

### ISSUE THREAD

**Issue by JavaJeffG** [SeleniumHQ/selenium#370]
Thanks so much for the new Selenium IDE Scheduler... I'm really enjoying using it.

One suggestion, the clock tooltip reads "Turn test scheduler on/off" whether it is currently on or off.  It would be great if the tooltip would make it clear which state it is in.   I like how the Record icon tool tip reads either "Click to Record" or "Now Recording, Click to Stop Recording".

How about something like:

  *  "Click to turn Scheduler on"
   * "Scheduler now on, Click to turn Scheduler off"

Thanks,
         Jeff

**Comment by andreastt** [comment]
@JavaJeffG: This is a great getting started bug.  Please see [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) if you want to scratch your own itch and fix it.

**Comment by AJ-72** [comment]
@andreastt can you please check my PR?
