### ISSUE TITLE
Should selenium-api be a dependency in selenium-java (jars, maven poms) ?

### ISSUE THREAD

**Issue by ph-ms** [SeleniumHQ/selenium#3705]
http://central.maven.org/maven2/org/seleniumhq/selenium/selenium-java/3.3.1/selenium-java-3.3.1.pom doesn't cite selenium-api as a dependency, and it should perhaps.

**Comment by asashour** [comment]
`selenium-java` depends on `selenium-chrome-driver`, which depends on `selenium-remote-driver,` which depends on `selenium-api`.

So, it is already included, and is automatically handled by maven.

**Comment by ph-ms** [comment]
I'll check again, but a build I had failed when on only depended on `selenium-java` when it did not fail for a previous Se release ... and maven's able to handle transitive deps.

**Comment by asashour** [comment]
May be you have excluded some of the intermediate dependencies.

Check `mvn dependency:tree`, or `Dependency Hierarchy` in eclipse view of pom.xml.

**Comment by barancev** [comment]
selenium-java definitely have selenium-api in transitive dependencies.

**Comment by paul-hammant** [comment]
xref #3771.  I wonder if me and the other reporter have a corrupt jar somehow. I'm struggling to make a reproduction though.

**Comment by asashour** [comment]
Try to delete your `~/m2/repository`, and post your complete POM.

**Comment by paul-hammant** [comment]
I tried that. I'll try it again and report back. 

If does seem odd though that it works when I put ...

```
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-api</artifactId>
      <version>${selenium.version}</version>
    </dependency>
``` 

... in the pom (and fails without that).

**Comment by paul-hammant** [comment]
Solved it. Dep clash: selenium-api should be excluded from phantomjsdriver's dep

 <dependency>
      <groupId>com.codeborne</groupId>
      <artifactId>phantomjsdriver</artifactId>
      <version>1.4.1</version>
      <exclusions>
        
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-remote-driver</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
