### ISSUE TITLE
Testng maven dependency for selenium-leg-rc ... but should there be?

### ISSUE THREAD

**Issue by ph-ms** [SeleniumHQ/selenium#3706]
http://central.maven.org/maven2/org/seleniumhq/selenium/selenium-leg-rc/3.3.1/selenium-leg-rc-3.3.1.pom

Downstream Projects that pull this in have a problem in that some test-runners subsequently see the testing classes and invoke test-suite collection logic looking for testing annotated classes. Spoiler: those downstream maven projects might be using JUnit not TestNG (and a few fine grained permutations of problem).

**Comment by shs96c** [comment]
TestNG is required because of `SeleneseTestNgHelper` The dependency is needed.

**Comment by ph-ms** [comment]
Simon,  Can we add <optional>true</optional> to the declaration in the POM?

I have a build where I had to use the <excludes><exclude>..</exclude></excludes> incantation on the import, and (after that) that build worked just fine using legacy selenium **without** testng in the classpath.

- Paul H
