### ISSUE TITLE
@FindBys not returning elements when using with List<WebElement>

### ISSUE THREAD

**Issue by SergioLeone** [SeleniumHQ/selenium#3707]
## Meta -
OS:  Win7 x64

Selenium Version:  3.3.1

Browser:  Firefox

Browser Version:  49.0.2 (64)

## Expected Behavior -
Get a list of elements matching search criteria.
```
@FindBys ({
    @FindBy (xpath = "father"),
    @FindBy (xpath = "child")
}) public List<WebElement> elementsList;
```
This should return a list of all "child" elements that are under "father"

## Actual Behavior -
returns null;

## Steps to reproduce -

```
@FindBys({
@FindBy(xpath = "//div[@id='some-id']"),
@FindBy(xpath = "//div[@class='some class']")
}) public List<WebElement> elementsList;
```
should return a list of "some class" elements (located by second xpath) that are under "some id" elements (located by first xpath).

```
@FindBy(xpath = "//div[@class='some class']")
public List<WebElement> elementsList;
```
This is working fine

**Comment by SergioLeone** [comment]
```
@FindBys({
@FindBy(xpath = "//div[@id='some-id']"),
@FindBy(xpath = "div[@class='some class']")
}) public List<WebElement> elementsList;
```
This works somehow (note '//' removed from the beginning of second xpath locator), but is much slower than single @FindBy, and still does not always get all the elements

**Comment by shs96c** [comment]
A sample page would help demonstrate this problem. 

Question: if you use a regular `driver.findElement(By.xpath("father")).findElement(By.xpath("child"))` do you get the expected result?

**Comment by SergioLeone** [comment]
@shs96c, thanks for the response.
Do you mean a sample html page that I'm running my tests on? I don't think that would be possible.
I can try to use @FindBys strategy on some public website though if that would help.

I will try `driver.findElement(By.xpath("father")).findElement(By.xpath("child"))` when I get to work tomorrow and post the results here. 
But shouldn't we use driver.findElement**s** with a List<>?

**Comment by SergioLeone** [comment]
Tried reproducing with all possible scenarios and it seems to be working now. Closing the issue.
