### ISSUE TITLE
Use Get Element Rect/Set Element Rect when talking to W3C WebDriver remotes

### ISSUE THREAD

**Issue by andreastt** [SeleniumHQ/selenium#3710]
Selenium language bindings should use the Get Element Rect and Set Element Rect commands when talking to W3C WebDriver remotes:

* Set Element Rect: POST `/session/{session id}/window/rect`
* Get Element Rect: GET `/session/{session id}/window/rect`

These two endpoints replace the four endpoints used for setting- and getting window position, and setting- and getting the window size.

I haven’t yet investigated which language bindings this applies to.

**Comment by lmtierney** [comment]
Added the ruby tag, I have an update for this but haven't pulled it in yet

**Comment by andreastt** [comment]
To be clear, geckodriver doesn’t support the window rect commands yet, but will after https://github.com/mozilla/webdriver-rust/pull/83 lands and we upgrade the webdriver dependency in the next release of geckodriver (0.16.0).

**Comment by andreastt** [comment]
cc @AutomatedTester

**Comment by barancev** [comment]
Should be implemented in all bindings by now.
