### ISSUE TITLE
Java: Refactor page factory to be more extensible

### ISSUE THREAD

**Issue by paul-nelson-baker** [SeleniumHQ/selenium#3713]
I've been using selenium for a few years and one thing that's always been at the back of my mind is the PageFactory. Whenever I need to write custom annotations for someone to use instead of the FindBy variants, I find that the process is somewhat difficult to make extensible in a manor that chains annotation rules.

So say, I want to use the default built-in decorators, my own decorators, and then a third party's (EG: Selenide as an example) the code becomes soupy and I find that for whatever given project I'm re-inventing or outright copying the original code to get some sort of builder-pattern to enable chaining all of these decorators so PageObjects can have all annotations work as you'd expect them to.

Would SeleniumHQ be open to such a refactor? What would be an acceptable approach and what requirements would be needed? Some obvious ones I can thing of might be

- Keep the original PageFactory available for back-wards compatibility
- The new extendable page factory must be static like the original one (not a personal fan of this) 
- The new extendable page factory may be an instance so it can act within dependency injection frameworks (as an alternative to being static)

etc.

I'm more than willing to do the work on it, but I wanted to run this by people first before doing something that would result in a rejected pull-request.

**Comment by shs96c** [comment]
You're not the only one to want this:

https://github.com/SeleniumHQ/selenium/pull/3680

Does @paul-hammant's PR move in the right direction for you?

**Comment by paul-nelson-baker** [comment]
Love it! Definitely right-direction. I would have done more to give Selenide (and other similar frameworks that do their own WebElement extension magic) the potential for more first class inclusive-ness, but this would more than suite _my own_ selfish my needs.

What is the typical timeline for a pr being merged and released to nexus once approved?

**Comment by LinuxSuRen** [comment]
我在Selenium的基础上又开发了一套框架，可以提供给各位来参考https://github.com/LinuxSuRen/phoenix.framework

**Comment by paul-hammant** [comment]
Anyone wanting to see an actual implementation of WebDriver compatible page-factory-annotations for Java outside the Selenium codebase can look here https://github.com/paul-hammant/ngWebDriver/commit/117f23b40fd945dbdd4c16921fdae3d855bc1194 (yes, complete with speedy unit tests)

**Comment by diemol** [comment]
Closing as the mentioned PR got merged.
