### ISSUE TITLE
Mozilla Firefox cannot be programmatically closed after Selenium update

### ISSUE THREAD

**Issue by fond42518** [SeleniumHQ/selenium#3716]
## Meta

OS:  Windows 10 Home x64 (10.0.14393.0)
Selenium Version:  3.3.1
Browser:  Mozilla Firefox 5.0.1

## Expected Behavior

Firefox should close when `driver.close()` is called.

## Actual Behavior

Firefox (FF) does not close when `driver.close()` is called. Attempted to reinstall FF and upgrade Selenium, but the issue persists. This worked yesterday with the same version of FF, but no longer seems to work properly after executing `pip install -U selenium`. Other Selenium functions seem to work as intended with the exception of closing the browser, which must be closed manually. Also verified that I am using the latest Selenium Gecko webdriver.

## Steps to reproduce

```python
from selenium import webdriver
ff = webdriver.Firefox()
ff.close()
```

**Comment by fangli88** [comment]
@fond42518 I think quit() is more reliable than close().

**Comment by lmtierney** [comment]
`close()` will only close the current 'window' (tab or window, but not the program itself). Use `quit()` to actually quit firefox
