### ISSUE TITLE
IE Driver Beta: sendKeys doesn't work when using Selenium Server

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#3717]
## Meta -
OS: Windows 7
Selenium Version: a little after 3.3 (commit e9a906a)
Browser: Internet Explorer
Browser Version: 11, but I don't think the version is important for this one

IE Driver Beta Version: 3.3.99.1

## Expected Behavior -
Things should be typed into the input field.

## Actual Behavior -
Nothing is typed. There's an error message in the [IEDriver log](https://github.com/SeleniumHQ/selenium/files/869678/iedriver.log.txt):
```
W 2017-03-24 21:17:47:067 response.cc(92) Error response has status code 400 and message 'Missing parameter: text' message
```

## Steps to reproduce -

I'm pretty sure this is the Selenium Server's fault. The client is speaking OSS dialect to the Selenium Server, which is not correctly translating that to W3C when speaking to IEDriver.

#### send_keys.py
```py
import sys

from selenium import webdriver

driver = webdriver.Remote(
    command_executor=sys.argv[1],
    desired_capabilities={'browserName': 'internet explorer'})

driver.get('http://localhost/form.html')
elem = driver.find_element_by_id('t')
elem.send_keys('abc')
print '%s [%s]' % (elem.text == 'abc', elem.text)
```

#### form.html

```html
<input type="text" id="t" value="" />
```

**Comment by jimevans** [comment]
Fixed in 4b5a88d
