### ISSUE TITLE
Cannot get cookies from PDF-only windows when using IE with IEDriverServer

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#3721]
## Meta -
OS:  Windows 7
Selenium Version:  3.3.0
Browser:  IE
Browser Version:  11.0.9600.18617, Update Version: 11.0.40

## Expected Behavior -
Users should be able to obtain browser cookies from PDF-only browser windows.  This does not work using IEDriver server 3.3.0.0, but does work with ChromeDriver 2.28.455520 and GeckoDriver 0.15.0.

## Actual Behavior -
I get a Net::Timeout exception in Ruby.

## Steps to reproduce -

Step 1.  Open Internet Explorer
Step 2.  Navigate to a pdf (e.g., http://myserver/my_pdf.pdf)
Step 3.  Verify that the PDF is displayed in the main browser window.
Step 4.  Attempt to read the browser's cookies.  I'm using Ruby so for me, it's something like...

	cookie_string = ""

	# Read the cookie hash...
	$driver.manage.all_cookies.each { |cookie|
		# consolidate the cookie hash to a string 
                # (e.g., cookie_name1=cookie_val1;cookie_name2=cookie_val2;etc...)
	    	cookie_string = cookie_string + "#{cookie[:name]}=#{cookie[:value]};"  
	}

	puts "COOKIES! -> #{cookie_string}"

**Comment by jimevans** [comment]
This will never work for the IE driver. The driver can only retrieve cookies for pages that have a `document` object. This is not the case for Internet Explorer and directly browsing .pdf documents.

**Comment by DamienLyles** [comment]
Is this just a limitation of the way that the IEDriver is currently coded?  It works in 2.4.8.
