### ISSUE TITLE
Can't switch tabs for Firefox 52.0.1

### ISSUE THREAD

**Issue by shinba521** [SeleniumHQ/selenium#3722]
## Meta -
OS:  
Win10 x64
Selenium Version:  
3.3.1
Browser:  
Firefox 52.0.1

geckodriver 0.15.0

## Expected Behavior -

Firefox 47.0 can open new tab by "body.send_keys(Keys.CONTROL + 't')" and switch to new tab

## Actual Behavior -

Firefox 52.0.1 just stay in current tab, can't open new tab and switch it

## Steps to reproduce -

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

browser = webdriver.Firefox()
browser.maximize_window()
browser.get('http://tw.yahoo.com')
body = browser.find_element_by_tag_name("body")
body.send_keys(Keys.CONTROL + 't') 
browser.switch_to.window(browser.window_handles[-1])
browser.get('http://www.google.com')

**Comment by sauravkumar05** [comment]
Alternate method :  instead of using tab (Keys) have you tried using switch to method to move to different window handle

**Comment by lmtierney** [comment]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1332279 and not a selenium issue
