### ISSUE TITLE
Selenium Webdriver Gem doesn't play nice with RSpec "all" matchers

### ISSUE THREAD

**Issue by luke-hill** [SeleniumHQ/selenium#3724]
## Meta -
OS:  

Selenium Version:  2.53.4

Browser:  Irrespective (I used Chrome)

Browser Version:  Irrespective (I used latest Chrome)

## Expected Behavior -
When asking RSpec to perform `all` matching tests. They run and pass/fail accordingly
## Actual Behavior -
The following the error is thrown
```
Selenium::WebDriver::Error::InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.1.7601 SP1 x86_64)
```
## Steps to reproduce -
Try and perform one of the following inline tests
`expect(['23 apr 2017','23 apr 2017','23 apr 2017','23 apr 2017']).to all eq('23 apr 2017')`
`expect(['23 apr 2017','23 apr 2017','23 apr 2017','23 apr 2017']).to all include('23 apr 2017')`
`expect([1, 3, 5]).to all( be < 10 )`
`expect([1, 3, 5]).to all( be_odd.and be < 10 )`

**Comment by p0deje** [comment]
selenium-webdriver has nothing to do with that.

Do you use Capybara? If yes, then it probably mixes in `#all` method which collides with matcher.
