### ISSUE TITLE
[WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by EndermanAPM** [SeleniumHQ/selenium#3725]
## Meta -
Python: 
3.6.1 (32 and 64) 3.5.2 (64) and 3.5.3 (32)
OS:  
Windows 10 / 2012 
Selenium Version:  
2.53.6/2.53.4
Browser:  
Firefox 

Browser Version:  
37.0.2 x32/46.0.1 x32
## Expected Behavior -

A driver should start given the profile.

## Actual Behavior -

At random, it will fail raising WinError 6 and all the following tries will too.

## Steps to reproduce -
Although not showed here, i also tried it without the Thread and was also raising the same error.
```

def setup_firefox_driver(dPath):
    fp = webdriver.FirefoxProfile()
    fp.set_preference("browser.download.folderList", 2)
    fp.set_preference("browser.download.manager.showWhenStarting", False)
    fp.set_preference("browser.download.dir", dPath)
    # fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/pdf") #"
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream")
    fp.set_preference("pdfjs.disabled", True)
    return fp


def run(dPath):
    driver = webdriver.Firefox(firefox_profile=setup_firefox_driver(dPath))
    driver.close()

for x in range(100):
    t = threading.Thread(target=run, args=(x,))
    t.start()
    t.join()
```
This is one of the traces:
```

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "<input>", line 2, in run
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\firefox\extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 571, in __init__
    _cleanup()
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 195, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\xavi\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 990, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid

```

I would love to switch to selenium 3 but the action_chains doesn't seem to work not be supported.

Regards.

**Comment by aneeshchandy** [comment]
What do you mean the action_chains doesn't seem to work? Could you give some specifics?

I tried the below code in MacOS, Selenium 3.0.1, Python 2.7.10 and using Firefox 51.0.1 (x64), and it worked fine for me.

Maybe you could you upgrade the browser version and try again and see if it happens again?

```
import threading
from selenium import webdriver

def setup_firefox_driver(dPath):
    fp = webdriver.FirefoxProfile()
    fp.set_preference("browser.download.folderList", 2)
    fp.set_preference("browser.download.manager.showWhenStarting", False)
    fp.set_preference("browser.download.dir", dPath)
    # fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/pdf") #"
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream")
    fp.set_preference("pdfjs.disabled", True)
    return fp

def run(dPath):
    driver = webdriver.Firefox(firefox_profile=setup_firefox_driver(dPath))
    driver.close()

for x in range(3):
    t = threading.Thread(target=run, args=(x,))
    t.start()
    t.join()
```

I reduced the thread size to three. Does that matter?

>

**Comment by lmtierney** [comment]
100 threads so quickly does seem excessive

**Comment by EndermanAPM** [comment]
More up to date firefox versions doesn't seem to work very well (if they even do it) under Selenium 2

The thread size matters because the main problem is that spawning various selenium driver instances makes it crash.

Action chains are what is used in order to access something that requires a previous acction in order to be visible. ex. When there is a hidden button inside a dropdwon menu you need to hover so you can click it.
In my Selenium 2 program I have this code:
```python
element_to_hover_over = common.tryToFind(driver, "xpath", "//span[text()='Archivos e Informes']")
    hover = ActionChains(driver).move_to_element(element_to_hover_over).perform()
    try:
        elem = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, '//*[@title="Factel"]'))
        )
    finally:

        elem.click()
```
But even after I updated the code according to the selenium3 docs it doesn't seem to do anything.

**Comment by EndermanAPM** [comment]
@lmtierney The actual code does stuff inside each thread so every driver spawn may be a coupple minutes apart. Also, the t.join() makes so only one of the threads is running concurrently.

**Comment by lmtierney** [comment]
If you're running one thread at a time, why use threads?

**Comment by lmtierney** [comment]
Googling the error seems like it could be a threading issue

**Comment by EndermanAPM** [comment]
As I stated on the initial question (I also googled, that's why I tested running it under python 32bit) the issue is also present when replacing the threads with a loop.

The reason for the threads is that I was going to add paralelism to the process but I tryed to pinpoint the problem by aboiding them running at the same time. (a.k.a. just to make sure the firefox instances were fighting each other).
Also, running the selenium code in a thread prevents the main thread from stopping if a exception is raised in one of the threads. Although this could be achived by surrounding the function call with a try: except block. The fun part is that even after undoing all the threading and sorrounding the call with a try except the function call the WinError causes all the next iterations also to fail.

So, in the following example, if one of the iterations raises a winerror6, all the following will also crash.
```
for x in range(100):
    try:
        run(x)
    except:
        pass
```

Although I need to verify it I thing if i would place another loop after that one, it would start just fine. So I think the problem happens when driver instances are created in a loop.

**Comment by lmtierney** [comment]
Ah sorry I didn't see that part of your comment.

I have a setup where I run 5 threads at the same time with 5 chrome instances and I don't have the issue you're experiencing, but I'm also running on MacOS. If I get time later I may be able to get that setup on Windows, but I'm not promising anything

**Comment by 6a6ka** [comment]
Hi there,
got same error on win8 with python 3.5.1 selenium 2.55 and firefox 46
Stacktrace leads to same subprocess module. Exception occurs accidentally and seems no dependencies from my code - it may works perfectly while running through loop , but it also may crash on 2nd step

**Comment by hazardary** [comment]
Hi there,
I opened a new ticket #5316. You can see my workround there.

**Comment by p0deje** [comment]
I get it that #4503 should fix the problem. Please, re-open if it is still present.

**Comment by barancev** [comment]
Issue #4505 look similar to this one too, is it a duplicate?
