### ISSUE TITLE
unable to connect  MacOSX + Mozilla 52.0.2 +  geckodriver 0.15.0 + selenium 3.3.0

### ISSUE THREAD

**Issue by spurnaye** [SeleniumHQ/selenium#3726]
## Meta -
OS:  
OSX

Selenium Version:  
3.3.0 (using Ruby selenium-webdriver gem 3.3.0)
3.3.1 is not available!!!

Browser:  
Firefox 52.0.2
geckodriver 0.15.0

Browser Version:  
52.0.2 (64-bit)

## Expected Behavior -
Launch browser

## Actual Behavior -
```
Selenium::WebDriver::Error::WebDriverError: unable to connect to Mozilla geckodriver 127.0.0.1:4444
from /Users/<USER>/<GEMPATH>/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/service.rb:130:in `connect_until_stable'
```

## Steps to reproduce -
```
require 'selenium/webdriver'
 Selenium::WebDriver::Firefox::Binary.path = "/Users/#{ENV['USER']}/Applications/Firefox.app/Contents/MacOS/firefox"
Capybara::Selenium::Driver.new(app, :browser => :firefox)
session = Capybara::Session.new(:selenium)
session.visit('/')
```

**Comment by lmtierney** [comment]
This is working fine for our CI and I just tried it on Windows as well. I'm closing this unless you can provide code using Selenium only (no Capybara) and provide a stack trace. I'd make sure you don't have multiple versions of geckodriver installed `geckodriver --version`

**Comment by spurnaye** [comment]
Hi @lmtierney I do not have multiple versions of geckodriver installed,
Checked with just selenium (without Capybara) and working fine.
Seems to be an issue with Capybara. Thanks for your help!

**Comment by twalpole** [comment]
@spurnaye  Because your `Capybara::Selenium::Driver.new(app, :browser => :firefox)` code doesn't make sense on it's own - it needs to be part of a Capybara.register_driver block

**Comment by kannans5** [comment]
I am getting the same error as well.
`Selenium::WebDriver::Error::WebDriverError:
       unable to connect to Mozilla geckodriver 127.0.0.1:4444`

I am registering the driver like

`Capybara.register_driver :selenium do |app|
  if Helpers::BROWSER == :firefox
    Capybara::Selenium::Driver.new(
      app,
      browser: :firefox,
      marionette: true
    )
  else
    Capybara::Selenium::Driver.new app, browser: Helpers::BROWSER
  end
end`

using
geckodriver 0.16.1
Firefox 53.0 (64-bit)
selenium-webdriver (3.4.0)
