### ISSUE TITLE
W3C IEDriverServer crashes

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#3727]
Using IE11, Win8.1 Browser testing VM supplied by MS
Latest IEDriverServer for w3c (the .2.zip release)

For the test (in java, but you get the idea):

```
@Test
public void hereWeGo() throws MalformedURLException {
  InternetExplorerOptions options = new InternetExplorerOptions()
      .withInitialBrowserUrl("http://www.google.com");

  WebDriver driver = new RemoteWebDriver(
      new HttpCommandExecutor(new URL("http://192.168.0.15:5555/")),
       options.merge(DesiredCapabilities.internetExplorer()));

  driver.get("http://www.google.com");
  driver.findElement(By.name("q")).sendKeys("I like cheese");
}
```

The IEDriverServer.exe reliably crashes. The logs can be found here:

https://gist.github.com/anonymous/06b61a2b6a345923078dc936b7166e49

**Comment by jimevans** [comment]
Fixed in 307dc76d and 0326f5c7 on ie-w3c branch.
