### ISSUE TITLE
Ruby bindings: Security vulnerability in rubyzip dependency

### ISSUE THREAD

**Issue by andyentity** [SeleniumHQ/selenium#3728]
The `rubyzip` version required by the `selenium-webdriver` gem has a vulnerability that allows directory traversal:

https://github.com/rubyzip/rubyzip/issues/315, was fixed in version `1.2.1`

Not exactly sure how critical this is for the webdriver gem but an upgrade is highly appreciated in order to prevent dependeny conflicts due to different required versions, since other gems are upgrading to the latest `rubyzip` as well.

**Comment by BrianHawley** [comment]
From the gemspec:
```ruby
s.add_runtime_dependency 'rubyzip', ['~> 1.0']
```
"~> 1.0" includes 1.2.1, so no change would be needed to the selenium-webdriver gem.

**Comment by p0deje** [comment]
@BrianHawley is right, there is no strict dependency on rubyzip, so anyone can require 1.2.1.

On the other hand, I don't want to lock it to `>= 1.2.1` because that will a bunch of dependency conflicts.
