### ISSUE TITLE
IE Driver Beta: Check proxyType case-insensitively

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#3730]
## Meta -
OS:  Windows
Selenium Version:  3.3
Browser:  Internet Explorer
Browser Version:  all

IE Driver Beta: 3.3.99.3

## Expected Behavior -
Specifying `"proxyType": "MANUAL"` should be allowed.

The W3C spec actually doesn't say that yet, but it was supposed to say it :)
I have sent a PR (https://github.com/w3c/webdriver/pull/870), and I will also patch the Java bindings to send in lowercase. But we should still let this be case-insensitive.

## Actual Behavior -
>D 2017-03-28 15:26:02:911 server.cc(338) Response: {"value":{"data":null,"error":"session not created","message":"Invalid capabilities in alwaysMatch: a proxy type named MANUAL is specified, but proxy type must be 'pac', 'noproxy', 'autodetect', 'system', or 'manual'","stacktrace":""}}

**Comment by jimevans** [comment]
This is fixed in the Java bindings, and the spec isn't changing. I'm closing this one, as "by design".
