### ISSUE TITLE
Tests: executing JavaScript before a page is loaded

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/selenium#3735]
This is related to the Selenium test suite.

Regarding PageLoadingTest.[testShouldDoNothingIfThereIsNothingToGoBackTo()](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/PageLoadingTest.java#L277) and ExecutingJavascriptTest.[testShouldThrowExceptionIfExecutingOnNoPage()](https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/ExecutingJavascriptTest.java#L499)

The first one:

1. Calls `driver.getWindowHandles()`
2. Executes JavaScript
3. Is expected to succeed

The second one:

1. Executes JavaScript
2. Is expected to fail

I guess they are contradicting, or `driver.getWindowHandles()` is expected to allow execution of JavaScript somehow.

This is needed to make the `HtmlUnitDriver` pass for both.

Appreciate your feedback.

**Comment by barancev** [comment]
testShouldThrowExceptionIfExecutingOnNoPage is obviously wrong. That's why it is ignored in all browsers.

**Comment by barancev** [comment]
Changed the test: e07e0918d2a87b37711fc7049c1c29eedf0bcc0b
