### ISSUE TITLE
If I use the spring framework, concurrency is automated，it‘s ok？

### ISSUE THREAD

**Issue by paladinGu** [SeleniumHQ/selenium#3736]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
Issues are not a place for questions. Please see [Bug Reporting](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and as questions to the mailing list
