### ISSUE TITLE
每次操作元素都要请求浏览器获取焦点

### ISSUE THREAD

**Issue by LinuxSuRen** [SeleniumHQ/selenium#3739]
## Meta -
OS:  
win7
Selenium Version:  
3.*
Browser:  
chrome

Browser Version:  
57.0.2987.133

## Expected Behavior -
可以控制浏览器是否每次操作都获取焦点
## Actual Behavior -
无法控制

**Comment by LinuxSuRen** [comment]
是否有办法可以让浏览器不在每次操作时向操作系统请求获取焦点

**Comment by ruby186** [comment]
@LinuxSuRen ,
In those legacy drivers impl, for example firefox impl with runtime plugins before they applied w3c specs, the implementations are looks like "mixed mode", which means, some action logics are native impl, some are simulate by javascript.

native impl may possbile be required user interactive focus. Simulator may not(legacy safari should be a very nice example). you can try to change your code to simulate logic with javascript, a samler woud be:  

```ruby
driver.execute_script "$('#some_locator_here').mouseover();"
```  

This should be not block your desktop interactive session same as selenium remote-control.

btw, the biggest issue of this stupid webdriver-impls is StaleElementRefException. this should be handle by framework-client not the users. if a element is really not here, should raise element not found.

This cracy logic make the automation suite can not be stable. but webdriver donot care that...

**Comment by p0deje** [comment]
I'm going to close that as it looks more like a conversation between two people and there is a small chance somebody from maintainers can understand that.

**Comment by LinuxSuRen** [comment]
@ruby186 
thanks, may be i can review the driver code for find my solustion
