### ISSUE TITLE
Nodes are not reading hub's configuration during re-registering

### ISSUE THREAD

**Issue by SlavikCA** [SeleniumHQ/selenium#374]
Reproduced with Selenium 2.45
HUB: Linux, Ubuntu
Node: Windows 8, Chrome

Steps to reproduce:
**1) Start Selenium Grid. Let say, only 2 stations: HUB and NODE.**
For HUB, set timeouts, as:
"timeout": 20000
"browserTimeout": 20000
For NODE do not set any timeouts explicitly.
**2) Run this code against Grid:**

``` java
driver.get(url);
sleep(30000);
driver.get(url);
```

It fails with `org.openqa.selenium.remote.SessionNotFoundException`.
This line added to the NODE log:
`INFO org.openqa.selenium.remote.server.DriverServlet - Session 7f5fffec-4882-4c4c-b091-c780c66d379d deleted due to client timeout`
**3) So, trying to resolve issue, increase timeouts on the HUB:**
"timeout": 40000
"browserTimeout": 40000
Restart HUB. NODE would re-register automatically.

**Defect:**
Code still fails. Timeout still set at 20 seconds. But, if you look at the Grid console, it would show new (updated) configuration, which is misleading.
The reason: NODE haven't read new timeouts from the HUB.
NODE will only read that new configuration, when re-started.

**Expected:**
NODE would read configuration from the HUB, when re-registering.

**Comment by ddavison** [comment]
why are you setting your hub timeout to `20000` if you are going to sleep for `30000`?

**Comment by SlavikCA** [comment]
That was example. You are right, it's not the best.

Actually, issue which I had was, that after I installed Selenium with [Chef](https://supermarket.chef.io/cookbooks/selenium) default was [30 seconds](https://github.com/dhoer/chef-selenium/blob/master/resources/hub.rb), and I needed it to be longer.

So, the defect is that, that HUB configuration is not propagated ti the NODE, when it re-registering.

**Comment by mach6** [comment]
Assigning this to myself for follow up... Will apply any changes (if needed) to Se3.

**Comment by mmichaelis** [comment]
Observed the same issue when fixing misunderstood timeouts (seconds vs. milliseconds) on hub configuration (docker-selenium). We restarted the hub only but with no result. Restarting nodes helped, though.
