### ISSUE TITLE
setting ChromeDriver preferences Selenium Webdriver in Python

### ISSUE THREAD

**Issue by tashuiwuhen** [SeleniumHQ/selenium#3740]
OS:  
 Windows 7/10

Selenium IDE Version:  
 2.9.1

ChromeDriver Version:  
 2.28 

Browser:  
 Chrome

Browser Version:  
56.0.2924.87 m (32-bit) 

## Expected Behavior -

I'm using Selenium Webdriver (in Python) to automate the downloading of thousands of files. I want to set Chrome's download folder programmatically by avoiding pop up the download dialog box. 

## Actual Behavior -

 I tried this:

        prefs = {
            "profile.default_content_settings.popups" : 0,
            "download.default_directory" : self.download_directory.replace("/","\\")+"\\",
            "directory_upgrade": True,
            "extensions_to_open": ""
        }
        chrome_options.add_experimental_option("prefs", prefs)

No good. Downloads dialog box still pop up.

Any thoughts?

**Comment by cgoldberg** [comment]
are you specifically testing something where you need to download in the browser?  ... or are you just trying to retrieve the files?  If the latter, I would recommend skipping the browser's download mechanism and making http requests to each url directly.

**Comment by tashuiwuhen** [comment]
At first,Thanks for you help!
But your suggestion can not solve my problem.The file is dynamically generated,so it have to download through the browser.
In addition，When my friend run the same code on MAC operating systerm，the problem disappeared.I doubt it related to the OS.How can I sovle the problem on Windows OS?Thanks you again.

**Comment by lmtierney** [comment]
If it works for your friend then it's something in the way you're specifying the directory path. This also means it isn't a selenium issue so I am closing.

What does `print self.download_directory` give you?

**Comment by tashuiwuhen** [comment]
@lmtierney @cgoldberg self.download_directory is .download/test/browser1
The problem appeared when the code ran on Winsdows OS , but disappeared when the code ran on MAC OS. Windows OS can be reproduced.

**Comment by lmtierney** [comment]
@tashuiwuhen use an absolute path and not a relative path

**Comment by tashuiwuhen** [comment]
@lmtierney  Thanks for your help! The problem solve by use an absolute path and not a relative path.
