### ISSUE TITLE
ChromeOptions AddLocalStatePreference problem

### ISSUE THREAD

**Issue by siilens** [SeleniumHQ/selenium#3746]
## Meta -
OS:  Windows 7

Selenium Version:  3.3

Browser:  ChromeDriver 2.28

Browser Version:  57

Hello, why i cannot add Local State preference for ChromeDriver? 
In my Local State file: 
`"enabled_labs_experiments":["prefer-html-over-flash@1"],`
And I would like ChromeDriver to load my "enabled_labs_experiments" settings. And this is what I tried to do in C#:
` ChromeOptions options = new ChromeOptions();
  options.AddLocalStatePreference("browser.enabled_labs_experiments", "[\"prefer-html-over-flash@1\"]");
`
Also i tried to
`options.AddLocalStatePreference("browser.enabled_labs_experiments", "prefer-html-over-flash@1");
`
But it doesn't work as I browse chrome://flags with Chrome browser, that setting is still showing "Default" instead of "Enabled". Can you tell me how can i enable labs experiments now, please?

**Comment by lmtierney** [comment]
Where are you getting that preference? `chrome://flags` is not equivalent to preferences. Preferences available are found in the Preferences file for your profile. I just looked, and that preferences is not in the Preferences file. I am closing this until you can come up with a reproducible test case to show that C# is not setting the preference right.

https://www.chromium.org/administrators/configuring-other-preferences

**Comment by siilens** [comment]
ChromeOptions.AddLocalStatePreference Method
"Adds a preference for the local state file in the user's data directory for Chrome. If the specified preference already exists, it will be overwritten."

I have just found an error, why it does not work
This is my Chrome Local State file
`"browser":{"enabled_labs_experiments":["prefer-html-over-flash@1"],`

This is Local state file in scoped_dir1***, when i'm using this:
`options.AddLocalStatePreference("browser.enabled_labs_experiments", "[\"prefer-html-over-flash@1\"]");`
`"browser":{"enabled_labs_experiments":"[\"prefer-html-over-flash@1\"]"}`
As you see, it adds this preference in Local State, but using wrong structure?

**Comment by lmtierney** [comment]
Like I said before, "browser.enabled_labs_experiments" nor "enabled_labs_experiments" are chrome preferences. You are trying to set a flag which is NOT a preference. Preferences will not have a `.` in them. Using a `.` insinuates that it should be structured as `"browser":{"enabled_labs_experiments":"[\"prefer-html-over-flash@1\"]"}`.

**Comment by siilens** [comment]
Ok, can you please explain me how can i set this preference?

**Comment by lmtierney** [comment]
You'll need to ask the chrome/chromium people what you need to set if it's possible

**Comment by skyiea** [comment]
@lmtierney Not sure why you refer to [the guide](https://www.chromium.org/administrators/configuring-other-preferences) when talking about available preferences. Here is [a complete list of possible preferences](https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup), which [contains](https://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/pref_names.cc?view=markup#l879) above-mentioned preference.
