### ISSUE TITLE
After PageFactory.InitElements, no refresh

### ISSUE THREAD

**Issue by Rogreis** [SeleniumHQ/selenium#3748]
After a PageFactory.InitElements, an element has its content changed, but this is not shown in the element. Or a content refresh is not done (without the attribute CacheLookup)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
