### ISSUE TITLE
Calling window.stop throws permission denied exception

### ISSUE THREAD

**Issue by chrisspen** [SeleniumHQ/selenium#3759]
## Meta -
OS:  Ubuntu 16.04
Selenium Version: 3.3.2 
Browser:  Firefox 45.0.2 with Geckodriver 0.15.0

## Steps to reproduce -
1. Try to execute `browser.execute_script('window.stop();')`
2. Receive error `WebDriverException: Message: Error: Permission denied to access property "stop"`

I was calling this just before a call to `browser.get(url)` to ensure the browser wasn't still loading, and after a recent Firefox/Selenium update (I'm not sure which), this now throws an exception.

**Comment by AutomatedTester** [comment]
This has been fixed in Firefox 48+. Please upgrade your Firefox. Current released version is 52 which has a lot of good features.
