### ISSUE TITLE
http request times out when application is run as a service in windows

### ISSUE THREAD

**Issue by reinjunon** [SeleniumHQ/selenium#3765]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.3.0
Browser:  
Firefox
WebDriver:
Gecko 0.15.0

Browser Version:  
firefox 52.0.2

The issue below happens only when run as a windows service. There are no issues when the validator is run as a console application.

Code that causes this exception:
wait.Until(ExpectedConditions.ElementToBeClickable(by));

Exception:
e1 = {"The HTTP request to the remote WebDriver server for URL http://localhost:64819/session/6e11eff8-ad12-4f55-a0cb-9038a4f987ce/element timed out after 30 seconds."}

Stack trace:
"   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\HttpCommandExecutor.cs:line 170\r\n   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\HttpCommandExecutor.cs:line 121\r\n   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\DriverServiceCommandExecutor.cs:line 84\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\RemoteWebDriver.cs:line 1102\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\RemoteWebDriver.cs:line 1143\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByCssSelector(String cssSelector) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\RemoteWebDriver.cs:line 880\r\n   at OpenQA.Selenium.By.<>c__DisplayClass1e.<CssSelector>b__1c(ISearchContext context) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\By.cs:line 288\r\n   at OpenQA.Selenium.By.FindElement(ISearchContext context) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\By.cs:line 303\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by) in c:\\Projects\\webdriver\\dotnet\\src\\webdriver\\Remote\\RemoteWebDriver.cs:line 435\r\n   at OpenQA.Selenium.Support.UI.ExpectedConditions.<>c__DisplayClass3b.<ElementToBeClickable>b__3a(IWebDriver driver) in c:\\Projects\\webdriver\\dotnet\\src\\support\\UI\\ExpectedConditions.cs:line 434\r\n   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition) in c:\\Projects\\webdriver\\dotnet\\src\\support\\UI\\DefaultWait{T}.cs:line 182\r\n   at DailyValidator.Company.Interact(IWebDriver driver, WebDriverWait wait, String logPath, By by, String data, String log, Boolean clickTwice) in C:\\Users\\dummy_user\\documents\\visual studio 2015\\Projects\\DailyValidator\\DailyValidator\\Company.cs:line 131"

**Comment by AutomatedTester** [comment]
Like IEDriver and ChromeDriver are not designed to be run as a service so may not work. Please run with a real user with a real desktop mananger.
