### ISSUE TITLE
User cannot switch to an iframe and interact with its elements if the iframe is off screen

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#3767]
## Meta -
OS:  
Windows 7

Selenium Version:  
selenium-webdriver (3.3.0), geckodriver 0.15.0
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

Browser:  
Firefox

Browser Version:  
52.0

## Expected Behavior -
The user should be able to switch to an iframe without 1st scrolling it into view.  The user should then be able to interact with elements inside of the iframe.  This may be related to issue 2377, but I am not sure.

## Actual Behavior -
The user is NOT able to switch to an iframe without 1st scrolling it into view.  The code seems to be switching to the iframe, but the user will NOT be able to interact with elements inside of the iframe.

## Steps to reproduce -
Bring up a page that has an iframe below the section of the page that is currently displayed (e.g., an iframe that the user would need to get to by 1st pressing Page Down on the keyboard).  
Without scrolling the iframe into view, attempt to switch to the iframe.
Attempt to interact with an element inside of the iframe.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

I will gladly reopen when that information is there.

**Comment by DamienLyles** [comment]
Sample html 
https://jsfiddle.net/0hdtcyjz/40/

On the sample jsfiddle page...
1.  Click the 'Update iFrame' button.  This will load an HTML form into the iFrame found at the bottom of the page, but the user would still need to scroll to get to the iframe.  Do NOT scroll to the iframe.
2. Switch to the iframe using something like
driver.switch_to.frame driver.find_element(:id,'iframe_id')
3.  Attempt to click button1 in the frame
driver.find_element(:xpath, "//*[@value='button1']")

Selenium will NOT be able to click the button

**Comment by DamienLyles** [comment]
Please re-open.  I have added the additional information that was requested.
