### ISSUE TITLE
.NET bindings - Actions.Perform() is broken for a wrapped IWebDriver that implements IHasInputDevices in Selenium 3.0

### ISSUE THREAD

**Issue by bondyja** [SeleniumHQ/selenium#3770]
We have a WebDriverWrapper class that is implementing IHasInputDevices (since this used to be a requirement with Selenium 2.0)

As a result, in the constructor of Actions(), our wrapped driver is being saved as the driver for the Actions instance. This is causing .Perform() to throw a NullReferenceException since it tries to cast the wrapped driver object to IActionExecutor, which fails, and then on the following line checks "if (actionExecutor.IsActionExecutor)"

This is not a critical issue since we can work around the problem by removing IHasInputDevices from our wrapper and adding IWrapsDriver , but is still inconvenient.

**Comment by jimevans** [comment]
Wrapper classes must implement `IActionExecutor` for use with the `Actions` class. This requirement was added as part of the move to support the W3C WebDriver Specification.

**Comment by glenner003** [comment]
Why were Actions IHasInputDevices,  IActionExecutor not included in the IWebDriver interface? To me this seems a very weird way of working with interfaces, and introduces lots of limitations.

**Comment by barancev** [comment]
@glenner003 FYI: there are drivers that don't implement all of these interfaces, e.g. https://github.com/SimpleBrowserDotNet/SimpleBrowser.WebDriver
