### ISSUE TITLE
Selenium Remote: cannot access org.openqa.selenium.interactions.Interactive   

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [SeleniumHQ/selenium#3771]
Since Selenium 3.2.0 RemoteWebDriver initialization fail as the project is compiled with error:
java: cannot access org.openqa.selenium.interactions.Interactive
  class file for org.openqa.selenium.interactions.Interactive not found

Library versions from pom: 
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <testng.version>6.11</testng.version>
        <allure.version>1.5.2</allure.version>
        <aspectj.version>1.8.6</aspectj.version>
        <properties-loader.version>1.6</properties-loader.version>
        <selenide.version>4.4</selenide.version>
        <slf4j-nop.version>1.7.25</slf4j-nop.version>
        <maven-surefire-plugin.version>2.19.1</maven-surefire-plugin.version>
        <org.seleniumhq.selenium.version>3.3.1</org.seleniumhq.selenium.version>
        <jsoup.version>1.10.2</jsoup.version>
        <org.yaml.version>1.18</org.yaml.version>
        <org.json.version>20160810</org.json.version>
        <allure-maven-plugin.version>2.5</allure-maven-plugin.version>
    </properties>
Both _**import org.openqa.selenium.interactions.Interactive;**_ and **_import org.openqa.selenium.interactions.Sequence;_** are not found in RemoteWebDriver.java v.3.1.0+

![selenium remote](https://cloud.githubusercontent.com/assets/9446141/24719874/f3b86a8e-1a43-11e7-824d-d66e85809776.png)
As far as I change org.seleniumhq.selenium.version to 3.1.0 - compile throws no errors.

**Comment by barancev** [comment]
Run mvn dependency:tree and watch if you have an old selenium version in the classpath.

**Comment by paul-hammant** [comment]
This was the root cause of #3705 too.

**Comment by AlexanderPoleschuk** [comment]
It seems that dependency to 3.1.0 goes from phantomjsdriver of Selenide:
**+- com.codeborne:phantomjsdriver:jar:1.4.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-api:jar:3.1.0:compile**

I'll communicate with Selenide developer.
@barancev Thanks for tips to find out the root cause.

Full output of mvn dependency:tree:
[INFO] Project:Project:jar:1.0-SNAPSHOT
[INFO] +- org.testng:testng:jar:6.11:compile
[INFO] |  \- com.beust:jcommander:jar:1.64:compile
[INFO] +- ru.yandex.qatools.properties:properties-loader:jar:1.6:compile
[INFO] |  \- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |     \- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] +- com.codeborne:selenide:jar:4.4:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.0:compile
[INFO] |  +- com.google.guava:guava:jar:21.0:compile
[INFO] |  +- net.lightbody.bmp:browsermob-core:jar:2.1.4:compile
[INFO] |  |  +- net.lightbody.bmp:littleproxy:jar:1.1.0-beta-bmp-15:compile
[INFO] |  |  |  \- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.8.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.5:compile
[INFO] |  |  +- dnsjava:dnsjava:jar:2.1.7:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.22:compile
[INFO] |  |  +- com.jcraft:jzlib:jar:1.1.3:compile
[INFO] |  |  +- io.netty:netty-all:jar:4.0.42.Final:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.56:compile
[INFO] |  |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.56:compile
[INFO] |  |  \- net.lightbody.bmp:mitm:jar:2.1.4:compile
[INFO] |  +- com.codeborne:phantomjsdriver:jar:1.4.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-api:jar:3.1.0:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- ru.yandex.qatools.allure:allure-testng-adaptor:jar:1.5.2:compile
[INFO] |  \- ru.yandex.qatools.allure:allure-java-aspects:jar:1.5.2:compile
[INFO] |     +- ru.yandex.qatools.allure:allure-java-adaptor-api:jar:1.5.2:compile
[INFO] |     |  +- ru.yandex.qatools.allure:allure-java-annotations:jar:1.5.2:compile
[INFO] |     |  |  \- ru.yandex.qatools.allure:allure-model:jar:1.5.2:compile
[INFO] |     |  |     +- org.jvnet.jaxb2_commons:jaxb2-basics-runtime:jar:0.9.3:compile
[INFO] |     |  |     \- ru.qatools.commons:properties:jar:2.0.RC5:compile
[INFO] |     |  \- org.apache.tika:tika-core:jar:1.7:compile
[INFO] |     \- org.aspectj:aspectjrt:jar:1.8.3:compile
[INFO] +- org.slf4j:slf4j-nop:jar:1.7.25:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.jsoup:jsoup:jar:1.10.2:compile
[INFO] +- org.seleniumhq.selenium:selenium-java:jar:3.3.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.3.1:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-remote-driver:jar:3.3.1:compile
[INFO] |  |     +- cglib:cglib-nodep:jar:3.2.4:compile
[INFO] |  |     +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |     +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |     \- net.java.dev.jna:jna-platform:jar:4.1.0:compile
[INFO] |  |        \- net.java.dev.jna:jna:jar:4.1.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.3.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.3.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.3.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.3.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.3.1:compile
[INFO] |  \- org.seleniumhq.selenium:htmlunit-driver:jar:2.24:compile
[INFO] |     +- org.seleniumhq.selenium:selenium-support:jar:3.3.1:compile (version selected from constraint [2.53.0,4.0.0))
[INFO] |     |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |     |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |     |  \- junit:junit:jar:4.12:compile
[INFO] |     \- net.sourceforge.htmlunit:htmlunit:jar:2.24:compile
[INFO] |        +- xalan:xalan:jar:2.7.2:compile
[INFO] |        |  \- xalan:serializer:jar:2.7.2:compile
[INFO] |        +- org.apache.httpcomponents:httpmime:jar:4.5.2:compile
[INFO] |        +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.23:compile
[INFO] |        +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.24:compile
[INFO] |        |  \- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |        |     \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |        +- net.sourceforge.cssparser:cssparser:jar:0.9.21:compile
[INFO] |        |  \- org.w3c.css:sac:jar:1.3:compile
[INFO] |        +- commons-io:commons-io:jar:2.5:compile
[INFO] |        \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.20.v20161216:compile
[INFO] |           +- org.eclipse.jetty:jetty-util:jar:9.2.20.v20161216:compile
[INFO] |           +- org.eclipse.jetty:jetty-io:jar:9.2.20.v20161216:compile
[INFO] |           \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.20.v20161216:compile
[INFO] |              \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.20.v20161216:compile
[INFO] +- org.yaml:snakeyaml:jar:1.18:compile
[INFO] \- org.json:json:jar:20160810:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.125 s
[INFO] Finished at: 2017-04-10T12:29:37+03:00
[INFO] Final Memory: 18M/208M
[INFO] ------------------------------------------------------------------------

![maven](https://cloud.githubusercontent.com/assets/9446141/24855294/d044efec-1de9-11e7-945f-002a1a46f0b2.png)

**Comment by AlexanderPoleschuk** [comment]
Update to selenide 4.4.2 have solved the issue. 
You can close the ticket.

**Comment by paul-hammant** [comment]
How would you have solved it with an <excludes> section, for the dep?

**Comment by AlexanderPoleschuk** [comment]
@paul-hammant in my case the solution was just to update Selenide version to a newer one.
As you may see from screenshot above and from dependency tree, there were an out-dated dependency 
+- com.codeborne:phantomjsdriver:jar:1.4.1:compile
[INFO] | | - org.seleniumhq.selenium:selenium-api:jar:3.1.0:compile
that prevented to load a new version of selenium api.
Selenide 4.4.2 uses runtime dependency for phantomjsdriver, therefore it's not an issue for my project anymore.

**Comment by paul-hammant** [comment]
The other technique is an exclude:

```
 <dependency>
      <groupId>com.codeborne</groupId>
      <artifactId>phantomjsdriver</artifactId>
      <version>1.4.1</version>
      <exclusions>
        <!--
           phantomjsdriver 1.4.1 has a dep on Selenium 3.1.0 :-(
           Refer:
           http://mvnrepository.com/artifact/com.codeborne/phantomjsdriver/1.4.1
        -->
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-remote-driver</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
