### ISSUE TITLE
chromedriver big alert 

### ISSUE THREAD

**Issue by lbottoni** [SeleniumHQ/selenium#3773]
## Meta 
OS:  Windows 10
Selenium Version:  IDE 2.9.1
Browser:  Firefox OK, chrome KO
Browser Version:  Chrome Versione 56.0.2924.87 (64-bit)
## Steps to reproduce -

- set in options->WebDriver chrome e check enable flag
- open cmd
- java -jar -Dwebdriver.chrome.driver=%HOMEPATH%\Downloads\Selenium\driver\chromedriver.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar

> 10:16:54.259 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
> 10:16:54.261 INFO - Launching a standalone Selenium Server
>  2017-04-06 10:16:54.280:INFO::main: Logging initialized @272ms to org.seleniumhq.jetty9.util.log.StdErrLog
> 10:16:54.344 INFO - Driver class not found: com.opera.core.systems.OperaDriver
> 10:16:54.344 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
> 10:16:54.345 INFO - Driver class not found: com.opera.core.systems.OperaDriver
> 10:16:54.345 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
> 10:16:54.352 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
> 2017-04-06 10:16:54.423:INFO:osjs.Server:main: jetty-9.2.20.v20161216
> 2017-04-06 10:16:54.476:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@6d4b1c02{/,null,AVAILABLE}
> 2017-04-06 10:16:54.661:INFO:osjs.AbstractConnector:main: Started ServerConnector@64bfbc86{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
> 2017-04-06 10:16:54.662:INFO:osjs.Server:main: Started @653ms
> 10:16:54.662 INFO - Selenium Server is up and running

- now form firefox , open IDE selenium e try any simple command

chrome is opened, but i see a big alert message, and any action selenium work. with firefox all work fine

`
[error] <!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/> <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" /> <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script> <script src="/assets/displayhelpservlet.js" type="text/javascript"></script> <script type="text/javascript"> var json = Object.freeze('{"version":"3.3.1","type":"Standalone","consoleLink":"/wd/hub"}'); </script> </head> <body> <div id="content"> <div id="help-heading"> <h1><span id="logo"></span></h1> <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2> </div> <div id="content-body"> <p> Whoops! The URL specified routes to this help page. </p> <p> For more information about Selenium <span class="se-type"></span> please see the <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>. <span id="console-item"> Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>. </span> </p> <p> Happy Testing! </p> </div> <div> <footer id="help-footer"> Selenium is made possible through the efforts of our open source community, contributions from these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>. </footer> </div> </div> </body> </html>
`

**Comment by lbottoni** [comment]
big alert

`Received command response (!=OK/ERROR): <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"version":"3.3.1","type":"Standalone","consoleLink":"/wd/hub"}');
  </script>
</head>
<body>

<div id="content">
  <div id="help-heading">
    <h1><span id="logo"></span></h1>
    <h2>Selenium <span class="se-type"></span>&nbsp;v.<span class="se-version"></span></h2>
  </div>

  <div id="content-body">
    <p>
      Whoops! The URL specified routes to this help page.
    </p>
    <p>
      For more information about Selenium <span class="se-type"></span> please see the
      <a class="se-docs">docs</a> and/or visit the <a class="se-wiki">wiki</a>.
      <span id="console-item">
        Or perhaps you are looking for the Selenium <span class="se-type"></span> <a class="se-console">console</a>.
      </span>
    </p>
    <p>
      Happy Testing!
    </p>
  </div>

  <div>
    <footer id="help-footer">
      Selenium is made possible through the efforts of our open source community, contributions from
      these <a href="https://github.com/SeleniumHQ/selenium/blob/master/AUTHORS">people</a>, and our
      <a href="http://www.seleniumhq.org/sponsors/">sponsors</a>.
   </footer>
  </div>
 </div>

</body>
</html>
 Request Data: cmd=getNewBrowserSession&1=*webdriver&2=http%3A%2F%2Fmnm-webapp.docker.localhost%2F&3=&4=webdriver.remote.sessionid%3D3176527d-ed19-4a13-b269-f6f6c83ce44a`

**Comment by QA-Entropy** [comment]
I am seeing the same behavior in 2 of my test environments as well. This issue seems to be specific to using the Selenium Standalone server with any of the Drivers for WebDriver Playback (Chrome, FireFox, IE, IE Edge. Firefox works fine when using straight from IDE but breaks when talking to the Selenium Server.

**Comment by lbottoni** [comment]
yes,this to replicate


- open cmd
- send command: java -jar -Dwebdriver.ie.driver=%HOMEPATH%\Downloads\Selenium\driver\IEDriverServer32.exe %HOMEPATH%\Downloads\Selenium\driver\selenium-server-standalone-3.3.1.jar
- open selenium IDE 
- go to options>options>WebDriver
- Enable WebDriver
- set "internet explorer"
- close and reopen selenium IDE

this is my simple testcase

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://www.google.it/" />
<title>google</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">google</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/?gws_rd=ssl</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=lst-ib</td>
	<td>test</td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>name=btnK</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=lst-ib</td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>`

for any step the IDE open a new blank window of internet explorer with that message. All step test fail

**Comment by devBarn** [comment]
I get this as well

OS: Windows 10
Selenium Version: IDE 2.9.1
Browser: Chrome KO
Browser Version: Chrome Version 58.0.3029.81 (64-bit)

**Comment by QA-Entropy** [comment]
*Additional Information*
I did some additional testing and the Selenium Standalone Server has been broken with this error since the release of 3.0. I tested this with 2.53.1 using WebDriver Playback with Chrome and it is working, ie and firefox do not work. I also tested with the most recent release (3.4.0-as of April 21, 2017) and for: chrome, ie and firefox, I am still getting the same initially reported behavior.

OS: Windows 10
Selenium Version: IDE 2.9.1
Selenium Standalone Server: 2.53.1
Chrome Driver: 2.29
Status: Working

**Comment by ilyavinogradov** [comment]
Specifying `http://127.0.0.1:4444/wd/hub` instead of `http://localhost:4444/wd/hub` as `seleniumAddress:` in the config file solved the problem.

**Comment by QA-Entropy** [comment]
The seleniumAddress: located in which config file?

**Comment by ilyavinogradov** [comment]
@QA-Entropy In the config file used by protractor (typically name `protractor.conf.js` but could be named differently and specified when you run `protractor <config file>.js` on th command line). Here are he contents of my config file (taken from the protractor tutorial):
```
exports.config = {
	framework: 'jasmine',
	seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
	specs: ['spec.js']
}
```

**Comment by QA-Entropy** [comment]
**@ilyavinogradov** Thank you for the clarification. Sadly the issue I am seeing is specific to using the Selenium IDE plugin for Firefox in conjunction with the Selenium Stand Alone Server. Do you know of a way to implement the same configuration with IDE?

**Comment by flostaj** [comment]
![record_oynatilinca_cikan_sorun](https://user-images.githubusercontent.com/30079493/28072967-1791d8ae-665d-11e7-8a00-791acf4a570a.PNG)
 Can you help me please?

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
