### ISSUE TITLE
Java HtmlUnitDriver, the method get() does not load the page 

### ISSUE THREAD

**Issue by ajimenezv** [SeleniumHQ/selenium#3777]
Hi!
I'm having some problems using the driver in a java application, the method get the second time i use it, does not load the page. I'm working on a linux 3.10 machine with java 1.8 and i have the latest distribution of selenium 3.3.1. Here's some the code which im having problems:

`DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability(CapabilityType.PROXY, proxy);
cap.setJavascriptEnabled(true);
driver = new HtmlUnitDriver(cap);
driver.get("http://data.theice.com/MyAccount/Login.aspx?ReturnUrl=~\\ViewData\\Default.aspx");`
(... Use some elements...)
Here i simulate a log in process filling the info. and submit the info. 

`driver.get("http://data.theice.com/ViewData/EndOfDay/FuturesReport.aspx");`
<-- Here does not load and remain in the first page.
`System.out.println(driver.getTitle());`
I tested this solution on a windows machine and it worked normally, however in the linux machine it doesnt load. 
I hope you can help me with this problem,
Thank you.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
