### ISSUE TITLE
2.29 Fails on startup with Chrome 57 and Mac OSX

### ISSUE THREAD

**Issue by owenkealey** [SeleniumHQ/selenium#3779]
<img width="1052" alt="screen shot 2017-04-05 at 23 49 03" src="https://cloud.githubusercontent.com/assets/26207512/24764979/1f618cc6-1ac4-11e7-90fd-df70d753ff8c.png">

this problem does not occur on any other os

**Comment by schmidtkp** [comment]
Your trace indicates your ChromeDriver is v2.9.x *not* v2.29. Are you sure you are using the correct ChromeDriver version?

**Comment by lmtierney** [comment]
As @schmidtkp stated, your traceback says you are using chromedriver `2.9`, please upgrade to `2.29`
