### ISSUE TITLE
perform() explodes on webdriverjs 2.45.x

### ISSUE THREAD

**Issue by scott2449** [SeleniumHQ/selenium#378]
Take this simple example:

```javascript
var webdriver = require('selenium-webdriver');

var driver = new webdriver.Builder().
   withCapabilities(webdriver.Capabilities.chrome()).
   build();

driver.get('http://www.google.com');
var searchBox = driver.findElement(webdriver.By.name('q'));
driver.actions().mouseMove(searchBox).perform();
searchBox.sendKeys('awesome');
searchBox.getAttribute('value').then(function (value) {
  console.info('awesome');
});

driver.quit();
```

Run it on 2.44 and it will work just fine, fails on 2.45. Comment out the actions/perform line and it works. I have found that regardless of the placement, action, or context this command just fails now. **Also this is an issue with the driver as the results are identical with every browser and versions 2.44 and 2.45 of selenium server. It also happens for every action I tried, move, click, etc**

Error in this particular example:
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=41.0.2272.104)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64)
```
Though I have also seen *Unknown Error: null*

**Comment by scott2449** [comment]
Error in this particular example:
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=41.0.2272.104)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.2 x86_64)
```
Though I have also seen *Unknown Error: null*

**Comment by scott2449** [comment]
@andreastt any eta on investigation / resolution on this one? I need the timeline in order to decide whether to release my library with 2.45 or 2.44 (or prioritize looking deeper myself). I really want the enhancements from 2.45 but I think this bug makes it's unusable for 80% of my users.

**Comment by andreastt** [comment]
Please investigate deeper if you can.  I don't use the JS bindings, so I can't possibly comment on any ETA.  Maybe @jleyba could have a look?

**Comment by jleyba** [comment]
My time to work on Selenium is a bit limited at the moment. It may be a while before I have a chance to investigate.

**Comment by scott2449** [comment]
Thanks for the update guys! 

I'll try and carve out some time to dig deeper. @jleyba suggestions on the best places to start looking?

**Comment by scott2449** [comment]
@jleyba I found the breaking change see my comment on https://github.com/SeleniumHQ/selenium/commit/da11d39a7884af64000c4875597583610abb7f79

**Comment by scott2449** [comment]
:+1: for all the additional tests! Add 5 characters of code and 100 line of tests :smirk:

**Comment by jleyba** [comment]
That's what happens when you have a large chunk of functionality not covered by tests :(
