### ISSUE TITLE
Cannot set window size in incognito mode with Chromedriver 2.29 + chrome 57

### ISSUE THREAD

**Issue by songsb13** [SeleniumHQ/selenium#3782]
## Meta -
OS:  windows 10, windows 7, windows server 2012 R2

Selenium Version:  
3.3.3(python3.5 32bit)

Browser:  Chrome 

Browser Version:  57.0.2987.133 (64-bit)

## Expected Behavior -
change window size
it WORKED with Chromedriver 2.27 + chrome 56.

## Actual Behavior -
raises error
```
Message: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 6.3.9600 x86_64)
```

## Steps to reproduce -

```
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito") 
chrome_options.add_argument("--silent")

self.driver = webdriver.Chrome(driver_path, chrome_options=chrome_options)
self.driver.set_window_size(355, 300)
```

**Comment by p0deje** [comment]
Please, file the issue in [chromedriver bug tracker](https://code.google.com/p/chromedriver/issues/).

**Comment by igormilla** [comment]
There is an open bug in the chromedriver responsible for this. Here is the [link to the issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=504&q=incognito%20set%20size&colspec=ID%20Status%20Pri%20Owner%20Summary) in a bug tracker. 
Please star that issue, so it gets a higher priority
