### ISSUE TITLE
500 Internal Privoxy Error when I instantiate a phantomjs webdriver

### ISSUE THREAD

**Issue by KuoRave** [SeleniumHQ/selenium#3783]
## Meta -
OS:  
Windows 7

Language:
Python v3.6

Selenium Version:  
3.3.1, Webdriver

Browser:  
Phantomjs

Browser Version:  
2.1.1

## Expected Behavior -
successfully create instance
## Actual Behavior -
I got the 500 error
## Steps to reproduce -
when i run the code
```
driver = webdriver.PhantomJS()
```
then i got the below msg

> selenium.common.exceptions.WebDriverException: Message:
> 500 Internal Privoxy Error
> Privoxy encountered an error while processing your request:
> Could not load template file no-server-data or one of its includ
ed components.
> Please contact your proxy administrator.
> If you are the proxy administrator, please put the required file(s)in the 
(confdir)/templates directory.  The location of the <code>(confdir
) directory is specified in the main Privoxy config file.
(It's typically the Privoxy install directory).

**Comment by barancev** [comment]
"Please contact your proxy administrator" as stated in the message.
Proxy should not handle local connections.
