### ISSUE TITLE
Repeat 'browser busy property is true' on IEDriverServer

### ISSUE THREAD

**Issue by RodHPE** [SeleniumHQ/selenium#3784]
OS:  win7_x64 enterprise version

Selenium Version:  3.0.1

Browser:  IE11.
IEDriverServer: Win32; version: 3.0.0.
Client: Webdriverio base on nodejs.

Note: Although my OS is X64, when using x64 IEDriverServer to run test, there have typing input huge slow issue. so change win32.

For our login page, when we click button to submit a form to login. there will wait a long time for response return about 2min. then login in success and run test correctly. Seems that the browser wait for the page load complete. but I sure our page not so complicated  that need this too much time loading.

Log  gives the repeated 'browser busy property is true' message, but chrome and firefox are ok.

our page build by: react + grommet + redux. pls give me a workaround. Thanks God!!

log:
D 2017-04-07 14:11:21:558 InputManager.cpp(241) Queueing SendInput structure for mouse click
T 2017-04-07 14:11:21:558 InputManager.cpp(615) Entering InputManager::AddMouseInput
T 2017-04-07 14:11:21:558 InputManager.cpp(602) Entering InputManager::GetNormalizedCoordinates
T 2017-04-07 14:11:21:558 InputManager.cpp(615) Entering InputManager::AddMouseInput
T 2017-04-07 14:11:21:558 InputManager.cpp(602) Entering InputManager::GetNormalizedCoordinates
T 2017-04-07 14:11:21:558 HookProcessor.cpp(93) Entering HookProcessor::Initialize
T 2017-04-07 14:11:21:558 HookProcessor.cpp(103) Entering HookProcessor::Initialize
T 2017-04-07 14:11:21:558 HookProcessor.cpp(166) Entering HookProcessor::InstallWindowsHook
T 2017-04-07 14:11:21:558 HookProcessor.cpp(93) Entering HookProcessor::Initialize
T 2017-04-07 14:11:21:558 HookProcessor.cpp(103) Entering HookProcessor::Initialize
T 2017-04-07 14:11:21:558 HookProcessor.cpp(166) Entering HookProcessor::InstallWindowsHook
D 2017-04-07 14:11:21:558 InputManager.cpp(169) Sent 3 events via SendInput()
T 2017-04-07 14:11:21:558 InputManager.cpp(193) Entering InputManager::WaitForInputEventProcessing
D 2017-04-07 14:11:21:558 InputManager.cpp(209) Number of inputs processed: 0
D 2017-04-07 14:11:21:558 InputManager.cpp(172) Wait for input event processing returned false
T 2017-04-07 14:11:21:558 HookProcessor.cpp(243) Entering HookProcessor::Dispose
T 2017-04-07 14:11:21:558 HookProcessor.cpp(196) Entering HookProcessor::UninstallWindowsHook
T 2017-04-07 14:11:21:558 HookProcessor.cpp(243) Entering HookProcessor::Dispose
T 2017-04-07 14:11:21:558 HookProcessor.cpp(196) Entering HookProcessor::UninstallWindowsHook
T 2017-04-07 14:11:21:608 HookProcessor.cpp(243) Entering HookProcessor::Dispose
T 2017-04-07 14:11:21:608 HookProcessor.cpp(243) Entering HookProcessor::Dispose
T 2017-04-07 14:11:21:608 response.cc(63) Entering Response::SetSuccessResponse
T 2017-04-07 14:11:21:608 response.cc(69) Entering Response::SetResponse
T 2017-04-07 14:11:21:608 IECommandExecutor.cpp(574) Entering IECommandExecutor::GetCurrentBrowser
T 2017-04-07 14:11:21:608 IECommandExecutor.cpp(580) Entering IECommandExecutor::GetManagedBrowser
T 2017-04-07 14:11:21:608 response.cc(51) Entering Response::Serialize
T 2017-04-07 14:11:21:608 IECommandExecutor.cpp(175) Entering IECommandExecutor::OnWait
T 2017-04-07 14:11:21:608 IECommandExecutor.cpp(574) Entering IECommandExecutor::GetCurrentBrowser
T 2017-04-07 14:11:21:608 IECommandExecutor.cpp(580) Entering IECommandExecutor::GetManagedBrowser
T 2017-04-07 14:11:21:608 Browser.cpp(438) Entering Browser::Wait
D 2017-04-07 14:11:21:608 Browser.cpp(448) Navigate Events Completed.
T 2017-04-07 14:11:21:608 Browser.cpp(713) Entering Browser::GetActiveDialogWindowHandle
T 2017-04-07 14:11:21:608 Browser.cpp(206) Entering Browser::GetContentWindowHandle
D 2017-04-07 14:11:21:613 Browser.cpp(464) Browser busy property is true.
T 2017-04-07 14:11:21:613 IECommandExecutor.cpp(382) Entering IECommandExecutor::WaitThreadProc
T 2017-04-07 14:11:21:813 IECommandExecutor.cpp(175) Entering IECommandExecutor::OnWait
T 2017-04-07 14:11:21:813 IECommandExecutor.cpp(574) Entering IECommandExecutor::GetCurrentBrowser
T 2017-04-07 14:11:21:813 IECommandExecutor.cpp(580) Entering IECommandExecutor::GetManagedBrowser
T 2017-04-07 14:11:21:813 Browser.cpp(438) Entering Browser::Wait
D 2017-04-07 14:11:21:813 Browser.cpp(448) Navigate Events Completed.
T 2017-04-07 14:11:21:813 Browser.cpp(713) Entering Browser::GetActiveDialogWindowHandle
T 2017-04-07 14:11:21:813 Browser.cpp(206) Entering Browser::GetContentWindowHandle
D 2017-04-07 14:11:21:813 Browser.cpp(464) Browser busy property is true.
T 2017-04-07 14:11:21:814 IECommandExecutor.cpp(382) Entering IECommandExecutor::WaitThreadProc
T 2017-04-07 14:11:22:014 IECommandExecutor.cpp(175) Entering IECommandExecutor::OnWait
T 2017-04-07 14:11:22:014 IECommandExecutor.cpp(574) Entering IECommandExecutor::GetCurrentBrowser
T 2017-04-07 14:11:22:014 IECommandExecutor.cpp(580) Entering IECommandExecutor::GetManagedBrowser
T 2017-04-07 14:11:22:014 Browser.cpp(438) Entering Browser::Wait
D 2017-04-07 14:11:22:014 Browser.cpp(448) Navigate Events Completed.
T 2017-04-07 14:11:22:014 Browser.cpp(713) Entering Browser::GetActiveDialogWindowHandle
T 2017-04-07 14:11:22:014 Browser.cpp(206) Entering Browser::GetContentWindowHandle
D 2017-04-07 14:11:22:120 Browser.cpp(464) Browser busy property is true. 
......
......

**Comment by jimevans** [comment]
The driver is behaving as expected. You can set the pageLoadStrategy to "eager" or "none" to have it return earlier, but you'll need to be sure to use proper waits for the next step in your automation.
