### ISSUE TITLE
Window resize / maximize not working with Safari

### ISSUE THREAD

**Issue by jibujmathew-rm** [SeleniumHQ/selenium#3789]
OS:  
MAC
Selenium Version:  
3.3.0
Browser:  
Safari

It looks like window resizing is not working with Safari 10. 
The code I have tried is - this.driver.Manage().Window.Size = new Size(x, y);
and the above code is raising NoSuchWindowException
I have tried with javascript also - ((IJavaScriptExecutor)this.driver).ExecuteScript(string.Format("window.resizeTo({0}, {1});", x, y)); but nothing happens.

Browser Version:  
10.1

## Expected Behavior -
Window to be resized
## Actual Behavior -
Not resizing

**Comment by lmtierney** [comment]
As per our new issue template:

> If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/
