### ISSUE TITLE
Opera browser in Selenium grid: Driver class not found

### ISSUE THREAD

**Issue by ttyymmo0** [SeleniumHQ/selenium#3790]
## Meta -
OS:  
Host: Windows 8.1 Enterprise 64 bit
Node and the Hub: Windows 7 Enterprise 32 bit service pack 1
Selenium Version:  
selenium-server-standalone-3.3.1.jar
Browser:  
Opera
Browser Version:  
44.0.2510.1159 (PGO)  32 bit

## Expected Behavior -
Initialize opera driver and be able to run tests
## Actual Behavior -
Driver class not found: com.opera.core.systems.OperaDriver
## Steps to reproduce -

I'm trying to setup an environment with Selenium grid to execute my Selenium test on a remote machine. The only browser I can`t get to work is Opera. I configured it the same as the other browsers. However the node shows a Driver class not found.

On the host opera is installed, the opera webdriver is in C:/GUI-Tests/Drivers/operadriver.exe, the stacktrace of the error is:
```
13:30:37.169 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:30:37.169 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped: Unable to create new instances on this machine.
13:30:37.178 INFO - Driver class not found: com.opera.core.systems.OperaDriver
13:30:37.178 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
```

Starting the hub:
`java -jar selenium-server-standalone-3.3.1.jar -role hub -hubConfig hubConfig.json`
My Hub config:
```
{
  "host": ip,
  "maxSessions": 5,
  "port": 4444,
  "cleanupCycle": 5000,
  "timeout": 300000,
  "newSessionWaitTimeout": -1,
  "servlets": [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 180000,
  "platform": "WINDOWS"
}

```
Starting the node:
`java -jar selenium-server-standalone-3.3.1.jar -role node -nodeConfig nodeConfig.json`
My node config file:  
```
{
  "capabilities":
  [
	{
	  "browserName": "opera",
	  "platform": "WINDOWS",
	  "maxInstances": 5,
	  "seleniumProtocol": "WebDriver",
	  "webdriver.opera.driver": "C:/GUI-Tests/Drivers/operadriver.exe"
	}
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}
```

**Comment by barancev** [comment]
com.opera.core.systems.OperaDriver is legacy Opera driver. It is not required to drive new Blink-based Opera.

Use operablink as browserName instead.
