### ISSUE TITLE
SAFARI: NoSuchWindowError: A request to use a window could not be satisfied because the window could not be found.

### ISSUE THREAD

**Issue by alycda** [SeleniumHQ/selenium#3796]
## Meta -
OS:  OSX 10.11.6
Selenium Version:  3.3.0, VSCode, npm/javascript
Browser:  Safari 

Browser Version:  10.1 (11603.1.30.0.34)

## Expected Behavior - 
Should be able to manipulate the window via `driver.manage().window().setSize(1024,768)`

## Actual Behavior - 
**NoSuchWindowError: A request to use a window could not be satisfied because the window could not be found.**

## Steps to reproduce -
`$ mocha --require bootstrap`

bootstrap.js:
````javascript
global.startWebdriver = function(browser) {
  return new Builder().forBrowser(browser).build()
    .then(function(driver) {
      global.driver = driver;
    })
}
````

test.js:
````javascript
describe('suite', () => {
  it('test', async ()=> {
    await startWebdriver('chrome');
    await driver.get('http://google.com');
    await driver.manage().window().setSize(1024,768)
    ...
  });
});
````

I am using babel & es7, and this works just fine for chromedriver, so if you think I am missing something regarding that configuration, it's probably just been omitted for brevity in my example

**Comment by ikuwow** [comment]
i have same issue.

**Comment by manoj9788** [comment]
The below code works fine for me,
Node 7.8.0
Node-Selenium: 3.4.0
`describe('Google Search', function() {
  let driver;

  beforeEach(async function() {
    driver = await new Builder().forBrowser('safari').build();
  });

  afterEach(async function() {
    await driver.quit();
  });

  it('example', async function() {
    await driver.get('http://google.com/ncr');
    await driver.manage().window().setSize(1024,500);
    await driver.findElement(By.name('q')).sendKeys('webdriver');
    await driver.findElement(By.name('btnG')).click();
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  });

});`

**Comment by mike123vn** [comment]
it does not work

**Comment by mike123vn** [comment]
@manoj9788 :Can i ask your safari version?

**Comment by manoj9788** [comment]
@mike123vn 10.0.2

**Comment by mike123vn** [comment]
So it seems to be that this bug appears in version >=10.1

**Comment by ikuwow** [comment]
@manoj9788 's solution does not work for me, and my safari version is 10.1, too.

**Comment by manoj9788** [comment]
I am not sure as such where could be the problem. As we don't support Safari actively now, pls raise an issue with Apple's Radar.

**Comment by burg** [comment]
We fixed a window resizing issue in Safari Technology Preview 28: https://webkit.org/blog/7516/release-notes-for-safari-technology-preview-28/

Can you please verify on that version, or later?

**Comment by MentalDisruptor** [comment]
Verified using Safari Technology Preview Release 29.

Window came up and responded to some basic actions such as page loading, element localisation and highlighting.

Result: ✅  Test successful.
Awesome, I'll have a look at some of my more complex tests later on. Thank you for the update. 😃

**Comment by guts79** [comment]
How do start safari technology Preview in the capabilities of your conf.ts ?

**Comment by mike123vn** [comment]
@guts79 
https://stackoverflow.com/questions/44005589/how-to-set-open-safari-preview-in-protractor

**Comment by p0deje** [comment]
I'm going to close this as being fixed in recent SafariDriver.

**Comment by SerhiiAksiutin** [comment]
config.py
`technology_preview = '/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver'`

test.robot
```
*** Settings ***
Library           Selenium2Library
Variables         config.py
Test Teardown     Close All Browsers

*** Test Cases ***
    Create Webdriver  Safari  executable_path=${technology_preview}
    Go to  https://developer.apple.com/safari/technology-preview/
```

**Comment by Elangopalakrishnan** [comment]
@MentalDisruptor Hi, I have installed safari preview in my mac book, 
And trying to launch the safari preview browser, How to launch that?
What are the capabilities we need to give, 
I tried in c#,
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("browserName", "safari technology preview");

It doesn't work, it shows exception-
"The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{browserName=safari technology preview}]

Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

System info: host: 'mkusers-iMac.local', ip: '10.18.15.42', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_131'

Driver info: driver.version: unknown"

am i missing any capabilities here??

Thanks!
Elango

**Comment by MentalDisruptor** [comment]
@Elangopalakrishnan Hi there. I tried in Java, not C#. I can't tell you how to do that in C#. But I guess that you also need to set the correct SafariOptions and DesiredCapabilities in your C# code accordingly.

What I've done in Java:
```
DesiredCapabilities desiredCaps = DesiredCapabilities.safari();
SafariOptions sOptions = new SafariOptions();
sOptions.setUseCleanSession(true); // init a clean Safari session at all times
sOptions.setUseTechnologyPreview(true); // enable Technology Preview

desiredCaps.setCapability(SafariOptions.CAPABILITY, sOptions);
WebDriver driver = new RemoteWebDriver(
                 new URL("http://url.to.seleniumgrid.hub:4444/wd/hub"),
                 desiredCaps
);
driver.open("http://www.example.org");
```
Hope that helps. :)

**Comment by Elangopalakrishnan** [comment]
@MentalDisruptor  Need to add any extension in safari technology preview browser like we added web driver 2.48 in safari browser ?

Need to specify any path in capabilities ??
sOptions.setUseCleanSession(true); // init a clean Safari session at all times
sOptions.setUseTechnologyPreview(true); // enable Technology Preview
These two enough ??
Because when i run this it opens normal safari browser, 
My code,
DesiredCapabilities capabilities = new DesiredCapabilities();
                    capabilities = DesiredCapabilities.Safari();
                   // capabilities = DesiredCapabilities.Safari();
                    SafariOptions options = new SafariOptions();
                    capabilities.SetCapability("UseCleanSession", "true");
                    capabilities.SetCapability("UseTechnologyPreview", "true")

RemoteWebDriver rwd = new RemoteWebDriver(new Uri("http://10.18.15.52:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

**Comment by timsheng** [comment]
@p0deje  are you this issue has been fixed in recent safaridriver ?

**Comment by p0deje** [comment]
I haven't checked, but people above tells it's fixed.

**Comment by egrigolon** [comment]
@p0deje not fixed in Safari Version 10.1.1 (12603.2.4). I haven't tried STP though.

**Comment by p0deje** [comment]
Yeah, the comments above say that it's fixed in TP.

**Comment by arjunjh10** [comment]
I am still getting this issue.

**Comment by arjunjh10** [comment]
Selenium Webdriver Version: 3.4.0
OS: OS X
Browser: Safari
Version: 10.1

Running on Browserstack. and getting the following error:
```
NoSuchWindowError: A request to use a window could not be satisfied because the window could not be found. (WARNING: The server did not provide any stacktrace information)```

**Comment by burg** [comment]
@arjunjh10 Please read the entire thread. This is not fixed in 10.1 or 10.1.1, but it might be fixed in the latest Safari Technology Preview (37). Can you try using Safari Technology Preview?

**Comment by arjunjh10** [comment]
@burg Thanks for the reply. Yes I do realise i didnt read it thoroughly. I'd try out Tech preview for my case. Thanks again

**Comment by jbarriojim** [comment]
I'm using os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144', selenium: 3.4.0, safari: 10.1.2 and with Safari Technology Preview (Release 38, August 2017) works fine. This is my Java code:

   ```
    SafariOptions safariOpts = new SafariOptions();
    safariOpts.setUseCleanSession(true);
    safariOpts.setUseTechnologyPreview(true);

    DesiredCapabilities cap = DesiredCapabilities.safari();
    cap.setCapability(SafariOptions.CAPABILITY, safariOpts);   
```

And after that, the driver.manage().window().maximize() instruction, started working.

**Comment by GILHemlatameshram** [comment]
Mac OS - OS X EI Captain
Version - 10.11.6
Safari - 10.1.2
Protractor - 5.2.0
Node - v8.9.1
running via standalone selenium server - selenium-server-standalone-3.7.1.jar
Hi, I am still getting below error 
NoSuchWindowError: A request to use a window could not be satisfied because the window could not be found.

My configurations are -

capabilities: {
			'browserName': 'safari',
			'safari.options': {
                         technologyPreview: true
				},
			},

Could anyone please guide here.

**Comment by tyaga001** [comment]
Mac OS - OS X EI Captain
Version - 10.11.6
Safari - 10.1.2
Protractor - 5.2.0
Node - v8.9.1
running via standalone selenium server - selenium-server-standalone-3.7.1.jar
Hi, I am still getting below error
NoSuchWindowError: A request to use a window could not be satisfied because the window could not be found.

My configurations are -

capabilities: {
'browserName': 'safari',
'safari.options': {
technologyPreview: true
},
},

**Comment by RAdevelop** [comment]
Hi!
I have same problem with: `driver.manage().window().setSize(1024,768)`

But I use NodeJS
macOS Sierra 10.12.6
"selenium-webdriver": "^4.0.0-alpha.1"
node -v  v11.2.0

So in selenium-webdriver 4.0.0-alpha.1 for setting window size use `driver.manage().window().setRect()`

**My solution is calling setRect with all argumet**:

For example:
`driver.manage().window().setRect({"width": width, "height": height, "x": 2, "y": 2});`

if U set x = 0 or 1 OR y = 0 or 1, it has error:

> InvalidArgumentError: Parameter 'y' has a boolean value, which is not allowed.

OR

> InvalidArgumentError: Parameter 'x' has a boolean value, which is not allowed.

That's why I set "x" = 2  and  "y" = 2

:)

**Comment by burg** [comment]
This is a safaridriver bug that has been fixed already in Safari Technology Preview. It's coming eventually to a Safari update.
