### ISSUE TITLE
Firefox-Profile alternative?

### ISSUE THREAD

**Issue by ORESoftware** [SeleniumHQ/selenium#3797]
I am struggling with the FirefoxProfile module here:

https://github.com/saadtazi/firefox-profile-js/issues/86

Is there any alternative? Ultimately what I am trying to do is download a file as part of a selenium test, and TMK I need to set Firefox preferences in order to save the file in a certain directory.

**Comment by lmtierney** [comment]
It seems you found your answer in that issue.

**Comment by ORESoftware** [comment]
yeah thx
