### ISSUE TITLE
IE Driver Beta 3.3.99.4- Unable to create new remote session

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/selenium#3798]
## Meta -
OS:  Windows 10 - Build 14393
Selenium Version: 3.3.1 (Java Bindings)
Browser:  Internet Explorer
Browser Version:  11.0.14393
IE Driver Version: 3.3.99.4

## Expected Behavior -
Internet Explorer will be started on the remote node.

## Actual Behavior -
Internet Explorer launches on the node with the start page, and the test immediately fails as Grid is unable to create a new session.
[node output](https://github.com/SeleniumHQ/selenium/files/907563/node.txt)
[stack-trace](https://github.com/SeleniumHQ/selenium/files/907564/stack-trace.txt)

## Steps to reproduce -
[Simple java test to reproduce the issue](https://github.com/SeleniumHQ/selenium/files/907553/repro.java.txt)

Just starting the connection is enough to trigger the behaviour. Substituting the beta driver for the current release version of 3.3.0 allows me to verify the rest of my configuration is correct.

**Comment by hazmeister** [comment]
One question comes to mind- do I need to set a capability so the grid knows to use the w3c protocol instead of the classic json protocol?

**Comment by jimevans** [comment]
@hazmeister The Java bindings not being able to initiate a session with the IE driver beta is a known issue, and is fixed in the tip of the tree for the Java bindings. Unfortunately, these fixes haven't yet been released in a public, downloadable binary form. Thanks for the report.

To answer your other question, no, there is no capability necessary. Everything should Just Work.

**Comment by jimevans** [comment]
@hazmeister Can you retry the beta with the 3.4 release of the Java language bindings?

**Comment by hazmeister** [comment]
Looks good with Selenium 3.4 and IEDriver 3.3.99.4 on Windows 10.14393.  Can be a bit slow and unreliable, but I'll post those as separate issues.
