### ISSUE TITLE
Robotframework Selenium2library and checkbox followed by a textbox.

### ISSUE THREAD

**Issue by NxRx** [SeleniumHQ/selenium#380]
I have a webpage whose structure looks like this
[checkbox1]
      [some text1]                    [textbox1]
[checkbox2]
      [some text2]                    [textbox2]

I am trying to find a logic where, if i click on checkbox1, textbox1 should be focused and allow me to enter text, if checkbox2 is checked, when i enter text, it should automatically fill in textbox2.

Can someone please help

**Comment by barancev** [comment]
Please send questions to the selenium user group [1]

[1] https://groups.google.com/forum/#!forum/selenium-users
