### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Sdk '10.2' was not in list of simctl sdks

### ISSUE THREAD

**Issue by fangyt** [SeleniumHQ/selenium#3800]
## Meta -
OS:  mac sierra 10.12.4

Selenium Version:  

Browser:  Safari 10.1 (12603.1.30.0.34)

Browser Version:

**Comment by Jarob22** [comment]
Please provide ALL the information required by the issue template and not just 2 version numbers with no details on what actually happened, what you were doing and what went wrong.

**Comment by fangyt** [comment]
Thank you, my problem has been solved, the problem is not binding compiled languages

**Comment by burg** [comment]
You can remove the 'R' label now.
