### ISSUE TITLE
Creating a Support Project Playlist for the .Net Bindings

### ISSUE THREAD

**Issue by seanrand57** [SeleniumHQ/selenium#3805]
Raising a ticket so I can create a PR for the creations of Playlists per project, addition of the following files
SupportWebDriver.playlist
WebDriverBackedSelenium.playlist
Firefox.playlist
IE.playlist
PhantomJS.playlist
Remote.playlists

Currently the project has a common test playlist but not a playlist for each of the other projects which would be useful when working in a specific project hence this addition.

I shall create a PR for this shortly,
Cheers
Sean

**Comment by jimevans** [comment]
Merged in PR 3807
