### ISSUE TITLE
Element not found in the cache

### ISSUE THREAD

**Issue by vaibhav44** [SeleniumHQ/selenium#381]
Hi Folks,
I am new to GUI based automation Testing.

Can somebody explain me what can cause the following exception.

I thought it may be due to some time constraints so I have used expilicit wait in my Java-Selenium prog
but i was not able to resolve this issue.

org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it  was looked up

**Comment by tarlabs** [comment]
@vaibhav44 , This is not a forum to ask question. You would need to ask questions on below link

https://groups.google.com/forum/#!forum/selenium-users
