### ISSUE TITLE
 Selenium3.3.0 not support edge browser ?

### ISSUE THREAD

**Issue by lovingyu** [SeleniumHQ/selenium#3812]
hi ,team

i'm  test edge browser with  selenium-webdriver 3.3.0, it's not work fine.
here is my script:

require "selenium-webdriver"
Selenium::WebDriver.logger.level = :info 
browser = Selenium::WebDriver.for :edge

the errormessage:
selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/w3c_bridge.rb:124:in `create_session': no sessionId in returned payload (Selenium::WebDriver::Error::WebDriverError)

the log info:
===========================
2017-04-11 13:23:39 INFO Selenium -> POST session
2017-04-11 13:23:39 INFO Selenium    >>> http://localhost:17556/session | {"desiredCapabilities":{"browserName":"MicrosoftEdge","platform":"WINDOWS"}}
2017-04-11 13:23:40 INFO Selenium <- {"sessionId":"6240CA12-5069-42E4-B492-E083393D61FD","status":0,"value":{"browserName":"MicrosoftEdge","browserVersion":"38.14393.0.0","platformName":"windows","platformVersion":"10","takesElementScreenshot":true,"takesScreenshot":true,"acceptSslCerts":true,"applicationCacheEnabled":true,"locationContextEnabled":true,"webStorageEnabled":true,"pageLoadStrategy":"normal"}}
--------------------------

also i add a output in the create_session method(in the w3c_bridge file):

  def create_session(desired_capabilities)
          resp = execute :new_session, {}, {desiredCapabilities: desired_capabilities}
	  puts "--------------------------"
	  puts resp
	  puts "--------------------------"
         @session_id = resp['sessionId']
          return W3CCapabilities.json_create resp['value'] if @session_id

          raise Error::WebDriverError, 'no sessionId in returned payload'
  end
the output is :
--------------------------
{"browserName"=>"MicrosoftEdge", "browserVersion"=>"38.14393.0.0", "platformName"=>"windows", "platformVersion"=>"10", "takesElementScreenshot"=>true, "takesScreenshot"=>true, "acceptSslCerts"=>true, "applicationCacheEnabled"=>true, "locationContextEnabled"=>true, "webStorageEnabled"=>true, "pageLoadStrategy"=>"normal"}
--------------------------

but when i use firefox browser to test, the resp output is :
--------------------------
{"sessionId"=>"7420d592-05e6-4136-aecb-d403a3802be7", "value"=>{"acceptInsecureCerts"=>false, "browserName"=>"firefox", "browserVersion"=>"52.0.1", "moz:accessibilityChecks"=>false, "moz:processID"=>12472, "moz:profile"=>"C:\\Users\\81440\\AppData\\Local\\Temp\\rust_mozprofile.8FBXwrw29P9Y", "pageLoadStrategy"=>"normal", "platformName"=>"windows_nt", "platformVersion"=>"10.0", "rotatable"=>false, "specificationLevel"=>0, "timeouts"=>{"implicit"=>0, "page load"=>300000, "script"=>30000}}}
--------------------------

Look forward to your reply，thanks

**Comment by lmtierney** [comment]
Hi, yes sorry this issue is fixed in 1a0f066 and will be in the next release. For the time being, please downgrade to `< 3.3.0`
