### ISSUE TITLE
Selenium Chromedriver driver.get nor find_element works on background

### ISSUE THREAD

**Issue by whatdis2** [SeleniumHQ/selenium#3815]
## Meta -
OS:  Windows 10 64-bit

Selenium Version:  3.3.3
Celery Version:  3.1.23

Browser:  Chrome

Browser Version:  ChromeDriver 2.29 and Chrome 57.0.2987.133

## Expected Behavior -
 The automated task does not complete when kicked off by celery using the following command:
```
from tasks import myworker1
myworker1.apply_async((inputArgs[1],
    inputArgs[2],
    inputArgs[3],
    inputArgs[4]),
   expires=90);
```
## Actual Behavior -
The task goes to an url logs in and then I need to redirect to another url after that. The problem occurs when after logged in I need to click or redirect to a different url within the same web page. Found out that driver.get("http://myurl.com") does not load. Thus I tried to click on the elements that in exchange will be like just going to the url directly. However, 'driver.find_element_by_css_selector("button.goTo").click()' does not work either. It never finds it.
Options for chromedriver:

```
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--start-maximized');
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument("--incognito")
chrome_options.add_argument("--disable-plugins-discovery")
self.driver = webdriver.Chrome(executable_path='C:/Chrome/chromedriver.exe',chrome_options=chrome_options)
```
Does running chrome in the background affects the driver.get or finding elements in a web page? Because if I run the same task without celery by calling it directly (the browser opens) it just works:
```
from tasks import myworker1
myworker1(arg1,arg2,arg3,arg4)
```

## Steps to reproduce -
Push a task to the queue via celery using the command '.apply_async' like explained above. driver.get or find_element will stop working after initial web page changed because of being redirected after log in to a website.

**Comment by p0deje** [comment]
What if you're not using Celery? Does it work?

If yes, then this is more like an environment issue rather than Selenium bug.

If no, please provide a [concise reproducible test case](http://sscce.org/) to re-open the issue.
