### ISSUE TITLE
Windows7-SeleniumIDE2.9.0-Javascript errors

### ISSUE THREAD

**Issue by dharris2** [SeleniumHQ/selenium#382]
After installing a new version of IDE (2.9.0) on FF 36.0.4 on a windows seven machine, I'm am getting an endless stream of error popups, if I open the actions or the options drop-down. I am also seeing what another user reported: "Table view is not available with this format"  Examples below:
1) There was an unexpected error. Msg: TypeError: editor.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 1007, column: 74
Editor.prototype.onPopupOptions@chrome://selenium-ide/content/editor.js:1007:75
onpopupshowing@chrome://selenium-ide/content/selenium-ide.xul:1:1
2) There was an unexpected error. Msg: TypeError: this.app is undefined
Url: chrome://selenium-ide/content/editor.js, line: 1054, column: 2
Editor.prototype.getTestCase@chrome://selenium-ide/content/editor.js:1054:3
Editor.prototype.tabSelected@chrome://selenium-ide/content/editor.js:601:7
onselect@chrome://selenium-ide/content/selenium-ide.xul:1:22
set_selectedIndex@chrome://global/content/bindings/tabbox.xml:406:15
set_selectedItem@chrome://global/content/bindings/tabbox.xml:431:34
_selectNewTab@chrome://global/content/bindings/tabbox.xml:476:11
onxblmousedown@chrome://global/content/bindings/tabbox.xml:771:11
![seleniumscreenshot](https://cloud.githubusercontent.com/assets/11681946/6870877/31a2bbcc-d475-11e4-87ad-56ac9d0e3167.JPG)

**Comment by zura44** [comment]
Hi, I also found out this issue today. 
The last time I use Selenium IDE is 13/3/2015 (Windows 8, Selenium IDE version : 2.8.0).
I have try reinstall to new Selenium IDE version also having the same issue.

**Comment by samitbadle** [comment]
Hi,

The latest versions of Selenium IDE contains a way to submit diagnostic information. If you are willing, can you give us a link to it. You can get it under the help menu.

It will help me track down the issue faster.

Thank you.

Cheers,
Samit

**Comment by dharris2** [comment]
Samit,
 I have submitted the issues from the help section. Let me know if there is anything else I can do to help.

**Comment by samitbadle** [comment]
Can you also put the link it generates here?

**Comment by zura44** [comment]
The information from Diagnostic

**Comment by samitbadle** [comment]
Thanks for the info. It seems that the information for installed plugins is corrupted for some reason. This can be due to a bad plugin or a bug somewhere. Try uninstalling all plugins and clearing the pluginsData option manually. You can then add the plugins back one by one until the issue reappears.

To clear the pluginsData option manually, make sure Selenium IDE is closed. Open about:config in a new Firefox tab. Agree to be careful. In the search box on the page, type extensions.selenium-ide.pluginsData and wait for the results to appear. Right click on the result and select Reset from the context menu.

Btw, when you submitted the diagnostic information, did you not receive an URL?

**Comment by dharris2** [comment]
I did not receive a URL It was just a submit button and then the window closed. No confirmation or anything. I'm trying the steps above right now.

**Comment by dharris2** [comment]
I removed all plugins and cleared the plugin data, and IDE is working again. I'm now in the process of adding plugins back to see if I can find the cause.

**Comment by samitbadle** [comment]
Since IDE is working and there has been no update, I am closing this issue.

**Comment by yqin150** [comment]
reopen the firefork browser
