### ISSUE TITLE
Improvement: liveness and readiness endpoint

### ISSUE THREAD

**Issue by JorritSalverda** [SeleniumHQ/selenium#3821]
In order to run selenium reliably in Kubernetes it needs a _liveness_ and _readiness_ endpoint.

The **/liveness** endpoint is used to see if the hub itself is healthy. If it doesn't respond with 200 OK the application gets killed and restarted. This should explicitly not take any dependencies - like the node health - into account.

The **/readiness** endpoint determines whether an application is ready to serve traffic. In this case it might make sense to take the health of the dependencies into account. Again it expects a 200 OK, in which case the application pod is added to a _service_ - effectively a load balancer - and removed from it as long as it returns another status code. However it doesn't lead to any application restarts.

For either endpoint it shouldn't tax the application too much, because it will be requested frequently.

**Comment by AutomatedTester** [comment]
we have the `/status` endpoint that does both these jobs in one. We use it to know if we should send traffic to it on startup, why add another 2 endpoints to solve this problem again?

**Comment by JorritSalverda** [comment]
Ah, I'm still running `3.1.0-astatine`. Has the /status endpoint been added since? That will probably suffice.

It can be used for both liveness and readiness checks. There's a subtle difference though if you want to use it to make running your application more stable.

The liveness check should never depend on the status of dependencies, because that could lead to a cascade of applications restarting. Let's say the /status endpoint depends on any of the nodes being healthy would lead to the hub restarting every time a node turns bad.

For readiness you could involve the health of any dependencies if they influence your ability to serve traffic. For an application running as a single instance though this wouldn't be much of help, because as soon as it gets removed from the load balancer / service you are no longer able to serve traffic at all.

**Comment by AutomatedTester** [comment]
This is in all endpoints, GeckoDriver, IEDriver and ChromeDriver.
