### ISSUE TITLE
Firefox has stopped working dialog on driver.quit()

### ISSUE THREAD

**Issue by AidanMcD** [SeleniumHQ/selenium#3822]
Selenium version: 2.44 - geckodriver version 0.13.0
OS: Windows 7 x64
Browser: Internet Explorer
Browser version: 9 (v9.0.8112.16421 Update 9.0.34)
Language:C#

## Expected Behavior -

Driver to quit without any errors.

## Actual Behavior -

Firefox has stopped working error appears.
![image](https://cloud.githubusercontent.com/assets/5120710/24948391/101b02b8-1f62-11e7-947c-ec2fb2c984b1.png)

##Steps to reproduce -

FirefoxOptions foptions = new FirefoxOptions();
foptions.SetPreference("marionette",false);
foptions.SetPreference("plugin.state.flash",0);
foptions.SetPreference("browser.startup.page", 0);
foptions.SetPreference("browser.startup.homepage", "about:blank");
foptions.SetPreference("browser.startup.homepage_override.mstone", "ignore");
RemoteWebDriver _driver = new FirefoxDriver(FirefoxDriverService.CreateDefaultService(), foptions,
                        TimeSpan.FromSeconds(30));
_driver.Navigate().GoToUrl("http://www.Google.com");
_driver.Quit()

**Comment by cgoldberg** [comment]
and if you close that uninformative popup, whats the actual error?

**Comment by p0deje** [comment]
What Firefox version?

Can you upgrade Selenium and GeckoDriver to latest versions and try again?

**Comment by barancev** [comment]
It's a browser issue, not Selenium one.

You can suppress these error messages as described here: https://www.raymond.cc/blog/disable-program-has-stopped-working-error-dialog-in-windows-server-2008/

**Comment by whimboo** [comment]
In case someone still has this issue with Firefox, I landed a change for geckodriver in [bug 1388249](https://bugzilla.mozilla.org/show_bug.cgi?id=1388249) which will prevent the crash reporter dialog to popup. It will be shipped with the next geckodriver release.
