### ISSUE TITLE
Please reopen issue 3767

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#3824]
## Meta -
OS:  
Windows 7

Selenium Version:  
selenium-webdriver (3.3.0), geckodriver 0.15.0
 ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]

Browser:  
Firefox

Browser Version:  
52.0

## Expected Behavior -
The user should be able to switch to an iframe without 1st scrolling it into view. The user should then be able to interact with elements inside of the iframe. This may be related to issue 2377, but I am not sure.

## Actual Behavior -
The user is NOT able to switch to an iframe without 1st scrolling it into view. The code seems to be switching to the iframe, but the user will NOT be able to interact with elements inside of the iframe.

## Steps to reproduce -
Sample html
https://jsfiddle.net/0hdtcyjz/40/

On the sample jsfiddle page...

Click the 'Update iFrame' button. This will load an HTML form into the iFrame found at the bottom of the page, but the user would still need to scroll to get to the iframe. Do NOT scroll to the iframe.
 Switch to the iframe using something like
 driver.switch_to.frame driver.find_element(:id,'iframe_id')
 Attempt to click button1 in the frame
 driver.find_element(:xpath, "//*[@value='button1']")
 Selenium will NOT be able to click the button

**Comment by p0deje** [comment]
I can confirm it doesn't work in Firefox 52 + GeckoDriver 0.15, but it works correctly in Chrome 57 + ChromeDriver 2.29.

With that said, I'll ask you to post this issue to [GeckoDriver issue tracker](https://github.com/mozilla/geckodriver/issues). From Selenium standpoint, there is nothing we can do to fix it.
