### ISSUE TITLE
Please reopen 3721.  Behavior works in IEDriverServer 2.48, but not latest

### ISSUE THREAD

**Issue by DamienLyles** [SeleniumHQ/selenium#3825]
## Meta -
OS:  
Windows 7

Selenium Version:  
3.3.0

Browser:  
IE

Browser Version:  
11.0.9600.18617, Update Version: 11.0.40

## Expected Behavior -
Users should be able to obtain browser cookies from PDF-only browser windows. This does not work using IEDriver server 3.3.0.0, but does work with ChromeDriver 2.28.455520 and GeckoDriver 0.15.0 AND IEDriverServer 2.48.

## Actual Behavior -
I get a Net::Timeout exception in Ruby.

## Steps to reproduce -

Step 1. Open Internet Explorer
 Step 2. Navigate to a pdf (e.g., http://myserver/my_pdf.pdf)
 Step 3. Verify that the PDF is displayed in the main browser window.
 Step 4. Attempt to read the browser's cookies. I'm using Ruby so for me, it's something like...
cookie_string = ""

# Read the cookie hash...
$driver.manage.all_cookies.each { |cookie|
	# consolidate the cookie hash to a string 
            # (e.g., cookie_name1=cookie_val1;cookie_name2=cookie_val2;etc...)
    	cookie_string = cookie_string + "#{cookie[:name]}=#{cookie[:value]};"  
}

puts "COOKIES! -> #{cookie_string}"

**Comment by jimevans** [comment]
What version of `IEDriverServer.exe` are you using? Are you using the 32-bit or 64-bit executable? Is your version of Windows 64-bit, and you're attempting to use the 64-bit executable? If so, that will never work, because of the use of Windows hook procedures in retrieving cookies for IE.

**Comment by DamienLyles** [comment]
Hi Jim,
I am using IEDriverServer.exe 3.3.0.0 (32-bit) on a 32-bit machine.

**Comment by jimevans** [comment]
And your `TRACE` level log from `IEDriverServer.exe` shows what?

**Comment by DamienLyles** [comment]
I can't reproduce the issue and it seems to be working now for 3.3.0.0.  I'm not a crazy person, I promise, lol.  I guess the issue got fixed in MS17-006 or something?  Anyway, this defect can be closed.  Thank you for looking into this.
