### ISSUE TITLE
Re-using same instance again webdriverJS

### ISSUE THREAD

**Issue by vishnuc** [SeleniumHQ/selenium#3830]
I am really new to this selenium , I managed to open a website using below nodejs code

> 
> var webdriver = require('selenium-webdriver');
> 
> var driver = new webdriver.Builder()
>     .forBrowser('chrome')
>     .build();
> console.log(driver);
> 
> driver.get('https://web.whatsapp.com');

 //perform all other operations here.
now https://web.whatsapp.com is opened and I manually scan QR code and log in.Now I have different javascript files to perform actions as delete , clear chat inside web.whatsapp.com etc...

Now If i get some error , I debug and when I run the script again using node test.js , it takes another 2 minutes to load page and do the steps I needed.I just wanted to reopen the already opened tab and continue my script instead new window opens.

Edit day 2 : still searching for solution.I tried below code to save object and reuse it.. Is it correct approach ?I get json parse error though.

```
var driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).setChromeOptions(o).build();
var savefile = fs.writeFile('data.json', JSON.stringify(util.inspect(driver)) , 'utf-8');
var parsedJSON = require('./data.json');
console.log(parsedJSON);
```

**Comment by jleyba** [comment]
Reusing a session between different node invocations is possible, but a bit of a hassle b/c you have to manage the Selenium server separately so the session persists (selenium-webdriver is designed to cleanup after itself and clean all browser sessions when the process exists).

Generally, what you'll do is just create an instance and use it with different functions inside the same script. For example:

```js

function getTitle(url) {
  return driver.get(url).then(() => driver.getTitle());
}

let driver = new webdriver.Builder().forBrowser('chrome').build();
getTitle('https://www.google.com/ncr').then(title => {
  console.log(title);
  return getTitle('https://web.whatsapp.com');
}).then(title => console.log(title));
```

In the future, please direct these types of questions to the [selenium-users group](https://groups.google.com/forum/#!forum/selenium-users), or ask in the `#selenium` IRC channel. This
issue tracker is reserved for reporting bugs with the Selenium clients.
