### ISSUE TITLE
Python API documentation points to version 3.2 but it should point to 3.3.3 

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#3831]
In https://seleniumhq.github.io/selenium/docs/api/py/api.html in the top left corner, the version number is 3.2 but it should be 3.3.3 or atleast 3.3.

**Comment by davehunt** [comment]
Fixed via https://github.com/SeleniumHQ/selenium/commit/9623a587f13750facda394f93a3b9374edf18353.

**Comment by aaltat** [comment]
I sure hope that there is a script that does all those version number changes... Thanks for a quick fix.

**Comment by lmtierney** [comment]
@aaltat the documentation is generated automatically, it just hadn't been done for 3.3.3 yet

**Comment by davehunt** [comment]
Yeah, there's a script here: https://github.com/SeleniumHQ/selenium/blob/master/generate_api_docs.sh, though I prefer to run those steps separately for the Python docs, because I'm paranoid. 😝
