### ISSUE TITLE
Suggestion: Add export to nightwatch function

### ISSUE THREAD

**Issue by qacwnfq** [SeleniumHQ/selenium#3835]
I'd like the seleniumide to be able to export the code to nightwatch also.
This has lots of advantages: being able to easily use the testarmada and magellan,
which have a lot of practical features, like taking care of parallelism, sauce tunnels and JUnit reporting.
Non-developers would be able to click together tests for all kinds of browers and setups after devs have setup nightwatch, magellan and sauce.

Of course if this is not a good Idea to include directly, one could start a separate project.

What do you guys think?

**Comment by cgoldberg** [comment]
sounds like a neat separate project for you

**Comment by barancev** [comment]
Yes, a good idea for a separate project, closing the issue.
