### ISSUE TITLE
.getText or .getAttribute("innerText") or .getAttribute("innerHTML") or .getAttribute("value") not working on element

### ISSUE THREAD

**Issue by Jackels** [SeleniumHQ/selenium#3836]
```
<div>
	<a class="stuff" href="?loc=view&amp;item=1234">text a</a>
	<p>text p</p>
</div>
```

```
WebElement elementWithClass = driver.findElement(By.className("stuff"));
WebElement parent = elementWithClass .findElement(By.xpath(".."));
System.out.println(elementWithClass.isVisible()); => True
System.out.println(elementWithClass.getText()); => ""
System.out.println(elementWithClass.getAttribute("innerText")); => ""
System.out.println(elementWithClass.getAttribute("innerHTML")); => ""
System.out.println(elementWithClass.getAttribute("value")); => null

System.out.println(parent.getText()); => "text a\ntext p"
```
I don't know if this is intended or a bug, but I am unable to select an element and just get its inner Text. Getting its parent tho works and it will print all the text it has, too much of course. This is using phantomjs.

**Comment by p0deje** [comment]
I can't reproduce the behavior on current Selenium master and PhantomJS 2.1.1.

Please provide a [concise reproducible test case](http://sscce.org/) to reopen the issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
