### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by KillaPL** [SeleniumHQ/selenium#384]
Hello

I am using selenium through ruby's selenium-webdriver to create a bot, which plays a browser game for me (single player browser game, no cheating here; ) ). The problem is, that process gains memory with time, and after 3, 4 hours it needs a restart, because of memory usage and slowing down. I managed to get a profile in firefox during the increased memory time and most of the time seems to be spent in selenium internals, namely in

```
Connection.prototype.close
```

in javascript.

What I do: I create a driver object in ruby and perform some actions in infinite loop. The code is available here: https://github.com/KillaPL/automaton.

Is this possibly a memory leak in selenium internals? I am not closing the connection myself anywhere. If so, what can I do more to help fix it? If not, what am I doing wrong?

To reproduce the issue, clone the https://github.com/KillaPL/automaton, bundle install and run it. It might fail on first run, it's not bulletproof yet. It will slowly, but steadily gain memory.

Profile file from firefox I used is available here: http://speedy.sh/Dgewu/profile.json

**Comment by AutomatedTester** [comment]
We could easily have a memory leak in our JS code but getting that sorted
has never been a priority since we never recommend people use the same
browser for hours ( I appreciate your use case is different)

**Comment by andreastt** [comment]
`Connection#close` is a FirefoxDriver internal right?

**Comment by KillaPL** [comment]
I am using FirefoxDriver, if that helps. Is there anything more I can do to help with this? Sadly, I don't think I can solve this by myself, the code seems rather complex to get into

**Comment by cerebrotecnologico** [comment]
We experience an OutOfMemoryError when using the FirefoxDriver. 
We nailed down to our Firefox plugin logging too much to the console.
The class UnixProcess is holding a buffer that is never cleared.

private final ByteArrayOutputStream inputOut = new ByteArrayOutputStream();

Output can be directed to a file, using the system property webdriver.firefox.log, but the output is ALWAYS appended to the inputOut buffer in te UnixProcess class.

**Comment by cerebrotecnologico** [comment]
Therefore, our work around has been to just avoid writing to the console from our plugin, nevertheless there is a clear bug in UnixProcess class

**Comment by andreastt** [comment]
@cerebrotecnologico: That seems like a problem with the Java language bindings, not FirefoxDriver, and unrelated to this issue.

**Comment by cerebrotecnologico** [comment]
The class org.openqa.selenium.os.UnixProcess contains the following method:

 private OutputStream getOutputStream() {
    return drainTo == null ? inputOut
        : new MultioutputStream(inputOut, drainTo);
  }

The variable inputOut is a ByteArrayOutputStream, holding anything that is written into an array of bytes.  The contents are never eliminated, therefore, all output is accumulated, eventually producing the OutOfMemoryError.

**Comment by cerebrotecnologico** [comment]
Oh, I see. Should I open a different ticket?

**Comment by andreastt** [comment]
If it's reproducible, yes.

**Comment by barancev** [comment]
Memory leak in UnixProcess has been fixed long ago, it now uses fixed size CircularOutputStream instead of ByteArrayOutputStream.

Memory leak in legacy firefox driver (if one exists) will never be fixed, it's effectively deprecated and replaced by geckodriver.
