### ISSUE TITLE
IE browser sessionID issues

### ISSUE THREAD

**Issue by Naresh1983** [SeleniumHQ/selenium#3841]
OS:  
 Windows 7
Selenium Version:  
3.0.1
 Internet Explorer 11

Browser Version:  
 e.g.: 11.0.9600.18617 (64-bit) 

## Steps to reproduce -
Hi currently I am using v3.3.0 (32bit) IEDriver. I am not able to get the child browser while clicking link on parent browser.
I am getting the "This page can't be displayed" error message in child browser.
Verified both browser properties
In Parent browser 
Protocol: HyperText Transfer Protocol with Privacy
Connection: TLS 1.0, AES with 256 bit encryption (High); RSA with 2048 bit exchange
In child browser:
Protocol: Unknown Protocol
Connection: Not Encrypted

Thanks in advance.

**Comment by p0deje** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) to reopen the issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Naresh1983** [comment]
Steps to Reproduce
1) Open IE 11browser, and paste test application url hit enter
2) Click on the report link
3) New browser window will open with report list. Getting "This page can't be displayed." error message instead of report list.

**Comment by p0deje** [comment]
> test application url

Which URL?

**Comment by Naresh1983** [comment]
its internal test application and you need digital certificate. We cannot access from outside.

**Comment by p0deje** [comment]
Then there is nothing we can help with.
