### ISSUE TITLE
Enabling tabbed browsing on IEServer driver

### ISSUE THREAD

**Issue by Sethuraman11** [SeleniumHQ/selenium#3847]
## Meta -
OS:  Windows 7

Selenium Version:  3.3.1

Browser:  IE

Browser Version: IE11

## Actual Behavior - IE driver is not opening a link in new tab, instead creating as new window

##Description - If we open a IE11 manually and navigating to any link, it is opening via new tab, after setting the tabbed browsing.
When we run through scripts, IEServer32 driver is not opening a link via new tab instead open in a new window,

Suggest me any capabilities need to be set for IEServer driver.

**Comment by jimevans** [comment]
This has never been an option for the IE driver, and there is no compelling reason to attempt to implement it. A separate window is indistinguishable from a new tab from the perspective of both the browser, and any site being browsed therein.
