### ISSUE TITLE
gecko driver opens chrome browser 

### ISSUE THREAD

**Issue by Nensig** [SeleniumHQ/selenium#3848]
## Meta -
OS:  MAC 10.12

Selenium Version:  3.3.1

Code I have written:

System.setProperty("webdriver.gecko.driver",System.getProperty("user.dir") + "/Chromedriver/chromedriver-1");
		
WebDriver driver = new FirefoxDriver();

Things needs to be note : I have not imported ChromeDriver. Also Chromedriver.exe is not in the project folder.

## Expected Behavior - 
Above code should through an error because gecko driver is for firefox. Also chromedriver package is not imported, Firfoxdriver package is imported. 

## Actual Behavior - 
It opens chrome driver.

**Comment by barancev** [comment]
If "webdriver.gecko.driver" points to chromedriver -- it's not unexpected you get Chrome instead of Firefox.
