### ISSUE TITLE
 Selenium Version Error

### ISSUE THREAD

**Issue by daveferrara1** [SeleniumHQ/selenium#3850]
## Meta -
 capabilities: {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': 'latest-1', 'selenium-version': '3.3.1'}

Using sauce labs.

Getting this response when adding in the selenium version capability.

 Could not open connection: The Sauce VMs failed to start the browser or device.
      For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages (Behat\Mink\Exception\DriverException)

This is limiting the platform to OS X 10.10 when using firefox, and can not specify the selenium version.

**Comment by p0deje** [comment]
This is an issue that should be reported to Sauce, not Selenium.
