### ISSUE TITLE
The application cannot click on an element while running

### ISSUE THREAD

**Issue by Petebuhler** [SeleniumHQ/selenium#3853]
## Meta -
OS:  
Windows 7 Ultimate
Selenium Version:  
2.53.1 
Browser:  
Firefox 42.0

Hello,
I`ve come accross an issue that the application cannot click on element while a test is running. Well the test is able to find the element and click on it (step is green) but there is no change on UI. The elements are part of SVG. Here is the sample of xpath which I use: "//*[name()='svg']/*[name()='g' and @id='BZS02_cmd']/*[name()='path' and @id='BZS02_cmd_button']". Command is "Click". Anyone has any idea what the problem might be? Thanks. Petr

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
