### ISSUE TITLE
Actions Drag&Drop doesn't work

### ISSUE THREAD

**Issue by aleksoider** [SeleniumHQ/selenium#3863]
## Meta -
OS:  Win 7

Selenium Version:  2.43.1

Browser:  Chrome 

Browser Version: Chrome 57.0.2987.133 / Chrome driver 2.29.461591

## Steps to reproduce -
I tried something like this: 
   _new Actions(driver).dragAndDropBy(draggableRow, x, y).perform();_
and i also tried to make an action chain by myself like this:
    _new Actions(driver)
      .clickAndHold(draggableRow)
      .moveToElement(targetRow, x, y)
      .release()
      .build()
      .perform();_

**Comment by p0deje** [comment]
Please provide a [concise reproducible test case](http://sscce.org/).

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
