### ISSUE TITLE
Selenium & FireFox Profiles

### ISSUE THREAD

**Issue by Sixosable** [SeleniumHQ/selenium#3864]
## Meta -
OS:  
Windows 10 Pro

Browser:  
FireFox Browser (47.0.1), without using any extensions

Browser Version:  
47.0.1 (32Bit EN-US)

## Expected Behavior -
Would expect the history to show the URLs I went to as it should save the Firefox Profile right?

## Actual Behavior -
None of the URLs I went to are there so it didn't save anything to the FireFox Profile.

## Steps to reproduce -
- Start up FireFox through Selenium with a FireFox Profile
- Go to a few URLs
- Close FireFox
- Open up FireFox again with the same profile
- Check if the URLs you went to are in the browsing history

**Comment by lmtierney** [comment]
That is not how it works. Selenium makes a copy of the profile you provide, nothing you do while using selenium with said profile will persist.

**Comment by Sixosable** [comment]
Well my question is in that case how I might be able to save to the profile again to make sure the cookies and such are maintained over time.
