### ISSUE TITLE
Improved WebDriverExceptions: Subclasses

### ISSUE THREAD

**Issue by peterstory** [SeleniumHQ/selenium#3865]
This is a feature request. Currently, Selenium Python's `WebDriverException` encompasses exceptions from many different causes. For example:

* Message: Session [ea4e15ef-f60e-48a5-b520-9f360a100378] was terminated due to FORWARDING_TO_NODE_FAILED
* Message: cannot forward the request 172.20.0.4:5555 failed to respond
* Message: Session [e8457d7d-585c-47d3-a248-d249e21d4a8f] not available and is not among the last 1000 terminated sessions.

It would be great if these different causes were reflected by using subclasses of WebDriverException. For example, I'm using `webdriver.Remote`, and I like to handle exceptions differently if they were caused by the URL being loaded (ex, DNS lookup failed), or by a problem with the webdriver session itself (remote browser instance was killed). 

My current workaround is to grep for error message strings in the WebDriverException, but that's certainly not ideal.

**Comment by lmtierney** [comment]
I don't foresee us doing something like this. I believe we are only encompassing the errors defined here: https://w3c.github.io/webdriver/webdriver-spec.html#handling-errors. The errors you posted also (it appears) are directly related to the grid and not when using binding -> driver.

That being said, you could subclass ErrorHandler and assign it to your webdriver instance after creation with your own errors (see https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L93).

I wouldn't be against allowing an error handler to be added to `__init__`, but wonder how many people would use this

**Comment by lmtierney** [comment]
I'll leave this open for a few days to see feedback

**Comment by peterstory** [comment]
Just for reference, here's an example of a page-specific (rather than grid-related) error which is also encompassed by `WebDriverException `:

* Message: Reached error page: about:neterror?e=nssFailure2&u=WEBSITE_URL_GOES_HERE&c=UTF-8&f=regular&d=The%20connection%20toWEBSITE_URL_GOES_HEREwas%20interrupted%20while%20the%20page%20was%20loading.

I'd like to treat this type of error differently, which I'm currently doing with my hack-ish searching for error substrings.

**Comment by lmtierney** [comment]
Fun fact. That 'hack-ish' way is basically how selenium does it https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L118-L157
