### ISSUE TITLE
Is it possible to call the `executePhantomJS` method from a `RemoteWebDriver` instance?  

### ISSUE THREAD

**Issue by Frannsoft** [SeleniumHQ/selenium#3866]
OS:  Windows
Selenium Version:  3.0.1
Browser:  N/A (PhantomJS)

Is it possible to call the `executePhantomJS` method from a `RemoteWebDriver` instance?  

The `PhantomJSDriver` object has the ability to call a PhantomJS specific script, but this method does not exist on `RemoteWebDriver`.  

I'm using Selenium Grid to run my tests, but am not able to find a good way to run PhantomJS scripts on the `RemoteWebDriver`.  I've tried manually adding the 'executePhantomScript' command to the `CommandExecutor.CommandInfoRepository` in a `RemoteWebDriver` derivative, but that does not seem to allow the script to run successfully (even though the command appears to be added successfully).  The command I'm adding is `/session/{sessionId}/phantom/execute`.  Output when attempting to run a script after adding the command:

```
System.NotImplementedException : POST /session/xxxx/phantom/execute
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'xxxx', ip: 'xxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_111'
Driver info: driver.version: unknown
```
Scouring the Issues here and in the GhostDriver repo does not turn anything up.

Is this a hopeless scenario?  If so, it seems like full PhantomJSDriver functionality is limited to local usage.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

But, no, you cannot call a phantomjs script through standalone; the endpoint is not implemented (as you experienced)  `System.NotImplementedException : POST /session/xxxx/phantom/execute`
