### ISSUE TITLE
driver.get throwing unhandled exception when using await/async

### ISSUE THREAD

**Issue by efx** [SeleniumHQ/selenium#3869]
## Meta -
OS:  macOS Sierra
nodejs version: 7.9.0
Selenium Version:  
` "selenium-webdriver": "^3.3.0" ` 
Browser:  
ChromeDriver 2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b)
Google Chrome 57.0.2987.133

## Expected Behavior -
web driver client to start browser and navigate to page

## Actual Behavior -
```
$ SELENIUM_BROWSER=chrome SELENIUM_PROMISE_MANAGER=0 node --harmony_async_await test.js
(node:55954) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'execute' of undefined
(node:55954) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[test.txt](https://github.com/SeleniumHQ/selenium/files/945347/test.txt)


```
## Steps to reproduce -
1. rename attached file to test.js
2. run npm install selenium-webdriver@3.3.0 (or navigate to a directory that has this version) 
3. run `SELENIUM_BROWSER=chrome SELENIUM_PROMISE_MANAGER=0 node --harmony_async_await test.js`

**Comment by jleyba** [comment]
Can't help you if you don't provide a concise reproducible test case.

If you have something like this:

```js
async function test() {
  // This generates a promise that is not being handled.
  // If it is rejected, you'll get the error you reported.
  driver.get(url);
}
```

You should just need an `await` statement

```js
async function test() {
  await driver.get(url);
}
```

**Comment by efx** [comment]
Sorry, thought I'd attached the file test.js:
```javascript
const webdriver = require('selenium-webdriver');


const chrome = require('selenium-webdriver/chrome');
// disabling via following 2 lines does not seem to affect it
//const { promise } = webdriver;
//promise.USE_PROMISE_MANAGER = false;
async function test() {
        const options = await new chrome.Options();
        const driver = await new chrome.Driver(options);

        return await driver.get('https://www.google.com');
}
test();
```

That solves it for me; In the above test.js, I was incorrectly using `return await` instead of `await`.
