### ISSUE TITLE
IE Browser | invalid selector exception if xpaths are used

### ISSUE THREAD

**Issue by dinezv** [SeleniumHQ/selenium#3870]
## Meta -
OS:  Windows 7, Windows 8 and Windows 10
Selenium Version:  2.53.1 & 3.3.1
Browser:  IE-10 and IE-11

org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression //*[contains(text(),'Country')]/ancestor::li[@class='clearfix listItemTrackPosition']//i[contains(@class,'remove-row')] because of the following error:
TypeError: Object doesn't support property or method 'toLowerCase' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 109 milliseconds

The xpath //*[contains(text(),'Country')]/ancestor::li[@class='listItemTrack']//i[contains(@class,'remove-row')] is valid and works perfectly fine on Chrome & Firefox browsers. However, it fails with the above error in IE-10/IE-11.

Similarly following xpath expression is failing on IE-10 & IE-11:

org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression //li[contains(@class, 'listItemTrackPosition')][1]//div[contains(@id, 'ruleConditionsFormattedText')] because of the following error:
TypeError: Object doesn't support property or method 'toLowerCase' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 78 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'win7-01', ip: '192.168.2.21', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=false, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=true, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=false, ie.ensureCleanSession=true, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:32396/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 194f63fd-7a14-4b2b-9c5e-38aa5ab57726
*** Element info: {Using=xpath, value=//li[contains(@class, 'listItemTrackPosition')][1]//div[contains(@id, 'ruleConditionsFormattedText')]}
Command duration or timeout: 584 milliseconds

Anyone noticed similar issues with IE? what is the solution if so?

Thanks...

**Comment by lmtierney** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) to reopen the issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by gauravgarg-777** [comment]
I am getting the same issue while using IE. Selenium Automation code works fine in Google chrome and Firefox whereas in IE, it shows the same error as mentioned above.

**Comment by barancev** [comment]
@gauravgarg-777 I'm sorry to say that but "getting the same issue" message contains zero information. Please provide a [concise reproducible test case](http://sscce.org/).

**Comment by gauravgarg-777** [comment]
I have encountered the same error message as mentioned above using same version of Selenium on IE11
