### ISSUE TITLE
How To Find Parent or Child Element

### ISSUE THREAD

**Issue by anzhehong** [SeleniumHQ/selenium#3871]
**Hello**,

I'm really new to `Selenium` and I just wonder whether we are able to find the **parent element or child element** using `Selenium:: WebDriver:: Element`? For example, here are two `UITableViewCell` in the tableView and if I have gotten the top image element, how can I get the element with the text 'Wiki - R311' or the second image on the second `UITableViewCell`?

Moreover, I am using **ruby** to write the codes.
![img](http://obl02ush1.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-04-21%20%E4%B8%8A%E5%8D%889.23.03.png)

> Thanks so much.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group or join us in IRC on Freenode `#selenium`
