### ISSUE TITLE
New Errors added in selenium-webdriver 3.4 never get used due to naming error [rb]

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#3878]
Selenium Version:  
3.4.0 - ruby
Browser:  
Firefox

The new errors added in selenium-webdriver 3.4.0  (ElementNotInteractable and ElementClickIntercepted) never get returned due to `for_code` - https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/error.rb#L218 - requiring eerror class names to end in 'Error'.  They should probably be renamed to ElementNotInteractableError and ElementClickInterceptedError

**Comment by twalpole** [comment]
@lmtierney @titusfortner Thoughts?

**Comment by lmtierney** [comment]
You're absolutely right, thanks for catching that

**Comment by lmtierney** [comment]
Fixed via 6e88496
