### ISSUE TITLE
UnreachableBrowserException in Selenium 2.45 when used in combination with SoapUI

### ISSUE THREAD

**Issue by tiegs** [SeleniumHQ/selenium#388]
Used versions:
SoapUI Pro v 5.1.2 (soapui-pro-maven-plugin)
Selenium 2.45 is used (selenium-java)
httpclient 4.3.6 is used

Steps to reproduce:
`WsdlProject wsdlProject = new WsdlProject("");`
`WebDriver driver = new FirefoxDriver();`

Result in Selenium 2.45:
The Browser is started but closed immediately.
Reproducible in Firefox and Chrome.

The following exception is thrown:
> org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session.  Possible causes are invalid address of the remote server or browser start-up failure.
> Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
> System info: host: 'xxx', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_75'
> Driver info: driver.version: FirefoxDriver
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
> 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
> 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
> 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
> 	at my.project.selenium.webdriver.test.foo(awda.java:77)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
> 	at org.testng.TestRunner.run(TestRunner.java:617)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
> 	at org.testng.TestNG.run(TestNG.java:1057)
> 	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
> 	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
> 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)

Result in Selenium 2.44:
Works as expected

I was able to trace the problem down to ApacheHttpClient, line 72:
`org.apache.http.HttpResponse response = fallBackExecute(context, httpMethod);`
The Problem seems to be the communication between selenium and the webdriver.

From the release notes of v 2.45: "Pull HttpClient implementation details out of HttpCommandExecutor".Maybe this change is responsible for the behavior?

**Comment by andreastt** [comment]
Does it work without SoapUI?

**Comment by tiegs** [comment]
Yes, it does work without the SoapUI-call. 
Its just weird that (and how) the behavior changed between 2.44 and 2.55.

Using selenium v 2.44 the SoapUI-call did not have any influence on the behavior of selenium  and I expected this to be the same in v 2.45 but the current version crashes. 

I'm not sure if this is an issue in Selenium or in SoapUI though considering the fact that it does work with the previous version I assumed its something wrong with the way selenium uses HttpClient but of course I may be wrong and SoapUI is to blame here. If this is the fact I'll submit an error-report there.

**Comment by lukeis** [comment]
This very much appears to be an issue with SoapUI, please log an issue there. I don't see a reproduction of the issue with normal java code.

**Comment by tiegs** [comment]
I think now I know what the Problem is:
SoapUI sets the default proxyselector to null and Apache httpclient is not expecting this.

Workaround:
`ProxySelector proxy = ProxySelector.getDefault();
WsdlProject wsdlProject = new WsdlProject("");
ProxySelector.setDefault(proxy);
WebDriver driver = new FirefoxDriver();`

@peidong-hu sent a patch for a similar problem in selenium-standalone-server-plugin two days ago:
https://github.com/Ardesco/selenium-standalone-server-plugin/issues/23

Just wanted to inform you (and maybe help a fellow who's having the same problem).

**Comment by jianfengs** [comment]
@tiegs 

I have been using that solution for a while but if we run test in parallel for both SOAPUI and Selenium test, it is still possible that SOAPUI set proxy to null at the same time firefox driver tries to start an instance. 

Do you know which exact method from SOAPUI JAVA API, they set the proxy to null?

If I add 
ProxySelector proxy = ProxySelector.getDefault(); 

to the every beginning of the build (still not sure how can I do that);

And then add 
ProxySelector.setDefault(proxy);

before firfox driver instance initiate.


Do you think that will help?

**Comment by tiegs** [comment]
Hi @jianfengs 

I can't tell what method SoapUI is using, sorry.

I'm not entirely sure what kind of parallel you're running your tests. We do run our test sequentially but for example one Test SoapUI one Selenium then SoapUI again. We do not run SoapUI and Selenium at the same time. That's why above workaround works for us.

If I remember correctly what you're describing is pretty much what we do: We save the default ProxySelector to some static variable when initializing our Selenium-Testrunner (before initializing SoapUI I think) and then reset it using `ProxySelector.setDefault(proxy);` before each Selenium-Test. But that only works reliable if you're not running SoapUI and Selenium at the same time (you'd propably run into some pretty nasty timing stuff here if you do)...

If you're using both in parallel the proper solution would be to force Selenium and SoapUI to use different httpclients I guess...
If running into this situation I'd maybe even head over to the guys at smartbear and file a bug against SoapUI for setting the default ProxySelector to null...don't know if this is legitimate.

Hope that clears up things a little...
