### ISSUE TITLE
WebDriver doesn't work properly with C# LINQ

### ISSUE THREAD

**Issue by drkghost** [SeleniumHQ/selenium#3883]
## Meta -
OS:  Windows 8.1 x64
Selenium Version: 3.0.1, C# nuget package  
Browser:  Chrome
Browser Version:  56.0.2924.87

## Steps to reproduce -
1. Open web-page with element located by some XPath which contains Text
2. Run one of the following functions for waiting
For Example:
Waiter(driver, 2000, "//button[@id='test_button']", "BUTTON");

1. 
```
public static void Waiter(IWebDriver driver, int millisec, string xpath, string text)
{
try
{
(new WebDriverWait(driver, TimeSpan.FromMilliseconds(millisec))).Until(
    d => d.FindElements(By.XPath(xpath)).Any(
        element => element.Displayed && element.Enabled && element.Text.Equals(text)));
}
catch (WebDriverTimeoutException ex)
{
// do smth
}
}
```

2.  
```
public static void Waiter(IWebDriver driver, int millisec, string xpath, string text)
{
try
{
(new WebDriverWait(driver, TimeSpan.FromMilliseconds(millisec))).Until(        
    d =>
    {
        var elements = d.FindElements(By.XPath(xpath));
        return elements.Any(element => element.Displayed && element.Enabled && element.Text.Equals(text));
    });
catch (WebDriverTimeoutException ex)
{
// do smth
}
}
```

3. 
```
public static void Waiter(IWebDriver driver, int millisec, string xpath, string text)
{
try
{
(new WebDriverWait(driver, TimeSpan.FromMilliseconds(millisec))).Until(
    d =>
    {
        var elements = d.FindElements(By.XPath(xpath));
        foreach (var element in elements)
        {
            if (element.Displayed && element.Enabled && element.Text.Equals(text))
            {
                return true;
            }
        }
    
        return false;
    });
catch (WebDriverTimeoutException ex)
{
// do smth
}
}
```

## Expected Behavior -
all examples should work identically

## Actual Behavior -
1st example causes StaleElementReferenceException
2nd and 3rd works properly without errors/exceptions

**Comment by diemol** [comment]
Apologies for the poor handling of this issue on our side.

Is this still valid? If so, can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information.
