### ISSUE TITLE
this pageLoadTimeout  is useless in Selenium3.4、FireFox53（geckodriver0.16）

### ISSUE THREAD

**Issue by yc2164708** [SeleniumHQ/selenium#3887]
System.setProperty("webdriver.gecko.driver", "D:\\workspace\\smart\\resources\\driver\\geckodriver_x64.exe");
WebDriver driver = new FirefoxDriver();
driver.manage().timeouts().pageLoadTimeout(8, TimeUnit.SECONDS);
driver.get("..........");

**Comment by yc2164708** [comment]
1493019028491	geckodriver	INFO	Listening on 127.0.0.1:4346
1493019029115	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1493019029401	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManJavaSacgreirp.tj sem:671 < startup()@resource://gre/modules/ArddroonrM:a nagerre.sjosumr:c8e3:4/ /<g rset/amrotduupl(e)s@/rAedsdoounrMcaen:a/g/egrr.jsm, linee 1/6m5o7d:u lNeSs_/EARdRdOoRn_MNaOnTa_gIeNrIT.IjAsLmI:Z3E1D2:9  A<d doobnsMearnvaeg(e)r@ riess onuortc ei:n/i/tgirael/components/addonManager.js:65
ized
1493019030598	Marionette	INFO	Listening on port 32397
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
四月 24, 2017 3:30:30 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
