### ISSUE TITLE
Popu-Menu Problem (bug ?) on Facebook

### ISSUE THREAD

**Issue by fi11222** [SeleniumHQ/selenium#3891]
## Meta -
OS:  Ubuntu 16.04 server (production) / Linux Mint 18 (dev)
Selenium Version:  3.0.2 used with ChromeDriver 2.27 through Python 3.5.2
Browser:  Chromium 57.0.2987.98 (64 bit) / Chrome 58.0.3029.81 (64 bit)
Browser Version: Chromium 57.0.2987.98 (64 bit) / Chrome 58.0.3029.81 (64 bit)

## Expected Behavior -
I am trying to locate a menu Item using xpath in order to click on it.

## Actual Behavior -
I have a case which works and one in which it does not.

Here is the case which works
![menu ok](https://cloud.githubusercontent.com/assets/6010464/25329727/a8e2f18a-28fa-11e7-92fe-b89a98b07f6c.png)
And here is the Python code I use:

        try:
            # wait for the presence of the settings arrow down button
            l_settings = WebDriverWait(self.m_driver, 15).until(
                EC.presence_of_element_located((By.XPATH, '//a[contains(@class, "_5lxs")]')))

            l_settings.click()
        except EX.TimeoutException:
            self.m_logger.critical('Did not find settings arrow down button')
            self.dump_html()
            raise

        try:
            # wait for the presence of the log-out button
            l_logoutButton = WebDriverWait(self.m_driver, 15).until(
                EC.presence_of_element_located(
                    (By.XPATH, '//a[@class="_54nc" and contains(@data-gt, "menu_logout")]')))

            l_logoutButton.click()
        except EX.TimeoutException:
            self.m_logger.critical('Did not find logout button')
            self.dump_html()
            raise

The first click displays the Facebook settings menu and the second selects the "logout" option. This code works without any problem.

The case **which does not work** is the following:
![menu fail](https://cloud.githubusercontent.com/assets/6010464/25330067/e8feea3e-28fb-11e7-81ac-57953aed29d1.png)
It seems very similar to the previous one (click on a link to make a pop-up menu appear and then select one of the menu items). Here is the code that I use:

            try:
               # The link to make the pop-up menu appear
                l_modeLink = p_story.find_element_by_xpath(
                        './/div[contains(@class, "UFILikeSentence")]//div[@class="_3scp"]' +
                        '//div[contains(@class, "uiPopover")]/a')

                l_modeLink.click()
            except EX.NoSuchElementException:
                self.m_logger.info('No mode selector')

             try:
                 # Waiting for the pop-up menu to appear
                 l_menu = WebDriverWait(self.m_driver, 10).until(
                     EC.presence_of_element_located((By.XPATH, '//ul[@class="_54nf"]')))

                 # scanning through all the menu items
                 for l_item in l_menu.find_elements_by_xpath('.//div[@class="_3scn"]'):
                     l_text = l_item.text
                     l_html = l_item.get_attribute('outerHTML')

                     # click on the one which contains the string "(unfiltered)"
                     if re.search('\(unfiltered\)', l_html+l_text):
                          l_item.click()

The first click makes the pop-up menu appear and the second is supposed to select the 3rd menu item. The behavior I obtain is strange but highly repeatable. For the first such pop-up menu on a Facebook page, it works. But for the second (and thereafter), it fails. In the latter case, this is what happens:

- The variable `l_text` **is empty** for all menu items, as if they contained no text.
- However, the variable `l_html` contains the expected HTML fragment which **does contain some text!** (This is the reason why I test the presence of the "(unfiltered)" string not only on `l_text` but on `l_html + l_text`
- The click fails with an error indicating the element is not visible. However, it IS clearly visible as I can see on the browser as the script is executing. If I add a wait contition on the visibility of the element, it timeouts however long the delay.

As can be seen on the screenshots, the implementation of the two pop-up menus are similar (both are place within a `div` of class `uiContextualLayerPositioner`) However, one is placed at the end of the body element (the one which works) while the one is at the beginning of the global page container div (the one which does not). I do not know if this has any influence.

The behavior is the same both on my dev environement (Mint 18 / Chrome) and on my production environment (Ubuntu 16.04 / Chromium)

## Steps to reproduce -
See code above.

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help
--> I will do that too

**Comment by lukeis** [comment]
you likely are locating the wrong element. I'd suggest asking on the selenium-users mailing list for help. Issues logged here are meant to fix bugs in selenium itself, not to help troubleshoot issues with selenium, that's what the mailing list is for.

https://groups.google.com/forum/#!forum/selenium-users

**Comment by fi11222** [comment]
You were right. I found the problem. Sorry ....
