### ISSUE TITLE
[python bindings] send_keys throws

### ISSUE THREAD

**Issue by dwt** [SeleniumHQ/selenium#3892]
## Meta -
OS:  OSX 10.12.4 (16E195)
Selenium Version:  selenium (3.4.0)
Browser:  Firefox
Browser Version:  53.0 (64-Bit)

## Expected Behavior -
I'm trying to send_keys() to a content editable html element `        self._find_element(By.CSS_SELECTOR, 'body').send_keys(MARKER)`. This worked fine under Firefox 52

## Actual Behavior -
This now raises with Firefox 53

## Steps to reproduce -
```
#!/usr/bin/env python

from selenium import webdriver

driver = webdriver.Firefox()
driver.get("http://ckeditor.com")

MARKER = 'fnord'
iframe = driver.find_element('css selector', 'iframe.cke_wysiwyg_frame')
driver.switch_to.frame(iframe)
driver.find_element('css selector', 'body').send_keys(MARKER)
```

I'm guessing that the API of Firefox may have changed - maybe that's a bug, maybe it's something you have missed. I don't know, so I'm reporting it here.

**Comment by AutomatedTester** [comment]
Did you upgrade your GeckoDriver?

**Comment by dwt** [comment]
Of course the newest version of gecko driver isn't accessible via home-brew yet. 👎 

I'll check that once it becomes available.

The stack trace is:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    driver.find_element('css selector', 'body').send_keys(MARKER)
  File "/Users/dwt/.virtualenvs/sntl-zms/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 349, in send_keys
    'value': keys_to_typing(value)})
  File "/Users/dwt/.virtualenvs/sntl-zms/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "/Users/dwt/.virtualenvs/sntl-zms/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/Users/dwt/.virtualenvs/sntl-zms/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected [object Undefined] undefined to be a string
```
p.s.: I know this isn't the place to complain, but man is it annoying that I have to keep track of yet another piece of infrastructure that needs simultaneous releases with the browser. :-((((

**Comment by AutomatedTester** [comment]
Closing as this has been fixed in the latest GeckoDriver

**Comment by lmtierney** [comment]
@dwt AFAICT it is available via homebrew

**Comment by dwt** [comment]
Got it, and it works. Thanks!
