### ISSUE TITLE
Safari 10 with Selenium 3+ click()

### ISSUE THREAD

**Issue by fabiyo** [SeleniumHQ/selenium#3894]
OS:  Sierra 10.12.4
Selenium Version:  
3+ (tried all versions)
Browser:  Safari 10.1

When I program my selenium test case I can load a page without a problem. Finding an element also works. But clicking on a link (<a/>) is not working. It just doesn't do anything. When I stop the Safari session and enable the window and I click on it, still nothing. I have to click a few times before it works. Also tried doubleclick() with Action but same issue.

I have tried different version of selenium and also been looking on the net for same kinda issues. Most of them having the same issue are from the protractor framework.

The strange thing is that Selenium acts as if the click actually executed. I can run my test and it succeeds, and Selenium states no error was thrown when clicking.

`@FindBy (id, "someId")`
`WebElement link;`

`...`

`link.click(); // not doing anything`

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
