### ISSUE TITLE
Remote driver fails with KeyError: 'moz:firefoxOptions' if given a profile

### ISSUE THREAD

**Issue by PyDeq** [SeleniumHQ/selenium#3897]
## Meta -
OS:   server: Debian 8 (jessie), client: openSUSE Leap 42.1
Selenium Version:  3.4.0
Browser:  Mozilla Firefox
Browser Version:  45.8.0

## Expected Behavior -
A `WebDriver` instance to be initialized.

## Actual Behavior -
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/tests/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/srv/tests/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 181, in start_session
    capabilities["moz:firefoxOptions"]["profile"] = browser_profile.encoded
KeyError: 'moz:firefoxOptions'
```

## Steps to reproduce -
```python
from selenium import webdriver

executor = 'http://turris-qa-lan-tester:4444/wd/hub'
capabilities = webdriver.DesiredCapabilities.FIREFOX.copy()
capabilities["marionette"] = False
profile = webdriver.FirefoxProfile()
webdriver.Remote(executor, capabilities, profile)
```

**Comment by SergioLeone** [comment]
You can't use ff 45 with latest geckodriver and selenium 3.4.0. Read the changelog, you need firefox 52+, gecko 0.16.0, and selenium 3.4.0

**Comment by PyDeq** [comment]
Oh, I apologize, I forgot to add `capabilities["marionette"] = False` to the reproducer :-(

**Comment by AutomatedTester** [comment]
I will get this sorted but you appear to be using a version of Firefox that is not supported(and is 8 vresions old). May I ask why?

**Comment by PyDeq** [comment]
It's the version available in the official repositories of the current stable Debian.
What do you mean by "not supported"? I [thought](www.seleniumhq.org/about/platforms.jsp) that Selenium supports the latest ESR release and the previous ESR release.
Does it affect this issue?

**Comment by AutomatedTester** [comment]
Firefox 45 is going to be the last ESR that applies to. Moving forward, Mozilla is going to be controlling what is supported which will likely be release versions only and ESR will likely be locked to a specific GeckoDriver version

**Comment by PyDeq** [comment]
Hopefully, GeckoDriver becomes at least feature complete before Selenium drops support of Firefox 45... :)

Thank you very much for the fix! :)

**Comment by AutomatedTester** [comment]
@PyDeq what features are you missing from GeckoDriver? We are currently passing 92% of the Selenium test suite

**Comment by PyDeq** [comment]
@AutomatedTester, I don't know. GeckoDriver's status is [said](https://github.com/mozilla/geckodriver/blob/master/README.md) to be "not yet feature complete". We heavily depend on our test suite. That is not a good place for experimenting with incomplete technologies. So we are still waiting with the migration to GeckoDriver.

But don't take me wrong. I am really happy that you are working on GeckoDriver. I am looking forward to the first major release. It's just this transition period what makes me worried. But it's the same with any new technology.
