### ISSUE TITLE
WebDriverTimeoutException thrown on running script in IE browser Canopy F# Visual Studio

### ISSUE THREAD

**Issue by Uma-Maheswari** [SeleniumHQ/selenium#3899]
## Meta -
OS:  Windows 8.1

Selenium Version:  3.0.0

Browser:  Internet Explorer 11

Browser Version:  11.0.9600.18618 64-bit

Hi, I am using IE11 browser to run my Canopy F# script. While running the script I am getting WebDriverTimeoutException error in passing the inputs to the Text fields. Following is my simple use case,
I want to open a google site and perform search for term 'table'. On executing the script, the IE browser is opened and navigated to google site and nothing happens after that. However, I am able to execute the same script successfully on Chrome and FF browser.

I am using 64bit IEDriver and 64bit IEbrowser. Even tried, using 32bit IEDriver and 64bit browser. Attached the console and Network data details for reference.
![consolemessage](https://cloud.githubusercontent.com/assets/13943472/25385952/41a51a40-29e3-11e7-90f7-628d02d05084.jpg)
![samplescript](https://cloud.githubusercontent.com/assets/13943472/25385961/4c98bdf8-29e3-11e7-81bd-dd6c6cc8ce5b.jpg)

Thank you in Advance

**Comment by lmtierney** [comment]
Looks like you're trying to send keys into a hidden and disabled input, try using `#lst-ib`

**Comment by Uma-Maheswari** [comment]
@Imtierney, I tried using the id you have suggested. Still getting WebDriverTimeoutException after the browser is opened

**Comment by lmtierney** [comment]
I suspect this is an issue with canopy/F# then. 

Please provide [concise reproducible test case](http://sscce.org/) using purely selenium code so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
