### ISSUE TITLE
Unicode characters for "@" key is not working in Internet Explorer 

### ISSUE THREAD

**Issue by skuppusw** [SeleniumHQ/selenium#3901]
## Meta -
OS:  Windows 7

Selenium Version:  
 2.53.1
Browser:  
Internet Explorer 
Browser Version:  
 IE11 (64-bit) 
IE Driver Version
3.0.0-x64-IEDriverServer 

## Expected Behavior -
It should enter @ in text field
## Actual Behavior -
Its entering q in text field

## Steps to reproduce -
1. Unicode characters are not working.
2. Below piece of code is working in chrome but not working in IE . I am using webdriverIO 
browser.keys(['\u0040']);

Please be sure to include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/
If you can't provide a link to the page, consider creating a reproducible page on https://jsfiddle.net/
-->

**Comment by skuppusw** [comment]
Could you please let me know is there any update on this issue

**Comment by w0ut0** [comment]
I think this is related to https://github.com/SeleniumHQ/selenium/issues/4523, are you by any chance on a non-US keyboard?

**Comment by Alexander-Kruglov** [comment]
I have the same problem with €

OS: Windows 7
Selenium Version: 3.8.1
Browser: Internet Explorer
Browser Version: 11.0.9600.18894

Action: driver.sendKeys("\u20AC").perform();
Expected: should send €
Actual: sends 4

**Comment by barancev** [comment]
Closing the issue, it should be fixed as a part of #4523
