### ISSUE TITLE
Cannot pass customized DriverService to FirefoxDriver c'tor

### ISSUE THREAD

**Issue by h-arlt** [SeleniumHQ/selenium#3902]
## Meta -
OS:  Any

Selenium Version:  3.4.0

Browser:  Firefox

Browser Version:  53.0 (64-bit)

## Expected Behavior -
It should be possible to pass an `DriverService` or `CommandExecutor`  instance as argument to some FirefoxDriver constructor.

## Actual Behavior -
FirefoxDriver constructors always use default DriverService and customized DriverService's cannot be passed as argument to any FirefoxDriver constructor.

## Steps to reproduce -
Attempt to create an instance of FirefoxDriver that takes an DriverService or CommandExecutor as argument.
Use-cases where this is necessary: use a specific port for the driver service or some custom environment when creating the browser process.

**Comment by barancev** [comment]
If you want to pass a cusom CommandExecutor instance you should call a RemoteWebDriver constructor:
`public RemoteWebDriver(CommandExecutor executor, Capabilities desiredCapabilities)`

**Comment by h-arlt** [comment]
So you force me and other users to copy all the FirefoxDriver code and 
create my own FirefoxDriver class just because you are unwilling to 
provide a proper way to pass a custom driver service?

Such a c'tor already exists for ChromeDriver and doing so for 
FirefoxDriver would just be fair and consistent.

PS: Closing issues before the authors had a chance to reply on your 
feedback is quite rude.

**Comment by barancev** [comment]
FirefoxDriver constructor that accepts a CommandExecutor instance just calls a super constructor:

**Comment by barancev** [comment]
OK, reopening the issue, please explain in more detains your suggestion that cannot be resolved by the provided solution.

**Comment by barancev** [comment]
```
DriverService myDriverService = ...;
WebDriver driver = new RemoteWebDriver(new DriverCommandExecutor(myDriverService, capabilities));
```

**Comment by h-arlt** [comment]
What about the rest of FirefoxDriver's logic, e.g. handling of certain default settings or like path to Firefox binary, the profile to use etc.

**Comment by barancev** [comment]
It's a driver server responsibility, e.g. GeckoDriverService to drive a browser with the help of geckodriver or XpiDriverService to drive a browser in legacy mode.

Watch the current state of FirefoxDriver, you can see it contains almost zero logic, just constructors that deletage all work to driver servers:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java

What part of FirefoxDriver logic is important for you that you want to be reusable?

**Comment by h-arlt** [comment]
> handling of certain default settings or like path to Firefox binary, the profile to use etc.

**Comment by barancev** [comment]
It's not handled in FirefoxDriver. It's a driver server responsibility. How would adding a constructor that accepts a DriverService or CommandExecutor resolve your issue? Please provide a piece of code that shows how you are going to use it.

**Comment by h-arlt** [comment]
Maybe the following explanation helps to get the idea:
I need to subclass FirefoxDriver in order to be able to automatically add some extensions to the generated/configured profile and to configure the driver service's environment suitable for headless mode via Xvfb.
I don't want to create the driver service by myself but be able to modify it after it has been constructed.

At the moment, I'll have to store my headless setting in the caps and drop it from there later on in 'startClient' where I have access to the command executor and its driver service.

It's more about customization hooks than c'tors. Sadly, FirefoxDriver doesn't provide any customization hooks that can be overriden by subclasses.

**Comment by h-arlt** [comment]
And of course, you are right when saying that a stand-alone c'tor that accepts a driver service or command executor does not solve my issue. I need one that the other c'tors delegate to.

**Comment by barancev** [comment]
We've implemented FirefoxDriver condtructors that accept a driver server instance as a parameter.

If you have a better idea how to make FirefoxDriver more extensible you can submit a pull request.
