### ISSUE TITLE
utils.is_url_connectable should take a URL?

### ISSUE THREAD

**Issue by sethamclean** [SeleniumHQ/selenium#3904]
I am starting a docker container using the image 'selenium/standalone-chrome' as part of my integration tests. If tests run immediately they fail due to the service apparently not being ready. This can be resolved by using `utils.is_url_connectable`. However this container may not necessarily be on the local system. 

`utils.is_connectable` seems like a good alternative, but it doesn't seem to check the `/status` URL and the service seems to not be ready even when this returns `True`.

Additionally the function name `is_url_connectable` seems strange given only a port can be provided as an argument.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
