### ISSUE TITLE
with release of 3.4.0, 3.3.0 dockerized builds fail

### ISSUE THREAD

**Issue by starpit** [SeleniumHQ/selenium#3906]
## Meta -
OS:  Linux

Selenium Version:  3.3.0

Browser:  firefox

## Expected Behavior -
we have dockerized tests that use maven, via gradle, to pull in selenium-java:3.3.0; we have been using this in tandem with geckodriver 0.15 for 6 or more weeks now, without a problem.

recently, our automated builds started to fail, despite not upgrading selenium or geckodriver. inspecting the logs, and it became apparent that, despite explicitly pegging to selenium-java:3.3.0, maven had started to pull in selenium-api (and other selenium bits) version 3.4.0! hence our tests began to fail.

attempts to peg to 3.3.0, e.g. 
```
    compile (group: 'org.seleniumhq.selenium', name: 'selenium-remote-driver', version: '3.3.0'){force=true}
    compile (group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.3.0'){force=true}
    compile (group:'org.seleniumhq.selenium', name:'selenium-api', version:'3.3.0'){force=true}
    compile (group:'org.seleniumhq.selenium', name:'selenium-java', version:'3.3.0'){force=true}
```

were to no avail. yes, we pulled in all or ?mostly? 3.3.0, but tests failed with setWindowPosition (#3893) or `INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)` errors.

upgrading to 3.4.0 and geckodriver 0.16. yet other fails

upgrading to firefox 53, and STILL failures. this time org.openqa.selenium.UnsupportedCommandException: POST /session/75ed13ec-8201-2849-adee-6af35c9ed63f/log did not match a known command

this is a complete failblog. how can we expect to maintain stability if selenium updates cause our pegged, dockerized, tests to fail?

**Comment by barancev** [comment]
Both are known issues.

To maintain stability don't update to the latest selenium versions unless they prove their stability. There goes active development at the moment to implement w3c standard requirements, and not all parts of selenium are equally conformant to the standard. That causes issues. Sorry.

**Comment by starpit** [comment]
that was part of my point. we didn't upgrade any part of selenium. somehow, maven started picking up 3.4.0, despite my specifying 3.3.0.

**Comment by barancev** [comment]
I suppose we should blame htmlunit-driver for range version specification in POM file:
http://repo1.maven.org/maven2/org/seleniumhq/selenium/htmlunit-driver/2.25/htmlunit-driver-2.25.pom

**Comment by shs96c** [comment]
This is a maven bug. It's constraint resolution isn't working properly.

**Comment by asashour** [comment]
I suggest for the time being, you can exclude `selenium-support` from `htmlunit-driver`
