### ISSUE TITLE
getWindowHandles method

### ISSUE THREAD

**Issue by ccangle** [SeleniumHQ/selenium#3907]
I'm using the browser of android emulator 4.4.2 to test the multi-window switch function.
But i faced with some problems. Blow is the problem:
Only one windowHandle can be obtained by call the method "getWindowHandles()", the page used for test has more than one tab. Beside, when i call the method "getWindowHandles()" to get windowHandle in different web page, the problem is still here.

Is there has anyone who can help me, i would be very appreciated, thank you in advance!

Here are some environment infomation:
operator system: win7(64-bit)
android emulator:4.4.2

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
