### ISSUE TITLE
firefox downloading(updating) addons when running tests

### ISSUE THREAD

**Issue by SergioLeone** [SeleniumHQ/selenium#3908]
## Meta -
OS:  Win 7 x64

Selenium Version:  3.4.0

Browser:  Firefox

Browser Version:  53.0 64-bit

## Expected Behavior -
disabled auto update for addons

## Actual Behavior -
When running my tests firefox driver stops executing commands because it starts downloading some things. Sometimes it resumes after download, sometimes fails because of timeout for page load. Still, even if it resumes, the delay for download is big, like a few minutes sometimes.

Here's the log:
```
1493190654998   addons.productaddons    INFO    sending request to: https://aus5.mozilla.org/update/3/GMP/53.0/20170413192749/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%206.1.1.0
%20(x64)/default/default/update.xml
1493190656309   addons.productaddons    INFO    Completed downloading document
1493190656675   addons.productaddons    INFO    downloadXHR File download. status=200
1493190656684   addons.productaddons    INFO    Downloaded file will be saved to C:\Users\L094540\AppData\Local\Temp\tmpaddon-c40aec
1493190658529   addons.productaddons    INFO    downloadXHR File download. status=200
1493190658536   addons.productaddons    INFO    Downloaded file will be saved to C:\Users\L094540\AppData\Local\Temp\tmpaddon-2e96c4
```

I have added the following preferences to the profile that I'm creating in test setup method
```
ffprofile.setPreference("app.update.enabled", false);
ffprofile.setPreference("app.update.service.enabled", false);
ffprofile.setPreference("app.update.auto", false);
ffprofile.setPreference("app.update.staging", false);
ffprofile.setPreference("app.update.silent", false);
```
however the result is the same.

Haven't noticed this behavior with selenium 3.3.* and firefox 49.0.2, only started with latest selenium+geckodriver

**Comment by p0deje** [comment]
You should log this issue to [geckodriver](https://github.com/mozilla/geckodriver/issues).

**Comment by navels** [comment]
We're running into this with Selenium 3.4 and FirefoxDriver
