### ISSUE TITLE
Cookies returned by IE driver contain no info about domain and expiration date

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#391]
Cookies returned by IE driver contain no info about domain and expiration date

(Moved from https://code.google.com/p/selenium/issues/detail?id=8509)

**Comment by tomatobrown** [comment]
Just to clarify a little more.  The issue is not that the domain or expiration date are missing.  The issue is that when using IE the entire session cookie is not returning from selenium via "get_cookies" as it does with Chrome and Firefox

**Comment by barancev** [comment]
How do you know what's the issue if you're not the author? :)

IE  driver can't obtain cookies that have httpOnly flag set. It is a known restriction. But it is a completely different issue.

**Comment by tomatobrown** [comment]
Valid, maybe these are separate issues.  This issue (http://stackoverflow.com/questions/29775006/retrieving-all-cookies-from-ie-using-python/29778273#29778273) brought me to the link in your initial post.
