### ISSUE TITLE
Missing mouse move event when clicking on link

### ISSUE THREAD

**Issue by dwt** [SeleniumHQ/selenium#3910]
## Meta -
OS:  10.12.4 (16E195)
Selenium Version:  selenium-webdriver (3.4.0) (gem)
Browser:  Firefox 53.0, Geckodriver 0.16.0

## Expected Behavior -

When clicking on a link appropriate mouse moved, mouse enter events should be dispatched to the site.

## Actual Behavior -
Those are not dispatched

## Steps to reproduce -
open a page via selenium
click on a link
notice that mouse moved, mouse enter and hover handlers on body are not triggered.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. When this has been added we will reopen this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by dwt** [comment]
Well, do you guys actually implement mouse moved events at all with gecko driver? As far as I know that's not the case yet. If so, I don't want to spend an hour providing a test case just to hear 'ah yea, we don't do that yet'.

**Comment by lmtierney** [comment]
@dwt Mouse move events are absolutely implemented with all bindings (except node) and as long as you don't use a remote end (using bindings to talk directly to geckodriver works) and you are using FF 52.0.1+ and geckodriver 0.15+.

**Comment by lmtierney** [comment]
As far as events triggering off of the mouse move event, you would need to raise an issue with geckodriver if that's the case.
