### ISSUE TITLE
Not taking full page screenshot with TakeScreenshot on chrome and firefox in Selenium 3.4

### ISSUE THREAD

**Issue by samnit** [SeleniumHQ/selenium#3912]
Hi,
By using the TakeScreenshot I am not able to get full page screenshot of chrome and Firefox in  **Selenium 3.4**. It is only bringing the screenshot of the browser which is currently visible on the screen and not the section below it which has to be scrolled down to,  
**For chrome I am using chrome version 57 and driver 2.28
For Firefox I am using Version 53 with geckodriver-v0.16.0-win64**
The code I am using to capture screenshot is : -
private static String takeScreenshot(WebDriver lDriver) throws IOException, HeadlessException, AWTException  { 
		try {
		String screenshotBase64 = ((TakesScreenshot)lDriver).getScreenshotAs(OutputType.BASE64);
		return screenshotBase64;
			} 
               catch (Exception e) {
				throw e;	
			}	
		}

**Comment by lmtierney** [comment]
Screenshots will only show the current viewport going forward

https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot

**Comment by samnit** [comment]
@lmtierney Is there any suggestions on how can I capture the whole page in screenshot ??

**Comment by lmtierney** [comment]
I have no suggestions unfortunately. It is very hard to capture the "entire page" since it is hard to define that. What happens if the page is lazy loaded or never-ending? How do you capture that? Would have to do some research

**Comment by samnit** [comment]
@lmtierney okay thanks for the reply. Pls let me know if you come across anything for a workaround for this.

**Comment by alexramos1** [comment]
Firefox supports the command "screenshot --fullpage" from the developer console (Shift+F2).
There is no need to worry about how to define "entire page" or lazy-load, etc, just need to execute this command.
I tried sending Shift+F2 using SendKeys() but that didn't work.. Is there anyway to execute a Firefox developer console command from a Selenium script?

**Comment by abenitezitrs** [comment]
This is working for me:
WebDriver driver = DriverFactory.getWebDriver();
Screenshot screenshot = new AShot().takeScreenshot(driver);
ImageIO.write(screenshot.getImage(), "PNG", new File("pathToSaveTheScreenshot.png"));

With that I am capturing the entire page.
