### ISSUE TITLE
WebDriverException: Message: marionette was not a the name of a known capability or a valid extension capability

### ISSUE THREAD

**Issue by ghostwords** [SeleniumHQ/selenium#3915]
Ubuntu 14.04 (Travis)
Selenium Python bindings 3.4.0 (latest)
Mozilla Firefox 53.0 (latest)
geckodriver v0.16.1 (latest)

I originally commented on https://github.com/SeleniumHQ/selenium/issues/3890#issuecomment-296695933 because it appeared to be the same issue, but the [latest geckodriver release](https://github.com/mozilla/geckodriver/releases/tag/v0.16.1) did not address it for me.

The above combination of versions causes every one of our tests to fail on Firefox with `WebDriverException: Message: marionette was not a the name of a known capability or a valid extension capability`. Please see https://travis-ci.org/EFForg/privacybadger/jobs/226049565 for the full stack trace. Downgrading to Python bindings < 3.4.0 resolves the issue.

Here is the pull request where I run into this problem: https://github.com/EFForg/privacybadger/pull/1343.

Here is the branch where I check to see if it's fixed in geckodriver v0.16.1 (it is not): https://github.com/EFForg/privacybadger/compare/upgrade-selenium.

**Comment by AutomatedTester** [comment]
This is because it is trying to use the newSession stuff. Are you using this in a grid system?

There is one approach that we can take but want to understand how you are using it before I do that fix.

**Comment by ghostwords** [comment]
I don't think we are using Selenium Grid ... Travis handles the multiple-jobs-at-the-same-time thing. [Here is our Travis config](https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/.travis.yml).

**Comment by lmtierney** [comment]
@ghostwords You are using the remote webdriver in some capacity whether it be standalone or grid https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/tests/selenium/pbtest.py#L98

**Comment by ghostwords** [comment]
Sorry, I'm not very familiar with the terminology. Yep, we use the [remote to talk to geckodriver](https://github.com/EFForg/privacybadger/pull/1168). But we're not using Grid, right?

**Comment by AutomatedTester** [comment]
@ghostwords 

If you remove https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/tests/selenium/pbtest.py#L91-L94

and change https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/tests/selenium/pbtest.py#L98 to be `driver = webdriver.Firefox()` you will get rid of the issue in this bug and then let Selenium control GeckoDriver.

it will also allow you to get rid of https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/tests/selenium/pbtest.py#L105-L106 and the `try:` associated

**Comment by AutomatedTester** [comment]
and you could also delete the shell script referenced in https://github.com/EFForg/privacybadger/blob/a7461d299a21fd5ec442a2788a318b9141a5ea95/tests/selenium/pbtest.py#L91-L94

**Comment by ghostwords** [comment]
@lmtierney It's geckodriver, from shell/Travis output for every test on Firefox:
`geckodriver     INFO      Listening on 127.0.0.1:4444`

**Comment by lmtierney** [comment]
@ghostwords just to piggy-back off of what @AutomatedTester is saying. I did look at that PR you referenced and mouse moves ARE working if you use FF 52.0.1+ and geckodriver 0.15+

**Comment by ghostwords** [comment]
@AutomatedTester You're suggesting getting rid of `web-ext`, is that right? We have an issue to track that here: https://github.com/EFForg/privacybadger/issues/1294. From what I understand, the reason we use `web-ext` is to load the extension we are testing into Firefox, which doesn't seem currently possible without `web-ext`.

**Comment by ghostwords** [comment]
Yep, `move_to` seems to work fine after upgrading to the latest geckodriver, but on the other hand, all tests broke, which is what we're discussing here. My workaround at the moment is to downgrade Selenium bindings to before 3.3.x, but that's just a short-term band-aid.

**Comment by AutomatedTester** [comment]
@ghostwords ok, a quick fix for you is to remove `marionette` key from the `DesiredCapabilities.FIREFOX` dict.

With `webdriver.Firefox()` we already remove that key for you. since you are using `webdriver.Remote()`  we assume you know what you're doing (and not working around other Selenium bugs 😄 )

**Comment by ghostwords** [comment]
Cool, thank you, I'll try that right now.

**Comment by ghostwords** [comment]
Looking good locally, Travis should kick off in a minute ...

**Comment by ghostwords** [comment]
Yep, `ffcaps.pop('marionette', None)` did the trick. Could you point me at some docs or commits that should help me understand why it needed to be removed?

Also, there is a typo in the WebDriverException message template: "marionette was not a the ...". Should I open an issue in this repo?

Thank you @AutomatedTester and @lmtierney  for helping!

**Comment by AutomatedTester** [comment]
@ghostwords please raise a bug for the typo. Could you also raise a bug for webextension support.

As for where we remove that key, its in https://github.com/SeleniumHQ/selenium/commit/01ac9f8430ca668a6b72df37d0e44aca92d46c50#diff-3ae9b88bbdc04edbf1ed5f6e78d10661R140

I can flip the way the conditional works to prevent this type of issue from reappearing in the future but way you were using it is very atypical. If it arises again in the future then I might 😄

**Comment by lmtierney** [comment]
@ghostwords geckodriver is implementing the new w3c spec (https://w3c.github.io/webdriver/webdriver-spec.html) and `marionette` is not an expected capability.

The `marionette` capability is really just for selenium to help determine what the user wants out of the remote end (say, standalone/grid in order to start the correct service).

**Comment by ghostwords** [comment]
Looks like WebExtensions support got merged two days ago: https://github.com/SeleniumHQ/selenium/issues/1181. I'm not sure but I think we're still waiting on geckodriver (https://github.com/mozilla/geckodriver/issues/211) before we can ditch `web-ext` since that's what we use to drive Firefox. Does that sound right, @cowlicks?

**Comment by lmtierney** [comment]
#1181 added it for the javascript bindings; similar would need to be done for python. As for the geckodriver issue, I'll have to see how javascript is getting around it

**Comment by cowlicks** [comment]
@lmtierney you mean #3846 I think.

@ghostwords I think we should wait for the python bindings since we're free to run bleeding edge selenium.
