### ISSUE TITLE
MoveToElement not working for webdriver when repeteated 

### ISSUE THREAD

**Issue by gamcusa** [SeleniumHQ/selenium#3916]
## Meta -
OS:  W7

Selenium Version:  Selenium3

Browser:  Chrome 58

Browser Version:  

## Expected Behavior -
I need to move through and click the drop down menu item. I can do it once but fails on the next one
## Actual Behavior -
I am able to select the one of the items, but not others.
## Steps to reproduce -

    public static void pdPublicAboutMenu() {

    WebElement About = driver.findElement(By.xpath("//a[contains(.,'About')]"));
    WebElement WhoWeAre = driver.findElement(By.xpath("//a[contains(.,'Who We Are')]"));
    WebElement Glossary = driver.findElement(By.xpath("//a[contains(.,'Glossary')]"));

     // I am able to navigate to WhoWeAre page fine, but not on Glossary page
		
    Actions DropDown = new Actions(driver);
    // Step1 - Pass	
    DropDown.moveToElement(About).moveToElement(WhoWeAre).click().perform();

     // STep 2 - Fails
     DropDown.moveToElement(About).moveToElement(Glossary).click().perform();

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by swathikvsr** [comment]
@gamcusa  can you please provide me the link if you have logged any issue with  chrome?
