### ISSUE TITLE
[python] provide element locator in the error when element is invisible

### ISSUE THREAD

**Issue by php-coder** [SeleniumHQ/selenium#3917]
When we're trying to interact with invisible element from Python library we got an exception with the following message: `You may only interact with visible elements`. When this message is showing to user it doesn't help him to debug this situation because it miss the information about element itself.

I'm suggesting to include element locator in the error message, for example: `Element id=my-bth is invisible. You may only interact with visible elements`.

(I was initially reported this to the Selenium2Library (https://github.com/robotframework/Selenium2Library/issues/769) but author has said that this is Selenium issue.)

**Comment by aneeshchandy** [comment]
Which browser are you using? If it is htmlunit driver, then you may want to file the bug here: https://github.com/SeleniumHQ/htmlunit-driver/issues.

**Comment by p0deje** [comment]
Isn't stacktrace enough to point to the element in code that is not visible?

**Comment by php-coder** [comment]
> Which browser are you using? If it is htmlunit driver, then you may want to file the bug here:

Yes, it's htmlunit and I'm going to create issue in their bug tracker as you've suggested. Thanks!

**Comment by p0deje** [comment]
> Yes, it's htmlunit and I'm going to create issue in their bug tracker as you've suggested. Thanks!

If you think this should no longer be an bug in Selenium, please close this issue.

**Comment by php-coder** [comment]
> Isn't stacktrace enough to point to the element in code that is not visible?

I'm using RobotFramework with a plugin for Selenium and the only way to see this stacktrace is to enable debug level. Also I'm running tests on TravisCI and when test fails I couldn't get the report at all. A minor improvement that I'm asking makes debugging process much easier.

**Comment by p0deje** [comment]
> A minor improvement that I'm asking makes debugging process much easier.

I'm not against that, however there are complications that are needed to be taken into account. For example, if we take id from element, what should we do for elements that have no id?

**Comment by php-coder** [comment]
> For example, if we take id from element, what should we do for elements that have no id?

It's a good question. I suspect that it will be hard to construct something like a full path to the element (`/html/body/div/ul/li[3]/span`) in that case. In this case, an error message can be the same as now (without any details).
