### ISSUE TITLE
driver.close() not more working with Selenium 3

### ISSUE THREAD

**Issue by JaspalAujla** [SeleniumHQ/selenium#3919]
driver.close() not more supported by Selenium 3.

I am writing to request, please add or fix this function as it is very useful while automating test cases which switch through number of windows.

Selenium Version: 3.4.0 (Java)

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
