### ISSUE TITLE
Cookies returned by Safari driver contain no info about domain and expiration date

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#392]
Cookies returned by Safari driver contain no info about domain and expiration date

(Moved from https://code.google.com/p/selenium/issues/detail?id=8509)

**Comment by staudenmeir** [comment]
Another bug: The attribute _secure_ is always `false`.

**Comment by jleyba** [comment]
This will not be fixed. The current SafariDriver is deprecated and will be deleted in favor of Apple's safaridriver for Safari 10 when macOS Sierra is released.
