### ISSUE TITLE
pageLoadTimeout not more working with Selenium 3

### ISSUE THREAD

**Issue by JaspalAujla** [SeleniumHQ/selenium#3920]
Below function (script) is not working with Selenium 3:
driver.manage().timeouts().pageLoadTimeout(timeInSeconds, TimeUnit.SECONDS);

Selenium Version: 3.4.0 (Java)

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
