### ISSUE TITLE
driver.close() not working with Selenium 3

### ISSUE THREAD

**Issue by JaspalAujla** [SeleniumHQ/selenium#3922]
OS: Windows 10
Selenium Version: 3.4.0 (Java)
Browser: Firefox
Browser Version: 53.0 (32-bit)

When I use below line of code:
driver.close();

**Expected Behavior -** 
Then browser window (tab) should be closed

**Actual Behavior -**
But the browser window (tab) is not closing

**Steps to reproduce -**
1. Initialize the WebDriver:
System.setProperty("webdriver.gecko.driver","geckodriver.exe");
WebDriver driver = new FirefoxDriver();

2. Launch application:
driver.get("http://www.seleniumhq.org/");

3. Close the browser or tab:
driver.close();

**Comment by barancev** [comment]
What geckodriver version do you use? Please retest in 0.16.1

**Comment by JaspalAujla** [comment]
I have tested it with geckodriver version 0.16.1 and it is working fine. Please close this issue.

**Comment by jimevans** [comment]
Closing per request.

**Comment by phanigithub** [comment]
getting thee same issue, driver.close is not working. Bellow are error details 
```

```
---------------------------------------------
Failed to interpret value as array
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'PCNAME-PC', ip: '192.168.0.101', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160623154057, version=47.0.1, platform=XP, proxy=Proxy(), command_id=1.0, specificationLevel=0.0, acceptSslCerts=false, browserVersion=47.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=Windows_NT, device=desktop}]
Session ID: c5dd595e-6527-4c1e-bdac-72d7ed2b3f74
---------------------------------------------
```
```

**Comment by shailesh9999** [comment]
Simillar issue with Windows 8

Browser - Google Chrome - Version 59.0.3071.115 (Official Build) (64-bit)
ChromeDriver.exe - 2.30.477700
Selenium-java - 3.4.0

driver.close() is not working.
