### ISSUE TITLE
pageLoadTimeout not working with Selenium 3

### ISSUE THREAD

**Issue by JaspalAujla** [SeleniumHQ/selenium#3923]
OS: Windows 10
Selenium Version: 3.4.0 (Java)
Browser: Firefox
Browser Version: 53.0 (32-bit)

When I use below line of code:
driver.manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);

**Expected Behavior -**
Then it would implement the maximum wait (5 seconds) for page load to complete

**Actual Behavior -**
But the maximum time for page load to complete not implemented

**Steps to reproduce -**

1. Initialize the WebDriver:
System.setProperty("webdriver.gecko.driver","geckodriver.exe");
WebDriver driver = new FirefoxDriver();

2. Set page load timeout 1 second:
driver.manage().timeouts().pageLoadTimeout(1 , TimeUnit.SECONDS);

3. Launch application:
driver.get("http://www.seleniumhq.org/");

Here, if application would take more than 1 second to load completely then the exception related to page load timeout should be occurred. But, it is not occurring.

**Comment by barancev** [comment]
Raised an issue on geckodriver: https://github.com/mozilla/geckodriver/issues/694

**Comment by barancev** [comment]
Appears to be Java binding issue.

**Comment by chinmoyee23** [comment]
i am facing the same issue. may i know the steps to resolve.

**Comment by barancev** [comment]
Fixed by 91f9f2a6194a9c33006e9415c1f257c6a1fa5c04, should be released in version 3.5
