### ISSUE TITLE
`initialize': Connection refused - connect(2) for "127.0.0.1" port 4444 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by pmck91** [SeleniumHQ/selenium#3926]
## Meta -
OS:  
OSX
Selenium Version:  
"selenium-webdriver", "~> 3.4"

Browser:  
Firefox v 53

`el = driver.find_element(name: "patient_os_id_filter_show")`

AND

`wait = Selenium::WebDriver::Wait.new(:timeout => 15)
  wait.until {
    driver.find_element(name: "patient_os_id_filter_show")
  }`

Both throw the error

## Expected Behavior -
Driver returns matching element
## Actual Behavior -

`Exception `Errno::ECONNREFUSED' at /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879 - Connection refused - connect(2) for "127.0.0.1" port 4444
Exception `Errno::ECONNREFUSED' at /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:100 - Connection refused - connect(2) for "127.0.0.1" port 4444
/Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 4444 (Errno::ECONNREFUSED)
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /Users/petermckinney/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:640:in `execute'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/remote/w3c_bridge.rb:208:in `quit'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/firefox/w3c_bridge.rb:58:in `quit'
        from /Users/petermckinney/.rvm/gems/ruby-2.2.2/gems/selenium-webdriver-3.4.0/lib/selenium/webdriver/common/driver.rb:187:in `quit'
        from run.rb:46:in `<main>'
`

full log here: https://gist.github.com/pmck91/c7427cdb8cdd5ecee0ddbbcda091fc65

**Comment by AutomatedTester** [comment]
Looking at the log supplied it does find the element. see https://gist.github.com/pmck91/c7427cdb8cdd5ecee0ddbbcda091fc65#file-gistfile1-txt-L213

It also looks like you quit the session at https://gist.github.com/pmck91/c7427cdb8cdd5ecee0ddbbcda091fc65#file-gistfile1-txt-L230 and then the connection refused messages appear so this appears to be working as intended.

In future, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
