### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: ReferenceError: InvalidCookieDomainError is not defined

### ISSUE THREAD

**Issue by berdt** [SeleniumHQ/selenium#3928]
Selenium: 3.4.1
Gecko: 16.1
Firefox: 52

This happens when e.g. setting cookies before before having its page open. Previously this would end in a proper error message.

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. We will re-open the issue when this is completed.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
