### ISSUE TITLE
seleninum.base is set when the option is unset

### ISSUE THREAD

**Issue by loginprompt** [SeleniumHQ/selenium#393]
Unset Options > Options > General > Remember base URL
Click button OK
Record a test case
View the source
Expect: selenium.base is absent from the source code 
Actual: selenium.base is present and set

**Comment by loginprompt** [comment]
Seeing this in 2.8.0, and 2.9.0

**Comment by samitbadle** [comment]
There are a whole bunch of bugs around baseUrl. They need to be fixed together. Until that happens, as a workaround, you can remove the baseURL from the source.
