### ISSUE TITLE
Could you please update document to 3.4.0 ?

### ISSUE THREAD

**Issue by xiaoCong2014** [SeleniumHQ/selenium#3930]
OS:  
Windows 10
Selenium Version:  
3.4.0
Browser:  
Chrome 54

Could you update the official document to the latest version of Selenium (such as version 3.4.0, at least 3.x version)? The way of building local environment for Selenium 3.x is exactly the same as selenium 2? Are you sure ?

the older document whited at beginning -->  "Note to the Reader - Docs Being Revised for Selenium 2.0! " not Selenium 3.x
document link : http://www.seleniumhq.org/docs/

**Comment by p0deje** [comment]
Please, raise this issue to https://github.com/SeleniumHQ/www.seleniumhq.org.

**Comment by xiaoCong2014** [comment]
Thanks .
