### ISSUE TITLE
Message: Unrecognised timeout: page load

### ISSUE THREAD

**Issue by bkkkd** [SeleniumHQ/selenium#3931]
`
driver  = webdriver.Firefox()
driver.set_page_load_timeout(10) # get this: Message: Unrecognised timeout: page load

`
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L762

I have change the code 
"type":"pageLoad"})

It's work.I am not sure the type is"pageLoad" or "page load" which is right.

## Meta -
OS:  Ubuntu

Selenium Version:  3.0.2

Browser:  Firefox

Browser Version : 53.0

**Comment by lmtierney** [comment]
You will need to upgrade to selenium `3.3.2+` to use FF53. The correct format would be

    {'pageLoad': 10}

**Comment by bkkkd** [comment]
I saw  the code was page load, not pageLoad in version 3.4
