### ISSUE TITLE
[IE] keypress event with RETURN is incorrect

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/selenium#3934]
## Meta
OS:  Windows 7
Selenium Version:   3.4.0
Browser:  Internet Explorer 11.0.9600.18638
InternetExplorerDriver: 3.4.0.0 (64-bit)

## Steps to reproduce -

```
<html><head></head><body>
<input type='text' id='keyId'>
<script>
function handler(e) {
  e = e ? e : window.event;
  document.getElementById('myTextarea').value += e.type + ':' + e.keyCode + ',' + e.charCode + ',' + e.which + ',' + e.key + ',' + e.char + ',' + e.code + '\n';
}
document.getElementById('keyId').onkeyup = handler;
document.getElementById('keyId').onkeydown = handler;
document.getElementById('keyId').onkeypress = handler;
</script>
<textarea id='myTextarea' cols=80 rows=20></textarea>
</body></html>
```

        final WebDriver driver = new InternetExplorerDriver();

        try {
            driver.get("http://localhost/");
            final String keysToSend = "" + Keys.RETURN;
            driver.findElement(By.id("keyId")).sendKeys(keysToSend);

            String s = driver.findElement(By.id("myTextarea")).getAttribute("value");
            System.out.println(s);
        } finally {
            driver.quit();
        }

## Expected Behavior -
```
keydown:13,0,13,Enter,
,undefined
keypress:13,13,13,Enter,
,undefined
keyup:13,0,13,Enter,
,undefined

```

## Actual Behavior -

```
keydown:13,0,13,Enter,
,undefined
keypress:13,13,13,
,
,undefined
keyup:13,0,13,Enter,
,undefined

```

**Comment by jimevans** [comment]
Please retest with the `requireWindowFocus` capability set to `true`. If that produces the desired results, the browser isn't responding as expected to the Windows `SendMessage` API. If it doesn't work with that capability, then it's a browser bug, and there's nothing the driver can do about it.

**Comment by barancev** [comment]
I've retested with requireWindowFocus=true, the outcome is the same.
Closing as "a browser bug" according to @jimevans comment.
