### ISSUE TITLE
selenium firefox driver is not present in selenium server standalone 3.4.0

### ISSUE THREAD

**Issue by ChinmoyJana14** [SeleniumHQ/selenium#3935]
I have tried to use the below line of code after adding the the  selenium server standalone 3.4.0 to build path but it is showing me that "FirefoxDriver cannot be resolved to a type"

But while I add the jar "selenium-firefox-driver-2.53.1" , it is working fine

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
