### ISSUE TITLE
Can't get alert message on siebel openui

### ISSUE THREAD

**Issue by pataf** [SeleniumHQ/selenium#3937]
## Meta -
OS:  Windows 7
Selenium Version:  2.9.1, IDE
Browser:  Firefox
Browser Version:  
  38.4.0

## Expected Behavior -
"getAlet" returns javascript Error Message

## Actual Behavior -
"getAlert" method displayed "[error] There were no alerts" but in application log we see the jquery alert sent.
When i close selenium ide and click on button, the error is throw.

## Steps to reproduce -
![screenshot_8](https://cloud.githubusercontent.com/assets/28137499/25521553/58a62a8a-2c00-11e7-84f0-1c676476ef7b.png)

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
