### ISSUE TITLE
driver.Quit() not working when there is a Windows Authentication pop up is displayed in IE 11 browser on Windows 10

### ISSUE THREAD

**Issue by gokuludt** [SeleniumHQ/selenium#3938]
## Meta -
OS:  Windows10 
Selenium Version:  3.4.0
Browser:   Internet Explorer 11,
Browser Version:  IEDriver: Win32_3.4.0

## Expected Behavior -
Browser is need to be closed when calling driver.Quit() method when there is a Windows Authentication pop up is displayed.
## Actual Behavior -
Browser not getting closed upon calling driver.Quit() method when there is a Windows Authentication pop up is displayed
## Steps to reproduce -
In windows 7, Browser is closed when calling driver.Quit() method when there is a Windows Authentication pop up is displayed but its not working properly in Windows 10

**Comment by jimevans** [comment]
The driver cannot manipulate the new security dialog that was introduced in Windows 10. There is no timetable for when it will be able to do so.

**Comment by akshat62** [comment]
To automate this thing you have to come out of selenium and use another class to handle window dialog box. Selenium cannot handle prompts other than of browsers.

If you are using Java, Robot class will help you to close the security dialog box and then you can continue with selenium.

**Comment by evgeny1** [comment]
Robot won't work when tests are run on Grid and cloud testing services.

**Comment by diemol** [comment]
Closing as this is out of the scope of what WebDriver can do, and also because the thread went stale.
