### ISSUE TITLE
Cannot set logging options for Gecko via DesiredCapabilities and moz:firefoxOptions 

### ISSUE THREAD

**Issue by schmidtkp** [SeleniumHQ/selenium#3943]
## Meta -
OS:  OSX
Selenium Version:  3.4.0 (Java bindings)
Browser:  Firefox
Browser Version: 53.0
GeckoDriver Version: 0.16.1

## Expected Behavior -
Should be able to set logging for Gecko via DesiredCapabilities using key "moz:firefoxOptions" and a JsonObject value of "{log: {level: trace}}"
## Actual Behavior -
org.openqa.selenium.WebDriverException: Firefox option was set, but is not a FirefoxOption: {"log":{"level":"trace"}}
## Steps to reproduce -
JsonObject asJsonObject = new JsonParser().parse("{log: {level: trace}}").getAsJsonObject();
DesiredCapabilities desiredCapabilities = DesiredCapabilities.firefox();
desiredCapabilities.setCapability("moz:firefoxOptions", asJsonObject);
FirefoxDriver firefoxDriver = new FirefoxDriver(desiredCapabilities);

-- or --

RemoteWebDriver remoteWebDriver = new RemoteWebDriver(hubUrl, desiredCapabilities);

**Comment by kvalev** [comment]
I think the correct usage is:
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(Level.ALL);
capabilities.setCapability("moz:firefoxOptions", options);
```

However this did not work for me, geckodriver was still using the loglevel info. I had to extend the existing `GeckoDriverService.Builder` in order to pass the `--log` argument:
```
GeckoDriverService.Builder builder = new Builder2().usingPort(0);
        Optional<FirefoxBinary> binary = options.getBinaryOrNull();
        if (binary.isPresent()) {
            builder.usingFirefoxBinary(binary.get());
        }

        GeckoDriverService gecko = builder
                .withLogFile(new File("geckodriver.log"))
                .build();

        return new FirefoxDriver(gecko, capabilities);
```
```
private static final class Builder2 extends GeckoDriverService.Builder {
        @Override
        protected ImmutableList<String> createArgs() {
            ImmutableList.Builder<String> argsBuilder = ImmutableList.builder();
            argsBuilder.addAll(super.createArgs());
            argsBuilder.add("--log");
            argsBuilder.add("trace");

            return argsBuilder.build();
        }
    }
```

**Comment by schmidtkp** [comment]
@kvalev I don't believe using FirefoxOptions.setLogLevel() will set the GeckoDriver logs based on what I've read from @andreastt posts.

**Comment by kvalev** [comment]
Well the suggested way (described in #3002 and #3550) seems to be manually starting geckodriver with the desired configuration, but I was looking for a more automated solution and came up with the workaround above. The only downside is that the constructor is deprecated.

**Comment by lmtierney** [comment]
I will re-iterate and expand on what I wrote in #3550. Selenium is sending the correct capabilities to geckodriver and the logging is set correctly. You will always see the `INFO` about starting geckodriver unless you add an argument to the service itself since geckodriver needs to be running in order to set the logging level with capabilities. The verbose logging you are still seeing (e.g. the `debug` messages) is coming from Firefox itself. Selenium has no control over these. If you have a trace I could look at that suggests otherwise @kvalev I'd be glad to look at it.

**Comment by kvalev** [comment]
I am not sure whether the Java binding implementation behaves like it is supposed to, but I guess it would be nice, if geckodriver is started (via `GeckoDriverService`) with the same log level, as the one configured in the `FirefoxOptions`.

**Comment by schmidtkp** [comment]
@kvalev @lmtierney All I'm wanting to do is set the GeckoDriver log level to 'trace' to help provide debug info to @andreastt, per what is indicated in https://github.com/mozilla/geckodriver/blob/master/README.md can be done via WebDriver capabilities (see Capabilities examples section)

**Comment by lmtierney** [comment]
@schmidtkp I was moreso just commenting to @kvalev. All you need to do is this:

        FirefoxOptions opts = new FirefoxOptions().setLogLevel(Level.ALL);
        WebDriver driver = new FirefoxDriver(opts);

`Level.ALL` translates to `trace` for geckodriver. I have tried and confirmed this will work with 3.4 java bindings.

**Comment by schmidtkp** [comment]
@lmtierney Your example is not setting the FirefoxOptions in the DesiredCapabilities. It is passing them to the FirefoxDriver(FirefoxOptions) constructor instead of the FirefoxDriver(DesiredCapabilities) constructor or the RemoteWebDriver(URL, DesiredCapabilities) constructor. We should be able to do:
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(Level.ALL);
capabilities.setCapability("moz:firefoxOptions", options);
```
but as @kvalev and I noted, this does not work.

**Comment by lmtierney** [comment]
In my example it gets converted to DesiredCapabilities. https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L108

If you want to do it with RemoteWebDriver that's different, but since you said `or` I didn't realize you needed both. Did you try my example? Does it not work for you? It works for me

**Comment by lmtierney** [comment]
If you're looking to do something more like this

    FirefoxOptions options = new FirefoxOptions();
    options.setLogLevel(Level.ALL);
    capabilities.setCapability("moz:firefoxOptions", options);

Try this instead

    FirefoxOptions options = new FirefoxOptions();
    options.setLogLevel(Level.ALL);
    capabilities = options.addTo(capabilities);

Let the code set the `moz:firefoxOptions` key, that is the intended way

**Comment by schmidtkp** [comment]
@lmtierney When I set the capabilities as you describe, here is what I get (depicted as JSON):
```
"moz:firefoxOptions": {
    "binary": Optional.empty, 
    "args": [],
    "legacy": false,
    "logLevel": "ALL",
    "prefs": {},
    "profile": null
}
```
In comparison to what is documented/expected by [GeckoDriver](https://github.com/mozilla/geckodriver/blob/master/README.md) (specifically "log" object as JSON):
```
"moz:firefoxOptions": {
    "binary": "/usr/local/firefox/bin/firefox",
    "args": ["--no-remote"],
    "prefs": {
	"dom.ipc.processCount": 8
    },
    "log": {
	"level": "trace"
    }
}
```
I do not see the two entries being equivalent:
`"logLevel": "ALL" != "log": {"level": "trace"}`

I assume, if the log level is properly set, then GeckoDriver will log to STDOUT? Still not getting any additional information.

**Comment by schmidtkp** [comment]
@lmtierney First, apologies. I was chasing my tail *thinking* the GeckoDriver log level was never being handled in the DesiredCapabilities due to an upstream failure from setting the browser version in the DesiredCapabilities:

`org.openqa.selenium.WebDriverException: Unrecognized channel: 53.0`

This error is why I wanted to get the log level set in the first place. But this error surfaces before anything gets logged by GeckoDriver, hence my incorrect assumption that the log level was not working. Sorry about that.  If I remove setting the browser version, the error is not triggered and I do get GeckoDriver TRACE logs **_if-and-only-if_** I use FirefoxDriver.

However, I do think there might be some truth in what you said:
> If you are using this with RemoteWebDriver, the trace logging may be swallowed.

When I use RemoteWebDriver I at least see `geckodriver::marionette	INFO` but never any `geckodriver::marionette	TRACE`

**Comment by lmtierney** [comment]
Alright now I've got something to work with. Can you share the code you're using to create the webdriver?

**Comment by lmtierney** [comment]
Ah ok it seems you already created an issue for that, and I see some chatter in IRC about it, so I defer to #3941

**Comment by andreastt** [comment]
To be crystal clear about what geckodriver’s expectations are without jumping into the Java code, geckodriver expects the following input to enable trace-level logs:

    {"moz:firefoxOptions": {"log": {"level": "trace"}}}

The `moz:firefoxOptions` field should be a member of the appropriate requested capabilities object, meaning that for W3C WebDriver conforming new session negotiations, it should be member of the JSON Object assigned to `alwaysMatch`, or one of the JSON Objects entries to the `firstMatch` array.

Example of `alwaysMatch`:

    {"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"log": {"level": "trace"}}}}}

Example of `firstMatch`:

    {"capabilities": {"firstMatch": [{"moz:firefoxOptions": {"log": {"level": "trace"}}}]}}

Because Selenium appear to be using the non-conforming new session negotiation with desired- and required capabilities, we didn’t remove legacy support for this in geckodriver yet. This means geckodriver for the time being also supports the following input:

    {"desiredCapabilities": {"moz:firefoxOptions": {"log": {"level": "trace"}}}}

<hr>

Now, what separates W3C WebDriver new session negotiation from legacy Selenium WebDriver negotiation, and how can you tell?

When geckodriver receives a JSON Object to POST `/session` with a top-level `capabilities` key, such as `{"capabilities": …}`, it goes into WebDriver-conforming negotiation mode to look for `alwaysMatch`/`firstMatch`. If there is no top-level `capabilities` field, it looks for `desiredCapabilities`/`requiredCapabilities`.

**Comment by lmtierney** [comment]
@andreastt thank you for clarifying. Simon is currently working on conforming the w3c new session capabilities (for server/grid as well)

**Comment by andreastt** [comment]
@lmtierney You can find my email easily if you have any questions. I’m also known as _ato_ in the #webdriver IRC channel on irc.w3.org during London hours. Happy to help out or offer moral support for enduring the transition.

**Comment by allengay** [comment]
@lmtierney I believe I tried your solution:
			FirefoxDriverManager.getInstance().setup();
			this.ffProfile = profile.getProfile("AllenFFProfile");
			DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			FirefoxOptions options = new FirefoxOptions();
			options.setLogLevel(Level.WARNING);
			capabilities = options.addTo(capabilities);
			capabilities.setCapability(FirefoxDriver.PROFILE, ffProfile);
			this.driver = new FirefoxDriver(capabilities);
but I am still getting level "info"

**Comment by lmtierney** [comment]
Show your stack trace

**Comment by Moustakas42** [comment]
Also can't limit the Marionette log. Have tried:

```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(Level.OFF);
```
`options.addArguments("--log fatal");`
and even adding these to my profile file:
```
user_pref("marionette.log.level", "FATAL");
user_pref("marionette.logging", "FATAL");
```

I'm on FF 54, Selenium 3.4, Geckodriver 0.17, Java bindings.

**Comment by andreastt** [comment]
@Moustakas42 To be clear, you can only limit output from the `Marionette` logger in Firefox and `geckodriver`, and not `addons.manager` and others.

That `options.setLogLevel(Level.OFF)` does not work I suspect is a bug with the Selenium Java client, since `geckodriver --log warn` works fine.

**Comment by Moustakas42** [comment]
@andreastt so is there currently any way to limit the `Marionette` logger? None of the options I listed produced any effects.

**Comment by andreastt** [comment]
@Moustakas42 In geckodriver you can use `--log fatal` to only print fatal level and above. I don’t think there is an option to disable all logging, but using this will effectively achieve that effect.

**Comment by Moustakas42** [comment]
@andreastt how can I pass this in Java? `options.addArguments("--log fatal");` didn't yield any effect.

**Comment by andreastt** [comment]
@Moustakas42 `options.setLogLevel(Level.FATAL)` I imagine. The arguments will be propagated to _Firefox_, not geckodriver.

**Comment by Moustakas42** [comment]
@andreastt is that java.util.logging.Level? It goes up to SEVERE (no FATAL), and I still get:

```
1499757968209	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1499757969295	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1499757969298	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1499757969298	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
```

**Comment by Mark-Reiser** [comment]
@Moustakas42 and @andreastt

I experience the same problems and tried several ways to deactivate any debugging but without success.

Has anyone an idea to turn off all the "Marionette DEBUG Received DOM event" messages?

I use FF 55.0.3, Geckodriver 0.18.0, Selenium 3.5.3, JUnit 3.12

**Comment by andreastt** [comment]
@Moustakas42 @Mark-Reiser Those entries are at the moment unconditionally printed by Marionette irregardless of the log level. This is a known issue tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1384956.

cc @whimboo
