### ISSUE TITLE
Selenium Grid 3.4.0 and IE 11. Has a huge delay after driver.findElement(...).click() method

### ISSUE THREAD

**Issue by aelzhanova** [SeleniumHQ/selenium#3944]
## Meta -
OS:  Windows 10; JDK 1.8.0_121; WindowsServer 2012 R2 Datacenter

Selenium Version:  3.4.0; SeleniumGrid 3.4.0

Browser:  IE 11

Browser Version:  IE 11.0.9600.18639 (Update versions:11.0.41 ) x64

## Expected Behavior -
After click() method not any delay
## Actual Behavior -
I find element and then click him. After that I see huge delay before test will go to the next step.
## Steps to reproduce -

I find element and then click him. After that I see huge delay before test will go to the next step. I working with SeleniumGrid and remoteWebDriver. It's blocking all my tests, before last week it works fine. It will be great if you can fix it

Example of my code:
    public VoiceCall clickCallSupport() {
        getCallSupportButton().click();
        WaitElement.waitWebElement(driver, ExpectedConditions.elementToBeClickable(cancelCallBtn), 15);
        return CallPage(driver);
    }

1.After getCallSupportButton().click(); huge delay and then test go to the next step

**Comment by aelzhanova** [comment]
Is it relate with https://github.com/SeleniumHQ/selenium/issues/3861 ?

**Comment by p0deje** [comment]
It's very likely that your pages just started to load slower so now you see this delay.

In any event, provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
