### ISSUE TITLE
Why does  driver.get('www.youtube.com') result in a malformed error? 

### ISSUE THREAD

**Issue by Moondra** [SeleniumHQ/selenium#3947]
from selenium import webdriver

    driver = webdriver.Firefox()
    driver.get('www.youtube.com')
    driver.save_screenshot('youtube.png')
    driver.quit()

Is resulting in `WebDriverException: Message: Malformed URL: www.youtube.com is not a valid URL.`
If I type the same URL in Firefox, I have no problems.

I'm using Windows 7, Firefox (53.0), Python 3.6 with Jupyter notebook (latest version) and latest Selenium.

Thank you.

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
Selenium expects the entire URL including the protocol. So add an `http://` or `https://` in front of the URL

Please send future questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
