### ISSUE TITLE
Drag and drop test in IDE sequence re-order tests

### ISSUE THREAD

**Issue by Filipovic93** [SeleniumHQ/selenium#3949]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.9.1
Browser:  
Firefox
## Expected Behavior -
Im trying to drag and drop the sequence in my test suite, as I need to do some tests in the top of the running tests.
## Actual Behavior -
Not possible to drag and drop, or reorder sequence.
![billede](https://cloud.githubusercontent.com/assets/5764040/25574421/8c6370b2-2e4e-11e7-9123-4b1322919573.png)

**Comment by lmtierney** [comment]
Duplicate of #3139
