### ISSUE TITLE
Changing names of test methods at runtime?

### ISSUE THREAD

**Issue by Udit2** [SeleniumHQ/selenium#3953]
Hi,

Is there a way to change the test method names of test cases not just test case name .I know that the test case name can be changed by implementing ITEST iterfac and implementing its method but thats not what I am looking.I looking to change the name of methods so that I can show my test reports with my custom name?

Please provide inputs ASAP.

Best Regards

**Comment by jimevans** [comment]
This is not a Selenium issue, but rather a question for your test runner library (JUnit, TestNG, etc.). You would do better asking the question in a forum dedicated to that project.
