### ISSUE TITLE
Can not click on a flash button with window wmode

### ISSUE THREAD

**Issue by slonghorn** [SeleniumHQ/selenium#3954]
OS:  
Windows 7 (64 bit)
Selenium Version:  
3.4.0 and others(Java)
Browser:  
Internet Explorer 8+(32 bit)

Using flash to upload file(SWFUpload), when setting the wmode property of flash to window, click the flash button with the IEDriverServer_32_bit_3.4.0, it can't open the file chooser dialog. But when setting the wmode to transparent, it works.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
