### ISSUE TITLE
0x80520015 when trying to save a screenshot in Selenium IDE

### ISSUE THREAD

**Issue by PhilDykes** [SeleniumHQ/selenium#3956]
OS:  
Windows 10
Selenium Version:  
IDE2.9.1
Browser:  
 Firefox 53.0 (32-bit)

## Expected Behavior -
Save screen shot to specified folder

## Actual Behavior -

Error message received

[error] Unexpected Exception: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFileOutputStream.init]" nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)" location: "JS frame :: chrome://selenium-ide/content/selenium-core/scripts/selenium-api.js :: newFileOutputStream :: line 3112" data: no]. toString -> function toString() { [native code] }, message -> Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFileOutputStream.init], result -> 2152857621, name -> NS_ERROR_FILE_ACCESS_DENIED, filename -> chrome://selenium-ide/content/selenium-core/scripts/selenium-api.js, lineNumber -> 3112, columnNumber -> 0, data -> null, stack -> newFileOutputStream@chrome://selenium-ide/content/selenium-core/scripts/selenium-api.js:3112:13 Selenium.prototype.doCaptureEntirePageScreenshot@chrome://selenium-ide/content/selenium-core/scripts/selenium-api.js:3197:28 retval@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:60:12 ActionHandler.prototype.execute@chrome://selenium-ide/content/selenium-core/scripts/selenium-commandhandlers.js:314:28 _executeCurrentCommand@chrome://selenium-ide/content/selenium-runner.js:306:19 resume@chrome://selenium-ide/content/selenium-core/scripts/selenium-executionloop.js:78:13 retval@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:60:12 , location -> JS frame :: chrome://selenium-ide/content/selenium-core/scripts/selenium-api.js :: newFileOutputStream :: line 3112

## Steps to reproduce -
Run the following ensuring a suitable save folder exists
<tr>
	<td>captureEntirePageScreenshot</td>
	<td>C:\Users\*******\Selenium Regression Test Results\Access</td>
	<td></td>
</tr>

IT looks like a permissions issue but I can't figure out how to give the required permissions. Using Windows 10.

Any help woul;d be appreciated.

Thanks

Phil

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
