### ISSUE TITLE
key value of key event fired from Protractor test case shows value as Unidentified

### ISSUE THREAD

**Issue by pankajthakur950** [SeleniumHQ/selenium#3959]
I am trying to test the Enter key press event through protractor test framework. Protractor is responding to Enter event but the event object which is send to handler function contains key value as 'Unidentified'.
Handler function checks the key value of event object to check the key presses & perform some operation. Although keyCode value of event object is correct but key value is not correct.
Is there any workaround for this issue. 

Browser Version : 45.7.0

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
