### ISSUE TITLE
confirmation handling Selenium IDE an duplicate record

### ISSUE THREAD

**Issue by Heizer1971** [SeleniumHQ/selenium#396]
notice: this bug was also reported in: 
https://code.google.com/p/selenium/issues/detail?id=7996

hello,
I have some problems with the treatment of confirmations.
If I use the IDE in record mode, it records not correct on this and popup will suppressed.
This problem exists since version 2.6.0.
In addition, some tests break with the message: "[error] There were no confirmations" if i use the command "storeConfirmation", but they are definitely there.

I have uploaded 2 photos .
The first shows my software with the IDE 2.4.0 and the correct lap recording.
The other at the same point with version 2.8.0 with duplicate records from the click command, but no confirmation.

![confirmation_2](https://cloud.githubusercontent.com/assets/11455286/6940097/9cafd2b8-d873-11e4-8ef8-be9af44ea74b.png)
![confimation_1](https://cloud.githubusercontent.com/assets/11455286/6940095/9978b2cc-d873-11e4-8d31-413a7d72343a.png)
the duplicte records was also reported from me in: https://code.google.com/p/selenium/issues/detail?id=8611
Sorry for this, but i don´t know what the right way is since the migration to GitHub.

Selenium version:2.5.0/2.6.0/2.8.0
OS:Windows 8.1 and Vista
Browser:Firefox 
Browser version:36.0.4

**Comment by samitbadle** [comment]
Are both the screen shots from the same version of Firefox?

**Comment by Heizer1971** [comment]
Sorry Samit, this is an old bug and old picture from this.
1.no not the same versions of firefox, but the problem is still relevant in firefox 36.0.4
2.I forgot the link to recreate the problem....es simple test.... 
http://heizershome.de/click.html

**Comment by Heizer1971** [comment]
brand new picture with firefox 36.0.4
I test an cloud-based-software with many confimations an the IDE said very often, that there are no confirmations, but they are definitely there. (in playback-mode)
in record-mode the IDE record then this 2 commands.
![bild_1](https://cloud.githubusercontent.com/assets/11455286/7028465/4479422c-dd56-11e4-8ba8-20edf30c2fa6.png)

**Comment by Heizer1971** [comment]
Important update:
I use the IDE only in sidebar -mode .... these two problems (double record a command and the treatment of confirmations) exist only in in this mode.
I just use it and need it, for several sessions and browsers. Samit: if you would like access to our software and a custom script, to understand the bug with the confirmation, please send me a mail.

**Comment by samitbadle** [comment]
Thank you for your test link. I have been able to reproduce this in sidebar mode, but the recording works as expected in the separate window mode. It could be a Firefox issue. Can you help by finding out which version of Firefox this issue started on? This means installing different versions of Firefox and trying your test with Selenium IDE 2.9.0 / 2.9.1 until you find one that works. I would suggest using portable Firefox to ease multiple Firefox installations under Windows.

**Comment by Heizer1971** [comment]
Hi Samit, thank you 4 feedback.
I tested a little bit with different firefox and selenium versions and here the first result: 
My Bug report actually contains 2 problems. I know that this is unprofessional, but I'll try to help you.
First problem: double records.
The first occurrence is exactly the Selenium version 2.60
2.50 works with all Firefox-versions, no double records.
![bild_2](https://cloud.githubusercontent.com/assets/11455286/7112866/6c8c2a0a-e1ce-11e4-9cd0-2be2fb8cc2f8.png)
![4png](https://cloud.githubusercontent.com/assets/11455286/7112867/6c91f908-e1ce-11e4-830c-0d764dc7dc52.png)

**Comment by samitbadle** [comment]
Thanks. I have managed to track down the command duplication. I will close this issue with the commit. Please open another bug for the remaining ones after you have tested a new release with this fix.

**Comment by sheel2006** [comment]
Hi Samit,
I am using FE 38.0.5 and IDE version 2.9.0 , getting error message.
Please refer diagnostic information , your help will be appreciated.
{
  "startTime": 1433604886305,
  "at": 1433606141434,
  "diags": {
    "PluginManager": {
      "pluginsData": [
        {
          "id": "rubyformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "rspecwdformatters;Ruby / RSpec / WebDriver;chrome://ruby-formatters/content/formats/ruby-wd-rspec.js;webdriver",
              "rubywdformatters;Ruby / Test::Unit / WebDriver;chrome://ruby-formatters/content/formats/ruby-wd.js;webdriver",
              "rspecformatters;Ruby / RSpec / Remote Control;chrome://ruby-formatters/content/formats/ruby-rc-rspec.js;undefined",
              "rubyformatter;Ruby / Test::Unit / Remote Control;chrome://ruby-formatters/content/formats/ruby-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "pythonformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "pythonwdformatter;Python 2 / unittest / WebDriver;chrome://python-formatters/content/formats/python2-wd.js;webdriver",
              "pythonformatters;Python 2 / unittest / Remote Control;chrome://python-formatters/content/formats/python2-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "javaformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "webdriverjunit4formatter;Java / JUnit 4 / WebDriver;chrome://java-formatters/content/formats/webdriver-junit4.js;webdriver",
              "backedjunit4formatter;Java / JUnit 4 / WebDriver Backed;chrome://java-formatters/content/formats/java-backed-junit4.js;undefined",
              "junit4formatter;Java / JUnit 4 / Remote Control;chrome://java-formatters/content/formats/java-rc-junit4.js;undefined",
              "junit3formatter;Java / JUnit 3 / Remote Control;chrome://java-formatters/content/formats/java-rc.js;undefined",
              "testngformatter;Java / TestNG / Remote Control;chrome://java-formatters/content/formats/java-rc-testng.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "csharpformatters@seleniumhq.org",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "csharpwdformatter;C# / NUnit / WebDriver;chrome://csharp-formatters/content/formats/cs-wd.js;webdriver",
              "csharpformatter;C# / NUnit / Remote Control;chrome://csharp-formatters/content/formats/cs-rc.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        }
      ],
      "errors": []
    },
    "Browser": {
      "os": "WINNT",
      "name": "Firefox",
      "version": "38.0.5",
      "ID": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
      "vendor": "Mozilla",
      "platformBuildID": "20150525141253",
      "platformVersion": "38.0.5",
      "userAgent": "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
    },
    "SeleniumIDE": {
      "version": "2.9.0",
      "sidebar": false
    }
  },
  "events": [
    {
      "at": 1433604886305,
      "type": "Event",
      "component": "HealthService",
      "event": "attached: editor"
    },
    {
      "at": 1433604886305,
      "type": "Event",
      "component": "editor",
      "event": "initializing"
    },
    {
      "at": 1433604886307,
      "type": "Event",
      "component": "editor",
      "event": "optionsChanged"
    },
    {
      "at": 1433604886337,
      "type": "Event",
      "component": "editor",
      "event": "initialized"
    },
    {
      "at": 1433604937208,
      "type": "Error",
      "component": "editor",
      "event": "UncaughtException",
      "msg": "TypeError: window is null",
      "url": "chrome://selenium-ide/content/selenium-runner.js",
      "line": 390,
      "column": 6,
      "stack": "createSelenium@chrome://selenium-ide/content/selenium-runner.js:390:7\nstart@chrome://selenium-ide/content/selenium-runner.js:405:16\nDebugger.prototype.start@chrome://selenium-ide/content/debugger.js:154:1\nEditor.prototype.playCurrentTestCase@chrome://selenium-ide/content/editor.js:925:1\nEditor.controller.doCommand@chrome://selenium-ide/content/editor.js:387:9\ngoDoCommand@chrome://global/content/globalOverlay.js:96:7\noncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1\n"
    }
  ],
  "metrics": {},
  "stats": {
    "editor": {
      "playCurrentTestCase": 1
    }
  }
}

**Comment by Prakalp-Jadhav** [comment]
Hi Samit, 
             I have added plug-in Selenium IDE - SelBlocks 2.1. Now when I double-click on any of my single selenium command, it throws me an error like this - 
pls refer sc below
![default](https://cloud.githubusercontent.com/assets/12185474/14609166/3b0786a8-05a6-11e6-8018-987576267565.png)

**Comment by KituRanu** [comment]
now i installed IDE 2.9.1 .when i run this it was showing always one error i cant recognize why this error always came. i also installed different different Firefox version but it was no changing any thing .plz help me.
![untitled](https://cloud.githubusercontent.com/assets/19345294/15247144/d2aa2ac8-192f-11e6-8e4e-18183a2e2eff.png)

**Comment by Heizer1971** [comment]
report a new issue
https://github.com/SeleniumHQ/selenium/issues/2321
bug not fixed or not released
