### ISSUE TITLE
IE web driver is not able to find/use window that is opened via active x control

### ISSUE THREAD

**Issue by nitimagulati** [SeleniumHQ/selenium#3960]
## Meta -
OS:  
 Windows 7, 64 bit
Selenium Version:  
 
selenium-webdriver (3.4.0)
webdriver-user-agent (7.3)
IE web driver version: 3.4.0.0 64 bit
Browser:  
Internet Explorer 11, Internet Explorer 10
Browser Version:  11.0.9600.16428IS  (64-bit) 

## Expected Behavior -
IE web driver should be able to find/use window that is opened via active x control
## Actual Behavior -
IE web driver is not able to find/use window that is opened via active x control
## Steps to reproduce -
Following link opens up a pop under window through Active x control, once it finish loading.
IE web driver is not able to use that window.
2 windows are there one parent and another which is opened as a pop up but browser.windows.size still shows 1.
Following is the link which opens up pop up window at page load.
https://www.priceline.com/stay/search/hotels/3000008602/20170905/20170907/1/?searchType=CITY

**Comment by jimevans** [comment]
Once you go outside normal browser mechanisms for opening windows (and ActiveX qualifies, as I'm defining the terms), IE exposes no programmatic way for the driver to detect that a new window is opening. There is no feasible way to fix this bug, so I'm closing this issue.
