### ISSUE TITLE
Execution of TestCase on Safari Using selenium3.3

### ISSUE THREAD

**Issue by jimmyjavid** [SeleniumHQ/selenium#3964]
Hi,
 I tried running testcase  on safari 5.1.7 but to my surprise I have found that the test case could not be executed.  So my concern here is to know whether Selenium 3.3 has stopped supporting safari?

**Comment by p0deje** [comment]
Old SafariDriver is not used anymore so you need to use [official SafarDriver by Apple](https://webkit.org/blog/6900/webdriver-support-in-safari-10/).

**Comment by jimmyjavid** [comment]
But my execution was on windows.  I need to run my test case on windows using Safari.
 So Is it  like It can't be done on windows using safari..

**Comment by p0deje** [comment]
Safari for Windows was abandoned by Apple several years ago and Selenium doesn't support it. Maybe some old Selenium versions did that, I don't know.

**Comment by jimmyjavid** [comment]
Sir P0deje,
 Earlier i used to use selenium 2.53 and it worked well till date.
 But as I shifted to selenium 3.3 safari could not be launched . In Other words Test cases could not be executed on safari using selenium 3.3 on windows.

**Comment by p0deje** [comment]
Yeah, I think since Selenium 3 we no longer support old Safar driver implementation. Instead, people should now use official SafariDriver by Apple.

**Comment by jimmyjavid** [comment]
so by using official safariDriver  can we be able to execute safari on **# windows**.

**Comment by p0deje** [comment]
No, Apple doesn't support Safari for Windows for about 5 years already and SafariDriver only works with latest Safari 10.

**Comment by jimmyjavid** [comment]
Sir P0deje,
 We have already automated our scripts on windows in safari v5.1.7 using selenium 2.53.
 As we upgrade on selenium3.3  those scripts cannot be executed.

  So where problem actually is? Is it with selenium3.3 or with safari's support to selenium.

**Comment by p0deje** [comment]
Selenium 3.3 doesn't support Safari 5.1.7.

**Comment by luke-hill** [comment]
Safari 5.1.7 is about an old a browser as is humanly possible. It doesn't support the latest CSS (Or even the version before), there is the IE8 stylesheet size limit and I would estimate the browser usage of this to be less than 0.0001%.

As of 2016, Safari V6 and V5 stats were no longer available because they went below the 0.05% threshold across the world.
