### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by elarouche** [SeleniumHQ/selenium#3967]
## Meta
OS: macOS Sierra Version 10.12.4
Selenium Version:  
3.4.0

## Steps to reproduce
`$ npm install selenium-server@3.4.0`

`$ ./node_modules/.bin/selenium`

Then receive following error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/ ....... /node_modules/selenium-server/lib/runner/../../logs/selenium.out'
```

I go ahead and make a `/logs` directory
`$ mkdir ./node_modules/selenium-server/logs/`

Then
`$ ./node_modules/.bin/selenium`

Run perfectly fine with the expected behaviour:
```
Selenium is started.
All output can be found at: /Users/ ....... /node_modules/selenium-server/lib/runner/../../logs
```
And creates the 2 files in the new directory (selenium.out & selenium.err)

I tested different versions and it starts giving that error at v3.1.0.
v3.0.1 works fine and creates the logs directory on npm install

**Comment by aneeshchandy** [comment]
The above node package is not part of "Selenium HQ/selenium". Please report the issue to the original author of that package.

https://github.com/eugeneware/selenium-server

**Comment by lmtierney** [comment]
See @aneeshchandy's (thanks) response
