### ISSUE TITLE
Class org.openqa.selenium.interactions.touch.TouchActions doesn't return web driver

### ISSUE THREAD

**Issue by unlimUA** [SeleniumHQ/selenium#3969]
`  public TouchActions(WebDriver driver) {
    this(((HasInputDevices) driver).getKeyboard(),
         ((HasTouchScreen) driver).getTouch());
  }`

`  @Deprecated
  public Actions(Keyboard keyboard) {
    this.driver = null;
    this.jsonKeyboard = keyboard;
    this.jsonMouse = null;
  }`

I have got error 
`java.lang.NullPointerException
    at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:631)
    at org.openqa.selenium.interactions.Actions.perform(Actions.java:593)
    at `, 
because TouchAction receive me driver=null
use selenium 3.4.0

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by unlimUA** [comment]
Method 
 ` public static void openNotificationPanel(SelenideElement statusBar){
        new TouchActions(driver)
                .flick(statusBar,0,+600,500)
                .perform();
    }`
test failed at `.perform`

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment]
Closing the issue, there is no reporoduction scenario provided.
