### ISSUE TITLE
Support for headless chrome

### ISSUE THREAD

**Issue by skateman** [SeleniumHQ/selenium#3971]
Hi!

Since version 58, Chrome can run in [headless mode](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md). I wanted to try it out with the following code:
```ruby
Selenium::WebDriver.for :chrome, switches: %w[--disable-gpu --headless]
```
This resulted with `Selenium::WebDriver::Error::UnknownError: unknown error: unrecognized Chrome version: HeadlessChrome/58.0.3029.96` so I tried:
```ruby
Selenium::WebDriver.for :chrome, switches: %w[--disable-gpu --headless --remote-debugging-port=9222], port: 9222
```
But the result was `Net::ReadTimeout: Net::ReadTimeout`.

**Comment by jdmesalosada** [comment]
Hi, I'm having a similar issue:¿. I'm unable to start the browser in a headless mode.

https://github.com/SeleniumHQ/selenium/issues/3970

this is with C#.

**Comment by lmtierney** [comment]
This is working fine for me with on Linux with Chrome 58, Chromedriver 29, selenium-webdriver 3.4

Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sanjaychaudhari1821** [comment]
This is working fine for me on Mac with Chrome canary, selenium-webdriver 3.4
changes in config file...
====>
var readline = require('readline')
var hasTriggered = false

exports.config = {

    specs: [
        // './test/desktop/specs/**/*.js'
    ],

    capabilities: [{
        browserName: 'chrome',
        chromeOptions: {
            // run in headless mode
            args: ['--headless'],
            // point to your Canary version as it is only supported there
            binary: '/Applications/Google Chrome Canary.app/Contents/MacOS/Canary'
        }
    }],
    framework: 'mocha',
    mochaOpts: {
        timeout: 10000
    }
}

**Comment by Windso** [comment]
I'm using Chromium headless with Chimp and am having a similar issue. I believe it has to do with Chromedriver. Chromedriver 2.33 works fine, but Chromedriver 2.9 gives me this error
```
[chimp][helper] setupBrowserAndDDP had error
{ Error: unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3238.0
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:196:31)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:275:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:22:24
    at node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:124:39
    (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.6 x86_64)
  message: 'unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3238.0\n  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.6 x86_64)',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3238.0\n  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.6 x86_64)' } }
Error: unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3238.0
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:196:31)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:275:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:22:24
    at node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:124:39
    (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.6 x86_64)

```

**Comment by lmtierney** [comment]
@Windso `2.9` is extremely old. `2.33` is the latest

**Comment by Windso** [comment]
@lmtierney My bad. I was looking at [this list of chromedrivers](https://npm.taobao.org/mirrors/chromedriver) and was under the impression that `2.9` was newer than `2.33`.
