### ISSUE TITLE
Missing class com.thoughtworks.selenium.webdriven.WebDriverBackedSelenium

### ISSUE THREAD

**Issue by nsankaranarayanan** [SeleniumHQ/selenium#3974]
## Meta -
OS:  

Selenium Version:  

Browser:  

I am currently using NetBeans and here is my sample code. The IDE is complaining that it can't find WebDriverBackedSelenium. I tried to find that class in the selenium standalone-server, server, java, etc and can't locate it.

Below is the sample code.

		String base_url = "http://localhost:8084";     
		Proxy proxy = new Proxy();     
		proxy.setProxyAutoconfigUrl(base_url);
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability(CapabilityType.PROXY, proxy);
		RemoteWebDriver driver = new RemoteWebDriver(capabilities);
		Selenium selenium = new WebDriverBackedSelenium(driver, base_url);

Thanks

**Comment by barancev** [comment]
We deploy a library that supports legacy (RC) implementation to maven central:
http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-leg-rc%7C3.4.0%7CN%2FA

**Comment by Steigwachs** [comment]
According to https://github.com/SeleniumHQ/selenium/wiki/Grid2 the code mentioned by nsankaranarayanan is not legacy but current. So why are current selenium-server-standalone jar files missing com.thoughtworks.* classes?
How can the code above reworked so that it runs with version 3.4?
Thanks.

**Comment by barancev** [comment]
selenium-server-standalone jar file is the server.
WebDriverBackedSelenium is a class that belongs to the client side, that's the reason it's not included to the server jar.
All RC code is deprecated for many years, you should not use it to develope new tests. Use WebDriver API.
