### ISSUE TITLE
ActionSequence seems to fail if control flow is off

### ISSUE THREAD

**Issue by juliemr** [SeleniumHQ/selenium#3975]
For the selenium-webdriver JavaScript bindings:

Creating an ActionSequence with multiple actions does not correctly perform the actions in order i the control flow is turned off. For example:

```js
webdriver.actions()
    .mouseMove(foo)
    .mouseUp()
    .mouseDown()
    .perform()
```

will occasionally perform the actions out of order.

I think this is due to `ActionSequence.perform()` relying on `Promise.all()` to manage its queue of `actions_`, instead of explicitly chaining them. 

See https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/actions.js#L123

**Comment by jleyba** [comment]
The ActionSequence class has been completely overhauled to support W3C actions. Details in #4564
