### ISSUE TITLE
Invalid GET /shutdown geckodriver  endpoint

### ISSUE THREAD

**Issue by zosrothko** [SeleniumHQ/selenium#3978]
## Meta -
OS:  Win7 Pro SP1

Selenium Version:  3.4.0

Browser:  Firefox

Browser Version:  53.0 (32 bits)

## Steps to reproduce -

The driver.quit() command generates an invalid geckodriver endpoint 
```
1493978605978	webdriver::server	DEBUG	â GET /shutdown 
1493978605980	webdriver::server	DEBUG	â 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x43a15d - <no info>\n   3:           0x42ec0f - <no info>\n   4:           0x423c30 - <no info>\n   5:           0x4078fa - <no info>\n   6:           0x6bc939 - <no info>\n   7:           0x415d0d - <no info>\n   8:           0x6b6e43 - <no info>\n   9:         0x775a59cd - BaseThreadInitThunk"}}
```
See the debugging log joined.

[Invalid-GET-shutdown.txt](https://github.com/SeleniumHQ/selenium/files/978680/Invalid-GET-shutdown.txt)

[Selenium2Example.java.txt](https://github.com/SeleniumHQ/selenium/files/978697/Selenium2Example.java.txt)

**Comment by lmtierney** [comment]
AFIAK geckodriver doesn't support the `/shutdown` endpoint, may just need to rip that out of java. Are you running through standalone/grid?

**Comment by zosrothko** [comment]
Sorry but I do not understand your question "Are you running through standalone/grid?" . Selenium2Example.java is a standalone java application.

**Comment by lmtierney** [comment]
K, didn't see the attached file

**Comment by shs96c** [comment]
The `/shutdown` end point is specific to Selenium, and isn't part of the [W3C WebDriver specification,](https://www.w3.org/TR/webdriver/) which geckodriver adheres to.

Reading the code, you should see a single call to endpoint, and then the driver should close as expected.

**Comment by shs96c** [comment]
As such, what you're seeing is expected selenium behaviour, even if the logs are a little noisy.
