### ISSUE TITLE
IEDriver constantly crashing on startup (Win7 IE8  64bit) with Selenium 2.45

### ISSUE THREAD

**Issue by pcomerton** [SeleniumHQ/selenium#398]
Every time I try to launch IEDriver it crashes with following error in log file:

W 2015-04-01 14:21:54:994 BrowserFactory.cpp(269) -2147467259 [Unspecified error]: Unable to convert document object pointer to IHTMLDocument2 object via ObjectFromLresult

Am launching IEDriver as shown below

InternetExplorerDriverService ieservice = InternetExplorerDriverService.CreateDefaultService(@"C:\Program Files\IEDriverServer");
                   
 ieservice.LoggingLevel = InternetExplorerDriverLogLevel.Trace;
 ieservice.LogFile = "C:\\TEMP\\iedriverserver.log";

 InternetExplorerOptions options = new InternetExplorerOptions();
                    
options.IgnoreZoomLevel = true;
options.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
options.ElementScrollBehavior = 
options.IgnoreZoomLevel = true;
                    
driver = new InternetExplorerDriver(ieservice, options, TimeSpan.FromMinutes(5));

Selenium version: 2.45.0
OS: Windows 7
Browser: IE7

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by pcomerton** [comment]
Steps to reproduce as follows:

1) Launch IEDRiver server with following code

using System;
using NUnit.Framework;
using System.Windows.Forms;
using OpenQA.Selenium.IE;
using Selenium;
using OpenQA.Selenium;

namespace Performance
{
    // This class stores all our test settings (as configured in Setup.xls).
    public class TestConfiguration : CommonTasks
    {
        public IWebDriver driver;                       // Browser driver

        public void GetBrowserDriver(string tWebDriver)
        {
            InternetExplorerDriverService ieservice = InternetExplorerDriverService.CreateDefaultService(@"C:\Program Files\IEDriverServer");
                   
            ieservice.LoggingLevel = InternetExplorerDriverLogLevel.Trace;
                    
            ieservice.LogFile = "C:\\TEMP\\iedriverserver.log";

            InternetExplorerOptions options = new InternetExplorerOptions();
                    
            options.IgnoreZoomLevel = true;

            options.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
                    
            options.ElementScrollBehavior = OpenQA.Selenium.IE.InternetExplorerElementScrollBehavior.Bottom;
                    
            options.IgnoreZoomLevel = true;
                    
            driver = new InternetExplorerDriver(ieservice, options, TimeSpan.FromMinutes(5));

            // Maximise browser window
            driver.Manage().Window.Maximize();

            }
        }
}

Expected Result: Selenium will lauch IEDriver which will in turn launch IE 8

Actual Result: IEDriver crashes without launchinh IE8 - message in log file as follows:

W 2015-04-01 14:21:54:994 BrowserFactory.cpp(269) -2147467259 [Unspecified error]: Unable to convert document object pointer to IHTMLDocument2 object via ObjectFromLresult

Selenium version: 2.45.0
OS: Windows 7
Browser: IE7

**Comment by barancev** [comment]
1) We don't accept reports about issues with IntroduceInstabilityByIgnoringProtectedModeSettings == true, if you agreed to introduce instability -- it's your choice :)

2) You did not provide enough information about the target page where the driver crashes and the operations that causes the exception.

**Comment by pcomerton** [comment]
Ji - thansk for reply - on 

1) thats fine on thanks. I'll retry with IntroduceInstabilityByIgnoringProtectedModeSettings == false

2) I'm not actually navigating to any page it crashes as soon as the webbrowser is launched. I don't actually do anything (or perform any operation) as can't get it to work yet. 

Do I need any more info before I do this and relog the ticket.

Thanks,

**Comment by ddavison** [comment]
you should log an issue here @pcomerton when you have thoroughly identified this as a "bug" in selenium.  as barancev said, go to the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) or write up a question in [stackoverflow](http://stackoverflow.com).  

These issues are used for tracking legitimate defects from Selenium.  not tracking help requests.

**Comment by pcomerton** [comment]
It's not a help request - I was asking what other info I need to include when I resubmit the ticket.

**Comment by ddavison** [comment]
well, i have a feeling that it has to do with yhour IEDriver version, and IE version.  you are using IE7.   that's quite old.

**Comment by pcomerton** [comment]
Sorry that ws a tyopo - I'm using IE8. I've tried with Selenium 2.45 and also Selenium 2.39 but the problem still occurs - maybe I need to go for an earlier driver.

**Comment by barancev** [comment]
Attach the iedriverserver.log generated by the service, and as @ddavison requested, specify the version of IEDriverServer, it is much more important than the version of Selenium .Net library.

**Comment by pcomerton** [comment]
Ok thanks guys. Attched is the log file (hopefully) the verison of IEDriverServer is IEDriverServer_x64_2.45.0

**Comment by ddavison** [comment]
and, are you sure the target platform is a 64 bit architecture?  also, we don't see the log. Just paste it as a comment, or [gist it](https://gist.github.com)

**Comment by pcomerton** [comment]
having trouble attaching log file - full text here

I 2015-04-01 15:56:25:374 server.cc(53) Starting WebDriver server on port: '49810' on host: ''
T 2015-04-01 15:56:25:374 server.cc(624) Entering Server::PopulateCommandRepository
T 2015-04-01 15:56:25:375 IEServer.cpp(25) Entering IEServer::IEServer
T 2015-04-01 15:56:25:375 server.cc(83) Entering Server::Start
D 2015-04-01 15:56:25:375 server.cc(104) Mongoose ACL is -0.0.0.0/0,+127.0.0.1
T 2015-04-01 15:56:25:986 server.cc(62) Entering Server::OnHttpEvent
T 2015-04-01 15:56:25:986 server.cc(128) Entering Server::ProcessRequest
T 2015-04-01 15:56:25:986 server.cc(137) Process request with: URI: /status HTTP verb: GET
body: {}
T 2015-04-01 15:56:25:986 server.cc(230) Entering Server::DispatchCommand
T 2015-04-01 15:56:25:986 server.cc(530) Entering Server::LookupCommand
D 2015-04-01 15:56:25:987 server.cc(239) Command: GET /status {}
T 2015-04-01 15:56:25:987 IEServer.cpp(43) Entering IEServer::GetStatus
T 2015-04-01 15:56:25:987 response.cc(55) Entering Response::SetSuccessResponse
T 2015-04-01 15:56:25:987 response.cc(61) Entering Response::SetResponse
T 2015-04-01 15:56:25:987 response.cc(43) Entering Response::Serialize
D 2015-04-01 15:56:25:987 server.cc(308) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.39.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

T 2015-04-01 15:56:25:987 server.cc(359) Entering Server::SendResponseToClient
T 2015-04-01 15:56:25:987 response.cc(32) Entering Response::Deserialize
T 2015-04-01 15:56:25:987 server.cc(413) Entering Server::SendHttpOk
T 2015-04-01 15:56:26:404 server.cc(62) Entering Server::OnHttpEvent
T 2015-04-01 15:56:26:404 server.cc(128) Entering Server::ProcessRequest
T 2015-04-01 15:56:26:404 server.cc(196) Entering Server::ReadRequestBody
T 2015-04-01 15:56:26:408 server.cc(137) Process request with: URI: /session HTTP verb: POST
body: {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}}
T 2015-04-01 15:56:26:408 server.cc(230) Entering Server::DispatchCommand
T 2015-04-01 15:56:26:408 server.cc(530) Entering Server::LookupCommand
D 2015-04-01 15:56:26:408 server.cc(239) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}}
T 2015-04-01 15:56:26:408 server.cc(174) Entering Server::CreateSession
T 2015-04-01 15:56:26:409 IEServer.cpp(34) Entering IEServer::InitializeSession
T 2015-04-01 15:56:26:409 IESession.cpp(28) Entering IESession::Initialize
D 2015-04-01 15:56:26:409 IESession.cpp(43) Mutex acquired for session initalization
T 2015-04-01 15:56:26:409 IECommandExecutor.cpp(385) Entering IECommandExecutor::ThreadProc
T 2015-04-01 15:56:26:481 IECommandExecutor.cpp(84) Entering IECommandExecutor::OnCreate
T 2015-04-01 15:56:26:482 IECommandExecutor.cpp(757) Entering IECommandExecutor::PopulateCommandHandlers
T 2015-04-01 15:56:26:482 IECommandExecutor.cpp(744) Entering IECommandExecutor::PopulateElementFinderMethods
T 2015-04-01 15:56:26:482 InputManager.cpp(31) Entering InputManager::InputManager
T 2015-04-01 15:56:26:482 InputManager.cpp(54) Entering InputManager::Initialize
T 2015-04-01 15:56:26:482 IESession.cpp(87) Created thread for command executor returns HWND: '000000000002151E'
T 2015-04-01 15:56:26:483 IESession.cpp(99) Session id is retrived from command executor window: '831a680e-1c0a-44e5-8b78-57c76cd46b06'
D 2015-04-01 15:56:26:483 IESession.cpp(105) Releasing session initialization mutex
T 2015-04-01 15:56:26:483 server.cc(346) Entering Server::LookupSession
T 2015-04-01 15:56:26:483 IESession.cpp(187) Entering IESession::ExecuteCommand
T 2015-04-01 15:56:26:483 IECommandExecutor.cpp(151) Entering IECommandExecutor::OnSetCommand
T 2015-04-01 15:56:26:483 command.cc(27) Entering Command::Populate
D 2015-04-01 15:56:26:483 command.cc(33) Raw JSON command: { "command" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}} }
T 2015-04-01 15:56:26:483 IESession.cpp(208) Beginning wait for response length to be not zero
T 2015-04-01 15:56:26:483 IECommandExecutor.cpp(162) Entering IECommandExecutor::OnExecCommand
T 2015-04-01 15:56:26:483 IECommandExecutor.cpp(453) Entering IECommandExecutor::DispatchCommand
T 2015-04-01 15:56:26:483 BrowserFactory.cpp(34) Entering BrowserFactory::Initialize
T 2015-04-01 15:56:26:483 BrowserFactory.cpp(741) Entering BrowserFactory::GetExecutableLocation
T 2015-04-01 15:56:26:483 BrowserFactory.cpp(782) Entering BrowserFactory::GetIEVersion
T 2015-04-01 15:56:26:500 BrowserFactory.cpp(833) Entering BrowserFactory::GetOSVersion
T 2015-04-01 15:56:26:500 ProxyManager.cpp(69) ProxyManager::Initialize
T 2015-04-01 15:56:26:500 IECommandExecutor.cpp(623) Entering IECommandExecutor::CreateNewBrowser
T 2015-04-01 15:56:26:500 BrowserFactory.cpp(62) Entering BrowserFactory::LaunchBrowserProcess
D 2015-04-01 15:56:26:500 BrowserFactory.cpp(66) Ignoring Protected Mode Settings: 0
D 2015-04-01 15:56:26:500 BrowserFactory.cpp(69) Checking validity of Protected Mode settings.
T 2015-04-01 15:56:26:500 BrowserFactory.cpp(843) Entering BrowserFactory::ProtectedModeSettingsAreValid
D 2015-04-01 15:56:26:500 BrowserFactory.cpp(846) Detected IE version: 8, detected Windows version: 6
T 2015-04-01 15:56:26:501 BrowserFactory.cpp(919) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 15:56:26:501 BrowserFactory.cpp(936) Found Protected Mode setting value of 3 for zone 1
T 2015-04-01 15:56:26:501 BrowserFactory.cpp(919) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 15:56:26:501 BrowserFactory.cpp(936) Found Protected Mode setting value of 3 for zone 2
T 2015-04-01 15:56:26:501 BrowserFactory.cpp(919) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 15:56:26:501 BrowserFactory.cpp(936) Found Protected Mode setting value of 3 for zone 3
T 2015-04-01 15:56:26:501 BrowserFactory.cpp(919) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 15:56:26:501 BrowserFactory.cpp(936) Found Protected Mode setting value of 3 for zone 4
D 2015-04-01 15:56:26:501 BrowserFactory.cpp(72) Has Valid Protected Mode Settings: 1
T 2015-04-01 15:56:26:501 BrowserFactory.cpp(146) Entering BrowserFactory::IsIELaunchURLAvailable
T 2015-04-01 15:56:26:538 BrowserFactory.cpp(167) Entering BrowserFactory::LaunchBrowserUsingIELaunchURL
D 2015-04-01 15:56:26:538 BrowserFactory.cpp(168) Starting IE using the IELaunchURL API
D 2015-04-01 15:56:30:178 BrowserFactory.cpp(122) IE launched successfully with process ID 8504
D 2015-04-01 15:56:30:178 BrowserFactory.cpp(128) Process with ID 8504 is executing iexplore.exe
T 2015-04-01 15:56:30:178 BrowserFactory.cpp(282) Entering BrowserFactory::AttachToBrowser
T 2015-04-01 15:56:32:932 server.cc(62) Entering Server::OnHttpEvent
T 2015-04-01 15:56:32:932 server.cc(128) Entering Server::ProcessRequest
T 2015-04-01 15:56:32:932 server.cc(137) Process request with: URI: / HTTP verb: GET
body: {}
T 2015-04-01 15:56:32:932 server.cc(413) Entering Server::SendHttpOk
T 2015-04-01 15:56:36:477 BrowserFactory.cpp(247) Entering BrowserFactory::GetDocumentFromWindowHandle
W 2015-04-01 15:56:36:936 BrowserFactory.cpp(269) -2147467259 [Unspecified error]: Unable to convert document object pointer to IHTMLDocument2 object via ObjectFromLresult
W 2015-04-01 15:56:36:936 IECommandExecutor.cpp(639) Unable to attach to browser COM object
T 2015-04-01 15:56:36:936 response.cc(68) Entering Response::SetErrorResponse
W 2015-04-01 15:56:36:936 response.cc(69) Error response has status code 6 and message 'Unexpected error launching Internet Explorer. Could not get document from window handle' message
T 2015-04-01 15:56:36:936 IECommandExecutor.cpp(569) Entering IECommandExecutor::GetCurrentBrowser
T 2015-04-01 15:56:36:936 IECommandExecutor.cpp(575) Entering IECommandExecutor::GetManagedBrowser
T 2015-04-01 15:56:36:936 IECommandExecutor.cpp(578) Current command executor is not valid
W 2015-04-01 15:56:36:936 IECommandExecutor.cpp(516) Unable to get current browser
T 2015-04-01 15:56:36:936 response.cc(43) Entering Response::Serialize
T 2015-04-01 15:56:36:936 IESession.cpp(217) Found non-zero response length
T 2015-04-01 15:56:36:936 IECommandExecutor.cpp(185) Entering IECommandExecutor::OnGetResponse
T 2015-04-01 15:56:36:936 IECommandExecutor.cpp(290) Entering IECommandExecutor::OnIsSessionValid
T 2015-04-01 15:56:36:936 server.cc(183) Entering Server::ShutDownSession
T 2015-04-01 15:56:36:936 IESession.cpp(115) Entering IESession::ShutDown
T 2015-04-01 15:56:36:936 IESession.cpp(169) Entering IESession::WaitForCommandExecutorExit
D 2015-04-01 15:56:36:936 IESession.cpp(146) Executor shutdown successful!
D 2015-04-01 15:56:36:936 IESession.cpp(154) Posting thread shutdown message
D 2015-04-01 15:56:36:936 IESession.cpp(157) Starting wait for thread completion
D 2015-04-01 15:56:36:937 IESession.cpp(160) Waiting for thread to end returned 4294967295
D 2015-04-01 15:56:36:937 server.cc(308) Response: {"sessionId":"831a680e-1c0a-44e5-8b78-57c76cd46b06","status":6,"value":{"message":"Unexpected error launching Internet Explorer. Could not get document from window handle"}}

T 2015-04-01 15:56:36:937 server.cc(359) Entering Server::SendResponseToClient
T 2015-04-01 15:56:36:937 response.cc(32) Entering Response::Deserialize
T 2015-04-01 15:56:36:937 server.cc(451) Entering Server::SendHttpInternalError
D 2015-04-01 15:56:36:938 IECommandExecutor.cpp(435) Shutdown message received
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(131) Entering IECommandExecutor::OnDestroy
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(133) Clearing managed element cache
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(135) Closing input manager
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(137) Closing proxy manager
T 2015-04-01 15:56:36:939 ProxyManager.cpp(171) ProxyManager::RestoreProxySettings
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(139) Closing browser factory
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(141) Posting quit message
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(143) Leaving IECommandExecutor::OnDestroy
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(437) Returned from DestroyWindow()
D 2015-04-01 15:56:36:939 IECommandExecutor.cpp(446) Exited IECommandExecutor thread message loop
T 2015-04-01 15:56:37:165 server.cc(62) Entering Server::OnHttpEvent
T 2015-04-01 15:56:37:165 server.cc(128) Entering Server::ProcessRequest
T 2015-04-01 15:56:37:165 server.cc(137) Process request with: URI: /favicon.ico HTTP verb: GET
body: {}
T 2015-04-01 15:56:37:165 server.cc(230) Entering Server::DispatchCommand
T 2015-04-01 15:56:37:165 server.cc(530) Entering Server::LookupCommand
D 2015-04-01 15:56:37:166 server.cc(239) Command: GET /favicon.ico {}
D 2015-04-01 15:56:37:166 server.cc(308) Response: { "status" : 404, "sessionId" : "<no session>", "value" : "Command not found: GET /favicon.ico" }
T 2015-04-01 15:56:37:166 server.cc(359) Entering Server::SendResponseToClient
T 2015-04-01 15:56:37:166 response.cc(32) Entering Response::Deserialize
T 2015-04-01 15:56:37:166 server.cc(470) Entering Server::SendHttpNotFound

**Comment by pcomerton** [comment]
Sorry  ddavison  - just pasted in log in comments as had trouble attaching it.

**Comment by barancev** [comment]
D 2015-04-01 15:56:25:987 server.cc(308) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.39.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

That's what I see in the log. Version 2.39.0.0

**Comment by pcomerton** [comment]
Yeah I swapped back this morning as Version 2.45.0.0 was causing the same error. I thought maybe I had gone too far ahead for IE8. Same result with Version 2.45.0.0

I 2015-04-01 16:36:15:639 server.cc(72) Starting WebDriver server on port: '50905' on host: ''
T 2015-04-01 16:36:15:639 server.cc(592) Entering Server::PopulateCommandRepository
T 2015-04-01 16:36:15:639 IEServer.cpp(26) Entering IEServer::IEServer
T 2015-04-01 16:36:15:639 server.cc(88) Entering Server::Start
D 2015-04-01 16:36:15:639 server.cc(110) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
T 2015-04-01 16:36:16:006 server.cc(136) Entering Server::ProcessRequest
T 2015-04-01 16:36:16:006 server.cc(145) Process request with: URI: /status HTTP verb: GET
body: {}
T 2015-04-01 16:36:16:006 server.cc(234) Entering Server::DispatchCommand
T 2015-04-01 16:36:16:006 server.cc(541) Entering Server::LookupCommand
D 2015-04-01 16:36:16:006 server.cc(243) Command: GET /status {}
T 2015-04-01 16:36:16:006 IEServer.cpp(46) Entering IEServer::GetStatus
T 2015-04-01 16:36:16:006 response.cc(60) Entering Response::SetSuccessResponse
T 2015-04-01 16:36:16:006 response.cc(66) Entering Response::SetResponse
T 2015-04-01 16:36:16:006 response.cc(48) Entering Response::Serialize
D 2015-04-01 16:36:16:006 server.cc(317) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.45.0.0"},"os":{"arch":"x64","name":"windows","version":"6.1.7601"}}}

T 2015-04-01 16:36:16:006 server.cc(370) Entering Server::SendResponseToClient
T 2015-04-01 16:36:16:006 response.cc(33) Entering Response::Deserialize
T 2015-04-01 16:36:16:006 server.cc(424) Entering Server::SendHttpOk
T 2015-04-01 16:36:16:029 server.cc(136) Entering Server::ProcessRequest
T 2015-04-01 16:36:16:029 server.cc(200) Entering Server::ReadRequestBody
T 2015-04-01 16:36:16:029 server.cc(145) Process request with: URI: /session HTTP verb: POST
body: {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}}
T 2015-04-01 16:36:16:029 server.cc(234) Entering Server::DispatchCommand
T 2015-04-01 16:36:16:029 server.cc(541) Entering Server::LookupCommand
D 2015-04-01 16:36:16:029 server.cc(243) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}}
T 2015-04-01 16:36:16:029 IEServer.cpp(36) Entering IEServer::InitializeSession
T 2015-04-01 16:36:16:029 IESession.cpp(34) Entering IESession::Initialize
D 2015-04-01 16:36:16:029 IESession.cpp(49) Mutex acquired for session initalization
D 2015-04-01 16:36:16:029 IESession.cpp(94) Using legacy driver implementation per user request
T 2015-04-01 16:36:16:030 IECommandExecutor.cpp(402) Entering IECommandExecutor::ThreadProc
T 2015-04-01 16:36:16:121 IECommandExecutor.cpp(90) Entering IECommandExecutor::OnCreate
T 2015-04-01 16:36:16:122 IECommandExecutor.cpp(774) Entering IECommandExecutor::PopulateCommandHandlers
T 2015-04-01 16:36:16:122 IECommandExecutor.cpp(761) Entering IECommandExecutor::PopulateElementFinderMethods
T 2015-04-01 16:36:16:122 InputManager.cpp(34) Entering InputManager::InputManager
T 2015-04-01 16:36:16:122 InputManager.cpp(57) Entering InputManager::Initialize
T 2015-04-01 16:36:16:122 BrowserFactory.cpp(894) Entering BrowserFactory::GetExecutableLocation
T 2015-04-01 16:36:16:122 BrowserFactory.cpp(935) Entering BrowserFactory::GetIEVersion
T 2015-04-01 16:36:16:143 BrowserFactory.cpp(986) Entering BrowserFactory::GetOSVersion
T 2015-04-01 16:36:16:143 IESession.cpp(118) Created thread for command executor returns HWND: '000000000011130C'
T 2015-04-01 16:36:16:143 IESession.cpp(122) Session id is retrived from command executor window: '06e1b3f7-166b-43a1-93c7-0b7e786afa30'
D 2015-04-01 16:36:16:143 IESession.cpp(128) Releasing session initialization mutex
T 2015-04-01 16:36:16:143 IESession.cpp(212) Entering IESession::ExecuteCommand
T 2015-04-01 16:36:16:143 IECommandExecutor.cpp(158) Entering IECommandExecutor::OnSetCommand
T 2015-04-01 16:36:16:143 command.cc(28) Entering Command::Deserialize
D 2015-04-01 16:36:16:143 command.cc(33) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":true,"enablePersistentHover":true,"ignoreZoomSetting":true,"elementScrollBehavior":1}} }
T 2015-04-01 16:36:16:143 IECommandExecutor.cpp(169) Entering IECommandExecutor::OnExecCommand
T 2015-04-01 16:36:16:143 IESession.cpp(233) Beginning wait for response length to be not zero
T 2015-04-01 16:36:16:143 IECommandExecutor.cpp(470) Entering IECommandExecutor::DispatchCommand
T 2015-04-01 16:36:16:143 BrowserFactory.cpp(44) Entering BrowserFactory::Initialize
T 2015-04-01 16:36:16:143 ProxyManager.cpp(70) ProxyManager::Initialize
T 2015-04-01 16:36:16:143 IECommandExecutor.cpp(640) Entering IECommandExecutor::CreateNewBrowser
T 2015-04-01 16:36:16:143 BrowserFactory.cpp(73) Entering BrowserFactory::LaunchBrowserProcess
D 2015-04-01 16:36:16:143 BrowserFactory.cpp(77) Ignoring Protected Mode Settings: 0
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(80) Checking validity of Protected Mode settings.
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(996) Entering BrowserFactory::ProtectedModeSettingsAreValid
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(999) Detected IE version: 8, detected Windows version: 6
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(1072) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(1089) Found Protected Mode setting value of 3 for zone 1
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(1072) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(1089) Found Protected Mode setting value of 3 for zone 2
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(1072) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(1089) Found Protected Mode setting value of 3 for zone 3
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(1072) Entering BrowserFactory::GetZoneProtectedModeSetting
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(1089) Found Protected Mode setting value of 3 for zone 4
D 2015-04-01 16:36:16:144 BrowserFactory.cpp(83) Has Valid Protected Mode Settings: 1
T 2015-04-01 16:36:16:144 BrowserFactory.cpp(157) Entering BrowserFactory::IsIELaunchURLAvailable
T 2015-04-01 16:36:16:187 BrowserFactory.cpp(61) Entering BrowserFactory::ClearCache
T 2015-04-01 16:36:16:187 BrowserFactory.cpp(178) Entering BrowserFactory::LaunchBrowserUsingIELaunchURL
D 2015-04-01 16:36:16:188 BrowserFactory.cpp(179) Starting IE using the IELaunchURL API
D 2015-04-01 16:36:19:349 BrowserFactory.cpp(133) IE launched successfully with process ID 6972
D 2015-04-01 16:36:19:349 BrowserFactory.cpp(139) Process with ID 6972 is executing iexplore.exe
T 2015-04-01 16:36:19:349 BrowserFactory.cpp(296) Entering BrowserFactory::AttachToBrowser
T 2015-04-01 16:36:19:349 BrowserFactory.cpp(340) Entering BrowserFactory::AttachToBrowserUsingActiveAccessibility
T 2015-04-01 16:36:23:737 server.cc(136) Entering Server::ProcessRequest
T 2015-04-01 16:36:23:737 server.cc(145) Process request with: URI: / HTTP verb: GET
body: {}
T 2015-04-01 16:36:23:737 server.cc(424) Entering Server::SendHttpOk
T 2015-04-01 16:36:28:076 BrowserFactory.cpp(260) Entering BrowserFactory::GetDocumentFromWindowHandle
W 2015-04-01 16:36:28:929 BrowserFactory.cpp(283) -2147467259 [Unspecified error]: Unable to convert document object pointer to IHTMLDocument2 object via ObjectFromLresult
D 2015-04-01 16:36:28:929 BrowserFactory.cpp(309) Failed to find IWebBrowser2 using ActiveAccessibility: Could not get document from window handle
D 2015-04-01 16:36:28:929 BrowserFactory.cpp(314) Using IShellWindows to find IWebBrowser2 interface
T 2015-04-01 16:36:28:929 BrowserFactory.cpp(404) Entering BrowserFactory::AttachToBrowserUsingShellWindows
D 2015-04-01 16:36:29:213 BrowserFactory.cpp(322) Ignoring zoom setting: 1
I 2015-04-01 16:36:29:213 IECommandExecutor.cpp(662) Persistent hovering set to: 1
T 2015-04-01 16:36:29:214 ProxyManager.cpp(103) ProxyManager::SetProxySettings
D 2015-04-01 16:36:29:214 ProxyManager.cpp(119) Using existing system proxy settings.
T 2015-04-01 16:36:29:214 DocumentHost.cpp(25) Entering DocumentHost::DocumentHost
T 2015-04-01 16:36:29:214 Browser.cpp(24) Entering Browser::Browser
T 2015-04-01 16:36:29:214 Browser.cpp(279) Entering Browser::AttachEvents
T 2015-04-01 16:36:29:523 server.cc(136) Entering Server::ProcessRequest
T 2015-04-01 16:36:29:523 server.cc(145) Process request with: URI: /favicon.ico HTTP verb: GET
body: {}
T 2015-04-01 16:36:29:523 server.cc(234) Entering Server::DispatchCommand
T 2015-04-01 16:36:29:523 server.cc(541) Entering Server::LookupCommand
D 2015-04-01 16:36:29:523 server.cc(243) Command: GET /favicon.ico {}
D 2015-04-01 16:36:29:523 server.cc(317) Response: { "status" : 404, "sessionId" : "<no session>", "value" : "Command not found: GET /favicon.ico" }
T 2015-04-01 16:36:29:523 server.cc(370) Entering Server::SendResponseToClient
T 2015-04-01 16:36:29:523 response.cc(33) Entering Response::Deserialize
T 2015-04-01 16:36:29:523 server.cc(481) Entering Server::SendHttpNotFound

**Comment by barancev** [comment]
I can't see nothing critical in the log. Summoning @jimevans

**Comment by pcomerton** [comment]
Thanks for your help barancev

**Comment by jimevans** [comment]
@pcomerton The description of the issue you've posted is inconsistent with the log file you submitted. You say that IE is never launched. In your log file using 2.45.0, there is the line:
    D 2015-04-01 16:36:19:349 BrowserFactory.cpp(133) IE launched successfully with process ID 6972
This is quite clearly indicative that IE is launching. Furthermore, you've said things are "crashing." Let's define our terms. Does your .NET code throw an exception, or does the IEDriverServer.exe process terminate?

Please don't fixate on `Unable to convert document object pointer to IHTMLDocument2 object via ObjectFromLresult` in the log file. There is a fallback mechanism to attempt getting the `IHTMLDocument2` object through a different code path if that one fails. Of course, if both attempts fail, there's no way to hook into the launched IE process, and thus, no way to automate it.

Finally, I'll point out that this is not a global problem. Thousands of people are running the IE driver against IE8 without experiencing anything close to this. What happens if you try a fresh Windows install, perhaps using a virtual machine, where you have full control of the OS?

**Comment by pcomerton** [comment]
@jimevans - Hi Jim thanks for feedback - I never said IE is never launched. If you read my descriptions above you will see I stated "Every time I try to launch IEDriver it crashes"  and " I'm not actually navigating to any page it crashes as soon as the webbrowser is launched. " i.e.  that as soon as the web browser (IE) is launched IEDriver crashes. 

When I say crash i mean I get a popup window which states that "Command Line Server for IE Driver has stopped working". When I click on the Debug button on the popup I get the following error message - An unhandled Win32 exception happened in IEDriverServer.exe 9364 in the Visual Studio Just-In-Time Debugger. When I select my debugger and click to debug I immediately get the fiollowing error "Unhandled exception at 0x000007FED79E52DB (IED4DA5.tmp) in IEDriverServer.exe: 0xC0000005; Access violation reading location 0x0000000000000000." 

Sorry would attach screenshots if I could but don't seem to have the rights to.

Incidentally the tests run fine using Chromedriver or Firefox.

Thanks,

Paul

**Comment by jimevans** [comment]
@pcomerton Okay, I believe I may have a handle what's causing the crash, and may be able to paper over it. I will be entirely _**unable**_ to solve the root cause of the issue, which is that something in your environment is preventing the driver from connecting to the `IWebBrowser2` COM object of the IE instance that it launches. That root cause is entirely specific to your environment, and I've no way to be able to narrow it down any further. Once again, I recommend trying your code using a virtual machine, whose environment you fully control (maybe from [http://modern.ie](http://modern.ie)?), for testing purposes, to narrow down that it's specific to the environment you're currently using.

**Comment by pcomerton** [comment]
@jimevans - Hi Jim - thanks for the feedback. I'll try on a virtual machine and post results after completed.

**Comment by jimevans** [comment]
Crash prevention implemented in 6c807c7. As stated above, that's the best we can do for this particular issue, absent more data enabling reproducibility.
