### ISSUE TITLE
Selenium IDE throws unexpected error. Msg: TypeError: editor.app is undefined

### ISSUE THREAD

**Issue by csanthosh13** [SeleniumHQ/selenium#3985]
## Meta -
OS:  Windows 10

Selenium Version:  Selenium IDE 2.9.1

Browser:  Firefox

Browser Version:  Firefox 53.0.2

## Expected Behavior -
When opening Selenium IDE, the functionality should work as expected.

## Actual Behavior -
On opening Selenium IDE, Application Error is being thrown. Please check screenshot for reference
![selenium_ide_error](https://cloud.githubusercontent.com/assets/1712373/25780436/c61efc8a-3345-11e7-9726-98e96a5baebf.jpg)
![selenium_ide_error](https://cloud.githubusercontent.com/assets/1712373/25780477/d5fbce08-3345-11e7-9c14-426ae7ae3bca.jpg)

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
