### ISSUE TITLE
Missing Python bindings for Chrome network emulation

### ISSUE THREAD

**Issue by tomaszn** [SeleniumHQ/selenium#3986]
Analogically to JS bindings prepared in #3624 and committed in d7bdd7cc, Python bindings are missing the Chrome debugging protocol functionality for getting and setting network emulation settings.
This functionality was added to ChromeDriver in March of 2015 (https://chromium.googlesource.com/chromium/src.git/+/12a55ff7369b35adb29cd28f5e3dd4ef923e3e6c).

**Comment by p0deje** [comment]
I'm closing this issue - keep track of #4011.
