### ISSUE TITLE
selenium must match fixes with firefox release cycle or identify that the build is not compatible

### ISSUE THREAD

**Issue by vairamsvsjdo** [SeleniumHQ/selenium#3987]
## Meta -
OS:  
Windows 10 , windows 7
Selenium Version:  
HQ 3.3.3, robotframework 3.0.2, python 3.6, selenium2library
Browser:  
Firefox

Browser Version:  

53.0.0

## Expected Behavior -
Selenium works as expected for Press Key (selenium2library key) in Firefox 53.0.0
## Actual Behavior -
fails and no error reported.

## Steps to reproduce -
see as described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1362609

selenium must match fixes with firefox release cycle or identify that the build is not compatible

**Comment by AutomatedTester** [comment]
The rule we have always worked on is latest Selenium and Firefox and if possible we will try do N-1 where N is the release version of Firefox.
