### ISSUE TITLE
Actions class is not consistently inheritable

### ISSUE THREAD

**Issue by brunnerh** [SeleniumHQ/selenium#3989]
## Meta -
Selenium Version:  3.4/.NET Bindings

## Expected Behavior -

When adding an action to an `Actions` subclass via `protected void AddAction(IAction actionToAdd)` the action should be executed when calling `Perform`.

## Actual Behavior -

Depending on the driver used, the action will be executed or ignored.

## Steps to reproduce -

1. Subclass `Actions`
2. Add method that calls `AddAction`
3. Call method in test case
    - ChromeDriver (executable v2.29): Executes
    - FirefoxDriver (executable: v0.16.1): Ignores

## Underlying reason

`Actions` has two lists of actions and `AddAction`, the only method that allows generic access to those lists, adds to the `CompositeAction` list.

    this.action.AddAction(actionToAdd);

`Perform` only executes one of the two based on driver capabilities:

    IActionExecutor actionExecutor = this.driver as IActionExecutor;
    if (actionExecutor.IsActionExecutor)
    {
        actionExecutor.PerformActions(this.actionBuilder.ToActionSequenceList());
    }
    else
    {
        this.action.Perform();
    }

**Comment by jimevans** [comment]
By all rights, the `Actions` class should have been `sealed`, but since it wasn't, let's work together on a fix. You should understand that your subclass will have to change and that the `AddAction` method will no longer be sufficient in itself to create a custom action. You'll also need to call a new method that adds the data structure that can be serialized to the W3C dialect of the wire protocol. You have two options.

    Actions.AddAction(Interaction actionToAdd)

Or

    Actions.AddInteraction(Interaction toAdd)

Which would you prefer?

**Comment by brunnerh** [comment]
Overloading `AddAction` is probably a bad idea; it would suggest that the overloads are equivalent, which they are not. Aside from the new method there should be a note that for every `AddAction` an equivalent `AddInteraction` call has to be made an vise-versa to ensure correct behaviour.

Personally i would not mind sealing the class, at this point any change is potentially breaking.

**Comment by brunnerh** [comment]
Also: The device classes probably need to be exposed to be able to construct interactions in the first place.

**Comment by jimevans** [comment]
Of course, the device type classes would need to be exposed. All evidence to the contrary, I do have a minimum level of competence. :) Truth to tell, I thought I'd already done so, but it got overlooked when the initial `Interactions` class was made public in 3.4

**Comment by barancev** [comment]
This issue should be fixed in version 3.7, please verify

**Comment by barancev** [comment]
Let's suppose it's fixed, according to @jimevans comment in commit a4bbfbeb3378c2bd3016fe650ee16cae80644e41)
