### ISSUE TITLE
Can't open SafariDriver

### ISSUE THREAD

**Issue by J320** [SeleniumHQ/selenium#3990]
## Meta -
OS:  MacOS Sierra 10.12.4

Selenium Version:  3.4.0

Browser: Safari

Browser Version: 10.1

## Expected Behavior -
I have the latest Selenium, OSX and Safari versions but I'm unable to open Safari Driver using a code as simple as this:

` 
 
      public class SafariDriverDemo {

      public static void main(String[] args) throws InterruptedException {
        WebDriver driver;
        driver = new SafariDriver();

        String baseURL = "https://www.google.com";

        driver.get(baseURL);
        Thread.sleep(3000);

        driver.quit();
      }

     }
`

## Actual Behavior -

- What I get in the console is the following: "Password:Password:Password:".

- And regardless of what password I write, the console displays: 
![screenshot](https://cloud.githubusercontent.com/assets/28388283/25800833/dc019948-33e2-11e7-985f-a83472a8d53e.jpeg)

This despite me having enabled 'Allow Remote Automation'. I've tried authorising the driver from the Terminal by typing '/usr/bin/safaridriver'and this is the result

`

    Could not start server: must specify at least one configuration argument.

     Usage: safaridriver [options]
     -h, --help                Prints out this usage information.
     -p, --port                Port number the driver should use. If the server
                          is already running, the port cannot be changed.
                          If port 0 is specified, a default port will be used

`

I don't know what action to take from here, maybe the issue can be fixed from the console.

## Steps to reproduce -
Simply writing the code displayed above which in theory should activate the Driver

**Comment by JasonLunn** [comment]
How are you launching the selenium server? I have found different behavior when I start selenium by hand and when I let it be started by a background process (from our CI system).

**Comment by J320** [comment]
Hi Jason, thank you for your reply. Sorry I haven't replied in so long, I've lost the notification somewhere.

I start it how I specify it above, just by calling SafariDriver on Selenium, I've also enabled Automation on Safari and tried using the Terminal but I don't know how to proceed. I tried '/usr/bin/safaridriver -p 0' but it asks me for some password and all the ones I know that have to do with the computer don't work.

**Comment by burg** [comment]
@J320, the behavior for this has changed in Safari 11. Now, it will never prompt for password; if you haven't authenticated it will quit immediately with a nonzero exit code and tell you what's wrong.

You can run `safaridriver --enable` once per login session and authenticate as an administrator user. Normally, this requires your login password (what you would use to authenticate for sudo). Once you do this, all subsequent launches will reuse the authentication and not prompt for a password.

Please close this issue once you can verify the above information.

**Comment by barancev** [comment]
Closing the issue, seems to be a misconfiguration.
