### ISSUE TITLE
webdriver.Builder().forBrowser('chrome').build() hangs indefinitely

### ISSUE THREAD

**Issue by raghuAtWings** [SeleniumHQ/selenium#3997]
## Meta -
OS:  
ubuntu (linux)
Selenium Version:  
"selenium-webdriver": "^3.4.0",
Browser:  
chrome

Browser Version:  
Google Chrome 58.0.3029.81 

## Expected Behavior -
All tests should run without getting error on getting webdriver
## Actual Behavior -
call to build webdriver hangs

## Steps to reproduce -
I am using mocha and selenium to do end to end integration testing. I am using beforeEach and afterEach hook to initialize browser and kill it after each test. Here is my js file which has both the methods

```
    const webdriver = require('selenium-webdriver')
    require('selenium-webdriver/chrome')
    require('chromedriver')
    global.driver = {}
    
    // setup
    beforeEach(async function () {
      this.timeout(60000)
      try {
        driver = await new webdriver.Builder().forBrowser('chrome').build()
        await driver.manage().window().setSize(1600, 900)
      } catch (ex) {
        console.log(ex.stack)
      }
    
    })
    
    afterEach(async function () {
      this.timeout(60000)
      await driver.quit()
    })
```

Now when i run the test suit on jenkins i very frequently see this ("email already registered" is a test name)

    ✓ email domain not allowed (4167ms)
        1) "before each" hook for "email already registered"
  
    
      39 passing (9m)
      1 pending
      1 failing
    
      1)  "before each" hook for "email already registered":
         Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

The thing to notice is that once this error comes the subsequent tests do not run. My test suit has 100s of tests and in the run above it quit once it encountered this beforeEach error and didn't run next set of tests.

**Comment by jleyba** [comment]
This is #3037

You need to update your test with:

```js
const {promise} = require('selenium-webdriver');
promise.USE_PROMISE_MANAGER = false;
```

See this example:

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/async_await_test.js

**Comment by raghuAtWings** [comment]
FYI this was already there. I had this in my code and still saw this behavior

**Comment by neutraali** [comment]
Also stuck on a similar issue - Calling:
```javascript
this.driver = new Builder()
	.forBrowser('chrome')
	.setChromeOptions(opts)
	.setChromeService(srvc)
	.build();
```
... Just seems to hang and nothing happens - _For the first run of the tests._ On the second run (e.g. running the exact same tests again) everything seems to work. As far as relevant libraries go we're running with:
```
    "chai": "4.2.0",
    "mocha": "5.0.5",
    "selenium-webdriver": "4.0.0-alpha.1"
```
Here's the last few lines of our `webdriver.log`:
```
