### ISSUE TITLE
[WIKI] DesiredCapabilities page table badly formatted

### ISSUE THREAD

**Issue by antonyoneill** [SeleniumHQ/selenium#3998]
## Meta -
OS:  -

Selenium Version:  -

Browser:  -

Browser Version:  -

## Expected Behavior -
`Used by the selenium server for browser selection` table renders correctly:

| **Key** | **Type** | **Description** |
|:--------|:---------|:----------------|
| browserName | string   | The name of the browser being used; should be one of `android`,`chrome`,`firefox`,`htmlunit`,`internet explorer`,`iPhone`,`Pad`,`opera`,`safari`. |
| version | string   | The browser version, or the empty string if unknown. |
| platform | string   | A key specifying which platform the browser should be running on. This value should be one of `WINDOWS`,`XP`,`VISTA`,`MAC`,`LINUX`,`UNIX`,`ANDROID`. When requesting a new session, the client may specify `ANY` to indicate any available platform may be used. For more information see [[GridPlatforms](GridPlatforms.md)] |

## Actual Behavior -
`Used by the selenium server for browser selection` table contains rows with `|` symbols which are causing options to be missed

| **Key** | **Type** | **Description** |
|:--------|:---------|:----------------|
| browserName | string   | The name of the browser being used; should be one of `{android|chrome|firefox|htmlunit|internet explorer|iPhone|iPad|opera|safari}`. |
| version | string   | The browser version, or the empty string if unknown. |
| platform | string   | A key specifying which platform the browser should be running on. This value should be one of `{WINDOWS|XP|VISTA|MAC|LINUX|UNIX|ANDROID}`. When requesting a new session, the client may specify `ANY` to indicate any available platform may be used. For more information see [[GridPlatforms](GridPlatforms.md)] |

## Steps to reproduce -

- Navigate to https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities
- Confirm table only contains first option for `browserName` and `platform`

**Comment by lmtierney** [comment]
Thanks, updated!
