### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by GaneshBalasubramanian15** [SeleniumHQ/selenium#4000]
Hello guys,

how are you keeping?
I am getting this issue when i recently upgraded my gecko to V0.16.1

org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DUB001843', ip: '169.254.214.50', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x489f6f - <no info>
   1:           0x48ad59 - <no info>
   2:           0x43c325 - <no info>
   3:           0x443f9a - <no info>
   4:           0x41ddb1 - <no info>
   5:           0x4091c7 - <no info>
   6:           0x6bc939 - <no info>
   7:           0x415a19 - <no info>
   8:           0x6b6e43 - <no info>
   9:         0x76dc59cd - BaseThreadInitThunk
Command duration or timeout: 832 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

------------------------->
This is my grid batch file, 

START "Selenium Node - (for Hub with Port 4411)" java -Dwebdriver.gecko.driver="geckodriver.exe" -Dwebdriver.ie.driver="IEDriverServer3_4_0.exe" -Dwebdriver.chrome.driver="chromedriver2_29.exe" -Dwebdriver.phantomjs.driver="XXXXXXXXphantomjs.exe" -jar selenium-server-standalone-3.4.0.jar -role node -nodeConfig node.json

---->
Node json file 
  {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver",
	  "firefox_binary": "C:\XXXX\\firefox.exe",
	  "webdriver.gecko.driver":" C:XXXXxgeckodriver.exe"
    },

kindly help and share your ideas.

**Comment by chrisalis** [comment]
I'm getting the same trying to run tests through Selenium Grid on my Linux Mint VM.

I start the node on the VM with:
java -jar -Dwebdriver.gecko.driver=/home/chris/geckodriver selenium-server-standalone-3.4.0.jar -role node -hub http://ASUSLaptop:4444/grid/register -port 5555 -browser browserName=firefox,version=50.0.2,maxInstances=2,platform=LINUX

My Grid Console shows the node registered with these capabilities:
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=firefox, maxInstances=2, version=50.0.2, platform=LINUX}]

In Eclipse, my test has:
		System.setProperty("webdriver.gecko.driver", linuxGeckoPath); // path to geckodriver-v0.16.1-linux64
		baseUrl = "http://www.expedia.co.uk";
		nodeURL = "http://192.168.124.135:5555/wd/hub";	//	LINUX VM
		DesiredCapabilities caps = DesiredCapabilities.firefox();
		caps.setBrowserName("firefox");
		caps.setPlatform(Platform.LINUX);
		driver = new RemoteWebDriver(new URL(nodeURL), caps);

When I run the test, in Eclipse I get:
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'LinuxMintx64VM', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-53-generic', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver

I get the same message on my Linux Mint VM terminal window.

Help would be appreciated.

**Comment by AutomatedTester** [comment]
This is normally happening when the Firefox version is <53. Please upgrade Firefox

**Comment by chrisalis** [comment]
As I said in my email, it's happening with FF 53.0.3

**Comment by AutomatedTester** [comment]
@chrisalis your comment on this bug has no mention of Firefox 53.

You have `java -jar -Dwebdriver.gecko.driver=/home/chris/geckodriver selenium-server-standalone-3.4.0.jar -role node -hub http://ASUSLaptop:4444/grid/register -port 5555 -browser browserName=firefox,version=50.0.2,maxInstances=2,platform=LINUX` which suggests Firefox 50, not 53. 

As _I_ said in my previous comment, please update

**Comment by samsul-kabir** [comment]
Hi there,

I am using protractor and having the same issue while running my test.

Protractor = 5.1.1
Firefox = 53.0.3

And getting this error:

Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'prv99.local', ip: '3554:120:1232:44:d398:3aad:e577:6535', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:        0x10c2a482e - backtrace::backtrace::trace::h76b688ec9dd0c4e2
   1:        0x10c2a4f6c - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
   2:        0x10c25c8cb - geckodriver::marionette::MarionetteHandler::create_connection::h4f4bd0cd049a6fe3
   3:        0x10c264caf - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::hcb53484f0f6d535e
   4:        0x10c257e60 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::he6d10c2fe3c7e795
   5:        0x10c22da5d - std::panicking::try::do_call::hd7b79b66c427c537
   6:        0x10c3cfd1a - __rust_maybe_catch_panic
   7:        0x10c23a79a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hde402662965177dc
   8:        0x10c3ce174 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f
   9:     0x7fff9493e93a - _pthread_body
  10:     0x7fff9493e886 - _pthread_start

**Comment by nddipiazza** [comment]
having this issue too. 

 ```
0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d
		   1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0
		   2:           0x44bfd0 - geckodriver::marionette::MarionetteHandler::create_connection::h6f7058fccafe4367
		   3:           0x425c32 - <webdriver::server::Dispatcher<T, U>>::run::h8f5348b8f5f7c053
		   4:           0x40b22c - std::panicking::try::do_call::hb67c6fb6bcd96195
		   5:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic
		                        at /checkout/src/libpanic_unwind/lib.rs:98
		   6:           0x41b943 - <F as alloc::boxed::FnBox<A>>::call_box::h4100941edc372034
		   7:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>
		                        at /checkout/src/liballoc/boxed.rs:650
		                         - std::sys_common::thread::start_thread
		                        at /checkout/src/libstd/sys_common/thread.rs:21
		                         - std::sys::imp::thread::{{impl}}::new::thread_start
		                        at /checkout/src/libstd/sys/unix/thread.rs:84
```

**Comment by johnskpaul** [comment]
Hi I'm using the latest version of firefox..configured jenkins in linux

public void setUp() throws Exception {
		  System.setProperty("webdriver.gecko.driver", "/usr/local/bin/geckodriver");
			DesiredCapabilities capabilities = DesiredCapabilities.firefox();
			capabilities.setCapability("marionette", true);
driver = new FirefoxDriver(capabilities);

I'm getting the same error...please let me know if there is any solution for this...

org.openqa.selenium.SessionNotCreatedException: 
Unable to find a matching set of capabilities
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.22.1.el6.x86_64', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d
   1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:           0x44bfd0 - geckodriver::marionette::MarionetteHandler::create_connection::h6f7058fccafe4367
   3:           0x425c32 - <webdriver::server::Dispatcher<T, U>>::run::h8f5348b8f5f7c053
   4:           0x40b22c - std::panicking::try::do_call::hb67c6fb6bcd96195
   5:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   6:           0x41b943 - <F as alloc::boxed::FnBox<A>>::call_box::h4100941edc372034
   7:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84

**Comment by nddipiazza** [comment]
install GTK3 deps

**Comment by ashokcse08** [comment]
Hi,

I am using FireFox 56.0 and geckodriver 0.19.0 and selenium 3.5.1 and getting the following error. The same error is seen for selenium 3.5.2 & 3.5.3. any help would be much appreciated.

org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-17T15:26:08.955Z'
System info: host: 'NASHOK', ip: '10.5.5.105', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: Driver
remote stacktrace: stack backtrace:
   0:   0x47d2a4 - <no info>
   1:   0x45d174 - <no info>
   2:   0x427701 - <no info>
   3:   0x42ac5a - <no info>
   4:   0x45ff5e - <no info>
   5:   0x45581f - <no info>
   6:   0x4437a6 - <no info>
   7:   0x443aa6 - <no info>
   8:   0x6de879 - <no info>
   9:   0x4439e9 - <no info>
  10:   0x44385b - <no info>
  11:   0x4575c8 - <no info>
  12:   0x6da071 - <no info>
  13: 0x769c336a - BaseThreadInitThunk
  14: 0x76f598f2 - RtlInitializeExceptionChain
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:360)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:363)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:137)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:254)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
	at talos.driver.DriverFactory.intializeDriver(DriverFactory.java:77)
	at talos.driver.Driver.setDriverValue(Driver.java:33)
	at talos.driver.Driver.getDriver(Driver.java:73)
	at talos.common.PageObjectFactory.<init>(PageObjectFactory.java:37)
	at talos.tests.scm.angular.AngularTestsForSCM.angularTest1(AngularTestsForSCM.java:33)

**Comment by njabs2703** [comment]
I'm using Firefox 59.0.1 (64-bit), selenium 3.6.0 and geckodriver 0.20.0. I am getting the issue below.

java.lang.UnsupportedOperationException: Cant create WebDriver: org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
[info] Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
[info] System info: host: 'guest', ip: 'X.X.X.X', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-37-generic', java.version: '1.8.0_151'
[info] Driver info: driver.version: FirefoxDriver
[info] remote stacktrace:
[info]   at org.scalatestplus.play.BrowserFactory$UnavailableDriver.complain(BrowserFactory.scala:155)
[info]   at org.scalatestplus.play.BrowserFactory$GrumpyDriver.manage(BrowserFactory.scala:117)
[info]   at org.scalatest.selenium.WebBrowser$delete$.all(WebBrowser.scala:4219)
[info]   at org.scalatest.selenium.WebBrowser$class.deleteAllCookies(WebBrowser.scala:4254)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at 
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info]   ...
[info]   Cause: org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
[info] Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
[info] System info: host: 'guest', ip: 'X.X.X.x', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-37-generic', java.version: '1.8.0_151'
[info] Driver info: driver.version: FirefoxDriver
[info] remote stacktrace:
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
[info]   at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
[info]   at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
[info]   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[info]   at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
[info]   at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
