### ISSUE TITLE
Selenium WebDriver v. 3.4.0 - Build info is missed in META-INF

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [SeleniumHQ/selenium#4001]
Following properties are missed in 3.4.0 Manifest file: 
**Build-Timestamp
Build-Revision
Build-Time**

Contents of .m2\repository\org\seleniumhq\selenium\selenium-api\3.4.0\selenium-api-3.4.0\META-INF\MANIFEST.MF:
```
Manifest-Version: 1.0

Name: Build-Info
Selenium-Version: 3.4.0

```
Previous version: .m2\repository\org\seleniumhq\selenium\selenium-api\3.3.1\selenium-api-3.3.1\META-INF\MANIFEST.MF:
```
Manifest-Version: 1.0

Name: Build-Info
Selenium-Version: 3.3.1
Build-Timestamp: 1489137029856
Build-Revision: 5234b325d5
Build-Time: 2017-03-10 09:10:29 +0000

```

**Comment by barancev** [comment]
Fixed in version 3.5.1
