### ISSUE TITLE
Handsontable contextmenu click problem

### ISSUE THREAD

**Issue by egemenceylan** [SeleniumHQ/selenium#4002]
## Meta -
OS:  Windows10

Selenium Version:  IDE 2.9.1

Browser:  Chrome, Firefox, Safari

Browser Version:

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
