### ISSUE TITLE
Node JS selenium-testing before/after test hooks fail when provided with descriptions

### ISSUE THREAD

**Issue by IronGremlin** [SeleniumHQ/selenium#4006]
Descriptions on `before` / `after` method hooks exposed in the Node.js `selenium-testing` module result in test failure due to `before` / `after` method hooks only possessing a single argument for the callback function, rather than two as in the case of `describe` or `it` methods.

Lack of support for descriptions results in hook failure being difficult to debug.

Looking at the source, this appears to be a pretty simple fix -

Was there a reason for this change or would you consider a pull request to bring these hooks in line with the other mocha hooks?

**Comment by jleyba** [comment]
The mocha hook wrappers are no longer necessary and were removed from the `selenium-webdriver/testing` module in 294d434c200040afe219f40cb6310ac9871c2b79
