### ISSUE TITLE
Unable to execute a javascript in ie8 though it is working in ie11

### ISSUE THREAD

**Issue by NikitaS1609** [SeleniumHQ/selenium#402]
Hi,
I have a following script which works fine in ie11 but fails to execute in ie8 with the following error

org.openqa.selenium.WebDriverException: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 85 milliseconds
Build info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:11:15'
System info: host: 'INMUCHPC03860', ip: '10.3.64.114', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_51'
Session ID: 49a59451-2f10-4798-a2fd-9ddcacd78add
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=8, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:20265/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)

Below is the code

public String getAbsoluteXPath(WebElement element, WebDriver driver) throws Exception
	{	
		return (String) ((JavascriptExecutor) driver).executeScript(
				"function absoluteXPath(element) {"+
				"var comp, comps = [];"+
				"var parent = null;"+
				"var xpath = '';"+
				"var getPos = function(element) {"+
				"var position = 1, curNode;"+
				"if (element.nodeType == Node.ATTRIBUTE_NODE) {"+
				"return null;"+
				"}"+
				"for (curNode = element.previousSibling; curNode; curNode = curNode.previousSibling) {"+
				"if (curNode.nodeName == element.nodeName) {"+
				"++position;"+
				"}"+
				"}"+
				"return position;"+
				"};"+
				"if (element instanceof Document) {"+
				"return '/';"+
				"}"+

				"for (; element && !(element instanceof Document) ; element = element.nodeType == Node.ATTRIBUTE_NODE ? element.ownerElement : element.parentNode) {"+
				"comp = comps[comps.length] = {};"+
				"switch (element.nodeType) {"+
				"case Node.TEXT_NODE:"+
				"comp.name = 'text()';"+
				"break;"+
				"case Node.ATTRIBUTE_NODE:"+
				"comp.name = '@' + element.nodeName;"+
				"break;"+
				"case Node.PROCESSING_INSTRUCTION_NODE:"+
				"comp.name = 'processing-instruction()';"+
				"break;"+
				"case Node.COMMENT_NODE:"+
				"comp.name = 'comment()';"+
				"break;"+
				"case Node.ELEMENT_NODE:"+
				"comp.name = element.nodeName;"+
				"break;"+
				"}"+
				"comp.position = getPos(element);"+
				"}"+

				"for (var i = comps.length - 1; i >= 0; i--) {"+
				"comp = comps[i];"+
				"xpath += '/' + comp.name.toLowerCase();"+
				"if (comp.position !== null) {"+
				"xpath += '[' + comp.position + ']';"+
				"}"+
				"}"+

				"return xpath;"+

				"} return absoluteXPath(arguments[0]);", element);
	}

Can you please help me with this?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
