### ISSUE TITLE
Findbys does not work properly

### ISSUE THREAD

**Issue by sapnasharma1806** [SeleniumHQ/selenium#4020]
## Meta -
OS:  
Windows 10

Selenium Version:  
<!-- 2.53.1, Webdriver>

TestNG: Version 6.11

Browser Version:  
Chrome: Version 58.0.3029.110

## Steps to reproduce -
Find user name text box on ParaBank home page
URL: http://parabank.parasoft.com

@FindBys({
    @FindBy(how = How.NAME, using = "username"),
    @FindBy(how = How.CLASS_NAME, using = "input")
})

it will return zero element

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
