### ISSUE TITLE
resizing causes display bugs

### ISSUE THREAD

**Issue by MaxPleaner** [SeleniumHQ/selenium#4021]
## Meta -
OS:  
**Ubuntu 16.04**
Selenium Version:  
**3.4.0** ruby gem
Browser:  
**Chromedriver v 2.29**

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

-->

Browser Version:  
**Version 58.0.3029.96 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)**

## Expected Behavior -

In order to take a fullscreen screenshot I'm first resizing the page to it's width/height as determined
through javascript. After doing this I place a breakpoint, and notice that my desktop UI is buggy

## Actual Behavior -

![bug](https://cloud.githubusercontent.com/assets/5035719/26029026/8febac54-37e0-11e7-8f49-1a1fd1f3420c.gif)

## Steps to reproduce -

```rb
  def get_page_width
    driver.execute_script <<-JS
      return Math.max(
        document.body.scrollWidth,
        document.body.offsetWidth,
        document.documentElement.clientWidth,
        document.documentElement.scrollWidth,
        document.documentElement.offsetWidth
      );
    JS
  end

  def get_page_height
    driver.execute_script <<-JS
      return Math.max(
        document.body.scrollHeight,
        document.body.offsetHeight,
        document.documentElement.clientHeight,
        document.documentElement.scrollHeight,
        document.documentElement.offsetHeight
      );
    JS
  end

  def get_page_dimensions
    [get_page_width, get_page_height]
  end
```

I resize the page and take a full-screen screenshot like so:

```rb
driver.manage.window.resize_to(width + 100, height + 100)
driver.save_screenshot path
```

After doing this I place a breakpoint with `byebug`.

I also tried removing the `+ 100` from the width/height dimensions, but it has no effect. 

I can post this as a bug on Chromedriver's page but thought it might be worthwhile to post it here first, to see if there's some Selenium-specific advice.

**Comment by p0deje** [comment]
I actually do the same the thing and never have any problems with desktop. In any event, please log this to ChromeDriver bugtracker as Selenium has nothing to do with it.
