### ISSUE TITLE
Unable to set nativeEvents to false when using IEDriver 3.4.0

### ISSUE THREAD

**Issue by KentGu** [SeleniumHQ/selenium#4023]
## Meta -
OS:  Windows 7 64 bit
Selenium Version:  3.4.0
Browser:  Internet Explorer 11 64 bit
IEDriver Version: 3.4.0 (both 32bit and 64bit)

Steps:
- Set native events to false
capabilities.setCapability(CapabilityType.HAS_NATIVE_EVENTS, false);
- New an InternetExplorerDriver with the capabilities
new InternetExplorerDriver(capabilities);

Expected:
An IE launched with native events capability set to false.

Actual:
The native events capability is always true. It used to be worked on IEDriver V3.3.0, I guess it may because the nativeEvents capability doesn't warp to the sub-object "se:ieOptions". I can't use V3.3.0 since that version has some kind of issue on the pop-up inputting thing (Issue #3587)

**Comment by KentGu** [comment]
Does anybody have any ideas on this?

**Comment by barancev** [comment]
Is this issue still actual?

**Comment by KentGu** [comment]
It was fixed last year. Thank you for your help
