### ISSUE TITLE
unable to connect to Mozilla geckodriver 127.0.0.1:4444

### ISSUE THREAD

**Issue by devanshukumar1990** [SeleniumHQ/selenium#4031]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

Firefox version used is v38.0, Selenium-webdriver is 3.4.0 and capybara (2.14.0). I am trying to use aws_account_tutls gem of ruby to create aws account.

   def create
      logger.debug "Launching new browser."
      Watir::Browser.new(:firefox, :profile => set_firefox_profile)
    end

    private
    def set_firefox_profile
      profile = Selenium::WebDriver::Firefox::Profile.new

      if proxy
        proxy_settings.each do |k,v|
          profile["network.proxy.#{k}"] = v
        end
      end

## Expected Behavior -
Should return a string of account number created on AWS
## Actual Behavior -
unable to connect to Mozilla geckodriver 127.0.0.1:4444 error is thrown.

**Comment by devanshukumar1990** [comment]
Above issue is resolved

**Comment by devanshukumar1990** [comment]
Have changed the selenium webdriver to 2.53.4 and is resolved.

**Comment by derpartment** [comment]
I am getting this issue on Travis-CI using WATIR and running webdrivers-3.2.4.  Anyone else experiencing the same thing?

**Comment by akiikius** [comment]
I am getting the error below even with selenium-webdriver 2.53.4
 
<testcase classname="webdriver_test_spec" name="Test hioh website navigates hioh" file="./webdriver_test_spec.rb" time="20.208727"><failure message="unable to connect to Mozilla geckodriver 127.0.0.1:4444" type="Selenium::WebDriver::Error::WebDriverError">Failure/Error: app = AbstractPage.new(Selenium::WebDriver.for(:firefox))

Selenium::WebDriver::Error::WebDriverError:
  unable to connect to Mozilla geckodriver 127.0.0.1:4444
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/service.rb:142:in `connect_until_stable&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/service.rb:72:in `block in start&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/socket_lock.rb:39:in `locked&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/service.rb:69:in `start&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/marionette/driver.rb:42:in `initialize&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:52:in `for&apos;
/Users/internal/.rvm/gems/ruby-2.6.2/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver.rb:86:in `for&apos;
./webdriver_test_spec.rb:24:in `block (2 levels) in &lt;top (required)&gt;&apos;</failure></testcase>
</testsuite>
