### ISSUE TITLE
Selenium IDE recorded script does not fire oninput event

### ISSUE THREAD

**Issue by jk-1** [SeleniumHQ/selenium#4032]
## Meta -
OS:  Ubuntu 16.04

Selenium Version: Selenium IDE 2.9.1 

Browser:  Firefox

Browser Version:  53.0 (64-bit)

## Steps to reproduce -

Start firefox
Install Selenium IDE add-on if needed
Open Selenium IDE
Goto https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_oninput
Start recording macro
Click and write string "abc" into the html input field on the right
During writing there will be text "You wrote: abc" under the field when oninput event is fired.
Press tab to move focus out of  html input field
Stop recording
Run recorded script. This time text abc appears in the html input field but below the field there is nothing because rerun does not fire oninput event.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
