### ISSUE TITLE
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

### ISSUE THREAD

**Issue by devanshukumar1990** [SeleniumHQ/selenium#4033]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

Firefox version used is v45.0, Selenium-webdriver is 2.53.4 and capybara (2.14.0). I am trying to use aws_account_utils gem of ruby to create aws account.

I am not sure what is being missed as I am not able to resolve it.

def create
      logger.debug "Launching new browser."
      Watir::Browser.new(:firefox, :profile => set_firefox_profile)
    end

    private
    def set_firefox_profile
      profile = Selenium::WebDriver::Firefox::Profile.new

      if proxy
        proxy_settings.each do |k,v|
          profile["network.proxy.#{k}"] = v
        end
      end

      profile['browser.privatebrowsing.dont_prompt_on_enter'] = true
      profile['browser.privatebrowsing.autostart'] = true
      profile.native_events = false
      profile
    end

## Expected Behavior -
Should return a string of account number created on AWS
## Actual Behavior -
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

**Comment by lmtierney** [comment]
Can you recreate this with just selenium code (not using capybara) and provide a stack trace with `$DEBUG = true` set beforehand?

**Comment by devanshukumar1990** [comment]
@lmtierney  - Thank you for your response. However I am new here and looking to implement aws account utils from here - https://github.com/intuit/aws_account_utils

I am calling it from Ruby code as suggested and not from Selenium code. Page where the browser gets initialized is : 

require 'aws_account_utils/base'
require 'watir-webdriver'
Watir::HTMLElement.attributes << :ng_model
Watir::HTMLElement.attributes << :ng_click

module AwsAccountUtils
  class WatirBrowser
    attr_reader :logger

    def initialize(logger)
      @logger  = logger
    end

    def create
      logger.debug "Launching new browser."
      Watir::Browser.new(:firefox, :profile => set_firefox_profile)
    end

    private
    def set_firefox_profile
      profile = Selenium::WebDriver::Firefox::Profile.new

      if proxy
        proxy_settings.each do |k,v|
          profile["network.proxy.#{k}"] = v
        end
      end

      profile['browser.privatebrowsing.dont_prompt_on_enter'] = true
      profile['browser.privatebrowsing.autostart'] = true
      profile.native_events = false
      profile
    end

    def proxy_settings
      {
          'http'          => proxy,
          'http_port'     => proxy_port,
          'ssl'           => proxy,
          'ssl_port'      => proxy_port,
          'no_proxies_on' => '127.0.0.1',
          'type'          => 1
      }
    end

    def proxy
      @proxy ||= ENV['AWS_ACCOUNT_UTILS_HTTP_PROXY']
    end

    def proxy_port
      @proxy_port ||= ENV['AWS_ACCOUNT_UTILS_HTTP_PROXY_PORT']
    end
  end
end

==============
 
I don't think code is actually using Capybara. Kindly suggest what can I provide more ?

**Comment by lmtierney** [comment]
Hmm well so you're using Watir then. Can you still set `$DEBUG = true` before instantiating the browser and provide the stack? Selenium `2.54` and `watir-webdriver` are all older versions so you may consider upgrading. Is there a reason you're trying to use a pretty old version of firefox too?

**Comment by devanshukumar1990** [comment]
@lmtierney - I am using lib as mentioned on https://github.com/intuit/aws_account_utils

So if u check file - https://github.com/intuit/aws_account_utils/blob/master/lib/aws_account_utils/watir_browser.rb

It is using watir browser. As for Selenium web driver I used version 3.0.4 too still same response. I have referenced other threads on google like http://stackoverflow.com/questions/14303161/unable-to-obtain-stable-firefox-connection-in-60-seconds-127-0-0-17055 where they suggested to downgrade Selenium-webdriver and Firefox version so I went to try the same, still getting same response at my end.

**Comment by devanshukumar1990** [comment]
@lmtierney - Here is the full trace below. Please check and advise.

Selenium::WebDriver::Error::WebDriverError in CloudProvidersController#create_aws_account
unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

Extracted source (around line #277):
              
                      'guess'        => 'Test Account Dev' }

        resp = aws_utils.create_account(account_name: 'My Test Account Devanshu Kumar',
                                        account_email: 'devanshu.kumar@abc.com',
                                        account_password: 'XYZ',
                                        account_details: details)

Extracted source (around line #156):
              
    def run!
      if self.class.commands.include?(@command)
        run_command
      elsif @command.nil?
        puts "Command required"
        puts @parser

Rails.root: /home/infiverve/controlpanel/controlpanel3.1

Full Trace : 
selenium-webdriver (2.53.4) lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable'
selenium-webdriver (2.53.4) lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
selenium-webdriver (2.53.4) lib/selenium/webdriver/common/socket_lock.rb:43:in `locked'
selenium-webdriver (2.53.4) lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
selenium-webdriver (2.53.4) lib/selenium/webdriver/firefox/bridge.rb:43:in `initialize'
selenium-webdriver (2.53.4) lib/selenium/webdriver/common/driver.rb:53:in `new'
selenium-webdriver (2.53.4) lib/selenium/webdriver/common/driver.rb:53:in `for'
selenium-webdriver (2.53.4) lib/selenium/webdriver.rb:84:in `for'
watir-webdriver (0.9.9) lib/watir-webdriver/browser.rb:46:in `initialize'
aws_account_utils (0.1.4) lib/aws_account_utils/watir_browser.rb:16:in `new'
aws_account_utils (0.1.4) lib/aws_account_utils/watir_browser.rb:16:in `create'
aws_account_utils (0.1.4) lib/aws_account_utils.rb:181:in `browser'
aws_account_utils (0.1.4) lib/aws_account_utils.rb:169:in `account_registration'
aws_account_utils (0.1.4) lib/aws_account_utils.rb:34:in `create_account'
app/controllers/cloud_providers_controller.rb:277:in `create_aws_account'
actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
rack (1.6.8) lib/rack/etag.rb:24:in `call'
rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.8) lib/rack/head.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.8) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.8) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.2.3) lib/eventmachine.rb:194:in `run_machine'
eventmachine (1.2.3) lib/eventmachine.rb:194:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
thin (1.6.3) lib/thin/controllers/controller.rb:87:in `start'
thin (1.6.3) lib/thin/runner.rb:200:in `run_command'
thin (1.6.3) lib/thin/runner.rb:156:in `run!'
thin (1.6.3) bin/thin:6:in `<top (required)>'
/home/infiverve/.rvm/gems/ruby-2.2.0/bin/thin:23:in `load'
/home/infiverve/.rvm/gems/ruby-2.2.0/bin/thin:23:in `<main>'
/home/infiverve/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/infiverve/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by lmtierney** [comment]
I am able to open Firefox 45 with selenium 2.53.4. Can you try this code and see if it works for you?

```
require "selenium-webdriver"
Selenium::WebDriver::Firefox.path = '<path to Firefox45 bin if multiple are installed>'
driver = Selenium::WebDriver.for(:firefox)
```

**Comment by devanshukumar1990** [comment]
@lmtierney - Ok. Thanks just checking it and will let you know.

**Comment by devanshukumar1990** [comment]
@lmtierney - My code is now as follows : 
==========================

require 'aws_account_utils/base'
require 'watir-webdriver'
require "selenium-webdriver"
Watir::HTMLElement.attributes << :ng_model
Watir::HTMLElement.attributes << :ng_click

module AwsAccountUtils
  class WatirBrowser
    attr_reader :logger

    def initialize(logger)
      @logger  = logger
    end

    def create
      logger.debug "Launching new browser."
      Watir::Browser.new(:firefox, :profile => set_firefox_profile)
    end

    private
    def set_firefox_profile
      #profile = Selenium::WebDriver::Firefox::Profile.new
      Selenium::WebDriver::Firefox.path = '/usr/bin/firefox'
      profile = Selenium::WebDriver.for(:firefox)

      if proxy
        proxy_settings.each do |k,v|
          profile["network.proxy.#{k}"] = v
        end
      end

      profile['browser.privatebrowsing.dont_prompt_on_enter'] = true
      profile['browser.privatebrowsing.autostart'] = true
      profile.native_events = false
      profile
    end

    def proxy_settings
      {
          'http'          => proxy,
          'http_port'     => proxy_port,
          'ssl'           => proxy,
          'ssl_port'      => proxy_port,
          'no_proxies_on' => '127.0.0.1',
          'type'          => 1
      }
    end

    def proxy
      @proxy ||= ENV['AWS_ACCOUNT_UTILS_HTTP_PROXY']
    end

    def proxy_port
      @proxy_port ||= ENV['AWS_ACCOUNT_UTILS_HTTP_PROXY_PORT']
    end
  end
end
===================
Please check and advise as I am still getting same error.

**Comment by lmtierney** [comment]
Please try ONLY the code I provided. You added it to your code and your code still has Watir starting a browser separately so I would expect it to still error

**Comment by devanshukumar1990** [comment]
@lmtierney  - I have made the changes as suggested by you. Please check below : 

===========================

require 'aws_account_utils/base'
#require 'watir-webdriver'
require "selenium-webdriver"
Watir::HTMLElement.attributes << :ng_model
Watir::HTMLElement.attributes << :ng_click

module AwsAccountUtils
  class WatirBrowser
    attr_reader :logger

    def initialize(logger)
      @logger  = logger
    end

    def create
      logger.debug "Launching new browser."
      #Watir::Browser.new(:firefox, :profile => set_firefox_profile)
      Selenium::WebDriver::Firefox.path = '/usr/bin/firefox'
      driver = Selenium::WebDriver.for(:firefox)
    end
==========================

I am still getting the same response.

**Comment by lmtierney** [comment]
That means there is something wrong with your environment then. It could be that it is trying to hit the wrong firefox version or that there is no display available to start the browser in (like xfvb). I'm closing this as it can not be reproduced outside your environment.
