### ISSUE TITLE
Local storage cannot be deactivated in chrome

### ISSUE THREAD

**Issue by Fishkob** [SeleniumHQ/selenium#4034]
## Meta -
OS:  ubuntu: 16.04

Selenium Version:  3.4.0

Chrome Driver Version: 2.29

Browser:  Chrome

Browser Version:  58.0.3029.81 (64-bit)

## Expected Behavior -
Tryin to disable local storage in Chrome Browser, which is available under:

chrome://settings/content
Radiobox: Block sites from setting any data
 

## Actual Behavior -
The Radiobox is not active and local storage still enabled

## Steps to reproduce -
First try 
`
ChromeOptions options = new ChromeOptions();
options.addArguments("--disable-local-storage");
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability(ChromeOptions.CAPABILITY,options);
WebDriver driverChrome = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"),capabilities);
`
Second try
`
preferences.put("profile.default_content_settings.cookies",2);
options.setExperimentalOption("prefs", preferences);
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability(ChromeOptions.CAPABILITY,options);
WebDriver driverChrome = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), capabilities);
`

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
