### ISSUE TITLE
Wrong Platform returned in Capabilities for .NET RemoteWebDriver with Windows Server 2012

### ISSUE THREAD

**Issue by InkUisitor** [SeleniumHQ/selenium#4037]
## Meta -
OS:  Win Server 2012
Selenium Version:  3.4.0
Browser:  All --> Chrome, PhantomJS, ...
Browser Version:  

## Expected Behavior -
Returned value must be a Windows like enum

## Actual Behavior -
Doesn't retrieve the platform on Windows Server 2012 with .NET WebDriver using remote Selenium Grid.
The capability returned is Any and not a Windows like enum

## Steps to correct -
You must add the enum "Win8_1 = Windows," in PlatformType. I don't know what you must do for the others drivers or if it's just a missing value in .NET WebDriver

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
