### ISSUE TITLE
Support for self-signed cryptographic modules in FirefoxDriver

### ISSUE THREAD

**Issue by julianmz** [SeleniumHQ/selenium#404]
##### Which steps will reproduce the problem?

Load webdriver.xpi and use firefox's "Cryptographic-Module-Manager" to load
the PKCS#11 module of your choice (I used my company's internal one). Insert a smartcard
and try to do a login by using Cryptographic-Module-Manager's "Log In"-option. 
##### What is expected?

After clicking the "Log In"-button it is expected that a dialog shows up which asks the user for 
the smartcard's master-password. 
##### What do you see instead?

A messagebox gets spawned immediatly telling the user that the log-in has failed even though the 
user had no chance to type in a password.
##### Additional information:

Selenium version: 2.45
OS: Windows 7 x86 Service Pack 1
Browser: Firefox
Browser version: 36.0.4

One could say now that there probably is a problem with firefox or the PKCS#11-module but I am convinced that this is not the case since:

1.) It works without any problems if webdriver.xpi is not loaded
2.) Editing the "fxdriver.modals.signalOpenModal"-function in prompt-service.js in such way,
    that it returns before "fxdriver.modals.findAssociatedDriver" gets called if its first parameter equals
    "null" seems to fix the problem.

**Comment by barancev** [comment]
This feature will never be implemented in "legacy" FirefoxDriver. If it's still worth to consider please raise an issue in geckodriver tracker: https://github.com/mozilla/geckodriver/issues
