### ISSUE TITLE
Exception is not thrown when chrome browser becomes unresponsive

### ISSUE THREAD

**Issue by RajAsapu** [SeleniumHQ/selenium#4040]
Environment : 

Chrome version : Version 58.0.3029.96 unknown (64-bit)
Chrome web driver version : 2.27
Operating System : ubuntu 16.04 LTS
Selenium version : 3.4.0
Selenium java version: 3.4.0

Steps to reproduce:
1. Run selenium test script multiple times(Assuming all the preconditions are defined).

Expected Result:
The test should open the browser and run the test and if the browser becomes unresponsive after some time the selenium should throw an exception.

Actual Result:
The browser becomes unresponsive displaying error message as "This window is not responding" and the selenium waits for ever and it doesn't display any error message.
![error](https://cloud.githubusercontent.com/assets/18503263/26211602/dbd27628-3bc0-11e7-9c48-c5ce55f7660a.JPG)

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
