### ISSUE TITLE
[Important] : Can't locate any web elements on a web page !!!

### ISSUE THREAD

**Issue by aharrim** [SeleniumHQ/selenium#4047]
This Issue happens on multiple driver , Firefox , IE and chrome !!!
Weirdly enough , other products web pages are working fine but this page specifically , selenium seems not able to locate items or i'm doing something wrong , not totally sure !

Using C#.net , here's the code : 

using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System;
using System.Threading;

namespace LocalSeleniumExample
{
    [TestFixture]
    public class LocalTest
    {
        private IWebDriver driver;
        private WebDriverWait wait;

        [SetUp]
        public void Initialize()
        {
            driver = new ChromeDriver();
            wait = new WebDriverWait(driver, new TimeSpan(0, 0, 5));
        }

        [Test]
        public void Login()
        {
            /*// Arrange
          
            driver.Navigate().GoToUrl("https://commerce.spscommerce.com");

            var waitableDriver = new WebDriverWait(driver, TimeSpan.FromSeconds(30));

            waitableDriver.Until(d => driver.FindElement(By.Id("username")));

            Thread.Sleep(6000);
            IWebElement emailElement = driver.FindElement(By.Id("username"));
            emailElement.SendKeys("retaileruiuser@gmail.com");

        }

        [TearDown]
        public void EndTest()
        {
            driver.Close();
        }
    }
}

I tried adding a wait , I tried adding thread.sleep and keep changing the locaters but not sure why the driver can't locate any web elements in "https://commerce.spscommerce.com" . I would really appreciate your help !!!

Thanks,
Regards,

**Comment by lmtierney** [comment]
The elements are inside an iFrame, you need to [switch to that first](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/server/handler/SwitchToFrame.html).

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
