### ISSUE TITLE
IE Driver Server does not use the right protected mode settings

### ISSUE THREAD

**Issue by essenius** [SeleniumHQ/selenium#4048]
## Meta -
OS:  Windows 7
Selenium Version:  Webdriver 3.4 (C#) and IEDriverServer 3.4
Browser:  Internet Explorer
Browser Version:  11.0.9600.18638

Related to https://github.com/SeleniumHQ/selenium/issues/919 

## Expected Behavior -
IEDriverServer should determine the used Protected Mode settings in the same way that IE itself does it, which is examining (in order of searching):

- HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones
- HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones
- HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones
- HKLM\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones

If IE finds the setting at a certain location, it doesn't look further. This is e.g. to allow policies to override local settings, which happens a lot in corporate environments. 

## Actual Behavior -
IEDriverServer only examines HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones

## Steps to reproduce -
Add DWORDS 1\2500, 2\2500, 3\2500 and 4\2500 under  HKCU\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones and give them all value 3. 
Make the same entries under HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones a combination of values 3 and 0.

Now IE uses the same protected mode settings for all zones, as it uses the values under the Policies tree, but the constructor for InternetExplorerDriver throws an OpenQA.Selenium.WebDriverException: 'Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.'

**Comment by harveymonster** [comment]
There is also an option to only use HKLM values and to ignore HKCU values.

> If the Security Zones: Use only machine settings setting in Group Policy is enabled, or if the Security_HKLM_only DWORD value is present and has a value of 1 in the following registry subkey, only local computer settings are used and all users have the same security settings:
HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
With the Security_HKLM_only policy enabled, HKLM values will be used by Internet Explorer. 

_(Taken from https://support.microsoft.com/en-us/help/182569/internet-explorer-security-zones-registry-entries-for-advanced-users)_

**Comment by barancev** [comment]
Is this issue still actual?

**Comment by harveymonster** [comment]
@barancev, in the browser factory, the function that checks if the protected mode settings are valid still only checks HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Zones, and so this is still an actual issue because the selenium code isn't properly checking the settings of Internet Explorer. The comment on this function even links to the Microsoft KnowledgeBase article that discusses how the different registry location and values are used to determine the final settings that IE uses (http://support.microsoft.com/kb/182569). 

Here is a link to the function I'm talking about:
https://github.com/SeleniumHQ/selenium/blob/83b2736806139c3a5ebe5f4b883422ed64b157d0/cpp/iedriver/BrowserFactory.cpp#L1098.

**Comment by barancev** [comment]
OK, thank you for explanation.

**Comment by diemol** [comment]
We really do not have the bandwidth right now to tackle this issue. If anyone feels like sending us a PR that includes some tests and proper documentation, we would be happy to collaborate with you.
