### ISSUE TITLE
"KLIB_SelfTest return : KLR_OK"

### ISSUE THREAD

**Issue by khj809** [SeleniumHQ/selenium#4051]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.1 (latest)

Browser:  Chrome

Browser Version:  2.29 (latest)

## Expected Behavior -
Run Chrome driver without any console output (I mean Windows cmd, not browser console)
## Actual Behavior -
In cmd, it prints weird log as below:
`KLIB_SelfTest return : KLR_OK`
I want this log (or any other logs) not to be printed.

## Steps to reproduce -

Just run Chrome web driver in Windows 10

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)
