### ISSUE TITLE
Which version of selenium 3.x.x is stable to work with which version of Gecko driver and firefox ?

### ISSUE THREAD

**Issue by xikandar** [SeleniumHQ/selenium#4056]
**Which version of selenium 3.x.x is stable to work with which version of Gecko driver and Firefox ?**

Kindly help, I am learning selenium and automating a project. I want to know a stable versions detail so that I can work with minimum hurdles... 

Sorry for asking this question in ISSUES section, I couldn't find any better place to ask for help :(

**Comment by MonsterMMORPG** [comment]
i am using chrome and c#

i can tell that it is not very stable. when exception happens, it doesnt work anymore

also you cant even close it properly

https://github.com/SeleniumHQ/selenium/issues/4054

**Comment by AutomatedTester** [comment]
@MonsterMMORPG your issue is not related.

**Comment by AutomatedTester** [comment]
@xikandar Latest Selenium, GeckoDriver and Firefox are the only supported versions.

**Comment by xikandar** [comment]
@AutomatedTester  so you recommend I use all 3 latest versions. I hope this set of latest items would help me in smooth automation instead of others in finding latest bugs :P

**Comment by AutomatedTester** [comment]
@xikandar it's just the same requirements as if you are using ChromeDriver :)

**Comment by xikandar** [comment]
I would mainly rely on Firefox.
