### ISSUE TITLE
error on running scripts in IDE 2.9.1

### ISSUE THREAD

**Issue by bhagatashish** [SeleniumHQ/selenium#4058]
## Meta -
OS:  Windows 7

Selenium Version:  2.9.1
Browser:  
Firefox?

Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Any issue logged here for Firefox 48 or later will be closed as a duplicate of
#2559. Our recommendation is to switch to GeckoDriver, or to continue testing
on Firefox 45 until GeckoDriver is a viable option for you. If you are
interested in helping us to sign the add-on to restore support for later
Firefox versions, please see the following comment for what's needed:
https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

Browser Version:  45.8.0

## Steps to reproduce -
Ran the below script 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="https://l8sida05:9801/" />
<title>Create Structure</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">Create Structure</td></tr>
</thead><tbody>
<tr>
	<td>pause</td>
	<td>20000</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=_160_groupSelectorButton</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>

<tr>
	<td>click</td>
	<td>//*[contains(@role,'menuitem') and normalize-space()='Global']</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//a[contains(.,'Web Content')]</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//a[contains(.,'Structures')]</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>//input[@class ='aui-button-input' and @value='Add Structure']</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>

<tr>
	<td>type</td>
	<td>id=_15_newStructureId</td>
	<td>SCN_AUTO_CM_01_STRC_intg1</td>
</tr>
<tr>
	<td>click</td>
	<td>id=_15_newStructureId</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>id=_15_name_en_US</td>
	<td>SCN_AUTO_CM_01_STRC_intg1</td>
</tr>
<tr>
	<td>type</td>
	<td>id=_15_description_en_US</td>
	<td>SCN_AUTO_CM_01_STRC_intg1</td>
</tr>

<tr>
	<td>click</td>
	<td>//input[@class ='aui-button-input' and @value='Launch Editor']</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=_15_plainEditorField</td>
	<td></td>
</tr>

<tr>
	<td>selectFrame</td>
	<td>id=_15_xsdContentIFrame</td>
	<td></td>
</tr>
<tr>
	<td>select</td>
	<td>//*[@id='_15_editorType']</td>
	<td>Plain</td>
</tr>
<tr>
	<td>type</td>
	<td>id=_15_plainEditorField</td>
	<td>&lt;?xml version=&quot;1.0&quot;?&gt;<br /><br />&lt;root&gt;<br /> &lt;dynamic-element name=&quot;Content&quot; type=&quot;text_area&quot; index-type=&quot;&quot; repeatable=&quot;false&quot;/&gt;<br />&lt;/root&gt;</td>
</tr>
<tr>
	<td>click</td>
	<td>id=_15_update-button</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>10000</td>
	<td></td>
</tr>
<tr>
	<td>selectWindow</td>
	<td></td>
	<td>Web Content - UPOINT</td>
</tr>

<tr>
	<td>click</td>
	<td>//input[@class ='aui-button-input' and @value='Save and Continue']</td>
	<td></td>
</tr>
<tr>
	<td>pause</td>
	<td>15000</td>
	<td></td>
</tr>

<tr>
	<td>captureEntirePageScreenshot</td>
	<td>C:\Selenium Screenshots\SCN_1_Create_Strc.png</td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>
2. After running the above script Selenium IDe is thorwing an error message as : testCase.debugContext.currentCommand(...) is undefined and it didn't run the script further

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
