### ISSUE TITLE
License issue: GPL code in deps

### ISSUE THREAD

**Issue by ChALkeR** [SeleniumHQ/selenium#4059]
This project is licensed under Apache License 2.0, but it depends on GPL code.

To reproduce: switch to a clean directory, `npm i selenium-webdriver`.

File `node_modules/adm-zip/methods/deflater.js` has the following header:
```
/*
 * $Id: rawdeflate.js,v 0.5 2013/04/09 14:25:38 dankogai Exp dankogai $
 *
 * GNU General Public License, version 2 (GPL-2.0)
 *   http://opensource.org/licenses/GPL-2.0
 * Original:
 *  http://www.onicos.com/staff/iz/amuse/javascript/expert/deflate.txt
 */
```

It looks used (at least it is `require`-d).

```
firefox/profile.js:const AdmZip = require('adm-zip'),
firefox/extension.js:const AdmZip = require('adm-zip'),
remote/index.js:const AdmZip = require('adm-zip');
```
which in turn requires `deflater.js` upon require.

See https://www.apache.org/licenses/GPL-compatibility.html:
> This **licensing incompatibility applies only when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3**. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.
> We avoid GPLv3 software because **merely linking to it is considered by the GPLv3 authors to create a derivative work**. We want to honor their license. Unless GPLv3 licensors relax this interpretation of their own license regarding linking, our licensing philosophies are fundamentally incompatible. **This is an identical issue for both GPLv2 and GPLv3.**

Upstream issue is https://github.com/cthackers/adm-zip/issues/77, but the adm-zip project looks dead, so it's not likely to be resolved there.

Similar issues in other projects: https://github.com/Medium/phantomjs/issues/495, https://github.com/giggio/node-chromedriver/issues/102.

**Comment by cgoldberg** [comment]
it looks pretty trivial to replace adm-zip with extract-zip to deal with this issue.  here is the PR that phantomjs-prebuilt used to handle the same change:
https://github.com/Medium/phantomjs/pull/497/files
