### ISSUE TITLE
IE11 issue with child window

### ISSUE THREAD

**Issue by Tuktuk2017** [SeleniumHQ/selenium#4061]
We are having an issue with handling child window in IE11 .We are not able to select anything in the child window. This is working all right with chrome. On further verification we saw GetAllWindowHandles returning 1,which is returning 2 when ran in Chrome. As par the Browser Security setting for IE11 is concerned, Enable Protected Mode is not checked or unchecked for IE11.This is as par default policy of our company and we cant change the settings.
 Just to update we are using IE driver 3.4.0 version
<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-ie-driver</artifactId>
			<version>3.4.0</version>
		</dependency>
		<dependency>

Attached is the Security Settings for IE11.Please let me know if any other information is required.
 Also attached is the screenshot of the Parent & Child Window.
[IE11 Security Settings.docx](https://github.com/SeleniumHQ/selenium/files/1020104/IE11.Security.Settings.docx)

**Comment by AutomatedTester** [comment]
I can't open the docx file, nor do I want to because who knows what is in it...


For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Vignesh-Venkatraman** [comment]
@Tuktuk2017 . Me to facing the same issue. Please update how you resolved the issue. It will be very helpful for me. Thnks in Advance

**Comment by Tuktuk2017** [comment]
We made changes in IE security settings.Enable protected mode should be
same for all security Zone
