### ISSUE TITLE
clicking on element in GWT tree view does not work

### ISSUE THREAD

**Issue by chris-hawley** [SeleniumHQ/selenium#4063]
I can't give access to the test site but here is the code that I am using. Also, the HTML of the element is copied below. 

```
 we = driver.findElement(By.xpath("//div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div"));
 int width = we.getSize().getWidth();
 action.moveToElement(we, width/2, 9).click().build().perform();

```

`<div style="display: inline; background-color: rgb(255, 179, 0);" class="gwt-TreeItem gwt-TreeItem-selected" role="treeitem" id="gwt-uid-102" aria-level="9" aria-setsize="4" aria-posinset="1" aria-selected="true">`

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by chris-hawley** [comment]
I'm going to set you up with a dummy account to a demo version of the webapp. Let me know how you want to credentials sent.

**Comment by lmtierney** [comment]
I do not have time to do that.

Since we don't know that this is an issue yet, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). Maybe someone has time to work with your dummy account.
