### ISSUE TITLE
Logs and extensions not available in Firefox 53.0.3 & Selenium 3.4.0

### ISSUE THREAD

**Issue by kabilanvk** [SeleniumHQ/selenium#4066]
## Meta -
OS:  Windows 10 Enterprise 64bit

Selenium Version:  3.4.0 .Net Driver

Browser:  Mozilla Firefox 53.0.3

Browser Version:  53.0.3 (32bit)

## Expected Behavior -
Extensions loaded during startup i.e. Firebug,Modify Header
Driver logs should be available

## Actual Behavior -
No extensions loaded i.e. Firebug,Modify Header
No driver logs available to troubleshoot

## Steps to reproduce -
1. Installing new FF 53.0.3
2. Start Webdriver with GeckoDriver 0.16.1 (x32)

**Comment by AutomatedTester** [comment]
Each session starts with a new session, you will need to use the Firefox Profile APIs to install the relevant extensions.
