### ISSUE TITLE
NoSuchDriverError on MAC

### ISSUE THREAD

**Issue by idgm81** [SeleniumHQ/selenium#4068]
Hi all,

I have problems with last chromedriver version 2.29 running test with ruby on MAC and Chrome > v57. Output error:

  no such session
 (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.5 x86_64) (Selenium::WebDriver::Error::NoSuchDriverError)

selenium-webdriver gem installed is 3.4.0

Thanks in advance!

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
