### ISSUE TITLE
Safari 10.3 Not getting Maximised (Selenium)

### ISSUE THREAD

**Issue by ikarrthik** [SeleniumHQ/selenium#4069]
## Meta -
OS:  Mac Seirra

Selenium Version:  3.0 Appium 1.6.4

Browser:  
<Safari 10.3>

The Safari browser is not getting maximized or full screen in the newer safari browser version 10.3 whereas the same script runs with a full screen in 10.1. Tried with the window.max() in the driver capabilities but still no use. Is there any workaround for this issue

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/
