### ISSUE TITLE
i am unable to connect in chrome using selenium web driver

### ISSUE THREAD

**Issue by 158w5a0532** [SeleniumHQ/selenium#4071]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
