### ISSUE TITLE
Chromedriver 2.29 giving error for latest chrome 58.0.3029.110 on my ubuntu. 'session not created exception'

### ISSUE THREAD

**Issue by umeshnevase** [SeleniumHQ/selenium#4076]
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  selenium-server-standalone-3.4.0

Browser:  Chrome 58.0.3029.110

Browser Version:

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
