### ISSUE TITLE
[Feature Request] PageFactory support for nested Page Objects

### ISSUE THREAD

**Issue by TinyCamera** [SeleniumHQ/selenium#4077]
Using a custom FieldDecorator, I can get PageFactory to populate nested PageObjects that are themselves annotated with FindBy

e.g. 

```
public class GooglePage {

	@FindBy(name = "q")
	WebElement search;

	@FindBy(css="#res .g")
	List<GoogleSearchItem> searchItems;
	
	public WebElement getSearch() {
		return search;
	}

	public List<GoogleSearchItem> getSearchItems() {
		return searchItems;
	}

}
```
```
public class GoogleSearchItem {

	@FindBy(css=".r a")
	WebElement title;

	@FindBy(className="st")
	WebElement description;

	public WebElement getTitle() {
		return title;
	}

	public WebElement getDescription() {
		return description;
	}

}

```

In this example, initialising the elements in `GooglePage` will recursively initialise the elements for `GoogleSearchItem`. I think this is a very powerful design pattern and is considered best practice within my organisation. 

I think this should be the default behaviour of the PageFactory, more specifically, of `DefaultFieldDecorator`. 

I'd be happy to do the work but I just wanted to hear from others first - is there good reason to not have this feature?

**Comment by dnekhayev** [comment]
Such functionality is implemented in HtmlElements framework. Have you seen it?

**Comment by diemol** [comment]
Exactly, please check https://github.com/yandex-qatools/htmlelements or https://github.com/qameta/atlas for this functionality.

No extense changes will be implemented to the `PageFactory` to keep it backwards compatible and maintainable.
