### ISSUE TITLE
"storedVars is not defined" error when run HTML test suite in Selenium HTML Runner

### ISSUE THREAD

**Issue by intruder777** [SeleniumHQ/selenium#4079]
## Meta -
OS:  Windows 7 SP1 x64
Selenium Version:  selenium-server-standalone-3.4.0, selenium-html-runner-3.4.0, Selenium IDE 2.9.1.1
Browser:  Firefox
Browser Version:  51.0.1 (32-bit)

## Expected Behavior -
Selenium HTML Runner must support storedVars object in storeEval and runScript commands.

## Actual Behavior -
Any HTML test which accesses storedVars object fails  with the following error when run through Selenium HTML Runner:
com.thoughtworks.selenium.SeleniumException: ReferenceError: storedVars is not defined

## Steps to reproduce -
1. Run Suite_storedVars2.html test suite in Firefox Selenium IDE plugin - no errors, test is successful.

2. Run selenium standalone:
java -jar selenium-server-standalone-3.4.0.jar

3. Run Suite_storedVars2.html test suite in selenium html runner:
java -jar selenium-html-runner-3.4.0.jar -timeout 1000 -htmlSuite "*firefox" "https://www.ibm.com/us-en/" "D:\SeleniumIDE\Suite_storedVars2.html" log1

4. Observe log1\firefox.results.html result file, which contains an error message:
com.thoughtworks.selenium.SeleniumException: ReferenceError: storedVars is not defined

Please find test suite Suite_storedVars2.txt (rename to .html) and test case Test_storedVars2.txt (rename to .html) files attached,
[Suite_storedVars2.txt](https://github.com/SeleniumHQ/selenium/files/1029228/Suite_storedVars2.txt)
[Test_storedVars2.txt](https://github.com/SeleniumHQ/selenium/files/1029231/Test_storedVars2.txt)

**Comment by jahblom** [comment]
Hi,

Any news on this?
I get the same exception when trying to access the storedVars using chromedriver.

_com.thoughtworks.selenium.SeleniumException: unknown error: storedVars is not defined
  (Session info: chrome=59.0.3071.109)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.14393 x86_64)_

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
