### ISSUE TITLE
Click is not working for FF 31 and chrome 32

### ISSUE THREAD

**Issue by Snehashree** [SeleniumHQ/selenium#408]
web driver click is not working in firefox version 31  and chrome 32. 
Click is working for Firefox version 24
EXPECTED: Webdriver to click the link in Chrome ,FF

ACTUAL:
System.InvalidOperationException : Element is not clickable at point (1444, 175)
Element is not clickable at point (1444, 175). Other element would receive the click: 
while in ff it is not even throwing any error. 

my code structure is like that 
<section> 
  <span> 
     <a id="anchorTagToClick"> 
        <span id="idToClick"> 
             link to click 
        </span> 
     </a> 
   </span>     
</section> 

Please let me know how can I fix this.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/).

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
