### ISSUE TITLE
Open intent URL with xdg-open on Ubuntu

### ISSUE THREAD

**Issue by lluisteamcmp** [SeleniumHQ/selenium#4080]
## Meta -
OS:  Linux 1b617851a909 4.9.27-moby 1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Selenium Version:  
3.4.0
Browser:  
Chrome

Browser Version:  
Version 58.0.3029.81 (64-bit)

## Expected Behavior -
On opening `intent` links, the driver could not lose access to the browser.

## Actual Behavior -
xdg-open tries to open such content from the URL and the driver stops working.

---

This is the trace of the error on trying a `driver.refresh` once the 'xdg-open' pops up:
```
objc[4481]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

org.openqa.selenium.TimeoutException: timeout
  (Session info: chrome=58.0.3029.81)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.9.27-moby x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 15.01 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '8889888d9c2b', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.27-moby', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5), userDataDir=/tmp/.org.chromium.Chromium.U0CuT5}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.81, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 02bfe2b83b3bd65900eb2a3293accddb
Command duration or timeout: 15.02 seconds
```

## Steps to reproduce -
Given starting a browser using this user agent: `"Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.114 Mobile Safari/537.36"`
When trying to open the next type of URL: `intent://stream/#Intent;scheme=freevr;package=[PACKAGE_NAME];S.stream=[STREAM_URL]`
Then the xdg-open 'alert' appears. That makes losing control over the driver, per example the driver is unable to do a navigate.refresh.

---

Here is a screenshot of the xdg-open pops up:
![image](https://cloud.githubusercontent.com/assets/28141920/26150263/f7e33b72-3afd-11e7-9904-47923f71555c.png)

---

Also I should comment that this is related to: https://github.com/SeleniumHQ/docker-selenium/issues/488

**Comment by AutomatedTester** [comment]
I suggest raising this with the ChromeDriver project. There is not much we can do to fix it.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by lluisteamcmp** [comment]
Reported in ChromeDriver: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1833
