### ISSUE TITLE
Webpack integration issue with selenium webdriver JS module

### ISSUE THREAD

**Issue by omkarmethe** [SeleniumHQ/selenium#4081]
I am trying to create the small UI test framework in javascript, our project is using webpack and planning to integrate this framework with the project. Hence imported 'selenium-webdriver' in the entry file of webpack.config.js
It is giving following error

```bash
ERROR in ./~/selenium-webdriver/net/portprober.js
Module not found: Error: Cannot resolve module 'child_process' in C:\Temp\Test\node_modules\selenium-webdriver\net
 @ ./~/selenium-webdriver/net/portprober.js 20:11-35

ERROR in ./~/selenium-webdriver/io/exec.js
Module not found: Error: Cannot resolve module 'child_process' in C:\Temp\Test\node_modules\selenium-webdriver\io
 @ ./~/selenium-webdriver/io/exec.js 20:21-45
```

**Comment by AutomatedTester** [comment]
looks like a webpack issue. you can get around it if you follow https://stackoverflow.com/questions/30000827/webpack-and-typescript-cannot-resolve-module-child-process-in-node-d-ts
