### ISSUE TITLE
Injecting more than one servlets to Selenium Hub

### ISSUE THREAD

**Issue by sahajamit** [SeleniumHQ/selenium#4085]
## Meta -
OS:  Windows 7
Selenium Version:  Selenium Grid 2.53.1
Browser:  chrome

## Expected Behavior -

As -servlets argument takes a list of string so ideally it should inject both the servlets.

## Actual Behavior -

It is only injecting the first servlet and ignoring the second one.

## Steps to reproduce -
I am trying to inject two servlets in to the Selenium Hub. I have followed all the instructions given at : http://www.seleniumhq.org/docs/07_selenium_grid.jsp

Hers is my command:   

"%JAVA_HOME%\bin\java" -cp "selenium-grid-utils-1.0-jar-with-dependencies.jar;selenium-server-standalone-2.53.1.jar" org.openqa.grid.selenium.GridLauncher -role hub -servlets com.sahajamit.selenium.grid.NodesInfoServlet -servlets com.sahajamit.selenium.grid.SeleniumConsole -port 4444 -browserTimeout 900000 -debug

This command successfully starts the hub but when I am trying to access my servlets than only the first servlet "NodesInfoServlet" is accessible and I am not able to access the second servlet "SeleniumConsole "

I tried to go to the selenium console at http://localhost:4444/grid/console?config=true&configDebug=true  and found that the second servlet was never injected. Here is the screenshot:

![grid-console](https://cloud.githubusercontent.com/assets/358319/26489857/a4744e1e-423b-11e7-886d-7e77303351e5.png)

**Comment by schmidtkp** [comment]
@sahajamit I attach multiple servlets to both my hub and nodes, but I do so via Java bindings and not from the command line. My guess is that you need to specify a single "-servlets" option with something like a quoted, comma separated list, argument to the "-servlets" option:

For example:

-servlets "com.sahajamit.selenium.grid.NodesInfoServlet,com.sahajamit.selenium.grid.SeleniumConsole"

But this is just a guess...

**Comment by LinuxSuRen** [comment]
why do not provider a ui for it, like this https://github.com/LinuxSuRen/phoenix.webui.server

**Comment by sahajamit** [comment]
Thanks @schmidtkp for your answer. I tried your suggestion but it didn't work. I have gone through the source code and found they are using JCommander to parse the command line arguments so ideally the way I am passing them should also work.

Please refer this:

https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/GridConfiguration.java#L86

As you said, for you it worked using Java client bindings so that's my last resort to try.

**Comment by krmahadevan** [comment]
@sahajamit - The values are indeed CSV separated. Refer [here](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/web/servlet/RegistrationServlet.java#L138).

I got this working as shown below (without double/single quotes)

```
java -jar selenium-server-standalone-3.4.0.jar -role node -hub http://localhost:4444/grid/register -servlets org.openqa.grid.web.servlet.DriverServlet,org.openqa.grid.web.servlet.ProxyStatusServlet
```

And here's the output

```
10:52:51.334 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
10:52:51.335 INFO - Launching a Selenium Grid node
10:52:51.829 INFO - binding org.openqa.grid.web.servlet.DriverServlet to /extra/DriverServlet/*
10:52:51.829 INFO - binding org.openqa.grid.web.servlet.ProxyStatusServlet to /extra/ProxyStatusServlet/*
```

**Comment by sahajamit** [comment]
@krmahadevan Thanks!!
I think the quotes were creating the problem and it worked without quotes.
Thanks again for your help.
