### ISSUE TITLE
Bug - multiple calls to driver.get(url + '/#!/home'); fail

### ISSUE THREAD

**Issue by ORESoftware** [SeleniumHQ/selenium#4087]
I posted this issue on SO:

https://stackoverflow.com/questions/44208949/selenium-routine-works-the-first-time-but-subsequent-runs-fail/44209526#44209526

It looks like if I call this more than once

```js
driver.get(url + '/#!/home');
```

it will not work after the first time, as described in the SO issue. This appears to be a bug. As a workaround, I have to explicitly call refresh().

Is there a specific issue tracker for the NPM/Node.js Selenium webdriver?

**Comment by akshat62** [comment]
It should work. I have tried it. Provide more code. 

Sometimes it happens that concatenation doesn't happens successfully.
Check it once. Split your code.

Use 
`String url= cdthost + "";
System.out.println(url);
driver.get(url);`

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by P9GIT** [comment]
I see the same issue I think, but only with Firefox.
Navigation to the same URL as the current URL makes the test stall.

Our set up:
Ruby bindings with Selenium driver 3.4 standalone JAR.
Gecko driver 0.17.0 (64 bit)
Firefox 54 (32 bit)
Windows 7 Ultimate (64 bit)

We have the same Selenium ruby code run with three browsers. Chrome and IE run with no problems.
I'm not certain this stems from the Selenium driver at all. 
It might be the gecko driver and/or FireFox itself.

I used the workaround that @ORESoftware has written on the SO issue. 

Hope this helps some one...

Thomas.

**Comment by ORESoftware** [comment]
@P9GIT  yep, I was sure of it, it's a real problem, thanks for verifying it

**Comment by ORESoftware** [comment]
@p0deje you have all the information you need to fix this issue? should be clear

**Comment by p0deje** [comment]
> you have all the information you need to fix this issue? should be clear

Not, I don't. I don't see this issue locally when trying to navigate to the same URL. Please give us a script that can be run locally to reproduce the bug.

**Comment by P9GIT** [comment]
@ORESoftware 

Sure, upvoted. 
Though I have zero reputation points being a newbie so their system won't show the upvote (it's recorded though).

**Comment by P9GIT** [comment]
@p0deje @ORESoftware 

I did some more tests and got these results. When visiting already loaded page:

DOES NOT WORK:
http://www.ford.com/#here
http://www.ford.com#!/here
http://www.ford.com#here/more

WORKS:
http://www.ford.com
http://www.ford.com/here
http://www.ford.com/here#here

pseudo-code:

driver_instance.navigate.to("http://www.ford.com#here/more")
driver_instance.find_element(:link_text,"Vehicles")
driver_instance.navigate.to("http://www.ford.com#here/more") <--- stalls here when the "bug" happens

It seems the fragment composition is the key here.

We see our failure on this URL path+fragment: /portal#issues/snoozed
Tested this on several other of our fragments of this form and they all fail in the same way.

Thomas.

**Comment by p0deje** [comment]
Thank you, I can now reproduce the bug, which seems to be GeckoDriver issue.

I've created mozilla/geckodriver#790 which you can track from now. Let's hear back from Mozilla guys.
