### ISSUE TITLE
Allow ignoring checked exceptions while waiting

### ISSUE THREAD

**Issue by olivergondza** [SeleniumHQ/selenium#409]
When using `FluentWait`, it is possible to ignore specified `RuntimeExceptions`. Checked exceptions can not be used since there is no *predicate* accepted by `until` methods that allows to throw checked exception from `apply` method. I see several ways to implement that:

1. Introduce new predicate type that permits checked exceptions.
2. Introduce Wrapping `RuntimeExcepiton` predicate implementations will use to propagate checked exceptions. `FluentWait#propagateIfNotIngored` will then unwrap before performing the check.
3. Make `FluentWait#propagateIfNotIngored` protected so subclasses can do 2.

To me, 1. seems preferable.

**Comment by andreastt** [comment]
Can you give an example of what you mean?  It's not clear to me what the problem is.

**Comment by olivergondza** [comment]
Following example allows `NoSuchElementException` to be treated as if `null` was return.

```java
WebElement foo = new FluentWait(driver)
    .ignoring(NoSuchElementException.class);
    .wait.until(new Function() {    
        public WebElement apply(WebDriver driver) {    
            return driver.findElement(By.id("foo"));    
        }
    });
```

However, the same does not work with `IOException` for instance as `apply` can not declare to throw it. Every client needs to translate checked exception to `null`/`false`. Aside from unnecessary boilerplate on client side, this approach does not attach the exception as a cause to `TimeoutException`.

**Comment by lukeis** [comment]
I'm also unclear what you mean. The example above (assuming the "foo" element doesn't exist). Will result in a TimeoutException thrown with the NoSuchElementException as the 'caused by' exception.

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/support/ui/FluentWait.java#L228

Can you please provide better snippets of code to reproduce what you expect to be working and why it isn't. When you do we can reopen this issue.

**Comment by olivergondza** [comment]
Consider you are waiting for file to be created so you can read it:

```java
FileInputStream foo = new FluentWait<String>("/tmp/my.file")
        .ignoring(FileNotFoundException.class)
        .until(new Function<String, FileInputStream>() {
            @Override public FileInputStream apply(String path) {
                // javac: unreported exception java.io.FileNotFoundException; must be caught or declared to be throw
                return new FileInputStream(path);
            }
});
```
If you declare it to be thrown:
```java
new Function<String, FileInputStream>() {
    // apply(java.lang.String) in <anonymous ...$4> cannot implement apply(F) in com.google.common.base.Function
    @Override public FileInputStream apply(String path) throws FileNotFoundException {
        return new FileInputStream(path);
    }
}
```

I am not aware any nice way to get this `FileNotFoundException` attached to `TimeoutException`.

**Comment by lukeis** [comment]
you could do:

    public class RuntimeFileNotFoundException extends RuntimeException {
      public RuntimeFileNotFoundException(Throwable t) {
        super(t);
      }
    }

    FileInputStream foo = new FluentWait<String>("/tmp/my.file")
        .ignoring(RuntimeFileNotFoundException.class)
        .until(new Function<String, FileInputStream>() {
            @Override public FileInputStream apply(String path) {
                try {
                  return new FileInputStream(path);
                } catch (FileNotFoundException fnfe) {
                  throw new RuntimeFileNotFoundException(fnfe);
               }
            }
    });

Note that WebDriverException extends RuntimeException. So, basically this implies that any exception thrown in here needs to be a Runtime one and you'll need to wrap other exceptions like FileNotFound accordingly.

**Comment by olivergondza** [comment]
Of course. Though, what is a oneliner for `RuntimeException` requires wrapping and special exception declared on client side when it comes to checked exceptions. That is what I suggest to improve.

**Comment by lukeis** [comment]
I'm not inclined to think we should allow that... maybe @shs96c can articulate something here on his thoughts.

But if you can think of how to accomplish it with preserving backwards compatibility with ExpectedConditions, then pull requests are welcome.

**Comment by jleyba** [comment]
Going to translate what I think is being requested here. @olivergondza please correct me if I'm wrong.

Conditions are defined as `com.google.common.base.Function` objects, and `Function#apply()` cannot throw a checked exception. To support ignoring checked exceptions, we'd need to introduce a new API:

    interface CheckedFunction<In, Out> extends Function<In, Out> {
        Out apply(In input) throws Exception;
    }

Internally, FluentWait would handle wrapping thrown checked exceptions for compatibility with the unchecked API (for better or worse, the Selenium API is standardized on unchecked exceptions). Finally, `FluentWait#until(Exception.class)` would check against the wrapped checked exception.

Assuming I'm understanding what is being requested here, I don't think the benefit is worth the cost in added complexity. I'm also curious what you're trying to run in a loop that throws checked exceptions.

**Comment by olivergondza** [comment]
@jleyba, that is correct.

When it comes to implementation, wrapping the exception is a one way to go. Another one would be to internally delegate to newly created `FluentWait#until(CheckedFunction)` (instead of `#until(Function)`) and inspect the exception directly. I will try to propose a PR during the weekend.

**Comment by jleyba** [comment]
Yeah... delegating from `#until(Function)` to `#until(CheckedFunction)` would be much better. It's Friday - my brain is fried.
