### ISSUE TITLE
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;

### ISSUE THREAD

**Issue by kumar-pulabaigari** [SeleniumHQ/selenium#4096]
## Meta -
OS:  Windows 10

Selenium Version: 3..3.0  

Browser:   Chrome
<!-- Internet Explorer?  Firefox?

_I have added the dependency : compile group: 'com.google.guava', name: 'guava', version:'21.0' 
to resolve the issue as mentioned in another ticket. Still I am getting this issue._

**_I am trying to build a new project using QAF in Gradle build tool._**

### Here exception:-
**java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;
      	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:409)
      	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
      	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
      	at com.qmetry.qaf.automation.step.CommonStep.get_aroundBody24(CommonStep.java:315)
      	at com.qmetry.qaf.automation.step.CommonStep$AjcClosure25.run(CommonStep.java:1)
      	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
      	at com.qmetry.qaf.automation.step.JavaStepReporter$MockJavaStep.doExecute(JavaStepReporter.java:138)
      	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
      	at com.qmetry.qaf.automation.step.JavaStepReporter.javaTestStep(JavaStepReporter.java:88)
      	at com.qmetry.qaf.automation.step.CommonStep.get(CommonStep.java:314)**

**Comment by kumar-pulabaigari** [comment]
I am trying to create a new project using QAF in Gradle build tool.

Here is the exception details:-
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;
      	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:409)
      	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
      	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
      	at com.qmetry.qaf.automation.step.CommonStep.get_aroundBody24(CommonStep.java:315)
      	at com.qmetry.qaf.automation.step.CommonStep$AjcClosure25.run(CommonStep.java:1)
      	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
      	at com.qmetry.qaf.automation.step.JavaStepReporter$MockJavaStep.doExecute(JavaStepReporter.java:138)
      	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
      	at com.qmetry.qaf.automation.step.JavaStepReporter.javaTestStep(JavaStepReporter.java:88)
      	at com.qmetry.qaf.automation.step.CommonStep.get(CommonStep.java:314)

**Comment by AutomatedTester** [comment]
It looks like you might not have the right dependencies. For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by cjayswal** [comment]
It's working fine for me with selenium-support dependency 3.0.0. For example refer following  ivy dependencies:

```
<dependency org="org.seleniumhq.selenium" name="selenium-support" rev="3.0.0" force="true"/>
<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.4.0" force="true"/>
<dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.4.0" force="true"/>

```

**Comment by nakulkhargonkar** [comment]
After upgrading and making changes in older framework,  we are getting same issue even after adding specified dependencies.

Here is the stack trace.
Buildfile: D:\eclipse_workspace_selenium3\CIM-ISFW\build.xml
clean:
   [delete] Deleting directory D:\eclipse_workspace_selenium3\CIM-ISFW\bin
init:
    [mkdir] Created dir: D:\eclipse_workspace_selenium3\CIM-ISFW\bin
     [copy] Copying 2 files to D:\eclipse_workspace_selenium3\CIM-ISFW\bin
build-project:
     [echo] testRunner: D:\eclipse_workspace_selenium3\CIM-ISFW\build.xml
     [echo] Using Java version 1.8.
    [javac] D:\eclipse_workspace_selenium3\CIM-ISFW\scripts\seleniumtestrunner.xml:65: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 81 source files to D:\eclipse_workspace_selenium3\CIM-ISFW\bin
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Creating empty D:\eclipse_workspace_selenium3\CIM-ISFW\bin\com\tibco\automation\mdm\util\userxmlsupport\package-info.class
make-jar:
      [jar] Building jar: D:\eclipse_workspace_selenium3\CIM-ISFW\dist\selenium-test.jar
runtests:
  [waitfor] Wait for selenium server to start
start-server:
     [echo] starting server D:\eclipse_workspace_selenium3\CIM-ISFW/server
     [echo] started server D:\eclipse_workspace_selenium3\CIM-ISFW/server
   [testng] Listening for transport dt_socket at address: 5431
   [testng] [Fatal Error] :31:4: The element type "constraint" must be terminated by the matching end-tag "</constraint>".
   [testng] Runnig Tests against url : null
   [testng] configurator.execution : false
   [testng] Entp & User creation through : false
   [testng] Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;
   [testng] Preparing For Shut Down...
   [testng] 	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:409)
   [testng] 	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
   [testng] 	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
   [testng] 	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
   [testng] 	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:86)
   [testng] 	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:93)
   [testng] 	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:62)
   [testng] 	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:58)
   [testng] 	at com.tibco.automation.mdm.page.common.AboutPage.<init>(AboutPage.java:17)
   [testng] 	at com.tibco.automation.mdm.util.TestRunListener.onStart(TestRunListener.java:79)
   [testng] 	at org.testng.TestRunner.fireEvent(TestRunner.java:1229)
   [testng] 	at org.testng.TestRunner.beforeRun(TestRunner.java:632)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:605)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1007)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1315)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1279)
   [testng] The tests failed.
stop-server:
[selenium-shutdown] Getting: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[selenium-shutdown] To: D:\eclipse_workspace_selenium3\CIM-ISFW\result.txt
[selenium-shutdown] Error opening connection java.io.FileNotFoundException: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[selenium-shutdown] Error opening connection java.io.FileNotFoundException: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[selenium-shutdown] Error opening connection java.io.FileNotFoundException: http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer
[selenium-shutdown] Can't get http://localhost:4444/selenium-server/driver/?cmd=shutDownSeleniumServer to D:\eclipse_workspace_selenium3\CIM-ISFW\result.txt
[selenium-shutdown] DGF Errors during shutdown are expected
openReport:
rerun:
     [echo] ${result.dir} 1
BUILD SUCCESSFUL
Total time: 2 minutes 18 seconds

Also attached screenshot.
![image](https://user-images.githubusercontent.com/48121769/54176690-d41dc180-44b5-11e9-8ff2-f14727933498.png)

**Comment by cjayswal** [comment]
It looks you have issues with dependencies. Follow steps in qaf documentation to [Create Project skeleton](https://qmetry.github.io/qaf/latest/create_test_project.html#option-2---eclipse-users) with build script and dependencies. Move your code into that and try to run build script (don't copy jar's from old project to new project, it will get resolved by ivy).

**Comment by nakulkhargonkar** [comment]
@cjayswal thanks a lot for your help. 

I will be posting sample working project link, incase some one wants to create a new project it may help them.
