### ISSUE TITLE
Unexpected error with Node.js - driver.manage().addCookie()

### ISSUE THREAD

**Issue by ORESoftware** [SeleniumHQ/selenium#4098]
On Node.js version 6.9.5, but that shouldn't matter

I have this:
```js
 driver.manage().addCookie('foo', 'bar');
```

I get this error:
`Error: addCookie called without passing Cookie object`

but this works:
```js
return driver.manage().addCookie({name:'foo', value: 'bar'});
```

seems like maybe the API should be updated to work with the first call, would completely reasonable.

**Comment by p0deje** [comment]
It's a correct API, see [docs](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Options.html#addCookie).
