### ISSUE TITLE
IE browser jumps when capturing image

### ISSUE THREAD

**Issue by leiwang008** [SeleniumHQ/selenium#410]
Evironment: Windows 7, IE11, selenium-server-standalone-2.45.0.jar, IEDriverServer.exe(for selenium2.45)

When IE is maximized, if we call org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(), the browser will jump up and down. After that the browser cannot be restored to the original location.

**Comment by andreastt** [comment]
This is expected behaviour because IE has to stitch together portions of the document to get a full document screenshot.
