### ISSUE TITLE
Selenium performance issue with IE browser

### ISSUE THREAD

**Issue by RamKumarVerizon** [SeleniumHQ/selenium#4103]
## Meta -
OS: Windows 7 Professional
Selenium Version: 3.3.0
Browser: Internet Explorer
Browser Version: 11.0.9600.18665CO
Java Version:1.8.0.73
## Expected Behavior -
IE browser should be launched within a second
## Actual Behavior -
IE browser takes 6 seconds to launch
## Steps to reproduce -
Used below line of code in Java to launch IE browser
WebDriver driver = new InternetExplorerDriver();
This launches IE browser in 6 seconds. Kindly help in launching IE browser in less than a second.

**Comment by ddavison** [comment]
does IE have an SLA that says "will be launched in one second?"

**Comment by RamKumarVerizon** [comment]
@ddavison 
Thanks for replying. But, UFT automation testing tool from HP takes 1 second.

**Comment by Jarob22** [comment]
@RamKumarVerizon UFT automation tool from HP is not selenium. There are no performance startup guarantees for browser, startup, especially since all of that is beyond selenium's control. Selenium drives browsers, it does not develop or fix them.

**Comment by AutomatedTester** [comment]
Unfortunately this is not a guarantee we can make. On startup we need to start a server that will control IE and then ask that to start the browser. While we can speed up the server startup the browser is the main time taken and that is not on us.

**Comment by jimevans** [comment]
There is a lot more going on than just launching the browser. It's an apples-to-oranges comparison, so I'm closing this issue.
