### ISSUE TITLE
Selenium IDE Error 

### ISSUE THREAD

**Issue by nirmalthanga** [SeleniumHQ/selenium#4104]
Windows 10
FireFox: 53.0.3 (32-bit) 
Selenium IDE: 2.9.1

I am seeing this error while executing the test case for simple application.

Error: 
There was an unexpected error. Msg: TypeError: window is null Url: chrome://selenium-ide/content/selenium-runner.js, line: 390, column: 7 createSelenium@chrome://selenium-ide/content/selenium-runner.js:390:7 start@chrome://selenium-ide/content/selenium-runner.js:405:16 Debugger.prototype.start@chrome://selenium-ide/content/debugger.js:154:3 Editor.prototype.playCurrentTestCase@chrome://selenium-ide/content/editor.js:925:3 doCommand@chrome://selenium-ide/content/editor.js:387:9 goDoCommand@chrome://global/content/globalOverlay.js:93:7 oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
