### ISSUE TITLE
[Selenium 3.4.0-Java]-beforeFindBy and afterFindBy methods of WebDriverEventListner interface throwing java.lang.NullPointerException

### ISSUE THREAD

**Issue by debanjan-selenium** [SeleniumHQ/selenium#4105]
## Meta -
OS:  Windows 8 Pro-64 bit OS, x64-based processor

Selenium Version:  selenium-server-standalone-3.4.0

Browser:  Mozilla Firefox

WebDriver:  geckodriver-v0.16.0-win64 (geckodriver.exe)

Browser Version:  53.0 (64-bit)

## Steps to reproduce -

1. Written "EventHandler" class which implements "WebDriverEventListener" as follows:

        package WebDriver_Event_Listener;

        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.support.events.WebDriverEventListener;

        public class EventHandler implements WebDriverEventListener{

	        @Override
	        public void afterAlertAccept(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void afterAlertDismiss(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void afterChangeValueOf(WebElement arg0, WebDriver arg1, CharSequence[] arg2) {
		        // TODO Auto-generated method stub
		        System.out.println("inside method afterChangeValueOf on " + arg0.toString());
	        }

	        @Override
	        public void afterClickOn(WebElement arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("inside method afterClickOn on " + arg0.toString());
		
	        }

	        @Override
	        public void afterFindBy(By arg0, WebElement arg1, WebDriver arg2) {
		        // TODO Auto-generated method stub
		        System.out.println("Find happened on " + arg1.toString() + " Using method " + arg0.toString());
		
	        }

	        @Override
	        public void afterNavigateBack(WebDriver arg0) {
		        // TODO Auto-generated method stub
		        System.out.println("Inside the after navigateback to " + arg0.getCurrentUrl());
		
	        }

	        @Override
	        public void afterNavigateForward(WebDriver arg0) {
		        // TODO Auto-generated method stub
		        System.out.println("Inside the afterNavigateForward to " + arg0.getCurrentUrl());
		
	        }

	        @Override
	        public void afterNavigateRefresh(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void afterNavigateTo(String arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("Inside the afterNavigateTo to " + arg0);
		
	        }

	        @Override
	        public void afterScript(String arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("Inside the afterScript to, Script is " + arg0);
		
	        }

	        @Override
	        public void beforeAlertAccept(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void beforeAlertDismiss(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void beforeChangeValueOf(WebElement arg0, WebDriver arg1, CharSequence[] arg2) {
		        // TODO Auto-generated method stub
		        System.out.println("Inside the beforeChangeValueOf method");
		
	        }

	        @Override
	        public void beforeClickOn(WebElement arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("About to click on the " + arg0.toString());
		
	        }

	        @Override
	        public void beforeFindBy(By arg0, WebElement arg1, WebDriver arg2) {
		        // TODO Auto-generated method stub
		        System.out.println("Just before finding element " + arg1.toString());
		
	        }

	        @Override
	        public void beforeNavigateBack(WebDriver arg0) {
		        // TODO Auto-generated method stub
		        System.out.println("Just before beforeNavigateBack " + arg0.getCurrentUrl());
		
	        }

	        @Override
	        public void beforeNavigateForward(WebDriver arg0) {
		        // TODO Auto-generated method stub
		        System.out.println("Just before beforeNavigateForward " + arg0.getCurrentUrl());
		
	        }

	        @Override
	        public void beforeNavigateRefresh(WebDriver arg0) {
		        // TODO Auto-generated method stub
		
	        }

	        @Override
	        public void beforeNavigateTo(String arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("Just before beforeNavigateTo " + arg0);
		
	        }

	        @Override
	        public void beforeScript(String arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("Just before beforeScript " + arg0);
		
	        }

	        @Override
	        public void onException(Throwable arg0, WebDriver arg1) {
		        // TODO Auto-generated method stub
		        System.out.println("Exception occured at " + arg0.getMessage());
		
	        }

	
        }

2. Written "programMain" class which calls the "EventHandler" class as follows:

        package WebDriver_Event_Listener;

        import org.openqa.selenium.By;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.support.events.EventFiringWebDriver;

        public class programMain {

	        public static void main(String[] args) {
		        // TODO Auto-generated method stub
		        System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
                    FirefoxDriver driver = new FirefoxDriver();
                    EventFiringWebDriver eventDriver = new EventFiringWebDriver(driver);

		        EventHandler handler = new EventHandler();
		        eventDriver.register(handler);
		        eventDriver.get("https://google.com");
		        WebElement element = eventDriver.findElement(By.linkText("Gmail"));
		        element.click();

	        }

        }

3. Executed the "programMain" class as a "Java Application"

4. `java.lang.NullPointerException` is observed for **WebDriver_Event_Listener.EventHandler.beforeFindBy(EventHandler.java:105)**

5. Console stack trace is as follows:

```
May 30, 2017 9:59:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Just before beforeNavigateTo https://google.com
Inside the afterNavigateTo to https://google.com
Exception in thread "main" java.lang.NullPointerException
	at WebDriver_Event_Listener.EventHandler.beforeFindBy(EventHandler.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$1.invoke(EventFiringWebDriver.java:81)
	at com.sun.proxy.$Proxy0.beforeFindBy(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:187)
	at WebDriver_Event_Listener.programMain.main(programMain.java:20)
```

6. Commented out `System.out.println("Just before finding element " + arg1.toString());` from `public void beforeFindBy(By arg0, WebElement arg1, WebDriver arg2)` method:

```
	@Override
	public void beforeFindBy(By arg0, WebElement arg1, WebDriver arg2) {
		// TODO Auto-generated method stub
		//System.out.println("Just before finding element " + arg1.toString());
		
	}
```

7.Executed the "programMain" class as a "Java Application" again.

8. `java.lang.NullPointerException` is observed for **WebDriver_Event_Listener.EventHandler.afterFindBy(EventHandler.java:38)**

9. Console stack trace is as follows:

```
May 30, 2017 10:06:45 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Just before beforeNavigateTo https://google.com
Inside the afterNavigateTo to https://google.com
Exception in thread "main" java.lang.NullPointerException
	at WebDriver_Event_Listener.EventHandler.afterFindBy(EventHandler.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$1.invoke(EventFiringWebDriver.java:81)
	at com.sun.proxy.$Proxy0.afterFindBy(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:189)
	at WebDriver_Event_Listener.programMain.main(programMain.java:20)
```

**Comment by shs96c** [comment]
The docs for `WebDriverEventListener` clearly state that `arg1` might be `null`, since it's only set if you call `WebElement.findBy`, which you're not doing in this code.

You should be performing a null check to make sure that the value has been set.
