### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by giggio** [SeleniumHQ/selenium#4106]
Right now Selenium only supports the .NET Framework. I understand that targeting .NET Standard 1.0 could demand a lot of work. That is not true for version 2.0.

I have seen that there is interest to support it, but I have not found an issue to address the demand. This issue covers it.

**Comment by Elufimov** [comment]
There is a pull request https://github.com/SeleniumHQ/selenium/pull/2269 You can read what selenium team think about it.

**Comment by p0deje** [comment]
I'm not .NET guy, but I guess we can close it as duplicate for #2269.

**Comment by jimevans** [comment]
No, let's leave the issue open. The PR is a different thing with its own set of concerns.

**Comment by giggio** [comment]
I just saw that version 3.6.0 is targeting .NET Standard. So this is solved.

https://www.nuget.org/packages/Selenium.WebDriver/3.6.0
