### ISSUE TITLE
Warn if path provided by the user to screenshot-taking method has non-png extension

### ISSUE THREAD

**Issue by abotalov** [SeleniumHQ/selenium#4108]
Currently most of client libraries support taking screenshot only in PNG format. Only [.NET is able to convert a screenshot to some other format](https://github.com/SeleniumHQ/selenium/blob/1e221937594c8ac4895899024927575aa6015a60/dotnet/src/webdriver/Screenshot.cs).

## Actual Behavior
Screenshot methods defined in most client libraries do not warn if path provided by the user has non-PNG extension. There are multiple cases where users wrote code that actually does it (see "Steps to reproduce"). I think they expected a screenshot to be saved in the format specified by the path extension.

## Expected Behavior
It would be better if screenshot-taking methods outputted a warning if path provided by the user has an extension but this extension (after being downcased) is not ".png". A warning should tell that despite a path ends with e.g. ".jpg", image will be saved in PNG format.

## Steps to reproduce
https://stackoverflow.com/a/24445213/841064
https://github.com/watir/watir/issues/400
http://artoftesting.com/automationTesting/screenShotInSelenium.html
http://www.softqe.com/capture-screenshot-using-selenium-webdriver/
http://www.ufthelp.com/2015/01/screenshot-using-selenium.html
https://community.perfectomobile.com/posts/1055085-sample-script-screenshot-python

cc @titusfortner

**Comment by AutomatedTester** [comment]
@abotalov a warning or an exception?

**Comment by abotalov** [comment]
@AutomatedTester I think a warning would be better because of backwards-compatibility.

**Comment by cgoldberg** [comment]
I just put up a PR to address this.  see #4141

**Comment by p0deje** [comment]
Ruby bindings support in bf9882412f117a28fb9a61278fa270ec7187cf4e.

**Comment by lmtierney** [comment]
Python bindings support in 8780494

**Comment by barancev** [comment]
It's not applicable to Java, user can't specify a path, getScreenshotAs method returns a temp file that has proper extension.

**Comment by diemol** [comment]
Seems this was implemented in all bindings but .NET, in any case, if someone needs this for .NET bindings, please raise a new issue or/and PR.
