### ISSUE TITLE
Unable to initialize htmlunitdriver: Error: Selenium htmlunit HtmlUnitDriver cannot be cast to selenium remote RemoteWebDriver

### ISSUE THREAD

**Issue by MahendraGowda** [SeleniumHQ/selenium#411]
I had tried to execute my testcases on html unit driver to implement headless browser testing. But I got error during driver initialization as 'org.openqa.selenium.htmlunit.HtmlUnitDriver cannot be cast to org.openqa.selenium.remote.RemoteWebDriver '. Any solution to resolve this issue would be appreciated.

**Comment by andreastt** [comment]
This is more a question than an issue.  Please see the selenium-users@ mailing list for support.
