### ISSUE TITLE
The Grid listen to the node is slow,need to improve performance

### ISSUE THREAD

**Issue by swissfiscal** [SeleniumHQ/selenium#4111]
when kill one node or stop one node ,the Grid  hub cant not discovery it offline immediate, waiting 30s can know it offline,please  improve  the  Grid  hub performance.

**Comment by p0deje** [comment]
I don't know how Grid works, but I suppose that is just a timeout for ping request that hub makes to a node. Pull requests are welcome :)

**Comment by diemol** [comment]
@swissfiscal I use the grid a lot in an open source project, and adding and removing nodes is done quite often there, it does not take 30 seconds at all.

Maybe you could share the exact command you use to start the grid? Also the command you use to start the nodes? I suspect that some parameters might be misconfigured.

**Comment by barancev** [comment]
Not enough information to act. It seems to be a configuration issue.
