### ISSUE TITLE
IEDriverServer_Win32_3.4.0 Virus Total detected malware and adware

### ISSUE THREAD

**Issue by hgwells13** [SeleniumHQ/selenium#4115]
My apologies, unsure if this is where I should open a malware packaging of driver binaries.

When I downloaded Selenium download page, the WIN32 IE driver version 3.4 (http://selenium-release.storage.googleapis.com/3.4/IEDriverServer_Win32_3.4.0.zip). Our IT Risk team ran virustotal software and detected:
  Jiangmin                              Adware.StartSurf.jh
  TrendMicro-HouseCall        Suspicious_GEN.F47V0422

**Comment by AutomatedTester** [comment]
Those appear to false positives seeing as we pass 58/60 virus scanners. I ran it again in https://www.virustotal.com/en/file/823e1f31e738417a31718b903573b40b88fe91abbff672cc17a91e1b717ad78b/analysis/1496323650/

If you have those antivirus please flag it for review.
