### ISSUE TITLE
Passthrough server responds in wrong dialect if the "upstream" driver only understands OSS

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#4119]
## Meta -
Selenium Version: synced to HEAD (currently 58ac131382942a543f692ed6319f87dd8a7f3552)

cc @shs96c

## Steps to reproduce -

Run the standalone server:
```
$ java -Dwebdriver.chrome.driver=chrome/chromedriver-2.29 -jar selenium-server-standalone-3.4.0.jar -enablePassThrough
```

Send a dual-dialect new session request:
```
$ curl -d'{"capabilities": {"alwaysMatch": {"browserName": "chrome"}}, "desiredCapabilities": {"browserName": "chrome"}}' http://localhost:4444/wd/hub/session
```

The request gets forwarded to Chromedriver, which responds with an OSS response. Because OSS is spoken by both sides, the server enters passthrough mode. However, it replies with a W3C response, e.g.,
```
{
    "value": {
        "capabilities": {
            "acceptSslCerts": true,
            ...
        },
        "sessionId": "01fdc7b0a9045152c8b15797a93567aa"
    }
}
```

Downstream clients doing the protocol handshake will take this to mean that they should use W3C, which is incorrect.

It seems like the problem is that [the BeginSession handler decides](https://github.com/SeleniumHQ/selenium/blob/b9f03491f807e034baa245fa764ff9d566113490/java/server/src/org/openqa/selenium/remote/server/BeginSession.java#L134) whether to send an OSS or W3C response based on the downstream request, rather than based on the upstream response, and it doesn't have any way of determining from the ActiveSession which dialect is being spoken.

Not sure how to fix this. Maybe the ActiveSession should be responsible for creating the new session response?

**Comment by shs96c** [comment]
I'll have a look at this.
