### ISSUE TITLE
Navigating to URL Containing @ Symbol

### ISSUE THREAD

**Issue by austinrr** [SeleniumHQ/selenium#4123]
## Meta -
OS:  macOS 10.12.4

Selenium Version: selenium-java  3.3.1

Browser:  Chrome

Browser Version:  Chrome 58.0.3029.110 (64-bit)

## Expected Behavior -
When using 
```
URL = new URL("https://hello.world.io/@snapshot/web/1.23.207-1-gc2b81d1/?referrer=/beta");
driver.get(url.toString())
```
 I expect the full url to be entered into the browser URL.

## Actual Behavior -
Only the portion of the url after the `@` character is getting entered into the URL of the ChromeBrowser.

**Comment by lmtierney** [comment]
I tried this and it worked fine, cannot reproduce

**Comment by austinrr** [comment]
@lmtierney I added some new details, could you try and reproduce again?

**Comment by lmtierney** [comment]
Assuming you're using URL from `java.net.URL` then yes, it's still working fine.

**Comment by lmtierney** [comment]
What version of java are you using?
