### ISSUE TITLE
Replacement for the methods

### ISSUE THREAD

**Issue by RajAsapu** [SeleniumHQ/selenium#4124]
Hi , I couldn't find below methods in Selenium 3.4.0 and i was able to access on using selenium 3.0.1.
Please help me with replacement methods for the below ones
```
``FileHandler.readAsString(file)
new Zip().zip(source,dest)
new Zip().unzip(source,dest)
FileHandler.makeExecutable(file)
FileHandler.canExecute(file)
```

**Comment by lmtierney** [comment]
https://github.com/SeleniumHQ/selenium/tree/8cf16eaf27509f00226e3cc33a52f0152337aa92/java/client/src/org/openqa/selenium/io

**Comment by RajAsapu** [comment]
@lmtierney : I am aware that methods of file handler are present under please read the question , I am unable to find those methods in latest releases which used to be in previous release 3.0.1

**Comment by lmtierney** [comment]
How are you trying to import them? You cleared out all of the new issue template and you are not providing enough information.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
Looks like they were removed e82de45 and 001c55f by @barancev

**Comment by lmtierney** [comment]
@barancev were these considered internal?

**Comment by tharakadesilva** [comment]
@RajAsapu Java has inbuilt methods for the functions removed.
The respective code would look like:
```
file.canExecute();
file.setExecutable(true);
String stringFromFile = new String(java.nio.file.Files.readAllBytes(path)); // might have more efficient alternatives for this
```

And as for the zip stuff, you could use native jdk to do it or you could use this: http://commons.apache.org/proper/commons-compress/examples.html which might be easier. If not, selenium 3.4.0 library still has the zip stuff (which uses native jdk) at https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/io/Zip.java.

**Comment by RajAsapu** [comment]
@tharakadesilva @lmtierney :Okay i guess this should be documented and make people aware that these methods are not recommended . I have referred few books which has quoted the above methods as the libraries accessible from selenium and many people are using these methods to do the zip of their log files. I agree that these methods can be implemented thru java and its the base for these methods , but i would suggest these methods to be marked as depreciated for few releases and remove later.

**Comment by tharakadesilva** [comment]
@RajAsapu deprecation would definitely have been the better option 🗡

**Comment by shs96c** [comment]
We normally deprecate methods for a single release and then delete them. I assume that in this case we believed them to be internal to Selenium and didn't follow our normal policy.
