### ISSUE TITLE
Selenium3.4.0-Java-GeckoDriver v0.16.1 : org.openqa.selenium.UnsupportedCommandException observed when browser.manage().window().fullscreen() is used

### ISSUE THREAD

**Issue by debanjan-selenium** [SeleniumHQ/selenium#4129]
## Meta -
OS:  Windows 8 Pro, 64 bit OS, x64-based processor

Selenium Version:  Selenium-Server-Standalone-3.4.0

GeckoDriver Version: v0.16.1

Browser:  Mozilla Firefox

Browser Version:  53.0

## Steps to reproduce -
Here is the minimal code block to reproduce the issue:

    package demo;
    import org.openqa.selenium.WebDriver;
    import org.openqa.selenium.firefox.FirefoxDriver;

    public class Q44356271_fullScreen {

	    public static void main(String[] args) {

           System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
           WebDriver browser = new FirefoxDriver();
           browser.get("http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?classic#form-fieldtypes");
           browser.manage().window().fullscreen();
	 }

    }

Here is the error stack trace from the console:

	1496745306655	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
	1496745308459	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  JavaScriptns reersruolrt::  r"e0sxo8u0r0c7e0:0/5/7g r(eN/Sm_oEdRuRlOeRs_/IALdLdEoGnAMLa_nVaAgLeUrE.)j"sm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
	  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:671 < startup()@resource://gre/modules/AddonManager.jsm:834 < startup()@resource://gre/modules/AddonManager.jsm:3129 < observe()@resource://gre/components/addonManager.js:65
	1496745317628	Marionette	INFO	Listening on port 4133
	JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
	Jun 06, 2017 4:05:21 PM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: W3C
	Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: POST /session/368f005d-5dbd-457e-ae83-b11d774d6dbe/window/fullscreen did not match a known command
	Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
	System info: host: 'ATECHM-03', ip: '192.168.0.105', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_77'
	Driver info: org.openqa.selenium.firefox.FirefoxDriver
	Capabilities [{moz:profile=C:\Users\ATECHM~1\AppData\Local\Temp\rust_mozprofile.zvLrWBJRQzkq, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=53.0, platformVersion=6.2, moz:processID=708.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
	Session ID: 368f005d-5dbd-457e-ae83-b11d774d6dbe
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
		at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.fullscreen(RemoteWebDriver.java:929)
		at demo.Q44356271_fullScreen.main(Q44356271_fullScreen.java:13)

**Comment by AutomatedTester** [comment]
This will be fixed in https://github.com/mozilla/geckodriver/issues/769

**Comment by debanjan-selenium** [comment]
@AutomatedTester Thanks. But how do we decide whether an issue would be addressed by SeleniumHQ/selenium group or mozilla/geckodriver group?

Thanks

**Comment by AutomatedTester** [comment]
@debanjan-selenium if you get  `org.openqa.selenium.UnsupportedCommandException: ` its likely that the browser vendors havent implemented it. At worst, raise it here and people will close and tell you the right place to raise it.

**Comment by debanjan-selenium** [comment]
That's sounds great !!! Thanks a ton @AutomatedTester

**Comment by Debanjan-B** [comment]
@AutomatedTester @lmtierney @shs96c  Can anyone confirm if the `fullscreen` mode is supported by the **`Python`** Clients as well?

**Comment by lmtierney** [comment]
@Debanjan-B I know you came into IRC already and got your answer, but I'll also link to the Issue to implement this. When `3.7` is released, it will be supported in all bindings. https://github.com/SeleniumHQ/selenium/issues/4290
