### ISSUE TITLE
Is it possible to list installed certificates on Firefox?

### ISSUE THREAD

**Issue by reebr** [SeleniumHQ/selenium#4130]
I need to get/list all certificates installed on Mozilla Firefox. I would like to know if is possible to manager it with Selenium webdriver.

I've found [this answer][1] and the file where the certificates are stored in: 

    
    %appdata%/Mozilla/Firefox/<user.profile>/cert8.db

But I can't parse this file format. So, is possible to get all certificates installed on Firefox using Selenium?

[1]:https://stackoverflow.com/a/8458694/4056678

**Comment by AutomatedTester** [comment]
This is not possible. If you want to have inspect them you will need to use something like certutil.

**Comment by reebr** [comment]
Answered here: [Is it possible to list installed certificates on Firefox?](https://stackoverflow.com/q/44377347/4056678).
