### ISSUE TITLE
Action contextclick or doubleclick problem for safari and firefox browsers

### ISSUE THREAD

**Issue by egemenceylan** [SeleniumHQ/selenium#4132]
## Meta -
OS:  Windows10, MacOS Sierra

Selenium Version: Webdriver 3.4.0

Browser:  Safari, Firefox

Browser Version:  Safari 10, Firefox 53

## Expected Behavior -

We want to use the functions of OpenQA.Selenium.Interactions.Action class (like double click, rightclick etc.) . These functions correctly work on google chrome. Normally, it must work on other browsers.

But...

## Actual Behavior -

For safari and firefox browsers, system gives an error.

**Safari situation:** 

Message: System.InvalidOperationException : Unknown command: {"id":"22gp1i3f00e5","name":"mouseMoveTo","parameters":{"element":":wdc:1496750152218"}} (WARNING: The server did not provide any stacktrace information)

**Firefox situation:** 

System does not any error for firefox but also it does not maka anything.

## Steps to reproduce -

Our code is below : 

Actions actions = new Actions(driver);

actions.DoubleClick(OurWebElement).Build().Perform();
actions.ContextClick(OurWebElement).Build().Perform();

We checked these issues : 
https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4136
https://github.com/SeleniumHQ/selenium/issues/3732

But we dont understand, how we can implement Apple's new safari driver to our project ? Or How we can resolve the problem on firefox. Please help us. Thanks.

**Comment by AutomatedTester** [comment]
Firefox bugs are https://github.com/mozilla/geckodriver/issues/661 and https://github.com/mozilla/geckodriver/issues/660.

As for Safari Driver issues you will need to raise a bug with them to get it fixed.
