### ISSUE TITLE
StaleElementReferenceException after update to newer version

### ISSUE THREAD

**Issue by nekiscz** [SeleniumHQ/selenium#4139]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.1.0+ (.NET)
Browser:  
ChromeDriver
Browser Version:  
58.0.3029.110

## Actual Behavior -
Code is working in version 3.0.1 but updating to any newer version will cause StaleElementReference on Perform(). 
**Code producing error:** 
```// Element locating        
// [FindsBy(How = How.ClassName, Using = "dot")]
// private IList<IWebElement> gameDots { get; set; }        

for (int i = 0; i < levelIndicators.Count; i++)
{
    Browser.Action.ClickAndHold(gameDots[0]);
    foreach (IWebElement gameDot in gameDots)
    {
       Browser.Action.MoveToElement(gameDot);
    }
    Browser.Action.MoveToElement(gameDots[0])
       .Build()
       .Perform();
}
```
**Browser class:**
```public static Actions Action { get; set; }
public static IWebDriver Driver { get; set; }

static Browser()
{
   Action = new Actions(Driver);  
}
```
**Thrown error:**

>OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document (Session info: chrome=58.0.3029.110) (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

[Stackoverflow question](https://stackoverflow.com/questions/44392879/staleelementexception-after-selenium-update)

## Expected Behavior -
Actions functionality will be consistent between versions.

## Steps to reproduce -
1. Go to http://play-dot-to.com/
2. Start game
3. Use provided code to finish level
4. StaleElementReference is thrown

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by kvlckova** [comment]
I tried to use different version and it does not seems to be an issue of chromedriver. I kindly ask you to try to reproduce it one more time.
It is working with Selenium 3.0.1. The newer version are not working and it does not matter if chromedriver version is downgraded or upgraded (There is still the same problem). 
As the main problem I see that Actions are not working in this configuration.

If this would be chromedriver bug, I would expect that it should not be working with the same chromedriver version at all. But it actually works when you change Selenium version to 3.0.1 without chromedriver version change.

**Comment by javaversion** [comment]
Did you find out what's the reason? I have the same problem  - after update to v3.6.0 of Selenium.
