### ISSUE TITLE
Unable to load chrome in Selenium

### ISSUE THREAD

**Issue by albertnangkil** [SeleniumHQ/selenium#4146]
Hi,

I need help. I can't launch chrome using Selenium. I tried doing the recommended fix of updating chrome. I've also tried to use guava 20, 21 and 22 but still i get the same error as below when i run my code. See  code and error for reference. Appreciate all the help i can get. Thanks!

**Code**:

package TestPack;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class SE {

	public static void main(String args[])
	{
				System.setProperty("webdriver.chrome.driver","C:\\Users\\albert.g.nangkil\\workspace\\chromedriver.exe");
				WebDriver driver = new ChromeDriver();		
				driver.get ("www.google.com");
				driver.manage().window().maximize();
				driver.getTitle();
				System.out.println(driver.getTitle());
	}
}

**Error**: Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:330)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:124)

**Comment by mcgee121** [comment]
what chrome driver OS and selenium version you have? Looks guava related to me..

**Comment by ddavison** [comment]
Hey there!

Looks as though your issue is actually a user issue rather than an issue with Selenium itself.  For these issues, we ask you to please use the [selenium users group](https://groups.google.com/forum/#!forum/selenium-users) as we reserve GitHub issues for actual issues with the software.  Thanks!

**Comment by albertnangkil** [comment]
Im using the latest version for Chrome driver  OS and selenium. I tried to installed versions 20, 21 and 22 and yet i still don't get chrome to load.
