### ISSUE TITLE
doubleClick(clickable): does not double click the found element

### ISSUE THREAD

**Issue by rscwcd** [SeleniumHQ/selenium#4149]
Hi,

We upgraded our system to use Gecko Driver(Version geckodriver-v0.16.1-win64) along with Selenium Web Driver(3.4.0) and FF 53.0. A feature called "Double Click" in our project is not working. We tried many different techniques but till now there is no success in hand. Also, we are not getting any error out of that. Below are the code that we are using to do so :

```
protected T double_click(By locator) {
WebElement clickable = findElement(ExpectedConditions.elementToBeClickable(locator));
new Actions(driver).moveToElement(clickable).doubleClick(clickable).perform();
return me();
}
```

The above method is :-1:

1. Able to find the element
2. Able to click on the element
3. Not able to generate double click event.
4. Rest other tests gets fail
The failure is not specific to any event or project but to all. Please advise.

Also, the classes related to double click in Selenium 3.4.0 is showing deprecated. Could you please let us know the next option we have to use these features ?

**Comment by lmtierney** [comment]
This is an issue with geckodriver, please see https://github.com/mozilla/geckodriver/issues/661 for tracking when this is resolved

**Comment by rscwcd** [comment]
@lmtierney : Hi, Thanks for suggestion, but I didn't find any appropriate answer from the link you shared. Everyone is doing same by just pointing to same link without checking whether the link has proper solution  to the problem or not.

**Comment by lmtierney** [comment]
There is no solution at this time, that is why there is an issue created

**Comment by Suresh4328** [comment]
Below solution worked for me.

To DoubleClick an Element
==================
public void doubleClick(WebElement webElement) {

//For FF browser.
((JavascriptExecutor)driver).executeScript("var evt = document.createEvent('MouseEvents');" + "evt.initMouseEvent('dblclick',true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0,null);" +  "arguments[0].dispatchEvent(evt);",webElement);

//For IE

//((JavascriptExecutor)driver).executeScript("arguments[0].fireEvent('ondblclick');", webElement);

}
