### ISSUE TITLE
Drag and Drop is not working

### ISSUE THREAD

**Issue by anilkosaraju** [SeleniumHQ/selenium#4150]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.0

Browser:  Chrome 58, Firefox 53.0.2.... With latest chrome and gecko drivers.

Browser Version:  

## Steps to reproduce - As it is an internal application, can't share the URL.
With the help of below image(Form Manager) you can understand that I'm trying to drag the element(Status) from rite side yellow highlighted one to the empty "td" highlighted in yellow in middle of the screen.

The below image describes about the Page source also. And the below is the code for your reference.

WebElement wbElementSource = driver.findElement(By.xpath("//div[contains(@id, 'FormManagerPropertiesList_pane')]//descendant::li[starts-with(@class, 'design-property')]//span[text()='Status']);
WebElement wbElementDestination = driver.findElement(By.xpath("//div[contains(@id, 'Design_DesignSurface')]//tr[contains(@class, 'design-surface-row')][7]//td[starts-with(@class, 'design-surface-cell') and contains(@class, '-cell-empty')]);
Actions act = new Actions(driver);
act.dragAndDrop(wbElementSource, wbElementDestination).build().perform();
		
//alternatively tried the below code as well.
act.clickAndHold(wbElementSource).moveToElement(wbElementDestination).release(wbElementSource).build().perform();

Form Manager: Trying to drag the status element to the empty space in the form manager.
![image](https://user-images.githubusercontent.com/9649881/26968512-e123e3f8-4d1f-11e7-9e54-3ccaba594f10.png)

Source control related page source:
![image](https://user-images.githubusercontent.com/9649881/26968752-c755c562-4d20-11e7-8979-a1e1d40cc7d9.png)

Destination control related page source:
![image](https://user-images.githubusercontent.com/9649881/26968799-f7818398-4d20-11e7-93c7-4142c1362625.png)

**Comment by p0deje** [comment]
We have a lot of drag&drop tests, so unless you can extract the part of your code and create a [concise reproducible test case](http://sscce.org/) to reproduce the issue, there is not much we can do about it.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

I will reopen the issue once there is a piece of code that we can run locally to see the issue is provided.

**Comment by sandeepjain1987** [comment]
Actions actions = new Actions(DriverFactory.GetCurrentWebDriver());
                actions.MoveToElement(patientButton).Perform();
This code doesn't work with FF 55, gecko 0.18.0, selenium 3.4.0+ win 7.
