### ISSUE TITLE
Selenium 3.4.0 doesn't click "span" on Edge 14.14393 

### ISSUE THREAD

**Issue by tjnhdo** [SeleniumHQ/selenium#4151]
I execute xpath like //span[contains(@Class,'pfandobjekt')].
This work on IE Firefox and Chrome browser. ( latest version)
But with Edge, I can't
Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393
Selenium 3.4.0

Please help me check.

**Comment by lmtierney** [comment]
Please log any Edge & MicrosoftWebdriver issues with Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=webdriver
