### ISSUE TITLE
Selenium HTML Runner Documentation

### ISSUE THREAD

**Issue by davidlwillson** [SeleniumHQ/selenium#4153]
At http://docs.seleniumhq.org/download/ I read: "To run Selenium tests exported from IDE, use the [Selenium Html Runner](https://goo.gl/8mbqu4)."

Where is the documentation? README? Man page? FAQ? Anything?

I've searched both old and new documentation sites and the web in general. I hope I just missed it.

I did find that I can run the jar with --help and get a dozen lines about usage. Please tell me there's more information somewhere.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

**Comment by mcdemarco** [comment]
The issue is that there is no documentation for Selenium HTML Runner.  The relevant thread in the selenium-users group is here:  https://groups.google.com/d/topic/selenium-users/GwpkC4TJcyU/discussion

**Comment by p0deje** [comment]
Ok, thanks for bringing that up.

**Comment by MilanMasek** [comment]
Hi, 

Not sure exactly where to push it in git repo, but here is quick guide for those people [like me ;] searching for such information. Obviously --help is a good start, but not enough to make stuff running in 5 minutes without previous experience with this tool.

Common information:
- Combination of releases of geckodriver / firefox / selenium-html-runner matters. There might be a matrix of compatible releases somewhere.
- selenium-html-runner runs only Test Suite (not Test Case - what is for example an export from Monitis Transaction Monitor). Be sure you comply with this.
- For Linux users with none DISPLAY - you need to start html-runner with Virtual display (search for xvfb)

Example Linux environment, install / download following releases:
`[mmasek@aws-sas-test` ~]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

[mmasek@aws-sas-test ~]$ rpm -qa | egrep -i "xvfb|java-1.8|firefox"
xorg-x11-server-Xvfb-1.19.3-11.el7.x86_64
firefox-52.4.0-1.el7.centos.x86_64
java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64
java-1.8.0-openjdk-headless-1.8.0.151-1.b12.el7_4.x86_64
`

Test Suite example:
`[mmasek@aws-sas-test ~]$ cat testsuite.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="YOUR-TEST-SCENARIO.html">YOUR-TEST-SCENARIO</a></td></tr>
</tbody></table>
</body>
</html>
`

Now, the most important part. 
Example of how to run it headless. Your experience might vary depending on software combinations -  geckodriver/FF/html-runner releases. You can also grep for scenario result eventually (PASS/FAILED):
`[mmasek@aws-sas-test ~]$ xvfb-run java -Dwebdriver.gecko.driver=/home/mmasek/geckodriver.0.18.0 -jar selenium-html-runner-3.7.1.jar -htmlSuite "*firefox" "https://YOUR-BASE-URL" "$(pwd)/testsuite.html" "results.html" ; grep result: -A1 results.html/firefox.results.html

Multi-window mode is longer used as an option and will be ignored.
1510061109691   geckodriver     INFO    geckodriver 0.18.0
1510061109708   geckodriver     INFO    Listening on 127.0.0.1:2885
1510061110162   geckodriver::marionette INFO    Starting browser /usr/bin/firefox with args ["-marionette"]
1510061111084   Marionette      INFO    Listening on port 43229
1510061111187   Marionette      WARN    TLS certificate errors will be ignored for this session
Nov 07, 2017 1:25:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-11-07 13:25:12.714:INFO::main: Logging initialized @3915ms to org.seleniumhq.jetty9.util.log.StdErrLog
2017-11-07 13:25:12.804:INFO:osjs.Server:main: jetty-9.4.z-SNAPSHOT
2017-11-07 13:25:12.822:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@87a85e1{/tests,null,AVAILABLE}
2017-11-07 13:25:12.843:INFO:osjs.AbstractConnector:main: Started ServerConnector@52102734{HTTP/1.1,[http/1.1]}{0.0.0.0:31892}
2017-11-07 13:25:12.843:INFO:osjs.Server:main: Started @4045ms
Nov 07, 2017 1:25:13 PM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | /auth_mellon.php |  |
Nov 07, 2017 1:25:14 PM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForPageToLoad | 3000 |  |
.
.
.etc

<td>result:</td>
<td>PASS</td>
`

**Comment by krmahadevan** [comment]
@MilanMasek - How about you creating a PR and submitting it to https://github.com/SeleniumHQ/docs so that the documentation appears in https://seleniumhq.github.io/docs/

**Comment by MilanMasek** [comment]
Any eta on merge?

**Comment by shs96c** [comment]
Looking at it now. We've been without a maintainer for the docs project for a while, and this fell through the cracks. My apologies.
