### ISSUE TITLE
Will selenium place a special tag in  browser document ?

### ISSUE THREAD

**Issue by liangrengongzuoshi** [SeleniumHQ/selenium#4161]
Will selenium place a special tag in the browser  document ?

like :_Selenium_IDE_Recorder,  _selenium  or   callSelenium?

If true, how can I hide them ?

Thank you very much.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
