### ISSUE TITLE
ImplicitWait and PageLoad don't seem to be working for FireFox?

### ISSUE THREAD

**Issue by realfaisalk** [SeleniumHQ/selenium#4164]
OS: Windows 10 Pro, 64 bit OS, x64-based processor

Selenium Version: Selenium-Server-Standalone-3.4.0

GeckoDriver Version: v0.16.1

Browser: Mozilla Firefox

Browser Version: 52.0

Framework: Specflow v2.1.0

Expected Behavior - ImplicitWait and PageLoad should wait for the amount of time specified when searching for an element if it is not immediately present and wait for the amount of time the driver should wait for a page to load when setting the Url property for FF.  

Actual Behavior - Steps fail due to code running ahead, indicating code isn't waiting for the timeouts.

Steps to reproduce -

Hi, I've read some of the other issues for the new ImplicitWait & PageLoad properties and can see that poeple were having issues but these seem to have been fixed recently.
I think there are still issues with these two when running them with FireFox. I've kept to v52 as I could see there were still issues with v53.
**Note: for Chrome, IE & Edge drivers I am still using the old ImplicitlyWait & SetPageLoadTimeout properties and have no issues when executing tests on these browsers. Obviously SetPageLoadTimeout thows an Exception when used with FF (gecko) driver.**

I am using a switch statement:
`switch (browser)
                {
                    case "FF":
                        var waitfor = Driver.Browser.Manage().Timeouts().ImplicitWait;
                        waitfor = TimeSpan.FromSeconds(Convert.ToDouble(impwait));
                        var pageload = Driver.Browser.Manage().Timeouts().PageLoad;
                        pageload = TimeSpan.FromSeconds((Convert.ToDouble(pagetimeout)));
                        break;
                    default:
                        Driver.Browser.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(Convert.ToDouble(impwait)));
                        Driver.Browser.Manage().Timeouts().SetPageLoadTimeout(TimeSpan.FromSeconds(Convert.ToDouble(pagetimeout))); //Causes an error with FF!
                        break;
                }`

Incidentally Selenium throws an Exception if I change the line:
` var pageload = Driver.Browser.Manage().Timeouts().PageLoad;
                        pageload = TimeSpan.FromSeconds((Convert.ToDouble(pagetimeout)));`
to
` Driver.Browser.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds((Convert.ToDouble(pagetimeout)));`

The Exception thrown is:
WebDriver: (IndexOutOfBounds): at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait) at OpenQA.Selenium.Remote.RemoteTimeouts.set_PageLoad(TimeSpan value) at PhoenixWebAutomation.Hooks1.BeforeTestRun() in C:\Users\XXXX\Documents\Visual Studio 2017\Projects\Automation Framework\src\02 Dev\XXXX\Hooks1.cs:line 71

**Comment by jimevans** [comment]
Two things. First, `System.TimeSpan` is a struct. That means that when you do the following:

    TimeSpan wait = driver.Manage().Timeouts().ImplicitWait;
    wait = TimeSpan.FromSeconds(5);

you're accomplishing nothing. It would be the same as getting or setting an integer property on an object. You're happily changing the value of the `wait` variable, but that variable doesn't contain a pointer to the property value, because as a struct, it's passed by value, not by reference.

Second, the .NET tests in the Selenium project's test code do explicitly the following:

    driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(2);

However, it's possible there's a mismatch between what the bindings are attempting to send over the wire and what the Firefox driver component, `geckodriver.exe` is expecting.

**Comment by realfaisalk** [comment]
You're correct, but the only reason I did it that way was because `driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(2);` will thrown an Exception, whereas `TimeSpan pageload = driver.Manage().Timeouts().PageLoad;
pageLoad = TimeSpan.FromSeconds(5);` does not.

**Comment by p0deje** [comment]
What is the exception when you try doing that? This exception is a real issue here.

**Comment by realfaisalk** [comment]
-		e	{" (IndexOutOfBounds)"}	System.Exception {System.InvalidOperationException}
+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}

		Source	"WebDriver"	string
		StackTrace	"   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)\r\n   at OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)\r\n   at OpenQA.Selenium.Remote.RemoteTimeouts.set_PageLoad(TimeSpan value)\r\n   at PhoenixWebAutomation.Hooks1.BeforeTestRun() in C:\\Users\\XXX\\Source\\Workspaces\\Automation Framework\\src\\02 Dev\\XXXX\\Hooks1.cs:line 68"	string
		+		TargetSite	{Void UnpackAndThrowOnError(OpenQA.Selenium.Remote.Response)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

**Note: Only happens with FFv52.0.1/geckodriver 0.61.1**

**Comment by realfaisalk** [comment]
Update: Upgraded FF to v54.0 and tried the code and it seems to be working without issue. So looks like it it's only a problem with FF v52?
Let me know if it's ok to close.

**Comment by p0deje** [comment]
Good, let's close it then.

**Comment by realfaisalk** [comment]
Thanks
