### ISSUE TITLE
Scroll element into view with different strategies

### ISSUE THREAD

**Issue by DavidGangel** [SeleniumHQ/selenium#4165]
## Meta -
OS:  ALL
Selenium Version:  3.x
Browser:  ALL

Improvement:
Implement a way to tell selenium how the scroll element into the view should behave.
It could be told by capability or any other way, it's up to you.
The most important part is that it should work across all the supported browsers.

Example:
ScrollElementIntoView.Top
ScrollElementIntoView.Center
ScrollElementIntoView.Bottom

This would be nice to tell selenium once when it starts the browser and be able to change if needed during the test run. This is for flexibility.
If no value is provided use Top as it is at the moment.

**Comment by p0deje** [comment]
You should post this issue to https://github.com/w3c/webdriver where the work on W3C specification is happening. If it's accepted - it will be implemented across all the drivers.

**Comment by DavidGangel** [comment]
Done.
Thank you!
