### ISSUE TITLE
Issue with selecting drop down value in an application. Getting error message “Element should have been "select" but was "span"

### ISSUE THREAD

**Issue by Sharazkm** [SeleniumHQ/selenium#417]
Please find the HTML Code for the drop down which I need to select in the attached screen shot.
I have used these codes to select any value from the marked dropdown value 

1)	WebElement dropDown = driver.findElement(By.id("hqCountry"));    dropDown.click();    driver.findElement(By.xpath("//*[@id='hqCountry_listbox']/li[125]")).click();
2)	New Select(driver.findElement(By.xpath("//*[@id='hqCountry_listbox']/li[55]"))).selectByValue("ABC");
3)	Also tried few more .None of them working.

None of the options are working .Please help me with a general solution so that I can use this method in future also
![issue1](https://cloud.githubusercontent.com/assets/11817296/7004332/771f0038-dc87-11e4-9ef7-d241f1260f82.jpg)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
