### ISSUE TITLE
Support query 

### ISSUE THREAD

**Issue by kumarn86** [SeleniumHQ/selenium#4170]
## Meta -
OS:  Windows 8.1

Selenium Version:  3.4.0

Browser:  Firefox 53 
<!-- Internet Explorer?  Firefox?

Does selenium 3.4.0 supports Gecko driver 0.10.0?

**Comment by kumarn86** [comment]
I am getting this below error when I use Selenium 3.4.0 with Geckodriver 0.10 , FF 53.0.

Please help

497347564117	Marionette	INFO	Listening on port 58922
[GPU 10708] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Jun 13, 2017 3:22:50 PM org.openqa.selenium.remote.ProtocolHandshake createSession

**Comment by lmtierney** [comment]
Geckodriver 0.10 is not supported please upgrade to the latest
