### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.firefox.FirefoxBinary

### ISSUE THREAD

**Issue by mpulipati** [SeleniumHQ/selenium#4171]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.3.0
Browser:  
Firefox 52.0

**Steps to Reproduce :**

i am using selenium version 3.3.0 , Firefox version 52.0  and the  gecko driver 0.15.0 try  and i am getting the error java.lang.IllegalAccessError: tried to access class org.openqa.selenium.os.ExecutableFinder from class org.openqa.selenium.firefox.FirefoxBinary
this is my code :

FirefoxProfile profile = new FirefoxProfile();
profile.setAcceptUntrustedCertificates(true);
profile.setAssumeUntrustedCertificateIssuer(true);
String currentDir = System.getProperty("user.dir");
String os = System.getProperty("os.name").toLowerCase();
String Firefoxdriverpath = null;
if (os.contains("win")) {
Firefoxdriverpath = currentDir
+ "\\src\\hpp\\publishbuild\\automation\\drivers\\geckodriver.exe";

} else {
Firefoxdriverpath = System.getProperty("user.dir")
+ File.separator + "src" + File.separator + "hpp"
+ File.separator + "publishbuild" + File.separator
+ "automation" + File.separator + "drivers"
+ File.separator + "geckodriver-v0.16.0-linux64"
+ File.separator + "geckodriver";
}

	System.setProperty("webdriver.gecko.driver", Firefoxdriverpath);
	DesiredCapabilities capabilities = DesiredCapabilities.firefox();
	capabilities.setCapability("marionette", true);
	capabilities.setCapability(FirefoxDriver.PROFILE, profile);
	MyThreadLocal.setDriver(new FirefoxDriver(capabilities));

org.openqa.selenium.firefox.FirefoxBinary.locateFirefoxBinariesFromPlatform(FirefoxBinary.java:438)
org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:155)
org.openqa.selenium.firefox.FirefoxOptions.getBinaryOrNull(FirefoxOptions.java:213)
org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:130)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:164)
hpp.publishbuild.automation.superhelper.MAF.openBrowser(MAF.java:410)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
org.testng.TestRunner.privateRun(TestRunner.java:773)
org.testng.TestRunner.run(TestRunner.java:623)
org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
org.testng.SuiteRunner.run(SuiteRunner.java:259)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
org.testng.TestNG.run(TestNG.java:1018)
hpp.publishbuild.automation.superhelper.TestNGRunner.run(TestNGRunner.java:48)
java.lang.Thread.run(Thread.java:745)

**Comment by AutomatedTester** [comment]
There is an issue with the way that you have setup your java project. The compiler is being given the wrong version of the class and is therefore erroring.

 Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mpulipati** [comment]
Thanks for your inputs.

I was using phantomjsdriver dependency  in my  POM file. So this was overriding my selenium api version. I was able to resolve this issue now.

**Comment by shindeDeepak** [comment]
Hi Pulipathi...
What changes did you made?
