### ISSUE TITLE
selenium-webdriver 3.4.1 breaks passing in a hash for desired_capabilities [rb]

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#4172]
## Meta -
Selenium Version:  
  3.4.1

## Expected Behavior -
Able to pass a hash for desired_capabilities as 3.4.0 supported

## Actual Behavior -
NoMethodError:
       undefined method `capabilities' for {:unexpectedAlertBehaviour=>"ignore", "moz:firefoxOptions"=>{}}:Hash

selenium-webdriver 3.4.0 supported passing a Hash for the `:desired_capabilities` option when creating a new marionette driver, 3.4.1  has broken that since it now unconditionally calls `#capabilities` on the object passed in  - https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/w3c/capabilities.rb#L149

There was no deprecation notification before this behavior, and having it break in a point release is completely unexpected.

**Comment by twalpole** [comment]
@p0deje  This is probably for you

**Comment by twalpole** [comment]
@matanmoda Any chance you could try my PR #4175 and see if it fixes for you, I don't currently have access to a remote setup to test against.

**Comment by p0deje** [comment]
@twalpole Thank you very much for reporting, that was indeed a regression bug introduced while implementing protocol handshake. I fixed it now for all the drivers and will make a point release later today. Sorry for the trouble!

On a side note, we have plans to rework capabilities in the future so I guess passing hashes will still be deprecated.
