### ISSUE TITLE
Buck doesn't write junit4 XML test output

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#4174]
The Selenium fork of Buck wrote *-junit4.xml files up until 2dce963c2118b9457b83d58a849ca610db904820 bumped the version. As far as I can tell, @shs96c had hacked support for JUnit4 output into his fork, and we were using that, but the new version doesn't include that change.

The JUnit XML outputs are used by Jenkins to present more fine-grained test results. Nobody noticed the missing XML files earlier, because Jenkins had already been broken by a different problem (#4173), and also because nobody ever looks at Jenkins.

**Comment by barancev** [comment]
cc: @shs96c

**Comment by barancev** [comment]
We hardly will fix this because we're migrating to Bazel.
