### ISSUE TITLE
selenium-java-3.4.0 maven module deployed to maven central with wrong packaging type

### ISSUE THREAD

**Issue by jjYBdx4IL** [SeleniumHQ/selenium#4176]
the packaging type for this should be "pom", instead we have invalid/empty jar files deployed in the repository that provoke errors when eclipse tries to import a maven project depending on selenium-java.

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/3.4.0/

**Comment by titusfortner** [comment]
Looks like this is fixed now https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/4.1.1/
