### ISSUE TITLE
IE Driver Window Handle loss

### ISSUE THREAD

**Issue by jmresler** [SeleniumHQ/selenium#4182]
## Meta -
OS: Windows 10
Selenium Version:  2.52.0
Browser: Internet Explorer 11 
Java 1.8
  
My test group has a test set consisting of 1800 test cases written for internet explorer. We have recently migrated to Windows 10, from Windows 7. The migration has broken our test bed. Without going further into the problem, we are able to execute the tests with the same IE settings (protected mode, registry, capabilities) on a Windows 10 laptop that is an HP but not one that is a Dell. 

I understand the configurations are obviously different but am confounded by why it would cause a failure assuming all other settings held constant.

I am trying to debug this in part by using the IE Driver Server log file. I see window handle losses (connection to window lost) in the log file but they don't always correlate to the failures. I've searched for an 'interpreter' of that log file but haven't found one. Can anyone tell me if the log file reporting a window handle being lost indicates a failure by the driver? Is it possible for the window handle being lost to later be 'found' again?

Thanks for your help.

**Comment by barancev** [comment]
Closing the issue as non-actionable.
