### ISSUE TITLE
testRightClick needs update when chrome 60 is released.

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#4183]
## Meta -
OS:  
Linux and Windows
Selenium Version:  
head
Browser:  
Chrome >60

Browser Version:  
 >60 

The testRightClick will fail with chrome 60

https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/test/mouse_test.html#L194

Chrome has made the change deliberately: 

https://chromium.googlesource.com/chromium/src/+/bafc23e1920cc799c03159c39e29878e26071db0

So the selenium test will need to be changed when 60 is released.

The diff will be something like
```
@@ -203,8 +203,8 @@
     assertEvents(
       mouseoverAndMoveEvents(greenDiv, 0),
       mousedownEvents(greenDiv, 2),
-      mouseoutEvents(greenDiv, b({ie: 0, wk: 2, ff: 0})),
-      mouseoverAndMoveEvents(redDiv, b({ie: 2, wk: 2, ff: 0})),
+      mouseoutEvents(greenDiv, b({ie: 0, wk: 0, ff: 0})),
+      mouseoverAndMoveEvents(redDiv, b({ie: 2, wk: 0, ff: 0})),
       mouseupEvents(redDiv, 2),
       goog.events.EventType.CONTEXTMENU, redDiv, b({ie: 0, wk: 2, ff: 2})
     );
```

**Comment by juangj** [comment]
Can we fix the test now by checking the user agent's version number?
