### ISSUE TITLE
基于selenium封装的java框架

### ISSUE THREAD

**Issue by LinuxSuRen** [SeleniumHQ/selenium#4188]
我这里有一个基于selenium封装的java框架，希望大家能给点建议。https://github.com/LinuxSuRen/phoenix.webui.framework

**Comment by LinuxSuRen** [comment]
就直接close啊

**Comment by lmtierney** [comment]
@LinuxSuRen this is for issues for the selenium project, if you'd like feedback you can chat in #selenium on Freenode

**Comment by LinuxSuRen** [comment]
@lmtierney 哦，抱歉，不知道这个

**Comment by ddavison** [comment]
@LinuxSuRen :

IRC: #selenium on Freenode
Slack: https://seleniumhq.herokuapp.com

**Comment by LinuxSuRen** [comment]
@ddavison thank you.
