### ISSUE TITLE
How do I manually/mouse dismiss a javascript.alert() and get back the the body of the web page

### ISSUE THREAD

**Issue by NevilleDNZ** [SeleniumHQ/selenium#4190]
## Meta -

OS:  GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)

Browser:  firefox-52.1.0-2.el6.centos.x86_64

Selenium Version:  2.53.2

Browser Version:  

## Steps to reproduce -

c.f. https://stackoverflow.com/questions/44568402/how-do-i-manually-mouse-dismiss-a-javascript-alert-and-get-back-the-the-body-o

Basically, when an alert is popped up in javascript, I can `dismiss()` it from python perfectly OK, by calling `selenium.webdriver.common.alert.Alert(browser).dismiss()`.

However, if the "browser user" dismisses the alert by clicking `[OK]` (on screen) with their mouse, then the browser alert gets "Lost in Space" the `body.text` can no longer be accessed from python.

FYI: The objective of the originating code is it allow the *browser user* intervene *on screen* in testing and manually response to specific alerts.

    #!/usr/bin/env python
    import os,sys,time
    import selenium.webdriver
    import selenium.webdriver.support.expected_conditions
    
    print dict(python=sys.version,selenium=selenium.__version__)
    
    path=os.path.join(os.getcwd(),"hello_worlds.html")
    url="file:///"+path
    
    open(path,"w").write("""<HTML>
      <HEAD><TITLE>Head Title</TITLE></HEAD>
      <BODY><H1>Hello, worlds!</H1></BODY>
    </HTML> """)
    
    browser=selenium.webdriver.Firefox()
    browser.get(url)
    
    body=browser.find_element_by_tag_name("body")
    print "BODY:",body.text
    
    try:
    
      for enum,world in enumerate("Mercury Venus Earth Mars Asteroids Jupiter Saturn Uranus Neptune".split()):
    
        if "Earth" in world: world+=": So do MANUALLY dismiss! {Click [OK] now!!!}"
        else: world+=": AUTO PILOT... please DONT dismiss! {done via selenium.dismiss()!}"
    
        browser.execute_script('alert("Hello, %s!")'%world)
        if selenium.webdriver.support.expected_conditions.alert_is_present():
          print selenium.webdriver.common.alert.Alert(browser).text
    
        time.sleep(enum+5)
        if "Earth" not in world: selenium.webdriver.common.alert.Alert(browser).dismiss()
    
        print "BODY:",body.text
    
    finally:
      browser.quit()

Output: (Crash at Earth)

    {'python': '2.6.6 (r266:84292, Aug 18 2016, 15:13:37) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]', 'selenium': '2.53.2'}
    BODY: Hello, worlds!
    Hello, Mercury: AUTO PILOT... please DONT dismiss! {done via selenium.dismiss()!}!
    BODY: Hello, worlds!
    Hello, Venus: AUTO PILOT... please DONT dismiss! {done via selenium.dismiss()!}!
    BODY: Hello, worlds!
    Hello, Earth: So do MANUALLY dismiss! {Click [OK] now!!!}!
    BODY:
    Traceback (most recent call last):
      File "./js_alert.py", line 37, in <module>
        print "BODY:",body.text
    ...
    selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Hello, Earth: So do MANUALLY dismiss! {Click [OK] now!!!}!
    Message: Unexpected modal dialog (text: Hello, Earth: So do MANUALLY dismiss! {Click [OK] now!!!}!) The alert disappeared before it could be closed.

The strange thing is that if the *browser user* triggers another alert (on **another** page even!), then a `selenium.dismiss()` will pull `body.text` back from limbo and selenium with *from then* will operate as per (my) expectations.

Any suggestions on how to get the browser back to the `page.body`?  (And escape the alert)

My best guess is that the alert is coming from here....
```
fxdriver.modals.closeUnhandledAlert = function(response, driver, accept) {
  var text = driver.modalOpen;
  fxdriver.modals.isModalPresent(function(present) {
    var errorMessage = 'Unexpected modal dialog (text: ' + text + ')';
    if (present) {
      try {
        if (accept) {
          fxdriver.modals.acceptAlert(driver);
        } else {
          fxdriver.modals.dismissAlert(driver);
        }
      } catch (e) {
        errorMessage +=
        ' The alert could not be closed. The browser may be in a ' +
        'wildly inconsistent state, and the alert may still be ' +
        'open. This is not good. If you can reliably reproduce this' +
        ', please report a new issue at ' +
        'https://github.com/SeleniumHQ/selenium/issues ' +
        'with reproduction steps. Exception message: ' + e;
      }
    } else {
      errorMessage += ' The alert disappeared before it could be closed.';
    }
    response.sendError(new WebDriverError(bot.ErrorCode.UNEXPECTED_ALERT_OPEN,
                                     errorMessage, {alert: {text: text}}));
  }, 2000);
};
```

**Comment by NevilleDNZ** [comment]
I can reliably reproduce this.

**Comment by cgoldberg** [comment]
technically accurate description of observed behavior is needed to reproduce or diagnose further (IMHO). 
 the given script is also needlessly verbose... most of the code has nothing to do with reproducing the issue.  see: http://sscce.org/

**Comment by NevilleDNZ** [comment]
Sorry, I can provide an unmaned "unittest" as the bug only occurs when the mouse is physically clicked.

Included is a technically accurate description of observed behaviour is provided to reproduce or diagnose further (IMHO).

re: "needlessly verbose" - change the following line to reduce verbosity...
`for enum,world in enumerate("Mercury Venus Earth Mars Asteroids Jupiter Saturn Uranus Neptune".split()):` to `for enum,world in "Other OK","Earth Bad":`

Note that the program crashes when receiving physical input from a human with a mouse.

The following is a list of historic posts referring to basically the same problem...
 
* downloading - [Issues downloading file using Selenium + Firefox](https://stackoverflow.com/questions/39289271/issues-downloading-file-using-selenium-firefox)
* java alert - [Selenium WebDriver - Unexpected modal dialog Alert](https://stackoverflow.com/questions/30771067/selenium-webdriver-unexpected-modal-dialog-alert/30773036)
* UnexpectedAlertPresentException - [Webdriver error: "No alert is present" after UnexpectedAlertPresentException is thrown](https://stackoverflow.com/questions/17576148/webdriver-error-no-alert-is-present-after-unexpectedalertpresentexception-is)
* DesiredCapabilities - [How to handle an Alert with "UnexpectedAlertBehaviour" capability in Selenium?](https://stackoverflow.com/questions/12913453/how-to-handle-an-alert-with-unexpectedalertbehaviour-capability-in-selenium)
* java&amp;javascript - [org.openqa.selenium.UnhandledAlertException: unexpected alert open](https://stackoverflow.com/questions/26772793/org-openqa-selenium-unhandledalertexception-unexpected-alert-open)
* disables exception or DesiredCapabilities - [org.openqa.selenium.UnhandledAlertException: unexpected alert open](https://stackoverflow.com/questions/26772793/org-openqa-selenium-unhandledalertexception-unexpected-alert-open)
* non-click suggestion - [When I show a dialog, an exception "UnhandledAlertException: Modal dialog present" is thrown](https://stackoverflow.com/questions/25200476/when-i-show-a-dialog-an-exception-unhandledalertexception-modal-dialog-presen)
* [IE and in the wild](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/4839)
* [java bug report](https://groups.google.com/forum/#!topic/webdriver/aNyOfEjMENg)
* "still doesn't work." catching exception does not reset the problem - (However almost exactly the same problem) - [how to handle javascript alerts in selenium using python](https://stackoverflow.com/questions/30146259/how-to-handle-javascript-alerts-in-selenium-using-python)
* [suggested doing a  driver.findElement(By.id("myAlert"));  but that throws same exception](https://sqa.stackexchange.com/questions/22482/why-my-alert-is-not-popping-up)
* [browser.refresh();  gives  UnexpectedAlertPresentException  so doesn't work. ](https://github.com/angular/protractor/issues/1486)`

How to fix the bug you ask? ...

When a mouse is ohysicall used to click on [Accept] or [Dismiss] buttons, then the following code is never called: ```fxdriver.modals.acceptAlert = function(driver) {
      var modal = fxdriver.modals.find_();
      var button = fxdriver.modals.findButton_(modal, 'accept');
      button.click();
      fxdriver.modals.clearFlag_(driver);
    };```

Hence the flag `driver.modalOpen = flagValue;` is never reset.

This miss-set flag causes on going grief whenever `fxdriver.modals.isModalPresent` is called...

```
fxdriver.modals.isModalPresent = function(callback, timeout) {
        fxdriver.modaltimer = new fxdriver.Timer();
        fxdriver.modaltimer.runWhenTrue(
        function() {
          var modal = fxdriver.modals.find_();
          return modal && modal.document && modal.document.getElementsByTagName('dialog')[0];
        },
        function() { callback(true) },
        timeout,
        function() { callback(false) });
    };
```

**Comment by p0deje** [comment]
Are you still using old legacy Firefox driver? If yes, can you try with latest GeckoDriver and compatible Firefox version?

**Comment by barancev** [comment]
Yes, I bet we'll not spend effort to fix this issue in legacy Firefox driver. Please check if this issue is actual for geckodriver.

**Comment by barancev** [comment]
Closing this issue as "won't fix" in legacy Firefox driver. If it's still actual in geckodriver please raise an issue in geckodriver's tracker: https://github.com/mozilla/geckodriver/issues
