### ISSUE TITLE
Can I access phantomJS's onResourceRequested or block resource requests?

### ISSUE THREAD

**Issue by kyle-ssg** [SeleniumHQ/selenium#4191]
Hey, this is more of a question than an issue.

I'm using selenium-webdriver for node and I'd like to be able to block network requests to certain resources.  I've seen http://phantomjs.org/api/webpage/handler/on-resource-requested.html which seems to be along the lines of what I wish to achieve, can I do this with selenium-webdriver or is there an alternative approach?

**Comment by p0deje** [comment]
Please log PhantomJS issues in https://github.com/detro/ghostdriver.

**Comment by kyle-ssg** [comment]
Right.. So using the selenium-webdriver builder with phantomjs capabilities exposes the same api as the repo linked ?

**Comment by p0deje** [comment]
Yeah. What I'm saying is that Issues related to PhantomJS driver
implementation should be reported to that trip.
