### ISSUE TITLE
Selenium 3.4.0: webDriver.Manage().Window.Maximize(); Not working on Mac safari browser 

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/selenium#4193]
**Environment:**
Browser: Safari 10.1.1
Mac os: macOS Sierra 10.12.5
WebDriver: Selenium 3.4.0
Script: C#
Platform: Visual studio
Safari extension i added in safari browser version is: 2.48.0

**Expected Behavior:**
Safari Browser windows should maximized.

**Actual Behavior:**
No action performed when run this code: 
webDriver.Manage().Window.Maximize();

I have tried with below codes but no actions performed :(

((IJavaScriptExecutor)webDriver).ExecuteScript("document.body.style.zoom = '100%';");
webDriver.Manage().Window.Maximize();
((IJavaScriptExecutor)webDriver).ExecuteScript("window.resizeTo(100,110);");

Thanks!
Elango

**Comment by zac11** [comment]
I am facing the same issue on Mac Sierra and `Chrome Version 61.0.3128.0 (Official Build) dev (64-bit)`. Should I need to file another issue or should I add my comments here?

**Comment by Elangopalakrishnan** [comment]
Have you tried with lower version of selenium web driver?? @zac11

**Comment by zac11** [comment]
@Elangopalakrishnan Well no, I haven't tried this with any other version of Selenium. My project requires me to use latest version of Chrome with latest version of Selenium.

**Comment by Elangopalakrishnan** [comment]
Hi, 

Initially i thought, It is because of selenium 3.4.0 version, But i tried now with selenium 2.53.1 version, But still i face same issue, Is there any changes in Safari Extension 2.48 ? 
I can see it is latest is Safari Extension 2.48 (DEPRECATED use Apple's Extension).
[http://www.seleniumhq.org/download/]

So i installed Browserling Extension (It supports Safari, Chrome and Firefox) and added into extension.
But still webDriver.Manage().Window.Maximize();  Not working.

@zac11  Please try this Apple's own extension and let me know it is working or not in chrome plz..
For me not working :(

Thanks!
Elango

**Comment by jiglesiasromero** [comment]
The same issue on Mac (El Capitan) and Safari 9.1
org.openqa.selenium.ScriptTimeoutException: Timed out awaiting response to command "maximizeWindow" after 30003 ms after driver.manage().window().maximize()

**Comment by FA-tvonmoll** [comment]
For Safari 10.1.1:

#3796 (and a couple others) would suggest that this is a Safari bug (and will hopefully be corrected with the next release per [this comment](https://github.com/SeleniumHQ/selenium/issues/3796#issuecomment-301551593)).

**Comment by Elangopalakrishnan** [comment]
@FA-tvonmoll ,
As per your previous comment, 
I have installed safari technology preview in my mac book, 
but how can i set the capabilities to launch that safari technology preview browser in my machine by using selenium webdriver ? 

I tried below code in c# script-
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability("browserName", "safari technology preview");

It doesn't work, it shows exception-
"The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{browserName=safari technology preview}]

Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

System info: host: 'mkusers-iMac.local', ip: '10.8.35.42', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_131'

Driver info: driver.version: unknown"

am i missing any capabilities here??

Thanks!
Elango

**Comment by svetikshark** [comment]
I also have problems in setting UseTechnologyPreview to true in c# - tried 
 SafariOptions o = new SafariOptions();
  o.AddAdditionalCapability("technologyPreview", "true");
and
 o.AddAdditionalCapability("useTechnologyPreview", "true");

both not working

**Comment by Elangopalakrishnan** [comment]
@svetikshark  please refer https://github.com/SeleniumHQ/selenium/issues/3796, here is the solution in java code :)

**Comment by svetikshark** [comment]
In c# there is no setUseTechnologyPreview function for Safaridriver for selenium 3.0.1 that's why I'm trying to add them with available AddAdditionalCapability function.

**Comment by Elangopalakrishnan** [comment]
@svetikshark Can you post full launch code?

**Comment by svetikshark** [comment]
using OpenQA.Selenium.Safari; 
private static DesiredCapabilities ForSafari()
        {
            SafariOptions o = new SafariOptions();
            o.AddAdditionalCapability("technologyPreview","true");
            DesiredCapabilities capabilities = (DesiredCapabilities)o.ToCapabilities();
            capabilities.SetCapability("browserName", "safari");
            capabilities.SetCapability("applicationName", "desktop");
            capabilities.SetCapability("javascriptEnable", "true");
            capabilities.SetCapability("cssSelectorsEnable", "true");
            capabilities.SetCapability("platform", "MAC");
            capabilities.SetCapability("secureSsl", "true");
            capabilities.SetCapability("takeScreenshot", "true");
            return capabilities;
        }

and I'm using it for remoteWebDriver
wd = new RemoteWebDriver(hubUri, capabilities, _commandTimeout)

**Comment by Elangopalakrishnan** [comment]
@svetikshark you are correct,  options.AddAdditionalCapability("technologyPreview","true"); is not working in c#, It is launching Normal safari browser.

I tried below code:
                    SafariOptions options = new SafariOptions();
                    options.AddAdditionalCapability("UseCleanSession", "true");
                    options.AddAdditionalCapability("UseTechnologyPreview", "true");                   
                    options.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
                    options.AddAdditionalCapability(CapabilityType.AcceptInsecureCertificates, true);
                    DesiredCapabilities capabilities = (DesiredCapabilities)options.ToCapabilities();
RemoteWebDriver rwd = new RemoteWebDriver(new Uri("URL:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

Don't know what to do :(

**Comment by chandrasekharmelam** [comment]
https://stackoverflow.com/questions/44449153/c-sharp-selenium-how-to-use-safari-technology-preview

**Comment by Elangopalakrishnan** [comment]
SafariDriverService serv = SafariDriverService.CreateDefaultService("/Applications/Safari Technology Preview.app/Contents/MacOS/", "safaridriver");
                    SafariOptions opts = new SafariOptions();
                    opts.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
                    opts.AddAdditionalCapability(CapabilityType.AcceptInsecureCertificates, true);
                    opts.AddAdditionalCapability("cleanSession", true);
                    DesiredCapabilities capabilities = new DesiredCapabilities();                   
                    webDriver = new SafariDriver(serv, opts);
                    RemoteWebDriver rwd = new RemoteWebDriver(new Uri("http://URL:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

This code throws exception , At first line "SafariDriverService serv = SafariDriverService.CreateDefaultService("/Applications/Safari Technology Preview.app/Contents/MacOS/", "safaridriver"); " safaridriver can be downloaded from apple.com

**Comment by svetikshark** [comment]
In my understanding this service should be started on machine which is going to execute the driver.Are you running it from mac machine? cause in my case node and hub are different machines so I don't see the way to start service on mac and send this info to hub on linux

**Comment by Elangopalakrishnan** [comment]
I have
safari technology preview - /Applications/Safari\ Technology\ Preview.app
safaridriver  -  /usr/bin/safaridriver in my mac seirra,

But still Normal safari browser only launching when i run below code in c#

SafariOptions options = new SafariOptions();
options.AddAdditionalCapability("UseCleanSession", true);
options.AddAdditionalCapability("UseTechnologyPreview", true);
options.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
options.AddAdditionalCapability(CapabilityType.AcceptInsecureCertificates, true);
DesiredCapabilities capabilities = (DesiredCapabilities)options.ToCapabilities();
RemoteWebDriver rwd = new RemoteWebDriver(new Uri("URL:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

It should launch safari technology preview (violate color) safari logo browser right???

**Comment by Elangopalakrishnan** [comment]
@chandrasekharmelam  thanks for code,

It is working fine in local  machine, but i need to launch safari browser in my remote mac machine.

webDriver = new SafariDriver();
webDriver.Navigate().GoToUrl("www.google.com");
webDriver.Manage().Window.Maximize();

How we will write for remote webdriver,
RemoteWebDriver rwd = new RemoteWebDriver(new Uri("URL:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

If i write ,  webDriver = new safariDriver(); Where i can specify the remote machine ipaddress and port ?

**Comment by barancev** [comment]
It's a safari driver issue, we hardly can do anything on the client side.

As for technologyPreview switch, please watch #4209
