### ISSUE TITLE
WebDriver with SSL on Python 2.7.9

### ISSUE THREAD

**Issue by jkohls** [SeleniumHQ/selenium#420]
There's an issue with the WebDriver over SSL connections on Python 2.7.9 and selenium (2.45.0). 

The host name is converted to an IP address in the init method of RemoteConnection and this causes this error (has actual values stripped out).

`"CertificateError: hostname '[IP_ADDRESS]' doesn't match either of '*.[HOSTNAME].com', '[HOSTNAME].com'"`
Full trace in [this gist](https://gist.github.com/jkohls/51487215a08ee2023413).

Starting with Python 2.7.9 SSL connections have certificate validation on by default and will fail if the host names do not match.

For more information see....
https://www.python.org/dev/peps/pep-0476/
https://www.python.org/dev/peps/pep-0466/

**Comment by jkohls** [comment]
Here's the change I made so I could use Python 2.7.9. 

https://github.com/SeleniumHQ/selenium/pull/421

**Comment by stefanogreg** [comment]
Please merge this PR, the bug is really annoying!

**Comment by stefanogreg** [comment]
If you need help for test let me know I can help

**Comment by danielwhatmuff** [comment]
Has this been closed out?

**Comment by davehunt** [comment]
Fixed by #3179
