### ISSUE TITLE
issue in launching Firefox/Chrome browser and given URL

### ISSUE THREAD

**Issue by sunitamh** [SeleniumHQ/selenium#4208]
## Meta -
OS:  

Selenium Version:  
< 2.44.0>
Browser:  
<Firefox 54.0 (32 bit)
simple webdriver code:

package sanitytest;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class adminlogin {

	public static void main(String[] args) {
	  WebDriver driver = new FirefoxDriver();
      //WebDriver driver = new ChromeDriver();
      driver.get("http://www.gcrit.com/build3/admin/login.php");

	}
}

error message
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

**Comment by vevinmoza** [comment]
you need to use selenium version 3 to 3.4 . 2.44 doesn't support firefox 54

**Comment by p0deje** [comment]
@vevinmoza is correct. Please, upgrade to latest Selenium and use GeckoDriver.

**Comment by sunitamh** [comment]
thanks for the reply. but earlier i downloaded the 3.4.0 version. but i was not able to attach jar files.  i have windows 8 please suggest

**Comment by sunitamh** [comment]
when i tried to download selenium 3.4.0 version, its now showing me .srcs files.
