### ISSUE TITLE
Safari: Can't set useTechnologyPreview in c# with capabilities

### ISSUE THREAD

**Issue by svetikshark** [SeleniumHQ/selenium#4209]
## Meta -
OS:  
OSX
Selenium Version:  
3.4.0
Browser:  
Safari 10.0.2

Options.AddAdditionalCapability("technologyPreview","true"); is not working in c#, It is launching Normal safari browser.

I tried below code:
SafariOptions options = new SafariOptions();
options.AddAdditionalCapability("UseCleanSession", true);
options.AddAdditionalCapability("UseTechnologyPreview", true);
options.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
options.AddAdditionalCapability(CapabilityType.AcceptInsecureCertificates, true);
DesiredCapabilities capabilities = (DesiredCapabilities)options.ToCapabilities();
RemoteWebDriver rwd = new RemoteWebDriver(new Uri("URL:5555/wd/hub"), capabilities, TimeSpan.FromSeconds(180));

**Comment by iangavr** [comment]
@barancev Sorry to bother this one again. If we just put away the issue with Maximize itself (which is a Safari driver bug, ok) and focus on why it's not possible to use the TechnologyPreview in C# while analogical actions with BrowserOptions in Java seem to be enabling it well. Is it also related to Safari driver issues?

**Comment by svetikshark** [comment]
got it working with options 
 Dictionary<string, object> remoteSafariOptions = new Dictionary<string, object>();  
                    remoteSafariOptions["technologyPreview"] = true;  
                    safariOptions = new SafariOptions();  
                    safariOptions.AddAdditionalCapability("safari.options", remoteSafariOptions);

**Comment by svetikshark** [comment]
this is working with selenium 3.4.0 but on 3.5.3 it is ignored and safari driver is called in usuall way

**Comment by burg** [comment]
@jimevans, is this a C# bindings issue, or related to server/hub?

I get bug reports about this all the time, but as safari.options is a purely synthetic capability (handled by language bindings, typically) there is nothing I can do about it from the safaridriver side.

**Comment by lmtierney** [comment]
This was an issue with standalone. It was fixed in e925304 and will be in the next release of the server
