### ISSUE TITLE
Tests failed with chrome in headless mode after window.print()

### ISSUE THREAD

**Issue by johndoejdg** [SeleniumHQ/selenium#4212]
## Meta -
OS:  Linux 4.11.3-1-ARCH
Selenium Version:  3.4.0
Browser:  Chrome 59.0.3071.104  stable

## Expected Behavior -
Test should not failed

## Actual Behavior -
During testing I see folow error in console:

```
[Facebook\WebDriver\Exception\UnknownServerException] chrome not reachable
  (Session info: headless chrome=59.0.3071.104)
  (Driver info: chromedriver=2.29,platform=Linux 4.11.3-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.11.3-1-ARCH', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29, userDataDir=/tmp/.org.chromium.Chromium.728tu6}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.104, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 5d06184c4ef6e78af13983da29ed078f 
```

## Steps to reproduce -
1. Start page with script that consist:
  let win = window.open(url);
  win.print();
Where url can be 'https://google.com'
2. Start selenium tests in headless mode.

**Comment by lmtierney** [comment]
Going to need more information than that, how did you start the webdriver, etc.

Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by p0deje** [comment]
I do believe this is a ChromeDriver issue, so probably should be reported to https://sites.google.com/a/chromium.org/chromedriver/help.

**Comment by barancev** [comment]
It's definetely a chromedriver issue.
