### ISSUE TITLE
IP not changing when attempting to use a proxy

### ISSUE THREAD

**Issue by j0rdancodes** [SeleniumHQ/selenium#4213]
## Meta
OS:  Windows 10

Selenium Version:  3.4.3

Browser:  Firefox

Browser Version:  54.0

## Issue

I am trying to change the IP using a proxy with Selenium Python but the IP isn't changing. How can I fix this? I have tried changing the proxy, but that doesn't seem to work.

```python
from selenium import *
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.proxy import *

profile = webdriver.FirefoxProfile()
browser = webdriver.Firefox(profile)
browser.get("https://www.google.com/search?q=whats+my+ip&rlz=1C1GCEA_enUS748US748&oq=whats+my+ip&aqs=chrome..69i57j0l5.1264j0j7&sourceid=chrome&ie=UTF-8")

def change_ip(proxylist, browser, profile):
    proxy = "149.56.201.164:80"

    profile = webdriver.FirefoxProfile()
    profile.set_preference("network.proxy.type", 1)
    profile.set_preference("network.proxy.http", "127.0.0.1")
    profile.set_preference("network.proxy.http_port", "8080")
    profile.update_preferences()

    browser = webdriver.Firefox(firefox_profile=profile)
    browser.get("https://www.google.com/search?q=what+is+my+ip&rlz=1C1GCEA_enUS748US748&oq=whats+my+ip&aqs=chrome..69i57j0l5.1264j0j7&sourceid=chrome&ie=UTF-8")

change_ip(proxies, browser, profile)
```

This isn't all of my code, just the parts that I have that I am using ATM.

**Comment by p0deje** [comment]
You should use [proxy object](http://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.proxy.html?highlight=proxy#selenium.webdriver.common.proxy).

This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
