### ISSUE TITLE
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL "xxxxx"The request was aborted: The operation has timed out. 

### ISSUE THREAD

**Issue by Amit199083** [SeleniumHQ/selenium#4218]
The issue is occurring everytime when i am executing the script.Following are the details:
1.) ChromeDriver Version-2.30
2.) Browser -Chrome
3.) Language-C#

The issue is occurring at diferrent places ,sometimes it gets failed due to "click" command or sometimes during "sendkeys" command.

Let me know if more information is required.

**Comment by p0deje** [comment]
The request takes too long - there might be various reasons for that from OS/network to you web application response time.

I'm closing this as we can't reproduce it until you provide [concise reproducible test case](http://sscce.org/). I'll re-open the issue if test case is provided.
