### ISSUE TITLE
IE Driver returns 404: File not found

### ISSUE THREAD

**Issue by nickgrealy** [SeleniumHQ/selenium#422]
Internet explorer throws a "404: File not found" exception, when accessed concurrently by multiple threads. This issue was initially raised on code.google.com. I've ported it here, because I believe there needs to be a better solution than "working as intended", and I'm willing to provide a Thread safe solution.

### Details

**Artifact:** `org.seleniumhq.selenium:selenium-ie-driver:2.39.0`
**IE Driver:** http://selenium-release.storage.googleapis.com/2.45/IEDriverServer_Win32_2.45.0.zip
**IE Version:** 10.0.25
**System:** Windows 8 Enterprise 64bit
**Duplicate of:** https://code.google.com/p/selenium/issues/detail?id=6592

### Exception

```java
Exception in thread "Thread-4" org.openqa.selenium.UnsupportedCommandException: Error 404: Not Found
Not Found
Command duration or timeout: 32 milliseconds
Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
System info: host: 'mycomputer', ip: '10.1.1.123', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.7.0_67'
Session ID: 65c90ea4-4af6-43bc-9f27-ex366bbe4150
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=10, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=true, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=http://localhost:6461/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at com.btfin.atp.SeleniumDefect$1.run(SeleniumDefect.java:21)
```

### Minimum code to reproduce

```java
final WebDriver driver = new InternetExplorerDriver(DesiredCapabilities.internetExplorer());
driver.get("www.google.com.au");
for (int i = 0; i < 2; i++){
	new Thread(){
		public void run() {
			driver.findElement(By.name("q")).sendKeys("Woot!");
		}
	}.start();
}
Thread.sleep(2000); // wait for all threads to finish...
driver.quit();
```

### Proposed solution

https://gist.github.com/nickgrealy/267fd8016bc84eddeb50#file-synchronizedwebdriver-java

This is just a base point for discussion. Other solutions welcomed.

**Comment by jleyba** [comment]
The WebDriver API is definitely not thread safe, nor is it intended to be.

**Comment by nickgrealy** [comment]
Hi @jleyba, can you elaborate on why it's intentionally not thread safe? Or better yet, can you point us to the documentation which states the API is not thread safe, which I imagine would also state the rationale? I couldn't find it documented anywhere.

I'm scratching my head wondering why, considering it's so simple to implement.

**Comment by sebastian-struckmann** [comment]
Hello Nick,

I am a member of Eclipse’s open-source project “Jubula“ [1]. Among other things, our tool is able to test HTML applications. To accomplish that, Jubula uses Selenium. For some time, we planned to switch to Selenium’s new WebDriver mechanism, but never got to do it. Therefore, an external contributor who needed that stepped in and updated our bundles [2],[3]. Currently we are integrating the contribution to stand side-by-side to our “old” implementation. While doing this, I stumbled across a class which our contributor got from you [4]. Would it be alright for you, if we use this class? If yes, is it okay for you to be mentioned as the author?

Best regards,
Sebastian Struckmann

[1] http://www.eclipse.org/jubula/
[2] http://bugzilla.bredex.de/1399
[3] http://eclip.se/474039
[4] https://bitbucket.org/jubula/com.bredexsw.jubula.core/src/b2a9ab48a24a3fd76f3697fccc825f6ab828e1a4/com.bredexsw.jubula.rc.html/src/com/bredexsw/jubula/rc/html/web/driver/SychronisedInternetExplorerDriver.java?at=WebdriverSwitch&fileviewer=file-view-default

**Comment by nickgrealy** [comment]
Hi @sebastian-struckmann ,

*Would it be alright for you, if we use this class?* Absolutely, please do.

*If yes, is it okay for you to be mentioned as the author?* That'd be great, thank you. If required, my email is nickgrealy@gmail.com .

Kind regards,
Nick Grealy
