### ISSUE TITLE
Cookies no longer being sent as of version (Chromedriver 2.30)

### ISSUE THREAD

**Issue by johneakin** [SeleniumHQ/selenium#4220]
ChromeDriver driver = new ChromeDriver();
driver.Navigate().GoToUrl("http://www.google.com");
driver.Manage().Cookies.DeleteAllCookies();
driver.Manage().Cookies.AddCookie(new OpenQA.Selenium.Cookie("test", "test"));
driver.Navigate().GoToUrl("http://www.google.com");

and the cookie isnt sent, this worked previously

**Comment by cgoldberg** [comment]
that might be a chromedriver bug in 2.30.
see this thread: https://groups.google.com/forum/#!topic/chromedriver-users/wDzh0MQyLKI

**Comment by p0deje** [comment]
@cgoldberg Thank you for research! Please keep track of https://bugs.chromium.org/p/chromedriver/issues/detail?id=1849.
