### ISSUE TITLE
Grid: Node not registering successfully to the hub in v3.4 (Node running on VirtualBox)

### ISSUE THREAD

**Issue by sandeepdharembra** [SeleniumHQ/selenium#4227]
## Meta -
OS:  Windows 10 (Running on virtualbox on Ubuntu 16.04)

Selenium Version:  3.4

Browser:  

Browser Version:  

## Expected Behavior -
Node Should stay Registered to the Hub

## Actual Behavior -
The node never seems to be successfully registered at all. According to the logs, it is registered and then unregistered after just a few seconds. 

## Steps to reproduce -
I am getting this issue with Selenium 3.4. Here is the complete scenario -

1)  Hub is running on my ubuntu machine
2) Ran node on the same machine as well as another machine and they both are working fine
3) Started one Win10 VM on the Ubuntu machine (running hub) using Oracle VirtualBox. Disabled Windows Firewall
4) Using the same selenium version (3.4), trying to start a node on this VM -
**Node logs say** - Node is registered to the hub and ready to  use

**Command used** : java -Dwebdriver.edge.driver="driver_path" -jar selenium-server-standalone-3.4.0.jar -role node -hub http://[IP]:4444/grid/register

**Hub Logs** -
```
19:30:14.787 INFO - Unregistering the node http://10.0.2.15:5555 because it's been down for 60030 milliseconds
19:30:14.787 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.2.15:5555
19:30:15.278 INFO - Registered a node http://10.0.2.15:5555
19:30:35.290 INFO - Marking the node http://10.0.2.15:5555 as down: cannot reach the node for 2 tries
```
Issue Same as https://github.com/SeleniumHQ/selenium/issues/3631

**Comment by zverevalexei** [comment]
Same happened here. I guess it happens because the VirtualBox VM doesn't expose its 5555 port, which results in HUB process being unable to ping the NODE process back. The both ports must be visible to each other.
I'm looking for a way to expose the port without binding it to the host machine.

**Comment by sandeepdharembra** [comment]
Thanks @zverevalexei 
Yes, just found out that, the VM (VirtualBox/VM) start the machine with network type as NAT which doesn't expose any port. I tried port forwarding with NAT which I believe is what you mentioned to avoid, however it did not work.
I changed the network type of VM to Bridged Adapter which configured the VM as a seprate machine with IP not shared with the host. Was able to start the VM as node and run the test via grid.
It seems that the issue was due to the way VM is/was setup and not related to to grid. I think the issue can be closed unless there is some thing you are working on. 
Please let me know

**Comment by zverevalexei** [comment]
@sandeepdharembra 
Exactly, I also found out that the bridge connection should be established instead of NAT. In case of NAT you are able to synchronize/share guest's machine ports. The bridged adapter would make the VM a host connected to your network with the ports exposed.
Now I'm trying to set it up in Vagrantfile :)

**Comment by sandeepdharembra** [comment]
@zverevalexei - Thanks

**Comment by mishrasanjeetr** [comment]
Hi,
I am facing same issue .Marking the node http://192.168.137.1:5566 as down: cannot reach the node for 2 tries

**Comment by barancev** [comment]
@mishrasanjeetr: Please stop hijacking closed issues! Raise a new one and provide a reproduction scenario.
