### ISSUE TITLE
chromedriver2.29 setMobileEmulation iphone5 only effect  3 seconds，then recover to full pc mode

### ISSUE THREAD

**Issue by ldjking** [SeleniumHQ/selenium#4228]
chromedriver version: 2.29 
chrome version: 58.0.3029.110

using nodejs    "selenium-webdriver": "^3.4.0",

code like below:

var webdriver = require('selenium-webdriver'),
	By = webdriver.By,
	until = webdriver.until,
	chrome = require('selenium-webdriver/chrome');

var options = new chrome.Options();

options.setMobileEmulation({
	deviceName: "Apple iPhone 5"
});
options.addArguments('disable-infobars');

var driver = new webdriver.Builder().forBrowser('chrome').setChromeOptions(options).build();

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
