### ISSUE TITLE
RHEL 5 cannot load Firefox libwebdriver shared object

### ISSUE THREAD

**Issue by kyz** [SeleniumHQ/selenium#423]
When Selenium is run with FirefoxDriver on Red Hat Enterprise Linux (RHEL) or Oracle Enterprise Linux (OEL) 5, it fails to start, despite the version of Firefox being supported by Selenium. The reason is that the prebuilt libwebdriver-firefox-*.so shared objects were built on a system using a newer glibc/GCC than RHEL5 supports.

The prebuilts should be built on a system with the minimum versions of glibc/GCC that the Selenium project is willing to support. If you're unwilling to do this, then *at least document what the required minimum versions of glibc/GCC are; collect them and update the documentation every time the prebuilts are built and committed again.

Here's a test case:

    public class test {
        public static void main(String args[]) {
            new org.openqa.selenium.firefox.FirefoxDriver();
        }
    }

When run with:

Selenium version: 2.44.0
OS: RHEL 5 / OEL 5 (glibc version 2.5, libstdc++ 4.1.2)
Browser: Firefox 31.2.0

it  gives the following error:

    Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: Bad request
    Command duration or timeout: 861 milliseconds
    Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
    System info: host: '....', ip: '....', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.39-400.214.3.el5uek', java.version: '1.7.0_55'
     Driver info: org.openqa.selenium.firefox.FirefoxDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
        at test.main(test.java:3)

Firefox launches. The WebDriver extension is present. However, this is what's in the browser log:

    {"level":"WARNING","message":"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create","timestamp":1414767273195,"type":""}
    {"level":"INFO","message":"1414767272125\taddons.manager\tDEBUG\tLoaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: [\"XPIProvider\"]\n","timestamp":1414767273196,"type":""}
    {"level":"INFO","message":"1414767272127\taddons.manager\tDEBUG\tLoaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: [\"LightweightThemeManager\"]\n","timestamp":1414767273196,"type":""}
    {"level":"INFO","message":"1414767272128\taddons.xpi\tDEBUG\tstartup\n","timestamp":1414767273196,"type":""}
    {"level":"INFO","message":"1414767272130\taddons.xpi\tDEBUG\tIgnoring file entry whose name is not a valid add-on ID: /tmp/anonymous8077704191763073687webdriver-profile/extensions/webdriver-staging\n","timestamp":1414767273196,"type":""}
    {"level":"INFO","message":"1414767272144\taddons.xpi\tDEBUG\tcheckForChanges\n","timestamp":1414767273196,"type":""}
    {"level":"INFO","message":"1414767272148\taddons.xpi\tDEBUG\tNo changes found\n","timestamp":1414767273197,"type":""}
    {"level":"WARNING","message":"Trying to re-register CID '{e26dbdcd-d3ba-4ded-88c3-6cb07ee3e9e0}' already registered by file:///tmp/anonymous8077704191763073687webdriver-profile/extensions/fxdriver@googlecode.com/components/prompt-service.js.","timestamp":1414767273197,"type":""}
    {"level":"INFO","message":"Failed to load native module at path '/tmp/anonymous8077704191763073687webdriver-profile/extensions/fxdriver@googlecode.com/platform/Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so': (80004005) /tmp/anonymous8077704191763073687webdriver-profile/extensions/fxdriver@googlecode.com/platform/Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so: ELF file OS ABI invalid\n","timestamp":1414767273197,"type":""}
    {"level":"INFO","message":"Could not read chrome manifest 'file:///usr/lib64/firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.\n","timestamp":1414767273197,"type":""}
    {"level":"INFO","message":"Warning: unrecognized command line flag -foreground\n","timestamp":1414767273197,"type":""}

The driver log for completeness:

    {"level":"INFO","message":"[fxdriver.badCertListener] Found preference for webdriver_assume_untrusted_issuer: true","timestamp":1414767273217,"type":""}
    {"level":"INFO","message":"[fxdriver.badCertListener] Found preference for webdriver_accept_untrusted_certs: true","timestamp":1414767273217,"type":""}
    {"level":"INFO","message":"[fxdriver.WdCertOverrideService] Accept untrusted certificates: true","timestamp":1414767273218,"type":""}
    {"level":"INFO","message":"[fxdriver.WebDriverServer] Using native events: false","timestamp":1414767273303,"type":""}
    {"level":"INFO","message":"[fxdriver.Utils] Loading: resource://fxdriver/evaluate.js","timestamp":1414767273303,"type":""}
    {"level":"INFO","message":"[fxdriver.Utils] Done reading: resource://fxdriver/evaluate.js","timestamp":1414767273304,"type":""}

The key issue is failure to load the native code:

    Failed to load native module at path '/.../libwebdriver-firefox-esr-latest.so': (80004005) /.../libwebdriver-firefox-esr-latest.so: ELF file OS ABI invalid

Because the WebDriver extension in Firefox can't load its native code, it reports 400 Bad Request back to the Java code.

For reasons best known to itself, glibc 2.5 on Linux cannot load a shared object if its OS/ABI field is "Linux".

    $ readelf -h libwebdriver-firefox-esr-latest.so 
    ELF Header:
      Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
      Class:                             ELF64
      Data:                              2's complement, little endian
      Version:                           1 (current)
      OS/ABI:                            UNIX - Linux
    ...

Another test program:

    /* try-loading-so.c */
    #include <dlfcn.h>
    int main(int argc, char*argv[]) {
      if (!dlopen(argv[1], RTLD_LAZY)) {
        puts(dlerror());
      }
    }

    $ ./try-loading-so ./libwebdriver-firefox-esr-latest.so
    ./libwebdriver-firefox-esr-latest.so: ELF file OS ABI invalid

If we change this to "none" (aka SysV), this gets past the first hurdle, and leaves us with another:

    $ elfedit --output-osabi none libwebdriver-firefox-esr-latest.so 
    $ readelf -h libwebdriver-firefox-esr-latest.so 
    ELF Header:
      Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
      Class:                             ELF64
      Data:                              2's complement, little endian
      Version:                           1 (current)
      OS/ABI:                            UNIX - System V
    ...

    $ ./try-loading-so ./libwebdriver-firefox-esr-latest.so 
    /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./libwebdriver-firefox-esr-latest.so)

So the object uses symbols from libstdc++ that only exists in GLIBCXX_3.4.15 (aka libstdc++.so 6.0.15 aka GCC 4.6) 
The standard libstc++ on RHEL 5.11 only goes up to GLIBCXX_3.4.8 (aka libstdc++.so.6.0.8 aka GCC 4.1.2)

I looked at the past releases to see how long this has been going on for. Surprisingly, it varies, both per-release and per-file.

    selenium 2.31.0: max version used
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so       GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-previous.so     GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-latest.so           GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-previous.so         GLIBCXX_3.4.5

no data for selenium 2.32.0 to 2.34.0, can't find the download any more

    selenium 2.35.0: max version used
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so       GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-previous.so     GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-latest.so           GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-previous.so         GLIBCXX_3.4.15

    selenium 2.36.0: max version used
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so       GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-previous.so     GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-latest.so           GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-previous.so         GLIBCXX_3.4.15

    selenium 2.37.0: max version used
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so       GLIBCXX_3.4.5
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-previous.so     GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-latest.so           GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-previous.so         GLIBCXX_3.4.15

    selenium 2.38.0 to 2.44.0: max version used
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-latest.so       GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-esr-previous.so     GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-latest.so           GLIBCXX_3.4.15
    Linux_x86_64-gcc3/components/libwebdriver-firefox-previous.so         GLIBCXX_3.4.15

I suspect this is simply the choice of compiler on the box that builds Selenium. I'm looking into compiling and building the libwebdriver components myself, to see if there's any code-based reason to mandate running on a system based on GCC 4.6 and higher.

As GCC 4.1.2 can compile Firefox 31.2 itself, surely there can't really be a reason why the GCC 4.6 runtime is needed to run an extension for it.

I don't know what the solution is, but even if you don't want to build Selenium on an old machine, GCC flags like `-fabi-version` may help.

[This SO answer](http://stackoverflow.com/questions/8842194/how-to-avoid-stt-gnu-ifunc-symbols-in-your-binary), which covers that the reason for OSABI "linux" is due to the compiled output including STT_GNU_IFUNC symbols, suggests that the simplest way to make widely compatible binaries is to statically compile them, so there isn't any dependency on libstdc++ at all.

**Comment by javabrett** [comment]
This looks like a serious issue.  I am surprised to find myself having troubles loading 2.44 on RHEL6.4/OEL6.4 , which seems to be limited to GLIBCXX_3.4.13.  The same test rig runs fine on Linux Mint 17.1, which has GLIBCXX_3.4.19.

I suspect the binary build is on an Ubuntu machine but I'm not certain and don't know the GLIBCXX version.

**Comment by barancev** [comment]
Native libs are excluded from the firefox driver, the issue should be fixed in 2.48

**Comment by kyz** [comment]
Thanks! I can confirm that selenium-2.48.2 FirefoxDriver now works with Firefox ESR 38.3.0 on RHEL5 (x86_64) -- there are no native libraries to load and the extension loads correctly.
