### ISSUE TITLE
Webdriver support for TOR Browser

### ISSUE THREAD

**Issue by isantolin** [SeleniumHQ/selenium#4239]
OS:  Any
Selenium Version:  Future
Browser:  Tor Browser

I think its a good idea add Tor Browser support in WebDriver

**Comment by andrusha** [comment]
Tor Browser = Pre-Configured Firefox + Extensions. Might be that no additional modifications are needed, worth checking if it works with current Selenium.

**Comment by isantolin** [comment]
@andrusha Tor Browser is not  just a Firefox browser with Extensions. Has a lot of options disabled (Canvas, Javascript) or modified from the mainstream version. Furthermore we need interact with the "Tor Network Settings" from startup that has a deep integration with Tor Browser

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
