### ISSUE TITLE
Issue starting firefox webdriver with specific profile

### ISSUE THREAD

**Issue by WizShrutz** [SeleniumHQ/selenium#424]
Hi ,
I have developed a proxy that monitors net traffic. I want to run scrips with selenium webdriver(C#.net) that has to use this proxy.

the proxy runs on the same machine so I set the proxy in FF to "127.0.0.1:8080" in a specific profile(say Trial1ForProxy)
![proxysettingsinff](https://cloud.githubusercontent.com/assets/11836056/7024344/cdee482e-dd59-11e4-8735-4567b1628ac6.png)

When I start FF with the specific profile with "firefox -p Trial1ForProxy" it works fine as expected.

But when I use the following code

            FirefoxProfileManager profileManager = new FirefoxProfileManager();
            FirefoxProfile firefoxProfile = profileManager.GetProfile("Trial1ForProxy");
            wDriver = new FirefoxDriver(firefoxProfile);

it gives me an error

           Additional information: The value of the property 'proxyaddress' cannot be parsed. The error is: Invalid URI: The URI scheme is not valid.

I assumed as it works with FF by DEFAULT it should work with selenium.

Secondy : I tried setting the proxy as system settings and start the selenium instance it gives the same error for all browsers(IE,FF,Chrome,etc)

Please suggest what can be done in this case or the correct URI in the above case

**Comment by andreastt** [comment]
This seems like a problem with the preferences parser in Java maybe?

**Comment by WizShrutz** [comment]
This is a c#.net code could u please correct the label 

Thanks 

---- Andreas Tolfsen wrote ----

**Comment by jimevans** [comment]
Can you provide a complete stack trace @WizShrutz? I can't seem to reproduce the issue.

**Comment by WizShrutz** [comment]
I tried the code on your blog

            FirefoxProfile firefoxProfile = new FirefoxProfile();
            OpenQA.Selenium.Proxy proxy = new OpenQA.Selenium.Proxy();
            proxy.HttpProxy = string.Format("127.0.0.1:{0}", 8889);
            proxy.FtpProxy = string.Format("127.0.0.1:{0}", 8889);
            proxy.SslProxy = string.Format("127.0.0.1:{0}", 8889);
            proxy.Kind = ProxyKind.Manual;
            firefoxProfile.SetProxyPreferences(proxy);
            wDriver = new FirefoxDriver(firefoxProfile);

![image](https://cloud.githubusercontent.com/assets/11836056/7028961/337b58f4-dd77-11e4-8fd7-104084b45511.png)

Still getting the above error as before, I am unable to get the stack trace , any suggestions ?
