### ISSUE TITLE
Selenium IDE test result with schedule

### ISSUE THREAD

**Issue by kgaillard** [SeleniumHQ/selenium#4241]
Hi there, sorry first post on GH.

I was using Selenium IDE and selenium server standalone 2.52.0 because I was on Mozilla 38. Now I have to work on Mozilla 45 and I try to use geckoserver but I didn't find it useful enough for me so I decided to try to only use Selenium IDE.

I'm discovering the test scheduler tools and I thought it would be perfect but I need to have some test report for any test suit.

I know we can use some plugin to have test report but I don't know if we can automatically have test report for any test suit plan on schedule.

Thanks in advance and sorry if I missed something.

## Meta -
OS: Windows 7
Selenium Version:
Selenium IDE 2.9.1.1
Browser:
Firefox 45

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
