### ISSUE TITLE
Allow Specifying which Marionette Port to Use

### ISSUE THREAD

**Issue by vortic** [SeleniumHQ/selenium#4242]
It seems like adding support for specifying the marionette port is pretty simple. Apologies if this has already been addressed:

In `selenium/webdriver/firefox/webdriver.py`:
1. add "mport" to the `__init__` function.
2. on line 144, pass `mport` to `Service` constructor

In `selenium/webdriver/firefox/service.py`:
replace `command_line_args` with:
~~~python
def command_line_args(self):
    args = ["--port", "%d" % self.port]
    if self.mport:
        args += ["--marionette-port", "%d" % self.mport]
    return args
~~~

I thought I would ask if this seems reasonable before making a pull request.

**Comment by vortic** [comment]
I went ahead and opened a PR for this: https://github.com/SeleniumHQ/selenium/pull/4278

**Comment by lmtierney** [comment]
Closing as this functionality is currently available via the `service_args` argument and in the future by passing a service object
