### ISSUE TITLE
Issue zooming in/out with Firefox 54.0

### ISSUE THREAD

**Issue by computerscientist** [SeleniumHQ/selenium#4244]
To whom it may concern,

I am having problems zooming in and out of a web page when I use Selenium in Firefox 54.0.
My code snippet to zoom in looks like this:

        WebElement html = findElement(By.tagName("html"));
        html.sendKeys(Keys.chord(Keys.CONTROL, Keys.ADD));

 And here is my code to zoom out:

        WebElement html = findElement(By.tagName("html"));
        html.sendKeys(Keys.chord(Keys.CONTROL, Keys.SUBTRACT));

Can someone please let me know what do do?

**Comment by barancev** [comment]
1) Use body instead of html, 2) Don't use numeric keyboard:

    WebElement body = findElement(By.tagName("body"));
    body.sendKeys(Keys.chord(Keys.CONTROL, "+"));
    body.sendKeys(Keys.chord(Keys.CONTROL, "-"));

**Comment by matifayaz** [comment]
Trying in Python with Selenium 3.4.3 & Firefox 57 but it's not working:
```
body = browser.find_element_by_tag_name('body')
body.send_keys(Keys.CONTROL, '+')
body.send_keys(Keys.CONTROL, Keys.ADD)
body.send_keys(Keys.CONTROL, Keys.SUBTRACT)
body.send_keys(Keys.LEFT_CONTROL, Keys.SUBTRACT)

```

**Comment by rishabh27892** [comment]
I am facing the exact same issue. any solution or workaround yet?

**Comment by ar-ms** [comment]
The following workaround did work for me.
```python
browser.execute_script('document.body.style.MozTransform = "scale(0.50)";')
browser.execute_script('document.body.style.MozTransformOrigin = "0 0";')
```

**Comment by rben01** [comment]
@ar-ms That's similar but not identical to pressing Ctrl +. In Firefox, it zooms the content but doesn't show the "125%" in the URL bar, so something is acting different under the hood.
