### ISSUE TITLE
Kotlin support 

### ISSUE THREAD

**Issue by qwertukg** [SeleniumHQ/selenium#4246]
Hello guys!
I was try to find something for [Kotlin](https://kotlinlang.org/) but can't. And was write some small [DSL](https://github.com/qwertukg/SeleniumBuilder), who use a [Kotlin builders](https://kotlinlang.org/docs/reference/type-safe-builders.html) style way. 
It will be very cool, if will be something like this in a future, from official team.
Good luck!

**Comment by qwertukg** [comment]
Kotlin example
```kotlin
var result = ""
chromeDriver("d:/chromedriver.exe") {
    get("http://google.com")

    elementById("lst-ib") {
        sendKeys("kotlin")

        wait(10) {
            elementVisibilityById("_fZl") {
                click()
            }

            elementVisibilityBySelector("a[href = 'https://kotlinlang.org/']") {
                result = text
            }
        }
    }
}
```

**Comment by p0deje** [comment]
I'm not sure that there is anyone on the team working with Kotlin so I doubt there will be official bindings for that language.

However, there is nothing stopping you from creating Kotlin bindings, we'll be more than happy to mention it in [Downloads](http://docs.seleniumhq.org/download/).
