### ISSUE TITLE
how to set page load timeout for selenium webdriver tab window

### ISSUE THREAD

**Issue by cruldra** [SeleniumHQ/selenium#425]
FirefoxDriver driver = new FirefoxDriver();
driver.manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);
driver.get("http://www.riguanghaian.com/");

this will be throw a timeoutexception and message timed out waiting for page load!
if i open a new webdriver tab window by click a hyperlink element as below:
WebElement element = driver.findElement(By.id(hyperlink_id));
element.click();
this will still load sometimes and can not get a timeoutexception,how can i do now ?
thanks!

**Comment by andreastt** [comment]
This is a question and not an issue.  Please address it to the Selenium user group.
