### ISSUE TITLE
Unable to sendkeys to grid cell in IE webdriver

### ISSUE THREAD

**Issue by mksingh123** [SeleniumHQ/selenium#4253]
Hi,
I am trying to sendkeys on a wijmo control (version: 5.20171.293) cell using the following:
cell.SendKeys(Keys.Control + 'a');
The code gets executed but it does not select all the cells. It works fine with Chrome.
Thanks!
Regards
Manish

Response from jsakamoto:
Unfortunately, I can't treat this issue because of I'm just packager, not contributor for Selenium IEDriver. 😢
Instead, you can create issue here: https://github.com/seleniumhq/selenium/issues/new
I hope this information helps you.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mksingh123** [comment]
Hi Alex,
Thanks a lot for your prompt response. For simplicity, I have created a simple google test as I can reproduce it with that as well and do not need any Wijmo control, just copy paste in Visual Studio and run it (provided you have Selenium and webdriver/s from nuget):
PS: The expected result and failure step provided in code comments for simplicity
Please let me know if you need any other detail.
Thanks!
Regards
Manish
=====================================================

using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using System;
using System.Threading;

namespace FredNxtOfficeWebAutomation.Tests
{
    [TestClass]
    public class GoogleTest
    {
        [TestMethod]
        public void SendkeyTest()
        {
            IWebDriver driver = null;
            driver = new InternetExplorerDriver();
            //driver = new ChromeDriver();
            driver.Manage().Window.Maximize(); 
            Uri BaseUrl = new Uri("http://www.google.com/");
            driver.Navigate().GoToUrl(BaseUrl);
            Thread.Sleep(2000); //Please increase this thread time if it doesn't work for you. I have a different way to handle this in my project
            driver.FindElement(By.Id("lst-ib")).SendKeys("selenium"); //Enter search text  
            
            //The below statement should select the text (selenium)
            //Works fine on Chrome
            //Doesn't work in IE          
            driver.FindElement(By.Id("lst-ib")).SendKeys(Keys.Control + 'a'); 
        }        
    }
}

**Comment by mksingh123** [comment]
Apologies for the bold text, it was by mistake...

**Comment by p0deje** [comment]
Thank you for a test script. I've never really used C# and I don't have VS so I'll keep this open until somebody (probably Jim) can have a look.

**Comment by mksingh123** [comment]
Hi Alex, 
Any updates on this? Do you need to assign this to someone else?
Thanks!
Regards
Manish

**Comment by p0deje** [comment]
We need to wait for somebody with C# bindings experience to look at this, so please be patient.

**Comment by Philip-Gullick** [comment]
Things to try:
Click the element to make it active:

Set require windows focus to true (only do this if this code is browser specific),
click the element before ctrl + a sequence.

I haven't tested this code but give it a go and see if it works.
More of an issue on how IE interacts with key simulations rather than the driver itself, hence chrome works.

public void SendkeyTest()
    {
      IWebDriver driver = null;
      var options = new InternetExplorerOptions();
      options.RequireWindowFocus = true;
      driver = new InternetExplorerDriver(options);
   

      //driver = new ChromeDriver();
      driver.Manage().Window.Maximize();
      Uri BaseUrl = new Uri("http://www.google.com/");
      driver.Navigate().GoToUrl(BaseUrl);
      Thread.Sleep(2000); //Please increase this thread time if it doesn't work for you. I have a different way to handle this in my project
      IWebElement element = driver.FindElement(By.Id("lst-ib")); //Enter search text  
      Actions mouseOverAction = new Actions(driver);
      mouseOverAction.MoveToElement(element)
                 .Click()
                 .SendKeys(Keys.Control + "a")
                 .Perform();
      //The below statement should select the text (selenium)
      //Works fine on Chrome
      //Doesn't work in IE          
      driver.FindElement(By.Id("lst-ib")).SendKeys(Keys.Control + 'a');
      
    }

**Comment by mksingh123** [comment]
Hi Philip,
Thanks for your response.
This works perfectly fine on local IE webdriver with my application automation code, but not when I run the same on Sauce Labs environment. Probably, I will check with sauce Labs Support team as to why it's happening, will keep you posted.
Thanks a lot!
Regards
Manish

**Comment by barancev** [comment]
Closing the issue becuse it works in local environment. Feel free to reopen it if SauceLabs responds it's an issue in Selenium but not their cloud environment.
