### ISSUE TITLE
Web Site error?

### ISSUE THREAD

**Issue by gsi-frank** [SeleniumHQ/selenium#4254]
Error while accessing http://www.seleniumhq.org/docs/03_webdriver.jsp

Sorry if this is not the place, but I did not know where to report the error.

**Comment by ruby186** [comment]
Error: Server ErrorThe server encountered an error and could not complete
your request.

Please try again in 30 seconds.

2017-07-04 9:59 GMT+08:00 Frank Abel Cancio Bello <notifications@github.com>
:

**Comment by p0deje** [comment]
Moved to SeleniumHQ/www.seleniumhq.org#155.
