### ISSUE TITLE
Table view does not exist for this view

### ISSUE THREAD

**Issue by Salonigothi** [SeleniumHQ/selenium#4255]
Getting an error while launching IDE - "Table view does not exist for this view".

IDE was working properly few days back but suddenly it stopped working  and I am unable to record or even open any test case

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by barancev** [comment]
Switch to HTML format (OPtions -> Format -> HTML), table view is available for HTML format only.
