### ISSUE TITLE
Not able to load the page properly.

### ISSUE THREAD

**Issue by luckugupta72** [SeleniumHQ/selenium#4256]
I am opening an URL using chrome initially I was able to open it properly and everything was working fine and all of a sudden it is not loading the page properly when I am clicking on any button it giving a server error. I uninstalled and reinstalled the google chrome driver and software but still, the issue exists. please find the screenshot in the attachment.

Thanks 
![untitled](https://user-images.githubusercontent.com/19589939/27821554-50eac626-60c0-11e7-902e-0935d92c909f.png)
![untitled](https://user-images.githubusercontent.com/19589939/27821595-6be480b6-60c0-11e7-805d-6f525bd8d8c2.png)
![untitled](https://user-images.githubusercontent.com/19589939/27821677-c16d4252-60c0-11e7-8513-47cd7120661b.png)

**Comment by p0deje** [comment]
This error comes from web application you are testing, not ChromeDriver.

**Comment by luckugupta72** [comment]
Its was working from past 2 months and there is no migration or changes has happened in the application.

So how can it be an application issue?

**Comment by p0deje** [comment]
Because it clearly says: "An application error occurred on the server."

**Comment by luckugupta72** [comment]
Yes, it is saying because it is not loading the website properly.
 When I am opening an application manually it's opening properly.

**Comment by p0deje** [comment]
There might be various reasons. For example, you're simply not logged in and try to open this URL. Or maybe your application is incompatible with Chrome, I don't know. In any event, that's not an issue coming from Selenium.
