### ISSUE TITLE
[Suggestion] Add until.* inverse methods for Node.js bindings

### ISSUE THREAD

**Issue by serge1peshcoff** [SeleniumHQ/selenium#4257]
(Please help me naming this issue, as I think it's probably not correct and I'm not sure how to name it)

I'm using npm `selenium-webdriver` package and sometimes, for instance, I need to `wait` until browser URL isn't equal to a specific string or doesn't contain a substring. There are `until.urlContains` and `until.urlIs` (and the same methods for title) and I think it would be really useful to have methods like `until.urlNotContains` which will wait till URL/title would be changed.

I can (and I want to) make a PR on that, and this issue is mostly to get the developers' opinion on that, would it be really useful and would my PR be merged if I'll do it. (I'm talking about Node.js version, since I'm working with it most of the time and have an idea of how to implement it)

**Comment by jleyba** [comment]
The idea behind the `until` module is to provide the basic conditions and users can define their own as needed. It doesn't look like python or C# have the inverted conditions, so I'm not inclined to add them to js (I think the java ExpectedConditions have grown too organically and I'm not basing any js design decisions on the state of that class).

I am generally open to adding more conditions, just not a full matrix of `until.X` and `until.notX`.

**Comment by serge1peshcoff** [comment]
To anybody who will need these methods: I've wrote a library that extends `utils`'s functionality by adding extra methods, such as `urlIsNot`, `urlNotContains` etc.
Here it is:
https://github.com/serge1peshcoff/selenium-until-extra
https://www.npmjs.com/package/selenium-until-extra
