### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Karthickprasanths** [SeleniumHQ/selenium#4258]
Am new to mobile emulation  i know know how to fix this .can some one help 

My code:
Map<String, String> mobileEmulation = new HashMap<String, String>();
		mobileEmulation.put("deviceName", "Google Nexus 5");
		Map<String, Object> chromeOptions = new HashMap<String, Object>();
		chromeOptions.put("mobileEmulation", mobileEmulation);
		DesiredCapabilities capabilities = DesiredCapabilities.chrome();
		capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

		return new ChromeDriver(capabilities);

FAILED CONFIGURATION: @BeforeTest setupSelenium(org.testng.TestRunner@2ee65e1d) org.openqa.selenium.WebDriverException: unknown error: cannot parse capability: chromeOptions from unknown error: cannot parse mobileEmulation from unknown error: 'Apple iPad' must be a valid device from unknown error: must be a valid device   (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 1.33 seconds Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40' System info: host: 'DESKTOP-FJBA4SA', ip: '10.1.0.174', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79' Driver info: org.openqa.selenium.chrome.ChromeDriver 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) 	at java.lang.reflect.Constructor.newInstance(Unknown Source) 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204) 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156) 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599) 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240) 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126) 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139) 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171) 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139) 	at com.xtime.automation.core.browser.MobileEmulator.createDriver(MobileEmulator.java:31) 	at com.xtime.automation.core.manager.DriverManager.getBrowserDriver(DriverManager.java:92) 	at com.xtime.automation.core.manager.DriverManager.initializeDriver(DriverManager.java:55) 	at com.xtime.automation.core.manager.DriverManager.initializeDriver(DriverManager.java:44) 	at com.xtime.automation.mp3.MP3TestBase.setupSelenium(MP3TestBase.java:57) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 	at java.lang.reflect.Method.invoke(Unknown Source) 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80) 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564) 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213) 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138) 	at org.testng.TestRunner.beforeRun(TestRunner.java:641) 	at org.testng.TestRunner.run(TestRunner.java:609) 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) 	at org.testng.SuiteRunner.run(SuiteRunner.java:240) 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198) 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123) 	at org.testng.TestNG.run(TestNG.java:1031) 	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132) 	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236) 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)

**Comment by zac11** [comment]
Nothing has been added as a part of issue description. Please close it or add issue description.

**Comment by p0deje** [comment]
You are using incorrect device name. See [ChromeDriver mobile emulation](https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation) documentation.

**Comment by Karthickprasanths** [comment]
Thanks a lot. i have got document while searching and i have implemented the same result is successful too .Once again thanks a lot.
