### ISSUE TITLE
Use of "-1" as port if not specified in the `-hub` URL

### ISSUE THREAD

**Issue by toote** [SeleniumHQ/selenium#426]
If you setup a selenium to connect to a hub using the option `-hub http://example.com/grid/register` the following appears in the error log output:

```
17:41:01.837 INFO - Registering the node to hub :http://example.com:-1/grid/register
```

**Comment by AJ-72** [comment]
@toote While setting up, you should also provide the port number on which hub is running. 

From the wiki page - https://code.google.com/p/selenium/wiki/Grid2: the command to start node is :
java -jar selenium-server-standalone-2.14.0.jar -role node  -hub http://localhost:<b>4444</b>/grid/register

**Comment by toote** [comment]
@AJ-72 thanks for the response. I knew about that, the report is to make it use a default port or give an error instead of using that obviously invalid port

**Comment by AJ-72** [comment]
Ok. Got it.
@andreastt Will someone from core team be confirming whether this feature should be added? And also whether we should default or error out. I can work on this if I get answers for these.
