### ISSUE TITLE
Chrome does not close

### ISSUE THREAD

**Issue by jonashartwig** [SeleniumHQ/selenium#4262]
OS:

Mac OSX 10.12.3
Windows 7
node:

lts 6.10.2
npm:

4.2.0
chrome window does not close after test run.

"dependencies": {
    "chromedriver": "^2.29.0",
    "jasmine": "^2.5.3",
    "jasmine-promises": "^0.4.1",
    "jasmine-reporters": "^2.2.0",
    "jasmine-spec-reporter": "^3.2.0",
    "selenium-webdriver": "^3.3.0"
  }
import seleniumWebDriver from "selenium-webdriver";

describe("e2e tests", () => {
    const { By, until } = seleniumWebDriver;
    let driver;

    beforeEach(() => {
        driver = new seleniumWebDriver.Builder()
            .forBrowser("chrome")
            .build();

        return driver.navigate().to("https://website.mine/")
            .then(() => driver.wait(until.elementLocated(By.id("login-username"))))
            .then(() => driver.findElement(By.id("login-username")).sendKeys("admin"))
            .then(() => driver.findElement(By.id("login-password")).sendKeys("admin"))
            .then(() => driver.findElement(By.tagName("button")).click())
            .then(() => driver.wait(until.elementLocated(By.css(".app-container-inner"))));
    });

    it("should have favorites card", () => driver.findElement(By.css(".start-view-favourites-list")).then(element => expect(element).toBeDefined()));

    afterEach(() => {
        driver.close();
        driver.quit();
    });
});

**Comment by jleyba** [comment]
Your `afterEach` isn't waiting for the promise returned by `driver.quit`.

```javascript
afterEach(() => driver.quit());
```

**Comment by jonashartwig** [comment]
works. thanks :)
