### ISSUE TITLE
Add documentation regarding shardTestFiles option

### ISSUE THREAD

**Issue by nickalto** [SeleniumHQ/selenium#4264]
## Meta -
OS:  OS X 10.12.5
Selenium Version:  3.0.1 via (https://github.com/vvo/selenium-standalone/commit/bc4021e764a628cea52e2e4e1b0ee06c2340bffc)
Browser:  N/A

## Expected Behavior -
Expected to see documentation regarding the `shardTestFiles` configuration option. 

## Actual Behavior -
Did not see any documentation regarding the `shardTestFiles` configuration option.

**Comment by cgoldberg** [comment]
@nickalto,

`shardTestFiles` is not a Selenium capability.  It's a configuration option specific to Protractor framework (which you must be using).

Protractor issues can be logged at: https://github.com/angular/protractor/issues

FWIW, `shardTestFiles` is used to specify that a set of files will run in parallel.
see: https://github.com/angular/protractor/blob/5.1.2/lib/config.ts#L285

**Comment by p0deje** [comment]
Per @cgoldberg comment, I'm closing this as not a Selenium issue.
