### ISSUE TITLE
Add documentation of refresh query parameter for Grid console

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/selenium#4273]
In #4189 it was suggested to add `refresh` query parameter for Grid console. However, Grid already has it - it's just not documented anywhere.

We need to add documentation for this parameter. I can do that if somebody points me where Grid documentation lives.

See discussion in #4189 for more details.

**Comment by diemol** [comment]
Grid 3.x is not under development anymore so I think we wono't be making changes in the docs for this.
