### ISSUE TITLE
Selenium gives back wrong number of open Tabs using Firefox

### ISSUE THREAD

**Issue by DavidGangel** [SeleniumHQ/selenium#4276]
## Meta -
OS:  Mac OS Sierra
Selenium Version:  Selenium 3.4.0
Browser:  Firefox 54.0.1 (64bit)

## Expected Behavior -
A new tab opens with the loaded PDF file. In SUM you have 2 tab opened. Selenium should return that there are 2 tabs.

## Actual Behavior -
List<String> tabs = new ArrayList<>(driver.getWindowHandles());
Assert.assertTrue(tabs.size() > 1, "New PDF window was not opened after clicking PDF button");
These lines are telling that there is only one tab opened.
The same test passes on Chrome.

## Steps to reproduce -
1. Open the URL:
http://www.audi-boerse.de/gebrauchtwagen/audi/a3/a3-sportback/celle/diesel/automatik/105ps-frontantrieb-silber-2_DEU52183F-8236.htm#/i/s/l|12,1,STAT_GWPLUS,U
2. Click on the "Druckoptionen"
3. Click on the PDF

**Comment by lmtierney** [comment]
This probably has to do with how Mozilla's PDF viewer works, it may not be considered a tab. Either way, this would be an issue with geckodriver/Firefox.

Please log an issue with Mozilla: github.com/mozilla/geckodriver

**Comment by DavidGangel** [comment]
Thank you.
Logged under: https://github.com/mozilla/geckodriver/issues/812
