### ISSUE TITLE
SlowLoadableComponent ignores UnableToLoadMessage

### ISSUE THREAD

**Issue by al007** [SeleniumHQ/selenium#4281]
## Meta
OS:  All

Selenium Version:  3.4.0 .NET

Browser:  Any

Browser Version:  Any

## Expected Behavior
When a SlowLoadableComponent instance throws a timeout exception on load, the message should include the UnableToLoadMessage.

## Actual Behavior
When a SlowLoadableComponent instance throws a timeout exception on load, the UnableToLoadMessage is not included into the message.

## Steps to reproduce

1. Write a PageObject class and extend it from SlowLoadableComponent.
2. In the EvaluateLoadedStatus method, set a custom message to UnableToLoadMessage property.
3. Call the .Load() method of the PageObject.
4. Notice that the generic timeout message is thrown out and the UnableToLoadMessage is ignored.

```
    class ExamplePage : SlowLoadableComponent<ExamplePage>
    {
        // ...
        protected override bool EvaluateLoadedStatus()
        {
            UnableToLoadMessage = "Unable to load example reason";
            return false;
        }
    }

    // ...

    function TestMethod()
    {
        // throw, but the message does not include "Unable to load example reason"
        new ExamplePage(...).Load();  
    }

```

## Source Code Bug Location
https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/support/UI/SlowLoadableComponent%7BT%7D.cs#L107-L108

**Comment by diemol** [comment]
Is this still valid in the most recent version of the .NET bindings?

**Comment by diemol** [comment]
Closing as we did not get more information. If this issue still exists with the latest versions, please feel free to open a new issue with all the required information on the template.
