### ISSUE TITLE
Selenium ide "Table view is not available in this format"

### ISSUE THREAD

**Issue by venkatakaushik1** [SeleniumHQ/selenium#4283]
## Meta -
OS:  Windows 8.1

Selenium Version:  2.9.1

Browser:  Firefox

## Steps to reproduce -

![table view](https://user-images.githubusercontent.com/8932110/27991485-1cb448b2-6496-11e7-9010-1e29b9c3f1f1.JPG)

**Comment by barancev** [comment]
Please change format to HTML (Options -> Format -> HTML), table view is available for HTML format only.
