### ISSUE TITLE
click() fails to bring clickability to an element which is not clickable

### ISSUE THREAD

**Issue by raffam** [SeleniumHQ/selenium#4284]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.3

Browser:  Firefox

Browser Version:  54.0.1

## Summary -
This bug is related to #4280 but regards the `click()` function
In #4280, the `location_once_scrolled_into_view()` function brought a link behind a navbar, rendering it not clickable, and the WebDriver failed to issue an exception
In this report, the link is already behind a navbar, and the `click()` function fails to render the element _clickable_. (using the terminology I learnt in that report)

## Expected Behavior -
`click()` would render the element _clickable_ (uniquely selectable by its coordinates) and then click on it

## Actual Behavior -
The link is not clicked

## Steps to reproduce -

Substitute username and password with the one of your LinkedIn account.
Since the link is not clicked, you will enter an infinite loop.
If you go in the browser windows and manually scroll up a bit (to have the link not only in the viewport but clickable), the link gets clicked, the loop finishes and the program concludes

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

username = "caloman@email.com"
password = "MarcoPolo32"
css_selector = ".pv-profile-section__see-more-inline.link"
url = "https://www.linkedin.com/in/enriqueaguilera/"

def sessionKeyLogin(driver):
    print("Logging in")
    signin_link = driver.find_element_by_class_name("sign-in-link")
    signin_link.click()
    time.sleep(5)
    login_email_element = driver.find_element_by_id("session_key-login")
    login_password_element = driver.find_element_by_id("session_password-login")
    login_email_element.clear()
    login_password_element.clear()
    login_email_element.send_keys(username)
    login_password_element.send_keys(password)
    login_password_element.submit()
    time.sleep(5)
    
#MAIN
driver = webdriver.Firefox()
driver.get(url)
time.sleep(5)

#Log in
sessionKeyLogin(driver)

#Without scrolling, the experience-section is not in the DOM and thus it is not found
for i in range(7):
    print("Scrolling")
    driver.execute_script("window.scrollBy(0,500)")
    time.sleep(2)

#Click on links
exp_section = driver.find_element_by_class_name("experience-section")

#This will generate an infinite loop because the link is never clicked
#If you go in the browser windows and manually scroll up a bit, the link gets clicked, the loop finishes and the program concludes
while True:
    link_list = exp_section.find_elements_by_css_selector(css_selector)
    count = len(link_list)
    print("Found "+str(count)+" links")
    if count==0:
        break
    for link in link_list:
        #if you uncomment this line, it works
        #driver.execute_script('window.scrollBy(0,-50)')
        print("Clicking on the link tag='"+link.tag_name+"' text='"+link.text+"'")
        link.click()
        time.sleep(2)

#driver.quit()
print("Ended!!!")
```

**Comment by p0deje** [comment]
Isn't it the same as mozilla/geckodriver#813?

**Comment by raffam** [comment]
Yes, sorry. I didn't think enough. The specification says, as you did, that in this case the command should throw an exception

> If the element’s center point is obscured by another element, an element click intercepted error is returned.

So it should not make the element visible. So I guess it's the user responsibility to catch the exception and make the element visible.

Moreover

>  If the element is outside the viewport, an element not interactable error is returned.

While Selenium brings the element into the viewport, so it already does more than it should
