### ISSUE TITLE
Jenkins is not identifying the chromedriver.exe. The same code I can able to run using testng

### ISSUE THREAD

**Issue by KVasanthaKumari** [SeleniumHQ/selenium#4287]
## Meta -
OS:  
Windows 7, 64 bit 64 GB
Selenium Version:  
Selenium3.0
Browser:  
Chrome/Firefox

Browser Version:  
Chrome v59
## Actual Behavior -
FAILED CONFIGURATION: @BeforeClass startCQ(1, 4445)
   [testng] java.lang.IllegalStateException: The driver executable does not exist: C:\Users\admin.dell\workspace\lib\drivers\chromedriver.exe
   [testng] 	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
   [testng] 	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:121)
   [testng] 	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:116)
   [testng] 	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
   [testng] 	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
   [testng] 	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
   [testng] 	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
   [testng] 	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:116)
   [testng] 	at com.axa.base.TestBaseSetup.initChromeDriver(Unknown Source)
   [testng] 	at com.axa.tests.CreateQuotation.startCQ(Unknown Source)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   [testng] 	at java.lang.reflect.Method.invoke(Unknown Source)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:617)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
   [testng] 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
   [testng] 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
   [testng] 	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
   [testng] 	at java.util.concurrent.FutureTask.run(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   [testng] 	at java.lang.Thread.run(Unknown Source)
   [testng]

**Comment by lukeis** [comment]
This path likely doesn't exist on your jenkins machine:

C:\Users\admin.dell\workspace\lib\drivers\chromedriver.exe

This also would be better suited as a discussion on the selenium users mailing list:

https://groups.google.com/forum/#!forum/selenium-users

**Comment by KVasanthaKumari** [comment]
The path is available

**Comment by hiteshgpt7** [comment]
is there any update on this  i have also facing same issue when i am running in jenkins but when i am running from eclipse it's working fine

**Comment by cgoldberg** [comment]
@hiteshgpt7 
this was a poorly described issue containing almost no information... and it was closed nearly 2 years ago.. so don't wait around for an update to it.  If you have a similar poroblem, please open a new issue with clear descriptions an other requested information.
