### ISSUE TITLE
Add support for W3C Fullscreen Window command

### ISSUE THREAD

**Issue by Frankstar** [SeleniumHQ/selenium#4290]
as stated by mozilla here https://bugzilla.mozilla.org/show_bug.cgi?id=1189749
fullScreen has been implemented now.

Manjaro 17.02 / 4.11.8-1
Aurora 56.0a1
geckodriver v0.17.0
selenium 3.4.3
python3

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

geckodriver = "/opt/geckodriver"
capabilities = DesiredCapabilities.FIREFOX
capabilities["marionette"] = True
browser = webdriver.Firefox(capabilities=capabilities, executable_path=geckodriver)
browser.fullscreen() gives me
```

> 'WebDriver' object has no attribute 'fullscreen'

so its missing in selenium client.

**Comment by lmtierney** [comment]
Generally we support the stable versions of the browsers, which this is not implemented in yet. That being said, the bindings will need to be updated in order to support it. I'll tag the ones that do not currently implement it.

**Comment by Frankstar** [comment]
Any Updates on this - i know Stable 55 is only out for 4 Days - but still asking, mayb you worked in background :)

**Comment by lmtierney** [comment]
Implemented in python in 7670b28

**Comment by lmtierney** [comment]
Also looks like it is in dotnet as of d6d0cb6, closing

**Comment by Frankstar** [comment]
so this will be in the 3.7 release when it hits PIP / PyPi ?
also the command will be ` webdriver.fullscreen_window()` ?

Thank you for your efford

**Comment by lmtierney** [comment]
@Frankstar yes, it will be in the `3.7` release. It is `fullscreen_window` to follow the same order as the other window commands in python such as `maximize_window` and  `minimize_window`. Also note that most other languages have the `fullscreen` method off of a `window` class or something along those lines. Python does not have this extra `window` class.
