### ISSUE TITLE
IEDriverServer doesn't handle concurrent requests correctly

### ISSUE THREAD

**Issue by juangj** [SeleniumHQ/selenium#4293]
## Meta -
OS:  Windows 7
Selenium Version:  IEDriver 3.3.0.0 is what I happened to be using (I didn't any changes that would have fixed this in a more recent build, but I can double-check with a newer release later)
Browser:  IE11, but it shouldn't matter

cc @jimevans 

## Steps to reproduce -
Send two commands to the IEDriverServer concurrently (i.e., with the second request arriving before the first response is sent).

This script reproduces the problem pretty reliably for me:

```py
import multiprocessing
import sys

from selenium import webdriver
from selenium.common import exceptions

driver = webdriver.Remote(
    command_executor=sys.argv[1],
    desired_capabilities={})

def Execute(id):
  print 'starting thread', id
  for n in xrange(3):
    try:
      want = 'thread %s, request %s' % (id, n)
      script = 'return "%s";' % want
      got = driver.execute_script(script)
      if got != want:
        print 'ERROR: (%s) returned %s' % (script, got)
    except exceptions.WebDriverException as e:
      print 'ERROR: (%s) exception %s' % (script, e)

p1 = multiprocessing.Process(target=Execute, args=(1,))
p2 = multiprocessing.Process(target=Execute, args=(2,))
p1.start()
p2.start()
p1.join()
p2.join()
```

Start IEDriver (WLOG let's say it's on port 4444), then run `python example.py http://localhost:4444`. Some sample output, which will of course differ a little every time:
```
starting thread 1
starting thread 2
ERROR: (return "thread 2, request 0";) returned thread 1, request 0
ERROR: (return "thread 1, request 0";) exception Message: Error 404: Not Found
Not Found

ERROR: (return "thread 1, request 1";) returned thread 2, request 0
ERROR: (return "thread 1, request 2";) returned thread 2, request 1
ERROR: (return "thread 2, request 1";) returned thread 1, request 2
ERROR: (return "thread 2, request 2";) returned thread 1, request 2
```

Full trace log from IEDriver here: https://gist.github.com/anonymous/f25108e2679431caaef5dc4a2d4cbfac

**Comment by juangj** [comment]
If I remember right, something in the W3C spec requires the server to behave as if it were processing requests in series. It's not useful to try to run more than one command simultaneously for a session anyway, so it would be fine for the second request to just block until the first one has been serviced. And clients normally shouldn't be attempting to send concurrent requests, because nothing useful will happen.

I think the Selenium standalone server actually prevented concurrent requests from occurring, until recently (possibly until f605b73595c4d25358ab6d64b81cec3f1a36269e ?). Only one thread per session forwarded requests to the remote driver, so requests were forwarded to the driver in series.

**Comment by juangj** [comment]
OK, confirmed that this also happens on IEDriverServer 3.4.0.1 (the prebuilt that's currently checked in on master).

**Comment by barancev** [comment]
Do any other drivers support concurrent requests?

**Comment by juangj** [comment]
I believe ChromeDriver and Geckodriver simply serve the requests in series: the one that arrives second is blocked until the first response is sent. In that respect, drivers should not service requests concurrently -- in fact, it's forbidden to do so if the requests are for the same session. But in another respect, the driver is an HTTP server and should not mix up requests like this.

**Comment by savsav** [comment]
Has there been a decision on this issue? It is being reproduced with javascript frameworks (such as WebdriverIO). It is easy to send off multiple requests at once with the asynchronous js nature.

**Comment by christian-bromann** [comment]
> In that respect, drivers should not service requests concurrently

@juangj Why not? It would speed up the test execution time if drivers would be able to do that. Especially when using a cloud backend like Sauce Labs or Browserstack where requests take longer it can be a beneficial time saving.

**Comment by juangj** [comment]
I don't remember why I would have written it that way -- I probably meant to say that the driver should not _be required to_ do so. It seems like it would be fine for a driver to queue multiple requests and process them in series, or even to optimize by executing non-state-changing commands concurrently.

**Comment by diemol** [comment]
While going through the spec, I see in the [processing model](https://www.w3.org/TR/webdriver/#processing-model) that requests for an existing session need to be queued.
The IEDriverServer is W3C compliant... is this still happening with version 3.150.1?

**Comment by diemol** [comment]
I am going to close this due to the lack of activity and the absence of more reports around this topic. If needed, we can reopen and dig deeper.
