### ISSUE TITLE
Jetty version mismatch in Maven pom for Selenium-java

### ISSUE THREAD

**Issue by paul-hammant** [SeleniumHQ/selenium#4295]
See http://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.4.0

Two Jetty jars at 9.4.1.v20170120 and three Jetty jars at 9.4.3.v20170317

It works, but it would be best if these were in lock step because that's how Jetty itself ships.

**Comment by barancev** [comment]
It seems to be fixed in trunk, all jetty-related dependencies are updated to 9.4.5, see https://github.com/SeleniumHQ/selenium/tree/master/third_party/java

**Comment by paul-hammant** [comment]
What does `mvn dependency:tree` report for a trunk build of WebDriver?

I ask, because transitive deps is where the same problem can manifest itself. I would check myself, but the selenium build doesn't complete on my Mac.
