### ISSUE TITLE
getScreenshotAs() function can't get full website screenshot

### ISSUE THREAD

**Issue by AnneGuo** [SeleniumHQ/selenium#4300]
## Meta -
OS:  
Windows7
Selenium Version:  
Selenium 2.53
Browser:  
Firefox 45.3.0 ESR

## Actual Behavior -
When I use getScreenshotAs() function to get screenshot,get the screenshot is incomplete,The screenshot's footer is empty.
## Steps to reproduce -
public static void screenCapture1(TakesScreenshot drivername, String dirname,String filename) {
		// this method will take screen shot ,require two parameters ,one is
		// driver name, another is file name
		File scrFile = drivername.getScreenshotAs(OutputType.FILE);
		try {
			System.out.println("save snapshot path is:"+dirname+"/" + filename);
			FileUtils.copyFile(scrFile, new File(dirname+ "/"+filename));
		} catch (IOException e) {
			System.out.println("Can't save screenshot");
			e.printStackTrace();
		}
	}

**Comment by p0deje** [comment]
Selenium team no longer supports old Firefox driver. In newer versions you should use GeckoDriver which is developed by Mozilla. Please, upgrade and reopen the issue if it is still reproducible.

**Comment by AnneGuo** [comment]
I had used GeckoDriver to get screenshot ,but the screenshot is not the full website screenshot. I had referred to https://github.com/SeleniumHQ/selenium/issues/3952 for help.I want to scroll to get full website screenshot,so I choose selenium 2.53 and firefox 45.3.0 ESR.I got the full website screen ,but the website is so long,the screenshot's footer is empty.

**Comment by p0deje** [comment]
This is what W3C WebDriver tells to do - only take a screenshot of the current viewport (https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot). If you need to take a screenshot of full web page, you can take one, scroll down, take another one and repeat until you reach the end of the page.

If you disagree, I'd recommend raising an issue to https://github.com/w3c/webdriver.
