### ISSUE TITLE
Add suppport find_by_accessibility_id for WinAppdriver

### ISSUE THREAD

**Issue by camillake** [SeleniumHQ/selenium#4301]
OS:  Windows 10
Selenium Version:  3.4.3 (python client)
Target testing app:  WPF app

**Comment by p0deje** [comment]
This support should be added in Appium or WinAppdriver client, not in Selenium.

**Comment by camillake** [comment]
@p0deje I use Selenium (python) as a WinAppdriver client to forward request to WinAppDriver server. Do you mean there is no plan to implement find_by_accessibility_id in selenium?

**Comment by p0deje** [comment]
Yes, Selenium implements W3C WebDriver specification and doesn't deal with desktop/mobile applications.
