### ISSUE TITLE
Run As different user in ChromeDriverService service

### ISSUE THREAD

**Issue by shlathsaheb** [SeleniumHQ/selenium#4307]
Can you add the run as different user option with chrome driver when we start the chrome process?

**Comment by p0deje** [comment]
Can you be more specific? What are you trying to achieve? What language do you use?

**Comment by shlathsaheb** [comment]
@p0deje : We are using C#.net. We follow windows auth. so would like to open chrome with different user credentials in same test to verify our authorization test cases. To be able to achieve that we need ability to run chrome as another user.
Currently chrome process start is abstract inside driverservice, so if possible in chrome driver we get an option to have user credentials as well to run chrome as another user?
Or if you have any other solution to the above described problem kindly share.

**Comment by p0deje** [comment]
I am not sure how this is implemented, but can't you run your script as a different user?

**Comment by jimevans** [comment]
We won't be adding a Windows-only feature to a cross-platform API. You can have your test runner run the entire test as a different user, or you can customize a subclass of `ChromeDriverService` to accomplish this.

**Comment by NehaBhatia28** [comment]
Hi,
I am using selenium remote webdriver and hitting the application on Single sign-on enabled remote machine.My application get login with the same user which I have used during login into remote machine. I want to run the application with different users while running tests but I am not able to do due to single sign-on.It is not giving working but I am not able to switch the user.it is always logged-in with the user which I used for login in the remote machine. The code looks like below:

WebDriver driver = null;
        ChromeOptions options = new ChromeOptions();
        options.addArguments(TEST_TYPE);
        options.addArguments(DISABLE_POPUP_BLOCKING);
        if(nodeName.equals("Level2"))
            options.addArguments("user-data-dir=C:/Users/Level2/AppData/Local/Google/Chrome/User Data/Default");
        else if(nodeName.equals("Level1"))
            options.addArguments("user-data-dir=C:/Users/Level1/AppData/Local/Google/Chrome/User Data/Default");
        DesiredCapabilities cap = DesiredCapabilities.chrome();
        cap.setCapability(ChromeOptions.CAPABILITY, options);
        cap.setBrowserName("chrome");
        cap.setCapability("applicationName", nodeName);
        String Node;
        if (System.getProperty("hubUrl") == null){
            Node = "http://" + hubIpaddress + ":" + hubPort + "/wd/hub";
        }else{
            Node = System.getProperty("hubUrl", "http://localhost:4444/wd/hub");
        }     
        System.out.println("---Node----"+Node);
        try {
            driver = new RemoteWebDriver(new URL(Node), cap);

**Comment by amirse80** [comment]
@NehaBhatia28, May I ask you if you have sloved this issue in some way?
We are facing same problem and I am trying to find out a solution on how to start the browser with another user than the one currently looged in?

**Comment by giznaj** [comment]
I am also having the same issue.  VSTS running selenium tests in C# and the browser is always instantiated with the current user on the target machine.  I don't have a solution, but I will try and add to this (workaround for now).

**Comment by giznaj** [comment]
For anyone looking at the workaround or resolution for this, you can visit here < https://www.gerbenvanadrichem.com/quality-assurance/how-to-get-selenium-to-run-the-browser-as-a-different-user/ > and use this solution if you have Selenium Grid in use.  I will continue to see what you can do without Grid
