### ISSUE TITLE
Operation has timed out error after loading the WebSite

### ISSUE THREAD

**Issue by dhapolapankaj** [SeleniumHQ/selenium#4312]
## Meta -
OS:  Windows 2016 server

Selenium Version:  

WebDriver.dll - 2.53.0.0

Browser:  
Internet Explorer

Browser Version:  
11.321.14393.0
Update Versions 11.0.36

## Expected Behavior -
The WebSite should have loaded correctly

## Actual Behavior -
The WebSite is loaded but Selenium do not move ahead and after approx 6 mins shows error saying "Operation has timesd out

## Steps to reproduce -

Please find attached log.

[IEDriver2.53_32bit_log.txt](https://github.com/SeleniumHQ/selenium/files/1148004/IEDriver2.53_32bit_log.txt)

This site contains iFrame and the website is loaded correctly
Below is excerpt from log
I 2017-07-14 04:00:15:487 server.cc(86) Starting WebDriver server on port: '53447' on host: ''
I 2017-07-14 04:00:15:488 IEServer.cpp(32) Driver version: 2.53.1.0 (32-bit)
D 2017-07-14 04:00:15:488 server.cc(148) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2017-07-14 04:00:16:196 server.cc(281) Command: GET /status {}
D 2017-07-14 04:00:16:198 server.cc(355) Response: {"sessionId":"","status":0,"value":{"build":{"version":"2.53.1.0 (32-bit)"},"os":{"arch":"x64","name":"windows","version":"10.0.14393.206 (rs1_release.160915-0644)"}}}

D 2017-07-14 04:00:16:199 server.cc(281) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":false,"enablePersistentHover":true,"initialBrowserUrl":"about:blank","unexpectedAlertBehaviour":"ignore","browserAttachTimeout":30000}}
D 2017-07-14 04:00:16:213 IESession.cpp(51) Mutex acquired for session initalization
D 2017-07-14 04:00:16:215 IESession.cpp(96) Using legacy driver implementation per user request
D 2017-07-14 04:00:16:229 IESession.cpp(130) Releasing session initialization mutex
D 2017-07-14 04:00:16:229 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","nativeEvents":false,"enablePersistentHover":true,"initialBrowserUrl":"about:blank","unexpectedAlertBehaviour":"ignore","browserAttachTimeout":30000}} }
D 2017-07-14 04:00:16:230 BrowserFactory.cpp(80) Ignoring Protected Mode Settings: 0
D 2017-07-14 04:00:16:230 BrowserFactory.cpp(83) Checking validity of Protected Mode settings.
D 2017-07-14 04:00:16:230 BrowserFactory.cpp(995) Detected IE version: 11, Windows version supports Protected Mode: 1
D 2017-07-14 04:00:16:230 BrowserFactory.cpp(1086) Found Protected Mode setting value of 0 for zone 1
D 2017-07-14 04:00:16:230 BrowserFactory.cpp(1086) Found Protected Mode setting value of 0 for zone 2
D 2017-07-14 04:00:16:231 BrowserFactory.cpp(1086) Found Protected Mode setting value of 0 for zone 3
D 2017-07-14 04:00:16:231 BrowserFactory.cpp(1086) Found Protected Mode setting value of 0 for zone 4
D 2017-07-14 04:00:16:231 BrowserFactory.cpp(86) Has Valid Protected Mode Settings: 1
D 2017-07-14 04:00:16:246 BrowserFactory.cpp(182) Starting IE using the IELaunchURL API
D 2017-07-14 04:00:16:506 BrowserFactory.cpp(136) IE launched successfully with process ID 11076
D 2017-07-14 04:00:16:506 BrowserFactory.cpp(142) Process with ID 11076 is executing iexplore.exe
D 2017-07-14 04:00:16:506 BrowserFactory.cpp(309) Using Active Accessibility to find IWebBrowser2 interface
D 2017-07-14 04:00:17:275 BrowserFactory.cpp(368) Found window handle 005D0328 for window with class 'Internet Explorer_Server' belonging to process with id 11076
D 2017-07-14 04:00:17:428 BrowserFactory.cpp(330) Ignoring zoom setting: 0
D 2017-07-14 04:00:17:508 BrowserFactory.cpp(628) Browser zoom level is 100%
I 2017-07-14 04:00:17:513 IECommandExecutor.cpp(678) Persistent hovering set to: 0
I 2017-07-14 04:00:17:513 IECommandExecutor.cpp(680) Stopping previously-running persistent event thread.
D 2017-07-14 04:00:17:513 ProxyManager.cpp(106) Using existing system proxy settings.
D 2017-07-14 04:00:17:524 server.cc(355) Response: {"sessionId":"1699b954-305d-4243-858f-b1fdaac99529","status":0,"value":{"browserAttachTimeout":30000,"browserName":"internet explorer","elementScrollBehavior":0,"enableElementCacheCleanup":true,"enablePersistentHover":false,"ie.browserCommandLineSwitches":"","ie.enableFullPageScreenshot":true,"ie.ensureCleanSession":false,"ie.fileUploadDialogTimeout":3000,"ie.forceCreateProcessApi":false,"ie.forceShellWindowsApi":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"about:blank","javascriptEnabled":true,"nativeEvents":false,"pageLoadStrategy":"normal","platform":"WINDOWS","requireWindowFocus":false,"unexpectedAlertBehaviour":"ignore","version":"11"}}

D 2017-07-14 04:00:17:526 server.cc(281) Command: POST /session/1699b954-305d-4243-858f-b1fdaac99529/timeouts {"type":"page load","ms":-1.0}
D 2017-07-14 04:00:17:527 command.cc(36) Raw JSON command: { "name" : "timeouts", "locator" : { "sessionid" : "1699b954-305d-4243-858f-b1fdaac99529" }, "parameters" : {"type":"page load","ms":-1.0} }
D 2017-07-14 04:00:17:527 IECommandExecutor.cpp(572) No alert handle is found
D 2017-07-14 04:00:17:538 server.cc(355) Response: {"sessionId":"1699b954-305d-4243-858f-b1fdaac99529","status":0,"value":null}

D 2017-07-14 04:00:17:540 server.cc(281) Command: POST /session/1699b954-305d-4243-858f-b1fdaac99529/timeouts {"type":"implicit","ms":1000.0}
D 2017-07-14 04:00:17:540 command.cc(36) Raw JSON command: { "name" : "timeouts", "locator" : { "sessionid" : "1699b954-305d-4243-858f-b1fdaac99529" }, "parameters" : {"type":"implicit","ms":1000.0} }
D 2017-07-14 04:00:17:540 IECommandExecutor.cpp(572) No alert handle is found
D 2017-07-14 04:00:17:551 server.cc(355) Response: {"sessionId":"1699b954-305d-4243-858f-b1fdaac99529","status":0,"value":null}

D 2017-07-14 04:00:17:552 server.cc(281) Command: POST /session/1699b954-305d-4243-858f-b1fdaac99529/url {"url":"http://localhost/ADCC00_AFS.Claims/Desktop/HomePage/Default.aspx?src=%2fADCC00_AFS.Claims%2fDesktop%2fHomePage%2fHomePage.aspx&StaticPulseMode=true&IframeMode=true"}
D 2017-07-14 04:00:17:553 command.cc(36) Raw JSON command: { "name" : "get", "locator" : { "sessionid" : "1699b954-305d-4243-858f-b1fdaac99529" }, "parameters" : {"url":"http://localhost/ADCC00_AFS.Claims/Desktop/HomePage/Default.aspx?src=%2fADCC00_AFS.Claims%2fDesktop%2fHomePage%2fHomePage.aspx&StaticPulseMode=true&IframeMode=true"} }
D 2017-07-14 04:00:17:553 IECommandExecutor.cpp(572) No alert handle is found
D 2017-07-14 04:00:17:555 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:17:556 Browser.cpp(478) Browser ReadyState is not at least '4'; it was 1
D 2017-07-14 04:00:17:758 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:17:850 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:18:054 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:18:276 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:18:485 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:18:521 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:18:776 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:18:777 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:18:984 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:19:014 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:19:216 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:19:217 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:19:418 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:19:419 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:19:620 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:19:621 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:19:822 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:19:823 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:20:024 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:20:025 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:20:227 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:20:229 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:20:430 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:20:431 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:20:632 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:20:634 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:20:836 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:20:837 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:21:042 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:21:045 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:21:248 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:21:252 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:21:455 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:21:457 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:21:660 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:21:661 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:21:862 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:21:864 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:22:322 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:22:323 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:22:537 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:22:559 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:22:760 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:23:206 Browser.cpp(478) Browser ReadyState is not at least '4'; it was 3
D 2017-07-14 04:00:23:484 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:24:087 Browser.cpp(478) Browser ReadyState is not at least '4'; it was 3
D 2017-07-14 04:00:24:297 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:24:619 Browser.cpp(478) Browser ReadyState is not at least '4'; it was 3
D 2017-07-14 04:00:24:820 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:24:861 Browser.cpp(478) Browser ReadyState is not at least '4'; it was 3
D 2017-07-14 04:00:24:899 ElementRepository.cpp(110) Refreshing managed element cache. Found 0 to remove from cache.
D 2017-07-14 04:00:25:064 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:25:276 Browser.cpp(502) Waiting for document to complete...
D 2017-07-14 04:00:25:952 Browser.cpp(540) document.readyState is not 'complete'; it was interactive
D 2017-07-14 04:00:26:211 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:26:235 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:26:468 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:26:469 Browser.cpp(458) Browser busy property is true.
D 2017-07-14 04:00:26:670 Browser.cpp(442) Navigate Events Completed.
D 2017-07-14 04:00:26:671 Browser.cpp(458) Browser busy property is true.

**Comment by jimevans** [comment]
The problem is not with the driver, it's with the website. For whatever reason, the site is not allowing the browser to complete its loading process fully. Note that the `readyState` property of the document does not ever get to "complete", but only gets to "interactive". Setting the page load strategy to "eager" instead of "normal" should let the test proceed. This is according to the design of the driver, and in compliance with the W3C WebDriver specification for navigating to a page.

**Comment by dhapolapankaj** [comment]
Okay Cool. Let me try that Sir!
