### ISSUE TITLE
Documentation for selenium-webdriver ... shortcomings

### ISSUE THREAD

**Issue by mrt123** [SeleniumHQ/selenium#4313]
Hi Guys, 

There is a fundamental difference on how  "selenium-webdriver" npm module works compared to other popular webdriver javascript implementations wd.js or webdriverIO. And although users are aware of advantages/ disadvantages of different api styles, there isn't much knowledge among users on what's the fundamental difference.  Eg. when you use "selenium-webdriver" you do not need to manage a standalone instance of selenium server (when every other webDriver implementation requires you to have it). This is something "selenium-webdriver" should take pride in, and expose in its documentation. Questions like these could be answered:
* Does the node process communicate with browser driver directly? 
* Whats thats the performance implication.
* Whats the maintenance implication.

If there other fundamental differences, it'll be nice to document.

At the moment we get a very mixed/incomplete perception of "selenium-webdriver":
[Stackoverflow - differences (and when to use) selenium-webdriver over webdriverjs?](https://stackoverflow.com/questions/21609040/what-are-the-differences-and-when-to-use-selenium-webdriver-over-webdriverjs).

Can we update documentation to clarify this?

**Comment by p0deje** [comment]
I'd say that pull requests are more than welcome!

**Comment by diemol** [comment]
This issue has gone stale, in addition to that, we have a page showing many available tools and frameworks in the ecosystem https://www.selenium.dev/ecosystem/
But documenting the internals of them is not really the project's responsibility.
