### ISSUE TITLE
Element Not Interactable Exception in selenium

### ISSUE THREAD

**Issue by GuruMca** [SeleniumHQ/selenium#4314]
org.openqa.selenium.ElementNotInteractableException: 
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-VHGNNQB', ip: '192.168.137.136', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\anura\AppData\Local\Temp\rust_mozprofile.xeVg7XMWjr9v, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=10.0, moz:processID=8444.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: f989aad7-a1b0-4ad4-8a00-2c9fb6d8d4bb

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by GuruMca** [comment]
When login with valid user credentials ,after login should verify logout link and should perform logout operation.
Please find the attached code for 

@Test
	public void login() throws Exception {
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		driver.findElement(By.id("txtUsername")).sendKeys("Admin");
		driver.findElement(By.id("txtPassword")).sendKeys("admin");
		driver.findElement(By.id("btnLogin")).click();
		//Click on Admin button
		driver.findElement(By.xpath(".//*[@id='welcome']")).click();
		Thread.sleep(50);
               // Click on logout button under admin menu
		driver.findElement(By.xpath(".//*[@id='welcome-menu']/ul/li[2]/a")).click();
		
	}

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) including a page where the issue can be reproduced.

**Comment by GuruMca** [comment]
//Click on Admin button
driver.findElement(By.xpath(".//[@id='welcome']")).click();
Thread.sleep(50);
// Click on logout button under admin menu
driver.findElement(By.xpath(".//[@id='welcome-menu']/ul/li[2]/a")).click();

After login,Admin page element is not working on click

**Comment by GuruMca** [comment]
![screenshot 7](https://user-images.githubusercontent.com/24816151/28258065-c383d138-6aec-11e7-8a04-1d22c563f677.png)

I have attached screenshot,I have login into http://opensource.demo.orangehrmlive.com/ with valid credentials ,Then its redirected to Adimin page url http://opensource.demo.orangehrmlive.com/index.php/dashboard
In this page i want to click on Welcome Admin--> Logout 
This operation i am get error 
org.openqa.selenium.ElementNotInteractableException:

Kindly help to do this

**Comment by GuruMca** [comment]
Dear barancev
 
   Can you please suggest how can i solve my problem,till now i facing this issue

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) that includes all the required preparation steps (opens the page, performs login, does whatever it should, and fails with the described exception). So we'll be able to take your scenario, run it and reproduce the error.

**Comment by mansigit86** [comment]
@GuruMca  Please try the below code on your WebElement and let us know if it works-

WebElement element=driver.findElement(By.xpath(".//[@id='welcome-menu']/ul/li[2]/a"));
((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);

**Comment by barancev** [comment]
I've reproduced the issue, but it's the target site issue. Element `//*[@id='welcome']` is not immediately ready to click on, it does not respond. You have to add a longer pauses or use some other waiting strategy:
```
//Click on Admin button
Thread.sleep(3000);
driver.findElement(By.xpath(".//*[@id='welcome']")).click();
// Click on logout button under admin menu
Thread.sleep(3000);
driver.findElement(By.xpath(".//*[@id='welcome-menu']/ul/li[2]/a")).click();
```

**Comment by prakash-maurya** [comment]
> @GuruMca Please try the below code on your WebElement and let us know if it works-
> 
> WebElement element=driver.findElement(By.xpath(".//[@id='welcome-menu']/ul/li[2]/a"));
> ((JavascriptExecutor)driver).executeScript("arguments[0].click();", element);

@mansigit86 : Thanks, use of JavascriptExecutor worked for me, I had similar issue on different application though.

**Comment by Ellky** [comment]
I have this issues too. Fixed by "execute script" command inside of that i append code "document.getElementById('nav_button_363').click();" in Selenium IDE.
