### ISSUE TITLE
Cannot Get Currently Selected Element

### ISSUE THREAD

**Issue by oriooctopus** [SeleniumHQ/selenium#4316]
I'm using safari and webdriver for this, and the problem arises when I open up an window, the input element that is immediately selected by default is the one I want to access, when I try to access it with 

> "driver.switchTo().activeElement())"

  I get this error

> Unhandled rejection WebDriverError: HTTP method 'POST' is not supported for command '/session/67ACFE2E-9EE8-4DCA-AA5C-EB947A40A6A8/element/active'.

I've been able to reproduce this error on other pages (without pop up windows). Is there any other way to access a currently selected element in selenium?

**Comment by barancev** [comment]
You forgot to report what browser and what driver do you use?

**Comment by oriooctopus** [comment]
You're right, thanks for noticing I just updated it

**Comment by metareven** [comment]
I am having the same issue when running our tests with Safari on browserstack.
I am using OS X Sierra and Safari 10.1, but it's difficult for me to know what version of the safari webdriver they are using

**Comment by p0deje** [comment]
It seems like SafariDriver doesn't implement this command. I can only recommend creating an issue at https://bugreport.apple.com/.
