### ISSUE TITLE
Invalid "Content-Encoding: None" header when downloading "IEDriverServer_x64_3.4.0.zip" from SeleniumHQ

### ISSUE THREAD

**Issue by qqilihq** [SeleniumHQ/selenium#4317]
When downloading e.g. this file: http://selenium-release.storage.googleapis.com/3.4/IEDriverServer_x64_3.4.0.zip from the SeleniumHQ website, the server sends a `Content-Encoding: None` HTTP header.

This header causes our build script (backed by Maven Wagon, backed by Apache HttpClient) to throw an exception. `None` does not seem to be a valid Content-Encoding, see e.g. [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding), probably it should rather be `identity`?

Any chance fixing this?

**Comment by juyeongkim** [comment]
+1 for `identity`

**Comment by diemol** [comment]
We have moved from Google Storage to GitHub releases, this should be fixed. 

Well, to be more precise, we do not have much control over the headers used by GitHub when downloading files.
