### ISSUE TITLE
 Timed out waiting for page load.

### ISSUE THREAD

**Issue by vashisthdeepak928** [SeleniumHQ/selenium#4319]
It is Code, I am running..

mport java.awt.Robot;
import java.util.concurrent.TimeUnit;

import org.bouncycastle.jcajce.provider.asymmetric.EC;
import org.openqa.selenium.By;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.internal.ProfilesIni;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.thoughtworks.selenium.Wait;

public class Bulkactivation {

	/**
	 * @param args
	 * @throws InterruptedException 
	 */
	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		WebDriver driver = new FirefoxDriver();
		int i;
		for(i=0;i<7;i++)
		{
			driver.get("http://10.1.75.78/Headend_v3.8/sms/upload/admin");
			driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.HOURS);
			//driver.manage().timeouts().implicitlyWait(10, TimeUnit.HOURS);
			
			driver.findElement(By.name("username")).sendKeys("admin");
			driver.findElement(By.name("password")).sendKeys("passwd");
			driver.findElement(By.linkText("Login")).click();
			driver.findElement(By.xpath(".//*[@id='menu']/ul[1]/li[9]/a")).click();
			driver.findElement(By.linkText("Bulk Activation")).click();
			
			
		 driver.findElement(By.name("filename")).sendKeys("/home/deepak/Desktop/new"+i+".csv");
		 System.out.print(i);
		 driver.findElement(By.xpath("//a[text()='Save']")).click();
		 driver.manage().timeouts().implicitlyWait(10, TimeUnit.HOURS);

When I am running this code getting one error " Timed out waiting for page load". It takes 25 minutes to upload one file and need to upload 5 files.

**Comment by barancev** [comment]
Unfortunately the issue is not actionable because http://10.1.75.78/ is an internal address and we can't reproduce the issue with the provided scenario.

As a workaround you can try to use an alternative page load strategy

        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability(CapabilityType.PAGE_LOAD_STRATEGY, "eager");
        WebDriver driver = new FirefoxDriver(new FirefoxOptions().addCapabilities(caps));
