### ISSUE TITLE
Actions during loops, multiple IWeb

### ISSUE THREAD

**Issue by robybyte** [SeleniumHQ/selenium#4322]
## Meta -
OS:  Windows 10 64 Bit

Selenium Version:  3.4.0 C#

Browser:  Chrome

Browser Version:  54.0.1 (32-Bit)

## Expected Behavior - 
Code: 
On this Website to test, there are only 16 objects. Not every element is deleteable. The first 12 Elements are not deletabe. 
```csharp
			Actions act = new Actions(wd);
			for (int i = 1; i <= 16; i++) {
				IWebElement tmp = wd.FindElement(By.XPath(".//*[@id='workflowGraph']/*[name()='svg']/*[name()='g']/*[name()='g'][2]/*[name()='g']["+ i +"]"));
				act.MoveToElement(tmp).Click(tmp).SendKeys(Keys.Delete).Perform();
			}
````
I expected that only the choosen button, it is below the g tag in original html, from my array will be the one to get the action. 

## Actual Behavior -
For i = 1: The first rect got the action. It is fine, expected and ok.
For i = 2: The first rect got the action after that the second rect got the action. 
...
For i = 12: The first, second, third, fourth ... eleventh got the action and than the twelfth got finally the action. 

This behaviour leeds to a misstake during my test case. Maybe the 11th is deleted and the program moves on the the twelfth, it tries to delete the 11th element twice. But it is allready deleted. So it crashes with some error. 
OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477700 

## Steps to reproduce -
Code from website for the xpath: 
```html
<div id="workflowGraph" style="height: 400px; overflow: auto; position: relative; display: flex;" oncontextmenu="return false;">
<svg style="width: 100%; height: 100%; display: block; min-width: 581px; min-height: 231px;">
<g>
    <g>
    <g>
        <!--16 Elements -->
        <g style="visibility: visible; cursor: move;" transform="translate(0.5,0.5)">
        <g style="cursor: move;">
        <g style="visibility: visible; cursor: move;" transform="translate(0.5,0.5)">
        <g style="cursor: move;">
        <g style="visibility: visible; cursor: pointer;" transform="translate(0.5,0.5)">
        <g style="cursor: pointer;">
        <g style="visibility: visible; cursor: pointer;" transform="translate(0.5,0.5)">
        <g style="cursor: pointer;">
        <g style="visibility: visible; cursor: move;" transform="translate(0.5,0.5)">
        <g style="cursor: move;">
        <g style="visibility: visible; cursor: move;" transform="translate(0.5,0.5)">
        <g style="cursor: move;">
        <g style="visibility: visible;" transform="translate(0.5,0.5)">
        <g style="visibility: visible;" transform="translate(0.5,0.5)">
       <g style="visibility: visible;" transform="translate(0.5,0.5)">
       <g style="visibility: visible;" transform="translate(0.5,0.5)">
    </g>
<g>
<g>
</g>
<linearGradient id="mx-gradient-white-1-white-1-e-0" x1="0%" y1="0%" x2="100%" y2="0%">
</svg>
</div>
```
Use the code above for reproduce the error.

**Comment by p0deje** [comment]
This is an issue with your code - you need to properly wait until removed element disappears from DOM and then proceed.
