### ISSUE TITLE
Context menu options disappeared and will not come back.

### ISSUE THREAD

**Issue by dailytabs** [SeleniumHQ/selenium#4326]
## Meta -
OS: Windows 10 Home 64-bit
Selenium Version: 2.9.1.1-signed
Browser: Firefox
Browser Version: 54.0.1 32-bit

## Expected Behavior
Context menus to appear.

## Actual Behavior
Separator shows, but no context menu options for selenium appear.

## Steps to reproduce
Pretty sure this started happening when Firefox was upgraded the week before last.

## Attempted Remedies
I have tried:
- installing flow-control plugin as mentioned in similar bug from earlier this year. It did not fix the issue and I uninstalled it.
- disabling & re-enabling both the Xebium formatters and Selenium IDE.
- uninstalling Xebium formatters.
- uninstalling & re-installing Selenium IDE.

Note: A new version of Selenium IDE appeared today, prior to me performing the attempted remedies above.

## Diagnostic Information
```
{
  "startTime": 1500323292907,
  "at": 1500323415101,
  "diags": {
    "PluginManager": {
      "pluginsData": [
        {
          "id": "xebiumformatter@xebia.com",
          "installed": true,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": [
              "xebiumformatter;Xebium Formatter;chrome://xebiumformatter/content/formats/xebiumformatter.js;undefined"
            ]
          },
          "options": {
            "disabled": false,
            "autoDisabled": false
          }
        },
        {
          "id": "flow-control@dave.hunt",
          "installed": false,
          "code": {
            "ideExtensions": [],
            "userExtensions": [],
            "formatters": []
          },
          "options": {
            "disabled": true,
            "autoDisabled": false
          }
        }
      ],
      "errors": []
    },
    "Browser": {
      "os": "WINNT",
      "name": "Firefox",
      "version": "54.0.1",
      "ID": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
      "vendor": "Mozilla",
      "platformBuildID": "20170628075643",
      "platformVersion": "54.0.1",
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
    },
    "SeleniumIDE": {
      "version": "2.9.1",
      "sidebar": false
    }
  },
  "events": [
    {
      "at": 1500323292907,
      "type": "Event",
      "component": "HealthService",
      "event": "attached: editor"
    },
    {
      "at": 1500323292907,
      "type": "Event",
      "component": "editor",
      "event": "initializing"
    },
    {
      "at": 1500323292911,
      "type": "Event",
      "component": "editor",
      "event": "optionsChanged"
    },
    {
      "at": 1500323293325,
      "type": "Event",
      "component": "editor",
      "event": "initialized"
    }
  ],
  "metrics": {},
  "stats": {}
}
```

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
