### ISSUE TITLE
Does not open new tab using SendKeys() method in C#  at Chromium Based Browsers

### ISSUE THREAD

**Issue by StonedAstronaut** [SeleniumHQ/selenium#4327]
## Meta -
1.

OS:  Windows 10
Selenium Version:  Latest Stable (NuGet) 3.4.0
Selenium.Chrome.WebDriver: Latest Stable (NuGet) 2.30.0
IDE: Visual Studio 2017 Community
.NET Framework: 4.6.2

Browser:  Google Chrome

Browser Version:  59.0.3071.115 (64-bit)

2. 

OS:  Windows 10
Selenium Version:  Latest Stable (NuGet) 3.4.0
operadriver_win64: 2.29 (https://github.com/operasoftware/operachromiumdriver/releases)
IDE: Visual Studio 2017 Community
.NET Framework: 4.6.2

Browser:  Opera

Browser Version: 46.0.2597.46 (PGO)

## Expected Behavior -
open new tab
## Actual Behavior -
no effect
but it work for firefox
## Steps to reproduce -

C#
```csharp
using System;
using OpenQA.Selenium;

namespace demo
{
    class Program
    {
        private static IWebDriver dr;

        static void Main(string[] args)
        {
            dr = new OpenQA.Selenium.Chrome.ChromeDriver();
            // or this
            // dr = new OpenQA.Selenium.Opera.OperaDriver();

            dr.Navigate().GoToUrl("https://google.com");

            dr.FindElement(By.TagName("body")).SendKeys(Keys.Control + "t" + Keys.Control);

            while (true)
            {
                Console.WriteLine("press \"x\" for browser exit");
                if (Console.ReadLine().Equals("x"))
                {
                    dr.Quit();
                    break;
                }
            }

            Console.WriteLine("Press any key for close...");
            Console.ReadKey();
        }
    }
}
```

**Comment by lmtierney** [comment]
This is a bug in chromedriver https://bugs.chromium.org/p/chromedriver/issues/detail?id=1554, and Opera is no longer supported
