### ISSUE TITLE
Resource Timing API not showing correct resources in Selenium

### ISSUE THREAD

**Issue by skjindal93** [SeleniumHQ/selenium#4328]
## Meta -
OS:  OSX
Selenium Version:  3.4.3
Browser:  Firefox
Browser Version:  54.0.1 

## Steps To Reproduce -
I have geckodriver latest version installed and I am running latest Firefox version. I wrote a selenium script to just open a URL in firefox and keep the browser open (I am not calling driver.close() or driver.quit())

Here is what the script looks like

```
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("https://www.nrk.no/")
```

<img width="1440" alt="screen shot 2017-07-18 at 9 52 46 am" src="https://user-images.githubusercontent.com/1905603/28302605-f5100d06-6bab-11e7-8473-bc4de7fb0843.png">

Now, the website is just reloaded again, so that the resources are fetched from cache. NOTE: I refreshed by just pressing enter in the address bar

The number of resources reported by Resource Timing API is < 40. Same is the discrepancy with the number of resources in Developer Tools in Networks tab. This is happening for every website.

<img width="1440" alt="screen shot 2017-07-18 at 9 54 03 am" src="https://user-images.githubusercontent.com/1905603/28302623-146f4db0-6bac-11e7-9f8e-2be8cdac7165.png">

This is not happening if I just run plain Firefox and refresh the page in the same way. The resources number match always, irrespective of the number of times I refresh the web page.

## Expected Behavior -
Number of resources for the refresh should almost be same as first reload

## Actual Behavior -
Number of resources for refresh is very less than the first reload

**Comment by lmtierney** [comment]
This is a geckodriver/Firefox issue, please log an issue with geckodriver: https://github.com/mozilla/geckodriver
