### ISSUE TITLE
how to make @FindAll annotation stop looking for object once the right one is found

### ISSUE THREAD

**Issue by samnit** [SeleniumHQ/selenium#4335]
## Meta -
OS:  Windows 10

Selenium Version:  3.4

 @FindAll annotation is supposed to match at least one of the given criteria.

I am trying to verify element on page with multiple locators.

When I give **2 correct values of xpath**, then the driver identifies it quickly on the webpage and returns normally. **But** when I give the **first one as Correct and second one as Incorrect** , then it still returns true that element is found but it **waits for the object timeout** that was provided while initialising the driver(implicit wait).

Isn't there a way where if it finds the first element then it just returns us as true, So that no more time is taken for the test execution to move forward.

**URL for WebPage** : http://store.demoqa.com/
**WebElement** : -
@FindAll ({
	                    @FindBy(xpath = "//input[@name='s']"),
	                    @FindBy(xpath = "//a[contains(.,'Magic Mouse')]")
		})
	public WebElement Header__txtSearch;

How can it be stopped after finding the correct locater info

**Comment by samnit** [comment]
@selenium-ci can u reply or give some suggestions ?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
