### ISSUE TITLE
IE webdriver issue with multiple C# test method runs

### ISSUE THREAD

**Issue by mksingh123** [SeleniumHQ/selenium#4336]
Hi,

I am facing an unique issue ONLY with IE webdriver, both locally as well as on Sauce Labs.
I run many test methods (C#) re using the same browser session. Till 22nd test method it works fine, but 23rd test onwards it throws an error like below:
Test method FredNxtOfficeWebAutomation.Tests.DraftsTest.DR003_VerifyCreateDraftExistingTemplate threw exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:60244/session/07a5d582-3a3c-4cf5-9659-7ac8d427bca0/elements timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out.

Any help would be much appreciated.
Thanks!

Regards
Manish

**Comment by mksingh123** [comment]
I have found a workaround for this today, however I think it's still an issue in IE webdriver and should be fixed. So please do not close this issue without assessing this in detail. Thanks a lot!

The workaround is as follows for anyone who faces this in future:

[TestInitialize()]
        public void MyTestInitialize()
        {
            int count = 0;
            label1:
            try
            {
                // set the browser from a build settings
                string browser = TestContext.Properties["browser"]?.ToString();// ?? "gcl";
                switch (browser.ToLower(CultureInfo.InvariantCulture))
                {
                    // <your test initialize code>
                }

                driver.Manage().Window.Maximize();

                // set URL from a build
                BaseUrl = new Uri(TestContext.Properties["url"].ToString());
            }

            catch (Exception ex)
            {
                if(ex is System.Net.WebException || ex is WebDriverException || ex is WebDriverTimeoutException)
                {
                    count++;
                    if (count < 3)
                    {
                        MyTestCleanup(); //Calls test cleanup
                        MyAssemblyCleanup(); //Calls Assembly cleanup
                        goto label1;
                    }
                }                                   
            }                       
        }
       
        [TestCleanup()]
        public void MyTestCleanup()
        {        
                 // <your test cleanup code if any>
        }

        [AssemblyCleanup()]
        public static void MyAssemblyCleanup()
        {
             // <your assembly cleanup code>
        }

**Comment by diemol** [comment]
Is this still a valid issue? If so, could you please provide a way to reproduce it?

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information. If this issue still exists with the latest versions, please feel free to open a new issue with all the required information on the template.
