### ISSUE TITLE
Element is not found when CSS selector contains quote

### ISSUE THREAD

**Issue by DavidGangel** [SeleniumHQ/selenium#4337]
## Meta -
OS:  Mac OSX 10.12.5
Selenium Version:  3.4.0
Browser:  
Chrome, Firefox

Browser Version:  
Doesn't seems to be related to specific browser.

## Expected Behavior -
The following locator should work:
```
label:contains('Garantie jusqu'à la 5e année du véhicule'):visible
```

## Actual Behavior -
Selenium times out by waiting for the element.

## Steps to reproduce -
1. Open the site:
http://pre.audi-disponible.fr/voiture-doccasion/url-1_1-search.htm#/i/s/l|12,1,DATE_OFFER,U/f|filter/models
2. Just try to find the element with Selenium:
```
label:contains('Garantie jusqu'à la 5e année du véhicule'):visible
```

Notes:
I think the issue is caused by the quote at the middle of the String.
However if I try to escape it by:
```
label:contains('Garantie jusqu\'à la 5e année du véhicule'):visible
```
it's still going to fail.

**Comment by luke-hill** [comment]
Could you try using double quotes to surround the contains tag. This way selenium won't be thinking the string has ended.

So in your example it would be: `label:contains("Garantie jusqu'à la 5e année du véhicule"):visible` - Because otherwise you have 3 single quote marks which might think that it starts and ends elsewhere

**Comment by DavidGangel** [comment]
@luke-hill if I use this:
```
syncHelper.waitForElementToAppear("label:contains(\"Garantie jusqu'à la 5e année du véhicule\"):visible");
```
I get this error:
```
Failed tests: 
  SearchByWarrantyTest.testNumberOfHitsUpdatesWhen5yearsWarrantyIsSelected:21->test:40 Cause: null --- Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'Davids-Mac-mini', ip: 'fe80:0:0:0:4a7:cf5f:9817:7fc8%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262), userDataDir=/var/folders/4r/cwq8hnb104x_wx7t6yl90qz00000gn/T/.org.chromium.Chromium.J708sm}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c4eba0039ac4ed207b99dad2ef177c93
```

**Comment by lmtierney** [comment]
`contains` is not valid in the CSS selector, it was removed from current CSS specs. It is still supported by jQuery I believe, but Selenium does not use jQuery

**Comment by DavidGangel** [comment]
@lmtierney Khm.
If I use the string before or after the quote char then Selenium finds the expected element.
How is it removed then?
We also have many places this kind of element locator "strategy" and not experiencing other issues.
Can you please reopen?

**Comment by lmtierney** [comment]
I will reopen if you provide a [concise reproducible test case](http://sscce.org/) so that we can act on this issue.

You can try your selectors in the console using `document.querySelector` or `document.querySelectorAll`. See the image below, I can find the element using your selector and jQuery but not with any variation of your selector using `document.querySelector`

![image](https://user-images.githubusercontent.com/4405962/28367079-079a65e4-6c55-11e7-825e-ff557a4f00e9.png)

**Comment by lmtierney** [comment]
See also [the deprecated section here](https://css-tricks.com/pseudo-class-selectors/#article-header-id-9)

**Comment by DavidGangel** [comment]
@lmtierney I know that the locator should work, by using the SelectorGadget chrome extension:
https://chrome.google.com/webstore/detail/selectorgadget/mhjhnkcfbdhnjickkkdbjoemdmbfginb

The linked deprecated page applies for Pseudo elements AFAIK. In my case the element is not a pseudo element.
In the JQuery API documentation it's also mentioned:
https://api.jquery.com/contains-selector/

**Comment by lmtierney** [comment]
Like I said, jQuery selectors are not supported in vanilla javascript. Selenium does not import jQuery. [SelectorGadget uses jQuery](https://github.com/cantino/selectorgadget#technologies)

**Comment by lmtierney** [comment]
> The linked deprecated page applies for Pseudo elements AFAIK. In my case the element is not a pseudo element.

No, it is not pseudo elements. `:contains` is a pseudo _selector_ that is no longer supported by CSS3
