### ISSUE TITLE
Chrome screenshots taken with selenium are black with IIS. However, it is properly taken when using Visual Studio

### ISSUE THREAD

**Issue by rravichandar** [SeleniumHQ/selenium#4338]
Versions IIS: 10.0.15063.0 chrome driver: 2.30 chrome : 59.0.3071.115
Screen shot taken with selenium chrome driver are black in IIS after the newest IIS update. However this problem does not occur when using Visual Studio. 

Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot();

It returns only a black screen. Thanks!

Regards,
Rina

**Comment by cgoldberg** [comment]
@rravichandar Can you explain what you mean when you say screenshots "are black in IIS".   How is IIS related to this issue?  

Perhaps you are testing a web application that is deployed on IIS, and when you take screenshots of this application via Webdriver, the images produced appear black?  However, that is a total guess at an interpretation of what you mean by "are black in IIS".  Please clarify what you *actually* mean.

**Comment by rravichandar** [comment]
Hi @cgoldberg ,

Ya. I deployed the appilcation in IIS and using the selenium chrome driver I take the screen shot of the page using 

driver = new ChromeDriver(@BinDir);
driver.Navigate().GoToUrl("somewebpage");
Screenshot ss = ((ITakesScreenshot)driver).GetScreenshot(); 

The screenshot is saved locally.When I look at the screenshot there is only a black screen and not the webpage it is supossed to open. 

However, when I use Visual Studio for debugging, I get the image of the Webpage.  
Thanks!

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
