### ISSUE TITLE
.click() scrolls the element to the _top_ of the viewport instead of to the _bottom_

### ISSUE THREAD

**Issue by raffam** [SeleniumHQ/selenium#4342]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.3

Browser:  Chrome 

Browser Version:  59.0.3071.115 (Official Build) (64-bit)

## Expected Behavior -
What is written in #4280 "When you call .click, [...] WebDriver spec tells to scroll to to the **very bottom of viewport**, so the button is not overlapped by other elements and click successfully happens."

## Actual Behavior -
The element is scrolled to the **top** of the viewport instead of to the bottom of it. Since in the top there is a navbar, the element becomes hidden under the navbar, and an exception is throw saying that another element would receive the click
If the element would be scrolled to the **bottom** of the viewport, as WebDriver specs say, it would be clicked correctly

## Steps to reproduce -

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

username = "YOUR_USERNAME"
password = "YOUR_PASSWORD"

css_selector = ".pv-profile-section__see-more-inline.link"
url = "https://www.linkedin.com/in/sachindsharma/"
section_name = "experience-section"

def login(browser):
    print("Login check 2")
    try:
        login_email_element = browser.find_element_by_id("login-email")
    except NoSuchElementException:
        print("NoSuchElementException caught")
        return False
    else:
        # Execute if no exception occurred
        print("LOGIN CHECK 2 TRIGGERED")
        login_password_element = browser.find_element_by_id("login-password")
        login_email_element.clear()
        login_password_element.click()  # focus on the field
        login_password_element.clear()
        time.sleep(2)
        login_email_element.send_keys(username)
        login_password_element.send_keys(password)
        login_password_element.submit()
        time.sleep(2)
        return True
            
def scroll(driver):
    old_source  = driver.page_source
    while True:
        print("Scrolling")
        driver.execute_script("window.scrollBy(0,500)")
        time.sleep(2)
        new_source = driver.page_source
        if new_source == old_source:
            break
        else:
            old_source = new_source
    
#MAIN
#driver = webdriver.Firefox()
driver = webdriver.Chrome()
driver.get("https://linkedin.com")
time.sleep(5)

#Log in
login(driver)
time.sleep(2)
driver.get(url)
time.sleep(2)

#Without scrolling, the experience-section is not in the DOM and thus it is not found
scroll(driver)

#Click on links
exp_section = driver.find_element_by_class_name(section_name)

while True:
    link_list = exp_section.find_elements_by_css_selector(css_selector)
    count = len(link_list)
    print("Found "+str(count)+" links")
    if count==0:
        break
    for link in link_list:
        print("Clicking on the link tag='"+link.tag_name+"' text='"+link.text+"'")
        link.click()
        time.sleep(5)

#driver.quit()
print("Ended!!!")
```

**Comment by lmtierney** [comment]
The comment in #4280 was in reference to that situation specifically. When you perform `.click()` it scrolls the element into the viewport. If the element was previously below the viewport, the element will be scrolled enough to where the element is now in the bottom of the viewport. If the element was previously above the viewport, the element will be scrolled enough to where the element is now in the top of the viewport.

**Comment by lmtierney** [comment]
See:

https://w3c.github.io/webdriver/webdriver-spec.html#element-click

and 

https://w3c.github.io/webdriver/webdriver-spec.html#dfn-scrolled-into-view

**Comment by raffam** [comment]
I see. Sorry for the misunderstanding
