### ISSUE TITLE
Firefox click on the wrong link even if the correct one is clickable

### ISSUE THREAD

**Issue by raffam** [SeleniumHQ/selenium#4343]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.3

Browser:  Firefox

Browser Version:  54.0.2

## Actual Behavior -
You call `.click()` on a link. Firefox scrolls the correct link into view. The link is now at the bottom of the viewport, and it is "clickable", that is, nothing hides it and it can be identified by its screen coordinates, as the following image shows

![image](https://image.ibb.co/eEBZ4k/selenium_ff_link.png "Firefox link into view at the bottom of the viewport")

Since the link is clickable, this bug is not related to #4280

But then, the link below the correct one is clicked (this is the wrong link to click). In the following screenshot, taken in a new window (since in the Selenium window the correct link is at the bottom of the viewport), the correct link is in red, while the incorrect one that is clicked is in blue.
![image](https://preview.ibb.co/eC72qQ/selenium_ff_not_correct_link.png "")

Chrome works correctly

## Steps to reproduce -

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

username = "YOUR_USERNAME"
password = "YOUR_PASSWORD"

css_selector = ".pv-profile-section__see-more-inline.link"
url = "https://www.linkedin.com/in/sachindsharma/"
section_name = "experience-section"

# Set this to False and it will work
ff = True

def login(browser):
    login_email_element = browser.find_element_by_id("login-email")
    login_password_element = browser.find_element_by_id("login-password")
    login_email_element.clear()
    login_password_element.click()  # focus on the field
    login_password_element.clear()
    time.sleep(2)
    login_email_element.send_keys(username)
    login_password_element.send_keys(password)
    login_password_element.submit()
    time.sleep(2)
            
#MAIN
if ff:
    driver = webdriver.Firefox()
else:
    driver = webdriver.Chrome()
driver.get("https://linkedin.com")
time.sleep(5)

#Log in
login(driver)
time.sleep(2)
driver.get(url)
time.sleep(2)

#Click on links
while True:
    link_list = driver.find_element_by_class_name(section_name).find_elements_by_css_selector(css_selector)
    count = len(link_list)
    print("Found "+str(count)+" links")
    if count==0:
        break
    for link in link_list:
        print("Clicking on the link tag='"+link.tag_name+"' text='"+link.text+"'")
        link.click()
        time.sleep(5)

#driver.quit()
print("Ended!!!")
```

**Comment by lmtierney** [comment]
Your issue is reproducible, but there's nothing Selenium can do about it. This has to do with geckodriver/Firefox. Please log an issue with geckodriver: https://github.com/mozilla/geckodriver/issues
