### ISSUE TITLE
 Selenium Chrome remote webdriver not  support mobile emulation with touch actions 

### ISSUE THREAD

**Issue by zenghuaguang** [SeleniumHQ/selenium#4348]
Does the Selenium Chrome remote webdriver support mobile emulation with touch actions or gestures? I got the following exception when running touch actions on a Selenium grid.

System.InvalidOperationException:
 Underlying driver does not implement advanced user interactions yet.
Obviously the exception says no, but I want to know if this is not because of a implementation mistake I made.

I basically have the following code:

RemoteTouchScreen touch = new RemoteTouchScreen(WebDriver as RemoteWebDriver);

touch.Down(startX, startY); //exception thrown
touch.Up(endX, startY);
if the WebDriver is of type ChromeDriver, which runs locally it works perfectly. If I use the RemoteWebDriver class it fails with the mentioned exception.

Both the drivers have mobile emulation enabled which I can see working in both situations.

Used .Net Selenium Client & WebDriver Language Bindings
Used Selenium server: selenium-server-standalone-2.53.1.jar

**Comment by krmahadevan** [comment]
@zenghuaguang - I tried using Selenium 3.4.0 with Java and the following code works fine.

```java
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.ExecuteMethod;
import org.openqa.selenium.remote.RemoteExecuteMethod;
import org.openqa.selenium.remote.RemoteTouchScreen;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;

public class SampleTestClass {
    private RemoteWebDriver driver;

    @BeforeClass
    public void beforeClass() throws MalformedURLException {
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    }

    @Test
    public void testMethod() {
        driver.get("about:blank");
        ExecuteMethod method = new RemoteExecuteMethod(driver);
        RemoteTouchScreen screen = new RemoteTouchScreen(method);
        screen.up(10, 20);
    }

    @AfterClass
    public void afterClass() {
        driver.quit();
    }
}
```

And I see the following in the node logs (Running selenium 3.4.0)
```
09:46:06.532 INFO - Done: [delete session: f8088e93-7940-49fa-aaa9-e42002ec4a2f]
09:47:12.826 INFO - Executing: [new session: Capabilities [{browserName=chrome, version=, platform=ANY}]])
09:47:12.827 INFO - Creating a new session for Capabilities [{browserName=chrome, version=, platform=ANY}]
Starting ChromeDriver 2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262) on port 13855
Only local connections are allowed.
09:47:13.580 INFO - Detected dialect: OSS
09:47:13.583 INFO - Done: [new session: Capabilities [{browserName=chrome, version=, platform=ANY}]]
09:47:13.678 INFO - Executing: [get: about:blank])
09:47:13.720 INFO - Done: [get: about:blank]
09:47:13.735 INFO - Executing: [Up])
09:47:13.759 INFO - Done: [Up]
09:47:13.771 INFO - Executing: [delete session: 61b60a9b-4f62-4d4f-8265-98562071419b])
09:47:13.843 INFO - Done: [delete session: 61b60a9b-4f62-4d4f-8265-98562071419b]
```

**Comment by zenghuaguang** [comment]
@krmahadevan 
Thanks for your answer ,I verified that's work fine with selenium-server-standalone-3.4.0.jar
