### ISSUE TITLE
W3C: Undefined behavior of WebElement.sendKeys() for checkbox

### ISSUE THREAD

**Issue by codingphil** [SeleniumHQ/selenium#4349]
Selenium Version:  
3.4.0
Browser:  
Firefox 54.0.1
geckodriver 0.18

I entered a bug for the geckodriver project because sendKeys(" ") of a space character for a checkbox element does nothing (silently fails).
[https://github.com/mozilla/geckodriver/issues/777](https://github.com/mozilla/geckodriver/issues/777)

The bug was closed with a reference to the webdriver spec.
https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys
The solution would be to use the Actions API for this use case.

I have 2 questions:
1.)
Isn't the behavior WebElement.sendKeys undefined for the checkbox (see referenced spec above)?
Setting the value of the checkbox element makes no sense.
If sendKeys() is not supported for a checkbox it should at least returning an error (in my opinion).

2.)
This question here is kind of a meta question:
How does Selenium avoid major incompatibilities like that in the time frame in which there still exist OSS webdrivers (like chromedriver). It seems that at least for this sendKeys() example and also the Actions API the semantics changed quite a bit.

Regards,
Philip

**Comment by barancev** [comment]
Please report this issue to W3C WebDriver tracker
https://github.com/w3c/webdriver/issues
