### ISSUE TITLE
Chrome driver current window handle does not get updated

### ISSUE THREAD

**Issue by ananthoju** [SeleniumHQ/selenium#435]
Using C# Chrome driver, when I open a new tab from another tab (via link), current window handle doesn't get updated.
Ex: I have an application that launched in Tab1 with window handle H1. Using a link in Tab1, i am launching Tab2 and it has window handle H2. When I come back to Tab1 and click on a link to switch to Tab2, I could able to switch to Tab2 but driver.CurrentWindowHandle value still has H1.

Can you clarify how can I get the updated Current Window Handle?

Thanks,
Jay

**Comment by andreastt** [comment]
You have to switch to the window first.

**Comment by ananthoju** [comment]
May be you misunderstood my earlier question. 
On click of a link in page of Tab1 already switching to Tab2, but Current window handle value is still H1.

**Comment by andreastt** [comment]
WebDriver doesn't track the active/currently focussed window.  “Switching to a window” in WebDriver context isn't the same as selecting the window with your mouse, as there's no relationship between the “window” concept on Windows and WebDriver.

When WebDriver talks of a “window” is actually refers to the top-level browsing context, which is what you see inside the viewport in your Chrome window.

When do an action in the browser than opens another browser (which may or may not be in a new window), you need to tell WebDriver to switch the active browser context to this new browser.  You do this through `switchToWindow`.
