### ISSUE TITLE
Unable to build Selenium stand alone file from code.

### ISSUE THREAD

**Issue by c0gupr2** [SeleniumHQ/selenium#4350]
## Meta -
OS:  Windows 10

Selenium Version:  3.4.0

Browser:  NA

Browser Version:  

## Steps to reproduce - 
As per the readme document, I executed a command to build selenium stand alone file. I see error. Please help me with the required certificate details to resolve this issue.

##Command
go //java/server/src/org/openqa/selenium/remote/server:server:uber //java/client/src/org/openqa/selenium:client-combined:project

##Error:
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by c0gupr2** [comment]
Please find below the logs attached

Parsing cpp/build.desc
Parsing cpp/iedriverserver/build.desc
Parsing dotnet/build.desc
Parsing dotnet/docs/build.desc
Parsing dotnet/src/support/build.desc
Parsing dotnet/src/webdriver/build.desc
Parsing dotnet/src/webdriverbackedselenium/build.desc
Parsing dotnet/test/chrome/build.desc
Parsing dotnet/test/common/build.desc
Parsing dotnet/test/edge/build.desc
Parsing dotnet/test/firefox/build.desc
Parsing dotnet/test/ie/build.desc
Parsing dotnet/test/phantomjs/build.desc
Parsing dotnet/test/remote/build.desc
Parsing dotnet/test/safari/build.desc
Parsing dotnet/test/support/build.desc
Parsing dotnet/test/webdriverbackedselenium/build.desc
Parsing ide/build.desc
Parsing ide/main/build.desc
Parsing ide/plugins/csharp-format/build.desc
Parsing ide/plugins/groovy-format/build.desc
Parsing ide/plugins/java-format/build.desc
Parsing ide/plugins/perl-format/build.desc
Parsing ide/plugins/php-format/build.desc
Parsing ide/plugins/python-format/build.desc
Parsing ide/plugins/ruby-format/build.desc
Parsing javascript/build.desc
Parsing javascript/android-atoms/build.desc
Parsing javascript/atoms/build.desc
Parsing javascript/atoms/fragments/build.desc
Parsing javascript/chrome-driver/build.desc
Parsing javascript/firefox-driver/build.desc
Parsing javascript/ie-driver/build.desc
Parsing javascript/jsunit/build.desc
Parsing javascript/node/build.desc
Parsing javascript/remote/build.desc
Parsing javascript/safari-driver/build.desc
Parsing javascript/selenium-atoms/build.desc
Parsing javascript/selenium-core/build.desc
Parsing javascript/watir-atoms/build.desc
Parsing javascript/webdriver/build.desc
Parsing javascript/webdriver/atoms/build.desc
Parsing javascript/webdriver/atoms/fragments/build.desc
Parsing javascript/webdriver/atoms/fragments/inject/build.desc
Parsing javascript/webdriver/atoms/inject/build.desc
Parsing py/build.desc
Parsing rb/build.desc
Parsing third_party/closure/build.desc
Parsing third_party/firebug/build.desc
Parsing third_party/js/sizzle/build.desc
Parsing third_party/js/wgxpath/build.desc
** Invoke //java/server/src/org/openqa/selenium/remote/server:server:uber (first_time)
** Execute //java/server/src/org/openqa/selenium/remote/server:server:uber
C:/Users/c0gupr2/Downloads/selenium-master/rake-tasks/buck.rb:37 warning: multiple Java methods for arguments (Java::OrgApacheHttpClientMethods::HttpGet), using first:
  public org.apache.http.client.methods.CloseableHttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientProtocolException
  public org.apache.http.HttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientProtocolException
go aborted!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.ssl.Alerts:-1:in `getSSLException'
sun.security.ssl.SSLSocketImpl:-1:in `fatal'
sun.security.ssl.Handshaker:-1:in `fatalSE'
sun.security.ssl.Handshaker:-1:in `fatalSE'
sun.security.ssl.ClientHandshaker:-1:in `serverCertificate'
sun.security.ssl.ClientHandshaker:-1:in `processMessage'
sun.security.ssl.Handshaker:-1:in `processLoop'
sun.security.ssl.Handshaker:-1:in `process_record'
sun.security.ssl.SSLSocketImpl:-1:in `readRecord'
sun.security.ssl.SSLSocketImpl:-1:in `performInitialHandshake'
sun.security.ssl.SSLSocketImpl:-1:in `startHandshake'
sun.security.ssl.SSLSocketImpl:-1:in `startHandshake'
org/apache/http/conn/ssl/SSLConnectionSocketFactory.java:396:in `createLayeredSocket'
org/apache/http/conn/ssl/SSLConnectionSocketFactory.java:355:in `connectSocket'
org/apache/http/impl/conn/DefaultHttpClientConnectionOperator.java:142:in `connect'
org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java:359:in `connect'
org/apache/http/impl/execchain/MainClientExec.java:381:in `establishRoute'
org/apache/http/impl/execchain/MainClientExec.java:237:in `execute'
org/apache/http/impl/execchain/ProtocolExec.java:185:in `execute'
org/apache/http/impl/execchain/RetryExec.java:89:in `execute'
org/apache/http/impl/execchain/RedirectExec.java:111:in `execute'
org/apache/http/impl/client/InternalHttpClient.java:185:in `doExecute'
org/apache/http/impl/client/CloseableHttpClient.java:83:in `execute'
org/apache/http/impl/client/CloseableHttpClient.java:108:in `execute'
sun.reflect.NativeMethodAccessorImpl:-2:in `invoke0'
sun.reflect.NativeMethodAccessorImpl:-1:in `invoke'
sun.reflect.DelegatingMethodAccessorImpl:-1:in `invoke'
java.lang.reflect.Method:-1:in `invoke'
org/jruby/javasupport/JavaMethod.java:525:in `invokeDirectWithExceptionHandling'
org/jruby/javasupport/JavaMethod.java:380:in `invokeDirect'
org/jruby/java/invokers/InstanceMethodInvoker.java:58:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/CallOneArgNode.java:57:in `interpret'
org/jruby/ast/LocalAsgnNode.java:123:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/ClassVarAsgnNode.java:92:in `interpret'
org/jruby/ast/OpAsgnOrNode.java:99:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/DAsgnNode.java:110:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
org/jruby/org/jruby/RubyProc$i_method_0_0$RUBYINVOKER$call.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:216:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:212:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/CallTwoArgNode.java:59:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
org/jruby/org/jruby/RubyProc$i_method_0_0$RUBYINVOKER$call.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:216:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:212:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/CallTwoArgNode.java:59:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/CaseNode.java:138:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:336:in `yield'
org/jruby/runtime/InterpretedBlock.java:293:in `yield'
org/jruby/runtime/Block.java:130:in `yield'
org/jruby/RubyArray.java:1661:in `eachCommon'
org/jruby/RubyArray.java:1671:in `each'
org/jruby/org/jruby/RubyArray$i_method_0_0$RUBYINVOKER$each.gen:65535:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:184:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/IfNode.java:117:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/EnsureNode.java:96:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/internal/runtime/methods/AliasMethod.java:81:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:227:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/FCallTwoArgNode.java:38:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallSpecialArgNode.java:65:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:184:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:336:in `yield'
org/jruby/runtime/InterpretedBlock.java:293:in `yield'
org/jruby/runtime/Block.java:130:in `yield'
org/jruby/RubyArray.java:1661:in `eachCommon'
org/jruby/RubyArray.java:1671:in `each'
org/jruby/org/jruby/RubyArray$i_method_0_0$RUBYINVOKER$each.gen:65535:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/IfNode.java:119:in `interpret'
org/jruby/ast/IfNode.java:119:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RescueNode.java:216:in `executeBody'
org/jruby/ast/RescueNode.java:120:in `interpretWithJavaExceptions'
org/jruby/ast/RescueNode.java:110:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/FCallNoArgBlockNode.java:32:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/VCallNode.java:85:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RescueNode.java:216:in `executeBody'
org/jruby/ast/RescueNode.java:120:in `interpretWithJavaExceptions'
org/jruby/ast/RescueNode.java:110:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/FCallNoArgBlockNode.java:32:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:2582:in `loadFile'
org/jruby/runtime/load/ExternalScript.java:66:in `load'
org/jruby/runtime/load/LoadService.java:255:in `load'
org/jruby/RubyKernel.java:1084:in `loadCommon'
org/jruby/RubyKernel.java:1066:in `load'
org/jruby/org/jruby/RubyKernel$s_method_0_1$RUBYINVOKER$load.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:208:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:204:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:2582:in `loadFile'
org/jruby/runtime/load/ExternalScript.java:66:in `load'
org/jruby/runtime/load/LoadService.java:255:in `load'
org/jruby/RubyKernel.java:1084:in `loadCommon'
org/jruby/RubyKernel.java:1066:in `load'
org/jruby/org/jruby/RubyKernel$s_method_0_1$RUBYINVOKER$load.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:208:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:204:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/internal/runtime/methods/ProcMethod.java:62:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:200:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:196:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:734:in `runInterpreter'
org/jruby/Ruby.java:586:in `runNormally'
org/jruby/Ruby.java:419:in `runFromMain'
org/jruby/Main.java:304:in `run'
org/jruby/Main.java:144:in `run'
org/jruby/Main.java:113:in `main'
C:/Users/c0gupr2/Downloads/selenium-master/rake-tasks/buck.rb:37:in `download'
C:/Users/c0gupr2/Downloads/selenium-master/rake-tasks/buck.rb:53:in `buck_cmd'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
C:/Users/c0gupr2/Downloads/selenium-master/rake-tasks/buck.rb:241:in `(root)'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
org/jruby/RubyArray.java:1671:in `each'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
org/jruby/RubyArray.java:1671:in `each'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31:in `(root)'
org/jruby/RubyKernel.java:1066:in `load'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:19:in `(root)'
org/jruby/RubyKernel.java:1066:in `load'
file:/C:/Users/c0gupr2/Downloads/selenium-master/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/bin/rake:12:in `rake'
org/jruby/RubyProc.java:275:in `call'
rake:1:in `(root)'
Exception `SystemExit' at org/jruby/RubyKernel.java:869 - exit

**Comment by p0deje** [comment]
It looks like something is wrong with your JDK SSL.

I'm adding labels for Java maintainers to have a look, but it's more likely to be your environment issue and I'd recommend first to Google for this error and, if it doesn't help, connecting to #selenium IRC channel and ask around.

**Comment by RajAsapu** [comment]
@c0gupr2 Do you have your certificates in the keystore , if not give it a try. It is the java SSL error which comes with certificate issues . Try below link
[](https://support.globalsign.com/customer/en/portal/articles/2121490-java-keytool---create-keystore)

**Comment by c0gupr2** [comment]
Hello Raj & Alex, thanks for your inputs on above issue. I am able to resolve ceritificate issue and I am stuck with new socketTimeoutException. Could you please share any lead to resolve this issue, if possible?

Parsing third_party/closure/build.desc
Parsing third_party/firebug/build.desc
Parsing third_party/js/sizzle/build.desc
Parsing third_party/js/wgxpath/build.desc
** Invoke //java/server/src/org/openqa/selenium/remote/server:server:uber (first_time)
** Execute //java/server/src/org/openqa/selenium/remote/server:server:uber
C:/Users/rohit/Downloads/selenium-master/rake-tasks/buck.rb:38 warning: multiple Java methods for arguments (Java::OrgApacheHttpClientMethods::HttpGet), using first:
  public org.apache.http.client.methods.CloseableHttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientProtocolException
  public org.apache.http.HttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientProtocolException
Jul 27, 2017 4:58:15 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Mon, 27 Jul 2037 20:58:15 -0000; secure; HttpOnly". Invalid 'expires' attribute: Mon, 27 Jul 2037 20:58:15 -0000
go aborted!
java.net.SocketException: Connection reset
java.net.SocketInputStream:-1:in `read'
java.net.SocketInputStream:-1:in `read'
sun.security.ssl.InputRecord:-1:in `readFully'
sun.security.ssl.InputRecord:-1:in `readV3Record'
sun.security.ssl.InputRecord:-1:in `read'
sun.security.ssl.SSLSocketImpl:-1:in `readRecord'
sun.security.ssl.SSLSocketImpl:-1:in `readDataRecord'
sun.security.ssl.AppInputStream:-1:in `read'
org/apache/http/impl/io/SessionInputBufferImpl.java:137:in `streamRead'
org/apache/http/impl/io/SessionInputBufferImpl.java:198:in `read'
org/apache/http/impl/io/ContentLengthInputStream.java:176:in `read'

**Comment by RajAsapu** [comment]
@c0gupr2 : I could see that it's failing due to invalid cookie header . Can you add cookie value as well and give it a try .. I could see that it's not displayed , Or read the cookie from GitHub using getCookie() and add it after modifications. You could also check the headers using post man interceptors , chrome network or fiddler.

**Comment by barancev** [comment]
System misconfiguration, not a Selenium issue.
