### ISSUE TITLE
Suggestion: Support for DriverService "run as" username/password

### ISSUE THREAD

**Issue by nbelyh** [SeleniumHQ/selenium#4355]
When creating tests for Windows, there is occasionally a need to run the same test, while switching between different users (like, rung line 1-10 using windows user A, then run line 11-20 using user B, etc).
This is useful for testing workflow applications for example, with **integrated windows security**

To be able to properly test this, one needs to logon different users and re-launch the driver using those. This pull request adds support for launching driver under a specific user (the underlying OS support is already there, it just exposes those fields as optional properties). Means, there is a "StartupInfo", but not all properties of it can now be set by user; this suggestion adds username/password to the list of available properties.

We needed this functionality in our project, that is basically a long workflow.
Other examples where it may be needed (from stackoverflow):

https://stackoverflow.com/questions/16590207/how-to-impersonate-a-specific-user-with-selenium-webdriver
https://stackoverflow.com/questions/28045870/how-can-i-run-internet-explorer-selenium-tests-as-a-specific-domain-user
https://stackoverflow.com/questions/9951377/using-impersonation-to-launch-processes-indirectly-in-c-sharp
https://sqa.stackexchange.com/questions/2277/using-selenium-webdriver-with-windows-authentication

Pull request:
#4354 

Usage example:

            var service = ChromeDriverService.CreateDefaultService();

            service.StartupDomain = "contoso";

            service.StartupUserName = "john.doe";

            var pwd = new SecureString();
            foreach (var c in "P@ssword")
                pwd.AppendChar(c);

            service.StartupPassword = pwd;

            service.Start();

            var options = new ChromeOptions();
            options.AddArgument("--no-sandbox");

            var driver = new RemoteWebDriver(service.ServiceUrl, options);

**Comment by p0deje** [comment]
Closing this in favor of #4354. There is no point of having both issue and PR opened.
