### ISSUE TITLE
SendKeys throws error "Cannot set the selection end" on Input Fields of type Email / Number

### ISSUE THREAD

**Issue by djgerhab** [SeleniumHQ/selenium#4361]
## Meta
OS: any
Browser:  any
Selenium Version:  
current (3.5 master)
usecase problem on 2.9.1 IDE

## Steps to reproduce / Actual Behavior
When attempting to sendKeys (Selenium IDE) on an input field of type email or number, the error of "Cannot set the selection end" is thrown.

## Expected Behavior 
The input field value should change to the appropriate text value entered like it does with other types or nontype input fields.

## Why this is happening
The sendKeys command calls the selection.js goog.dom.selection.setText function which checks for the ability to use selectionStart (via goog.dom.selection.useSelectionProperties_ function), which returns false, and thus throwing the error. 

Per the W3 standards (https://www.w3.org/TR/html5/forms.html#the-input-element) the number/email input field types do not need to apply to selectionStart. I really want to know why not... but assuming that the browsers all follow this, thus is the reason why I am receiving null when checking the selectionStart on these type of input fields.

## Suggestions
I consider this an issue because I feel as though this is a very common usecase to have, especially when validating login forms and currently I don't know of a workaround for sendKeys on these fields. Either a new method of sending text needs to be changed (or added for theses cases) or at the very least it should be documented that it doesn't work.

Thanks in advance for the support!

**Comment by siggerzz** [comment]
I'm also seeing this problem on input fields with the **contenteditable=true** attribute, when using SendKeys on Safari on input fields with the **contenteditable=true** attribute, when using SendKeys on Safari (iOS using Appium). I raised an issue on Appium, however the devs there said it's likely an issue with Selenium itself.

https://github.com/appium/appium/issues/8927

**Comment by siggerzz** [comment]
Any update on this? A number of my tests have been failing for months due to this issue and I'm not sure how to proceed 👎

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/

**Comment by siggerzz** [comment]
@barancev  I'm experiencing this issue with Selenium 3, not Selenium IDE, shall I get a new issue created?

**Comment by barancev** [comment]
@siggerzz Sure, for WebDriver raise a new issue.

**Comment by MintLucky** [comment]
Ran into this problem in project. Is there any progress in solving this issue ?
