### ISSUE TITLE
java.lang.AssertionError: unknown error: unhandled inspector error	

### ISSUE THREAD

**Issue by pshorally** [SeleniumHQ/selenium#4365]
## OS:  
Windows 10
##Selenium Version:  
Selenium webdriver 3.4.0

##Browser:  
Chrome 
##Browser Version:  
59

## Expected Behavior -
Chrome browser should not throw error

## Steps to reproduce -
random

##Issue Description:
After upgrading Selenium webdriver 3.4.0 version and chrome browser 59

## Following issue noticed :
java.lang.AssertionError: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}

Steps to reproduce:
randomly occuring below issue

java.lang.AssertionError: unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 495 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'QA553', ip: '10.59.51.31', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41), userDataDir=C:\Users\PARAME~1\AppData\Local\Temp\scoped_dir2332_13297}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: c33556aacbb08a995906407cba54f2a1
	at com.lucernex.qa.utils.Assert.fail(Assert.java:96)
	at com.lucernex.qa.views.BaseView.takeScreenshot(BaseView.java:188)
	at com.lucernex.qa.views.admin.lxadmin.SetupFirmWizardView.clickButton(SetupFirmWizardView.java:82)
	at com.lucernex.qa.SetupFirmWizardSteps.I_click_the_button_in_the_setup_firm_wizard(SetupFirmWizardSteps.java:144)
	at ?.And I click the "Reset" button in the setup firm wizard(target/test-classes/CreateEnterpriseCompany.feature:119)

Could you please suggest

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
