### ISSUE TITLE
Driver hangs after switching to window that is opened in app by java spcript

### ISSUE THREAD

**Issue by Tadel** [SeleniumHQ/selenium#4368]
## Meta -
OS: Windows 10
Selenium Version: 3.4.0
Browser: Chromer (version 59.0.3071.115 - 64bit)

## Expected Behavior -
Driver switch to window and works normally after switching

## Actual Behavior -
After switching to window with URL 'about:blank', driver hangs. It will hang forever untill you will kill it, and will not throw any exception

## Steps to reproduce -
1. Open browser on any website
2. Open new tab with URL 'about:blank'
3. Switch to that tab
4. Driver will hang.

**Comment by lmtierney** [comment]
How are you opening said tab?

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by Tadel** [comment]
Hi, I made made some updates for the issue, becouse it turned out it have another source

**Comment by p0deje** [comment]
If you can reproduce this issue using Firefox + GeckoDriver, then I'll reopen it. But for now it looks like something specific to ChromeDriver which Selenium team doesn't maintain. This is why I've asked to post this issue to ChromeDriver bug tracker.

**Comment by Tadel** [comment]
Turned out it is connected to chromedriver, as it worked fine with gecko
