### ISSUE TITLE
Selenium::WebDriver::Error::ServerError Error 500

### ISSUE THREAD

**Issue by anmolpuri** [SeleniumHQ/selenium#4370]
## Meta -
OS:  
macOS Sierra 10.12.4
Selenium-Webdriver Version:  
3.4.4
Browser:  
Chrome

WebDriver Version:  
59.0.3071.115

## Expected Behavior -

The code should be able to get the driver and start running tests on the node.

## Actual Behavior -

I have set up a selenium grid and a google chrome node using docker and when trying to connect to the hub to get the driver I get an Error 500.

Full error:
/Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok': status code 500 (Selenium::WebDriver::Error::ServerError)
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/bridge.rb:103:in `create_session'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/bridge.rb:54:in `handshake'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/driver.rb:39:in `initialize'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/common/driver.rb:58:in `new'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/common/driver.rb:58:in `for'
	from /Users/apuri/.rvm/gems/ruby-2.4.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver.rb:86:in `for'
	from grid.rb:3:in `<main>'

## Steps to reproduce -
create a docker-compose.yml with the following:

hub:
    image: 'selenium/hub'
    ports:
        - '4444:4444'

chrome:
    image: 'selenium/node-chrome-debug'
    hostname: chrome
    ports:
        - '5909:5900'
    links:
        - hub

Run docker-compose up -d

Once it's up and running, you should be able to navigate to localhost:4444 and see the selenium grid page. Clicking the console should bring you to the page with the nodes.

The ruby script that I have is:

require 'selenium-webdriver'

@driver = Selenium::WebDriver.for(
  :remote,
  url: "http://localhost:4444/wd/hub", desired_capabilities: :chrome) # you can also use :chrome, :safari, etc.

Running this gives me the error, I've tried 0.0.0.0 instead of localhost too with the same result. I've also tried mapping to a different port but it doesn't work. I have selenium-webdriver v 3.4.4.
[Selenium-Docker.zip](https://github.com/SeleniumHQ/selenium/files/1174561/Selenium-Docker.zip)

**Comment by lmtierney** [comment]
> ports:
> - '5909:5900'

Is this a typo or is this how it really is in your compose file?

**Comment by lmtierney** [comment]
So I went ahead and tried it out myself. It is actually running into issue #3808 which will be fixed in the next release of the hub. In order to use the latest hub, you'll have to use version `3.4.0` of the ruby gem (to avoid other issues as well)

**Comment by anmolpuri** [comment]
Ok thanks a lot!
