### ISSUE TITLE
driver.findelement().sendKeys('Random Message') is behaving inconsistent, skipping characters while typing on browser.

### ISSUE THREAD

**Issue by rajatpuneak** [SeleniumHQ/selenium#4374]
## Meta -
OS:  Windows 7
Selenium Version:  3.5.0
Browser:  Chrome - Chromedriver 2.31.0 - (Node/npm chromedriver)

Browser Version:   Version 59.0.3071.115 (Official Build) (64-bit)

## Expected Behavior -
sendKeys('Random Message') should type in "Random Message" always.

## Actual Behavior -
but at times is typing "Rando Message" / "Random Messag" / "Random Messge" / "Random Messae" etc

## Steps to reproduce -
on input fields, textArea trying to set text using sendKeys('') method.

**Comment by luke-hill** [comment]
Can you double check you've entered the correct Chrome version. Are you sure you don't mean *59*? - Chrome Version 49 is archaic, and is not supported by chromedriver 2.31

Assuming you mean 59, then obviously this can continue. I will let a maintainer contribute more.

**Comment by rajatpuneak** [comment]
Yes, its Version 59.0.3071.115 (Official Build) (64-bit), mistakenly did not update in the above issue.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by twalpole** [comment]
You're probably experiencing - https://bugs.chromium.org/p/chromedriver/issues/detail?id=1771&q=sendkeys&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary .  It was an issue with a previous version of chromedriver and appears to have cropped up again.

**Comment by p0deje** [comment]
@twalpole Thanks for pointing this out, closing this with https://bugs.chromium.org/p/chromedriver/issues/detail?id=1771.
