### ISSUE TITLE
Drag and Drop on ExtJS Application

### ISSUE THREAD

**Issue by gvarun112** [SeleniumHQ/selenium#4376]
## Meta -
OS:  

Selenium Version:  3.1.0

Browser:  Chrome

Browser Version:   59.0.3071.115

Drag and Drop functionality is not working with an ExtJS Application

I have tried it both ways like below:

```
           Actions act = new Actions(driver);
            WebElement drag = driver.findElement(By.xpath(sourcexpath));
            WebElement drop = driver.findElement(By.xpath(targetxpath));
            act.dragAndDrop(drag, drop).build();
            act.perform();
```

```
                act.clickAndHold(source_element)
                        .moveToElement(target_element)
                        .release(source_element).perform();
```

None of these work because of the dynamic nature of ExtJS applications. Is there a work around for this?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
