### ISSUE TITLE
[SafariDriver] Unable to Login to Webpage

### ISSUE THREAD

**Issue by danielsantillan** [SeleniumHQ/selenium#4377]
## Meta -
OS:  
mac OS Sierra Version 10.12.5

Selenium Version:  
3.4.0

Browser:  
Safari 10.1.1 (12603.2.4)

## Expected Behavior -
Safari automated browser opens and follows nightwatch test cases. 
Correct login credentials should be accepted and the user should be directed to the main page of the website. 

## Actual Behavior -
Safari opens as expected and successfully runs any test cases that do not involve loging into the webpage. When it attempts to submit the correct login information, the safari page enters a loading state and the TC assertion fails because it is unable to confirm that we're now on the app main screen. 

Interestingly enough, if I interrupt the automation test and attempt to login to the page manually using the automated safari instance, I get the same error. Normal Safari does not have this issue. I can login as expected. To me, this suggests an issue with Safari itself. Is that consistent with what others thing

## Steps to reproduce -
I'm using nightwatch and have the following two files. "testSafariError.js" and "safariErrorPage.js"
Please run the following:
_nightwatch --e 'safari' --test testSafariError.js_

**"testSafariError.js"**

```export default {

  after: (client) => {
    client.end();
  },

  'Login/Home - Login - Login with correct credentials': (client) => {
    const loginPage = client.page.safariErrorPage();
    loginPage.navigate();
    client.pause(2000);
    loginPage.login('{username}', '{password}');

    // after successful login
    // we are redirected to projects page
    client.pause(4000);
    client.assert.urlContains('projects');
  },
};
```

**"safariErrorPage.js"**

```const loginCommands = {
  clickElementVisible(element) {
    return this
      .waitForElementVisible(element)
      .click(element);
  },

  clickElementPresent(element) {
    return this
      .waitForElementPresent(element)
      .click(element);
  },

  login(email, pass) {
    return this
      .waitForElementVisible('@emailInput')
      .setValue('@emailInput', email)
      .clearValue('@passInput')
      .setValue('@passInput', pass)
      .clickElementVisible('@loginButton');
  },
};

const loginElements = {
  emailInput: 'input[type=email]',
  passInput: 'input[name=password]',
  loginButton: 'button[type=submit]',
};

export default {
  url: '{Page URL}',
  commands: [loginCommands],
  elements: {
    emailInput: {
      selector: loginElements.emailInput,
      locateStrategy: 'css',
    },
    passInput: {
      selector: loginElements.passInput,
      locateStrategy: 'css',
    },
    loginButton: {
      selector: loginElements.loginButton,
      locateStrategy: 'css',
    },
  },
};
```

**Comment by p0deje** [comment]
You're saying this is Safari issue. Selenium team doesn't maintain SafariDriver, so I suggest reporting this to https://bugreport.apple.com/
