### ISSUE TITLE
Backward compatible error codes

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#4380]
I haven't investigated to see if other bindings have this issue, so I'm marking it C-rb, but we should verify it is addressed on all bindings before closing it.

When running tests on Firefox through a remote server, the new w3c errors are getting translated in the server, but not properly handled in the bindings.

Essentially we need to implement all of the "new" error codes that have been added here: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/ErrorCodes.java

I'm also marking it as easy because this makes an excellent "fix a bug become a committer" item.

**Comment by jaysonesmith** [comment]
I'll get started on it

**Comment by jimevans** [comment]
These error codes have been implemented in .NET since aefe62e. Since .NET was the last holdout to the issue, I'll be closing it momentarily.
