### ISSUE TITLE
Session delete timeout

### ISSUE THREAD

**Issue by christopheg** [SeleniumHQ/selenium#4384]
I am running the docker-selenium image (https://github.com/elgalu/docker-selenium) for our CI tests.
When starting a test, we randomly experience a timeout. 
Our PHP webdriver client gives this error:

```
[Facebook\WebDriver\Exception\WebDriverCurlException]
Curl error thrown for http DELETE to /session/d5b562f9-6902-4e7c-b36d-3d872ebe3eef
Operation timed out after 30001 milliseconds with 0 bytes received
```

During such a timeout, Chrome seems to be unresponsive. A video of Chrome during this timeout can be found in attachment: [test_error.zip](https://github.com/SeleniumHQ/selenium/files/1182580/test_error.zip)

During this problem, this is what can be found in selenium-node-chrome-stderr.log:

```
23:58:50.690 INFO - Executing: [new session: Capabilities [{browserName=chrome, chromeOptions={args=[no-sandbox], binary=}, platform=ANY}]])
23:58:50.698 INFO - Creating a new session for Capabilities [{browserName=chrome, chromeOptions={args=[no-sandbox], binary=}, platform=ANY}]
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on port 4579
Only local connections are allowed.
23:58:52.655 INFO - Detected dialect: OSS
23:58:52.658 INFO - Done: [new session: Capabilities [{browserName=chrome, chromeOptions={args=[no-sandbox], binary=}, platform=ANY}]]
23:58:52.669 INFO - Executing: [implicitly wait: 5000])
23:58:52.672 INFO - Done: [implicitly wait: 5000]
23:58:52.677 INFO - Executing: [maximise window])
23:58:52.790 INFO - Done: [maximise window]
23:58:52.804 INFO - Executing: [get: http://xxxx.xxx.xxx])
23:59:55.402 INFO - Executing: [delete session: d5b562f9-6902-4e7c-b36d-3d872ebe3eef])
```

Selenium Hub version information:
Selenium build info: version: '3.3.1', revision: '5234b32'

**Comment by manoj9788** [comment]
Is it better to raise it here https://github.com/elgalu/docker-selenium/issues ?

**Comment by p0deje** [comment]
I'm not sure if this is related to Docker or Grid.

@ddavison Any thoughts?

**Comment by christopheg** [comment]
already created a ticket at docker-selenium:
https://github.com/elgalu/docker-selenium/issues/163

**Comment by barancev** [comment]
Can you reproduce this issue without docker, running grid on local machine?

**Comment by barancev** [comment]
Can you reproduce this issue without docker, running grid on local machine?

**Comment by christopheg** [comment]
Sorry, I haven't got the time yet to deploy a new machine with the Selenium grid. 
It could however be that this problem is performance-related. We only see this error in our CI where we are running up to 3 tests in parallel. Each tests launches a mysql docker, an apache docker, a php-cli docker and a selenium grid docker. That makes 12 dockers in total running on the same machine.
Do you think that log files of the selenium docker could help finding the problem?

**Comment by barancev** [comment]
Quite possible it's a performance issue. Try to add resources or use a more performant machine. Also it can be a docker image configuration issue. Or chromedriver issue. According to the log, grid passed the quit command to the driver. Try to figure out how to obtain chromedriver logs from the node.

**Comment by barancev** [comment]
Closing the issue, there is nothing actionable in it.
