### ISSUE TITLE
ExpectedConditions.visibilityOfElement(element) does not work to find element

### ISSUE THREAD

**Issue by atomar09** [SeleniumHQ/selenium#4385]
## Meta -
OS:  
OSX 10.12.6
Selenium Version:  
3.4.0
Browser:  
Firefox 54.0.1, geckodriver 0.18
Chrome 59.0.3071.115, chromedriver 2.30
It happens on Firefox and Chrome both, it does not look like a FF specific issue.

Browser Version:  
Firefox 54.0.1 (64-bit)
Chrome 59.0.3071.115 (64-bit)

## Expected Behavior -
Element should be found by using ExpectedConditions.visibilityOfElement(element)

## Actual Behavior -
Element is not found by using ExpectedConditions.visibilityOfElement(element)

## Steps to reproduce -
Please execute this code, I have mentioned the comments in the code for which line is not working as expected.

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class ExplicitWaitTest {

	private WebDriver driver;
	private String baseUrl = "https://letskodeit.teachable.com/p/practice";

	@Before
	public void setUp() {
		System.setProperty("webdriver.gecko.driver", "<replace this with geckodriver path>");
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
	}

	@Test
	public void testWithExplicitTime() {
		driver.get(baseUrl);
		driver.findElement(By.xpath("//div[@id='navbar']//a[contains(text(),'Login')]")).click();

		WebDriverWait wait = new WebDriverWait(driver, 3);

		// ExpectedConditions.visibilityOf(element) -> This method is not finding the element
		WebElement emailField = wait.until(
				ExpectedConditions.visibilityOf(driver.findElement(By.id("user_email"))));
		
		// ExpectedConditions.visibilityOfElementLocated(locator) -> This is finding the element correctly
		// WebElement emailField = wait.until(
		//		ExpectedConditions.visibilityOfElementLocated(By.id("user_email")));
		emailField.sendKeys("test data");
	}

	@After
	public void tearDown() throws InterruptedException {
		Thread.sleep(2000); // just for looking
		driver.quit();
	}
}

<img width="705" alt="screen shot 2017-07-28 at 4 03 54 pm" src="https://user-images.githubusercontent.com/15164626/28739278-8680d86a-73ae-11e7-9b46-f58a6436b4fd.png">

**Comment by p0deje** [comment]
You need to use `ExpectedConditions.visibilityOfElementLocated` - it ensures that:

a) element is present in DOM
b) element is visible

When you use `ExpectedConditions.visibilityOf` it doesn't check that element is present in DOM.

See documentation http://seleniumhq.github.io/selenium/docs/api/java/index.html. Closing since it works as expected.

**Comment by atomar09** [comment]
Thanks!
ExpectedConditions.visibilityOf(element) should only be used when we are used that element is present in the DOM, but we want to wait for it's visibility?

**Comment by p0deje** [comment]
Yes.
