### ISSUE TITLE
sockjs client unreleasable dependency problem

### ISSUE THREAD

**Issue by bryanrasmussen** [SeleniumHQ/selenium#4388]
## Meta -
OS:  Windows 10
Selenium Version:  latest - cannot npm install webdriver
Expected Behavior -
Selenium-webdriver npm library is installed

## Actual Behavior -
installation fails and I get message 
PS D:\projects\NGANGA\nganga_projects\accessbility> npm install selenium-webdriver
npm ERR! code ETARGET
npm ERR! notarget No matching version found for sockjs-client@0.0.0-unreleasable
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruger\AppData\Roaming\npm-cache\_logs\2017-07-30T18_58_59_647Z-debug.log

## Steps to reproduce -
run npm install selenium-webdriver on a system that hasn't had it installed before.

- the complete error log is 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'selenium-webdriver' ]
2 info using npm@5.0.4
3 info using node@v6.9.1
4 verbose npm-session 83764cee881fc252
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/selenium-webdriver 23ms (from cache)
8 silly pacote tag manifest for selenium-webdriver@latest fetched in 92ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 http fetch GET 200 https://registry.npmjs.org/sockjs-client 15ms (from cache)
13 silly registry:manifest no matching version for sockjs-client@0.0.0-unreleasable in the cache. Forcing revalidation
14 http fetch GET 304 https://registry.npmjs.org/sockjs-client 526ms (from cache)
15 silly fetchPackageMetaData error for sockjs-client@0.0.0-unreleasable No matching version found for sockjs-client@0.0.0-unreleasable
16 verbose type version
17 verbose stack sockjs-client: No matching version found for sockjs-client@0.0.0-unreleasable
17 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:61:11)
17 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:51:18)
17 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
17 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
17 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
17 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
17 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
17 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
17 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
17 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
17 verbose stack     at runCallback (timers.js:637:20)
17 verbose stack     at tryOnImmediate (timers.js:610:5)
17 verbose stack     at processImmediate [as _immediateCallback] (timers.js:582:5)
18 verbose cwd D:\projects\NGANGA\nganga_projects\accessbility
19 verbose Windows_NT 10.0.14393
20 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "selenium-webdriver"
21 verbose node v6.9.1
22 verbose npm  v5.0.4
23 error code ETARGET
24 error notarget No matching version found for sockjs-client@0.0.0-unreleasable
25 error notarget In most cases you or one of your dependencies are requesting
25 error notarget a package version that doesn't exist.
26 verbose exit [ 1, true ]

**Comment by p0deje** [comment]
I can't reproduce. Installation completes successfully on Windows 10:

```
> npm install selenium-webdriver
+ selenium-webdriver@3.5.0
added 31 packages in 24.438s
```

Also, I don't see how selenium-webdriver depends on sockjs-client, so it's likely to be your own dependency specified in `package.json`.

**Comment by mojoaxel** [comment]
see https://github.com/substack/shoe/issues/27
