### ISSUE TITLE
lintText is not working with Selenium 2.45.0

### ISSUE THREAD

**Issue by mrjaiswar** [SeleniumHQ/selenium#439]
lintText is not working with Selenium 2.45.0

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mrjaiswar** [comment]
With Selenium ver 2.44.0 when I am trying to execute below code it works but when I switch to selenium 2.45.0 it is not able to perform the action.

driver.findElement(By.linkText("Admin Tools")).click();

here I am using linkText method to click

below is the source code:
<a style="font-weight:bold" href="/app/page/AdminTools">Admin Tools</a>

**Comment by ddavison** [comment]
it's most likely because the link text, differs in the html.

```html
<a href="#">Admin Tools</a>
```

is different than

```html
<a href="#">
                       Admin
                        Tools
</a>
```
for example.

**Comment by mrjaiswar** [comment]
true, but in my case no difference is there.
It is nothing to deal with the source code, problem happens when I switch to selenium 2.45.0 from selenium 2.44

**Comment by ddavison** [comment]
ok.  Do what @barancev had noted, and try bringing up your issue with the selenium users group, or post a question on StackOverflow.

**Comment by AutomatedTester** [comment]
Please give a reduced test case with the least amount of HTML to reproduce and the code we can execute 



—
