### ISSUE TITLE
Update Promise definition

### ISSUE THREAD

**Issue by Martin-Wegner** [SeleniumHQ/selenium#4391]
Since TypeScript 2.4:

> Type 'typeof Promise' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.

See https://github.com/Microsoft/vscode/pull/30228 and https://github.com/Microsoft/vscode/pull/30268

```
import { promise } from 'selenium-webdriver';
...
async setViewportSize(viewPortWidthInPx: number, viewPortHeightInPx: number): promise.Promise<void> {
...
```

**Comment by jleyba** [comment]
Looks like you filed this against the wrong project. Selenium does not use TypeScript

**Comment by Martin-Wegner** [comment]
@jleyba sorry, I thought that you are responsible for the Selenium TypeScript definition files.

**Comment by SimonSchick** [comment]
@jleyba Just curious, have you considered shipping your own typings for TS? It's getting quiet popular!

**Comment by jleyba** [comment]
No, I've never done anything with TS. I barely have time to work on Selenium anymore as it is :(

Contributions are welcome though!
