### ISSUE TITLE
geb.driver.DriverCreationException: failed to create driver from callback 

### ISSUE THREAD

**Issue by renukaprasadcb06** [SeleniumHQ/selenium#4392]
Hi

I am getting below Exception while running test scripts.

geb.driver.DriverCreationException: failed to create driver from callback 'script1501516684770944233575$_run_closure1@6601cc93'
java.lang.NoClassDefFoundError: Lorg/openqa/selenium/remote/html5/RemoteWebStorage;
failed to create driver from callback 'script1501516684770944233575$_run_closure1@6601cc93'

OS: Windows 10 64 bit
Chrome browser: v60 (latest one)
Selenium :-2.43.1
Chrome web driver:-2.24.417431

geb-version:0.10.0
geb-testng-version:0.13.1
geb-spoc-version:0.13.1

Thanks in Advance...!

**Comment by barancev** [comment]
Please report this issue to the Geb tracker.
