### ISSUE TITLE
Browser long starts - DriverService waitUntilAvailable timeout should be parameterized

### ISSUE THREAD

**Issue by palladium-dkt** [SeleniumHQ/selenium#4394]
## Meta -
OS: 
Windows10, Linux CentOs 7

Selenium Version:  
3.4.0
Browser:  
All

## Expected Behavior -
On some specific environment or after many tests, browsers can be a bit long to start (more than 30sec) so we must be able to set a custom timeout when Driver.waitUntilAvailable() function is called.
For example we can have a setLaunchTimeout(timout) function on WebDriver class or a configuration key.

## Actual Behavior -
Timeout is set to 20sec with no way to change it. We have firefoxes than starts in 30 or 40 sec after performing tests.

## Steps to reproduce -

Launch more than 5 firefoxes on the same computer, the 6th one should start in more than 20sec

**Comment by Tom-Trumper** [comment]
I've experienced the same issue when trying to launch Internet Explorer on a Windows 7 VM with limited memory (not an ideal arrangement of course) as part of a Grid environment, particularly when using the `ie.ensureCleanSession` capability. This typically manifests as a SO_TIMEOUT exception being thrown by the node if the browser session is not started within the 20 second timeout limit - however a browser session is eventually started by this process but it is not attached to a WebDriver session.

**Comment by prasanna532** [comment]
Iam facing this issue with firefox.

**Comment by diemol** [comment]
This seems to be already possible, here is the related code https://github.com/SeleniumHQ/selenium/blob/trunk/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L87

Closing this, but feel free to reopen in case it is not working as expected.
