### ISSUE TITLE
Unable to locate web object for salesforce in lightning mode

### ISSUE THREAD

**Issue by PrashantAxtria** [SeleniumHQ/selenium#4395]
Hi, 

Selenium is unable to identify web object in sales-force application in lightning mode.
Same script is working fine in classic view(objects are recognizable in classic view).

Please respond on priority as issue is a road-blocker for us.

Thank
Prashant

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by PrashantAxtria** [comment]
Thanks a lot for quick response, Shared link by you is not up and running. Is there any other link for selenium issues

**Comment by barancev** [comment]
It's up and running.
![image](https://user-images.githubusercontent.com/617090/28822238-28f0a066-76c1-11e7-98c9-9c0cad498f66.png)
