### ISSUE TITLE
findElement(By.linkText("")) not find correct UTF8 text

### ISSUE THREAD

**Issue by ginglove** [SeleniumHQ/selenium#4396]
## Meta -
OS:   Windows 10
Selenium Version:   3.4.0 
Browser:   Firefox
Browser Version:  54.0.1(20170628075643)

## Actual Behavior -
I have use findElement(By.linkText("Xe++")) in my previous session but when i use this again with text "Sự kiện". 
This bug happens , it cannot find my text "Sự kiện" and it run my previous successful session
## Steps to reproduce -
1.  driver.get("http://dantri.com.vn");
    driver.manage().timeouts().implicitlyWait(20,TimeUnit.SECONDS);
    WebElement svideo=driver.findElement(By.linkText("Xe++"));
2. This session find successful
3. I have try another 
    driver.get("http://dantri.com.vn");
    driver.manage().timeouts().implicitlyWait(20,TimeUnit.SECONDS);
    WebElement svideo=driver.findElement(By.linkText("Sự kiện"));

**Comment by barancev** [comment]
Please be more specific, what do you mean by "cannot find" -- an exception? some other element found instead?

**Comment by barancev** [comment]
Closing the issue due to inactivity, it's not clear what the problem is.
