### ISSUE TITLE
selenium running issue - HTMLLauncher.runHTMLSuite

### ISSUE THREAD

**Issue by SHUFIL** [SeleniumHQ/selenium#4398]
## Meta -
OS:  ubuntu 14-64bit

Selenium Version:  

Browser:  google chrom driver v60

Browser Version:  

## Steps to reproduce -
I getting this error 
org.openqa.selenium.server.SeleniumCommandTimedOutException
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:155)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:198)
        at org.openqa.selenium.server.SeleniumServer.runHtmlSuite(SeleniumServer.java:640)
        at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:305)
        at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:245)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:96)
i have tryed with java 1.8 , selenium-html-runner-3.4.0.jar, selenium-server-standalone-2.39.0.jar and selenium-server-standalone-3.4.0.jar with chrom driver_64 bit and Testhtml.html using below url 
https://gist.githubusercontent.com/gchr/300a16b0b3b5271247609a28b2e98a1f/raw/29ed38cdba0ac92358025b0fec00678570967987/selTest.html

**Comment by SHUFIL** [comment]
I have check with Firefox - getting this issue 
HTML suite exception seen:
org.openqa.selenium.server.SeleniumCommandTimedOutException
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:155)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:198)
        at org.openqa.selenium.server.SeleniumServer.runHtmlSuite(SeleniumServer.java:640)
        at org.openqa.selenium.server.SeleniumServer.boot(SeleniumServer.java:305)
        at org.openqa.selenium.server.SeleniumServer.main(SeleniumServer.java:245)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:96)
## script for firfox ##java -jar -Dwebdriver.gecko.driver=geckodriver selenium-server-standalone-2.39.0.jar -htmlSuite *firefox http://seleniumhq.org "./Tsuite.html" "/tmp/firefox-results.html"

## script for chorm ##java -jar -Dwebdriver.chrome.driver=chromedriver selenium-server-standalone-2.39.0.jar -timeout 600 -htmlSuite *googlechrome "http://seleniumhq.org/" "./Tsuite.html" "/tmp/chrome-resultss.html"

All files same folder only 
## HTML suite
https://gist.githubusercontent.com/gchr/300a16b0b3b5271247609a28b2e98a1f/raw/29ed38cdba0ac92358025b0fec00678570967987/selTest.html

**Comment by SHUFIL** [comment]
I have create htmlsuite using selenium IDE firefox plugin , getting same error .

**Comment by barancev** [comment]
1) The provided file is a test scenario. Please provide the test suite file too.
2) Please provide the full execution log for the version 3.4.0

**Comment by SHUFIL** [comment]
**test suite file** # if r u asking about testsuite.html , blow i have mentioned  .
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://seleniumhq.org" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>

</tbody></table>
</body>
</html>
__________________________________________________________________________________
if am using selenium-server-standalone-3.4.0.jar, i getting below error , previously i tried 2.39.0.jar only,
 
Unable to find the HTML runner. This is normally because you have not downloaded
or made available the 'selenium-leg-rc' jar on the CLASSPATH. Your test will
not be run.
Download the Selenium HTML Runner from http://www.seleniumhq.org/download/ and
use that in place of the selenium-server-standalone.jar for the simplest way of
running your HTML suite.

**Comment by barancev** [comment]
Please provide the *complete* execution log for the version 3.4.0

**Comment by SHUFIL** [comment]
./testing.sh
  PID TTY          TIME CMD
 1169 tty7     00:05:30 Xorg
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
Unable to find the HTML runner. This is normally because you have not downloaded
or made available the 'selenium-leg-rc' jar on the CLASSPATH. Your test will
not be run.
Download the Selenium HTML Runner from http://www.seleniumhq.org/download/ and
use that in place of the selenium-server-standalone.jar for the simplest way of
running your HTML suite.

**Comment by barancev** [comment]
Yes, for 3.4.0 you have to download so called html-runner: https://goo.gl/8mbqu4

**Comment by barancev** [comment]
java -jar selenium-html-runner-3.4.0.jar -htmlSuite bla-bla-bla

**Comment by SHUFIL** [comment]
root@mail:/var/lib/jenkins/selenium# ./testing.sh
  PID TTY          TIME CMD
 1169 tty7     00:05:30 Xorg
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
Multi-window mode is longer used as an option and will be ignored.
Port is longer used as an option and will be ignored.
1501771752319   geckodriver     INFO    geckodriver 0.18.0
1501771752326   geckodriver     INFO    Listening on 127.0.0.1:6512
1501771752687   geckodriver::marionette INFO    Starting browser /usr/lib/firefox/firefox with args ["-marionette"]

(firefox:14229): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:14229): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:14229): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:14229): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1501771753302   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771753305   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771753321   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771753322   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771753984   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771753986   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771753993   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771753994   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771756471   Marionette      INFO    Listening on port 46163
Aug 03, 2017 8:19:16 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-08-03 20:19:16.692:INFO::main: Logging initialized @5083ms to org.seleniumhq.jetty9.util.log.StdErrLog
2017-08-03 20:19:16.741:INFO:osjs.Server:main: jetty-9.4.z-SNAPSHOT
2017-08-03 20:19:16.780:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@6200f9cb{/tests,null,AVAILABLE}
2017-08-03 20:19:16.797:INFO:osjs.AbstractConnector:main: Started ServerConnector@698e872e{HTTP/1.1,[http/1.1]}{0.0.0.0:5634}
2017-08-03 20:19:16.797:INFO:osjs.Server:main: Started @5188ms
2017-08-03 20:19:17.247:INFO:osjs.AbstractConnector:main: Stopped ServerConnector@698e872e{HTTP/1.1,[http/1.1]}{0.0.0.0:5634}
2017-08-03 20:19:17.248:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@6200f9cb{/tests,null,UNAVAILABLE}
1501771757255   Marionette      INFO    New connections will no longer be accepted
Aug 03, 2017 8:19:17 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
java.lang.RuntimeException: Unable to find suite table: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="selenium.base" href="http://seleniumhq.org">
<title>New Test</title>
</head>
<body>
<table border="1" cellspacing="1" cellpadding="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>

</tbody></table>


</body></html>
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:118)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

root@mail:/var/lib/jenkins/selenium# ls /tmp/firefox-results.html/
root@mail:/var/lib/jenkins/selenium#

**Comment by SHUFIL** [comment]
i have try with different port , see the error 

root@mail:/var/lib/jenkins/selenium# ./testing.sh
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
  PID TTY          TIME CMD
 1169 tty7     00:05:30 Xorg
Multi-window mode is longer used as an option and will be ignored.
Port is longer used as an option and will be ignored.
1501771914009   geckodriver     INFO    geckodriver 0.18.0
1501771914013   geckodriver     INFO    Listening on 127.0.0.1:31704
1501771914421   geckodriver::marionette INFO    Starting browser /usr/lib/firefox/firefox with args ["-marionette"]

(firefox:14370): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:14370): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:14370): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:14370): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1501771914978   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771914981   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771914997   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771914998   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771915661   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771915662   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771915670   addons.xpi      WARN    Add-on langpack-en-ZA@firefox.mozilla.org is not compatible with application version.
1501771915671   addons.xpi      WARN    Add-on langpack-en-GB@firefox.mozilla.org is not compatible with application version.
1501771918229   Marionette      INFO    Listening on port 45105
Aug 03, 2017 8:21:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-08-03 20:21:58.521:INFO::main: Logging initialized @5168ms to org.seleniumhq.jetty9.util.log.StdErrLog
2017-08-03 20:21:58.568:INFO:osjs.Server:main: jetty-9.4.z-SNAPSHOT
2017-08-03 20:21:58.606:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@6200f9cb{/tests,null,AVAILABLE}
2017-08-03 20:21:58.621:INFO:osjs.AbstractConnector:main: Started ServerConnector@768ced4{HTTP/1.1,[http/1.1]}{0.0.0.0:16654}
2017-08-03 20:21:58.622:INFO:osjs.Server:main: Started @5269ms
2017-08-03 20:21:59.029:INFO:osjs.AbstractConnector:main: Stopped ServerConnector@768ced4{HTTP/1.1,[http/1.1]}{0.0.0.0:16654}
2017-08-03 20:21:59.033:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@6200f9cb{/tests,null,UNAVAILABLE}
1501771919039   Marionette      INFO    New connections will no longer be accepted
Aug 03, 2017 8:21:59 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
WARNING: Test of browser failed: *firefox
java.lang.RuntimeException: Unable to find suite table: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="selenium.base" href="http://seleniumhq.org">
<title>New Test</title>
</head>
<body>
<table border="1" cellspacing="1" cellpadding="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>

</tbody></table>


</body></html>
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.runHTMLSuite(HTMLLauncher.java:118)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.mainInt(HTMLLauncher.java:245)
        at org.openqa.selenium.server.htmlrunner.HTMLLauncher.main(HTMLLauncher.java:273)

root@mail:/var/lib/jenkins/selenium#
root@mail:/var/lib/jenkins/selenium#
root@mail:/var/lib/jenkins/selenium#
root@mail:/var/lib/jenkins/selenium#
root@mail:/var/lib/jenkins/selenium#
root@mail:/var/lib/jenkins/selenium# ls /tmp/firefox-results.html/

**Comment by barancev** [comment]
I suppose "$(pwd)/google.html" is **not** a suite file.

**Comment by barancev** [comment]
At least it does not contain any links to test scenarios.

**Comment by SHUFIL** [comment]
"$(pwd)/google.html" , for testing only i have used pwd, without pwd also error getting , previous chat i have mentioned   , can you please suggest how to fix this error .

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
