### ISSUE TITLE
C# bindings interpet error 33 as Insecure Certificate after closing and attempting a new session in Edge

### ISSUE THREAD

**Issue by InstyleVII** [SeleniumHQ/selenium#4405]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.4
Browser:  
Edge
Browser Version:  
16.16259

## Expected Behavior -
C# bindings return "Session Not Created Exception" when WebDriver throws an error 33.
## Actual Behavior -
C# bindings return "Insecure Certificate" when WebDriver throws an error  33.
## Steps to reproduce -
`try
{
    var service = EdgeDriverService.CreateDefaultService();
    service.UseVerboseLogging = true;
    var driver = new EdgeDriver(service);
    driver.Url = "https://www.bing.com/";
    Console.WriteLine("navigation complete");
    System.Threading.Thread.Sleep(5000);
    driver.Close();
    Console.WriteLine("Start new session");
    driver = new EdgeDriver(service);
    driver.Url = "https://www.bing.com/";
    driver.Close();
    if (driver != null) driver.Quit();
}
catch (Exception e)
{
    Console.WriteLine("Test failed with {0} error. callstack: {1}", e.Message, e.StackTrace);
}`

**Comment by jimevans** [comment]
Fixed in aefe62e.
