### ISSUE TITLE
Selenium IDE is not compatible with Firefox 55

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#4406]
Mozilla claimed (https://developer.mozilla.org/en-US/Add-ons/Installing_extensions)

> From Firefox 57 onwards, WebExtensions will be the only supported extension type, and Firefox will not load other types.
> 
> Even before Firefox 57, changes coming up in the Firefox platform will break many legacy extensions. These changes include multiprocess Firefox (e10s), sandboxing, and multiple content processes. Legacy extensions that are affected by these changes should migrate to WebExtensions if they can.

Yes, this happened to Selenium IDE too, it does not work in Firefox 55+

This issue is created to mark all other Selenium IDE issues that are related to FF 55+ as duplicates of this one.

I'm going to keep it open until we can provide an alternative solution, a capture-n-replay tool implemented as a WebExtentsion compatible with newest Firefox versions.

**Comment by kirangurram** [comment]
/Is this issue resolved or you guyz still working on the fix?

**Comment by schunt1** [comment]
Yes me too, I cant open a test case in Selenium IDE having upgraded to FF 55

**Comment by 05typesdc5** [comment]
I also get error on Windows 7 Firefox 55.0 and Selenium IDE 2.9.1.  Seems to have started happening right after I updated to Firefox 55.

message:

There was an unexpected error. Msg: TypeError: window.editor.infoPanel is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version
