### ISSUE TITLE
The setup FirefoxProfile in FirefoxOptions wipes the logging setting

### ISSUE THREAD

**Issue by BabyRoot** [SeleniumHQ/selenium#4410]
## Meta 
OS:  Windows 10
Selenium Version:  3.4.0
Browser:  Firefox + geckodriver 0.18.0
Browser Version:  54.0.1 (32bit)

## Expected Behavior -
If we set some profile in options and set the loglevel OFF - loglevel apply OFF
Something like in [DEF.txt](https://github.com/SeleniumHQ/selenium/files/1201668/DEF.txt) 

## Actual Behavior -
By default, the console displays a little information when working with Firefox
If we connect the profile in settings, then the loglevel is reset and we see a lot of unnecessary information in the console -  [PROFILE.txt](https://github.com/SeleniumHQ/selenium/files/1201670/PROFILE.txt)
If we set the loglevel to OFF and set some profile in options, then it does not apply
Now (profile + Level.OFF) it like - [PROFILE_OFF.txt](https://github.com/SeleniumHQ/selenium/files/1201671/PROFILE_OFF.txt)

## Steps to reproduce -
```
FirefoxOptions options = new FirefoxOptions();
FirefoxProfile myProfile = new FirefoxProfile();
options.setProfile(myProfile);
options.setLogLevel(Level.OFF);            
WebDriver driver = new FirefoxDriver(options);
driver.close();
```

If we set only setLogLevel - [LEVEL_OFF.txt](https://github.com/SeleniumHQ/selenium/files/1201672/LEVEL_OFF.txt) - correct work.

**Comment by barancev** [comment]
It's a different preference that causes log messages to appear, you have to disable extensions logging too:
```
FirefoxOptions options = new FirefoxOptions();
options.setProfile(myProfile);
options.addPreference("extensions.logging.enabled", false);
FirefoxDriver driver = new FirefoxDriver(options);
```

**Comment by larsen0815** [comment]
With that preference set to false I get this:

    Preference extensions.logging.enabled may not be overridden: frozen value=true, requested value=false".

OS: Debian Stretch
Selenium Version: 3.7.1
Firefox: 57.0+build4-0ubuntu0.16.0 (installed via Ubuntu PPA)
geckodriver: 0.19.1
