### ISSUE TITLE
Artifact "selenium-standalone-server" version 3.4.0 missing on Maven repo

### ISSUE THREAD

**Issue by mgavilan** [SeleniumHQ/selenium#4416]
## Meta -
OS:  Windows 10
Selenium Version:  3.4.0
Browser:  Not browser related

## Expected Behavior -
When using dependency to "selenium-standalone-server" version 3.4.0 in Maven pom.xml, it should be found and downloaded automatically from the central Maven Repository at [](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone) !

## Actual Behavior -
When using dependency to "selenium-standalone-server" version 3.4.0 in Maven pom.xml, it cannot be found, as it is not available in the central Maven Repository at [](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone) !

## Steps to reproduce -
Try to access link [](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone/3.4.0), it will return "404 Not Found"

Would you please check, why this version is not available in the central maven repository?

Thanks and regards
Marcos

**Comment by barancev** [comment]
Standalone server is, eh, standalone.
You need http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-server%7C3.4.0%7Cjar

**Comment by mgavilan** [comment]
Hi Alexei,

thanks a lot for this quick response.

Do I understand you correct: **_org.seleniumhq.selenium:selenium-server_** replaces the former **_org.seleniumhq.selenium:selenium-standalone-server_** and can be used compatible to the former artifact, by just modifying the dependency in pom.xml?

If so, is this documented somewhere in the official Selenium project?

Thanks for the clarification.

Bets regards
Marcos

**Comment by barancev** [comment]
We have no selenium-standalone-server artifact, and never had.

**Comment by mgavilan** [comment]
Hi Alexei,

again, thanks a lot for the really responsive reaction. May I ask whome you refer to by "we"?

Looking at the [ Selenium Downloads page](http://docs.seleniumhq.org/download/) the Selenium Standalone Server is listed very prominently in the beginning of the page, without any hint, that this does not come from Selenium.
Furthermore it is not listed in the "**Third Party**" section further down.

Just for my understanding, where _selenium-standalone-server_ comes from.

Thanks and regards
Marcos

**Comment by barancev** [comment]
"Selenium Standalone Server" listed on the download page is not a maven artifact.

**Comment by mgavilan** [comment]
Hi Alexei,

good to know, as it was available in the Maven repo until version 2.53.1 and I wasn't able to find any hint, that the new version is no longer a Maven artifact!

Regards
Marcos

**Comment by barancev** [comment]
Please provide a link to the atrifact you're talking about.

**Comment by mgavilan** [comment]
Hi Alexei,

it'S this one: [https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-server-standalone)

**Comment by barancev** [comment]
http://repo.jenkins-ci.org/releases/ is not an official maven (central) repository.
No idea who owns the repository, who and for what purpose deployed selenium-server-standalone there.

**Comment by ORESoftware** [comment]
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-server-standalone</artifactId>
    <version>2.46.0</version>
</dependency>

```
that is not working for me...what is the correct pom.xml value?
