### ISSUE TITLE
Read time out using Appium with Selenium Grid

### ISSUE THREAD

**Issue by kailo777** [SeleniumHQ/selenium#4419]
## Meta -
OS:  
Windows 7 (HUB)
macOS Sierra 10.12

Selenium Version:  
3.4.0

Appium Version:
1.6.5

Browser:  
Safari on iPhone 7 Plus (Real Device)

Hello togther I'm running my selenium Grid Hub on windows 7 
`java -jar selenium-server-standalone-3.4.0.jar -debug true -role hub -browserTimeout 60 -sessionTimeout 20000 `

Running on Mac
appium -nodeconfig iPhoneSafariLauncher.json -U UID

```
{
"capabilities": [
   {
        "browserName": "safari",
        "platformName": "iOS",
        "platformVersion" : "10.3",
        "udid": "UID",
        "deviceName": "iPhone7_QLIVE",
        "automationName": "XCUITest",
        "xcodeOrgId": "XXXXXXXX"   ,
        "xcodeSigningId": "iPhone Developer"
    }
  ],
"configuration":
   {
        "cleanUpCycle":20000,
        "timeout":30000,
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "url": "http://appiumnode:4723/wd/hub",
        "host": "appiumnode",
        "port": 4723,
        "role": "node",
        "maxSession": 5,
        "nodePolling": 5000,
        "downPollingLimit": 2,
        "register": true,
        "registerCycle": 5000,
        "hubPort": 4444,
        "hubHost": "hubHost",
        "hub": "hubHost:4444/grid/register",
        "unregisterIfStillDownAfter": 60000,
        "nodeStatusCheckTimeout": 10000
    }
}
```

Ping hubHost to appiumnode sucessfully
Ping appiumnode to hubHost successfully

Firewall is deacitvated for appiumnode 
Add firewall rule for hubhost:4444

## Expected Behavior -
Running my Testsuites sucessfully

## Actual Behavior -

The node is sucessfully added to the grid but during running my testsuite the following error occure:

21:31:35.107 DEBUG - Failed to check status of node: Read timed out

After that the hub trying to restart the test a couple of times. 

**After register node**
 
21:30:49.167 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
21:30:49.167 INFO - Launching Selenium Grid hub
2017-08-07 21:30:50.131:INFO::main: Logging initialized @1231ms to org.seleniumhq.jetty9.util.log.StdErrLog
21:30:50.143 INFO - Will listen on 4444
2017-08-07 21:30:50.184:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-08-07 21:30:50.211:INFO:osjs.session:main: DefaultSessionIdManager workerName=node0
2017-08-07 21:30:50.211:INFO:osjs.session:main: No SessionScavenger set, using defaults
2017-08-07 21:30:50.214:INFO:osjs.session:main: Scavenging every 660000ms
2017-08-07 21:30:50.220:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@71d15f18{/,null,AVAILABLE}
2017-08-07 21:30:50.440:INFO:osjs.AbstractConnector:main: Started ServerConnector@33cb5951{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-08-07 21:30:50.442:INFO:osjs.Server:main: Started @1542ms
21:30:50.443 INFO - Nodes should register to http://hubHost:4444/grid/register/
21:30:50.443 INFO - Selenium Grid hub is up and running
21:30:51.450 DEBUG - getting the following registration request  : {"capabilities":[{"browserName":"safari","platformName":"iOS","platformVersion":"10.3","udid
":"UID","deviceName":"iPhone7_QLIVE","automationName":"XCUITest","xcodeOrgId":"XXXXXXX","xcodeSigningId":"iPhone Develo
per"}],"configuration":{"cleanUpCycle":20000,"timeout":30000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","url":"http://appiumnode:4723/wd/hub","ho
st":"appiumnode","port":4723,"role":"node","maxSession":5,"nodePolling":5000,"downPollingLimit":2,"register":true,"registerCycle":5000,"hubPort":4444,"hubHost":"N
BMU036","hub":"NBMU036:4444/grid/register","unregisterIfStillDownAfter":60000,"nodeStatusCheckTimeout":10000,"id":"http://appiumnode:4723"}}
21:30:51.519 DEBUG - Using class org.openqa.grid.selenium.proxy.DefaultRemoteProxy
21:30:51.520 WARN - Max instance not specified. Using default = 1 instance
21:30:51.521 DEBUG - starting cleanup thread
21:30:51.522 DEBUG - cleanup thread starting...
21:30:51.522 INFO - Registered a node http://appiumnode:4723
21:30:51.525 DEBUG - proxy added http://appiumnode:4723
21:30:56.531 DEBUG - Closing connections idle longer than 100 MILLISECONDS
21:30:56.557 DEBUG - CookieSpec selected: default
21:30:56.570 DEBUG - Auth cache not set in the context
21:30:56.571 DEBUG - Connection request: [route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
21:30:56.584 DEBUG - Connection leased: [id: 0][route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
21:30:56.585 DEBUG - Opening connection {}->http:/appiumnode:4723
21:30:56.592 DEBUG - Connecting to appiumnode/appiumnode:4723
21:30:56.618 DEBUG - Connection established hubHost:51596<->appiumnode:4723
21:30:56.618 DEBUG - http-outgoing-0: set socket timeout to 10000
21:30:56.619 DEBUG - Executing request GET /wd/hub/status HTTP/1.1
21:30:56.619 DEBUG - Target auth state: UNCHALLENGED
21:30:56.620 DEBUG - Proxy auth state: UNCHALLENGED
21:30:56.622 DEBUG - http-outgoing-0 >> GET /wd/hub/status HTTP/1.1
21:30:56.622 DEBUG - http-outgoing-0 >> Host: appiumnode:4723
21:30:56.623 DEBUG - http-outgoing-0 >> Connection: Keep-Alive
21:30:56.623 DEBUG - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
21:30:56.623 DEBUG - http-outgoing-0 >> Accept-Encoding: gzip,deflate
21:30:56.623 DEBUG - http-outgoing-0 >> "GET /wd/hub/status HTTP/1.1[\r][\n]"
21:30:56.624 DEBUG - http-outgoing-0 >> "Host: appiumnode:4723[\r][\n]"
21:30:56.624 DEBUG - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
21:30:56.625 DEBUG - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)[\r][\n]"
21:30:56.625 DEBUG - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
21:30:56.625 DEBUG - http-outgoing-0 >> "[\r][\n]"
21:30:56.671 DEBUG - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
21:30:56.672 DEBUG - http-outgoing-0 << "X-Powered-By: Express[\r][\n]"
21:30:56.673 DEBUG - http-outgoing-0 << "Access-Control-Allow-Origin: *[\r][\n]"
21:30:56.674 DEBUG - http-outgoing-0 << "Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS,DELETE[\r][\n]"
21:30:56.674 DEBUG - http-outgoing-0 << "Access-Control-Allow-Headers: origin, content-type, accept[\r][\n]"
21:30:56.675 DEBUG - http-outgoing-0 << "Content-Type: application/json; charset=utf-8[\r][\n]"
21:30:56.676 DEBUG - http-outgoing-0 << "Content-Length: 83[\r][\n]"
21:30:56.677 DEBUG - http-outgoing-0 << "ETag: W/"53-iSAFMe/inxxA2uDWSE1UX7Igtu8"[\r][\n]"
21:30:56.678 DEBUG - http-outgoing-0 << "Date: Mon, 07 Aug 2017 19:30:56 GMT[\r][\n]"
21:30:56.678 DEBUG - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
21:30:56.679 DEBUG - http-outgoing-0 << "[\r][\n]"
21:30:56.680 DEBUG - http-outgoing-0 << "{"status":0,"value":{"build":{"version":"1.6.5","revision":null}},"sessionId":null}"
21:30:56.687 DEBUG - http-outgoing-0 << HTTP/1.1 200 OK
21:30:56.688 DEBUG - http-outgoing-0 << X-Powered-By: Express
21:30:56.689 DEBUG - http-outgoing-0 << Access-Control-Allow-Origin: *
21:30:56.689 DEBUG - http-outgoing-0 << Access-Control-Allow-Methods: GET,POST,PUT,OPTIONS,DELETE
21:30:56.690 DEBUG - http-outgoing-0 << Access-Control-Allow-Headers: origin, content-type, accept
21:30:56.690 DEBUG - http-outgoing-0 << Content-Type: application/json; charset=utf-8
21:30:56.691 DEBUG - http-outgoing-0 << Content-Length: 83
21:30:56.692 DEBUG - http-outgoing-0 << ETag: W/"53-iSAFMe/inxxA2uDWSE1UX7Igtu8"
21:30:56.692 DEBUG - http-outgoing-0 << Date: Mon, 07 Aug 2017 19:30:56 GMT
21:30:56.693 DEBUG - http-outgoing-0 << Connection: keep-alive
21:30:56.705 DEBUG - Connection can be kept alive indefinitely
21:30:56.713 DEBUG - Connection [id: 0][route: {}->http://appiumnode:4723] can be kept alive indefinitely
21:30:56.714 DEBUG - Connection released: [id: 0][route: {}->http://appiumnode:4723][total kept alive: 1; route allocated: 1 of 2000; total allocated: 1 of 2000]

**Now Running the testsuite** 
21:31:23.955 INFO - Got a request to create a new session: Capabilities [{platformVersion=10.3, name=build/webapp/app/intern, browserName=safari, idle-timeout=
60, platformName=iOS, deviceName=iPhone7_QLIVE}]
21:31:23.956 DEBUG - Available nodes: [http://appiumnode:4723]
21:31:23.956 DEBUG - Trying to create a new session on node http://appiumnode:4723
21:31:23.956 INFO - Trying to create a new session on test slot {platformVersion=10.3, xcodeOrgId=QG2X3EN69M, automationName=XCUITest, browserName=safari, plat
formName=iOS, udid=UID, deviceName=iPhone7_QLIVE, xcodeSigningId=iPhone Developer}
21:31:23.959 DEBUG - Closing connections idle longer than 100 MILLISECONDS
21:31:23.960 DEBUG - http-outgoing-4: Close connection
21:31:23.961 DEBUG - CookieSpec selected: default
21:31:23.961 DEBUG - Auth cache not set in the context
21:31:23.962 DEBUG - Connection request: [route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
21:31:23.962 DEBUG - Connection leased: [id: 5][route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
21:31:23.962 DEBUG - Opening connection {}->http://appiumnode:4723
21:31:23.963 DEBUG - Connecting to appiumnode/appiumnode:4723
21:31:24.065 DEBUG - Connection established hubHost:51607<->appiumnode:4723
21:31:24.066 DEBUG - http-outgoing-5: set socket timeout to 134000
21:31:24.067 DEBUG - Executing request POST /wd/hub/session HTTP/1.1
21:31:24.069 DEBUG - Target auth state: UNCHALLENGED
21:31:24.070 DEBUG - Proxy auth state: UNCHALLENGED
21:31:24.071 DEBUG - http-outgoing-5 >> POST /wd/hub/session HTTP/1.1
21:31:24.072 DEBUG - http-outgoing-5 >> User-Agent: dojo/2.0.0-dev Node.js/6.10.3
21:31:24.073 DEBUG - http-outgoing-5 >> Connection: close
21:31:24.074 DEBUG - http-outgoing-5 >> Host: localhost:4444
21:31:24.074 DEBUG - http-outgoing-5 >> Accept: application/json,text/plain;q=0.9
21:31:24.075 DEBUG - http-outgoing-5 >> Content-Type: application/json;charset=UTF-8
21:31:24.076 DEBUG - http-outgoing-5 >> Content-Length: 174
21:31:24.077 DEBUG - http-outgoing-5 >> Accept-Encoding: gzip,deflate
21:31:24.078 DEBUG - http-outgoing-5 >> "POST /wd/hub/session HTTP/1.1[\r][\n]"
21:31:24.079 DEBUG - http-outgoing-5 >> "User-Agent: dojo/2.0.0-dev Node.js/6.10.3[\r][\n]"
21:31:24.080 DEBUG - http-outgoing-5 >> "Connection: close[\r][\n]"
21:31:24.081 DEBUG - http-outgoing-5 >> "Host: localhost:4444[\r][\n]"
21:31:24.081 DEBUG - http-outgoing-5 >> "Accept: application/json,text/plain;q=0.9[\r][\n]"
21:31:24.082 DEBUG - http-outgoing-5 >> "Content-Type: application/json;charset=UTF-8[\r][\n]"
21:31:24.083 DEBUG - http-outgoing-5 >> "Content-Length: 174[\r][\n]"
21:31:24.083 DEBUG - http-outgoing-5 >> "Accept-Encoding: gzip,deflate[\r][\n]"
21:31:24.084 DEBUG - http-outgoing-5 >> "[\r][\n]"
21:31:24.085 DEBUG - http-outgoing-5 >> "{"desiredCapabilities":{"name":"build/webapp/app/intern","idle-timeout":60,"deviceName":"iPhone7_QLIVE","platformName"
:"iOS","platformVersion":"10.3","browserName":"safari"}}"
21:31:25.049 DEBUG - Closing connections idle longer than 100 MILLISECONDS
21:31:25.052 DEBUG - CookieSpec selected: default
21:31:25.053 DEBUG - Auth cache not set in the context
21:31:25.054 DEBUG - Connection request: [route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
21:31:25.055 DEBUG - Connection leased: [id: 6][route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 2 of 2000; total allocated: 2 of 2000]
21:31:25.056 DEBUG - Opening connection {}->http://appiumnode:4723
21:31:25.057 DEBUG - Connecting to appiumnode/appiumnode:4723
21:31:25.090 DEBUG - Connection established hubHost:51608<->appiumnode:4723
21:31:25.091 DEBUG - http-outgoing-6: set socket timeout to 10000
21:31:25.092 DEBUG - Executing request GET /wd/hub/status HTTP/1.1
21:31:25.092 DEBUG - Target auth state: UNCHALLENGED
21:31:25.093 DEBUG - Proxy auth state: UNCHALLENGED
21:31:25.094 DEBUG - http-outgoing-6 >> GET /wd/hub/status HTTP/1.1
21:31:25.094 DEBUG - http-outgoing-6 >> Host: appiumnode:4723
21:31:25.095 DEBUG - http-outgoing-6 >> Connection: Keep-Alive
21:31:25.095 DEBUG - http-outgoing-6 >> User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
21:31:25.096 DEBUG - http-outgoing-6 >> Accept-Encoding: gzip,deflate
21:31:25.097 DEBUG - http-outgoing-6 >> "GET /wd/hub/status HTTP/1.1[\r][\n]"
21:31:25.097 DEBUG - http-outgoing-6 >> "Host: appiumnode:4723[\r][\n]"
21:31:25.098 DEBUG - http-outgoing-6 >> "Connection: Keep-Alive[\r][\n]"
21:31:25.099 DEBUG - http-outgoing-6 >> "User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)[\r][\n]"
21:31:25.099 DEBUG - http-outgoing-6 >> "Accept-Encoding: gzip,deflate[\r][\n]"
21:31:25.099 DEBUG - http-outgoing-6 >> "[\r][\n]"
21:31:35.102 DEBUG - http-outgoing-6 << "[read] I/O error: Read timed out"
21:31:35.103 DEBUG - http-outgoing-6: Close connection
21:31:35.104 DEBUG - http-outgoing-6: Shutdown connection
21:31:35.105 DEBUG - Connection discarded
21:31:35.105 DEBUG - Connection released: [id: 6][route: {}->http://appiumnode:4723][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
21:31:35.107 DEBUG - Failed to check status of node: Read timed out
Terminate batch job (Y/N)? Y

Thanks in Advance 

Best Regards

Kai

**Comment by p0deje** [comment]
This looks like Appium issue, not Selenium. Please provide a test case with only Selenium to re-open the issue.
