### ISSUE TITLE
How do I open a new tab in IE using selenium (java) and open a url in that tab (not window)

### ISSUE THREAD

**Issue by coyun** [SeleniumHQ/selenium#442]
How do I open a new tab in IE using selenium (java) and open a url in that tab (not window)? I am using the below code to open a new tab?

driver.get("https://google.com/");

//below line of code opens a new tab but does sets control on new tab.
driver.findElement(By.cssSelector("Body")).sendKeys(Keys.CONTROL + "t");//opens new tab

// As control does not sets on new tab, the below link opens on first tab only..
driver.get("https://facebook.com/");//but load facebook in first tab i.e on google page  
Can anyone tell me, how to shift control to new tab so that the facebook link opens in that new tab.

Hi

I using Selenium Web-Driver Version 2.40 and IE 11.0

WebDriver driver = new InternetExplorerDriver(ieCapabilities);

driver.manage().window().maximize();

driver.get("https://google.com/");

driver.findElement(By.cssSelector("Body")).sendKeys(Keys.CONTROL + "t");//opens new tab

//Store the current window handle

String winHandleBefore = driver.getWindowHandle();

//Perform the click operation that opens new window //Switch to new window open

for(String winHandle : driver.getWindowHandles()){

driver.switchTo().window(winHandle);

driver.get("https://facebook.com/");

}

// Perform the actions on new window

//Close the new window, if that window no more required

driver.close();

//Switch back to original browser (first window)

driver.switchTo().window(winHandleBefore);

//continue with original browser (first window)

I am not able to open facebook on new tab of same window..

Regards Shashank Goyal

http://stackoverflow.com/questions/22820527/how-to-open-new-tab-in-ie-using-selenium-java-and-open-a-url-in-that-tab-not

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by ddavison** [comment]
@coyun , I am sircapsalot on StackOverflow, the person that answered that particular question.  Did that answer not help you?  I told you that Selenium doesn't care the difference between a window and tab, and frankly neither should you.
