### ISSUE TITLE
Windows Server 2012, IE input disabled when running tests in service mode

### ISSUE THREAD

**Issue by webdeveloperninja** [SeleniumHQ/selenium#4420]
## Meta -
OS:  
Windows Server 2012 Service Mode
Selenium Version:  
2.52.0
Browser:  
Internet Explorer 11

## Expected Behavior -
Send keys fills input field. 

## Actual Behavior -
In service mode IE 11 inputs will not take focus. It is impossible to fill out inputs. Buttons, Check boxes, radios all work fine. It is almost like the inputs are disabled.
```
    it('should login', () => {
        let userNameInput = $('#username');
        let passwordInput = $('#password');
        let loginSubmitButton = $('#submit');
        let selectLocationButton = $('#select-location');

        userNameInput.sendKeys(USERNAME);

        passwordInput.sendKeys(PASSWORD);

    });```

**Comment by jimevans** [comment]
What does "service mode" mean? If you mean attempting to run `IEDriverServer.exe` in the context of a Windows service [that is expressly unsupported](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#running-iedriverserverexe-under-a-windows-service).

**Comment by webdeveloperninja** [comment]
@jimevans thank you closing
