### ISSUE TITLE
Selenium hangs over socket read 

### ISSUE THREAD

**Issue by dkrishnam** [SeleniumHQ/selenium#4422]
Threads are getting hanged on socket read and below is the thread dump.

Thread 2041: (state = IN_NATIVE)
 - java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[], int, int, int) @bci=0 (Compiled frame; information may be imprecise)
 - java.net.SocketInputStream.socketRead(java.io.FileDescriptor, byte[], int, int, int) @bci=8, line=116 (Compiled frame)
 - java.net.SocketInputStream.read(byte[], int, int, int) @bci=117, line=171 (Compiled frame)
 - java.net.SocketInputStream.read(byte[], int, int) @bci=11, line=141 (Compiled frame)
 - org.apache.http.impl.io.SessionInputBufferImpl.streamRead(byte[], int, int) @bci=16, line=139 (Compiled frame)
 - org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer() @bci=68, line=155 (Compiled frame)
 - org.apache.http.impl.io.SessionInputBufferImpl.readLine(org.apache.http.util.CharArrayBuffer) @bci=227, line=284 (Compiled frame)
 - org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(org.apache.http.io.SessionInputBuffer) @bci=16, line=140 (Compiled frame)
 - org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(org.apache.http.io.SessionInputBuffer) @bci=2, line=57 (Compiled frame)
 - org.apache.http.impl.io.AbstractMessageParser.parse() @bci=38, line=261 (Compiled frame)
 - org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader() @bci=8, line=165 (Compiled frame)
 - org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader() @bci=4, line=167 (Compiled frame)
 - org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(org.apache.http.HttpRequest, org.apache.http.HttpClientConnection, org.apache.http.protocol.HttpContext) @bci=41, line=272 (Compiled frame)
 - org.apache.http.protocol.HttpRequestExecutor.execute(org.apache.http.HttpRequest, org.apache.http.HttpClientConnection, org.apache.http.protocol.HttpContext) @bci=39, line=124 (Compiled frame)
 - org.apache.http.impl.execchain.MainClientExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware) @bci=714, line=271 (Compiled frame)
 - org.apache.http.impl.execchain.ProtocolExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware) @bci=447, line=184 (Compiled frame)
 - org.apache.http.impl.execchain.RetryExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware) @bci=39, line=88 (Compiled frame)
 - org.apache.http.impl.execchain.RedirectExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware) @bci=85, line=110 (Compiled frame)
 - org.apache.http.impl.client.InternalHttpClient.doExecute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext) @bci=168, line=184 (Compiled frame)
 - org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext) @bci=4, line=71 (Compiled frame)
 - org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext) @bci=4, line=55 (Compiled frame)
 - org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(org.apache.http.protocol.HttpContext, org.apache.http.client.methods.HttpUriRequest) @bci=10, line=143 (Compiled frame)
 - org.openqa.selenium.remote.internal.ApacheHttpClient.execute(org.openqa.selenium.remote.http.HttpRequest, boolean) @bci=178, line=89 (Compiled frame)
 - org.openqa.selenium.remote.HttpCommandExecutor.execute(org.openqa.selenium.remote.Command) @bci=119, line=133 (Compiled frame)
 - org.openqa.selenium.remote.RemoteWebDriver.execute(java.lang.String, java.util.Map) @bci=82, line=605 (Compiled frame)
 - org.openqa.selenium.remote.RemoteWebDriver.startSession(org.openqa.selenium.Capabilities, org.openqa.selenium.Capabilities) @bci=64, line=218 (Interpreted frame)
 - org.openqa.selenium.remote.RemoteWebDriver.<init>(org.openqa.selenium.remote.CommandExecutor, org.openqa.selenium.Capabilities, org.openqa.selenium.Capabilities) @bci=97, line=118 (Interpreted frame)
 - org.openqa.selenium.remote.RemoteWebDriver.<init>(java.net.URL, org.openqa.selenium.Capabilities) @bci=11, line=142 (Interpreted frame)
 - com.bc.task.browserdriver.ChromeBrowserDriver.initBrowser(com.bc.task.browserdriver.BrowserRequestParams) @bci=71, line=57 (Interpreted frame)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reporoduction scenario provided.
