### ISSUE TITLE
Safari 10.1.2 and Selenium 3 - issue org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!

### ISSUE THREAD

**Issue by kai00000** [SeleniumHQ/selenium#4428]
T E S T S
02:11:07 -------------------------------------------------------
02:11:07 Running com.sap.ui5.selenium.qunit.QUnitTest
02:11:07 Password:
02:11:08 Password:
02:11:08 Password:
02:11:29 Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.152 sec <<< FAILURE! - in com.sap.ui5.selenium.qunit.QUnitTest
02:11:29 initializationError(com.sap.ui5.selenium.qunit.QUnitTest)  Time elapsed: 0.003 sec  <<< ERROR!
02:11:29 org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
02:11:29 Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
02:11:29 System info: host: 'sofm33448710a.dhcp.sofl.sap.corp', ip: 'fe80:0:0:0:9a5a:ebff:fed1:667b%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_51'
02:11:29 Driver info: driver.version: SafariDriver
02:11:29 	at java.net.PlainSocketImpl.socketConnect(Native Method)
02:11:29 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
02:11:29 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
02:11:29 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
02:11:29 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
02:11:29 	at java.net.Socket.connect(Socket.java:589)
02:11:29 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
02:11:29 	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
02:11:29 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
02:11:29 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
02:11:29 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
02:11:29 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
02:11:29 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
02:11:29 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
02:11:29 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
02:11:29 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
02:11:29 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
02:11:29 	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
02:11:29 	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
02:11:29 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:343)
02:11:29 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
02:11:29 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
02:11:29 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
02:11:29 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
02:11:29 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
02:11:29 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
02:11:29 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
02:11:29 	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:60)
02:11:29 	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:51)
02:11:29 	at com.sap.ui5.selenium.utils.Browser$6.createLocal(Browser.java:181)
02:11:29 	at com.sap.ui5.selenium.utils.Browser.create(Browser.java:257)
02:11:29 	at com.sap.ui5.selenium.utils.WebDriverPool.getFreeDriver(WebDriverPool.java:117)
02:11:29 	at com.sap.ui5.selenium.qunit.QUnitTest.getFreeDriver(QUnitTest.java:288)
02:11:29 	at com.sap.ui5.selenium.qunit.QUnitTest.getFreeDriver(QUnitTest.java:273)
02:11:29 	at com.sap.ui5.selenium.qunit.QUnitTest.findTests(QUnitTest.java:432)
02:11:29 
02:11:29 
02:11:29 Results :
02:11:29 
02:11:29 Tests in error: 
02:11:29   QUnitTest.findTests:432->getFreeDriver:273->getFreeDriver:288 » WebDriver The ...
02:11:29 

Hello Colleagues,

Is anyone have idea how can we solve this?
I followed the procedure below and ran manually locally on the machine but it did not help..

Ensure that the Develop menu is available. It can be turned on by opening Safari preferences (Safari > Preferences in the menu bar), going to the Advanced tab, and ensuring that the Show Develop menu in menu bar checkbox is checked.
Enable Remote Automation in the Develop menu. This is toggled via Develop > Allow Remote Automation in the menu bar.
Authorize safaridriver to launch the webdriverd service which hosts the local web server. To permit this, run /usr/bin/safaridriver once manually and complete the authentication prompt.

**Comment by p0deje** [comment]
Cannot reproduce with Selenium server 3.5 and latest SafariDriver. Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by kai00000** [comment]
For this case the problem was that i was trying to run it remotely with ssh (Jenkins Job). 
But if i run it locally or not through ssh connection (it can be JNLP) it works.

**Comment by brunolm** [comment]
I have the same issue. When I run via SSH I get that the "Allow Remote Automation" is not enabled.

If I VNC into the machine and run from there it works.

Mac for some reason doesn't allow automation via SSH, Idk. I don't have a solution for this.
