### ISSUE TITLE
Please include a prefilled issue template link

### ISSUE THREAD

**Issue by sitsofe** [SeleniumHQ/selenium#443]
Description of the problem:
Briefly scanning through the recent issues that have been filed in the new Seleinum Github issue tracker shows a pattern of low quality issues which are being posted to the wrong place / lack necessary information. Perhaps a bug template link may raise the bar a little bit?

Steps to reproduce:
Go to https://github.com/SeleniumHQ/selenium/issues?q=is%3Aissue+is%3Aclosed .

Expected results:
Issues that have been filed to contain all the usual information, issues not contain "how do I?" requests.

Actual results:
Many "help me" issues, some issues lacking clear reproduction steps, missing version information etc.

Additional information:
Although it's crude perhaps a link to a prefilled report like
https://github.com/SeleniumHQ/selenium/issues/new?title=footitle&body=barbody
might help a little bit? (found via isaacs/github#99)

Version information:
Github issue tracker as of 11th April 2015.

**Comment by lukeis** [comment]
This is more of a github issue itself by not allowing an issue template akin to google code. 

This is not going to stop users from filing poor issues. The type of people who log crappy issue reports completely ignored the predefined template from google code and posted their issues anyways.

Do you have any suggestions where such a link would make sense? (Alas github does not allow us to customize the "new issue" button).

**Comment by andreastt** [comment]
However, by having [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md) in our repository, Github puts a link to it at the top when creating an issue or a pull request.  @sitsofe, do you think there are things we're missing in that document?

**Comment by sitsofe** [comment]
@lukeis:
If people willfully overrode the template on Google Code without good reason then I guess there's little hope here.

It's a shame that the "file new issue" link can't be customised. For now I think the only places a bug template link can go is into CONTRIBUTING.md and/or as a new heading in README.md.

@andreastt:
The only real comment I can make is that the document is so big that I can't even see to the end of the table of contents in my (laptop) browser window without scrolling. That document is invaluable for people making code contributions but I'm guessing many users are only going to be filing bugs and won't make it to the "Issue Contributions" ("is that to do with bug reports?") and even then you're still a link away from bug filing basics.

**Comment by andreastt** [comment]
@sitsofe: I've made a series of changes in d23f680..2beb20a that addresses some of your concerns.  If you have further concrete ideas, I'm happy to listen to those.

**Comment by lukeis** [comment]
I've also reached out to github support to request that they allow the 'New Issue' button to be customized, or provide an issue template in some manner.

Response I've gotten:
"I'd be happy to pass your feedback to the team to consider, but can't make any promises."  :)
