### ISSUE TITLE
GetScreenshot

### ISSUE THREAD

**Issue by sbryfcz** [SeleniumHQ/selenium#4431]
## Meta -
OS:  
Windows 10

Selenium Version:  
.Net PackageL Selenium WebDriver 3.4.0

Browser:  
Internet Explorer

Browser Version:  
Version: 11.1480.14393.0
Update Version: 11.0.44

## Expected Behavior -
Screenshot is taken of the browser's current viewport (without scrolling back to the top).

## Actual Behavior -
Before the screenshot is taken, the browser scrolls back to the top of the page and then the screenshot is taken. In Edge, Chrome, and Firefox, this is not the behavior. Those browsers take the screenshot of the current viewport without scrolling to the top.

## Steps to reproduce -
```C#
var driver = new InternetExplorerDriver();
driver.Manage().Window.Position = new Point(0, 0);
driver.Manage().Window.Size = new Size(1280, 800);

driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

// navigate to the base url
driver.Navigate().GoToUrl("http://www.engadget.com");

// just wait a bit for the page to fully load
Thread.Sleep(5000);

// scroll down 100 px
driver.ExecuteScript("window.scrollTo(0, 100)");

// take a screenshot
var screenshotDriver = driver as ITakesScreenshot;
Screenshot screenshot = screenshotDriver.GetScreenshot();
var capturedScreen = new Bitmap(new MemoryStream(screenshot.AsByteArray));

capturedScreen.Save("C:\\screenshot.png");
```

**Comment by KathiresanRamkumar95** [comment]
I also Have A doubt How am take full page screenshot in IE, Edge, Chrome and Safari browser?
Thanks!

**Comment by p0deje** [comment]
IEDriver has been significantly reworked recently, can you try and check if this error exists in 3.5?

**Comment by sbryfcz** [comment]
Looks like its fixed! Thanks a ton!
