### ISSUE TITLE
Selenium IDE does not work with Firefox version 55

### ISSUE THREAD

**Issue by AaronKlassenSSN** [SeleniumHQ/selenium#4435]
## Meta -
OS:  Windows 7

Selenium Version:  IDE

Browser:  Firefox

Browser Version:  55.0

**Comment by barancev** [comment]
Duplicate of #4406

**Comment by skmvali** [comment]
https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
