### ISSUE TITLE
Selenium Driver and OpenCV waitKey(0) Segfault

### ISSUE THREAD

**Issue by frederikbrinck** [SeleniumHQ/selenium#4439]
## Meta - Versions
OS:  macOS Sierra 10.12.5

Selenium Version:  3.4.3

Browser:  Firefox, version 55.0 (64-bit)

Browser Version:  55.0 (64-bit)

OpenCV Version: 3.2.0 

Python Version: 2.7.13

## Expected Behavior - OpenCV Show Image
I am running the following piece of code in OpenCV 3.2.0 to display an image.

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import cv2

cv2.namedWindow('window')
img = cv2.imread('my_image.png')
cv2.imshow('window', img)

cv2.waitKey(0)
```
This works fine. However, when I add in driver open and close with Selenium, I get a segfault.

The following code produces a segfault.

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import cv2

driver = webdriver.Firefox()
driver.close()

cv2.namedWindow('window')
img = cv2.imread('my_image.png')
cv2.imshow('window', img)

cv2.waitKey(0)
```

## Actual Behavior - Segfault

I get a segfault on `cv2.waitKey(0)`. In case I omit the `driver.close()` no segfault is thrown.

## Steps to reproduce

Run this code in python

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import cv2

driver = webdriver.Firefox()
driver.close()

cv2.namedWindow('window')
img = cv2.imread('my_image.png')
cv2.imshow('window', img)

cv2.waitKey(0)
```

**Comment by p0deje** [comment]
It doesn't look to be Selenium issue but rather OpenCV one. Is there anything that I miss?

**Comment by barancev** [comment]
Closing the issue, seems to be not related to Selenium, may be a Firefox-OpenCV collision.
