### ISSUE TITLE
driver.set_script_timout broken on firefox beta

### ISSUE THREAD

**Issue by cowlicks** [SeleniumHQ/selenium#4444]
## Meta -
OS:  Linux
Selenium Version:  3.4.2

Browser:  firefox 56.0b2 (beta)

## Expected Behavior -
`driver.set_script_timeout(n)` should work, 
## Actual Behavior -
it doesen't work
`selenium.common.exceptions.WebDriverException: Message: timeouts `
## Steps to reproduce -
```python
from selenium import webdriver
ffp = webdriver.FirefoxProfile()
driver = webdriver.Firefox(firefox_profile=ffp, firefox_binary='/path/to/firefox-56.0b2/firefox/firefox')
driver.set_script_timeout(10);
```

**Comment by barancev** [comment]
What version of geckodriver do you use?

**Comment by cowlicks** [comment]
@barancev  0.17.0

**Comment by barancev** [comment]
Please upgrade to 0.18 and retest

**Comment by cowlicks** [comment]
That works, but 0.18 breaks our firefox ESR's tests. But I suppose that is a separate issue.

**Comment by p0deje** [comment]
Guess this issue can be closed then.
