### ISSUE TITLE
Fails for integer parameters (Firefox)

### ISSUE THREAD

**Issue by iliakan** [SeleniumHQ/selenium#4445]
OS:  MacOS 10.12
Selenium Version: 3.5.0 
Browser: Firefox 52.3
Geckodriver: 0.18.0 (downloaded latest today)
Node.JS module selenium-webdirver: 3.5.0 (downloaded latest today)

I'm trying to set `browser.download.folderList` to `2`, but Selenium sends it as `2.0` to geckodriver, so that it crashes.

## Steps to reproduce 

Here's the code for Node.JS that requires only selenium-webdriver installed.
That might not be selenium-webdriver problem though, maybe it's a Java code issue.

```js
const SeleniumServer = require('selenium-webdriver/remote').SeleniumServer;
const webdriver = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');

const seleniumServer = new SeleniumServer('./vendor/selenium-server-standalone.jar', {
  args: ['-debug'],
  stdio: 'inherit'
});

seleniumServer.start();
const profile = new firefox.Profile();
profile.setPreference("browser.download.folderList", 2);

const options = new firefox.Options().setProfile(profile);

const driver = new webdriver.Builder()
  .usingServer(seleniumServer.address())
  .withCapabilities({
    browserName: 'firefox',
    name:        require('os').hostname + ': ' + new Date().toLocaleString()
  }).
  setFirefoxOptions(options).
  build();
```

From the debug output:
```
23:54:10.194 DEBUG - http-outgoing-0 >> "{"desiredCapabilities":{"browserName":"firefox","name":"function getHostname() { [native code] }: 2017-8-11 23:54:09","moz:firefoxOptions":{"prefs":{"browser.download.folderList":2.0}}}}"
```

You can see 2.0 here, so geckodriver dies.

It worked in older selenium, I upgraded it first time in half-year or like that, and got the regression.

**Comment by iliakan** [comment]
@barancev Please note that Node.JS actually passes integer to selenium. 

That's an excerpt from my larger app:
```
Accept: application/json; charset=utf-8
Content-Length: 362
Content-Type: application/json;charset=UTF-8
Host: 192.168.1.5:4444
Connection: close

{"desiredCapabilities":{"browserName":"firefox","name":"function getHostname() { [native code] }: 2017-8-14 14:35:30","moz:firefoxOptions":{"prefs":{"browser.download.manager.showWhenStarting":false,"browser.download.dir":"/js/payments/tmp","browser.download.folderList":2,"browser.helperApps.neverAsk.saveToDisk":"application/excel,application/octet-stream"}}}}
```

But Selenium passes 2.0 to geckodriver (Wrong!)

```
{"desiredCapabilities":{"browserName":"firefox","name":"function getHostname() { [native code] }: 2017-8-14 14:35:30","moz:firefoxOptions":{"prefs":{"browser.download.manager.showWhenStarting":false,"browser.download.dir":"/js/payments/tmp","browser.download.folderList":2.0,"browser.helperApps.neverAsk.saveToDisk":"application/excel,application/octet-stream"}}}}
```

**Comment by iliakan** [comment]
So that's probably a Java issue rather than Node.JS driver.

**Comment by shs96c** [comment]
Technically, this is a problem with remote ends not handling JS correctly --- there's no concept of "float" or "int", just "number".

https://github.com/google/gson/issues/1084

Having said that, things breaking is bad, so we need to put a fix of some sort into selenium

**Comment by barancev** [comment]
Version 3.5.2 released with this fix.

**Comment by iliakan** [comment]
Awesome.
