### ISSUE TITLE
Multithreading with same webdriver instance.

### ISSUE THREAD

**Issue by sahilkhan99** [SeleniumHQ/selenium#4446]
## Meta -
OS:  Windows 10

Selenium Version:  

Browser:  Internet Explorer

Browser Version:  IE11

## Expected Behavior -
I dont know if it is possible to do multi threading with selenium webdriver instance. Just a curious questions if anyone know answer or good article to help me.

Basic example with multithreading is entering email and password with two threads in parallel. Is it possible in IEWebdriver ?
I'm trying with the below code, but it always fails when the other thread is executing,
```
Action action1 = () =>
            {
              InputEmailAddresss();
            };

Action action2 = () =>
            {
              InputPassword();
            };
Parallel.Invoke(action1, action2);
```

## Actual Behavior -
Error out as 404 not found one of the element. Because it cannot run multiple threads at the same time.

## Steps to reproduce -
It is a basic question. It is easy to reproduce the problem with above lines of code and run tests.

Your help is really appreciated. Thank you in advance.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
