### ISSUE TITLE
Switching frame with WebElement throwing Compile time error

### ISSUE THREAD

**Issue by tbc-ats** [SeleniumHQ/selenium#4447]
Selenium Java WebDriver 3.5.0 
Eclipse Oxygen

Switching frame with WebElement. My issue is coming at compile time. Getting Error: "**The method frame(String) is ambitious for the type WebDriver.TargetLocator**"... My code is as below.

_public static void setFrame(By frameElement) {
		sDriver.switchTo().defaultContent();
		sDriver.switchTo().frame(sDriver.findElement(frameElement));
	}_

It was working perfectly fine with Selenium WebDriver 3.4.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/).

I can't reproduce the issue:
![image](https://user-images.githubusercontent.com/617090/29266986-61a81aa0-80ef-11e7-8101-fcf31a7d4cb4.png)

**Comment by tbc-ats** [comment]
Hi,

I have attached the screen shot of the error i am getting...i am also
sharing the java file which is having the error. I am using
"selenium-server-standalone-3.5.0.jar". This was working perfectly fine
with 3.4.0.

[image: Inline image 1]

**Comment by barancev** [comment]
I've downloaded your code, but I can't reproduce the issue:
![image](https://user-images.githubusercontent.com/617090/29308172-76dde38c-81ad-11e7-98b4-53bff98ed1aa.png)

driver.findElement(...) returns a WebElement object that can't be ambiguous with String. It seems to be an eclipse compiler issue, please report it to eclipse team.

**Comment by tbc-ats** [comment]
I tried on  2 different eclipse version, 2 different machine, but this happens only when we add selenium-server-standalone-3.5.0.jar.

**Comment by barancev** [comment]
I understand your pain, but you can see, there are three frame(...) methods that have various parameter types, and there is no ambiguity among them:
![image](https://user-images.githubusercontent.com/617090/29308848-fcd90118-81af-11e7-8a86-e96ca5f4d71e.png)

Try to compile yur project with Oracle Java compiler or OpenJDK, can you reproduce the issue with any other compiler than Eclipse?

**Comment by tbc-ats** [comment]
Found the culprit... I had another jar "java-client-5.0.0-beta8.jar" which was causing the error with 3.5.0. strangely it was working fine with 3.4.0....thanks for your help
