### ISSUE TITLE
Firefox is displaying as stopped working when we close Firefox using selenium

### ISSUE THREAD

**Issue by prasanna532** [SeleniumHQ/selenium#4448]
**Selenium version: 3.5.0**

**Firefox version: 55.0**

System.setProperty("webdriver.gecko.driver", "driver_path");
            FirefoxProfile geoDisabled = new FirefoxProfile();
            geoDisabled.setPreference("geo.enabled", true);
            geoDisabled.setPreference("geo.provider.use_corelocation", true);
            geoDisabled.setPreference("geo.prompt.testing", true);
            geoDisabled.setPreference("geo.prompt.testing.allow", true);
            DesiredCapabilities capabilities = DesiredCapabilities.firefox();
            capabilities.setCapability(FirefoxDriver.PROFILE, geoDisabled);
            driver = new FirefoxDriver(capabilities);

After closing the  Firefox it is displaying one window with **firefox is not working and check solution in online**

**Comment by barancev** [comment]
This is a browser issue, try a more recent browser version (dev edition or nightly)

**Comment by prasanna532** [comment]
![image](https://user-images.githubusercontent.com/25867821/29303943-f4418eb4-81ad-11e7-9b6c-2c70630a38da.png)
