### ISSUE TITLE
Custom Firefox Profile is written to disk twice 

### ISSUE THREAD

**Issue by h-arlt** [SeleniumHQ/selenium#4452]
## Meta -
OS:  Linux Mint 18.1 (Ubuntu Xenial)

Selenium Version: 3.4.0  

Browser:  Firefox

Browser Version:  45 ESR / 55b14 (64-bit)

## Expected Behavior -
Passed profile is written to disk only once.
## Actual Behavior -
Profile configured at FirefoxOptions instance used for instantiating FirefoxDriver is written twice.
## Steps to reproduce -
- take code below and fill in paths to your Firefox and Gecko Driver Service binaries
- set a breakpoint at `org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk()`
- run tests in debug session

```java
  @Test
  public void testFFProfileLegacy() {
        final FirefoxOptions opts = new FirefoxOptions();
        opts.setBinary("<PATH_TO_FIREFOX_ESR>");
        opts.setLegacy(true);
        
        
        final FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("my_test_bool", true);
        
        opts.setProfile(profile);

        final WebDriver wd = new FirefoxDriver(opts);
        wd.get("http://www.seleniumhq.org/");

   }
  
  @Test
  public void testFFProfileMarionette() {
        System.setProperty(GeckoDriverService.GECKO_DRIVER_EXE_PROPERTY, "<PATH_TO_GECKODRIVER_SERVER>");
        final FirefoxOptions opts = new FirefoxOptions();
        opts.setBinary("<PATH_TO_FIREFOX>");
        opts.setLegacy(false);
        
        
        final FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("my_test_bool", true);
        
        opts.setProfile(profile);

        final WebDriver wd = new FirefoxDriver(opts);
        wd.get("http://www.seleniumhq.org/");

  }

```

**Comment by barancev** [comment]
Optimization issue, it does not hurt fuctionality.

Capabilities contains profile twice (under "profile" and "firefox_profile" keys). Yes, we convert them twice, and we pass extra data over the wire. It's suboptimal. But we're not going to fix it in legacy driver.

Fortunately, geckodriver allows to pass options in more compact form that resolves this issue:
```
final FirefoxOptions opts = new FirefoxOptions();
opts.addPreference("my_test_bool", true);
WebDriver wd = new FirefoxDriver(opts);
```

**Comment by h-arlt** [comment]
This is not acceptable. Performing such a kind of heavy I/O should be avoided whenever possible. This is especially true on Firefox startup as this unnecessarily increases startup time to several seconds.

Your workaround is not feasible for us as we need to configure preferences and extensions to be used.

**Comment by barancev** [comment]
There will be added a new method to install extensions, see #4215, that will be more effective than passing the whole profile too.

Anyway, I'll reopen the issue, it's a good target if someone wants to create a PR.

**Comment by h-arlt** [comment]
Roger that. Thanks Alexei!

**Comment by shs96c** [comment]
We had a look at this at SeleniumConf, and tried to implement this. Approaches taken:

* Cache the output of "layoutDisk" and remove cache on any state change. This caused the profile to pollute the temp directory, which has been a source of a number of bugs before. We don't want to break these tests.
* Considered an identity cache within the json encoders to ensure that `toJson` is only called once per object. However, profiles tend to be large, and there's some concern about running out of memory in a hurry. Thus, we discarded this approach.
* Considered implementing `toJson` in `FirefoxOptions`. This has the same problem as above, but now with added JSON.

Leaving open in the hope that someone better than me comes along to fix it :)

**Comment by diemol** [comment]
A related issue (#4215)  was closed, where all bindings implemented it.
