### ISSUE TITLE
Unable to connect to chromedriver with 3.5.0

### ISSUE THREAD

**Issue by boris-petrov** [SeleniumHQ/selenium#4453]
Since I updated to Selenium 3.5.0 (using Ruby and Capybara), the following message is displayed:

```
Selenium::WebDriver::Error::WebDriverError:                                    
  unable to connect to chromedriver 127.0.0.1:9515
```

Everything works fine with Selenium 3.4.3 (and 3.4.4 but it has another [issue](https://github.com/SeleniumHQ/selenium/issues/4311))

## Meta -
OS:  Linux
Selenium Version:  3.5.0
Browser:  Chromium 60.0.3112.90
ChromeDriver version: 2.31.488763

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by boris-petrov** [comment]
I'm not sure what more do you need. There is no test case - Capybara/Selenium fails to connect to the ChromeDriver on start (the exact code is `Capybara.current_session.current_window.resize_to(1920, 1060)`). Happens only with the latest Selenium. What more could I give you?

**Comment by lmtierney** [comment]
You could start by sample code, using only selenium. We do not do support for Capybara. I've just tried starting Chromium with Selenium Ruby 3.5, Chromium 60.0.3112.78, and Chromedriver 2.31.488763 and it's fine.

**Comment by p0deje** [comment]
I also tried the following code right now:

```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:chrome)
driver.manage.window.resize_to 100, 100
```

It worked perfectly and resized window correctly.

ChromeDriver 2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b)
Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by boris-petrov** [comment]
Ok, I'll try creating a short reproduction then. I'll post it here when I'm done. Also, note we're using JRuby.

**Comment by boris-petrov** [comment]
Ok, so the problem happens only when using JRuby. Have a directory with:

Gemfile
```
source "https://rubygems.org"

gem "selenium-webdriver"
gem "rspec"
```

specs/foo_spec.rb
```ruby
require_relative './spec_helper'
```

specs/spec_helper.rb
```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:chrome)
driver.manage.window.resize_to 100, 100
```

And run:

```sh
sudo jruby -S gem install bundler
sudo jgem install bundler
jruby -S bundle install
jruby -S rspec specs
```

And you will see it fail with the error I've given in the first post. Running a `rspec specs` instead works fine.

**Comment by p0deje** [comment]
Thank you for additional report. I can reproduce the problem now.

This seems to be something related to how IO is handled in ChildProcess gem. I'll need to investigate and get back.

**Comment by p0deje** [comment]
Once CI shows we're good to release, I'll make a point 3.5.1 release of gem.

Thank you again for a bug report.

**Comment by boris-petrov** [comment]
@p0deje - No problem, thanks for the quick fix! Do you think this behavior of JRuby is wrong? If that's a bug, perhaps you/I could log an issue with them?

**Comment by p0deje** [comment]
I'm not sure. It seems like GeckoDriver and ChromeDriver need some real I/O in order to work correctly, but not all processes require this.

**Comment by p0deje** [comment]
3.5.1 is available on Rubygems, give it a try.

**Comment by boris-petrov** [comment]
Works like a charm, thank you!
