### ISSUE TITLE
Safari isDisplayed returns false

### ISSUE THREAD

**Issue by ivanovstepan** [SeleniumHQ/selenium#4456]
## Meta -
OS:  
macOS Sierra 10.12.6
Selenium Version:  
3.4.0
Browser:  
Safari

Browser Version:  
10.1.2

**use** Safari Technology Preview release 37

## Expected Behavior -
element.isDisplayed() =true
## Actual Behavior -
element.isDisplayed() =false
## Steps to reproduce -
1.Go to https://google.com
2. use ((JavascriptExecutor) driver).executeScript(script.toString(), element.getElement()) 
	script = "arguments[0].style.overflow='hidden'"
	element = element with xpath = '//div[@title='Google']/div'
3. driver.findElement(org.openqa.selenium.By.xpath("//div[@title='Google']/div")).isDisplayed() returns false

**Comment by barancev** [comment]
Please report this issue to Apple

**Comment by MrDefinite** [comment]
@ivanovstepan Has this issue been resolved?

**Comment by yvasylenko** [comment]
Hi, 
@barancev could you please provide more details, why should this issue be reported to Apple?
What should I specify to show them that this issue relates to Safari browser, not safari-driver?

I've got the same issue for Safari 11.0.3, Selenium 3.8.1 and safari-driver 3.9.0
I've checked the location of the element and both coordinates have positive values.
Please let me know, if there are any updates on this.

**Comment by barancev** [comment]
@yvasylenko Because Selenium just sends a request to safaridriver (implemented by Apple) that does all the real job.

**Comment by yvasylenko** [comment]
Thanks for the explanation, I've realized my mistake regarding safaridriver.

**Comment by jorgejar** [comment]
> Thanks for the explanation, I've realized my mistake regarding safaridriver.

Im seeing issues with the driver as well, curious to know what happened in your situation

**Comment by anoop52172** [comment]
Facing issue with using java jar 3.13.0 elements 'Displayed' is returning false where as it return true for Chrome and IE Browser

**Comment by anoop52172** [comment]
Have not found any work around for this issue, it seems the behaviour of safari driver which now is maintained with safari browser
