### ISSUE TITLE
Is selenuim gevent-compatible?

### ISSUE THREAD

**Issue by gukoff** [SeleniumHQ/selenium#4457]
Can one use `gevent.monkey.patch_all()` before `import selenium` in order to make it asynchronous?

It seems to work, although there is nothing about it in the docs. I'm not sure that I can rely on it.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
