### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by raffam** [SeleniumHQ/selenium#4458]
## Meta -
OS:  

Selenium Version:  3.5.3

Browser:  

Browser Version:  

## Steps to reproduce -

Can I RESPECTFULLY say that I find the [Selenium official Python documentation](https://seleniumhq.github.io/selenium/docs/api/py/api.html) incomplete?

For example, the documentation for `selenium.webdriver.remote.webelement` fails to point out that `find_elements*` method always return a list (eventually empty), while `find_element*` return the element directly or raises a `selenium.common.exceptions.NoSuchElementException`

The `switch_to` documentation of `selenium.webdriver.remote.webdriver.WebDriver` is non-existent (literally)
There is a documentation for `switch_to_active_element()` and the like which says that the methods are deprecated and you should use `driver.switch_to.active_element` instead. But what does the `switch_to` methods do at all? What does it mean to switch to the default element? Or to an alert? Or to a default content?

The example of `selenium.webdriver.remote.webelement.WebElement` 's  `get_property()` function is wrong. It says

> # Check if the "active" CSS class is applied to an element.
> text_length = target_element.get_property("text_length")

At least the comment is wrong, which seems to have been copy-pasted from the `get_attribute(name)` function

> # Check if the "active" CSS class is applied to an element.
> is_active = "active" in target_element.get_attribute("class")

Maybe it's just me, or maybe I have found the wrong link from the documentation (the link is on pypi page of selenium). Selenium is a great piece of software, but I think it would be event better if the documentation was better

**Comment by luke-hill** [comment]
There is an active effort to rebuild the docs from scratch on a diff repo here. Feel free to contribute I'm sure the devs would welcome your suggestions

The website as it stands is here: https://seleniumhq.github.io/docs/

**Comment by raffam** [comment]
In the meantime, what is [http://seleniumhq.github.io/selenium/docs/api/py/#](this) ?

**Comment by raffam** [comment]
@luke-hill thanks for the link.
Your link does not include API documentation, right?
Is your website related to [this](https://github.com/baijum/selenium-python) or there are actually two efforts to rebuild the docs?

**Comment by manoj9788** [comment]
@raffam the link that Luke provided is the project to rewrite the docs - your patches should go into the python doc-strings as @lmtierney mentioned. Browse the source..

**Comment by raffam** [comment]
Another thing to document would be the logger. See [this](https://stackoverflow.com/questions/9226519/turning-off-logging-in-selenium-from-python) StackOverflow discussion

**Comment by manoj9788** [comment]
@raffam Feel free to send in a PR

**Comment by santiycr** [comment]
PR sent: https://github.com/SeleniumHQ/selenium/pull/5042

**Comment by mmerrell** [comment]
GREAT to see you Santi!
MM
