### ISSUE TITLE
selenium-server-standalone-2.45.0.jar server hanging at step Started org.openqa.jetty.Server

### ISSUE THREAD

**Issue by anithairene** [SeleniumHQ/selenium#446]
I downloaded the latest selenium server onto my Mac OS X Yosemite 10.10.
Selenium server ->selenium-server-standalone-2.45.0.jar  from http://www.seleniumhq.org/download/

On the terminal I typed "java -jar selenium-server-standalone-2.45.0.jar".
I get the below messages on my terminal window and then it hangs infinitely.

$ java -jar selenium-server-standalone-2.45.0.jar 
13:46:41.664 INFO - Launching a standalone server
13:46:41.693 INFO - Java: Oracle Corporation 25.40-b25
13:46:41.693 INFO - OS: Mac OS X 10.10 x86_64
13:46:41.701 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
13:46:41.750 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
13:46:41.784 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
13:46:41.785 INFO - Version Jetty/5.1.x
13:46:41.786 INFO - Started HttpContext[/selenium-server,/selenium-server]
13:46:41.802 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@7cf10a6f
13:46:41.803 INFO - Started HttpContext[/wd,/wd]
13:46:41.803 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
13:46:41.803 INFO - Started HttpContext[/,/]
13:46:41.805 INFO - Started SocketListener on 0.0.0.0:4444
13:46:41.805 INFO - Started org.openqa.jetty.jetty.Server@49097b5d

![selenium server hanging](https://cloud.githubusercontent.com/assets/11924932/7115980/8bb13a8a-e1e5-11e4-9103-9c799535b45e.jpg)

**Comment by anithairene** [comment]
Note I have java installed

$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by lukeis** [comment]
when you say hanging and infintely, do you mean the output stops and nothing else happens? or that you get the messages repeatedly?

The server 'starting' and sitting there doing nothing (waiting for requests) is expected and you should be reaching out to the Selenium-users mailing list for support on understanding how to use selenium. Or read our documentation at www.seleniumhq.org

**Comment by anithairene** [comment]
@lukeis, thanks. it was going in a loop. I have killed and started a new session and it doesnt seem to be happening now.
