### ISSUE TITLE
No Selenium WebDriver 3.5.0 for Java available in Maven?

### ISSUE THREAD

**Issue by goodbomb** [SeleniumHQ/selenium#4464]
Hi,

The .NET and Python package managers seem to already have v3.5.x available:
https://www.nuget.org/packages/Selenium.WebDriver/
https://pypi.python.org/pypi/selenium

However, Maven's latest is still 3.4.0. When will 3.5.x be available?
https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java

Thanks!

**Comment by lmtierney** [comment]
There is a dependency issue that is being ironed out and it will be pushed out as soon as it is resolved.

As this is a question and not an issue, in the future please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by barancev** [comment]
FYI: version 3.5.1 is available in maven central
