### ISSUE TITLE
import org.openqa.selenium.htmlunit.HtmlUnitDriver; can not be resolved

### ISSUE THREAD

**Issue by beshoo** [SeleniumHQ/selenium#4467]
Dear all . i am using  eclipse , i did install Maven in  eclipse.
i did rebelde Mavin index.
 
My pom.xml
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.like</groupId>
  <artifactId>instagramLiker</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>
  	<dependency>
  		<groupId>org.seleniumhq.selenium</groupId>
  		<artifactId>htmlunit-driver</artifactId>
  		<version>2.27</version>
  	</dependency>
  </dependencies>
</project>
```

and here is my IDE
http://i.imgur.com/kUyePPn.png

IDE report:
import org.openqa.selenium.htmlunit.HtmlUnitDriver; can not be resolved. WHY?
I am very new to Java world and i want to use htmlUnit , what i am doing wrong ?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
