### ISSUE TITLE
Flaky InvalidSelectorException caused by Error: Permission denied

### ISSUE THREAD

**Issue by 1aleksandrmd1** [SeleniumHQ/selenium#4469]
## Meta -
OS: Window 7
Selenium Version: 2.53.0
Browser: Internet Explorer 11
Драйвер: IEDriverServer_Win32_3.4.0, 64 бит. драйвер не использую из-за медленной работы
Browser Version:  
Версия: 11.0.9600.18738 (64-bit)
Версия обновления: 11.0.44

## Expected Behavior - Отсутствие плавающей ошибки InvalidSelectorException. Правильная интерпретация ошибки,  InvalidSelectorException не должна быть плавающей, если поломанный xpath, либо он возвращает не WebElement трудно ожидать, что он станет рабочим, в данном случае ошибка плавающая и возникает на разных элементах в разное время. 
Если  элемент не найден должна выбрасываться NoSuchElementException, если устарел StaleElementReferenceException, но не как не  InvalidSelectorException, которая пропадает при sleep(3000). 

## Actual Behavior - возникает плавающая ошибка InvalidSelectorException на разных элемента, в разный момент времени. Частный случай:
org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression .//input[@value='Очистить'] because of the following error:
Error: Разрешение отклонено (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62 milliseconds
For documentation on this error, please visit: http://seleniumhq.or..._exception.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'DF3-131016-NE03', ip: '10.80.16.134', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver

## Steps to reproduce - В примере видно, что локатор корректный  .//input[@value='Очистить']. 
 Элемент на странице существует, более того driver().getPageSource() возвращает во время ошибки:  
`...
<TD>
<INPUT class=btn onclick="getSubmit('dcForm', 'clear')" type=button value=Очистить> 
</TD>
...`
При явном ожидании элемента, периодически получаю InvalidSelectorException, NoSuchElementException в зависимости от ожидания
 
Попробовал реализовать самостоятельное ожидание 
`public WebElement findElementTo(By xpath, int timout){    
            long deadLine = DateManager.getCurrentTimestamp() + (timout*1000);
                while(deadLine > DateManager.getCurrentTimestamp()){
                        try{
                               WebElement WebElement= find(xpath);
                               return WebElement;
                        }catch(Exception e){
                               LOG.info("Ошибкак при получении элемента\n"+Init.getWebDriver().getPageSource()+"\n"+e);
                        }
        }       
                WebElement WebElement= find(xpath);
                return WebElement;             
        }

        private WebElement find(By xpath) throws InvalidSelectorException{     
                WebElement WebElement = Init.getWebDriver().findElement(xpath);        
            if(WebElement.isDisplayed()){
                return WebElement;
            }
            throw new org.openqa.selenium.ElementNotVisibleException("Элемент не виден. 
        Xpath="+xpath+"\n\n\n");
        } `
Соответственно постоянно идет обращение к получению элемента и в течении 10 мин я могу получать ошибку InvalidSelectorException. Замечу это не регулярная ошибка, она периодически возникает на разных элементах. 
На странице используются AJAX запросы. 
Как решение проблемы, делаю такие грабли:
`public void waitForJQueryLoad(long timeout) { 
                 WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), timeout);
                wait.until(new ExpectedCondition<Boolean>(){ 
                         @Override
                        public Boolean apply(WebDriver driver){
                               Boolean active = false;
                               JavascriptExecutor js = null;
                               try{
                                       js = ((JavascriptExecutor)driver);
                                       active = (Boolean)js.executeScript("return $j.active == 0");
                               }catch(WebDriverException e){
                                       LOG.info("Ошибка драйвера:\n"+e);
                               }
                               LOG.info("$.active="+active);
                               return active; 
                        }
                });
                 try {
                        //Таймаут необходим, для отрисовки элементов DOM, после JQuery запросов.
                        Thread.sleep(250);
                } catch (InterruptedException e) {
                        // TODO Автоматически созданный блок catch
                        e.printStackTrace();
                }`
То есть дожидаюсь что бы все AJAX запросы были выполнены и жду построения ДОМ в течении 0,25 сек
 
Я не в курсе как отрабатывает дальше цепочка, селениум - драйвер IE - браузер IE. Но из опыта прихожу к выводам:
1) Не правильно интерпретируется ошибка InvalidSelectorException - она же означает, что xpath не валидный, либо возвращается не WebElement, а текст к примеру
в нашем случае тут явно WebElement. К тому же ошибка плавающая, это говорит, что локатор валидный. Более того обычный sleep решает проблему.
2) Второе странное поведение, если  предположить, что ДОМ не успел до строиться, например странно (value=Очистить - почему то без кавычек), но тогда почему при последующих запросах, получения того же элемента WebElement WebElement= find(xpath);, ДОМ не перестраивается для драйвера? То есть если в текущем тесте получили  InvalidSelectorException, то она так и появляется, пока таймаут не закончится. (Приложение отрабатывает корректно и совершенно точно элементы подгружается до окончания таймаута)
3) Думаю проблема заключается в драйвере IE, возможно из-за того, что используется драйвер 32 битный, но пока не будет исправлена длительная работа 64 битного драйвера, нет возможности переходить на него.
Хотелось бы понять чем характеризуется такое странно поведение в тестах.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/), code talks better that words.

And please use English for narratives :)

**Comment by 1aleksandrmd1** [comment]
reproducible test case. Call - clickButtonTest() 
html
`<table class="tableborder" style="text-align:right; padding-top:10px; border: 0;" >
        <tr>
            <td>
            <input type="button" class="btn" onclick="getSubmit('dcForm', 'clear')" value="Очистить"/>
            </td>           
        </tr>
    </table>
`
code
`public void clickButtonTest() { 
                WebElement webElement = findElement(By.xpath(".//input[@value='Очистить']"));
                clickButton(webElement);
        }

        public void clickButton(WebElement webElement){        
                elementToBeClick(webElement);
                Actions actions = new Actions(Init.getWebDriver());    
                actions.moveToElement(webElement).click().build().perform();
        }
        public WebElement findElement(By path, int timout) {
                presenceOfElement(path, timout);
                visibilityOfElement(path, timout);     
                WebElement element = Init.getWebDriver().findElement(path);
                return element;
        }

                public void visibilityOfElement (By xpath, int timeout) {
                WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), timeout);
             try{ 
                //wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(xpath));
                wait.until(ExpectedConditions.presenceOfElementLocated(xpath));
                return;
             }catch (TimeoutException e){
                 throw new org.openqa.selenium.TimeoutException("Элемент не найден в DOM с локатором path = "+xpath+"\n\n\n"+e);    
             }catch (NoSuchElementException e){        
                 throw new org.openqa.selenium.NoSuchElementException("Элемент не найден в DOM с локатором path = "+xpath+"\n\n\n"+e);    
     }catch (StaleElementReferenceException e){
                 throw new org.openqa.selenium.StaleElementReferenceException("Элемент не найден в DOM с локатором path = "+xpath+"\n\n\n"+e);
             }
        }
public void visibilityOfElement(By xpath, int timeout) {
                  WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), timeout);
                    try{ 
                        wait.until(ExpectedConditions.visibilityOfElementLocated(xpath));
                        return;
                    }catch (TimeoutException e){
                        throw new org.openqa.selenium.TimeoutException("Элемент не найден с локатором path = "+xpath+"\n\n\n"+e);    
                    }catch (NoSuchElementException e){
                        throw new org.openqa.selenium.NoSuchElementException("Элемент не найден с локатором path = "+xpath+"\n\n\n"+e);    
                   }catch (StaleElementReferenceException e){
                        throw new org.openqa.selenium.StaleElementReferenceException("Элемент не найден с локатором path = "+xpath+"\n\n\n"+e);
                   }
        }
public void elementToBeClick(WebElement webelement, int timeout) {
                WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), timeout);
             try{ 
                wait.until(ExpectedConditions.elementToBeClickable(webelement));
                return;
             }catch (TimeoutException e){
                 throw new org.openqa.selenium.TimeoutException("Элемент не найден в DOM с локатором path = "+webelement.toString()+"\n\n\n"+e);   
             }catch (NoSuchElementException e){        
                 throw new org.openqa.selenium.NoSuchElementException("Элемент не найден в DOM с локатором path = "+webelement.toString()+"\n\n\n"+e);  
             }catch (StaleElementReferenceException e){
                throw new org.openqa.selenium.StaleElementReferenceException("Элемент не найден в DOM с локатором path = "+webelement.toString()+"\n\n\n"+e);
             }
        }
`
Not regular error
org.openqa.selenium.InvalidSelectorException: Unable to locate an element with the xpath expression .//input[@value='Очистить'] because of the following error:
Error: Разрешение отклонено (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62 milliseconds
For documentation on this error, please visit: http://seleniumhq.or..._exception.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'DF3-131016-NE03', ip: '10.80.16.134', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver

Key phrases: Error: Permission denied. 
Not regular error. Why?
Made settings
https://leaptest.com/support/knowledgebase/configuration-of-ie-for-using-selenium-web-blocks
 
driver.getPageSource()

`
<TR>
<TD><INPUT class=btn onclick="getSubmit('dcForm', 'clear')" type=button value=Очистить> </TD></TR>
`

**Comment by 1aleksandrmd1** [comment]
<TR>
<TD><INPUT class=btn onclick="getSubmit('dcForm', 'clear')" type=button value=Очистить> </TD></TR>

**Comment by 1aleksandrmd1** [comment]
> 
<TR>
<TD><INPUT class=btn onclick="getSubmit('dcForm', 'clear')" type=button value=Очистить> </TD></TR>

**Comment by barancev** [comment]
https://gist.github.com/barancev/2189190e0f3bb402e4d56d8627eed970

I run this test case (50 iterations) on IE 11, WIn7, using IEDriverServer 3.5 and 3.4, client libraries 3.5 and 2.53.1 -- not a single failure.

Try to use this sample, can you reproduce the issue?

If you can -- it seems to be local IE security configuration issue.

If you can't -- it must be related to more complicated page structure, and we still need a reproduction case.

**Comment by 1aleksandrmd1** [comment]
The error is reproduced.
The page is more complicated, there are AJAX requests.
The subsystem uses jquery, js, struts.
IE 11 works in compatibility mode IE8
A security problem is possible. I set a minimum security. Did not help.
How would receive stactrace information server failure?

**Comment by 1aleksandrmd1** [comment]
Sorry for my English)

**Comment by barancev** [comment]
I want to confirm that you are able to reproduce the error on this sample:
https://gist.github.com/barancev/2189190e0f3bb402e4d56d8627eed970
Right?

**Comment by 1aleksandrmd1** [comment]
Unfortunately there is no access to the Internet. 
Testing is conducted on a local network.
The application is commercial. External access is absent.
The executable code corresponds to the private element.
The application you are testing does not match - https://jsbin.com/hezugubopa/1/edit?html,output
A testable application is much more complicated.
It is unlikely that an error will occur in this example - https://jsbin.com/hezugubopa/1/edit?html,output
The problem is eliminated, such code
`public void waitForJQueryLoad(long timeout) { 
                 WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), timeout);
                wait.until(new ExpectedCondition<Boolean>(){ 
                         @Override
                        public Boolean apply(WebDriver driver){
                               Boolean active = false;
                               JavascriptExecutor js = null;
                               try{
                                       js = ((JavascriptExecutor)driver);
                                       active = (Boolean)js.executeScript("return $j.active == 0");
                               }catch(WebDriverException e){
                                       LOG.info("Ошибка драйвера:\n"+e);
                               }
                               LOG.info("$.active="+active);
                               return active; 
                        }
                });
                 try {
                        //Таймаут необходим, для отрисовки элементов DOM после JQuery запросов.
                        Thread.sleep(250);
                } catch (InterruptedException e) {
                        // TODO Автоматически созданный блок catch
                        e.printStackTrace();
                }
        }`

**Comment by barancev** [comment]
I'm sorry to say that, but without a sample that allows to reproduce the issue we hardly can help :(

**Comment by 1aleksandrmd1** [comment]
Good afternoon! |  
Problem solved.
The error occurred when processing WebDriverException.
True error:
WebDriverException: error determining if element is displayed
NullPointException

They appeared when the element attributes were received. 
Decision
`WebDriverWait wait = new WebDriverWait(Init.getWebDriver(), Init.getTimeOutInSeconds());
                wait.until(new ExpectedCondition<Boolean>(){ 
                         @Override
                        public Boolean apply(WebDriver driver){       
                               JavascriptExecutor js = ((JavascriptExecutor)driver);
                             Boolean active = (Boolean)js.executeScript("return document.readyState == 'complete'");
                               return active; 
                        }
                });
`
I thought the driver is automatically waiting for the page to refresh.
That is, performs document.readyState == 'complete'

**Comment by barancev** [comment]
1) The last comment looks totally unrelated to the original post.
2) executeScript does not wait for anything, it can be executed at any moment, and sometimes it can be unsuccessful (e.g if the page is refreshing, as you said), it's legit behaviour and you should be ready to handle such outcome.

**Comment by 1aleksandrmd1** [comment]
I'll try to explain the relationship.
page contains: FORM submit

`private WebElement find(By xpath) throws InvalidSelectorException{     
            WebElement WebElement = Init.getWebDriver().findElement(xpath);        
        if(WebElement.isDisplayed()){ // floating error: NullPointException, WebDriverException: error determining if element is displayed
            return WebElement;
        }
        throw new org.openqa.selenium.ElementNotVisibleException("Элемент не виден. 
    Xpath="+xpath+"\n\n\n");
    } `
`
next
if it is caught
`
try{
WebElement element = find(xpath);
}catch(NullPointException, WebDriverException){...
}
`
when determining the following elements: 
InvalidSelectorException on Init.getWebDriver().findElement(xpath);  
Error: Разрешение отклонено (WARNING: The server did not provide any stacktrace information)

why? I do not know. 
driver code is not available.
decision:

before   WebElement WebElement = Init.getWebDriver().findElement(xpath);     
Check that the page is loaded - document.readyState == 'complete'
here is not AJAX. page is loaded.

my problem is completely solved.
I shared my experience with the improvement of work IEDriver

**Comment by barancev** [comment]
From this explanation I'd make a conclusion that InvalidSelectorException with "Error: Permission denied" message can be thown by findElement operation called when the current page is reloading.

It's quite possible and it can be considered as legit behavior because InvalidSelectorException is a subclass of NoSuchElementException.

Thank you for the investigation! Closing the issue as resolved.
