### ISSUE TITLE
Multiple Browser Opening At Same Time instead of serial execution..... 

### ISSUE THREAD

**Issue by vaibhav44** [SeleniumHQ/selenium#447]
As per my requirement I am using Selenium Grid v2.44 for automation.

-->I have created a Driver class where I have defined a method which contains all grid needed info and returns Webdriver driver.

->In all my Java prog I am using this Driver to instantiate driver .

-->The problem which I am facing is that, Suppose if I have 5 Test classes and I am executing it through testng xml, its first opening 5 Browsers and then execute each class one by one.

I am unable to attach a text file so Please find below Driver class and A Java prog which explains the way I'm calling the Driver class.

Any help is appreciated.

Thanks

Driver Class :
package com;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.Platform;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class Driver {
	
	public static WebDriver configureDriver() throws MalformedURLException {
		
		 String nodeURL = "http://ip:5555/wd/hub";
		
		DesiredCapabilities dr = DesiredCapabilities.firefox();
	 
		dr.setBrowserName("firefox");
	 
		dr.setPlatform(Platform.WINDOWS);
		
		WebDriver rmtDriver = new RemoteWebDriver(new URL(nodeURL), dr);
	 
		rmtDriver.manage().window().maximize();
		
		return rmtDriver;
	
	 }
	 
}

Test Java Prog :
 package com;

import java.io.IOException;
import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.log4j.Logger;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.SkipException;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class Test {
	
	
	public static WebDriver driver;
	
	
	public SPM_Access_Control() throws IOException {
		
		driver = Driver.configureDriver();
		
		
	}
	
	/*
	 * Check for Run-Type Match in configureBeforeClass 
	 */
	
	@BeforeClass
	
	@Parameters({ "runType","Env" })
	
	public static void configureBeforeClass(String run,String env) throws InvalidFormatException, IOException, InterruptedException{
		
		System.out.println("Before Class Execution");
	}
	
	@Test
	
	public void test1() throws IOException, InterruptedException{
				
		
	}	
		
		
	
	
	
	@AfterClass
	
	public void screenShot() throws IOException {
		
		System.out.println("Close Browser Method Being Called");
		
			driver.quit();
		 
	} 
	
	
}

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
