### ISSUE TITLE
Assembly error using Edge Driver

### ISSUE THREAD

**Issue by BrianVBaker** [SeleniumHQ/selenium#4470]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

EdgeHTML Version:

## Expected Behavior -
Edge driver should launch the Edge browser

## Actual Behavior -
$exception	{"Could not load type 'OpenQA.Selenium.Edge.EdgeDriver' from assembly 'WebDriver, Version=2.45.0.0, Culture=neutral, PublicKeyToken=null'.":"OpenQA.Selenium.Edge.EdgeDriver"}	System.TypeLoadException

It indicates there is a missing type from the Selenium Webdriver bindings

**Comment by hazmeister** [comment]
@BrianVBaker you're using a really old version of Selenium there- I'm pretty sure Edge existed when 2.45 was released.  Try a new set of bindings (2.53. or 3.5) and you should see some improvements.

**Comment by BrianVBaker** [comment]
Thanks Hazmeister.
One of the hazards of using NuGet in Visual Studio is making sure you only have what you need.  I actually had 2 versions of Selenium.WebDriver in my solution 3.5.1 and 2.46.  So I cleared out all references to Selenium and just re-added the 3 NuGet references I needed.

Selenium.Support
Selenium.WebDriver
Selenium.WebDriverBackedSelenium

From Microsoft MicrosoftWebDriver.exe copied into project root and set to 'Always Copy'  when building.
