### ISSUE TITLE
@FindAll Annotation searches for all locator infos

### ISSUE THREAD

**Issue by samnit** [SeleniumHQ/selenium#4471]
OS:  Windows 10
Selenium Version:  Selenium 3.4

@FINDALL annotation is supposed to match at least one of the given criteria.
I have following OR:
URL for WebPage : http://store.demoqa.com/
WebElement : -
@FINDALL ({
@findby(xpath = "//input[@name='s']"),
@findby(xpath = "//a[contains(.,'Magic Mouse')]")
})
public WebElement Header__txtSearch;

I am trying to verify element on page with multiple locators i.e if one fails other might return true.

But when I give the first one as Correct and second one as Incorrect , then it still returns true that element is found but it goes onto the second choice as well to find that element and waits for ObjectTimeout. **It should immediately return true after finding first match.**

**Comment by kumar-nitish** [comment]
No, its not supposed to do that. It will return list of all elements that matches any of the specified locator.

You could refer to documentation https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/FindAll.html.

**Comment by thomhurst** [comment]
xpath = " //input[@name='s']|//a[contains(.,'Magic Mouse')] "

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

**Comment by samnit** [comment]
@kumar-nitish can u tell a workaround for the same ? ?
@thomhurst I already know about this approach I need to use different type of locaters like CSS,ID and XPath together

**Comment by barancev** [comment]
I think this is a legit performance issue, there is no reason to timeout on the second locator if an element can be found by the first one. This issue is a good target for a PR.

**Comment by kumar-nitish** [comment]
@samnit  ```@FindAll``` is not the right solution for this problem, because as it's name says FindAll, so it will find all elements with specified locators. ( See below snapshot for internal details). 

![image](https://user-images.githubusercontent.com/3117614/29427873-d2bf4bd0-83a8-11e7-9c4e-c846ef022193.png)


##### Suggested Solutions
1. If you need to use this functionality a lot, then you can create your own annotation say ( ```@FindAny ```), to return as soon as you find an element.
1. Solution suggested by @thomhurst 
1. Instead of page-factory create a helper method that will accept multiple selectors and then do the required operation 

_Sample Code_
```
public static WebElement findAnyElementWithSelector(WebDriver driver, By... bys) {
        for (By by : bys) {
            System.out.println("Searching with : " + by.toString());
            List<WebElement> elements = driver.findElements(by);
            if (elements.size() > 0)
                return elements.get(0);
        }
        throw new NoSuchElementException("No element found with selectors : " + StringUtils.join(bys, " OR "));
    }
```
_Usage_
```
findAnyElementWithSelector(driver, By.xpath("//input[@name='s']"), By.xpath("//a[contains(.,'Magic Mouse')]"));
```

**Comment by barancev** [comment]
@FindAll being applied to a "single element" field finds the first element that matches any of the provided locators. Yes, may be the name is not ideal for this use case. But it's definetely not wise to hit a timeout on the second locator if you have already got an element by the first one, and you need a single element, not a list.

**Comment by kumar-nitish** [comment]
@Nolfgk your commit will break existing functionality and test case
```
  @Test
   public void findFourElementsByAny() {
     final AllDriver driver = mock(AllDriver.class);
     final WebElement elem1 = mock(AllElement.class, "webElement1");
     final WebElement elem2 = mock(AllElement.class, "webElement2");
     final WebElement elem3 = mock(AllElement.class, "webElement3");
     final WebElement elem4 = mock(AllElement.class, "webElement4");
     final List<WebElement> elems12 = new ArrayList<>();
     elems12.add(elem1);
     elems12.add(elem2);
     final List<WebElement> elems34 = new ArrayList<>();
     elems34.add(elem3);
     elems34.add(elem4);
     final List<WebElement> elems1234 = new ArrayList<>();
     elems1234.addAll(elems12);
     elems1234.addAll(elems34);
 
     when(driver.findElementsByName("cheese")).thenReturn(elems12);
     when(driver.findElementsByName("photo")).thenReturn(elems34);
 
     ByAll by = new ByAll(By.name("cheese"), By.name("photo"));
     assertThat(by.findElements(driver), equalTo(elems1234));
   }
```

**Comment by samnit** [comment]
@kumar-nitish @barancev @Nolfgk  What can I use for now in my object map for mulitple locaters ? Is there any other solution ?

**Comment by samnit** [comment]
@kumar-nitish Thanks for the solution, it had worked fine. Is this resolve merged into the latest selenium release or I still need to use the file provided by you ??

**Comment by rakesh822** [comment]
@kumar-nitish is your fix merged ??
