### ISSUE TITLE
IE driver is not recognized

### ISSUE THREAD

**Issue by Sethuraman11** [SeleniumHQ/selenium#4472]
## Meta -
OS:  Windows 7

Selenium-Java Version:  3.4.0

Browser:  IE

Browser Version: IE11

## Actual Behavior - New IE opened tab is not comes under a new window when we use getWindowHandles. it is returning 1 as size but 2 windows are opened.

##Description - IE driver is not controlled by WebDriver when it opens in a new tab, even though 2 windows are opened. It shows 1 window is present.

## Steps to reproduce -
1. Open a IE browser using IEServer32.exe driver.
2.Using a 'Robot' class, opene a new tab by pressing "CTRL+T"
3.Get the count of windows after a new tab opened.
Expected : 2 windows
Actual : 1 window.

##Selenium Code to reproduce:
                System.setProperty("webdriver.ie.driver","Path to driver");
                WebDriver driver = new InternetExplorerDriver();
		driver.get("<URL>");
		Thread.sleep(2500);
		
	Robot robot = new Robot();
        robot.delay(3000);
        robot.keyPress(KeyEvent.VK_CONTROL);
        robot.keyPress(KeyEvent.VK_T);
        robot.delay(3000);
        robot.keyRelease(KeyEvent.VK_T);
        robot.keyRelease(KeyEvent.VK_CONTROL);
		Thread.sleep(2500);
		Set<String> parentHandle = driver.getWindowHandles(); 
		System.out.println(parentHandle.size());
		for (String winHandle : driver.getWindowHandles()) {
		    driver.switchTo().window(winHandle); 
		}
		driver.navigate().to("<URL>");

**Comment by jimevans** [comment]
Manually intervening in a browser instance (and using an automation tool external to the IE driver is indistinguishable from manual operation) being automated to open a new tab is not a supported scenario for the IE driver. The driver gets no notification of the newly opened tab, and therefore cannot attach to it.
