### ISSUE TITLE
WebDriverException: Session is already started

### ISSUE THREAD

**Issue by liangrengongzuoshi** [SeleniumHQ/selenium#4476]
browser = webdriver.Firefox()

proxy=webdriver.Proxy()
proxy.proxy_type=ProxyType.MANUAL
proxy.http_proxy='host:port'
proxy.add_to_capabilities(webdriver.DesiredCapabilities.FIREFOX)
browser.start_session(webdriver.DesiredCapabilities.FIREFOX)

throws Exception:
selenium.common.exceptions.WebDriverException: Message: Session is already started

My firefox's version is V54.0.1

How to fix this?

Thanks a lot.

**Comment by shs96c** [comment]
The first line (`browser = webdriver.Firefox()`) has created the session already. If you want to set the proxy, create the capabilities and pass them to the call to `Firefox()`

**Comment by liangrengongzuoshi** [comment]
But why using phantomjs is OK ? What I want to do is change the proxy after the driver has bean set up.
Thanks a lot.

    browser=webdriver.PhantomJS(PATH)
    proxy=webdriver.Proxy()
    proxy.proxy_type=ProxyType.MANUAL
    proxy.http_proxy='host:port'
    proxy.add_to_capabilities(webdriver.DesiredCapabilities.PHANTOMJS)
    browser.start_session(webdriver.DesiredCapabilities.PHANTOMJS)

**Comment by barancev** [comment]
Selenium does not allow to change proxy settings on the fly.

**Comment by liangrengongzuoshi** [comment]
selenium+phantomjs can change proxy settings when it fly.

**Comment by barancev** [comment]
I's a proprietary PhantomJS feature.

**Comment by liangrengongzuoshi** [comment]
OK，thanks.
