### ISSUE TITLE
Internet explorer hangs after clicking <a> that returns a file to download

### ISSUE THREAD

**Issue by Dkstlaurent-Xpertdoc** [SeleniumHQ/selenium#448]
We're using c# and Internet explorer 11
When we make the driver click the button which in our case executes an action and returns a file to download (in an iframe) at the end.
Sometimes, Internet explorer hangs in the click method after click an <a> and never gets out of it and sometimes the same test passes. Our goal is not to download the file (we have other way to verify the file) but to get our action done and be able to close internet explorer afterward or to continue testing other buttons.
when the test fails this error gets back to the top 

"Test threw exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://192.168.137.5:4444/wd/hub/session/16cdc835-87f5-4af6-965b-1e60ef73c28d/element/7/click timed out after 60 seconds. ---> System.Net.WebException: The request was aborted: The operation has timed out.
Result StackTrace:	
at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
 --- End of inner exception stack trace ---
    at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()"

when it gets stuck in the click method it causes all the following tests to fail

**Comment by ddavison** [comment]
why don't you just validate that the `href` points to the right file?  I don't see much use in clicking the link if you expect it to direct to a downloadable file

**Comment by Dkstlaurent-Xpertdoc** [comment]
because the <a> doesn't have an href, the click is handled by jquery. In the click handler, we post a form to the server (using ajax). In the success callback, we call jquery fileDownload that downloads (in an iframe) the resulting document. So we need to click the button to post the form to the server. There's no way to not call jquery.fileDownload.

**Comment by jimevans** [comment]
Two questions: Does the browser display an info bar about the file being downloaded? And if your log for `IEDriverServer.exe`(you **have** enabled logging, right?), are you stuck in a wait loop, and if so where?

**Comment by Dkstlaurent-Xpertdoc** [comment]
Yes browser display the info bar for the download and yes logs are enabled. Here they are
![ie logs](https://cloud.githubusercontent.com/assets/11926803/7159957/09cd106e-e354-11e4-915a-13b6c3b3253a.png)

**Comment by jimevans** [comment]
Then there's absolutely nothing to be done about it. While the info bar is being displayed, the browser considers the page to be loading, and does not return a readyState of "complete". This behavior is out of the control of the IE driver. A future version of the IE driver should allow you to work around the issue by setting a pageLoadStrategy capability to return earlier.

**Comment by Dkstlaurent-Xpertdoc** [comment]
Then why does it works sometimes and sometimes it doesn't ? Also is there a way to not wait for the ready state to be able to continue and close the browser? Because this means that it makes selenium unusable for us

**Comment by jimevans** [comment]
I don't know why it works sometimes and doesn't others. You'd have to ask the IE team why, in this case, the readyState property of the document doesn't move from `interactive` to `complete`.

In theory, you should be able to set the page load timeout to a short value, which should throw a `WebDriverTimeoutException` after the `Click`, which you can catch and then proceed to manipulate the browser. And no, there's no way to prevent the waiting for  `document.readyState` to be complete. As I said, a future version of the IE driver should allow this, but there is no timetable or guarantee when it will be implemented.

If Selenium isn't meeting your needs, then, by all means, I encourage you to find a library that does.

**Comment by awood20** [comment]
Sorry to comment on an old/closed issue but I think I'm running into the same issue and wondering of this was ever solved in some manner?

**Comment by kriegaex** [comment]
@awood20: Ticket #999 is still open. I think the two are related, and there is more infor there. E.g. I guess it is noteworthy that the download dialog is not actually modal, you can click anywhere on the page while the dialog is visible.
