### ISSUE TITLE
IE driver WebElement getLocation returns x=0 y=0

### ISSUE THREAD

**Issue by eugenedani** [SeleniumHQ/selenium#4480]
## Meta -
OS:  Windows 10 (OS build 15063)
Selenium Version:  3.5.0, IE driver 3.5.0
Browser:  Internet Explorer 
Browser Version:  11.483.15063.0 (64-bit)

## Expected Behavior -
WebElement getLocation method returns actual element location

## Actual Behavior -
WebElement getLocation method returns x=0 y=0

## Steps to reproduce -
WebDriver webDriver = new InternetExplorerDriver();
webDriver.get("https://www.google.com/");
WebElement element = driver.findElement(By.name("q"));
Point location = element .getLocation();

location.x and location.y have value 0

**Comment by barancev** [comment]
Reproduced.

**Comment by jimevans** [comment]
Fixed in d25d966. Released in `IEDriverServer.exe` 3.5.1.
