### ISSUE TITLE
Improper browser versions 

### ISSUE THREAD

**Issue by harshg0910** [SeleniumHQ/selenium#4485]
## Meta -
OS:  Windows 10
Selenium Version: 3.4.0
Browser:   Internet Explorer and Firefox
GeckoDriver Version: 0.17.0
Browser Version:  IE (v11.540) and Firefox (v54.0.1)

I'm trying to get the browser versions for both IE and Firefox in C# binding using the capabilities. For IE I'm getting '11' in and for Firefox I'm getting '' in capabilities.version property.

## Expected Behavior -
For IE get minor version also "11.540"
For Firefox actual version "54.0.1"

## Actual Behavior -
For IE get minor version also "11"
For Firefox actual version ""

## Steps to reproduce -
ICapabilities capabilities = ((RemoteWebDriver)webDriver).Capabilities;
capabilities.Version;

**Comment by p0deje** [comment]
The following works:

```java
	WebDriver driver = new FirefoxDriver();
	Capabilities capabilities = ((RemoteWebDriver) driver).getCapabilities();
	System.out.println("Version is: " + capabilities.getCapability("browserVersion"));
```

However, I get that this is something that still needs to be fixed in Java bindings, because `.getVersion()` method of `Capabilities` returns empty string.

**Comment by barancev** [comment]
In Java this has been fixed in 3.5, for Firefox.

**Comment by barancev** [comment]
IEDriverServer returns version number without minor version. Should we change this, @jimevans?

**Comment by jimevans** [comment]
@barancev The specification does not specify how detailed the browser version needs to be. Using only major version is an aesthetic choice. I'm not convinced that being more granular actually provides additional value.

**Comment by diemol** [comment]
Closing as issue got stale and no more user comments were added which could indicate the importance of the issue.
