### ISSUE TITLE
Selenium js not work with winium

### ISSUE THREAD

**Issue by randomailer** [SeleniumHQ/selenium#4488]
Meta -

OS: Mac OS 10.12.6
Selenium Version: 3.5.0
Browser: non browser, project [winium](https://github.com/2gis/Winium.Desktop)

I'm trying to get element window

```
const webdriver = require('selenium-webdriver')

const By = webdriver.By

const driver = new webdriver.Builder()
  .usingServer('http://terminal:9999')
  .withCapabilities({
    'app': 'C:/windows/system32/calc.exe'
  })
  .forBrowser('windows')
  .build()


  const w = driver.findElement(By.id('CalcFrame'))
```

`UnsupportedOperationError: 'css selector' is not valid or implemented searching strategy.`

**Comment by jleyba** [comment]
The error you are getting is from the remote end (winium), not the selenium client.

Note, `By.id('foo')` is equivalent to `By.css('#foo')`
