### ISSUE TITLE
In MS Edge v14+, SelectElement fails to deselect options from HTML <select multiple> controls

### ISSUE THREAD

**Issue by craigfowler** [SeleniumHQ/selenium#4490]
## Meta -
OS:  
Tested on Linux/Mono version 5.2.0.215
Likely affects any OS with DotNet
Selenium Version:  
Reproduced on `Selenium.Support` (NuGet package v3.4.0)
Appears that it will also affect v3.5.1 (based on a brief code review)
Browser:
Microsoft Edge
Browser Version:  
Reproduced with Edge 15 on Windows 10

### Deselecting single elements
Given you have an instance of `OpenQA.Selenium.Support.UI.SelectElement` and:
* It wraps a visible HTML `<select>` element
* That select element has the `multiple` attribute
* The select element has more than one option currently-selected.

When you make use of any of the **DeselectByXyz** methods from the `SelectElement` instance, indicating one of the currently-selected options (either by index, underlying value or displayed text).

Then the indicated option should be deselected and any other options which were previously selected should remain so.

### Deselecting all elements
Given you have an instance of `OpenQA.Selenium.Support.UI.SelectElement` and:
* It wraps a visible HTML `<select>` element
* That select element has the `multiple` attribute
* The select element has more than one option currently-selected.

When you make use of the **DeselectAll** method from the `SelectElement` instance.

Then all of the options in the select element should be deselected.

## Actual Behavior -
In Edge, the Deselect operation is functioning like "Select single option".  

### Deselecting single elements
In the first scenario (deselecting single elements), the actual result is that now the *only* element selected is the element which you had requested to deselect.

### Deselecting all elements
In the second scenario (using deselect-all) the result is that:
* The first item (in markup order) which was previously selected before **DeselectAll** was invoked is now selected
* All other previously-selected items are now deselected

## Steps to reproduce -
I have a test case for this, and records from a failed CI build.  Probably the Sauce Labs test log is the most useful, as it shows a breakdown of all of the API calls made to WebDriver.

* **[HTML markup used in the test case]** - *You can ignore the non-standard `metal:` attributes in the markup - they have no bearing on the test*
  * There is [some JavaScript associated with the page] which keeps some other elements on the page in-sync with the `<select>` controls and read their values
* **[Test fixture]** - *This is written in a Screenplay testing style (that being the project where I found this) but rest-assured, the deselection lines of test code just lead to a plain SelectElement and its deselect methods*
* **[Travis build log]** - *This is for Edge, the other jobs in the same build (current latest Chrome, Firefox, Internet Explorer and Safari) all pass this same test*
  * Notably, near the bottom of the build log is a Screenplay report, which indicates which features/scenarios were being executed and in what order.  Lines 2870 through 2904 are where the deselect tests fail.
* **[Sauce Labs test logs]** - *This log was produced using the Travis build job linked above, and the order in which the tests appear in the Screenplay report are the same as they were executed in Sauce Labs*
  * Notably, command 15: `POST element/4/click` appears to be the troublesome one.  MS Edge appears to be interpreting this as "Select this option and only this option" where all other browsers treat it as "toggle selection"
  * This is evident in the associated Sauce Labs screenshot - the element which was clicked is the one which reads "Carrot" which has the value (bold text near the bottom of the screen) "veg".  However, it should have been deselected, not selected.

[HTML markup used in the test case]: https://github.com/csf-dev/CSF.Screenplay/blob/985fef9f2e9de92ad8d0ec4c052cea15e9a635db/Tests/CSF.Screenplay.WebTestWebsite/Views/PageTwo/Index.pt
[some JavaScript associated with the page]: https://github.com/csf-dev/CSF.Screenplay/blob/985fef9f2e9de92ad8d0ec4c052cea15e9a635db/Tests/CSF.Screenplay.WebTestWebsite/Scripts/PageTwo.js
[Test fixture]: https://github.com/csf-dev/CSF.Screenplay/blob/985fef9f2e9de92ad8d0ec4c052cea15e9a635db/Tests/CSF.Screenplay.Web.Tests/Actions/DeselectTests.cs
[Travis build log]: https://travis-ci.org/csf-dev/CSF.Screenplay/jobs/265696662
[Sauce Labs test logs]: https://saucelabs.com/beta/tests/6275bc4aca324b209a97c563efd3ccd9/commands#15

## Research I have performed so far
I have a feeling that this might be related to [issue #5437605] on Microsoft's Edge issue tracker (which was migrated from [this previous report]).

If it is, then Microsoft consider it "functioning as specified" for Edge to interpret clicks as single-item selection (for a `<select multiple>` element).  It seems that they would want WebDriver to do more than just a normal click (such as sending modifier keys) in order to get the desired functionality.  This would mean that `SelectElement` does not support Edge as-is?

I'm not sure where to go next from here.  Is it a Selenium bug or an Edge bug?  Seems that might be up for some debate.

[issue #5437605]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5437605/
[this previous report]: https://connect.microsoft.com/IE/feedback/details/2020772/-microsoft-edge-webdriver-cannot-select-multiple-on-select-html-tag

**Comment by craigfowler** [comment]
Update: This exact same symptom now affects Apple Safari, starting with version 11 (does not affect 10).

**Comment by craigfowler** [comment]
## Updated info
Hi all.  I've done a fair bit of investigation around this in my own project and I'd like to share my findings.  Most notably *I was wrong about Safari 11*, it's not quite the same symptom and it differs enough to be worth it's own issue (which I'll open momentarily).  I've edited the title of this ticket to remove mention of Safari and I'd suggest someone removes the label.

### Microsoft Edge v14 +
I have confirmed that using **EdgeHTML version 14+**, you must indeed send a Ctrl+Click from the WebDriver in order to select/deselect individual options within an HTML `<select multiple>` element.  I have worked around this limitation by creating a slightly modified version of the `SelectElement` class (few changes so I could subclass it) and then creating a subclass named `SelectElementUsingModifierKey`.  [You can see my changes here](https://github.com/csf-dev/CSF.Screenplay.Selenium/tree/4913a02fd34c598fc9d6b3f741108005f6aecafe/CSF.Screenplay.Selenium/CSF.Selenium.Support.UI) but in short it changes the click to:

```csharp
new Actions(driver)
  .KeyDown(modifierKey)
  .Click(option)
  .KeyUp(modifierKey)
  .Perform();
```

When testing against an affected version of Edge, I use that modified select element instead of the usual one.

### Microsoft Edge v13
I have also tested the same against EdgeHTML version 13 to find that it didn't work.  In Edge 13, whether I send ctrl+click or whether I send a plain click, the selected options do not change.

I cut my investigation of Edge 13 short though because:
* It's a very old browser now (2015)
* I expect *real world* users to receive automatic updates and be using the latest version

Based on that, the cost/benefit of creating a fix wasn't worth it to me.

### Safari 10.x
Both Safari 10.0 and 10.1 work just fine with the out-of-the-box `SelectElement` class.  This is true whether or not the select element has the `multiple` attribute or not.

### Safari 11.0
I was incorrect when I had said that it was the exact same symptom which affects Safari v11.0 as well as Edge.  I had assumed that it was the same problem because of the similarities between my Safari problem and my Edge problem.  I had sent a click via the wire protocol to a remote web driver, but despite seeing that the server received and processed the click on the HTML `option` element, the state of the `<select multiple>` element (the options selected) did not change.

However, I have also seen that Safari suffers the exact same problem when dealing with select elements that *do not* have the `multiple` attribute.  So - in that case I don't think that the problem has anything to do with needing to send a modifier key + click.

**Comment by diemol** [comment]
@craigfowler thank you for adding all your findings here. Apologies for the lack of response... Is this still an issue or is the browser version too old that makes this issue not relevant anymore?
If this is still an issue, a way to reproduce it with an automated script would be very helpful.

**Comment by craigfowler** [comment]
I think I understand what you're saying here.  Edge/EdgeHTML is dying tech now, so I wouldn't oppose dropping this ticket as "not worth the effort to fix".

I somehow doubt many web applications are going to want to spend effort maintaining support & testability of a dead browser.  If anyone has had this problem then they have already had it and worked-around it, and it's unlikely any new work will run into this problem because they won't be testing against pre-Chromium Edge.

I've actually put my usage of Selenium down for a while, so I have yet to try on Edge/Chromium (and might not get a chance for a while).  Given it's pretty much a rewrite, I wouldn't expect any issues for EdgeHTML to still be valid for the Chromium browser.

**Comment by diemol** [comment]
Thank you for the feedback @craigfowler. 
Then, I will be closing this for now, but we are always welcoming a new issue in case this needs to be tackled.
