### ISSUE TITLE
selenium-webdriver examples broken by Google btnG element not clickable

### ISSUE THREAD

**Issue by mykmelez** [SeleniumHQ/selenium#4491]
## Meta -
OS:  macOS 10.11.6
Selenium Version:  3.5.0
Browser:  Firefox, Chrome
Browser Version:  Firefox 55, Chrome 60
GeckoDriver Version: 0.18.0
ChromeDriver Version: 2.31.488774

## Expected Behavior -
The [selenium-webdriver README](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver#usage) inlines an example Node script that uses Firefox to load Google and search for "webdriver". Running that example script should succeed, and a variety of other scripts in the [example/ directory](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example) should similarly succeed.

## Actual Behavior -
The script fails with the cryptic error message "WebDriverError" in Firefox and only a slightly better error message "ElementNotVisibleError: element not visible" if I modify it to use Chrome instead of Firefox. A variety of other scripts in the example/ directory similarly fail.

## Steps to reproduce -
> npm install selenium-webdriver
> node node_modules/selenium-webdriver/example/google_search.js

After a bit of debugging, I discovered that the error is triggered by the statement `driver.findElement(By.name('btnG')).click()`, and Firefox appears to be returning the error message "element not interactable" (even though that doesn't get printed to my terminal, which is a different issue).

So it seems like both Firefox and Chrome see the "btnG" button on Google's home page as inaccessible (whether because "not visible" or "not interactable"). Presumably this is because of some change to that page that has broken these examples, not because of a regression in Selenium itself. Nevertheless, it manifests as broken examples in Selenium, which is why I'm filing it here.

**Comment by jess010** [comment]
There appears to be some uncaught instances of this issue in the repo. Opening a PR to address by updating references to current name instead of return approach. The Selenium WebdriverJs Wiki page still needs updating also.

**Comment by jess010** [comment]
For what it's worth, having reference to a button 'click' action using webdriver in the example on the Wiki, in addition to the previous 'sendKeys' command very helpful for getting up to speed with basic webdriver functionality when I was using this for a hackathon a month ago. 

Even though there is a risk of 'btnK' references becoming deprecated at some point in future also, I would urge you folks to keep it as a button click to better help new devs in future learn the basics.
