### ISSUE TITLE
Re-render an HTML page with CSS and HTML working

### ISSUE THREAD

**Issue by KellyBJiang** [SeleniumHQ/selenium#4492]
OS:  Linux
Browser:  Chrome
I crawled a webpage using Selenium and PhantomJS, I want to highlight some keywords and render this page as html again.
However, the CSS and Javascript, and the links doesn't work anymore.
Is there any way I can re-render the page with CSS, Javascript and the links working?

    browser = webdriver.PhantomJS(service_log_path='/dev/null')
    browser.get('http://www.mdpi.com/')
    html_ph = open("phantomjs.html","w")
    html_ph.write(browser.page_source.encode('utf-8'))
    html_ph.close()

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
