### ISSUE TITLE
/wd/hub/sessions not worked in standalone server mode

### ISSUE THREAD

**Issue by alterhu2020** [SeleniumHQ/selenium#4496]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.5.0
Browser:  
Chrome

Browser Version:  
Chrome 59.0

## Expected Behavior -
The page should display correct content with the session list it had found
## Actual Behavior -
1. Page throw this exception popup message: `Unable to refresh session list`
2. Go to the chrome's console, and found that there's a request 404 error caused this exception which is : `http://localhost:4444/wd/hub/sessions` 
![selenium404exception](https://user-images.githubusercontent.com/5029046/29446117-59e59966-839f-11e7-8295-0a66ec4e6308.jpg)
3. I don't found any page had mentioned that this JSON interface not available or not? please help this .
## Steps to reproduce -
1. Download the latest release selenium server file: selenium-server-standalone-3.5.0.jar
and start it from command line: `java -jar selenium-server-standalone-3.5.0.jar -debug`
2. Open the browser to this url:
`http://localhost:4444/wd/hub`

**Comment by shankarkc** [comment]
@alterhu2020 may be its something to do with this bug
https://github.com/SeleniumHQ/selenium/issues/4495
Can u pls check your hub log to see if the node getting disconnect/reconnect continuously ?

**Comment by barancev** [comment]
@shankarkc Stop hijacking random issues to draw attention to the one you've reported.

**Comment by alterhu2020** [comment]
@barancev , This issue is very bad for me, because it broken my whole script ,which I want to check the existing session started by selenium server before starting new session.

**Comment by barancev** [comment]
Fixed in afdf13b849e3d9d104dd3f6a4f24c82989826d76
It's not decided yet when it will be released. If you're in hurry you can build selenium server from source.

**Comment by alterhu2020** [comment]
OK,  I will refer the code you had made for this command ,thanks for your help . @barancev

**Comment by shankarkc** [comment]
@barancev I  am not trying to get attention nor hijacking anything. As its a community i am just trying to help. As the issue reported on 3.5.0 it looked like it might be related.  So i just asked if its the same issue.
