### ISSUE TITLE
REMOTE_HOST is not replaceable with SE_OPTS

### ISSUE THREAD

**Issue by McSnowflake** [SeleniumHQ/selenium#4501]
## Meta
OS:  Linux using Docker
Selenium Version:  3.4.0

## Summary
The removal of REMOTE_HOST breaks usage scenarios where port mapping is needed.

## Example
Setting up a selenium grid via docker as explained here:  #432.

It's essentially this
`docker run -d --name node101 -p XXXXXX:5555 -e HUB_PORT_4444_TCP_ADDR=192.168.2.103 -e HUB_PORT_4444_TCP_PORT=4444 -e SE_OPTS="-host 192.168.2.103 -port XXXXXX" selenium/node-chrome:3.4.0`
nodeConfig contains :   `"port": 5555`

What this is expected to do:
Multiple nodes running on one host: The nodes running at port 5555 inside containers that expose this port to be unique for the host (XXXXXX). When registering to the hub the node shall tell that exposed port to the hub instead of the internal.

What it actually does:
SE_OPTS  overwrites the nodes port setting, which will make it use this port (XXXXXX) inside the container which will break the port mapping.

## Conclusion
REMOTE_HOST allowed to tell the node the exposed port (without overwriting its port setting), so that it could then tell the hub to use it, making port mapping actually possible.

## Related tickets
 #307, #481, #432

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/docker-selenium #540](https://github.com/SeleniumHQ/docker-selenium/issues/540) via [**ZenHub**](https://www.zenhub.com/)

**Comment by McSnowflake** [comment]
@barancev I created this ticket at selenium intentionally, because the REMOTE_HOST param is not special for the docker images, but was a basic selenium feature. At least that's what I understood.

**Comment by barancev** [comment]
It is special for docker images.
