### ISSUE TITLE
Python package for 3.5.0 reports __version__ as 3.4.3

### ISSUE THREAD

**Issue by dbl82** [SeleniumHQ/selenium#4502]
## Meta -
OS:  Windows 10
Selenium Version:  3.5.0
Browser:  None

## Expected Behavior -
`selenium.__version__` should report '3.5.0'

## Actual Behavior -
```
import selenium
selenium.__version__
'3.4.3'
```

## Steps to reproduce -
```
import selenium
selenium.__version__
'3.4.3'
```

**Comment by lmtierney** [comment]
Fixed in 00460be7708d07f2dd58b818137986ecb8ac5ec7
