### ISSUE TITLE
chrome driver takes 131 seconds to start headless browser

### ISSUE THREAD

**Issue by kiodou** [SeleniumHQ/selenium#4509]
## Meta -
OS:  
Ubuntu
Selenium Version:  
3.5.0
Browser:  
Chrome

Browser Version:  
Google Chrome 60.0.3112.101 (64 bit)

## Expected Behavior -
Start chrome driver in less than a minute
## Actual Behavior -
Chrome driver starts in exactly 131 seconds every time (issues started randomly out the blue)
## Steps to reproduce -
It's just simple code, i start up Xvfb (virtual frame buffer) and i start the chrome driver, but it takes 131 seconds to start. Here is the selenium debug log, and in addition i log the time it takes to start to webdriver.

```
08/18/2017 03:34:03 PM Testing driver: https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
08/18/2017 03:34:07 PM POST http://127.0.0.1:52807/session {"capabilities": {"alwaysMatch": {"browserName": "chrome"}, "firstMatch": [{}]}, "desiredCapabilities": {"platform": "ANY", "browserName": "chrome", "version": "", "chromeOptions": {"args": [], "extensions": []}}}



08/18/2017 03:36:15 PM Finished Request
08/18/2017 03:36:15 PM DELETE http://127.0.0.1:52807/session/9c3894efdb69dc989966cc37e6f1fd22 {"sessionId": "9c3894efdb69dc989966cc37e6f1fd22"}
08/18/2017 03:36:15 PM Finished Request
08/18/2017 03:38:23 PM completed in 131 seconds
```

I haven't did any update prior to this problem, the issue just appeared randomly, starts up in a few seconds and i can run my test suite. It currently still works on mac os, just not for linux.

Thank You,

**Comment by kiodou** [comment]
I've tried both pyvirtualbuffer and Xvfb, i get the same results. I've upgraded selenium package (coding in python), i've tried all the chromedrivers from 2.24 to 2.31, exact same results. From looking at the log just by starting up it makes this request to `http://127.0.0.1:52807/session`, maybe that could be what holding it up.

**Comment by barancev** [comment]
Report this to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help
