### ISSUE TITLE
Unable to initiate Internet Explorer v10 with Selenium (3.5.0) when "webdriver.Ie()" contains "DesiredCapabilities" class object through Python PyDev (Eclipse).

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4510]
## Meta - Unable to initiate Internet Explorer v10 with Selenium (3.5.0) when `webdriver.Ie()` contains `DesiredCapabilities` class object through Python PyDev (Eclipse).

Error `TypeError: __init__()` is observed when `desired_capabilities=cap` is present within `webdriver.Ie()`

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.0 (Python 3.6.1)

Selenium Binding: Python 3.6.1

IEDriverServer Version: 3.5.0.0

Browser: INTERNETEXPLORER

Browser Version: INTERNETEXPLORER 10.0

## Steps to reproduce -
Minimal Code Block:

	from selenium import webdriver
	from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

	cap = DesiredCapabilities().INTERNETEXPLORER
	cap['platform'] = "Win8"
	cap['version'] = "10"
	cap['browserName'] = "internet explorer"
	cap['ignoreProtectedModeSettings'] = True
	cap['IntroduceInstabilityByIgnoringProtectedModeSettings'] = True
	cap['nativeEvents'] = True
	cap['ignoreZoomSetting'] = True
	cap['requireWindowFocus'] = True
	cap['INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS'] = True
	browser = webdriver.Ie(desired_capabilities=cap, executable_path="C:\\Utility\\BrowserDrivers\\IEDriverServer.exe")
	browser.get("https://www.facebook.com/")

Error stack trace on my console:

	Traceback (most recent call last):
	  File "C:\Users\AtechM_03\LearnAutmation\PythonProject\MyPythonPackage\B_IE.py", line 14, in <module>
	    browser = webdriver.Ie(desired_capabilities=cap, executable_path="C:\\Utility\\BrowserDrivers\\IEDriverServer.exe")
        TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'

**Comment by lmtierney** [comment]
The error message explains exactly what is happening. Please look at the API before raising issues. The key is `capabilities` for `webdriver.Ie()`

**Comment by Debanjan-B** [comment]
@lmtierney Thanks for the comments. Can you please provide us the link to see the Python APIs?

**Comment by lmtierney** [comment]
@Debanjan-B  http://seleniumhq.github.io/selenium/docs/api/py/

**Comment by Debanjan-B** [comment]
@lmtierney Thanks a lot for the help.

**Comment by Debanjan-B** [comment]
Perhaps I should have been asked the definite question:

As per the [documentation](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#module-selenium.webdriver.remote.webdriver), **`desired_capabilities`** seems to be the **Required parameter** for `class selenium.webdriver.remote.webdriver.WebDriver()`

So any reason to use **`desired_capabilities`** in `class selenium.webdriver.chrome.webdriver.WebDriver()` where [Firefox](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html#module-selenium.webdriver.firefox.webdriver) and [IE](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_ie/selenium.webdriver.ie.webdriver.html#module-selenium.webdriver.ie.webdriver) uses **`capabilities`** only

Can I have the closing comments please? @lmtierney @AutomatedTester @shs96c

**Comment by lmtierney** [comment]
I cannot attest to why they were different originally, but they all get put into the right spot in the end. Those are just keywords to the object init

**Comment by Debanjan-B** [comment]
@lmtierney Does [Selenium](https://github.com/SeleniumHQ) [umbrella project for a range of tools and libraries] follow/have any standard **Specification Document** apart from published online [Documentation](http://docs.seleniumhq.org/docs/) and [API](http://seleniumhq.github.io/selenium/docs/api/py/) docs (something similar to W3C Specs) to look upon?

@jimevans @shs96c  Any suggestions?

**Comment by manoj9788** [comment]
Spec file is here: https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by Debanjan-B** [comment]
Thanks @manoj9788 Thats the **WebDriver
W3C Candidate Recommendation 23 August 2017** Spec file.

I looking out if **Selenium Project** themselves is following any Standards/Specification to implement the **`WebDriver`** project through Java/Python/JavaScript/C#/Ruby bindings.
