### ISSUE TITLE
Executable needs to be in PATH - Running Selenium on GNURoot on Android

### ISSUE THREAD

**Issue by LecJackS** [SeleniumHQ/selenium#4514]
## Meta -
OS: GNURoot on Andoid

Selenium Version:  3.5.0

Browser:  Chromium

Browser Version:  

## Expected Behavior -
To load driver
## Actual Behavior -
Error. Chromium executable not found in path.
## Steps to reproduce -

Selenium installed using pip, on GNURoot on Android.

Trying to run this code :

    import selenium

    from selenium import webdriver

    #driver = webdriver.Chrome()

    driver = webdriver.Chrome(executable_path='/usr/bin/chromedriver')

    time.sleep(5)

    driver.quit()
 

What I get:

>  python 5formscrape-selenium.py
> 
>  Traceback (most recent call last):
> 
> File "5formscrape-selenium.py", line 5, in <module>  driver =
> webdriver.Chrome(executable_path='/usr/bin/chromedriver')
> 
> File
> "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py",
> line 62, in __init__  self.service.start()
> 
> File
> "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py",
> line 81, in start  os.path.basename(self.path),
> self.start_error_message)
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver'
> executable needs to be in PATH. Please see
> https://sites.google.com/a/chromium.org/chromedriver/home

 

`$PATH` contains `/usr/bin`

chromedriver file is in `/usr/bin` with privileges

    sudo chmod a*x chromedriver 

So what I'm missing here?

As suggested in StackOverflow, I printed:

    import os

    import sys

    import subprocess

    print(sys.path)

    print(os.getenv('PYTHONPATH'))

    print(subprocess.check_output(["which", "chromedriver"]))

For what I get:

> ['/sdcard/3python2', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/pymodules/python2.7']
> 
> None
> 
> /usr/bin/chromedriver

But I don't know how to interpret that information.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by zahraegh** [comment]
@LecJackS I have similar issue using jupyter! Where you are to solve your problem?

**Comment by LecJackS** [comment]
@zahraegh Trying to use it on Android was the problem. Worked perfectly on windows and ubuntu.

**Comment by zahraegh** [comment]
Well, here is link to my original issue:
https://stackoverflow.com/questions/49017450/cannot-import-selenium-in-new-environment-anaconda-python-3-6-even-though-it-is
I had no luck importing selenium in my jupyter notebook and I decided to give jupyterlab binder a try. I was able to install the selenium on the binder terminal by `pip install selenium` and do `from selenium import webdriver`. How can I perform webdriver.Chrome(r"path/to/chromedriver.exe")? Can the path to an executable be in my local drive? right now I am getting `WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home` error message.
