### ISSUE TITLE
python+selenium+phantomjs can not handle https url which `adding certification is strongly advised`

### ISSUE THREAD

**Issue by 3xp10it** [SeleniumHQ/selenium#4516]
## Meta
OS:  
mscOS sierra
Selenium Version:  
selenium-3.5.0
Browser:  
phantomjs v2.1

## Detail

https://stackoverflow.com/questions/45789484/pythonseleniumphantomjs-can-not-handle-https-url-which-adding-certification-i

**Comment by barancev** [comment]
You have to report this issue to the phantomjsdriver (aka ghostdriver): https://github.com/detro/ghostdriver
