### ISSUE TITLE
Not able to launch Safari browser in windows10 with selenium 3.4.0 and safari browser 5.1.7 and safari driver 2.48

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#4519]
## Meta -
OS:   Windows 10 
Selenium Version:   3.4.0,
Browser:   Safari

I am trying to run a test using selenium using C#  on safari browser, i am using below code to launch browser but i am getting error
 DesiredCapabilities capabilities =  DesiredCapabilities.Safari();
  capabilities.Platform= Platform.CurrentPlatform;
driver.Manage().Timeouts().SetPageLoadTimeout(TimeSpan.FromSeconds(pageload_time));
driver = new SafariDriver(opt);
driver.Navigate().GoToUrl(value);

But here i am getting error ""Object reference not set to an instance of an object."  in setting pageloadtimeout itself

**Comment by jimevans** [comment]
Apple has not supported Safari on Windows in at least two years. Accordingly, the .NET bindings do not support the legacy Safari driver any longer.

**Comment by shiyaf** [comment]
Thanks for clarification
