### ISSUE TITLE
IEDriverServer.exe (3.5.0.0) with Selenium (3.5.0) doesn't produce any logs when "webdriver.Ie()" contains "log_file='./Logs/IEDriverServer.log'" through Python PyDev (Eclipse)

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4521]
## Meta - IEDriverServer.exe (3.5.0.0) with Selenium (3.5.0) doesn't produce any logs when "webdriver.Ie()" contains "log_file='./Logs/IEDriverServer.log'" through Python PyDev (Eclipse)

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.0 (Python 3.6.1)

Selenium Binding: Python 3.6.1

IEDriverServer Version: 3.5.0.0

Browser: INTERNETEXPLORER

Browser Version: INTERNETEXPLORER 10.0

## Expected Behavior - 

The documentation for [`"webdriver.Ie()"`](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_ie/selenium.webdriver.ie.webdriver.html#module-selenium.webdriver.ie.webdriver) clearly mentions as follows:

    class selenium.webdriver.ie.webdriver.WebDriver(executable_path='IEDriverServer.exe', capabilities=None, port=0, timeout=30, host=None, log_level=None, log_file=value)

So, IEDriverServer.exe (3.5.0.0) with Selenium (3.5.0) should produce expected logs when "webdriver.Ie()" contains "log_file='./Logs/IEDriverServer.log'" through Python PyDev (Eclipse).

## Steps to reproduce -
Minimal Code block:

	from selenium import webdriver
	from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

	cap = DesiredCapabilities().INTERNETEXPLORER
	cap['platform'] = "Win8"
	cap['version'] = "10"
	cap['browserName'] = "internet explorer"
	cap['ignoreProtectedModeSettings'] = True
	cap['IntroduceInstabilityByIgnoringProtectedModeSettings'] = True
	cap['nativeEvents'] = True
	cap['ignoreZoomSetting'] = True
	cap['requireWindowFocus'] = True
	cap['INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS'] = True
	browser = webdriver.Ie(capabilities=cap, executable_path="C:\\Utility\\BrowserDrivers\\IEDriverServer.exe", log_file='./Logs/IEDriverServer.log')
	browser.get('http://google.com/')
	browser.quit()

**Comment by lmtierney** [comment]
This is working fine, there's just nothing to log. The default log level is `FATAL` as per https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#command-line-switches

If you also added `log_level='DEBUG'` to your `webdriver.IE()` call, you'd get plenty in the log file

**Comment by Debanjan-B** [comment]
Thanks @lmtierney That works as expected.
