### ISSUE TITLE
Chrome tracing stops after first access to “.logs()”

### ISSUE THREAD

**Issue by bluejamesbond** [SeleniumHQ/selenium#4530]
I have set up tracing on Selenium. I am able to access the trace the first time. However, in the middle of the test if I access the performance logs once, then all subsequent performance logs do not contain the trace information . 

Accessing the logs via the following API:
```
driver.manage().logs().get(LogType.PERFORMANCE)
```

I followed the instructions [here](https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log) which states, however it doesn't seem to be working as described: 
> Collecting trace events can add overhead to a test, so ChromeDriver only collects trace events at appropriate points during a test. Currently, trace events are only collected on page navigation events and when any **ChromeDriver log (e.g. the performance log) is requested**. There is always a possibility that the buffer will still fill, so ChromeDriver monitors the buffer usage for supported Chrome versions (r263512 and later). If the buffer fills, ChromeDriver will log a warning and will add an entry to the performance log, as described below.

## Meta
OS:  OSX
Selenium Version:  3.5.1
Browser:  Chrome
Browser Version:  60

## Behavior
- enable tracing
- visit page 1
- getLogs (the cpu profiler information is accessible here)
- click a UI element
- getLogs (no cpu profiler information, only network logs are seen)

## Behavior with Code
```groovy
def run() {
   def driver = getDriverWithTracing();
   
   driver.get("https://yahoo.com");
   getTrace(); // has all the CPU traces
   driver.clickButton(); // this click does not change the URL but runs some JavaScript code
   getTrace(); // has no CPU traces < --- how can we fetch all the logs here?
   driver.get("https://yahoo.com")
   getTrace(); // has all the CPU traces
}

def getTrace() {
   JSONArray list = new JSONArray()

    for (LogEntry entry : driver.manage().logs().get(LogType.PERFORMANCE)) {
      JSONObject object = new JSONObject(entry.getMessage())
      list.put(((JSONObject) object.get("message")).get("params"))
    }
   
    return list
}

String TRACING_CATEGORIES = String.join(
            ",",
            "-*",
            "devtools.timeline",
            "v8.execute",
            "disabled-by-default-devtools.timeline",
            "disabled-by-default-devtools.timeline.frame",
            "toplevel",
            "blink.console",
            "latencyInfo",
            "disabled-by-default-devtools.timeline.stack"
    )

def getDriverWithTracing() {
   DesiredCapabilities capabilities = DesiredCapabilities.chrome();
   ChromeOptions options = new ChromeOptions();
   LoggingPreferences logs = new LoggingPreferences();

   logs.enable(LogType.PERFORMANCE, Level.ALL);

   Map<String, Object> perfLogPrefs = new HashMap<>();
   perfLogPrefs.put("traceCategories", TRACING_CATEGORIES); // comma-separated trace categories

   capabilities.setCapability(CapabilityType.LOGGING_PREFS, logs);
   options.setExperimentalOption("perfLoggingPrefs", perfLogPrefs);
 
   capabilities.setCapability(ChromeOptions.CAPABILITY, options);

   return new ChromeDriver(capabilities);
}
```

_NOTE: If I navigate away from the page via. `driver.get(<url>)`, then the trace information is populated and accessible._

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/).

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bluejamesbond** [comment]
@barancev i have added some code

**Comment by bluejamesbond** [comment]
@barancev just wanted to follow up. any information. I had gone through the driver logs which indicate that the cpuProfiler has stopped has after the first getLog via `Tracing.end`

**Comment by barancev** [comment]
It seems to be a chromedriver issue, please follow instructions on https://sites.google.com/a/chromium.org/chromedriver/help
