### ISSUE TITLE
What is the best solution to share same WebDriver object through our tests? Meaning if we are running a test suite where each test performs a different operation, how do we maintain the same browser session through out?

### ISSUE THREAD

**Issue by mansigit86** [SeleniumHQ/selenium#4533]
## Meta -
OS:  
<MAC OS, Windows>
Selenium Version:  
<WebDriver 3.4 -->
Browser:  
Firefox,Chrome

Browser Version:  
<Chrome 60.0 (64-bit) -->

Sample Code goes like this -

public class BaseClass {
	static WebDriver driver;
	
	@BeforeMethod
	public void openBrowser() throws Exception{
		driver=SelectBrowser.StartBrowser("firefox","http://automationpractice.com/");
		Login objLogin=PageFactory.initElements(driver, Login.class);
		driver=objLogin.TestLogin();
	}
	@AfterMethod
	public void closeBrowser(){
	driver.close();	
	}
	
	@Test
	public void PlaceNewOrder() throws Exception{
		PlaceAnOrder objPlaceOrder=PageFactory.initElements(driver, PlaceAnOrder.class);
		objPlaceOrder.PlaceOrder();
		
	}

Expected# I wish to use the same webdriver object that I am initializing in the @BeforeMethod, in the other @Test too. 

Actual# But when the control moves to @Test, it opens a new browser session.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
