### ISSUE TITLE
Sendkeys is losing dashes (hyphen)

### ISSUE THREAD

**Issue by BrianVBaker** [SeleniumHQ/selenium#4534]
Selenium Webdriver 3.5.1  (Chrome)

Hyphens (dashes) are being lost when trying to send strings containing hyphens or dashes to fields

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Should be fixed in 3.5.3, please reopen the issue if it's not true.
