### ISSUE TITLE
Selenium Grid - Specified number of threads not getting fully occupied

### ISSUE THREAD

**Issue by vignesh-paramasivam** [SeleniumHQ/selenium#4536]
OS:  
- Linux Suse11

Selenium Version:  
- 2.53.1

Test environment:

- Selenium Grid v2.53.1
- Ruby, Cucumber, Remotewebdriver with http::persistent client
- Browser Version:  Chrome v55+ (Current version 60.0.3112.90)

I have specified the number of threads as 20 for 300 test cases. When the test run starts it occupies all the 20 threads and completes over 270+ test cases, after that the thread occupancy is getting reduced to very few and by the end it is running with single thread.

This is the same case irrespective of number of threads, where the last 10% of the tests are occupied with minimum number of threads even though there are more test cases to run than the number_of_threads.

## Expected Behavior -
If the total number of tests are more than given number_of_threads, then it should occupy all the available threads to run.

**Comment by diemol** [comment]
Apologies for the late reply.
This sounds as a test runner issue instead of a Grid issue.
Could you please try again with the latest released versions and if the issue still persists, create a new issue with a reproduction scenario?
