### ISSUE TITLE
Safari Technology Preview (STP) can not be used with selenium hub.

### ISSUE THREAD

**Issue by hypnoce** [SeleniumHQ/selenium#4537]
## Meta -
OS:  MacOS Sierra 10.12.6
Selenium Version:  3.5.2 (server)
Browser:  Safari
Browser Version:  TP 37

## Expected Behavior -
When I instantiate a RemoveWebDriver with safari options set to use TP, I expect to to launch a safari TP browser.
## Actual Behavior -
But the hub instantiates the stable safari browser 10.1.2.
## Steps to reproduce -
Create a single node hub on MacOS with safari as browser. Launch a remote session with technologyPreview capability set to true.

After analysis, the bug seems to be located in [ServicedSession](https://github.com/SeleniumHQ/selenium/blob/8db389076bd2d5b4384345777908d9b4f8ec2c12/java/server/src/org/openqa/selenium/remote/server/ServicedSession.java#L147) where we do not pass any capabilities when creating the driver service.
Therefore, SafariDriverService [will be instantiated with default SafariOptions](https://github.com/SeleniumHQ/selenium/blob/20ae4f916196ad885923839f1da6455cc74c62af/java/client/src/org/openqa/selenium/safari/SafariDriverService.java#L45). In consequence, [The default Safari browser is used](https://github.com/SeleniumHQ/selenium/blob/20ae4f916196ad885923839f1da6455cc74c62af/java/client/src/org/openqa/selenium/safari/SafariDriverService.java#L45)

**Comment by khramovv** [comment]
Is there is some updates?

**Comment by burg** [comment]
I have heard reports that this reproduces with the Selenium 3.6 jar as well. Can someone take a look? Happy to help however I can from the Safari side, but this is almost certainly a bug in grid-related code.

**Comment by shs96c** [comment]
Partly related to #3123. Once that fix is in place, nodes should be able to be configured to always use the STP.

Also related to ed04104efdcc4ef201b37d1e7abb4f761b7e31d1, where we configure the service from the options passed to the remote driver.

**Comment by praveen-cimplicity** [comment]
Hi Simon, Kindly update once [Selenium 3.7 beta](https://www.seleniumhq.org/download/) has a fix for this - Thanks

**Comment by shs96c** [comment]
The fix for this will be in 3.7

**Comment by praveen-cimplicity** [comment]
Thanks Simon for your efforts. Any 3.7 release cadence or ETA that selenium users can expect?

**Comment by barancev** [comment]
Version 3.7 has been shipped.

**Comment by praveen-cimplicity** [comment]
Just want to make sure the selenium 3 node JSON we are using for Technology preview is free from typos. Could someone please review? Thanks
==================================================
`{
  "capabilities":
      [
        {
	  	"browserName": "safari",
		"maxInstances": 1,
	  	"technologyPreview":true,
	  	"seleniumProtocol": "WebDriver",
	  	"webdriver.safari.driver": "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver"
        }
      ],
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSessions": 1,
    "port": 5446,
    "register": true,
    "registerCycle": 5000,
    "role": "node"
}`
==================================================

**Comment by barancev** [comment]
Reading "technologyPreview" setting from the node config file is not yet implemented, it's an independent issue, we're working on this feature.

**Comment by praveen-cimplicity** [comment]
Hi Alexei, Could you please provide the GitHub issue# or link for STP? -Thanks
