### ISSUE TITLE
Click on a Link - Opens New Tab - Switch to New Window is not working in IE, but working in Chrome

### ISSUE THREAD

**Issue by newton143** [SeleniumHQ/selenium#4541]
## Meta -
OS:  Windows 7
Selenium Version:  3.4
Browser:  Internet Explorer
Browser Version:  IE11

## Expected Behavior -
Able to switch to new tab in IE

## Actual Behavior -
Unable to switch to new tab in IE

## Steps to reproduce -
 After clicking on below link, opens new tab, unable to switch to new tab in IE Browser.
            <a title="Imports and Feeds" class="cso-hyper-link clsHyperlink cso-text-large cso-text-bold  cso-wrap-text " id="_ct0ai0ee" aria-label="Imports and Feeds" href="/JWTOutboundSSO.aspx?area=import&amp;newtab=true" target="_blank" ct="Hyperlink">Imports and Feeds</a>

  I tried similar link in same page which opens another new tab in IE, its working fine
     <a title="API Explorer" class="cso-hyper-link clsHyperlink cso-text-large cso-text-bold  cso-wrap-text " id="_cp0ai0ee" aria-label="API Explorer" href="/JWTOutboundSSO.aspx?area=apiexplorer&amp;newtab=true" target="_blank" ct="Hyperlink">API Explorer</a>

I tried the above same links in Chrome Browser, both are working fine
            <a ct="Hyperlink" id="_cp0ai0ee" class="cso-hyper-link clsHyperlink cso-text-large cso-text-bold  cso-wrap-text " style="" href="/JWTOutboundSSO.aspx?area=apiexplorer&amp;newtab=true" target="_blank" title="API Explorer" aria-label="API Explorer">API Explorer</a>

            <a ct="Hyperlink" id="_ct0ai0ee" class="cso-hyper-link clsHyperlink cso-text-large cso-text-bold  cso-wrap-text " style="" href="/JWTOutboundSSO.aspx?area=import&amp;newtab=true" target="_blank" title="Imports and Feeds" aria-label="Imports and Feeds">Imports and Feeds</a>

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by newton143** [comment]
Click on a link, opens a new window, Unable to switch to new window. - webdriver timeout exception

   var options = new InternetExplorerOptions();
        options.BrowserAttachTimeout = new TimeSpan(00, 00, 120);
        options.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
        options.EnsureCleanSession = true;
        options.RequireWindowFocus = true;
        IWebDriver driver = new InternetExplorerDriver(options);
        driver.Manage().Timeouts().PageLoad = new TimeSpan(00, 00, 60);
        driver.Navigate().GoToUrl("http://qa01.csod.com");
        string window1 = driver.CurrentWindowHandle;
         //Click on WebElement
       var webelement = driver.FindElement(By.XPath("//a[@title='Imports and Feeds']"));
       driver.ExecuteJavaScript("arguments[0].click();", webelement);
       WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));
        wait.Until(wnd => wnd.WindowHandles.Count == (previousWinCount + 1));
        string window2 = "";
        var windowHandles = driver.WindowHandles;
        foreach (string handle in windowHandles)
        {
            if (handle != window1)
            {
                window2 = handle;
                break;
            }
        }
        driver.SwitchTo().Window(window2);    //This line throws timeout exception

##Exception Details
{"The HTTP request to the remote WebDriver server for URL http://localhost:45255/session/b5fc19b8-510c-4b9d-bbc7-7d97c3624c60/window timed out after 60 seconds."}

##StackTrace:
at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteTargetLocator.Window(String windowHandleOrName)
at FireFoxDriver.Program.Main(String[] args) in C:\Temp\FireFoxDriver\FireFoxDriver\Program.cs:line 69
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()

##InnerException:
{"The operation has timed out"}

**Comment by dmahmudiev** [comment]
I'm seeing a similar issue on Firefox 55.0.3 (on a Mac) when closing a modal. After closing the modal I get a failure at: @driver.switch_to.window(...) when the web driver tries to go back to the original window.

**Comment by barancev** [comment]
@dmahmudiev Please raise a new issue and provide a reproduction scenario.

**Comment by barancev** [comment]
http://qa01.csod.com is not externally available. Please provide a sample page to reproduce the issue on.

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.

**Comment by sowmyasreeni** [comment]
Hi,

If anyone has solved the click() issue please help me as am stuck with this issue for firefox.

Scenario:
1) Click() element 
2.) New windows opens

issue:
new window opens. but timeout in click() itself.
