### ISSUE TITLE
function click, select throw "Timeout loading page after 1ms" exception

### ISSUE THREAD

**Issue by phamluk** [SeleniumHQ/selenium#4544]
## Meta -
OS:  win 7, win 10

Selenium Version:  3.5.0, 3.5.1, 3.5.2

Browser:  firefox

Browser Version:  54 , 55

## Expected Behavior -
perform sucessfull and return without exception
## Actual Behavior -
return -1 and throw exception "org.openqa.selenium.TimeoutException: Timeout loading page after 1ms"
## Steps to reproduce -
_WebElement list = driver.findElement(By.id("list"));
List<WebElement> eles = list.findElements(By.tagName("option"));
eles.get(0).click();_

or 
_WebElement list = driver.findElement(By.id("list"));
Select select = new Select(list);
select.selectByIndex(0);_

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, no reproduction scenario provided.
