### ISSUE TITLE
touch.flick implemented not properly in ruby bindings

### ISSUE THREAD

**Issue by oleksiybondar** [SeleniumHQ/selenium#4549]
## Meta -
OS:  any
Selenium Version:  3.4.4
Browser:  any

## Steps to reproduce -

```
require 'selenium-webdriver'

username = "please put your upwork login here"
password = "please put your upwork password here!"

mobile_emulation = { "deviceName" => "Nexus 5" }
caps = Selenium::WebDriver::Remote::Capabilities.chrome(
    "chromeOptions" => { "mobileEmulation" => mobile_emulation })
driver = Selenium::WebDriver.for :chrome, desired_capabilities: caps
driver.extend Selenium::WebDriver::DriverExtensions::HasTouchScreen

driver.get "https://www.upwork.com/"

# go to login
# open a menu
e = driver.find_element css: '.right-off-canvas-toggle.menu-icon.pull-right'
driver.touch.single_tap(e).perform
# navigate to login
sleep 1
e = driver.find_element xpath: '/html/body/div[1]/div/header[1]/div[2]/aside/nav/ul/li[7]/a'
driver.touch.single_tap(e).perform
# fill user_name and password
e = driver.find_element id: 'login_username'
e.send_keys username

e = driver.find_element id: 'login_password'
e.send_keys password

e = driver.find_element xpath: '//*[@id="layout"]/div[2]/div/form/div[8]/button'
driver.touch.single_tap(e).perform


sleep 10
e = driver.find_element xpath: '//body/ion-nav-view'
# swipe left to unlock a menu
driver.touch.flick(e, Integer(e.rect.width * (-0.75)), 0, 'normal').perform
```
this code will fails with next exception:
```
in `<top (required)>': unknown error: 'speed' must be a positive integer (Selenium::WebDriver::Error::UnknownError)
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64)
```
if you modify a  last line like 
`driver.touch.flick(e, Integer(e.rect.width * (-0.75)), 0, 'fast').perform`
it will work but extremely slow since in this case speed will be 1 pixel per second
since
```
module Selenium
  module WebDriver
    class TouchScreen
      FLICK_SPEED = {normal: 0, fast: 1}.freeze
```

## Solution -
replace flick speed values
```
module Selenium
  module WebDriver
    class TouchScreen
      FLICK_SPEED = {normal: 50, fast: 100}.freeze
```
and another thing is to allow user to pass integer values 
because current implementation does not allow to do so
see original code
```
when 4
          element, xoffset, yoffset, speed = args

          assert_element element
          flick_speed = FLICK_SPEED[speed.to_sym]

          unless flick_speed
            raise ArgumentError, "expected one of #{FLICK_SPEED.keys.inspect}, got #{speed.inspect}"
          end

          @bridge.touch_element_flick element.ref, Integer(xoffset), Integer(yoffset), flick_speed
```

so it could be modified like
```
when 4
          element, xoffset, yoffset, speed = args

          assert_element element
          flick_speed =  speed.is_a?(Numeric) && speed > 0 ?
                                      Integer(speed) :
                                      FLICK_SPEED[speed.to_sym]

          unless flick_speed
            raise ArgumentError, "expected one of #{FLICK_SPEED.keys.inspect}, got #{speed.inspect}"
          end

          @bridge.touch_element_flick element.ref, Integer(xoffset), Integer(yoffset), flick_speed
```

P.S. sorry for a miss format but I think I'm already found the root of the issue and I'm able to overcome this difficulty with a monkey patch but its not best solution...

**Comment by p0deje** [comment]
Interesting. I get it that it's something Chrome-specific, though I'm not 100% sure about that. The current spec defines actions (https://w3c.github.io/webdriver/webdriver-spec.html#actions) which can also be used to simulate swipes, but I'm not even sure what are the drivers supporting this.

If this is supported only by Chrome, I think we should be good to just allow passing the speed. I'm adding labels for all the bindings because we don't allow it anywhere. For example, Java bindings allow normal, fast and slow speed.

**Comment by p0deje** [comment]
I think I've fixed the problem in master.

So now you can pass speed explicitly (7a197cce08e47d052112e1339fc4cddea6fc1ea8):

```ruby
driver.touch.flick(e, 0, 10, 50).perform
```

Also, I've made a couple of additional changes so you no longer need to do this:

```ruby
driver.extend Selenium::WebDriver::DriverExtensions::HasTouchScreen
```

Chrome driver is now extended with HasTouchScreen (cd10cae4ca1fba833948cad3e12507f338c2208e).

And you should no longer see deprecation warnings about mouse/keyboard when using `driver.touch` (3e1bac65e8b09a4e300ddde8b89ff2ce5f75c008).

Let me know if that doesn't work for you.
