### ISSUE TITLE
How can I use Selenium IDE with new Firefox version?

### ISSUE THREAD

**Issue by ionakathryn** [SeleniumHQ/selenium#4552]
OS:  Mac 
Selenium Version:  IDE 
Browser:  Firefox

I am wondering if there is a way to install the Selenium IDE to the new Firefox version? I can revert back to previous Firefox versions and download the IDE but don't want to do this due to security issues. Not an issue but a question on how to download the Selenium IDE. 

Thanks

Browser Version:  
55.0

**Comment by lmtierney** [comment]
Duplicate of #4406

**Comment by SeleniumIDErevival** [comment]
you can use CyberFox to keep Selenium IDE

**Comment by prasanna532** [comment]
i found one ide. Katalon
