### ISSUE TITLE
while fetching title of a window to perform switch i am getting "openqa.selenium.UnhandledAlertException" in Firefox

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#4553]
## Meta -
OS:  Windows 10
Selenium Version:  3.4.0
Browser:  Firefox 55.0.2
Gecko driver : 0.18.0

I am having a website page which contains a link, on clicking on the link will open a modal dialog.
I have to click on a link inside that modal dialog, while click on link in modal dialog will open another window which will cause to open a window authentication popup, after submitting credentials window page will get displayed.
I have to switch to new window opened after clicking a link in modal dialog, for that when i check for window title as  "title value ==driver.title()" it throws "openqa.selenium.UnhandledAlertException" error

Expected Behavior -
Should be able to switch to new window  after selecting appropriate window title

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by shiyaf** [comment]
Issue is happening because of window authentication pop up, when it pop-up s I am entering credentials and clicking OK button using MS UI method . After that when I try to perform any action using Selenium method it throws above said "unhandledalert" exception.
Here culprit is window authentication popup which is handled by UI method ,
So it would be great if I get any selenium method to handle this window authentication popup

**Comment by barancev** [comment]
It's going to implemented after W3C WebDriver specification reaches Level 2: https://github.com/w3c/webdriver/issues/385
