### ISSUE TITLE
W3C Spec Compliance: deprecate getPlatform and replace with getPlatformName

### ISSUE THREAD

**Issue by matthewdoerksen** [SeleniumHQ/selenium#4561]
## Meta -
OS:  All
Selenium Version:  3.5.2 (head)
Browser:  All
Browser Version:  All

## Steps to reproduce -
N/A

## Work to do
Deprecate Capabilities.getPlatform() and replace with getPlatformName() - push for users to use the W3C proper method.
Migrate all internal usages of getPlatform to the new getPlatformName so as to provide a W3C consistent experience.

**Comment by amirhmd** [comment]
Hello guys,

I am very new to os and selenium, but this one seems to me a refactoring of the code. am I right? is this a good one to start with?

BR
