### ISSUE TITLE
Jenkins doesn't execute WebDriver based test

### ISSUE THREAD

**Issue by plaidshirtakos** [SeleniumHQ/selenium#4563]
## Meta -
OS:  
Ubuntu 16.04.3 LTS
Selenium Version:  
2.53.1
Browser:  
Firefox 55.0 (64-bit)

## Expected Behavior -
This test is to upload files to a website, so it opens file chooser dialog. I added it to Jenkins, build is successful, but tests are failing.

## Actual Behavior -

> Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@2437c6dc
> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
> No protocol specified
> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Could not connect: Connection refused
> Error: cannot open display: :0

**Comment by Drimix20** [comment]
I assume that tests are running on jenkins slave. Do you have running selenium server on port 7055 on the same jenkins slave? Because it is saying that "Unable to connect to host 127.0.0.1 on port 7055". You should specify public ip address of selenium server instead of localhost if you have it running on different node.

**Comment by plaidshirtakos** [comment]
@Drimix20 : There is only 1 node and this is the master Jenkins node.

**Comment by barancev** [comment]
Legacy Firefox driver (that's default in 2.53) does not support Firefox 55.
Is there a reason you don't upgrade to Selenium 3 (3.5 at the moment) and geckodriver?

**Comment by plaidshirtakos** [comment]
As I know, it is different not only in geckodriver.

**Comment by barancev** [comment]
If you want to use 2.53 you have to downgrade Firefox to ESR 45
