### ISSUE TITLE
Selenium 3.5.2-Java : getPlatform() method and map.get("platform") method returns different results for capability Platform through geckodriver

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4565]
## Meta - `getPlatform()` method and `map.get("platform")` method returns different results for capability `Platform` through geckodriver.

**`cap.getPlatform().toString()`** returns `Platform` as **`XP`** while **`map.get("platform")`** returns `Platform` as **`ANY`**

Through [**`895`**](https://github.com/mozilla/geckodriver/issues/895) @andreastt confirmed it's a Java Client issue.

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.2 (Java)

Selenium Binding: Java

GeckoDriver Version: 0.18.0

Browser: Mozilla Firefox

Browser Version: 55.0.2

## Steps to reproduce -
Minimal Code Block:

	package demo;

	import java.util.Map;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_Platform
	{
		public static void main(String[] args) 
		{
			String attribute = "platform";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			System.out.println("Platform is : "+cap.getPlatform().toString());
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value : "+ value);
		}
	}

Console Output:

```
Platform is : XP
Key : platform Value : ANY
```

**Comment by barancev** [comment]
https://github.com/mozilla/geckodriver/issues/902

**Comment by barancev** [comment]
Appears to be a client side issue, reopening.

**Comment by Debanjan-B** [comment]
@barancev  I am sorry, I think initially I tagged a wrong issue in the description. Now corrected it. Thanks
