### ISSUE TITLE
Automating mobile Browser (Chrome) using Selenium WebDriver

### ISSUE THREAD

**Issue by jimmyjavid** [SeleniumHQ/selenium#4568]
Hi,
 I need to automate webBrowser on mobile with Selenium.
  In other words in my scenario I can't use Appium . I am solely dependent on Selenium.
  So I need to design code where I can automate mobile browser without using Appium or launching Appium Server.
 Is there any way where I can automate mobile browser without using APPIUM???

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
