### ISSUE TITLE
Selenium 3.5.2-Java :  Need methods to retrieve the new capabilities with a "moz:" prefix through Java Client.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4569]
## Meta -  Need methods to retrieve the new capabilities with a "moz:" prefix through Java Client. As of now we are unable to retrieve the capabilities like `"moz:experimental-webdriver"` through Java Client.

As per WebDriver [**`W3C Candidate Recommendation 24 August 2017`**](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities) Mozilla could elect to hide new features behind capabilities with a "moz:" prefix. 

In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities#x7.-capabilities):
> Mozilla could elect to hide new features behind capabilities with a "moz:" prefix:

Example:
```
{
	"browserName": "firefox",
	"browserVersion": "1234",
	"moz:experimental-webdriver": true
}
```
As of now Java client have the implementation for `browserName`, `browserVersion` and `platform`.
Java client needs to implement methods to retrieve the new capabilities with a "moz:" prefix like `"moz:experimental-webdriver"`

----------------------------------

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.2 (Java)

Selenium Binding: Java

GeckoDriver Version: 0.18.0

Browser: Mozilla Firefox

Browser Version: 55.0.2

## Steps to reproduce -
Minimal Code Block:

	package demo;

	import java.util.Map;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_Experimental
	{
		public static void main(String[] args) 
		{
			String attribute = "moz:experimental-webdriver";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			System.out.println("Browser Name is : "+cap.getBrowserName().toLowerCase());
			System.out.println("Platform is : "+cap.getPlatform().toString());
			System.out.println("Browser version is : "+cap.getVersion().toString());
			//Need a get() method for "moz:experimental-webdriver"
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value : "+ value);
		}
	}

Console Output:

```
Browser Name is : firefox
Platform is : XP
Browser version is : 55.0.2
Key : moz:experimental-webdriver Value : null
```

**Comment by barancev** [comment]
"moz:experimental-webdriver" is not a real capability name, it's just an example.

Try driver.getCapabilities().getCapability("moz:headless") or "moz:profile"

**Comment by Debanjan-B** [comment]
Thanks a ton @barancev for your guidance. Your suggestion works like a charm.

    Mozilla Profile is : C:\Users\AtechM_03\AppData\Local\Temp\rust_mozprofile.cW0numUC1Uyb
    Mozilla Profile is : C:\Users\AtechM_03\AppData\Local\Temp\rust_mozprofile.cW0numUC1Uyb
   Headless Mozilla ? true
   Headless Mozilla ? true

**Comment by Debanjan-B** [comment]
@barancev As per the W3C specs `Mozilla could elect to hide new features behind capabilities with a "moz:" prefix`. 

So can there be a possibility that there exists more capabilities which we can be passed through the WebDriver instance other then the one reflected within:

    CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0.3","platformName":"windows_nt","platformVersion":"6.2","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":5896,"moz:profile":"C:\\Users\\ATECHM~1\\AppData\\Local\\Temp\\rust_mozprofile.WeR5sAyNrxyz","moz:accessibilityChecks":false}

If so how can we come to know about those capabilities?

Thanks

**Comment by jimevans** [comment]
I'm not entirely sure what you're asking, @Debanjan-B. If you want to know what capabilities you can pass to geckodriver, you can pass any of the standard capabilities listed by [the W3C Specification](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities), or capabilities supported using `moz:firefoxOptions`. The latter are defined by Mozilla, and are documented in [the geckodriver project](https://github.com/mozilla/geckodriver/blob/master/README.md). Remember, just because you get capabilities back from a session does **not** mean they can be specified when requesting a session.

**Comment by Debanjan-B** [comment]
@jimevans Thanks a lot. Your comment `Remember, just because you get capabilities back from a session does not mean they can be specified when requesting a session` does answers my query. 

But as I try to understand the implementation of the capabilities as per [W3C Specification](https://w3c.github.io/webdriver/webdriver-spec.html#capabilities), can we conclude that the capabilities mentioned in [geckodriver/README.md](https://github.com/mozilla/geckodriver/blob/master/README.md#firefox-capabilities) are the only capabilities which as an end user we can configure as per our requirement?

**Comment by jimevans** [comment]
Yes, that's exactly right. The only `moz:` capabilities that a user can configure are those documented by Mozilla. The readme is their chosen mechanism of documentation. Therefore, any other extension capabilities are, by definition, undocumented, and relying on them in any way is a bad idea.

**Comment by Gudzo** [comment]
@jimevans @barancev @Debanjan-B 
Hi guys, sorry it's an old thread, but I am stuck with headless Firefox. Well actually the problem is not with Firefox headless, I can make Firefox run in headless mode, the problem is I can't manage to run it in headless mode when I am using GeckoDriverService, here is a piece of my code:

public static FirefoxDriver getFirefox(Map map) throws IOException {
        System.setProperty("webdriver.gecko.driver","/root/firefox_driver/geckodriver");
        
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("--headless", true);
        
        FirefoxBinary firefoxBinary = new FirefoxBinary();
        firefoxBinary.addCommandLineOptions("--headless");

        FirefoxOptions options = new FirefoxOptions();
        options.setBinary(firefoxBinary);
        options.setHeadless(true);
        
        GeckoDriverService service;
        GeckoDriverService.Builder builder = new GeckoDriverService.Builder();
        service = builder.usingAnyFreePort()
                .withEnvironment(map)
                .usingFirefoxBinary(firefoxBinary)
                .build();

        service.start();

        return new FirefoxDriver(service);
    }

The problem is that when I use GeckoDriverService, Firefox always runs in GUI mode, if I don't start the server with GeckoDriverService headless is not a problem, it's easy. And if you are asking why I am using GeckoDriverService is because I need it to track network requests and get API calls.

Regards,
Filip

**Comment by barancev** [comment]
@Gudzo You're welcome to the mail-list or IRC or Slack to discuss this topic, no need to hijack a closed issue that is not even slightly related to your question.
