### ISSUE TITLE
Selenium 3.5.0: Java and Python client sending different number of capabilities to Marionette

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4571]
## Meta - Selenium 3.5.0: Java and Python client sending different number of capabilities to Marionette

When `capabilities` are retrieved through **Java** Client **14** capabilities are retrieved from the **`Map.Entry<String, ?>`** object  through **`Capabilities`** class object by default.

When `capabilities` are retrieved through **Python 3.6.1** Client **12** capabilities are retrieved from the **`Dictionary`** object by default.

--------------------------------------------------

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.2

Selenium Binding: Java & Python 3.6.1

GeckoDriver Version: 0.18.0

Browser: Mozilla Firefox

Browser Version: 55.0.2

## Steps to reproduce -

Minimal Java Code:

```
package demo;

import java.util.Map;
import java.util.logging.Level;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;

public class WEBDRIVER_CAPABILITIES_MAP
{
	public static void main(String[] args) 
	{
		System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(Level.FINEST);
		WebDriver driver =  new FirefoxDriver(options);
        Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
        Map<String, ?> map = cap.asMap();
        for ( Map.Entry<String, ?> entry : map.entrySet()) 
        {
            System.out.println(entry.getKey() + " value is " + entry.getValue());
        }
        driver.quit();
 	}
}

```

Console Output:

```
moz:profile value is C:\Users\ATECHM~1\AppData\Local\Temp\rust_mozprofile.CrLgYK3noEc9
rotatable value is false
timeouts value is {implicit=0, pageLoad=300000, script=30000}
pageLoadStrategy value is normal
platform value is ANY
specificationLevel value is 0
moz:accessibilityChecks value is false
acceptInsecureCerts value is false
browserVersion value is 55.0.2
platformVersion value is 6.2
moz:processID value is 3604
browserName value is firefox
javascriptEnabled value is true
platformName value is windows_nt
```

Minimal Python Code:

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'

options = Options()
options.binary = binary
driver = webdriver.Firefox(log_path='./Logs/WEBDRIVER_capabilities.log', firefox_options=options, executable_path="C:\\Utility\\BrowserDrivers\\geckodriver.exe")
my_dict = driver.capabilities
for key,val in my_dict.items():
    print (key, "=>", val)
driver.quit();
```

Console Output:

```
acceptInsecureCerts => True
browserName => firefox
browserVersion => 55.0.2
moz:accessibilityChecks => False
moz:processID => 3468
moz:profile => C:\Users\ATECHM~1\AppData\Local\Temp\rust_mozprofile.87dcBfBxqQdP
pageLoadStrategy => normal
platformName => windows_nt
platformVersion => 6.2
rotatable => False
specificationLevel => 0
timeouts => {'implicit': 0, 'pageLoad': 300000, 'script': 30000}
```

**Python 3.6.1 Client clearly misses `platform` and `javascriptEnabled` capability.**

**Comment by lmtierney** [comment]
`platform` and `javascriptEnabled` are not `w3c` capabilities, so they aren't sent.

**Comment by lmtierney** [comment]
Please, instead of opening so many issues, consider stopping by IRC channel `#selenium` on freenode or asking questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

**Comment by Debanjan-B** [comment]
Thanks @lmtierney for suggesting the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). I am in sync with the geckodriver group. @andreastt had been phenomenal in explaining us and we are updated with the W3C capability as per the specs.

As the implementations of webdriver (Java/Python) doesn't have a standard Spec, to help the end-user rather Closing the issue I think you could have addressed it through a changelist.
