### ISSUE TITLE
Selenium 3.5.0 - Python - set_page_load_timeout() issue

### ISSUE THREAD

**Issue by gjthompson1** [SeleniumHQ/selenium#4572]
## Meta -
OS:  
macOS Sierra 10.12.2
Selenium Version:  3.5
Driver:  Chomedriver 2.31
Python: 3.6.1

[](https://stackoverflow.com/questions/45850978/chromedriver-browser-timeout-go-back-to-previous-page-error-python-selenium/45867310#45867310)

## Expected Behavior -

Expect driver to timeout, return control, and drop the exception.

## Actual Behavior -

Driver hits timeout, return control, but further .get() return timeout error.

## Steps to reproduce -

This does not work

```
from selenium import webdriver

driver = webdriver.Chrome(executable_path='../helpers/drivers/chromedriver_2_31')
driver.set_page_load_timeout(0.1)

driver.get('http://www.abc.com')

driver.set_page_load_timeout(10)
driver.get('http://www.abc.com')
```

This Does 

```
driver = webdriver.Chrome(executable_path='../helpers/drivers/chromedriver_2_30')
driver.set_page_load_timeout(0.1)

driver.get('http://www.abc.com')

driver.set_page_load_timeout(10)
driver.get('http://www.abc.com')
```

[https://stackoverflow.com/questions/45850978/chromedriver-browser-timeout-go-back-to-previous-page-error-python-selenium/45867310#45867310](https://stackoverflow.com/questions/45850978/chromedriver-browser-timeout-go-back-to-previous-page-error-python-selenium/45867310#45867310)

**Comment by 52Heartz** [comment]
Why closed?

**Comment by lmtierney** [comment]
Please don't comment on old closed issues. If you have a similar issue, please open a new one with a [concise reproducible test case](http://sscce.org/).
