### ISSUE TITLE
"error":"unknown command","message":"GET / did not match a known command"

### ISSUE THREAD

**Issue by plaidshirtakos** [SeleniumHQ/selenium#4573]
## Meta -
OS:
Windows 8.1
Selenium Version:
3.5.2
Browser:
Firefox 55.0.2 (64-bit)

## Expected Behavior -
This code should open a webpage in browser:
```
System.setProperty("webdriver.firefox.bin", C:\\Portable\\firefox.exe);
System.setProperty("webdriver.gecko.driver", "C:\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();
driver.navigate().to(url);
```

## Actual Behavior -
Default webpage loaded in browser and I see the following on given port:

> {"value":{"error":"unknown command","message":"GET / did not match a known command","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x4319fd - <no info>\n   4:           0x425ca5 - <no info>\n   5:           0x407eba - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x417655 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:     0x7ffdddfa13d2 - BaseThreadInitThunk"}}

**Comment by barancev** [comment]
And what's the geckodriver version?

**Comment by plaidshirtakos** [comment]
Geckodriver version is 0.18.0.

**Comment by barancev** [comment]
Init the driver as
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(Level.ALL);
driver = new FirefoxDriver(options);
```
and attach the complete log here.

**Comment by plaidshirtakos** [comment]
New information:

> 1503647326090	geckodriver::marionette	TRACE	  connection attempt 0/600
> 1503647328211	geckodriver::marionette	TRACE	  connection attempt 1/600
> 1503647330321	geckodriver::marionette	TRACE	  connection attempt 2/600
> 1503647332471	geckodriver::marionette	TRACE	  connection attempt 3/600
> 1503647334611	geckodriver::marionette	TRACE	  connection attempt 4/600
> 1503647336756	geckodriver::marionette	TRACE	  connection attempt 5/600
> 1503647338881	geckodriver::marionette	TRACE	  connection attempt 6/600
> 1503647341037	geckodriver::marionette	TRACE	  connection attempt 7/600
> 1503647343188	geckodriver::marionette	TRACE	  connection attempt 8/600
> 1503647345313	geckodriver::marionette	TRACE	  connection attempt 9/600
> 1503647347425	geckodriver::marionette	TRACE	  connection attempt 10/600
> 1503647349538	geckodriver::marionette	TRACE	  connection attempt 11/600

**Comment by barancev** [comment]
Please attach the complete log.

**Comment by barancev** [comment]
```
System.setProperty("webdriver.firefox.bin", C:\\Portable\\firefox.exe);
System.setProperty("webdriver.gecko.driver", "C:\\geckodriver.exe");
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(Level.ALL);
WebDriver driver = new FirefoxDriver(options);
driver.navigate().to(url);
```

**Comment by plaidshirtakos** [comment]
I waited for 200 attempts, but I see nothing else nor on given port nor in IDE log.

> [TestNG] Running:
>   C:\Users\kovacs\.IdeaIC2017.2\system\temp-testng-customsuite.xml
> 1503648702992	geckodriver	INFO	geckodriver 0.18.0
> 1503648703008	geckodriver	INFO	Listening on 127.0.0.1:18041
> 1503648703758	geckodriver::marionette	INFO	Starting browser C:/Portable/firefox.exe with args ["-marionette"]
> 1503648705807	geckodriver::marionette	TRACE	  connection attempt 0/600
> 1503648707948	geckodriver::marionette	TRACE	  connection attempt 1/600
> 1503648710073	geckodriver::marionette	TRACE	  connection attempt 2/600
> 1503648712203	geckodriver::marionette	TRACE	  connection attempt 3/600
> ...

**Comment by barancev** [comment]
Well, where did you get the error message quoted in the original post? Does it disappear?

**Comment by plaidshirtakos** [comment]
No, those are the same as earlier on port 18041.

**Comment by barancev** [comment]
So please provide the complete log, including the error message and everything else.

**Comment by barancev** [comment]
The log should start from a line that looks like
```
1503648702992	geckodriver	INFO	geckodriver 0.18.0
````
and end with the error like
```
{"value":{"error":"unknown command","message":"GET / did not match a known command","stacktrace":"stack backtrace:\n 0: 0x4bb74f - \n 1: 0x4bbea9 - \n 2: 0x43ce8d - \n 3: 0x4319fd - \n 4: 0x425ca5 - \n 5: 0x407eba - \n 6: 0x6d95b9 - \n 7: 0x417655 - \n 8: 0x6d38b3 - \n 9: 0x7ffdddfa13d2 - BaseThreadInitThunk"}}
```
mentioned in the original report.

**Comment by plaidshirtakos** [comment]
So, the first line is in my previous post and it appears on IDE's console.
Second line is on given port.

**Comment by barancev** [comment]
I don't understand what do you mean by "appears on the given port" :(
Please provide all available logs and explain where did you get them from.

**Comment by plaidshirtakos** [comment]
Given port:
1503648703008	geckodriver	INFO	Listening on 127.0.0.1:18041
When I open it, I see that JSON formatted information.

**Comment by barancev** [comment]
Oh! It's API endpoint, of course you can't navigate to this address in browser, it's nonsence.

**Comment by plaidshirtakos** [comment]
Yes, that is OK, but it can't open this url during execution: `driver.navigate().to(url);`

**Comment by barancev** [comment]
Please report the issue to geckodriver tracker: https://github.com/mozilla/geckodriver/issues
Not sure if they support portable firefox builds.
