### ISSUE TITLE
when I click a button which will close the current window , no response from my java program

### ISSUE THREAD

**Issue by k19810703** [SeleniumHQ/selenium#4575]
## Meta -
OS:  MAC

Selenium Version:  3.5.2

Browser:  firefox

Browser Version:  55.0

geckodriver : 0.18

here is my code:
WebDriver wd = new FirefoxDriver();
  wd.manage().window().maximize();
  wd.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
  wd.navigate().to("app url");
  //click to open new window
  wd.findElement(By.xpath(".//*[@id='contentsArea']/div[2]/a")).click();
  //switch to new window
  Thread.sleep(3000);
  Set<String> handles = wd.getWindowHandles();
  for (String s : handles) {  
      wd.switchTo().window(s);
        String crtvalue=wd.getCurrentUrl();
        if (crtvalue.contains("new window url")) {  
          wd.manage().window().maximize();
            break;  
        }
    };
  //click the button to close new window
  wd.findElement(By.xpath(".//*[@id='contentsArea']/div[3]/input")).click();
  System.out.println("end");

I supposed to saw end in console but it never shows and java program didn't end.

last line in console log:
1503655968648	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "2147483659"

**Comment by barancev** [comment]
See https://github.com/mozilla/geckodriver/issues/611
