### ISSUE TITLE
moveToElement() not working with dynamic popups (dotnet)

### ISSUE THREAD

**Issue by curtisy1** [SeleniumHQ/selenium#4576]
## Meta -
OS:  Windows 10
Selenium Version:  Webdriver v3.5.1, Firefox.Webdriver v0.18.0
Browser:  Firefox Nightly
Browser Version:  57.0a1 (2017-08-24) (64-Bit)

## Expected Behavior -
Performing a ContectClick action on a DataTable appends a contextmenu with elements to the clicked tr. MoveToElement() should move to the specified element that was appended before

## Actual Behavior -
MoveToElement fails with a StaleElementReference Exception (see SeleniumLog_MoveToElement), whereas FindElements() returns the elements successfully. Also MoveByOffset() and then clicking on the offset is working as expected (see SeleniumLog_MoveByOffset)

## Steps to reproduce -
Rightclick on a DataTable element (or most likely also anything else), that triggers a custom popup (not the standard Firefox contextmenu). Call actions.MoveToElement(elementThatGotAppendedByPopup).

A snippet of the actual HTML looks like this:
```
<table>
    <tbody>
        <tr>
            <div class="ti_popup" style="left: 377px; top: 113.5px; display: block;">
                <div class="ti_popup_item"><span class="glyphicons glyphicons-copy" style="margin-right:6px"></span>Ausschneiden</div>
                <div class="ti_popup_item"><span class="glyphicons glyphicons-git-compare" style="margin-right:6px"></span>Drehen</div>
                <div class="ti_popup_item"><span class="halflings halflings-trash" style="margin-right:6px"></span>Auftrag entfernen</div>
             </div>
        </tr>
    </tbody>
```

And the actual test code excerpt that's failing looks like this:
```
action.ContextClick(Browser.Driver.FindElement(By.XPath(Tours.TableElementConstructor + "/tr[2]/td[5]"))).Build().Perform();
// this is finding the correct elements
var popup = Browser.Driver.FindElements(By.CssSelector("div.ti_popup_item"));
// not working version
/*action.MoveToElement(popup[1]).Click().Build().Perform();*/
// working version
action.MoveByOffset(10, 40).Click().Build().Perform();
```
TableElementConstructor being a const string of: "//table[@Id='DataTables_Table_0']/tbody"

Trace logs are attached below. Please tell me if you need any more information.

[Logs.zip](https://github.com/SeleniumHQ/selenium/files/1251714/Logs.zip)

**Comment by barancev** [comment]
StaleElementReference exception is a legit response if some parts of the target page are updated that can happen as a result of moving element or some other actions.

**Comment by curtisy1** [comment]
That's my point. It's not being moved at all. Basically you right click and have a contextmenu in a fixed place. The contextmenu is a part of the table row (as you can see in the HTML snippet) for as long as you don't perform another click. My assumption was that if FindElements is capable of actually **finding** the elements (e.g. popup has a count of 3 in my example), right before performing the MoveToElement() action, said action should be able to find it (as nothing else has changed in between. No page updates or moved elements, just the driver trying to locate the element). I also made sure the page is completely loaded before (jquery.active is 0, document.readyState, even a long Thread.Sleep didn't help), so that can't be the issue in my opinion.

**Comment by barancev** [comment]
You can't move the element that was found but is no more present on the page. Implement a different algorithm that does not depend on such page updates.

**Comment by curtisy1** [comment]
> You can't move the element
I'm assuming you're missing a to there. I don't want to **move** the element, I want to **move to** it.

> that was found but is no more present on the page.
I'm fairly certain the element is still there as after MoveToElement a) it's clickable and b) updating the popup variable still results in a count of 3. If you can explain to me how the element is supposed to be removed from the page before the MoveToElement() action (as it's also not working when commenting the FindeElements() out, which I only really need fo that definite example), I'll grately accept the issue as closed. However I fail to see what could make the element disappear when nothing is happening in these steps:
1. ContextClick() appends element to DOM
2. absolutely nothing is happening, but just in case we wait until ajax and javascript is completely loaded (up to a minute)
3. we try to move to the element which results in a staleElementReference exception (when visibly we can still see the popup)

If you point out to me how exactly in these three steps (which is basically all my code does) the element is no more present on the page, I'd be glad. But again, I fail to see where exactly the issue should be on my end of the line.

**Comment by barancev** [comment]
OK, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by curtisy1** [comment]
Alright, thanks. I'll try my best to make a sscce over the weekend.

**Comment by curtisy1** [comment]
Update: After a few tests of my own popup implementation, I found that it **only** doesn't work with my company's popup implementation. I still don't know what exactly causes this but as it's proprietrary code I'm not allowed to share, I'm closing this issue as it seems unrelated to Webdriver.
