### ISSUE TITLE
Error on executing action.MoveToElement in Firefox 

### ISSUE THREAD

**Issue by svetikshark** [SeleniumHQ/selenium#4577]
## Meta -
OS:  
 Windows 
Selenium Version:  
3.5.2
Browser:  
 Firefox beta 56.0b3
  
Browser Version:  
beta 56.0b3
Gecko 0.18
code on c# 

## Expected Behavior -
action.MoveToElement(element).Build().Perform(); should move pointer to element

## Actual Behavior -
exception is thrown

System.ArgumentException : Target element cannot be converted to IWebElementReference
   at OpenQA.Selenium.Interactions.PointerInputDevice.PointerMoveInteraction.ConvertElement()
   at OpenQA.Selenium.Interactions.PointerInputDevice.PointerMoveInteraction.ToDictionary()
   at OpenQA.Selenium.Interactions.ActionSequence.ToDictionary()
   at OpenQA.Selenium.Remote.RemoteWebDriver.PerformActions(IList`1 actionSequenceList)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
@the-automation Raise a new issue and provide a [concise reproducible test case](http://sscce.org/) too

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
