### ISSUE TITLE
workaround requireWindowFocus=true for IE 64bit slow typing does not help after upgrading node to 3.5.2 from 3.4.0

### ISSUE THREAD

**Issue by morgwai** [SeleniumHQ/selenium#4578]
This should be a comment to [#5116](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5116), but I don't have permission to add a comment there.

## Meta -
OS:  Windows 10, 64bit
Selenium Version:  3.5.2
Browser:  Internet Explorer
Browser Version:  11 64-bit

## Expected Behavior -

`capabilities.setCapability("requireWindowFocus", true);` should solve "slow typing" problem on 64bit Internet Explorer described in [#5116](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5116)

## Actual Behavior -

after upgrading node from 3.4.0 to 3.5.2 "slow typing" problem persist even if "requireWindowFocus" is requested.

**Comment by jimevans** [comment]
Not for nothing, but can you explain your aversion to using the 32-bit `IEDriverServer.exe`? After all, it's highly probable that [the process rendering the content in IE is 32-bit anyway](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html?m=1), even on 64-bit Windows.

**Comment by morgwai** [comment]
no aversion at all: that's what I will switch to now, but I thought that developers should be aware of this regression nevertheless :)

**Comment by jimevans** [comment]
Then, because of how actions processing changed from 3.4 to 3.5 for the IE driver, this "workaround", which should never have been propagated as a solution in the first place, no longer works. There is no way to fix this in the architecture of the IE driver. Thank you for the issue report.
