### ISSUE TITLE
geckodriver ignores environment settings using FirefoxBinary#setEnvironmentProperty()

### ISSUE THREAD

**Issue by gerixx** [SeleniumHQ/selenium#4582]
## Meta -
OS:  any

Selenium Version:  3.5.2 Java binding

Browser:  Firefox geckodriver

## Expected Behavior -
Using `FirefoxBinary#setEnvironmentProperty(...)` additional environment variables are set for the firefox process under test.

## Actual Behavior -
Additional environment variables are not set for geckodriver and firefox processes. Root cause seems to be that the environment properties map is not forwarded to the geckodriver Builder instance. 

## Steps to reproduce -
Launch Firefox using `FirefoxBinary `and `FirefoxOptions`:
```
FirefoxBinary binary = new FirefoxBinary();
binary.setEnvironmentProperty("MY_ENV_VAR", "myvalue");
FirefoxOptions options = new FirefoxOptions().setBinary(binary);
FirefoxDriver driver = new FirefoxDriver(options);
```

**Comment by barancev** [comment]
Setting environment variables in FirefoxBinary is deprecated (see 4a919b7).
Users should configure environment using DriverService.withEnvironment method.
```
FirefoxDriver driver = new FirefoxDriver(new GeckoDriverService.Builder()
  .withEnvironment("MY_ENV_VAR", "myvalue").biuld());
```
