### ISSUE TITLE
Session [null] not available and is not among the last 1000 terminated sessions

### ISSUE THREAD

**Issue by FlexiB** [SeleniumHQ/selenium#4585]
## Meta -
OS:  Ubuntu 12.04

Selenium Version:  3.5.2

Browser:  Firefox

Browser Version:  

## Expected Behavior -

I try to execute a test on Firefox with selenograph (contains GridRouter)

## Actual Behavior -
When I execute a test on Firefox, I have this error "Session [null] not available and is not among the last 1000 terminated sessions".

But it's OK when I execute on Chrome,Chrome Headless or IE.

## Steps to reproduce -

Create a grid router.
Configure your Grid Router with a profil.xml that contains firefox.
Execute a test using your Grid Router IP and firefox capabilities.

**Comment by barancev** [comment]
selenograph is not a software created by Selenum team, report the issue to the corresponding tracker. Or provide a reproduction scenario with barebone Selenium server.
