### ISSUE TITLE
Maven build fail when Im run mvn install

### ISSUE THREAD

**Issue by natylok** [SeleniumHQ/selenium#4586]
OS:  
Ubuntu
Selenium Version:  
3.5.2
Browser:  
Chrome

Since selenium has been upgraded to 3.5.2 Im getting the following error when Im trying to run mvn clean install , 

 Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project Automation-Maven: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: Unable to get dependency information for io.appium:java-client:jar:RELEASE: Invalid version for dependency org.seleniumhq.selenium:selenium-java:jar: Range cannot have identical boundaries: [3.5.2,3.5.2]

Please I cant find any solution in other places 

My dependencies :

  <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>3.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <version>2.27</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.52.0</version>
        </dependency>

        <dependency>
            <groupId>com.relevantcodes</groupId>
            <artifactId>extentreports</artifactId>
            <version>2.40.2</version>
        </dependency>

        <dependency>
            <groupId>com.applitools</groupId>
            <artifactId>eyes-common-java</artifactId>
            <version>2.57</version>
        </dependency>

        <dependency>
            <groupId>com.applitools</groupId>
            <artifactId>eyes-sdk-java</artifactId>
            <version>2.24</version>
        </dependency>

        <dependency>
            <groupId>com.applitools</groupId>
            <artifactId>eyes-selenium-java</artifactId>
            <version>2.57</version>
            
                
                    
                    
                
            
        </dependency>

        <dependency>
            <groupId>org.sikuli</groupId>
            <artifactId>sikuli-core</artifactId>
            <version>1.2.2</version>
        </dependency>

        <dependency>
            <groupId>org.sikuli</groupId>
            <artifactId>sikuli-webdriver</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.11</version>
        </dependency>

        <dependency>
            <groupId>org.sikuli</groupId>
            <artifactId>sikuli-api</artifactId>
            <version>1.2.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>mainSanity.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> 
                        <phase>package</phase> 
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
