### ISSUE TITLE
UnhandledAlertException issue with Gecko Driver

### ISSUE THREAD

**Issue by sriramsubramaniyam** [SeleniumHQ/selenium#4588]
I get windows authentication pop up in my webpage upon the launch. I am using Robot() to handle it. Problem is even though the pop up is handled I get the UnhandledAlertException.

To ensure if the issue is with the way I am handling pop up, I commented the code handling the pop up during debug, handled it manually in the application  and still UnhandledAlertException was thrown at- 
if (driver.getTitle().trim().equalsIgnoreCase(title))

Here is the snipped of the code am using to handle the pop up-

	public void VerifyTitle(String title, String SiteCoreSpain_URL, String UserId, String Password)  {
					
		try {					
			EnterUserId(UserId);
			Thread.sleep(1000);
			EnterPassword(Password);				
			Thread.sleep(1000);					
			if (driver.getTitle().trim().equalsIgnoreCase(title)){				
				System.out.println("PASS");		
			}
			else				
				System.out.println("FAIL");
			
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	
         public void EnterUserId(String userId) throws IOException{
		
		try{
	             //create robot for keyboard operations
	            Robot rb = new Robot();	    
         	    rb.delay(5000);
         	    //Enter user name by ctrl-v
	            StringSelection username = new StringSelection(userId);	            
                    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(username, null);       	            
                    PressV();
    	            PressTAB();
                    System.out.println("user id entered");
         	    //wait
	            rb.delay(5000);	    
		}catch (Exception e) {
			e.printStackTrace();	
	               System.out.println("user id not entered");
		}
	}
	
	public void EnterPassword(String password) throws IOException{
	try {    
	     //create robot for keyboard operations
	     Robot rb = new Robot(); 
	     rb.delay(5000); 
             //Enter password by ctrl-v
	    StringSelection pwd = new StringSelection(password);
	    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(pwd, null);
	    PressV();
            PressTAB();           
	    PressENTER();	    
            System.out.println("Password entered");
             //wait
	    rb.delay(5000);	    
	    }catch (Exception e) {
		e.printStackTrace();	
	        testLogger.log(driver, "Password has not been entered");
	    }	
	}
	
	public void PressTAB() throws AWTException
	{
		try{
			Robot robot = new Robot();
			robot.keyPress(KeyEvent.VK_TAB);
			robot.keyRelease(KeyEvent.VK_TAB);
		}catch(AWTException e){
			e.printStackTrace();
		}	
		
	}
	
	public void PressV() throws AWTException
	{
		try {
			Robot robot = new Robot();		
			robot.keyPress(KeyEvent.VK_CONTROL);
			robot.keyPress(KeyEvent.VK_V);
			robot.keyRelease(KeyEvent.VK_V);
			robot.keyRelease(KeyEvent.VK_CONTROL);
		}catch(AWTException e){
			e.printStackTrace();
		}
	}
	
	public void PressENTER() throws AWTException{
		try{
			Robot robot = new Robot();
			robot.keyPress(KeyEvent.VK_ENTER);
			robot.keyRelease(KeyEvent.VK_ENTER);
		}catch(AWTException e){
			e.printStackTrace();
		}
		
	}
	}

It works fine with Chromedriver. But throws exception for Gecko driver. 
Firefox version 55.0.3
I am using Selenium Webdriver with Java and TestNG framework.

**Comment by barancev** [comment]
Please report this issue to geckodriver's tracker: https://github.com/mozilla/geckodriver/issues

**Comment by sriramsubramaniyam** [comment]
@barancev Thank you. Done it already but I didn't know how to close it here.
