### ISSUE TITLE
firefox driver "webdriver.log.file" system property is ignored (no log file created)

### ISSUE THREAD

**Issue by bartoszkaczorek** [SeleniumHQ/selenium#459]
Hi,

The issue occurs when trying dump javascript console logging to file while using firefox and selenium standalone server. I was trying to follow official wiki page and added "webdriver.log.file" system property when starting selenium server i.e.:

```
java -jar selenium-server-standalone.jar -Dwebdriver.log.file=C:\myfile.log
```

After running selenium standalone server I lunch my tests (using javascript intern framework) - the tests are running fine, but the problem is that no log file is created and the "webdriver.log.file"  system property seems to be ignored.

I was able to get log file for firefox stdout/stderr using "webdriver.firefox.logfile" property, and I was also successful with chrome log files using "webdriver.chrome.logfile" and "webdriver.chrome.verboseLogging" system properties, but still for some reason it does not work with "webdriver.log.file".

Wiki page I was following:
https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver

My environment details are:
Firefox version: 37.0.1
Selenium standalone server version: 2.45.0
Platform: Windows 7

Thanks,
Bart

**Comment by Jarob22** [comment]
Uploading the .patch file as a .zip as github doesnt accept .patch files in comments. This fixes the wiki that erroneously says the property is webdriver.log.file

[0001-changing-the-referenced-property-from-webdriver.log..zip](https://github.com/SeleniumHQ/selenium/files/389490/0001-changing-the-referenced-property-from-webdriver.log.zip)

**Comment by Jarob22** [comment]
@barancev Please see above comment for the wiki fix for this issue.

**Comment by barancev** [comment]
Yes, there is no such a property. As well as there is no such a capability too. It's the name of a Firefox preference. Removed it from the wiki.
