### ISSUE TITLE
Best practices for developers to increase testability of web apps for QA

### ISSUE THREAD

**Issue by sharathpoluru** [SeleniumHQ/selenium#4592]
## Meta - Best practices for developers to increase testability of web apps for QA. I am trying to prepare standards to ensure what needs to be included/ standard to be included to help QA in identifying objects via Selenium Automation on a C#.Net application ..
OS:  Windows 10 64 bit and above

Selenium Version: Latest Version

Browser: Chrome

Browser Version: Latest Version

**Comment by jimevans** [comment]
This is a question, not an issue. Feel free to use the [user mailing list](https://groups.google.com/forum/#!forum/selenium-users) for questions like this.
