### ISSUE TITLE
Safari 10.1.2 and Selenium 3 - getFreeDriver (could not create session)

### ISSUE THREAD

**Issue by kai00000** [SeleniumHQ/selenium#4593]
Hello Colleagues,
Can you assist with the issue below.

15:48:32 Results :
15:48:32 
15:48:32 Tests in error: 
15:48:32   QUnitTest.qUnitRunner:574 » UnsupportedCommand A session with id = '58CF0F71-E...
15:48:32   QUnitTest.access$400:91->getFreeDriver:288 » SessionNotCreated Could not creat...
15:48:32   QUnitTest.qUnitRunner:574 NullPointer
15:48:32   QUnitTest.qUnitRunner[1: sap/ui/core/demokit/sample/ViewTemplate/scenario/Opa.qunit.html - safari 11603.3.8 ] » NullPointer
15:48:32   QUnitTest.access$400:91->getFreeDriver:288 » SessionNotCreated Could not creat...
15:48:32   QUnitTest.qUnitRunner:574 NullPointer
15:48:32   QUnitTest.qUnitRunner[2: sap/ui/core/demokit/sample/odata/v4/ListBinding/Opa.qunit.html - safari 11603.3.8 ] » NullPointer
15:48:32   QUnitTest.access$400:91->getFreeDriver:288 » SessionNotCreated Could not creat...
15:48:32   QUnitTest.qUnitRunner:574 NullPointer
15:48:32   QUnitTest.qUnitRunner[3: sap/ui/core/demokit/sample/odata/v4/SalesOrdersTemplate/Opa.qunit.html - safari 11603.3.8 ] » NullPointer
15:48:32   QUnitTest.access$400:91->getFreeDriver:288 » SessionNotCreated Could not creat...
15:48:32   QUnitTest.qUnitRunner:574 NullPointer
15:48:32   QUnitTest.qUnitRunner[4: sap/ui/core/demokit/sample/odata/v4/SalesOrders/Opa.qunit.html - safari 11603.3.8 ] » NullPointer
15:48:32   QUnitTest.access$400:91->getFreeDriver:288 » SessionNotCreated Could not creat...
15:48:32   QUnitTest.qUnitRunner:574 NullPointer
15:48:32   QUnitTest.qUnitRunner[5: sap/ui/core/demokit/sample/ViewTemplate/types/Opa.qunit.html - safari 11603.3.8 ] » NullPointer
15:48:32 
15:48:32 Tests run: 16, Failures: 0, Errors: 16, Skipped: 0
15:48:32

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
