### ISSUE TITLE
Chrome 60.0 not reachable - Selenium 3.5.3 

### ISSUE THREAD

**Issue by kicasta** [SeleniumHQ/selenium#4596]
## Meta -
OS:  Windows 7

Selenium Version:  3.5.3

Browser:  Chrome

Browser Version:  60.0

## Expected Behavior -
perform a driver.get(URL);
## Actual Behavior -
browser gets opened but can´t get the URL and fails with the following exception:

org.openqa.selenium.WebDriverException: chrome not reachable
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62.35 seconds
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
## Steps to reproduce -

```
WebDriver driver = new RemoteWebDriver(new URL("http://" + testData.remoteIpAddress + ":4444/wd/hub"), capabilities);
driver.get(URL);
```

**Comment by barancev** [comment]
chromedriver=2.22 is out of date, please upgrade,
