### ISSUE TITLE
Waiting for element during execution

### ISSUE THREAD

**Issue by plaidshirtakos** [SeleniumHQ/selenium#4598]
## Meta -
OS:
Windows 8.1
Selenium Version:
3.5.2
Browser:
Firefox 55.0.3 (64-bit)

## Expected Behavior -
Execution of testcase should be paused for 30 seconds, while webpage is fully loaded.

## Actual Behavior -
It is executed without any waiting time and I get a NullPointerException. It opens browser window,  but without waiting time. Execution takes only 8 seconds.

        System.setProperty("webdriver.firefox.bin", Vars.FFPATH);
        System.setProperty("webdriver.gecko.driver", "C:\\geckodriver.exe");
        WebDriver driver = new FirefoxDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.manage().window().maximize();

I tried to wait for a specific element too:
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(ExpectedConditions.visibilityOfElementLocated(webpage.linput));

**Comment by barancev** [comment]
webpage.linput is null

**Comment by plaidshirtakos** [comment]
If it would be null(but not that), this line shouldd be executed, because it is earlier in file:

> driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

Why doesn't it wait for 30 seconds?

**Comment by barancev** [comment]
WebDriverWait and driver.manage().timeouts().implicitlyWait are totally independent waiting strategies.

Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
