### ISSUE TITLE
"SendKeys" command executed very slowly in IE10

### ISSUE THREAD

**Issue by ReinhardXu2007** [SeleniumHQ/selenium#460]
Selenium:2.45.0
Binding: Java
Brower: IE10
IEDriverServer: 2.45.0

"SendKeys" command executed very slowly when there is keydown, propertychange event handler registed on the target element.
You can try it on baidu.com, taobao.com.

**Comment by jimevans** [comment]
Are you using the 32-bit or 64-bit `IEDriverServer.exe`?

**Comment by jimevans** [comment]
No answer after asking for clarification, and none of the requested information supplied. Closing this issue.
