### ISSUE TITLE
My IE went black when runing test on VMs,it seems like IEDriverServer is stuck

### ISSUE THREAD

**Issue by bizzxq** [SeleniumHQ/selenium#4601]
OS:  
win7 32bit
Selenium Version:  
selenium-java:3.5.2  IEDriverServer: 3.5.1 32bit
Browser:  
IE11

This problem occurred after we upgrade the version of selenium and IEDriverServer. We use selenium 2.53 and IEDriver 2.46 before. It works well. After we upgrade to the new version,IE goes black when running test on jenkins slave VMs. It does not always occur. If I kill IEDriverServer.exe, IE get right. So I think maybe it's an issue of IEDriverServer.
 
Please give me some solutions or suggestions,thanks a lot!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
