### ISSUE TITLE
Firefox legacy driver broken initialization with specified options

### ISSUE THREAD

**Issue by akostadinov** [SeleniumHQ/selenium#4602]
## Meta
OS:  Fedora Linux 26
Selenium Version:  selenium-webdriver-3.5.1
Browser:  Firefox
Browser Version: 52 ESR / 55 (64bit)

## Steps to reproduce
```
        caps = Selenium::WebDriver::Remote::Capabilities.firefox marionette: false
        options = Selenium::WebDriver::Firefox::Options.new(profile: firefox_profile)
        driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps, options: options
```

## Expected Behavior
Legacy driver initialized. What I'm basically trying to do is initialize a legacy FF driver with proxy support until ESR is rebased to version 54+ so that marionette can be used in all cases.

## Actual Behavior
```
Exception: ArgumentError: unknown option: {:options=>#<Selenium::WebDriver::Firefox::Options:0x00009f4f1ba410 @args=[], @binary=nil, @profile=nil, @log_level=nil, @prefs={}, @options={}>}
--
0: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:86:in `initialize'
1: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:53:in `new'
2: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
3: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/driver.rb:39:in `initialize'
4: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:58:in `new'
5: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:58:in `for'
6: /home/avalon/.gem/ruby/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver.rb:86:in `for'
7: (pry):8:in `debug_in_after_hook'
8: /home/avalon/.gem/ruby/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
9: /home/avalon/.gem/ruby/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
```

**Comment by akostadinov** [comment]
FYI I can achieve the same by using non-documented options within the capabilities. I guess legacy driver just isn't updated to handle the documented syntax for adding options. Now I add proxy to firefox profile.

```
         firefox_profile = Selenium::WebDriver::Firefox::Profile.new
         proxy = "...."
         firefox_profile.proxy = Selenium::WebDriver::Proxy.new({:http => proxy, :ssl => proxy})
         firefox_profile['network.proxy.no_proxies_on'] = "localhost, 127.0.0.1"
         client = Selenium::WebDriver::Remote::Http::Default.new
         client.open_timeout = 180

        caps = Selenium::WebDriver::Remote::Capabilities.firefox marionette: false, profile: firefox_profile, firefox_binary: "/home/user/firefox-52-esr/firefox"
        driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps, http_client: client
```

I'm not sure it's worth fixing provided legacy driver is expected to be discontinued relatively soon and a workaround already exists.

**Comment by p0deje** [comment]
Are you trying to create `:remote` or `:firefox`? For remote, options are currently not being translated to capabilities at all. For `:firefox` - options are only supported when used with GeckoDriver.

**Comment by akostadinov** [comment]
Ops, wrong paste, I updated to be `:firefox`. I see that opts are only supported for GeckoDriver. [Documentation](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings) AFAICT is wrong.

**Comment by p0deje** [comment]
I've updated the documentation to mention that examples are for GeckoDriver.

Thank you for pointing that out!

**Comment by akostadinov** [comment]
I see section "SSL Certificates" wrt "The Legacy Firefox driver ignores invalid SSL certificates by default..." still misleading. I can't edit the wiki to update with the snippet I found working though.

**Comment by p0deje** [comment]
I've updated the examples for secure SSL, thank you again for pointing it out!
