### ISSUE TITLE
mousehover is not working on microsoft edge

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#4605]
OS: windows 10 (version : 1703, build no : 15063.540)
Selenium Version: 3.4.0
Browser: Microsoft Edge
WebDriver version : 4.15063

When i try to perform mouse hover on a web application using below code, action is not happening 
Actions action = new Actions(driver);
action.MoveToElement(objHandle);
 action.Perform();

**Comment by barancev** [comment]
Should be supported in release 10586, according to [1]. Please report the issue to Microsoft bug tracker [2].

[1] https://docs.microsoft.com/en-us/microsoft-edge/webdriver-commands
[2] https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
