### ISSUE TITLE
Exception thrown setting Firefox binary

### ISSUE THREAD

**Issue by matthewdoerksen** [SeleniumHQ/selenium#4606]
## Meta -
OS:  
As tested MAC but the issue will appear on all OSes
Selenium Version:  3.5.3
Browser: Firefox (though Chrome is likely to be affected as well since we can set the binary as part of DefaultRemoteProxy.beforeSession(...) ) 

Browser Version:  55.0.3

## Expected Behavior
No exception would be thrown while trying to set the binary location for Firefox

## Actual Behavior

(relevant chunk of the stack trace)

Aug 29, 2017 3:28:11 PM org.openqa.grid.web.servlet.handler.RequestHandler beforeSessionEvent
SEVERE: Error running the beforeSessionListener : null
java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:495)
	at org.openqa.grid.selenium.proxy.DefaultRemoteProxy.beforeSession(DefaultRemoteProxy.java:228)
	at org.openqa.grid.web.servlet.handler.RequestHandler.beforeSessionEvent(RequestHandler.java:165)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:105)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:84)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)

## Steps to reproduce -

Attempt to set the location of the Firefox binary during testing.

## Known Location/Issue

During the upgrade from Selenium 2.53.7 to Selenium 3, WebDriverRequest.extractDesiredCapability() switched to returning an ImmutableMap from a standard map. Then, when we attempt to modify it to inject the binary location as part of DefaultRemoteProxy, it throws an exception since modification of the map is not allowed.

**Comment by matthewdoerksen** [comment]
Thanks @shs96c.

**Comment by elgalu** [comment]
Thanks for the fix! Will this be released in 3.5.4? We were pretty close to upgrade [Zalenium](https://github.com/zalando/zalenium) but we found this "last" issue hitting our current setup :)

**Comment by elgalu** [comment]
Ah never mind, fixed our issue by not setting `chrome_binary` nor `firefox_binary` into [the node capabilities](https://github.com/elgalu/docker-selenium/blob/3.3.1-p27/selenium-node-chrome/bin/start-selenium-node-chrome.sh#L39).
