### ISSUE TITLE
Platform Capabilities Overwritten Selenium JS 2.53.1 and 2.53.2

### ISSUE THREAD

**Issue by jovanross** [SeleniumHQ/selenium#4609]
## Meta -
OS:  
Windows 7, Windows 8.1 and Window 10
Selenium Version:  
2.53.1 and 2.53.2 Selenium Javascript
Browser:  
Internet Explorer and Edge

Browser Version:  
IE 11.103 and Edge (all versions)

## Expected Behavior -
Pass desired capabilities for browser options along with a specific platform value, the framework should retain the original platform value.

The framework should send the very same platform capabilities to my selenium grid, if one is specified by the user.

browserName = internet explorer
platform = **Windows 10**
version = 11.103
`` ie options below included for completeness``
requireWindowFocus = true
enablePersistentHover = true
enableElementCacheCleanup = true
ie.ensureCleanSession = true
ie.forceCreateProcessApi = true

## Actual Behavior -

When I pass in the below values, the framework (lib/capabilities.js) hardcodes "WINDOWS" as the platform.

### Original
browserName = internet explorer
platform = **Windows 10**
version = 11.103
`` ie options below included for completeness``
requireWindowFocus = true
enablePersistentHover = true
enableElementCacheCleanup = true
ie.ensureCleanSession = true
ie.forceCreateProcessApi = true

### Framework Normalized Capabilities
browserName = internet explorer
platform = **WINDOWS**
version = 11.103
`` ie options below included for completeness``
requireWindowFocus = true
enablePersistentHover = true
enableElementCacheCleanup = true
ie.ensureCleanSession = true
ie.forceCreateProcessApi = true

However, when I don't include the browser options, the framework uses my specified platform capability.

### Original
browserName = internet explorer
platform = Windows 10
version = 11.103

### Framework Normalized Capabilities
browserName = internet explorer
platform = Windows 10
version = 11.103

## Steps to reproduce -
~~~~
//internally, this configuration receives a platform value of WINDOWS instead of Windows 10
var webdriver = require('selenium-webdriver');
var session = new webdriver.Builder()
.usingServer('http://ondemand.saucelabs.com/wd/hub')
.withCapabilities({
  "browserName": "internet explorer",
  "platform": "Windows 10",
  "version": "11.103"
})
.setIeOptions({
  "options_": {
    "requireWindowFocus": true,
    "enablePersistentHover": true,
    "enableElementCacheCleanup": true,
    "ie.ensureCleanSession": true,
    "ie.forceCreateProcessApi": true
  },
  "proxy_": null
})
.setEdgeOptions({
  "options_": {
    "pageLoadStrategy": "eager"
  },
  "proxy_": null
})
.build();
~~~~

**Comment by Proryanator** [comment]
Did this actually fix this issue? I'm having the following setup:
A selenium-grid instance.
An appium node instance setup with some capabilities, connected to the grid.
When I create an AppiumDriver, it completely deletes/overwrites those capabilities of the ones set in the node.

Here's the thing: there's no way to instantiate RemoveWebDriver, or any derived class, where you do not specify capabilities. This means that every time you instantiate a driver you'll overwrite the capabilities defined in the node.

Is this still expected behavior? What would be the point of being able to set capabilities in the node, but have to overwrite it every time?
