### ISSUE TITLE
iOS - Exception: Cannot set the selection end when SendKeys to element

### ISSUE THREAD

**Issue by siggerzz** [SeleniumHQ/selenium#4611]
I initially raised this issue on the Appium repo, however the devs over there said it's likely an issue with Selenium itself. Hoping you guys will be able to resolve this soon! (Original issue: https://github.com/appium/appium/issues/8927)

## Meta -
OS:  iOS - Hybrid application
Selenium Version:  3.5.1
Browser:  iOS Hybrid Web App - Safari?
Browser Version:  iOS Version - 10.3.2

## Expected Behavior -
I should be able to SendKeys to an element with the **contenteditiable** attribute.

## Actual Behavior -

When I use SendKeys to an element with the **contenteditable** attribute on iOS (using Appium) I get the following error:

```
Message: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.InvalidOperationException : An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Cannot set the selection end (status: 13)
```

## Steps to reproduce -

From what I've seen online, this is caused when trying to SendKeys to an element which has the 'contenteditable' attribute. I'm assuming this is an iOS issue, since the test works fine on Android.

Other Examples of this issue:
https://github.com/appium/appium/issues/6506
https://github.com/appium/appium/issues/1001
https://discuss.appium.io/t/sendkeys-is-not-working-in-ipad-safari/3466

**Comment by LukasLewandowski** [comment]
Any progress on this?

**Comment by barancev** [comment]
Would we know what atom Appium dislikes...

**Comment by siggerzz** [comment]
The appium guys have updated the version of Selenium atoms in appium 1.6.6-beta-4, however I'm now unable to find any elements when using iOS. I've let them know, however I'm still waiting on a response.

**Comment by diemol** [comment]
I went through the linked Appium issues and there is no clear information on what to do. However, Appium is on version 1.18.1 and Selenium 3.141.59 (latest) and 4-alpha-6. 
My assumption is that this issue has been fixed and no feedback was given here, or this issue is not relevant anymore because it has been stale for over 3 years. Closing this now.
