### ISSUE TITLE
Exemple of Selenium WebDriver .NET Core Implementation

### ISSUE THREAD

**Issue by rodolpholl** [SeleniumHQ/selenium#4615]
## Meta -
OS:  
Windows 10
Selenium Version:  
WebDriver Dotnet 3.5.1
Browser:  
Firefox / Chrome

There are any example implementing Selenium at .NET Core 2.0 in the sametime at windows and ubuntu?

Thanks,

Rodolpho Loreto.

**Comment by jimevans** [comment]
This is a question, not an issue. Please use the [user-facing mailing list](https://groups.google.com/forum/#!forum/selenium-users) for questions.

**Comment by rodolpholl** [comment]
Thank you!
