### ISSUE TITLE
Make `ChromeOptions.toCapabilities()` public

### ISSUE THREAD

**Issue by CzBiX** [SeleniumHQ/selenium#4617]
## Expected Behavior -
I can use `ChromeOptions` to build capabilities for `RemoteWebDriver`

```kotlin
val chromeOptions = ChromeOptions().apply {
	addArguments("headless")
}

val driver = RemoteWebDriver(URL("http://127.0.0.1:1234"), chromeOptions.toCapabilities())
```

## Actual Behavior -
`ChromeOptions.toCapabilities()` is package visible.

**Comment by barancev** [comment]
It's public:
http://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_Chrome_ChromeOptions_ToCapabilities.htm

**Comment by CzBiX** [comment]
@barancev Sorry, I was missing the language what I used.
I refer to the Java version, not C#.

**Comment by barancev** [comment]
We're heading to a slightly different direction, see #4619
