### ISSUE TITLE
Implement new class (tenatively titled W3CCapabilities) to configure capabilities for RemoteWebDriver

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#4618]
See https://groups.google.com/forum/#!topic/selenium-developers/JmrUJu0GRoI

**Comment by shs96c** [comment]
Straw man java implementation here: 

https://gist.github.com/shs96c/42f336ba917d61f0a326696c55d9cb4f

**Comment by shs96c** [comment]
Second set straw-man proposal, showing usages: https://gist.github.com/shs96c/a8c2522807a46f8f1dbdb7ef03ce9f10

**Comment by llaskin** [comment]
quick comment: Can we not deprecate DesiredCaps until this is done?

**Comment by barancev** [comment]
RemoteWebDriverBuilder is implemented in Java:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriverBuilder.java

**Comment by kool79** [comment]
@barancev 
Can we have change signature of
`RemoteWebDriverBuilde #setCapability` from setCapability(String, String)  to setCapability(String, Object)?
  I'm trying to send w3c session creation request to appium but it requires some caps to be set as numbers (appium:newSessionTimeout)

**Comment by diemol** [comment]
Closing as implementation has been completed.
