### ISSUE TITLE
IEDriver not formatting capabilities correctly IEDriver 3.5.1

### ISSUE THREAD

**Issue by JoshuaBurns** [SeleniumHQ/selenium#4623]
## Meta -
OS:  Windows Server 2008 R2 Standard

Selenium Version:
Selenium Webdriver: 3.5.1
Selenium Support: 3.5.1
selenium standalone server:  3.5.3
IEDriverServer: 3.5.1.0

Browser:  Internet Explorer

Browser Version:  11.0.9600.17843IS

## Expected Behavior -

Internet explorer is launched, navigates to url, and finds element on page. 

## Actual Behavior -

Internet explorer is launched but and navigates to expected page but then fails to locate element due to `OpenQA.Selenium.NoSuchWindowException : Unable to find elements on closed window`

## Steps to reproduce -
C# code
Here is a test case that reproduces the issue. 

```
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Remote;
using System;

namespace POMAuctivaTest.TestSuite
{
    [TestFixture]
    [Category("test")]
    public class Test
    {
        public IWebDriver driver { get; set; }
        [OneTimeSetUp]
        public void setUp()
        {
            InternetExplorerOptions ieOptions = new InternetExplorerOptions();
            ieOptions.EnsureCleanSession = true;
            ieOptions.RequireWindowFocus = true;
            ieOptions.IgnoreZoomLevel = true;
            ICapabilities ieCaps = ieOptions.ToCapabilities();
            driver = new RemoteWebDriver(new Uri("http://localhost:4446/wd/hub"), ieCaps, TimeSpan.FromMinutes(2));
        }

        [Test]
        public void test()
        {
            driver.Navigate().GoToUrl("http://www.lufthansa.com/online/portal/lh/ua/homepage");
            System.Threading.Thread.Sleep(3000);
            var elements = driver.FindElements(By.XPath("//ul[starts-with(@class, 'row destination')]/child::li[2]"));
        }

        [OneTimeTearDown]
        public void tearDown()
        {
            driver.Quit();
        }
    }
}
```

Here is the log for this run. 
[ie_grid_console_log.txt](https://github.com/SeleniumHQ/selenium/files/1271216/ie_grid_console_log.txt)

The relevant line to me seems to be 

`11:37:02.631 INFO - Mismatched capabilities. Creating a synthetic w3c capability.`

Now looking at the [commit log](https://github.com/SeleniumHQ/selenium/commit/08a118bd6fb8609445d256e62f9eef0ae7eb4b88) it seems @jimevans might have already identified this/addressed it. 

I didnt see a bug for this so wanted to document it.

**Comment by jimevans** [comment]
The exception `Unable to find elements on closed window` has nothing whatsoever to do with the capabilities. At that point, you have a session. If there was a problem with capabilities, the test wouldn't get to that point. The capability formatting is fine. You have a separate issue altogether.

**Comment by barancev** [comment]
Start remote server with extra options to collect IE driver logs:
```
java -Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE -jar selenium-server-standalone-3.5.3.jar
```
run your scenario and attach the collected log file here.

**Comment by JoshuaBurns** [comment]
@barancev is this when registering the hub or the node, or both?

**Comment by barancev** [comment]
@JoshuaBurns When starting the node that should run IE

**Comment by JoshuaBurns** [comment]
I was unable to start the node the way you requested. Attempting to start the node with 

```
PS C:\Users\vagrant> java -Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE -jar "C:\selenium\server\selenium-server-standalone-3.5.3.jar" -role node -nodeConfig "C:\selenium\config\selenium_node.json"
Error: Could not find or load main class .ie.driver.logfile=iedriver.log
```

I am unsure how to proceed here with getting further logs. A few other things I tested was running this same setup locally (without RemoteWebDriver), things worked as expected. And I also tried to include the following line when initializing the driver but did not see any additional output. 

`ieOptions.SetLoggingPreference(LogType.Browser, LogLevel.All);`

**Comment by barancev** [comment]
@JoshuaBurns It's powershell "feature", put quotes around options:
java "-Dwebdriver.ie.driver.logfile=iedriver.log" "-Dwebdriver.ie.driver.loglevel=TRACE" -jar "C:\selenium\server\selenium-server-standalone-3.5.3.jar" -role node -nodeConfig "C:\selenium\config\selenium_node.json"

**Comment by JoshuaBurns** [comment]
[IE Trace log](https://github.com/SeleniumHQ/selenium/files/1278217/iedriver.txt)

**Comment by JoshuaBurns** [comment]
So I am attempting to test this situation on my local machine. Registering my local machine as both the hub and the node. I am unable to create the driver now when I try to run the same test case via my local node. Being that others are not responding "me too" to this ticket it has me thinking that it was an issue in my VM setup. Does this exception message mean something obvious to you? Sorry if this is the wrong place for this comment I am just trying to do further testing. 

OneTimeSetUp: System.InvalidOperationException : Unable to create new service: InternetExplorerDriverService
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'xxxxx-xx', ip: 'xx.xx.xxx.xx', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown (InsecureCertificate)

**Comment by JoshuaBurns** [comment]
This ticket can be closed. I recreated my virtual environment, and retested this test case everything is functioning as I expect it to. Must have been an issue in my environment.
