### ISSUE TITLE
java.net.BindException: Address already in use: connect (Selenium::WebDriver::Error::UnknownError)

### ISSUE THREAD

**Issue by vveliev** [SeleniumHQ/selenium#4625]
## Meta -
OS:  Windows 10

Selenium Version:  3.5.3

Browser:  Chrome

Browser Version:  60

## Expected Behavior -
Expecting it to work.

## Actual Behavior -
Running out of available ports 
```
      java.net.BindException: Address already in use: connect (Selenium::WebDriver::Error::UnknownError)
```
## Steps to reproduce -
run heavy selenium script, that does many requests, and browser refresh

**Comment by barancev** [comment]
Do you run browsers remotely using Selenium Server?

**Comment by vveliev** [comment]
yes, but as standalone server, grid seemed to be fine.

**Comment by alamai** [comment]
I am experiencing same issue on Chrome 60 (Win7, ChromeDriver 2.32, Selenium Server 3.5.3).
Looping through List of size 175. 
*List size limited to 70 → NO ERROR.
*List size 71-175 (last index) → ERROR manifests.

**Comment by adowden** [comment]
I am having the same issue on Windows 10. Selenium Stand alone server 3.4.0 Chromedriver 2.29
java.lang.RuntimeException: java.net BindException:Address already in  use

**Comment by p0deje** [comment]
Can you provide a test script that I can run to reproduce the issue?

**Comment by barancev** [comment]
Closing the issue due to inactivity.
