### ISSUE TITLE
Element State got changed from success to 0 .

### ISSUE THREAD

**Issue by saibtech** [SeleniumHQ/selenium#4626]
## Meta -
OS:  
Windows 7
Selenium Version:  
Selenium 3.5.3
Browser:  
Chrome .

**Code** 
client.element("xpath","//google/a", result => console.log(result))

**Expected behavior**
Element Should return a JSON with the state 
{ state: 'success',
  sessionId: '29110f15-d614-4c66-b233-122c9f922ff7',
  hCode: 42690232,
  value: { ELEMENT: '77' },
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }

**Actual Behavior**
Element return a JSON without a state field

{ sessionId: 'f6a469c63ca23b343f089babc71095f7',
  status: 0,
  value: { ELEMENT: '0.05127538398415643-7' } }

**Comment by jimevans** [comment]
The `state` field has never been any official part of any version of the wire protocol, neither the [open-source (OSS) version](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol), nor the [W3C Spec version](https://w3c.github.io/webdriver/webdriver-spec.html). If your language bindings are expecting that, they are expecting the wrong thing and need to be updated.
