### ISSUE TITLE
Selenium 3.5.2-Java : Documentation mentions available levels for log object are trace, debug, config, info, warn, error, and fatal while Selenium 3.5.2 Java client intelligence provides the following options: All, CONFIG, FINE, FINER, FINEST, INFO, OFF, SEVERE and WARNING

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4628]
## Meta - Selenium 3.5.2-Java : [Documentation](https://github.com/mozilla/geckodriver#log-object) mentions available levels for log object are `trace`, `debug`, `config`, `info`, `warn`, `error`, and `fatal` while Selenium 3.5.2 Java client intelligence provides the following options: `All`, `CONFIG`, `FINE`, `FINER`, `FINEST`, `INFO`, `OFF`, `SEVERE` and `WARNING`

![selenium_java_logging](https://user-images.githubusercontent.com/26503213/29995220-fd380fae-9001-11e7-9dd1-525965f17690.png)

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.2

Selenium Binding: Java

GeckoDriver Version: 0.18.0

Browser: Mozilla Firefox

Browser Version: 55.0.3

## Steps to reproduce -
Minimum Code:

	package demo;

	import java.util.logging.Level;

	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.firefox.FirefoxOptions;

	public class Gecko_TRACE_LOGS 
	{
		public static void main(String[] args) 
		{
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			FirefoxOptions options = new FirefoxOptions();
			options.setLogLevel(Level.OFF);
			WebDriver driver =  new FirefoxDriver(options);
			driver.get("https://stackoverflow.com");
			System.out.println("Application opened");
			System.out.println("Page Title is : "+driver.getTitle());
			driver.quit();
		}
	}

**Comment by barancev** [comment]
Unfortunately, names are not same :(

But mapping is simple:
OFF -> fatal
SEVERE -> error
WARNING -> warn
INFO -> info
CONFIG -> config
FINE -> debug
FINER and FINEST -> trace

Yes, this should be documented in setLog mewthod javadoc.

**Comment by Debanjan-B** [comment]
@barancev Thanks for the help. IMO, shouldn't there be some difference between `FINER` and `FINEST` at client level which currently maps to `trace`?

Additionally, I think we are still missing out `ALL` from client level.

**Comment by barancev** [comment]
Yes, my bad, ALL, FINER and FINEST -> trace
Geckodriver has 7 levels only.

**Comment by barancev** [comment]
Fixed by 72e397775631daab45370c2225ec313908b9f33c
Instead of fixing documentation I've implemeted an enum :)

**Comment by Debanjan-B** [comment]
Thanks @barancev The enum implementation looks great !!! Thanks for the help.
