### ISSUE TITLE
webDriver.get(url) doesn't do anything when ChromeDriver is initiated with user-data-dir

### ISSUE THREAD

**Issue by rohithkk** [SeleniumHQ/selenium#4629]
OS:  Windows8
Selenium Version:  3.4
Browser:  Chrome

I've very peculiar usecase that requires me to run multiple webdriver instances at the same time. Unfortunately, IDP for the application that I'm trying to automate doesn't allow for multiple simultaneous logins.. as soon as the second login is done, first login session expires. While researching how to share sessions across WebDriver instances, I came across user-data-dir option.

This is how I implemented..

I'll create one webdriver instance and login into the application. I'll keep this webdriver instance running and will create more webdriver instances that actually do the automation work.Since I already logged into the application from first instance, I should be automatically logged into the second instance. 

```
public class TestClass {

   private static WebDriver webDriver = null;

   public static void main(String[] args) throws InterruptedException {

        TestClass tc = new TestClass();

        if(webDriver == null) {

            webDriver = tc.getWebDriverInstance();

            webDriver.get("https://example.com/loginpage");
            //enter userid/password, click login button
            //login is successful and redirected to next page - https://example.com/securepage
         }

         WebDriver newWebDriverOne = this.getWebDriverInstance();
         newWebDriverOne.get("https://example.com/securepage"); // this doesn't work

         WebDriver newWebDriverTwo = this.getWebDriverInstance();
         newWebDriverTwo.get("https://example.com/securepage");// this doesn't work
  }

  WebDriver getWebDriverInstance(){    

    DesiredCapabilities dCaps = DesiredCapabilities.chrome();    
    ChromeOptions options = new ChromeOptions();    
    options.addArguments("user-data-dir=C:/user/me/selenium/chrome");    
    dCaps.setCapability(ChromeOptions.CAPABILITY, options);
    return new ChromeDriver(dCaps); 
   }
 }
```

Problem with this is, when I call get() on the newWebDriver instance which is created after the first one, nothing happens. Selenium opens the second window as since I created a new webdriver instance, but get() doesn't do anything. I tried manually entering the securepage url in the opened window and it worked. I was able to see the secure page without getting redirected to login page. That means that the automatic login into second instance is working since they share same profile. But the webDriver is useless as it doesn't do get() anymore.

It seems like it is impossible to have multiple webdriver instances if we specify user-data-dir. Is there any other option to share cookie data between sessions?

**Comment by barancev** [comment]
Try to report this issue to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help
