### ISSUE TITLE
Need to add the "withMessage()" method within the "Sample usage" documentation of FluentWait

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4630]
## Meta - Usage of `withMessage()` method must be included within the `Sample usage` documentation of [FluentWait](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html).

OS: Windows 8 Pro, 64 bit

Selenium Version: 3.5.2

Selenium Binding: Java

GeckoDriver Version: 0.18.0

Browser: Mozilla Firefox

Browser Version: 55.0.3

**Comment by Debanjan-B** [comment]
Thanks @p0deje   [**`FluentWait`**](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html) also mentions about `timeoutException` at the end which is different than the `exceptions` handled through `ignoring` method. 

Can we include it in the `Sample usage` documentation too?

**Comment by barancev** [comment]
Sample usage is just a sample, it is not intended to document all methods, they have their own javadoc. Sample usage mentions the most important parts of FluenWait API. There is no need to overcomplicate it.

**Comment by Debanjan-B** [comment]
@barancev I think by "Sample usage" documentation of [**`FluentWait`**](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html) I meant/pointed to the JavaDoc only. 

Please have a re-look at this Issue.

**Comment by barancev** [comment]
Yes, the same javadoc page contains description of all available methods, there is no need to mention them all in *sample* usage.
