### ISSUE TITLE
Why there is no Selenium.Support nuget 3.5.3? WebDriverWait is missing in Selenium.Support 3.5.2

### ISSUE THREAD

**Issue by LadaVarga** [SeleniumHQ/selenium#4631]
Hello,

## Meta -
OS:  
ANY
Selenium Version:  
Selenium.Support 3.5.2
Browser:  
ALL

3 days ago Selenium.Support 3.5.2 were released.
Our project cannot be compiled because new WebDriverWait(driver, TimeSpan.FromSeconds(10));
is not exists anymore.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'WebDriverWait' could not be found (are you missing a using directive or an assembly reference?)		c:\!!code\xxxx\zxxx\xxxs\xxx.cs	482	Active

Is this issue fixed in Selenium 3.5.3 ?
Is this intended change?
Will be any Selenium.Support 3.5.3?
With Selenium.Support 3.5.1 everything is ok.

## Steps to reproduce -
Try compile project with Selenium.Support 3.5.2.

**Comment by jimevans** [comment]
As of 3.5.2, `WebDriverWait` is now part of the main `WebDriver.dll` assembly. You no longer need a reference to `WebDriver.Support.dll` to use ‘WebDriverWait`. I assumed that the case where a project referenced the support package, but not the main WebDriver package, would be exceedingly rare. If changing the reference to the main WebDriver package does not resolve the issue, we can reopen it.
