### ISSUE TITLE
ChromeOptions not being applied

### ISSUE THREAD

**Issue by SaadeMotion** [SeleniumHQ/selenium#4638]
## Meta -
OS:  Ubuntu 16

Selenium Version:  3.5.0

Browser:  ChromeDriver

Browser Version:  2.32.498513

## Expected Behavior -
ChromeOptions working properly
## Actual Behavior -
ChromeOption not being applied.

tried with:

``` 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--argument')

 webdriver.Chrome(chrome_options=chrome_options)
```
and also:
``` 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--argument')
webdriver.Chrome(chrome_options=chrome_options)
```

## Steps to reproduce -

Download everything, install and use any piece of code above

**Comment by lmtierney** [comment]
What option are you trying? How do you know it's not being applied?

**Comment by SaadeMotion** [comment]
i tried with:

incognito = Chrome wont opened in incognito
user-data-dir = By typing: chrome://version in address bar, Profile Path not changed
window-size = Window opens in default size

and many others that doesnt seems to work. Actually, none of this worked: https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by lmtierney** [comment]
All of these, with the addition of `start-maximized` are working fine for me. What version of chrome are you using? Can you add these lines before you start your chrome instance and paste the DEBUG lines from the console after doing so?

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by SaadeMotion** [comment]
Actually, i think i'm doing something wrong. With fresh new archive, it works properly, can u tell me whats wrong in here?:

``` 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--incognito')

class MyClass( webdriver.Chrome ):
    def __init__(self):
        webdriver.Chrome.__init__(self, chrome_options=chrome_options)

```

**Comment by SaadeMotion** [comment]
Maybe some restriction on extending class? not permitted?

**Comment by lmtierney** [comment]
That works fine for me as well

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
