### ISSUE TITLE
Tests do not run using Selenium Grids with V-3.5.3

### ISSUE THREAD

**Issue by karendantis** [SeleniumHQ/selenium#4639]
Tests do not run using Selenium Grids
OS:  
MACOS
Selenium Version:  
3.5.3
Browser:  
Chrome - Version 60.0.3112.113 (64-bit)

ChromeDriver used:  v2.31 

Expected Behavior - Should be able to run tests using selenium grids 3.5.3

Actual Behavior - Using selenium grids 3.5.3 the browser invokes but does not proceed with the tests

Steps to reproduce:

Hub setup->
java -jar jars/selenium-server-standalone-3.5.3.jar -enablePassThrough false -role hub -hubConfig hub.json

{
  "host": null,
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,

  "cleanUpCycle": 5000,
  "timeout": 300000,
  "browserTimeout": 0,
  "maxSession": 5,
  "jettyMaxThreads":-1
}

Node 1 setup->
java -jar jars/selenium-server-standalone-3.5.3.jar -enablePassThrough false -role wd -nodeConfig node1.json

{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 5,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "hub": "http://localhost:4444",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}

I do not get any error but the tests stop when the browser is invoked.

Screenshot attached: 
![screen shot 2017-09-06 at 11 13 29](https://user-images.githubusercontent.com/26387843/30103945-75035382-92f4-11e7-91e1-5a8da7a62f96.png)

**Comment by barancev** [comment]
Show the code you run and the hub/node logs.

**Comment by karendantis** [comment]
Attached code and node logs



[Code.txt](https://github.com/SeleniumHQ/selenium/files/1280675/Code.txt)
[OSXNode.txt](https://github.com/SeleniumHQ/selenium/files/1280683/OSXNode.txt)

**Comment by barancev** [comment]
You did not attempt to perform any actions with the driver. So what's the problem? Browser started, that's all you wanted to do, according to your code and logs.

**Comment by karendantis** [comment]
the drivers were initiated during hub and node run:

Hub setup->
java -Dwebdriver.chrome.driver=/Driver/2017_V0.1/2.31/chromedriver -jar jars/selenium-server-standalone-3.5.3.jar -enablePassThrough false -role hub -hubConfig hub.json

Node 1 setup->
java -Dwebdriver.chrome.driver=/Driver/2017_V0.1/2.31/chromedriver -jar jars/selenium-server-standalone-3.5.3.jar -enablePassThrough false -role wd -nodeConfig node1.json

**Comment by barancev** [comment]
This looks more like a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by karendantis** [comment]
Do you have answer for this question?

**Comment by barancev** [comment]
According to your code sample and the logs you did not perform any commands with the initialized driver.

**Comment by karendantis** [comment]
Thank you very much 👍
