### ISSUE TITLE
selenium ide is not working "Table view is not available with this format" is displayed

### ISSUE THREAD

**Issue by Parkhya-Sol** [SeleniumHQ/selenium#4640]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Parkhya-Sol** [comment]
Hello,
Thank you for reply,
I install the selenium IDE in Firefox 5 the version on window 7.
Installation was successfully but when i app the selenium IDE(9.5.2) version.
In comment section "Table view is not available with this format" is displayed.
when i click on any where an error message is displayed.
Selenium recording and command section in table from is not working.
Please check the screenshot. 
![issue 3](https://user-images.githubusercontent.com/21004960/30146375-56f45eb0-93b5-11e7-9386-88837e36ff6e.PNG)
![selenium issue](https://user-images.githubusercontent.com/21004960/30146379-5c3d89dc-93b5-11e7-8ab3-955660b915ed.PNG)
![selenium_1](https://user-images.githubusercontent.com/21004960/30146388-60c327aa-93b5-11e7-80b0-1518aaed2a78.PNG)
Please help me...
Thank you.

**Comment by p0deje** [comment]
What version of Firefox do you use?

**Comment by Parkhya-Sol** [comment]
I used Firefox 55.0.3(64bit)

**Comment by p0deje** [comment]
Please see https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/ about Firefox 55 and Selenium IDE.

**Comment by Parkhya-Sol** [comment]
which version Selenium IDE is support for me.

**Comment by Parkhya-Sol** [comment]
Hello,

Is selenium IDE support Firefox version 54?

**Comment by p0deje** [comment]
Yes, you can use it with Firefox 54.

**Comment by Parkhya-Sol** [comment]
okay , thank you..i will try..if i have some issue with it, i will mail
you..
