### ISSUE TITLE
Somehow provide a way to stop the selenium standalone server programmatically

### ISSUE THREAD

**Issue by nddipiazza** [SeleniumHQ/selenium#4642]
## Meta -
OS:  
all
Selenium Version:  
3.5.3
Browser:  
all

## Expected Behavior -

Previously there was a way to shut down selenium server using: 
http://localhost:64146/selenium-server/driver/?cmd=shutDownSeleniumServer

## Actual Behavior -
No documented way to shut down selenium standalone server.

## Steps to reproduce -
Start selenium server.
Note no way to stop server with an api request.

**Comment by mach6** [comment]
duplicate of #2958

**Comment by p0deje** [comment]
Please see the discussion in #2958 for the ways to stop server without API.

**Comment by p0deje** [comment]
@mach6 Do you intend to keep this issue open?

**Comment by nddipiazza** [comment]
So... is there no way to stop the standalone server with the API? like 
http://localhost:64146/selenium-server/driver/?cmd=shutDownSeleniumServer did?

**Comment by nddipiazza** [comment]
I don't want to have to resort to finding the PID etc because I'm using Selenium for non-test purposes. It would be nice if we can somehow surface the shutdown action via an API request like it was before.

**Comment by nddipiazza** [comment]
OK i didn't read down far enough. 

https://github.com/SeleniumHQ/selenium/issues/2852#issuecomment-268324091 
is the answer for standalone shutdown ability.
