### ISSUE TITLE
Selenium IDE stopped working in latest version of Firefox

### ISSUE THREAD

**Issue by sohelt19** [SeleniumHQ/selenium#4648]
Selenium IDE is not working at all in the latest version of Firefox. After opening it the following error message has shown:

"There was an unexpected error. Msg: TypeError: obj is undefined
Url: chrome://implicit-wait/content/implicit-wait-ide.js?1504688107560, line: 185, column: 9
wrap@chrome://implicit-wait/content/implicit-wait-ide.js?1504688107560:185:9
ImplicitWait/<@chrome://implicit-wait/content/implicit-wait-ide.js?1504688107560:27:9"

## Meta -
OS:  Windows 10

Selenium Version:  2.9.1

Browser:  Firefox

Browser Version:  55.0.3 (32-bit)

## Expected Behavior - 
Selenium IDE should work with latest version of Firefox.

## Actual Behavior - 
After opening IDE it shows a error message and not working at all.

## Steps to reproduce -
1. Open latest version of Firefox
2. Open Selenium IDE and you will see the error message.

**Comment by p0deje** [comment]
Please see https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/ about Firefox 55 and Selenium IDE.
