### ISSUE TITLE
Is not working "selecting multiple rows at different place in a table using Selenium 3.5.2 and firefox v54/v55" 

### ISSUE THREAD

**Issue by vinaymopidevi** [SeleniumHQ/selenium#4649]
I am trying below code to fetch the table rows, but I need to select the rows which are at different place in a table. using Selenium 3.5.2, firefox v54/v55

		// code 1#
		try {
			Actions action = new Actions(driver);
			action.keyDown(Keys.CONTROL);
			for (WebElement element : list) {				
				action.moveToElement(element).click(element);
			}
			action.keyUp(Keys.CONTROL);
			action.build().perform();
		} catch (Exception e) {

			e.printStackTrace();
		}
		// code 2#

		Keyboard keyboard = ((HasInputDevices) driver).getKeyboard();
		Mouse mouse = ((HasInputDevices) driver).getMouse();
		for (WebElement element : list) {
			keyboard.pressKey(Keys.CONTROL);
			mouse.click(((Locatable) element).getCoordinates());
			keyboard.releaseKey(Keys.CONTROL);
		}
		
		//code 3#
		Robot robot=null;
		try {
			  robot = new Robot();
		} catch (AWTException e) {			
			e.printStackTrace();
		}
		robot.keyPress(KeyEvent.VK_CONTROL);
		for (WebElement element : list) {				
			action.moveToElement(element).click(element);
		}		
		robot.keyRelease(KeyEvent.VK_CONTROL);

none of them are working in firefox v55/v55

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
