### ISSUE TITLE
standalone 2.45.0.0 and IEDriver 2.45.0 super slow typing

### ISSUE THREAD

**Issue by chris1248** [SeleniumHQ/selenium#465]
I am running into (again) the super slow typing getting sent to the the 32 bit IEDriverServer.exe. As a result, any text sent to the input fields type about 1 character per 5 seconds. 

Environment:
Testbox: 
Windows 7 - IE 11
IEDriverServer.exe - version 2.45
selenium-server-standalone-2.45.0.jar

I had experienced this in the 64 bit driver too. This makes this version completely unusable.

**Comment by jimevans** [comment]
Can you please provide a sample of WebDriver code displaying the behavior? Also, as a diagnostic operation, set the requireWindowFocus capability to true, and provide a log of at least debug level from `IEDriverServer.exe`.

**Comment by jimevans** [comment]
No answer after asking for clarification, and none of the requested information supplied. Closing this issue.

**Comment by chris1248** [comment]
This problem exists in the 64 bit driver too.

**Comment by jimevans** [comment]
I fully expect the problem to [exist in the 64-bit driver](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html). It's the 32-bit driver exhibiting the problem that is surprising. However, if the Windows hook procedures (see the previous link) are prevented from working somehow, you'd see the same symptoms there. To enable the logging remotely, you can start the standalone server on the remote machine with the appropriate system properties set, as documented on the [wiki page for the IE driver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#important-system-properties).
