### ISSUE TITLE
Not able to launch multiple edge browser in selenium

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#4650]
## Meta -
OS:  Windows 10
Selenium Version:  3.4.0

Browser:  Microsoft Edge

**Comment by p0deje** [comment]
At the moment you can only run 1 instance of Edge. That is a limitation of MicrosoftWebDriver. Please raise this issue at https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/tools/webdriver.
