### ISSUE TITLE
Underlying webdriver instance does not support javascript error shown when using Edge

### ISSUE THREAD

**Issue by mark0203** [SeleniumHQ/selenium#4651]
## Meta -
**OS:**  Windows10
**Selenium Version:**  
  Ruby gem - selenium-webdriver 3.5.1
  Selenium-Standalone-Server 3.5.0 (also tested with 3.5.3)
**Browser:**  Edge 
**Browser Version:**  15.15063 (64bit)

## Expected Behavior -
Not getting the Javascript support error since it's enabled and also works fine with with selenium 3.4.0 (both webdriver gem and standalone server) with the same Edge browser and same reproduce steps.

## Actual Behavior -
When performing an action like watir element.flash (or fire_event), I get this Javascript error and the test fails. This happens only on Edge (not on Chrome or FF), when I use selenium-webdriver 3.5.1 and selenium-standalone-server 3.5.0 (or 3.5.3). 

## Steps to reproduce -
```ruby
require 'watir'
url = "http://localhost:4444/wd/hub"
caps = WebDriver::Remote::Capabilities.new
caps[:browserName] = "MicrosoftEdge"
browser = Watir::Browser.new(
	:remote,
	:url => url,
	:desired_capabilities => caps)
browser.goto "https://www.google.com"
element = browser.input(:id => 'lst-ib')
element.flash
```
I get the error:
```ruby
irb(main):008:0* browser = Watir::Browser.new(
irb(main):009:1* :remote,
irb(main):010:1* :url => url,
irb(main):011:1* :desired_capabilities => caps)
You can now pass values directly into Watir::Browser opt without needing to use :desired_capabilities
=> #<Watir::Browser:0x..fd0daf7f6 url="about:blank" title="">
irb(main):012:0>
irb(main):013:0* browser.goto "https://www.google.com"
=> "https://www.google.com"
irb(main):014:0> element = browser.input(:id => 'lst-ib')
=> #<Watir::Input: located: false; {:id=>"lst-ib", :tag_name=>"input"}>
irb(main):015:0> element.flash
Selenium::WebDriver::Error::UnsupportedOperationError: underlying webdriver instance does not support javascript
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/oss/bridge.rb:569:in `assert_javascript_enabled'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/oss/bridge.rb:267:in `execute_script'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/common/driver.rb:213:in `execute_script'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.1/lib/watir/browser.rb:265:in `execute_script'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.1/lib/watir/js_snippets.rb:12:in `execute_js'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.1/lib/watir/js_execution.rb:48:in `block in flash'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.1/lib/watir/elements/element.rb:678:in `element_call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.8.1/lib/watir/js_execution.rb:48:in `flash'
        from (irb):15
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'
irb(main):016:0>
```

## Side note -
I created this ticket here on request of @titusfortner @Blackbaud-TitusFortner (see link below to Watir-general group)
I did raise this issue with MS:
[MS-dev-edge-issues](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13599112/)
And I did ask questions in the Selenium and Watir groups:
[Selenium-users](https://groups.google.com/forum/#!topic/selenium-users/2FE3arNRanU)
[Watir-general](https://groups.google.com/forum/#!topic/watir-general/KRehp-T0V-8)

**Comment by p0deje** [comment]
Interesting, I'll have a look at this.

**Comment by titusfortner** [comment]
This has to do with how Ruby checks for the capability to be present when doing javascript things. Since Edge uses the w3c capabilities it won't have the javascript capability enabled. The way Edge Bridge used to work it was avoided, but now OSS things are getting used by Edge that didn't used to. I think we're ok to just delete it at this point, honestly. If someone is trying to use javascript with a browser that doesn't support JavaScript I think they get what they get.

**Comment by mark0203** [comment]
The comment I got in the MS ticket.

> Steven K. 8 hours ago MICROSOFT EDGE TEAM
> I verified that our MicrosoftWebDriver does work and has been tested with Selenium Standalone Server 3.5.3 using the .Net language bindings.

**Comment by p0deje** [comment]
Fixed now, will be available in the next Ruby bindings release.

**Comment by mark0203** [comment]
Thanks. I'll give it a try once the new release is ready.

**Comment by mark0203** [comment]
I just noticed the new selenium-webdriver was out, so I gave it a spin and the issue is resolved. Many thanks for this fix.
