### ISSUE TITLE
Chrome opens multiple tabs instead of new windows for a new session request

### ISSUE THREAD

**Issue by hsarmah09** [SeleniumHQ/selenium#4653]
Google chrome portable(version 60.0.3112.113) opens multiple tabs instead of multiple new windows with Selenium standalone server 3.5.3.

Steps to reproduce
1. Softwares versions
Google chrome portable: 60.0.3112.113
Selenium: 3.5.3
Selenium standalone server: 3.5.3
Chrome driver: 2.31

2. Create multiple jobs in Jenkins which runs tests on chrome or locally from a workbench.
3. Send multiple requests to selenium standalone server to open google chrome and run some tests.

Expected behaviour: Chrome opens a new window for each incoming new session request from selenium server and runs tests.
Actual behaviour: Chrome opens new tabs when already one window is open and stops working i.e. does not execute commands passed through selenium.

**Comment by barancev** [comment]
Please provide Selenium Server log.

**Comment by hsarmah09** [comment]
prefs={enable_do_not_track=true}, }, } matched class org.openqa.selenium.remote.
server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDrive
rService)
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on
port 13721
Only local connections are allowed.
14:11:16.843 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:16.843 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/timeouts (
handler: ServicedSession)
14:11:16.859 INFO - To upstream: {"type":"implicit","ms":10000}
14:11:16.859 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:16.874 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:16.874 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/url (handl
er: ServicedSession)
14:11:16.874 INFO - To upstream: {"url":"/"}
14:11:18.234 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:18.245 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:18.246 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/window/cur
rent/maximize (handler: ServicedSession)
14:11:18.248 INFO - To upstream: {"windowHandle":"current","handle":"current"}
14:11:19.299 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:19.330 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.330 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/timeouts (
handler: ServicedSession)
14:11:19.330 INFO - To upstream: {"type":"implicit","ms":3000}
14:11:19.345 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:19.361 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.361 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:19.377 INFO - To upstream: {"using":"id","value":"passwordinput-rf"}
14:11:19.392 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.40117721055826383-1"}]}
14:11:19.408 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.408 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:19.408 INFO - To upstream: {"using":"id","value":"passwordinput-rf"}
14:11:19.439 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.40117721055826383-1"}}
14:11:19.455 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.455 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
40117721055826383-1/clear (handler: ServicedSession)
14:11:19.455 INFO - To upstream: {"id":"0.40117721055826383-1"}
14:11:19.487 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:19.501 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.515 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:19.546 INFO - To upstream: {"using":"id","value":"passwordinput-rf"}
14:11:19.546 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.40117721055826383-1"}]}
14:11:19.546 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.562 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:19.562 INFO - To upstream: {"using":"id","value":"passwordinput-rf"}
14:11:19.562 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.40117721055826383-1"}}
14:11:19.593 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.593 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
40117721055826383-1/value (handler: ServicedSession)
14:11:19.593 INFO - To upstream: {"id":"0.40117721055826383-1","value":["Portal2
018"]}
14:11:19.656 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:19.674 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.675 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:19.680 INFO - To upstream: {"using":"id","value":"user-rf"}
14:11:19.703 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.40117721055826383-2"}]}
14:11:19.739 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.739 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:19.739 INFO - To upstream: {"using":"id","value":"user-rf"}
14:11:19.770 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.40117721055826383-2"}}
14:11:19.786 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.786 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
40117721055826383-2/clear (handler: ServicedSession)
14:11:19.786 INFO - To upstream: {"id":"0.40117721055826383-2"}
14:11:19.817 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:19.818 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.818 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:19.820 INFO - To upstream: {"using":"id","value":"user-rf"}
14:11:19.830 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.40117721055826383-2"}]}
14:11:19.837 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.837 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:19.841 INFO - To upstream: {"using":"id","value":"user-rf"}
14:11:19.872 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.40117721055826383-2"}}
14:11:19.888 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:19.903 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
40117721055826383-2/value (handler: ServicedSession)
14:11:19.903 INFO - To upstream: {"id":"0.40117721055826383-2","value":["protics
_ubb"]}
14:11:19.973 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:20.003 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:20.004 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:20.011 INFO - To upstream: {"using":"id","value":"login-button-rf"}
14:11:20.055 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.40117721055826383-3"}]}
14:11:20.071 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:20.071 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:20.071 INFO - To upstream: {"using":"id","value":"login-button-rf"}
14:11:20.086 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.40117721055826383-3"}}
14:11:21.122 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:21.122 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing GET on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.4
0117721055826383-3/displayed (handler: ServicedSession)
14:11:21.153 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":true}
14:11:21.184 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:21.184 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing GET on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.4
0117721055826383-3/enabled (handler: ServicedSession)
14:11:21.215 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":true}
14:11:21.215 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:21.231 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
40117721055826383-3/click (handler: ServicedSession)
14:11:21.231 INFO - To upstream: {"id":"0.40117721055826383-3"}
14:11:21.351 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:21.389 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:21.389 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:21.404 INFO - To upstream: {"using":"xpath","value":"//button[@class='btn-
grey ']"}
14:11:24.385 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.4506915611169955-1"}]}
14:11:24.404 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:24.406 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:24.412 INFO - To upstream: {"using":"xpath","value":"//button[@class='btn-
grey ']"}
14:11:24.435 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.4506915611169955-1"}}
14:11:25.480 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:25.480 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing GET on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.4
506915611169955-1/displayed (handler: ServicedSession)
14:11:25.511 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":true}
14:11:25.527 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:25.527 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing GET on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.4
506915611169955-1/enabled (handler: ServicedSession)
14:11:25.575 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":true}
14:11:25.609 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:25.609 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element/0.
4506915611169955-1/click (handler: ServicedSession)
14:11:25.624 INFO - To upstream: {"id":"0.4506915611169955-1"}
14:11:25.758 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:25.770 INFO - Binding default provider to: org.openqa.selenium.chrome.Chro
meDriverService
14:11:25.770 INFO - Found handler: org.openqa.selenium.remote.server.BeginSessio
n@3bad234d
14:11:25.772 INFO - /session: Executing POST on /session (handler: BeginSession)

14:11:25.783 INFO - Mismatched capabilities. Creating a synthetic w3c capability
.
14:11:25.784 INFO - Capabilities are: Capabilities {loggingPrefs={browser=ALL},
browserName=chrome, chromeOptions={args=[], extensions=[], binary=C:\Users\Publi
c\portableBro..., prefs={enable_do_not_track=true}, }, }
14:11:25.785 INFO - Capabilities {loggingPrefs={browser=ALL}, browserName=chrome
, chromeOptions={args=[], extensions=[], binary=C:\Users\Public\portableBro...,
prefs={enable_do_not_track=true}, }, } matched class org.openqa.selenium.remote.
server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDrive
rService)
14:11:25.790 INFO - Capabilities {loggingPrefs={browser=ALL}, browserName=chrome
, chromeOptions={args=[], extensions=[], binary=C:\Users\Public\portableBro...,
prefs={enable_do_not_track=true}, }, } matched class org.openqa.selenium.remote.
server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDrive
rService)
14:11:25.794 INFO - Capabilities {loggingPrefs={browser=ALL}, browserName=chrome
, chromeOptions={args=[], extensions=[], binary=C:\Users\Public\portableBro...,
prefs={enable_do_not_track=true}, }, } matched class org.openqa.selenium.remote.
server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDrive
rService)
Starting ChromeDriver 2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8) on
port 19411
Only local connections are allowed.
14:11:26.794 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:26.833 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:26.877 INFO - To upstream: {"using":"link text","value":"Schlie▀en"}
14:11:30.118 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[]}
14:11:30.149 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:30.149 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/timeouts (
handler: ServicedSession)
14:11:30.165 INFO - To upstream: {"type":"implicit","ms":15000}
14:11:30.165 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:30.196 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:30.196 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:30.196 INFO - To upstream: {"using":"link text","value":"Information"}
14:11:30.227 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":[{"ELEMENT":"0.4506915611169955-2"}]}
14:11:30.243 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:30.243 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/element (h
andler: ServicedSession)
14:11:30.243 INFO - To upstream: {"using":"link text","value":"Information"}
14:11:30.259 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":{"ELEMENT":"0.4506915611169955-2"}}
14:11:30.290 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:30.290 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/moveto (ha
ndler: ServicedSession)
14:11:30.290 INFO - To upstream: {"element":"0.4506915611169955-2"}
14:11:35.329 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:35.344 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:35.344 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/click (han
dler: ServicedSession)
14:11:35.360 INFO - To upstream: {"button":0}
14:11:35.360 INFO - To downstream: {"sessionId":"4f6824fb645fa7b280c2eeb79b65b52
1","status":0,"value":null}
14:11:35.360 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSes
sion@1b95c6d1
14:11:35.360 INFO - Handler thread for session 4f6824fb645fa7b280c2eeb79b65b521
(chrome): Executing POST on /session/4f6824fb645fa7b280c2eeb79b65b521/elements (
handler: ServicedSession)
14:11:35.360 INFO - To upstream: {"using":"link text","value":"Produktinformatio
nen"}

**Comment by barancev** [comment]
Selenium starts chromecriver several times. If it's trying to reuse the same Chrome window -- it's a chromedriver issue. Please report it to https://sites.google.com/a/chromium.org/chromedriver/help
