### ISSUE TITLE
chrome driver entrypoint not found exceptions

### ISSUE THREAD

**Issue by gtaranas** [SeleniumHQ/selenium#4656]
## Meta -
OS:  windows xp sp3

Selenium Version:  2.32

Browser:  Chrome

Browser Version:  49.0.2623.112

![screenshot](https://user-images.githubusercontent.com/3484868/30165864-40e032ae-93ea-11e7-950e-6e21ae93a285.png)

**Comment by gtaranas** [comment]
Also tested with

browser chrome version: 49.0.2623.112

chromedriver: 2.21, 2.22

**Comment by barancev** [comment]
----------ChromeDriver v2.32 (2017-08-30)----------
Supports Chrome v59-61
https://chromedriver.storage.googleapis.com/2.32/notes.txt

**Comment by gtaranas** [comment]
Also tested with

browser chrome version: 49.0.2623.112

chromedriver: 2.21, 2.22

**Comment by barancev** [comment]
You can try to report this issue to chromedriver team, but I bet they'll not fix it, they don't support old browser versions.

**Comment by gtaranas** [comment]
the solution was to install vc++ redistributable, thanks.
