### ISSUE TITLE
Selenium IDE issue

### ISSUE THREAD

**Issue by howardselenium** [SeleniumHQ/selenium#4658]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by howardselenium** [comment]
There was an unexpected error. Msg: TypeError: window.editor.infoPanel is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
onclick@chrome://selenium-ide/content/selenium-ide.xul:1:1


any one could help me to fix this issue  as soon as possible

**Comment by ddavison** [comment]
see the [blog post here](https://seleniumhq.wordpress.com/)
