### ISSUE TITLE
TouchActions should inherit keyboard Actions

### ISSUE THREAD

**Issue by iSimonWeb** [SeleniumHQ/selenium#4662]
## Meta -
OS:  
WSL (Windows Subsystem for Linux)
Selenium Version:  
3.5.0
Browser:  
Chrome --headless with [libudev-stub](https://github.com/therealkenc/libudev-stub)

Browser Version:  
60

## Expected Behavior -
`TouchActions` should inherit `sendKeys()` and other keyboard `Actions`, as it currently is for the [Java version of selenium](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html)

## Actual Behavior -
To tap on a field and then send some keys we have to use `touchActions()` and a separate `sendKeys()`, losing the possibility to chain them all.
Could it be useful and comfortable?

**Comment by barancev** [comment]
In what language binding?

**Comment by iSimonWeb** [comment]
Pardon, was talking about JavaScript, which I'm currently working on to
build a bot.

Thanks for your quick answer.

**Comment by jleyba** [comment]
Closing this issue - further discussion about the actions API in #4564
