### ISSUE TITLE
[IEDriverServer] Element click do not click on the element directly

### ISSUE THREAD

**Issue by bboycs** [SeleniumHQ/selenium#4663]
## Meta -
OS:  Window 8.1 
Selenium Version:  3.4.0
Browser:  Internet Explorer 11 

Browser Version:  11.0.9600.18763

## Expected Behavior -
Element should clicked directly instead of go through with siblings elements.
I have table with rows which accept click action to trigger some responses. 
The the tr shall be clicked directly.

## Actual Behavior -
The row1 will be selected and then move to row2 then only execute on the element.click()

Sample code :
element(by.css("tr[name='row2']")).click()

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bboycs** [comment]
I am not sure how to provide reproduce the test case.
But i able to resolved the issue by 

browser.executeScript('arguments[0].click()', element) instead of element.click()
