### ISSUE TITLE
visibility_of_all_elements in expected conditions broken

### ISSUE THREAD

**Issue by doktorj2501** [SeleniumHQ/selenium#4666]
Traceback (most recent call last):
  File "/home/ec2-user/jcdc-website-development/sel/test-success.py", line 32, in testSuccess
    results[res_pos] = tt.linkcheck(tt.au_link,tt.au_exp_text)
  File "/home/ec2-user/jcdc-website-development/sel/successobj.py", line 132, in linkcheck
    wait(self.driver, 60).until(EC.visibility_of_all_elements_located)
AttributeError: 'module' object has no attribute 'visibility_of_all_elements_located'

## Meta -
OS:  Windows Server 2012

Selenium Version:  3.5.0

Browser:  Chrome

Browser Version:  Latest

## Steps to reproduce - Create test case with location strategy that uses EC visibility_of_all_elements
eg:   wait(self.driver, 60).until(EC.visibility_of_all_elements_located)
get this error

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
Sounds like you're using an older version, I believe this was added in `3.4.0`

**Comment by doktorj2501** [comment]
Yup. For some reason I had a 3.0 hub that was running and ps -u wasn't picking it up. Sorry.

**Comment by doktorj2501** [comment]
Spoke too soon. Started up 3.5 hub, made sure that the hub said 3.5 on grid/console, re-ran test, and still got this:
  File "/home/ec2-user/jcdc-website-development/sel/successobj.py", line 132, in linkcheck
    wait(self.driver, 60).until(EC.visibility_of_all_elements_located)
AttributeError: 'module' object has no attribute 'visibility_of_all_elements_located'

**Comment by barancev** [comment]
`visibility_of_all_elements_located` is a class

Usage is like
```
wait(self.driver, 60).until(EC.visibility_of_all_elements_located((By.ID, "my-id")))
```

**Comment by doktorj2501** [comment]
How come it can't operate the same as presence_of_all_elements_located?

**Comment by doktorj2501** [comment]
because this: 
wait(self.driver, 60).until(EC.presence_of_all_elements_located)
totally works

**Comment by doktorj2501** [comment]
If it's a locator for one specific thing, then it shouldn't be _of_all_elements_located

'all' does not connote specificity.

I'm so tired of y'all being in bug denial. You should be aware you have a reputation for that.

**Comment by barancev** [comment]
If you want your issue to be accepted, please follow the rules. That's what I asked for in the very first comment.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also, take note that it's the issue tracker, not the support forum. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by lmtierney** [comment]
@doktorj2501 That's certainly uncalled for. We're all volunteers here taking time from our lives to help people, and it's very hard to diagnose issues without reproducible test cases.

`wait(self.driver, 60).until(EC.presence_of_all_elements_located)` certainly does not work, all it does is init the class with your `driver` as the locator and return the class instance

**Comment by lmtierney** [comment]
Also note, it does the same thing for visibility, which is why I suspect your _python_ bindings (this has nothing to do with grid), are old. What version of the python bindings are you on?

```
>>> WebDriverWait(driver, 60).until(EC.visibility_of_all_elements_located)
<selenium.webdriver.support.expected_conditions.visibility_of_all_elements_located object at 0x105268190>
```

**Comment by doktorj2501** [comment]
That may indeed be the case. I am no longer in office, but I will try that Monday. Thanks and sorry.

**Comment by doktorj2501** [comment]
Yup. It was old bindings. To those who gave good advice, thanks.
