### ISSUE TITLE
Selenium 3.5.3-Java-GeckoDriver 0.18.0 : 'platformName' attribute returns "XP" where as W3C Specs mentions either "linux", "mac" or "windows"

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4668]
## Selenium 3.5.3-Java-GeckoDriver 0.18.0 : `platformName` attribute returns **`XP`** where as W3C Specs mentions either **`linux`**, **`mac`** or **`windows`**

[W3C Specs](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities) mentions the following:

In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.-capabilities), section [7.2 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.2-processing-capabilities):
> windows

where as GeckoDriver 0.18.0 returns **`XP`**

As per [mozilla/geckodriver/895](https://github.com/mozilla/geckodriver/issues/895)  and @andreastt  That sounds like a client API issue. 

As per #4565 and @barancev closed this in [1940813 ](https://github.com/SeleniumHQ/selenium/commit/19408132593577014e28ddab5f7053019e4fc001)

But still seems out of sync.

## Meta -
OS:  Windows 8 Pro, 64 bit
Selenium Version:  3.5.3
Browser:  Mozilla Firefox
Browser Version:  55.0.3 (64-bit)

## Steps to reproduce -
Minimal Code Block : 
```
import java.util.Map;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.RemoteWebDriver;

public class WEBDRIVER_platformName
{
	public static void main(String[] args) 
	{
		String attribute = "platformName";
		System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
		WebDriver driver =  new FirefoxDriver();
                Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
                Map<String, ?> map = cap.asMap();
                Object value = map.get(attribute);
                System.out.println("Key : " + attribute + " Value :"+ value);
               driver.quit();
 	}
}

```

Console Output : 
`Key : platformName Value :XP`

**Comment by andreastt** [comment]
We return `Services.sysinfo.getProperty("name").toLowerCase()` from XPCOM for `platformName`, which is a more specific version of the requested platform. This is behaving according to the specification.

**Comment by Debanjan-B** [comment]
Thanks @andreastt 

Can please point me to the documentation of this implementation:

    Services.sysinfo.getProperty("name").toLowerCase()

I am unable to resolve `Services` in my IDE. Please suggest the required imports.

**Comment by Debanjan-B** [comment]
Additionally, it is observed that Java Client still supports `getBrowserName()`, `getPlatform()` and `getVersion()` methods. Though `getBrowserName()` and `getVersion()` returns exact results but `getPlatform()` fails.

**Comment by andreastt** [comment]
Let me clarify a bit. Through capabilities you request a given platform from a matrix. The remote end does it best at matching that, but the returned `platformName` capability can be something _more specific_ than what you requested.

For example, if you request `windows` you might end up getting `windows_nt` or `windows_vista` back.

You’re looking for [Services.jsm](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Services.jsm) or [`nsIPropertyBag2`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPropertyBag2) for documentation on `Services.sysinfo`. It’s a Gecko internal.
