### ISSUE TITLE
Selenium 3.5.3-Java-IEDriverServer 3.5.1 : 'platformName' attribute returns "XP" where as W3C Specs mentions either "linux", "mac" or "windows"

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4669]
## Selenium 3.5.3-Java-IEDriverServer 3.5.1 : `platformName` attribute returns **`XP`** where as W3C Specs mentions either **`linux`**, **`mac`** or **`windows`**

[W3C Specs](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities) mentions the following:

In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.-capabilities), section [7.2 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.2-processing-capabilities):
> windows

where as IEDriverServer 3.5.1 returns **`XP`**

As per #4526 and this [comment](https://github.com/SeleniumHQ/selenium/issues/4526#issuecomment-328199607) latest `IEDriverServer` is w3c compatible. But seems out of sync.

## Meta -
OS:  Windows 8 Pro, 64 bit
Selenium Version:  3.5.3
Browser:  Internet Explorer
Browser Version:  10.0 (64-bit)

## Steps to reproduce -
Minimal Code Block : 
```
import java.util.Map;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.RemoteWebDriver;

public class WEBDRIVER_platformName
{
	public static void main(String[] args) 
	{
		String attribute = "platformName";
		System.setProperty("webdriver.ie.driver", "C:\\Utility\\BrowserDrivers\\IEDriverServer.exe");
		WebDriver driver =  new InternetExplorerDriver();
                Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
                Map<String, ?> map = cap.asMap();
                Object value = map.get(attribute);
                System.out.println("Key : " + attribute + " Value :"+ value);
               driver.quit();
 	}
}

```

Console Output : 
`Key : platformName Value :XP`

**Comment by lmtierney** [comment]
That list is not final, it is an example. It even states in the spec:

```
This list is not exhaustive.

When returning capabilities from New Session, it is valid to return a more specific platformName, allowing users to correctly identify the Operating System the WebDriver implementation is running on.
```

**Comment by Debanjan-B** [comment]
Thanks @lmtierney But either way I think there is something wrong in the method calls because, while I execute this scenario on **`WIN8`** system the Java client is picking up **`XP`**, which is not correct. Where as Java Client intelligence does differentiates between **`Platform.WINDOWS`**, **`Platform.WIN8`**, **`Platform.WIN8_1`** and **`Platform.WIN10`**

![capability](https://user-images.githubusercontent.com/26503213/30267439-380801c0-9700-11e7-810b-046138d62b0d.png)

**Comment by barancev** [comment]
Selenium Grid uses `platformName` capability to find the best node for a new session.

Concrete drivers (like `InternetExplorerDriver` or `FirefoxDriver`) simply ignore this capability. They run a browser on the local machine, no matter what the current platform is.

`platformName` capability returned by a driver in the response to a new session request is totally unrelated to `platformName` capability passed to the driver constructor.

But, yes, `XP` is a wrong answer. It should be `WINDOWS`.
