### ISSUE TITLE
version 3.5.3 changed response when called via REST

### ISSUE THREAD

**Issue by Kreny** [SeleniumHQ/selenium#4672]
OS:  Windows 8.1
Selenium Version:  3.5.3
Browser:  Chrome

Selenium server changed response in 3.5.3 (in compare with 3.4.0). Please see bellow an example

## Expected Behavior -
{
   "state": "success",
   "sessionId": "ce0112a2-9f87-4be1-81b7-b8adde0bc6c5",
   "hCode": 16564417,
   "value": "rgba(0, 0, 0, 1)",
   "status": 0
}
## Actual Behavior -
{
   "sessionId": "c8d2d22ee906b28d8f8e39a2ff419076",
   "status": 0,
   "value": "rgba(0, 0, 0, 1)"
}
## Steps to reproduce -
GET http://[server]:[port]/wd/hub/session/{session id}/element/{element id}/css/color

If this change is by design, is it possible to return "state" element to the response please?
I have selenium framework built around these rest calls and I am using "state" values in responses.

**Comment by shs96c** [comment]
The text-based "state" field was a legacy of the early work to do with implementing the w3c spec. With 3.5, we moved to simply passing the response from the remote end (geckodriver in this case, I'd imagine) back to the user.

Your framework should either rely on the [JSON Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol), or (preferably) the [W3C spec](https://w3c.github.io/webdriver/webdriver-spec.html) protocol.

**Comment by MadLittleMods** [comment]
In my case, I was relying on `hCode`/`hashCode` to relate some data to the HTTP request which is no longer available in Selenium `>=3.5.0`. I had to pin down my Docker image to `selenium/standalone-chrome:3.4.0-francium` for now.

**Comment by shs96c** [comment]
The `hCode`/`hashCode` was even more accidental --- an artefact of the way that our JSON encoder originally worked. It's the java hashcode of an `Object` and isn't ever going to be stable. The best thing to find is the `sessionId`, which is consistent for the entire session.

**Comment by Kreny** [comment]
Hi also .../elements and ..../element response has changed, now it returns

{
   "sessionId": "8e9294499fa4d6327e162a584450450d",
   "status": 0,
   "value":    [
      {"ELEMENT": "0.97781068070811-40"},
      {"ELEMENT": "0.97781068070811-41"}
   ]
}

What is "0.97781068070811"? I assume that "40" and "41" is element id. 

Thank you,

br, Vladan
