### ISSUE TITLE
Getting POP UP with Failed to load extension from: C:\Users\<user>\AppData\Local\Temp\scoped_dir<number>\internal. Loading of unpacked extensions is disabled by the administrator.

### ISSUE THREAD

**Issue by bashettiwarrajesh** [SeleniumHQ/selenium#4675]
## Meta -
OS:  Windows
Selenium Version:  3.4.0
Browser:  Chrome

Hello, 
Need one information, please. I'm getting below chrome information message in the pop up when we instantiate the chrome browser and I know this can be resolved by adding below mentioned code and it did worked in my previous project which was custom based framework . And right now we are trying to automate new application with serenity-bdd-cucumber combination one , can any one help me to know how this can be dealt in serenity bdd project.

Error:
Getting POP UP with Failed to load extension from: C:\Users\<user>\AppData\Local\Temp\scoped_dir<number>\internal. Loading of unpacked extensions is disabled by the administrator.

Code in my previous project:
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
			ChromeOptions options = new ChromeOptions(); 
			Map<String, Object> prefs = new HashMap<String, Object>();
			prefs.put("profile.default_content_setting_values.notifications", 0);
			options.setExperimentalOption("prefs", prefs);
			options.addArguments("disable-infobars");
			options.setExperimentalOption("excludeSwitches", Arrays.asList("enable-automation"));
			options.addArguments("--start-maximized");
			capabilities.setCapability(ChromeOptions.CAPABILITY, options);
			capabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, Boolean.TRUE);
			System.setProperty("webdriver.chrome.driver",".\\chromedriver.exe");              
			return new ChromeDriver(capabilities);    

Q1) What configuration details needs to be added in the serenity property file in order to disable this message, we have already tried with below lines but no luck
          chrome_preferences.profile.default_content_setting_values.notifications=0
         chrome_preferences.profile.default_content_setting.popups=0
Q2) Do we have any other approach.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
