### ISSUE TITLE
IEDriver crashes on getting log

### ISSUE THREAD

**Issue by dr29bart** [SeleniumHQ/selenium#468]
Java sample to reproduce the problem:
```Java
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.logging.LogType;

public class NewClass {

    public static void main(String[] args) {
        InternetExplorerDriver driver = new InternetExplorerDriver();
        driver.manage().logs().get(LogType.BROWSER);
        driver.quit();
    }
}
```
[Here](https://gist.github.com/dr29bart/500ac5dbef6b823d25eb) is the stack trace

**Comment by jimevans** [comment]
The IE driver does not support getting logs of any kind. Those commands have not been implemented. They will be implemented only when the server-side API is properly specified.
