### ISSUE TITLE
I cannot upload files with selenium web driver.

### ISSUE THREAD

**Issue by rleaplaza** [SeleniumHQ/selenium#4681]
I have a problem uploading a file via selenium web driver v.3.5.3 in firefox 55.0.3
Geckodriver 0.18.0
Both of the instructions are correct.:
   WebElement elem=driver.findElement(By.xpath("//input[@type='file']"));
   elem.sendKeys("C:\\opt\\formatos_excel_importacion\\prueba.txt");
In Google chrome it works fine, but it doesn't do the same in firefox.
![2017-09-11 15_07_03-tests - d__tests - tests - _src_testsolicitudchrome java - intellij idea](https://user-images.githubusercontent.com/20775668/30292108-f67c085c-9702-11e7-9fb9-c97b9c95a2ee.png)
The error says: Exception in thread "main" org.openqa.selenium.InvalidArgumentException: File not found: C:\opt\formatos_excel_importacion\prueba.txt

**Comment by jithinmatthew** [comment]
Please check this issue.
https://github.com/mozilla/geckodriver/issues/858

This configuration set works for me..!!
Geckodriver - 0.17.0
FireFox - 54.0 (64-bit)
Os  - Mac
Selenium Version - v.3.5.3

**Comment by barancev** [comment]
`File not found: C:\opt\formatos_excel_importacion\prueba.txt`

**Comment by rleaplaza** [comment]
Thanks for the advices, I found the solution to my problem.
FirefoxProfile profile=new FirefoxProfile();
        profile.setPreference("dom.file.createInChild",true);
        DesiredCapabilities capabilities=DesiredCapabilities.firefox();
        capabilities.setCapability(FirefoxDriver.PROFILE,profile);
        driver=new FirefoxDriver(capabilities);
Now I can upload files normally.

**Comment by rakeshnambiar** [comment]
Hi @rleaplaza Have you tried this with Chrome browser? I am facing similar problem with chromedrive latest version & browser version version: 70.0.3538.110.
