### ISSUE TITLE
Element is not clickable in Chrome Headless 

### ISSUE THREAD

**Issue by mh884** [SeleniumHQ/selenium#4685]
I have a problem with clicking on the element from headless Chrome this call worked some time Without Headless Chrome and does not work at all with Headless 

**Call**
driver.FindElement(By.Id("createBtn"))

**Element**
{Element (id = 0.18579689918655928-11)}
    Coordinates: {OpenQA.Selenium.Remote.RemoteCoordinates}
    Displayed: true
    Enabled: true
    Id: "0.18579689918655928-11"
    Location: {X = 808 Y = 343}
    LocationOnScreenOnceScrolledIntoView: {X = 808 Y = 343}
    Selected: false
    Size: {Width = 121 Height = 40}
    TagName: "a"
    Text: "Create"
    WrappedDriver: {OpenQA.Selenium.Chrome.ChromeDriver}

**Error:**
Message: System.InvalidOperationException : unknown error: Element is not clickable at point (868, 363)
  (Session info: headless chrome=61.0.3163.79)
  (Driver info: chromedriver=2.31.488763

**Comment by robinbobin25** [comment]
+1 Have similar issue with chrome Version 61.0.3163.79 (Official Build) (64-bit) and Selenium version: '3.5.3'

**Comment by Shkvarka** [comment]
Same issue here, but in UI mode, tried Selenium 3.4.0 and 3.5.3, Chrome Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by barancev** [comment]
Please retest with chromedriver 2.32

**Comment by Shkvarka** [comment]
Alexey, yes, it fix the issue. Thank you

**Comment by HartBlanc** [comment]
I'm still having this issue in 2.34

**Comment by jericpo** [comment]
Also with 2.35

**Comment by wilsonfcit** [comment]
Also with 2.35!

**Comment by WaldenLian** [comment]
I also have this issue with chromedriver 2.35.

**Comment by SamCosta1** [comment]
Also with 2.35

**Comment by Rockster160** [comment]
Also with 2.35.528157

**Comment by okunetskyi-amplify** [comment]
Same issue with chrome  64.0.3282.186 and chrome driver 2.36

**Comment by yukihariguchi** [comment]
Also with 2.36.540469

**Comment by caiopsouza** [comment]
I had the same issue and noticed that if you use the param "app" when creating the driver instance the page won't load.

**Comment by pakogn** [comment]
Hi!

I just faced the problem and I found a workaround.

running javascript

document.forms["formId"]["radioId"].checked=true;


this solved my problem, also with headless.

greetings!

**Comment by mattias-palm** [comment]
2.42 as well. I don't know if this is the reason for the issue but it's happening on a page with an iframe. Everything inside the iframe works fine, but not on the parent outside of it.

**Comment by tomaszwojciechowski** [comment]
I suggest reopening this issue.

**Comment by baash05** [comment]
Seeing this issue right now.

**Comment by ltiritilli** [comment]
It worked for me after adding:
```
options.addArguments("--window-size=1920,1080");
options.addArguments("--start-maximized");
options.addArguments("--headless");

```

**Comment by unalilker** [comment]
Hi @ltiritilli,

It just worked like a charm with that arguments. 

Thanks a lot for your solution

**Comment by animagiq** [comment]
> It worked for me after adding:
> 
> ```
> options.addArguments("--window-size=1920,1080");
> options.addArguments("--start-maximized");
> options.addArguments("--headless");
> ```

worked for me!thx a lot

**Comment by janmohammadi** [comment]
> It worked for me after adding:
> 
> ```
> options.addArguments("--window-size=1920,1080");
> options.addArguments("--start-maximized");
> options.addArguments("--headless");
> ```

Worked for me very well! **But why?!?!?!!**

**Comment by mtclimberguy** [comment]
Seeing this in Selenium ChromeDriver 2.45.615355 and Chrome 71.0.3578.98. Using in RSpec for Ruby on Rails. I can confirm that this is with a Stripe iframe on the page.

I tried adding the additional options like so, but still got the error:
`Capybara.register_driver(:headless_chrome) do |app|`
  `capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(`
      `chromeOptions: { args: %w[headless disable-gpu, window-size=1920,1080, start-maximized] }`
`  )`

  `Capybara::Selenium::Driver.new(`
      `app,`
      `browser: :chrome,`
      `desired_capabilities: capabilities`
  `)`
`end`

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium project: https://bugs.chromium.org/p/chromedriver
