### ISSUE TITLE
Add Firefox Developer Edition fallback

### ISSUE THREAD

**Issue by xmo-odoo** [SeleniumHQ/selenium#4687]
## Meta -
OS:  OSX 10.11.6
Selenium Version: selenium-python 3.4.3 
Browser:  Firefox Developer Edition 56.0b10

## Issue -
In its process to discover the Firefox binary, on Darwin WebDriver currently looks up `/Application/Firefox.app` and `~/Applications/Firefox.app`.

On developer machines, it wouldn't be too unlikely to have [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) installed as it provides additional devtools and features, but if it *replaces* Firefox on the machine WebDriver will not work.

## Solution
Add `/Application/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin` to the lookup list.

**Comment by p0deje** [comment]
Looking up binary is not a responsibility of Selenium anymore - this is now handled by [GeckoDriver](https://github.com/mozilla/geckodriver). You could try raising this to GeckoDriver's bug tracker, but I'm not sure it's going to be accepted assuming you can easily handle it on client side:

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox import Options

options = Options()
options.binary = "/Application/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin"
driver = Firefox(firefox_options=options)
```
