### ISSUE TITLE
Error handling when no Firefox binary is found

### ISSUE THREAD

**Issue by xmo-odoo** [SeleniumHQ/selenium#4688]
## Meta -
OS:  OSX 10.11.6
Selenium Version: selenium-python 3.4.3
Browser: Firefox Developer Edition 56.0b10

## Issue -
On Windows and OSX, if no firefox binary is found (e.g. due to #4687) `_get_firefox_start_cmd` will return an empty string and ultimately an unclear message about capabilities ("Unable to find a matching set of capabilities") rather than the clear RuntimeException it raises for generic unices.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by xmo-odoo** [comment]
1. have firefox not be installed
2. run selenium FirefoxDriver

Observed:
"Unable to find a matching set of capabilities" error

Expected:
RuntimeError indicating it could not find Firefox

**Comment by barancev** [comment]
Selenium receives this error message from geckodriver.
We should not change anything on Selenium side, the issue should be fixed in geckodriver.
Follow this issue for the progress: https://github.com/mozilla/geckodriver/issues/832
