### ISSUE TITLE
Export PDF with Chrome/Chromium

### ISSUE THREAD

**Issue by eduardohmg** [SeleniumHQ/selenium#4690]
## Meta -
OS: Windows Server 2008 and Linux (CentOS)
Selenium Version:  3.5.3
IDE: Eclipse
Language: Java 8
Browser:  Chrome and Chromium
Browser Version: 60.0.3112.113 (64bit)

## Expected Behavior -

Export page as PDF using a simple command like "getScreenshot()" for screenshot.

Ex: "getPDF()"

## Actual Behavior -

Does not have this feature.

## Steps to reproduce -

Does not exist in the documentation.

Obs: Chrome and Chromium already has this feature. Selenium just have to implement it.

Thank you.

**Comment by barancev** [comment]
Selenum API follows W3C WebDriver specification [1], you can raise an issue on the spec to suggest this enhancement.

[1] https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by gumatias** [comment]
hi @eduardohmg! have you find a workaround? I just found this out and seems unfortunate that there's little incentive here. thanks!

**Comment by eduardohmg** [comment]
Hello @gumatias. I'm using Puppeteer (JS) instead of Selenium (Java).

**Comment by gumatias** [comment]
thanks, @eduardohmg ! FWIW, we started experimenting wish Google Cloud Functions and Puppeteer and we've had a great success so far 😄 https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine
