### ISSUE TITLE
[SafariDriver] Random Unknown error

### ISSUE THREAD

**Issue by AlexShemeshWix** [SeleniumHQ/selenium#4692]
## Meta -
OS:  
Mac OS Siera 10.12.5
Selenium Version:  
3.4.0
Browser:  
Safari 10
Browser Version:  
10

## Expected Behavior -
Tests run 100% of the time no errors

## Actual Behavior -
Tests randonly fail on Safari browser running on Mac OS
## Steps to reproduce -

I have CI system. It consists ofJenkins Master server (version 2.60.2) running on Ubuntu 16.04Jenkins slaves Swarm Slave (version 3.4.1) running on Ubuntu 16.04Selenium hub (version 3.4.0) running on Ubuntu 16.044 Selenium nodes for Safari Browser (version 3.4.0) Running on Mac OS Siera 10.12.5 . With Safari 10.Im testing Java Script project that uses Mocha+Karma to run tests.Most of the time everything is working as it should. But sometimes i have error like this one.

`{"message":"[get(\"http://my-jenkins-slave-hostname:9876/?id=39481\")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $","status":13,"cause":{"value":{"stacktrace":"com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient...`

It looks like some nodes of selenium sometimes fail randomly. All nodes are exact replicas of same image (Im using Mac Stadium to manage Mac OS nodes)

Ive tried to configure Karma to give more details in logs, ive tried to increase timeouts, but no luck. Error message stays the same. How can i troubleshoot such problem? Any ideas?

**Comment by barancev** [comment]
Please provide the log from the node where the error occured.

**Comment by barancev** [comment]
Closing the issue due to inactivity.
