### ISSUE TITLE
[Chrome] interaction with Lighthouse

### ISSUE THREAD

**Issue by isantolin** [SeleniumHQ/selenium#4697]
## Meta -
**OS:**  
Any
**Selenium Version:**  
Any
**Browser:**  
Chrome

"Lighthouse" is a new tool bundled in Chrome > 60 Developer Tools that audit sites. There is any possibility to add a function to interact with that?

![image](https://user-images.githubusercontent.com/264640/30397947-e99974b4-98a4-11e7-923f-8f4a2abb9687.png)

[https://hackernoon.com/the-new-chrome-devtool-feature-you-want-to-know-about-c0d2371151d6](https://hackernoon.com/the-new-chrome-devtool-feature-you-want-to-know-about-c0d2371151d6
)

**Comment by barancev** [comment]
This issue should be reported to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by isantolin** [comment]
@vikramvi No response yet
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2018&q=Lighthouse&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by vikramvi** [comment]
@isantolin  Thanks for response.
 
Currently I'm using **https://github.com/godaddy/timings** to capture page load timing.  But some of my front end dev believe **lighthouse** is better tool. Thus I need to do comparison study.

**Comment by vanux** [comment]
You can also report it here - https://github.com/GoogleChrome/lighthouse
