### ISSUE TITLE
How to integration sikuli with Selenium Grid?

### ISSUE THREAD

**Issue by sguess** [SeleniumHQ/selenium#4699]
OS:  Windows 2012R2
Selenium Version:  3.5.3
Browser:  Chrome 
Sikuli Version: 1.1.0

We have 2 selenium grid node servers, and one selenium hub server. How to integration sikuli to selenium grid and run sikuli in Grid Node server?

We need to use selenium grid to test some web pages which they are **Applet page and Flex page.**  We need to use sikuli to find some button. 

The selenium couldn't transfer the images from my application to Grid Node server, and it couldn't found any button on Applet page and Flex page.

Do you have a solution for integration sikuli with Selenium Grid?
Do you have other solution for test Applet page and Flex page by Selenium Grid? 
(The Grid nodes in different server)

Thanks,
Daniel

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
