### ISSUE TITLE
use "selectwindow" command , can not control new window tab,how to use control new window in selenium IDE?

### ISSUE THREAD

**Issue by nickz06** [SeleniumHQ/selenium#4701]
## Meta -
OS:  

Selenium Version:  2.9.1

Browser:  firefox 54.0.1 64 bit

Browser Version:  

## Actual Behavior -
show "Could not find window with title" strings

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
