### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: performActions

### ISSUE THREAD

**Issue by Krishna077** [SeleniumHQ/selenium#4705]
## Meta -
OS:  
OS X Yosemite
10.10.5

Selenium Version:  
Selenium - 3.3.3
Python - 3.5

Browser:  
Firefox 49.0
Geckodriver - v0.18.0

## Expected Behavior -
Click and hold of a component

## Actual Behavior -
selenium.common.exceptions.WebDriverException: Message: performActions

tried with Geckodriver 0.15.0 as well and still getting the same error.

## Steps to reproduce -
element = driver.find_element_by_xpath("//*[@data-drop-position='0:3']")
action = ActionChains(driver).click_and_hold(element)
action.perform()

**Comment by barancev** [comment]
geckodriver 0.18 requires firefox 53+ according to release nodes,

**Comment by Krishna077** [comment]
Thanks. Just upgraded Selenium to 3.5.0 and Firefox to 55.0.3 , it worked fine.
