### ISSUE TITLE
is it still necessary to deploy a standalone-server for testing by using Chrome Driver

### ISSUE THREAD

**Issue by caryyu** [SeleniumHQ/selenium#4706]
As i guess, Chrome Driver has already been implemented Web Specification protocol inside, so i'm a little bit confused wether or not using the standalone-server for my test environment. what if i just only use Chrome Driver to do, Can  i ?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
