### ISSUE TITLE
return overlapping element instead of unknown error

### ISSUE THREAD

**Issue by akostadinov** [SeleniumHQ/selenium#4707]
Hello, there is a well known scrolling issue with sticky headers/footers or other elements overlapping the element we want to click. #1687 and #1740 explain the issue well.

At the moment selenium is returning a generic error that is not so helpful if one wants to automatically workaround such occurrences. It would be more useful if there is a special error type when this happens and the overlapping element to be extractable from the exception object. For example:

```
begin
  browser.find_element(...).click
rescue WebDriver::Error::OverlappingElementError => e
  el = e.overlapping_element
  # some processing to scroll past `el` margins
end
```

## Meta -
OS:  all
Selenium Version:  selenium-webdriver-3.5.1 / ruby
Browser:  Firefox
Browser Version: 52ESR  

## Expected Behavior -
```
Selenium::WebDriver::Error::OverlappingElementError: ...
error.overlapping_element -> #<Selenium::WebDriver::Element:0x..fa5c4141b03367db4 id="{1b2b29b1-eb8b-4039-8861-bee67c9b72e3}">
```
## Actual Behavior -
```
#<Selenium::WebDriver::Error::UnknownError: Element <a href="" class="add-row-link ng-binding" role="button" aria-label="Add row" ng-click="onAddRow()"></a> is not clickable at point (492.5, 11.166671752929688). Other element would receive the click: <nav class="navbar navbar-pf-vertical" role="navigation"></nav>>
```

## Steps to reproduce -
see #1740

**Comment by p0deje** [comment]
I lean towards not adding it because:

* you can already understand what element overlaps from the error message;
* this requires all drivers to return such an overlapping element which means this needs to be added the [click part of webdriver spec](https://w3c.github.io/webdriver/webdriver-spec.html#element-click);

I'm going to keep this open so that other committers can take a look.

**Comment by barancev** [comment]
click part of the spec says: "If the element’s center point is obscured by another element, an element click intercepted error is returned"

**Comment by akostadinov** [comment]
Selenium already returns the element intercepting the click partially as a string. That made me thing the element is known. If one wants to write code that automatically scrolls page around to avoid the overlap, then human readability is not so useful.

From  above comments, sounds like there would be no issue to return a special error instead of the generic `UnknownError`. And if some drivers don't support figuring out the exact element, then fine, but would be useful to have the element reference as part of the `OverlappingElementError` when that is possible.

**Comment by p0deje** [comment]
The problem here is that we can't figure out this element in bindings. The element is known only for the driver (ChromeDriver, GeckoDriver) so it has to return it in the response to the click command. Since spec doesn't specify this behavior, it first has to be added to the spec so later it can be implemented both in drivers and bindings.

**Comment by akostadinov** [comment]
Got it, thank you for your thorough explanation. Can we at least have a special error type then?

Also, do you know how can I request a change in the webdriver spec?

**Comment by p0deje** [comment]
> Got it, thank you for your thorough explanation. Can we at least have a special error type then?

WebDriver already has `ElementClickIntercepted` error. However, ChromeDriver responds with unknown error. GeckoDriver should raise `ElementClickInterceptedError` correctly.

> Also, do you know how can I request a change in the webdriver spec?

You can add issue to https://github.com/w3c/webdriver/issues.

**Comment by p0deje** [comment]
Closing as this needs to addressed in the spec first.

**Comment by akostadinov** [comment]
FYI I couldn't make geckodriver 0.18.0 return an error with an overlapping element. Will be able to test that when proper interactability checks are implemented there.
