### ISSUE TITLE
XHR ERROR: URL = XXX Response_Code = 403 Error_Message = Forbidden

### ISSUE THREAD

**Issue by saharawolf** [SeleniumHQ/selenium#4708]
Hello, 

I am receiving the error above running a test for an http website.
i am running selenium server standalone vers 2.45.0.jar as it was the only version i successfully make it work.
firefox 42.0
my scénario is in html : 
<link rel="selenium.base" href="http://mywebsite" />
<title>New Test</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">New Test</td></tr>
</thead><tbody>
<tr>
        <td>open</td>
        <td></td>
        <td>/</td>
</tr>
<tr>
        <td>close</td>
        <td></td>
        <td></td>
</tr>

</tbody></table>
</body>
</html>

any help ?

thank you

**Comment by shs96c** [comment]
Could you please supply a complete, reproducible test case, and detail the error you're receiving. We need enough information to reproduce the problem ourselves before we can debug it.

**Comment by barancev** [comment]
Closing the issue due to inactivity.
