### ISSUE TITLE
IE11 can't find elements

### ISSUE THREAD

**Issue by jnfsmile** [SeleniumHQ/selenium#471]
Using selenium with C# on .NET.

The command `driver.FindElements(By.CssSelector("*<selector>*"))` throws:

`Finding elements with css selector == *<selector>*returned an unexpected error (UnexpectedJavaScriptError)` (space missing in original).

The command `driver.FindElements(By.TagName("*<tag>*"))` throws:

`Finding elements with tag name == *<tag>*returned an unexpected error` (space missing in original).

The command `driver.FindElements(By.XPath("*<xPath>*"))` throws:

`The xpath expression '*<xPath>*' cannot be evaluated or does notresult in a WebElement`

...

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jimevans** [comment]
You've given no concrete examples of code that actually fail. Furthermore, the symptoms you describe are far from globally occurring. Given that, there is no action that can be taken on this issue.

**Comment by jnfsmile** [comment]
I've given several examples of code that fails. Here is a full program:

    driver = (IWebDriver)Activator.CreateInstance(typeof(InternetExplorerDriver));
    driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));
    driver.Navigate().GoToUrl("https://github.com/");
    int c = driver.FindElements(By.CssSelector("button.btn-primary")).Count;

the last line throws the `InvalidOperationException` error

    Finding elements with css selector == button.btn-primaryreturned an unexpected error (UnexpectedJavaScriptError)

**Comment by barancev** [comment]
It runs well:
![20-04-2015 15-21-44](https://cloud.githubusercontent.com/assets/617090/7229874/34db97d2-e771-11e4-9708-09d1a3acd719.png)

Please visit [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) if you need help detecting what's misconfigured in your environment.
