### ISSUE TITLE
Chromedriver slower with --headless option

### ISSUE THREAD

**Issue by khersonIT** [SeleniumHQ/selenium#4713]
## Meta -
OS:  
Windows 7 x64
Selenium Version:  
3.5.2
Browser:  
Chrome
Browser Version:  
60.0.3112.113

## Expected Behavior -
Try to use --headless option with chromedriver to speed up scripts.
## Actual Behavior -
All scripts in headless mode run twice as long.
## Steps to reproduce -
Any simple tests. I use 2 get requests, load cookies, put data on site and request to site to generate one dynamic page. For me it was more then 1 minute with --headless option and 29 sec without it.

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://sites.google.com/a/chromium.org/chromedriver/help
