### ISSUE TITLE
Unable to click using chromedriver without scrolling into the view

### ISSUE THREAD

**Issue by mishrav** [SeleniumHQ/selenium#4714]
## Meta -

I updated chromedriver 2.32 and chrome to 61 and started getting error 

OS:  
`Linux 4.4.0-1032-aws x86_64`

Selenium Version:  
`2.3.0, Python`

Browser:  
`chromedriver=2.32.498513  `

WebDriverException: Message: unknown error: Element is not clickable at point (106, 1302)

``` (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.4.0-1032-aws x86_64)
Browser Version:  
chrome=61.0.3163.91
```
## Actual Behavior -
WebDriverException: Message: unknown error: Element is not clickable at point (106, 1302)

## Steps to reproduce -
Unable to click the element without scrolling into the view. 

Chrome driver release notes: `https://sites.google.com/a/chromium.org/chromedriver/downloads`
```
Supports Chrome v59-61

Changes include:
Fixes a bug where Chromedriver fails to click due to page scrolling changes in Chrome 61+.
Fixes a bug where Chromedriver fails to delete cookies in Chrome 62+.
Implemented spec-compliant new session handshake.
Fixes a bug where Chromedriver fails to retrieve default prompt text in Chrome 62+.
Changes to the way automation extension is loaded on Mac and Windows.
The latest WebDriver atoms have been imported.
Supports new spec compliant endpoints for executing scripts.
Fixes a bug where Chromedriver fails to send characters 3 and # keys on Mac Chrome 62+.
Removed dependency of GLIBC 2.18.
Updates to capabilities processing as per new w3c spec.
Ensures sending keys to non-prompt dialog returns correct errors as per new w3c spec.
Ensure that file exists while sending keys to file input field.
For details, please refer to the notes. The latest version is recommended, and bugs will not be fixed in previous versions.
```

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by M0ns1gn0r** [comment]
Had the same problem until I realized that my tests still execute `chromedriver.exe` of the previous version. On 2.32.498550 the problem disappeared.
