### ISSUE TITLE
Hi I am not able to integrate existing Selenium drivers with Latest Salesforce Lightning Winter 2017 edition. It throws an error once user logs in. Sorry to interrupt is the error message popup with defined Error text.

### ISSUE THREAD

**Issue by latikakadam** [SeleniumHQ/selenium#4720]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by latikakadam** [comment]
Error in $A.getCallback() [null is not an object (evaluating 'navigator.appVersion.match(/(version)[/\s]([\d.]+)/i)')]

getKeyboardEventName()

doubleCheck()
Action failed: force:listViewManager$controller$handleResize [window.requestAnimationFrame is not a function. (In 'window.requestAnimationFrame', 'window.requestAnimationFrame' is undefined)]

handleResize()

handleResize()

update()

afterRender()

bound ()@[native code]

bound ()@[native code]

bound ()@[native code]

afterRender()

onXHRReceived()

bound ()@[native code]

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
