### ISSUE TITLE
maximise_window with headless selenium hangs indefinitely

### ISSUE THREAD

**Issue by andyjp94** [SeleniumHQ/selenium#4721]
## Meta -
OS:  
Ubuntu 16.04  
Selenium Version:  
3.4.3 
Browser:  
Firefox  

Browser Version:  
55.0.2 (64-bit) 

## Expected Behavior -
Using xvfb-run with a selenium python script so that it can run headless. Tried to maximise the window using maximise_window for screenshot purposes.
## Actual Behavior -
It hangs forever. If I use set_window_size then its perfectly happy. This is not a problem when using chrome.s
## Steps to reproduce -
```
apt-get install -y xvfb
wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
tar -xvzf geckodriver-v0.18.0-linux64.tar.gz 
cat >> test.py <<EOF
#!/usr/bin/env python3
from selenium import webdriver
browser = webdriver.Firefox(executable_path="./geckodriver")
browser.maximize_window()
EOF
chmod +x test.py
xvfb-run -a test.py
```

**Comment by barancev** [comment]
Please raise an issue on https://github.com/mozilla/geckodriver/issues
