### ISSUE TITLE
Wrong positions for all elements when display is not set to 100% in Windows

### ISSUE THREAD

**Issue by Sethiel** [SeleniumHQ/selenium#4725]
Selenium 2.40.0
Windows 10
Firefox 27.0.1

When the "Scale and layout" in Windows 10 is set to a different value than 100%, Selenium won't take this setting into account and all coordinates of all elements are therefore off.

Right-click on desktop in Windows, pick Display Settings, under tab "Display" there is a field labeled "Change the size of text, apps and other items" (changing this requires log off and log on to apply). Set this to 175% for example and see any previously valid tests to fail due to the scale not being into account.

**Comment by barancev** [comment]
It's expected behavior, Selenium can't calculate correct element position and size if they are scaled.

**Comment by q-jack** [comment]
Why is that so? Nowadays there are a lot of displays which are using the scale and layout function from windows. The browser engines are doing it correctly. What is the main problem to do it as well in selenium.
I just want to know if selenium will ever do it one day.

**Comment by luke-hill** [comment]
There is a wiki entry for this here: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver/_compare/0cf46848abd86f06876ee6ad0a41ee098c7327a0...74561c47d0300289087a9ea154164ffeb0e9b778

**Comment by q-jack** [comment]
thanks for the information.
Does is valid for all drivers, right? Because the article is about internetExplorerDriver
