### ISSUE TITLE
location_once_scrolled_into_view not working in ruby

### ISSUE THREAD

**Issue by matanmoda** [SeleniumHQ/selenium#4728]
## Meta -
OS:  MAC Sierra 10.12

Selenium Version:  3.5.2

Browser:  Chrome

Browser Version:  61

**Comment by lmtierney** [comment]
I cannot reproduce this. There was a change in how Chrome scrolled in Chrome 61 that required an update in chromedriver. Please make sure you're using chromedriver version `2.32` as that contains the fix.
