### ISSUE TITLE
unable to resolve this issue

### ISSUE THREAD

**Issue by vigneshjagan** [SeleniumHQ/selenium#4729]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -

1505934787013	addons.manager	DEBUG	Application has been upgraded
1505934787393	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1505934787397	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1505934787404	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1505934787407	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1505934787408	addons.manager	DEBUG	Starting provider: XPIProvider
1505934787408	addons.xpi	DEBUG	startup
1505934787410	addons.xpi	INFO	Mapping fxdriver@googlecode.com to C:\Users\vignesh\AppData\Local\Temp\anonymous191060962525605079webdriver-profile\extensions\fxdriver@googlecode.com
1505934787410	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: C:\Users\vignesh\AppData\Local\Temp\anonymous191060962525605079webdriver-profile\extensions\webdriver-staging
1505934787411	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1505934787412	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1505934787413	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1505934787413	addons.xpi	INFO	Mapping loop@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1505934787416	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1505934787416	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1505934787417	addons.xpi	DEBUG	Skipping unavailable install location app-system-local
1505934787418	addons.xpi	DEBUG	checkForChanges
1505934787419	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1505934787420	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
1505934787420	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1505934787427	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1505934787427	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1505934787428	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1505934787428	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1505934787429	addons.xpi	DEBUG	New add-on loop@mozilla.org in app-system-defaults
1505934787429	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1505934787430	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1505934787430	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1505934787431	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\vignesh\\AppData\\Local\\Temp\\anonymous191060962525605079webdriver-profile\\extensions\\fxdriver@googlecode.com","st":1505934784901,"mt":1505934784788}},"app-system-defaults":{"e10srollout@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1461279552000},"firefox@getpocket.com":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1461279552000},"loop@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\loop@mozilla.org.xpi","st":1461279552000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1461279552000}}}
1505934787443	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\vignesh\AppData\Local\Temp\anonymous191060962525605079webdriver-profile\extensions.json
1505934787444	addons.xpi-utils	DEBUG	New add-on fxdriver@googlecode.com installed in app-profile
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1505934787488	DeferredSave.extensions.json	DEBUG	Save changes
1505934787489	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1505934787492	DeferredSave.extensions.json	DEBUG	Starting timer
1505934787494	DeferredSave.extensions.json	DEBUG	Save changes
1505934787503	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1505934787510	DeferredSave.extensions.json	DEBUG	Save changes
1505934787511	addons.xpi-utils	DEBUG	New add-on loop@mozilla.org installed in app-system-defaults
1505934787520	DeferredSave.extensions.json	DEBUG	Save changes
1505934787521	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1505934787526	DeferredSave.extensions.json	DEBUG	Starting write
1505934787532	DeferredSave.extensions.json	DEBUG	Save changes
1505934787532	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1505934787533	addons.xpi-utils	INFO	Hiding the updated system add-ons.
1505934787533	addons.manager	DEBUG	Registering startup change 'installed' for fxdriver@googlecode.com
1505934787533	addons.xpi-utils	DEBUG	Make addon app-profile:fxdriver@googlecode.com visible
1505934787534	DeferredSave.extensions.json	DEBUG	Save changes
1505934787541	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1505934787555	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.0
1505934787555	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1505934787556	DeferredSave.extensions.json	DEBUG	Save changes
1505934787557	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1505934787561	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0
1505934787562	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1505934787562	DeferredSave.extensions.json	DEBUG	Save changes
1505934787563	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1505934787568	addons.xpi	DEBUG	Calling bootstrap method install on loop@mozilla.org version 1.2.6
1505934787568	addons.xpi-utils	DEBUG	Make addon app-system-defaults:loop@mozilla.org visible
1505934787569	DeferredSave.extensions.json	DEBUG	Save changes
1505934787569	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1505934787569	DeferredSave.extensions.json	DEBUG	Save changes
1505934787570	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"wmTUR4agYy5V","location":"app-profile","version":"3.5.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Users\\vignesh\\AppData\\Local\\Temp\\anonymous191060962525605079webdriver-profile\\extensions\\fxdriver@googlecode.com","installDate":1505934784901,"updateDate":1505934784901,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":3279485,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"48.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0,"seen":true}
1505934787570	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1505934787573	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"C6rDosWCqC55","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1461279552000,"updateDate":1461279552000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":4778,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1505934787574	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1505934787574	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"UiWPPkd9bKbc","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1461279552000,"updateDate":1461279552000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":893211,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1505934787574	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1505934787575	addons.xpi	DEBUG	Updating XPIState for {"id":"loop@mozilla.org","syncGUID":"_nDS0f0zrdCe","location":"app-system-defaults","version":"1.2.6","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Hello","description":"Web sharing for Firefox","creator":"Mozilla","homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\loop@mozilla.org.xpi","installDate":1461279552000,"updateDate":1461279552000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":4185303,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0a1","maxVersion":"46.*"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1505934787575	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1505934787575	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"er2O7x3gjgOl","location":"app-global","version":"46.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1461279552000,"updateDate":1461279552000,"applyBackgroundUpdates":1,"skinnable":true,"size":22006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"46.0","maxVersion":"46.0"}],"targetPlatforms":[],"seen":true}
1505934787576	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1505934787577	DeferredSave.extensions.json	DEBUG	Save changes
1505934787577	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1505934787577	addons.xpi-utils	DEBUG	Updating add-on states
1505934787578	addons.xpi-utils	DEBUG	Writing add-ons list
1505934787598	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1505934787600	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1505934787600	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1505934787601	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0
1505934787602	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1505934787603	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1505934787636	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1505934787636	addons.manager	DEBUG	Provider finished startup: XPIProvider
1505934787636	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1505934787636	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1505934787637	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1505934787637	addons.manager	DEBUG	Starting provider: GMPProvider
1505934787643	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1505934787644	addons.manager	DEBUG	Provider finished startup: GMPProvider
1505934787644	addons.manager	DEBUG	Starting provider: PluginProvider
1505934787644	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1505934787644	addons.manager	DEBUG	Provider finished startup: PluginProvider
1505934787645	addons.manager	DEBUG	Completed startup sequence
[GFX1]: Potential driver version mismatch ignored due to missing DLLs
Crash Annotation GraphicsCriticalError: |[0][GFX1]: D3D11 device creation failed: 0x887a0004 (t=8.30257)[GFX1]: D3D11 device creation failed: 0x887a0004
1505934789818	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1505934789818	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1505934789818	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1505934790218	DeferredSave.extensions.json	DEBUG	Write succeeded
1505934790218	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1505934790219	DeferredSave.extensions.json	DEBUG	Starting timer
1505934790240	addons.repository	DEBUG	No addons.json found.
1505934790241	DeferredSave.addons.json	DEBUG	Save changes
1505934790253	DeferredSave.addons.json	DEBUG	Starting timer
1505934790479	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1505934790479	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1505934790479	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1505934790485	DeferredSave.extensions.json	DEBUG	Starting write
1505934790488	DeferredSave.addons.json	DEBUG	Starting write
1505934790707	DeferredSave.extensions.json	DEBUG	Write succeeded
1505934791438	DeferredSave.addons.json	DEBUG	Write succeeded
Sep 21, 2017 12:43:19 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
JavaScript error: http://demoqa.com/selectable/, line 515: ReferenceError: accordion is not defined
cursor current location text is:Item 6
i was unable to resolve this issue
please help

**Comment by lmtierney** [comment]
How are we supposed to help? All you've given us is a stack trace. The issue template is there for a reason.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction case provided,
