### ISSUE TITLE
`isElementPresent()` won't resolve

### ISSUE THREAD

**Issue by khanh-nguyen** [SeleniumHQ/selenium#473]
The following test works for me:
```
var someElement = yield browser.$('.class-of-existing-element');
// perform test on someElement
```
However, if I only want to check if element is displayed, the following doesn't work
```
var elementPresent = yield browser.isElementPresent('.class-of-existing-element');
t.ok(elementPresent, 'element should present on page');
```
In fact, as a result of this latter code, I can see selenium spins up a webpage but stays forever without resolving and terminating the test. 
`isElementPresent` is documented [here](http://selenium.googlecode.com/git/docs/api/javascript/class_webdriver_WebDriver.html#isElementPresent). 

OS: Mac Maverick.

**Comment by lukeis** [comment]
the expected value being passed in is supposed to be a locator or an element.

You've passed in a String. You want to pass in a [Locator](http://selenium.googlecode.com/git/docs/api/javascript/class_webdriver_Locator.html) instead.

**Comment by jleyba** [comment]
As @lukeis mentioned, WebDriverJS doesn't support jquery selectors (guessing you're using protractor, which adds the `$` short cut).  Locator syntax is still pretty light weight though:

    browser.isElementPresent(By.css('.foo'));
    browser.isElementPresent({css: '.foo'});

**Comment by khanh-nguyen** [comment]
Awesome. Works for me. Thanks a lot for your quick response, guys. 
And, thanks for the detailed example, @jleyba. (we expanded webdriver that `$` )
