### ISSUE TITLE
Getting Error Message, "JavaScript Application"

### ISSUE THREAD

**Issue by elieabouzeid1** [SeleniumHQ/selenium#4731]
When I open Selenium IDE I get a popup message stating the following error. This is preventing me from recording or playing a script. Does anyone have any [suggestions?]
![capture](https://user-images.githubusercontent.com/32144937/30671277-09d928f2-9e34-11e7-9531-c6f07534859c.JPG)

 "There was an unexpected error. Msg: TypeError: Components.classes['@mozilla.org/supports-array;1'] is undefined
Url: chrome://selenium-ide/content/xul-utils.js, line: 36, column: 13
toXPCOMArray@chrome://selenium-ide/content/xul-utils.js:36:13
_loadSeleniumCommands@chrome://selenium-ide/content/treeView.js:200:55
initialize@chrome://selenium-ide/content/treeView.js:90:13
classCreate/<@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:23:7
Editor@chrome://selenium-ide/content/editor.js:170:19
SidebarEditor@chrome://selenium-ide/content/sidebar-editor.js:22:5
onload@chrome://selenium-ide/content/selenium-ide-sidebar.xul:1:1"

**Comment by barancev** [comment]
See #4406
