### ISSUE TITLE
Find Element By class is not working

### ISSUE THREAD

**Issue by engrasma1991** [SeleniumHQ/selenium#4734]
"Find Element by class is not working"
can anyone please tell what's wrong in my code?

public void pricing() throws Exception{

//Add Pricing Plan

driver.findElement(By.className("addbutton tooltips")).click();
}

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
