### ISSUE TITLE
Selenium is hanging when go to the site that have Basic Authentication

### ISSUE THREAD

**Issue by Trucnt** [SeleniumHQ/selenium#4735]
## Meta -
OS:  Windows 10
 
Selenium Version:  3.5.3
 
Browser:  Microsoft Edge
 
Browser Version:  Microsoft Edge 40.15063.0.0 (64-bit)

## Expected Behavior -
The selenium will run next step or throw an exception.

## Actual Behavior -
The selenium is hanging

## Steps to reproduce -
Can you please use the java code below to reproduce this issue:
```
public class TestSeleniumEdge extends KeepToFileText {

	public static void main(String[] args) {
		try {
			// set edge driver path
			System.setProperty("webdriver.edge.driver", "path\\MicrosoftWebDriver.exe");
			// create new EdgeDriver instance
			WebDriver webDriverEdge = new EdgeDriver();
			// go to site that have Basic authentication
			webDriverEdge.get("https://www.engprod-charter.net/");
			// selenium is hanging here
			// expected: the selenium run next step or throw an exception
			// TODO
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("Done!");
	}
```

**Please help to investigate and let me know if any questions.**
Thanks.

**Comment by barancev** [comment]
Egde issues should be reported to Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/support/

**Comment by eurekalopes** [comment]
Above reported issue by is happening with Chrome Version 65.0.3325.181 (Official Build) (32-bit) 
Selenium : 3.11.0
