### ISSUE TITLE
Chrome extension not being loaded by ChromeDriver

### ISSUE THREAD

**Issue by nadvolod** [SeleniumHQ/selenium#4736]
## Meta -
OS:  
Windows 10

Selenium Version:  
3.5.2
Browser:  
Chrome version 57
ChromeDriver version:
2.29

## Expected Behavior -
When I load Chrome browser using ChromeDriver, the extension should be loaded with the browser.
## Actual Behavior -
No extension is loaded with the browser. Also, the arguments that I pass in to Chrome don't work either.
## Steps to reproduce -
Simply try to instantiate a ChromeDriver with the versions of Selenium and chromedriver.exe and Chrome that I listed above. You will see that this doesn't work.

My code:
```
private IWebDriver GetChromeDriver(BrowserConfigurationOptions browserConfigOptions)
{
    var outPutDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
    var chromeDriverPath = Path.GetFullPath(outPutDirectory + @"\Drivers");

    var options = new ChromeOptions();
    options.AddExtension(outPutDirectory + @"\3.1.5_0.crx");
    options.AddArguments("disable-infobars");
    options.AddUserProfilePreference("credentials_enable_service", false);
    options.AddArgument("--kiosk");

    return new ChromeDriver(chromeDriverPath, options);
}
```

**Comment by barancev** [comment]
https://www.screencast.com/t/7RH7zDNAO -- I've successfully added evernote web clipper addon to chrome, it's selenium c# 3.5.2, chromedriver 2.32 and the chrome 61

**Comment by nadvolod** [comment]
Hi, that wasn't my bug. My bug is with **ChromeDriver 2.29** and **Chrome 57**. Meaning that Selenium 3.5.2 is not backwards compatible with an older ChromeDriver. So when I updated Selenium to a later version, it broke our tests.
It also worked for me with 2.32 and Chrome 60. But again, that's not the bug that I logged.

**Comment by barancev** [comment]
Selenium 3.5 is compatible with latest chrome 61 and chromedriver 2.32.
Is there any reason you want to use older chrome versions?

**Comment by nadvolod** [comment]
Yes, our current app supports up to Chrome 57.0. Higher versions of ChromeDriver don't support Chrome 57. So our only option is to use ChromeDriver 2.29.

**Comment by barancev** [comment]
If you want to use outdated chrome and chromedriver you have to use outdated selenium library too.
Selenium 3.4 is the last version that supports chromedriver 2.29

**Comment by nadvolod** [comment]
That's fine. I just want to make sure that there is no backwards compatibility expected for WebDriver and ChromeDriver then? If that's the case, then I understand and it's fine. If not, I just wanted to make you all aware of the issue so that it might help others in the future.

**Comment by barancev** [comment]
Yes, we are aware of this incompatiblity.
