### ISSUE TITLE
Very slow text entry on IEDriverServer 3.5.1

### ISSUE THREAD

**Issue by kroe761-zz** [SeleniumHQ/selenium#4737]
## Meta -
OS:  
Windows Server 2012
Selenium Version:  
3.5.3 (Java)
Browser:  
Internet Explorer
Browser Version:  
11

## Issue -

When running tests in IE11 via the Selenium Grid (hub is grid version 3.1.0, node is version 3.5.3), if I use IE Driver 32bit 3.5.1, I experience very slow sendkeys() action (as has been documented in the past).   When I switch to IE Driver 32bit 3.4.0, I do not experience this.   

I have spent some time researching solutions, and nothing I have found in Github, StackOverflow, etc works.  

#### Webdriver definition
`DesiredCapabilitiescaps = DesiredCapabilities.internetExplorer();
caps.setBrowserName("internet explorer");
caps.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, false);
caps.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
caps.setCapability(InternetExplorerDriver.NATIVE_EVENTS, false);
caps.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true);
caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
caps.setJavascriptEnabled(true); `

I even tried `INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS`, but that did not help, so I am not continuing to try it. 

#### IE settings
- All the security zones set to protected mode ON
- Advanced > Security> Enable 64-bit processes for Enhanced Protected Mode is unchecked.
- Connnections > Lan Settings > Automatically Detect Settings is unchecked

## Notes
This may or not help, but I did not experience this issue until yesterday, and as far as I can tell nothing changed.  I have a test suite of around 500 tests, and when i kicked them off yesterday IE failed after around 50 tests because of a known bug in deleting cookies.  I restarted the suite (making no changes), and they failed after around 12 tests.  I added debugging to find where the tests started to hang, and then the first test failed. I fixed my cookies issue by using `JavascriptExecutor`, but in doing so this slow text issue surfaced.  I still cannot figure out why two days ago I had no issues with cookies or text on 64bit 3.5.1 and two days later I am 
having to rewrite my cookie logic and deal with slow text, accomplishing this only on the 32bit driver.  Very, very odd. 

Why would v.3.4.0 work, but v3.5.1 not work?  Is there a known issue with this driver as opposed to earlier versions?  Thanks

**Comment by lmtierney** [comment]
Take a look at this blog post http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html

**Comment by kroe761** [comment]
That’s very interesting, and certainly worth knowing - but it doesn’t help :-)

**Comment by luke-hill** [comment]
A separate and perhaps interesting idea. Is that the IEDriver 3.5+ executable is massively different in terms of its architecture. See here for some more information regarding this.

3.5 onwards uses (or attempts to use the w3c payload) - https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG

**Comment by nandhu19940** [comment]
Just try with different bit version of driver

**Comment by lTyl** [comment]
I had a similar issue before as well. Adding `requireWindowFocus: true` to my capabilities resolved it in my case. IE11, Windows 8.1.

**Comment by vnktrmn** [comment]
@ITyl : Man, you saved my day ! It works! I used x64 driver and just added InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, true

to my capability. And it worked !

**Comment by ckzgraphics** [comment]
**IE + SendKeys = Slowness** is an old issue- [https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5116](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5116)

**Comment by diemol** [comment]
After reading the comments it seems the issue got solved. If that is not the case, please feel free to open a new one after upgrading to the latest versions of all components, and also providing a deterministic way to reproduce the issue.
