### ISSUE TITLE
Ruby driver.quit throws errors

### ISSUE THREAD

**Issue by s2t2** [SeleniumHQ/selenium#4738]
## Meta -
OS:  Mac

Selenium Version:  selenium-webdriver (3.5.2)

Browser:  firefox

Browser Version:  
 53.0.3 (64-bit)

## Expected Behavior -

I should be able to use the code from the [wiki instructions](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#api-example) without error. Specifically I should be able to call `quit` on the driver.

## Actual Behavior -

Calling `.quit` on a driver throws errors (see below).

## Steps to reproduce -

```rb
require "selenium-webdriver"

driver = Selenium::WebDriver.for :firefox
driver.navigate.to "http://google.com"
driver.quit #> Selenium::WebDriver::Error::UnknownError: quit
driver.quit #> Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4444
```

**Comment by s2t2** [comment]
See also https://github.com/teamcapybara/capybara/issues/1773

**Comment by barancev** [comment]
What geckodriver version do you use?

**Comment by barancev** [comment]
Following the mentioned capybara issue, I think this one can be closed.
