### ISSUE TITLE
Selenium IDE issues 

### ISSUE THREAD

**Issue by adityazix** [SeleniumHQ/selenium#4739]
## Meta -
OS:  Windows 7

Selenium Version: 2.9.1  

Browser:  Mozilla  Firefox 55.0.3

Browser Version:  

## Actual Behavior - There was an unexpected error. Msg: TypeError: window.editor.infoPanel is undefined
Url: chrome://selenium-ide/content/selenium-ide-sidebar.xul, line: 1, column: 1
onclick@chrome://selenium-ide/content/selenium-ide-sidebar.xul:1:1

**Comment by barancev** [comment]
Duplcate of #4406
