### ISSUE TITLE
text() not working in by.xpath() in IE

### ISSUE THREAD

**Issue by hvardhanivp** [SeleniumHQ/selenium#474]
I want to search the exact text in the webpage. So I preferred to use text() method in xpath but it's not working.

Example: 
driver.findElement(By.xpath("//span[(text()="someText")"]) not workin in IE. Please fix it or provide the workaround for that.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
