### ISSUE TITLE
GeckoDriver fails to start FireFox-55 when Windows screen is Locked

### ISSUE THREAD

**Issue by tttower** [SeleniumHQ/selenium#4742]
OS:  Windows-7
Selenium Version: 3.4.0  
Browser: FF-55.0.3  
GeckoDriver-0.18.0

When Windows Screen is locked, GeckoDriver fails to start Firefox browser.
Noticed, after FF was upgraded to 55.0.3
Works fine with FF-53.0
When Windows unlocked, Selenium/GeckoDriver/FF-55 works as expected.

Expected Behavior: With LockedScreen, GeckoDriver should start FF browser. 
Actual Behavior: GeckoDriver starts, no FF GUI.
Steps to reproduce: Lock Windows screen, start Selenium/FF test case remotely or
via delayed Batch file.

**Comment by Frankstar** [comment]
just curious, what are you trying to achieve?
wouldnt a headless solution be better anyway?

**Comment by barancev** [comment]
Please raise an issue on https://github.com/mozilla/geckodriver/issues

**Comment by tttower** [comment]
Just trying to be consistent between GeckoDriver/FF version behaviors. So, if previous version works under certain conditions, expectation is next version will do the same.

**Comment by Frankstar** [comment]
what barancev tryed to say is - it isnt an selenium bug.
you are in the wrong issue tracker.
