### ISSUE TITLE
Onblur event issue

### ISSUE THREAD

**Issue by sanjayrjain** [SeleniumHQ/selenium#4743]
## Meta -
OS:  Windows 7

Selenium Version:  2.52
 
Browser:  IE 11

Browser Version:  IE 11

## Expected Behavior -
onblur , focus should be moved out by the  Edit box.

## Actual Behavior -
Stays in the same webedit box even after using Keys.TAB method.

## Steps to reproduce -
HTML: 
<input name="percent_list" id="percent_list" type="text" value="1" align="right" class="formInput" onblur="calculate();">
<input name="percent_sell" id="percent_sell" type="text" value="1" align="right" class="formInput" onblur="calculate();">
<input name="total_commision" id="total_commision" type="text" value="2.00" readonly="yes" class="formInput">

Code: 
driver.findElement(By.id("percent_list")).sendKeys("2.5");
driver.findElement(By.id("percent_sell")), Keys.TAB);
driver.findElement(By.id("referral_fee_percent")), Keys.TAB);

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
