### ISSUE TITLE
Right click is not working 

### ISSUE THREAD

**Issue by Edzotech** [SeleniumHQ/selenium#4744]
#**Meta -**

OS:
Windows 7
Selenium Version:
3.4.0 
Browser:
Firefox 53.0.3

**Expected Behavior -**

Right click should be happend

**Actual Behavior -**

Normal(Left) click happening

**I tried with Below five methods... nothing works :**

        package WebDriverAdvancedPrograms;
        import java.awt.AWTException;
        import java.awt.Robot;
        import java.awt.event.KeyEvent;
        import java.util.concurrent.TimeUnit;
        
        import org.openqa.selenium.*;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.interactions.Action;
        import org.openqa.selenium.interactions.Actions;
        
        public class RightClick {
        
        	public static void main(String[] args) throws InterruptedException, AWTException {
        		System.setProperty("webdriver.gecko.driver", "G:\\Selenium\\geckodriver-v0.16.0-win64\\geckodriver.exe");
        		WebDriver driver = new FirefoxDriver();
        		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS) ;
        		driver.get("http://facebook.com");
        		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        
        		WebElement element=driver.findElement(By.linkText("Forgotten account?"));
        
        
        		//		// Method 1 - NOT WORKING
        		//		Actions builder = new Actions(driver);
        		//		Action mouseOverHome = builder
        		//				.moveToElement(element)
        		//				.contextClick(element)
        		//				.sendKeys(Keys.DOWN)
        		//				.sendKeys(Keys.ENTER)
        		//				.build();
        		//		mouseOverHome.perform();
        
        		// Method 2 - NOT WORKING
        		//		Actions builder = new Actions(driver);
        		//		Action mouseOverHome = builder
        		//				.moveToElement(element)
        		//				.contextClick(element)
        		//				.sendKeys(Keys.ARROW_DOWN)
        		//				.sendKeys(Keys.RETURN)
        		//				.build();
        		//		mouseOverHome.perform();
        
        		// Method 3 - NOT WORKING
        		//		Actions builder = new Actions(driver);
        		//		Action mouseOverHome = builder
        		//				.contextClick(element)
        		//				.sendKeys(Keys.ARROW_DOWN)
        		//				.sendKeys(Keys.RETURN)
        		//				.build();
        		//		mouseOverHome.perform();
        
        		// Method 4 - NOT WORKING
        		//		Actions builder = new Actions(driver);
        		//		Action mouseOverHome = builder
        		//				.contextClick(element)
        		//				.sendKeys(Keys.ARROW_DOWN)
        		//				.sendKeys(Keys.ARROW_UP)
        		//				.sendKeys(Keys.RETURN)
        		//				.build();
        		//		mouseOverHome.perform();
        
        
        		//		// Method 5 - NOT WORKING
        				Actions action= new Actions(driver);
        				action.contextClick(element).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.RETURN).build().perform();
        
        
        
        	}
        }

**Comment by barancev** [comment]
Upgrade geckodriver, latest version is 0.19 at the moment.

**Comment by Edzotech** [comment]
Tried with selenium 3.5.0, FF 55.0.3 and gickodriver 0.19 but did not work....

**Comment by barancev** [comment]
According to https://github.com/mozilla/geckodriver/issues/660 it's fixed. May be you have to use a newer browser version.
