### ISSUE TITLE
Can't record, Errormessage in Test-Case - Properties

### ISSUE THREAD

**Issue by gituser823** [SeleniumHQ/selenium#4745]
## Meta -
OS:  Windows 7

Selenium Version:  2.9.1.1-signed

Browser:  Firefox

Browser Version:  55.0.3 (64-bit)

## Expected Behavior -
Things should be recorded or the Properties should open
## Actual Behavior -
Nothing is recorded and when I click on the window Test Case (no actual Test Case is there yet, because it can not be created) -> Properties the following window pops up:

There was an unexpected error. Msg: TypeError: window.editor.suiteTreeView is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

## Steps to reproduce -
Open Selenium IDE, right-click inside Test-Case window and choose Properties.

**Comment by barancev** [comment]
Duplicate of #4406
