### ISSUE TITLE
Python tests for Firefox don't use Marionette by default

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#4750]
## Meta -
OS:  MacOS

Selenium Version:  latest master

Browser:  Firefox

Running the Python tests via `tox -c py/conftests.py` for Firefox sets the Marionette capability to `False`, which means that we currently do not run the tests with `geckodriver`. Is there a reason why we do not enable Marionette by default? Firefox 47 which was the last version to support the Firefox Driver is unsupported for a long time, same for Firefox 45ESR.

Source: https://github.com/SeleniumHQ/selenium/blob/master/py/conftest.py#L101

@AutomatedTester, is there any reason for that default behavior?

## Expected Behavior -
Running the Python tests should use Marionette by default.

## Actual Behavior -
Marionette is not being used.

## Steps to reproduce -
- Clone the repository
- Build Selenium: `./go py_prep_for_install_release`
- Run tests: `tox -c py/conftests.py`

**Comment by lmtierney** [comment]
@whimboo Currently `Firefox` is for the legacy driver. The suite was created back when geckodriver was still pretty fresh.

To run the tests with geckodriver and latest stable Firefox, use `--driver=Marionette`

I suppose we could switch it up and make this the default and change the old one to `Legacy`. I'm impartial

**Comment by lmtierney** [comment]
Also of note, Legacy driver _does_ work with `FF52 ESR`

**Comment by AutomatedTester** [comment]
Details to run the tests are in https://github.com/SeleniumHQ/selenium/wiki/Python-Bindings and there are test targets in `tox.ini`

**Comment by lmtierney** [comment]
@AutomatedTester can we close this now, or are you leaving it as an action item for yourself?

**Comment by netzulo** [comment]
im ok with `tox` environments , close please if any action it's required :)

**Comment by diemol** [comment]
Closing this as the issue went stale, @AutomatedTester feel free to reopen in case you need to.

**Comment by AutomatedTester** [comment]
This got fixed ages ago. Using Geckodriver means we are using Marionette
