### ISSUE TITLE
window.stop() on a website results in timeout with Chromedriver

### ISSUE THREAD

**Issue by MarkusPint** [SeleniumHQ/selenium#4751]
## Meta -
OS:  
OS X 10.12.6

Selenium Version:  
3.4.0

Browser:  
Chrome

Language:
NodeJS

Browser Version:  
60.0.3112.113 (Official Build) (64-bit)

## Expected Behavior -
When navigating to a website that executes window.stop(), by using driver.get(), Selenium shouldn't become unresponsive. Instead, after the navigation has been completed, the test case should continue. Even though window.stop() causes the page to stop loading prematurely, it doesn't change the fact that the navigation has been completed.

## Actual Behavior -
[SEVERE] Timed out receiving message from renderer: 59.326
[SEVERE] Timed out receiving message from renderer: -0.002

## Steps to reproduce -
driver.get() to a page that executes the JS: ```window.stop()```, it will hang and timeout with the error above.

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
