### ISSUE TITLE
Issue upgrading IEDriverServer

### ISSUE THREAD

**Issue by mdanellorsui** [SeleniumHQ/selenium#4755]
OS: Windows 7
Selenium Version: 
3.6.0 - C# WebDriver
3.5.1 - IEDriverServer
Browser: IE
Version: 11.0.9600.18792

we upgraded IEDriverServer from 2.53.1 to 3.5.1 and now getting the following error on create driver:

OpenQA.Selenium.WebDriverException: Invalid capabilities in firstMatch element 0: unknown capability named unexpectedAlertBehaviour
Stack Trace:
    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(InternetExplorerDriverService service, InternetExplorerOptions options)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(InternetExplorerOptions options)
   at RSUI.Testing.Framework.DriverManager.CreateInternetExplorerDriver() in C:\agent\_work\1\s\RSUI.Testing.Framework\DriverManager.cs:line 33

code to create session:
   
        public static void CreateInternetExplorerDriver()
        {
            InternetExplorerOptions options = new InternetExplorerOptions
            {
                UnexpectedAlertBehavior = InternetExplorerUnexpectedAlertBehavior.Ignore
            };
            _driver = new InternetExplorerDriver(options);
            _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);
            WaitForDriverReady(_driver);
            _driver.Manage().Window.Maximize();
        }

**Comment by mdanellorsui** [comment]
Additional:  it appears that IEServerDriver 3.4.0 works with WebDriver 3.5.1, but IEServerDriver 3.5.0 does not.

**Comment by mstarrrsui** [comment]
Additional info from the driver logs for what we are seeing:

 2017-09-26 10:42:39:000 server.cc(86) Starting WebDriver server on port: '5818' on host: ''
I 2017-09-26 10:42:39:001 IEServer.cpp(33) Driver version: 3.5.0.0 (32-bit)
D 2017-09-26 10:42:39:001 server.cc(148) Civetweb ACL is -0.0.0.0/0,+127.0.0.1
D 2017-09-26 10:42:39:931 server.cc(281) Command: GET /status {}
D 2017-09-26 10:42:39:932 server.cc(338) Response: {"value":{"build":{"version":"3.5.0.0 (32-bit)"},"os":{"arch":"x64","name":"windows","version":"10.0.15063.608 (WinBuild.160101.0800)"}}}

D 2017-09-26 10:42:39:933 server.cc(281) Command: POST /session {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","unexpectedAlertBehaviour":"ignore","nativeEvents":true,"enablePersistentHover":true},"capabilities":{"firstMatch":[{"browserName":"internet explorer","unexpectedAlertBehaviour":"ignore","se:ieOptions":{"nativeEvents":true,"enablePersistentHover":true}}]}}
D 2017-09-26 10:42:39:933 IESession.cpp(53) Mutex acquired for session initalization
D 2017-09-26 10:42:39:939 IESession.cpp(109) Releasing session initialization mutex
D 2017-09-26 10:42:39:939 command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" : {"desiredCapabilities":{"browserName":"internet explorer","version":"","platform":"WINDOWS","unexpectedAlertBehaviour":"ignore","nativeEvents":true,"enablePersistentHover":true},"capabilities":{"firstMatch":[{"browserName":"internet explorer","unexpectedAlertBehaviour":"ignore","se:ieOptions":{"nativeEvents":true,"enablePersistentHover":true}}]}} }
W 2017-09-26 10:42:39:939 CommandHandlers\NewSessionCommandHandler.cpp(216) Error validating capabilities: Invalid capabilities in firstMatch element 0: unknown capability named unexpectedAlertBehaviour
W 2017-09-26 10:42:39:939 IECommandExecutor.cpp(514) Unable to get current browser
D 2017-09-26 10:42:39:950 IESession.cpp(150) Executor shutdown successful!
D 2017-09-26 10:42:39:950 IESession.cpp(158) Posting thread shutdown message
D 2017-09-26 10:42:39:950 IESession.cpp(161) Starting wait for thread completion

**Comment by andrei-ts** [comment]
I'm facing the same issue with webdriver 3.6.0 and IEDriverServer 3.6.0

**Comment by toraylin** [comment]
_driver.Manage().Window.Maximize() is working for IEServerDriver 3.4.0 , but not for 3.5 and 3.6.

I got the error message in Visual Studio .
An exception of type 'System.NotImplementedException' occurred in WebDriver.dll but was not handled in user code. Additional information: Command not found: **POST /session/window/maximize**

**Comment by lmtierney** [comment]
@toraylin your exception is unrelated to this issue. It sounds like the bindings you are using are not sending the w3c command (IEServerDriver 3.5 and 3.6 are w3c compliant now). Any further questions should be directed to the [selenium user group] https://groups.google.com/forum/#!forum/selenium-users).

If you have a legitimate issue, please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by DaveHann** [comment]
Does not look like there is any movement on this issue...
I am seeing a similar problem when I upgraded from 2.44 to 3.6.0. 
After the update I get the following error
org.openqa.selenium.WebDriverException: Command not found: POST /session/null/window/size (WARNING: The server did not provide any stacktrace information)
If I revert back to the 2.44 version everything works again.

Has anyone heard of others facing the same problem?

**Comment by lmtierney** [comment]
@DaveHann your issue is similar to @toraylin's in that the bindings you are using are not sending w3c compatible commands

**Comment by jimevans** [comment]
First off, to use version 3.5 or higher of `IEDriverServer.exe`, you **must** be using version 3.5 or greater of the language bindings. This is documented in the [CHANGELOG for the IE driver](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG#L47).

As for the issue with `UnexpectedAlertBehavior`, yes, that's a protocol issue where the .NET bindings have not kept pace with the IE driver becoming spec-compliant. I have a fix for that, but it's a breaking change, and has not been pushed to master yet. Unfortunately, the set of things I get paid to do (of which, Selenium is not one) has impinged on getting things completely fixed up.

**Comment by DaveHann** [comment]
yup, got the latest and greatest.
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.6.0</version>
        </dependency>

**Comment by jsiegmund** [comment]
Have the same issue trying to use UnexpectedAlertBehavior. Is there a workaround available that we can use to ignore JS errors without using this property?

**Comment by jimevans** [comment]
Yes. You can set a capability called `unhandledUserPrompt`. It takes a string, and the following five values are valid (case sensitive):

    accept
    dismiss
    ignore
    accept and notify
    dismiss and notify

Note that for .NET, you’ll want to use the `AddAdditionalCapability` overload that takes three arguments, and the third argument, a `bool` called `isGlobalCapability`, should be set to `true`. That should  work around the issue. Be prepared for that workaround to eventually throw a runtime error when the capability is fully supported.

**Comment by p0deje** [comment]
Is this still a problem?

**Comment by DaveHann** [comment]
It continues to be for me.  I have the latest java language bindings, I have the directory of the driver server set in my path.  If I use the old version it works but if i put the new version in the same directory it fails.
org.openqa.selenium.WebDriverException: Command not found: POST /session/null/window/size (WARNING: The server did not provide any stacktrace information)
I use the generic selenium server in my pom file 
 <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>3.6.0</version>
The reason i decided to upgrade is the command line server for the IE driver keeps crashing and I thought this might fix the problem.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEDriverServer.exe
  Application Version:	2.44.0.0

**Comment by p0deje** [comment]
@DaveHann This seems like a different issue. Please create a new one with a test script to reproduce the problem on latest Selenium and IEDriverServer.

**Comment by sergmal** [comment]
Hi,
why this issue is closed? I have exactly the same problem as @mdanellorsui described in Initial post.

**Comment by jimevans** [comment]
@segmal Because the issue should be fixed in 3.7 of the .NET bindings. For which I’ve just realized the CHANGELOG wasn’t updated. I guess I know what I’m doing later today.

**Comment by sergmal** [comment]
Thank you for effort @jimevans
