### ISSUE TITLE
executeAsyncScript doesn't trigger ScriptTimeoutException properly

### ISSUE THREAD

**Issue by JackTheHammer** [SeleniumHQ/selenium#4756]
## Meta -
OS:  
Windows 7 x64
Selenium Version:  
Selenium Java 3.5.3 with ChromeDriver 2.32
Browser:  
Reproduced on Chrome 60.0.3112.113 64-bit

Browser Version:  
Reproduced on Chrome 60.0.3112.113 64-bit

Detailed (verbosed) log of execution:
https://gist.github.com/anonymous/b38e3a0cba84e2ae182a726484aba4c7

## Expected Behavior -
Following code (specifically, executeAsyncScript) should throw ScriptTimeoutException, because setScriptTimeout is set to 0 ns. 

```
System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
System.setProperty("webdriver.chrome.verboseLogging", "true");
WebDriver driver = new ChromeDriver();
driver.manage().timeouts().setScriptTimeout(1, TimeUnit.NANOSECONDS);

String script = "var callback = arguments[arguments.length - 1];" +
        "var stringVar = 'abcd';" + 
        "callback(stringVar);";

Instant beforeScript = Instant.now();
String result = (String) ((JavascriptExecutor) driver).executeAsyncScript(script);
System.out.println(result + " took time: " + Duration.between(beforeScript, Instant.now()).toMillis() + " ms");
```

## Actual Behavior -

Result successfully returned from script, but ScriptTimeoutException didn't triggered

## Steps to reproduce -

Just run the code

**Comment by barancev** [comment]
Please raise this issue on chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by JackTheHammer** [comment]
Already raised.
And also, this issue reproduced with GeckoDriver 0.19

I assume this must be whole webdriver problem.

**Comment by jimevans** [comment]
I don't believe the async script timeout can be set to anything more granular than 1 millisecond. I mean, it can be set to that in the language binding, but I don't think any remote-end implementation recognizes anything less than 1 millisecond. I'm quite sure the W3C WebDriver spec says the timeout is in milliseconds.

**Comment by JackTheHammer** [comment]
I've tried it with 0 ms, and 1 ms. Same result.
According to javadoc, it should throw ScriptTimeoutException even if you don't set timeout at all.

**Comment by JackTheHammer** [comment]
Should I post report from GeckoDriver ?

**Comment by barancev** [comment]
@JackTheHammer Did you see explanation in https://bugs.chromium.org/p/chromedriver/issues/detail?id=2040#c2? I believe geckodriver issue will be rejected for the same reason.

**Comment by JackTheHammer** [comment]
Thank you.
Now when I know that my script wasn't actually async script, so I'm looking for solution to handle synchronous script timeout, but it seems like Selenium don't have this feature yet. Found similar issue here: https://github.com/seleniumhq/selenium/issues/1387
I'll stick to classic multi-threading then.
