### ISSUE TITLE
Leftover processes when aborting rspec

### ISSUE THREAD

**Issue by heaven** [SeleniumHQ/selenium#4757]
OS:  
Mac OS
Selenium Version:  
2.6.0
Browser:  
Chrome

Using with `rspec` and `capybara`. When stopping specs with `Ctrl+C` the rspec shuts down gracefully but `chromedriver` process doesn't and we end up with leftover `chromedriver` and `Google Chrome` processes. We didn't have similar issues with `poltergeist` and `phantomjs` so I thought this might be something to do with `selenium`. Please let me know if I should report this to another team.

**Comment by p0deje** [comment]
Please upgrade to latest selenium-webdriver gem (where this behavior is changed) or use `detach: false` option. By default, Ctrl-C will *not* kill chromedriver and Chrome. With detach disabled - it will.

**Comment by heaven** [comment]
Sorry, there's a typo in the gem version, it's `3.6.0`. If I press `Ctrl+C` just once and let the RSpec shut down gracefully it's ok, the problem is happening when I abort it pressing the `Ctrl+C` once again - RSpec exits but the driver keeps running. Will `detach: false` help with this? I just tried to use as follows `Capybara::Selenium::Driver.new(app, browser: :chrome, desired_capabilities: capabilities, http_client: client, detach: false)` with no success.

**Comment by p0deje** [comment]
The process needs to be gracefully shut down upon SIGINT. If you force it, there is no guarantee to the process will be killed.
