### ISSUE TITLE
java: selecting an element by its parent xpath returns null attributes

### ISSUE THREAD

**Issue by a1dutch** [SeleniumHQ/selenium#4761]
## Meta -
OS:  MacOS 10.12.6

Selenium Version:  3.5.3

Browser:  FireFox

Browser Version:  55.0.3

GekoDriver: 0.19.0

## Expected Behavior -
The attributes returned via `getAttribute` should return the actual value rather than `null` when using a parent xpath selector.

## Actual Behavior -
The attributes are returned as `null` when using a parent xpath selectors `//parent::*` or `..`, calling the `getTagName()` method returns the correct tag name for the parent.

## Steps to reproduce -

Given the html below

```html
<ul class="nav nav-tabs hidden-xs" role="tablist">
  <li role="presentation" class="active">
    <a href="#tab1" role="tab" data-toggle="tab">tab1</a>
  </li>
  <li role="presentation">
    <a href="#tab2" role="tab" data-toggle="tab">tab2</a>
  </li>
</ul>
```

The two following method calls will not retrieve any attributes (role or class) on the links parent (li element)

```java
driver.findElement(By.linkText("tab1")).findElement(By.xpath("..")).getAttribute("role")
```

```java
driver.findElement(By.linkText("tab1")).findElement(By.xpath("//parent::*")).getAttribute("role")
```

**Comment by barancev** [comment]
Prepend local path queries with a dot: "./.." or ".//parent::*

**Comment by a1dutch** [comment]
This still doesn't work, the attribute is still returned as `null` whether i use `..`, `//parent::*`, `./..` or `.//parent::*`

**Comment by barancev** [comment]
```
driver.get("https://jsbin.com/lokufi");
System.out.println(
  driver.findElement(By.linkText("tab1")).findElement(By.xpath("./..")).getAttribute("role"));
```
prints "presentation"

**Comment by a1dutch** [comment]
@barancev thanks, seems it was picking up a different link which was for mobile view only which had no role.
