### ISSUE TITLE
scripts failing randomly because of browser page load/driver initialisation is taking longer time some times

### ISSUE THREAD

**Issue by Narsimharao** [SeleniumHQ/selenium#4765]
## Meta -
OS:  Windows

Selenium Version:  2.53 and and above

Browser:  Firefox/Chrome

Browser Version:  latest chrome and firefox

## Actual Behavior -
Browser initialisation taking longer time and page is loading very slow and taking more than 5 minutes some times and in next run its taking only few seconds. its an intermittent issue and scripts are failing randomly.
## Steps to reproduce -
using the following code 
var driverService = FirefoxDriverService.CreateDefaultService(GetDriverPath(), "geckodriver.exe");
                        Instance = new FirefoxDriver(driverService, options, TimeSpan.FromSeconds(60));

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
