### ISSUE TITLE
Selenium does not click on an element if the element is not in the page view.

### ISSUE THREAD

**Issue by TabishKhan21** [SeleniumHQ/selenium#4766]
## Meta - 
OS:  Windows 10

Selenium Version:  3.4.0

Browser:  Google Chrome

Browser Version:  61.0.3163.100

## Steps to reproduce - 
1. Write a script where selenium clicks on a web element that is not in the page view
2. Run the script

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by lmtierney** [comment]
This was a known issue with Chrome 61, please make sure you're using chromedriver `2.32` or greater. If you still have issues after doing so, please log an issue with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
