### ISSUE TITLE
ELEMENT not finded after update selenium/standalone-firefox from 3.4.0 to 3.5.0 

### ISSUE THREAD

**Issue by yak80** [SeleniumHQ/selenium#4773]
After upgrade `selenium/standalone-firefox` from `3.4.0` to `3.5.0` (or above) project tests are fail.
```
            loginPage.navigate()
                .waitForElementVisible('#app', Helper.maxLoadingTime);
```
Look like it wait entry `ELEMENT` but receive `element-6066-11e4-a52e-4f735466cecf` instead.

## Meta -
OS:  Dockerized

Selenium Version:  selenium/standalone-firefox:3.5.0 (or above)

Browser:  selenium/standalone-firefox:3.5.0 (or above)

## Expected Behavior - 
with version 3.4.0 all work fine
```
INFO Response 200 POST /wd/hub/session/cf0426b6-2d16-4142-a018-8748b1acb8fe/elements (176ms) { state: 'success',
  sessionId: 'cf0426b6-2d16-4142-a018-8748b1acb8fe',
  hCode: 438605693,
  value: [ { ELEMENT: '0' } ],
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }
INFO Request: GET /wd/hub/session/cf0426b6-2d16-4142-a018-8748b1acb8fe/element/0/displayed 
 - data:   
 - headers:  {"Accept":"application/json"}
INFO Response 200 GET /wd/hub/session/cf0426b6-2d16-4142-a018-8748b1acb8fe/element/0/displayed (213ms) { state: 'success',
  sessionId: 'cf0426b6-2d16-4142-a018-8748b1acb8fe',
  hCode: 562104897,
  value: true,
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }
LOG     → Completed command waitForElementVisible (395 ms)
LOG     → Completed command useCss (1 ms)
```
https://travis-ci.org/instrumentisto/vue-app-example/builds/280784271

## Actual Behavior -
In versions 3.5.0 and above
```
INFO Response 200 POST /wd/hub/session/96ea1cdc-63d1-486e-bd30-68ace2968fa3/elements (150ms) { state: 'success',
  sessionId: null,
  hCode: 1090440510,
  value: 
   [ { 'element-6066-11e4-a52e-4f735466cecf': '2a7b784d-1585-4f3c-b562-cc5f665c9228' } ],
  class: 'org.openqa.selenium.remote.Response',
  status: 0 }
INFO Request: GET /wd/hub/session/96ea1cdc-63d1-486e-bd30-68ace2968fa3/element/undefined/displayed 
 - data:   
 - headers:  {"Accept":"application/json"}
ERROR Response 500 GET /wd/hub/session/96ea1cdc-63d1-486e-bd30-68ace2968fa3/element/undefined/displayed (152ms) { state: 'javascript error',
  sessionId: null,
  hCode: 1848680964,
  value: 
   { additionalInformation: '\nDriver info: driver.version: unknown',
     localizedMessage: 'Element reference not seen before: undefined\nBuild info: version: \'3.5.0\', revision: \'8def36e068\', time: \'2017-08-10T23:00:22.093Z\'\nSystem info: host: \'2143c01b6db5\', ip: \'172.18.0.5\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.4.0-93-generic\', java.version: \'1.8.0_131\'\nDriver info: driver.version: unknown',

```
https://travis-ci.org/instrumentisto/vue-app-example/builds/280778475

## Steps to reproduce -
1. Clone repository https://github.com/instrumentisto/vue-app-example 
2. Change `SELENIUM_FIREFOX_VERSION` to `3.5.0`  in `Makefile`
3. 
```
make deps dev=yes && make build && make dist && make docker.image
make test.e2e start-app=yes browsers=firefox
```

**Comment by romandragan** [comment]
:+1: Same for me.

**Comment by barancev** [comment]
I see that you're using nightwatch in the example project, so please log an issue to nightwatch bug tracker.

**Comment by NicoHaase** [comment]
We have the same problem using behat, mink, whatever is needed for a PHP stack, so I don't think that nightwatch is the one to blame. If the return value of an API changes, there might be a problem in the API?

**Comment by jimevans** [comment]
@NicoHaase If a project consumes an API, isn’t it incumbent on the maintainer of that project to be aware of changes that may occur in that API, especially if those changes have been made intentionally and communicated about publicly? In this case, the change in the element identifier key has been part of the W3C WebDriver Specification for well over a year. It can hardly be characterized as obscure or unexpected.

**Comment by NicoHaase** [comment]
@jimevans Thanks - I was not aware of the specification. Can you point me to more information about this change, so that I can raise a bug ticket in https://github.com/instaclick/php-webdriver?

**Comment by barancev** [comment]
@NicoHaase That's true, not only nightwish. It's not about API, it's about protocol, as Jim stated.

Selenium migrates from old OSS protocol [1] to new W3C WebDriver protocol [2]. All "official" (developed by Selenium team) bindings provide backward compatible dual-protocol API. Third party implementations (like nightwish or a PHP binding used by behat) should be changed to support new protocol too. Or you can continue to use legacy Selenium Server 2.53 (or may be even 3.4 that is still "legacy" to some extent).

Yes, we understand that breaking protocol is painfull, but we had to do this to get rid of restrictions imposed by old protocol.

[1] https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol
[2] https://w3c.github.io/webdriver/webdriver-spec.html
