### ISSUE TITLE
wait.Until(ExpectedCondition(ElementToBeClickable())) failing to find element when not remote desktoped to machine

### ISSUE THREAD

**Issue by jburns24** [SeleniumHQ/selenium#4777]
## Meta -
OS:  Windows Server 2008 R2 6.1

Selenium Version:  
Standalone Server 3.5.3
Selenium Webdriver 3.5.1
Selenium Support 3.5.1
IEDriver 3.5.1

Browser:
Internet Explorer 

Browser Version:  

IE 11

## Expected Behavior -
Element found when running tests on machine that is logged in but I am not currently remote desktoped to
## Actual Behavior -
I recently had all these tests running on standalone server 2.53 with selenium webdriver and support version 2.53.1, machine setup was the same otherwise. These machines were used to regression test overnight and tests used to function OK. After upgrading I am seeing tests fail to locate first element in test case. Screenshots show nothing but a black screen. But I notice that if I remote desktop to the node machine and then run a test everything works great. But if I kill my remote connection tests fail to locate element. I can see that the browser is getting opened and driver is able to navigate to the URL but when it tried to find an element it fails. 

I am seeing this same behavior in Chrome, and Firefox but due to the way the machines are setup I can only easily capture logs from IE when not remote desktoped to the machine. I could get other trace logs from browsers if you can tell me how to do something similar to `-Dwebdriver.ie.driver.logfile=iedriver.log -Dwebdriver.ie.driver.loglevel=TRACE` for other browsers. I 
## Steps to reproduce -
```
using System;
using System.Linq;
using System.Threading;
using POMAuctivaTest.AuctivaPageModels;
using CustomExceptions;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Remote;
using NUnit.Framework;
using System.Diagnostics;
using System.Configuration;
using System.Collections.Generic;
using System.IO;


namespace POMAuctivaTest.TestSuite
{
    [TestFixture]
    [Category("test")]
    public class Test
    {
        public IWebDriver driver { get; set; }
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger("Test");
        public UserInfo User;
        [OneTimeSetUp]
        public void setUp()
        {
            InternetExplorerOptions ieOptions = new InternetExplorerOptions();
            ieOptions.EnsureCleanSession = true;
            ieOptions.RequireWindowFocus = true;
            ieOptions.IgnoreZoomLevel = true;
            ICapabilities ieCaps = ieOptions.ToCapabilities();
            driver = new RemoteWebDriver(new Uri("http://10.34.161.113:5555/wd/hub/"), ieCaps, TimeSpan.FromMinutes(2));
            driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(180);
            driver.Manage().Window.Maximize();
        }

        [Test]
        public void test()
        {
            driver.Navigate().GoToUrl("https://www.auctiva.com/default.aspx");
            Thread.Sleep(4000);
            By selector = By.CssSelector("#ftctrl_header_ftctrl_SignIn_btn_SignIn"); //  login button
            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(15));
            wait.Until(ExpectedConditions.ElementToBeClickable(driver.FindElement(selector)));
            driver.FindElement(selector);
        }

        [OneTimeTearDown]
        public void tearDown()
        {
            driver.Quit();
        }
    }
}
```
[iedriver.txt](https://github.com/SeleniumHQ/selenium/files/1341125/iedriver.txt)
[iedriverNotRDP.txt](https://github.com/SeleniumHQ/selenium/files/1341124/iedriverNotRDP.txt)

**Comment by jburns24** [comment]
So I have been testing other situations and noticed that if I changed the `Wait` condition to `ElementExists` that this test case works. Attached is the ie trace logs from this run. 
[ElemenExists.txt](https://github.com/SeleniumHQ/selenium/files/1342087/ElemenExists.txt)

**Comment by jburns24** [comment]
![image](https://user-images.githubusercontent.com/19497855/30989436-8a1289e0-a452-11e7-889f-e040b0f2220a.png)
This is also something I have noticed that I believe is related to this. Notice the "Take Screenshot" is not clickable. I have never noticed this until I started experiencing this issue. Hovering over the button shows "Screenshot not supported"

**Comment by diemol** [comment]
@jburns24 apologies for the lack of response.
We are doing an issue cleanup, I will close this one since it has been stale for almost 3 years, so either a workaround was found or the issue is not relevant anymore.

**Comment by diemol** [comment]
Please feel free to open a new one if the issue still persists.
