### ISSUE TITLE
mouse move doesn't work properly in IE (3.6.0)

### ISSUE THREAD

**Issue by mgrybyk** [SeleniumHQ/selenium#4778]
## Meta -
OS:  windows 10
Selenium Version:  3.6.0
Browser:  IE11, 3.6.0.0

## Expected Behavior -
mouse move should work properly, same as in Chrome, Firefox

## Actual Behavior -
I'm trying to drag element vertically down.
Browser's move position is like 200px left of the element I want to move

## Steps to reproduce -
write some test that will drag some element to another position or draw line, whatever.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mgrybyk** [comment]
my fault, the issue was in not really good implementation of WebElemenet wrapper. 
Strange thing that mousemove worked just fine in chrome, firefox.

Closing issue. INVALID
