### ISSUE TITLE
https://<USER_NAME>:<PASSWORD>@URL not working with Safari

### ISSUE THREAD

**Issue by chandraprakashgoyal** [SeleniumHQ/selenium#4779]
## Meta -
OS:  Mac (Version: 10.12.6)
Selenium Version:  3.5.3
Browser:  Safari 11.0
Browser Version:  Safari 11.0

## Steps to reproduce -
Safari is not supporting "https://<USER_NAME>:<PASSWORD>@URL" but same is working with Firefox and Chrome. Please help.

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/
