### ISSUE TITLE
EventFiringWebElement - Throws a not JSON serializable exception

### ISSUE THREAD

**Issue by harishzen** [SeleniumHQ/selenium#478]
I'm using a selenium v2.45 with the python binding. Its a  EventFiringWebElement webdriver(firefox) (to include a before_click event) . When i try to do a switch frame i get a TypeError : is not JSON serializable exception thrown . Works fine with normal webdriver(firefox). Any clues?

**Comment by lukeis** [comment]
please provide a concise reproducible script along with traceback and relevant other versions (firefox and OS), then we can reopen your issue.

**Comment by harishzen** [comment]
Script to Reproduce:
https://gist.github.com/harishzen/b80da702de49fed38c08#file-selenium_event-py 

Using:
selenium==2.45.0
Chrome 43.0.2357.124 (64-bit)
OS X Yosemite - Ver. 10.10.3
