### ISSUE TITLE
Selenium is unable to identify element in IE 

### ISSUE THREAD

**Issue by mahmad1** [SeleniumHQ/selenium#4789]
## Meta -
OS:  Windows 7 64 bit

Selenium Version:  2.45

Browser:  Internet Explorer

Browser Version: 11.0.96000

Hi Team,

I am using Keyword driven framework to execute the script using selenium and java.

Problem-
 Selenium is not able to identify the element when it's redirecting to new page (different page within application) in IE browser but in Firefox and Chrome it is working as expected.
URL-
Web Application
Code for IE Browser-
File file = new File("C:\\Selenium\\Browser\\IE\\IEDriverServer.exe");
System.setProperty("webdriver.ie.driver", file.getAbsolutePath() );       
 DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();			 capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true); 
 driver = new InternetExplorerDriver(capabilities);

## Expected Behavior -
Script should click on expected element.

## Actual Behavior -
It is not clicking on expected element and giving the below error-
org.openqa.selenium.NoSuchWindowException: Unable to find element on closed window (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 15 milliseconds
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'GUEST076', ip: '172.18.249.66', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{se:ieOptions={browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:1493/, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascriptEnabled=true, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
## Steps to reproduce -
-Click on the above url
-Select country as United State
-Click on continue
-Click on 'Carpet Tile' link 

Please let me know if you required more information.

Thanks,
Aklakh Ahmad

**Comment by p0deje** [comment]
Can you try on the latest version of Selenium and IEDriverServer (3.6 at the moment)?

**Comment by mahmad1** [comment]
Thank you Alex for response, as u said I updated the latest version of Selenium and IEDriverServer, Once (First time ) it's worked as expected but from second time time onward same error is coming even I cleared the cache and restarted server as well.

**Comment by barancev** [comment]
Remove
capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
from your code and retest. We don't accept issues with flakiness deliberately allowed.

**Comment by mahmad1** [comment]
Hi Alexei, 
I removed the capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
even though it is not working.
Current code is -
else if(browser.equalsIgnoreCase("internet")){
	System.setProperty("webdriver.ie.driver", "C:\\Selenium\\Browser\\IE\\IEDriverServer.exe");
        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        driver = new InternetExplorerDriver(capabilities);
}
Now url is also not opening.

**Comment by p0deje** [comment]
> Now url is also not opening.

What URL is not opening? The original issue was about element not being found. Do you now see a different error?

**Comment by arviedelgado** [comment]
Have you updated the Registry?

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE

Add New DWORD Value as follows:

Name:	iexplore.exe
Type:	REG_DWORD
Value:	0

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. Otherwise the issue will be closed.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.

**Comment by mahmad1** [comment]
As I am using Keyword driven framework, I am writing the test steps in excel sheet.
I have updated the registry file as well but the issue is when I executing with IE browser , the script is not executing.
In Firefox and chrome it is working as expected.
