### ISSUE TITLE
IEDriverServer vendor mode JSON format error

### ISSUE THREAD

**Issue by filipcynarski** [SeleniumHQ/selenium#479]
I'm trying to use IEDriverServer on vendor mode with following error. I'm running Selenium tests on Java using most recent version of selenium and fluentlenium frameworks. On debug mode I'm receiving this message from IEDriverServer as a result of javascript execution.

```JSON format error: For findElements command, parameters object must contain pair with name "locator"
Command duration or timeout: 0 milliseconds
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'ITHFPC23', ip: '10.98.0.54', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_17'
*** Element info: {Using=css selector, value=body div#msgContainer h1}
Session ID: 8c478f26-1088-4e71-bee7-c59b2cd68c1f
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{platformVersion=8.1, platform=ANY, browserVersion=11, -ms-requireWindowFocus=false, secureSsl=true, platformName=windows, browserName=Internet Explorer, takesElementScreenshot=true, takesScreenshot=true}]```

Tested on IE11, Windows 7, all updates have been installed.

**Comment by ddavison** [comment]
please provide a [clear concise reproducible case](http://sscce.org)

**Comment by jimevans** [comment]
Actually, this is a known issue with using the Microsoft driver implementation. That implementation uses a slightly different dialect of the JSON wire protocol, and the Java language bindings haven't made the modifications required to speak that dialect. The modifications from the .NET bindings to accommodate the Microsoft implementation need to be ported to Java.

**Comment by filipcynarski** [comment]
Here are steps to reproduce:

Preconditions: IE11 installed on Windows 7, IEDriver Tools upgrade installed from Microsoft site.

1. Write your Selenium test code in Java which opens the web page and invokes CSS selector using findby Fluentlenium method 
2. Run IEDriverServer in vendor mode
3. Execute your tests for IE (IE driver is set to vendor as well)

Current result: exception is thrown 
Expected result: IE executed the CSS selector

**Comment by filipcynarski** [comment]
Thank you jimevans

**Comment by jimevans** [comment]
I'm closing this issue. The Microsoft WebDriver implementation for Internet Explorer has been largely abandoned for the time being in favor of a WebDriver implementation for Microsoft Edge (formerly Spartan). If and when the changes required for the Microsoft Edge implementation are back-ported by Microsoft to their Internet Explorer implementation, we can revisit this issue.
