### ISSUE TITLE
'org.openqa.selenium.support.ui.ExpectedConditions' is deprecated

### ISSUE THREAD

**Issue by lavellj12** [SeleniumHQ/selenium#4794]
## Meta -
OS:  
< OSX>
Selenium Version:  

Browser:  
<Safari
-->

Browser Version:  

## Expected Behavior -
Open the app, login, go and edit profile, and change the password

## Actual Behavior -
Class not found: "sample.Newpass"Empty test suite.

## Steps to reproduce -

I honestly don't know if I have the format correct I'm still trying to get the hang of asking questions on these sites.

**Comment by lavellj12** [comment]
package sample;
//Import necessary classes
import io.appium.java_client.android.AndroidDriver;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.MalformedURLException;
import java.net.URL;


public class Newpass {

    String profile = "com.sonic.sonicdrivein.inhouse:id/dashboard_profile_button_image";
    String sign ="com.sonic.sonicdrivein.inhouse:id/navigation_text_sign_in";
    String signUpDoneButton = "com.sonic.sonicdrivein.inhouse:id/toolbar_button_cta";
    String enterUsernameButton = "com.sonic.sonicdrivein.inhouse:id/validation_input_field";
    String enterPasswordButton = "com.sonic.sonicdrivein.inhouse:id/sign_in_field_password";
    String name = "com.sonic.sonicdrivein.inhouse:id/navigation_text_profile_name";
    String editprofile = "com.sonic.sonicdrivein.inhouse:id/profile_button_edit";
    String changePassword = "com.sonic.sonicdrivein.inhouse:id/edit_profile_text_change_password";
    String oldpass = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RelativeLayout[1]/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.EditText";
    String newpass = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.RelativeLayout[2]/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.RelativeLayout/android.widget.EditText\n";


    AndroidDriver driver;

    /**
     * Sets the device name as Android Emulator
     * Searching for the Sonic App
     * Sets the connection to the local host credentials on appium
     * @throws MalformedURLException is trying to connect with the appium host
     *
     */
    @Before
    public void setup() throws MalformedURLException {

        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("deviceName", "Android Emulator");
        capabilities.setCapability("app", "/Users/lavelljackson/Desktop/Sonic App/Android_3.0.2v3084.apk");

        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

    }

    /**
     * @throws InterruptedException clears the interruption status
     */
    @Test
    public void ChangePass() throws InterruptedException {

        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(ExpectedConditions.elementToBeClickable(By.id(profile)));

        //Click the profile icon
        driver.findElement(By.id(profile)).click();

        //Click the sign in button
        driver.findElement(By.id(sign)).click();

        //Enter Username
        driver.findElement(By.id(enterUsernameButton)).sendKeys("qa713confirmed@mailinator.com");

        //Enter Password
        driver.findElement(By.id(enterPasswordButton)).sendKeys("Sonic2017");

        //Tap the DONE button
        driver.findElement(By.id(signUpDoneButton)).click();

        driver.findElement(By.id(profile)).click();

        driver.findElement(By.id(name)).click();

        //Enter the code for "Edit Profile"
        driver.findElement(By.id(editprofile)).click();

        driver.findElement(By.id(changePassword)).click();

        driver.findElement(By.xpath(oldpass)).sendKeys("Sonic2017");

        driver.findElement(By.xpath(newpass)).sendKeys("Sonic2018");
    }

    /**
     * Driver quit
     * void teardown exit the test after every run
     */
    @After
    public void teardown() {
        driver.quit();

    }
}

**Comment by lmtierney** [comment]
> I honestly don't know if I have the format correct I'm still trying to get the hang of asking questions on these sites.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
