### ISSUE TITLE
Firefox no longer transparently accepting untrusted SSL certificates with version webdriver v3.6.0

### ISSUE THREAD

**Issue by vflame** [SeleniumHQ/selenium#4796]
OS:  Win 10 x64
Selenium Version:  3.6.0
Browser:  Firefox Nightly
Browser Version:  57.0a1 (2017-09-17) (64-bit)

Firefox automatically accepts the FiddlerCore (version (4_6_20172_35715) certificate when visiting a SSL/TLS enabled site and is working as intended in .net webdriver release 3.5.2. Why does going to version 3.6.0 would cause the SSL error and downgrading it causes the SSL certificate to be automatically accepted?

v3.5.2 certificate automatically added into exception:
![3 5 2](https://user-images.githubusercontent.com/12207061/31102955-82de372a-a7a2-11e7-84ce-34e804b0611f.png)

v3.6.0 not adding certificate automatically:
![3 6 0](https://user-images.githubusercontent.com/12207061/31102961-87f07e1c-a7a2-11e7-8353-ee2f72271c59.png)

**Comment by diemol** [comment]
Apologies for the late reply, I notice this issue was filled with Firefox Nightly... Is this still valid with the latest version of Selenium and the stable Firefox release?

**Comment by diemol** [comment]
If so, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information. If this issue still exists with the latest versions, please feel free to open a new issue with all the required information on the template.
