### ISSUE TITLE
Firefox minimize and close

### ISSUE THREAD

**Issue by Vinaypawar77** [SeleniumHQ/selenium#4798]
## Meta -
OS:  
Windows -7 64 bit
Selenium Version:  
3.5.1, 3.5.2, 3.5.3, 3.6.0
Gecko Driver
0.18.0
Browser:  
Firefox

Browser Version:  
55.0.3, 56

## Expected Behavior -
Browser should run full Test.

## Actual Behavior -
When we run test, Firefox first mimimize and then close in between running of test.
Error:
[GFX1-]: Receive IPC close with reason=AbnormalShutdown

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
