### ISSUE TITLE
Execution Fails in IE, saying element not found when execution window is minimized.

### ISSUE THREAD

**Issue by PavaniSamineni** [SeleniumHQ/selenium#4799]
Hi,

I have a test script which has some 200 steps, when am monitoring the execution browser (IE), all the steps gets passed. but when I  minimize the execution browser manually(when am not monitoring the execution screen) and steps are getting failed saying element not found.
(its an internal application, not able to share the URL)

Is there any limitation from the selenium in IE execution?

Note: For some public applications am able to execute successfully without monitoring in IE.

IE version: 11.0.96
selenium Version: 2.53

Thanks in advance
//Pavani

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
