### ISSUE TITLE
IEDriverServer cannot be set to vendor mode from external services like SeleniumGrid

### ISSUE THREAD

**Issue by filipcynarski** [SeleniumHQ/selenium#480]
IEDriverServer cannot be set to vendor mode from external services like SeleniumGrid as a result to be able to use IEDriverServer user needs to recompile it w/ default value of --implementation parameter set to VENDOR.

Could you please make external configuration for example (property file, system variable or extend SeleniumGrid to handle this parameter)?

**Comment by jimevans** [comment]
I'm closing this issue. The Microsoft WebDriver implementation for Internet Explorer has been largely abandoned for the time being in favor of a WebDriver implementation for Microsoft Edge (formerly Spartan). If and when the changes required for the Microsoft Edge implementation are back-ported by Microsoft to their Internet Explorer implementation, we can revisit this issue.
