### ISSUE TITLE
Unable to find element with Internet Explorer through selenium hub

### ISSUE THREAD

**Issue by paulbriton** [SeleniumHQ/selenium#4800]
## Meta -
OS: **Windows 10**
Selenium Version: **3.6**
Browser: **Internet Explorer**
Browser Version:  **IE11**

## Expected Behavior -
Finding an element with any available selector using Selenium hub.

## Actual Behavior -
"Element not found" or "Undefined index: ELEMENT"

## Steps to reproduce -
I'm using Facebook PHP bindings in this example, but I can reproduce with old PHPUnit ones too. The issue only happens when using the hub mode. Provided test case should be simple enough to be translated to another bindings.

- Run a selenium hub : java -jar selenium-server-standalone-3.6.0.jar -enablePassThrough false -role hub
- Run a selenium node : java -jar selenium-server-standalone-3.6.0.jar -enablePassThrough false -role node 
- Try [this code](https://gist.github.com/paulbriton/e740af8fcdb6621171f48c9d692af24a).

**Comment by jimevans** [comment]
The IE driver (and indeed no driver implementation) has used `ELEMENT` as the key for an element reference for over a year now. The bindings need to be updated to use the proper key.

**Comment by paulbriton** [comment]
So why this only happens with IE driver using the hub ?

**Comment by jimevans** [comment]
Because the IE driver now supports the W3C WebDriver Specification dialect of the wire protocol used for communication. In prior versions, the driver would return an element representation that used both keys in the dictionary. It no longer does so. I strongly suspect that if the language bindings used `IEDriverServer.exe` directly instead of the Java standalone server, they would encounter the same issue.

**Comment by paulbriton** [comment]
My guess was if it doesn't work, it doesn't work for both stand-alone and hub. 

It's not possible to keep both keys in the dictionary ? This way, it'll give us some time to make the proper change in the bindings. The support of the W3C spec is currently in progress in the facebook php bindings.

**Comment by paulbriton** [comment]
Also, which version should I use to avoid this problem ?

**Comment by paulbriton** [comment]
Answering last question myself, IEDriverServer 3.4 does the trick !

**Comment by Rialakshmi** [comment]
@paulbriton You saved my day. 3.4 worked for me. Thanks a lot!!!
