### ISSUE TITLE
Unable to retrieve browser console logs in IE11

### ISSUE THREAD

**Issue by vkhromenkov** [SeleniumHQ/selenium#4802]
## Meta -
OS:  
Windows 7 Pro
Selenium Version:  
3.5.3
Browser:  
Internet Explorer 11
Browser Version:  
11.0.9600.18792

## Expected Behavior - 
successfully retrieved browser console logs with driver.manage().logs().get("browser")

## Actual Behavior - 
```
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:83)
	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
```

## Steps to reproduce -

Simple piece of code:
```java
WebDriver driver = new InternetExplorerDriver();
driver.manage().logs().get("browser");
```
Just a note that it works fine on Chrome and fails on Firefox due to not implemented in gecko driver

**Comment by lmtierney** [comment]
Console logs are not available from IE
