### ISSUE TITLE
Selenium 3.6.0 (Java client) is unable to navigate to the URL with existing Firefox profile

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4803]
## Meta - Selenium 3.6.0 (Java client) is unable to navigate to the URL with existing Firefox profile

OS:  Windows 8 Pro
Selenium Version:  3.6.0
Browser:  Mozilla Firefox
Browser Version:  56.0 - 64 bit
GeckoDriver: v0.19.0

## Steps to reproduce -

1. Created a Firefox profile through Profile Manager (Mozilla Firefox: 56.0 - 64 bit) as "debanjan" which gets created at "C:\Users\AtechM_03\AppData\Roaming\Mozilla\Firefox\Profiles\l85yv0bu.debanjan"

2. Referred to the [documentation](https://github.com/mozilla/geckodriver#firefox-capabilities) which clearly mentions:

`To have geckodriver pick up an existing profile on the filesystem, you may pass ["-profile", "/path/to/profile"].`

3. Changed my code as follows:

		package demo;

		import org.openqa.selenium.WebDriver;
		import org.openqa.selenium.firefox.FirefoxDriver;
		import org.openqa.selenium.firefox.FirefoxOptions;

		public class FirefoxProfile {

			public static void main(String[] args) {

			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			FirefoxOptions opt = new FirefoxOptions();
			opt.addArguments("-profile", "C:\\Users\\AtechM_03\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\l85yv0bu.debanjan");
			WebDriver driver = new FirefoxDriver(opt);
			driver.get("https://google.com");
			}
		}

4. On execution, Mozilla Firefox browser gets initialized but doesn't navigates to the url "https://google.com".

5. Trace Logs : 

		1507042822078	geckodriver	INFO	geckodriver 0.19.0
		1507042822097	geckodriver	INFO	Listening on 127.0.0.1:6525
		1507042823284	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\AtechM_03\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\l85yv0bu.debanjan"
		1507042829832	Marionette	INFO	Enabled via --marionette
		1507042850845	Marionette	INFO	Listening on port 2828

**Comment by Debanjan-B** [comment]
@barancev Congrats on being on board of the Steering Committee !!!

**Comment by moisesGlb** [comment]
I have the same problem, do you know a solution for that? what do you mean with profile?

**Comment by lmtierney** [comment]
@Debanjan-B can you enable trace logs for both Java and geckodriver? We need to see what exactly is being sent with the new session command

**Comment by lmtierney** [comment]
It looks like it is sending the command over correctly, but I want to be sure before I blame it on mozilla

**Comment by mgconno** [comment]
Has anyone found a workaround for this issue. I'm having the same problem.  I've seen in other threads recommendations to use different versions of Firefox, but I can't change my version because of work constraints.

**Comment by Debanjan-B** [comment]
What is the version you are using?

**Comment by mgconno** [comment]
On my windows box where I am doing development I can only use Firefox ESR 52.4.0 (32-bit).

I will need in the future for this maven built selenium test to run on a Jenkins server that has Firefox 52.1/2/3 or 45.0 thru 8 or 38.* so I am more flexible in the long run, but I need to get it working on my box first. It works with Chrome, but IE doesn’t work either.

**Comment by barancev** [comment]
Selenium client library passes Firefox arguments to geckodriver, and it should decide what to do with these arguments. Please raise an issue on geckodriver tracker: https://github.com/mozilla/geckodriver/issues
