### ISSUE TITLE
ChromeOptions NoSuchMethodError addArguments

### ISSUE THREAD

**Issue by rmebamds** [SeleniumHQ/selenium#4804]
## Meta -
OS:  Ubuntu 16.04
Selenium Version:  3.6.0 w/ latest ChromeDriver 
Browser:  Latest Chrome

Upgrading from 3.5.3 to 3.6.0 has resulted in some bizarre behavior.  I'm getting NoSuchMethodError with addArguments of ChromeOptions: 

java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)Lorg/openqa/selenium/chrome/ChromeOptions;

Running Reflection just before my instantiation of ChromeOptions clearly shows the methods are there.

Reverting back to 3.53.0 solves the issue.  It seems like classpath pollution, but both versions have that method.

My code has basically been the same throughout several years of using Selenium.  I would paste the code but it's irrelevant, it dies after ChromeOptions is instantiated and the first call to addArguments.  I've tried it with a List/String[]/Individual String.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

We did not change ChromeOptions.addArguments method, appeal to community for help to resolve classpath issue.

**Comment by odemkovych** [comment]
rmebamds, I think you should recompile your library/code which uses the addArguments method. Because in the new 3.6.0 selenium library the addArguments has changed signature:  return value of the method is changed.

**Comment by Volker-59** [comment]
@barancev 

I have the same problem. Versin 3.6.0 / Won 2008 Srv and Chrome 2.33, JAVA 1.6.x

```
...[java] Exception in thread "main" java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeOptions.addArguments([Ljava/lang/String;)V...
```

and all is new recompiled....

```
ChromeOptions chromeOptions = new ChromeOptions();

String webdriverChromeDriver = new MonitoringHelper().getProperty("CHROMEDRIVER");
System.setProperty("webdriver.chrome.driver", webdriverChromeDriver);

chromeOptions.addArguments("no-sandbox");
chromeOptions.addArguments("start-maximized");
chromeOptions.addArguments("ignore-certificate-errors");
chromeOptions.addArguments("disable-infobars");

capability = DesiredCapabilities.chrome();
capability.setCapability(ChromeOptions.CAPABILITY, chromeOptions);

remWebDriver = new org.openqa.selenium.remote.RemoteWebDriver(new URL(hubURL), capability);
```

The Eclipse Helper shows me, the method exist and I have only the 3.6.0 Libs in my Classpath.

Any idea?
