### ISSUE TITLE
Browser Window not getting Focus Sometimes in Legacy Mode (even with Native Events)

### ISSUE THREAD

**Issue by gwtuser** [SeleniumHQ/selenium#4805]
## Meta -
OS:  OpenSUSE 42.2 64-bit
Selenium Version:  3.5.3
Browser:  Firefox ESR
Browser Version:  FF45ESR and FF52ESR

## Expected Behavior -
When "native event" support is enabled (as we've been doing since Selenium v2), browser window should get focus properly, and it did for v2.53.1 in FF45ESR.  (In our case, certain elements don't act properly without focus.)

## Actual Behavior -
In Legacy Mode and any FF, from FF45ESR to FF52ESR to FF56, native events seem broken in that the browser no longer seems to give the window focus properly after the get() call is made on the driver.

## Steps to reproduce -
Focus works properly in FF52ESR with new gecko driver (non-legacy) mode.  Before I go to the trouble of creating a repro-case, what is the status of "native event" support in Legacy Mode?  Will it be supported?  Or is it going to be left "as is"?

**Comment by barancev** [comment]
Native events in legacy driver were removed in version 3.1.0. There is no plan to restore them.

**Comment by gwtuser** [comment]
I could understand no maintenance being done on Legacy Mode, by why intentionally break it by removing features from WebDriver v2?  For our customers, Legacy Mode is unusable without native event support.  I would've assumed that full Legacy Mode support (including native events) would have remained intact until Legacy Mode itself got removed.

**Comment by gwtuser** [comment]
Can you please respond?  Is "legacy mode" supported at all?  If I file a bug against it, will it just be closed?

**Comment by barancev** [comment]
Legacy mode is supported as legacy. No new features, no bug fixes. But we accept pull requests.

**Comment by gwtuser** [comment]
So you're saying that the only way to get bugs fixed in legacy mode is for me to submit fixes myself?

**Comment by barancev** [comment]
1) Native events had gone forever.
2) We try to fix issues in legacy driver with synthesized events if they are critical.
3) Also we accept pull request for less critical issues.
4) Yes, the easiest wat to get a bug fixed in legacy driver is to fix it yourself and submit a pull request.
