### ISSUE TITLE
Driver neither navigating to page nor throwing an error

### ISSUE THREAD

**Issue by joshash** [SeleniumHQ/selenium#4810]
I am running Mac OSX, Python 3, and am using the latest version of the Chrome Driver and selenium. 

Here is my meager code so far:
```
import selenium
from selenium import webdriver

driver = webdriver.Chrome(executable_path="/usr/local/bin/chromedriver")


driver.get('htttp://economist.com')

```
I get no error, but a Chrome window opens to a blank page.

**Comment by lmtierney** [comment]
> driver.get('htttp://economist.com')
got an extra `t` in that `http`
