### ISSUE TITLE
Tell chromedriver which public IP to bind to

### ISSUE THREAD

**Issue by arya6000** [SeleniumHQ/selenium#4813]
I think chromedriver supports this, but there is no way to pass this from Selenium

If a machine has multiple public IPs, selenium would be able to tell chromedriver which IP to bind to. I think the relevant file to modify would be ChromeDriverService.java

**Comment by p0deje** [comment]
How do you tell ChromeDriver to bind to the other port?

**Comment by barancev** [comment]
It seems that chromedriver has no such an option:
```
C:\Users\alexei>chromedriver -h
Usage: chromedriver [OPTIONS]

Options
  --port=PORT                     port to listen on
  --adb-port=PORT                 adb server port
  --log-path=FILE                 write server log to file instead of stderr, in
creases log level to INFO
  --verbose                       log verbosely
  --version                       print the version number and exit
  --silent                        log nothing
  --url-base                      base URL path prefix for commands, e.g. wd/url

  --port-server                   address of server to contact for reserving a p
ort
  --whitelisted-ips               comma-separated whitelist of remote IPv4 addre
sses which are allowed to connect to ChromeDriver
```

**Comment by jleyba** [comment]
I believe this is what the `--whitelisted-ips` option is for.

**Comment by p0deje** [comment]
I don’t think that whitelisted IPs is the same because chromedriver still binds to localhost. In any event, it can already be configured using service arguments.

Closing this since it’s not clear what to do with it. Please comment with explanation to reopen.

**Comment by tdaniely** [comment]
whitelisted-ips describes behavior of which external addresses are allowed to connect, but for some reason this effects the bind address? These are two separate subjects.

**Comment by stevenkaras** [comment]
FYI - chromedriver explicitly binds either on 127.0.0.1 or 0.0.0.0. There is no support there for binding the control socket to any other address (I checked, and it's nontrivial to hack in).
