### ISSUE TITLE
Rselenium in parallel: error when try to open page in a node

### ISSUE THREAD

**Issue by mislav0207** [SeleniumHQ/selenium#4822]
On following site: Run RSelenium in parallel, I have found out how to open multiply browsers (sessions) in parallel using parallel package:

```
 library(RSelenium)
library(rvest)
library(magrittr)
library(foreach)
library(doParallel)

# number of cores
(cl <- (detectCores() - 1) %>%  makeCluster) %>% registerDoParallel

# open a remoteDriver for each node on the cluster
# docker run -d -p 4445:4444 selenium/standalone-chrome:3.4.0
clusterEvalQ(cl, {
  library(RSelenium)
  remDr <- remoteDriver(remoteServerAddr = "192.168.99.100", port = 4445L,
                        browserName = "chrome")
  remDr$open()

})
```

But if I add only one additional line of code that open specific page:
```
clusterEvalQ(cl, {
  library(RSelenium)
  remDr <- remoteDriver(remoteServerAddr = "192.168.99.100", port = 4445L,
                        browserName = "chrome")
  remDr$open()
  Sys.sleep(3L)
  remDr$navigate("http://plovila.pomorstvo.hr/")
})
```
it returns an error:
```
Error in checkForRemoteErrors(lapply(cl, recvResult)) : 
  6 nodes produced errors; first error:      Summary: UnknownError
     Detail: An unknown server-side error occurred while processing the command.
     class: org.openqa.selenium.WebDriverException
     Further Details: run errorDetails method
```
Why it returns an error with this additional line of code?

There is one more strange thing. It sometimes works at firs, but after if I try more times it returns an error all the time.

**Comment by barancev** [comment]
What is the server error? Are there error messages on the server console? To get logs you can use a local selenium server (not containerized) or a debug version of container.

**Comment by mislav0207** [comment]
I have installed chrome-debugf and TightVNC. I have executed my code several times and looked at VNC viewer. It opens some sites but not all (some nodes return error). When I have tried smaller number of cores it worked sometimes. Maybe it is a problem when I try to open 7 web pages at the same time (in parallel)? I don't know where to find log files?

**Comment by mislav0207** [comment]
If I use 5 cores it works fine, but if I use 6 or more cores it returns an error above.

**Comment by barancev** [comment]
Here is info how to find logs: https://github.com/SeleniumHQ/docker-selenium#troubleshooting

**Comment by barancev** [comment]
Closing the issue, there is nothing actionable here.
