### ISSUE TITLE
Selenium IDE error

### ISSUE THREAD

**Issue by adrianortiz14** [SeleniumHQ/selenium#4823]
Anyone else ever get this error message when using Selenium IDE on Firefox?

*There was an unexpected error. Msg: TypeError: Components.classes['@mozilla.org/supports-array;1'] is undefined
Url: chrome://selenium-ide/content/xul-utils.js, line: 36, column: 13
toXPCOMArray@chrome://selenium-ide/content/xul-utils.js:36:13
_loadSeleniumCommands@chrome://selenium-ide/content/treeView.js:200:55
initialize@chrome://selenium-ide/content/treeView.js:90:13
classCreate/<@chrome://selenium-ide/content/selenium-core/scripts/htmlutils.js:23:7
Editor@chrome://selenium-ide/content/editor.js:170:19
SidebarEditor@chrome://selenium-ide/content/sidebar-editor.js:22:5
onload@chrome://selenium-ide/content/selenium-ide-sidebar.xul:1:1*

**Comment by barancev** [comment]
See #4406
