### ISSUE TITLE
getting unhandledAlertException on Selenium 3.5.3

### ISSUE THREAD

**Issue by febyraju** [SeleniumHQ/selenium#4824]
Windows 64-Bit OS
Selenium: 3.5.3
Mozilla: 57.0b5
Gecko: geckodriver-v0.19.0-win64

Getting org.openqa.selenium.UnhandledAlertException when upgraded selenium, gecko and FF to latest version given above for my automation.
I have right click and a user authentication in my application and want to handle those but the latest version give UnhandledAlertException.

SKIPPED CONFIGURATION: @AfterClass afterClass
SKIPPED: testMethod
org.openqa.selenium.UnhandledAlertException: : 
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'QATEST003', ip: '10.0.8.249', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\fraju\AppData\Local\Temp\2\rust_mozprofile.HaqKoI8mS6hI, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0, platformVersion=6.3, moz:processID=17224, browserName=firefox, javascriptEnabled=true, platformName=XP, moz:webdriverClick=false}]

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by febyraju** [comment]
But i get this org.openqa.selenium.UnhandledAlertException only after upgrading to Firefox 56 and greater.
FF54 doesn't shows this error and curious to know is that something related to new version.
