### ISSUE TITLE
socket.error: [Errno 111] Connection refused when initialising Firefox webdriver

### ISSUE THREAD

**Issue by bje-** [SeleniumHQ/selenium#4826]
## Meta -
OS:  Linux
Selenium Version:  2.53.2
Browser:  Firefox
Browser Version: 45.3.0  

## Expected Behavior -
No exception.

## Actual Behavior -
A socket.error exception is raised.

## Steps to reproduce -

Run this script via `xvfb-run -d python fail.py`:

from selenium import webdriver
browser = webdriver.Firefox()

Intermittently, this script produces the traceback shown in the attachment.
[traceback.txt](https://github.com/SeleniumHQ/selenium/files/1367202/traceback.txt)

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bje-** [comment]
I have provided a tiny test case that fails intermittently. I am unable to reliably reproduce the problem (at this stage).

**Comment by p0deje** [comment]
I can't reproduce this neither locally nor on CI, so without any additional information (like environment description), it's impossible to diagnose the problem.

**Comment by bje-** [comment]
I can't reproduce it with Firefox running on my local X display (in a shell loop!). I'll now try with xvfb (which is where I saw the problem originally).

**Comment by bje-** [comment]
Unable to reproduce consistently. I've ditched xvfb-run and am now using pyvirtualdisplay instead. I suspect it will work more reliably.
