### ISSUE TITLE
Chrome driver reloaded on Clicking specific element on webpage

### ISSUE THREAD

**Issue by Fatimi** [SeleniumHQ/selenium#4827]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.6
Browser:  
Chrome 

Currently problem I m facing is when I click on specific element in chrome browser the Webpage gets reloaded and makes my script to get failed

package pmo_automation;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.security.Credentials;
import org.openqa.selenium.security.UserAndPassword;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.gargoylesoftware.htmlunit.javascript.host.Location;
import com.gargoylesoftware.htmlunit.javascript.host.Window;

public class loginPage  {
	
	
	public static void main(String[] args) throws IOException, InterruptedException  {
			
		
		System.setProperty("webdriver.chrome.driver", "C:/Users/aamir.fatimi/Downloads/chromedriver_win32/chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.navigate().to("http://sohaib.ahmed:nov@1234@dbu-export-09/en/Pages/default.aspx/");

WebElement eservices1 = driver.findElement(By.linkText("E-SERVICES"));
		eservices1.click();
		
	 }
}

**Comment by p0deje** [comment]
`dbu-export-09` cannot be reached from Internet.

Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided,
