### ISSUE TITLE
Need to handle HttpAuth popup through Selenium Webdriver on Firefox

### ISSUE THREAD

**Issue by Fatimi** [SeleniumHQ/selenium#4828]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.6
Browser:  
Firefox Latest

Can anyone help me here I need to handle httpAuth through Selenium Webdriver.

![10-9-2017 6-59-07 pm](https://user-images.githubusercontent.com/3796742/31341847-49d5026a-ad24-11e7-96ba-e966b814d2a9.png)

**Comment by milanoid** [comment]
Quick and dirty solution is to pass Basic http auth credentials (username and password) directly in the URL itself. E.g. http://username:password@hostname.com. Firefox might prompt you with confirmation alert window though.

**Comment by p0deje** [comment]
W3C WebDriver specification doesn't require HTTP basic authentication support. Please, track w3c/webdriver#385 for updates.
