### ISSUE TITLE
JS: buggy passing of URL base path to chromedriver 

### ISSUE THREAD

**Issue by dbo** [SeleniumHQ/selenium#483]
The --url-base parameter is passed as --url-base=<url> whereas chromedriver expects it as --url-base <url>.

**Comment by jleyba** [comment]
Just checked chromedriver 2.14 and 2.15.  Both accept --url-base=/foo

**Comment by dbo** [comment]
I've debugged the problem further, it's twofold:
- using chromedriver --url-base <url> does NOT work (though chromedriver serves / without complaining)
- Actually the problem is that the client is not storing the given base path resp. passing it to the driver service.

I'll create another pull request for that.
