### ISSUE TITLE
Unable to click on a salesforce tag :: after (.support-servicedesk-navigator .x-btn-mc em.x-btn-split:after) using webdriver

### ISSUE THREAD

**Issue by vinitsriwastava** [SeleniumHQ/selenium#4831]
Unable to click on a salesforce tag :: after (.support-servicedesk-navigator .x-btn-mc em.x-btn-split:after) using webdriver

![image](https://user-images.githubusercontent.com/17021013/31344246-c90f643e-ad2f-11e7-883f-6516621cad0c.png)

<em class="x-btn-split" unselectable="on" id="ext-gen80">
<button type="button" id="ext-gen33" class=" x-btn-text">
<div class="mruIcon">
<img class="tabIcon" src="https://acet-uhg--PPIT--c.cs65.content.force.com/servlet/servlet.ImageServer?id=0150m0000009750&amp;oid=00D0m0000000Op2&amp;lastMod=1506338189000" alt="">
</div><span>Member Search</span>
</button>
</em>

Need to click on arrow icon

![image](https://user-images.githubusercontent.com/17021013/31344370-21221ef0-ad30-11e7-8cab-73d49e803995.png)

I have tried action and css both but nothing worked:

WebElement ele = driver.findElement(By.xpath("//*[@id='ext-gen128']");
Actions build = new Actions(driver);
build.moveToElement(ele, Xoffset, Yoffset).click().build().perform();

Please help me.

Thanks,
Sumit

**Comment by vinitsriwastava** [comment]
![image](https://user-images.githubusercontent.com/17021013/31344706-0cba9644-ad31-11e7-82b8-1fb30e9711bc.png)

CSS part of the UI

**Comment by kumar-nitish** [comment]
@vinitsriwastava  It would be helpful if you could share your full web page dump along with the exact code snippet you are using because above shared code snipped seems to be a dummy example because they have different id.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
