### ISSUE TITLE
Selenium Documentation mentions dubious Method Detail for getScreenshotAs() method

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4833]
## Meta - [Selenium Documentation](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/TakesScreenshot.html) mentions dubious Method Detail for getScreenshotAs() method

First it mentions:

> For **WebDriver** extending TakesScreenshot, this makes a best effort depending on the browser to return the following in order of preference:
> 
> - Entire page
> 
> - Current window
> 
> - Visible portion of the current frame
> 
> - The screenshot of the entire display containing the browser

In the very next line it mentions:

> For **WebElement** extending TakesScreenshot, this makes a best effort depending on the browser to return the following in order of preference: - The entire content of the HTML element - The visible portion of the HTML element

OS:  All

Selenium Version:  3.6

Browser:  All

Browser Version:  

## Steps to reproduce -

Browse to Interface [**`TakesScreenshot`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/TakesScreenshot.html) page and observe the **`getScreenshotAs()`** Method Detail.

**Comment by lmtierney** [comment]
I'm not sure what the issue is?

**Comment by Debanjan-B** [comment]
Sorry to get back late on this but how can `WebDriver` and `WebElement` both extend `TakesScreenshot` ?

**Comment by lmtierney** [comment]
https://w3c.github.io/webdriver/webdriver-spec.html#take-element-screenshot

**Comment by lmtierney** [comment]
http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html

**Comment by Debanjan-B** [comment]
@lmtierney Thanks, you pointed me to the right documentations. Somehow I am still not fully convinced.

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
