### ISSUE TITLE
How to change screen resolution in a phantomjs from selenium?

### ISSUE THREAD

**Issue by Firues** [SeleniumHQ/selenium#4834]
Hello. 
This is clear phantomjs code for js (This code changes the resolution.):
```
var WebPage = require('webpage');
page = WebPage.create()

page.onInitialized = function () {
    page.evaluate(function () {
        window.screen = {width: 1600, height: 900, availWidth: 1600, availHeight: 900};
    });
};

page.open('http://browserspy.dk/screen.php');
page.onLoadFinished = function () {
    page.render('ScreenShot' + '.png');
    phantom.exit();
}
```

How to change on selenium? (Please don't suggest to change the viewportSize. This is not the screen resolution.)
Thank you very much.

**Comment by lmtierney** [comment]
It is not possible via selenium. Also, PhantomJS support is now deprecated (since it was abandoned) in support of headless Chrome or headless Firefox. We also have docker containers https://github.com/SeleniumHQ/docker-selenium
