### ISSUE TITLE
C# Selenium does not perform Click / Sendkey operations  on IE 11 - Windows Server 2012 R2 environment

### ISSUE THREAD

**Issue by sathishkumarperumal** [SeleniumHQ/selenium#4837]
OS:  
Windows Server 2012 R2
Selenium Version:  2.33
Browser:  Internet Explorer 11

## Actual Behavior - Click / sendkey operations are not working

Steps : 

Develop selenium C# n unit test and run from above OS/Browser/Selenium version.

Regards,
Sathish

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided,
