### ISSUE TITLE
Failed to start webdriver session with RemoteWebDriver

### ISSUE THREAD

**Issue by adam-zjy** [SeleniumHQ/selenium#4840]
## Meta -
OS:  
Windows 10
Selenium Version:  
Selenium 3.5.3
Browser:  
Chrome 60 / Firefox 56

## Expected Behavior -
Browsers should be started and ready for testing

## Actual Behavior -
I can see the browsers are start up but it will be closed rapidly in the next second

### Source Code for FireFox

`
            DesiredCapabilities capabilities = DesiredCapabilities.firefox();
            System.setProperty("webdriver.gecko.driver", // path of geckodriver.exe)
            FirefoxBinary binary = // path of the firefox.exe
            FirefoxOptions options = new FirefoxOptions();
            options.setBinary(binary);
            options.setLogLevel(Level.ALL);
            capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, options);
            RemoteWebDriver driver = new RemoteWebDriver(url, capabilities)
`
### Log trace for Firefox
C:\AutoBBM\project\grid\WebContent\WEB-INF\lib>java -Dwebdriver.gecko.driver=geckodriver.exe -jar selenium-server-standalone-3.5.3.jar -role node -nodeConfig nodeconfig.json
16:05:51.780 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:05:51.790 INFO - Launching a Selenium Grid node
2017-10-10 16:05:55.752:INFO::main: Logging initialized @6630ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:05:56.100 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:05:56.250 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
16:05:56.464 INFO - Using the passthrough mode handler
2017-10-10 16:05:56.656:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-10-10 16:05:56.911:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@32c726ee{/,null,STARTING} has uncovered http methods for path: /
2017-10-10 16:05:56.974:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@32c726ee{/,null,AVAILABLE}
2017-10-10 16:05:57.115:INFO:osjs.AbstractConnector:main: Started ServerConnector@4839623b{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-10-10 16:05:57.154:INFO:osjs.Server:main: Started @8031ms
16:05:57.161 INFO - Selenium Grid node is up and ready to register to the hub
16:05:57.235 INFO - Starting auto registration thread. Will try to register every 5000 ms.
16:05:57.252 INFO - Registering the node to the hub: http://localhost:4444/grid/register
16:05:57.863 INFO - The node is registered to the hub and ready to use
2017-10-10 16:06:29.919:INFO:osjshC.ROOT:qtp1041109062-22: org.openqa.selenium.remote.server.WebDriverServlet-1838ccb8: Initialising WebDriverServlet
16:06:30.189 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
16:06:30.210 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@507bee15
16:06:30.238 INFO - /session: Executing POST on /session (handler: BeginSession)
16:06:30.398 INFO - Capabilities are: Capabilities {acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=trace}, binary=C:\AutoBBM\project\build-au..., prefs={}, }, }
16:06:30.444 INFO - Capabilities {acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=trace}, binary=C:\AutoBBM\project\build-au..., prefs={}, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
16:06:30.506 INFO - Capabilities {acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=trace}, binary=C:\AutoBBM\project\build-au..., prefs={}, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
16:06:30.558 INFO - Capabilities {acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=trace}, binary=C:\AutoBBM\project\build-au..., prefs={}, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1507622791017   geckodriver     INFO    geckodriver 0.18.0
1507622791080   geckodriver     INFO    Listening on 127.0.0.1:27773
1507622791551   geckodriver::marionette INFO    Starting browser C:\AutoBBM\project\build-auto\browsers\firefox\56\Mozilla Firefox\firefox.exe with args ["-marionette"]
1507622792448   addons.xpi      WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/AutoBBM/project/build-auto/browsers/firefox/56/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1507622793646   geckodriver::marionette TRACE     connection attempt 0/600
1507622793708   Marionette      DEBUG   Received observer notification "profile-after-change"
1507622794079   Marionette      DEBUG   Received observer notification "command-line-startup"
1507622794079   Marionette      INFO    Enabled via --marionette
1507622795757   geckodriver::marionette TRACE     connection attempt 1/600
1507622797864   geckodriver::marionette TRACE     connection attempt 2/600
Unable to read VR Path Registry from C:\Users\I073397\AppData\Local\openvr\openvrpaths.vrpath
[Parent 5068] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\I073397\AppData\Local\openvr\openvrpaths.vrpath
[Child 10324] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1507622798893   Marionette      DEBUG   Received observer notification "sessionstore-windows-restored"
1507622799434   Marionette      DEBUG   Setting recommended pref app.update.auto to false
1507622799436   Marionette      DEBUG   Setting recommended pref app.update.enabled to false
1150756027267292979944736       geckodriv9e     rM:a:rmiaornieottnee    tDtEeB  UDGE    BSUeGt  tCionngn ercetceodm mteon dMeadr iporneeft tteo on olkit.cosmeticAnimations.enabled to false
1507622799441   Marionette      DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
l1507o6c2a2l7h9o9s4t4:2 6M1a8r2i2o
1507622799776   geckodriver::marionette TRACE   <- {"applicationType":"gecko","marionetteProtocol":3}
nette   DEBUG   Setting recommended pref dom.file.createInChild to true
1507622799447   Marionette      INFO    Listening on port 61822
1507622799760   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:61841
11550077662222779999956 Marionette      TRACE   0 -> [0,1,"newSession",7{7"6a   cgceecpktoIdnrsievceurr:e:Cmearrtiso"n:ettrtuee ,T"RbArCoEwserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
        -> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsec1507622799969        Marionette      CONFIG  Matched capabilities: {"browserName":"firefox","browserVersion":"56.0","platformName":"windows_nut",r"epClearttfso"r:mtVreures,i"obnr"o:w"s1e0r.N0a"m,e""p:a"gfeiLroeafdoSxt"r}a}t}e]g
y":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificatio1507622800422       geckodriver::marionette TRACE   <- [1,1,null,{"sessionId":"07a54d8f-0898-4a41-b2ee-b33e8f9001a8","capabilities":{"brnowseLreNvaemle""::0",f"imroezf:opxr"o,c"ebsrsoIwDs"e:r5V0e6r8s,i"omno"z::"p5r6o.f0i"l,e""p:l"aCt:f\o\rUmsNearmse\"\:I"0w7i3n3d97\\oAppDatwas\_\nLto"c,a"lp\l\aTtefmopr\m\Vreurst_mozprofiles.ieoDns"U:jal7PTe1","moz:acce"s1s0i.b0i"l,i"tpyaCgheeLcokasd"S:tfraategy":"normal","acceptInsecureCerts":true,Dtimeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specifilcatisoen,L"emvoezl:"h:e0a,d"lmeoszs:"p:rfoaclesses}I
":5068,"moz:profile":"C:\\Users\\I073397\\AppData\\Local\\Temp\\rust_mozprofile.eDsUjal7PTe1","moz:accessibilityChecks":false,"moz:headless":false}}]
1507622800423   webdriver::server       DEBUG   <- 200 OK {"value": {"sessionId":"07a54d8f-0898-4a41-b2ee-b33e8f9001a8","capabilities":{"ac1c5e0p7t6I2n2s7e9c9u9r6e9C        eMratrsi"o:ntertutee,   "WbArRoNw       sTeLrSN acmeer"t:i"ffiicraetfeo xe"r,r"obrrso wwsielrlV ebres iiognn"t:"56r.e0d" ,f"omro zt:haicsc essessisbiiolni
1507622800247   Marionette      DEBUG   Register listener.js for window 4294967297
y15076C2h2e8c0k0s4"1:1f aMlse,"moz:heaardiloensest"t:ef aTlRsAeC,E"     m0o z<:-p r[o1c,e1s,snIuDll,{"sessionId":"07a54d8f-0898-4a41-":5068,"moz:profile":"C:\\Users\\I073397\\AppData\\Local\\Temp\\rust_mozprofile.eDsUjal7PTe1","pageLoadStrategy":"normal","platfb2ee-b33e8f9001a8","capabilities":{"browserName":"firefox","browserVersion":"56.0","platformName":"windows_nt","platformVersion"ormName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":3000:"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotat00,"script"a:3ble":false,"specifi0cationLevel":0,"moz:processID":5068,"moz:profile":"C:\\Users\\I073397\\AppData\\Local\\Temp\\r000}}}}
ust_mozprofile.eDsUjal7PTe1","moz:accessibilityChecks":false,"moz:headless":false}}]
16:06:42.899 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@1e577ff4
16:06:42.913 INFO - Handler thread for session 07a54d8f-0898-4a41-b2ee-b33e8f9001a8 (firefox): Executing DELETE on /session/07a54d8f-0898-4a41-b2ee-b33e8f9001a8 (handler: ServicedSession)
1507622803016   webdriver::server       DEBUG   -> DELETE /session/07a54d8f-0898-4a41-b2ee-b33e8f9001a8
1507622803019   Marionette      TRACE   0 -> [0,2,"quit",{"flags":["eForceQuit"]}]
1507622803017   geckodriver::marionette TRACE   -> 37:[0,2,"quit",{"flags":["eForceQuit"]}]
1507622803021   Marionette      INFO    New connections will no longer be accepted
1507622803242   Marionette      TRACE   0 <- [1,2,null,{"cause":"shutdown"}]
[Parent 5068] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1507622803294   geckodriver::marionette TRACE   <- [1,2,null,{"cause":"shutdown"}]
1507622803294   webdriver::server       DEBUG   Deleting session
1507622803294   geckodriver::marionette DEBUG   Stopping browser process
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
1507622803513   webdriver::server       DEBUG   <- 200 OK {"value": {}}
16:06:43.521 INFO - To downstream: {"value": {}}
16:06:43.542 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@1e577ff4
1507622803560   webdriver::server       DEBUG   -> DELETE /session/07a54d8f-0898-4a41-b2ee-b33e8f9001a8
16:06:43.566 INFO - To downstream: {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x44787f - <no info>\n   3:           0x4203e1 - <no info>\n   4:           0x407dc7 - <no info>\n   5:           0x6d95b9 - <no info>\n   6:           0x4173a7 - <no info>\n   7:           0x6d38b3 - <no info>\n   8:     0x7ff8e5128102 - BaseThreadInitThunk"}}
1507622803563   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"session not created","message":"Tried to run command without establishing a connection","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x44787f - <no info>\n   3:           0x4203e1 - <no info>\n   4:           0x407dc7 - <no info>\n   5:           0x6d95b9 - <no info>\n   6:           0x4173a7 - <no info>\n   7:           0x6d38b3 - <no info>\n   8:     0x7ff8e5128102 - BaseThreadInitThunk"}}
1507622803666   webdriver::server       DEBUG   -> GET /shutdown
1507622803669   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /shutdown did not match a known command","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x4319fd - <no info>\n   4:           0x425ca5 - <no info>\n   5:           0x407eba - <no info>\n   6:           0x6d95b9 - <no info>\n   7:           0x417655 - <no info>\n   8:           0x6d38b3 - <no info>\n   9:     0x7ff8e5128102 - BaseThreadInitThunk"}}

### Source Code for Chrome
`
           DesiredCapabilities capabilities = DesiredCapabilities.chrome();
           System.setProperty("webdriver.chrome.driver", // path of chromedriver.exe)
           Map<String, Object> chromeOptions = new HashMap<String, Object>();
        
           chromeOptions.put("binary", chromeApplicationLocation);
           chromeOptions.put("args", Arrays.asList("--user-data-dir=" + chromeUserDataLocation, "--start-maximized", "--disable-extensions", "--test-type", "--disable-popup-blocking", "--no-first-run", "disable-infobars"));
           capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
           RemoteWebDriver driver = new RemoteWebDriver(url, capabilities)
`

### Log trace for Chrome
16:25:27.490 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
16:25:27.501 INFO - Launching a Selenium Grid node
2017-10-10 16:25:30.290:INFO::main: Logging initialized @5494ms to org.seleniumhq.jetty9.util.log.StdErrLog
16:25:30.420 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:25:30.485 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform WIN10
16:25:30.557 INFO - Using the passthrough mode handler
2017-10-10 16:25:30.615:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-10-10 16:25:30.684:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@32c726ee{/,null,STARTING} has uncovered http methods for path: /
2017-10-10 16:25:30.705:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@32c726ee{/,null,AVAILABLE}
2017-10-10 16:25:30.772:INFO:osjs.AbstractConnector:main: Started ServerConnector@1afdd473{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-10-10 16:25:30.784:INFO:osjs.Server:main: Started @5988ms
16:25:30.789 INFO - Selenium Grid node is up and ready to register to the hub
16:25:30.822 INFO - Starting auto registration thread. Will try to register every 5000 ms.
16:25:30.830 INFO - Registering the node to the hub: http://localhost:4444/grid/register
16:25:31.135 INFO - The node is registered to the hub and ready to use
2017-10-10 16:26:09.545:INFO:osjshC.ROOT:qtp1041109062-23: org.openqa.selenium.remote.server.WebDriverServlet-1838ccb8: Initialising WebDriverServlet
16:26:09.811 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
16:26:09.828 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@d346229
16:26:09.865 INFO - /session: Executing POST on /session (handler: BeginSession)
16:26:10.294 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
16:26:10.357 INFO - Capabilities are: Capabilities {proxy={proxyAutoconfigUrl=http://proxy:8083, proxyType=PAC, }, onlyProxySeleniumTraffic=true, avoidProxy=true, browserName=chrome, chromeOptions={args=[--user-data-dir=C:\AutoBBM\..., --start-maximized, --disable-extensions, --test-type, --disable-popup-blocking, --no-first-run, disable-infobars], binary=C:\AutoBBM\project\build-au..., prefs={download.prompt_for_download=false, profile.managed_default_con...=1, download.default_directory=C:\Users\I073397\AppData\Lo..., }, }, platformName=ANY, version=, platform=ANY, }
16:26:10.543 INFO - Capabilities {proxy={proxyAutoconfigUrl=http://proxy:8083, proxyType=PAC, }, onlyProxySeleniumTraffic=true, avoidProxy=true, browserName=chrome, chromeOptions={args=[--user-data-dir=C:\AutoBBM\..., --start-maximized, --disable-extensions, --test-type, --disable-popup-blocking, --no-first-run, disable-infobars], binary=C:\AutoBBM\project\build-au..., prefs={download.prompt_for_download=false, profile.managed_default_con...=1, download.default_directory=C:\Users\I073397\AppData\Lo..., }, }, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
16:26:10.681 INFO - Capabilities {proxy={proxyAutoconfigUrl=http://proxy:8083, proxyType=PAC, }, onlyProxySeleniumTraffic=true, avoidProxy=true, browserName=chrome, chromeOptions={args=[--user-data-dir=C:\AutoBBM\..., --start-maximized, --disable-extensions, --test-type, --disable-popup-blocking, --no-first-run, disable-infobars], binary=C:\AutoBBM\project\build-au..., prefs={download.prompt_for_download=false, profile.managed_default_con...=1, download.default_directory=C:\Users\I073397\AppData\Lo..., }, }, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
16:26:10.804 INFO - Capabilities {proxy={proxyAutoconfigUrl=http://proxy:8083, proxyType=PAC, }, onlyProxySeleniumTraffic=true, avoidProxy=true, browserName=chrome, chromeOptions={args=[--user-data-dir=C:\AutoBBM\..., --start-maximized, --disable-extensions, --test-type, --disable-popup-blocking, --no-first-run, disable-infobars], binary=C:\AutoBBM\project\build-au..., prefs={download.prompt_for_download=false, profile.managed_default_con...=1, download.default_directory=C:\Users\I073397\AppData\Lo..., }, }, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41) on port 36397
Only local connections are allowed.
16:26:26.182 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@1b427ea8
16:26:26.196 INFO - Handler thread for session 2dd731fcd519079923b5fc1d72140efb (chrome): Executing DELETE on /session/2dd731fcd519079923b5fc1d72140efb (handler: ServicedSession)
16:26:26.363 INFO - To downstream: {"sessionId":"2dd731fcd519079923b5fc1d72140efb","status":0,"value":null}
16:26:26.412 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@1b427ea8
16:26:26.449 INFO - To downstream: {"sessionId":"2dd731fcd519079923b5fc1d72140efb","status":0,"value":null}

**Comment by adam-zjy** [comment]
Another thing need to clarified is that, I'm using -hubConfig to init the hub

The json file is configured like below.

{
"host": "localhost",
"port": "4444",
"newSessionWaitTimeout": -1,
"servlets": [gridext.CustomServlet,gridext.ManageHubServlet,gridext.ManageProxyServlet],
"prioritizer": null,
"capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
"throwOnCapabilityNotPresent": true,
"nodePolling": 5000,
"cleanUpCycle": 5000,
"timeout": 2940000,
"browserTimeout": 300000,
"maxSession": 1
}

**Comment by barancev** [comment]
I can't see any critical error messages in the provided logs.

Firefox:
```
1507622800423 webdriver::server DEBUG <- 200 OK {"value": {"sessionId":"07a54d8f-0898-4a41-b2ee-b33e8f9001a8","capabilities":
```
session started
```
1507622803019 Marionette TRACE 0 -> [0,2,"quit",{"flags":["eForceQuit"]}]
1507622803017 geckodriver::marionette TRACE -> 37:[0,2,"quit",{"flags":["eForceQuit"]}]
1507622803021 Marionette INFO New connections will no longer be accepted
```
session closed, everything looks ok.

Do you have any exceptions on the client side? Can you operate the created driver?

**Comment by adam-zjy** [comment]
No I can't do any operation on the driver, the browser is flash quit

Here is the log from the hub server:
09:23:10.612 INFO - Got a request to create a new session: Capabilities [{acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=trace}, binary=C:\AutoBBM\project\build-auto\browsers\firefox\56\Mozilla Firefox\firefox.exe, prefs={}}}]
09:23:10.622 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, acceptSslCerts=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, maxInstances=1, version=56.0, platform=WIN10, firefox_profile=}
09:23:23.285 WARN - session ext. key 2d815a4d-e01b-45a5-8c9a-48285155575a has TIMED OUT due to client inactivity and will be released.

**Comment by barancev** [comment]
Session expired by timeout, that means you did not attempt to execute any commands. Do you have any exceptions on the client side? What command fails exactly?

**Comment by adam-zjy** [comment]
hi

What do you mean for the 'client side', hub or node? I think all the consoles I've logged in the ticket.

The command which I run into I supposed should be POST on /session

**Comment by barancev** [comment]
'Client side' means the code written by you, the code that uses Selenium API.

**Comment by barancev** [comment]
Closing the issue, there is nothing actionable here.
