### ISSUE TITLE
Invalid W3C caps generated from Ruby bindings.

### ISSUE THREAD

**Issue by pulkitsharma07** [SeleniumHQ/selenium#4841]
Hi,

Using selenium-webdriver gem 3.6.0

When creating caps the following way
```ruby
 caps = Selenium::WebDriver::Remote::Capabilities.firefox
 caps["browser_version"] = "54"
```

Creates the following W3C capabilities:
```json
{  "capabilities" : {"firstMatch" : [{"browserName" : "firefox", "browser_version" : "54"}]}}
```
(https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/w3c/capabilities.rb#L162)
Here, `browser_version` key is not according to the W3C specification.

Any particular reason for this? According to me, it should be converted to camel case.

**Comment by p0deje** [comment]
There is a bit messy convention in how capabilities are processed:

1. If it's a symbol, it will be translated to camel case.
2. If it's a string, it will be kept as-is.

There is an outstanding issue to rework capabilities in Ruby bindings (#2478) to get rid of such inconsistencies. For now, please use symbols:

```ruby
 caps = Selenium::WebDriver::Remote::Capabilities.firefox
 caps[:browser_version] = "54"
```

**Comment by pulkitsharma07** [comment]
Just mentioning here, incase anybody faces the error
` W3C payload contained keys that do not comply with the spec: [browser_version]`

Since passthrough mode is enabled by default on the latest selenium jar versions, it will throw an error if `browser_version` is passed as a `string` instead of a `symbol`.
