### ISSUE TITLE
Chrome Clicking element in iframe that has "padding: 1rem .8rem 0 1.4rem!important;" fails

### ISSUE THREAD

**Issue by bebef1987** [SeleniumHQ/selenium#4842]
## Meta -
OS:  
All

Selenium Version:  
3.6.0

Browser:  
Chrome

Browser Version:  
61.0.3163.79 

Chrome driver:
2.33.506120

## Expected Behavior -
Element gauth-widget-frame should be clicked after we switch to frame 

## Actual Behavior -
Elemen is not clicked when `padding: 1rem .8rem 0 1.4rem!important;` is in the iframe style

## Steps to reproduce -
Run TestMeFail.java

Demo HTML:  https://github.com/bebef1987/demo-project/blob/sel_padding/padding.html

From 
https://github.com/bebef1987/demo-project/tree/sel_padding

**Comment by bebef1987** [comment]
Also tested with Selenium 3.5.3 and got the same behavior
As it'e failing only on chrome might be a driver issue

**Comment by barancev** [comment]
Raise an issue on chromedriver tracker
https://sites.google.com/a/chromium.org/chromedriver/help
