### ISSUE TITLE
Selenium Firefox Profile Path different from FirefoxProfile.ProfileDirectory

### ISSUE THREAD

**Issue by danwan** [SeleniumHQ/selenium#4844]
I'm using Selenium 3.5.3, geckodriver V0.19, FF 56.0 Language: C#

My Goal: Get the real profile path of the currently used profile. Temp Location.

Issue: When I use: FirefoxProfile.ProfileDirectory it gives me a profile path like this: C:\Users\dan\AppData\Local\Temp\anonymous.1d23xxxxxx.webdriver-profile

But that path doesn't exist.

When I check the Troubleshooting Information within FF, I get the following profile path: C:\Users\dan\AppData\Local\Temp\rust_mozprofile.ydmZeTAJyfZe

And that's the real path.

I know I can specify a profile that is loaded by Selenium for FF. That is working fine. I need to find the TMP location. Because I need to save the profile after I'm done with my automation stuff.

Selenium copies the specified profile to a TMP location, and does not store it back to the location where it was loaded from.

So if someone has an idea how to extract the firefox TMP profile location from within C#, that would be great.

PS: Searching the folders in the profile directory directly, and checking for the name and creation time, wouldn't be optimal because I'm multi threading.

**Comment by p0deje** [comment]
You can retrieve full path to Firefox profile from capabilities. In Ruby, it will look like this:

```ruby
driver = Selenium::WebDriver.for(:firefox)
driver.capabilities[:profile]
#=> "/var/folders/3s/yybq9c5n4pd0z9t4phtp6ml00000gn/T/rust_mozprofile.yCaRZ0CvkzjZ"
```

I'm not sure how exactly that should be done in C#, you will need to consult the docs, but it should be approximately this:

```csharp
driver.Capabilities.GetCapability("profile");
```

**Comment by danwan** [comment]
Thank you very much, that pointed me to the right direction.

Here's the solution:
var dir = ((RemoteWebDriver)driver).Capabilities.GetCapability("moz:profile").ToString();

**Comment by jimevans** [comment]
Or cast to the `IHasCapabilities` interface instead of `RemoteWebDriver`, but yes, that's correct.

**Comment by gabernardone** [comment]
> var profiletmp= driver.Capabilities.GetCapability("moz:profile").ToString(); 

it worked for me, tks (:
