### ISSUE TITLE
Selenium 3.3.6 is showing error while adding option from dropdown

### ISSUE THREAD

**Issue by Aparn12** [SeleniumHQ/selenium#4848]
I am using FF 64.0 and selenium 3.6 .

I got below error at the time of running below code

Code

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class Login {

public static void main(String []args)
{

	System.setProperty("webdriver.gecko.driver", "C:/Java/geckodriver-v0.16.0-win64/geckodriver.exe");
	WebDriver driverobj=new FirefoxDriver();
	driverobj.get("https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html ");

	
	driverobj.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
	
	//new Select(driverobj.findElement(By.xpath("//select[@id='userName']"))).selectByIndex(2);
	
	Select dropdown = new Select(driverobj.findElement(By.id("userName")));
	dropdown.selectByVisibleText("Asmsa1");
}
}

Error

1507628784139	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
1507628784152	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
1507628784163	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
Oct 10, 2017 3:16:24 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1507628784224	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1507628787018	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1507628787019	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1507628790236	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html"
1507628790289	Marionette	DEBUG	Received DOM event "pageshow" for "https://illnqw1409.corp.amdocs.com:28501/idp-simulator/public/index.html"
Oct 10, 2017 3:16:30 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
Exception in thread "main" org.openqa.selenium.WebDriverException: timeouts

Can you plz let us know solutipon. I got solution from one conversation as' WebDriver spec needs to include the /shutdown endpoint' what should I do for this. Because. I am new selenium user.

Note- I reported this issue , as per that this is bug in selenium

**Comment by pbi-qfs** [comment]
```
from future import FF 64.0 ? :)
```

I suspect you're using Firefox 54. Does the error also happen, when you execute your code using the current FF 56 (or beta/nightly) and geckodriver 0.19 ?

**Comment by Aparn12** [comment]
I am using FF 56 only
[FF.docx](https://github.com/SeleniumHQ/selenium/files/1387300/FF.docx)

PFA for the same

**Comment by barancev** [comment]
Geckodriver 0.16 is outdated, latest version is 0.19

**Comment by Aparn12** [comment]
Thanks a lot. Actually I have geckodriver v 0.19. I have provided wrong path in code.Thanks.

**Comment by Aparn12** [comment]
it worked now
