### ISSUE TITLE
 Unable to click on a salesforce tag ::after which is an arrow dropdown 

### ISSUE THREAD

**Issue by vinitsriwastava** [SeleniumHQ/selenium#4849]
Unable to click on a salesforce tag :: after (.support-servicedesk-navigator .x-btn-mc em.x-btn-split:after) using webdriver

![](https://user-images.githubusercontent.com/17021013/31344246-c90f643e-ad2f-11e7-883f-6516621cad0c.png)

Need to click on arrow icon

![](https://user-images.githubusercontent.com/17021013/31344370-21221ef0-ad30-11e7-8cab-73d49e803995.png)

I have tried action and css both but nothing worked:

1. WebElement switchLabel =driver.findElement(By.cssSelector(".x-btn-split::after"));
  ((JavascriptExecutor)driver)
          .executeScript("arguments[0].click();",switchLabel);*/

2. Actions action = new Actions(driver);
action.moveToElement(driver.findElement(By.cssSelector(".x-btn-split::after"))), 20,23).click().build().perform();  
    
3.  WebElement ele = driver.findElement(By.xpath("//*[@id='ext-gen80']"));
  Actions build = new Actions(driver);
  build.moveToElement(ele, 21, 23).click().build().perform();

CSS part of the UI: 

![](https://user-images.githubusercontent.com/17021013/31344706-0cba9644-ad31-11e7-82b8-1fb30e9711bc.png)

Please help.

Thanks,
Sumit

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
