### ISSUE TITLE
Add method to deal with common issues related to clicking

### ISSUE THREAD

**Issue by cezarypiatek** [SeleniumHQ/selenium#4852]
Hi

There is a lot of common issues related to clicking with selenium. I have described some of them (as well as solutions) in my blog post https://cezarypiatek.github.io/post/why-click-with-selenium-so-hard/  
I think it would be helpful and save a lot of troubles if this problem could be solved inside selenium (without need to write additional wrappers for selenium library).  How about adding a method that could perform click action dealing with common problems (it they occur). Something like **ClickWhenItPossible()**

If this is an acceptable approach I am ready to help, but I'm not sure where this method should be implemented (on which level of selenium abstraction). At first glance maybe this should be add to Browser Automation Atoms.

What do you think about this idea?

**Comment by barancev** [comment]
Let's start from adding (failing) tests for these "common issues". Tests first. I'd recommend to add new tests   to the Java suite.
