### ISSUE TITLE
Twice MoveToElement is not working in Selenium C# API

### ISSUE THREAD

**Issue by napriienko** [SeleniumHQ/selenium#4857]
Twice MoveToElement is not working 
OS:  
Windows 8.1
Selenium Version:  
Selenium Webdriver API 3.6.0 for C#
Browser:  
Chrome 61
Chromedriver 2.32 and 2.33

Issue Description:
If I use MoveToElement second time, it is not working. 

Steps to reproduce:

1. Use Actions.MoveToElement(el) first time
It will move the mouse to the specified element
2. Add another Actions.MoveToElement(el1), provide another web element.
In the selenium debug window you will notice it is moving to the previous element "el" that was used in the first MoveToElement.

In my case the first element did not exist anymore and I got StaleElementReferenceException.

The issue is started to happen since Selenium Webdriver API 3.1.0 and up. If I downgrade the nuget package to Webdriver API 3.0.1 I can not reproduce the issue any more.

It is not a chrome driver issue as the same code but written in Java works fine in Webdriver API 3.6.0.

here the code that reproduces the issue:
`	driver = new ChromeDriver();
        wait = new WebDriverWait(driver, TimeSpan.FromSeconds(15));
        driver.Url = "http://www.google.nl/";
	Actions actions = new Actions(driver);
	driver.FindElement(By.Name("q")).SendKeys("webdriver");
	Thread.Sleep(1000);
	actions.MoveToElement(driver.FindElement(By.CssSelector("input[type = button]"))).Perform();
	driver.FindElement(By.CssSelector("input[type = button]")).Click();
	var s = driver.FindElement(By.Id("logocont"));
	actions.MoveToElement(s).Perform();
	s.Click();
        driver.Quit();
        driver = null;

`

**Comment by lmtierney** [comment]
You need to create a new `Actions` object after each `Perform` as it does not clear the stored actions. Java does clear after each `Perform` which is why it works there.

**Comment by lmtierney** [comment]
Duplicate of #4724
