### ISSUE TITLE
Hub / Firefox node fails with Selenium 3.6.0 - WebDriverException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by jwhitlock** [SeleniumHQ/selenium#4859]
## Meta
OS: Dockerized Hub / Node  ([node-firefox](https://hub.docker.com/r/selenium/node-firefox) 3.6.0, [node-chrome](https://hub.docker.com/r/selenium/node-chrome/) 3.6.0, [hub](https://hub.docker.com/r/selenium/hub/) 3.6.0)
Selenium Version: 3.6.0
Browser: Firefox 56.0
Geckodriver Version: 0.19.0

## Expected Behavior
Firefox should run Selenium tests when run as a node in a hub. Chrome runs successfully.

## Actual Behavior
Firefox fails on first test with error:
```
E       WebDriverException: Message: Unable to find a matching set of capabilities
E       Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
E       System info: host: 'b880454af06d', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.8.0_131'
E Driver info: driver.version: unknown
```

Webdriver reports this configuration:

```
request = <SubRequest 'driver' for <Function 'test_title'>>
driver_class = <class 'selenium.webdriver.remote.webdriver.WebDriver'>
driver_kwargs = {'browser_profile': None, 'command_executor': 'http://hub:4444/wd/hub', 'desired_capabilities': {'browserName': 'firefox', 'platform': 'ANY', 'version': ''}}
```

## Steps to reproduce -
https://github.com/mozilla/kuma/pull/4195 is for branch [upgrade_pytest_1308322](https://github.com/mozilla/kuma/tree/upgrade_pytest_1308322), which contains [a script](https://github.com/mozilla/kuma/blob/48dbaf6a9406e94d1dd95af371fb1141be0c6d47/scripts/run_selenium_hub.sh) that runs the Dockerized hub and node. This should work on OSX / Linux with python 2.7.x (``python --version``)

```
git clone https://github.com/mozilla/kuma.git
git checkout upgrade_pytest_1308322
cd kuma
virtualenv venv
source venv/bin/activate
pip install lxml==3.5.0
pip install -r requirements/test.txt
scripts/run_selenium_hub.sh
```

This will start the selenium hub and nodes for Firefox and Chrome. It will run all or most tests successfully against Chrome, and then fail on the first Firefox test.

Here are the [logs from run_selenium_hub.sh](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c), including [logs from the hub](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L315-L347) and [logs from the firefox node](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L349-L379).

Here is the [full console log](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/23/consoleFull) from a test run on Jenkins.

**Comment by barancev** [comment]
Seems to be a geckodriver or browser issue, the driver failed to start the browser:
https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L252-L272

Please re-create this issue on the geckodriver tracker:
https://github.com/mozilla/geckodriver/issues
