### ISSUE TITLE
Chrome driver error ....... Needs to be ADDED to PATH ??

### ISSUE THREAD

**Issue by LoneWolfsMoon** [SeleniumHQ/selenium#4860]
SYSTEM INFO : 

![screenshot from 2017-10-12 20-31-09](https://user-images.githubusercontent.com/30674228/31512776-6afe50c6-af8c-11e7-8087-c1a90f4cb95a.png)

ERROR : 

![screenshot from 2017-10-12 19-03-47](https://user-images.githubusercontent.com/30674228/31512799-77544b82-af8c-11e7-9619-14eac54c77c4.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
