### ISSUE TITLE
Couldn't download 3.5.3 selenium jar

### ISSUE THREAD

**Issue by dankonino** [SeleniumHQ/selenium#4862]
## Meta -
OS:  OSX 
Selenium Version:  3.5.3
Hi guys, I encounter `service unavailable` if I try to access  https://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar 
This is happening in browser, and in terminal `  ./node_modules/.bin/selenium-standalone install` 
there is only couldn't download. Firstly it seemed as internet problem but not anymore since it's not available in the browser as well.
Sincerely dankonino

**Comment by dankonino** [comment]
I think I can close the issue, it's been a problem for a while. But suddenly works after posting it in here :) 👍

**Comment by weiming-myob** [comment]
I started having this issue when installing selenium-server-standalone-3.8.0.jar this afternoon. Can someone help?

`----------
selenium-standalone installation starting
----------

---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/selenium-server/3.8.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip
to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/chromedriver/2.37-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz
to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/geckodriver/0.23.0-x64-geckodriver
/Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/bin/selenium-standalone:111
        throw err;
        ^

Error: Could not download https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
    at Request.<anonymous> (/Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/lib/install.js:373:21)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)`
