### ISSUE TITLE
Could not load type 'OpenQA.Selenium.Support.UI.WebDriverWait' in version 3.6.0 for C#

### ISSUE THREAD

**Issue by medigvijay** [SeleniumHQ/selenium#4864]
## Meta -
OS:  Windows 7

Selenium Version:  3.6.0

Browser:  Chrome

Browser Version:  61.0.3163.100(64 bit)

**Comment by jimevans** [comment]
The WebDriverWait class has been moved into the main WebDriver assembly. To use WebDriverWait, you no longer need the support package. The namespace remained the same, so for the vast majority of users, this change was entirely transparent, since most projects that reference WebDriver.Support also reference WebDriver.

**Comment by sirj77** [comment]
Hi @jimevans .
Sorry for a stupid question, but am I right to have this fixed I can delete 'Selenium.Support' library from my installed packages? Will it solve an issue?

**Comment by jimevans** [comment]
If `WebDriverWait` is the only class you use from the `Selenium.Support.dll` assembly, then yes, you can remove that package. However, there are other classes you may be using (like `ExpectedConditions`) that would require you to retain the reference.

**Comment by tboby** [comment]
Hi @jimevans , I have a 3rd party package that depends on `Selenium.Support.dll`, so I can't remove it. I have `3.8.0` of both `Selenium` and `Selenium.Support`.

How do I resolve this issue? I can't downgrade just Support because then I get conflicting references.

**Comment by aditki** [comment]
@jimevans, What would the new reference to the class be. I have been trying "using OpenQA.Selenium.WebDriver;" and also removing the reference but no success.

**Comment by jimevans** [comment]
@aditki The namespace is still the same as when it was in the support assembly (`OpenQA.Selenium.Support.UI`). This was to facilitate as seamless a transition as possible.

**Comment by tboby** [comment]
@jimevans For what it's worth, tracking down that faulty transitive dependency and chasing the author to update was very difficult. While I can see the benefits of that migration method, I would sincerely ask that an alternative is found if this needs to happen again in future.

I had to run with a custom build of a 3rd party library fora  few months!

**Comment by jimevans** [comment]
@tboby I’m sorry you had to go to the extra effort.
