### ISSUE TITLE
keyDown and keyUp issue clicks when they should not

### ISSUE THREAD

**Issue by kdillon** [SeleniumHQ/selenium#4865]
## Meta -
OS: All
Selenium Version:  All
Browser:  All

keyDown/keyUp requires focus to function, but not a click. A click is a specific way to focus, but focus can also be granted in other ways like tabbing, or from javascript. keyDown/keyUp should not assume that focus has been granted from a click. Focusing via click results in the sending of superfluous events to the element, which can cause incorrect results due to inaccuracy in the events that should be generated for a particular action.

## Expected Behavior -
keyDown/keyUp should focus using the javascript focus API, not clicks.

## Actual Behavior -
keyDown/keyUp triggers a click - a very specific type of focus-granting action that can have side-effects.

## Steps to reproduce -
CTRL+Click on the clickable div in:
https://jsfiddle.net/nyw7w6qf/1/
Note: 1 click detected

Now run...
WebElement webElement = webDriver.findElement(By.cssSelector("#testDiv"));
Actions builder = new Actions(webDriver);
Action modifierkey = builder.keyDown(webElement, Keys.CONTROL).build();
modifierkey.perform();
webElement.click();
modifierkey = builder.keyUp(webElement, Keys.CONTROL).build();
modifierkey.perform();

Note: 3 clicks detected (at least for me). 1 from keyDown, 1 from click, 1 from keyUp

**Comment by p0deje** [comment]
I can reproduce it using Ruby bindings:

```ruby
require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:firefox)
driver.get 'https://jsfiddle.net/nyw7w6qf/1/'

frame = driver.find_element(name: 'result')
driver.switch_to.frame(frame)
div = driver.find_element(id: 'testDiv')

driver.action.key_down(div, :command).click.key_up(div, :command).perform

driver.quit
```

I agree that it seems strange to perform click when doing keyDown/keyUp and I see it's being done in bindings:

```ruby
      def key_down(*args)
        @actions << [:mouse, :click, [args.shift]] if args.first.is_a? Element

        @actions << [:keyboard, :press, args]
        self
      end
```

However, I'm not sure why exactly it works like this. I'll try to figure it out with other committers.

**Comment by p0deje** [comment]
For now, you can work this around using the following actions chain:

```ruby
driver.action.move_to(div).key_down(:command).click.key_up(:command).perform
```

**Comment by binodpanta** [comment]
any updates on this ? As of selenium 3.5.3 this is still an open issue

**Comment by binodpanta** [comment]
the workaround above does seem to work but this issue should still be fixed

 Actions builder = new Actions(containingWindowDriver.getWebDriver());
        Action modifierkey = builder.moveToElement(getWebElement()).keyDown(thiskey.toKeys()).build();
        modifierkey.perform();
        runner.run();
        modifierkey = builder.moveToElement(getWebElement()).keyUp(thiskey.toKeys()).build();
        modifierkey.perform();

**Comment by p0deje** [comment]
I'm still trying to figure out why it's done the way it's done. I hope we can get an answer and decide what to do [this this thread](https://groups.google.com/forum/#!topic/selenium-developers/N--bJgDcXY0).

**Comment by diemol** [comment]
Is this issue still valid?

**Comment by diemol** [comment]
I will close this as seems more folks are not bumping into it or it was fixed.

If needed, we can reopen.
