### ISSUE TITLE
pronlem with html runner

### ISSUE THREAD

**Issue by PhamNgocPhi** [SeleniumHQ/selenium#4882]
i have pronlem like this
System Configuration - Windows 64 bit AWS cloud based – Windows 10 (t2.xlarge)

 
Java Client                                           Java8 131             C:\Program Files (x86)\Java\jre1.8.0_131
Geckodriver.exe                               0.16.1                    C:\Selenium\geckodriver-v0.16.1-win64
Java Selenium Files                          3.4.0                      C:\Selenium\selenium-java-3.4.0
Firefox 64 bit                                      53.03                     C:\Program Files (x86)\Mozilla Firefox
Selenium html runner                    3.4.0                      C:\Selenium\selenium-html-runner-3.4.0
Selenium server standalone        3.4.0                      C:\Selenium\selenium-server-standalone-3.4.0
Selenium IDE Test Suite                                                 C:\Selenium\Selenium IDE Test Cases
Seleniumtext.bat                                                             C:\Selenium\Seleniumtext.bat
System Properties PATH                                                               C:\Selenium\selenium-java-3.4.0\
                                                                                                C:\Program Files (x86)\Mozilla Firefox
                                                                                                C:\Selenium\geckodriver-v0.16.1-win64
Issue
I have a Test Suite created in Selenium IDE. The Test Suite always executes successfully and passes each of the 8 Test Cases when run from Selenium IDE. The Slider control has to be on slow.
 
However, when I attempt to run the selenium html runner all 8 test cases fail. I believe its related to the speed in which the test is executed. I have also noticed that set.Speed() or pause commands written in the test cases appear to be ignored. How can the speed of this test be set with the selenium html runner?  
 
The objective here is to use the Test Suite with Jenkins Continuous Integration.
 
The ‘seleniumtext.bat’ is used to execute the test from the Windows cmd prompt. This contains the following:
java -jar selenium-html-runner-3.4.0.jar -htmlSuite "*firefox" "https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html" "C:\Selenium\Selenium IDE Test Cases\DCP_Test_Suite.html" "C:\Selenium\Test Results\seleniumtestresult.html"
 
Please note – I get exactly the same results when I tried on my local Windows machine.
 
Here is an example of where a Test Case failed picked up from the bottom of the C:\Selenium\Test Results\seleniumtestresult.html
 
|click | //div[@id='body']/div/form/div[4]/div/div/button |  |
|pause | 2000 |  |
|waitForElementPresent | name=volumeIdentifier |  |
com.thoughtworks.selenium.Wait$WaitTimedOutException: Can't wait for ElementPresent
 
The full command line results are shown here:
 
C:\Selenium>seleniumtext.bat
 
C:\Selenium>java -jar selenium-html-runner-3.4.0.jar -htmlSuite "*firefox" "https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html" "C:\Selenium\Selenium IDE Test Cases\DCP_Test_Suite.html" "C:\Selenium\Test Results\seleniumtestresult.html"
Multi-window mode is longer used as an option and will be ignored.
1495695210491   geckodriver     INFO    Listening on 127.0.0.1:34106
1495695211166   geckodriver::marionette INFO    Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1495695211349   addons.manager  ERROR   startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_IJavaScrLLEGALi_pVtA LeUrEr)o"r :  lroecsaotuirocne:: /"/JgSr ef/rmaomdules/Adedo n:M:a nraegseoru.rjcsem:,/ /lgirnee/ m1o6d5u7l:e sN/SF_iElReRUOtRi_lNsO.Tj_sImN I:T:I AFLiIlZeEUDt:i lAsd_dgoentMDainager is not initialized
r :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:671 < startup()@resource://gre/modules/AddonManager.jsm:834 < startup()@resource://gre/modules/AddonManager.jsm:3129 < observe()@resource://gre/components/addonManager.js:65
1495695212672   Marionette      INFO    Listening on port 2093
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
May 25, 2017 6:53:32 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-05-25 06:53:32.844:INFO::main: Logging initialized @2923ms to org.seleniumhq.jetty9.util.log.StdErrLog
2017-05-25 06:53:32.889:INFO:osjs.Server:main: jetty-9.4.z-SNAPSHOT
2017-05-25 06:53:32.910:INFO:osjsh.ContextHandler:main: Started o.s.j.s.h.ContextHandler@f79e{/tests,null,AVAILABLE}
2017-05-25 06:53:32.925:INFO:osjs.AbstractConnector:main: Started ServerConnector@638011{HTTP/1.1,[http/1.1]}{0.0.0.0:45810}
2017-05-25 06:53:32.925:INFO:osjs.Server:main: Started @3004ms
May 25, 2017 6:53:33 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:53:34 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForNotVisible | xpath=(/html/body/div/div[2]/div/div[5]/div/div/div[2]) |  |
May 25, 2017 6:54:04 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:05 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForElementPresent | xpath=(/html/body/div/div[1]/div[3]/nav/div/div/ul/li[1]/a) |  |
May 25, 2017 6:54:05 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:05 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForElementPresent | xpath=(/html/body/div/div[2]/div/form/div[3]/div/div/div[1]/div[1]/div/input) |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | 1234 |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForElementPresent | xpath=(/html/body/div/div[2]/div/form/div[3]/div/div/div[1]/div[2]/div/div/div[1]/span/span[2]) |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(/html/body/div/div[2]/div/form/div[3]/div/div/div[1]/div[2]/div/div/div[1]/span/span[2]) |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForElementPresent | xpath=(/html/body/div/div[2]/div/form/div[3]/div/div/div[1]/div[3]/div/input) |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |selectWindow | null |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=dateInput | 01/05/2017 |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | document.addTransferForm.dateInput[1] | 01/05/2017 |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=salePrice | 900000 |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=interestTransferredAsAPercentage | 32.4 |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | //div[@id='body']/div/form/div[4]/div/div/button |  |
May 25, 2017 6:54:06 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 2000 |  |
May 25, 2017 6:54:08 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |waitForElementPresent | name=volumeIdentifier |  |
May 25, 2017 6:54:39 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:39 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:39 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | ABC Settlements |
May 25, 2017 6:54:40 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:40 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:40 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | 1234 |
May 25, 2017 6:54:41 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:41 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | 1 |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | css=button.btn.btn-default |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[4] |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[2] |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[5] |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=salePrice | 1 |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | //div[@id='body']/div/form/div[4]/div/div/button |  |
May 25, 2017 6:54:42 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:43 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 1000 |  |
May 25, 2017 6:54:44 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:44 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 1000 |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | 1 |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | css=button.btn.btn-default |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[4] |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[2] |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[5] |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=salePrice | 167123 |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | //div[@id='body']/div/form/div[4]/div/div/button |  |
May 25, 2017 6:54:45 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:46 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 1000 |  |
May 25, 2017 6:54:47 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:47 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 1000 |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | AG123 |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | css=button.btn.btn-default |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[4] |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[2] |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[5] |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=salePrice | 88199238 |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | //div[@id='body']/div/form/div[4]/div/div/button |  |
May 25, 2017 6:54:48 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |open | https://lg-dcp-deployment-tst-jenkinsb.s3.amazonaws.com/build/6.0.769_default/ApplicationComponents/DataCapturePortal/index.html |  |
May 25, 2017 6:54:49 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | link=New |  |
May 25, 2017 6:54:49 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |pause | 1000 |  |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=agencyFileReference | 1 |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | css=button.btn.btn-default |  |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[4] |  |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[2] |  |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | xpath=(//button[@type='button'])[5] |  |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |type | name=salePrice | 8850000 |
May 25, 2017 6:54:50 AM org.openqa.selenium.server.htmlrunner.CoreTestCase run
INFO: |click | //div[@id='body']/div/form/div[4]/div/div/button |  |
Review Screen - Amend All & Cancel.html
<a href="Review Screen - Amend All &amp; Cancel.html">Review Screen - Amend All &amp; Cancel</a></td></tr>
</tbody></table>
Represent Proprietor on Title & Cancel.html
<a href="Represent Proprietor on Title &amp; Cancel.html">Represent Proprietor on Title &amp; Cancel</a></td></tr>
<tr class="status_failed"><td>
Add Incoming Proprietor as Company and Cancel.html
<a href="Add Incoming Proprietor as Company and Cancel.html">Add Incoming Proprietor as Company &amp; Cancel</a></td></tr>
<tr class="status_failed"><td>
Add Contract Representative - Cancel.html
<a href="Add Contract Representative - Cancel.html">Add a Representative - Cancel</a></td></tr>
<tr class="status_failed"><td>
Search by Vol & Folio - Successful.html
<a href="Search by Vol &amp; Folio - Successful.html">Search by Vol &amp; Folio - Successful &amp; Cancel</a></td></tr>
<tr class="status_failed"><td>
Add Contract Details - Cancel.html
<a href="Add Contract Details - Cancel.html">Add Contract Details - Cancel </a></td></tr>
<tr class="status_failed"><td>
Search by Vol & Folio - Unsuccessful.html
<a href="Search by Vol &amp; Folio - Unsuccessful.html">Search by Vol &amp; Folio - Unsuccessful &amp; Cancel</a></td></tr>
<tr class="status_failed"><td>
Add Incoming Proprietor.html
<a href="Add Incoming Proprietor.html">Add Incoming Proprietor &amp; Cancel</a></td></tr>
<tr class="status_failed"><td>
2017-05-25 06:54:50.764:INFO:osjs.AbstractConnector:main: Stopped ServerConnector@638011{HTTP/1.1,[http/1.1]}{0.0.0.0:45810}
2017-05-25 06:54:50.765:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@f79e{/tests,null,UNAVAILABLE}
1495695290769   Marionette      INFO    New connections will no longer be accepted
 
i don't know how to fix this

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
