### ISSUE TITLE
Drop-down not working with Safari Driver on Safari 11

### ISSUE THREAD

**Issue by sharma1234** [SeleniumHQ/selenium#4885]
Getting below exception while accessing drop-down. [Site link : https://efqa1.qa-bkstr.com/shop/textbooks-and-course-materials]

**org.openqa.selenium.WebDriverException:** An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 
 
Selenium version: 3.0.1
OS: Mac OS sierra
Browser: Safari
Browser version: 11
SafariDriver

**Drop down element is AJAX based and not a native HTML select/option element set.**

**//DOM**
```<div style="display: none; visibility: visible; padding;" id='programDiv'>
<div class="fieldLabel" id='programLabelDiv' style="padding-bottom: 5px"><label for="programIdSelect">Select Your Program</label></div>
<select id="programIdSelect" name="programId" style="margin-bottom: 13px;">
</select>
</div>
```

**//accessing drop down**

WebElement dropdown =  getDriver().findElement(By.xpath("//select[@id='programIdSelect']"));
Select sel = new Select(dropdown);

**//safari driver & All Capabilities**

DesiredCapabilities safaricapabiCapabilities=new DesiredCapabilities().safari();
try
{
driver=new SafariDriver(safaricapabiCapabilities);
}catch(Exception e1)
{
testStepContinue(false,"createInstance() = "+"Unable to Start on Local");
System.out.println(e1);
}
driver.manage().timeouts().pageLoadTimeout(40, TimeUnit.SECONDS);
driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
driver.manage().window().maximize();  
localThread.set(driver); 
} 

Please help! i am stuck!!

**Comment by barancev** [comment]
1) Selenium 3.0.1 is very out of date. Current version is 3.6.0, please upgrade
2) Safari driver issues should be reported to Apple's bug tracker: https://bugreport.apple.com/
