### ISSUE TITLE
Not possible to set Chrome preferences for media_stream_camera/media_stream_mic. Url is split at each dot.

### ISSUE THREAD

**Issue by sdanailova** [SeleniumHQ/selenium#4886]
OS:  
Windows 10
Selenium Version:  
3.5.3
Chrome driver:
2.32.498550 
Chrome version:
61

Not possible to set Chrome preferences for media_stream_camera/media_stream_mic. The given url is split at each dot. Tried with single and double quote, escape symbol, [], nothing works.

Code:
 ChromeOptions options = new ChromeOptions();
 Map<String, Object> prefs = new HashMap<>();      
 prefs.put(                "profile.content_settings.exceptions.media_stream_camera.'https://app.test.store.com:443,'.setting",
                2);
 options.setExperimentalOption("prefs", prefs);

## Expected Behavior in the Preferences file : 
"media_stream_mic": {
	"https://app.test.store.com:443,*": {						
		"setting": 2
	}
},

## Actual Behavior : 
"media_stream_camera ":{
		" 'https://app":{"test":{"store":{"com:443,*' ":{" setting ":2}}}}
}

**Comment by barancev** [comment]
That's what Selenium passes to chromedriver:
```
{
  "desiredCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [],
      "extensions": [],
      "prefs": {
        "profile.content_settings.exceptions.media_stream_camera.\u0027https://app.test.store.com:443,\u0027.setting": 2
      }
    }
  },
  "requiredCapabilities": {},
  "capabilities": {
    "desiredCapabilities": {
      "browserName": "chrome",
      "goog:chromeOptions": {
        "args": [],
        "extensions": [],
        "prefs": {
          "profile.content_settings.exceptions.media_stream_camera.\u0027https://app.test.store.com:443,\u0027.setting": 2
        }
      }
    },
    "requiredCapabilities": {},
    "alwaysMatch": {
      "goog:chromeOptions": {
        "args": [],
        "extensions": [],
        "prefs": {
          "profile.content_settings.exceptions.media_stream_camera.\u0027https://app.test.store.com:443,\u0027.setting": 2
        }
      }
    },
    "firstMatch": [
      {
        "browserName": "chrome"
      }
    ]
  }
}
```
So it seems to be a chromedriver issue. Please report it to https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lega-land** [comment]
I'll leave it here for those who also looked for the issue:
https://crbug.com/chromedriver/2082
