### ISSUE TITLE
'Unable to create a new session because of no configuration' with Safari and Chrome

### ISSUE THREAD

**Issue by vomaya** [SeleniumHQ/selenium#4887]
## Meta -
OS:  
 macOS Sierra Version 10.12.3 
Selenium Version:  
 3.6.0 Standalone
Browser:  
Chrome & Safari 

Browser Version:  
Chrome: 61.0.3163.100 64 bit, Safari: Version 10.0.3 (12602.4.8) 

## Expected Behavior -

Test session can be started on Chrome and Safari with Selenium 3.6.0

## Actual Behavior -

Upon trying to start any test, Selenium throws an exception when profile chrome or safari is chosen (Firefox starts, but has other unrelated issues)

┌─ @BeforeScenario # DesktopContext::hookBeforeScenario()
      │
      ╳  Could not open connection: Unable to create a new session because of no configuration.
      ╳  Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
      ╳  System info: host: '...', ip: '...', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
      ╳  Driver info: driver.version: unknown (Behat\Mink\Exception\DriverException)

## Steps to reproduce -

This is the configuration in behat.yml:

safari:
  extensions:
    Behat\MinkExtension:
      base_url:  'http://'
      default_session: selenium2
      browser_name: 'safari'
      selenium2:
        capabilities: {"deviceType":"ANY", "browser":"safari", "browserName":"safari", "deviceOrientation":"ANY", "ignoreZoomSetting":false, "platform":"MAC"}

chrome:
  extensions:
    Behat\MinkExtension:
      base_url: 'http://'
      default_session: selenium2
      browser_name: 'chrome'
      selenium2:
        capabilities: {"deviceType":"ANY", "marionette":false, "browserVersion":"61", "browser":"chrome", "name":"Behat feature suite", "browserName":"chrome", "deviceOrientation":"ANY", "ignoreZoomSetting":false, "version":"61", "platform":"MAC"}

**Comment by barancev** [comment]
Please report this issue to Behat tracker.
