### ISSUE TITLE
Text property of IWebElement returns 2 different values in Chrome and Firefox

### ISSUE THREAD

**Issue by algot** [SeleniumHQ/selenium#4888]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.6.0
Browser:  
Firefox, Chrome

Browser Version:  
ChromeDriver 2.33 and GeckoDriver 0.19

## Expected Behavior -
Text property should returns the same values
## Actual Behavior -
Text property returns different values
## Steps to reproduce -
I have following HTML code

```
<label for="corp_type_label" id="Type_label">
<div class="ms-crm-div-NotVisible">Type</div>
--
<div class="ms-crm-Inline-GradientMask"></div>
</label>
```

When I get Text property for label element
```WebDriverManager.Driver.FindElement(By.CssSelector("#Type_label")).Text;  ```
I get following
Chrome:
"--"
Firefox:
"Type\r\n--"

Why different drivers returns different outputs by the same code?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by algot** [comment]
I expected that the same property of the same webelement should return the same value.
But as you can see in Chrome and Firefox I got different values.
I don't know which output could be considered as correct. At first it should be the consistent for testing in different browsers.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
