### ISSUE TITLE
Selenium tests are very-very slow in some networks

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#489]
I am working in hotel on Bali, via public WiFi.
My Selenium tests are incredibly slow (see attached image).
![image](https://cloud.githubusercontent.com/assets/279773/7321190/683b59f4-ead3-11e4-890c-0baec37e5dd5.png)

The problem is in method `org.openqa.selenium.WebDriverException#getSystemInformation`:

``` java
    try{
      host = InetAddress.getLocalHost().getHostName();
    } catch (UnknownHostException throw_away) {}
```

Method `getHostName()` uses system call to get name of current computer, which can be **very-very long**. 
I believe host name is not really needed and can be skipped. Just log IP.

**Comment by asolntsev** [comment]
Created pull request for fixing this problem: https://github.com/SeleniumHQ/selenium/pull/490

**Comment by asolntsev** [comment]
Created another pull request for this issue: https://github.com/SeleniumHQ/selenium/pull/591
This pull request runs resolving IP/host in a separate background thread.

**Comment by barancev** [comment]
Duplicate of #3048
