### ISSUE TITLE
Mac, Chrome - Selenium does not scroll enough vertically if horizontal scrollbars are present

### ISSUE THREAD

**Issue by kdillon** [SeleniumHQ/selenium#4890]
## Meta -
OS: macOS Sierra (10.12.2)
Selenium Version:  ChromeDriver 2.30.477690
Browser:  Chrome, CEF
Browser Version:  Chrome 58.0.3029.96

## Usecase -

I am scrolling down to an element on a page that overflows both vertically AND horizontally.
I am trying to click an element that is offscreen vertically.

## Expected Behavior -
Upon receiving a click() command, Selenium scrolls down to the target element until the target is within the viewport, and then issues a click.

## Actual Behavior -
This appears to be a symptom of some combination of MacOS and newer Chrome, where the scrollbars are hidden in Chrome until the mouse comes near. This makes the viewport larger, but the actual usable area is still the same size as it would be on Windows, because the scrollbars are still there, even if they are invisible.

So when Selenium scrolls into view, it stops (as expected) when the target element enters the viewport. However, it is not interactable because there is an invisible scrollbar over it, which will appear (briefly) when Selenium issues a click on it. The click hits the scrollbar rather than the target element.

What's really bad about this is that it fails silently. Usually if a click is going to hit an element, but hits another element instead, there is a helpful error message. But in this case, the element simply never receives the click, resulting in mysterious failures.

## Steps to reproduce -
Copy this simple test page:
```
<!DOCTYPE HTML>
<html>
    <head>
        <title>Scrolling test for Selenium</title>
 		<script>
	        function been_clicked(clicked_el){
	        	document.getElementById('HUD').innerHTML=clicked_el;
	        }
        </script>
   </head>
    <body style="overflow: visible;">
    	<span id="x" style="position: absolute; left: 10000px;" onclick="been_clicked('X-ONLY')" >X-ONLY</span>
    	<span id="y" style="position: absolute; top: 7000px;" onclick="been_clicked('Y-ONLY')" >Y-ONLY</span>
    	<span id="xy" style="position: absolute; top: 5000px; left: 5000px" onclick="been_clicked('XY')" >X AND Y</span>
    	<span id="origin" style="position: absolute; top: 0px; left: 0px" onclick="been_clicked('ORIGIN')" >ORIGIN</span>

		<span id="HUD" style="position: fixed; top: 10px; left: 200px; background-color: red;">Updates go here</span>
    </body>
</html>
```
And run this code in your preferred boilerplate Selenium test class:

webDriver.findElement(By.cssSelector("#x")).click();
// verify that HUD now says "X-ONLY". This is a check to make sure that this is working.

webDriver.findElement(By.cssSelector("#y")).click();
// verify that HUD now says "Y-ONLY". This fails for me, and if you watch it, you can see the horizontal scrollbar appear briefly as it receives the click. By adding another element lower in the page, and clicking on that, then clicking #y , #y functions normally again.

## Fallout -
This can potentially break tests for any element that needs to be scrolled-to where the center of the element is less than the height (or width) of the scrollbar. While my case has to deal with vertical scrolling and interference with the horizontal scrollbar, I suspect that the same will hold true for horizontal scrolling and vertical scrollbars.

Screenshot:

![scrollbar_interference](https://user-images.githubusercontent.com/2445805/31676250-02deba10-b335-11e7-81fa-bae76758756b.png)

Note, this issue is CC'd at chromium.org ( https://bugs.chromium.org/p/chromedriver/issues/detail?id=2084 )

**Comment by barancev** [comment]
There is no need to keep here a copy of a driver specific issue.

**Comment by olegvs** [comment]
I've seen similar issue on windows with IE driver: so I don't think this is driver specific.
