### ISSUE TITLE
IEDriverServer Issue when working with Multiple Windows (corrected)

### ISSUE THREAD

**Issue by blueray333** [SeleniumHQ/selenium#4893]
First of all, this is my second posting for the same issue. I made a mistake and  I cannot seem to delete/close nor update my original posting.  Apologies for any confusion this might have caused. 

## Meta -
OS:  Windows 7

Selenium Version: 3.6.0  

Browser:  Internet Explorer 11

Browser Version:  11.0.9600.18792 (64-bit) 

## Expected Behavior -
Able to check the title of the 2nd window

## Actual Behavior -
Two observations:
1. putting a Thread.sleep(5000) after clicking the link for the 2nd window shows only 1 window handle
2. with no Thread.sleep, it is able to store two window handles, but when switching to it, Exception of "No Window Found" is encountered

## Steps to reproduce -

Here is my code (made it simple to simulate the issue):

		String IEDriverLocation = "C://Selenium//IEDriverServer.exe";
		File file = new File(IEDriverLocation);
		System.setProperty("webdriver.ie.driver", file.getAbsolutePath());
		DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
		ieCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
		
		ieCapabilities.setCapability("requireWindowFocus", true);
		
		InternetExplorerOptions s = new InternetExplorerOptions(ieCapabilities);
		WebDriver ieDriver = new InternetExplorerDriver(s);
		ieDriver.manage().window().maximize();
		ieDriver.get("http://thehubdev");
                Thread.sleep(30000);
                String parentWindow = ieDriver.getWindowHandle();
		test = ieDriver.findElement(By.xpath("//a[@href='/_layouts/15/user.aspx']"));
		test.click();

		//Thread.sleep(5000);   //enabling this will only show 1 handle as the output below.  without  this shows 2 handles.
		System.out.println("HANDLE SIZE -> " + ieDriver.getWindowHandles().size());
		ieDriver.getWindowHandles();
		ArrayList<String> handles = new ArrayList<String>(ieDriver.getWindowHandles());
		System.out.println("LIST SIZE -> " + handles.size());
		
		for(String child: handles) {
			System.out.println("switching -> " + child);
			ieDriver.switchTo().window(child);  //with no Thread.sleep(5000), handles count 2, but fires an exception for the 2nd handle with exception "No Window found". 
			System.out.println(ieDriver.getTitle()); 
		}

**Comment by jimevans** [comment]
You've specified in your WebDriver code that you want the test to be flaky (`NTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS`). This behavior is consistent with what happens when a Protected Mode boundary is crossed. Please reproduce the issue with IE configured properly, and without this capability.

**Comment by blueray333** [comment]
Thanks jimevans. Unfortunately, our ie security settings is locked and cannot be changed. Is there other options to fix this? Thank you.

**Comment by jimevans** [comment]
The requirement that the browser’s Protected Mode settings be set for the IE driver [are not arbitrary](http://jimevansmusic.blogspot.com/2012/08/youre-doing-it-wrong-protected-mode-and.html). There are solid, technical reasons for requiring that. Unfortunately, if you cannot change the system settings, we cannot rule that out as the cause of the issue.
