### ISSUE TITLE
Unable to click on button placed inside an iframe

### ISSUE THREAD

**Issue by aparna207** [SeleniumHQ/selenium#4895]
## Meta -
OS: OSX macOS Sierra 10.12.6  
Selenium Version:  3.6.0 

Browser:  Safari 

Browser Version:  11.0.1(12604.3.2)

## Steps to reproduce - 

1.  Open safari browser
2.  Access web application login screen
3.  Enter valid credentials and click on Login button, pop up appears
4.  Switch to iframe
5.  Click on button placed inside an iframe

No action when clicked on button. Same code is working fine in other browsers(Chrome, Mozilla, IE11)

Below is the code:

```
SafariOptions options = new SafariOptions();
options.setUseCleanSession(true);
driver = new SafariDriver(options); 
driver.manage().window().maximize();
driver.get("testurl");
driver.findElement(By.id("UN")).sendKeys("admin");
driver.findElement(By.id("UN")).sendKeys("admin$");
driver.findElement(By.id("Login")).click();
driver.switchTo().frame(driver.findElement(By.xpath("//*[starts-with(@class,'dijitDialog') and contains(@style,'z-index: 950;')]//*[starts-with(@id,'AxDojo_Dialog_frame')]")));
driver.findElement(By.xpath("//*[@id='ButtonPlaceHolder']/button[2]")).click();
```

No action when last step is executed.
As work around found an alternate to perform click on the button with below code
`driver.findElement(By.xpath("//*[@id='ButtonPlaceHolder']/button[2]")).sendKeys(Keys.ENTER);`

But like this we need to change in many areas, Selenium is browser independent and maintenance of code browser wise is tedious task to us. Please can anyone look into this issue.

**Comment by barancev** [comment]
Safari driver issues should be reported to Apple's bug tracker: https://bugreport.apple.com/
