### ISSUE TITLE
unknown error: failed to wait for extension background page to load

### ISSUE THREAD

**Issue by cheerayhuang** [SeleniumHQ/selenium#4896]
## Meta -
OS:  
Ubuntu 14.04, kernel 3.19.0

Selenium Version:  

3.6.0

Browser:  
Chromium Browser, Chrome Driver 2.31 and 2.33 (both are tested for this issue)

Browser Version:  

60.0.3112.78 

## Expected Behavior -
Create and return WebDriver normally.

## Actual Behavior -

Throw an exception as bellow:

```
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://dnpjjfhimhgghciignhbkdgllkplgkii/_generated_background_page.html 
from unknown error: page could not be found: chrome-extension://dnpjjfhimhgghciignhbkdgllkplgkii/_generated_background_page.html
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 3.19.0-32-generic x86_64)
```

## Steps to reproduce -

```Python

             chrome_options = webdriver.ChromeOptions()

             chrome_options.add_extension(self.get_chrome_proxy_extension(proxy=self.proxy))

             chrome_options.add_argument('user-agent={0}'.format(user_agent))

             chrome_options.add_argument('headless')

             return webdriver.Chrome(chrome_options = chrome_options)
````

As above, when I load an extension via ChromeOptions and add the "headless" argument, the ChromeDriver will give me an exception.

But if I just add the argument  "headless" into ChromeDriver, everything is OK.  And also just loading an extension via ChromeOptions is OK.

>   this issue is a little like #3508 , but this is not caused by method "getSize()" or "maximize()".

**Comment by barancev** [comment]
1) Latest chromedriver is 2.33 at the moment, try to upgrade.
2) chromedriver issues should be reported to https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by bearnxx** [comment]
did you  solve the problem？

**Comment by hey1937** [comment]
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://kbjodoffbgbkdenmeklfhafmlkalclja/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://kbjodoffbgbkdenmeklfhafmlkalclja/_generated_background_page.html

-------------------------------------------------------
this is my mistake? don,t tell me try to upgrade  chromedriver

**Comment by cgoldberg** [comment]
> this is my mistake?

How would we know?  You hijacked a closed issue and added no information about what you are attempting.  Please submit a new issue and fill out the issue template.
