### ISSUE TITLE
IE Webdriver: Multiple Instances not working / possible

### ISSUE THREAD

**Issue by rgoerner** [SeleniumHQ/selenium#4898]
OS: Windows 10
Selenium 3.6.0, 64bit Webdriver for IE 11

Also, maxInstances=10 and MaxSessions=10 are set, only max 2 concurrent IE seems to be in use.

Is this a normal behaviour, restriction, or did I miss something?
Thank you :)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
