### ISSUE TITLE
iOS/Safari - Hybrid App (via Appium) - Unable to find element within IFrame.

### ISSUE THREAD

**Issue by siggerzz** [SeleniumHQ/selenium#4899]
## Meta -
OS: iOS
Selenium Version: 3.0.1 (Also reproducible on 3.6.0)
Browser: iOS Hybrid App (Safari)
Browser Version:  Not sure - Tested using iOS 11
## Expected Behavior -
I should be able to find elements within an IFrame after executing `driver.SwitchTo().Frame(iFrameElement);`

## Actual Behavior -
When trying to find elements within an IFrame after executing `driver.SwitchTo().Frame(iFrameElement);`, I get NoSuchElementException.
Viewing the page source after switching IFrame still shows the parent document.

## Steps to reproduce -
```
driver.SwitchTo().Frame(iFrameElement);
elementWithinIFrame.click();
```

From what I've seen this is only an issue with Safari. I've had no problems when running the same scenario on Android/Chrome. Sorry I can't provide any code/HTML for you!

Other examples of this issue:
https://github.com/appium/appium/issues/5199
https://github.com/SeleniumHQ/selenium/issues/4397
https://github.com/appium/appium/issues/5560

**Comment by lukeis** [comment]
this is not a selenium bug, rather one for Appium, please log a bug there accordingly.
