### ISSUE TITLE
Command line server for the IE driver has stopped working (upgrading to 3.6 from 3.4)

### ISSUE THREAD

**Issue by abioneperhobby** [SeleniumHQ/selenium#4901]
## Meta -
OS:  
Microsoft Windows 10 Pro 10.0.15063 build 15063
Selenium Version:  
robotframework (3.0.2)
robotframework-ftplibrary (1.4)
robotframework-requests (0.4.7)
robotframework-selenium2library (1.8.0)
robotframework-seleniumlibrary (3.0.0b1)
robotframework-SikuliLibrary (0.1.5)
Browser:  
Ie11
Browser Version:  

![image](https://user-images.githubusercontent.com/2149815/31729062-3f65d03c-b42e-11e7-9634-9c8bf66be216.png)

## Expected Behavior -
Browser should be opened
## Actual Behavior -
Browser crash opening
## Steps to reproduce -

Execute this Test
```

*** Settings ***
Library           	     SeleniumLibrary     15    15

*** Test Cases ***
CrashTest
	Open Browser			https://www.google.com				ie


```

i used the last version of 32 bit driver (http://www.seleniumhq.org/download/) .
![image](https://user-images.githubusercontent.com/2149815/31729418-400913d6-b42f-11e7-85bf-70307485226d.png)

if i use the 3.4 version, it works
![image](https://user-images.githubusercontent.com/2149815/31729446-54fe0f94-b42f-11e7-900d-5e39a2cce816.png)

how i can give some log?
thanks.

**Comment by abioneperhobby** [comment]
@barancev where i can find crash log? i'm using selenium by robotframework, i tried to google about it, but i'm not able to find where logs are.

**Comment by abioneperhobby** [comment]
@barancev on Robot Framework , IE crash only using the
Open Browser         url              ie
keyword.
i can split this operation with
Create Webdriver				Ie
Go To                                               url

it works.

i'm moving the issue on Seleniumlibrary

**Comment by aaltat** [comment]
This actually look like a Selenium or IEDriverServer.exe problem. When I have this code: 
```
from selenium import webdriver


driver = webdriver.Ie()
driver.set_script_timeout(5.0)
driver.get('https://www.google.fi')
driver.quit()
```
And I am using Windows 10 with this IE version: 
![untitled](https://user-images.githubusercontent.com/2665023/31789293-5b1bddde-b51a-11e7-90ba-606a6fce4631.png). 
And I have Selenium 3.6.0 installed.

Then if have IEDriverServer.exe (32bit) 3.4.0 in the %PATH% then the above code works fine. But if I have IEDriverServer.exe (32bit) 3.5.0 or 3.6.0 in the %PATH% then I see this exception: 
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    driver.set_script_timeout(5.0)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 796, in set_script_timeout
    'script': int(float(time_to_wait) * 1000)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 306, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 526, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host
````

If I remove the line `driver.set_script_timeout(5.0)` then the above code works also fine with IEDriverServer.exe (32bit) 3.5.0 or 3.6.0. 

Could the issue be reopened and investigated?

**Comment by aaltat** [comment]
Could the issue be reopened and investigated because the problem seems to be at the IEDriverServer.exe side.

**Comment by Aliya-I** [comment]
I have the same problem with IEDriverServer.exe (32bit versoin 3.7.0)

**Comment by pavoltravnik** [comment]
I am dealing with "Command line server for the IE driver has stopped working" error on Microsoft Azure even on freshly installed instance. Any version of IEDriverServer.exe doesn't work.

**Comment by iPiyushPatel** [comment]
I'm still facing this issue. 32 bit IE driver doesn't work with 64 bit version on Windows 10 or Azure machine & Selenium C#.  Can anyone help ?

**Comment by cliffbdf** [comment]
I have the same problem. Driver is most recent: IEDriverServer_Win32_3.11.1. I am using Windows 7 Enterprise (Version 6.1, Service Pack 1).

**Comment by jimevans** [comment]
To anyone saying, "I am having this problem too," there can be any number of things that can cause this issue ("Command line serverfor the IE driver has stopped working"). The root cause for the initial report has, in fact, been fixed. If you're receiving this error now, you'll need to file a new issue, and (**_and this is absolutely critical_**) you must include code that reproduces the issue. This particular issue will not be reopened.
