### ISSUE TITLE
Failed: java.io.FileNotFoundException exception on running protractor test on safari

### ISSUE THREAD

**Issue by no5419595** [SeleniumHQ/selenium#4904]
## Meta -
OS:  
OS X Sierra
Selenium Version:  
selenium standalone: 3.6.0
Browser:  
Safari 10

## Expected Behavior -
There should be no error on this

## Actual Behavior -
I get an error like the following when running my protractor test on safari. It only happens with safari but the problems seems to be from selenium if I look at the stack trace.

[safari #51] Failed: java.io.FileNotFoundException: http://localhost:29917/session/658663C8-1A53-44CE-804E-F6A17E4675AB/element/node-CA121C93-F696-41AA-903C-270872F8F920/displayed
[safari #51] Stack:
[safari #51] WebDriverError: java.io.FileNotFoundException: http://localhost:29917/session/658663C8-1A53-44CE-804E-F6A17E4675AB/element/node-CA121C93-F696-41AA-903C-270872F8F920/displayed
[safari #51] at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
[safari #51] at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
[safari #51] at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
[safari #51] at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
[safari #51] at process.tickCallback (internal/process/next_tick.js:109:7)
[safari #51] From: Task: WebElement.isDisplayed()
[safari #51] at WebDriver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
[safari #51] at WebElement.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
[safari #51] at WebElement.isDisplayed (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:2270:17)
[safari #51] at actionFn (/usr/local/lib/node_modules/protractor/lib/element.ts:94:34)
[safari #51] at Array.map (native)
[safari #51] at actionResults.getWebElements.then (/usr/local/lib/node_modules/protractor/lib/element.ts:484:67)
[safari #51] at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
[safari #51] at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
[safari #51] at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
[safari #51] at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)Error
[safari #51] at ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/lib/element.ts:482:23)
[safari #51] at ElementArrayFinder.(anonymous function) [as isDisplayed] (/usr/local/lib/node_modules/protractor/lib/element.ts:96:21)
[safari #51] at ElementFinder.(anonymous function) [as isDisplayed] (/usr/local/lib/node_modules/protractor/lib/element.ts:873:14)
....

## Steps to reproduce -

This is the problematic piece of code giving me that problem. It seems to happen every time there is a promise.then operation. My protractor test script is written in typescript 

banner.button1.isDisplayed().then(function(result) {
          if ( result ) {
            banner.button1.click();
          }
      });

Is there a way to workaround this or resolve this problem?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by no5419595** [comment]
Hello,

This is what my testcase is doing, I get the error on the last section where I try to click on the button.

browser.get(browser.baseUrl);

var EC = protractor.ExpectedConditions;
        browser.wait(EC.presenceOf(elem), 10000).then(function() {            
            if (EC.presenceOf(elem)) {
            } else {            
                throw new Error("Element " + elem +" not displayed");
            }
        });

banner.button1.isDisplayed().then(function(result) {
          if ( result ) {
            banner.button1.click();
          }
      });

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
