### ISSUE TITLE
Setting implicit wait causes IEDriverServer 3.6.0.0 to crash

### ISSUE THREAD

**Issue by troyhoffman** [SeleniumHQ/selenium#4905]
## Meta -
OS:  
Windows 7 x64
Selenium Version:  
3.6.0
Browser:  
Internet Explorer 
Python:
3.6.1 (64-bit)

Browser Version:  
11.0.9600.18697 (32-bit or 64-bit)

## Expected Behavior -
I should be able to set the implicit wait without a crash

## Actual Behavior -
As soon as I call webdriver.implicitly_wait, I get an error message "Command line server for the IE driver has stopped working"

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	IEDriverServer32_3600.exe
  Application Version:	3.6.0.0
  Application Timestamp:	59c567f7
  Fault Module Name:	IEDriverServer32_3600.exe
  Fault Module Version:	3.6.0.0
  Fault Module Timestamp:	59c567f7
  Exception Code:	40000015
  Exception Offset:	000158d1
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	b69b
  Additional Information 2:	b69b522641cca62102b1b8971c85daba
  Additional Information 3:	6ecc
  Additional Information 4:	6ecc49e2304d946bff2361b5b17ee636

NOTE: I've seen several other issues logged with this same type of crash, but none of them include code to reproduce it. Most have been closed as not reproducible, but there is at least one recent one still open. Since I can't tell if it's failing for the same reason, I entered a new issue. If this is a duplicate, I can merge my information into another issue as a comment.

## Steps to reproduce -
Run the following code, changing the value for the server variable to the location of the IEDriverServer executable on your system. The line that triggers it is my_webdriver.implicitly_wait(60). 

Using the 64-bit version of the driver still reproduces the problem with the same Exception Code. Using version 3.0.0.0 (32 or 64 bit) does not reproduce the problem. 

```
from selenium import webdriver

server = "c:\\temp\\iedriver\\IEDriverServer32_3600.exe"
my_webdriver = webdriver.Ie(executable_path=server)
my_webdriver.implicitly_wait(60)
my_webdriver.close()
```

**Comment by twiggy** [comment]
same here. I'm running through standalone server from linux to a windows box as well. 

I turned IE log to Trace and got this, hope it helps.

D 2017-10-20 16:41:34:315 command.cc(36) Raw JSON command: { "name" : "setTimeouts", "locator" : { "sessionid" : "b21fbe61-5bfc-40f7-8fe2-d51cc1f40ec2" }, "parameters" : {"sessionId": "b21fbe61-5bfc-40f7-8fe2-d51cc1f40ec2", "implicit": 60000} }
T 2017-10-20 16:41:34:315 IECommandExecutor.cpp(133) Entering IECommandExecutor::OnExecCommand
T 2017-10-20 16:41:34:315 IECommandExecutor.cpp(454) Entering IECommandExecutor::DispatchCommand
T 2017-10-20 16:41:34:315 IECommandExecutor.cpp(577) Entering IECommandExecutor::GetCurrentBrowser
T 2017-10-20 16:41:34:315 IECommandExecutor.cpp(583) Entering IECommandExecutor::GetManagedBrowser
T 2017-10-20 16:41:34:315 IECommandExecutor.cpp(529) Entering IECommandExecutor::IsAlertActive
T 2017-10-20 16:41:34:315 Browser.cpp(700) Entering Browser::GetActiveDialogWindowHandle
T 2017-10-20 16:41:34:315 Browser.cpp(206) Entering Browser::GetContentWindowHandle
D 2017-10-20 16:41:34:315 IECommandExecutor.cpp(543) No alert handle is found

**Comment by p0deje** [comment]
I cannot reproduce. Also, there is nothing suspicious in logs.

> Using the 64-bit version of the driver still reproduces the problem with the same Exception Code. 

Have you tried 32-bit version of the driver?

> Most have been closed as not reproducible, but there is at least one recent one still open.

Which one is that?

**Comment by rab2215** [comment]
I am experiencing the an error when setting an implicit wait as well, only I'm getting a different error.

`org.openqa.selenium.WebDriverException: Invalid timeout type specified: ms
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'SEL-GRID-W7-10', ip: '10.3.200.81', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: unknown
Command duration or timeout: 134 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'lindsays-iphone.isirona.local', ip: '10.1.64.119', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0, ie.ensureCleanSession=false, elementScrollBehavior=0, enablePersistentHover=true, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:46819/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: 06db64e7-9206-48be-9e7c-6e8033ef3aca
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)`

**Comment by quldude** [comment]
I tried both 32-bit and 64-bit versions (3.6.0) and seeing the same issue...
Message: System.NotImplementedException : Command not found: POST /session/timeouts

**Comment by lmtierney** [comment]
@quldude and @troyhoffman can you try with the new `3.7.0.0` version? Some stuff around timeouts got fixed there

**Comment by quldude** [comment]
After updating webdriver to v3.7 (from 3.0.1) and IE 32-bit v3.6, I got it to work.

**Comment by p0deje** [comment]
Guess we can close as fixed.
