### ISSUE TITLE
Racing condition between Selenium Server and ChromeDriver

### ISSUE THREAD

**Issue by SzabKel** [SeleniumHQ/selenium#4909]
## Meta -
OS:  
Windows 7  Pro x32 SP1 Virtual Machine (running on vmware ESXi 6.0.0)
Selenium Version:  
[selenium-java 3.4.0], [selenium-server 3.6.0], [ChromeDriver 2.33]  (and a few versions before this one too, I updated the server and the browser a few times during the past months)
Browser:  
Chrome v61 32bit

## Main issue -
ChromeDriver won't delete it's scoped_dir<****>_<*****> folders from Windows's Temporary files.

## Expected Behavior -
If the browser gets closed remotely by calling `driver.quit();`, either ChromeDriver itself or Selenium Server should remove the temporary files (or at least selenium-server should not hold the files).

## Actual Behavior -
[It was supposed to be fixed a few times already.](https://stackoverflow.com/questions/43289035/chromedriver-not-deleting-scoped-dir-in-temp-folder-after-test-is-complete), but I am still struggling with this on a Windows 7 virtual machine. The directories just keep piling up (each around 5MB) and after a day or two it slows down the system. I saw this issue mentioned with Firefox's driver too.

As much as I can see, sometimes when a browser closes a scoped_dir folder gets deleted, but most of the time it won't. I tried to use a ps1 script to manually delete the files ([source](https://paste.ubuntu.com/25766373/), mentioned [here](https://sqa.stackexchange.com/questions/26675/chromedriver-not-deleting-scoped-dir-in-temp-folder-after-test-is-complete/27070)), but It just cannot delete them until I shutdown `selenium-server`. For me, It looks like Chrome and selenium-server keep each other from deleting the files.

Please tell me, what information should I share to help this issue resolved.

Until then:
- I am using Java 1.8 to connect to the server
- I start the selenium server by simply calling `java -jar selenium-server.jar` in command line
- My test cases require lot's of browser starting and stopping, but I close them every time with a `driver.quit()` in a `try-catch-finally` structure.
- My software runs in a multi-threaded environment, meaning multiple threads will request browsers at the same time
- I tried using `driver.close()` before calling `driver.quit()`, but it just crashed with an already closed driver exception.

## Steps to reproduce -
Keep starting and closing browsers, when the selenium-server runs on Windows 7 machine and look for the directories in `C:\Users\<User>\AppData\Local\Temp`

**Comment by SzabKel** [comment]
I made a fresh Windows 7 install (64bit), installed Chrome v62, ChromeDriver 2.33 on JDK 8u151 (64bit). I used [this project](https://github.com/SzabKel/scopeddirtest) to start and stop browsers, but could not reproduce the issue. The scoped_dir folders are deleted without a problem. I guess there is another thing I am missing or It is due to the different system architecture (x86 v x64).

**Comment by barancev** [comment]
May I close the issue then?

**Comment by SzabKel** [comment]
@barancev I still don't know what caused the issue, but using the newest version on a fresh Windows 7 x64 installation works fine. It would take too much effort to investigate further, if no one else experience the issue, you should close it.
