### ISSUE TITLE
Jenkins as service. FF as background. Selenium throws ElementNotVisibleException

### ISSUE THREAD

**Issue by balamv** [SeleniumHQ/selenium#491]
Hi,
we are firing selenium API[2.0] tests using Jenkins which runs as a service. FF is running in the background. we are coming across this abnormal issue. Not sure whether due to FF which runs in the background which updated the dom and driver not able to find the element.

Issue A: 
1. web driver finds the web element input text 
2. web driver clears the existing text.
3. web driver adds new text in the input field

After 2nd step, am getting the below error. Though it finds the same element in 1st step and cleared, it can not able to input new text in the 3rd step.

Issue B: 

1. web driver finds the web element input text  textField
2. web driver clears the existing text in textField.
3. web driver adds new text in the textField
4. web driver needs to find the next web element which is a button named buttonField. It fails with the same above error. 

For trouble shooting, I tried to find the buttonField before 2 nd step and it was available. What is causing this issue?  Is this due to FF runs in the background ? The same testcases works when I execute from eclipse and FF as foreground.

org.openqa.selenium.ElementNotVisibleException: Element is not currently visible and so may not be interacted with
Command duration or timeout: 63 milliseconds
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'swissbox', ip: '171.61.02.32', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.6.0_05'
Session ID: 3727f8b0-ec8b-47a8-a13f-d7487b287716
Driver info: org.openqa.selenium.firefox.FirefoxDriver

**Comment by balamv** [comment]
Any solution for this issue?

**Comment by barancev** [comment]
Running a browser under a system account without access to an interactive session is explicitly not supported.
