### ISSUE TITLE
The requested URL could not be retrieved

### ISSUE THREAD

**Issue by jqs1124** [SeleniumHQ/selenium#4910]
Ie sets the proxy and reports the following exceptions：
The following error was encountered while trying to retrieve the URL: http://127.0.0.1:56739/session

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jqs1124** [comment]
str_proxy = '222.189.117.118:3321'
    http_proxy = Proxy()
    http_proxy.proxy_type = {'ff_value': 1, 'string': 'manual'}
    http_proxy.httpProxy = str_proxy
    http_proxy.socksProxy = str_proxy
    http_proxy.ftpProxy = str_proxy
    desired_capabilities = DesiredCapabilities.INTERNETEXPLORER.copy()
    http_proxy.add_to_capabilities(desired_capabilities)
    browser = webdriver.Ie(IE_DRIVER_PATH, capabilities=desired_capabilities)
  
  logs:
[selenium.webdriver.remote.remote_connection] DEBUG: POST http://127.0.0.1:59515/session {"capabilities": {"alwaysMatch": {"browserName": "internet explorer", "platformName": "windows", "proxy": {"proxyType": "manual", "socksProxy": "222.189.117.118:3321", "ftpProxy": "222.189.117.118:3321", "httpProxy": "222.189.117.118:3321"}}, "firstMatch": [{}]}, "desiredCapabilities": {"platform": "WINDOWS", "browserName": "internet explorer", "version": "", "proxy": {"proxyType": "manual", "httpProxy": "222.189.117.118:3321", "ftpProxy": "222.189.117.118:3321", "socksProxy": "222.189.117.118:3321"}}}

exception:
urlopen error [errno 10061]

**Comment by diemol** [comment]
Is this issue still valid? If so, please provide a more complete script to reproduce it. In the one above there is an IP used for a proxy which we don't know how it is configured. Again, please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information.
