### ISSUE TITLE
Add capability to install an addon from a base64 string

### ISSUE THREAD

**Issue by jrbenny35** [SeleniumHQ/selenium#4914]
As of geckodriver v0.19 you can now pass an addon as a base64 string to be installed. 

See the bug reference here: https://bugzilla.mozilla.org/show_bug.cgi?id=1383931

**Comment by jrbenny35** [comment]
I am working on a solution for this and will open a PR.

**Comment by barancev** [comment]
See also #4215, not all bindings have implemented addon installation yet.

**Comment by AutomatedTester** [comment]
This has been added as far as I can see
