### ISSUE TITLE
chooseOkOnNextConfirmation can not handle confirm dialog on onload stage

### ISSUE THREAD

**Issue by jonnyaih** [SeleniumHQ/selenium#4915]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.1, IDE 2.9.1
Browser:  
Firefox
Browser Version:  
31.0esr

## Expected Behavior -
On loaded page should be displayed True
## Actual Behavior -
On loaded page displayed False
## Steps to reproduce -
- unzip [page.zip](https://github.com/SeleniumHQ/selenium/files/1400924/page.zip)
- IDE: chooseOkOnNextConfirmation
- IDE: open page.html
- Check a text on the page

**Comment by barancev** [comment]
Selenium IDE is deprecated, no issues will be fixed. But, of course, you can submit a pull request.
