### ISSUE TITLE
Keys.chord does not work with Chromedriver

### ISSUE THREAD

**Issue by JFischer84** [SeleniumHQ/selenium#4916]
Hi, I am not sure if this belongs here, or if it would fit better on Chromedrivers own Site. If it does not belong here, please let me know. I am new to reporting Issues on Github, so If anything is wrong or there is something missing, please let me know that too. 

## Meta 
OS:  OSX
Selenium Version:  3.6.0, IntelliJ 2017.2.5
Browser:  Chrome
Browser Version: 62.0.3202.62 (64bit)
Chromedriver Version: 2.33

## Expected Behavior 
Key.chord should mark, copy and paste Text in an input-field with Keys.chord(Keys.COMMAND, "a") etc. 
I tried it with webelement.sendKeys(Keys.chord(Keys.COMMAND, "a")), and with 
Actions actions = new Actions(driver);
actions.sendKeys(selectedElement, Keys.chord(Keys.COMMAND, "a"));
## Actual Behavior 
it does nothing, no error in log
## Steps to reproduce 
System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver_2_33");
Webdriver driver = new ChromeDriver();
driver.get("https://www.google.de");
WebElement searchbar = driver.findElement(By.className("gsfi"));
searchbar.click();
searchbar.sendKeys("abcdef");
searchbar.sendKeys(Keys.chord(Keys.COMMAND, "a"));

**Comment by p0deje** [comment]
I don't think ChromeDriver is capable of simulating OS-level key inputs. In any event, Selenium is responsible only for sending the command to ChromeDriver, so please post ChromeDriver-specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by tubisoft** [comment]
thank you thats great 

https://www.tubiseo.com
