### ISSUE TITLE
Unable to use Html Unit Driver to click on anchor on web-page.

### ISSUE THREAD

**Issue by OllieReynolds** [SeleniumHQ/selenium#4918]
I am developing a Groovy application, using selenium-webdriver-driver-2.52. I also have the following libraries at use: httpclient 4.5.1 and htmlunit 2.18. 

There is an element on the webpage:
`<a class="btn btn-lg btn-success" href="#" role="button" type="button" ng-click="login()">Login</a>`

` WebClient webClient = new WebClient()
        webClient.setJavaScriptEnabled(true)
        webClient.setThrowExceptionOnFailingStatusCode(false)
        webClient.setThrowExceptionOnScriptError(false)

        HtmlPage currentPage

            currentPage = (HtmlPage) webClient.getPage(<URL>);
            List<HtmlAnchor> anchors = currentPage.getAnchors()
            HtmlAnchor anchor = anchors[0]
            HtmlPage newPage = anchor.click()

`

The web client is able to locate the anchor, using getAnchors on the current page. However, when I invoke the click button on the anchor, the returned Page is the same as the one I am currently on. The expected behavior however, is that clicking on the button would take me to the next page.

Also, one observation is that the HREF is a hashtag, but when I hover over this in a browser, I can see the actual URL I am after. 

Also, the web frontend I am navigating to using selenium makes use of AngularJS - not sure if this could be affecting anything.

**Comment by barancev** [comment]
Please report this issue to HtmlUnit project,
