### ISSUE TITLE
FileUtils.copyFile throws a FileUtils cannot be resolved error with Selenium WebDriver Java 3.6.0

### ISSUE THREAD

**Issue by fdeamicis** [SeleniumHQ/selenium#4919]
I just installed Selenium WebDriver Java version 3.6.0.  When I did that, FileUtils.copyFile throws a FileUtils cannot be resolved error.  (Check the attachment for illustration). I'm going to revert back to Selenium WebDriver Java version 3.5.3 because it doesn't have the error

![futil](https://user-images.githubusercontent.com/4235950/31823731-0d7fb2f6-b57b-11e7-8d1d-66d5b64e2d45.jpg)

**Comment by barancev** [comment]
It's FileHandler.copy(File, File) now.

**Comment by ShivKumarKoyalkar** [comment]
Thanks @barancev. Saved my day!

**Comment by Bheemshankar** [comment]
Thanks
