### ISSUE TITLE
C# AddAdditionalCapability call on DriverOptions not working correctly

### ISSUE THREAD

**Issue by jsiegmund** [SeleniumHQ/selenium#4925]
## Meta -
OS:  
Windows Server 2012
Selenium Version:  
3.6.0
Browser:  
Internet Explorer

Browser Version:  
N/A, most recent version of internet explorer driver.

This is concerning the C# libraries.  

## Expected Behavior -
When setting additional capabilities via the AddAdditionalCapability method on the DriverOptions, I would expect those capabilities to be passed on to any RemoteWebDriver session. 

## Actual Behavior -
The capabilities are not passed. Instead, when I view the internals of the InternetExplorerDriverOptions object, the capabilities have been added to the **additionalInternetExplorerOptions** collection instead of **additionalCapabilities**. I now have fabricated some reflection code which adds the capabilities to the right collection, after which the passing also works.

## Steps to reproduce -
Create a new InternetExplorerDriverOptions object (I'm betting this works for the other driver types as well) and add any capability using the AddAdditionalCapability method. Inspect the private properties and notice they have been added to the wrong collection.

**Comment by jimevans** [comment]
There is an overload to `AddAdditionalCapability` that will add to the top level capabilities. It takes a third `bool` argument. Set this to `true` to add to the top-level capabilities. If this does not meet your needs, you’ll need to provide an actual code snippet that describes what you’re attempting to do.

**Comment by barancev** [comment]
Closing the issue, no reproduction scenario provided. Let's hope the advice in the previous comment resolved the issue.

**Comment by bicarbon8** [comment]
is this really the recommended approach here? the _InternetExplorerDriverOptions_ (now renamed to _InternetExplorerOptions_) implements this overload, but the underlying _DriverOptions_ object does not so it means one cannot write generic code for such instances and instead must cast and check against each implementation of _DriverOptions_ 🤕
