### ISSUE TITLE
Selenium 3.6.0 WebDriverException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by TarunTater** [SeleniumHQ/selenium#4927]
## Meta -
OS:  Mac OS Sierra - 10.12.1
Selenium Version:  3.6.0
Browser:  Firefox
Browser Version: 52.4.1 (64-bit)
geckodriver: v0.19.0

When I try a simple code to open a browser in `python` and hit a page in this : 
`driver = webdriver.Firefox(executable_path="/Users/tarun/mozDriver")`
I get this error : 
`WebDriverException: Message: Unable to find a matching set of capabilities`

Other suggested posts suggest that I should update browser, selenium etc, but I have already updated them and still get the error. I don't get this error on chrome

**Comment by javaversion** [comment]
Did you try with v56 of Firefox? The same exception was thrown (Selenium Version: 3.6.0 + geckodriver: v0.19.0) in my project and this version solved it.

**Comment by TarunTater** [comment]
@javaversion - ya, that worked. Thanks

**Comment by LakshmanMusulla** [comment]
Hey Guys, i am using below code  and i am seeing 
Message: Unable to find a matching set of capabilities

from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
binary = FirefoxBinary("C:\\Program Files (x86)\\Mozilla Firefox\firefox.exe")
driver = webdriver.Firefox(executable_path="geckopath",firefox_binary=binary)

**Comment by hmchaitra** [comment]
Hey,
I am also facing the same issue..can anyone help out..
for what version of firefox what version of geckodriver is required, i mean how can we get the version compatibility.????

**Comment by badari412** [comment]
@hmchaitra, you can get that info from geckodriver releases page: https://github.com/mozilla/geckodriver/releases

Check the release notes of your geckodriver to know the corresponding version of Firefox.

**Comment by hmchaitra** [comment]
Thank you..

**Comment by javaversion** [comment]
Hi @hmchaitra , 

Selenium v3.6.0 (Java) Release explicitly didn't mention any dependency explicitly.

The last dependency explicitly mentioned by Selenium was for v3.4.0 which is as follows :

Geckodriver 0.16 is strongly recommended

GeckoDriver Release Perspective :

    GeckoDriver v0.19.0: Firefox 55.0 (and greater) & Selenium 3.5 (and greater)
    GeckoDriver v0.18.0: Firefox 53.0 (and greater)
    GeckoDriver v0.16.0: Selenium 3.4 (and greater)

Mozilla Firefox Versions :

Ideally, each Selenium release should support each version of Mozilla Firefox releases (starting with Firefox 48.x) where the property "marionette" needs to be set to true.

If you are working with the legacy Firefox releases (till Firefox 47.x) GeckoDriver still works but you have to explicitly set the property "marionette" to false.

Kind regards.

**Comment by patelketul** [comment]
I getting same error, too. I am running selenium server 3.6.0 on macOS Sierra using python and I am registering a WINDOWS node and trying to open firefox 59.0.
