### ISSUE TITLE
Safari - Capture Page Screenshot

### ISSUE THREAD

**Issue by ebortolin** [SeleniumHQ/selenium#4928]
## Meta
OS: 
![image](https://user-images.githubusercontent.com/22818613/31877302-4227a63c-b7d6-11e7-8d96-d0037faf7d62.png)
Selenium Version:  3.6.0
Browser:  Safari
Browser Version: 11.0.1 (13604.3.1)
Safari Driver: [SafariDriver.safariextz](https://selenium-release.storage.googleapis.com/2.48/SafariDriver.safariextz) v. 2.48

## Expected Behavior
Take a screenshot of current page of browser with the command `Capture Page Screenshot`. Created file should should contain an image with all and only i can see in the page.
![responsive no crop](https://user-images.githubusercontent.com/22818613/31878078-159f013e-b7d9-11e7-8217-25b3f253c6d0.png)
## Actual Behavior
Image generated by `Capture Page Screenshot` adds a border on the right side. Inspecting html page, it doesn't seem to be a dom element.
![responsive no crop](https://user-images.githubusercontent.com/22818613/31878086-1dddb854-b7d9-11e7-96c0-a2c71cf44b78.png)
I had same problem with Chrome in Windows using webdriver 3.4.0, but it was solved in version 3.6.0.
## Steps to reproduce
```
Create Webdriver			Safari
Go To					https://url_page/
Capture Page Screenshot			img/test.png
```
I can't insert a test case because the problem manifests only with some web sites.
These are libraries i've installed:
- robotframework (3.0.2)
- robotframework-requests (0.4.7)
- robotframework-selenium2library (3.0.0b1)
- robotframework-seleniumlibrary (3.0.0b3)
- robotframework-SikuliLibrary (DEV)
- selenium (3.6.0)

**Comment by barancev** [comment]
Safari driver issues should be reported to https://bugreport.apple.com/

**Comment by burg** [comment]
You appear to be using the legacy Safaridriver extension, which is unsupported and unmaintained. Please use the Apple-provided safaridriver included with Safari 10 and later.
