### ISSUE TITLE
NoClassDefFoundError: SessionNotFoundException with selenium 3.6 and HtmlUnitDriver 2.52.0

### ISSUE THREAD

**Issue by Ben1980** [SeleniumHQ/selenium#4930]
## Meta -
OS:  Windwos 10
Selenium Version:  3.6.0
Browser:  HtmlUnitDriver

Browser Version:  HtmlUnitDriver 2.52.0

## Expected Behavior -
This package configuration should compile and work:
org.seleniumhq.selenium:selenium-api:3.6.0
org.seleniumhq.selenium:selenium-java:3.6.0
org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0

## Actual Behavior -
Is causing a NoClassDefFoundError
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException

## Steps to reproduce -
Just get sources from [Example](https://github.com/Ben1980/seleniumError.git) and run it with gradlew.bat build or in your IDE

**Comment by barancev** [comment]
Latest htmlunit-driver is 2.27 (note the artifact name change), version number matches htmlunit version.
http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Chtmlunit-driver%7C2.27%7Cjar
