### ISSUE TITLE
IEDriver 3.6.0 : throw the exception on the line of driver.Manage().Window.Size

### ISSUE THREAD

**Issue by toraylin** [SeleniumHQ/selenium#4933]
OS: Windows 7
Selenium Version:
Selenium.WebDriver 3.6.0
Selenium.WebDriver.IEDriver 3.6.0
IE Version: 11.0.9600.18792

I upgrade the latest Selenium Web driver and IE driver. However, in C#, the following code throws the exception on this line **driver.Manage().Window.Size;**

 **Size driverSize = new Size();
 driverSize = driver.Manage().Window.Size;
 int width = driverSize.Width;**

The error message is : 
An exception of type 'OpenQA.Selenium.NoSuchWindowException' occurred in WebDriver.dll but was not handled in user code
Additional information: Error retrieving window

Any idea?

Thanks,
Ray

**Comment by barancev** [comment]
If this issue is still actual please provide a reproduction scenario and we'll reopen it.
