### ISSUE TITLE
Cant read input field with selenium 3.6 and htmlunitdriver 2.27

### ISSUE THREAD

**Issue by Ben1980** [SeleniumHQ/selenium#4935]
## Meta -
OS:  Windows 10
Selenium Version:  3.6.0
Browser:  HtmlUnitDriver

Browser Version:  HtmlUnitDriver 2.27

## Expected Behavior -
Should be able to fill input field and read its content.

## Actual Behavior -
With artifacts:
org.seleniumhq.selenium:selenium-api:3.6.0
org.seleniumhq.selenium:selenium-java:3.6.0
org.seleniumhq.selenium:htmlunit-driver:2.27
Causing NoSuchMethodError: com.gargoylesoftware.htmlunit.html.Keyboard and getAttribute("value") returns empty string.

With artifacts:
org.seleniumhq.selenium:selenium-api:2.53.1
org.seleniumhq.selenium:selenium-java:2.53.1
Everthing is fine.

## Steps to reproduce -
Just get sources from [Example ](https://github.com/Ben1980/seleniumError.git) and run it with gradlew.bat build or in your IDE

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/htmlunit-driver #60](https://github.com/SeleniumHQ/htmlunit-driver/issues/60) via [**ZenHub**](https://www.zenhub.com/)
