### ISSUE TITLE
window.open returns null when invoked via Selenium

### ISSUE THREAD

**Issue by lalitrnagpal** [SeleniumHQ/selenium#4936]
OS: Windows 7 Enterprise
Selenium Version:  2.53.1
Browser:  Internet Explorer 11

The following code inside a function runs on clicking a button. When invoked via Selenium, it fails - the window handle returned is null. This runs fine when invoked with a manual  @click.

```
		// open a new window and set it as the target of the form submission
		win = window.open("/BlankWithIndicator.jsp", "dynamicSortWindowName", "width=450,height=325,left=575,top=191");
		win.focus();
		
```

win variable has null from window.open(...) call and then fails on the next line win.focus()

I am invoking the function containing these lines via click of a button using

` myWebDriver.findElement(By.id("openAdvancedSortButton")).click(); `

The javascript code above is a 3rd party code and so we cannot change the window.open(...) line to something else, any suggestions on what else can be done. 

We even tried using the JavascriptExecutor approach as well to directly call the JavaScript method instead of via click of a button and that failed too.

**Comment by barancev** [comment]
This is not Selenium API, report this issue to Serenity project,

**Comment by lalitrnagpal** [comment]
You mean the below classes that I have used here, are not a part of Selenium?

```
org.openqa.selenium.By;
org.openqa.selenium.WebDriver;

```

`myWebDriver.findElement(By.id("openAdvancedSortButton")).click(); 
`

Can you suggest how would you do this 'purely' in Selenium then?

**Comment by barancev** [comment]
Sorry, now I see it's not a part of Serenity API, but a part of the target application.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also, latest Selenium version is 3.6, version 2.53 is antique, please upgrade.

**Comment by barancev** [comment]
Closing the issue, no reproduction scenario provided.
