### ISSUE TITLE
IE driver 32bits getWindowHandles return empty result

### ISSUE THREAD

**Issue by peidong-hu** [SeleniumHQ/selenium#494]
32bits IE driver returns empty result when trying to getWindowHandles. I encountered this issue with the following code. (64bits IE driver works well.)

private void refreshWindowsList(@Nullable WebDriver webD) {
		if (null == webD)
			throw GlobalUtils.createNotInitializedException("Web Driver");
		Set<String> allWinHandles = webD.getWindowHandles();
		if (allWinHandles.isEmpty()) throw GlobalUtils.createInternalError("Selenium getWindowsHandles error.");
		for (String winH : allWinHandles) {

**Comment by jimevans** [comment]
This issue slipped my notice until now. I've not seen anything like this outside of either crossing a Protected Mode boundary, having not set up the proper browser configuration (especially for IE11), or not properly awaiting the opening of a new window. Can you provide a full reproducible case, stripped down to only executing WebDriver code?

**Comment by jimevans** [comment]
After two weeks of awaiting and not receiving further information, closing.
