### ISSUE TITLE
Referenced assembly 'WebDriver' does not have a strong name	

### ISSUE THREAD

**Issue by mvsreddymca** [SeleniumHQ/selenium#4940]
Hi,

We are trying to build a .Net(4.0) application and try to deploy as a COM Class Interface. 
I assume that it's mandatory to add a strong name all the COM interfaces. For this we don't have strong name of this 'WebDriver' . Could you please review and help on this.

**Comment by jimevans** [comment]
You can find strong-named assembles at the [official Selenium download site](http://selenium-release.storage.googleapis.com/index.html). They are not, and will not be, made available via NuGet.

**Comment by MattyBoy4444** [comment]
This is a bad solution!  This should be re-opened.
