### ISSUE TITLE
CSS selector cannot identify the new attribute for input type.

### ISSUE THREAD

**Issue by timcons2** [SeleniumHQ/selenium#4943]
## Meta -
OS:  win10

Selenium Version: 3.5  

Browser:  chrome the latest

Browser Version:  61.0.3163.100 (64 bits)

## Expected Behavior -
driver.findElement(By.cssSelector("input[data-ctm-test='userName']")).sendKeys("Admin");
can be recognized.
## Actual Behavior -
Exception encounter by no element is found.
## Steps to reproduce -
The name and id will be different for each publish so we mock up a new attribute called data-ctm-test for CSS selector to identify as below:
<input name="WebPatterns_wt7$block$wtUsername$wtUserNameInput" tabindex="1" class="OSFillParent Mandatory" id="WebPatterns_wt7_block_wtUsername_wtUserNameInput" autofocus="autofocus" onkeydown="return OsEnterKey('WebPatterns_wt7_block_wtAction_wtLoginButton', arguments[0] || window.event)" type="text" maxlength="50" placeholder="Username" data-ctm-test="userName">

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Manumanu199719** [comment]
https§://Rrs.fr/

**Comment by barancev** [comment]
Closing the issue, no reproduction scenario provided.
