### ISSUE TITLE
Issue while Login with different user on SSO enabled machine

### ISSUE THREAD

**Issue by NehaBhatia28** [SeleniumHQ/selenium#4945]
I am using selenium remote webdriver and hitting the application on Single sign-on enabled remote machine.My application get login with the same user which I have used during login into remote machine. I want to run the application with different users while running tests but I am not able to do due to single sign-on.It is not giving working but I am not able to switch the user.it is always logged-in with the user which I used for login in the remote machine. The code looks like below:

WebDriver driver = null;
        ChromeOptions options = new ChromeOptions();
        options.addArguments(TEST_TYPE);
        options.addArguments(DISABLE_POPUP_BLOCKING);
        if(nodeName.equals("Level2"))
            options.addArguments("user-data-dir=C:/Users/Level2/AppData/Local/Google/Chrome/User Data/Default");
        else if(nodeName.equals("Level1"))
            options.addArguments("user-data-dir=C:/Users/Level1/AppData/Local/Google/Chrome/User Data/Default");
        DesiredCapabilities cap = DesiredCapabilities.chrome();
        cap.setCapability(ChromeOptions.CAPABILITY, options);
        cap.setBrowserName("chrome");
        cap.setCapability("applicationName", nodeName);
        String Node;
        if (System.getProperty("hubUrl") == null){
            Node = "http://" + hubIpaddress + ":" + hubPort + "/wd/hub";
        }else{
            Node = System.getProperty("hubUrl", "http://localhost:4444/wd/hub");
        }     
        System.out.println("---Node----"+Node);
        try {
            driver = new RemoteWebDriver(new URL(Node), cap);

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
