### ISSUE TITLE
There was a problem while loading TestCase 

### ISSUE THREAD

**Issue by pavan93** [SeleniumHQ/selenium#4946]
![selenium_web_driver](https://user-images.githubusercontent.com/13575020/31981613-1baea5f8-b972-11e7-8508-ebd324730217.png)
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by barancev** [comment]
Duplicate of #4406

**Comment by pavan93** [comment]
see my concern is my firefox is upgrading to 55 versoin automatically so need to be in stable 44 version everytime or everyday I can't install latest version so please kindly tell me procedure to stop continuous upgrade of firefox 
thanks
pavan

**Comment by barancev** [comment]
https://www.mozilla.org/en-US/firefox/organizations/faq/

**Comment by pavan93** [comment]
OK thanks for you support...
Thanks
pavan

**Comment by pavan93** [comment]
Thanks for your support
