### ISSUE TITLE
Click ignored when asynchronous js processing intervenes

### ISSUE THREAD

**Issue by dwt** [SeleniumHQ/selenium#4949]
## Meta -
OS:  OS X 10.12, CentOS 6, Windows 10
Selenium Version:  3.4, 3.5, 3.6
Browser:  Firefox (52, 56) Chromium (63.0.3213.0)

## Expected Behavior -

When executing a click event on an href, the link should be followed

## Actual Behavior -

If the click event is executed too early during page load, while there is still js processing working in the background (not affecting the href in any way as far as I can tell), the click event regularly leads to the link being visible selected (:active) but not being clicked / followed.

## Steps to reproduce -

Sadly, I haven't been able to reduce this from the application that I have seen this happen with. I can give some manual steps to get to where this happens if that helps though.

To Do so:
*  Go to https://zms-demo.de and get an admin account (left side down).
* log in as admin
* In the upper right, click the gear icon and select 'System'

The problem can now be observed when (automated via selenium) clicking back and forth between the secondary level tab bar ('Benutzer', 'System', 'Sprachen', 'Meta-Attribute', ...) It works great by hand, but via selenium the click events are ignored anything between 10-50% of the time, also depending on the browser executing this. Especially clicking away from the 'System' tab when it is loading.

However, when I tried to reduce this behavior without talking to the real server, it always vanished. I suspect that I haven't been able to retain the asynchronous behavior that makes this happen, but I cannot invest more time in it now.

## Workaround -

We have used code like the following to create a workaround signal in the website

```js
$("body").addClass("loading");

$(document).ready(function() {
        if ($.active !== 0) {
                $(document).ajaxStop(function() {
                        $("body").removeClass("loading").addClass("loaded");
                })
        } else {
                $("body").removeClass("loading").addClass("loaded");
        }
});
```

and then wait for the `.loaded` class to appear on the website before interacting with it via selenium manually in the tests. Which is of course quite inconvenient. Especially because the JS is (supposedly just) doing progressive enhancement which his not relevant to what is interacted with in these tests.

Sorry I couldn't reproduce this further, I would very much appreciate any Ideas if there is a better way to achieve this, or if I'm missing any crucial feature of Selenium to cope with this? Also I still think there is a bug in Selenium, which makes it not correctly execute click events in certain conditions that I could not reduce yet.

What kind of guidance can I give you to find this bug? (Sorry, It will be hard for me to justify investing another 2-3 days to completely take the App apart to minify this).

**Comment by dwt** [comment]
To better understand how we deal with this, I should add the python context manager we use to ensure Selenium waits for page loads when we interact with the page in a way where we expect a page load to happen.

```py
@contextmanager
def _wait_for_page_load(self, timeout=DEFAULT_TIMEOUT, roottag='body'):
    old_page = self.driver.find_element_by_tag_name('html')
    yield
    self._wait(EC.staleness_of(old_page), timeout=timeout)
    
    # wait for js to be finished loading
    root = self._find_element(By.CSS_SELECTOR, roottag, timeout=timeout)
    classes = root.get_attribute("class").split(' ')
    if 'zmi' in classes and 'loading' in classes:
        self._find_element(By.CSS_SELECTOR, roottag+'.loaded', timeout=timeout)
```

This is used in the following manner:

```py
with self._wait_for_page_load():
    # trigger a page load
# Code that expects the new page to be loaded
```

We have added the second part of that context manager (which waits for the js) in response to this problem - but we would rather like to get rid of it, to make the tests execute faster, and wait specifically for progressive enhancements where we actually use them. (Thus also verifying that the rest of the app should work when these have not yet loaded).

The problem manifests itself in that the line `self._wait(EC.staleness_of(old_page), timeout=timeout)` runs into it's timeout as click does not trigger a page reload.

**Comment by dwt** [comment]
If wanted, I can privately share a test case in python to the developers of selenium that reproduces this bug against a private instance - it should be easy to adapt against the public instance linked above. However, it sadly is not reduced much.

**Comment by dwt** [comment]
Uhm, I feel kind of dumb now, as I just realized that the test in question is actually open source. :-) Ah well, here it is in it's entirety:

https://zmslabs.org/trac/browser/ZMS/trunk/selenium_tests/bug_reduction_test.py?rev=4285

**Comment by barancev** [comment]
Don't click too early :) Selenium can't detect if a click handler is attached to an element or not yet. Use more sophisticated waitings to detect the moment an element is ready to interact.

**Comment by dwt** [comment]
Please reopen - this is not about click handlers being attached or not. The clicked href is just a regular href that should just work.

**Comment by dwt** [comment]
I do understand that you cannot interact with js functionality that hasn't yet loaded. This bug is about interacting with the rest of a progressively enhanced page that _has_ already loaded.

**Comment by dwt** [comment]
@barancev ping?

This issue needs reopening, as the closing reason you suggested does not apply.

**Comment by barancev** [comment]
OK, reopening. But demand to install ZMS to reproduce the issue is too cruel! Can it be reproduced against https://zms-demo.de/? Please provide a [concise reproducible test case](http://sscce.org/).

**Comment by dwt** [comment]
Yes it can - I can try to reduce the test case to get there, but it will take some time. In the meantime: Is there anything you guys know about this kind of bug or am I the first to find something like this?

**Comment by barancev** [comment]
Lets' see the bug first.

**Comment by dwt** [comment]
Try this test:

```py
# encoding: utf-8

import unittest
from contextlib import contextmanager
from urlparse import urlparse, urljoin

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from ZMSTestCase import ZMSTestCase

DEFAULT_TIMEOUT = 20

class BugReductionTest(unittest.TestCase):
    
    def setUp(self):
        # get your own account if this one has already expired (system is reset regularly)
        # To get an account visit https://zms-demo.de and use the button on the lower left
        self.base_url = 'https://zms-demo.de'
        self.login = 'mhaecker@mac.com'
        self.password = 'm10214'
        
        firefox_path = None # I tested this against several firefox versions. Chrome has the same problem
        profile = webdriver.FirefoxProfile();
        self.driver = webdriver.Firefox(profile, firefox_binary=firefox_path)
    
    def test_reproduction(self):
        missed_clicks = 0
        self._navigate_to_workflow()
        for i in range(100):
            try:
                self._show_zmi_nav_tab('Aktionen', timeout=4)
            except TimeoutException as ignored:
                print('missed'); missed_clicks += 1
                self._show_zmi_nav_tab('Aktionen', timeout=2)
            self.driver.execute_script('window.scrollBy(0,350)')
            try:
                self._show_zmi_nav_tab('System', timeout=4)
            except TimeoutException as ignored:
                print('missed'); missed_clicks += 1
                self._show_zmi_nav_tab('System', timeout=2)
            self.driver.execute_script('window.scrollBy(0,350)')
        self.assertEquals(missed_clicks, 0)
    
    ###############################################################
    # Helpers below this line - you shouldn't need to change them #
    ###############################################################
    
    @contextmanager
    def _wait_for_page_load(self, timeout=DEFAULT_TIMEOUT, roottag='body'):
        old_page = self.driver.find_element_by_tag_name('html')
        yield
        self._wait(EC.staleness_of(old_page), timeout=timeout)
        
        # wait for javascript to be loaded (@see bootstrap.plugin.zmi.js)
        # root = self._find_element(By.CSS_SELECTOR, roottag, timeout=timeout)
        # classes = root.get_attribute("class").split(' ')
        # if 'zmi' in classes and 'loading' in classes:
        #     self._find_element(By.CSS_SELECTOR, roottag+'.loaded', timeout=timeout)
        
        # the code that makes this workaround work hasn't yet been deployed to zms-demo, 
        # so you can't see the fix at work.
    
    def _login(self):
        login_url = urljoin(self.base_url, '/manage_main')
        import urlparse
        components = urlparse.urlsplit(login_url)
        credentials = '%s:%s@' % (self.login, self.password)
        components_with_auth = urlparse.SplitResult(components[0], credentials + components[1], *components[2:])
        self.driver.get(urlparse.urlunsplit(components_with_auth))
    
    def _navigate_to_workflow(self):
        self.driver.get('https://zms-demo.de/manage_customize?lang=ger')
        login = self._find_element(By.CSS_SELECTOR, '.form-control[name=__ac_name]')
        login.clear()
        login.send_keys(self.login)
        password = self._find_element(By.CSS_SELECTOR, '.form-control[name=__ac_password]')
        password.clear()
        password.send_keys(self.password)
        self._find_element(By.CSS_SELECTOR, 'input[name=submit]').click()
    
    def _show_zmi_nav_tab(self, text, timeout=DEFAULT_TIMEOUT):
        with self._wait_for_page_load(timeout=timeout):
            # element = self._find_element(By.CSS_SELECTOR, '.main-nav a'%text.lower(), timeout=timeout)
            element = self._find_element(By.XPATH, '//*[contains(@class,"nav-tabs")]//a[text()="%s"]' % text, timeout=timeout)
            element.click()
    
    def _wait(self, condition, timeout=DEFAULT_TIMEOUT):
        return WebDriverWait(self.driver, timeout).until(condition)
    
    def _find_element(self, by, value, timeout=DEFAULT_TIMEOUT):
        print "_find_element",by,value
        return self._wait(EC.visibility_of_element_located((by, value)), timeout=timeout)
    

if __name__ == "__main__":
    unittest.main()
```

**Comment by dwt** [comment]
That password will regularly be reset (as it's a demo system) so you might have to create your own to test this. To do so, just visit ams-demo.de and click the 'get admin account' button after providing your email.

<img width="429" alt="bildschirmfoto 2017-11-03 um 12 21 33" src="https://user-images.githubusercontent.com/57199/32371586-bac5940a-c091-11e7-83e3-fabb36d547c6.png">

**Comment by dwt** [comment]
@barancev Hey, did you encounter any problems replicating the problem? Anything I can help with?

**Comment by dwt** [comment]
ping? Anyone out there?

**Comment by barancev** [comment]
Selenium's guilt is its speed only. Yes, it clicks a tab too early, because it's fast. I could reproduce the issue manually too (but once only).

I can only repeat what I told already. Selenium can't detect if a click handler is attached to an element or not yet. Use more sophisticated waitings to detect the moment an element is ready to interact.

Or, better, ping the developers and suggest them to make elements hidden until they are ready to interact.

**Comment by dwt** [comment]
Hi @barancev: I am very surprised you attribute this to a missing click handler - because I am pretty sure there are _no_ click handlers involved? 

The html that is clicked is this:

```html
<li class="active">
  <a href="https://zms-demo.de/manage_customizeLanguagesForm?lang=ger">Sprachen</a>
</li>
```

Thus I can also not reproduce this by hand. Thus I really think this issue needs reopening.

**Comment by barancev** [comment]
Tomorrow I'll create a screencast that proves this issue can be reproduced manually.

**Comment by barancev** [comment]
https://www.screencast.com/t/bGInY5TfI
Red halo around the cursor appears at the moment of click.

**Comment by dwt** [comment]
Well, this is very strange and reason to investigate deeper on my part. Thanks very much for your trouble.
