### ISSUE TITLE
Issue with Grid2 wiki page

### ISSUE THREAD

**Issue by drobson1891** [SeleniumHQ/selenium#495]
About halfway down under the Configuring Nodes by Command Line section, there's an explanation for a piece of code or command that will start 11 browsers, but the actual code does not precede this.

**Comment by ddavison** [comment]
sure it does....

this tells you that **by default...** when you fire up a node, it gets assigned 11 possible browsers to be run.

![screen shot 2015-04-27 at 12 13 43](https://cloud.githubusercontent.com/assets/2972876/7352004/e10db9f8-ecd6-11e4-82c5-2eab34db0fd8.png)

**Comment by ddavison** [comment]
I think what you're looking for is a little bit past that.  https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json

**Comment by dtrobson099** [comment]
Yes - I was able to figure that out, I just think it could have been worded
better.  It reads very ambiguously.

"By default, this starts 11 browsers..."

"This" doesn't refer to anything immediately concrete in context.
"Starting the node", which was defined earlier, would be more appropriate.

Nitpicky I know, but I just noticed this and was trying to help.



On Mon, Apr 27, 2015 at 12:15 PM, Dj <notifications@github.com> wrote:

> I think what you're looking for is a little bit past that.
> https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/495#issuecomment-96728793>.
>



-- 

*Dan Robson*
413 Edgecreek Trail | Rochester, NY 14609
dan@robsonemail.com
Cell: (585) 738-8296

**Comment by ddavison** [comment]
i agree this could be better worded.  I'm on the documentation team in the SeleniumHQ github group, however I don't have access to the wiki :confused: , i'll see if i can get someone to unlock the wiki, and I can make a change to it.  Do you have any recommendation on what it could say?

**Comment by dtrobson099** [comment]
Without getting too verbose - it doesn't actually start the browsers, it
just instantiates them so they're available to start from the grid.
Perhaps: "By default, starting the node allows for concurrent use of 11
browsers..." would be more appropriate.

On Mon, Apr 27, 2015 at 1:20 PM, Dj <notifications@github.com> wrote:

> i agree this could be better worded. I'm on the documentation team in the
> SeleniumHQ github group, however I don't have access to the wiki [image:
> :confused:] , i'll see if i can get someone to unlock the wiki, and I can
> make a change to it. Do you have any recommendation on what it could say?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/495#issuecomment-96748321>.
>



-- 

*Dan Robson*
413 Edgecreek Trail | Rochester, NY 14609
dan@robsonemail.com
Cell: (585) 738-8296

**Comment by ddavison** [comment]
fixed!
