### ISSUE TITLE
doubleClick with selenium-html-runner-3.6.0 doesn't work on firefox 53

### ISSUE THREAD

**Issue by jeirgino** [SeleniumHQ/selenium#4950]
## Meta -
OS:  win 8.1
Selenium Version:  selenium-html-runner-3.6.0
Browser:  firefox 
Browser Version:  53.0

## Expected Behavior -
Hello everyone. Thank you for watching my issue.
In my testcase I want to perform a doubleClick throught html-runner command

## Actual Behavior -
In selenium-IDE-2.9.1 it works but when I launch the script with html-runner-3.6.0 and a htmlSuite
the log said that the command passed but nothing happened on firefox.
It works for chrome.

## Steps to reproduce -
in my test case:
doubleClick | //div[3]/div/div[2]/div/table/tbody[2]/tr/td/div |

java -jar selenium-html-runner-3.6.0.jar -htmlSuite  *firefox  @baseURL testSuite.html log.html

**Comment by lmtierney** [comment]
This is already logged with the appropriate party. mozilla/geckodriver#661
