### ISSUE TITLE
Mismatch in documentation and implementation of WebDriverWait Constructor argument type

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#4952]
## Meta - Mismatch in WebDriverWait Constructor Argument type. 
Though the argument type of the constructor for `WebDriverWait` mentions **`long`** but the `Long.MAX` value **`9223372036854775807`** is not getting accepted.

## Steps to reproduce -
The [documentation](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/WebDriverWait.html) of **`WebDriverWait`** says :  

	public WebDriverWait(WebDriver driver, long timeOutInSeconds)

Even Eclipse IDE shows the same as follows:

	org.openqa.selenium.support.ui.WebDriverWait.WebDriverWait(WebDriver driver, long timeOutInSeconds)
	
A small test on the Java Primitive Data Types is as follows:

	public class Min_Max_Primitive_Data_Types 
	{
		public static void main(String[] args) 
		{
		    System.out.println("Integer.MIN = " + Integer.MIN_VALUE);
		    System.out.println("Integer.MAX = " + Integer.MAX_VALUE);
		    System.out.println("Long.MIN = " + Long.MIN_VALUE);
		    System.out.println("Long.MAX = " + Long.MAX_VALUE);
		}
	}
	
The output reveals:

	Integer.MIN = -2147483648
	Integer.MAX = 2147483647
	Long.MIN = -9223372036854775808
	Long.MAX = 9223372036854775807
	
Now configuring :

	WebDriverWait wait2 = new WebDriverWait(driver, 9223372036854775807);
	
Eclipse IDE showing error as :

	The literal 9223372036854775807 of type int is out of range

Which means though the argument type of the constructor for `WebDriverWait` mentions **`long`** but the `Long.MAX` value **`9223372036854775807`** is not getting accepted.

#OS:  Windows8, Pro

#Selenium Version:  3.6.0

#Browser:  Firefox

#Browser Version:  56.0 (64-bit)

**Comment by shs96c** [comment]
The compiler tells you that it's interpreting your number as an int, which is then being coerced to a long.
