### ISSUE TITLE
IEDriver find_elements_by_xpath throws 'out of memory error' on Win10 

### ISSUE THREAD

**Issue by ovkom** [SeleniumHQ/selenium#4957]
## Meta -
OS:  Windows 10
Selenium Version: 2.53.1 , 3.4.0
IEDriver version: 2.53.1, 3.4.0
Browser:  Internet Explorer 11
Browser Version:  11

## Expected Behavior -
list is returned, empty or not
## Actual Behavior -
error 'out of memory'
## Steps to reproduce -
url = https://www.ncbi.nlm.nih.gov/variation/tools/1000genomes
driver.get(url)
driver.find_elements_by_xpath("//div[contains(text(), 'Loading...')]")
First the problem was found using the remote driver on SauceLabs.com (ticket 44343). They reproduced it on local IEDriver (see their screenshot iedriver_out_of_memory). The error is returned when the expected list supposed to be empty (my impression). The error has never happened on Windows 7.
![iedriver_out_of_memory](https://user-images.githubusercontent.com/33096263/32006980-3f6b097e-b976-11e7-9f69-e68c2f0407d2.png)

**Comment by diemol** [comment]
Is this issue still valid? 
I tried this and I did not get any errors (aside from the pop up with "warning, unsupported browser").

**Comment by diemol** [comment]
I'll close this since the issue went stale and no more comments from the community were received.
