### ISSUE TITLE
Actions.dragAndDropBy() fails with short stroke - completion depends timing/cpu load

### ISSUE THREAD

**Issue by gwtuser** [SeleniumHQ/selenium#4960]
## Meta -
OS:  OpenSUSE 42.2
Selenium Version:  3.5.3
Browser:  Firefox
Browser Version: 56  
-->

## Expected Behavior -

Drag should've moved the full stroke specified by the offsets, not short-stroking.

## Actual Behavior -

In default (non-legacy) mode, and geckodriver (18 and 19 tested), Actions.dragAndDropBy() fails to complete the drag, seemingly moving the thumbslider (in my case) a random distance less than what I requested.  

## Steps to reproduce -

By manually composing a sequence:

Actions.clickAndHold(element).moveByOffset(xOffset,yOffset).release()

I see the same behavior, ... but it's fixed if I insert a pause

Actions.clickAndHold(element).moveByOffset(xOffset,yOffset).pause(500).release()

So obviously, what's happening is that the code is actually only attempting to drag for a fixed amount of time, and then giving up.  If the underlying JavaScript/browser code triggered by the thumb dragging hasn't finished running and the thumb slider hasn't actually moved the requested distance within that fixed amount of time, it simply releases prematurely.

Note that, legacy mode works perfectly - I don't need to add any delay.

Can you provide an Actions.moveByOffsetAndWait() that waits until the cursor reaches the requested offset?  Otherwise, I'm going to be stuck trying to pick an appropriate pause(), which may either be too much, or not enough.

Note that I can provide a repro case, but I suspect the devs may acknowledge the behavior I describe as expected or part of the design - but then how do I deal with the variability in execution time breaking my tests - other than adding a very large pause?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by gwtuser** [comment]
I explained why I didn't provide a test case upfront in the last paragraph - because I suspected that you guys would answer, "That's expected behavior," and I didn't want to do throwaway work if that would be the ultimate answer even after I went to the trouble of building a standalone test case.

However, I will create a test case now since you seem to be saying it shouldn't behave like that.

**Comment by barancev** [comment]
Don't forget to provide a reproduction scenario, otherwise the issue will be closed.

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided. Feel free to request reopening as soon as you get a reproduction case.
