### ISSUE TITLE
Cannot define class using Reflection

### ISSUE THREAD

**Issue by Affon** [SeleniumHQ/selenium#4964]
OS: Linux Ubuntu 16.04
Selenium Version:  2.52.0 
Browser:  Chrome

Browser Version:  Version 61.0.3163.91

I'm running Selenium tests from jenkins on a linux machine. When running the tests I'm having this:
`ERROR: Cannot define class using reflection` with no other details

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also, version 2.52 is too old. Latest one is 3.6 at the moment.

**Comment by Affon** [comment]
```
navigateToUrl (url) {
  driver.get('about:blank')
  driver.get(url)
};
```
The browser is open but I get the previous error in the console, then nothing happens. Also I updated Selenium to 3.6 and the error is still the same.
Everything is correctly imported, the same command worked last week.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

As soon as you have exact steps to reproduce the issue we'll be ready to reopen it.

**Comment by Toshakins** [comment]
This happened to me when I tried to use OpenJDK ver. 9 on Ubuntu and supplied `--no-sandbox` option. Resolved by switching to the OpenJDK ver. 8.
