### ISSUE TITLE
error

### ISSUE THREAD

**Issue by huamgg** [SeleniumHQ/selenium#4967]
## Meta -
OS:  

Selenium Version:  IDE.2.9.1

Browser:  Firefox

Browser Version:  

## Actual Behavior -

There was an unexpected error. Msg: TypeError: window.editor.suiteTreeView is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by lmtierney** [comment]
Duplicate of #4406
