### ISSUE TITLE
IEDriverServer 3.6.0 hanging after file download attempt

### ISSUE THREAD

**Issue by JOberloh** [SeleniumHQ/selenium#4972]
Upon clicking a download link in IE, the IE download banner will appear at the bottom of the list and the test will stop and hang from that point on. Use the following test class to recreate the issue:

```
using System.IO;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.IE;

namespace PageObjectModel.Tests
{
    [TestFixture]
    class NoSetupTest
    {
        private IWebDriver driver;

        [Test]
        public void Test()
        {
            driver = new InternetExplorerDriver();
            driver.Manage().Window.Maximize();
            driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/download");
            System.Threading.Thread.Sleep(2000);
            driver.FindElement(By.LinkText("ClasificacionErrores.txt")).Click();
            System.Threading.Thread.Sleep(2000);
            driver.Navigate().GoToUrl("https://www.google.com");
        }
    }
}
```

**Comment by jimevans** [comment]
That’s probably because the browser’s `readyState` property does not return to `complete` when the file download item is active. You can try setting the `pageLoadStrategy` to `eager`, though that may have repercussions on other page loads during the rest of your test suite.

**Comment by jimevans** [comment]
No response from reporter in 6 months. File downloads aren’t supported by WebDriver in general nor by the IE driver in specific. Workaround provided. Closing issue.
