### ISSUE TITLE
IEDriver 3.6 - save_screenshot doesn't save what browser is rendering on particular pages

### ISSUE THREAD

**Issue by andreabisello** [SeleniumHQ/selenium#4973]
On
Windows 10 64 bit full stack updated
With
Selenium 3.6
IEDriver 3.6

this

browser.save_screenshot('screenshot.png')

will not save what the browser is rendering.

i tried to a lot of public website to reproduce the issue, but i'm not able to reproduce it.

this happens in my customer web application, page is protected and i cannot share it.

other webdriver works as aspected and there is not a loading time issue because i'll wait a 15 seconds before taking screenshot (2 second can be sufficient).

This is what IE is rendering

![image](https://user-images.githubusercontent.com/2149815/32112242-fde0e1b8-bb3c-11e7-9964-d5df3d113c5c.png)

This is what the keyword save in the screenshot

![image](https://user-images.githubusercontent.com/2149815/32112251-0368c196-bb3d-11e7-8071-04470282c9d2.png)

where are the left and right colum gone?

**Comment by cgoldberg** [comment]
http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html

**Comment by diemol** [comment]
After reading the linked issue and seeing that no reproduction scenario was ever provided, plus the link above explaining more details... this issue has stalled and it will be closed.

If this is still a valid issue, please create a new one and fill out all the required information.
