### ISSUE TITLE
I want to get the data of trend picture which use svg path label

### ISSUE THREAD

**Issue by YancyGo** [SeleniumHQ/selenium#4975]
## Meta -
OS:  windows 7

Selenium Version:  2.52

Browser:  Chrome

## Expected Behavior -
- As shown below， I want to get the data of trend picture which use svg path label，I don't have any clue now，who can give me some advices

![image](https://user-images.githubusercontent.com/12470388/32130315-f84f1a12-bbc8-11e7-9bc1-ed21a90852ee.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
