### ISSUE TITLE
provide a "LATEST" txt file in the binary folder

### ISSUE THREAD

**Issue by andreabisello** [SeleniumHQ/selenium#4978]
in order to automate upgrading of drivers,
i want to create a script that download the latest version of the driver and store it in a json file.
if a new version is avaiable, it will download again.

with chrome driver, i can use the LATEST_RELEASE in https://chromedriver.storage.googleapis.com/index.html to mach the latest url.

Can you provide the same file in this http://selenium-release.storage.googleapis.com/index.html folder ?

**Comment by diemol** [comment]
Since we are moving our binaries to GitHub releases, this is solved.

You can check what the `latest` stable version is by viewing https://github.com/SeleniumHQ/selenium/releases/latest
