### ISSUE TITLE
 org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer

### ISSUE THREAD

**Issue by gamerchandu** [SeleniumHQ/selenium#4979]
## Meta -
OS:  Windows 7
 Selenium Version:   3.0.1
 Browser:  Chrome 
Browser Version:  62.0.3202.75
Chrome driver version : 2.30.477700
## Actual Behavior - 
Exception in thread "main" org.openqa.selenium.WebDriverException: disconnected: unable to connect to renderer
- Exception occurs at maximise() step .

## Steps to reproduce -
public class OpenBrowser
{
public static void main(String args[]) 
{
WebDriver driver;
System.setProperty("webdriver.chrome.driver","//path to chrome driver");
driver=new ChromeDriver();
driver.manage().window().maximize();
driver.get("http://www.google.com");
}
}

**Comment by barancev** [comment]
Upgrade chromedriver.

**Comment by arroyoc** [comment]
Verified that upgrading chromedriver to version 2.33 fixed this problem.

**Comment by alexandrera** [comment]
Even after the update to version 2.33 the maximize action still don't work. If I remove it, all goes well.
**driver.manage().window().maximize();**

**Comment by alexandrera** [comment]
No, actually I'm on Windows 10.

**Comment by dianhua1560** [comment]
Updating chromedriver and selenium standalone jar fixed this issue for me.
I was using windows 7 and python.

**Comment by varuntaneja** [comment]
it worked after updating chromedriver..

**Comment by Himanshuhacks** [comment]
I was also facing the same issue. I updated my chrome driver to version 2.33 and now it is working fine

**Comment by Udhh** [comment]
For me also, it worked after updating the chrome driver.

**Comment by samlucax** [comment]
I'm using the chromedriver 2.33, and I had to remove the **maximize()** function to work as expected.

There are someone facing the same problem using the **maximize** ?

**Comment by lmtierney** [comment]
@samlucax depends, are you on linux? https://bugs.chromium.org/p/chromedriver/issues/detail?id=1901&can=1&q=maximize&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by mshimer** [comment]
upgrade to chromedriver 2.33 fixed this for me.  Download latest and move to node_modules/selenium-standalone/.selenium/chromedriver/<here>

Get rid of old one.

**Comment by ameykhopade2** [comment]
Hi, Even I am getting the same problem for Maximize. I did upgrade the chrome version to 2.33 still getting the error. It is working fine on local machine with the upgrade but when I deploy my test on server through tfs. I am getting this error for maximize. its win 10 on serever.

**Comment by Prasannasana** [comment]
Hi,
  I am using Windows 2012 R2 server(64-Bit) . From Jenkins i am trying to run a job where it has to open URL using Robot framework tool. In my Script I used "Maximize Browser Window" Selenium keyword. When the execution comes to this keyword it is constantly failing with "WebDriverException: Message: disconnected: unable to connect to renderer" error.
I am using 2.33.506120 Chrome Driver  version and Chrome Version is  "62.0.3202.94" .
Can anyone Please tell me what might be the reason and the remedy for this.

Thanks.

**Comment by kokog78** [comment]
@ameykhopade2 are you sure that on win 10 server the latest chrome browser & driver are installed?

**Comment by ameykhopade2** [comment]
its working fine now. latest chrome browser was installed on the server but my TFS build was now deploying the new browser which was creating the problem changed the build def and its working with the upgrade to 2.33.
thanks:)

**Comment by sarodemallika** [comment]
Hi,
I am getting the same error while executing below code :

 Driver = new ChromeDriver(driverPath, chromeOptions, TimeSpan.FromSeconds(180));

Chrome version: 62.0.3202.94 (Official Build) (64-bit)
Chrome Driver version:2.33

using Proxy settings in IE. Running Visual studio as Administrator.

**Comment by sarodemallika** [comment]
This is the Exception stack trace I am getting:
session not created exception from disconnected: Unable to receive message from renderer (Session info: chrome=62.0.3202.94) (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7600 x86_64) (InsecureCertificate)-------------trace-------------- at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout) at Web.Sample.NuGet.Framework.TestBase.StartDriver(String browser, Int32 implicitWaitSec) in C:\Users\nsakare\LATESTSITCRM\SITCRM\BAF.Tests\Framework\TestBase.cs:line 237 at BAF.Tests.Tests.PaymentsAndClaims.SIT.UC318_Populate_PolicyDetails_Test.UC318_US_96864_001P_PopulateClaimsPaidThisYear_Active_ClaimMade_Contri() in C:\Users\nsakare\LATESTSITCRM\SITCRM\BAF.Tests\Tests\360\SIT\UC318_Populate_PolicyDetails_Test.cs:line 425

**Comment by sarodemallika** [comment]
Hi anyone please help me fix this issue.
Thanks.

**Comment by sarodemallika** [comment]
options.addArguments("no-sandbox"); - solved the problem.. :)

**Comment by mvpmurali27** [comment]
options.addArguments("no-sandbox") and version 2.33 solved the issue

**Comment by sarodemallika** [comment]
I am using chromedriver 2.30.0.1 as 2.33 is giving some problem .

**Comment by kulavardan** [comment]
1. Upgrade chromedriver
2. Remove window size set keywords if you are using any

**Comment by Jia-ullah** [comment]
Yes it worked after updating chrome driver. I upgraded to 2.3.4 version. Thanks :)

**Comment by sreeramydk** [comment]
It worked for me after upgrading my chrome driver to 2.3.5 version. Thanks..

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)

**Comment by gramai** [comment]
Hello. 
I am getting the same error
`*** selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: disconnected: unable to connect to renderer
  (Session info: chrome=70.0.3538.80)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64)`
