### ISSUE TITLE
Webdriver.Remote not working on AWS EC2 Ubuntu 16.04

### ISSUE THREAD

**Issue by swagluke** [SeleniumHQ/selenium#4991]
I'm trying to do some website testing which requires to keep the old webdriver open then use webdriver.remote to re-attach back using the executor url and session id of the old driver. Same code runs fine on my MacBook, but running into error on AWS EC2 Ubuntu 16.04. 
## Meta -
OS:  Ubuntu 16.04
Selenium Version:  3.4.0
Browser:  Google-Chrome

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

-->

Browser Version:  
chromedrive = 2.33.506092

## Expected Behavior -
Using Remote Webdriver to re-attach to the old ChromeDriver.

## Actual Behavior -
Webdriver.Remote failed to start.
![screen shot 2017-11-02 at 10 16 50 am](https://user-images.githubusercontent.com/7270414/32330617-095a1374-bfb7-11e7-954c-d149cc054a89.png)

## Steps to reproduce -
Screen shot of the code is attach below. Run code by typing "sudo python3 Test.py"

![screen shot 2017-11-02 at 10 16 37 am](https://user-images.githubusercontent.com/7270414/32330633-10f52e0c-bfb7-11e7-86a3-63b992cb2084.png)

import os, subprocess
import time
import webbrowser
from selenium import webdriver
from selenium.common.exceptions import TimeoutException

options = webdriver.ChromeOptions()
options.binary_location = '/usr/bin/google-chrome'
options.add_argument('headless')
options.add_argument('--no-sandbox')
options.add_argument('window-size=1920x1080')
url = "https://www.facebook.com"
driver = webdriver.Chrome(chrome_options=options)
executor_url = driver.command_executor._url
session_id = driver.session_id
print(session_id)
print(executor_url)
driver.get(url)

driver2 = webdriver.Remote(command_executor=executor_url, desired_capabilities={})
# driver2.close()
driver2.session_id = session_id
print(driver2.current_url)
driver2.get("https://www.google.com")
print(driver2.current_url)

**Comment by cgoldberg** [comment]
please don't provide screenshots of source code.  It's extremely unhelpful compared to pasting the actual text.

**Comment by swagluke** [comment]
@cgoldberg My apologies. I've edited the post.

**Comment by swagluke** [comment]
After digging so long for this issue, I finally found the solution myself. Turns out Ubuntu without GUI is pain in the butt to deal with. So when you try to launch Selenium Webdriver. You need to add a few options not only the regular webdriver.Chrome, but also webdriver.Remote.

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import 
DesiredCapabilities

options = webdriver.ChromeOptions()
options.binary_location = '/usr/bin/google-chrome'
options.add_argument('headless')
options.add_argument('--no-sandbox')

driver = webdriver.Chrome(chrome_options=options)
executor_url = driver.command_executor._url
session_id = driver.session_id
driver.get("http://www.google.com")

print(session_id)
print(executor_url)

print(driver.current_url)

driver2 = webdriver.Remote(command_executor=executor_url, desired_capabilities=options.to_capabilities())
driver2.close()
driver2.session_id = session_id
print(driver2.current_url)
driver2.get("http://www.facebook.com")
print(driver2.current_url)
```
Also, having webdriver.remote will open up a zombie webdriver too. If you only care about re attach back to existing webdriver. You can close the new driver before the new driver attached back to the old one.
