### ISSUE TITLE
GetScreenshot() ignoring InternetExplorerOptions.EnableFullPageScreenshot option after upgrade from 2.48.0 to 3.6.0. Screenshot no longer shows the full page.

### ISSUE THREAD

**Issue by tronolone** [SeleniumHQ/selenium#4992]
![image](https://user-images.githubusercontent.com/12600498/32309241-6cadc878-bf47-11e7-84e2-dffb2bcbac78.png)
## Meta -
OS:  Windows 10
Selenium Version:  3.6.0 standalone jar using grid, C# 3.6.0 bindings
Browser Version:  Internet Explorer: 11.1770.14393.0 (32-bit)

## Steps to reproduce - See snippet below and attached screenshot.

  
    using System;
    using OpenQA.Selenium;
    using OpenQA.Selenium.IE;
    using OpenQA.Selenium.Remote;

    class Sandbox
    {
        public static void Main(string[] args)
        {
            // Define options.
            InternetExplorerOptions ieOptions = new InternetExplorerOptions();
            ieOptions.EnableFullPageScreenshot = true;

            // Convert options to DesiredCapabilities.
            DesiredCapabilities caps = (DesiredCapabilities)ieOptions.ToCapabilities();

            // Create the RemoteWebDriver on the Selenium grid.
            IWebDriver driver = new RemoteWebDriver(new Uri("http://HubComputerName:4444/wd/hub"), caps);
            
            // Maximize window.
            driver.Manage().Window.Maximize();

            // Go to the test page.
            driver.Navigate().GoToUrl(@"https://en.wikipedia.org/wiki/Selenium_(software)");

            // Take a screenshot.
            ((ITakesScreenshot)driver).GetScreenshot().SaveAsFile(@"O:\QA\image.png", ScreenshotImageFormat.Png);

            // Terminate the session.
            driver.Quit();
        }
    }

**Comment by lmtierney** [comment]
What version of the dotnet bindings are you using?

**Comment by tronolone** [comment]
@lmtierney C# 3.6.0 bindings

**Comment by jimevans** [comment]
Since the IE driver adopted the W3C Webdriver Specification in 3.5, all screenshots are view port only, as this is mandated by the specification. This is by design; it will not be changed until and unless the spec is.
