### ISSUE TITLE
'Could not find or load main class org.openqa.grid.selenium.GridLauncher' while launching grid extras 1.12.17 with selenium server 3.6.0

### ISSUE THREAD

**Issue by vignesh-paramasivam** [SeleniumHQ/selenium#4996]
OS:  
Windows 7
Selenium Grid Extras Version:  
1.12.17
Selenium Grid Version:
 3.6.0

I was using the Selenium grid extras 1.12.6 with Selenium standalone server 2.53.1. Now, i'm trying to upgrade both the Grid extras 1.12.17 and Server 3.6.0 and was facing with the below error,
`Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher`

I have tried with different versions,

Extras **1.12.17** with Server 2.53.1 - Working fine
Extras 1.12.17 with Server 3.6.0 - Error: Class not found
Extras 1.12.17 with Server 3.4.0 - Error: Class not found
Extras 1.12.17 with Server 3.5.3 - Error: Class not found
Extras **1.12.14** with Server 3.6.0 - Error: Class not found

**node_5555.json**
`
{
  "capabilities": [
    {
      "applicationName": "win7_64bit_ff",
      "platform": "win7",
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 3,
      "version": "46.0"
    },
    {
      "applicationName": "win7_64bit_chrome",
      "platform": "win7",
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 4,
      "version": "62.0.3202.75"
    },
    {
      "applicationName": "win7_64bit_ie_11",
      "platform": "win7",
      "seleniumProtocol": "WebDriver",
      "browserName": "internet explorer",
      "maxInstances": 1,
      "version": "11.00.9600.16428"
    }
  ],
  "configuration": {
    "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
    "maxSession": 7,
    "port": 5555,
    "register": true,
    "unregisterIfStillDownAfter": 10000,
    "hubHost": "machine001",
    "hubPort": 4444,
    "nodeStatusCheckTimeout": 10000,
    "downPollingLimit": 0
  }
}
`

selenium_grid_extras_config.json
`
{
  "theConfigMap": {
    "auto_start_hub": "0",
    "video_recording_options": {
      "record_test_videos": "false",
      "videos_to_keep": "0"
    },
    "node_config_files": [
      "node_5555.json"
    ],
    "hub_config_files": [],
    "iedriver": {
      "bit": "64",
      "directory": ".",
      "version": "2.53.1"
    },
    "chromedriver": {
      "bit": "32",
      "directory": ".",
      "version": "2.33"
    },
    "default_role": "node",
    "reboot_after_sessions": "20",
    "auto_update_browser_versions": "0",
    "hub_config": {},
    "auto_start_node": "1",
    "auto_update_drivers": "0",
    "webdriver": {
      "directory": ".",
      "version": "selenium-server-standalone-3.6.0"
    },
    "log_maximum_age_ms": 864000000,
    "grid_jvm_options": {
      "selenium.LOGGER.level": "WARNING",
      "webdriver.server.session.timeout": "900"
    },
    "grid_extras_port": "3000",
    "active_modules": [
      "com.groupon.seleniumgridextras.tasks.DeleteOldLogsTask",
      "com.groupon.seleniumgridextras.tasks.Setup",
      "com.groupon.seleniumgridextras.tasks.Teardown",
      "com.groupon.seleniumgridextras.tasks.MoveMouse",
      "com.groupon.seleniumgridextras.tasks.RebootNode",
      "com.groupon.seleniumgridextras.tasks.KillAllIE",
      "com.groupon.seleniumgridextras.tasks.KillAllFirefox",
      "com.groupon.seleniumgridextras.tasks.KillAllChrome",
      "com.groupon.seleniumgridextras.tasks.KillAllSafari",
      "com.groupon.seleniumgridextras.tasks.SetAutoLogonUser",
      "com.groupon.seleniumgridextras.tasks.GetProcesses",
      "com.groupon.seleniumgridextras.tasks.KillPid",
      "com.groupon.seleniumgridextras.tasks.Netstat",
      "com.groupon.seleniumgridextras.tasks.Screenshot",
      "com.groupon.seleniumgridextras.tasks.ExposeDirectory",
      "com.groupon.seleniumgridextras.tasks.StartGrid",
      "com.groupon.seleniumgridextras.tasks.GetInfoForPort",
      "com.groupon.seleniumgridextras.tasks.GridStatus",
      "com.groupon.seleniumgridextras.tasks.KillAllByName",
      "com.groupon.seleniumgridextras.tasks.StopGrid",
      "com.groupon.seleniumgridextras.tasks.GetConfig",
      "com.groupon.seleniumgridextras.tasks.StopGridExtras",
      "com.groupon.seleniumgridextras.tasks.IEProtectedMode",
      "com.groupon.seleniumgridextras.tasks.IEMixedContent",
      "com.groupon.seleniumgridextras.tasks.SystemInfo",
      "com.groupon.seleniumgridextras.tasks.GetNodeConfig",
      "com.groupon.seleniumgridextras.tasks.UpdateNodeConfig",
      "com.groupon.seleniumgridextras.tasks.AutoUpgradeDrivers",
      "com.groupon.seleniumgridextras.tasks.DownloadWebdriver",
      "com.groupon.seleniumgridextras.tasks.DownloadIEDriver",
      "com.groupon.seleniumgridextras.tasks.DownloadChromeDriver",
      "com.groupon.seleniumgridextras.tasks.SessionHistory"
    ]
  }
}
`
## Expected Behavior -
Extras 1.12.17 with Server 3.6.0 - should start the node.
## Actual Behavior -
Extras 1.12.17 with Server 3.6.0 - Error: Class not found

Error log:
```
C:\GridNode\testsenode5555>java -Dselenium.LOGGER.level=WARNING -Dwebdriver.serv
er.session.timeout=900 -Dwebdriver.ie.driver=.\iedriver_2.53.1_64bit.exe -Dwebdr
iver.edge.driver="C:\Program Files (x86)\Microsoft Web Driver\MicrosoftWebDriver
.exe" -Dwebdriver.chrome.driver=.\chromedriver_2.33_32bit.exe -Dwebdriver.gecko.
driver=\tmp\webdriver\geckodriver\geckodriver_0.10.0.exe -cp C:\GridNode\testsen
ode5555\SeleniumGridExtras-1.12.17-SNAPSHOT-jar-with-dependencies.jar;.\selenium
-server-standalone-3.6.0.jar org.openqa.grid.selenium.GridLauncher -role node -f
riendlyHostName MACHINE001 -nodeConfig node_5555.json -log log\node_5555.log

Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher
```

## Steps to reproduce -
Executed the bat file with below command, with the specified node_5555.json and extras config.
```
@echo off

setlocal

 cd %~d0%~p0
 title Selenium Webdriver port:5555, Extras port:3000
 echo Starting node from directory %CD%
 set _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true
 java -jar SeleniumGridExtras-1.12.17-SNAPSHOT-jar-with-dependencies.jar
 taskkill /fi "username eq %USERNAME%" /fi "windowtitle eq %COMSPEC% - node_5555.bat" /F /T
 exit %ERRORLEVEL%

endlocal
```

**Comment by barancev** [comment]
The class name is GridLauncherV3 now, report the issue to grid extras.
