### ISSUE TITLE
Add support of Chrome's built-in code coverage collection

### ISSUE THREAD

**Issue by stasberkov** [SeleniumHQ/selenium#4999]
Chrome v59 introduced code coverage feature. I.e. devtool has functions like 
Profiler.startPreciseCoverage
Profiler.stopPreciseCoverage
Profiler.takePreciseCoverage
Profiler.getBestEffortCoverage
https://chromedevtools.github.io/devtools-protocol/tot/Profiler/#method-startPreciseCoverage
Please allow using them from Selenium somehow.

**Comment by barancev** [comment]
Selenium provides universal cross-browser API specified by W3C WebDriver standard.

You can start a browser with Selenium and use some devtools client library to attach to the running browser.
