### ISSUE TITLE
Chrome browser get hanged when exception error is thrown when test runs through selenium server in remote machine

### ISSUE THREAD

**Issue by perwez123** [SeleniumHQ/selenium#500]
I am using the selenium grid to run my test in several platform , I have updated all the jars of 2.45 (Selenium java 2.45 , selenium stand alone server 2.45 , chrome driver 2.14) . I am seeing that the browser gets handed when exception error is thrown in chrome browser and it does not refresh the browser . Even though that the refresh function also does not work . The same script were working fine in all these platform without hanging issue when was using  selenium 2.41 version . When i run the same script in my local system everything works fine .

Selenium Version : 2.45 
Chrome broeswer : Version 42.0.2311.90 m

Chrome driver : 2.14

OS : Windows 7 

Can you please provide me the solution for this issue .

Error message 
--------------------------

 [testng] org.openqa.selenium.TimeoutException: Timed out after 180 seconds waiting for com.pageobject.iap.videoplayer.VideoPlayBackControls$3@7843f53
   [testng] Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
   [testng] System info: host: 'W7-VM1', ip: '10.98.1.30', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_71'
   [testng] Session ID: 2056e2bf-e8ae-472b-b65b-35eb2862a612
   [testng] Driver info: org.openqa.selenium.remote.RemoteWebDriver
   [testng] Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\Pearson\AppData\Local\Temp\scoped_dir3664_31316}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, webdriver.remote.sessionid=2056e2bf-e8ae-472b-b65b-35eb2862a612, version=42.0.2311.90, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
   [testng] 	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
   [testng] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
   [testng] 	at com.pageobject.iap.videoplayer.VideoPlayBackControls.waitToCompleteWatchingVideo(Unknown Source)
   [testng] 	at com.qtpselenium.suite.iap.regressionTestScripts.VideoPlayerTestScript.TC1_allcontrolsDisplay_functioning_InPreviewInlinePage(Unknown Source)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] 	at java.lang.reflect.Method.invoke(Method.java:606)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
   [testng] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
   [testng] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:617)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
   [testng] 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
   [testng] 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
   [testng] 	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
   [testng] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   [testng] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
   [testng] 	at java.lang.Thread.run(Thread.java:745)

**Comment by ddavison** [comment]
This is not a Selenium problem.. If it were, org.openqa.selenium would be showing up in that stack trace.  I'd investigate your `waitToCompleteWatchingVideo()` method inside `VideoPlayBackControls`.

**Comment by perwez123** [comment]
I have a question here is , When time out exception error thrown from test Ng wait time , Then why the browser does refresh when refresh function is called before every tests . 

For example ;

Test 1 has thrown the above error.
Test 2 has the refresh browser function before test , where as refresh function should be able to refresh the browser for second test even if first test has encountered an issue .




Full code is here 
----------------------------
public class VideoPlayerTestScript extends BrowserConfigurations {
	
	@BeforeMethod
	public void beforemethod(Method method) throws Exception{
		driver.navigate().refresh();
		WaitTool.waitForPageTOLoadCompletely(driver, 60);
		APP_LOGS.info("Refreshing the browser .........");
		APP_LOGS.info("#############   Started Executing Test Case  ##################"+method.getName());
		
	
	}
	
	@DataProvider
	public Object[][] getTestData() throws Exception
	{
		return ExcelReader.getTableArray(ExcelPath.VideoPlayer, "video");
	}
/*@Test(dataProvider="getTestData",description=" All controls are turned ON")
	public void TC1_allcontrolsDisplay_functioning_InPreviewInlinePage(String interaction_name,String index,String tilte) throws Exception{
		
		
		VideoAdminControlObjects videoadminObj= new VideoAdminControlObjects(driver);
		videoadminObj.clickOnVideoToggleCheckBox();
		videoadminObj.reapeat();
		videoadminObj.setWatchCount("1");
		//Opening the video player in the PreviewInline
		Navigation nav=new Navigation(driver);
		nav.openPlayerIn_PopUp();
		nav.click_On_Next(index);
		
		VideoPlayBackControls videoPlayback= new VideoPlayBackControls(driver, Integer.parseInt(index));
		videoPlayback.waitfor_VideoPlayer_ToLoad();
		VideoVolumeControl volume= new VideoVolumeControl(driver,Integer.parseInt(index));
		VideoCaptionControl captions= new VideoCaptionControl(driver,Integer.parseInt(index));	
		VideoQualityControls qcSettings= new VideoQualityControls(driver, Integer.parseInt(index));
        VideoScreenResize fullscreen= new VideoScreenResize(driver,Integer.parseInt(index));
        VideoPlayBackSpeedControl speedControl=new VideoPlayBackSpeedControl(driver, Integer.parseInt(index));
        
	
		verifyTrue(videoPlayback.isPlaybuttonDisplayedInBottomLeft(), "Paly button did not display in the video player");
		verifyTrue(videoPlayback.isPlayButtonDisplayedIn_Overlay(), "Paly button did not display in the Overlay of the video player");
		
		// Verify Volume control..
		
		verifyTrue(volume.isVolumeControlButtonDisplayed(), "Volume control button did not display in the video Player");
		verifyTrue(volume.isSetToUnmuteMode(), "By default voulme remains Mute...");
		
		

*@Test(dataProvider="getTestData",description="All controls are turned On and verify Replay functions ")
	
	public void TC2_allcontrolsDisplay_functioning_InPreviewPopUpPage(String type,String index,String title) throws Exception{

	
		
		VideoAdminControlObjects videoadminObj= new VideoAdminControlObjects(driver);
		videoadminObj.clickOnVideoToggleCheckBox();
		videoadminObj.reapeat();
		videoadminObj.setWatchCount("5");
		//Opening the video player in the PreviewInline
		Navigation nav=new Navigation(driver);
		nav.openPlayerIn_PopUp();
		nav.click_On_Next(index);
		
		VideoPlayBackControls videoPlayback= new VideoPlayBackControls(driver, Integer.parseInt(index));
		VideoVolumeControl volume= new VideoVolumeControl(driver,Integer.parseInt(index));
		VideoCaptionControl captions= new VideoCaptionControl(driver,Integer.parseInt(index));	
		VideoQualityControls qcSettings= new VideoQualityControls(driver, Integer.parseInt(index));
        VideoScreenResize fullscreen= new VideoScreenResize(driver,Integer.parseInt(index));
        VideoPlayBackSpeedControl speedControl=new VideoPlayBackSpeedControl(driver, Integer.parseInt(index));
        
		
		verifyTrue(videoPlayback.isPlaybuttonDisplayedInBottomLeft(), "Paly button did not display in the video player");
		verifyTrue(videoPlayback.isPlayButtonDisplayedIn_Overlay(), "Paly button did not display in the Overlay of the video player");
		
		// Verify Volume control..
	
		verifyTrue(volume.isVolumeControlButtonDisplayed(), "Volume control button did not display in the video Player");
		verifyTrue(volume.isSetToUnmuteMode(), "By default voulme remains Mute...");
		
		checkForVerificationErrors();
}

**Comment by perwez123** [comment]
And also saw that browser gets hanged after throwing this error , even if try to refresh the browser manually , it did not refresh . The same code works fine when it run in my local system but this problem occurs only when test is run in remote system using selenium server . 

My question is --   Browser should not be hanged and should be able to refresh for the next test even if any error thrown .

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
