### ISSUE TITLE
In Selenium 3.5 in IE11,10 and in Edge browsers xpath functions are not working fine.

### ISSUE THREAD

**Issue by Aditya1209** [SeleniumHQ/selenium#5000]
## Meta -
OS:  

Selenium Version:  3.5

Browser:  Internet Explorer

Browser Version:  

## Steps to reproduce -

Issue:
In Internet Explorer web elements find using contains,text, preceding-sibling, following-sibling are not working which are working fine in Firefox,Chrome and safari browsers. Please help on this.

**Comment by jimevans** [comment]
Can you please provide a concrete example on a publicly available web page?

**Comment by Aditya1209** [comment]
Navigate to : https://www.google.com/gmail/about/

Try to click on Sign in link using : Either Link text By.linkText("Sign In")  or Using By.xpath("//a[contains(text(),'Sign In')]").

The Above mentioned Three locators are working fine in Fire fox and Chrome browsers. But not working in IE 10, IE 11 and Edge browsers too. Like same way when we construct xPath using descendant,Following-sibling or Preceding-sibling also not working in above mentioned IE browsers but working fine in Firefox and Chrome browsers.

**Comment by barancev** [comment]
There locators don't work in Chrome too.
By.linkText searches by visible (rendered) text, that is capitalized "SIGN IN" on the mentioned page.
By.xpath searches by the data present in DOM, that is "Sign in" on the mentioned page
By.linkText("SIGN IN") or By.xpath("//a[contains(text(),'Sign in')]") works in IE as well as in other browsers.

**Comment by Aditya1209** [comment]
Thanks for the explanation. Now elements are working fine in all browsers.

Do we have any method or capability, which skips the case sensitivity in Locators and works fine?

**Comment by barancev** [comment]
In XPath you can do something like 
`translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')`

Other than that -- no.
