### ISSUE TITLE
RESPONSE InitSession unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by 82006463** [SeleniumHQ/selenium#5002]
## Meta -
OS:  CentOS 7.3
Selenium Version:  2.53.1
Browser:  Chrome v62.0.3202.75
ChromeDriver:  v2.33.506092

Can someone help me ? thank you very much!

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lazb** [comment]
I have same problem. I'm using this script to install all dependencies: https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5

Then I run:
```
 chromedriver --url-base=/wd/hub --log-path=/tmp/chromedriver.log
Starting ChromeDriver 2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4) on port 9515
Only local connections are allowed.
```

And when I start functional test with codeception I get:
`[Facebook\WebDriver\Exception\UnknownServerException]
  unknown error: Chrome failed to start: exited abnormally
    (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.6.3-coreos x86_64)
`

**Comment by ambirag** [comment]
@lazb i get the same on Ubuntu, ticket with Chromedriver project https://bugs.chromium.org/p/chromedriver/issues/detail?id=2123 if you can provide any more data, please do

**Comment by lazb** [comment]
@ambirag I've checked linked issue and for me actually it was problem that in codeception I forgot to add --no-sandbox arg

`chromeOptions:
            args: ["--headless", "--disable-gpu", "--window-size=1920,1080", "--no-sandbox"] 
            binary: "/usr/bin/google-chrome-stable"`

**Comment by andreasneuber** [comment]
Had they same strange problem - adding `--no-sandbox` to chromeOptions did the trick.
Thanks lazb for mentioning.
