### ISSUE TITLE
Can't change Firefox preferences by serenity.properties

### ISSUE THREAD

**Issue by vivregenek** [SeleniumHQ/selenium#5007]
serenity-core 1.6.0, selenium-java 3.5.3, geckodriver 0.19.0 FF 56.0.2 (64)

I am trying changed FF preferences with serenity.properties:
`firefox.preferences="browser.download.dir=C:\\temp;browser.helperApps.alwaysAsk.force=false;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.download.folderList=2;"`

But it doesn't work. In about:config I see deafult values for this preferences.  
Also get this entries in output

`main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
Separator = ;
arg = browser.download.dir=C:\temp\
arg = browser.helperApps.alwaysAsk.force=false
arg = browser.download.manager.showWhenStarting=false
arg = browser.download.useDownloadDir=true
arg = browser.download.folderList=2
arg = browser.helperApps.neverAsk.saveToDisk=text/html`

**Comment by barancev** [comment]
Report this issue to Serenity project.
