### ISSUE TITLE
Urls having username and password are not working in IE10/IE11

### ISSUE THREAD

**Issue by Kuldeepnagar** [SeleniumHQ/selenium#501]
Urls having username and password are not working in IE10/IE11

We have RC tests which were working fine in IE9. 

We open our application by providing the username/password in url to bypass authentication for ex - 

selenium.open("http://username:password@localhost:9001") ;

While running these tests in IE10/IE11 we are seeing authentication box which is not showing up on IE9

Please suggest

Thanks
Kuldeep

**Comment by barancev** [comment]
Seleniun RC is deprecated and its support discontinued.
Also, this is IE new "security feature".

**Comment by Kuldeepnagar** [comment]
Hi barancev, 

Could you please suggest some workaround?

As number of tests are huge and It would take time to migrate them to Webdriver.

Thanks in Advance

**Comment by barancev** [comment]
Use older browser versions.
And migrate to WebDriver as soon as possible. There is no way to continue with RC.
