### ISSUE TITLE
Add %APPDATA%\..\Local\Mozilla Firefox\firefox.exe to the list of default places to check for Firefox

### ISSUE THREAD

**Issue by 1kastner** [SeleniumHQ/selenium#5015]
## Meta -
OS: Windows 10
Browser: Firefox
Driver: Python

## Expected Behavior -

Find a user-only installed firefox installation at `%APPDATA%\..\Local\Mozilla Firefox\firefox.exe`

## Actual Behavior -

Currently at [firefox_binary.py](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_binary.py) in the method `_default_windows_location` only the following are checked:

```
[os.getenv("PROGRAMFILES", r"C:\Program Files"),
os.getenv("PROGRAMFILES(X86)", r"C:\Program Files (x86)")]
```

But not the directory `%APPDATA%\..\Local` aka `C:\Users\CURRENT_USER\AppData\Local` where Firefox is installed if it is only installed for one user.

**Comment by lmtierney** [comment]
> Currently at firefox_binary.py in the method _default_windows_location only the following are checked:

This is only used for Legacy driver. With geckodriver, it finds the binary itself.

Please file an issue with geckodriver https://github.com/mozilla/geckodriver

**Comment by 1kastner** [comment]
Thanks for the helpful comment!
