### ISSUE TITLE
dict comprehension not available in Python 2.6

### ISSUE THREAD

**Issue by pabra** [SeleniumHQ/selenium#5018]
https://github.com/SeleniumHQ/selenium/blob/6e66b0513f022f1d555d8cab9d19d883274a46c4/py/selenium/webdriver/remote/webdriver.py#L991
https://github.com/SeleniumHQ/selenium/blob/6e66b0513f022f1d555d8cab9d19d883274a46c4/py/selenium/webdriver/remote/webdriver.py#L1031

see the PEP:
https://www.python.org/dev/peps/pep-0274/

**Comment by AutomatedTester** [comment]
As mentioned in the PR, 2.6. is not supported.

**Comment by pabra** [comment]
But your docs say Python 2.6 is supported:
https://github.com/SeleniumHQ/selenium/blob/b66efc8f47ccd43322075e070371f5fa0807b9a9/py/docs/source/index.rst#L29
