### ISSUE TITLE
Cannot run Safari Technology Preview with RemoteWebDriver

### ISSUE THREAD

**Issue by schmidtkp** [SeleniumHQ/selenium#5020]
## Meta -
OS:  macOS Sierra 10.12.6
Selenium Version:  v3.7.0 (Java client)
Browser:  Safari Technology Preview
Browser Version:  Release 43 (Safari 11.1, WebKit 12605.1.12)

## Expected Behavior -
Should be able to launch Safari Technology Preview via DesiredCapabilites and RemoteWebDriver after calling SafariOptions.setUseTechnologyPreview().
## Actual Behavior -
Setting technologyPreview flag has no effect on launching Safari Technology Preview. This ability last worked in v3.4.0 and has failed ever since.

I know SafariOptions.setUseTechnologyPreview() has been marked deprecated in v3.7.0, but it is still available for use, however is seems to be ignored and only launches the standard Safari browser.

I'm now only successful at getting Safari Technology Preview to launch if I call SafariDriver(SafariOptions).
## Steps to reproduce -
The following attempts FAIL to launch Safari Technology Preview for v3.5.x, 3.6.0 and 3.7.0):
```
DesiredCapabilities caps = DesiredCapabilities.safari();
SafariOptions safariOptions = new SafariOptions();
safariOptions.useCleanSession(true);
safariOptions.setUseTechnologyPreview(true);  <-- deprecated in v3.7.0 but still avaialble
caps.setCapability(SafariOptions.CAPABILITY, safariOptions);
RemoteWebDriver remoteWebDriver = new RemoteWebDriver(HubUrl(), caps);
```
```
DesiredCapabilities caps = DesiredCapabilities.safari();
caps.setCapability(SafariOptions.CAPABILITY, "{cleanSession: true, technologyPreview: true});
RemoteWebDriver remoteWebDriver = new RemoteWebDriver(HubUrl(), caps);
```

**Comment by barancev** [comment]
It seems that deprecating this option was a bad idea, it's important for remote case. But deprecation does not explain why it does not work.

**Comment by schmidtkp** [comment]
@barancev If there is any additional information/help I can provide, please let me know.

**Comment by namvuCosmo** [comment]
I'm facing the same problem. Last time it worked was 3.3.1 and 3.4.0, now only standard safari is opened. With the new API changes I don't see how STP can be open on remote Node. 
Just to be clear, @schmidtkp did you have to specify the -Dwebdriver.safari.driver to the STP driver binary when you launch selenium (node or local)? And I don't think there's anything to set the STP binary (like safari_bniary,..), right?

**Comment by barancev** [comment]
This issue will be fixed in version 3.8

**Comment by titusfortner** [comment]
@barancev I'm running on master and still having this issue.
This packet is giving me the system safari not the technology preview

```
2017-11-17 12:12:33 INFO Selenium    >>> http://127.0.0.1:4444/wd/hub/session | {"desiredCapabilities":{"browserName":"safari","version":"","platform":"MAC","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"safari.options":{"technologyPreview":true}},"capabilities":{"firstMatch":[{"browserName":"safari"}]}}
2017-11-17 12:12:35 INFO Selenium <- {"status":0,"sessionId":"49E318CE-A825-48BE-8124-28C389279BB8","value":{"applicationCacheEnabled":true,"rotatable":false,"databaseEnabled":true,"handlesAlerts":true,"version":"12604.3.5.1.1","cleanSession":true,"platform":"macOS","nativeEvents":true,"locationContextEnabled":false,"webStorageEnabled":true,"browserName":"safari","javascriptEnabled":true,"platformName":"macOS","cssSelectorsEnabled":true}}
```

**Comment by barancev** [comment]
@titusfortner I've just landed a patch 781c1c668d1ef44a81b8349882987f4df58082d0, try again, please.

**Comment by titusfortner** [comment]
@barancev yes, I can verify this works in master now. Thanks!

**Comment by chenry35** [comment]
Any news for the release date of the selenium standalone server 3.8 please? :)

**Comment by schmidtkp** [comment]
@barancev I'm still seeing failures in Java client v3.8.1. If I enable STP and pass the SafariOptions to RemoteWebDriver, I get:

`WebDriverException: Error forwarding the new session cannot find : Capabilities {browserName: safari, browserVersion: 11, platform: MAC ...`

Yet the Grid Console is showing the node configured as:

`capabilities: Capabilities {browserName: safari, browserVersion: 11, maxInstances: 1, node: http://localhost:5555, platform: MAC, platformName: MAC, se:CONFIG_UUID: a05a1288-0e0b-4e88-b2ac-518..., seleniumProtocol: WebDriver}`

**Side Note**: Calling:
`RegistrationRequest.build(gridNodeConfiguration)`
is adding additional **platform** capability even though the supplied gridNodeConfiguration Json has **platformName** defined. Don't know if this has any ill side-effect.

If I do **NOT** specify STP, I get the following error:

`SessionNotCreatedException: Unable to create new service: SafariDriverService`

Can this please be re-opened?

**Comment by titusfortner** [comment]
The standalone server code is working with Ruby, so if it isn't working in Java it will be an issue with the Client bindings, which I haven't tested or investigated.

**Comment by kool79** [comment]
It is an issue for me also (java, v3.8.1 When I created RemoteWebDriver with SafariOptions (on remote node) I get error:  
`SessionNotCreatedException: Unable to create new service: SafariDriverService`
When I use plain capabilities without SafariOptions  (browserName, platformName, browserVersion)  all works well

**Comment by kool79** [comment]
Have more info about error. I have the error "Unable to create new service: SafariDriverService" only when I supply `"port": 0` inside capability `"safari.options"`. When `"port"` is absent then no errors (safari successfully launched). Unfortunately we cannot neither change nor delete `"port"` property from wire when we use SafariOptions. It is included by default and equals to `0`. 
   Workaround is to use map and then attach it as `"safari.options"`:
```java
DesiredCapabilities dc = new DesiredCapabilities();
dc.setCapability(CapabilityType.BROWSER_NAME, "safari");
dc.setCapability(CapabilityType.PLATFORM_NAME, Platform.MAC);

Map<String, Object> opt = new TreeMap<>();
// opt.put("port", 0);  ->  failed with 0 or any other value.
opt.put("cleanSession", true);  // useless. Apple's safaridriver always creates clean session
opt.put("technologyPreview", false);

dc.setCapability("safari.options", opt);

RemoteWebDriver wd = new RemoteWebDriver(hub, dc);
```

When I set port, i.e for 
```java
Map<String, Object> opt = new TreeMap<>();
opt.put("port", 0);  
//opt.put("cleanSession", true);  // useless. Apple's safaridriver always creates clean session
// opt.put("technologyPreview", false);
```
then hub's console shows:
```
01:56:55.832 DEBUG - http-outgoing-12 >> "  "desiredCapabilities": {"browserName":"safari","platformName":"mac","safari.options":{"port":0},"se:CONFIG_UUID":"39a017bc-02cb-4049-acc
3-4f710653a332"},[\n]"
01:56:55.835 DEBUG - http-outgoing-12 >> "  "capabilities": {[\n]"
01:56:55.837 DEBUG - http-outgoing-12 >> "    "desiredCapabilities": {"browserName":"safari","platformName":"mac","safari.options":{"port":0},"se:CONFIG_UUID":"39a017bc-02cb-4049-a
cc3-4f710653a332"},[\n]"
01:56:55.839 DEBUG - http-outgoing-12 >> "    "firstMatch": [[\n]"
01:56:55.841 DEBUG - http-outgoing-12 >> "      {"browserName":"safari","platformName":"mac","se:CONFIG_UUID":"39a017bc-02cb-4049-acc3-4f710653a332"}[\n]"
01:56:55.843 DEBUG - http-outgoing-12 >> "    ][\n]"
01:56:55.845 DEBUG - http-outgoing-12 >> "  }[\n]"
01:56:55.848 DEBUG - http-outgoing-12 >> "}"
01:56:55.865 DEBUG - http-outgoing-12 << "HTTP/1.1 500 Server Error[\r][\n]"
01:56:55.865 DEBUG - http-outgoing-12 << "Content-Type: application/json;charset=utf-8[\r][\n]"
01:56:55.866 DEBUG - http-outgoing-12 << "Content-Length: 13396[\r][\n]"
01:56:55.868 DEBUG - http-outgoing-12 << "Server: Jetty(9.4.7.v20170914)[\r][\n]"
01:56:55.870 DEBUG - http-outgoing-12 << "[\r][\n]"
01:56:55.873 DEBUG - http-outgoing-12 << "{"value":{"stacktrace":"org.openqa.selenium.SessionNotCreatedException: Unable to create new service: SafariDriverService\nBuild info: ...
.... truncated : stacktrace is the same  as in my previous message
```
I tried to analyze where error can occur  (without debugging) but I did not find any issues in source code.
In any case I think we can remove deprecated  package-local method setPort() and completely remove "port" from wire.

**Comment by kool79** [comment]
@schmidtkp, DefaultCapabilityMatched do the additional filtration when safari browser with technologyPreview requested. Only nodes witch has slots with capability `"technologyPreview":true` are matched. So you node config should contain:
```json
{
  "browserName": "safari", 
  "browserVersion": "11", 
  "platform": "MAC",
  "technologyPreview":true
}
```
 But I think youl'll still have error `SessionNotCreatedException: Unable to create new service: SafariDriverService`

@barancev , can you look at this issue (see my prev. comment), because it is critical for Safari testing on grid. I've create related ticket #5307 which contains additional  issues/features for SafariOptions.

**Comment by schmidtkp** [comment]
@kool79 I don't think it is necessary/required to set **technologyPreview:true** in the node configuration. You do have to set it as part of the DesiredCapabilities via SafariOptions. When STP was working, I did not have to set anything in the node config, only in the DesiredCapabilities.

**Comment by barancev** [comment]
@schmidtkp Yes, @kool79 said truth, now it's required to specify "technologyPreview": true in a node config if you want it to run STP. By default it's set to false. The hub uses this capability to find a proper node that can run STP (that _declares_ it can run). This feature allows to have various nodes (with STP and with regular safari) in the same grid, and the hub will be able to choose a proper node for the passed capabilities.

**Comment by schmidtkp** [comment]
@barancev Thanks! Didn't know this changed.

**Comment by schmidtkp** [comment]
@kool79, @barancev I can confirm, after adding `"technologyPreview": true` to my node config, that I also get `SessionNotCreatedException: Unable to create new service: SafariDriverService` trying to run Safari on grid. This is with Java binding v3.8.1

**Comment by lucasvc** [comment]
I can confirm @kool79 says in [comment 352953296](), and not using `SafariOptions` works.
But today I saw this `INFO` logs:

    [junit] Jan 18, 2018 9:12:05 PM org.openqa.selenium.remote.DesiredCapabilities safari
    [junit] INFO: Using `new SafariOptions()` is preferred to `DesiredCapabilities.safari()`

I'm right thinking that if method `DesiredCapabilities.safari()` will be deprecated in the near future, this issue should be solved before?

**Comment by barancev** [comment]
I should note that I can't reproduce this issue. In the log below you can see that there is  a `port` option passed in capabilities and it does not prevent a driver to start.

(I understand that this option is useless, and it's already marked as deprecated and subject to be vanished soon, but I still want to get you know it works for me)

Driver initialization:
```
SafariOptions options = new SafariOptions().setUseTechnologyPreview(true);
WebDriver driver = new RemoteWebDriver(options);
```
Hub log:
```
00:23:38.485 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.10.0', revision: '8d0c109fb9'
00:23:38.487 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-03-06 00:23:39.134:INFO::main: Logging initialized @951ms to org.seleniumhq.jetty9.util.log.StdErrLog
00:23:39.273 INFO [Hub.start] - Selenium Grid hub is up and running
00:23:39.273 INFO [Hub.start] - Nodes should register to http://10.0.0.7:4444/grid/register/
00:23:39.273 INFO [Hub.start] - Clients should connect to http://10.0.0.7:4444/wd/hub
00:23:44.028 INFO [DefaultGridRegistry.add] - Registered a node http://10.0.0.7:5555
00:24:01.673 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: safari, safari.options: {cleanSession: false, port: 0, technologyPreview: true}}
00:24:01.680 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=ed347e26-108e-4084-9683-e8becdea350e, seleniumProtocol=WebDriver, technologyPreview=true, browserName=safari, maxInstances=1, platformName=MAC, platform=MAC}
```
Node log:
```
00:23:43.429 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.10.0', revision: '8d0c109fb9'
00:23:43.433 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 5555
2018-03-06 00:23:43.551:INFO::main: Logging initialized @458ms to org.seleniumhq.jetty9.util.log.StdErrLog
00:23:43.708 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 5555
00:23:43.708 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
00:23:43.716 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
00:23:43.716 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
00:23:44.035 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
00:23:44.087 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
00:24:01.833 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: safari, safari.options: {cleanSession: false, port: 0, technologyPreview: true}}
00:24:01.835 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.safari.SafariDriverService)
00:24:03.656 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
00:24:04.406 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 68DA92B2-F477-4853-AFDE-E9743A690CC3 (org.openqa.selenium.safari.SafariDriverService)
```

**Comment by namvuCosmo** [comment]
I've been testing with safari and safariTP using Selenium for a while now, and I always have 2 nodes (one for each safari) running on each High Sierra machine. With Selenium 3.10.0, if SafariOptions is being used, alongside with DesiredCapabilities like this:

**Comment by barancev** [comment]
FYI: tested on Safari technology preview version "Release 50 (Safari 11.2, WebKit 13606.1.5)"

**Comment by namvuCosmo** [comment]
Hi, I've been testing with safari and safariTP (among other browsers) using Selenium for awhile now, and I always have 2 nodes (one for each safari) on each of my High Sierra machine. With Selenium 3.10.0, if SafariOptions is being used alongside with DesiredCapabilities like this:
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setVersion(browser.getVersion());
capabilities.setCapability("platform", browser.getPlatform());
SafariOptions options = new SafariOptions();
options.setUseTechnologyPreview(true);
capabilities.setCapability(SafariOptions.CAPABILITY, options);
WebDriver driver = new RemoteWebDriver(new URL(browser.getRemoteAddress()),capabilities);
```

the hub will throw exception:
```
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {browserName: safari, name: iceTestTest, safari.options: {cleanSession: false, port: 0, technologyPreview: true}}
    at org.openqa.grid.internal.ProxySet.verifyAbilityToHandleDesiredCapabilities(ProxySet.java:153)
    at org.openqa.grid.internal.DefaultGridRegistry.addNewSessionRequest(DefaultGridRegistry.java:228)
    at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:110)
    at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
    at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
    at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
    at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
    at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
    at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
    at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
    at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
    at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
    at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
    at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
    at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
    at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
    at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
    at java.lang.Thread.run(Thread.java:745)

```
although the node does exist on the Grid. My way around this is to remove options.setUseTechnologyPreview(true), or the SafariOptions completely.

Testing with Safari 11.0.2 (136043.4.7.1.6) and STP Release 50 (Safari 11.2, WebKit 13606.1.5)

**Comment by schmidtkp** [comment]
I've confirmed this is _no longer_ an issue with:
- Selenium Java client bindings v3.10.0
- Safari web browser v11.0.3
- Safari Technology Preview release 51 (Safari v11.2)
