### ISSUE TITLE
Remote server - failure to get session on account of NullPointerException in org.openqa.selenium.remote.server.handler.NewSession.handle

### ISSUE THREAD

**Issue by SlyAtBest** [SeleniumHQ/selenium#5025]
## Meta -
OS:  Windows 7 Professional 64-bit

Selenium Version:  3.7.1

Browser:  Chrome

Browser Version:  62.0.3202.89 (64-bit)

Chrome Driver Version: 2.33.506120

## Expected Behavior -
1. Create jetty server and embed remote server
2. Create RemoteWebDriver instance and get session
3. Stop jetty server
## Actual Behavior -
1. Create jetty server and embed remote server
2. Creates RemoteWebDriver but throws a NullPointerException on line 66 of org.openqa.selenium.remote.server.handler.NewSession.handle when trying to get a new session.  I'm confident that it is not a ChromeDriver issue as it works perfectly in isolation.
## Steps to reproduce -
1. Download the attached zip containing the maven project 'selenium-test'  - [selenium-test.zip](https://github.com/SeleniumHQ/selenium/files/1450729/selenium-test.zip)
2. Import project into favoured IDE. 
3. Run the junit test com.clearswift.selenium_test.TestRemoteServer.java
4. The exception should be thrown.

N.B. The test will leave residual ChromeDriver.exe's running in the background if run multiple times.  I did try to prevent this but the nature of the exception being thrown appeared to stop me from closing the instance.

**Comment by barancev** [comment]
No idea what are you trying to acheve, but if you use WebDriverServlet instead of legacy DriverServlet the code will work well:
```
context.addServlet(WebDriverServlet.class, String.format("%s*", RELATIVE_PATH));
```

**Comment by SlyAtBest** [comment]
Spot on, using WebDriverServlet does resolve the issue thanks!
