### ISSUE TITLE
Request to update Change Log for Selenium C# 3.7.0 

### ISSUE THREAD

**Issue by AdvanceAutomation** [SeleniumHQ/selenium#5027]
1. Change Log for C# 3.7.0 needs to be updated on

https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG

2. On www.SeleniumHQ.org website links are still pointing to 3.6.0.  But Nuget is pointing to 3.7.0. This needs to be updated too.

**Comment by lmtierney** [comment]
SeleniumHQ is updated. @jimevans is aware that the CHANGELOG needs to be udpated and will get to it when he has time

**Comment by AdvanceAutomation** [comment]
@lmtierney  thank you. Will wait for @jimevans  to update.

**Comment by sunilpathak44** [comment]
I tried down loading selenium 3.7.0 for C# but only 1 folder with 3 files are displaying having  extension*.nupkg .
is it new correct or we are going to update *.jar files in it
please help

**Comment by AdvanceAutomation** [comment]
@sunilpathak44  what you are asking is more of question than an issue. Questions should be posted in Slenium user group.

Java uses jar files. C# has dll's.  What you see in the folder is correct. go to VS and reference those nupkg files.

For future question - join and ask in the Selenium user group-
https://groups.google.com/forum/#!forum/selenium-users
