### ISSUE TITLE
IEDriver's Element.isDisplayed() should ignore opacity

### ISSUE THREAD

**Issue by SevInf** [SeleniumHQ/selenium#503]
According to [W3C spec draft](https://w3c.github.io/webdriver/webdriver-spec.html#isdisplayed) `isDisplayed` method should not take opacity into account.
This is true for Firefox and Chrome drivers, [`checkShown_`](https://github.com/SeleniumHQ/selenium/blob/0a9cc30d576c7290dcd54ccfd54aff27058192ff/javascript/atoms/action.js#L52-L57) method in atoms also explicitly ignores opacity.

But for IEDriver [this is not the case](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/Element.cpp#L103). `ignoreOpacity` value was changed when fixing [#6827](https://code.google.com/p/selenium/issues/detail?id=6827), but I believe it was a mistake: this change had made IEDriver implementation inconsistent with other drivers and current spec draft.

**Comment by SevInf** [comment]
Related: https://code.google.com/p/selenium/issues/detail?id=7625

**Comment by jimevans** [comment]
Fixed in 698dc42.
