### ISSUE TITLE
Disconnectedundefined message is really confusing.

### ISSUE THREAD

**Issue by AlexShemeshWix** [SeleniumHQ/selenium#5030]
## Meta -
OS:  Windows
Selenium Version:  3.6.0
Browser:  IE 11
Browser Version:  11.1480

## Expected Behavior -
All test pass
## Actual Behavior -
I have Disconectedundefined error and my test suit fails.
## Steps to reproduce -

I have setup that consist of Slenium Grid . Several nodes that run Firefox, Chrome, IE10 on Windows and Safari 10 on MacOS.
Projects use Karma for e2e tests that are hooked up to Selenium grid.

I have this one project that constantly fails .
Its started with failures in Safari. 
I could not find errors in logs on any side of the setup. The only thing that was abnormal was error message Disconnectedundefined message in karma log.
Ive disconnected Safari browser .
The same issue appeared on IE couple of days later.

QUESTION:
How can i even debug such situation. 
Lack of error message is very disturbing, i cant blame developers since i cant point out problem.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by AlexShemeshWix** [comment]
I disagree.
Lack of proper error message is a problem.
The system behaves strange and there is no explanation on how to debug the problem.
So please provide some guidance to avoid such questions in the future

**Comment by barancev** [comment]
You did not provide a reproduction scenario, so we qualified this message as a question rather than a bug-report. Selenium is not a commercial tool, it has no official support channel, it's supported by community in the mentioned google group. Please send questions to this group.

**Comment by AlexShemeshWix** [comment]
My reproduction scenario includes production project with 2K tests. Jenkins
Cluster spread over 2 data centers.
Its kind of hard to duplicate.
My problem is Disconnectedundefined message which is not informative to say
the least.
Nobody answered my question in google group.
Its a simple bug. Please make sure that all errors during random Disconnect
have proper description. Undefined error is not good to troubleshoot
anything.

**Comment by barancev** [comment]
I'm sorry you feel pain caused by those failures. But please reread your report neutrally. Suppose you've received such a report about the software you develop -- could you "fix it"? Something has been disconnected... What disconnected from what? Was it Selenium at all who raised this exception? Can it be that selenium raised exception full of information, but Karma lost it? The issue report is not actionable in the current state. We can't fix this "simple bug" because we can't see what exactly is broken.

**Comment by AlexShemeshWix** [comment]
Thanks for response i really appreciate you spending time on my issue.
If it was my software i would recommend developer to enable highest level
of logging, and ask him to reproduce issue and send over logs.
I would study logs and point out that my software executed as expected.
My selenium configuration consist of Chrome , FF and IE nodes. Chrome and
FF are working ok. This problem happens on IE and Safari only.
So Selenium Hub is ok , its webdriver that would ot report some errors.
Im asking for guidance how to troubleshoot such issues.
Should i put sniffer and intercept all the communications between IE node
and selenium hub?
Should i check windows logs?
Should i inject NewRelic into selenium somehow and see if i can catch some
exceptions?

I need to localize case before i can submit reproducible scenario. I cant
just create JS project with 2000 tests. And my current setup runs ok on
1000 tests.
So please help me to localize the problem.
How can i get more detailed logs from selenium driver to be sure it works
ok?

**Comment by barancev** [comment]
Selenium is not a commercial tool, it has no official support channel, it's supported by community. Please send questions to the user group: https://groups.google.com/forum/#!forum/selenium-users.
