### ISSUE TITLE
Actions.MoveToElement throws StaleElementException on Element that is found again after a DOM refresh

### ISSUE THREAD

**Issue by realfaisalk** [SeleniumHQ/selenium#5032]
## Meta -
OS:  
Windows 10, v1703 build 15063.674
Selenium Version:  
v3.6.0
Browser:  
Chrome & Firefox 
Browser Version:  
v62.0.3202.75 (32-bit) & v56.0.2 (32-bit)

## Expected Behavior -
Actions.MoveToElement to not throw a StaleElementException when the element has been "found" again after a DOM refresh.
## Actual Behavior -
I move the mouse to an element, click on some other element, then navigate back.
I then "find" the element again and try to move the mouse to the element again where a StaleElementException is thrown.
This happens on both Chrome & FF.
```
public void CNN()
        {
            driver.Navigate().GoToUrl("http://www.cnn.com/");
            //Maximize the window so that the list can be gathered successfully.
            driver.Manage().Window.Maximize();

            //find the list
            By xPath = By.XPath("//div[@class='nav-menu-links']/a");
            IList<IWebElement> linkCollection = driver.FindElements(xPath);

            //Get the first tlink
            string locator = "//div[@class='nav-menu-links']/a[1]";
            IWebElement myLink = driver.FindElement(By.XPath(locator));

            //Move mouse to the 1st link, Click each link
            foreach (var item in linkCollection)
            {
                //Hover over the first link
                move.MoveToElement(myLink).Build().Perform();

                //Click on the link
                item.Click();

                //Go back
                driver.Navigate().Back();

                //Find the first link again
                myLink = driver.FindElement(By.XPath(locator));
            }
        }
```

Exception thrown: 'OpenQA.Selenium.StaleElementReferenceException' in WebDriver.dll
An exception of type 'OpenQA.Selenium.StaleElementReferenceException' occurred in WebDriver.dll but was not handled in user code
The element reference of <a class="nav-menu-links__link"> stale: either the element is no longer attached to the DOM or the page has been refreshed

**Comment by lmtierney** [comment]
The dotnet bindings do not clear out the previous actions after performing them. This means that your first action is still stored on the first element which is now stale. You need to re-init your Actions object each time you want to perform anything unless you want to do it to the EXACT same elements as the last time.

**Comment by realfaisalk** [comment]
@lmtierney wierd :o; but thanks
