### ISSUE TITLE
AbstractConnector:main: Stopped ServerConnector error for first time running HTML suite

### ISSUE THREAD

**Issue by giznaj** [SeleniumHQ/selenium#5033]
## Meta -
OS:  Windows 7

**Selenium Version:**  Selenium Server 3.7.0, HTML Runner 3.7.0, Jenkins 2.89

**Browser:**  Internet Explorer

**Browser Version:**  11.674.15063.0 update 11.0.47

## Expected Behavior -
The test suite (HTML Test Suite) should run the first time without triggering the exception/error

## Actual Behavior -
the first time you run the test suite the exception/error is triggered.

## Steps to reproduce -
**Pre-condition:** There is a project on Jenkins that has a build step to run/execute a HTML Runner test suite.

1. Login to Jenkins with an account that can run the HTML Runner test suite 
2. Build the project 
3. Navigate to the console output of the build

**Post-condition:**
If you re-run the project immediately after you will be able to successfully run it (no exception/error)

**Observations:**
If you wait a short period of time like 10 to 20 minutes after you see the exception/error you can build the project and not see the error.  I do not know how much time has to elapse from the first attempt that fails to see the very next attempt fail.  However, every next day that I come in to run the test, it fails for the first time and when I run again it passes as expected.  This makes it hard to determine if it is TIME or CALENDAR DATE that is the trigger to restart issue.

No matter what browser I have specified in the build/project definition the same actual behaviour happens when the project is built for the first time.

I have seen this error since at least 2.7X of Jenkins and since at least 3.3.0 of the HTML Runner

**Logs/errors:**
12:31:44 2017-11-08 12:31:44.556:INFO:osjs.AbstractConnector:main: Started ServerConnector@779568{HTTP/1.1,[http/1.1]}{0.0.0.0:26980}
12:31:44 2017-11-08 12:31:44.556:INFO:osjs.Server:main: Started @5430ms
12:31:44 2017-11-08 12:31:44.603:INFO:osjs.AbstractConnector:main: Stopped ServerConnector@779568{HTTP/1.1,[http/1.1]}{0.0.0.0:26980}
12:31:44 2017-11-08 12:31:44.603:INFO:osjsh.ContextHandler:main: Stopped o.s.j.s.h.ContextHandler@caa560{/tests,null,UNAVAILABLE}
12:32:22 Nov 08, 2017 12:32:22 PM org.openqa.selenium.server.htmlrunner.HTMLLauncher mainInt
12:32:22 WARNING: Test of browser failed: *iexplore

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version

**Comment by giznaj** [comment]
I opened this a year ago and you close it with "Check IDE new version, this version is deprecated".  The new version is not even in scope for this error as the new version of selenium ide does not provide HTML files for Jenkins to run using the plugin mentioned.  

Don't worry, we've moved on but you have to understand that response is not taken well.

**Comment by barancev** [comment]
Sorry we could not help you. Yes, new version does not resolve this issue. But the old version of Selenium IDE is deprecated anyway, because it couldn't be adopted to new browser versions without total rework.

Yes, the new version of Selenium IDE stores scenarios in a new (JSON based) format, there is a console runner for the files in this format, and we hope someone will implement a Jenkins plugin that supports this new runner.

**Comment by giznaj** [comment]
Thanks barancev.  I appreciate you responding to me.  I too hope that someone takes that one.  It was a really good feature.
