### ISSUE TITLE
Ability to get the By from an already found IWebElement

### ISSUE THREAD

**Issue by JohnGagliardi** [SeleniumHQ/selenium#5034]
Here is the scenario in which this would be useful.

I have been passed a By as a parameter to a function. I can use this to find a child element under the element found using the passed By. I cannot, without some workaround, get the By for the child element which I would need to use some functions.

Note, this is purely for ease of coding. I could build out the child By where a generate the parent By but because the parent By is used across many functions, and is dynamic, it makes it easier and cleaner (way fewer variables) to do it this way.

here is some C# code that demos the issue:

    public void SelectValueFromDropdown(string value, By parent)
    {
       IWebElement childElement= this.WebDriver.FindElement(parent).FindElement(By.CssSelector("td:nth-child(3) > select"));

       this.WebDriver.SelectDropDownOption([By for Child element goes here], value)
    }

Please let me know if I am missing some already built functionality to handle this.

Thanks

**Comment by barancev** [comment]
What's the use case? Why can't you use parent web element itself?
SelectDropDownOption(childElement, value)

**Comment by JohnGagliardi** [comment]
Your comment pointed out the solution I was looking for. Not sure how I missed this.

Thanks for the help.
