### ISSUE TITLE
selenium.common.exceptions.ElementNotInteractableException: Message: 

### ISSUE THREAD

**Issue by JKAK47** [SeleniumHQ/selenium#5037]
hi , i have some problems when i try to visit 12306.cn and try to book a ticket, the errors show that 
Traceback (most recent call last):
  File "D:/Dev/WorkStation/PyProjectWorkstation/HelloWorld/12306.py", line 33, in <module>
    driver.find_element_by_css_selector("[title=杭州]").click()
  File "C:\fastDev\Python3_5_2\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\fastDev\Python3_5_2\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\fastDev\Python3_5_2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\fastDev\Python3_5_2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: 
i added sleep in the codes but this problem still exist, could you please have a look? many thanks!

#!/usr/bin/env python3
# --*-- coding utf-8 --*--
#Python3.5.2
# coding:utf-8
__author__='PengRong'

from selenium import webdriver
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait  # available since 2.4.0
import selenium.webdriver.common.by as bb
from selenium import webdriver
import time

driver=webdriver.Firefox()
driver.set_window_size(1080,900)
driver.implicitly_wait(15)
driver.get("https://kyfw.12306.cn")

driver.find_element_by_id("login_user").click()
#driver.find_element_by_id("username").send_keys("xxxx@qq.com")
#driver.find_element_by_id("password").send_keys("xxxxxxxx")

# this is for click the 'book titkcet' button
driver.find_element_by_link_text("车票预订").click()

time.sleep(3)
#select depart city
# for this step, there is a small problem, the city list can not be found in the source codes at first, then i use **setTimeout(function(debugger;),5000) in Chrome**, in that way i found **[title=杭州]**
driver.find_element_by_id("fromStationText").click()
driver.find_element_by_css_selector("[title=杭州]").click()

time.sleep(3)
#select destination city
driver.find_element_by_id("toStationText").click()
driver.find_element_by_css_selector("[title=南京]").click()

time.sleep(3)
#depart date
driver.find_element_by_id("train_date").click()
driver.find_element_by_css_selector("body>div.cal-wrap>div:nth-child(1)>div.cal-cm>div:nth-child(22)>div").click()

time.sleep(3)
#select the seat type
driver.find_element_by_css_selector("#_ul_station_train_code>li:first-child").click()
#  #_ul_station_train_code > li:nth-child(1)  from firefox

#click "query" button
driver.find_element_by_id("query_ticket")

#select the second-class seat
seat=driver.find_element_by_id("ZE_56000G431400")
seat.click()
print(seat.text)

#refresh the website to see if there are tickets available, if there are, print that we have tickets, if no, keep refreshing
while True:
	try:
		driver.find_element_by_id("query_ticket").click()
		seat = driver.find_element_by_id( "ZE_56000G431400" )
		seat.click( )
		if seat.text in['无','--']:
			print('暂时无票，继续查询')
			time.sleep(2)
		else:
			print('有票')
			break
	except:
		pass

**Comment by barancev** [comment]
Please attach the complete log with full error message and stacktrace.

**Comment by JKAK47** [comment]
![image](https://user-images.githubusercontent.com/12482698/32592958-ea9d8470-c560-11e7-87a1-79d285ba1534.png)

**Comment by JKAK47** [comment]
hi， the full errors information are shown above, thanks!

**Comment by barancev** [comment]
Weird, the log looks inclomplete, the most interesting part is cut out.

OK, then, tell what version of Selenium python library do you use and what version of geckodriver?

**Comment by JKAK47** [comment]
![image](https://user-images.githubusercontent.com/12482698/32605021-c2b5b354-c58a-11e7-899f-ccf4be00cc08.png)

![image](https://user-images.githubusercontent.com/12482698/32605058-e4d8d1be-c58a-11e7-8361-ef20ad5ba7df.png)

**Comment by barancev** [comment]
Upgrade the client library to the latest version (3.7 at the moment) and retest.

**Comment by barancev** [comment]
Please let's know if the issue is still actual in the latest client library (that is already 3.8.1 at the moment)

**Comment by barancev** [comment]
We actually need to know if this issue is still actual in the client version 3.8.

**Comment by tarasvaskiv** [comment]
Still got it. pip selenium is newest. Geckodriver is 0.19.1 version 
file:///home/coder/Pictures/Screenshot%20from%202017-12-09%2000-52-44.png

**Comment by zouzhenglu** [comment]
I have this problem, too. 
Env: python:3.6.3

**Comment by barancev** [comment]
Closing the issue as there were no response from the author, hope the issue had been fixed by updrading Selenium.
