### ISSUE TITLE
Add information to the wiki regarding InternetExplorerDriver

### ISSUE THREAD

**Issue by pbne04** [SeleniumHQ/selenium#5038]
Using Visual Studio 2017 with C# and latest nuget packages, I have experienced problems getting the InternetExplorerDriver working, even though I have made sure to implement the required configuration.

I have found that starting Visual Studio in Administrator Mode will make the driver work as intended, but I feel that this information should be added to the wiki under 'Required Configuration'.

https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#user-content-required-configuration

I am not certain if this is only a problem with Internet Explorer.

**Comment by hazmeister** [comment]
Running as admin shouldn't be a prerequisite for getting internet explorer to run- what problems were you getting when running visual studio with your local account?

**Comment by pbne04** [comment]
This is the error:
IEDriver starts fine:

Started InternetExplorerDriver server (32-bit)
3.7.0.0
Listening on port 59744
Only local connections are allowed

Browser starts up but never connects:

Can’t reach this page
•Make sure the web address http://localhost:62612 is correct

Unit test error:
OpenQA.Selenium.NoSuchWindowException : Currently focused window has been closed.
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at 
   ...

If I start visual studio in administrator mode and run my test, I have no problems making it work.

**Comment by jimevans** [comment]
This is almost certainly a Protected Mode issue. The fact that running as administrator resolved the issue is more evidence to support that. We will not be adding advisories to the wiki to run as administrator.

**Comment by barancev** [comment]
If you have all Protected mode checkbox "off", please set them all "on" and try again if this helps?

**Comment by pbne04** [comment]
Sorry for the late reply.
In my setup I followed the instructions from the wiki: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

..but I guess I must have missed something, because I tried the same setup on a different machine, and it works as intended.

Thank you and sorry to waste your time :)
