### ISSUE TITLE
blurring an input field does not work on linux/firefox/ssh

### ISSUE THREAD

**Issue by xzh1** [SeleniumHQ/selenium#504]
I got an issue with running selenium in a Ubuntu 14 Linux box.

I was using firefox 37 and selenium JVM 2.45.

I was trying to blur an input after some value was sent there.

To do this, I tried:

driver.findElement(By.id("my element ID")).sendKeys(Keys.Tab)

and:

executing the JavaScript document.getElementById('my element ID').blur(); with the Selenium JS execution feature.

When I have GUI, both ways run smoothly. However, when I use DISPLAY=:0 option to run my test in a ssh session, neither ways worked any more.

Anyone knows any work around for this issue?

Thanks in advance!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by xzh1** [comment]
I have put the question in the Selenium Google group. However, I kind of suspecting this is a issue from the Selenium firefox driver as I tried the two way I mentioned on Windows (GUI or ssh session) and Linux with GUI, they both work fine. Only Linux ssh session case is not working...

**Comment by barancev** [comment]
Do you run the browser in an xvfb (or other virtual x-server) session or pure headless? The latter is explicitly not supported. A browser is a GUI application and it needs GUI event queue to work properly.

**Comment by xzh1** [comment]
It is not pure headless. I tried this command: xdpyinfo -display :0 >/dev/null 2>&1 && echo "In use" || echo "Free" which shows me the remote browser does have a virtual GUI to run.
