### ISSUE TITLE
GeckoDriver randomly returns connection refused error

### ISSUE THREAD

**Issue by ehhc** [SeleniumHQ/selenium#5040]
Hi,
I am using the robotframework for my gui tests. The robotframework is a wrapper for a lot of testing libraries e.g. selenium for web tests. Unfortunately I have the following issue and no idea what might cause it: In my test environment my tests randomly fail because connection refused exceptions (see stacktrace below).
I’ve already asked the maintainer of the corresponding robotframework library but he has no idea neither and guessed that it might be a selenium problem.
I’m using a CentOS 7 system with the newest available Firefox Version (Firefox 52) and the belonging GeckoDriver Version (geckoDriver v0.17). 
My initial thought was that I might use an outdated setup, but Firefox 52 is the newest version available for Centos 7 and is the official supported one. The GeckoDriver Version can’t be updated as well because the newer versions don’t support Firefox 52.  Updating the Browser and the GeckoDriver isn’t a possible option therefore..
Do you have any ideas what might cause my problem? As I said it only happens randomly so that I can’t point to a concrete cause.. Any ideas? I don’t even have an idea how to isolate the cause of my problem any further..
Thanks in advance for your help
```
org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'jenkins-slave', ip: xxx', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.26.2.el7.x86_64', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x57af6d - backtrace::backtrace::trace::h59229d13f6a8837d
   1:           0x57b0c2 - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:           0x4472fc - webdriver::error::WebDriverError::new::h0b226f62ff19e120
   3:           0x4514c1 - geckodriver::marionette::MarionetteHandler::create_connection::hd468f55550be3626
   4:           0x426854 - <webdriver::server::Dispatcher<T, U>>::run::h62323eaff3e71b8c
   5:           0x40935c - std::panicking::try::do_call::hb7e6ff6d130a72cf
   6:           0x5de23a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   7:           0x41c003 - <F as alloc::boxed::FnBox<A>>::call_box::hd6ceeda495c4fa0e
   8:           0x5d68d4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84

```

**Comment by curtisy1** [comment]
This looks like a Gecko-specific issue to me. Connection refused in this context probably has to do with geckodriver panicking for some reason.

Do you have a specific test that always fails or is it completely random?

Also can you get a tracelog? If you don't know how to do that, feel free to ask.

**Comment by ehhc** [comment]
Hi,
thanks for your answer. The problem is that i don’t use selenium directly but thru the robotframework as a wrapper. The stacktrace above is all i what i get that’s connected to selenium. There is more but i guess it’s part of the wrapper library. Anyway: you can find the full for me available stacktrace in this issue in the corresponding robotframework library:  https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/issues/21
Yeah.. unfortunately it only happens randomly. If i could give you a reproducible test i would be a huge step forward to finding the source of the problem.. but i can’t.. Do you have any ideas how to isolate the issue more?
Thanks again

**Comment by cgoldberg** [comment]
I highly recommend you upgrade all components (selenium/geckodriver/firefox) rather than trying to configure everything with old versions.

Firefox 52 is the newest version available for Centos 7
just grab the latest firefox tarball from mozilla: http://ftp.mozilla.org/pub/firefox/releases

**Comment by curtisy1** [comment]
@ehhc I guess the robotframework allows setting command line options somehow. If so, you could add -v (for verbose which should print a lot of debugging information to stdout) to geckodriver. Maybe if we get a complete trace-level log we can further pin down the problem

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

For issues, please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions).

**Comment by ehhc** [comment]
I have upgraded to Firefox 57 and geckodriver v0.19.1. Unfortunately the issue still persists. But instead of "Connection refused" i get a "Process unexpectedly closed with status: 1" error message randomly now..

I don't know why you see it as a question instead of a bug... There is a stacktrace and a error so for me it looks like an issue..
