### ISSUE TITLE
Unable to reference SelectElement class in C#

### ISSUE THREAD

**Issue by thyclouds** [SeleniumHQ/selenium#5045]
## Meta -
OS:  
Windows 10
Selenium Version: 
3.7
Browser:  
Firefox

Browser Version:  
56.02 (64-bit)

## Expected Behavior -

Writing a simple interaction with a website in C#, I'm intending to locate a Select element and then get all of it's possible values.

```
using System;
using System.Collections;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;

class GetData
{
    static void Main(string[] args)
    {
        using (IWebDriver driver = new FirefoxDriver())
        {
            //Notice navigation is slightly different than the Java version
            //This is because 'get' is a keyword in C#
            driver.Navigate().GoToUrl("https://site-name.com/url");
            IWebElement element01 =driver.FindElement(By.XPath("//*[@id='element-id']/select"));
            SelectElement selectList = new SelectElement(element01);
            IList<IWebElement> options = selectList.Options;
        }
    }
}
```

## Actual Behavior -

I am unable to pull in SelectElement class into the namespace.
I have issued "using OpenQA.Selenium.Support.UI;" but it doesn't work.
I have used Visual Studio 2017 and vs Code to the same result.
I have tried all supported frameworks .Net and .Net Core to the same result.
Tried 3.6 to no avail.
I have used JetBrains to disassemble webdriver.dll and I do see SelectElement class.
So the program doesn't compile.
For that matter I'm unable to reference any classes in OpenQA.Selenium.Support.UI

Please help to figure out how to pull this class into the namespace.
Thank you in advance!

## Steps to reproduce -

Use code above, install 3.7 version using NuGet and you will be able to get to this result.

**Comment by jimevans** [comment]
`SelectElement` is not now, nor has it ever been part of WebDriver.dll. You need to add a reference to the `Selenium.Support` package.

**Comment by thyclouds** [comment]
Excellent! Resolved now!
