### ISSUE TITLE
Cannot set Firefox log level in 3.7.1

### ISSUE THREAD

**Issue by nkonev** [SeleniumHQ/selenium#5047]
## Meta -
OS:  
Fedora Linux XFCE 24
Selenium Version:  
3.7.1
Browser:  
Firefox

Browser Version:  
56.0.2

Firefox Driver version:
0.19.1

## Expected Behavior -
When I set log level to info
```
                // firefox
                FirefoxDriverManager.getInstance().version(0.19.1).setup(); // download executables if need and set System.properties
                // https://developer.mozilla.org/en-US/Firefox/Headless_mode
                FirefoxOptions firefoxOptions = new FirefoxOptions();
                firefoxOptions.setLogLevel(FirefoxDriverLogLevel.INFO);
                driver = new FirefoxDriver(firefoxOptions);
```
I expect that log level was set to info.

## Actual Behavior -
Anyway log level don't sets.
console
```
1510508640285	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
```
(https://travis-ci.org/nkonev/blog/builds/301013382#L4774)

## Steps to reproduce -
See code above.

I catched this bug when I updated from selenium 3.7.0 to 3.7.1.
Log sets correct in selenium 3.7.0 (https://travis-ci.org/nkonev/blog/builds/301005993#L4201)

**Comment by barancev** [comment]
Unfortunately, some messages from marionette and browser leak to the log despite the log level settings. Geckodriver team is working on this issue. Setting log level to FATAL will suppress more messages.

If you want to suppress all log from geckodriver and firefox, there is a simple workaround:
```System.setProperty("webdriver.firefox.logfile", "/dev/null");```
Also you can set this property using Java -D command line option.

**Comment by barancev** [comment]
FYI links to the related bug-reports in Mozilla tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1384956
https://bugzilla.mozilla.org/show_bug.cgi?id=1399441

**Comment by nkonev** [comment]
@barancev But why it works in 3.7.0 and stopped in 3.7.1 ?

I open diff https://github.com/SeleniumHQ/selenium/compare/2321c73...b66efc8#diff-1f7999f4b4a8e73dc9c72441017cfeb6L176

and `service.sendOutputTo(ByteStreams.nullOutputStream());` changed to `service.sendOutputTo(System.err);`.

I think this change produces this bug. I check it with breakpoint at this line.

**Comment by barancev** [comment]
Sending everything to /dev/null by default is a bad idea. It was done in 3.7.0 by mistake. I tried to hide logs produced by legacy firefox driver only. There was no intention to change geckodriver behavior. The behaviour was broken in 80d35e0a7b710864fd12da567d0d0ba499b23371 and reslored back in 373261bd0d6e6588e59fc55bc27350f1759f7cf9

Suppressing DEBUG messages from marionette should be implemented in geckodriver, not in Selenium client libs.
