### ISSUE TITLE
Broken link to build.desc in Automation Atoms Wiki

### ISSUE THREAD

**Issue by michaelfward** [SeleniumHQ/selenium#5048]
The [Automation Atoms Wiki page](https://github.com/SeleniumHQ/selenium/wiki/Automation-Atoms) contains a broken [link](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver-atoms/build.desc) at the very end of the introductory page.

Full Link HREF -

 https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver-atoms/build.desc

**Comment by michaelfward** [comment]
See the above commit [941154b](https://github.com/michaelfward/selenium/commit/941154bc7f995a9330d737924b8db23b48733e4d) on my forked version of the repo for the update *I think* will fix the issue.

**Comment by p0deje** [comment]
Fixed, thank you!
