### ISSUE TITLE
Not able to execute TestNG tests in order wise.

### ISSUE THREAD

**Issue by Aditya1209** [SeleniumHQ/selenium#5049]
I want to execute my TestNG Class tests in order wise how they have written from to to bottom. To achive this right now i am using **priority** for each test in one testNG class.

Sample TestNg Class:
FirsttestNG.class assume this class is having 3 tests as shown below
@Test(priority=1)
public void test1()
{
}
@Test(priority=2)
public void test2()
{
}
@Test(priority=3)
public void test3()
{
}

SecondTestNG.class assume this class also having 3 tests
@Test(priority=1)
public void secondtest1()
{
}
@Test(priority=2)
public void secondtest2()
{
}
@Test(priority=3)
public void secondtest3()
{
}

When i execute above mentioned classes alone from testNg xml file the out put will be as shown below.
for FirstTestNgClass out put : first test1 method will execute then test2 follwed by test3.
for SecondtestNg class also execution sequence will be same.

Now the problem is when i execute both FirstTestNG and SecondTestNG Classes at a time form testNg xml then execution sequence will be 
**Out Put**
test1
secondtest1
test2
secondtest2 
test3
secondtest3

but i want as shown below:
**out Put:** 
test1
test2
test3
secondtest1
secondtest2
secondtest3

**can we achive this ?**

**Comment by barancev** [comment]
Thers is nothing to Selneium here, send this question to TestNG user group.
