### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{firefox_binary=

### ISSUE THREAD

**Issue by Udayarajan** [SeleniumHQ/selenium#5053]
## Meta -

I am getting the following error 

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{firefox_binary=/Program Files/Mozilla Firefox/firefox.exe, moz:firefoxOptions={binary=Optional[FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe)], args=[], legacy=null, logLevel=null, prefs={}, profile=null}}], required capabilities = Capabilities [{firefox_binary=/Program Files/Mozilla Firefox/firefox.exe, moz:firefoxOptions={binary=Optional[FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe)], args=[], legacy=null, logLevel=null, prefs={}, profile=null}}]

OS : Windows 7 Proffessional 64 bit.

Firefox Version 56.0.2

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
