### ISSUE TITLE
chrome_options not working in python since 3.7.0

### ISSUE THREAD

**Issue by jolting** [SeleniumHQ/selenium#5055]
I noticed my chrome_options weren't working in 3.7.0, but 3.6.0 worked.

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.binary_location = 'mycefapp.exe'

driver = webdriver.Chrome(chrome_options=chrome_options)
```
The binary_location was getting ignored.

I was looking at this commit:
https://github.com/SeleniumHQ/selenium/commit/3578c0faee107dc0faef164a4acf02b916caa2be#diff-10f65ccee5b377aa8f2b3fde4bf566f8

Does it have something to do with this?
https://github.com/SeleniumHQ/selenium/blob/7b8ce0abd138f47af0650079ed7e51ae8ac02c88/java/server/src/org/openqa/selenium/remote/server/ActiveSessionFactory.java#L82

**Comment by barancev** [comment]
What chromedriver version do you use?

**Comment by barancev** [comment]
And why are you looking at the server code? Do you use RemoteWebDriver or ChromeDriver (as stated in the original report)?

**Comment by jolting** [comment]
I don't know the selenium code base. Just looking for hints. I'll get back to you on the chrome driver version.

**Comment by lmtierney** [comment]
This sounds like you're using an old chromedriver version. The code changed in `3.7.0` to the new options key of `goog:chromeOptions` which is only supported in chromedriver `2.32` and later. If you NEED to use an older chromedriver, you need to either downgrade your bindings or send a raw dictionary:

```
driver = webdriver.Chrome(desired_capabilities={"chromeOptions": {"binary": 'mycefapp.exe'} })
```

**Comment by jolting** [comment]
Thanks!!! That worked.

**Comment by xfalcon727** [comment]
Using this:

driver = webdriver.Chrome(desired_capabilities={"chromeOptions": {"binary": 'mycefapp.exe'} })

How I do pass "user-data-dir" as an argument in the raw dictionary instead of "binary" here?
