### ISSUE TITLE
Could not create a session: The Safari instance is already paired with another WebDriver session.

### ISSUE THREAD

**Issue by mikhail-yarosh** [SeleniumHQ/selenium#5057]
Can't start few sessions via RemoteWebDriver on node with 

MacOS El Capitan.
Hub and node both on selenium-server-standalone-3.7.1.jar
Safari v 11.0.1

Trying to run multiple safari tests on one node in parallel.

## Expected Behavior -
Few Safari instances should be run and work simultaneously by one for each test.

## Actual Behavior -
Hub console shows few locked Safari instances, but node start and use the only, the rest of tests fails with 
"org.openqa.selenium.SessionNotCreatedException: Could not create a session: The Safari instance is already paired with another WebDriver session. (WARNING: The server did not provide any stacktrace information)"

**ALSO**: 
  505 s000  S      0:00.05 /usr/bin/safaridriver --port 44508
  760 s000  S      0:00.04 /usr/bin/safaridriver --port 23656
  764 s000  S      0:00.04 /usr/bin/safaridriver --port 34016
  773 s000  S      0:00.04 /usr/bin/safaridriver --port 41575
  776 s000  S      0:00.04 /usr/bin/safaridriver --port 46705
  787 s000  S      0:00.05 /usr/bin/safaridriver --port 2775
  790 s000  S      0:00.04 /usr/bin/safaridriver --port 10923
This instances are alive even after restarting of grid. Looks like node/hub not terminating safaraidriver instances, after usage.

## Steps to reproduce -
Hub started with config:
`java -jar selenium-server-standalone-3.7.1.jar -role hub  -log hub.log -debug `

Node's config:
`java -jar selenium-server-standalone-3.7.1.jar -role node -hub http://IP_ADDRESS_HERE:4444/grid/register/ -browser "browserName=safari,setjavascriptEnabled=true,acceptSslCerts=true,maxInstances=15,Platform=MAC" -port 5555 -log node.log
`
And try run few tests on this grid, using:
```
DesiredCapabilities capability = DesiredCapabilities.safari();
RemoteWebDriver driver = new RemoteWebDriver(new URL("http://192.168.3.75:4444/wd/hub"), capability);
```

**Comment by namvuCosmo** [comment]
I don't think the safaridriver supports more than 1 instance at a time for automated testing. The same limitation applies for Microsoft edge as far as I know.

**Comment by mikhail-yarosh** [comment]
@namvuCosmo ok, what approach should i use to run few instances at a time?

**Comment by namvuCosmo** [comment]
What I'm doing now is either on several machines, physical or virtual...
You might need to set maxInstances to 1, or just remove that.

**Comment by mikhail-yarosh** [comment]
@namvuCosmo so, for now, selenium unable to use more than one safaridriver instance and can't properly kill them?

**Comment by namvuCosmo** [comment]
It's the driver which can't initiate more than one instance of safari. Once
the test is done, the browser intance can be cleaned properly and you can
schedule another one to be opened up after. Selenium itself merely
transfers the request to the driver.

**Comment by mikhail-yarosh** [comment]
@namvuCosmo understood. TY.

**Comment by iphysresearch** [comment]
Just quit your safari browser before your test.
When doing so, It works fine for me...
