### ISSUE TITLE
setValue is omitting digit 3 while login using selenium and mochajs

### ISSUE THREAD

**Issue by suwarna-wade** [SeleniumHQ/selenium#5058]
Meta:
selenium-standalone: 3.4.0
chromedriver: 2.38
mocha: 3.2.0,
webdriverio: 4.5.2
npm: 5.5.1
node: v8.4.0
OS: mac 10.13.1

`loginSU(data) { this.withPass.click() //const dtls = Object.assign({}, loginDtls) b.pause(2000) this.phone.setValue("9833445678") b.pause(2000) this.password.setValue("123456") this.loginBtn.click() }
`
This is my login function which I am calling in my index.js file

`it('should select' +' '+ service + ' '+' service and ask for login if owner is not logged in',()=>{ if(Homepage.loginModal.isVisible() == true){ Homepage.loginSU() b.debug() assert.equal(Homepage.prop_pic.isVisible(), true) } else{ console.log('user is already logged in') } })
`

Issue: When I run the test, it enters the number and password omitting digit 3 due to which the test case is filling.
<img width="360" alt="screenshot at nov 15 16-23-09" src="https://user-images.githubusercontent.com/24934465/32832875-0334971e-ca23-11e7-80ea-563d6ed7795d.png">
Kindly help with the issue as I do not find any related issue on stack.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ASYB** [comment]
Even we are facing the same issue, when there is digit 3 in the input value it will not take digit 3 alone

when you input 33412 it will take only 412
when you input 33333 it will take blank

**Comment by barancev** [comment]
@ASYB What OS do you use?

**Comment by LvivEchoes** [comment]
The same here!

I am using OS X, Selenium 3.6.0

**Comment by barancev** [comment]
This issue should be reported to chromedriver: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by LvivEchoes** [comment]
@barancev 

But the same behavior on geckodriver?

It could be the same issues in the same time in both drivers ?
