### ISSUE TITLE
have an error where running example in Getting-Started

### ISSUE THREAD

**Issue by gezhihui** [SeleniumHQ/selenium#5059]
have an error where running example in Getting-Started as below link:
https://github.com/SeleniumHQ/selenium/wiki/Getting-Started

error as below:
"C:\Program Files\Java\jdk-9.0.1\bin\java" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\lib\idea_rt.jar=53148:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\bin" -Dfile.encoding=UTF-8 -classpath C:\selenium-server-standalone-3.7.1.jar;F:\selenium\out\production\selenium main.java.Example
错误: 找不到或无法加载主类 main.java.Example
原因: java.lang.ClassNotFoundException: main.java.Example

Process finished with exit code 1

Do you have an suggest about that ?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
