### ISSUE TITLE
Selenium script was working fine in windows 7 and not working in windows 10, Also getting "Nosuch Element exception"

### ISSUE THREAD

**Issue by manoece90** [SeleniumHQ/selenium#5060]
## Meta -
OS:  Windows 10

Selenium Version:  3.6.0.0

Browser:  Internet Explorer

Browser Version:  11

**Comment by AdvanceAutomation** [comment]
@manoece90  Need more information.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
