### ISSUE TITLE
I Can't set browserName for FirefoxDriver

### ISSUE THREAD

**Issue by Lonckaster** [SeleniumHQ/selenium#5063]
## System

Gecko Driver Version: 18.0
Platform: Win 10
Firefox: 54.0.1
Selenium WebDriver: 3.7.0
Program Language: C#
## Issue

I have some problems with modified FireFox browser. When the Browser opens and I get an error:

> **["System.ArgumentException" in WebDriver.dll]** TypeError: Given browserName [object String] "firefox", but my name is [object String] "anotherbrowser"

I think, it's because of browser's name "anotherbrowser" instead of "firefox" in it's binary code.

So I found the solution on **Java**:

        FirefoxOptions options = new FirefoxOptions();
        options.setBinary("Path to browser binary");
        options.setCapability("browserName", "anotherbrowser");
        options.setCapability("marionette", false);
        driver = new FirefoxDriver(options);
I tested it, and its work fine. But I need on **C#**, so I tried to rewrite it: **(1st code)**

        DesiredCapabilities cap = DesiredCapabilities.Firefox();
        cap.SetCapability("firefox_binary", @"Path to Browser");
        cap.SetCapability(CapabilityType.BrowserName, "anotherbrowser");
        IWebDriver driver = new FirefoxDriver(cap);
I run the program and I got an error:

> **["System.ArgumentException" in WebDriver.dll]** There is already an option for the browserName capability. Please use the instead.

So I re-wrote my code: **(2nd code)**

        DesiredCapabilities cap = new DesiredCapabilities("anotherbrowser", "54.0.1", new Platform(PlatformType.Windows));
        cap.SetCapability("firefox_binary", @"Path to Browser");
        IWebDriver driver = new FirefoxDriver(cap);
And I got same error.

After I tried to test my codes with **Selenium WebDriver 3.6.0**.

I run **1st code** and I got an error:

> **["System.InvalidOperationException" in WebDriver.dll]** Invalid moz:firefoxOptions field acceptInsecureCerts

Then I run **2nd code** and I got another error:

> **["System.InvalidOperationException" in WebDriver.dll]** Invalid moz:firefoxOptions field browserName

Why isn't it possible in **C#** to rewrite `[browserName]` to another, but in **Java** everything is okay? Please, help me to re-write **Java** solution to **C#**

_P.s. I can't use original Firefox browser, because it doesn't have same advantages as my modified Firefox._

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by Lonckaster** [comment]
But It's issue too. I think that logic of my code is in a right way. Maybe there is a problem in Selenium Webdriver C#, what it can't set browserName. Because same code in Java works fine.

**Comment by barancev** [comment]
"Please, help me to re-write Java solution to C#" is a question :)

I don't see any reason at all to change browser name capability in your scenario. Just keep it empty. All you need it correct path to the browser binary.

**Comment by Lonckaster** [comment]
Путь к бинарнику у меня верный. Т.к. перед ошибкой selenium открывает браузер. Попытался восрользоваться ваши советом, вместо "brausername" поставил string.Empty - результата нет. Все еще выдает ошибку что уже есть такая capability. Что еще странно - даже если ставить имя браузера "firefox", ошибку выдает туже самую.

**Comment by barancev** [comment]
I mean, don't set browser name at all ("empty string" is not empty value)

**Comment by barancev** [comment]
FirefoxOptions options = new FirefoxOptions();
options.BrowserExecutableLocation = @"Path to Browser";
IWebDriver driver = new FirefoxDriver(options);

**Comment by Lonckaster** [comment]
I had already tried it. And I get an error: 

> **["System.ArgumentException" in WebDriver.dll]** _TypeError: Given browserName [object String] "firefox", but my name is [object String] "anotherbrowser"_

**Comment by barancev** [comment]
Interesting... Let's open for investigation.

**Comment by barancev** [comment]
What exactly did you change to set alternative browser name in your "enhanced firefox"?

**Comment by Lonckaster** [comment]
But in Java everything works fine.
In anotherbrowser.exe all names "firefox" are changed to "anotherbrowser". So WebDriver cant find command to firefox methods I think.

**Comment by Lonckaster** [comment]
It's not an enhanced for firefox. It's another browser, firefox-based browser.

**Comment by barancev** [comment]
@jimevans Is there a reason .Net binding does not allow to use custom browser name in firefox capabilities?

**Comment by barancev** [comment]
@Lonckaster By the way, in the Java sample you have
```options.setCapability("marionette", false);```
that means you're *not* using geckodriver.

What firefox version is your application based on?

**Comment by Lonckaster** [comment]
54.0.1

**Comment by Lonckaster** [comment]
Here's the same issue: [(https://toster.ru/q/465391)]

**Comment by barancev** [comment]
@Lonckaster Try this code:
```FirefoxOptions options = new FirefoxOptions();
options.UseLegacyImplementation = true;
options.BrowserExecutableLocation = @"Path to Browser";
options.AddAdditionalCapability("browser", "anotherbrowser");
IWebDriver driver = new FirefoxDriver(options);```

**Comment by Lonckaster** [comment]
Big Thank You!!!) It works!

**Comment by jimevans** [comment]
The right way to approach this with the `FirefoxOptions` class is to subclass it, and use that in the constructor. To wit:

    public class AnotherBrowserOptions : FirefoxOptions
    {
        public AnotherBrowserOptions() : base()
        {
            this.BrowserName = "anotherbrowser";
        }
    }
