### ISSUE TITLE
chrome_options download.default_directory

### ISSUE THREAD

**Issue by Jawad-As** [SeleniumHQ/selenium#5065]
## Meta -
OS:  Windows 7
Selenium Version:  3.7.0
Browser: Chrome
Browser Version:  57.0.2987.133 (Official Build) (32-bit)

## Expected Behavior -
I expect it to download and save the file to the specified location.
It used to work just fine, but since I updated selenium to the new version; This doesn't work anymore.

## Actual Behavior -
It keeps saving the file to the default directory "C:/Users/Me/Downloads/"

## Steps to reproduce -

conda version 4.3.30
python 3.6.3
update selenium package version 3.6.0 >>> 3.7.0

```python
#-----------------------------------------------------------
from selenium import webdriver

save_to = "C:/Users/Me/Desktop/"
chrome_options = webdriver.ChromeOptions()
prefs = { 'download':{'default_directory': save_to,
                      'directory_upgrade': True,
                      'extensions_to_open':''}}
chrome_options.add_experimental_option('prefs', prefs)						
driver = webdriver.Chrome(chromedriver_path, chrome_options)
#------------------------------------------------------------
```

**Comment by lmtierney** [comment]
Nothing has changed in selenium around that functionality.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lmtierney** [comment]
I take that back, the only thing that changed was the key the options are being sent over in. From `chromeOptions` to `goog:chromeOptions`. This was changed by a googler, so the above comment still applies.

**Comment by lmtierney** [comment]
Ah actually I see you're using an older chrome version so probably using an older chromedriver as well. The `goog:chromeOptions` only works with chromedriver `2.32` and greater. If you're using an older one still, you'll have to just use a raw dictionary.

prefs = { 'download':{'default_directory': save_to,
                      'directory_upgrade': True,
                      'extensions_to_open':''}}
chrome_options.add_experimental_option('prefs', prefs)						
driver = webdriver.Chrome(chromedriver_path, desired_capabilities={"chromeOptions": {"prefs": prefs} })
