### ISSUE TITLE
Unable to access IE using Robot framework with pycharm.

### ISSUE THREAD

**Issue by sarathchitturi** [SeleniumHQ/selenium#5066]
Getting below issue when try to access IE  using Robot framework with pycharm.

 "Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones."

I dont have access to enable options, as I am using company laptop. Is there any workaround to overcome this issue?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
