### ISSUE TITLE
Breaking backward compatibility

### ISSUE THREAD

**Issue by leebake** [SeleniumHQ/selenium#5071]
After upgrading selenium-java version from 3.0.1 to 3.7.1 I got a compile error:

```
Wait<WebDriver> waiter
waiter.until(ExpectedConditions.presenceOfElementLocated(locator.get()));
```
Waiter expects java Function interface, while ExpectedConditions.presenceOfElementLocated returns ExpectedCondition that extends guava Function.

**Comment by wrlyonsjr** [comment]
I had the same problem.  For me it was a dependency issue.  I updated guava dependency to 21 and the problem went away.

**Comment by barancev** [comment]
Yes, you have to upgrade guava to the latest version.

**Comment by leebake** [comment]
It works, thanks!
