### ISSUE TITLE
Selenium role node does not support HTTPS

### ISSUE THREAD

**Issue by vasilevich** [SeleniumHQ/selenium#5073]
I have set up a secure selenium grid on a remote server and attached it behind HTTPS (so man in the middle can not see my tests) so I tried to run:

java -jar selenium-server-standalone-3.7.1.jar -role node -hub https://example.com:80/grid/register

however after launch, selenium replaced https:// with http:// and the connection failed, thus I had to fallback to http:// .

can you please add https:// support? i think it is fair to say that certain tests require more security and could use the encryption of https which is already implemented in java. and should pretty much work out of the box.

thank you.

**Comment by bloudraak** [comment]
I'm able to run the hub behind a reverse proxy (ARR 3.0). In this case I have a DNS record `selenium.example.net`. IIS and ARR 3.0 is installed on the hub and rewrites `https://selenium.example.net` to `localhost:4444`.

When starting nodes, I can use the following:

```
java -Xrs -Xmx2048m -jar "c:\selenium\selenium-server-standalone-3.8.0.jar" -role webdriver -hub https://selenium.example.net/grid/register -port 5555
```

The challenge, like the OP, is that all communication between nodes and the hub has to be encrypted, especially when the nodes and hub are running is a shared environment, while the systems under test are governed by regulations (e.g. HIPAA, PII and PCI). The fact that we're unable to encrypt traffic between nodes and hub means there is an unattended exposure of information to parties who have no need-to-know.

**Comment by bloudraak** [comment]
Actually the original OP is correct. The logs show the following when port 80 is blocked on the hub:

```
00:39:02.086 INFO - Starting auto registration thread. Will try to register every 5000 ms.
00:39:02.086 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:39:02.236 INFO - The node is registered to the hub and ready to use
00:40:22.655 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:40:22.717 INFO - The node is registered to the hub and ready to use
00:41:43.242 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:41:43.315 INFO - The node is registered to the hub and ready to use
00:43:03.714 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:43:03.777 INFO - The node is registered to the hub and ready to use
00:44:24.351 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:44:24.398 INFO - The node is registered to the hub and ready to use
00:45:45.044 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:45:45.153 INFO - The node is registered to the hub and ready to use
00:47:05.832 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:47:05.864 INFO - The node is registered to the hub and ready to use
00:48:26.454 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:48:26.486 INFO - The node is registered to the hub and ready to use
00:49:47.143 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:49:47.190 INFO - The node is registered to the hub and ready to use
00:51:07.803 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
00:51:07.866 INFO - The node is registered to the hub and ready to use
00:52:28.425 INFO - Registering the node to the hub: http://selenium.example.net:-1/grid/register
```

**Comment by ketanb007** [comment]
Hello @bloudraak 

Could you please elaborate the steps you have done to start the selenium grid hub with https://

Thanks!!

**Comment by vasilevich** [comment]
I would like to add, that the only problem here is, that the commandline input( or some code a bit after) rewrites the input url with "https" into "http" and I think this rewirite should be disabled, because java supports https out of the box and this rewirite makes nos ense.

**Comment by MarkL4YG** [comment]
In my opinion [lines like this one](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/SelfRegisteringRemote.java#L254) are responsible for this.  
It appears that the protocol and the URI are stripped from whatever is set as the hub option and afterwards hard-coded "http" is used to concatenate the hub URL.  

In my opinion both things aren't very flexible.  
The first disables the possibility to run/proxy the hub without a new hostname or port and the second completely disables support for secure connections.  
Therefore, the only option to support secure connections in the grid is to use proxies for both the hub and the nodes.  
As already mentioned, this is especially poor since Java natively supports HTTPS with very few code differences - if any.

**Comment by RusmanCool** [comment]
@vasilevich @MarkL4YG Have you resolved the issue with a Client sending requests over HTTPS? I agree with @MarkL4YG about the hardcoded protocol. In addition, I could not find if Selenium Grid uses any certificates for HTTPS.

**Comment by RusmanCool** [comment]
#5859 post [suggests using nginx](https://serverfault.com/questions/145383/proxy-https-requests-to-a-http-backend-with-nginx) for this. Has anyone tried using reverse proxy for communication to/from Selenium Hub and between Hub and Node/-s?

**Comment by dylanlive** [comment]
@RusmanCool Setting up nginx in front of Hub for https is doable - I've done it. In between Hub and Nodes though would be complicated, as described in this ticket, a lot is hardcoded (for example, I believe the Hub Host in the node's config is hardcoded to http).

**Comment by vasilevich** [comment]
@RusmanCool like @dylanlive noted, having https support on the selenium grid is not required, you just have to set up nginx/apache or anything else in between to proxify the request, which is good enogh.
the real issue is, that within the selenium grid client,  the "http" is hardcoded and there is no way to change that other than going inside the code of the client.  

you just need to fix the clientside code and thats it for this to be resolved. as I don't see many people using the server without any kind of reverse proxy.

as to your second question, yes nginx, and any reverse proxy for that matter, will work just fine with any http-based server behind it. especially, and not limited to the selenium hub.  it is just the client that causes the issue here not the server.

**Comment by RusmanCool** [comment]
@vasilevich @dylanlive thank you for responses. I'll try to set up nginx between my client app and SeleniumHub.

**Comment by MarkL4YG** [comment]
In order to use HTTPS everywhere, you'd need to set up a reverse-proxy in front of the hub so it can be accessed using HTTPS and you'd also need to set up a normal proxy for the nodes so their connection gets tunneled as HTTPS to the reverse-proxy of the server. Obviously this only makes sense when the connection between proxy and nodes does not leave a secure network.

**Comment by vasilevich** [comment]
@MarkL4YG exactly what I was thinking, this, OR fix the client.... then you don't need to tunnel from the client at all. and the fix should be simple enogh. literally no reason to hardcode http,  java supports https natively without any special code.

**Comment by AlvaHenrik** [comment]
We would also prefer a setup without proxies between hub and nodes a lot. Please implement this with Selenium 4!

**Comment by dvarrazzo** [comment]
Another manifestation of the same problem: with selenium behind an haproxy redirecting http to https, the node fails registration because the hub doesn't process redirects correctly:

```
$ java -jar selenium-server-standalone-3.5.3.jar -role node -hub https://selenium-hub.example.com/grid/register -host 172.17.0.1 -port 5555
13:25:34.312 INFO - Selenium build info: version: '3.5.3', revision: 'a88d25fe6b'
13:25:34.312 INFO - Launching a Selenium Grid node
...
13:25:34.858 INFO - Selenium Grid node is up and ready to register to the hub
13:25:34.866 INFO - Starting auto registration thread. Will try to register every 5000 ms.
13:25:34.867 INFO - Registering the node to the hub: http://selenium-hub.example.com:-1/grid/register
13:25:34.894 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 301:Moved Permanently
```

**Comment by ambirag** [comment]
> #5859 post [suggests using nginx](https://serverfault.com/questions/145383/proxy-https-requests-to-a-http-backend-with-nginx) for this. Has anyone tried using reverse proxy for communication to/from Selenium Hub and between Hub and Node/-s?

@RusmanCool I have implemented Traefik as reverse proxy - https://github.com/ambirag/da-kubes for https hub but no https between hub and node.

**Comment by adiohana** [comment]
We have implemented a multi grid (3 hubs with 20 nodes connected to each hub) in aws. All communication between hubs and nodes are with https using Nginx as a reverse proxy in both hub and node. Node should also have a reverse one because of the registration phase.

It wasn’t easy though, and it requires “grouping” when re-stacking the environment or auto scaling. The benefit of that is having scalable and secure environment.

Still, I don’t think it should be part of selenium server and it should be implemented as a plugin / wrapper on top of selenium grid server.

**Comment by MarkL4YG** [comment]
> Still, I don’t think it should be part of selenium server and it should be implemented as a plugin / wrapper on top of selenium grid server.

Can you please specify what exactly you mean? Proxying or general HTTPS support?

**Comment by MarkDeckert** [comment]
Is there any movement on adding https support?  Is there a future version where this will be a feature?

**Comment by 4x0v7** [comment]
I'm working on adding support with #7588 
Would appreciate any guidance!

**Comment by MarkL4YG** [comment]
@4x0v7 I would start at removing the hardcoded HTTP from the client and optionally using SSL to connect. The MVP could be to at least allow usage of a reverse proxy for the server. Actual SSL support for the server could then follow.

**Comment by 4x0v7** [comment]
Ok thanks I'll start by removing those references.
As a stretch for adding TLS support, would there be any interest in allowing mutual (client certificate) TLS as well?

**Comment by adiohana** [comment]
Mutual authentication support will be a great thing, I think.

**Comment by 4x0v7** [comment]
I have a working implementation on [a branch here](https://github.com/4x0v7/selenium/tree/jetty-ssl).
At the moment there is only support for PCKS#1 RSA PEM files, ie `-----BEGIN RSA PRIVATE KEY-----` keys and `-----BEGIN CERTIFICATE-----` certs.
It builds and works for me!

**Comment by rhysvo** [comment]
Any updates with this? I am in an environment where _only_ TLS can be used for connections going to and from the cluster, and would rather not have to use a TLS tunnel for any nodes outside the cluster.

**Comment by simhem** [comment]
Hi, any news on https support ? I'm currently working on kubernetes and the only entrypoint to the hub is https (company policies).
For communication between hub and node, it's okay because i have a docker container with a hub and node in it so the communication between those 2 can be localhosted.
Also i create new hubs/nodes dynamically, so i don't know if a proxy would do the trick (since new IngressRoutes would be created all the time, also it maybe would be too much traffic incoming).
If anyone has an idea, it would be awesome

**Comment by diemol** [comment]
Thanks to @adamgoucher, Grid 4 (in the alphas now) has HTTPS support. You all can try it now and download it from https://www.selenium.dev/downloads/.

Information on how to use it can be seen in the binary itself:
```
java -jar selenium-server-4.0.0-alpha-5.jar info security                                                                                                                                     ✔  08:20:31

About Security
==============

Selenium 4 has a number of changes aimed at improving the security posture
of running your own infrastructure. The ability to communicate to a Selenium
Server (whether it is acting as a Standalone or Grid) is discussed in `Secure
Communication` and restricting Grid Nodes to only those you trust is covered
in `Node Registration.`

1. Secure Communication =======================

Selenium Grid by default communicates over HTTP. This is fine for a lot of
use cases, especially if everything is contained within the firewall and against
test sites with testing data. However, if your server is exposed to the Internet
or is being used in environments with production data (or that which has PII)
then you should secure it.

Standalone

In order to run the server using HTTPS instead of HTTP you need to start it
with the `--https-private-key` and `--https-certificate` flags to provide
it the certificate and private key (as a PKCS8 file).

  java -jar selenium.jar \
       hub \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem


Distributed

Alternatively, if you are starting things individually you would also specify
https when telling where to find things.

  java -jar selenium.jar \
       sessions \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem


  java -jar selenium.jar \
       distributor \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       -s https://sessions.grid.com:5556


  java -jar selenium.jar \
       router \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       -s https://sessions.grid.com:5556 \
       -d https://distributor.grid.com:5553 \


Certificates

The Selenium Grid will not operate with self-signed certificates, as a result
you will need to have some provisioned to you from a Certificate Authority
of some sort. For experimentation purposes you can use MiniCA to create and
sign your certificates.

  minica --domains sessions.grid.com,distributor.grid.com,router.grid.com


This will create minica.pem and minica.key in the current directory as well
as cert.pem and key.pem in a directory `sessions.grid.com` which will have
both distributor.grid.com and router.grid.com as alternative names. Because
Selenium Grid requires the key to be in PKCS8, you have to convert it.

  openssl pkcs8 \
    -in sessions.grid.com/key.pem \
    -topk8 \
    -out sessions.grid.com/key.pkcs8 \
    -nocrypt


And since we are using a non-standard CA, we have to teach Java about it.
To do that you add it to the cacert truststore which is by default, $JAVA_HOME/jre/lib/security/cacerts


  sudo keytool \
      -import \
      -file /path/to/minica.pem \
      -alias minica \
      -keystore $JAVA_HOME/jre/lib/security/cacerts \
      -storepass changeit \
      -cacerts


More information can be found at:

* MiniCA: https://github.com/jsha/minica


2. Node Registration ====================

Selenium Grid distributes script execution to worker nodes. Those nodes self-register
with the Grid Distributor process when they start and the Distributor trusts
that they should be getting work. This is fine in highly secured networks
where everything is trusted, but aside from that you really want to make sure
that the node is one you control and not a rouge node. In order to do this,
you start the Distributor, Router and Node servers with the new `--registration-secret`
command-line argument.

Using the same examples as above, they become the following with this additional
layer of security.

  java -jar selenium.jar \
       distributor \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       -s https://sessions.grid.com:5556 \
       --registration-secret cheese \


  java -jar selenium.jar \
       router \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       -s https://sessions.grid.com:5556 \
       -d https://distributor.grid.com:5553 \
       --registration-secret cheese


  java -jar selenium.jar \
       node \
       --https-private-key /path/to/key.pkcs8 \
       --https-certificate /path/to/cert.pem \
       --detect-drivers \
       --registration-secret cheese
Note: If the registration-secret from the Node to the Distributor (or Router)
is incorrect, there is nothing to indicate that returned to the Node. There
is an ERROR level log entry produced on the servers. You should be monitoring
the logs for that and raise alarms as deemed appropriate.
```
