### ISSUE TITLE
Which version of selenium standalone is latest?

### ISSUE THREAD

**Issue by shankarkc** [SeleniumHQ/selenium#5077]
## Meta -
OS:  
Linnux
Selenium Version:  
2.53
Browser:  
All

Browser Version:  
Any

## Expected Behavior -
In selenium latest release of git tab shows Latest release as 3.5.3 But http://www.seleniumhq.org/download/ shows latest release as 3.7.1 Its not clear for the users if we need to move up to 3.7.1 OR stick to 3.5.3.... Is 3.7.1 is unstable and because of that 3.5.3 marked as latest release? Some days back 3.6.X was in releases tab. But now its gone from releases tab. I am not sure why? If we decide to pull something from releases can you pls add some note why its removed? So that we can adjust our-self to it.
## Actual Behavior -
versions above 3.5.3 missing in reases tab
## Steps to reproduce -
goto releases [link](https://github.com/SeleniumHQ/selenium/releases)

**Comment by p0deje** [comment]
GitHub releases are essentially tags, you shouldn't use them.
