### ISSUE TITLE
Cannot create profile directory when /tmp folder is large

### ISSUE THREAD

**Issue by waseemh** [SeleniumHQ/selenium#508]
We are getting an exception when trying to initialize FireFox WebDriver on a linux machine. The cause of exception is that Firefox fails to create a profile under /tmp directory.
I assume that this failure is a result of very large /tmp folder (over 35K entries) which Java File IO can't handle.
Once /tmp folder is emptied, Firefox WebDriver is initialized successfully.

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7056; process output follows: 
08:54:29 null
08:54:29 Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
08:54:29 System info: host: 'etvr-mon02', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.3.3.el6.x86_64', java.version: '1.7.0_71'
08:54:29 Driver info: driver.version: FirefoxDriver
08:54:29 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
08:54:29 	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
08:54:29 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:115)
08:54:29 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
08:54:29 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
08:54:29 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
08:54:29 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
08:54:29 	at com.liveperson.automation.seleniumUtils.BrowserType.setDriver(BrowserType.java:85)
08:54:29 	at com.liveperson.automation.e2e.e2e.e2etestutils.E2EDriverFactory.getObject(E2EDriverFactory.java:49)
08:54:29 	at com.liveperson.automation.e2e.e2e.e2etestutils.E2ETestsBase.testSetup(E2ETestsBase.java:131)
08:54:29 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:54:29 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
08:54:29 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:54:29 	at java.lang.reflect.Method.invoke(Method.java:606)
08:54:29 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
08:54:29 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
08:54:29 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
08:54:29 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
08:54:29 	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
08:54:29 	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
08:54:29 	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
08:54:29 Caused by: org.openqa.selenium.WebDriverException: Cannot create profile directory at /tmp/unzip8719121035284230033stream
08:54:29 Build info: version: '2.42.0', revision: '5e824302019c86eae9c8c3ca9155e7307b410cf8', time: '2014-05-24 09:48:41'
08:54:29 System info: host: 'etvr-mon02', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.3.3.el6.x86_64', java.version: '1.7.0_71'
08:54:29 Driver info: driver.version: FirefoxDriver
08:54:29 	at org.openqa.selenium.io.TemporaryFilesystem.createTempDir(TemporaryFilesystem.java:88)
08:54:29 	at org.openqa.selenium.io.FileHandler.unzip(FileHandler.java:43)
08:54:29 	at org.openqa.selenium.firefox.internal.FileExtension.obtainRootDirectory(FileExtension.java:81)
08:54:29 	at org.openqa.selenium.firefox.internal.FileExtension.writeTo(FileExtension.java:58)
08:54:29 	at org.openqa.selenium.firefox.internal.ClasspathExtension.writeTo(ClasspathExtension.java:63)
08:54:29 	at org.openqa.selenium.firefox.FirefoxProfile.installExtensions(FirefoxProfile.java:416)
08:54:29 	at org.openqa.selenium.firefox.FirefoxProfile.layoutOnDisk(FirefoxProfile.java:394)
08:54:29 	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:89)

**Comment by barancev** [comment]
Not a Selenium issue

**Comment by waseemh** [comment]
Shouldn't it have a fallback solution in such cases?

**Comment by barancev** [comment]
What fallback would you expect? Clean the tmp dir implicitly?

**Comment by waseemh** [comment]
Absolutely not.
I should note that /tmp mount was not full (it was 50% capacity) but it had lot of entries.

**Comment by barancev** [comment]
You can report this issue to the Java bug tracker than.
