### ISSUE TITLE
Handle chrome notification in real-time

### ISSUE THREAD

**Issue by NateZ7** [SeleniumHQ/selenium#5080]
## Meta -
OS:  
macOS high sierra
Selenium Version:  3.4.0

Browser:  
Chrome

-->

Browser Version:  
Version 61.0.3163.100 (Official Build) (64-bit)

## Steps to reproduce -
I want to be able to test if a notification has arrived. I'm sending a message from a different device and gets a notification in the Monitor (Web), I want to test the UI to make sure the notification appeared but I couldn't find any way doing it with Selenium..

Any help will be appreciated. thanks !

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
