### ISSUE TITLE
Selenium 3.7.0 default download directory change failure on chrome driver

### ISSUE THREAD

**Issue by bullwe** [SeleniumHQ/selenium#5081]
## Meta -
OS:  Ubuntu 16.04

Selenium Version:  3.7.0

Browser:  Chrome

Browser Version:  61.0.3163.91

## Expected Behavior -
After changing default download directory, it is expected to find downloaded file in that particular directory

## Actual Behavior -
Files being downloaded to default directory (Downloads)
## Steps to reproduce -
python code:
    prefs = {"download.default_directory" : /new/existing/directory/}
    chromeOptions.add_experimental_option("prefs",prefs)
    browser = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)

**Comment by p0deje** [comment]
What ChromeDriver version do you use?

**Comment by bullwe** [comment]
I am using ChromeDriver 2.28.455506 (18f6627e265f442aeec9b6661a49fe819aeeea1f)

**Comment by p0deje** [comment]
Can you try with latest version (2.32)?

**Comment by bullwe** [comment]
I have downgraded selenium to 3.5 it started working, I will try today it with chromedriver(v2.33) and selenium (v3.7) as well

**Comment by bullwe** [comment]
Well it seems that with chromedriver(v2.33) and selenium (v3.7) it works fine as well as with chromedriver(v2.28) and selenium (v3.5)
So the problem only appears with chromedriver(v2.28) and selenium (v3.7)

**Comment by p0deje** [comment]
Yes, that's expected. You will need to use ChromeDriver 2.33 if you want to use Selenium 3.7

**Comment by bullwe** [comment]
Thanks for your attention!
