### ISSUE TITLE
ChromeOptions doesn't go through when starting using RemoteWebDriver

### ISSUE THREAD

**Issue by Icaroto** [SeleniumHQ/selenium#5083]
## Meta -
OS:  
Windows 10, Mac

Selenium Version:  
3.7.0

Browser:  
Chrome

Browser Version:  
62.0.3202.94 (Official Build) (64-bit)

## Expected Behavior -
Windows to start maximized using ChromeOptions argument "--start-maximized" or "--kiosk"

## Actual Behavior -
Windows start with normal size

## Steps to reproduce -
```
public void Start ()
        {
            ChromeOptions options = new ChromeOptions();
                options.AddArgument("--start-maximized");

            DesiredCapabilities caps = options.ToCapabilities() as DesiredCapabilities;
                caps.SetCapability(CapabilityType.BrowserName, "chrome");
                caps.SetCapability(CapabilityType.Version, string.Empty);
                caps.SetCapability(CapabilityType.Platform, "WINDOWS");

            new RemoteWebDriver("http://localhost:5555/wd/hub", caps);
        }
```

OR

```
public void Start ()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddArgument("--start-maximized");

            return new RemoteWebDriver("http://localhost:5555/wd/hub", options.ToCapabilities());
        }
```

If I start ChromeDriver with the same argument it works fine. Only when through RemoteWebDriver.

**Comment by vhsantos26** [comment]
I had the same problem when I try to did this

```java
@Override
	protected void startService() {
		if (chromeService == null) {
			try {
				chromeService = new ChromeDriverService.Builder()
						.usingDriverExecutable(new File(GetDriverFile.chromeDriver())).usingAnyFreePort().build();
				chromeService.start();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	@Override
	protected void createDriver() {
		driver = new ChromeDriver(chromeService, BrowserOptions.chrome());
	}
```

**Comment by yurabysaha** [comment]
The same problem on python

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--start-maximized')
chrome = webdriver.Chrome(chrome_options=options)

**Comment by Kappasama** [comment]
I have the same problem. Python 3.5, selenium 3.5, selenium-server-standalone-3.8.1

**Comment by linhle123** [comment]
Has anyone figured out how to overcome this issue?

**Comment by cgoldberg** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES

see 3.8.0:
```
* Browser options can now be passed to remote WebDriver via the `options` parameter
* Browser option parameters are now standardized across drivers as `options`. `firefox_options`,
  `chrome_options`, and `ie_options` are now deprecated
```

**Comment by lmtierney** [comment]
Make sure if you're using standalone `3.8.0` or greater to use the `goog:chromeOptions`.

**Comment by lmtierney** [comment]
Whoops, didn't mean to close.

**Comment by lmtierney** [comment]
I am unable to recreate this with the latest versions.

**Comment by Icaroto** [comment]
Hi @lmtierney 

I'm still getting the issue :(

I downloaded the new standalone (3.8.1) and to make sure, updated the NuGet packages from my solution to 3.8.0 too.

I used the code from the first example I gave but the result is the same,. The window still do not open maximized.

**Comment by danielsaf** [comment]
Hi @Icaroto,
try like this
 {          maxInstances: 1,
            browserName: "chrome",
            "goog:chromeOptions": {
                args: ["--start-maximized", "--start-fullscreen"],
            },
        },
    ],

For me with selenium 3.8.1, chromedriver 3.25 and in windows server works fine.

**Comment by diemol** [comment]
After reading a few comments, this issue should be solved. If this is not true, after trying again with the latest versions of WebDriver and the browser driver/browser, please create a new issue with all the required information.
