### ISSUE TITLE
((RemoteWebDriver) driver).getCapabilities().getPlatform().toString() returns ANY for iPhone/iPad

### ISSUE THREAD

**Issue by rachitktesting** [SeleniumHQ/selenium#5087]
## Meta -
OS:  
Any iPhone / iPad
Selenium Version:  
2.53.1
Browser:  
Safari on iPhone / iPad
Browser Version:  
Latest

## Expected Behavior -
((RemoteWebDriver) driver).getCapabilities().getPlatform().toString() shall give either iPhone/iPad

## Actual Behavior -
((RemoteWebDriver) driver).getCapabilities().getPlatform().toString() is giving value as ANY

## Steps to reproduce -
Please execute any selenium script on iPhone/iPad and use the property ((RemoteWebDriver) driver).getCapabilities().getPlatform().toString() for iPhone/iPad specific actions and then you will see that value of platform is not returned properly.

**Comment by barancev** [comment]
Selenium just shows what a driver returns.
Please report this issue to the Safari driver tracker https://bugreport.apple.com/
