### ISSUE TITLE
Unable to launch IE 11 using Selenium IDE because of error "[error] Could not connect to Selenium Server. Have you started the Selenium Server yet?"

### ISSUE THREAD

**Issue by nguyenlamngoc** [SeleniumHQ/selenium#5092]
![seleniumide_unablelaunchie](https://user-images.githubusercontent.com/13899274/33109171-09ed2c80-cf7b-11e7-8381-a1e9e071b122.png)

## Meta -

OS:  Windows 10
Selenium Version: Selenium build info: version: '3.7.1', revision: '8a0099a'
Browser:  Internet Explorer 11 , Firefox v 47.0 (32-bit) 

## Steps to reproduce -
1. Install java: java version "1.8.0_151"
2. Started the selenium server from command prompt: java -Dwebdrive.ie.driver=IEDriverServer32.exe -jar selenium-server-standalone-3.7.1.jar
=> 15:19:29.234 INFO - Selenium Server is up and running
3. Opened selenium IDE and in Options > Options > Web Driver Tab > Checked the "Enable WebDriver Playback" and type "internet explorer" in the text box
4. Import a test case and click on play button. => Error displayed "[error] Could not connect to Selenium Server. Have you started the Selenium Server yet?" and IE is not launched

Notes: After doing step 4, in command prompt shows:
15:19:46.597 INFO - /session: Executing POST on /session (handler: BeginSession)
15:19:46.665 INFO - Capabilities are: Capabilities {browserName: internet explorer}
15:19:46.668 INFO - Capabilities {browserName: internet explorer} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version
