### ISSUE TITLE
Selenium 3.7.0 - Invalid capabilities in alwaysMatch: unhandledPromptBehavior is type boolean instead of string

### ISSUE THREAD

**Issue by priyaa02** [SeleniumHQ/selenium#5093]
## Meta -

Hello ,
I have upgraded by selenium automation framework. Details are shared below

OS: Windows 7
Selenium Version:  3.7.0
Browser:  IE 3.7.0 32 bit driver

While executing my code, I am getting exception # **Invalid capabilities in alwaysMatch: unhandledPromptBehavior is type boolean instead of string** . 

Is this due to the new driver upgraded because existing IE driver 3.4.0 is not generating this error. ?

**Comment by jimevans** [comment]
As noted in the [IE driver CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG), starting with 3.5, the IE driver now implements the W3C WebDriver specification. This changes some of the capabilities used when creating a new session. Without supplying code that shows how you're creating an instance of the `InternetExplorerDriver` class, more advice would be purely speculative.

**Comment by priyaa02** [comment]
Code Snippet : 
case "IE":

					capabilities.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, Boolean.TRUE);
					/*capabilities.setCapability("UNHANDLED_PROMPT_BEHAVIOUR", "false"); 
					capabilities.setCapability("UNHANDLED_PROMPT_BEHAVIOUR", "accept"); 
					capabilities.setCapability("UNHANDLED_PROMPT_BEHAVIOUR", "ignore");*/
					capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
					capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
					capabilities.setCapability(CapabilityType.SUPPORTS_ALERTS, true);
					capabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, true);
					capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
					capabilities.setCapability(InternetExplorerDriver.ENABLE_ELEMENT_CACHE_CLEANUP, true);
					capabilities.setCapability("nativeEvents", false);
					capabilities.setCapability("requireWindowFocus", false);
					capabilities.setJavascriptEnabled(true);
					capabilities.setCapability("ignoreProtectedModeSettings", true);
					System.setProperty("webdriver.ie.driver", ieExe.getAbsolutePath());
					opt = new InternetExplorerOptions();
					opt.merge(capabilities);
					driver = new InternetExplorerDriver(opt);
					driver.manage().deleteAllCookies();
					driver.manage().window().maximize();

**Comment by priyaa02** [comment]
I have added my code above. Not able to debug where the issue.

**Comment by barancev** [comment]
```
capabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, true);
```
This line causes the failure, the value of this capability should be a string.

**Comment by priyaa02** [comment]
Thanks.  I modified the code snippet as "capabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, UnexpectedAlertBehaviour.IGNORE);"
