### ISSUE TITLE
sel 3.7.0 : Error with send_keys(str)

### ISSUE THREAD

**Issue by langme** [SeleniumHQ/selenium#5097]
## Meta -
OS:  Windows 10 -- Python 3.6.3, pytest-3.2.5, py-1.5.0, pluggy-0.4.0
Selenium Version:  3.7.0
Browser:  no browser only Appium Android device

## Expected Behavior -
arrive to write in textView by input.send_keys("toto")
## Actual Behavior -
Error : Message: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","value","id","sessionId"]

 search_input.send_keys(word_to_search)
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py:349: in send_keys
    'value': keys_to_typing(value)})
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py:493: in _execute
    return self._parent.execute(command, params)
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py:249: in execute
    self.error_handler.check_response(response)
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\appium\webdriver\errorhandler.py:29: in check_response
    raise wde
..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\appium\webdriver\errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)

**Comment by barancev** [comment]
Please report this issue to Appium tracker.
