### ISSUE TITLE
With Selenium 3.4.0 + geckodriver 0.16.0 + Firefox 52.1.0  combination, browser is "Not Responding" sometimes

### ISSUE THREAD

**Issue by RoupRanjan0308** [SeleniumHQ/selenium#5099]
## Meta -
OS:  Windows 7
Selenium Version:  WebDriver 3.4.0
Driver Version:  geckodriver 0.16.0 win-32 
Browser:  Firefox: 52.1.0(32-bit)

Issue:
While running the Automation script browser is "Not Responding" sometimes. Please some let m know if it is an issue. if not please suggest the perfect  combination of Selenium+Firefox browser+geckodriver version.
Thanks in Advance...!!!!

**Comment by barancev** [comment]
Is there a reason you're using outdated versions of software?

**Comment by RoupRanjan0308** [comment]
Yes, as per my client Firefox 52.1.0 32-bit is the approved version and as
compatible to that I'm using selenium version and gecko driver

Warm Regards,

Roupya Ranjan Bag
Mob: +91-9176022276
e-mail : roup.ranjan0308@gmail.com

On Nov 22, 2017 12:59 PM, "Alexei Barantsev" <notifications@github.com>
wrote:

Is there a reason you're using outdated versions of software?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SeleniumHQ/selenium/issues/5099#issuecomment-346265843>,
or mute the thread

**Comment by barancev** [comment]
Mozilla does not (and will not) fix issues in geckodriver related to use old browser versions. For Firefox 52 you can use stable legacy Firefox driver.
