### ISSUE TITLE
The default duration value for the starting pointerMove action should be equal to zero

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#5101]
Current implementation of W3C actions generates the following JSON output for 

```python
actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER, "touch"))
pointer = actions.pointer_action
pointer.move_to_location(target_location['x'] + 100, target_location['y'] + 100)\
       .click_and_hold()\
       .move_by(100, 0)\
       .release()
actions.perform()
```

action:

```
"actions":[{"parameters":{"pointerType":"touch"},"type":"pointer","id":"touch","actions":[{"duration":250,"x":100,"type":"pointerMove","y":1011,"origin":"viewport"},{"duration":0,"button":0,"type":"pointerDown"},{"duration":250,"x":100,"type":"pointerMove","y":0,"origin":"pointer"},{"duration":0,"button":0,"type":"pointerUp"}]}]
```

Actual result:
The very first `pointerMove` action item has duration equal to the default value (250ms). This does not look correct from the server's point of view, since `pointerMove` action with non-zero duration is expected to have a starting point, which is unknown in case it is the very first action item in the chain. 

Expected result:
`pointerMove` action item's duration should always be equal to zero if this is the very first action in the chain. We expect the main purpose of such item is to set the initial coordinates for the following action items.

**Comment by lmtierney** [comment]
I will have to discuss with other committers about changing the default move duration to 0. That being said, I believe we do need to add a duration parameter for all of the moving actions so I'll hopefully get to that soon. That way, you can specify your move duration how you want.
