### ISSUE TITLE
Not able to maximize the Browser Chrome Browser Window on latest chrome Version 62.0.3202.94 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by anshulc55** [SeleniumHQ/selenium#5104]
OS:  
Windows 10
Selenium Version:  
2.53
Browser:  
Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
Driver:
ChromeDriver 2.33 

Since I updated my Chrome Browser (Version 62.0.3202.94 (Official Build) (64-bit)), I am getting error -
Selenium WebDriver instance is not available
unknown error: failed to change window state to maximized, current state is normal (Session info: chrome=62.0.3202.94) (Driver info: chromedriver=2.33.506120

We are facing this issue while maximizing the window. This issue never encountered with earlier chrome browsers <v62. 
Command which is failing -
driver.manage().window().maximize();

## Expected Behavior -
The browser window should be maximized.

## Actual Behavior -
Getting error -
Selenium WebDriver instance is not available
unknown error: failed to change window state to maximized, current state is normal (Session info: chrome=62.0.3202.94) (Driver info: chromedriver=2.33.506120

## Steps to reproduce -
Create the webdriver instance.
Execute selenium Browser window maximize command.

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
