### ISSUE TITLE
Selenium version mismatch error

### ISSUE THREAD

**Issue by rishabh27892** [SeleniumHQ/selenium#5106]
I have already referred bug 2739 for this but could not find a working solution especially since my version match with the versions specified in the solutions. https://github.com/SeleniumHQ/selenium/issues/2739

Hi I am facing the same issue-
"selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpqz86Ue If you specified a log_file in the FirefoxBinary constructor, check it for details. "

I did not change anything with script, I read through the comments, seems like my configuration should work swiftly..
I just now changed it to:

Ubuntu 16.04.3 LTS
Mozilla Firefox 56.0
geckodriver 0.18.0
selenium-3.7.0

Please respond, I dont see any recent comments assuming the issue is fixed for good, Kindly share the knowledge ASAP! Thanks in advance

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by AutomatedTester** [comment]
That should work. If you have steps to reproduce that show its not working (and ideally please try on another machine with the same configuration)

**Comment by rishabh27892** [comment]
@AutomatedTester and @p0deje -I will try to reproduce it on another machine today and will update you with whatever I find. I am actually very new to the testing world, so I will provide you guys with the reproducible test case by referring the provided link. Thanks for responding.

**Comment by rishabh27892** [comment]
#I am using '**#**' for comments
#So here is what I did in a new machine Ubuntu was already installed in it, I double checked the Mozilla version before starting anything(54.0):

#Installations
cd ~/
sudo apt-get install python-pip
sudo pip install --upgrade pip
sudo pip install selenium
sudo apt-get install python-pytest
sudo apt-get install git
pip install unittest-xml-reporting

#Geckodriver -I have made my own copy in my repo so that I have it accessible all the time(version 0.18 is very new)
git clone https://github.com/rishabh27892/webui-test-files/
cd webui-test-files/
tar -xvzf geckodriver-v0.18.0-linux64.tar.gz
chmod +x geckodriver
sudo cp geckodriver /usr/local/bin/
cd ~/
rm -rf webui-test-files/

#Download ixautomation repo-which is the project I have been working on
git clone https://github.com/ixsystems/ixautomation/
cd ixbuild/freenas/webui-tests/

#Run the script
python runtest.py

#So it did run for firefox 54.0, but as soon as I did an upgrade, it stopped working with the same error as before
sudo apt-get upgrade
python runtest.py
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Possible firefox version mismatch. You must use GeckoDriver instead for Firefox 48+. Profile Dir: /tmp/tmp9tjc27 If you specified a log_file in the FirefoxBinary constructor, check it for details

#I double checked the version of firefox, it was upgraded to 57.0. @AutomatedTester @p0deje - Is this information useful ? I will keep my testing machine open If you want to reproduce everything. Thankyou and feel free to respond back with any further questions.

**Comment by rishabh27892** [comment]
#I am basically using this, where I think may be the issue..
def webDriver():
    caps = webdriver.DesiredCapabilities().FIREFOX
    caps["marionette"] = False
    global driver
    driver = webdriver.Firefox(capabilities=caps)
    driver.implicitly_wait(30)
    driver.maximize_window()
    return driver

**Comment by rishabh27892** [comment]
"caps = webdriver.DesiredCapabilities().FIREFOX
caps["marionette"] = False"

I tested the same thing by removing the desired capabilities because I think for Selenium3.5 and above it is there by default. It is working now!

**Comment by rishabh27892** [comment]
its selenium 3.0 and above
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by barancev** [comment]
`caps["marionette"] = False`
means you're running legacy Firefox driver that can be used for Firefox versions up to 52, newer versions are not supported in legacy mode.
