### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/bin/safaridriver

### ISSUE THREAD

**Issue by GabLeRoux** [SeleniumHQ/selenium#5109]
## Meta -
OS:  
MacOS High Sierra 10.13.1
![image](https://user-images.githubusercontent.com/1264761/33176592-8ef2d2b0-d02d-11e7-95b7-10681c65c3ef.png)

Selenium Version:  
```
❯ pip freeze | grep selenium
selenium==3.7.0
```
Browser:  
Safari

Browser Version:  
11.0.1
![image](https://user-images.githubusercontent.com/1264761/33176649-c7fbf992-d02d-11e7-9380-02c5723c4bc9.png)

## Code

`safari.py`:
```python
from selenium import webdriver

driver = webdriver.Safari('/usr/bin/safaridriver')
driver.get('https://gableroux.com')
```

## Expected Behavior

Selenium should connect to the `safaridriver` service

## Actual Behavior

```
python safari.py
Traceback (most recent call last):
  File "safari.py", line 3, in <module>
    driver = webdriver.Safari('/usr/bin/safaridriver')
  File "/usr/local/opt/pyenv/versions/selenium-example/lib/python3.4/site-packages/selenium/webdriver/safari/webdriver.py", line 47, in __init__
    self.service.start()
  File "/usr/local/opt/pyenv/versions/selenium-example/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 102, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/bin/safaridriver
```

## Steps to reproduce

```bash
# install pyenv
brew install pyenv pyenv-virtualenv
# install python 3.4.2
pyenv install 3.4.2
# create a virtualenv with that version
pyenv virtualenv 3.4.2 selenium-example
pyenv activate selenium-example
# install selenium requirement
pip install selenium==3.7.0
# Then execute the very simple script
python safari.py
```

```bash
which safaridriver
# /usr/bin/safaridriver
```

```bash
safaridriver --help
# Usage: safaridriver [options]
# 	-h, --help                Prints out this usage information.
# 	-p, --port                Port number the driver should use. If the server
# 	                          is already running, the port cannot be changed.
# 	                          If port 0 is specified, a default port will be used.
# 	--enable                  Applies configuration changes so that subsequent WebDriver
# 	                          sessions will run without further authentication.
safaridriver -p 0
safaridriver --enable
```
I entered root password when prompted.

I opened `Safari.app` and enabled *Allow remote automation*
<img width="707" alt="image" src="https://user-images.githubusercontent.com/1264761/33177354-57bf9460-d030-11e7-8e73-de0445327e34.png">

It is now checked in the menu:
![image](https://user-images.githubusercontent.com/1264761/33177562-0bff763e-d031-11e7-8b6c-580a9812a874.png)

I've read related documentation: https://webkit.org/blog/6900/webdriver-support-in-safari-10/

> Ensure that the `Develop menu` is available. It can be turned on by opening Safari preferences (`Safari > Preferences` in the menu bar), going to the Advanced tab, and ensuring that the Show Develop menu in menu bar checkbox is checked.

✅ 

> Enable Remote Automation in the Develop menu. This is toggled via `Develop > Allow Remote Automation` in the menu bar.

✅ 

> Authorize `safaridriver` to launch the `webdriverd` service which hosts the local web server. To permit this, run `/usr/bin/safaridriver` once manually and complete the authentication prompt.

✅ 

I did not find any other specific documentation for using `safaridriver` and `selenium`, am-I missing something? If everything looks right, I will fill a bug at https://bugreport.apple.com/ :v:

**Comment by GabLeRoux** [comment]
Found the problem, first parameter is not the `executable_path`:

```python
driver = webdriver.Safari(executable_path='/usr/bin/safaridriver')
# or
driver = webdriver.Safari()
```

**Comment by MrBCut** [comment]
@GabLeRoux GabLeRoux thank you for theses steps, outline and resolve. A great guide for setting this up correctly.

**Comment by MrBCut** [comment]
> Found the problem, first parameter is not the `executable_path`:
> 
> ```python
> driver = webdriver.Safari(executable_path='/usr/bin/safaridriver')
> # or
> driver = webdriver.Safari()
> ```
> 
> reference:
> 
> ```python
>     def __init__(self, port=0, executable_path="/usr/bin/safaridriver",
>                  desired_capabilities=DesiredCapabilities.SAFARI, quiet=False):
> ```
@GabLeRoux do you mind pointing me to where you found these logics please? :)
