### ISSUE TITLE
UnsupportedOperationException when using advanced user interactions on wrapped HtmlUnitDriver

### ISSUE THREAD

**Issue by lklonowski** [SeleniumHQ/selenium#5124]
## Meta -
OS:  Windows 7
Selenium Version:  3.7.1
Browser:  HtmlUnit
Browser Version:  2.28.2

## Expected Behavior -
when wrapping an `HtmlUnitDriver` inside an `EventFiringWebDriver`, advanced user interactions can be performed without exceptions
## Actual Behavior -
an `UnsupportedOperationException` is thrown every time

`EventFiringWebDriver` throws this Exception, because the `HtmlUnitDriver` does not implement the `Interactive` interface; the `BuildAction` only catches `UnsupportedCommandException`s and therefore doesn't use the fallback option
=> is this meant to work this way and how do I cope with this?
## Steps to reproduce -
- wrapping an `HtmlUnitDriver` inside an `EventFiringWebDriver`
- performing advanced user interactions

```
HtmlUnitDriver htmlUnitDriver = new HtmlUnitDriver();
WebDriver driver = new EventFiringWebDriver(htmlUnitDriver);

Actions builder = new Actions(driver);
builder.doubleClick().perform();
```

**Comment by barancev** [comment]
Yes, HtmlUnitDriver should implement Interactive interface.

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/htmlunit-driver #66](https://github.com/SeleniumHQ/htmlunit-driver/issues/66) via [**ZenHub**](https://www.zenhub.com/)
