### ISSUE TITLE
Unable to execute Selenium Tests using Safari 11 - Authentication form

### ISSUE THREAD

**Issue by mmorenoivy** [SeleniumHQ/selenium#5130]
OS:  
MAC Sierra OS 10.12
Selenium Version:  
3.6.0
Browser:  
Safari 11.0.1

Browser Version:  
11.0.1

## Steps to reproduce -
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Safari;

namespace TestSafari
{
    class Program
    {
        static void Main(string[] args)
        {
            IWebDriver safari = new SafariDriver();
            safari.Navigate().GoToUrl("http://username:pw@applic.com/ui/");
        }
}

**Comment by p0deje** [comment]
Please post SafariDriver specific issues to [its own bug tracker](https://bugreport.apple.com/).

**Comment by p0deje** [comment]
But actually, most drivers don't support authentication by passing username and password in URL and W3C specification doesn't require it.

**Comment by mmorenoivy** [comment]
@p0deje, does this mean there's no alternative method of executing tests to safari anymore?

**Comment by p0deje** [comment]
Probably not when you need to use HTTP authentication. I might be wrong though.

**Comment by mmorenoivy** [comment]
@p0deje  I would like to try the HTTP Authentication. Thanks!
