### ISSUE TITLE
Selenium 3.7.1 fails to launch FirefoxDriver when a valid binary path is proviced.

### ISSUE THREAD

**Issue by R4il** [SeleniumHQ/selenium#5134]
OS:  
 Windows 10
Selenium Version:  
 3.7.1, using java bindings.
Browser:  
 Firefox 57.0

Browser Version:  
e.g.: 57.0 (64-bit)

I read that most Firefox issues will be closed as duplicate to 2559 but this is not really on Firefox's or geckodriver's side. This seems to be an issue caused in the Selenium's FirefoxOptions class.

## Expected Behavior -
When providing a valid binary path or binary executable file to a FirefoxOptions object and this is used to construct a FirefoxDriver the driver should be successfully constructed and use the indicated binary. This should be the case even if Firefox is not installed in the system, that is the point of passing the binary path.
## Actual Behavior -
If Firefox is not installed in the system an exception will be thrown pointing this out. This shouldn't be the case since a user defined path is been passed to the constructors.
## Steps to reproduce -
On a environment with no Firefox installed, download a copy of Firefox and provide the path to the binary firefox.exe file to a FirefoxOptions like this:
```java
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setBinary(firefoxBinary);
```

Then create a driver:
```java
driver = new FirefoxDriver(firefoxOptions);
```
And it should fail as above. 
This seems to originate from the FirefoxOptions class line 218:
```java
public FirefoxBinary getBinary() {
    return getBinaryOrNull().orElse(new FirefoxBinary());
}
```
Because even when the binary is successfully created(I checked while debugging) the orElse needs to initialize the default FirefoxBinary and this fails by throwing:
  
```java
throw new WebDriverException("Cannot find firefox binary in PATH. " +
                                 "Make sure firefox is installed. OS appears to be: " + Platform.getCurrent());
``` 

Best workaround I came up with is setting the system property:
```java
if(binaryPath != null) {
    System.setProperty("webdriver.firefox.bin", binaryPath);
}
```
And this works nicely, but i thought it was worth documenting this issue since it came suddenly. Dozens of tests that ran normally started breaking when updated from Selenium 3.5.3 to 3.7.1

Stack trace of error:
Caused by: org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'WXVDEPDPRGUD057', ip: '10.51.179.173', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:116)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary(FirefoxOptions.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:155)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)

**Comment by barancev** [comment]
Fixed in version 3.8 (commit b29e332260d58a4139fd5ae8fd822e65b09a5a2b)
