### ISSUE TITLE
Send keys to authentication window doesn't work for chromdriver.

### ISSUE THREAD

**Issue by lilit14** [SeleniumHQ/selenium#5137]
## Meta -
OS:  Windows 10
Selenium Version:   3.7.0
Browser: Chrome 62, chromediver 2.33
python 2.7

here is the code sample
1 wait(driver, 5).until(EC.alert_is_present())
2 alert = driver.switch_to_alert()
3 alert.send_keys("username" + Keys.TAB + "password")
4 alert.accept()

## Actual Behavior -
I'm getting timeout exception on line 1 - selenium.common.exceptions.TimeoutException: Message: 
but actually the alert is present. 
![chromeauthenticationrequired](https://user-images.githubusercontent.com/14979534/33370348-b33954e0-d510-11e7-884d-37bf60741510.PNG)

when removing line 1, I'm getting exception on line 2
selenium.common.exceptions.NoAlertPresentException: Message: no alert open

**Comment by barancev** [comment]
Drivers will implement this feature not earlier than it is specified in W3C WebDriver standard.
Follow this issue for the status: https://github.com/w3c/webdriver/issues/385

**Comment by hujog** [comment]
**workaround** that worked for me: 
Authenticate via the URL
`https://username:password@www.example.com`

OS: Linux Mint 17.3
Selenium Version: 3.7.0
Browser: Chrome 62.0.3202.94, chromediver 2.32
python 3.4.3

**Comment by lilit14** [comment]
Thanks, the workaround works for me as well.

**Comment by gauravk97** [comment]
If even this doesn't work, then one change that you can try is 

alert.send_keys("username" + Keys.TAB.toString() + "password")
in the third command

**Comment by arunkrh** [comment]
I am not able to login to the site using Alert.send_keys()
My System configuration:
OS: Windows10 64bit
Browser Version: 72.0.3
Selenium: 3.141
Python: 3.7
Chrome Driver: 72.0.3

Code tried:1
+++++++++++
browser = webdriver.Chrome()
browser.get('http://10.179.230.232/desktop/')

alert = Alert(browser)
alert.send_keys("apc"+str(Keys.TAB)+"apc")
alert.accept()
++++++++
Code Tried: 2
++++++++
browser = webdriver.Chrome()
browser.get('http://10.179.230.232/desktop/')

Alert.send_keys("apc")
browser.switch_to.alert()
Alert.send_keys("apc")
+++++++++
Error:
Traceback (most recent call last):
  File "C:/DataVerificationSQA/UITest/dceUITest.py", line 47, in <module>
    alert.send_keys("apc"+str(Keys.TAB)+"apc")
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\alert.py", line 105, in send_keys
    self.driver.execute(Command.SET_ALERT_VALUE, {'text': keysToSend})
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=72.0.3626.69 (3c16f8a135abc0d4da2dff33804db79b849a7c38),platform=Windows NT 10.0.14393 x86_64)

![image](https://user-images.githubusercontent.com/26589115/54084215-f5669c80-4353-11e9-8681-462c0cd13a8a.png)

Firefox is working fine.
++++++++++
browser = webdriver.Firefox()
browser.get(r'http://10.179.230.232/desktop/')
alert = Alert(browser)
alert.send_keys(f'apc{Keys.TAB}apc')
alert.accept()
++++++++++++

Please help me to solve this issue.
Thanks
