### ISSUE TITLE
MoveToElement() function doesn't move the element (and there is no error message either)

### ISSUE THREAD

**Issue by HPetra** [SeleniumHQ/selenium#5141]
## Meta -
OS:  
Ubuntu 16.04 
Selenium Version:  
 3.7.1 
Browser:  
 Chrome

Browser Version:  
62.0.3202.94 (64-bit)

## Expected Behavior
Original element is moved to target element and released at that specific position.

## Actual Behavior 
Original element is moved, target element is found, but the original element is not moved and released to that specific position.

## Steps to reproduce
	WebDriver driver = new ChromeDriver();

		driver.navigate().to("http://react-dnd.github.io/react-dnd/examples-dustbin-multiple-targets.html");
		
		WebElement dragBox = driver.findElement(By.xpath("//div[@data-reactid='105']"));	
		
		Actions action = new Actions(driver); 
		
		action
		   	.clickAndHold(dragBox).moveByOffset(5,5)
		    .build()
		    .perform();

		WebDriverWait wait = new WebDriverWait(driver, 10);
		WebElement element = wait.until(
		    ExpectedConditions.presenceOfElementLocated(By.xpath("//div[contains(@style,'background-color: darkkhaki')]"))
		); 
		
		WebElement dropBox = driver.findElement(By.xpath("//div[@data-reactid='96']"));
		
		action
			.moveToElement(dropBox,5,5)
			.release()
		    .perform();

**Comment by venkatakumar9** [comment]
when will this defect can be fixed please?

**Comment by barancev** [comment]
This issue should be fixed in chromedriver, please report it to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by venkatakumar** [comment]
This issue looks like resolved in latest version of chrome
