### ISSUE TITLE
The selenium-server-standalone-3.8.0.jar  is corrupted?

### ISSUE THREAD

**Issue by markbook2** [SeleniumHQ/selenium#5142]
## Meta -

Steps to reproduce:
1. Go to https://selenium-release.storage.googleapis.com/

2. Check file size in XML for the selenium-server-standalone-3.8.0.jar:
```xml
<Contents>
<Key>3.8/selenium-server-standalone-3.8.0.jar</Key>
<Generation>1511989263546495</Generation>
<MetaGeneration>1</MetaGeneration>
<LastModified>2017-11-29T21:01:03.491Z</LastModified><ETag>"1455d5d756bf0574d1ca3dbc458aff37"</ETag>
<Size>235</Size>
</Contents>
```
Its size is 235 bytes.

3. Try to download the file and run it:
```
curl -O https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
java -jar selenium-server-standalone-3.8.0.jar
Error: Invalid or corrupt jarfile selenium-server-standalone-3.8.0.jar

du -b selenium-server-standalone-3.8.0.jar
235     selenium-server-standalone-3.8.0.jar
```

**Comment by duffman03** [comment]
My team is reproducing this issue (using webdriver-manager).

$ webdriver-manager start
webdriver-manager: using local installed version 12.0.6
[14:15:51] I/start - java -Dwebdriver.chrome.driver=/Users/USER/code/olp-pipelines/node_modules/webdriver-manager/selenium/chromedriver_2.33 -Dwebdriver.gecko.driver=/Users/USER/code/olp-pipelines/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1 -jar /Users/USER/code/olp-pipelines/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.8.0.jar -port 4444
[14:15:51] I/start - seleniumProcess.pid: 98365
Error: Invalid or corrupt jarfile /Users/USER/code/PROJECT/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.8.0.jar
[14:15:52] I/start - Selenium Standalone has exited with code 1

**Comment by DGerich** [comment]
Can confirm, same problem in our projects.

**Comment by drewswaycool** [comment]
Same here as well.

**Comment by jacobcabantomski-ct** [comment]
Workaround if you're using `webdriver-manager`:

```bash
webdriver-manager update --versions.standalone=3.7.1
``

**Comment by alancnet** [comment]
👍 This is blocking for us

**Comment by wiltzius** [comment]
Just went through debugging the same. Pinning the version to 3.7 resolved the issue for us as well. Seems cross-platform; I could reproduce on both Mac and Linux.

**Comment by wiltzius** [comment]
I also had to downgrade to 3.7 for our CI system today. I did not get the "corrupted" messages -- for me webdriver-manager is perfectly happy to start but protractor fails to connect to the selenium server that's running. Selenium-webdriver outputs only this basic info:

```[17:09:44] I/launcher - Running 1 instances of WebDriver
[17:09:44] I/local - Starting selenium standalone server...
[17:09:45] E/launcher - Error: Error: Server terminated early with status 1
    at Error (native)
    at earlyTermination.catch.e (/Users/tomwiltzius/Documents/welkin/dugong/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:109:7)

[17:09:45] E/launcher - Process exited with error code 100```

**Comment by Lilly2016** [comment]
After updating to Selenium standalone 3.8.0, I get the same err as above. 

Running `webdriver-manager start --versions.standalone=3.7.1` will start the server, but my protractor don't run and return err:
`Unable to create new service: ChromeDriverService`

Node Version: `v8.9.0`
Protractor Version: `Version 5.2.0`
Operating System and Version: `Windows 10`

**Comment by sthaha** [comment]
@Lilly2016 a work around I had for this was to download the `3.7.1` version and rename it to `3.8.0`

**Comment by vishalkaului** [comment]
Same in our project too.

**Comment by rammie** [comment]
Same problem here is as well.

**Comment by barancev** [comment]
Sorry. Our upload script by mistake attempted to upload files in text mode instead of binary. This has been just fixed and correct files has been uploaded.

**Comment by wiltzius** [comment]
Thank you!

**Comment by DGerich** [comment]
Thank you

**Comment by dragankrstonosic** [comment]
All WebDriver files are corrupted in version 3.8.1 (Release date 2017-12-01). The downloads are at path: https://selenium-release.storage.googleapis.com/index.html?path=3.8/
