### ISSUE TITLE
Selenium jar file and chrome driver

### ISSUE THREAD

**Issue by harshtrivedi134** [SeleniumHQ/selenium#5144]
I have tried a lot of combinations of selenium jar files and chrome versions. I am unable to run my automated behat tests.
I want to know which versions of selenium jar file and chrome driver are most stable?

**Comment by cgoldberg** [comment]
> I want to know which versions of selenium
> jar file and chrome driver are most stable?

the most recent

**Comment by harshtrivedi134** [comment]
Thanks for your comment @cgoldberg. I am using selenium 3.7.1 jar file and chrome driver 2.33
The logs are given below:
# Running the selenium driver
$ java -Dwebdriver.chrome.driver="chromedriver" -jar selenium-server-standalone-3.7.1.jar

12:32:40.444 INFO - Selenium build info: version: '3.7.1', revision: '8a0099a'
12:32:40.456 INFO - Launching a standalone Selenium Server
2017-11-30 12:32:40.630:INFO::main: Logging initialized @1721ms to org.seleniumhq.jetty9.util.log.StdErrLog
12:32:40.885 INFO - Driver class not found: com.opera.core.systems.OperaDriver
12:32:41.166 INFO - Driver provider class org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities {browserName: internet explorer, ensureCleanSession: true, platform: WINDOWS, version: } does not match the current platform MAC
12:32:41.166 INFO - Driver provider class org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities {browserName: MicrosoftEdge, platform: WINDOWS, version: } does not match the current platform MAC
12:32:41.350 INFO - Using the passthrough mode handler
2017-11-30 12:32:41.483:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2017-11-30 12:32:41.565:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@458c1321{/,null,STARTING} has uncovered http methods for path: /
2017-11-30 12:32:41.594:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@458c1321{/,null,AVAILABLE}
2017-11-30 12:32:41.746:INFO:osjs.AbstractConnector:main: Started ServerConnector@1500955a{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2017-11-30 12:32:41.747:INFO:osjs.Server:main: Started @2838ms
12:32:41.747 INFO - Selenium Server is up and running

# Console output in PHPStorm while running the behat tests:

Could not open connection: Unable to create new service: ChromeDriverService
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: '****', ip: '****', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.1', java.version: '1.8.0_121'
Driver info: driver.version: unknown

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
