### ISSUE TITLE
InvalidOperationException while creating the firefox instance

### ISSUE THREAD

**Issue by Narsimharao** [SeleniumHQ/selenium#5145]
## Meta -
OS:  Windows Server 2012 R2, version 6.3

Selenium Version:  3.7

Browser:  Firefox 55

Browser Version:  

## Actual Behavior -
System.InvalidOperationException: Process unexpectedly closed with status: 0
    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(String geckoDriverDirectory, FirefoxOptions options)
## Steps to reproduce -

                    var ffLocation = System.Environment.GetEnvironmentVariable("FIREFOX");
                    var options = new FirefoxOptions();
                    options.SetPreference("network.http.pipelining", true);
                    options.SetPreference("network.http.proxy.pipelining", true);
                    options.SetPreference("network.dns.disableIPv6", true);
                    options.SetPreference("webdriver.load.strategy", "unstable");
                    options.SetPreference("network.http.response.timeout", "400");
                    options.SetPreference("network.http.connection-timeout", "120");
                    options.SetPreference("network.http.keep-alive.timeout", "140");
                    options.SetPreference("network.http.request.max-start-delay", "15");
                    options.BrowserExecutableLocation = @ffLocation;
                    Instance = new FirefoxDriver(“gecko driver directory path”,options);

I am using c#. when I try locally the same code is working fine. but when I run the same in teamcity, I am seeing the above error. can you please help me

**Comment by barancev** [comment]
Do you run TeamCity agent as a service? Does it have access to interactive console (access to desktop)?

**Comment by barancev** [comment]
Please provide the complete log for investigarion.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
