### ISSUE TITLE
[Feature request] Add the possibility to create cookies with a SameSite attribute

### ISSUE THREAD

**Issue by GJFR** [SeleniumHQ/selenium#5148]
The constructor of the Cookie class supports cookie attributes like path, domain, secure, etc. Unfortunately there is no way to set the SameSite attribute. As Chrome and Opera already implement this and Firefox intends to do so ([link](https://www.chromestatus.com/feature/4672634709082112)), I think it would be a good idea for Selenium to support this. Besides, the SameSite attribute is backwards compatible so non-supporting browsers will just ignore it.

Therefore I suggest adding the possibility to configure the SameSite attribute in the same manner as the other attributes (through a dedicated parameter in the Cookie constructor). Another potential solution would be through a more generic parameter that can carry multiple attribute-value pairs, such that not every new attribute needs another parameter in the constructor.

**Comment by p0deje** [comment]
The cookie object is defined by [W3C WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-for-cookie-conversion), so you might want to raise this issue to [its bug tracker](https://github.com/w3c/webdriver/issues).
