### ISSUE TITLE
Localization - Executing scripts in different languages

### ISSUE THREAD

**Issue by Aditya1209** [SeleniumHQ/selenium#5156]
I just want to know how to execute my web driver scripts in other languages? I have my scripts developed in English language same scripts i want to execute in Spanish,Germany and other languages. do we have any capabilities to work with it? please give me guidance on this.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
