### ISSUE TITLE
Doc: "Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`" is really accurate?

### ISSUE THREAD

**Issue by acdcjunior** [SeleniumHQ/selenium#5157]
## Meta
- OS: Any
- Selenium Version:  3.8.0
- Browser: Chrome

The newest version logs:
> Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`

When using `DesiredCapabilities.chrome()`.

The documentation (https://sites.google.com/a/chromium.org/chromedriver/capabilities), on the other hand, specifies legitimate uses of `DesiredCapabilities` such as the `proxy` property (see example on that documentation page). Based on that, isn't the instruction to avoid  `DesiredCapabilities.chrome()` a bit misleading? When I got it I wanted to do something about it, but it seems nothing can really be done about it in many cases.

**Comment by barancev** [comment]
Please be more specific about mentioned many cases. Proxy can be set in ChromeOptions:
```new ChromeDriver(new ChromeOptions().setProxy(myProxy));```
Yes, chromedriver documentation is slightly behind the current implementation and should be updated.

**Comment by acdcjunior** [comment]
My main motivation were the chromedriver docs, but the capabilities I had in mind were the constants at https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/CapabilityType.java.

 Not all of them have an equivalent method on `ChromeOptions` (as proxy does), but, on the other hand, two things are to be considered: (1) not every capability of those constants are honored by chromedriver (or any other driver, this isn't specific to chromedriver), so no point in having a method in `ChromeOptions` for these and (2) `ChromeOptions` is a `MutableCapabilities`, so theoretically we could still set a capability as we would on a `DesiredCapabilities`, right?

I think this point two closes the case, I only noticed it when looking at the source code.

Thanks for the response.

**Comment by barancev** [comment]
Yes, ChromeOptions extends MutableCapabilities, so it can be used (and designed to be used) as a type safe chrome-specific capability collection.

**Comment by servantelectronics** [comment]
Java complains "cannot resolve symbol" myProxy? 
new ChromeDriver(new ChromeOptions().setProxy(myProxy));
