### ISSUE TITLE
send_keys() is having problems sending the character "3"

### ISSUE THREAD

**Issue by tylerpaskowski** [SeleniumHQ/selenium#5158]
## Meta -
OS:  OSX
Selenium Version:  3.8
Browser:  Chrome

Browser Version:  Version 62.0.3202.94 (64-bit)

## Expected Behavior -
send_keys("12345") -> to send the string 12345 to the given web element
## Actual Behavior -
"1245" gets sent, excluding the character `3`
## Steps to reproduce -
Opening a python shell to execute these commands, and viewing the results in the browser.

```
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium.webdriver.chrome import webdriver
>>> wd = webdriver.WebDriver()
>>> wd.get('https://google.com')
>>> wd.find_element_by_id("lst-ib").send_keys("test")
>>> wd.find_element_by_id("lst-ib").send_keys("12345")
>>> 
```

**Comment by lmtierney** [comment]
I cannot recreate this with your code. Regardless, this would be an issue for chromedriver. 

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by cgoldberg** [comment]
🎵 🎶 🎼 _**3 is the magic number**_ 🎵 🎶 🎼

**Comment by barancev** [comment]
Duplicate of #5058
