### ISSUE TITLE
Download file in headless chrome

### ISSUE THREAD

**Issue by jonhkr** [SeleniumHQ/selenium#5159]
## Meta -
OS:  OSX
Selenium Version:  3.8.1
Browser:  Chrome

## Expected Behavior -
Permit files to be downloaded in headless mode.

## Actual Behavior -
Files aren't downloaded.

## Steps to reproduce -
Launch chrome in headless mode and try to download any file.

Looks like it is a feature to prevent sites from downloading files when running chrome in headless mode.
https://bugs.chromium.org/p/chromium/issues/detail?id=696481

To permit downloads it's necessary to send a command to chrome.
I'm using java and I couldn't find a way to make it work.

I even tried sending a post request to `/session/:sessionId/chromium/send_command` but that didn't work.

**Comment by p0deje** [comment]
Apparently, this new command needs to be added to all the bindings.

**Comment by jonhkr** [comment]
I managed to get it working by issuing the above request directly to the `chromedriver` but using a development build of chromium.

**Comment by jonhkr** [comment]
This is how I did it:

```Java
ChromeDriverService driverService = ChromeDriverService.createDefaultService();

ChromeDriver driver = new ChromeDriver(driverService, options);

Map<String, Object> commandParams = new HashMap<>();
commandParams.put("cmd", "Page.setDownloadBehavior");

Map<String, String> params = new HashMap<>();
params.put("behavior", "allow");
params.put("downloadPath", downloadFilepathString);
commandParams.put("params", params);

ObjectMapper objectMapper = new ObjectMapper();
HttpClient httpClient = HttpClientBuilder.create().build();

String command = objectMapper.writeValueAsString(commandParams);

String u = driverService.getUrl().toString() + "/session/" + driver.getSessionId() + "/chromium/send_command";

HttpPost request = new HttpPost(u);
request.addHeader("content-type", "application/json");
request.setEntity(new StringEntity(command));
httpClient.execute(request);
```

**Comment by nstubi** [comment]
Hello,

Any plans to support setDownloadBehavior in order to download files using chrome in headless mode?

Any doc/examples in .Net would be much appreciated.

Regards,
Nicolas

**Comment by shreyanshp** [comment]
Even I am facing this same issue

**Comment by pulkitsharma07** [comment]
@p0deje, @jonhkr 
I am working on integrating this with the Ruby bindings, but for some reason I still not able to download in headless mode.

Could you please verify this spec, it is failing for me: https://github.com/pulkitsharma07/selenium/commit/1142e0b5ff859ffea3b5b3fccad23433ad08089f#diff-b1ade8967288d0002579a914345a9f56R72

For me even https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/test/chrome/devtools_test.js#L51 is failing.

I am using Chrome 64 and chromedriver 2.35, not sure what could be causing this.

**Comment by luke-hill** [comment]
I've popped an optimisation in, also, whilst not having worked in this area of the specs. Is there a reason you verbosely create the driver, there are helpers such as `create_driver!` which will check to see if an instance exists and/or create one.

**Comment by pulkitsharma07** [comment]
No particular reason, I missed that. The branch is not yet ready, Will do the changes to use `create_driver!`.

But, still, the main issue is that I am not able to download files in headless mode.

**Comment by jbustillos** [comment]
Is there an example for .NET?

**Comment by p0deje** [comment]
@pulkitsharma07 I cannot make it work too, maybe something has changed in recent Chrome/ChromeDriver?

**Comment by pulkitsharma07** [comment]
So, in my headless tests Chrome is crashing on clicking the element to download the file, whereas it is not crashing with the same scenario in normal mode. 

chromedriver logs:
```
  [1518706724.071][DEBUG]: DEVTOOLS COMMAND Input.dispatchMouseEvent (id=32) {                                                          |   25 [1518706738.962][DEBUG]: DEVTOOLS COMMAND Input.dispatchMouseEvent (id=34) {
     "button": "left",                                                                                                                  |   24    "button": "left",
     "clickCount": 1,                                                                                                                   |   23    "clickCount": 1,
     "modifiers": 0,                                                                                                                    |   22    "modifiers": 0,
     "type": "mouseReleased",                                                                                                           |   21    "type": "mouseReleased",
     "x": 20,                                                                                                                           |   20    "x": 20,
     "y": 16                                                                                                                            |   19    "y": 17
  --------------------------------------------------------------------------------------------------------------------------------------|   18 }
  --------------------------------------------------------------------------------------------------------------------------------------|   17 [1518706738.967][DEBUG]: DEVTOOLS RESPONSE Input.dispatchMouseEvent (id=34) {
  --------------------------------------------------------------------------------------------------------------------------------------|   16
  --------------------------------------------------------------------------------------------------------------------------------------|   15 }
  --------------------------------------------------------------------------------------------------------------------------------------|   14 [1518706738.967][INFO]: Waiting for pending navigations...
  --------------------------------------------------------------------------------------------------------------------------------------|   13 [1518706738.967][DEBUG]: DEVTOOLS COMMAND Runtime.evaluate (id=35) {
  --------------------------------------------------------------------------------------------------------------------------------------|   12    "expression": "1"
  --------------------------------------------------------------------------------------------------------------------------------------|   11 }
  --------------------------------------------------------------------------------------------------------------------------------------|   10 [1518706738.970][DEBUG]: DEVTOOLS RESPONSE Runtime.evaluate (id=35) {
  --------------------------------------------------------------------------------------------------------------------------------------|    9    "result": {
  --------------------------------------------------------------------------------------------------------------------------------------|    8       "description": "1",
  --------------------------------------------------------------------------------------------------------------------------------------|    7       "type": "number",
  --------------------------------------------------------------------------------------------------------------------------------------|    6       "value": 1
  --------------------------------------------------------------------------------------------------------------------------------------|    5    }
  }                                                                                                                                     |    4 }
  [1518706724.374][SEVERE]: Unable to receive message from renderer                                                                     |    3 [1518706738.970][INFO]: Done waiting for pending navigations. Status: ok
  [1518706724.374][INFO]: Waiting for pending navigations...                                                                            |    2 [1518706738.970][INFO]: RESPONSE ClickElement
  [1518706724.374][INFO]: Done waiting for pending navigations. Status: disconnected: not connected to DevTools                         |    1 [1518706742.192][INFO]: COMMAND QuitAll {
  [1518706724.374][DEBUG]: DevTools request: http://localhost:12345/json                                                                |      ---------------------------------------------------------------------------------------------------------------------------------
  [1518706724.375][DEBUG]: DevTools request failed                                                                                      |      ---------------------------------------------------------------------------------------------------------------------------------
  [1518706724.375][INFO]: RESPONSE ClickElement
```

**Comment by pulkitsharma07** [comment]
@p0deje I have filed https://bugs.chromium.org/p/chromedriver/issues/detail?id=2270. Please take a look.

**Comment by pulkitsharma07** [comment]
Upgrading to Chrome 65/chromedriver 2.36 fixed my crash issue with headless chrome.

**Comment by lmtierney** [comment]
After talking with the chromedriver team, the `send_command` will be moved to a w3c-compliant protocol extension endpoint (https://w3c.github.io/webdriver/webdriver-spec.html#protocol-extensions).

See the issue raised in the chromium bugtracker: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2307

**Comment by p0deje** [comment]
Ruby landed in master using `Driver#download_path=`, so we might need to refactor it once Chromium changes to W3C compliant commands.

**Comment by thehme** [comment]
I just realized that my js selenium webdriver test, which was checking the downloads page in the Chrome browser, does not work when I run it in headless mode. From the conversation above, I gather this is not yet supported, correct?

**Comment by guigs** [comment]
It works for me on Ruby with current master.

**Comment by jackkinsella** [comment]
> page.driver.browser.download_path

Technically this is available via the selenium-webdriver gem, as of v 3.13.0

Here's the implementation:
```
          params = {
            'cmd' => 'Page.setDownloadBehavior',
            'params' => {
              'behavior' => 'allow',
              'downloadPath' => path
            }
          }
          @bridge.send_command(params)
```

**Comment by Elangopalakrishnan** [comment]
@jackkinsella 

How we can implement above solution in c# script coz i need to download pdf and validate in chrome headless browser mode..

Please guide me on this..

Thanks in advance,
Elango

**Comment by jbustillos** [comment]
Please provide a c# example using selenium.

El 28 ene. 2019 8:15 a. m., Epk <notifications@github.com> escribió:

@jackkinsella<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjackkinsella&data=02%7C01%7C%7C59daa4d67e094f9da93c08d6852b1dc9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636842817554656333&sdata=QsU6Z6qBNfaou9sb2AhwNtlOT8paFAqDrf2sL4XJ%2Bks%3D&reserved=0>

How we can implement above solution in c# script coz i need to download pdf and validate in chrome headless browser mode..

Please guide me on this..

Thanks in advance,
Elango

**Comment by jackkinsella** [comment]
Sorry, don't know C#. I just provided the Ruby implementation as a reference to anyone who is facing the same issue and wanted to translate to their own environment.

**Comment by Elangopalakrishnan** [comment]
@jbustillos I have tried in c# please have a look into,, https://github.com/SeleniumHQ/selenium/issues/6895

**Comment by poojaghosh47** [comment]
Hi All,

Thanks for the solution : It worked for me for HeadlessBrowser Even for Local windows as well as in Linux machine , And Also on jenkins server... :)

ChromeDriverService driverService = ChromeDriverService.createDefaultService();

ChromeDriver driver = new ChromeDriver(driverService, options);

Map<String, Object> commandParams = new HashMap<>();
commandParams.put("cmd", "Page.setDownloadBehavior");

Map<String, String> params = new HashMap<>();
params.put("behavior", "allow");
params.put("downloadPath", downloadFilepathString);
commandParams.put("params", params);

ObjectMapper objectMapper = new ObjectMapper();
HttpClient httpClient = HttpClientBuilder.create().build();

String command = objectMapper.writeValueAsString(commandParams);

String u = driverService.getUrl().toString() + "/session/" + driver.getSessionId() + "/chromium/send_command";

HttpPost request = new HttpPost(u);
request.addHeader("content-type", "application/json");
request.setEntity(new StringEntity(command));
httpClient.execute(request);

**Comment by HaveSpacesuit** [comment]
Here is a .NET implementation to enable downloads using headless chrome:

```csharp
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.AddArgument("--headless");

ChromeDriver chromeDriver = new ChromeDriver(chromeOptions);

Dictionary<string, object> commandParameters = new Dictionary<string, object>
{
    ["behavior"] = "allow",
    ["downloadPath"] = @"C:\Downloads"
};

chromeDriver.ExecuteChromeCommand("Page.setDownloadBehavior", commandParameters);
```

**Comment by rishi1992** [comment]
> This is how I did it:
> 
> ```java
> ChromeDriverService driverService = ChromeDriverService.createDefaultService();
> 
> ChromeDriver driver = new ChromeDriver(driverService, options);
> 
> Map<String, Object> commandParams = new HashMap<>();
> commandParams.put("cmd", "Page.setDownloadBehavior");
> 
> Map<String, String> params = new HashMap<>();
> params.put("behavior", "allow");
> params.put("downloadPath", downloadFilepathString);
> commandParams.put("params", params);
> 
> ObjectMapper objectMapper = new ObjectMapper();
> HttpClient httpClient = HttpClientBuilder.create().build();
> 
> String command = objectMapper.writeValueAsString(commandParams);
> 
> String u = driverService.getUrl().toString() + "/session/" + driver.getSessionId() + "/chromium/send_command";
> 
> HttpPost request = new HttpPost(u);
> request.addHeader("content-type", "application/json");
> request.setEntity(new StringEntity(command));
> httpClient.execute(request);
> ```

This fix is not working with my configuration. I'm still unable to download a file in headless mode.

**Comment by rishi1992** [comment]
public static WebDriver getChromeDriver() throws IOException {
		//Initialize ChromeDriver

		ChromeOptions options = new ChromeOptions();
		Map<String, Object> prefs = new HashMap<>();
		//String downloadFilepath = System.getProperty("user.dir");
		prefs.put("safebrowsing.enabled", false);
		prefs.put("download.default_directory", System.getProperty("user.dir"));
		prefs.put("download.prompt_for_download", false);
		prefs.put("download.directory_upgrade", true);
		prefs.put("cmd", "Page.setDownloadBehavior");
		prefs.put("profile.default_content_settings.popups", 0);
		prefs.put("behavior", "allow");
		options.setExperimentalOption("prefs", prefs);
		options.addArguments("--disable-notifications");
		options.addArguments("--start-maximized");
		options.addArguments("disable-infobars");
		options.addArguments("--disable-gpu");
		options.addArguments("--headless");
		options.addArguments("window-size=1980,1080");
		options.addArguments("--allow-running-insecure-content");
		options.addArguments("--disable-extensions");
		options.addArguments("--no-sandbox");
		options.addArguments("--test-type");
		options.addArguments("--disable-web-security");
		//options.setBinary("C:\\Program Files (x86)\\Google\\Chrome");
		String chromedriverpath_1 = System.getProperty("user.dir");
		String chromedriverpath = chromedriverpath_1+"//chromedriver_2_44.exe";
		//System.out.println(chromedriverpath);
		System.setProperty("webdriver.chrome.driver", chromedriverpath);
		//System.setProperty("user.dir","//chromedriver_2.44.exe");



		ChromeDriverService driverService = ChromeDriverService.createDefaultService();
		ChromeDriver driver = new ChromeDriver(driverService, options);
		
		
		ObjectMapper objectMapper = new ObjectMapper();
		HttpClient httpClient = HttpClientBuilder.create().build();
		String command = null;
		try {
			command = objectMapper.writeValueAsString(prefs);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}

		String u = driverService.getUrl().toString() + "/session/" + driver.getSessionId() + "/chromium/send_command";
		HttpPost request = new HttpPost(u);
		request.addHeader("content-type", "application/json");
		request.setEntity(new StringEntity(command));
		httpClient.execute(request);
		return driver;
	}

**Comment by amishad02** [comment]
@rishi1992 did you found any solution can you please share.

**Comment by JDCain** [comment]
@amishad02 I use the following successfully

```
var driver = new ChromeDriver(driverService, options);

var param = new Dictionary<string, string> {{"behavior", "allow"}, {"downloadPath", DownloadPath}
};

var cmdParam = new Dictionary<string, object> {{"cmd", "Page.setDownloadBehavior"}, {"params", param}};

var url = driverService.ServiceUrl + "session/" + driver.SessionId + "/chromium/send_command";
var cli = new WebClient {Headers = {[HttpRequestHeader.ContentType] = "application/json"}};
_ = cli.UploadString(url, JsonConvert.SerializeObject(cmdParam));
```

**Comment by pouellet** [comment]
Anyone had success sending the `/session/:sessionId/chromium/send_command` command to a headless chrome process that was launched in a selenium grid? This solution seems to work well for a standalone selenium chrome, but I couldn't get it to work when proxied through the selenium grid.

**Comment by rishi1992** [comment]
This has worked for me,

 // Set the ChromeDriver path
    System.out.println("launching Chrome browser");
    String chromedriverPath = System.getProperty("user.dir") + "\\chromedriver_2_44.exe";
    System.setProperty("webdriver.chrome.driver", chromedriverPath);
    // Set the download folder path
    String downloadPath = System.getProperty("user.dir");
    //String downloadPath = "E:\\seleniumdownload";
    HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
    chromePrefs.put("safebrowsing.enabled", "true");
    chromePrefs.put("downloadPath", downloadPath); //This is one of the main line to be written
    chromePrefs.put("behavior", "allow"); //This is one of the main line to be written
    // Initialize Chrome options
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--disable-notifications");
    options.addArguments("--start-maximized");
    options.addArguments("disable-infobars");
    options.addArguments("--disable-gpu");
    options.addArguments("--headless");
    options.addArguments("window-size=1980,1080");
    options.addArguments("--allow-running-insecure-content");
    options.addArguments("--disable-extensions");
    options.addArguments("--no-sandbox");
    options.addArguments("--ignore-certificate-errors");
    // Initialize driver
    ChromeDriverService driverService = ChromeDriverService.createDefaultService();
    driver = new ChromeDriver(driverService, options);

    Map<String, Object> commandParams = new HashMap<>();
    commandParams.put("cmd", "Page.setDownloadBehavior");
    commandParams.put("params", chromePrefs);

    ObjectMapper objectMapper = new ObjectMapper();
    HttpClient httpClient = HttpClientBuilder.create().build();

    String command = objectMapper.writeValueAsString(commandParams);
    String u = driverService.getUrl().toString() + "/session/" + ((RemoteWebDriver) driver).getSessionId() + "/chromium/send_command";

    HttpPost request = new HttpPost(u);
    request.addHeader("content-type", "application/json");
    request.setEntity(new StringEntity(command));
    httpClient.execute(request);

**Comment by krzysztofrrr** [comment]
Any good solution/workaround in **Python** ?
I tried many ideas posted here and over internet, but nothing seems to work. I have a scenario when I just click on a download button and file get's downloaded(what is not happening in headless).

**Comment by chevi** [comment]
> Any good solution/workaround in **Python** ?
> I tried many ideas posted here and over internet, but nothing seems to work. I have a scenario when I just click on a download button and file get's downloaded(what is not happening in headless).

Please check, if there is a new tab is opened, when you click on a download link (for example if <a> has target="_blank" attribute). In my case download in headless with above solution doesn't work for downloads in a new tabs. So you can remove target="_blank" attribute by JS or get href and try to download by direct link in the same tab. This works for me.

**Comment by cgoldberg** [comment]
to enable headless downloads in Python:

```
from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options

options = Options()
options.headless = True 
driver = Chrome(options=options)
params = {'behavior': 'allow', 'downloadPath': '/path/for/download'}
driver.execute_cdp_cmd('Page.setDownloadBehavior', params)
```

**Comment by krzysztofrrr** [comment]
Thanks cgoldberg - that works fine!

**Comment by deeptechs** [comment]
> to enable headless downloads in Python:
> 
> ```
> from selenium.webdriver import Chrome
> from selenium.webdriver.chrome.options import Options
> 
> options = Options()
> options.headless = True 
> driver = Chrome(options=options)
> params = {'behavior': 'allow', 'downloadPath': '/path/for/download'}
> driver.execute_cdp_cmd('Page.setDownloadBehavior', params)
> ```

@cgoldberg What is your env? Chrome and chromedriver versions, standalone selenium or Grid?

Thanks

**Comment by ander7agar** [comment]
> to enable headless downloads in Python:
> 
> ```
> from selenium.webdriver import Chrome
> from selenium.webdriver.chrome.options import Options
> 
> options = Options()
> options.headless = True 
> driver = Chrome(options=options)
> params = {'behavior': 'allow', 'downloadPath': '/path/for/download'}
> driver.execute_cdp_cmd('Page.setDownloadBehavior', params)
> ```

@cgoldberg I am using this similar procedure with **selenium-webdriver for Node** and it does not work for me. I suspect that it is because in my case a new tab is opened to download file (`target "_blank"`). This is executed through JavaScript code when I click on a button.

Does this happen to anyone else?

**Comment by ander7agar** [comment]
Is there any way to make this permanent? That is, I want it to be enabled by default when a new instance of the browser is opened.

**Comment by ckempster** [comment]
> Is there any way to make this permanent? That is, I want it to be enabled by default when a new instance of the browser is opened.

Make use of Hooks

**Comment by ckempster** [comment]
> > Is there any way to make this permanent? That is, I want it to be enabled by default when a new instance of the browser is opened.
> 
> Make use of Hooks

An example I call from my hooks is 👍 
` private void createChromeBrowser() {
        WebDriverManager.chromedriver().setup();
        String downloadPath = System.getProperty("user.dir");
        HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
        chromePrefs.put("safebrowsing.enabled", "true");
        chromePrefs.put("downloadPath", downloadPath);
        chromePrefs.put("behavior", "allow");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--window-size=1366,768");
        options.addArguments("--disable-infobars");
        options.addArguments("--incognito");
        options.addArguments("--enable-javascript");
        options.addArguments("--disable-websecurity");
        options.addArguments("--start-maximised");
        options.addArguments("--ignore-certificate-errors");
        options.addArguments("--disable-popup-blocking");
        options.addArguments("--fast-start");
        options.addArguments("--javascript-harmony");
        options.addArguments("--no-sandbox");
        driver = new ChromeDriver(options);
    }`

**Comment by jonsamwell** [comment]
The command does not seem to be working now in Chrome 74+

```
browser.driver.sendChromiumCommand('Page.setDownloadBehavior', {
      behavior: 'allow',
      downloadPath: fullDownloadDirectoryPath
    });
```

Fails with the error

```
UnsupportedOperationError: POST /session/ac771ec3019f7b4c7191e2c9ae2b2056/chromium/send_command
```

Any idea why it is failing or how to get headless Chrome downloads working again?

**Comment by lmtierney** [comment]
Because the endpoint for that command changed in chromedriver to `/session/:sessionId/goog/cdp/execute`

**Comment by jonsamwell** [comment]
@lmtierney many thanks for this.  I am still getting a 500 internal server error now if I use that endpoint uri instead?

```
http://192.168.1.189:54193/wd/hub/session/d47c025d923e19c77aacab20f69809f6/goog/cdp/execute
```

**Comment by aditya2020** [comment]
> > This is how I did it:
> > ```java
> > ChromeDriverService driverService = ChromeDriverService.createDefaultService();
> > 
> > ChromeDriver driver = new ChromeDriver(driverService, options);
> > 
> > Map<String, Object> commandParams = new HashMap<>();
> > commandParams.put("cmd", "Page.setDownloadBehavior");
> > 
> > Map<String, String> params = new HashMap<>();
> > params.put("behavior", "allow");
> > params.put("downloadPath", downloadFilepathString);
> > commandParams.put("params", params);
> > 
> > ObjectMapper objectMapper = new ObjectMapper();
> > HttpClient httpClient = HttpClientBuilder.create().build();
> > 
> > String command = objectMapper.writeValueAsString(commandParams);
> > 
> > String u = driverService.getUrl().toString() + "/session/" + driver.getSessionId() + "/chromium/send_command";
> > 
> > HttpPost request = new HttpPost(u);
> > request.addHeader("content-type", "application/json");
> > request.setEntity(new StringEntity(command));
> > httpClient.execute(request);
> > ```
> 
> This fix is not working with my configuration. I'm still unable to download a file in headless mode.

I agree. My Chrome version is "78.0.3904.70". This doesnt work for me

**Comment by NN88** [comment]
This worked for me:

### Environment
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin18]
Rails 4.2.10
chromedriver: 79.0.3945.36
webdrivers (4.0.1)
capybara (3.24.0)

### Other resources
https://stackoverflow.com/questions/48810757/setting-default-download-directory-and-headless-chrome

### Implementation
```ruby
options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--window-size=1500,1500')
  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-gpu')
  options.add_argument('--disable-popup-blocking')

  options.add_preference(:download,
                          directory_upgrade: true,
                          prompt_for_download: false,
                          default_directory: ENV['downloads_folder']
                          )

  options.add_preference(:browser, set_download_behavior: { behavior: 'allow' })

Capybara.register_driver :headless_chrome do |app|
  driver = Capybara::Selenium::Driver.new(
                                app,
                                browser: :chrome,
                                options: options
                                )

  
  bridge = driver.browser.send(:bridge)
  path = '/session/:session_id/chromium/send_command'
  path[':session_id'] = bridge.session_id

  bridge.http.call(:post, path, cmd: 'Page.setDownloadBehavior',
                                params: {
                                  behavior: 'allow',
                                  downloadPath: ENV['downloads_folder'],
                              })

  driver
end

Capybara.javascript_driver = ENV['capybara_js_driver'].to_sym
```

**Comment by sanathfp** [comment]
I'm trying to get this working on javascript using nodejs. Is there a solution yet?

**Comment by RiJung** [comment]
not yet , still the same issue to trry to block downloads, "Download Path Option" work  "download_restrictions" works not
```

import { Builder, Capabilities } from 'selenium-webdriver';
import * as Chrome from 'selenium-webdriver/chrome.js'

export async function getDriver() {
  const service = new Chrome.ServiceBuilder("./selenium/chromedriver");
  const chromeOpts = await new Chrome.Options()
      .addArguments("--disable-infobars")
      .addArguments("--headless")
      .setUserPreferences({
        "download_restrictions" : 3
      })

  const driver = new Builder()
      .withCapabilities(Capabilities.chrome())
      .setChromeService(service)
      .setChromeOptions(chromeOpts)
      .build();

  return driver;
}

const driver = await getDriver()
driver.get("http://www.africau.edu/images/default/sample.pdf")
```

**Comment by victorigualada** [comment]
> I'm trying to get this working on javascript using nodejs. Is there a solution yet?

I've found a solution to this in Node.JS. You need to set the download path through the `driver#setDownloadPath(path)` method: https://github.com/SeleniumHQ/selenium/blob/83e80c246a2b68fbc6544d29fd5bff548a78c0f8/javascript/node/selenium-webdriver/chromium.js#L750

**Comment by diemol** [comment]
Closing as this went stale. If the issue still persists, please open an issue with the ChromeDriver team.
