### ISSUE TITLE
File upload browse button

### ISSUE THREAD

**Issue by Venky2005** [SeleniumHQ/selenium#5160]
I am working on clicking a browse button which brings the file upload window. 
Selenium doesn't click on Browse button. This works fine if i run it from Visual studio 2015, but not in 2017.

Environment:
Selenium version - Latest 3.6.0
Browser - Internet Explorer 9

Steps:
1. Open web application
2. Click to browse button
3. Selenium doesn't click on Browse button. This works fine if i run it from Visual studio 2015, but not in 2017.

Working code:
this.Driver.GetElement(browseButton).SendClick();
 
![image](https://user-images.githubusercontent.com/34226126/33536090-0f7e024c-d880-11e7-8907-878d9300311b.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
