### ISSUE TITLE
Outdated docs for "selenium-webdriver" npm package

### ISSUE THREAD

**Issue by SamuraiJack** [SeleniumHQ/selenium#5162]
The github docs has stuck on v3.3.0: http://seleniumhq.github.io/selenium/docs/api/javascript/page/Changes.html

Latest is 3.6.0 with quite substantial changes.

**Comment by jleyba** [comment]
Docs updated to `4.0.0-alhpa.1` (5234204decced61846a59d5b6c83753b73940267)
