### ISSUE TITLE
Unable to use extensions in 3.8+ node-chrome-debug

### ISSUE THREAD

**Issue by Zechtitus** [SeleniumHQ/selenium#5165]
I am running into issues attempting to run chrome extensions with the 3.8+ node-chrome-debug.

Rolled back to 3.7.1 and it worked (getting disable developer extensions popup however).

My app is using nightwatch with the following chrome options.
args: [
  '--no-sandbox',
  '--disable-popup-blocking',
  '--disable-infobars',
]

I fiddled with a bunch of the other chrome options without any success. I don't think it is specific to the extension but in my case the extension was PIA - I use this for DFP testing with google and I need the vpn location set. I made sure I had the latest extension downloaded. Attempting to access the extension directly with chrome-extension seemed to work fine from my own laptop.
chrome-extension://jplnlifepflhkbkgonidnobkakhmpnmh/html/foreground.html

Screenshot of issue when running in container:
![extension _blocked](https://user-images.githubusercontent.com/10325856/33581810-9251d650-d90f-11e7-944f-56ac8754a145.png)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
