### ISSUE TITLE
Unable to hide info level log message

### ISSUE THREAD

**Issue by rococode** [SeleniumHQ/selenium#5166]
I'm trying to get rid of this message: `When using the W3C Action commands, offsets are from the center of element` which appears every time `Actions.moveToElement` is called.
```
        String[] disable = {
                "org.openqa.selenium.interactions.Actions",
                "org.openqa.selenium.remote.ProtocolHandshake"
        };
        for (String s : disable) {
            java.util.logging.Logger.getLogger(s).setLevel(Level.SEVERE);
        }
```

This code does not work either, and it uses the exact format used to fetch the logger in the first place.

```       
Class[] d = {
                Actions.class,
                ProtocolHandshake.class
        };
        for (Class c : d) {
            java.util.logging.Logger.getLogger(c.getName()).setLevel(Level.OFF);
        }
```

This fails to disable either set of log messages. I'm fairly certain the problem is user error, but I don't know where. What am I doing wrong here?

**Comment by barancev** [comment]
I'm not a guru in logging tuning, but
```Logger.getLogger("org.openqa.selenium").setLevel(Level.SEVERE);```
disables them all.

**Comment by mau0727** [comment]
I tried to replicate the error by creating an action and calling the move to element function, but I could not see the any output in my console.

is this still an issue?

 WebElement element = driver.findElement(By.name("ctl00$cphMain$txtUsername"));
        Actions action= new Actions(driver);
        action.moveToElement(element);

**Comment by barancev** [comment]
Closing the issue, the comment above shows how to disable INFO level log messages.
