### ISSUE TITLE
[py3] selenium.common.exceptions.WebDriverException

### ISSUE THREAD

**Issue by hkyq** [SeleniumHQ/selenium#5167]
I've got this Python 3 code:

    login_username = "username"
    login_password = "password"

    driver = webdriver.Firefox()
    driver.get("url")

    def login():
        username = driver.find_element_by_name("tbUserName")
        password = driver.find_element_by_name("tbPassword")
        username.send_keys(login_username)
        password.send_keys(login_password)
        time.sleep(1)
        driver.find_element_by_name("btnSubmit").click()
        time.sleep(1)
        driver.refresh()
        time.sleep(3)
        get_content()

    def get_content():
        driver.get(different_url) # this url is seperate from the url above
        events_ = driver.find_elements_by_css_selector("div.textblock")
        
I'm able to call `login()` (which calls `get_content()`) once. The next time I get the following error:

    File "main.py", line 24, in handle
    login()
    File "main.py", line 27, in login
    driver.get(url)
    File "C:\Users\reyna\AppData\Local\Programs\Python\Python35\lib\site-     packages\selenium\webdriver\remote\webdriver.py", line 323, in get
        self.execute(Command.GET, {'url': url})
      File "C:\Users\reyna\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in  execute
        self.error_handler.check_response(response)
      File "C:\Users\reyna\AppData\Local\Programs\Python\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in     check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: Failed to write     response to stream

Note that when I say the next time I run it, I get the error, I mean the next time the functions are ran, not the entire script. Also, `driver.get(different_url)` is a new URL (the login cookies from the previous function are needed for this url). URL's have been changed for privacy reasons.

Help would be appreciated :grinning:

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
