### ISSUE TITLE
Unable to open firefox browser using geckdriver 

### ISSUE THREAD

**Issue by Jayshree23** [SeleniumHQ/selenium#5169]
Steps to Reproduce:-
1. Download all selenium Jars for selenium 3.8.0
2.use System.setProperty("webdriver.gecko.driver","path of gecko exe files"); 
3. WebDriver driver=new FireFoxDriver(); //not getting any option to import Firefox and throws a               compilation error.

**Actual Result:**- Firefox browser should be opened.

**Expected Result**:- Compilation error at step 3

**Comment by barancev** [comment]
Proper class name is FirefoxDriver, not FireFoxDriver

**Comment by Jayshree23** [comment]
It was a typo error I used FirefoxDriver.

**Comment by barancev** [comment]
So you have misconfigured your development environment. This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
