### ISSUE TITLE
Selenium Issue with Firefox Version 54.0 getting Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start. Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'

### ISSUE THREAD

**Issue by nravi07** [SeleniumHQ/selenium#5173]
ip: '127.0.1.1', os.name: '', os.arch: '', os.version: '4.10.0-40-generic', 
## Meta -
OS: Linux amd64  

Selenium Version:  3.6.0, Eclipse IDE

Browser:   Firefox

java.version: '1.8.0_131'
Web Drivers : geckodriver-v0.17.0-linux64.tar.gz
Can we know the supported versions of Selenium and Firefox gecdrivers with Eclipse IDE and Java version?  

Firefox version 54, Mozilla . As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:112)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:97)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at TestSele36.main(TestSele36.java:13)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:14720/hub/status] to be available after 45007 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:110)
	... 8 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 9 more

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by nravi07** [comment]
want to setup and run a simple test program using Selenium 3.6.0 and Java 1.8.0_131 and Firefox gecdrivers 17.0 in Unix Operating system.

My sample code to open url:www.google.com in Firefox WebBrowser.
_______________________________________________________
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;

public class TestSele36 {
	public static void main(String[] args) throws Exception {
System.out.println("Main Starts:");
		  System.setProperty("webdriver.firefox.marionette",
					"/home/ravi/Desktop/Selenium-3.6.0/geckodriver-v0.17.0-linux64.tar.gz");

FirefoxDriver driver = new FirefoxDriver();
 System.out.println("Browser Starts with Google.com:");
driver.get("https://www.google.com/");
   }
}

Expected Output:
1. Firefox browser open google search site.

While running the program in Eclipse IDE we are getting the following:

- It was invoking the Firefox Browser but it was not loading the google search web page. It was showing empty web page and getting the below error message:

Main Starts:
1512561868056	addons.manager	DEBUG	Application has been upgraded
1512561868075	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1512561868077	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1512561868081	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1512561868084	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1512561868085	addons.manager	DEBUG	Starting provider: XPIProvider
1512561868085	addons.xpi	DEBUG	startup
1512561868086	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /tmp/anonymous245989992443395486webdriver-profile/extensions/webdriver-staging
1512561868086	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /tmp/anonymous245989992443395486webdriver-profile/extensions/fxdriver@googlecode.com
1512561868087	addons.xpi	INFO	Removing all system add-on upgrades.
1512561868087	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1512561868088	addons.xpi	INFO	Mapping firefox@getpocket.com to /opt/firefox54/browser/features/firefox@getpocket.com.xpi
1512561868088	addons.xpi	INFO	Mapping screenshots@mozilla.org to /opt/firefox54/browser/features/screenshots@mozilla.org.xpi
1512561868089	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /opt/firefox54/browser/features/e10srollout@mozilla.org.xpi
1512561868089	addons.xpi	INFO	Mapping aushelper@mozilla.org to /opt/firefox54/browser/features/aushelper@mozilla.org.xpi
1512561868089	addons.xpi	INFO	Mapping webcompat@mozilla.org to /opt/firefox54/browser/features/webcompat@mozilla.org.xpi
1512561868090	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /opt/firefox54/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1512561868091	addons.xpi	DEBUG	checkForChanges
1512561868091	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1512561868091	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1512561868092	addons.xpi	DEBUG	New add-on fxdriver@googlecode.com in app-profile
1512561868093	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1512561868095	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1512561868096	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1512561868097	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
1512561868097	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1512561868098	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1512561868098	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1512561868098	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1512561868099	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1512561868099	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1512561868099	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1512561868100	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1512561868100	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1512561868100	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous245989992443395486webdriver-profile/extensions/fxdriver@googlecode.com","st":1512561867000,"mt":1512561867000}},"app-system-defaults":{"firefox@getpocket.com":{"d":"/opt/firefox54/browser/features/firefox@getpocket.com.xpi","st":1496949508000},"screenshots@mozilla.org":{"d":"/opt/firefox54/browser/features/screenshots@mozilla.org.xpi","st":1496949508000},"e10srollout@mozilla.org":{"d":"/opt/firefox54/browser/features/e10srollout@mozilla.org.xpi","st":1496949508000},"aushelper@mozilla.org":{"d":"/opt/firefox54/browser/features/aushelper@mozilla.org.xpi","st":1496949508000},"webcompat@mozilla.org":{"d":"/opt/firefox54/browser/features/webcompat@mozilla.org.xpi","st":1496949508000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/opt/firefox54/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1496949508000}}}
1512561868108	addons.xpi-utils	DEBUG	Opening XPI database /tmp/anonymous245989992443395486webdriver-profile/extensions.json
1512561868109	addons.xpi-utils	DEBUG	New add-on fxdriver@googlecode.com installed in app-profile
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1512561868126	addons.xpi	WARN	Add-on fxdriver@googlecode.com is not correctly signed.
1512561868127	addons.xpi	WARN	Add-on fxdriver@googlecode.com is not correctly signed.
1512561868129	DeferredSave.extensions.json	DEBUG	Save changes
1512561868130	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1512561868133	DeferredSave.extensions.json	DEBUG	Starting timer
1512561868138	DeferredSave.extensions.json	DEBUG	Save changes
1512561868138	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
1512561868148	DeferredSave.extensions.json	DEBUG	Save changes
1512561868149	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1512561868153	DeferredSave.extensions.json	DEBUG	Save changes
1512561868153	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
1512561868162	DeferredSave.extensions.json	DEBUG	Save changes
1512561868163	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1512561868171	DeferredSave.extensions.json	DEBUG	Starting write
1512561868176	DeferredSave.extensions.json	DEBUG	Save changes
1512561868176	DeferredSave.extensions.json	DEBUG	Data changed while write in progress
1512561868176	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1512561868180	DeferredSave.extensions.json	DEBUG	Save changes
1512561868180	addons.manager	DEBUG	Registering startup change 'installed' for fxdriver@googlecode.com
1512561868181	addons.xpi-utils	DEBUG	Make addon app-profile:fxdriver@googlecode.com visible
1512561868181	DeferredSave.extensions.json	DEBUG	Save changes
1512561868181	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1512561868190	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox54/browser/features/firefox@getpocket.com.xpi
1512561868196	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1512561868196	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1512561868197	DeferredSave.extensions.json	DEBUG	Save changes
1512561868197	addons.manager	DEBUG	Registering startup change 'installed' for screenshots@mozilla.org
1512561868197	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox54/browser/features/screenshots@mozilla.org.xpi
1512561868199	addons.xpi	DEBUG	Calling bootstrap method install on screenshots@mozilla.org version 6.6.0
1512561868199	addons.xpi-utils	DEBUG	Make addon app-system-defaults:screenshots@mozilla.org visible
1512561868200	DeferredSave.extensions.json	DEBUG	Save changes
1512561868200	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1512561868201	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox54/browser/features/e10srollout@mozilla.org.xpi
1512561868203	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.50
1512561868204	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1512561868205	DeferredSave.extensions.json	DEBUG	Save changes
1512561868205	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1512561868206	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox54/browser/features/aushelper@mozilla.org.xpi
1512561868207	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1512561868207	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1512561868208	DeferredSave.extensions.json	DEBUG	Save changes
1512561868208	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1512561868209	addons.xpi	DEBUG	Loading bootstrap scope from /opt/firefox54/browser/features/webcompat@mozilla.org.xpi
1512561868210	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.1
1512561868210	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1512561868211	DeferredSave.extensions.json	DEBUG	Save changes
1512561868211	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1512561868212	DeferredSave.extensions.json	DEBUG	Save changes
1512561868212	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"{f205134a-4901-47ca-ba41-bc8d1819759b}","location":"app-profile","version":"3.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous245989992443395486webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1512561867000,"updateDate":1512561867000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":3279485,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"48.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868213	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{d4884238-779f-443e-a8c4-915b90be67f5}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/features/firefox@getpocket.com.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":913904,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868213	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1512561868213	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{fccb1b8a-69e2-4850-b3f9-06f279c38cd4}","location":"app-system-defaults","version":"6.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Screenshots","description":null,"creator":null,"homepageURL":"https://pageshot.net/"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/features/screenshots@mozilla.org.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":716271,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0a1","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868213	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1512561868214	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{d73b7999-ef2b-45f6-87c9-9fc93780d9ac}","location":"app-system-defaults","version":"1.50","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/features/e10srollout@mozilla.org.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":12517,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868214	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1512561868214	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{755af0fb-b73e-4c02-a162-929ef10de01c}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/features/aushelper@mozilla.org.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868214	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1512561868215	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{b4bdfe91-fb1f-42fb-bbcf-92e678b1568b}","location":"app-system-defaults","version":"1.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/features/webcompat@mozilla.org.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":9004,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1512561868215	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1512561868215	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{025a84c4-21cd-4487-8c14-ed4dfbd31300}","location":"app-global","version":"54.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://browser/content/default-theme-icon.svg","icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/opt/firefox54/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1496949508000,"updateDate":1496949508000,"applyBackgroundUpdates":1,"skinnable":true,"size":2912,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0","maxVersion":"54.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
1512561868215	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1512561868217	DeferredSave.extensions.json	DEBUG	Save changes
1512561868218	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1512561868218	addons.xpi-utils	DEBUG	Updating add-on states
1512561868220	addons.xpi-utils	DEBUG	Writing add-ons list
1512561868222	addons.xpi	DEBUG	Registering manifest for /opt/firefox54/browser/features/aushelper@mozilla.org.xpi
1512561868222	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1512561868223	addons.xpi	DEBUG	Registering manifest for /opt/firefox54/browser/features/e10srollout@mozilla.org.xpi
1512561868223	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.50
1512561868224	addons.xpi	DEBUG	Registering manifest for /opt/firefox54/browser/features/firefox@getpocket.com.xpi
1512561868224	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1512561868225	addons.xpi	DEBUG	Registering manifest for /opt/firefox54/browser/features/screenshots@mozilla.org.xpi
1512561868226	addons.xpi	DEBUG	Calling bootstrap method startup on screenshots@mozilla.org version 6.6.0
1512561868226	addons.xpi	DEBUG	Registering manifest for /opt/firefox54/browser/features/webcompat@mozilla.org.xpi
1512561868226	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.1
1512561868230	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1512561868230	addons.manager	DEBUG	Provider finished startup: XPIProvider
1512561868230	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1512561868230	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1512561868231	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1512561868231	addons.manager	DEBUG	Starting provider: GMPProvider
1512561868235	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1512561868235	addons.manager	DEBUG	Provider finished startup: GMPProvider
1512561868235	addons.manager	DEBUG	Starting provider: PluginProvider
1512561868236	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1512561868236	addons.manager	DEBUG	Provider finished startup: PluginProvider
1512561868236	addons.manager	DEBUG	Completed startup sequence
1512561869724	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1512561869728	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1512561869730	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1512561870056	DeferredSave.extensions.json	DEBUG	Write succeeded
1512561870056	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1512561870057	DeferredSave.extensions.json	DEBUG	Starting timer
1512561870086	DeferredSave.extensions.json	DEBUG	Starting write
1512561870091	addons.repository	DEBUG	No addons.json found.
1512561870092	DeferredSave.addons.json	DEBUG	Save changes
1512561870098	DeferredSave.addons.json	DEBUG	Starting timer
1512561870139	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1512561870139	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1512561870140	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1512561870152	DeferredSave.addons.json	DEBUG	Starting write
1512561870169	DeferredSave.extensions.json	DEBUG	Write succeeded
1512561870204	DeferredSave.addons.json	DEBUG	Write succeeded
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'RaviUbuntuVM', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-40-generic', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:112)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:97)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at TestSele36.main(TestSele36.java:13)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:28402/hub/status] to be available after 45001 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:110)
	... 8 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 9 more

_________________________________________________________________
**Can we know what are changes we need do to fix this issue.**

**Comment by barancev** [comment]
'webdriver.firefox.marionette' is a boolean property.
To set path to geckodriver one can use 'webdriver.firefox.driver' property.

**Comment by cgoldberg** [comment]
>> System.setProperty("webdriver.firefox.marionette",
>> "/home/ravi/Desktop/Selenium-3.6.0/geckodriver-v0.17.0-linux64.tar.gz");

> To set path to geckodriver one can use 'webdriver.firefox.driver' property.

also, it looks like you are trying to use `geckodriver-v0.17.0-linux64.tar.gz` as a driver.  You need to the extract geckodriver binary from the tarball before using it.

**Comment by nravi07** [comment]
Thanks for the solution. Now we are able to invoke the geckodrives and working Firefox Web Browser.

**Comment by Savithri123** [comment]
Hi all,
I am also getting the same issue.
"**Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start**."

Firefox Version: 58.0.2
Gecko Driver Version:  geckodriver-v0.19.1-win64
Selenium Version : selenium-java-3.9.1

My Code is >>
package Test1;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Test1 {

	public static void main(String[] args) throws InterruptedException {

	System.setProperty("webdriver.firefox.marionette","C:\\Users\\user\\Downloads\\geckofolder\\geckodriver");
	WebDriver driver = new FirefoxDriver();
	driver.get("http://www.facebook.com");
		 
         System.out.println("Successfully opened the website www.facebook.com");
		 
	Thread.sleep(5000);
        driver.quit();
	}
}
I Tried both **webdriver.firefox.marionette** and **webdriver.gecko.driver** But Still getting the same problem.
Can Anyone please provide a solution for this? Thanks in advance.
