### ISSUE TITLE
Safari does not quit calling .quit

### ISSUE THREAD

**Issue by ilovegithub2** [SeleniumHQ/selenium#5179]
## Meta -
OS: OSX highSierra
Selenium Version:  
Ruby selenium-webdriver v 3.8.0
Browser: Safari   Desktop

Browser Version:  11.0.1 (13604.3.5)

## Steps to reproduce -
Run this code and expect the browser to quit.

require 'selenium-webdriver'

browser = Selenium::WebDriver.for :safari

browser.get 'https://www.e2x.co.uk'

sleep 2

browser.quit

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/

**Comment by himildesai** [comment]
@ilovegithub2 Did you open a bug with Apple? Can you add a link to it here?

**Comment by lmtierney** [comment]
@himildesai bugs are not public and are only visible to the person submitting

**Comment by tarasmytlovych** [comment]
@ilovegithub2 Any news from apple?
I have the same with java 1.8.0_211-b12, selenium-java 3.141.59, Safari v12.1, mac os 10.14.4
