### ISSUE TITLE
Custom user agent string in MicrosoftEdge webdriver

### ISSUE THREAD

**Issue by SagitYehezkeli** [SeleniumHQ/selenium#5181]
## Meta -
OS:  Windows 10

Selenium Version:  3.6.0

Browser:  MicrosoftEdge

Browser Version:  41.16299.15.0

## Expected Behavior -
Be able to custom a user agent string from Edge webdriver python.
## Actual Behavior -
This behavior dose not exsist at all in Edge. 
In Firefox there is: profile.set_preference('general.useragent.override', XXX)
In Chrome there is: MyChromeOptions().add_argument('--user-agent=' + XXX)

**Comment by lmtierney** [comment]
Edge has not provided us with a way to specify preferences/options. When it does, we will add that functionality.

Please log any Edge & MicrosoftWebdriver issues with Microsoft: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/?page=1&q=webdriver
