### ISSUE TITLE
Version check in nodes no longer works

### ISSUE THREAD

**Issue by marsh0lion** [SeleniumHQ/selenium#5184]
OS:  Ubuntuu 16.04
Selenium Version:  3.8.1 (both hubs and nodes)
Browser:  Chrome 
Browser Version:  62.0.3202.94 (Official Build) (64-bit)

## Steps to reproduce -
1. Set up a selenium hub
2. Set up 1 node with the following capability:
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
	  "platform": "LINUX",
	  "version": "99"
    }
3. Set up a second node with the following capability:
    {
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
	  "platform": "LINUX",
	  "version": "50"
    }
4. Fire off 2 selenium scenarios targeting chrome version 99

## Expected Behavior -
One Scenario executes with 1 scenario waiting (on the node with version 99)

## Actual Behavior -
Both nodes run 1 scenario each

## Additional information
* This setup worked on 3.7.0, I was unable to test it on 3.8.0 (due to other selenium grid issues).
* Firefox (gecko Driver) actually checks the version number of the browser (so this browser hack to direct to nodes doesn't work).

## My use case
On my development machine, I have one of the nodes directing output to xvfb so that it doesn't disturb my work. The other node is visible so I can see what is wrong with my tests

**Comment by barancev** [comment]
I can't preproduce the issue, please be more specific.

What I did to reproduce it:
1) Start hub
java -jar selenium-server-standalone-3.8.1.jar -role hub
2) Start two nodes:
java -jar selenium-server-standalone-3.8.1.jar -role node -capabilities "browserName=chrome,version=99" -port 5555
java -jar selenium-server-standalone-3.8.1.jar -role node -capabilities "browserName=chrome,version=50" -port 6666
3) Run a script
DesiredCapabilities capabilities = DesiredCapabilities.chrome();
capabilities.setCapability("version", "99");
RemoteWebDriver driver1 = new RemoteWebDriver(capabilities);
RemoteWebDriver driver2 = new RemoteWebDriver(capabilities);

The result you can see on the screenshot below, one session is active, one request is queued:
![image](https://user-images.githubusercontent.com/617090/33704457-93b84058-db3d-11e7-8f22-bf5148ef8729.png)

**Comment by marsh0lion** [comment]
Hi barancev,
Thanks for your reply.
A couple of differences that I note in your attempted replication (although I'm not sure of the affect they have on the issue):
- Difference in OS. Your selenium picks up VISTA (I'm guessing windows 10) whereas mine picks up LINUX (ubuntu 16.04 to be exact).
- I start all my instances using config files (and don't use the capabilities command line argument you did) - switching to using command line arguments had no effect.
- I'm connecting via PHP (which would use '->' to call a function on an object).

I'm not 100% sure where the connection details are set up in our application (a quick grep on function names you used found nothing), but as you can see via the hub log (below) it looks like the data is being sent through correctly (and nothing has changed our end between 3.7.1 & 3.8.1)

Hub log:
07:38:02.808 INFO - Got a request to create a new session: Capabilities {browser: firefox, browserName: chrome, browserVersion: ANY, chromeOptions: {args: [--disable-infobars, --disable-background-thrott...], prefs: {credentials_enable_service: false}}, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, name: t11, tags: [e0a871debb60, PHP 7.1.11], version: 99}
07:38:02.820 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, se:CONFIG_UUID=b5361a51-9a01-4725-8711-94a2beddfe4c, browserName=chrome, maxInstances=1, version=50, platform=LINUX}
07:38:06.677 INFO - Got a request to create a new session: Capabilities {browser: firefox, browserName: chrome, browserVersion: ANY, deviceOrientation: portrait, deviceType: tablet, ignoreZoomSetting: false, max-duration: 300, name: Behat Test, platform: LINUX, selenium-version: 2.31.0, version: 99}
07:38:06.679 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, se:CONFIG_UUID=3d79351b-cb88-428d-a521-cb02836bcfcf, browserName=chrome, maxInstances=1, version=99, platform=LINUX}
![selenium hub](https://user-images.githubusercontent.com/1079133/33733306-465edc2a-dbee-11e7-846c-4320e7591bcf.png)

Startup command for node:
java -Dwebdriver.chrome.driver=../chromedriver -Dwebdriver.gecko.driver=../geckodriver -jar selenium-server-standalone-3.8.1.jar -role node -nodeConfig node-config.json

Startup command for hub:
java -jar selenium-server-standalone-3.8.1-hub.jar -role hub -hubConfig hub-config.json

Java version:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by barancev** [comment]
Your new session request contains `browserName: chrome, browserVersion: ANY` specification.

`browserVersion` (that is W3C compatible capability name) has precedence over `version` (a legacy capability name).

**Comment by marsh0lion** [comment]
Thanks barancev,
Now to update my setup. As a side note, I've had a quick scan of the Changelog and couldn't see any reference to the change (not that I'd looked at them in the first place ...).

**Comment by barancev** [comment]
A client can pass either verision (OSS) or browserVersion (W3C) capability, or both ones, but if you pass both please use the same value.

Changelog has no special mention of browserVersion capability, we just claimed W3C support in general, that includes this capability.
