### ISSUE TITLE
WebDriverException in python binding of 'set_page_load_timeout'

### ISSUE THREAD

**Issue by alex4200** [SeleniumHQ/selenium#5187]
## Meta -
OS:  Ubuntu 16.04.3
Selenium Version:  3.8.0
Browser:   Firefox 57.0 / geckodriver 0.16.0

## Expected Behavior -

The method `set_page_load_timeout`  works as described in the [documentation](http://selenium-python.readthedocs.io/api.html)

## Actual Behavior -

```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    driver.set_page_load_timeout(3)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 833, in set_page_load_timeout
    'type': 'page load'})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: timeouts
```

## Steps to reproduce -

```
from selenium import webdriver
driver = webdriver.Firefox()
driver.set_page_load_timeout(3)
driver.get("http://selenium-python.readthedocs.io")
```

with python 2.7.12

**Comment by lmtierney** [comment]
You need geckodriver version `0.18.0` or greater for this to work

**Comment by alex4200** [comment]
On which documentation can I see that the command `set_page_load_timeout`is implemented in geckodriver 0.18.0? On [this page](http://selenium-python.readthedocs.io/api.html) there is no hint for that whatsoever...

**Comment by lmtierney** [comment]
https://github.com/mozilla/geckodriver/releases/tag/v0.18.0 read the 'Fixed' area

**Comment by AutomatedTester** [comment]
that site is not maintained by the selenium project. As for where it is
documented, it is documented on the Mozilla github page
https://github.com/mozilla/geckodriver/releases/tag/v0.18.0

**Comment by alex4200** [comment]
And where is the mention of the set timeout thingy? Is it `The SetTimeouts command maps to the Marionette setTimeouts command, which makes geckodriver compatible with Firefox 56 and greater`? And if so, what the heck is a 'Marionette'? 

How is it possible for someone not involved in all the firefox/webdriver/geckodriver/selenium/Marionette development to find proper documentation? Or is it ok to ask every bit of information and question here on the github issues? What is the suggest way of finding actual information regarding selenium tests?

**Comment by lmtierney** [comment]
Yes, that is the message. Marionette is what drives Firefox along with geckodriver. Selenium talks to geckodriver, geckodriver talks to Marionette, Marionette is built into Firefox and controls it. https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette

Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). Or join us in IRC in `#selenium` on Freenode.

**Comment by cgoldberg** [comment]
official python api docs: https://seleniumhq.github.io/selenium/docs/api/py/api.html
