### ISSUE TITLE
Unable to bind to locking port 7054 within 45000 ms

### ISSUE THREAD

**Issue by suman583** [SeleniumHQ/selenium#519]
I get this error occasionally when multiple tests are run in parallel with selenium 2.44 and Firefox 33.

Looking at the selenium code (NewProfileExtensionConnection.java ) its clear that lock is taken on 7054 before  finding a free port for firefox and cleanup/creation of friefox profile directory. If there are say 100 tests running in parallel and  if one tests take 1 sec in this block then naturally this  error will come.

I  understand that the driver is using 7054 as a mutex to ensure that only one process is scanning for a free port at any one time but why should  other methods (like layoutondisk , cleanup etc) be inside this lock
      profileDir = profile.layoutOnDisk();
      process.clean(profile, profileDir);

Ideally the lock should only have been taken  for this line execution 
 port = determineNextFreePort(profile.getIntegerPreference(PORT_PREFERENCE,
DEFAULT_PORT));

If this was the case then the lock would have been released faster and we could have avoided this issue.

also, can we provide a setter method to pass a custom locking port ?Right now its hardcoded to 7054.

**Comment by krosenvold** [comment]
At least historically this has not used to work, since firefox also has a singleton regarding temp dir for the profile. Unless you can point to a specific issue at mozilla where this has been fixed/changed, it still works that way. Feel free to reopen this issue if you have any indications that this has changedn
