### ISSUE TITLE
xpath doesn't work

### ISSUE THREAD

**Issue by ElDzi** [SeleniumHQ/selenium#5190]
I'm using ChromeDriver.
Code: `        Select s = new Select(findElement(By.xpath("'//select[@class=\"PI__select PI__input js-select js-select-SIZE js-select-SIZE-static\"]")));`

On site i have
`<div class="PI__wrap js-insert-select-sizes"><div class="PI__input-wrap PI__select_wrap js-select-wrap-SIZE js-select-wrap-SIZE-static"><div class="PI__placeholder js-placeholder">SIZE</div><select class="PI__select PI__input js-select js-select-SIZE js-select-SIZE-static"><option value="">SIZE</option><option value="53015720659">39</option><option value="53015720723">40</option><option value="53015720787">41</option><option value="53015720851">42</option><option value="53015720915">43</option><option value="53015720979" class="sold-out" disabled="">44</option><option value="53015721043">45</option><option value="53015721107">46</option><option value="53015721171">47</option></select><div class="cf"></div></div></div>`

Why it's doesn't work?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
