### ISSUE TITLE
SSL Pfx Authentication

### ISSUE THREAD

**Issue by carliandro** [SeleniumHQ/selenium#5191]
OS:  Windows 10

Selenium Version:  
3.5.3 with Eclipse IDE

Browser:  
MS Edge
PhantomJS

Browser Version:  
Microsoft Edge 40.15063.674.0(64-bit)
Phantomjs 3.1

## Expected Behavior -
Authentication with specific pfx certificate without need  choose certificate in pop up

## Actual Behavior -
Need to choose the certificate in pop

## Steps to reproduce -
Use any site that needs to authenticate with pfx certificate

**Comment by barancev** [comment]
PhantomJS support has been discontinued.
EdgeDriver issues should be sent to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
