### ISSUE TITLE
custom chrome binary location not honored

### ISSUE THREAD

**Issue by rab2215** [SeleniumHQ/selenium#5192]
When specifying a custom chrome binary location via ChromeOptions, the chromedriver still opens chrome from the default location.  This issue began after upgrading from 3.4.0 to 3.7.1 (also tried 3.8.1 with the same result).  

I am setting the binary location in this manner:

```java
private String browserLocation = “location of browser exe“;

Map<String, Object> chromeOptions = new HashMap<>(); chromeOptions.put("binary", browserLocation);
  DesiredCapabilities desiredCapabilities = new DesiredCapabilities();  
desiredCapabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
```

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions).

**Comment by rab2215** [comment]
The issue occurred using the Selenium Grid, Selenoid, as well as when testing locally.  The issue only occurs when changing the Java API version.  

1. On client, change the location of the chrome browser.exe (in our case its an Electron application).

2. Set desired capabilities to new location.
```java
private String browserLocation = “location of browser exe“;
 
Map<String, Object> chromeOptions = new HashMap<>(); 
chromeOptions.put("binary", browserLocation);

  DesiredCapabilities desiredCapabilities = new DesiredCapabilities();  
desiredCapabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions); 
```
3.  Start session:
```java
WebDriver webDriver = new RemoteWebDriver(seleniumGridUrl, desiredCapabilities);
```
4.  Browser will start at the default location, not location defined via ChromeOptions.

**Comment by barancev** [comment]
You have to set browser name in capabilities:
```
desiredCapabilities.setBrowserName("chrome");
```

Or, better, init the driver using new API:
```
ChromeOptions options = new ChromeOptions().setBinary("location of browser exe");
WebDriver webDriver = new RemoteWebDriver(seleniumGridUrl, options);
```

**Comment by rab2215** [comment]
Ok so I left out the other capabilities that are supplied because they were not relevant to the issue at hand.  I am supplying the chrome browser capability, I can update the steps and add all the capabilities I am using if necessary.  If the capability was really the issue i doubt that it would have worked on the previous version.

**Comment by barancev** [comment]
That's exactly what we requested: please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment]
Also provide the log from the server console (both the hub and the node that handled the session)

**Comment by rab2215** [comment]
So I'm having issues reproducing the problem now except for when using selenoid.  Seems as if it may only be selenoid related, this can be closed until I can troubleshoot the issue more.
