### ISSUE TITLE
All tests failing with EOFError

### ISSUE THREAD

**Issue by gischer** [SeleniumHQ/selenium#5193]
## Meta -
OS:  OSX 10.12.6
Selenium Version:  3.8.0
Browser:  Chrome, Chromium Webdriver

Browser Version:  Version 63.0.3239.84 (Official Build) (64-bit)
ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)

## Expected Behavior -

Tests run and browser closes

## Actual Behavior -
All tests, even trivial ones created for this purpose, terminate with EOFError and leave the instantiated browser open.  I can get 5 or 6 copies of Chrome running on my desktop at once.

## Steps to reproduce -

I feel that it is quite likely that I have having some version mismatch problem, but I don't know what it is.  I just hit a different issue that required that I rebuild all of my brew infrastructure.

I've downloaded new versions of Xcode and Xcode command line tools, but this did not help.  Searching the web gave me year-old pages that say to update my version of chromedriver and selenium.  That hasn't helped, as far as I can see.

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue.  See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
Also provide the version of chrome and chromdriver you're using

**Comment by gischer** [comment]
Wow, that's odd.  I cut and pasted the versions into the original, but they aren't showing.  Comment syntax issues, I guess.

Chrome: Version 63.0.3239.84 (Official Build) (64-bit)
Chromedriver: ChromeDriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)

**Comment by lmtierney** [comment]
Ah, this could be an issue with chrome `63`. Google needs to release a new chromedriver to "officially" support Chrome `63`. I don't suppose you can downgrade to chrome `62`?

**Comment by gischer** [comment]
I am using Ruby on Rails, and invoking tests using Rspec. My simplest test that is failing uses Capybara on top of Selenium.  The file looks like this:

require "rails_helper"
require "spec_helper"

feature "User Administration:", :js => true do
  scenario "Dumb Test" do
    visit "/larpthings/home"
    expect(page).to have_content "LarpThings"
  end
end
----------
My spec/rails_helper.rb file contains these lines:

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end
--------
It fails with this output:
Failures:

  1) User Administration: Dumb Test
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit "/larpthings/home"
          
          Selenium::WebDriver::Error::UnknownError:
            unknown error: cannot determine loading status
            from unknown error: missing or invalid 'entry.level'
              (Session info: chrome=63.0.3239.84)
              (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.6 x86_64)
          # ./spec/features/test_spec.rb:6:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: TCPSocket.open(conn_address, conn_port, @local_host, @local_port)
          
          Errno::ECONNREFUSED:
            Connection refused - connect(2) for "127.0.0.1" port 9516
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:879:in `open'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:878:in `connect'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:1453:in `begin_transport'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:1410:in `transport_request'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:1384:in `request'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:853:in `start'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/2.1.0/net/http.rb:1375:in `request'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:299:in `delete_all_cookies'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/options.rb:81:in `delete_all_cookies'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara/selenium/driver.rb:102:in `reset!'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara/session.rb:109:in `reset!'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara.rb:330:in `block in reset_sessions!'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara.rb:330:in `each'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara.rb:330:in `reset_sessions!'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/capybara-2.7.0/lib/capybara/rspec.rb:21:in `block (2 levels) in <top (required)>'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:364:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `each'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:607:in `block in run_example_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:606:in `each'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:606:in `run_example_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:477:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:485:in `run_after_example'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:251:in `block in run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:478:in `block in with_around_and_singleton_context_hooks'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:435:in `block in with_around_example_hooks'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:478:in `block in run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:320:in `call'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:320:in `call'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-rails-3.4.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:425:in `instance_exec'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:389:in `execute_with'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:320:in `call'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:320:in `call'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:478:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:435:in `with_around_example_hooks'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:478:in `with_around_and_singleton_context_hooks'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example.rb:233:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:581:in `block in run_examples'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:577:in `map'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:577:in `run_examples'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:543:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/bin/rspec:23:in `load'
          # /Users/gischer/SweetvineSystems/ilarp/vendor/bundle/ruby/2.1.0/bin/rspec:23:in `<top (required)>'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
          # /Users/gischer/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
          # /Users/gischer/.rbenv/versions/2.1.8/bin/bundle:23:in `load'
          # /Users/gischer/.rbenv/versions/2.1.8/bin/bundle:23:in `<main>'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 8.75 seconds (files took 2.35 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/test_spec.rb:5 # User Administration: Dumb Test

**Comment by lmtierney** [comment]
Your stacktrace shows you're using chromedriver `2.29`. You probably have multiple in your path. You need to find where `2.29` is and delete it.

`which chromedriver`

**Comment by gischer** [comment]
This observation has solved my problem, which was wrapped up with the chromedriver-helper gem.

Thanks so much!

**Comment by titusfortner** [comment]
@gischer the chromedriver-helper gem uses a shim to keep drivers up to date, if you are interested in that functionality, the `webdrivers` gem does the same thing without using shims.
