### ISSUE TITLE
selenium 3.7/3.8, same browser on different OS, platform not recognized

### ISSUE THREAD

**Issue by rgoerner** [SeleniumHQ/selenium#5200]
I have one hub which some nodes are connecting to.
For example, a windows-host with chrome and Appium (Android Device, with chrome)
configs are below.

If I send a request, using chrome OR remote webdriver, and I set platform to "windows," Windows" or "WIN10", all the browsertests are executed on the windows-node *AND* the android - node, which is wrong.

I use cucumber and serenity, and run the test like this:

/opt/apache/maven/current/bin/mvn integration-test -Dwebdriver.remote.url=http://172.31.40.121:4444/wd/hub -Dwebdriver.driver="chrome" -Dmaven.test.failure.ignore=true -Dcontext="chrome" -Dplatform="WIN10"

Anyway, chrome should *only* start on Windows, but command is spread to Windows *and* Android.

Any ideas? I think, this is a bug, because platform is not recognized well.

Best,
Ronny

start cmd.exe /k "cd c:\selenium && java -Dwebdriver.gecko.driver="C:\selenium\geckodriver.exe" -Dwebdriver.chrome.driver="C:\selenium\chromedriver.exe" -Dwebdriver.ie.driver="C:\selenium\IEDriverServer.exe" -Dwebdriver.edge.driver="C:\selenium\MicrosoftWebDriver.exe" -jar c:\selenium\selenium-server-standalone-3.8.1.jar -role webdriver -maxSession 25 -hub http://172.31.40.121:4444/grid/register -port 5566 -browser "browserName=firefox, maxInstances=10, Platform=WINDOWS, seleniumProtocol=WebDriver" -browser "browserName=chrome, maxInstances=10, seleniumProtocol=WebDriver, Platform=Windows" -browser "browserName=internet explorer,maxInstances=1" -browser "browserName=MicrosoftEdge,maxInstances=1""

and for appium:
call cmd.exe /k "cd c:\selenium && c:\users\testing\AppData\Roaming\npm\appium --nodeconfig=c:\users\testing\Desktop\appium.json"

where the appium.json looks like:

{
  "capabilities":
      [
        {
          "browserName": "chrome",
          "maxInstances": 1,
          "platform":"Android",
		  "deviceName":"192.168.243.101:5555",
		  "platformName":"Android"
        }
      ],
  "configuration":
  {
    "id": "Genymotion: Samsung Galaxy S7 Android 7.1.0 SDK 25",
    "cleanUpCycle":2000,
    "timeout":300,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url":"http://127.0.0.1:4723/wd/hub",
    "host": "172.31.40.121",
    "port": 4723,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "172.31.40.121"
  }
}

**Comment by kool79** [comment]
It seems you have issue with passing system properties from maven process to serenity process or applying  properties for remoteWebDriver.

> /opt/apache/maven/current/bin/mvn integration-test -Dwebdriver.remote.url=http://172.31.40.121:4444/wd/hub -Dwebdriver.driver="chrome" -Dmaven.test.failure.ignore=true -Dcontext="chrome" -Dplatform="WIN10"

Can you show how you pass those properties from maven   to serenity (should be in pom-file in `<systemPropertyVariables>` )? BTW for serenity standard property names for browser/platform are: `webdriver.remote.os` and `webdriver.remote.driver`. Do  you use custom WebDriver implementation? if yes, check what capabilities are really passed to RemoteWebDriver

**Comment by diemol** [comment]
Closing as we never got more information from the OP.
