### ISSUE TITLE
can not wait element write by  driver.manage().timeouts().implicitlyWait(i, TimeUnit.SECONDS);

### ISSUE THREAD

**Issue by Oly-Don** [SeleniumHQ/selenium#5201]
## Meta -
OS:  
win10
Selenium Version:  
3.5.1
Browser:  firefox

Browser Version:  
firefox ZH-cn 55.0
JAVA Code 👍 
<  driver.manage().timeouts().implicitlyWait(30 , TimeUnit.SECONDS);>
## Expected Behavior -
auto keep looking element to present between 30 second  

## Actual Behavior -
run fail inmediately when run scripit to find a  loading element without wait in 30 secnd.

## Steps to reproduce -

My code:

  FirefoxOptions options = new FirefoxOptions();
 ProfilesIni allProfiles = new ProfilesIni();
        FirefoxProfile profile = allProfiles.getProfile("default");
                options.setProfile(profile );
  driver = new FirefoxDriver(options);
 driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);//this seems no work at all,when could not find element,driver have fail immediately 

30 TimeUnit.SECONDS  change to 3000 TimeUnit.SECONDS,
this problem is OK.   confuse by this !

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
