### ISSUE TITLE
Is it possible to ByPass IE-Protected mode setting from selenium??

### ISSUE THREAD

**Issue by TARIFABBAS** [SeleniumHQ/selenium#5202]
My IT has disabled protected mode setting for "Local Intranet and Trusted Sites" I am getting below error 

_Exception in thread "main" org.openqa.selenium.NoSuchSessionException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 65 milliseconds_

When I am using the capability **"capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);**" getting this error :: capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);

Can anyone help me in this out as it has become a blocker for me?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
