### ISSUE TITLE
chrome was closed unexpectedly

### ISSUE THREAD

**Issue by Amber2008** [SeleniumHQ/selenium#5207]
## Meta -
OS:  
Windows 7 Professional

Selenium Version:  
3.5.3

Browser:  
chrome V62
chromedriver v2.33

## Expected Behavior -
chrome will not closed unexpectedly

## Actual Behavior -
chrome will be closed unexpectedly after running many cases.

Could you give me some clause to investigate, I can't find any error why the chrome was closed unexpectedly.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
