### ISSUE TITLE
Copying file from Linux to NAS Share with Java (Apache FileUtils FileCopy)

### ISSUE THREAD

**Issue by gnanasekar6914** [SeleniumHQ/selenium#5208]
One of the developers here has written some Java code which uses the Apache FileUtils FileCopy command to copy a csv from a host server (linux) to a file share ([EMC](https://mindmajix.com/emc-san-storage-training) NAS).

The share's setup such that 'Everyone' has 'Full Control' (i.e. to ensure there are no permissions issues - we'll later restrict permissions once things are proven to work).

The code runs under TomCat/Apache.

It works copying the file from one directory on the host server to another; just not when attempting to copy to the remote share (no errors appear to be thrown / nothing happens - the code just continues as if the copy had worked, but nothing shows up in the destination). The same issue occurs when attempting to write a new file to the share.

http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FileUtils.html

Has anyone seen this behaviour before / any ideas what may cause it? 

Thanks in advance.
Gnanasekar

**Comment by cgoldberg** [comment]
perhaps file an issue with Apache Commons IO?... this is the tracker for Selenium issues.

**Comment by barancev** [comment]
Not related to Selenium
