### ISSUE TITLE
C# Action.MoveToElement(...) throws NullReferenceException

### ISSUE THREAD

**Issue by jakobstrauch** [SeleniumHQ/selenium#521]
Firefox 37, Chrome latest, latest NuGet package of Selenium (2.45.0)

For some elements i get an exception for Action.MoveToElement(...). Inspecting the IWebElement with the VS debugger reveals, that the element is found and also most of the properties are set - except these ones:

Coordinates 
LocationOnScreenOnceScrolledIntoView 

They cannot be read by the VS debugger , because their getters throw the NullReferenceException (this may be the root of evil for MoveToElement)

On another page, the method works liek a charm. What may be the problem here? 

Thanks and Regards,
Jakob

**Comment by lukeis** [comment]
please provide a stack trace and reproducible test script that shows the issue...

Otherwise questions like these are better suited for the [mailing list](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by barancev** [comment]
Closing the issue due to inactivity
