### ISSUE TITLE
Unable to trigger OnChange event in <select>dropdown using Selenium Webdriver for pega based application

### ISSUE THREAD

**Issue by rsbkumar** [SeleniumHQ/selenium#5210]
My application is built using Pega 7.1.8. I am facing issue in selecting value from one of the dropdown in popup(Modal window) using selenium WebDriver. I have 2 dropdowns in popup(Modal window). Based on selection of value in 1st dropdown  the value in 2nd dropdown gets populated. And based on value selected in 2nd dropdown some additional fields in the popup will be displayed. There is an OnChange event in HTML that exists for both the dropdown. I am able to select value in 1st dropdown but I am unable to select value from 2nd dropdown. I used Select option in selenium WebDriver to select value from 1st dropdown.  If I use the same code in 2nd dropdown I am getting Activity Status error from Pega. The value is getting selected in UI but getting error from Pega. 

When I discussed with developers they told that they have written some backend verification logic on selection of value in 2nd dropdown which works when OnChange event in dropdown is triggered. Automation code is unable to trigger OnChnage event in 2nd dropdown. I also tried with Click and select using Xpath, SendKeys, Tab, JavaScript but nothing is solving the issue.

I am using Selenium Ver 3.4 and ChromeDriver Version 2.33 and IE Driver version 3.4 and ChromeBrowser Version -60 and IE Browser version – 11. The issue exists only in browsers opened using automation. Attached is the detailed problem statement document.

Below is the HTML of 2 dropdowns.

1st dropdown:

<select class="cc_standard" data-ctl="[&quot;Dropdown&quot;]" id="Category" name="$PSelectActivity$pCategory" validationtype="required" data-change="[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;SelectActivites&quot;, &quot;&quot;, &quot;&amp;=&quot;, &quot;&quot;, &quot;ResetActivityValues,&quot;,&quot;:event&quot;,&quot;&quot;,&quot;SelectActivity&quot;]]]" style="width:48%"><option value="" title="Select">Select</option><option value="DMS">DMS</option><option value="File Transfer">File Transfer</option><option value="Miscellaneous">Miscellaneous</option><option value="SMS">SMS</option></select>

2nd dropdown:

<select class="cc_standard" data-ctl="[&quot;Dropdown&quot;]" disabled="" id="EformType" name="$PSelectActivity$pEformType" validationtype="" data-change="[[&quot;refresh&quot;, [&quot;otherSection&quot;,&quot;SelectActivites&quot;, &quot;DetermineExceptionProcess&quot;, &quot;&amp;FreezDate=&amp;DiffDays=&amp;MaxIndex=&amp;CurrentDate=&quot;, &quot;&quot;, &quot;SetActivityData,&quot;,&quot;:event&quot;,&quot;&quot;,&quot;SelectActivity&quot;]]]" style="width:48%"><option value="" title="Select">Select</option></select>
[Pega_Selenium_dropdown.docx](https://github.com/SeleniumHQ/selenium/files/1551453/Pega_Selenium_dropdown.docx)

**Comment by cgoldberg** [comment]
please don't post examples in MS Word format... use plain txt or image attachments so it is accessible to all.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by rsbkumar** [comment]
Hi  it's not a question. It's a problem. Iam unable to select value from
dropdowns built using Pega tool. Selenium web driver is unable to trigger
on change event on selection of value in dropdown.

Requesting u to reopen the ticket. Let others who experience same problem
may contribute to this issue.

**Comment by barancev** [comment]
This is bug tracker, not support line. Selenium is supported by [community user group](https://groups.google.com/forum/#!forum/selenium-users). Send your question to the group and there is a chance someone helps you diagnose or resolve the issue.

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. We can't debug screenshots, we need an executable scenario.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
