### ISSUE TITLE
Safari 11, Selenium Version 3.4.0, SelectByIndex not working 

### ISSUE THREAD

**Issue by lisaPthomas** [SeleniumHQ/selenium#5212]
## Meta -
OS:  
virtual machine (sauce using webdriverIO)
OS x 10.12
Selenium Version:  
3.4.0
Browser:  
Safari 11

Browser Version:  
11.0

## Expected Behavior -
```
OrderDetailsPage....

 arrivalWindow: {
    get: function() {
      return browser.element("select.js-preferred");
    }
  },
...
```
```
...
OrderDetailsPage.arrivalWindow.selectByIndex(1);
...
```

this is working correctly on Safari 10, using  Selenium version: 2.53.1
## Actual Behavior -
does not select the element by index, skips over this action.

## Steps to reproduce -
Try to use selectByIndex with selenium 3.4.0 version on Safari 11.

**Comment by barancev** [comment]
Please report this issue to webdriver.io project:
https://github.com/webdriverio/webdriverio/issues
