### ISSUE TITLE
Is there a HideCommandPromptWindow like method for Python like there's one for C#?

### ISSUE THREAD

**Issue by flawiddsouza** [SeleniumHQ/selenium#5214]
### Meta
OS:  Windows 10
Selenium Version:  3.8.0, Python
Browser:  Chrome
Browser Version:  63.0.3239.84 (64-bit)

### Expected Behavior
HideCommandPromptWindow like method for Python like there's one for C#

### Actual Behavior
Non-existent or undocumented

The chromedriver console pops up every time I initialize the driver with it. Is there any way to hide it?

**Comment by bjquinn** [comment]
+1, this would be very useful.  an example of an implementation of this can be found here:

https://github.com/masc-it/selenium/commit/05a5bb9e2dd603a0ee3ad05a94cc6063ff9c843b

**Comment by diemol** [comment]
Seems this will be fixed by #8647

**Comment by diemol** [comment]
The linked PR above was merged, and this will be part of the next Alpha release.
