### ISSUE TITLE
32 bit Windows IE driver is blocked by McAfee

### ISSUE THREAD

**Issue by allaco** [SeleniumHQ/selenium#5215]
## Meta -
OS:  Windows 10

Selenium Version:  3.8.1

Browser:  Internet Explorer

Browser Version:  

## Expected Behavior -
IEDriverServer_Win32_3.8.0.zip should not be detected as malware.
 
## Actual Behavior -
It is not possible to download the IEDriverServer_Win32_3.8.0.zip as it is blocked by McAfee in our corp network.
Virus analysis can be seen on this page:
https://www.virustotal.com/en/file/17d0d4095c6fdfd8b8699eefb8fadd7fcfa322f789d9cba43aafc5e40c88789a/analysis/

Compare to 64bit version (which is not being blocked):
https://www.virustotal.com/en/file/d1e633dece685e506d06159bd70850711d38fd47c74b1db241b9020db796b92f/analysis/

## Steps to reproduce -

- Try to download driver for 32 bit Windows IE from http://www.seleniumhq.org/download/ while having McAfee Web Gateway enabled
OR
- Verify the file on https://www.virustotal.com

**Comment by noahlocke** [comment]
We're also seeing the same issue. 

https://www.virustotal.com/#/file/17d0d4095c6fdfd8b8699eefb8fadd7fcfa322f789d9cba43aafc5e40c88789a/detection

**Comment by bobotzzz** [comment]
Please uninstall mcafee and use a serious AV ! See if it still reproduces afterwards

**Comment by noahlocke** [comment]
@bobotzzz what are you talking about? Did you even read the issue? Did you look at the Virus Total report? Please research before commenting, as your comment is entirely unhelpful.

**Comment by cgoldberg** [comment]
It gets flagged because it contains a portable executable named "IEDriverServer.exe"?

This isn't a Selenium issue, but rather an issue with your AV software or its configuration.  If you can't fix or disable your AV, you will have to find an alternate way to get the driver on to the machine (i.e. sneakernet, compile it yourself, etc)

**Comment by allaco** [comment]
@bobotzzz It is impossible to disable the AV Web Gateway as it is enforced by the corporate network rules.

@cgoldberg Thank you for your comment. Indeed looks like it was a McAffee issue. After their signatures were updated on the Virus Total, the zip file is not being detected as malware anymore. I was also able to download it successfully from seleniumhq.

Thanks! 
Closing this.
