### ISSUE TITLE
Error forwarding the new session java.util.zip.ZipException selenium standalone server 3.8.1

### ISSUE THREAD

**Issue by jburns24** [SeleniumHQ/selenium#5217]
## Meta -
Bindings: .Net C#
OS:   Windows Server 2008 R2

Selenium Version:  
Selenium.Webdriver 3.8.0
Selenium.Support 3.8.0
selenium standalone server 3.8.1
geckodriver 19.0.1

Browser:  Firefox 57.0.2

## Expected Behavior - 
Firefox profile is sent to test node and loaded 
## Actual Behavior - When remote webdriver is trying to initialize exception is thrown 
Exception: `		Message	"Error forwarding the new session java.util.zip.ZipException: invalid stored block lengths\nBuild info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'\nSystem info: host: 'CHI-SGNODE1', ip: '10.0.2.15', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'\nDriver info: driver.version: unknown"	string
`

## Steps to reproduce -
```
FirefoxOptions ffoptions = new FirefoxOptions();
var relativePath = "../../../ffProfiles/6pwsso99.QAprofile";
ffoptions.BrowserExecutableLocation = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
var fullPath = Path.GetFullPath(Path.Combine(TestSuiteEnvironment.AssemblyDirectory, relativePath));
FirefoxProfile ffProfile = new FirefoxProfile(fullPath);
ffoptions.Profile = ffProfile;
Driver = new RemoteWebDriver(new Uri("http://localhost:4446/wd/hub/"), ffoptions.ToCapabilities(), TimeSpan.FromMinutes(2));
```
Exception is thrown when new RemoteWebDriver is called. If I comment out the line that sets the profile this does not throw an exception. This was working running standalone server 3.7.1 with selenium.webdriver 3.7.0 

I also tested with firefox 56.0.2 (before Firefox quantum) and this was still an issue. I also downgraded the version of the standalone server on the node (but not the hub) and was getting the same exception with "version:3.8.1" which leads me to believe this exception originates from the hub side.

**Comment by diemol** [comment]
Is this issue still valid with the most recent version of the components and using Grid 4 (alpha)?

**Comment by diemol** [comment]
I'll close this since the issue went stale and no more comments from the community were received.
