### ISSUE TITLE
Units for 'timeout' and 'browserTimeout' parameters in json config are changed since v3.x from ms to sec

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/selenium#5218]
In grid v2.x all timeouts in json configuration files were in ms. But during migration to grid v3.8 I found that `timeout` and `browserTimeout` now must be defined in seconds (in json). Below is table with time units used for timeouts when defined from command-line interface (CLI) and in json for v2.x and for v3.x

parameter | v2.x, CLI | v3.x, CLI | | v2.x, json | v3.x, json
------------ | -------- | ----------|-|----------|--------------
timeout      |  sec       |  sec        | | **ms**        | **sec**  :warning: 
browserTimeout |sec | sec        | | **ms**        | **sec** :warning: 
all others         |   ms      | ms          | |ms          | ms

The units used among properties in json for v3.x are not consistent and very confusing: some timeouts in ms (nodeStatusCheckTimeout, unregisterIfStillDownAfter, newSessionWaitTimeout etc) while others (timeout, browserTimeout) use seconds.
During migration I don't expect those changes because **all parameter's names remain the same while units changed**. Also there are no any notes about this in [wiki](https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json)
   Sure, there is command-line help where we can read about time units.  But there are many configurations, guides etc which use the 'old' units:
 *  [official appium documentation](http://appium.io/slate/en/master/?ruby#selenium-grid) (at moment) 
 * #2973
 * #3371

Againg, most of users are not aware about those changes and continue to use old ones after migration to v3.x.
This should be either documented or fixed.  I propose to introduce new parameter names and raise exception if someone continue to use old ones. For consistency all params (json, cli) should be defined in ms.

**Comment by diemol** [comment]
@kool79 yes, we are aware of this discrepancy but Grid 3.x is not under development anymore, and we are also aware of this for the undergoing development of Grid 4.
Since we won't make any changes to the code of Grid 3.x, I'll close this issue.
