### ISSUE TITLE
getWindowHandles() should return a list of windows ordered by window age

### ISSUE THREAD

**Issue by thephilwells** [SeleniumHQ/selenium#522]
Using the Java API, one should be able to do this

```
List<String> handles = driver.getWindowHandles();
driver.switchTo().window(handles[1]);
```

..and able to reliably expect that they are viewing the second-oldest open window.  This matters most when more than two windows are open, as when one needs to open more than one new window from the original window.

**Comment by lukeis** [comment]
This is in contradiction with the [WebDriver w3c spec](https://github.com/w3c/webdriver) for [getWindowHandles](https://w3c.github.io/webdriver/webdriver-spec.html#getwindowhandles).

If you would like to attempt to see this changed, please log either log a bug on the spec repo or send an email to the mailing list shown in that repo's readme.
