### ISSUE TITLE
useful for many people: in nodejs, chrome actions do not work in 3.8 and HEAD. Before they do, we need doc saying 3.6 must be used for chrome

### ISSUE THREAD

**Issue by MagicPoulp** [SeleniumHQ/selenium#5222]
## Meta -

I think this is an important issue for many people. And it can be solved quickly by adding the doc I suggest below. When trying to support both firefox and chrome, different package versions must be used. And it takes time to understand.

As I show in the example code, chrome actions stopped working on HEAD and 3.8 of SeleniumHQ/selenium, for Javascript.

In your repository
b588bf5 added firefox support for w3c actions and dropped support for legacy. Firefox or its driver needs the new API. And chrome and its driver currently works only with the legacy API.

--> Request please:

It would be nice and helpful for many people to document the following:
"
Concerning the support for actions in firefox and chrome:
-- firefox:
firefox and its geckodriver recently started to require to use W3C compliant actions, using a new API.
Support for the latest firefox actions is not present in selenium 3.6. It is available directly when building manually the repository SeleniumHQ/selenium (./go node:atoms)
-- chrome:
Support for actions in chrome is supported in 3.6 using the legacy API.
The use of actions in chrome is not ready yet on the HEAD.

OS:  
Debian 9
Selenium Version:  
3.8 (not npm package)
Browser:  
Chrome and Firefox

Browser Version:  
Firefox 57
chromium 62

## Expected Behavior -
The example code below with a simple action should not show an error on chrome.
In firefox, it works fine.

## Actual Behavior -
" UnknownCommandError: Unrecognized command: actions"

## Steps to reproduce -
import { Builder, By, logging, until } from 'selenium-webdriver';

```javascript

import { Builder, By, logging, until } from 'selenium-webdriver';

describe("example_actions_not_working_on_chrome", function() {
    it("try", function() {
        let driver = new Builder()
        .forBrowser('chrome') // with chrome, error
        // .forBrowser('firefox') // with firefox, there are no error
            .build();
        driver.get('http://www.google.com/');
        const actions = driver.actions();
        actions.keyboard().sendKeys('p');
        actions.perform()
    })
})
```

**Comment by jleyba** [comment]
Thanks for the feedback. Instead of recommending a version split, I'm going to try adding a translation layer to the new API.

I'm tracking feedback on the new Actions API in #4564, so I'm going to close this in favor of having a single bug.
