### ISSUE TITLE
Not able to click elements which are present down [bottom] the page and not visible until i scroll down.

### ISSUE THREAD

**Issue by bhaveshsharma** [SeleniumHQ/selenium#5225]
Setup : 
selenium = 3.4.0  (pip installer)
gecko driver = 0.19
chrome driver = 2.33
Firefox browser = 57.0
chrome  browser = 63

Issue :  

I have a page, and there is a button on this page.
when this button is clicked, it opens a window/dialog, which have couple of other elements like text fields, radio box, select box etc.
Problem is, im not able to click elements which are not visible right now.  I mean these elements are present in that window but i can see them only when i scroll down.

I have simple code which click this : 

        form2.pol_sched_combobox.click()
        form2.pol_sched_combobox.select('Weekly')

This happens only for Firefox browser. This works fine for Chrome.

Error it displays is : 

StaleElementReferenceException: Message: The element reference of <input id="ext-gen1275" class="x-form-field x-form-text x-form-empty-field x-trigger-noedit"> stale: either the element is no longer attached to the DOM or the page has been refreshed

Although page is not refreshed. i can see element is present if i scroll down.

Note : If i manually scroll down before script reaches these elements, then script is able to identify and click elements.  so im very clear that issue is elements are not visible to script because they are present at lower botton of the page.

This is the issue im getting after i did the upgrade to latest driver and selenium.
This used to work fine when i have selenium 2.53.1 and firefox 46.

what is the solution for this?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by bhaveshsharma** [comment]
I felt this is issue with latest selenium or gecko drivers.
if something is working with previous versions and not working with new versions then something needs to be looked into new files.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bhaveshsharma** [comment]
As i mentioned previously, i have a TC which does like this : 
1. Login to UI.
2. Access some page.
3. In this page, we have some button, when clicked open up a new window.   
4. This window have elements.  some elements are visible in the window, and some elements are visible when we scroll down.
5. Now elements which are visible when we scroll down are the ones which are failing at click now.
6. So earlier [when i have 2.53.1] this all works fine, when i start script, it automtically clicks the elements that are at the botton of the window, i dont have to scroll or make these elements visible.
7. But now, it does not work.

Code i have is : 

`        # Logon to application
        login_page = Login_Page(self.driver, spath=self.screenpath)
        status = login_page.login(self.base_url, self.username, self.password)
        self.assertTrue(status)

        # Navigate to Access Management page
        nav = MainNavigationTabs(self.driver, spath=self.screenpath)

        # Select Data protection and click antivirus
        nav.hover_on_Data_Protection()
        nav.dp_links.click_antivirus()
        time.sleep(3)

        tab = Antivirus_Tabs_Page(self.driver, spath=self.screenpath)

        # click av servers tab and verify it's selected
        tab.click_av_policies()
        tab.is_av_policies_selected()

        page = Antivirus_Policies_Page(self.driver, spath=self.screenpath)

        # Verify login name in Page header
        login_name = page.header.get_login_name()
        self.assertEqual(self.username, login_name)

        # click view/edit button
        page.av_view_edit_button.click()

        form1 = Antivirus_Policies_Details_Form(self.driver, spath=self.screenpath)

        form1.is_details_form_found()
        form1.is_edit_button_found()
        form1.is_close_button_found()

        form1.pol_edit_button.click()

        form2 = Antivirus_Policies_Edit_Form(self.driver, spath=self.screenpath)

        form2.wait_for_page_load()

        form2.enable_pol_checkbox.click()
        form2.enable_force_checkbox.click()

        form2.pol_name_textbox.clear()
        form2.pol_name_textbox.write('edit_name')

        form2.pol_descr_textbox.clear()
        form2.pol_descr_textbox.write('edit_description')

        form2.pol_path_textbox.clear()
        form2.pol_path_textbox.write('/ifs/home')

        form2.limit_depth.click()
        form2.limit_depth.click()
        form2.pol_depth_textbox.write

        form2.impact_pol_combobox.click()
        form2.impact_pol_combobox.select('MEDIUM')
        time.sleep(5)
        
        page = Antivirus_Policies_Page(self.driver, spath=self.screenpath)
        form2 = Antivirus_Policies_Edit_Form(self.driver, spath=self.screenpath)
        
        form2.scheduled.click()
        form2.pol_sched_combobox.click()
        form2.pol_sched_combobox.select('Weekly')

        form2.pol_edit_save_button.click()
`
It fails at line form2.pol_sched_combobox.click()

Error i get is  : 

Traceback (most recent call last):
  File "antivirus_readwrite_policies_edit.py", line 89, in test_xxxxx_antivirus_readwrite_policies_edit
    form2.pol_sched_combobox.click()
  File "C:\gitcode\onefs-master\isilon\test-qa\tests\webui\framework\common\BaseControl.py", line 55, in click
    self._element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
StaleElementReferenceException: Message: The element reference of <input id="ext-gen1275" class="x-form-field x-form-text x-form-empty-field x-trigger-noedit"> stale: either the element is no longer attached to the DOM or the page has been refreshed

Please let me know if some thing else needs to be provided.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by bhaveshsharma** [comment]
So i have drill down more in this issue. Root caused the problem
So with latest gecko driver 0.19 and firefox version 57, this issue is consistently reproducible.

There are 2 issues :   
First Issue : 

So if i have a page, and if i click some button which opens up a sub window or say a modal dialog, then you  can click only on object that are visible in that window.  
elements which are present in that window but not visible  ( i mean can be visible only when you scroll this sub window or modal dialog)  are not clickable.
You have to scroll down to have those elements visible  and then only click() works.

Second Issue:
In any sub window or modal dialog, if by clicking some elements displays more element inside(  i mean i click some checkbox and after that couple of more elements are displayed like textfields, radio butons etc), these elements are also clickable.
So if i have identifiers created using xapth for these type of elements, they will not work, until i scroll down to that checkbox, have that in focus and then click it. wait till all sub elements are displayed and then try to click it.


Both these issues worked fine when i have selenium 2.53.1 with firefox 46.
But these are not working when i have selenium 3.4.0 with gecko driver 0.19 and firefox 57.0

For now as an workaround, im using following to scroll down so that element comes into focus and then im able to click the elements : 
        element = self.driver.find_element_by_xpath("//label[text()='Scheduled']")
        self.driver.execute_script("return arguments[0].scrollIntoView();", element)

So question is - something (my scripts) which are working fine previously are not working fine after upgrade.   what changed in behaviour im not sure, but this is basic stuff and should work.

Note : With chrome i see everything working before or after upgrade. So issue is only with firefox.

Let me know if something else needs to be provided.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by sveinn** [comment]
I have the same issue with Firefox 57. However it appears to be resolved in Firefox 58 beta (Firefox 58 not released at the time of writing this).

**Comment by bhaveshsharma** [comment]
Yes this issue is fixed in Firefox 58 beta.

I verified the same.

We can close this issue.

**Comment by askgarg** [comment]
I am facing this issue with Selenium and Chrome.

**Comment by dilip16j** [comment]
@askgarg - I'm facing a similar issue with chrome 69, how were you able to resolve this?

**Comment by GirishGanapathi** [comment]
Same finding this issue in chrome 70 !
