### ISSUE TITLE
Selenium+chromedriver+google-chrome “--host-rules” option doesn't work?

### ISSUE THREAD

**Issue by asegrenev** [SeleniumHQ/selenium#5226]
## Meta -
OS:  Linux Ubuntu
Selenium Version:  3.8.1
Browser:  ChromeDriver(2.34.522913)+Chrome(63.0.3239.84 64-bit) (also tried with Chromium(63.0.3239.84) )
Python 3.5.2

## Expected Behavior -

`--host-rules "MAP * localhost"`  maps all hosts to localhost. And no page is loaded.

## Actual Behavior -

Nothing happens - all hosts resolved as usual without mapping. In log file all seems to be allright - no errors or something...
> [1,018][INFO]: Launching chrome: /opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control **--host-rules="MAP * localhost"** --ignore-certificate-errors --load-extension=/tmp/.org.chromium.Chromium.dgOMsm/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12406 --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.ZOu1OP data:,

## Steps to reproduce -
```python
from pyvirtualdisplay import Display
display = Display(visible=0, size=(800, 600))
display.start()

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument('--host-rules "MAP * localhost"')
service_log_path = 'chromedriver.log'
service_args = ['--verbose']
driver = webdriver.Chrome('/usr/local/bin/chromedriver', chrome_options=chrome_options, service_args=service_args, service_log_path=service_log_path)
driver.get('http://google.com')
print(driver.page_source)
driver.close()
driver.quit()
display.stop()
```

This code prints loaded html. But if `--host-rules "MAP * localhost"` worked as expected - there must be a connection error. (There's no proxy on localhost)

When I've tried to write `chrome_options.add_argument('--host-rules="MAP * localhost"')` (added '=' sign) - there was an error in log:
> v14830:14885:1215/122036.230588:ERROR:host_mapping_rules.cc(107)] Failed parsing rule: "MAP * localhost"

And no mapping of course...

**Comment by barancev** [comment]
Please report this issue to chromedriver project: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by ravirk91** [comment]
Hi,
We are also facing "Failed parsing rule" issue when trying to pass "--host-rules" argument  in selenium chrome driver. Could you please let me know whether this issue is resolved or not .

**Comment by cgoldberg** [comment]
Please report this issue to chromedriver project: https://sites.google.com/a/chromium.org/chromedriver/help
