### ISSUE TITLE
unable to connect to chromedriver - incompatibilty with the gem 'extlib' 

### ISSUE THREAD

**Issue by Sunia** [SeleniumHQ/selenium#523]
I have integrated latest version of selenium-webdriver with capybara and cucumber. But getting this error.

**Comment by Sunia** [comment]
If I try to run rake tasks with firefox, then getting the error of 'Childprocess:LaunchError' and if set chromedriver as default then it throws an error of 'unable to connect to chromedriver '.

As suggested, I have set all the chromedriver path. Also used gem "chromedriver-helper". But none works.

Then we processed all the gems to check the incompatibilty with some gem. 
and found the solution.

gem "extlib" created the issue. On uninstalling this gem, everything works fine. As this app was first made in rails 2 so this gem was used at sometime.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
