### ISSUE TITLE
Error on Actions.MoveToElement() - Target element cannot be converted to IWebElementReference

### ISSUE THREAD

**Issue by hprutsman** [SeleniumHQ/selenium#5231]
## Meta -
OS:  Windows 10
Selenium Version:  Selenium.WebDriver 3.8.0, net45
Browser:  Internet Explorer
Browser Version:  
11.64.16299.0 (64-bit)

## Expected Behavior
MoveToElement Action Should move the pointer to the element. 

## Actual Behavior 
When wrapping an IWebElement in a class that implements IWebElement and ILocatable and then attempting an Action like MoveToElement, an error is received that the target element cannot be converted to IWebElementReference.  I am unable to implement IWebElementReference though because it is an internal class.  This looks to be the same as Issue#4577 that was closed due to no reproducible test case.

#### StackTrace:
Result StackTrace:	
at OpenQA.Selenium.Interactions.PointerInputDevice.PointerMoveInteraction.ConvertElement()
   at OpenQA.Selenium.Interactions.PointerInputDevice.PointerMoveInteraction.ToDictionary()
   at OpenQA.Selenium.Interactions.ActionSequence.ToDictionary()
   at OpenQA.Selenium.Remote.RemoteWebDriver.PerformActions(IList`1 actionSequenceList)
   at OpenQA.Selenium.Interactions.Actions.Perform()
   at TestWebReference() line 344
Result Message:	System.ArgumentException : Target element cannot be converted to IWebElementReference

## Steps to reproduce

        public void TestWebReference()
        {
            var driver = new InternetExplorerDriver();
            driver.Url = "https://www.google.com";
            IWebElement element = driver.FindElementById("lst-ib");
            WebElementWrapper wrapper = new WebElementWrapper(element);
            Actions act = new Actions(driver);
            act.MoveToElement(wrapper).Perform();
        }

        public class WebElementWrapper : IWebElement, ILocatable
        {
            private IWebElement _element;
            private ILocatable _locatable;

            public WebElementWrapper(IWebElement element)
            {
                _element = element;
                _locatable = element as ILocatable;
            }

            public string TagName => _element.TagName;

            public string Text => _element.Text;

            public bool Enabled => _element.Enabled;

            public bool Selected => _element.Selected;

            public Point Location => _element.Location;

            public Size Size => _element.Size;

            public bool Displayed => _element.Displayed;

            public Point LocationOnScreenOnceScrolledIntoView => _locatable.LocationOnScreenOnceScrolledIntoView;

            public ICoordinates Coordinates => _locatable.Coordinates;

            public void Clear()
            {
                _element.Clear();
            }

            public void Click()
            {
                _element.Click();
            }

            public IWebElement FindElement(By by)
            {
                return _element.FindElement(by);
            }

            public ReadOnlyCollection<IWebElement> FindElements(By by)
            {
                return _element.FindElements(by);
            }

            public string GetAttribute(string attributeName)
            {
                return _element.GetAttribute(attributeName);
            }

            public string GetCssValue(string propertyName)
            {
                return _element.GetCssValue(propertyName);
            }

            public string GetProperty(string propertyName)
            {
                return _element.GetProperty(propertyName);
            }

            public void SendKeys(string text)
            {
                _element.SendKeys(text);
            }

            public void Submit()
            {
                _element.Submit();
            }
        }

**Comment by jimevans** [comment]
You should also implement `IWrapsElement`, which returns the internal `IWebElement` value.

**Comment by hprutsman** [comment]
Thanks @jimevans, implementing IWrapsElement fixed it.
