### ISSUE TITLE
Should method .quit kill the Safari process or just close all the safari window?

### ISSUE THREAD

**Issue by JoannaCode** [SeleniumHQ/selenium#5232]
## Meta -
OS:  MACOS 10.12.6

Selenium Version:  3+

Browser:  Safari10

Browser Version:  

## Expected Behavior -
Not a bugs, just want to ask.

**Comment by lmtierney** [comment]
Please do not use Github issues as a place for questions. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
