### ISSUE TITLE
Python --Trigger search results twice, ChromeDriver with User Agent

### ISSUE THREAD

**Issue by marslan390** [SeleniumHQ/selenium#5234]
OS:
macOS
Selenium Version:
3.8.0
Browser:
Chrome

I am facing an issue while using ChromeDriver with user agent, it triggered the serach result twice, 1 search result with provieded cookie and then it automatically refresh the results with my current location, code snippet is:

options = Options()
options.add_argument("--user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1")
driver = webdriver.WebDriver(driver_path, options=options)
driver.get("http://www.google.com")
driver.add_cookie({
    'domain': '.google.com',  # note the dot at the beginning
    'name': 'UULE',
    'value': 'a+cm9sZToxCnByb2R1Y2VyOjEyCnByb3ZlbmFuY2U6Ngp0aW1lc3RhbXA6MTQ2OTA5Mzk0ODg4NDAwMApsYXRsbmd7CmxhdGl0dWRlX2U3OjQwNzU5Mzk0MQpsb25naXR1ZGVfZTc6LTczOTY5Nzc5NQp9CnJhZGl1czozNTM0MA==',
    'path': '/',
    'expires': time.time() + (60 * 60 * 24),
    'secure': True,
})
search = driver.find_element_by_name('q')
search.send_keys("Coffee")
search.send_keys(Keys.RETURN)

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
