### ISSUE TITLE
ExpectedConditions do assumptions based on StaleElementReferenceException 

### ISSUE THREAD

**Issue by karniemi** [SeleniumHQ/selenium#5235]
**Issue**
ExpectedConditions do assumptions based on StaleElementReferenceException 

**Example**
For example, ExpectedConditions.invisibilityOfElementLocated() evaluates to true on StaleElementReferenceException. In the DOM manipulating javascript-hell of recent ages, StaleElementReferenceException might mean that element is no more - but it might as well mean that the DOM got modified and the locator-identified element is still on the page with a different reference.  So StaleElementReferenceException only means that the reference from findElement() went stale - but one can/should not do any further implication from that. As far as I understand, Selenium should/could retry when StaleElementReferenceException is raised to be sure about the actual state of Locator-pointed element(s).

I tried to find out if this has been a discussed design choice at some point of selenium history. But could not find any records.

**Comment by barancev** [comment]
No, Selenium does not retry to find element after StaleElementReferenceException. It can be implemented as a wrapper if someone needs this feature.

For the issue please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by karniemi** [comment]
Sorru, but I can't see how this could implemented as a wrapper. Selenium "eats" the StaleElementException in this case -and instead returns an incorrectly assumed boolean value. There's no way any wrapper could find out from the boolean return value, whether it was due to the false assumption(from stale reference) or if the element was really not visible. 

The main question is about the logic: should selenium or any test software do any assumptions if a reference goes stale? I think no, because that assumption is/can be incorrect. One should either retry or throw the problem up - now selenium does not do either of them in the example case-but returns an assumption.

**Comment by barancev** [comment]
A wrapper can catch StaleElementReferenceException and retry element search. I mean a wrapper around driver not around expected condition.

StaleElementReferenceException means that the target element disappears. If an element disappears it's not visible anymore, and the condition resolves to true.

Yes, *another* element with the same locator can appear on the page in a second. But at the moment when Selenium evaluated the condition, the element found by the given locator just disappeared from the page. Selenium can't predict future, it can't know if some other element with the same localtor will appear soon. It just knows what's happening on the page at the moment.

The same is true for an element that does not disappear (no StaleElementReferenceException) but changes visibility only. It can go back to visible in a second or two, and Selenium can't predict this too.

**Comment by karniemi** [comment]
@barancev A bit late, but Thank You! Your thorough explanation makes perfect sense.
