### ISSUE TITLE
Upload file on Safari browser

### ISSUE THREAD

**Issue by rshravi** [SeleniumHQ/selenium#5236]
## Meta -
OS:  
MacOS 10.12
Selenium Version:  
2.47.1, IntelliJ
Browser:  
Safari 11.0

Hi Guys,

I am running automated script present in Git and running through Bamboo on Saucelabs.
The requirement is to upload the orders file to the cart page.
 ==>input name="myfile" type="file" class=""
I am trying to upload using below code

#######Code###########
String FullfileName = System.getProperty("user.dir") + fileName;
WebElement element = driver().findElement(By.name("myfile"));

LocalFileDetector detector = new LocalFileDetector();
            File localFile = detector.getLocalFile(FullfileName);
            if (uploadFileField instanceof RemoteWebElement) {
                ((RemoteWebElement) uploadFileField).setFileDetector(detector);
            }
element.sendKeys(localFile.getAbsolutePath());
#######Code###########
1.The above code working fine in Chrome. But its not working on safari browser.
2. The file path in bamboo is :/media/ephemeral0/build-dir/REG-IMBUCRC3-RRTF/src/Data/orders.csv]

I am not able to upload file using above code. Can anyone help me how to upload file in safari browser using sacelabs.

Thanks in advance

**Comment by barancev** [comment]
Please report this issue to Safari driver tracker: https://bugreport.apple.com/

**Comment by gvrrvenkat** [comment]
Hi 
Am also facing same issue in MAC OS, Safari. Could you please provide the solution to me.
Thanks in advance.

With Regards
Venkat

**Comment by gvrrvenkat** [comment]
Hi Ravi/Barancev

If you found the solution for this.please share it to me as am struck my work.

Thanks in advance.

With Regards
Venkat

**Comment by satvikgadam** [comment]
Hi

U can use apple script to perform file upload.
If u need any assistance pls let me know 

Thanks
Satvik gadam

**Comment by gvrrvenkat** [comment]
Hi Satvik

Thanks for your reply.
Can you please provide the apple script to perform file upload and also confirm is Apple script working in Sauce lab?

Thanks in advance.

With Regards
Venkat

**Comment by satvikgadam** [comment]
Hi Venkat,

I didn't test with Sauce lab. Please find the code as below.The resourceFolder is the path where the file which need to be uploaded.The path includes the file name.Let me know whether the below provided solution works for you.


public static void appleScript(String reourceFolder) {
		Runtime runtime = Runtime.getRuntime();
		String appleScriptCommand = "tell app \"System Events\"\n" + "keystroke  \"G\" using { command down, shift down }\n " +
		"delay 2\n" + "keystroke \"" + reourceFolder + "\"\n" + "delay 1\n" + "keystroke return\n" + "delay 1\n" +  "keystroke return\n" 
		+ "delay 1\n" + "end tell";
		System.out.println(appleScriptCommand);
		String []args = { "osascript", "-e" ,appleScriptCommand};
		try {
			Process process = runtime.exec(args);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

Thanks,
Satvik Gadam

**Comment by cgoldberg** [comment]
https://github.com/SeleniumHQ/selenium/issues/5236#issuecomment-353627105
