### ISSUE TITLE
Double Click with IEDriver 3.8.0

### ISSUE THREAD

**Issue by TPDias** [SeleniumHQ/selenium#5237]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.5.3
Browser:  
Internet Explorer - IEDriver 3.8.0

Hi,
I'm running an automated script and I want to perform a doubleClick with selenium but with the new driver the action is not possible. It works with IEDriver 3.3.0.
Can anyone help?

Browser Version:  
11.125

## Actual Behavior -

org.openqa.selenium.UnsupportedCommandException: mouseMoveTo
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'NELT753', ip: '10.155.129.53', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_141'
Driver info: driver.version: unknown
Command duration or timeout: 162 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'xxxx', ip: 'xxxx', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Session ID: da5a82f4-b18f-49d9-b3ae-f20d2d46a5d6
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{timeouts={pageLoad=300000, implicit=0, script=30000}, platform=ANY, browserVersion=11, platformName=windows, browserName=internet explorer, proxy={}, se:ieOptions={ignoreProtectedModeSettings=true, elementScrollBehavior=0, ignoreZoomSetting=true, enablePersistentHover=false, requireWindowFocus=false, ie.ensureCleanSession=false, initialBrowserUrl=http://localhost:33165/, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.fileUploadDialogTimeout=3000, ie.browserCommandLineSwitches=}, setWindowRect=true, unhandledPromptBehavior=dismiss, pageLoadStrategy=normal, acceptInsecureCerts=false}]

## Steps to reproduce -

try{
     WebElement element = driver.findElement(By.xpath("xapth"));
     Actions action = new Actions(driver);
     action.doubleClick(element).perform();
}catch(Exception e) {
     LOGGER.error(e.getMessage(), e);
}

**Comment by barancev** [comment]
Please upgrade client library to 3.8 to match IEDriverServer version.
