### ISSUE TITLE
WebDriverException: Message: {"errorMessage":"undefined is not an object (evaluating '(C(a)?xb(C(a)):window) ...

### ISSUE THREAD

**Issue by iarp** [SeleniumHQ/selenium#5238]
OS:  Windows Server 2008 R2, Windows 7, Windows 10
Selenium Version:  3.8.0
Browser:  Chrome 63.0.3239.108, chromedriver.exe 2.34, phantomjs.exe 2.1.1

I have a script I run every 15 minutes Monday to Friday 8am to 6pm. For the most part it runs fine, except without fail every Monday I get the following as error messages until I login to the machine and restart the script.

There are no chromedriver or phantomjs running in the background when this happens. I always browser.quit() at the end of the scripts execution. I have hundreds of these error messages logged and the one commonality between them all is its always the first interaction with the browser thats failing (aside from loading the page).

The following code uses chromedriver:

> elem = browser.find_element_by_id('username')
> elem.send_keys('')

Results in:

> WebDriverException: Message: {"errorMessage":"undefined is not an object (evaluating '(C(a)?xb(C(a)):window).getComputedStyle(a,null).MozTransform.match')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"164","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:64021","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"value\": [\"\"], \"sessionId\": \"f922dc20-d3a7-11e7-9d9d-c7b35afd707f\", \"text\": \"\", \"id\": \":wdc:1511810417933\"}","url":"/value","urlParsed":{"anchor":"","query":"","file":"value","directory":"/","path":"/value","relative":"/value","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/value","queryKey":{},"chunks":["value"]},"urlOriginal":"/session/f922dc20-d3a7-11e7-9d9d-c7b35afd707f/element/:wdc:1511810417933/value"}}
Screenshot: available via screen

The following code uses phantomjs:

> WebDriverWait(browser, 30).until(expected_conditions.visibility_of_element_located((By.ID, 'username')))

Results in:

> Message: {"errorMessage":"undefined is not an object (evaluating '(y(a)?y(a).parentWindow||y(a).defaultView:window).getComputedStyle(a,null).MozTransform.match')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:56004","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"GET","url":"/displayed","urlParsed":{"anchor":"","query":"","file":"displayed","directory":"/","path":"/displayed","relative":"/displayed","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/displayed","queryKey":{},"chunks":["displayed"]},"urlOriginal":"/session/b350f3a0-d8fa-11e7-a47f-2fc5f228f53f/element/:wdc:1512395704093/displayed"}}
Screenshot: available via screen

**Comment by barancev** [comment]
The exception occurs somewhere inside the driver, so it should be reported to chromedriver tracker:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by iarp** [comment]
You're saying somehow both chromedriver and phantomjs are returning the same error message?

**Comment by barancev** [comment]
You'll be surprised, but yes :)
It can be reproduced even without Selenium: https://github.com/detro/ghostdriver/issues/325

**Comment by iarp** [comment]
Ah ha, one of the other open issues linked on the ghostdriver issue mentions changing the user agent potentially causing it and I change the user agent with every start of the script. Thanks.
