### ISSUE TITLE
chromedriver working fine under cmd, powershell but crashes under ansicon (either cmd or powershell)

### ISSUE THREAD

**Issue by AtricoSoftware** [SeleniumHQ/selenium#5239]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.34.522940
Browser:  
Chrome
Browser Version:  
63.0.3239.84 (Official Build) (64-bit)

## Expected Behavior -
chromedriver runs as normal

## Actual Behavior -
"chromedriver.exe has stopped working" dialog
no logs, nothing!

## Steps to reproduce -
from powershell/cmd.exe
>ansicon
>chromedriver

Can be reproduced using "ansicon powershell" instead

**Comment by AtricoSoftware** [comment]
From the windows event log:
**Application ErrorEvent ID 1000**
Faulting application name: chromedriver.exe, version: 0.0.0.0, time stamp: 0x5a2c9c38
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x1571dc30
Faulting process id: 0x301c
Faulting application start time: 0x01d379b3ac365d26
Faulting application path: C:\bin\chromedriver.exe
Faulting module path: unknown
Report Id: 08e70713-c09f-435a-93e2-a2a8e36ca562
Faulting package full name: 
Faulting package-relative application ID: 

**Information: Event ID 1001**
Fault bucket 1975238666535247423, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: chromedriver.exe
P2: 0.0.0.0
P3: 5a2c9c38
P4: StackHash_b4ee
P5: 0.0.0.0
P6: 00000000
P7: PCH_21
P8: c0000005
P9: 00000008
P10: 

Analysis symbol: 
Rechecking for solution: 0
Report Id: 08e70713-c09f-435a-93e2-a2a8e36ca562
Report Status: 0
Hashed bucket: f5267cbdfdebd2570b69751a19731e3f

[Report.wer.txt](https://github.com/SeleniumHQ/selenium/files/1576426/Report.wer.txt)

**Comment by barancev** [comment]
Report this issue to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by AtricoSoftware** [comment]
Moved!
