### ISSUE TITLE
On High Sierra the preferred geckodriver is not always selected

### ISSUE THREAD

**Issue by bdezonia** [SeleniumHQ/selenium#5240]
## Meta -
OS:  
OSX High Sierra
Selenium Version:  
I've installed the 3.4.4, 3.6.0, and 3.8.0 rubygem for selenium-webdriver
Browser:  
Firefox

Browser Version:  
56.0.2 and 57.0.1

## Expected Behavior -

If multiple geckodriver installations are found at the @executable path prefer the one that is just named geckodriver

## Actual Behavior -

In the selenium source code the @executable name has a star appended to it ("geckodriver*"). The order of what is selected by selenium changed from Sierra to High Sierra (maybe because of changes in file system behaviors?). In my case tests that passed on Sierra started failing on High Sierra.

## Steps to reproduce -

On my system I have a geckodriver link in /usr/local/bin to my homebrew cellar version of 0.19.1. If you also place an older geckodriver in /usr/local/bin named geckodriver.sav selenium will prefer to use it instead.

In my case geckodriver.sav may have been version 0.14.0. I started seeing test failures with Capybara fill_in command where it complained that it expected a string and got a Undefined object instead. An IllegalArgumentException I think. This was a known bug fixed in 0.16.1 or similar.

None of these bugs were apparent until after upgrading to High Sierra.

**Comment by cgoldberg** [comment]
> prefer the one that is just named geckodriver

It would have to be a little smarter than that to work on all platforms.  On Windows, the file is named `geckodriver.exe`.
