### ISSUE TITLE
Chrome's force-device-scale-factor flag is not respected

### ISSUE THREAD

**Issue by tinganho** [SeleniumHQ/selenium#5241]
It seems like Chrome's `force-device-scale-factor` is not respected.
```ts
chromeOptions.addArguments('--force-device-scale-factor=2');
```
yields:
<img width="535" alt="screen shot 2017-12-21 at 02 17 00" src="https://user-images.githubusercontent.com/1324476/34235910-15e7230c-e5f5-11e7-950c-c139e4ec06a6.png">

whereas when I just run 
```
google-chrome --force-device-scale-factor=2
```
<img width="946" alt="screen shot 2017-12-21 at 02 15 28" src="https://user-images.githubusercontent.com/1324476/34235878-d740adee-e5f4-11e7-870c-57867be25a15.png">
`

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Also, please don't ignore the new Issue template, we ask that information so that we can attempt to diagnose the problem.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
This is working fine for me with python:

    >>> from selenium.webdriver import Chrome, ChromeOptions
    >>> opt = ChromeOptions()
    >>> opt.add_argument('--force-device-scale-factor=5')
    >>> driver = Chrome(options=opt)

**Comment by tinganho** [comment]
@lmtierney I use this Docker container https://github.com/elgalu/docker-selenium. 

Apply the mentioned patch here:
https://github.com/elgalu/docker-selenium/issues/200
And then build it:
```
docker build -t selenium .
```
Run the docker container. Add the argument `--force-device-scale-factor` and you will see that the window does not scale.

**Comment by lmtierney** [comment]
Those are not the official selenium docker images, and you still have not given a reproducible test scenario.

If you can reproduce it locally without a docker image, then we have something we can look into.

If you can't reproduce it locally without a docker image, but can reproduce it with a selenium docker image, then you can raise an issue with https://github.com/seleniumhq/docker-selenium

If you can only reproduce it with a docker image from https://github.com/elgalu/docker-selenium, then they'll need to help you

**Comment by diemol** [comment]
This can be closed here since the issue was opened in the other repo, I don't think this is a Selenium issue but more something between docker images and the usage of xvfb.
elgalu/docker-selenium#200
