### ISSUE TITLE
WIN10 IE11 selenium.common.exceptions.NoSuchWindowException: Message: Unable to get browser

### ISSUE THREAD

**Issue by theproshin** [SeleniumHQ/selenium#5242]
## Meta -
OS:  WINDOWS 10 (64) Corporate, 1709, 16299.125

Selenium Version:  
Server 3.8.1
client 3.8.0
IEDriverServer.exe 3.8.0

Browser:  
Internet Explorer 11.125.16299.0
Version update 11.0.49 (KB4052978)

## Expected Behavior -

driver.title should return the page title

## Actual Behavior -

selenium.common.exceptions.NoSuchWindowException: Message: Unable to get browser

## Steps to reproduce -

```
>>> selenium.__version__
'3.8.0'
>>> from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
>>> from selenium.webdriver import Remote
>>> cap = DesiredCapabilities.INTERNETEXPLORER.copy()
>>> driver = Remote(command_executor='http://remote_host:4444/wd/hub', desired_capabilities=cap)
>>> driver.get('http://google.com')
>>> driver.title
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\VENV\selenium\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 332, in title
    resp = self.execute(Command.GET_TITLE)
  File "C:\VENV\selenium\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\VENV\selenium\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: Unable to get browser
```

After that, the driver depends and does not respond to any commands

LOG [https://drive.google.com/file/d/1KkBp2xBBS1moSS9u-bemEBt0dQr3Ksxa/view](https://drive.google.com/file/d/1KkBp2xBBS1moSS9u-bemEBt0dQr3Ksxa/view)

PS. 
With system preferences 
OS WIN 10 64 Pro, 1709, 16299.**19**
IE 11 11.**15**.16299.0
update version 11.0.47 (KB4040685)

The error does not repeat.

**Comment by RedScrash** [comment]
I have the same issue afther last windows update.
OS: Windows 10 Pro
Version: 1709
Compiled: 16299.125
Windows update: KB4057247
IE Driver version: 3.8.0

**Comment by diemol** [comment]
Apologies for the lack of response.
I will close this issue since it did not get more traction, so it was either solved by recent versions of the IEDriver (in case the issue was caused by it), or it is not relevant anymore.

In case this issue is still valid, please feel free to open a new one and fill out all the information requested on the template.
