### ISSUE TITLE
[Enhancement] Option to specify if it is ok to attempt cilck on elements which appears to be invisible to webdriver

### ISSUE THREAD

**Issue by Nfactor26** [SeleniumHQ/selenium#5243]
**Problem description:**
Recently while working on several automation use cases, i ran in to some sites where 
a) target IWebElement is visible on the page , however , selenium reports that it can't interact with the element since element appears to be invisible to webdriver.
b) target IWebElement is immediately below some other element and webdriver fails to interact with it since it reports that some other element will receive the click instead. During a user interaction , typically element with watermark (overlaid html) gets removed from DOM and input element has the focus.

**Requested Enhancement:**
a) It should be possible to provide a flag whether to attempt any interaction on IWebElement which webdriver detects that it is not visible on the page while the element is actually visible on the page and user can interact with it.
b)It should be possible to provide a flag whether to attempt interaction such as click on an element even if webdriver detects that some other element will receive the click instead. 

Regards,
Nish26

**Comment by barancev** [comment]
1) If Selenium thinks an element is invisible while it's visible for a human -- please report this case as a new issue and provide a page where it can be reproduced.

2) Selenium can interact with visible (or, interactable) elements only. If you want to send an event to an invisible element you can use executeScript method.

3) If you want to click at some point, no matter what element is there, you can use Actions.

**Comment by Nfactor26** [comment]
Thanks barancev !!
I was not aware that click using Actions works differently. I will give it a try.
[Advanced Interactions documentation](https://github.com/SeleniumHQ/selenium/wiki/Advanced-User-Interactions ) mentions that  "ClickAction - Equivalent to WebElement.click()" .

For invisible element issue, i will try to open a new issue as soon as i can find some example on some internet site.

**Comment by barancev** [comment]
The wiki page desribes legacy drivers. I've added there a link to the up to date specification: https://w3c.github.io/webdriver/webdriver-spec.html#actions
