### ISSUE TITLE
Target exception: org.openqa.selenium.WebDriverException: Permission denied to access property 'M'

### ISSUE THREAD

**Issue by VidyaTigani** [SeleniumHQ/selenium#5244]
This is my code,
In firefox 45 it is giving above error.
I am able to run this script through jmeter in firefox, but not in Blazemeter.

My code is,

import org.apache.jmeter.services.FileServer;
import org.openqa.selenium;
import org.openqa.selenium.firefox.FirefoxProfile;
import java.time.temporal.ChronoUnit;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;   
import org.openqa.selenium.WebElement;
import org.openqa.selenium.By;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.util.concurrent.TimeUnit;
import java.util.ArrayList;
import java.util.List;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
WebDriverWait wait= new WebDriverWait(WDS.browser,220);
WDS.sampleResult.sampleStart();
WDS.browser.get("https://app.mammoth.io/#/login");

wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("userEmail"))).sendKeys(new String[] {"deepak.merahkee@gmail.com"});
wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("userPwd"))).sendKeys(new String[] {"*************"});
login=wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[@class='btn btn-mammoth']")));
start=LocalDateTime.now();
login.click();
wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//section[@class='workspace ng-scope']")));

end=LocalDateTime.now();
Long minutesBetween=ChronoUnit.MILLIS.between(start,end);
String Timestamp = Long.toString(minutesBetween);

WDS.log.info("Login: login = "+Timestamp);
WDS.browser.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);  
 
WDS.sampleResult.sampleEnd();

**Comment by VidyaTigani** [comment]
How to solve this? And what is property M in the error.

**Comment by luke-hill** [comment]
Can you just double check your Firefox version, that is incredibly outdated (Nearly 2years I believe).

If you are not using Marionette you can still upgrade to a version much newer than that, if not then the latest Firefoxen (56/57 Quantum), should be used first.

**Comment by sbabupresidency1** [comment]
Yes. Luke is correct. Update your firefox version to the latest. and change your code.
- Babu S

**Comment by VidyaTigani** [comment]
In firefox version 57 it won't work. I am running this script through Jmeter. In that with firefox version 45 it is working fine. But in blazemeter it gives this error. I want to run this in blazemeter.

**Comment by barancev** [comment]
Please report this issue to Blazemeter.
