### ISSUE TITLE
chromeOptions.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true) Error

### ISSUE THREAD

**Issue by MeiJunZhang** [SeleniumHQ/selenium#5245]
**System:**
Platform: Win 10
Chrome: 63.0.3239.84
Selenium WebDriver: 3.8.0
Program Language: C#
**Issue**
Hey, when I use the dotnet simulation to visit HTTPS website, need to use the chromeOptions.AddAdditionalCapability (CapabilityType.AcceptSslCertificates, true); however, when the program execution here will prompt an error:“ [See nested exception: System.InvalidOperationException: unknown error: cannot parse capability: goog:chromeOptions
From unknown error: unrecognized chrome option: acceptSslCerts”,this is my code:
var chromeOptions = new ChromeOptions();
chromeOptions.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
var driver = new ChromeDriver(chromeOptions);
driver.Navigate().GoToUrl("http://www.baidu.com/");

**Comment by lmtierney** [comment]
`AcceptSslCertificates` is a `DesiredCapability` not an option for chrome

**Comment by lmtierney** [comment]
Sorry, I see now that you did have `true` set in there to add them to the top level ones

**Comment by lmtierney** [comment]
Add another true in there to add it to the top level capabilities 

    chromeOptions.AddAdditionalCapability (CapabilityType.AcceptSslCertificates, true, true)

**Comment by MeiJunZhang** [comment]
@lmtierney  This is the first time I use this program, and there may be a problem of continuous feedback, thanks a lot!
