### ISSUE TITLE
set_window_size crashing browser

### ISSUE THREAD

**Issue by JClant** [SeleniumHQ/selenium#5247]
## Meta -
OS:  Ubuntu Server 16.04

Selenium Version:  3.8.0

Browser:  Chrome

Browser Version:  63.0.3239.84

## Expected Behavior -
Save screenshot of very long page.
## Actual Behavior -
```
Traceback (most recent call last):
  File "do.py", line 13, in <module>
    browser.get("https://github.com/SeleniumHQ/docker-selenium/issues/520")
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-87-generic x86_64)
```

## Steps to reproduce -
```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

options = webdriver.ChromeOptions()
options.add_argument('headless')

browser = webdriver.Remote(
        command_executor = 'http://selenium:4444/wd/hub',
        desired_capabilities = options.to_capabilities())

browser.set_window_size(1280, 10000)
browser.maximize_window()
browser.get("https://github.com/SeleniumHQ/docker-selenium/issues/520")
browser.save_screenshot("s.png")
browser.quit()
```
Reducing height to under 2000px seems to work most of the time, although sometimes I get the same error for lower height.

**Comment by barancev** [comment]
Please report this issue to chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by JClant** [comment]
The same problem happens with Firefox, so I think it is not Chrome specific

**Comment by barancev** [comment]
1. Please explain why do you think it's the same problem?
2. I can't reproduce the issue on my Windows box, so it's environment specific. May be you just does not have, say, enough memory?
3. In any case, as soon as a driver executable crashes, we can't fix this issue, it should be reported to the driver creator, that is a browser vendor.

**Comment by JClant** [comment]
1. I get similar error saying Firefox driver crashed
2. Most likely environment specific. First I thought low memory might be the reason because I was running it in a VM, but same problem on bare metal. Both times inside Docker.
Also I did run PhantomJS directly. It didn't have any problem rendering over 10000px. P. S. Chrome headless is supposed to be lighter on memory.
3. That is clear. Thanks for your time
