### ISSUE TITLE
selenium-webdriver in Rails 5.2 system tests: "unable to connect to chromedriver 127.0.0.1:9515"

### ISSUE THREAD

**Issue by GBH** [SeleniumHQ/selenium#5248]
## Meta -
OS:  
Ubuntu
Selenium-webdriver Version:  
3.8.0
Browser:  
Chrome
Browser Version:  
58

## Expected Behavior -
Being able to run tests

## Actual Behavior -
```
Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:142:in `connect_until_stable'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:72:in `block in start'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/service.rb:69:in `start'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/chrome/driver.rb:41:in `initialize'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/driver.rb:44:in `new'
    selenium-webdriver (3.8.0) lib/selenium/webdriver/common/driver.rb:44:in `for'
    selenium-webdriver (3.8.0) lib/selenium/webdriver.rb:84:in `for'
    capybara (2.16.1) lib/capybara/selenium/driver.rb:23:in `browser'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:52:in `block in register_selenium'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:51:in `tap'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:51:in `register_selenium'
    actionpack (5.2.0.beta2) lib/action_dispatch/system_testing/driver.rb:27:in `block in register'
```

## Steps to reproduce

A completely fresh vanilla Rails app with a simple generated system test.

Not sure what I need to do. Chromedriver is installed and can be ran:

```
$ which chromedriver
/home/oleg/.rbenv/shims/chromedriver

$ chromedriver -v
ChromeDriver 2.34.522913 (36222509aa6e819815938cbf2709b4849735537c)
```

Any clues what I might be missing here? Thanks.

**Comment by cgoldberg** [comment]
This is not a Selenium issue.  You are trying to use Chrome 58 with Chromedriver 2.34, but version 2.34 only supports Chrome 61-63.

 See: https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by GBH** [comment]
That might have something to do with it. I'll give it a try. Thanks!

**Comment by GBH** [comment]
This was an environment issue. I had to:

- `gem uninstall chromedriver-helper`
- remove it from rbenv shims (`which chromedriver` for that)
- Download directly http://chromedriver.storage.googleapis.com/index.html
- plug chromedriver somewhere on the $PATH (I just plopped in ~/bin)

Hopefully this will help others that google for the same issue.

**Comment by titusfortner** [comment]
@GBH so you know, the `webdrivers` gem does the same thing as chromedriver-helper to auto-update the drivers, only without shims if that is appealing.

**Comment by joshpencheon** [comment]
It's worth noting that the `chromedriver` executable that is provided by `chromedriver-helper` performs the actual download / installation from https://chromedriver.storage.googleapis.com lazily.

Therefore, if for whatever reason that installation doesn't complete with selenium's timeout period, you can have issues.

Running e.g. `chromedriver --help` and waiting will force the gem to download the driver in advance.

**Comment by titusfortner** [comment]
fwiw, the `webdrivers` gem will wait for the download (if needed) before attempting to use the driver (and starting the timeout clock). Everything is better without shims. :)

**Comment by dipto0321** [comment]
> This was an environment issue. I had to:
> 
> * `gem uninstall chromedriver-helper`
> * remove it from rbenv shims (`which chromedriver` for that)
> * Download directly http://chromedriver.storage.googleapis.com/index.html
> * plug chromedriver somewhere on the $PATH (I just plopped in ~/bin)
> 
> Hopefully this will help others that google for the same issue.

Nice solution. Worked for me 👍

**Comment by rgaufman** [comment]
I had the same issue:

```
$ chromedriver -v
ChromeDriver 2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052)
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 71.0.3578.80
$ rspec
...
     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:9515
...
```

I resolved it by running:

```
gem uninstall chromedriver-helper
bundle install
```

Thank you!!
