### ISSUE TITLE
Maps returned form Javascript are empty

### ISSUE THREAD

**Issue by MrNakaan** [SeleniumHQ/selenium#5250]
## Meta -
OS:  Windows 10

Selenium Version: 3.4.0 

Browser:  Chrome 63.0.3239.84 (Official Build) (64-bit)

## Expected Behavior -
Given the following:
`((JavascriptExecutor) driver).executor.executeScript("var foo = new Map(); foo.set('one', 2); foo.set('two', 4); foo.set('three', 8); foo.set('four', '16'); return foo;");`
A `Map<String, Object>` is expected to be returned

## Actual Behavior -
An empty `Map` is returned, event when attempting to cast from the originally returned `Maps$TransformedEntriesMap` class to a `Map<String, Object>` or `Map<Object, Object>`

## Steps to reproduce -
```
package com.example.selenium.bug;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class BugDemo {
public static void main(String[] args) {
Map<String, Object> values = ((JavascriptExecutor) new ChromeDriver()).executor.executeScript("var foo = new Map(); foo.set('one', 2); foo.set('two', 4); foo.set('three', 8); foo.set('four', '16'); return foo;");
System.out.println("Size: " + values.size()); // Should be 4, returns 0
}
```

**Comment by barancev** [comment]
I've created an issue on W3C WebDriver specification: https://github.com/w3c/webdriver/issues/1178

First it should be added to the spec, and then we'll be able to raise issues on drivers (including chromedriver)

**Comment by MrNakaan** [comment]
The doc at https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html should be updated to indicate that Mats don't return properly.

**Comment by farhadbaghirov** [comment]
when execute following javascript code ,executeScript method return empty map,actually map should not empty.
`var myMap = new Map();
var element = document.getElementById('sadsadas');
var subList = element.getElementsByTagName('span');
var i;
for(i = 0; i < subList.length; i++){
var spanElement = subList[i];
var id = spanElement.getAttribute('id');
var style = spanElement.style.display;
var text = spanElement.innerHTML;
myMap.set(id,text);
}
return myMap;`
