### ISSUE TITLE
HOW CAN I MAKE selnium testing service SITE ??????????

### ISSUE THREAD

**Issue by jjunest** [SeleniumHQ/selenium#5251]
## Meta -
OS:  windows10

Selenium Version:  

	<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.44.0</version>
		</dependency>

Browser:  
Chrome Browser

## Expected Behavior -
I want make the "selenium testing web site" .

I want if user click the button on my page, the selenium webdriver started and do the automatically specific actions. (like login)

but,,,, I tested the all code and it works well in my local computer.

but when i uploaded the mycode to webserver ("i'm using hosting service").

it didn't work.

the problem is "the web driver open";

how can i make the selenium testing website?

below is my code.

if user click the open button, user's computer open the chrome browser automatically!!

please help me!!

below is my code. and this is Spring 

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model, HttpServletRequest httpServletRequest) {

		String chromeDriver2_34 = httpServletRequest.getSession().getServletContext().getRealPath("resources/chromedriver_win32_1/chromedriver.exe");
		driver = new ChromeDriver();
		driver.get("https://www.naver.com");
		
		
		
		return "home";
	}

## Actual Behavior -

it works in my local computer.. but it didn't work on the hosting server.

why is it happened? and how can i fix the problem?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
