### ISSUE TITLE
Strongname issue in Selenium DotNET.

### ISSUE THREAD

**Issue by sebionofrei** [SeleniumHQ/selenium#5254]
Steps to reproduce:

1. create an empty windows (or console) app.
2. download the strongnamed version of the selenium libraries (i've used 3.8.0 - net40)
3. reference all files in the project.
4. Try to identify a SelectElement anywhere in your project. You'll see errors like in the attachment bellow:
![selenium-error](https://user-images.githubusercontent.com/5826625/34319981-ae7fe5c8-e7f7-11e7-801e-338e22388302.png)

If you do the same but with the unsigned libraries, this issue is not happening. This also did not happen in 3.7.0 and earlier versions. Started happening since 3.7.1
This is because, as you can see, the SelectElement exists only in the unsigned one, and can't be referenced.

@jimevans - i already tried to speak about the same thing in ticket #5227 but you closed it believing that i was complaining about nupkg files (which is not true)

**Comment by daweedz** [comment]
I get the exact same error message for the ExpectedCondition class in 3.8.0.0.

![image](https://user-images.githubusercontent.com/8189367/34488056-3e8ddfda-efd7-11e7-83ce-156dae7bc09e.png)

**Comment by jimevans** [comment]
This should be fixed with commit 19e81de. See the forthcoming 3.9 release of the .NET bindings (sorry, no official release date is available) for the fix.

**Comment by daweedz** [comment]
Is it just me, or anyone else still have this issue with 3.9?
![image](https://user-images.githubusercontent.com/8189367/35858147-b6f49782-0b3b-11e8-89fa-c98c90295ab1.png)

**Comment by jimevans** [comment]
@daweedz Please try 3.9.1 of the .NET bindings. I believe I've actually, truly, for realz fixed the issue with the .NET build process now.
