### ISSUE TITLE
IEDriverserver close automatically

### ISSUE THREAD

**Issue by patelrais** [SeleniumHQ/selenium#5261]
Selenium with IE (latest version) working when run in .Net. But if run the same exe on other machine driver window close first and the load url in IE and rest of the process stop working. 
Path of IEDriverserver is specified in the selenium. I have also tried tools->Security->enable protected mode for Inernet/Local Intranet/Trusted Sites/Restricted sites, still getting same issue.
Please help.
On the same machine where this issue getting when run the exe from Visual Studio its working fine, but not working when exe run separately without visual studio.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
