### ISSUE TITLE
Is public Actions doubleClick(WebElement target) deprecated?

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5264]
## Meta - Is **`public Actions doubleClick(WebElement target)`** deprecated?

Documentation at [**`Package org.openqa.selenium.interactions`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/package-summary.html) says it is deprecated.

![doubleclick](https://user-images.githubusercontent.com/26503213/34361291-ab87fec0-ea8e-11e7-9ef9-a953c040200d.png)

But again, documentation at [**`doubleClick`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#doubleClick-org.openqa.selenium.WebElement-) says it exists.

![doubleclick](https://user-images.githubusercontent.com/26503213/34361326-1c41a620-ea8f-11e7-93bb-d49d35171b0c.png)

Can we get a clarification please?

OS:  All
Selenium Version:  3.8.1
Browser:  All

Browser Version:  All

**Comment by kool79** [comment]
What is the issue? "Deprecated" does not mean it must not exists. But it can be deleted in future. When? depends on deprecation policy and (maybe) other factors.
https://en.wikipedia.org/wiki/Deprecation

**Comment by Johnsavadkuhi** [comment]
no  

says  DoubleClickAction deprecated  use  doubleClick ( )  instead of

**Comment by barancev** [comment]
All *Action classes in org.openqa.selenium.interactions are deprecated because we're changing the the underlying implementation. But these classes were never supposed to be used directly. Users were expected to use Actions class that builds and performs action sequences. And this part of API is not changes and is not depreated.
