### ISSUE TITLE
internet explorer mouse over sub-menus not working python

### ISSUE THREAD

**Issue by mrajancsr** [SeleniumHQ/selenium#5265]
Hello, i have an issue using selenium with python and internet explorer.   I am performing automated testing and I need to download prices from a website by hovering over the "settlements" tab, and upon hovering over this tab, a "settlement info" tab shows up.  Upon hovering over this, a "view" tab shows which i need to click.  

I can successfully hoer over the "settlements" tab which shows the hovering and closes it a milli second.  But i am not able to hover over the corresponding tabs.  Ironically, my code doesnm't throw off any error, but in the website, i am still at the current "site" and haven't really gone to the location where the prices are stored.  Any help would be appreciated.  This is my code:

   from selenium import webdriver
import os
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait as wait
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

caps = DesiredCapabilities.INTERNETEXPLORER
caps['enablePersistentHover'] = False
caps['nativeEvents'] = False
#set directory where files will be downloaded
iedriver = 'H://work/IEDriverServer.exe'
driver = webdriver.Ie(iedriver,capabilities=caps) #establish internet explorer as website

#website where we download files from
url = 'https://markets.midwestiso.org/MISO/'
driver.get(url)
driver.switch_to.alert.accept()
time.sleep(2)

driver.switch_to.frame('nav')

settlements_menu = driver.find_element_by_id("tab2_p")

driver.switch_to_default_content()
driver.switch_to_frame("ContentFrame")
settlement_info_menu = driver.find_element_by_id("tab2_tab2flyover0")
view_menu =  driver.find_element_by_id("tab2_tab2flyover0text0")

action = ActionChains(driver)
action.move_to_element(settlements_menu).move_to_element(settlement_info_menu)

action.click(view_menu).perform()

Heres the html of the website.  Unfortunately, you won't be able to enter the website without permissions (which i do have).  

    <html>
      <frameset name = "frameset" frameborder="no" noresize="">
    <frame name="nav" src="/miso/header/header.do;jsessionid=2d..!" frameboarder="no" no resize="" scrolling="no">
      <html>
        <body background = "/miso/images/hdrbackgroundslvr.gif >
           <table width ..>
           <div id="xclock1"..>
           <div id="tab1">
           <div id="tab2">
              <table width="115">
              <tbody>
                <tr>
                  <td class='normalHeaderTabs" id="tab2TableDetail" style="background: url ("https://markets.midwesiso.org/MISO/images/hdrTabNormal.gif");">..</td>
                     <p id="tab2_p" style="color: rgb(2555,255,255);" onmouseover="this.style.color=">Settlements</p
                  </td>
                </tr>
              </tbody>
             </table>
            </div>
    <frame name="ContentFrame"
     src="/MISO/common/blank.html;jsessionid=2bC6h1hLNJwrN..." frameborder="no" scrolling="auto">
        <html>
          <head>..</head>
          <body>
            <table witdh='735' ..></table>
            <div id='tab1flyover0" onmouseover='document.getElementbyID('tab1flyover0DivShim')
              <table width="160" cellspace="0" cellpadding="0">
                <tbody>
                  <tr>
                    <td aligh="left" id="tab2_tab2flyover0tableDetail0" valign="center" onclick='parent.frames[0].changeTopTabs('tab2TableDetail');parent.frames[0].changeContentFrame('/MISO/vss/view.do?cmd=view');">
                      <p id="tab2_tab2flyover0text0" style="color:black;">View</p>
                     </td>
                   </tr>
                 </tbody>
                 </table>
               </div>
            <div id="tab1flyover2" style="left" onmouseover='document..'
            <iframe id='tab1flyover1DivShim'>
            <div id="tab2" onmouseover='document.getElementById("tab2DivShim");document.getElementByid('tab2').style.visibility='visible';"onmouseout="..'
            <table width="160">
             <tbody>
               <tr>
                 <td height="20" id="tab2_tab2cell0"; onmouseover="document.getElementByID('tab2flyover0') onmouseout='document.getElementByID("tab2_tab2Cell0).style.backgroundcolor='#C0CoCo';document.getElementbyId('tab2flyover0').style.visibility='hidden'
                   <p id='tab2_tab2flyover0" >Settlement Info</p>
                 </td>
               </tr>
             </table>
            </div>
            <

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

For issues, please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
