### ISSUE TITLE
 org.openqa.selenium.InvalidSelectorException - cannot be evaluated or does notresult in a WebElement

### ISSUE THREAD

**Issue by kalyanihg** [SeleniumHQ/selenium#5267]
Using IE 11 and getting below error - 
Exception in thread "main" org.openqa.selenium.InvalidSelectorException: The xpath expression './/*[@id='zz11_RootAspMenu']/li/ul/li[1]/ul/li[1]/a/span/span' cannot be evaluated or does notresult in a WebElement (WARNING: The server did not provide any stacktrace information)

DOM HTML is - 
<li class="dynamic">
<a class="dynamic menu-item ms-core-listMenu-item ms-displayInline ms-navedit-linkNode" href="javascript:OpenWizardAsModalDialog('/locator.aspx?name=DMS.Case.New.23&subtype=23');" tabindex="0">
<span class="additional-background ms-navedit-flyoutArrow">
<span class="menu-item-text">Case</span>
</span>
</a>
</li>

**Comment by kalyanihg** [comment]
Please let me know how click on the menu item , Its urgent.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by kalyanihg** [comment]
This was working earlier , and now showing above error thats why I added this as an issue.
