### ISSUE TITLE
Selenium Java-facing issue while running IE script

### ISSUE THREAD

**Issue by madhur-dumane** [SeleniumHQ/selenium#5268]
Java Selenium- We use either Virtual Machine or cloud to run Scripts.

Virtual Machine- When we actually working on Virtual machine it means when it is active then scripts are passing but when virtual Machine disconnect(disconnection might be because of any reason like we manually disconnected or machine shut down or suppose if I just locked machine and went then after some time it will disconnect automatically.) that time scripts are failing. When analyzed then got to know that its just opening IE browser then entering url but after that its not entering username password not even clicking button nothing is happening and scripts are failing.

Cloud: on aloud also we facing similar issue as I mentioned above for VM but additional to that for VM when you lock(windows+L) machine then it is working fine till VM get disconnect but for cloud even if you lock or even minimize that cloud then also scripts are failing.

Note: Chrome scripts are working fine in any condition.

**Comment by barancev** [comment]
IE can't work in "detached" session, it's a technical restriction that has no known solution at the moment. Keep the session active.

**Comment by madhur-dumane** [comment]
how to keep session active?Can you share anything for this?

**Comment by barancev** [comment]
Don't lock it. Disable screensaver. Don't disconnect from RDP/VNC session.
