### ISSUE TITLE
[Feature Request] pause/resume webdriver (render page, execte js) . 

### ISSUE THREAD

**Issue by eromoe** [SeleniumHQ/selenium#5269]
Hello, 

I don't see such feature so ask here. I think it is very useful to pause/freeze the webdriver.

Imagine:

1. A web page has some function automatically change element on the page or execute some js change content.

2. I need check some element content in the page( Because I need click the button, so I can't just save the html right after page render completely ) and do some other works.

3. I need click a button before that button changed/disappear.  

4.  Click this button change the page elements, so I can do `2` . 

So it would be very nice if there is some way to tell driver stop render html anymore, stop executing any javascript , flash or something else .  Resume  in future .  

Like:

```python
driver.pause() 

day_btns = driver.find_elements_by_css_selector('.CalendarCon a')

# if not pause, links and btns may change
links = driver.find_elements_by_css_selector('#artContainer a')

save_to_db([l.get_attribute('href') for l in links])

something_else()


for btn in day_btns:
    driver.resume() 
    btn.click()

    wait = WebDriverWait(driver, 5)
    wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, '#artContainer ul')))

    driver.pause() 

    links = driver.find_elements_by_css_selector('#artContainer a')
    save_to_db([l.get_attribute('href') for l in links])
    something_else()
    
```

**Comment by p0deje** [comment]
This has to be implemented in drivers and is outside of Selenium control. I'm not even sure it's even possible at all. You can try creating issue against [webdriver spec](http://goo.gl/LxCtcV) - if it's accepted and becomes the part of spec, then drivers will implement them eventually.

**Comment by edurenye** [comment]
I created this issue w3c/WebPlatformWG#98 to implement it as WebPlataformWG has taking the role of IndieUI Events after it being deprecated.

**Comment by edurenye** [comment]
Looks like the right place is in w3c/webdriver#1199
