### ISSUE TITLE
Input field accepting more than its maximum length-iOS Devices

### ISSUE THREAD

**Issue by ppanuganti** [SeleniumHQ/selenium#5270]
Device : Mobile Phones and Tablets
OS :  iOS
Appium Version : 1.6.4
Browser : Safari

Hi,

I'm experiencing an issue with the sendKeys method on a textfield where the input field is accepting more than its maximum length, I have set the maxlength as 10 but during executions the input field is accepting more than 10. This issue is seen on iOS Devices(Mobile phones and tablets) whereas it is working fine in Desktop Safari. I'm using selenium webdriver in Java.

This is the piece of code:
			driver.get("http://scorebuzz.000webhostapp.com/");
			driver.findElement(By.id("firstname")).sendKeys("abcdefghijklmnop");
			String ele = driver.findElement(By.id("firstname")).getAttribute("maxlength");
			System.out.println(ele);

This is the link to the site
http://scorebuzz.000webhostapp.com/

Is there a way to handle the max length such that only 10 characters are entered and restricts the further characters in automation.

Thanks and Regards,

**Comment by barancev** [comment]
Please report this issue to Appium project.
