### ISSUE TITLE
Unable to match capability set 0: se:CONFIG_UUID with InternetExplorerDriver on a grid node

### ISSUE THREAD

**Issue by bhecquet** [SeleniumHQ/selenium#5272]
## Meta -
OS:  Windows 7

Selenium Version:  3.8.1

Browser:  Internet Explorer

Browser Version:  11

## Expected Behavior -
Calling this constructor should launch driver

## Actual Behavior -
Error is `org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: se:CONFIG_UUID is an unknown extension capability for IE`

Removing se:CONFIG_UUID capability do the trick, but it's a wordaround 

## Steps to reproduce -
I'm using selenium grid with a custom DriverProvider. Grid is started with "enablePassThrough" option set to false. It works well with firefox or chrome, but with Internet Explorer, when calling `new InternetExplorerDriver(capabilities);`,I get 

`18:03:03.750 INFO - Creating a custom new session for Capabilities {acceptSslCerts: true, browserName: internet explorer, ensureCleanSession: true, ie.ensureCleanSession: true, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: about:blank, javascriptEnabled: true, proxy: {proxyType: autodetect}, se:CONFIG_UUID: a94e237b-8194-4648-8a5a-460..., takesScreenshot: true, version: , webdriver.ie.driver: D:/Dev/seleniumRobot-grid/d...}
org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: se:CONFIG_UUID is an unknown extension capability for IE
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'SN782980', ip: '172.23.21.176', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: InternetExplorerDriver`

It seems that driver (Win32 version 3.8.0) does not support the CONFIG_UUID capability

**Comment by jimevans** [comment]
No, it doesn’t. And it doesn’t have to, according to the W3C WebDriver spec. The custom driver provider does not conform to the spec. The IE driver will, by design, be very strict about what capabilities it matches. You’ll need to have the custom provider emit valid, spec-compliant capabilities for spec-conforming remote ends (of which the IE driver is one as of 3.5)

**Comment by bhecquet** [comment]
I may miss something but what I see is that this capability is added by the grid hub, not by my custom driver provider

----- Mail original -----
De: "jimevans" <notifications@github.com>
À: "SeleniumHQ/selenium" <selenium@noreply.github.com>
Cc: "bhecquet" <bhecquet.w@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 29 Décembre 2017 19:46:30
Objet: Re: [SeleniumHQ/selenium] Unable to match capability set 0: se:CONFIG_UUID with InternetExplorerDriver on a grid node (#5272)



Closed #5272 .
