### ISSUE TITLE
Wiki SSL Implementation Typo 

### ISSUE THREAD

**Issue by codered** [SeleniumHQ/selenium#5274]
I am opening this request so someone can update the SSL Section of the wiki for ruby-bindings. 

I spent over 2-3 hours debugging (looking at source code and such) and then I realized the documentation missed the two "::" between Remote & Capabilities :(

The text in question:

> 
> capabilities = Selenium::WebDriver::Firefox::RemoteCapabilities.firefox(accept_insecure_certs: true)
> driver = Selenium::WebDriver.for :firefox, desired_capabilities: :capabilities

This should actually be:

caps = Selenium::WebDriver::**Remote::Capabilities**.firefox(accept_insecure_certs: true)
browser = Selenium::WebDriver.for :remote, desired_capabilities: caps

Thanks in Advance! 

Keep up the great work :)

**Comment by luke-hill** [comment]
Could you rename this to `Wiki - Ruby Bindings missing Module Namespacing "::" in Docs`

**Comment by lmtierney** [comment]
This has been updated.
