### ISSUE TITLE
Link Click opens two new windows and does not load the new pages

### ISSUE THREAD

**Issue by Sonali2608** [SeleniumHQ/selenium#5275]
Still facing issues with handling new window (whenever a link click -opens new window it opens up two windows on click event). Ideally it should open one window which is excepted scenario. But two windows are opened up one of them ends up in page not found(on checking URL it is found out that session id , cookies are not passed), the second one keeps on loading ,loading and does ends up in time out as (the session cookies is incorrect)

Code cannot be shared here due to privacy issues. But code is simple and the link to be clicked is in Iframe.

		driver1.findElements(By.tagName("iframe")).size();
		driver1.switchTo().frame(0);
		driver1.findElement(By.xpath("")).click();

Does anyone have any idea why the link click opens up two windows?

Also when I login with normal system IE.exe it works. But the same URL when hit through IE driver32bit even manually the click opens up two windows?

**Comment by badari412** [comment]
Which version of IE? which version of Selenium? I suggest you to go through this link, the user seems to have similar problem:
(https://stackoverflow.com/a/38867632/7433942)

Here the user resolved the problem by setting the native events to true.

**Comment by Sonali2608** [comment]
I already had below in my code, still no luck.
I have IE 32 bit driver, IE 11 , Selenium java - 3.8.1 .

			DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
			ieCapabilities.setCapability("nativeEvents", true);    
			ieCapabilities.setCapability("unexpectedAlertBehaviour", "accept");
			ieCapabilities.setCapability("ignoreProtectedModeSettings", true);

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

We don't need your exact original code protected by privacy rules. Just create an artificial sample page and a scenario against this page that allows to reproduce the issue.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
