### ISSUE TITLE
I am getting the following error with the latest images in selenium -firefox-debug .

### ISSUE THREAD

**Issue by annapetrai** [SeleniumHQ/selenium#5277]
Testing started at 2:52 μμ ...
Codeception PHP Testing Framework v2.3.7
Powered by PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

  [RunProcess] Starting php ./vendor/bin/codecept clean

In WebDriverException.php line 114:
                                                                               
  Session [(null externalkey)] not available and is not among the last 1000 t  
  erminated sessions.                                                          
  Active sessions are[ext. key 82e9187e-c730-47a5-9b50-9df4f856c953]           
                                                                               

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

**Comment by barancev** [comment]
Please report this issue to Codeception project.
