### ISSUE TITLE
With selenium-webdriver 3.8.0 and IE driver 3.8, IE 11 gives issue

### ISSUE THREAD

**Issue by reemanaik** [SeleniumHQ/selenium#5278]
## Meta -
OS:  
Win10 64 bit
Selenium Version:  
3.8.0
Browser:  
Internet Explorer
Browser Version:  
11.125.16299.0

Expected Behavior -
When browser is opened by using below given steps, it should properly redirect to first google.com and then yahoo.com. 
@browser.goto('www.google.com')
> redirect to www.google.com
@browser 
> instance details
@browser.goto('www.yahoo.com')
> redirect to www.yahoo.com

Actual Behavior -
@browser.goto('www.google.com') 
> redirects to google.com correctly.
@browser 
 > gives Watir::Exception::NoMatchingWindowFoundException: browser window was closed message

Steps to reproduce -
For 32 bit ruby, open IRB console and open browser using following commands.
require 'watir'
client         = Selenium::WebDriver::Remote::Http::Default.new
client.open_timeout = 500  
caps           = Selenium::WebDriver::Remote::Capabilities.internet_explorer(
    :initialBrowserUrl              => 'about:blank',
    :enablePersistentHover          => false,
    :ignoreProtectedModeSettings    => true,
    'ie.ensureCleanSession'         => true,
    :unexpectedAlertBehaviour => 'ignore',
    :introduce_flakiness_by_ignoring_security_domains => true
)
@browser       = Watir::Browser.new :ie, :http_client => client, :desired_capabilities => caps
@browser.goto('www.google.com') 
@browser
@browser.goto('www.yahoo.com')

**Comment by titusfortner** [comment]
What version of Watir are you using? The latest versions of Watir have a Configuration class that makes most of that code unnecessary.

I don't have a Windows machine handy to reproduce this directly. Can you do this and link to a gist of the output?

```ruby
Selenium::WebDriver.logger.level = :info
Watir.logger.level = :info
```

**Comment by reemanaik** [comment]
I am using Watir 6.8.4. I have attached the log file.
[ie_error_log.txt](https://github.com/SeleniumHQ/selenium/files/1599376/ie_error_log.txt)

**Comment by p0deje** [comment]
I cannot reproduce and this might happen because of `introduce_flakiness_by_ignoring_security_domains`. Please, try disabling it and reproducing.
