### ISSUE TITLE
Performance getting slower and slower after each webDriver.navigate().to(pageUrl); and findElement*()

### ISSUE THREAD

**Issue by dpalic** [SeleniumHQ/selenium#5280]
## Meta -
OS:  linux / Ubuntu 16.04 x64
Selenium Version:  3.8.1
Browser:  Firefox
Browser Version:  57.0.1

## Expected Behavior -
on many page opens with `webDriver.navigate().to(pageUrl)` and in every page itself about 100 `webElement.findElement*(By.xpath())` or `webDriverWait.findElement*(By.xpath())` shall not change any response times of the findElement*() method.

## Actual Behavior -
right now (and at least since 3.5) the longer we try to hold open one webdriver (FF-window) the slower the access are getting. (but you need to access different xpaths and really many thousands different findElement*(By.xpath()) methods. The performance is degrading for a simple xpath quickly to 1000ms on the same page, which take before only tens of ms.

The only workaround is to close the current webdriver about 1000 findElement*() calls and to reopen a new webdriver. The issue here is that it is not so easy to take over the session details from webdriver to webdriver. (hope someone can point me to a good solution, which is able to handle also XSRF-tokens and other security dependent tokens.

## Steps to reproduce -
on any page with many results can this behavior be reproduced. (e.g. google, amazon, ...)

**Comment by JyothiMurthy** [comment]
Even I am facing the same issue with Chrome Driver while running in maven

**Driver Info :** 
Chrome Driver version : 2.29
Chrome Browser Version : 57
Selenium Jar Version : 2.53

**Comment by AutomatedTester** [comment]
this is tracked in https://github.com/mozilla/geckodriver/issues/729. as for chrome you'll need to raise a bug there
