### ISSUE TITLE
WebElements getting Stale

### ISSUE THREAD

**Issue by at1087** [SeleniumHQ/selenium#5282]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Actual Behavior -
With previous version of Selenium, I used to pick up several hundreds of Button WebElements, place them on a list and click one at a time from the list, pick up the data that I needed, click "Back" and pick up the next button from the list.
Now, with the latest version, I am unable to do any more and I am forced to query again all those buttons.
The DOM is still active all the time.
I am using ChromeDriver on Windows 10 Pro and my program is C# 

THanks,
Ahaorn
Aharon.Tam@gmail.com

[18:41] <AT_> I wonder if it is a bug that was introduced or there is another way to maintain all these button active?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
