### ISSUE TITLE
maven selenium-java 3.*.jar files all 1KB in size (empty)

### ISSUE THREAD

**Issue by MrCodingMachine** [SeleniumHQ/selenium#5283]
Had problems compiling today and noticed that in the maven repository where selenium is stored...

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/

It looks like every selenium-java jar artifact that is 3.0 and greater is only 1kb and only contains MANIFEST file.

Not sure if this issue is something for this site or if it's a Maven site related issue. 

UPDATE:  I noticed in issue 5142 the following comment:

_barancev  commented on Nov 29 2017 • 
Sorry. Our upload script by mistake attempted to upload files in text mode instead of binary.
This has been just fixed and correct files have been uploaded._
 
So maybe the upload scripts did the same thing to the Maven repo and that's why they are all 1kb?

Thanks.

**Comment by barancev** [comment]
selenium-java artifact does not have any code, it's correct. It's just an "entry point" that contains a set of dependencies on the artifacts that hold real code. Yes, it should be better deployed as a POM-type artifact, see #4176
