### ISSUE TITLE
Unable to find a matching set of capabilities - Selenium 3.4.0 when Running in Selenium Grid

### ISSUE THREAD

**Issue by swnathan** [SeleniumHQ/selenium#5285]
Getting Below Exception when Invoking Firefox Browser when running in Grid.

In Local it is working fine

net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Unable to find a matching set of capabilities)

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also, version 3.4 is outdated, please make sure you can reproduce the issue on the latest version (3.8.1 at the moment)

**Comment by barancev** [comment]
Closing the issue, there is no reproduction scenario provided.
