### ISSUE TITLE
Typos in the wiki logging page

### ISSUE THREAD

**Issue by matthewhively** [SeleniumHQ/selenium#5289]
There are a lot of typos in the wiki page for logging:
https://github.com/SeleniumHQ/selenium/wiki/Logging
I would fix them myself, but there is no edit button.

Most of them are simple word problems
Example:
`more of less`
instead of
`more or less`

The most glaring though is the links to the JsonWireProtocol link to
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol.md
--redirect--> https://raw.githubusercontent.com/wiki/SeleniumHQ/selenium/JsonWireProtocol.md
instead of 
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

**Comment by lmtierney** [comment]
This has been updated
