### ISSUE TITLE
Pressing Enter key opens a new tab but don't recognize elements in the new tab opened

### ISSUE THREAD

**Issue by fonsecba** [SeleniumHQ/selenium#529]
Hi guys,
I'm working on Selenium IDE. I just created a script that click on a link by using the command sendKeys with value ${KEY_ENTER} so the goal is simulate that user presses Enter key. The action opens the new tab as expected but Selenium IDE is not recognizing any elements in the new tab opened and the test cannot continue working.
So it is working well when use click command but for our proposal I need to test using senKeys  ${KEY_ENTER} 

Thanks,

**Comment by barancev** [comment]
Selenium does not support tabs. Configure the browser to use windows instead of tabs.
