### ISSUE TITLE
OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost/

### ISSUE THREAD

**Issue by java123code** [SeleniumHQ/selenium#5293]
1. resources I used : C# , Selenium , VS 2017, Jenkins , VM machine (windows 10) , Nunit v3.9, geckoDrive v19, firefox v56/57 

    2. I can execute firefox / chrome browser cases on local machine 

    3. I can execute chrome browser cases on VM machine 

    4. Issue : **I can Not execute firefox cases on VM machine and its throwing below error.** 

Error Message
OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost:49463/
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

Stacktrace at OpenQA.Selenium.DriverService.Start() at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(String geckoDriverDirectory, FirefoxOptions options, TimeSpan commandTimeout) at MPAutomation.Driver.Initialize(String browser) in 

D:\Workspace.Automation\MPproject\MPAutomation\Utility\Driver.cs:line 79 # code on this line : Instance = new FirefoxDriver(service.FirefoxBinaryPath, options, TimeSpan.FromSeconds(10));
at MPAutomation.BaseTest.Init() in 

D:\Workspace.Automation\MPproject\MPAutomation\Utils\BaseTest.cs:line 54 #code here : LoginPage.GoTo(Settings.BrowserType); # I am passing "Firefox" 

--TearDown at MPAutomation.Driver.Close() in 

D:\Workspace.Automation\MPproject\MPAutomation\Utility\Driver.cs:line 117 # Instance.Close(); at MPAutomation.BaseTest.Cleanup() in D:\Workspace.Automation\MPproject\MPAutomation\Utils\BaseTest.cs:line 97

---------------------------------------------------------------------  
  **firefox implemnetation looks like this in Driver.cs**
       else if(browser.Equals(Constant.Firefox))
                    {
// driver init from here 
                        FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(DrivePath);
                        service.FirefoxBinaryPath = DrivePath;
                        var profile = new FirefoxProfile();
                        profile.AcceptUntrustedCertificates = true;
                        var options = new FirefoxOptions();
                        options.AcceptInsecureCertificates = true;
                        options.Profile = profile;                
                        Instance = new FirefoxDriver(service.FirefoxBinaryPath, options, TimeSpan.FromSeconds(10));
                        Instance.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

                        Utility.Logger.Write("***** Firefox Browser has been initialized now  *********");

                    }

           --------------------------------
    5. We have one certificate for firefox and which has already been taken care locally and on VM 

    6. I am not sure why automation is not able to start firefox on VM  

-----------------------
Yes, I followed below links before posting this issue

https://github.com/mozilla/geckodriver/issues/372
https://github.com/SeleniumHQ/selenium/issues/3195

**Comment by jimevans** [comment]
This issue, as reported, is not an issue; the reporter is using the wrong values in the `FirefoxDriver` constructor. What the user wants is the following:

    Instance = new FirefoxDriver(service, options, TimeSpan.FromSeconds(10));

The string overload expects the path to the `geckodriver` executable, not the path to the Firefox browser (which is what is actually being passed). Since the user has already created a `FirefoxDriverService` object, that is what should be used. Finally, a 10-second timeout for HTTP communication is incredibly short. I would recommend something longer (the default is 60 seconds).
