### ISSUE TITLE
Cannot perform build without python

### ISSUE THREAD

**Issue by anikulin** [SeleniumHQ/selenium#5297]
## Meta -
OS:   Windows 10
Selenium Version:  3.8.1
Java: JDK 1.8.0_121

## Expected Behavior -
According to README.md, the only necessary requirement for building Selenium is JDK, while python is optional. So it should be possible to build selenium on the system having JDK only.

## Actual Behavior -
In fact, running the build on such system fails with "No such file or directory - python" error.

## Steps to reproduce -
1. Checkout selenium source code
2. Run the build:
`go selenium-java`

-> build fails with the error:
```
C:\git\selenium>go selenium-java
Downloading buck build tool, it can take up to several minutes...
python C:/git/selenium/buck-out/crazy-fun/be2bf932342e5d67f58c9b26f5065c745d285d0d/buck.pex kill
go aborted!
Command failed with status (127): [python C:/git/selenium/buck-out/crazy-fu...]
C:/git/seleniumHQ/rake-tasks/buck.rb:50:in `download'
C:/git/seleniumHQ/rake-tasks/buck.rb:57:in `buck_cmd'
C:/git/seleniumHQ/rake-tasks/buck.rb:257:in `block in (root)'
Errno::ENOENT: No such file or directory - python
C:/git/seleniumHQ/rake-tasks/buck.rb:50:in `download'
C:/git/seleniumHQ/rake-tasks/buck.rb:57:in `buck_cmd'
C:/git/seleniumHQ/rake-tasks/buck.rb:257:in `block in (root)'
Tasks: TOP => selenium-java => //java/client/src/org/openqa/selenium:selenium
(See full trace by running task with --trace)
```

Possible solution could be to include the python in the list of build requirements, or make sure it's acquired during the buck download.

**Comment by anikulin** [comment]
also it would be nice to note that build is not python 3 compatible ([SeleniumHQ/selenium#5252](https://github.com/SeleniumHQ/selenium/issues/5252))

**Comment by barancev** [comment]
README fixed, thank you!
