### ISSUE TITLE
`ChromeOptions.setProxy` not properly set proxy

### ISSUE THREAD

**Issue by Hronom** [SeleniumHQ/selenium#5299]
## Meta -
OS:  Xubuntu 17.10

Selenium Version:  3.7.1

Browser:  Chrome

## Expected Behavior -
Created selenium proxy was set:
```
org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
proxy.setSocksProxy(proxyPojo.ip + ":" + proxyPojo.port);
proxy.setSocksVersion(5);
return proxy;
```

## Actual Behavior -
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: cannot parse capability: proxy from unknown error: proxyType is 'manual' but no manual proxy capabilities were found

## Solution that helps -
https://stackoverflow.com/a/28891213/285571
```
ChromeOptions options = new ChromeOptions();
options.addArguments("--proxy-server=socks5://" + host + ":" + port);
WebDriver driver = new ChromeDriver(options);
```

Please can you fix converting of selenium proxy object to appropriate Chrome Driver argument string.

**Comment by fabianhick** [comment]
I encountered another issue when setting the socks version on the Proxy object:
`Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')`

**Comment by diemol** [comment]
For a socks proxy, the proxy type needs to be set to manual, as the spec [says](https://www.w3.org/TR/webdriver1/#proxy). If you need any help with that, please use the support [channels](https://www.selenium.dev/support/).

**Comment by fabianhick** [comment]
@diemol: Would you mind an implemented wrapper which would perform the manual configuration in the background?
This way the chromium driver would be easily replaceable with gecko and usability would improve greatly.

**Comment by diemol** [comment]
@fabianhick I think it does not make sense to implement a wrapper for a manual configuration, the idea of it is to allow the user do what they need, and putting a wrapper around it will potentially hinder their options. Plus, it will be harder to maintain.
