### ISSUE TITLE
isDisplayed returning true for CSS visibility: collapse

### ISSUE THREAD

**Issue by sophosis** [SeleniumHQ/selenium#530]
Firefox 35
Selenium 2.44.0
Geb 0.10.0

I had a case where I tried to use `isDisplayed()` on an element that was being shown and removed from view by setting CSS `visibility` to `collapse`. However, `isDisplayed()` returned true when the element was set to `visiblity: collapse`.

I've included a HTML sample that illustrates the use of `collapse`.

The test sample comes from my use of Geb, but I assign a WebElement to a variable and use `isDisplayed()` on it, for this report's purpose.

<br>
HTML
```
<html>
<body>
<div id='first'>
this is visible
 <div id='secret' style='visibility: visible'>
    this might be visible
 </div>
</div>

<script>
document.getElementById('first').onclick = function() {
    var secret = document.getElementById('secret')
   
    if (secret.style.visibility == 'collapse') secret.style.visibility = 'visible';
    else secret.style.visibility = 'collapse';
};
</script>
</body>
</html>
```

<br>
Test
```
// Element is visible
def webDriverElement = $('#secret').firstElement()
assert webDriverElement.isDisplayed()

$('#first').click()

// Element should not be visible
webDriverElement = $('#secret').firstElement()
assert webDriverElement.isDisplayed() == false
```
```
Condition not satisfied:

webDriverElement.isDisplayed() == false
|                |             |
|                true          false
[[[[FirefoxDriver: firefox on WINDOWS (dea1ad94-9a87-48b0-bd5f-c8ebba6407c6)] -> tag name: html]] -> css selector: #secret]

	at Test.test(Test.groovy:18)

```

**Comment by jleyba** [comment]
Thanks for the bug report and repo case. There are no collapse visibility checks (oversight on our part):

https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/dom.js#L600
