### ISSUE TITLE
Unable to locate element in iframe after switch to iframe 

### ISSUE THREAD

**Issue by mshemadarshini** [SeleniumHQ/selenium#5300]
Able to detect the iframe and switch to it succesfully. But when I try to locate the element using driver.find_element_by_id('X78') its not successful. 

I'm trying to do 2 item : 
a) To detect element of text field and input text into the field
b) To detect a radio button and select the option

But its failing to detect the id now and i cant go to next step to either send keys for text field or click the radio button. 

There's javascript also involve in the code. Screenshot of the code per below.

This issue has also being shared in stakeoverflow.
https://stackoverflow.com/questions/48088420/python-selenium-iframe-dynamically-change-id-and-name-but-src-is-same

![Uploading Capture.PNG…]()

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
