### ISSUE TITLE
Download site zip file is broken

### ISSUE THREAD

**Issue by NozomiIto** [SeleniumHQ/selenium#5305]
## Meta -
Browser:  Chrome
Browser Version:  63.0.3239.84 (Official Build) (64-bit)

## Expected Behavior -

When I visit http://www.seleniumhq.org/download/ and download Java Client from `Selenium Client & WebDriver Language Bindings` section, downloaded selenium-java-3.8.1.zip is just 8.2MB and libs directory in the unzipped dir is broken.

<img width="247" alt="screen shot 2018-01-09 at 8 09 50" src="https://user-images.githubusercontent.com/4276719/34697034-8cf73cc4-f514-11e7-81c3-13760fa3920d.png">

## Actual Behavior -

libs dir should contain all dependent jar files.

**Comment by barancev** [comment]
The size is correct. I've just downloaded the file and verified it, the archive is valild, 'lib' subdir contains 8 jar files.

**Comment by NozomiIto** [comment]
Thanks. I've found the reason why libs dir contents was not displayed to me was that libs dir did not have read permission on Mac PC.
My friend also said to me he could not open libs dir, so I'm afraid it is not my unzip process problem.

**Comment by barancev** [comment]
This complain makes sense, we'll check permissions, reopening the issue.

**Comment by barancev** [comment]
It seems to be a build tool (buck) issue that screws file and dir permissions in zip file on Windows.

**Comment by pathakrakhi** [comment]
hello i downloaded selenium from http://www.seleniumhq.org/download/ downloaded selenium-java-3.8.1.zip is just 7.96 MB and libs directory contains 8 files and there is no Jna-package files...please suggest

**Comment by barancev** [comment]
@pathakrakhi Selenium Java binding does not depend on JNA anymore.

**Comment by pathakrakhi** [comment]
oh ,thank you so much

**Comment by barancev** [comment]
Depends on https://github.com/facebook/buck/issues/1790

**Comment by barancev** [comment]
Actually depends on https://github.com/facebook/buck/issues/1724

**Comment by barancev** [comment]
We've migrated from buck to bazel, so this issue is not actual anymore.
