### ISSUE TITLE
org.openqa.selenium.remote.SessionNotFoundException is missing from the documentation of Exception Summary and WebDriverException Class

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5308]
## Meta - **`org.openqa.selenium.remote.SessionNotFoundException`** is missing from the documentation of **`Exception Summary`** in [**`Package org.openqa.selenium`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/package-summary.html) page and [**`WebDriverException Class`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriverException.html)

OS:  All
Selenium Version:  3.8.1
Browser:  All

Browser Version:  All

## Steps to reproduce -
[**`Package org.openqa.selenium`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/package-summary.html) 

[**`WebDriverException Class`**](http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriverException.html)

**Comment by barancev** [comment]
There is no SessionNotFoundException in the current Selenium code.
