### ISSUE TITLE
[node.js] "Execute" event

### ISSUE THREAD

**Issue by jugglinmike** [SeleniumHQ/selenium#5311]
I'm writing some integration tests, and my test runner has a feature where it
can force tests to fail after some delay. Some tests describe longer
interactions than others, and I can support this by setting the duration for
each test individually.

However, this is not ideal because if the first command of some long-running
test times out, the test runner will not recognize this until the extended
duration has passed.

What I would like to do is increase the duration with every WebDriver command
execution. This would obviate the need to maintain timeout values in proportion
to the complexity of the test--the value would automatically expand as tests
progressed. It would also make detecting timeouts more efficient generally
(since the expected value would only be increased immediately prior to each
operation).

Since the `Executor#execute` method is part of the public API, I could attempt
to do this today by overwriting that method. However, although the method is
public, the contract I'd be relying on (i.e. "this method is invoked by the
WebDriver internals for each command executed") is not. So I'm requesting an
explicit API to support my use case.

In the interest of being more constructive, I would suggest the Event Emitter
pattern exposed either on the WebDriver instance of the Executor instance. In
that case, usage would look something like the following:

```js
webdriver.getExecutor().on('execute', () => {
  this.timeout(this.timeout() + 1000);
});
```

But I'm not too concerned with the API itself--if the maintainers agree that
the use case is warranted, I'd be happy with any implementation.

I recognize that the WebDriver module supports timeout functionality itself,
but I cannot rely on that completely--my tests perform other asynchronous
operations that may time out. This functionality would allow me to maintain an
appropriate value within the test runner.

Thanks for the great work!

**Comment by jleyba** [comment]
The command executor is meant to be a generic interface so that you can inject your own - it's just not very convenient to do so right now (you can't use the Builder and have to manually create your desired driver instance).

I think an appropriate change would be to have something like:

```js
new Builder()
    .forBrowser('firefox')
    // Function takes the default executor that would be used for the
    // new session and returns a modified one. You can modify it or
    // return a custom one: as long as the return value is an object with
    // an `execute` method.
    .customCommandExecutor(function(exe) {
      return {
        execute(command) {
          console.log(`execute ${command.getName()}`);
          return exe.execute(command);
        }
      };
   })
  .build();
```

**Comment by jleyba** [comment]
Your timeout case would be something like:

```js
function limitCommands(exe) {
  return {
    execute(command) {
      return new Promise((resolve, reject) => {
        setTimeout(() => reject(Error('command timed out')), timeout);
        resolve(exe.execute(command));
      });
    }
  };
}
```

The catch is this only works with stopping the command on the client. There's no guarantee the
remote end will execute another command if one is already in progress (e.g. it's blocked waiting on
a navigation event to complete). The appropriate thing to do for those cases is to adjust the
[session timeouts](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_Options.html#setTimeouts).

**Comment by jugglinmike** [comment]
Thanks for the input! My explanation was a little confusing, so your example
script doesn't quite match the use case I had in mind. I think the API you are
proposing would still suite my needs, though. Here's a different application of
your design as it might appear in a [Mocha](https://mochajs.org/)-powered test
suite:

```js
setup(function() {
  // Set a "base" timeout of 0.5 seconds to account for delays that occur in
  // the process of reacting to Promise resolutions.
  this.timeout(500);

  const builder =new Builder()
    .forBrowser('firefox');

  // Extend the test timeout before every WebDriver command so that the
  // accepted duration of each test implicitly scales with the number of
  // commands that it issues.
  const extendTimeout = (exe) => {
    return {
      execute: (command) => {
        this.timeout(this.timeout() + 1000);

        return exe.execute(command);
      }
    };
  };

  builder.customCommandExecutor(() => ({ execute }));

  this.driver = builder.build();
});

// ...

test('a WebDriver-powered acceptance test', async function() {
  await this.driver.get('http://zombo.com');

  // any number of additional WebDriver commands
});
```

**Comment by diemol** [comment]
I went through the thread and there is no conclusion or next steps, the issue went stale. I will close this as we are doing an issue clean up.

If there is the need to work on this, please reach out through the [support channels](https://www.selenium.dev/support/) or create a feature request with a potential PR.
