### ISSUE TITLE
Optional support for XPath 2.0 in the Firefox driver

### ISSUE THREAD

**Issue by withrocks** [SeleniumHQ/selenium#5320]
Support for XPath is limited to 1.0 in Firefox, and since Selenium uses the browser's XPath support by default, it means that we are also limited to that version. According to the following ticket, support will not be added in the near future:

https://bugzilla.mozilla.org/show_bug.cgi?id=396966

This means that we can't use more powerful xpath queries, such as regular expression matches (https://www.w3.org/TR/xpath-functions-31/#func-matches).

I suggest adding optional support for XPath 2.0 by loading a javascript implementation at page load. Perhaps we could use this one: https://github.com/ilinsky/jquery-xpath

Google's javascript library https://github.com/google/wicked-good-xpath is already the default XPath library for IE according to: https://github.com/SeleniumHQ/selenium/blob/5577c15ba08ce36ee18177d737aef97ed06dbc77/cpp/iedriverserver/CHANGELOG#L1494

However, if I'm not mistaken, that library doesn't support xpath 2.0, but xpath 1.0 level 3.

I'm willing to implement this myself if you think the feature makes sense.

**Comment by barancev** [comment]
Please send this enhancement request to W3C WebDriver specification:
https://w3c.github.io/webdriver/webdriver-spec.html
