### ISSUE TITLE
unknown error: failed to wait for extension background page to load

### ISSUE THREAD

**Issue by pskh** [SeleniumHQ/selenium#5322]
## Meta -

OS: Windows 7 , ubuntu 14.04
Selenium Version:  3.8.1
Browser:  Chrome browser, Chrome Driver 2.34
Browser Version:  63.0.3239.132

## Expected Behavior -
trouble-free operation

## Actual Behavior -
Throw an exception as bellow:
ERROR: unknown error: failed to wait for extension background page to load: chrome-extension://iifchhfnnmpdbibifmljnfjhpififfog/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://iifchhfnnmpdbibifmljnfjhpififfog/_generated_background_page.html
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace
 information)
Command duration or timeout: 10.45 seconds

## Steps to reproduce -
Use CryptoPro Extension(https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog?hl=ru) for chrome browser and set headless mode in chrome options.

![screen](https://user-images.githubusercontent.com/19980865/34777950-ec19b042-f62c-11e7-9328-260d0ab32b66.png)

Will work fine without headless

**Comment by barancev** [comment]
Please report this issue to chromedriver, it's a driver internal failure.
