### ISSUE TITLE
Selenium 3.8 dotnet DLL's are not CLS-compliant

### ISSUE THREAD

**Issue by mellamojaja** [SeleniumHQ/selenium#5324]
## Meta -
OS:  Windows 10

Selenium Version:  3.8.0

Browser: 

Browser Version:  

## Actual Behavior (Issue)
The webdriver DLL's are not CLS-compliant, so any project that uses them and that wants to be CLS-compliant, shows hundreds of warnings like this: 

![image](https://user-images.githubusercontent.com/8699293/34814746-1a0720e8-f6af-11e7-8277-7c0e0ce18c2e.png)

The CLS-compliant attribute may be set at assembly level, and you may see it using [ILSpy.net](https://github.com/icsharpcode/ILSpy#ilspy-------) or any other assembly decompiler. For example, using ILSpy.net, the webdriver.dll file looks like this: 

![image](https://user-images.githubusercontent.com/8699293/34776758-2d76ee0c-f618-11e7-9e26-a6ae49d27b26.png)

## Expected Behavior -
The webdriver DLL's should be CLS-compliant, like they were was on version 3.4.0:

![image](https://user-images.githubusercontent.com/8699293/34814943-ce31bf9c-f6af-11e7-8850-72f6d2183cc4.png)

One possible solution could be this small modification in the "WebDriver" and "WebDriver.Support" projects of the Selenium .NET solution:

1. Create a folder called "Properties"
2. Create a file called "AssemblyInfo.cs" inside that folder with the following content: 

```
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: CLSCompliant(true)]
```

## Steps to reproduce -

1. Download the latest [Selenium code from GitHub](https://github.com/SeleniumHQ/selenium)
2. Open the .NET solution ("dotnet > WebDriver.NET.sln") in Visual Studio
3. Build all
4. Open [ILSpy.net](https://github.com/icsharpcode/ILSpy#ilspy-------) or any other assembly browser. Open webdriver.dll, located in "build" folder (for example, "build > cli > Debug > net45")
5. You WON'T see the following line: [assembly: CLSCompliant(true)], which meand the DLL is not CLS-compliant.

**Comment by jimevans** [comment]
Fixed in commit 98be3b3.
