### ISSUE TITLE
Copy paste not working using Robot Class: Ctrl+C; content is not saving into clipboard, but it used to work perfectly fine few days back

### ISSUE THREAD

**Issue by praveenreddygm** [SeleniumHQ/selenium#5327]
## Meta -
OS:  Windows 10
Selenium Version:  3.5.3; WebDriver
Browser:  NA; Trying to copy text from outlook/Any file using Robot class and its features; Basically we can open outlook using Sikuli or Winnium; here problem is about Robot class and its features that "Using Robot class i have copied content during run time BCDE and trying to retrieve it from clipboard to print again in console or any other file. But it's fetching old value from the clip board? but it used to work perfectly fine few days back.
Expected Output is: BCDE"

import java.awt.AWTException;
import java.awt.HeadlessException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;

import org.sikuli.basics.Settings;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Key;
import org.sikuli.script.Pattern;
import org.sikuli.script.Screen;

public class Sikuli_Demo {

public static void main(String[] args) throws InterruptedException, FindFailed, AWTException, HeadlessException, UnsupportedFlavorException, IOException {

	Screen screen=new Screen();
	Thread.sleep(2000);
	Pattern clickOutlook=new Pattern("images\\1_ClickOutlook.png");

	Pattern clickNewMail=new Pattern("images\\3_NewMail.png");

	screen.click(clickOutlook);
	Thread.sleep(2000);
	screen.click(clickNewMail);
	Thread.sleep(2000);
	screen.type("ABCDE");
	screen.type(Key.LEFT+Key.LEFT+Key.LEFT+Key.LEFT);
	Thread.sleep(2000);

	Robot robot=new Robot();
	Thread.sleep(4000);
	
	robot.keyPress(KeyEvent.VK_SHIFT);
	robot.keyPress(KeyEvent.VK_RIGHT);
	robot.keyPress(KeyEvent.VK_SHIFT);
	robot.keyPress(KeyEvent.VK_RIGHT);
	robot.keyPress(KeyEvent.VK_SHIFT);
	robot.keyPress(KeyEvent.VK_RIGHT);
	robot.keyPress(KeyEvent.VK_SHIFT);
	robot.keyPress(KeyEvent.VK_RIGHT);

	Thread.sleep(2000);
	robot.keyRelease(KeyEvent.VK_RIGHT);
	robot.keyRelease(KeyEvent.VK_SHIFT);
	Thread.sleep(2000);
	System.out.println("Check1");
	robot.keyPress(KeyEvent.VK_CONTROL);
	robot.keyPress(KeyEvent.VK_C);
	Thread.sleep(2000);
	robot.keyRelease(KeyEvent.VK_CONTROL);
	robot.keyRelease(KeyEvent.VK_C);
	Thread.sleep(2000);
	robot.keyPress(KeyEvent.VK_RIGHT);
	robot.keyRelease(KeyEvent.VK_RIGHT);

	System.out.println("Check2");

	String str=(String)Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);
	Thread.sleep(2000);

	System.out.println("Copied content is :"+str);
	screen.type(str);
}
}

**Console:
![1_clickoutlook](https://user-images.githubusercontent.com/35334539/34831328-b2e564de-f70c-11e7-96f8-875491f9a97c.png)
![3_newmail](https://user-images.githubusercontent.com/35334539/34831329-b33de708-f70c-11e7-8e0f-c99c1aaa05a6.png)

** 
Basically i got below error first:
Jan 11, 2018 6:15:36 PM java.util.prefs.WindowsPreferences 
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[log] CLICK on L(540,1401)@s(0)[0,0 2560x1440]
[log] CLICK on L(58,214)@s(0)[0,0 2560x1440]
[log] TYPE "ABCDE"
[log] TYPE "#LEFT.#LEFT.#LEFT.#LEFT."
Check1
Check2
Exception in thread "main" java.awt.datatransfer.UnsupportedFlavorException: Unicode String
at sun.awt.datatransfer.SunClipboard.getData(Unknown Source)
at Sikuli_Demo.main(Sikuli_Demo.java:63)

But After following below steps error is not coming but clipboard is not saving the copied content during run time: https://stackoverflow.com/questions/8513740/copy-paste-not-working-in-a-signed-applet

On Windows 7, it can be found at C:\Program Files (x86)\Java\jre6\lib\security. Copy this file to your home folder (ex. C:\Users\Kyle). Rename the file to .java.policy (note the period at the beginning). Edit the file in a text editor. Locate this line of text:
Add the following line just below it like so:

// "standard" properies that can be read by anyone
permission java.awt.AWTPermission "accessClipboard";
Save the file. Close any open browsers and ensure that Java is not running before testing.

**Console after following above steps**:

Jan 11, 2018 5:41:31 PM java.util.prefs.WindowsPreferences 
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[log] CLICK on L(540,1401)@s(0)[0,0 2560x1440]
[log] CLICK on L(58,214)@s(0)[0,0 2560x1440]
[log] TYPE "ABCDE"
[log] TYPE "#LEFT.#LEFT.#LEFT.#LEFT."
Check1
Check2
Copied content is :praveenreddygm@gmail.com
[log] TYPE "praveenreddygm@gmail.com "

**Expected Output**: BCDE

**Comment by barancev** [comment]
Not related to Selenium.

**Comment by praveenreddygm** [comment]
May i know which is the right platform? Below statement is the issue, i believe its part of selenium-Robot (import java.awt.*)
String str=(String)Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);

Error: Exception in thread "main" java.awt.datatransfer.UnsupportedFlavorException: Unicode String
at sun.awt.datatransfer.SunClipboard.getData(Unknown Source)

**Comment by praveenreddygm** [comment]
I mean its copying text and not storing text into clipboard using robot class Key Events, but it used to working fine previously

robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyPress(KeyEvent.VK_SHIFT);
robot.keyPress(KeyEvent.VK_RIGHT);

Thread.sleep(2000);
robot.keyRelease(KeyEvent.VK_RIGHT);
robot.keyRelease(KeyEvent.VK_SHIFT);
Thread.sleep(2000);
robot.keyPress(KeyEvent.VK_CONTROL);
robot.keyPress(KeyEvent.VK_C);
Thread.sleep(2000);
robot.keyRelease(KeyEvent.VK_CONTROL);
robot.keyRelease(KeyEvent.VK_C);
Thread.sleep(2000);
robot.keyPress(KeyEvent.VK_RIGHT);
robot.keyRelease(KeyEvent.VK_RIGHT);

String str=(String)Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);

**Comment by lmtierney** [comment]
If you think there's an issue with selenium, offer a reproducible scenario using only selenium. Otherwise, I'm afraid it's impossible for us to debug. Please raise an issue with the library you are using first. If something "just changed" within the last couple of days, if anything it is probably a driver issue and not a selenium issue.

**Comment by barancev** [comment]
Java AWT Robot is a part of Java SDK, it's not a part of Selenium.

**Comment by praveenreddygm** [comment]
@barancev Could you please help me with exact link where i can raise this issue. I'm not able to find it out. Thanks in Advance !!

**Comment by barancev** [comment]
This is a question rather than an issue. Try to post it to https://stackoverflow.com/
