### ISSUE TITLE
Need new build of .net assemblies with Firefox performance fix 

### ISSUE THREAD

**Issue by tnelson-cb** [SeleniumHQ/selenium#533]
This is related to issue 8551

How do get new build of .net assemblies with Firefox performance fix?

The last build was 2-27-2015 or selenium 2.45.0 (Firefox runs 100% slower)
According to issue 8551 the developer site there has been a fix for the performance issue but a new release of the .net assemblies do not exist on NuGet.

my comments added to issue 8551
I think there has been a fix for the performance(slowness) issue with FF. However I use the .net assemblies and release 2.45.0 was build back on 2-27-2015 and does not contain the performance fix for Firefox. Can we get a new .net build 2.45.1 that contains the Firefox performance fix and get out on NuGet please.

**Comment by barancev** [comment]
"How to" is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
