### ISSUE TITLE
Python-Selenium-Eclipse-safari -connection refused error

### ISSUE THREAD

**Issue by deals4kr** [SeleniumHQ/selenium#5330]
## Meta -
OS:  OSX EL Capitan version 10.11.6
 
Selenium Version:   3.8.1

Browser:  Version 11.0.2 (11604.4.7.1.6)

Browser Version:  Version 11.0.2 (11604.4.7.1.6)

**Comment by deals4kr** [comment]
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
import urllib

browser = webdriver.Remote(desired_capabilities=webdriver.DesiredCapabilities.SAFARI)
#browser=webdriver.Safari()
browser.get('http://www.google.com')

**Comment by lmtierney** [comment]
What version of OS are you using?

**Comment by lmtierney** [comment]
And is your selenium server running on the default ip/port?

**Comment by deals4kr** [comment]
I do not know how to verify which port it is running. Please let me know
how can i verify this?

**Comment by lmtierney** [comment]
Well the first question I should ask since you're new is, are you running `selenium-server-standalone` at all? Do you need to? Can you just run locally with:

```
from selenium.webdriver import Safari
driver = Safari()
```

**Comment by lmtierney** [comment]
You would know the ip and port when you started up the server, it should say in the console

**Comment by deals4kr** [comment]
i downloaded selenium stand alone server (selenium-server-standalone-3.8.1.jar) and added to external library in eclipse
After executing above code i still get connection refused error.
`from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
import urllib

# browser = webdriver.Remote(desired_capabilities=webdriver.DesiredCapabilities.SAFARI)
# #browser=webdriver.Safari()
# browser.get('http://www.google.com')

from selenium.webdriver import Safari
driver = Safari()`

---------
Traceback (most recent call last):
  File "/Users/JyothiKondaReddy/Documents/workspace/PySelenium/pySelPack/pymodule.py", line 15, in <module>
    driver = Safari()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/safari/webdriver.py", line 47, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/safaridriver unexpectedly exited. Status code was: 1

**Comment by lmtierney** [comment]
selenium-server-standalone-3.8.1.jar isn't needed if you're running locally. I have a feeling the `safaridriver` on el capitan is well behind. Right now we suggest users use Safari Technology Preview as that is the latest and greatest. Keep in mind safaridriver is still under development and is not a complete product.

I am unable to reproduce this issue with the latest Safari and Sierra. As this seems more of a question rather than an issue, please ask any further questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). There will be more people able to help you there.

**Comment by lmtierney** [comment]
Also make sure to `Enable Remote Automation in the Develop menu. This is toggled via Develop > Allow Remote Automation in the menu bar.` as outlined in https://webkit.org/blog/6900/webdriver-support-in-safari-10/

**Comment by deals4kr** [comment]
Hi Team,
Please help me to get through this error: Even with firefox also i am getting below error.

Code:
```
from selenium import webdriver

from selenium.webdriver.common.keys import Keys

browser = webdriver.Firefox()
```

browser.get('http://www.yahoo.com')

assert 'Yahoo' in browser.title


Error: 
```
Traceback (most recent call last):


  File "/Users/JyothiKondaReddy/Documents/workspace/PySelenium/pySelPack/Login.py", line 45, in <module>


    browser = webdriver.Firefox()


  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__


    self.service.start()


  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start


    os.path.basename(self.path), self.start_error_message)


selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```


Even though i copied geckdriver to /usr/local/bin,  I still see geckodriver needs to be in PATH.

Please advice.

**Comment by cgoldberg** [comment]
> Even though i copied geckdriver to /usr/local/bin

did you also make it executable?

`$ chmod +x /usr/local/bin/geckodriver`

**Comment by deals4kr** [comment]
Yes, I did that earlier.

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
