### ISSUE TITLE
Element available for interacting even if it's hidden by {overflow: hidden}

### ISSUE THREAD

**Issue by GeyseR** [SeleniumHQ/selenium#5331]
Hi!

I'm not sure is current behavior expected or not, so I decided to file a ticket for selenium dev team. For some reason locating and interacting with an invisible element on the page is working for me. The element is presented in DOM but it's hidden by parent's `{overflow: hidden}` css. 

## Meta -
OS: 
Ubuntu 
Selenium Version:  
3.8.1
Browser:  
Chrome
Browser Version:  
63.0.3239.84

## Expected Behavior - 
id_displayed returns False and element is not clickable
## Actual Behavior -
id_displayed returns True and element is not clickable
## Steps to reproduce -
html/styles: https://jsfiddle.net/ck6utghr/
```python
browser = webdriver.Remote(url, capabilities)
browser.get('test.html')
wait = WebDriverWait(browser, timeout=20)
wait.until(
    EC.visibility_of_element_located((By.CSS_SELECTOR, '.target-link')),
)
link = browser.find_element_by_css_selector('.target-link')
link.click()
```

**Comment by p0deje** [comment]
I'm not an expert in CSS so I don't really know how overflow should be handled in all the cases. I see that there is quite a lot of logic around handling overflow state when checking for element visibility:

https://github.com/SeleniumHQ/selenium/blob/b3cda3214e47152818b6c56b25afa4573c4fd3bb/javascript/atoms/dom.js#L520-L528

Still, this particular case looks like a bug in atoms that we haven't encountered yet. I don't think I can fix it, so it would be great if somebody with a better understanding could have a look (cc @barancev @AutomatedTester).
