### ISSUE TITLE
Selenium Grid - Firefox - UnknownCommandError: POST /session/{sessionId}/moveto did not match a known command

### ISSUE THREAD

**Issue by sahil1610** [SeleniumHQ/selenium#5332]
## Meta -
OS:  OSX

Selenium Grid Version:  3.8.1

Browser:  Firefox

Browser Version:  57.0.4

## Actual Behavior - Actions class function are not working

# _**This issue is specific to selenium grid only**_

## Steps to reproduce -
Run the following protractor script in FIREFOX browser: 

`describe('Test', function () {
 'use strict';
  it('Firefox Actions class', function () {
        browser.get('http://www.protractortest.org/#/');
        browser.actions().mouseMove(element(by.css('.github-button'))).perform();
        browser.sleep(10000);
    });
})`

_**Note that the same works on Selenium grid 3.2.0**_

**Comment by lmtierney** [comment]
This is an issue with protractor, please file an issue there.

**Comment by jleyba** [comment]
Partly an issue with protractor, the new actions API hasn't been published for the JS bindings (see #4564)

I'll be publishing a release in the next few days. Not sure when protractor will adopt it though.

**Comment by jleyba** [comment]
FYI, `selenium-webdriver@4.0.0-alpha.1` has been published to npm

**Comment by sahil1610** [comment]
@jleyba Sorry about asking a lame question but I am sort of confused here. The issue was only for selenium grid which I was setting up using Docker.

When I start selenium server using webdriver-manager start, the tests worked as expected.

So how this all will fix the issue? Protractor will publish a new update here? Or selenium will publish a new update.

**Comment by sahil1610** [comment]
@jleyba this is to fixed by protractor?

**Comment by dsamburskyi** [comment]
@lmtierney @sahil1610 I'm sorry for bringing up the question again, but why is this Protractor issue if this works with standalone Firefox (locally and Docker image from SeleniumHQ) and fails only on Selenium Grid (Docker)? All are running same versions of selenium 3.14.0, geckodriver 0.21.0 and Detected dialect: W3C.
I can provide more info if needed.
I'd appreciate if anyone can provide me technical detail to understand this :)

**Comment by lmtierney** [comment]
@dsamburskyi If you have a reproducible scenario using selenium code, please open a new issue with the information.

**Comment by rkrisztian** [comment]
@dsamburskyi , see https://github.com/angular/protractor/issues/4687#issuecomment-472488592 where I answer your question. In short, it's a bug in Protractor.
