### ISSUE TITLE
how  can i start selenium webdriver in chrome browser

### ISSUE THREAD

**Issue by thajunnisa** [SeleniumHQ/selenium#5333]
the below  error occur when i run script
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1515584193809,"updateDate":1515584193809,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1515750041681	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1515750041682	DeferredSave.extensions.json	DEBUG	Save changes
1515750041683	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1515750041683	addons.xpi-utils	DEBUG	Updating add-on states
1515750041684	addons.xpi-utils	DEBUG	Writing add-ons list
1515750041688	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1515750041689	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1515750041690	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1515750041691	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1515750041713	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1515750041713	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1515750041717	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1515750041717	addons.manager	DEBUG	Provider finished startup: XPIProvider
1515750041717	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1515750041718	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Starting provider: GMPProvider
1515750041725	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1515750041726	addons.manager	DEBUG	Provider finished startup: GMPProvider
1515750041726	addons.manager	DEBUG	Starting provider: PluginProvider
1515750041726	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1515750041726	addons.manager	DEBUG	Provider finished startup: PluginProvider
1515750041727	addons.manager	DEBUG	Completed startup sequence
1515750043266	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1515750043266	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1515750043267	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1515750043878	DeferredSave.extensions.json	DEBUG	Write succeeded
1515750043879	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1515750043879	DeferredSave.extensions.json	DEBUG	Starting timer
1515750043906	DeferredSave.extensions.json	DEBUG	Starting write
1515750043915	addons.repository	DEBUG	No addons.json found.
1515750043916	DeferredSave.addons.json	DEBUG	Save changes
1515750043929	DeferredSave.addons.json	DEBUG	Starting timer
1515750044051	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1515750044052	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1515750044052	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1515750044061	DeferredSave.addons.json	DEBUG	Starting write
1515750044077	DeferredSave.extensions.json	DEBUG	Write succeeded
1515750044151	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at test.Test.main(Test.java:10)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1515584193809,"updateDate":1515584193809,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1515750041681	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1515750041682	DeferredSave.extensions.json	DEBUG	Save changes
1515750041683	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1515750041683	addons.xpi-utils	DEBUG	Updating add-on states
1515750041684	addons.xpi-utils	DEBUG	Writing add-ons list
1515750041688	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1515750041689	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1515750041690	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1515750041691	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1515750041713	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1515750041713	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1515750041717	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1515750041717	addons.manager	DEBUG	Provider finished startup: XPIProvider
1515750041717	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1515750041718	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Starting provider: GMPProvider
1515750041725	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1515750041726	addons.manager	DEBUG	Provider finished startup: GMPProvider
1515750041726	addons.manager	DEBUG	Starting provider: PluginProvider
1515750041726	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1515750041726	addons.manager	DEBUG	Provider finished startup: PluginProvider
1515750041727	addons.manager	DEBUG	Completed startup sequence
1515750043266	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1515750043266	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1515750043267	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1515750043878	DeferredSave.extensions.json	DEBUG	Write succeeded
1515750043879	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1515750043879	DeferredSave.extensions.json	DEBUG	Starting timer
1515750043906	DeferredSave.extensions.json	DEBUG	Starting write
1515750043915	addons.repository	DEBUG	No addons.json found.
1515750043916	DeferredSave.addons.json	DEBUG	Save changes
1515750043929	DeferredSave.addons.json	DEBUG	Starting timer
1515750044051	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1515750044052	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1515750044052	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1515750044061	DeferredSave.addons.json	DEBUG	Starting write
1515750044077	DeferredSave.extensions.json	DEBUG	Write succeeded
1515750044151	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'hp-PC', ip: '192.168.43.54', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_151'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at test.Test.main(Test.java:10)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1515584193809,"updateDate":1515584193809,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1515750041681	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1515750041682	DeferredSave.extensions.json	DEBUG	Save changes
1515750041683	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1515750041683	addons.xpi-utils	DEBUG	Updating add-on states
1515750041684	addons.xpi-utils	DEBUG	Writing add-ons list
1515750041688	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1515750041689	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1515750041689	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1515750041690	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1515750041691	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1515750041713	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1515750041713	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1515750041717	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1515750041717	addons.manager	DEBUG	Provider finished startup: XPIProvider
1515750041717	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1515750041718	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1515750041718	addons.manager	DEBUG	Starting provider: GMPProvider

**Comment by schmidtkp** [comment]
@thajunnisa You description says "chrome" but you error says "firefox". What are you wanting to really do here?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
