### ISSUE TITLE
JsonWireProtocol - `moveto` does not move the mouse pointer to the correct coordinates in Firefox

### ISSUE THREAD

**Issue by aquilax** [SeleniumHQ/selenium#5334]
## Meta -
OS:  Windows 10
Selenium Version:  selenium-server-standalone-3.8.1.jar
Browser:  Firefox 
Browser Version: 57.0.4 (64-bit)  / geckodriver 0.19.1 

## Expected Behavior -
`/session/{SESSION_ID}/moveto` to move the mouse pointer to the x/y coordinates relative to the upper-left corner of the element

## Actual Behavior -
The mouse pointer is moved to coordinates relative to the center of the element,

## Steps to reproduce -
`/session/{SESSION_ID}/moveto`
```
{"element":"898e9e6c-eddf-4d9a-ab3d-5ec383b3f945","xoffset":629,"yoffset":636}
```

For geckodriver this translates to:
```
{
	"actions": [{
		"id": "mouse",
		"type": "pointer",
		"parameters": {
			"pointerType": "mouse"
		},
		"actions": [{
			"duration": 200,
			"x": 629,
			"y": 636,
			"type": "pointerMove",
			"origin": {
				"ELEMENT": "8694b33d-5c4c-4a2e-94c9-8b513e35c3c5",
				"element-6066-11e4-a52e-4f735466cecf": "8694b33d-5c4c-4a2e-94c9-8b513e35c3c5"
			}
		}]
	}]
}
```
Defined in the [webdriver specification](https://www.w3.org/TR/webdriver/#dfn-dispatch-a-pointermove-action)

**Comment by lmtierney** [comment]
I'm confused what you're asking. The spec which you linked specifically says that it should be from the center point of the element?

```
Let x element and y element be the result of calculating the in-view center point of element.

Let x equal x element + x offset, and y equal y element + y offset.

**Comment by aquilax** [comment]
@lmtierney That is correct. The issue is that I am calling Selenium's `/moveto` [method](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto), which is supposed to use top-left corner for the offsets.

**Comment by lmtierney** [comment]
I guess I'm still confused. If you're using Firefox `57.0.4 (64-bit) / geckodriver 0.19.1` you shouldn't be using `/moveto` at all as it's not in the w3c spec

**Comment by lmtierney** [comment]
The previous `/moveto` command which is JSS/OSS protocol, non-w3c did in fact start from the `0, 0` point of the element.

**Comment by jleyba** [comment]
Is this a problem of sending a `/moveto` command to the Selenium server and it is not properly translating it to a new actions command for Firefox?

For the JS bindings, I recently added the reverse - translating W3C to legacy by first injecting an [`executeScript`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/input.js#L1175) call to [translate the offsets](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/input.js#L1144) (see 2e913973d5171a9aa3c7697733c521bcae5fff4c)

**Comment by lmtierney** [comment]
@jleyba this was an issue before (#3693) and the solution was `passThrough` mode. So the user is expected to send the correct command for the protocol they expect. I do believe there is a shim for `/moveto` to translate it to `w3c` currently, but yes as @aquilax describes it doesn't have the exact desired outcome (since w3c is from the center point of the element). In this scenario, since we are talking to geckodriver, if the server wasn't there they would receive the `UnsupportedCommand` error. So the user should be using the `/actions` endpoint instead.

**Comment by aquilax** [comment]
Yes the issue is the one, that @jleyba describes. 
I think receiving `UnsupportedCommand` command in this case would be less misleading since the current solution does not adhere to the `/moveto` documentation.
Another option could be to implement the command properly using `/actions` and element's size.

**Comment by lmtierney** [comment]
I'll leave it up to the java folks on what they want to do @barancev @shs96c

**Comment by shinxi** [comment]
Just want to add, now the `moveTo` can't work well with the latest ChromeDriver, facing the same issue like in the Firefox. 

OS: MacOS/Windows
Selenium selenium-server-standalone-3.141.5.jar 
Browser: Chrome 
Browser Version: 76.0.3809.100 (64-bit) / ChromeDriver 76.0.3809.68

**Comment by diemol** [comment]
Is this still an issue?
[Here](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/client/src/org/openqa/selenium/remote/http/W3CHttpCommandCodec.java#L295) is how Grid translates the command to actions.

**Comment by diemol** [comment]
Closing as the issue went stale.
