### ISSUE TITLE
Add C# Bindings for Chrome Network Emulation

### ISSUE THREAD

**Issue by jakedurand** [SeleniumHQ/selenium#5338]
Functionality was added to ChromeDriver in March of 2015
https://chromium.googlesource.com/chromium/src.git/+/12a55ff7369b35adb29cd28f5e3dd4ef923e3e6c

This has been added for Python and Javascript
https://github.com/SeleniumHQ/selenium/pull/4011
https://github.com/SeleniumHQ/selenium/pull/3624

Open PR and issue for Java
https://github.com/SeleniumHQ/selenium/issues/3450
https://github.com/SeleniumHQ/selenium/pull/3479

Commit for Ruby
https://github.com/SeleniumHQ/selenium/commit/1103cb7e9e35e8bd22a5aea9b5455445baa6fb85

I'm new here, so I apologize in advance if I did something incorrect on creating this issue! I wouldn't mind trying my hand at this myself, but I'm brand new to the Selenium project and relatively new to code in general.

**Comment by jimevans** [comment]
Fixed in commit e2bc8ea
