### ISSUE TITLE
Documentation snippet for Javascript doesn't work

### ISSUE THREAD

**Issue by mercmobily** [SeleniumHQ/selenium#5339]
## Meta -
OS:  Ubuntu/GNU/Linux
Selenium Version:  
selenium-webdriver@4.0.0-alpha.1
Browser:  Chrome

I just wanted to let you know that the JAVASCRIPT snippet here: http://docs.seleniumhq.org/docs/03_webdriver.jsp

Which reads as follows:

    var driver = new webdriver.Builder().build();
    driver.get('http://www.google.com');

    var element = driver.findElement(webdriver.By.name('q'));
    element.sendKeys('Cheese!');
    element.submit();

    driver.getTitle().then(function(title) {
      console.log('Page title is: ' + title);
    });

    driver.wait(function() {
      return driver.getTitle().then(function(title) {
        return title.toLowerCase().lastIndexOf('cheese!', 0) === 0;
      });
    }, 3000);

    driver.getTitle().then(function(title) {
      console.log('Page title is: ' + title);
    });

    driver.quit();

Has a "number" of issues:

* `require` is missing
* `forBrowser()` is missing (so yes, even by adding the `require()`, it still doesn't work
* It doesn't use the MUCH more readable async/await feature of ES6 (and it really should)
* `driver.quit()` is not nested into a `then`, which means it might happen *before* things have finished

This is what the snippet could look like:

    const webdriver = require('selenium-webdriver');

    (async function () {
      try {
        var driver = new webdriver.Builder().forBrowser('chrome').build()
        await driver.get('http://www.google.com')

        var element = await driver.findElement(webdriver.By.name('q'))
        await element.sendKeys('Cheese!')
        await element.submit()

        var title = await driver.getTitle()
        console.log('Page title is: ' + title)
        await driver.quit()
      } catch (e) {
        console.log('Error', e)
      }
    })()

After writing all of this, I just realised that the snippet is https://www.npmjs.com/package/selenium-webdriver is very similar to mine.

**Comment by manoj9788** [comment]
@mercmobily We are aware, Please refer to the examples [here](https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver/example) and NPM page that you referred. We will be redesigning the whole SeleniumHQ website and also shall update the examples accordingly where necessary.

**Comment by mercmobily** [comment]
If there is already an issue which says "redo documentation and website", this should be marked as duplicate.

FWIW,I love the webdriver module in terms of code (really, nicely crafted) but documentation really is confusing and derailing. I have only used Selenium with Polymer before; so it was all pre-cooked and pre-packaged for me. Now that I need to write some very tricky integration tests using Selenium directly, I have to say it's a little difficult!

Keep up the good work though...

**Comment by diemol** [comment]
We have a new website with docs as well, this issue should be solved there https://www.selenium.dev/documentation/en/
