### ISSUE TITLE
ChromeDriver blocks after clicking browser Print Button 

### ISSUE THREAD

**Issue by LivClau** [SeleniumHQ/selenium#5342]
## Meta -
OS: Windows 10
Selenium Version:  3.8.1
Chrome Driver version: 2.35
Browser:  Chrome 63.0.3239.132

We have a page with a link for the window print: 

<html>
<header>
	<title>Test Print</title>
</header>
<body>
<h1>Test Print</h1>
<a id="printButton" href="javascript:window.print()">Print Page</a>
</body>
</html>

We have the following automation code: 
		ChromeOptions options = new ChromeOptions();
		options.addArguments("start-maximized");
		System.setProperty("webdriver.chrome.logfile", "D:\\chromedriver.log");
		System.setProperty("webdriver.chrome.verboseLogging", "true");
		WebDriver driver = new ChromeDriver(options);
		driver.get("http://localhost/testprint");
		System.out.println("Click the print button!");
		driver.findElement(By.id("printButton")).click();
		System.out.println("The Print Preview is displayed!");

When we run this code, it displays in the console : 

Starting ChromeDriver 2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73) on port 7430
Only local connections are allowed.
Jan 16, 2018 12:12:27 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Click the print button!

And remain in running for an indefinite period of time. 
I've attached the ChromeDriver log. 
[chromedriver.log](https://github.com/SeleniumHQ/selenium/files/1634557/chromedriver.log)

**Comment by p0deje** [comment]
You are not doing anything after you click a print button. What happens if you try to send commands while print preview is displayed?

**Comment by LivClau** [comment]
Updated code like this: 

		logMessage("Start");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("start-maximized");
		System.setProperty("webdriver.chrome.logfile", "D:\\chromedriver.log");
		System.setProperty("webdriver.chrome.verboseLogging", "true");
		WebDriver driver = new ChromeDriver(options);
		driver.get("http://localhost/testprint");
		for (String winHandle : driver.getWindowHandles()) {
			logMessage("Window handle" + winHandle);
	    }
		logMessage("Get the print button!");
		WebElement printButton = driver.findElement(By.id("printButton"));
		logMessage("Click the print button!");
		printButton.click();
		logMessage("The Print Preview is displayed!");
		for (String winHandle : driver.getWindowHandles()) {
	        logMessage("Window Handle: " + winHandle);
	    }
		for (String winHandle : driver.getWindowHandles()) {
			driver.switchTo().window(winHandle);
	    }
		logMessage("Get the cancel button!");
		WebElement cancelButton = driver.findElement(By.cssSelector("div#print-header > div > button.cancel"));
		logMessage("Click the cancel button!");
		cancelButton.click();
		logMessage("Cancel button clicked!");

And the console output is : 

12:20:31.829 Start
Starting ChromeDriver 2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73) on port 14197
Only local connections are allowed.
Jan 18, 2018 12:20:34 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
12:20:34.610 Window handleCDwindow-(2600546BB3BE4AC5F98FC8884CBAB2D6)
12:20:34.610 Get the print button!
12:20:34.630 Click the print button!
12:30:34.723 The Print Preview is displayed!
12:30:35.32 Window Handle: CDwindow-(2600546BB3BE4AC5F98FC8884CBAB2D6)
12:30:35.32 Window Handle: CDwindow-(645DA68E0B8C56C773F1C622EB0DC4AB)
12:30:35.56 Get the cancel button!
12:30:36.140 Click the cancel button!
12:30:36.210 Cancel button clicked!

It is clear that after clicking the print button it stays 10 minutes before returning execution: 
logMessage("Click the print button!");
printButton.click();
logMessage("The Print Preview is displayed!");
-->
12:20:34.630 Click the print button!
12:30:34.723 The Print Preview is displayed!

I've also attached the Chrome Driver log
[chromedriver.log](https://github.com/SeleniumHQ/selenium/files/1642521/chromedriver.log)

**Comment by p0deje** [comment]
I can reproduce it now, thank you.

However, Selenium only clicks the button - everything else is handled by ChromeDriver and is beyond Selenium control. You should look for similar issues at https://bugs.chromium.org/p/chromedriver/issues or maybe create a new one there.

**Comment by TriStarGod** [comment]
@p0deje Did you figure this out?

**Comment by p0deje** [comment]
I haven't, but there are a couple of issues in ChromeDriver that you might want to look at:

* https://bugs.chromium.org/p/chromedriver/issues/detail?id=1087
* https://bugs.chromium.org/p/chromedriver/issues/detail?id=891
