### ISSUE TITLE
Chrome + chromedriver scrolling works, but not --headless 

### ISSUE THREAD

**Issue by krimpenrik** [SeleniumHQ/selenium#5343]
## Meta -
OS: Windows 10 and Ubuntu 16.04 LTE
Selenium Version:  
3.8.1 pip installed python3.6
Browser:  
Chrome + chromedriver 

Browser Version:  
Installed: 63.0.3239.108-0ubuntu0.16.04.1 << Chrome browser on ubuntu, also got latest on windows
Installed: 63.0.3239.108-0ubuntu0.16.04.1 << Chrome driver on ubunto, also got latest on windows 

## Expected Behavior -
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

Scroll down to page, THIS WORKS, but only in GUI mode, not in --headless mode. Both in windows and on linux you can't scroll down headless. 

Is this normal Behavior? 

## Actual Behavior -
No scrolling takes place in headless mode 

## Steps to reproduce -
More complete post: 
https://stackoverflow.com/questions/48257870/headless-chrome-with-selenium-can-only-find-ways-to-scroll-non-headless

## The simplified script: 
https://pastebin.com/KuiRjbb4
Trying to run on this website: 
 https://goo.gl/JcnAds

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
