### ISSUE TITLE
Cannot find proxy with ID "https"

### ISSUE THREAD

**Issue by adiohana** [SeleniumHQ/selenium#5347]
AMI : Red Hat Enterprise Linux 7.4 Intuit AMI
nginx : 1.12 (ssl offloading at nginx)
java : 1.8.0_152
google-chrome : 63.0.2840.100-1.x86_64
chromedriver : 2.53.0

We are using selenium grid and running hub and node behind nginx in order to communicate with SSL.

selenium server standalone jar includes the following class:

ProxyStatusServlet.java

Which includes the following piece of code:

    try {
      URL u = new URL(id);
      id = "http://" + u.getHost() + ":" + u.getPort();
    } catch (MalformedURLException ignore) {}

this means that if I change the node id to start with "https", it will never find it under the proxy registry. because of that, node is always re-registering to grid hub and sessions are terminated.

**Comment by kool79** [comment]
Workaround is to define `id` explicitly in node-config.json in the next ways::
* use http for ID  OR
* use custom id which **is not** valid URL. For example, some kind of guid. Or just strip protocol part

To tell hub how to connect to node use the parameter 'remoteHost' in node-config.json :
```
"remoteHost": "https://my-node:4444",
"id": "my-node:4444"
```

**Comment by adiohana** [comment]
Thank you.

We will try that.


Thanks,
Adi
