### ISSUE TITLE
Strange behavior regarding frozen preferences

### ISSUE THREAD

**Issue by fbergamini** [SeleniumHQ/selenium#5348]
## Meta -
OS:  Windows 7 

Selenium Version:  3.8.1

Browser:  Firefox (geckodriver)

Browser Version:  57.0.4 (64 bits)

## Expected Behavior -

browser.link.open_newwindow preference always set to 2.

## Actual Behavior -

When using a custom profile with browser.link.open_newwindow preference set to 3, Selenium will automatically change the value to 2, as expected from [webdriver.json](https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/webdriver.json#L10) frozen preferences. However, if I do not set a profile, the preference will have value 3.

### Selenium automatically setting value to 2:

FirefoxProfile profile = new FirefoxProfile(new File("PATH TO PROFILE"));
FirefoxOptions options = new FirefoxOptions().setProfile(profile);
WebDriver driver = new FirefoxDriver(options);

### Value set to 3:

WebDriver driver = new FirefoxDriver();

**Comment by p0deje** [comment]
I assume that's the default behavior of GeckoDriver or Marionette. If you think that setting `3` by default is incorrect, you should raise this to https://github.com/mozilla/geckodriver.

I don't see anything that can/should be done on Selenium side.
