### ISSUE TITLE
WebDriverServlet use fixed timeout (10min) to proxy commands instead of value defined by browserTimeout

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/selenium#5349]
Selenium Versions:  
* all versions with passthrough mode handler, 
* 3.8.1+

## Expected Behavior -
  **WebDriverServlet** should use timeout defined by `browserTimeout` parameter  to safe guard your from frozen driver/browser (when it proxy command to particular driver). See  [here](https://github.com/SeleniumHQ/selenium/blob/6e95a6684bb3b7c393449ec6959f339530783b8e/java/server/src/org/openqa/selenium/remote/server/DriverServlet.java#L274) for identical implementation but in the class  org.openqa.selenium.remote.server.DriverServlet.java  (currently removed in 65f74252e5) 
## Actual Behavior -
  Fixed timeout is used: [10 minutes](https://github.com/SeleniumHQ/selenium/blob/1e1af07c30c9cda7db2490fb50e282ee59b0c092/java/server/src/org/openqa/selenium/remote/server/WebDriverServlet.java#L255).

## Additional info -
  Currently (in the master branch) **the only** usage of `browserTimeout` parameter is to calculate  timeout for GridHttpClient (at hub side), it's value is based on `browserTimeout `, see [here](https://github.com/SeleniumHQ/selenium/blob/1e1af07c30c9cda7db2490fb50e282ee59b0c092/java/server/src/org/openqa/grid/internal/TestSession.java#L212). This calculation assume that execution time on node is limited by browserTimeout which is wrong for current implementation. This lead to  different behavior (and different exception provided to client side)  when browser hangs. See table below for example: 

| browserTimeout | actual timeout (session kill): | who kills |
|:----------------------:|:-------------------------:|------------|
|  60 sec                      |  ~134                            | hub|
|  270  sec                   |  ~596 sec                      | hub|
|  300 sec                    | 600 sec (10 min)            | node|
|  600 sec                    | 600 sec (10 min)           | node|
|  1000000                  | 600 sec (10 min)           | node|

**Comment by luke-hill** [comment]
Can I just ask are your values in the middle table inclusive or exclusive of the values on the left.

i.e. for 60s timeout, is the actual timeout 134s, or 60s + 134s (194s). I only ask because I've noticed something for a while on IE / FF tests which mirrors this.

**Comment by kool79** [comment]
actual should be about 134 sec.

**Comment by diemol** [comment]
@kool79 Thanks for the detailed report. Yes, there was some formula in the TestSession class which modified the`browserTimeout` value before the command was executed. That logic has been removed here https://github.com/SeleniumHQ/selenium/commit/213e229cebbbc162d88fe839aec8998906241475. and this commit https://github.com/SeleniumHQ/selenium/commit/3f20f9f2ecb8ddd0ef13c2c17f1f46adaeb762a6 re-establishes the use of `browserTimeout`. 
This will be available in the next release.
