### ISSUE TITLE
org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error

### ISSUE THREAD

**Issue by staplesj** [SeleniumHQ/selenium#5350]
## Meta -
OS:  Windows 10 Pro for Workstations.
Selenium Version:  3,8.1
Browser:  Edge
Browser Version:  Microsoft Edge 41.16299.15.0

I am attempting to test what happens when I log onto the AUT twice.
The expected behaviour - the first session should automatically log me out, with a message in the URL bar, i.e: LOGGED_ON_ELSEWHERE.

The test works perfectly well in Firefox & Chrome, but performs strangely in Edge.

It throws a WebDriverException here at `driver = new EdgeDriver();`

    `System.setProperty("webdriver.edge.driver", "C:\\selenium-files\\MicrosoftWebDriver.exe");
     driver = new EdgeDriver();`

The first session just vanishes - browser has closed, and execution continues on the second browser normally.

The error message is unhelpful:

`org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error`

How can I remedy this please?

**Comment by kool79** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13618786/
```Steven K. Oct 27, 2017 MICROSOFT EDGE TEAM
Edge only allows one instance to be running for Web Driver testing.  
Perhaps with if/when Edge supports multiple profiles this capability will also be added.
I will close this as “working as designed.”
A workaround it to use Selenium Grid and have the testing run on multiple client machines.
```

**Comment by Johnsavadkuhi** [comment]
.

**Comment by p0deje** [comment]
Closing since this is Edge Web Driver limitation.

@kool79 Thank you for explaining.

**Comment by mE75252** [comment]
Well, Edge opens for a sec and then disappears immediately even for the very first instance. 
I'm using,
- Selenium 3.11.0
- Java binding
- Windows 10 (build 15063.1029)
- Edge driver (Version: 4.15063 | Edge version supported: 15.15063 )

Here is my code to open the browser:
import org.openqa.selenium.edge.EdgeDriver;
System.setProperty("webdriver.edge.driver", C://mE//Selenium//Installation//Drivers//Edge//v15063//MicrosoftWebDriver.exe");
WebDriver driver = new EdgeDriver();

Here is the error: Exception in thread "main" org.openqa.selenium.WebDriverException: Unable to parse remote response: Unknown error

**Comment by malam75252** [comment]
I'm still having the same issue (Edge crashes) while launching Edge browser with selenium. I don't have any instance of Edge open. Any help will be appreciated.

**Comment by RoakyWood** [comment]
Same issue. Answer did not match the question. The question is on first launch. No other Edge instance is open in my case either.

**Comment by sakthiveliyappan** [comment]
I have come across the same issue...so i did close all instance and run one instance at a time.Thanks

**Comment by rp13** [comment]
Facing this issue even downloaded proper driver for OS build version and cleared the webdriver data in Task manager, browser launching successfully but closing immediately without entering the URL
