### ISSUE TITLE
How to  remove file with python+selenium  after logining in  dropbox ? 

### ISSUE THREAD

**Issue by gitsnippet** [SeleniumHQ/selenium#5353]
How to  remove file with python+selenium  after logining in  dropbox ?

**Comment by lmtierney** [comment]
This is a place to report issues with selenium, not usage questions. This question is more suited for StackOverflow. In the future, please send questions related to selenium itself to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
