### ISSUE TITLE
Getting exception in Safari when clicked on html button : OpenQA.Selenium.ElementNotVisibleException: An element command could not be completed because the element is not visible on the page.

### ISSUE THREAD

**Issue by sachinyadav15** [SeleniumHQ/selenium#5355]
Safari Browser version : 11.0.3
Let me know if more details required.

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/

**Comment by RenzoLiu0209** [comment]
I met the same problem. Have this problem fixed?

**Comment by Icaroto** [comment]
Im also having this issue. It finds the element but when try to click if trhows an error. it is not on all elements, just one.

**Comment by maritakula-pk** [comment]
Safari is throwing exception to  click(), sendKeys() ? Does anyone has any fix ?

**Comment by sandeepjain1987** [comment]
Any updates on this issue ?

**Comment by SergeyPalanevich** [comment]
You can find details at https://bugs.webkit.org/show_bug.cgi?id=174710. This bug has been fixed, but Apple have yet to fix this in SafariDriver. This has been reported to Apple under bug report number 33459305.

**Comment by CAPie** [comment]
I've faced with same issue.
cannot click on some elements.
