### ISSUE TITLE
On pop-up/subwindow open, no content is getting rendered in selenium headless testing.

### ISSUE THREAD

**Issue by ShilpaAJ** [SeleniumHQ/selenium#5358]
OS:  Ubuntu (Linux)
Selenium Version:  2.53.1
Browser:  Firefox 46.0

I am running a selenium test suite in headless mode via Jenkins in containerized environment (Docker image has 
![issue](https://user-images.githubusercontent.com/31206027/35090456-a0d382e2-fc31-11e7-9b8a-e8260c53adb8.png)
Ubuntu as its base image running over a Linux box). I am opening a website and performing some validations. At a particular step, a button is clicked on the application and a pop-up/subwindow is supposed to open with the details of the button clicked. At that point it stucks up for indefinite time. To check I added a code to capture screenshot of what's happening. I found that a black pop-up/subwindow opens up but no content is getting rendered over it. Attached is the snapshot which opens up at that point. The same code is working fine on local and on remote hub via Jenkins. Any suggestions/advice.
![Uploading Issue.png…]()

**Comment by barancev** [comment]
Please be more specific, what do you mean exactly by "headless mode"?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
