### ISSUE TITLE
Error while executing test with more than 5 chrome instances open in Selenium-Python

### ISSUE THREAD

**Issue by rasagjnya** [SeleniumHQ/selenium#536]
Hi,  I have a script where there are 8 test methods each opening a chrome browser and keeping it open (without driver.quit()). After the completion of 5 methods an error comes as below:

"Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\selenium\webdriver\chrome\service.py", line 63, in start
    self.service_args, env=env, stdout=PIPE, stderr=PIPE)
  File "C:\Python34\lib\subprocess.py", line 754, in **init**
    _cleanup()
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\SeleniumAutomation\common\common_settings.py", line 126, in setup_selenium
    driver = CommonSettings.setup_server(self.executionFlag)
  File "..\SeleniumAutomation\common\common_settings.py", line 168, in setup_server
    driver = CommonSettings.getdriver(executionFlag)
selenium.common.exceptions.WebDriverException: Message: ChromeDriver executable needs to be available in the path. Please download from http://chromedriver.storage.googleapis.com/index.html and read up at http://code.google.com/p/selenium/wiki/ChromeDriver"

Pleae let me know if there's any way to get around this because its causing many issues.

Thank You

**Comment by ddavison** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

But based on your stack trace, this should be easy to fix.. just put ChromeDriver on your path like it asks

**Comment by rasagjnya** [comment]
Hi @ddavison , this is an issue :-( ....The chrome driver is there (as mentioned in other posts of the forum) and it specifically happens with scripts whose test methods are more than 5 and there is not driver.quit()

**Comment by tarlabs** [comment]
@rasagjnya, Anything that doesn't give a steps to reproduce is not considered issue over here. It is very difficult for someone to imagine what all configuration you are using and then debug the issue. So please mention how one can reproduce the error. Setup a github project may be and post the link to same, so it can be run and the error can be reproduced.

Else post it in user group and once it gets confirmed that it is an issue then open one here

**Comment by rasagjnya** [comment]
Ok.

**Comment by rasagjnya** [comment]
Hi, Please find below the code that is giving me error:

`from selenium.webdriver.support.ui import WebDriverWait
import unittest, sys
sys.path.append('..\SeleniumAutomation')
from common.common_settings import *


class main (unittest.TestCase):

    def setUp(self):
        self.testName = CommonSettings.GetTestName(self)
        self.executionFlag = ""
        self.driver=CommonSettings.setup_selenium(self, sys.argv);

    def test_a(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,CommonSettings.timeout) 
            driver.get("http://mail.google.com/")
            driver.find_element_by_id("Email").send_keys("qwerty@gmail.com")
            driver.find_element_by_id("Passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("signIn").click()

       except Exception as e:

            #Error Handling & Screenshot generation
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def test_b(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,CommonSettings.timeout) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:

            #Error Handling & Screenshot generation
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def test_c(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,CommonSettings.timeout) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:

            #Error Handling & Screenshot generation
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def test_d(self):
        try:     
            driver = self.driver
            wait = WebDriverWait(driver, CommonSettings.timeout)          
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

        except Exception as e:
            
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def test_e(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,CommonSettings.timeout) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:
            
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def test_f(self):
        try:     
            driver = self.driver
            wait = WebDriverWait(driver, CommonSettings.timeout)
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

        except Exception as e:           
            CommonSettings.errorHandler(self.driver, self.executionFlag,self.testName)
            self.fail()

    def tearDown(self):
         #self.driver.quit()
         print ("Test Completed " +sys.argv[0])

if __name__ == '__main__':
    unittest.main(argv=[sys.argv[0]],warnings=False)`

**Comment by barancev** [comment]
Your sample is totally useless without CommonSettings class

**Comment by rasagjnya** [comment]
I have modified the code to make it more meaningful:

`from selenium import webdriver
import unittest
from selenium.webdriver.support.ui import WebDriverWait

class main (unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Chrome(executable_path = "path to chrome driver")
        self.driver.implicitly_wait(30)
        self.base_url = "http://mail.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_a(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,10) 
            driver.get("http://mail.google.com/")
            driver.find_element_by_id("Email").send_keys("qwerty@gmail.com")
            driver.find_element_by_id("Passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("signIn").click()

       except Exception as e:
            self.fail()

    def test_b(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,10) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:
            self.fail()

    def test_c(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,10) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:
            self.fail()

    def test_d(self):
        try:     
            driver = self.driver
            wait = WebDriverWait(driver, 10)          
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

        except Exception as e:
            self.fail()

    def test_e(self):
       try:
            driver = self.driver
            wait = WebDriverWait(driver,10) 
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

       except Exception as e:
            self.fail()

    def test_f(self):
        try:     
            driver = self.driver
            wait = WebDriverWait(driver, 10)
            driver.get("http://mail.yahoo.com/")
            driver.find_element_by_id("login-username").send_keys("qwerty")
            driver.find_element_by_id("login-passwd").send_keys("abc@gmail.com")
            driver.find_element_by_id("login-signin").click()

        except Exception as e:           
            self.fail()

    def tearDown(self):
         #self.driver.quit()
         print ("Test Completed " +sys.argv[0])

if __name__ == "__main__":
    unittest.main(argv=[sys.argv[0]],warnings=False)'

**Comment by SpartaSixZero** [comment]
Hi, 

Is there any updates on this issue? I'm experiencing the same problem. Please check out my post on StackOverflow here: http://stackoverflow.com/questions/31079460/oserror-winerror-6-the-handle-is-invalid-selenium-python

Basically, I have 7 tests and running them gives me the same error that OP is seeing. And the location to my chromedriver is in my PATH variable. As described in my StackOverflow post, I am not seeing the same issue while using Firefox driver. However, I still prefer to use ChromeDriver over Firefox driver.

**Comment by FrnkVieira** [comment]
Hello,

Any updates ? I'm also experiencing this issue but in a different way. I have a lot of machines running automated tasks with selenium (2~6 browsers open simultaneously) and from hour to hour we see this bug in a literally random way. When the first exception appears than the whole script will keep raising this exception at every subprocess call, not sure even if this is a selenium bug or a Python one, in my case it only happens in long running scripts at Windows with any webdriver (Tested with Chrome, Firefox, IE).
