### ISSUE TITLE
Actions, input and webdriver: inconsistency or (likely) my own stupidity?

### ISSUE THREAD

**Issue by mercmobily** [SeleniumHQ/selenium#5363]
## Meta -
OS: Ubuntu 
Selenium Version:   Any
Browser:  Any

This is not quite an issue, but... help.
Since there is virtually no documentation on the javascript/node side of the story, I am self-documenting things and making node from the code.
I am stuck at actions. In the [actions.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/actions.js) file I see for example

     dragAndDrop(element, location) {
        return this.mouseDown(element).mouseMove(location).mouseUp();
      }

And:

     click(opt_elementOrButton, opt_button) {
        return this.scheduleMouseAction_('click',
            command.Name.LEGACY_ACTION_CLICK, opt_elementOrButton, opt_button);
      }

From [this blog](http://www.seleniumeasy.com/selenium-tutorials/how-to-perform-mouseover-action-in-selenium-webdriver) I saw how to use actions.
What I don't quite get, is the API. The actions.js file has methods like `mouseUp`, `mouseDown`, `mouseMove`, `click`, `keyUp`, `keyDown`, `sendKeys` .

SOME of them, I found in [input.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/input.js), like `keyUp`, `keyDown` (under "keyboard"); confusingly, the pointer ones in input.js have different names (`press`, `release`, `move`...).

THEN SOME of them I find in [webdriver.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js) like (`click`, `sendKeys`, etc.)

Can somebody please explain:

* The relationship between the three files
* Why the inconsistency in naming  and parameter (e.g. `mouseMove(location, opt_offset)` in actions.js  vs `move({x = 0, y = 0, duration = 100, origin = Origin.VIEWPORT})` in input.js 
* How to do things like `dragAndDrop()` _without_ using an action

Thanks in advance, and sorry about the noise. 1 hour on this, and I just don't get it...

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by mercmobily** [comment]
I agree it's a question; but it's a question about the code itself and its design -- and the question exists because the documentation doesn't.

Please reopen this if nobody in the community user group knows the detail of the code of a specific API... (will let you know)

**Comment by mercmobily** [comment]
@jleyba Tagging you in case you are feeling magnanimous...

**Comment by lmtierney** [comment]
@mercmobily does this not cover your questions?

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html

**Comment by lmtierney** [comment]
Although I do believe that is for the new beta version, I'll let @jleyba weigh in

**Comment by mercmobily** [comment]
It is for the beta version and no, theink doesn't really answer my
questions...
