### ISSUE TITLE
Firefox - C# - (3.8.0) - Null Exception thrown when try to Capture javascript console logs.

### ISSUE THREAD

**Issue by beloquintana** [SeleniumHQ/selenium#5369]
## Meta -
OS:  Window Sever 2012
Selenium Version:  
3.8.0
Browser:  
Firefox
Browser Version:  
57.0.4 (64-bit)

## Expected Behavior - 
Capture javascript console logs

## Actual Behavior -
Null Exception

## Steps to reproduce -
                   Configuration:

                    FirefoxOptions options = new FirefoxOptions();
                    options.SetLoggingPreference(LogType.Browser, LogLevel.All);
                    var driver = new FirefoxDriver(@"C:\Selenium",options);
                    driver.Navigate().GoToUrl("https://www.google.com.");
                    IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
                    js.ExecuteScript("console.error('log error')");
                    List<LogEntry> logs = driver.Manage().Logs.GetLog(LogType.Browser).ToList();

**Comment by lmtierney** [comment]
Firefox does not support capturing console logs, nor does the w3c specify it to. It may be added to the spec at a later date.

https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by beloquintana** [comment]
With this configuration it work for me in Firefox 47, Selenium 2.53.1 and Window. If there is another option for theses version I look forward to your answer.                

                    ChromeOptions options = new ChromeOptions();
                    options.SetLoggingPreference(LogType.Browser, LogLevel.Severe);
                    var obj = options.ToCapabilities().GetCapability("loggingPrefs");
                    DesiredCapabilities browCapab = DesiredCapabilities.Firefox();
                    browCapab.SetCapability("loggingPrefs", obj);
