### ISSUE TITLE
right click not working with IEDriver

### ISSUE THREAD

**Issue by doshinam** [SeleniumHQ/selenium#5370]
## Meta -
OS:  Windows 7

Protractor Version:  5.2.2

Browser:  IE 11

Browser Version:  11.0.9600.18893

Driver: IEDriverServer 3.8.0

## Expected Behavior -
Right click on an element should open the context menu
## Actual Behavior -
Right click action is not triggered
## Steps to reproduce -
In order to right click on an element, I am using
      this.executeSequence([
            browser.actions().mouseMove(element(by.xpath("//span[text()='xyz'']")).perform(),
            browser.actions().click(element(by.xpath("//span[text()='xyz'']"), protractor.Button.RIGHT).perform()
        ]);

This works as expected on Chome, but it does not work on IE.

**Comment by lmtierney** [comment]
IEDriverServer 3.8.0 expects w3c actions, not the OSS actions. As of right now, protractor does not send w3c compatible actions. Protractor needs to update in order to use IEDriverServer 3.5.0+.

Alternatively, you can downgrade your IEDriverServer to 3.4.0

**Comment by doshinam** [comment]
With the IEDriverServer 3.4.0 version, I am unable to create the a new session

17:22:04] I/hosted - Using the selenium server at http://localhost:5555/wd/hub
undefined
[17:22:05] E/launcher - Unable to create new service: InternetExplorerDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'LT-160501', ip: '192.168.21.101', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: unknown
[17:22:05] E/launcher - SessionNotCreatedError: Unable to create new service: InternetExplorerDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'LT-160501', ip: '192.168.21.101', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: unknown

Here is the config
  capabilities: {
      browserName: 'internet explorer',
      version: '11',
      'ignoreProtectedModeSettings': true
  },

seleniumAddress: 'http://localhost:5555/wd/hub',
