### ISSUE TITLE
Default Selenium JS Driver does not append new input but Selenium Chrome Headless does

### ISSUE THREAD

**Issue by eliduke** [SeleniumHQ/selenium#5371]
## Meta
OS:  Mac OS 10.12.6
Selenium Version:  3.60

## Expected Behavior
I have some functionality in a Rails app where hitting enter in an input appends a new input below the existing one and focus moves to the new input. The js to accomplish such a thing works perfectly fine in the browser during hand testing, and I want some feature tests for it as well.

With the following js

```
$(function(){
  $("form.scan").keydown(function (e) {
    if (e.keyCode === 13) {
      inputsDiv      = $("#inputs");
      existingInputs = inputsDiv.children();
      lastInput      = existingInputs.last();
      newInput       = '<input type="text" name="item_ids[]" id="item_' + (existingInputs.length + 1) + '" placeholder="Scan and hit ENTER" class="form-control" />';

      if (lastInput.is(":focus")) {
        if (lastInput.val().length > 0) {
          inputsDiv.append(newInput);
          inputsDiv.children().last().focus();
        }
      } else {
        $(document.activeElement).next().focus();
      }
      e.preventDefault();
    }
  });
});
```

I would expect the following spec to pass

```
it "pressing RETURN in the last field when filled out, appends new field and moves focus to it" do
  visit "/"

  expect(page).to_not have_css("#item_4")

  fill_in("item_3", with: "123")
  find("#item_3").send_keys(:return)

  expect(page).to have_css("#item_4")
  expect(page.evaluate_script("document.activeElement.id")).to eq "item_4"
end
```

## Actual Behavior
The test in question will not pass with the default selenium js driver, but simply switching the js driver to `:selenium_chrome_headless` makes the tests pass. Seems like there must be something wrong with the default js driver.

## Steps to reproduce
I have created a sample app to reproduce the issue here:

https://github.com/eliduke/selenium-webdriver-bug-report

**Comment by lmtierney** [comment]
I have no idea what capybara is doing in this scenario, or what browser/driver it is attempting to use at this time. Please raise a bug with capybara. Alternatively, if you can reproduce this using just selenium code then I will reopen it.

**Comment by eliduke** [comment]
@lmtierney It’s using the selenium driver.

**Comment by eliduke** [comment]
@lmtierney If I pry into the spec in question and check what Capybara is using, this is what I get:
```
Capybara.javascript_driver => :selenium
```

**Comment by twalpole** [comment]
@eliduke This issue has nothing to do with Selenium, and is caused by a difference in behavior between geckodriver/firefox and chromedriver/chrome when it comes to focusing of elements when keys are sent to them.  The easiest solution for you is to change your JS from checking if the last element is the focused one, to checking if the last element is the one that received the keydown event (or possibly is the activeElement).  

For future reference, the default Capybara selenium driver is Selenium with Firefox as opposed to :selenium_chrome_headless which (as named) is Selenium with chrome configured to run headless.

**Comment by eliduke** [comment]
@twalpole It’s not an issue of the focus, it’s an issue of the new input being added. When using the default js driver, if I pry into the spec after I have sent :return, the new input has not been added. When using selenium headless chrome, the input has been added. Thoughts on that?

**Comment by eliduke** [comment]
@twalpole Also, the form in question can have lots of inputs and hitting enter in any of the in-between inputs just moves the focus along to the next input. It’s only when hitting enter in the last input that it should add a new input. So, I need to be checking for keydown in the whole form, not just in one input.

**Comment by twalpole** [comment]
@eliduke It IS an issue of focus -  the line  `if (lastInput.is(":focus"))` doesn't match with geckodriver/firefox because the focus isn't set by them when send keys is sent.  So if you change that to something along the lines of  `if (lastInput == $(e.target).closest('input')` then it should work in both browsers and in your tests (you should really be checking the input that actually received the key rather than the focused element anyway)

**Comment by lmtierney** [comment]
Thanks @twalpole

**Comment by eliduke** [comment]
@twalpole I tried your suggestion and it worked! So, now I'm curious what the story is there. I realize that this is not the place to carry on the discussion, but where is that place? Is this a bug or just a subtle difference between firefox and chrome? Thanks again for your help!

**Comment by twalpole** [comment]
@eliduke It's a difference between geckodriver/firefox and chromedriver/driver.  I'm not 100% sure which is correct, but I'd lean more towards the chromedriver/chrome behavior being correct.  It looks like it probably comes down to step 9 of the remote end steps for  Element Send Keys - "If element is not the active element run the focusing steps for the element." ( https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys ) and whether an input element can be active but not focused.  Therefore If you want to discuss it somewhere the geckodriver project would probably be the place to start.  If you do bring it up there make sure you post a TRACE log with a reproducible example (details at the geckodriver project).

**Comment by eliduke** [comment]
@twalpole Thanks again for your time on this. I take a look at the geckodriver project. 👍
