### ISSUE TITLE
Problem with HUB forwarding request to NODE

### ISSUE THREAD

**Issue by StephenPCG** [SeleniumHQ/selenium#5373]
## Meta -
Selenium Version:  
* hub docker image: selenium-hub:latest
* node docker image: selenium-node-chrome:latest

## Steps to reproduce -

We deployed a selenium-hub and several selenium-node-chromes with docker, due to our company's firewall policy, hub does not have direct network to nodes. We have a **single** ingress http gateway (nginx), which does the following route based on `Host` header:
* `hub.selenium.mycompany.com` -> route to hub
* `node1.selenium.mycompany.com` -> route to chrome node 1
* `node2.selenium.mycompany.com` -> route to chrome node 2
* so on and so forth

The node is started as:
```
SE_OPTS='-remoteHost http://node1.selenium.mycompany.com -id node1' /opt/bin/entry_point.sh
```

And the node successfully registered with hub. However, things failed when hub got a request to create a new session.

The client sends an HTTP request like:

```
POST /wd/hub/session HTTP/1.1
Host: hub.selenium.mycompany.com
(other info snipped)
```

The hub selects an available node (assume it's node1), and forwards the request by:

* first makeing a tcp connection to `node1.selenium.mycompany.com:80` (connected to the nginx)
* then forwarding the http request as is, with `Host` header not modified

When this request reaches the nginx, it sees the `Host` header is `hub.selenium.mycompany.com`, so routed back to hub again, causes a dead loop.

Suggested solution is, when hub forwarding the request to node, it should set Host header according to node's `remoteHost` value. This change should do no harm to most existing installations.

**Comment by diemol** [comment]
@StephenPCG, seems that you have special network conditions. Why don't you check how to overwrite the Host header via Nginx?

What the hub does is just to contact the node via the url used to register, and if it is not accessible then it is just not possible to do it. I don't think the Grid should be changed to support that, it is merely a routing configuration.

**Comment by StephenPCG** [comment]
@diemol Because both hub and node have the same nginx instance as gateway. The hub forwards the request without any information indicating it should be routed to hub, nginx can not distinguish it. The problem is not nginx not rewriting Host header, the problem is nginx has no way to know the request is intended to be sent to node.

The hub, being an HTTP router, it should follow some forwarding conventions. For example, it could send the request like:

```
POST /wd/hub/session HTTP/1.1
Host: node1.selenium.mycompany.com
X-Forwarded-For: hub.selenium.mycompany.com
```

There are sometimes hub do not have direct access to nodes. For example, there are multiple nodes in a same NAT, and the network administrator does not allow setup port forwarding, they set up a single nginx as HTTP gateway, forwarding requests to corresponding backends. If the hub forwards a request without any node info in headers, the nginx has no idea which node should the request be forwarded to.

**Comment by travisghansen** [comment]
@StephenPCG yes, exactly this.  I'm just bumping into this as well where the `Host` header is not being rewritten when forwarding the request to the node.

In my case, I'm trying to make it so nodes can be run on any network.  To accomplish this, I'm using a reverse proxy (frp) using an http listener that supports vhosts (basically a self-hosted ngrok).  The request from hub gets forwarded to the correct IP/PORT but because the host header hasn't been rewritten it goes nowhere.

Alternatively, and it seems this is a broader issue, if the communication channel between node/hub was updated to use websockets none of the vpn/reverse proxy/etc things would be needed but rather the communication would 'just work'.

**Comment by diemol** [comment]
Going back to this thread after a while...
The question that comes to my head is, how is the Grid even able to start if the hub cannot talk to the nodes? The node can register but after a while the hub is doing some health checks on the nodes, and if they fail, the node is taken offline.
How are you able to have the Grid passing the health checks?

**Comment by diemol** [comment]
Closing as the issue went stale
