### ISSUE TITLE
[rb] Response status 100 causes KeyError

### ISSUE THREAD

**Issue by angelikatyborska** [SeleniumHQ/selenium#5376]
## Meta
OS:  Debian 9.3 (from a Docker container, host OS is OS X 10.11.6, Docker version 17.09.0-ce, build afdb6d4)

Selenium Version: Ruby gem selenium-webdriver 3.8.0

Browser: Headless Chrome

Browser Version: 63.0.3239.132

## Expected Behavior

When Chrome crashes for a reason unknown to me, ChromeDriver provides such a response to selenium-webdriver:

```
{
  "sessionId" => "c86c4b01f01ad357f3977b619cc01a32",
  "status" => 100,
  "value" => {
    "message" =>"chrome not reachable\n  (Session info: headless chrome=63.0.3239.132)\n  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.9.49-moby x86_64)"
  }
}
```

I would like to see an exception that would include the message or a similar response that would indicate the browser is not responding. If that is not possible because  response status 100 is not part of the protocol (I am not certain about that), then an exception about a response violating the protocol could be thrown (including the incorrect response).

## Actual Behavior

This status response 100 cannot be mapped to any error class. A cryptic `key not found: 100 (KeyError)` exception is thrown from selenium-webdriver:

```
Traceback (most recent call last):
	27: from run.rb:42:in `<main>'
	26: from run.rb:25:in `run'
	25: from run.rb:25:in `each_with_index'
	24: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/result.rb:40:in `each'
	23: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/result.rb:40:in `each'
	22: from run.rb:31:in `block in run'
	21: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
	20: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/node/finders.rb:266:in `all'
	19: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/node/base.rb:85:in `synchronize'
	18: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/node/finders.rb:267:in `block in all'
	17: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/queries/selector_query.rb:145:in `resolve_for'
	16: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/node/base.rb:81:in `synchronize'
	15: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/queries/selector_query.rb:147:in `block in resolve_for'
	14: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/node/base.rb:103:in `find_css'
	13: from /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/selenium/driver.rb:84:in `find_css'
	12: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
	11: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:557:in `find_elements_by'
	10: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
	 9: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	 8: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	 7: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	 6: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	 5: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	 4: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	 3: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:74:in `assert_ok'
	 2: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/remote/response.rb:41:in `error'
	 1: from /home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/error.rb:32:in `for_code'
/home/angelika/src/selenium-webdriver-3.8.0/lib/selenium/webdriver/common/error.rb:32:in `fetch': key not found: 100 (KeyError)
```

## Steps to reproduce
Here is a repository with a Dockerfile and a short Ruby script (using Capybara) that almost always causes Chrome to crash and reproduces this bug: https://github.com/angelikatyborska/headless-chrome-crashes. Please follow the README.

**Comment by nhammERA** [comment]
Adding to this thread because I too am running into the same issue.
OS: Ubuntu 16.04 (64 bit)
Browser: Chromium Version 63.0.3239.84 (running headless)
ChromeDriver 2.35.528139 
Gems
 * selenium-webdriver (3.8.0)
 * watir (6.8.4)

**Comment by elialbert** [comment]
any update on this? seems like latest chrome (64.xxx) causes previously working headless tests to start failing with this error as well.

**Comment by p0deje** [comment]
This is fixed in master and will be released in 3.9 (not sure when).

**Comment by elialbert** [comment]
gotcha! can you give me a clue what's actually causing this on the selenium side? some of our tests are failing right now and some are not and I'd love to fix this in my own build as it's got us completely blocked right now.

**Comment by p0deje** [comment]
Take a look at cae006b1a358d04e109e483c8851acbce67c0249.

**Comment by luke-hill** [comment]
Update: I'm 99% sure he meant: https://github.com/SeleniumHQ/selenium/commit/e85b830caf0f8342e7427d4d7a8136e312f24086

But yeh, it's basically not rescuing a specific Key Not Found Error

**Comment by elialbert** [comment]
gotcha thanks!

**Comment by elialbert** [comment]
also - I don't have the time to make a reproducible docker image or something right now, but the ultimate cause of my chromedriver server errors was actually headless chrome downloading a file during a test.

**Comment by mikefogg** [comment]
@elialbert thank you for that last comment! Solved a problem we were running into all morning (it was... frustrating...) the `key not found: 100` error was coming up and couldn't figure out what it was. Your comment led us to check and sure enough it was the same issue, we were downloading a file during a test as well.

**Comment by elialbert** [comment]
bam! so happy to help
