### ISSUE TITLE
TypeError: Libs.Selenium.WebElement.subelement object is not JSON serializable

### ISSUE THREAD

**Issue by cindysongzi** [SeleniumHQ/selenium#5377]
## Meta -
OS:  Windows 10

Selenium Version:  
3.33

Browser:  
Chrome

Browser Version:  
Version 63.0.3239.132 (Official Build) (64-bit)

## Expected Behavior -
driver.execute_script(js, ele) should work.

## Actual Behavior -
TypeError: <Libs.Selenium.WebElement.StaticElement.StaticElement object at 0x0000022FB4B0B908> is not JSON serializable

## Steps to reproduce -
I created StaticElement to inherit selenium original WebElement in my script running with Chrome browser. But it failed to execute js with wrror "TypeError: Libs.Selenium.WebElement.subelement object is not JSON serializable". 
After that, I tried to type my StaticElement to WebElement and ran scriot again, it still failed. 
sample code:
user = self.browser.find_web_element(By.XPATH, __USER)
u = WebElement(self, user)
self.browser._selenium_context().execute_script("arguments[0].click();", u)

Besides, I have read issues#2666, and I don't think it helps on Chrome browser. Can you guys take a look? Thanks!

**Comment by cindysongzi** [comment]
I solved the problem. Thanks anyway.

**Comment by Luclause** [comment]
I'm having the exact same issue, could you post your solution?
