### ISSUE TITLE
Selenium:Java - Need the selenium client binary checksum to avoid  encountering errors which may have been introduced during its transmission or storage.

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5378]
## Meta - Need the **`Selenium Client Binary`** [**`Checksum`**](https://en.wikipedia.org/wiki/Checksum) in [**`Release Notes`**](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG) to avoid  encountering errors which may have been introduced during its transmission or storage. 

A checksum which can be possibly calculated via MD5 algorithm.

OS:  All

Selenium Version:  All

Browser:  All

Browser Version:  All

## Steps to reproduce - 

- Download : 

        selenium-server-standalone-3.9.0

        selenium-java-3.9.0

Maven Configuration : 

            <artifactId>selenium-java</artifactId>
            <version>3.9.0</version>

**Comment by diemol** [comment]
This has been open for a while to gather interest from the community, as we do not see many people chiming in, we interpret it as a feature not widely needed. Therefore, I will close this. However, we are always open to PRs in case someone wants to contribute this.
