### ISSUE TITLE
PhantomJSDriverService Vs ChromeDriverService

### ISSUE THREAD

**Issue by voleynik** [SeleniumHQ/selenium#5379]
Hello Selenium friends.

I have a situation where I need to switch from 

org.openqa.selenium.phantomjs.PhantomJSDriverService

to 

org.openqa.selenium.chrome.ChromeDriverService

The issue I am facing is this:

PhantomJSDriverService has this "PhantomJSDriverService.PHANTOMJS_CLI_ARGS" capability and

you can do this (see pointer <====== below):
PhantomJSDriverService service = new PhantomJSDriverService.Builder()
                .usingPort(portNumber)
                .usingPhantomJSExecutable(new File(phantomJsExecPath))
                .usingCommandLineArguments(PhantomUtil.getCommandLineParameters()) <======
                .build();

ChromeDriverService does not have any of these features.

I am calling phantomjs.exe from Java code and need to do the same to chrome.exe as follows:

chrome.exe --headless --disable-gpu --remote-debugging-port=9222

Any help would be greatly appreciated.
Regards,
Vladimir
vladimir.oleynikATmailDOTcom
https://github.com/voleynik

**Comment by jleyba** [comment]
Use the ChromeOptions class:

http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/chrome/ChromeOptions.html

**Comment by voleynik** [comment]
Thanks :-)
