### ISSUE TITLE
Geckodriver TakesScreenshot class method getScreenshotAs() creates broken image for page with opened local image file in Firefox

### ISSUE THREAD

**Issue by beluha** [SeleniumHQ/selenium#5381]
## Meta -
OS:  Windows 7 64-bit

Selenium Version:  3.7.1, 3.8.1

Browser:  Firefox

Browser Version:  57.0.4

## Expected Behavior -
Image with browser page content
## Actual Behavior -
An empty/broken image
## Steps to reproduce -

1. There is Moon.jpg file in attach.
![moon](https://user-images.githubusercontent.com/19341020/35219397-7c2dcd80-ff83-11e7-99e6-53f76e844a77.jpg)
2. Open this file through code with help of geckodriver and FirefoxDriver.
3. Take screenshot with help of TakesScreenshot getScreenshotAs() method.
4. Validate captured image - just open it.

Or execute the following Java code to reproduce provided steps.
## Java code
import java.io.File;
import java.io.IOException;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;

public class BrowserCapture {
    public static void main(String[] args) throws IOException {
        WebDriver driver = new FirefoxDriver(new FirefoxOptions().setProfile(new FirefoxProfile()));
        driver.get("file:///C:/temp/Moon.jpg");
        File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
    }
}
## Verify
Open created image file "scrFile". Windows image viewer says it is empty, FF browser says it has errors.

## Note
Chrome driver and IE Driver server don't have such issue.

**Comment by barancev** [comment]
Please report this issue to geckodriver project: https://github.com/mozilla/geckodriver/issues

**Comment by beluha** [comment]
https://github.com/mozilla/geckodriver/issues/1156
