### ISSUE TITLE
Selenium test does not work with chromium headless

### ISSUE THREAD

**Issue by creatorness** [SeleniumHQ/selenium#5383]
## Meta -
OS:  Ubuntu 14.04.1
Selenium Version:   3.8.1 (python 3.4.3)
Browser:  chromium
Browser Version:  63.0.3239.84
ChromeDriver: 2.33

## Expected Behavior -
That the test works
## Actual Behavior -
Test work now and then
## Steps to reproduce -
-

I have the following problem, but I do not know if it is a Selenium or Chromium headless problem.
On the development system, the tests are developed and they run through error-free at any time.
But if these tests are played on the live test system and run there, then they run 30% error free and the others time not.

I have, as far as I was able, the software Selenium and Chromium on both systems brought to the same version
The only difference at the moment is that the development system is Ubutnu 16.04.2 and the python version is 3.5.2.
I even tried ChromeDriver 2.35, but there was no improvement.

**Comment by lmtierney** [comment]
This would have nothing to do with Selenium. Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by cgoldberg** [comment]
@creatorness , for future reference... _"they run 30% error free and the others time not"_ is entirely unhelpful for diagnosing an issue.
