### ISSUE TITLE
Option "-enablePassThrough false" does not apply

### ISSUE THREAD

**Issue by dev-e** [SeleniumHQ/selenium#5385]
## Meta -
OS:  
Ubuntu Linux 16.04
Selenium Version:  
3.8.1
Browser:  
Firefox (docker image selenium/node-firefox-debug)

## Expected Behavior -
Option "enablePassThrough" is set appropriately
## Actual Behavior -
Option "enablePassThrough" is set to default (true)
## Steps to reproduce -
launch java -Xms500m -Xmx500m -jar /opt/selenium/selenium-server-standalone.jar -role node -hub http://localhost:4444/grid/register -nodeConfig /opt/selenium/config.json **-enablePassThrough false**

LOG from selenium HUB:
`11:13:30.392 DEBUG - getting the following registration request  : {"class":"org.openqa.grid.common.RegistrationRequest","name":null,"description":null,"configuration":{"remoteHost":"http://10.64.209.10:5555","hubHost":"localhost","hubPort":4444,"id":"http://10.64.209.10:5555","capabilities":[{"applicationName":"","browserName":"firefox","maxInstances":1,"moz:firefoxOptions":{"log":{"level":"info"}},"platform":"LINUX","se:CONFIG_UUID":"0359fb34-6c18-47c6-bf17-c61fe05cd835","seleniumProtocol":"WebDriver","version":"57.0.2"}],"downPollingLimit":2,"hub":"http://selenium-hub:4444/grid/register","nodePolling":5000,"nodeStatusCheckTimeout":5000,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","register":true,"registerCycle":5000,"unregisterIfStillDownAfter":60000,"cleanUpCycle":null,"custom":{},"host":"10.64.209.10","maxSession":1,"servlets":[],"withoutServlets":[],"browserTimeout":240,"debug":false,"jettyMaxThreads":null,"log":null,"port":5555,"role":"node","timeout":15,"enablePassThrough":true}}`

From selenium HUB console:
```
browserTimeout: 240
debug: false
help: false
jettyMaxThreads: -1
port: 5555
role: node
timeout: 15
enablePassThrough: true
cleanUpCycle: 5000
host: 10.64.209.10
maxSession: 1
capabilities: Capabilities {applicationName: , browserName: firefox, maxInstances: 1, moz:firefoxOptions: {log: {level: info}}, platform: LINUX, se:CONFIG_UUID: 0359fb34-6c18-47c6-bf17-c61..., seleniumProtocol: WebDriver, version: 57.0.2}
downPollingLimit: 2
hub: http://localhost:4444/grid/register
id: http://10.64.209.10:5555
hubHost: selenium-hub
hubPort: 4444
nodePolling: 5000
nodeStatusCheckTimeout: 5000
proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy
register: true
registerCycle: 5000
remoteHost: http://10.64.209.10:5555
unregisterIfStillDownAfter: 60000
```

Works if add the option to JSON config. But even in this case changes are not shown in hub console.

Launching HUB with $SE_OPTS="-enablePassThrough false":
from LOG:
```
starting selenium hub with configuration:
{
  "host": null,
  "port": 4444,
  "role": "hub",
  "maxSession": 5,
  "newSessionWaitTimeout": -1,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "jettyMaxThreads": -1,
  "cleanUpCycle": 5000,
  "browserTimeout": 240,
  "timeout": 15,
  "debug": true
}
appending selenium options: -enablePassThrough false
11:27:38.517 INFO - Selenium build info: version: '3.8.1', revision: '6e95a6684b'
11:27:38.517 INFO - Launching Selenium Grid hub
```

From HUB console:
```
Config for the hub :
browserTimeout : 240
debug : true
help : false
jettyMaxThreads : -1
port : 4444
role : hub
timeout : 15
enablePassThrough : false
cleanUpCycle : 5000
host : 10.64.214.30
maxSession : 5
hubConfig : /opt/selenium/config.json
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
registry : org.openqa.grid.internal.DefaultGridRegistry
Config details :
hub launched with : -browserTimeout 240 -debug true -help false -jettyMaxThreads -1 -port 4444 -role hub -timeout 15 -enablePassThrough false -cleanUpCycle 5000 -host 10.64.214.30 -maxSession 5 -hubConfig /opt/selenium/config.json -capabilityMatcher org.openqa.grid.internal.utils.DefaultCapabilityMatcher -newSessionWaitTimeout -1 -throwOnCapabilityNotPresent true -registry org.openqa.grid.internal.DefaultGridRegistry
the final configuration comes from :
the default :
browserTimeout : 0
debug : false
help : false
port : 4444
role : hub
timeout : 1800
enablePassThrough : true
cleanUpCycle : 5000
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
registry : org.openqa.grid.internal.DefaultGridRegistry

updated with params :
browserTimeout : 240
debug : false
help : false
jettyMaxThreads : -1
port : 4444
role : hub
timeout : 15
enablePassThrough : true
cleanUpCycle : 5000
maxSession : 5
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
registry : org.openqa.grid.internal.DefaultGridRegistry
```

**Comment by barancev** [comment]
This option will be completely removed in version 3.9
Please log issues if something is not working as expected without this option.
