### ISSUE TITLE
Given URL is not passed on the latest version of Firefox V58 64-bit Browser 

### ISSUE THREAD

**Issue by DhavalAtri** [SeleniumHQ/selenium#5388]
## Meta -
OS:   Windows 10 Pro 64-bit Operating system  x64 based processor 
Selenium Version:  
3.8.1 (Using Maven Project)
Browser:  
Firefox 58.0 (64-bit)
Geckodriver Version : 0.19.1

## Expected Behavior -
Selenium should hit/enter given URL 
## Actual Behavior -
Selenium not enter the given URL in browser 

## Steps to reproduce -
Using attached code and execute simple program 
`System.setProperty("webdriver.gecko.driver", "C:\\Users\\dhaval.atri\\Desktop\\Dhaval\\Automation_Code\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();
driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
driver.manage().window().maximize();
driver.get("http://www.seleniumeasy.com/");`

**Comment by barancev** [comment]
Please start the driver with increased log level and attatch the log here
```
FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
WebDriver driver = new FirefoxDriver(options);
```

**Comment by DhavalAtri** [comment]
Thanks barancev For reply .. After put your code in my script Script running and url entered into the browser .
Please find the bellow mentioned log as you want ....
IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer Processing error: message was deserialized, but the handler returned false (indicating failure)

1516958100316	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1516958100587	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1516958100587	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1516958100588	Marionette	DEBUG	New connections are accepted
1516958100588	Marionette	INFO	Listening on port 60927
1516958101501	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:60927
1516958101503	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:60956
1516958101505	Marionette	WARN	TLS certificate errors will be ignored for this session
1516958101612	Marionette	DEBUG	Register listener.js for window 4294967297
1516958101622	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"65ac84d1-f8b2-4f55-868d-af1152be0a6b","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"58.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":10812,"moz:profile":"C:\\Users\\dhaval.atri\\AppData\\Local\\Temp\\rust_mozprofile.6d6NMiHGJt8P","moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Jan 26, 2018 2:45:01 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1516958101689	webdriver::server	DEBUG	-> POST /session/65ac84d1-f8b2-4f55-868d-af1152be0a6b/url {"url":"http://www.seleniumeasy.com/test/jquery-dropdown-search-demo.html"}
1516958101698	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1516958102452	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1516958104590	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://www.seleniumeasy.com/test/jquery-dropdown-search-demo.html"
1516958105664	Marionette	DEBUG	Received DOM event "pageshow" for "http://www.seleniumeasy.com/test/jquery-dropdown-search-demo.html"
1516958105666	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by barancev** [comment]
According to the log, everything is OK, the driver said that it opened the URL successfully. What exactly is not working as expected?

**Comment by DhavalAtri** [comment]
1517198744928	geckodriver	INFO	geckodriver 0.19.1 (0000000000000000000000000000000000000000 2017-10-31)
1517198744947	geckodriver	INFO	Listening on 127.0.0.1:9430
1517198745394	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Dell\\AppData\\Local\\Temp\\rust_mozprofile.5RV9wtsMAUxK"
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
[GFX1]: Potential driver version mismatch ignored due to missing DLLs 0.0.0.0 and 0.0.0.0
1517198751279	Marionette	INFO	Listening on port 2828
[GPU 11624] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[GPU 11624] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

Above is the log which i found with Firefox 53 version

**Comment by barancev** [comment]
Accoring to the release notes [1], geckodriver 0.19 supports Firefox 55+

[1] https://github.com/mozilla/geckodriver/releases
