### ISSUE TITLE
If URI containing the address of the WebDriver remote server contains basic authorization, Remote web driver doesn't create.

### ISSUE THREAD

**Issue by OlegYanush** [SeleniumHQ/selenium#5389]
OS:  
 Windows 10
Selenium Version:  
3.8.0
Browser:  
Any

If URI containing the address of the WebDriver remote server contains basic authorization, RemoteWebDriver doesn't create. The server generates a 401 response.  It reproduced for .net client library. I solved it  explicitly adding basic authorization to HttpWebRequest, because if URI contains basic authorization, HttpWebReqest class doesn't add this header by default.

## Expected Behavior -
Remote web driver successfully creating.
## Actual Behavior -
The server generates a 401 response.
## Steps to reproduce -
var driver = new RemoteWebDriver(new Uri("https://username:password@example.com"), capabilities);

**Comment by ipinzari** [comment]
I m facing the same issue. @OlegYanush  Can help me to by pass this problem please?

**Comment by cgoldberg** [comment]
AFAIK, not all browsers support passing basic auth credentials in the URL. 

If you just remove the credentials from the URL, you will be prompted with an authorization alert when visiting the protected page.  You can then have your script switch to the alert window, enter credentials,  and submit to continue.

**Comment by ipinzari** [comment]
@cgoldberg  This is a different issues. We are trying to run our tests in a selenium hub environment which requires a username and password. We are not trying to use 
driver. GoToUrl("https://username:password@example.com").

**Comment by OlegYanush** [comment]
@ipinzari, I know two ways to solve this problem. But, unfortunately, best way is changing code in project. Second way is implementing custom HttpCommandExecutor, but it will be necessary to implement classes that are internal and private classes of HttpCommandExecutor. This is a bad smelling code, but it will solve the problem.

**Comment by OlegYanush** [comment]
@ipinzari, Try to use this class instead of HttpCommandExecutor. In this class a lot of code from HttpCommandExecutor.
Example:
var commandExecutor = new ImprovedHttpCommandExecutor(new Uri("https://username:password@example.com"), TimeSpan.FromSeconds(60), useBasicAuth: true);
var driver = new RemoteWebDriver(commandExecutor, TimeSpan.FromSeconds(60), useBasicAuth: true), capabilities);

[ImprovedHttpCommandExecutor.zip](https://github.com/SeleniumHQ/selenium/files/1663240/ImprovedHttpCommandExecutor.zip)

**Comment by diemol** [comment]
Is this still an issue?
If so, how are people being able to use cloud providers like Sauce Labs, which in many cases people create the `RemoteWebDriver` by putting their user and key next to the connection url.

**Comment by diemol** [comment]
Closing this as the issue went stale.
