### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by Juniorn1003** [SeleniumHQ/selenium#5391]
## Meta -
OS:  
Linux (Debian)

Selenium Version:  
3.8.1

Browser:  
Firefox

Browser Version:  
52.5.0

GeckoDriver Version:
0.19.1

## Expected Behavior -
Going to www.google.com with out getting connection refused

## Actual Behavior -
Justin opens the firefox blank page, it doesn't goes to the link page.

## Steps to reproduce -

from selenium import webdriver
driver = webdriver.Firefox()
driver.get("www.google.com")

( By the way, I am using Python )
I am sorry if this is a duplicate of an issue, I just can't fix it with my knowledge.
In StackOverflow and in other communities,  I couldn't find the answer for me.
What happens is when I use the code above (In the steps to reproduce) it opens a blank firefox page, then just stays like that, then gives me the error:

"selenium.common.exceptions.WebDriverException: Message: connection refused" with all other things.

In my geckodriver.log, it says:

1516818959130	geckodriver	INFO	geckodriver 0.19.0
1516818959177	geckodriver	INFO	Listening on 127.0.0.1:57047
1516818960498	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.Z9N4ep0K37xR"
1516818963771	Marionette	ERROR	Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
[Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
MarionetteServer.prototype.start@chrome://marionette/content/server.js:95:19
MarionetteComponent.prototype.init@resource://gre/components/marionette.js:217:5
MarionetteComponent.prototype.handle@resource://gre/components/marionette.js:112:5

Can this be fixed? Is it just a bug, or a version problem?

**Comment by lmtierney** [comment]
Geckodriver `0.19.0` suggests Firefox 55 or greater. `0.18.0` suggest Firefox 53 or greater. I'd try `0.17.0` if you're limited to Firefox 52.

The recommendations are found on their releases page. https://github.com/mozilla/geckodriver/releases

**Comment by Juniorn1003** [comment]
Thanks, 16.1 Works like charm for me.
