### ISSUE TITLE
Session was terminate due PROXY_REGISTRATION

### ISSUE THREAD

**Issue by jeitae** [SeleniumHQ/selenium#5392]
OS:  Mac OS high Sierra 10.13.2

Selenium Version:  3.4.0

Browser:  MAC, APPIUM

## Steps to reproduce -
-command: java -jar selenium-server-standalone-versionxxxx.jar -role hub
-add node with appium config.

---------

org.openqa.selenium.WebDriverException: Session ["SESSION_ID"] was terminated due to PROXY_REREGISTRATION
Command duration or timeout: 474 milliseconds.

How i can take control of that? if i run 2 test all good but for more all fail by PROXY_REREGISTRATION

----------LOG Selenium Grid-----------------

11:27:46.795 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
11:27:46.795 INFO - Launching Selenium Grid hub
11:27:47.350 INFO - Will listen on 4444
11:27:47.444 INFO - Nodes should register to http://169.254.117.65:4444/grid/register/
11:27:47.444 INFO - Selenium Grid hub is up and running
11:28:05.585 DEBUG - getting the following registration request  : {"capabilities":[{"seleniumProtocol":"WebDriver","automationName":"XCUITest","browserName":"MAC","maxInstances":6,"udid":"a99511e1IPHONE_UDID","platform":"MAC"}],"configuration":{"unregisterIfStillDownAfter":60000,"role":"node","nodeStatusCheckTimeout":5000,"nodeTimeout":120,"hubHost":"localhost","hubPort":4444,"deviceReadyTimeout":120,"timeout":0,"url":"http://0.0.0.0:54576/wd/hub","nodePolling":500,"proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy","cleanUpCycle":5000,"hub":"localhost:4444/grid/register","port":54576,"newCommandTimeout":120,"browserTimeout":0,"maxSession":6,"registerCycle":5000,"register":true,"host":"0.0.0.0","id":"http://0.0.0.0:54576"}}
11:28:05.685 DEBUG - Using class org.openqa.grid.selenium.proxy.DefaultRemoteProxy
11:28:05.690 INFO - Registered a node http://0.0.0.0:54576
11:28:05.691 DEBUG - proxy added http://0.0.0.0:54576
11:28:06.197 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:06.207 DEBUG - CookieSpec selected: default
11:28:06.215 DEBUG - Auth cache not set in the context
11:28:06.216 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:06.227 DEBUG - Connection leased: [id: 0][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:06.228 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:06.231 DEBUG - Connecting to /0.0.0.0:54576
11:28:11.450 DEBUG - http-outgoing-0: Shutdown connection
11:28:11.451 DEBUG - Connection discarded
11:28:11.451 DEBUG - Connection released: [id: 0][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:11.452 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:11.955 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:11.957 DEBUG - CookieSpec selected: default
11:28:11.957 DEBUG - Auth cache not set in the context
11:28:11.957 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:11.957 DEBUG - Connection leased: [id: 1][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:11.958 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:11.958 DEBUG - Connecting to /0.0.0.0:54576
11:28:16.964 DEBUG - http-outgoing-1: Shutdown connection
11:28:16.964 DEBUG - Connection discarded
11:28:16.964 DEBUG - Connection released: [id: 1][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:16.965 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:16.965 INFO - Marking the node http://0.0.0.0:54576 as down: cannot reach the node for 2 tries
11:28:17.468 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:17.470 DEBUG - CookieSpec selected: default
11:28:17.470 DEBUG - Auth cache not set in the context
11:28:17.470 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:17.470 DEBUG - Connection leased: [id: 2][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:17.470 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:17.471 DEBUG - Connecting to /0.0.0.0:54576
11:28:22.476 DEBUG - http-outgoing-2: Shutdown connection
11:28:22.477 DEBUG - Connection discarded
11:28:22.477 DEBUG - Connection released: [id: 2][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:22.478 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:22.979 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:22.981 DEBUG - CookieSpec selected: default
11:28:22.981 DEBUG - Auth cache not set in the context
11:28:22.981 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:22.981 DEBUG - Connection leased: [id: 3][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:22.981 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:22.982 DEBUG - Connecting to /0.0.0.0:54576
11:28:27.988 DEBUG - http-outgoing-3: Shutdown connection
11:28:27.989 DEBUG - Connection discarded
11:28:27.989 DEBUG - Connection released: [id: 3][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:27.989 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:28.490 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:28.490 DEBUG - CookieSpec selected: default
11:28:28.491 DEBUG - Auth cache not set in the context
11:28:28.493 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:28.493 DEBUG - Connection leased: [id: 4][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:28.493 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:28.493 DEBUG - Connecting to /0.0.0.0:54576
11:28:33.499 DEBUG - http-outgoing-4: Shutdown connection
11:28:33.499 DEBUG - Connection discarded
11:28:33.500 DEBUG - Connection released: [id: 4][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:33.500 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:34.001 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:34.002 DEBUG - CookieSpec selected: default
11:28:34.003 DEBUG - Auth cache not set in the context
11:28:34.003 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:34.003 DEBUG - Connection leased: [id: 5][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:34.003 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:34.004 DEBUG - Connecting to /0.0.0.0:54576
11:28:39.007 DEBUG - http-outgoing-5: Shutdown connection
11:28:39.007 DEBUG - Connection discarded
11:28:39.008 DEBUG - Connection released: [id: 5][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:39.008 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:39.512 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:39.513 DEBUG - CookieSpec selected: default
11:28:39.514 DEBUG - Auth cache not set in the context
11:28:39.514 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:39.514 DEBUG - Connection leased: [id: 6][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:39.514 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:39.514 DEBUG - Connecting to /0.0.0.0:54576
11:28:44.517 DEBUG - http-outgoing-6: Shutdown connection
11:28:44.518 DEBUG - Connection discarded
11:28:44.518 DEBUG - Connection released: [id: 6][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:44.518 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:45.021 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:45.023 DEBUG - CookieSpec selected: default
11:28:45.023 DEBUG - Auth cache not set in the context
11:28:45.023 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:45.023 DEBUG - Connection leased: [id: 7][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:45.024 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:45.024 DEBUG - Connecting to /0.0.0.0:54576
11:28:50.028 DEBUG - http-outgoing-7: Shutdown connection
11:28:50.028 DEBUG - Connection discarded
11:28:50.029 DEBUG - Connection released: [id: 7][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:50.029 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out
11:28:50.534 DEBUG - Closing connections idle longer than 100 MILLISECONDS
11:28:50.536 DEBUG - CookieSpec selected: default
11:28:50.536 DEBUG - Auth cache not set in the context
11:28:50.536 DEBUG - Connection request: [route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:50.537 DEBUG - Connection leased: [id: 8][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 1 of 2000; total allocated: 1 of 2000]
11:28:50.537 DEBUG - Opening connection {}->http://0.0.0.0:54576
11:28:50.537 DEBUG - Connecting to /0.0.0.0:54576
11:28:55.540 DEBUG - http-outgoing-8: Shutdown connection
11:28:55.540 DEBUG - Connection discarded
11:28:55.541 DEBUG - Connection released: [id: 8][route: {}->http://0.0.0.0:54576][total kept alive: 0; route allocated: 0 of 2000; total allocated: 0 of 2000]
11:28:55.541 DEBUG - Failed to check status of node: Connect to 0.0.0.0:54576 [/0.0.0.0] failed: connect timed out

------ NodeConfig Appium JSON -------

{  
   "capabilities":[  
      {  
         "seleniumProtocol":"WebDriver",
         "automationName":"XCUITest",
         "browserName":"MAC",
         "maxInstances":6,
         "udid":"a99511e1IPHONE_UDID",
         "platform":"MAC"
      }
   ],
   "configuration":{  
      "unregisterIfStillDownAfter":60000,
      "role":"node",
      "nodeStatusCheckTimeout":5000,
      "nodeTimeout":120,
      "hubHost":"localhost",
      "hubPort":4444,
      "deviceReadyTimeout":120,
      "timeout":0,
      "url":"http://localhost:54576/wd/hub",
      "nodePolling":500,
      "proxy":"org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
      "cleanUpCycle":5000,
      "hub":"localhost:4444/grid/register",
      "port":"54576",
      "newCommandTimeout":120,
      "browserTimeout":0,
      "maxSession":6,
      "registerCycle":5000,
      "register":true
   }
}

**Comment by barancev** [comment]
There is no route back from the hub to a node, check your network configuration.
