### ISSUE TITLE
Cannot execute JS such that it stays within the driver session

### ISSUE THREAD

**Issue by MirzaSB** [SeleniumHQ/selenium#5394]
OS:  Any OS
Selenium Version:  3.6.0
Browser:  Any browser, but I used Chrome.
Browser Version:  Latest

## Expected Behavior -
JS code should stay during the driver session.

## Actual Behavior -
Every time a JS is injected/executed via the driver, it resets itself, and the data pertaining to it is never stored.

## Steps to reproduce -
1. Via code, invoke a Chrome browser.
2. Execute the following code:
`JavascriptExecutor executor = (JavascriptExecutor) driver;
execute.executeScript("var x = 2;");
Object x = execute.executeScript("return x;");`
3. Observe the exception that is thrown. 
In the third line, an error is thrown. When the expected result should be that 2 is returned.

## Notes:
This is an issue as we cannot setup event listeners to ensure that certain events are triggered based on webdriver actions.

**Comment by twalpole** [comment]
Your variables are going out of scope, you need to assign them on a global object, like

    JavascriptExecutor executor = (JavascriptExecutor) driver; execute.executeScript("window.x = 2;"); Object x = execute.executeScript("return window.x;");

**Comment by MirzaSB** [comment]
@twalpole 

Thank you. I will try it out tomorrow, and if it works, I will close the ticket.
