### ISSUE TITLE
Driver does not support setting HTML5 geolocation information. Use the HasLocationContext property to test for the driver capability.

### ISSUE THREAD

**Issue by sisillV** [SeleniumHQ/selenium#5395]
OS:  Win 10
Selenium Version:  v 3.8.0
Browser:  Internet Explorer (Selenium.WebDriver.IEDriver 3.8.0 c#)

Browser Version:  Internet Explorer 11.2007.14393.0

## Expected Behavior -
I try to get performance value from IEDriver:
IJavaScriptExecutor jsExec = (IJavaScriptExecutor)driverInterface;

            var res = jsExec.ExecuteScript(@"var timings = window.performance.timing || {};
                                                                  return timings;");
And I expect to have results like:

{[connectEnd, 1516952763573]}
{[connectStart, 1516952763573]}
{[domComplete, 1516952764559]}
{[domContentLoadedEventEnd, 1516952764527]}
{[domContentLoadedEventStart, 1516952764413]}
{[domInteractive, 1516952764413]}
{[domLoading, 1516952763654]}
{[domainLookupEnd, 1516952763573]}
{[domainLookupStart, 1516952763573]}
{[fetchStart, 1516952763573]}
{[loadEventEnd, 1516952764560]}
{[loadEventStart, 1516952764559]}
{[navigationStart, 1516952761624]}
{[redirectEnd, 0]}
{[redirectStart, 0]}
{[requestStart, 1516952763575]}
{[responseEnd, 1516952763697]}
{[responseStart, 1516952763648]}
{[secureConnectionStart, 0]}
{[unloadEventEnd, 0]}
{[unloadEventStart, 0]}

## Actual Behavior -
I have error. The most "meaningful" error message that I found was:

Message:	"Driver does not support setting HTML5 geolocation information. Use the HasLocationContext property to test for the driver capability"

Please help me with this!

## Steps to reproduce -
Run script for IE driver:

IJavaScriptExecutor jsExec = (IJavaScriptExecutor)driverInterface;

            var res = jsExec.ExecuteScript(@"var timings = window.performance.timing || {};
                                                                  return timings;");

**Comment by diemol** [comment]
This does not sound as a Selenium bug but a "how do I do this with Selenium" issue. Please bear in mind that this is an issue tracker and not a forum. Here are the [communication channels](https://www.selenium.dev/support/) that can be used to reach out for help.
