### ISSUE TITLE
HTTP Authentication in Chrome WebDriver

### ISSUE THREAD

**Issue by robertmoral** [SeleniumHQ/selenium#5396]
## HTTP Authentication in Chrome
OS:  
Windows 10
Selenium Version:  
2.47
Browser:  
Chrome 64

I would like to ask if Chrome webdriver supports HTTP Authenticaion. Age ago I used Firefox web driver and there was needed to set up  some extra parameter into profile. But what about Chrome?
 
syntax is: 
   username:password@url

Thanks much for any help.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by mukeshtiwari1987** [comment]
@robertmoral I tested https://the-internet.herokuapp.com/basic_auth on a local Windows 10 - Chrome 64 with Selenium version 2.47.0. It worked.
