### ISSUE TITLE
ElementNotInteractableException is not thrown when click() is called, despite WebElement.isVisible() returning false

### ISSUE THREAD

**Issue by xplolel** [SeleniumHQ/selenium#5397]
OS:  
Windows 10
Selenium Version:  
3.7.1 Grid(RemoteWebDriver)    JAVA
Browser:  
Firefox

Browser Version:  
57.0 (64-bit)

A regular radiobutton(<input type='radiobutton' name='...'/>) is placed on the website, the frame is properly selected and overall interaction with the every html input (including the one that that does not work later) works. 

BUT

When the WebElement radioButton's click() method is called...

## Expected Behavior -
if element is visible {Radiobutton in being selected}// that case works
else {an exception ElementNotInteractableException or any inheriting one should be thrown}

## Actual Behavior -
if element is visible {Radiobutton in being selected}// that case works
else {nothing happens}

IMPORTANT: radioButton.isVisible() works properly, checking this condition before selection and optional scroll to the element solves the issue, however a bypass is required to make it work.
I believe an exception should be thrown

## Steps to reproduce -

Pseudocode:
map webelement -> try to interact with it when it's visible;
scroll the page, so that the element that is being tested would not be visible;
check if the interaction with the element causes an exception(IT SHOULD) and check webElement.isVisible() output;

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
