### ISSUE TITLE
Difference in serialization of Capabilities between Dotnet and Java bindings causes issues connecting to Saucelabs

### ISSUE THREAD

**Issue by AgentMC** [SeleniumHQ/selenium#5398]
## Meta - 
OS:  Windows 10
Selenium Version:  3.8.0
Browser:  Chrome latest

## Expected Behavior -
For constructed in a default manner instance of ChromeOptions, serializers across language bindings must follow the same conventions.
## Actual Behavior -
dotnet bindings generate an empty `goog:chromeOptions` property which cannot be properly initialized by SauceLabs.
## Steps to reproduce -
Consider the following source code
```
    class Program
    {
        static void Main(string[] args)
        {
            var options = new ChromeOptions();
/*!*/       options.AddUserProfilePreference("credentials_enable_service", false);
/*!*/       options.AddUserProfilePreference("profile.password_manager_enabled", false);
            var caps = options.ToCapabilities() as DesiredCapabilities;
            caps.SetCapability("username", "my_user_name");
            caps.SetCapability("accessKey", "my-access-key-as-guid");
            using (var driver = new RemoteWebDriver(new Uri("http://ondemand.saucelabs.com:80/wd/hub"), caps, TimeSpan.FromSeconds(840)))
            {
                driver.Url = "http://www.google.com";
            }
        }
    }

```
This code runs perfectly fine. Same goes for it's Java equivalent.
However, if I remove both of marked calls to `options` object, the `RemoteWebDriver` instance throws an exception on creation. The identical Java code still runs fine.
Here are logs from runs on both languages with both calls to `options` removed:

 - Java (works): https://saucelabs.com/beta/tests/2ff94b46a0064fd39c9e2cbe9e295839/logs#0
```
{
    "screenshot": 0,
    "between_commands": null,
    "suggestion_values": [],
    "request": {
      "desiredCapabilities": {
        "goog:chromeOptions": {
          "binary": "D:\\Program Files\\Chrome 63\\63.0.3239.84\\chrome.exe",
          "args": [],
          "extensions": []
        },
        "javascriptEnabled": true,
        "chromeOptions": {
          "binary": "D:\\Program Files\\Chrome 63\\63.0.3239.84\\chrome.exe",
          "perfLoggingPrefs": {
            "enableNetwork": true,
            "enablePage": true
          },
          "args": [
            "start-maximized",
            "disable-webgl",
            "blacklist-webgl",
            "blacklist-accelerated-compositing",
            "disable-accelerated-2d-canvas",
            "disable-accelerated-compositing",
            "disable-accelerated-layers",
            "disable-accelerated-plugins",
            "disable-accelerated-video",
            "disable-accelerated-video-decode",
            "disable-gpu",
            "disable-infobars",
            "test-type",
            "disable-extensions",
            "remote-debugging-port=64535"
          ]
        },
        "browserName": "chrome",
        "loggingPrefs": {
          "performance": "ALL",
          "driver": "ALL",
          "browser": "ALL"
        }
      }
    },
```
 - C# (doesn't work): https://saucelabs.com/beta/tests/d1e319ac6f64438b87420abf341c0daa/logs#0
```
{
    "screenshot": 0,
    "between_commands": null,
    "suggestion_values": [],
    "request": {
      "desiredCapabilities": {
        "goog:chromeOptions": {},
        "deviceName": "",
        "browserName": "chrome",
        "chromeOptions": {
          "binary": "D:\\Program Files\\Chrome 63\\63.0.3239.84\\chrome.exe",
          "args": [
            "start-maximized",
            "disable-webgl",
            "blacklist-webgl",
            "blacklist-accelerated-compositing",
            "disable-accelerated-2d-canvas",
            "disable-accelerated-compositing",
            "disable-accelerated-layers",
            "disable-accelerated-plugins",
            "disable-accelerated-video",
            "disable-accelerated-video-decode",
            "disable-gpu",
            "disable-infobars",
            "test-type",
            "disable-extensions"
          ]
        }
      }
    },
```

My understanding is that Java serializes child properties allowing SL to set what it needs, e.g. chromeBinary. On contrary, C# leaves empty object, so SL cannot initialize it the expected way.

Disclaimer: I don't work for SL, and this is all info I have from the support ticket. Right now we working this around by calling those preferences.

**Comment by jimevans** [comment]
@AgentMC I'm simulating this with `RemoteWebDriver` by using the following code:

    using (ChromeDriverService service = ChromeDriverService.CreateDefaultService())
    {
        service.Port = 7777;
        service.Start();
        ChromeOptions options = new ChromeOptions();
        options.AddUserProfilePreference("credentials_enable_service", false);
        options.AddUserProfilePreference("profile.password_manager_enabled", false);
        DesiredCapabilities caps = options.ToCapabilities() as DesiredCapabilities;
        caps.SetCapability("username", "myusername");
        caps.SetCapability("accesscode", "myaccesscode");
        IWebDriver driver = new RemoteWebDriver(new Uri("http://localhost:7777"), caps);
        driver.Quit();
    }

Here's the actual JSON sent over the wire from the .NET bindings when you set the options in the `ChromeOptions` class:

    {
      "desiredCapabilities": {
        "browserName": "chrome",
        "goog:chromeOptions": {
          "prefs": {
            "credentials_enable_service":false,
            "profile.password_manager_enabled":false
          }
        },
        "username":"myusername",
        "accesscode":"myaccesscode"
      }
    }

And when you don't:

    {
      "desiredCapabilities": {
        "browserName": "chrome",
        "goog:chromeOptions":{},
        "username":"myusername",
        "accesscode":"myaccesscode"
      }
    }

This is the raw, unadulterated JSON payload of the new session command from the .NET bindings. As you can see, there are some significant differences in what is being sent over the wire from the bindings and what SauceLabs is reporting, including munging things to include arguments for the browser. The .NET bindings have now standardized on `goog:chromeOptions` in keeping with [modern chromedriver implementations](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1786) and as a future-proofing for the chromedriver compliance with the W3C WebDriver specification. The `chromeOptions` capability is now only supported for compatibility. In any case, there is no requirement that either `chromeOptions` or `goog:chromeOptions` have a value object that has any properties at all, or that the capability even exist in the request. If SauceLabs is expecting something different, that's making unwarranted assumptions about the payload they receive.

**Comment by titusfortner** [comment]
If `goog:chromeOptions` is present, chromedriver will prefer it, so everything in your log files above in `chromeOptions` will be ignored. 

The difference between Java & C# right now is that Java sends by default: `"goog:chromeOptions":{"args":[], "extensions":[]}"` and C# sends `"goog:chromeOptions":{}`. Currently Sauce is ignoring empty values, which means that the browser location is not getting included in the signature that chromedriver is looking for.

@AgentMC can you send me a link to the Sauce issue you alluded to? titus@saucelabs.com

We're working on a fix, but the temp solution is to make sure something is always getting passed in.

Closing because this isn't a Selenium issue.

**Comment by AgentMC** [comment]
Done, thx for looking into this @titusfortner
