### ISSUE TITLE
Driver randomly becomes unresponsive with Chrome v64

### ISSUE THREAD

**Issue by brandonschabell** [SeleniumHQ/selenium#5399]
## Meta -
OS:  
Linux - Ubuntu 14.04
Selenium Version:  
3.8.1
Browser:  
Chrome
Browser Version:  
64.0.3282.119 (64-bit)
Chromedriver Version:
2.35

## Expected Behavior -
WebDriver should be consistently responsive

## Actual Behavior -
WebDriver methods occasionally hang, causing the test runner to seize up.

## Steps to reproduce -
When calling methods belonging to the Selenium.WebDriver class, the driver randomly becomes unresponsive. I have a fairly simple test that does the following:

```
driver.get(SOME_PAGE);
driver.manage().addCookie(new Cookie("auth", SESSION_ID);
driver.manage().logs();
```

I run the test 240 times using CircleCI, and it fails once or twice, at any of those 3 methods. The error is always the same:

> 
> [1517000354.693][SEVERE]: Timed out receiving message from renderer: 15.000 
> [1517000354.695][SEVERE]: Timed out receiving message from renderer: -0.003

This started as soon as Chrome v.64 was released, so it's possible that it is just a Chrome bug, but I haven't seen anyone complain about it except for those using Selenium.

**Comment by lmtierney** [comment]
This appears to be chrome/chromedriver related.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)
