### ISSUE TITLE
Returning a recursive structure from executeScript() hangs/crashes browser

### ISSUE THREAD

**Issue by lqc** [SeleniumHQ/selenium#540]
The documentation of `executeScript()` and `executeAsyncScript()` does not contain any information how recursive structures are handles and that's because they _aren't_.

In Firefox, an attempt to return a recursive structure briefly hangs the browser and then the command silently fails without ever returning, i.e. the test script is blocked forever as it waits for the Firefox extension to return anything.

On Internet Explorer, this usually leads to a crash.

Selenium version: 2.43.1

**Comment by lqc** [comment]
A related W3C spec bug report: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26137

**Comment by barancev** [comment]
Atoms fixed by commit 0fd840096fec20363daef3161a825e937b8bdc7e

**Comment by barancev** [comment]
Related geckodriver issue: https://github.com/mozilla/geckodriver/issues/914

**Comment by barancev** [comment]
Checked to work well in Marionette: e4ad062623ad30652955302df979443c5770077c
Fixed in legacy Firefox driver: c86d229ddf28d7e0b789ce136ebe5ed0e1bdc1b4

**Comment by barancev** [comment]
It seems to be implemented in IE too, the corresponding test passes.
