### ISSUE TITLE
[Node JS API] What's the point of the weakmap in exec.js...?

### ISSUE THREAD

**Issue by mercmobily** [SeleniumHQ/selenium#5400]
In exec.js, I can see:

    const COMMAND_RESULT = /** !WeakMap<!Command, !Promise<!Result>> */new WeakMap;
    const KILL_HOOK = /** !WeakMap<!Command, function(string)> */new WeakMap;

    class Command {
        constructor(result, onKill) {
          COMMAND_RESULT.set(this, result);
          KILL_HOOK.set(this, onKill);
        }
        // ...
    }

Why the Weakmap?
I mean, why not just:

    class Command {
        constructor(result, onKill) {
          this.result = result
          this.onKill = onkill
        }
        // ...
    }

...?

**Comment by jleyba** [comment]
Restricts the visibility of those variables making them only accessible within the module.

**Comment by mercmobily** [comment]
You seem to have gone to great lengths to keep those private. Any specific reason why they are so well-kept, and not many of the other variables ending with `_`?

**Comment by jleyba** [comment]
No particular reason, just an inconsistent style on my part.
