### ISSUE TITLE
Issue with chrome driver not able to switch to frame

### ISSUE THREAD

**Issue by prasannarhegde2015** [SeleniumHQ/selenium#5401]
## Meta -
OS:  Windows 10

Selenium Version:   2.53

Browser:  Chrome

Browser Version:  

Version 64.0.3282.119 (Official Build) (64-bit)
## Expected Behavior -
While Switching to Frame it should switch to desired Frame using xpath given
## Actual Behavior -
Fails to switch to desired frame directly using xpath
## Steps to reproduce -

No specific step code was working fine till **chrome driver version 2.29** on **chrome version 62.00**
and works fine on IE driver as well with same code
Now after using **chrome driver 2.35** with chrome version **64**,  I see the issue
I googled and found same issue reported earlier and closed 

[Similar old issue that was closed ](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/1969)

If i use the workaround suggested in same thread I see it works 
ie Find Frame by its xpath 
then again switch to same frame by using getattribute id 
something like:

```
WebElement frame = drv.findElement(By.xpath("//iframe[@title='...']"));
		drv.switchTo().frame(frame.getAttribute("id"));
```

This used to work in older chrome driver 2.29 and below with chrome version 62 and below
and still works on Internet explorer driver.
`wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.id("..")));`

Please confirm if this is issue
Let me know if threre are plans to fix this so that I may twaek my framework accordingly

**Comment by cgoldberg** [comment]
that example code you said is for a workaround?  so what is the actual issue being reported here?
can you give a repro case?

**Comment by lmtierney** [comment]
What problem are you seeing? Are you getting an error? There was a new bug in chromedriver that isn't waiting for content to load into the iframe before attempting to interact with it, is that what you're seing?

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198

**Comment by prasannarhegde2015** [comment]
Hi please find sample code along with output on Chrome driver 2.29 and 2.35
You can see 2.35 fails with timeout due to it canot find element either it switched to wrong frame or did not switch to frame at alll
![driver2 35](https://user-images.githubusercontent.com/14150820/35495560-6e3e8ef8-04e7-11e8-8c88-69d2bf5f7d2b.PNG)
![driver2 29](https://user-images.githubusercontent.com/14150820/35495573-7ff0e632-04e7-11e8-8a0d-869cd382b3ba.PNG
I hope this should make things clear

**Comment by barancev** [comment]
Please provide code as a text, not a picture. And we need a sample page that can be usedd to reproduce the issue.

**Comment by prasannarhegde2015** [comment]
Hi please find the code

``


package com.test.driver;

import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class TestDriver {
	public static String chromedriverpath="D:\\Download\\Port\\Driver\\chromedriver_2.29\\"
			+ "chromedriver.exe";
	public static WebDriverWait wait;
	public static String baseurl="https://dev23478.service-now.com";
	
	
	public static void main(String[] args)
	{
		
		System.setProperty("webdriver.chrome.driver", chromedriverpath);
		ChromeOptions options = new ChromeOptions();
		options.addArguments("chrome.switches","--disable-extensions");
		options.addArguments("chrome.switches","--disable-infobars");
		Map<String, Object> prefs = new HashMap<String, Object>();
	    prefs.put("credentials_enable_service", false);
	    prefs.put("profile.password_manager_enabled", false);
	    options.setExperimentalOption("prefs", prefs);
	    ChromeDriver drv = new ChromeDriver(options);
	    wait = new WebDriverWait(drv, 30);
		drv.get(baseurl);
		drv.manage().window().maximize();
		WebElement frm0 = drv.findElement(By.id("gsft_main"));
		drv.switchTo().frame(frm0);
		drv.findElement(By.id("user_name")).sendKeys("####");
		drv.findElement(By.id("user_password")).sendKeys("######");
		drv.findElement(By.id("sysverb_login")).click();
		drv.switchTo().defaultContent();
		
		//================================================
		wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.xpath("//iframe[@title='Navigation Content']")));
		wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//h2[contains(text(),'10 Things')]")));
		System.out.println("***************done*****************");
		


''
Above is working code in 2.29
Now same code fails in 2.35

**Comment by barancev** [comment]
Unfortunately, the scenario can't be run without login and password. Please provide a publically available sample page that can be used to reproduce the issue.

**Comment by prasannarhegde2015** [comment]
Please use 
Username : chrome235
Passed: test@123
Let me know if you can see issue..
Also make sure you use selenium 2.53

**Comment by prasannarhegde2015** [comment]
Url  dev23478.service-now.com should be publicly accessible

**Comment by prasannarhegde2015** [comment]
Hi Any update on issue ?
Let me know if you were able to connect to url provided
If mine is  not working  you can create your own developer instance for service now free
from "https://developer.servicenow.com/app.do#!/home"

and try to execute same code

Let me know still if you see this issue or not
For me it appears like dynamic wait statements are failing when inside Frame

**Comment by FA-tvonmoll** [comment]
Possibly [this one] from chromedriver(https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198&q=frame&colspec=ID%20Status%20Pri%20Owner%20Summary)?

**Comment by prasannarhegde2015** [comment]
Yes Appears to be same issue.....but can confirm only if issue gets fixed...I have given code to reproduce..and portal details also ...waiting for new version of Chrome driver hoping it will get resolved

**Comment by erchristopher** [comment]
This is still an issue. Tested with latest chrome driver 74. When we have iFrame directly under body, chrome - though it switches - is unable to identify the elements within the iFrame. The same is working fine in FF. I modified the HTML from <body><iFrame></iFrame></body> to <body><div><iFrame></iFrame></div></body> BOTH Chrome and FF worked fine!!!

**Comment by GulshanK** [comment]
Is there a solution to this issue ? I have a similar issue where buttons within a frame aren't working on Chrome 73.

**Comment by erchristopher** [comment]
> Is there a solution to this issue ? I have a similar issue where buttons within a frame aren't working on Chrome 73.

The only option i had was to put the iFrame into a DIV (it can be an empty DIV too, so dev should be ok to do that - i guess ) 

<body>**<div>**<iFrame></iFrame>**</div>**</body>

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver
