### ISSUE TITLE
Selenium 3.8.1 : Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Snigdhaa** [SeleniumHQ/selenium#5403]
Windows 8
Eclipse : Version: Oxygen.2 Release (4.7.2)
Selenium " 3.8.1"
Gecko driver : geckodriver-v0.19.1-win32
Firefox : 51.0.1 (32-bit)

Error : Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities

please suggest

**Comment by barancev** [comment]
According to the release notes [1], geckodriver 0.19 supports Firefox 55+

[1] https://github.com/mozilla/geckodriver/releases

**Comment by Snigdhaa** [comment]
thanx @barancev issue resolved just depreciated the browser
