### ISSUE TITLE
Continue WebDriver test execution, when element is not visible/clickable

### ISSUE THREAD

**Issue by plaidshirtakos** [SeleniumHQ/selenium#5407]
## Meta -
OS:  
Windows 8.1
Selenium Version:  
WebDriver 3.8.1

I have a Selenium WebDriver based testsuite. XPATH on site are changing sometimes, so I would like to use this to identify which XPATH has to be refreshed. So in case element isn't visible or not clickable, it should write to log currently executed class and method name with an error message. So test should be continued in case of failure.

## Expected Behavior -
Testsuite execution should be continued in case of non visible/non clickable elements. Errors should be logged to console or in file.

## Actual Behavior -
Execution fails on every missing/not visible elements.

**Comment by lmtierney** [comment]
Selenium is just an API for interacting with the browser, it is not a test framework. You have to handle exceptions in your test suite by yourself
