### ISSUE TITLE
How to Handle "Select a Certificate popup" in chrome browser for Selenium Java

### ISSUE THREAD

**Issue by vatsa9902** [SeleniumHQ/selenium#5408]
## Meta -
OS:  
Windows 7

Selenium Version:  
2.33 

Browser Version:  
Chrome v63.0.3239.132

## Steps to reproduce -
Launch the application which has security certificate associated. On launching we get "Select a Certificate popup" . How to avoid this and how to handle this.

Tried adding the certificate to trusted source dint work 

Please find the screenshot attached for the screen obtained.

![image](https://user-images.githubusercontent.com/35960104/35566835-d6e761ee-05e8-11e8-8fd8-7b57f9859b3d.png)

**Comment by luke-hill** [comment]
You are using a version of Selenium that is seriously beyond support.

If you insist on using the 2.x series, you have to be using 2.53 (Last 2.x version).

Otherwise try upgrade to at least selenium 3.7+ Especially if you're running a new version of chrome (v63)

**Comment by Karthi96** [comment]
How to resolve this? Still unable to resolve that?

**Comment by JobaDiniz** [comment]
> You're interacting with a pop-up which is out of the remit of browser automation directly. I'd look into additional packages that can assist you there

That's reasonable, however, the problem is that when we do
```
line 1: Navigate().GoToUrl(...); //Select Certificate is shown
line 2: //code to interact with the Windows Popup
```
The **line 2** is never reached when the _Select Certificate_ popup is shown, therefore, we cannot interact with it. 
Any ideas?

**Comment by Pfheonix** [comment]
INavigation.GoToUrl() is blocking. That means line 2 will not be reached because GoToUrl() waits until the loading is completed.

`1:  Task.Run(() => driverObject.Navigate().GoToUrl());
 2: //Other code which will run while that waits. `

The above "works," but I am not sure that it is reliably useful.

**Comment by JobaDiniz** [comment]
The main problem is that any action can trigger the popup, eg .Click() can trigger a navigation and that navigation can show the popup. So far there is not an actual solution other than what you proposed

**Comment by Pfheonix** [comment]
Very true. But you know your environment, as this is a test situation, and you should know your environment as well as can be expected given what closed source applications you may need to work with. You should know where the navigation should be expected to occur and reduce the testing as much as feasible to prevent navigation which requires a re-authentication. Or, better yet, make the framework asynchronous through expansion in your own project, then await when you have made too much progress to be able to continue without the return of the task. That's what the await is there for. Hell, await everything and check if there may be a pop up. If the title is stuck on "Loading..." after a timeout, perform the selection action. If it's not, you're probably good.
