### ISSUE TITLE
[py][chrome] raises log_type client on remote node with chrome browser

### ISSUE THREAD

**Issue by netzulo** [SeleniumHQ/selenium#5410]
## Meta -
OS:  **Windows NT 10.0.16299 x86_64**
Selenium Version:  **3.5.0** _( ``pip install selenium`` https://pypi.python.org/pypi/selenium )_
Browser:  **CHROME**
Browser Version:  **64.0.3282.119**

## Expected Behavior -

* log_type client working for chrome browsers **or** deleting this log_type _(client)_ from documentation

#### Documentation used

http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.get_log

##### Java doc :
https://seleniumhq.github.io/selenium/docs/api/java/constant-values.html#org.openqa.selenium.logging.LogType

#### Test

``` python 
# opened CHROME 2.33 browser on WIN10 64bits
log_type = 'client'
driver.get_log(log_type) # this lanes raises error
```
- *PASSED* when _log_type_ is *browser* get an array
- *PASSED* when _log_type_ is *driver* get an array
- *FAILED* when _log_type_ is *client* must get an array
- *PASSED* when _log_type_ is *server* get an array

#### Stacktrace

```
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
            raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: unknown error: log type 'client' not found
E         (Session info: chrome=64.0.3282.119)
E         (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64)

c:\users\cronosadmin\envs\qacode\lib\site-packages\selenium-3.5.0-py3.6.egg\selenium\webdriver\remote\errorhandler.py:194: WebDriverException
```

## Steps to reproduce -
* Open chrome browser  using *hub+node* to open on remote node
* try to print to console `driver.get_log('client')` _hey! got the hole!_

- [ ] *sure about* | google chrome issue , https://sites.google.com/a/chromium.org/chromedriver/help
- [ ] *sure about* | selenium grid library issue _(it's on java, i want to test python)_
- [ ] *sure about* | selenium python library issue
- [x] *sure about* | all get_log type are working for the same browser session
- [x] *sure about* | all get_log type are working on win/linux
- [x] *sure about* | all get_log type are working on 32/64 bits
- [x] *sure about* | all get_log type are working different on another browsers , is not conclusive
- [x] *sure about* | my library issue , https://github.com/netzulo/qacode

**Comment by cgoldberg** [comment]
> Documentation used

just an FYI...
The linked docs are not the official Python API docs from Selenium project.
Official API docs are here: https://seleniumhq.github.io/selenium/docs/api/py/api.html

**Comment by netzulo** [comment]
@cgoldberg  FYI , i knewt it so... same result : https://seleniumhq.github.io/selenium/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html#selenium.webdriver.remote.webdriver.WebDriver.get_log

**Comment by lmtierney** [comment]
The available log types can be retrieved via the `log_types` WebDriver method, this is what should be used when determining what is available.

> FAILED when log_type is client must get an array

I don't know where this requirement came from?

**Comment by netzulo** [comment]
readed here too : https://seleniumhq.github.io/selenium/docs/api/java/constant-values.html#org.openqa.selenium.logging.LogType

**Comment by lmtierney** [comment]
Closing this as all log types are not guaranteed to be there. Check which ones are available via the `log_types` command before attempting to retrieve.

**Comment by netzulo** [comment]
@lmtierney then, just need validate, it's different for each browser and selenium mode ? ( local drivers or remote drivers )

**Comment by lmtierney** [comment]
It can be yes. For instance, you wouldn't be able to get `server` using just the chrome webdriver. And I believe `browser` is only currently available with chrome, although there are plans to add it to the w3c spec later.

**Comment by netzulo** [comment]
maybe need to be documented :) so thank you for help, ill handle then! ^^ @lmtierney
