### ISSUE TITLE
Not able to find Element

### ISSUE THREAD

**Issue by sjdptn** [SeleniumHQ/selenium#5414]
Eclipse: Oxygen forJAVA EE Developers
Selenium: 3.7.1
Appium: 1.7.1
testing device: ios Simulator

Code 
package appium;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

public class NewTest {
	@SuppressWarnings({ "rawtypes" })
	private IOSDriver driver;

  @SuppressWarnings("rawtypes")
@Test
  public void first() throws MalformedURLException, InterruptedException {
	  DesiredCapabilities caps = new DesiredCapabilities();
	  caps.setCapability("platformName", "iOS");
	  caps.setCapability("platformVersion", "11.0"); 
	  caps.setCapability("deviceName", "iPhone 7"); 
	  caps.setCapability("automationName", "XCUITest");
	  caps.setCapability("app", "/Users/preeti/Library/Developer/Xcode/DerivedData/Kiosk-cqqwwmdzdfarneanaqslqyqicatp/Build/Products/Debug-iphonesimulator/Kiosk.app"); 
	  driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	  driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	  driver.findElementByAccessibilityId("SKIP").click();
	  driver.findElement(By.xpath("//XCUIElementTypeButton[1]")).click();
	  driver.findElementByAccessibilityId("Cheeses").click();
	  driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	  driver.findElementByAccessibilityId("BOAR'S HEAD LACEY SWISS CHEESE $11.99/lb. now $5.49/lb.").click();
	  
	
	  
	  
	  
	 
  }

}

Failure:
It is failing at the last step even when the element is present and also trying to locate the element using the accessibility id found through appium inspector

**Comment by maeriens** [comment]
This is an Appium question - and they have requested you [more information about it](https://github.com/appium/appium/issues/10104) :)
