### ISSUE TITLE
Autodetect proxy error with Selenium 3.8.1 + firefox 58 + gecko .19

### ISSUE THREAD

**Issue by ianantha** [SeleniumHQ/selenium#5417]
I am using Selenium 3.8.1 + firefox 58 + gecko .19.

My code snippets looks as below.

            FirefoxProfile profile = new FirefoxProfile();
            profile.setAcceptUntrustedCertificates(true);
            profile.setAssumeUntrustedCertificateIssuer(false);
            profile.setPreference("browser.download.useDownloadDir", true);
            profile.setPreference("browser.download.folderList", 0);
            profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/xml");
            profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/zip");
            profile
                .setPreference(
                    "browser.helperApps.neverAsk.saveToDisk",
                    "application/x-xpinstall;application/x-zip;application/x-zip-compressed;application/octet-stream;application/zip;application/pdf;application/msword;text/plain;application/octet");
            profile.setPreference("browser.helperApps.alwaysAsk.force", false);
            profile.setPreference("browser.download.manager.showWhenStarting", false);

            
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities = DesiredCapabilities.firefox();
            capabilities.setCapability(FirefoxDriver.PROFILE, profile);
            capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);

            // set to not use a proxy
            Proxy seleniumProxyConfig = new Proxy();
            seleniumProxyConfig.setProxyType(ProxyType.DIRECT);
            capabilities.setCapability(CapabilityType.PROXY, seleniumProxyConfig);
            capabilities.setCapability(CapabilityType.ForSeleniumServer.AVOIDING_PROXY, true);

            logger.info("URL Being opened is:" + url);
            driver = new CustomRemoteWebDriver(new URL(url), capabilities);

            // driver.manage().window().maximize();

            // THIS SCREWS UP TEST EXECUTION for some reason
            driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);

            ResourceManager.addResource(WEBDRIVER_RESOURCE_NAME, driver);

When i run the the test, i get the below error.

“autodetect is not a valid proxy configuration capability”
Using he proper gecko driver and command accordingly “start java -Djava.io.tmpdir=c:\selenium\temp -Dwebdriver.gecko.driver=geckodriver.exe -jar c:\selenium\selenium-server-standalone-3.8.1.jar” 

If i remove the proxy code then my firefox is dead.

Can someone help me on this please

**Comment by jtolotta** [comment]
I had an issue with Selenium 3.8.1 and OpenJDK 8 on Linux Mint with Proxy settings.
However, Selenium 3.8.1 and Oracle JDK 8 on Windows with Proxy settings was fine.
Could be isolated to just me, so I didn't want to raise an issue.

Rolling back to 3.8.0 fixed it for this case.

**Comment by barancev** [comment]
Can you please strip configuation to as simple as possible to reproduce the issue: no CustomRemoteWebDriver, just plain local FirefoxDriver, a default profile, is the issue still actual?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
