### ISSUE TITLE
server timeouts seem to be broken?

### ISSUE THREAD

**Issue by josh-walker** [SeleniumHQ/selenium#5418]
## Meta -
OS:  Linux, Win7
Selenium Version:  
3.8.1, 3.6.0
Browser:  
FF, Chrome, IE
Browser Version:  
FF 57
Chrome 63
IE11

## Expected Behavior -
I expect the browser sessions  to eventually be killed when the tests hang and can't deliberatly quit().

## Actual Behavior -
Sessions just sit around forever until I close them manually or reboot the machine.

## Steps to reproduce -
run the server like this:
`#!/bin/bash
java -Dwebdriver.chrome.driver=drivers/linux/chromedriver -jar lib/selenium-server-standalone-3.6.0.jar -port 4466 -timeout 60 -browserTimeout 60
`

then connect to http://localhost:4466/wd/hub/static/resource/hub.html and create a new chrome session.

You can wait as long as you like, the session will not be cleaned up.

I'm aware that there's some confusion about whether those numbers are millis, seconds or minutes, so I tried appropriate values for all of them and none seem to work.

And if I omit the timeout params, the default 30m timeout also does not kill the browser instances.

**Comment by joerg1985** [comment]
We are using the standalone server in an windows environment and have the same issue.

A lot of people just hit stop in jenkins and after a view days we need to restart windows to get rid of all these zombie sessions / processes.

This is the command we are using to start the server: 
`java -jar selenium-server-standalone-3.8.1.jar -port 5555 -timeout 3600`

**Comment by diemol** [comment]
Hi @josh-walker @joerg1985 
Yes, `browserTimeout` was not working properly. This got fixed in https://github.com/SeleniumHQ/selenium/commit/3f20f9f2ecb8ddd0ef13c2c17f1f46adaeb762a6 and it will be available in the next release.

**Comment by FzmTYustas** [comment]
Is the fix suitable for timeout (in additional browser_timeout)?
