### ISSUE TITLE
org.openqa.selenium.TimeoutException: timeout when navigating within the same page using a URL with the element part

### ISSUE THREAD

**Issue by baflQA** [SeleniumHQ/selenium#5419]
## Meta -
OS: Linux
Selenium Version:  3.8.1 - both Hub and Node 
Browser:  Chrome
Chrome driver: 2.35
Browser Version:  Chrome 64.0.3282.119

## Expected Behavior 
Driver is navigating to the page.
## Actual Behavior -
Timeout exception is thrown.
## Steps to reproduce -
Set up simplest grid - hub and node with the default config running on the same machine (You can use docker images, or selenium standalone servers).
Create a new Remote Driver instance. 

Run below test:
```
@Test
	public static void test() {
	final String docs = "seleniumhq.org/docs/";
	driver.get(docs + "01_introducing_selenium.jsp");
	driver.get(docs + "01_introducing_selenium.jsp#introducing-selenium");
	}
```

The last line will throw a Timeout Exception.

This test will pass using the IDE or the standalone server.

**Comment by barancev** [comment]
See https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239

**Comment by baflQA** [comment]
Thank You very much for Your immediate response. 
Btw - how come You track every issue on every project related to the Selenium project? :P
