### ISSUE TITLE
requests for Operablink returns Capabilities with browserName of "chrome"

### ISSUE THREAD

**Issue by anyway1021** [SeleniumHQ/selenium#542]
We have a mechanism to classify the browser types tested, and put them into charts to display within a dashboard, so we rely on the "browserName" value in Capabilities returned by Selenium Grid. 
However, most browser types work well except for "operablink". Let's say, when we tell grid that we want an "operablink", the grid does trigger an opera instance to test, but the "browserName" returned within Capabilities is "chrome" which confuses our dashboard so that no opera case chart is shown on the page.
I ever searched for this issue, and found Selenium was using chrome-driver to support operablink, this may be the root cause of the bug, and grid developers may say, it's just by design. But from users' perspective, this could be a bug or say a leak of using opera browser. Let's just imagine, we all know we are using opera, but the browserName we get is otherwise "chrome". It seems a bit ridiculous.

**Comment by jleyba** [comment]
> Selenium was using chrome-driver to support operablink

This is incorrect. The latest operadriver, provided by Opera, is based on the chromedriver (as the Opera browser is based on Chromium).  If the operadriver is returning "chrome" for its browser name, then it's a bug with the operadriver not changing the capabilities.  You should file a bug against the operasoftware/operachromiumdriver project.
