### ISSUE TITLE
My selenium source is not correct!

### ISSUE THREAD

**Issue by yagocorbal** [SeleniumHQ/selenium#5425]
When I try to change the Clipboard format on my Selenium IDE from HTML to VBA it doesn't work on the source of the Selenium, just keep showing the HTML as you can see on the attach picture.

**Comment by barancev** [comment]
1) There is no attach picture
2) VBA formatter is a third-party addon
3) "Old" Selenium IDE development is discontinued, we're working on a new implementation, watch this project: https://github.com/SeleniumHQ/selenium-ide
