### ISSUE TITLE
UnknownCommandError: Unrecognized command: actions

### ISSUE THREAD

**Issue by zedwang** [SeleniumHQ/selenium#5428]
## Meta
OS:  Windows 10
Selenium Version:  4.0.0-alpha.1
Browser:  chrome  
Browser Version:    64
  
  
My code snippets looks as below.
```js
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('chrome').build();
  var entrytoEdit = "Browser Stack";
  var toDoTestItems = [entrytoEdit, "Test Value1", "Test Value2"];
    await driver.get('http://todomvc.com/examples/react/#/');
    let query = await driver.wait(until.elementLocated(By.className('new-todo')),1000)
    for (const item of toDoTestItems) {
        await query.sendKeys(item, Key.RETURN);
    }
    const deleteBtn = await driver.findElements(By.css('.filters li'));
    await driver.actions().click(deleteBtn[2]).perform();
})();
```
run
```
(node:7616) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): UnknownCommandError: Unrecognized command: actions
(node:7616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Why is this happening?

**Comment by lmtierney** [comment]
The `4.0.0-alpha.1` version is only compatible with w3c compliant webdrivers (geckodriver, IEDriverServer). It will be compatible with chromedriver once they release their w3c compliant version.

**Comment by kxc1573** [comment]
I get it too，but use ie browser

OS: Windows 10
Selenium Version: 4.0.0-alpha.1
Browser: chrome
Browser Version: 64

My code:
`'use strict';

let webdriver = require('selenium-webdriver');
let until = webdriver.until;
let By = webdriver.By;

let driver = new webdriver.Builder()
    .forBrowser('ie')
    .setIeOptions({})
    .build();


!async function() {
    await driver.get('JUST ONE WEB');

    let frame = await driver.findElement(By.id('conFrame'));
    if (frame) {
        await driver.switchTo().frame(frame);

        console.log(await driver.getCurrentUrl());
        let start = driver.findElement(By.css('.startBtn'));
        await start.click();

        let loginname = await driver.findElement(By.id('loginname'));
        // await driver.actions().move({x: 100, y: 10, origin: loginname}).press().release().perform();
        await driver.actions().click(loginname).perform();
    }

    await driver.sleep(60000);
    await driver.close();
}()`

run
`(node:20644) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): UnknownCommandError: Unrecognized command: actions
(node:20644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ryancat** [comment]
I get it with Firefox browser

OS: Windows 7
Selenium Version: 4.0.0-alpha.1
Browser: Firefox
Browser Version: 59

UnknownCommandError: Unrecognized command: actions
    at buildRequest (/Users/xin.chen/code/aurora/node_modules/selenium-webdriver/lib/http.js:375:9)
    at Executor.execute (/Users/xin.chen/code/aurora/node_modules/selenium-webdriver/lib/http.js:455:19)
    at mixin.execute (/Users/xin.chen/code/aurora/node_modules/selenium-webdriver/lib/webdriver.js:696:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'UnknownCommandError', remoteStacktrace: ''

**Comment by ryancat** [comment]
BTW this actually working locally, however it doesn't work on Saucelabs

**Comment by marcelklehr** [comment]
Those providers are probably not running the latest alpha version.

**Comment by ivytsoi** [comment]
Reporting a similar problem:
OS: Windows 10
Selenium Version: 4.0.0-alpha.1 / 4.0.0-alpha.4
Browser: Chrome
Browser Version: 75

UnknownCommandError: Unrecognized command: actions
      at buildRequest (node_modules/selenium-webdriver/lib/http.js:393:9)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:473:19)
      at Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:699:38)

**Comment by Anish-Agnihotri** [comment]
Reporting a similar problem:
OS: MacOS Catalina 10.15 Beta
Browser: Chrome
Browser Version: 75

```
UnknownCommandError: Unrecognized command: actions
    at buildRequest (node_modules/selenium-webdriver/lib/http.js:393:9)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:473:19)
    at thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:699:38)
```

I had updated to the Alpha to use the new `.dragAndDrop()` functionality on Actions, and move away from `ActionSequence`, but it looks like I'll be holding off for the time-being till ChromeDriver support (especially considering these might fail on BrowserStack, even if they were to run locally).

**Comment by TatyanaMartynyuk** [comment]
Same issue here.
OS: macOS Mojave, version 10.14.5 (18F203)
Browser: Chrome, version 75
Selenium-webdriver: 4.0.0-alpha.1

`await driver.actions().dragAndDrop(draggable, { x: 350, y: 0 }).perform();`
produces

> UnknownCommandError: Unrecognized command: actions
>       at buildRequest (node_modules/selenium-webdriver/lib/http.js:375:9)
>       at Executor.execute (node_modules/selenium-webdriver/lib/http.js:455:19)
>       at thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:696:38)

Are there any alternatives to `dragAndDrop`?..

**Comment by Anish-Agnihotri** [comment]
Hey @TatyanaMartynyuk,

I personally ended up having to use LegacyActions and did a `mouseDown`, moved the mouse to a random coordinate (x: 0, y: 0) in my case, and then a `mouseUp`.

A bit unfortunate that it doesn't work without this workaround.

**Comment by TatyanaMartynyuk** [comment]
@Anish-Agnihotri 
I updated my Chrome to version **76.0.3809.87**  and ChromeDriver to version **75.0.3770.140** and `await driver.actions().dragAndDrop(draggable, { x: 350, y: 0 }).perform();` works now. 🤷
