### ISSUE TITLE
isDisplayed threw NoSuchElementException when element invisible

### ISSUE THREAD

**Issue by sirdir** [SeleniumHQ/selenium#543]
so i have 
@FindBy(xpath = "//div[@data-tips-name='fillSelected']//div[@data-id='fillSelected']/i")
private WebElement ppPreviousFiles_btnClearAll;

and i want see if element visible and I know that he invisible at that moment http://prntscr.com/7562m2
calling ppPreviousFiles_btnClearAll.isDisplayed(); 
but instead of "false" i get NoSuchElementException http://prntscr.com/7561fy

**Comment by roydekleijn** [comment]
IsDisplayed checks the display status (eg block, hidden or none)

In your case you should use findElements and check the size of it

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
