### ISSUE TITLE
How to use selenium with <input type="submit">?

### ISSUE THREAD

**Issue by cubetastic33** [SeleniumHQ/selenium#5433]
## Meta -
OS:  Ubuntu 17.10
Selenium Version:  3.8.1(I think), in Python
Browser:  Firefox

## Expected Behavior -
The form should get submitted
## Actual Behavior -
The button is never even clicked
## The problem -
I tried clicking the button manually after having python fill the form, and it worked. However, when I let python do the clicking, it doesn't work. I figured that this is because it is not a regular button, but an input with type submit. How do I make this work? Also, all of this is not inside a form but a fieldset.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by cgoldberg** [comment]
call `.submit()` on any element in the form
