### ISSUE TITLE
Having a problem with ChromeDriver

### ISSUE THREAD

**Issue by nguyenvl179** [SeleniumHQ/selenium#5434]
Hello erveryone,
If I connect to a new tab and reconnect to the previous tab I can not get the text of the alert
My version of Chrome : 64

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
