### ISSUE TITLE
WebDriver .C# solution 

### ISSUE THREAD

**Issue by mvsreddymca** [SeleniumHQ/selenium#5435]
We are going to write a .Net application (DLL) and going to use ‘WebDriver’.
However our component is required to registry as a COM interface dll and it's required to add a strong name on “WebDriver”. Could you please help us C# .Net solution code with strong name details? 
Thank you for your help on this. Have a good day!!!

**Comment by diemol** [comment]
Isn't this the same that you posted in #4940? @jimevans already replied over there.

**Comment by mvsreddymca** [comment]
Thanks @diemol
