### ISSUE TITLE
python+selenium+PhantomJS: driver.execute_script() can't work

### ISSUE THREAD

**Issue by invomDing** [SeleniumHQ/selenium#5438]
Hi~
I was trying to simulate page scroll by js, but it doesn't work.
My attempt:
```
driver = webdriver.PhantomJS()
driver.get(url)
driver.maximize_window()
driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
html = driver.page_source.encode('utf-8')
```
then i fonud a solution: screenshot before script
```
driver.get_screenshot_as_file('123.png')
driver.execute_script("window.scrollTo(0, document.body.scrollHeight)")
```
<br>
A bit magical :D
But i don't know why

**Comment by lmtierney** [comment]
This would be an issue with phantomjs. You can raise an issue with them, but last I heard it was no longer being maintained. We also have dropped support for it.
