### ISSUE TITLE
Using sendKeys on IEDriverServer with requireWindowFocus option set to true leads to unpredictable results

### ISSUE THREAD

**Issue by doctordrue** [SeleniumHQ/selenium#5439]
## Meta -
OS:  
Windows 10 1709
Selenium Version:  3.8.0 Java, IEDriverServer.exe 3.8.0
Browser:  Internet Explorer
Browser Version:  11.194.16299.0
requireWindowFocus options is set to **true**

## Expected Behavior -
Value typed into input is the same as value that were typing
## Actual Behavior -
Unpredictable results of typing
## Steps to reproduce -
```
    @DataProvider
    public Object[][] textProvider() {
	return new Object[][] { { "all lowercase text" }, { "ALL UPPERCASE TEXT" }, { "Mixed Text" } };
    }

    @Test(dataProvider = "textProvider")
    public void typeTypeIntoInputTest(String text) throws InterruptedException {
	WebElement element = driver.findElement(By.tagName("input"));
	element.click();
	element.clear();
	Thread.sleep(1500);
	element.sendKeys(text);

	String value = element.getAttribute("value");
	Assert.assertEquals(value, text);
}
```
You can find the whole code of test to reproduce the issue in my repo: https://github.com/doctordrue/selenium-issues/blob/master/src/test/java/com/doctordrue/java/selenium/tests/issues/ie/send_keys/SendKeysIEDriverIssue.java
IEDriverServer log attached: [IEServerlog.log](https://github.com/SeleniumHQ/selenium/files/1695343/IEServerlog.log)

**Comment by p0deje** [comment]
Can you be more specific when you say "unpredictable results"?

Are you sure you're not interacting with OS by using mouse/keyboard while test is running? If you interact, it might cause this problem:

https://github.com/SeleniumHQ/selenium/blob/1cffee4cb9e0b5eccd57ef26fcb6d64ce0719a5d/cpp/iedriver/InputManager.cpp#L205-L214

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
