### ISSUE TITLE
 IE Browser - Unable to create new remote session

### ISSUE THREAD

**Issue by gohelkiran** [SeleniumHQ/selenium#5442]
## Meta -
 OS: Windows Server 2008/2012 (Virtual machine on AWS)
Selenium Version:  
 Selenium Version: 3.0.1
Browser:  
Internet Explorer 11

Browser Version:  
11.0.9600.18450

## Expected Behavior -
Internet browser 11 must launch using IEDriverServer.exe and open a given URL
## Actual Behavior -
Internet browser opens properly, but URL opened is different. It opens localhost URL with random port number like
http://localhost:25128/

## Steps to reproduce -
Open a hub using 
java -jar selenium-server-standalone-3.0.0.jar -role hub

Open a node using 
java -jar selenium-server-standalone-3.0.1.jar -role node -hub http://xxx.xxx.xxx.xxx:4444/grid/register

Create a web driver and open a URL.

Log from selenium hub
--------------------
16:53:00.335 INFO - Got a request to create a new session: Capabilities [{browserName=internet explorer, platform=WINDOWS}]
16:53:00.336 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=internet explorer, maxInstances=1, platform=WINDOWS}

Error message
 Fatal error: Uncaught exception 'Facebook\WebDriver\Exception\SessionNotCreatedException' with message 'Unable to create new remote session. desired capabilities = Capabilities [{browserName=internet explorer, platform=WINDOWS}], required capabilities = Capabilities [{}] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700' System info: host: 'WIN-MT0KFAH3HJN', ip: '10.10.10.10', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_141' Driver info: driver.version: InternetExplorerDriver' in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:154 Stack trace: #0 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throwException(33, 'Unable to creat...', Array) #1 E:\webenvoy\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Object(Facebook\WebDriver\Remote\WebDriverCommand)) #2 E:\webenvoy\ in E:\webenvoy\vendor\facebook\webdriver\lib\Exception\WebDriverException.php on line 154

**Comment by p0deje** [comment]
1. Please upgrade to latest versions of grid/bindings/IEDriver and re-test.
2. If issue is present, please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

I'll reopen the issue after that.
