### ISSUE TITLE
IE webdriver throws noProxy is type string instead of array   Exception when noProxy setting specified

### ISSUE THREAD

**Issue by shankarkc** [SeleniumHQ/selenium#5443]
## Meta -
OS:  
Win10
Selenium Version:  
2.7
Browser:  

Browser Version:  
11

## Expected Behavior -
IE to honor the No_proxy setting set by user
I set http proxy as below
```
    <parameter name="http_proxy" value="proxy.mycompany.corp:8080" />
    <parameter name="https_proxy" value="proxy.mycompany.corp:8080" />
    <parameter name="http_noproxy" value="localhost, *.mycompany.corp, *.mycompany.com, *.mycompany.biz,, 127.0.0.1, 10.0.2.15, *.lab1.mycompany.com" />

```
when i create proxy with below code
```
Proxy prox = new Proxy();
prox.setProxyType(ProxyType.MANUAL);
prox.setHttpProxy(testParameter.getHttp_proxy());
prox.setSslProxy(testParameter.getHttps_proxy());
prox.setNoProxy(testParameter.getHttp_noproxy());
```

Expected behavior is Selenium grid should be able to create IE session when noproxy setting string is specified. Same works fine with crome webbrowser.

## Actual Behavior -

I get below exception when use IE browser
```
org.openqa.selenium.InvalidArgumentException: All firstMatch elements failed validation
Invalid capabilities in firstMatch element 0: proxy setting noProxy is type string instead of array
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'INLN50949132A', ip: '10.138.169.153', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 1.49 seconds
```

## Steps to reproduce -
Refer attached maven project..
Update liner 27 to 30 in ..\testNGSelenium\src\test\java\com\javacodegeeks\testng\selenium\TestNGSeleniumSimpleSearchExample.java  to use right grid and proxy/no_proxy setting
run mvn clean install
You can refer the log file too for the callstack

[testNGSelenium.zip](https://github.com/SeleniumHQ/selenium/files/1697937/testNGSelenium.zip)
[log.zip](https://github.com/SeleniumHQ/selenium/files/1697976/log.zip)

**Comment by barancev** [comment]
Fixed by 66fcb623d4ce8aad0ca78997eba643375e4ab33a, to be released in version 3.13
