### ISSUE TITLE
Wrong build uploaded for java client bindings(When i download  selenium java client ,it is downloading standalone server instead of java client .zip or .rar file)

### ISSUE THREAD

**Issue by chennareddy08** [SeleniumHQ/selenium#5446]
1.Navigate to http://www.seleniumhq.org/download/
2.Under Selenium Client & WebDriver Language Bindings try to download java client binding and observe.

link:https://goo.gl/wz6ovx

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Expected Behavior -
Should download java client bindings
## Actual Behavior -
downloading selenium-server-standalone-3.9.0 (2) instead of java client binding

**Comment by priyanka1736** [comment]
M facing the same issue

**Comment by barancev** [comment]
Fixed

**Comment by chennareddy08** [comment]
Thank you
