### ISSUE TITLE
"h is null" JavaScript error occurs sometimes

### ISSUE THREAD

**Issue by pastapreneur** [SeleniumHQ/selenium#545]
My tests sometimes fail because of a Javascript Error:
```
Exception traceback: Traceback (most recent call last):
  File "run.py", line 292, in <module>
    r.play()
  File "run.py", line 256, in play
    self.run_downloads()
  File "run.py", line 146, in run_downloads
    self.run_download(download)
  File "run.py", line 167, in run_download
    executor.start()
  File "run.py", line 61, in start
    expected_conditions.presence_of_element_located((By.CLASS_NAME, "newsfeed-widget"))
  File "/srv/intex/venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 66, in until
    value = method(self._driver)
  File "/srv/intex/venv/local/lib/python2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 58, in __call__
    return _find_element(driver, self.locator)
  File "/srv/intex/venv/local/lib/python2.7/site-packages/selenium/webdriver/support/expected_conditions.py", line 279, in _find_element
    raise e
WebDriverException: Message: [JavaScript Error: "h is null" {file: "file:///tmp/tmpv9LZnL/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8478}]'[JavaScript Error: "h is null" {file: "file:///tmp/tmpv9LZnL/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 8478}]' when calling method: [nsICommandProcessor::execute]
```

This seems to happen randomly - sometimes the tests work and other times they get this exception, without changing any code.

The exception seems to occur with the WebDriverWait part of my code, so here's the relevant code:
```
self.driver.find_element_by_name("button1").click()
try:
    WebDriverWait(self.driver, 60).until(
        expected_conditions.presence_of_element_located((By.CLASS_NAME, "newsfeed-widget"))
    )
except TimeoutException:
    pass
```

Any help would be appreciated.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by pastapreneur** [comment]
I appreciate your reply, and I agree with the notion of reproducible test cases, however I don't know how to reproduce this one. It happens randomly without any external changes to the environment. Perhaps if you can tell me what I should start looking for I may be able to find out what reproduces the bug?

**Comment by samccone** [comment]
:+1: running into this also
https://travis-ci.org/twosigma/beaker-notebook/jobs/75473122#L4204
