### ISSUE TITLE
webdriver.Firefox() exception on Raspberry pi 3 Ubuntu Classic Server 16.04

### ISSUE THREAD

**Issue by nobism** [SeleniumHQ/selenium#5450]
## Meta -
Platform: Raspberry Pi 3
OS:  Ubuntu 16.04 Classic Server
Selenium Version: 3.9.0
Geckodriver: 19.0.1 ARM7hf
Browser:  Firefox 58.0.1
Language: Python 3.5.2

## Expected Behavior -
Expect no exception.

## Actual Behavior -
Exception raised:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
>     keep_alive=True)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
>     self.error_handler.check_response(response)
>   File "/home/martin/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1

geckodriver.log 

> 1517973993086	geckodriver	INFO	geckodriver 0.19.1
> 1517973993130	geckodriver	INFO	Listening on 127.0.0.1:33938
> 1517973994816	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.5EcLbXHxWGet"
> ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> 16639
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child

geckodriver.log (from Jenkins test, see below)

> 1517973683203	geckodriver	INFO	geckodriver 0.19.1
> 1517973683224	geckodriver	INFO	Listening on 127.0.0.1:44639
> 1517973686092	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.U9bo7S9WVbVv"
> ExceptionHandler::GenerateDump cloned child 16387
> ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 1517973692009	geckodriver	INFO	geckodriver 0.19.1
> 1517973692030	geckodriver	INFO	Listening on 127.0.0.1:51052
> 1517973693698	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.fYJ8OWbQXcXg"
> ExceptionHandler::GenerateDump cloned child 16427
> ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 1517973697889	geckodriver	INFO	geckodriver 0.19.1
> 1517973697930	geckodriver	INFO	Listening on 127.0.0.1:51720
> 1517973699621	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ChmQVltqdxxx"
> ExceptionHandler::GenerateDump cloned child ExceptionHandler::WaitForContinueSignal waiting for continue signal...
> 16466
> ExceptionHandler::SendContinueSignalToChild sent continue signal to child
> 

## Steps to reproduce -
```
$ python3
>>> from selenium import webdriver
>>> webdriver.Firefox()
```

## My actual problem -
Above is the simplest way that I've been able to reproduce the issue. But I've actually been trying to run tests using Jenkins on my Raspberry Pi 3, and I get the same error when `webdriver.Firefox()` is called. The setup on Jenkins is the same, except for `xvfb` is being used with the old `export DISPLAY=:99` trick (which doesn't work for me). I've also tried to use `pyvirtualdisplay` with no luck (same exception as above):

```
$ python3
>>> from selenium import webdriver
>>> from pyvirtualdisplay import Display
>>> display = Display(visible=0, size=(1366, 768))
>>> display.start()
>>> webdriver.Firefox()
```

I've tried *many* different versions of Selenium, geckodriver (even compiled ARM6hf versions) and Firefox with no luck.

I have had some success though, earlier I had Raspbian Stretch Lite (Nov 2017) on my Raspberry Pi 3 and my tests were working fine on Jenkins using Geckodriver 15.0, Firefox-sre 52.6 and Selenium 3.4.1. I'll fall back to this setup if this issue can't be resolved.

**Comment by lmtierney** [comment]
This appears to be a geckodriver/Firefox issue. Please raise an issue with them https://github.com/mozilla/geckodriver/issues
