### ISSUE TITLE
selenium 3.8.1 + ChromeDriver 2.35.528139 opening new tab with ( Crtl + t ) doesn't work 

### ISSUE THREAD

**Issue by vikramvi** [SeleniumHQ/selenium#5462]
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
3.8.1
Browser:  
Chromedriver 2.35.528139

## Expected Behavior -

1. User should be able to open new empty tab on chromedriver

## Actual Behavior -

1.  New tab is not opened

## Steps to reproduce -
1.  code to reproduce issue

```
driver.get("http://www.google.com");

		driver.findElement(By.tagName("body")).sendKeys(Keys.CONTROL + "t");
		Set<String> allWindowsId = driver.getWindowHandles();
		for (String windowId : allWindowsId) {
			if (driver.switchTo().window(windowId).getTitle().contains("New Tab")) {
				driver.switchTo().window(windowId);
				break;
			}
		}

		driver.navigate().to("http://www.yahoo.com/");

```

Please clarify if this is selenium or chromedriver issue

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by vikramvi** [comment]
just fyi..

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2265
