### ISSUE TITLE
action.move_to.perform is not working for firefox, IE and Edge browser

### ISSUE THREAD

**Issue by sanam1725** [SeleniumHQ/selenium#5463]
OS:  
Windows 8, Windows 10 and Ubuntu 14.0

Selenium Version:  
3.4.0

Browser:  
IE - 10, 11
Firefox - 53.0 , Geckodriver - 16.0
Edge - 14

Ruby Version : 2.3.0

**I am trying to click on element which will be visible on hovering element.**

Code which i am using is 
    `driver.action.move_to(element).perform`

This works fine with chrome browser but does not work for mentioned browser

Sample page where the same scenario can be tested is : http://the-internet.herokuapp.com/hovers
Here i am trying trying to click on 'View profile' which will be available once we hover on first image

Code:
```
    element = driver.find_element(:css, "img[src='/img/avatar-blank.jpg']")
    driver.action.move_to(element).perform
    driver.find_element(:css, "a[href, '/users/1'").click
```
    
Is there any alternate way to perform the same test?

**Comment by titusfortner** [comment]
Your versions are out of date. Actions are the last piece of w3c
specification to be implemented and have had the most work done on them
this past year. Update to the latest version of Firefox with geckodriver
0.19.1.

**Comment by sanam1725** [comment]
Thank you for the suggestion. I will update and see if it works fine or not.

What about IE and edge browser? This issue is seen even for these browsers

**Comment by luke-hill** [comment]
Your version of Edge is considerably out of date too, and the MicrosoftWebDriver executable is still being worked on actively. I don't know what % support they claim to have. But I know from personal experience it is the least complete / compliant driver. (Compared to IE/Gecko/Chrome).

Also Selenium `3.4.x` was where a lot of nuts and bolts with regards to Driver Options was added (In various patch versions). So the patch version actually matters. Failing that can you use 3.5.0 of the bindings?

**Comment by sanam1725** [comment]
As mentioned will update the set up and see if this issue actually gets fixed or not

**Comment by sanam1725** [comment]
I updated my set up with 

> Selenium Version : 3.9.0
IEDriverServer : 3.9.0
Firefox browser : 58
Geckodriver : 0.19.1
Edge : 15

Hover action went fine without any issue in all the browsers

**Comment by cgoldberg** [comment]
The OP was using it incorrectly:

> Code which i am using is
> driver.action.move_to(element).perform

it is `perform()` ...  it is a method you must call, not a property.

@naeem76 if you made the same mistake, fix your code.  Otherwise, please open a new issue with full details.

**Comment by naeem76** [comment]
I didn't have the same problem as OP, but anyhow I fixed it, I just had to scrolltoview in Firefox
