### ISSUE TITLE
Unable to interact with light DOM children in browser using polyfill

### ISSUE THREAD

**Issue by Artur-** [SeleniumHQ/selenium#5470]
## Meta -
OS:  macOS High Sierra 10.13.2
Selenium Version:  
3.8.1
Browser:  
Works on Chrome+Safari which have native Shadow DOM support
Broken in IE11, Edge, Firefox

## Expected Behavior -
- You can interact with an element which is in light DOM only, regardless of if the browser supports native shadow DOM or not.
- An element returned from `executeScript` can be used in a subsequent call instead of always throwing `StaleElementReferenceException`

## Actual Behavior -
An element which is in light DOM only can be returned by `executeScript` but trying to perform any action on the element results in `StaleElementReferenceException`

## Steps to reproduce -

```
git clone https://github.com/Artur-/shadydom-selenium
cd shadydom-selenium
mvn install
```

**Comment by Artur-** [comment]
I presume this is about how the webdrivers detect that an element is attached to the DOM, and that either the polyfill does not implement all the needed methods or the webdrivers do not use the polyfilled methods.

**Comment by p0deje** [comment]
Is it related to #5869?

**Comment by AutomatedTester** [comment]
closing as requested info was not given
