### ISSUE TITLE
Unable to find RobotRetriever class in selenium-server-3.9.1.jar

### ISSUE THREAD

**Issue by kkareemk** [SeleniumHQ/selenium#5473]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -
We used selenium-server-2.53.jar for developing our framework where we used RobotRetriever class
We have upgraded to 3.9.1 which is latest, but unable to find RobotRetriever class, not sure how to proceed further.
Please suggest

**Comment by cgoldberg** [comment]
it was part of Selenium RC, and was removed with 26eca99119982ba81b755edfc613030e4a1b19de

**Comment by barancev** [comment]
You have to deal with java.awt.Robot directly
