### ISSUE TITLE
Set flag (chrome://flags/#autoplay-policy) with ChromeOptions.

### ISSUE THREAD

**Issue by triodjangopiter** [SeleniumHQ/selenium#5477]
## Meta -
OS:  Mac OS Hight Sierra v10.13.3
Selenium Version:  3.8.1
Browser:  Google Chrome Version 64.0.3282.140 (Official Build)

## Expected Behavior  -
Switch flag chrome://flags/#autoplay-policy to "Document user activation is required."
 Is it possible?

## Actual Behavior  -
Chrome starts with a default value.

## Steps to reproduce -

    ChromeOptions options = new ChromeOptions();
    Map<String, Object> prefs = Maps.newHashMap();
    prefs.put("--autoplay-policy", "Document user activation is required.");
    options.setExperimentalOption("prefs", prefs);
    WebDriver driver = new ChromeDriver(options);

I trying:

    options.addArguments("--autoplay-policy=document-user-activation-required");

Same result. doesn't work.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
