### ISSUE TITLE
implicitlyWait method throws exception if an alert is open or if the page is not fully loaded

### ISSUE THREAD

**Issue by kistvan-odon** [SeleniumHQ/selenium#548]
Steps to reproduce:
1. perform an action that generates a browser pop-up alert or causes the page to load slowly
2. try to change the implicit wait while the alert is open or the page loads

Expected results: the implicit wait is successfully changed

Actual results: an UnhandledAlertException exception is thrown in case an alert is open or an WebDriverException (Error communicating with the remote browser. It may have died.) is thrown.

**Comment by sevaseva** [comment]
What browser? What OS?
Consider adding regression tests to https://github.com/SeleniumHQ/selenium/search?utf8=%E2%9C%93&q=ImplicitWaitTest in your language of choice.

**Comment by barancev** [comment]
UnhandledAlertException is expected in the described case.

As for the "Error communicating with the browser" please provide an executable reproduction scenario and a sample page.

**Comment by barancev** [comment]
I have no idea why do you need to change implicit wait interval when an alert is open. The only action you can do in this state is to accept or to decline the alert. You can't call findElement(s), the only operation that is aware of implicit wait. Alert handling operations don't take implicit wait into account.

**Comment by kistvan-odon** [comment]
@barancev 
So, as I told you I have a method that checks if an alert is open and then take some actions based on the result but I don't want it to wait for the default implicit wait and that's why I want to change it to a lesser value.
I could change the implicit wait before performing the action that generates the alert but I want the method that checks the alert to be a generic one and not having to add more logic to the tests.

**Comment by lukeis** [comment]
@kistvan-odon what action are you attempt to make after the alert is shown and after you want to set the new implicit wait timeout?

As barancev pointed out the only method calls that take the implicit wait into account are not valid while the alert has not been accepted/dismissed.

**Comment by kistvan-odon** [comment]
@lukeis 
The action that I want to make after generating the alert and changing the implicit wait is "driver.switchTo().alert()" because as far as I noticed it is also affected by the implicit wait.
Like I said before I managed to do the same thing by using ExpectedConditions but to me it doesn't seem legit to prevent the use of implicitlyWait by throwing an exception.
I had the following code but I don't use it anymore:

 public Alert getAlertWhenVisible(int timeoutSeconds) {
        manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
        for (int i = 0; i < timeoutSeconds; i++) {
            try {
                Alert alert = this.switchTo().alert();
                manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
                return alert;
            } catch (NoAlertPresentException e) {
                // no need to do anything
            }
        }
        Assert.fail(String.format(
                "No alert was present after %d seconds!",
                timeoutSeconds));
        return null;
}

As for WebDriverException (Error communicating with the remote browser. It may have died.) I'll keep looking for a reproduction scenario.

**Comment by lukeis** [comment]
relatively easy to reproduce:

    >>> from selenium import webdriver as w
    >>> d = w.Firefox()
    >>> d.implicitly_wait(10)
    >>> d.execute_script("setTimeout(function(){window.alert('hi')}, 2000)"); print d.switch_to.alert.text
    hi
    >>> d.implicitly_wait(2)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 621, in implicitly_wait
        self.execute(Command.IMPLICIT_WAIT, {'ms': float(time_to_wait) * 1000})
      File "/Library/Python/2.7/site-packages/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 175, in execute
        self.error_handler.check_response(response)
      File "/Library/Python/2.7/site-packages/selenium-2.45.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 165, in check_response
        raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
    selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: hi
    <super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>


and yes, since switch to alert listens for implicit wait timeouts, we should allow calling that method.

**Comment by lukeis** [comment]
although that appears to be Firefox specific... as Chrome and IE do not behave that way and do not adhere to implicit wait timeout when looking for alerts.

The webdriver w3c spec also does not mention waiting for alerts as apart of the implicit wait timeout:
https://w3c.github.io/webdriver/webdriver-spec.html#sessions
"A session has an associated implicit wait timeout that specifies a time to wait for the implicit element location strategy when locating elements using find element and find elements. Unless stated otherwise it is zero milliseconds."

It appears FirefoxDriver is not actually waiting for the implicit wait timeout... I just happen to choose *just the right* value in my example to have it work. You should use Explicit Waits instead for alerts.

FirefoxDriver waits up to 2 seconds for an alert to be present... likely due to some original issue when the driver was developed that caused a timing issue (shrug).
https://github.com/SeleniumHQ/selenium/blob/master/javascript/firefox-driver/js/firefoxDriver.js#L51-L52

**Comment by kistvan-odon** [comment]
@lukeis 
You are right.
I wrote the method that used implicit wait more than a year ago and I can't remember how I ended up with the conclusion that alerts are affected by implicit wait.
Thank you!
