### ISSUE TITLE
There was an unexpected error. Msg: TypeError: window.editor.treeView is undefined Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1 oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

### ISSUE THREAD

**Issue by hgzWeb** [SeleniumHQ/selenium#5480]
There was an unexpected error. Msg: TypeError: window.editor.treeView is undefined
Url: chrome://selenium-ide/content/selenium-ide.xul, line: 1, column: 1
oncommand@chrome://selenium-ide/content/selenium-ide.xul:1:1

**Comment by ruby186** [comment]
try to downgrade your firefox to 54 and below it would works fine.
or, portableapps is a better way. we can use portableapps to handle multiple versions.

mozilla is no longer support with these old extensions.
