### ISSUE TITLE
Open the same instance of browser every time with the same UUID

### ISSUE THREAD

**Issue by futi16** [SeleniumHQ/selenium#5484]
## Meta -
OS:  Win7

Selenium Version:  3.6.0

Browser:  Opera

Browser Version:  
48.0.2685.52 (PGO) (64bit)

**Comment by cgoldberg** [comment]
> every time you open a browser with selenium it open a new profile

this is default behavior by design.

**Comment by futi16** [comment]
Is there any way to open a browser with the same or specific UUID? If you say default, is there some settings that i can change? This is the only way to log into site that i want, as i have limit of 5 registered devices and monthly number i can delete of 2 devices.

**Comment by cgoldberg** [comment]
> Is there any way to open a browser with the same or specific UUID?

you can use an existing profile.

>  is there some settings that i can change?

you can specify the option when creating a webdriver.

[note: this tracker is for *issues*, not general questions]

**Comment by futi16** [comment]
Can you just say where it is in documentation or just a simple example, because i search and didn't find anything?

**Comment by cgoldberg** [comment]
You can find it in the documentation for the driver you are using.  For example, in the Chromedriver docs, see the *'Use custom profile (also called user data directory)'* section: https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by futi16** [comment]
I managed to open chrome with default profile, but when i try to go to some page i get 'Failed to launch GPU process' but if i delete the option line it open a browser and it go to some site.
This get me error 'Failed to launch GPU process':
`from selenium import webdriver
 
options = webdriver.ChromeOptions()
options.add_argument("user-data-dir=C:\\Users\\username\\AppData\\Local\\Google\\Chrome\\User Data")
driver = webdriver.Chrome(chrome_options=options)
driver.get('https://python.org')`

but this work:
`from selenium import webdriver

driver = webdriver.Chrome()
driver.get('https://python.org')`

I also tried with `options.add_argument('--disable-gpu')` when it didn't work, but the only difference is i don't get error, it just don't work
