### ISSUE TITLE
Connect to opened IEBrowser via IEDriverServer

### ISSUE THREAD

**Issue by evgen-san** [SeleniumHQ/selenium#5489]
Is it real to make possible to connect to opened IE browser via IEDriverServer.exe?
I was not found anything approaches to do this.
It should be very usefull for debagging tests. A many web-applications contains tens of web-pages during a business processes journey. It's too hard to go on the needed web-page every times anew.

**Comment by jimevans** [comment]
Attaching to an existing running instance of Internet Explorer is not a supported scenario for the IE driver.
