### ISSUE TITLE
Online Selenium API docs have JS errors

### ISSUE THREAD

**Issue by kaiyoma** [SeleniumHQ/selenium#5491]
If you open [the main URL](https://seleniumhq.github.io/selenium/docs/api/javascript/index.html) and click on "WebElement" in the sidebar, navigation fails and this error appears in the console:

```
Uncaught TypeError: Cannot assign to read only property '0' of string 'W'
    at af (dossier.js:95)
    at dossier.js:95
    at Array.forEach (<anonymous>)
    at t (dossier.js:9)
    at $e (dossier.js:95)
    at dossier.js:7
    at Array.forEach (<anonymous>)
    at t (dossier.js:9)
    at I (dossier.js:94)
    at new Tf (dossier.js:106)
```

I'm seeing this error a lot when clicking around the API docs.

**Comment by lmtierney** [comment]
I don't get this error anywhere. What browser?

**Comment by kaiyoma** [comment]
Chrome 64 on Windows. I've tried clearing my cache, and that helps, but I'm still seeing the error. If I clear the cache and click on all the links in the sidebar one at a time, eventually I'll encounter one that fails with a backtrace similar to what I posted above.

**Comment by jleyba** [comment]
Does this still happen for you? I can't reproduce on macOS (tested Chrome, Safari, and Firefox)

**Comment by kaiyoma** [comment]
Nope, seems to be fixed. Feel free to close.
