### ISSUE TITLE
Timed out receiving message from renderer

### ISSUE THREAD

**Issue by akshatj777** [SeleniumHQ/selenium#5493]
## Meta -
OS:    -  Windows 10 
Selenium Version:  3.5.1
Chrome Driver Version : ChromeDriver 2.35.528161
Browser:  Google Chrome 64.0.3282.167

Steps : 1) Switch to a new window
2) Let : 
BUR= Suppose https://facebook.com

Url = /class/sn/student#/Id=my&nsn=%%NNS&

public void NNSfil(String Url) {
		String n_U=Url.replaceAll("%%NNS",f_nns);
		driver.get(BUR+n_U);
		System.out.println("$$$URL is"+BUR+n_U);
		delay();
		driver.navigate().refresh();
		if(driver.findElements(By.cssSelector(".data")).size()>0){
	waitTo().until(ExpectedConditions.invisibilityOf(driver.findElement(By.cssSelector(".data"))));
		}
	}

Error recieving : 

[1518589680.030][SEVERE]: Timed out receiving message from renderer: 299.998
[1518589680.031][SEVERE]: Timed out receiving message from renderer: -0.001
[1518589680.035][SEVERE]: Timed out receiving message from renderer: -0.005

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
