### ISSUE TITLE
Selenium version 2.53 can't locate element randomly

### ISSUE THREAD

**Issue by nnquy** [SeleniumHQ/selenium#5494]
## Meta -
OS:  
Windows 10
Selenium Version:  
2.53.0
Browser:  
Chrome

We're using Slenium to do testing on SFDC site, we got issue element could not be found randomly.
Is there any know issue or any solution to fix on this case?

Thanks

**Comment by mar1ged** [comment]
I think the first answer will be "update to 3.9.1" ...

**Comment by indraganti** [comment]
Hi Mar1ged,
On behalf of Quy (my team member)
We tried after upgrading Selenium version to 3.9.1 but still issue exists . 
Kindly help .

**Comment by sahajamit** [comment]
Please upload the actual stacktrace and your code snippet which you are using to better understand the issue.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by indraganti** [comment]
Its an issue Barancev.  We are not able to resolve issue . When we run, few test steps are passing and few are failing .. and when we ran next time failed steps passed and few others failed .. 
it’s random behaviour

**Comment by barancev** [comment]
@indraganti Yes, I understand that you suffer from this random failures, but still advice you to write to the user group. This is the issue tracker, not a support channel.

**Comment by indraganti** [comment]
Ok barancev. Thank you for your reply . Will do update in user group and follow up
