### ISSUE TITLE
binary browser option from the nodes are not respected

### ISSUE THREAD

**Issue by damencho** [SeleniumHQ/selenium#5496]
## Meta -
OS:  Linux

Selenium Version:  3.9.1

Browser:  Firefox, Chrome

Browser Version:  

## Expected Behavior -
Setting custom binary option for a browser version should be respected.
## Actual Behavior -
The default Firefox or Google-Chrome binary is executed.
## Steps to reproduce -

Running selenium server and nodes v3.9.1. The node has the following config:
"capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 1,
      "version": ""
    },
    {
      "chrome_binary": "/usr/bin/google-chrome-beta",
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 1,
      "version": "beta"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 1,
      "version": ""
    },
    {
      "seleniumProtocol": "WebDriver",
      "firefox_binary": "/usr/bin/firefox-beta",
      "browserName": "firefox",
      "maxInstances": 1,
      "version": "beta"
    }
  ],

When the remote driver requests browserName: firefox and version: beta the option firefox_binary is not respected, the same applies for browserName: chrome and version: beta.

**Comment by J-Phipps** [comment]
This was supposed to have been fixed in 3.7 and is frustrating me to no end.
https://github.com/SeleniumHQ/selenium/issues/3123

**Comment by damencho** [comment]
Yep, I saw that issue. I wanted to try fixing it and send a PR, but I'm not sure what is the correct way of fixing it.
I saw that firefox_binary and chrome_binary are sent to the server. And there are two options from here:
1. Make sure server send this key back to the node and node will use it
2. Do a second caps matching on the node after receiving a session creation request and use the config key from there.

**Comment by zensolution** [comment]
I saw the same issue that chrome_binary was ignored. The only working version seems to be 3.7.1.  I am using java version.

**Comment by diemol** [comment]
Is this still an issue in Grid 3.141.59 and Grid 4 (alphas)?

**Comment by diemol** [comment]
Closing as the issue went stale.
