### ISSUE TITLE
Sendkeys not working with selenium box 

### ISSUE THREAD

**Issue by deepidua** [SeleniumHQ/selenium#5498]
## Meta -
OS:  

Selenium Version:  
  <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
          <version>2.53.1</version>
      </dependency>
  <dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-server</artifactId>
	    <version>2.53.1</version>
     </dependency>
      <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.14</version>
    </dependency>
    <dependency>
Browser:  

Browser Version:  

## Actual Behavior -
It is not opening a new tab but rather opening url in same tab and also, send keys are not working on selenium box but javascript executor is working

## Steps to reproduce -
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setPlatform(Platform.LINUX);
		capabilities.setBrowserName("firefox");
		capabilities.setCapability("auth", "xxxxx"); // auth token
																// required to
																// access
																// SeleniumBox
		LogHandler.info("print1");
		capabilities.setCapability("video", true);
		capabilities.setJavascriptEnabled(true);
		LogHandler.info("set capabilities for video true");
		// Initialize driver to use Selenium Box URL
		driver = new RemoteWebDriver(new URL("https://seleniumbox.xxx.com/wd/hub"), capabilities);

		LogHandler.info("print2");

		
		
		wait = new WebDriverWait(driver, 180);

		
		LogHandler.info("print3");

		
		driver.get("my url");
		Thread.sleep(10000);
		commonutil.getscreenshot(driver, "testseleniumbox");
		

		// Key in the username and password on the login window

		commonutil.findWebElementbyId(driver, "id")
				.sendKeys(commonutil.getPropertyvalue(username", "config"));
		Thread.sleep(1000);
		commonutil.findWebElementbyId(driver, "id").click(); // new
		Thread.sleep(1000);
		commonutil.findWebElementbyId(driver, "lInput.id").sendKeys(constant.Password);

		// Click on the login button after entering the login credentials
		commonutil.findWebElementbyId(driver, "loginbtn.id").click();
		Thread.sleep(15000);

		

		driver.manage().window().maximize();
		Thread.sleep(3000);
		// new
		JavascriptExecutor js = (JavascriptExecutor) driver;
		

	
		

		Actions act = new Actions(driver);
		
		 act.keyDown(Keys.CONTROL).sendKeys("t").keyUp(Keys.CONTROL).build().perform();  //getting error in this line as unsupported command exception 
//((JavascriptExecutor)driver).executeScript("window.open();");  tried this also to launch a new tab but no luck

((JavascriptExecutor) driver).executeScript("arguments[0].setAttribute('value', '" + uname + "')",
				driver.findElement(By.id("xxx")));  //this is working 
driver.findElement (By.id("")).sendKeys("xxx"); //this is not working

**Comment by lmtierney** [comment]
Please raise an issue with https://github.com/mozilla/geckodriver/issues

Relevant issues:

https://github.com/mozilla/geckodriver/issues/786
https://github.com/mozilla/geckodriver/issues/786
