### ISSUE TITLE
Unable to use KeyDown(Keys.Command)

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [SeleniumHQ/selenium#5500]
## Meta 
OS:  OSX 10.13.3
Selenium Version:  3.9.1
Visual Studio for Mac: 7.4 Preview (7.4 build 985)

## Expected Behavior 
Exception are not thrown and the functional works.

## Actual Behavior 
Exception is occurred.
```
System.ArgumentException : key must be a modifier key (Keys.Shift, Keys.Control, or Keys.Alt)
Parameter name: key
```

## Steps to reproduce 
1. Download a [sample](https://1drv.ms/u/s!AjJkvULquuvugWM7lCXWaL0SC2EX. A folder contains folder with the sample and `AppiumForMac.app`.
2. Run `AppiumForMac.app`
3. Open the sample
4. Build it and run tests 

Sample contains only on test with next line:
```
new Actions(this.driver).KeyDown(Keys.Command).SendKeys("q").KeyUp(Keys.Command).Perform();
```

**Comment by mykyta-bondarenko-gl** [comment]
`Escape` doesn't work too (the same result).

**Comment by jimevans** [comment]
Fixed with commit a8d9b86.

**Comment by jimevans** [comment]
Hang on, the `KeyDown` method of the `Actions` class is clearly documented to only be valid for modifier keys (Shift, Alt, Control, etc.). You're asking for a change in the API contract. I'm not certain that's a wise course of action.

**Comment by mykyta-bondarenko-gl** [comment]
@jimevans you added missed keys before. As I understand I should use this method to simulate keyboard actions which  I can't simulate via `SendKeys` method. 
That's why I asked to add `Escape` and `Space` keys to the collection.

Thanks

**Comment by jimevans** [comment]
The missed keys that were added (Command) were modifier keys. Space and Escape are not.

**Comment by mykyta-bondarenko-gl** [comment]
What is the right way to use Space and Escape? @jimevans  ^

**Comment by mykyta-bondarenko-gl** [comment]
Thanks. 
I understand how I can use `Space` (" ") but how can I use `Escape`? I tried "Esc", "ESC", "Escape" and several other ways and nothing works :( 
@jimevans ^

**Comment by jimevans** [comment]
`actions.SendKeys(Keys.Escape);` doesn’t work?

**Comment by jimevans** [comment]
The properties of the `Keys` class, each representing a specific key, are strings. As such, they can be used anywhere strings are, and can be concatenated to make them part of other strings as well. As this is working for you now, I’m going to close this issue.
