### ISSUE TITLE
Find element by does not properly scope x paths when applied to an element

### ISSUE THREAD

**Issue by BasHamer** [SeleniumHQ/selenium#5501]
## Meta -
OS:  
Windows 10
Selenium Version:  
 <package id="Selenium.Support" version="3.8.0" targetFramework="net47" />
 <package id="Selenium.WebDriver" version="3.8.0" targetFramework="net47" />

Browser:  
Chrome

Browser Version:  
 Docker grid chrome node

## Expected Behavior -
when finding elements inside of an existing element using xpaths then the xpaths should not escape that element.

## Actual Behavior -
an or operator will escape depending on where it is placed

## Steps to reproduce -

```
<html>
<div class="target"></div>
<span class="b"></span>
</html>
```

var div = Driver.FindElement(By.XPath(@"//div[@class='target']");
var icons = div.FindElements(By.XPath( "//*[contains(@class,'a')] | //*[contains(@class,'b')]"));

var iconsworks = div.FindElements(By.XPath( "//*[contains(@class,'a') | contains(@class,'b')]"));

**Comment by p0deje** [comment]
I don't understand what the problem is. 
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

**Comment by BasHamer** [comment]
whoops, did not expect the formatter to have eaten my html

**Comment by jleyba** [comment]
This is how XPath works. If you start your selector with `/`, it will __always__ search from the document root regardless of the context node. If you want to search under an individual element you need to provide a relative selector.

Example:

```html
<!DOCTYPE html>
<div id="one"></div><div id="two"><div id="three"></div></div>
<script>
function print(node) {
	if (!node) return null;
	return node.id ? `${node.nodeName}#${node.id}` : node.nodeName;
}
function test(root, xpath='//div') {
	var result = document.evaluate(xpath, root, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
	document.write(`<div>from ${print(root)}, found ${print(result)}</div>`);
}
test(document);
test(document.body);
test(document.getElementById('two'));
test(document.getElementById('two'), './/div');
</script>
```

This page will produce:

```html
from #document, using //div, found DIV#one
from BODY, using //div, found DIV#one
from DIV#two, using //div, found DIV#one
from DIV#two, using .//div, found DIV#three
```

**Comment by BasHamer** [comment]
unfortunately, the method comments state that that is not how it works. 
Finds all <see cref="T:OpenQA.Selenium.IWebElement">IWebElements</see> within the current context

I'd assume the current context in my example is the div, and that is how it works; it is not until you apply a top-level OR that you escape the context.

My best guess is that is preprends the xpath with the currently selected element and that is why the second method works and the first one escapes the "current context"
