### ISSUE TITLE
When the hub is restarted, windows agents don't seem to reconnect/re-register

### ISSUE THREAD

**Issue by Deklin** [SeleniumHQ/selenium#5504]
## Meta -
OS:  
Windows 2012R2
Selenium Version:  
3.9.1
Browser:  
IE

Browser Version:  
N/A

## Expected Behavior -
Nodes should re-connect to hub/re-register when the hub comes back up.

## Actual Behavior -
We are running selenium-grid in kubernetes, when we restart the hub pod, the static windows agents show an error registering but once the hub is back up they never re-register. Instead we need to restart each of the nodes manually

## Steps to reproduce -

1. Run the selenium grid hub
2. Connect a windows node to it and have it register
2a. Confirm the node appears in grid/console
3. Stop the hub
3a. Observe on the windows node that it has a connection issue with the hub
4. Start the hub
4a. observe in grid/console after a period of time the windows nodes never re-register

5. restart the windows node and let it register
5a. observe in the grid/console that the node is back.

**Comment by diemol** [comment]
Hi @Deklin,

Could you provide the logs of the hub (before and after restarting) and the nodes? If I remember correctly, there is no "restarting pod" in Kubernetes, a new one is always spinned up, which I think will have a different IP.

**Comment by barancev** [comment]
Closing the issue as there is no additional information provided.
