### ISSUE TITLE
cant load such file from selenium/webdriver/phantomjs

### ISSUE THREAD

**Issue by sampathmende** [SeleniumHQ/selenium#5505]
windows 8.1
[2018-02-09 10:23:44 +0000] code - Arachni - #Set:0x0055d99c9ff170
[-] **[LoadError] cannot load such file -- selenium/webdriver/phantomjs**
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in require' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:inexecutable'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:126:in has_executable?' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:50:inhost_has_browser?
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:65:in use_browsers?' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:24:inbrowser_cluster'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:167:in audit' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:inblock in run'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in exception_jail' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:inrun'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/framework.rb:62:in block in run' **[-] [Errno::EINVAL] Invalid argument @ rb_io_seek - /tmp/arachni20180209-893-1sbkutgafr** [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:inseek'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in block in load' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:inopen'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:in load' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:40:inrun'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:25:in initialize' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:innew'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:in <top (required)>' [-] /root/.rbenv/versions/2.3.0/bin/arachni_reporter:23:inload'
[-] /root/.rbenv/versions/2.3.0/bin/arachni_reporter:23:in `

**Comment by lmtierney** [comment]
Please raise an issue with the library that is giving you the error. https://github.com/Arachni/arachni/issues
