### ISSUE TITLE
add_argument for user agent cuts off at first space

### ISSUE THREAD

**Issue by jaypinho** [SeleniumHQ/selenium#5507]
## Meta
OS: macOS High Sierra

Selenium Version: 3.9.0

Browser: Chrome

Browser Version: 64.0.3282.167 (Official Build) (64-bit)

## Problem

I'm using Ruby and the Selenium WebDriver to view a webpage using headless Chrome.

I need to change the user agent for my project. On my local computer, I can easily do this via the **add_argument** method in Selenium::WebDriver::Chrome::Options:

```
options = Selenium::WebDriver::Chrome::Options.new()
options.add_argument('--headless')
options.add_argument('--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36')
driver = Selenium::WebDriver.for(:chrome, options: options)
puts driver.execute_script('return navigator.userAgent')
```

This (correctly) returns:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36

However, when I push this code to my Heroku app and run the same code*, suddenly here's what gets returned:

> Mozilla/5.0

I have spent upwards of 4 hours trying all manner of fixes. Pretty early on I realized this was probably some kind of escaping issue, so I looked up how to escape spaces and (I think) have tried absolutely everything: backslashes, double-backslashes, quotes, double-quotes, etc. None of it has worked. As far as I can tell, absolutely any user agent I pass as an option will get cut off at the first space.

Am I missing something obvious here?

Thank you! 

\**The only change I make to the code running on Heroku is that I have to slightly update the first line of code above to point the Heroku app to the Chrome binary:*

```
options = Selenium::WebDriver::Chrome::Options.new(binary: ENV['GOOGLE_CHROME_SHIM'])
```

**Comment by lmtierney** [comment]
Put your user agent in double quotes

```
options.add_argument('--user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"')
```

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jaypinho** [comment]
@lmtierney That didn't work. It now returns:

> "Mozilla/5.0

I posted it here because it seems to be an issue with escaping generally (unless, again, I'm missing something).

**Comment by lmtierney** [comment]
You can always try escaping the spaces with `\ ` but again, please post this to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) as this is not an issue with selenium itself.

**Comment by jaypinho** [comment]
Thanks, will do.
