### ISSUE TITLE
Timeout issue with Selenium 3.9.0 & okhttp

### ISSUE THREAD

**Issue by KuzhaliDhivyan** [SeleniumHQ/selenium#5510]
## Meta -
OS:  Windows 7

Selenium Version:  3.9.0 

Browser:  Chrome

Browser Version:  

## Expected Behavior - 
All tests should pass with Okhttp in version 3.9.0

## Actual Behavior -
Getting org.openqa.selenium.WebDriverException: java.net.SocketException: Read Timeout error. And below error when run in AWS

org.openqa.selenium.remote.UnreachableBrowserException: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
System info: , os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_131'
Driver info: driver.version: RemoteWebDriver

Test passes on setting the below property:

System.setProperty("webdriver.http.factory", "apache"); 

## Steps to reproduce -
On executing the tests cases using selenium version 3.9.0 , Getting org.openqa.selenium.WebDriverException: java.net.SocketException: Read Timeout error.

Same behavior is observed from CI  like Jenkins/Bamboo

Test pass when run individually.

**Comment by barancev** [comment]
Check version 3.9.1

**Comment by Manikandan-Zoho** [comment]
I am using okhttp3 I having the **socket timeout Issue** in selenium 2.53 & 3.8.1 , How to reproduce this?

**Comment by KuzhaliDhivyan** [comment]
Yes , seems like issue is fixed. Thank you.
