### ISSUE TITLE
Selenium.Support.StrongNamed should depend on Selenium.WebDriver.StrongNamed instead of Selenium.WebDriver

### ISSUE THREAD

**Issue by justkao** [SeleniumHQ/selenium#5511]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.9.1

## Expected Behavior
The package Selenium.Support.StrongNamed should depend on Selenium.WebDriver.StrongNamed

## Actual Behavior
The package Selenium.Support.StrongNamed depends on Selenium.WebDriver

## Steps to reproduce -
Download strong signed packages from http://selenium-release.storage.googleapis.com/index.html?path=3.9/ and reference the Selenium.Support.StrongNamed package in net core project that is strong named. Building this project causes the build error.

`Referenced assembly 'WebDriver, Version=3.9.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by jimevans** [comment]
As a workaround, please do not use package references for the strong-named assemblies. Extract the assembles from the .nupkg files and reference the assemblies directly.

**Comment by jimevans** [comment]
Fixed in 637967a. Will be released in next release of the .NET bindings (currently next release will be 3.12, and no scheduled time frame for the release is available).
