### ISSUE TITLE
Implicit wait doesn't work for Firefox browser using Python-Selenium bindings above 3.4.0

### ISSUE THREAD

**Issue by Kannamaraj** [SeleniumHQ/selenium#5512]
## Meta -
OS:  
Windows (10), OSX (Sierra, High Sierra, El Capitan)
Selenium Version:  
"3.5.2", "3.5.3", "3.6.0", "3.7.0", "3.7.1", "3.8.0", "3.8.1". Anything above 3.4.0
Browser:  
Firefox (GeckoDrivers tried: 0.15.0, 0.16.0, 0.18.0, 0.19.0, 0.19.1)
Browser Version:  
FF: 56.0, 57.0, 58.0
## Expected Behavior -
Implicit wait should work
## Actual Behavior -
Implicit wait command fails with error: **implicit_wait did not match a known command**
**StackTrace:**
selenium.common.exceptions.WebDriverException: Message: POST /session/<Session-ID>/timeouts/implicit_wait did not match a known command
Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:12:12.411Z'
System info: host: '<>', ip: '<>', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'
## Steps to reproduce -
1. Run any basic sample script like opening google page using python selenium bindings.
2. User implicit wait command (**driver.implicitly_wait(4)** (Python Selenium bindings used 3.8.1 locally and set up grid above 3.4.0)
3. The command fails with error: **implicit_wait did not match a known command**
Stacktrace:
selenium.common.exceptions.WebDriverException: Message: POST /session/<Session-ID>/timeouts/implicit_wait did not match a known command
Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:12:12.411Z'
System info: host: '<>', ip: '<>', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_151'

**Comment by lmtierney** [comment]
I cannot reproduce this with python bindings at `3.8.1` and selenium server at `3.8.1`. Keep in mind for this to work you would need geckodriver of at least `0.18.0` and Firefox of at least `56` (see `Fixed` in https://github.com/mozilla/geckodriver/releases/tag/v0.18.0).

**Comment by timsutton** [comment]
@Kannamaraj mentions using grid, were you using grid or standalone @lmtierney?

**Comment by lmtierney** [comment]
I tried it with grid

**Comment by gohelkiran** [comment]
I have same issue with v3.12.0 on standalone server

**Comment by ngreyes** [comment]
This issue still exist with Firexof 60.0.1 and latest gecko driver 0.20.1.  It seems root cause has never been found, bummer.  Please also work on weekend s until you get it resolve.
