### ISSUE TITLE
Firefox related error: UnsupportedOperationError: sendKeysToActiveElement with sendkeys

### ISSUE THREAD

**Issue by bsarkadi** [SeleniumHQ/selenium#5517]
## Meta -
OS:  Win7
Selenium Version:  Standalone Server 3.9.1
Browser:  Firefox 58.0.2 
Geckodriver 0.19.1
Protractor: 5.3.0

## Expected Behavior -
sending keys to browser via sendKeys() function

## Actual Behavior -
I get this error:
UnsupportedOperationError: sendKeysToActiveElement with sendkeys
## Steps to reproduce -

This is the code where the error occurs. This works perfectly when running in Chrome.

``var loginForm = element(by.id("loginForm"));
            loginForm.isPresent().then(function(result) {
                if (result) {
                    element(by.id("username")).isPresent().then(function(result) {
                        if (result) {
                            element(by.id("username")).clear().sendKeys(browser.params.dev_username);
                        }
                    });
                    element(by.id("password")).isPresent().then(function(result) {
                        if (result) {
                            element(by.id("password")).clear().sendKeys(browser.params.dev_password);
                        }
                    });
                }
            });
``

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) **with selenium** so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by bsarkadi** [comment]
I got this answer in the geckodriver forum:

> This is an issue with the bindings that you are using. There should be a little shim in the bindings that make sure the same functionality is given on older commands that have been removed. This issue will appear when chrome switch over to W3C support. This has been implemented in the core selenium binding, a python example at https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/action_chains.py#L343-L356

Could you help if this shim exists for the JS binding?

**Comment by bsarkadi** [comment]
Hi again,

The issue is still present with these versions:

OS: Win7
Selenium Version: Standalone Server 3.11.0
Browser: Firefox 59.0.2
Geckodriver 0.20.1
Protractor: 5.3.0

Steps to reproduce:

Please try if the sendkeys Protractor command works with Firefox. 
I get the error even if I reduce the test case to just getting the url and using sendkeys.
`it('@Test Login function', function() {
        browser.driver.get(browser.params.base_url);
        browser.driver.findElement(by.id('username')).sendKeys('dev');
    });`

**Comment by amolinaalvarez** [comment]
Same problem using Firefox 67.0

**Comment by fluffypomeranian** [comment]
+1 broke when upgrading chrome version 75-->76
