### ISSUE TITLE
Selenium-Python : selenium.common.exceptions.InvalidElementStateException details are missing from the documentation and source

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5520]
## Meta - Selenium-Python :  `selenium.common.exceptions.InvalidElementStateException` details are missing from the [documentation](https://seleniumhq.github.io/selenium/docs/api/py/common/selenium.common.exceptions.html#selenium.common.exceptions.InvalidElementStateException) and [source](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/common/exceptions.html#InvalidElementStateException)

OS:  All
Selenium Version:  Selenium v3.9.1
Browser:  All

Browser Version:  N/A

## Steps to reproduce -
`selenium.common.exceptions.InvalidElementStateException`

- [Documentation](https://seleniumhq.github.io/selenium/docs/api/py/common/selenium.common.exceptions.html#selenium.common.exceptions.InvalidElementStateException)

- [Source](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/common/exceptions.html#InvalidElementStateException)

**Comment by lmtierney** [comment]
Added to source, will be in the documentation when they are generated with the next release.
