### ISSUE TITLE
Validate nested XPath locators

### ISSUE THREAD

**Issue by phoenix384** [SeleniumHQ/selenium#5521]
To find an element via XPath below another element, the XPath expression should begin with a dot. Otherwise the nested XPath is treated like a normal XPath searching for the element below the root node.

For example:
`driver.findElement(By.xpath("//input")).findElement(By.xpath("//label"));`
finds something although there is no label element inside an input element.

`driver.findElement(By.xpath("//input")).findElement(By.xpath(".//label"));`
finds nothing which is correct.

It is a common unnoticed mistake that could be avoided by validating that the XPath expression inside ByXPath.findElement does not start with "/" if the search context is a WebElement.

I could make a PR for that, if desired.

**Comment by barancev** [comment]
What would you suggest to implement in a validator? Putting a warning to the log?

**Comment by phoenix384** [comment]
No, I guess no one would take notice of a log warning.
Actually I thought about throwing an exception. I can't think of a case where such an XPath locator is not a mistake. So why not call attention to it?

**Comment by barancev** [comment]
This behaviour (an exception) would contradict to XPath standard and XPath implementation in JavaScript (read "in browsers").

**Comment by phoenix384** [comment]
What do you mean by that? What standard forbids to prevent the user from making a mistake?
What does the XPath standard have to do with throwing an exception in a Java class (ByXpath.java) if the second expression starts with a "/"?

**Comment by AutomatedTester** [comment]
closing as XPath has a lot of inbuilt error handling and we are just handing off to the browser
