### ISSUE TITLE
Ignore IE Protected Mode desired capability setting is not effective with selenium jar 3.8+

### ISSUE THREAD

**Issue by tomatobrown** [SeleniumHQ/selenium#5525]
## Meta -
OS:  
Windows 7 (hub, node), OS 10.11.6 on Mac (agent)
Selenium Version:  
3.9.1
Browser: 
IE 11

Browser Version:  
IE 11.0.9600

## Expected Behavior -
IEDriver to execute tests against IE

## Actual Behavior -
Exception thrown when creating driver:
```
SessionNotCreatedError: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
```
## Steps to reproduce -
1. Using Node JS with selenium-webdriver `4.0.0-alpha.1` or `3.6.0`
2. Setup a hub and node on Windows 7 machine with selenium jar 3.9.1
3. Run tests against new selenium grid using IE11

Expected: Tests to run
Actual: Exception throwing above

Other things of note:
1. I've tried IEDriver 3.8 and 3.9
2. All of this works correctly with selenium jar 3.6 
3. I AM setting the following capabilities
```
	capabilities.set('ignoreProtectedModeSettings', true);
	capabilities.set('ie.ensureCleanSession', true);
	capabilities.set('enableElementCacheCleanup', true);
	capabilities.set('ignoreZoomSetting', true);
```

**Comment by tomatobrown** [comment]
This issue might be related to: https://github.com/SeleniumHQ/selenium/issues/5502

**Comment by joeyparrish** [comment]
I get the same thing with selenium 3.12 and the latest IE driver.

**Comment by barancev** [comment]
@tomatobrown 
1) Please retest with Selenium 3.10 or newer
2) Please provide the hub and the node log that show what capabilities were passed in the new session request.

**Comment by jeffery-cavallaro** [comment]
Confirmed that behavior still exists with selenium 3.13.1.

**Comment by barancev** [comment]
Closing the issue as the author did not provide the requested information (logs).
