### ISSUE TITLE
sendKeys is very slow in remote node for IE driver 3.8

### ISSUE THREAD

**Issue by Elakkiyaab** [SeleniumHQ/selenium#5526]
## Meta -
OS:  Windows 7

Selenium Version:  3.7.0(standalone driver)

Browser:  Internet explorer 11(driver version 3.8)
<!-- Internet Explorer?  Firefox?

Tests are running very slow for IE browser in remote node.The text are typing very slow in text field(both 32 bit and 64 bit).It was fast for 3.4
Does this issue fixed in 3.9 standalone server?
Is there any specific capability needs to added?

**Comment by AutomatedTester** [comment]
There is way too little information on this to even be close to actionable. 

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Elakkiyaab** [comment]
it is typing string one by one  in IE browser in grid node.It is taking too much time to complete one test if there are many text fields .

**Comment by lmtierney** [comment]
@Elakkiyaab please review http://jimevansmusic.blogspot.co.uk/2014/09/screenshots-sendkeys-and-sixty-four.html
