### ISSUE TITLE
Selenium 3.8.0 webdriverbackedselenium issue

### ISSUE THREAD

**Issue by nkarthikeyan90** [SeleniumHQ/selenium#5528]
i have upgraded to selenium v3.80 instaded using 2.5.4 also i have developed by C# language in my selenium tool.while run webdriverselennium line getting error like "findelement.js file missing"
how to resolve this also selenium.type not working how to intialize variable for this

**Comment by jimevans** [comment]
Build process fixed in 76ff24f. Updated binaries will be released in the next release of the .NET bindings (currently, next release will be 3.12, but there is no expected timeframe for the release).
