### ISSUE TITLE
NPE with Selenium 3.9.1 in local execution (instanciate Hub by java code )

### ISSUE THREAD

**Issue by Ben-MBA** [SeleniumHQ/selenium#5533]
## Meta -
OS:  
 Windows 
Selenium Version:
3.9.1
Browser:  
Chrome V 

I used this code with many version of Seleniu 3.0.X 

ExecutionManager.hub = new Hub(GridHubConfiguration.loadFromJSON(HUB_CONFIG_JSON));

And from the update with the version 3.9.1, I have a NPE without any stack trace or message !
when loading the hubconfig.json in the GridHubConfiguration

Browser Version:  
64.XX

## Expected Behavior -
Grid is launched locally
## Actual Behavior -
NPE
## Steps to reproduce -
just execute the folowing code : 
ExecutionManager.hub = new Hub(GridHubConfiguration.loadFromJSON(HUB_CONFIG_JSON));

Note : remotelly all works fine.

Thks FOR HELP.

**Comment by barancev** [comment]
I can't reproduce the issue with the provided code sample and a config file with default content. Please provide the complete reproduction scenario.

**Comment by Ben-MBA** [comment]
Hello, thank you for yur help and this is my config file : 
{
  "host": 127.0.0.1,
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "maxSession": 20
}

There is no special think and I use Java 8 if it can help. 
Same code works with 3.1.8

**Comment by barancev** [comment]
I can't reproduce the issue yet.
Please be more specific, what part of the code throws
`GridHubConfiguration config = GridHubConfiguration.loadFromJSON(HUB_CONFIG_JSON)`
or
`new Hub(config)`

**Comment by Ben-MBA** [comment]
The NPE is in the method GridHubConfiguration.loadFromJSON : 
I follow the execution and the error was in the Gson google class in the method getAdapter().

It is strange I didn't see any NPE when debugging and in the folowing loop candidate  was usually null !!

 for (TypeAdapterFactory factory : factories) {
        TypeAdapter<T> candidate = factory.create(this, type);
        if (candidate != null) {
          call.setDelegate(candidate);
          typeTokenCache.put(type, candidate);
          return candidate;
        }
      }
      throw new IllegalArgumentException("GSON cannot handle " + type);

And far in the method :+1: public static GridHubConfiguration loadFromJSON(JsonObject json) {
    try {
      GsonBuilder builder = new GsonBuilder();
      GridHubConfiguration.staticAddJsonTypeAdapter(builder);
      return builder.excludeFieldsWithoutExposeAnnotation().create()
        .fromJson(json, GridHubConfiguration.class);
    } catch (Throwable e) {
      throw new GridConfigurationException("Error with the JSON of the config : " + e.getMessage(),
                                           e);
    }
  }

e was of type NPE !!!

any help please.

**Comment by Ben-MBA** [comment]
I spend some other time and the NPE is in the class sur.reflect.annotation.AnnotationParser in the method parseAnnotations (dont have source) and called from the method declareAnnotations in the class Field.
And the field was : org.openqa.grid.internal.utils.configuration.GridHubConfiguration.hubConfig of type String. 

I verified also in the class GridHubConfiguration that there is no modification between 3.8.1 and 3.9.1 !!

Hope I help with all these information. I'm really confused and i can't understand the pb!!

**Comment by lytran610** [comment]
Hello, 

I got the same pb when upgrading to 3.9.1. Could you please help to check?

**Comment by Ben-MBA** [comment]
Issue is fixed with the version 3.10.0.
So I close it
