### ISSUE TITLE
IEDriverServer.exe 3.9.0.0 is detected as SONAR.Heuristic by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by KevinChrz** [SeleniumHQ/selenium#5534]
As of February 22, 2018 the file IEDriverServer.exe is flagging with Symantec Endpoint Protection as Heur.AdvML.C with the following details:

Category: Malware
Sub category: Heuristic Virus
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Heur.AdvML.C
File: C:\PATHING\packages\Selenium.WebDriver.IEDriver.3.9.0\driver\IEDriverServer.exe
Location: Deleted or access blocked
Computer:
User: NETWORK SERVICE
Action taken: Cleaned by Deletion

![iedriverserver flag 01](https://user-images.githubusercontent.com/13453819/36595755-740cafd4-1871-11e8-942b-ec29b3773985.png)
![iedriverserver flag 02](https://user-images.githubusercontent.com/13453819/36595757-75e75930-1871-11e8-82e9-a7a7b84866a9.png)

**Comment by AutomatedTester** [comment]
Running the zip through [virustotal](https://www.virustotal.com/#/url/30f098841fd25787cdcf9221dfcc0e886ba2650e6fcd6d21b291fdac24942417/detection) it doesnt show any infections  and your antivirus doesnt show the confidence so this is a false positive in your antivirus

**Comment by KevinChrz** [comment]
If you don't care, I don't either. This was just me letting you know how it reacts to Symantec Endpoint Protection.

**Comment by AutomatedTester** [comment]
We do care and why we run it through virustotal straight away . Please can you flag it to symantic(Their email process rarely works for us)

**Comment by KevinChrz** [comment]
I will file and see if it gets anywhere. Here's to hope!
