### ISSUE TITLE
firefox path error

### ISSUE THREAD

**Issue by surmitchauhan** [SeleniumHQ/selenium#5535]
I am using a bot and this error is occuring.when i run the bot it has to start the firefox automatically but this error shows up.

OpenQA.Selenium.WebDriverException: Cannot find Firefox binary in PATH or default install locations. Make sure Firefox is installed. OS appears to be: Vista at OpenQA.Selenium.Firefoxinternal.Executable..ctor(String userSpecifiedBinaryPath) at OpenQA.Selenium.Firefox.FirefoxBinary..ctor(String pathToFirefoxBinary) at WindowsFormsApplicationl.Forml.BotMainQ

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
