### ISSUE TITLE
How to handle psedu elements eg ::before in selenium

### ISSUE THREAD

**Issue by lovish-jain** [SeleniumHQ/selenium#5537]
## Meta -
OS:  
WIndows 7
Selenium Version:  
3.7.1
Browser:  
Chrome
Browser Version:  
64.0.3282.186 (Official Build) (64-bit)

## Expected Behavior -
In the screenshot above i want to click on radio button 50% and above. Locating this radio button is highlighting pseudo-element ::before. Please help how can i locate this element and select it.

![myntra](https://user-images.githubusercontent.com/23254432/36644121-965d1c0c-1a7b-11e8-8f8c-5553fe3f8aa6.jpg)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
