### ISSUE TITLE
Select target does not work in Firefox Developer Edition with new multi-process mode.

### ISSUE THREAD

**Issue by adbutterfield** [SeleniumHQ/selenium#554]
Hi,

So I use Selenium IDE with Firefox Developer Edition on Mac. Just yesterday when opened my browser to make some tests, I was prompted: "Multi-process is coming soon to Firefox Developer Edition. You can start using it now to get early access to some of the benefits..."

Sounded good to me, so I enabled it. However after that, if I try to add a command, such as assertVisible, then hit the select button to grab a target from the browser, the little yellow box that you use to highlight targets does not appear. Also if you click on the page anywhere, no target is ever selected. 

If I disable the multi-process mode (open preferences and un-check "Enable multi-process Firefox Developer Edition"), then everything goes back to normal. If I enable it again, it's broke. Disable again, and back to normal again.

Version numbers, in case that helps:
Selenium IDE 2.9.0
FirefoxDeveloperEdition 40.0a2

**Comment by neoecos** [comment]
:+1:  
Same error here selenium-firefox-driver 2.47.1  with Firefox 42.0a

**Comment by samitbadle** [comment]
Hi,

Have you created a bug on Mozilla website at https://bugzilla.mozilla.org/. They should not break compatibility with existing addons. Feel free to put a bug id here.

Cheers,
Samit
