### ISSUE TITLE
jetty-repacked jar has incorrect dir flag

### ISSUE THREAD

**Issue by isidorkin** [SeleniumHQ/selenium#5543]
## Meta -
Selenium Version:  
3.9.1

## Steps to reproduce -
$ zipinfo -l /export/jetty-repacked-9.4.7.v20171121.jar 
-rw----     2.0 fat        0 bl        2 defN  1-Feb-85 00:00 META-INF/
-rw----     2.0 fat     3244 bl     1022 defN  1-Feb-85 00:00 META-INF/MANIFEST.MF
-rw----     1.0 fat        0 b-        0 stor  1-Feb-85 00:00 META-INF
-rw----     2.0 fat        0 bl        2 defN 21-Nov-17 14:28 META-INF/maven/
-rw----     2.0 fat        0 bl        2 defN 21-Nov-17 14:28 META-INF/maven/org.eclipse.jetty/
-rw----     2.0 fat        0 bl        2 defN 21-Nov-17 14:28 META-INF/maven/org.eclipse.jetty/jetty-http/
-rw----     2.0 fat      103 bl      100 defN 21-Nov-17 14:28 META-INF/maven/org.eclipse.jetty/jetty-http/pom.properties

comparing to other jars -rw---- looks wrong for dir

**Comment by isidorkin** [comment]
moreover, there are 2 instances of META-INF
-rw---- 2.0 fat 0 bl 2 defN 1-Feb-85 00:00 META-INF/
-rw---- 1.0 fat 0 b- 0 stor 1-Feb-85 00:00 META-INF

**Comment by shs96c** [comment]
This is a buck problem. I can fix this.

**Comment by shs96c** [comment]
Underlying issue logged as a buck bug: https://github.com/facebook/buck/issues/1790

**Comment by barancev** [comment]
We've migrated from buck to bazel and stopped repacking jetty. so this issue is not actual anymore.
