### ISSUE TITLE
INFO level logs visible in console after selenium 3.5.2 version

### ISSUE THREAD

**Issue by ezywebs** [SeleniumHQ/selenium#5544]
OS:  
 Windows 10
Selenium Version:  
3.5.2 +
Browser:  
FF, Chrome

Since version 3.5.2 Selenium sends all debugging info to console, so I am able to see all requests at INFO level. In 3.5.1 version it didn't happen. 
I am using watir gem(6.10) with selenium-webdriver gem.
Search in google gave some advices but none of them helped. Can you advice how to silence all the debug info, or how to increase logging level?

**Comment by titusfortner** [comment]
Default is set to `:warn` so you shouldn't be seeing `INFO` level from Selenium directly.

Adjusting logging for Watir & Selenium:
https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#logging
and
http://watir.com/watir-6-6/#watir-logger
