### ISSUE TITLE
'Click' action doesn't work on IE11 with py-selenium

### ISSUE THREAD

**Issue by SouWilliams** [SeleniumHQ/selenium#5545]
## Meta -
OS:  Windows10

Selenium Version:  3.8.1

Browser:  IE11

Browser Version:  11.248.16299.0

## Expected Behavior -
The 'Click' action can click button or any clickable elements.
## Actual Behavior -
With py-selenium IEServerDriver, the 'Click' action doesn't work. Cannot click any button on the page, no errors display in the IDE(intellij IDEA)

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by SouWilliams** [comment]
[py-selenium.zip](https://github.com/SeleniumHQ/selenium/files/1766374/py-selenium.zip)
I have attached the project under this topic. I use Intellij IDEA.
Thanks

**Comment by barancev** [comment]
The site http://tp6wdp.nanshan.com.tw:8888/ is not externally accessible.

**Comment by SouWilliams** [comment]
@barancev Sorry, my fault. Pls check the latest source code.
[py-selenium.zip](https://github.com/SeleniumHQ/selenium/files/1769367/py-selenium.zip)

**Comment by betaedu27** [comment]
Hello I'm having the same problem, I cant click on any element. And I'm not getting any error.

OS: Windows10
Selenium Version: 3.8.1
Python Version: 3.6.3
Browser: IE11

**Comment by barancev** [comment]
Sorry for leaving this issue unanswered for long time. I should admit that the provided sample works for me. The most probable reason for "selenium does not click and there are no error messages" behavior is a non-100% zoom setting in browser or operating system. They both should be set to 100%.
