### ISSUE TITLE
Testing with Scala Selenium and javascript

### ISSUE THREAD

**Issue by MarcPlanas** [SeleniumHQ/selenium#5550]
I can't test elements with JavaScript on it. I have this code for testing:

```
 go to "whateverAdress"
 val element = xpath("//*[@class='btn']").webElement
 element.click()
 val inputBox = xpath("//input[@id='578551eac5741search']").webElement
 inputBox.sendKeys("text")
```

And I get the error below:

> [info] org.openqa.selenium.ElementNotInteractableException: You may only interact with visible elements

The second object appears after the first one is clicked. It happens to every web page I try it. How I make the second element visible?

Thanks 

## Meta -
OS:  

:  

Browser:  
<!-- chrome,  Firefox

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
