### ISSUE TITLE
Unable to take screenshot in Selenium 3.9.1 because of FileUtils 

### ISSUE THREAD

**Issue by AshishCircl** [SeleniumHQ/selenium#5552]
Written this code for ScreenShot but facing issue for FileUtils please provide solution or alternate way to take screenshot 
 public void getscreenshot() throws Exception 
      {
              File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
          
              FileUtils.copyFile(scrFile, new File("D:\\screenshot.png"));
      }

**Comment by barancev** [comment]
What's the issue exactly?

**Comment by mttSpierings** [comment]
Would something like this solve your problem?

`((ITakesScreenshot)driver).GetScreenshot().SaveAsFile("FilePathAndName.png", ScreenshotImageFormat.Png);`

**Comment by barancev** [comment]
Closing the issue due to lack of information.
