### ISSUE TITLE
WebDriver.switchTo().window(String) does not switch to main document in Firefox 57 but it does in Chrome 62 and Firefox 45.

### ISSUE THREAD

**Issue by bochulindra** [SeleniumHQ/selenium#5555]
## Meta -
OS:  
macOS High Sierra (10.13.3)
Selenium Version:  
3.9.1
Browser:  
Firefox 
Browser Version:  
57 (64-bit)

## Expected Behavior -

1. I switch to a frame using WebDriver.switchTo().frame()
2. I switch to a different window using WebDriver.switchTo().window(String)
3. I switch back to the original window using WebDriver.switchTo().window(String)
4. In Chrome 62 (64-bit) and FF45, I am not inside the frame I switched to in step 1. In Firefox 57, I expect to behave the same as Chrome 62 (64-bit) and FF45.

## Actual Behavior -

4. In Firefox 57, I AM inside the frame I switched to in step 1. I am seeing different behavior than in Chrome 62 (64-bit) and FF45.

## Steps to reproduce -

See Expected Behavior above.

**Comment by lmtierney** [comment]
This is reported to geckodriver here https://github.com/mozilla/geckodriver/issues/610
