### ISSUE TITLE
Click does nothing for a dynamic element within a frame

### ISSUE THREAD

**Issue by srigney** [SeleniumHQ/selenium#5557]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.0.1, RobotFramework 3.0, Python 2.7
Browser:  
Internet Explorer
Browser Version:  
11.248.16299.0

## Expected Behavior -
Should be able to click on a dynamically enabled element within a frame.
## Actual Behavior -
The click action shows as successful in the logs, but nothing actually happens. 
## Steps to reproduce -
Below are screen shots 
App/Frame undr test
![2018-03-01_0837](https://user-images.githubusercontent.com/20686626/36868111-308ac324-1d4c-11e8-8f09-ea6bba3a1703.png)

DOM
![2018-03-01_0832](https://user-images.githubusercontent.com/20686626/36868098-1d3acc38-1d4c-11e8-8746-b8eecc1a5281.png)

RobotFramework Log
![2018-03-01_1212](https://user-images.githubusercontent.com/20686626/36868151-52074bbc-1d4c-11e8-89ac-b3f430f0a682.png)

Code snippet
![2018-03-01_1236](https://user-images.githubusercontent.com/20686626/36868558-8d86ded6-1d4d-11e8-8112-28d01623a248.png)

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by betaedu27** [comment]
Hello,

Any news about this?

**Comment by jimevans** [comment]
@betaedu27 The development team is still awaiting a repro case, which includes a set of pages (or links to a public page) that can be tested against. We can take no action on the issue until and unless that is provided.

**Comment by srigney** [comment]
Well I am not working with a public website so I can't give you access to ours. I thought I had provided enough information to get some helpful insight as to what the issue might be. Neither me nor my team has time to build something out for you to debug. so I guess you can close this ticket.

**Comment by p0deje** [comment]
Сlosing since there is no way to reproduce it. I'll re-open should we have such a script.
