### ISSUE TITLE
select2 menus do not work in firefox-driver

### ISSUE THREAD

**Issue by SiKing** [SeleniumHQ/selenium#5558]
## Meta -
OS:  
 any
Selenium Version:  
 any after 3.3.1, tested up to 3.8.1
Browser:  
 Firefox
Browser Version:  
 any after 52, tested up to 58

## Expected Behavior -
 select2 (see https://select2.org/dropdown) menus should work in Firefox, same as other browsers

## Actual Behavior -
 select2 do not work correctly

## Steps to reproduce -
I have used the following (Java) code running through BrowserStack to test on various browsers.

```
driver.get("https://select2.org/dropdown");

List<WebElement> selectElements = driver.findElements(By.tagName("select"));
Assert.assertEquals(1, selectElements.size());

Select select = new Select(selectElements.get(0));
select.selectByValue("NV");
```

If the RemoteDriver is latest Firefox using latest Selenium version, I get:
```
org.openqa.selenium.WebDriverException: Element <option> could not be scrolled into view
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'mac-207-254-53-65.browserstack.com', ip: 'fe80:0:0:0:75:bdb3:579e:f092%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_51'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at org.openqa.selenium.support.ui.Select.setSelected(Select.java:324)
	at org.openqa.selenium.support.ui.Select.selectByValue(Select.java:201)
	at ...
Caused by: org.openqa.selenium.WebDriverException: Element <option> could not be scrolled into view
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'mac-207-254-53-65.browserstack.com', ip: 'fe80:0:0:0:75:bdb3:579e:f092%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_51'
Driver info: driver.version: unknown
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'SCG00845', ip: 'fe80:0:0:0:14:b5bd:eeda:a89a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version: unknown
```

This code works fine with other drivers - tested with Chrome, Edge, and IE. But more importantly: **this code works with Selenium version 3.3.1 + (last supported) Firefox 52**.

A workaround can be based on [this SO answer](https://stackoverflow.com/a/17757761/3124333).

**Comment by p0deje** [comment]
Select2 uses ul/li elements to represent dropdown to the user. It's not a standard select element, so you should use a different API to select element (e.g. click on dropdown, wait until the elements are shown, click on the option you need).

**Comment by SiKing** [comment]
So do I understand correctly that loss of functionality is not a defect? Because this works in Selenium 3.3.1. Also, if one Selenium-browser behaves different from at least three others, that is not a defect either? Because this works in Chrome, Edge, and IE.

**Comment by lmtierney** [comment]
So looking at the page, it has nothing to do with select2. There is a hidden select element above the select2 widget that the prior drivers are hitting. Since it's hidden, firefox with geckodriver isn't able to select it. This would be an issue for them https://github.com/mozilla/geckodriver/issues

**Comment by rangercoder** [comment]
@SiKing hi,I have also encountered the same problem with you.At now,Do you have solve it?Thank you very much.

**Comment by rangercoder** [comment]
@SiKing hi,thanks for your reply. I don't understand what is SeleniumHelper that can't find on selenium api.

**Comment by rangercoder** [comment]
@SiKing Can you share your SeleniumHelper code?Thx a lot

**Comment by rangercoder** [comment]
@SiKing hello,I have added it .But it still occur the same problem.this is my code:
`try{
			//SeleniumHelper.scrollTo(driver, element);
			JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
			jsExecutor.executeScript("arguments[0].scrollIntoView(true);", element);
			Select select = new Select(element);
			select.selectByVisibleText(text);
			Logger.Output(LogTypeName.INFO, "select the value is:" + text +".");
		}catch(UnexpectedTagNameException e){
			Logger.Output(LogTypeName.ERROR, "element:" + element +"is not a select.");
		}`
Thank you very much again.

**Comment by SiKing** [comment]
@rangercoder Yes, the whole point of this ticket is that you cannot use `Select()`. If you read through my code carefully, you will see that.

**Comment by rangercoder** [comment]
@SiKing Ok,I get it.Thank you very much.
