### ISSUE TITLE
Some error codes defined for Java client are not in sync with the actual W3C spec

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#5562]
Some error codes defined in [KNOWN_ERRORS](https://github.com/SeleniumHQ/selenium/blob/176b4a9e3082ac1926f2a436eb346760c37a5998/java/client/src/org/openqa/selenium/remote/ErrorCodes.java#L215) map are not in sync with the actual W3C spec at https://www.w3.org/TR/webdriver/#handling-errors

These codes are:

- `no such alert`: current: 404, expected: 400
- current: `invalid element selector`, expected: `invalid selector`
- `no such frame`: current: 404, expected: 400
- `no such window`: current 404, expected: 400
- `stale element reference `: current: 404, expected: 400

**Comment by p0deje** [comment]
@mykola-mokhnach Pull requests are more than welcome!

**Comment by barancev** [comment]
I wonder why they are 400 in the specification, there was a patch [1] to change them to 404. It seems to be reverted somehow.

@shs96c @andreastt can you please comment?

[1] https://github.com/w3c/webdriver/pull/1043 that

**Comment by andreastt** [comment]
@mykola-mokhnach You are linking to the W3C’s CR of the specification, whereas vendors follow the ED at https://w3c.github.io/webdriver/webdriver-spec.html#dfn-error-code.

The list of error codes above is correct.

**Comment by mykola-mokhnach** [comment]
@andreastt Do you mean that https://www.w3.org/TR/webdriver/#handling-errors is out of date?

**Comment by andreastt** [comment]
@mykola-mokhnach I mean that it doesn’t reflect the reality in the implementations. It is generally avisable to avoid the W3C /TR namespace and look at the latest drafts of the specifications. You can think of most /TR specs as intended for lawyers.

**Comment by mykola-mokhnach** [comment]
OK, thanks. Can I edit the issue description then, because the error codes in the actual Java implementation look good in the github spec, but the w3c code for `invalid selector` is still not ok?

**Comment by andreastt** [comment]
I’m unfamiliar with ErrorCodes.java, but it lists the `invalid selector` code as tied to `InvalidSelectorException` and associated with the 400 HTTP status code. I don’t know what the additional true/false arguments do, but this seems in sync with the spec?

**Comment by mykola-mokhnach** [comment]
N/W, I've double checked the recent master and it's in sync. Thanks for your time
