### ISSUE TITLE
Selenium does not allow negative values for Set_window_position 

### ISSUE THREAD

**Issue by flamaster2016** [SeleniumHQ/selenium#5563]
## Meta -
OS:  Linux mint 18.3

Selenium Version:  3.9.0

Browser:  Chrome 64 using chromedriver 3.25

Browser Version:  

64
## Expected Behavior -
Set_window_position moves window to described position even if position value is negative. 
## Actual Behavior -
Set_window_position moves window to 0 if provided position is negative. 
## Steps to reproduce -

1. Launch chrome via selenium webdriver and Python. 
2. Attempt to move window with Set_window_position to 0,-50. 
3. Validate window position with get_window_position - it is 0,0.

**Comment by p0deje** [comment]
Negative positions are a valid payload and should move the window to the left or top of the screen. If you want window to move to 0, 0, you should specify that values.

**Comment by lmtierney** [comment]
This is driver-implementation specific. Selenium is sending what you are giving it. If you believe there is an issue, raise it with the driver vendor.

```
>>> driver.set_window_position(-100, -100)
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:52587/session/a5a23a3141308dbd0874f0b1ea94cc36/window/current/position {"x": -100, "y": -100, "windowHandle": "current", "sessionId": "a5a23a3141308dbd0874f0b1ea94cc36"}
```

**Comment by flamaster2016** [comment]
I'm confused where the issue is. On a different system (rasp pi noobs), it moves the window to the appropriate position (I. E. Y = - 100 moves the top of the window 100px above the top of the screen). On this system, it does not. Why?

**Comment by flamaster2016** [comment]
I also tried this with geckodriver 0.19.1 and Firefox quantum 58 and got the same result - the window is not positioned above 0.

**Comment by p0deje** [comment]
It might be a limitation of OS window manager. In any event, I'd recommend raising this on  [ChromeDriver bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).

**Comment by flamaster2016** [comment]
I've also tried this on Ubuntu 16.04 with Selenium 3.9.0 and ChromeDriver 3.25 (with Chrome 64) and it works as expected - the browser window moves to the negative values and is positioned appropriately.
