### ISSUE TITLE
Issue With Javascript Mouse Hover on Firefox 57

### ISSUE THREAD

**Issue by ppanuganti** [SeleniumHQ/selenium#5565]
## Meta -
OS : Windows 7
Browser:
Firefox
Browser Version:
Firefox  57

Expected Behavior - 

The javascript mouse hover should work on the specified element

Actual Behavior - 

The mouse hover is not working, Though it doesn't throw any error the action is not performed

Description:
As the Actions class is not working with the geckodriver we are going with javascript to perform mouseover on the element and observing that the execution is passing but the action is not happening.

Javascript used:
var evObj = document.createEvent('MouseEvents');evObj.initMouseEvent('mouseover', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null); document.getElementById('logo').dispatchEvent(evObj);

Please Suggest how to perform mouse hover on required element in FF 57 and above versions.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
