### ISSUE TITLE
Add support for sourceMapUrl when fetching Chrome logs

### ISSUE THREAD

**Issue by swrobel** [SeleniumHQ/selenium#5567]
## Meta -
Selenium Version:  selenium-webdriver (ruby) 3.9.0

Browser:  Chrome

Browser Version:  64.0.3282.186 (Official Build) (64-bit)

## Expected Behavior -
Fetching browser logs has the ability to return the sourceMapUrl (original file & line) where the log entry was triggered.

## Actual Behavior -
Source Maps are not available, at least in the Ruby Gem

## Steps to reproduce -

Generate some input to [this page](https://mdn.github.io/devtools-examples/sourcemaps-in-console/index.html)

Without sourcemaps:
`main.js:8 Hello Stefan`

With sourcemaps:
`main.coffee:4 Hello Stefan`

Chromium team has [provided input](https://bugs.chromium.org/p/chromium/issues/detail?id=812153#c9) for how to access sourceMapUrls but it is a little beyond me to understand how to get this with the remote debugging protocol.

**Comment by swrobel** [comment]
Not stale

**Comment by AutomatedTester** [comment]
@swrobel does the new Selenium 4 console log APIs give you what you need?

**Comment by swrobel** [comment]
@AutomatedTester I don't know ... I can't even figure out how to get it to work in v4 of the ruby library. `browser.manage.logs.get(:browser)` returns `[]` even when I have console logs in my js.

**Comment by diemol** [comment]
Have you checked https://www.selenium.dev/documentation/webdriver/bidi_apis/ and https://www.selenium.dev/documentation/support_packages/chrome_devtools/?
