### ISSUE TITLE
Selenium Password Management

### ISSUE THREAD

**Issue by hiren-patel1** [SeleniumHQ/selenium#5571]
## Meta -
OS:  Linux/Windows

Selenium Version:  any future release

Browser:  CHROME/IE/FF

Browser Version:  

## Expected Behavior -
When i was using tools like UFT ( Unified Functional Testing by HP ) - they have provided a saperate password encrypter tool or online service - where user can just enter their password and get encrypted password.

And then use webdriver.sendkeys_encrypted ( Assuming - that selenium can provide function like this ),
which internally decrypts the password and sends to browser password field.

This will be a really good help for many who are putting their passwords in plain text in their selenium java code.

This is just a suggestion for the future. But certainly big step for passwords management for many.

**Comment by cjayswal** [comment]
I think the feature you are expecting can be considered out of scope for selenium. It should be implemented in your testing framework just like in [QAF](https://qmetry.github.io/qaf/latest/locating_elements.html#self-descriptive-locator).
In QAF it has inbuilt [listener](https://github.com/qmetry/qaf/blob/04f9ab9ed851ffd0170f2ea43b715209b632c8c3/src/com/qmetry/qaf/automation/ui/webdriver/ElementMetaDataListener.java) available that does the [decryption](https://github.com/qmetry/qaf/blob/04f9ab9ed851ffd0170f2ea43b715209b632c8c3/src/com/qmetry/qaf/automation/ui/webdriver/ElementMetaDataListener.java#L150) before sendkeys if meta-data of element specifies type `password`. You also can specify your custom encryption.

**Comment by hiren-patel1** [comment]
Thanks,
Arpit

On Mar 8, 2018, at 10:37 PM, cjayswal <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the feature you are expecting can be considered out of scope for selenium. It should be implemented in your testing framework just like in QAF<https://qmetry.github.io/qaf/latest/locating_elements.html#self-descriptive-locator>.
In QAF it has inbuilt listener<https://github.com/qmetry/qaf/blob/04f9ab9ed851ffd0170f2ea43b715209b632c8c3/src/com/qmetry/qaf/automation/ui/webdriver/ElementMetaDataListener.java> available that does the decryption<https://github.com/qmetry/qaf/blob/04f9ab9ed851ffd0170f2ea43b715209b632c8c3/src/com/qmetry/qaf/automation/ui/webdriver/ElementMetaDataListener.java#L150> before sendkeys if meta-data of element specifies type password. You also can specify your custom encryption.

**Comment by barancev** [comment]
Yes, this feature is definitely out of scope.
