### ISSUE TITLE
Capybara session becomes unresponsive after empty response

### ISSUE THREAD

**Issue by jcarlson** [SeleniumHQ/selenium#5577]
## Meta -
OS:  
OS X 10.13.3

Selenium Version:  
Ruby 2.3.3p222
Selenium Webdriver 3.10.0 
ChromeDriver 2.33.506106

Browser:  
Chrome 65

Browser Version:  
65.0.3325.146 (Official Build) (64-bit)

## Expected Behavior -
Chrome Driver is responsive after receiving an empty response. Previously, it was possible to assert the contents of the browser when an empty response was received, such as `expect(page).to have_content('ERR_EMPTY_RESPONSE')`

## Actual Behavior -
Chrome Driver becomes unresponsive after receiving an empty response

## Steps to reproduce -
```ruby
Capybara.default_driver = :selenium_chrome
# => :selenium_chrome

session = Capybara.current_session
# => #<Capybara::Session>

session.visit 'https://www.github.com'
# => nil

session.visit 'http://notfound.google.com'
Net::ReadTimeout: Net::ReadTimeout
from /Users/jcarlson/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'

session.visit 'https://www.google.com'
Net::ReadTimeout: Net::ReadTimeout
from /Users/jcarlson/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
```

This issue appears to have cropped up after Chrome self-updated to v65. In order to get it working again, I have tried upgrading `selenium-webdriver` and `capybara` gems as well as the `chromedriver` installed via Homebrew.

At this point, I am unable to confirm whether this is a problem with `chromedriver`, `selenium-webdriver`, or Chrome itself.

**Comment by jcarlson** [comment]
Never mind, I've figured this out. It was not apparent to me that the `chromedriver-helper` gem was [vendoring it's own version](https://github.com/flavorjones/chromedriver-helper#description) of `chromedriver` in `$HOME/.chromedriver-helper`, rather than using an available system version.

Following [these steps](https://github.com/flavorjones/chromedriver-helper#updating-to-latest-chromedriver) resolved the problem.

Additionally, as our CircleCI build installs Chrome Stable Current on every build, I've added the following to my RSpec suite to ensure the latest Chrome Driver is also available:

```ruby
RSpec.configure do |config|
  config.before(:suite) do
    # ensure the latest Chrome Driver is installed
    Chromedriver::Helper.new.update
  end
end
```

**Comment by titusfortner** [comment]
@jcarlson for the record, `webdrivers` gem will be superior to the chromedriver-helper because it doesn't deal with shims or dealing with PATH. It just downloads the latest driver (chrome, firefox, IE, Edge) and tells the Ruby code to use that one instead of what is in PATH.
