### ISSUE TITLE
safari Webdriver() throws AttributeError with default arguments for python client driver

### ISSUE THREAD

**Issue by mingeth** [SeleniumHQ/selenium#5578]
## Meta -
OS:  linux
Selenium Version:  3.10.0
Browser:  Safari/Version 11.0.3 (13604.5.6)

## Expected Behavior -
launching webdriver.Safari() from python with default arguments should create a safaridriver instance

## Actual Behavior -
AttributeError: 'WebDriver' object has no attribute 'service'

## Steps to reproduce -
>>> from selenium import webdriver
>>> s = webdriver.Safari()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/selenium/webdriver/safari/webdriver.py", line 49, in __init__
    self.service.start()
AttributeError: 'WebDriver' object has no attribute 'service'

**Comment by mingeth** [comment]
pull request created at branch python-safari-webdriver-defaultargs

**Comment by barancev** [comment]
PR merged as 2a0f63d19bd6e666ad432ee459762489d6b6033a

**Comment by lmtierney** [comment]
It is fixed in the trunk and will be in the next release

**Comment by suchau3** [comment]
OS: MacOS 10.13.4
Selenium Version: 3.11.0
Browser: Safari/Version 11.1 (13605.1.33.1.2)

Hi, is this solved and release updated yet? 

I get the same error as @mingeth and @corytu 

File ".../selenium/webdriver/safari/webdriver.py", line 49, in __init__
    self.service.start()
AttributeError: 'WebDriver' object has no attribute 'service'

**Comment by corytu** [comment]
@suchau3 Please see @lmtierney's comment right above yours.

> It is fixed in the trunk and will be in the next release

**Comment by mithunsureshqa** [comment]
how do we fix this locally?  i am new to this.

**Comment by da-false9** [comment]
You need to go to the directory where is saved your webdriver.py for Safari.
In my case it's /Users/YOUR_USER_NAME/vitenv/lib/python3.6/site-packages/selenium/webdriver/safari 
After this you need to open webdriver.py and to add those 2 strings of the code that were added in the decision for this issue.

**Comment by swissbeats93** [comment]
I get more errors after that, specifically which 2 lines should be appended and on which part of web driver.py
