### ISSUE TITLE
Selenium HTML Runner not working behind corporate proxy server

### ISSUE THREAD

**Issue by Redirts** [SeleniumHQ/selenium#5582]
## Meta -
OS:  Linux RedHat 7

Selenium Version:  selenium-html-runner-3.4.0.jar + IDE 2.9.1
Browser:  Firefox

Browser Version:  Firefox 57.0.4

## Expected Behavior
Be able to specify (in some way) the proxy hostname/IP and Port so that Selenium HTML runner can run behind/through a proxy

## Actual Behavior -
I get a timeout executing selenium test cases because these particular webpages need to be opened only when the proxy is defined.

## Steps to reproduce -

I tried passing to Java the proxy parameter (-D) in different manners but it does not seem to make a difference.

**Comment by Nassim07** [comment]
hey,
I have exacly the same problem, did anyone find the sollution ?
Please help.

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version
