### ISSUE TITLE
Unable to SendKeys with IEDriver 3.10 - crashes driver

### ISSUE THREAD

**Issue by StormCat007** [SeleniumHQ/selenium#5584]
## Meta -
OS:  Windows 10 & Windows 7 - exception capture was with windows 10

Selenium Version:   3.10 C# version, Visual Studio IDE. IE driver version 3.10

Browser:   Internet Explorer 11

Browser Version:  11.00.14393.2007

## Actual Behavior - SendKeys causes the driver to crash the following exception is captured

Faulting application name: IEDriverServer.exe, version: 3.10.0.0, time stamp: 0x5a999b44
Faulting module name: IED4E61.tmp, version: 0.0.0.0, time stamp: 0x5a999b3d
Exception code: 0xc0000005
Fault offset: 0x00006a2a
Faulting process id: 0x9ad8
Faulting application start time: 0x01d3b70ba8909bc4

Unhandled exception at 0x0FEB6A2A (IED4E61.tmp) in IEDriverServer.exe: 0xC0000005: Access violation reading location 0x00000088.

## Steps to reproduce - Sample code below. NativeEvents are set to false & protected mode was set to off for all zones within the browser.
`            
InternetExplorerOptions internetExplorerOptions = new InternetExplorerOptions();
            internetExplorerOptions.EnableNativeEvents = false;

            InternetExplorerDriver ieDriver = new InternetExplorerDriver(internetExplorerOptions);

            ieDriver.Navigate().GoToUrl("http://google.com");

            System.Threading.Thread.Sleep(2000);
            
            IWebElement element = ieDriver.FindElementByName("q");

            element.SendKeys("test");

`

**Comment by jimevans** [comment]
Fixed in commit 2fe0d1a.
