### ISSUE TITLE
Error running Selenium sample file

### ISSUE THREAD

**Issue by iPenguin67** [SeleniumHQ/selenium#5585]
## Meta -
OS:  
Windows 7
Selenium Version:  
Selenium 2 WebDriver API (through Python)
Browser:  
Chrome

Browser Version:  
 64.0.3282.186 (Official Build) (64-bit)

I installed Selenium yesterday alongside Chromedriver and am trying to test its basic functionality. I created a hello.py python file with the sample code on the Selenium site (see end of post).

When I ran the file using python hello.py from the command line while in the enclosing folder, I got the error message in the 
attached file.
![selenium error](https://user-images.githubusercontent.com/20567444/37172373-969c06f4-22de-11e8-8f5c-9826fd1058d5.PNG)

Code run from hello.py:

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

**Comment by lmtierney** [comment]
What exact versions of the python bindings and chromedriver are you using?

**Comment by iPenguin67** [comment]
I used Chromedriver 2.36, the latest version on the site. As for the python bindings, I believe it is 3.10 based on the PyPi page, but I downloaded it via "pip install selenium" .

**Comment by lmtierney** [comment]
I cannot reproduce this, using your exact versions. My only suggestion is to make sure you don't have another geckodriver on your path.

**Comment by cgoldberg** [comment]
@iPenguin67 

> I used Chromedriver 2.36

Chromedriver 2.36 is not compatible with Chrome 64 (see: https://chromedriver.storage.googleapis.com/2.36/notes.txt)

**Comment by iPenguin67** [comment]
@cgoldberg I downgraded to Chromedriver 2.35 just now and am still getting the same error when I ran it. 
@lmtierney I did have a separate instance of Chromedriver in my local path, so I removed that. I still get an error, but only the first line (the one with gpu_process_transport_factory)

**Comment by lmtierney** [comment]
@iPenguin67 this is an issue with either chromedriver or chrome, please raise an issue with them.
