### ISSUE TITLE
Why IsSelect() is not working with Selenium?

### ISSUE THREAD

**Issue by dipakbachhav** [SeleniumHQ/selenium#5586]
-1
down vote
favorite

I am trying to check whether my radio button is selected or not using selenium IsSelect() method.

Kindly find below HTML code and please let me know a solution.

   <li _ngcontent-c6="">
    <input id="type__1" class="checkbox_question__0" type="radio" _ngcontent-c6="" autocomplete="off" name="radio-group__1">
    <label _ngcontent-c6="" for="mack_1">
    <div class="pseudo-check" _ngcontent-c6=""></div>
    Yes
    </label>
    </li>
    <li _ngcontent-c6="">
    <input id="Type__2" class="checkbox_question__0" type="radio" _ngcontent-c6="" autocomplete="off" name="radio-group__2">
    <label _ngcontent-c6="" for="mack_2">
    <div class="pseudo-check" _ngcontent-c6=""></div>
    No
    </label>
    </li>

I tried all possible solution but none of them are working. Please find beow sample code.

    @FindBy(xpath =".//*[@id='my-app']/div/parent/child/div[2]/div/ul/li[1]/label/div")
     WebElement RadioButton;

    @FindBy(xpath =".//*[@id='my-app']/div/parent/child/div[2]/div/ul/li[2]/label/div")
     WebElement RadioButton1;

    boolean radioBtnIsEnabled21 = RadioButton.isSelected();
    System.out.println("Is Yes radio button 21 Selected: "+radioBtnIsEnabled21);

    boolean radioBtnIsEnabled22 = RadioButton1.isSelected();

    System.out.println("Is No radio button 22 Selected: "+radioBtnIsEnabled22);

With above code I was expecting radioBtnIsEnabled22 should give me true value but with above code I am getting false value for both the radio buttons

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
