### ISSUE TITLE
About ChromeDriver TimeoutExecption

### ISSUE THREAD

**Issue by idlefire** [SeleniumHQ/selenium#5587]
## Meta -
OS:  Windows 10

Selenium Version:  3.8.1

Browser:  Chrome

Browser Version:  65.0.3325.146

## Expected Behavior -
If I visit the site timeout occurred. Use js to open a new tab, and before the closing of the tab.
## Actual Behavior -
Chrome's occurred timeout, but firefox not.
## Steps to reproduce -

```python
       browser_driver = driver.Chrome()
       browser_driver.set_page_load_timeout(10)
        try:
            browser_driver.get("https://wenku.baidu.com/")
        except TimeoutException:
            js = 'window.open("https://www.baidu.com/");'
            browser_driver.execute_script(js)
            handlers = browser_driver.window_handles
            browser_driver.switch_to.window(handlers[0])
            browser_driver.close()
```
![default](https://user-images.githubusercontent.com/18007341/37202306-1df5584e-23c5-11e8-972f-7125d8caed61.png)
![default](https://user-images.githubusercontent.com/18007341/37202324-286e5654-23c5-11e8-9a4d-fcbdbc4f33c9.png)

**Comment by Manikandan-Zoho** [comment]
I am also having the same issue while taking the screenshot in selenium 3.8.1, chrome version 63.0

**Comment by barancev** [comment]
Please retest with the latest chromedriver version 2.36 and the latest selenium version 3.10

**Comment by barancev** [comment]
Also make sure 10 seconds is enough to load the target page and increase page load timeout if necessary.

**Comment by idlefire** [comment]
emmm...
It also no work...
I just want to mak it jumps after 10s.

**Comment by barancev** [comment]
So what's the issue? The driver throws TimeoutException, as expected, if the page is loading too long.

**Comment by idlefire** [comment]
Same as before.
I want to execute js，but it will throws TimeoutExecption.

**Comment by barancev** [comment]
Because it times out too, the new page is loading too long.

**Comment by idlefire** [comment]
Firefox not occur it...
