### ISSUE TITLE
Firefox Driver 2.45 is 100% slower than 2.44

### ISSUE THREAD

**Issue by vladikoff** [SeleniumHQ/selenium#559]
Context see https://code.google.com/p/selenium/issues/detail?id=8551

**Comment by lukeis** [comment]
duplicate of #383 

please wait for a new release or build the latest from source or download the latest from our [ci](http://ci.seleniumhq.org/selenium-server-b4692eaa05633fc96c69b7198ed2040951c8a1c6.jar)
