### ISSUE TITLE
TypeError: Cannot read property 'start' of null starting up edge driver

### ISSUE THREAD

**Issue by lynseyp** [SeleniumHQ/selenium#5591]
## Meta -
OS:  
Windows 10
Selenium Version:  
4.0.0-alpha.1
Browser:  
Edge 14.14393
Browser Version:  
14.14393

## Expected Behavior -
Edge starts up ok using the following code:
  var edge = require('selenium-webdriver/edge');
  var edgeCaps = new edge.Options();
  edgeCaps.set('port','55555')
  return new webdriver.Builder()
  .withCapabilities(edgeCaps)
  .build();
## Actual Behavior -
Get the following error on .build()
"TypeError: Cannot read property 'start' of null"

## Steps to reproduce -
Running using     node v8.9.3 and cucumber 4.0.0
using ide VSCode in debug mode.

Tracked the problem down to createSession in edge.js
Changing line 200 / 201:
```
  static createSession(options, service = getDefaultService()) {
    let client = service.start().then(url => new http.HttpClient(url));
```

To:
```
  static createSession(options, opt_serviceExecutor) {
    let service = opt_serviceExecutor || getDefaultService();
    let client = service.start().then(url => new http.HttpClient(url));
```

I have attached an example project that can be run using the above config, that should reproduce the error.
[EdgeIssue.zip](https://github.com/SeleniumHQ/selenium/files/1797437/EdgeIssue.zip)

**Comment by jleyba** [comment]
Yup, looks like the builder sometimes passes `null` which overrides the default value. Want to send a PR?

**Comment by liminzhu** [comment]
Run into the same problem today and looks like it comes from 

https://github.com/SeleniumHQ/selenium/blob/5f52b02163ce12ec6612d58a6989f45f064ac7ea/javascript/node/selenium-webdriver/index.js#L662

and

https://github.com/SeleniumHQ/selenium/blob/5f52b02163ce12ec6612d58a6989f45f064ac7ea/javascript/node/selenium-webdriver/edge.js#L200

null overrides the default value, so changing service to undefined does the trick for me, but I don't know the code base well enough to say it won't trigger some other weird issue.

**Comment by diemol** [comment]
After checking the code base, it looks like this was already fixed. If the issue still persists after trying with `beta-2` or more recent version, please feel free to comment or to open a new issue.
