### ISSUE TITLE
Unable to create new session. 

### ISSUE THREAD

**Issue by flik** [SeleniumHQ/selenium#5592]
## Meta -
OS:  
 Windows 8.1
Selenium Version:  
 selenium-server-standalone-3.9.1.jar
Browser:  
Firefox

Browser Version:  
49.0.1

## Expected Behavior -
It should create session

## Actual Behavior -
Unable to create new session. 
## Steps to reproduce -
$ java -jar selenium-server-standalone-3.9.1.jar

http://127.0.0.1:4444/wd/hub/static/resource/hub.html

try to create firefox session.

**Comment by ShyamKunda** [comment]
It seems steps to reproduce link is broken.

**Comment by flik** [comment]
I fixed this issue by selenium version change. First I was running version selenium-server-standalone-2.39.0 and session creation issue was coming then downloaded other version selenium-server-standalone-3.3.0 It is running fine now.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by flik** [comment]
Hi @barancev,
Here are very easy steps to reproduce. Just download the selenium version : selenium-server-standalone-3.9.1.jar 
Then run it by command: 
`$ java -jar selenium-server-standalone-3.9.1.jar`

It will start correctly but when you visit the link: http://127.0.0.1:4444/wd/hub/static/resource/hub.html
There are two buttons and one for create new session, just try to create new session with firefox. 
You will see an error in red color : Unable to create new session.

This is the problem which stop running every code by selenium.

**Comment by barancev** [comment]
Please show the server log, there must be an error message in the log that explains why it can't start a session.

**Comment by flik** [comment]
Here is screen short: [https://ibb.co/hkknux](https://ibb.co/hkknux)

output on console: 
```
09:24:10.804 INFO - Selenium Server is up and running on port 4444
2018-04-06 09:26:54.346:INFO:osjshC.ROOT:qtp654845766-11: org.openqa.selenium.re                                                     mote.server.WebDriverServlet-d8355a8: Initialising WebDriverServlet
09:26:55.351 INFO - Found handler: org.openqa.selenium.remote.server.commandhand                                                     ler.Status@1fb3e934
09:26:55.366 INFO - /status: Executing GET on /status (handler: Status)
09:26:55.843 INFO - Found handler: org.openqa.selenium.remote.server.commandhand                                                     ler.GetAllSessions@622d6a65
09:26:55.847 INFO - /sessions: Executing GET on /sessions (handler: GetAllSessio                                                     ns)
09:27:05.237 INFO - Found handler: org.openqa.selenium.remote.server.commandhand                                                     ler.BeginSession@272ff844
09:27:05.237 INFO - /session: Executing POST on /session (handler: BeginSession)
09:27:05.675 INFO - Capabilities are: Capabilities {browserName: chrome}
09:27:05.679 INFO - Capabilities {browserName: chrome} matched class org.openqa.                                                     selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ch                                                     rome.ChromeDriverService)
```

**Comment by auchytil** [comment]
@flik: Isn't it caused by a version mismatch between the version of the webdriver and the version of the server?

**Comment by barancev** [comment]
According to the screenshot and the log, you attempt to run Chrome, where as original report was about Firefox. And I bet you have no chromedriver (and geckodriver) in PATH.

This is issue tracker, not a support channel. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
