### ISSUE TITLE
Elements index Element

### ISSUE THREAD

**Issue by GodStar88** [SeleniumHQ/selenium#5597]
var post = driver.FindElements(By.XPath("//div[@class='_5pcr userContentWrapper']"));
for (int i = 0; i < post.Count; i++)
{
       string str = post.ElementAt(i).FindElement(By.XPath("//div[@class='_5pbx userContent _3576']")).Text;
}

Hello. I just used this code
I got the same result (str).
please help me

**Comment by lmtierney** [comment]
Duplicate of #5501

**Comment by GodStar88** [comment]
I can't find the way. Please help me
