### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError

### ISSUE THREAD

**Issue by LeeKisu** [SeleniumHQ/selenium#5598]
## Meta -
OS:  
Ubuntu Server 16.04 (64-bit)
Selenium Version:  

Browser:  
Firefox 

Browser Version:  
Mozilla Firefox 58.0.2

Ruby 2.5.0

## Expected Behavior -
Just run the selenium-webdriver

## Actual Behavior -
stack backtrace:: address not available (Selenium::WebDriver::Error::UnknownError)

## Steps to reproduce -
`require 'selenium-webdriver'
require 'rspec'
require 'headless'

puts "headless..."
headless = Headless.new
headless.start

puts "selenium..."
driver = Selenium::WebDriver.for :firefox`
When i run this code, the error is occur, address not available (Selenium::WebDriver::Error::UnknownError).
What's problem?

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
