### ISSUE TITLE
How do i upgrade chromedriver for selenium standalone (nodeJS)

### ISSUE THREAD

**Issue by malliapi** [SeleniumHQ/selenium#5599]
The tittle is pretty self explanatory but my situation is that i need to use Chrome 65 which only works with chromedriver 2.36. I see the nodejs version is still at 3.6.0 for selenium. When will the be updated?

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
