### ISSUE TITLE
Java Heap Space Error when File Upload to Remote Grid

### ISSUE THREAD

**Issue by gheuer** [SeleniumHQ/selenium#560]
I'm trying to upload a 300mb .zip file using a remote grid, LocalFileDetector and RemoteWebElement sendKeys but i keep getting Java Heap Space error. I have already try increasing the java -Xmx and -Xms arguments both in the grid node and in the testing environment to 1gb, 2gb and 3gb but the process always throws the exception when its consumming about 1.7gb.
Any workaround or solution for this issue? Thank you

Environment: 
Selenium Grid and Selenium firefox node with docker containers. 
Java 7
Selenium 2.45.0

java.lang.OutOfMemoryError: Java heap space
java.util.Arrays.copyOf(Arrays.java:2367)
java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587)
java.lang.StringBuffer.append(StringBuffer.java:332)
org.openqa.selenium.internal.Base64Encoder.encode(Base64Encoder.java:65)
org.openqa.selenium.io.Zip.zipFile(Zip.java:76)
org.openqa.selenium.remote.RemoteWebElement.upload(RemoteWebElement.java:104)
org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:93)...

**Comment by barancev** [comment]
Selenium is intented to be a UI automation tool. We're not going to optimize it to allow uploading large files, it is out of scope.

**Comment by shs96c** [comment]
You need to make sure the server is started with a max heap at least four times larger than the zip file.
