### ISSUE TITLE
Chromedriver leaves forked Chrome instances hanging in background after test run (with large CPU load)

### ISSUE THREAD

**Issue by garrymann** [SeleniumHQ/selenium#5600]
## Meta
OS:  
Microsoft Windows [Version 10.0.16299.248] x64
Selenium Version:  
2.53.1
Browser:  
Chrome 65 x64
Browser Version:  
Version 65.0.3325.146 (Official Build) (64-bit)
Additional rerequisites:
- ChromeDriver (2.36) 
- NodeJS (v8.10.0)
- cucumber: ^1.3.0
- protractor: ^5.1.1

## Expected Behavior -
2. The chromedriver.exe should stop and its Chrome instances as well.

## Actual Behavior -
2. The chromedriver.exe stops 4-5 secs after the tests completed. Then the forked Chrome instances stay in the background as running processes with huge CPU usage.

## Steps to reproduce -
1. Run at least 1 failing test with CucumberJS and Protractor. 
note: I'm running e2e tests against an Angular 1.6 application
2. Examine the processes in Task manager.

## Note:
This issue was introduced by the latest Chrome and ChromeDriver update. No symptomps were present in previous versions.

## Screenshot:
![Actual result](https://user-images.githubusercontent.com/17498617/37300130-8604fc2a-2625-11e8-8503-6cc57450ed6d.png)

**Comment by cgoldberg** [comment]
> Run at least 1 failing test with CucumberJS and Protractor.

does your code always call quit() on the driver instance when a test fails? (usually done as a teardown/cleanup fixture in your framework)

**Comment by garrymann** [comment]
@cgoldberg Hi!
The .quit() is handled by Protractor as far as I know. So it is not necessary since runner [teardownEnv ](https://github.com/angular/protractor/blob/35dcea01bf/lib/runner.js#L418) will take care of that for you.

**Comment by barancev** [comment]
If you (or Protractor) called quit, but chromedriver could not stop the browser -- report this issue to chromedriver: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by garrymann** [comment]
@barancev Done. Thanks.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2311

Things I've tried but did not resolve the issue:
reinstall chrome (v65 x64)
disable and remove extensions
run it without a single chrome instance open in the background
delete npm-cache
redo npm i
update to npm 5.7  (latest)
update to node 8 (latest LTS)
update windows 10: Version 10.0.16299.248

Any other ideas?

**Comment by cgoldberg** [comment]
> it is not necessary since runner teardownEnv 
> will take care of that for you

and what happens when something crashes unexpectedly before your teardown is called?

**Comment by garrymann** [comment]
tried to call the quit manually as a hook but it can't reach the instance by this time:
this.registerHandler('AfterFeatures', () => {
        logger.warn('Force closing ChromeDriver.');
        return browser.driver.quit();
    });

So in conclusion nothing happens. After trying many workarounds (and sticking to the latest versions) I guess Google Chrome needs to fix stuff with Chrome and Chromedriver then.

Thanks anyway!

**Comment by farmazonne** [comment]
FYI: Don't know why but deleting arg "--no-sandbox" fixed the issue for me.

**Comment by nolmit** [comment]
removing "no-sandbox" helped for me too

**Comment by Vishwa1** [comment]
I was facing the same issue and was so annoyed with it. Had to always keep an eye on CPU usage and kill the process. However, removing "no-sandbox" resolved my problem too.

**Comment by elsticky** [comment]
Saw the same problem, also removed --no-sandbox from my protractor config and the high CPU load disappeared. Took a long time to find this out since the problem started occurring previous week and the --no-sandbox place was already in there for a month or so.

**Comment by RenaudF** [comment]
`ps | grep Chrome | awk '{print $1}' | xargs kill` can help you tidy up if you're on a *nix system. Not sure what the windows equivalent would look like.

**Comment by jmhdez** [comment]
I don't know why, but when I add `--disable-gpu` the problem goes away.

**Comment by TARIFABBAS** [comment]
After removing --no-sandbox from chrome options, there is coming problem in opening chrome browser also.
Anyone, have encounter the same problem and what's the solution?
