### ISSUE TITLE
InternetGetCookieEx2 could not be located in the dynamic link library WININET.DLL

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#5603]
## Meta -
OS:  
Windows 7
Selenium Version:  
IEDriverServer win 32 version 3.11
Selenium python bindings 3.11
Browser:  
Internet Explorer 10

Browser Version:  
Internet Explorer 10

## Expected Behavior -
Selenium starts up IE 10.

## Actual Behavior -
Error message pops up with text:
the procedure entry point InternetGetCookieEx2 could not be located in the dynamic link library WININET.DLL

## Steps to reproduce -
```
from selenium import webdriver
webdriver.Ie()
```

## Notes:
* Not happening on IE 11 windows 10/8/7
* Not happening with webdriver version 3.10
* already tried SFC/SCANNOW

**Comment by jimevans** [comment]
This is a direct result of the cookie work that was done in 3.11. I thought I’d guarded against that scenario, but apparently I screwed something up.

**Comment by jimevans** [comment]
@PhillippSelenium This might be too much to ask, but what happens with IE11 on Windows 7? The API that the driver is attempting to call is WinINet, but it’s a system component. I need to know if upgrading IE also upgrades the WinINet.

**Comment by PhilippSelenium** [comment]
It works for me on Win7 with IE11. I did not upgrade though since that would destroy our test environment.

**Comment by tbates527** [comment]
I also tried these exact same steps with IE10/Windows 7.  I can get 3.10 to work but not 3.11.

**Comment by jimevans** [comment]
IE 10/Windows below 8.1 is broken in 3.11. I know this already, and I know why (thanks for the confirming data @PhilippSelenium). There’s no need for further confirmation on broken configurations.

**Comment by jimevans** [comment]
This should be fixed by 99fc46a, released in IE driver 3.11.1. Please give that a try.

**Comment by PhilippSelenium** [comment]
Yes that works. Thanks for the fast fix.
