### ISSUE TITLE
‘WebDriver’ & chromedriver(DOTNET) - Is runs on WINDOW 2008,2016 servers and Windows 10 machines ?

### ISSUE THREAD

**Issue by mvsreddymca** [SeleniumHQ/selenium#5605]
We are going to write a .Net application (DLL) and going to use ‘WebDriver’ & "chromedriver"
However our component is required to registry as a COM interface dll.

This application is planning host in CITRIX Server (WINDOW 2008,2016) and Windows 10 machines. 
 
Could you please confirm that new webdriver component is runs  on - WINDOW 2008,2016 CITRIX Servers and Windows 10 machines. ?
 
Thank you for your help on this. Have a good day!!!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by mvsreddymca** [comment]
Thanks you,
We are going to write a .Net application (DLL) and going to use ‘WebDriver’ & "chromedriver"

This application is planning host in CITRIX Server (WINDOW 2008).
driver.Navigate().GoToUrl();  - This is not respond and page time out

                ChromeDriverService ChromeService = ChromeDriverService.CreateDefaultService(@"Path");
                ChromeService.SuppressInitialDiagnosticInformation = true;
                ChromeService.HideCommandPromptWindow = true;
                ChromeOptions options = new ChromeOptions();
                //options.AddArgument("--window-position=-32000,-32000");
                //options.AddArgument("--headless");
                options.AddAdditionalCapability("useAutomationExtension", false);
                var driver = new ChromeDriver(ChromeService, options);
                driver.Navigate().GoToUrl(serviceUrl);

driver.Navigate().GoToUrl();  - It's opened a new chrome window and selected url is not responded in CITRIX Server 2008("This site can’t be reached").  

No issue in my local WIN 7 Machine.  Please let us know if any setting is required to setup in Chrome level in server.
