### ISSUE TITLE
Support -capabilities flag with role standalone

### ISSUE THREAD

**Issue by ygmarchi** [SeleniumHQ/selenium#5608]
## Meta -
OS:  
Selenium Version:  
3.11.0
Browser:  

Browser Version:  

## Expected Behavior -
Support -capabilities flag with role standalone
## Actual Behavior -
The flag is not supported. It's supported only in the node role

**Comment by barancev** [comment]
What's purpose of this flag? In Grid environment we use it to match node configuration against a new session request to choose a proper node that can handle this request. What behaviour do you expect from standalone?

**Comment by barancev** [comment]
Closing the issue as the purpose of this change is not clear.
