### ISSUE TITLE
WebDriverException: unknown error: cannot determine loading status from unknown error: unknown sessionId

### ISSUE THREAD

**Issue by jselect** [SeleniumHQ/selenium#5609]
## Meta -
OS:  Linux 4.4.0-116-generic x86_64
Selenium Version:  3.11.0
Browser:  chrome 
Browser Version:  65.0.3325.146 (64-bit)

## Expected Behavior -
Element is found

## Actual Behavior -
org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status from unknown error: unknown sessionId (Session info: chrome=65.0.3325.146) (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-116-generic x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 0 milliseconds Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z' System info: host: 'ITM-41', ip: '10.3.199.68', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121' Driver info: ru.wb.site.uitest.common.selenium.CustomRemoteWebDriver Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.36.540471 (9c759b81a907e7..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.146, webStorageEnabled: true, webdriver.remote.sessionid: 0b7ec67533c747fd1e0a8e65333...} Session ID: 0b7ec67533c747fd1e0a8e65333dddd9 *** Element info: {Using=xpath, value=//ul[@class='user_menu']/li[@data-jsv]/a}

## Steps to reproduce -
1. find element by xpath=//h1[text()='К сожалению, запрошенная вами страница не существует'] | //h1[text()='404 Not Found'] | //h1[starts-with(text(),'Ошибка сервера')] | //p[starts-with(normalize-space(text()), 'В данный момент запрашиваемая вами страница недоступна.')]  - NotFoundException is thrown - it is ok as expected
2. find element by xpath=//ul[@class='user_menu']/li[@data-jsv]/a 

But I can get the page screenshot and htmlsource

**Comment by jselect** [comment]
I downgraded to chromedriver= 2.35.528161 - bug is not reproduced.

**Comment by barancev** [comment]
Please report this issue to chromedriver project: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by jselect** [comment]
reported https://bugs.chromium.org/p/chromedriver/issues/detail?id=2333
