### ISSUE TITLE
WebElement takeScreenshot function doesn't work if the window is scrolled

### ISSUE THREAD

**Issue by ryancat** [SeleniumHQ/selenium#5616]
## Meta -
OS:  OSX

Selenium Version:  4.0.0-alpha.1

Browser:  Firefox

Browser Version:  59

## Expected Behavior -
```element.takeScreenshot()``` should take a screenshot for the element, regardless if the window is scrolled.

## Actual Behavior -
When taking screenshot for element, if the window is scrolled, the screenshot position is wrong.

## Steps to reproduce -

```
describe('google.com', () => {
  let driver;

  before(async () => {
    driver = await (new Builder()).forBrowser('firefox').build();
  });

  after(async () => {
    return await driver.quit();
  });

  it('should have correct title', async () => {
    try {
      await driver.get('https://www.google.com/search?q=espn#searchform');
      let data = await driver.findElement(By.id('searchform')).takeScreenshot();
      fs.writeFileSync('/path/to/screenshot', 'screenshot.png', data, 'base64');
    } 
    catch (err) {
      console.log(err);
    }
  });
});
```

**Comment by selurvedu** [comment]
Same here.

**Comment by diemol** [comment]
Is this still happening with the most recent version of Firefox, GeckoDriver and the NodeJS bindings (`beta-2`)?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
