### ISSUE TITLE
how to create Test data in libreoffice    ...    selenium in linux OS

### ISSUE THREAD

**Issue by BVallamla** [SeleniumHQ/selenium#5618]
we are moving into selenium from eggplant tool... automating web applications in linux machines.

How can we create test data with libreoffice... does java supports manipulation of libre office

thanks and regards,
Bhanu

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
