### ISSUE TITLE
Firefox Webdriver 2.45.0 stops working with prev Firefox releases after crashing with 38.0.1

### ISSUE THREAD

**Issue by elbaloo** [SeleniumHQ/selenium#562]
Possibly related with #437?

1. Added selenium and selenium support to project via Nuget manager
2. Attempted to run test from NUnit without Firefox installed -> got no Firefox binary exception
3. Installed Firefox 38.0.1 and tried again -> Firefox opened but didn't navigate to url given
4. Installed previous ESR (36.0.4) and tried again -> Same behavior as with 38.0.1
5. Did the same down til 34.0 with same behavior.

Windows 8.1 64-bit
Using 4.0 dotnet bindings

**Comment by barancev** [comment]
Duplicate of #437
