### ISSUE TITLE
browser.switchToframe() fails to switch focus to different iframes in Firefox 45

### ISSUE THREAD

**Issue by nkulkarni8** [SeleniumHQ/selenium#5620]
OS:  Windows 7
Selenium Version:  3.4.0 and IDE : Visual Studio Code
Browser:  Firefox
Technology: Javascript
Browser Version:  45.0

Selenium Javascript test fails to execute on Firefox when you switch to Frame.

Error:
WebDriverError: Permission Denied to access property "__eventWrappers1521111203607"

This works absolutely fine on chrome version, only fails on Firefox.

**Comment by barancev** [comment]
No change this issue in the legacy firefox driver will be fixed, unless someone provids a pull request.

Please consider migration to geckodriver-based firefox driver and modern firefox versions.

**Comment by NagarajuAkkepelli** [comment]
HI Kulkarni,
try this command in your test..

this.browser.element("css selector", locators.flatTheam.flatTheamFrame, function(response) {
            this.frame({ELEMENT: response.value.ELEMENT}, 'frame changed');
        });

**Comment by barancev** [comment]
Development of XPI-based Firefox driver has been discontinued and this issue will never be fixed in it.
