### ISSUE TITLE
WebDriverWait().until function not found

### ISSUE THREAD

**Issue by pauloaspimenta** [SeleniumHQ/selenium#5624]
## Problem -
I decided to upgrade the whole selenium grid environment to use 3.11.0 webdriver. I went through the changes and updated the pom.xml file to use 3.11.0 selenium-java and guava 21.0.
So I compiled my project and the following error occurs in WebDriverWait until.

**Before:**
   I had the following setup:
   Selenium Version: 2.47.0
   Guava: 14.0.1
   Java: jdk 1.8 (latest)
**After:**
   Now, this is my setup:
   Selenium Version: 3.11.0
   Guava: 21.0
   Java: jdk 1.8 (latest)

##Code: -
```
WebDriverWait wait = new WebDriverWait(driver, 10000);
wait.until(ExpectedConditions.alertIsPresent());
```
**The error when i compile is the follow:**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project MyProject: Compilation failure
[ERROR] /c:/MyProject/src/main/java/com/atlassian/plugins/MyProject/selenium/keywords.java:[1632,45] cannot access java.util.function.Function               
[ERROR] class file for java.util.function.Function not found

**The line of the error is wait.until(ExpectedConditions.alertIsPresent());...**

**Comment by lmtierney** [comment]
Try Guava version `23`

https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L207

**Comment by Jaysheel** [comment]
I was running into same error.
Upgrading to guava 23.6-jre, did work for me.

**Comment by barancev** [comment]
Yes, please upgrade Guava, Selenium requires Guava version 23
