### ISSUE TITLE
Python API design inconsistency for defining locators

### ISSUE THREAD

**Issue by SmashManiac** [SeleniumHQ/selenium#5625]
The Selenium language bindings for Python makes it hard to manage a consistent way to find locators.

One particular issue I've been running into is when attempting to mix webdriver.find_element_by_* methods and expected_conditions methods requiring a locator in parameter. The former requires declaring the locator strategy in the method name, while the latter requires declaring it through a By object.

While this works fine for simple scripts, things become complicated when attempting to implement a page object model that separates the business logic from Selenium, and the locator strategy is not consistent between elements. It does not appear possible to have a single locator definition without having to implement some kind of mapping between By objects and their corresponding webdriver methods.

While there is a webdriver.find_element method that would solve this problem as it uses a By object as parameter, the documentation specifies that the method is private and should not be used.

**Comment by lmtierney** [comment]
It is perfectly acceptable to just use the `find_element` and `find_elements` methods. Most people I've seen with page object implementations declare their locators a as a tuple with `(by, locator)` and pass them to `find_element`. We will remove the line from documentation about them being private methods
