### ISSUE TITLE
Firefox proxy port not set correctly in selenium-webdriver

### ISSUE THREAD

**Issue by thislooksfun** [SeleniumHQ/selenium#5627]
## Meta -
OS:  macOS 10.12.6 (16G1212)
Selenium Version:  Selenium Webdriver v3.6.0
Browser:  Firefox (via GeckoDriver)

Browser Version:  58.0.2 (64-bit)

## Expected Behavior -
Running
```javascript
const mitmProxy = proxy.manual({http: 'localhost:8080', https: 'localhost:8081'});
const firefoxOptions = new firefox.Options();
firefoxOptions.setBinary(ffBinary);
firefoxOptions.setProxy(mitmProxy);
var driver = new webdriver.Builder().forBrowser('firefox').setFirefoxOptions(firefoxOptions).build();
```
should set the 'http' proxy to 'localhost' with port '8080', and set the 'ssl' proxy to 'localhost' with port '8081'

## Actual Behavior -
Running the above code correctly sets the proxy addresses to 'localhost', but the HTTP port is set to '80' and the SSL port is set to '443'.

## Steps to reproduce -
Run the above code snippet, then go to `about:preferences` -> 'Network Proxy'

**Comment by oscar811** [comment]
Facing the same issue and there is a workaround for fixing network proxy issue. It works good to me.

```javascript
const mitmProxy = {proxyType:'manual', httpProxy: 'localhost:8080', httpProxyPort:8080, sslProxy: 'localhost:8081', sslProxyPort:8081});
const firefoxOptions = new firefox.Options();
firefoxOptions.setBinary(ffBinary);
firefoxOptions.setProxy(mitmProxy);
var driver = new webdriver.Builder().forBrowser('firefox').setFirefoxOptions(firefoxOptions).build();
```

**Comment by diemol** [comment]
Closing as a workaround was provided by the community and the issue also went stale.
