### ISSUE TITLE
Grid node leaves TCP connections to ChromeDriver open causing future tests to fail with the "Connection timed out" exception

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#5631]
## Meta -
OS:  Windows 7, 10, Server 2012 R2
Selenium Version: 3.8.1 and earlier; 3.9.0-3.11.0 with Apache HttpClient only
Browser: Chrome
Browser Version: any

When a Selenium Grid node sends the "POST /session" HTTP request to a ChromeDriver instance, ChromeDriver closes the TCP connection used for the request after responding, but the Grid node leaves it open even after that ChromeDriver instance terminates. Below is a screenshot that demonstrates the issue (ChromeDriver was listening on port 34755).

![image](https://user-images.githubusercontent.com/7848534/37533670-dd2dcfae-2918-11e8-99a5-11594a1a78e3.png)

I noticed that the Grid node only closes the connection when it starts another ChromeDriver that listens on the same port. The issue only occurs on Windows if the connection stays in that half-closed state for more than 2 hours and 20 minutes. Another condition is the Grid node should start a new ChromeDriver instance listening on the same port as the old one and also attempt to establish a connection to it using the same source port. In the example above, it would be ports 34755 and 55990. If all these conditions are met, the connect attempt fails with the "Connection timed out: connect" exception and the Selenium test fails producing a stack trace like in https://github.com/SeleniumHQ/selenium/issues/5459.

## Expected Behavior -
Tests on Grid run without the "Connection timed out" exception when the node tries to connect to ChromeDriver running on localhost.

## Actual Behavior -
Tests on Grid sometimes fail with the "Connection timed out" exception.

## Steps to reproduce -
This issue is hard to reproduce because the probability of the node to reuse the same set of ports is small. You just need to run a lot of tests and wait many hours or even days. I wrote a small program that simulates this behavior of the node and can reproduce the same error in two and a half hours. It makes only a single "/shutdown" request to ChromeDriver for simplicity.

```
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.net.Socket;

public class ChromeDriverConnectionTimedOut {
	static void useChromeDriver() throws IOException, InterruptedException {
		// Start a new ChromeDriver instance
		Runtime.getRuntime().exec("chromedriver.exe --port=10000");
		// Wait for ChromeDriver to start
		Thread.sleep(1000);
		// Send any command, like shutdown is this case, and leave the socket open
		// for at least 2 hours 20 minutes
		Socket socket = new Socket("localhost", 10000, InetAddress.getByName("localhost"), 20000);
		BufferedWriter out = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream(), "UTF8"));
		BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream(), "UTF8"));
		System.out.println("Sending a request");
		out.write("GET /shutdown HTTP/1.1\r\n");
		out.write("User-Agent: Java/1.8.0_162\r\n");
		out.write("Host: localhost:10000\r\n");
		out.write("Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n");
		out.write("Connection: close\r\n\r\n");
		out.flush();
		String responseLine;
		StringBuilder response = new StringBuilder();
		while ((responseLine = in.readLine()) != null) {
			if (!responseLine.isEmpty()) response.append("\n\t" + responseLine);
		}
		System.out.println("Reseived the response " + response);
		// Wait 2.5 hours before closing the socket
		Thread.sleep(150 * 60000);
		socket.close();
		System.out.println("Closed the socket");
	}
	public static void main(String[] args) throws IOException, InterruptedException {
		System.out.println("Using ChromeDriver the first time");
		useChromeDriver();
		System.out.println("Using ChromeDriver the second time");
		useChromeDriver();
	}
}
```

Here's the output you'll see if you run it

```
Using ChromeDriver the first time
Sending a request
Reseived the response 
	HTTP/1.1 200 OK
	Content-Length:40
	Content-Type:application/json; charset=utf-8
	Connection:close
	{"sessionId":"","status":0,"value":null}
Closed the socket
Using ChromeDriver the second time
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at ChromeDriverConnectionTimedOut.useChromeDriver(ChromeDriverConnectionTimedOut.java:17)
	at ChromeDriverConnectionTimedOut.main(ChromeDriverConnectionTimedOut.java:42)
```

**Comment by Jaysheel** [comment]
@JohnA2 I am not sure about the details, but I was also running into java.net.ConnectException: Connection timed out: connect
i.e. https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239.

Can you try with upgrading to chrome driver 2.36? I think you would be using 2.34 or 2.35.

**Comment by JohnA2** [comment]
@Jaysheel I'm already using chrome driver 2.36. https://bugs.chromium.org/p/chromedriver/issues/detail?id=2239 looks very different from my issue.

**Comment by JohnA2** [comment]
I did more testing and found that OkHttp closes the connection used for the "POST /session" request after 5 minutes. So this bug only applies to Apache HttpClient, which is used by Selenium 3.8.1 and earlier or Selenium 3.9.0-3.11.0 if the `webdriver.http.factory` system property is set to `apache`.

I think this bug can be closed as "won't fix" since Apache HttpClient is no longer the default in the latest Selenium versions.

**Comment by barancev** [comment]
@JohnA2 Thank you! Yes, we're migrating to OkHttp, all uses of Apache HC will be removed soon. So let's close this issue as "won't fix".
