### ISSUE TITLE
webdriver.executeScript function return different results for string script vs function

### ISSUE THREAD

**Issue by ryancat** [SeleniumHQ/selenium#5632]
## Meta -
OS:  OSX

Selenium Version:  4.0.0-alpha.1

Browser:  Firefox

Browser Version:  59

## Expected Behavior -
webdriver.executeScript should take either string or function as the script to execute. I would expect it's return value should not be different if I pass string vs function. 

## Actual Behavior -
When passing string, it may gave different result compare to function. 

## Steps to reproduce -
Correct:
```
driver.executeScript(() => window.devicePixelRatio); // give 2 on retina screen
```

Wrong:
```
driver.executeScript('window.devicePixelRatio'); // give 1 on retina screen
```

**Comment by jleyba** [comment]
Can you please provide a complete reproducible test case?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
