### ISSUE TITLE
WebDriver action classes do not execute while inside an iframe within the Microsoft Edge Driver

### ISSUE THREAD

**Issue by fdeamicis** [SeleniumHQ/selenium#5633]
I am using Windows 10 Build 10586.  I have installed Microsoft Edge browser Release 10586

The following action classes do not get executed  while inside an iframe within the Microsoft Edge Driver:
action.dragAndDrop
action.doubleClick
action.contextClick
action.clickAndHold
action.moveToElement
action.release

Here are the sample programs where I've tried to execute these actions:

Program 1:

package trainingSeleniumAutomation;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.interactions.Actions;

public class ActionsClassEdge {

	public static void main(String[] args) throws InterruptedException, AWTException {
		// TODO Auto-generated method stub

		//Initiate Browser
		System.setProperty("webdriver.edge.driver", "C:\\MicrosoftEdge\\MicrosoftWebDriver.exe");
		
		WebDriver driver = new EdgeDriver();
		driver.manage().window().maximize();
		
		Actions action = new Actions(driver);
	    
		driver.get("https://jqueryui.com/droppable/");
		
		Thread.sleep(1000);
		
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
				
		driver.switchTo().frame(0);
		
		
		Thread.sleep(1000);
		
		
		WebElement drag=driver.findElement(By.xpath("//*[@id='draggable']"));
	      
		
                WebElement drop=driver.findElement(By.xpath("//*[@id='droppable']"));
		
		
		Thread.sleep(1000);
		
			
		action.dragAndDrop(drag, drop).build().perform();
				
	}

}

Program 2:

package trainingSeleniumAutomation;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.Collections;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;

public class ActionsClassEdge1a {

	public static void main(String[] args) throws InterruptedException, AWTException {
		// TODO Auto-generated method stub

		//Initiate Browser
               System.setProperty("webdriver.edge.driver", "C:\\MicrosoftEdge\\MicrosoftWebDriver.exe");
		
		WebDriver driver = new EdgeDriver();
		driver.manage().window().maximize();
		
		Actions action = new Actions(driver);
	    
		driver.get("https://jqueryui.com/droppable/");
		
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		driver.switchTo().frame(0);
		
		WebElement drag = driver.findElement(By.id("draggable"));
	
		WebElement drop = driver.findElement(By.id("droppable"));
		
				
		action.doubleClick(drag);
		
		Thread.sleep(1000);
		
				
		action.contextClick(drop);
		
		
		Thread.sleep(1000);
		
		
				
		action.dragAndDrop(drag, drop).perform();
		
		
		
	}

}

Program 3:

package trainingSeleniumAutomation;

import java.util.Collections;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.interactions.Actions;

public class ActionsClassEdge2a {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		//Initiate Browser
                System.setProperty("webdriver.edge.driver", "C:\\MicrosoftEdge\\MicrosoftWebDriver.exe");
		
		WebDriver driver = new EdgeDriver();
		driver.manage().window().maximize();
		
		Actions action = new Actions(driver);
	    	    
		driver.get("https://jqueryui.com/droppable/");
		
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		
		driver.switchTo().frame(0);
		
		WebElement drag = driver.findElement(By.id("draggable"));
	
		WebElement drop = driver.findElement(By.id("droppable"));
		
		action.clickAndHold(drag).moveToElement(drop).release(drop).build().perform();
		
		//driver.quit();
		
		
	}

}
![edge1](https://user-images.githubusercontent.com/4235950/37548336-7afb7914-294d-11e8-9164-38c432e57555.jpg)
![edge2](https://user-images.githubusercontent.com/4235950/37548337-80fdf148-294d-11e8-901e-bb67e9e310af.jpg)

**Comment by Jaysheel** [comment]
@fdeamicis , just curious. Why you are not upgrading to latest release version? (with upgrading windows as well?)
I am sure there would be more fixes in newer versions.

**Comment by barancev** [comment]
This issue should be reported to Microsoft (the EdgeDriver developer): https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/
