### ISSUE TITLE
selenium-webdriver NodeJS 4.0.0-1 alpha does not work in IE driver

### ISSUE THREAD

**Issue by Havunen** [SeleniumHQ/selenium#5634]
```driver.wait(until.elementLocated(By.id('something')), 5000)```
causes IE driver to fail: 
`UnsupportedOperationError: Error 404: Not Found`

Version 3.6 works

**Comment by Havunen** [comment]
NodeJS:
v9.8.0

![image](https://user-images.githubusercontent.com/2021355/37565958-65eebd32-2abb-11e8-9cb6-1da901300d07.png)
![image](https://user-images.githubusercontent.com/2021355/37565972-8c370f08-2abb-11e8-8e9f-9efc69ce30cb.png)

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
