### ISSUE TITLE
Facing org.openqa.selenium.WebDriverException while running safariDriver in Mac

### ISSUE THREAD

**Issue by shariqMohammed92** [SeleniumHQ/selenium#5637]
Facing server side error while running the automation suite with safari webDriver.

Error:org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'Admins-Mac-mini.local', ip: '192.168.11.72', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.1', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver

**The timeout duration is shown to be ## 0 milliseconds.**

## Meta -
OS: macOS HighSierra v10.13.1
Browser:  
Safari v11.0.1

![screen shot 2018-03-19 at 12 29 59 pm](https://user-images.githubusercontent.com/37373409/37582121-5401c27a-2b71-11e8-9b20-0ae2717a4dce.png)

**Comment by barancev** [comment]
Please report this issue to Apple: https://webkit.org/reporting-bugs/

**Comment by dacloutier-logmein** [comment]
I know it has been closed, but anyone found a way around that?

I've been facing that issue too in a pretty random fashion. 

Safari 11
many mac OS versions
