### ISSUE TITLE
Chromedriver couldn't find the Android file using valid file path

### ISSUE THREAD

**Issue by xbotest** [SeleniumHQ/selenium#5638]
Working with Samsung S6, during uploading a file using SendKeys(), it always reports 'file not found' issues. But i can confirm the file exits.

Have tried
driver.FindElement(By.Id("0-new")).SendKeys("//storage/emulated/0/Download/automation_test.pdf");
driver.FindElement(By.Id("0-new")).SendKeys("//data/local/tmp/automation_test.pdf");
driver.FindElement(By.Id("0-new")).SendKeys("//sdcard/Download/automation_test.pdf");

All of above doesn't work, although file exists in these folders.

This issue occurs ChromeDriver 2.33-2.36, but 2.20 doesn't have this problem (didn't try with other versiosn). So I guess it should be chromedriver issue.

Anyone can help check, and provide a solution?

**Comment by barancev** [comment]
Please report this issue to chromedriver: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by xbotest** [comment]
Got it
