### ISSUE TITLE
Selenium gives error Unable to locate element on closed window: IE 11

### ISSUE THREAD

**Issue by nkulkarni8** [SeleniumHQ/selenium#5639]
OS: Windows 7
Selenium Version: 3.4.0 and IDE : Visual Studio Code
Browser: IE 11
Technology: Javascript
Browser Version: 11

Selenium Javascript test fails to execute on Internet Explorer giving error: Unable to locate element on closed window

Error:
Unable to locate element on closed window.

This works absolutely fine on chrome version, but fails on IE.

**Comment by nkulkarni8** [comment]
We are trying to run javascript test on IE 11 and using selenium version 3.4.0.

The test launches the IE explorer and then tries to do a switch window on the iFrame.
In my case, the internet explorer launches and navigates to the desired URL, but still I get the error on console "Unable to locate element on a closed window".

Expected result should be navigating to the frame and click on the  button, but it fails to do so.

This same test works absolutely fine on Chrome.

Please suggest suitable solutions. Thanks

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
