### ISSUE TITLE
Selenium Driver instance will go into sleep state

### ISSUE THREAD

**Issue by shaileshrbiradar** [SeleniumHQ/selenium#5641]
## Meta -
OS: Windows 10 Server
Selenium Version: selenium-server-standalone-3.11.0.jar
Browser:  Chrome
Version : 65.0.3325.162 (Official Build) (64-bit)
Chromedriver : 2.37.543627
Language Used : Java

**Application Expected Behavior** :-
I have an application which is using Gmail accounts for authentication. When I try to open an URL in chrome browser, it will open a pop-up window(Gmail Authentication Window) with main window(Application view with some third party loader). In the pop-up window, I will enter my gmail username and password and hit on login button. After that the pop-up window will refresh and disappears after particular time. As well as my main-window will refresh and I will logged in into the application successfully.

**Issue** :- 
After entering  username and password the child window is refreshing. But it isn't disappear.

**Solution tried** :-
When I try to open an URL in chrome browser, it will open a pop-up window(Gmail Authentication Window) with main window(Application view with some third party loader). In the pop-up window, I will enter my gmail username and password and hit on login button. I waited for 1 Minutes and I found that the window won't disappear. So,I have closed the child window and navigated the driver control to main window checked the below solutions,
a) Refresh the application
b) Tried to open the application URL again
c) Used Selenium Press-keys method
In first two solutions, selenium isn't perform the activities and it goes to sleep state(Doesn't see any activities in 5 Minutes). In the third solution, the driver will be refreshing the page and it will go to sleep state(Not performing the later activities).

**My application was working fine for below configurations** :-
OS: Windows 10 Server
Selenium Version: selenium-server-standalone-3.8.1.jar
Browser:  Chrome
Version : 63.* (Official Build) (64-bit)
Chromedriver : 2.35.*

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
