### ISSUE TITLE
Open Chrome with Toggle Device Toolbar Activated

### ISSUE THREAD

**Issue by ddreyse** [SeleniumHQ/selenium#5642]
I know how to open chrome with "--auto-open-devtools-for-tabs", but i need to open it with Toggle Device Toolbar activated. This mode, emulate the touch interactions events, replacing the click with a touch. How can i do that?

Here's my code:
(...)
			Map<Object, String> mobileEmulation = new HashMap<Object, String>();
			mobileEmulation.put("deviceName", "Nexus 5X");
			DesiredCapabilities capabilities = DesiredCapabilities.chrome();
			ChromeOptions chromeOptions = new ChromeOptions();
			chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
			chromeOptions.addArguments("--auto-open-devtools-for-tabs");
			chromeOptions.addArguments("--allow-running-insecure-content");
			capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
			driver = new ChromeDriver(capabilities);
(...)

What new argument i must to add?

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
