### ISSUE TITLE
Phantomjs jquery dialog pop-up

### ISSUE THREAD

**Issue by csselo** [SeleniumHQ/selenium#5647]
## Meta -
OS:  ubuntu 17 x64

Selenium Version:  3.4.3

Browser:  phantomjs

Browser Version:  2.1.1 last

## Expected Behavior -
Can I handle a jquery dialog popup with phantomjs _ I can do it with FF but it doesn t handle it?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
