### ISSUE TITLE
Improve org.​openqa.​selenium.By documentation

### ISSUE THREAD

**Issue by krichter722** [SeleniumHQ/selenium#5649]
## Meta -
OS:  ---
Selenium Version:  3.7.0
Browser:  ---
Browser Version:  ---

## Expected Behavior -
The documentation of `org.​openqa.​selenium.By` isn't overly long yet and could use some info about recursive behaviour, e.g. intuitively I'd expect `tagName` not to recurse, but apparently it does, does it (don't answer here, but in the code, please).

A boolean option to recursive would be nice, but that's another enhancement proposal.

**Comment by barancev** [comment]
Selenium implements W3C WebDriver standard [1], its behavior is well-documented. It would be unwise to rewrite all the spec in the form of javadoc. If you want to provide a new feature please raise an issue on the specification.

[1] https://w3c.github.io/webdriver/webdriver-spec.html

**Comment by krichter722** [comment]
> Selenium implements W3C WebDriver standard [1], its behavior is well-documented. It would be unwise to rewrite all the spec in the form of javadoc. If you want to provide a new feature please raise an issue on the specification.

Rewriting is a bad idea, I agree. You can and should link it then. There're much more issues with the Javadoc that seems in bad shape (often `""` and `null` are treated the same which is extremely counter-intuitive without it being mentioned) because of this logic (it's well defined in the W3C spec, so we don't need to mention crucial behaviour in the Javadoc). You don't, but then boil the Javadoc down to a link to the W3C spec if that's the only location of well maintained documentation.

**Comment by barancev** [comment]
Yes, pull requests are welcome :)
