### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION with selenium java 

### ISSUE THREAD

**Issue by SuhaThevar90** [SeleniumHQ/selenium#565]
Hi 
Trying to execute a test case with selenium 2.44 version with java , Windows 7 OS 
Gettting the below error frequently

#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x656970ba, pid=5260, tid=1828
#
# JRE version: Java(TM) SE Runtime Environment (7.0_51-b13) (build 1.7.0_51-b13)
# Java VM: Java HotSpot(TM) Client VM (24.51-b03 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [ODBC32.dll+0x270ba]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\Live\iAF-Selenium-v3\bin\hs_err_pid5260.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

E:\Live\iAF-Selenium-v3\bin>pause 0
Press any key to continue . . .

Could you please help me out with a solution as i am not able to proceed with the execution.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
