### ISSUE TITLE
IeDriver do not scroll into element

### ISSUE THREAD

**Issue by Nawakator** [SeleniumHQ/selenium#5650]
## Meta -
OS:  Windows 7/10
Selenium Version:  Selenium 3.11.1.1
Browser:  Internet Explorer 11

The Ie driver does not scroll into view element anymore (Removed GetLocationOnceScrolledIntoView from InputManager.cpp).

It seems linked to W3C compliant, but I really do not understand this.
Internet Explorer will never evolve and the new feature has not applied into the other drivers.
Since 3.5.x they are many regressions that make the test between Ie and the other browsers not compatible.
We have to update all our test by adding some if browser.equals(...) to be able to run the tests.

Also the scripts may don't work if we change the resolution!

Browser Version:  Ie 11 (Win 64b)

## Expected Behavior -
If a web element is outside the view, the precedents versions scroll into it.

## Actual Behavior -
Now we have an exception MoveTargetOutOfBoundsException

## Steps to reproduce -
You can use the tests create by g04k4 (selenium-tests.zip)
From [https://github.com/SeleniumHQ/selenium/issues/5024](url)

**Comment by jimevans** [comment]
Does the behavior of current versions of the IE driver match that when running against recent versions of Firefox using geckodriver?

**Comment by Nawakator** [comment]
Indeed, the beahvior seem to be the same in Firefox not in Chrome

**Comment by Nawakator** [comment]
So whe have to implement a scroll into view before call validate, moveto, click on WebElement

**Comment by jimevans** [comment]
@Nawakator I expect that chromedriver will pick up the same behavior once its W3C compliant implementation is released (soon, certainly before the end of the year).

So yes, if you’re using the Actions APi to manipulate elements, you’ll need to scroll the target into view first. The JavaScript `scrollIntoView` function can be useful here. Note that this change has no bearing on the `click()` and `sendKeys()` methods of the `WebDriver` interface. They will still attempt to scroll the target element into view automatically.

**Comment by barancev** [comment]
@Nawakator If you mean Actions, follow this issue: https://github.com/w3c/webdriver/issues/1005, this new feature will be implemented in drivers only after fixing this spec issue.

If you faced scrolling issues with "regular" (not Action based) sendKeys or click operations please provide a reproduction scenario.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
