### ISSUE TITLE
"Maximum call stack size exceeded" when trying to return objects with reference loop using ExecuteJavaScript

### ISSUE THREAD

**Issue by arnonax** [SeleniumHQ/selenium#5651]
## Meta -
OS:  
Windows 8.1
Selenium Version:  
3.11.0.0
Browser:  
Chrome, Firefox

## Steps to reproduce -
(In C#)
`driver.ExecuteJavaScript<string, object>("var x={};var y={a:x};x.b=y;return x;");`

## Expected Behavior -
Results is a Dictionary (x) with an element 'b' pointing to another dictionary (y) which contains an element 'a' which points back to x.

## Actual Behavior -
An InvalidOperationException: "Maximum call stack size exceeded" is thrown.

In Firefox the method freezes until a Timeout occurs.

I believe that the problem is not directly in the Selenium binding implementation, and I guess the JSON Wire protocol isn't design to support it either. But I think that the standard should at least specify a common exception to this situation, and I suggest to consider enhancing the protocol to be able to support it.

**Comment by jimevans** [comment]
@arnonax What version of Firefox did you test against? There is a web platform test for W3C spec-compliant implementations that tests exactly for this. I would be shocked if your code didn’t throw an exception at least on Firefox beta (60 at the time of this writing), but @AutomatedTester would know better.

**Comment by arnonax** [comment]
Indeed I used a very old version of FireFox (39). I now updated it to 59.0.1 (64-bit) and I get a proper exception:
System.InvalidOperationException: TypeError: cyclic object value (UnexpectedJavaScriptError)
Thanks!

**Comment by jimevans** [comment]
Given that the behavior is correct in current Firefox I’m going to close this issue.

**Comment by barancev** [comment]
This case (cyclic reference) is defined in the specification, see [1], description of serialization algorithm. If chromedriver does not conform to the specification you can raise an issue on it, see [2].

[1] https://w3c.github.io/webdriver/webdriver-spec.html#executing-script
[2] https://sites.google.com/a/chromium.org/chromedriver/help
