### ISSUE TITLE
OpenQA.Selenium.Support.UI Namespace does not contain WebDriverWait class

### ISSUE THREAD

**Issue by MDCCXIII** [SeleniumHQ/selenium#5654]
## Meta -
OS:  Windows 7 

Selenium Version:  3.11.0

Browser:  N/A

Browser Version:  N/A

## Expected Behavior -
Per the documentation OpenQA.Selenium.Support.UI Namespace should contain WebDriverWait class.
## Actual Behavior -
WebDriverWait class is not present in the visual studio class inspector and the [github source code](https://github.com/SeleniumHQ/selenium/tree/master/dotnet/src/support/UI)
(Result images at bottom of issue)

## Steps to reproduce -
Install Selenium.Support by Selenium Committers NuGet v3.11.0 and inspect the referenced assembly using Visual Studios class view.

Official support ui namespace documentation:
![official support ui namespace documentation](https://user-images.githubusercontent.com/22691751/37716549-c81377ae-2cec-11e8-9f54-e2ec2d567f7c.PNG)
Official webdriverwait class documentation:
![official webdriverwait class documentation](https://user-images.githubusercontent.com/22691751/37716554-cb1737c4-2cec-11e8-9cfb-5ee0f806114e.PNG)
Selenium github source code - support ui namespace classes:
![selenium github source code - support ui namespace classes](https://user-images.githubusercontent.com/22691751/37716557-ccc8698a-2cec-11e8-8fb3-0b88ff70b3d2.PNG)
Missing webdriverwait class in openqa selenium support ui - visual studio class view:
![missing webdriverwait class in openqa selenium support ui](https://user-images.githubusercontent.com/22691751/37716563-ce1636e6-2cec-11e8-9b47-d42c8af610c9.PNG)

**Comment by jimevans** [comment]
The bug is in the documentation. The class has been moved to the main WebDriver.dll assembly (Selenium.WebDriver NuGet package).

**Comment by MDCCXIII** [comment]
Link to the documentation? I'm not seeing the WebDriverWait class in the WebDriver assembly either.
Biggest issue is that Visual studio seems to have trouble referencing the class.

**Comment by jimevans** [comment]
Screenshot of ILDASM, taken with the WebDriver.dll downloaded directly from NuGet and extracted from the selenium.webdriver.3.11.0.nupkg file.

![ildasm webdriverwait](https://user-images.githubusercontent.com/352840/37720337-78547086-2cfd-11e8-8caa-d8a95cf3bb36.png)

The class is there, in the correct namespace, in the WebDriver.dll assembly. If you're upgrading from a previous version that required the support reference, try removing the packages or references and re-adding them.

**Comment by MDCCXIII** [comment]
I have already attempted the removing of packages and references and re-adding, however i will try again, i can't argue with that screenshot. Thanks for your time!

**Comment by MDCCXIII** [comment]
Thank you Very Much!!! After much head scratching i finally noticed that i had a stale v3.4.x webdriver.dll in my project for whatever reason and when i installed the webdriver from nuget the reference continuously pointed back to the stale dll. After deleting the old dll and updating the reference all is right in the world once again. Sorry for the false alarm!

**Comment by jimevans** [comment]
Glad it got worked out.
