### ISSUE TITLE
ByChained/element.FindElements() is not working as expected 

### ISSUE THREAD

**Issue by abmptit** [SeleniumHQ/selenium#5656]
I created a test into the existent ByChainedBrowserTests where I Used an exitent html page and i reproduce the case:

        [Test]
        public void FindElement_TwoBys_ShouldReturnTwoElements()
        {
            driver.Url = nestedPage;
            driver.Navigate();
            var parentSelector = By.XPath("//div[@name='div1'][1]");
            var a = By.XPath("//div[@name='div1'][1]").FindElements(driver);
            var b = By.XPath("//a").FindElements(driver);
            var c = By.XPath("//div[@name='div1'][1]//a[contains(@href,'.html')]").FindElements(driver);

            var by = new ByChained(By.XPath("//div[@name='div1'][1]"), By.XPath("//a"));
            var elements = by.FindElements(driver);

            Assert.AreEqual(2, elements.Count);
        }

**Comment by abmptit** [comment]
elements.Count returns 12 like By.XPath("//a").FindElements(driver).Count
it should return 2 because under a we have only 2 //a

**Comment by jimevans** [comment]
That's not how XPath works for Selenium. Finding elements by XPath follows the spec for XPath, which says that the `//` selector selects from the root of the document (see [section 2.5](https://www.w3.org/TR/1999/REC-xpath-19991116/#path-abbrev) of the spec). To make this work, you'd need to change your second XPath to `By.XPath(".//a")`.
