### ISSUE TITLE
Cloud providers and Grid could benefit from client bindings sending in version and platform info.

### ISSUE THREAD

**Issue by sah** [SeleniumHQ/selenium#5657]
As a cloud provider, we would absolutely love a key in the new session request that says something like “hi I’m version X.Y of the Java bindings running on macOS 10.13” — along the lines of an HTTP User-Agent. This would help with diagnosing bugs and incompatibilities, especially when dealing with a wide variety of versions of both the client bindings and Selenium server and drivers. For similar reasons, I suspect it might also be useful for Grid to log this info.

I'd be happy to contribute code for this across a bunch of the bindings, if people think it's a good idea and we can agree on where to put it and what the format should be.

**Comment by shs96c** [comment]
Is it okay to put that information in an HTTP header?

**Comment by sah** [comment]
Sure, that would work. Could even tailor the actual `User-Agent`...

**Comment by jleyba** [comment]
We should probably decide on a standard `User-Agent` format for the project so we're consistent across the different bindings.

**Comment by pulkitsharma07** [comment]
Are we planning to overwrite the `User-Agent` header which is generated by the underlying HTTP library the bindings use?

I recommend using a new non-standard header (something like `Selenium-Client-Ver`) for sending the binding version, so that it can be succinct (and unambiguous), plus we don't have to worry about adding content to any existing header(s).

**Comment by jleyba** [comment]
How about: `X-Selenium-Version: ${LANGUAGE}[-${COMPONENT}]@${VERSION}`

Possible values:

- `java-client@3.8.1`
- `java-grid@3.8.1`
- `nodejs@4.0.0-alpha.1`

Use multiple values to capture nodes in a grid. For example:

`X-Selenium-Version: java-grid@3.8.1,java-grid@3.7,java-client@3.8.1`

indicates a request came from a grid server (v3.8.1), which is forwarding a request from another grid at v3.7, which received the initial request from a client using 3.8.1.

**Comment by jimevans** [comment]
@jleyba I like where you're going with that, but it doesn't add in the OS information as was in the original request. Moreover, I'm not entirely sure how we can get a satisfactory OS information string together that would please everyone.

And let's be very clear here, I'm in favor of this if it is _**only**_ to be applied on new session requests, and is _**optional**_, meaning that third parties and intermediate nodes can't depend on it, but could make use of it if and only if it's present.

**Comment by shs96c** [comment]
@jleyba I think putting this in the `User-Agent` header makes the most sense, and from the local end should be: `selenium//${version} (${language} ${platform-family})`. That's a little more in line with how the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) suggest a UA string should be formed. 

I'm not sure about the concatenation thing, but if we did it, then we'd want to look at the routing headers in emails as an example to follow.

@jimevans UA strings are definitely not things that people should rely on. I'm curious about why you think it should **only** be for new session requests. Will discuss that with you on IRC.

**Comment by jleyba** [comment]
Would `${platform-family}` have any more granularity than what is supported in W3C capabilities? I wouldn't want to send anything more detailed without giving users an easy opt-out.

**Comment by sah** [comment]
Sounds like `User-Agent` may be the direction being settled on here, but just in case it's not, FYI `X-` headers are no longer considered best practice: https://tools.ietf.org/html/rfc6648

`${language}` doesn't contemplate third-party bindings; there are multiple binding libraries in widespread use for js and PHP, for example. Maybe `${language} ${library}`, where official libraries use something like `official` or `selenium` as the library name?

**Comment by sah** [comment]
Or maybe third-party libraries would change the `selenium//${version}` part?

**Comment by cgoldberg** [comment]
> UA strings are definitely not things that people should rely on.

Mobile browser detection via UA sniffing is still *very* common practice for dynamic serving.  I think altering the UA string is asking for trouble.

**Comment by jimevans** [comment]
@cgoldberg Sincewe are talking about the HTTP communication between the language bindings and WebDriver remote ends, not modifying the UA string between the browser/mobile app and the web server, I’m not sure how that affects sniffing that web apps, even mobile ones would do.

**Comment by cgoldberg** [comment]
@jimevans my bad :)

**Comment by shs96c** [comment]
@sah I'd suggest other implementations do something based on what we decide here, but it's entirely up to them.

**Comment by sah** [comment]
@shs96c Sure, they'll make their own decisions, but it would be nice if what's decided here leaves an easy & obvious way for them to fit gracefully into the format if they so choose.

**Comment by jleyba** [comment]
So, we'd have things like:

-  `User-Agent: selenium//3.14 (java windows)`
-  `User-Agent: selenium//3.14 (python linux)`

Other projects can follow the convention, but they are not Selenium and should change the product name accordingly

-   `User-Agent: webdriverio//4.9 (js windows)`

**Comment by sah** [comment]
Looks great to me! Waiting for a thumbs up and I'll get a PR going.

**Comment by shs96c** [comment]
Fixed using @jleyba's format for Java in f3ba82ccb6b9c54bfc9f459c18458c78ba3ca42d

**Comment by jimevans** [comment]
.NET UA string added in a433820.

**Comment by p0deje** [comment]
Ruby merged in 429af62c79c4048d54856a9d4b79d451d98e372a.
