### ISSUE TITLE
Browser Console Logs containing structured JSON objects are returned as a String with text 'Object'

### ISSUE THREAD

**Issue by sandeepnagra** [SeleniumHQ/selenium#5658]
OS:  OSX
Selenium Version:  3.8.0
Browser:  Chrome 65.0
Language: Ruby 2.4.1

I referred to this section of logging document - https://github.com/SeleniumHQ/selenium/wiki/Logging#log-message

I have a similar situation where I want to read the logs from console where some logs are in JSON format but using the command `@browser.manage.logs.get(:browser)` with browser logging prefs set to ALL, I do get all the logs but the objects within the log are returned as a string with text 'object'. There should be an option to get the logs in JSON format as well. It seems like they are converted to string based on what I see here - https://github.com/browserstack/selenium-webdriver-ruby/blob/0f1ba0689b6250a2f35f8911003310a54463fa32/lib/selenium/webdriver/common/log_entry.rb

**Comment by pulkitsharma07** [comment]
Let's track this here https://github.com/browserstack/selenium-webdriver-ruby/issues/2 :-)

**Comment by Jamie-** [comment]
I believed this was actually a chromedriver bug so raised an issue over there. Seems there's nothing they can do about it as it's what Chrome gives them, see: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3052
