### ISSUE TITLE
System Invalid Cast Exception C#

### ISSUE THREAD

**Issue by jdelange** [SeleniumHQ/selenium#566]
I think my issue listed here could be a bug: https://groups.google.com/forum/#!topic/selenium-users/iNS0ZqYoNas Initially I posted this at the wrong place https://github.com/RaYell/selenium-webdriver-extensions/issues/89#event-312808440 so that's why I am now posting it here.

**Comment by jimevans** [comment]
The code in the mailing list thread is working exactly as expected. This behavior is categorically not a bug in the .NET bindings.

**Comment by jdelange** [comment]
Jim, thanks for your fast follow-up. Then it's my mistake and you can close this. I noticed your comment in the mailing list, I will see if I can solve it.
