### ISSUE TITLE
close this window!

### ISSUE THREAD

**Issue by liang1024** [SeleniumHQ/selenium#5660]
![qq 20180322132546](https://user-images.githubusercontent.com/18343332/37752769-8f9c1b4a-2dd4-11e8-9fd0-d78c706bdfd9.png)

DevTools listening on ws://127.0.0.1:12090/devtools/browser/6b3f23c1-86af-48e1-b669-330170226401

==================
# I pack it as exe with it to others
But I don't know how to close this window
It's not friendly!!!
What can I do to turn it off!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
