### ISSUE TITLE
Exception thrown when trying to Throttle Chrome using dotnetcore (c#)

### ISSUE THREAD

**Issue by qwertykg** [SeleniumHQ/selenium#5666]
## Meta -
OS:  Windows 10

Selenium Version: 3.11.0 

Browser:  Chrome

Browser Version:  65.0.3325.181

## Expected Behavior -
When setting the NetworkConditions of the ChromeDriver, the browser should run throttled with the specified network settings when using c# dotnet
## Actual Behavior -
The following error is thrown:

OpenQA.Selenium.WebDriverException : Unexpected error. unknown command: session/62fe84edb13b79c914bef4b7d1181f6a/chromium/network_connection
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Chrome.ChromeDriver.get_NetworkConditions()

## Steps to reproduce -

Currently I've tried: 
  
    var options = new ChromeOptions();
    options.AddArguments("disable-infobars");

    private ChromeDriver _webDriver;
    _webDriver = new ChromeDriver(options);

    var networkConditions = new ChromeNetworkConditions();
    networkConditions.Latency = new TimeSpan(150);
    networkConditions.IsOffline = false;
    networkConditions.DownloadThroughput = 450 * 1024;
    networkConditions.UploadThroughput = 150 * 1024;
    _webDriver.NetworkConditions = networkConditions;

AND

     var options = new ChromeOptions();
     options.AddArguments("disable-infobars");

     private ChromeDriver _webDriver;
     _webDriver = new ChromeDriver(options);

    _webDriver.NetworkConditions.Latency = new TimeSpan(150);
    _webDriver.NetworkConditions.IsOffline = false;
    _webDriver.NetworkConditions.DownloadThroughput = 450 * 1024;
    _webDriver.NetworkConditions.UploadThroughput = 150 * 1024;

The seems to be occuring when trying to set ' _webDriver.NetworkConditions'

**Comment by jimevans** [comment]
This was partially fixed in 63f65c6, and the fix was completed in 4a1f340.
