### ISSUE TITLE
[WebDriverJs] 2.45 breaks Yadda examples

### ISSUE THREAD

**Issue by cressie176** [SeleniumHQ/selenium#567]
In https://github.com/acuminous/yadda/issues/109 @kblcuk reports that selenium-webdriver 0.245 causes all the [Yadda webdriver examples](https://github.com/acuminous/yadda/blob/master/examples/mocha-webdriver/test.js) examples to hang. I've reproduced and can confirm that the examples run fine with 2.44

I suspect it's related to my use of ```webdriver.promise.controlFlow().execute``` and see the selenium-webdriver code in this area has changed considerably. Am I using controlFlow() incorreclty?

**Comment by jleyba** [comment]
There's a bug that can cause the control flow to hang (see #363).

You can avoid it by changing your `before` function to wait for the driver to be fully created:

    before(function(done) {
        driver = new webdriver.Builder().usingServer().withCapabilities({'browserName': 'chrome'}).build();
        driver.manage().timeouts().implicitlyWait(10000).thenFinally(done);
    });

Alternatively:

    before(function(done) {
        executeInFlow(function() {
            driver = new webdriver.Builder().usingServer().withCapabilities({'browserName': 'chrome'}).build();
            driver.manage().timeouts().implicitlyWait(10000);
        }, done);
    });

Follow #363 for future updates on the underlying bug.
