### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service "chromedriver"

### ISSUE THREAD

**Issue by murflaw7424** [SeleniumHQ/selenium#5671]
## Meta -
OS:  Mac OSX 10.12.6
Selenium webdriver Version: 3.9.0
ChromeDriver: 2.37.544337
Browser:  Chrome
Browser Version:  Version 65.0.3325.181 (Official Build) (64-bit)

## Expected Behavior -

Program should:

1. open chrome browser
2. open indicated webpage
3. prompt for login credentials
4. select agree to terms box and login
5. select link1
6. select link2
7. select link3
8. open Tracker software

This program runs perfectly fine at the office and on my mobile hotspot.

## Actual Behavior -

When logged into my home network I error out in running the chromedriver with the following error message:
    -selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver

If I test this by connecting to my hot spot I can my code with no issues.

## Steps to reproduce -

#! /usr/bin/env python3
# This program is intended to login to the Lion Street website and utilize Tracker 4.0.
# Import selenium and webdriver to use browser

import time, selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select

# Enter login information
user = input('Enter your username: ')
pwd = input('Enter your password: ')

# Open chrome browser and Lion Street website login
chromeDriver = '/LOCATION-OF/chromedriver'
browser = webdriver.Chrome(chromeDriver)
browser.get('https://MYWEBSITE.com/')
assert "Lion Street" in browser.title
username = browser.find_element_by_id('user_login') # Find username input
password = browser.find_element_by_id('user_pass') # Fins password input
username.send_keys(user) # Send username input to webpage
password.send_keys(pwd) # Send password input to webpage

agree = browser.find_element_by_name('terms') # Finds agree to terms
agree.click() # Checks agree to terms

log_in = browser.find_element_by_name('login-submit') # Finds "Log In" button
log_in.click() # Selects "Log In" button

# Navigate to tracker

#tracker = browser.find_element_by_xpath("//img[contains(@src, 'Tracker_logo-300x71.png')]/parent::a").click() # Finds "Tracker" button
#tracker.click() # Selects "Tracker" button
quicklinks = browser.find_element_by_link_text('Quick Links').click() # Finds and clicks "Quick Links" menu
tracker = browser.find_element_by_link_text('TRACKER').click() # Finds and clicks "Tracker" button
trackerFinal = browser.find_element_by_name('tracker').click() # Finds "Go to Tracker Now" button

**Comment by lmtierney** [comment]
If it runs fine in on one network and not on the other then it is an environment issue and not an issue with selenium.

**Comment by murflaw7424** [comment]
Thank you for the fast reply.  Do you have any reason why my home network would prevent this from running?  Again, it works perfectly fine at work or off of a hotspot.

**Comment by lmtierney** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by murflaw7424** [comment]
Wanted to provide everyone an update.  I ended up having to hard reset my home wireless router for an unrelated reason, and after doing so I decided to test my selenium drivers again.  Everything now works perfectly.
