### ISSUE TITLE
Empty page on firefox when running JMeter WebDriver Sampler

### ISSUE THREAD

**Issue by hello1357** [SeleniumHQ/selenium#5672]
## Meta -
OS:  
Mac
Selenium Version:  
2.52.0
Browser:  
Firefox 

Browser Version:  
59.0.1

## Expected Behavior -
My WebDriver Sampler on JMeter looks like this:
WDS.sampleResult.sampleStart()
WDS.browser.get('http://google.com')
WDS.sampleResult.sampleEnd()

After running the Thread I can see that a new firefox browser is opened but the page is empty. 
## Actual Behavior -
After running the Thread I can see that a new firefox browser is opened but the page is empty. 
And I see this error on the logs: 
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global

I have not used port 7055.

**Comment by cgoldberg** [comment]
@hello1357 
Firefox 59 is not compatible with Selenium 2.52.  You would need Selenium 3.5+ along with geckodriver.
https://github.com/mozilla/geckodriver#selenium

**Comment by hello1357** [comment]
Thanks for the reply @cgoldberg 
I am actually using selenium as part of the JMeter plugin. And the latest version that I see is jpgc-webdriver-2.3

**Comment by hello1357** [comment]
I have installed geckodriver and updated system.properties:webdriver.gecko.driver=/Users/myName/Downloads/apache-jmeter-4.0/bin/geckodriver

**Comment by lmtierney** [comment]
Please raise an issue with JMeter, it appears they cannot handle using geckodriver or provide the means to explicitly use legacy firefox driver

**Comment by yuandai** [comment]
what's the solution here? I am having the same issue ...

**Comment by harshith-rs** [comment]
Is can i point to the geckodriver in system.properties file..?? will this work
