### ISSUE TITLE
Using a specific driver using setBinary() not working

### ISSUE THREAD

**Issue by DollarAkshay** [SeleniumHQ/selenium#5673]
## Meta -
**OS**:  Windows 10

**Selenium Version**:  selenium-webdriver 3.6.0

**Browser**:  Firefox (geckodriver v0.20.0)

**Browser Version**:  59.0.1 (64-bit)

## Expected Behavior 
`new firefox.Options().setBinary("<path>")` should use a specific driver
## Actual Behavior
Setting a binary path does not work. Throws this error instead.
```
D:\Web Automation Bot\node_modules\selenium-webdriver\lib\promise.js:2626
        throw error;
        ^

WebDriverError: Process unexpectedly closed with status 1
    at Object.throwDecodedError (D:\Web Automation Bot\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (D:\Web Automation Bot\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (D:\Web Automation Bot\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (D:\Web Automation Bot\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (D:\Web Automation Bot\node_modules\selenium-webdriver\firefox\index.js:521:41)
    at createDriver (D:\Web Automation Bot\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (D:\Web Automation Bot\node_modules\selenium-webdriver\index.js:645:16)
    at Object.<anonymous> (D:\Web Automation Bot\index.js:7:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## Steps to reproduce
Here is my code.  If i remove the `setFirefoxOptions()` it works perfectly as I have added it to my path. 
```
var webdriver = require('selenium-webdriver');
var firefox = require('selenium-webdriver/firefox');

var driver = new webdriver.Builder()
    .forBrowser('firefox')
    .setFirefoxOptions(
        new firefox.Options()
            .setBinary('D:\\Web Automation Bot\\drivers\\geckodriver.exe')
    )
    .build();

driver.get('https://google.com');
driver.sleep(1000);
driver.quit();
```

Looking for some quick help here.  Thanks 😁

**Comment by jimevans** [comment]
@DollarAkshay I'm not an expert in the JavaScript language bindings, but in other languages, the `setBinary` method on the `FirefoxOptions` object is used to define the location of the _**Firefox**_ binary, not the geckodriver binary. If there is an accompanying "service" object in the JavaScript language bindings (`FirefoxDriverService` is the class in the .NET language bindings), that is where you would set the path to the geckodriver binary.

**Comment by DollarAkshay** [comment]
@jimevans Okay, then my questinon becomes,  "how do I tell nodejs to use a specific gecko driver without adding it to my path ?"

In python I used to do it like `driver = webdriver.Chrome(chrome_options=options, executable_path=driverPath)`. Is there something like that for nodejs ?

**Comment by jimevans** [comment]
Why wouldn’t the following work (reminder, I never use the JavaScript language bindings, so I’m just going off reading the API documentation).

    var webdriver = require('selenium-webdriver');
    var firefox = require('selenium-webdriver/firefox');

    var driver = new webdriver.Builder()
      .forBrowser('firefox')
      .setFirefoxService(
        new firefox.ServiceBuilder('D:\\Web Automation Bot\\drivers\\geckodriver.exe').build()
    )
    .build();

**Comment by DollarAkshay** [comment]
@jimevans I switched to 4.0.0(Cause I guessed FirefoxService is not a part of 3.6.0). Nope dosent work. It throws this error.
```
d:\Web Automation Bot\node_modules\selenium-webdriver\index.js:474
      throw TypeError('not a firefox.ServiceBuilder object');
```

**Comment by jimevans** [comment]
Sorry, once again, I don’t use the JavaScript bindings, so I’m just going off the documentation, but the error you’re receiving should be a pretty big clue what the issue is. Don’t use the `build()` method in the `setFirefoxService()` method, since it apparently expects a `ServiceBuilder` and not the built service. To wit:

    var webdriver = require('selenium-webdriver');
    var firefox = require('selenium-webdriver/firefox');

    var driver = new webdriver.Builder()
      .forBrowser('firefox')
      .setFirefoxService(
        new firefox.ServiceBuilder('D:\\Web Automation Bot\\drivers\\geckodriver.exe')
    )
    .build();

**Comment by DollarAkshay** [comment]
@jimevans
Oh hey, that works :)
Thanks Buddy :)
