### ISSUE TITLE
unable to sendkey in selenium - call function result missing 'value'

### ISSUE THREAD

**Issue by oxiput** [SeleniumHQ/selenium#5674]
## Meta -
OS:  Window 7
Selenium Version:  3.8.1
Browser:  Chrome 65.0.3325.181

## Expected Behavior -
on email control "rahul" should get typed
## Actual Behavior -
facebook page iopened and "rahul"  is not typed. it display below error
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: call function result missing 'value'
Note: It was running good uesterd although I found this error today.
Note: Chrome Version-65.0.3325.181

## Steps to reproduce -
I have written below code
driver.get("http://facebook.com");
driver.findElement(By.xpath("//*[@id='email']")).sendKeys("rahul");

**Comment by jigyasa-at-git** [comment]
I had this exact same issue yesterday. Upgraded chrome driver to the latest
2.37 and browser to 65. Issue is resolved.

**Comment by nrjkumar41** [comment]
On 22 March, Chrome got the new update due to which this issue arises.
In case upgrading the chromedriver to 2.37 with chrome version 65 this doesn't work, then simply downgrade your chrome to 64 then it will work.

Worked for me...

Another question arises, how to stop chrome from the auto update. Well, I am sure little r&d on google will help you to get rid of this chrome auto update problem as well.

**Comment by paulinereyes** [comment]
Thanks. It works after installing the latest version of Chromedriver.exe :)

**Comment by jleyba** [comment]
Closing issue since this is a version compatibility issue that can be fixed by updating the chromedriver binary.

**Comment by GithubStarmedia** [comment]
Have that error, when update browser:
org.openqa.selenium.SessionNotCreatedException: session not created exception

  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544337

Any idea?

**Comment by koslazorkin** [comment]
install chrome64_64.0.3282.140, worked for me

**Comment by CarlosAguA** [comment]
Upadting Selenium.WebDriver.ChromDriver v2.38.0 did the trick. I´m using Visual Studio and accesed through Nuget Package Manager.

**Comment by vieckys** [comment]
Hello below is my code : 

`    it('should load url', function(done) {
        driver.get('https://www.google.com/');
        driver.findElement(webdriver.By.name('q')).click();
        driver.findElement(webdriver.By.name('q')).sendKeys('mocha docs');
    });
`

and i am getting following error : 

`     Uncaught WebDriverError: unknown error: call function result missing 'value
'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d902
3f),platform=Windows NT 6.1.7601 SP1 x86_64)`

**Comment by jamespsterling** [comment]
Updating to chrome 66 and driver 2.38 solved it for me
