### ISSUE TITLE
removed capabillity/option enbaleFullPageScreenshot

### ISSUE THREAD

**Issue by yanivyu1** [SeleniumHQ/selenium#5675]
## Meta -
OS:  

Selenium Version:  3.11

Browser:  IE11

Browser Version:  

## Expected Behavior -
existence of desierd capabillities/options after the browser is opned
## Actual Behavior -
only default one appear

**Comment by jimevans** [comment]
The IE driver now implements the W3C WebDriver Specification, which mandates that screenshots are of the current view port only. Until and unless the specification changes, it is unlikely the ability to take “full-page” screenshots will not reappear in the IE driver.
