### ISSUE TITLE
NodeJS: Support synchronous API

### ISSUE THREAD

**Issue by mfulton26** [SeleniumHQ/selenium#5680]
## Meta -
OS: Windows 10?
Selenium Version: 3.6.0

## Status Quo -

Currently [`selenium-webdriver`](https://www.npmjs.com/package/selenium-webdriver) works great with `async`/`await` but putting `await` at the beginning of each line can get a little annoying:

```js
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();
```

## Feature Request -

As many scripts don't actually need this asynchronous nature it would be great to provide a synchronous alternative.

One option would be to supply alternative methods by appending `Sync` to the end of each method name:

```js
const {Builder, By, Key, until} = require('selenium-webdriver');

let driver = new Builder().forBrowser('firefox').buildSync();
try {
  driver.getSync('http://www.google.com/ncr');
  driver.findElementSync(By.name('q'));.sendKeys('webdriver', Key.RETURN);
  driver.waitSync(until.titleIs('webdriver - Google Search'), 1000);
} finally {
  driver.quitSync();
}
```

This doesn't do much in the terms of savings. It is simply a trade-off between `await` and `Sync` but `Sync` is consistent with Node's `fs` module, etc. (e.g. `fs.readSync`).

Perhaps a better option would be to provide a synchronous API using a different module name. e.g. `selenium-webdriver/sync` instead of simply `selenium-webdriver`

```js
const {Builder, By, Key, until} = require('selenium-webdriver/sync');

let driver = new Builder().forBrowser('firefox').build();
try {
  driver.get('http://www.google.com/ncr');
  driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
  driver.wait(until.titleIs('webdriver - Google Search'), 1000);
} finally {
  driver.quit();
}
```

**Comment by mfulton26** [comment]
@jleyba, I appreciate your reply although the answer saddens me. 😞 I have been using JavaScript for awhile now and I understand that it is an asynchronous language but that hasn't prevented others from making things easier (e.g. [WebdriverIO - WebDriver bindings for Node.js](http://webdriver.io/)).

**Comment by jleyba** [comment]
If their API is blocking, then they must have some native component to adapt Node. I'm not interested in adding that complexity.

If their API merely "looks synchronous" and they handle coordination behind the scenes...well, `selenium-webdriver` did that up until the most recent release (checkout `selenium-webdrive@3.6.0`). Maybe my implementation just sucked (probable), but this just caused all sorts of headaches.

My goal with `selenium-webdriver` is to provide the barebones library for browser automation. Other users are welcome (and encouraged) to build abstractions on top of it to simplify things for their use case.
