### ISSUE TITLE
Drag and drop is not working with chrome

### ISSUE THREAD

**Issue by SafaGrayet** [SeleniumHQ/selenium#5681]
I'm runnig a selinium test with the action of drag and drop, the test passed without errors but the action was not passed, when i debugged the code i had this error "ChromeDriver: chrome on XP (f1bd42211fa54183eff27cbccf728845)"

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
