### ISSUE TITLE
action.MoveToElement() is not working in FF 59.01

### ISSUE THREAD

**Issue by toraylin** [SeleniumHQ/selenium#5683]
Hi 
I update the latest drivers.
geckodriver v.20
Firefox version 59.01
Selenium WebDriver v3.11

Today I notice that action.MoveToElement() is not working in FF 59.01 and it throws the error

Result Message:	System.InvalidOperationException : (562.533317565918, 820.0249938964844) is out of bounds of viewport width (1638) and height (810) (MoveTargetOutOfBounds).

Our tests were running fine in FF 56-58 . Any idea? 

Thanks,

Ray

**Comment by lmtierney** [comment]
This would be a bug with either geckodriver or Firefox, please file a bug with Mozilla https://bugzilla.mozilla.org
