### ISSUE TITLE
Proxy is not enabled for Internet Explorer when ie.usePerProcessProxy is true

### ISSUE THREAD

**Issue by beluha** [SeleniumHQ/selenium#5687]
## Meta -
OS:  Windows 7, Windows 10

Selenium Version:  3.x (had a chance to reproduce in 3.7.1, 3.11)

Browser:  Internet Explorer

Browser Version:  11.0.9600.18952CO, 11.966.15063.0CO

## Expected Behavior -
For enabled ie.usePerProcessProxy the proxy is used for current IE browser process
## Actual Behavior -
Proxy is ignored and is not used by current IE browser proxy at all when ie.usePerProcessProxy is true.
## Steps to reproduce -
There is simple java code using BrowserMobProxyServer

```
import org.openqa.selenium.PageLoadStrategy;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.UnexpectedAlertBehaviour;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.ie.InternetExplorerOptions;
import org.openqa.selenium.internal.ElementScrollBehavior;

import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;

public class IeProxy {
    private static BrowserMobProxy proxyServer = new BrowserMobProxyServer();

    public static void main(String[] args) throws InterruptedException {
        Proxy proxy = getProxy();
        InternetExplorerOptions internetExplorerOptions = new InternetExplorerOptions();
        internetExplorerOptions
            .setProxy(proxy)
            .requireWindowFocus().usePerProcessProxy().enableNativeEvents()
            .introduceFlakinessByIgnoringSecurityDomains().ignoreZoomSettings()
            .setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.ACCEPT)
            .enablePersistentHovering().setPageLoadStrategy(PageLoadStrategy.EAGER)
            .elementScrollTo(ElementScrollBehavior.TOP).setCapability(InternetExplorerDriver.SILENT, true);

        WebDriver driver = new InternetExplorerDriver(internetExplorerOptions);
        driver.get("http://google.com");

        Thread.sleep(5000);

        // stopping driver and proxy
        driver.close();
        driver.quit();
        proxyServer.abort();
    }

    private static Proxy getProxy() {
        proxyServer.setTrustAllServers(true);
        proxyServer.start();

        return ClientUtil.createSeleniumProxy(proxyServer);
    }
}
```

If do not call `usePerProcessProxy()` then it means we use system proxy. And on the loaded page we will see expected behavior 
![expected](https://user-images.githubusercontent.com/19341020/37957655-2e032bb2-31b7-11e8-9bc5-8db7453e5846.PNG)

If to call `usePerProcessProxy()` then proxy is ignored at all. And unexpected and actual behavior for the loaded page is 
![actual](https://user-images.githubusercontent.com/19341020/37957792-8485b87e-31b7-11e8-92ce-17bebe8edfec.PNG)

So for `usePerProcessProxy()` we expect to see 
![expected](https://user-images.githubusercontent.com/19341020/37957822-983e67bc-31b7-11e8-9c75-7d5ce7436a88.PNG)
for the `driver.get("http://google.com");`

Maven dependencies:
```
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.11.0</version>
        </dependency>        
        <dependency>
            <groupId>net.lightbody.bmp</groupId>
            <artifactId>browsermob-core</artifactId>
            <version>2.1.5</version>
        </dependency>
```

Related issues:
https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/8257

**Comment by jimevans** [comment]
Can you provide a trace-level log from `IEDriverServer.exe`?

**Comment by beluha** [comment]
[ie.log](https://github.com/SeleniumHQ/selenium/files/1851769/ie.log)
Added Trace log.

**Comment by beluha** [comment]
[ie.log](https://github.com/SeleniumHQ/selenium/files/1851783/ie.log)
Attached.

**Comment by beluha** [comment]
Windows 10
[ie.log](https://github.com/SeleniumHQ/selenium/files/1851852/ie.log)
OS 64 bit.

**Comment by jimevans** [comment]
As I suspected, using the 32-bit driver works. You should almost certainly be using the 32-bit driver anyway, [even on 64-bit Windows](http://jimevansmusic.blogspot.com/2014/09/screenshots-sendkeys-and-sixty-four.html). The logs you collected even call this out:

> W 2018-03-27 14:53:17:699 c:\projects\webdriver\cpp\iedriver\proxymanager.cpp(255) Proxy will not be set! There is a mismatch in the bitness between the driver and browser. In particular, be sure you are not attempting to use a 64-bit IEDriverServer.exe against IE 10 or 11, even on 64-bit Windows.
