### ISSUE TITLE
Wiki Page needs updating

### ISSUE THREAD

**Issue by jguffey** [SeleniumHQ/selenium#5690]
## Meta -
OS:  
N/A
Selenium Version:  
N/A
Browser:  
N/A

On the page: https://github.com/SeleniumHQ/selenium/wiki/Logging links labeled "capabilities page" lead to https://github.com/SeleniumHQ/selenium/DesiredCapabilities when they should lead to https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities. I cannot find how to suggest wiki edits, otherwise I'd submit a PR myself.

## Expected Behavior -
When I click "capabilities page" , I should be taken to https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

## Actual Behavior -
I am actually taken to https://github.com/SeleniumHQ/selenium/DesiredCapabilities, a 404 page.

## Steps to reproduce -
Visit https://github.com/SeleniumHQ/selenium/wiki/Logging and click on any link labeled "capabilities page".

**Comment by p0deje** [comment]
Thank you, fixed!
