### ISSUE TITLE
Wrong parameter name for chrome network conditions in .Net implementation

### ISSUE THREAD

**Issue by KokaChernov** [SeleniumHQ/selenium#5693]
From https://bugs.chromium.org/p/chromedriver/issues/detail?id=2356

Looks like wrong command parameter here:
https://github.com/SeleniumHQ/selenium/blob/selenium-3.11.0/dotnet/src/webdriver/Chrome/ChromeDriver.cs#L150 

Should be spelled as 'network_conditions' instead of 'network_connection'

**Comment by jimevans** [comment]
Fixed in 63f65c6.

**Comment by KokaChernov** [comment]
@jimevans thank you.
