### ISSUE TITLE
Unable to connect Google Calendar Account

### ISSUE THREAD

**Issue by AntaninaKaltsova** [SeleniumHQ/selenium#5697]
OS:
Windows 10, MacOS

Selenium-standalone version:
6.13.0

Chrome driver:
2.37-x64-chromedriver

Browser:
Chrome

Browser Version:
Version 65.0.3325.181 (Official Build) (64-bit)

**## Expected Behavior**
User is expected to register connect Google Calendar Account as an external service. The user is faced with the standard Google login process - three screens, one each for user id, password, and authorization acceptance. The user provides the appropriate information on the first two screens, clicking next after populating the input, and then clicks Allow on the final input, at which point he is redirected back to the Application having authorized his usage of Google.

**## Actual Behavior**
The google username screen and password screen is displayed as expected, however the third step where the google interface renders the Authorize permissions screen instead renders a white page (see screenshot).

![e633767422a7d9e8d316e07571bff830](https://user-images.githubusercontent.com/15190546/38016258-2952909c-3277-11e8-89d0-eba827255414.png)

**Comment by monpriya** [comment]
We've got the same issue using
MacOS;
Selenium-webdriver 3.8.0;
Chrome Driver 2.37.544337;
Chrome Version 65.0.3325.181 (Official Build) (64-bit).

**Comment by radiovisual** [comment]
Thanks for reporting. 

Can someone post a [reproducible test case](http://sscce.org/) that can be run to speed up the feedback loop on this issue?

**Comment by monpriya** [comment]
Reproduce step:
visit "https://accounts.google.com/signin/oauthxxxxx" (third party website)

find_by_id('identifierId').set(username)
click_button("Next")

find_by_id('identifierpassword').set(password)
click_button("Next")

this page shows url "https://accounts.google.co.th/accounts/SetSID" 
expect authorize permissions screen

**Comment by testphreak** [comment]
The issue isn't related to Selenium from my investigation. The issue seems to have been introduced with ChromeDriver greater than v2.35. There's [2357](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2357) and [2359](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2359) on the `chromedriver` project that talks about this issue. There is an active conversation on another [thread](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2354) currently on that project, related to this issue.

**Comment by monpriya** [comment]
Thank you so much

**Comment by lmtierney** [comment]
Closed, see issues referenced by @testphreak
