### ISSUE TITLE
Selenium python binding throwing wrong exception for stale element in IE

### ISSUE THREAD

**Issue by PhilippSelenium** [SeleniumHQ/selenium#5700]
## Meta -
OS:  
Windows 10
Selenium Version:  
IEDriverServer: 3.11.1
Python bindings: 3.11.0
Browser:  
Internet Explorer 10/11

Browser Version:  
Internet Explorer 10/11

## Expected Behavior -
StaleElementReferenceException: Message: Element is no longer valid

## Actual Behavior -
InvalidArgumentException: Message: Element is no longer valid

## Steps to reproduce -
Access a stale element in IE 10/11

## Traceback:
```
  File "C:\Users\buibot00\venv\bb\lib\site-packages\selenium\webdriver\remote\webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\buibot00\venv\bb\lib\site-packages\selenium\webdriver\remote\webelement.py", line 653, in find_element
    {"using": by, "value": value})['value']
  File "C:\Users\buibot00\venv\bb\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\buibot00\venv\bb\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\buibot00\venv\bb\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
InvalidArgumentException: Message: Element is no longer valid
```

**Comment by lmtierney** [comment]
I don't have access to a WIndows machine right now, can you provide the full stacktrace?

**Comment by PhilippSelenium** [comment]
I am sorry but I cannot give you the top half of the traceback since it is code specific to our company and i am not allowed to post that here. But all the calls to selenium are in the traceback. I attached the driver log
[iedriverserver_test_stream_detection.log](https://github.com/SeleniumHQ/selenium/files/1870562/iedriverserver_test_stream_detection.log)
.

**Comment by lmtierney** [comment]
It looks like you're trying to find a new element based on a stale element as the root:

```
D 2018-04-03 04:49:20:075 server.cc(339) Command: POST /session/7752da94-ffbd-4f9e-a432-c925ffb367b0/element/41083761-8b83-4142-a6e9-0549c64ac030/element {"using": "xpath", "id": "41083761-8b83-4142-a6e9-0549c64ac030", "value": "./div/div[2]"}
D 2018-04-03 04:49:20:075 command.cc(36) Raw JSON command: { "name" : "findChildElement", "locator" : { "sessionid" : "7752da94-ffbd-4f9e-a432-c925ffb367b0", "id" : "41083761-8b83-4142-a6e9-0549c64ac030" }, "parameters" : {"using": "xpath", "id": "41083761-8b83-4142-a6e9-0549c64ac030", "value": "./div/div[2]"} }
D 2018-04-03 04:49:20:075 IECommandExecutor.cpp(699) No alert handle is found
W 2018-04-03 04:49:20:078 IECommandHandler.cpp(53) Found managed element is no longer valid
D 2018-04-03 04:49:20:079 server.cc(396) Response: {"value":{"data":null,"error":"invalid argument","message":"Element is no longer valid","stacktrace":""}}
```

@jimevans should this give `invalid argument` or `stale element reference`?

**Comment by jimevans** [comment]
The IE driver is returning the wrong error here, according to the spec.

**Comment by jimevans** [comment]
I've corrected the issue in the IE driver to now return the "stale element reference" error type. The python bindings (and all others) should pick up this fix for free. If you are still running into python-specific symptoms surrounding this behavior, please file a new issue.
