### ISSUE TITLE
Unable to access element that has ng-click

### ISSUE THREAD

**Issue by juzdarwin** [SeleniumHQ/selenium#5703]
## Meta -
OS:  Windows 10
Selenium Version:  3.4
Browser:  Firefox
java: 1.8

<span title="Edit Client" ng-click="clientCardCtrl.GoToClientProfile(client.ClientId)" class="label label-success pull-right handlink">
                <i class="fa fa-edit"></i>
            </span>
Browser Version:  59.0.2(64 bit)

## Expected Behavior 
I am able to access this element to click on it

## Actual Behavior -
i am not able to access this element to click on it

**Comment by lmtierney** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we can act on this issue. Once this is done the issue will be re-opened. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
