### ISSUE TITLE
C# ChromeDriver throws exception when executed dynamically by reflection.

### ISSUE THREAD

**Issue by TrailRunner-MF** [SeleniumHQ/selenium#5705]
## Meta -
OS:  
Windows 10 Enterprise (64 bit)
Selenium Version:  
Selenium.WebDriver.3.11.0
Selenium.WebDriver.ChromeDriver.2.37.0
Browser:  
Chrome Browser version 65.0.3325.181（Official Build）(64 bit)

.NET Framework： version 4.6.1
MSTest.TestFramework.1.2.0
MSTest.TestAdapter.1.2.0

## Expected Behavior -
Test method equiped with chrome driver should work when it is invoked by dotNet reflection.

## Actual Behavior -
It throws System.InvalidOperationException: 
Exception message is as follows.
disconnected: unable to connect to renderer  
  (Session info: chrome=65.0.3325.181)  
  (Driver info: chromedriver=2.31.488763 

## Steps to reproduce -
Please extract attachment file in any arbitrary folder, then visual studio solution 'TrialWebTestForInspection.sln' will appear.

[TrialWebTestForInspection.zip](https://github.com/SeleniumHQ/selenium/files/1858453/TrialWebTestForInspection.zip)

The solution consists of two projects, "TrialWebUnitTest" and "TrialWebUnitTestRunner".

The first one "TrialWebUnitTest" is MS Unit Test, and it contains 3 test methods. 
Each of them a very simple and they just launch webdriver-corresponding browser and navigate to Selenium HQ site.

The test method is like as follows.
```
[TestMethod]
public void NavigateToSeleniumHQByChrome()
{
	string TargetUrl = "https://www.seleniumhq.org/projects/webdriver/";
	this.driver = new ChromeDriver();
	driver.Manage().Window.Size = new System.Drawing.Size(1000, 800); // <- Exception raise here!
	this.driver.Navigate().GoToUrl(TargetUrl);
	this.driver.Dispose();
}
```

The later one "TrialWebUnitTestRunner" is a WindowsForm application which provide a simple test runner user interface.
It refers to the previous "TrialWebUnitTest" as a ClassLibrary, and it kicks each test method in it.
The test method invoking program is like as follows.
```
internal bool ExecTestDynamically(ref string retErrorMsg)
{
	var target = new TrialWebUnitTest.WebDriverTest01();
	System.Type targetType = typeof(TrialWebUnitTest.WebDriverTest01);
	var method = targetType.GetMethod("NavigateToSeleniumHQByChrome");
	try
	{
	    method.Invoke(target, null);
	    return true
	}
	catch (Exception exp)
	{
	    retErrorMsg = exp.Message + Environment.NewLine + exp.StackTrance;
	    return false;
	}
}
```

When you invoke test method which run IE-driver or FireFox-driver, it works fine.
But when you choose Chrome-driver, the following exception is thrown.

> System.InvalidOperationException:  
disconnected: unable to connect to renderer  
  (Session info: chrome=65.0.3325.181)  
  (Driver info: chromedriver=2.31.488763 

--------
I'd like to know,  if it is a bug of current Chrome driver version, or it is a part of specification.
Then I'd like to know, if there is a way to avoid this problem.

What I'm afraid of is the possibility that IWebDriver specification originally does not support correct action whent it is run by reflection.

**Comment by jimevans** [comment]
You say you’re using chromedriver.exe 2.37, but your exception info indicates 2.31. If that’s the case, chromedriver.exe may not be able to communicate with Chrome 65. Because of using reflection, the .NET bindings may be picking up a different chromedriver than you expect. What happens if you explicitly state where chromedriver is found in the `ChromeDriver` constructor?

**Comment by TrailRunner-MF** [comment]
Thanks jimevans.

I installed selenium webdriver and chrome driver by using nuget manager in visual sutudio 2017.
As I show the image below, nuget package manager shows the chrome driver's version is latest, v.2.73.0.
![nugetmanager01](https://user-images.githubusercontent.com/12433690/38070024-94952490-3354-11e8-966f-9f686f251855.jpg)

Another evidence is the following image that shows nuget package is recovered in installing folder and extract the correct version package file, Selenium.WebDriver.ChromeDriver.2.37.0.nupkg.
![nugetmanager02](https://user-images.githubusercontent.com/12433690/38070145-4c5afdac-3355-11e8-8af0-6565b7c36956.jpg)
 
But it is true that the error message shows "(Driver info: chromedriver=2.31.488763".
What I suspect now is that the nuget package of chromedriver version 2.37.0 content is different version. I'm afraid it's downgraded unintentionally.

**Comment by lmtierney** [comment]
@TrailRunner-MF you might try `where chromedriver` from a command prompt to see if there are multiple versions on your path

**Comment by jimevans** [comment]
@TrailRunner-MF When I get to a place I can run code, I’ll be happy to take a look at your sample. In the meantime, as a means of gathering more data on the issue, is it that much of a burden for you to make the minor change I asked and trying it on your end? Please try using a specific path to chromedriver.exe where you have manually downloaded the executable (not relying on NuGet).

**Comment by jimevans** [comment]
@TrailRunner-MF And, yes, by specifying a path in the `ChromeDriver` constructor, I'm able to get the test to run in both instances, using reflection and not. Sounds like relying on the Nuget package to place chromedriver.exe in a place where it can be reliably found when code is run via reflection is a mistake. Given that, I'm closing this issue report as the language bindings are working as they should, when the driver executable can be reliably found.

**Comment by TrailRunner-MF** [comment]
@jimevans Thank you very much for your advice. In accordance with your advice I tried to find the chromedriver installed path, but I found much easier way.
I found that not only in classlibrary (TrialWebUnitTest), but also in WindowsForm TestRunner, I should have to install chromedriver expressly.
In Visual Studio, this operation is so simple. I kicked up nuget-manager in testrunner project (TrialWebUnitTestRunner) and installed essential nuget packages(selenium.webdriver, chromdriver, and so on), Then packages.config file was generated automatically in testrunner projects which specify the latest version of every nuget-packages. Of course test-runner's chrome operation start working fine!

So far, every thing is OK. I put the revised version of the sample program in it. Please close this issue.
Thank you for your help. I really appliciate it.

[Uploading TrialWebTestForInspection.Revised.zip…]()
