### ISSUE TITLE
Add support for the new Safari Driver in javascript

### ISSUE THREAD

**Issue by paladox** [SeleniumHQ/selenium#5707]
## Meta -
OS:  mac 10.13
Selenium Version:  3
Browser:  safari

Browser Version:  11.0.3 (13604.5.6)

## Expected Behavior -
I expect to be able to run tests in safari using javascript

## Actual Behavior -
It dosen't work

It starts the browser but then immediately closes a few seconds after. Whereas it works with chrome.

Is the new safari driver supported in javascript?

**Comment by paladox** [comment]
https://github.com/SeleniumHQ/selenium/commit/a793d61bfc1ea4fdb20e6b222ae25bfdb117d9f3

says that some safari driver code was moved to the safari branch, but im confused why? Also the branch does not exist any more.

**Comment by jleyba** [comment]
Yes, it does work. I ran the `selenium-webdriver` test suite against Safari less than 2 weeks ago (and haven't made any changes since).

Closing this issue because no information was provided beyond "It doesn't work"
