### ISSUE TITLE
Use "ChromeOpthions().set_headless() " to start_up chrome with headless is not work.

### ISSUE THREAD

**Issue by JamesBaiyong** [SeleniumHQ/selenium#5708]
## Meta -
OS:  ubuntu 

Selenium Version:  
3.11.0

Browser:  
chrome

Browser Version:  
65.0.3325.181 

## Expected Behavior -
start chrome with headless
## Actual Behavior -
start chrome not headless
## Steps to reproduce -
**This code will open a chrome window,that is not start_up chrome withe headless**
```python
from selenium import  webdriver
web = webdriver.ChromeOptions().set_headless()
d = webdriver.Chrome(chrome_options=web,executable_path='./chromedriver')
d.get('http://www.baidu.com')
d.quit()
```
**But use this code that be work**
```python
from selenium import  webdriver
web = webdriver.ChromeOptions()
web.add_argument("--headless")
web.add_argument("--disable-gpu")
d = webdriver.Chrome(chrome_options=web,executable_path='./chromedriver')
d.get('http://www.baidu.com')
print(d.page_source)
d.quit()
```

Then i try to find reason 
I am find that diffent withe this \:
use set_headless \:
in optihons.py 192 line will return {.......'args':[],......}
use add_argument \:
in opthons.py 192 line will return {....'args':['--headless','--disable--gpu'],......}

so, that is a bug?
can you tell me the rason?
thank you very much 😊

**Comment by lmtierney** [comment]
Because this line

```
web = webdriver.ChromeOptions().set_headless()
```

Returns `None`

The `set_headless()` command does not return an instance of the `ChromeOptions`, you'd need to write it as

```
web = webdriver.ChromeOptions()
web.set_headless()
```
