### ISSUE TITLE
not a valid Base-64 Error on GetScreenshot() for IEWebDriver 

### ISSUE THREAD

**Issue by sisillV** [SeleniumHQ/selenium#5712]
## Meta -
OS:  Windows server 2016

Selenium Version:  3.11.0
IEWebDriver 3.11.1
Browser:  Internet Explorer 11

-->

Browser Version:  11.1198.14393.0

## Expected Behavior -
I run c# code:
((ITakesScreenshot)driver).GetScreenshot().SaveAsFile(some path + "/screenshot" + dateFormatFileNameStr + ".png", ScreenshotImageFormat.Png);

And I expect the screenshot to be taken and saved in the foder.

## Actual Behavior -
I see error message:
ErrorMessage: 
 System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
StackTrace: 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at OpenQA.Selenium.Remote.RemoteWebDriver.GetScreenshot()

**Comment by pranav700** [comment]
I think it's getting converted to a modified Base64, where the / character is changed  _. See http://en.wikipedia.org/wiki/Base64#Implementations_and_history. 
Try this
((ITakesScreenshot)driver).GetScreenshot().SaveAsFile(some path + @"\screenshot\" + dateFormatFileNameStr + ".png", ScreenshotImageFormat.Png);

**Comment by barancev** [comment]
Please provide a sample page that gives invalid screenshots.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
