### ISSUE TITLE
Error on using WebDriverWait instance

### ISSUE THREAD

**Issue by Mohsin-Awan7500** [SeleniumHQ/selenium#5718]
I get error on this line while compiling:

Setup.wait.until(ExpectedConditions.presenceOfElementLocated(By.id(HomeScreen.tabHome_ID)));

I'm using IntelliJ IDE

**Error**

Error:(51, 19) java: method until in class org.openqa.selenium.support.ui.FluentWait<T> cannot be applied to given types;
  required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
  found: org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
  reason: cannot infer type-variable(s) V
    (argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)

**Comment by lmtierney** [comment]
What version is your Guava at? You need 23+ I believe

**Comment by Mohsin-Awan7500** [comment]
I'm not using Guava in my project. It is working fine. I made a new project where it is causing problem!

**Comment by barancev** [comment]
Please show your project classpath settings.

**Comment by Mohsin-Awan7500** [comment]
![image](https://user-images.githubusercontent.com/31037041/38199244-7c05c2e2-36a9-11e8-92ec-39a99679cb4f.png)

Didn't get what you are asking for?

**Comment by Mohsin-Awan7500** [comment]
If I don't use the **wait** to fix it then I get error while instantiating driver:

java.lang.NoSuchFieldError: INSTANCE

**Comment by barancev** [comment]
Ctrl-click `ExpectedConditions` class to dive into it, then find a use of `ExpectedCondition` class and ctrl-click it, you should see that it `extends Function<WebDriver, T>`, again ctrl-click `Function` interface, you shold see that it's
```
public interface Function<F, T> extends java.util.function.Function<F, T>
```
Also watch the window title to see what jar file this `Function` interface belongs to.

**Comment by Mohsin-Awan7500** [comment]
![image](https://user-images.githubusercontent.com/31037041/38199935-e7279e0e-36ab-11e8-95b9-ba82e3db5c85.png)

Did it help?

**Comment by barancev** [comment]
Watch the title. You're using selenium 3.4.0 apparently. You have to configure classpath properly.
