### ISSUE TITLE
IEDriver takeScreenshot() scroll to page top before taking the image

### ISSUE THREAD

**Issue by yanivyu1** [SeleniumHQ/selenium#5719]
## Meta -
OS:  windows 10
Selenium Version:  3.11
Browser:  IE11

i'm trying to take a screenshot of a scrollable element on IE11 and do it with scroll and take screenshot.
i scroll each iteration to a different position in the page but before the IEdriver take the screenshot it scroll to the top of the page and takes screenshot of the page's top section over and over again
Browser Version:  

## Expected Behavior -
take screenshot of the current position
## Actual Behavior -
take screenshot of the page's top
## Steps to reproduce -
scroll in jumps of 250px and use the selenium getScreenshotAs(OutputType.BASE64) method

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario.
