### ISSUE TITLE
[Query] Unable to pass a variable string to the ExpectedConditions method presenceOfElementLocated()

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#5720]
## Meta - Need help to understand the implementation of the _ExpectedConditions_ method `presenceOfElementLocated()` which is defined as :

```
  public static ExpectedCondition<WebElement> presenceOfElementLocated(final By locator) {
    return new ExpectedCondition<WebElement>() {
      @Override
      public WebElement apply(WebDriver driver) {
	return findElement(locator, driver);
      }
```

In one of my Tests I have implemented _WebDriverWait_ as follows :

```
public static WebDriverWait wait = null; 
wait = new WebDriverWait(driver, 120);
wait.until(ExpectedConditions.presenceOfElementLocated(By.id(HomeScreen.tabHome_ID)));
```
This gives me an error as follows : 

```
Error:(51, 19) java: method until in class org.openqa.selenium.support.ui.FluentWait cannot be applied to given types;
required: java.util.function.Function<? super org.openqa.selenium.WebDriver,V>
found: org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement>
reason: cannot infer type-variable(s) V
(argument mismatch; org.openqa.selenium.support.ui.ExpectedCondition<org.openqa.selenium.WebElement> cannot be converted to java.util.function.Function<? super org.openqa.selenium.WebDriver,V>)
```

Can someone help me to understand where am I wrong?

OS:  Windows8 Pro
Selenium Version:  3.x
Browser:  Firefox

Browser Version:  59.0.2 (64-bit)

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Debanjan-B** [comment]
Thanks @lmtierney Actually, I did posted this question on [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). But as the question deals with the source code (though Selenium is Open Source) hence deleted the question from selenium user group. Let me know if discussing the Selenium Source Code in public forums is acceptable to Selenium Team.
