### ISSUE TITLE
PhantomJSDriverService interface missing in Selenium 3.11.0

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#5721]
## Meta -
OS:  
Windows 7
Selenium Version:  
3.11.0
Browser:  
Chrome

I was used the selenium 3.7.1. Now I just updated to selenium 3.11.0 and I got error in my PhantomJS driver section. It seems PhantomJSDriverService interface missing. What is the alternative to start PhantomJS in Selenium 3.11.0 for headless execution?

Thanks,
sanojqa

**Comment by barancev** [comment]
Now you have to add a dependency on PhantomJS driver explicitly to the classpath.

**Comment by sanojqa** [comment]
@barancev Following is the dependency right?

<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>1.4.4</version>
</dependency>

**Comment by barancev** [comment]
No idea. Support for "official" PhantomJS driver has been discontinued, so you have to choose the best of the forks.
