### ISSUE TITLE
Selenium grid performance

### ISSUE THREAD

**Issue by vinutha5** [SeleniumHQ/selenium#5726]
## Meta -
OS:   Windows 2008 server 
Selenium Version:  3.8.1 
Browser:  Chrome

Hi,

I am trying to run selenium grid.

Currently I'm using v3.8.1 with one hub on 1 network and 20+ nodes of different networks registering to that selenium hub.

Its executing fast when hub and node are created on same machine where the application has deployed. Nodes created in other remote machines are comparatively slow.

For 100 test steps execution, the node with in the application server machine takes 3 min 30 sec but node in other rdps takes 5 min 30 secs

We have tested on network latency and tried creating Node on same network machine but still took same time as other network rdps.

More Info : Windows server 2008, Ruby gem - selenium-webdriver-2.53.4, selenium-server-standalone-3.8.1, Java 8.

Tried with these selenium grid versions - 2.48, 2.49, 2.52, 2.53 and 3.8.1

Any help on this is appreciated. Thank You.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
