### ISSUE TITLE
Delay each execution step for debugging purposes

### ISSUE THREAD

**Issue by Freyert** [SeleniumHQ/selenium#5727]
Loads of Selenium stackoverflow questions regarding slowing test execution down to a pace visible by the human eye.

Implicit waits seem to be the play, but it's not _exactly_ what people want and the benefit from just _delaying all executions_ so that they are visible would be fantastic for debugging.

Has this already been done?

**Comment by lmtierney** [comment]
You could use an `EventFiringWebDriver` with an `AbstractEventListener` that performs some sort of delay in the `before_` methods. I'm not sure something like this already exists or not.

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
