### ISSUE TITLE
ChromeDriver throwing -> call function result missing 'value' 

### ISSUE THREAD

**Issue by Thabane** [SeleniumHQ/selenium#5732]
## Meta -
OS:  
Windows 7
Selenium Version:  
ChromeDriver 2.37
Browser:  
Chrome

Driver throws the error below every time the sendkey() method is called.

"call function result missing 'value' " the rest on the exception message is details about the chrome driver version.

Browser Version:  
Latest Chrome Update 65

## Expected Behavior -
Send keys to the element as expected.

## Actual Behavior -
Throws an error upon attempting to do this.

## Steps to reproduce -
Run a test scenario where the chrome driver is being used to send a string to a textbox element.
Preferable run this is a loop that that does the same for like 100 times. Because I have a hunch that this might be caused by large load. I use the the driver to regression testing.

**Comment by barancev** [comment]
This issue should be reported to chromedriver:
https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by vieckys** [comment]
same error for me also.
