### ISSUE TITLE
UnsupportedDriverException when running test case in linux

### ISSUE THREAD

**Issue by chiragghai** [SeleniumHQ/selenium#5733]
OS:  LINUX
Selenium Version:  2.53.1
Browser:  chrome 65
Chromrdriver: 2.37

While running the test cases in **Windows agent**, I got success but when running the same in **Linux** I get unsupported driver exception.
I tried all the chrome driver compatibility with chrome browser but same error 
 
**Caused by: net.thucydides.core.webdriver.UnsupportedDriverException at HomeSteps.java:37
            Caused by: net.thucydides.core.webdriver.UnsupportedDriverException at HomeSteps.java:37
                Caused by: org.openqa.selenium.WebDriverException at HomeSteps.java:37**

Dependencies in build.gradle:-
	compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version:'2.53.1'
    compile group: 'net.serenity-bdd', name: 'serenity-core', version:'1.1.25-rc.5'
    compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version:'2.53.1'
    //compile group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.7'
    compile group: 'net.serenity-bdd', name: 'serenity-junit', version: '1.2.3-rc.3'
    compile group: 'org.assertj', name: 'assertj-core', version:'1.7.0'
    compile group: 'com.googlecode.lambdaj', name: 'lambdaj', version:'2.3.3'
    compile group: 'org.scream3r', name: 'jssc', version:'2.8.0'
    compile group: 'org.apache.commons', name: 'commons-exec', version:'1.3'
    compile group: 'org.apache.commons', name: 'commons-lang3', version:'3.0'
    compile group: 'commons-io', name: 'commons-io', version:'2.4'
    compile group: 'commons-lang', name: 'commons-lang', version: '2.6' 
    compile group: 'log4j', name: 'log4j', version:'1.2.17'
   	compile group: 'com.thoughtworks.xstream', name: 'xstream', version: '1.4.9'
   	compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'  	
   	compile group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version:'2.8.5'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version:'2.8.5'
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version:'2.8.5'
    compile group: 'org.springframework', name: 'spring-core', version:'4.3.3.RELEASE'
    compile group: 'org.apache.cxf', name: 'cxf-rt-frontend-jaxws', version:'3.0.2' 
    compile group: 'com.google.code.gson', name: 'gson', version: '2.6.2'
   	compile group: 'com.google.guava', name: 'guava', version: '22.0' 	
   	compile group: 'org.apache.cxf', name: 'cxf-rt-transports-http', version: '3.0.3'
   	compile(group: 'nddsjava-natives', name: 'nddsjava-natives', version:'5.3.0.2',classifier:'natives-linux64bit')  
    compile(group: 'nddsjava-natives', name: 'nddsjava-natives', version: '5.3.0.2',classifier:'natives-macosx64bit')  
    compile(group: 'nddsjava-natives', name: 'nddsjava-natives', version: '5.3.0.2',classifier:'natives-windows64bit') 
    compile group: 'org.apache.poi', name: 'poi', version: '3.9'

Why it is so that it worked in windows agent and not in linux?

**Comment by barancev** [comment]
Please report this issue to thucydides project.

**Comment by chiragghai** [comment]
But I faced "org.openqa.selenium.WebDriverException" this one too. If you know the solution please let me know.

**Comment by barancev** [comment]
Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
