### ISSUE TITLE
Selenium WebDriver has inconsistent behaviour on finding Elements (contained in IFrame)

### ISSUE THREAD

**Issue by marci13** [SeleniumHQ/selenium#5734]
## Meta -
OS:  Windows 10
Selenium Version:  3.10.0
Browser:  Google Chrome
Browser Version:  Version 65.0.3325.181 (Official Build) (32-bit)
Java Version: JDK 1.8.0_131

## Expected Behavior - 
When invoking findElement() for an Element, which is not yet attached to the DOM, because the IFrame is not loaded yet, one expects, that the WebDriver will find the Element after it has appeared in the DOM with implicit wait timeout sufficiently choosen.
When WebDriverWait.until(...) has no disadvantage compared to Thread.sleep(...) 

## Actual Behavior -
When invoking findElement() before IFrame is loaded (Element not available) it will cause:
1) NoSuchElementException (if implicit wait timeout to low)
2) NoSuchElementException (if implicit wait timeout large enough) though element gets loaded and attached to DOM during execution time

When invoking WebDriverWait.until( [ElementVisible] )
1) TimeoutException (if explicit wait timeout to low),
2) TimeoutException (if explicit wait timeout large enough), though element has been loaded and appears in DOM

When pausing the Application in Debug Mode after failing to find the desired element, it will never be found again, no matter how long you wait, though it is clearly loaded in the browser.

Now the Abnormality:
If one uses Thread.sleep() before with sufficiently large time amount, findElement() as well as WebDriverWait.until() end up successfull finding element or returning from wait with no exception.
If then the program is stopped in debug mode, one will always find the element.

So there seems to be a different in the state of the WebDriver object when you either:
1) use it (e.g. findElement()) BEFORE element is loaded correctly
2) do NOT use it until element is loaded correctly

(also works when you set breakpoint before finding element instead of Thread.sleep() and continue after element appears in browser)

The behaviour of the WebDriver after the element is loaded is expected to be the same, no matter if you try to find an element before its loaded or not. This is not the case with this issue.
 
## Steps to reproduce -

Here a little example code:
################################################################################
// getting Selenium WebDriver object
final WebDriver driver = this.seleniumContext.getDriver();

// setting implicit wait timeout sufficiently large (5 seconds)
driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);

try {
	driver.findElement(By.id("ELEMENT_ID"));
	System.out.println("Driver HAS found element BEFORE sleep!");
} catch (final NoSuchElementException e) {
	System.out.println("Driver has NOT found element BEFORE sleep!");
}

// sleeping 5 seconds
Thread.sleep(5000);

try {
	driver.findElement(By.id("ELEMENT_ID"));
	System.out.println("Driver HAS found element AFTER sleep!");
} catch (final NoSuchElementException e) {
	System.out.println("Driver has NOT found element AFTER sleep!");
}
################################################################################
Output:
Driver has NOT found element BEFORE sleep!
Driver has NOT found element AFTER sleep!
################################################################################
Now the example with no findElement() before sleep:
################################################################################
// getting Selenium WebDriver object
final WebDriver driver = this.seleniumContext.getDriver();

// setting implicit wait timeout sufficiently large (5 seconds)
driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);

// sleeping 5 seconds before first findElement()
Thread.sleep(5000);

try {
	driver.findElement(By.id("ELEMENT_ID"));
	System.out.println("Driver HAS found element AFTER sleep!");
} catch (final NoSuchElementException e) {
	System.out.println("Driver has NOT found element AFTER sleep!");
}
################################################################################
Output:
Driver HAS found element AFTER sleep!
################################################################################

Now the big Question:

How can the first call of findElement() (before sleep) influence the result of the second call (after sleep) ?
If you leave it out, the driver then finds the element.

Can someone explain the behaviour of the WebDriver in this case, and maybe give me a solution to properly wait for the desired element? Remind, that if a wait routine is invoked before sleep, it will still not find the element and always ends up in TimeoutException.

Thanks for Your support Folks,

Kind Regards,

Marcel

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) including a sample page where the issue can be reproduced.

**Comment by lmtierney** [comment]
I'm guessing you're running into this issue:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2198

**Comment by goyalgaurav85** [comment]
We also observed similar kind of issue. In our application, we observed inconsistent behavior for few of the elements contained in an iFrame. 
We are trying to find element **using an unique id** but it is throwing an **error saying, unable to find element with this CSS Selector.**  Following is the screenshot :-
![err](https://user-images.githubusercontent.com/38128010/38412186-673a3104-39a6-11e8-8bae-9e0b10c2caf4.png)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario.
