### ISSUE TITLE
Update Selenium-Webdriver WebElement ID Keys for Firefox 61+

### ISSUE THREAD

**Issue by chenba** [SeleniumHQ/selenium#5735]
## Meta -
OS:  Linux

Selenium Version:  4 (selenium-webdriver 4.0.0alpha-1 npm module)

Browser:  Firefox

Browser Version:  61.0a1 (64bit)

## Expected Behavior -
Selenium-Webdriver successfully extracting a chrome element in Firefox as a WebElement.

## Actual Behavior -
Selenium-Webdriver extracting a chrome element in Firefox as a plain object.

## Steps to reproduce -

Once you have an instance of a Firefox driver: 
```
driver.setContext(firefox.Context.CHROME)
.then(()=>driver.wait(until.elementLocated(By.id('pageActionButton'))));
```

I'm filing this preemptively... I saw that Firefox Nightly now has a change from [bug 1400233](https://bugzilla.mozilla.org/show_bug.cgi?id=1400233) that removed the LEGACY_ELEMENT_ID_KEY of "ELEMENT" and added a new id key for chrome elements.  Since that [geckodriver hasn't been updated](https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver/src/marionette.rs#l655) at the time of writing, the error will be from geckodriver if you try the code above.  But, looking at [the code](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L1720), a corresponding change appear to be necessary in selenium-webdriver as well.

**Comment by barancev** [comment]
It's not actual anymore because all drivers use W3C WebDriver protocol these days.
