### ISSUE TITLE
${KEY_ENTER} or any ${KEY_***} doesn't work with html-runner

### ISSUE THREAD

**Issue by Jordannoel** [SeleniumHQ/selenium#5736]
## Meta -
OS:  Windows 10
Html-runner version:  3.10.0
Browser:  Firefox and Chrome
Gecko Driver : 0.20.0
Chrome Driver : 2.37

Browser Version:  Firefox 54.1, Chrome 65.0.3325.181

## Expected Behavior - 
When I run the command `sendKeys id=myId ${KEY_ENTER}`, I want it to simulate the behavior of someone pressing enter.

## Actual Behavior - 
Instead, it fills my text box with null. Every other ${KEY_***} also fill my text box with null.
For example, if I write this :

```
<tr>
	<td>sendKeys</td>
	<td>id=myId</td>
	<td>test</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=myId</td>
	<td>${KEY_ENTER}</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=myId</td>
	<td>${KEY_BKSP}</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=myId</td>
	<td>${KEY_LEFT}</td>
</tr>
<tr>
	<td>sendKeys</td>
	<td>id=myId</td>
	<td>${something}</td>
</tr>
```
It will fill my textbox with : testnullnullnullnull
Is it a syntax problem, do I have a bad html-runner version, or a bad chrome/gecko driver ?

**Comment by Jordannoel** [comment]
The only way I found is to use the deprecated command keyPress, taking as a first parameter the id of the element and as second parameter the value of the key in ascii.
For example :
```
<tr>
	<td>keyPress</td>
	<td>id=s2id_autogen1_search</td>
	<td>\13</td>
</tr>
```

Will press enter on my s2id_autogen1_search input.

**Comment by ldthieu** [comment]
Tks for a great tools, It is very helpful to me! 
But I have a similar issue with Selenium IDE plugin for Chrome.
Chrome version: 65.0.3325.181
Selenium IDE version: 3.0.1

![issuse](https://user-images.githubusercontent.com/33156507/38776800-333d3e28-40c7-11e8-9fae-19247ce51f3f.png)

i record a test case for sign in google account by Selenium IDE . When i run test case, Selenium IDE said me that "Trying to execute sendKeys on id=identifierId with value ${KEY_ENTER}... Success" but it is not executed in browser

**Comment by barancev** [comment]
Legacy Selenium IDE is deprecated. See https://github.com/SeleniumHQ/selenium-ide for the new version
