### ISSUE TITLE
selenium 3.11 - JAVA (Multi-threading),Multiple browsers launch attempted Exceptions Observed

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#5740]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.11 
Browser:  
 Internet Explorer,  Firefox, Opera, Chrome 

Browser Version:  

## Expected Behavior -
The program should launch all the browsers, open websites and perform operations intended.
## Actual Behavior -
The program behaves inconsistently during opening of browsers, sometimes throwing errors and failing to launch browsers.
Error log can be found below (for one sample run):
Apr 09, 2018 12:09:21 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Test for the browser IE failed for website youtube
Exceptionorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver
Test for the browser chrome failed for website google
Exceptionorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver
Test for the browser Internet Explorer failed for website google
Test for the browser Opera failed for website google
Exception observedorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: googleOperaDriver
Exceptionorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: ChromeDriver
Test for the browser Firefox failed for website google
Exceptionorg.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:23410
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: FirefoxDriver

## Steps to reproduce -

Launch separate thread for each browser operations as shown below:

Thread googleOpera = new Thread (new googleOperaDriver(),"GoogleOperaThread");
		googleOpera.start();
		Thread googleFirefox = new Thread (new googleFirefox(),"GoogleFirefoxThread");
		googleFirefox.start();
		Thread googleIE = new Thread (new googleInternetExplorer(),"GoogleIEThread");
		googleIE.start();
		Thread googleChrome = new Thread (new googleChrome(),"GoogleChromeThread");
		googleChrome.start();
		Thread youtubeIE= new Thread(new youtubeIE(),"YoutubeThread");
		youtubeIE.start();

**Comment by cgoldberg** [comment]
@SudeeptMohan  you didn't call any selenium code in your repro example

**Comment by diemol** [comment]
@SudeeptMohan 
Please provide a complete reproducible case, so far those are only snippets from your code. It is much more helpful when a complete test case is provided and we just need to execute it to reproduce the issue you mention.

**Comment by diemol** [comment]
Sorry, but how can I execute a "docx" file? I think it would be easier if you provide a link with a GitHub project where it is more simple to see what is going on.

**Comment by SudeeptMohan** [comment]
@diemol  i am not sure about how to provide a link with GitHub project, could you please provide steps to do so?
On my machine i am running the code via eclipse ...

**Comment by SudeeptMohan** [comment]
On a recent run for this program, the program ran successfully without any errors.Would conduct another run in the morning to see how program behaves.

**Comment by SudeeptMohan** [comment]
Inconsistent behavior of the program in the latest run on my machine, browsers launched successfully - chrome, mozilla.
Error thrown for launch of  IE, opera given below:

Exceptionorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver
Test for the browser Internet Explorer failed for website google
Exception observedorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: googleOperaDriver
Test for the browser IE failed for website youtube
Exceptionorg.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'ADMIN-PC', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: InternetExplorerDriver

**Comment by SudeeptMohan** [comment]
Let me try to re-state the problem.

The program is intended to launch a separate thread for each browser opening a specific website.
When a single thread is run(with rest of the code for other threads commented out), the website opens without throwing any error, however it is when all the threads are invoked in a single program run ,the program throws error (time-out error to be specific).

Sample Program (Please copy following files in eclipse and execute the program)

File 1
package samplePrograms;

public class browserAutomation1 {

	public static void main(String[] args) {
		Thread googleOpera = new Thread (new GoogleOpera(),"GoogleOperaThread");
		googleOpera.start();
                Thread googleFirefox = new Thread (new GoogleFirefox(),"GoogleFirefoxThread");
		googleFirefox.start();
		Thread googleIE = new Thread (new GoogleIe(),"GoogleIEThread");
		googleIE.start();
		Thread googleChrome = new Thread (new GoogleChrome(),"GoogleChromeThread");
		googleChrome.start();
		//Thread youtubeIE= new Thread(new youtubeIE(),"YoutubeThread");
		//youtubeIE.start();


	}

}

File 2
package samplePrograms;

import java.io.File;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.opera.OperaDriver;
import org.openqa.selenium.opera.OperaOptions;

public class GoogleOpera extends browserAutomation1 implements Runnable {

	public void run(){
		System.setProperty("webdriver.opera.driver", "C:\\Marionette\\operadriver_win32\\operadriver.exe");
		OperaOptions options = new OperaOptions();
		options.setBinary (new File("C:\\Program Files\\Opera\\51.0.2830.55\\opera.exe"));

		try {
		WebDriver driver = new OperaDriver(options);
		driver.get("https://www.google.com");
		}
		catch (Exception e){
			System.out.println(e);
		}
		}
	
}


File 3
package samplePrograms;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GoogleChrome extends browserAutomation1 implements Runnable {

	
	public void run(){
		System.setProperty ("webdriver.chrome.driver","C:\\Marionette\\chromedriver_win32_New\\chromedriver.exe") ;

	try {
	WebDriver driver = new ChromeDriver();
	driver.get("https://www.google.com");
	}
	catch (Exception e) {
		System.out.println(e);
	}
	}

	
}


File 4

package samplePrograms;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;

public class GoogleFirefox extends browserAutomation1 implements Runnable{

	public void run(){
		System.setProperty("webdriver.gecko.driver","C:\\Marionette\\geckodriver.exe" );
		try {
		FirefoxOptions options = new FirefoxOptions();
				options.setLogLevel(FirefoxDriverLogLevel.DEBUG);
				WebDriver driver = new FirefoxDriver(options);
		driver.get("https://www.google.com");
		}
		catch (Exception e) {System.out.println();
		}

	}	
}


File 5
package samplePrograms;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class GoogleIe extends browserAutomation1 implements Runnable {
	public void run(){
		DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
				capabilities.setCapability(CapabilityType.BROWSER_NAME, "IE");
				capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
				capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
				System.setProperty("webdriver.ie.driver", "C:\\Marionette\\IEDriverServer_Win32_3.9.0\\IEDriverServer.exe");
				
		try {
		WebDriver driver = new InternetExplorerDriver();
		driver.get("https://www.google.com");
		}
		catch (Exception e) {System.out.println(e);
		}

}
}

Hope this helps to understand the program output and the error.

**Comment by diemol** [comment]
@SudeeptMohan after reading the whole issue again, I understand that the written code sometimes works and sometimes does not. I also see in a previous comment that if you execute things sequentially, it works.

Which it just means that it is an issue with the way Threads are being handled. Threads are very tricky and can lead to inconsistent behaviours if they are not used properly (i.e. checking that the code is thread safe). I am not an expert in Threads, therefore I use them as little as possible, and I cannot advise how to proceed, but for me this looks clearly that is not a Selenium related issue.

**Comment by SudeeptMohan** [comment]
Yes, you seem right.I have posted this question under another forum.Closing it here.
