### ISSUE TITLE
Command Line problem on running java -jar command for selenium 3.11

### ISSUE THREAD

**Issue by SudeeptMohan** [SeleniumHQ/selenium#5742]
## Meta -
OS:  
 Windows 10
Selenium Version:  
3.11

## Expected Behavior -
command should run successfully

## Actual Behavior -
C:\Users\admin\Desktop\selenium-java-3.11.0>java -jar client-combined-3.11.0.jar
no main manifest attribute, in client-combined-3.11.0.jar

## Steps to reproduce -
1.Download latest version of selenium client from official website.
2.unzip the downloaded folder and try running the command java -jar client-combined-3.11.0.jar

**Comment by SudeeptMohan** [comment]
Link to download selenium client - https://docs.seleniumhq.org/download/
Download for language JAVA, Client 3.11.0

**Comment by barancev** [comment]
Selenium client is not runnable, it's jus a library. You must be wanted to download and run Selenium Standalone Server.
