### ISSUE TITLE
Selenium test cases are failing with org.openqa.selenium.TimeoutException: from Jenkins

### ISSUE THREAD

**Issue by Manigunner** [SeleniumHQ/selenium#5744]
## Meta -
OS:  
Windows 7
Selenium Version:  
2.53.0

Browser:  
Google CHrome

Browser Version:  
65

## Expected Behavior -
Test Suites should be executed successfully

## Actual Behavior -
It is faliling with Timedout exception for all the functions

## Steps to reproduce -
Code Sample:
WebDriverWait wait = new WebDriverWait(driver, 1000);
wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(ORCollection.get("BtnMDUEligibilityClick").toString())));
WebElement el = driver.findElement(By.xpath(ORCollection.get("BtnMDUEligibilityClick").toString()));
((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", el);
WebElementClick(" ",ORCollection.get("BtnMDUEligibilityClick").toString());
Thread.sleep(10000);

Error log:
org.openqa.selenium.TimeoutException: Timed out after 40 seconds waiting for visibility of element located by By.xpath: //button[contains(@class,'js-submit')]

I have increased webdriver.wait value in code from 40 seconds to 1000 but still we are getting the same error as Timedout

But while executing the same code via eclipse its running fine. Please help on resolving the issue

TIA

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by firozautomation** [comment]
Even I am also getting the same error when driver.quit() method is used.
I am using Firefox ESR 38 version of firefox, and Selenium 3.9.0, TestNG 6.10, OS Win 8.1
I have written the code to call RestAPI and then to Verify the same in the UI and then in AfterMethod of TestNG, i have written driver.quit() method.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario.
