### ISSUE TITLE
Its possible record  TV shows with selenium

### ISSUE THREAD

**Issue by bn0785ac** [SeleniumHQ/selenium#5745]
If you know a TV streaming site (without captcha)

can i use selenium for record it (just  click at play button, record it during a planned time *240 minutes* no more)

**Comment by p0deje** [comment]
Selenium is browser automation tool, not screen recording tool. You should probably look into screencast recording tools.

In any event, this is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
