### ISSUE TITLE
Non-w3c capabilities never applied?

### ISSUE THREAD

**Issue by timdrew** [SeleniumHQ/selenium#5746]
First time user, apologies if I've missed something or this is by design but it appears that non-w3c capabilities have no effect.

If webdriver [always modifies the parameters ](https://github.com/SeleniumHQ/selenium/blob/259f539c03ac4c03c19172f67f6a94dc99d7a10d/py/selenium/webdriver/remote/webdriver.py#L243)to the below structure, with non-w3c capabilities only appearing in "desiredCapabilities":
```
        parameters = {"capabilities": w3c_caps,
                      "desiredCapabilities": capabilities}
```
Then subsequently NewSessionCommandHandler [determines capability processing based on the existence of the "capabilities" object](https://github.com/SeleniumHQ/selenium/blob/74e584d12ba31bb2e1b61b17a4751402c70c6da6/cpp/iedriver/CommandHandlers/NewSessionCommandHandler.cpp#L44-L70), which is always present:  
```
  ParametersMap::const_iterator it = command_parameters.find("capabilities");
  if (it != command_parameters.end()) {
    LOG(DEBUG) << "Found W3C capabilities structure";
    Json::Value validated_capabilities = this->ValidateArguments(it->second, &error_message);
    ...
  } else {
    // W3C capabilities not found. Try legacy capabilities.
    // Note that we ignore requiredCapabilities. This is by design.
    it = command_parameters.find("desiredCapabilities");
    if (it != command_parameters.end()) {
      returned_capabilities = this->ProcessLegacyCapabilities(executor, it->second, &error_message);
   ...
  }
```
It looks like desiredCapabilities are never used. If I perform a quick hack to webdriver to remove the w3c filtered "capabilities" then all of a sudden my non-w3c capabilities start taking effect.
```
        parameters = {"desiredCapabilities": capabilities}
```

## Meta -
OS:  
Windows 7 
Selenium Version:  
IEDriverServer 3.9, Python bindings 3.11
Browser:  
IE11

## Expected Behavior -
Set non-w3c capability, observe its effect
## Actual Behavior -
Set non-w3c capability, observe no effect
## Steps to reproduce -
```
capabilities = {}
capabilities['ignoreProtectedModeSettings'] = True
driver = webdriver.Ie(capabilities=capabilities)
```

> selenium.common.exceptions.SessionNotCreatedException: Message: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

**Comment by timdrew** [comment]
May be related to other issues e.g. https://github.com/SeleniumHQ/selenium/issues/5531

**Comment by jimevans** [comment]
You should fix your code for IE to use the W3C-compliant capabilities structure. The ability of the IE driver to understand the `desiredCapabilities` property will be removed soon. You can achieve what you want by sending the following payload:

    {
      “capabilities”: {
        “firstMatch”: [ {
          “browserName”: “internet explorer”,
          “se:ieOptions”: {
            “ignoreProtectedModeSettings”: true
          }
        } ]
      }
    }

Most language bindings (Python included, I think), have an `InternetExplorerOptions` class or equivalent, which is designed to create the correctly formatted payload without you having to manually set properties. That is the preferred mechanism for setting capabilities, especially using the local driver executables like `IEDriverServer.exe`.

**Comment by timdrew** [comment]
Works nicely, thanks for the prompt response guys.
