### ISSUE TITLE
A unexpected TypeError in driver.wait(until.elementLocated(By.id('elementid')), timeout)

### ISSUE THREAD

**Issue by kxc1573** [SeleniumHQ/selenium#5749]
## Meta -
OS:                               Windows 10
Selenium Version:        4.0.0-alpha.1
Browser:                       Internet Explorer
Browser Version:          IE11

## Actual Behavior -
I used seleium in IE11 to do some work， just like the example:
``` 
async function example() {
     let button =
       await driver.wait(until.elementLocated(By.id('foo')), 10000);
   await button.click();
 }
````
and got an unexpected break with the code：
```
let isLoggedIn = await driver.wait(until.elementLocated(By.id('bottomNav'));, 10*1000);
```
the exception info is:
```
 TypeError: Wait condition must be a promise-like object, function, or a Condition object
```

I wanted to  know why, so I got some log and debug inspect , found that: 
    - the result of `until.elementLocated(By.id('bottomNav')`  is  a instance of `WebDriver.WebElementCondition`
    - but in `driver.wait()`, the result be judged 'false'
    - and then, I get the TypeError.

I can show threr screenshots
code:
![code](https://user-images.githubusercontent.com/14289035/38540739-7a574bb0-3ccf-11e8-904e-099b29a4c7a5.png)
console:
![console](https://user-images.githubusercontent.com/14289035/38540812-becf3596-3ccf-11e8-81a8-a34139d40985.png)
use `node  --inspect-brk xxx.js`  to  inspect
![error_in_driver_wait](https://user-images.githubusercontent.com/14289035/38540828-c83cdd18-3ccf-11e8-8f9d-fa714ade2ac3.png)

**Comment by ian-craig** [comment]
I was having the same issue, but looks like this caused by #5560 .

**Comment by smartamus** [comment]
Also having this issue, but working fine locally, just a problem when uploaded to an aws lambda function.

**Comment by diemol** [comment]
The change done by #5560 was reverted a while ago but it was only released a few months ago. Please check again with `beta-2` and if the issue still persists, please open a new one or comment here.

**Comment by clmay** [comment]
We are still having the same issue despite having upgraded to `selenium-webdriver@^4.0.0-beta.2`. We are using a custom Jest environment that extends `NodeEnvironment`. This is how we are setting it up so far:

```
// page-class.ts
import {By, WebDriver, until} from 'selenium-webdriver'

export class MyPage {
  constructor(driver: WebDriver) {
    this.driver = driver
  }
  ...

  login = async () => {
    await this.driver.wait(until.elementLocated(By.xpath('some-xpath')))
  }
  ...
}
```

```
// my-test.test.ts
describe('test suite', () => {
  let driver: WebDriver

  beforeAll(async () => {
    driver = global.driver
  })  

  it('...', () => {
    const page = new MyPage(driver)
    await page.login()
    ...
  }
  ...
}
```

We're still getting

```
TypeError: Wait condition must be a promise-like object, function, or a Condition object
```

It seems to work if we don't use the custom Jest environment, and just instantiate the driver locally.
