### ISSUE TITLE
Marking .NET PageFactory obsolete - only PageFactory class was marked

### ISSUE THREAD

**Issue by LirazShay** [SeleniumHQ/selenium#5752]
Since the decision to remove the PageFactory support from the C# bindings explained [here](http://jimevansmusic.blogspot.co.il/2018/03/deprecating-parts-of-seleniums-net.html) need to mark many classes as obsolete, that the users will know about it and make their preparations/considerations for the removal.  
Currently, only PageFactory class was marked as Obsolete, but many users still don't aware of this change.   
All the classes inside the OpenQA.Selenium.Support.PageObjects namespace should also have that attribute since they will also be removed. 
For example:  

- ByAll.cs
- ByChained.cs
- ByFactory.cs
- ByIdOrName.cs
- CacheLookupAttribute.cs
- DefaultElementLocator.cs
- DefaultPageObjectMemberDecorator.cs
- FindsByAllAttribute.cs
- **FindsByAttribute.cs**
- FindsBySequenceAttribute.cs
- **How.cs**
- IElementLocator.cs
- IPageObjectMemberDecorator.cs
- **PageFactory.cs**
- RetryingElementLocator.cs
- WebDriverObjectProxy.cs
- WebElementListProxy.cs
- WebElementProxy.cs

_Bold are the most commonly used classes_

See: https://github.com/SeleniumHQ/selenium/tree/master/dotnet/src/support/PageObjects

**Comment by jimevans** [comment]
Except that not all of those classes need to be removed. The `By` extensions, for example, are perfectly legitimate to use outside of the context of the `PageFactory`. Outside of those, is there any user using the supporting classes (`FindsByAttribute`, `DefaultElementLocator`, etc.), **without** also using `PageFactory` (in which case, they correctly receive the deprecation warning)? Absent hard data to the contrary, I’m not inclined to make changes to code that’s to be removed.

**Comment by LirazShay** [comment]
@jimevans 
Most of the users do not aware of this change.
I've marke 3 classes:
FindsByAttribute.cs
How.cs
and PageFactory
FindsBy attribute and most of those classes will not be relevant without the PageFactory.
I do not understant which classes will do be relevant.
That's why all those classes were moved to [DotNetSeleniumExtras](https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras/tree/master/src/PageObjects)
@jimevans 
Did you find a new owner for this new repo?

**Comment by jimevans** [comment]
@LirazShay No, a new repository owner has not been found. And again, none of the classes you have mentioned are of any use without somewhere using the `PageFactory` class, in which case, a deprecation warning will be displayed. Do you have specific instances where someone is using `How` or `FindsByAttribute` but is **not** using `PageFactory`?

**Comment by LirazShay** [comment]
@jimevans 
Thanks for the replay, I really appriciate your work and your big contribution to the community.
About this issue, I agree with you but I still think it will be dishonest to mark only 1 class as obsolete and then in the next release remove 18 classes at once. I think each class that should be removed should have this attribute before.
About the new repo, if you want I will be happy to take care of it. I also have an idea of to implement the PageFactory without need to use the Proxy object, so it should also work in  .NET 2. Can we discuss about it by email or some other private way?

**Comment by jimevans** [comment]
I’m sure you didn’t mean it this way, but your use of the word “dishonest” is concerning. It seems like you’re calling my integrity, which I highly value, into question. The plan was never to remove the classes after a single release of being marked deprecated. The most important thing is that users are notified that `PageFactory` is going away from the core Selenium repo eventually, and marking that class accomplishes that. Selenium users are smart enough be given the benefit of the doubt to know that means the supporting classes will be removed too.

I’m happy to discuss the issue and the ownership of the new repo further via the Selenium IRC channel. I’m only sporadically available for the next 24 hours from the time of this post, but I’m online there most weekdays, usually during US east coast business hours.

**Comment by LirazShay** [comment]
@jimevans
I'm really sorry, and of course, I didn't mean that at all. As I wrote, I really appriciate your contribution and commitment and integrity. Just I thought that some users will not be aware that the FindsBy will not work. maybe they think there will be a different class to use instead. but I've convinced now. Closing this issue. thanks again. I'll implement an example of PageFactory without proxy and we'll talk.

**Comment by Dreamescaper** [comment]
@jimevans 
Problem with missing Obsolete attribute on FindsByAttribute is the following. 
Currently FindsByAttribute is present in both Selenium.Support and DotNetSeleniumExtras.

If we use DotNetSeleniumExtras' PageFactory, but still use Selenium.Support's FindsBy (accidentally, since both are available), we'll get no warnings, but the page won't work.

Thanks, and have a nice day!

**Comment by apis3445** [comment]
Why do you decide doesn't continue with pageFactory? if you doesn't continue now I have to change a lot of code and in the new projects add more code for get the elements

**Comment by jimevans** [comment]
@apis3445 As explained in the initial report on this very issue, the reasons for the deprecation are [here](http://jimevansmusic.blogspot.com/2018/03/deprecating-parts-of-seleniums-net.html). As has been said both in other comments in this issue and other places publicly, you can use the code in the [DotNetSeleniumExtras repository](https://github.com/DotNetSeleniumTools/DotNetSeleniumExtras) (and the accompanying NuGet packages).
