### ISSUE TITLE
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4750 as down: cannot reach the node for 2 tries 

### ISSUE THREAD

**Issue by stephenws** [SeleniumHQ/selenium#5753]
The problem
I am using selenium-server-standalone-3.11.0/3.7.1 for connecting nodes to Hub. After connecting node to hub I am getting below error:

INFO [DefaultGridRegistry.add] - Registered a node http://0.0.0.0:4750
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4751 as down: cannot reach the node for 2 tries
INFO [DefaultRemoteProxy.onEvent] - Marking the node http://0.0.0.0:4750 as down: cannot reach the node for 2 tries

On hub console it shows that devices are connected as given in attached screenshot.

![image](https://user-images.githubusercontent.com/26320996/38560880-4b98f3ee-3cf4-11e8-8ae8-722483b1ca8f.png)

https://gist.github.com/stephenws/fe5ec8fce5dc69dba80cf8f4ba47a49c

**Comment by barancev** [comment]
This is a network configuration issue, make node hosts available from the hub host.
