### ISSUE TITLE
Browser is displayed as null in the Grid console

### ISSUE THREAD

**Issue by bsriram99** [SeleniumHQ/selenium#5756]
Hello-
After I set up the hub(macos) and node(win 10 vm), I ran below in the command prompt of the node
java -Dwebdriver.geckodriver.driver=geckodriver.exe -jar selenium-server-standalone-3.11.0.jar -role webdriver -hub http://10.247.240.20:4444/grid/register -browser browsername=firefox -port 5566

I do see some warnings as below:

![image](https://user-images.githubusercontent.com/34170648/38573751-df6c73aa-3cab-11e8-8e1f-57aa7755ac32.png)

After refreshing the grid console, browser is null
![image](https://user-images.githubusercontent.com/34170648/38573804-fea25c3a-3cab-11e8-9b47-4216016fa229.png)

If anyone has any suggestions for me on how to fix this, please let me know. Thanks in advance!

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by dylanlive** [comment]
@bsriram99 Hi there. I noticed two issues in the command you provided:

1) You provided `-role webdriver` when should be `-role node`
2) You provided `-browser browsername=firefox` when it should be `-browser browserName=firefox` (notice the casing of browserName)

With the above, I would give this a try:
```
java -Dwebdriver.geckodriver.driver=geckodriver.exe -jar selenium-server-standalone-3.11.0.jar -role node -hub http://10.247.240.20:4444/grid/register -browser browserName=firefox -port 5566
```

Additional documentation and examples can be found here:
https://github.com/SeleniumHQ/selenium/wiki/Grid2

P.S., I would recommend utilizing a nodeConfig file, as described here:
https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json

**Comment by barancev** [comment]
Yes, the root cause is misspelled `browserName` property.
