### ISSUE TITLE
Should use HTTP keep alive to avoid port exhaustion

### ISSUE THREAD

**Issue by awarecan** [SeleniumHQ/selenium#5758]
## Meta -
OS:  Windows 7, 10
Selenium Version:  3.8.1
Browser:  Chrome
Browser Version:  65.0.3325.181 (64-bit)
Node.js: 8.11.1

## Expected Behavior -
During the test, TCP connection should be reused

## Actual Behavior -
Each WebDriver command will create a new TCP connection to ChromeDriver

## Steps to reproduce -
```JavaScript
await browser.get('https://www.google.com/');
for (let i=0; i<50000; i++) {
  await browser.getCurrentUrl();
}
```
use `netstat -na` to monitor the number of TCP connection in TIME_WAIT state while you are running above code. You will see massive amount of TCP connections. If you are using a powerful box and has default Windows TCP/IP configuration, you will hit ephemeral port exhaustion very soon.

## Note -
This was [a well known issue related with ChromeDriver](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2183). However ChromeDriver has [a dirty fix](https://chromium.googlesource.com/chromium/src/+/736efbc1c284f9b85d7dcda22771e23786def5d5%5E%21/#F0) in 2.35 release. It requires client set `Connection: keep-alive` HTTP header, see the discussion in #4162 and #3457

Now, we finally have chance to resolve this issue in selenium-webdriver side by passing in an Agent with keepAlive option while creating HttpClient in createExecutor() function.

**Comment by p0deje** [comment]
Seems like we need to do this for all the bindings.

**Comment by barancev** [comment]
In Java I can't reproduce this issue with chromedriver, but the number of TIME_WAIT'ing ports grows if I use geckodriver.

**Comment by dmytro-verner** [comment]
@barancev  possibly you have registry's HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters (in case of Windows) TcpTimedWaitDelay set to non-default value(which is 240 secs). 

Setting this value to a lower bound(e.g. 30 secs) can help to circumvent the current issue.

**Comment by barancev** [comment]
It appears that OkHttp uses keep-alive by default, so it's not an issue with Java binding.

**Comment by p0deje** [comment]
Since there is no straightforward way to use keep-alive connections in standard Ruby library, I think we'll just stick to existing solution described in [wiki](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings/_edit#using-persistent-http-connections). One needs to install `net-http-persistent` gem and use `Persistent` HTTP client. We might consider making it a runtime dependency and use by default, but that's subject for discussion.

**Comment by ariasuni** [comment]
Are there any known workaround for the Python bindings?

**Comment by lmtierney** [comment]
@ariasuni you can currently set `keep_alive` on a `Remote` webdriver instance. Currently it's not in the individual drivers, but you could always start up the driver binary yourself and use `Remote` to connect to it as a workaround. Which drivers do we know support keep alive? We can add it to those xtors.

https://github.com/SeleniumHQ/selenium/blob/2c2db8a47b72b1e9d1c380b4e8664de1b13ebada/py/selenium/webdriver/remote/webdriver.py#L127

**Comment by ariasuni** [comment]
Unfortunately, your solution is more a refactoring, and it would require me to modify a ton of production code which I can’t do.

[It worked perfectly fine for me with 2.53.* but not any 3.*](https://github.com/SeleniumHQ/selenium/issues/3772#issuecomment-391286366), thus I can’t upgrade and use recent versions of Firefox or Chromium.

**Comment by ariasuni** [comment]
Well, I have this problem with PhantomJS but I guess that it won’t be resolved if it’s specific to this webdriver.

**Comment by secondcircle** [comment]
Anyone know if there is a fix for chromedriver with C#? I'm running into this same port exhaustion issue only with chromedriver.

**Comment by awarecan** [comment]
@secondcircle Could you double check your chromeDriver version? The keep-live feature is only available on 2.35 and after. 

From the code I read, `RemoteDriver` should support keep-alive by default, and `ChromeDriver` just a simple extension of `RemoteDriver`
https://github.com/SeleniumHQ/selenium/blob/894b67a1c9c288e8ac6cf247fdbd03f92c9e0b24/dotnet/src/webdriver/Remote/DriverServiceCommandExecutor.cs#L37

**Comment by barancev** [comment]
@awarecan I've expanded the issue from python to other bindings too. At the same time I've removed "browser"-label because we only can fix client bindings. But this will have effect only for the drivers that provide support for keep-alive. It seems that chromedriver supports it, so we can use this driver to test client bindings.

If python binding has implemented keep-alive support we can remove this label from this issue, but I want to get a confirmation from the python part of the team. The same for C#.

**Comment by awarecan** [comment]
@secondcircle I realized the dotNet binding issue now. I actually point to the right issue in the beginning of this thread, please check #4162 that is about dotNet binding and chromeDriver 2.35

@barancev I don't have time to check what happens in python and C# language binding, I bet #4162 points to the root cause, the chromeDriver 2.35's implementation may have issue with the HTTP 1.1 client, have to set `Connection: keep-alive` header explicitly to make it works

**Comment by awarecan** [comment]
To whom may have interesting, mozilla/geckodriver#713 is the discussion in geckodriver project

**Comment by lmtierney** [comment]
As stated, `keep_alive` is already used for Chrome in python, removing label.
