### ISSUE TITLE
WebTest method for link 

### ISSUE THREAD

**Issue by amit1984** [SeleniumHQ/selenium#576]
public static readonly string[] LinkLocators = new String[] {
 "xpath=//a[@title='{0}']",
   "xpath=//a[@href='{0}']"

    };

 public void UserClicksLink(String LinkCaption)
            {
                instance.Click(GetLocator(LinkCaption, LinkLocators));
            }

**Comment by amit1984** [comment]
This method can be added to webtest for link

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
