### ISSUE TITLE
As a side-effect of CLI refactoring, Grid server configs no longer retain config file paths

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/selenium#5760]
## Meta -
OS:  
all  
  
Selenium Version:  
3.11.0  
  
Browser:  
all  
  
Browser Version:  
N/A  

## Expected Behavior -
If a Grid server configuration object  is populated via JSON config file, the path of the config file should be retailed in the configuration object.
## Actual Behavior -
The field in the configuration object that should contain the config file path is 'null'.
## Steps to reproduce -
GridHubConfiguration hubConfig = GridHubConfiguration.loadFromJSON(getHubConfigPath());
System.out.println(hubConfig.hubConfig);
// expect: C:\Users\sbabcoc\hubConfig.json
// actual: null

**Comment by sbabcoc** [comment]
Submitted PR 5710 with proposed fix: https://github.com/SeleniumHQ/selenium/pull/5710

**Comment by barancev** [comment]
PR merged. Thank you!
