### ISSUE TITLE
Grid is not working properly if no of classes greater than one in test tag

### ISSUE THREAD

**Issue by Edzotech** [SeleniumHQ/selenium#5764]
## Meta -
OS:  Windows 7

Selenium Version:  3.5.3, Selenium Standalone server 3.11.0

Browser:  Firefox, Chrome

Browser Version:  
 Firefox 59,Chrome 65
## Expected Behavior -
Scripts should execute parallel in the grid
## Actual Behavior -
Grid is NOT working. Issue is grid is launching 4 chrome, and 1 fire fox instances and not executing anything. They just launched and stay idle. 

## Steps to reproduce -

i have launched hub with following command
java -jar selenium-server-standalone-3.11.0.jar -role hub

i have launched node with following command
java -Dwebdriver.gecko.driver=i:/Selenium/geckodriver-v0.20.0-win64/geckodriver.exe -Dwebdriver.chrome.driver=i:/Selenium/chromedriver_win32/chromedriver.exe -jar selenium-server-standalone-3.11.0.jar -role node -hub http://localhost:4444/grid/register

I have the following code in six classes named GridExample_Seek1 to GridExample_Seek6

```
package GridExample;
import java.net.URL;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class GridExample_Seek1 {

    WebDriver driver;

    @BeforeTest
    @Parameters("browser")
    public void setup(String browser) throws Exception{
       
        if(browser.equalsIgnoreCase("firefox")){
            System.setProperty("webdriver.gecko.driver", "I:/Selenium/geckodriver-v0.20.0-win64/geckodriver.exe");
            DesiredCapabilities capabilities = DesiredCapabilities.firefox();
            capabilities.setPlatform(org.openqa.selenium.Platform.WINDOWS);
            driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
           
        }

        else if(browser.equalsIgnoreCase("chrome")){
            System.setProperty("webdriver.chrome.driver","I:/Selenium/chromedriver_win32_appium/chromedriver.exe");
            DesiredCapabilities capabilities = DesiredCapabilities.chrome();
            capabilities.setPlatform(org.openqa.selenium.Platform.WINDOWS);
            driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capabilities);
           
        }


    }

    @Test
    public void CrossBrowserTesting() throws InterruptedException{


        By TextJobName=By.id("SearchBar__Keywords");
        By TextLocationName=By.id("SearchBar__Where");

        By LinkInformationTechnology=By.xpath("//*[@id='classificationsPanel']/nav/ul/li[18]/a");
        By LinkLocationSydney=By.xpath("//*[@id='react-autowhatever-1-section-0-item-0']/span");
        By LinkLocationMelbourne=By.xpath("//*[@id='eact-autowhatever-1-section-0-item-0']/span");

        By ButtonSeek=By.xpath("//*[@id='SearchBar']/button");

        By LabelClassification=By.cssSelector("._2jxxdU_._2VxM8lk");

        driver.get("http://seek.com.au");
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.findElement(TextJobName).sendKeys("Selenium webdriver");
        Thread.sleep(1000);
        driver.findElement(LabelClassification).click();
        Thread.sleep(1000);
        driver.findElement(LinkInformationTechnology).click();
    }

    @AfterMethod
    public void teardown() throws InterruptedException{
         driver.quit();
    }
}
```

I observed below points while working with grid.

1.When i mentioned only 1 classe(GridExample_Seek1) under each test tag in xml file, grid is working fine. scripts are running in parallel.

2.When i mentioned only 3 classes(GridExample_Seek1,GridExample_Seek2,GridExample_Seek3) under each test tag in xml file, grid is working. BUT tests are executing one by one, not in parallel.

3.If i mentioned 6 classes(GridExample_Seek1 to GridExample_Seek6) under each test tag in xml file, grid is NOT working. issue is grid is launching 4 chrome, and 1 fire fox instances and not executing anything. They just launched and stay idle. 

Please see the snapshots for grid and testng.xml file

![grid 1](https://user-images.githubusercontent.com/30716119/38628265-9941f516-3dce-11e8-94ac-4ac779d77bc9.png)
![grid 2](https://user-images.githubusercontent.com/30716119/38628267-9aac7426-3dce-11e8-8f5f-808d630efd86.png)
![grid 3](https://user-images.githubusercontent.com/30716119/38628282-a15dfcd6-3dce-11e8-9e25-9498c6cd532c.png)
![testng xml](https://user-images.githubusercontent.com/30716119/38628300-a900aa9c-3dce-11e8-819d-1908f799ac41.png)

**Comment by diemol** [comment]
Apologies for the late reply, but this all looks as an issue of TestNG configuration and not Grid.
To be sure of that, could you please share more information? Logs from test execution and Grid can help.

**Comment by diemol** [comment]
Closing as no more info was provided.
