### ISSUE TITLE
 captial letter in middle of the name then it takes it as method 

### ISSUE THREAD

**Issue by amit1984** [SeleniumHQ/selenium#577]
public void UserTypesIntoField(String what, String where)
            {
                where  = where.Replace("'", "");
                instance.Type(GetLocator(
                where.Replace(" ", ""), textFieldLocators), what);
            }

---------------------------------------------------------------------------------------

If the textbox ID have a captial letter in middle of the name then it takes it as method so we can replace this using this replace string to solve the problem

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
