### ISSUE TITLE
Chrome Driver 2.36 Login issue thread is waiting at Driver.URL C#

### ISSUE THREAD

**Issue by PraveenKushwahaa** [SeleniumHQ/selenium#5771]
## Meta -
OS:  Windows 10, Server 2012
Browser: Chrome 
Version: 65.0.3325.181 (Official Build) (64-bit)  
Web driver: 2.36
Dotnet Framework: 4.6

## Expected Behavior -
In my application I'm using window AD for authentication. Whenever I open application in chrome browser it ask for authentication and a login pop-up window(attached screenshot) gets open. In the pop-up window, I enter my credential and click on login button. Once successfully logged-in I'm able access my application. Expecting same behavior in automation. 

## Actual Behavior -
Same thing i have automated with the help of selenium driver. I had used selenium web driver 2.34 for Chrome and Chrome version was 64, with this combination login functionality was working fine. Now recently I have upgraded web driver to 2.36 and Chrome to 65, post this upgrade login functionality is not working. Now in application when login pop-up window opens and application wait for user inputs
i'm using auto hot key "WindowsAuthenticationChrome" to enter the credentials, now application gets hang at driver.url="some url" thread gets blocked and unable to launch auto hotkey and after some time it throw command timeout exception. and when i manually enter credentials or close the popup thread get released and execute next line of code.

**This issue is coming after version upgrade**.

## Steps to reproduce -
Created sample console application

```
class Program
	{
		static void Main(string[] args)
		{
			string[] arguments = new string[] { "no-sandbox", "test-type", "ignore-certificate-errors", "disable-popup-blocking" } ;
			var chromeOptions = new ChromeOptions() { BinaryLocation = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" };
			chromeOptions.AddArguments(arguments);
			var chromedriver = new ChromeDriver(@"C:\TestCases\Drivers", chromeOptions, new System.TimeSpan(0, 10, 0));
			//chromedriver.Url = "actual url" login pop-up window come;
			chromedriver.Url = "https://www.google.co.in/";
		}
	}
```
In sample code i'm creating object of web driver with some capabilities, when i'm trying to open my application url where login pop-up window come code gets hang after some time it throw command timeout exception however when i'm trying to open simple page ("https://www.google.co.in") where popup window is not coming code is working fine.
![login issue](https://user-images.githubusercontent.com/38317825/38680811-d64f88ea-3e84-11e8-80e1-6ed957e667b6.jpg)

**Any help would be grateful!**

**Comment by barancev** [comment]
Selenium itself does not support Window ActiveDirectory, not it's going to support it in future. Use another automation tool to deal with this login dialogue, or configure test harness to work without AD.
