### ISSUE TITLE
WebDriverError: Error forwarding the new session Error forwarding the request Read timed out

### ISSUE THREAD

**Issue by siva3946** [SeleniumHQ/selenium#5773]
Hello! 

Please help me below issue

WebDriverError: Error forwarding the new session Error forwarding the request Read timed out
    at Object.checkLegacyResponse.

details config:
chromedriver :2.35
Node.js 8.9 version
selenium grid 3.9.1 with 2 node for automation.

Please help me

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
