### ISSUE TITLE
Internet Explorer automation crashes when a long test is run that interacts multiple webpages

### ISSUE THREAD

**Issue by ben-yocum** [SeleniumHQ/selenium#5778]
## Meta -
OS:  Windows 10
Selenium Version:  3.9.0 (IEDriverServer.exe)
Browser: Internet Explorer 11

selenium-webdriver (npm): 4.0.0-alpha.1
Node: 8.10.0

Browser Version: 11.909.15063.0 (64-bit)

## Expected Behavior -
I should be able to run a long test that interacts with multiple pages without my test crashing.

## Actual Behavior -
Webdriver (or Internet Explorer?) crashes when repeatedly loading and interacting with pages with Internet Explorer. This is NOT the only condition under which this bug occurs. It seems that issuing too many Webdriver commands with at least some driver.get() commands mixed in will reliably cause the crash. I consider this to be a SERIOUS BUG because it seems that it can break ANY long test against IE that interacts with more than one page.

The following does NOT seem to cause the crash:

* A long test that never changes pages or reloads the current page
* Only calling driver.get() without interacting with the page

The crash can take a variety of forms. Typically it happens after running for 10-20 minutes and will produce one of the following errors.

* Sometimes the browser page will go white and can no longer be interacted with, causing webdriver to error: `TimeoutError: Timed out waiting for page to load.`
* Sometimes the browser page will appear to load, but webdriver will report that an element clearly visible on the page cannot be interacted with: ` NoSuchElementError: Unable to find element with css selector == *[id="q"]`
* Sometimes Internet Explorer crashes completely, causing the standard Windows error window when a program stops responding: `Internet Explorer has stopped working. A problem caused the program to stop working correctly. Please close the program.`

## Steps to reproduce -
Execute this code and let the loop repeat for approximately 10-20 minutes. For your convenience I put this code with a package.json and complete setup instructions in [this git repo](https://github.com/GitSage/selenium-bug-browserget-repro).

```const {Builder, By} = require('selenium-webdriver');

(async function example() {
	let browser = await new Builder()
		.forBrowser('internet explorer')
		.build();
	let startTime = new Date().getTime();
	let currentTime;
	let numLoops = 0;

	while(true) {
		currentTime = new Date().getTime();
		numLoops++;
		process.stdout.write(`\rReloads: ${numLoops}, elapsed time: ${getElapsedTimeString(startTime, currentTime)}        `);
		await browser.get('https://google.com');
		await browser.findElement(By.name('q')).sendKeys('This will crash soon');
	}
})();

function getElapsedTimeString(startTime, endTime) {
	let elapsedSeconds = Math.floor((endTime - startTime) / 1000);

	let date = new Date(null);
	date.setSeconds(elapsedSeconds);
	return date.toISOString().substr(11, 8);
}```

**Comment by jimevans** [comment]
The latest version of the [IE driver is 3.11.1](http://selenium-release.storage.googleapis.com/index.html) (yes, I’m fully aware the downloads page on seleniumhq.com points to 3.9). I don’t expect there to be any change between 3.9 and 3.11.x, but could you at least retry your test with the latest driver?

**Comment by GitSage** [comment]
3.11.0 (32 bit): Crashed after 9 minutes. `TimeoutError: Timed out witing for page to load.`
3.11.0 (64 bit): Still has the 64-bit slow-typing issue. Did not proceed with test.

I also tried some older versions.

3.4.0 (32 bit): Successful run, no sign of defect. I killed it manually after 40 minutes.
3.7.0 (32 bit): Success.
3.8.0 (32 bit): Success.

**The defect is not present until 3.9.0.**

**Comment by apurba31** [comment]
I am running tests using version 3.12, and here as well the driver stops working. As long as its a single test, it works fine. But as the number of tests increases it stops. I am running a regression suite and I have to run multiple suits at a time, this behavior beats the purpose of regression!

**Comment by mjdavies** [comment]
Same.  Anyone get anywhere with this?

**Comment by ge3uHCekTop** [comment]
We've faced the same problem and looks like root cause lies deep in Internet Explorer memory leaks. Just check how much memory IE consumed when you got this error. I suppose this will be something around 2GB.

The only workaround we've found - restart IE after each 15-20 cases.
