### ISSUE TITLE
[Mac OS][C#]FireFox Driver asking for gecko.exe even though its Mac

### ISSUE THREAD

**Issue by kenofori** [SeleniumHQ/selenium#5779]
## Meta -
OS:  OS X
Selenium Version:  3.11.2 
Browser:  FireFox 59

Hi there,
I download C# build of Selenium 3.11.2 from Nuget and im able to run a safari on my Mac.
But if i run the FireFox it shows following error

`DriverServiceNotFoundException: The geckodriver file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.`

Now the thing is im on Mac, and when i open FireFoxDriver class code , all i see is refences to .exe which i believe is meant for windows.

Anyhow, i tried with following approaches by providing path directly to downloaded Gecko for Mac or its parent directory but still same error

```
new FirefoxDriver("/Volumes/BOOTCAMP/Projects/SeleniumProjct/geckodriver");
new FirefoxDriver("/Volumes/BOOTCAMP/Projects/SeleniumProjct/");
```

Please advise.
Thanks

**Comment by kenofori** [comment]
Can i override this behaviour without messing with code? 
So filename is always DefaultFirefoxDriverServiceFileName
Thanks

**Comment by jimevans** [comment]
You can create a `FirefoxDriverService` object using the `FirefoxDriverService.CreateDefaultService` method that takes the executable name as an argument. The resulting service object can be passed into the `FirefoxDriver` constructor. The question is why you’d need to override this, unless you’ve renamed the executable something other than “geckodriver.”

**Comment by kenofori** [comment]
@jimevans Thank you very much, it did the trick and now Firefox is working :)
