### ISSUE TITLE
FirefoxDriver not respecting sequential timeouts

### ISSUE THREAD

**Issue by rvazarkar** [SeleniumHQ/selenium#578]
After raising a TimeoutException, the Firefox Webdriver will fail to respect a second one immediately afterwards. The issue can be reproduced using the following code:

``` python
from selenium import webdriver
from selenium.common.exceptions import TimeoutException
import time

if __name__ == '__main__':
    driver = webdriver.Firefox()
    driver.set_page_load_timeout(5)
    for i in xrange(0, 10):
        try:
            t1 = time.time()
            driver.get('http://deelay.me/20000/http://www.google.com')
            driver.save_screenshot('/root/screen')
            t2 = time.time()
            print 'finished ' + str(i)
            print t2-t1
        except TimeoutException:
            print 'caught timeout ' + str(i)
    driver.quit()
```

The first iteration will properly timeout after 5 seconds, while the second iteration will not complete until the page fully loads (intentionally delayed by 20 seconds in the example). 

This will cause Selenium to hang completely if it encounters a page that never loads (such as real time data that continuously polls) provided it has already timed out once before.

**Comment by barancev** [comment]
The issue is still actual in legacy Firefox driver, but it's not going to be fixed.

New Firefox driver implementation (aka geckodriver) does not suffer from this issue.
Tested on Selenium 3.5.2 + geckodriver 0.18 + Firefox Nightly 57
