### ISSUE TITLE
chromedriver prevent unexpected alert open: {Alert text : }

### ISSUE THREAD

**Issue by codenoid** [SeleniumHQ/selenium#5781]
## Meta -
OS:  
Ubuntu 16.04.3 LTS
Selenium Version:  
downloaded at yesterday (idk the version)
Browser:  
Webdriver / google chrome

Browser Version:  
Google Chrome 65.0.3325.181 (64-bit)

Driver : 
Python Selenium

## Expected Behavior -

Prevent unexpected alert open: {Alert text : }

## Actual Behavior -

```
Traceback (most recent call last):
  File "app.py", line 171, in <module>
    main()
  File "app.py", line 109, in main
    clipper = driver.find_elements_by_css_selector("div.btn")
  File "/home/blaster/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 605, in find_elements_by_css_selector
    return self.find_elements(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/blaster/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 983, in find_elements
    'value': value})['value'] or []
  File "/home/blaster/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/blaster/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : }
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ab2a9a23218b282151362a66cd662),platform=Linux 4.4.0-116-generic x86_64)
```

## I have tried to use (but it doesn't work)

`driver.execute_script("window.alert = function() {};")`

## Steps to reproduce -
i can't tell you where i'm doing automation, but this alert appear when i want leave a page,

## Additional Info
this question available [in Stackoverflow](https://stackoverflow.com/q/49848571/9137919) too

**Comment by barancev** [comment]
It's working as designed. Selenum throws an exception when it detects an unhandled alert (including the ones that appear on page upload).

**Comment by codenoid** [comment]
but, `try` and `except` doesn't work with it :( @barancev

**Comment by jimevans** [comment]
This may not be triggered by the JavaScript `alert()` function, but rather something on the `onbeforeunload` event. The most common case of this is where there is a form of some kind that the developer doesn’t want the user to lose input data if they haven’t submitted it before attempting to navigate away. Chrome may not be able to automate those dialogs. They do not fit the strict definition of “alert.”
