### ISSUE TITLE
"Maximise browser Window" keyword not working in chrome.I am using selenium2Library.

### ISSUE THREAD

**Issue by mithunsureshqa** [SeleniumHQ/selenium#5793]
## Meta -
OS:  macOS High Sierra 10.13.4
Selenium Version:  3.11.0, Selenium2library=3.1.1 
Browser:  Chrome
Browser Version:  
Chrome --> 65.0.3325.181

## Expected Behavior -
Chrome browser should maximize to full screen mode.
## Actual Behavior -
Chrome browser does not maximize fully on using "Maximize Browser Window". Its not full screen.
## Steps to reproduce -
try Maximize Browser Window command with chrome browser on pycharm. or 
Easiest way to find where the problem is to you to run the following script:
save below steps as test.py script. Run from command line. --> python test.py
driver = webdriver.Chrome()
driver.get('https://github.com/robotframework/SeleniumLibrary')
driver.maximize_window()
time.sleep(5)
driver.quit()

from discussion : https://github.com/robotframework/SeleniumLibrary/issues/123#issuecomment-382142668

-->

**Comment by lmtierney** [comment]
That's how chrome maximizes on MacOS, you'll have to take it up with them.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
