### ISSUE TITLE
Safari freezing after click, Which leads to naviagate to another page.

### ISSUE THREAD

**Issue by NaveenKummetha** [SeleniumHQ/selenium#5795]
## Meta -
OS:  OSX 10
Selenium Version:  3.8.1
Browser:  Safari
Browser Version:  11.0.3

Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Any issue logged here for Firefox 48 or later will be closed as a duplicate of
#2559. Our recommendation is to switch to GeckoDriver, or to continue testing
on Firefox 45 until GeckoDriver is a viable option for you. If you are
interested in helping us to sign the add-on to restore support for later
Firefox versions, please see the following comment for what's needed:
https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

If the issue is with Microsoft Edge consider logging an issue with Microsoft instead:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

If the issue is with Firefox GeckoDriver (aka Marionette) consider logging an issue with Mozilla:
https://bugzilla.mozilla.org/buglist.cgi?product=Testing&component=Marionette

If the issue is with Safari, only Safari 10+ is supported. Please log any Safari issue with Apple:
https://bugreport.apple.com/

If the issue is with PhantomJS consider logging an issue with Ghostdriver:
https://github.com/detro/ghostdriver

-->

## Expected Behavior -
After **click** in the current page, It needs to navigate to next page.
While navigating running WaitUntilElementClickable or presence or visible.
Once element clickable needs to perform another task.
## Actual Behavior -
After **click** in current page, It is slowly navigating to next page.
If we run while navigating running WaitUntilElementClickable. safari freezing. No more operations performed.

As my observation running WaitUntilElementClickable uses the while loop with multiple times trying findElement() until element clickable. This while loop will exit after wait time. On the first iteration in while loop it will go to findelement and then freezing.

until method logic.

while(true){
    findelement() -> freezing here as my expectation. And then it is not breaking the loop.
    if(wait time reached){
          break;
    }
}

## Steps to reproduce -

Go to any website.
Click on any link to navigate.
Run WaitUntilElementClickable or presence or visible. the issue will start here. safari freez.

We have a temporary solution like by giving sleep for some time(10 sec), We can perform further tasks.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario.
