### ISSUE TITLE
selenium-webdriver npm packages

### ISSUE THREAD

**Issue by wlucha** [SeleniumHQ/selenium#5797]
The packages of selenium-webdriver between the versions 3.6.0 and 4.0.0-alpha.1 arent published to npm.
Is there any particular reason why these package aren't available via npm?

**Comment by barancev** [comment]
They are published: https://www.npmjs.com/package/selenium-webdriver
Please be more specific about your issue.

**Comment by lmtierney** [comment]
@wlucha there are no versions in between `3.6.0` and `4.0.0-alpha.1`. `3.6.0` was the last `3.x` version before the `4.0.0-alpha.1`

**Comment by notmessenger** [comment]
@Imtierney even though there are

https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.7.0
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.8.0
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.8.1
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.9.0
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.9.1
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.10.0
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.11.0
and
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.12.0 releases in the repo?

Are they intended to not be used I'm guessing and the switch over is from `3.6.0` to `4.0.0` when it happens?
