### ISSUE TITLE
Chrome Session not created

### ISSUE THREAD

**Issue by ajayimade** [SeleniumHQ/selenium#5799]
## Meta -
OS:  Ubuntu 16.04-
Selenium Version:  3.11.0
Browser:   Chrome(66.0.3359.117)
ChromeDriver: 2.37.544315

Using python client for selenium.

Getting below issue:
SessionNotCreatedException: Message: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.13.0-38-generic x86_64) 

I have tried to downgrade version of Chrome & Chrome Driver but facing same type of issue

**Comment by lmtierney** [comment]
> unable to connect to renderer

This is an issue with chrome or chromedriver, please enter a bug there https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lmtierney** [comment]
This typically happens when a new chrome version comes out and you need a newer chromedriver. You could try the one just released https://chromedriver.storage.googleapis.com/index.html?path=2.38/

**Comment by ajayimade** [comment]
I have tried 2.38 version also I tried to downgrade version of Chrome so
that chromedriver v2.37 supports.
But no success.

**Comment by barancev** [comment]
Anyway, you have to report this issue to chromedriver project.
