### ISSUE TITLE
Unable to run scripts on  IE 11 and RemoteWebDriver using Selenium-standalone-server.3.9.1

### ISSUE THREAD

**Issue by formynet** [SeleniumHQ/selenium#5801]
## Meta -
OS:  
Windows 7 Enterprise
Selenium Version:  
3.9.1

Selenium standalone server version :  3.9.1
Browser:  
 Internet Explorer 11

Browser Version:  
11.0.9600.18952

## Expected Behavior -
User should be able to run selenium scripts on IE 11 browser using selenium grid with Selenium standalone server version :  3.9.1 .

## Actual Behavior -
User gets java.lang.AssertionError: Exception creating driver: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'WAV0226', ip: '<<ip>>', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 670 milliseconds
 stacktrace :[Ljava.lang.StackTraceElement;@8a60bc

## Steps to reproduce -
1. Set IE Protected Mode to the same value (enabled or disabled) for all zones.
2.  Followed below steps to set up Registry as mentioned in IE Driver documentation:
For IE 11 only, you will need to set a registry entry on the target computer so that the driver can maintain a connection to the instance of Internet Explorer it creates. For 32-bit Windows installations, the key you must examine in the registry editor is HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.

3. Started hub and node. Hub and node are successfully started as displayed below :+1: 
HUB CONSOLE
src\test\resources>java -jar selenium-server-standalone-3.9.1.ja
r -role hub
13:37:15.748 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
13:37:15.768 INFO - Launching Selenium Grid hub on port 4444
2018-04-18 13:37:22.030:INFO::main: Logging initialized @11244ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-04-18 13:37:22.231:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T16:27:37-05:00, git hash: 8
2b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-04-18 13:37:22.349:INFO:osjs.session:main: DefaultSessionIdManager workerName=node0
2018-04-18 13:37:22.349:INFO:osjs.session:main: No SessionScavenger set, using defaults
2018-04-18 13:37:22.419:INFO:osjs.session:main: Scavenging every 600000ms
2018-04-18 13:37:22.479:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@1b7e5df{/,null,AVAILABLE}
2018-04-18 13:37:22.809:INFO:osjs.AbstractConnector:main: Started ServerConnector@6e276e{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
2018-04-18 13:37:22.819:INFO:osjs.Server:main: Started @12027ms
13:37:22.819 INFO - Selenium Grid hub is up and running
13:37:22.819 INFO - Nodes should register to <<url>>
13:37:22.819 INFO - Clients should connect to <<url>>
13:38:31.592 INFO - Registered a node <<node url>>

NODE CONSOLE:
>java -Dwebdriver.chrome.driver="chromedriver.
exe" -Dwebdriver.ie.driver="iedriver.exe" -jar selenium-server-standalone-3.9.1.jar -role node -hub "<<url>>"
13:38:29.741 INFO - Selenium build info: version: '3.9.1', revision: '63f7b50'
13:38:29.743 INFO - Launching a Selenium Grid node on port 5555
2018-04-18 13:38:30.428:INFO::main: Logging initialized @1835ms to org.seleniumhq.jetty9.util.log.StdErrLog
2018-04-18 13:38:30.708:INFO:osjs.Server:main: jetty-9.4.7.v20170914, build timestamp: 2017-11-21T16:27:37-05:00, git hash: 8
2b8fb23f757335bb3329d540ce37a2a2615f0a8
2018-04-18 13:38:30.738:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@20b53a{/,null,STARTING}
has uncovered http methods for path: /
2018-04-18 13:38:30.748:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@20b53a{/,null,AVAILABLE}
2018-04-18 13:38:30.778:INFO:osjs.AbstractConnector:main: Started ServerConnector@18d2680{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2018-04-18 13:38:30.778:INFO:osjs.Server:main: Started @2181ms
13:38:30.778 INFO - Selenium Server is up and running on port 5555
13:38:30.778 INFO - Selenium Grid node is up and ready to register to the hub
13:38:30.958 INFO - Starting auto registration thread. Will try to register every 5000 ms.
13:38:30.958 INFO - Registering the node to the hub: <<url>>
13:38:31.632 INFO - Updating the node configuration from the hub
13:38:31.662 INFO - The node is registered to the hub and ready to use
2018-04-18 14:39:44.707:INFO:osjshC.ROOT:qtp26882836-16: org.openqa.selenium.remote.server.WebDriverServlet-93084c: Initialis
ing WebDriverServlet
14:39:44.977 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@a9552
14:39:44.987 INFO - /session: Executing POST on /session (handler: BeginSession)
14:39:45.596 INFO - Capabilities are: Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtected
ModeSettings: true, ignoreZoomSetting: true, platform: WINDOWS, version: }
14:39:45.606 INFO - Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtectedModeSettings: true
, ignoreZoomSetting: true, platform: WINDOWS, version: } matched class org.openqa.selenium.remote.server.ServicedSession$Fact
ory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (32-bit)
3.10.0.0
Listening on port 3589
Only local connections are allowed
14:39:50.755 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@1cfe4b
14:39:50.755 INFO - /session: Executing POST on /session (handler: BeginSession)
14:39:50.755 INFO - Capabilities are: Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtected
ModeSettings: true, ignoreZoomSetting: true, platform: WINDOWS, version: }
14:39:50.755 INFO - Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtectedModeSettings: true
, ignoreZoomSetting: true, platform: WINDOWS, version: } matched class org.openqa.selenium.remote.server.ServicedSession$Fact
ory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (32-bit)
3.10.0.0
Listening on port 6790
Only local connections are allowed
14:40:20.733 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@c6f00d
14:40:20.733 INFO - /session: Executing POST on /session (handler: BeginSession)
14:40:20.743 INFO - Capabilities are: Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtected
ModeSettings: true, ignoreZoomSetting: true, platform: WINDOWS, version: }
14:40:20.753 INFO - Capabilities {browserName: internet explorer, ensureCleanSession: true, ignoreProtectedModeSettings: true
, ignoreZoomSetting: true, platform: WINDOWS, version: } matched class org.openqa.selenium.remote.server.ServicedSession$Fact
ory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)

-------------------------------------------
In eclipse console , I get below error :
java.lang.AssertionError: Exception creating driver: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 'WAV0226', ip: '<<IP>>', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_162'
Driver info: driver.version: unknown
remote stacktrace: 
Command duration or timeout: 670 milliseconds
 stacktrace :[Ljava.lang.StackTraceElement;@8a60bc

This despite IE being set up correctly with all protected mode zones.
IE browser is not even opened. 

I get above error irrespective of script. I have tried instantiating webdriver using capabilities and options. Same issue. 

The error message is also highly misleading as IE does have required protected mode setting. Any help to resolve this is highly appreciated.

**Comment by formynet** [comment]
I am able to run scripts using IE 11 and selenium client locally but for some reason  I get reported error using IE 11 and Selenium-standalone-server 3.9.1 version

**Comment by formynet** [comment]
Any update on the ticket?

**Comment by diemol** [comment]
I was able to run tests with the latest IE, IEServer and Selenium Grid 4 beta-2, I cannot reproduce this issue and we are not troubleshooting Selenium Grid 3.x issues anymore.

Please try with the most recent version of Grid, and if you bump into any problems, please open a new issue.
