### ISSUE TITLE
ElementNotVisible error for visible elements in IE, When Parent element size is 0px

### ISSUE THREAD

**Issue by athulds** [SeleniumHQ/selenium#5804]
## Meta -
OS:  Windows 7
Selenium Version:  3.11.0 
Browser:  Internet Explorer 

Browser Version:  11 (32 bit)

## Expected Behavior - 
Regardless of the visibility of the parent elements in the DOM, A visible, interactable element should be
accessible through selenium also.Actions which user is able to do manually also should work through selenium. Behaviour in both internet explorer and chrome should be same.
## Actual Behavior -
In Internet explorer, elements which are visible and interactable for the user are throwing ElementNotVisible Exception.
This issue is there only in internet explorer. When one of the parent has a style property with height 0px and width 0px, selenium is telling the element is not visible.Hence it is not allowing actions on that element also.

## Steps to reproduce -
Use the attached html file to reproduce the issue. There is an input f
ield which is visible and accessible for the user.It has a parent div element which has style property with both height and width 0px.
There is no issue in chrome.
[selenium_bug.zip](https://github.com/SeleniumHQ/selenium/files/1927041/selenium_bug.zip)
Steps:
>element  = driver.find_element_by_xpath('//input')
>element.is_displayed()
>False
>element.click()
>ElementNotVisibleException

**Comment by GitSage** [comment]
I was unable to reproduce your defect.

OS: Windows 10
Selenium Version: 3.11.1
Browser: Internet Explorer

Browser Version: 11 (64 bit)

I successfully ran the following with webdriverjs and Node 8.11.0.

```
const {Builder, By} = require('selenium-webdriver');

(async () => {
	let driver = await new Builder()
		.forBrowser('internet explorer')
		.build();

	await driver.get('http://127.0.0.1:8080/selenium_bug.html');
	let input = await driver.findElement(By.xpath('//input'));
	let isDisplayed = await input.isDisplayed();

	if(!isDisplayed) {
		throw 'Could not see input!';
	}
	console.log(`Element is displayed: SUCCESS`);

	let value = 'Hi, Mom!';
	await input.sendKeys(value);

	let actual = await input.getAttribute('value');
	if(value !== actual) {
		throw 'Could not send keys to input!';
	}
	console.log(`Element can be interacted with: SUCCESS`);

	await driver.quit();
})();
```

**Comment by diemol** [comment]
This issue went stale, we didn't get more information from the OP after the comment made above.
