### ISSUE TITLE
RemoteWebDriver.findElement()  returns null

### ISSUE THREAD

**Issue by kool79** [SeleniumHQ/selenium#5809]
**Selenium Version:**  v 3.8.1 (java bindings)

I use `RemoteWebDriver` (connected to chomedriver)  which is wrapped by `EventFiringWebDriver`. 

My stacktrace shows NPE with stacktrace

```
Caused by: java.lang.NullPointerException:
	at org.openqa.selenium.support.events.EventFiringWebDriver.extractInterfaces(EventFiringWebDriver.java:124)
	at org.openqa.selenium.support.events.EventFiringWebDriver.access$500(EventFiringWebDriver.java:69)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.<init>(EventFiringWebDriver.java:368)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.<init>(EventFiringWebDriver.java:360)
	at org.openqa.selenium.support.events.EventFiringWebDriver.createWebElement(EventFiringWebDriver.java:311)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:194)
.....
```

NPE was caused by line
```
extractInterfaces(allInterfaces, object.getClass());
```
in `EventFiringWebDriver.extractInterfaces()`.  When I analyzed chain of calls I found that  `object`  should be the WebElement which is returned by 
```
 WebElement temp = driver.findElement(by);
```
by `EventFiringWebDriver.findElement()`. Here `driver` is instance of RemoteWebDriver.

I know that actually it is chromedriver issue. But there are very similar issues here (for findElement*s*() ) which were fixed at client side, see  #4555 and #4375.

**Extra info:**
In my case I tried to wait until element in another window will dissapear (by scenario window should be closed after click 'pay' button) So I expected that findElement will throw StaleElementException, ElementNotFoundException or NoSuchWindowException but I got NPE instead. 
Subsequent  call to webdriver returned:
```org.openqa.selenium.NoSuchWindowException: no such window: target window already closed from unknown error: web view not found (Session info: chrome=63.0.3239.108) (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7601 SP1 x86_64) ....```

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also retest in the latest version (that is 3.11 at the moment)

**Comment by kool79** [comment]
Retested on 3.11 - have the same issue

I cannot give you reproducible testcase which works well because issue occurred rarely (I have 2 fails in the same place in code for  > 200 executions of data-driven test)

  Can we have some workaround for this? Like you did for `findElements`  in 4a3ec2d when fixing #4555. For example, throw `NotFoundException` or some other exception when remote driver returns `null` for findElement ?

**Comment by Karengrigoryan060** [comment]
Hi all. 
Can someone help to find workaround for this?
