### ISSUE TITLE
Make DriverService.Builder.usingDriverExecutable accept InputStream

### ISSUE THREAD

**Issue by EldarAgalarov** [SeleniumHQ/selenium#5815]
Please implement
usingDriverExecutable(InputStream is) in addition to usingDriverExecutable(File file)

When driver executable is as resource inside JAR  then there are problems, because inside jars resources are streams. 

Preferred way:
`ChromeDriverService.Builder().usingDriverExecutable(getClass().getResourceAsStream("/chromedriver.exe")).build()`

**Comment by barancev** [comment]
To run an executable you have to extract it from JAR to an independent file. We'll not add this feature in Selenium, this extraction or any other preparation steps should be implemented independently.
