### ISSUE TITLE
[Mac OS][C#]FireFox Driver Set Capability and ServiceName same time

### ISSUE THREAD

**Issue by kenofori** [SeleniumHQ/selenium#5816]
OS: OS X
Selenium Version: 3.11.2
Browser: FireFox 59

Hi there,

Im trying to use both capability and service name but there is no relavant constructor which takes both.
Please advise

`
FirefoxDriverService driverService = FirefoxDriverService.CreateDefaultService("/Volumes/BOOTCAMP");

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.SetCapability(CapabilityType.AcceptInsecureCertificates, true);

new FirefoxDriver(driverService, capabilities);		    

`

**Comment by jimevans** [comment]
You should be using the constructor overload that takes a `FirefoxDriverService` and a `FirefoxOptions` as arguments. Using the raw capabilities object is deprecated in the .NET bindings.

**Comment by kenofori** [comment]
If i try options like this

`
FirefoxOptions options = new FirefoxOptions();
options.AddAdditionalCapability(CapabilityType.AcceptInsecureCertificates, true);
new FirefoxDriver(driverService, options, TimeSpan.FromSeconds(1));		    		    
`

I get this error.

> InvalidOperationException: Invalid moz:firefoxOptions field acceptInsecureCerts

**Comment by kenofori** [comment]
Alright, i used following
`		    options.AcceptInsecureCertificates = true;
`

but i still see attached error.
Please advise

And in case its GeckoDriver issue, what should i do? report issue there?

Thank you very much support so far

**Comment by Bethannfrum** [comment]
Fix and restore to original format and release old documents

**Comment by diemol** [comment]
As mentioned in the comments above, if the issue still persists, please report it to https://github.com/mozilla/geckodriver/
