### ISSUE TITLE
API for # of free/busy nodes ?

### ISSUE THREAD

**Issue by Twista** [SeleniumHQ/selenium#5819]
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
v.2.53.0
Browser:
xx

---

I'm trying to setup monitoring for our selenium grid to see how many nodes are busy/free (and eventually set-up scaling for them). Already found few pages describing API methods, but none of them show such a method, to see how many nodes are free/busy/available. Am I missing anything?

So far I was able to come-up with this:
`curl -sX GET http://<grid-url>/grid/console | grep -c "class='busy'"` - which tells me how many nodes are busy atm (means also I need to know how many nodes we have at time of the request)

My question is: is there any API-enpoint which will tell me that info (busy/free/capacity) - we will upgrade to Selenium 3 very soon => would appreciate Selenium 3 only solution too.

thanks!

**Comment by schmidtkp** [comment]
@Twista You could write your own servlet and add it to your hub config. You can then call the servlet from whatever makes sense for you. This is what I've done to provide teams with a view of the grids usage - Total nodes registered, Nodes in Use, Nodes Free, Queued Requests, etc...

**Comment by Twista** [comment]
Thanks you @schmidtkp for response.

Gonna try that, do you have any good resource where to start with serverlets&selenium ?

**Comment by schmidtkp** [comment]
@Twista Adding servlets to hub is pretty straight forward. See Selenium docs for that. As for writing servlets, it deoends on lanuge you are using (I use Java) so I would suggest Google is your best friend :-)
