### ISSUE TITLE
Unable to navigate to URL in Safari

### ISSUE THREAD

**Issue by spatchamatla** [SeleniumHQ/selenium#582]
Protractor 2.1.0
Safari 8.0.6
Webdriver 2.45.0
OSX 10.10.3
Safari extension 2.45.0

i tried with selenium-server-standalone-2.45.0 and when i run the script it navigates to the first URL but when it try to navigate to second url, it displays only **about:blank** and it times out with
```
ScriptTimeoutError: Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.10 seconds
Build info: version: '2.45.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'mac.local', ip: '<>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=8.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null

java.lang.NullPointerException
    at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:319)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
    at com.sun.proxy.$Proxy1.getCurrentUrl(Unknown Source)
    at org.openqa.selenium.support.events.EventFiringWebDriver.getCurrentUrl(EventFiringWebDriver.java:164)
    at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:30)
    at org.openqa.selenium.remote.server.handler.GetCurrentUrl.call(GetCurrentUrl.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
its not even navigating to second URL.Im using browser.get() to navigate to the URLs. i tested both url's manually and it works fine if i run on chrome as well.
Is there any where i can download safari extension v2.38.0 or safari extension v2.44.0?

**Comment by gerrymcgovern1** [comment]
I am also seeing this issue only with Safari. Chrome and Firefox both work fine. Would be great to get a fix!

**Comment by ddavison** [comment]
could you provide a [SSCCE](http://sscce.org) please?

**Comment by spatchamatla** [comment]
Im using 
Protractor 2.1.0
Safari 8.0.6
Webdriver 2.45.0
OSX 10.10.3
Safari extension 2.45.0
```
describe ('Test Safari with two URLs', function() {

    var defaultSyncStatus = browser.ignoreSynchronization;

    beforeEach(function(){
        //for non angular Pages
        browser.ignoreSynchronization = true;
        browser.get('http://www.google.com');
    });

    afterEach(function() {
    });

    it('test with apple.com', function () {
        browser.ignoreSynchronization = defaultSyncStatus;
        browser.get('http://www.apple.com');
    });
});
```
let me know if you need more information.

**Comment by gerrymcgovern1** [comment]
Rspec/Capybara - (Rspec 3.2.0, Capybara 2.4.4)
safari - 8.0.6
safari extension - 2.45
selenium-webdriver - 2.46.2
OSX - 10.10.3

I see the error when attempting to enter email and password for twitter login. 

     Selenium::WebDriver::Error::ScriptTimeOutError:
       Timed out awaiting response to command "executeScript" after 30002 ms
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/safari/bridge.rb:92:in `raw_execute'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:635:in `execute'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/bridge.rb:360:in `executeScript'
     # /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/common/driver.rb:210:in `execute_script'
     # /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/selenium/node.rb:46:in `set'
     # /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/node/element.rb:107:in `block in set'
     # /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Library/Ruby/Gems/2.0.0/gems/capybara-2.4.4/lib/capybara/node/element.rb:103:in `set'
     # ./page_objects/wifi/twitter_login_page.rb:6:in `enter_twitter_login_details'
     # ./spec/wifi/wifi_login_spec.rb:20:in `block (2 levels) in <top (required)>'

**Comment by ddavison** [comment]
hrm... can't seem to replicate.  

```ruby
require 'selenium-webdriver'

browser = Selenium::WebDriver.for :safari

browser.get 'http://www.google.com'
puts "we're at #{browser.title}"
browser.get 'http://www.apple.com'
puts "we're at #{browser.title}"

#=> we're at Google  we're at Apple
```

**Comment by spatchamatla** [comment]
im able to replicate here on my end and here is the protractor config as well.
```
/**
 * Created by spatchamatla on 05/11/15.
 */

var browsers = {
    chrome:{
        name:'Chrome',
        browserName:'chrome',
        chromeOptions : {
            args: ['--lang=en','--window-size=1024,768']
        }
    },
    safari:{
        name:'Safari',
        browserName:'safari'
    },
    multiCapabilities: [{
        browserName: 'safari'
    }, {
        browserName: 'chrome',
        chromeOptions : {
            args: ['--lang=en','--window-size=1024,768']
        }
    }]

}
exports.config = {
    // The address of a running selenium server.
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

    // Spec patterns are relative to the configuration file location passed to protractor
    // They may include glob patterns.
    specs: [
        '../Scenarios/CSAdmin/Impersonation_scenario.js'
    ],

    //asynchronous time out
    allScriptsTimeout: 30000,

    onPrepare: function() {
        //increase the script time outs
        browser.manage().timeouts().setScriptTimeout(30000);
    },

    //For Jasmine framework
    framework: 'jasmine',

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        // Use colors in the command line report.
        showColors: true,
        //for StackTrace -- not for Jasmine 2
        includeStackTrace:true,
        //for Verbose -- not for Jasmine 2
        isVerbose:true,
        //for defaultTimeoutInterval
        // max time any test case can run
        defaultTimeoutInterval:300000
        //showTiming: true
    }
};

if(process.argv[3] === '--chrome'){
    exports.config.capabilities = browsers.chrome;
}else if(process.argv[3] === '--safari'){
    exports.config.capabilities = browsers.safari;
};
```

**Comment by ddavison** [comment]
have you checked with https://github.com/angular/protractor ?  it looks like it may be an issue with Protractor, since I cannot replicate with anything "other" than protractor.  

Ruby bindings, Java bindings both to no avail, but i **can** reproduce using protractor.  I defer to that project.
