### ISSUE TITLE
unable to perform drag and Drop using selenium in IE browser

### ISSUE THREAD

**Issue by AbhiRaj93** [SeleniumHQ/selenium#5821]
moveTargetOutOfBoundException.Requested mouseMovementOut of view port.Getting the error when trying to performMoveToElement in ie browser using selenium

**Comment by jimevans** [comment]
This is in compliance with the W3C WebDriver Specification. While prior versions of the driver may have allowed this, current and future versions do not and will not unless there are changes to the spec. The behavior should now be consistent with running against Firefox while using geckodriver.

**Comment by AbhiRaj93** [comment]
I am using webdriver version 3.8.1 and ie 11.its not working here..As per my project req.. Have to run it in IE... will it work in any version later than 3.8.1

**Comment by jimevans** [comment]
Moving to an element works in all versions, as long as the element is within the browser view port window. If the target element is not in the view port, you will need to scroll it into view first. You also don’t state what version of the IE driver (which can be different from the version of Selenium) you’re using.

The point about Firefox was not intended to indicate that you needed to run the test in Firefox. Instead, it was simply to point out that the specification defines this behavior, and that both geckodriver and the IE driver should behave the same way.

Let me repeat the earlier comment to answer your question. Current and future versions of the IE driver will show this behavior until and unless there are changes to the specification that dictate changes in the driver implementation.

**Comment by AbhiRaj93** [comment]
IE driver version is 3.11.0.Have upgraded selenium version to 3.11.0 as well.Have scrolled it into view also and tried.The same is working pretty fine in chrome.

**Comment by AbhiRaj93** [comment]
Thanks for your help and info :smiley:
