### ISSUE TITLE
invalid selector: Unable to locate an element with the xpath expression

### ISSUE THREAD

**Issue by rahul769a** [SeleniumHQ/selenium#5826]
## Meta -
OS:  Win7 

Selenium Version:  
3.11.0
Browser:  
chrome

Browser Version:  

## Steps to reproduce -
Xpath written  //*[name()='g'][@clip-path='url(https://cncqa.cora.genpact.ai/CoraCnC/Dashboard/#highcharts-c47ixxb-34)']
Note: i am able find the element in chrome xpathfinder,
##when i am running the script  it is getting failed with below mentioned error

org.openqa.selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression [//*[@class='highcharts-series highcharts-series-0 highcharts-tilemap-series highcharts-color-0 highcharts-tracker ']//*[name()='path'][@stroke='#f04d3b'] because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '[//*[@class='highcharts-series highcharts-series-0 highcharts-tilemap-series highcharts-color-0 highcharts-tracker ']//*[name()='path'][@stroke='#f04d3b']' is not a valid XPath expression.
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'EDT-118', ip: '172.16.17.118', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: D:\Users\--\AppDat...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true}
Session ID: 41f1e34e768fa2ea8d481538d28a7712
*** Element info: {Using=xpath, value=[//*[@class='highcharts-series highcharts-series-0 highcharts-tilemap-series highcharts-color-0 highcharts-tracker ']//*[name()='path'][@stroke='#f04d3b']}
Execution completed.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
