### ISSUE TITLE
Timeout: timed out error when using Selenium hub and node.

### ISSUE THREAD

**Issue by MarkDabe** [SeleniumHQ/selenium#5828]
I am trying to run a series of tests against internet explorer on a remote machine. I have both Selenium hub and node running on that remote machine. When I trying running the tests from my local machine the tests fail and I get the following error:
[localhost:2664] out: Traceback (most recent call last):
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/fuelserve/testing/login.py", line 50, in setUp
[localhost:2664] out:     desired_capabilities={'platform': 'WINDOWS','browserName': 'internet explorer', 'javascriptEnabled': True}
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
[localhost:2664] out:     self.start_session(desired_capabilities, browser_profile)
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
[localhost:2664] out:     response = self.execute(Command.NEW_SESSION, parameters)
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
[localhost:2664] out:     response = self.command_executor.execute(driver_command, params)
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
[localhost:2664] out:     return self._request(command_info[0], url, body=data)
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 528, in _request
[localhost:2664] out:     resp = opener.open(request, timeout=self._timeout)
[localhost:2664] out:   File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
[localhost:2664] out:     response = self._open(req, data)
[localhost:2664] out:   File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
[localhost:2664] out:     '_open', req)
[localhost:2664] out:   File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
[localhost:2664] out:     result = func(*args)
[localhost:2664] out:   File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
[localhost:2664] out:     return self.do_open(httplib.HTTPConnection, req)
[localhost:2664] out:   File "/usr/local/lib/python2.7/urllib2.py", line 1201, in do_open
[localhost:2664] out:     r = h.getresponse(buffering=True)
[localhost:2664] out:   File "/srv/fuelserve/venvs/branches-20180419-6994/lib/python2.7/site-packages/raven/breadcrumbs.py", line 375, in getresponse
[localhost:2664] out:     rv = real_getresponse(self, *args, **kwargs)
[localhost:2664] out:   File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
[localhost:2664] out:     response.begin()
[localhost:2664] out:   File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
[localhost:2664] out:     version, status, reason = self._read_status()
[localhost:2664] out:   File "/usr/local/lib/python2.7/httplib.py", line 394, in _read_status
[localhost:2664] out:     line = self.fp.readline(_MAXLINE + 1)
[localhost:2664] out:   File "/usr/local/lib/python2.7/socket.py", line 480, in readline
[localhost:2664] out:     data = self._sock.recv(self._rbufsize)
[localhost:2664] out: timeout: timed out

However, when I restart both the hub and node again the tests run normally. What would be causing this error ? Thanks.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
