### ISSUE TITLE
Odd behavior in Node.js bindings

### ISSUE THREAD

**Issue by cameronroe-cbt** [SeleniumHQ/selenium#5829]
## Meta -
OS:  macOS

Selenium Version:  4.0.0-alpha.1

Browser:  any

Browser Version:  any

The issue I am having is odd behavior from the Node.js bindings in terms of using the `wait()` function with `condition` being a function that returns a `Condition`. This pattern worked fine on 3.6, but presents unintuitive behavior in 4.0.0-alpha.1. I am able to prepare a pull request to address this odd behavior, I am just unsure of what should be the correct behavior of this pattern. Currently, it is immediately resolving the Promise with the success callback and not respecting a given timeout. If behavior should be consistent with 3.6, it should respect the timeout and only resolve when the condition is true and reject on timeout. If this pattern should be disallowed, then there should be a friendly exception thrown instead of silently assuming the condition is true and resolving the promise immediately.

I have an example snippet attached that reproduces this issue.

```javascript
"use strict"; 
var webdriver = require("selenium-webdriver");
 
var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();
function checkTitle() {
    driver.getTitle()
    .then(function(title) {
        console.log("The title is: " + title)
    });
    return webdriver.until.titleIs('Google');
}
 
function handleFailure(err) {
     console.error('Something went wrong!\n', err.stack, '\n');
     quitDriver();
} 
function quitDriver() {
    console.log("WebDriver is about to close.");
    driver.close();
} 
driver.get('https://google.com'); 
let result = driver.wait(checkTitle, 1000).then(quitDriver, handleFailure);
```

**Comment by diemol** [comment]
@cameronroe-cbt, is this still happening on the most recent release?
https://www.npmjs.com/package/selenium-webdriver/v/4.0.0-alpha.8

**Comment by diemol** [comment]
Closing as we did not get more information from the OP.
