### ISSUE TITLE
The Switch To Window request is not translated correctly for geckodriver (Selenium 3.11.0)

### ISSUE THREAD

**Issue by OttoG** [SeleniumHQ/selenium#5831]
## Meta -
OS:  OSX

Selenium Version:  selenium-server-standalone-3.11.0

Browser:
Firefox

Browser Version:
59.0.2 (64-bit)

## Expected Behavior -

I am using NightwatchJS to drive a Firefox browser through Selenium Server. One task that is needed is switching the active window.

NightwatchJS sends commands to Selenium using the old JsonWireProtocol. These commands are translated somehow by Selenium into W3C WebDriver commands that are sent to the geckodriver for Firefox. This translation fails for the command known as "POST /session/:sessionId/window" in the JsonWireProtocol documentation:

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidwindow

The geckodriver application expects a property named "handle" in the parameters argument (in the POST request), but it gets a property named "name", similarly to the JsonWireProtocol POST request:

https://w3c.github.io/webdriver/webdriver-spec.html#switch-to-window

With Google Chrome, the same command works, presumably because chromedriver uses the old protocol, so that no translation is needed.

## Actual Behavior -

For exemple, NightwatchJS will post this to Selenium to switch to the window with handle 2147483669 (captured with tcpdump):

```
POST /wd/hub/session/6a857140-c0e3-e44e-a236-e976c1fff0c9/window HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 21
Host: localhost:4444
Connection: close

{"name":"2147483669"}
```

The result will be:

```
HTTP/1.1 500 Server Error
Connection: close
Date: Wed, 25 Apr 2018 16:43:06 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Cache-Control: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 1266
Server: Jetty(9.4.7.v20170914)

{"state":"invalid argument","sessionId":null,"value":{"additionalInformation":"\nDriver info: driver.version: unknown","localizedMessage":"Missing 'handle' parameter\nBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'\nSystem info: host: 'cpdstosem003.local', ip: 'fe80:0:0:0:8e8:a787:95f2:aa9f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_25'\nDriver info: driver.version: unknown","systemInformation":"System info: host: 'cpdstosem003.local', ip: 'fe80:0:0:0:8e8:a787:95f2:aa9f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_25'","supportUrl":null,"cause":null,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"suppressed":[],"message":"Missing 'handle' parameter\nBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'\nSystem info: host: 'cpdstosem003.local', ip: 'fe80:0:0:0:8e8:a787:95f2:aa9f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.4', java.version: '1.8.0_25'\nDriver info: driver.version: unknown","class":"org.openqa.selenium.InvalidArgumentException","buildInformation":null},"class":"org.openqa.selenium.remote.Response","status":61}
```

If tcpdump is used to capture the communication between Selenium and geckodriver, this exchange is seen for the same command:

```
POST /session/ee990c9b-9ccf-7f4f-8543-7e7979a17ab0/window HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 21
Host: localhost:23884
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.9.1

{"name":"2147483669"}

HTTP/1.1 400 Bad Request
Connection: close
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Content-Length: 93
Date: Wed, 25 Apr 2018 16:48:48 GMT

{"value":{"error":"invalid argument","message":"Missing 'handle' parameter","stacktrace":""}}
```

## Steps to reproduce -

Perhaps the tcpdump traces are enough to illustrate the problem, but here is how to reproduce it.

Start a Selenium server listening to port 4444, for example by:

/usr/bin/java -Dwebdriver.gecko.driver=./geckodriver -jar ./selenium-server-standalone-3.11.0.jar -port 4444

Connect to port 4444 using curl or some other tool in order to establish a session. Then use the same tool to send the first POST request shown above (POST /wd/hub/session/6a857140-c0e3-e44e-a236-e976c1fff0c9/window HTTP/1.1 with content {"name":"2147483669"}), adjusting the session ID to match the current session.

The window handle content could be adjusted to match an existing window handle in the session (as done below), but it is not necessary to reproduce the problem, as the geckodriver will not understand the "name" parameter that is sent after translation.

```
curl -XPOST http://localhost:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"firefox","javascriptEnabled":true}}'

curl -XPOST http://localhost:4444/wd/hub/session/b40b7c56-7c7c-0243-83d1-881b70a24204/url -d '{"url":"https://github.com/SeleniumHQ"}'

curl http://localhost:4444/wd/hub/session/b40b7c56-7c7c-0243-83d1-881b70a24204/window_handles

curl -XPOST http://localhost:4444/wd/hub/session/b40b7c56-7c7c-0243-83d1-881b70a24204/window -d '{"name":"2147483649"}'
```

The last command is correctly formed according to the JsonWireProtocol specification but gives a format error. I realize that the semantics differ slightly between the two protocols (the name parameter means handle or name in the JsonWireProtocol, but there is no way of selecting a window by name in the WebDriver protocol), but one would assume the translation to work to the extent that it can, by allowing selection by handle.

**Comment by lmtierney** [comment]
> These commands are translated somehow by Selenium into W3C WebDriver commands that are sent to the geckodriver for Firefox

It is my understanding that _some_ commands are still translated, but they should not be relied upon. As of `3.5` I believe, passthrough mode is on by default so commands will pass through server which is why you aren't getting the `handle` parameter.

In short, nightwatch needs to update to handle `w3c` commands and not rely on selenium to translate commands for it.

Is any of this inaccurate @barancev @shs96c ?

**Comment by barancev** [comment]
Yes, nightwatch should be updated to conform to W3C standard.

Or even better it should implement negotiation phase to detect remote end conformance level (is it legacy or w3c conformant) and send different payload according to the negotiation results. That's exactly what selenium bindings do.
