### ISSUE TITLE
Web Driver Issue Find Element and Timeout not respected

### ISSUE THREAD

**Issue by OnamChilwan** [SeleniumHQ/selenium#5836]
I am trying to locate elements on the page but although I have set the timeout and used waits, it doesn't seem to respect this. It waits a couple of seconds before crashing and stating, unable to locate the element. 

Am I using this incorrectly?

Packages:

>     <PackageReference Include="LightBDD.NUnit3" Version="2.3.4" />
>     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.0" />
>     <PackageReference Include="NReco.PhantomJS" Version="1.0.4" />
>     <PackageReference Include="NUnit" Version="3.9.0" />
>     <PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
>     <PackageReference Include="Selenium.Chrome.WebDriver" Version="2.38.0" />
>     <PackageReference Include="Selenium.PhantomJS.WebDriver" Version="2.1.1" />
>     <PackageReference Include="Selenium.WebDriver" Version="3.11.2" />

```
            using (var a = ChromeDriverService.CreateDefaultService($@"{Directory.GetCurrentDirectory()}\Tools"))
            {
                using (var driver = new ChromeDriver(a, new ChromeOptions(), TimeSpan.FromSeconds(10)))
                {
                    driver.Manage().Cookies.DeleteAllCookies();
                    driver.Manage().Timeouts().ImplicitWait = new TimeSpan(0, 0, 40);
                    driver.Navigate().GoToUrl("https://www.paypal.com");
                    driver.Manage().Window.Maximize();
                    var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
                    wait.Until(x => x.FindElement(By.Id("email"))); //crashes here

                    driver.FindElementById("email").Click();
                }
            }
```

*UPDATE*
Should also mention that even after adding a `Thread.Sleep` and the window has loaded, it can't locate the element. Looks like it doesn't have focus or a handle on the window opened..

**Comment by barancev** [comment]
I've investigated PayPal site home page, there is no element with id=email there

**Comment by OnamChilwan** [comment]
Sorry, I should of mentioned that the example I gave above was a theoretical one. The actual page I visit times out after a period of time. In a nutshell, when you transact with PayPal you have x amount of time to login and complete the payment. Doesn't make sense to add the URL I am trying to hit in this issue as it probably won't be reachable.

The page I actually visit does have an element called email and another for password. I have also removed the implicit wait to no avail.

**Comment by OnamChilwan** [comment]
Btw this shouldn't be closed as it is an issue :) I'll try to work through it or use an alternative library

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
