### ISSUE TITLE
Element drag/Move not working. No action performed

### ISSUE THREAD

**Issue by JurisPanfilo** [SeleniumHQ/selenium#5837]
## Meta -
OS:  Windows 7 
Selenium Version:  3.11.0
Browser:  Chrome 66.0.3359.139
Chromedriver version:  ChromeDriver 2.38

## Expected Behavior -
When I run 
`Actions builder = new Actions(driver);
WebElement element = driver.findElement(By.id("hplogo"));
builder.dragAndDropBy(element,100, 100).build().perform();`
I expect to see how element is dragged and dropped By offset 100, 100

## Actual Behavior -
Nothing happens. No exceptions.
If I click in browser window during dragAndDropBy execution,  I can observe that element blinks under cursor.

## Steps to reproduce -
Manual execution
Navigate to www.google.com
Drag and drop element logo by offset 100, 100

Automated execution
driver.get("http://www.google.com");
WebElement element = driver.findElement(By.id("hplogo"));
builder.dragAndDropBy(element,100, 100).build().perform();`

**Comment by mbn217** [comment]
HI, can you try this code below (java)
WebElement From = driver.findElement(By.xpath("yourFROMxpath"));
 
WebElement To = driver.findElement(By.xpath("yourTOxpath"));
 
Actions builder = new Actions(driver);
 
Action dragAndDrop = builder.clickAndHold(From)
 
.moveToElement(To)
 
.release(To)
 
.build();
 
dragAndDrop.perform();

**Comment by JurisPanfilo** [comment]
> HI, can you try this code below (java)
WebElement From = driver.findElement(By.xpath("yourFROMxpath"));

Hi, Tried.  Same behavior.

**Comment by barancev** [comment]
Please report this issue to chromedriver project:
https://sites.google.com/a/chromium.org/chromedriver/help
