### ISSUE TITLE
Internet Explorer does not click on multiline links in an iframe

### ISSUE THREAD

**Issue by Chraneco** [SeleniumHQ/selenium#5840]
## Meta -
OS:  Windows 10

Selenium Version:  3.11

Browser:  Internet Explorer

Browser Version:  11

## Expected Behavior -

IE should successfully click on all kinds of links

## Actual Behavior -

In some cases, IE driver incorrectly calculates the coordinates of link elements, causing IE to miss the intended click.

## Steps to reproduce -

Two conditions must be true for this problem to appear:
- The link is inside an iframe which is not located at the top left of the page
- The link must be wrapped to at least two lines to have multiple clientrects.

You can use the following simple HTML to reproduce the problem:

main.html
```
<html>
<body>
<iframe id="test" src="test.html" style="margin-top:80px;" />
</body>
</html>
```

test.html
```
<html>
<body><table style="border:3px solid red"><tr><td><a href="http://google.com" style="border:3px solid red">Test Test Test Test Test Test Test Test Test Test Test Test Test</a></td></tr></table></body>
</html>
```

Selenium script
```
driver.Navigate().GoToUrl("http://localhost:8000/main.html");
Thread.Sleep(3500);
driver.SwitchTo().Frame(driver.FindElementById("test"));
driver.FindElementByTagName("a").Click();
```

The problem is that `Element.cpp` sets a property called `hasAbsolutePositionReadyToReturn` with these conditions which later on prevents taking the position of the iframe into account.

**Comment by pranav700** [comment]
I have used this with C# code and found no issues. 
Either you can try with 
driver.FindElement(By.PartialLinkTest("Test")).Click();

**Comment by opxh** [comment]
Hi, facing the same problem with elements like <input>, f.e. this element
<INPUT id=modeByCustomer title="%sometext" CHECKED type=radio value=0 name=mode>
wont be clicked by this code^
new Actions(driver).MoveToElement(option).Click().Build().Perform();// option.Click();
or
element.Click() (where element is IWebElement)
p.s. a variable is found and found correctly, it's get clicked only by executing js like this:
((IJavaScriptExecutor)driver).ExecuteScript("arguments[0].click()", option);
But I'm looking for solving problem without executing any JS.
Any suggestions? Thanks.

**Comment by diemol** [comment]
I'll close this since there was no more input after the comment above, and no logs were provided either. If this is still an issue with the most recent versions, please feel free to reopen or create a new issue.
