### ISSUE TITLE
IEDriver: driver.FindElements return HTTP request timed out after 60 seconds

### ISSUE THREAD

**Issue by sisillV** [SeleniumHQ/selenium#5841]
## Meta -
OS:  Windows Server 2016 DataCenter

Selenium Version:  
Selenium.WebDriver v.3.11.12 C#
Selenium.Support  v.3.11.12 C#

Browser:  
Internet Explorer 11.1198.14393.0

Selenium.WebDriver.IEDriver 3.11.1

## Expected Behavior -
driver.FindElements(byEl) returns list with all matching instance if there is no such element return an empty list

## Actual Behavior -
driver.FindElements(byEl)

 returns:
The HTTP request to the remote WebDriver server for URL http://localhost:61317/session/aaa8ca5c-e6a0-441f-9abc-1c50e9466cab/elements timed out after 60 seconds.'

I don't have problems if I use Chrome driver.

**Comment by mbn217** [comment]
you might need to wait for the list to display . Try to use this method (java) 
	/**
	 * @Purpose This method will wait for an element until
	 * its visible , the default wait is 30seconds
	 * @param element -> the element you want to wait for their visibility
	 * @return boolean value , true if element is present and false if not
	 */
	public static boolean waitForElement(WebElement element) throws IOException {
		//log.info("Waiting for an element in the page...");
		boolean isElementPresent = true;
		try {
			WebDriverWait wait = new WebDriverWait(Driver.getDriver(), 30);
			wait.until(ExpectedConditions.visibilityOf(element));
			//log.info("Element is visible");
			return isElementPresent;
		} catch (Exception e) {
			//log.info("waitForElement method failed! "+ e.getMessage() );
			return !isElementPresent;
		}
	}

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
