### ISSUE TITLE
.NET: AvailableLogTypes throws NullReferenceException if browser is not Chrome

### ISSUE THREAD

**Issue by Dreamescaper** [SeleniumHQ/selenium#5842]
## Meta -
OS:  
Windows 10
Selenium Version:  

Browser:  
Internet Explorer,  Firefox

Browser Version:  
11.0.14393.0

## Expected Behavior -
AvailableLogTypes shouldn't throw NullReferenceException. If logging is not supported by driver - it should return empty collection.

## Actual Behavior -
If browser is IE or firefox - `driver.Manage().Logs.AvailableLogTypes` fails with NullReferenceException.

## Steps to reproduce -
Execute the following line:
```
var logTypes = new InternetExplorerDriver().Manage().Logs.AvailableLogTypes;
```

**Comment by jimevans** [comment]
Resolved in 1156fbc.
