### ISSUE TITLE
driver timeout trying to driver.get(url)

### ISSUE THREAD

**Issue by philippeantonietti** [SeleniumHQ/selenium#5843]
ChromeDriver 2.38.552522 

in Java if you try to get to the page will be waiting for ever and the driver will timeout

expect to load the page and get a screenshot / download file

**driver.get("https://bit.ly/2GEEBKO");**

**Comment by philippeantonietti** [comment]
does not work as well for the link :  https://crwd.fr/2G1Uyuf

**Comment by lmtierney** [comment]
Please report this to chromedriver/chrome https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by philippeantonietti** [comment]
@lmtierney do you believe those links would work with Firefox ?

**Comment by lmtierney** [comment]
I don't know, but I do know that it would be a driver related issue. Also, please do not post shortened URLs to the issue tracker, they could lead to malicious websites and I will not click on them

**Comment by philippeantonietti** [comment]
@lmtierney all right, thanks 

so if someone else needs any information in this regards here will be the issue

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2408
