### ISSUE TITLE
AddonFormatError: Couldn't find manifest.json in modify_headers.xpi

### ISSUE THREAD

**Issue by JannikZed** [SeleniumHQ/selenium#5844]
## Meta -
OS:  
macOS
Selenium Version:  
Selenium server version: 3.11.0, revision: e59cfb3
Browser:  
Firefox 56

We are currently rewriting a selenium based scrapper from python in nodeJS. We need to install a .xpi extension to Firefox 56 from file. We use the python function "add_extension" and everything works. With the same file using node JS and the "addExtensions('modify_headers.xpi')" function we get a strange error documented below.

Browser Version:  
Firefox 56

## Expected Behavior -
Install the modify_heraders application

## Actual Behavior -
throws error:
```
Options {
  map_:
   Map {
     'browserName' => 'firefox',
     'moz:firefoxOptions' => { profile: [Profile], prefs: [Object], args: [Array] } } }
(node:4997) UnhandledPromiseRejectionWarning: AddonFormatError: Couldn't find manifest.json in modify_headers.xpi
```
## Steps to reproduce -
Using the node js API try to install a plugin.

**Comment by barancev** [comment]
NodeJS binding provides special commands to install/uninstall addons in runtime, see installAddon and uninstallAddon methods in [1]

[1] http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Driver.html
