### ISSUE TITLE
IEDriverServer should ignore extension capabilities that it doesn't use.

### ISSUE THREAD

**Issue by DrMarcII** [SeleniumHQ/selenium#5845]
## Meta -
OS:  
Windows Any
Selenium Version:  
3.11
Browser:  
Internet Explorer
Browser Version:  
Any
## Expected Behavior -
If IEDriverServer receives extension capabilities (capabilities with ":" in the name) that it does not understand, they should be ignored.
## Actual Behavior -
IEDriverServer returns an error, e.g.:

"Unable to match capability set 0: google:canReuseSession is an unknown extension capability for IE"

**Comment by jimevans** [comment]
The W3C WebDriver Specification specifically gives implementations like the IE driver the ability to not match on capabilities it does not recognize. Thank you for the issue report, but this one will not be fixed.
