### ISSUE TITLE
/java/client/test/org/openqa/selenium/chrome:chrome failed with exit code: 32

### ISSUE THREAD

**Issue by ArthurGIT2017** [SeleniumHQ/selenium#5846]
I was trying to run Chromedriver tests from SleniumHQ project sources on my Linux box.

I built the project for the target chrome 
./go chrome

then run the Chromedriver tests
./go test_chrome

tests started to run and at some point test failed with the following error message:

TESTS FAILED: 2 FAILURES
Failed target: //java/client/test/org/openqa/selenium/chrome:chrome
FAIL org.openqa.selenium.chrome.ChromeDriverTests
go aborted!
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/buck-out/crazy-fun/0c687e0a193b409b8b59b08b8db36b4177b28eaa/buck.pex test --stamp-build=detect //java/client/test/org/openqa/selenium/chrome:chrome failed with exit code: 32
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/rake-tasks/buck.rb:85:in `block in buck_cmd'
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/rake-tasks/buck.rb:69:in `buck_cmd'
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/rake-tasks/buck.rb:162:in `block in (root)'
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/rake-tasks/buck.rb:88:in `buck_cmd'
/usr/local/google/home/khachatryan/SeleniumHQ/selenium/rake-tasks/buck.rb:158:in `block in (root)'
Tasks: TOP => test_chrome => //java/client/test/org/openqa/selenium/chrome:chrome:run

Chromedriver path is set in the PATH

Could you please help me to understand what is error 32 and why test execution was aborted?

**Comment by barancev** [comment]
No idea what is code 32, but it's normal to have some tests failed, see the test reports for more information.
