### ISSUE TITLE
[Mac OS][C#] Safari Driver - Disable Images

### ISSUE THREAD

**Issue by kenofori** [SeleniumHQ/selenium#5848]
OS: OS X
Selenium Version: 3.11.2
Browser: Safari 11.1

Hi there,

How can i disable rendering of images in SafariDriver to save bandwidth?

Thanks

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
