### ISSUE TITLE
Unable to verify the element in Headless browser

### ISSUE THREAD

**Issue by snehalgajbhiye** [SeleniumHQ/selenium#5850]
## Meta -
OS:  macsOS high Sierra
Selenium Version: 3.8.1
Browser:  
Google Chrome

If the issue is with Google Chrome consider logging an issue with chromedriver instead:
https://sites.google.com/a/chromium.org/chromedriver/help

-->

Browser Version:  65(64-bit)

## Expected Behavior -
It should able to select element as its working fine when open for actual UI.

## Actual Behavior -
Its not able to select any element on the page.

## Steps to reproduce -
@BeforeMethod
    public void setUp() throws Exception {
        ChromeOptions chromeOptions = new ChromeOptions();
        //todo Change your chrome driver path
        System.setProperty("webdriver.chrome.driver",
             "/Users/snehal/Downloads/chromedriver");
        chromeOptions.addArguments("--headless");
        driver = new ChromeDriver(chromeOptions);
    }

    @Test
    public void testIssue() throws Exception {
        // todo change it to test html page
        driver.get("https://stag.furlenco.com");
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(
                ExpectedConditions.presenceOfElementLocated(By.xpath("//*[text='Bengaluru']")));
        System.out.println(
                "Label text : " + driver.findElement(By.xpath(("//*[text='Bengaluru']"))).getText());
    }

}

**Comment by pranav700** [comment]
You can use below xpath to get the element. For eg as your code is locating Bengaluru so

//div[contains(@class, 'Bengaluru') and text()='Bengaluru']

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
