### ISSUE TITLE
Nightwatch does not work with firefox on selenium grid 3.7+

### ISSUE THREAD

**Issue by metareven** [SeleniumHQ/selenium#5851]
How to reproduce:

Install nightwatch v 0.19.20

Run docker-compose up with the following docker-compose.yml file:

```
seleniumhub:
  image: selenium/hub:3.11
  ports:
    - 4444:4444
  environment:
    - GRID_TIMEOUT=10

firefoxnode:
  image: selenium/node-firefox:3.11
  ports:
    - 5900:5900
  links:
    - seleniumhub:hub
```

Run any test using a remote webdriver with the following desiredCapabilities:
```
"desiredCapabilities":{
  "browserName": "firefox"
}
```
The test will now crash, claiming to be unable to connect, with an error message akin to this:

```
Error retrieving a new session from the selenium server
 MyCoolTest   Connection refused! Is selenium server started?

 MyCoolTest   { value: 
   { sessionId: '40bc120d-5ce5-4710-ac51-e01b1a61be3a',
     capabilities: 
      { 'moz:profile': '/tmp/rust_mozprofile.j6a6rb2IUrXa',
        rotatable: false,
        timeouts: [Object],
        pageLoadStrategy: 'normal',
        'moz:headless': false,
        'moz:accessibilityChecks': false,
        'moz:useNonSpecCompliantPointerOrigin': false,
        acceptInsecureCerts: false,
        browserVersion: '59.0.2',
        platformVersion: '4.13.0-39-generic',
        'moz:processID': 139,
        browserName: 'firefox',
        platformName: 'linux',
        'moz:webdriverClick': true,
        'webdriver.remote.sessionid': '40bc120d-5ce5-4710-ac51-e01b1a61be3a' } } }
```

We can here see that the sessionID in the response from the request made by nightwatch is inside the value object and not on the top level as Nightwatch expects. I have tried editing the Nightwatch-code to look for the sessionID inside the value object, but all of our tests then fails elsewhere so there seems to be more compatability issues here as all of our tests works just fine when using selenium Grid 3.6.

When using chrome, the sessionID is on the top level of the response instead of being inside the value object

This has to be fixed somehow. Posting the same issue on the Nightwatch github as I am not sure which of you is to blame

**Comment by lmtierney** [comment]
> This has to be fixed somehow. Posting the same issue on the Nightwatch github as I am not sure which of you is to blame

It's nightwatch. They need to update to be `w3c` compatible in order to interact with Firefox and geckodriver

**Comment by metareven** [comment]
Did a request to the selenium grid and node locally and the issue seems to stem from the grid.

GRID:
```
REQUEST:
curl -d '{"desiredCapabilities":{"browserName":"firefox"}}' localhost:4444/wd/hub/session

RESPONSE:
{"value":{"sessionId":"42937f84-53fe-41cf-9b7a-40d3c1aeec99","capabilities":{"moz:profile":"/tmp/rust_mozprofile.v4tnKSYa59Rd","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"pageLoadStrategy":"normal","moz:headless":false,"moz:accessibilityChecks":false,"moz:useNonSpecCompliantPointerOrigin":false,"acceptInsecureCerts":false,"browserVersion":"59.0.2","platformVersion":"4.13.0-39-generic"
```

NODE:
```
REQUEST:
curl -d '{"desiredCapabilities":{"browserName":"firefox"}}' http://172.17.0.3:5555/wd/hub/session

RESPONSE:
{"status":0,"sessionId":"0c122c01-3126-4f67-b293-ae0221a72d97","value":{"moz:profile":"/tmp/rust_mozprofile.edkY0pLpgcxU","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"pageLoadStrategy":"normal","moz:headless":false,"moz:accessibilityChecks":false,"moz:useNonSpecCompliantPointerOrigin":false,"acceptInsecureCerts":false,"browserVersion":"59.0.2","platformVersion":"4.13.0-39-generic","moz:processID":722,"browserName":"firefox","platformName":"linux","moz:webdriverClick":true,"webdriver.remote.sessionid":"0c122c01-3126-4f67-b293-ae0221a72d97"}}
```

**Comment by metareven** [comment]
Looking at the W3C documentation at : https://www.w3.org/TR/webdriver/#new-session it looks like you are the ones who are not W3C-compatible as the grid is supposed to return an object with sessionID at the top level, or am I reading this wrong?

@lmtierney can you point me to the place in the code where this is handled and possibly re-open this issue?

**Comment by lmtierney** [comment]
Please refer to https://www.w3.org/TR/webdriver/#processing-model section `When required to send a response` Item `4`

**Comment by lmtierney** [comment]
Also, please see the long standing issue https://github.com/nightwatchjs/nightwatch/issues/1456

**Comment by lmtierney** [comment]
Also, try talking directly to geckodriver itself. You will see that it is also wrapped in `value`
```
geckodriver
1525270642452	geckodriver	INFO	geckodriver 0.20.1
1525270642460	geckodriver	INFO	Listening on 127.0.0.1:4444
1525270712502	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.ZZAzU3hdmZK5"
```

```
curl -d '{"desiredCapabilities":{"browserName":"firefox"}}' http://127.0.1:4444/session
{"value": {"sessionId":"954d3ba2-35a7-450d-a56c-2279f8eb53da","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"59.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":18082,"moz:profile":"/tmp/rust_mozprofile.ZZAzU3hdmZK5","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.15.0-20-generic","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
```
