### ISSUE TITLE
Unable to open IE 11 using selenium

### ISSUE THREAD

**Issue by NikhilAnadkar** [SeleniumHQ/selenium#5852]
## Meta -
OS: Windows 10
Selenium Version: 3.11.0
Browser: Internet Explorer
Browser Version: 11

Expected Behavior -
With standalone selenium hub & node on Windows 10, IE 11 should launch with the latest IEDriverServer.

Actual Behavior -
The node fails with:

Unable to create new remote session. desired capabilities = Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}], required capabilities = Capabilities [{}]\nBuild info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'\nSystem info: host: '#######', ip: '##.#.##.###', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_171'\nDriver info: driver.version: InternetExplorerDriver

**Comment by abjerstedt** [comment]
That is not enough information to debug the problem.

What version of IEDriver are you using? Are you sure that you have the 32 bit driver installed (considering you are running on a 32 version of WIN10)?

Did you follow: https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

Also - you should probably provide the segment of code that you are using to generate the request. I'm personally unable to get IE 11 working as well, but Its specific to the x64 driver.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
