### ISSUE TITLE
Safari: probably xPath functions contains() and/or text() not work

### ISSUE THREAD

**Issue by rdpanek** [SeleniumHQ/selenium#5853]
## Meta -
OS:  
OSX
Selenium Version:  
3.8.1 and 3.11
Browser:  
Safari Technology Preview Release 54 (Safari 11.2, WebKit 13606.1.13.2)

Hi, any idea why this xpath not function in Safari webdriver? but in chrome is OK.
"//text()[contains(.,'SomeText')]/parent::*"
"//h2[text()[contains(.,'SomeText')]]"
"//h2[contains(text(),'SomeText')]"

but directly in Safari ( open manually Safari > Develop > Show Javascript Console) these xpaths work?
I have suspicious of a faulty implementation feature contains or/and text.

Example test:
it("test step", () => {
  const xpathSelector = "//h2[contains(text(),'SomeText ')]"
  browser.waitForExist(xpathSelector)

  browser.scroll(xpathSelector, 0, -250)
  browser.pause(3000)
  browser.waitForVisible(xpathSelector)
  browser.click(xpathSelector)
})

Commands waitForExist and scroll work correctly, but waitForVisible and click no.

----------------

00:28:19.444 INFO - To upstream: {"using":"xpath","value":"//h2[contains(text(),'SomeText')]"}
00:28:19.448 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":[{"ELEMENT":"node-03AEAF42-A401-4A4B-9C7B-3FC44B660242"}]}
00:28:19.450 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:19.450 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing GET on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20/element/node-03AEAF42-A401-4A4B-9C7B-3FC44B660242/displayed (handler: ServicedSession)
00:28:19.454 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":false}
00:28:19.945 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:19.945 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing POST on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20/elements (handler: ServicedSession)
00:28:19.945 INFO - To upstream: {"using":"xpath","value":"//h2[contains(text(),'SomeText')]"}
00:28:19.949 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":[{"ELEMENT":"node-03AEAF42-A401-4A4B-9C7B-3FC44B660242"}]}
00:28:19.951 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:19.951 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing GET on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20/element/node-03AEAF42-A401-4A4B-9C7B-3FC44B660242/displayed (handler: ServicedSession)
00:28:19.955 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":false}
00:28:20.444 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:20.444 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing POST on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20/elements (handler: ServicedSession)
00:28:20.445 INFO - To upstream: {"using":"xpath","value":"//h2[contains(text(),'SomeText')]"}
00:28:20.449 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":[{"ELEMENT":"node-03AEAF42-A401-4A4B-9C7B-3FC44B660242"}]}
00:28:20.451 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:20.451 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing GET on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20/element/node-03AEAF42-A401-4A4B-9C7B-3FC44B660242/displayed (handler: ServicedSession)
00:28:20.455 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":false}
00:28:20.505 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:20.505 INFO - Handler thread for session C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (safari): Executing DELETE on /session/C0C166C0-B8D1-4B27-96D2-CB44D32CCD20 (handler: ServicedSession)
00:28:20.507 INFO - To downstream: {"status":0,"sessionId":"C0C166C0-B8D1-4B27-96D2-CB44D32CCD20","value":{}}
00:28:20.507 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@6f5093bb
00:28:20.513 INFO - To downstream: A session with id = 'C0C166C0-B8D1-4B27-96D2-CB44D32CCD20' was not found.

-----------------

## The problem

Hi, any idea why this xpath not function in Safari webdriver? but in chrome is OK.
`"//text()[contains(.,'SomeText')]/parent::*"`
`"//h2[text()[contains(.,'SomeText')]]"`
`"//h2[contains(text(),'SomeText')]"`

but directly in Safari ( open manually Safari > Develop > Show Javascript Console) these xpaths work?
I have suspicious of a faulty implementation feature contains or/and text.

## Link to Selenium logs
https://gist.github.com/rdpanek/48bb5dba9d86a9a9308e736a273bec06

## Code To Reproduce Issue [ Good To Have ]
```
it("test step", () => {
  const xpathSelector = "//h2[contains(text(),'SomeText ')]"
  browser.waitForExist(xpathSelector)

  browser.scroll(xpathSelector, 0, -250)
  browser.pause(3000)
  browser.waitForVisible(xpathSelector)
  browser.click(xpathSelector)
})
```
Commands waitForExist and scroll work correctly, but waitForVisible and click no.

```
00:50:46.202 INFO - To upstream: {"using":"xpath","value":"//h2[contains(text(),'SomeText')]"}
00:50:46.205 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":[{"ELEMENT":"node-66B75EB7-F972-4421-BE79-C9688BC2C472"}]}
00:50:46.207 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.208 INFO - Handler thread for session 5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (safari): Executing GET on /session/5490DE85-4B33-4EA7-BCE2-9501EEEA62C8/element/node-66B75EB7-F972-4421-BE79-C9688BC2C472/displayed (handler: ServicedSession)
00:50:46.211 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":false}
00:50:46.308 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.308 INFO - Handler thread for session 5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (safari): Executing DELETE on /session/5490DE85-4B33-4EA7-BCE2-9501EEEA62C8 (handler: ServicedSession)
00:50:46.310 INFO - To downstream: {"status":0,"sessionId":"5490DE85-4B33-4EA7-BCE2-9501EEEA62C8","value":{}}
00:50:46.310 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@61726b5a
00:50:46.312 INFO - To downstream: A session with id = '5490DE85-4B33-4EA7-BCE2-9501EEEA62C8' was not found.
```

**Comment by barancev** [comment]
The provided sample page is written using some other API, not Selenium, it must be a sort of wrapper around Selenium. Please report this issue to the corresponding project.
