### ISSUE TITLE
The suggestions for react js auto suggest input box does not appear when a test is run in IE11 via webdriver

### ISSUE THREAD

**Issue by nitinv0078** [SeleniumHQ/selenium#5854]
**OS**:  Windows 10Pro 64 Bit
**Selenium Web Driver version**: 3.11.2  
**Selenium WebDriver IEDriver version:** 3.11.1
**Browser:**  Internet Explorer 11
**Browser Version:** 11.64.16299.0 (Test runs in 32bit)
**IDE :** Visual Studio 2017
 **Issue:**: If I run automated test using Chrome driver on a react js auto suggest input box then:

1. I can enter the text via send keys without clicking the input box.
2. When I enter a text then suggestions corresponding to the entered text appear.

But when I run same automated test in IE11 then:

1. I can enter the text via send keys only when I click the input box first otherwise not.
2. When text is entered no suggestions appear. If I manually type in the browser controlled by the test then too options appear.

Also if I directly go to the input box manually in IE11 I can see the options.

I can not provide you link to my application since it is an internal application but you can use this url which has same react js auto suggest input component which is used in our application:

**https://codepen.io/moroshko/pen/GEPoQW**

## Expected Behavior -

When an automated test is run on IE11 then in IE:
1. I should be able to enter the text via send keys without clicking the input box.
2. When I enter a text then suggestions corresponding to the entered text appear while running automated test.

## Actual Behavior -

When an automated test is run on IE11 then in IE:
1. I can enter the text via send keys only when I click the input box first otherwise not.
2. When text is entered no suggestions appear. If I manually type in the browser controlled by the test then too options appear.

## Steps to reproduce -

Use link:

**https://codepen.io/moroshko/pen/GEPoQW**

Run an automated test using Chrome Webdriver and enter text 'ja' using send keys then options Java & Java Script will appear.

Run same test in IE11 then you won't be able to enter the text 'ja' until you click the input box first. Once you click the input box then even though the automated test has finished typing the text there wont be any suggestions.

Please note the input box is in a Iframe so you need to switch to the IFrame first. Below are the selectors I used:

        private readonly By _demoIframe = By.CssSelector("iframe[id*=iFrameKey]");
        private readonly By _demoInput = By.CssSelector("input[type=text][role=combobox][placeholder*=Type]");
        private readonly By _suggestionList = By.CssSelector("[role=listbox][class*=suggestions-list]");
        private readonly By _suggestionOption= By.CssSelector("li[role=option]");

Please let me know if you need any other information.

**Comment by sumanthmattapalli** [comment]
Hi @nitinv0078 ,

Did you find any solution for this issue ?

**Comment by nitinv0078** [comment]
Hi @sumanthmattapalli ,

No solution was found for it and no one picked it up here as well. 

Regards
Nitin

**Comment by sumanthmattapalli** [comment]
Thanks for the update @nitinv0078

**Comment by sumanthmattapalli** [comment]
@nitinv0078  I got it working by changing win 64 bit to win 32 bit version

**Comment by diemol** [comment]
I'll close this since there was no more input after the comment above, and no logs were provided either. If this is still an issue with the most recent versions, please feel free to reopen or create a new issue.
