### ISSUE TITLE
Selenium click not working for selenium 3.10

### ISSUE THREAD

**Issue by ShiekhaGB** [SeleniumHQ/selenium#5857]
Selenium click is not working in IE 11. I am using selenium 3.10.0. and 32-bit InternetExplorerDriver exe.
Dependencies used are as - 

desiredCapabilities.setCapability("ignoreProtectedModeSettings", true); desiredCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
desiredCapabilities.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);
desiredCapabilities.setCapability("nativeEvents", true);
desiredCapabilities.setCapability("enablePersistentHover", true);

Can someone please help on this.?

I do not want to use javascript/ actions to click because the same code is being used for chrome. And it would be a rework.

**Comment by jimevans** [comment]
@ShiekhaGB Clicking on elements in IE is not globally broken for all users with all pages. You have not provided enough information to provide you with any assistance. You’ll need to provide a page that demonstrates the issue, or a link to a site that does so. Absent that, there is nothing actionable in this issue report.

**Comment by ShiekhaGB** [comment]
@jimevans Page that I am trying to access cannot be shared as its a project page. 
Please let me know what else I can help you with so that you may look into the issue. 

The same code is working for Chrome 65. I think there is some Internet Explorer dependency which I am missing. Because it was working fine with Selenium 2.53.

Btw, I tried clicking on google search button. Send keys are working fine but it's not clicking the button.

**Comment by luke-hill** [comment]
:point_up: A sample reproduction scenario against google.com will suffice then. If you are saying the button to search isn't working.

If you need a more indepth website. There are a whole host of pages at http://the-internet.herokuapp.com/ - But you *need* to provide a reproduction scenario.

The minimum required is sample code in its entirety (Not a partial method / command), that will allow jim or someone else to copy and run without any (or little), modifications.

**Comment by ShiekhaGB** [comment]
Baaleos said - 

I was also getting this issue, but found that it could be resolved by adding this to the capabilities
I am using InternetExplorerOptions instead of capabilities, but you should be able to get the gist.

               ```
options.EnableNativeEvents = false;
options.UnhandledPromptBehavior = UnhandledPromptBehavior.Accept;
options.EnablePersistentHover = true;
options.IgnoreZoomLevel = true;
options.AcceptInsecureCertificates = true; // #Bug - SeleniumHQ/selenium-google-code-issue-archive#2381
options.IntroduceInstabilityByIgnoringProtectedModeSettings = true;
options.IgnoreZoomLevel = true;
options.EnsureCleanSession = true;


But, I have another question here. Desired Capabilities are used to open a new instance for IE -
_driver.set((RemoteWebDriver) classConstructor	.newInstance(desiredCapabilities));

So, I would need to pass the options to Internet Explorer desired capabilities like we do for chrome.
desiredCapabilities.setCapability(ChromeOptions.CAPABILITY, options)

How can we do the same for IE?
