### ISSUE TITLE
InternetExplorerDriver losing WindowHandles after Navigate().GoToUrl()

### ISSUE THREAD

**Issue by mattridgway** [SeleniumHQ/selenium#586]
### setup
 - Windows 8.1 64bit
 - IE11(v.11.0.19 KB3049563) 64bit
 - Chrome (v.43.0.2357.81m)
 - NuGet package Selenium.WebDriver (v.2.45.0)
 - IEDriverServer.exe (v.2.45.0 - 64bit downloaded not built locally)
 - IEProtectedMode is off
 - HKLM/SOFTWARE/Wow6432Node/Microsoft/InternetExplorer/Main/FeatureControl/FEATURE_BFCACHE exists with a iexplore.exe dword = 0

### code
``` C#
static void Main(string[] args)
{
    //var driver = new OpenQA.Selenium.Chrome.ChromeDriver();
    var driver = new OpenQA.Selenium.IE.InternetExplorerDriver();
    try
    {
        driver.Navigate().GoToUrl("https://www.google.com/");
        driver.FindElementByName("q").SendKeys("FooBar");
    }
    catch(Exception ex)
    {
        Console.WriteLine($"Exception: {ex.Message}");
    }
    finally
    {
        Console.ReadLine();
        driver.Quit();
    }
}
```

### problem
When the code reaches line 8 (driver.FindElementByName) I get a "NoSuchElementException" thrown, with the message "Unable to find element with the name == q". 

### investigation
Looking at driver.WindowHandles before line 8 the count is one, after line 8 the count is 0. It appears that during the navigation the handles are lost.

### what I've tried
 - Adding a Delay (System.Threading.Tasks.Task.Delay(1000).Wait()) between the navigation and findelement in case the page hadn't loaded properly in time. However the resulted in a different exception "NoSuchWindowException" with the message "Unable to find element on closed window".
 - Before the Navigate grabbing the current window handle (var handle = driver.CurrentWindowHandle;) and then using a SwitchTo back to that handle (driver.SwitchTo().Window(handle);) - however this has the exact same NoSuchWindowException as above.
 - Using the ChromeDriver with the exact same code works fine

Our particular environment requires that we test against IE10 + IE11, as such using the ChromeDriver is not a viable workaround

**Comment by jmiller76** [comment]
Is protected mode off in All Zones?

**Comment by mattridgway** [comment]
@jmiller76 - that was exactly it - it wasn't been seen as a trusted site (although I had added it) - turned it on for internet sites too and it worked fine. thank you.
