### ISSUE TITLE
/usr/bin/chromedriver: Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by lijun003** [SeleniumHQ/selenium#5860]
when starting webdriver, "/usr/bin/chromedriver: Syntax error: ")" unexpected" occurred. Anyone knows the reason?

**Comment by pranav700** [comment]
Have you hardcoded this or put the driver.exe file in bin/debug folder ?..

I always put the driver.exe file inside bin/debug folder

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
