### ISSUE TITLE
[rb] Atoms broken or not yet implemented ? 

### ISSUE THREAD

**Issue by janas-sebastien** [SeleniumHQ/selenium#5861]
Hi,

While testing the latest dev version of selenium via capybara in ruby (with firefox), I had an error because in the file

selenium/rb/lib/selenium/webdriver/atoms.rb

In the function

def read_atom(function)
        File.read(File.expand_path("../atoms/#{function}.js", __FILE__))
end

We look for *.js file in a directory that should be called atoms one level higher, but that directory does not exist in the current version of the package.

Is that something still to be implemented, or a bug ? 

Thanks and Regards,

Sébastien

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by janas-sebastien** [comment]
Hello,

I did not manage to recreate the issue by calling the selenium commands directly, only by calling it via capybara. I also posted an issue on their side to see if somebody can find back the actual selenium commands that are used. I'll then post an update here.

At the same time, it's quite obvious from the code I posted in my first message that something is not right. The code searches explicitely in a directory that does not exist. Maybe, with your knowledge, you know how I could force the code to pass by that function ? 

That's my attempt that works in selenium:

require 'selenium-webdriver'

driver = Selenium::WebDriver.for(:firefox)
driver.navigate.to "https://github.com/"
element = driver.find_element(:name, 'q')
element.send_keys "Selenium"
element.submit
puts driver.title
driver.quit

That's the crashing code in capybara

require 'capybara/dsl'
require 'selenium-webdriver'

include Capybara::DSL
Capybara.default_driver = :selenium 
Capybara.javascript_driver = :selenium

visit('https://github.com/')
find("input[name$='q']").set "Test"

Cheers,

Seb

**Comment by lmtierney** [comment]
This is how `expand_path` works. Put a breakpoint there and you'll see:

```
> File.expand_path("../atoms/getAttribute.js", __FILE__)
> <local>/selenium/rb/lib/selenium/webdriver/atoms/getAttribute.js"
```

```
> File.expand_path("../getAttribute.js", __FILE__)
> <local>/selenium/rb/lib/selenium/webdriver/getAttribute.js"
```

**Comment by janas-sebastien** [comment]
Ok, embarassing moment :-)

I finaly found the issue, and the error is mine. I have built the latest version of the gem from the sources, by downloading only the selenium/rb directory.

The problem is that the getattribute file is copied at build time from the selenium/javascript directory, which was missing from me. It is still strange that the build succeeded without error.

Sorry for the waste of time,

Sébastien

**Comment by p0deje** [comment]
No worries, glad you figured it out.
