### ISSUE TITLE
Grid doest not work for Chromium in Selenium 3.11

### ISSUE THREAD

**Issue by WhiteSummeRK** [SeleniumHQ/selenium#5864]
OS:  LINUX
Selenium Version:  3.11
Browser:  Chromium

I've tried to perform a test using Selenium grid with Chromium. The test goes just fine with all other browsers, but i have to test it with chromium.
The test didn't work (didn't even opened chromium when instantiating RemoteWebDriver) in selenium 3.11. But when i remove the 3.11 version one and install Selenium 3.5, the test goes just fine

PS: The test also works when i open my virtual machine (where i m actually running the test) and test it manually (independent of the selenium version).

Browser Version:  65.0.3325.181

Browser Capabilities: 
```
def chromium_caps(browser, platform=None):
    cm_opt = webdriver.ChromeOptions()
    cm_opt.binary_location = '/usr/bin/chromium-browser'
    cm_caps = DesiredCapabilities.CHROME.copy()
    cm_caps.update(cm_opt.to_capabilities())
    cm_caps['browserName'] = browser.lower()
    cm_caps['platform'] = platform
    return cm_caps
```

in Selenium 3.11 the test is expected to go just fine, however it shows an error like this 
 **WebDriverException: Message: Error forwarding the new session cannot find : Capabilities {browserName: chromium, version: }**

**My grid looks like this**
![image](https://user-images.githubusercontent.com/33036566/39711107-1b957e7c-51f5-11e8-9ae3-93b2fd272b79.png)

# REPRO CASE

- use the capabilities provided to instantiate a RemoteWebDriver, using selenium 3.11 and chromedriver 2.38
- try to run any test with `caps['BrowserName'] = 'chromium'`

**Comment by cgoldberg** [comment]
you might need to set `browserName` as "chrome" rather than "chromium".

also, please provide a complete repro case (not just a partial snippet) and specify the version of chromedriver you are using on the remote node.

**Comment by pranav700** [comment]
I think you should use browser name as chrome instead of chromium.

**Comment by WhiteSummeRK** [comment]
Using `browserName` as "chrome" fixed my problem, thank you so much guys :+1:
