### ISSUE TITLE
Unable to create new session in Windows 10 Home

### ISSUE THREAD

**Issue by Sondt88** [SeleniumHQ/selenium#5865]
## Meta -
OS:  Windows 10 Home

Selenium Version:  3.11.0

Browser:  Chrome

Browser Version:  66.0.3359.139

## Steps to reproduce -
- Start driver : java -jar -Dwebdriver.gecko.driver="chromedriver-Windows" "selenium-server-standalone-3.11.0.jar"

- Go to http://localhost:4444/

- Create new session.

![screenshot_4](https://user-images.githubusercontent.com/33948097/39741764-4aef0f5a-52c5-11e8-9e36-6dc1f9b4e925.png)

Please help me to resolve this.

Thank you.

**Comment by lmtierney** [comment]
You're setting the path to geckodriver as chromedriver. Use

```
-Dwebdriver.chrome.driver
```

**Comment by Sondt88** [comment]
The problem still there. 

Do you have any other suggestion?

Thank you.
