### ISSUE TITLE
Selenium webdriver.firefox.port not working

### ISSUE THREAD

**Issue by skiplist** [SeleniumHQ/selenium#587]
We are using a javascript library that relies on user focus and mouse events.  Thus, multiple firefox agents running within a single node interfere with one another, and we have to run single firefox instances within multiple agents instead.  When doing so, we get the following intermittent error:

```
org.openqa.selenium.WebDriverException: Unable to bind to locking port 7054 within 45000 ms
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: '<ip address>', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-36-virtual', java.version: '1.7.0_55'
Driver info: driver.version: FirefoxDriver
Command duration or timeout: 46.30 seconds
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: '<ip address>', ip: '<ip address>', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-58-virtual', java.version: '1.7.0_55'
Driver info: org.openqa.selenium.remote.RemoteWebDriver

    Caused by:
    org.openqa.selenium.WebDriverException: Unable to bind to locking port 7054 within 45000 ms
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: '<ip address>', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-36-virtual', java.version: '1.7.0_55'
    Driver info: driver.version: FirefoxDriver
    Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
    System info: host: '<ip address>', ip: '<ip address>', os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-58-virtual', java.version: '1.7.0_55'
    Driver info: driver.version: FirefoxDriver
```

This appears to be caused by multiple Firefox agents trying to access the same locking port as described in the Firefox agent port locking strategy here:  https://code.google.com/p/selenium/wiki/FirefoxDriverInternals

From reading the documentation here:  https://code.google.com/p/selenium/wiki/FirefoxDriver there appears to be a system property named webdriver.firefox.port that can be used to avoid port conflicts between different agents running on the same box.  After setting this port, the agents continue to fail with the same exception and port number (even though this port should no longer be in use because of the system property being specified).  Further investigation reveals that the code does not seem to honor the property:  https://code.google.com/p/selenium/source/browse/java/client/src/org/openqa/selenium/internal/SocketLock.java?r=1e77c63607a89eb5919f1b4cb8f50f1ade7094bd

There also appears to be some discussion of the issue (with how to recreate it) here:  https://code.google.com/p/selenium/issues/detail?id=7272&can=1&q=webdriver.firefox.port&colspec=ID%20Stars%20Type%20Status%20Priority%20Milestone%20Owner%20Summary

_Note_:  Setting http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/firefox/FirefoxProfile.html#setAlwaysLoadNoFocusLib%28boolean%29 does not allow us to use multiple firefox instances in the same agent.

Affects version: 'org.seleniumhq.selenium:selenium-java:2.45.0'

_This bug was originally posted at:  https://code.google.com/p/selenium/issues/detail?id=8593  but is still a problem, so I have reposted it here._

**Comment by Denis-Iskhakov** [comment]
According to the source code if there are multiple Firefox instances starting and one of them is unfortunate enough to retry all of its locking port checks at the moments while some other instances are starting that unfortunate instance will throw such exception.

You may try to decrease probability of that error by increasing resources available to the system (CPU, IOPS) to speedup browser startups. Or by limiting the amount of concurrently running Firefox instances.

**Comment by skiplist** [comment]
Hi @Denis-Iskhakov,

Thanks for the feedback.  Does this mean there is a race-condition between multiple Firefox instances?   

>If you change its number it will change for all WebDriver instances and you will get the same error but with different locking port number printed in it.

After looking at the code, I could not find where the setting webdriver.firefox.port was used.

**Comment by Denis-Iskhakov** [comment]
> Thanks for the feedback. Does this mean there is a race-condition between multiple Firefox instances?

One type of race condition is possible if different WebDriver instances are running in different JVMs. In that case that instances will compete for the system-wide locking port, but will not respect the JVM-wide synchronized block which guards locking port acquisition. So some unfortunate instance may easily reach the locking port timeout of 45 seconds and throw the exception.

Another type race condition seems to be possible for multiple Firefox instances starting from one JVM. It's because lines 91 - 144 in https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/internal/NewProfileExtensionConnection.java may take longer than 45 seconds for heavily loaded system. If Firefox starting process is taking almost 45 seconds it will start successfully because it is less than starting timeout, but the whole code block at lines 91 - 144 may take longer than 45 seconds, so another instance which is waiting for the lock inside lock() method of SocketLock.java will reach the lock timeout and throw the "Unable to bind to locking port" exception.

> After looking at the code, I could not find where the setting webdriver.firefox.port was used. 
It looks like it's used in NewProfileExtensionConnection.java in lines 92-93. At least in the latest version of source code.

**Comment by barancev** [comment]
`webdriver.firefox.port` is not related to the locking port number. It used to set port where Firefox driver listens on. Locking port is system wide, it must not be changed on per-process (or per-agent) basis.

Later on `webdriver.firefox.port` property was depecated in favour of `webdriver_firefox_port` preference that should be set in FireroxProfile instance passed to FirefoxDriver constructor.
