### ISSUE TITLE
Issues with set_page_load_timeout

### ISSUE THREAD

**Issue by rogerthat94** [SeleniumHQ/selenium#5871]
## Meta -
OS:  
Ubuntu 16.04.4 LTS
Selenium Version:  
3.11.0
Browser:  
GeckoDriver

Browser Version:  
0.20.1 (If I go to help -> about Firefox in the window that opens with GeckoDriver is launched, it says "Firefox 59.0.2")

## Expected Behavior -
I am trying to get the contents on a page when it first loads. If the Javascript on the page hasn't finished running after 10 seconds, I just want to get whatever was loaded. However, set_page_load_timeout does not seem to work reliably. 

## Actual Behavior -
If I call set_page_load_timeout and pass the value 10 the code hangs on the driver.get line after 10 seconds have passed. However if I pass the value 1, it works fine. 

## Steps to reproduce -
I created the following code snippet that demonstrates the problem:
```
driver = webdriver.Firefox(executable_path=<Path to geckodriver executable>)
driver.set_page_load_timeout(10)

try:
    driver.get('https://yahoo.com')
except:
    pass

print("HERE")
print(driver.page_source)
print("END")
```

Note that yahoo.com doesn't finish loading for me in Firefox 59.0.2 on Linux. The page partly loads but the little blue dot on the left of the tab keeps moving back on forth. If Yahoo loads properly for you (as it does for me on Firefox on macOS, you probably won't be able to reproduce this issue using Yahoo.

Is this an actual bug with set_page_load_timeout? If not, is there something that I'm doing wrong? I apologize if this is an issue I should be bringing up with Mozilla. It seemed like a Selenium issue because set_page_load_timeout worked fine with 1 but not with 10.

**Comment by lmtierney** [comment]
This is a geckodriver issue documented here https://github.com/mozilla/geckodriver/issues/1236

**Comment by rogerthat94** [comment]
Thanks for pointing me in the right direction! Sorry I didn't find this myself.
