### ISSUE TITLE
Driver fails to click button when it is out of screen bounds

### ISSUE THREAD

**Issue by johno1985** [SeleniumHQ/selenium#5874]
Windows 10
Selenium Version:  
3.11.0
Browser:  
Firefox 59.0.3 (64-bit)

## Expected Behavior -

I expect the driver to scroll to the position of the button, and click it

## Actual Behavior -

No scrolling occurs, the driver successfully finds the button and seems to successfully click it but nothing happens. No errors occur, the only error that occurs is my test assertion fails because it is expecting an effect of the button click, which did not happen

## Steps to reproduce -
The following markup results in the button rendering beyond the screen boundary of my 15.6" laptop display

`<div class="container content">
		<t:logo></t:logo>
		<h3 class="text-center">Billing Information</h3>
		<form class="form-horizontal"
			action="${pageContext.request.contextPath}/billing-info"
			method="post">
			<div class="form-group row">
				<div class="col-sm-offset-4 col-sm-5">
					<t:formErrors></t:formErrors>
				</div>
			</div>
			<div class="form-group">
				<label for="firstName" class="col-sm-4 control-label">First
					Name</label>
				<div class="col-sm-5">
					<input type="text" name="firstName" class="form-control"
						placeholder="First Name" value="${model.firstName()}">
				</div>
			</div>
			<div class="form-group">
				<label for="lastName" class="col-sm-4 control-label">Last
					Name</label>
				<div class="col-sm-5">
					<input type="text" name="lastName" class="form-control"
						placeholder="Last Name" value="${model.lastName()}">
				</div>
			</div>
			<div class="form-group">
				<label for="email" class="col-sm-4 control-label">Email</label>
				<div class="col-sm-5">
					<input type="email" name="email" class="form-control"
						placeholder="Email" value="${model.email()}">
				</div>
			</div>
			<div class="form-group">
				<label for="addressLine1" class="col-sm-4 control-label">Billing
					Address Line 1</label>
				<div class="col-sm-5">
					<input type="text" name="addressLine1" class="form-control"
						placeholder="Billing Address Line 1" value="${model.addressLine1()}">
				</div>
			</div>
			<div class="form-group">
				<label for="addressLine2" class="col-sm-4 control-label">Billing
					Address Line 2</label>
				<div class="col-sm-5">
					<input type="text" name="addressLine2" class="form-control"
						placeholder="Billing Address Line 2" value="${model.addressLine2()}">
				</div>
			</div>
			<div class="form-group">
				<label for="city" class="col-sm-4 control-label">City</label>
				<div class="col-sm-5">
					<input type="text" name="city" class="form-control"
						placeholder="City" value="${model.city()}">
				</div>
			</div>
			<div class="form-group">
				<label for="state" class="col-sm-4 control-label">State</label>
				<div class="col-sm-5">
					<input type="text" name="state" class="form-control"
						placeholder="State" value="${model.state()}">
				</div>
			</div>
			<div class="form-group">
				<label for="zip" class="col-sm-4 control-label">Zip</label>
				<div class="col-sm-5">
					<input type="text" name="zip" class="form-control"
						placeholder="Zip" value="${model.zip()}">
				</div>
			</div>
			<div class="form-group">
				<label for="country" class="col-sm-4 control-label">Country</label>
				<div class="col-sm-5">
					<input type="text" name="country" class="form-control"
						placeholder="Country" value="${model.country()}">
				</div>
			</div>
			<div class="form-group text-right">
				<div class="col-sm-offset-7 col-sm-2">
					<button type="submit" class="btn btn-primary">Purchase</button>
				</div>
			</div>
		</form>
	</div>`

The following Java code is used to click the button:

`WebElement field = waiter.until(ExpectedConditions.visibilityOf(
				By.xpath("/html/body/div[contains(@class, 'container content')]/form//div[button[contains(text(), 'Purchase')]]//button")));
		field.click();`

When I run the test, pause on a debug, manually scroll to the bottom and then resume, my test passes OK

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by johno1985** [comment]
I have!

**Comment by pranav700** [comment]
can you try with CSSpath aswell ?

**Comment by johno1985** [comment]
Hi Alexei, looks like I just gave you the source markup, apologies.
Here is the markup and resources which will hopefully result in the
'Purchase' button rendering off screen. The field.click() call seems to
execute successfully but the effect of the button click does not take place.

Note, I did not set any dimensions in my driver, the browser window opened
using whatever defaults are set

**Comment by barancev** [comment]
Please create a ready to use sample page using https://jsbin.com/ or a similar service that allows to reproduce the issue, or provide a link to the actual page you have troubles with.

**Comment by barancev** [comment]
@johno1985 Sorry, I can't find the html file with the assets.

I've created a sample page from the html code you sent in the original post, and I wrote that I can't reproduce the issue on this sample page. Can you run the scenario from my comment above, does it fail to scroll and click for you?

Iэму changed windows size in the scenario because the sample page does not require scrolling with default windows size.

**Comment by johno1985** [comment]
If you unzip the package I emailed, you should see a file named 'Launch BI
Billing Information.html' inside the 'New Folder' folder

**Comment by barancev** [comment]
I did not receive any email from you. Please attach the sample page here.

**Comment by barancev** [comment]
Stop mailing to GitHub robot :)
Please attach the sample page here.

**Comment by johno1985** [comment]
Sorry @barancev, I was replying from my email account.
[New folder.zip](https://github.com/SeleniumHQ/selenium/files/2006438/New.folder.zip)

**Comment by bsaylor** [comment]
It looks like it am seeing the same behavior after upgrading to 3.11.0.  Existing test is failing because the button is not visible to be clicked.  The scrolling into view before clicking is not happening.  I tried adding  a scrollToElement() action before performing the click and then it works.

**Comment by johno1985** [comment]
The funny thing is that the driver successfully finds the button, it
'successfully' clicks the button but the button click event does not seem
to fire.

**Comment by johno1985** [comment]
However, when I add a breakpoint to the code, manually scroll the button
into view and then resume, everything works fine

**Comment by barancev** [comment]
It works for me with the provided sample page too.
Please check that you use the latest geckodriver version and update it if needed.
If the issue is still actual you have to report it to geckodriver project [1], because it's responsible for autoscrolling.

[1] https://github.com/mozilla/geckodriver/issues
