### ISSUE TITLE
How to set acceptInsecureCerts in Selenium Node json file or in command line.

### ISSUE THREAD

**Issue by gregall** [SeleniumHQ/selenium#5877]
## Meta -
OS:                            
**Linux, Ubuntu 16.04**
Selenium Version:    
**3.11.0**
Browser:                    
**Firefox 59.x**

## Expected Behavior -
When i declare `acceptInsecureCerts=True` in node.json (configuration file for Selenium Grid Node) it should be respected.
My node config:
``` 
{
  "capabilities":
  [
    {
      "browserName": "chrome",
      "maxInstances": 15,
      "seleniumProtocol": "WebDriver",
      "platform":"MAC",
      "chromeOptions": {
            "args": [
                  "--headless",
                  "--disable-gpu",
                  "--window-size=1024x570",
                  "--no-sandbox"]
      }},
      {
      "browserName": "firefox",
      "marionette": true,
      "version": "59",
      "platform": "LINUX",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "acceptSslCerts": true,
      "javascriptEnabled": true,
      "takesScreenshot": true,
      "cleanSession": true,
      "acceptInsecureCerts": true,
      "webdriver.firefox.profile": "default"
    }
  ],
  "host": "<IP>",
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 15,
  "port": 5511,
  "register": true,
  "registerCycle": 5000,
  "hub": "<HUB_ADDRESS>",
  "nodeStatusCheckTimeout": 5000,
  "nodePolling": 5000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}
```
## Actual Behavior -
Default value for `acceptSslCerts` is always `False` until i declare in my test file:
`desired_capabilities={'moz:firefoxOptions': {'args': ['-headless']}, 'platform': 'LINUX', 'browserName': 'firefox', 'version': '59', 'acceptInsecureCerts': True}`.

Maybe is there different solution for my problem (i don't wan't to edit multiple test files to add to `desired_capabilities` `acceptInsecureCerts`)?

**Comment by gregall** [comment]
Hey,
Can anybody help me, maybe @barancev ? 
I was trying to get help from [geckodriver](https://github.com/mozilla/geckodriver/issues/1267), but this is a selenium case.
Regards :)

**Comment by gabrielstar** [comment]
I ran into the same issue? Has anyone an idea how to fix it ?
