### ISSUE TITLE
Implement `__repr__` for most classes, especially `WebElement`, for much easier debugging 

### ISSUE THREAD

**Issue by cool-RR** [SeleniumHQ/selenium#588]

**Comment by lukeis** [comment]
webelement has it now with b2219e10837dd33d9ada49cbe697bb81a5f3aa28

**Comment by lukeis** [comment]
we're still missing __repr__ in other significant classes, like remote/webdriver.py

**Comment by santiycr** [comment]
@lukeis any other classes you think we should add a __repr__ to?
