### ISSUE TITLE
In Testng.xml one of the class is not executing in the sequence it always executes at last 

### ISSUE THREAD

**Issue by Pradeep1-MK** [SeleniumHQ/selenium#5883]
Iam facing one strange issue.
Iam keeping all test cases in testng.xml and keeping parameter preserve-order= true
but out of 15 test cases one of the test case is present in the middle but it always executes at last.
can i get help from any one??

I have converted xml file as .txt file and attached it.
In that testng.txt file this class  	always executest last. Can you guys help me iam struck with this issue.
<class name="com.jamcracker.testcases.customeManagement.TC007NetworkInterface"></class>

[testng.txt](https://github.com/SeleniumHQ/selenium/files/1991795/testng.txt)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
