### ISSUE TITLE
Documentation for previous versions?

### ISSUE THREAD

**Issue by maximedupre** [SeleniumHQ/selenium#5884]
http://seleniumhq.github.io/selenium/docs/api/javascript/

This seems to be the documentation for the v4.0.0-alpha.1 release. How can I view the doc for v3.6.0?

Cheers!

**Comment by lmtierney** [comment]
You would have to build them yourself.

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
