### ISSUE TITLE
Taking screenshots on SauceLabs using "report" (Geb framework) prevents successful execution

### ISSUE THREAD

**Issue by rnemeth1980** [SeleniumHQ/selenium#5886]
## Meta -
OS:  Windows 10 - SauceLabs

Selenium Version:  3.9.1

Browser:  IE11

Browser Version:  11.103

## Expected Behavior -
Successful test execution while screenshots are taken.
## Actual Behavior -
I experience a strange behavior during test execution using IE11 on Win10.
There is a strange surge, bump, vibration or bounce every couple of seconds.
This strange short vibration is experienced during the whole execution.
This prevents running all our tests using IE11.
The exact same test is running perfectly fine in a k8s environment inside the company using Chrome.
We figured out with SauceLabs Support that if “report” is not used this strange behavior disappears.
EDGE works fine with the same test using “report”.
## Steps to reproduce -
Run tests using the Geb framework (http://www.gebish.org) on IE11 / Windows 10

**Comment by cgoldberg** [comment]
You haven't provided exact steps to reproduce with sample code, or any errors/logs...  I'd suggest creating a detailed issue report report for either Sauce Labs or Geb framework, but I don't see anything actionable here for Selenium maintainers.
