### ISSUE TITLE
Allow custom drivers in the selenium-webdriver Node/JavaScript package

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#5889]
## Meta -
OS:  Windows
Selenium Version:  "selenium-webdriver": "4.0.0-alpha.1"
Browsers:  Firefox (Gecko), Chrome

## Expected Behavior -

In setting up user environments to work on a repository, it would be easier to not have to modify user paths to include downloaded drivers. 

## Actual Behavior -

This doesn't seem to be supported. I couldn't find an explicit mention of doing so in the docs or TypeScript typings.

## Steps to reproduce -

I tried setting my `geckoDriver.exe` as the binary path:

```javascript
import { Builder, WebDriver } from "selenium-webdriver";
import { Options } from "selenium-webdriver/firefox";

(async () => {
    const driver = await new Builder()
        .forBrowser("firefox")
        .setFirefoxOptions(new Options().setBinary("path/to/my/geckoDriver.exe"));

    await driver.get("http://localhost:3000");
})();
```

...but that threw an error:

```
WebDriverError: Process unexpectedly closed with status 1

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
```

**Comment by lmtierney** [comment]
`setBinary` is for the browser binary, not the driver. You can use this to specify the location of the driver https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_ServiceBuilder.html

**Comment by JoshuaKGoldberg** [comment]
Thanks!
