### ISSUE TITLE
Values are Clearing or Trimming while entering text in textbox  using selenium with c#

### ISSUE THREAD

**Issue by SrikanthSamala** [SeleniumHQ/selenium#5893]
During execution, fields like Text Formatted ("__/__/__") and zip code (___-______) and some other fields are auto Clearing when I am using webElement.SendKeys("02/02/2018") or using Keyboard Strokes using Actions . if I am Providing Implicit WaitTime (Thread.Sleep(3000) Sometimes its not clearing but I don't want to give extra waitTime as I am already using Explicit WaitTime using WaitDriver. I tried using latest webdriver. Is there any solution please help me out. 
 
Thanks 
Srikanth Samala

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
