### ISSUE TITLE
GetCookieNamed() return OpenQA.Selenium.WebDriverException

### ISSUE THREAD

**Issue by alvaroguinda** [SeleniumHQ/selenium#5897]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.11.2 Visual Studio
Browser:  
Chrome

Browser Version:  
66.0.3359.139  (64-bit)

## Expected Behavior -
I can get the Cookie identified by the cookie name

## Actual Behavior -
When trying to get the cookie, WebDriverException is raised

## Steps to reproduce -
Access website
Try to read some cookie

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
