### ISSUE TITLE
Node not being registered to hub selenium 3.12.0 (Was passed main parameter '-role')

### ISSUE THREAD

**Issue by Khoosham** [SeleniumHQ/selenium#5898]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.12.0
Browser:  
Chrome
Browser Version:  
66.0.3359.139 (64-bit)

## Expected Behavior -
Node should attach to hub as in selenium version 3.8.1.

## Actual Behavior -
 I am using selenium 3.8.1 version. i have made my own utility to start/stop hub and register node etc...
Currently i am using this command to register the node to the server and this works great.

```
String[] args = { "-role", "node", "-host", host, "-hub", hubURL, "-port", port };
GridNodeConfiguration gridNodeConfiguration = new GridNodeConfiguration();
 JCommander.newBuilder().addObject(gridNodeConfiguration).build().parse(args);
```

The issue i am having is that i have updated to 3.12.0 and the command above does not work.
i get the following error com.beust.jcommander.ParameterException: Was passed main parameter '-role' but no main parameter was defined in your arg class. Like you see above i have already defined the role as node but still the node wont attach. Any help regarding this please ? Thank you.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
