### ISSUE TITLE
Node is not registered in localhost hub using selenium server 3.12.0

### ISSUE THREAD

**Issue by thuanvo191** [SeleniumHQ/selenium#5899]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.12.0
Browser:  
Chrome
Browser Version:
66.0.3359.139 (Official Build) (64-bit)

## Expected Behavior -
Node should register successfully
## Steps to reproduce -
HubConfig:

{
  "host": 127.0.0.1,
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "maxSession": 20
}

NodeConfig:

{
  "capabilities":
      [
        {
          "browserName": "firefox",
          "maxInstances": 20,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "chrome",
          "maxInstances": 20,
          "seleniumProtocol": "WebDriver"
        },
        {
          "browserName": "internet explorer",
          "maxInstances": 20,
          "seleniumProtocol": "WebDriver"
        }
    ],	
  
    "nodePolling":5000,
    "maxConcurrent": 5,
    "cleanUpCycle":2000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 20,
    "port": 5556,
    "remoteHost" : "http://127.0.0.1:5556",
    "register": true,
    "registerCycle": 10000,   
    "hubHost": "127.0.0.1",
    "hubPort": 4444
    
}

I am using selenium 3.11.0 version. I register the node to the hub and this works great.
The issue i am having is that when I change selenium server to 3.12.0 version. I can't register the node to the hub
It show error  "Marking the node http://127.0.0.1:5556 as down: cannot reach the node for 2 tries"
Any help regarding this please ? Thank you.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
