### ISSUE TITLE
Getting [SEVERE]: Unable to receive message from renderer

### ISSUE THREAD

**Issue by sanojqa** [SeleniumHQ/selenium#5901]
chrome=66.0.3359.170
chromedriver=2.38
selenium version: '3.7.1

Getting following error:
================
[1526445895.501][SEVERE]: Unable to receive message from renderer
Exception in thread "main" org.openqa.selenium.WebDriverException: disconnected: Unable to receive message from renderer
  (Session info: chrome=66.0.3359.170)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)

Used Code:
========
	System.setProperty(ChromeDriverService.CHROME_DRIVER_EXE_PROPERTY, "C:\\Users\\sanojs\\Downloads\\chromedriver.exe");
		ChromeDriverService chromeservice = new ChromeDriverService.Builder().build();
		driver = new ChromeDriver(chromeservice);
driver.get("https://www.google.com/");

		driver.findElement(By.id("lst-ib")).click();
		driver.findElement(By.id("lst-ib")).sendKeys("Ralue");

**Comment by barancev** [comment]
Please report this issue to chromedriver project: http://chromedriver.chromium.org/help
