### ISSUE TITLE
Autodownload does not work in headless chrome webdriver

### ISSUE THREAD

**Issue by Rahul9844** [SeleniumHQ/selenium#5902]
When I executed my tests in headless mode; auto download of files does not seem to work. Anyone any idea why it is not working, as I expected it to work.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by lmtierney** [comment]
Also a duplicate of #5159
