### ISSUE TITLE
Every action slow on IE 11 browser in Windows Server 2016 

### ISSUE THREAD

**Issue by pranjal1987** [SeleniumHQ/selenium#5909]
Window : Windows Server 2016
Browser Version:  
IE 11

## Expected Behavior -
Each selenium action should be working normally as expected behaviour

## Actual Behavior -
Actually all the selenium actions like click, sendkeys, gettext are working very slowly like taking atleast 7-8 seconds in between each actions.

## Steps to reproduce -
1. Login to windows server 2016
2. Launch any URL on IE 11 browser using selenium
3. Perform any selenium action

Note: I have tried all the Selenium versions from 2.47.0 to 3.9.0 along with both IEDriverServer.exe for 32 and 64 bit.

**Comment by jimevans** [comment]
Please provide a `DEBUG` or `TRACE` Level log from IEDriverServer.exe that indicates the issue.

**Comment by barancev** [comment]
Closing the issue as there is no requested information provided.
