### ISSUE TITLE
Is there a feature to provide x509 cert and key to login to a site?

### ISSUE THREAD

**Issue by medyagh** [SeleniumHQ/selenium#5911]
I use selenium as a testing framework in [winnaker](https://github.com/target/winnaker), recent spinnaker versions have feature to login using a x509 Cert instead of username/password login.

Is there support for X509 certs in selenium or the webdriver framework?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
