### ISSUE TITLE
Specflow Generator error

### ISSUE THREAD

**Issue by Jenizah** [SeleniumHQ/selenium#5912]
OS:  
Windows 10
Specflow for Visual Studio 2015 version 2017.1.14

Selenium and packages Versions:  
 "NUnit" version="3.6.1" targetFramework="net452" 
"Selenium.Firefox.WebDriver" version="0.16.1" targetFramework="net452"
"Selenium.Support" version="3.4.0" targetFramework="net452" 
"Selenium.WebDriver" version="3.4.0" targetFramework="net452"
"Selenium.WebDriver.ChromeDriver" version="2.38.0" targetFramework="net452"
"Selenium.WebDriver.IEDriver" version="3.4.0" targetFramework="net452"
"SpecFlow" version="2.1.0" targetFramework="net452"
"SpecFlow.Plus.Excel" version="1.4.2" targetFramework="net452"
"SpecRun.Runner" version="1.5.2" targetFramework="net452"
"SpecRun.SpecFlow" version="1.5.2" targetFramework="net452"

Actual Behavior: 

After updating a feature file and rebuilding the solution, the following errors are received. Solution is working before, not sure what happened why it suddenly throws these issues. 

Missing [assembly:GeneratorPlugin] attribute in <path>SpecFlow.Plus.Excel.SpecFlowPlugin.dll
#error TechTalk.SpecFlow.Generator
#error Server stack trace: 
#error    at TechTalk.SpecFlow.Generator.Plugins.GeneratorPluginLoader.LoadPlugin(PluginDescriptor pluginDescriptor)
#error    at TechTalk.SpecFlow.Generator.GeneratorContainerBuilder.LoadPlugin(PluginDescriptor pluginDescriptor, IGeneratorPluginLoader pluginLoader, GeneratorPluginEvents generatorPluginEvents)
#error    at TechTalk.SpecFlow.Generator.GeneratorContainerBuilder.LoadPlugins(ObjectContainer container, IGeneratorConfigurationProvider configurationProvider, SpecFlowConfigurationHolder configurationHolder, GeneratorPluginEvents generatorPluginEvents)
#error    at TechTalk.SpecFlow.Generator.GeneratorContainerBuilder.CreateContainer(SpecFlowConfigurationHolder configurationHolder, ProjectSettings projectSettings)
#error    at TechTalk.SpecFlow.Generator.TestGeneratorFactory.CreateGenerator(ProjectSettings projectSettings)
#error    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
#error    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
#error Exception rethrown at [0]: 
#error    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
#error    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
#error    at TechTalk.SpecFlow.Generator.Interfaces.ITestGeneratorFactory.CreateGenerator(ProjectSettings projectSettings)
#error    at TechTalk.SpecFlow.IdeIntegration.Generator.AppDomain.RemoteAppDomainTestGeneratorFactory.CreateGenerator(ProjectSettings projectSettings)
#error    at TechTalk.SpecFlow.IdeIntegration.Generator.GeneratorServices.CreateTestGenerator()
#error    at TechTalk.SpecFlow.IdeIntegration.Generator.IdeSingleFileGenerator.GenerateCode(String inputFilePath, String inputFileContent, GeneratorServices generatorServices, ProjectSettings projectSettings)
#error    at TechTalk.SpecFlow.IdeIntegration.Generator.IdeSingleFileGenerator.Generate(String inputFilePath, String inputFileContent, GeneratorServices generatorServices, CodeDomHelper codeDomHelper, ProjectSettings projectSettings)

**Comment by barancev** [comment]
Not related to Selenium
