### ISSUE TITLE
Unable accept accept upload folder alert using selenium java while doing upload folder in google drive

### ISSUE THREAD

**Issue by shankarselenium** [SeleniumHQ/selenium#5914]
## Meta -
OS:  
  Windows 10 
Selenium Version:  
Selenium 3.0.11
Browser:  
Chrome 66 and above

![uploadfolderalert](https://user-images.githubusercontent.com/39407134/40233318-1f918830-5ac0-11e8-887c-48e2ceebb3e8.JPG)

Unable accept the upload folder alert using selenium java while doing upload folder in google drive

I have tried to accept the upload folder alert which facing while upload folder in google drive application.. Thanks in advance.

I already tried with Alert functions in selenium.. but it is not working. if anyone face same issue and found the solution then please reply with solution and thanks inadvance

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
