### ISSUE TITLE
"StoreEval" command does not work. "Help"

### ISSUE THREAD

**Issue by cardoson1** [SeleniumHQ/selenium#5920]
## Meta -
OS:  Windows 10

Selenium Version:  Selenium IDE v3.0.1

Browser:  Google Chrome

Browser Version:  Version 66.0.3359.181 (Official) 64-bit

## Expected Behavior -
I am using the "storeEval" command for the following target, "${value1}+${value2}" and using the value "result" ie the variables were expected to receive the values, sum and place in the "result" value.
## Actual Behavior -
Selenium informs that it does not know the command "storeEval", but if I put the "store" command only the value "result" appears the number of variable 1 followed by + and the variable 2.
## Steps to reproduce -
I'm running the following Test:

I am using the following website to test - http://grupovirtuous.com.br

1. Command   open
    Target   /matkids/game.php
    Value

2. Command   click at
    Target   name=name
    Value   85.9

3. Command   type
    Target   name=name
    Value   Cardoso

4. Command   click at
    Target   name=sends
    Value   67.14

5. Command   store text
    Target   //td[2]/font/b
     Value   value1

6. Command   store text
    Target   //tr[2]/td/font/b
    Value   value2

7. Command   click at
    Target   name=response
    Value   19,14

8. Command   storeEval
    Target   ${value1}+${value2}
    Value   result

9. Command   type
    Target   name=response
    Value   ${result}

10. Command   click at
      Target   name=sends
       Value   19,6

11. Command   assert text
      Target   //p[2]/font/b
       Value   You\N hit!!!

All pass, but step 8 fails because Selenium informs that the command "storeEval" is not recognized.

OBS: I'm sorry for the English, because I had to use google translator because I speak Portuguese.
 
Download the .side file and open it using the Selenium IDE for Mozila or Chrome and see how it works.
Link - https://mega.nz/#!XUQXhLjK!-6kTY6s7fjA6KK_uWVDLC7V2Jgr4fVbG8cRzxS7gp04
[Soma_ger.zip](https://github.com/SeleniumHQ/selenium/files/2020834/Soma_ger.zip)

**Comment by lmtierney** [comment]
Please raise an issue to the IDE repo https://github.com/seleniumhq/selenium-ide/issues
