### ISSUE TITLE
Not able to launch any URL on IE11 using Selenium Webdriver 2.53.1 on Windows Server 2016 machine

### ISSUE THREAD

**Issue by anurag2893** [SeleniumHQ/selenium#5923]
I have been trying to execute my test scripts on IE11 using selenium 2.53.1 and Java on Windows Server 2016 machine but it is giving **SessionNotFoundException** , on the other hand, the same code is working fine on IE11 on Windows 8.1. I have added registry key as well as did the required changes in Internet Options. Is there any issue with running scripts on Windows Server or it is as same as executing on Windows 8.1 or Windows 7?

**Exact Issue** org.openqa.selenium.remote.SessionNotFoundException: session null does not exist (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'EC2AMAZ-CCND6VF', ip: '10.252.11.113', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{capabilities={proxy={}, acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0, ie.ensureCleanSession=true, elementScrollBehavior=0, enablePersistentHover=true, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:47243/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ignoreProtectedModeSettings=true}, timeouts={implicit=0, pageLoad=300000, script=30000}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, platformName=windows, setWindowRect=true}, sessionId=83876ead-304d-464b-a7c1-fd13bb53ea75, platform=ANY}]
Session ID: null

**Comment by AutomatedTester** [comment]
That looks like it is creating a session, does the browser start up and do commands execute? is this with selenium Grid?

**Comment by anurag2893** [comment]
Yes browser does start every time but it does't launch any URL and the above mentioned error is being displayed and test fails. It's Selenium Standalone Server.

**Comment by anurag2893** [comment]
Strange part is that the same piece of code is working absolutely fine on Windows 8.1

**Comment by dmitryyu** [comment]
does it use WebDriver grid ? if so - probably it's https://github.com/SeleniumHQ/selenium/issues/5915

**Comment by anurag2893** [comment]
no it doesn't use Selenium grid, I'm running it locally

**Comment by barancev** [comment]
Please retest with the latest Selenium and IEDriverServer version, that is 3.12 at the moment.

**Comment by barancev** [comment]
Closing the issue, vertion 2.53 is two years old, feel free to reopen the issue if it is still actual in the latest 3.x version
