### ISSUE TITLE
can't started the instance of IE11

### ISSUE THREAD

**Issue by sltruman** [SeleniumHQ/selenium#5929]
it looks that IEDriverServer was not listening on specific port.
but I was ready for environment.

Web Driver: latest
System: win 10 64
Browser: IE 11
Driver version: IEDriverServer 3.9 x64

![default](https://user-images.githubusercontent.com/12881971/40340109-f66ee4fa-5daf-11e8-9c06-b8149c9e339a.PNG)

![screenshot from 2018-05-18 17-24-58](https://user-images.githubusercontent.com/12881971/40340115-faf9c42c-5daf-11e8-97c3-d0d465903f14.png)

![2](https://user-images.githubusercontent.com/12881971/40340185-4b41f616-5db0-11e8-8958-dbbe063b8fbe.PNG)

![screenshot from 2018-05-22 11-09-34](https://user-images.githubusercontent.com/12881971/40340266-a3d86e4a-5db0-11e8-9af1-00ee143083d2.png)

**Comment by barancev** [comment]
Please retest with the latest IEDriverServer version, that is 3.12 at the moment.

**Comment by barancev** [comment]
Closing the issue, feel free to reopen it if it is still actual in IEDriverServer version 3.12 or newer.
