### ISSUE TITLE
hubHost option isn`t readable from node.json configuration file

### ISSUE THREAD

**Issue by TreefeedXavier** [SeleniumHQ/selenium#5930]
## Meta -
OS:  
Windows 10 
Selenium Version:  
3.12 
Browser:  
GeckoDriver

## Expected Behavior -
I have a node.json file:
```
{
 "capabilities": 
	[ 
		{
			"browserName": "firefox",
			"platform": "WIN10",
			"maxInstances": 10
		}
	],
	"nodeTimeout":120,
	"port":5558,
	"hubPort":4444,
	"hubHost":"1XX.2X.1X.1XX",
	"nodePolling":2000,
	"registerCycle":10000,
	"register":true,
	"cleanUpCycle":2000,
	"timeout":30000,
	"maxSession":10
}
```
and start node with 
```
java -jar selenium-server-standalone-3.12.0.jar -role node -nodeConfig node.json
```
## Expected Behavior -
Node connected to 1XX.2X.1X.1XX
## Actual Behavior -
Node try connect to localhost instead of 1XX.2X.1X.1XX

When I try java -jar selenium-server-standalone-3.12.0.jar -role node -hubHost 1XX.2X.1X.1XX - it connect properly. As well that node.json file work fine with 3.11 version.

**Comment by barancev** [comment]
Fixed by 517b8b4c296852b7f7cc41cf4f9152c34910c71d, released in version 3.13
