### ISSUE TITLE
When both bean shell and annotation transform is used to select methods to execute, methods with priority attribute set are not executed.

### ISSUE THREAD

**Issue by formynet** [SeleniumHQ/selenium#5931]
## Meta -
OS:  

Selenium Version:  
 
3.5.3
Browser:  

Browser Version:  

## Expected Behavior -
When both bean shell and annotation transform are used to select methods to execute, methods with priority attribute set should be executed as per their priority among the methods selected.

## Actual Behavior -
When both bean shell and annotation transform are used to select methods to execute, methods with priority attribute set are NOT executed at all.

## Steps to reproduce -

0. Set up eclipse -test ng  project with the following:
a. add a method in testng class with priority and any group name. 
b. add another testng class with method with out priority.
1. Add a bean shell method selector to select any group in a testng suite with testng class from step 1.
2. Add a listener class with overridden tranform from IAnnotationTransformer3 that has the same logic as in beanshell method selector to select a method of any group.
3. Execute both testng classes using testng suite.

Expected 
BOth methods with priority and without priority should be executed.

Actual
Only testng class with method with out priority is executed.

**Comment by barancev** [comment]
Not a Selenium issue, send report to TestNG project.
