### ISSUE TITLE
iedriver no longer treats the Windows Security Dialog (login box) as an alert on Windows 10

### ISSUE THREAD

**Issue by james-grant-sbsa** [SeleniumHQ/selenium#5932]
## Meta -
OS:  Win10

Selenium Version:  3.12

Browser:  IE11

Browser Version:  
11.192.16299.0

## Expected Behavior -
The following C# code runs against 32 bit version of IEDriverServer:

`var home = "https://site.under.test.com/"; 
  driver = new InternetExplorerDriver(AppDomain.CurrentDomain.BaseDirectory);

  driver.Url = home;  
  driver.Manage().Window.Maximize();
  driver.Navigate().GoToUrl(home + "secure/");

  var wait = new WebDriverWait(driver, new TimeSpan(0, 0, 30));

  IAlert alertPopUp = wait.Until(ExpectedConditions.AlertIsPresent());
  alertPopUp.SetAuthenticationCredentials(p0, p1);
  alertPopUp.Accept();`

Expectation: Code execution flows to the code that deals with the alert

## Actual Behavior -
Code execution is blocked inside the call to GoToUrl()
## Steps to reproduce -
Run the C# code above on Windows 10 against IE11

**Comment by james-grant-sbsa** [comment]
Confirmed, this is not an issue on Win8.1 or lower.

**Comment by joerg1985** [comment]
The support of authentication dialogs was removed from the java bindings [with this commit](https://github.com/SeleniumHQ/selenium/commit/bdf883bf519e3ab60ac35f9ecaeb37bb5b11c046#diff-ab348a77233142a1627d1fdad15aeca5). 

I am surprised, they are still present in the c# binding, because there is [no support for basic authentication in the webdriver specification](https://github.com/SeleniumHQ/selenium/issues/453).

**Comment by sRajeswari** [comment]
Facing same issue in java binding.  code is hanged on driver.get. URL asks for basic authentication in popup. 
Previously it is handled through 'Alert.SetAuthenticationCredentials' method. 


Code:
System.setProperty("webdriver.ie.driver", driverPath+"IEDriverServer.exe");
driver = new InternetExplorerDriver();	
driver.get("http://xxx.com");

Specification:
OS: Win10 (64 bit)
Selenium Version: 3.13
IEDriver: IEDriverServer_x64_3.13.0
Browser: IE11
Browser Version:11.1088.15063.0

May I know what is work around to handle basic authentication for IE11 in Win10?

**Comment by cgoldberg** [comment]
https://github.com/SeleniumHQ/selenium/issues/6098#issuecomment-401775686

**Comment by sRajeswari** [comment]
@cgoldberg 
Thank you for mentioning reference.  Shall I consider this issue yet to be fixed ? 
Any workaround to handle authentication pop-up now?

**Comment by diemol** [comment]
Consolidating this into #6644
