### ISSUE TITLE
"Element not clickable at point" for material design input field when using IE

### ISSUE THREAD

**Issue by Chraneco** [SeleniumHQ/selenium#5935]
## Meta -
OS:  Windows 10

Selenium Version:  3.12 and IEDriverServer version 3.12

Browser:  Internet Explorer

Browser Version:  11

## Expected Behavior -
Material Design input fields should be clickable with Selenium even if there is a label.
## Actual Behavior -
Exception is being thrown when trying to click on such an element:

`ElementClickInterceptedException: Element not clickable at point (387,70). Other element would receive the click: <label class="mdl-textfield__label" for="sample1">Text...</label>`

## Steps to reproduce -

Please use the following simple HTML file which uses material design:

```
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.teal-red.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</head>

<body>
<form action="#">
    <div>
        <div class="mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="text" id="sample1">
            <label class="mdl-textfield__label" for="sample1">Text...</label>
        </div>
    </div>
</form>
</body>
</html>
```

Please run the following code against it:

```
System.setProperty("webdriver.ie.driver", "<path to driver>");
InternetExplorerOptions ieOptions = new InternetExplorerOptions();
ieOptions.setCapability(CapabilityType.HAS_NATIVE_EVENTS, true);
ieOptions.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, true);
ieOptions.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, false);
ieOptions.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, false);
ieOptions.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, false);
ieOptions.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
ieOptions.setCapability(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, ElementScrollBehavior.TOP);
ieOptions.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.ACCEPT);
ieOptions.setCapability("ie.fileUploadDialogTimeout", 10000);
InternetExplorerDriver driver = new InternetExplorerDriver(ieOptions);

driver.navigate().to("file:///<path to HTML file>");
try {
     Thread.sleep(1000);
} catch (InterruptedException e) {
     e.printStackTrace();
}
driver.findElementById("sample1").click();
driver.quit();
```

You can see that the space of the label is actually covering the input field which is probably why that exception is being thrown, manually I am still able to click on the input field though and Selenium should be able to as well.

**Comment by jimevans** [comment]
Get Microsoft to fix their broken IE implementation of `elementsFromPoint` (prefixed in IE11 as `msElementsFromPoint`), and we can fix the “issue” with the driver. The driver is strictly following the W3C WebDriver Specification for detecting overlapping elements.

**Comment by joerg1985** [comment]
@Chraneco could you retest the bug with the current release (3.13)? 

this bug might be fixed with this commit: https://github.com/SeleniumHQ/selenium/commit/12e772cb0fc87604f19a773e548f4059d4829645

**Comment by diemol** [comment]
I'll close this since the issue went stale and the OP did not provide more feedback after the previous comment.
