### ISSUE TITLE
OFF: help with old webdriver code (Kernel32.java, Windows Job Objects)

### ISSUE THREAD

**Issue by betonetotbo** [SeleniumHQ/selenium#5939]
Sorry about the OFF TOPIC, but I'm desperate and running out of time. 

I created [this question on stackoverflow ](https://stackoverflow.com/questions/50498555/jna-in-windows-auto-terminate-child-processes-using-windows-jobs) to find out what is happening.

My code was based on the Selenium Webdriver [Kernel32.java](https://github.com/pilwon/selenium-webdriver/blob/master/java/client/src/org/openqa/selenium/os/Kernel32.java), I thought someone here could help me.

**Comment by barancev** [comment]
Not related to Selenium. Let SO handle this quesion.
