### ISSUE TITLE
Error handler throwing a KeyError for 'status' when response is "400, Could not proxy command to remote server"

### ISSUE THREAD

**Issue by eduardoreynoso** [SeleniumHQ/selenium#5942]
Selenium version: 3.12
Appium-Python-Client: 0.26
Os: macOS High Sierra 10.16.4
Emulator version: Nexus 5 X Api level 27 8.1 Oreo

This error was found while using Appium but I decided to open it here because appium uses Selenium library and its throwing the exception on `errorhandler.py` line 130:
`status = value["status"]`
The response that I am seeing there is: 
<pre>
{'status': 400,
 'value': '{"value":{"message":"Could not proxy command to remote server. '
          'Original error: Error: read '
          'ECONNRESET","stacktrace":"ProxyRequestError: Could not proxy '
          'command to remote server. Original error: Error: read '
          'ECONNRESET\\n    at JWProxy.proxy$ '
          '(/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)\\n    '
          'at tryCatch '
          '(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)\\n    '
          'at GeneratorFunctionPrototype.invoke [as _invoke] '
          '(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)\\n    '
          'at GeneratorFunctionPrototype.prototype.(anonymous function) [as '
          'throw] '
          '(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)\\n    '
          'at GeneratorFunctionPrototype.invoke '
          '(/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)\\n    '
          'at <anonymous>"}}'}
</pre>

**Comment by barancev** [comment]
errorhandler.py just handled an error that occurs in appium.
Please report this issue to Appium project.
