### ISSUE TITLE
Add capability to disable 'Save your password' message for Edge browser

### ISSUE THREAD

**Issue by ckzgraphics** [SeleniumHQ/selenium#5943]
## Meta -
OS:  Windows 10

Selenium Version:  2.53.0

Browser:  Edge 15 / 16 / 17

Currently there is **no predefined capability to disable '_Save your password_' message for Edge** browser.

Browser Version:  

## Expected Behavior -
There should a some capability which when used would disable 'Save your password' pop up

## Actual Behavior -
There is no such capability

## Steps to reproduce -

1. Open a website which needs login credentials 
2. Provide username
3. Provide password
4. Click login button
5. You will see 'Save your password' pop up displayed on the Edge browser

You can use the script from [this gist](https://gist.github.com/ckzgraphics/2faede4e5fffcd8315cfc591ab08e870) to reproduce the issue

**Comment by jimevans** [comment]
While the Selenium project, via the language bindings, could provide an arbitrary capability name that you could pass to the Edge driver, unless and until the driver itself understood the capability, it would have no effect. Unfortunately, the Selenium project does not produce or maintain the Edge driver executable; Microsoft does. You’ll need to get them to support such a capability before the language bindings should be expected to add it.

**Comment by ckzgraphics** [comment]
HI there,
I have raised an issue with the [Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/platform/) for the same - [#17647317](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17647317/)

Is there another way to handle this situation?

**Comment by p0deje** [comment]
Nope, that's the only way to handle this. Let's wait now.

**Comment by cgoldberg** [comment]
> Is there another way to handle this situation?

@ckzgraphics as a workaround, disable the prompt via Group Policy or registry.

**Comment by ckzgraphics** [comment]
@p0deje - I have not received any update on [Microsoft page](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17647317/)! Nobody has commented on it yet!

@cgoldberg - Thank you for the update, I have tried that on my LOCAL SYSTEM. However, this time I was aiming to **perform execution on [BrowserStack](https://www.browserstack.com/automate)**. Since on the remote machines, I **do not have any access to the system setting** this workaround would not work.

**Comment by rcmedina** [comment]
Another workaround is to open the Edge browser in InPrivate mode.  It won't display the Save Password prompt in InPrivate mode.
DesiredCapapbilities dc = new DesiredCapapbilities();
dc = new DesiredCapabilities.edge();
dc.setCapability("InPrivate", true);

**Comment by diemol** [comment]
The issue link in the MS page does not exist anymore, and also a workaround has been provided. In addition, the flavor of Edge menioned in this issue is not under development anymore.
