### ISSUE TITLE
IE: Clear() call fails for javascript validated text input field

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#5945]
## Meta -
OS:  Windows 10
Selenium Version:  3.11/3.12
Browser: Internet Explorer
Browser Version: 11.431.16299.0

## Expected Behavior -
Calling Clear() on an IWebElement representing a text field should empty the field.

## Actual Behavior -
Calling Clear() on an IWebElement representing a text field does not empty the field.

It appears that this problem only occurs for text fields that have an attached javascript behavior that validates/repopulates the field when it loses focus.  This problem does not occur using the latest ChromeDriver (2.38.0.1), but does with the IEDriver (3.11.0/3.12.0). The IEDriver works correctly at version 3.8.0.

## Steps to reproduce -
C# test:

````
		public void EnterDate_Test()
		{
			var ied = new InternetExplorerDriver();
			var uri = new Uri("c:\\temp\\html\\default.html");
			ied.Navigate().GoToUrl(uri.AbsoluteUri);
			var input = ied.FindElementById("doctor");
			input.Clear();
		}
````

HTML source:

````
<html>
  <head>
    <title>Cloudy with a chance of Brimstone</title>
	<script type="text/javascript">
	  function whosit() {
	    window.document.getElementById("doctor").value = new Date().toLocaleTimeString()
	  }
	  
	  function whatsit() {
	    window.document.getElementById("doctor").value = new Date().toLocaleTimeString()
	  }
	</script>
  </head>
  <body onload="whosit()">
    <h1>Something something</h1>
    <form>
	  <input onblur="whatsit()" id="doctor" type="text"/>
	</form>
  </body>
</html>
````

**Comment by jimevans** [comment]
The Chrome implementation is in error. The IE driver conforms to the W3C WebDriver Specification, which in its algorithm for [clearing a resettable element](https://w3c.github.io/webdriver/#dfn-clear-a-resettable-element) clearly states that the “unfocusing steps” for the element (which includes firing the `blur` event) must be executed. I strongly suspect that the Firefox (geckodriver) implementation behaves as the IE driver does.
