### ISSUE TITLE
Selenium.WebDriver package won't install on C# Universal Windows project (NuGet)

### ISSUE THREAD

**Issue by arroyoc** [SeleniumHQ/selenium#5947]
## Meta -
OS:  Windows 10

Selenium Version:  
Selenium.WebDriver .NET bindings for the SElenium WebDriver API Version: Latest stable 3.12.0
(I have also tried previous versions)

Browser:  
(not relevant)

Browser Version:  
(not relevant)

Summary:
I am attempting to use Selenium.WebDriver in my Visial c# Windows Universal application. However, I have been unsuccessful.
I am getting the following error when trying to install the Selenium.WebDriver .NET bindings for the Selenium WebDriver API through the NuGet Package Manager:
`Package restore failed. Rolling back package changes for 'NameOfApp'`

## Expected Behavior -
I expected to be able to install the selenium webdriver package. This works on my WPF application.

## Actual Behavior -
An error appears reading `Package restore failed. Rolling back package changes for 'NameOfApp'`. Making it seem impossible to install this package.

## Steps to reproduce -
1. Open Visual Studio
2. File > New Project
3. Under Visual C#, Select "Windows Universal"
4. Select "Blank App (Universal Windows)" > Give a valid name for the project > Click OK
5. Select your target versions (I left them default) > Click OK
At this point the project should be completed and opened...
6. Click "Tools" on the top toolbar > NuGet Package Manager > Manage NuGet packages for Solution...
7. Go to the updates tab and make sure all your packages are up to date
8. Go to "Browse"
9. Search for "Selenium.WebDriver" > Click the top one that is by "Selenium Committers"
10. Check the project to install it to > click "Install"
Error will appear

Does anyone know of any workarounds for this? Am I doing something wrong? Is there something being done already to fix this?

**Comment by jimevans** [comment]
Closing this since "Universal Windows" projects are no longer supported, and since now we publish .NET Standard 2.0 compatible libraries. If that type of project does not support .NET Standard 2.0, it will not be possible to use the .NET bindings in that type of project.
