### ISSUE TITLE
Click is Passed But Action is not Performed on element using gecko driver !

### ISSUE THREAD

**Issue by sachinbhatia39** [SeleniumHQ/selenium#5951]
## Meta -
OS:  Windows 10
Selenium Version:  3.12
Browser:  Firefox ?
Browser Version:  60.0.1 (64-bit)

## Expected Behavior -
Element Should Clicked.

## Actual Behavior -
Click Action is not Performed on element

## Steps to reproduce -
Open website https://www.shop.com/ 
Click on Drop down where All Department is by default chosen inside search text box
Click on Drop-down to open drop-down list
click  Cameras Option inside list

Click is Passed but Action is not performed.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
