### ISSUE TITLE
ffOptions.addPreference("browser.link.open_newwindow", 3); doesn't workatall

### ISSUE THREAD

**Issue by jettysoft** [SeleniumHQ/selenium#5955]
Hi Barancev,

I'm facing issue after tried using the following code
FirefoxOptions options = new FirefoxOptions();
options.addPreference("browser.link.open_newwindow", 3);
driver = new FirefoxDriver(options);

with latest version of geckodriver.

Please help me on this.

Thanks

**Comment by joerg1985** [comment]
Hey, 

it looks like you are setting the variable to its default value. This should be the reason why nothing changes.

This settings seems to be limited, if the window is opened by Javascript.
http://kb.mozillazine.org/Browser.link.open_newwindow.restriction

**Comment by jettysoft** [comment]
Thanks for the reply, 
what would be the solution for this issue?

**Comment by cgoldberg** [comment]
> what would be the solution for this issue?

you have yet to describe any issue...
happy to re-open this if you provide the info requested in the issue template.
