### ISSUE TITLE
[Meta] Mark selenium-google-code-issue-archive repo as archived

### ISSUE THREAD

**Issue by nschonni** [SeleniumHQ/selenium#5965]
I landed on https://github.com/seleniumhq/selenium-google-code-issue-archive from an SO link, but I figured it might be good to actual lock/archive the repo to prevent new ones being created there https://help.github.com/articles/about-archiving-repositories/

**Comment by nschonni** [comment]
There are a few other repos in the org that also haven't gottent touch and/or are empty that maybe could be archived:
- https://github.com/SeleniumHQ/regression-tests.github.com
- https://github.com/SeleniumHQ/conference-workshops
- https://github.com/SeleniumHQ/irc-logs
- https://github.com/SeleniumHQ/selenium-maven-release-test
- https://github.com/SeleniumHQ/mobile-spec

**Comment by diemol** [comment]
All repos mentioned have been archived or deleted.
