### ISSUE TITLE
[14596:10928:0531/174034.867:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2  [14452:3972:0531/170507.354:ERROR:install_util.cc(597)] Unable to read registry value HKLM\SOFTWARE\Policies\Google\Chrome\MachineLevelUserCloudPolicyEnrollmentToken for writing result=2

### ISSUE THREAD

**Issue by gittadesushil** [SeleniumHQ/selenium#5966]
## Meta -
OS:  Windows 10
Selenium Version:  3.11.0 
Browser:  Chrome 
Chrome driver: 2.39.562718

Browser Version:  Version 67.0.3396.62 (Official Build) (64-bit)

## Expected Behavior -
Chrome should open smoothly without any error and url has to be navigated

## Actual Behavior -
Chrome browser is getting launched but navigation is not working.
## Steps to reproduce -
Create a chrome driver object and navigate to url.

## Debug log - 
https://gist.github.com/gittadesushil/1c7e49e05316600c3cb9c2ab4dade6ad

**Comment by jimevans** [comment]
Given the output in the gist comes from the chromedriver executable, it seems like this is an issue that should be raised with the chromium project.

**Comment by gittadesushil** [comment]
This is the first error coming:
[14596:10928:0531/174034.867:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2


@jimevans  I did raised the bug with chromium project. Could you please have look into that?
https://bugs.chromium.org/p/chromium/issues/detail?id=848232

**Comment by barancev** [comment]
Closing in favour of the mentioned chromedriver issue

**Comment by ownchoice** [comment]
I fixed it by replacing:

`chrome_options = webdriver.ChromeOptions()`

For:

`from selenium.webdriver.chrome.options import Options
chrome_options = Options()`

**Comment by jarmake** [comment]
I just manually created the missing registry key and it stopped logging that.

**Comment by lortegas** [comment]
Jarmake... How did you do it?

**Comment by gittadesushil** [comment]
Please share the steps to add registry key.

**Comment by AnaLDM** [comment]
Thanks a lot!!!!!!!!!!!!!!!! @jarmake

**Comment by bwuzhang** [comment]
I'm getting a `ERROR:configuration_policy_handler_list.cc(91)] Unknown policy: MachineLevelUserCloudPolicyEnrollmentToken` if I do that. @jarmake

**Comment by jarmake** [comment]
Unfortunately I haven't encountered that problem @bwuzhang so I don't know what to suggest for that.

**Comment by lortegas** [comment]
Thanks @jarmake

**Comment by Parnash** [comment]
Hi All,
 I am facing this error while Run Automation Test Cases from Jenkins. My Jenkins version is 2.121.1 and My cromedriver plugin version in jenkins is 1.2.
     [exec] [27492:17924:0622/103937.330:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2
     [exec] [27492:17924:0622/103937.909:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

Can anyone help regarding this pls...???

**Comment by Michael-M-Judd** [comment]
I looked into other solutions before @jarmake but only that worked for me... My scrapers were working before and I hadn't updated my python selenium nor my chromedriver. Not sure what happened.

**Comment by cgoldberg** [comment]
> Not sure what happened.

most likely your Chrome browser updated itself.

please note that this issue is closed in favor of the chromedriver issue mentioned previously.

**Comment by fmarkos** [comment]
From an elevated command prompt:
reg add HKLM\SOFTWARE\Policies\Google\Chrome /v MachineLevelUserCloudPolicyEnrollmentToken  /t REG_SZ

**Comment by blvckf0x** [comment]
I made the change in registry, and I think that cause a new problem 🥇 
Unable to read VR Path Registry from C:\Users\User\AppData\Local\openvr\openvrpaths.vrpath
not sure if this is the chain ...

**Comment by YousefJadallah** [comment]
After doing the steps metioned by @jarmake , the message was  changes:

[21152:19700:0718/183745.036:ERROR:install_util.cc(597)] Unable to read registry value HKLM\SOFTWARE\Policies\Google\Chrome\MachineLevelUserCloudPolicyEnrollmentToken for writing result=2
[21152:19700:0718/183745.037:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy: MachineLevelUserCloudPolicyEnrollmentToken
[21152:19700:0718/183745.116:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy: MachineLevelUserCloudPolicyEnrollmentToken

**Comment by GaryGwynn** [comment]
all my f# scripts are failing and also getting this error....
Starting ChromeDriver 2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab) on port 53878
Only local connections are allowed.
[19436:22284:0719/080024.016:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy:
[19436:22284:0719/080024.111:ERROR:configuration_policy_handler_list.cc(91)] Unknown policy:

DevTools listening on ws://127.0.0.1:53881/devtools/browser/081f1f56-3e55-4908-b159-bd2cc3863c91

**Comment by YousefJadallah** [comment]
Actually i updated selenium and everything is going fine .

`pip install -U selenium`

**Comment by Prologueyan** [comment]
@YousefJadallah  I update the selenium but still got the problem

**Comment by Yavier28** [comment]
@jarmake Thanks! The solution Worked like a charm and now the driver is closing properly!!

We need to pay attention to those warning messages that appear on the console

**Comment by cawoodm** [comment]
1. For the "Unknown policy" message:
Go to `HKLM\SOFTWARE\Policies\Google\Chrome` and delete all the policies mentioned in your console
2. For the "unable to read" message:
 create the registry value (string) e.g. `MachineLevelUserCloudPolicyEnrollmentToken`
