### ISSUE TITLE
executeAsyncScript blocks other actions from occuring

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#5972]
## Meta -
OS: Windows 10
Selenium Version: selenium-webdriver@4.0.0-alpha.1
Browser: Firefox (GeckoDriver)
Browser Version: 59

## Expected Behavior -

Suppose you have a long-running script injected into the page:

```javascript
const doLongWork = async (browser) => {
    await browser.executeAsyncScript((callback) => {
        setTimeout(callback, 3000);
    });
};
```

...and while this runs, you'd like to do other things:

```javascript
const myActions = async (browser) => {
    const pendingLongWork = doLongWork(browser);
     
    await (await browser.findElement(By.className("myClass"))).click();

    await pendingLongWork;
};
```

I would expect that the existence of a pending `executeAsyncScript` call wouldn't block other actions from occurring in the meantime.

## Actual Behavior -

Other asynchronous WebDriver calls such as `.findElement` and `.click` block until the pending `executeAsyncScript`'s callback is fired.

## Steps to reproduce -

1. Create a new browser object
2. Run the `myActions` method above, including `doLongWork`

## Use case -

For example, https://stackoverflow.com/questions/37271745/is-it-possible-to-observe-postmessages-using-webdriver-js.

Edit: also found https://stackoverflow.com/questions/37052804/selenium-async-script-in-own-thread-blocks-other-scripts?rq=1

It can be useful to poll with long-running scripts for events on the page.

**Comment by barancev** [comment]
It works as designed. executeAsyncScript calls an async script on the browser side, and waits untill callback will be called. It's not async from Selenium point of view. See [1] for full description.

[1] https://w3c.github.io/webdriver/#execute-async-script
