### ISSUE TITLE
[python] throws “ No connection could be made because the target machine actively refused it” error without using quit

### ISSUE THREAD

**Issue by Sreyas-Sreelal** [SeleniumHQ/selenium#5973]
## Meta -
OS:  Windows 10
Selenium Version:  3.6.0
Browser:  PhantomJS 
Browser Version:  2.1.1 (64 bit)
Python : 3.5

## Expected Behavior -
 Shouldn't throw the error as i didn't even used quit() method 
## Actual Behavior -
selenium python throws **“ No connection could be made because the target machine actively refused it”** error even without using quit
## Steps to reproduce -
Use following code to reproduce the problem
```Python
from selenium import webdriver
import time
import os

class Account:
    def __init__(self,client):
        self.client = client
        self.foo()

    def foo(self):
        self.client.get("https://google.com")

class User:
    def __init__(self,id):
        self.id = id

    def search(self,account):
        account.client.get("https://wwww.google.com")


client = webdriver.PhantomJS()
a = Account(client)
a.foo()

while True:
    someid = input("Input id : ")
    u = User(someid)
    u.search(a)
    while True:
        try:
            u.search(a)
            os.system("cls")
            print("Started.... press ctrl+c to stop")
            time.sleep(1)
        except KeyboardInterrupt:
            break
    if input("Search more? (y/n)").lower() == "n":
        break
```
The error :
  

>  No connection could be made because the target machine actively refused it

is been thrown in the second iteration of first while (when i stops inside loop and allow continuation of first loop)

**Log :** [ghostdriver.log](https://github.com/SeleniumHQ/selenium/files/2060963/ghostdriver.log)

**Comment by lmtierney** [comment]
We no longer support PhantomJS. You could try and raise an issue with them as this would be a PhantomJS issue if anything.
