### ISSUE TITLE
SendKeys send wrong command (SHIFT, F2)

### ISSUE THREAD

**Issue by aviarrigo** [SeleniumHQ/selenium#5976]
## Meta
OS: Fedora 
Selenium Version:  3.12.0
Browser:  Firefox Quantum
Browser Version:  58.0.1 (64-bit) , geckodriver 0.20.1

## Expected Behavior

Send_keys  with SHIFT+F2 open Firefox Console on every page
## Actual Behavior -

Send SHIFT+F2  on real webpage seems like send a scroll command, instead on about:config or local page works perfectly

## Steps to reproduce -
open a terminal and execute following python code:

```
import selenium.webdriver
import pdfkit
import time
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

driver = selenium.webdriver.Firefox()

driver.get('http://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html')

time.sleep(1)

# select pdf filename
ac = ActionChains(driver)

# SHIFT+F2 opens dev toolbar

ac.key_down(Keys.SHIFT).send_keys(Keys.F2).key_up(Keys.SHIFT).perform()
time.sleep(0.1)
# command to change print filename
ac.send_keys('pref set print.print_to_filename /home/test2.pdf').send_keys(Keys.ENTER).perform()
time.sleep(5)

# disable dev toolbar
#ac.key_up(Keys.SHIFT).send_keys(Keys.F2).key_up(Keys.SHIFT).perform()

driver.execute_script("window.print()")

```

**Comment by lmtierney** [comment]
Please log any Firefox & Geckodriver issues with Mozilla: https://www.github.com/mozilla/geckodriver

**Comment by barancev** [comment]
Also note that Selenium can't manage dev console.

**Comment by aviarrigo** [comment]
Thanks for your quickly answer (i'm not so quick...). I' noted that Selenium can't manage dev console, but can send keys and this features seems not work correctly

**Comment by barancev** [comment]
Selenium sends key events to the page (or, browsing context), not the system level window.

**Comment by aviarrigo** [comment]
Thanks, I admit that i don't have an in-depth knowledge about Selenium but i've tried send key events to local page and it works perfectly.
