### ISSUE TITLE
Secured cookies aren't returned for IE

### ISSUE THREAD

**Issue by ovixeu** [SeleniumHQ/selenium#5978]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.4
Browser:  
 Internet Explorer 11, IEDriverServer 3.11.0 32 bit

## Expected Behavior -
Return all cookies.
## Actual Behavior -
Secured cookies aren't returned.
## Steps to reproduce -
driver.manage().getCookies()

**Comment by alexlazarciuc** [comment]
Hi @ovixeu 

I just run this sample test on my local and everything works fine. I can get the cookies & attach new cookie too. Bear in mind to you x32 architecture of IE Driver (https://www.seleniumhq.org/download/)

[Test]
        public static void Main()
        {
            IWebDriver driver = new InternetExplorerDriver();
            driver.Url = "https://www.google.com";
          
            Thread.Sleep(2000);
            var instance = (RemoteWebDriver)driver;
            var webDriver = instance.Manage();
            var cookies = webDriver.Cookies.AllCookies;

            Cookie cookie = new Cookie("test", "test1", null, null,null);
            driver.Manage().Cookies.AddCookie(cookie);

        }

**Comment by diemol** [comment]
I'll close this since there was no more input after the comment above, and no logs were provided either. If this is still an issue with the most recent versions, please feel free to reopen or create a new issue.
