### ISSUE TITLE
Each testcase in a testsuite is opening a new window for execution instead of continuing the execution in the previously opened window

### ISSUE THREAD

**Issue by chaitramv** [SeleniumHQ/selenium#598]
1. I am running the selenium-standalone-server-2.45.0 on my machine (Ubuntu-14.04).
2. Configured selenium ide to play the test cases (previously recorded in firefox) in chrome (i.e Options -> options -> webdriver -> enabled webdriver playback, chrome)
3. The testsuite consists of 3 testcases. When the testsuite was played, each testcase opened a new chrome browser window for execution. But expected was that all 3 testcases had to be executed in the window opened by the first testcase.(As happens when executed in firefox).

Is it possible to execute all the 3 testcases in the same window opened by the 1st testcase? If yes, what changes i have to do in configuration or in my selenium ide command?

**Comment by Akash17101992** [comment]
Limitations

This is merely the first step in providing full WebDriver playback. Bugs and limitations are to be expected. I am aware of the following limitations:-

    Multiple browser windows will be opened and will remain open.
    Test may not pause or exit on errors.
    An alert message may pop up for conditions that I have not encountered in my testing.
    Executing a single command is not yet supported.
    Highlighting a locator using the Find button may not work.
    The timeout settings are ignored.
    Screenshots may not work.
    User extensions and plugins may not work.

**Comment by samitbadle** [comment]
Expect this feature in the next release. I am currently trying to get Selenium IDE addon signed by Mozilla so you can still use it when Firefox 40 is released.

**Comment by Ashwinpuri** [comment]
Hi, Is this issue been fixed yet or not. Kindly let me know the way out as am experiencing the same. Thanks.

**Comment by barancev** [comment]
Selenium IDE development has been discontinued. No more new features and no bug fixes. From Firefox 55 onwards, Selenium IDE will no longer work [1]. The last supported version is Firefox ESR 52.

Yes, we've started a project to develop a new tool that should replace Selenium IDE. Follow #4406 for the progress.

Sorry this issue has not beed properly and timely addressed, and thank you for submission!

[1] https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/
