### ISSUE TITLE
Selenium randomly hangs on getPageSource()

### ISSUE THREAD

**Issue by obykoo** [SeleniumHQ/selenium#5981]
## Meta -
OS:  
Windows 7 32 bit

Selenium Version:  
3.12.0 or previous versions 3.8.1

Browser:  
Chrome

I do not know if this issue is selenium or chromedriver releated, because I have tried different versions of chromedriver and selenium and also different chrome versions and it did not help.

Browser Version:  
63.0.3239.108 (32-bit)

## Expected Behavior -

getPageSource() should return page source

## Actual Behavior -

test randomly (like once-twice per 24 hours) hangs on getPageSource() without any Exception thrown

## Steps to reproduce -
```
event.log("Getting page source");
String source=broswer.getPageSource(); ///Hangs here, does not go to next step...
event.log("Getting page source, time = "+stopwatch.time());
event.log("Creating JSOUP doc");
Document doc=Jsoup.parse(source,broswer.getCurrentUrl());
event.log("Creating JSOUP doc, time = "+stopwatch.time());
```

**## Is there way I can make getPageSource() at least timeout?** 

I can not provide website due to my employer. Sorry.

**Comment by p0deje** [comment]
Can you enabling chromedriver logs and attach one to see what's going on there?

**Comment by barancev** [comment]
Closing the issue as there is no information provided to act on.
