### ISSUE TITLE
Missing ServiceBuilder equivalent for IE (Node)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#5983]
## Meta -
OS: Windows 10
Selenium Version: selenium-webdriver@4.0.0-alpha.1
Browser:  Internet Explorer
Browser Version:  11

## Expected Behavior -

I'd like to configure a custom driver location for `IEDriverServer.exe`. Other browsers export a `ServiceBuilder` you can use:

```javascript
const seleniumFirefox = require("selenium-webdriver/firefox");

builder.setFirefoxService(new seleniumFirefox.ServiceBuilder("./path/to/geckoDriver.exe"));
```

## Actual Behavior -

No equivalent `ServiceBuilder` class or method that allows a custom path to `IEDriverServer.exe` is provided.

[`locateSynchronously`](https://github.com/SeleniumHQ/selenium/blob/e060906bbdbd954da21883f7f6fdd71cb48db3dd/javascript/node/selenium-webdriver/ie.js#L311) only allows checking for the user's path.

Relevant: https://stackoverflow.com/questions/35587825/internet-explorer-driver-without-the-need-of-path-variable

**Comment by jleyba** [comment]
I could throw something together, but I don't have access to Windows to properly test the change. I would happily review a pull request though :)
