### ISSUE TITLE
Missing .headless() equivalent for Edge (Node)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#5984]
## Meta -
OS: Windows 10
Selenium Version: selenium-webdriver@4.0.0-alpha.1
Browser: Edge
Browser Version: *

## Expected Behavior -

Chrome and Firefox allow a `.headless()` method to indicate the browser should run in headless mode.

## Actual Behavior -

[`edge.js`](https://github.com/SeleniumHQ/selenium/blob/e060906bbdbd954da21883f7f6fdd71cb48db3dd/javascript/node/selenium-webdriver/edge.js) has no mention of "headless" at all.

**Comment by lmtierney** [comment]
Can you provide documentation on how to run Edge in headless mode?

**Comment by lmtierney** [comment]
This is the only thing I could find on the topic. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14057655/

**Comment by JoshuaKGoldberg** [comment]
Heh, looks like I have to complain elsewhere. 😊😢
