### ISSUE TITLE
Documentation correction for SSL

### ISSUE THREAD

**Issue by bethesque** [SeleniumHQ/selenium#5986]
https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#ssl-certificates

I could not get the given code example to work

```ruby
capabilities = Selenium::WebDriver::Firefox::Remote::Capabilities.firefox(accept_insecure_certs: true)
driver = Selenium::WebDriver.for :firefox, desired_capabilities: :capabilities
```

This was the code that I got running (different module for Capabilities and corrected reference to `capabilities` local var.)

```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(accept_insecure_certs: true)
driver = Selenium::WebDriver.for :firefox, desired_capabilities: capabilities
```

**Comment by lmtierney** [comment]
Fixed, thanks!

**Comment by bethesque** [comment]
Thanks for the quick response. The second line needs fixing too. `desired_capabilities: :capabilities` should be `desired_capabilities: capabilities`

**Comment by lmtierney** [comment]
Whoops sorry. Fixed again, thanks!
