### ISSUE TITLE
Not able to capture full screenshot after scrolling down on ubuntu using ashot

### ISSUE THREAD

**Issue by swaradewarde** [SeleniumHQ/selenium#5992]
Hi guys,
I need to take full screenshot of a web application by scrolling down. I have used Ashot to achieve same, check below code

final Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportRetina(100,0,0,2)).takeScreenshot(driver);
        final BufferedImage image = screenshot.getImage();
        try {
            ImageIO.write(image, "PNG", new File(fileNameToCopy));
        } catch (IOException e) {
            e.printStackTrace();
        }

This code is working well on my local (mac osx) however when i am running same code on jenkins server (ubuntu) the screenshot captured has some background black spaces. Attaching screenshots taken on both local and on jenkins server.

Could you pls tell me what could be the issue.

Thanks in advance.

environment details with screenshots mentioned below.

## Meta -
jenkins box details:
OS:  Linux version 4.4.0-1055-aws  (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
Selenium Version:  3.5.3
Browser:  Mozilla Firefox 54.0
geckodriver: geckodriver-v0.17.0-linux64.tar.gz
![jenkins_ooredommappcataloguepageandroid_screenshot 1](https://user-images.githubusercontent.com/39795588/40960744-4cdcedaa-68be-11e8-83d3-34b4c26351f8.png)

local machine details
OS:  macOS Sierra 
Selenium Version:  3.5.3
Browser:  Mozilla Firefox 54.0
geckodriver: geckodriver-v0.17.0
![local_ooredommappcataloguepageandroid_screenshot](https://user-images.githubusercontent.com/39795588/40960769-57db337e-68be-11e8-9b70-93b1e1e5dd3c.png)

**Comment by barancev** [comment]
Please report this issue to Ashot, it's not developed by Selenium team.

**Comment by swaradewarde** [comment]
ok thank you barancev (Y)
