### ISSUE TITLE
Can't find element after update to any new version.

### ISSUE THREAD

**Issue by MioOgbeni** [SeleniumHQ/selenium#5995]
## Meta -
OS:  
 Windows 10 1803 17134.48
Selenium Version:  
3.11.1, 3.11.2 and more
AppiumDriver Version:  
3.0.0.2
AppiumServer Version:  
1.8.0

Hi, by now I have used Selenium version 3.11.0, but now I have decided to update and found out that from version 3.11.2 I can not find a single element, any attempts always end up with an error.

Is there someone who can help me, or say what is wrong?

Here is my appium log https://gist.github.com/MioOgbeni/c3f647a50e5dbd13ed94fefbecf39c18

I also asked on Appium Git, but i think that this is error in selenium. 
https://github.com/appium/appium/issues/10806

**Comment by barancev** [comment]
Please provide the log collected with version 3.11.0 (that works well) so we'll be able to compate them.

**Comment by MioOgbeni** [comment]
Theres logs of one of my tests, first test is running on version 3.11.0 and second is on version 3.11.2. https://gist.github.com/MioOgbeni/01431e35efb7fa42b5303107d2ba09e7

**Comment by barancev** [comment]
The element can't be found by version 3.11.0 too:
https://gist.github.com/MioOgbeni/01431e35efb7fa42b5303107d2ba09e7#file-activityadd_v3_11_0-txt-L859-L873

But there is a difference. In version 3.11.0 appium always uses [MJSONWP] legacy protocol. In version 3.11.2 appium attempts to swicth to new W3C protocol, but falls back to the legacy one:
https://gist.github.com/MioOgbeni/01431e35efb7fa42b5303107d2ba09e7#file-activityadd_v3_11_2-txt-L7

At the same time, you can see lots of [W3C] marks, that means it uses W3C protocol contrary to the "fallback" message.

But the most interesting part is the command where it can't find an element:
https://gist.github.com/MioOgbeni/01431e35efb7fa42b5303107d2ba09e7#file-activityadd_v3_11_2-txt-L370-L381
It passes a request using W3C protocol, but attempts to handle error response using legacy protocol, that causes a failure.

I suppose this issue should be reported to Appium project, they should use either W3C protocol or legacy one but not a mix of them.
