### ISSUE TITLE
Update commons-exec-1.1 jar dependecy

### ISSUE THREAD

**Issue by spatelamp** [SeleniumHQ/selenium#600]
Hello,

Please update the commons-exec-1.1 jar dependency to latest stable version. The current 1.1 version is not included in maven-metadata.xml for commons-exec, probably signifying they don't want others to use this version. Also 1.1 is pretty old (2007), it would be nice to have latest lib.

Please have this as priority. 

http://mvnrepository.com/artifact/org.apache.commons/commons-exec

<b>Maven-metadata.xml content

```
<?xml version="1.0" encoding="UTF-8"?>
-<metadata>
     <groupId>org.apache.commons</groupId>
     <artifactId>commons-exec</artifactId>
     -<versioning>
            <latest>1.3</latest>
            <release>1.3</release>
           -<versions>
                 <version>1.0</version>
                 <version>1.0.1</version>
                 <version>1.2</version>
                 <version>1.3</version>
           </versions>
     <lastUpdated>20141106034814</lastUpdated>
     </versioning>
</metadata>
```

Thank You.

**Comment by barancev** [comment]
https://github.com/SeleniumHQ/selenium/tree/master/third_party/java/commons-exec
To be released in 2.46
