### ISSUE TITLE
Selenium Weddriver 3.12.1 : throw the error on the line ExecuteScript("return jQuery.active == 0")

### ISSUE THREAD

**Issue by toraylin** [SeleniumHQ/selenium#6001]
Hi I upgrade the latest Selenium WebDriver and Chrome driver 2.39 in VS 20015 .  
Selenium.WebDriver 3.12.1
Selenium.Support: 3.12.1

However, it throws the error on the following line.
  bool isAjaxDone = ((bool)((IJavaScriptExecutor)_driver).ExecuteScript("return jQuery.active == 0"));

Error message: 
=OpenQA.Selenium.WebDriverException : unknown error: jQuery is not defined
(Session info: chrome=67.0.3396.62)
(Driver info: chromedriver=2.39.562718 (9a2698cba08cf5a471a29d30c8b3e12becabb0e9),platform=Windows NT 10.0.16299 x86_64)

Go back to Selenium.WebDriver 3.11.2 ,Selenium.Support: 3.11.2 and it does not have any issue.

Any idea? Is it the known issue in Selenium.WebDriver 3.12.1?

Thanks,

Ray

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
