### ISSUE TITLE
Running Selenium headless on Ubuntu server using Python

### ISSUE THREAD

**Issue by Six-wars** [SeleniumHQ/selenium#6002]
I've been trying to get a Django test that uses selenium to run using firefox on a server getting issues running it headless. StackOverflow post [here](https://stackoverflow.com/questions/50719283/selenium-python-cant-connect-with-headless-firefox).

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
