### ISSUE TITLE
Selenium WebDriver java - SPA Problem

### ISSUE THREAD

**Issue by YakirSA** [SeleniumHQ/selenium#6003]
## Meta -
OS:  

Selenium Version:  3.12.0

Browser:  Chrome, Firefox, Edge, IE

Browser Version:  latest

## Description -
I'm doing my automated testing using java on Intellij IDEA.
I'm working on an SPA(single page application).
During one of my tests where I was trying to click on a found element, it seemed not to able to find the element and press on it which made it send back an exception from the next command line because it could get to the new pop up box where the next element exists.
It seems like it skips on this line of code...
I tried to make it wait until the driver would locate the element, also explicit wait and Thread.sleep but nothing seemed to work.
I was wondering maybe selenium webdriver isn't what I should use on a SPA.
I can't understand what's wrong about it! any help would be great.

## The Bug -
org.openqa.selenium.WebDriverException: unknown error: Element </div _ngcontent-c24="" class="to-box" style="cursor:pointer">...</div> is not clickable at point (888, 400). Other element would receive the click: <input _ngcontent-c24="" class="spy ng-untouched ng-pristine ng-valid" name="subject" placeholder="Subject" type="text" ng-reflect-name="subject" ng-reflect-model=""/>
  (Session info: chrome=66.0.3359.181)

The '/' at the start of the < and at the end of it is so it would be shown.

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
