### ISSUE TITLE
driver.findElements() can not get right result when called continuously

### ISSUE THREAD

**Issue by sanqingshan** [SeleniumHQ/selenium#6004]
## Meta -
OS:  win7

Selenium Version:  3.12.0

Browser:  Firefox

Browser Version:  60.0.1

## Expected Behavior -
driver.findElements() not get right result when called continuously;
## Steps to reproduce -

when call like this the second result is same to first:
List<WebElement> uniqueTextXpathWebElements = driver.findElements(By.xpath(uniqueTextXpath));
		List<WebElement> containsTextXpathWebElements = driver.findElements(By.xpath(containsTextXpath));
		logger.debug("find {} element by containsTextXpath:{}",containsTextXpathWebElements.size(),containsTextXpath);
		logger.debug("find {} element by uniqueTextXpath:{}",uniqueTextXpathWebElements.size(),uniqueTextXpath);

when call like this the second result is right

List<WebElement> uniqueTextXpathWebElements = driver.findElements(By.xpath(uniqueTextXpath));
		SeleniumUtil.pause(Context.getSleepTime());
		List<WebElement> containsTextXpathWebElements = driver.findElements(By.xpath(containsTextXpath));
		logger.debug("find {} element by containsTextXpath:{}",containsTextXpathWebElements.size(),containsTextXpath);
		logger.debug("find {} element by uniqueTextXpath:{}",uniqueTextXpathWebElements.size(),uniqueTextXpath);

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sanqingshan** [comment]
String uniqueTextXpath = "//" + tag + "[text()='" + keyword + "']";
String containsTextXpath = "//" + tag + "[contains(text(),\"" + keyword + "\")]";
List<WebElement> uniqueTextXpathWebElements = driver.findElements(By.xpath(uniqueTextXpath));
//this result should be 2 size data,but actiuelly it was just one data as same as previous result;
//but when called a pause after previous,it can get 2 size data;
List<WebElement> containsTextXpathWebElements = driver.findElements(By.xpath(containsTextXpath));

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
