### ISSUE TITLE
Fix .npmignore 

### ISSUE THREAD

**Issue by SimonSchick** [SeleniumHQ/selenium#6005]
You are currently shipping various redundant files such as tests, examples etc.

Please consider not shipping files that are non essential for the package to function.

Prime candidates are `test` `examples`, `lib/test`.

**Comment by GitSage** [comment]
Also `.idea`, `ide.iml`, `selenium.iml`. Looks like @shs96c and @barancev use IntelliJ :)

**Comment by SimonSchick** [comment]
FYI: an alternative is specifying `files` in the `package.json`

**Comment by diemol** [comment]
Seems this was already fixed https://github.com/SeleniumHQ/selenium/blob/2d53be8ddb4b17226dc1c1dbcd9045a144ae8f8c/javascript/node/selenium-webdriver/.npmignore#L9-L8
