### ISSUE TITLE
Error compilation

### ISSUE THREAD

**Issue by leocotes** [SeleniumHQ/selenium#6006]
Hello guys,
 I'm a beginner in python, I would like to use selenium to send msg by web whatsapp, but i don't know to solve this error.

OS - Win10x64
Python 3.6
Pycharm Community 2018.1.4
![sem titulo](https://user-images.githubusercontent.com/23029893/41163366-d8128ee6-6b0e-11e8-8134-c9849022edac.png)

Thank everyone!

**Comment by lmtierney** [comment]
How did you install the python library? Can you show the directory it is installed?

**Comment by leocotes** [comment]
I installed by cmd

pip install selenium

![2](https://user-images.githubusercontent.com/23029893/41164037-98982f58-6b10-11e8-9e2b-e18bdbafceeb.PNG)
![3](https://user-images.githubusercontent.com/23029893/41164044-9c420624-6b10-11e8-808e-c5d4efd43a96.PNG)

**Comment by lmtierney** [comment]
If you installed it via pip, then it doesn't look like it installed correctly... Are you sure it fully installed? Maybe you're running into #5907 ?

**Comment by leocotes** [comment]
Take a look, i think that is ok.

![1](https://user-images.githubusercontent.com/23029893/41165328-bf021d40-6b13-11e8-92b1-1d9e4bdf0623.PNG)
![2](https://user-images.githubusercontent.com/23029893/41165332-c2276d18-6b13-11e8-9170-5b039b1ba601.PNG)

**Comment by cgoldberg** [comment]
your first screenshot shows python trying to run inside a virtualenv (venv), but you are installing selenium outside of the virtualenv.  To use a virtualenv, install python *after* you activate your virtualenv.

**Comment by leocotes** [comment]
Thank you @cgoldberg and @lmtierney 

Now works perfect! I needed to put the patch to works.

chromedriver = r"patch of the exe"
driver = webdriver.Chrome(chromedriver)

Thanks!!!!
