### ISSUE TITLE
error: cannot access Killable

### ISSUE THREAD

**Issue by achyutha526** [SeleniumHQ/selenium#6007]
Hi,

The code compilation is failing with "error: cannot access Killable" at the line 
class FirefoxWebDriver extends FirefoxDriver{
......

We have upgraded to Selenium 3.11 from 3.3.1. We are trying to run tests on chrome browser configured with selenium grid using Docker. I found that Killable class was removed. Kindly suggest if I need update any code changes.

Thanks.

**Comment by barancev** [comment]
You just have to stop using Killable wherever you use it.
