### ISSUE TITLE
Issue when nativeEvents:false capability is set

### ISSUE THREAD

**Issue by ppanuganti** [SeleniumHQ/selenium#6009]
OS:  
**Windows 7, 8**
Browser:  
 **Internet Explorer 9.0, 10.0**

Hi,

We are facing an issue when **_nativeEvents:false_** capability is set for Windows/IE combination.

Problem:
We have a scenario where we need to click on a button which we are able to perform only when nativeEvents:false capability is set. By setting this capability we are facing an issue at succeeding steps in the execution where we are supposed to handle an alert. we are unable to get the response from that alert when this capability is set and the execution aborts.
Tried by removing the nativeEvents:false capability and able to handle the alert but the click on the button is failing.

Please suggest if there is any way to handle this kind of issues where both the click and alert can be handled.

Thanks & Regards

**Comment by jimevans** [comment]
@ppanuganti You neglected to mention the version of the IE driver you're using, and you've provided no way to reproduce the issue (which would include a sample HTML page that reproduces the click "not working") for fixing the click for native events.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
