### ISSUE TITLE
'UnreachableBrowserException: Error communicating with the remote browser. It may have died'  when using ExpectedConditions

### ISSUE THREAD

**Issue by funnybutrandom** [SeleniumHQ/selenium#6010]
## Meta -
OS:  Linux 
Selenium Version:  3.12.0
Browser:  Chrome Driver 2.39
Browser Version:  67.0.3396.62

## Expected Behaviour
When calling the following method:
`    public void fluentWaitForElementToBeStale(WebElement element) {
        FluentWait<WebDriver> wait = (new FluentWait<>(webdriver)).withTimeout(30, TimeUnit.SECONDS).pollingEvery(1, TimeUnit.MILLISECONDS).ignoring(TimeoutException.class);
        wait.until(ExpectedConditions.stalenessOf(element));
    }`
Like so:
`fluentWaitForElementToBeStale(fluentWaitForElement(By.cssSelector("[id*=sys_group_grid][title='Enter Text to Filter on Group Name']")));`
The code should run without error (as it did in previous versions of Selenium)
## Actual Behavior -
On methods that use Expected Conditions, I'm seeing occasional errors as can be seen in the attached exception (with personal details removed) 
[Exception.txt](https://github.com/SeleniumHQ/selenium/files/2090276/Exception.txt)
I don't see this in 3.7.0

## Steps to reproduce
Create a series of Cucumber tests and add them to a Testng suite, run the suite in parallel with 5 threads

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by funnybutrandom** [comment]
Extra details added, do you need anything else?

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/)

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), otherwise the issue will be closed.
