### ISSUE TITLE
Not able to get the driver of a new browser window opened after logging in to a web app and login browser window gets closed.

### ISSUE THREAD

**Issue by akkiprasad** [SeleniumHQ/selenium#6015]
## Meta -
OS:  

Browser:  

## Expected Behavior -
Exception: NosuchwindowException :Unable to get the browser 
NosuchwindowException :Window is closed
## Actual Behavior -
When I login to a web application and when enter username and password and OK button,the login window is getting closed and a new window with new URL opening up.
But I am not able to get the handle of that browser.

Login Button: driver.findElement(By.name("OK")).click();
After this new browser window opens up but driver.getWindowHandles().size(); returns zero
and System.out.println("No:"+driver.getWindowHandle());  throws org.openqa.selenium.NoSuchWindowException: **Window is closed**

**Comment by akkiprasad** [comment]
Protected mode already enabled for all the zones.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by akkiprasad** [comment]
Hi @barancev ,
Sorry couldn't explain in details being a novice user.
Actual: I am not able to get a handle of a browser window opened new after logging in window.
Expected:I need to perform actions on browser window opened after logging in.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
