### ISSUE TITLE
Issue with Screenshots in Safari 11.1

### ISSUE THREAD

**Issue by ppanuganti** [SeleniumHQ/selenium#6017]
## Meta -
**OS: OS X Sierra (10.13)
Browser:safari 11.1** 

## Problem -
We are observing that when we execute a run on safari 11.1  the complete page screenshot is taken which is not expected.

## Expected Behavior -
The screenshot captured should be only the part which is in view port 
![image](https://user-images.githubusercontent.com/34885614/41342564-2e4e0646-6f1a-11e8-8f7c-577aa681fa94.png)

## Actual Behavior -
The complete page screenshot is taken
![image](https://user-images.githubusercontent.com/34885614/41342477-f5270458-6f19-11e8-842b-bf911015df56.png)

## Steps to reproduce -

1. Open Amazon site (amazon.com)
2.Navigate to footer
3.Get the screenshot of the footer part which is in view port

**Comment by lmtierney** [comment]
This would be a bug with safaridriver, please log any Safari issue with Apple: https://bugreport.apple.com/

**Comment by FA-tvonmoll** [comment]
FWIW: I filed a bug with Apple back in April about this. It's marked as a `DUPE`, but still in the open status.
