### ISSUE TITLE
Selenium webdriver reference is null for parallel execution for N unit

### ISSUE THREAD

**Issue by kumarbrandmuscle** [SeleniumHQ/selenium#6018]
Hi,
In order to run browsers for parallel,we have to the browser as static.
So,that I declared the drivers as  public  IWebDriver Driver; while passing it to the webdriver interaction class it is throwing null.(object reference is not object.)
sample of interactions code:
public class BasicInteractions:Base
    {
        //private IWebDriver Driver;
        public BasicInteractions(IWebDriver Driver)
        {
            Base bc = new Base();
            this.Driver = bc.Driverclass();
        }

        #region Navigating to the URL
        public void GoToURL(string url)
        {
            //openBrowser();
            
         Driver.Navigate().GoToUrl(url);
        }
        public void Refresh()
        {
            Driver.Navigate().Refresh();
        }
        public void ScrollBy(int scroll)
        {
            IJavaScriptExecutor js = (IJavaScriptExecutor) Driver;
            js.ExecuteScript(" window.scrollBy(0, scroll);");

        }
        public string GetCurrentURL()
        {
            return Driver.Url;
        }
        #endregion

        #region sendkeys functionality
        public void Type(By by, string value)
        {
            Driver.FindElement(by).SendKeys(value);
        }

sample of base class:
 public class Base
    {
        public  IWebDriver Driver;
        
        
        //public void openbrowser()
        //{
        //    //var dir = Path.GetDirectoryName(typeof(Base).Assembly.Location);
        //    //Environment.CurrentDirectory = dir;
        //    //string path = dir;
        //    //Console.WriteLine(path);
        //    //Driver = new ChromeDriver(path + @"\Assets");
        //    //Driver.Manage().Window.Maximize();
        //}
        public  IWebDriver Driverclass()
        {
            if (Driver == null)
            {
                var dir = Path.GetDirectoryName(typeof(Base).Assembly.Location);
                Environment.CurrentDirectory = dir;
                string path = dir;
                Driver = new ChromeDriver(path + @"\Assets");
                Driver.Manage().Window.Maximize();
                return Driver;
            }
            else
            {
                return Driver;
            }
        }
could post me a solution on this.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
