### ISSUE TITLE
Selenium IDE - Cannot clone/duplicate tests. Instructions in #6276 don't work.

### ISSUE THREAD

**Issue by lucianobargmann** [SeleniumHQ/selenium#6020]
## Meta -
OS: Windows 10
Selenium Version:  IDE 3.0.3

Browser:  
Chrome 67.0.3396.87 (Official Build) (64-bit)
Firefox 60.0.2 (64bit)

## Expected Behavior -
Objective: Duplicate a test case and alter a few params. Issue 6276 from archive (https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6276#issuecomment-192136639) states that we should either:

1. Select all the commands in the test case and copying them (ctrl-C or Command-C or Edit->Copy)
and pasting them in a new test case!
**Expected:** IDE would allow you to *Select all the commands in the test case*

or 

2. You can also go to the "source" view and copying all the text there and paste it in
a new one. 
**Expected:** *Source View* to exist or, when loading a .side file, IDE would warn you the IDs are duplicated and *offer the option* to fix that (assigning new IDs to all elements)

## Actual Behavior -
1. You cannot select more than one command (test step).
and
2. When you copy and paste JSON elements, the IDs are duplicated. IDE stops working correctly. Displays all tests selected. Changes in one test is replicated to all other tests, etc

### For case 1
1. Open Selenium IDE
2. Create 3 test steps (content doesnt matter)
3. Copy all commands - **ISSUE* You cannot select more than one command.

### For case 2
1. Open Selenium IDE
2. Create 3 test steps (content doesnt matter)
3. Save project to a .side file
4. Open the file in a text (JSON) editor
5. Duplicate a Test
6. Save file
7. Load on IDE - **ISSUE** IDE stops working correctly. Displays all tests selected. Changes in one test is replicated to all other tests, etc

**Comment by lmtierney** [comment]
The IDE has its own repo for now, please raise an issue there: https://github.com/seleniumhq/selenium-ide/issues
