### ISSUE TITLE
Missing folders when installing selenium on Python through Amazon Linux EC2 and pipenv

### ISSUE THREAD

**Issue by S-Cardenas** [SeleniumHQ/selenium#6022]
I'm attempting to install the python distribution of Selenium to be run an AWS Lambda. The Selenium package is being installed and built through the [docker-lambda](https://github.com/lambci/docker-lambda) python images. When using the the [docker-lambda python 3.6 run image](https://github.com/lambci/docker-lambda/tree/master/python3.6/run) and installing via `pipenv run pip3 install -Ur requirements.txt` I notice that the selenium package did not install all of its required folders/files (checkout the missing webdriver folders). 

Actual:
<img width="202" alt="41379608-07ca0bec-6f28-11e8-9183-4e92cfbd21e7" src="https://user-images.githubusercontent.com/14102289/41430449-a51294b6-6fd5-11e8-893c-8c6805e9af8b.png">

When I installed **without** pipenv, `pip3 install -Ur requirements.txt` the entire selenium module is installed correctly.

Expected:
<img width="225" alt="41379636-17621996-6f28-11e8-999a-f321c52c6cb0" src="https://user-images.githubusercontent.com/14102289/41430509-c65dff2a-6fd5-11e8-90b8-8c660c07b0a7.png">

Does anyone know the reason why `pipenv pip3 install` incorrectly installs the package. Is it checking for something in the background that standard `pip3 install` does check for?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
