### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MStahl15** [SeleniumHQ/selenium#6023]
## Meta -
OS:  Windows 10
Selenium Version:  Selenium IDE 3.0.3.0
Browser:   Firefox

## Feature Request -
Ability to drag and drop tests within a test suite into a specific order before running the entire suite.  

This would be a great feature since a lot of objects have to be created in a specific order in projects.

**Comment by netzulo** [comment]
Selenium IDE ? it's deprecated, no ? : https://www.google.es/search?q=selenium+ide+firefox+deprecated

sorry if sounds bad , @MStahl15 , maybe you need to learn about advanced actions for java : https://github.com/SeleniumHQ/selenium/wiki/Advanced-User-Interactions

**Comment by MStahl15** [comment]
Not deprecated...last update was June 7th 2018:

https://github.com/SeleniumHQ/selenium-ide

**Comment by netzulo** [comment]
:O ty for the info about selenium IDE, @MStahl15 :) didn't think about check for this at selenium repo, i'll take a look

**Comment by lmtierney** [comment]
@MStahl15 please post this to https://github.com/SeleniumHQ/selenium-ide/issues
