### ISSUE TITLE
Change of artifactId Selenium-java.jar from 3.3.1 to 3.4 causing a ton of 'can not be accessed' errors in my maven project

### ISSUE THREAD

**Issue by PrasadNutalapati** [SeleniumHQ/selenium#6024]
## Meta -
OS:  
MAC OS Sierra 
Selenium Version:  
3.X
Browser:  
Not Applicable
We are running a Selenium 3.3.1 project with many dependencies(given in a pom.xml file) as part of a maven project. Only when we change the version of artifactId Selenium-java from 3.3.1 to 3.4, all started crumbling. A ton of 'not accessible' errors came up for By, Select, Keys etc. kind of regular Selenium classes. Some other classes like WebDriver, WebElement etc are resolving just fine. 

No matter whether we clean,build,install the Maven project the errors won't go away. I even removed the entire .m2 folder and refreshed the project, for no avail. 
When I either moved back to artifactId version 3.3.1 or go to a higher version 3.12.0, every thing compiles just fine. Is there any particular problem with artifactId Selenium-java 3.4.0? I am using Eclipse Oxygen.

## Expected Behavior -
With the change in the artifactId selenium-java from 3.3.1 to 3.4.0, all the new jars should be downloaded and the existing code should be seemlessly compiling with out errors.
## Actual Behavior -
Regular Selenium Java classes imports like BY, Select, Keys, JavaScriptExecutor are throwing not resolved errors, while some other classes like WebDriver, WebElement are getting resolved just fine.
## Steps to reproduce -

![image](https://user-images.githubusercontent.com/20956177/41449616-a97f3778-7027-11e8-9290-dc3570115f0a.png)

![image](https://user-images.githubusercontent.com/20956177/41449672-168b1698-7028-11e8-8d18-f36e1a54dda2.png)

![image](https://user-images.githubusercontent.com/20956177/41449693-3df8c96e-7028-11e8-95e6-8e1e48dec838.png)

**Comment by barancev** [comment]
Why 3.4? The latest Selenium version is 3.12 at the moment.

And this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by PrasadNutalapati** [comment]
Thanks for your response.
Selenium 3.4 is because for our Saucelab requirement is that it supports only Selenium-Java for SAFARI browser with 3.4 only. See here. [https://wiki.saucelabs.com/display/DOCS/2017/10/20/Announcing+support+for+Safari+11+in+Mac+OS+10.12]
As it is mentioned the code compiles pretty nicely when we change the artifactId Selenium -java version to 3.12 with out any problem.

**Comment by barancev** [comment]
Sorry to say this, but we'll not fix the issue in 3.4, it's so out of date.

And I don't believe that SauceLabs does not support newer Selenium versions on MacOS, you refer to a half-year blog post, it can be not actual anymore.

**Comment by aksbhai** [comment]
Sorry... my query was regarding defect #4093 where Firefox profile were
unable to launch in latest version of Firefox where the .xpi file needed
install.rpk to proceed further.
Please let me know how to go ahead in launch of latest Firefox profile by
adding .xpi file for add-on to be added in launch of profile.
One such solution was provided by Nitish.

**Comment by PrasadNutalapati** [comment]
Thank you very much barancev for your input.
I will try and verify whether Saucelab enhanced their support of Selenium-Java beyond 3.4.0 in which case we are lucky. If they really support 3.12 the latest, it is awesome.
Thanks again for you response and support.
