### ISSUE TITLE
Click not executing upon React Js platform

### ISSUE THREAD

**Issue by omerovadia** [SeleniumHQ/selenium#6030]
OS:  Mac \ Windows
Browser: Chrome 66.0.3359.181
Chrome driver 2.40
Selenium: 3.12.0
React JS version: V16

Since we upgraded react Js version to 16, driver.click() not perform actual selection, the element found but the click taken affectively.
I tried by xpath, id, selector.
Sending keys is also working.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
