### ISSUE TITLE
Chrome driver : OpenQA.Selenium.WebDriverException: 'Unexpected error. System.Net.WebException: Unable to connect to the remote server

### ISSUE THREAD

**Issue by rajeeshmenoth** [SeleniumHQ/selenium#6035]
## Meta -
**OS:**  
Windows 10
**Selenium Version:**  
3.11.0
**Browser:**
67.0.3396.87
**Chrome driver:**
2.39.562718
## Error

OpenQA.Selenium.WebDriverException: 'Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 10.16.24.70:9515

## Code
`
[SetUp]
        public void InitilizeTest()
        {

   DesiredCapabilities capability = DesiredCapabilities.Chrome();
            capability.SetCapability("platform", "WIN10");
            capability.SetCapability("browserName", "chrome");
            capability.SetCapability("version", "67.0.3396.87");
            System.Environment.SetEnvironmentVariable("-Dwebdriver.chrome.driver", @"C:\\code\\chromedriver.exe");
            driverChrome = new RemoteWebDriver(
              new Uri("http://10.16.24.70:9515"), capability
            );
        }`

## Chrome driver running in remote machine
When I open the chrome driver in remote path I am getting the following information.
![image](https://user-images.githubusercontent.com/8437883/41536597-b65780be-7323-11e8-85b2-8a413a75fbd5.png)

## Expected Behavior -
We are executing chrome driver in remote machine.
## Actual Behavior -
It's failing for the initial run time.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
