### ISSUE TITLE
Chromium based browser (Ghost browser) unexpectedly exited status code 0

### ISSUE THREAD

**Issue by Jaquedeveloper** [SeleniumHQ/selenium#6037]
## Meta -
OS:  
Windows 10
Selenium Version:  

Browser:  
Ghost Browser

## Expected Behavior -

Open and keep control of browser.

## Actual Behavior -
Opens the browser and exits, not closing the browser but losing control of it.

## Steps to reproduce -
Install Ghost Browser
Get path
insert it's path as the browser executable path

Code
   ```
 exe_path = r'C:\Users\Anonymous\AppData\Local\GhostBrowser\Application\ghost.exe'
 driver = webdriver.Chrome(executable_path=exe_path)
```

**Comment by barancev** [comment]
This is a chromedriver issue, please report it to https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by Jaquedeveloper** [comment]
@barancev, Can selenium actually open a Chromium based browser (not Chrome)?
