### ISSUE TITLE
Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by a365541453** [SeleniumHQ/selenium#6039]
OS:  
CentOS Linux release 7.5.1804 (Core)

Selenium Version:  
selenium     3.12.0

Browser:  
google-chrome-stable

Browser Version:  
Google Chrome 67.0.3396.87 (64bit)

## Expected Behavior -
I want to start Chrome 
The code is this:

from selenium import webdriver
browser = webdriver.Chrome('/django/chromedriver')

## Actual Behavior -

    browser = webdriver.Chrome('/django/chromedriver')
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.10.0-862.3.2.el7.x86_64 x86_64
## Steps to reproduce -
python:
I use python3.4

Installation method:
yum install google-chrome-stable

ChromeDriver version:
ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb)

I print log information
get one WARNING information:
[1.006][WARNING]: PAC support disabled because there is no system implementation

but,I don't know how to solve this problem

In addition, 
the system currently in use is cloned and the previous system has a problem.

thanks ~

**Comment by a365541453** [comment]
I print log information
get one WARNING information:
[1.006][WARNING]: PAC support disabled because there is no system implementation

but,I don't know how to solve this problem
thanks~

**Comment by barancev** [comment]
According to the error log, you have chromedriver=2.9.248304, please upgrade.

**Comment by barancev** [comment]
Please read your error log carefully. You must be having an outdated chromedriver version in PATH.

**Comment by a365541453** [comment]
sorry，before I misunderstood what you meant, now I know
I previously used 2.4.248304, thinking this is the latest version,
In fact ，already have 2.4.565383
Thank you

**Comment by luke-hill** [comment]
So perhaps a common misconception is the drivers are ordered sequentially. But infact they are not. They are ordered according to semver.org

So the drivers (in order), are.

2.1, 2.2 .... 2.9, 2.10, 2.11 ... 2.19, 2.20, 2.21 .. and so on.

Unfortunately the chromedriver archive sorts them alphabetically. Putting 2.9 at the bottom.
