### ISSUE TITLE
Webdriver Exception - Selenium Webdriver Java < Urgent >

### ISSUE THREAD

**Issue by YakirSA** [SeleniumHQ/selenium#6041]
## Meta -
OS:  Windows 10

Selenium Version:  3.12.0 (latest)

Browser:  Chrome

Browser Version:  67.0.3396.87(64-bit)

## Expected Behavior -
It supposed to keep running as usual.

## Actual Behavior -
When I run my automation it gets stuck and stops working on random parts of the code, and sends back webdriver exception.
Checked if the element has changed and it didn't. I'm trying to find it using xpath but also tried id, class name, link text, and tag name....
Now I'm losing my mind because of it, I just can't understand why it happens it doesn't make any sense.
Just now I tried it twice and it stopped in two different locations.
I can't send a link to the page but, if anyone could help me it would be great!

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by YakirSA** [comment]
How is it not an issue??
Its a problem

**Comment by barancev** [comment]
Yes, Selenium user group is indended to solve user problems :)
