### ISSUE TITLE
fullScreen with firefox

### ISSUE THREAD

**Issue by well-oo** [SeleniumHQ/selenium#6042]
## Meta -
OS:  Raspberry pi 3 B+ armv7l, Raspbian ( Debian) 9 stretch

Selenium Version:  
3.12.0

Browser:  
Firefox-ESR with geckodriver v0.17.0

Browser Version:  
Mozilla Firefox 52.8.1

## Expected Behavior -
Open firefox in full screen
## Actual Behavior -
Firefox is opened but not in full screen

error log : 

```
Traceback (most recent call last):
  File "fi.py", line 4, in <module>
    browser.fullscreen_window()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 734, in fullscreen_window
    self.execute(Command.FULLSCREEN_WINDOW)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: fullscreenWindow
```

## Steps to reproduce -
With Python 3.5 and Python 2.7
http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.fullscreen_window

```
from selenium import webdriver
browser = webdriver.Firefox()
browser.get('http://google.com')
browser.fullscreen_window()
```

**Comment by barancev** [comment]
Use legacy FirefoxDriver to deal with Firefox ESR 52.

**Comment by netzulo** [comment]
are you tried to call to maximize_window directly , 

documentation: http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.maximize_window

example : https://github.com/netzulo/qacode/blob/129dfec1f6e8d7292aeb1ad24a4417bbf1ce88e9/qacode/core/bots/modules/nav_base.py#L59

test: https://github.com/netzulo/qacode/blob/129dfec1f6e8d7292aeb1ad24a4417bbf1ce88e9/tests/001_functionals/suite_004_navbase.py#L52

It's working for me at 

- [x] chrome
- [x] firefox
- [x] iexplorer
- [x] edge

**Comment by well-oo** [comment]
@netzulo I tried to make the browser in fullscreen mode like when your type F11 on your keyboard.
maximize_window() works but do not make the browser in full screen.

I tried legacy FireFoxDriver like you suggered @barancev but i have an error, maybe it's not possible with my configuration

```
Traceback (most recent call last):
  File "testFirefox.py", line 81, in <module>
    browser.fullscreen_window()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 734, in fullscreen_window
    self.execute(Command.FULLSCREEN_WINDOW)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Unrecognized command: POST /session/ee5c08f9-fd73-4000-8682-3395b4634b7e/window/fullscreen
```

code source :
 ```
from selenium import webdriver 
from selenium.webdriver import Firefox
browser = Firefox(executable_path="/usr/bin/firefox-esr", capabilities= {"marionette": False})
browser.get(http://google.com)
browser.fullscreen_window()
```

Full screen works with Chromium and it's faster than Firefox so I think i'm gonna use it

Thanks

**Comment by netzulo** [comment]
aaaaaaaa it's a raspberry py with ESR firefox!!! xDDD ouch! i can test it, but talk to me at gmail with : netzuleando@gmail.com :)


stop to talk here, issue is closed :(

**Comment by marsilba** [comment]
@well-oo
How did you get the Chromium to work?
I tried but I can not, I can only open Firefox but it does not open full screen.
