### ISSUE TITLE
Gecko: Loading unused old webdriver which is not necessary

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#6043]
I use the C# driver, latest version.

When The Geckodriver starts it calls FirefoxExtension.Install() which unpacks a ZIP file into a Temp directory, modifies the files, packs them again, converts them to base64 and loads them into Firefox.

All this is completely unnecessary when the Gecko driver is used.
The function Install() should not be called when FirefoxOptions.UseLegacyImplementation is false.

**Comment by jakedurand** [comment]
Is this not needed for loading extensions to the profile?

**Comment by Elmue** [comment]
When I remove the code that unpacks the ZIP file everything still works fine. The ZIP file WebDriver.FirefoxExt.zip is full of javascript files which where used for the old Firefox plugin. With Gecko this is not needed anymore.

The contents of the ZIP file is:

bad-cert-listener.js
command-processor.js
dommessenger.js
driver-component.js
evaluate.js
httpd.js
modifier-keys.js
prompt-service.js
server.js
session.js
session-store.js
synthetic-mouse.js
timer.js
web-element-cache.js
chrome.manifest
install.rdf
nsICommandProcessor.xpt
nsIHttpServer.xpt
nsIResponseHandler.xpt
wdICoordinate.xpt
wdIModifierKeys.xpt
wdIMouse.xpt
wdIStatus.xpt
fxdriver.xul

----------------

Additionally I suppose that the resource files (which are not in the ZIP file)
WebDriver.FirefoxNoFocus.x64.dll
WebDriver.FirefoxNoFocus.x86.dll
are also not needed anymore with Gecko.

----------------

This ZIP file has half a Megabyte and can be removed completely in the future when all users will have switched to Gecko.

**Comment by jimevans** [comment]
@Elmue I’m not going to speak to the removal of the .xpi yet. It’s an issue that can be revisited when I have time, but it likely won’t be for at least a couple of weeks. However, regarding the “dlls” you mention, the libraries aren’t actually _named_ with a .dll extension; that’s just the name of the resource they have in the WebDriver.dll assembly. When extracted at runtime to be used by the legacy Firefox driver on Linux (an incredibly rare for .NET users and getting rarer every day scenario), they have an appropriate file name on the file system.

**Comment by jimevans** [comment]
I believe I have fixed this in db1e959. It's entirely possible the change will break the legacy driver, though I've tried to avoid that. If this does not resolve the issue, @Elmue, please let me know.

**Comment by Elmue** [comment]
Isn't there an if (...) missing ?

if (isMarionette) this.profile.RemoveWebDriverExtension();

**Comment by jimevans** [comment]
Where? The method is marked `internal`, meaning no external library can call it, and it’s only being called internally from branches where `isMarionette` is already true. Please feel free to correct me if I’m wrong.

**Comment by Elmue** [comment]
I did not look so deeply into the code. 
If you are sure, then it's OK.

**Comment by jimevans** [comment]
It shouldn’t, but I’m not infallible. Nor am I in a position to rigorously test versions of Firefox that are two years old. In making the statement, I’m editorializing that using the legacy driver is an obsolete code path, and given the choice between breaking the legacy driver and making the current (geckodriver) experience better, I’ll prioritize the latter. It’s also a pointer to myself of a place to check if reports start rolling in about the legacy driver not working anymore. Are those reasons satisfactory to you?
