### ISSUE TITLE
Make Python ChromeDriver override stop_client instead of quit

### ISSUE THREAD

**Issue by nanonyme** [SeleniumHQ/selenium#6044]
This is a feature request (trivial). Would do a PR myself but don't currently have CLA signed.
See https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py#L129
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L699
it's clear that it was intended the service stop logic would be in function stop_client (based on documentation in https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L223) and actual quit would not be overridden. Should not require any changes in tests. Currently Chrome WebDriver is also for some reason swallowing the exception with the reason that you don't care about exception if something has gone wrong which is a complete oxymoron

**Comment by nanonyme** [comment]
For completeness: in Python 3 exceptions are chained if you don't suppress them so end-user will always have the exception from quit available for usage in debuggers and logs if it's not suppressed.

**Comment by netzulo** [comment]
totally agree with @nanonyme  : https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py#L123-L129

``` python
        try:
            RemoteWebDriver.quit(self)
        except Exception:
            # We don't care about the message because something probably has gone wrong
            pass
        finally:
            self.service.stop()
```

**Comment by lmtierney** [comment]
This makes sense, I'll try to get it in after this next release

**Comment by symonk** [comment]
@lmtierney / @AutomatedTester  this looks to be done; can we close?

https://github.com/SeleniumHQ/selenium/blob/f4f4489d1c91af50f349b800b7459f44d84e97b0/py/selenium/webdriver/chromium/webdriver.py#L186

**Comment by diemol** [comment]
Seems like it was indeed done. I'll close this since there was no more input after the comment above. If this is still an issue with the most recent versions, please feel free to reopen or create a new issue.
