### ISSUE TITLE
Updating Selenium driver to v3.12.0 or v3.12.1 in .Net packages raises casting issue in Appium automation

### ISSUE THREAD

**Issue by Gocoollnath** [SeleniumHQ/selenium#6045]
## Meta -
Appium version 1.8.1
Desktop OS/version used to run Appium: Windows 10 Pro
Node.js version (unless using Appium.app|exe): 8.10.0
Mobile platform/version under test: Android API 25 ,v7.1.1
Real device or emulator/simulator: Real Device Samsung Tab
Appium CLI or Appium.app|exe: both
IDE: VisualStudio 2017 Enterprise and C# as coding language
Selenium Driver and Selenium support driver : v3.12.0 (Issue creating version)

## Code to Reproduce

public static AndroidElement UserName_Field()

    {
        AndroidElement UserName = driver.FindElement(By.Id("*:id/LoginView_txtUsername"));
        return UserName;
    }

## Exception stacktraces
Test Name:	TestMethod1
Test FullName:	UnitTestProject1.UnitTest1.TestMethod1
Test Source:	C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs : line 25
Test Outcome:	Failed
Test Duration:	0:00:53.4154213

## Result StackTrace:	

at OpenQA.Selenium.Appium.AppiumDriver`1.FindElement(By by)
   at *_Mobile.Page_Objects.Login_Objects.UserName_Field() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\Page_Objects\Login_Objects.cs:line 21
   at *_Mobile.Log_in_module.Login_module.Login(String Uname, String Pwd) in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\App_Modules\Login_module.cs:line 18
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Users\gokulnath.kumar\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 27
Result Message:	
Test method UnitTestProject1.UnitTest1.TestMethod1 threw exception: 
System.InvalidCastException: Unable to cast object of type 'OpenQA.Selenium.Remote.RemoteWebElement' to type 'OpenQA.Selenium.Appium.Android.AndroidElement'.

## Link to Appium logs

https://gist.github.com/Gocoollnath/c6b4be5ababf838a0acf0adb72552a20

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Gocoollnath** [comment]
@barancev  I have updated my post accordingly.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), including driver initialization code.

**Comment by Gocoollnath** [comment]
AndroidDriver<AndroidElement> driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), dc);

public static AndroidElement UserName_Field()

{
    AndroidElement UserName = driver.FindElement(By.Id("*:id/LoginView_txtUsername"));
    return UserName;
}

**Comment by jimevans** [comment]
Yes, the method for how `RemoteWebDriver` instances are generated changed in 3.12.0. This was documented in the [CHANGELOG for the .NET bindings](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG). Downstream projects such as Appium will need to adjust. In point of fact, the change was made as a partial response to a request by the Appium project. If they have not yet updated or released their .NET code to take advantage of the new method, that’s not anything the Selenium project can do anything about, but it’s most certainly not an issue with Selenium. This is particularly so when the change was communicated directly to that specific project’s team, in addition to the wider release notes.
