### ISSUE TITLE
Implicitlywait() fails to wait for an element 

### ISSUE THREAD

**Issue by JeffGaly** [SeleniumHQ/selenium#6047]
I wish to make my page to wait for 3 minutes which will do a process of generating reports about 2 to 3 minutes.
I tried using implicitlyWait(),ExplicitWait() ,scriptwait(),pageloadtimeout ()but nothing works as page gets loaded to next step without waiting for 3 minutes.

Note :I dont wish to use thread.sleep() .
Any suggestions will be useful .

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
