### ISSUE TITLE
selenium-webdriver gem 3.13.0 was not published

### ISSUE THREAD

**Issue by eloyesp** [SeleniumHQ/selenium#6048]
Nothing is broken, just that the gem was version was updated in https://github.com/SeleniumHQ/selenium/commit/361e9b3222248d8606eebfc569c782cca7e1a5a6 to 3.13.0 one week ago, but the gem was not published to [rubygems](https://rubygems.org/gems/selenium-webdriver).

**Comment by titusfortner** [comment]
The release hasn't actually happened yet. Simon likes to bump up the versions ahead of the release. I think there's an outstanding bug that needs to be fixed before we pull the trigger on it.
