### ISSUE TITLE
FindElement / Until exception is not caught by catch block

### ISSUE THREAD

**Issue by alexandis** [SeleniumHQ/selenium#6050]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.12.1
Browser:  
Internet Explorer

Browser Version:  
11.726.15063.0 (64-bit)

## Expected Behavior -
If element is not found, the exception is caught in "catch" block.

## Actual Behavior -
If element is not found, the exception is not caught in "catch" block - instead, the execution stops right on the method's call.

## Steps to reproduce -
Self-explanatory screenshot in C#:
![image](https://user-images.githubusercontent.com/6149843/41701058-9514f352-7533-11e8-9145-bb89460b9055.png)

**Comment by barancev** [comment]
And what is incorrect in Selenium behaviour? It thows an exception, as expected.

**Comment by alexandis** [comment]
I want to be able to handle this situation. Meanwhile, I can't see how can I do that, since catch block is not entered, no matter what type of exception I catch.

**Comment by GitSage** [comment]
Maybe the issue is the debugging tools in your editor breaking before you enter the `catch` block? Try unchecking the `Break when this exception type is thrown` box visible in the screenshot. 

Alternatively, try running in Run mode rather than Debug mode.

**Comment by alexandis** [comment]
> Alternatively, try running in Run mode rather than Debug mode.
Already tried just to "run" - it's the same: my catch block is not fallen into.
I've currently got rid of using wait.Until and FindElement and use only FindElements. Afterwards, if element is found (FirstOrDefault is not null), I am calling wait.Until([element.Displayed | element.Visible and other conditional logic]). But I am not sure it would work out in all cases...

**Comment by barancev** [comment]
Yes, it seems that you have a conditional breakpoint on exceptions of this type.
