### ISSUE TITLE
[dotnet] Refactor DefaultWait to better handle exceptions

### ISSUE THREAD

**Issue by Arithmomaniac** [SeleniumHQ/selenium#6054]
https://github.com/SeleniumHQ/selenium/blob/90611adf87d70007c9dc519131232967bae44f4a/dotnet/src/webdriver/Support/DefaultWait%7BT%7D.cs#L178-L186

This could be written more simply (with [greater code efficiency](https://www.thomaslevesque.com/2015/06/21/exception-filters-in-c-6/)) using C# 6 `when` filters:

```csharp
 catch (Exception ex) when (this.IsIgnoredException(ex))
 { 
     lastException = ex; 
 }
```

(if mini code changes like this are really preferred as PRs, despite the paperwork, I can oblige.)

**Comment by jimevans** [comment]
If that’s a syntactic sugar feature of C# 6 that is compatible back to .NET 3.5, I’ll consider making the change, but since it’s not just syntactic sugar, but actually has stack implications, I’m loathe to blindly make the change without further investigation.

**Comment by diemol** [comment]
This issue has gone stale, if there is still the intention to achieve this, please raise a PR.
