### ISSUE TITLE
Enable reading timeouts on non-spec driver instances

### ISSUE THREAD

**Issue by Arithmomaniac** [SeleniumHQ/selenium#6055]
Right now, you can set e.g. `ImplicitWait` on a  non-W3C-compliant driver instance:
https://github.com/SeleniumHQ/selenium/blob/85318cb2af44e768ec7041891e3ecf52b00039bd/dotnet/src/webdriver/Remote/RemoteTimeouts.cs#L167-L168

But not get one:
https://github.com/SeleniumHQ/selenium/blob/85318cb2af44e768ec7041891e3ecf52b00039bd/dotnet/src/webdriver/Remote/RemoteTimeouts.cs#L130

This shouldn't need to be the case. Whatever is going on internally to set the timeout should be able to store it if it has not been already, and read it too.

One use case for this is the ability to [temporarily suspend implicit waiting](https://stackoverflow.com/a/23359199) without having direct access to the original wait times.

**Comment by jimevans** [comment]
The legacy OSS dialect of the wire protocol doesn’t support any endpoint for getting the timeouts, only setting them. The timeouts are managed by the remote end driver (IEDriverServer.exe, geckodriver.exe, chromedriver.exe, etc.), not the language binding. Even if the bindings didn’t short-circuit the call, it wouldn’t work at the driver level. Yes, that use case is one reason the endpoint was added to the W3C WebDriver Specification, but using it requires that the remote end implement the spec.

**Comment by Arithmomaniac** [comment]
Would a PR that stores the values on the `RemoteTimeouts` as a fallback be accepted?

**Comment by prashant08** [comment]
I am getting issue using C#-Selenium on below code:

public static void SetImplicitWait(this IWebDriver driver, TimeSpan waitTime)
    {
        driver.Manage().Timeouts().ImplicitWait = waitTime;
    }
System.NotImplementedException: Driver instance must comply with the W3C specification to support getting timeout values.

Please help to resolve this issue.
