### ISSUE TITLE
Calling isDisplayed() on an empty span with certain styling results in true when it should not

### ISSUE THREAD

**Issue by GitSage** [SeleniumHQ/selenium#6058]
## Meta
OS:  Windows 10
Selenium Version:  3.11.0
Browser:  IE11, Firefox, Chrome
Browser Version:  
IE: 11.1.029.15063.0 (64-bit)
Firefox: 58.0.2 (64-bit)
Chrome: Version 67.0.3396.87 (Official Build) (64-bit)

## Expected Behavior
Calling `isDisplayed` on any empty span should always result in `false`.

## Actual Behavior
Calling `isDisplayed` on an empty span with `style="position:absolute; top: 100px; bottom: 100px; left: 100px; right: 100px;"` results in `true`.

## Steps to reproduce
Given this html: 
```
<html>
<body>

	<span id="none"></span>
	<span style="position:absolute; top: 100px; bottom: 100px; left: 100px;" id="absolute-top-bottom-left"></span>
	<span style="position:absolute; top: 100px; bottom: 100px; right: 100px;" id="absolute-top-bottom-right"></span>
	<span style="position:absolute; top: 100px; left: 100px; right: 100px;" id="absolute-top-left-right"></span>
	<span style="position:absolute; left: 100px; bottom: 100px; right: 100px;" id="absolute-bottom-left-right"></span>
	<span style="position:absolute; top: 100px; bottom: 100px; left: 100px; right: 100px;" id="absolute-top-bottom-left-right"></span>

</body>
</html>
```

Check the result of calling `isDisplayed` on each `span`:

```
const {Builder, By} = require('selenium-webdriver');

(async () => {
	let driver = await new Builder()
		.forBrowser('firefox')
		.build();

	await driver.get('http://127.0.0.1:8081/selenium_bug.html');

	let isDisplayed5 = await driver.findElement(By.id('none')).isDisplayed();
	console.log(`none: ${isDisplayed5}`);

	let isDisplayed1 = await driver.findElement(By.id('absolute-top-bottom-left')).isDisplayed();
	console.log(`absolute-top-bottom-left: ${isDisplayed1}`);

	let isDisplayed2 = await driver.findElement(By.id('absolute-top-bottom-right')).isDisplayed();
	console.log(`absolute-top-bottom-right: ${isDisplayed2}`);

	let isDisplayed3 = await driver.findElement(By.id('absolute-top-left-right')).isDisplayed();
	console.log(`absolute-top-left-right: ${isDisplayed3}`);

	let isDisplayed4 = await driver.findElement(By.id('absolute-bottom-left-right')).isDisplayed();
	console.log(`absolute-bottom-left-right: ${isDisplayed4}`);

	let isDisplayedVisible = await driver.findElement(By.id('absolute-top-bottom-left-right')).isDisplayed();
	console.log(`absolute-top-bottom-left-right: ${isDisplayedVisible}`);

	await driver.quit();
})();
```

Output:

```
none: false
absolute-top-bottom-left: false
absolute-top-bottom-right: false
absolute-top-left-right: false
absolute-bottom-left-right: false
absolute-top-bottom-left-right: true
```

I have put this code [into a repository](https://github.com/GitSage/is-displayed-position-absolute-bug) along with a `package.json` for easier reproduction. 

I am willing to try to fix this, but I'll need some advice on where to look for the `isDisplayed()` functionality. I wasn't able to track it down in the source to `selenium`. From what I discovered it's a complicated problem and handled differently for each browser.

If you're wondering why this strange-looking combination of styles is relevant: it is used in the angular material library. For example, see [the sample button on this page](https://material.angular.io/components/button/overview). Screenshot attached.

![capture](https://user-images.githubusercontent.com/7013825/41744029-cc01b752-755f-11e8-8faa-d011854618eb.PNG)

**Comment by AutomatedTester** [comment]
What makes you think this element shouldnt be returned as not displayed? It's empty but it is being rendered on the page

**Comment by AutomatedTester** [comment]
It is discussed in https://w3c.github.io/webdriver/#element-displayedness which points at the code. The difference between `<span></span>` and `<span style="position:absolute; top: 0; bottom: 0; left: 0; right: 0;"></span>` is the size of the element on the page. The former creates a 0 sized element where the latter creates an element the size of the viewport so while it is empty the browser has still had to render it.

**Comment by twalpole** [comment]
@GitSage Element displayedness is discussed in the WebDriver spec - https://w3c.github.io/webdriver/#element-displayedness - which refers back to an atom used by Selenium.  In that atom it states that elements that 0 width or 0 height should be considered not displayed - so I would tend to agree with your assertion (unless the element has child elements or text and overflow is not hidden).

**Comment by GitSage** [comment]
> An element is in general to be considered visible if any part of it is drawn on the canvas within the boundaries of the viewport. 

Thanks for the link! Your explanation makes sense. This also explains why removing any of `top`, `bottom`, `left`, or `right` makes it not displayed (because that makes the span into a 0-width line with no area). 

If anybody else reads this and feels confused the way I did: even though the box is invisible, it is taking space and can cover things up or be interacted with. Therefore it is drawn and should be considered "displayed." This behavior is consistent with other invisible boxes (e.g. `<div style="position: fixed; width: 100px; height: 100px;"></div>`). 

This issue should be closed.

**Comment by AutomatedTester** [comment]
Glad we helped to explain it. There are a lot of massive edge cases. I did a talk about it at Selenium conf London a few years ago

http://oss.theautomatedtester.co.uk/Presentations/seleniumconf-london-2016/#/
https://www.youtube.com/watch?v=hTa1KI6fQpg
