### ISSUE TITLE
storeElementPresent

### ISSUE THREAD

**Issue by dbase66** [SeleniumHQ/selenium#606]
storeElementPresent is OK (true), if the element is present.

If the element is not present, storeElementPresent return [error] Unexpected Exception: TypeError: inWindow.frames[i] is undefined. 
instead of (false). the script stopps here.

this is not expected result.
what ist the problem? all other tests (for example waitForElementPresent) dont return such error

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
