### ISSUE TITLE
Unable to Execute Tests using Local Selenium Grid

### ISSUE THREAD

**Issue by jarhorn** [SeleniumHQ/selenium#6060]
## Meta -
**OS:**
Windows 10
**Selenium Version:** 
3.12.0
**Browser:**  
Chrome 
**Browser Version:**  
65.0
**Chrome Driver Version:**
2.38
**Language Binding:**
C# (.NET)
**Test Framework:**
SpecFlow

## Expected Behavior -
Tests run using local grid execute as expected

## Actual Behavior -
**Test Execution fails with error:**
[6/21/2018 6:46:15 PM Error] 	[ERROR] Exception has been thrown by the target of an invocation. -> Unable to create session from org.openqa.selenium.remote.NewSessionPayload@4bb2f4f4
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.936Z'
System info: host: 'CH5KM6SR117', ip: '10.7.250.164', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: unknown (SessionNotCreated)

**Grid Hub shows:**
18:46:15.430 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {accessKey: 023cf374-b399-4622-bf95-42c..., browserName: Chrome, build: , name: 2018-06-21T22:46:14.864Z, platform: WIN10, timeouts: , username: jason.horn, version: 65.0}
18:46:15.433 DEBUG [ProxySet.getNewSession] - Available nodes: [http://10.7.250.164:30049]
18:46:15.434 DEBUG [BaseRemoteProxy.getNewSession] - Trying to create a new session on node http://10.7.250.164:30049
18:46:15.435 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=e82580f7-defb-4c89-a32e-12312b27b913, seleniumProtocol=WebDriver, browserName=Chrome, maxInstances=5, platformName=WIN10, version=65.0, platform=WIN10}

**Grid Node shows:**
18:33:26.567 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:4444/grid/register
18:33:26.769 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
18:33:26.802 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use

## Steps to reproduce -
1. startup selenium server hub
   - java -jar C:\development\tools\Selenium\SeleniumServer\selenium-server-standalone.jar -role hub -hubConfig SeleniumServerHubConfig.json (see attached SeleniumServerHubConfig.json)
1. start selenium server node
   - java -Dwebdriver.chrome.driver=C:\development\tools\Selenium\ChromeDriver\chromedriver.exe -jar C:\development\tools\Selenium\SeleniumServer\selenium-server-standalone.jar -role node -nodeConfig SeleniumServerNodeConfig.json (see attached SeleniumServerNodeConfig.json)
1. execute tests from Visual Studio

## Attachments -
[configs.zip](https://github.com/SeleniumHQ/selenium/files/2125611/configs.zip)

**Comment by netzulo** [comment]
@jarhorn , at your **SeleniumServerHubConfiguration.json** file, it's a good practice set ``"host": ip_or_hostname`` key (*i prefer use exact IP when machine have multiples interfaces*)


*Check this links just for your FYI*

+ Have hub+node generator here : https://github.com/netzulo/qalab/tree/master/qalab/configs
+ Drivers versioned here : https://github.com/netzulo/qadrivers
+ Tests using GRID at first project with 2nd project drivers here : https://github.com/netzulo/qacode/tree/master/tests/001_functionals

---

*expecting be usefull*

**Comment by barancev** [comment]
"Chrome" != "chrome", browser name is case sensitive, change the node configuration (and driver initialization too)
