### ISSUE TITLE
Unable to install selenium ide plugin in old firefox browsers

### ISSUE THREAD

**Issue by sreekumarthesun** [SeleniumHQ/selenium#6061]
<img width="1184" alt="screen shot 2018-06-22 at 4 13 49 am" src="https://user-images.githubusercontent.com/3665271/41750552-443b69f0-75da-11e8-8cd0-49d431d13a56.png">
I am trying to install selenium ide with old firefox version in mac. 
When I am clicking selenium ide plug-in extension from google, it goes to new version of selenium ide and showing error message not supported for this browser version.

Can you please help me to install specific version of firefox and selenium ide. As I have many old scripts to execute as part of automation. 

Latest version of selenium ide is not taking old scripts. 

I have tried with firefox Firefox 28.0.dmg and 32.0.dmg

**Comment by barancev** [comment]
https://addons.mozilla.org/en-US/firefox/addon/selenium-ide/versions/

If you can't install an addon from this site download the addon file (the version you need) and drag-n-drop it into the browser window.
