### ISSUE TITLE
wrong action actions.MoveToElement(element).Click()

### ISSUE THREAD

**Issue by LeBronPark** [SeleniumHQ/selenium#6062]
## Meta -
OS:  windows10
Selenium Version:  2.53.1
Browser:  Chrome 67

I have a problem.

I think this issue is because of chrome 67. 

This problem did not appear before chrome 65?

for example : 

IWebElement element in (IEnumerable<IWebElement>)driver.FindElements(By.CssSelector("ul.lst_total > li.bx > div.total_wrap > a.api_txt_lines"));

if it is x = 17, y = 1714, width = 320, height = 30, 

chrome is  working scroll down about y.

but,  Click event is working wrong. not exactly position. click other position.

How can i fix it?

**Comment by LeBronPark** [comment]
and I debug.

((OpenQA.Selenium.Remote.RemoteCoordinates)((OpenQA.Selenium.Remote.RemoteWebElement)element).Coordinates).LocationOnScreen' 'System.NotImplementedException

**Comment by barancev** [comment]
Please retest on the latest Selenium version (3.12 at the moment), legacy version 2.53 is not supported anymore.

**Comment by barancev** [comment]
Closing the issue as version 2.53 is out of date.
