### ISSUE TITLE
Unable to click on Alert at angular webapps 

### ISSUE THREAD

**Issue by surajkakode** [SeleniumHQ/selenium#6063]
## Meta -
OS:   Windows 10 

Selenium Version:  3.11.0, webdriver

Browser:  Firefox, chrome

## Steps to reproduce -

I am trying to click on Alert. Kindly help me with the code.
Thanks in advance.
Website runs on :  angular 6.0.4 
popup can be found here: "https://www.fincash.com/solutions/savings-plus/funds/cash"
kindly help.
Below is the code

driver.get("https://www.fincash.com/solutions/savings-plus/funds/cash");
        driver.findElement(By.xpath("//label/div")).click();
        try {
            WebDriverWait wait = new WebDriverWait(driver, 2);
            wait.until(ExpectedConditions.alertIsPresent());
            Alert alert = driver.switchTo().alert();
            driver.findElement(By.xpath("//button/span[contains(text(),'Yes')]")).click();
            // alert.accept(); alert.dismiss() ;  // i already tried this too
        } catch (Exception e) {
            //exception handling
            e.printStackTrace();
            log.info("excepition caught");
        }

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
