### ISSUE TITLE
Selenium 3.5.3 screen shots are not working consistently (Chrome headless)

### ISSUE THREAD

**Issue by indsoftselenium** [SeleniumHQ/selenium#6067]
## Meta -
OS:  Windows 10.0.14393

Selenium Version:  3.5.3

Browser:  Chrome

Browser Version:  67

## Expected Behavior -
Selenium screen shots should work consistently
## Actual Behavior -
Selenium screen shots are not working consistently
- randomly the screen shot is a full black image
- it seems the Chrome headless selenium driver instance take incorrectly screen shots from a regular opened chrome Chrome session instance
## Steps to reproduce - run two test robots testing the same application in loop for more than 24 hours, one with Chrome headless an the other with regular Chrome using the Chrome driver 2.37
1) Randomly the screen shots are a full black image
2) When a error (alert) occur on headless robot session the screen shot is take from the regular Chrome robot session

**Comment by slapadus** [comment]
This is my code:

    /**
     * Screen shot utility: use TakesScreenshot when is possible, on error use AWT Robot
     */
    public static void toolsTakeScreenShot(final String testName) throws Exception {
        final String filePath = getTestScreenShotFileFullPath(testName);
        try {
            TakesScreenshot screenShot = (TakesScreenshot) getWebDriver();
            File tmpFile = screenShot.getScreenshotAs(OutputType.FILE);
            FileUtils.moveFile(tmpFile, new File(filePath));
        } catch (Exception ex) {
            BufferedImage screenImage = new Robot()
                    .createScreenCapture(new Rectangle(Toolkit.getDefaultToolkit().getScreenSize()));
            ImageIO.write(screenImage, getTestScreenShotFileExt(), new File(filePath));
        }
    }

used in

    /**
     * capture a screen image with the failure
     */
    void screenCaptureOnTestFailure(final String testName, final Throwable e) {
        try {
            report_error(testName + " test failed, exception occured: " + e.getMessage());
            if (isScreenShotOnFailureActive()) {
                // take a screen shoot with the failure
                ToolsForWebAndGraphics.toolsTakeScreenShot(testName);
                report_error("screenCaptureOnTestFailure: see screen capture image:"
                        + getTestScreenShotFileFullPath(testName));
            }
        } catch (Exception ex) {
            logger.error("screenCaptureOnTestFailure: exception occured while capturing screen image:"
                    + ex.getMessage());
        }
    }

**Comment by slapadus** [comment]
Chrome driver v2.37

**Comment by MisterSigal** [comment]
It's not about taking screenshots, something is broken, because when I run my test, I see many black bricks instead of html and bricks are even in Chrome DevTool

**Comment by MisterSigal** [comment]
I cant create an issua (button is disabled) hope my test case will help to find a bug:

OS:  Mac 10.12.5
Selenium webdriver Version:  3.6.0 and 4.0.1 alpha
Browser:  Chrome
Browser Version:  67.0.3396.87
Chrome driver: 2.40
Node: 8.9.4

## Expected Behavior 
To open test case in normal Chrome

## Actual Behavior 
Opens test in Chrome and randomly replace rendered HTML and Chrome DevTools markdown and buttons (etc.) with black bricks

## Steps to reproduce
1 install selenium-webdriver
2 install -g chromedriver
3 create a test case
4 run it

**Comment by barancev** [comment]
This issue should be reported to chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
