### ISSUE TITLE
Disable content security policy Safari

### ISSUE THREAD

**Issue by sasanapu** [SeleniumHQ/selenium#6068]
## Meta -
OS:   Mac OS
Selenium Version:  3.9.0
Browser:  Safari

Issue:
Our web application is CSP enabled, and when i try to enter text in an input field by using **sendKeys** i am getting the following error
Caused by: org.openqa.selenium.WebDriverException: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

The same test passes in other browsers.

Here is the code
 @FindBy(name = "$$$$")
 @CacheLookup
 private WebElement x;

x.click();
x.sendKeys(<name>);

where is an input box.

Browser Version:  10.1.2

Is there a workaround to disable the CSP for the safari browser. I have seen there are options to override it in Firefox and Chrome but not in Safari
The safariOptions doesn't have addArgument

**Comment by sasanapu** [comment]
any update would be helpful, for us to understand your roadmap

**Comment by Cowicide** [comment]
**sasanapu**, did you ever find a solution for this for Safari?

**Comment by diemol** [comment]
@sasanapu is this issue still valid? If so, can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we did not get more information. If this issue still exists with the latest versions, please feel free to open a new issue with all the required information on the template.
