### ISSUE TITLE
Can't handle Modal window with Edge Driver

### ISSUE THREAD

**Issue by louis57** [SeleniumHQ/selenium#6073]
## Meta -
OS: Ubuntu 16.04.1
Selenium Version:  3.12.0
Browser:  Edge 16.16299

I am writing tests and there are some places that when I click on a button, a new browser (as in New modal window) will be opened. I have already handled them by using webDriver.switchTo().window(windowHandle), and it works fine on 3 browsers Chrome, Firefox and Internet Explorer 11.

Now I am trying to run these tests on Microsoft Edge. It works as expected, except when it comes to modal windows:

- When I let the tests run to the point I click on the button, I saw that the Modal Window was opened and disappeard in a blink, it was not in the background as well.

- When I debug the tests to the click() action, then the Modal window was opened and stayed there after the click(), and the tests could continue.

This is how I create EdgeDriver. I use Remote Driver:
```
EdgeOptions options = new EdgeOptions();            
webDriver = new RemoteWebDriver(new URL(remoteURL), options);
```
This is click action:
```
webDriver.findElement(By.name("firstReport")).click();
```
This is html of this button:
       
![download](https://user-images.githubusercontent.com/12949146/41925628-6d65386a-796d-11e8-8359-4502a5163415.png)
I also tried with JavaScriptExecutor and Actions, but the same result. it seems like when the tests run, something modifies display property but I am not sure if it is Selenium or EdgeDriver

I already created a ticket for Edge Team, but I would like to ask here if someone knows a solution for it

**Comment by lmtierney** [comment]
Definitely an issue with Microsoft WebDriver and you've already created a bug with them so I'm closing.

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
