### ISSUE TITLE
Cannot create a remote driver if system properties proxyHost and proxyMode exist

### ISSUE THREAD

**Issue by vutruong1711** [SeleniumHQ/selenium#6080]
## Meta -
OS:  
Windows 10
Eclipse Neon
Maven 3.5.2
Testng 6.13

Selenium Version:  
3.12.0 - java language

Browser:  
Any

## Problem description:
I setup a maven selenium test project as usual with two system properties "proxyHost" and "proxyPort" for surefire plugin. However, I found that selenium http client use this setting for sending request to selenium hub. Should "http.proxyHost" and "http.proxyPort" be used insteads?

`<systemPropertyVariables>
 	<proxyHost>some info here - in my case it is a working proxy IP</proxyHost>
 	<proxyPort>working port of above proxy server</proxyPort>
</systemPropertyVariables>
`

## Expected Behavior -
- Http request to hub for creating a new driver will not be sent via proxy just because there is two system properties: proxyHost and proxyPort. This should use properties from java document: "http.proxyHost" and "http.proxyPort".
 
## Actual Behavior -
- The request is sent via proxy. We have WebDriverException:
Unable to parse remote response:  + response from the proxy (This is an html document from our working proxy server in my case). If two properties have invalid values then we don't get this page.

## Steps to reproduce -
1. Before the test run, set two system properties:
--> proxyHost: some working proxy IP/FQDN or an invalid information
--> proxyPort: similar to above
2. Get a new remote webdriver by command:
--> WebDriver driver = new RemoteWebDriver(url, chromeOpt);

**Comment by barancev** [comment]
This is fixed in version 4, we ignore now system properties "proxyHost" and "proxyPort" as well as "http.proxyHost" and "http.proxyPort"

**Comment by chitayta** [comment]
@vutruong1711 Perfect!
