### ISSUE TITLE
Unable to identify the web elements under iframe document content in IE10 or IE11

### ISSUE THREAD

**Issue by mmuthupa** [SeleniumHQ/selenium#6082]
## Meta -
OS:  
<-- Windows 7 -->
Selenium Version:  
<-- 3.6.0, WebDriver -->
Browser:  
<-- Internet Explorer 10 and 11 -->

IE Driver server Version:  
<-- IE Driver server 3.6.0 -->

## Expected Behavior -
The element should be identified in IE also

## Actual Behavior -

The web elements are present under the iframe - Content Document - This can be identified using javascript but through selenium webdriver unable to identify any elements under that iframe - Content Document. This issue is only in IE where as it is working fine in chrome and Firefox browser

## Steps to reproduce -
i can able to navigate or switch to that iframe but after switching to iframe the elements are present in content document, my html structure is like below

<iframe src = url of that particular page>
<head>
</head>
<body>
<div>
<table>
<tr>

unable to identify any elements or tags under the iframe through selenium webdriver where as through java script document.getElementByTagsName("iframe").contentDocument after that able to identify the elements using script so please help to resolve the issue.

**Comment by jimevans** [comment]
@mmuthupa You’ll need to provide a full repro case that includes a set of HTML files (or a public URL) against which to test. Locating elements in a frame via WebDriver is not broken for all IE users against all websites (see the [WebDriver Herald website](http://webdriver-herald.herokuapp.com) for a list of tests the IE driver is executed against and passing). If you’re using `contentDocument` to access the document in IE, remember that IE sandboxes frames pretty thoroughly, even moreso if the main and framed documents are from different domains. Also, if you’ve not configured [IE’s Protected Mode settings properly](http://jimevansmusic.blogspot.com/2012/08/youre-doing-it-wrong-protected-mode-and.html) for use with WebDriver, that is unlikely to work either.

**Comment by mmuthupa** [comment]
@jimevans  i should not share the companys website html page according to the rule, but what i understand from our development team is that the pages loaded under iframes are having CSRF Tokens(Cross Site Request Forgery Token) through AJAX. According to your suggestion enabled all the zones protected mode settings and tried disableing of all the security zones protected mode settings even though facing the same issue. Kindly suggest any solution.

**Comment by mmuthupa** [comment]
Hi Team,

Any update on the above issue, application is protected with CSRF token, might be that could be the reason the selenium unable to access it? Kindly give any suggestion - how to crack it please.

**Comment by jimevans** [comment]
@mmuthupa No, there has been no update on the issue. Until and unless a reproduction case is provided that would allow the IE driver development team to investigate the issue, there can be no further updates. Please note that the repro does not have to be on the exact site that you’re testing against; a different demonstration site that behaves the same way would also be perfectly acceptible. Until someone is willing to provide such  a sample site with sample code that clearly reproduces the issue, there is no action that can be taken on this issue as written.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
