### ISSUE TITLE
Make OpenQA.Selenium.Keys Non-Static for DotNet

### ISSUE THREAD

**Issue by zubra5** [SeleniumHQ/selenium#6083]
## Meta 
OS:  Windows 10
Selenium Version:   3.3.0
Visual Studio 2015

## Expected Behavior 
OpenQA.Selenium.Keys is non-static class and it can be inherited. It is possible to wrap this class and then expand as ShortKeys. 
## Actual Behavior 
OpenQA.Selenium.Keys is static class and it cannot be inherited from. There is not allowed to inherit from static class

**Comment by jimevans** [comment]
I’m not sure I see the use for making this non-static. The values of the fields are set by the W3C WebDriver spec. If you need to combine the values in some way, you can use a utility class; there is no need to extend `Keys`

**Comment by zubra5** [comment]
At first I need to wrap class `Keys` . There need to hide from end user API Selenium and provide only our API. Now I couldn't wrap `Keys` using by standard ways in DotNet

**Comment by jimevans** [comment]
I can easily conceive of ways to “wrap” the class without extending it. I’m closing this issue as “won’t fix.”
