### ISSUE TITLE
unable to handle  ssl certification error for IE 11 

### ISSUE THREAD

**Issue by JeffGaly** [SeleniumHQ/selenium#6084]
My trying to handle SSL error with the help of below code in my app but fails to continue to browser.

capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
capabilities.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);

Using selenium version 3.5.3 
IE driver =2.45 /3.12.0 <64 bit>

**Comment by jimevans** [comment]
IE provides no way to use self-signed SSL certificates. There is no capability one can set that will make the browser behave differently. The driver can not be made to do what you want it to do. It’s a limitation of the browser and the driver.
