### ISSUE TITLE
Test Case fails when the object of the next page does not gets loaded due to bad internet speed or some other reason

### ISSUE THREAD

**Issue by Akash17101992** [SeleniumHQ/selenium#609]
Hi,

I am using Selenium IDE in my organization for the automation purpose.
I am facing an issue while executing the test case, as the test case breaks down when the object of the next page does not gets loaded due to bad internet or some other reason.
So to resolve this error what i need to do is give 'waitForElementPresent' command every time a new page is loaded.
So I want to know is there any other way to prevent the test case from failing due to these reasons.
Or can you do an update to the tool so that it will automatically add this command when a new page is loaded.

Take an example of Gmail Login:
Step1: I enter my email ID and Password and then click on LogIn
Step2: Clicking on LogIn will take me to another page
Step3: I click on ComposeMail

Now what I want to happen is:
Step1: I enter my email ID and Password and then click on LogIn
Step2: Clicking on LogIn will take me to another page
Step3: Automatically 'waitForElementPresent' command should add in the script which will wait for the object 'Compose Mail'.
Step4: I click on ComposeMail

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
