### ISSUE TITLE
Click method don't work correctly

### ISSUE THREAD

**Issue by tuean** [SeleniumHQ/selenium#6090]
## Meta -
OS:  
OSX
Selenium Version:  
selenium-java 3.10.0
Browser:  
safari

Browser Version:  
11.0.3

## Expected Behavior -
I'm trying to click a certain button but it happened nothing in run mode.
## Actual Behavior -
However, it worked while I debugger on the click line.
I want to know how to solve this problem.Thanks.

## Steps to reproduce -
The codes is as following;

        WebDriver webDriver =  new SafariDriver();
        webDriver.manage().window().maximize();
        webDriver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
        // script timeout
        webDriver.manage().timeouts().setScriptTimeout(100, TimeUnit.SECONDS);
        // pageLoad timeout
        webDriver.manage().timeouts().pageLoadTimeout(100, TimeUnit.SECONDS);
        webDriver.get("https://www.baidu.com");
        WebDriverWait wait = new WebDriverWait(webDriver, 10);

        WebElement input = webDriver.findElement(By.xpath("//*[@id=\"kw\"]"));
        input.sendKeys("tuean");

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"su\"]")));

        WebElement search = webDriver.findElement(By.xpath("//*[@id=\"su\"]")).findElement(By.xpath(".."));

        // the following is the line while I set breakpoint
        **search.click();**

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by tuean** [comment]
I didn't change any code but changed Safari to Chrome (version: 67.0.3396.87) and it works fine.
I found that the httpRequest from selenium to safari is the same and guess that maybe there are some limits in Safari WebDriver.
