### ISSUE TITLE
Warning: The server did not provide any stacktrace  information

### ISSUE THREAD

**Issue by MayaShinde** [SeleniumHQ/selenium#6091]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by MayaShinde** [comment]
Hi All, 

Yesterday only I ru my code it was working fine but today I got this warning will running the selenium script. Kindly help me 

Thanks,
Maya

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
