### ISSUE TITLE
Prometheus metrics for monitoring Selenium performance

### ISSUE THREAD

**Issue by jabbrwcky** [SeleniumHQ/selenium#6092]
Hi,

I added prometheus metrics colletion support to selenium grid (currently up to 3.11, merging currently to 3.13).

The integrated JMX interfaces did just not provide the information we wanted and we now have had an internal installation tunning nicely with prometheus metrics for a few months now.

Would you be interested to have this added to the mainline? 

I would clean up things a bit and create a PR. This would also reduce my workload chasing selenium development and merging everything.

Please let me know what you think

**Comment by barancev** [comment]
Yes, we've added initial JMX support, but the set of metrics can be expanded.

**Comment by jabbrwcky** [comment]
Ok, then I'll give it a go.

Current set of metrics include:
- Selenium version and build info (static)
- maximum concurrent sessions configured for hub
- registered nodes
- HTTP request response codes and request duration times
- HTTP request counts
- pending session requests on (hub/nodes)
- number of test slots available (nodes)
- number of test slots currently in use (nodes)
- number of active test sessions
- JVM metrics (standard prometheus JVM exporter)

Right now the metrics are opt-in, implemented by adding a thin wrapper to GridRegistry, RemoteProxy and adding metrics reporters for Jetty and the JVM.

Some thing I noted during implementation is that the repackaging of jetty prevents using existing jetty metrics exporters available for prometheus, requiring to copy the existing reporters' code to adapt it to the repackaged jetty package names.

What was/is the rationale behind repackaging Jetty?

**Comment by barancev** [comment]
We have to include two different versions of Jetty to Selenium distribution package, due to historical reasons. One of them is repacked.

**Comment by jackTheRipper** [comment]
Hello, any updates regarding this issue? I am also interested in having more metrics than the default one from JMX to monitor my Selenium Grid deployed in K8S

**Comment by dratler** [comment]
Hi @barancev ,
from which selenium version JMX is supported ?

**Comment by diemol** [comment]
Closing this as the OP didn't provide more information.
Additionally, Grid 3.x is not under development anymore.
However, Grid 4 has tracing enabled. You can see an example repo showing this here https://github.com/manoj9788/tracing-selenium-grid
