### ISSUE TITLE
Selenium Click is not working in Windows 10 IE11

### ISSUE THREAD

**Issue by CGkabila** [SeleniumHQ/selenium#6093]
We are using Selenium with C#,But Selenium click functionality is not working in Windows 10 IE11,If I am using Javascriptexecutor then its working,
But My requirement is not to use Javascriptexecutor 

((IJavaScriptExecutor)seleniumuiDriver.webDr).ExecuteScript("return document.querySelectorAll(arguments[0])[0].click();", identifier.Split('$')[0]);

When I am using Javascriptexecutor then I cant able to use ID,Xpath,Name.I can able to use only CssSelector. Is there any way to work with in IE11 
windows 10 without Javascriptexecutor

Selenium Version:2.49
Programing Language:C#

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
