### ISSUE TITLE
Python-[selenium.webdriver.support.expected_conditions] Source code for text_to_be_present_in_element(object) and text_to_be_present_in_element_value(object) exists and works but need to enable the documentation

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#6096]
## Meta - Source code for `text_to_be_present_in_element(object)` and `text_to_be_present_in_element_value(object)` exists and works but need to enable the documentation

OS:  N/A

Selenium Version:  Selenium 3.9 Documentation

Browser:  N/A

Browser Version:  N/A

## Expected Behavior - Though the following expected_conditions are functional and works well:

- `text_to_be_present_in_element(object)`
- `text_to_be_present_in_element_value(object)`

But they are not present in the documentation.

## Actual Behavior -

Documentation for `text_to_be_present_in_element(object)` and `text_to_be_present_in_element_value(object)` must be enabled.

## Steps to reproduce -

MCVE: [How to extract data from the following html?](https://stackoverflow.com/questions/50906710/how-to-extract-data-from-the-following-html/50906829#50906829)

**Comment by lmtierney** [comment]
Hmm on another note... it appears the way Simon has been generating docs hasn't been working. I'll try and release 3.13

**Comment by Debanjan-B** [comment]
Thanks @lmtierney now it seems the documentation is updated and all seems well. But the front page [Selenium Documentation](https://seleniumhq.github.io/selenium/docs/api/py/api.html) exclusively shows the text **Selenium 3.13 documentation** but the inner pages doesn't depicts this info. For example [selenium.webdriver.support.expected_conditions](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.expected_conditions.html#module-selenium.webdriver.support.expected_conditions) page.

**Comment by lmtierney** [comment]
@Debanjan-B the documentation for the expected conditions was there before I updated it to `3.13`, I just updated it because it needed to be updated to the latest. As for your example, it's listed as `3.13` at the bottom. We shouldn't need to list it on every page, the first page depicts the version.

**Comment by Debanjan-B** [comment]
@lmtierney  Thanks a lot. Closing the issue.
