### ISSUE TITLE
[Selenium Java v3.13.0] Release notes mentions allowing GSON to be   removed from our dependencies but gson-2.8.4 still present

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#6097]
## Meta - [Release notes](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG) mentions `allowing GSON to be   removed from our dependencies` but **gson-2.8.4** still present in _Selenium Java Clients_.

OS:  Windows
Selenium Version:  3.13.0
Browser:  N/A

Browser Version:  N/A

## Steps to reproduce -

gson-2.8.4
![gson-2 8 4](https://user-images.githubusercontent.com/26503213/42092137-74c2e116-7bc5-11e8-8515-50814be04a97.png)

**Comment by barancev** [comment]
It's "allowed to be removed", but not removed yet. We just get rid of Gson in all public (and non-internal) methods that will allow us to remove dependency on Gson in future when all parts of the code will be migrated to the new parser/formatter.

**Comment by Debanjan-B** [comment]
Thanks @barancev for the clarification. But any reason to include `Gson` in the build if it is **confirmed** as already marked as `"allowed to be removed"`? Do our team still suspect that the Java Client still have a dependency on `Gson`?

**Comment by diemol** [comment]
Closing as gson is not part of the 3.14.0 release
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5992658/82607284-d7800300-9bb8-11ea-86b4-2b95df7c153b.png">
