### ISSUE TITLE
Unable to handle the Authenticate window in IE11 - Windows 10

### ISSUE THREAD

**Issue by ranju4u6** [SeleniumHQ/selenium#6098]
OS:   Windows 10
Selenium-Java Version:  3.12.0
Browser:  Internet Explorer 11

While trying to perform a basic Authentication to one of my application using selenium, the code is unable to detect the presence of Alert window. This was working fine with Windows 7 & IE 11. But when the OS got upgraded to Windows 10, application is indefinitely waiting on the line 'wait.until(ExpectedConditions.alertIsPresent());'.  I know this is a duplicate issue, but in most of the cases appending the username and password did the trick, but not in our case.
'driver.get("http://<user_name>:<password>@mywebapp.com/someContext/page.jsp");'

We tried all the approach mentioned in the following link and it dint worked.
https://blog.ham1.co.uk/2016/03/05/selenium-allow-basic-auth-in-ie11/
Even after doing the registry changes, the authenticate window is popping up. 

Code:
```
	```

	DesiredCapabilities capability = DesiredCapabilities.internetExplorer();
		capability.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);
		capability.setCapability(InternetExplorerDriver.INITIAL_BROWSER_URL,"https://www.google.com/");
		
		
		WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), capability);
		driver.manage().window().maximize();
		
		driver.get("http://mywebapp.com/someContext/page.jsp");
		
		WebDriverWait wait = new WebDriverWait(driver, 10);
		wait.until(ExpectedConditions.alertIsPresent());
		
		System.out.println(driver.switchTo().alert());
	

		driver.close();

```
```
Error:
Exception in thread "main" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for alert to be present (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:271)
	at selenium.perfecto.test.SeleniumIE.main(SeleniumIE.java:56)
Caused by: org.openqa.selenium.NoSuchWindowException: Unable to get browser (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14 milliseconds

**Comment by email2vimalraj** [comment]
@ranju4u6 : Please mention the IEDriver version.

**Comment by ranju4u6** [comment]
Started InternetExplorerDriver server (32-bit)
2.53.1.0
Listening on port 5555
Only local connections are allowed

**Comment by email2vimalraj** [comment]
Hi,

Kindly upgrade your driver version to latest (3.13.0) and try.

Thanks
Vimalraj

**Comment by ranju4u6** [comment]
I upgraded the driver as well as stand alone jar to 3.13. But I am getting the following exception.

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'

But I am setting the following in capabilities.
capability.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS,true);

**Comment by jimevans** [comment]
The system-provided security credentials dialog in current versions of Windows 10 has changed drastically. It is no longer able to be automated. All attempts to inspect the window using standard tools have proven fruitless. Handling the basic authentication dialog is no longer supported by Selenium.

**Comment by ranju4u6** [comment]
@jimevans Oh. that's really a sad news. Wondering why even the 'http://<user_name>:<my_password>@mywebapp.com/someContext/page.jsp' approach is failing for IE(even after making the registry changes to avoid the security related stuff), but works for chrome. !!.

**Comment by jimevans** [comment]
That would be a question for the IE team at Microsoft. The driver is doing nothing special when navigating.

**Comment by ranju4u6** [comment]
Got you. I totally agree. Thanks a lot, for the info @jimevans .

**Comment by ranju4u6** [comment]
I am not an expert in C#.
is this the part that you are talking about?
```
            CookieContainer cookieContainer = new CookieContainer();
            HttpWebRequest req = HttpWebRequest.Create(url) as HttpWebRequest;
            req.CookieContainer = cookieContainer;
            req.KeepAlive = true;
            req.Headers.Add("Authorization", "Negotiate " + Convert.ToBase64String(data6));

            WebResponse resp = req.GetResponse();
            resp.Close();
```
how can we use the same with selenium webdriver?
