### ISSUE TITLE
Selenium Python bindings logging has hanged between 3.12.0 and 3.13.0 

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#6104]
## Meta -
OS: Ubuntu 18.04 LTS with Python 2.7.15
Selenium Version: 3.12.0 and 3.13.0
Browser: Chrome 67.0.3396.99

## Expected Behavior -
When I have this code:
```
import logging

from selenium import webdriver

logging.basicConfig(level=logging.DEBUG)
driver = webdriver.Chrome()
driver.get("http://www.python.org")
driver.save_screenshot('~/tmp.png')
driver.quit()
```
Then in Selenium 3.12.0, the logging will log the messages to the Chromedriver direction and generic `selenium.webdriver.remote.remote_connection:Finished Request` message when response is received. 
## Actual Behavior 
But in Selenium 3.13.0 logging will also log the response messages received from the Chromedriver and the `selenium.webdriver.remote.remote_connection:Finished Request` message. 

This causes logs to be quite big when example `save_screenshot`method is called, because the response message contains the coded screen shot. In [Selenium 3.12.0](https://github.com/SeleniumHQ/selenium/files/2156518/selenium3-12-0.log) log size is about 1.3Kb and in [Selenium 3.13.0](https://github.com/SeleniumHQ/selenium/files/2156519/selenium3-13-0.log) log size is about 176Kb, which is almost 90 times more. Was the change indented (and permanent) and I should reserve (a lot) more space for my tests runs? Or was this by accident and could be fixed in the next release?

## Steps to reproduce -
Run the code snipped from above.

**Comment by netzulo** [comment]
:O interesting... checking

**Comment by lmtierney** [comment]
I'm not seeing this behavior with your scenario. Maybe it was an issue with chromedriver that is not resolved? We did log the full response a few versions ago but it was immediately reverted, are you sure you are using `3.13`?

This is what I get with your code:

```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:44281/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"extensions": [], "args": []}}}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:44281/session/d80b65a5a4b3e5d80e57d8764d927b14/url {"url": "http://www.python.org", "sessionId": "d80b65a5a4b3e5d80e57d8764d927b14"}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:GET http://127.0.0.1:44281/session/d80b65a5a4b3e5d80e57d8764d927b14/screenshot {"sessionId": "d80b65a5a4b3e5d80e57d8764d927b14"}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```

**Comment by aaltat** [comment]
I will give it a new try when I return to home, should be in next week.

**Comment by aaltat** [comment]
I did try with this ChromeDriver: 
```
$ chromedriver --version
ChromeDriver 2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706)
```
And problem remains the same as previous posts. There is difference in the logging between Selenium versions 3.12.0 and 3.13.0. I did use Chrome 68.0.3440.75 (Official Build) (64-bit) in Ubuntu.

**Comment by lmtierney** [comment]
Interesting, I do see the problem in the pypi release but not in our repo. We should be releasing `3.14.0` soon and it will have the fix, otherwise I will do a point release.

**Comment by aaltat** [comment]
I can easily wait for the 3.14.0 release.

**Comment by lmtierney** [comment]
Ok, thanks for bringing this to our attention!

**Comment by lmtierney** [comment]
We now have `urllib3` as a dependency, so if you're setting your basicConfig to debug for all loggers then yes you should expect to see urllib3 logging as well.

If you want it similar behavior as before, you'll have to add this line after your `basicConfig` setup:

```
logging.getLogger('urllib3.connectionpool').setLevel(logging.WARNING)
```

**Comment by lmtierney** [comment]
Closing this as `3.14` is now out.

**Comment by aaltat** [comment]
Thanks for the details and fixing the original problem.
