### ISSUE TITLE
uploading file is working fine in chrome but getting issues while running tests in firefox using nightwatch.js 

### ISSUE THREAD

**Issue by NagarajuAkkepelli** [SeleniumHQ/selenium#6105]
hi,

while running selenium tests in firefox i am getting upload file issue using nightwatch.js. Here is the sample of my test..

uploadFile: function (file) {

this.browser.click(locators.dashboard.candidate.createResume);
this.browser.pause(timeOut);
this.browser.verify.urlContains(baseURL+'/#/candidate/create-resume');
this.browser.click(locators.createResume.chooseFileButton);
this.browser.setValue(locators.createResume.chooseFileButton, require('path').resolve(__dirname + '/' + file));
}

my specifications:
firefox version - " 60.0.2 (64-bit) ",
chrome Version 67.0.3396.99 
nightwatch v0.9.21,
node v8.11.1
"selenium-standalone": "^6.11.0",

**Comment by barancev** [comment]
Please report this issue to Nightwatch.js project
https://github.com/nightwatchjs/nightwatch
