### ISSUE TITLE
[nightwatchjs] Tests are running fine on Chrome but getting errors while running on Firefox..

### ISSUE THREAD

**Issue by NagarajuAkkepelli** [SeleniumHQ/selenium#6106]
My Tests are running fine on Chrome but getting errors while running it on firefox. I am using nightwatch.js framework. My nightwatch.js file is given below.

firefox version - " 60.0.2 (64-bit) ",
chrome Version 66.0.3359.181
nightwatch v0.9.21,
node v8.11.1
"selenium-standalone": "^6.11.0",

{
  "src_folders": [
    "test/tests"
  ],
  "output_folder": "test/reports",
  "custom_commands_path": "",
  "custom_assertions_path": "",
  "page_objects_path": "",
  "globals_path": "",
  "selenium": {
    "start_process": true,
    "server_path": "C:\\Users\\PhpstormProjects\\N@G\\firefoxjob\\Charminar\\node_modules\\selenium-standalone\\.selenium\\selenium-server\\3.8.1-server.jar",
    "log_path": "",
    "port": 4444,
    "cli_args": {
      "webdriver.chrome.driver": "C:\\Users\\PhpstormProjects\\N@G\\firefoxjob\\Charminar\\node_modules\\selenium-standalone\\.selenium\\chromedriver\\2.37-x64-chromedriver",
      "webdriver.gecko.driver": "C:\\Users\\PhpstormProjects\\N@G\\firefoxjob\\Charminar\\node_modules\\selenium-standalone\\.selenium\\geckodriver\\0.20.1-x64-geckodriver"
    }
  },
  "test_settings": {
    "default": {
      "launch_url": "http://localhost",
      "selenium_port": 4444,
      "selenium_host": "localhost",
      "silent": true,
      "screenshots": {
        "enabled": true,
        "on_failure": true,
        "on_error": true,
        "path": "test/screenshots"
      },
      "desiredCapabilities": {
        "browserName": "firefox",
        "javascriptEnabled": "1",
        "acceptSslCerts": true,
        "trustAllSSLCertificates": true,
        "acceptInsecureCerts": true,
        "marionette": true,
        "elementScrollBehavior": 1
      },
      "moz:firefoxOptions": {
        "args": [
          "window-size=1600, 1000",
          "disable-infobars",
          "disable-notifications",
          "use-fake-device-for-media-stream",
          "use-fake-ui-for-media-stream",
          "--log",
          "debug"
        ],
        "prefs": {
          "dom.ipc.processCount": 8
        }
      },
      "log": {
        "level": "trace"
      }
    },
    "chrome": {
      "desiredCapabilities": {
        "browserName": "chrome",
        "javascriptEnabled": true,
        "acceptSslCerts": true,
        "handlesAlerts": true,
        "cssSelectorsEnabled": true,
        "databaseEnabled": true,
        "rotatable": true,
        "chromeOptions": {
          "args": [
            "window-size=1600, 1000",
            "disable-infobars",
            "disable-notifications",
            "use-fake-device-for-media-stream",
            "use-fake-ui-for-media-stream"
          ]
        },
        "loggingPrefs": {
          "browser": "ALL",
          "performance": "ALL"
        }
      }
    }
  }
}

Mainly switchWindow(), moveToElement, Back commands were not working in firefox.

Any suggestions or solution for this??

Thanks in advance.

**Comment by barancev** [comment]
Please report this issue to Nightwatch.js project
https://github.com/nightwatchjs/nightwatch
