### ISSUE TITLE
[nightwatchjs] how can we take a screenshot & PDF on failure in headless chrome while running in Linux shell

### ISSUE THREAD

**Issue by NagarajuAkkepelli** [SeleniumHQ/selenium#6107]
how can we take a screenshot & PDF on failure in headless chrome while running in Linux shell..

I am using Nightwatch.js as framework for my testing and this is my nightwatch.js file..

{
  "src_folders" : ["test/tests"],
  "output_folder" : "reports",
  "custom_commands_path" : "",
  "custom_assertions_path" : "",
  "page_objects_path" : "",
  "globals_path" : "",

  "selenium" : {
    "start_process" : true,
    "server_path" : "/headless/node_modules/selenium-standalone/.selenium/selenium-server/3.7.1-server.jar",
    "log_path" : "",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "/headless/node_modules/selenium-standalone/.selenium/chromedriver/2.33-x64-chromedriver",
      "webdriver.gecko.driver" : "/headless/node_modules/selenium-standalone/.selenium/geckodriver/0.19.1-x64-geckodriver",
      "webdriver.edge.driver" : ""
    }
  },

  "test_settings" : {
    "default" : {
      "selenium_port" : 4444,
      "selenium_host" : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled": true,
        "on_failure": true,
        "on_error": false,
        "path": "/headless/test/screenshots"
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "javascriptEnabled": true,
        "chromeOptions" : {
          "binary" :"",
          "args" : [
            "window-size=1600, 1000",
            "--headless",
            "--disable-gpu",
            "--no-sandbox",
            "disable-popup-blocking disable-translate"]
        }
      }
    }
  }
}

Any suggestions for how to take screenshot and PDF's on failure..??

**Comment by barancev** [comment]
Please report this issue to Nightwatch.js project
https://github.com/nightwatchjs/nightwatch
