### ISSUE TITLE
Python and headless Firefox - Broken Pipe Error

### ISSUE THREAD

**Issue by gius-italy** [SeleniumHQ/selenium#6108]
OS:  Ubuntu 16.04 (64-bit)
Selenium Version:  3.13.0
Python Version: 3.5.2
Browser: Mozilla Firefox 60.0.2 - GeckoDriver 0.21.0 (64-bit)

## Expected Behavior -
Headless firefox webdriver should normally load the web page with the command browser.get("https://somewebpage.com")

## Actual Behavior -
browser.get(url) throws a BrokenPipeError and doesn't load the web page but it works on the second time if you rapidly give the command again 

## Steps to reproduce -
~~~~
import time
from selenium import webdriver

fox_opt=webdriver.FirefoxOptions()
fox_opt.add_argument('--headless')
with webdriver.Firefox(firefox_options=fox_opt) as browser:
    time.sleep(10)
    browser.get("https://www.google.com")   #Here you get a broken pipe error
    browser.get("https://www.google.com")   #But now everything goes fine
~~~~

**Comment by lmtierney** [comment]
Please log any Firefox & Geckodriver issues with geckodriver: https://github.com/mozilla/geckodriver/issues
