### ISSUE TITLE
Unable to find/click any elements in Safari(v11.1) on macOS

### ISSUE THREAD

**Issue by bluemoon711** [SeleniumHQ/selenium#6109]
## Meta -
OS:   10.13
Selenium Version:  
standalone 3.13 
Browser:  
Safari 11.1

Browser Version:  
Safari 11.1

## Expected Behavior -
module.exports = {
  'Demo test Google' : function (client) {
    client
      .url('http://www.google.com')
      .waitForElementVisible('body', 1000)
      .assert.title('Google')
      .assert.visible('input[type=text]')
      .setValue('input[type=text]', 'rembrandt van rijn')
      .waitForElementVisible('button[name=btnG]', 1000)
      .click('button[name=btnG]')
      .pause(1000)
      .assert.containsText('ol#rso li:first-child',
        'Rembrandt - Wikipedia')
      .end();
  }
};
## Actual Behavior -
  can't find element 'body', 'input' and 'button'
## Steps to reproduce -
I could see the safari browser is open, the url is right. After that, the browser can't recognize the elements and did nothing. The same script works fine in chrome/firefox.

**Comment by barancev** [comment]
Please report this issue to Nightwatch.js project
https://github.com/nightwatchjs/nightwatch
