### ISSUE TITLE
Request : Adding the possibility to access localStorage using node.js

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#6111]
According to the wiki (http://seleniumhq.github.io/selenium/docs/api/javascript/index.html) and all the test i made, it seems that it is impossible to access the localStorage on the client side (The localstorage that we access while pressing F12) , which is possible in all other languages. Could you add this functionnality please ?

**Comment by jleyba** [comment]
Have you tried using `driver.executeScript()`?

**Comment by Zayonx2** [comment]
How exactly should i use this ? Because i never saw anything talking about this in the documentation.

**Comment by manoj9788** [comment]
You can find it here: 
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/test/execute_script_test.js

**Comment by Zayonx2** [comment]
I meant, what does the script would looks like to get an element in the localStorage, 
When i said that i never saw anything talking about this in the documentation, i was meaning that i never saw anything talking about localStorage.

**Comment by jleyba** [comment]
It would look something like:

```js
function getLocalStorageItem(driver, key) {
  return driver.executeScript("return localStorage.getItem(arguments[0])", key);
}
```

**Comment by Zayonx2** [comment]
Getting error : "Cannot read property 'executeScript' of undefined.

**Comment by prasanth-G24** [comment]
var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(options)
    .withCapabilities(webdriver.Capabilities.chrome())
    .build();
(async function main(){
        driver.get("https://www.mydomain.com").then(()=>{
                sleep(2000).then(()=>{
                        getLocalStorageItem("myItem").then((response)=>{
                                console.log(response);
                                driver.quit();
                        });
                });
        });
})();
const sleep = ms => {
        return new Promise(resolve=>{
                setTimeout(resolve,ms);
        });
};
const getLocalStorageItem = key => {
        return driver.executeScript("return localStorage.getItem(arguments[0])", key).catch((error) => {
                console.log(error);
        });
};
This works perfectly for me

**Comment by barancev** [comment]
@jleyba Is `driver.executeScript()` the "officially recommended" way to deal with local storage? Or there is a plan to implement API for this purpose?

**Comment by AutomatedTester** [comment]
Closing as this can be done via `executeScript`
