### ISSUE TITLE
 maven dependency selenium-java 3.13.0 not found

### ISSUE THREAD

**Issue by Tsyklop** [SeleniumHQ/selenium#6114]
[## Meta -
OS:  Windows 10
Selenium Version:  Selenium Java 3.13.0
Browser:  -

I create maven project in IDEA. 

Paste dependency code from maven.central.

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.13.0</version>
        </dependency>

selenium-java 3.13.0 not found. With selenium java 3.12.0 all ok.

**Comment by barancev** [comment]
http://search.maven.org/#artifactdetails%7Corg.seleniumhq.selenium%7Cselenium-java%7C3.13.0%7Cjar

**Comment by barancev** [comment]
It is in the maven central repo, so it's either maven issue or your environment misconfiguration.
