### ISSUE TITLE
Selenium returning the hidden element as visible, clickable and enabled when element is hidden & not clickable

### ISSUE THREAD

**Issue by nagarjun64** [SeleniumHQ/selenium#6115]
## Meta -
OS:  
 OSX
Selenium Version:  
3.12.0, 3.13.0
Browser:  
Chrome, Firefox. Both are latest versions

Browser Version:  
Chrome - 67.0.3396.99
Firefox - 61.0

## Expected Behavior -
Element which is not visible, not clickable, not enabled should return false

## Actual Behavior -
Element which is not visible, not clickable, not enabled is returning true

## Steps to reproduce -
In the webapplication which is being tested, using the selenium methods to check visible and enabled and custom method to check clickable which is returning true instead of false when the element is not visible, clickable, enabled.
Raised the same issue [here](https://stackoverflow.com/questions/51136790/selenium-returning-the-hidden-element-as-visible-clickable-and-enabled-when-ele/
)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by nagarjun64** [comment]
@barancev when the element is not visible and selenium is returning true, I take it as an issue with Selenium

**Comment by barancev** [comment]
Yes, but as you narrated it, this is a question rather than an issue.

Please read the rules:
https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports
