### ISSUE TITLE
remove shebangs from all python source files

### ISSUE THREAD

**Issue by cgoldberg** [SeleniumHQ/selenium#612]
There are currently 125 python source files that are shebanged with:
`#!/usr/bin/python`

`$ grep -r "#!" ./py | wc -l`
`125`

This is not as good as:
`#!/usr/bin/env python` 

... which is more portable of a shebang line. (your target interpreter may be located somewhere besides `/usr/bin/python`)

However, all 125 shebangs are unnecessary.  This is all library code, not meant to be run at the command line.  So python does nothing with shebangs in this case.

The selenium package does not have any setuptools entry-points, or bin scripts, so these can all be safely removed.

Also, consider that the codebase is both python2 and python3 compatible.  A py2-only shebang isn't always correct.

**Comment by cgoldberg** [comment]
I will PR this if there is some agreement.

**Comment by AutomatedTester** [comment]
PR away! :)

David Burns
Email: david.burns@theautomatedtester.co.uk
URL: http://www.theautomatedtester.co.uk/
