### ISSUE TITLE
ElementClickInterceptedException is too verbose

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#6121]
## Meta -
OS:  Windows 10
Selenium Version:  3.12.0
Browser:  Internet Explorer

## Expected Behavior -
Exception text should be brief.

## Actual Behavior -
Exception text includes thousands of lines of output.

````
Element not clickable at point (1769,639). Other element would receive the click: <div ...
[followed by thousands of lines of HTML...]
````

## Steps to reproduce -
Cause the error on a large page

**Comment by jimevans** [comment]
Fixed in 663edd4
