### ISSUE TITLE
Grid: Non-Existent Route Returns 200 Status Code

### ISSUE THREAD

**Issue by dylanlive** [SeleniumHQ/selenium#6126]
## Meta
OS:  macOS
Selenium Version:  3.11, code indicates this should be in master still
Browser:  Chrome

## Expected Behavior
When visiting a page/servlet that does not exist in Grid, a 404 status code should be returned.

## Actual Behavior
A 200 status code is returned for pages that do not exist.

## Steps to reproduce
1) Launch a hub or node
2) Open your browser's network tab
3) Visit localhost:4444/thisdoesntexist

```
Request URL: http://localhost:4444/thisdoesntexist
Request Method: GET
Status Code: 200 OK
```

## More Information
It appears the design for any [non-registered routes](https://github.com/SeleniumHQ/selenium/blob/5457171bd52747eed2ab625607d29670448f4523/java/server/src/org/openqa/grid/selenium/GridLauncherV3.java#L270) to direct to `DisplayHelpServlet`, which [returns the 200](https://github.com/SeleniumHQ/selenium/blob/5457171bd52747eed2ab625607d29670448f4523/java/server/src/org/openqa/grid/web/servlet/DisplayHelpServlet.java#L122).

Considering I typed a page that should not exist, I feel it may be more obvious if a 404 is returned to indicate a problem.

Context: My application was requesting a custom servlet by the wrong name, and became confused when a 200 was returned but the proper action did not occur. A 404 would have very quickly jumped out as a route issue.

**Comment by shs96c** [comment]
We have two options here: either serve up the help page as a 404, or limit the routes that map to the display help servlet. Since the servlet's purpose is to point people in the right direction, it seems unwise to limit the routes that point people at it.

**Comment by barancev** [comment]
+1 to implement a 404 page with the help content.

**Comment by krmahadevan** [comment]
@barancev @shs96c - Can you please suggest what should the help content have? Should it contain all the references to all the valid end-points that are currently available in the grid (including both the default end-points and also the custom end-points injected) (or) should it just contain some text which says that the end-point is invalid. Based on your response, i can raise a PR accordingly.

**Comment by shs96c** [comment]
I think there may be a third option: use the current display help servlet as we do now, but only return a 200 for the root of the server and the root of wherever we have the hub situated (that is, the URL where the remote client is pointed at). In all other cases, we can return a 404. Thoughts?
