### ISSUE TITLE
AuthenticateUsing Feature required

### ISSUE THREAD

**Issue by shossain786** [SeleniumHQ/selenium#6128]
## Meta -
OS:  Windos 7

Selenium Version:  3.12

Browser: Internet Explorer

Browser Version:  11

## Expected Behavior - 
Authenticate Using function is one of the important feature which is being used in our application and widely used till 2.53.0. Since we planning to upgrade Selenium version and there are no good replacement of this feature we can not upgrade Selenium Version to the latest one. We uses testing in IE browser and this function is being used in all cases.

## Actual Behavior -
This feature need to be added back to latest version of WebDriver, so we can happily migrate to latest Selenium WebDriver version. Thank you.
## Steps to reproduce -
Pop UP Authentication to a application at the time of url launch.

**Comment by barancev** [comment]
Watch https://github.com/w3c/webdriver/issues/385, it should be added to the specification first and then it'll be implemented in drivers.

**Comment by shossain786** [comment]
Can we get any permanent solution for this? Really waiting for this feature as we want to upgrade to latest version Selenium WebDriver.

**Comment by luke-hill** [comment]
As previously mentioned, the **only** way this will be re-added is when it is **first** added to the w3c specification, which going forward _all_ browser vendors will subscribe to maintain.
