### ISSUE TITLE
Add a GridLauncher.stop method for easy integration with Commons Daemon prunsrv

### ISSUE THREAD

**Issue by rgl** [SeleniumHQ/selenium#613]
It would be really nice if there was a stop method somewhere. Currently I'm able to almost use [Commons Daemon prunsrv](http://commons.apache.org/proper/commons-daemon/procrun.html) with something like (on Windows):

```
prunsrv //IS//selenium-server-hub
  --Jvm auto ^
  --StdOutput auto ^
  --StdError auto ^
  --LogPath "%SERVICE_HOME%\logs" ^
  --StartPath "%SERVICE_HOME%" ^
  --StartMode=jvm --StartClass=org.openqa.grid.selenium.GridLauncher --StartMethod=main ^
  --StartParams "-role;hub;" ^
  --StopMode=jvm --StopClass=org.openqa.grid.selenium.GridLauncher --StopMethod=close ^
  --Classpath selenium-server.jar ^
  --JvmMs 256 ^
  --JvmMx 256
```

BUT `GridLauncher` is missing a `close` method... can we have it? :-)

I could try to implement it myself if you are willing to accept the PR. I would introduce a static variable (of Closeable/Stoppable type) and change the Hub class (and the others) to implement the Stoppable interface.

**Comment by rgl** [comment]
I think this is not really needed. I've implemented a [wrapper that calls System.exit](https://github.com/rgl/selenium-server-windows-service/blob/master/src/com/ruilopes/selenium/Service.java) and that seems to do the trick.

My end goal was to create a Windows Service... but unfortunately that will not work. For example, Chrome does not really work when run from a Windows service context... I [even documented this](https://github.com/rgl/selenium-server-windows-service).

**Comment by barancev** [comment]
So closing the issue for now.
