### ISSUE TITLE
Unable to build Selenium server standalone jar

### ISSUE THREAD

**Issue by WilliamCKTang** [SeleniumHQ/selenium#6134]
## Meta -
OS:  
Windows 8
Selenium Version:  

Hi,

Could I get assistance why I am unable to build the selenium jar? Thanks in advance.

D:\MacNode\selenium-selenium-3.7.1>go selenium-server-standalone --trace
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\HPE\LeanFT\bin\java_shared\classes";"C:\Program Files (x86)\HPE\LeanFT\bin\java_shared\classes\jasmine.jar"
(in D:/MacNode/selenium-selenium-3.7.1)
Parsing cpp/build.desc
Parsing cpp/iedriverserver/build.desc
Parsing dotnet/docs/build.desc
Parsing dotnet/test/chrome/build.desc
Parsing dotnet/test/common/build.desc
Parsing dotnet/test/edge/build.desc
Parsing dotnet/test/firefox/build.desc
Parsing dotnet/test/ie/build.desc
Parsing dotnet/test/phantomjs/build.desc
Parsing dotnet/test/remote/build.desc
Parsing dotnet/test/safari/build.desc
Parsing dotnet/test/support/build.desc
Parsing dotnet/test/webdriverbackedselenium/build.desc
Parsing ide/build.desc
Parsing ide/main/build.desc
Parsing ide/plugins/csharp-format/build.desc
Parsing ide/plugins/groovy-format/build.desc
Parsing ide/plugins/java-format/build.desc
Parsing ide/plugins/perl-format/build.desc
Parsing ide/plugins/php-format/build.desc
Parsing ide/plugins/python-format/build.desc
Parsing ide/plugins/ruby-format/build.desc
Parsing javascript/build.desc
Parsing javascript/android-atoms/build.desc
Parsing javascript/atoms/build.desc
Parsing javascript/atoms/fragments/build.desc
Parsing javascript/chrome-driver/build.desc
Parsing javascript/firefox-driver/build.desc
Parsing javascript/ie-driver/build.desc
Parsing javascript/jsunit/build.desc
Parsing javascript/node/build.desc
Parsing javascript/remote/build.desc
Parsing javascript/safari-driver/build.desc
Parsing javascript/selenium-atoms/build.desc
Parsing javascript/selenium-core/build.desc
Parsing javascript/watir-atoms/build.desc
Parsing javascript/webdriver/build.desc
Parsing javascript/webdriver/atoms/build.desc
Parsing javascript/webdriver/atoms/fragments/build.desc
Parsing javascript/webdriver/atoms/fragments/inject/build.desc
Parsing javascript/webdriver/atoms/inject/build.desc
Parsing py/build.desc
Parsing rb/build.desc
Parsing third_party/closure/build.desc
Parsing third_party/firebug/build.desc
Parsing third_party/js/sizzle/build.desc
Parsing third_party/js/wgxpath/build.desc
** Invoke selenium-server-standalone (first_time)
** Invoke //java/server/src/org/openqa/grid/selenium:selenium (first_time)
** Execute //java/server/src/org/openqa/grid/selenium:selenium
D:/MacNode/selenium-selenium-3.7.1/rake-tasks/buck.rb:37 warning: multiple Java methods for arguments (Java::OrgApacheHttpClientMethods::HttpGet), using first:
  public org.apache.http.client.methods.CloseableHttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apac
he.http.client.ClientProtocolException
  public org.apache.http.HttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientPro
tocolException
go aborted!
java.net.UnknownHostException: github.com
java.net.Inet6AddressImpl:-2:in `lookupAllHostAddr'
java.net.InetAddress$2:-1:in `lookupAllHostAddr'
java.net.InetAddress:-1:in `getAddressesFromNameService'
java.net.InetAddress:-1:in `getAllByName0'
java.net.InetAddress:-1:in `getAllByName'
java.net.InetAddress:-1:in `getAllByName'
org/apache/http/impl/conn/SystemDefaultDnsResolver.java:45:in `resolve'
org/apache/http/impl/conn/DefaultHttpClientConnectionOperator.java:112:in `connect'
org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java:359:in `connect'
org/apache/http/impl/execchain/MainClientExec.java:381:in `establishRoute'
org/apache/http/impl/execchain/MainClientExec.java:237:in `execute'
org/apache/http/impl/execchain/ProtocolExec.java:185:in `execute'
org/apache/http/impl/execchain/RetryExec.java:89:in `execute'
org/apache/http/impl/execchain/RedirectExec.java:111:in `execute'
org/apache/http/impl/client/InternalHttpClient.java:185:in `doExecute'
org/apache/http/impl/client/CloseableHttpClient.java:83:in `execute'
org/apache/http/impl/client/CloseableHttpClient.java:108:in `execute'
sun.reflect.NativeMethodAccessorImpl:-2:in `invoke0'
sun.reflect.NativeMethodAccessorImpl:-1:in `invoke'
sun.reflect.DelegatingMethodAccessorImpl:-1:in `invoke'
java.lang.reflect.Method:-1:in `invoke'
org/jruby/javasupport/JavaMethod.java:525:in `invokeDirectWithExceptionHandling'
org/jruby/javasupport/JavaMethod.java:380:in `invokeDirect'
org/jruby/java/invokers/InstanceMethodInvoker.java:58:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/CallOneArgNode.java:57:in `interpret'
org/jruby/ast/LocalAsgnNode.java:123:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/ClassVarAsgnNode.java:92:in `interpret'
org/jruby/ast/OpAsgnOrNode.java:99:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/DAsgnNode.java:110:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
org/jruby/org/jruby/RubyProc$i_method_0_0$RUBYINVOKER$call.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:216:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:212:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/CallTwoArgNode.java:59:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
org/jruby/org/jruby/RubyProc$i_method_0_0$RUBYINVOKER$call.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:216:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:212:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/CallTwoArgNode.java:59:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/CaseNode.java:138:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:336:in `yield'
org/jruby/runtime/InterpretedBlock.java:293:in `yield'
org/jruby/runtime/Block.java:130:in `yield'
org/jruby/RubyArray.java:1661:in `eachCommon'
org/jruby/RubyArray.java:1671:in `each'
org/jruby/org/jruby/RubyArray$i_method_0_0$RUBYINVOKER$each.gen:65535:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:184:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/IfNode.java:117:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/EnsureNode.java:96:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/internal/runtime/methods/AliasMethod.java:81:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:112:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:227:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/CallTwoArgNode.java:59:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:336:in `yield'
org/jruby/runtime/InterpretedBlock.java:293:in `yield'
org/jruby/runtime/Block.java:130:in `yield'
org/jruby/RubyArray.java:1661:in `eachCommon'
org/jruby/RubyArray.java:1671:in `each'
org/jruby/org/jruby/RubyArray$i_method_0_0$RUBYINVOKER$each.gen:65535:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:227:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/FCallTwoArgNode.java:38:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/EnsureNode.java:96:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/internal/runtime/methods/AliasMethod.java:81:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:227:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:302:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:173:in `call'
org/jruby/ast/FCallTwoArgNode.java:38:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallSpecialArgNode.java:65:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:184:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:336:in `yield'
org/jruby/runtime/InterpretedBlock.java:293:in `yield'
org/jruby/runtime/Block.java:130:in `yield'
org/jruby/RubyArray.java:1661:in `eachCommon'
org/jruby/RubyArray.java:1671:in `each'
org/jruby/org/jruby/RubyArray$i_method_0_0$RUBYINVOKER$each.gen:65535:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/CallNoArgBlockNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/IfNode.java:119:in `interpret'
org/jruby/ast/IfNode.java:119:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RescueNode.java:216:in `executeBody'
org/jruby/ast/RescueNode.java:120:in `interpretWithJavaExceptions'
org/jruby/ast/RescueNode.java:110:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/FCallNoArgBlockNode.java:32:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/VCallNode.java:85:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:284:in `yield'
org/jruby/runtime/InterpretedBlock.java:218:in `yieldSpecific'
org/jruby/runtime/Block.java:99:in `yieldSpecific'
org/jruby/ast/ZYieldNode.java:25:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RescueNode.java:216:in `executeBody'
org/jruby/ast/RescueNode.java:120:in `interpretWithJavaExceptions'
org/jruby/ast/RescueNode.java:110:in `interpret'
org/jruby/ast/BeginNode.java:83:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:163:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:272:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:114:in `callBlock'
org/jruby/runtime/callsite/CachingCallSite.java:123:in `callIter'
org/jruby/ast/FCallNoArgBlockNode.java:32:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:70:in `INTERPRET_METHOD'
org/jruby/internal/runtime/methods/InterpretedMethod.java:141:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:2582:in `loadFile'
org/jruby/runtime/load/ExternalScript.java:66:in `load'
org/jruby/runtime/load/LoadService.java:255:in `load'
org/jruby/RubyKernel.java:1084:in `loadCommon'
org/jruby/RubyKernel.java:1066:in `load'
org/jruby/org/jruby/RubyKernel$s_method_0_1$RUBYINVOKER$load.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:208:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:204:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:2582:in `loadFile'
org/jruby/runtime/load/ExternalScript.java:66:in `load'
org/jruby/runtime/load/LoadService.java:255:in `load'
org/jruby/RubyKernel.java:1084:in `loadCommon'
org/jruby/RubyKernel.java:1066:in `load'
org/jruby/org/jruby/RubyKernel$s_method_0_1$RUBYINVOKER$load.gen:65535:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:208:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:204:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:282:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:139:in `call'
org/jruby/ast/FCallOneArgNode.java:36:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/BlockNode.java:71:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:107:in `INTERPRET_BLOCK'
org/jruby/runtime/InterpretedBlock.java:363:in `evalBlockBody'
org/jruby/runtime/InterpretedBlock.java:317:in `yield'
org/jruby/runtime/BlockBody.java:70:in `call'
org/jruby/runtime/Block.java:89:in `call'
org/jruby/RubyProc.java:275:in `call'
org/jruby/internal/runtime/methods/ProcMethod.java:62:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:200:in `call'
org/jruby/internal/runtime/methods/DynamicMethod.java:196:in `call'
org/jruby/runtime/callsite/CachingCallSite.java:262:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:105:in `call'
org/jruby/ast/CallNoArgNode.java:61:in `interpret'
org/jruby/ast/NewlineNode.java:103:in `interpret'
org/jruby/ast/RootNode.java:129:in `interpret'
org/jruby/evaluator/ASTInterpreter.java:115:in `INTERPRET_ROOT'
org/jruby/Ruby.java:726:in `runInterpreter'
org/jruby/Ruby.java:734:in `runInterpreter'
org/jruby/Ruby.java:586:in `runNormally'
org/jruby/Ruby.java:419:in `runFromMain'
org/jruby/Main.java:304:in `run'
org/jruby/Main.java:144:in `run'
org/jruby/Main.java:113:in `main'
D:/MacNode/selenium-selenium-3.7.1/rake-tasks/buck.rb:37:in `download'
D:/MacNode/selenium-selenium-3.7.1/rake-tasks/buck.rb:53:in `buck_cmd'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
D:/MacNode/selenium-selenium-3.7.1/rake-tasks/buck.rb:269:in `(root)'
org/jruby/RubyProc.java:275:in `call'
org/jruby/RubyProc.java:235:in `call'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
org/jruby/RubyArray.java:1671:in `each'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
org/jruby/RubyArray.java:1671:in `each'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
org/jruby/RubyArray.java:1671:in `each'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31:in `(root)'
org/jruby/RubyKernel.java:1066:in `load'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:19:in `(root)'
org/jruby/RubyKernel.java:1066:in `load'
file:/D:/MacNode/selenium-selenium-3.7.1/third_party/jruby/jruby-complete.jar!/META-INF/jruby.home/bin/rake:12:in `rake'
org/jruby/RubyProc.java:275:in `call'
rake:1:in `(root)'
Exception `SystemExit' at org/jruby/RubyKernel.java:869 - exit

**Comment by barancev** [comment]
`java.net.UnknownHostException: github.com`
Check your network configuration.
