### ISSUE TITLE
Spelling mistake/Text Change

### ISSUE THREAD

**Issue by mattyb6** [SeleniumHQ/selenium#6136]
OS:  Windows 10

Selenium Version: 3.1.1, IDE

Browser:  Chrome

Browser Version:  67.0.3396.99 (64-bit)

## Steps to reproduce - 
When recording a session, where there is a Command that is 'open', click on that line. Then click on 'Reference' and under the description for open url - Opens a URL and waits for teh page to load before proceeding. This accepts both relative and absolutes URLs.

Just a spelling mistake for the which is down as teh.

![screenshot_1](https://user-images.githubusercontent.com/33258849/42517113-e3db8c80-8456-11e8-9242-f0fb9d0ad436.png)
![screenshot_2](https://user-images.githubusercontent.com/33258849/42517114-e3f95e18-8456-11e8-9fe1-06b37c13ecc7.png)

**Comment by lmtierney** [comment]
Please submit IDE issues to the IDE repo https://github.com/SeleniumHQ/selenium-ide
