### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

### ISSUE THREAD

**Issue by srinivasgoud-n** [SeleniumHQ/selenium#6141]
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.<init>(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

code snippet:

public class FirstSeleniumTest {

	WebDriver driver = null;
	String baseURL = "https://mail.google.com/";

	@BeforeMethod
	public void setup() throws InterruptedException {
		String currentDir = System.getProperty("user.dir");
		System.setProperty("webdriver.chrome.driver", currentDir + "\\executabledrivers\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.get(baseURL);
		Thread.sleep(4000);
	}

	@Test
	public void seleniumTest1() throws InterruptedException {
		System.out.println("seleniumTest1");
		driver.findElement(By.id("identifierId")).sendKeys("testautomation");

		Thread.sleep(2000);

	}

	@AfterMethod
	public void tearDown() {
		driver.close();
		driver.quit();
	}

}

OS:  Windows

Browser:  Chrome

Browser Version:  66.0.3359.181 (Official Build) (64-bit)

## Steps to reproduce -
Execute above script

**Comment by barancev** [comment]
What Selenium version do you use? Show your classpath settings, what versions of dependencies do you have in the classpath.

**Comment by srinivasgoud-n** [comment]
Selenium version: 3.13.0

This is how my classpath looks like:

<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry exported="true" kind="lib" path="lib/activation.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/ant-javamail.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/apache-mime4j-0.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/ATUReporter_Selenium_testNG_5.1.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/ATUTestRecorder_2.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/AutoItX4Java.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/bsh-1.3.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/bsh-2.0b4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cglib-nodep-2.1_3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-codec-1.10.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-collections-3.2.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-el-1.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-exec-1.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-exec-1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-io-2.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-io-2.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-jxpath-1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-lang3-3.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-lang3-3.3.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-lang3-3.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-logging-1.1.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-logging-1.1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-logging-1.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/commons-logging-1.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cssparser-0.9.11.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cssparser-0.9.14.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cssparser-0.9.16.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-core-1.2.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-java-1.1.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-junit-1.2.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-scala_2.10-1.2.0-javadoc.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-scala_2.10-1.2.0-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/cucumber-scala_2.10-1.2.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/dsn.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/extentreports-java-1.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/gherkin-2.7.7.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/gherkin-jvm-deps-1.0.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/guice-3.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/hamcrest-core-1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/hamcrest-library-1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-2.13.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-2.15.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-2.18.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-core-js-2.13.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-core-js-2.15.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/htmlunit-core-js-2.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpclient-4.3.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpclient-4.3.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpclient-4.5.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpcore-4.3.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpcore-4.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpcore-4.4.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpmime-4.3.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpmime-4.3.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpmime-4.5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/imap.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/ini4j-0.5.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/itext-2.1.7.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jacob.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jasper-compiler-5.5.15.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jasper-compiler-jdt-5.5.15.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jasper-runtime-5.5.15.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/java-client-3.2.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/javax.servlet-api-3.1.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jbehave-core-3.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jbehave-gherkin-3.7.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jbehave-junit-runner-1.0.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jcommander-1.29.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jcommander-1.48.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jcommon-1.0.23.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-continuation-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-http-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-io-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-jmx-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-security-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-server-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-servlet-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-servlets-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-util-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jetty-websocket-8.1.8.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jfreechart-1.0.19-demo.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jfreechart-1.0.19-experimental.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jfreechart-1.0.19-swt.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jfreechart-1.0.19.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jfreesvg-2.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jna-3.4.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jna-4.1.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jna-platform-3.4.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jna-platform-4.1.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/json-20080701.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jsp-api-2.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/junit-4.11.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/junit-4.12.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/junit-dep-4.11.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/junit.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jxl-2.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/log4j.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/mail.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/mailapi.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/maven-surefire-plugin-2.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/nekohtml-1.9.19.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/nekohtml-1.9.21.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/nekohtml-1.9.22.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/netty-3.5.7.Final.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/operadriver-1.5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/orsoncharts-1.4-eval-nofx.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/orsonpdf-1.6-eval.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/phantomjsdriver-1.1.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/phantomjsdriver-1.2.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-3.9.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/pop3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/protobuf-java-2.4.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/reportng-1.1.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/sac-1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/saxon-8.7.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/SaxonLiaison.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/selenium-java-2.53.1-srcs.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/selenium-java-2.53.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/selenium-safari-driver-2.29.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/serializer-2.7.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/serializer-2.7.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/servlet.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/sikuli-java.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/smtp.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/swtgraphics2d.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/testlink-api-client-2.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/testng-6.9.9.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/testserver-cucumber-core-1.0.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/velocity-dep-1.4.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/websocket-api-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/websocket-client-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/websocket-common-9.2.13.v20150730.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/ws-commons-util-1.0.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xalan-2.7.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xalan-2.7.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xercesImpl-2.10.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xercesImpl-2.11.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xml-apis-1.4.01.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xmlrpc-client-3.1-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xmlrpc-client-3.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xmlrpc-common-3.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jna-4.2.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-ooxml-3.5-beta5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-examples-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-excelant-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-ooxml-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-ooxml-schemas-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/poi-scratchpad-3.17.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/groovy-2.4.9.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/groovy-json-2.4.9.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpclient-4.5.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpcore-4.4.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/httpmime-4.5.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/json-path-3.0.5-javadoc.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/json-path-3.0.5-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/rest-assured-3.0.5-javadoc.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/rest-assured-3.0.5-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/rest-assured-3.0.5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/rest-assured-common-3.0.5-javadoc.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/rest-assured-common-3.0.5-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/tagsoup-1.2.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xml-path-3.0.5-javadoc.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/xml-path-3.0.5-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/com.springsource.javax.media.jai.codec-1.1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/com.springsource.javax.media.jai.core-1.1.3.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/jmf-2.1.1e.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/monte-repack-1.0.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/testng-6.8.5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/testng-6.9.6.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/byte-buddy-1.7.5.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/client-combined-3.8.1-sources.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/client-combined-3.8.1.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/gson-2.8.2.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/guava-23.0.jar"/>
	<classpathentry exported="true" kind="lib" path="lib/selenium-server-standalone-3.13.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by barancev** [comment]
@srinivasgoud-n: You comment looks incomplete.

**Comment by srinivasgoud-n** [comment]
[classpath.txt](https://github.com/SeleniumHQ/selenium/files/2183554/classpath.txt)

**Comment by barancev** [comment]
You have
```
	<classpathentry exported="true" kind="lib" path="lib/selenium-java-2.53.1.jar"/>
```
in the classpath that causes collisions.

**Comment by barancev** [comment]
Also
```
	<classpathentry exported="true" kind="lib" path="lib/client-combined-3.8.1.jar"/>
```
Never include multiple versions of the same library to the classpath!

**Comment by srinivasgoud-n** [comment]
removed above two entries from classpath. still facing same issue..

**Comment by barancev** [comment]
This is a question rather than an issue. Or al least it's not a Selenium issue but your project misconfiguration. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by mkienenb** [comment]
Caused when your version of selenium is too old and guava is too new.    guava > 22.0 will generate this error.  Either downgrade to guava.22.0 or upgrade selenium.

See here 
https://github.com/SeleniumHQ/selenium/issues/4381
