### ISSUE TITLE
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

### ISSUE THREAD

**Issue by srinivasgoud-n** [SeleniumHQ/selenium#6142]
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

code snippet:

public class FirstSeleniumTest {

WebDriver driver = null;
String baseURL = "https://mail.google.com/";

@BeforeMethod
public void setup() throws InterruptedException {
	String currentDir = System.getProperty("user.dir");
	System.setProperty("webdriver.chrome.driver", currentDir + "\\executabledrivers\\chromedriver.exe");
	driver = new ChromeDriver();
	driver.get(baseURL);
	Thread.sleep(4000);
}

@Test
public void seleniumTest1() throws InterruptedException {
	System.out.println("seleniumTest1");
	driver.findElement(By.id("identifierId")).sendKeys("testautomation");

	Thread.sleep(2000);

}

@AfterMethod
public void tearDown() {
	driver.close();
	driver.quit();
}
}

OS: Windows

Browser: Chrome

Browser Version: 66.0.3359.181 (Official Build) (64-bit)

Expected Behavior - Chrome browser has to be launched
Actual Behavior - Getting exception: java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker
Steps to reproduce -
Execute above script

**Comment by srinivasgoud-n** [comment]
[classpath.txt](https://github.com/SeleniumHQ/selenium/files/2183793/classpath.txt)

**Comment by barancev** [comment]
Duplication of #6141
