### ISSUE TITLE
Socket not found exception, Multiple test runs fails

### ISSUE THREAD

**Issue by FabianO0815** [SeleniumHQ/selenium#6145]
## Meta -
OS:  
Windows 10 1803

Selenium Version:  
3.13.1.0
Browser: 
Chrome Version 67.0.3396.99 (Offizieller Build) (64-Bit)
chromedriver.exe 2.40.0 from Nuget

Browser Version:  
67.0.3396.99 (Offizieller Build) (64-Bit)

Test Framework:
xUnit

Programming IDE:
Visual Studio 2017 v15.7.5

## Expected Behavior -
Select multiple test from test explorer and run in debug mode
## Actual Behavior -
Select multiple test from test explorer and run in debug mode.  Only the first test finished succesfuly.
When the second test wants to initialize the driver it crashes with the folowing exception:

`Testname:	SellyconSelniumXUnit.ChromeTests.ChromeUploadDxfConfigurator
Test FullName:	SellyconSelniumXUnit.ChromeTests.ChromeUploadDxfConfigurator
Testquelle:	D:\workspace\...\...\ChromeTests.cs Zeile 39
Testergebnis:	Fehlgeschlagene
Testdauer:	0:00:41,699

Ergebnis StackTrace:	
----- Inner Stack Trace #1 (OpenQA.Selenium.WebDriverException) -----
   bei OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.Remote.RemoteTimeouts.ExecuteSetTimeout(String timeoutType, TimeSpan timeToWait)
   bei OpenQA.Selenium.Remote.RemoteTimeouts.set_PageLoad(TimeSpan value)
   bei SellyconSeleniumLibrary.WrapperFactory.BrowserFactory.InitBrowser[T,TDriver](Action`1 optionCallback, TDriver tdriver)
   bei SellyconSelniumXUnit.ChromeTests.ChromeUploadDxfConfigurator() in D:\workspace\SellyconSeleniumIntegration\SellyconSelniumXUnit\ChromeTests.cs:Zeile 41.
----- Inner Stack Trace #2 (OpenQA.Selenium.WebDriverException) -----
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Close()
   bei SellyconSeleniumLibrary.WrapperFactory.BrowserFactory.CloseDriver()
   bei SellyconSelniumXUnit.ChromeTests.Dispose() in D:\workspace\SellyconSeleniumIntegration\SellyconSelniumXUnit\ChromeTests.cs:Zeile 267.
   bei Xunit.Sdk.ExecutionTimer.Aggregate(Action action)
   bei ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
   bei Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<RunAsync>b__1()
   bei Xunit.Sdk.ExceptionAggregator.Run(Action code)
----- Inner Stack Trace -----
   bei System.Net.HttpWebRequest.GetResponse()
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
----- Inner Stack Trace -----
   bei System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
Ergebnis Meldung:	
System.AggregateException : Mindestens ein Fehler ist aufgetreten.
---- OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 127.0.0.1:63311
   bei System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   bei System.Net.HttpWebRequest.GetRequestStream()
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
---- OpenQA.Selenium.WebDriverException : A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:63311/session//window. The status of the exception was ConnectFailure, and the message was: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
-------- System.Net.WebException : Die Verbindung mit dem Remoteserver kann nicht hergestellt werden.
------------ System.Net.Sockets.SocketException : Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 127.0.0.1:63311

`

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
