### ISSUE TITLE
Selenium IE driver is not retaining session when opens multiple IE windows through automated script

### ISSUE THREAD

**Issue by Rialakshmi** [SeleniumHQ/selenium#6148]
## Meta -
OS:  Windows 7 and Windows 10

Selenium Version:  
2.47.1

Browser:
Internet Explorer - 11  

Browser Version:  

IE -11.0.9600.19035
## Expected Behavior -
Newly opened window should retain the session (credential information provided in parent window).
## Actual Behavior -
Credentials are getting lost. Newly opened window again asks for the credentials.
## Steps to reproduce -

I followed the below points:-
Required Configuration
The IEDriverServer exectuable must be downloaded and placed in your PATH.
On IE 7 or higher on Windows Vista or Windows 7, you must set the Protected Mode settings for each zone to be the same value. The value can be on or off, as long as it is the same for every zone. To set the Protected Mode settings, choose "Internet Options..." from the Tools menu, and click on the Security tab. For each zone, there will be a check box at the bottom of the tab labeled "Enable Protected Mode".
Additionally, "Enhanced Protected Mode" must be disabled for IE 10 and higher. This option is found in the Advanced tab of the Internet Options dialog.
The browser zoom level must be set to 100% so that the native mouse events can be set to the correct coordinates.
For Windows 10, you also need to set "Change the size of text, apps, and other items" to 100% in display settings.
For IE 11 only, you will need to set a registry entry on the target computer so that the driver can maintain a connection to the instance of Internet Explorer it creates. For 32-bit Windows installations, the key you must examine in the registry editor is HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. For 64-bit Windows installations, the key is HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BFCACHE. Please note that the FEATURE_BFCACHE subkey may or may not be present, and should be created if it is not present. Important: Inside this key, create a DWORD value named iexplore.exe with the value of 0.

The code tries to connect to RemoteWebdriver. it tries to launch multiple courses in a parent window.
CODE:-
------------
browserCapabilities= DesiredCapabilities.internetExplorer();            browserCapabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
browserCapabilities.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);
browserCapabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
 browserCapabilities.setCapability(InternetExplorerDriver.INITIAL_BROWSER_URL, url);
driver = new RemoteWebDriver( new URL(REMOTE_HUB),browserCapabilities);
driver.navigate().to(url);
 driver.manage().window().maximize();
   String scriptcurriculum = "javascript: var launchID=document.getElementById('" + curriculumButton + "');" +"if(null!=launchID) {document.getElementById('" + curriculumButton + "').getElementsByTagName('button')[0].click();}";
            ((JavascriptExecutor) driver).executeScript(scriptcurriculum);

Now it loses the session and ask me to enter credentials in new window.

The same code works perfectly for Firefox and Chrome

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by Rialakshmi** [comment]
Please close. I did some wrong programming. While I try to give you concise reproducible test case, I got the answer by myself.

**Comment by lorby** [comment]
Rialakshmi, would you mind sharing how you fixed this? I am having a similar issue where new IE windows opened do not share the same session as the selenium window (and require logindetails etc. again). Thank you.
