### ISSUE TITLE
Waiting for element to become stale on Safari fails, even though element is gone.

### ISSUE THREAD

**Issue by MicahLC** [SeleniumHQ/selenium#6152]
## Meta
OS: 
OS X Sierra
Selenium Version: 
3.13.0
Browser: 
Safari
Browser Version:  
11.1.2

## Expected Behavior
Every time I wait for an element to become stale in a test on Safari, it should pass.
## Actual Behavior
Sometimes, waiting for an element that is clearly gone from the DOM to become stale fails, but only on Safari.

## Steps to reproduce
Check out the repository I've got here: https://github.com/MicahLC/safari_selenium_bug
It should be self-contained; you'll just need to run `mvn test` on an OS X machine with Safari automation enabled.
This test, unfortunately, does not fail every time. I've had pretty good success getting it to fail within the first 5-10 times running it. I have also found that once it starts failing, subsequent runs with the same open instance of Safari continue to fail.

## Background

I'm a test automation dev at Zappos and have noticed that our tests that wait for `stalenessOf` fail very regularly on iOS devices and Safari. Hence why this test uses Zappos.com.

**Comment by MicahLC** [comment]
I forgot to mention that this issue doesn't occur on other browsers. I've included the option to run on Safari, Chrome, and Firefox so you can try it out.

**Comment by BuffaloBuffalo** [comment]
I forked the reproduction case with a more concise html page for reproducing, if that helps

https://github.com/BuffaloBuffalo/safari_selenium_bug

**Comment by Michael-Stanford** [comment]
I have this issue, too. Not intermittent - happens every time.
OS X Version 10.13.6 (17G65)
Safari Version 11.1.2 (13605.3.8)
selenium-webdriver v4.0.0-alpha 1

**Comment by diemol** [comment]
Are you still having this issue with the most recent version of Safari and the Selenium bindings (beta-2)?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
