### ISSUE TITLE
Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 (\'There are no more files.\') 

### ISSUE THREAD

**Issue by santhoshrenga** [SeleniumHQ/selenium#6155]
OS:  
Windows Server 2016
Selenium Version:  
3.4.0
Browser:  
Internet Explorer 11

I have setup the selenium cluster with IE browser to test Nightwatch automation script on daily basis. I'm using 32 bit IE driver. 

ISSUE:
- Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070012 (\'There are no more files.\') 

I'm getting the above error message and it requires me to restart my ec2 instance to get this error resolved.

I have configured the latest configuration suggested by selenium GitHub repository but no luck.
appreciate your quick response. thanks in advance.

**Comment by barancev** [comment]
This is a generic system error. See [1] and [2] for recommendations. Also upgrade Selenium  and IEDriverServer to the latest version (3.13 at the moment).

[1] https://answers.microsoft.com/en-us/windows/forum/windows_7-files/there-are-no-more-files-error-whenever-i-try-to/73df3ecf-f02b-4b9e-aa3e-86a4c7604241
[2] https://windowsreport.com/there-are-no-more-files/
