### ISSUE TITLE
Alert.sendKeys(String) always send text to first input box irrespective of cursor location

### ISSUE THREAD

**Issue by akhanna38** [SeleniumHQ/selenium#6157]
Alert.sendKeys(String) always send text to first input box irrespective of cursor location
OS:  Win7
Selenium Version:  3.13.0
Browser:  IE11

I am trying to send username and password to security popup on IE11 but both values goes to username field only.
Here is the code snippet. I will try to find a public website to reproduce this.

`Alert alert = driver.switchTo().alert();
			Thread.sleep(2000);
			Robot r = new Robot();
			alert.sendKeys("username");
			Thread.sleep(2000);
			r.keyPress(KeyEvent.VK_TAB);
			r.keyRelease(KeyEvent.VK_TAB);
			Thread.sleep(2000);
			alert.sendKeys("password");
			Thread.sleep(2000);
			alert.accept();`

**Comment by jimevans** [comment]
Attempting to use `Alert.sendKeys` on a credentials dialog is unsupported. Moreover, even attempting to switch to the alert on Windows 10 won’t work, because the login dialog cannot be automated (it’s opaque to all attempts at reading the dialog’s controls).
