### ISSUE TITLE
Getting “java.net.SocketException: Software caused connection abort: recv failed” Exception while using Gecko driver 21.0

### ISSUE THREAD

**Issue by TagoreRavindra** [SeleniumHQ/selenium#6164]
Hi All,

I’m using

Latest Gecko Driver-21.0

Firefox Version-61.0.1

Selenium Stand Server -3.13

I’m getting Exception “java.net.SocketException: Software caused connection abort: recv failed” while handling the child window

I’m getting the above issue at driver.getWindowhandles() Statement

Can anyone look into this

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by TagoreRavindra** [comment]
Hi barancev,
**Test Scenario:** Click on One button and it will open up a new window and we've to verify text in child window and close the child window and come back to parent window
For this i'm getting "java.net.SocketException:Software caused connection abort: recv failed" Exception
When i'm debugging the code its throwing the above exception at "driver.getWindowHandles()" Statement
But when i'm using Gecko driver -20.1 Version its working fine

**Comment by barancev** [comment]
Please provide an executable scenario in a programming language that can be just copied and run to reproduce the issue.

**Comment by Deepti-10** [comment]
Hi, I am facing he same issue with:
Latest Gecko Driver-21.0

Firefox Version-61.0.1

Selenium Stand Server -3.13

Earliest help would be very useful. Thanks.

**Comment by chalakprabhu** [comment]
provide details log and program

**Comment by Deepti-10** [comment]
***Snippet of method to open a new window.***
 public static void OutemailValidation(TestDataDTO testDataDTO, WebDriver driver) throws Exception {		    	   
		    	   System.out.println("Inside OutemailValidation Method");	  
			             String originalHandle = driver.getWindowHandle();  // Get the current window handle			              
			              System.out.println(originalHandle);
			              //Open New Tab to login to Gmail
			              driver.findElement(By.cssSelector("body")).sendKeys(Keys.CONTROL + "t");
			              ArrayList tabs = new ArrayList(driver.getWindowHandles());
				      System.out.println(tabs.size());
			              driver.get("gmail.com");
			              Thread.sleep(5000);

Exception received:
java.net.SocketException: Software caused connection abort: recv failed

Note: The output "Inside OutemailValidation Method" is displayed. But received  exception at the line- String originalHandle = driver.getWindowHandle();

**Comment by TagoreRavindra** [comment]
Hi Deepti,

I've also got the same issue
We need to down grade our Gecko driver to 20.0, then we can able to handle the windows
Latest Gecko Driver 21.0 is not supporting the Window handle properly(Some times it works, Some time may not)
So, from my side-We should use Gecko Driver 20.0 until Gecko Driver 21.0 is fully implemented 

Thanks
Tagore

**Comment by chalakprabhu** [comment]
down vote
Set<String> windows = driver.getWindowHandles();
Iterator<String> itr = windows.iterator();

//patName will provide you parent window
String patName = itr.next();

//chldName will provide you child window
String chldName = itr.next();

//Switch to child window
driver.switchto().window(chldName);

//Do normal selenium code for performing action in child window

//To come back to parent window
driver.switchto().window(patName);



try this one it will work

**Comment by TagoreRavindra** [comment]
Hi Deepti,

I'm using below code for window handling, can you try and let me know

//To get Parent window
String ParentWindow=driver.getWindowHandle();

//To Get Child Window
Set<String> ChildWindow=driver.getWindowHandles();

int windowsize = driver.getWindowHandles().size();
if(windowsize>1)
{
for(String windowhandle : ChildWindow)
{
if(!windowhandle.equals(Parentwindow))
{
driver.switchto().window(windowhandle)

//perform some actions on Child window
}
}
}
In the above code, I'm getting the below error
Getting “java.net.SocketException: Software caused connection abort: recv failed”

Can you try and let me know

**Comment by chalakprabhu** [comment]
ok

**Comment by SandeepPadhy** [comment]
Thanks Ravindra for your suggestion,seems a workaround for time being. After downgrading the geckodriver version to 20x i am able to continue with my work.

**Comment by SandeepPadhy** [comment]
Also Please let me know how to wait for window popup to come alive before i run the driver.getWindowHandles() command to capture the window id's. Is there any way?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.

**Comment by TagoreRavindra** [comment]
Thanks @barancev
