### ISSUE TITLE
Issue with running webdriverio tests in parallel with selenium grid

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#6165]
## Meta -
OS: docker for mac
Selenium Version: 3.11.0
Browser:  Chrome

## Expected Behavior -
Should be able to run parallel tests with selenium grid

## Actual Behavior -
Tests start to fail as soon as number of chrome nodes become more than 2

## Steps to reproduce -
I am running webriverio ui tests with mocha framework in selenium grid. The selenium grid set up is done using docker-compose. I am only using chrome nodes in selenium grid. 

My tests start to fail when the number of chrome nodes becomes more than 2. I am specifying same value for ‘maxInstances’ property in test runner and ‘NODE_MAX_INSTANCES’ in docker-compose.yml. Using vnc viewer, I see that it launches same number of parallel browser as mentioned in ‘maxInstances’ property (3, in this case). But tests start to fail when parallel browser count becomes more than 2. I have a total of 12 test spec files grouped in as many test suites.

I don’t understand why this is happening only with increase in number of nodes. The final error shown in logs is session terminated due to BROWSER_TIMEOUT.  Please find attached my test container logs. I have set logging level to ‘verbose’. I have also attached logs for successful test run when only 1 chrome node is part of grid.

[parallelTestsSuccess.pdf](https://github.com/SeleniumHQ/selenium/files/2197666/parallelTestsSuccess.pdf)
[parallelTestFailures.pdf](https://github.com/SeleniumHQ/selenium/files/2197667/parallelTestFailures.pdf)

**docker-compose.yml:**
version: '3'
services:
  app:
    image: jobz_web_employer
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
    - NODE_ENV=production
    - CONFIG_ENV=staging
    - CONFIG_CUSTOM_API=https://blah.de
    restart: always

  seleniumhub:
    image: "selenium/hub:3.11.0"
    container_name: shub
    restart: always
    ports:
    - 4444:4444
    environment:
    - GRID_MAX_SESSION="20"
    - GRID_BROWSER_TIMEOUT=100
    - GRID_TIMEOUT=90

  chromenode:
    image: "selenium/node-chrome-debug:3.11.0"
    container_name: chrome
    restart: always
    ports:
    - 5900
    depends_on:
    - seleniumhub
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    - NODE_MAX_INSTANCES=3
    - NODE_MAX_SESSION=3
    links:
    - jobz_web_employer_proxy:blah.blah.de
    - seleniumhub:hub
    
  jobz_web_employer_proxy:
    image: jobz_web_employer_proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
    - 80:80
    restart: always
    depends_on:
    - app
    links:
    - app

  tests:
    image: jobz_web_employer
    command: yarn wdio
    environment:
    - NODE_ENV=production
    - CONFIG_ENV=staging
    - PORT=80
    depends_on:
    - seleniumhub
    links:
    - seleniumhub:hub

My test runner (**wdio.ci.conf.js**) is below:
exports.config = merge(wdioConf.config, {
  host: 'shub',
  port: 4444,
  capabilities: [
    {
      browserName: 'chrome',
      maxInstances: 3,
      chromeOptions: {
        args: [
          '--disable-blink-features=BlockCredentialedSubresources',
          '--window-size=1024,768',
          '--no-sandbox'
        ]
      }
    }
  ],
  baseUrl: 'http://blah:80'

**Comment by barancev** [comment]
`BROWSER_TIMEOUT` is just a side effect. You called `log` command that is not supported at the moment, and this command killed the driver. And you called `log' command for a reason, because something bad happened to the element with id=carousel-dropzone. I bet you'll have the same issue if you run tests in parallel locally (without selenium server) too. And if you are really sure that it's a selenium server issue, we'll need a reproduction scenario with the vanilla selenium client but not webdriver.io
