### ISSUE TITLE
webdriver.firefox.bin property is ignored

### ISSUE THREAD

**Issue by b71729** [SeleniumHQ/selenium#6167]
## Meta -
OS:  **Windows 10**
Selenium Version:  **Standalone 3.13.0**
Browser:  **Firefox 61.0.1, Geckodriver 0.21.0**
Browser Version:   **Firefox 61.0.1 64bit, Geckodriver 0.21.0**

## Expected Behavior -
According to https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver#important-system-properties, running selenium server in standalone mode with `webdriver.firefox.bin` property set should overwrite the path to Firefox binary.

```
java -jar -Dwebdriver.gecko.driver=C:/latest/geckodriver.exe -Dwebdriver.firefox.bin=C:/latest/firefox.exe selenium-server-standalone-3.13.0.jar
```

I can confirm the `gecko.driver` property is respected, but `firefox.bin` is not.

## Actual Behavior -
Taken from Selenium Server stdout:

```
16:30:57.049 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'

16:30:57.049 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444 2018-07-16 16:30:57.133:INFO::main: Logging initialized @325ms to org.seleniumhq.jetty9.util.log.StdErrLog

16:30:57.505 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444  

16:31:03.858 INFO [ActiveSessionFactory.apply] - Capabilities are: {"browserName": "firefox"} 

16:31:03.858 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService) 

1531755064043   geckodriver INFO geckodriver 0.20.11531755064043   geckodriver INFOListening on 127.0.0.1:47151

>>>>> 1531755064913   mozrunner::runner   INFO Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\TMP\\AppData\\Local\\Temp\\rust_mozprofile.Cl9EnxGqZEea" <<<<<
```

## Steps to reproduce -
```
java -jar -Dwebdriver.gecko.driver=C:/latest/geckodriver.exe -Dwebdriver.firefox.bin=C:/latest/firefox.exe selenium-server-standalone-3.13.0.jar
```
Run above snippet on Windows 10, with geckodriver 0.21.0 and selenium standalone 3.13.0.

---

**NOTE** I have tried modifying the contents of `webdriver.firefox.bin` as passed through to follow other path conventions, i.e. Unix and with backslashes rather than forwardslashes. Nothing works. The system-installed Firefox is *always* launched.

**Comment by b71729** [comment]
There is a workaround (sort-of): launch geckodriver as a standalone server with the `-b` argument pointing at the desired firefox executable, i.e.:

```
geckodriver.exe -b path\to\firefox.exe
```

This does carry the caveat of not being able to co-exist with other browsers on the same port.

**Comment by diemol** [comment]
This has been fixed for Grid 4, will be available in the next Alpha release.

**Comment by ygmarchi** [comment]
Working patch for version 3.141.59

[diff.txt](https://github.com/SeleniumHQ/selenium/files/5694252/diff.txt)
