### ISSUE TITLE
Class cast exception in RemoteLocationContext.location()

### ISSUE THREAD

**Issue by AJ-72** [SeleniumHQ/selenium#6174]
## Meta -
OS:  
Windows 8.1, 10
Selenium Version:  
3.2
Browser:  
Chrome
Browser Version:  
62

## Expected Behavior -
org.openqa.selenium.remote.html5.RemoteLocation.location() should provide the physical location of the browser.

## Actual Behavior -
org.openqa.selenium.remote.html5.RemoteLocation.location() throws class cast exception - java.lang.Long cannot be cast to java.lang.Double

## Steps to reproduce -
```
public static void main(String args[]) throws MalformedURLException {
		RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),DesiredCapabilities.chrome());
		LocationContext lContext = (LocationContext)new Augmenter().augment(driver);
		Double latitude,longitude;
		latitude=43.1231;
		longitude=4.234;
		lContext.setLocation(new Location(latitude, longitude, 2));
		System.out.println(lContext.location().getLatitude());				
	}
```
Changing the class member variables in Location class from Double to Long should fix the issue, I think. I can provide a PR if that should be enough.

**Comment by barancev** [comment]
Fixed by 8e308c57954f94692171d4381035bab8c872c5a4
