### ISSUE TITLE
How to handle custom event using Selenium Nodejs driver?

### ISSUE THREAD

**Issue by Surya97** [SeleniumHQ/selenium#6175]
I am actually trying to handle a custom event and when the event is successfully listened I want to access some variable from browser console from my script. Code I am trying is https://jsfiddle.net/82z4qcmu/5/ , 
But I am getting error saying "element is not defined"

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
