### ISSUE TITLE
parseHttpResponse should indicate which command is unsupported

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#6180]
## Meta -
OS:  Windows 10
Selenium Version: selenium-webdriver@4.0.0-alpha.1
Browser: For testing, Internet Explorer
Browser Version: 11

## Expected Behavior -

When your browser driver doesn't support a command, it can be useful to know _which_ command isn't supported.

## Actual Behavior -

Here's the report you get:

```
UnsupportedOperationError: Error 404: Not Found
    Not Found

      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:558:11)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
```

Tracing this down, `let value = httpResonse.body.replace(/\r\n/g, '\n');` could have `command.getName() + ': '` prepended. I can do that if you don't mind?

## Steps to reproduce -

Send a `close` command to `IEDriverServer.exe`.

I'm accomplishing this by using `jest-webdriver` and `jest-dev-server`.

**Comment by jleyba** [comment]
I'm way behind on Selenium work and not sure when I'll be able to get to this. Feel free to send a PR for any changes you'd like to make.
