### ISSUE TITLE
Erroneous log on hub (Marking the node http://192.168.137.1:5566 as down: cannot reach the node for 2 tries) and connection timeout on grid console

### ISSUE THREAD

**Issue by mishrasanjeetr** [SeleniumHQ/selenium#6184]
## Meta -
OS:  Windows 10
Selenium Version: 3.13.0

Browser:  Chrome

Browser Version:  Version 67.0.3396.99 (Official Build) (64-bit)

## Steps to reproduce -1.Start hub by using :   java -jar selenium-server-standalone-3.13.0.jar -role hub
                                       2.start node by using : java -Dwebdriver.chrome.driver="D:\chromedriver.exe" -jar selenium-server-standalone-3.13.0.jar -role webdriver -hub http://192.168.1.3:4444/grid/register -port 5566
                                     3.Launch grid console by using: http://192.168.1.4:4444/grid/console
 
![gridconsole](https://user-images.githubusercontent.com/41361533/42959553-dedb9b60-8ba6-11e8-869e-ec6bc6da41fa.png)

**Comment by netzulo** [comment]
check if your port it's open first... have you tried to type 

+ from hub machine : `telnet 192.168.137 5566` and get PASSED test ?
+from node machine: `telnet /192.168.1.4 4444` and get PASSED test ?

after this... maybe you can open an issue here... but... this isn't a forum , please, refer to : https://www.seleniumhq.org/support/

**Comment by mishrasanjeetr** [comment]
I have tried this command(telnet 192.168.137.1 5566) and found following log from hub machine D:\>telnet 192.168.1.4:4444
'telnet' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cgoldberg** [comment]
@mishrasanjeetr install a telnet client to use telnet

**Comment by mishrasanjeetr** [comment]
@netzulo 
I have checked and found it's not connected Following error message is displayed.
Could not open connection to the host, on port 5566: Connect failed
