### ISSUE TITLE
Chrome didn't shut down correctly

### ISSUE THREAD

**Issue by MaxGsomGsom** [SeleniumHQ/selenium#6185]
## Meta
OS:  Windows 10
Selenium Version:  3.12.0-3.13.1
IDE: Visual Studio 2017, C#
Browser:  Chrome 65-67, ChromeDriver 2.38.0-2.40.0

## Expected Behavior
Calling driver.Close(), driver.Quit() or driver.Dispose() correctly closes browser

## Actual Behavior
When custom user-data-dir used, calling one of these function closes browser. But after reopening with the same user-data-dir browser shows message "Chrome didn't shut down correctly".

## Steps to reproduce
1. Specify new user-data-dir, create new instance of chromedriver and run it
2. Open any web site
3. Call driver.Quit() or driver.Dispose() to close browser
4. Create new instance of chromedriver with the same user-data-dir and run it
5. "Chrome didn't shut down correctly" message will appear

**Comment by barancev** [comment]
Please report this issue to chromedriver project: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by VinickGold** [comment]
Hi @MaxGsomGsom, same behavior here. How did you fix that?

**Comment by MaxGsomGsom** [comment]
I have not found solution. But there is possible workaround: write a program that closes "Chrome didn't shut down correctly" prompt.
