### ISSUE TITLE
The config.json parameters are not used correctly in selenium grid 

### ISSUE THREAD

**Issue by Kalste** [SeleniumHQ/selenium#6188]
## Meta -
OS:  
Windows 7
Selenium Version:  
Java 3.13
Browser:  
Firefox
Browser Version:  
ESR 60.0.1

## Expected Behavior -
I have a selenium grid with one hub and one node. The hub and the node are on different windows 7 machines.
I use for both hub and node a config.json file.
The hub is started with:
```
java -jar selenium-server-standalone-3.13.0.jar -role hub -hubConfig confighub.json
```

and the node with
```
java -Dwebdriver.gecko.driver="C:/LPROG/Ldev/selenium_grid/geckodriver-v0.21.0-win32.exe" -jar selenium-server-standalone-3.13.0.jar -role node -nodeConfig confignode.json
```

The json files are attached but renamed in txt files.

Both json files include the debug parameter with the value true.
But the grid says for the hub the final configuration is debug false, see screenshots and logs.
For the node is debug false too.

The json files include servlets for the hub and the node.
The node uses the parameters correct but not the hub, see screenshots and logs.

The debug value should be true and the servlets should be used.

![hub_3 13](https://user-images.githubusercontent.com/33020490/43006971-5661a9f0-8c37-11e8-8caa-cd715c735ca0.jpg)

[Uploading lognode_3.13.txt…]()
![node_3 13](https://user-images.githubusercontent.com/33020490/43007068-93cc3c92-8c37-11e8-9c26-737bc454f2ac.jpg)
![Uploading node_3.13.jpg…]()
[confighub.txt](https://github.com/SeleniumHQ/selenium/files/2214219/confighub.txt)
[confignode.txt](https://github.com/SeleniumHQ/selenium/files/2214220/confignode.txt)

**Comment by Kalste** [comment]
Something wnt wrong, here are the log files
[hublog_3.13.txt](https://github.com/SeleniumHQ/selenium/files/2214227/hublog_3.13.txt)
[lognode_3.13.txt](https://github.com/SeleniumHQ/selenium/files/2214228/lognode_3.13.txt)

**Comment by barancev** [comment]
I see that confignode.txt has "debug": true, but the screenshots shows it false, that might be an issue.

**Comment by krmahadevan** [comment]
@barancev - True, but like I mentioned above, I don't think that config parameter is even reaching the Hub via the registration request, because its been intentionally left out (At-leasst that is what I could make of it)

**Comment by Kalste** [comment]
@krmahadevan 
I understand, that the debug parameter is only for the process, not for all.
I understand the points 1 and 2, but I don´t understand the point 3.

I tried to set the debug flag, for both, the hub and the node.
The config.json file for the hub and the node has the debug parameter set to true.

When I look at the log file (with_debug_true_lognode.txt) from the node at line 31, there is -> "debug": false,
But my node has debug true.
At line 72 there is -> "debug": true,
My hub has debug true, thats right.
But in line 112, there is again -> "debug": false,

I think debug is true and only the value in the log file is wrong, is this possible?

The other point, is the point with the servlets.
If I use this command -> java -jar selenium-server-standalone-3.13.0.jar -role hub -hubConfig confighub.json -servlets 

org.openqa.grid.web.servlet.LifecycleServlet,org.openqa.grid.web.servlet.Grid1HeartbeatServlet,org.openqa.grid.web.servlet.ResourceServlet,org.openqa.g

rid.web.servlet.DisplayHelpServlet,org.openqa.grid.web.servlet.DriverServlet,org.openqa.grid.web.servlet.ProxyStatusServlet,org.openqa.grid.web.servlet

.beta.ConsoleServlet
the servlets are used correct, see servlets_in_command.jpg, servlets_in_command_loghub.txt and servlets_in_command2.jpg

If I use this command -> java -jar selenium-server-standalone-3.13.0.jar -role hub -hubConfig confighub.json
and the json has the following lines:
"servlets" : ["org.openqa.grid.web.servlet.LifecycleServlet",
				"org.openqa.grid.web.servlet.Grid1HeartbeatServlet",
				"org.openqa.grid.web.servlet.ResourceServlet",
				"org.openqa.grid.web.servlet.DisplayHelpServlet",
				"org.openqa.grid.web.servlet.DriverServlet",
				"org.openqa.grid.web.servlet.ProxyStatusServlet",
				"org.openqa.grid.web.servlet.beta.ConsoleServlet"],

I get this, see servlets_in_json.jpg, servlets_in_json_loghub.txt and servlets_in_json2.jpg
The servlets are listed twice and in the log there are messages -> ...Servlet cannot be instantiated

This is only for the hub, I think the node does it right.

[servlets_in_command_loghub.txt](https://github.com/SeleniumHQ/selenium/files/2249170/servlets_in_command_loghub.txt)
[servlets_in_json_loghub.txt](https://github.com/SeleniumHQ/selenium/files/2249171/servlets_in_json_loghub.txt)
[with_debug_true_lognode.txt](https://github.com/SeleniumHQ/selenium/files/2249172/with_debug_true_lognode.txt)
![servlets_in_command](https://user-images.githubusercontent.com/33020490/43518131-53ccfb88-958b-11e8-8e3a-6fe96808a985.jpg)
![servlets_in_command2](https://user-images.githubusercontent.com/33020490/43518132-53e750b4-958b-11e8-8d90-2000ae13f77e.jpg)
![servlets_in_json](https://user-images.githubusercontent.com/33020490/43518133-540183b2-958b-11e8-9072-976986c4a135.jpg)
![servlets_in_json2](https://user-images.githubusercontent.com/33020490/43518134-541abc92-958b-11e8-9f34-36de7c6bbe04.jpg)

**Comment by barancev** [comment]
I think we should hide config details from the console :)

But the duplicated servlet list is an issue too, I agree.

**Comment by bhecquet** [comment]
I get the same problems with the servlets:
- listed twice
- more important, some of them cannot be loaded because of the "[" character at the beginning of the first servlet name and "] at the end of the last servlet name. It seems that servlet configuration is read as a string instead of a json array

**Comment by krmahadevan** [comment]
Let me see if I can create a PR for this.

**Comment by barancev** [comment]
I've pushed a series of commits that should fix all the abovementioned issues related to hub config ([] chars, "wrong" debug value, servlets duplication).

Node related issues are to be investigated yet.

**Comment by Kalste** [comment]
Hallo,
we changed to version 3.141.59 at the hub and the node and I found out, that 2 parameters from the config file are not used any more, the parameter "log": "C:/.../loghub.txt" and "debug": true.
These two paramters are set, but there is no log file and I see no debug infos.
I testet a little bit and this situation is the same in version 3.141.5 and 3.141.0.
In version 3.14.0 I got a log file and debug infos.
If I use these -> java -jar selenium-server-standalone-3.141.59.jar -role hub -hubConfig confighub.json -log C:\...\loghub.txt -debug, I get a log file and debug infos.
The same situation is for the node.
Do I have to set the log and the debug parameter at the java command and not any more in the config file?
Is this a bug or a feature?

**Comment by diemol** [comment]
Actually the issue comes from a change done a while ago where the parsing of all parameters was refactored. After that, basically the `log` and `debug` parameters in the configuration files for node and hub are ignored. But it works if you pass them through the command line.

About the Grid console, the `debug` value for the node is wrong due to the way the parameters are parsed.

The thing is that we are not planning to do any more code changes in the Grid 3.x and we will focus entirely in the Grid 4.0. Since this is not a critical bug and there is a workaround, I think we could leave this as it is. What do you think @barancev?

**Comment by Kalste** [comment]
@diemol Is there a plan, whenn Grid 4.0 will be released?

**Comment by diemol** [comment]
@Kalste apologies for the late reply, Grid 4 is already available in the alphas https://www.selenium.dev/downloads/

and per the previous comments, I will close this issue since the behaviour won't be changed for Grid 3.x
