### ISSUE TITLE
Javascript console error when Selenium Extension is installed in Chrome:  Uncaught in promise

### ISSUE THREAD

**Issue by td2014** [SeleniumHQ/selenium#6190]
## Meta -
OS:  
OSX
Selenium Version:  
3.1.0 Chrome Extension
Browser:  
Chrome

Browser Version:  
Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
No console errors when loading webpage
## Actual Behavior -
Javascript console error occurs:
Uncaught (in promise) "Could not establish connection. Receiving end does not exist."
## Steps to reproduce -
1. Install Selenium web extension in Chrome.
2. Open cnn.com
3. Examine javascript console to see error mentioned above.
NOTE:  This error does not seem to occur when Selenium web extension dialog is actually open.  Also, I already filed bugs with Chromedriver/chromium teams, and they told me to file bug with Selenium since they don't think it is with them.
I hope this helps.  
Thanks.

**Comment by cgoldberg** [comment]
please post in the Selenium IDE issues tracker:
  * https://github.com/SeleniumHQ/selenium-ide/issues
