### ISSUE TITLE
ERROR: TypeError: Cannot read property 'until' of undefined

### ISSUE THREAD

**Issue by mdasifazhar** [SeleniumHQ/selenium#6195]
Hi,
My test cases are running over headless browser.
I'm automating my scenario using HtmlUnitDriver and getting the below error:-

var webdriver = context.HtmlUnitDriver;
var By = webdriver.Untill;
ERROR: TypeError: Cannot read property 'until' of undefined

Getting same error for By:-
ERROR: TypeError: Cannot read property 'By' of undefined
var By = webdriver.By;

Regards

**Comment by netzulo** [comment]
@mdasifazhar how we can reproduce this ? maybe complete example with small HTML ?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
