### ISSUE TITLE
New windows were blocked in WIN10 1803 IE11

### ISSUE THREAD

**Issue by shijie262** [SeleniumHQ/selenium#6196]
## Meta -
OS:  
OS: Windiws10 1803
Browser: Internet Explorer  11
Browser Version: 11.165.17134.0
Driver : IEDriverServer 3.13

## Expected Behavior -
     I use webdriver to open a page, and click a link like <a target="_blank" href="xxxx">xxxx</a>, before win10 1803, it can open a new window.
## Actual Behavior -
    But now, seems all new windows were blocked, but I can see new internet explorer processes appeared in task manager.

## Steps to reproduce -
   I tried all ways I can searched: disabled IE popup blocker,  add reg item:PopupMgr=no , change previous driver versions. but can not work for all.

**Comment by jimevans** [comment]
@shijie262 If Windows is reporting that `CoCreateInstance` has failed, there’s likely nothing the driver can do to fix that.

**Comment by barancev** [comment]
It must be a security policy setting that prevents IE automation (prevents instantiating IE engine using CoCreateInstance function). You have to tune the environment or use virtual machines.

**Comment by PhilippSelenium** [comment]
@barancev Can you be more specific what exactly to tune in the environment. Since I am getting the same error:
```
2125463506 [Unknown error 0x8150002E]: CoCreateInstance for IWebBrowser2 failed
```

**Comment by barancev** [comment]
No idea, try to searсh https://social.msdn.microsoft.com/ or https://stackoverflow.com/, it can be everything from lack of memory to security settings.

**Comment by shijie262** [comment]
When we uninstall the win10 patch until the IE 11 version down to "11.0.47", everything gona be fine
