### ISSUE TITLE
Safari: Unable to upload File using file chooser window, error: 'This Safari window is remotely controlled by an automated test.'

### ISSUE THREAD

**Issue by poorvikamahesh** [SeleniumHQ/selenium#6198]
OS:
10.13.4 (High Sierra)

Selenium Version:
3.12.0

Browser:
Safari (11.1)

I am trying to automate an application that requires us to choose a file from the Select file window. (Please note, there is no text box /input field where we can give the path of the file)

We are using AutoIt / Robot class for other browsers.

But for Safari we are unable to even open the File chooser window. Safari blocks it.

Is there any workaround for the same?

Attached is the screen shot of the error

<img width="623" alt="screen shot 2018-07-24 at 8 57 03 am" src="https://user-images.githubusercontent.com/10269471/43115653-34abb088-8f22-11e8-9303-44ff46c520bb.png">

**Comment by twalpole** [comment]
There has to be a file input field somewhere in the page, possibly hidden, for the page to trigger the file select window to open.  The workaround is to execute JS to make that file input visible then send keys to that element for the file name you want to upload

**Comment by lmtierney** [comment]
Unfortunately as you have found, you cannot use the safari outside of using the w3c API and safaridrive while in automation. If you think this is in error, you can raise an issue with Apple: https://bugreport.apple.com/

In the future Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
