### ISSUE TITLE
[marionette] Error responses returned from executeScript silently ignored

### ISSUE THREAD

**Issue by lqc** [SeleniumHQ/selenium#620]
Selenium version: 2.45.0-b02d299 (built from master)
Firefox version: 38.0.5

*Steps to reproduce:*

1. Open marionette connect
2. Execute ``driver.executeScript("throw Error('BAD!')")``

*Expected:*

A WebDriver exception raised with error detauls

*Actual:*

The function returns a map::

    {
     message=Error: BAD!,
     status=17,
     stacktrace=execute_script @undefined, line undefined inline javascript, line 0 src: "let __marionetteFunc = function(){throw Error('BAD!')};__marionetteFunc.apply(null, __marionetteParams);"
    }

The error seems to be in ``MarionetteConnection``, which correctly unpacks the error value from the response, but doesn't set ``Response.status``:

      response = new JsonToBeanConverter().convert(Response.class, rawResponse);
      if (map.containsKey("error")) {
        response.setValue(map.get("error")); // status is still 0 (SUCCESS)

I'll try to create a patch this weekend.

**Comment by andreastt** [comment]
You’re running an old version of Firefox.  If you try this with Firefox Nightly (41 or newer) it should work fine since there have been changes to the Marionette protocol recently.

**Comment by lqc** [comment]
I understand that Marionette is still in kind of alpha stage, but the
release notes for 2.46.0 mention "beta marionette driver". They don't
mention any Firefox version requirements, which makes people just assume
it's plain broken.

What do you think about adding a minimum version check after creating the
session so it's clear what is going on ?

On Friday, June 5, 2015, Andreas Tolfsen <notifications@github.com> wrote:

> You’re running an old version of Firefox. If you try this with Firefox
> Nightly (41 or newer) it should work fine since there have been changes to
> the Marionette protocol recently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SeleniumHQ/selenium/issues/620#issuecomment-109358137>
> .
>


-- 
Łukasz Rekucki

**Comment by AutomatedTester** [comment]
Actually we need to remove all that code to be honest and have people use the HTTPd that we are going to release. 



—

**Comment by AutomatedTester** [comment]
We being Mozilla



—

**Comment by lqc** [comment]
On Friday, June 5, 2015, David Burns <notifications@github.com> wrote:

> Actually we need to remove all that code to be honest and have people use
> the HTTPd that we are going to release.
>

Pardon my ignorance, but what do you mean by HTTPd here ? Can it translate
from WebDriver commands to Marionette?



-- 
Łukasz Rekucki

**Comment by AutomatedTester** [comment]
Yes. There is a mandate from W3C Working group to have a httpd, like
InternetExplorerDriver and ChromeDriver.

David Burns
Email: david.burns@theautomatedtester.co.uk
URL: http://www.theautomatedtester.co.uk/

**Comment by andreastt** [comment]
> I understand that Marionette is still in kind of alpha stage, but the release notes for 2.46.0 mention "beta marionette driver". They don't mention any Firefox version requirements, which makes people just assume it's plain broken.

Marionette is changing constantly as part of the ongoing WebDriver specification changes.  There should be no assumptions made about its stability quite yet.
