### ISSUE TITLE
Empty classifier in selenium-java, selenium-remote-driver artifact and others lead to errors with maven-dependency-plugin

### ISSUE THREAD

**Issue by Tkuco** [SeleniumHQ/selenium#6200]
## Meta -
OS:  Windows 10

Selenium Version:  3.13.0

Browser:  -

Browser Version:  -

## Expected Behavior -
In a Tycho Project (Mavenization for Eclipse) when using selenium-java artifact as dependency and trying to copy this and its transitive dependency with the help of the maven-dependency-plugin (version 3.1.1) to disk it all should be copied correctly.
## Actual Behavior -
In a Tycho Project (Mavenization for Eclipse) when using selenium-java artifact as dependency and trying to copy this and its transitive dependency with the help of the maven-dependency-plugin (version 3.1.1) to disk it fails because it can't handle empty classifier defined in pom.xml of selenium-java.

Error is
`[ERROR] Internal error: org.eclipse.core.runtime.AssertionFailedException: The Maven artifact to be added to the target platform is not stored at the required location on disk: required "D:\local_maven_repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3-.jar" but was "D:\local_maven_repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar" -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.core.runtime.AssertionFailedException: The Maven artifact to be added to the target platform is not stored at the required location on disk: required "D:\local_maven_repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3-.jar" but was "D:\local_maven_repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar"`

Solution for fix: Simply remove all occurances of `<classifier/> or <classifier></classifier>` of all dependencies within the pom.xml of selenium-java, selenium-remote-driver. Or is there a reason to have this?

I know this is actually a Tycho problem not handling empty classifier correctly, but I think the removal of all empty classifier is easier to do.. I just wanted to ask.

## Steps to reproduce -
Create a new tycho project with a pom (packaging eclipse-plugin) and add 

`<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-dependency-plugin</artifactId>
			<version>3.1.1</version>
			<executions>
				<execution>
					<id>copy-libs</id>
					<phase>process-resources</phase>
					<goals>
						<goal>copy-dependencies</goal>
					</goals>
					<configuration>
						<excludeTransitive>false</excludeTransitive>			
						<includeScope>runtime</includeScope>
						<excludeTypes>pom</excludeTypes>
						<outputDirectory>lib</outputDirectory>
						<overWriteReleases>false</overWriteReleases>
						<overWriteSnapshots>false</overWriteSnapshots>
					</configuration>
				</execution>
			</executions>
		</plugin>
	</plugins>
</build>
<dependencies>
	<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-java</artifactId>
		<version>3.13.0</version>
	</dependency>
</dependencies>`

**Comment by barancev** [comment]
No. please, fix the Tycho issue :)

Removing empty classifiers in all artifacts (including ones already deployed to maven central) is not easier to do.
