### ISSUE TITLE
Issue 'Modal Dialog Present' happening after latest update with Internet Explorer 11 (KB4021558)

### ISSUE THREAD

**Issue by sanoopkarakkat** [SeleniumHQ/selenium#6201]
I am getting 'Modal dialog present' exception while running my test cases which was working fine till 23rd July. On 24th July, Microsoft rolled out an update KB4021558 regarding some vulnerability fix for IE 11. After this update, I am getting an exception while executing an AutoIT exe for handling a Windows-based pop-up. 

Please see the configurations below.

OS : Windows 10
IE Driver : 3.13.0 (32 Bit)
IE Version : IE 11.0.10240.17443 (KB4021558)

Is anyone having same issues with the latest IE update?

Any help would be highly appreciated.

**Comment by jimevans** [comment]
There is nothing to act on in this issue report without code (including a sample page) that demonstrates the problem.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
