### ISSUE TITLE
[Documentation] Update link to Guiceberry in Wiki

### ISSUE THREAD

**Issue by JoaoGFarias** [SeleniumHQ/selenium#6205]
The link to the Guiceberry project, in the [LoadableComponent wiki page](https://github.com/SeleniumHQ/selenium/wiki/LoadableComponent) is outdated.

The project has moved to Github, on the following link: https://github.com/zorzella/guiceberry

**Comment by lmtierney** [comment]
This has been updated, thanks for bringing this to our attention!
