### ISSUE TITLE
[Documentation] Update link to [GridPlatforms] in Wiki for DesiredCapabilities

### ISSUE THREAD

**Issue by vefimofff** [SeleniumHQ/selenium#6206]
Page: https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities
Text: For more information see **[GridPlatforms]**
Link: GridPlatforms
Actual value: https://github.com/SeleniumHQ/selenium/wiki/GridPlatforms.md
Expected value: https://github.com/SeleniumHQ/selenium/wiki/Grid-Platforms

**Comment by vefimofff** [comment]
Also noticed that on https://github.com/SeleniumHQ/selenium/wiki/Grid-Platforms 3 links to **[DesiredCapabilities]** lead to _https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities.md_
which opens a page with raw content. I suggest to replace them with _https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities_ which will open a well-formatted page.

**Comment by vefimofff** [comment]
I would easily fix it myself but unfortunately didn't find the clear way to submit pull with wiki fixes. Any recommendations are welcome.

**Comment by lmtierney** [comment]
This has been updated, thanks for bringing this to our attention!
