### ISSUE TITLE
Selenium-webdriver 2.46.1 for Ruby send_keys(:return) fails with from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by Jumper303** [SeleniumHQ/selenium#621]
Detected with: Selenium-webdriver 2.46.1 for Ruby
Ruby version: 1.9.3
Firefox: 38.0.1

Action:   test_element.send_keys(:return)
Exception: "\xEE" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

Can't reproduce this with Selenium-webdriver 2.45.0 for Ruby.

**Comment by p0deje** [comment]
Yeah, this is addressed with SeleniumHQ/selenium#617. I hope we'll merge it today and make another release.

**Comment by p0deje** [comment]
Fixed in https://github.com/SeleniumHQ/selenium/commit/cdfd19cf4fffec13cdc6d6da051af74ad5682051
