### ISSUE TITLE
Selenium failing to locate Modal Dialog box 

### ISSUE THREAD

**Issue by Ashish20689** [SeleniumHQ/selenium#6210]
## Meta -
OS:   Windows 7 
Selenium Version:  3.13.0 Web Driver 
Browser:  Firefox

I was automating Timesheet Entry in office, earlier after logging into the timesheet website the timesheet entry page used to load and automating was not a challenge, But now since goal setting has opened as part of appraisals, they have introcuded a modal dialog box, so as soon as I login into the timesheet website the modal dialog box opens. Though I tried clicking close button using its xpath and even by cssselector, selenium just fails to locate the element.

Next when I tried clicking button on the timsheet page which is beinf overridden by the modal dialog boz I got the below error

Code:

		WebDriverWait wait1 = new WebDriverWait(driver, 60);
		wait1.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/form/div[3]/nav[2]/div[2]/ul[1]/li[1]/a/b")));	(Locating timehseet daily button)	
		driver.findElement(By.xpath("/html/body/form/div[3]/nav[2]/div[2]/ul[1]/li[1]/a/b")).click();
		driver.findElement(By.linkText("Timesheet Weekly")).click();

Error:

Element <b class="caret"> is not clickable at point (115,57.5) because another element <div id="divMissTSCutOffAdvance" class="modal fade bs-example-modal-lg in"> obscures it

This means selenium can detect that modal dialog box is an element appearing on the main page

So i modified the code as below 

		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		Thread.sleep(10000);
        WebDriverWait waitX = new WebDriverWait(driver, 30);
        waitX.until(ExpectedConditions.visibilityOfElementLocated(By.id("divMissTSCutOffAdvance"))).click();
		WebDriverWait wait1 = new WebDriverWait(driver, 60);
		wait1.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/form/div[3]/nav[2]/div[2]/ul[1]/li[1]/a/b")));	(Locating timehseet daily button)	

Error:
Selenium fails to locate element with id divMissTSCutOffAdvance

I have tried various methods to resolve it or find a work around but nothing worked. I even tried switching to new window using getWindowHandles method but failed,
tried to use switch to alert as well thinking if it was being treated as a alert but nothing worked.

When I give some waiting time and try driver.switchTo().alert();
It throws error saying : No modal dialog is currently open

-->

Driver Version:  0.21.0 Gecko Driver (64-bit) 
Browser Version:  Firefox 61.0.1 (64-bit) 

## Steps to reproduce -
I wanted to paste the entire script but since it contains my official company login credentials its not easy to do it

![image](https://user-images.githubusercontent.com/41769090/43301818-040aebc8-9185-11e8-96e3-fac55efe9181.png)

**Comment by Ashish20689** [comment]
## Meta -
OS:  

Selenium Version:  

Browser:  


Driver Version:  

Browser Version:  


## Expected Behavior -

## Actual Behavior -

## Steps to reproduce -

**Comment by GitSage** [comment]
If you're able, I suggest making an [SSCCE](http://sscce.org/). Create a small html file with the modal on it and the bare minimum needed to reproduce the issue. [Here](https://github.com/GitSage/selenium-is-displayed-ie-bug) is an example of an SSCCE I've done in the past.

It's possible that someone will be able to figure out your problem with just the snippets and screenshot that you've provided, but I wouldn't count on it happening any time soon. Without reproduction it will be hard for people to help you.

I'm no expert at the Java version of WebDriver but I don't see any overt issues these snippets.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
