### ISSUE TITLE
Selenium Scripts are not stable with Firefox browser

### ISSUE THREAD

**Issue by Anbuchozhan** [SeleniumHQ/selenium#6212]
## Meta -
OS:  Windows 7
Selenium Version:  
3.3.1
Browser:  
Firefox & IE

Browser Version:  
Firefox 52.2.1(32 bit) ( geckodriver0.15) & IE11

##Issue:
Designed scripts are working fine in IE browser but when we run the same in firefox then scripts are not working in stable. Firefox browser is launched, url passed & logged in then its not wait for page to load. I have used explicit wait in most of places & also i used waitforpageto load explicit wait. 

Used **return document.readystate** to wait until page get loads but it return **'complete'** while loading the page itself. But everything working fine & stable in IE. 

Only these stability issue is occurred in firefox. Do i need to add any desiredcapabilities for this issue? 

**Mousehover & double click are not working in firefox with geckodriver0.15 & selenium 3.3.1.** 

## Expected Behavior -
Script should run in stable & browser should wait for explicit wait

## Actual Behavior -
Browser is not waiting for explicit wait. Mousehover is not working in firefox 52.2.1 with geckodriver0.15 & selenium 3.3.1

**Comment by GitSage** [comment]
Do you have an [SSCCE](http://sscce.org)?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

(Also, don't use outdated versions and don't report issues related to outdated versions)
