### ISSUE TITLE
Errno::EALREADY: Operation already in progress - connect(2) for 127.0.0.1:9515

### ISSUE THREAD

**Issue by Ephs05msm** [SeleniumHQ/selenium#6213]
## Meta -
OS:  
Windows 10 Build 17723.rs5_release.180720-1452
Ubuntu running inside Windows Subsystem for Linux

Selenium Version:  
Selenium Webdriver 3.13.1
ChromeDriver 2.40

Browser:  
Chrome

Browser Version:  
68.0.3440.75 (Official Build) (64-bit)

## Expected Behavior -
Ruby spec test suite runs each test and passes or fails for reasons governed by the test itself

## Actual Behavior -
New Insider build of Windows installed overnight. As of today, the test suite fails with the message below. When `rspec` is run repeatedly, the failures occur on arbitrary tests (all of which pass when they actually run), and the number of failures has ranged from one to three in a given execution of `rspec`. When there are multiple failures, the port increments up by one in each instance (e.g., 9515, 9516, 9517). Here is the message:
```
Errno::EALREADY:
       Operation already in progress - connect(2) for 127.0.0.1:9515
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/socket_poller.rb:79:in `listening?'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/socket_poller.rb:39:in `block in connected?'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/socket_poller.rb:100:in `with_timeout'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/socket_poller.rb:39:in `connected?'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/service.rb:141:in `connect_until_stable'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/service.rb:72:in `block in start'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/service.rb:69:in `start'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/chrome/driver.rb:43:in `initialize'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/driver.rb:44:in `new'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver/common/driver.rb:44:in `for'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.13.1/lib/selenium/webdriver.rb:86:in `for'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/capybara-3.4.2/lib/capybara/selenium/driver.rb:31:in `browser'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/capybara-3.4.2/lib/capybara/selenium/driver.rb:59:in `visit'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/capybara-3.4.2/lib/capybara/session.rb:269:in `visit'
     # /home/MattMarino/.rvm/gems/ruby-2.5.0/gems/capybara-3.4.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
```

Gemfile.lock:
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.0)
      actionpack (= 5.2.0)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.0)
      actionpack (= 5.2.0)
      actionview (= 5.2.0)
      activejob (= 5.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.0)
      actionview (= 5.2.0)
      activesupport (= 5.2.0)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.0)
      activesupport (= 5.2.0)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.0)
      activesupport (= 5.2.0)
      globalid (>= 0.3.6)
    activemodel (5.2.0)
      activesupport (= 5.2.0)
    activerecord (5.2.0)
      activemodel (= 5.2.0)
      activesupport (= 5.2.0)
      arel (>= 9.0)
    activestorage (5.2.0)
      actionpack (= 5.2.0)
      activerecord (= 5.2.0)
      marcel (~> 0.3.1)
    activesupport (5.2.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    arel (9.0.0)
    bcrypt (3.1.12)
    bindex (0.5.0)
    bootsnap (1.3.1)
      msgpack (~> 1.0)
    bourbon (5.1.0)
      sass (~> 3.4)
      thor (~> 0.19)
    builder (3.2.3)
    byebug (10.0.2)
    capybara (3.4.2)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      xpath (~> 3.1)
    childprocess (0.9.0)
      ffi (~> 1.0, >= 1.0.11)
    coderay (1.1.2)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    crass (1.0.4)
    diff-lcs (1.3)
    email_spec (2.2.0)
      htmlentities (~> 4.3.3)
      launchy (~> 2.1)
      mail (~> 2.7)
    erubi (1.7.1)
    execjs (2.7.0)
    factory_bot (4.10.0)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.10.0)
      factory_bot (~> 4.10.0)
      railties (>= 3.0.0)
    ffi (1.9.25)
    font-awesome-rails (4.7.0.4)
      railties (>= 3.2, < 6.0)
    foreman (0.85.0)
      thor (~> 0.19.1)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    htmlentities (4.3.4)
    i18n (1.0.1)
      concurrent-ruby (~> 1.0)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    marcel (0.3.2)
      mimemagic (~> 0.3.2)
    method_source (0.9.0)
    mimemagic (0.3.2)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    msgpack (1.2.4)
    multi_json (1.13.1)
    nio4r (2.3.1)
    nokogiri (1.8.4)
      mini_portile2 (~> 2.3.0)
    oath (1.1.0)
      bcrypt
      rails
      warden
    oath-generators (1.0.1)
      oath (>= 0.0.12)
    pg (1.0.0)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.6.0)
      byebug (~> 10.0)
      pry (~> 0.10)
    public_suffix (3.0.2)
    puma (3.12.0)
    rack (2.0.5)
    rack-proxy (0.6.4)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.0)
      actioncable (= 5.2.0)
      actionmailer (= 5.2.0)
      actionpack (= 5.2.0)
      actionview (= 5.2.0)
      activejob (= 5.2.0)
      activemodel (= 5.2.0)
      activerecord (= 5.2.0)
      activestorage (= 5.2.0)
      activesupport (= 5.2.0)
      bundler (>= 1.3.0)
      railties (= 5.2.0)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.2.0)
      actionpack (= 5.2.0)
      activesupport (= 5.2.0)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.1)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    sass (3.5.7)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.13.1)
      childprocess (~> 0.5)
      rubyzip (~> 1.2)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.8)
    time_for_a_boolean (0.2.0)
      activerecord
      railties
    turbolinks (5.1.1)
      turbolinks-source (~> 5.1)
    turbolinks-source (5.1.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.16)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.6.2)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webpacker (3.5.5)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    xpath (3.1.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  bootsnap (>= 1.1.0)
  bourbon
  byebug
  capybara
  coffee-rails (~> 4.2)
  email_spec
  factory_bot_rails
  font-awesome-rails
  foreman
  jbuilder (~> 2.5)
  jquery-rails
  listen (>= 3.0.5, < 3.2)
  oath
  oath-generators
  pg (>= 0.18, < 2.0)
  pry-byebug
  puma (~> 3.11)
  rails (~> 5.2.0)
  rspec-rails
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  time_for_a_boolean
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  webpacker

RUBY VERSION
   ruby 2.5.0p0

BUNDLED WITH
   1.16.1
```

## Steps to reproduce -
- Install latest version of ChromeDriver in Windows.
- Include ChromeDriver in PATH.
- In the same folder where ChromeDriver.exe resides, create a file called "chromedriver" that contains:
```
#!/bin/sh
chromedriver.exe "$@"
```
- Open Ubuntu terminal
- cd to project path
- run `rspec`

**Comment by p0deje** [comment]
I cannot reproduce the issue using the information you provided - there is no code which starts/stops driver. Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. If you use RSpec, please upload all the relevant spec helper code as well as the tests. Ideally though, you'd reduce it to a single Ruby file that can be run to reproduce the failure.

**Comment by remidoolaeghe** [comment]
I've had the same issue as @Ephs05msm. In few words, it seems this happens when running the tests on WSL, with at least two classes of system tests. My WSL runs an Ubuntu 16.

I've created a project with almost only what's useful to reproduce the case. Just clone [this repository](https://github.com/remidoolaeghe/Ruby-on-Rails_System-Tests_On_WSL_Fails). 

I may be wrong, but it seems there is a concurrent access somewhere that makes the first test class provoke an error.

## You may have to install additionnal dependencies in WSL

`sudo apt-get install libnss3`

`sudo apt install chromium-browser`

## How to reproduce

Just run system tests

`rails test:system`

## What you should get:

> Puma starting in single mode...
> * Version 3.10.0 (ruby 2.4.4-p296), codename: Russell's Teapot
> * Min threads: 0, max threads: 1
> * Environment: test
> * Listening on tcp://0.0.0.0:64406
> Use Ctrl-C to stop
> [Screenshot]: tmp/screenshots/failures_test_my_test_0.png
> 
> E
> 
> Error:
> MyTest#test_my_test_0:
> Errno::EALREADY: Operation already in progress - connect(2) for 127.0.0.1:9515
>     test/system/my_test.rb:7:in `block (2 levels) in <class:MyTest>'
> 
> 
> bin/rails test test/system/my_test.rb:6
> 
> ...................
> 
> Finished in 10.215314s, 1.9578 runs/s, 0.0000 assertions/s.
> 20 runs, 0 assertions, 0 failures, 1 errors, 0 skips

**Comment by p0deje** [comment]
Thank you for providing a test case. I have installed WSL on my Windows 10 machine, cloned your repository and installed all the necessary dependencies. Still, the system tests pass just fine (skipping the fact that it doesn't exit chromedriver properly):

![screen shot 2018-09-15 at 09 23 46](https://user-images.githubusercontent.com/665846/45581930-15e3fb80-b8c9-11e8-8b84-d65b371c2825.png)

If it happens all the time, it might be related to some abnormal chrome/chromium behavior, so can you please verify that chromium can be started manually?

**Comment by megaspaz** [comment]
Not sure what version of chromedriver.exe is being talked about here, but my short experience using 2.41 and 2.42 with selenium webdriver 3.13.X and 3.14.0 is as follows under WSL:

2.41 with webdriver 3.13.X and 3.14.0 - working. The tests run with chrome.
2.42 with webdriver 3.14.0 - Errno::EALREADY: Operation already in progress - connect(2) for 127.0.0.1:9515

My set up for my teaching project is run serially right now - no concurrent test cases...
Since I have no experience with windows/wsl, my setup done as below, using the top 2 or 3 search results.

1.  Install Ubuntu from the store, rvm and ruby. https://www.digitalocean.com/community/tutorials/how-to-install-ruby-and-set-up-a-local-programming-environment-on-windows-10

2. Cloned repo using git bash native windows version. https://github.com/megaspaz/testing

3. Get IDE up. https://confluence.jetbrains.com/display/RUBYDEV/How+to+add+WSL+SDK+on+Windows+to+RubyMine

4. Install chromedriver.exe. I just copied it to System32 and in bash.exe made a link with ln to it in /usr/bin/ called chromedriver.

**Comment by remidoolaeghe** [comment]
@p0deje I've added more tests to my repository (now 800 tests), because my previous version only ran one test class (as missing rails conventions, my test class didn't end with "test"). I've noticed that only one test was failing each time I run the system tests, but never the same test (may be any test from any test class). The error remains always the same though.

I've tried executing chromium manually. In my terminal, nothing shows up. No error, no effect. I don't know what I can conclude.

@megaspaz I've tried executing the tests using following combination:

- chromedriver 2.41 with Selenium webdriver 3.13.0
- chromedriver 2.42 with Selenium webdriver 3.13.0
- chromedriver 2.42 with Selenium webdriver 3.14.0

The result remains the same, one randomly failing test most of the time.

**Comment by p0deje** [comment]
I've started see this error after @remidoolaeghe increased an amount of tests, but still it happens from time to time. Thank you everyone for the help with debugging! 

It seems that on WSL we get different error when checking if we're connected to ChromeDriver or any other service/socket. I've pushed a workaround in b7af8ed1c14acf58e9cde88b3b34caa71733980a. I'd appreciate if you guys could test it before I make an official release.

**Comment by remidoolaeghe** [comment]
@p0deje I've taken the following commit, i.e. *36e4f3e25e1a1a00335a24e3c918d74bb370a1e7* because I had problems with dependencies. I'm not quite sure about it. I mention it for you to know.

Using this commit, all my tests were running green on my test project (the one you cloned) and on my real project. Everything seems to be fine with the fix you provided.

Just putting this line in my Gemfile did the job:

`  gem 'selenium-webdriver', git: 'https://github.com/SeleniumHQ/selenium.git', ref: '36e4f3e25e1a1a00335a24e3c918d74bb370a1e7'`

I think you can embed this fix in your next official release. Thanks for your time and for fixing
the problem.

**Comment by p0deje** [comment]
@remidoolaeghe Oh, I didn't know you can install selenium-webdriver from Git like that. I thought there was some problem because it lives in `rb/` directory. Good to know now.

In any event, thank you for the help on triaging the bug. I'll probably postpone on release until few more code changes.

**Comment by titusfortner** [comment]
@remidoolaeghe just be careful, you don't get compiled binaries when you pull from github like that (getAttribute atom being the major one, and soon that will likely include isShown atom).

**Comment by remidoolaeghe** [comment]
@titusfortner Thanks for the tip. I'll migrate to official release as soon as it is available.

**Comment by daveomcd** [comment]
I've been having similar issues.  I've installed the gem version that @remidoolaeghe mentioned and it seemed to correct things after downgrading to chromedriver 2.40.  However, I'm seeing issues periodically.  Seemingly always on the first test with the following 3 always passing.

`daveomcd@LAPTOP-GDA9LTDQ:~/rails_projects/sample$ rails test test/system/users_test.rb
Running via Spring preloader in process 672
/home/daveomcd/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:185: warning: Insecure world writable dir /home/daveomcd/.rvm/gems/ruby-2.4.2/bin in PATH, mode 040777
Run options: --seed 51949

# Running:

Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:50660
[Screenshot]: tmp/screenshots/failures_test_destroying_a_User.png
E

Error:
UsersTest#test_destroying_a_User:
Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9515 (Connection refused - connect(2) for "127.0.0.1" port 9515)
    test/system/users_test.rb:38:in `block in <class:UsersTest>'


bin/rails test test/system/users_test.rb:37

...

Finished in 15.686655s, 0.2550 runs/s, 0.1912 assertions/s.
4 runs, 3 assertions, 0 failures, 1 errors, 0 skips`

**Comment by p0deje** [comment]
@daveomcd This is a different error. Please, raise a new issue with all the details (OS, environment) and script to reproduce the problem.
