### ISSUE TITLE
npm selenium-webdriver directs to SeleniumHQ/selenium

### ISSUE THREAD

**Issue by 412andrewmortimer** [SeleniumHQ/selenium#6215]
## Meta -
OS:  META (this is a documentation issue)

Selenium Version:  ALL

Browser:  ANY

Browser Version:  

## Expected Behavior -
[selenium-webdriver](https://www.npmjs.com/package/selenium-webdriver) should direct the user to source code which is a JavaScript project when they click to view the repository.
## Actual Behavior -
Being on npmjs.com the user is directed to a non-JavaScript project, that is related to, but not the actual module the user is trying to get information about. The user arrives at his page instead: [Selenium](https://github.com/SeleniumHQ/selenium) 
## Steps to reproduce -
1. The user should be in a position that they need information about the selenium-webdriver npm package.
2. The should go to https://www.npmjs.com/package/selenium-webdriver to get that infomation.
3. The user should click the **repository link** on npmjs.com to view the source code of `selenium-webdriver`
3. The user is directed to the umbrella page of the project instead of the actual source code. 

It's a bad experience to be looking for something as simple as the `engine` in the pakckage.json. Only to be dumped into the main project page to try to decipher how any of this giant ecosystem even organizes itself.

**Comment by jleyba** [comment]
SeleniumHQ/selenium is the correct project for selenium-webdriver. The node client code is in https://github.com/SeleniumHQ/selenium/tree/master/javascript/node

**Comment by 412andrewmortimer** [comment]
I disagree but, who am I? What you are saying is: technically a project inside of a project. Which is just confusing. I personally don't keep my silverware in my oven, just because it's the same room of the house.
