### ISSUE TITLE
Firefox doesn't work with selenium hub

### ISSUE THREAD

**Issue by lieyike** [SeleniumHQ/selenium#6216]
## Meta -
OS:  Fedora
Selenium Version:  3.12.0
Browser:  Firefox
Geckodriver Version: 0.21.0

Browser Version:   61.0.1

## Expected Behavior -
Firefox should start and run test

## Actual Behavior -
A firefox browser will start but it didn't open the url and do nothing.

Log in selenium hub will show receive a request and trying to create a new session on test slot
Log in selenium node will show started new session.
Can't see any execption in the hub or node
For my test, I am using nightwatch, and the log show "Error retrieving a new session from the selenium server  "
and "Connection refused! Is selenium server started?"

But the test work well if I just start a standalone server without using hub.
I want to know if I can run firefox on selenium hub ?
## Steps to reproduce -
Here is my example : https://github.com/lieyike/Run-with-Selenium-hub
Run on selenium hub (Test fail)
1.npm install 
2.bash start-hub.sh
3.bash start-node.sh
4.npm run test

Only start standalone server (Test pass)
if run will standalone or using nightwatch to start selenium, test will work
1.npm install 
2.bash start-standalone.sh
3.npm run test

Nightwatch  standalone server (Test Pass)
1.edit  https://github.com/lieyike/Run-with-Selenium-hub/blob/master/nightwatch.conf.js#L9
start_process to true
2.npm run test

**Comment by lieyike** [comment]
Log from nightwatch
`INFO Request: POST /wd/hub/session 
 - data:  {"desiredCapabilities":{"browserName":"firefox","javascriptEnabled":true,"acceptSslCerts":true,"platform":"ANY","marionette":true,"moz:firefoxOptions":{"args":[]},"name":"Bing"}} 
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":178}
INFO Response 200 POST /wd/hub/session (1066ms) { value: 
   { sessionId: 'dc891244-5948-4805-a4b1-1c8a7fbd8193',
     capabilities: 
      { acceptInsecureCerts: false,
        browserName: 'firefox',
        browserVersion: '61.0.1',
        'moz:accessibilityChecks': false,
        'moz:headless': false,
        'moz:processID': 24953,
        'moz:profile': '/tmp/rust_mozprofile.rIPwE63TCFth',
        'moz:useNonSpecCompliantPointerOrigin': false,
        'moz:webdriverClick': true,
        pageLoadStrategy: 'normal',
        platformName: 'linux',
        platformVersion: '4.13.16-100.fc25.x86_64',
        rotatable: false,
        timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
        'webdriver.remote.sessionid': 'dc891244-5948-4805-a4b1-1c8a7fbd8193' } } }

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ value: 
   { sessionId: 'dc891244-5948-4805-a4b1-1c8a7fbd8193',
     capabilities: 
      { acceptInsecureCerts: false,
        browserName: 'firefox',
        browserVersion: '61.0.1',
        'moz:accessibilityChecks': false,
        'moz:headless': false,
        'moz:processID': 24953,
        'moz:profile': '/tmp/rust_mozprofile.rIPwE63TCFth',
        'moz:useNonSpecCompliantPointerOrigin': false,
        'moz:webdriverClick': true,
        pageLoadStrategy: 'normal',
        platformName: 'linux',
        platformVersion: '4.13.16-100.fc25.x86_64',
        rotatable: false,
        timeouts: [Object],
        'webdriver.remote.sessionid': 'dc891244-5948-4805-a4b1-1c8a7fbd8193' } } }
`

**Comment by barancev** [comment]
Please report this issue to nightwatch project.

**Comment by lieyike** [comment]
I think the error cause by the selenium hub send an old firefox reponse 
And for the nightwatch, it should sessionId from response.sessionId
it can't get the sessionId from response.sessionId
Response data from failed one, the sessionId is inside the value
{
  value: {
    sessionId: '19e38a06-a16e-45e5-83e1-97128fa725a1',
    capabilities: {
      acceptInsecureCerts: false,
      browserName: 'firefox',
      browserVersion: '61.0.1',
      'moz:accessibilityChecks': false,
      'moz:headless': false,
      'moz:processID': 18478,
      'moz:profile': '/tmp/rust_mozprofile.OW981COzRdk2',
      'moz:useNonSpecCompliantPointerOrigin': false,
      'moz:webdriverClick': true,
      pageLoadStrategy: 'normal',
      platformName: 'linux',
      platformVersion: '4.13.16-100.fc25.x86_64',
      rotatable: false,
      timeouts: {
        implicit: 0,
        pageLoad: 300000,
        script: 30000
      },
      'webdriver.remote.sessionid': '19e38a06-a16e-45e5-83e1-97128fa725a1'
    }
  }
}

Response data from the sucess one
{
  status: 0,
  sessionId: 'b729f9f4-d29b-4c1b-b2a2-ee462fad04e3',
  value: {
    acceptInsecureCerts: false,
    browserName: 'firefox',
    browserVersion: '61.0.1',
    'moz:accessibilityChecks': false,
    'moz:headless': false,
    'moz:processID': 16705,
    'moz:profile': '/tmp/rust_mozprofile.krHrKHWGxGKg',
    'moz:useNonSpecCompliantPointerOrigin': false,
    'moz:webdriverClick': true,
    pageLoadStrategy: 'normal',
    platformName: 'linux',
    platformVersion: '4.13.16-100.fc25.x86_64',
    rotatable: false,
    timeouts: {
      implicit: 0,
      pageLoad: 300000,
      script: 30000
    },
    'webdriver.remote.sessionid': 'b729f9f4-d29b-4c1b-b2a2-ee462fad04e3'
  }
}

**Comment by ryanwischkaemper** [comment]
@lieyike did you ever find a resolution for this? I'm having the exact same problem

**Comment by lieyike** [comment]
@ryanwischkaemper not yet, I will raise a issue in nigtwatch project, but I think this issue may cause by selenium hub which response different json. The best way to do is that let nightwatch to control selenium.

**Comment by lieyike** [comment]
@ryanwischkaemper  check here
https://github.com/nightwatchjs/nightwatch/issues/1874
