### ISSUE TITLE
Documentation on how to produce Geckodriver trace level logs using the Node bindings missing

### ISSUE THREAD

**Issue by motin** [SeleniumHQ/selenium#6219]
## Meta -
OS: All 
Selenium Version:  
3.6.0 selenium-webdriver from npm + Geckodriver
Browser:  
Firefox

Browser Version:  
Recent versions (61+ for instance)

## Expected Behavior -

It's allegedly possible to [set log levels for the Geckodriver via `{"moz:firefoxOptions": {"log": {"level": "..."}}}`](https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md) and I expect to be able to set this Firefox option in some intuitive manner, or else in a manner explained by documentation. 

For instance:
```
    const firefox = require("selenium-webdriver/firefox");
    const webdriver = require("selenium-webdriver");
    const profile = new firefox.Profile();
    profile.setPreference('marionette', true);
    profile.setPreference('marionette.logging', 'TRACE');
    const options = new firefox.Options();
    options.setProfile(profile);
    const builder = new webdriver.Builder()
      .forBrowser("firefox")
      .setFirefoxOptions(options);
```

Or:
```
    const firefox = require("selenium-webdriver/firefox");
    const webdriver = require("selenium-webdriver");
    const profile = new firefox.Profile();
    const options = new firefox.Options();
    options.setProfile(profile);
    const builder = new webdriver.Builder()
      .forBrowser("firefox")
      .withCapabilities({"moz:firefoxOptions": {"log": {"level": "trace"}}})
      .setFirefoxOptions(options);
```

Or:
```
    const firefox = require("selenium-webdriver/firefox");
    const webdriver = require("selenium-webdriver");
    const logging = require("selenium-webdriver/lib/logging");
    const options = new firefox.Options();
    options.setProfile(profile);
    const loggingPreferences = new logging.Preferences();
    loggingPreferences.setLevel(logging.Type.DRIVER, "trace");
    options.setLoggingPreferences(loggingPreferences);
    const builder = new webdriver.Builder()
      .forBrowser("firefox")
      .setFirefoxOptions(options);
```

## Actual Behavior -

The above examples does not work and documentation on how to do this via the JavaScript API are missing from these sources:
https://www.npmjs.com/package/geckodriver#use-it-by-setting-webdriver-capabilities
https://seleniumhq.github.io/docs/drivers.html#driver_specific_capabilities
https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox.html
https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Options.html
https://github.com/SeleniumHQ/selenium/issues
https://github.com/mozilla/geckodriver/issues

For all other bindings, there are issues containing solutions on how to produce Geckodriver trace level logs: 
 * .NET: https://github.com/SeleniumHQ/selenium/issues/4855
 * Java: https://github.com/SeleniumHQ/selenium/issues/3943, https://github.com/SeleniumHQ/selenium/issues/3002
 * Ruby: https://github.com/SeleniumHQ/selenium/issues/3433
 * Python: https://github.com/mozilla/geckodriver/issues/1015
 
The closest thing to documentation is [this example for Chrome](https://github.com/SeleniumHQ/selenium/blob/3e99112a0d59878c6f31cc50fe8b0593c49e497f/javascript/node/selenium-webdriver/chrome.js#L63-L76), but attempting the same for Firefox using geckodriver has proved fruitless. 

There is also this SO question, but it is not yet been answered: https://stackoverflow.com/questions/48782242/turn-on-logging-for-gecko-driver-in-selenium-node-js

## Steps to reproduce -

1. Be asked to produce trace level logs for the Geckodriver in order to report a new issue against https://github.com/mozilla/geckodriver
2. Fail in this endeavour

## Other

Note: From https://github.com/mozilla/geckodriver/issues/362#issuecomment-274888779 we know that this documentation is out of scope for the Geckodriver project itself.

A related issue is https://github.com/SeleniumHQ/selenium/issues/2632, where the following is mentioned:
> Some bindings, i.e. for Node.js, supports exposing stdout/stderr but only by modifying a class constructor’s argument. When we tell users “to run geckodriver with the -vv flag” they often have no idea where to start.

**Comment by motin** [comment]
Found a workaround. 

Start geckodriver locally with verbose logging:

```
npx geckodriver -vv
```

Then add to the builder instruction when setting of the driver:
```
builder.usingServer("http://127.0.0.1:4444");
```

**Comment by lmtierney** [comment]
I'm not a JS guy and this is untested, but it should look something like this:

```
 let chrome = require('selenium-webdriver/firefox');

 let service = new firefox.ServiceBuilder()
     .enableVerboseLogging()
     .build();

 let options = new firefox.Options();

 let driver = firefox.Driver.createSession(options, service);
```

**Comment by tdaniely** [comment]
It seems to me very odd that as a grid admin I can enable logs for all browsers on the node command line except for firefox.
Not clear why it doesn't take global `webdriver.*.logfile` and `webdriver.*.verboseLogging` like all the other drivers.

**Comment by jleyba** [comment]
@tdaniely this bug is about the nodejs bindings, not Selenium Grid.

**Comment by dmlemeshko** [comment]
The workaround above is working, but maybe somebody knows how to make it work via code?
`ServiceBuilder().enableVerboseLogging(true)` doesn't seem to work or I miss smth...
