### ISSUE TITLE
log level to print url

### ISSUE THREAD

**Issue by dhirajforyou** [SeleniumHQ/selenium#6222]
## Meta -
OS:  ubuntu

Selenium Version:  3.12.0

Browser:  Firefox

Browser Version:  latest

## Steps to reproduce -
Previously, I used firefox-standalone 2.48.2 selenium docker and It used to print url while accessing it.
ex. INFO - Executing: [get http://www.bbc.com/]

I am using latest selenium 3.12.0 version, its not printing these type of log.

Have tried below two propreties while running , which are not helping:

JAVA_OPTS="-Dselenium.LOGGER.level=ALL

JAVA_OPTS="-Djetty-logging.properties.LEVEL=DEBUG"

What log level should be used to get the similar line to be printed ?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by dhirajforyou** [comment]
Thanks @barancev .
