### ISSUE TITLE
Changing window with IE

### ISSUE THREAD

**Issue by houesmalek** [SeleniumHQ/selenium#6223]
Hello everyone,

I'm making a test that clicks on a button and launches a window to do some other tasks.
 My test works perfectly with Firefox and Chrome. However, when it comes to IE (_version 11.0.9600_), the robot doesn't see the new window launched.
 So when I call these 2 lines in order to change to window,
```
@{Windows}=    Get Window Names
Select Window    @{Windows}[1]	
```

It fails with this error: **List variable '@{Windows}' has no item in index 1**. 
I've even put a` sleep 10 `after clicking a the boutton that launches the window but nothing seems to work. 

Any recommandations please?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
