### ISSUE TITLE
Server returned HTTP response code: 405 in IE11 Driver when using getTabIds/switchTab

### ISSUE THREAD

**Issue by lttrung112** [SeleniumHQ/selenium#6229]
## Meta -
OS:  Windows 10
Selenium Version:  3.11.0
Browser:   Internet Explorer
IEDriver server version:  3.13.0.5
Browser Version:  11.0.9600.19078 (64-bit) 

## Expected Behavior -
This API work well in IE11
## Actual Behavior -
Error:
java.io.IOException: Server returned HTTP response code: 405 for URL: http://localhost:46906/session/97c7f754-8172-4aef-baf9-0a6ec6e08eee/window_handles
running internet explorer (v11)
Error: An unknown server-side error occurred while processing the command.
    at Object.getTabIds (E:\Octans\Configuration-test\F18.8\garoon\tests\tcb-selenium\node_modules\wdio-sync\build\index.js:349:27)

## Steps to reproduce -
I have got a failure when running browser.getTabIds(); API in IE11, could you please have some advice?
```
Script:
        browser.url('http://webdriver.io');
        const tabIds = browser.getTabIds();
        browser.switchTab(tabIds[1]);

```
I use Grid to implement:
-------------------------
Log from Hub:
-------------------
<details>

C:\GRID>java -jar selenium-server-standalone-3.11.0.jar -role hub
18:36:40.685 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:36:40.687 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-07-31 18:36:41.034:INFO::main: Logging initialized @603ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:36:41.192 INFO [Hub.start] - Selenium Grid hub is up and running
18:36:41.192 INFO [Hub.start] - Nodes should register to http://10.192.8.5:4444/grid/register/
18:36:41.192 INFO [Hub.start] - Clients should connect to http://10.192.8.5:4444/wd/hub
18:36:44.542 INFO [DefaultGridRegistry.add] - Registered a node http://10.192.8.5:7777
18:40:13.462 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationC
ontextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, vers
ion: 11}
18:40:13.466 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {webdriver.ie.driver=C:/Program Files (x86)/Internet Explorer/iexplore.exe, server:CONFIG_UUID=9
5c55c53-df36-471e-85e0-b207a61ac316, seleniumProtocol=WebDriver, browserName=internet explorer, ignoreProtectedModeSettings=true, maxInstances=10, platformName=WINDOWS, version=11, plat
form=WINDOWS}

</details>

Log from Node:
-------------------
<details>

C:\GRID>java -Dwebdriver.ie.driver="C:/GRID/IEDriverServer_latest.exe" -jar selenium-server-standalone-3.11.0.jar -role node -hub http://10.192.8.5:4444/grid/register -nodeConfig "C:/GR
ID/nodeconfig_IE11_local.json"
18:36:43.994 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:36:43.997 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 7777
2018-07-31 18:36:44.133:INFO::main: Logging initialized @441ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:36:44.260 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
18:36:44.260 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 7777
18:36:44.260 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
18:36:44.265 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
18:36:44.265 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://10.192.8.5:4444/grid/register
18:36:44.548 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
18:36:44.590 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
18:40:13.560 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: tr
ue, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, version: 11}
18:40:13.562 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDr
iverService)
Started InternetExplorerDriver server (32-bit)
3.13.0.5
Listening on port 46906
Only local connections are allowed
18:40:14.570 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
18:40:14.585 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 97c7f754-8172-4aef-baf9-0a6ec6e08eee (org.openqa.selenium.ie.InternetExplorerDriverService)
18:40:20.196 INFO [ActiveSessions$1.onStop] - Removing session 97c7f754-8172-4aef-baf9-0a6ec6e08eee (org.openqa.selenium.ie.InternetExplorerDriverService)
</details>

**Comment by barancev** [comment]
Please report this issue to webdriver.io project

**Comment by lttrung112** [comment]
@barancev 
I already reported to  webdriver.io project they route to IE Driver team, can you show me the route cause?
https://github.com/webdriverio/webdriverio/issues/2828

**Comment by barancev** [comment]
Then, provide a reproduction scenario without use of webdriver.io, in vanilla Selenium, and we'll reopen the issue.

**Comment by DarkKnight711** [comment]
Can we reopen this issue? Encountering the same error when running on Grid. 

IEDriverServer 3.4 is the last version working on WebDriverIO

**Comment by jimevans** [comment]
@DarkKnight711 If, as mentioned above, we can get a reproduction scenario that does not involve webdriver.io, we'll happily open the issue.
