### ISSUE TITLE
Need `addCustomRequestHeaders` capabilities for ChromeOptions

### ISSUE THREAD

**Issue by prashanth-sams** [SeleniumHQ/selenium#6230]
## Meta -
**OS:**  
OSX, Linux
**Selenium Version:**  
3.10.0
**Browser:**  
Google Chrome
**Browser Version:**  
Google Chrome 64.0.3282.140 (64 bit)

## Actual Behavior -
Currently, `addCustomRequestHeaders` is not a part of Selenium 2 or 3 implementation. The generic way of bypassing basic auth like `https://user:pass@url.com` doesn't seems to work while automating redirects (from desktop to mobile) and some other complex scenarios.

## Steps to reproduce -
Need something like this as we had in Selenium RC,

      caps = Selenium::WebDriver::Remote::Capabilities.chrome(

      "chromeOptions" => {
          "addCustomRequestHeaders" => {'Authorization' => "Basic **encoded_userpass**"}
      })

      @driver = Selenium::WebDriver.for :chrome, desired_capabilities: caps

Meanwhile, I tried `browsermob-proxy`; but, I faced issues with `https` in `Chrome` browser; and starting `browsermob-proxy` port for parallel tests with 14+ browsers at the same time is never been a good idea.

**Comment by p0deje** [comment]
This is likely to be implemented in the next version of W3C WebDriver specification. Please, follow w3c/webdriver#385 for updates.
