### ISSUE TITLE
Message: OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL when using Chrome Headles

### ISSUE THREAD

**Issue by Haxy89** [SeleniumHQ/selenium#6234]
## Meta -
OS: Windows 10
Selenium Version:  3.13.1
Browser:  Chrome Headless 
Browser Version:  68.0.3440.84 64bit

## Expected Behavior -
Tests run in Headless mode
## Steps to reproduce -
I am starting chromedriver like this:

```
public static IWebDriver GetDriver()
        {
            var driverName = ConfigurationManager.AppSettings["Driver"];
            IWebDriver driver;

            switch (driverName.ToLowerInvariant())
            {
                case "chrome":
                    var options = new ChromeOptions();

                    if (ConfigurationManager.AppSettings["Headless"] == "true")
                    {
                        options.AddArgument("window-size=1920,1080");
                        options.AddArgument("headless");
                        options.AddArgument("disable-gpu");
                        options.AddArgument("no-sandbox");
                    }

                    driver = new ChromeDriver(options);
                    break;
                default:
                    throw new NotImplementedException();
            }

            return driver;
        }

```

When I use Chrome standalone everything works ok. When use headless I get timeout:
![image](https://user-images.githubusercontent.com/37550896/43522841-d1c68b26-959a-11e8-9407-7336587f3684.png)

![image](https://user-images.githubusercontent.com/37550896/43522999-4efde030-959b-11e8-8744-fb969b3c8a6d.png)

**Comment by jimevans** [comment]
@SCarlAdams No, they’re not the same issue. The other issue was in creating a session; this one relates to navigating to a url once a session has been created. Nevertheless, it’s difficult to see how this issue is a Selenium one as opposed to a Chrome or chromedriver.exe one. All the language bindings are doing is firing off an http request to chromedriver.exe, which doesn’t issue a response to the request before the timeout.

**Comment by alexeypt** [comment]
I bumped into the same issue (Chrome v71, Selenium.WebDriver.ChromeDriver v2.45). Adding the following lines fixed it for me:
```
options.AddArgument("proxy-server='direct://'");
options.AddArgument("proxy-bypass-list=*");
```
Full list of options:
```
ChromeOptions options = new ChromeOptions();
options.AddArgument("headless");
options.AddArgument("no-sandbox");
options.AddArgument("proxy-server='direct://'");
options.AddArgument("proxy-bypass-list=*");
```

More information about Network Settings: https://www.chromium.org/developers/design-documents/network-settings

**Comment by dodo1292** [comment]
> I bumped into the same issue (Chrome v71, Selenium.WebDriver.ChromeDriver v2.45). Adding the following lines fixed it for me:
> 
> ```
> options.AddArgument("proxy-server='direct://'");
> options.AddArgument("proxy-bypass-list=*");
> ```
> 
> Full list of options:
> 
> ```
> ChromeOptions options = new ChromeOptions();
> options.AddArgument("headless");
> options.AddArgument("no-sandbox");
> options.AddArgument("proxy-server='direct://'");
> options.AddArgument("proxy-bypass-list=*");
> ```
> 
> More information about Network Settings: https://www.chromium.org/developers/design-documents/network-settings

This worked for me too! You made my day after 2 weeks of ignorance...
