### ISSUE TITLE
/sessions endpoint doesn't respond

### ISSUE THREAD

**Issue by thedeeno** [SeleniumHQ/selenium#624]
If I pry into a `Selenium::WebDriver` session and attempt to hit the server with `GET /sessions` I receive the following error:

```
Selenium::WebDriver::Error::UnknownError: Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.
Active sessions are[ext. key d18b9dfa-e33b-49bf-a715-35e43b810c04] (org.openqa.grid.common.exception.GridException)
from [remote server] org.openqa.grid.internal.ActiveTestSessions(ActiveTestSessions.java):110:in `getExistingSession'
```
I've also tried to curl the end point as well:
```
curl -H "Content-Type: application/json; charset=UTF-8" -H "Accept: application/json" http://localhost:4444/sessions
```
But I keep getting this (incorrect) response:
```
<html><head><title>Selenium Grid2.0 help</title></head><body>You are using grid 2.45.0<br>Find help on the official selenium wiki : <a href='http://code.google.com/p/selenium/wiki/Grid2' >more help here</a><br>default monitoring page : <a href='/grid/console' >console</a></body></html>
```

Am I doing something wrong? There are active sessions and I can actually drive them through the server.

**Comment by lukeis** [comment]
this endpoint on the standalone server would be:

http://localhost:4444/wd/hub/sessions

not

http://localhost:4444/sessions

**Comment by thedeeno** [comment]
aaaannd, now I feel dumb. That url works great. Thank you!

**Comment by thedeeno** [comment]
Hmm @lukeis I'm still getting the following error:

```json
{"status":13,"value":{"message":"Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]","class":"org.openqa.grid.common.exception.GridException","stackTrace":[{"fileName":"ActiveTestSessions.java","className":"org.openqa.grid.internal.ActiveTestSessions","methodName":"getExistingSession","lineNumber":110},{"fileName":"Registry.java","className":"org.openqa.grid.internal.Registry","methodName":"getExistingSession","lineNumber":423},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"getSession","lineNumber":238},{"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"process","lineNumber":119},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"process","lineNumber":83},{"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"doGet","lineNumber":61},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":707},{"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":820},{"fileName":"ServletHolder.java","className":"org.seleniumhq.jetty7.servlet.ServletHolder","methodName":"handle","lineNumber":565},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doHandle","lineNumber":479},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doHandle","lineNumber":225},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1031},{"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty7.servlet.ServletHandler","methodName":"doScope","lineNumber":406},{"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty7.server.session.SessionHandler","methodName":"doScope","lineNumber":186},{"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","methodName":"doScope","lineNumber":965},{"fileName":"ScopedHandler.java","className":"org.seleniumhq.jetty7.server.handler.ScopedHandler","methodName":"handle","lineNumber":117},{"fileName":"HandlerWrapper.java","className":"org.seleniumhq.jetty7.server.handler.HandlerWrapper","methodName":"handle","lineNumber":111},{"fileName":"Server.java","className":"org.seleniumhq.jetty7.server.Server","methodName":"handle","lineNumber":349},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"handleRequest","lineNumber":452},{"fileName":"BlockingHttpConnection.java","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handleRequest","lineNumber":47},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","methodName":"headerComplete","lineNumber":884},{"fileName":"AbstractHttpConnection.java","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler","methodName":"headerComplete","lineNumber":938},{"fileName":"HttpParser.java","className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseNext","lineNumber":634},{"fileName":"HttpParser.java","className":"org.seleniumhq.jetty7.http.HttpParser","methodName":"parseAvailable","lineNumber":230},{"fileName":"BlockingHttpConnection.java","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","methodName":"handle","lineNumber":66},{"fileName":"SocketConnector.java","className":"org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint","methodName":"run","lineNumber":254},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":599},{"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":534},{"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}]}}
```

Thoughts?

**Comment by lukeis** [comment]
please follow up with a post to the user group:
https://groups.google.com/forum/#!forum/selenium-users

**Comment by thedeeno** [comment]
Issue raised in user group. Thanks again.

**Comment by Nakilon** [comment]
@thedeeno did you solve the last one?

**Comment by abacaj** [comment]
same problem here, no modifications running from `selenium-server-standalone-2.48.2.jar`

...any solutions?

**Comment by Nesaganesh** [comment]
Did anyone slove this issue, please anyone help I am stuck up with this and trying for last 3 days

**Comment by evasiuk** [comment]
I've got the same issue

**Comment by evasiuk** [comment]
looks like that is because of using non-default port (on 4444 there is expected page, but not usable), will try to align all ports

**Comment by evasiuk** [comment]
now getting:
{"value":{"stackTrace":[{"fileName":"ExternalSessionKey.java","methodName":"fromWebDriverRequest","className":"org.openqa.grid.internal.ExternalSessionKey","lineNumber":75},{"fileName":"WebDriverRequest.java","methodName":"extractSession","className":"org.openqa.grid.web.servlet.handler.WebDriverRequest","lineNumber":60},{"fileName":"RequestHandler.java","methodName":"getSession","className":"org.openqa.grid.web.servlet.handler.RequestHandler","lineNumber":237},{"fileName":"RequestHandler.java","methodName":"process","className":"org.openqa.grid.web.servlet.handler.RequestHandler","lineNumber":119},{"fileName":"DriverServlet.java","methodName":"process","className":"org.openqa.grid.web.servlet.DriverServlet","lineNumber":83},{"fileName":"DriverServlet.java","methodName":"doGet","className":"org.openqa.grid.web.servlet.DriverServlet","lineNumber":61},{"fileName":"HttpServlet.java","methodName":"service","className":"javax.servlet.http.HttpServlet","lineNumber":707},{"fileName":"HttpServlet.java","methodName":"service","className":"javax.servlet.http.HttpServlet","lineNumber":820},{"fileName":"ServletHolder.java","methodName":"handle","className":"org.seleniumhq.jetty7.servlet.ServletHolder","lineNumber":565},{"fileName":"ServletHandler.java","methodName":"doHandle","className":"org.seleniumhq.jetty7.servlet.ServletHandler","lineNumber":479},{"fileName":"SessionHandler.java","methodName":"doHandle","className":"org.seleniumhq.jetty7.server.session.SessionHandler","lineNumber":225},{"fileName":"ContextHandler.java","methodName":"doHandle","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","lineNumber":1031},{"fileName":"ServletHandler.java","methodName":"doScope","className":"org.seleniumhq.jetty7.servlet.ServletHandler","lineNumber":406},{"fileName":"SessionHandler.java","methodName":"doScope","className":"org.seleniumhq.jetty7.server.session.SessionHandler","lineNumber":186},{"fileName":"ContextHandler.java","methodName":"doScope","className":"org.seleniumhq.jetty7.server.handler.ContextHandler","lineNumber":965},{"fileName":"ScopedHandler.java","methodName":"handle","className":"org.seleniumhq.jetty7.server.handler.ScopedHandler","lineNumber":117},{"fileName":"HandlerWrapper.java","methodName":"handle","className":"org.seleniumhq.jetty7.server.handler.HandlerWrapper","lineNumber":111},{"fileName":"Server.java","methodName":"handle","className":"org.seleniumhq.jetty7.server.Server","lineNumber":349},{"fileName":"AbstractHttpConnection.java","methodName":"handleRequest","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","lineNumber":452},{"fileName":"BlockingHttpConnection.java","methodName":"handleRequest","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","lineNumber":47},{"fileName":"AbstractHttpConnection.java","methodName":"headerComplete","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection","lineNumber":884},{"fileName":"AbstractHttpConnection.java","methodName":"headerComplete","className":"org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler","lineNumber":938},{"fileName":"HttpParser.java","methodName":"parseNext","className":"org.seleniumhq.jetty7.http.HttpParser","lineNumber":634},{"fileName":"HttpParser.java","methodName":"parseAvailable","className":"org.seleniumhq.jetty7.http.HttpParser","lineNumber":230},{"fileName":"BlockingHttpConnection.java","methodName":"handle","className":"org.seleniumhq.jetty7.server.BlockingHttpConnection","lineNumber":66},{"fileName":"SocketConnector.java","methodName":"run","className":"org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint","lineNumber":254},{"fileName":"QueuedThreadPool.java","methodName":"runJob","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool","lineNumber":599},{"fileName":"QueuedThreadPool.java","methodName":"run","className":"org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3","lineNumber":534},{"fileName":"Thread.java","methodName":"run","className":"java.lang.Thread","lineNumber":745}],"class":"java.lang.NullPointerException"},"status":13}

**Comment by abacaj** [comment]
I had to build my own endpoint to get the queue length - because the default page was returning errors.
