### ISSUE TITLE
INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS not ignoring protected settings. (Java)

### ISSUE THREAD

**Issue by jrgleason** [SeleniumHQ/selenium#6247]
## Meta -
OS:  
Windows 7 Enterprise
Selenium Version:  

Browser:  
IE 
Lang:
Java 1.8

Browser Version:  
11.0.9600 (32 bit)

## Expected Behavior -

        DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
        capabilities.setCapability(INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        ...
        System.setProperty("webdriver.ie.driver", "./libs/IEDriverServer.exe");
        InternetExplorerOptions options = new InternetExplorerOptions(capabilities);
        return new InternetExplorerDriver(options);

Should allow me to open IE

## Actual Behavior -

    org.openqa.selenium.SessionNotCreatedException: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.
    Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
    System info: host: 'XXX', ip: 'XXXXX', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_161'
    Driver info: driver.version: InternetExplorerDriver
    remote stacktrace: 

Steps to reproduce:

This is a little tougher because I think it is based on my config of protected settings which is regulated by dev-ops so I have very little freedom. I would be more than happy to try to create an agnostic example if someone can lead me down that path.

**Comment by jimevans** [comment]
Can you provide a TRACE-level log from IEDriverServer.exe? That would likely be instructive.

**Comment by barancev** [comment]
Closing the issue as there is no requested information (logs) provided.
