### ISSUE TITLE
Selenium release 3.14.0 - Broken ABI with appium-dotnet-driver 

### ISSUE THREAD

**Issue by pavkr** [SeleniumHQ/selenium#6248]
The issue was presented in 3.11.1 and addressed in v 3.11.2
I've hit the same issue in latest 3.14.0

Link to a previous bug report: 
[https://github.com/SeleniumHQ/selenium/issues/5768](github/issues/5768)

Selenium version: 3.14.0
Appium driver version: 3.0.0.2

An Exception: 
`System.TypeLoadException: 'Method 'Dispose' in type 'OpenQA.Selenium.Appium.Service.AppiumCommandExecutor' from assembly 'appium-dotnet-driver, Version=3.0.0.2, Culture=neutral, PublicKeyToken=null' does not have an implementation.'`

**Comment by jimevans** [comment]
Nope. This isn't changing back a second time. Please see the note in the [CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG#L78). Appium is going to have to release an update for this. A [pull request](https://github.com/appium/appium-dotnet-driver/pull/218) implementing this code in Appium [was merged](https://github.com/appium/appium-dotnet-driver/commit/3e01e49730cf473c7ca4edbad708af6e8fa8a3e4) on 20 June. The Selenium .NET bindings do not adhere to "semver" rules, and do not guarantee a binary interface between "y" releases (where version numbers are "x.y.z").

**Comment by pavkr** [comment]
Fair enough! Thank you.
Meanwhile, for the rest, if you need lates appium but not webdriver, selenium.webdriver 3.12.1 will not have this issue
