### ISSUE TITLE
To the *Options classes, add an `addEnvironmentVariables` method

### ISSUE THREAD

**Issue by nddipiazza** [SeleniumHQ/selenium#6249]
## Meta -
OS:  
All
Selenium Version:  
3.x
Browser:  
Chrome, maybe the others as well

## Expected Behavior -

There are a pretty good number of situations when you want to set the environment variables that will be set to a driver service.

Common enough that we should probably add environment variables to the classes that inherit `MutableCapabilities`. Specially `ChromeOptions` so that uses can just use the simple paradigm:

```
ChromeOptions options = new ChromeOptions();
options.addEnvironmentVariables("TMPDIR", "/custom/tmp/dir");
ChromeDriver driver = new ChromeDriver(options);
```

We should allow this.

## Actual Behavior -

Since we don't have that variable, it forces us to use the other paradigm to fire up a chrome driver service.

```
ChromeDriverService chromeDriverService = new ChromeDriverService.Builder()
         .usingDriverExecutable(new File("driver_linux/chromedriver"))
         .usingAnyFreePort()
         .withEnvironment(ImmutableMap.of("TMPDIR", "/some/other/stuff")).build();
```

but that requires a lot of refactoring and difficulties. Not desirable.

**Comment by jimevans** [comment]
I'm not sure I'd support this. There's a valid separation of concerns between the `Options` class, which controls the capabilities requested of the browser driver, and the `Service` class, which controls the execution of the driver executable. Adding things about the latter to the former increases confusion about which pieces belong where.

**Comment by nddipiazza** [comment]
I just feel like if you allow command line arguments there you should allow environment variables there too. Without it causes the refactoring as I mentioned.

**Comment by jimevans** [comment]
@nddipiazza What do you mean "if you allow command line arguments there?" The `addArguments` method that exists on `ChromeOptions`, which adds command-line switches to the `chrome.exe` command line? That's a feature internal to the driver for Chrome, and not universal to all drivers. Yes, Firefox and Chrome support it, but IE, Edge, and Safari don't. Selenium doesn't have any control over how the browser is launched above what the driver allows it to have via capabilities (which are exposed through the `Options` classes). Even if you added an `addEnvironmentVariable` method to the options class, there is no guarantee that the browser launched by the driver would be in an environment that inherited those environment variables. If you expect that the browser launched by the driver will inherit the environment in which the driver executable is launched, then (1) you're relying on undefined behavior and happening to get lucky, and (2) the proper place to define the environment that the driver executable uses is in the `Service` class.

**Comment by nddipiazza** [comment]
OK let's focus the conversation to just `ChromeOptions` for now.
I'm confused by this: 
> Even if you added an addEnvironmentVariable method to the options class, there is no guarantee that the browser launched by the driver would be in an environment that inherited those environment variables. 

My use case was this: https://superuser.com/questions/1345618/what-is-the-chrome-command-line-argument-in-headless-no-sandbox-mode-that-pick

Basically I had to either use Chrome Driver Service, or use a global environment variable `/etc/environment`. but i was unable to use the simple `ChromeDriver driver = new ChromeDriver(new ChromeOptions());`. So my line of thinking is... if you can get command line arguments to the process with ChromeOptions.addArguments... why can't we also send environment variables? Seems the same to me?

**Comment by lmtierney** [comment]
> So my line of thinking is... if you can get command line arguments to the process with ChromeOptions's addArguments

But this doesn't add command line arguments to chromedriver, it gets them to chrome when chromedriver starts chrome

**Comment by nddipiazza** [comment]
Ahhhhh right. darn. Yep that's the piece I was missing.

**Comment by nddipiazza** [comment]
Yeah i didn't realize it was just this easy: 
```
driver = new ChromeDriver(new ChromeDriverService.Builder()
                  .usingAnyFreePort()
                  .withEnvironment(ImmutableMap.of("TMPDIR", WORK_DIR.getAbsolutePath()))
                  .build(), options);
```
