### ISSUE TITLE
Python RemoteDriver regression in version 3.14.0

### ISSUE THREAD

**Issue by jugglinmike** [SeleniumHQ/selenium#6250]
OS: macOS
Selenium Version: 3.14.0 (Python bindings)
Browser:  Apple Safari
Browser Version: 11.1.1 (13605.2.8)

## Expected Behavior -

The RemoteDriver should be capable of sending multiple commands to the same session.

## Actual Behavior -

The RemoteDriver fails to interact with a session following creation.

## Steps to reproduce -

Given a file `repro.py`:

```py
from selenium import webdriver
driver = webdriver.Remote('http://127.0.0.1:4444')
driver.title
```

And a running instance of `safaridriver` via

    $ safaridriver --port 4444

Version 3.13.0 executes the script with no errors. Version 3.14.0 reports the following error:

    Traceback (most recent call last):
      File "repro.py", line 3, in <module>
        driver.title
      File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 341, in title
        resp = self.execute(Command.GET_TITLE)
      File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
        self.error_handler.check_response(response)
      File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
        raise exception_class(value)
    selenium.common.exceptions.WebDriverException: Message: 

(The reported error message is truncated.)

**Comment by lmtierney** [comment]
It looks like safaridriver needs `keep_alive` set with the `urllib3` changes (using `webdriver.Safari()` sets `keep_alive` to `True` by default). This works without error:

```
from selenium import webdriver
driver = webdriver.Remote('http://127.0.0.1:4444', keep_alive=True)
driver.title
```

I'm not sure what change with the move to `urllib3` would have caused this to start happening though. @AutomatedTester thoughts?

**Comment by lmtierney** [comment]
It seems to work if I duplicate the conditional:
```
if body and method != 'POST' and method != 'PUT':
    body = None
```
To the non-keep_alive request


https://github.com/SeleniumHQ/selenium/blob/49a58eb5854e2c4b93f817a4cffd3df54bb0436c/py/selenium/webdriver/remote/remote_connection.py#L394-L409

**Comment by jugglinmike** [comment]
I first experienced the regression using Safari Technology Preview, but I figured the report would seem more legitimate if it were demonstrated with more stable software :)

**Comment by jugglinmike** [comment]
Thanks, @AutomatedTester!
