### ISSUE TITLE
Severe bug in Firefox driver

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#6266]
There is are fat bugs in https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Firefox/Internal/Executable.cs   in LocateFirefoxBinaryFromPlatform()

The Selenium programmer who wrote this code doesn't have any experience in Windows programming. If you run the Selenium code in a 32 bit application the buggy code will not find a 64 bit version of Firefox. This is a shame.

A 32 bit Windows process accesses other locations in the registry than a 64 bit process.

The 64 bit installations of Firefox are written to 
HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox

The 32 bit installations of Firefox are written to 
HKEY_LOCAL_MACHINE\SOFTWARE\Wow64Node\Mozilla\Mozilla Firefox

1.) BUG 
The buggy code does not search in both nodes for a Firefox installation so it will only find anything if Firefox has the same bitness as the application which runs Selenium. A 32 bit process will only find 32 bit Firefoxes and vice versa. But the 32 bit Gecko driver can  automate both: Firefox 32 and 64, so this makes no sense.

2.) BUG 
if (mozillaKey == null) { mozillaKey = Registry.CurrentUser.OpenSubKey(firefoxRegistryKey);

The code searches in HKEY_CURRENT_USER which is complete nonsense because there it will never find an install path.

3.) BUG 
Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles) + " (x86)" is completely wrong for the same reason because SpecialFolder.ProgramFiles points to a different folder depending if the Selenium code runs in a 32 bit or a 64 bit application. This is completely wrong. 
Correct would be to use SpecialFolder.ProgramFiles and SpecialFolder.ProgramFilesX86. See https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.110).aspx. Additionally it is completely wrong to assume that Firefox is installed into a specific folder and search on the disk. All the information is already in the Registry and searching on the disk is a dirty workaround which has only been implemented because the code which searches in the registry is buggy. The Firefox installer writes the install path into the registry and there is absolutely no reason to search Firefox on the disk.

4.) OBSOLETE
// Didn't find binary in any of the default install locations, so look
// at directories on the user's PATH environment variable.

This is really a shame. The PATH variable is completely OBSOLETE. It was from the old times of Windows 3 and should not be used anymore in modern software !

5.) AWKWARD CODE
in GetExecutablePathUsingRegistry() :
.... string.Format(CultureInfo.InvariantCulture, @"{0}\Main", currentVersion)
Why so complicated?

-------------------------

I post a tested and working code here which works ALWAYS. There is neither a workaround required to search Firefox on disk nor in the PATH environment variable at all.

Please replace all the buggy code with this function:

`

        // Selenium is unable to read a 64 registry path from a 32 bit Selenium process!
        // This code is bullet proof.
        protected String FindFirefoxExe()
        {
            List<RegistryView> i_Views = new List<RegistryView>();
            i_Views.Add(RegistryView.Registry32);
            if (Utils.Is64BitPlatform())
                i_Views.Add(RegistryView.Registry64);
            
            foreach (RegistryView e_View in i_Views)
            {
                using (RegistryKey i_HKLM = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, e_View))
                {
                    using (RegistryKey i_Moz = i_HKLM.OpenSubKey(@"SOFTWARE\Mozilla\Mozilla Firefox"))
                    {
                        if (i_Moz == null)
                            continue;

                        String s_CurVersion = (String)i_Moz.GetValue("CurrentVersion");
                        if (String.IsNullOrEmpty(s_CurVersion))
                            continue;
                                                        
                        using (RegistryKey i_Main = i_Moz.OpenSubKey(s_CurVersion + @"\Main"))
                        {
                            if (i_Main == null)
                                continue;

                            String s_Path = (String)i_Main.GetValue("PathToExe");
                            if (s_Path != null && File.Exists(s_Path))
                                return s_Path;
                        }
                    }
                }
            }

            throw new Exception("Could not read the current FireFox version from the registry. Please install Firefox anew.");
        }
`

Please note that in the case that Firefox is installed as 32 bit AND as 64 installations the code will first search the 32bit "CurrentVersion" and if not found it will search the 64bit "CurrentVersion". You can change this order by adding the  RegistryView in the opposite order to i_View.

NOTE: If you don't want to implement a function Is64BitPlatform() you can also omit this if (...) 
In case that the code is running on a 32 bit Windows, RegistryView.Registry64 will be redirected automatically to the 32 bit registry hive.

`
        
          List<RegistryView> i_Views = new List<RegistryView>();     
           i_Views.Add(RegistryView.Registry32);
           i_Views.Add(RegistryView.Registry64);
`
would search the 32 bit hive twice on a 32 bit Windows.

**Comment by shs96c** [comment]
@Elmue, I'd kindly remind you that another human being wrote this code, and you're being incredibly rude. I'm closing this issue because I have little interest in dealing with people who can't be bothered to show the slightest shred of civility towards someone who's given their free time to gift the world Open Source Software.

If you want this issue fixed, please refile and imagine that I'm going to cc your most dearly loved with whatever it is you write.

**Comment by schmidtkp** [comment]
@Elmue As a member of the Selenium community at large, and not the developer of the above mentioned code, I do find your "combative" style of reporting problems very "unprofessional". There is no need to "shame" someone. You may not know the history behind why code was written the way it was, at some given point in time. Maybe it is obsolete and could be refreshed. Who knows. I for one greatly appreciate those that take the time to work on the Selenium project without compensation and in their own spare time. In the future, please refrain from such remarks and stick to simply stating the facts of the issue. Leave the emotions out.

**Comment by shs96c** [comment]
I'm locking this issue. I don't think we're going to have a productive conversation here. @schmidtkp, thank you for your support. It's much appreciated.
