### ISSUE TITLE
Devexpress SpinEdit

### ISSUE THREAD

**Issue by ivanb000** [SeleniumHQ/selenium#6267]
## Meta -
OS:  Windows 10
Selenium Version:  3.1.0, Chrome IDE
Browser:  Chrome

Browser Version:  Version 68.0.3440.106 (Official Build) (64-bit)

## Expected Behavior -
Go to "https://demos.devexpress.com/aspxeditorsdemos/ASPxSpinEdit/Features.aspx"
Do a Selenium Chrome IDE Test on the First and third Spin Editors
Start Recording:
Command "Type"
Target "id=ContentHolder_ASPxSpinEdit1_I" //This is the First Spin Editor
or
Target "id=ContentHolder_ASPxSpinEdit3_I" //This is the Third Spin Editor
Value "11"
Finish Recording
Run the Tests:
Expected Behavior is that the test fills the Spin Editors

## Actual Behavior -
Same as above 
But the Run the Tests:
Actual Behavior is that the test leaves the Spin Editors empty

## Steps to reproduce -
Follow the Expected Behavior Steps

Thanks and Best Regards,
Ivan

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #334](https://github.com/SeleniumHQ/selenium-ide/issues/334) via [**ZenHub**](https://www.zenhub.com/)
