### ISSUE TITLE
Selenium does not find Firefox Installation

### ISSUE THREAD

**Issue by Elmue** [SeleniumHQ/selenium#6268]
There are several bugs in https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Firefox/Internal/Executable.cs in LocateFirefoxBinaryFromPlatform()

If you run the Selenium code in a 32 bit application the code will not find a 64 bit installation of Firefox. 
But the 32 bit Gecko driver can automate both: Firefox 32 and 64, so this makes no sense.

A 32 bit Windows process accesses other locations in the registry than a 64 bit process.

The 64 bit installations of Firefox are written to
HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox

The 32 bit installations of Firefox are written to
HKEY_LOCAL_MACHINE\SOFTWARE\Wow64Node\Mozilla\Mozilla Firefox

1.) BUG
The code does not search in both nodes for a Firefox installation so it will only find anything if Firefox has the same bitness as the application which runs Selenium. A 32 bit process will only find 32 bit Firefoxes and vice versa. 

2.) BUG
if (mozillaKey == null) { mozillaKey = Registry.CurrentUser.OpenSubKey(firefoxRegistryKey);

The code searches in HKEY_CURRENT_USER which is useless because there it will never find an install path.

3.) BUG
Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles) + " (x86)" is wrong for the same reason because SpecialFolder.ProgramFiles points to a different folder depending if the Selenium code runs in a 32 bit or a 64 bit application.
Correct would be to use SpecialFolder.ProgramFiles and SpecialFolder.ProgramFilesX86. See https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.110).aspx. Additionally it is wrong to assume that Firefox is installed into a specific folder and search on the disk. (My Firefox is for example installed into an individual folder) 
All the information is already in the Registry and searching on the disk is a workaround which has only been implemented because the code which searches in the registry is buggy. The Firefox installer writes the install path into the registry and there is absolutely no reason to search Firefox on the disk.

4.) OBSOLETE
// Didn't find binary in any of the default install locations, so look
// at directories on the user's PATH environment variable.

The PATH variable is completely obsolete. It was from the old times of Windows 3 and should not be used anymore in modern software.

5.) AWKWARD CODE
in GetExecutablePathUsingRegistry() :
.... string.Format(CultureInfo.InvariantCulture, @"{0}\Main", currentVersion)
Why so complicated?

I post a tested and working code here which works always. There is neither a workaround required to search Firefox on disk nor in the PATH environment variable at all.

Please replace all the buggy code with this function:

`

    // Selenium is unable to read a 64 registry path from a 32 bit Selenium process.
    // This code is bullet proof.
    protected String FindFirefoxExe()
    {
        List<RegistryView> i_Views = new List<RegistryView>();
        i_Views.Add(RegistryView.Registry32);
        if (Utils.Is64BitPlatform())
            i_Views.Add(RegistryView.Registry64);
        
        foreach (RegistryView e_View in i_Views)
        {
            using (RegistryKey i_HKLM = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, e_View))
            {
                using (RegistryKey i_Moz = i_HKLM.OpenSubKey(@"SOFTWARE\Mozilla\Mozilla Firefox"))
                {
                    if (i_Moz == null)
                        continue;

                    String s_CurVersion = (String)i_Moz.GetValue("CurrentVersion");
                    if (String.IsNullOrEmpty(s_CurVersion))
                        continue;
                                                    
                    using (RegistryKey i_Main = i_Moz.OpenSubKey(s_CurVersion + @"\Main"))
                    {
                        if (i_Main == null)
                            continue;

                        String s_Path = (String)i_Main.GetValue("PathToExe");
                        if (s_Path != null && File.Exists(s_Path))
                            return s_Path;
                    }
                }
            }
        }

        throw new Exception("Could not read the current FireFox version from the registry. Please install Firefox anew.");
    }

`

Please note that in the case that Firefox is installed as 32 bit AND as 64 installations the code will first search the 32bit "CurrentVersion" and if not found it will search the 64bit "CurrentVersion". You can change this order by adding the RegistryView in the opposite order to i_View.

NOTE: If you don't want to implement a function Is64BitPlatform() you can also omit this if (...)
In case that the code is running on a 32 bit Windows, RegistryView.Registry64 will be redirected automatically to the 32 bit registry hive.

`

       RegistryView[] i_Views = new ListRegistryView[] { RegistryView.Registry32, RegistryView.Registry64 };

`
would search the 32 bit hive twice on a 32 bit Windows.

**Comment by cgoldberg** [comment]
The proper way to propose code changes is via Pull Request after signing the Contributor License Agreement, not in a narrative bug report filled with derogatory remarks.

**Comment by Elmue** [comment]
Maybe you explain me what this list of issues is useful for if nobody cares about severe bugs during 3 months? If the Selenium code tells that Firefox is not installed although it is, this is a very severe bug for me. So you tell the people not to post bugs here anymore? And that I post code here which is ready for copy and paste is not enough support?

**Comment by Elmue** [comment]
And by the way, I cannot see any "derogatory remarks" in my bugreport.

**Comment by jimevans** [comment]
Alright, I'm locking this issue. There's no need for the hostility. Yes, this issue hasn't received any attention, mostly because the code in question is likely to undergo a large revision (and will likely be removed entirely) in the run-up to Selenium 4.0. I apologize for not immediately commenting to that effect when the issue was initially reported.

**Comment by jimevans** [comment]
I'm now also closing this issue, since, as of the addition of 6722058, the code being referenced is no longer part of the project.
