### ISSUE TITLE
While Running RC Program with Firefox The Mozila is diplaying as Mozila Crash Reporter

### ISSUE THREAD

**Issue by kishoreplans** [SeleniumHQ/selenium#627]
RC Execution code

package test;

import com.thoughtworks.selenium.DefaultSelenium;
import com.thoughtworks.selenium.Selenium;

public class RC1 {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		Selenium s = new DefaultSelenium("localhost",4444,"*firefox","http://google.co.in");
		
		s.start();
		s.windowMaximize();
		s.windowFocus();
		s.open("/");
	}
}

Selenium RC version : 2.46.0 
Firefox: 38.0.5

**Comment by lukeis** [comment]
RC is deprecated. Please use WebDriver or WebDriverBackedSelenium if you must continue to use the RC interface. 

We not longer track issues related to RC.

**Comment by barancev** [comment]
Nevertheless, I've fixed this issue :)
Fixed by commit 5331865dcaf4273d4b2ba9a3bbd5e37c845dccef

**Comment by lukeis** [comment]
Dammit @barancev stop that! ;)
