### ISSUE TITLE
SelectElement and ng-select

### ISSUE THREAD

**Issue by melanchall** [SeleniumHQ/selenium#6272]
Is it possible to use Selenium for `ng-select` elements? Previously on a site `select` elements were presented, but recently they were replaced by `ng-select` ones. My code relies on `SelectElement` class which doesn't support `ng-select`.

In particular I need `Options` property provided by `SelectElement`. Is there a way to operate by `ng-select` with Selenium?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
