### ISSUE TITLE
Adjust the log_path DeprecationWarning's stack level

### ISSUE THREAD

**Issue by edmorley** [SeleniumHQ/selenium#6274]
## Meta -
OS:  Windows 10
Selenium Version:  
Browser:  Firefox
Browser Version: 63.0a1

## Expected Behavior -

That the `DeprecationWarning` added in #5979 sets an appropriate [stacklevel](https://docs.python.org/2/library/warnings.html#warnings.warn), so that the warning references the offending caller, and not the file + line number of where the `logger.warn()` is called.

## Actual Behavior -

`stacklevel` not used, so the stack trace doesn't point at the offending caller:

```
        if log_path:
>           warnings.warn('use service_log_path instead of log_path', DeprecationWarning)
E           DeprecationWarning: use service_log_path instead of log_path
../../../venv/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py:104: DeprecationWarning
```

## Steps to reproduce -

Update a project using pytest-selenium 1.13 from selenium 3.13.0 to 3.14.0 with DeprecationWarnings as errors. eg:
mozilla/treeherder#3872
https://travis-ci.org/mozilla/treeherder/jobs/411325051#L947

**Comment by lmtierney** [comment]
Currently none of our `DeprecationWarning` warnings have a `stacklevel` different than default. I'm not against changing this, but if we do it for `service_log_path` we should probably do it for all of them.

Thoughts @AutomatedTester ?

**Comment by lmtierney** [comment]
Added `stacklevel=2` to all DeprecationWarning via 18681a6c1b59434f2639c2c56383a58f1118f009

**Comment by edmorley** [comment]
Many thanks :-)
