### ISSUE TITLE
Null pointer Exception on doing element.getText() in appium

### ISSUE THREAD

**Issue by sukirti21** [SeleniumHQ/selenium#6276]
Hi I am getting **nullPointerException when i am doing getText() operation on element.**When i am debugging my code I saw that element is founded successfully but when i am doing 
element.getText(),it gives me null pointer. Kindly help me resolving this issue.

//Screenshot Attached:
<img width="1440" alt="screen shot 2018-08-13 at 7 00 36 pm" src="https://user-images.githubusercontent.com/42337640/44039273-61f91156-9f36-11e8-8016-1aca0f744cac.png">
<img width="1440" alt="screen shot 2018-08-13 at 7 00 53 pm" src="https://user-images.githubusercontent.com/42337640/44039326-7ffd039c-9f36-11e8-9a5f-c4d20e8329e0.png">

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
