### ISSUE TITLE
Error when writing password field

### ISSUE THREAD

**Issue by Samirovich** [SeleniumHQ/selenium#6279]
## Meta -
OS:  
GNU/Linux Fedora 28
Selenium Version:  
3.14.0
Browser:  
Firefox (and Chrome)

Browser Version:  
61.0.1 (64bit)

## Expected Behavior -
Fill password textfield
## Actual Behavior -
Throws error when doing so:
Traceback (most recent call last):
  File "selenium_test.py", line 16, in <module>
    login("username","password)
  File "selenium_test.py", line 13, in login
    password.send_keys(password) # Write password into password box
  File "/home/samir/Envs/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 478, in send_keys
    {'text': "".join(keys_to_typing(value)),
  File "/home/samir/Envs/venv/lib/python3.6/site-packages/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'FirefoxWebElement' has no len()

## Steps to reproduce -
```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

def login(user, password):
    browser = webdriver.Firefox()
    browser.get('https://misiir.sii.cl/cgi_misii/siihome.cgi')
    rut = browser.find_element_by_id('rutcntr')  # Find rut box
    password = browser.find_element_by_id('clave') # Find password box
    #browser.find_element_by_css_selector("[title^='Ingresar]").click() # Click "Ingresar" button
    rut.send_keys(user) # Write user(rut) into box
    password.send_keys(password) # Write password into password box
    rut.submit()

login("username","password")
```

I also tried on another machine and using the chromedriver and same error appears

**Comment by ingmargoudt** [comment]
This is a question rather than an issue. Look at what your exception says and look at your code. You are writing a WebElement in a WebElement.

**Comment by Samirovich** [comment]
My bad
