### ISSUE TITLE
IDE clicking links opening 2 tabs and comment usage severely changed  

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/selenium#6282]
## Meta -
OS:  Windows 10

Selenium Version:  3.2 IDE

Browser:  Firefox

Browser Version:  61.0.2 (64-bit)

## Expected Behavior -
External Links to open one page, blank commands or commands with just comments continue test
## Actual Behavior -
External Links to open 2 pages , blank commands or commands with just comments fail test
## Steps to reproduce -

example commands:

{
      "id": "8b361480-6900-499b-9528-b4a96dc8100a",
      "comment": "",
      "command": "clickAt",
      "target": "css=#dataTable1 > tbody > tr.child > td > div > div:nth-child(2) > em > em > strong:nth-child(7) > strong > p > a",
      "targets": [],
      "value": ""
    }

this is the link it opens: 
href="http://docquery.fec.gov/cgi-bin/fecimg/?201606109017556842"

this command set as follows will cause a failure where previously it wouldn't.
 {
      "id": "645bcd21-32c1-4624-8dbe-8c4877cef97f",
      "comment": "Tests top of page stuff",
      "command": "",
      "target": "",
      "targets": [],
      "value": ""
    }

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #344](https://github.com/SeleniumHQ/selenium-ide/issues/344) via [**ZenHub**](https://www.zenhub.com/)
