### ISSUE TITLE
Expected condition "ElementToBeClickable" misleading. 

### ISSUE THREAD

**Issue by alex4200** [SeleniumHQ/selenium#6285]
## Meta -
OS:  
Ubuntu 16.04, OsX 10.13.6, others
Selenium Version:  
3.8.0, 3.11.0
Browser:  
Firefox (various versions), geckodriver 0.18.0, 0.19.1

## Expected Behavior -

When using the expected condition `ElementToBeClickable` in a constructions like the following: 
```
WebDriverWait(bspdriver.webdriver, 60).\
                until(EC.element_to_be_clickable(what)).click()
```

I expect the webdriver to wait until an element is _clickable_.  As the name of the expected condition says you:  `ElementToBeClickable`

## Actual Behavior -

If the element is hidden behind some other element (like an alert, see e.g. [here](https://stackoverflow.com/questions/51841884/python-selenium-finds-clickable-element-that-cannot-be-clicked) or [here](https://stackoverflow.com/questions/51654804/elementtobeclickable-issues-with-selenium-java)) the `WebDriverWait` method does not wait until the element really becomes _clickable_,  but continues. Therefore the following `click` results in some error like

````
ElementClickInterceptedException: Message: Element <button class="ivu-btn ivu-btn-primary ivu-btn-long ivu-btn-small" type="button"> is not clickable at point (1193.3332901000977,522) because another element <div class="ivu-modal-wrap vertical-center-modal circuit-loading-modal"> obscures it
````

Suggestion: Either fix this issue, or the expected condition should be named like

`ElementToBeClickableExceptObscurredByOtherElement`

## Steps to reproduce -

TBD if really required.

**Comment by lmtierney** [comment]
The documentation for the ExpectedCondition lists what it checks for. You can always add more errors to ignore when you create your wait:

```
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support.expected_conditions import ExpectedConditions as EC

WebDriverWait(bspdriver.webdriver, 60, ignored_exceptions=(ElementClickInterceptedException)).until(EC.element_to_be_clickable(what)).click()
```

**Comment by alex4200** [comment]
I do not quite understand the reason this ticket has been closed. I appreciate if someone can explain it to me in greater detail. 

Maybe you mean that the name of a method/function does not need to represent what the method/function is supposed to do?

**Comment by barancev** [comment]
@alex4200 Legacy is hard... If we rename the method thousands of users will be hurt by this change.
