### ISSUE TITLE
Safari web driver 2.48 with Safari 11.1.0 and Version: Oxygen.3a Release (4.7.3a)

### ISSUE THREAD

**Issue by namrata2929** [SeleniumHQ/selenium#6289]
I was trying a simple test automation and I have downloaded the JAR from the Selenium from http://selenium-release.storage.googleapis.com/index.html?path=2.53/. 

The code is as below:
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.safari.SafariDriver;

public class IndeedTest {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		
		WebDriver driver=new SafariDriver();
		driver.get("https://www.google.com");
		driver.findElement(By.name("q")).sendKeys("download selenium");
		Thread.sleep(2000);
		driver.findElement(By.name("btnK")).click();

	}

}

I am not able to connect to the safari browser.The error I get is as below:
INFO: Stopping Safari
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Aug 15, 2018 3:56:30 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10071 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Jhon-MacBook-Pro.local', ip: '195.164.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_111'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:76)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:62)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:42)
	at IndeedTest.main(IndeedTest.java:10)

**Comment by namrata2929** [comment]
Any suggestion to resolve the issue

**Comment by jimevans** [comment]
Recent versions of Safari will not work with the extension-based, obsolete, and no-longer-maintained driver that used to be available from the Selenium project. Modern versions of Safari require Apple’s driver implementation, which is supplied as part of the OS. Unfortunately, the introduction of the new driver happened after the last 2.x release of Selenium. The way to “resolve the issue” is to update to the most recent Selenium release (3.14 at the time of this writing).
