### ISSUE TITLE
Selenium web drive  with Oxygen.3a Release (4.7.3a) and 3.14 gecko driver on Mac OS 13.3

### ISSUE THREAD

**Issue by namrata2929** [SeleniumHQ/selenium#6290]
I am trying to implement the test case and the code is as below.I have added the latest JAR files for selenium and firefox 61.0 version.

import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
public class IndeedTest {
	
	public static void main(String[] args) {
		System.setProperty("webdriver.gecko.driver","geckodriver.exe");
		//It opens the firefox browser
		
		FirefoxDriver driver = new FirefoxDriver();
		//Enetr the URL
		
		driver.get("http://www.indeed.co.in");
		
		driver.findElement(By.id("what")).clear();
		driver.findElement(By.id("what")).sendKeys("Selenium");
		
		driver.findElement(By.id("where")).sendKeys("Bangalore");
		
		driver.findElement(By.id("fj")).click();
		
		
	}

}
The code is not executed as expected.This has the following error

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
/features/webcompat-reporter@mozilla.org.xpi
1534372102181	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat-reporter@mozilla.org version 1.0.0
1534372102182	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1534372102183	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 2.0
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1534372102232	addons.manager	DEBUG	Provider finished startup: XPIProvider
1534372102232	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1534372102233	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1534372102233	addons.manager	DEBUG	Starting provider: GMPProvider
1534372102466	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1534372102467	addons.manager	DEBUG	Provider finished startup: GMPProvider
1534372102467	addons.manager	DEBUG	Starting provider: PluginProvider
1534372102467	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1534372102468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1534372102479	addons.manager	DEBUG	Completed startup sequence
1534372107763	addons.repository	DEBUG	No addons.json found.
2018-08-15 18:28:31.828 plugin-container[2424:105869] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6e3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:38.438 plugin-container[2425:105949] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9743, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:47.583 plugin-container[2426:106123] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6b43, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
console.error: "Could not write session state file " (new Error("_initWorker called too early! Please read the session file from disk first.", "resource:///modules/sessionstore/SessionFile.jsm", 335)) "_initWorker/<@resource:///modules/sessionstore/SessionFile.jsm:335:15\n_initWorker@resource:///modules/sessionstore/SessionFile.jsm:328:12\n_postToWorker@resource:///modules/sessionstore/SessionFile.jsm:352:11\nwrite@resource:///modules/sessionstore/SessionFile.jsm:392:19\nwrite@resource:///modules/sessionstore/SessionFile.jsm:64:12\n_writeState@resource:///modules/sessionstore/SessionSaver.jsm:357:12\n_saveState@resource:///modules/sessionstore/SessionSaver.jsm:295:12\n_saveStateAsync@resource:///modules/sessionstore/SessionSaver.jsm:341:5\nsaveStateAsyncWhenIdle@resource:///modules/sessionstore/SessionSaver.jsm:192:9\n"
1534372129145	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/tj/wzc7r76j2230lh5s1tlds2hh0000gn/T/anonymous3175238951375036863webdriver-profile/extensions/webdriver-staging
1534372129147	addons.xpi	DEBUG	Existing add-on activity-stream@mozilla.org in app-system-defaults
1534372129148	addons.xpi	DEBUG	Existing add-on aushelper@mozilla.org in app-system-defaults
1534372129149	addons.xpi	DEBUG	Existing add-on firefox@getpocket.com in app-system-defaults
1534372129150	addons.xpi	DEBUG	Existing add-on formautofill@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on onboarding@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat-reporter@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1534372129153	addons.xpi	DEBUG	getInstallState changed: false, state: {}
JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 2189: TypeError: addon is null

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at IndeedTest.main(IndeedTest.java:9)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
/features/webcompat-reporter@mozilla.org.xpi
1534372102181	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat-reporter@mozilla.org version 1.0.0
1534372102182	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1534372102183	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 2.0
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1534372102232	addons.manager	DEBUG	Provider finished startup: XPIProvider
1534372102232	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1534372102233	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1534372102233	addons.manager	DEBUG	Starting provider: GMPProvider
1534372102466	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1534372102467	addons.manager	DEBUG	Provider finished startup: GMPProvider
1534372102467	addons.manager	DEBUG	Starting provider: PluginProvider
1534372102467	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1534372102468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1534372102479	addons.manager	DEBUG	Completed startup sequence
1534372107763	addons.repository	DEBUG	No addons.json found.
2018-08-15 18:28:31.828 plugin-container[2424:105869] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6e3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:38.438 plugin-container[2425:105949] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9743, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:47.583 plugin-container[2426:106123] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6b43, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
console.error: "Could not write session state file " (new Error("_initWorker called too early! Please read the session file from disk first.", "resource:///modules/sessionstore/SessionFile.jsm", 335)) "_initWorker/<@resource:///modules/sessionstore/SessionFile.jsm:335:15\n_initWorker@resource:///modules/sessionstore/SessionFile.jsm:328:12\n_postToWorker@resource:///modules/sessionstore/SessionFile.jsm:352:11\nwrite@resource:///modules/sessionstore/SessionFile.jsm:392:19\nwrite@resource:///modules/sessionstore/SessionFile.jsm:64:12\n_writeState@resource:///modules/sessionstore/SessionSaver.jsm:357:12\n_saveState@resource:///modules/sessionstore/SessionSaver.jsm:295:12\n_saveStateAsync@resource:///modules/sessionstore/SessionSaver.jsm:341:5\nsaveStateAsyncWhenIdle@resource:///modules/sessionstore/SessionSaver.jsm:192:9\n"
1534372129145	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/tj/wzc7r76j2230lh5s1tlds2hh0000gn/T/anonymous3175238951375036863webdriver-profile/extensions/webdriver-staging
1534372129147	addons.xpi	DEBUG	Existing add-on activity-stream@mozilla.org in app-system-defaults
1534372129148	addons.xpi	DEBUG	Existing add-on aushelper@mozilla.org in app-system-defaults
1534372129149	addons.xpi	DEBUG	Existing add-on firefox@getpocket.com in app-system-defaults
1534372129150	addons.xpi	DEBUG	Existing add-on formautofill@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on onboarding@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat-reporter@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1534372129153	addons.xpi	DEBUG	getInstallState changed: false, state: {}
JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 2189: TypeError: addon is null

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Namrathas-MacBook-Pro.local', ip: '192.168.0.14', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at IndeedTest.main(IndeedTest.java:9)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
/features/webcompat-reporter@mozilla.org.xpi
1534372102181	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat-reporter@mozilla.org version 1.0.0
1534372102182	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1534372102183	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 2.0
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1534372102232	addons.manager	DEBUG	Provider finished startup: XPIProvider
1534372102232	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1534372102232	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1534372102233	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1534372102233	addons.manager	DEBUG	Starting provider: GMPProvider
1534372102466	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1534372102467	addons.manager	DEBUG	Provider finished startup: GMPProvider
1534372102467	addons.manager	DEBUG	Starting provider: PluginProvider
1534372102467	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1534372102468	addons.manager	DEBUG	Provider finished startup: PluginProvider
1534372102479	addons.manager	DEBUG	Completed startup sequence
1534372107763	addons.repository	DEBUG	No addons.json found.
2018-08-15 18:28:31.828 plugin-container[2424:105869] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6e3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:38.438 plugin-container[2425:105949] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9743, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-08-15 18:28:47.583 plugin-container[2426:106123] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6b43, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
console.error: "Could not write session state file " (new Error("_initWorker called too early! Please read the session file from disk first.", "resource:///modules/sessionstore/SessionFile.jsm", 335)) "_initWorker/<@resource:///modules/sessionstore/SessionFile.jsm:335:15\n_initWorker@resource:///modules/sessionstore/SessionFile.jsm:328:12\n_postToWorker@resource:///modules/sessionstore/SessionFile.jsm:352:11\nwrite@resource:///modules/sessionstore/SessionFile.jsm:392:19\nwrite@resource:///modules/sessionstore/SessionFile.jsm:64:12\n_writeState@resource:///modules/sessionstore/SessionSaver.jsm:357:12\n_saveState@resource:///modules/sessionstore/SessionSaver.jsm:295:12\n_saveStateAsync@resource:///modules/sessionstore/SessionSaver.jsm:341:5\nsaveStateAsyncWhenIdle@resource:///modules/sessionstore/SessionSaver.jsm:192:9\n"
1534372129145	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/tj/wzc7r76j2230lh5s1tlds2hh0000gn/T/anonymous3175238951375036863webdriver-profile/extensions/webdriver-staging
1534372129147	addons.xpi	DEBUG	Existing add-on activity-stream@mozilla.org in app-system-defaults
1534372129148	addons.xpi	DEBUG	Existing add-on aushelper@mozilla.org in app-system-defaults
1534372129149	addons.xpi	DEBUG	Existing add-on firefox@getpocket.com in app-system-defaults
1534372129150	addons.xpi	DEBUG	Existing add-on formautofill@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on onboarding@mozilla.org in app-system-defaults
1534372129151	addons.xpi	DEBUG	Existing add-on screenshots@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat-reporter@mozilla.org in app-system-defaults
1534372129152	addons.xpi	DEBUG	Existing add-on webcompat@mozilla.org in app-system-defaults
1534372129153	addons.xpi	DEBUG	getInstallState changed: false, state: {}
JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 2189: TypeError: addon is null

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

Can you suggest any fixes for the problem

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also, according to the log you have version 2.53.1 but not 3.14 as stated in the subject.
