### ISSUE TITLE
Let ActionChains.pause allow pausing split seconds not just multiples of seconds

### ISSUE THREAD

**Issue by mei-tech** [SeleniumHQ/selenium#6295]
## Meta -
OS:  
> Ubuntu 18.04

Selenium Version:  
> 3.14.0

Browser:  
> Firefox 61.0.1

## Expected Behavior -
`ActionChains.(driver).pause(1.2).perform()`
should accept floating numbers, not just integers, or directly ms as integer
All you do is in:
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/actions/interaction.py
Change
`output["duration"] = self.duration * 1000`
to, e.g.
`output["duration"] = int(self.duration * 1000)`

## Actual Behavior -
`ActionChains.(driver).pause(1.2).perform()`

leads to:
> Traceback (most recent call last):
>   File "/home/andreas/selenium-api/app/main.py", line 29, in <module>
>     ActionChains(driver).pause(1.2).perform()
>   File "/home/andreas/selenium-api/venv/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
>     self.w3c_actions.perform()
>   File "/home/andreas/selenium-api/venv/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
>     self.driver.execute(Command.W3C_ACTIONS, enc)
>   File "/home/andreas/selenium-api/venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
>     self.error_handler.check_response(response)
>   File "/home/andreas/selenium-api/venv/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: Parameter 'duration' was not a positive integer/errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace)
>selenium.common.exceptions.InvalidArgumentException: Message: Parameter 'duration' was not a positive integer
## Steps to reproduce -

all you have do is:
```
from selenium import webdriver
from selenium.webdriver import ActionChains

profile = webdriver.FirefoxProfile()
driver = webdriver.Firefox(firefox_profile=profile, executable_path="./bins/geckodriver-v0.21.0-linux64/geckodriver")
ActionChains(driver).pause(1.2).perform()
```

**Comment by Herst** [comment]
Superseded by #6300.

**Comment by lmtierney** [comment]
Fixed in https://github.com/SeleniumHQ/selenium/commit/3b5e720214236c3161035228db4702f0aeee11a8

@Herst thanks for the ping.
