### ISSUE TITLE
Missing grid console image for Safari Technology Preview

### ISSUE THREAD

**Issue by schmidtkp** [SeleniumHQ/selenium#6297]
## Meta -
OS:  macOS High Sierra 10.13.6
Selenium Version:  3.14.0
Browser:  Safari Technology Preview
Browser Version:  Release 63 (Safari 12.1, WebKit 13607.1.2.1)

## Expected Behavior -
The Selenium Grid Console should display an icon ![safari_preview](https://user-images.githubusercontent.com/3578664/44237206-4a9f4e80-a175-11e8-93d3-fb1954d8c374.png) for Safari Technology Preview browsers. 

## Actual Behavior -
Get an href="#" for each browser instance instead of an \<IMG\> tag.
## HTML Source -
`<a href="#" title="{node=http://localhost:5555, server:CONFIG_UUID=56655eb7-9631-4cd9-ae80-900b833c0467, seleniumProtocol=WebDriver, technologyPreview=true, browserVersion=63, browserName=Safari Technology Preview, maxInstances=4, platformName=MAC, platform=MAC}">Safari Technology Preview</a>`

## Grid Console Image -
<img width="638" alt="screen shot 2018-08-16 at 4 56 58 pm" src="https://user-images.githubusercontent.com/3578664/44237259-77536600-a175-11e8-98c7-780bba5186c3.png">

This coincides with commit: https://github.com/SeleniumHQ/selenium/commit/0efc0be17cd616bb61ab7af4266dbf4b7d5665b9

## Steps to reproduce -
Launch a Selenium grid node with Capabilities {browserName: Safari Technology Preview, browserVersion: 63, technologyPreview: true}

**Comment by diemol** [comment]
Just added the image for it, it will be available in the next release:

![image](https://user-images.githubusercontent.com/5992658/45207614-b5313f00-b288-11e8-8c2a-6d63f0bf40b4.png)
