### ISSUE TITLE
Switching between multiple drivers is not happening

### ISSUE THREAD

**Issue by kasthurk** [SeleniumHQ/selenium#630]
I need to switch between multiple drivers.

Here is the sample code with Slenium + Geb + Java +Groovy

  def config = browser.config
  def customDriver = config.getDriverFactory(config.getDriverConf()).driver 
  browser.driver=customDriver

Below code is working fine, its creating a fresh driver.

But its not shifting the focus to new driver.

Is there any way to shift focus between drivers.

**Comment by jimevans** [comment]
Define "focus." If you mean "brings the other browser window into the foreground so that it has the focus of the operating system," then you're right, the driver won't do that. And cannot be made to (reliably) do so on all operating systems.

**Comment by ddavison** [comment]
no response for 10 days. closing
