### ISSUE TITLE
GridException. Cannot extract a capabilities from the request. When create RemoteWebDriver by RemoteSessionSettings

### ISSUE THREAD

**Issue by gur2048** [SeleniumHQ/selenium#6301]
OS:  Windows 10
Selenium Version:  3.14 for .net
![2018-08-17 12_32_47-billing_tests d__git_billingservice test - _ui test_packages config - jetbr](https://user-images.githubusercontent.com/13627447/44259273-ba671500-a219-11e8-8210-d0f8d974c8de.jpg)
Geckodriver Version: 0.21.0
Browser:  Firefox
Browser Version:  61.0.2 (64-bit)

## Log - 
2018-08-17 12:05:20.853:WARN:osjs.HttpChannel:qtp1627821297-17: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"prefs":{"security.sandbox.content.level":5,"plugin.state.flash":2,"permissions.default.desktop-notification":2,"browser.defaultbrowser.notificationbar":"false","dom.webnotifications.enabled":"false","toolkit.cosmeticAnimations.enabled":"false","layout.animated-image-layers.enabled":"false","browser.suppress_first_window_animation":"false"}},"marionette":true,"enableVNC":true}}}
## Expected Behavior -
Created RemoteWebdriver instance.
## Actual Behavior -
GridException: Cannot extract a capabilities from the request
## Steps to reproduce -
1. Create FirefoxOptions like
`{
  "browserName": "firefox",
  "moz:firefoxOptions": {
    "prefs": {
      "security.sandbox.content.level": 5,
      "plugin.state.flash": 2,
      "permissions.default.desktop-notification": 2,
      "browser.defaultbrowser.notificationbar": "false",
      "dom.webnotifications.enabled": "false",
      "toolkit.cosmeticAnimations.enabled": "false",
      "layout.animated-image-layers.enabled": "false",
      "browser.suppress_first_window_animation": "false"
    }
  },
  "marionette": true,
  "enableVNC": true
}`

2. Create instanse RemoteSessionSettings, sending to constructor FirefoxOptions
![2018-08-17 12_30_42-billing_tests d__git_billingservice test - d__git_plarium wi webdriver support](https://user-images.githubusercontent.com/13627447/44265694-5c91f780-a230-11e8-9f36-53669a17eb6d.jpg)

3. Try create RemoteWebDriver, use instanse RemoteSessionSettings as desiredCapabilities arg.
![2018-08-17 12_31_28-billing_tests d__git_billingservice test - c__users_v gurov_ rider2018 1_confi](https://user-images.githubusercontent.com/13627447/44259193-8be93a00-a219-11e8-9abe-7f9469f95480.jpg)

**Comment by jimevans** [comment]
I’m going to go ahead and tag @barancev and @shs96c to check the grid code for `alwaysMatch` capability processing. At first glance, the new session command payload looks valid and spec-compliant to me (though that’s only at first glance and I could very well be wrong). In the meantime, @gur2048, what happens if you use the following instead:

     var settings = new RemoteSessionSettings(null, firefoxOptions):

**Comment by gur2048** [comment]
Hello @jimevans , thanks for reply.
If I using the following instead:
`var settings = new RemoteSessionSettings(null, firefoxOptions):`
I get the same result:
`2018-08-17 13:56:19.502:WARN:osjs.HttpChannel:qtp1627821297-19: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"firstMatch":[{"browserName":"firefox","moz:firefoxOptions":{"prefs":{"security.sandbox.content.level":5,"plugin.state.flash":2,"permissions.default.desktop-notification":2,"browser.defaultbrowser.notificationbar":"false","dom.webnotifications.enabled":"false","toolkit.cosmeticAnimations.enabled":"false","layout.animated-image-layers.enabled":"false","browser.suppress_first_window_animation":"false"}},"marionette":true,"enableVNC":true}]}}`

![2018-08-17 14_00_52-billing_tests d__git_billingservice test - d__git_plarium wi webdriver support](https://user-images.githubusercontent.com/13627447/44263030-0029da80-a226-11e8-805c-36e441a26bbe.jpg)

By the way, if I use: firefoxOptions.ToCapabilities(); for getting capabilities - RemoteWebDriver instance will be created successfully.

**Comment by jimevans** [comment]
@gur2048 Please provide your code for creating the `FirefoxOptions` object. Paste the code into a comment; please do not use a screenshot. I suspect the issue is that you're using capabilities that do not conform to the W3C standard (e.g. `"marionette"` and `"enableVNC"`). `RemoteSessionSettings` expects fully spec-compliant payloads; the `FirefoxOptions.ToCapabilities()` case strips out the non-conforming capability names.

**Comment by gur2048** [comment]
Thank @jimevans , you're right. The exception reason was in nonconforming capability names. You can close this issue.
