### ISSUE TITLE
Cannot compile/run Selenium with JDK 1.8 for version 3.14.0

### ISSUE THREAD

**Issue by glajchs** [SeleniumHQ/selenium#6306]
## Meta -
OS:  Linux Mint 18.1 XFCE
Selenium Version:  3.14.0
Browser:  N/A
Browser Version:  N/A

## Expected Behavior -
Selenium will compile in maven for a project using JDK 1.8

## Actual Behavior -
Maven throws errors saying that the selenium jars were compiled against "53.0" (JDK 1.9) and will require that JDK version to run.  This is done by way of the maven enforcer plugin, specifically "enforce-bytecode-version".
Since I see no references in the docs, changelog/etc about requiring JDK 1.9 support, I can only assume that this latest build had its target JDK version changed by mistake.
Here's the output you get:

`[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-bytecode-version) @ apptegic-selenium ---
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-opera-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-safari-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-api:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-ie-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-remote-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-edge-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[INFO] Restricted to JDK 1.8 yet org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0:compile contains module-info.class targeted to 53.0
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
Found Banned Dependency: org.seleniumhq.selenium:selenium-opera-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-safari-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-api:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-ie-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-remote-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-edge-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0
Found Banned Dependency: org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0
`

## Steps to reproduce -
1. Download maven
2. Include the "selenium-server" and "selenium-chrome-driver" modules in a pom.xml file.
3. Setup the maven enforcer plugin.  Here's a snippet showing how to enable this.  Alternatively you can just open the jar files and check the bytecode versions.
`            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-versions</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>3.0</version>
                                </requireMavenVersion>
                                <requireJavaVersion>
                                    <version>[1.8,1.9)</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>enforce-bytecode-version</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <enforceBytecodeVersion>
                                    <maxJdkVersion>${java.version}</maxJdkVersion>
                                </enforceBytecodeVersion>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>extra-enforcer-rules</artifactId>
                        <version>1.0-beta-4</version>
                    </dependency>
                </dependencies>
            </plugin>
`

**Comment by barancev** [comment]
Yes, module-info.class is targeted to Java 9, because it contains module information required by Java 9 and never should be used in Java 8. These classes were added intentionally to improve Java 9 support.

I bet it's enforcer plugin issue that it does not handle properly these special classes.

@shs96c Your opinion?

**Comment by qqilihq** [comment]
Any news? I can effectively **not** build when updating to 3.14.0 in my Java 8 project. Though probably (???) unintended, this is a major breaking change.

In case you plan to drop Java 8 support, a short statement would be appreciated.

**Comment by barancev** [comment]
@qqilihq What issue do you have exactly? Selenium 3.14 contains module info that can be used by Java 9, but it works perfectly with Java 8 because it just ignores module info.

**Comment by qqilihq** [comment]
@barancev thx, I'll provide further details about mentioned issue during the next days.

**Comment by barancev** [comment]
Closing the issue as there is no evidence of any Java 8 incompatibility.
