### ISSUE TITLE
Can t even open selenium

### ISSUE THREAD

**Issue by tchaton** [SeleniumHQ/selenium#6310]
Windows 10 64 bits - lastest Firefox

from selenium import webdriver

browser = webdriver.Firefox(executable_path="geckodriver.exe")

browser.get("http://google.com") #this will load the the google homepage

Does work at all .

**Comment by lmtierney** [comment]
The issue template is there for a reason. You have given us nothing to work with. We test that this works with every commit. If it "doesn't work at all" then there should be an error

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
