### ISSUE TITLE
[Grid] Clicking "view config" on Console jumps to top of page

### ISSUE THREAD

**Issue by dylanlive** [SeleniumHQ/selenium#6311]
## Meta -
OS:  
macOS 10.12.6
Selenium Version:  
3.13.0
Browser:  
Chrome

Browser Version:  
latest

## Expected Behavior -
Clicking "view config" on the Grid Console should not reload the page and jump to the top

## Actual Behavior -
Clicking "view config" on the Grid Console reloads the page and jumps to the top

## Steps to reproduce -
1) Launch hub
2) Connect many nodes to the hub
3) Click "view config" - you'll be jumped to the top

**Comment by dylanlive** [comment]
@shs96c @barancev I'd like to open a PR for this; however, I know se4 will redesign the console.

I'm assuming that's still a-ways away, so would you accept a PR for this minor fix?

It looks like it'll be more work than my previous PR #5546 as the logic displays the config based on the request parameters- would we want to keep support for Non-Javascript enabled browsers?

I'm assuming yes and can work to support both (but it'll be a bit more work).

**Comment by barancev** [comment]
I'm not sure we should care about non-JS enabled browsers. Why should we? What's the target audience?

**Comment by dylanlive** [comment]
@barancev Awesome, that would make the PR easier to just display the Config using JavaScript.

I’d like to open a PR so that clicking View Config won’t jump you back to the very top of the page (annoying with many nodes expanding the page length). 

I’m hoping to get acknowledgment it’ll be accepted before putting in the work.

**Comment by diemol** [comment]
Hi @dylanlive,

You are right, it is an annoying issue, if you send the PR, I'd be happy to review it and merge it.

**Comment by dylanlive** [comment]
@diemol Thanks! Mostly finished, just polishing. Hopefully should have some time this weekend to wrap it up

**Comment by dylanlive** [comment]
Opened https://github.com/SeleniumHQ/selenium/pull/6386 to fix

**Comment by diemol** [comment]
PR #6386 merged via https://github.com/SeleniumHQ/selenium/commit/4e6f0117d872f7b132143903be7cb2b744739161, thanks @dylanlive!
