### ISSUE TITLE
servlets parsing logic is broken

### ISSUE THREAD

**Issue by shankarkc** [SeleniumHQ/selenium#6312]
## Meta -
OS:  
All
Selenium Version:  
3.14.0
Browser:  
Any

Browser Version:  
NA
## Expected Behavior -
 when user specify  custom servlets selenium grid should be able to instantiate it
## Actual Behavior -
Parsing logic is broken. As a result servlet names contain typos
## Steps to reproduce -
Use below json file as input
```
{
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets": [
     "io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet",
     "com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet"
   ],
  "capabilityMatcher": "io.sterodium.extensions.capability.CustomCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 5000,
  "browserTimeout": 5000,
  "maxSession": 60
}
```
Launch hub as below 
```
java -cp c:\ai\test-grid\hub\SeleniumGridExtras-2.0.4-SNAPSHOT-jar-with-dependencies.jar;.\extension-proxy-1.0.jar;\tmp\webdriver\3.14.0.jar  org.openqa.grid.selenium.GridLauncherV3 -role hub -log log\\hub_4444.log -hubConfig hub_4444.json
```
In hub log you will see error that grid cannot create instance of the classses as below : -
```
13:52:29.756 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
13:52:29.759 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
13:52:29.790 WARN [ExtraServletUtil.createServlet] - The specified class : [io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet cannot be instantiated [io/sterodium/extensions/hub/proxy/HubRequestsProxyingServlet
13:52:29.791 WARN [ExtraServletUtil.createServlet] - The specified class :  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet] cannot be instantiated  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet]
13:52:29.791 WARN [ExtraServletUtil.createServlet] - The specified class : [io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet cannot be instantiated [io/sterodium/extensions/hub/proxy/HubRequestsProxyingServlet
13:52:29.793 WARN [ExtraServletUtil.createServlet] - The specified class :  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet] cannot be instantiated  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet]
13:52:30.921 INFO [Hub.start] - Selenium Grid hub is up and running
```
If you notice the warning classname contains a typo. 13:52:29.790 WARN [ExtraServletUtil.createServlet] - The specified class : [io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet cannot be instantiated [io/sterodium/extensions/hub/proxy/HubRequestsProxyingServlet
13:52:29.791 WARN [ExtraServletUtil.createServlet] - The specified class :  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet] cannot be instantiated  com.ariba.es.ai.hub.proxy.servlets.SeleniumApiProxyServlet]
Notice that json array **delimiter [ and ] appended** to the elements. As a result class instantiation fails.

**Comment by shankarkc** [comment]
@barancev can you please take look at this? Our servlets are not working with new version of grid bcz of this issue.

**Comment by barancev** [comment]
I hope it's fixed in master, by commit 45fce8c2b80d94bffdca25bc2746209004bc06f9, but I have to check. If you can build selenium from the source and test your config it would be excellent.

**Comment by barancev** [comment]
Actually, two commits, df2df0de9cf48e1867124b938673107f3d94610f and 45fce8c2b80d94bffdca25bc2746209004bc06f9

**Comment by dylanlive** [comment]
Note: I'm not seeing this when supplying a singular servlet.

Example, from nodeConfig:
```
"servlets":  ["com.cbg.servlets.MyCustomServlet"],
```

So perhaps this is only with multiple servlets, per your repo steps.

**Comment by barancev** [comment]
Yes, I've verified that both single-item servlet list and multiple-item servlet list work well in master. Hope we'll ship another version soon.

**Comment by shankarkc** [comment]
Thanks a lot @barancev and @dylanlive👍
