### ISSUE TITLE
InternetExplorerDriver doesn't work for Windows 10

### ISSUE THREAD

**Issue by Shukurdin-Aydarov** [SeleniumHQ/selenium#6313]
## Meta -
OS:  
Windows 10
Browser:  
Internet Explorer 11

I have the following code: 
```csharp 
       [TestMethod]
        public void TestMethod1()
        {
            var options = new InternetExplorerOptions
            {
                ForceCreateProcessApi = true
            };

            var driver = new InternetExplorerDriver(options);
            driver.Navigate().GoToUrl("http://google.ru");
        }
```
And this code throws an exception:
WebDriverTest.UnitTest1.TestMethod1 threw exception: 
System.InvalidOperationException: Unexpected error launching Internet Explorer. Unable to use CreateProcess() API. To use CreateProcess() with Internet Explorer 8 or higher, the value of registry setting in HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\TabProcGrowth must be '0'. (SessionNotCreated).

I created an entry in the registry, as in the documentation (https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver), but it does not help me.

**Comment by Proryanator** [comment]
Did you make sure your followed these setup instructions?

https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver#required-configuration

**Comment by Shukurdin-Aydarov** [comment]
@Proryanator, yes, I did.

**Comment by diemol** [comment]
Is this issue still valid? Seems it went stale.

**Comment by diemol** [comment]
I'll close this since the issue went stale and no more comments from the community were received.
