### ISSUE TITLE
[Feature Request] Add keep_alive flag to WebDriver's constructor

### ISSUE THREAD

**Issue by rkanine** [SeleniumHQ/selenium#6316]
Browser in which feature is requested : Firefox
Currently if we want to set keep_alive to false, we need to implement our own class along the lines of WebDriver class ( in [file](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py) ) and set keep_alive in RemoteWebDriver's constructor call.
For ease of configuration, this should be available as a constructor parameter in WebDriver itself.

Thanks,
Kislaya

**Comment by lmtierney** [comment]
This has been added and will be in the next release

**Comment by rkanine** [comment]
Thanks!! @lmtierney

**Comment by rkanine** [comment]
@lmtierney Can you please elaborate which release will this be a part of? 3.15.0? 3.14.1?

**Comment by lmtierney** [comment]
@rkanine whatever release is next. I'm not sure if we'll release a `3.14.1` or not
