### ISSUE TITLE
dsiable  spdy

### ISSUE THREAD

**Issue by sali123** [SeleniumHQ/selenium#6318]
I am trying to disable spdy obn chrome webdriver using python. it is not giving me error and it does not work as If the command is not there

      options.add_argument("--use-spdy=off")
      options.add_argument("start-maximized")
      options.binary_location = params["root_dir"] + r'\browsers\Chrome\Application\Chrome.exe'
       driver = webdriver.Chrome(executable_path=executable_path, chrome_options=options)

please note all other options are taking effect except for spdy.

**Comment by lmtierney** [comment]
We pass along args as given. If the arg you're adding doesn't do what you expect in Chrome then that's Chrome's issue. If you have an error from the python library, please raise a new issue with all the information requested from the New Issue template.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
