### ISSUE TITLE
Request: timeline or roadmap for future releases

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SeleniumHQ/selenium#6322]
Is there consensus on when new releases are meant to be shipped? `4.0.0-alpha1` is 7 months old and there are some juicy features that have gone in since then.

Would be great to have some documentation here on what we can expect.

**Comment by peppertech** [comment]
Any update on on this topic?  It's been quite some time and any guidance on a rough roadmap would be really helpful.  Thanks!

**Comment by AutomatedTester** [comment]
Unfortunately we can't offer exact times when doing releases. We are releasing this, the last one was a month ago. A lot of the work here is being done as a whole for the selenium project.

**Comment by peppertech** [comment]
Thanks David,

We're excited to see the new release and use it.  We'll wait patiently.
We're not allow to use libraries that are in an Alpha status at our
company, and thus the question.
Thanks again,

--jb

**Comment by AutomatedTester** [comment]
We’re working hard and ASAP is the best answer I can give. We’re working off https://docs.google.com/document/d/1f4dbqJrZqI_IZRH50Xxr-t7WPS8utuK2JVmeqJCGTnc but may change it
