### ISSUE TITLE
How Full Page Capture use javascript in Chrome?

### ISSUE THREAD

**Issue by pyeongoh** [SeleniumHQ/selenium#6325]
## Meta -
OS:  OSX

Selenium Version:  "selenium-webdriver": "^4.0.0-alpha.1"

Browser:  Chrome
<!-- Internet Explorer?  Firefox?

I wanna capture a page has scrollbar with many contents in on single screenshot.
If i knew right, PhantomJS is deprecated. so any solutions to achive above purpose?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by JackWangAndRose** [comment]
I have the same question . Html2canvas.js may make it.
