### ISSUE TITLE
incognito on firefox webdriver

### ISSUE THREAD

**Issue by sali123** [SeleniumHQ/selenium#6328]
, I am trying to turn on Incognito on firefox. I am using         options = Options()     options.add_argument('-private'). the browser  is opened in incognito mode but after loading the website , it is become normal again.

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by lmtierney** [comment]
Please log any Firefox & Geckodriver issues with Mozilla: https://github.com/mozilla/geckodriver
