### ISSUE TITLE
geckowebdriver stopped running

### ISSUE THREAD

**Issue by sali123** [SeleniumHQ/selenium#6329]
I developed my application in two steps

1- the first step I load a website into the browser, register all the session storage, local storage, take screen shot, etc... this step works fine.
2. the user has the option to click on a button in the browser. then he click 'Finish' button in my application.
3. The second step started here where I call a function to my driver from the previous session, then I call again the function to log all the session storage, local storage, take screen shot, etc...

in the middle of execution of step three, the process gecowedriver.exe is terminated, although some of my function managed to deal with it. and I receive the below error
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\python3.7.0\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\python3.7.0\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\python3.7.0\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\python3.7.0\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\python3.7.0\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\python3.7.0\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by cgoldberg** [comment]
please provide the failing code.  A narrative description isn't helpful.

**Comment by sali123** [comment]
link_elements = webdriver.find_elements_by_tag_name('a')
    link_urls = []
    for element in link_elements:
            link = element.get_attribute("href")
            if link not in link_urls:
                link_urls.append(link)

after a few iteration  to  extract href, the gekowebdriver process is stopped,  and I start to receive this error
 ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also we need to know version of selenium client binding, geckodriver and browser.

**Comment by sali123** [comment]
below is a code I developed to duplicate the error.

Meta -

OS:Windows 7

Selenium Version:3.11.0
geokodriver: v0.21.0

Browser:firefox

Browser Version:60.1.0esr (64-bit)
Expected Behavior -  extract all links from all url loaded by user into the browser regardless how many time he changed it.
Actual Behavior - ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
Steps to reproduce -
1- run the code in python
2- click "Open Browser"
3-Click "Save Content" button
4-Click "Save Content" button (this is second Time)
5-Click "Save Content" button (this is third Time)

----------------------------------------------------------------------------


from selenium import webdriver
from tkinter import *
import tkinter as tk

#------------------------------
# create_driver_session
#-----------------------------
def create_driver_session(session_id, executor_url):
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver

    # Save the original function, so we can revert our patch
    org_command_execute = RemoteWebDriver.execute

    def new_command_execute(self, command, params=None):
        if command == "newSession":
            # Mock the response
            return {'success': 0, 'value': None, 'sessionId': session_id}
        else:
            return org_command_execute(self, command, params)

    # Patch the function before creating the driver object
    RemoteWebDriver.execute = new_command_execute
    new_driver = webdriver.Remote(command_executor=executor_url, desired_capabilities={'acceptInsecureCerts': True, 'browserName': 'firefox', 'marionette': True})
    new_driver.session_id = session_id

    # Replace the patched function with original function
    RemoteWebDriver.execute = org_command_execute

    return new_driver



def dump_all_data():
    driver2 = create_driver_session(params["session_id"], params["executor_url"])
    extract_links(driver2)
  

def extract_links(webdriver):
    link_elements = webdriver.find_elements_by_tag_name('a')
    link_urls = []
    for element in link_elements:
            link = element.get_attribute("href")
            if link not in link_urls:
                link_urls.append(link)
                

def openbrowser():
    driver =webdriver.Firefox()
    driver.get("https://cnn.com")
    #save session variables
    params["executor_url"] = driver.command_executor._url
    params["session_id"] = driver.session_id

    dump_all_data()


window = Tk()
window.geometry("600x400")
params = {}

b2_text = tk.StringVar()
b2=Button(window,textvariable=b2_text,width="20", command=dump_all_data)
b2.grid(row=3, column=1)
b2_text.set("Save Content")


b1_text = tk.StringVar()
b1=Button(window,textvariable=b1_text,width="20", command=openbrowser)
b1.grid(row=1, column=1)
b1_text.set("Open Browser")

**Comment by barancev** [comment]
Can you please retest with the latest selenium version (that is 3.14 at the moment)?

(I'm not claiming it should work in 3.14, just want to make sure it's an actual issue)

**Comment by cgoldberg** [comment]
* the example you posted doesn't run because you didn't start the event loop (`mainloop()`)
* if you *do* start the event loop, you shouldn't make blocking calls (like calling webdriver methods) inside a button command or you block the mainloop from processing events. (notice your GUI freezes)

**Comment by sali123** [comment]
I updated the example based on cgoldberg comment. I also upgraded selenium for version 3.14.

The error now does not appear after the sevenths time after clicking the "Save Content" button.

**Comment by lmtierney** [comment]
Keep in mind this is being used outside of the suggested behavior. Keeping a session alive and then re-using it by sessionid and capabilities is YMMV and use at your own risk. That being said, you probably just need to set `keep_alive` to True in the RemoteWebDriver ctor due to the changes in geckodriver `0.21`

**Comment by sali123** [comment]
ok, thanks.
