### ISSUE TITLE
selenium server without SSL or TLS 1.0 ?

### ISSUE THREAD

**Issue by RyanChang0307** [SeleniumHQ/selenium#6338]
Dears,

I did know that selenium server communicated with Firefox using SSL,

Is there any way change the protocol using TLS 1.1 or higher?

Thanks!!!

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) or [selenium-developers](https://groups.google.com/forum/#!forum/selenium-developers) groups.
