### ISSUE TITLE
selenium 2.46.0 - java.lang.NoClassDefFoundError: org/apache/http/config/RegistryBuilder

### ISSUE THREAD

**Issue by matteoturra** [SeleniumHQ/selenium#634]
Launching integration test phase with maven I get this error:
java.lang.NoClassDefFoundError: org/apache/http/config/RegistryBuilder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at org.openqa.selenium.remote.internal.HttpClientFactory.getClientConnectionManager(HttpClientFactory.java:68)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:56)
	at org.openqa.selenium.remote.internal.HttpClientFactory.<init>(HttpClientFactory.java:60)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.getDefaultHttpClientFactory(ApacheHttpClient.java:251)
	at org.openqa.selenium.remote.internal.ApacheHttpClient$Factory.<init>(ApacheHttpClient.java:228)
	at org.openqa.selenium.remote.HttpCommandExecutor.getDefaultClientFactory(HttpCommandExecutor.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:63)
	at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:58)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:95)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:275)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)

My pom.xml has this dependencies (version 2.46.0)
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<scope>test</scope>
		</dependency>

To avoid the error I added this dependency too:
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpcore</artifactId>
  <version>4.4.1</version>

**Comment by barancev** [comment]
Please show the complete pom.xml file that causes the issue, or execute a command
mvn dependency:tree
and attach the output.

**Comment by matteoturra** [comment]
This is my dep-tree
com.mycomp.myproj:didanet:war:01.06.01-SNAPSHOT
+- com.mycomp.myproj.core:didanet-core-base:jar:01.06.01-SNAPSHOT:compile
|  +- com.fasterxml.jackson.core:jackson-databind:jar:2.1.4:compile
|  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.1.4:compile
|  \- com.fasterxml.jackson.core:jackson-core:jar:2.1.4:compile
+- com.mycomp.myproj.core:didanet-core-dao:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.core:didanet-core-jdbc:jar:01.06.01-SNAPSHOT:compile
|  \- com.mycomp.myproj.core:didanet-core-jdbc:test-jar:tests:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.core:didanet-core-document:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.core:didanet-core-file:jar:01.06.01-SNAPSHOT:compile
|  |  \- net.sf.supercsv:super-csv:jar:2.1.0:compile
|  +- com.mycomp.mylibrary.docx4j:Docx4j:jar:1.0.0-SNAPSHOT:compile
|  |  \- org.docx4j:docx4j:jar:3.2.1:compile
|  |     +- org.plutext:jaxb-svg11:jar:1.0.2:compile
|  |     +- org.plutext:jaxb-xslfo:jar:1.0.1:compile
|  |     +- org.plutext:jaxb-xmldsig-core:jar:1.0.0:compile
|  |     +- net.engio:mbassador:jar:1.1.10:compile
|  |     +- org.slf4j:jcl-over-slf4j:jar:1.7.5:compile
|  |     +- org.slf4j:slf4j-log4j12:jar:1.7.5:compile
|  |     +- org.apache.xmlgraphics:xmlgraphics-commons:jar:1.5:compile
|  |     +- org.apache.xmlgraphics:fop:jar:1.1:compile
|  |     |  +- org.apache.xmlgraphics:batik-svg-dom:jar:1.7:compile
|  |     |  |  +- org.apache.xmlgraphics:batik-anim:jar:1.7:compile
|  |     |  |  +- org.apache.xmlgraphics:batik-css:jar:1.7:compile
|  |     |  |  +- org.apache.xmlgraphics:batik-dom:jar:1.7:compile
|  |     |  |  +- org.apache.xmlgraphics:batik-parser:jar:1.7:compile
|  |     |  |  \- org.apache.xmlgraphics:batik-util:jar:1.7:compile
|  |     |  +- org.apache.xmlgraphics:batik-bridge:jar:1.7:compile
|  |     |  |  +- org.apache.xmlgraphics:batik-script:jar:1.7:compile
|  |     |  |  \- org.apache.xmlgraphics:batik-xml:jar:1.7:compile
|  |     |  +- org.apache.xmlgraphics:batik-awt-util:jar:1.7:compile
|  |     |  +- org.apache.xmlgraphics:batik-gvt:jar:1.7:compile
|  |     |  +- org.apache.xmlgraphics:batik-transcoder:jar:1.7:compile
|  |     |  |  \- org.apache.xmlgraphics:batik-svggen:jar:1.7:compile
|  |     |  +- org.apache.xmlgraphics:batik-extension:jar:1.7:compile
|  |     |  \- org.apache.xmlgraphics:batik-ext:jar:1.7:compile
|  |     +- org.apache.avalon.framework:avalon-framework-api:jar:4.3.1:compile
|  |     +- org.apache.avalon.framework:avalon-framework-impl:jar:4.3.1:compile
|  |     +- xalan:xalan:jar:2.7.1:compile
|  |     |  \- xalan:serializer:jar:2.7.1:compile
|  |     +- net.arnx:wmf2svg:jar:0.9.0:compile
|  |     +- org.apache.poi:poi-scratchpad:jar:3.8:compile
|  |     +- org.antlr:antlr-runtime:jar:3.3:compile
|  |     +- org.antlr:stringtemplate:jar:3.2.1:compile
|  |     \- com.google.guava:guava:jar:18.0:compile
|  +- net.sf.jasperreports:jasperreports:jar:6.0.0:compile
|  |  +- commons-beanutils:commons-beanutils:jar:1.9.0:compile
|  |  +- commons-digester:commons-digester:jar:2.1:compile
|  |  +- com.itextpdf:itextpdf:jar:5.5.0:compile
|  |  +- com.itextpdf:itext-pdfa:jar:5.5.0:compile
|  |  +- jfree:jcommon:jar:1.0.15:compile
|  |  +- jfree:jfreechart:jar:1.0.12:compile
|  |  +- xml-apis:xml-apis:jar:1.3.02:compile
|  |  +- org.eclipse.jdt.core.compiler:ecj:jar:4.3.1:compile
|  |  +- org.codehaus.castor:castor:jar:1.2:compile
|  |  +- org.apache.lucene:lucene-core:jar:4.5.1:compile
|  |  +- org.apache.lucene:lucene-analyzers-common:jar:4.5.1:compile
|  |  +- org.apache.lucene:lucene-queryparser:jar:4.5.1:compile
|  |  |  +- org.apache.lucene:lucene-queries:jar:4.5.1:compile
|  |  |  \- org.apache.lucene:lucene-sandbox:jar:4.5.1:compile
|  |  |     \- jakarta-regexp:jakarta-regexp:jar:1.4:compile
|  |  \- org.olap4j:olap4j:jar:0.9.7.309-JS-3:compile
|  \- net.sf.jasperreports:jasperreports-fonts:jar:6.0.0:compile
+- com.mycomp.myproj.core:didanet-core-test:jar:01.06.01-SNAPSHOT:test (scope not updated to compile)
|  \- org.seleniumhq.selenium:selenium-java:jar:2.46.0:test (version managed from 2.45.0)
|     +- org.seleniumhq.selenium:selenium-chrome-driver:jar:2.46.0:test
|     +- org.seleniumhq.selenium:selenium-htmlunit-driver:jar:2.46.0:test
|     |  \- net.sourceforge.htmlunit:htmlunit:jar:2.17:test
|     |     +- org.apache.commons:commons-lang3:jar:3.4:test
|     |     +- org.apache.httpcomponents:httpmime:jar:4.4.1:test
|     |     +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:test
|     |     +- xerces:xercesImpl:jar:2.11.0:test
|     |     +- net.sourceforge.nekohtml:nekohtml:jar:1.9.22:test
|     |     +- net.sourceforge.cssparser:cssparser:jar:0.9.16:test
|     |     |  \- org.w3c.css:sac:jar:1.3:test
|     |     \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.11.v20150529:test
|     |        \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.11.v20150529:test
|     |           \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.11.v20150529:test
|     +- org.seleniumhq.selenium:selenium-ie-driver:jar:2.46.0:test
|     +- org.seleniumhq.selenium:selenium-safari-driver:jar:2.46.0:test
|     +- org.webbitserver:webbit:jar:0.4.14:test
|     |  \- io.netty:netty:jar:3.5.2.Final:test
|     \- org.seleniumhq.selenium:selenium-leg-rc:jar:2.46.0:test
+- com.mycomp.myproj.document:didanet-document:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.document:didanet-document-data-dao:jar:01.06.01-SNAPSHOT:compile
|  \- com.mycomp.myproj.core:didanet-core-dao:test-jar:tests:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.document:didanet-document-docx:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.document:didanet-document-jr:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.document:didanet-document-pdf:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.integration:didanet-integration-aie:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.integration:didanet-integration-kim:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.core:didanet-core-proxy:jar:01.06.01-SNAPSHOT:compile
|  |  +- org.apache.axis:axis:jar:1.4:compile
|  |  +- commons-discovery:commons-discovery:jar:0.2:compile
|  |  +- javax.xml:jaxrpc-api:jar:1.1:compile
|  |  \- javax.xml.soap:saaj-api:jar:1.3:compile
|  \- com.mycomp.myproj.integration:didanet-integration-kim-stub:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.integration:didanet-integration-invalsi:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.integration:didanet-integration-sidi:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.integration:didanet-integration-sidi-stub:jar:01.06.01-SNAPSHOT:compile
|  \- org.apache.httpcomponents:httpclient:jar:4.3.5:compile
+- com.mycomp.myproj.platform:didanet-platform-base:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-data-dao:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-data-etl:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-login:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-login:jar:tests:01.06.01-SNAPSHOT:test
+- com.mycomp.myproj.platform:didanet-platform-desktop:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-desktop:jar:tests:01.06.01-SNAPSHOT:test
+- com.mycomp.myproj.platform:didanet-platform-job:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.integration:didanet-integration-meal:jar:01.06.01-SNAPSHOT:compile
|  |  \- com.mycomp.myproj.integration.meal:didanet-integration-meal-stub:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.myproj.integration:didanet-integration-sga:jar:01.06.01-SNAPSHOT:compile
|  \- com.mycomp.kjobscheduler:KJobSchedTomcat:jar:0.0.4-SNAPSHOT:compile
|     +- com.mycomp.kjobscheduler:KJobSchedCore:jar:0.0.4-SNAPSHOT:compile
|     \- javax.transaction:jta:jar:1.0.1B:compile
+- com.mycomp.myproj.platform:didanet-platform-gateway:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.gateway:KGatewayCore:jar:1.0.0-SNAPSHOT:compile
|  |  +- com.mycomp.esse4:Winsession:jar:4.03.00-SNAPSHOT:compile
|  |  +- com.mycomp.esse4:Interfaces:jar:4.03.00-SNAPSHOT:compile
|  |  +- com.mycomp.esse4:SessionProxy:jar:4.03.00-SNAPSHOT:compile
|  |  |  \- com.mycomp.esse4:StubForEsse4:jar:4.03.00-SNAPSHOT:compile
|  |  +- com.mycomp.esse4:FRKCore:jar:4.03.00-SNAPSHOT:compile
|  |  +- com.mycomp.esse4:ESSE4FRK:jar:4.03.00-SNAPSHOT:compile
|  |  +- axis:axis:jar:1.4:compile
|  |  |  +- org.apache.axis:axis-jaxrpc:jar:1.4:compile
|  |  |  +- org.apache.axis:axis-saaj:jar:1.4:compile
|  |  |  \- axis:axis-wsdl4j:jar:1.5.1:runtime
|  |  \- com.mycomp.gateway:KGatewayInterface:jar:1.0.0-SNAPSHOT:compile
|  \- com.mycomp.gateway:KGatewayTitulus:jar:1.0.0-SNAPSHOT:compile
|     \- javax.mail:mail:jar:1.4.2:runtime
+- com.mycomp.myproj.platform:didanet-platform-register:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-register:jar:tests:01.06.01-SNAPSHOT:test
+- com.mycomp.myproj.platform:didanet-platform-session:jar:01.06.01-SNAPSHOT:compile
|  +- com.mycomp.esse4:Base:jar:4.03.00-SNAPSHOT:compile
|  |  \- com.mycomp.esse4:StubEsse4:jar:4.03.00-SNAPSHOT:compile
|  \- com.mycomp.esse4:FRK:jar:4.03.00-SNAPSHOT:compile
|     \- com.mycomp.wu.se:security-engine-interfaces:jar:00.00.02-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-teaching:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.platform:didanet-platform-user:jar:01.06.01-SNAPSHOT:compile
+- com.mycomp.myproj.prototype:didanet-prototype-service-dao:jar:01.06.01-SNAPSHOT:compile
+- commons-fileupload:commons-fileupload:jar:1.2.2:compile
+- commons-io:commons-io:jar:1.4:compile
+- commons-logging:commons-logging:jar:1.1.1:compile
+- com.servlets:cos:jar:05Nov2002:compile
+- org.directwebremoting:dwr:jar:2.0.5:compile
+- org.mnode.ical4j:ical4j:jar:1.0.5.2:compile
|  +- commons-codec:commons-codec:jar:1.8:compile
|  +- commons-lang:commons-lang:jar:2.6:compile
|  \- backport-util-concurrent:backport-util-concurrent:jar:3.1:compile
+- com.lowagie:itext:jar:2.1.4:compile
|  +- bouncycastle:bcmail-jdk14:jar:138:compile
|  \- bouncycastle:bcprov-jdk14:jar:138:compile
+- com.lowagie:itext-rups:jar:2.1.4:compile
+- com.lowagie:itext-rtf:jar:2.1.4:compile
+- net.sourceforge.javacsv:javacsv:jar:2.0:compile
+- com.sun.mail:javax.mail:jar:1.4.7:compile
|  \- javax.activation:activation:jar:1.1:compile
+- javax.servlet.jsp.jstl:javax.servlet.jsp.jstl-api:jar:1.2.1:compile
+- javax.servlet:jsp-api:jar:2.0:provided
+- junit:junit:jar:4.11:test
|  \- org.hamcrest:hamcrest-core:jar:1.3:test
+- log4j:log4j:jar:1.2.14:provided (scope not updated to compile)
+- org.apache.cxf:cxf-bundle:jar:2.7.15:compile
|  +- org.apache.velocity:velocity:jar:1.7:compile
|  +- commons-collections:commons-collections:jar:3.2.1:compile
|  +- wsdl4j:wsdl4j:jar:1.6.2:compile
|  +- com.sun.xml.bind:jaxb-xjc:jar:2.1.13:compile
|  +- com.sun.xml.bind:jaxb-impl:jar:2.1.13:compile
|  +- org.apache.ws.xmlschema:xmlschema-core:jar:2.1.0:compile
|  +- antlr:antlr:jar:2.7.7:compile
|  +- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
|  +- xml-resolver:xml-resolver:jar:1.2:compile
|  +- org.apache.geronimo.specs:geronimo-jaxws_2.2_spec:jar:1.1:compile
|  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
|  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
|  +- org.apache.geronimo.specs:geronimo-javamail_1.4_spec:jar:1.7.1:compile
|  +- org.eclipse.jetty:jetty-server:jar:8.1.15.v20140411:compile
|  +- org.eclipse.jetty:jetty-continuation:jar:8.1.15.v20140411:compile
|  +- org.eclipse.jetty:jetty-http:jar:8.1.15.v20140411:compile
|  +- org.eclipse.jetty:jetty-io:jar:8.1.15.v20140411:compile
|  +- org.eclipse.jetty:jetty-util:jar:8.1.15.v20140411:compile
|  +- org.eclipse.jetty:jetty-security:jar:8.1.15.v20140411:compile
|  +- org.slf4j:slf4j-api:jar:1.7.9:compile
|  +- org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1:compile
|  +- org.springframework:spring-jms:jar:3.0.7.RELEASE:compile
|  +- aopalliance:aopalliance:jar:1.0:compile
|  +- org.springframework:spring-aop:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-beans:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-core:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-context:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-expression:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-asm:jar:3.0.7.RELEASE:compile
|  +- org.springframework:spring-tx:jar:3.0.7.RELEASE:compile
|  +- org.apache.httpcomponents:httpcore-nio:jar:4.2.4:compile
|  +- org.apache.httpcomponents:httpcore:jar:4.2.4:compile
|  +- org.apache.httpcomponents:httpasyncclient:jar:4.0-beta3:compile
|  +- org.apache.mina:mina-core:jar:2.0.7:compile
|  +- asm:asm:jar:3.3.1:compile
|  +- rhino:js:jar:1.7R2:compile
|  +- javax.ws.rs:javax.ws.rs-api:jar:2.0-m10:compile
|  +- net.oauth.core:oauth-provider:jar:20100527:compile
|  +- net.oauth.core:oauth:jar:20100527:compile
|  +- net.sf.ehcache:ehcache-core:jar:2.5.1:compile
|  +- org.apache.ws.security:wss4j:jar:1.6.18:compile
|  +- org.apache.santuario:xmlsec:jar:1.5.8:compile
|  +- org.opensaml:opensaml:jar:2.6.1:compile
|  +- org.opensaml:openws:jar:1.5.1:compile
|  +- org.opensaml:xmltooling:jar:1.4.1:compile
|  +- joda-time:joda-time:jar:2.2:compile
|  \- org.apache.neethi:neethi:jar:3.0.3:compile
+- mysql:mysql-connector-java:jar:5.1.25:compile
+- ojdbc:ojdbc:jar:6:compile
+- org.jacoco:org.jacoco.agent:jar:runtime:0.6.4.201312101107:test
+- org.apache.poi:poi:jar:3.9:compile
+- org.seleniumhq.selenium:selenium-firefox-driver:jar:2.46.0:test
|  +- org.seleniumhq.selenium:selenium-remote-driver:jar:2.46.0:test
|  |  +- cglib:cglib-nodep:jar:2.1_3:test
|  |  +- com.google.code.gson:gson:jar:2.3.1:test
|  |  +- org.seleniumhq.selenium:selenium-api:jar:2.46.0:test
|  |  +- net.java.dev.jna:jna:jar:4.1.0:test
|  |  \- net.java.dev.jna:jna-platform:jar:4.1.0:test
|  \- org.apache.commons:commons-exec:jar:1.3:test
+- org.seleniumhq.selenium:selenium-server:jar:2.46.0:test
|  +- org.bouncycastle:bcprov-jdk15on:jar:1.48:test
|  +- org.bouncycastle:bcpkix-jdk15on:jar:1.48:test
|  +- mx4j:mx4j-tools:jar:3.0.1:test
|  +- org.mortbay.jetty:servlet-api-2.5:jar:6.1.9:test
|  +- org.seleniumhq.selenium:jetty-repacked:jar:7.6.1:test
|  +- org.seleniumhq.selenium:jetty-rc-repacked:jar:5:test
|  +- net.jcip:jcip-annotations:jar:1.0:test
|  \- org.yaml:snakeyaml:jar:1.8:test
+- org.seleniumhq.selenium:selenium-support:jar:2.46.0:test
+- javax.servlet:servlet-api:jar:2.5:provided
\- org.apache.tomcat:tomcat-jdbc:jar:7.0.56:test
   \- org.apache.tomcat:tomcat-juli:jar:7.0.56:test

**Comment by barancev** [comment]
Outdated parts of httpcomponents are loaded as transitive dependencies of
+- org.apache.cxf:cxf-bundle:jar:2.7.15:compile
and
+- com.mycomp.myproj.integration:didanet-integration-sidi:jar:01.06.01-SNAPSHOT:compile
