### ISSUE TITLE
CKEditor 4/5 Support for all browser E2E

### ISSUE THREAD

**Issue by JSponaugle** [SeleniumHQ/selenium#6342]
Hello Selenium Team & Community,

   I am looking for a solution to provide CKEditor 4/5 support to a Angular Based Application. We use ng2-ckeditor as our plugin to provide ckeditor support and would like to know of a possible solution to a java or javascript base coded test scripts.

**Comment by AutomatedTester** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users). 

As long as the browser can introspect the HTML it should work though that doesnt mean it will be easy.
