### ISSUE TITLE
How to simulate onclick using Selenium/Python

### ISSUE THREAD

**Issue by lucy9383** [SeleniumHQ/selenium#6345]
## Meta -
OS:  

Selenium Version:  

Browser:  
<!Chrome>

Browser Version:  
<!68 (64-bit) -->

I am using Python/Selenium to click on an icon on a web site to add it as one of my condition. It's making a Javascript call. I've tried find_element_by_css_selector and execute_script but was unable to access this element.  Many thanks in advance!!!!

The element is and it is drop down menu which appears after I inputting keyword:
`<a href="javascript:void(0)" code="sc_u_sfwsj" class="mnuItm" ondblclick="mnuItm_dblClick();return false;" onclick="mnuItm_click(this,'{12:6,0:0,11:&quot;SFWSJ&quot;,2:&quot;SFWSJ&quot;,3:&quot;The Wall Street Journal - All sources&quot;,4:0,5:0,6:0,7:0,14:0,10:1}');return false;" title="Click to add to search; double-click to exclude from search.">The Wall Street Journal - All sources</a>`

The code I have tried:

```
wd.find_element_by_css_selector("a[onlick*=The Wall Street Journal - All sources]").click()



wd.execute_script("mnuItm_click(this,'{12:6,0:0,11:&quot;SFWSJ&quot;,2:&quot;SFWSJ&quot;,3:&quot;The Wall Street Journal - All sources&quot;,4:0,5:0,6:0,7:0,14:0,10:1}');return false;").click()
```

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
