### ISSUE TITLE
delegateCommandSystemProperties(ant + testng) is not working when using selenium-server-standalone-3.x

### ISSUE THREAD

**Issue by wonderwo** [SeleniumHQ/selenium#6346]
## Meta -
OS:  
 Windows 10
Selenium Version:  
3.x

After using selenium-server-standalone-3.x.jar properties are not getting replaced in testng even if delegateCommandSystemProperties is set to true. However same thing is working with selenium-server-standalone-2.x.jar.

Ant Version:  
apache-ant-1.10.5

TestNg version: 
testng-6.8

Expected Behavior - Properties passed from build.xml should get replaced in testng.xml

Actual Behavior -Properties passed from build.xml are not getting replaced in testng.xml

Steps to reproduce -
Create a target and ddd below testng tag in ant's build.xml:
                <testng
			   classpathref="tesng.all.path"
			   outputdir="${test.output}"
			   delegateCommandSystemProperties="true">
			  <sysproperty key="browser" value="${Browser}"/>
			<xmlfileset dir="${testng.base.dir}" includes="testng.xml"/>
		</testng>
Accept the parameter in testng.xml in test tag:
          <test verbose="2" name="Create connection and Import Report">
		<parameter name="browser" value="${browser}"/>

Run ant using command:
ant.bat -file build.xml -DBrowser=Chrome

**Comment by wonderwo** [comment]
The issue is observed selenium-server-standalone-3.0.0-beta3.jar onwards

**Comment by diemol** [comment]
Hi @wonderwo,

If you were using specific and/or custom arguments to start a Selenium Grid in versions 2.x, it is expected that those might not work right away when moving to Selenium Grid 3.x.

In addition, the information provided is not enough see if this is a bug or not.

Please check your parameters and their correspondence to recent Grid versions. In case you find a bug, please open a new issue and fill the complete template.

You can also join the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) in case you have questions or you could send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
