### ISSUE TITLE
alert is read only - exception thrown

### ISSUE THREAD

**Issue by fabianfrz** [SeleniumHQ/selenium#6349]
## Meta -
OS:  windows 7
Selenium Version:  
selenium ide 3.1.1.0
Browser:  
Firefox

-->

Browser Version:  
61.0.2

## Expected Behavior -
Works without exception
## Actual Behavior -
TypeError: ""alert" is read-only"
in modifyWindowToRecordPopUpDialogs in moz-extension://708ac0eb-73ae-49c3-934c-66b490b06697/assets/record.js:43776:249
## Steps to reproduce -

open a web console and look what it writes.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by fabianfrz** [comment]
looks like it is a duplicate of #52. Reproducing is easy because you only have to open the console and then click a random link. For some reason (I am on my Linux machine now, it does not happen there - selenium ide 3.2.5, Firefox 61.0.2).

**Comment by p0deje** [comment]
I don't understand how this is related to #52, can you elaborate?

Also, Selenium IDE doesn't work in Firefox 48+. A new version (https://github.com/seleniumhq/selenium-ide) is being developed, but has not been released yet.

**Comment by lmtierney** [comment]
They are using the new version of selenium-ide and this issue needs to be moved there.

**Comment by lmtierney** [comment]
Issue moved to [SeleniumHQ/selenium-ide #375](https://github.com/SeleniumHQ/selenium-ide/issues/375) via [**ZenHub**](https://www.zenhub.com/)
