### ISSUE TITLE
Firefox driver 2.46.0 regression - unable to set to non-js 

### ISSUE THREAD

**Issue by radek1st** [SeleniumHQ/selenium#635]
Setting:
profile.setPreference("javascript.enabled", false);
doesn't have any effect when using Firefox 38.0.5

It works correctly on 2.45.0.

**Comment by lukeis** [comment]
reproducible python script:

    from selenium import webdriver as w
    fp = w.FirefoxProfile()
    fp.set_preference("javascript.enabled", False)
    d = w.Firefox(firefox_profile=fp)
    d.get('about:config')

click the button and search for javascript.enabled and notice it's set to True.

Firefox 38.0.5  selenium 2.46.0

**Comment by barancev** [comment]
I suspect I know why we used to pre-run Firefox with -silent option.
But now it fails...

**Comment by lukeis** [comment]
we're unlikely to fix this though.... running without javascript enabled may have unintended other consequences on the Driver.

Running HtmlUnit without javascript enabled is an alternative.

**Comment by radek1st** [comment]
Hi, unlikely to fix it shortly (for next release) or unlikely to fix it ever? Cheers

**Comment by barancev** [comment]
"Fixed" by commit 28e4d9ce02c10e6765516049e8b39177e7f4259f
Fail fast solution.

**Comment by moritzp** [comment]
Gosh this just cost us half a day to figure out... Is there a workaround? This really hurts :(

**Comment by ddavison** [comment]
@moritzp it's been implemented, but not published yet. until it is - you can download the [latest jar](http://ci.seleniumhq.org:8080/job/Build%20All%20Java/lastSuccessfulBuild/artifact/selenium-server-standalone-latest.jar) that has the fix in it

**Comment by radek1st** [comment]
@ddavison by saying it has a fix in it do you mean that "javascript.enabled" flag is hardcoded and switching off javascript is no longer possible?

**Comment by ddavison** [comment]
to answer that question, i'll refer you to @barancev :)

**Comment by barancev** [comment]
I'd like to apply a proper fix if someone has one :)

This issue caused by the change 6fc17a0cba238af9d76f5fe6e32f73ac8958c19e that fixed much more critical issue -- total inability to start Firefox 38+.

We can create a user.js file with javascript.enabled = true, but Firefox ignores this preference (and only this!) being run in normal mode, without -s option. At the same time, -s option crashes the browser.

Why Firefox ignores this preference? I don't know. How to pass it to the actual profile? I don't know too. The only workaround I can imagine now is running browser with a pre-defined profile.

**Comment by dhruvbhatia** [comment]
This also seems to apply for the [permissions.default.image](http://kb.mozillazine.org/Permissions.default.image) flag, which is used to disable images.

Firefox is ignoring any user defined value.

**Comment by moritzp** [comment]
Mm using pre-defined profiles comes with a lot of downsides... We have a bunch of devs running tests locally and tons of vms for ci. All of them would need the profile etc... That'd be some serious pain too.

**Comment by fotinakis** [comment]
Here is a workaround for disabling JavaScript in Firefox via an addon, which works with Firefox 45 and selenium-webdriver 2.53.4: http://stackoverflow.com/a/39301760/128597

**Comment by muodov** [comment]
Is there still no other way than addon in 2019?
