### ISSUE TITLE
Can something be done towards reducing overall selenium repo size of over 1.6 GiB?

### ISSUE THREAD

**Issue by praveen4463** [SeleniumHQ/selenium#6351]
Selenium repo is over 1.6 GiB which is usually considered way too big. I see that may be caused by the thousands of commit objects/snapshots stored in git files.

Should it be reduced by removing "older by 6 months commits" which should potentially free up a lot of storage and reduce size to become < 1 GiB ?

**Comment by lmtierney** [comment]
Just don't clone the entire history, use a low depth

`git clone --depth 1 https://github.com/SeleniumHQ/selenium.git`
