### ISSUE TITLE
Drag and drop not working in IE11

### ISSUE THREAD

**Issue by rsdeepu** [SeleniumHQ/selenium#6354]
Drag and drop functionality not working in IE11. But I have tried the same to chrome browser it is working.
Somebody please help me?

Please see below the code which is worked in chrome but not in IE11

Actions dragandDrop=action.dragAndDrop(from, to);
dragandDrop.perform();

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

Also, please retest in the latest IEDriverServer that is 3.14 at the moment.

**Comment by rsdeepu** [comment]
@barancev Thanks for your reply.
I tested in 3.14 but no success.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by GitSage** [comment]
Nobody can do anything to help you until you give us something to work with. I know your application is proprietary, but you could, for example, make a small sample HTML document that has the same drag-and-drop element on it. 

[Here](https://github.com/GitSage/selenium-is-displayed-ie-bug) is the reproduction that I included with one of my bugs. You don't have to go so far as to make a Git repo, but we definitely need more than you've given us.

There are many ways to implement drag-and-drop functionality. We don't know which you are using. Native HTML5 `draggable`? `JQuery UI Draggable`? `DraggableJS`? Your own custom JavaScript implementation? Something else? Until we know more, there's nothing we can do.

**Comment by rsdeepu** [comment]
Hi All,

The IE11 drag and drop issue was resolved by using awt.Robot
