### ISSUE TITLE
Assert with variable doesn't work in new IDE version 3.3.1

### ISSUE THREAD

**Issue by julienb81** [SeleniumHQ/selenium#6357]
Command assert does not work any more with variable in the target. It works with the previous version 3.2.5. The variable value is considered undefined.

## Meta -
OS:  Windows 7
Selenium Version: IDE 3.3.1
Browser:  Firefox 62.0.1 and Chrome 68

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #382](https://github.com/SeleniumHQ/selenium-ide/issues/382) via [**ZenHub**](https://www.zenhub.com/)
