### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by fgisslen** [SeleniumHQ/selenium#6359]
Hi,
I get unknown error: DevToolsActivePort file doesn't exist every day when trying to start 50 instances of InstaPy at the same time in the morning.
I use --no-sandbox and --no-zygote. 

Any ideas?

**Comment by cgoldberg** [comment]
Please completely fill out the issue template when submitting a new issue.  Nothing can be done with the limited info you provided.
