### ISSUE TITLE
How to screen the entire browser?

### ISSUE THREAD

**Issue by JackWangAndRose** [SeleniumHQ/selenium#6362]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -

Now，I only can screenshot the page,but I wang to take screen entire Browser Including URL bar！How can I make it ?

**Comment by diemol** [comment]
Hi @JackWangAndRose, 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
