### ISSUE TITLE
Python:Selenium 3.13 documentation:Selenium Client Driver - Discrepancy in documentation and source code

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#6363]
## Meta - Discrepancy in the `Python:Selenium 3.13 documentation:Selenium Client Driver` _documentation_ and _source code for_ **selenium.webdriver.firefox.webdriver** as follows:

- [selenium.webdriver.firefox.webdriver](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html#module-selenium.webdriver.firefox.webdriver) mentions:

      class selenium.webdriver.firefox.webdriver.WebDriver(firefox_profile=None, firefox_binary=None, timeout=30, capabilities=None, proxy=None, executable_path='geckodriver', options=None, log_path='geckodriver.log', firefox_options=None, service_args=None, desired_capabilities=None)

- Where as [sourcecode](https://seleniumhq.github.io/selenium/docs/api/py/_modules/selenium/webdriver/firefox/webdriver.html#WebDriver) mentions:

      def __init__(self, firefox_profile=None, firefox_binary=None,
                 timeout=30, capabilities=None, proxy=None,
                 executable_path="geckodriver", options=None,
                 log_path="geckodriver.log", firefox_options=None):

The two parameters mentioned in the documentation **service_args=None** and **desired_capabilities=None** are missing in the source code.

OS:  All
Selenium Version:  3.13
Browser:  N/A

Browser Version:  N/A

**Comment by lmtierney** [comment]
Docs will be updated shortly with correct sourcecode via https://github.com/SeleniumHQ/selenium/commit/4048bdba145fda1144d4d6f9a54de4d3349135b6

**Comment by lmtierney** [comment]
Docs update is live
