### ISSUE TITLE
How do I use Selenium to operate a browser that is open normally？

### ISSUE THREAD

**Issue by once86** [SeleniumHQ/selenium#6364]
How do I use Selenium to operate a browser that is open normally? My current question is the x,y coordinates obtained in a normal browser, how to get xpath through selenium instead of opening a WebDriver. Or how to turn a normally open browser into a WebDriver.

maybe:
            var shellWindows = new ShellWindows();
            InternetExplorerDriver internetExplorerDriver = InternetExplorer;

**Comment by jimevans** [comment]
The short answer is, “You don’t.” Most WebDriver implementations require specific settings when the browser is launched (different for every browser) in order for the driver to be able to connect and control the browser. As this is a question better suited to a [user mailing list](
https://groups.google.com/forum/m/#!forum/selenium-users) than an issue tracker, I’m closing this.
