### ISSUE TITLE
Rect is undefined error

### ISSUE THREAD

**Issue by paprotti** [SeleniumHQ/selenium#6365]
## Meta -
OS:  Windows 10

Selenium Version:  v3.14.0

Browser:  Firefox Delevoper edition

Browser Version:  63.0b2 (64-bit)

## Issue description -

I'm working with kendo MVC. On kendo grids I've got CRUD actions and few of them are using modal. When this modal has more than 1 tabstrip the issue appears. For example I've got 2 tabstrips with kendo dropdown, numericbox etc. When I change value I need to focus them - did it with MoveToElement() method, and till the first tabstrip is on everything is ok, but on the second one I can't focus my element.

Code:
       

            js.ExecuteScript("$('#ShopAccount').children('.k-grid-toolbar').children('.k-grid-add').click()"); //click add button

            //first tabstrip
            js.ExecuteScript("$('#Shop').val(4)"); //set value on a dropdown
            IWebElement shop = driver.FindElement(By.XPath("//*[@id='tabstrip-1']/div[1]/div[2]/span[1]")); //find dropdown's element
            action.MoveToElement(shop).Click().Perform(); //focusing action
            
            driver.FindElement(By.XPath("//*[@id='tabstrip']/ul/li[2]")).Click(); //go to a second tabstrip

            js.ExecuteScript("$('#PriceLevel').val(1)"); //set value on a dropdown on second tab
            IWebElement priceLevel = driver.FindElement(By.XPath("//*[@id='tabstrip-2']/div[1]/div[2]/span")); //first dropdown's element
            action.MoveToElement(priceLevel).Perform(); //moving to element
            action.Click().Perform(); //focus this el

## Expected Behavior -

Focus kendo's elements like dropdown, numericbox

## Actual Behavior -

Getting an error that rect is undefined

## Steps to reproduce -

After moving to second tab line:

**action.MoveToElement(priceLevel).Perform(); //moving to element**

Giving me an error

> TypeError: rect is undefined. Can't access property 'x' of it.

I checked in console and the properties x and y exist. Stack trace is not telling much but:

> SeleniumTests.dll!SeleniumTests.Ebay.EbayAccounts.AccountAdd() Line 53

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue. Something like HTML code of the page that can be used locally to reproduce the issue.

**Comment by paprotti** [comment]
I don't think raw HTML will help, because kendo is written in JS and without these scripts it can works. Anyway I've tested this on kendo's website where are tabstrip examples and fortunately this error appears.

website:
https://demos.telerik.com/kendo-ui/tabstrip/index

Code:

    using OpenQA.Selenium;
    using OpenQA.Selenium.Firefox;
    using OpenQA.Selenium.Interactions;
    using System;
    using Xunit;

    namespace KendoTabstripTest
    {

    public class UnitTest1
    {

            [Fact]
            public void Test1()
        {

            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(@"C:\", "geckodriver.exe");

            IWebDriver driver = new FirefoxDriver(service);
            IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
            Actions action = new Actions(driver);

            driver.Url = "https://demos.telerik.com/kendo-ui/tabstrip/index";

            driver.Manage().Window.Maximize();

            IWebElement el1 = driver.FindElement(By.XPath("//*[@id='tabstrip-1']/div"));
            action.MoveToElement(el1).Perform();

            driver.FindElement(By.XPath("//*[@id='tabstrip']/ul/li[2]")).Click();

            IWebElement el2 = driver.FindElement(By.XPath("//*[@id='tabstrip-2']/div"));
            action.MoveToElement(el2).Perform(); //error
        }
    }
    }

**Comment by p0deje** [comment]
Thank you for a great bug report! I can reproduce the problem.

This is specific for GeckoDriver and I've found mozilla/geckodriver#1269 which describes the exact same problem. Please subscribe to it.

Closing this as it's GeckoDriver bug.
