### ISSUE TITLE
the current page is responded with a status of 504 (Gateway Time-out) ，then calling WebDriver.get(url ) doesn't work.

### ISSUE THREAD

**Issue by yimymo** [SeleniumHQ/selenium#6366]
## Meta -
OS:  
Windows 7，Windows 10, Windows server 2008 R2
Selenium Version:  
3.14 
Browser:  
Chrome 68 chromedriver2.39

Browser Version: 
68.0.3440.106 (32-bit) 

## Steps to reproduce -
Call WebDriver.get(url ) to open webpage several times in a row (every interval of about 3 minutes).
Because our application environment is not very stable, sometimes first  the server responded with a status of 504 (Gateway Time-out) ，and the page shows 'An error occurred....' . But every time next, 
the page always shows  'An error occurred....' . At this time, manually refresh the current page, the page display is normal. 
I have tried it dozens of times.

![Uploading image.png…]()

**Comment by yimymo** [comment]
![test](https://user-images.githubusercontent.com/26621449/45082089-28bd3a00-b12b-11e8-983e-dd3a920d84e9.png)

**Comment by cgoldberg** [comment]
Your application under test is not always reachable. what does this have to do with Selenium?
