### ISSUE TITLE
Selenium do not launch Firefox browser

### ISSUE THREAD

**Issue by IlyaDhtvzGhbltn** [SeleniumHQ/selenium#6367]
OS:  
Windows 10 
  
Selenium Web driver v3.14, 
Selenium FireFox Driver v0.21,  
IDE Visual Studio 2017 15.5.7 

Browser:  
Firefox
Browser Version:  
61.0.2 (64-bit)

## Steps to reproduce -

Open VS and paste current Code : 

```
string profileP = @"C:\Users\Iam\AppData\Roaming\Mozilla\Firefox\Profiles\ksj27pw6.Myprof";
FirefoxOptions options = new FirefoxOptions();
options.AddArguments("-profile", profileP);
FirefoxDriver browser = new FirefoxDriver(options);  // crush 
```

FF opened correct, with current profile, but then throw this error :

> OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:57637/session timed out after 60 seconds.'

**Comment by IlyaDhtvzGhbltn** [comment]
I can't solve this Issue already second day. Why so simple operation are so hard for Selenium ?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by IlyaDhtvzGhbltn** [comment]
anyway, could you help me?

**Comment by barancev** [comment]
That's what the uses group was created for.

**Comment by IlyaDhtvzGhbltn** [comment]
My question, has not been published in group. I sent the request more than 3 times, and question still not been added. Why ?
