### ISSUE TITLE
[Request] DotNet DefaultWait{T}: Add async version of Until method

### ISSUE THREAD

**Issue by yngndrw-sage** [SeleniumHQ/selenium#6369]
**Regarding DotNet Selenium.Support.UI.DefaultWait<T>.**

It would be nice if an async version of the [`DefaultWait<T>.Until(condition)`](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Support/DefaultWait%7BT%7D.cs#L142) method (`public async Task<TResult> UntilAsync<TResult>(Func<T, TResult> condition)`) could be added.

Essentially the code should be exactly the same with the following changes:
- The return type should be `Task<TResult>`
- The method signature should be marked as `async`
- [`Thread.Sleep(this.sleepInterval);`](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Support/DefaultWait%7BT%7D.cs#L201) should be changed to `await Task.Delay(this.sleepInterval);`
- The new method should be added to the [`IWait<T>`](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Support/IWait%7BT%7D.cs) interface

**Comment by jimevans** [comment]
Until support for .NET 3.5 and 4.0 is removed, this request is a non-starter. The use of #ifdef conditional compile directives to produce different APIs for different versions of .NET is not an appropriate approach for the .NET bindings of the Selenium project.
