### ISSUE TITLE
IEDriverServer.exe: Starting from version 3.5.0, screenshot only takes the visible part.

### ISSUE THREAD

**Issue by PatrickWANGv** [SeleniumHQ/selenium#6371]
## Meta -
OS:  Windows 10, version 1803
Selenium Version:  IEDriverServer.exe 3.5.0 or later
Browser:  Internet Explorer
Browser Version:  11.228.17134.0 (32-bit)

## Expected Behavior -
Using 32-bit IEDriverServer.exe, taking web page screenshot should save the whole page screenshot. IEDriverServer.exe version 3.4.0 or before could correctly save the whole page screenshot.

## Actual Behavior -
Starting from IEDriverServer.exe version 3.5.0, it only saves the visible part of the web page, not the entire whole page.

## Steps to reproduce -
In PowerShell,
    $s=[OpenQA.Selenium.ITakesScreenshot] $webDriver;
    $s.GetScreenshot().SaveAsFile($filename,[OpenQA.Selenium.ScreenshotImageFormat]::Png);

## 32-bit or 64-bit - 
My machines are all 32-bit. No ideas about it on 64-bit.

Thanks.

**Comment by jimevans** [comment]
Starting from IE driver 3.5, the IE driver implements the [W3C WebDriver Specification](https://w3c.github.io/webdriver/). According to the spec, specifically section 19, defines screenshots to be the visible view port, and not “the full page.” This is especially true as the term “full page” is less meaningful in today’s modern web, particularly those pages with so-called “infinite scroll.”
