### ISSUE TITLE
Out of Memory Error in distributed testing

### ISSUE THREAD

**Issue by ecamy** [SeleniumHQ/selenium#6372]
## Meta -
OS:  
Node: Win10
Hub: Win8

Selenium Version:  
V3.6.0

Browser:  
Chrome 61.0.3163.31

## Expected Behavior -

I have used testNG + Selenium Grid to test my web app.  The node prompted the following:
 java.lang.OutOfMemoryError: Java heap space 
after my testing program was been running for two days, then the thread is stopped. 

My web appp is a complex query program, which depends on a store procedure.
and my testing environment is as following:
1 Hub
3 Nodes
6 threads ( 2 threads/ per node)

## Actual Behavior -
May be I should set JAVA_OPTS=-Xms64m -Xmx512m for solving it, but how can i do if I use more computer to be my client nodes?

## Steps to reproduce -
1. Starting selenium hub and node
2. Running testng.xml for several days, then testing.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
