### ISSUE TITLE
Getting Driver is not accessible for all webdrivers in Eclipse in MAC

### ISSUE THREAD

**Issue by kanuj16** [SeleniumHQ/selenium#6378]
Hi,

I am trying to run Selenium in Eclipse in MAC machine but getting “The type org.openqa.selenium.firefox.FirefoxDriver is not accessible” error message.

I am getting this error message in all web drivers.

Looks like am missing to set the path correctly?

Can someone please help?

Kanuj

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
