### ISSUE TITLE
Double click is not working with FireFox61

### ISSUE THREAD

**Issue by dileepvarier** [SeleniumHQ/selenium#6379]
## Meta -
OS:  
Windows 7
Selenium Version:  
Selenium 3.14
Browser:  
FireFox

Browser Version:  
61.0.2 (32-bit)

## Expected Behavior -

I tried to double click the below elements using the below code, it is not working, only single click is happening. 

Actions routeTreeLnk = new Actions(driver);
routeTreeLnk.moveToElement(IEdriver.findElement(By.xpath("//*[@id=\"10003_node\"]"))).doubleClick().perform();

Later I tried the same using the JS

WebElement element = driver.findElement(By.xpath("//*[@id=\"10003_node\"]"));
((JavascriptExecutor) driver).executeScript("var evt = document.createEvent('MouseEvents');"+ 
					    "evt.initMouseEvent('dblclick',true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0,null);"+ 
					    "arguments[0].dispatchEvent(evt);", element);

Here also not working, only single click is happened.

Am using 64 bit OS. Initially I tried with 64 FF and 64 bit geckoDriver (geckodriver-v0.21.0). Then I tried 32 bit FF and 32 bit geckoDriver.

In both I received same result.

Can any one help on this ? I didn't find proper solution from Internet

## Actual Behavior -

Double click is not working with 32/64 bin FF and Drivergeckodriver-v0.21.0

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by lmtierney** [comment]
Closing as no test case was provided
