### ISSUE TITLE
Better string interpolation for execute_script. 

### ISSUE THREAD

**Issue by neatville** [SeleniumHQ/selenium#6384]
OS:  
Linux
Selenium Version:  
3.13.0
Browser:  
N/A

If we want to pass a number of arguments from Python to JavaScript, it would be nice to not have to remember the order. f-strings example:
`driver.execute_script(f"var arg = {hello}; if (!arg) { arg='default'; } document.title = arg;")` 
That currently returns a syntax error. JavaScript uses a lot of brackets too so it's hard to say exactly how it would work.

**Comment by lmtierney** [comment]
As with any formatted string, if you want to include brackets, you need to double them. Frex, you would use this instead and it would work fine:

`driver.execute_script(f"var arg = {hello}; if (!arg) {{ arg='default'; }} document.title = arg;")
