### ISSUE TITLE
running chrome-headless is too slow than non-headless.

### ISSUE THREAD

**Issue by HarryMai** [SeleniumHQ/selenium#6385]
## Meta -
OS:  windows7

Selenium Version:  3.5.3

Browser:  Chrome

## Expected Behavior -
open a website by using chrome-headless is faster than non-headless
## Actual Behavior -
running chrome-headless is too slow than non-headless.
## Steps to reproduce -
my code is :

				  if(headless==null||headless.isEmpty()||headless.equalsIgnoreCase("false")){
					  logger.info("----------headless close------------");
				  }else if(headless.equalsIgnoreCase("true")){
					  options.addArguments("--headless");
                                          options.addArguments("--disable-gpu");
				  }

BTW :  
I want to know is the selenium version problem... or is it the options setting problem???  i need someone help please ....

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
