### ISSUE TITLE
Just a bug I found hope I helped you.

### ISSUE THREAD

**Issue by Theexplor3r** [SeleniumHQ/selenium#6388]
I created a random tests. While running one of the test I paused it in debugger and switched from Execute tab to Tests tab and ran the test with start button. What happened is that it whited-out.
![whited-out](https://user-images.githubusercontent.com/41435915/45297821-3dc11100-b50f-11e8-9aea-c5490bc9b9af.PNG)

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #389](https://github.com/SeleniumHQ/selenium-ide/issues/389) via [**ZenHub**](https://www.zenhub.com/)
