### ISSUE TITLE
No space symbols after send_keys (on Debian OS)

### ISSUE THREAD

**Issue by chevi** [SeleniumHQ/selenium#6391]
## Meta -
OS:  Xfce 4.12

Selenium Version:  3.14

Browser:  Chrome

Browser Version:  69.0.3497.81 (64-bit)
Chrome driver Version: 2.41

## Expected Behavior -
Entered text with space symbols
## Actual Behavior -
Entered text is without space symbols
## Steps to reproduce -

> from selenium import webdriver
> from selenium.webdriver.common.keys import Keys
> txt = "hello! This is robot"
> driver = webdriver.Chrome()
> driver.get("http://www.python.org")
> elem = driver.find_element_by_id("id-search-field")
> elem.send_keys(txt)
> driver.save_screenshot('screenie.png')
> driver.close()

NOTE: with Firefox GeckoDriver - space symbols are typed and displayed correctly. 
NOTE: with same Chrome driver, but on Ubuntu/Mint - no problem

**Comment by barancev** [comment]
Please log this issue to chromedriver tracker: https://bugs.chromium.org/p/chromedriver/issues/list
