### ISSUE TITLE
Missing thread in distributed test using Selenium grid.

### ISSUE THREAD

**Issue by ecamy** [SeleniumHQ/selenium#6395]
## Meta -
OS:  
Hub: 1 computer, Win8
Node: 3 computer, Win10
Web application server: 2 computer, Cent OS6.6

Selenium Version:  
Selenium 3.5.3

Browser:  
Chrome 61 

I am testing my web app using Selenium+testng.   I send 12 threads to the 3 nodes, run 4 threads on each nodes,  in which two threads are sent to app server A, and the others are sent to app server B. 

When I run the test suites, some threads will stop till all testing cases were completed. I have tried to deal with it by adjusting my testing strategy, such as 2 hub testing, but failed. I repeated the testing again and again, and the max browser is 11, which is the same with your max limitation.

I also modified the maxSessions(20 or above) and  maxInstance(20), but still failed. An error example is as follows:
Hub: java -jar selenium-server-standalone-3.5.3.jar -role hub -maxSession 60
Node:  
java -jar selenium-server-standalone-3.5.3.jar -role node -hub http://192.168.100.1:4444/gird/register -maxSession 20 -port 5555 -browser browserName=chrome,maxInstances=12 -host 192.168.100.2

The missing threads does not run any more, and the window of these threads stop rolling still a run is ended. 

Other strange experiment result confuse me, that is six threads on one computer to one application can work well, why four threads to two application does not?

## Expected Behavior -
We can solve the above by adjusting max browser

## Actual Behavior -
Not work

## Steps to reproduce -
1. Starting 12 threads,  in which six to the server A, and six to the server B
2. At first starting 6 threads to server A, then Starting the rest to Server B, using 2 hub
3. See the result, some threads will be missing(stop till ending) , for all above two.

**Comment by cgoldberg** [comment]
please provide a test case showing sample code.  Your description is lengthy, but way too vague.  Also, please use meaningful and exact terms to describe the problem.

**Comment by ecamy** [comment]
Hi, cgoldberg,
Please see the attached titled "tg0910.txt", which is my testng file.
[tg0910.txt](https://github.com/SeleniumHQ/selenium/files/2373497/tg0910.txt)
Here is the comments : 
Two web servers whose IP addresses are 192.168.101.1/2:
test11- test16 is for testing the web application on 192.108.101.1,  
test21- test26 is for testing the web application on 192.168.101.2,

Three clients whose IP addresses are 192.168.88.1/2/3 
192.168.88.1:5555/5556/5557/5558 is for submitting the http requests to the servers, where port 5555/5556 send request to 192.168.101.1,  port 5557/5558 send request to 192.168.101.2. 
The ports of 192.168.88.2 and 192.168.88.3 are the same as 192.168.88.1.

Three classes is testing script, whose names are com.test.web.tg1/2/3 and for testing different web pages with different cases.
For the application on 192.168.101.1, we test three web pages, and two case files per web page. eg, 
Tg1 is for testing g1 web pages, using fbw_07 and fbw_08, which run on 192.168.88.1:5555 and 192.168.2:5556, respectively. 
Tg2 - g2 web pages - case files: cbw_07 and cbw_08 - address: 192.168.88.1:5556 and 192.168.88.3:5555
Tg3 - g3 web pages - case files: gim_05 and gim_06 - address: 192.168.88.2:5555 and 192.168.88.3:5556

When I run the testng.xml which based on Selenium grid. When I run the tg0910.xml which has twelve threads, some threads are missing, and the windows of the thread stop to scroll down(If normal, the window will scroll down with data stream from hub, all the time).  The errors message is about " the port is occupied", but I am not sure 

When I only run the threads test11-16(six threads which submit to one server 192.168.101.1 , It works well, and no missing threads.  

For running threads normally, I send a thread to other unused port, then some threads also stop. For example, when two threads on port 5555 and port 5556  are running, I send a thread to port 5557, then the thread on port 5555 will stop. (attn: Requests on port 5555 and 5556 will be sent to 192.168.101.1, Request on port 5557 will be sent to 192.168.101.2) 

That's my detail on the issue. I also want to provide you the sample codes, but I have no machine to debug it because all my testing machine is running. Now I use six machines  to test the two applications, It woks well. 

In a word,  I find that if a client send requests to two different applications using selenium grid, some threads don't work anymore, the windows of running stop all along.  

You can replace your class, server ip, client ip and case files to reproduce. Please pardon my poor abilities for this case. 

Thanks a lot.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) instead of narrative description. In your case it should be a sample project consisting of test scenarios and TestNG configuration that can be built and run to reproduce the issue.

**Comment by ecamy** [comment]
Hi, barancev, 
Thank you for your suggestions. I am looking for two web apps to complete the sample case, and a online system is the best. It looks like a bit difficult to find such an app, Have you an online system for testing?

**Comment by ecamy** [comment]
Hi,Teams,
By testing on a sample web application in the two days, The issue does not occur any more. So I think that it is related to my coding strategy and monitoring program, not related to Selenium grid.
Thanks so much.
