### ISSUE TITLE
The getAttribute atom treats `draggable` as a boolean attribute when it is actually enumerated

### ISSUE THREAD

**Issue by twalpole** [SeleniumHQ/selenium#6396]
## Meta -
OS:  OSX
Selenium Version:  Ruby 3.14.0
Browser:  Firefox & Chrome

The getAttribute atom treats the `draggable` attribute as boolean, when it is actually an enumerated attribute - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable.  This makes it impossible to read the actual value of the attribute since it will always return `true` if the attribute exists. I experienced this using the ruby bindings via selenium-webdriver 3.14.0 but it will affect any binding using the getAttribute atom.

**Comment by barancev** [comment]
You should log this issue to the spec first:
https://w3c.github.io/webdriver/

**Comment by barancev** [comment]
Oh, sorry, ingore my previous comment, the spec does not list boolean attributes explicitly, it just refers HTML specification.

**Comment by barancev** [comment]
There is one more interesting question about enumerated attributes. What should we return -- the actual attribute value or its "state"? Each enumerated attribute has two special states: 1) missing value default (if the attribute is not specified) and 2) invalid value default (if the value is not among the list of valid values).

**Comment by barancev** [comment]
Merged as 7c17f61c1ac35f0dbbce207f95186b483a27f33f

Unfortunately it will not make all drivers immediately compliant. A driver devs should update the atoms used in the driver.
