### ISSUE TITLE
bot.inject.cache.getElement throws STALE_ELEMENT_REFERENCE Error for elements inside a shadowRoot

### ISSUE THREAD

**Issue by dominikg** [SeleniumHQ/selenium#6399]
The check
https://github.com/SeleniumHQ/selenium/blob/cadae224ba4ff7cc7b59839ac44c7f750bc8da98/javascript/atoms/inject.js#L521-L528

does not take ShadowDom into account and thus fails for every element inside a shadowRoot.

**Comment by diemol** [comment]
Closing this to consolidate on #5869
