### ISSUE TITLE
Grid (3.13.0): Node not registering successfully 

### ISSUE THREAD

**Issue by lewisob** [SeleniumHQ/selenium#6404]
## Meta -
OS:  
Hub - OSX
Node - Windows 10 (On VirtualBox)
Selenium Version:  3.13.0

## Expected Behavior -
Node should register successfully.

## Actual Behavior -
The node looks like it registers but the hub shows an error - `Broken pipe (Write failed)`
<img width="526" alt="screen shot 2018-09-13 at 4 05 11 pm" src="https://user-images.githubusercontent.com/5219064/45470006-4152d300-b76f-11e8-9dd2-c06a4163c923.png">

Then the node seems to keep re-registering every minute or so:
```
23:10:00.403 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
23:12:25.668 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://X.X.X.X:4444/grid/register
```

When I attemp to run tests (using this node) this is the output from the grid logs:
```
16:09:41.121 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {acceptInsecureCerts: false, browserName: chrome, chrome.switches: --window-size=1920,1080, goog:chromeOptions: {args: [test-type, --window-size=1920,1080, test-type], extensions: []}, idle-timeout: 180, platform: WIN10, record-screenshots: false, version: }
16:09:41.133 DEBUG [ProxySet.getNewSession] - Available nodes: [http://X.X.X.X:4567]
16:09:46.138 DEBUG [ProxySet.getNewSession] - Available nodes: [http://X.X.X.X:4567]
16:09:51.142 DEBUG [ProxySet.getNewSession] - Available nodes: [http://X.X.X.X:4567]
16:09:56.146 DEBUG [ProxySet.getNewSession] - Available nodes: [http://X.X.X.X:4567]
16:09:57.500 DEBUG [DefaultRemoteProxy.isAlive] - Failed to check status of node: Failed to connect to /X.X.X.X:4567
16:09:57.500 INFO [DefaultRemoteProxy.onEvent] - Unregistering the node http://X.X.X.X:4567 because it's been down for 85239 milliseconds
16:09:57.500 WARN [DefaultGridRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://X.X.X.X:4567
```

## Steps to reproduce -
- I am running the grid on my macbook using wifi connection.
- On the same Macbook, using Vagrant + VirtualBox I run a node on Windows 10.
Vagrantfile network config - `config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "X.X.X.X"`

Has anyone ever experienced the same issue with Selenium Grid while running a node on a VirtualBox?
The `Broken pipe (Write failed)` message looks like a network thing but was hoping someone has experienced this before? 
I have tried experimenting with different network set ups but cannot get passed this.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
