### ISSUE TITLE
Deleteallcookies causes internet explorer to crash

### ISSUE THREAD

**Issue by jsa34** [SeleniumHQ/selenium#6405]
## Meta -
OS:  windows 7

Selenium Version:  3.14.0

Browser:  IE 11

Browser Version:  11.0.9600.19035 64bit

## Steps to reproduce - 

Call deleteAllCookies during page transition causes IE crash with report 'APPCRASH'

**Comment by jimevans** [comment]
Using the “delete all cookies” command is not globally broken for all scenarios. Can you provide a reproducible case (with code)? “During page transition” is a vague description that can’t be reproduced at face value.

**Comment by jsa34** [comment]
Can't isolate at the moment what is causing this to produce a reproducable case.  Put a workaround in by removing it and handling user cache in a different way.  If I can isolate a test case, I will reopen.  Apologies - posted and then realised that it only happens on a closed system which I can't expose for testing, but am unable to find a publicly available example where this happens.

**Comment by GeeSlimmy** [comment]
Delete All Cookies is not working on IE11 Browser with Selenium Webdriver. It works fine with all other browsers but on IE11 it hangs.
