### ISSUE TITLE
Support find by image as part of Selenium? Follow what Appium offers?

### ISSUE THREAD

**Issue by daluu** [SeleniumHQ/selenium#6406]
Maybe this is beyond scope of Selenium in that Selenium tries to keep things simple and barebones, whereas it makes more sense to have for (graphics heavy) mobile automation.

However, I don't see why it couldn't be considered for making as part of core Selenium WebDriver that could work across browsers and OS platforms with the right low level UI automation implementation for this.

See https://github.com/appium/appium/issues/943 and a recent blog post about the implementation now available to the public: https://appiumpro.com/editions/32 & https://appiumpro.com/editions/33.

Could be useful for Selenium against graphics heavy websites.

**Comment by lmtierney** [comment]
This should probably be raised to the [webdriver spec](https://www.w3.org/TR/webdriver1/)

**Comment by barancev** [comment]
Closing the issue as there is no reason to keep it open here. This feature will be implemented as soon as (and if) it's added to the W3C specification.
