### ISSUE TITLE
Support setting proxy for Safari WebDriver implementation

### ISSUE THREAD

**Issue by SamuraiJack** [SeleniumHQ/selenium#6413]
Hello,

As mentioned in https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/5051 proxy support is an important feature. Please add it to Safari Driver.

Thanks, Nickolay

**Comment by jimevans** [comment]
@SamuraiJack The Safari driver implementation is no longer developed or maintained by the Selenium project. It is developed and maintained by Apple. Feature requests for the safaridriver should be directed to Apple.
