### ISSUE TITLE
InternetExplorerDriver can't retrieve browser logs

### ISSUE THREAD

**Issue by jhrcek** [SeleniumHQ/selenium#6414]
## Meta -
OS:  Windows Server 2016
Selenium Version:  3.11.0
Browser:  InternetExplor

Browser Version:  internet explorer 11

## Expected Behavior -
WebDriver should be able to retrieve browser logs from InternetExplorer

## Actual Behavior -
WebDriver is throwing exceptions for when either method of the `org.openqa.selenium.logging.Logs` interface is used with `InternetExplorerDriver`

## Steps to reproduce -
Running the following code with InternetExplorerDriver (which otherwise works fine) throws exceptions (see comments)
```java
        Set<String> logTypes =  webDriver.manage().logs().getAvailableLogTypes();
/*
This throws :

java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
	at org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:108)
*/
        LogEntries logEntries = driver.manage().logs().get("browser");
        logEntries.getAll().forEach(entry -> System.out.println(entry.toString()));
/*
The above throws: 

 org.openqa.selenium.UnsupportedCommandException: malformed response to remote logs command
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com', ip: '172.16.127.16', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
 	at org.openqa.selenium.remote.RemoteLogs.getRemoteEntries(RemoteLogs.java:83)
 	at org.openqa.selenium.remote.RemoteLogs.get(RemoteLogs.java:77)
*/
```

**Comment by jimevans** [comment]
@jhrcek There are two problems with this. First, the IE driver implements the [W3C WebDriver Specification](https://w3c.github.io/webdriver/), which does not supply any log retrieval end points at all. Second, even if "Level 2" of the spec does document end points for log collection, it's incredibly unclear how the driver would access the "browser logs," which people usually want to mean "stuff written to the JavaScript console." Internet Explorer does not expose the JavaScript `console` object contents to external clients like the IE driver (the F12 Developer Tools don't count, as they're an internal implementation).

Having researched the issue over the years, I don't believe it can be easily done, but I'm willing to be proven wrong. I'd be more than happy to implement the command, if someone could indicate to me how it should be implemented. What COM API should I be querying? Is there a reliable way to capture that content 100% of the time, even for things logged during the `onload` event? Note that I'm not even asking for a PR to implement the collection, just what pieces I need to implement to get it working.

I'll leave this issue open for now, but in the absence of at least a promising avenue of future inquiry, provided within, say, the next four weeks, I'll be forced to close it as "unable to fix."

**Comment by jhrcek** [comment]
@jimevans thanks for explanation. If there's no clear way to fix this, I'm ok with closing this issue.

**Comment by jimevans** [comment]
@praveen Installing a browser add-on for IE requires administrative privileges and an elevated execution context (i.e., modifying the HKEY_LOCAL_MACHINE registry hive). This makes it a nonstarter for many users, who do not have such administrative control.
