### ISSUE TITLE
Improve Error Messages in ExpectedConditions.java

### ISSUE THREAD

**Issue by kunalgosar** [SeleniumHQ/selenium#6422]
Some of the messages here remove a lot of necessary context to fully understand the error.

For example: "number to be more than \"%s\". Current number: \"%s\"" misses the context of the locator and elements that are missing.

**Comment by kunalgosar** [comment]
@lmtierney would you be able to help in getting this reviewed and merged?

**Comment by lmtierney** [comment]
Not a Java person, sorry

**Comment by barancev** [comment]
PR merged, thanks!
