### ISSUE TITLE
Unable to run selenium scripts in parallel in IE 9

### ISSUE THREAD

**Issue by Priyaa25** [SeleniumHQ/selenium#6424]
Browser : IE
Windows: 7
Selenium version : Selenium-server-3.4
IE Driver version: 2.29
IE Version : 9

I am trying to open 2 sessions in IE for running my scripts in parallel. The selenium script types the values to be entered in both the sessions in one session and in the other session IE is launched and fails after that. Any idea regarding this?

**Comment by decreteii** [comment]
I think it's a known issue https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5980485/

**Comment by barancev** [comment]
@Priyaa25 Please retest in Selenium 3.14 using IEDriverServer 3.14

**Comment by barancev** [comment]
Closing the issue, it was reported against outdated software version and is supposedly fixed by now.
