### ISSUE TITLE
SafariDriver Could not start server: must specify at least one configuration argument.

### ISSUE THREAD

**Issue by yourSylvia** [SeleniumHQ/selenium#6426]
## Meta -
OS:  MacOS High Sierra 10.13.6

Selenium Version: 3.14 

Browser:  Safari

Browser Version: 11.1.2 

## Steps to reproduce -
Follow the instruction: https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari

First I run 'safaridriver --enable', then I tried the code in the instruction and run 'python test_webkit.py', I get:

~~~
objc[44085]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x7fff91e09748) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10f6a6eb0).
One of the two will be used. Which one is undefined.

objc[44085]: Class AMSupportURLSession is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x7fff931379f0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10f6a6f00).
One of the two will be used. Which one is undefined.

Could not start server: must specify at least one configuration argument.
~~~

So I tried to run '/usr/bin/safaridriver' and '/usr/bin/safaridriver -p 0' and get the same result. Which path should I chooose? Can anyone help?

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/

**Comment by manjunathscp** [comment]
@yourSylvia  Hi, was there any update on the issue with Apple?
