### ISSUE TITLE
chromedriver launches browser but doesnt do anything

### ISSUE THREAD

**Issue by AingharanU** [SeleniumHQ/selenium#6428]
OS:  Windows 10
Selenium Version:  3.14.0
Browser:  Google Chrome 
Browser Version: 69.0.3497.81 (Official Build) (32-bit)
Driver Version: ChromeDriver 2.42

I am using jupyter notebook to run my code. 
Trying to launch browser and direct to any site. Tested with www.google.ca.
```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('www.google.ca')
```
Browser will launch with 'data:,' in the url and will not do anything else. It will just be there until I manually close it at which point I get a SessionNotCreatedException. 

It was working fine until the latest chrome update about two weeks prior.
Any idea on whats wrong?

**Comment by 0TT0mation** [comment]
I think you should pass the chromedriver location to the driver initiation (in case it's not in PATH) and some options (if needed).

Something like:

chromedriver = " C:\path\to\chromedriver"
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("user-data-dir=C:\chrome-dev-app2")
driver = webdriver.Chrome(chromedriver,chrome_options =chrome_options)

**Comment by AingharanU** [comment]
Thanks alot! What seemed to fix it was the 
chrome_options.add_argument("user-data-dir=C:\dev-app2")

Thanks again!

**Comment by AingharanU** [comment]
Okay I seemed to have jumped the gun there. Probably shouldn't have tested with www.google.ca as that was the homepage and when that opened I assumed it was working. 

But now it just opens on a new tab window and continues to stay in a state of loading until manually closed like before.

The difference now is that the url no longer says "data:," but is blank. Doesn't go to the specified page. 

'''
from selenium import webdriver
chromedriver = "C:/path/to/chromedriver.exe"
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("user-data-dir=C:\dev-app2")
driver = webdriver.Chrome(chromedriver, chrome_options=chrome_options)
driver.get('https://www.bing.ca')
'''

**Comment by lmtierney** [comment]
@AingharanU make sure you escape the `\` in your user-data-dir path. `C:\\dev-app2`

**Comment by 0TT0mation** [comment]
You need to download chromedriver from https://sites.google.com/a/chromium.org/chromedriver/

After that replace the string inside the chromedriver variable with the path where YOU have downloaded chromedriver somethin like :

C:\Users\your_user\Downloads\chromedriver

BUT THE PATH WILL BE DIFERENT FOR YOU. check that before copy pasting
