### ISSUE TITLE
Selenium test case failing while running in a server machine using the executable jar file, without giving any error

### ISSUE THREAD

**Issue by handakafunda** [SeleniumHQ/selenium#6435]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Steps to reproduce -
1. create a selenium script to load google home page.
2. click on the I'm feeling Lucky button 
3. it should load the doodle page

when i run this script on my local machine, it worked fine.
Now i have created an executable jar file using maven and eclipse to run my test suit and downloaded this jar on my remote desktop machine on server with all the necessary dependent files. When i run the test using CMD java -jar "test-suit.jar"
it is opening IE browser successfully and load the url . It is clicking on I'm feeling lucky but it does not load doodle page after click and test fails . no error is given just i got this log

log4j:WARN No appenders could be found for logger (org.apache.http.client.protoc
ol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.
Sep 20, 2018 7:28:39 AM io.github.bonigarcia.wdm.WebDriverManager getDriversFrom
Xml
INFO: Reading https://selenium-release.storage.googleapis.com/ to seek IEDriverS
erver
Sep 20, 2018 7:28:40 AM io.github.bonigarcia.wdm.WebDriverManager getLatest
INFO: Latest version of IEDriverServer is 3.14
Sep 20, 2018 7:28:40 AM io.github.bonigarcia.wdm.Downloader checkBinary
INFO: Using binary driver previously downloaded
Sep 20, 2018 7:28:40 AM io.github.bonigarcia.wdm.WebDriverManager exportDriver
INFO: Exporting webdriver.ie.driver as C:\Users\debolin.dhar\.m2\repository\webd
river\IEDriverServer\Win32\3.14\IEDriverServer.exe
null
true
null
false
Started InternetExplorerDriver server (32-bit)
3.14.0.0
Listening on port 24032
Only local connections are allowed
Sep 20, 2018 7:28:47 AM org.openqa.selenium.remote.ProtocolHandshake createSessi
on
INFO: Detected dialect: W3C
true
false
clicked on I'm feeling lucky
doodle Page doesn't exist

===============================================
Suite
Total tests run: 4, Failures: 1, Skips: 1
===============================================

i am not getting what could be the error. whether it is not clicking and not throwing any error also or i need to take certain additional settings to be set on my server machine or change in my script to get it work

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
