### ISSUE TITLE
timeout no more 10 minutes

### ISSUE THREAD

**Issue by AwesomeAwesomeBest** [SeleniumHQ/selenium#6437]
OS:  
Windows 7
Selenium Version:  
2.33
Browser:  
Chrome 64.0.3282.119

I can't increase timeout waiting load page more 10 minutes. I see issue #4874, but its dont help me.
I'm use contructor (directory, option, timespan). I try timespan.FromHours but 10 minutes, not more. Please, help me.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also version 2.33 is drastically out of date, the current version is 3.14

**Comment by AwesomeAwesomeBest** [comment]
I'm use selenium chromedriver, last version from it 2.42. My bot find element on page by xPath, and click him. After page load they find and clict next element. And so in circle. Between first click pass 10 minutes and bot crash by timeout.

**Comment by barancev** [comment]
What Selenium client library version do you use?

And, by the way, 2.33 is not the latest version of chromedriver, please upgrade it.

**Comment by diemol** [comment]
Closing this issue as we didn't get a reply from the original poster. 

If someone is facing this issue, feel free to comment and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
