### ISSUE TITLE
Regression in Selenium >= 3.8.1: ConnectionResetError with chromedriver and Travis CI (Packet instance, not EC2)

### ISSUE THREAD

**Issue by andreymal** [SeleniumHQ/selenium#6438]
## Meta
OS: Ubuntu Trusty (Travis CI, Packet)
Selenium Version: >= 3.8.1
Browser: latest Chrome (69) with latest chromedriver (2.42)

## Expected Behavior

Selenium should work like <= 3.8.0, without ConnectionResetError

## Actual Behavior

```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
[...]
  File "/opt/python/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

## Steps to reproduce

Just use Selenium >= 3.8.1 (incl. 3.14.1) with chromedriver and Travis CI Packet instance (EC2 instance works good for me).

Selenium 3.8.0 works good.

I can't reproduce this problem using Python 2.7 (Python 3.x socket bug?)

I made a [special repository](https://github.com/andreymal/selenium-travis-test) for testing, see results here: https://travis-ci.org/andreymal/selenium-travis-test/branches

You can see the full log with traceback here: https://travis-ci.org/andreymal/selenium-travis-test/jobs/430688661

**Comment by andreymal** [comment]
@cgoldberg you should not close the issue until it is fixed or disproved. "Me too" replies are bad, but this is not the reason for closing. The problem is still not fixed. People still have to lock `selenium==3.8.0`.

**Comment by lmtierney** [comment]
@andreymal what am I doing wrong here? https://travis-ci.com/lmtierney/selenium-travis-test/builds/85680967

I've tried rebuilding it a few times and it hasn't failed.

**Comment by lmtierney** [comment]
Looks like putting it into a branch gave me a better result

**Comment by lmtierney** [comment]
Ok I did lots of testing and I believe this is the change that is causing your issues. Why it is, I'm not really sure. I might have time to look tomorrow, but can you try reverting this in your testing?

https://github.com/SeleniumHQ/selenium/commit/66f77a0c3623d0761f35f82ad620b3cd1cba66c7#diff-dfed5bc177b87ab317c584e06566adc6

**Comment by andreymal** [comment]
@lmtierney 

>what am I doing wrong here?

See "Worker information" → "hostname", the EC2 instance works good

I didn't find how to explicitly select the Packet instance, so we have to restart the build until "Worker information" will report about the Packet instance

(Can someone test https://www.packet.net/ directly without Travis? It's possible that this is a Packet bug, but I don't know how to verify this)

(Anyway, Selenium 3.8.0 works good with Packet)

**Comment by lmtierney** [comment]
Yes, I was able to reproduce it on packet. Please try reverting the commit I mentioned in my last comment and run your tests as it seems to work for me.

**Comment by lmtierney** [comment]
After hours of trying things, it actually appears to be intermittent on `packet`. I can re-run the same test and one time it will pass on a `packet` host and another time it will fail. Honestly, it almost seems to be a timing thing. With that commit I mentioned, it does add one more check on the socket.

**Comment by andreymal** [comment]
Yes, I can't reproduce it with the reverted commit https://travis-ci.org/andreymal/selenium-travis-test/jobs/432625691

**Comment by lmtierney** [comment]
But that passed?

**Comment by lmtierney** [comment]
Oh whoops, read your comment wrong. I'm not sure what else to try from here

**Comment by cgoldberg** [comment]
I think I found the reason that commit is problematic.

I think a bug exists in the `is_connectable` function it's using (from py/selenium/webdriver/common/utils.py)

`is_connectable` relies on `socket.create_connection` raising a `socket.error`.  This is fine in Python 2 but not Python 3.  Starting with python 3.3, `socket.create_connection` no longer raises `socket.error`.  So instead of returning False, the function just bails when a `ConnectionResetError` is raised.

**Comment by lmtierney** [comment]
@andreymal can you try the fix from #6480 ? I tried but for some reason now my workers are all `gce` without changing anything in my travis config

**Comment by andreymal** [comment]
@lmtierney now it fails rarely, but still fails https://travis-ci.org/andreymal/selenium-travis-test/jobs/436860967 (not sure why, I'll try to recheck it later)

Maybe [this line](https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/py/selenium/webdriver/remote/remote_connection.py#L497) should also be modified?

`sudo: false` and `dist: trusty` helped me to disable `gce`

**Comment by konstin** [comment]
@cgoldberg This is *exactly* the same bug as #5296. Even `is_connectable` [is correctly identified](https://github.com/SeleniumHQ/selenium/issues/5296#issuecomment-390835124) there. Imo #5296 should be reopened.

**Comment by alexandernst** [comment]
I have been hitting this for quite some time now. 3.8.1 contains the bug, 3.8.0 doesn't. 

Full backtrace using 3.8.1: 

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/code/crawler/management/commands/crawl.py", line 38, in handle
    browser = Browser()
  File "/code/browser.py", line 86, in __init__
    chrome_options=options,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 490, in _request
    resp = self._conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Repro code, as simple as opening tabs in a loop and loading `google.com`.
