### ISSUE TITLE
Selenium 2.9 record button is not working

### ISSUE THREAD

**Issue by Ranj1912** [SeleniumHQ/selenium#6439]
## Meta -
OS:  Windows 10

Selenium Version:   2.9.1

Browser:  Firefox

Browser Version:  
 56.0b10

## Steps to reproduce -
![record issue](https://user-images.githubusercontent.com/43517807/45928816-5f86b300-bf67-11e8-8d1a-4efb300c367b.jpg)

**Comment by cgoldberg** [comment]
please submit an issue to https://github.com/SeleniumHQ/selenium-ide
