### ISSUE TITLE
What is the reason to rewrite various locators to css in W3C mode?

### ISSUE THREAD

**Issue by mykola-mokhnach** [SeleniumHQ/selenium#6449]
We've faced quite unusual behaviour in all selenium clients (java/ruby/python) while implementing W3C support in Appium. All id/name/class name locators were forcefully rewritten to css locator type before being sent to the server. This behaviour, of course, broke our tests for native mobile context (since css locators have no sense there), so we had to override it and restore the normal behaviour. Although, it would be interesting to know what was the original cause for such an ugly hack and whether you plan to keep it for the future.

Reference commit: https://github.com/appium/python-client/commit/238ca0e1b006d1430c32a4cc789f1bf763cf6366

**Comment by mykola-mokhnach** [comment]
CC @KazuCocoa

**Comment by jimevans** [comment]
Put simply, locators that can be directly expressed as CSS selectors (ID, name, class name) are not present in the spec at all. A spec-compliant remote end with a find element payload of `{ using: "id, value: "foo"

**Comment by mykola-mokhnach** [comment]
Sure, I understand the concern and I see that https://www.w3.org/TR/webdriver1/#locator-strategies does not include any of the selector types above (which is not very optimal for mobile though). Is there any way to put such locators back to the spec?
