### ISSUE TITLE
chrome 69.0.3497.100 enable flash error

### ISSUE THREAD

**Issue by nu1ee** [SeleniumHQ/selenium#6450]
```
prefs = {
	"profile.default_content_setting_values.plugins": 1,
	"profile.content_settings.plugin_whitelist.adobe-flash-player": 1,
	"profile.content_settings.exceptions.plugins.*,*.per_resource.adobe-flash-player": 1,
	"PluginsAllowedForUrls": "http://www.xxx"
}

ChromeOptions.add_experimental_option("prefs",prefs)
```

This command is no longer valid

**Comment by lmtierney** [comment]
Care to elaborate? What command is no longer valid? If you're talking about `add_experimental_option` then you need to create an instance of ChromeOptions first. You're calling it as a class method

**Comment by nu1ee** [comment]
I need to enable flash in the url, but the latest version of chrome can't enable flash. I use python.

**Comment by lmtierney** [comment]
That would be an issue for the Chrome team then
