### ISSUE TITLE
could add the match for https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/support/expected_conditions.py

### ISSUE THREAD

**Issue by mansonami** [SeleniumHQ/selenium#6452]
class text_to_be_present_in_element_value_match(object):
    """
    An expectation for checking if the given text is present in the element's
    locator, text
    """
    def __init__(self, locator, text_):
        self.locator = locator
        self.text = text_

    def __call__(self, driver):
        try:
            element_text = _find_element(driver,
                                         self.locator).get_attribute("value")
            if element_text:
                str = re.findall(self.text, element_text)
                return str
            else:
                return False
        except StaleElementReferenceException:
                return False

**Comment by diemol** [comment]
Not clear what this issue tries to tell us, please open a new one with all the required information from the template. If this was a question, please consider: 
  * 📫 Sending it to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post it to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
