### ISSUE TITLE
Please have an up to date howto on at least how to open a webpage

### ISSUE THREAD

**Issue by daredevilbsd** [SeleniumHQ/selenium#6453]
After following this:

https://cat.ninja/using-selenium-with-headless-firefox-on-freebsd/

And many other tutorials I still cannot get what I need is that I want to get and save the content of a webpage using javascript, the way it looks like in the browser.

After spending hours on dead projects like console crawler and phantomjs I have found selenium, and it MIGHT be the solution for what I need but I still cannot get it to work.

OS: latest FreeBSD stable FreeBSD 11.2-RELEASE

pkg install py36-pip
pip-3.6 install selenium
pkg install geckodriver
pkg install firefox-62.0.2,1

Example1:

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()

```

```
Traceback (most recent call last):
  File "open.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium
```

I try:

```
python3.6 a.sel
Traceback (most recent call last):
  File "a.sel", line 5, in <module>
    br = webdriver.Firefox()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 162, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


```
Example 2

```
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

br = webdriver.Firefox()
br.get('http://www.google.com/')

save_me = ActionChains(br).key_down(Keys.CONTROL)\
         .key_down('s').key_up(Keys.CONTROL).key_up('s')
save_me.perform()
```

Let's start it with that these are python, why on earth this is not mentioned anywhere that this is freaking python, why cannot at very least a simple example be provided for opening a god damn webpage?!?

**Comment by lmtierney** [comment]
It even says on the tutorial you shared:

> Running the Automation scripts
While trying to run my automation scripts, I encountered some non self explanatory error messages. Turns out that eventhough firefox is in the PATH in out environment variables, we still need to explicitly specify its location to selenium. This location is usually /usr/bin/local/firefox in FreeBSD. In your python script make sure you mention it:
>
>driver = webdriver.Firefox(firefox_binary='/usr/local/bin/firefox', ...)

This is a question rather than an issue. Issues are reserved for actual issues with the code, with a reproducible test scenario. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).
