### ISSUE TITLE
Selenium IDE Window - width auto adjusts

### ISSUE THREAD

**Issue by ClaireHut42** [SeleniumHQ/selenium#6454]
## Meta -
OS:  Windows 10
Selenium Version: 3.3.1  
Browser: Google Chrome
Browser Version: 69.0.3497.100 (64-bit)

## Expected Behavior -
The Selenium IDE Windows remain at a fixed width

## Actual Behavior -
Selenium IDE Window containing the Tests / Test Suites / Executing changes width when the mouse moves over it. It makes the main window readjust so it is difficult to click on commands.

## Steps to reproduce -
Move mouse over the left window. Move the mouse to the main window.

![capture1](https://user-images.githubusercontent.com/33250281/46132896-3308ba80-c237-11e8-8911-89eeb6ba46d7.png)

![capture2](https://user-images.githubusercontent.com/33250281/46132871-271cf880-c237-11e8-98fa-3ac4cc412d81.PNG)

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #419](https://github.com/SeleniumHQ/selenium-ide/issues/419) via [**ZenHub**](https://www.zenhub.com/)
