### ISSUE TITLE
Problem with a table html element inside a updatepanel

### ISSUE THREAD

**Issue by SamirGoes** [SeleniumHQ/selenium#6457]
## Meta -
OS:  Windows 10

Selenium Version:  3.12.1

Browser:  Internet Explorer

Browser Version:  11.483.15063.0

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
