### ISSUE TITLE
Unable to modify download directory or some setting after create a widow

### ISSUE THREAD

**Issue by WongYueKeung** [SeleniumHQ/selenium#6458]
#This issue comes up with all plantform as long as u using selenium

Hi, I used this selenium for many years, there r some issue I would like to share and hope someone can come out and fix this important issue.
for example, we are testing a webpage using PHP with facebook/webdriver
Before we create a window, we can put some setting inside the DesiredCapabilities options, and then create a chrome window, or tab.
Is it easy to set download directory, disable javascript and stuff like that before we create a chrome window.
After that we will be not able to change that setting via chromedriver. However, we still can change those setting by open setting page on chrome and do it manually.
The point for us to using chromedriver is lots of action operate on chrome can be done automatically like testing.
In my case, there is a login page that requires javascript to show, and when it comes to another page, I want to disable the javascript to see what data actually did  server sent to the browser(raw Http response data), so we can find out bug and fix it, but if the javascript is enabled, it will change the DOM content, and we cant see.
Steps to reproduce (if relevant, you MUST provide a simplified HTML page or
just make a simple javascript, when the window is loaded ready, change the content of the webpage, execute getPageSource(),  and you cannot see raw data sent from server anymore.

Plz allow us to change the DesiredCapabilities setting again after we create a chrome process.

**Comment by lmtierney** [comment]
Please stop raising issues on this matter. Once again, this is a problem for Chrome/Chromedriver.

The capabilities payload required would be in the `goog:chromeOptions` key.

This is python, so you'll need to translate.
```
desired_capabilities = {'goog:chromeOptions': {'prefs': {'profile.default_content_setting_values': {'javascript': 2}}}}
```

PLEASE send future questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
