### ISSUE TITLE
Add clipping information to GET /session/:sessionId/screenshot

### ISSUE THREAD

**Issue by jeantil** [SeleniumHQ/selenium#646]
I mistakenly created this issue on the wrong tracker back in january. 

This is an enhancement request for the JSON wire protocol. 

Currently https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/screenshot doesn't take any parameter and doesn't document the expected relationship between the windows size and the screenshot size. 

Ghostdriver in Phantomjs does not enforce clipping to viewport size when taking a screenshot, leading to screenshots which have the correct viewport width but a random height depending on page content. 

PhantomJS does offer an API to define a clipping area to be used for rendering the screenshot but there is no way for Ghostdriver to use it without breaking a use case or another. 

Adding a clip query parameter (or better a width and height) parameter to the GET screenshot  call would allow both use cases (clipped and unclipped). 

With the advent of FullPage websites/parallax/... the height of pages can be huge, leading to enormous screenshots. Adding viewport clipping would allow for smaller screenshots.

hopefully this is the correct tracker to submit this

Thanks

**Comment by AutomatedTester** [comment]
The default for when everything has moved to the W3C implementation of WebDriver is that screenshots will be limited to only the viewport and we are also adding the ability to screenshot specific elements 



—

**Comment by jeantil** [comment]
that's great for my use case :) I guess I'll report this to phantomjs then (I noticed the ability of screenshotting specific elements in the w3c draft)

**Comment by AutomatedTester** [comment]
The specification in this area needs rewriting. Work has started in https://github.com/w3c/webdriver/pull/98



—

**Comment by lukeis** [comment]
gonna close this issue, as the parts exist in other repos (either phantomjs&ghostdriver or w3c/webdriver )

**Comment by jeantil** [comment]
I have come to the same understanding. Thanks for closing the issue

Le mer. 17 juin 2015 22:58, Luke Inman-Semerau <notifications@github.com> a
écrit :

**Comment by foxx** [comment]
Am I correct in saying that this issue will never be fixed? e.g. we will never be able to take full page screenshots?

**Comment by lukeis** [comment]
@foxx correct. It will take viewable page shots. As to say that which is in the current viewport.
