### ISSUE TITLE
Selenium 3.14.1 + geckodriver 0.22.1 + Firefox 61(64-bit) Do not connect through proxy

### ISSUE THREAD

**Issue by Ganelony** [SeleniumHQ/selenium#6460]
## Meta -
OS:  
Windows 8
Selenium Version:  
3.14.1
Browser:  
Firefox

I have got a problem, that I really cant get through!

My comp is behind proxy! I can't connect to Internet directly, so I get through the Proxifier and 10.25.16.43 proxy server in my local net.
Python is Ok with that situation and all of my parsing scripts work well!
Recently I installed Selenium 3.14.1 module and geckodriver 0.22.1 tried them with Firefox 61(64-bit) - did not connect.
I checked: "geckodriver.exe" and "Firefox.exe" are in the PATH...

Script is like that:

from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/')

Python returns Error: Can not connect to the Service geckodriver.

Proxifier shows the follows:

[09.28 13:23:51] python.exe *64 - localhost:61171 (IPv6) error : Could not connect through proxy 10.25.16.43:8080 - Proxy server cannot establish a connection with the target, status code 502
[09.28 13:23:54] python.exe *64 - localhost:61171 error : Could not connect through proxy 10.25.16.43:8080 - Proxy server cannot establish a connection with the target, status code 502

Log of geckodriver is like that:

1538101395324	geckodriver	INFO	geckodriver 0.21.0
1538101395340	geckodriver	INFO	Listening on 127.0.0.1:61171
If geckodriver's version is 0.21.0

And Log is empty if geckodriver's version is 0.22.0

hosts - coments removed from localhost:

127.0.0.1 localhost

Could anybody advice me, what I did wrong!?

**Comment by barancev** [comment]
CLosing the issue as a solution was found.
