### ISSUE TITLE
Safari - The command 'GET /session/SESSION_ID/element/ELEMENT_ID/displayed' was not found

### ISSUE THREAD

**Issue by nairouz12** [SeleniumHQ/selenium#6466]
## Meta -
**OS:**  MAC OS High Sierra 10.13.6
**Selenium Version:**  selenium-webdriver (3.14.0)
**Browser:**  Safari 12.0
**Ruby:** 2.5.1

## Expected Behavior -
element could be found and clicked

## Actual Behavior -
Issue started after getting Safari browser version upgraded to 12.0.
The command GET could not be found
`The command 'GET /session/3EB05907-8FC7-4BD5-87CF-91284C2E8F47/element/node-262078C2-F9AF-4EF7-8F06-409B155E06AF/displayed' was not found. (Selenium::WebDriver::Error::UnknownCommandError)`

the same test was properly working with the previous version of Safari
Issue not reproduced with Firefox and Chrome

**Comment by lmtierney** [comment]
Ruby needs to be updated to use the atom for w3c implementations

**Comment by nairouz12** [comment]
how can i updated?

**Comment by lmtierney** [comment]
@nairouz12 I'm just adding information to this issue, we need to fix it. This github project covers 5 languages

**Comment by nairouz12** [comment]
@lmtierney do you confirm that this is an issue that needs to be fixed? if yes, by when?
Is there any workaround to make my scripts running again in Safari?

**Comment by nairouz12** [comment]
Yes indeed. I got my scenarios working back with the legacy mode.

**Comment by lmtierney** [comment]
This is fixed with b618499adcc3a9f667590652c5757c0caa703289 and will be in the next release
