### ISSUE TITLE
C# - Chrome Browser Resizing not working as expected!

### ISSUE THREAD

**Issue by jtorres006** [SeleniumHQ/selenium#6473]
OS:  Windows
Selenium Version:  3.14
Browser:  Chrome
Browser Version:  69.0.3497.92
ChromeDriver: 2.42.0.1

We have a wrapper class around selenium and I am detecting that browser resizing is not working as expected.

C# - Unit test fails:
            _driver.Navigate().GoToUrl(url);
            var size = new System.Drawing.Size(500, 500);
            _driver.Manage().Window.Size = size;            
            Assert.AreEqual(new System.Drawing.Size(500, 500), _driver..Manage().Window.Size, "The browser size was not changed as expected!");

Error Message:
The browser size was not changed as expected!
  Expected: {Width=500, Height=500}
  But was:  {Width=605, Height=500}

Will continue to research and its not high priority for me but maybe others.

I was working properly on Chrome 64 with selenium 3.12.1 & ChromeDriver 2.37.0.

Thanks, 
Jason T.

**Comment by barancev** [comment]
It's a browser "feature", they increased min window width, we had to change our tests too: 669690b2a8c696f2c7ff2481d3b044ba88e69c81

**Comment by jtorres006** [comment]
Thanks for that information, will update our test :)
