### ISSUE TITLE
when invoke IWebElement property Location in WebView it is automatically scrolled into view

### ISSUE THREAD

**Issue by vatsikmax** [SeleniumHQ/selenium#6476]
## The problem

When I'm trying to invoke property Location for IWebElement(will call it Element further) in WebView, and Element is not visible but exists in the dom (for example last list instance) -> Element is scrolled to the top of container automatically
(I successfully switch to WEBVIEW and found Elemement) 

## Environment

* Appium version 1.9.0
* macbook Sierra:
* Node.js version 8.11.4
* Device under test iPhone 6+ Ios 10.3
* Real device Hybrid App

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.getAttribute() with args: ["innerHTML","5148","d6f95fdb-47ff-48ca-b7fc-bad0b7de0f1b"]
[debug] [XCUITest] Executing command 'getAttribute'
[debug] [RemoteDebugger] Executing 'get_attribute_value' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Unable to collect garbage at this time
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":\"\u003C!----\u003E\u003Cdiv ngcontent-c16=\\\"\\\" class=\\\"c-full-width\\\"\u003E\u003Cbc-qpl-base-item ngcontent-c16=\\\"...'
[debug] [RemoteDebugger] Found method 'Runtime.evaluate' for '408' message
[debug] [RemoteDebugger] Received result for atom 'get_attribute_value' execution: "<div ngcontent-c16=\"\" class=\"c-full-width\"><bc-qpl-base-item ngcontent-c16=\"\" dat...
[debug] [MJSONWP] Responding to client with driver.getAttribute() result: "<div ngcontent-c16=\"\" class=\"c-full-width\"><bc-qpl-base-item ngcontent-c16=\"\" data-automation-e2e-selector=\"value\" nghost-c19=\"\"><div ngcontent-c19=\"\" class=\"c-list-group-item c-p-sm c-p-horizontal-md c-bg-warning-0\" data-automation-e2e-selector=\"listItemContainer\"><div ngcontent-c19=\"\" class=\"c-header-lg c-m-0 text c-text-gray-7 truncateText\" data-automation-e2e-selector=\"title\">Adam Black</div><div ngcontent-c19=\"\" class=\"c-body-text c-m-0 text c-text-gray-6 truncateText\" data-automation-e2e-selector=\"byline\">Waratah Capital Advisors, LTD</div></div></bc-qpl-base-item></div><div ngcontent-c16=\"\" style=\"display: none; position: absolute; top: 0px; bottom: 0px; left: 0px; right: 0px; z-index: 1; background-color: rgba(255, 255, 255, 0.498039); background-position: initial initial; background-repeat: initial initial;\"><all-bound-alert nghost-c5=\"\" class=\"ng-star-inserted\"><div ngcontent-c5=\"\" class=\"bound-alert bound-alert__container\"><div ngcontent-...
[HTTP] <-- GET /wd/hub/session/d6f95fdb-47ff-48ca-b7fc-bad0b7de0f1b/element/5148/attribute/innerHTML 200 55 ms - 1686
[HTTP] 
[HTTP] --> GET /wd/hub/session/d6f95fdb-47ff-48ca-b7fc-bad0b7de0f1b/element/5148/size
[HTTP] {}
[debug] [MJSONWP] Calling AppiumDriver.getSize() with args: ["5148","d6f95fdb-47ff-48ca-b7fc-bad0b7de0f1b"]
[debug] [XCUITest] Executing command 'getSize'
[debug] [RemoteDebugger] Executing 'get_size' atom in default context
[debug] [RemoteDebugger] Garbage collecting with 5000ms timeout
[debug] [RemoteDebugger] Unable to collect garbage at this time
[debug] [RemoteDebugger] Sending javascript command (function(){return function(){var h=this;functi...
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var h=this;functi...
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{"result":{"type":"string","value":"{\"status\":0,\"value\":{\"width\":414,\"height\":62}}"},"wasThrown":false},"id":409}'
[debug] [RemoteDebugger] Found method 'Runtime.evaluate' for '409' message
[debug] [RemoteDebugger] Received result for atom 'get_size' execution: {"width":414,"height":62}
[debug] [MJSONWP] Responding to client with driver.getSize() result: {"width":414,"height":62}

## Code To Reproduce Issue [ Good To Have ]

IWebElement last = allLoadedItems.Last().Element;
last.Location;

**Comment by barancev** [comment]
Please report this issue to Appium project: https://github.com/appium/appium/issues
