### ISSUE TITLE
Clicking element is not clickable

### ISSUE THREAD

**Issue by buihoanghai** [SeleniumHQ/selenium#6482]
Element is not clickable other element would receive the click. But the receive element is parent element. Is it a bug or feature?

![image](https://user-images.githubusercontent.com/6602376/46468210-67194800-c802-11e8-8206-93f6e26146fa.png)

![image](https://user-images.githubusercontent.com/6602376/46468477-181fe280-c803-11e8-92a4-4ef49411a5b9.png)

**Comment by lmtierney** [comment]
This determination is handled solely by Chromedriver/Chrome

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
