### ISSUE TITLE
CORS related tests not possible with Selenium + Python + Chrome/Firefox

### ISSUE THREAD

**Issue by asudhak** [SeleniumHQ/selenium#6486]
## Meta -
OS:  
OSX

Selenium Version:  
1.22 Python

Browser:  
Chrome

Browser Version:  
69.0.3497.100

## Expected Behavior -
* Login to domain1.com
* cookies for domain1 are set
* Open page domain2.com in a new tab
* domain2 contains a CORS request to domain1
* domian1 sets correct CORS headers 'Access-Control-Allow-Origin' and 'Access-Control-Allow-Credentials' from domain2
* domain 2 successfully sets cookies and the CORS request is succesful

This behavior works as expected when manually performing the above steps.

## Actual Behavior -
* Login to domain1.com
* cookies for domain1 are set
* Open page domain2.com in a new tab
* domain2 contains a CORS request to domain1
* CORS request fails because the cookies for domain1 is not available in the context of domain2 when using selenium

## Steps to reproduce -
Its not possible to create a SSCCE for this, so i'm providing a code snippet of what i'm trying to achieve.

` options = webdriver.ChromeOptions()
        print url

        browser = webdriver.Chrome(executable_path="./chromedriver")
        
        browser.get("http://127.0.0.1:8080/")
        print browser.title
        browser.find_element_by_name('username').send_keys("admin")
        browser.find_element_by_name("password").send_keys("hunter2")
        browser.find_element_by_tag_name("button").click()
        print browser.get_cookies()
        #shows cookies correctly

        print 'loading cors page: ' + url
        browser.execute_script("window.open('%s');" %url)
        #chrome web console shows that the request failed because it failed to set the cookies`

**Comment by p0deje** [comment]
What exact error do you see in CORS response? Can you reproduce the error using Firefox + GeckoDriver?

The mechanism of sending credentials is implemented by browser, I don't think Selenium can interfere with it anyhow. I also tested using a simple example (
http://jsfiddle.net/jyougo/3aettrzq/) and I can see that Chrome successfully sends `Access-Control-Allow-Credentials: true` header.

**Comment by asudhak** [comment]
@p0deje
The error that I see is a 401 because the CORS request which is supposed to send credentials does not have any credentials to send.  

>Can you reproduce the error using Firefox + GeckoDriver?
Yes, same behaviour. Navigating to a new domain seems to clear all cookies.

I will try to provide a server and a working example of the issue. Meanwhile, can you tell me if Selenium clears browser cookies or resets any sessions when you navigate to a new domain using selenium ?

**Comment by diemol** [comment]
Closing as we didn't get more information from the OP after their last comment.
