### ISSUE TITLE
the type org.openqa.selenium.firefox.firefoxdriver is not accessible

### ISSUE THREAD

**Issue by nhhphuong** [SeleniumHQ/selenium#6487]
## Meta -
OS:  
Windows 10

Selenium Version:  
3.14.0

Browser:  
Firefox

Language
Java

I tried to use driver = new FirefoxDriver(); and define a line 
import org.openqa.selenium.firefox.firefoxdriver; but it always displays a message "the type org.openqa.selenium.firefox.firefoxdriver is not accessible"

@ It works well if I used library under 3.14

**Comment by barancev** [comment]
It's FirefoxDriver, not firefoxdriver. Java is case-sensitive.
