### ISSUE TITLE
Unable to set selenoid specific capabilities in C#

### ISSUE THREAD

**Issue by gustafj** [SeleniumHQ/selenium#6497]
## Meta -
OS:  Windows 10 & Linux

Selenium Version:  
Selenium.WebDriver 3.14.0

Browser:  
Firefox & Chrome

Browser Version:  
Firefox 60.0 64-bit
Chrome 66.0 64-bit

## Expected Behavior -
Ability to set capabilities for `selenoid`

## Actual Behavior -
`warning CS0618: 'DesiredCapabilities.SetCapability(string, object)' is obsolete: 'Use of DesiredCapabilities has been deprecated in favor of browser-specific Options classes'`

## Steps to reproduce -
n/a

## Description:

How should capabilities for `selenoid` be set in C# now when `DesiredCapabilities` is deprecated?  
The documentation does not mention this use case as far as I can see.

E.g. enabling VNC, which we currently do using `DesiredCapabilities`
```csharp
var cap = new DesiredCapabilities()
cap.SetCapability("enableVNC", configuration.EnableVNC);
Driver = new RemoteWebDriver(uri, cap);
```
[Selenoid capabilities docs](https://aerokube.com/selenoid/latest/#_special_capabilities)

**Comment by jimevans** [comment]
If it has not already done so, and documentation seems to indicate it hasn’t, the Selenoid project needs to update to become compliant with the [W3C WebDriver Specification](https://w3c.github.io/webdriver/). Once it does, you should be able to use the ‘RemoteSessionSettings` class to create the proper settings JSON payload for transmission to the remote end in the new session command.

Also, please note that, for now, `DesiredCapabilities` is only marked deprecated.  It can still be used for the moment. Ideally, the developers of custom remote ends like Selenoid (or SauceLabs, or BrowserStack, or whatever) would provide client code in whatever languages they would care to support that would plug into the Selenium language bindings.
