### ISSUE TITLE
ignoreProtectedModeSettings does not work on IE-11

### ISSUE THREAD

**Issue by amiya-pattnaik** [SeleniumHQ/selenium#6502]
## Meta -
OS:  

Selenium Version:  

Browser:  

Hi Team,
I am using selenium with JavaScript / Node.js
When i execute my code in IE 11 I get below error. 
ERROR: Unexpected error launching Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the same value (enabled or disabled) for all zones.

Selenium V  3.12.0, IE 11. Could you please help me on this ?
I have below capabilities in my code  IE capabilities
```
  browserName: 'internet explorer',
              platform: '',
              version: '',
              acceptUntrustedCertificates: true,
              ignoreProtectedModeSettings: true,    //only applicable to IE browser
              ignoreZoomSetting: true,              //only applicable to IE browser
              ensureCleanSession: true,
              enableElementCacheCleanup: true,
              IntroduceInstabilityByIgnoringProtectedModeSettings: true,
              maxInstances: '5',
              // specs: [
              //     './test/specs/*.js'
              // ],
          },
```

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

Sorry for slow triaging the issue...
