### ISSUE TITLE
IEDriverServer 2.46 crashing while trying to read the message text of non standard alert

### ISSUE THREAD

**Issue by sroyal5990** [SeleniumHQ/selenium#651]
In the GetDirectUIDialogText() method of Alert.cpp when the program attempts at get the name of message_text_object (hr = message_text_object->get_accName(child_id, &text_bstr)) if the object doesn't have a name then this will fail to get a name and return S_FALSE. This is a problem because the FAILED(hr) function doesn't catch this due to S_FALSE equaling 1 while FAILED only checks for negative numbers. When the program tries to assign text_bstr to text it will crash due to text_bstr being null. It seems like the check to see if getting the accName property failed should include checking for S_FALSE as this also indicates a failure to get the accName property.

**Comment by jimevans** [comment]
Fixed and landed in bb5ca71
