### ISSUE TITLE
MIME type lost when using SendKeys() to upload an xlsx file

### ISSUE THREAD

**Issue by alprema** [SeleniumHQ/selenium#6519]
## Meta -
OS:  Windows 10 x86
Selenium Version:  2.53
Browser:  Chrome
Browser Version:  69.0.3497.92

## Expected Behavior -
SendKeys() (using LocalFileDetector) forwards my file properly to an <input /> element, with its MIME type intact.
## Actual Behavior -
When sending an xlsx file, the MIME type is lost and the client page cannot validate the file using its type.
## Steps to reproduce -
```csharp
var input = _driver.FindElementByCssSelector("input");
input.SendKeys(@"C:\myfile.xlsx");`
```

**Comment by lmtierney** [comment]
This is environment/driver related.

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by lmarchanilmo** [comment]
any workaround or answer to this?
