### ISSUE TITLE
Wrong homebrew command in docs

### ISSUE THREAD

**Issue by ghiculescu** [SeleniumHQ/selenium#6521]
https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#quick-installation

The command is no longer `brew install chromedriver`. It's now `brew tap homebrew/cask && brew cask install chromedriver`.

Info on homebrew casks: https://github.com/Homebrew/homebrew-cask

I don't have wiki edit access so just flagging it here for someone who does.

**Comment by diemol** [comment]
Hi @ghiculescu,

Thanks for pointing it out, I just updated it.
