### ISSUE TITLE
not able to switch windows in safari on mac

### ISSUE THREAD

**Issue by ravi005e** [SeleniumHQ/selenium#6524]
What steps will reproduce the problem?
1. Run any test in safari that generates a pop-up window.
2. Pop-Up window opens and it switches to the window but after that it hangs executing
no further commands.

Selenium version:3.9.1
OS:Windows macos
Browser:Safari
Browser version:12

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/
