### ISSUE TITLE
IEDriverServer crashes with element.getCssValue("z-index")

### ISSUE THREAD

**Issue by JonathanHallKJR** [SeleniumHQ/selenium#6527]
## Meta -
OS: Windows 8.1
Selenium Version:  selenium-java latest (3.14.0) 
IEDriverServer Version(s) - Win32 3.14.0
Browser:  Internet Explorer
Browser Version:  11.0.9600.19101

## Expected Behavior -
Expect the z-index value to be returned and to be able to continue using driver for subsequent calls.

## Actual Behavior -
IEDriverServer crashes a java.net.ConnectException is thrown. 
Attached [log.3.14.txt](https://github.com/SeleniumHQ/selenium/files/2471760/log.3.14.txt)

## Steps to reproduce
The following code triggered the issue.

```java
    public static void main(String[] args ) {
        Handler c = new ConsoleHandler();
        c.setLevel(Level.ALL);
        Logger logger = Logger.getLogger(RemoteWebDriver.class.getName());
        logger.setLevel(Level.ALL);
        logger.addHandler(c);

        System.setProperty("webdriver.ie.driver.loglevel","TRACE");

        final WebDriver driver = new InternetExplorerDriver();
        driver.get("https://www.google.com");
        final WebElement element = driver.findElement(By.xpath("//input[@name='q']"));
        System.out.println(element.getCssValue("z-index"));
        driver.quit();
    }
```

## Analysis
Discovered while upgrading IEDriverServer, so tried a few versions to narrow down the issue.

:heavy_check_mark:  IEDriverServer.exe version 3.8.0  - Works as expected.
:heavy_check_mark:  IEDriverServer.exe version 3.10.0  - Works as expected.
:heavy_multiplication_x: IEDriverServer.exe version 3.11.0 - Replicates issue.
:heavy_multiplication_x: IEDriverServer.exe version 3.14.0 (Latest) - Replicates issue.

:heavy_multiplication_x: The `element.getCssValue` call fails with "z-index" or "zIndex" 
:heavy_check_mark:  but works for other properties (eg "width" which returns a string)

:warning: While investigating the last log message before Exception (`CreateAnonymousFunction`) and debugging the anonymous function with IE Developer Tools. I could see it was returning an integer value, for z-index, changing that to a string meant the call returned without error.

**Comment by jimevans** [comment]
@JonathanHallKJR Thank you for the well-researched issue report. While the repro case supplied doesn't exactly reproduce the issue (on the main Google search page, the element in question returns "auto" for the z-index property, not a numeric value), the thoroughness of the rest of the report enabled a very quick fix. This fix will be released in the next publicly available version, or you can try 3.14.0.14 now, by grabbing [the executable checked into the source tree](https://github.com/SeleniumHQ/selenium/raw/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe)
