### ISSUE TITLE
Holding non-modifier key crashes Selenium in .NET

### ISSUE THREAD

**Issue by Matthiee** [SeleniumHQ/selenium#6528]
## Meta -
OS:  Windows 10
Selenium Version:  3.14.0
Browser:  Any

Unable to hold a non-modifier key down. Because of [SingleKeyAction.cs#L46](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Interactions/SingleKeyAction.cs#L45). Even though it isn't used in my case. I also cannot find anything about holding down keys is only limited to modifier keys. Please correct me if I'm wrong. 

I'm happy to provide a PR that would fix my case. 

## Expected Behavior -
Holds down the specified key in my example the space key. 

## Actual Behavior -
Throws exception:
`key must be a modifier key (Keys.Shift, Keys.Control, Keys.Alt, Keys.Meta, Keys.Command, Keys.LeftAlt, Keys.LeftControl, Keys.LeftShift)`

## Steps to reproduce -

Use this `Actions.KeyDown(Keys.Space);`

**Comment by jimevans** [comment]
For what it’s worth, the `KeyDown` method is clearly documented to be only valid for modifier keys (see the `<exception>` block in the source code documentation, or the [generated API docs](https://seleniumhq.github.io/selenium/docs/api/dotnet/)). I’m not sure changing the API contract at this point is appropriate.

If you need this functionality, and you’re using a remote end that communicates using the W3C WebDriver Specification dialect of the wire protocol (for desktop browsers, any current implementation except Chrome, at the time of this writing), you can use the `ActionBuilder` class instead.

**Comment by Matthiee** [comment]
Hi Jim

I actually considered to use the `ActionBuilder` but it isn't easy to use without the `Actions` class. 

Some examples of issues I have:

- `ActionBuilder.ToActionSequenceList()` is marked as `internal`, workaround, I could use reflection to make it work
- `PauseInteraction` class is marked as `internal`, workaroud, I could recreate the class in my own project

**Comment by jimevans** [comment]
@Matthiee Please help me understand your use case. I'm not necessarily opposed to changing the API on principle, but you'll need to provide me with something incredibly compelling to change the .NET bindings `Actions` implementation to be inconsistent with that provided by every other language binding.

The `ToActionSequenceList` being internal is probably an oversight, left over from when the classes were developed and ready to be used internally, but not ready to be exposed publicly to users. However, strictly speaking, it's not necessary. You could easily do something like this:

    KeyInputDevice keyDevice = new KeyInputDevice();
    ActionSequence keySequence = new ActionSequence(keyDevice, 0);
    keySequence.AddAction(keyDevice.CreateKeyDown(' ');
    keySequence.AddAction(keyDevice.CreateKeyUp(' ');

    List<ActionSequence> sequenceList = new List<ActionSequence>() { keySequence };

While it's not yet possible to manually add a pause in the sequence, I'm correcting that immediately.

**Comment by Matthiee** [comment]
@jimevans Thank you for the changes you made, those will help a lot! 👍 

I don't think I will be able to provide you with something incredibly compelling. 

But I've found a couple of issues on SO regarding this topic. 

- https://stackoverflow.com/questions/36266151/how-to-press-and-hold-non-modifier-key-space-key-using-selenium
- https://stackoverflow.com/questions/33574825/selenium-keydown-for-keys-not-in-the-modifier
- https://stackoverflow.com/questions/17756532/how-to-hold-key-down-with-selenium

Maybe this is something you could consider for a breaking changes release?

**Comment by jimevans** [comment]
We will not be making these changes to this API for .NET.
