### ISSUE TITLE
Error after ./go //javascript/node:selenium-webdriver

### ISSUE THREAD

**Issue by avuong** [SeleniumHQ/selenium#653]
Hello I typed in ./go //javascript/node:selenium-webdriver after cloning the repository and got this error:

Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

Does anyone have any idea how to solve this? 

Thanks

**Comment by jleyba** [comment]
Error mesage comes from the `go` script:
https://github.com/SeleniumHQ/selenium/blob/master/go

I get that warning, but everything still builds:

```
$ ./go //javascript/node:selenium-webdriver
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
(in /Users/jleyba/Development/selenium2)
Copying sources...
Copying library files...
Copying resource files...
Generating documentation...
ALL DONE

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
