### ISSUE TITLE
My IE driver start typing very slow after 3 min of running my tests

### ISSUE THREAD

**Issue by suryap666** [SeleniumHQ/selenium#6530]
Steps to reproduce
1. My test runs more than 5 min
2. After a while, I can see each send key characters

Currently my solution to this problem: Restart the IE driver

Driver.close();
Driver.Quit(); and re-open
Please let me know if any solution for this problem. even in browser stack, my sessions are split due to this issue. 

My operating system: 
Windows 10 64 bit

**Comment by suryap666** [comment]
Hi, I am using a 32-bit driver and my tests are 15 to 20 min long. Sometimes I need to restart the browser 4 times in a test So that Internet Explorer will not crash.

**Comment by Vimal-Raghubir** [comment]
Ok it seems that the tests' time frame is too long for the web driver. I haven't experienced this myself so I don't know how to advise you on this. Sorry.

**Comment by barancev** [comment]
I've made two experiments.
1) Multiple sendKeys operations on the same page:
```
    driver.get("http://localhost/addressbook/");
    for (int i = 0; i < 500; i++) {
      long start = System.currentTimeMillis();
      driver.findElement(By.name("user")).clear();
      driver.findElement(By.name("user")).sendKeys("selenium");
      driver.findElement(By.name("pass")).clear();
      driver.findElement(By.name("pass")).sendKeys("password");
      long end = System.currentTimeMillis();
      System.out.println("" + i + "\t" + (end - start));
    }
```
2) Multiple sendKeys operations with page loading:
```
    for (int i = 0; i < 500; i++) {
      long start = System.currentTimeMillis();
      driver.get("http://localhost/addressbook/");
      driver.findElement(By.name("user")).sendKeys("selenium");
      driver.findElement(By.name("pass")).sendKeys("password");
      long end = System.currentTimeMillis();
      System.out.println("" + i + "\t" + (end - start));
    }
```
And I could not detect serious degradation in both experiments:
![image](https://user-images.githubusercontent.com/617090/56095414-5f3f0c80-5ee5-11e9-9984-49a355579157.png)
![image](https://user-images.githubusercontent.com/617090/56095415-69610b00-5ee5-11e9-9e62-ccd7ff269299.png)

Environment: Windows 10, IEDriverServer 3.141.5.13 (32-bit), IE11

So please provide a scenario that allows to reproduce the issue.

**Comment by suryap666** [comment]
Hi Barancev,

I am using MVC C# application, Filling a lot of information on many pages and a lot of button clicks.

I think you will be able to reproduce if you are clicking buttons.

Thanks for the reply

**Comment by barancev** [comment]
I tried to click buttons too and found no degradation there.

I suppose it can be not Selenium but the application under test that degrades. In any case, we can't fix anything that we can't reproduce. So we need a reproduction scenario.

**Comment by suryap666** [comment]
when we are doing manual testing, there are no issues with internet explorer. 

Thanks any way. I think I am the only one facing this issue. Now we have upgraded our application to React and API services. Also, tests are in chrome. Now no more issues with the new application.  

Thanks everyone :)

**Comment by barancev** [comment]
I bet you never perform manually as many actions as you do in automated tests :)
