### ISSUE TITLE
Manual actions in Selenium during tests

### ISSUE THREAD

**Issue by slawomir0211** [SeleniumHQ/selenium#6533]
Started the test in Selenium in addition in my browser I manually clicked and/or entered the data in the fields.

Is it possible to save the actions that I made manually - actions logs?
I want to know what the user's actions during manual test.

**Comment by dmytrocx75** [comment]
It's hard to answer something as you put questions unclearly. Provide more details on each of your questions.

**Comment by slawomir0211** [comment]
Simple example
During the test Selenium opens a page example.com. Next Selenium click on link to example.com/login. On the login page Selenium enters username and password _-- it is correct test_

Example with manual actions
During the test Selenium opens a page example.com. **Now manually I click on link example.com/about (but on About page isn't link to example.com/login** Next Selenium try to click on link to example.com/login, but can't because link to example.com/login doesn't exist. _-- test failed_
Test failed because I make manual action, so I want to log all manually actions

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
