### ISSUE TITLE
throw Error("Cannot set the selection end");  when setting text in input with type email.

### ISSUE THREAD

**Issue by MintLucky** [SeleniumHQ/selenium#6540]
## Meta -
OS:  any
Selenium Version:  3.5
Browser:  any

## Expected Behavior -
The input field value should change to the appropriate text value entered like it does with other types or nontype input fields.

## Steps to reproduce / Actual Behavior
When attempting to sendKeys (Selenium IDE) on an input field of type email or number, the error of "Cannot set the selection end" is thrown.

## How it is happening
The sendKeys command calls the selection.js goog.dom.selection.setText function which checks for the ability to use selectionStart (via goog.dom.selection.useSelectionProperties_ function), which returns false, and thus throwing the error.

Per the W3 standards (https://www.w3.org/TR/html5/forms.html#the-input-element) the number/email input field types do not have IDL attributes selectionStart/selectionEnd. This is why goog.dom.selection.useSelectionProperties_ function returns false.

## Possible solution
Implement specific logic in selenium atoms for inputs that not have IDL attributes selectionStart/selectionEnd ( email and number )  and not check them for the ability to use selectionStart.

## The same issue was raised over a year ago
https://github.com/SeleniumHQ/selenium/issues/4361
Is there any progress in fixing this issue in WebDriver, Selenium IDE or SideeX ?

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by MintLucky** [comment]
See it now please

**Comment by barancev** [comment]
Is it related to WebDriver or Selenium IDE?

**Comment by MintLucky** [comment]
I'm using SideeX code. SideeX inherited this bug from Selenium IDE. Seems that Selenium IDE inherited this bug from WebDriver. 
In my case it is more related to Selenium IDE, but in common seems this bug is related for both.

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #454](https://github.com/SeleniumHQ/selenium-ide/issues/454) via [**ZenHub**](https://www.zenhub.com/)

**Comment by barancev** [comment]
There is no evidence WebDriver can't handle email or number input fields, there are regression tests for these kinds of inputs and they pass. If you have a specific reproduction scenario using WebDriver please provide it and we'll reopen the issue, maybe there is an edge case. But we can't accept it with "it seems" statement, sorry.

**Comment by corevo** [comment]
@barancev see [here](https://github.com/SeleniumHQ/selenium-ide/issues/454#issuecomment-436181661)
