### ISSUE TITLE
merging few ChromeOptions between themself gives "goog:chromeOptions - args" only from "main"

### ISSUE THREAD

**Issue by Osmyslitelny** [SeleniumHQ/selenium#6541]
## Meta -
OS:  
any
Selenium Version:  
3.8 +
Browser:  
chrome

I wanna merge two instance of ChromeOptions with the different args. As result i didn't get the expected behavior. I'm not sure that my expecting is correct but for me as user was expected that i got new object which would include args from 1st and 2nd instance.

## Expected Behavior -
{ "goog:chromeOptions": 
    {"args": ["one","two"] }
}
## Actual Behavior -
{ "goog:chromeOptions": 
    {"args": ["two"] }
}
## Steps to reproduce -
ChromeOptions one = new ChromeOptions().addArguments("one");
ChromeOptions two = new ChromeOptions().addArguments("two");
two.merge(one).asMap();

## Question
Is it behavior correct or it would be better change it? I got this problem in code when I tried to create RemoteWebdriver. When new session is creating the code perform this asMap() method.
p.s. If change the logic is good idea I can create some MR with improve the asMap with the following idea: If toReturn contains goog:chromeOptions then combine them. Or the 2nd way update some logic for merge method.

**Comment by clever-squirrel** [comment]
This seems to be a more general problem for the MutableCapabilities.  It's not just `goog:chromeOptions` but also any other nested capabilities object.  Sauce Labs for instance takes a 'sauce:options' which is similarly overwritten instead of being merged as expected.

**Comment by barancev** [comment]
Fixed by commit ec9c67b2fb1ec110f51934832fec3cef8a9bf746
