### ISSUE TITLE
Python Selenium Firefox Profile Not Work

### ISSUE THREAD

**Issue by luckynegi100000001** [SeleniumHQ/selenium#6542]
```
from selenium import webdriver

MY_PROFILE = "D:\\FIREFOX_PROFILE"

FFP = webdriver.FirefoxProfile(MY_PROFILE)

print(FFP.profile_dir)
# OUTPUT: C:\Users\ABC\AppData\Local\Temp\****\***
# But it should be OUTPUT: D:\FIREFOX_PROFILE

DRIVER = webdriver.Firefox(firefox_profile = FFP)

print(FFP.profile_dir)
# OUTPUT: C:\Users\ABC\AppData\Local\Temp\****\***
# But it should be OUTPUT: D:\FIREFOX_PROFILE
```

How I user a profile, cookies, caches latter on.
if there are any way to reuse the profile.
I also create `RUN` -> `firefox.exe -p` and create a new profile, but I can't use that.

I am using:

- Selenium Version: 2.53.6
- Python Version: 3.4.4
- Firefox Version: Various(49.0.2 etc)

I also try with latest python 3.7.0 with latest selenium install on that but that also not work :(

**Comment by barancev** [comment]
1) Latest is 3.14, not 3.7
2) It workas as expected, Selenium creates a copy of the specified profile and uses this copy.

**Comment by luckynegi100000001** [comment]
I am using:
    Selenium Version: 2.53.6
    Python Version: 3.4.4
    Firefox Version: Various(49.0.2 etc)

I also try with
    python version 3.7
    Selenium version 3.14.1

not work. Let me provide some understandable docs

**Comment by barancev** [comment]
Hm... Not sure if it's clearly documented...
@AutomatedTester ?

**Comment by luckynegi100000001** [comment]
![screenshot_5](https://user-images.githubusercontent.com/44198067/47017335-c6b51300-d173-11e8-8a4e-496e8d3ffd0a.png)

**Comment by AutomatedTester** [comment]
This seems to be working as intended. It takes the directory you pass in and clones it and uses the clone. If you pass in an empty directory then we are going to copy and use that empty directory.

I am not sure what you think the issue is here?

**Comment by luckynegi100000001** [comment]
I want to save all the profile data in this folder and use that data later when ever I reopen firefox with webdriver

**Comment by barancev** [comment]
@AutomatedTester The issue is that this behavior is not documented in FirefoxDriver class.
