### ISSUE TITLE
Timeout expired waiting for async script

### ISSUE THREAD

**Issue by Shukurdin-Aydarov** [SeleniumHQ/selenium#6546]
OS:  **Window 10**
Selenium Version: **3.6.0**
Browser:  **Internet Explorer**
Browser Version: **11.285.17134.0**
Node version: **8.12.0**
Programming language: **Typescript v3.0**

Hello! I have a several problems with WebDriver.
1. When I execute the following code: 
```typescript 
test('IE: execute async js', async () => {
        setDriverPath();
        const driver = new Builder()
            .forBrowser("ie")
            .build();

        const start = new Date().getTime();
        await driver.executeAsyncScript(() => window.setTimeout(()=> console.log("Hello!"), 500));
        console.log('Elapsed time: ' + (new Date().getTime() - start) + ' ms');
    });

function setDriverPath() {
    const driversFolder = path.join(__dirname, "../drivers");
    if (!process.env.PATH) {
        process.env.PATH = driversFolder;
    }
    else if (!process.env.PATH.includes(driversFolder)) {
        process.env.PATH += ";" + driversFolder;
    }
};

```
I get the following error:
![image](https://user-images.githubusercontent.com/33725995/47062394-fa3d7f00-d1ff-11e8-963e-2e57372c51ad.png)

For Chrome and Firefox, it works well.

2. When I use forceCreateProcessApi(true) Internet Explorer doesn't open the page. Code: 
```typescript 
   test("IE: forceCreateProcessApi", async () => {
        setDriverPath();

        const options = new ie.Options()
            .forceCreateProcessApi(true)
            .ensureCleanSession(true);

        const driver = new Builder()
            .forBrowser("ie")
            .setIeOptions(options)
            .build();

        await driver.get("www.google.com");
    });

```
Link to project: https://github.com/Shukurdin-Aydarov/TestWebDriver

**Comment by aleics** [comment]
I'm also facing this issue when using the Internet Explorer 11 browser, together with protractor. Probably a related issue is: https://github.com/angular/protractor/issues/1999

**Comment by barancev** [comment]
You're using `executeAsyncScript` in a wrong way. Accoring to the documentation, "scripts executed with this function must explicitly signal they are finished by invoking the provided callback. This callback will always be injected into the executed function as the last argument".

So the provided code sample should be corrected like this:
```
await driver.executeAsyncScript(function () { var callback = arguments[arguments.length - 1]; window.setTimeout(function () { console.log('Hello!'); callback() }, 500) });
```
And remember that IE does not support arrow-functions.
