### ISSUE TITLE
"Protected Mode" in the security settings from the Internet Explorer11

### ISSUE THREAD

**Issue by igabrrica** [SeleniumHQ/selenium#6547]
Hallo everybody,

I get always an error when I want to start the Internet Explorer with Selenium.

I already know the cause, why it doesn`t work. Selenium has a Problem with the security settings from my Internet Explorer. 
In the security settings from my Internetexplorer are the protected mode in the four zones (Internet, Local internet, Trusted sites, Restricted sites) different, but when I want to start the Internet Explorer with selenium, they have to be all the same, enabled or disabled.

Now we come to my Problem:
I am working in a company and I asked the administrator to change the "protected mode" for all zones in the security settings to the same value. He has changed the group policies, but we have a enterprise environment and that`s the reason why it still doesn`t work.

Does someone know, how to fix this problem?
Which registry we have to change?

Best wishes

Ibush

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
