### ISSUE TITLE
Grant virtual to RemoteWebDriver

### ISSUE THREAD

**Issue by manhattan918** [SeleniumHQ/selenium#655]
I want to change the behavior by inheriting the `RemoteWebDriver`(C# APIs).
However, the `RemoteWebDriver` has not `virtual`.
Therefore, can not be called as the base method of a subclass.

Is it possible to grant the `virtual` to `RemoteWebDriver`?

**Comment by jimevans** [comment]
I'm going to reject this suggestion. The `RemoteWebDriver` behavior is fairly static, and you will need to provide a very compelling argument of what types of behavior you feel are missing for me to change my mind about it. Prefer composition to inheritance, if you need something like this. You can see the `EventFiringWebDriver` class in the `WebDriver.Support` libraries for an example of how to do this.
