### ISSUE TITLE
driver.get buffer until timeout when access mp4 url

### ISSUE THREAD

**Issue by codenoid** [SeleniumHQ/selenium#6556]
## Meta -
OS:  
Ubuntu 16.04
Selenium Version:  
Python3 Package Selenium==3.14.1
Browser:  
Chrome 69.0
chromdriver 2.41.578700

my code : 

```
print("Access Video")
driver.get("https://video.fcgk6-1.fna.fbcdn.net/v/t42.9040-2/10000000_497712050706420_2670005349141970944_n.mp4?_nc_cat=109&efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ht=video.fcgk6-1.fna&oh=bd61eb2ab91947fa9302c90ed24c9b7c&oe=5BC91565")
print("finish")
```
Expected Result : 

```
Access Video
(browser finish loading page, and i think is should no more than 5 sec)
finish
```

Actual Result : 
```
Access Video
(Buffer for more than 30 seconds and so on until timeout)
```
more info : 

1. the video has been fully loaded but driver.get still buffer
2. i try adding timeout, but it's not solution

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by codenoid** [comment]
hi folks, [link to chromium issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2621)
