### ISSUE TITLE
Selinium Not able to open the website properly in selinium browser getting unable to Identify Your browser

### ISSUE THREAD

**Issue by pradyadav** [SeleniumHQ/selenium#6560]
Hello sir
i am using selenium for automation purpose so i try to open www.whitepages.com using selenium as i am from india  this site is not opening here so i have used the vpn to open the site and in normal chrome and firefox  i am able to see the website properly but when i try use selenium then i am geeing error  which written  

unable to Identify Your browser

![mail](https://user-images.githubusercontent.com/29659630/47215812-5d760f80-d3c0-11e8-8ecd-d5f9f4700009.png)
![shot2](https://user-images.githubusercontent.com/29659630/47215816-60710000-d3c0-11e8-9200-8ca08375b4eb.png)

**Comment by PandaMagnus** [comment]
What are the browser capabilities you're using when instantiating your webdriver?

**Comment by diemol** [comment]
Hi @pradyadav,

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
