### ISSUE TITLE
Nav windows remain in dock after Mojave update

### ISSUE THREAD

**Issue by ssorriba** [SeleniumHQ/selenium#6561]
## Meta -
OS:  MacOS Mojave 10.14

Selenium Version:  3.5.3

Browser:  Google Chrome 

Browser Version:  69.0.3497.100 

So, since i updated to Mojave in my Mac, i noticed that every time i run a test, the window nav that selenium opens remains in the dock after it's finished, like this:

[https://imgur.com/a/vHz2tv3](url)

I'm not sure if it's Selenium, WebDriver or what, but what i'm sure is that this behavior started after the OS update, so it might have something to do with Mojave?

## Expected Behavior -
Once the test is finished, the window nav closes

## Actual Behavior -

Once the test is finished, the window nav closes but it remains in the dock, like in the photo.

**Comment by MarlonCabraca-minted** [comment]
Hi, Im seeing your reported issue, which was the cause?

**Comment by cgoldberg** [comment]
@MarlonCabraca-minted  if you have Chrome icons in your dock, you have instances of Chrome that were not terminated.  Without more information about what you are running, there's really nothing anyone can do here.

**Comment by MarlonCabraca-minted** [comment]
Eclipse tests end as usual, Chrome window closes but icons  still there like if I used ¨keep in dock¨

**Comment by Songyu-Wang** [comment]
Had the same issue. After googling, here is the solution https://www.tekrevue.com/tip/recent-applications-extra-icons-mojave-dock/
It is a new Mac feature...
