### ISSUE TITLE
[Request] Implement By.custom(String) so that we can find elements using AI via Testdotai.

### ISSUE THREAD

**Issue by eabedrapo** [SeleniumHQ/selenium#6562]
## Requirement - 
Expand By class to support a "custom" method accepting the string "`<X>:<label>`" that maps the elements already "trained" with the classifier.

## Background -
During SeleniumConf Chicago I went to Jason Arbon's talk and as many in the audience I got amazed by the whole idea of using AI to find elements in a mobile application using Appium.

So I went to their office hours and asked if they have started any support for Selenium, but their answer was they haven't started anything although it's on their plans to integrate with Selenium as well.

I spent some time searching for any open issues related to this request and I didn't find anything, but if I duplicated somebody's request, feel free to close this one with a reference to that issue.

I noticed that in By.java the java doc reads "_In order to create your own locating mechanisms, it is possible to subclass this class and override the protected methods as required, though it is expected that all subclasses rely on the basic finding mechanisms provided through static methods of this class_".

However, I think that given Appium's last version included a new method to support Test.ai Classifier Plugin, everyone using Selenium would get similar benefits if By class gets a new method implemented by the Selenium community instead of having everyone creating different subclasses to accomplish the same goal.

## References -

Although many of you may have heard Jason's talk at the conference and maybe you're already in touch with him, here I'm adding a few references about the Test.ai Classifier Plugin for Appium:
* Repository in Github: https://github.com/testdotai/appium-classifier-plugin
* Jason's article in Medium: https://medium.com/testdotai/adding-ai-to-appium-f8db38ea4fac?sk
* Jason's talk at the SeleniumConf Chicago: https://youtu.be/qjwbi6ZqYXA?t=12197

## Note about me -

I'm just a user of Selenium (java) and I have been pushing its use to implement our automated UI tests at work since 2012. I heard about Test.ai for the first time at the conference and I got immediately caught by the potential of the tool and I'd love if I could have it implemented for Selenium too.

Of course, I haven't committed a line of code for the Selenium project so I feel a little shy to send this request in the first place, but I think I would be able to help with this if I get some help in setting up my environment with go and getting someone to pair to discuss ideas and reviewing my code.

If you think someone with more experience in the project should implement this new extension, I still want to contribute to the project, so feel free to contact me back with ideas.

Thanks!

**Comment by barancev** [comment]
And what's the proposed implementation?

(Note we're not going to add dependencies on any external library that implements custom search strategies)

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
