### ISSUE TITLE
Files in Selenium-Java-3.14.0.zip shows modified date as “2/1/1985”

### ISSUE THREAD

**Issue by SameerAjitPatil** [SeleniumHQ/selenium#6564]
OS:  Windows 8.1
Selenium Version:  3.14.0

When i opened the zip file of Selenium-Java latest version (3.14.0), i observed that the modified date for all the files is shown as 2/1/1985 !

## Expected Behavior -
Modified date should be the date when latest zip is releases

## Actual Behavior -
Modified date for all files shown as “2/1/1985”.

## Steps to reproduce -
1. Download and open Zip file for latest selenium (selenium-java-3.14.0.zip) available at "https://www.seleniumhq.org/download/"

![image](https://user-images.githubusercontent.com/17757149/47291433-38340c00-d621-11e8-9770-b93551f0434f.png)

**Comment by shs96c** [comment]
This is expected behaviour. We use a build system that guarantees reproducible builds, and part of this process is normalising the timestamps in zip files.
