### ISSUE TITLE
`getRect` failed for AndroidDriver using selenium-webdriver of version 4.0.0-alpha1 (nodejs)

### ISSUE THREAD

**Issue by astappiev** [SeleniumHQ/selenium#6567]
## Meta -
OS:  Windows 10
Selenium Version:  4.0.0-alpha1 (nodejs)
Browser:  Appium Native (Andoid 7 Emulator)

## Expected Behavior -
As both methods `getSize` and `getPosition` were removed from `Window` class in version 4, the only way to get size is to use `getRect` method.
```js
const rect = await driver.manage().window().getRect();
-> {width: 400, height: 600, left: 0, top: 0}
```

## Actual Behavior -
Throws next error:
```js
WebDriverError: Method is not implemented
    at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:585:15)
    at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:533:13)
    at Executor.execute (node_modules\selenium-webdriver\lib\http.js:468:26)
```
Following logs of selenium driver, it sacessfully executes `getSize` method, but fails on `getPosition`. So, I gues it should use position `0:0` when driver is not supported the command.
```
[HTTP] <-- GET /wd/hub/session/5d3a7cf1-9dde-4924-8318-7ef04c75e9d3/window/current/size 200 12 ms - 98
[HTTP] --> GET /wd/hub/session/5d3a7cf1-9dde-4924-8318-7ef04c75e9d3/window/current/position {}
[HTTP] <-- GET /wd/hub/session/5d3a7cf1-9dde-4924-8318-7ef04c75e9d3/window/current/position 501 3 ms - 112
```

## Steps to reproduce -
Create a webdriver for Native app and try to get size of window.

```js
const capabilities = new Capabilities();
capabilities.set('platformName', 'Android');
capabilities.set('deviceName', 'Android Emulator');
capabilities.set('platformVersion', '7.0');
capabilities.set('app', 'http://saucelabs.com/example_files/ContactManager.apk');
capabilities.set('clearSystemFiles', true);
capabilities.set('noReset', true);

const driver = await new Builder()
    .withCapabilities(capabilities)
    .usingServer('http://127.0.0.1:4723/wd/hub')
    .build();

const rect = await driver.manage().window().getRect();
```

## How to fix -
If `GET_WINDOW_POSITION` failed  due to missing method on Driver, just use `{left: 0, top: 0}` or return `getSize` method to `Window` class.

**Comment by barancev** [comment]
Please report this issue to Appium project.
