### ISSUE TITLE
Promise error Raspberry Pi and node.js running headless (no desktop)

### ISSUE THREAD

**Issue by nospam2k** [SeleniumHQ/selenium#6569]
I believe the problem is in part not running Xvfb but not sure how to do that in Node.JS

(node:7794) UnhandledPromiseRejectionWarning: Error: Server terminated early with status 2
    at earlyTermination.catch.e (/home/pi/.node-red/node_modules/selenium-webdriver/remote/index.js:251:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)

var webdriver = require('selenium-webdriver'),
  By = webdriver.By,
  until = webdriver.until;

var firefox = require('selenium-webdriver/firefox');
require('geckodriver');

var firefoxOptions = new firefox.Options();
firefoxOptions.setBinary('/usr/bin/firefox');
firefoxOptions.headless();

const driver = new webdriver.Builder()
   .forBrowser('firefox')
   .setFirefoxOptions(firefoxOptions)
   .build();

driver.get('https://www.google.com');
driver.findElement(By.name('q')).sendKeys('webdriver');

driver.sleep(1000).then(function() {
  driver.findElement(By.name('q')).sendKeys(webdriver.Key.TAB);
});

driver.findElement(By.name('btnK')).click();

driver.sleep(2000).then(function() {
  driver.getTitle().then(function(title) {
    if(title === 'webdriver - Google Search') {
      node.warn('Test passed');
    } else {
      node.warn('Test failed');
    }
  });
});

driver.quit();

**Comment by diemol** [comment]
HI @nospam2k,

It is not clear what you are trying to achieve.

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by nospam2k** [comment]
I'm not sure what else to add. I have you a simple example using Google.Com and the error I get. The key here is that I'm using be a raspberry pi without a desktop.

**Comment by barancev** [comment]
Please provide the full log and especially the full error message.

**Comment by barancev** [comment]
Closing the issue as there is no enough information to act upon.

It is possible that geckodriver crashes. Try to raise an issue on https://github.com/mozilla/geckodriver/issues/, but be prepared to provide an error log anyway.
