### ISSUE TITLE
Error when using ActionBuilder with Firefoxdriver: 'Cannot press more then one button'

### ISSUE THREAD

**Issue by philipfong** [SeleniumHQ/selenium#657]
**Environment:**

Ruby 2.16 on Windows
Selenium WebDriver 2.46.2
RSpec 3.2 with Capybara 2.4.4
Firefox version 38.0.5

**Steps to reproduce:**

I am using the ActionBuilder to complete some rather unconventional dragging and dropping of items within an app that I'm testing.  Here is a trimmed down version of the method I'm using where I'm omitting a few conditional statements that are not relevant to this bug report:

    def drag_to_dashboard(type)
      actionbuilder = page.driver.browser.action
      source = find('.toolbox li', :text => type).native
      actionbuilder.click_and_hold(source).perform
      actionbuilder.move_to(find('h6', :text => 'TOOLBOX').native).perform
      actionbuilder.move_by(90, 0).perform
      actionbuilder.release.perform
    end

The method is designed to find an element, click and hold, drag it to another element, move it to another offset, then finally release the left mouse button.

**Observed behavior:**

When the test example reaches this method, I am getting this error after running rspec:

UnknownError: Cannot press more then one button or an already pressed button.'UnknownError: Cannot press more then one button or an already pressed button.' when calling method: [wdIMouse::down]
[remote server] file:///C:/Users/CoE/AppData/Local/Temp/webdriver-profile20150611-4876-19cmmpj/extensions/fxdriver@googlecode.com/components/driver-component.js:10667:in `FirefoxDriver.prototype.mouseButtonDown'
[remote server] file:///C:/Users/CoE/AppData/Local/Temp/webdriver-profile20150611-4876-19cmmpj/extensions/fxdriver@googlecode.com/components/command-processor.js:12282:in `DelayedCommand.prototype.executeInternal_/h'
[remote server] file:///C:/Users/CoE/AppData/Local/Temp/webdriver-profile20150611-4876-19cmmpj/extensions/fxdriver@googlecode.com/components/command-processor.js:12287:in `DelayedCommand.prototype.executeInternal_'
[remote server] file:///C:/Users/CoE/AppData/Local/Temp/webdriver-profile20150611-4876-19cmmpj/extensions/fxdriver@googlecode.com/components/command-processor.js:12229:in `DelayedCommand.prototype.execute/<'

**Expected behavior**: The method works perfectly fine with ChromeDriver and should work with Firefoxdriver as well

**Comment by p0deje** [comment]
I don't think you're using the action builder right.

Please, try something like this. You should only call `#perform` once.

```ruby
def drag_to_dashboard(type)
  actionbuilder = page.driver.browser.action
  source = find('.toolbox li', :text => type).native
  destination = find('h6', :text => 'TOOLBOX').native
  actionbuilder.click_and_hold(source)
               .move_to(destination)
               .move_by(90, 0)
               .release
               .perform
end

**Comment by p0deje** [comment]
Closing since there has been no response for 20 days.

**Comment by philipfong** [comment]
Hi everyone, just wanted to let you guys know that I've corrected the way I was using actionbuilder, and that I was using it completely wrong.  I'm now able to get the actionbuilder to work properly in all browsers (Chrome, Firefox, IE).  Thank you.

**Comment by om-nishu-trantor** [comment]
@philipfong We assume your corrections came from suggestions from @p0deje ...
If not then please put in the correction/syntax of the way it worked.
Thanks

**Comment by om-nishu-trantor** [comment]
@p0deje I seem to be having same issue...
```ruby
actionbuilder = page.driver.browser.action
source = page.first("#sourceId > div.source.div.class").native
destination = page.find("#destinationId").native
actionbuilder.click_and_hold(source).move_to(destination).move_by(90, 0).release.perform
```
When we perform above, this is obtained 
```ruby
*** Selenium::WebDriver::Error::UnknownError Exception: UnknownError: Cannot press more then one button or an already pressed button.'UnknownError: Cannot press more then one button or an already pressed button.' when calling method: [wdIMouse::down]

nil
```

Using 
```ruby
capybara (2.4.4)
capybara-webkit (1.6.0)
rspec-core (3.3.2)
rspec-rails (3.3.3)
selenium-webdriver (2.47.1)
```

**Comment by philipfong** [comment]
Yes the suggestion made by @p0deje helped solve my issue.  I was calling .perform incorrectly.

Looking at your code, I can't tell why you would be getting that error.  It is nearly identical to mine, except I'm not using webkit I'm using ChromeDriver, IEDriver, and Firefoxdriver.

**Comment by titusfortner** [comment]
@om-nishu-trantor - That test is failing on the #click_and_hold method, which works for other browsers. You should raise this as an issue in the capybara-webkit project.

**Comment by twalpole** [comment]
@titusfortner the error @om-nishu-trantor posted is a Selenium::WebDriver::Error::UnknownError error -- thats not coming from capybara-webkit

**Comment by twalpole** [comment]
@om-nishu-trantor Are you doing an action before that where you didn't release the mouse button?

**Comment by om-nishu-trantor** [comment]
I've written the piece of code I am performing. Before that is just a ```visit this_path``` command to the page.

**Comment by twalpole** [comment]
@om-nishu-trantor if you run just that test alone does it work (with no previous tests being run)?  - I guess its possible a previous test is leaving the mouse down

**Comment by titusfortner** [comment]
The code base throwing the error does not matter. If the code works for every other browser, and especially when the browser with an issue is entirely virtual, the odds are very high that your virtual browser is in a state that isn't able to interact with the selenium feature appropriately.

**Comment by twalpole** [comment]
@titusfortner - It does matter when selenium doesn't interact with capybara-webkit -- A specific test uses either selenium or capybara-webkit --- if this test is throwing a Selenium error then its obviously using the selenium driver and reporting it to the capybara-webkit project doesn't make any sense.  That said yes the report by @om-nishu-trantor does sound like the browser is in a strange state with a mouse button still held down at the start of the test.

**Comment by titusfortner** [comment]
@twalpole - Ah, I was under the misapprehension that capybara-webkit was a similar implementation to Poltergeist, but it is not. There is technically no such thing as a "Selenium Driver" the way that the Capybara community uses it. Selenium is a library that interacts with browser drivers (which capybara-webkit is not). So the real question is...

@om-nishu-trantor - which browser are you using?

**Comment by twalpole** [comment]
@titusfortner I believe because of the "[wdIMouse::down]" at the end of the error message @om-nishu-trantor is using Firefox since thats an interface that appears to only be defined in the firefox driver

**Comment by om-nishu-trantor** [comment]
@titusfortner 
I am running specs in firefox.
No previous specs have been running in the browser. I thought that refreshing the page would do, but to no improvement.
Is there anyway I can bring it back from the strange mouse-down state ?

**Comment by titusfortner** [comment]
I just tested with Firefox on a Mac.
I can replicate your exception when I do:
```
driver.action.click_and_hold(element).click_and_hold(element).perform
```
but not with only one call to the #click_and_hold method
I'm not sure why your test as written thinks the mouse is already being clicked and held.

**Comment by titusfortner** [comment]
@twalpole - #click_and_hold is subsequent calling of session/:session_id/moveto and session/:session_id/buttondown commands. It is implemented in other browsers as well as Firefox.

Actually @om-nishu-trantor you can set ```$DEBUG = true``` before running your tests and look for more than one instance of buttondown getting called.

**Comment by twalpole** [comment]
@titusfortner yes, I was just pointing out the reference to the wdIMouse interface implied Firefox since that name is only defined in the Firefox driver - anyway it's irrelevant now since the fact that the issue occurs when using Firefox has been confirmed by on-nishu-trantor

**Comment by om-nishu-trantor** [comment]
I've been able overcome this error by using the following code :-
```
builder = page.driver.browser.action
source_slide = page.all("#sourceId > div.source.div.class")[5]
_source = source_slide.native
target = page.find("#destinationDiv").native

builder.click_and_hold(_source)
builder.move_to(target)
builder.release.perform
builder.perform
```
But problems are with jQuery sortable and Capybara, do not belongs to here.
But still, this should be reasoned out why ```.click_and_hold(source).move_to(destination).move_by(90, 0).release.perform``` do not works but same broken down into steps works.
