### ISSUE TITLE
IEServerDriver PageLoadTimeout after closing one ModelDialog triggers a new ModelDialog.

### ISSUE THREAD

**Issue by JonathanHallKJR** [SeleniumHQ/selenium#6574]
## Meta -
OS: Windows 8.1
Selenium Version: selenium-java latest (3.14.0)
IEDriverServer Version(s) - Win32 3.14.0
Browser: Internet Explorer
Browser Version: 11.0.9600.19101

## Expected Behavior -

Expect the disappearance of the Modal Dialog to allow the test to continue, even if the application under test immediately opened a new Model Dialog.

## Actual Behavior -

Clicking a button that closes the dialog eventually fails with a `TimeoutException: Timed out waiting for page to load`. 

Looking in the [IEServerlog.log](https://github.com/SeleniumHQ/selenium/files/2513650/IEServerlog.log) it repeats a loop around `HtmlDialog::Wait`

```
iedriver\iecommandexecutor.cpp(801) Creating wait thread with deferred response of `{ "value" : null }`
iedriver\iecommandexecutor.cpp(558) Entering IECommandExecutor::WaitThreadProc
iedriver\iecommandexecutor.cpp(181) Entering IECommandExecutor::OnWait
iedriver\iecommandexecutor.cpp(890) Entering IECommandExecutor::GetCurrentBrowser
iedriver\iecommandexecutor.cpp(896) Entering IECommandExecutor::GetManagedBrowser
iedriver\htmldialog.cpp(126) Entering HtmlDialog::Wait
iedriver\htmldialog.cpp(100) Entering HtmlDialog::IsValidWindow
iedriver\htmldialog.cpp(188) Entering HtmlDialog::GetTopLevelWindowHandle
iedriver\htmldialog.cpp(193) Entering HtmlDialog::GetActiveDialogWindowHandle
iedriver\htmldialog.cpp(188) Entering HtmlDialog::GetTopLevelWindowHandle
iedriver\iecommandexecutor.cpp(829) Entering IECommandExecutor::IsAlertActive
iedriver\htmldialog.cpp(193) Entering HtmlDialog::GetActiveDialogWindowHandle
iedriver\htmldialog.cpp(188) Entering HtmlDialog::GetTopLevelWindowHandle
iedriver\iecommandexecutor.cpp(843) No alert handle is found
iedriver\iecommandexecutor.cpp(801) Creating wait thread with deferred response of `{ "value" : null }`
[...]
```
## Steps to reproduce -

See [Attached code](https://gist.github.com/JonathanHallKJR/adefa242cbdda98b30ba48ad82b4b3d3#file-seleniumbugreport-java-L51)

While running it serves 3 pages:
* http://localhost:8080/ - main Page with test button and textarea for log messages.
* http://localhost:8080/popup/promptWindow - first dialog.
* http://localhost:8080/popup/areYouSure - second dialog.

Expected Flow would be:
1. User clicks Test button on the main page.
  * which opens a first dialog with `window.showModalDialog` passing a callback function in via `window.dialogArguments[0]`.
2. User clicks a button on the first dialog. 
  * which triggers calls to `window.close()` then `callback(answer)`
  * first callback logs the answer and opens the second modal dialog. 
  :warning: NOTE: When running in automation this is where it fails to detect the first dialog has gone.
3. User clicks a button on the second dialog.
  * which triggers calls to `window.close()` then `callback(answer)`
  * second callback logs the answer.

## Analysis
Originally discovered while testing a real application in which the automation would fail during a `driver.getWindowHandles()` (after the `element.click()`).  The IEDriverServer logs then showed a similar `HtmlDialog::Wait` loop above with a different deferred response.

:warning: If you catch the TimeoutException and call `driver.getWindowHandles()` there are **three** window handles returned despite only two being visible to the user.

It may be possible to fix this in the application under test since the either of the following prevent replication (however the code as is works for humans and is only causing problems for automation).
1. If the callback doesn't trigger a new `window.showModalDialog`.
2. If the callback is called before `window.close()` (but two dialogs are open at the same time)

**Comment by jimevans** [comment]
The root cause of the issue is that the close behavior of `showModalDialog` windows has changed in IE. Instead of immediately destroying the parent window of the content window (which should have the window class `Internet Explorer_TridentDlgFrame`), IE instead re-parents the content window to a hidden one with the window class `Internet Explorer_Hidden`. For our purposes, if the parent window of the content window is the latter, it is for all intents and purposes for us, closed.

I've added a change in 150b032 that addresses the issue when I run (and adapted version of) the provided code locally. This is checked into the project tree as [a prebuilt binary](https://github.com/SeleniumHQ/selenium/blob/master/cpp/prebuilt/Win32/Release/IEDriverServer.exe). @JonathanHallKJR, please feel free to check that out and see if it works. I'm not going to automatically close this issue until someone's had a chance to check out the change and see if it actually resolves the issue.

**Comment by JonathanHallKJR** [comment]
:heavy_check_mark:  The prebuilt IEDriverServer 3.14.0.15 fixes my issue. 

I re-ran my replication code and and the test my application under test the new driver worked for both.

Thank you @jimevans for such a quick turn around on my issues.
