### ISSUE TITLE
SendKeys not entering text on textarea fields.  However, it works fine for input tag fields.

### ISSUE THREAD

**Issue by sksajjan** [SeleniumHQ/selenium#6576]
Windows 10 Selenium 3.4 IEDriver 3.4 64x - not entering text on textarea fields
Windows 10 Selenium 3.4 IEDriver 3.14 64x - - not entering text on textarea fields
Windows 10 Selenium 3.4 IEDriver 3.4 32x - Entering text on textarea however, having issue in closing browser driver.
Windows 10 Selenium 3.4 IEDriver 3.14 32x - Entering text on textarea however, having issue in closing browser driver.

**Comment by sksajjan** [comment]
however, it works fine if i use Javascript like document.getElementsByClass('classname').textcontent='value'

**Comment by jimevans** [comment]
What version of Windows? The Windows 10 October 2018 Update shipped with a bug that manifests when closing browser windows. Microsoft has a fix for the issue, but it has yet to release it in a hotfix. I am hopeful it will make it into the next rolling update.

**Comment by sksajjan** [comment]
I am on Windows 10 version 1803 (OS Build 17134.345), which appears to not have the october update

**Comment by barancev** [comment]
1) Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

2) What issue in closing browser driver do you have?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
