### ISSUE TITLE
I have a set of selenium testcases which gets executed every night as they are scheduled in jenkins. I added a set of new testcases to the existing framework , committed them. i dont see them getting executed along with other cases.

### ISSUE THREAD

**Issue by ChaitA** [SeleniumHQ/selenium#6577]
## Meta -
OS:  
Windows 10
Selenium Version:  

Browser:  
FireFox

I have a set of selenium testcases which gets executed on every nightly as they are scheduled in jenkins. I added a set of new testcases to the existing framework , committed them. i dont see them getting executed along with other cases.

I get the below error on jenkins for the newly added testcases,
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: '199-7-165-32', ip: '199.7.165.32', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Windows\proxy\rust_mozprofile.PIe0SoKZEyx3, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0, platformVersion=10.0, moz:processID=7880.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt, moz:webdriverClick=true}]
Session ID: 3999a382-8958-4d71-83c9-9e6bcf83da44
*** Element info: {Using=id, value=sso-username-input}

**Comment by rkhaneds** [comment]
Did the test went fine in your local machine? I would check in local before i push the code, are you running test in grid on the night builds?

**Comment by diemol** [comment]
Hi @ChaitA, 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
