### ISSUE TITLE
I was wondering about the function of the element sendkeys(keys.Enter), the runtime of the automate test at the stage of this element runs in repetitive errors, and the cause of the error is that this element works 2 times.

### ISSUE THREAD

**Issue by LILI1363** [SeleniumHQ/selenium#6587]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by diemol** [comment]
Hi @LILI1363,
 
This seems more like a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
