### ISSUE TITLE
After running 20 success tests, I failed to run my 21 tests one by one

### ISSUE THREAD

**Issue by LILI1363** [SeleniumHQ/selenium#6588]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:

**Comment by LILI1363** [comment]
I am doing SELENIUM auto testing
The automatic test runs in low-level performances without fail, but in repetitive performances it's defeated.

**Comment by LILI1363** [comment]
For example, in order to make sure my test is working properly, I need to run a repetitive test of my own
But what happens is that if I've tested 20 times in the run, then the result is that 19 times the test passes and 1 time the test fails.
I do not understand why

**Comment by LILI1363** [comment]
> need more info. please fill out the issue template.

For example, in order to make sure my test is working properly, I need to run a repetitive test of my own
But what happens is that if I've tested 20 times in the run, then the result is that 19 times the test passes and 1 time the test fails.
I do not understand why

**Comment by cgoldberg** [comment]
please fill out the issue template
