### ISSUE TITLE
Selenium does not set firefox profile - python 

### ISSUE THREAD

**Issue by digiboons** [SeleniumHQ/selenium#6592]
System
windows:10
Selenium:3.14
Python:3.7
Gecodriver:0.23

Expection:
Open the firefox with test profile

Issue:
Open the firefox with default profile
Create a temp profile folder to temp folder 

Code Block

```
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from selenium import webdriver

fp = FirefoxProfile("C:\\Users\\<USER>\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\ji8rbij6.test")
browser = webdriver.Firefox(firefox_profile=fp)
```

Has anyone have any idea ! 

Thanks in Advance

**Comment by digiboons** [comment]
Extra information 

the configuration option below works for assigning profile to geckodriver but this time it refuses connection

Expection:
Open the firefox and remote control

Happining:
Open the firefoxand connection error

```
from selenium.webdriver.firefox.options import Options

options.add_argument("-profile")
options.add_argument("C:/Users/<USER>/AppData/Roaming/Mozilla/Firefox/Profiles/ji8rbij6.test")

browser=webdriver.Firefox(options=options)
```

Thanks in Advance

**Comment by cgoldberg** [comment]
`options` should be an instance of `selenium.webdriver.firefox.options.Options()`.. where are you creating it?

**Comment by digiboons** [comment]
Sorry about code,i missed a line there.It is like this actually .

```
from selenium.webdriver.firefox.options import Options

options=Options
options.add_argument("-profile")
options.add_argument("C:/Users/<USER>/AppData/Roaming/Mozilla/Firefox/Profiles/ji8rbij6.test")

browser=webdriver.Firefox(options=options)
```

**Comment by earendil** [comment]
It looks like you are not setting the profile like it's meant to be done through Options.

Try that:
`from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from selenium import webdriver

options=Options()
fp = FirefoxProfile("C:\\Users\\<USER>\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\ji8rbij6.test")

options.profile(fp)

browser=webdriver.Firefox(options=options)`
