### ISSUE TITLE
after driver.mange().setTimeouts() and driver.get(url) will get UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by tp6g04jp6** [SeleniumHQ/selenium#6594]
## Meta -
OS:  win10
Selenium Version:  nodejs 4.0.0-alpha.1
Browser:  chrome

Browser Version:  

## Expected Behavior -
```javascript
(async function() {
    let target = 'https://tieba.baidu.com/p/5887088983'
    const chrome = require('selenium-webdriver/chrome')
    const webdriver = require('selenium-webdriver')
    const { Builder, By, Key, until } = require('selenium-webdriver');
    let driver = await new Builder()
        .forBrowser('chrome')
        .build()
    await driver.manage().setTimeouts({ implicit: 0, pageLoad: 3000, script: 3000 })
    await driver.get(target)
    console.log(1234)
    await driver.quit()
}())
```
Because target url takes too long to load, I set pageLoad parameter to 3000 seconds to interrupt this page loading.
I expect it will console 1234 after page loading, but it didn't.
And I get an  UnhandledPromiseRejectionWarning.

```javascript
(node:169916) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: timeout
  (Session info: chrome=70.0.3538.77)
  (Driver info: chromedriver=70.0.3538.16 (16ed95b41bb05e565b11fb66ac33c660b721f778),platform=Windows NT 10.0.17134 x86_64)
```

## Actual Behavior -
I don't know how to do if I want to interrupt or set limit for a web page which takes too long to load in NodeJS.

**Comment by diemol** [comment]
Hi @tp6g04jp6, please have a look at https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs 

If you have more questions, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by tp6g04jp6** [comment]
Hi, @diemol,
Thank you for the information.
