### ISSUE TITLE
Edge WebDriverException: Cannot start the driver service on http://localhost:64301/

### ISSUE THREAD

**Issue by SCarlAdams** [SeleniumHQ/selenium#6598]
OS:  
Windows 10
Selenium Version:  
.net Selenium.WebDriver package 3.14.0

MicrosoftWebDriver:
Release 17134 Version: 6.17134 | Edge version supported: 17.17134

Browser:  
Microsoft Edge

Browser Version:  
Edge 41.16299.15.0

Language:
C#

Expected Behavior -
Create a webDriver instance for Microsoft Edge.

## Actual Behavior -
OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:64301/

## Steps to reproduce -
// path to MicrosoftWebDriver in system path.

// First Attempt:
EdgeDriverService service = EdgeDriverService.CreateDefaultService(@"C:\public\data\trunk\AutomatedTesting\eBusinessSeleniumTest\packages\currentEdgeDriver");
WebDriver = new EdgeDriver(service);

// second attempt:
 WebDriver = new EdgeDriver();

Both have exactly the same results.

**Comment by jimevans** [comment]
@SCarlAdams This sounds suspiciously like a mismatched driver executable (browser version 16299, but the executable supports 17134). When you update to the Windows 10 October 2018 Update, the problem goes away, because the driver is shipped as part of a feature of the OS.

**Comment by SCarlAdams** [comment]
Thanks Jim. That gives me a very good avenue!

**Comment by barancev** [comment]
Have the upgrade resolved the issue?

**Comment by SCarlAdams** [comment]
Sorry I have not replied back. Things happen. But because of issues the
organization is not installing the October 2018 update. I will wait for the
next one and see.

**Comment by barancev** [comment]
@SCarlAdams Any news on the issue?

**Comment by SCarlAdams** [comment]
On govt. Furlough, so no.

**Comment by barancev** [comment]
I'm going to close the issue for now because we can't do anything on Selenium side to fix it. You have to upgrade the driver provided by Microsoft.
