### ISSUE TITLE
Incorrect version progression on newest release

### ISSUE THREAD

**Issue by mtrea** [SeleniumHQ/selenium#6607]
The last "full" release was https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.14.0

2 days ago, https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.141.0 was created. It looks like this version number is incorrect; perhaps it was supposed to be 3.14.1.

**Comment by jimevans** [comment]
This is fully intended and deliberate, in keeping with successive digits of pi (as noted in the CHANGELOG for [Java](https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG) and [.NET](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG). While the project development team does take the project’s code seriously, we also try to have a sense of humor about things. Joking about pi might not be good humor, but it’s humor nonetheless.

**Comment by joshbruning** [comment]
I assume that the next version will be 3.142? Will an upcoming version be "3.15", "3.142", "3.1415"? "4.0beta1" or "salami"? For context, we have some automation that relies on version ordering; would be nice to clarify what the technical constraints are on version choice.

**Comment by jimevans** [comment]
@joshbruning The intent is for this release to be the final 3.x release, so we _hope_ the next public (non-beta) release will be 4.0.

**Comment by SiKing** [comment]
I would just like to request: If my pom.xml has:
```
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-java</artifactId>
  <version>LATEST</version>
  <scope>test</scope>
</dependency>
```
whatever the "next" version is, please make sure things still work as intended.

**Comment by phoet** [comment]
i loughed. not.
