### ISSUE TITLE
system memory leak: when no driver.quit() is executed against a InternetExplorerDriver or ChromeDriver (Java)

### ISSUE THREAD

**Issue by DaveBrad** [SeleniumHQ/selenium#661]
Description
===========
- when a testcase executes and the driver.quit() is not executed (crashes before completion) the IE and Chrome drivers leave conhost.exe and IEDriverServer.exe/ChromeDriver.exe processes around (about 18MB the pair on Win7).

- The test case is valid, but if were to fail then would result in processes being hung. The closure of the browser windows manually does not cause a clean up for IE and Chrome.

Consideration
=============
Firefox driver does not have this issue. When the FF browser is manually closed the processes used are closed out and terminated.

Environment
===========
- WIN7
- Java 8
- Netbeans 8.0.2
- Selenium 2.46.0 installed (netbeans server side plugin, download of drivers from Selenium wbe links etc)

Why this is a problem
=====================
When test cases are run there is a likelyhood that things will fail. When this happens there should be a good cleanup of any processes that were created by WebDrivers. Alternatives require the testcase code to write explicit code to manage around the bad/lack-of driver cleanup. The fact that manually closing the driver launched windows results in the processes remaining is of concern as a system memory leak via "conhost processes". 

This is not a netbeans issue as FF works, but IE and Chrome have the issue. Its the same code and environment for each run in the testcase and in netbeans. Only the drivers are different.

I expect to be using Netbeans, Selenium2, TestNG, and an additional test framework for capturing HTML object test data and converting into Java testdata code. Thus, a repeat-able set of dynamic data for different browsers may be compiled. With 1000's of TCs and a potential for a memory leak like this (cannot be cleaned up except by explicit TC code) is a major concern.

Testcase code
=============
package org.sel;

import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.dictionary.DictSelector;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.opera.OperaDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Main {
   /**
    * @param args the command line arguments
    */
   public static void main(String[] args) {

      // Create a new instance of the XXXX driver
     String browser = "xxxx";
      browser = "ie";
//      browser = "firefox";
//    browser = "opera";   // not working
//      browser = "chrome";

      WebDriver driver = null;

      if (browser.equals("ie")) {
         driver = new InternetExplorerDriver();

      } else if (browser.equals("opera")) {
         System.setProperty("webdriver.opera.driver",
           "C:\\Program Files (x86)\\Opera\\launcher.exe");
         driver = new OperaDriver();

      } else if (browser.equals("firefox")) {
         driver = new FirefoxDriver();

      } else if (browser.equals("chrome")) {
         System.setProperty("webdriver.chrome.driver",
           "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chromedriver.exe");

         driver = new ChromeDriver();

      }
      try {
         Thread.sleep(1000);
      } catch (InterruptedException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
      }
      // load the site page to test
      driver.get("www.google.com");

      // driver.quit();   // edited out during testcase writing
    }
}

**Comment by lukeis** [comment]
The only reason this happens to work in Firefox is because the server listening for commands is run in an extension and is apart of the browser process. 

We will not be changing the design of chromedriver (which is actually a separate project) nor of IEDriverServer. You should be cleaning up the driver (calling quit) even when the test fails or the browser crashes. This is akin to always calling File.close or SocketConnection.close.

**Comment by DaveBrad** [comment]
Understand position and response, shame though. 

Being new to Selenium (but not programming etc) I've relied on the few examples provided. They do not indicate that this problem needs to be addressed by the user of selenium. In fact, the www.google.com example has the explicit driver.quit code, but no example which shows that 
user's need to code the quit into clean up.

I guess the driver.quit is not the best choice of terms as I assumed this meant quit (exit) browser. Where in fact it is close and stopClient of the "WebDriver". The driver.close really doesn't appear 
to do anything. (The newness of Selenium). 

Your akin statement is good and understood. However, a test framework vs an application needs to be smarter in my view. Applications have got the "language" framework to catch bad programming. 

Unfortunately when the driver.quit was being used, there is a console message saying things are forced which doubled my concern:

>>Jun 14, 2015 8:43:29 PM org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder

>>INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess

$SeleniumWatchDog@9e7ee8
>>>>>>AFTER QUIT 

this also had many issues and forum questions. So an expected driver.quit produces an "ERROR" (a red colored INFO actually). So I looked at things more closely and found "holes?" in Selenium (IMHO).

I too have developed test frameworks and found that I needed to build automatic cleanup API's so the user's explicitly knew they had to do some thing to ensure resources were cleaned up. (In fact, throwing an Exception further reinforced the need and pointed them in the right direction.)

Thank you for your quick response. I do not necessarily agree with the response but appreciate as it provides a position to work with. Also, thank you for your volunteer work on Selenium.

**Comment by barancev** [comment]
1) Selenium is NOT a testing framework, it is a browser driver. Yes, you're right, a user should use a testing framework abilities to perform cleanup (call driver.quit()).

2) As for the second mentioned problem (error message) see issue #614
