### ISSUE TITLE
Documentation: Proxy depreciation warning message references are cyclical (Python)

### ISSUE THREAD

**Issue by crutledge** [SeleniumHQ/selenium#6610]
We get a warning message when using set_proxy() method.
https://github.com/SeleniumHQ/selenium/blob/8a0ef8d205cedbce7c0f11db0d5c6b933d66e586/py/selenium/webdriver/firefox/firefox_profile.py#L184-L189

We are advised that this method is being depreciated and to reference the Driver object. Driver object is vague, but if we look at RemoteWebDriver we're told to use the above code.
https://github.com/SeleniumHQ/selenium/blob/8a0ef8d205cedbce7c0f11db0d5c6b933d66e586/py/selenium/webdriver/remote/webdriver.py#L142-L145

Some clarification needs to be done here as the two references are cyclical. If you look at Firefox/WebDriver object the proxy parameter has documentation about about connecting to the Firefox browser, not the proxy settings that the browser will be using.

**Comment by AutomatedTester** [comment]
I am not sure why you think this is cyclical. The Driver one should have the same message as the profile that you should use `FirefoxOptions`.
