### ISSUE TITLE
Seleium Can not Lauch Chrome Browser on Apache via mod_wsgi 

### ISSUE THREAD

**Issue by GoTop** [SeleniumHQ/selenium#6618]
I am developing a Django Project. I use a view named test_seleium_view() to lauch a Chrome Browser by Seleium. For demonstration purpose, my code is as simple as below:

```
#urls.py
# coding=utf-8
from __future__ import unicode_literals, absolute_import
from django.conf.urls import url
from .views import *

urlpatterns = [url(r'^test_seleium$',test_seleium_view,name='test_seleium'),]
```
```
#test_seleium.py
# coding=utf-8
from __future__ import unicode_literals, absolute_import
import time
from django.shortcuts import render_to_response
from selenium import webdriver

def test_seleium_view(request):
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_argument("--start-maximized")
    chrome_options.add_argument('--disable-extensions')
    CHROME_DRIVER_PATH = r"C:\Program Files (x86)\chromedriver\chromedriver_win32_v2.43.exe"
    driver = webdriver.Chrome(executable_path=CHROME_DRIVER_PATH, chrome_options=chrome_options)

    driver.get('http://www.google.com')
    time.sleep(5)
    driver.quit()

    return render_to_response('result.html',{'text': "success"})
```
When I visit http://127.0.0.1:8000/app_name/test_seleium on Django development server, everything is working fine, Seleium lauch a Chrome browser then open http://www.google.com wait for 5 seconds then close Chrome browser.

Then I take this Django project to my virtual machine(VMware Workstation, win 7 64bit installed) which installed Apache and mod_wsgi, when I visit http://my_vmware_virtual_host_ip:8000/app_name/test_seleium, it doesn't lauch Chrome browser, but after a while, the page show the text "success",just like test_seleium_view() had ran successfully, and there is a chrome.exe process on windows 7 background.

-->

## Meta -
OS:  
Windows 7 64bit on VMware Virtual Machine
VMware Workstation 15.0.0 build-10134415

Selenium Version:  
Selenium 3.14.1

Browser:  
Chrome  70.0.3538.77 64bit

Other Software:
chromdriver win32_v2.43，win32_v2.42
Apache 2.4.37 Win64
mod_wsgi 4.6.5+ap24vc14-cp36-cp36m-win_amd64
python 3.6.4 64bit
Django 2.0.7

## Expected Behavior -
In VMware virtual machine, when I open the url reffer to the Django View on a Chrome Browser, A new Chrome Browser is open then it open Google.com wait for 5 seconds then Chrome Browser will close, and the Django view page show text "success".

## Actual Behavior -
when I open the url reffer to the Django View on a Chrome Browser, nothing happen, no Chrome browser open, but after 5 seconds the Django view page still show text "success"

**Comment by cgoldberg** [comment]
does your VM have a display server?

**Comment by GoTop** [comment]
> does your VM have a display server?

I intalled VMware Workstation on my local PC(windows 7 64bit), so what is  display server?

**Comment by diemol** [comment]
@GoTop A browser needs either a physical or a virtual display (like Xvfb). Since you expect to see the browser opening, you need to configure a display for that process so the browser is visible.

From the description you provide, it looks like the application is running without a configured display. Therefore, I will close this issue since it is more a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
