### ISSUE TITLE
Message: Can not connect to the Service chromedriver

### ISSUE THREAD

**Issue by rbnali** [SeleniumHQ/selenium#6623]
## Meta -
OS:  MacOS Sierra 10.12.6
Selenium Version:   3.141.0
Browser:  Chrome 

Browser Version:  ChromeDriver 2.43

## Expected Behavior - Open Chrome driver
```
from selenium import webdriver
browser = webdriver.Chrome()
browser.get('http://seleniumhq.org/')
```
## Actual Behavior - ERROR

I always get the following error
```
WebDriverException: Message: Can not connect to the Service chromedriver
```

I also tried
```
from selenium import webdriver
browser = webdriver.Chrome(PATH_TO_CHROME_DRIVER)
browser.get('http://seleniumhq.org/')
```
with chromedriver in my work folder, and chromedriver in my /usr/local/bin/ but it still doesn't work....

Can someone help?

**Comment by AutomatedTester** [comment]
Can you put the actual code that you are using. It looks like you are telling chrome bindings to speak to firefox from these messages

**Comment by rbnali** [comment]
Hi David,

Actually, chromedriver and geckodriver are both not working.

Here is the code for Firefox:
```
from selenium import webdriver
browser = webdriver.Firefox(PATH_TO_GECKODRIVER)
browser.get('http://seleniumhq.org/')
```

**Comment by barancev** [comment]
"not working" is a zero-information statement. Show the execution log and the error messages.

**Comment by rbnali** [comment]
I get exactly the same error:

```
---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-37-a8c9bcf82007> in <module>()
      1 from selenium import webdriver
----> 2 browser = webdriver.Firefox()
      3 #browser.get('http://seleniumhq.org/')

~/anaconda3/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py in __init__(self, firefox_profile, firefox_binary, timeout, capabilities, proxy, executable_path, options, service_log_path, firefox_options, service_args, desired_capabilities, log_path, keep_alive)
    162                 self.profile = FirefoxProfile()
    163 
--> 164             # disable native events if globally disabled
    165             self.profile.native_events_enabled = (
    166                 self.NATIVE_EVENTS_ALLOWED and self.profile.native_events_enabled)

~/anaconda3/lib/python3.6/site-packages/selenium/webdriver/common/service.py in start(self)
    102                 raise WebDriverException("Can not connect to the Service %s" % self.path)
    103 
--> 104     def assert_process_still_running(self):
    105         return_code = self.process.poll()
    106         if return_code is not None:

WebDriverException: Message: Can not connect to the Service geckodriver
```

**Comment by barancev** [comment]
The log looks corrupted, it points to the wrong lines of code...

1) What geckodriver version do you use? What browser version?
2) Can you verify presense of 'geckodriver' process while the tests are waiting for connection?
3) Do you have a firewall or VPN or any other network software that can block or redirect connections?

**Comment by rbnali** [comment]
Hi @barancev 

- Geckodriver version: v0.23.0
- Firefox version: 63.0.1 
- No VPN / Firewall

**Comment by barancev** [comment]
Can you verify presense of 'geckodriver' process while the tests are waiting for connection?

**Comment by rbnali** [comment]
Here is what I have in my geckodriver.log:
```
1541514049431	geckodriver	INFO	geckodriver 0.21.0
1541514049437	geckodriver	INFO	Listening on 127.0.0.1:52781
1541514114009	geckodriver	INFO	geckodriver 0.21.0
1541514114018	geckodriver	INFO	Listening on 127.0.0.1:52836
# over and over
```

**Comment by rbnali** [comment]
@vviers 

Is chromedriver in your '/usr/bin' folder? If yes, try moving it to '/usr/local/bin' .This solved my issue!

**Comment by vviers** [comment]
Yes it is in `usr/local/bin`. Could it be a network issue? Some sort of port that is blocked?
I am working from uni on the university network.

**Comment by rbnali** [comment]
I don't think so. If you want to check, share the connexion with your phone and try again.

**Comment by TopKeingt** [comment]
Hi, I'm using selenium in one of my project. I having the same issue as well. I'm using window 10 with 
- chromedriver v. 73.0.3683.68
- Google Chrome v.73.0.3683.86
- Python 3.6.5

the code: 
```python
 from selenium.webdriver import Chrome
 browser = Chrome(executable_path="/path/to/chromedriver.exe")
```
above code hanged for a while and then produce the same error output: `Message: Can not connect to the Service chromedriver`.

And some suggestion like add `127.0.0.1   localhost` to `/etc/hosts` did not solve my problem.

**Comment by xiaolin-guo** [comment]
I have the same problem too. 
Chromedriver path in $PATH, I tried to add 127.0.0.1 localhost in C:\Windows\System32\drivers\etc\hosts,
it didn't work as after reboot I lost my internet connection.

Would anyone help, thanks!

Windows 10 x64
Python 3.7.0
Chrome Driver: 73.0.3683.68 (latest)
Selenium: 3.141.0 
Chrome: 73.0.3683.86 (latest)

Code:
from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://www.python.org")

Output:
Traceback (most recent call last):
  File "Test.py", line 5, in <module>
    driver = webdriver.Chrome()
  File "C:\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service chromedriver

**Comment by TopKeingt** [comment]
I've solved the issue after few random researches and installation. However, I could not really know which that solved my issue but here are all researches that I used (for chromedriver in window 10):
- Reinstall chromedriver using [CHOCO](https://chocolatey.org/) (it will automatically add to PATH) ([selenium's quickstart](https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#quick-installation))
- Remove any duplicated chromedriver.exe ([github's issue](https://github.com/flavorjones/chromedriver-helper/issues/44#issuecomment-358743719)).
- Change from public to private wifi 
- add `os.environ["webdriver.chrome.driver"] = "C:\path\to\chromedriver.exe"` before call `webdriver.Chrome()` according from [this stackoverflow question](https://stackoverflow.com/a/8259152/7668944)

**Comment by barancev** [comment]
@rbnali As far as I see from the comments you've resolved the issue, right?

Moving an executable file to a different location could fix it if you had multiple chromedriver versions in PATH, and an outdated one had higher priority. And when you put a newer version to a "proper" place it becomes the first in priority list.

So I'm going to close this report as it's an environment issue and there is nothing to fix in the code.

**Comment by chenhb-zte** [comment]
anyone found the way for this issue?  I saw the chromedriver.exe was running, but can not connect.

**Comment by xiaolin-guo** [comment]
> anyone found the way for this issue? I saw the chromedriver.exe was running, but can not connect.

I didn't find a way to solve the issue on Windows, I just switch to MAC and it worked on it.....

**Comment by TopKeingt** [comment]
> anyone found the way for this issue? I saw the chromedriver.exe was running, but can not connect.

Hey @chenhb-zte, Maybe try to switch to private wifi (if you connected to public wifi) or check for correct version for both chrome and chromedriver. 

Also you can check if you can connect to chromedriver via Chrome by running chromedriver:
__chromedriver's message when running__:
`Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.`

and connect it with `localhost:{chromedriver's port}` my case is `localhost:9515`. If you see `unknown command:` then you actually connected to chromedriver.

Those methods are what I did to fix my chromedriver's issue

**Comment by chenhb-zte** [comment]
@TopKeingt  Thanks. I tried the way which you provided,  localhost:9515 can not be connected,  looks the firewall caused this issue.

**Comment by rbnali** [comment]
@barancev Actually, the problem occurred again after a few months I don't know why. 

Selenium works perfectly fine with my old mac book (Chrome 72.0.3626.121 | Selenium 3.9 | old version of Chromedriver from march 2018), but not with my recent one (Chrome 74.0.3729.157 | Selenium 3.141.0 | ChromeDriver 74.0.3729.6).

@TopKeingt I will try this!

**Comment by xiaolin-guo** [comment]
I disable my firewall resolved this problem. then I enable the firewall again everything works fine now...
