### ISSUE TITLE
Can not modify(or insert) page source if original web page contains single quote(')

### ISSUE THREAD

**Issue by nlpsuge** [SeleniumHQ/selenium#6624]
## Meta -
OS:  
Fedora 29
Selenium Version:  
3.141.0
Browser:  
Firefox (geckodriver v0.23-linux64)
Browser Version:  
63.0.1 (64-bit)

## Expected Behavior -
Add `<input` id="imagepicker_identity_id" /> into page source by innerHTML

## Actual Behavior -
It's not work if original page source contains single quote(')
due to:
JavascriptException: Message: SyntaxError: unexpected token: identifier

## Steps to reproduce -
This is my test case:
https://github.com/nlpsuge/SeleniumDemo/blob/master/issues/ModifyPageSourceTest.py

**Comment by cgoldberg** [comment]
the test case provided is pretty unhelpful.  Please provide a http://sscce.org/ and a better explanation of the issue.
