### ISSUE TITLE
Chromedriver 2.43 / Chrome 70 not clicking on correct coordinates inside Iframe.

### ISSUE THREAD

**Issue by DanielPradoPino** [SeleniumHQ/selenium#6629]
## Meta -
OS:  
 Windows All Versions
Selenium Version:  
2.43 
Browser:  
Chrome using mobile emulator

Chromedriver is not clicking properly on elements inside some Iframes, if I open the Iframe src directly everything is working properly so we can discard a bad HTML formatting.

Iframe example on https://sports.coral.co.uk/playerbets

Issue started with Chome 70, previous version (69) is working fine.

Browser Version:  
70.0.3538.77  (64-bit)

## Expected Behavior -
Chrome clicking properly in elements
## Actual Behavior -
Chrome clicking outside element (wrong coordinates)
## Steps to reproduce -

Switch to Iframe "id=betBuilder" on provided URL and try to click on any element.

Thanks.

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
