### ISSUE TITLE
same html page,use By.XPath, ie,firefox run good, chrome give a error.

### ISSUE THREAD

**Issue by brickhe** [SeleniumHQ/selenium#663]
In same html page:  http://news.baidu.com/
driver.getElements(By.Xpath("//body")) is run good on IE and Firefox, but on Chrome it cause a error:

invalid selector: Unable to locate an element with the xpath expression //body because of the following error: TypeError: Cannot read property 'match' of undefined   (Session info: chrome=41.0.2272.76)   (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.1 SP1 x86_64)

And run javascript in chrome can get the right result:
So I resolve it like below:
--------------------------
Dim all As ReadOnlyCollection(Of IWebElement)
        Try
            all = Application.driver.FindElements(By.XPath(xpath))
        Catch ex As Exception
            Dim js = "var ret = Array(); var a = document.evaluate(arguments[0], document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null); for( var i = 0 ; i < a.snapshotLength ; i++ ){ aResult.push(a.snapshotItem(i)); } return ret;"
            all = (DirectCast(Application.driver, IJavaScriptExecutor).ExecuteScript(js, xpath))
        End Try

have something different on Chrome? or different with this page?  http://news.baidu.com/

**Comment by barancev** [comment]
Please report this issue to the chromedriver tracker https://code.google.com/p/chromedriver/issues/
