### ISSUE TITLE
[SEVERE]: Timed out receiving message from renderer 

### ISSUE THREAD

**Issue by Owklolz** [SeleniumHQ/selenium#6630]
**OS:**  
Windows 10
**Selenium Version:**  
selenium-server-standalone-3.14.0 for java (using maven)
**Browser:**  
Google chrome Version 70.0.3538.77 (Official Build) (64-bit)
**driver:**  
ChromeDriver 2.43

I know so many people have been asking for a solution for this issue, tickets and threads everywhere but still no obvious solution neither obvious source of this problem. I am using the lastest versions of requirements. i made sure (hopefully) there are no compatibility issues.

**Issue :** 
_[1541586055.743][SEVERE]: Timed out receiving message from renderer: 299.359_ 
Happening randomly at the start of the test after calling for `driver.get(url)` without throwing any exception, it just freezes , i should either use ui to manually refresh the browser or just restart the test, or it will just keep hanging like this forever.
I want to know if it is a selenium bug or chromedriver bug or an issue with chrome browser or there's something wrong with the way i use it.  
btw : i have been looking for a solution for a long time now, and i have tried every solution i have found in any thread in any forum, in vain..
Details:
I have been using selenium java for a while now , first started using it locally on my computer using chromedriver webdriver , i've always had this issue then switched to using remote webDriver but nothing changed it is still happening the same old way.

if there's anything that i should provide please tell me.

Here are my chromeOptions:
`options.addArguments("--no-sandbox");
					options.addArguments("--disable-dev-shm-usage");
					options.addArguments("--aggressive-cache-discard");
					options.addArguments("--disable-cache");
					options.addArguments("--disable-application-cache");
					options.addArguments("--disable-offline-load-stale-cache");
					options.addArguments("--disk-cache-size=0");
					// options.addArguments("--headless");
					options.addArguments("--disable-gpu");
					options.addArguments("--dns-prefetch-disable");
					options.addArguments("--no-proxy-server");
					options.addArguments("--log-level=3");
					options.addArguments("--silent");
					options.addArguments("--disable-browser-side-navigation");
					options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
					options.setProxy(null);`

**Comment by cgoldberg** [comment]
does it still occur if you remove those options? .. If not, can you narrow it down to which Chrome option is causing this?  You have an absurd amount of options specified.

**Comment by arthurio** [comment]
@Owklolz What is the observed behavior in your case? I had a somewhat similar issue where I created multiple sessions and the first one would work, but following ones would timeout and throw a timeout exception. I would see a blank chrome window opened and nothing would happen. Also, this was using a remote webDriver.
To fix it, I made sure to use a unique user data dir for any new `webdriver.Remote` connection (`'--user-data-dir=/tmp/chromedevprofile/something_unique'`).
Could you try that and share the result here? Or is it something you already tried?

**Comment by Owklolz** [comment]
@cgoldberg  Yes it occurs even if i run it without any options.

@arthurio I am running on selenium server which choses a node , tried working with one node , started with the command `java -Dwebdriver.chrome.driver="path/chromedriver.exe" -jar selenium-server-standalone-3.14.0.jar -role node -hub http://ipAdress:4444/grid/register/` 
And by the way before that, i used to run it locally using chromeDriver. 
I did not try to use a unique user data dir for new sessions. I will try to set that as a chrome option using a generic name so it would be unique for every session.
I am running a test suite using testng xml file , but even when i run tests manually from eclipse this timeout happens randomly , you don't know which test would produce it , and it does not throw any exception.

**Comment by schmidtkp** [comment]
Maybe related, maybe not, but I've encountered random BindException: Address already in use, using same Selenium/ChromeDriver/Chrome browser versions, but Windows Server 2016.

Also, the bind exception only happens when I have the nodes in the grid configured to have maxSession/maxInstances > 1.

The bind exception does not happen using the macOS version of the ChromeDriver, nor with Firefox/GeckoDriver and Firefox legacy webdriver (for Firefox ESR browser), regardless of maxSession/maxInstances setting (1 or more).

I've concluded this is a ChromeDriver (Windows OS) issue rather then a Selenium client-binding issue, but I've been unable to create a reproducible test case.

**Comment by dylanlive** [comment]
I've been seeing this issue for awhile, and believe for my case I traced it to ad providers/trackers that have a script that stalls to finish loading. Not entirely sure why a normal timeout through Selenium didn't catch it, perhaps the browser itself is freezing during render.

@schmidtkp I don't believe that issue is related to this ticket or Chromedriver - I have also seen that and I'm actively exploring it related to port exhaustion.
https://github.com/SeleniumHQ/selenium/issues/5149
https://stackoverflow.com/questions/4320397/webdriver-java-net-bindexception-address-already-in-use-connect/4321285#4321285

**Comment by hfontanez1968** [comment]
In my case, I can run my tests from Eclipse and it runs fine. However, when I run my tests from our Jenkins server, the issue occurs. Firefox works just fine running on the same Jenkins server.

**Comment by hfontanez1968** [comment]
In my case, I can run my tests from Eclipse and it runs fine. However, when I run my tests from our Jenkins server, the issue occurs. Firefox works just fine running on the same Jenkins server.

By the way, I've tried version 2.37.544315 and it does the same thing.

**Comment by DragonGowda** [comment]
I am facing similar issue while running my tests on Jenkins. I am using chromedriver 2.45 version and chrome browser being 73.0.3683.86.
Error message displayed is as below.
[1554382544.273][SEVERE]: Timed out receiving message from renderer: 600.000
Please help in getting this resolved as I am unable to complete any automation execution in Jenkins.

**Comment by barancev** [comment]
"Timed out receiving message from renderer" means that chromedriver can't receive a response from chrome in time, it's a miscommunication between chromedriver and chrome. So please raise an issue on https://bugs.chromium.org/p/chromedriver/issues/list
