### ISSUE TITLE
Netwonsoft.Json dotnet reference problem

### ISSUE THREAD

**Issue by miroslawmajka** [SeleniumHQ/selenium#664]
We've hada problem using selenium lately in conjunction with a web solution tha uses the Newtonsoft.Json library. Every time we ran our console app with selenium, the web app from the same solution broke because of the library reference to the 4.5 version. I've noticed that the version referenced in the selenium project is using 4.5 in the project file. This looks like a bug even though the referenced library is on 6.0.0.

```
selenium/dotnet/src/webdriver/WebDriver.csproj
```

Issue with the reference (points to version 4.5, not 6.0):

``` 
<Reference Include="Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\third_party\dotnet\json-net-6.0r2\Net40\Newtonsoft.Json.dll</HintPath>
    </Reference>
```

**Comment by jimevans** [comment]
Unless you're including the WebDriver source code in your solution and building it normally, this should not be an issue. The WebDriver assembly as shipped merges the JSON library as an internal set of classes. It's possible there might be a big in the .NET Framework's Fusion class loader, but the correct version of the JSON library is being used by WebDriver.

**Comment by miroslawmajka** [comment]
It looks like when our console application is running, by referencing the Selenium WebDriver the libarary cachce gets modified and the version that is supposed to be cached becomes 4.5.0.0. (like in the Reference, Inclue="... , Versions=4.5.0.0." line of the project file.

We could try recompiling the solution after removing the 'Version=' part from that statement since the SpecificVersion flag is set to false anyway. If this works then suppose we could post it as a fix to the problem?

Our temporary solution to this is running both the console application and the web application, which are both from the same solution, in concurrency from Visual Studio. This way both run OK.

But when we run the console app first it tries to communicate with the Web app hosted in IIS and by that point the Json library dependency is broken (pointing to 4.5.0.0) and any WebAPI calls originating in the console app fail.

**Comment by jimevans** [comment]
You've rather missed my point, I'm afraid. The .NET bindings, when distributed in a binary form, do not read the JSON.NET assembly from the GAC, nor from disk at all. The reference has been merged entirely into the WebDriver.dll assembly, requiring no external assemblies. If you can provide a sample solution demonstrating the issue, I'll be happy to take a closer look.

**Comment by miroslawmajka** [comment]
Hi there, thanks for getting back to me. I've create a simple test solution: https://github.com/miroslawmajka/NewtonsoftReferenceBug, need to add some Selenium code calls and make sure the scenario fails as described. Will let you know once this is working (breaking) when I get a chance to do some work side coding.

**Comment by miroslawmajka** [comment]
Hello again, after some time investigating the issue today we found that it was in fact a dependency library which was using FluentAutomation WebDriver (Chrome) that didn't have the Newtonsoft.Json dependency specified in the project file in our solution. That is why our web application was going to version 4.5.0 referenced by the FluentAutomation package.

This one can be closed. Sorry about the fuss!
