### ISSUE TITLE
Node is disconnected with Hub

### ISSUE THREAD

**Issue by udayanem** [SeleniumHQ/selenium#6641]
## Meta -
OS:  
 Windows 7
Selenium Version:  
 Selenium 3.12
Browser:  
 Chrome 3.12

## Steps to reproduce -

All my project source code is in BitBucket and project is setup in Jenkins.
Goal is to run entire suite on a schedule time daily from Jenkins.

Hub(Linux) is running on the same Jenkins Server and Node(Windows) is getting connected to the Hub.

But the problem is, Node is disconnected with the Hub after 1-2 days, because of this, my scheduled jobs in Jenkins are failing most of the time.

How can i make sure the Hub and Node stay connected for longer days(say 30 / 50 days)?

Following is the command i am using to connect Node with Hub:
`java -jar -Dwebdriver.chrome.driver=chromedriver.exe -Dwebdriver.gecko.driver=geckodriver.exe selenium-server-standalone-3.12.0.jar -role node -nodeConfig node1.json`

and following is nod1.json file content:
```
{
  "capabilities":
  [
    {
      "browserName": "firefox",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "chrome",
      "maxInstances": 5,
      "seleniumProtocol": "WebDriver"
    },
    {
      "browserName": "internet explorer",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "port": 17946,
  "register": true,
  "registerCycle": 5000,
  "timeout":432000,
  "hub": "http://jenkins.abc.com:4444",
  "nodePolling": 5000,
  "role": "node"
}
```

Can someone help me what i am missing? How can i make the Node and Hub connected?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
