### ISSUE TITLE
Setting browserName to chrome by default when ChromeOptions object is created makes Appium session create fail

### ISSUE THREAD

**Issue by megolee** [SeleniumHQ/selenium#6643]
## Meta -
OS:  
<OSX>
Selenium Version:  
< 3.12.0> Depends by Appium Java client 6.1.0
<3.141.5> Depends by Appium Java client latest commit

https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/chrome/ChromeOptions.java#L86

From selenium java version 3.6.0, when initialize an object of ChromeOption, it will set the browser name capability with chrome as above link. And this makes Appium create session fail with logs as below:

https://gist.github.com/megolee/2633e04a76b18b45d92740268d2ac847

Now we have to reset browserName to empty as a workaround to solve this issue. 

Please refer to issue https://github.com/appium/java-client/issues/969 for more detail. Thanks~

**Comment by AutomatedTester** [comment]
This is correct behaviour. You will need to either remove that key from the desired or Appium will need to
