### ISSUE TITLE
Please offer a solution for basic authentication

### ISSUE THREAD

**Issue by AndreasKarz** [SeleniumHQ/selenium#6644]
## Meta -
OS:  

Selenium Version:  

Browser:  

Browser Version:  

## Expected Behavior -
Please finally make it possible that it is possible to send a header with the method GoToUrl(). This is the only really working possibility for Basic Authentication. Because tools like AutoIt don't work on BrowserStack etc.

## Actual Behavior -
There is no way to send a header. And the complete problem is open since 2016!!!
https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/34 
We are thinking about to change to Ranorex -- with this issues we can't work professional.

**Comment by jimevans** [comment]
You mean using something like [a solution using a proxy](https://github.com/jimevans/stpcon-selenium-201/blob/master/ProxyExamples/AuthenticationExtensionMethods.cs)? You haven’t said, but guessing that you’re using C#, there are [example repositories](https://github.com/jimevans/stpcon-selenium-201) that demonstrate using a proxy to accomplish lots of tasks that may nor be possible with Selenium.

**Comment by AndreasKarz** [comment]
> You mean using something like [a solution using a proxy](https://github.com/jimevans/stpcon-selenium-201/blob/master/ProxyExamples/AuthenticationExtensionMethods.cs)? You haven’t said, but guessing that you’re using C#, there are [example repositories](https://github.com/jimevans/stpcon-selenium-201) that demonstrate using a proxy to accomplish lots of tasks that may nor be possible with Selenium.

No a proxy is no solution, then you can install a proxy in BrowserStack. We need a solution, that works on every case. Why should it be so difficult to implement a header function so that the tool can be used professionally? 
If you google the topic, you'll quickly find that thousands of developers have been struggling with the same problem for years.

**Comment by shs96c** [comment]
To do this in a cross-browser way that provides a pleasant user API is distinctly non-trivial, but we're working on it, as https://github.com/w3c/webdriver/issues/385 shows.

It turns out that not every browser has a mechanism for simply "implementing a header function so that the tool can be used professionally". Personally, I'm tempted to blame those amateurs who've poured years of effort into the blasted things.

More seriously, @AndreasKarz, we know this is something that people really want, and it's something that we really want too. If you'd like to help us push it over the line, contributing to the W3C webdriver spec would be an excellent first step: it's on GitHub and run in the open specifically to enable this kind of collaboration.

**Comment by unverified-contact** [comment]
Are there any hacks or workarounds to be able to do this kind of thing in the meanwhile? Maybe there's a (semi) neat way to do this with a plugin or something similar?

**Comment by unverified-contact** [comment]
Are there any hacks or workarounds to be able to do this kind of thing in the meanwhile? Maybe there's a (semi) neat way to achieve this effect with a plugin or something similar?

**Comment by walter-hernandez** [comment]
@shs96c @AndreasKarz in the w3c/webdriver#385, in the last comment, they are welcoming the writing of the prose and merged of the change. @AndreasKarz it would be a great contribution to a highly demanded spec in the W3C webdriver and hence, selenium

**Comment by tchret** [comment]
Following

**Comment by ArmandoAssuncao** [comment]
While is not is done, i created this code that work:

https://gist.github.com/ArmandoAssuncao/51edbbdc8dc2e8e6ac8c16c2847ed960

**Comment by diemol** [comment]
While not a cross browser solution yet, as we are still heading in that direction with WebDriver BiDi, for now this can be done on Chromium based browsers, see the example at https://www.selenium.dev/documentation/webdriver/bidi_apis/#register-basic-auth
