### ISSUE TITLE
[SEVERE] Driver will not wait longer than 60 seconds

### ISSUE THREAD

**Issue by vitalisc** [SeleniumHQ/selenium#6650]
OS:  Windows 8
Selenium Version:  3.1.41.0
Browser:  Chrome
Browser Version:  70.0.3538.102

Issue : Please take a look at this screenshot http://prntscr.com/lhrr4s
This happen almost  all the time both  navigating on a web page or clicking element on a web page 
Everything are set to 60 seconds, which is not right, not everyone  have access to fast internet , i have tried many solutions i saw online to increase the timeout , but none worked , it will always stop at 60 seconds

Expected Behavior : selenium webdriver timeout to be dynamic so that users can choose the timeout that works for them, or if there is a  way to modify the timeout  please let me know

**Comment by jimevans** [comment]
The .NET bindings already have the feature you’re looking for. Assuming you are using the no-argument constructor for `ChromeDriver`, you can achieve what you want with the following constructor overload.

    // The third argument is the important one here. It
    // sets the timeout between the language bindings
    // and the remote end (chromedriver.exe, geckodriver.exe, etc.)
    IWebDriver driver = new ChromeDriver(ChromeDriverService.CreateDefaultService(), new ChromeOptions(), TimeSpan.FromSeconds(120));

**Comment by vitalisc** [comment]
ok thanks for your response i can confirm this code is working for chrome what about firefox

thanks

**Comment by jimevans** [comment]
Every browser driver has a constructor overload that takes a TimeSpan for the timeout. Visual Studio’s IntelliSense should be able to show you those overloads.

**Comment by jimevans** [comment]
@vitalisc You’ve set your proxy on a `ChromeOptions` object you’re never using.  What you want is this:

    var chromeOptions = new ChromeOptions();
    var proxy = new Proxy();
    proxy.HttpProxy = "138.68.232.41:8080";
    chromeOptions.Proxy = proxy;

    var driverService = ChromeDriverService.CreateDefaultService();
    driverService.HideCommandPromptWindow = true;

    // Use the created ChromeOptions here,
    // instead of creating a new one.
    var driver = new ChromeDriver(driverService, chromeOptions, TimeSpan.FromSeconds(80));

**Comment by vitalisc** [comment]
thanks for your support , i tested the program it didn't change the ip please can you test from your end

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Test_proxy
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var chromeOptions = new ChromeOptions();
            var proxy = new Proxy();
            proxy.HttpProxy = "138.68.232.41:8080";
            chromeOptions.Proxy = proxy;

            var driverService = ChromeDriverService.CreateDefaultService();
            driverService.HideCommandPromptWindow = true;

            // Use the created ChromeOptions here,
            // instead of creating a new one.
            var driver = new ChromeDriver(driverService, chromeOptions, TimeSpan.FromSeconds(80));

            driver.Url = "https://www.iplocation.net/find-ip-address";
        }
    }
}
