### ISSUE TITLE
Unable to scroll down in Firefox.

### ISSUE THREAD

**Issue by ShibiKP** [SeleniumHQ/selenium#6653]
## Meta -
OS:  
Windows 8.1 
Selenium Version:  
Selenium version 3.14.0
Browser:  
Firefox 
-->

Browser Version:  
63.0

## Expected Behavior -
In web page webelement is present at end of the web page or middle of web page.
It should automatically scroll down and perform action in webelement. 

## Actual Behavior -
But we getting Error message as "could not be scrolled into view" and Exception as "org.openqa.selenium.ElementNotInteractableException".

## Steps to reproduce -

1. Launch firefox using selenium 3.14.0 (download the latest version of firefox)
2.  Go to URL ("http://automationpractice.com/index.php")
3. Click the T- Shirt scroll down product will display.
4. Need to Click the webelement.

[Firefox ErrorMessage.txt](https://github.com/SeleniumHQ/selenium/files/2579619/Firefox.ErrorMessage.txt)

Please find the java code:-

driver.get("http://automationpractice.com/index.php");
	    
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		 
System.out.println("Page title is: " + driver.getTitle());
	    
Assert.assertEquals("My Store", driver.getTitle());
	    
 waitForPageLoad();
	    
 driver.findElement(By.xpath("(//a[text()='T-shirts'])[2]")).click();
	    
    String ProductName=driver.findElement(By.xpath("//a[@class='product_img_link']")).getAttribute("title");
	    
String ProductPrice=driver.findElement(By.xpath("//span[@class='price product-price']")).getText().trim().toString();
	  	
driver.findElement(By.xpath("//a[@class='product_img_link']")).click();

Thanks & Regards,
Shibi KP

**Comment by ShibiKP** [comment]
I have tried the javascript, Action Class to scroll down the webpage. But javascript and Action action have performed. unfortunately the scrolling action not yet happen.

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
