### ISSUE TITLE
functionalTimeouts incorrectly send according to GeckoDriver

### ISSUE THREAD

**Issue by GARMBoshouwers** [SeleniumHQ/selenium#6654]
This is a bug report first added to the GeckoDriver issue list [#1426](https://github.com/mozilla/geckodriver/issues/1426)

They believe this is an issue in Selenium.

## System

* Version: geckodriver 0.23.0
* Platform: Microsoft Windows 10 Pro
* Firefox: 63.0.1
* Selenium: selenium-server-standalone-3.14.0.jar
* Intern: 4.3.2
* Node: 9.3.0

## Testcase

In the above environment, setup the following files:
[run.js](https://pastebin.com/wRHv9sMH)
[test.js](https://pastebin.com/wGnv4peh)

Note: the test uses an environmental variable to set the path to the FireFox browser executable. Edit line 22 of run.js to hardcode this.

Run the test using
`node run.js firefox`

The test fails to run. The script fails after the capabilities check. The test works in Chrome, Edge and IE11. 
The test also works in FireFox if the functionalTimeout block is commented out in the config object (run.js, lines 11-13)

It seems the communication of timeout values is incorrect between Intern and geckodriver in these versions.

## Stacktrace

Added as attachment `functionalTimeout command line output.txt`

## Trace-level log

Added as attachment `functionalTimeout trace log.txt`

[functionalTimeout command line output.txt](https://github.com/SeleniumHQ/selenium/files/2579869/functionalTimeout.command.line.output.txt)
[functionalTimeout trace log.txt](https://github.com/SeleniumHQ/selenium/files/2579870/functionalTimeout.trace.log.txt)

**Comment by lmtierney** [comment]
What library are you using to send commands to `selenium-server-standalone` ?

**Comment by lmtierney** [comment]
Looks like intern must have some library built into it now that talks to selenium-server? Either way, raise an issue with them, your library needs to send the correct command to selenium-server

**Comment by lmtierney** [comment]
This is already raised to your library here https://github.com/theintern/leadfoot/issues/166

**Comment by GARMBoshouwers** [comment]
OK, thanks for your help.
