### ISSUE TITLE
E: unable to locate package chromium-chromedriver

### ISSUE THREAD

**Issue by cottons1618** [SeleniumHQ/selenium#6657]
## Meta -
OS: Kali Linux 2018.3
Selenium Version:  3.8
Browser: Chrome

## Actual Behavior - I'm trying to install chromedriver in Kali Linux. I followed the step in the Debian based Linux distro guide of entering 

`sudo apt-get install chromium-chromedriver` 

However, when I run it, I get an error that says 

`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`E: Unable to locate package chromium-chromedriver`

please let me know how if you need anything else.

## Steps to reproduce -
In a newly installed version of Kali Linux 3.8, open up terminal and type `sudo apt-get install chromium-chromedriver`

**Comment by lmtierney** [comment]
1. This package `chromium-chromedriver` is not created nor maintained by Selenium
2. Chromedriver is not created nor maintained by Selenium
