### ISSUE TITLE
Firefox: Load a fake webcam video file with media.navigator.streams.fake flag

### ISSUE THREAD

**Issue by Darkensses** [SeleniumHQ/selenium#6659]
## Meta -
OS:  Windows 10

Selenium Version:  3.141.59

Browser:  Firefox

Browser Version:  63

## Expected Behavior -
Use a video file for media.navigator.streams.fake flag, like chrome option --use-file-for-fake-video-capture=path/to/video.y4m

## Actual Behavior -
Only show the multiple color video default to 'simulate' a webcam

## Steps to reproduce -
FirefoxOptions options = new FirefoxOptions();
options.addPreference("media.navigator.streams.fake", true);
options.addPreference("media.navigator.permission.disabled", true);
this.webDriver = new FirefoxDriver(options);

What do I need to add?

**Comment by lmtierney** [comment]
Please log any Firefox & Geckodriver issues with Mozilla: https://github.com/mozilla/geckodriver/issues

**Comment by Darkensses** [comment]
Ok, thanks
