### ISSUE TITLE
RemoteWebDriver use exist sessionId

### ISSUE THREAD

**Issue by youwi** [SeleniumHQ/selenium#6660]
## RemoteWebDriver 
platform: selenium-remote-driver

Selenium Version:  3.14.0

How to new a RemoteWebDriver with exist session ID?
there is no constructor   for "new RemoteWebDriver(URL,sessionId)".

here is a ugly code
```
 public class ReusableRemoteWebDriver extends RemoteWebDriver implements Serializable {
  public ReusableRemoteWebDriver(URL remoteAddress, String oldSessionId) throws ConnectException {
    super(remoteAddress, new DesiredCapabilities());
    waitForRemoteBrowserReady(remoteAddress);
    this.setSessionId(oldSessionId);
    this.oldSessionId = oldSessionId;
    if (this.getCommandExecutor() instanceof org.openqa.selenium.remote.HttpCommandExecutor) {
      try {
        HttpCommandExecutor executor =  this.getCommandExecutor();
        Feild field =  org.openqa.selenium.remote.HttpCommandExecutor.class.getDeclaredField("commandCodec");
        field.setAccessible(true);
        field.set(executor, new JsonHttpCommandCodec());
        Feild field2  = org.openqa.selenium.remote.HttpCommandExecutor.class.getDeclaredField("responseCodec");
        field2.setAccessible(true);
        field2.set(executor, new JsonHttpCommandCodec());
      } catch (IllegalArgumentException var3) {
   
       } catch (IllegalAccessException var4) {
    
       }
    }
     this.startSession(new DesiredCapabilities());
    }
```
the code may not work in the future.

## Expect
provide a constructor "new RemoteWebDriver(URL,sessionId)", officially

**Comment by diemol** [comment]
Hi @youwi,

The solely purpose of RemoteWebDriver (WebDriver itself) is to create a session, by design it won't receive a session as a parameter.

Perhaps it would be more useful if you post your question on the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
