### ISSUE TITLE
Wrong user agent header in shutdown request

### ISSUE THREAD

**Issue by mzedeler** [SeleniumHQ/selenium#6662]
## Meta -
OS: Ubuntu Linux 18.x
Selenium Version: Latest available revision on `master`: cb8aa77853496e052c61bbed3952d8c86ef247af
Browser: Chrome
Browser Version:   70.x
Driver variant: Ruby

## Expected Behavior -
When the Selenium driver shuts down, it should send a shutdown request with `User-Agent: selenium/<version>`.

## Actual Behavior -
When the Selenium driver shuts down, it sends a shutdown request with `User-Agent: Ruby`.

## Steps to reproduce -
I haven't been able to write one. Will provide if anyone is interested, but I believe that I have found the specific line where the user agent isn't being set correctly:

https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/service.rb#L128

**Comment by twalpole** [comment]
Before I work on this, where is the requirement for the user agent specified? I know it was added for remote connections, but I don't find anywhere that it's specified for local services.

**Comment by mzedeler** [comment]
The reason that I requested this, is because if you run Selenium in an environment where other HTTP calls needs to be intercepted by mock frameworks, it is really useful to be able to white list the Selenium user agent, so it is always passed through.

At the moment, I have to use two specific white list rules, one that passes requests through if they match the Selenium user agent and another just for the shutdown request.
