### ISSUE TITLE
Nice Locators

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6664]
The current locators are very low level, and so we need to add some nice ones that people can use to the support library. These should probably subclass `By`

**Comment by kambleaa007** [comment]
hello @shs96c  
Locators like By.XPath or By.CssSelector are mostly used for flexibilty
By.Id get used when there is only one element is present
can we apply `Generic methods` so user will get more help

**Comment by jimevans** [comment]
@shs96c Let’s make sure we fully document these so they don’t become a support nightmare. I’m thinking of something like a `near` or `above` or `below` locator, where our vision of those terms may not precisely align with what every user, everywhere believes.

I’d much rather “teach people to fish,” by saying something like, “Here’s how you implement something like a ‘friendly’ locator, and here are some implementations. If they work for you as-is, great. If not, you can use these implementations as templates to get you the exact behavior you want.” I’m explicitly wanting to avoid the horror of `ExpectedConditions`, and hopefully setting the expectation up front will help with the support and maintenance burden down the road.

**Comment by diemol** [comment]
Closing as this has been implemented for Java (will open a new issue for the currently remaining binding that is still missing it -- JavaScript)
