### ISSUE TITLE
Allow a v3 Grid Node to participate in Grid TNG

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6666]

**Comment by paulsbruce** [comment]
Folks, a particular use case for this is to carry over any customization work people have done against the DefaultRemoteProxy class (see thread linked below). Along with other use cases for v3 nodes in TNG, this could provide a stop-gap solution that buys time for architectural thinking about how to do this natively in TNG, as well as improves backward compatibility to the v3 ecosystem.

https://groups.google.com/d/msg/selenium-developers/7CYNeAzbb64/Mmg07XQgDAAJ

**Comment by paulsbruce** [comment]
Hallo @barancev ! Just a ping on this, I'd like to start in on this work, at least for my own prototyping and need guidance on how to do this in a way that fits in with the Se4 grid architecture as it currently stands.

What would be the best forum/format/channel to discuss this together?

* Google Groups Selenium Developers
* IRC
* Slack
* This issue
* Something else

**Comment by AutomatedTester** [comment]
Looking into the way the Se4 grid has been rearchitected I am not sure that this is a useful amount of work. The new grid has really great features that trying to shoehorn the old grid registration will be clunky.
