### ISSUE TITLE
Java implementation of DevTools API

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6667]
This should allow users to take advantage of features offered by using the Chrome Debugging Protocol (and equivalents on other browsers), notably:

* Full page screenshots
* Streaming logs
* Waiting for mutation events on the page

**Comment by shs96c** [comment]
There's code for this in https://github.com/shs96c/selenium/tree/cdp

**Comment by joywave** [comment]
This would be really nice to have. I looked at this today and some previous attempts were https://github.com/SeleniumHQ/selenium/pull/5262 https://github.com/SeleniumHQ/selenium/issues/5159

**Comment by adiohana** [comment]
@shs96c 
I see that this is part of Selenium 4. **Is there a point for me to work on the PR now?** 
Chrome DevTools integration requires WebSocket functionality and some changed in RemoteWebDriver which is kind of a big change

**Comment by barancev** [comment]
Initial support has been implemented:
f280b8b8232824ee432917f068c6b79990bde08a
a99534efddef9a27d37d41a73ae31391f03300e0
58298638deb63a91a22c6ae8f0309faf4e6d434e

**Comment by shs96c** [comment]
@adiohana Absolutely! We're super-keen on coming up with a nicer way of presenting this in the user-facing APIs, and we really need to find a way of generating the raw CDP classes rather than writing it all by hand.

**Comment by adiohana** [comment]
@shs96c 
Thanks for the confirmation, we will do it soon

**Comment by adiohana** [comment]
@shs96c 
seems that generating the raw CDP is a complicated task and can be fragile because we are counting on Google developers not to change their CDP json schema as stated here: https://github.com/ChromeDevTools/devtools-protocol/blob/master/json/browser_protocol.json

I see that you already implemented (partially) the following domains:
* Target
* Runtime
* Console
* Log

I think that the 2 most critical domains (for the features I stated above and more) are:
*Network
*Performance

Do you think it worth implementing Network and Performance "manually" while we are working on the auto generation of the CDP classes?

**Comment by shs96c** [comment]
@adiohana, writing those two manually makes sense as a stepping stone to getting everything running. If you've got the time, I'd be very happy to review a PR :) If you need a hand, I tend to lurk on the #selenium IRC and Slack channels (London work hours), and I can step you through anything you're finding tricky to deal with.

**Comment by adiohana** [comment]
Thanks @shs96c 
I am working on this together with dratler.shay@gmail.com 
we will submit the PRs tomorrow probably.
We also joined the slack channel so we will reach out in case of any issues

**Comment by adiohana** [comment]
#7212 

@shs96c 
PR is ready. We have a good infrastructure for DevTools and Network and Performance implementations.

I will add the notes and gaps also to here:
* Need to add support for List as Command input.
* Add better error handling for DevTools operations
* Add more test scenarios
* Implement more DevTools methods according to https://chromedevtools.github.io/devtools-protocol/

let me know if you want to open tasks for the above notes. We will be happy to add more API's and more functionalities to DevTools in the near future.

**Comment by dratler** [comment]
Hi ,
I would like to implement "Profiler Domain" out of DevTools , is it fine ?

**Comment by shs96c** [comment]
@dratler Apologies for not responding sooner --- I'd missed the notification. Implementing any part of the CDP is fine. Putting forwards any diffs for Selenium is also fine. It's encouraged! Thank you for taking the time and effort to join in the fun! :)

**Comment by dratler** [comment]
Hi @shs96c ,
no problem just say when :).
P.S I have investigated more about auto generated and for our use case I think it will not do well.
For now I'm also working on Page CDP

**Comment by SergeyPirogov** [comment]
Would be nice to have support for debugger and profiler

**Comment by dratler** [comment]
Hi @SergeyPirogov ,
profiler is implemented and for Debugger it's under construction

**Comment by barancev** [comment]
I'm working on the code generatior that will cover full CDP specification. Please be patient, it's going to be available soon.

**Comment by barancev** [comment]
What we really need help with is the current implementation of the Fetch domain. It does not pass its tests. If someone could investigate and fix it that would be very appreciated.

**Comment by dratler** [comment]
I will fix it

**Comment by NoamGoren** [comment]
Hi @barancev ,
@dratler  and I fixed this issue.
PR can be found on https://github.com/SeleniumHQ/selenium/pull/7754

**Comment by diemol** [comment]
I'll close this since initial support has been added in the linked commits above, the PR discussion will be handled in the PR, and a more detailed discussion on how it will be supported can be followed at #8168
