### ISSUE TITLE
Task scheduler not launching powerbi report in chrome using Selenium script

### ISSUE THREAD

**Issue by ankittarsolia** [SeleniumHQ/selenium#6671]
Hi All,

I am trying to launch the powerbi report in chrome browser through Selenium script. its basically taking the username and password to launch the report in chrome browser.
I created the console application and make the exe.
Expected Behavior:
1. when we executed the exe manually then its should launch the powerbi report in chrome(username and password will be filled by script). 
--> This is working fine.

2. When we scheduled the exe from task scheduler then exe should run and launch the powerbi report in chrome browser(username and password will be filled by script). 
--> This should working but its not working.

Assumption for point 2: exe trying to sent the command to chrome browser in background but its not performing any action and throwing following error:
Error: The HTTP request to the remote WebDriver server for URL timed out after 60 seconds.

Sample Code: Used following code.

IWebDriver driver = new ChromeDriver();

                    driver.Navigate().GoToUrl(testreport);
                    driver.FindElement(By.Id("a12345")).SendKeys("abc");
                    driver.FindElement(By.Id("idTestButton1")).Click();

                    Thread.Sleep(10000);
                    AutoItX.Send("abc");
                    AutoItX.Send("{TAB}");
                    AutoItX.Send("test123", 1);
                    AutoItX.Send("{Enter}");

                    DateTime startTime = DateTime.UtcNow;

WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(120));
wait.Until(ExpectedConditions.ElementIsVisible(By.ClassName("reprtname")));

Thanks

**Comment by diemol** [comment]
Hi @ankittarsolia,
 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
