### ISSUE TITLE
selenium keyword not working in Linux 7.5 for robot framework

### ISSUE THREAD

**Issue by Rohit2387** [SeleniumHQ/selenium#6675]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by Rohit2387** [comment]
OS : RHEL 7.5
BROWSER : Firefox
SELENIUM VERSION : 2.9.1
ROBOT VERSION : 2.8.1
BROWSER VERSION : It was tried with 60,52.7.0,54,45,32

**Comment by barancev** [comment]
Please report the issue to https://github.com/robotframework/Selenium2Library
