### ISSUE TITLE
[JavaScript] Loading extensions from file in Chrome doesn't work in 4.0.0-alpha.1

### ISSUE THREAD

**Issue by soulgalore** [SeleniumHQ/selenium#6676]
## 💥 Regression Report

Loading a Chrome extension in 4.0.0-alpha.1 doesn't work, it throws ```unknown error: cannot process extension #1 from unknown error: cannot base64 decode```

## Last working Selenium version

Worked up to version: 3.6.0

Stopped working in version: 4.0.0-alpha.1

## To Reproduce
Loading an extension like:

```
 chromeOptions.addExtensions(
      path.resolve(moduleRootPath, 'vendor', 'browsertime-extension.crx')
   );
```
doesn't work.  See https://github.com/sitespeedio/browsertime/blob/master/lib/chrome/webdriver/index.js#L100-L105

Detailed steps to reproduce the behavior:

## Expected behavior

You should be able to load extensions from file in Chrome.

## Test script reproducing this issue (when applicable)

I think this was introduced here: https://github.com/SeleniumHQ/selenium/commit/9976795d0357aa19f95d6c73c9f203449e182fbf#diff-cc4a7b2914982158b85fcd2ff2a60ea2

I can have a go to see if I can fix it the coming days, if I get the environment working.

## Environment

OS: OS X
Browser: Chrome
Browser version:  70.0.3538.10
Browser Driver version:  ChromeDriver 2.43
Language Bindings version: JavaScript 4.0.0-alpha.1
Selenium Grid version (if applicable):

**Comment by soulgalore** [comment]
I had a quick go at it and I could see that the serialization of the Chrome capabilities object never runs: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/chrome.js#L658-L671

So that the Chromedriver gets the full path to the extension instead of the BASE64 encoded version.

**Comment by soulgalore** [comment]
@jleyba any chance you can help me with this? I had a go some time ago but didn't fully understand how it should work so I could fix the issue.

**Comment by SebastienGllmt** [comment]
@soulgalore I managed to get it working by passing in a Buffer instead of a filepath
```
function encode(file) {
  var stream = fs.readFileSync(file);
  return new Buffer.from(stream).toString('base64');
}

...
new Builder()
  .setChromeOptions(new chrome.Options()
      .addExtensions(encode(path.resolve(__dirname, 'my_extension.crx'))));
```

**Comment by soulgalore** [comment]
@SebastienGllmt thanks, yes. You could even simplify to:

` fs.readFileSync(path.resolve(__dirname, 'my_extension.crx'), { encoding: 'base64' })`

The changelog needs to mention that the functionality changed.

**Comment by Hamzosb** [comment]
Hello guys
I read your solutions but didn't get it well
Can you please tell me what i need to modify in order to load my chrome extension ( **error : selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot process extension #1
from unknown error: cannot base64 decode** )

Python code : 
capabilities = {
    "browserName": "chrome",
    "version": "81.0",
    "enableVNC": True,
    "enableVideo": True,
    "goog:chromeOptions": {
         "args": ["disable-infobars", "start-maximized"],
         "extensions": [r"C:\Users\SAMSUNG\Dropbox\adb.crx"],
      }}


driver = webdriver.Remote(command_executor="http://selenoid/wd/hub",
                          desired_capabilities=capabilities)

**Comment by KatSick** [comment]
any updates on this? base64 extensions have a size limitation, unfortunately :(

**Comment by zshlomyz** [comment]
Hi, Please note that in version 4.1.0 (currently the latest), adding an extension caused an exception with the error - TimeoutError: timeout: Timed out receiving message from renderer: 1.965
  (Session info: chrome=96.0.4664.45)
It works using version 4.0.0.
Can you check, please?
Thanks
