### ISSUE TITLE
Load classes from buildr urls

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6677]
The new grid is pluggable, but it would be really helpful to be able to say something like "load the sessionmap from this jar", give a Buildr url (or maven coords in some other format), and have a classloader be created that does the hard work for us.

**Comment by raju249** [comment]
As discussed on [slack thread](https://seleniumhq.slack.com/archives/G0174SDHPQQ/p1595322044132300?thread_ts=1595247788.125500&cid=G0174SDHPQQ). This is already implemented via using `--ext` flag. The next comment explains about using `--ext` and [coursier](https://github.com/coursier/coursier) for whoever stumbles upon this issue.

/cc @shs96c @diemol

**Comment by raju249** [comment]
If someone stumbles upon this issue, here is how you can include alternate implementations using `--ext` flag and `coursier`.

For example, lets assume you want to use the `redisBackedSessionMap` [jar](https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-session-map-redis) to use the redis based implementation of session map.

you would run
`java -jar <path/to/selenium.jar> --ext <path to redis session map jar> sessions`
This would add the `RedisBackedSessionMap` implementation in the class path and things would work.

This is applicable for any alternate implementation that you would like to include (Eg: For a Node)

Other than this, you can also use, [coursier](https://github.com/coursier/coursier) to use third party dependencies and include them in classpath.
