### ISSUE TITLE
Closing a new windows and switching back causes NoSuchWindowException

### ISSUE THREAD

**Issue by tictac-freshmint** [SeleniumHQ/selenium#6678]
## 🐛 Bug Report

When I switch to a newly opened window and close it I cannot switch back to the main window (which still is displayed).

## To Reproduce

1. Trigger an action which opens a new window, which is the second window.
2. Switch to it and close it with Selenium API.
3. Try to switch back the the previous window.

This will generate a NoSuchWindowException although the window still exists on the desktop.

## Expected behavior

I want to be able to switch back to the original window in such a case.

The described behavior looks like a bug to me.

## Test script or set of commands reproducing this issue

// some action which triggers that the new window opens
getDriver().switchTo().window(handleOfNewlyOpenedSecondWindow).close();
getDriver().switchTo().window(handleOfFirstWindowWhichIsStillDisplayed);

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 70.0.3538.110
Browser Driver version: ChromeDriver 2.44
Language Bindings version: Java
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
