### ISSUE TITLE
getVersion() of IE's DesiredCapabilities not working.

### ISSUE THREAD

**Issue by sainivarun** [SeleniumHQ/selenium#668]
getVersion() of Internet Explorer's DesiredCapabilities is returning "" only instead of version number.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by sainivarun** [comment]
selenium version: 2.43
IE browser: 11,10,9
IEDriver: 2.43

Below are the queries:
 DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
1) capabilities.getVersion();
2)  capabilities.getCapability("version");

Expected result: version of IE browser like 11.*** or 10.*** or 9.***
Actual result: Both 1) & 2) are displaying blank values instead of IE version.

**Comment by barancev** [comment]
DesiredCapabilities.internetExplorer() does not know what IE version are you going to use.

To obtain the actual set of capabilities of a running driver:

RemoteWebDriver driver = new RemoteWebDriver(DesiredCapabilities.internetExplorer());
Capabilities actualCapabilities = driver.getCapabilities();
String ieVersion = actualCapabilities.getVersion();
