### ISSUE TITLE
RemoteWebDriver InvalidCastException with DriverOptions - C# Webdriver version 3.141.0

### ISSUE THREAD

**Issue by peterhughes0** [SeleniumHQ/selenium#6683]
## 🐛 Bug Report

There appears to be an issue with initialising the RemoteWebDriver with DriverOptions in Selenium version 3.141.0

System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]'.'

This is attempting to create a RemoteWebDriver session in Browserstack -( in the example, the credentials I have replaced with 'xxxxxx' but the code still displays the error.)

## To Reproduce

The code below reproduces the error exactly at the line:
```
 driver = new RemoteWebDriver(new Uri("http://hub.browserstack.com/wd/hub/"), chromeOptions);
```

The stack trace shows:
```
 at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)\r\n   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
```
```
class Program
{
    static void Main(string[] args)
    {
        IWebDriver driver;
        var chromeOptions = new ChromeOptions();
        chromeOptions.AddAdditionalCapability("browserstack.user", "xxxxxxxxxxxxxx");
        chromeOptions.AddAdditionalCapability("browserstack.key", "xxxxxxxxxxxxxx");
        chromeOptions.AddAdditionalCapability("browser", "Chrome");
        chromeOptions.AddAdditionalCapability("browser_version", "62.0");
        chromeOptions.AddAdditionalCapability("os", "Windows");
        chromeOptions.AddAdditionalCapability("os_version", "10");
        chromeOptions.AddAdditionalCapability("resolution", "1024x768");
        driver = new RemoteWebDriver(new Uri("http://hub.browserstack.com/wd/hub/"), chromeOptions);

        driver = new RemoteWebDriver(
          new Uri("http://hub-cloud.browserstack.com/wd/hub/"), chromeOptions
        );
        driver.Navigate().GoToUrl("http://www.google.com");
        Console.WriteLine(driver.Title);

        IWebElement query = driver.FindElement(By.Name("q"));
        query.SendKeys("Browserstack");
        query.Submit();
        Console.WriteLine(driver.Title);

        driver.Quit();
    }
}
```

I attempted to roll back to bindings version 3.9 and also replaced ChromeOptions with the obsolete DesiredCapabilities and the error no longer displayed.

Attempting to use DesiredCapabilities on version 3.141.0 produced the same error as before, only by rolling back, and also using DesiredCapabilities did this seem to work

i.e with Selenium Webdriver version 3.9 and:

```
var caps = new DesiredCapabilities();
            
            caps.SetCapability("browser", "Chrome");
            caps.SetCapability("browser_version", "62.0");
            caps.SetCapability("os", "Windows");
            caps.SetCapability("os_version", "10");
            caps.SetCapability("resolution", "1024x768");
            caps.SetCapability("browserstack.user", "xxxxxxxxxxxxxxxxxxx");
            caps.SetCapability("browserstack.key", "xxxxxxxxxxxxxxxx");

            driver = new RemoteWebDriver(
              new Uri("http://hub-cloud.browserstack.com/wd/hub/"), caps
            );
```
Was successful, and no error was displayed
## Environment

OS: Any - but Windows 10 in example
Browser: Any, but example is Chrome 62
Browser version: 62.0
Browser Driver version: - on Browserstack
Language Bindings version: C# 3.141.0

**Comment by jimevans** [comment]
@peterhughes0 As a diagnostic step, what happens if you call `chromeOptions.ToCapabilities();`?

**Comment by peterhughes0** [comment]
I should have mentioned - I also tried this, and exactly the same error

**Comment by jimevans** [comment]
@peterhughes0 I'm almost positive this is an issue with BrowserStack's remote end implementation. Looking at the code, the only raw cast that would cause the exception is when [this line](https://github.com/SeleniumHQ/selenium/blob/d1f8d7e468077ea0f2e65e58b5cd032c0833cbfc/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L1094) is called:

    Dictionary<string, object> rawCapabilities = (Dictionary<string, object>)response.Value;

While this _is_ a bug in the .NET bindings' source code, in that we shouldn't be blindly casting without testing that the cast will succeed, the `Value` property as parsed from the JSON response should always be a JSON object, which should be translated into a `Dictionary<string, object>` by the JSON parser. If that's not the case, then either the BrowserStack remote end is violating the protocol, or there's a more interesting issue in parsing what the remote end is returning.

**Comment by peterhughes0** [comment]
@jimevans ok thank you, I thought that given the fact that the Browserstack documentation is recommending the usage of DesiredCapabilities then perhaps something is out of date on their end. But I would imagine they perhaps may have changed something their end in order for this to fail in the more recent bindings, where it previously has worked, assuming that cast has always been there...

**Comment by peterhughes0** [comment]
I have tried the above (added the true argument to every .AddAdditionalCapability call) but I still see the same InvalidCastError.

**Comment by jimevans** [comment]
@peterhughes0 The following code works fine in my environment. I am able to create a session in BrowserStack without error.

    // Actual credentials obscured.
    string user = "xxxxxxxxx";
    string apiKey = "xxxxxxxxxxx";
    ChromeOptions options = new ChromeOptions();
    options.AddAdditionalCapability("browserstack.user", user, true);
    options.AddAdditionalCapability("browserstack.key", apiKey, true);
    options.AddAdditionalCapability("browser", "Chrome", true);
    options.AddAdditionalCapability("browser_version", "70.0", true);
    options.AddAdditionalCapability("os", "Windows", true);
    options.AddAdditionalCapability("os_version", "10", true);
    options.AddAdditionalCapability("resolution", "1024x768", true);

    IWebDriver driver = new RemoteWebDriver(new Uri("http://hub-cloud.browserstack.com/wd/hub/"), options);
    driver.Quit();

**Comment by peterhughes0** [comment]
Ok, that's interesting.. I have copied your exact code, but still the same error (with my own Browserstack credentials applied)

Just to confirm.. which version of the bindings is this using? I'm on 3.141.0

**Comment by jimevans** [comment]
I’m using tip-of-tree, which is equivalent to 3.141.

**Comment by peterhughes0** [comment]
@jimevans I have done some more digging, and I am pretty certain that this is caused by a firewall blocking the remote connection. So I'm guessing the invalid cast is basically that at some point the response coming back is actually completely inappropriate - and not from browserstack at all. So this is clearly not a bindings issue, but not even a browserstack issue. But something I am experiencing on my end.

Thank you for your help with this anyhow.
