### ISSUE TITLE
Merge Selenium IDE to the monorepo

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium#6685]
Merge Selenium IDE to the monorepo

**Comment by shs96c** [comment]
It seems wise to finish the migration to Bazel first.

**Comment by shs96c** [comment]
It also seems wise to begin this process by getting the main IDE repo building using Bazel, and then merging, rather than merging and then trying to fix the build.

**Comment by AutomatedTester** [comment]
This is a nice to have for Se4 and is being worked on but removing it from the Se4 tracker

**Comment by titusfortner** [comment]
No value tracking this as an issue right now. If/when we can do it, we will.
