### ISSUE TITLE
headless chrome not working in java 

### ISSUE THREAD

**Issue by batof** [SeleniumHQ/selenium#6688]
OS: Windows 7
ChromeDriver 2.44.609538
selenium verison 3.141.59

 it shows org.openqa.selenium.remote.ProtocolHandshake createSession
 Detected dialect: OSS

it works without adding
chromeOptions.addArguments("--headless");

already edited

**Comment by diemol** [comment]
Hi @batof,

Why did you delete/not use the issue template? 

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site). Without it, this issue will likely stale and be closed in a few days.

**Comment by batof** [comment]
## 🐛 Bug Report
headless chrome not working in java 

## To Reproduce
`public class TestDriver {
    public static void main(String[] args) {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--headless");
        driver = new ChromeDriver(chromeOptions);
        System.out.println("Going to load webpage");
        driver.get("https://example.com/");
        System.out.println("Succeed to load webpage");
    }
}
`


Detailed steps to reproduce the behavior:
Console print "Going to load webpage" and then stuck.

## Expected behavior

A clear and concise description of what you expected to happen.
Console should print "Going to load webpage" and "Succeed to load webpage".

## Test script or set of commands reproducing this issue
If I comment `chromeOptions.addArguments("--headless");`
it works.

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 70.0.3538.110 (64bits)
Browser Driver version: ChromeDriver 2.44.609538
Language Bindings version: Java 1.8.0_161
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
What if you set
`chromeOptions.setHeadless(true);`
instead of
`chromeOptions.addArguments("--headless");`
?

**Comment by diemol** [comment]
I just double checked and it should be possible with both options, I also created an [example](https://github.com/diemol/docker-selenium-issues/blob/master/selenium-issue-6688/src/test/java/ChromeHeadless.java) that you can check. 

Closing as we didn't get any more replies.
