### ISSUE TITLE
Selenium IDE: Open Timeout waiting for all images to load

### ISSUE THREAD

**Issue by Redirts** [SeleniumHQ/selenium#6689]
## 🐛 Bug Report

I recorded a selenium test via IDE on Firefox and every so often when I replay it (via selenese-runner in headless mode), it fails (timeout) on the first command "open" of the main URL.

Since I am collecting screenshots I can see that the page seems loaded but maybe not all resources (images, scripts) have completed.

This is annoying because my next command is to click on an link that I can see is available to click on the screenshot.

There should be a way to define if the open command should wait until all resources all loaded or not before proceeding to next command.

In this case I don't want to wait for the whole page to finish loading before clicking on an element I can check is already visible.

## To Reproduce
Any selenium script with a generic open command such as:
open("https://blitz.sapo.pt/")

## Expected behavior
It should move to the next command as soon as open is emitted.
If we want to wait for the page to load the next command can be waitForPageToLoad or if we want to wait for a certain element to be available we can use waitForElement..., etc.

## Test script or set of commands reproducing this issue
N/A

## Environment

OS: Red Hat Enterprise Linux Server 7.5 
Browser: Firefox (geckodriver)
Browser version: 57.0.4
Browser Driver version: GeckoDriver 0.23

**Comment by barancev** [comment]
Legacy Selenium IDE is not supported anymore. Consider migration to the new Selenium IDE implementation: https://github.com/SeleniumHQ/selenium-ide
