### ISSUE TITLE
dotnet: Make DriverService more easily extensible

### ISSUE THREAD

**Issue by FuchsiaSoft** [SeleniumHQ/selenium#6690]
## 🚀 Feature Proposal

Making some minor accessibility modifier changes and adding property accessors to some private fields to make DriverService (and perhaps subclasses) more readily extensible.

I am happy to do the changes myself in-line with contributor guidelines, just want a green light in principle before I bother.

## Motivation

Being able to run individual tests under different credentials (with for e.g. nUnit generic fixtures), with proper user impersonation not basic http auth means having to launch the browser process as that user, so it will handle NTLM etc.

I appreciate it's not Selenium's job to worry about platform and use-case specific things such as impersonation and NTLM auth, which is why the only change I propose is to make the classes more readily extensible so that people may easily make their own override for `DriverService.Start()`.

## Example

Using a framework such as nUnit which allows decoration of tests with multiple attributes for differing scenarios, it would then be possible to have a suite of tests which run under different user accounts all from the same code base, with no extra config considerations for the CI environment.

**Comment by jimevans** [comment]
@FuchsiaSoft I've just committed 03b5642, which creates the `DriverProcessStarting` event. This event is fired immediately before the call to the `Start` method of the process object. In its event arguments, the `ProcessStartInfo` object is exposed, which will allow a user to modify the start info (potentially including impersonated credentials) before the driver process starts. Would that suffice for your scenario?

**Comment by FuchsiaSoft** [comment]
@jimevans It does yes, nice and clean to implement my side for impersonation 😃

Thanks!, I'll keep an eye on the NuGet feed for the update.

**Comment by jimevans** [comment]
Given that the aforementioned commit resolves this feature request, I'm going to close the issue. Keep an eye out for the first 4.0 alpha releases, which will contain the change.
