### ISSUE TITLE
can support QQBroswer?

### ISSUE THREAD

**Issue by guohuanyang** [SeleniumHQ/selenium#6693]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by AutomatedTester** [comment]
Hi,

The Selenium project does not have the bandwidth to create a new driver however we have created a [specification](https://w3c.github.io/webdriver/) that allows people to build their own driver and it has a [centralised test suite](https://github.com/web-platform-tests/wpt).

I am happy to have discussions with the QQBrowser team if you can make introductions.
