### ISSUE TITLE
Support structured logging on stdout

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6694]
This allows systems such as DataDog to extract meaningful information from the logs. Which can only be a Good Thing.

**Comment by shs96c** [comment]
988667fe23d4637e55c67eb7bf2b4926fcedc7ee landed much of what we need for this to happen. The next step will be land a mechanism to add richer metadata to the log messages, presumably related to the information set on the tracing spans.

**Comment by AutomatedTester** [comment]
This was landed in #8583
