### ISSUE TITLE
W3C update request. clear() method should not use blur.

### ISSUE THREAD

**Issue by dmitryyu** [SeleniumHQ/selenium#6696]
W3C Requirements for clear() method contain "blur" action as the last step.

The step is really unnecessary.
Why the method should not execute blur event:.

1. clear() method is used when we want to clear text values in input elements. 
If user does the actions he still stays in the focused element.
(Please note: from the beginning it was implemented as a "reset" action. But reset - it's not a User's step so we should not have the method for repeating real user steps)

2. To handle the following case looks like a trick:
If we have input field which saves the value by using Enter action, without it it returns value to original one.
if real user does it: -  it looks OK:
- user selects the input
- clears all values (by using delete/backspace)
- types new values (and then press Enter) - as a result value will be correctly applied.

in the case the clear method cannot be used:
once blur is executed - value will be automatically returned to previous one. So clear is not suitable for the case... and as result:

3. Because clear() cannot be used in the case above we should simulate Keyboard actions:
- sendKeys(CTRL+A+DELETE)
but in the case why do we have clear() method ? -- need to remove it ?

4. To be honest everyone (No?) uses the method to clear values in an input elements, so backward compatibility should be... (and if somebody uses clear() method as reset action - need to add an appropriate method for it but i guess it's not necessary because "reset" doesn't correspond to any of real user step.

**Comment by dmitryyu** [comment]
FYI: 
@barancev

**Comment by jimevans** [comment]
@dmitryyu The request you’re making would need to be addressed in the specification. You would need to file an issue with [that repository](
https://github.com/w3c/webdriver). In point of fact, there is already [an issue](
https://github.com/w3c/webdriver/issues/1354) that discussed the blur event during element clear. As a point of setting appropriate expectations, however, given that the spec is already at Recommendation, I don’t think there’s a lot of enthusiasm for changing that part of the spec. At any rate, this repo is probably not the place to affect the change you want.

**Comment by dmitryyu** [comment]
Thanks for the quick response... I will close the issue.
