### ISSUE TITLE
Migrate build from buck to bazel

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6698]
- [ ] General
  - [ ] Stamp builds correctly
- [ ] Java
  - [x] Export to Maven Central
  - [ ] Java 9 modules
  - [ ] Package zips for java
- [ ] Python
  - [x] Create `py_import` to import wheels
  - [ ] Python wheel creation

**Comment by dagguh** [comment]
Out of curiosity - did you consider Gradle? It's a very established build system, also excelling at speed and incremental builds (like Buck). It has a very rich ecosystem and e.g. [Java 9 modules are supported very well](https://guides.gradle.org/building-java-9-modules/).

It's worrying that Bazel doesn't have a stable release yet.

**Comment by sschuberth** [comment]
Sorry if this is becoming slightly off-topic, but I'd like to add my vote for Gradle, esp. as I find it worrying that "[Bazel doesn't offer any built in feature to resolve transitive Maven dependency](https://groups.google.com/d/msg/repo-discuss/z10230ap-Ck/5OFIeoUhCwAJ)".

**Comment by laurentlb** [comment]
@sschuberth: See this recent blog post: https://blog.bazel.build/2019/03/31/rules-jvm-external-maven.html
(@jin and @dkelmer may help if needed)

> It's worrying that Bazel doesn't have a stable release yet.

What do you mean?

**Comment by sschuberth** [comment]
@laurentlb, nice to see some demoscener in here 😉 And thanks for pointing out that blog post, that's relieving.

**Comment by barancev** [comment]
Also we don't use Maven transitive dependencies in Selenium project, we define all dependencies explicitly ourselves and store all deps in the repository. So Selenium can be built even without access to the Internet (as soon as you cloned the repo and installed buck (or bazel, in future)).

**Comment by shs96c** [comment]
Selenium supports more than just Java: our build system needs to support Java, .Net, Python, Ruby, and (soon) Go. Gradle does not support all these options, and therefore is out of consideration.

**Comment by diemol** [comment]
This is in the done column https://github.com/SeleniumHQ/selenium/projects/2, so I assume this is done.
Feel free to reopen if something is missing.
