### ISSUE TITLE
JavaScript bindings uses `eval` for parsing HTTP response

### ISSUE THREAD

**Issue by erykpiast** [SeleniumHQ/selenium#670]
In `http.js` you can find [`goog.json.parse` method](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/http/http.js#L192-L193), used for parsing response of HTTP request. Internally this method [tries to run passed string as a code](https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/third_party/closure/goog/json/json.js#L102) (yes, through `eval`).

Don't you think it is not reasonable to run any code sent from some server in your application? Selenium server is very often external service, like BrowserStack or SauceLabs. Me, personally, don't trust them as much to give them total control, even over my testing environment.

**Comment by lukeis** [comment]
if running in node, I suppose either we or you could set goog.json.USE_NATIVE_JSON to true and then it would use node's JSON.parse method instead.

I believe the intention of the javascript bindings was to be able to run them in a browser too, so if that were to go into the native bindings it would need to be guarded.

**Comment by erykpiast** [comment]
Hmm, what is desired browser support in that case? SInce [a couple of years
ago](http://caniuse.com/#search=JSON) browsers have JSON.parse built-in.

2015-06-18 18:23 GMT+02:00 Luke Inman-Semerau <notifications@github.com>:

**Comment by lukeis** [comment]
indeed... @jleyba think we should enable that variable to avoid the 'eval' call in closure?

**Comment by jleyba** [comment]
This was blown out of proportion:  `goog.json` validates strings before calling `eval`. Not pushing a new version to npm for this.

https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/third_party/closure/goog/json/json.js#L99

**Comment by erykpiast** [comment]
Hmm, I didn't notice that. But can you tell me, how `RegExp` plus `eval` is better than `JSON.parse`?

**Comment by jleyba** [comment]
I didn't say it was better. I said I don't consider the change significant enough to warrant pushing a new version to npm.

**Comment by erykpiast** [comment]
Got it. So, you expect differences between standard and `goog` implementation?

**Comment by jleyba** [comment]
`goog.json.parse` will accept input like `"[,,]"`:

```
var x= goog.json.parse('[,,]');
console.log(x.length);  // 2

var y = JSON.parse('[,,]');
// SyntaxError: Unexpected token ,
```

For more info, see comments in `goog.json.isValid`:
https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/third_party/closure/goog/json/json.js#L42

**Comment by erykpiast** [comment]
So it seems like a breaking change for some cases. What can I say, I just wanted to help!

**Comment by jleyba** [comment]
Breaking change if this code was used by some protocol buffer JavaScript libraries. The WebDriver protocol only supports valid JSON, so this change should be transparent to the user.
