### ISSUE TITLE
Javascript set current time of video don't work 

### ISSUE THREAD

**Issue by thaichau298** [SeleniumHQ/selenium#6700]
Sometimes the javascript to set current time don't work but when i get current time, the time is time which i had set.  Any solution for this issue 

Code:
[Code.txt](https://github.com/SeleniumHQ/selenium/files/2622542/Code.txt)

Selenium : 3.141.59
Browser : Edge (version 42)
Window 10

**Comment by lmtierney** [comment]
This has nothing to do with selenium other than the fact that you're using the javascript executor
