### ISSUE TITLE
Ensure traces are injected and read to and from HTTP calls.

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#6703]
Without this, the traces only really make sense in the standalone mode.

**Comment by dratler** [comment]
Hi @shs96c ,
can you share more light what is required to do ?
are these traces been send to a Driver Log ?

**Comment by pujagani** [comment]
For most configurations, the traces are correctly ordered, complete and match the request flow. However, adding few spans and events specially for error cases is needed. I have documented the findings here  https://gist.github.com/pujagani/2e2de5d79a2f30da5edb1582208130aa

**Comment by AutomatedTester** [comment]
Closing this as it appears to be done now
