### ISSUE TITLE
page have cross domain iframe inside iframe i able to switch first iframe but unable to access its elements

### ISSUE THREAD

**Issue by pranaynagpure321** [SeleniumHQ/selenium#6707]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by pranaynagpure321** [comment]
I am running test on payment page, but it seems there are multiple iframes, i have switched to #idpFrame (Id) but not able to access elements inside it, Therefore i cannot switch to second iframe(#amadeusFrame) inside first iframe. I read issue Posted under cross domian Iframe problems
can someone help me please here.
[payment_thomas.zip](https://github.com/SeleniumHQ/selenium/files/2632746/payment_thomas.zip)

i have attached html files here, please disable java Script before opening html file.

**Comment by pranaynagpure321** [comment]
sry for that

**Comment by diemol** [comment]
Hi @pranaynagpure321,
 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
