### ISSUE TITLE
view-source ("ctrl+u" equivalent) not supported in python Selenium

### ISSUE THREAD

**Issue by ketankr9** [SeleniumHQ/selenium#6708]
### Please note that this issue tracker is not a help form and this issue will be closed.

I searched every where but I am not able to get page source from python Selenium Driver, I am talking about **view-source:https://githhub.com/** equivalent not the current DOM (inspect element).

driver.page_source gives only the current page source as viewed from the browser, but I want the page source as is sent by the server, unmodified by javascripts.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
