### ISSUE TITLE
Selenium Grid- Masterhub for multiple hubs.

### ISSUE THREAD

**Issue by jyotibaviskar** [SeleniumHQ/selenium#671]
Hi,

We are now running script using selenium grid(Node-Hub).
But its sequential & took much time. We want to make it parallel to save time.
(Using thre hubs which will be controlled by one masterhub)

We need to run three batches of test cases paralley.
By making use of three hub using selenium grid.
how can we trigger the execution at the same time on all three hubs?

Can we have one master hub for those three?
If Yes, how to establish a hub to hub connection?

Can we have one machine as node for masterhub & hub for all other nodes in selenium grid?

**Comment by ddavison** [comment]
you can use custom test runners to run parallel tests.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
