### ISSUE TITLE
throws exception if element does not display

### ISSUE THREAD

**Issue by vitalisc** [SeleniumHQ/selenium#6715]
OS:  Windows 8
Browser: Chrome
Browser version:  70.0.3538.110 
Selenium version (if applicable): 3.141.59 

here is my code sample 

if (driver.FindElement(PLAYBUTTON).Displayed) 
            {
                while (driver.FindElement(PLAYBUTTON).Displayed) 
                {
                    driver.FindElement(PLAYBUTTON).Click();
                    Thread.Sleep(3000);

                    
                }
            }

what i tried to do above is , if the element is displayed then perform the while action but if not , it perform the action on the else statement . The  challenge here is that it throws exception  when the element is not found 
please how do i achieve this 
thanks

**Comment by diemol** [comment]
Hi @vitalisc,

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by vitalisc** [comment]
they are dead areas to seek for help

**Comment by diemol** [comment]
This is not true at all, you just joined the Slack chat and we are there replying to your questions, https://seleniumhq.slack.com/archives/C0ABCS03F/p1543829561256800

**Comment by vitalisc** [comment]
am sorry it took me some seconds to figure out how to use the slack
i was first welcomed by bot , so i got confused
