### ISSUE TITLE
IEDriver doesn't move cursor to (0, 0) first time

### ISSUE THREAD

**Issue by j0tunn** [SeleniumHQ/selenium#672]
```js
var browser = wd.promiseRemote(...);
...
var body = browser.elementByCssSelector('body');
wd.moveTo(body, 0, 0); // Does nothing!
```

The problem is next: `InputManager` object on construction inits last known mouse position as (0, 0). We are trying to move to (0, 0). And in such case there is a false-positive check: https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/InputManager.cpp#L500

**Comment by jimevans** [comment]
Merged in be99111
