### ISSUE TITLE
Add support for 'strictFileInteractability' W3C capability

### ISSUE THREAD

**Issue by burg** [SeleniumHQ/selenium#6721]
Per recent spec draft changes, 'strictFileInteractability' is now a standardized capability. At a minimum, it needs to be added to the whitelist in remote/webdriver.py so that it does not get stripped. I don't know what else should be done for other language bindings.

**Comment by lmtierney** [comment]
Added to acceptable capabilities in python 9a59ba0

**Comment by p0deje** [comment]
Added in e2acf0c7c6cbd01d0ba117cb2d0c57def7e2e586 to Ruby

**Comment by barancev** [comment]
Commit 368bd78ccbed5c2905804009f3f7514dce7ec140 adds this capability to Java binding.
Type-safe methods in Options classes are coming soon.

**Comment by jimevans** [comment]
This landed in .NET in b4ecd81, complete with type-safe property in the `DriverOptions` class.

**Comment by barancev** [comment]
Added to Java binding by 031cedd270cace9fd74527e0885c7875a468131b

**Comment by Harsha509** [comment]
Added to c-nodejs with merge https://github.com/SeleniumHQ/selenium/pull/7850

**Comment by shs96c** [comment]
Closing this. Thank you to everyone involved in getting this done!
