### ISSUE TITLE
Unable to locate element in IE11 using Selenium with C#

### ISSUE THREAD

**Issue by shiyaf** [SeleniumHQ/selenium#6722]
I am having a drop down box which will get enabled and disabled based on some previous data selection,
When it gets disabled one attribute "disabled" will get added in DOM with value "disabled", but in IE11 i am always getting error "Unable to find element with css selector == select[id="releaseNo"][disabled="disabled"].

Here one thing i observed is whenever i use attribute "disabled" , it is not working

Can anyone help on this issue, since i want to check the element is got disabled.
![screenshot_when_item is in disabled state](https://user-images.githubusercontent.com/31208286/49449535-1c677c80-f801-11e8-84e0-a1e43c869f11.PNG)
![screenshot_when_item is in enabled state](https://user-images.githubusercontent.com/31208286/49449536-1c677c80-f801-11e8-9972-c59b7f16fa08.PNG)

**Comment by diemol** [comment]
Hi @shiyaf,

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
