### ISSUE TITLE
ECONNRESET may cause duplicate request even if the first succeeded

### ISSUE THREAD

**Issue by hurrikam** [SeleniumHQ/selenium#6723]
## 🐛 Bug Report

In certain environments a command request could raise `ECONNRESET` even if the command data has been already received and the `end` event processed. That causes the same command to be executed twice.

## To Reproduce

This behaviour is reproducible with our custom WebDriver server implementation (Node JS).
The server is configured with HTTPS and valid corporate SSL certificates.
The WebDriver test runs on a development machine.

Detailed steps to reproduce the behavior:

Given the set-up above, when launching the test:

1. the `sendRequest` function in the module `node_modules/selenium-webdriver/http/index.js` is first called to create a new session
2. `response.on('data')` and `response.on('end')` for the request are fired and correctly processed
3. however, right after the `request.on('error')` is fired too with `e.code === ECONNRESET`
4. a delayed re-request is scheduled (using `setTimeout`)

This will cause that command to run twice and to create two sessions on the custom WebDriver server.
Same applies to other WebDriver commands.

## Expected behavior

Whenever the `end` event has been processed then a flag should exists which causes a following `ECONNRESET` event to be ignored.
I applied a local fix by adding a `request.ignoreECONNRESET` flag and that makes my test run correctly:

```
response.on('data', body.push.bind(body));
    response.on('end', function() {
      var resp = new httpLib.Response(
          /** @type {number} */(response.statusCode),
          /** @type {!Object<string>} */(response.headers),
          body.join('').replace(/\0/g, ''));
      onOk(resp);
      request.ignoreECONNRESET = true;
    });
  });

  request.on('error', function(e) {
    if (e.code === 'ECONNRESET') {
      if (request.ignoreECONNRESET) {
        console.log('response was received anyway. Ignoring ECONNRESET');
        return;
      }
      console.log('Repeating request due to error');
      setTimeout(function() {
        sendRequest(options, onOk, onError, opt_data, opt_proxy);
      }, 15);
    } else {
```

## Test script or set of commands reproducing this issue

The code above (without patch) doesn't handle the edge case where the specific error is fired even though the `onOk(resp)` handler has been already called for the request.

## Environment

OS: Windows 10
Browser: Miscellaneous browsers on Smart TVs and consoles
Browser version: Miscellaneous
Browser Driver version: Custom Node JS implementation
Language Bindings version: selenium-webdriver 3.6.0 up to 4.0.0 Alpha
Selenium Grid version (if applicable): N/A

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
