### ISSUE TITLE
java.lang.ClassCastException occuring in 3.14, 3.141.5, 3.141.59 but working fine till 3.13.0

### ISSUE THREAD

**Issue by arunvincy** [SeleniumHQ/selenium#6727]
## Failure Error

Running TestSuite
Testing in Browserie
Started InternetExplorerDriver server (32-bit)
3.141.0.0
Listening on port 27497
Only local connections are allowed
Dec 05, 2018 1:53:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 46.995 sec <<< FAILURE! - in TestSuite
Qualified_BD_BS(com.basic.NewTest)  Time elapsed: 42.274 sec  <<< FAILURE!
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to org.openqa.selenium.internal.WrapsDriver

## Last working Selenium version

Worked up to version: 3.13.0

Stopped working in version: 3.14.0

## To Reproduce

WebDriver driver;
    String name;
    WebElement parentElem;

    public kuidropdown(WebElement parentElem) {
        this.parentElem = parentElem;
        name = parentElem.getAttribute("aria-owns");
       // System.out.println(name);
        this.driver = ((WrapsDriver) parentElem).getWrappedDriver();

## Environment

OS: Windows 7
Browser: Chrome, IE
Browser Driver version: IEDriverServer 3.14

**Comment by barancev** [comment]
org.openqa.selenium.internal.WrapsDriver moved to org.openqa.selenium.WrapsDriver, update your code
