### ISSUE TITLE
Ie11 : is not showing all the cookies. 

### ISSUE THREAD

**Issue by kasthurk** [SeleniumHQ/selenium#673]
I am trying to read the cookies for IE11 browser but driver.manage().cookies is showing very few cookies.

but the same is working for chrome.

---------------
i can see the cookie which am interested is availabe in network log(Developper tool).

how can we get it using selenium?

**Comment by jimevans** [comment]
The IE driver is limited to retrieving only those cookies visible via JavaScript (i.e, only those available through `document.cookie`). The IE F12 Developer Tools may be able to display other cookies as well, but they have a special access to internal APIs of the browser. Until and unless Microsoft exposes and documents those APIs, the IE driver cannot do anything more than it already does.
