### ISSUE TITLE
Hovering Not supported on IE11 browser with Selenium 3.141.59 

### ISSUE THREAD

**Issue by Raamkumarayaveeran** [SeleniumHQ/selenium#6734]
## 💬 Hovering Not supported on IE11 browser with Selenium 3.141.59 

Hover Function not working in selenium web driver for IE 11 browser.

Tried the possible ways to overcome this scenarios like JavaScript, actions and few IE setting configuration. Since our code will execute over Jenkins we didn't try with Robot class.

Kindly help us, if you have idea to perform Hover on IE11 browser with selenium web driver

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
