### ISSUE TITLE
Object of action class not working for multiple times

### ISSUE THREAD

**Issue by ishah09** [SeleniumHQ/selenium#6735]
## 🐛 Bug Report

Object of action class not working for multiple times, which do not performed click. If we use same object for multiple click event, it throwing staleelementreference exception which does not mean. Same thing is working, if we use different objects for each separate click. 

## To Reproduce

-Use action click multiplr times anywhere with same object. Note: Found this issue for C# selenium version only. 

## Expected behavior

By single object, it should working properly. 

## Test script or set of commands reproducing this issue

        class temp 
        {
        [Test]
        public void temps()
        {
            IWebDriver driver = new ChromeDriver();
            driver.Url = "http://google.com";
            Actions obj1 = new Actions(driver);
            IWebElement temp1=  driver.FindElement(By.Name("q"));
            temp1.SendKeys("Selenium");
            Thread.Sleep(1000);
            obj1.MoveToElement(driver.FindElement(By.Name("btnK"))).Click().Perform();
            Thread.Sleep(3000);
            try
            {
                Actions obj2 = new Actions(driver);
                obj2.MoveToElement(driver.FindElement(By.XPath("//a[@href='https://www.seleniumhq.org/']"))).Click().Perform();

            **// If you try here, with obj1 which used just above. It will not work.**            
           //obj1.MoveToElement(driver.FindElement(By.XPath("//a[@href='https://www.seleniumhq.org/']"))).Click().Perform();
            }
            catch (Exception e)
            {
                e.ToString();
            }
            Thread.Sleep(1000);
        }
       }
 
## Environment

OS: Windows 10
Browser: Chrome
Browser version: 70.0.3538.110 - 64 Bit
Browser Driver version: ChromeDriver 2.43
Language Bindings version: C#
Selenium : 3.14

**Comment by jimevans** [comment]
Calling `Perform()` on an Actions instance does not clear the previous actions in the queue. This is a feature designed to allow users to reuse the same sequence of actions, not to reuse the same `Actions` object with new actions. Using a new `Actions` object (which is fairly lightweight, and one should not be afraid of creating) is the right approach.

**Comment by ishah09** [comment]
I am not clear with your instruction, Can you elaborate it with simple example. OR correction in my above example.
