### ISSUE TITLE
Cannot be saved in a normal format in chrome for win10

### ISSUE THREAD

**Issue by SmalBox** [SeleniumHQ/selenium#6736]
## 🐛 Bug Report

In chrome of win10, Selenium IDE only saves scripts with the suffix ".txt". This prevents the script from being imported again.

## To Reproduce

Just in chrome for win10,  open selenium and create a  project, then click the button of saving it will pop up a window. The save format in the lower right corner is just ".txt".

When the opened project, it will not be found. Even if you select all files and find it, will reminder "Error migrating project" and "Unknown file was received".

## Expected behavior

It will be saved as ".side" formed.

## Test script or set of commands reproducing this issue

This  problem occurs in the Selenium IDE, so no scripts are required for this problem

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 72.0.3626.7
Selenium Grid version (if applicable): 3.4.5

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #517](https://github.com/SeleniumHQ/selenium-ide/issues/517) via [**ZenHub**](https://www.zenhub.com/)

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #516](https://github.com/SeleniumHQ/selenium-ide/issues/516) via [**ZenHub**](https://www.zenhub.com/)
