### ISSUE TITLE
Setting of proxy on chrome browser dont work anymore 

### ISSUE THREAD

**Issue by vitalisc** [SeleniumHQ/selenium#6737]
OS:  Windows 8.1
Browser:  Chrome
Browser version:  70.0.3538.110 
Browser Driver version: ChromeDriver 2.43, 
Language c#
Selenium Grid version : 3.141.59 

I tried to change my browser ip address  using the code below , but it didnt  work, 
i dont know if there is another new way to do this please advise 

thanks

OpenQA.Selenium.Proxy _proxy = new OpenQA.Selenium.Proxy();
                    _proxy.HttpProxy = 209.97.155.3:3128
                    ChromeOptions options = new ChromeOptions();
                    options.Proxy = _proxy;

                    var driverService = ChromeDriverService.CreateDefaultService();
                    driverService.HideCommandPromptWindow = true;

                    var driver = new ChromeDriver(driverService, options, TimeSpan.FromSeconds(70));

**Comment by barancev** [comment]
Seems to be a regression issue in chromedriver, please report it to https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by barancev** [comment]
Actually, you don't need, it seems to be caught already: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2653

**Comment by barancev** [comment]
Reading the comments I'm not sure it's the same issue that hits you. So you'd better report your issue anyway, and let chromedriver developers decide if it's a duplicate or not.
