### ISSUE TITLE
Please add docs/release notes to explain why Third Party dependencies have been massively slashed

### ISSUE THREAD

**Issue by gwtuser** [SeleniumHQ/selenium#6740]
In the [selenium-server-standalone-3.141.0.jar](http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.0.jar) (and 3.141.5/3.141.59), there's been a massive cut in the included 3rd party dependencies, slashing the size of the JAR in half (20mb => 10mb).  I confirmed by looking at the pom that indeed many dependencies such as htmlunit have been removed.

Can you add docs somewhere (e.g. release notes), explaining why this happened, and what, if any, impact it will have?  For example, perhaps they are no longer used in Selenium 3 but no one realized it.

**Comment by AutomatedTester** [comment]
this is all documented in the changelog https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG

**Comment by gwtuser** [comment]
No, actually it's not.  Did you think I posted the issue without reading the existing changelog?  There is no mention of the dependencies being massively chopped, including in particular htmlunit.

**Comment by gwtuser** [comment]
Note that there were some 30+ dependencies in 3.14, and only 10 in 3.141.  There is no mention of this in the release notes for 3.141.  I didn't read older release notes as they wouldn't be relevant to 3.141.

**Comment by diemol** [comment]
@gwtuser yes, it is mentioned in the changelog, see https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L39

The Apache HttpClient was removed (which was deprecated some previous to that one) and that is the difference you see.

**Comment by barancev** [comment]
I've added extra info by commit 36f3bca8d8bd281d43ed78a2e5f14cc20a574579
