### ISSUE TITLE
Chrome 71 [ClearText does not work for REACT input box]

### ISSUE THREAD

**Issue by ckzgraphics** [SeleniumHQ/selenium#6741]
## 🐛 Bug Report

While running test against a REACT webpage on Chrome 71 + Windows 10, 'clear text' command does not clear the input box contents.

## To Reproduce

Detailed steps to reproduce the behavior:

[In Chrome 71 + Windows 10] 

1. Open URL- [https://foxhound87.github.io/mobx-react-form-demo/dem](https://foxhound87.github.io/mobx-react-form-demo/dem)
2. Use 'Clear Text' command (POST /session/<SESSION_ID>/element/<ELEMENT_ID>/clear)

## Expected behavior

The text should be cleared from the text box.

## Test script or set of commands reproducing this issue

**You can use the following GIST to replicate the issue-** [https://gist.github.com/ckzgraphics/418cf54ed3a60f057fcc0834e9bef010](https://gist.github.com/ckzgraphics/418cf54ed3a60f057fcc0834e9bef010)

**BrowserStack Session [executed on REACT webpage][FAILED]-** [a21750b06f9ec90ccc35c62c7f83da534bb7b253](https://automate.browserstack.com/builds/dc03f2ef4188580b1aecf0ae6ec06dbded367de4/sessions/a21750b06f9ec90ccc35c62c7f83da534bb7b253?auth_token=29ff3749fe7566965c459d223a3743c4b840b97ffb394ed2a98a81282a274026)

**Selenium Logs (for the above session)-** [https://gist.github.com/ckzgraphics/1968040180812899dc771df69ff5f7eb](https://gist.github.com/ckzgraphics/1968040180812899dc771df69ff5f7eb)

**BrowserStack Session [executed on SIMPLE webpage][PASSED]-** [e3f6831f153a002d874a6fcc50ee37f8feeaadb2](https://automate.browserstack.com/builds/dc03f2ef4188580b1aecf0ae6ec06dbded367de4/sessions/e3f6831f153a002d874a6fcc50ee37f8feeaadb2?auth_token=fbd3805fe5163e2c54f009f96f8f2aa3dc1a80829b84eaaa12af3b2db2087e56)

**Selenium Logs (for the above session)-** [https://gist.github.com/ckzgraphics/1589742d8ca96836018237e1057548e9](https://gist.github.com/ckzgraphics/1589742d8ca96836018237e1057548e9)

## Environment

**OS:** Windows 10
**Browser:** Chrome
**Browser version:** 71
**Browser Driver version:** 2.44

**Language Bindings version:**
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Selenium Grid version (if applicable):** 3.14.0

**Comment by yboi** [comment]
The same an issue when using pytest.

**Comment by barancev** [comment]
Yes, this input is tricky...
```
      WebElement ele = webDriver.findElement(By.xpath(".//input[@name='username']"));
      new Actions(webDriver).click(ele)
        .pause(200).keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL)
        .pause(200).sendKeys(Keys.BACK_SPACE)
        .pause(200).sendKeys("KOOKOK").perform();
```

**Comment by barancev** [comment]
In debugger, step by step, you can see that selenium clears the input, but later the application restores its value. The reason is simple: `clear` operation is not fair, it does not match any human user action. Selenium is cheating to clear an input, but this cheating does not work for sophisticated fields with intelligent event handlers. So you have to act like a human user, that is what `Actions` class is intended for.

**Comment by ckzgraphics** [comment]
> In debugger, step by step, you can see that selenium clears the input, but later the application restores its value. The reason is simple: `clear` operation is not fair, it does not match any human user action. Selenium is cheating to clear an input, but this cheating does not work for sophisticated fields with intelligent event handlers. So you have to act like a human user, that is what `Actions` class is intended for.

I am using 'ele.clear();' not the Action class!! The same works properly on older Chrome browser. You think I should create the same in Chromium project?

**Comment by ckzgraphics** [comment]
The behaviour was logged on [Chromium(Chromedriver)[2702]](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2702&q=&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary)

**Comment by yboi** [comment]
barancev можеш дать линк на автомейш чат? раньше юзал, но потерял

**Comment by mushtaqsayyed** [comment]
Using the following workaround resolved the behaviour:
driver.findElement(By.name("username")).sendKeys(Keys.chord(Keys.CONTROL,"a", Keys.DELETE));

**Comment by barancev** [comment]
@yboi
https://join.skype.com/nKjAhLUdpWRl
https://t.me/qa_automation
https://software-testers.herokuapp.com/, #automation channel

**Comment by sjethvani** [comment]
I am having angular input tag , which wasn't getting cleared using driver.findElement().clear() in chrome V71 (chrome driver 2.45) . I used below code , which worked for me

```
WebElement ele = webDriver.findElement(By.xpath(".//input[@name='username']")); 
new Actions(webDriver).click(element).sendKeys(Keys.END).keyDown(Keys.SHIFT).sendKeys(Keys.HOME).keyUp(Keys.SHIFT).sendKeys(Keys.BACK_SPACE).sendKeys("").perform()
```

**Comment by aleksandr-kotlyar** [comment]
Hello friends!
I want to share with you my solution for history, even if the issue is closed. 
Alexei's @barancev [variant](https://github.com/SeleniumHQ/selenium/issues/6741#issuecomment-447057035) **didn't work** for my current project react app and password input field.
> ```
>       WebElement ele = webDriver.findElement(By.xpath(".//input[@name='username']"));
>       new Actions(webDriver).click(ele)
>         .pause(200).keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL)
>         .pause(200).sendKeys(Keys.BACK_SPACE)
> ```
And yesterday i have created my own solution, which **works**:
```
while field_password().get_attribute('value') != '':
    field_password().send_keys(Keys.BACKSPACE)
```
**AND** still **works**:
```
while len(field_password().get_attribute('value')) != 0:
    field_password().send_keys(Keys.BACKSPACE)
```
where `field_password()` is a `WebElement`, or to be fair `SeleneElement`, from [selene](https://github.com/yashaka/selene) library:
```
def field_password() -> SeleneElement:
    return s('input[name="password"]')
```
But for pure selenium my solution should also work.

I hope it would help someone someday.

Best regards,
Aleksandr.
