### ISSUE TITLE
grid documentation: I needed to remove docker and virbr0 (kvm) network interfaces

### ISSUE THREAD

**Issue by DieterRogiest** [SeleniumHQ/selenium#6750]
## 🐛 Bug Report

For a real selenium grid (on two real physical computers, no VMs), to get the linux node use the right network interface, I had to remove from it the docker and vibr0 (kvm) network interfaces.

Can this info be added to the grid documentation? Not everybody is a networking expert.
Is it possible to fix this so that the node uses the correct network interface?

## To Reproduce

on my home network:
hub (a Macbook laptop): 
java -jar selenium-server-standalone-3.141.59.jar -role hub
node (Kubuntu 18.04 with docker and kvm installed): 
java -Dwebdriver.chrome.driver=./chromedriver -Dwebdriver.firefox.driver=./geckodriver -jar selenium-server-standalone-3.141.59.jar -role node -hub http://192.168.0.171:4444/grid/register -port 5555

The hub output showed that the node got registered and on http://192.168.0.171:4444/grid/console I could see the usual info.
Running my maven command on the macbook to run a simple test failed. 
In the hub output I saw "marking the node as down because it can't be reached for 2 tries" and it registered again (continually if I recall correctly).
In the hub output I noticed that the node was registered with an ip different from 192.168.0.xxx and on the node the command ifconfig showed me that this was the ip of docker network interface.
So on the node I stopped docker and disabled it (systemctl stop docker and systemctl disable docker and reboot) and then I restarted the node command.
The node then registered on the hub with the ip of virbr0 interface (in the past I had installed kvm on it). With three commands from https://ciberciti.biz/faq/linux-kvm-disable-virbr0-nat-interface I removed that interface as well.
Then the node could connect to the grid with its normal network interface 192.168.0.xxx
and my maven command could successfully run with browsers getting launched on the node.

## Expected behavior

The command to run the node should use the "normal" network interface, not blindly picking docker or virbr0 interfaces.
Somewhere on stackoverflow I read that these things are not a selenium issue but a matter of network configuration. I doubt every selenium user is a networking expert.
Please add this info somewhere to the grid documentation so that others can benefit from it too.

(also my apologies for my other bad report the other day about this, yesterday I was feverish and had a bad headache)

**Comment by diemol** [comment]
Hi @DieterRogiest,

That is the expected behaviour, if `-host` is not specified, the hub/node will bind to all public non-loopback interfaces of the machine. So in cases of special network configurations, it is better to specify the desired host through the `-host` flag.

I added a note about that in the docs, see https://seleniumhq.github.io/docs/grid.html#a_note_about_the_host_flag
