### ISSUE TITLE
NoSuchSessionException

### ISSUE THREAD

**Issue by skAutomation12** [SeleniumHQ/selenium#6753]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by skAutomation12** [comment]
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'
Driver info: driver.version: RemoteWebDriver 


I didnt call driver.quit() 
Scenario: 
I have a suite of 50 test divided between 2 testNG class files. 
Class1 completely runs; Class 2 --execution breaks at 10th test after executing halfway.  and 11th continues as usual. Please help me fix this issue.

**Comment by diemol** [comment]
Hi @skAutomation12 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
