### ISSUE TITLE
Chrome can be opened using IE instance or Firefox instance

### ISSUE THREAD

**Issue by chirantan2012** [SeleniumHQ/selenium#6755]
## 🐛 Bug Report

This piece of code is opening chrome and accessing the web page though IE instance or Firefox instance is created, as the path is pointed to chromedriver.exe. There must be a checking whether the correct driver has opened. In other combinations/vice versa combinations  it is not occurring and the chrome is prohibited from occurring.

Detailed steps to reproduce the behavior:
import java.io.File;

import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

public class Main {

	public static void main(String[] args){
		
		String path = System.getProperty("user.dir")
				+ File.separator
				+"drivers"
				+File.separator
				+"chromedriver.exe";
		
		System.setProperty("webdriver.ie.driver", path);
		InternetExplorerDriver driver = new InternetExplorerDriver();
		
		//OR
		
		//System.setProperty("webdriver.gecko.driver", path);		
		//FirefoxDriver driver = new FirefoxDriver();		
		
		driver.get("https://www.google.com");
		driver.findElement(By.name("q")).sendKeys("google");
		driver.quit();

	}

}

## Expected behavior
Chrome should not open.
Should have thrown an error like other cases, " org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities"
## Test script or set of commands reproducing this issue
import java.io.File;

import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;

public class Main {

	public static void main(String[] args){
		
		String path = System.getProperty("user.dir")
				+ File.separator
				+"drivers"
				+File.separator
				+"chromedriver.exe";
		
		System.setProperty("webdriver.ie.driver", path);
		InternetExplorerDriver driver = new InternetExplorerDriver();
		
		//OR
		
		//System.setProperty("webdriver.gecko.driver", path);		
		//FirefoxDriver driver = new FirefoxDriver();		
		
		driver.get("https://www.google.com");
		driver.findElement(By.name("q")).sendKeys("google");
		driver.quit();

	}

}
Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: <Windows 10 >
Browser: <Chrome>
Browser version: <71.0.3578.80>
Browser Driver version: <ChromeDriver 2.45>
Language Bindings version: <Java 1.8.0.181> 
Selenium Webdriver version: <3.12.0>

**Comment by cgoldberg** [comment]
seems like expected behavior to me.

**Comment by barancev** [comment]
Yes, it's expected behavior. Selenium is indifferent to executable file names. If you have an IEDriverServer executable and decided to give it a name 'chromedriver.exe' it's up to you. Selenium will start any file you pointed to as a driver executable.
