### ISSUE TITLE
Extract XPath from element

### ISSUE THREAD

**Issue by rominf** [SeleniumHQ/selenium#6760]
## 🚀 Feature Proposal
I propose to add a field `xpath` to elements:
```python
element.xpath
```

## Motivation
I automatically generate xpaths for future extraction of elements by xpath.

## Example
In Python:
```python
element = browser.find_element_by_name('p')
print(f"xpath: {element.xpath}"
```

**Comment by briz88** [comment]
to what end? you already have the element identified, why would you need an xpath?

**Comment by rominf** [comment]
I have a site with constant structure but with content that charges overtime. I know the text of the element at present moment and want to extract xpath of it, to select this element even after text changes.
I have about 100 sites, so I want to do this automatically.

**Comment by lmtierney** [comment]
This would be a feature request for the W3C WebDriver specification. Please raise the issue here https://github.com/w3c/webdriver/issues

**Comment by rominf** [comment]
@lmtierney, I found that this issue: https://github.com/w3c/webdriver/issues/816. But it was closed. That means that this won't be implemented?

**Comment by lmtierney** [comment]
@rominf Appears so.
