### ISSUE TITLE
How to Selenium 3.14 remove base64 string. Terminal is completly flooded

### ISSUE THREAD

**Issue by VereschakSun** [SeleniumHQ/selenium#6762]
## 🐛 Bug Report

Hello!
I used selenium 3.11 and when I run code with custom firefox profile - browser startup 3-5sec and console of selenium was clean from flood text.

But when I using 3.14 Selenium is output to console all base64 code of my custom profile and I am waiting 1-2 minutes before firefox is running. How can I disable this console output hell ? Thanks!

**Comment by diemol** [comment]
Hi @VereschakSun 
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
