### ISSUE TITLE
DevToolsActivePort file doesn't exist (Driver info: chromedriver=2.45.615291,platform=Windows NT 6.1.7601 SP1 x86_64)

### ISSUE THREAD

**Issue by 599139** [SeleniumHQ/selenium#6764]
**Issue Description
============**
Chromedriver fails to spin up Chrome browser when tests are run (sequentially). Out of 100 tests typically such failures would impact 10-20 tests.
I've tried various chromedriver and chrome versions but none of them seems to make the issue any better.  Since this is an intermittent issue I'm unable to provide a 100% reproducible case, but hope the exception stack trace and other details below helps.

**Bindings and Versions
===============**
Chrome Version -  71.0.3578.80
"Selenium.Support" version="3.10.0" targetFramework="net461" 
 "Selenium.WebDriver" version="3.10.0" targetFramework="net461"
 "Selenium.WebDriver.ChromeDriver" version="2.45.0" targetFramework="net461" 

**Exception Details 
============**
**Exception Message** : unknown error: DevToolsActivePort file doesn't exist (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)

**Exception StackTrace** : at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities) at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities) at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout) at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout) at Common.BaseHooks.GetSeleniumDriver(TimeSpan commandTimeout) 

Exception Source : WebDriver

**Code which instantiates Chromedriver Instance :** 
==================================

       ChromeOptions chromeOptions = new ChromeOptions();
	chromeOptions.Proxy = proxy;
	chromeOptions.BinaryLocation = PathHelper.GetBrowserAbsolutePath(browser);
	chromeOptions.AddArgument("--start-maximized"); 
	chromeOptions.AddArgument("--disable-infobars"); 
	chromeOptions.AddArgument("--disable-extensions"); 
	chromeOptions.AddArgument("--disable-gpu"); 					
	chromeOptions.AddArgument("--disable-dev-shm-usage"); 
	chromeOptions.AddArgument("--no-sandbox");
	chromeOptions.AddUserProfilePreference("download.default_directory", downloadDirectory);
	chromeOptions.AddUserProfilePreference("download.prompt_for_download", false);
	chromeOptions.AddUserProfilePreference("disable-popup-blocking", "true");				
					
	driver = new ChromeDriver(AssemblyDirectory, chromeOptions, commandTimeout)

**The next line from where the exception is being thrown is :	driver.Manage().Window.Maximize();**

					
Attached is the test log from the execution, PFA.

![image](https://user-images.githubusercontent.com/33328317/50104552-53259580-01f8-11e9-9cce-2e8dfc821688.png)

**Comment by 599139** [comment]
Hi, 
      I've upgraded to latest Selenium.Webdriver Nuget pkg - 3.141.0 . No luck, same problem persisting with exact same exception stack trace

**Comment by p0deje** [comment]
Typically such an error would happen when Selenium tries to use OSS protocol to communicate with ChromeDriver which expects W3C protocol and vice versa. This is why it's crucial to have the matching versions of Selenium + Chrome + ChromeDriver.

I'm not C# maintainer, so I cannot really dig into this issue, but I can the following will help with further debugging:

1. Verify that all the versions of Selenium + Chrome + ChromeDriver are up to date. It's possible that your code can use different ChromeDriver than what you'd normally see in console (at least this happens often with Ruby bindings).
2. Reduce the test case to no `ChromeOptions` (e.g. remove all custom arguments and profile preferences).
3. Attach ChromeDriver logs to this issue.

**Comment by 599139** [comment]
@p0deje -  
I ensured all of the above points are taken care and got the issue reproduced, PFA the chromedriver log. ( I had to truncate a part of the binary location since this log is a live project log)
[chromedriver.log](https://github.com/SeleniumHQ/selenium/files/2696567/chromedriver.log)

Please let me know if you need more details.

**Here's the driver instantiation code (modified to align per your request above)**
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.Proxy = proxy;
chromeOptions.BinaryLocation = PathHelper.GetBrowserAbsolutePath(browser);
ChromeDriverService _service = ChromeDriverService.CreateDefaultService(AssemblyDirectory);
_service.LogPath = downloadDirectory + "\\chromedriver.log";
_service.EnableVerboseLogging = true;
driver = new ChromeDriver(_service, chromeOptions, commandTimeout);

**Comment by 599139** [comment]
@p0deje  - since you mentioned that you're not a .C# maintainer, I'm wondering if it would be possible for you to add someone from the .Net group?
I'm running >400 tests and ~50 of them complains on this issue, thus the urgency to get it fixed.

adding  @barancev  since I had past experience with you dealing on C# selenium issues.  Thanks

**Comment by p0deje** [comment]
By looking at your logs, is it possible that you use an old Chrome version (I see `64` in path)?

```
"binary": "C:\\Programs\\Server\\...\\Executables\\Chrome64_71\\Application\\chrome.exe"
```

**Comment by barancev** [comment]
This definetely is a chromedriver issue, please report it to https://bugs.chromium.org/p/chromedriver/issues/list

(Actually, it was reported already many times, but there is no solution yet...)

**Comment by barancev** [comment]
Instead of reporting a new issue you can follow this one: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2647

**Comment by 599139** [comment]
@p0deje  - Its Chrome v 71. The 64 you see is because its a 64 bit version of the driver
@barancev  - thanks will follow it up on the chromedriver bug
