### ISSUE TITLE
Drag and drop is not working if the page got scroll

### ISSUE THREAD

**Issue by KDsankar** [SeleniumHQ/selenium#6766]
## 🐛 Bug Report

I need to drag a element from a position to another position but the droppable element is in bottom of the page so that i need to drag the element and scroll the page to the bottom and drop. 

## Note:
The page got selected from the dragable element position to droppable element position

But it's not working in selenium.

## Environment

OS: Windows, OSX
Browser: Chrome
Browser version: 67
Browser Driver version: e.g.: ChromeDriver 2.34
Language Bindings version: Java 8
Selenium Grid version (if applicable): 3.8.1

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
