### ISSUE TITLE
Unable to drag and drop in the same canvas using chromedriver

### ISSUE THREAD

**Issue by zhuxysun** [SeleniumHQ/selenium#6768]
I am using chromedriver to do the drag and drop in the same one canvas, but it doesn't work, so I come to look for help.

## Environment

OS:  windows 10
Browser:  chrome
Browser version:  70
Browser Driver version: 70
Language Bindings version:  Java 8

## Script
int x = 300;
int y = 300;
int xOffset = 400;
int yOffset = 400;
Actions actions = new Actions(driver);
actions.moveByOffset(x, y).perform();
actions.clickAndHold().moveByOffset(xOffset, yOffset).release().build().perform();

The result of the script is just clicking the location of (x, y), no drag and drop behavior.
I try to change the last line to "actions.moveByOffset(xOffset, yOffset).contextClick().build().perform();", it works. The location are not outside the canvas.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction case provided.
