### ISSUE TITLE
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output: refox/browser/features/e10srollout@mozilla.org.xpi

### ISSUE THREAD

**Issue by rohithkr18** [SeleniumHQ/selenium#6769]
## 💬 Empty firefox browser is launching but url is not getting entered

Here is the code
public class Demo1 {

	public static void main(String[] args)
	{
		System.setProperty("webdriver.gecko.driver", "/home/blubirch/workspace/Alpha/software/geckodriver");
		WebDriver driver=new FirefoxDriver();
		driver.get("https://www.flipkart.com");

	}
}

os ubuntu 16.04
firefox version 51.0.1
selenium 3.141.59, 3.14.0, 2.53.1

please help with the issue

**Comment by rohithkr18** [comment]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
refox/browser/features/e10srollout@mozilla.org.xpi
1545200769502	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.7
1545200769503	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1545200769504	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1545200769505	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1545200769507	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1545200769511	addons.manager	DEBUG	Provider finished startup: XPIProvider
1545200769511	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1545200769512	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1545200769513	addons.manager	DEBUG	Starting provider: GMPProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: GMPProvider
1545200769522	addons.manager	DEBUG	Starting provider: PluginProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: PluginProvider
1545200769523	addons.manager	DEBUG	Completed startup sequence
1545200769930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1545200769930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1545200769931	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1545200770037	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770038	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1545200770038	DeferredSave.extensions.json	DEBUG	Starting timer
1545200770051	addons.repository	DEBUG	No addons.json found.
1545200770051	DeferredSave.addons.json	DEBUG	Save changes
1545200770054	DeferredSave.addons.json	DEBUG	Starting timer
1545200770075	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1545200770081	DeferredSave.extensions.json	DEBUG	Starting write
1545200770103	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770106	DeferredSave.addons.json	DEBUG	Starting write
1545200770121	DeferredSave.addons.json	DEBUG	Write succeeded
1545200796100	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1545200796101	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1545200796102	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.7
1545200796104	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 1.0
1545200796292	addons.manager	DEBUG	shutdown
1545200796293	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1545200796293	addons.xpi	DEBUG	shutdown
1545200796293	addons.xpi-utils	DEBUG	shutdown
1545200796294	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1545200796295	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1545200796302	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1545200796307	addons.xpi	DEBUG	Notifying XPI shutdown observers
1545200796313	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at apple.Demo1.main(Demo1.java:11)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
refox/browser/features/e10srollout@mozilla.org.xpi
1545200769502	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.7
1545200769503	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1545200769504	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1545200769505	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1545200769507	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1545200769511	addons.manager	DEBUG	Provider finished startup: XPIProvider
1545200769511	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1545200769512	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1545200769513	addons.manager	DEBUG	Starting provider: GMPProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: GMPProvider
1545200769522	addons.manager	DEBUG	Starting provider: PluginProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: PluginProvider
1545200769523	addons.manager	DEBUG	Completed startup sequence
1545200769930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1545200769930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1545200769931	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1545200770037	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770038	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1545200770038	DeferredSave.extensions.json	DEBUG	Starting timer
1545200770051	addons.repository	DEBUG	No addons.json found.
1545200770051	DeferredSave.addons.json	DEBUG	Save changes
1545200770054	DeferredSave.addons.json	DEBUG	Starting timer
1545200770075	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1545200770081	DeferredSave.extensions.json	DEBUG	Starting write
1545200770103	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770106	DeferredSave.addons.json	DEBUG	Starting write
1545200770121	DeferredSave.addons.json	DEBUG	Write succeeded
1545200796100	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1545200796101	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1545200796102	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.7
1545200796104	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 1.0
1545200796292	addons.manager	DEBUG	shutdown
1545200796293	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1545200796293	addons.xpi	DEBUG	shutdown
1545200796293	addons.xpi-utils	DEBUG	shutdown
1545200796294	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1545200796295	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1545200796302	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1545200796307	addons.xpi	DEBUG	Notifying XPI shutdown observers
1545200796313	addons.manager	DEBUG	Async provider shutdown done

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:32:46'
System info: host: 'blubirch-pc', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_191'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at apple.Demo1.main(Demo1.java:11)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
refox/browser/features/e10srollout@mozilla.org.xpi
1545200769502	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.7
1545200769503	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/firefox@getpocket.com.xpi
1545200769504	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1545200769505	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi
1545200769507	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Registering manifest for /usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi
1545200769508	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1545200769511	addons.manager	DEBUG	Provider finished startup: XPIProvider
1545200769511	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1545200769511	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1545200769512	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1545200769513	addons.manager	DEBUG	Starting provider: GMPProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: GMPProvider
1545200769522	addons.manager	DEBUG	Starting provider: PluginProvider
1545200769522	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1545200769522	addons.manager	DEBUG	Provider finished startup: PluginProvider
1545200769523	addons.manager	DEBUG	Completed startup sequence
1545200769930	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1545200769930	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1545200769931	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1545200770037	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770038	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1545200770038	DeferredSave.extensions.json	DEBUG	Starting timer
1545200770051	addons.repository	DEBUG	No addons.json found.
1545200770051	DeferredSave.addons.json	DEBUG	Save changes
1545200770054	DeferredSave.addons.json	DEBUG	Starting timer
1545200770075	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1545200770075	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1545200770081	DeferredSave.extensions.json	DEBUG	Starting write
1545200770103	DeferredSave.extensions.json	DEBUG	Write succeeded
1545200770106	DeferredSave.addons.json	DEBUG	Starting write
1545200770121	DeferredSave.addons.json	DEBUG	Write succeeded
1545200796100	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1545200796101	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1545200796102	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.7
1545200796104	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 1.0
1545200796292	addons.manager	DEBUG	shutdown
1545200796293	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1545200796293	addons.xpi	DEBUG	shutdown
1545200796293	addons.xpi-utils	DEBUG	shutdown
1545200796294	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1545200796295	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1545200796298	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1545200796302	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1545200796307	addons.xpi	DEBUG	Notifying XPI shutdown observers
1545200796313	addons.manager	DEBUG	Async provider shutdown done

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by diemol** [comment]
@rohithkr18 

Please create a new issue and fill out the template, we don't have enough information to see if this is a bug/issue or not.

Alternatively, also consider sending a question to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by barancev** [comment]
And the problem is that you're trying to use two (or three) years old Selenium version 2.53.1 with a modern browser version. Please upgrade Selenium.
