### ISSUE TITLE
Reached error page: about:neterror

### ISSUE THREAD

**Issue by PickHub** [SeleniumHQ/selenium#6770]
## 🐛 Bug Report

The [Selenium example](https://github.com/lightbody/browsermob-proxy#using-with-selenium) form the readME throws the following error: 'Reached error page: about:neterror'. 

    // start the proxy
    BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0);

    // get the Selenium proxy object
    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);

    // configure it as a desired capability
    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

    // start the browser up
    WebDriver driver = new FirefoxDriver(capabilities);

    // enable more detailed HAR capture, if desired (see CaptureType for the complete list)
    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);

    // create a new HAR with the label "yahoo.com"
    proxy.newHar("yahoo.com");

    // open yahoo.com
    driver.get("http://yahoo.com");

    // get the HAR data
    Har har = proxy.getHar();

## Environment

OS: OSX
Browser: Firefox
Browser version: 64.0
Browser Driver version: Geckodriver 0.23.0

**Comment by diemol** [comment]
Hi @PickHub,

Please report BrowserMobProxy issues to that [project](https://github.com/lightbody/browsermob-proxy).
