### ISSUE TITLE
Safari 12.0.2 not compatible

### ISSUE THREAD

**Issue by everly-blake** [SeleniumHQ/selenium#6772]
After updating to Safari 12.0.2 from version 12.0.1, I can no longer connect with a webdriver session.

STR:
Be running Safari 12.0.2
selenium-webdriver version 3.141
watir gem version 6.16.0

Watir::Browser.new :safari

Unable to connect to driver.

**Comment by lmtierney** [comment]
Can you please provide a full stack with debug on?

**Comment by lmtierney** [comment]
I've tried this with Sarari `12.0.2` and pure selenium `3.141` and also with watir `6.16.0`. I cannot reproduce this. I will re-open if you can give steps to reproduce. I'd suggest restarting your machine in case any lingering safaridrivers are running.
