### ISSUE TITLE
When [If]'s [End] is just before [While]'s [End], the [While] loop is never repeated.

### ISSUE THREAD

**Issue by YecineM** [SeleniumHQ/selenium#6778]
## 🐛 Bug Report

A clear and concise description of what the bug is :

The bug concerns an [**If**] command inside a [**While**] command.
Specifically, it happens when [**If**]'s [**End**] is just before [**While**]'s [**End**], that is, when the two **End** commands are not separated by any other command.

I haven't tested the opposite (While inside If) , but you may want to check it too.

## To Reproduce

**Detailed steps to reproduce the behavior:**

![image](https://user-images.githubusercontent.com/45966855/50325565-ed7e2580-04e5-11e9-97b7-8d9c3be55749.png)

## Expected behavior

A clear and concise description of what you expected to happen :
The [**While**] loop is never repeated.
If you separate the two **End**s by any command (I tried **echo | hello**) , everything becomes fine and the bug doesn't occur.
## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  Windows 7 64 bits
Browser:  Chrome
Browser version:  71
Browser Driver version:  2.45
Language Bindings version:  I don't know, please tell me how to check this version.
Selenium Grid version (if applicable):

**Comment by lmtierney** [comment]
Issue moved to [SeleniumHQ/selenium-ide #524](https://github.com/SeleniumHQ/selenium-ide/issues/524) via [**ZenHub**](https://www.zenhub.com/)
