### ISSUE TITLE
Could not do Arrow down using sendKeys(Keys.ARROW_DOWN) in chrome

### ISSUE THREAD

**Issue by sureshshaw** [SeleniumHQ/selenium#6779]
OS: windows 10 x64
Selenium Version: 3.141.59
Browser: Google Chrome( 71.0.3578.98 (Official Build) (64-bit))/Firefox(60.4.0esr (32-bit))
Chrome Driver Version : ChromeDriver 2.45

Expected Behavior -
**act.contextClick(tutorial).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ENTER).build().perform();** 
should press arrow down on context menu and then press ENTER.

Actual Behavior -
it doesn't work, it is not pressing arrow down.

Steps to reproduce -
System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
ChromeDriver driver = new ChromeDriver();// browser open
driver.get("http://toolsqa.com/automation-practice-form");
WebElement tutorial = driver.findElement(By.xpath("//div/ul[@id='primary-menu']/li/a/span/span[contains(.,'Tutorial')]"));
Actions act = new Actions(driver);
act.moveToElement(tutorial).build().perform();
act.contextClick(tutorial).sendKeys(Keys.ARROW_DOWN).sendKeys(Keys.ENTER).build().perform();

**Comment by o-x-y-g-e-n** [comment]
I think you are targeting the wrong 'Tutorial' element. The element you targeted is behind the webpage you intend to work with.

@sureshshaw

**Comment by barancev** [comment]
contextClick on a link opens a native context menu that can't be managed by Selenium (by design).
