### ISSUE TITLE
 TestNG eclipse issue after clicking on Runas --> TestNG Test

### ISSUE THREAD

**Issue by raghav2329** [SeleniumHQ/selenium#678]
![testng issue](https://cloud.githubusercontent.com/assets/12811132/8224278/2310ab46-15a2-11e5-9d4d-cac41ea5f240.jpg)

**Comment by lukeis** [comment]
Please email the user group for support questions:
https://groups.google.com/forum/#!forum/selenium-users

Also, TestNG is a different project entirely.

**Comment by raghav2329** [comment]
Thanks. I got stuck with same issue for long time and its very urgent.KIndly let me know who can  help me to resolve this issue.
