### ISSUE TITLE
Getting "Unable to add cookie to page" exception when trying to add cookies

### ISSUE THREAD

**Issue by okyrylenko** [SeleniumHQ/selenium#6780]
I am getting "Unable to add cookie to page" exception when trying to add cookies to IE driver. 
Bindings -DotNet
IEDriver - WebDriverIEDriver64.2.45.0.0
IE version - IE
OS - Windows10
All protection modes are checked in IE options as well as enabling to accept cookies
Please let me know if you need more info

**Code:**
                    var IEoptions = new InternetExplorerOptions
                    {
                        IntroduceInstabilityByIgnoringProtectedModeSettings = true
                    };
                    driver = new InternetExplorerDriver(_IEDriverPath, IEoptions);

==============================================================
                var cookie = new Cookie(cookieName, cookieValue);

                _driver.Manage().Cookies.AddCookie(cookie);

===============================================================
 **stacktrace:**
Unable to add cookie to pageSystem.InvalidOperationException: Unable to add cookie to page
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteCookieJar.AddCookie(Cookie cookie)

**Comment by diemol** [comment]
This is similar to #6775, where the reply [comment](https://github.com/SeleniumHQ/selenium/issues/6775#issuecomment-449001884) also applies.
