### ISSUE TITLE
OkHttpClient.Factory() lacks constructor with socketTimeout and readTimeout

### ISSUE THREAD

**Issue by KroArtem** [SeleniumHQ/selenium#6786]
## 💥 Regression Report

OkHttpClient.Factory() lacks constructor with socketTimeout and readTimeout
This constructor was removed here: https://github.com/SeleniumHQ/selenium/commit/04f6621

The reason to reduce timeouts is the following: we have selenium hub and nodes running in the cloud. Google has preemption. This means machines can be taken down for some time and we don't know whether it'll happen or not.
In case connection was established and then node was lost, we’ll wait 3 hours for the timeout to happen. 3 hours is the default read timeout for HttpCommandExecutor

This issue was discussed here (and later the same day):
https://seleniumhq.slack.com/archives/C0ABCS03F/p1545424892040600

## Last working Selenium version

Worked up to version: This functionality was available in 3.14 but was removed later. 

Stopped working in version: 3.141.x

## To Reproduce

Try to set up `OkHttpClient.Factory` with socketTimeout and readTimeout. Right now it's impossible.
```
OkHttpClient.Factory clientFactory = new OkHttpClient.Factory(Duration.ofMillis(connectionTimeout), Duration.ofMillis(socketTimeout));
HttpCommandExecutor executor = new HttpCommandExecutor(new HashMap<>(), hubUrl, clientFactory);
webDriver = new RemoteWebDriver(executor, option);
```

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS:  any
Browser: any
Browser version: any
Browser Driver version: any
Language Bindings version:  3.141.59
Selenium Grid version (if applicable):  3.141.59

**Comment by KroArtem** [comment]
@diemol ^^ as we've discussed in the Slack/IRC, I've created an issue.

**Comment by shs96c** [comment]
Don't create the factory directly: go through the builder:

```java
HttpClient client = HttpClient.Factory.createDefault().builder()
      .connectionTimeout(Duration.ofSeconds(30))
      .readTimeout(Duration.ofSeconds(3))
      .createClient(new URL("http://example.com"));
```

This provides equivalent functionality, and means that we can switch to another httpclient with minimal disruption (I'm very making the okhttp dependency optional, and using the Java 11 JRE HttpClient where possible).

**Comment by shs96c** [comment]
We obviously have some missing code to handle the case you've suggested. I end up with:

```java
  public static void main(String[] args) throws Exception {
    Factory factory = Factory.createDefault();
    Builder builder = factory.builder()
        .readTimeout(Duration.ofSeconds(30))
        .connectionTimeout(Duration.ofSeconds(3));

    new HttpCommandExecutor(ImmutableMap.of(), new URL("http://localhost:4444"), new Factory() {
      @Override
      public Builder builder() {
        return new Builder() {
          @Override
          public HttpClient createClient(URL url) {
            return builder.createClient(url);
          }
        };
      }

      @Override
      public void cleanupIdleClients() {
        factory.cleanupIdleClients();
      }
    });
  }
```

which works, but isn't particularly elegant. Will fix.

**Comment by henrykuijpers** [comment]
Hitting this issue as well...

I'm trying to instantiate a RemoteWebDriver. In order to specify the socket timeout and the connection timeout, I have to specify the CommandExecutor to provide these details.

This command executor is apparently not so easy to obtain. I would expect something like this:
```
final factory = new HttpClientFactory()
    .builder()
    .readTimeout(Duration.ofMinutes(10))
    .connectionTimeout(Duration.ofMinutes(10))
    .build();
```

Instead, I need to go through the mess of code that @shs96c was pointing out...

Please fix this. :)

**Comment by rdonuk** [comment]
Hello, any plan for fixing this?

**Comment by shs96c** [comment]
Yes there is. I'm landing some changes to our HTTP abstractions to make this easier.

**Comment by gcooney** [comment]
@shs96c Are those changes close to landing?  I'd be happy to contribute a patch here if there's not something in flight already.

**Comment by henrykuijpers** [comment]
Any update?

**Comment by rdonuk** [comment]
I am using it like below

```
	private static Factory HTTP_CLIENT_FACTORY = new Factory() {
		@Override
		public HttpClient.Builder builder() {
			return super.builder()
					.connectionTimeout(Duration.ofSeconds(SELENIUM_HTTP_EXECUTOR_CONNECTION_TIMEOUT))
					.readTimeout(Duration.ofSeconds(SELENIUM_HTTP_EXECUTOR_SOCKET_TIMEOUT));
		}
	};

		HttpCommandExecutor executor =
				new HttpCommandExecutor (Collections.<String, CommandInfo>emptyMap (), url, HTTP_CLIENT_FACTORY);
```

**Comment by rdonuk** [comment]
I am using it like below. What is the problem with that.

```
private static Factory HTTP_CLIENT_FACTORY = new Factory() {
    @Override
    public HttpClient.Builder builder() {
        return super.builder()
                .connectionTimeout(Duration.ofSeconds(SELENIUM_HTTP_EXECUTOR_CONNECTION_TIMEOUT))
                .readTimeout(Duration.ofSeconds(SELENIUM_HTTP_EXECUTOR_SOCKET_TIMEOUT));
    }
};

HttpCommandExecutor executor = new HttpCommandExecutor (Collections.<String, CommandInfo>emptyMap (), url, HTTP_CLIENT_FACTORY);
```

**Comment by rdonuk** [comment]
Any update?

**Comment by diemol** [comment]
OkHttpClient is not used in the project anymore. However, we have improved this and it is possible to provide those values now, more information can be seen [here](https://github.com/SeleniumHQ/selenium/issues/8931#issuecomment-752466772).
