### ISSUE TITLE
sendKeys(Keys.chord(Keys.COMMAND,"t")) does not works in MAC OS

### ISSUE THREAD

**Issue by AutomationObject** [SeleniumHQ/selenium#6790]
Meta
OS: OSX
Selenium Version: 3.6.0, IntelliJ 2018.2.5
Browser: Chrome
Browser Version: Version 71.0.3578.98 (64bit)
Chromedriver Version: latest 

Expected Behavior
Key.chord should mark, copy and paste Text in an input-field with Keys.chord(Keys.COMMAND, "a") etc.
I tried it with webelement.sendKeys(Keys.chord(Keys.COMMAND, "t")), and with
Actions actions = new Actions(driver);
actions.sendKeys(selectedElement, Keys.chord(Keys.COMMAND, "t"));

Actual Behavior
it does nothing, no error in log

Steps to reproduce
System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver_2_33");
Webdriver driver = new ChromeDriver();
driver.get("https://www.google.de");
WebElement searchbar = driver.findElement(By.className("gsfi"));
searchbar.click();
searchbar.sendKeys("abcdef");
searchbar.sendKeys(Keys.chord(Keys.COMMAND, "t"));

**Comment by ice1080** [comment]
I'm seeing the same thing both on Windows with Control and on Mac with Command. In our case we are trying to paste something from the clipboard, and these keys seem to be ignored, so only the character "v" is sent to the element. I have also tried using keyDown and stringing together multiple sendKeys instead of just chord and nothing seems to work

**Comment by kenticomartinh** [comment]
Same problem here, command key doesn't seem to work against Safari on Mac. Anyone able to workaround that?

**Comment by hanshul-dua** [comment]
> ```
> element.sendKeys(Keys.chord(Keys.COMMAND, "a"));
> ```

sfgyugdshygtf5iu




\

**Comment by diemol** [comment]
Did I understand correctly that this works in Firefox but fails in Chrome? Even in the most recent versions of all components involved?

**Comment by alb-i986** [comment]
Currently it's working also on Chrome to me.

ChromeDriver 89.0.4389.23
MacOS 10.15.7

**Comment by diemol** [comment]
Thank you for the feedback, closing this for now. If someone is still bumping into the issue with the most recent versions of Selenium and browser, please feel free to comment or open a new issue.
