### ISSUE TITLE
(Advanced) Webdriver: ExpectedConditions.invisibilityOf is not working as expected. Always throws an exception

### ISSUE THREAD

**Issue by Djuise** [SeleniumHQ/selenium#6792]
I found the issue [5070](https://github.com/SeleniumHQ/selenium/issues/5070) but it was closed. Can you read the problem from this issue and give me the answer to my comment? 

> If I understood correctly then point of the problem it 
> ```
> @FindBy(id = "some id")
> public static WebElement element;
> ```
> "element" - it's not WebElement it just proxy to the element with id ("some id"). So it can't be used for > waiting.
> 
> Change:
> > ExpectedConditions.invisibilityOf(element)
> to 
> > ExpectedConditions.invisibilityOf($(By.id("some id"))) 
> or 
> > ExpectedConditions.invisibilityOf(driver.findElement(By.id("some id")))
> 
> it should help you.
> 
> If someone from SeleniumHD can explain to me why WebDriverWait working incorrectly with a proxy > (it the same library package and should not be any problem)

Thank you for advance

**Comment by cgoldberg** [comment]
please fill out the issue template.  it's not clear what you are asking.

**Comment by diemol** [comment]
Closing as we didn't get any answer from the OP.
