### ISSUE TITLE
Node connectivity issue . (cannot reach the node for 2 tries)

### ISSUE THREAD

**Issue by rajkumar-cp** [SeleniumHQ/selenium#6795]
[Mobile.txt](https://github.com/SeleniumHQ/selenium/files/2717193/Mobile.txt)
[Mobile2.txt](https://github.com/SeleniumHQ/selenium/files/2717194/Mobile2.txt)

## 🐛 Bug Report

Selenium Grid not working as expected. It is not connecting to nodes properly.

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

I am trying to use Selenium Grid with appium. When i launch the hub and nodes the hub is throwing below error

19:06:20.586 INFO - Marking the node http://192.168.43.146:4726 as down: cannot reach the node for 2 tries
19:07:01.436 INFO - Unregistering the node http://192.168.43.146:4724 because it's been down for 60070 milliseconds
19:07:01.437 WARN - Cleaning up stale test sessions on the unregistered node http://192.168.43.146:4724
19:07:04.105 INFO - Registered a node http://192.168.43.146:4724
[Hub Log.txt](https://github.com/SeleniumHQ/selenium/files/2717187/Hub.Log.txt)
[Node1 Log.txt](https://github.com/SeleniumHQ/selenium/files/2717188/Node1.Log.txt)
[Node2 Log.txt](https://github.com/SeleniumHQ/selenium/files/2717189/Node2.Log.txt)

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Selenium Grid version (if applicable): 2.53.0

**Comment by diemol** [comment]
@rajkumar-cp  could you please upgrade to 3.141.59 and try again? If it is still failing, 
Please provide a [concise reproducible test case](http://sscce.org/), including all configuration files.

**Comment by rajkumar-cp** [comment]
@diemol 
The issue is not reproducible in the latest version.

You are good to close this bug.

Thanks again. Cheers :)

**Comment by diemol** [comment]
Thanks for replying @rajkumar-cp, closing.
