### ISSUE TITLE
BinaryLocation property not used to find binary on chrome options

### ISSUE THREAD

**Issue by Jordank321** [SeleniumHQ/selenium#6799]
## 🐛 Bug Report

When the binary location is set to either the directory of the chromedriver.exe or the path to the chromedriver.exe the exception for driver not found is raised.

## Reproduce

Have the chromedrive.exe in a path where it is not found by the deafaut settings
Construct the ChromeDriver with ChromeOptions where the property BinaryLocation is set to the path or directory of the exe
The error is thrown

Detailed steps to reproduce the behavior:

## Expected behavior

The property BinaryLocation is used to find the exe

## Environment

OS: Windows 10
Browser: Chrome
Language Bindings version: Dotnet

**Comment by jimevans** [comment]
The `BinaryLocation` property of `ChromeOptions` is used to specify the location of the Chrome browser itself. It is not now, nor was it ever, intended to indicate the location of `chromedriver.exe`. To specify where the driver executable is located, use the `ChromeDriverService` object and pass that to a constructor to `ChromeDriver`. The code would look something like this:

    var service = ChromeDriverService.CreateDefaultService(@"C:\path\to\executable");

    // Set any options required with the below
    // object.
    var options = new ChromeOptions();
    IWebDriver driver = new ChromeDriver(service, options);
