### ISSUE TITLE
[Help Required]  How to change the rules of Content Security Policy through JavascriptExecutor in Selenium - Java?

### ISSUE THREAD

**Issue by sonali215** [SeleniumHQ/selenium#6803]
Hi Everyone,

I have written a Java - Selenium Program to replace screenshots for App Store and Play Store. However, custom hosted URLs are not supported as input on the webpage because of the Content Security Policy on the web pages. I have used JavascriptExecutor in selenium to update the Image URLs in the webpages. 

Please View the screenshot references below : 

1.https://lh3.googleusercontent.com/EDDOO6HKwKHGISG6pCNSu65wDqckRPvzFQm6av2YF4SNSvcSk3mN6cJjBUPbIf_TiaFLQBTRVBF5r1doZabli0qC0v75dKeiyB8Py1neDCy8bOIC4N9XuSZCw9MyoOFy7BIniCrFJhy-kdU_lXZypYV9Opv4KX7_ndoI5RdSI_z73tZn0nFIhUTSiokUwvDC5DhozFcr2uq2f8iOMpvyu6S_nXVExUk_WxJb-Hg9Vp0_4VLxyzzOip2RN4OWCkW1GoIR5FTNjJ97NvcXnxtUgjxYygsTcrdtI94hhGy1d-yhBStede6Z4HuMO1AoFTf1LhZBAkQLZfx1-CQFiM0HMyrzVSR6biNUA_qMQ_2eEO2wbPAuCKsur-aw36ZZxT3_emuY8gs-ZTZI5phZYskMCJnnBCBYIrxwJFvBp86XfHqnpHDsJu9kw-7I1LLD_YJLh9otNElRrSILtQOIGQDVYMRf2-CxrNHI5vC_PwFDq2We1RrzVQIShJwp3S2cTcEgpCTLJZS6QSDKgaxgVqvqRBtvxgyg80I9jfnn1h3OapRaDzVHDXK6546nxr1_8ovIvBexPJj0DEvaSA7WM1iieCkCcAUMEIftr2DxMP6gswG98_Vfp4mgYb3EcETHSsyRi_3N4KsodWalCB0PYDjJAbsMR5BC7i5mlB4SiEFNahew-LzHdZFylm3rmZOB8t2v7zw97FhjjTYDXmkqIA=w2169-h1220-no

----
2.https://lh3.googleusercontent.com/oPnnk-NOsi2FplUuy5AOfCRKc_mP3GPvhoN4CYVjxD7vNpmHnBW2jgVL7ixZi-skdFJQE_C7erfhPL8JGgfhXAA0CPI5Di1UopDOm46BbgWg9ChqcfIrRxWGv3rK2XMb-Uixe56Z0MhizrvpuO5yQzLE_MaLC3ms-pK5h_9E7DVxrNOZpMtgU77gkZWplduDtWDgDBeCKgDdxM8p7FWzfUDr0jOumasAV0j2WklRs4twqym0knMgxfUgQN403dlbssirVk03OjbvlDFgH34xBZO8bWX3fjoxR2Zumczg5Bv4TTDapNmsvVqytyV9ZswyP_iYO0LYRKdW6wBiP2dtd8D7elBtVWpWCuE74dj9tENFsh7_Z7MOp-64mnNj_uQOzrMOKEMnnFbbyrREutQMyyeNzJ8s-FQL5EtTuAeEAeqEBRbhgT2iiYr7wzOi8KEHKUtAOnuMRMs9EpixadgXelIZiPeVZ2HvlrzmcO_5-D-0vNFbBOke0BJn_De1zv7wZFkTaVuuENgc9oqjvqJYK99g_KuHAnFZzYEkfCf0Bd_TCoWGKhMX08V_NiJbskN9XZl7HZbwaO8yRPeFqV3DyclR0MEHj3JNHeG4eAiwTeyQcAu5uGn-uh-VCKOTbT0wxI3aHhtMsiUv517OjCAVrhLg=w2169-h1220-no

I would like to change these audit rules. I would like to load images of any domain with http. I have researched upon this, looked through multiple solutions, but none of them work.

Please suggest me a workaround on this.

Thanks in advance.

**Comment by cgoldberg** [comment]
This is the tracker for Selenium issues.  Please post general questions to the [**selenium-users**](https://groups.google.com/forum/#!forum/selenium-users) mailing list.
