### ISSUE TITLE
Deploy location 'cause few issues

### ISSUE THREAD

**Issue by Shnitzelil** [SeleniumHQ/selenium#681]
Hey,

The deploy location in maven project file (pom.xml)

    <distributionManagement>
        <snapshotRepository>
            <id>sonatype-nexus-snapshots</id>
            <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>sonatype-nexus-staging</id>
            <url>http://oss.sonatype.org/service/local/staging/deploy/maven2</url> 
        </repository>
    </distributionManagement>

displaying the next error when building it on our CI machines

14:04:58 [WARNING] Checksum validation failed, could not read expected checksum: Error transferring file: Connection timed out for https://oss.sonatype.org/content/repositories/snapshots/org/seleniumhq/selenium/selenium-java/maven-metadata.xml
14:06:01 [WARNING] Could not transfer metadata org.seleniumhq.selenium:selenium-java/maven-metadata.xml from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): Error transferring file: Connection timed out

Is it possible to point it to the correct location??

**Comment by ddavison** [comment]
can you show us the `<dependency>` bit where you are depending on selenium?

**Comment by lukeis** [comment]
Sounds like you're trying to build/ deploy selenium itself.... You don't do that, we do that :)

Going to close until you describe completely what you are doing (and include your Pom file)
