### ISSUE TITLE
Is there an alternative to using window().setSize in Selenium?

### ISSUE THREAD

**Issue by AshpritK** [SeleniumHQ/selenium#6810]
With latest Chrome Browser update, our UI tests for mobile browsers are failing on Chrome browser for windows.

I have been using this:
driver.manage().window().setSize(dimension);

They are failing as UI elements do not match the expected on minimum chrome browser width.

But the site just loads fine on actual mobile devices on chrome browser.

Is there an alternative available in selenium which overrides the default minimum browser width set by chrome browser.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
