### ISSUE TITLE
WebDriverException error message 

### ISSUE THREAD

**Issue by JAffleck** [SeleniumHQ/selenium#6811]
## 🐛 Bug Report

**A** exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:52098/session/d599f3eaccd3414b8e9922007c8b3ee0/element/0.9150696802032856-146/enabled. The status of the exception was UnknownError, and the message was: Only one usage of each socket address (protocol/network address/port) is normally permitted Only one usage of each socket address (protocol/network address/port) is normally permitted

Should instead say:
**An** exception with a null response ...

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
