### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by kaiyoma** [SeleniumHQ/selenium#6812]
## 🐛 Bug Report

If I run my entire battery of Selenium tests through mocha, I always see this warning message (from Node) at the same exact spot:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

If I log the stack trace for the warning, I see this:

```
MaxListenersExceededWarning
Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at process.addListener (events.js:259:10)
    at process.once (events.js:290:8)
    at exec (...\node_modules\selenium-webdriver\io\exec.js:124:11)
    at resolveCommandLineFlags.then.args (...\node_modules\selenium-webdriver\remote\index.js:219:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm invoking `driver.quit()` at the end of every test suite, so maybe the leak is somewhere inside Selenium?

## To Reproduce

Run multiple test suites and tests all at once through mocha. Running a single test doesn't trigger the issue.

## Expected behavior

No warnings.

## Test script or set of commands reproducing this issue

I can't provide this as all of our tests are internal and proprietary.

## Environment

OS: Multiple (Windows 10 and Linux)
Browser: Chrome
Browser version: 71.0.3578.98
Browser Driver version: ChromeDriver 2.43.600210
Language Bindings version: JavaScript 3.6.0

**Comment by cgoldberg** [comment]
> I can't provide this as all of our tests are internal and proprietary

then please create a simplified example to reproduce the issue

**Comment by kaiyoma** [comment]
Okay, I was able to cobble together a simplified example.

Environment: Node 10.13.0, yarn 1.12.3, Chrome 71.0.3578.98

To repro:
1. Download and extract this zip: [test.zip](https://github.com/SeleniumHQ/selenium/files/2728390/test.zip)
2. `cd test`
3. `mkdir webdriver`
4. Copy the Chromedriver binary for your platform to the `webdriver` directory
5. `yarn install`
6. `yarn run test`

Towards the end of the mocha run, right as Suite 9 is starting, you'll see the warning from Node.

```
    ...
    Sub-suite 1
      √ Test 1 (46ms)
      √ Test 2

  Suite 9
(node:5956) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

Let me know if you have any issues running the example.

**Comment by martin770** [comment]
A safe way to add a listener without exceeding the maxListeners is to remove a listener before adding it. If the listener doesn't exist, nothing happens when it tries to remove it. If the listener does exist, then you remove it and re-add it, so there's still only one listener.

The issue was reported in v3.6.0, so maybe the code has changed since then. In the latest repository I see:
```
  // io/exec.js:139
  process.once('exit', onProcessExit);
```

This could easily be changed to
```
process.removeListener('exit', onProcessExit);
process.once('exit', onProcessExit);
```

**Comment by manuman94** [comment]
I'm running through this issue in my Protractor project. When I make multiple browser.restart() calls I'm getting this warning at the console. The trace is showing that io/exec.js: 124 is the responsible.

`process.once('exit', onProcessExit);`

**Comment by mr-blanket** [comment]
I've made quite a journey to reach this issue :)

I've made a workaround that I call after `browser.restart()` - it removes duplicated listeners:
```
	public static listenersCleanup() {
		console.debug(`Running ${this.listenersCleanup.name} ...`);
		let exitListeners = process.listeners("exit");
		let exitListenersFn = exitListeners.map((f) => f.toString());

		exitListeners.forEach((listener: any, index: number) => {
			if (exitListenersFn.indexOf(listener.toString()) !== index) {
				process.removeListener('exit', listener);
			}
		});
		console.debug(`\tDone!`);
	}
```
