### ISSUE TITLE
[py] 'GET' can't have body

### ISSUE THREAD

**Issue by ki4070ma** [SeleniumHQ/selenium#6819]
## 🐛 Bug Report

'GET' can't have body.

https://github.com/SeleniumHQ/selenium/blob/a920faac5532175843c6a135f1f2dd621d8016c3/py/selenium/webdriver/remote/remote_connection.py#L393

Needed in https://github.com/appium/python-client/issues/311

### Background
* https://github.com/SeleniumHQ/selenium/issues/6250
* https://github.com/SeleniumHQ/selenium/commit/c88ac018489ebfe7366c7da8fc2fded963b2fe2d

## Expected behavior

'GET' can accept body.

**Comment by KazuCocoa** [comment]
📝 
We will change on the appium side. thanks
(feel free to close this)

**Comment by ki4070ma** [comment]
Done by https://github.com/appium/appium-base-driver/pull/294 on appium side.
Please freely open if necessary.
