### ISSUE TITLE
sizzle.h generated location

### ISSUE THREAD

**Issue by otkeri** [SeleniumHQ/selenium#6820]
### i'd like to know the exact location of sizzle.h file.

- in Rakefile
```
:
file "cpp/iedriver/sizzle.h" => [ "//third_party/js/sizzle:sizzle:header" ] do
  cp "build/third_party/js/sizzle/sizzle.h", "cpp/iedriver/sizzle.h"
end
:
```

- sizzel.h in iedriver cpp project
```
selenium/cpp/iedriver/Generated/sizzle.h
```
The generated file location is "selenium/cpp/iedriver/sizzle.h".
The cpp included file is "selenium/cpp/iedriver/Generated/sizzle.h".
The generated file is not compiled.  What is right?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
