### ISSUE TITLE
Element.getText() converting upperCase I to lower case i

### ISSUE THREAD

**Issue by abhinav1708** [SeleniumHQ/selenium#6825]
Driver: chromedriver

Issue Description:
I have a string in my web Page i.e displayed as Primary 1 Criteria (In Hex), if I get the text it is returning Primary 1 Criteria (in Hex). It is converting uppercase I to lowercase I. Capitalisation is implemented using CSS original Text is Primary 1 criteria (in hex):

$0.textContent
"Primary 1 criteria (in hex):"
$0.outerText
"Primary 1 Criteria (In Hex):"
$0.innerText
"Primary 1 Criteria (In Hex):"

Element HTML

<div class="div-table-cell ems-property-label text-capitalize">Primary 1 criteria (in hex):</div>

**Comment by diemol** [comment]
@abhinav1708 could you please create a new issue and fill out the complete template, 
also provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
