### ISSUE TITLE
Certain exceptions cause WebDriver to become unresponsive

### ISSUE THREAD

**Issue by Thenakedgun** [SeleniumHQ/selenium#6826]
## 🐛 Bug Report

Under certain circumstances when an Exception is thrown within Python in seemingly unrelated code, the Firefox/WebDriver instance becomes unresponsive & it is not possible to close open Firefox instances.

When called, `driver.quit()` returns `None`, but does not close the active Firefox instance. Additionally, `driver.close()` also doesn't close the browser instance & instead produces the following error:
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=61067): Max retries exceeded with url: /session/5385f593-7782-4073-996e-b226f0e9dc4e/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000114A0CE05F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

If in the "Test Script" below, I enter either a valid or invalid URI, then the browser closes as expected. In the event of an invalid URI, selenium throws a `selenium.common.exceptions.InvalidArgumentException`, but this is caught & terminates normally. Similarly, if I replace the `input` statement with, `raise KeyboardInterrupt()` or `raise EOFError()` then the browser is also closed as expected.

Using `pdb`, the expected path of execution seems to be followed. I posted this on SO yesterday to see if I was just expecting / doing something incorrectly, but the post didn't get any bites: https://stackoverflow.com/questions/54069341/exception-prevents-webdriver-from-responding-properly

## To Reproduce

Run the "Test Script" below; this example seems to be reflective of the issue I'm running into.

When prompted for input, rather the entering a string, press `Ctrl+C` to send the `SIGINT`. During the `input` statement on my machine, this raises an `EOFError()`.

## Expected behavior

Execution should be halted when the `EOFError` is raised & flow resumes at the `except` statement. It will then `pass`, and continues in the `finally` statement & the browser instance is closed by either `driver.close()` or `driver.quit()`.

## Test script or set of commands reproducing this issue

```
from selenium import webdriver
import pdb

try:
	#pdb.set_trace()
	driver = webdriver.Firefox(executable_path='./bin/geckodriver.exe')
	variable = input("Enter something or Ctrl+C: ")
	driver.get(variable)
except Exception as e:
	pass
finally:
	driver.close()
	driver.quit()
```

Within my real code environment, I've wrapped my script in a similar `try except finally` statement, and similarly, after certain exceptions are thrown in seemingly unrelated statements the `driver` object stops responding as expected. This seemed to be the minimum amount of code which produced the same error.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 64.0
Browser Driver version: GeckoDriver v0.23.0
Language Bindings version: Python 3.6.4
Selenium Version: 3.141.0

**Comment by diemol** [comment]
@Thenakedgun I am not working with the Python bindings, but after reading the issue, I can see that there is a big difference between the version of the language bindings and the Selenium version, these should be in synch. 
Perhaps try that first and report back your results.

**Comment by Thenakedgun** [comment]
@diemol K, just updated to `Python 3.7.2` which seems to be the most recent version for Windows. I reinstalled `selenium` via `pip`, double-checked the Python version it was going to run under, and re-ran the Test Script. 

Unfortunately I arrived at the exact same result-- the browser instance can't be terminated in the `finally` section. Tried swapping the order of `driver.close` and `driver.quit` & it made no difference. Again, `driver.close()` throws the error, where `driver.quit` seemingly does nothing. 

Here's the geckodriver.log file for the sake of it:
[geckodriver.log](https://github.com/SeleniumHQ/selenium/files/2745876/geckodriver.log)

**Comment by diemol** [comment]
@Thenakedgun I meant the Python language bindings, you mentioned:
>Language Bindings version: Python 3.6.4
and the latest one should be around 3.141.59

**Comment by Thenakedgun** [comment]
@diemol Sorry, could you point me to the resource? 

I installed selenium via pip and `3.141.0` seems to be the most up-to-date available there. I went into the github repo & it seems to list this version as the most recent changeset as well: `selenium/py/CHANGES ... Selenium 3.141.0`

Pseudo-relatedly, the SeleniumHQ.org website and the language bindings listed only showed Python up to a slightly older version.

Language | Client Version | Release Date |   |   |  
-- | -- | -- | -- | -- | --
Java | 3.141.59 | 2018-11-14 | Download | Change log | Javadoc
C# | 3.14.0 | 2018-08-02 | Download | Change log | API docs
Ruby | 3.14.0 | 2018-08-03 | Download | Change log | API docs
Python | 3.14.0 | 2018-08-02 | Download | Change log | API docs

**Comment by diemol** [comment]
You are right, the latest Python bindings version is 3.141.0

I see that you are getting this in the log:

```
1547132933531	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ETOOLL~1\\AppData\\Local\\Temp\\rust_mozprofile.fA9HxLJFTsgi"
1547132933888	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1547132933888	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
```

Looks like you are taking a screenshot, It seems something related to GeckoDriver, but I cannot confirm. Best would be **to provide first a** [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site), then @AutomatedTester or @whimboo could confirm if it is an issue in GeckoDriver or not.

**Comment by AutomatedTester** [comment]
It looks like Firefox is crashing from that log but there isnt much there. Could you enable the tracelog and add a link to that please 

https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by Thenakedgun** [comment]
@diemol I'm not sure what the purpose of the "screenshot" extension comments were in the logfile-- what was being run was the ~10 line "Test Script" specified in the initial post; no screenshots were attempted.

@AutomatedTester Yep, enabled it, and here's the log: [geckodriver.log](https://github.com/SeleniumHQ/selenium/files/2749536/geckodriver.log)

`Ctrl+C` was pressed in response to the input statement after ensuring Firefox had completely finished launching. This was the complete program, updated with the specified `firefox_options` (with the extension changed as the file was blocked): [test.txt](https://github.com/SeleniumHQ/selenium/files/2749541/test.txt)

Finally, this was the full console output: [ConsoleOutput.txt](https://github.com/SeleniumHQ/selenium/files/2749542/ConsoleOutput.txt)

**Comment by whimboo** [comment]
The screenshot log entries are totally unrelated here. Those come from the screenshot extension in Firefox. Further note that your example code is wrong given that `KeyboardInterrupt` is derived from `BaseException`, and your `except` block will not be used. The exception bubbles up.

>	driver.quit()
>	driver.close()

There is no need for the second line given that at this point Firefox has already been exited.

Also the attached log is NOT a trace level log. Please make sure that you take it from geckodriver.log.

**Comment by Thenakedgun** [comment]
@whimboo 
> There is no need for the second line given that at this point Firefox has already been exited.

Sorry if the order wouldn't make sense under normal circumstances. In my case, it doesn't matter whether `driver.close()` or `driver.quit()` is called, either together or independently, or what order I attempt them in, Firefox _will not_ close from either statement. I'll reverse the order of these statements in future however.

Additionally, I revised the `catch` statement slightly, this should now properly catch every exception, preventing it from bubbling up, correct? After these changes, the same behaviour from the bug report is still exhibited:
```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

try:
	opts = Options()
	opts.log.level = "trace"
	driver = webdriver.Firefox(firefox_options=opts, executable_path='./bin/geckodriver.exe')
	variable = input("Enter something or Ctrl+C: ")
	driver.get(variable)
except:
	pass
finally:
	driver.close()
	driver.quit()	
```

> Also the attached log is NOT a trace level log. Please make sure that you take it from geckodriver.log

The file I attached previously was the geckodriver.log file that was generated upon running the above script & pressing `Ctrl+C` at the input statement. I followed the link that @AutomatedTester provided, and included the code specified in the Python section of the Enabling Trace Logs post. If the resulting logfile is insufficient, could you please advise as to how I should modify the above code to provide the results you require?

**Comment by whimboo** [comment]
The problem actually is that you are using `firefox_options` as kwarg name when instantiating the Firefox driver. Instead it has to be just `options`.

**Comment by barancev** [comment]
@whimboo That's exactly what @Thenakedgun said, the document
https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
recommends to use `firefox_options` argument that is deprecated, please update the instruction.

**Comment by Thenakedgun** [comment]
@whimboo K. replaced the options line with:
```
	opts = Options()
	opts.log.level = "trace"
	driver = webdriver.Firefox(options=opts, executable_path='./bin/geckodriver.exe')
```

And this was the generated geckodriver.log: [geckodriver.log](https://github.com/SeleniumHQ/selenium/files/2752249/geckodriver.log)

**Comment by whimboo** [comment]
> @whimboo That's exactly what @Thenakedgun said, the document
> https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
> recommends to use `firefox_options` argument that is deprecated, please update the instruction.

Now I see. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1519925 to get this fixed. Thanks.

**Comment by whimboo** [comment]
@Thenakedgun thank you for the log. Now it is really a trace log. So I see that Marionette closes its connection about 5s after the new session has been created. I assume that is the time it has been taken for you to enter something for the `input()` command? It would be good if you could add some print lines to the Python code, so it will be visible when exactly which steps are getting executed. 

Note that I cannot replicate the issue on MacOS. And I don't have a chance to test under Windows right now. Maybe some more logging on the Selenium side might help.

**Comment by Thenakedgun** [comment]
@whimboo Thanks for trying this on Mac, figured it'd probably some Windows stuff-up; seems to happen on Win7 & 10 at the minimum. 

I could add print statements, but what would you suggest? The relevant code is only, like, 2 lines long. Stepping through with `pdb`, everything runs fine & the driver is successfully created, the input is prompted, `Ctrl+C` generates an `EOFError` & execution skips the next line & moves directly to the `except finally` statements. Is there a way for me to log the python statements that I'm running into the `geckodriver.log` file itself, so the timeline can be seen in one place?

> Marionette closes its connection about 5s after the new session has been created

This is interesting, because if I type a valid / invalid URL, the browser stays responsive regardless of how long I take to write it.

------------------------------------------------------------------------------------------------------------------

In the meantime if anyone else is running into this bug, this is the temporary workaround I implemented since I posted this bug report, but a real solution would be preferable, as this is a little gross:

```
tasklist = check_output(["tasklist", "/fi", "imagename eq firefox.exe"], shell=True).decode()
currentFFIDs = re.findall(r"firefox.exe\s+(\d+)", tasklist)
		
driver = webdriver.Firefox(options=opts, executable_path='./bin/geckodriver.exe')
		
tasklist = check_output(["tasklist", "/fi", "imagename eq firefox.exe"], shell=True).decode()
firefoxIds = set(re.findall(r"firefox.exe\s+(\d+)", tasklist)).difference(currentFFIDs)
		
...

try:
	driver.close()
	driver.quit()
				
	# Could't close the driver via normal means-- Force Close #
	except:
		taskkill = 'taskkill /f '+''.join(["/pid "+f+" " for f in firefoxIds]).strip()
		check_output(taskkill.split(), shell=True)
		print("\nHAD TO FORCE-CLOSE FIREFOX", flush=True)
```
Allegedly, "geckodriver.exe" was the name that appeared in the Window's task list at some point in the past, whereas I'm only seeing instances of "firefox.exe", which is why I couldn't just `taskkill` by name. If you don't care about possibly closing _other_ firefox instances, then you can just kill all without bothering to grep the selenium IDs.

**Comment by whimboo** [comment]
Would you mind upgrading to the latest released geckodriver 0.24.0 and creating a new trace log? Thanks.

**Comment by Thenakedgun** [comment]
Yep, sorry about the delay there. 

This is the log with geckodriver 0.24.0, [geckodriver.log](https://github.com/SeleniumHQ/selenium/files/2858960/geckodriver.log). 

Same issue manifested. Including the code again in case I've overlooked something due to the time gap. Listing the environment again due to a few small changes:

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 65.0
Browser Driver version: GeckoDriver v0.24.0
Language Bindings version: Python 3.7.2
Selenium Version: 3.141.0

## Test Script
```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

try:
	opts = Options()
	opts.log.level = "trace"
	driver = webdriver.Firefox(options=opts, executable_path='./bin/geckodriver24.exe')
	variable = input("Enter something or Ctrl+C: ")
	driver.get(variable)
except:
	pass
finally:
	driver.close()
	driver.quit()	
```

**Comment by whimboo** [comment]
I checked again the latest log and I don't see a problem. I don't see the `get` command executed but this should happen because you most likely enter a string without surrounding quotes? In such a case the except case is hit with a `name not defined` error, which in your code is silently ignored.

**Comment by Thenakedgun** [comment]
@whimboo, as far as I can see, the problem is still manifesting. As you say, the application shouldn't actually run `driver.get(variable)`, as the previous line throws an exception which is then caught and silently ignored. However, in the `finally` section, `driver.close` throws: `urllib3.exceptions.MaxRetryError`, I think that should be observable in the tracelog. The innermost (outermost?) exception says, `NameError: name 'driver' is not defined`, however, it not only *has* been defined at this point, but if a variable *is* input on line 9, whether `variable` points to a valid URL or not, the `finally` statement *can* close the webdriver instance as expected.

**Comment by barancev** [comment]
Is this issue still actual in the latest Firefox version? According to the log, it fails on the initialization stage when you constuct a driver and it's not related to `get` command or any unhandled exception.

I think it's useless to keep this issue open here even if it is still actual, we can't make anything in Selenium to fix it. If the failuire persists raise a new issue on https://github.com/mozilla/geckodriver/issues
