### ISSUE TITLE
selenium is taking too much time (exactly 5 mins) to click an element or get an element

### ISSUE THREAD

**Issue by Codude** [SeleniumHQ/selenium#6831]
## 🐛 Bug Report

selenium is taking too much time (exactly 5 mins) to click an element or get an element

## Environment

OS: OSX
Browser: Chrome
Browser version: latest
Browser Driver version: 3.141.59
Selenium Grid version (if applicable):3.141.59

**Comment by diemol** [comment]
Hi @Codude,

Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we didn't get any more information.
