### ISSUE TITLE
I couldn't succeed './go //javascript/atoms:test:run'

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium#6832]
### Please note that this issue tracker is not a help form and this issue will be closed.

I'm trying to build `selenium` project by following the README.md
I succeeded `./go build`. but I couldn't succeed `./go //javascript/atoms:test:run`
It has errors like that.

```
python buckw kill
python buckw build --stamp-build=detect --deep //javascript/atoms:test
Starting new Buck daemon...
[2019-01-10 15:05:45.131][error][command:null][tid:13][com.facebook.buck.io.watchman.WatchmanFactory] Watchman's stderr:
 2019-01-10T15:05:45,131: [] while computing statefile: failed to create C:\Users\XXX_X~1\AppData\Local\Temp/???-state:
 Invalid argument

[2019-01-10 15:05:45.131][error][command:null][tid:13][com.facebook.buck.io.watchman.WatchmanFactory] Error 1 executing
get-sockname
BUILD FAILED: The rule //javascript/atoms:test could not be found.
Please check the spelling and whether it exists in D:\Workspace\selenium\javascript\atoms\BUCK.
DOWNLOADED 0 ARTIFACTS, 0.00 BYTES, 0.0% CACHE MISS
BUILDING: FINISHED IN 1.2s
BUILD FAILED
go aborted!
python buckw build --stamp-build=detect --deep //javascript/atoms:test failed with exit code: 5
D:/Workspace/selenium/rake-tasks/buck.rb:52:in `block in buck_cmd'
D:/Workspace/selenium/rake-tasks/buck.rb:36:in `buck_cmd'
D:/Workspace/selenium/rake-tasks/buck.rb:227:in `block in (root)'
ArgumentError: unknown encoding name - MS949
```
What weird I think was `XXX_X~1`. That's not my username. 
I don't know why they was going to try to make folder at the path.

it's windows10 64bit and I installed BUCK and Watchman.

Let me know where I should look in if there is someone who know what it is.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by Jongkeun** [comment]
@diemol, Of course, I already asked on the slack. But no one could help. 
So I opened an issue here. Do you think if I send questions on the selenium user group is better?

**Comment by diemol** [comment]
Please keep trying on Slack/IRC, probably when you asked no one who has the knowledge to help you there was around.

**Comment by Jongkeun** [comment]
Ok Will do. Thanks!
