### ISSUE TITLE
webdriver request is pending and other actions can't be performed

### ISSUE THREAD

**Issue by gs202** [SeleniumHQ/selenium#6834]
## 🐛 Bug Report
A site contains popup that is written in JS, that appears after clicking on a specific button element.
After clicking that button, the popup will appear and disables clicking on any other element in the page behind it (it is possible to click on the popup), also it holds the request of the click until user interacts with the popup.

While using geckodriver, after clicking on the element that triggers the popup, i can interact with the popup (e.g. send another click function).
While in other drivers (i.e chromedriver) the 1st click request is pending and won't finish until the popup times out or until i manually click on it.

## Expected behavior

chromedriver should not wait for the request to end and continue to the next action (same as geckodriver)

## Test script or set of commands reproducing this issue

Python:
driver.find_element_by_id('my_button').click() # will cause the popup to appear
driver.switch_to.frame('popup_frame')
driver.find_element_by_id('continue_button').click()

The 1st click action won't be finished and stay pending

## Environment

OS: MacOS / Win10 / Linux
Browser: Chrome
Browser version: Version 71.0.3578.98
Browser Driver version: chromedriverVersion 2.45.615355
Language Bindings version: Python 3.6
Selenium Grid version (if applicable): N/A

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
