### ISSUE TITLE
firefox.Options. setPreference() not a function

### ISSUE THREAD

**Issue by nombrekeff** [SeleniumHQ/selenium#6835]
## 🐛 Bug Report
Hi, I've been referencing  [this](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox.html) docs, wich seams incorrect.

I've been trying to set the firefox driver path, but when testing  i've come across this:

It says in the [`firefox.Options`](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox_exports_Options.html) docs that a method called  `.setPreference(key, value)` exists but when called it says it is not defined. 

Are they intended to exist? Or is that docs outdated?

If so where could I find info in how to set the driver path?

_PD: I can attach more info if needed!_

## Environment
OS:  Windows 8
Browser: Firefox
Browser version: 63.0.1 (32-bit)
Browser Driver version: 0.23.0

EDIT:
I'm using version: `3.6.0` of selenium-webdriver

**Comment by AutomatedTester** [comment]
You have 2 commands that you are saying doesnt exist, one in the summary and one in the body. Which command are you after?

**Comment by nombrekeff** [comment]
Oh sorry! I was having problems with both and then realized the `useGeckoDriver` was not in the docs so I removed it.
I'm interested in the `setPreference`, or some other way of setting the driver path.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Also `setPreference` can't be used to set the path to a driver. This method sets browser preferences that you can see if you enter `about:config` in the browser addressbar.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by nombrekeff** [comment]
> This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

Oh I see, thanks,  
I will be leaving a question over there.



> Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.
I will create an example of the issue and posted here in a bit.

**Comment by nombrekeff** [comment]
I've made a gist with the failing example: https://gist.github.com/nombrekeff/dc2b118ab76e899f3352da717f7306a8

**Comment by nombrekeff** [comment]
> Referencing the question "How to set the profile":

I've tested and the `.setProfile` method and seems to be working, so I consider that fixed.

**Comment by barancev** [comment]
Yes, `setPreference` method was added in version 4.0.0-alpha

**Comment by nombrekeff** [comment]
Ahh okey I imagined it migth of been added in newer versions. I will update then!
I'm going to leave an question regarding  the setting of the driver on the google groups and continue there, I would consider this issue closed from my side!
