### ISSUE TITLE
Even in a root, cannot search element for specific frame.

### ISSUE THREAD

**Issue by skeksk91** [SeleniumHQ/selenium#6836]
- Chrome

Hi 
This is just for a curious.

I sometimes got stuck in the case that can't search a element,
because the element included in specific frame. 

I was started to search element in a root, I don't make sense the concept
we have to get driver move into the frame which has the element,
and start to search.

Why don't selenium concept doesn't allow below
Find_element_by_id("AAA") -> then get element even it's in the specific frame (descendants in tree)

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
