### ISSUE TITLE
Saucelab execution failed when i try to execute on IE11 on Windows

### ISSUE THREAD

**Issue by divyjain7688** [SeleniumHQ/selenium#6838]
I created 1 jenkins job with sauce on demand plugin added to it
In jenkin i have given value for webdriver as Windows 10 Internet Explorer 11
and in my code i have defined below capabilities
 Class<? extends BaseClassV8_Parallel> SLclass = this.getClass();

            DesiredCapabilities caps = new DesiredCapabilities();

            caps.setBrowserName(System.getenv("SELENIUM_BROWSER"));
            caps.setVersion(System.getenv("SELENIUM_VERSION"));
            caps.setCapability(CapabilityType.PLATFORM, System.getenv("SELENIUM_PLATFORM"));
            caps.setCapability("name", SLclass.getSimpleName());
            caps.setCapability("screenResolution", "1920x1080");
            caps.setCapability("tunnelIdentifier", "hdsupply");
            caps.setCapability("seleniumVersion", "3.4.0");

But it is failing with beow reason in jenkins
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 17, Time elapsed: 27.615 s <<< FAILURE! - in TestSuite
[ERROR] driverSetup(com.selenium.ebiz.smoketest.SmokeTest_End_To_End_Scenario_1_New_V8)  Time elapsed: 27.131 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Connection refused: connect
Command duration or timeout: 3.68 seconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'gfmwsb01lds.hsi.hughessupply.com', ip: '10.224.196.74', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.8.1.el6.x86_64', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{enablePersistentHover=true, ie.fileUploadDialogTimeout=3000.0, platform=WINDOWS, ie.ensureCleanSession=false, ie.browserCommandLineSwitches=, requireWindowFocus=false, takesScreenshot=true, browserName=internet explorer, javascriptEnabled=true, unexpectedAlertBehaviour=dismiss, browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, unhandledPromptBehavior=dismiss, pageLoadStrategy=normal, ignoreZoomSetting=false, hasMetadata=true, version=11, nativeEvents=true, elementScrollBehavior=0.0, webdriver.remote.sessionid=d25e0964821b48d5a08939485c3f08b9, initialBrowserUrl=about:blank, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true}]
Session ID: d25e0964821b48d5a08939485c3f08b9
Caused by: java.net.ConnectException: Connection refused: connect

Can anyone please help me in this

**Comment by shs96c** [comment]
I see you're using Selenium 3.4.0. Does the same happen with the most recent version of the IEDriverServer and Selenium?

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
