### ISSUE TITLE
Build Error  After chrome update

### ISSUE THREAD

**Issue by vitalisc** [SeleniumHQ/selenium#6839]
After updating my chromedriver to the latest driver  i started getting build errors 

1>------ Build started: Project:  Booster, Configuration: Debug Any CPU ------
1>   Booster -> W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\ Booster.exe
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): warning MSB3026: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): error MSB3027: Could not copy "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". Exceeded retry count of 10. Failed.
1>W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\Selenium.WebDriver.ChromeDriver.targets(66,5): error MSB3021: Unable to copy file "W:\Vb projects\ Booster\ Booster\packages\Selenium.WebDriver.ChromeDriver.2.45.0\build\..\driver\win32\chromedriver.exe" to "W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe". The process cannot access the file 'W:\Vb projects\ Booster\ Booster\ Booster\bin\Debug\chromedriver.exe' because it is being used by another process.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

OS:!-- Windows 8.1?
Browser: -- Chrome
Browser version: 
Browser Driver version: <!--: ChromeDriver 2.43,

**Comment by jimevans** [comment]
Not really a Selenium issue, but check your task list (Control+Escape on Windows) for running `chromedriver.exe` processes. Kill any you find running and try again.

**Comment by vitalisc** [comment]
ok thanks it worked
