### ISSUE TITLE
move() should not use default offsets=0

### ISSUE THREAD

**Issue by johnjbarton** [SeleniumHQ/selenium#6842]
## 🐛 Bug Report

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/input.js#L397

```js
  move({x = 0, y = 0, duration = 100, origin = Origin.VIEWPORT}) {
    return {type: Action.Type.POINTER_MOVE, origin, duration, x, y};
  }
```
Using the default of `0` here is not correct for [JSON wire protoctol drivers](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidmoveto).
The code has to allow undefined to be passed in because the no-offset case does not mean zero offset.
------------
POST /session/:sessionId/moveto

Move the mouse by an offset of the specificed element. If no element is specified, the move is relative to the current mouse cursor. **If an element is provided but no offset, the mouse will be moved to the center of the element.** If the element is not visible, it will be scrolled into view.
URL Parameters:
:sessionId - ID of the session to route the command to.
JSON Parameters:

- element  {string} Opaque ID assigned to the element to move to, as described in the WebElement JSON Object. If not specified or is null, the offset is relative to current position of the mouse.
- xoffset - {number} X offset to move to, relative to the top-left corner of the element. If not specified, the mouse will move to the middle of the element.
- yoffset - {number} Y offset to move to, relative to the top-left corner of the element. If not specified, the mouse will move to the middle of the element.
------------

**Comment by p0deje** [comment]
If I understand the code correctly, it doesn't implement JSON Wire Protocol actions, but rather [W3C WebDriver specification](https://w3c.github.io/webdriver/#pointer-actions). There, both xoffset and yoffset are required.

**Comment by johnjbarton** [comment]
The client also supports JSON wire protocol (used by most browsers still)
https://github.com/SeleniumHQ/selenium/blob/07a18746ff756e90fd79ef253a328bd7dfa9e6dc/javascript/node/selenium-webdriver/lib/input.js#L998

**Comment by jimevans** [comment]
@johnjbarton In point of fact, the W3C dialect is the default protocol used by all most recent versions of each browser driver except chromedriver, so I’m not sure the phrase “used by most browsers” is entirely accurate.

**Comment by johnjbarton** [comment]
Unfortunately this issue is a bigger issue than I originally implied. 

On firefox, which uses a W3C driver, mouseMove fails if x or y offsets are `undefined`. (I could not find anything in the spec to require this). So for this case the default value of `0` is required.

**Comment by diemol** [comment]
Is this still an issue with the latest browser versions and Selenium WebDriver versions?

**Comment by diemol** [comment]
Closing this as we did not get more information, please feel free to open a new issue if the problem still persists after trying with the most recent versions.
