### ISSUE TITLE
I can't get page source.

### ISSUE THREAD

**Issue by fengbin8606** [SeleniumHQ/selenium#6845]
## 🐛 Bug Report
My code is:

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class Test {

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "D:\\ChromeDriver\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        ChromeDriver driver = new ChromeDriver(options);
        driver.get("http://ccc.spdb.com.cn/news/qgxhd/");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(driver.getPageSource());
        driver.quit();
    }

}

## To Reproduce
The result is :
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 6315
Only local connections are allowed.
一月 12, 2019 3:40:02 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: OSS
`<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>`

## Expected behavior
The page source of "http://ccc.spdb.com.cn/news/qgxhd/". 

## Environment

OS: Windows 7
Browser: Chrome
Browser version: 71.0.3578.98
Browser Driver version: ChromeDriver 2.45
Language Bindings version: Java 3.14.0 
Selenium Grid version (if applicable):

**Comment by lilin3** [comment]
if your os is windows, you have to add argument "--disable-gpu"
you can google search the use of headless chrome

**Comment by fengbin8606** [comment]
I test argument "--disable-gpu","--allow-running-insecure-content","--disable-web-security","--enable-automation","--no-sandbox","--disable-infobars","--disable-dev-shm-usage","--disable-browser-side-navigation".  The result is the same:`<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>`

**Comment by lilin3** [comment]
last time I get empty page source is because the site use https and use unsafe ssl certificate. but you are using http.

**Comment by fengbin8606** [comment]
```
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class Test {

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "D:\\ChromeDriver\\chromedriver.exe");
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--disable-gpu");
        options.addArguments("--allow-insecure-localhost");
        options.addArguments("--allow-running-insecure-content");
        options.addArguments("--ignore-certificate-errors");
        options.addArguments("--no-sandbox");
        options.addArguments("--window-size=1280,1000");
        options.setCapability("acceptSslCerts", true);
        options.setCapability("acceptInsecureCerts", true);
        ChromeDriver driver = new ChromeDriver(options);
        driver.get("http://ccc.spdb.com.cn/news/qgxhd/");
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(driver.getPageSource());
        driver.quit();
    }

}
```
The result is the same: `<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>`

##Environment

OS: Windows 7
Browser: Chrome
Browser version: 71.0.3578.98
Browser Driver version: ChromeDriver 2.45
Language Bindings version: Java 3.14.0
Selenium Grid version (if applicable):

**Comment by lilin3** [comment]
there are two error in the chrome cosole log, maybe printing out it can help you, I have no solution.
if you don't use headless mode, it works fine

**Comment by barancev** [comment]
Please report this issue to https://bugs.chromium.org/p/chromedriver/issues/list
