### ISSUE TITLE
How to save chrome user profile by selenium?

### ISSUE THREAD

**Issue by buff2017** [SeleniumHQ/selenium#6846]
I doing make automation tools to save chrome user profile for my company by same config.

but selenium seem like cant do that.`webdriver.ChromeOptions` only do set chrome options when the program runing, but not save it which mean when open chrome again , everything is reset.

i tried used selenium to do that, following is my code. and also i tried used `execute_script` or `find_element_by_xpath` to simulation user setting action. but that's a lot job(cuz shadow element)

```python
options = webdriver.ChromeOptions()
prefs = {
  'profile.default_content_setting_values': {
 'images': 2
 }
}
options.add_experimental_option('prefs', prefs)
options.add_argument('--profile-directory=Default')
# options.add_argument('--profile-directory=Profile 1')

options.add_argument(r"user-data-dir=C:\Users\myname\AppData\Local\Google\Chrome\User Data")  # Path to your chrome profile
driver = webdriver.Chrome(executable_path=r"C:\Users\myname\Desktop\Selenium\drive\chromedriver.exe",
                          chrome_options=options)
driver.get('chrome://settings/content/images?search=image')
```

so there have another way do batch processing chrome profile?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
