### ISSUE TITLE
[Suggestion] Starting a service in Python bindings is slow

### ISSUE THREAD

**Issue by iwasa-kosui** [SeleniumHQ/selenium#6848]
## Question

In my opinion, retrying interval to start the Service in Python bindings is a little too long.
We have to wait at least one second.
So that, it's good that shorten the retrying interval.
Does anyone have a good idea?

## Motivation
As you see in the below, we have to wait 1 second because of `time.sleep(1)` to start the Service.
I think it's so long.

https://github.com/SeleniumHQ/selenium/blob/11c25d75bd7ed22e6172d6a2a795a1d195fb0875/py/selenium/webdriver/common/service.py#L131-L135
https://github.com/SeleniumHQ/selenium/blob/11c25d75bd7ed22e6172d6a2a795a1d195fb0875/py/selenium/webdriver/common/service.py#L97-L104

**Comment by cgoldberg** [comment]
I agree that isn't optimal.
