### ISSUE TITLE
Selenium IDE: 'Execute Script' command fails if the variable has a line break

### ISSUE THREAD

**Issue by Andy802** [SeleniumHQ/selenium#6858]
## 🐛 Bug Report

I'm using Selenium IDE v3.4.4 in Chrome. I'm using the 'store text' command to store an address (with line breaks) as a variable then running 'execute script' on that variable I get the error: Failed: Invalid or unexpected token

Html example is like:

```
<tr>
  <td>Address</td>
  <td>
    <span>"Unit 1"
    <br>
    "South Street"
    <br>
    "London"
    </span>
  </td>
</tr>
```

//I get the text value
Command: store text
target: xpath=//tr[td='Address']/td[2]/span
value: custAdd

//I do any javascript command and I get the error
Command: execute script
target: return ${custAdd}.replace(String.fromCharCode(10),' ')
Value: custAdd

I get the error. Failed: Invalid or unexpected token

What does work:

Without doing the 'execute script' I can use the variable with the 'type' command to type the stored address into another field.

I can do the 'execute script' command on any stored variable that has no line breaks.

I would expect this to work (it has done in an old version of selenium 2.9.1 on firefox).

OS: Windows 10
Browser: Chrome
Browser version:  71.0.3578.98
Browser Driver version: Selenium IDE 3.4.4

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #548](https://github.com/SeleniumHQ/selenium-ide/issues/548) via [**ZenHub**](https://www.zenhub.com/)
