### ISSUE TITLE
ErrorCode handling in shorter version

### ISSUE THREAD

**Issue by lkord** [SeleniumHQ/selenium#6859]
## 🚀 Feature Proposal

It is a code refactor proposal

## Motivation

Good python code practices. Please comment and discuss.

## Example

Instead of https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L141

    from enum import Enum

    # some mock data
    status = 'OK'
    exception_class = -1

    # proposal here
    class Code:
        def __init__(self, code, status, ex):
            self.code = code
            self.status = status
            self.ex = ex

        def check(self, status):
            return status in self.status

    class ErrorCode(Enum):
        """Valid Error Codes"""
        SUCCESS = Code(0, '', None)
        OK = Code(1, 'OK', 'exception_1')
        FALSE = Code(2, 'False', 'exception_2')
        TRUE= Code(3, 'True', 'exception_3')

    # use this in handler instead of ifs
    # if status == ErrorCode.SUCCESS.value.code:
    #    print('do stuff for success')
     for case in ErrorCode:
        if case.value.check(status):
            exception_class = case.value.ex
            break
        else:
            exception_class = 'webdriver_ex'

    print(exception_class)

**Comment by cgoldberg** [comment]
this code would break under Python 2.7 unless we added another dependency or implemented our own enum.

**Comment by lkord** [comment]
@cgoldberg enum is not necessary here. It brings the uniqueness of fields only. We can skip Enum  in ErrorCode definition and thus `.value` in `for` loop
`
# if status == ErrorCode.SUCCESS.code:
#    print('do stuff for success')
 for case in ErrorCode:
    if case.check(status):
        exception_class = case.ex
        break
    else:
        exception_class = 'webdriver_ex'
`

**Comment by cgoldberg** [comment]
You can submit a PR with your proposed changes... although I don't see the need for changing this code.

**Comment by barancev** [comment]
Yes, it's better be a PR.
