### ISSUE TITLE
Font family in at symbol (@) when using getAttribute

### ISSUE THREAD

**Issue by hamiltonmarques** [SeleniumHQ/selenium#6861]
Hi,
When we use getAttribute to get HTML5 validation message, if it contains at symbol (@) the font family makes difference.

Prints:
![image](https://user-images.githubusercontent.com/23129723/51317298-5baefd00-1a3e-11e9-8254-e8477de1e3c0.png)

![image](https://user-images.githubusercontent.com/23129723/51318143-a29df200-1a40-11e9-9356-69eec3084fb2.png)

![image](https://user-images.githubusercontent.com/23129723/51318168-b6495880-1a40-11e9-9a99-86770af7ab81.png)

![image](https://user-images.githubusercontent.com/23129723/51318231-dda02580-1a40-11e9-891d-a07fbdd18909.png)

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by hamiltonmarques** [comment]
### login.feature
Feature: Login
Scenario Outline: Login with invalid email
        Given I am in login page
        When I login with email "hamilton.rosa@" and password "1234"
        Then the message `"<Message>"` should be displayed in the field "Email"

    Examples:
        | Message                                                           |
        | Insira uma parte depois de "@". "hamilton.rosa@" está incompleto. |

### login.steps.ts
import { Given, When, Then } from 'cucumber'
import { expect } from 'chai'
import { LoginPage } from '../../../src/page-objects/login/login.po'
import { driver } from '../../../src/support/driver';
import { FormPage } from '../../../src/page-objects/global/form.po';

let loginPage = LoginPage.page();
let formPage = FormPage.page();

Given(/^I am in login page$/, async () => {
    await driver.get('https://hongkiat.github.io/html5-loginpage/');
});

When(/^I login with email `"(.*)"` and password `"(.*)"`$/, async (email: string, password: string) => {
    await loginPage.setEmail(email);
    await loginPage.setPassword(password);
    await loginPage.clickLogin();
});

Then(/^the message `"(.*)"` should be displayed in the field `"(.*)"`$/, async (expectedMessage: string, fieldName: string) => {
    let message = await formPage.getValidationMessage(fieldName);
    return await expect(expectedMessage).be.equals(message);
});

### login.po.ts
import { SEARCH_TYPE, setValue, click } from '../../support/driver'

export class LoginPage {

    $inputEmail = 'usermail';
    $inputPassword = 'password';
    $inputLogin = '//input[@value="Login"]';

    async setEmail(email: string) {
        return await setValue(this.$inputEmail, email, SEARCH_TYPE.NAME);
    }
    async setPassword(password: string) {
        return await setValue(this.$inputPassword, password, SEARCH_TYPE.NAME);
    }
    async clickLogin() {
        return await click(this.$inputLogin, SEARCH_TYPE.XPATH);
    }
    static page() {
        return new LoginPage();
    }
}

### form.po.ts
import { SEARCH_TYPE, getValidationMessage } from '../../support/driver'
import { String } from 'typescript-string-operations'

export class FormPage {

    $selInput = '//label[text()="{0}"]/following::input[1]';

    async getValidationMessage(fieldName: string) { 
        return await getValidationMessage(String.Format(this.$selInput, fieldName), SEARCH_TYPE.XPATH);
    }
    static page() {
        return new FormPage();
    }
}

### driver.ts
import { WebDriver, Capabilities, Builder, until, By } from "selenium-webdriver";
import { ServiceBuilder, setDefaultService } from 'selenium-webdriver/chrome';
import { path } from 'chromedriver';

setDefaultService(new ServiceBuilder(path).build());

export let driver: WebDriver;

export enum SEARCH_TYPE {
    CSS,
    CLASS,
    NAME,
    LINK_TEXT,
    ID,
    PARTIAL_LINK_TEXT,
    XPATH,
    TAG
}
export function setupDriver() {
    driver = new Builder().withCapabilities(Capabilities.chrome()).build();
}
export async function quitDriver() {
    return await driver.quit();
}
export async function getValidationMessage(selector: string, t: SEARCH_TYPE) {
    await waitForElementLocated(selector, t);
    return await driver.findElement(getCondition(selector, t)).getAttribute('validationMessage');
}
export async function setValue(selector: string, value: string, t: SEARCH_TYPE) {
    await waitForElementLocated(selector, t);
    return await driver.findElement(getCondition(selector, t)).sendKeys(value);
};
export async function click(selector: string, t: SEARCH_TYPE) {
    await waitForElementLocated(selector, t);
    let element = await driver.findElement(getCondition(selector, t));
    return await element.click();
};
export async function waitForElementLocated(selector: string, type: SEARCH_TYPE, timeout?: number | undefined) {
    return await driver.wait(until.elementLocated(getCondition(selector, type)), timeout);
};
function getCondition(selector: string, t: SEARCH_TYPE) {
    switch (t) {
        case SEARCH_TYPE.CLASS:
            return By.className(selector);
        case SEARCH_TYPE.CSS:
            return By.css(selector);
        case SEARCH_TYPE.NAME:
            return By.name(selector);
        case SEARCH_TYPE.LINK_TEXT:
            return By.linkText(selector);
        case SEARCH_TYPE.PARTIAL_LINK_TEXT:
            return By.partialLinkText(selector);
        case SEARCH_TYPE.ID:
            return By.id(selector);
        case SEARCH_TYPE.XPATH:
            return By.xpath(selector);
        case SEARCH_TYPE.TAG:
            return By.tagName(selector);
    }
};

**Comment by hamiltonmarques** [comment]
Hi!
Let me simplify with a console application:

using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System;

namespace ValidationMessage
{
    class Program
    {
        static void Main(string[] args)
        {
            string inputEmail = "usermail";
            string inputPassword = "password";
            string inputLogin = "//input[@value=\"Login\"]";
            string selInput = "//label[text()=\"Email\"]/following::input[1]";

            IWebDriver driver = new ChromeDriver();

            driver.Navigate().GoToUrl("https://hongkiat.github.io/html5-loginpage/");

            driver.FindElement(By.Name(inputEmail)).SendKeys("hamilton.rosa@");
            driver.FindElement(By.Name(inputPassword)).SendKeys("1234");
            driver.FindElement(By.XPath(inputLogin)).Click();

            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));

            IWebElement validationMessage = wait.Until(ExpectedConditions.ElementIsVisible(By.XPath(selInput)));

            string message = validationMessage.GetAttribute("validationMessage");
            string expectedMessage = "Insira uma parte depois de \"@\". \"hamilton.rosa@\" está incompleto.";

            if (message.Equals(expectedMessage))
            {
                Console.WriteLine("\nNice! Test passed!");
            }
            else
            {
                Console.WriteLine("\nAren't they equals?\n" + message);
                Console.WriteLine(expectedMessage);

                Console.WriteLine("\nCoffee time!");
            }

            driver.Quit();
            Console.ReadKey();
        }
    }
}

**Comment by barancev** [comment]
The issue is not related to @ sign, it's a space issue. Look at this comparison, the actual value is on the left, the expected message is on the right:
![image](https://user-images.githubusercontent.com/617090/56015474-d320bf80-5d01-11e9-980d-c9a4d6b4b26e.png)
You can see that the browser sometimes uses an `A0` space char instead of `20`. It's a feature of the Portuguese locale. I tried English, Spanish, Russian -- they always use `20` space char.

We'll discuss if it is a Selenium responsibility to "fix" spaces in attribute values or they should be kept untouched.

**Comment by titusfortner** [comment]
Selenium should return exactly what is in the DOM. Test library code can manage white space issues, especially if it is limited to specific locales.
