### ISSUE TITLE
addArguments dont work

### ISSUE THREAD

**Issue by IhChowdhury** [SeleniumHQ/selenium#6867]
I am trying to open browser in useing debugger address but after using setExperimentalOptions no addArguments() dont work. Here is my code.. Anyone can help me?

String PROXY = "104.248.166.226:3128";
        Proxy proxy = new Proxy();
        proxy.setHttpProxy(PROXY)
                .setFtpProxy(PROXY)
                .setSslProxy(PROXY);
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.PROXY, proxy);

//        WebDriver driver = new FirefoxDriver();
        ChromeOptions options = new ChromeOptions();

        options.addArguments("start-maximized");
        options.addArguments("--disable-images");
        options.addArguments("user-agent=\"$1\"");

        Map<String, Object> prefs = new HashMap<>();
        prefs.put("profile.default_content_setting_values.images", 2);
        prefs.put("profile.default_content_settings.popups", 0);
        prefs.put("profile.default_content_settings.geolocation", 2);
//        options.setExperimentalOption("prefs", prefs);
        options.setExperimentalOption("debuggerAddress", "localhost:" + port);

        capabilities.setCapability(ChromeOptions.CAPABILITY, options);
        driver = new ChromeDriver(capabilities);
[New Text Document (2).txt](https://github.com/SeleniumHQ/selenium/files/2778759/New.Text.Document.2.txt)

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com) where the community can help you as well.
