### ISSUE TITLE
Python driver.quit() throwing BadStatusLine error

### ISSUE THREAD

**Issue by bioneyez** [SeleniumHQ/selenium#6870]
## 🐛 Bug Report
I'm using Selenium with Python and Chrome. When I'm calling driver.quit() the following error occurs: https://gist.github.com/bioneyez/45fa305a0dda2d2b97511223b8e8872d
Here is the chromedriver log I got: 
[qc1.log](https://github.com/SeleniumHQ/selenium/files/2782599/qc1.log)

## To Reproduce
Simple example code: https://gist.github.com/bioneyez/34cfa8290b80ed2dbfd3e277dc3e5898

## Expected behavior
Chrome opens google, then closes without any errors.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 71.0.3578.98
Browser Driver version: Chromedriver 2.45.615291
Language Bindings version: Python 2.7.12
Selenium: 3.141.0

**Comment by AutomatedTester** [comment]
from the log I dont think you are using 3.141.0. Please can you double check

**Comment by bioneyez** [comment]
>>> import selenium
>>> print selenium.__version__
3.141.0

I used this piece of code to check.

**Comment by AutomatedTester** [comment]
@bioneyez I dont see any of the code going through urllib3 in the stack which was used to fix this issue a few months ago.

**Comment by bioneyez** [comment]
And what would be the solution?
I think i have the urllib3 downloaded since running 

> pip install --upgrade selenium
```
Requirement already up-to-date: selenium in c:\python27x86\lib\site-packages (3.141.0)
Requirement already satisfied, skipping upgrade: urllib3 in c:\python27x86\lib\site-packages (from selenium) (1.24.1)
```

**Comment by bioneyez** [comment]
Urllib3 is installed and selenium still uses urllib2, instead of 3.  Any idea how can i solve this problem?

**Comment by cgoldberg** [comment]
> Any idea how can i solve this problem?

remove the old selenium package and install the newest version of the selenium Pyton bindings.  Then make sure you are running the same Python interpreter that you installed the package for.

**Comment by bioneyez** [comment]
@cgoldberg I tried what you suggested and the error is still present. I printed out the selenium version, the interpreter and the version of interpreter in use. Everything seems right.
Selenium version: 3.141.0
Interpreter: CPython
Version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

**Comment by cgoldberg** [comment]
but you are still running old code

**Comment by bioneyez** [comment]
you mean python 2.7.12?

**Comment by cgoldberg** [comment]
no.. you are not running the latest version of selenium package

**Comment by bioneyez** [comment]
I could be wrong but I think i have the latest one. 
I tried uninstalling the existing one just like you told me with `pip uninstall selenium`
then `pip install selenium`
this installed selenium 3.141.0.
I even tried running `pip install --upgrade selenium` which told me that selenium is up-to date.

> Requirement already up-to-date: selenium in c:\python27x86\lib\site-packages (3.141.0)
> Requirement already satisfied, skipping upgrade: urllib3 in c:\python27x86\lib\site-packages (from selenium) (1.24.1)

**Comment by AutomatedTester** [comment]
Are you using a virtualenv or could you try use an virtualenv to make sure
that things are working as expected?

**Comment by bioneyez** [comment]
I tried virtualenv and the same error is present.
```
Selenium version: 3.141.0
Interpreter: CPython
Version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

DevTools listening on ws://127.0.0.1:50935/devtools/browser/7557c662-4424-4eba-925b-7b46cf521e3f
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    driver.quit()
  File "C:\Users\lorand.fazakas\.virtualenvs\pythonenv-BQAFWgtf\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 158, in quit
    self.service.stop()
  File "C:\Users\lorand.fazakas\.virtualenvs\pythonenv-BQAFWgtf\lib\site-packages\selenium\webdriver\common\service.py", line 151, in stop
    self.send_remote_shutdown_command()
  File "C:\Users\lorand.fazakas\.virtualenvs\pythonenv-BQAFWgtf\lib\site-packages\selenium\webdriver\common\service.py", line 127, in send_remote_shutdown_command
    url_request.urlopen("%s/shutdown" % self.service_url)
  File "c:\python27x86\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27x86\Lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "c:\python27x86\Lib\urllib2.py", line 447, in _open
    '_open', req)
  File "c:\python27x86\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\python27x86\Lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "c:\python27x86\Lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "c:\python27x86\Lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "c:\python27x86\Lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "c:\python27x86\Lib\httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by rnth** [comment]
Update selenium to using 3.3.1 instead of 3.141 fixes issue

**Comment by bioneyez** [comment]
> Update selenium to using 3.3.1 instead of 3.141 fixes issue

I got the same error as before.

**Comment by AutomatedTester** [comment]
Closing this issue as it is an issue on a specific machine/setup of machines.
