### ISSUE TITLE
Change event not firing on inputs during playback

### ISSUE THREAD

**Issue by mcclellanmj** [SeleniumHQ/selenium#6871]
## 🐛 Bug Report
Selenium IDE tests which type into input fields do not fire the change event during playback in the IDE.  In the case of the "type" command it will trigger a change event for the initial clear but will not trigger the change event after finishing the typing.  In the case of "send keys" no change event is triggered at all.

If the same test is run using webdriver using the side-runner these fire as expected.

## To Reproduce
Type into any input field that has only a change event listener attached to it and then shift focus to another field. 

## Expected behavior
When the focus shifts from one element to another the change event handler should fire.  In the example side file this is expected to show the value of the input to the right in a span.

## Project file reproducing this issue (highly encouraged)
[Selenium OnChange.zip](https://github.com/SeleniumHQ/selenium-ide/files/2751621/Selenium.OnChange.zip)

## Environment

OS: Windows 10
Selenium IDE Version:  3.4.4

Browser: Firefox
Browser Version: 64.0

**Comment by corevo** [comment]
Potential IDE workaround in https://github.com/SeleniumHQ/selenium-ide/commit/925dd410e2a6c2f534a5922f198c513fb5137e48  
For full fix need to make sure to fire `input` event after every key stroke, probably whenever keyboard.pressKey is called.

**Comment by mcclellanmj** [comment]
I updated my test case to include showing the input events and it does appear to show the input events.  The change event is also now firing with the fix that @corevo put in, prior to that I would see input events but never see the change event.

[Selenium-OnChangeAndInput.zip](https://github.com/SeleniumHQ/selenium/files/2787615/Selenium-OnChangeAndInput.zip)

**Comment by barancev** [comment]
OK, so what can/should we change in atoms?

**Comment by mcclellanmj** [comment]
I'm not sure what would need to change in atoms.  It does seem like something in the way atoms is typing input causes the browser to not see the input as changed.  For my purposes the workaround that @corevo put in the Selenium-IDE project has been sufficient though.

**Comment by halbri** [comment]
Thanks so much corevo, it's doing all i need now!
Your Great!
