### ISSUE TITLE
Add support for W3C "New Window" command

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#6873]
## 🚀 Feature Proposal

At the last TPAC it was decided to add a new command called "New Window" which allows tests to open a new tab or window. The related work can be seen at https://github.com/w3c/webdriver/issues/1138.

All drivers will have support for this probably soon, so it would be good to get support added in all the Selenium bindings.

As of now the command supports two types of browsing contexts to open, which are `tab` and `window`. If nothing gets passed in the browser will decide the best type on its own. This also happens when the requested type is not supported, eg. new browser window on mobile.

## Example

Please provide an example for how this feature would be used.

```python
handle, _type = driver.new_window(type_hint="tab")
driver.switch_to(handle)
```

More WebDriver tests which are part of the web-platform-tests suite can be found at https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/new_window.

**Comment by whimboo** [comment]
@barancev mind adding labels for all bindings? Thanks.

**Comment by whimboo** [comment]
Could anybody from the Selenium community suggest how the API should look like? The command returns a dictionary like the following:

> {u'type': u'tab', u'handle': u'8589934593'}

It's most likely not appropriate to return both but only the `handle` in the client's method. Type would only be interesting if a specific type of top-browsing context has been requested, but a different one has been created by the browser due to eg. system limitations. Should the client method handle such a case and raise an error eg. when getting a `strict_type` parameter?

**Comment by jimevans** [comment]
@whimboo The initial implementation in the .NET bindings returns neither. In order to remain consistent with other methods in the `ITargetLocator` interface, the driver switches the command context to the newly opened window and returns a reference to the current driver. Thus making the usage as follows:

    // Note that focusedDriver and driver are the same object. This construction
    // was used simply to show the return type. 
    IWebDriver focusedDriver = driver.SwitchTo().NewWindow(WindowType.Tab);
    string newWindowHandle = driver.CurrentWindowHandle;

One could argue with this approach, and it does obscure the details of the wire protocol, but from the Selenium usage point of view, I believe API consistency concerns are more important. I suspect the Java language bindings will take a similar approach. For Python and Ruby, which largely eschew the role-based interface concept, maintainers may elect a different approach.

**Comment by jimevans** [comment]
I'm reopening this, as the code needs to be added to Java, Ruby and JS language bindings.

**Comment by whimboo** [comment]
@barancev would you have the time to add the support to the Java bindings? Not sure who works on ruby and nodejs.

**Comment by barancev** [comment]
Implemented in Java binding: 501f2f76f71a0fa61e7e3d359ae8c7b232b28006

**Comment by whimboo** [comment]
So Roby is taking care of in #6946? Whom can we CC for the nodejs binding?

**Comment by jimevans** [comment]
@jleyba, that’s likely to be you...

**Comment by corevo** [comment]
I had some time on my hands #6956  
I could use @jleyba's review

**Comment by p0deje** [comment]
Ruby support landed in 2960a3d01ed016900c1e097015ab3329e6bd65bc.

**Comment by barancev** [comment]
Node.js support added by 59e5bf25a585a92239ccba557d8df0f20333e04f
And now we can close this issue.

**Comment by whimboo** [comment]
Thanks everyone in helping with that addition! I hope people will enjoy it now in being able to remove all the quirks.
