### ISSUE TITLE
set_attribute not availabl in python

### ISSUE THREAD

**Issue by Mattwmaster58** [SeleniumHQ/selenium#6876]
## 🚀 Feature Proposal

It would be nice to add the method `set_attribute` to the base webdriver class.

## Motivation

Other language bindings, such as Java, [apparently have a `setAttribute` method](https://stackoverflow.com/questions/35127108/how-to-set-value-to-input-web-element-using-selenium). I've run into multiple situations where this would come in handy.

## Example

Instead of using `send_keys` to fill out a long chunk of text, using the proposed `set_attribute` the field value could be set in one go without as much delay as using `send_keys`

**Comment by AutomatedTester** [comment]
looking at the Java API it does not have this method you want. This can easily be solved by using `execute_script`
