### ISSUE TITLE
Node to Hub connection question

### ISSUE THREAD

**Issue by michaelgeorgeattard** [SeleniumHQ/selenium#6879]
Hi,

My Hub is reachable over public internet, while my Node is behind an internal network.

Node can reach Hub successfully, however Hub times out trying to register the Node using it's internal ip, which will of course will never work.

Is it possible to register a node which is not visible over public internet, without having to set up a VPN or NAT hole punching?

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
