### ISSUE TITLE
Remove org.openqa.selenium.internal.WrapsElement

### ISSUE THREAD

**Issue by joshlandin** [SeleniumHQ/selenium#6881]
It is not uncommon to unwrap an element in remote grid environments. For example, when `org.openqa.selenium.support.events.EventFiringWebDriver.EventFiringWebElement` wraps a `org.openqa.selenium.remote.RemoteWebElement` and the test needs to set a `org.openqa.selenium.remote.LocalFileDetector` on the `RemoteWebElement`.

Example:
```
public void fileInput(String cssSelector, String absolutePath)
{
   WebElement fileElement = this.driver().findElement(By.cssSelector(cssSelector));
   if (fileElement instanceof WrapsElement) {
     fileElement= ((WrapsElement)fileElement).getWrappedElement();
   }
  if (fileElement instanceof RemoteWebElement)
  {
    LocalFileDetector detector = new LocalFileDetector();
    File f = detector.getLocalFile(absolutePath);
    ((RemoteWebElement)fileElement).setFileDetector(detector);
    path = f.getAbsolutePath();
  }
  fileElement.sendKeys(path);
}
```
Starting with Selenium 3.141.59, this code breaks since the package name changed for `WrapsElement` from `org.openqa.selenium.internal` to `org.openqa.selenium`. The interface `org.openqa.selenium.internal.WrapsElement` was left in the code base, and thus, existing imports are happy.

Consider removing `org.openqa.selenium.internal.WrapsElement` to avoid confusion.

**Comment by shs96c** [comment]
It was marked as deprecated, so it's gone in 0fe993f485a16a9531afd6929ddd82e2ece656fd. Thanks for pointing it out!
