### ISSUE TITLE
Output stream in GeckoDriverService is never closed

### ISSUE THREAD

**Issue by benrebak** [SeleniumHQ/selenium#6883]
## 🐛 Bug Report

The file output stream provided to GeckoDriverService via its static builder class is never closed.

I am running some JUnit tests using Selenium, which will log the browser output to a log file in a folder foo/ . After running the tests, the contents of foo/ are zipped and copied to another folder, passed/ or failed/ , and the foo/ folder is force deleted.

This delete operation is unsuccessful because the log output stream held by the GeckoDriverService isn't closed.

## To Reproduce

Detailed steps to reproduce the behavior:

Create a FirefoxDriver as below:

`System.setProperty(BROWSER_LOGFILE, "/path/to/my/log/file.log");`
`return new FirefoxDriver(firefoxOptions);`

After running the test, and having the FirefoxDriver write output to the file given above,

`org.apache.commons.io.FileUtils.forceDelete(new File("/path/to/my/log/"));`

## Expected behavior

The directory "/path/to/my/log/" and all contents are deleted.

## Test script or set of commands reproducing this issue

See above.

## Environment

OS: Windows 10
Browser: Firefox
Browser version: 60.3
Browser Driver version: GeckoDriver 0.23
Language Bindings version: Java 3.13

**Comment by cgoldberg** [comment]
do you ever quit the driver before deleting the logs?

**Comment by benrebak** [comment]
@cgoldberg yes. These tests are managed using JUnit rules. The rule managing setup and teardown of the Selenium driver is definitely calling driver.quit before the rule which manages logs tries to delete the log folder.

**Comment by barancev** [comment]
OK, reproduced. Thank you for the bug report!
