### ISSUE TITLE
[internal build bug] gendocs.js doesn't work right if user has node_modules in parent directory

### ISSUE THREAD

**Issue by n-rook** [SeleniumHQ/selenium#6885]
Very minor issue, feel free to close if you don't care.

The script `javascript/node/gendocs.js` runs `npm install` in a specific place and expects the `node_modules` directory to get installed there.

However, the way `npm install` works, if there isn't a package.json in the place where it's run (or a node_modules directory), npm will [walk up the ancestry tree](https://docs.npmjs.com/files/folders#more-information) in the local filesystem, looking for a node_modules directory or package.json. If the user happens to have a node_modules in one of these places, that means the script gendocs.js will fail— it will install js-dossier somewhere strange, and won't be able to find it afterward.

I am not sure what the best fix is. Creating an artificial, empty node_modules directory would work, but doesn't seem "right".

**Comment by barancev** [comment]
As far as this utility is "internal" we can suppose it is used in a "proper" environment. May be it's worth to mention this issue in documentation, feel free to commit a PR if you think it's important.
