### ISSUE TITLE
Not able to click on button for file upload when using Safari 12 on mac OSX 10.12 or 10.13

### ISSUE THREAD

**Issue by parshudhole** [SeleniumHQ/selenium#6887]
When input type=file is specified for any control then Safari webdriver is not working with it.
Error thrown input type file is not supported ,please use sendKeys instead.
## To Reproduce

HTML  code for page:

Detailed steps to reproduce the behavior:
I am automating use case of file upload for Safari ,I need to only  click on Browse button of webpage using Selenium (file selection from file dialogue will be done  by apple script later)
Below are steps for the issue I am facing
Please refer the attached html code (SampleWebpage)  for controls and ids mentioned in steps.

1.If you provide id of selectedFile1 which   in selenium python script, then it throws error saying "Error thrown input type file is not supported ,please use sendKeys instead."
2.So I added next control (browsebutton1) in webpage which uses onclick action and click on previous control (selectedFile1).
In both the cases I am not able to click on button ,I tried xpath ,id .
This webpage automation works fine for Chromedriver using the same approch but failing for Safari.

Python script that I am using as below:

    __browser_name = BrowserName.SAFARI
    __browser_obj = BrowserOperation(__browser_name)
    __browser_obj.open_browser()
    url_list = [Url.STATIC_MULTIPLE_FILES_UPLOAD_URL_RS3]
    __tab_obj = __browser_obj.get_tab()
    __tab_obj.load_url(Url.STATIC_MULTIPLE_FILES_UPLOAD_URL_RS3)
    __element_obj = __tab_obj.get_element()
    id1="browsebutton1"
    xpath1='//input[@id="browsebutton1"]'
    __element_obj.click_on_element(id=id1)

## Environment

OS: mac OSX 10.12.6
Browser: Safari 12.0.2 ,12.0.3
Browser version: 12.0.2 ,12.0.3
Selenium version:3.4.3
Python :2.7
Selenium Grid version (if applicable):

**Comment by parshudhole** [comment]
Can someone provide any update on this ?Is this open issue with Safari driver ?Is there any workaround exists for this?

**Comment by jimevans** [comment]
The W3C WebDriver Specification does not allow clicking `<input type="file">` elements. It is expressly disallowed. You’ll see the same behavior for Firefox, Internet Explorer, and soon Chrome. If you want to upload files with such an element, you should use send_keys, with the full path to the file you wish to upload.

**Comment by parshudhole** [comment]
Even with using send_keys ,I am not able to click on this element ?Can you provide working code snippet or example if any.

**Comment by xiaoxiaofeixiang** [comment]
driver.findElement(By.name('login')).sendKeys(Key.ENTER)   try it

**Comment by burg** [comment]
You can't trigger the native file selection dialog via safaridriver. It is expressly not supported due to the glass pane. Instead, you need to use Element Send Keys targeted at the <input type=file> with the file path(s) separated by ','. The files need to be world-readable for safaridriver to attach them. Read more about the glass pane here: https://developer.apple.com/documentation/webkit/about_webdriver_for_safari?language=objc

**Comment by barancev** [comment]
The same is true for all browsers, W3C WebDriver specification explicitly says that Selenium should throw an exception on an attempt to click a file input, SafariDriver works as designed.
