### ISSUE TITLE
org.openqa.selenium.os.WindowsUtils is depricated, what is the alternative?

### ISSUE THREAD

**Issue by anasfahumy** [SeleniumHQ/selenium#6889]
## 💥 Regression Report

I am using org.openqa.selenium.os.WindowsUtils; for killing processes. 

WindowsUtils.killPID(app)
WindowsUtils.killByName()

**Comment by barancev** [comment]
What functions of WindowsUtils do you use?

**Comment by anasfahumy** [comment]
> What functions of WindowsUtils do you use?

WindowsUtils.killPID(app)
WindowsUtils.killByName()

**Comment by barancev** [comment]
Just copy the code you need to your own utility class:
https://github.com/SeleniumHQ/selenium/blob/f41fe5fb1a9bebaf4a29f1a51f00a6b281400fe9/java/client/src/org/openqa/selenium/os/WindowsUtils.java#L38-L69

**Comment by anasfahumy** [comment]
Thank you!!!
