### ISSUE TITLE
org.openqa.selenium.security.UserAndPassword not found on v3.141.59, is it deprecated?

### ISSUE THREAD

**Issue by anasfahumy** [SeleniumHQ/selenium#6890]
## 💥 Regression Report

I was using org.openqa.selenium.security.UserAndPassword in my project, After updating to Selenium v3.141.59 it is not found. Please help to correct my code.

**Comment by barancev** [comment]
This class was deliberately removed and will not get back to Selenium code unless this feature is specified in W3C WebDriver standard.
