### ISSUE TITLE
Cookie is Serializable, but ReturnedCookie isn't

### ISSUE THREAD

**Issue by Viserius** [SeleniumHQ/selenium#6893]
Currently, you are able to de-serialize cookies, because Cookie is serializable.
However, you arený able to actually serialize the cookies, as ReturnedCookie is returned, and ReturnedCookie is not serializable.

## To Reproduce
```
FileStream fs = new FileStream("Cookies.dat", FileMode.Create);
BinaryFormatter formatter = new BinaryFormatter();
formatter.Serialize(fs, driver.Manage().Cookies.AllCookies);
fs.close();
```

## Error
OpenQA.Selenium.Internal.ReturnedCookie in assembly WebDriver, Version=3.141.0.0, Culture=neutral, PublicKeyToken=null is not marked as Serializable.

**Comment by moh-hassan** [comment]
I get the same error in version 4.0.0-alpha07  
```
System.Runtime.Serialization.SerializationException: Type 'OpenQA.Selenium.Internal.ReturnedCookie' in Assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```
There is another issue, trying to serialize using Newtonsoft.Json then deserialize, I get an error in deserialization because Cookie class has no parameterless constructor.

```
System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'OpenQA.Selenium.Cookie'
```
