### ISSUE TITLE
Chrome headless file download using c# 

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/selenium#6895]
## 💬 Questions and Help
Hi All,

I required to download and validate a pdf file in chrome headless browser,
Tried with below code, But the pdf file is not downloaded when i click download button(confirmed in screenshot)

Code:
static async Task AllowHeadlessDownload(ChromeDriverService driverService, ChromeDriver driver)
        {
            var jsonContent = new JObject(
                new JProperty("cmd", "Page.setDownloadBehavior"),
                new JProperty("params",
                new JObject(new JObject(
                    new JProperty("behavior", "allow"),
                    new JProperty("downloadPath", @"D:\pdf")))));
            var content = new StringContent(jsonContent.ToString(), Encoding.UTF8, "application/json");
            var sessionIdProperty = typeof(ChromeDriver).GetProperty("SessionId");
            var sessionId = sessionIdProperty.GetValue(driver, null) as SessionId;

            using (var client = new HttpClient())
            {
                client.BaseAddress = driverService.ServiceUrl;
                var result = await client.PostAsync("session/" + sessionId.ToString() + "/chromium/send_command", content);
                var resultContent = await result.Content.ReadAsStringAsync();
            }
        }

public ChromeDriver ChromeHeadless()
        {
            var options = new ChromeOptions();
            options.AddArguments("headless");
            options.AddArguments("--window-size=1920,1080");
            options.AddArguments("test-type");
            options.AddArguments("disable-popup-blocking");
            options.AddArgument("disable-extensions");
            options.AddUserProfilePreference("plugins.plugins_disabled", new[] {
                "Chrome PDF Viewer" });
            options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);            
            driverService = ChromeDriverService.CreateDefaultService();
            ChromeDriver driver = new ChromeDriver(options);            
            Environment.SetEnvironmentVariable("BrowserName", driver.Capabilities.BrowserName);
            Environment.SetEnvironmentVariable("BrowserVersion", driver.Capabilities.Version);
            AllowHeadlessDownload(driverService, driver).GetAwaiter().GetResult();
            return driver;
}

But i'm getting error "System.Net.Http.HttpRequestException: 'An error occurred while sending the request.'SocketException: No connection could be made because the target machine actively refused it 177.0.0.1:5580'
at the line "var result = await client.PostAsync("session/" + sessionId.ToString() + "/chromium/send_command", content);"

Anyone faced same issue ?

Thanks,
Elango

**Comment by jimevans** [comment]
@Elangopalakrishnan Help me understand your use of an external HTTP client library, rather than using the built-in extension command mechanism of the .NET language bindings? There are examples of how to accomplish that in the [.NET bindings source code](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Chrome/ChromeDriver.cs#L147). In point of fact, there is already a [custom extension command](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Chrome/ChromeDriver.cs#L203) for executing Chrome Debugging Protocol commands in the .NET bindings. I'd update your `AllowHeadlessDownload` method to do something like the following:

    public void AllowHeadlessDownload(ChromeDriver driver)
    {
        // Note: Yes, you could use "var" to make this slightly less verbose.
        // This example purposefully doesn't so as to be as complete as possible.
        Dictionary<string, object> parameters = new Dictionary<string, object>();
        parameters["behavior"] = "allow";
        parameters["downloadPath"] = @"D:\pdf";
        driver.ExecuteChromeCommand("Page.setDownloadBehavior", parameters);
    }

Now, this may not work entirely, because `chromedriver.exe` may not fully understand the command as you've attempted to use it here, but that's not a problem with Selenium; rather it would be one with chromedriver, which is not maintained by the Selenium project.

**Comment by Elangopalakrishnan** [comment]
@jimevans thank you so much for reply! I tried above code by referring [https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDownloadBehavior](url) 

But it is not working, there no pdf are downloading when i click download button...

**Comment by jimevans** [comment]
So what's the issue? Is it that you're unable to execute the custom command (as your original issue report would indicate)? If so, my previous comment shows how to properly execute what you're attempting to. Is your issue that you don't get files downloaded? If so, that's not something that Selenium can do anything about.

If the command being sent to chromedriver to enable the download behavior is being malformed by the language bindings, that's something we can address. If the command is being sent and processed by chromedriver, but is not being honored by the driver when you click on a PDF link, there's precious little Selenium can do about that.

**Comment by Elangopalakrishnan** [comment]
Yeah, i'm unable to execute the command Page.setDownloadBehavior from my selenium with c# code.
But i saw in internet many ppl are done with python, ruby and java,.. 
Why not in c#, why c# doesn't have any **options.setExperimentalOption()**...
i could see many of selenium methods are not yet implemented in c# :(

How we will achieve this pdf downloads in c#....

**Comment by jbustillos** [comment]
+1 Any c# SetExperimentalOption alternative on the .NET library would be nice

**Comment by jimevans** [comment]
The method for .NET is `AddAdditionalCapability`, and it’s been part of the .NET bindings’ API since at least 2013. Just because the method does not share the same name, @Elangopalakrishnan, does not mean that the functionality does not exist. Moreover, I vehemently dispute the assertion that “many of selenium methods are not yet implemented in C#.” That is an extraordinary claim, and frankly, an offensive one, and it requires extraordinary evidence to back it up. Please provide that evidence or retract the claim.

**Comment by jbustillos** [comment]
Thanks for the pointer towards `AddAdditionalCapability`

**Comment by Elangopalakrishnan** [comment]
@jimevans apologies if i said wrong, i faced issues when i try to do tap actions on iOS using IAction. 
I will post the issues if i find in future and please refer this issue https://github.com/appium/appium/issues/8848 , I didn't mean that in any wrong way/negative.
anyway thanks for your time..

**Comment by barancev** [comment]
Should this issue be closed for now?

**Comment by ascendantofrain** [comment]
Here is how I handle automatic downloads in Headless Chrome, hopefully it'll help you.

    chromeHeadlessOptions.AddUserProfilePreference("download.default_directory", workingDirectory);
    chromeHeadlessOptions.AddUserProfilePreference("profile.default_content_setting_values.automatic_downloads", 1);

**Comment by diemol** [comment]
Closing as we didn't get any more replies.

**Comment by phenry9999** [comment]
I do have a question about this. This method seems to change the default file naming behavior. When a same file name is downloaded in Windows, a " (1)" is concatenated to the filename. This behavior is no longer occurring with the above change, the file is overwritten with the new incoming file which is undesirable. How can we get back the default browser behavior?
