### ISSUE TITLE
[SEVERE]driver.Chrome() fails to close chromedriver.exe upon using driver.quit() at the end C#

### ISSUE THREAD

**Issue by vitalisc** [SeleniumHQ/selenium#6896]
After calling driver.quit() at the end of a multithreaded program physical browser will close but the process   chromedriver.exe will still be running 
take a look here http://prntscr.com/mdtqtb

selenium c#

**Comment by cgoldberg** [comment]
please show some code to reproduce this.

**Comment by vitalisc** [comment]
private void threadWork(int i , int urlsPerThread , int diff = 0)
        {
            var myurl = "";
            int startIndex = i * urlsPerThread;
            for (int j = 0; j < urlsPerThread + diff; j++)
            {
                myurl = dataGridView1.Rows[startIndex + j].Cells[0].Value.ToString();
                IWebDriver driver = new ChromeDriver();
                driver.Navigate().GoToUrl(myurl);
                Thread.Sleep(3000);
                driver.Quit();
            }
        }

this is the c# code

**Comment by vitalisc** [comment]
the program loops datagrid table  in multithreaded way, but this is the main code that interacts with the  chromedriver despite having the quit there, it will just close the browser and leave the chromedriver running

**Comment by diemol** [comment]
@vitalisc  
Could you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided,
