### ISSUE TITLE
Raspberry pi 3 drive = webdriver.Firefox() exeption connection

### ISSUE THREAD

**Issue by hitokiri** [SeleniumHQ/selenium#6897]
The problem occurs when the object instance is made
```
from selenium import webdriver
browser = webdriver.Firefox()
```

in this part it displays a browser window and the following error appears

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/folder/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/folder/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/folder/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/folder/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/folder/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```

OS: 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch
Architecture:Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
Browser: Mozilla Firefox
Browser version: 52.9.0
Browser Driver version: geckodriver 0.19.1
Language Bindings version: Python 3.5.3  virtualenv: 16.1.0
Selenium Grid version (if applicable): selenium  3.141.0

**Comment by cooperfrench95** [comment]
You need to update firefox.

**Comment by hitokiri** [comment]
Now update, but I do not think that's the case, since in another device with a version 28 of firefox, it works well

**Comment by cgoldberg** [comment]
@hitokiri 

can you reproduce using new versions of selenium, geckodriver, and firefox?

**Comment by hitokiri** [comment]
@cgoldberg  
Hi, I already test with version 60 of firefox and with the new versions of both the gecko drive, and the newest selenium package and the same problem happens, when starting the object it gives the same error

**Comment by cgoldberg** [comment]
are you using an arm7 build of geckodriver?

**Comment by hitokiri** [comment]
@cgamache 
if as a matter of fact I have another device of that architecture that is not a raspberry with an older version of firefox a 28 with the drivers and new library and if it works, but in raspberry I get that problem.

**Comment by barancev** [comment]
@hitokiri First of all, can you run geckodriver on the device? Without Selenium, just try to start geckodriver executable and see if there are any errors.

**Comment by hitokiri** [comment]
@barancev  the errors start since obj = webdriver.Firefox ()

**Comment by barancev** [comment]
@hitokiri When you call webdriver.Firefox() it starts a new geckodriver process, that should start listening to a port, and attempts to connect to this process over the network. I suggest to check that the executable geckodriver can be started on the device. Don't run any python code, just attempt to start a new geckodriver process to make sure it can work on the device.

**Comment by diemol** [comment]
Closing as we didn't get any reply from the OP.
