### ISSUE TITLE
Click() on left handed mouse executing the wrong mouse button

### ISSUE THREAD

**Issue by AviFix** [SeleniumHQ/selenium#6898]
## 🐛 Bug Report

Hi
My mouse is configured for a left handed user (right and left click are reversed).

When using the click() option, it clicks on the wrong button.

Thanks

OS:  Windows 10
Browser: IE
Browser version: 11.523

**Comment by jimevans** [comment]
@AviFix You haven't said, but are you using the `requireWindowFocus` capability? As an experiment, what happens if you don't use it? I want to see if your experience matches up with what I'm seeing locally.

**Comment by barancev** [comment]
Fixed by commit f59211f5c30a4e5d7c1e3c8c2e84d21d9a339e19 according to the commit message.
