### ISSUE TITLE
[javascript] HttpClient: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Darth-koder007** [SeleniumHQ/selenium#6899]
## 🐛 Bug Report
To make a API request through httpClient without `headers` object in request object results in error `Cannot read property 'forEach' of undefined`

## To Reproduce

Import `httpClient` and  try making an api request with below kind of request object which should not have a headers object

```javascript
const localHttpClient = new HttpClient('http://localhost');
const postRequest = {
    method: 'POST',
    path: '/path/',
    data: {
        "Key": "value"
    }
};

localHttpClient.send(postRequest)
```

## Expected behavior

API request should have been executed without error `Cannot read property 'forEach' of undefined`

## Fix
Issue is fixed in this [pull request](https://github.com/SeleniumHQ/selenium/pull/6882)

**Comment by Darth-koder007** [comment]
@barancev Please have a look
Thanks

**Comment by barancev** [comment]
PR merged
