### ISSUE TITLE
Allow childprocess 1.0 dependency of ruby selenium-webdriver?

### ISSUE THREAD

**Issue by jrochkind** [SeleniumHQ/selenium#6907]
Ruby gem selenium-webdriver has a dependency on `'childprocess', ['~> 0.5']`

https://github.com/SeleniumHQ/selenium/blob/d7674b0c2ffff75787e94aef13e4ceab04252a86/rb/selenium-webdriver.gemspec#L33

The childprocess gem had a [1.0 release](https://rubygems.org/gems/childprocess/versions/1.0.0) a couple days ago. That is not allowed by the selenium-webdriver dependency specification. 

Should it be?

**Comment by twalpole** [comment]
Fixed via 6d7f6338c0c985403840c819652cb9cd1ebf22df

**Comment by jrochkind** [comment]
thanks!
