### ISSUE TITLE
Browser test fails because of cygwin internal path

### ISSUE THREAD

**Issue by Grandmagic13** [SeleniumHQ/selenium#6908]
## 🐛 Bug Report: Browser test fails because of cygwin internal path

When trying to run a browser test on firefox written in ruby (capybara, selenium webdriver), I get the following error:
```
Failures:

  1) logging in is possible
     Failure/Error: super(url)

     Selenium::WebDriver::Error::SessionNotCreatedError:
       Failed to start browser /firefox/firefox.exe: no such file or directory
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/marionette/driver.rb:50:in `initialize'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:31:in `new'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:24:in `browser'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/selenium/driver.rb:50:in `visit'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/session.rb:274:in `visit'
     # /home/bjanoska/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
```

The problem seems to be, that when selenium is trying to locate firefox.exe, it is using the cygwin relative path (/firefox/firefox.exe) instead of the absolute windows path (C:/cygwin64/firefox/firefox.exe). I'm assuming this would cause a problem with other browsers as well.  
Since the code will not run firefox inside of the cygwin platform itself, but on windows, it needs to get the windows absolute path to kick off the browser.

#### Proposed solution: 
https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/platform.rb line 124 in function `cygwin_path` `
```
`cygpath #{flags.join ' '} "#{path}"`.strip
```
be changed to 
```
`cygpath -d #{flags.join ' '} "#{path}"\`.strip
```

## To Reproduce

To reproduce, execute any browser test that is written in ruby and powered by selenium from the cygwin console. Test should fail with  
```
Selenium::WebDriver::Error::SessionNotCreatedError:
       Failed to start browser <browser cygwin path>: no such file or directory
```

Detailed steps to reproduce the behavior:

## Expected behavior

Expecting the browser to open when running a browser test.

## Test script or set of commands reproducing this issue

Sadly, I'm working with company code, so I can't paste examples

## Environment

OS: Windows 10
Browser: Mozilla Firefox
Browser version: 65.0 (64bit)
Browser Driver version:  GeckoDriver 0.24
Language Bindings version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-cygwin]
Selenium Grid version (if applicable): -

**Comment by twalpole** [comment]
I'm unclear what adding the `-d` switch to cygpath would do here, since the docs - https://cygwin.com/cygwin-ug-net/cygpath.html - state that just outputs DOS shortened names.

**Comment by Grandmagic13** [comment]
Maybe the -w switch is the clearest choice, haven't tried, as the browser launches with the -d option as suggested above. It may be because -d and -w may produce the similar output... Anyways, the point is that the natively running code, when trying to reach the webdriver, needs the path in native form instead of receiving a path like "/cygdrive/c/Users/myUser/webdrivers/geckodriver.exe", since it disables the code from executing the webdriver.

**Comment by twalpole** [comment]
I don't have access to a cygwin environment currently to check - could you please tell me what the output of running the 3 following commands in your environment are

    cygpath -d "/firefox/firefox.exe"

    cygpath -w "/firefox/firefox.exe"

    cygpath "/firefox/firefox.exe"

**Comment by twalpole** [comment]
Note: you can also just do

    Selenium::WebDriver::Firefox.path = "path to firefox"

in your code

**Comment by Grandmagic13** [comment]
That could have been a workaround but I don't have that option since the project is running on multiple platforms.

command outputs:
$ cygpath -d "/firefox/firefox.exe"
C:\cygwin64\firefox\firefox.exe

$ cygpath -w "/firefox/firefox.exe"
C:\cygwin64\firefox\firefox.exe

$ cygpath "/firefox/firefox.exe"
/firefox/firefox.exe

**Comment by twalpole** [comment]
Fixed via https://github.com/SeleniumHQ/selenium/commit/13c5bb00b66810a04beefa629c2b2d673c80aacc
