### ISSUE TITLE
Ruby gem `selenium-webdriver` 3.141.0 install fails on ruby 2.6.0

### ISSUE THREAD

**Issue by abhchand** [SeleniumHQ/selenium#6910]
## 🐛 Bug Report

Installing the ruby `selenium-webdriver` gem fails on ruby `2.6.0`

It throws an RDoc error, claiming that `lib/childprocess/tools/generator.rb` may not be properly documented. However, the core gem seems to install successfully. 

If I retry the same with `ruby 2.5.1` it is successful, so it may be a problem with `2.6.0` specifically

## To Reproduce

```
#  alternatively use rbenv or any other ruby management tool
$ rvm install 2.6.0  
.....


$ which ruby
/home/abhchand/.rvm/rubies/ruby-2.6.0/bin/ruby

$ gem install selenium-webdriver
Fetching rubyzip-1.2.2.gem
Fetching childprocess-0.9.0.gem
Fetching selenium-webdriver-3.141.0.gem
Fetching ffi-1.10.0.gem
Successfully installed rubyzip-1.2.2
Building native extensions. This could take a while...
Successfully installed ffi-1.10.0
Successfully installed childprocess-0.9.0
Successfully installed selenium-webdriver-3.141.0
Parsing documentation for rubyzip-1.2.2
Installing ri documentation for rubyzip-1.2.2
Parsing documentation for ffi-1.10.0
Installing ri documentation for ffi-1.10.0
Parsing documentation for childprocess-0.9.0
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /home/abhchand/.rvm/rubies/ruby-2.6.0/bin/ruby -c lib/childprocess/tools/generator.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

  (NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

## Expected behavior

Successful completion of `gem install selenium-webdriver`

## Test script or set of commands reproducing this issue

See above

## Environment

OS: Ubuntu 18.04 LTS
Browser: n/a
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: Ruby 3.141.0
Selenium Grid version (if applicable): n/a

**Comment by p0deje** [comment]
Just tried installing on a fresh machine and it worked fine. Looking at your error it seems that it fails when generates documentation for ChildProcess gem. I'd recommend trying to install with `--no-ri --no-rdoc` options and, if it still doesn't work, reporting the issue to ChildProcess bug tracker.

I'm going to close this issue for now as it looks like it's not related to Selenium, but will re-open if turns out it is.

**Comment by abhchand** [comment]
@p0deje - Appreciate you looking at it and trying to replicate! 

Will follow up with the `childprocess` gem if it continues to fail there.
