### ISSUE TITLE
InternetExplorerDriverService.LogFile doesn't wrap path with quotes to support paths with spaces

### ISSUE THREAD

**Issue by icnocop** [SeleniumHQ/selenium#6912]
## 🐛 Bug Report

If I pass the `InternetExplorerDriverService.LogFile` property a path containing spaces, the log file path is not passed to `IEDriverServer.exe` correctly.

## To Reproduce

Set the `LogFile` property of the `InternetExplorerDriverService` instance to a path with spaces.

## Expected behavior

I expected the log file to be created at the path I specified to the `LogFile` property.

## Actual behavior

The log file is created at the path before the first space.

## Test script or set of commands reproducing this issue
```
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var explorerOptions = new InternetExplorerOptions
            {
                EnsureCleanSession = true,
                IntroduceInstabilityByIgnoringProtectedModeSettings = true
            };

            var internetExplorerDriverService = InternetExplorerDriverService.CreateDefaultService();
            internetExplorerDriverService.HideCommandPromptWindow = false;
            internetExplorerDriverService.LoggingLevel = InternetExplorerDriverLogLevel.Trace;
            internetExplorerDriverService.LogFile = @"C:\My Path With Spaces\selenium.log";
            InternetExplorerDriver driver = new InternetExplorerDriver(internetExplorerDriverService, explorerOptions);

            driver.Url = "http://www.seleniumhq.org";
            driver.Navigate();
        }
    }
```

In this case, the log file is created at "C:\My"

## Environment

OS: Windows 10
Browser: IE
Browser version: 11.253.17763.0
Browser Driver version: 3.14.0.0
Language Bindings version: C# .NET 4.5

By quickly scanning the code, this issue also seems to happen with the Chrome and Opera driver services.

Thank you.

**Comment by jimevans** [comment]
Fixed in 64320c7
