### ISSUE TITLE
The basic project's tests fail from scratch: ./go clean test

### ISSUE THREAD

**Issue by CrispusDH** [SeleniumHQ/selenium#6915]
## 🐛 Bug Report

The basic project's tests fail from scratch.

## To Reproduce

Detailed steps to reproduce the behavior:
- fork `selenium` repo
- run `./go clean test`

## Actual behavior

Tests fail with [such trace](https://gist.github.com/CrispusDH/3cc7283ef3eddae3d08723aa75316f6f)

## Expected behavior

Tests pass

## Environment

OS: macOS Mojave v. 10.14.2

**Comment by CrispusDH** [comment]
I have installed `Java 8` and `python`. Also I have done `sudo pip install requests`. @barancev , could you help me to bring through these errors? :)

**Comment by p0deje** [comment]
Do you have `chromedriver` installed?

**Comment by CrispusDH** [comment]
I will make a PR for updating `CONTRIBUTION.md`

**Comment by barancev** [comment]
Information about dependencies was added to the README file, so I think the issue can be closed now.
