### ISSUE TITLE
Google drive issue with chrome

### ISSUE THREAD

**Issue by Mbachacou** [SeleniumHQ/selenium#6919]
## Environment
OS: Windows 10
Browser: Chrome
Browser version: 72.0.3626.96
Browser Driver version: ChromeDriver 2.46
Selenium Grid version (if applicable):  3.141.59

## Issue
Hello,

I test Google Drive with Selenium and Chrome.

Since the last update of Google drive, some elements not appears on main page : https://drive.google.com/drive/my-drive after login.

But manually, all elements are loaded and visible.

We've got a unknown or not managed html tag <c-wiz jsrender> that not appear with Selenium.

I have tested with Firefox and all is working fine.

So i think is a Chrome issue.

Could you look and keep us informed please ?

Thanks in advance.

Regards.

Maialen Bachacou from Maltem Insight Performance company.

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver
