### ISSUE TITLE
IsDisplayed returns false when element is present on page

### ISSUE THREAD

**Issue by jongrey** [SeleniumHQ/selenium#692]
Browser: Firefox 38.0.5
Webdriver version: 2.46.0 (.NET)

Summary: IsDisplayed method of webelement returns 'false' though element is present on page. Actually, there is a number of consecutive elements in table header for which validation on being displayed is made. First element returns true, while all other elements return false. HTML structure of controls is following:
[td id='some_id']
      [table]
              [tbody]
                      [tr]
                             [td]Text_to_search_on_page

Validation is made this way:
if (driver.FindElement(By.XPath("//*[contains(text(),'" + text + "')]")).Displayed)
{
         return true;
}

Following validation finds element with specified text but its "Displayed" attribute is set to "false" while "Enabled" attribute is set to true.

**Comment by ddavison** [comment]
in your case, could you tell us what your `text` variable equates to?  in any case, are you sure that you are returning the element you think you are?  it's possible that there are more than one elements being returned.

If that's not the case, then maybe you need to wait until it's displayed.  there could be javascript's that have an effect on it's displayability.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jongrey** [comment]
I'm sorry, guys. I've thoroughly debugged it and found out that there are multiple elements being returned indeed. My sincere apologies for taking your time. Issue can be closed.

**Comment by kjetester** [comment]
Almost same except I'm using correct selector:
`driver.findElements(By.xpath("//*[contains(text(), 'someText')]")).size() == 1` returns true
`driver.findElements(By.xpath("//*[contains(text(), 'someText')]")).isDisplayed()` returns false
Any ideas?
