### ISSUE TITLE
Query : Help needed building MSI using setuptools

### ISSUE THREAD

**Issue by pradeeps** [SeleniumHQ/selenium#6920]
## 💬 Questions and Help

I am trying to build an MSI from source, but noticed that the source does not have setup.py. Is there any way? 

OS : Windows 10
Python  : 3.6

Sorry, had to ask this question here as there is no slackshannel on herokuapp and there's no one in IRC node.

**Comment by cgoldberg** [comment]
look for it in the `/py` directory in the selenium repo.

https://github.com/SeleniumHQ/selenium/blob/master/py/setup.py
