### ISSUE TITLE
[Firefox] Selenium::WebDriver::Error::WebDriverError when trying to have an HTTP and HTTPS proxy

### ISSUE THREAD

**Issue by cwardata** [SeleniumHQ/selenium#6921]
## 🐛 Bug Report

I'm trying to have an HTTP and HTTPS proxy when running selenium with capybara. I looked at the various gist/SO answers and the documentation but I'm getting`Selenium::WebDriver::Error::WebDriverError` on the most probably to work code I have.

## To Reproduce

```
require 'selenium-webdriver'
require 'capybara/dsl'

Capybara.register_driver :selenium do |app|
  profile = Selenium::WebDriver::Firefox::Profile.new
  proxy = Selenium::WebDriver::Proxy.new(http: "localhost:8080", ssl: "localhost:8080")
  profile.proxy = proxy
  options = Selenium::WebDriver::Firefox::Options.new(profile: profile)
  Capybara::Selenium::Driver.new(app, browser: :firefox, options: options)
end

Capybara.current_driver = :selenium
```

## Expected behavior

Firefox should open and the HTTP and HTTPS requests should go through the proxy.

## Environment

OS: OSX
Browser: Firefox
Browser version: 65.0
Browser Driver version: geckodriver 0.23.0
Language Bindings version: Ruby 2.5.0 with Capybara

Thanks

**Comment by p0deje** [comment]
Can you provide more information? What exact error with full backtrace do you get? What do you use as a proxy server?

**Comment by cwardata** [comment]
Full backtrace:

```
Traceback (most recent call last):
	17: from scripts/firefox.rb:23:in `<main>'
	16: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	15: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/session.rb:277:in `visit'
	14: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/selenium/driver.rb:51:in `visit'
	13: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/navigation.rb:30:in `to'
	12: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in `get'
	11: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
	10: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
	 9: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	 8: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	 7: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	 6: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	 5: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	 4: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	 3: from handleEvent@chrome://marionette/content/listener.js:244:9
	 2: from handleReadyState@chrome://marionette/content/listener.js:271:21
	 1: from InsecureCertificateError@chrome://marionette/content/error.js:298:5
WebDriverError@chrome://marionette/content/error.js:179:5: Selenium::WebDriver::Error::WebDriverError
```

I'm using mitmproxy.

Minimal reproduction script:

```
require 'selenium-webdriver'
require 'capybara/dsl'

class C
  extend Capybara::DSL
end

Capybara.register_driver :selenium do |app|
  profile = Selenium::WebDriver::Firefox::Profile.new
  proxy = Selenium::WebDriver::Proxy.new(http: "localhost:8080", ssl: "localhost:8080")
  profile.proxy = proxy
  options = Selenium::WebDriver::Firefox::Options.new(profile: profile)
  Capybara::Selenium::Driver.new(app, browser: :firefox, options: options)
end

Capybara.current_driver = :selenium

C.visit("https://google.com")
```

**Comment by titusfortner** [comment]
Does it just work if you set the ssl port to 443 instead of 8080?

Also, the expected place for a proxy is [directly in the capabilities](https://w3c.github.io/webdriver/#capabilities).

Also, fwiw, the last time I tried to use the `Firefox::Profile` class I couldn't get it to work. I have a hacking session scheduled next weekend to collaborate on making sure all the capabilities code is the way we need it to be in preparation for Selenium 4.

**Comment by cwardata** [comment]
Thanks a lot @titusfortner, I think I'm almost there but getting a new error:

```
Traceback (most recent call last):
	17: from scripts/firefox.rb:25:in `<main>'
	16: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
	15: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/session.rb:277:in `visit'
	14: from */.rvm/gems/ruby-2.5.0/gems/capybara-3.13.2/lib/capybara/selenium/driver.rb:51:in `visit'
	13: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/navigation.rb:30:in `to'
	12: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:57:in `get'
	11: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
	10: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
	 9: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	 8: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	 7: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	 6: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	 5: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	 4: from */.rvm/gems/ruby-2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	 3: from handleEvent@chrome://marionette/content/listener.js:244:9
	 2: from handleReadyState@chrome://marionette/content/listener.js:271:21
	 1: from InsecureCertificateError@chrome://marionette/content/error.js:298:5
WebDriverError@chrome://marionette/content/error.js:179:5: Selenium::WebDriver::Error::WebDriverError
```

With:

```
require 'selenium-webdriver'
require 'capybara/dsl'

class C
  extend Capybara::DSL
end

Capybara.register_driver :selenium do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(
    proxy: Selenium::WebDriver::Proxy.new(
      http: "localhost:8080",
      ssl: "localhost:8080"
    )
  )

  Capybara::Selenium::Driver.new(
    app,
    browser: :firefox,
    desired_capabilities: capabilities
  )
end

Capybara.current_driver = :selenium

C.visit("https://perdu.com")
```

That error is quite cryptic even looking at the source code I'm not able to figure out why it's happening.

`https://amazon.com`, `http://amazon.com`, and `https://perdu.com` all raise an error (they all are or redirect to HTTPS). And `http://perdu.com` doesn't throw (doesn't redirect to HTTPS). 

I see the type is `pac` instead of `direct` for HTTP. Not sure if it matters.

**Comment by p0deje** [comment]
You configure Selenium correctly. The reason you cannot see HTTPS sites is because you don't have a certificate installed. Please follow [point 4 in documentation](https://docs.mitmproxy.org/stable/concepts-modes/#regular-proxy) to install certificate. 

I've checked it manually and was getting the same error as you. After I installed certificate, I could visit Amazon and Perdu without any problem.

**Comment by p0deje** [comment]
However, this issue shows that Ruby bindings lack proper error message for an insecure certificate. Instead of cryptic `Selenium::WebDriver::Error::WebDriverError` you should see proper `Selenium::WebDriver::Error::InsecureCertificateError`. I'll push a fix shortly.

**Comment by p0deje** [comment]
Since this is not an issue with Selenium, but misconfiguration, I'm going to close this. Thanks for the bug report!

**Comment by cwardata** [comment]
@p0deje I do have the correct root certificate installed. For instance using Chrome controller with the same proxy works and using Firefox uncontrolled on the same proxy works too (I added the certificate from mitm.it (autogenerated locally))

**Comment by p0deje** [comment]
Ok, then I cannot reproduce the issue. What I've tried was the following:

```ruby
require 'selenium-webdriver'

Selenium::WebDriver.logger.level = :debug

proxy = Selenium::WebDriver::Proxy.new(http: "localhost:8080", ssl: "localhost:8080")
capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(proxy: proxy)
driver = Selenium::WebDriver.for(:firefox, desired_capabilities: capabilities)
```

After that I was receive Insecure certificate error until I visited `mitm.it` and installed certificate. Then all secure sites worked perfectly fine. Can you try the same and see if it works?

Please note, the certificate only lives until the browser is closed, so every time you start a new proxy/driver - you need to regenerate certificate.

**Comment by titusfortner** [comment]
I haven't done much with proxies, so I'm not going to be able to reproduce your issue, but I know that Chrome & Firefox handle certificates differently

For Firefox you need to set "acceptInsecureCerts" to "true", so please make sure that has been done as well. (https://w3c.github.io/webdriver/#x7-capabilities)

**Comment by cwardata** [comment]
@p0deje Thanks for trying to reproduce and the `logger.level = :debug` tip. I reran it with with the debug logs, and I'm getting `insecure certificate` in the logs.

Anyway, I'm going the lazy route of just accepting insecure certificates, that's good enough in my use case.

Thanks to both of you for your help, it's very appreciated.

----------

> Please note, the certificate only lives until the browser is closed, so every time you start a new proxy/driver - you need to regenerate the certificate.

It's actually generated one time when mitmproxy is ran for the first time.

https://docs.mitmproxy.org/stable/concepts-certificates/#the-mitmproxy-certificate-authority

**Comment by p0deje** [comment]
👌

Is there anything else to do here? If not, would you close the issue.

**Comment by cwardata** [comment]
I don't mind closing but not sure why I'm getting insecure certificate when I have the root certificate installed

**Comment by cwardata** [comment]
Might be related: https://blog.mozilla.org/security/2019/02/14/why-does-mozilla-maintain-our-own-root-certificate-store/
