### ISSUE TITLE
after is not defined [ Javascript Library ]

### ISSUE THREAD

**Issue by vinigomescunha** [SeleniumHQ/selenium#6923]
## 🐛 Bug Report

after is not defined
node_modules/selenium-webdriver/testing/index.js:222:3

Apparently this syntax problem comes from an undefined variable or from an external library like mocha, I will explain how I did to reproduce

### Steps:
1 - npm install selenium-webdriver
2 - npm install selenium-standalone
3 - .selenium-standalone install && selenium-standalone start
4 - demo: [ save as index.js ] `

    const {By, Key, until} = require('selenium-webdriver');
     const {suite} = require('selenium-webdriver/testing');
     suite(function(env) {
       describe('Google Search', function() {
         let driver;
         before(async function() {
           driver = await env.builder().build();
         });

         after(() => driver.quit());

         it('demo', async function() {
           await driver.get('http://www.google.com/ncr');

           let q = await driver.findElement(By.name('q'));
           await q.sendKeys('webdriver', Key.RETURN);
           await driver.wait(
               until.titleIs('webdriver - Google Search'), 1000);
         });
       });
     });`
5 - SELENIUM_REMOTE_URL='http://localhost:4444/wd/hub' SELENIUM_BROWSER=chrome node index.js

## Environment

OS: Linux
Browser: Chrome
Browser version: 71.0.3578.98 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 2.43
Language Bindings version: Nodejs v8.11.3
Selenium Grid version (if applicable): 3.141.0

**Comment by onpbxtester** [comment]
try to run with mocha
5 - SELENIUM_REMOTE_URL='http://localhost:4444/wd/hub' SELENIUM_BROWSER=chrome mocha index.js

**Comment by vinigomescunha** [comment]
Yes, with the mocha the test works, in this case the mocha ends up being a direct dependence
The documentation does not say that when we use the library 'selenium-webdriver / testing' the mocha is needed for initialization of independent tests.

**Comment by Jeffhabs** [comment]
Yes it does, at the very top of the [page](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/testing/index.html). 
> Provides extensions for Jasmine and Mocha.

**Comment by vinigomescunha** [comment]
Yes, but the mocha is already in the package.json

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/package.json#L34

And from what I understood, before the mocha was treated by a wrapper

https://github.com/SeleniumHQ/selenium/commit/294d434c200040afe219f40cb6310ac9871c2b79#diff-5d879943fc13628123401a08c7af676e

I am in doubt if the error of syntax and even of the mocha or of a code that should have been removed previously.
