### ISSUE TITLE
desired capabilities is ignored

### ISSUE THREAD

**Issue by lilredindy** [SeleniumHQ/selenium#693]
Description
===========
without using the selenium grid, only standalone server running on osx, i set the desired capabilities object with the platform key set to 'windows'.  when i run the test it runs the test on mac, ignoring the platform set to windows...apparently this is expected behavior, ie, desired capabilties != actual capabilities

Steps to reproduce
==================
                capabilities = {"platform": "WINDOWS",
                                      "browserName": "firefox",
                                      "version": ""}

		self.driver = webdriver.Remote( 
   				command_executor='http://127.0.0.1:4444/wd/hub', 
   				desired_capabilities= capabilities )

Expected
========
exception

Actual
======
test is run on osx

**Comment by jleyba** [comment]
This is working as expected. The server will always start a browser, even if it can't give you what you want (e.g. will start firefox on osx when you asked for firefox on windows).

**Comment by lilredindy** [comment]
Can u explain why it's the right behavior?

**Comment by AutomatedTester** [comment]
This is a quirk in the way WebDriver was created. It's "desired" capabilities so we try give you what you desire. 




We will be fixing in future versions. I have specced it out already. https://w3c.github.io/webdriver/webdriver-spec.html#capabilities




—

**Comment by lilredindy** [comment]
I get it...u can't always get want u want, but this isn't art it's technology

**Comment by lukeis** [comment]
in the Java client bindings required capabilities has been implemented. Python bindings need to implement them.

**Comment by jleyba** [comment]
A more accurate representation of the current state of affairs is the FirefoxDriver server checks required capabilities sent on a new session request. The `browser` and `platform` capabilities are not actually checked though.

**Comment by lilredindy** [comment]
well that's not so good.  maybe you can fix it so it adheres to the contract
