### ISSUE TITLE
org.openqa.selenium.ElementNotInteractableException: element not interactable with Sendkeys

### ISSUE THREAD

**Issue by snovshadyan** [SeleniumHQ/selenium#6931]
## 🐛 Bug Report

In both Firefox and Chrome, I'm getting "org.openqa.selenium.ElementNotInteractableException: element not interactable" error when trying to send text to input field with Sendkeys. Clicking on the same element works fine.

<input type="text" name="post_title" size="30" value="" id="title" spellcheck="true" autocomplete="off">

Below is the fragment of the java selenium code:

.
.
.
    @FindBy(xpath="//*[@id=\"title-prompt-text\"]")
    WebElement NewPostTitle;

    @FindBy(xpath="//*[@id=\"content\"]")
    WebElement NewPostContent;

    public PostsPage(){
        PageFactory.initElements(driver, this);
    }
.
.
.
.

     public boolean verifyNewPost() throws Exception{

        AddNewBtn.click();
        WFEC(By.xpath("//*[@id=\"title-prompt-text\"]"));
        NewPostTitle.click();
        NewPostTitle.sendKeys("TestTitle"); <---------- this fails
        NewPostContent.click();
        NewPostContent.sendKeys("Test Content");
        PublisgBtn.click();
        AllPostsTab.click();
        WFEV(By.xpath("//a[contains(text(),'TestTitle"));
        return NewPostField.isDisplayed();
    }

.
.
.
    public  void WFEC(By by) throws Exception {

        sleep(100);
        HEY(driver.findElement(by)); <- this just highlighting the element
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(ExpectedConditions.elementToBeClickable(by));
    }

## Environment

OS: <!-- Windows 10
Browser: Chrome & Firefox
Browser version: Version 71.0.3578.98
Browser Driver version: ChromeDriver 73.0.3683.20
Language Bindings version: 
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by diemol** [comment]
Closing as we didn't get an answer from the OP.
