### ISSUE TITLE
https://seleniumhq.herokuapp.com lapsed, was this intentional? claimed by me temporarily

### ISSUE THREAD

**Issue by symonk** [SeleniumHQ/selenium#6934]
Hi, I Pinged @shs96c on Linked in about this previously,  I was trying to chat about a few things on the slack channel for Selenium and quite a few online links directed me to:

`https://seleniumhq.herokuapp.com` 

which the subdomain has lapsed.  Was this an intentional change for the selenium group?

I have claimed the heroku subdomain just to avoid a malicious actor from taking it until I find out if you don't really care about it anymore, or it was a genuine mistake.  Happy to return it for the latter of course!

Thanks

**Comment by p0deje** [comment]
@symonk Thank you!

@titusfortner IIRC you were the one who made this domain up. Do we still need it?

**Comment by symonk** [comment]
heading away for a few days now, so I will await a response here.  Apologies if I am slow to reply until Sunday

**Comment by lmtierney** [comment]
This herokuapp is no longer needed as we have a [direct sign-up link](https://goo.gl/9o4J3Y). We're hoping to move it to the seleniumhq.org domain soon. It would be nice to setup a simple redirect on that herokuapp subdomain though since there are so many places pointing toward it.

**Comment by symonk** [comment]
transfer pending to @shs96c, awaiting his response.  Sorry for the delay

**Comment by shs96c** [comment]
Thank you @symonk! I've now got the keys. It's very much appreciated that you looked after the project so thoughtfully. You're a star!

Closing this now, since the rest is down to us.
