### ISSUE TITLE
Combine several Selenium Grids

### ISSUE THREAD

**Issue by mahula** [SeleniumHQ/selenium#6936]
## 💬 Combine or integrate several Selenium Grids

Is it possible to integrate a Selenium Grid into another one.
E.g. trying to extend an existing grid by a second one, is it possible to call the second grid's hub node like a node in the first grid?

**Comment by xMutaGenx** [comment]
Not sure why you'd need this, but afaik there's no grid to grid communication, you'd simply put a load balancer in front of the multiple grids, or wait for Grid v4 :)

**Comment by rookieInTraining** [comment]
@mahula - You can probably go for Grid Routers till the time Grid v4 is available.

**Comment by diemol** [comment]
With Grid 4 new design, this should not be needed. Please have a look to the WIP docs https://www.selenium.dev/documentation/en/grid/grid_4/ and if you have any more questions about your use case, please feel free to drop by our Slack/IRC channels, see the link for the channels [here](https://www.selenium.dev/support/).
