### ISSUE TITLE
Reverse order of table columns

### ISSUE THREAD

**Issue by amado-saladino** [SeleniumHQ/selenium#6942]
## 🐛 Bug Report

Open this demo web site: https://demo.nopcommerce.com

Given: Product 1 = "Apple MacBook Pro 13-inch"
And : Product 2 = "Asus N551JK-XO076H Laptop"
When : I search for product 1 and product 2 and add them to compare page respectively
And : Go to <Comparison Page>
Then : I should see this image
![image](https://user-images.githubusercontent.com/20227574/52902302-96f84380-3217-11e9-8235-40e525a36d9e.png)

comparison functionality works fine, now I need to capture both Product 1 and Product 2 titles inside the table, I decided to work with Css selector where
Product 1 css selector "tr:nth-of-type(3) > td:nth-child(2) > a"
Product 2 css selector "tr:nth-of-type(3) > td:nth-child(3) > a"

Both selectors work fine in Chrome console, but when I use page init with Selenium as below:
```
@FindBy(css = "tr:nth-of-type(3) > td:nth-child(2) > a")
    WebElement FirstProductText

    @FindBy(css = "tr:nth-of-type(3) > td:nth-child(3) > a")
    WebElement SecondProductText
```
## To Reproduce

In Groovy script I printed the text of each element using:
```
println( FirstProductText.getText() )
println (SecondProductText.getText() )
```
## Expected behavior

I should see the results as:
> Apple MacBook Pro 13-inch
> Asus N551JK-XO076H Laptop

## But
I see these value in reverse  order:
> Asus N551JK-XO076H Laptop
> Apple MacBook Pro 13-inch

## Environment

OS: Windsows 8.1
Browser: Chrome
Browser version: 73
Browser Driver version: 2.46

**Comment by p0deje** [comment]
This is a question rather than an issue. Please send questions to the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.
