### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by ealashwali** [SeleniumHQ/selenium#6945]
## Environment

OS: Ubunut 18.04
Browser: Firefox Developer 66.0b8 (64-bit)
Browser version:  Firefox Developer 66.0b8 (64-bit)
Browser Driver version: geckodriver-v0.24.0-linux64
Language Bindings version: Python 3.6.7
Selenium Grid version (if applicable): not sure what you mean. But I installed it using:
python3 -m pip install -U selenium

The Firefox Developer edition is installed in this path:
/home/e/Documents/ff_extension/firefox
(where firefox.exe is inside the directory firefox).

I am sorry for the duplicate post but tried several solution none have worked. I am trying to run Selenium using python 3. I want it to work with Firefox Developer 66.0b8 (64-bit). When I run this simple example which I found in a previous post for similar problem:
```
capabilities = webdriver.DesiredCapabilities().FIREFOX
capabilities["marionette"] = False
binary = FirefoxBinary('/home/e/Documents/ff_extension/firefox') 
fp = webdriver.FirefoxProfile()
driver = webdriver.Firefox(firefox_binary=binary,  firefox_profile=fp,capabilities=capabilities)
```

I get the error:
`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

Can you please suggest any solution to me? I have a stable Firefox (non Developer) installed, but I want to use the Developer edition for testing purposes.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
