### ISSUE TITLE
Could not convert 'text' to string on Firefox

### ISSUE THREAD

**Issue by dparne** [SeleniumHQ/selenium#6947]
## 🐛 Bug Report

I started getting the error `Could not convert 'text' to string` on Firefox. I know there is an old issue about this but I have updated version of the selenium web driver and I am still getting this error (just from today).

## To Reproduce

Use a script `ElementFinder.sendKeys("somevalue")` and execute it on browser stack in firefox

## Expected behavior

Script should work

## Test script or set of commands reproducing this issue

`ElementFinder.sendKeys()`

## Environment

Platform	 Windows 10
Browser	 Firefox 65.0
Browserstack

## Observations

When I changed the following piece of code on `lib/webdriver.js`

```javascript
    if (!this.driver_.fileDetector_) {
      return this.schedule_(
          new command.Command(command.Name.SEND_KEYS_TO_ELEMENT).
              setParameter('text', keys.then(keys => keys.join(''))).
              setParameter('value', keys),
          'WebElement.sendKeys()');
    }
```

to

```javascript
    if (!this.driver_.fileDetector_) {
      return this.schedule_(
          new command.Command(command.Name.SEND_KEYS_TO_ELEMENT).
              setParameter('text', keys.then(keys => keys.join(''))).
              setParameter('value', keys.then(keys => keys.join(''))),
          'WebElement.sendKeys()');
    }
```
made it work

**Comment by barancev** [comment]
What part of the puzzle throws the exception? The driver (geckodriver)? What version of the driver is in use?

**Comment by barancev** [comment]
And by the way I can't understand how changing value of the `value` key affects the `text` key that causes the issue. Can you explain how does it fix the issue?

**Comment by dparne** [comment]
It was really bizarre. I could not understand how it worked when I changed `value`. Today it seems to work without that change as well. Sorry. I am gonna close this issue
