### ISSUE TITLE
Safari 12.1 driver.findElement/WebDriverWait throws java.lang.nullpointerexception null 

### ISSUE THREAD

**Issue by riticar** [SeleniumHQ/selenium#6951]
## 🐛 Bug Report

I am trying to run a java-maven selenium test on Mac OS High Sierra with Safari browser 12.2 version. The browser gets launched and the url is loaded but the test fails with java.lang.nullpointerexception null at driver.findElement(By.className("Locator")

I have set the java path in my profile using the information from http://www.sajeconsultants.com/how-to-set-java_home-on-mac-os-x/
I have also enabled Allow Remote Automation in the safari browser. I tried using various versions of selenium-java 3.14.0 / 3.141.59 through maven pom.xml I have updated the safari browser to 12.2 version. Also tried running the test on Safari Technology Preview 75 browser

This is only stack trace I am getting:

java.lang.NullPointerException: null
at SafariTest.LoginUser(SafariTest.java:41)
at SafariTest.test(SafariTest.java:150)
-->

## Expected behavior

No java.lang.NullPointerException to be encountered 

## Test script or set of commands reproducing this issue

WebDriver driver = new SafariDriver();
//Browser is maximized
driver.manage().window().maximize();
//Browser navigates to the url
driver.navigate().to(url);
driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
WebElement e = driver.findElement(By.className("Locator");

## Environment

OS: Mac os high sierra
Browser: Safari
Browser version: 12.2
Browser: Safari Technology Preview
Browser version: 75
Browser Driver version: Inbuilt safaridriver
Language Bindings version: selenium-java 3.141.59

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
