### ISSUE TITLE
Target dropdown in Chrome Extension

### ISSUE THREAD

**Issue by nzhome** [SeleniumHQ/selenium#6952]
Target dropdown in Chrome Extension always goes downwards, and always gets cropped, and you can't click xpath:position

Potential solutions?
a) How to make the dropdown always go upwards instead?
b) How to make the default target always be xpath:position instead of id?   

reason: my pages always change id every time you reload the page.

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #578](https://github.com/SeleniumHQ/selenium-ide/issues/578) via [**ZenHub**](https://www.zenhub.com/)
