### ISSUE TITLE
How can I run the testng.xml file with multiple external jars on Ubuntu terminal?

### ISSUE THREAD

**Issue by marufsayyed** [SeleniumHQ/selenium#6953]
## 🐛 Bug Report

>
 I want to run the kol.xml file with external jar  but I don't know the exact command to run the XML file with external jar 
NOTE- this jar file are required to take the screenshot of the webpage  and I have added all jars including external jar  in the libs folder
External jar files -commons-io-2.5.jar, commons-io-2.6.jar, commons-io-2.6-javadoc.jar, commons-io-2.6-sources.jar, and commons-io-2.6-tests.jar
## Expected behavior
kol.xml should run with external jars on ubuntu terminal

## Test script or set of commands reproducing this issue

[java -cp /home/dev2/eclipse-workspace/cmdd/bin:/home/dev2/eclipse-workspace/cmdd/libs/* org.testng.TestNG kol.xml]
please suggest how can i add external jars to this command 

## Environment

OS: <Ubuntu -->
Browser: 
Browser version: 
Browser Driver version:  
Selenium Grid version (if applicable): <e.g.: 3.141.59 -->

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
