### ISSUE TITLE
Chrome session goes stale after opening a link in a new tab/window

### ISSUE THREAD

**Issue by miksch123** [SeleniumHQ/selenium#6958]
Description: Chrome session goes stale after opening a link in a new tab/window. Chrome browser tries to navigate to URL, but makes automation go stale in the process. No html content gets loaded. It looks like chrome is initializing the navigation, but then stopping to perform the navigation.

Development language: C#
OS: Windows 10 1809
Browser: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
Versions:
Selenium: 3.141.0
selenium.support: 3.141.0
selenium.chrome.webdriver: 2.45.0
Nunit: 3.12.0
Specflow: 2.4.1
Specflow.Nunit: 2.4.1

Steps performed:
- navigate to chip.de
- click on the facebook link (new tab with facebook link opens)
- switch to new tab

Expected behavior: Tab navigates to URL. Web Content gets displayed.

Actual behavior: Tab tries to initialize navigation but fails without any error causing test automation to go stale.

Code snippet: 
public static  ChromeOptions options(string lang)
{
 ChromeOptions option = new ChromeOptions();
 option.AddArgument("--start-maximised");
 option.AddArguments("-lang=" + lang);
 return option;
}
driver = new ChromeDriver(options("en-us"));

driver.Navigate().GoToUrl("https://www.chip.de/");

 public static void ClickElementJS()
{
 IJavaScriptExecutor exe = (IJavaScriptExecutor)driver;
 exe.ExecuteScript("arguments[0].click();", driver.FindElement(By.ClassName("Social__Link Social__Link--Facebook")));
}
ClickElementJS();

public static bool SwitchWindow(string baseWindow)
        {
            var availableWindows = new List<string>(driver.WindowHandles);

            foreach (string w in availableWindows)
            {
                driver.SwitchTo().Window(w);
                
                if (w != baseWindow)
                    return true;
            }
            return false;
        }

SwitchWindow(baseWindow);

public static bool WaitUntilElementIsVisible(int time, string element)
        {
            try
            {
                new WebDriverWait(driver, TimeSpan.FromSeconds(time))
                    .Until<IWebElement>(d => d.FindElement(By.TagName(element)));
                visible = true;
            }
            catch (Exception)
            {
                visible = false;
            }

            return visible;
        }

 bool divvisible = WaitUntilElementIsVisible(5, "div");
            if (divvisible is false)
            {
                DriverCommands.Driver.Navigate().Refresh();
            }

new WebDriverWait(driver, TimeSpan.FromSeconds(10))
                .Until<bool>(d => d.Url.ToString().Contains("https://www.facebook.com/CHIP"));

Comments: this issue is not happening when I am running it in debug mode.

**Comment by GAMAOLI** [comment]
Estou na mesma, aparentemente portas permitidas não funcionam no Google Chrome mais recente 72.0.3626.109.
Este bug já foi encontrado no ramo Canary: https://bugs.chromium.org/p/chromium/issues/detail?id=916025

A solução temporária é desativar a opção "Ativar serviço de rede" nas configurações chrome: // flags

**Comment by miksch123** [comment]
Thank you for your answer. I have tried it with disabled network service flag. Unfortunately, it does not help or change anything.

**Comment by lewisob** [comment]
Also experiencing this.

**Comment by maxwell** [comment]
I've found at least in the Ruby Driver (via Capybara), if I sleep for a moment before trying to switch into the opened frame, that allowed the window to load.  

Perhaps if you try to interact with a window that was just opened without letting it start to load, it somehow makes the window go stale?

**Comment by lewisob** [comment]
Yes adding sleeps also helped me but not ideal.
I just found a solution [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2660&q=switchTo().window&colspec=ID%20Status%20Pri%20Owner%20Summary)
Use `--disable-site-isolation-trials` Chrome switch.

**Comment by miksch123** [comment]
> I've found at least in the Ruby Driver (via Capybara), if I sleep for a moment before trying to switch into the opened frame, that allowed the window to load.
> Perhaps if you try to interact with a window that was just opened without letting it start to load, it somehow makes the window go stale?

Thank you Maxwell. Your suggestion turned out to be right. The thing is, with chrome you need to sleep for at least 5 seconds to make the test work. Anything under it seems to still make it go stale, but sleeping 5 + seconds seems to help. Thank you very much.

**Comment by miksch123** [comment]
Read message above ^

**Comment by maxwell** [comment]
I've found @lewisob 's suggestion worked for me, and let me remove the sleep from my code!

**Comment by twalpole** [comment]
Note: This is a known issue with chrome/chromedriver - https://bugs.chromium.org/p/chromedriver/issues/detail?id=2650&q=load&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary - basically any attempt to access information on or about a page in a popup window before that page reaches a certain state will stop the loading that would normally occur.  The problem is there is no way to know when the page reaches that state without asking for info on or about it, which stops the loading.
