### ISSUE TITLE
Selenium Standalone Server with Credentials

### ISSUE THREAD

**Issue by Gentlehag** [SeleniumHQ/selenium#696]
Is there a way to setup the selenium standaloine serer with credentials ? 
I 've to offer it on a aserver and want to make sure that no one unauthorized is using it.

**Comment by ddavison** [comment]
SauceLabs implements something like this.  They use standard HTTP auth to hide their hub.

    http://user:secrettoken@somegrid.url:4444/wd/hub

That being said - it *is* possible.  I personally haven't done it, but my gut tells me that you can just wrap port 4444 with apache, nginx or any web server that allows restrictions like you ask.

I am, however going to close this issue as it's not a technical issue with Selenium, more of a question.  Questions should be asked in the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by gouchaoer** [comment]
that is what i need
