### ISSUE TITLE
Selenium Grid UI does not load JS and CSS files 

### ISSUE THREAD

**Issue by harloveleenKaur** [SeleniumHQ/selenium#6961]
Hi,

We have been using Selenium Grid in a docker container behind a HAPROXY , due to which the selenium has incorrect display or it is not able to load the css and js files - 
![image](https://user-images.githubusercontent.com/20640613/53220429-7eaa7d80-368a-11e9-8ae6-36c900f63e9b.png)

In the HAProxy we are enabiling the following directive:

-------------------------------------------------------------------------------------

http-response set-header X-Content-Type-Options nosniff

-------------------------------------------------------------------------------------

which triggers Strict Content-Type checking in Web Browsers, the web browser refuses to load the resources as css while the web server tells that it is text/plain. 

Hence, Could you please add the proper content type to these files as this is blocking us. -
- **consoleservlet.css**
- **consoleservlet.js**

Thank you.

**Comment by pankajsethi93** [comment]
I am facing this same issue too.
Any help would be appreciable :)

**Comment by diemol** [comment]
@harloveleenKaur 
Can you please provide more information on how to reproduce this? A script that starts HAProxy and the Grid, otherwise we need to start assuming things (basically because the issue template was deleted).

**Comment by harloveleenKaur** [comment]
Okay 
We are trying to start Selenium on Docker behind a proxy : 
This is what is the desired result: 
![image](https://user-images.githubusercontent.com/20640613/53487678-33410680-3ab2-11e9-907c-feb8bb91d6eb.png)

However, the actual output is this : 
<img width="328" alt="capture" src="https://user-images.githubusercontent.com/20640613/53487591-f70da600-3ab1-11e9-8a7d-1faf21a593cd.PNG">


That means that the javascript file and the CSS file which are responsible for the correct display are missing/ or not downloaded.
When we had a look further the error was : 
We had to enable this header  :- X-Content-Type-Options nosniff  
in the HAProxy 


How to reproduce this : 
- Start an haproxy with enabling the header mentioned above 
- then start the docker container for selenium behind this haproxy ( we use a web portal) https://github.com/SeleniumHQ/docker-selenium/tree/master/Hub

I am not sure if it is easy for you to reproduce, but it might be easier to add the correct Content-Type for the above mentioned files ( It should not produce a new error although) 

THanks

**Comment by diemol** [comment]
Could you please provide the explicit instructions to do this?
>    * Start an haproxy with enabling the header mentioned above
>    * then start the docker container for selenium behind this haproxy ( we use a web portal) https://github.com/SeleniumHQ/docker-selenium/tree/master/Hub

**Comment by virenv** [comment]
@harloveleenKaur: This issue should be agnostic of dockers and HAProxy. You can get it on any Client (Browser) which has CORB implemented and any proxy which sets the X-Content-Type-Options: nosniff header

@diemol In the grid code, taking the example of ConsoleServlet, I can see that we are intentionally setting wrong mime type here: [Code File](https://github.com/SeleniumHQ/selenium/blob/a61cc22fd053ea827cf39aa4065ae4912bb6af2a/java/server/src/org/openqa/grid/web/servlet/console/ConsoleServlet.java) Line 88
If this is not intentional it can introduce this problem. As for the browser it have the liberty to block the script because of mismatching Content-Type. More can be read here: [CORB](https://www.chromium.org/developers/design-documents/blocking-cross-site-documents)
If this is a bug, can I attempt to fix it?

**Comment by dylanlive** [comment]
Indeed.

## Environment
macOS High Sierra
Chome Version 72.0.3626.119

## Replication steps:
1) `java -jar selenium-server-standalone-3.141.59.jar -role hub`
2) Open Chrome with Devtools Console Open
3) Navigate to http://localhost:4444/grid/console
>Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:4444/grid/resources/org/openqa/grid/images/consoleservlet.css".

## Investigation

I took a look into this a few days ago to see if I could fix it, but started to venture deeper into the codebase that I wasn't too familiar with.

While we specify `type='text/css'` here https://github.com/SeleniumHQ/selenium/blob/7fdf318b4094af637cb17d0f39ad0755b8f5cd83/java/server/src/org/openqa/grid/web/servlet/console/ConsoleServlet.java#L97

The server serves the .css file as `text/plain`.

I found references in the codebase of a StaticResourceHandler which does MimeChecking. I noticed the resource path does not match the css/js/images that the consoleservlet returns
https://github.com/SeleniumHQ/selenium/blob/7fdf318b4094af637cb17d0f39ad0755b8f5cd83/java/server/src/org/openqa/selenium/remote/server/StaticResourceHandler.java#L43

Whereas the css is returned on `/grid/resources/org/openqa/grid/images/consoleservlet.css`

Overall, I don't really know the intent of this StaticResourceHandler and if at one point it was meant to handle these assets, so I called it a night and paused investigating.

**Comment by virenv** [comment]
@dylanlive: I think StaticResourceHandler is not used at this moment. Though this class is created to handle resources, as far as I could tell.
The fix to this issue should be done in ResourceServlet.java. There we are serving resource handling requests. All js and css files reach there. I created a small fix to test this out and the fix works. I am not sure what is the overall plan for this ResourceServlet.java. But at this moment the fix in this file works.

You can take a look at the fix in this [PR](https://github.com/virenv/selenium/pull/1/files#diff-3bcd393cf7f69ce3d3577d91ad812c9a). Please ignore the unnecessarily log files included by mistake.

**Comment by virenv** [comment]
PR that fixes this issue #6980

**Comment by harloveleenKaur** [comment]
@diemol  I agree with @virenv  and @dylanlive  
Please see the replication steps below - 

> Indeed.
> 
> ## Environment
> macOS High Sierra
> Chome Version 72.0.3626.119
> 
> ## Replication steps:
> 1. `java -jar selenium-server-standalone-3.141.59.jar -role hub`
> 2. Open Chrome with Devtools Console Open
> 3. Navigate to http://localhost:4444/grid/console
> 
> > Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:4444/grid/resources/org/openqa/grid/images/consoleservlet.css".
> 
> ## Investigation
> I took a look into this a few days ago to see if I could fix it, but started to venture deeper into the codebase that I wasn't too familiar with.
> 
> While we specify `type='text/css'` here
> 
> [selenium/java/server/src/org/openqa/grid/web/servlet/console/ConsoleServlet.java](https://github.com/SeleniumHQ/selenium/blob/7fdf318b4094af637cb17d0f39ad0755b8f5cd83/java/server/src/org/openqa/grid/web/servlet/console/ConsoleServlet.java#L97)
> 
> Line 97 in [7fdf318](/SeleniumHQ/selenium/commit/7fdf318b4094af637cb17d0f39ad0755b8f5cd83)
> 
>  .append("<link href='/grid/resources/org/openqa/grid/images/consoleservlet.css' rel='stylesheet' type='text/css' />"); 
> The server serves the .css file as `text/plain`.
> 
> I found references in the codebase of a StaticResourceHandler which does MimeChecking. I noticed the resource path does not match the css/js/images that the consoleservlet returns
> [selenium/java/server/src/org/openqa/selenium/remote/server/StaticResourceHandler.java](https://github.com/SeleniumHQ/selenium/blob/7fdf318b4094af637cb17d0f39ad0755b8f5cd83/java/server/src/org/openqa/selenium/remote/server/StaticResourceHandler.java#L43)
> 
> Line 43 in [7fdf318](/SeleniumHQ/selenium/commit/7fdf318b4094af637cb17d0f39ad0755b8f5cd83)
> 
>  private static final String STATIC_RESOURCE_BASE_PATH = "/static/resource/"; 
> Whereas the css is returned on `/grid/resources/org/openqa/grid/images/consoleservlet.css`
> 
> Overall, I don't really know the intent of this StaticResourceHandler and if at one point it was meant to handle these assets, so I called it a night and paused investigating.

**Comment by diemol** [comment]
Fixed to have code correctness via https://github.com/SeleniumHQ/selenium/commit/94f5d2e8f8ebf48545344c0230541817578da58b
Thanks for your contribution @virenv

Just bear in mind that the Grid 3.x won't be released anymore, and if someone needs this, s/he will need to build the jar themselves, with `./go selenium-server-standalone`.

I will add a comment to the templates where we won't receive more PRs for the 3.x Grid.

**Comment by pankajsethi93** [comment]
So I have cloned the selenium directory and make the build for jar using command ./go selenium-server-standalone ..
It got build but I am wandering where the output is stored. I read in the documentation that using ./go command gives a toplevel "build" directory and the output is stored in it. But in my case, no build directory is generated. But yes one "buck-out" directory is generated and I can find a jar output in the path /gen/java/server/src/org/openqa/grid/selenium/selenium.jar. 
So is it the correct output?

**Comment by diemol** [comment]
Yes, that is the generated jar.

**Comment by pankajsethi93** [comment]
Thanks alot @diemol
