### ISSUE TITLE
What is driver.controlFlow function?

### ISSUE THREAD

**Issue by pwsses** [SeleniumHQ/selenium#6962]
### When I try using eyes.selenium which is AI based selenium test Tool.
I met follow message in eyes.open API.

"UnhandledPromiseRejectionWarning: TypeError: driver.controlFlow is not a function"

There are using controlFlow method after bulid. 

I can't find this method in selenium doc. Is method deprecated? 

applitools guide : (https://applitools.com/tutorials/selenium-javascript.html#quick-start)

Please help me about this.

Thank you.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by jleyba** [comment]
`driver.controlFlow` was removed. What code are you running that's trying to call it?

**Comment by fescobar** [comment]
@pwsses what was the problem? did you find any solution or workaround?
