### ISSUE TITLE
webdriver and asyncio

### ISSUE THREAD

**Issue by parthibd** [SeleniumHQ/selenium#6964]
I am facing issues with selenium and asyncio. I am trying to run multiple instances of webdriver in the same loop. The first instance starts just file and goes to the required url. But the subsequent instances just open up a blank firefox windows . Can someone give me some hints into why this is happening ?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
