### ISSUE TITLE
Click is not working properly in Chrome V 72 

### ISSUE THREAD

**Issue by toraylin** [SeleniumHQ/selenium#6968]
Hi, 
I see my chrome version was upgraded to v72 last week. 
Selenium Click () is not working properly for the menu items.
For example, 
If driver finds the parent class name (A)  , and then I click A, Click A is working.
If I  use  parent A to find Child class name (B), and then I click B,  Click B is not working (no response)
Using Actions class to handle click is not working either.

I downgraded Chrome from v72 to v71 or v70 and both clicks are working properly.  I have the confidence to say click is not working properly in Chrome v72. 

Environment: 
Selenium 2.45, Chrome v72: , Windows 10  Click is not working properly 
Selenium 2.45, Chrome v71, Windows 10 :  Click is working properly 

Thanks,

Ray

**Comment by p0deje** [comment]
Please post ChromeDriver specific issues to [its own bug tracker](https://sites.google.com/a/chromium.org/chromedriver/help).
