### ISSUE TITLE
on linux, if port 1024 is occupied, can this be improved?

### ISSUE THREAD

**Issue by fzhyzamt** [SeleniumHQ/selenium#6970]
## 💬 Questions and Help

my port config range is [1024, 65535], so if port 1024 is occupied, then find ephemeral port will fail.
Why return to 1024 directly? can we use random port?
```shell
#shell 1
root@/tmp# cat /proc/sys/net/ipv4/ip_local_port_range
1024	65535
root@/tmp# nc -l 1024
....

#shell 2
Caused by: java.lang.RuntimeException: Unable to find a free port
	at org.openqa.selenium.net.PortProber.findFreePort(PortProber.java:67)
```
[org.openqa.selenium.net.PortProber.createAcceptablePort](https://github.com/SeleniumHQ/selenium/blob/83b2736806139c3a5ebe5f4b883422ed64b157d0/java/client/src/org/openqa/selenium/net/PortProber.java#L79)

I find [this](https://github.com/SeleniumHQ/selenium/issues/4920#issue-267325853) and [this](https://github.com/SeleniumHQ/selenium-google-code-issue-archive/issues/3868#issue-138324933), but there is not solve my problem.

**Comment by diemol** [comment]
@fzhyzamt, first, apologies for the late reply, second, we have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template. Until then, we cannot continue.

**Comment by fzhyzamt** [comment]
@diemol
Hi, I didn't see anything in the "Questions" template.
Do you mean the title? Or does the classification require a link query to the template?
No one is talking inside

**Comment by diemol** [comment]
When you create an issue the following options are shown:
![image](https://user-images.githubusercontent.com/5992658/54910408-96289080-4eec-11e9-8f18-1a1ad00b4af4.png)

and if you select "Bug Report", a template that requests the information is there:
![image](https://user-images.githubusercontent.com/5992658/54910475-b48e8c00-4eec-11e9-8ccc-1e7dc61b630f.png)

You mention that you selected the "Questions" option:
![image](https://user-images.githubusercontent.com/5992658/54910520-c96b1f80-4eec-11e9-96e5-1a22aeb52b5a.png)
As it clearly states, this is not a help forum and gives you options to address the question.
