### ISSUE TITLE
InternetExplorerDriver crashing on sendKeys to file selection control (sometimes) (with dumps)

### ISSUE THREAD

**Issue by reinsch82** [SeleniumHQ/selenium#6976]
The IE driver crashes sometimes (we can repro this in a rather complicated environment within a few hours)

But the good news is we have a dump here and we could provide more:
https://at.cloud.fabasoft.com/folio/public/2o5ysh2mp1fyk3uuto3owqdk8h

## Environment

OS: Windows 10 1809
Browser: IE
Browser version: 
Browser Driver version: InternetExplorerDriver 3.141.5
Language Bindings version: Java 3.141.159

**Comment by jimevans** [comment]
Fixed with commit 2a91fe5.
