### ISSUE TITLE
Add wait methods

### ISSUE THREAD

**Issue by heckad** [SeleniumHQ/selenium#6979]
## 🚀 Feature Proposal

For each find method like `find_element_by_css_selector` or `find_element_by_css_selector` add wait method wich will be wait until element show.

## Motivation

I am use python and now I shoud make function 
```
def wait_element_by_css_selector(driver, css_selector, timeout=10):
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.wait import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
    return WebDriverWait(driver, timeout).until(EC.presence_of_element_located((By.CSS_SELECTOR, css_selector)))
```
and add it to `WebDriver` as method. I now that it isn`t good practic and I suggest write the correct code and add it to selenium

## Example

For example I want to send file and when it finishes uploading, a confirm button appears on the page. For click on it you will need to write `driver.wait_element_by_id("confirm").click()`

**Comment by cgoldberg** [comment]
I don't think we want convenience methods for calling WebDriverWait with specific ExpectedConditions and specific locator types.  WebDriverWait is kind of awkward, but at least it gives you the flexibility of waiting on an any condition using any locator.

just my $.02...

**Comment by diemol** [comment]
Completely agreed with @cgoldberg, Selenium is just a set of "tools and libraries enabling web browser automation.", which means that it gives users all the freedom to make it fit to their particular needs. That type of features are not really part of the base library.

If you need a framework that helps you to do that, there are several around, for Python you could check https://github.com/watir/nerodia
