### ISSUE TITLE
[Java] How to deal with the IE zoom level not 100% problem?

### ISSUE THREAD

**Issue by hakuyou** [SeleniumHQ/selenium#6981]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by hakuyou** [comment]
Hi, 

I have two Selenium Server nodes running as Jenkins slave on remote with IE 11 and win 10. The browser's zoom level and windows display setting have set to 100%.

If someone connect the remote sever using remote desktop(mstsc.exe) with win 10 and the display settings is not 100% while then the selenium test start, the IE zoom level exception will be thrown and the test will be interrupted.

I have try to use ignoreZoomSetting as follow:


            DesiredCapabilities capability = DesiredCapabilities.internetExplorer();
            capability.setCapability(InternetExplorerDriver.IGNORE_ZOOM_SETTING, true);
            return new RemoteWebDriver(new URL(url), capability);   

but it doen't works.

Now I'm trying to find a way to reset the IE zoom level to 100% before the Selenium Sever launch it's instance. Does anybody have ideas? 

Thanks

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
