### ISSUE TITLE
Publish a nuget package with chromedriver

### ISSUE THREAD

**Issue by bgavrilMS** [SeleniumHQ/selenium#6985]
## 🚀 Feature Proposal

Publish a nuget package with chromedriver, similarly to how you publish a Maven artifact with it https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-chrome-driver

## Motivation

There are currently a few NuGet packages that will install chromedriver, [the most successful](https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/) has some 4.5M downloads. These are done by the community. 

Enterprises have a tough time approving these for use. It would be much easier if SeleniumHq would publish it.

**Comment by diemol** [comment]
I am not sure if NuGet is the right tool for that, nevertheless that is not the point to discuss here :)
Anyway, ChromeDriver is done directly by the Chromium team, so I strongly believe that this should be something to tackle by them or any other open source enthusiast. 

The Selenium project should not really package and ship code that is produced elsewhere. Division of concerns I would say.

What you reference here https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-chrome-driver, it is actually just the bindings to interact with ChromeDriver, people still need to download it and configure it. Unless I am completely wrong about this.

**Comment by bgavrilMS** [comment]
Good point, thanks.
