### ISSUE TITLE
ExpectedConditions.presenceOf(WebElement) for Java

### ISSUE THREAD

**Issue by rkrisztian** [SeleniumHQ/selenium#6987]
## 🚀 Feature Proposal

I think the Java bindings could use an `ExpectedConditions.presenceOf(WebElement)` wait condition for use together with the `FindBy` annotation. In fact, every canned condition that can be used with a `By` parameter, should also have a counterpart that can be used with a `WebElement` parameter.

## Motivation

In Java, you can already call `ExpectedConditions.presenceOfElementLocated(By)`, but the use of the `FindBy` annotation makes tests easier to read, and since there could be cases when you need to specify a complex wait condition that would want to use something like `presenceOf(WebElement)` as part of the condition, I miss a method like that.

## Example

Now, this is quite difficult for me, because honestly I can't tell an actually practical, non-fabricated real-life example where particularly `presenceOf` would be used. :) Yes I could say: **"in complex wait conditions"** (explained below), but I could still not come up with an example where I actually needed it. And that is because my examples would be only as strong as examples for `presenceOfElementLocated(By)`. The reason is, just checking if elements are present in the DOM aren't the most useful checks, as most of the time you also care about visibility. Or that's what would be normal, a regular user only checks what is also visible on the screen, except for exceptional cases, but I also call them hacky cases, because you rely too much on internal details. Still, I know sometimes `presenceOf` may be the only option, and `visibilityOf`, while it is meant to be used on elements that are known to be present in the DOM, with Selenium 3's default implicit timeout of zero, it can be used just fine with `FindBy`-annotated elements. Although this isn't really a strong reasoning either, because most people realize that their life is simpler if the implicit timeout is set to something higher (what's the point of such a feature when it's not used most of the time, unless you use `findElement` together with Protractor against an Angular app of course?), then mixing up implicit and explicit timeouts will result in problems, but that's already true for `presenceOfElementLocated(By)`. And of course there's the point of implicit waits also being simply more concise than explicitly waiting for an element to be present, unless your wait condition is more complex, **like, including `or` calls**. So as you can see, **it's really just a matter of where you put the selectors**. For that reason alone, a consistent parity between such methods would be expected. One should not exist without the other.

_**(Edit: this paragraph is now the topic of #7007, to keep this issue focused on 1 topic.)** Maybe an also useful feature request would be to **disable implicit timeouts when explicit waits are performed**. My life has become much easier when I extended the `WebdriverWait` class to do exactly that, as I didn't end up in situations where the total wait time exceeded the explicit wait time. I see many end-to-end testing tools have been created partly for the reason that they do better than the timeout handling in Selenium. Maybe we should change that. And maybe that's too late to be included in Selenium 3, I know. :)_

Also, **why would wait conditions be complex**? At first they may sound like you don't really know what you're expecting. e.g. you enter a search keyword into the search field. There may or may not be any results displayed, and somehow both are acceptable, but not something like a validation error or an internal server error... Then you would check for either a "no-result" element or a "list" element. But why would you be in a situation like that instead of managing test data properly? Sometimes you have no option as you don't control the data well enough? You don't want your tests to fail because of that? **Rare cases for sure.** And then you also have `driver.findElements` as well as `ExpectedConditions.presenceOfAllElementsLocatedBy`... But they're still not ones I would use together with `@FindBy` or `@FindAll` or `@FindBys`.

I will leave to your judgement whether I provided a good enough reason. If you say no to it, I would appreciate a reasoning that is more than just "you guys weren't convinced; I didn't give a good enough reason." Thanks in advance.

**Comment by virenv** [comment]
@rkrisztian: You have mentioned a few points in a long explanation. It would be really good if you can bullet point each point just after that paragraph or may be summarize it in the end. I personally think that it will add more clarity to your requirements.

To your very first point ExpectedConditions.presenceOf(WebElement). If you already have an instance of this WebElement why would you need presenceOf check. You can only check this condition if you pass a By. Sorry if I missed something in your explanation.

**Comment by alexHayes08** [comment]
Looking into this there do seem to be overloaded methods like `ExpectedConditions.invisibilityOf(WebElement)`[src](https://github.com/SeleniumHQ/selenium/blob/ddd3c7c3c6574a2d608f2f0873d35ab7d5970247/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java#L1331) and `ExpectedConditions.visibilityOf(WebElement)`[src](https://github.com/SeleniumHQ/selenium/blob/ddd3c7c3c6574a2d608f2f0873d35ab7d5970247/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java#L296) which do take an element as an argument.

Are these what you're looking for?

**Comment by rkrisztian** [comment]
@alexHayes08 , the answer for your question is already in the ticket description.

**Comment by virenv** [comment]
@rkrisztian : To be honest you have a very big explaination which is diminishing the impact of what you want to say. It would be really good if you can condense the explaination to just talk about specifics. 

I find it confusing to understand what you understand when we say ExpectedConditions.PresenceOf ?. In code presenceOf expected conditions just check that a valid element is returned by driver.findby method. Which means that we are simply asserting that a valid element of that locator is present in the DOM. 
So if you want to check for presenceOf element by passing a WebElement you are saying that you already have an instace of the element that you want to find. If you already have that element then you would not need a presenceOf expected condition.

**Comment by rkrisztian** [comment]
@virenv, please take a look at how `@FindBy` works. It proxies `WebElement` objects so that they are looked up on first use. This is where a `presenceOf` implementation would get tricky, because such a condition would probably call a dummy operation like `getTagName()` to force the lookup.

**Comment by jimevans** [comment]
Or, in the case of the Java `PageFactory` one could use an element locator that performs the “wait for presence” check (like that provided by `AjaxElementLocatorFactory`) obviating the need for such an addition to `ExpectedConditions`. Or, if that’s not sufficient, one can create a custom implementation of the `ElementLocatorFactory` interface to be used with `PageFactory`.

**Comment by virenv** [comment]
@rkrisztian : Now I think I got a hang of what you wanted to say. That seems to be a good idea but I am not sure it will be a requirement that you would bake into a library. I am not a commiter to this project by that is my opinion. I think we can implement this without having it in library.

**Comment by formynet** [comment]
@jimevans trying to make sense of your comment "Note that this is simply my opinion. I dislike the use of PageFactory vs. other methods of creating page objects, so you’re free to discard my comment entirely." Why do you dislike PageFactory vs other methods of creating page objects?

**Comment by jimevans** [comment]
@formynet That's out of scope and not really relevant to this discussion. I dislike PageFactory because of the way it attempts to use proxy objects. There are better ways to create an object that represents a page or a portion of the page, which is no more verbose than using the PageFactory style. I also don't much care for the use a annotations in this way, but again, that's just an opinion.

**Comment by barancev** [comment]
@rkrisztian Please provide a sample where this feature would be usable. How and when is it supposed to be used?

**Comment by diemol** [comment]
Closing this one as we didn't get more information.
