### ISSUE TITLE
3.141.0 Encoding problem

### ISSUE THREAD

**Issue by Tyrone-Zhao** [SeleniumHQ/selenium#6988]
Meta -
ProgramLanguage: Python 3.7.1
OS: MacOS Mojave
Selenium Version: 3.141.0
IDE: VScode 1.31.1
Browser: Chrome
Browser Version: 72.0.3626.119

Expected Behavior -
driver.page_source return the correct encoding "utf-8", but get "gbk". It is possible that the server side did not set the response header.
![image](https://user-images.githubusercontent.com/37615298/53700569-ca99b700-3e2e-11e9-92cd-468901cd3cca.png)

Actual Behavior -
![image](https://user-images.githubusercontent.com/37615298/53700592-eef59380-3e2e-11e9-927b-57f1d3c4eb2c.png)

Please check up the encoding, and fix driver.page_source method to read the response data properly.

Maybe Useful -
![image](https://user-images.githubusercontent.com/37615298/53700602-016fcd00-3e2f-11e9-8e37-b937e95771fe.png)
![image](https://user-images.githubusercontent.com/37615298/53700606-0896db00-3e2f-11e9-947f-74a7c96efbe4.png)

**Comment by diemol** [comment]
@Tyrone-Zhao 
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site). We prefer to avoid assuming things, that is why we have an issue template requesting all the data (which you have deleted 😞).

**Comment by Tyrone-Zhao** [comment]
### Backgroud
We are programing crawlers with selenium, but some web servers don't always return the correct response header. This causes the driver. page_source that these websites display in the browser to be garbled. It is not realistic for us to have the website to change the response header code. Chrome has also removed the coding Settings, which are too difficult to handle by loading js. And we can do it right in python. However, Selenium's Python API does not handle it correctly. I have always believed that Selenium's Python API is an important programming tool for users who use Python to program crawlers. So I hope this issue can be properly handled.

### SSCCE
The URL in SSCCE is a Chinese weather website with a large number of users, but the server has a long history. To run the following code, you may need a Chinese agent or IP. 

```python
import urllib
import time
from selenium import webdriver

url = f"http://toy1.weather.com.cn/search?cityname={urllib.request.quote('广州')}"
f = urllib.request.urlopen(url)
print(f"Expected Behavior: \n{f.read().decode('utf-8')}\n\n")

driver = webdriver.Chrome()
driver.get(url)
time.sleep(2)
print(f"Actual Behavior: \n{driver.page_source}\n\n")
print(f"The response Headers: \n{f.info()}")
```

Best wishes.

**Comment by lmtierney** [comment]
I'm not sure I _completely_ follow, but chromedriver is required to send us json encoded in `utf-8` which we decode in the line you pointed out in your screenshot. We do not do any processing with the encoding on the page or page headers, that is the duty of chromedriver. This sounds like something you want to raise with them.

Unless I missed something, and there is something we need to fix on our end?

**Comment by Tyrone-Zhao** [comment]
Ok, I'll submit this issue to chromedriver.
