### ISSUE TITLE
ie driverservice allways get incorrect processid and uri port

### ISSUE THREAD

**Issue by brickhe** [SeleniumHQ/selenium#699]
chrome driverservice is correct,
but IE is wrong, ie allways return processid with 0, and uri port is minus 1 from the real port displayed in the console.

c# / win7 64bit / ie11/ webdriver 2.46

**Comment by jimevans** [comment]
I've created the following simple C# code:
```
static void Main(string[] args)
{
    InternetExplorerDriverService service = InternetExplorerDriverService.CreateDefaultService();
    service.Start();
    Console.WriteLine("Started with process ID {0}, listening on port {1}", service.ProcessId, service.Port);
    Console.WriteLine("Press <Enter> when done");
    Console.ReadLine();
    service.Dispose();
}
```
When I execute that code, I receive the following in my console window:
```
Started InternetExplorerDriver server (32-bit)
2.46.0.2
Listening on port 15489
Started with process ID 1580, listening on port 15489
Press <Enter> when done
```
A quick look at my Task Manager shows the following (note the correct Process ID for IEDriverServer.exe):
![taskmanager](https://cloud.githubusercontent.com/assets/352840/8319000/200a27bc-19d8-11e5-9285-2220896a7be8.PNG)

You'll need to provide more information for this issue to receive any attention.

**Comment by jimevans** [comment]
Six days with no response. Closing this issue for now. If you can provide further information, we can consider reopening it.
