### ISSUE TITLE
OpenJDK 11.0.2 does not seem to support maven download of selenium-java jars

### ISSUE THREAD

**Issue by formynet** [SeleniumHQ/selenium#6993]
## 🐛 Bug Report

OpenJDK 11.0.2 does not seem to support maven download of selenium-java jars in Windows 10 OS.

## To Reproduce
1.download openjdk 11.0.2 and set up environment variables.
2.make sure java environment is correctly setup by executing any java program.
3.create a new selenium maven project in windows 10 operating system.
4. add below dependency for selenium in valid maven pom.xml
`
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
            <scope>test</scope>
    </dependency>
`

5. Clean install the maven project.

Actual
selenium jars are not downloaded. 
User gets below errors in console.
[ERROR] error reading C:\Users\<userid>\.m2\repository\org\seleniumhq\selenium\selenium-api\3.141.59\selenium-api-3.141.59.jar; zip END header not found
[ERROR] error reading C:\Users\<userid>\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.141.59\selenium-remote-driver-3.141.59.jar; zip END header not found

## Expected behavior

Selenium jars should be downloaded in local m2 folder.

## Environment

OS:  Win 10
Browser:  Not applicable.
Browser version: 
Browser Driver version: 
Language Bindings version:   Java 3.141.59
Selenium Grid version (if applicable):  Not applicable.
@shs96c

**Comment by virenv** [comment]
> **selenium jars are not downloaded.**
User gets below errors in console.
[ERROR] error reading C:\Users<userid>.m2\repository\org\seleniumhq\selenium\selenium-api\3.141.59\selenium-api-3.141.59.jar; zip END header not found
[ERROR] error reading C:\Users<userid>.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.141.59\selenium-remote-driver-3.141.59.jar; zip END header not found

This error suggests that the jar files were downloaded in the .m2 folder. However, while reading it there was some issue. Can you please confirm that?

**Comment by formynet** [comment]
please close the bug. it was probably my maven issue. thanks for looking into it.

**Comment by jimevans** [comment]
Closing per reporter request
