### ISSUE TITLE
ActionsChains key_action.pause causes "exception 'value' must be a single unicode point" in Appium Webview or Chromium

### ISSUE THREAD

**Issue by jvanyo** [SeleniumHQ/selenium#7000]
## 🐛 Bug Report

Using python in Appium with an Android device running a hybrid app or the chrome browser:
I was attempting to execute:
ActionChains(driver).move_to_element(element).click().perform()
when I got the exception: 'value' must be a single unicode point

I created an issue against appium: https://github.com/appium/appium/issues/12255
You can see from that discussion that it led to selenium ActionChains.
While playing with the code I found the problem is with the code
self.w3c_actions.key_action.pause()
2 questions:  
1. Why are there 2 key_action.pause() lines?
2. Throughout this class, could the key_action.pause() be replaced with pointer_action.pause(), which does not cause the error?

    def click(self, on_element=None):
        """
        Clicks an element.

        :Args:
         - on_element: The element to click.
           If None, clicks on current mouse position.
        """
        if on_element:
            self.move_to_element(on_element)
        if self._driver.w3c:
            self.w3c_actions.pointer_action.click()
            self.w3c_actions.key_action.pause()
            self.w3c_actions.key_action.pause()
        else:
            self._actions.append(lambda: self._driver.execute(
                                 Command.CLICK, {'button': 0}))
        return self

## To Reproduce

You need to be running Appium Version 1.11.1. (version 1.11.0 returns a different error)

## Test script or set of commands reproducing this issue
from appium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.actions.action_builder import ActionBuilder

import time
import traceback

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '8.1'
desired_caps['deviceName'] = 'XXXXX'
desired_caps['newCommandTimeout'] = '300'
desired_caps['automationName'] = 'UIAutomator2'
desired_caps['browserName'] = 'Chrome'
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

try:
action = ActionBuilder(driver)
    action.key_action.pause()
    action.perform()
    print('The key_action.pause worked')
except Exception:
    print('key_action.pause failed')
    print(traceback.format_exc()) 
	
try:
    action = ActionBuilder(driver)
    action.pointer_action.pause()
    action.perform()
    print('The pointer_action.pause worked')
except Exception:
    print('pointer_action.pause failed')
    print(traceback.format_exc()) 
	
time.sleep(5)
driver.close_app()

Results:
key_action.pause failed
Traceback (most recent call last):
  File "W3CActionChainsFailure2.py", line 20, in <module>
    action.perform()
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
  File "C:\Program Files\Python37\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
from invalid argument: 'value' must be a single unicode point
  (Session info: chrome=72.0.3626.105)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)

The pointer_action.pause worked

Appium logs shows:
[HTTP] --> POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions
[HTTP] {"actions":[{"type":"key","id":"key","actions":[{"type":"pause","duration":0}]}],"sessionId":"9dbc8b78-dad3-4401-a929-3df051d
26aa4"}
[W3C (9dbc8b78)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions' to command name 'performActions'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions] to [POST http://127.0.0.1:8000/wd/hu
b/session/0c5d3edc1d5b4eb9d1e6b62914a0ec97/actions] with body: {"actions":[{"type":"key","id":"key","actions":[{"type":"pause","dura
tion":0}]}],"sessionId":"9dbc8b78-dad3-4401-a929-3df051d26aa4"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0c5d3edc1d5b4eb9d1e6b62914a0ec97","status":61,"value":{"message":"inv
alid argument\nfrom invalid argument: 'value' must be a single unicode point\n  (Session info: chrome=72.0.3626.105)\n  (Driver info
: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)"}}
[WD Proxy] Got an unexpected response: {"sessionId":"0c5d3edc1d5b4eb9d1e6b62914a0ec97","status":61,"value":{"message":"invalid argum
ent\nfrom invalid argument: 'value' must be a single unicode point\n  (Session info: chrome=72.0.3626.105)\n  (Driver info: chromedr
iver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Win...
[debug] [W3C (9dbc8b78)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Or
iginal error: The request to /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions has failed
[debug] [W3C (9dbc8b78)]     at JWProxy.proxy (C:\Users\laors\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-drive
r\lib\jsonwp-proxy\proxy.js:180:13)
[debug] [MJSONWP] Matched JSONWP error code 61 to InvalidArgumentError
[HTTP] <-- POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions 400 133 ms - 1071
[HTTP]
[HTTP] --> POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions
[HTTP] {"actions":[{"type":"pointer","parameters":{"pointerType":"mouse"},"id":"mouse","actions":[{"type":"pause","duration":0}]}],"
sessionId":"9dbc8b78-dad3-4401-a929-3df051d26aa4"}
[W3C (9dbc8b78)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions' to command name 'performActions'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions] to [POST http://127.0.0.1:8000/wd/hu
b/session/0c5d3edc1d5b4eb9d1e6b62914a0ec97/actions] with body: {"actions":[{"type":"pointer","parameters":{"pointerType":"mouse"},"i
d":"mouse","actions":[{"type":"pause","duration":0}]}],"sessionId":"9dbc8b78-dad3-4401-a929-3df051d26aa4"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"0c5d3edc1d5b4eb9d1e6b62914a0ec97","status":0,"value":null}
[WD Proxy] Replacing sessionId 0c5d3edc1d5b4eb9d1e6b62914a0ec97 with 9dbc8b78-dad3-4401-a929-3df051d26aa4
[HTTP] <-- POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/actions 200 30 ms - 76
[HTTP]
[HTTP] --> POST /wd/hub/session/9dbc8b78-dad3-4401-a929-3df051d26aa4/appium/app/close
[HTTP] {"sessionId":"9dbc8b78-dad3-4401-a929-3df051d26aa4"}
[debug] [W3C (9dbc8b78)] Calling AppiumDriver.closeApp() with args: ["9dbc8b78-dad3-4401-a929-3df051d26aa4"]

## Environment

OS: Window 7
Browser: Android 8.1 Chrome
Browser version: 72.0.3626.105
Browser Driver version: ChromeDriver 2.45.615291
Language Bindings version: Python 3.7.2
Selenium Grid version (if applicable):  3.141.0
Appium Version 1.11.1.  (version 1.11.0 returns a different error)

**Comment by lmtierney** [comment]
> Why are there 2 key_action.pause() lines?
There are two because the `pointer_action.click()` performs a `pointer_down` and `pointer_up` action which requires the `KeyInput` device to pad two pauses in order to keep the order of operations right. This is mostly to remain backward compatible with the old actions api and you can in fact create your own action sequence as suggested in the appium bug.

If you can recreate this using just selenium and not appium then I can look into it, but I don't have enough time right now to get appium setup

**Comment by lmtierney** [comment]
Looking more into this, it looks like you're trying to use chrome with `w3c` but version `2.45`. I'd advise you to try this with a newer version (versions compatibility is listed here http://chromedriver.chromium.org/downloads) as actions were still being tweaked in the last release. If it's still not fixed in the latest release, please raise an issue with the chromedriver team:
https://bugs.chromium.org/p/chromedriver/issues/list

**Comment by jvanyo** [comment]
I just found that others have reported this issue with Safari in StackOverflow: https://stackoverflow.com/questions/52947603/selenium-action-move-to-element-doesnt-work-in-safari-because-of-usupported

**Comment by lmtierney** [comment]
Yep, and I'm sure 4 months ago when Safari was still working on w3c actions as well (note they had to set w3c to true to even use it since it was in development), that it wasn't quite finished yet.

I just tried it on the latest and greatest and it works fine.

**Comment by jvanyo** [comment]
Just moved up Appium to use Chromedriver 2.46 and it works.  Thanks.
