### ISSUE TITLE
Selenium Scripts is not getting parameters from App.Config file in NUnit Project

### ISSUE THREAD

**Issue by ank1006** [SeleniumHQ/selenium#7001]
I am trying to use App.Config file to pass my Browser name and url to my test framework. I have used ConfigurationManager class to do so but still no luck in getting the values from config file. Here is the config file and code that i am using

**App Config :** 

![image](https://user-images.githubusercontent.com/47805449/53842503-d08cc500-3ff3-11e9-95bb-51dbf7dad1a5.png)

 browsername =  ConfigurationManager.AppSettings["BrowserName"]; 
 Url = ConfigurationManager.AppSettings["Url"];

**Comment by virenv** [comment]
@ank1006 : This is not a Selenium problem. Your C# code needs to be reviewed to fix this problem.

**Comment by ank1006** [comment]
@virenv This is certainly is not a problem but I thought there is some configuration missing that needs to be done while using app.config to pass data to selenium scripts,so wanted to check if somebody has implemented similar stuff.

**Comment by virenv** [comment]
@ank1006 : I am not an expert on this topic but it seems that documentation on MSDN and this [Stackoverflow](https://stackoverflow.com/questions/19232695/how-to-use-configurationmanager) might help you.

**Comment by jimevans** [comment]
This problem has nothing to do with Selenium. Selenium does not interfere with the .NET ConfigurationManager
