### ISSUE TITLE
Disable implicit timeouts during explicit waits

### ISSUE THREAD

**Issue by rkrisztian** [SeleniumHQ/selenium#7007]
## 🚀 Feature Proposal

Essentially what I report here is the same as #1176, and I know it has a resolution, this ticket is to challenge that resolution.

## Motivation

Currently timeout handling in Selenium is not ideal in my opinion:

* Efficiency (not my strongest argument, as it may be premature optimization):
    * Implicit waiting the most efficient way of waiting for element to exist, because the polling happens in the browser. This timeout however is 0 since Selenium 3, thus not used.
    * Explicit waits will continuously do the polling in the client, talking to the browser through the network in every half a second by default (doing up to a total of 20 queries when 10 seconds is the timeout). If for example, one changes the poll interval to 50 ms, this could get worse.
* Code readability
    * When simply the element existence is the condition, implicit waits are the simplest to use, as `driver.findElement` does not require a new object creation, and use of static imports for more brevity.
* Automatic timeout management is less error prone
     * Several frameworks (Cypress, TestCafe) would take the timeout handling out of developers' hands, and keep it as automatic as possible. So if you perform several point-and-click operations on a page (one after the other), all you need is, find an element until a timeout happens, then click, then rinse and repeat. If you added explicit waits to parts where you think are necessary, in the future you would find your tests breaking randomly...

Therefore, implicit timeouts do make sense, I think people will want to use them (except with frameworks like Protractor, which should disable such timeouts by itself), however, this effectively means that implicit timeouts should be disabled just for the duration of using `WebDriverWait`, after which, the previously used setting should be restored (regardless of timeouts, I would say, as test writers may catch exceptions for whatever reasons).

## Example

There are several canned conditions in `ExpectedConditions` that performs an element lookup, either by calling `driver.findElement` explicitely, or implicitely when using `@FindBy` and similar annotations.

https://letmedothat.wordpress.com/2015/04/11/why-would-you-never-mix-explicit-and-implicit-waits-in-selenium-webdriver/

**Comment by Huffman17** [comment]
It's funny because WebDriverWait actually thread sleeps. Which they also mention being a "Worst Case" on the seleniumHQ website.

**Comment by virenv** [comment]
@Huffman17 : At the end there is no other way to wait in a program sequence. Explicit waits are high level constructs that will eventually have to use native programming constructs to wait. Sleep is one such construct that enables you to wait deterministically.

**Comment by Huffman17** [comment]
@virenv Yes, however, this for example from the seleniumhq website `    IWebElement myDynamicElement = wait.Until<IWebElement>(d => d.FindElement(By.Id("someDynamicElement")));
` If you look at the wait.Until function that is provided by selenium it is doing a thread sleep. Which is funny because they also mention :

> The worst case of this is Thread.sleep(), which sets the condition to an exact time period to wait.

Pretty funny actually.

**Comment by jimholmes** [comment]
@Huffman17 There's a vast difference between dropping a Thread.Sleep alone in your test and using it in a timeout loop as part of a poll. That's what explicit waits do--poll versus simply sleep.

**Comment by virenv** [comment]
@rkrisztian : I do agree to the points you have mentioned above and I do agree that Explicit wait should/might be called by setting implicit wait to 0 first. However, I am not convinced that you would need it implemented in Selenium. This is because adding this functionality will render ExpectedCondition class useless to people who don't want to set the Implicit wait time to 0. We can argue that people who dont want to set implicit wait to 0 are missing something but that would be going against the reality. 

Most importantly from a programing perspective, making your classes tight would result in narrowed spectrum of usage. Library should give you basic blocks/constructs on which you can build whatever you want. In this case creating a wrapper class would do what we need. An external helper library would just be a great idea.

**Comment by mintgreenmonkey** [comment]
@Huffman17 

> Pretty funny actually.

You can edit the page and update it to a version less hilarious to you if you want.

**Comment by KitoCoding** [comment]
> @Huffman17 There's a vast difference between dropping a Thread.Sleep alone in your test and using it in a timeout loop as part of a poll. That's what explicit waits do--poll versus simply sleep.
@jimholmes 
```
public TResult Until<TResult>(Func<T, TResult> condition)
        {
            if (condition == null)
            {
                throw new ArgumentNullException("condition", "condition cannot be null");
            }

            var resultType = typeof(TResult);
            if ((resultType.IsValueType && resultType != typeof(bool)) || !typeof(object).IsAssignableFrom(resultType))
            {
                throw new ArgumentException("Can only wait on an object or boolean response, tried to use type: " + resultType.ToString(), "condition");
            }

            Exception lastException = null;
            var endTime = this.clock.LaterBy(this.timeout);
            while (true)
            {
                try
                {
                    var result = condition(this.input);
                    if (resultType == typeof(bool))
                    {
                        var boolResult = result as bool?;
                        if (boolResult.HasValue && boolResult.Value)
                        {
                            return result;
                        }
                    }
                    else
                    {
                        if (result != null)
                        {
                            return result;
                        }
                    }
                }
                catch (Exception ex)
                {
                    if (!this.IsIgnoredException(ex))
                    {
                        throw;
                    }

                    lastException = ex;
                }

                // Check the timeout after evaluating the function to ensure conditions
                // with a zero timeout can succeed.
                if (!this.clock.IsNowBefore(endTime))
                {
                    string timeoutMessage = string.Format(CultureInfo.InvariantCulture, "Timed out after {0} seconds", this.timeout.TotalSeconds);
                    if (!string.IsNullOrEmpty(this.message))
                    {
                        timeoutMessage += ": " + this.message;
                    }

                    this.ThrowTimeoutException(timeoutMessage, lastException);
                }

                Thread.Sleep(this.sleepInterval);
            }
        }
```

As you can see the Web Driver Wait feature is simply thread sleeping in a loop. Seleniums documentation states that the WebDriver Wait does not thread sleep, when clearly it does.

**Comment by Huffman17** [comment]
> @Huffman17 There's a vast difference between dropping a Thread.Sleep alone in your test and using it in a timeout loop as part of a poll. That's what explicit waits do--poll versus simply sleep.

Ah, Took another look. Makes sense! Thanks. So there is merit in using it 👍

**Comment by Huffman17** [comment]
> @Huffman17
> 
> > Pretty funny actually.
> 
> You can edit the page and update it to a version less hilarious to you if you want.

Sorry you mean editing the page in dev tools? I don't see what your getting at.

**Comment by mintgreenmonkey** [comment]
> Sorry you mean editing the page in dev tools? I don't see what your getting at.

https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/rst/04_webdriver_advanced.rst

I'm saying it's perfectly possible for you to fork this, change the page to a version that's less hilarious to you, and create a pull request.

**Comment by Huffman17** [comment]
@mintgreenmonkey perhaps you should observe the other comments ...

**Comment by diemol** [comment]
I think there are two points here:
1. Selenium is just a set of libraries that allows anyone to control the browser, that is why it is as unopinionated as possible. In this case, it allows the user to control the waits as desired, and in the end to make them work better for your environment. What we recomment is to not mix them. Under this point of view, things should stay the same and not change as this issue suggests, so to basically let the user be always in control.

2. >Automatic timeout management is less error prone 
      
    Selenium is not a testing framework, is just one more tool you add to the toolbelt and/or framework being used to test an app. If the point is to handle timeouts in an opinionated way, there are several frameworks built on top of Selenium that help with that. Some examples are Selenide for Java, Watir for Ruby and Nerodia for Python. All of them have well maintained extra methods that help the user get rid of the potential confusions of managing timeouts. I suggest to take a look at those frameworks, since they solve the problem already.
