### ISSUE TITLE
C# - OpenQA.Selenium.WebDriverException : for chromedriver.exe (nuget pkg version 2.46.0)

### ISSUE THREAD

**Issue by sanjaykulkarni04** [SeleniumHQ/selenium#7008]
OpenQA.Selenium.WebDriverException :

A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:49730/session/c097260d15be5935b9842a216fa2903d/element. The status of the exception was UnknownError, and the message was: Only one usage of each socket address (protocol/network address/port) is normally permitted

I am getting above error while executing scripts in parallel in xunit. FYI - I have .net core 2.2 xunit automation project and I am using Selenium.WebDriver.ChromeDriver 2.46.0 nuget pkg version. I also have chrome Version 72.0.3626 on my automation machine.

Can someone please assist me? Please let me know if you require more info.

OS: Windows NT 10.0
Browser: Chrome
Browser version: Chrome 72.0.3626.121
Browser Driver version: ChromeDriver.exe 2.46.0
Language Bindings version: C# nuget package version - Selenium.WebDriver 3.141.0

**Comment by virenv** [comment]
@sanjaykulkarni04 : Can you add more details like based on the [document here](http://sscce.org/)

More specifically if you can information like
- How you are creating driver for each thread
- a simplified code sample which can reproduce the error.

**Comment by diemol** [comment]
Closing as we didn't get any reply from the OP.
Feel free to reopen and provide all the information required in the issue template.
