### ISSUE TITLE
Selenium WebDriver supports Angular Apps or not?

### ISSUE THREAD

**Issue by firozshaik1987** [SeleniumHQ/selenium#701]
Hi Team,
I have a requirement of automating an Angular JS based application(whose front end widgets are developed by Angular JS not the usual JQuery). I do know that protractor tool is there in the market and we can use it. But it is completely Javascript oriented. And moreover it has only 2-3 more locator finding strategies (by.model('name') & by.binding('bindingname')) than what we usually have in normal Selenium WebDriver Java API (By.css,By.name,By.id,,By.xpath......). What I would like to know is, is usual selenium webdriver JAVA API is going support the angular JS based applications in future or not? Or Should I switch to Protractor completely.....? Please answer me whom exactly I should reach out to get this information.

Thanks,
Firoz

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by jleyba** [comment]
Selenium and Angular are two separate projects. Protractor is a tool provided by Angular to simplify writing tests against Angular JS apps. You'll have to ask the Angular folks if you want a protractor-like tool for Java. From the Selenium project's perspective, there's nothing to do here.

**Comment by firozshaik1987** [comment]
Hi jleyba,

Thank you for your input on this. What I am thinking about is , if Selenium is going to handle Angular based apps too in future, I would only stick to  Selenium ..Otherwise I may have to use only protractor in this particular case...As selenium is a web automation tool, do you really think that its scope is limited to only some web applications whose front end widgets are developed by JQuery but not the Angular JS...With a view that selenium should support every web application irrespective of what technology the application is developed by, can we expect usual selenium(Java API) to support Angular JS based applications too in future ?

**Comment by jleyba** [comment]
Selenium is a browser automation tool that provides a lot of DOM and JavaScript manipulation features. There is nothing in Selenium that favors one framework over another (jQuery vs Angular).

**Selenium does not do anything special for jQuery or any other framework**

Protractor is a framework built on top of Selenium by members of the Angular project. You should start a conversation with the protractor devs if you'd like to see something like it for Java.
