### ISSUE TITLE
Problem when try to find a object into a document html

### ISSUE THREAD

**Issue by jyarlequefl** [SeleniumHQ/selenium#7011]
## 🐛 Bug Report

Hi Everyone,  I have a problme when try to find an object in a web page, I attached an image, like you see, the object that we try to automate is an input, but this is into a second html, I try to use the id, xpath, class, and all the properties of selector, but it can´t, always appears the same error: NoSuchElementException: Unable to find element with id..., so I work with waits, and sleeps, but it´s the same, do you know the way to build an xpath to find this objct, i know the structure of web page is weird but it´s what i has, so please, if you know how, let me know, thank you so much.
![helpgw](https://user-images.githubusercontent.com/28601971/53999780-c7464a00-4112-11e9-9ce5-8fa653f50c1e.png)

## Environment

OS: Windows 10
Browser: Internet Explorer 
Browser version: 7
Browser Driver version: IEDriverServer 
Language Bindings version: Java 6

**Comment by lmtierney** [comment]
Your element is within a `<frame>` so you need to switch context. Don't forget to switch back when you're done:

https://www.seleniumhq.org/docs/03_webdriver.jsp#moving-between-windows-and-frames

`driver.switchTo()` will give you a `TargetLocator`

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebDriver.TargetLocator.html
