### ISSUE TITLE
Selenium grid support for appium server flag --session-override

### ISSUE THREAD

**Issue by Jiurong-Yang** [SeleniumHQ/selenium#7012]
Basically the Appium server have a command line option --session-override which will kill previous appium session if a new session request is received. But this flag is useless when in a selenium grid system. Due to the fact that selenium sees the node as unavailable and never forward the new session request.

How the feature would work is if the request is for a specific node. For appium that means the "applicationName" field is available in the desired capabilities then attempt to start a driver session on the server end. If "applicationName" then pick any available node that matches the desired capabilities. 

## Motivation
I'm just seeing a lot of node blocks when using Jenkins and somehow the step to stop a build mid build jenkins never trigger the clean up properly so if that happens the node becomes blocked unless I reboot grid or wait until grid finally recognize the node as available. 

Let me know what you guys think, or if anyone else is having the same issue as me.

**Comment by diemol** [comment]
Not sure how we will support this, as we will need to check with the Appium team to find a good approach. I will close this for now as we are handling a possible Appium + Grid 4 integration at #9127
