### ISSUE TITLE
Is there any reason get_parent or get_ siblings methods for a element does not exist?

### ISSUE THREAD

**Issue by Songyu-Wang** [SeleniumHQ/selenium#7015]
## 🚀 Feature Proposal

Adding a method to allow user to get the parent of a element
Adding a method to allow user to get the siblings of a element

## Motivation

If I can find the children element of a element with calling find on that element, why cant I get the parent or siblings?
The implementation should be very simple and those two methods seems like common method ppl use everyday.

## Example

Assuming:
```
<div "some_setting">
<div "some_other_setting"> text </div>
<div> otherstuff </div>
</div>
```
It would be easier if we can jump from inner div to outer div to check if setting are overwritten correctly

**Comment by cgoldberg** [comment]
Which client bindings are you referring to?

in the Python bindings (for example), `WebElement` already has a `parent` property... adding a `get_parent` method would be redundant (and unpythonic).

**Comment by Songyu-Wang** [comment]
@cgoldberg 
Based on the docs: `Internal reference to the WebDriver instance this element was found from.`
parent property is only for internal reference which would not return what normal people expect it to return.
See https://stackoverflow.com/questions/30439688/get-td-which-contains-specific-texts-and-then-find-its-parents-and-siblings as an example

**Comment by luke-hill** [comment]
Dependent on how you have located your element and what bindings you use depends on how this is done. Also note that for finding a parent of an element you would need to be using xpath locators only.

Either way, this feels like a package (py/gem/jar)'s responsibility as a layer ontop of selenium rather than selenium itself, and I know some of the bindings have removed things similar to this in the past because it's not really the responsibility of selenium

**Comment by okyrylenko** [comment]
you can use `/..` xpath to navigate to a parent element

**Comment by Songyu-Wang** [comment]
@luke-hill @okyrylenko Thanks for the workaround. I know I can do them that way, but my problem is that the code is less readable unless I wrap it as helper functions.
But if this is already decided to not include in selenium. I guess I will close the issue then.
