### ISSUE TITLE
Headless mode chromium js output data

### ISSUE THREAD

**Issue by sriramkumar1996** [SeleniumHQ/selenium#7019]
## 🐛 Bug Report

Websites with javascript enabled data loading, usually takes 1 (or) 2 seconds to load the pages.
After a sleep timer, the html page data can be seen(after writing to a file) but when tried in headless mode couldn't get the complete html page data.

## To Reproduce

import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
#options.add_argument("--headless") # Runs Chrome in headless mode.
options.add_argument("--start-maximized")

driver = webdriver.Chrome(chrome_options=options, executable_path="/path/to/chrome/driver")

url = 'https://www.yahoo.co.jp/'
driver.get(url)
time.sleep(3)

file = open("index.html", "w")
file.write(driver.page_source)
driver.quit()

Code source - [Testing.zip](https://github.com/SeleniumHQ/selenium/files/2950509/Testing.zip)

Detailed steps to reproduce the behavior:

## Expected behavior
Case 1:
In the above code, when run normally(without headless active), 
1. Yahoo website
2. Loads the section data using their javascript
3. Get the driver.page_source data and save it to a html file

Everything works till this point. The data is loaded into file. 

Case 2:

When I run this in headless mode, uncomment the `options.add_argument("--headless")` line and run the code. 
I cannot see the javascript loaded data(html page is not loaded completely).
 
## Test script or set of commands reproducing this issue

You can test by opening the saved html file and comparing it with the original website page(https://www.yahoo.co.jp/).

Case 1: Can load the news contents of the web page.
Case 2: Cannot load the news content of the web page.

I suspect that some features in headless mode is being disabled(javascript engine?). 

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version :

**Comment by lmtierney** [comment]
Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
