### ISSUE TITLE
Java 9,10 and 11 Support RoadMap

### ISSUE THREAD

**Issue by SurPatidar** [SeleniumHQ/selenium#7021]
## 🐛 Bug Report

Selenium Standalone server hub and node not working with Java 11 and getting the org.openqa.selenium.WebDriverException: Cannot define class using reflection exception.

Could you please provide the Selenium Roadmap to support Java 11?

## Environment

OS: Windows
Browser: Chrome
Browser version: 72
Browser Driver version: ChromeDriver
Language Bindings version: java 11.0.2
Selenium Grid version (if applicable):  3.9

**Comment by barancev** [comment]
Can you reproduce the issue with the latest selenium server version?

**Comment by SurPatidar** [comment]
Thanks @barancev , i tried with 3.141.59 version and it is working fine . As per the 3.141.59 dependency , it showing that net.bytebudy jar version upgraded and support to Java 11.  

Can you confirm that 3.141.59 officially support to Java 11 ?  We checked multiple article  and tickets  but not able to found that Selenium officially  support to Java 11. 

Can you or your team also mentioned the same on https://seleniumhq.org site to avoid the confusion?

 Thanks for you support..

**Comment by shs96c** [comment]
Selenium supports Java 11 already. The standalone jar is designed to be used out-of-process, but the maven dependencies (certainly in the clients) have module definitions and can be used with the Java Module System. If you find problems with these module definitions, please raise an issue.
