### ISSUE TITLE
Failed to takeScreenshot in driver and element

### ISSUE THREAD

**Issue by pwsses** [SeleniumHQ/selenium#7022]
Hi 

Currently, I failed take screenshot in my target. so I need some help.

I develop selenium Test case.  my develop env.

PC : windows 10, chrome driver 2.36, nodeJS
target : chromium 63 version

I connect my target with "chrome.Driver.createSession" (chromeOptions.options_['debuggerAddress'])

In this case, 

1. driver.takeScreenshot()
      - after call api, stop process,
      - my target chromium develop say, chrome driver not supported this api
         (https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md)
2. driver.findElement(webdriver.By.tagName('body')).takeScreenshot(false);
     - error message occur.
     - UnsupportedOperationError: unknown command: session/158573a92f5c1a400b8bf506d5c116c3/element/0.48810784510225513-2/screenshot

how to take screenshot in chrome debuggerAddress...???

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver
