### ISSUE TITLE
Unable to install selenium server standalone 3.8.0

### ISSUE THREAD

**Issue by weiming-myob** [SeleniumHQ/selenium#7023]
## 🐛 Bug Report

I started having problem when installing selenium-server-standalone-3.8.0.jar from npm this afternoon. Can someone help, please?

## To Reproduce
We are pulling selenium-server-standalone from npm and install to local and aws instance with a clean build, which mean no node_modules folder. Below is the error
> selenium-standalone installation starting
> 
> selenium install:
> from: https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
> to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/selenium-server/3.8.0-server.jar
> 
> chrome install:
> from: https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip
> to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/chromedriver/2.37-x64-chromedriver
> 
> firefox install:
> from: https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-macos.tar.gz
> to: /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/.selenium/geckodriver/0.23.0-x64-geckodriver
> /Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/bin/selenium-standalone:111
>         throw err;
>         ^
> 
> Error: Could not download https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
>     at Request.<anonymous> (/Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/selenium-standalone/lib/install.js:373:21)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at Request.onRequestResponse (/Users/weiming.chen/Projects/AD-PracticeOnline-Automation-Tests/node_modules/request/request.js:1066:10)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
>     at TLSSocket.socketOnData (_http_client.js:440:20)
>     at emitOne (events.js:116:13)

## Environment

OS: 
Browser Driver version:

**Comment by weiming-myob** [comment]
Here is the location where the error throws in install.js, it seems that  `request(downloadUrl, requestOpts)` does not return Success status code. 

```
  function getDownloadStream(downloadUrl, cb) {
    var r = request(downloadUrl, requestOpts)
      .on('response', function(res) {
        startedRequests += 1;

        if (res.statusCode !== 200) {
          return cb(new Error('Could not download ' + downloadUrl));
        }
  ....
  ....
  ....
  }
```

**Comment by dylanlive** [comment]
It's downloading just fine for me. Can you download it on your machine from your browser?
https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar

**Comment by dylanlive** [comment]
Actually, now it's not downloading for me. Interesting.

```
Request URL: https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar
Request Method: GET
Status Code: 503 
```

Other versions seem to be working, so perhaps the short term solution will be to use 3.8.1
https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar

**Comment by weiming-myob** [comment]
Interesting, after I added console.log inside of the function as below, it works. Is this implies some timing issue?

```
 function getDownloadStream(downloadUrl, cb) {
    var r = request(downloadUrl, requestOpts)
      .on('response', function(res) {
        **console.log(res.statusCode);**
        startedRequests += 1;

        if (res.statusCode !== 200) {
          return cb(new Error('Could not download ' + downloadUrl));
        }
....
}
```

**Comment by weiming-myob** [comment]
@dylanlive thanks for the info, I am going to try 3.8.1.

**Comment by weiming-myob** [comment]
It seems working locally for MacOS and Windows, verifying linux on AWS.

**Comment by weiming-myob** [comment]
Honestly, I think this 503 server error happens intermittently regardless which version of selenium server standalone you are downing today. Because I tried to download 3.4.0, it happened first time, and then worked, and them broken again. :(

**Comment by barancev** [comment]
If google storage is flaky these days we hardly can do anything. Let's hope google will fix this issue.

**Comment by weiming-myob** [comment]
Really?! This ticked is closed just like that? I would expect we could come up with a solution or external ticket if this is a dependency. Just did a quick google search, I wonder if this issue is related to [Google issue 2898](https://github.com/googleapis/google-cloud-dotnet/issues/2898)?

**Comment by cgoldberg** [comment]
>  I wonder if this issue is related to Google issue 2898?

seems unrelated.. the 503 comes from google when the cloud storage service is unavailable.

**Comment by dylanlive** [comment]
It is downloading for me now again using [this link](https://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.0.jar). I do know Google had some downtime issues yesterday that may have been related (although weird that it was just for a specific file).
