### ISSUE TITLE
ChromeDriver 74 out before actual Chrome 74 is out

### ISSUE THREAD

**Issue by flisowski** [SeleniumHQ/selenium#7028]
## 💬 Latest Chrome version 73* latest ChromeDriver version 74*

Forgive me if it's a silly question but how can we have the situation as described in the title? Since WebDriver manager gets latest version of ChromeDriver but there is no compatible Chrome out there yet, all tests fail.

**Comment by lmtierney** [comment]
WebDriver manager is not developed nor maintained by the Selenium team. Please raise an issue with them
