### ISSUE TITLE
where the output gets stored when building a jar for selenium using ./go selenium-server-standalone.

### ISSUE THREAD

**Issue by pankajsethi93** [SeleniumHQ/selenium#7029]
So I have cloned the selenium directory and make the build for jar using command ./go selenium-server-standalone ..
It got build but I am wandering where the output is stored. I read in the documentation that using ./go command gives a toplevel "build" directory and the output is stored in it. But in my case, no build directory is generated. But yes one "buck-out" directory is generated and I can find a jar output in the path /gen/java/server/src/org/openqa/grid/selenium/selenium.jar.
So is it the correct output?

**Comment by diemol** [comment]
https://github.com/SeleniumHQ/selenium/issues/6961#issuecomment-472770739

**Comment by pankajsethi93** [comment]
Thanks @diemol
