### ISSUE TITLE
Need `addCustomRequestHeaders` capabilities for ChromeOptions to handle basic auth popup

### ISSUE THREAD

**Issue by mkvidyarthi** [SeleniumHQ/selenium#7033]

**Comment by jimevans** [comment]
Help me understand how that would help? Has chromedriver implemented a feature that allows it to send additional headers with each request by specifying a capability? If so, this is the first I’m hearing of it, and you can ise addExpeimental

**Comment by mkvidyarthi** [comment]
I wanted to do somthing like this, selenium.addCustomRequestHeader( "Authorization","Basic "UIgkjdjdoiuoqweroUF"), it will authenticate session and then I can proceed further to test application.

But that's all sorted without it. I've passed credentials in URL https://<username>:<password>@<url> and the thing I was missing is options.setAcceptInsecureCerts(true); Adding insecure certs option true helped me to proceed futher.
