### ISSUE TITLE
Unable to switch back to main page after switching to the iframe once

### ISSUE THREAD

**Issue by nitingupta220** [SeleniumHQ/selenium#7034]
I have an HTML structure like this: - 
```
<html>
    <title>Demo</title>
    <body>
        <div>
            <p>Hello World</p>
            <button>Press me</button>
            <iframe id="iframe">
                  <textarea class='body'></textarea>
            </iframe>
         </div>
     </body>
</html>
```
I'm using selenium-webdriver with nodejs.
I want to swtich to Iframe and type in the textarea and then want to go back to the div and press the button which is outside the iframe.

I'm able to switch back to the iframe by following code: - 
```
const frame = await driver.findElement(By.css('#iframe'));
await driver.wait(until.ableToSwitchToFrame(frame));
const body = await driver.findElement(By.css('.body'));
```

Now I want to go back to the parent div and wanted to press the button but I won't be able to do that.

I have used this:  -
``` await driver.switchTo().defaultContent();```
And this
``` await driver.switchTo().parentFrame();```

But both didn't work. Can anyone help? @virenv @barancev  

P.S: - I'm using node js selenium-webdriver package.

**Comment by virenv** [comment]
@nitingupta220 : I am sorry, I am not well versed with JavaScript. I tried the same scenario in Java and it works perfectly fine. I think a JavaScript binding expert will be able to help you out here.

**Comment by nitingupta220** [comment]
Thanks, @virenv  for the reply.
Do you know in the community who will be able to help me with that issue?

**Comment by rapidroamer** [comment]
Hi Nitin,
Are we able to click the button in the first place ( even before going to the iframe). Just want to confirm we are not dealing with selector issue for the button.

**Comment by diemol** [comment]
Hi @nitingupta220 

Thanks for posting this question, nevertheless, this is not a forum for support or to ask questions. I'd recommend to send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by nitingupta220** [comment]
> Hi Nitin,
> Are we able to click the button in the first place ( even before going to the iframe). Just want to confirm we are not dealing with selector issue for the button.

Hello Vijay,
Yes, we are able to click on the button at the first place. This thing is happening when we switch to the iframe.

**Comment by nitingupta220** [comment]
> Hi @nitingupta220
> 
> Thanks for posting this question, nevertheless, this is not a forum for support or to ask questions. I'd recommend to send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

Hello @diemol I'm not posting any question. I tried one thing and found that this might be an issue with the Javascript version of Selenium.

**Comment by diemol** [comment]
@nitingupta220 sorry if I didn't get that...

Then, I'd like to point out that we have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? When possible, please provide the information requested in the original template, together with a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by nitingupta220** [comment]
@diemol Sorry if I break the rules.
But I didn't know what are the issue templates?
Can you tell me some example so that I can draft my issue request similar to that issue template?

**Comment by diemol** [comment]
No worries @nitingupta220, it is not really about the rules but more about the community, providing enough information helps the maintainers and collaborators understand the issue, and it also helps other people to identify if they have the same issue.

When you create a new issue, you end up in this page:
![image](https://user-images.githubusercontent.com/5992658/54992959-fe48a680-4fc0-11e9-9458-3f528ba6f98a.png)

and when you select "Bug Report", there are several fields we expect to be filled out:
![image](https://user-images.githubusercontent.com/5992658/54993013-1e786580-4fc1-11e9-8c51-ff1ca89c602e.png)
which should include a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
