### ISSUE TITLE
Unknown error, Unable to receive message from renderer

### ISSUE THREAD

**Issue by bitswarming** [SeleniumHQ/selenium#704]
I'm  struggling with the following issue.
I believe this is fundamental webdriver's issue. And doesn't depends on firefox/chrome version or even webdriver verison.

Here are steps to reproduce this problem on unix. But it can be easily done on any platform.

1) Launch browser, e.g. firefox, via webdriver. (any language binding request or even curl, if you can).

2) Get website url via webdriver. Assuming webserver has SINGLE url (easier to block with iptables rule)

3) Send simple execute_script command to webdriver. e.g. "return document.location.href" - it works. 

4) Now turn browser in  "toooo looooong page loading mode". This is typical situation in real world for example 
slow internet connection or webserver fail. Assuming browser still launched.
To simulate this situation run in new termial command like 
sudo iptables -A  INPUT -s x.x.x.x   -j DROP 
(where x.x.x.x is webservers ip from step 2). this blocks website.

5) Test again.  Send simple execute_script command to webdriver. e.g. "return document.location.href" - it works. 

6) Now refresh page. Just click browsers "refresh" button, or f5. page is loading for a  long time . and can't load.

While its loading you can execute "document.location.href" via developer console or firebug - it works. Actually DOM hasn't changed.
But if you send again   execute_script  "return document.location.href"  via  webdriver - failed with "unable to receive message from renderer" 
and unknown error. It should be mentioned that selenium rc works well in this situation and returns correct response.  Selemium rc is not affected by this issue.

7) You can flush iptables with "sudo iptables -F"

So it makes my project to move back to selenium rc or build my own patched version of webdriver ^(

**Comment by barancev** [comment]
The exception "unable to receive message from renderer" is generated by chromedriver, please report this issue to the chromedriver tracker: https://sites.google.com/a/chromium.org/chromedriver/help

And what exception is generated by FirefoxDriver?

**Comment by barancev** [comment]
Closing the issue as there is no responce from the author for long time.

**Comment by skptricks** [comment]
It causes because page took long time to load , you need add additional line to your chromedriver option. Please refer the below link for more information : 
[Timed out receiving message from renderer in selenium](https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html)

**Comment by cgoldberg** [comment]
@skptricks I'm deleting all of your spammy responses.  The solution they provide is also not correct .
