### ISSUE TITLE
NoSuchFrameError raised after clicking on div that opens a new window on Safari

### ISSUE THREAD

**Issue by JasonLunn** [SeleniumHQ/selenium#7044]
## 🐛 Bug Report

Invoking `click` on an element located within an iFrame that has an onclick handler that opens a new window opens the new window but returns a "No Such Frame" error on Safari. Works fine on Chrome and FireFox.

Cross-posted with Apple Bug Reporter \#49027480

## To Reproduce

Given two simple HTML pages:

`Parent.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parent</title>
</head>
<body>
<iframe src="ClickMe.html"></iframe>
</body>
</html>
```

and `ClickMe.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Click Me</title>
</head>
<body>
<div onclick="var new_window = window.open(); new_window.document.location.href = 'https://www.google.com/';">Broken</div>
</body>
</html>
```

Detailed steps to reproduce the behavior:

## Expected behavior

Expected server to return no error since the click was successful and the new window was opened.

## Test script or set of commands reproducing this issue

The following script will open a window but will raise a `Selenium::WebDriver::Error::NoSuchFrameError`:
```ruby
require 'selenium-webdriver'
d = Selenium::WebDriver.safari
d.navigate.to 'https://yourhost.example.com/Parent.html'
d.switch_to.frame 0
d.find_element( css: 'div' ).click
```

## Environment

OS: OSX High Sierra 10.13.6 (17G5019)
Browser: Safari
Browser version: 12.0.3 (13606.4.5.3.1)
Browser Driver version: N/A (provided by OS)
Language Bindings version: JRuby selenium-webdriver (3.141.0)

**Comment by lmtierney** [comment]
Please log any Safari issue with Apple: https://bugreport.apple.com/
