### ISSUE TITLE
Add multiline copy/past

### ISSUE THREAD

**Issue by adrien-bertrand** [SeleniumHQ/selenium#7047]
Hi, 
if its possible to add this feature 
Thanks 

## 🚀 Feature Proposal

Allow to copy/paste some row to easily update scenarios using the same functions in different places. 

## Motivation

It's possible to do it using a code editor but i need to edit every "id" elements after.
yesterday  i had to copy 96 lines in a lot of tests.

**Comment by diemol** [comment]
@adrien-bertrand could you please suggest that feature in the IDE repo? https://github.com/SeleniumHQ/selenium-ide

**Comment by adrien-bertrand** [comment]
https://github.com/SeleniumHQ/selenium-ide/issues/630
