### ISSUE TITLE
Cannot Navigate to new window... OpenQA.Selenium.WebDriverException: unknown error: missing or invalid 'entry.level'

### ISSUE THREAD

**Issue by manbadalyan** [SeleniumHQ/selenium#7048]
## 🐛 Bug Report

Driver opens main URL, but when clicking login button chrome driver can't switch to or can't open directly URL. 

Throw an error 
Message: Cannot Navigate to new window... OpenQA.Selenium.WebDriverException: unknown error: missing or invalid 'entry.level'
  (Session info: chrome=73.0.3683.75)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.17134 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.get_Title()
   at TestInitalization.Initialization.get_Title() in C:\...\TestInitalization\Initialization.cs:line 58
   at TestInitalization.Initialization.ChangeBrowserTab() in C:\...\TestInitalization\Initialization.cs:line 70

## Test script or set of commands reproducing this issue
    public class JoinTestCasesSteps
    {
public JoinTestCasesSteps() => Driver = Initialization.GetDriver;
        public void OpenJoinTab()
        {
            page.Join.Click();
            log.Info("Clicking 'Join' Tab");
            Initialization.ChangeBrowserTab();

        }
}
           public class Initialization
    {

 public static void Init(string baseURL, string browser, int sec, string xmlpath, string stand)
        {

            _stopWatch = Stopwatch.StartNew();
            log.TestStart();

            switch (browser)
            {
                case "IE":
                    WebDriver = new InternetExplorerDriver();
                    break;
                case "Firefox":
                    WebDriver = new FirefoxDriver();                    
                    break;
                case "Edge":
                    WebDriver = new EdgeDriver();
                    break;
                default:                    
                    WebDriver = new ChromeDriver();
                    break;
            }
            ChangeBrowserTab();
            //WebDriver.Manage().Window.Maximize();
            Goto(baseURL, sec);
            UpdateXMLFile(xmlpath, browser, stand, baseURL);
        }
        public static IWebDriver GetDriver
        {
            get { return WebDriver; }
        }

        public static void ChangeBrowserTab()
        {
            try
            {
                GetDriver.SwitchTo().Window(GetDriver.WindowHandles.Last());
                string t = Title;
            }
            catch (Exception e)
            {
                Assert.Fail("Cannot Navigate to new window... " + e);
            }
        }
        public static void Goto(string url, int sec)
        {
            try
            {
                WebDriver.Navigate().GoToUrl(url);
                //WebDriver.Url = url;
                WebDriver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(sec);
            }
            catch (Exception e)
            {
                
                Assert.Fail("Cannot open URL" + e);
            }
        }
}

## Environment

OS: 
Browser: 
Browser version: <73.0.3683.75 (Official Build) (64-bit)>
Browser Driver version: <ChromeDriver 2.45>
Language Bindings version: <Nunit 3, C#> 
Selenium Grid version (if applicable): <3.141.0

**Comment by virenv** [comment]
@manbadalyan : It seems that you have copied your test code itself. Can you create a simple test which can reproduce the problem and add that instead of this code?

**Comment by diemol** [comment]
@manbadalyan 
The log shows that you are using a version of Chrome not compatible with the version of ChromeDriver
```
(Session info: chrome=73.0.3683.75)
(Driver info: chromedriver=2.29.461591 
```

Please update it according to http://chromedriver.chromium.org/downloads

After updating, if the issue still persists, feel free to reopen and provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).
