### ISSUE TITLE
Unable to click on elements Selenium version 3.141.59

### ISSUE THREAD

**Issue by pranger8709** [SeleniumHQ/selenium#7049]
I have recently updated Selenium and ChromeDriver and now my automation fails to click on elements. I tried down grading Selenium and ChromeDriver to resolve  the issue but it didn't. I think it might have something to do with the version of Chrome I am using (73.0.3683.75). I haven't submitted a bug with Chrome yet as I want to see if there is a work around. I have tried adding a delay before the click and the javascriptexecutor and both do not work,

Since actions have been depreciated is there another way to perform the same behavior?

**Comment by cgoldberg** [comment]
please fill out the template when submitting an issue
