### ISSUE TITLE
Set the 'value' of an Element

### ISSUE THREAD

**Issue by GerhardKreuzer** [SeleniumHQ/selenium#7055]
Hi
I have this nive element:
<input name="ConsultationSearchForm:StartDate" tabindex="3" class="textField" id="ConsultationSearchForm:StartDate" onkeypress="return signalEnterOnText(event)" type="text" size="10" maxlength="10" value="24.03.2019">

Now I have to change 'value', but there is no accessible function on the object I get back by searching .FindElement(By.Id("ConsultationSearchForm:StartDate"))

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
.. ah, code disappeared. ????????????????????
<input name="ConsultationSearchForm:StartDate" tabindex="3" class="textField" id="ConsultationSearchForm:StartDate" onkeypress="return signalEnterOnText(event)" type="text" size="10" maxlength="10" value="24.03.2019">

**Comment by GerhardKreuzer** [comment]
Aha, no Chance to post a code snippet ..
Leads to the nect question, how can I post code snippets here?

**Comment by jimevans** [comment]
@GerhardKreuzer The .NET bindings follow the Java bindings’ pattern of using role-based interfaces for certain items. To change the `value` attribute of an element, you’ll need to use JavaScript, and in the .NET bindings, that means [casting your driver to `IJavaScriptExecutor`](https://stackoverflow.com/questions/6229769/execute-javascript-using-selenium-webdriver-in-c-sharp/6285793). The code for that would look something like the following:

    // WARNING! Below code written from memory
    // without the benefit of an IDE. It may not run
    // properly or even compile without modification.
    // The below code also deliberately uses a more
    // verbose style of C# than many people are
    // used to so as to show the steps more clearly.
    // Assume "driver" is a valid IWebDriver and
    // "element" is a valid IWebElement
    //
    // Use the `as` operator to avoid double-casting for type correctness.
    // Type correctness check omitted for brevity.
    IJavaScriptExecutor executor = driver as IJavaScriptExecutor;

    // JavaScript uses the `arguments` array to
    // pass parameters into the JavaScript executed
    // in the browser, and we pass our element reference
    // that way.
    executor.ExecuteScript("arguments[0].setAttribute('value', '<your value>')", element);

I will note that this forum isn’t the best place to get support-style questions answered, and opening issues like this in the future are likely to be closed without getting you the help you want. I can suggest the user-facing mailing list

**Comment by diemol** [comment]
@GerhardKreuzer
As mentioned above, this is not a support/help forum, it is a place to report bugs/issues. To get more answers please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well. Remember to provide enough information.
