### ISSUE TITLE
FirefoxDriver cannot set the path on a hidden fileupload input

### ISSUE THREAD

**Issue by zenlambda** [SeleniumHQ/selenium#706]
I tried to implement a file upload test with [nightwatchjs](/nightwatchjs/nightwatch) but I couldn't set the path of an invisible 'fileupload' form input. (The file upload is initiated by the user with a visible label, although this is not clicked by the test because we want to avoid platform specific dialogs). This appears to be an issue with the Firefox only, the test works fine in Chrome.

The nightwatch devs claim this is an issue with the Firefox driver.

The original nightwatch bug report was nightwatchjs/nightwatch#505 .

**Comment by zenlambda** [comment]
I reproduced this on selenium server 2.45 and 2.46.

**Comment by ddavison** [comment]
the point of Selenium is to automate web applications just as a user would.. how would the user upload the file if the form field is invisible?

**Comment by zenlambda** [comment]
@ddavison The input element is invisible but the label is not. The user can see and click on the label, initiating the native file chooser.

**Comment by ddavison** [comment]
if that's the case, why don't you use the JavaScriptExecutor to force the value?  I personally don't believe that Selenium *should* be able to interact with invisible elements, but other people in the org may differ

**Comment by barancev** [comment]
Yes, this is a legit issue, but we need an exact reproduction scenario because of various meanings of "hidden".

**Comment by barancev** [comment]
For example, this sample works well for me:

```WebDriver driver = new FirefoxDriver();
driver.get("http://blueimp.github.io/jQuery-File-Upload/basic.html");
WebElement input = driver.findElement(By.id("fileupload"));
input.sendKeys("C:\\temp\\image.png");```

Is it "hidden enough"? :)

**Comment by zenlambda** [comment]
@barancev You're right 'my kind' of invisible is different:

Here is a [plunkr](http://plnkr.co/edit/N2jnixIyyjy1gIo2UhzT?p=preview) ( [embedded view](http://embed.plnkr.co/N2jnixIyyjy1gIo2UhzT/preview) ):

In this case the input is surrounded by a zero sized div, (I also think using simple display: none; made no difference - Firefox test still wouldn't work).


I don't have a direct selenium API reproducer but here is a Nightwatch one to illustrate: 
```
var path = require('path');
var testFilePath = path.resolve(
    path.join(__dirname, '../../../tests/data/test.csv'));

module.exports = {
    "Test Fiddle": function(browser) {
        console.log(require('fs').existsSync(testFilePath));

        browser.url("http://run.plnkr.co/plunks/N2jnixIyyjy1gIo2UhzT/")
            // url ripped from the iframe src on the plunkr 'embedded' view
        .pause(1000)

        .setValue('#invisible_input', testFilePath)
        .waitForElementPresent('#result', 2000)

        .end();

    }
};
```

**Comment by jleyba** [comment]
You could try using JS to make the element visible so you can manipulate it.
Something like:

```
WebElement el = driver.findElement(By.cssSelector("div > div"));
driver.executeScript("arguments[0].style.height=1; arguments[0].style.width=1", el);
driver.findElement(By.id("invisible_input")).sendKeys(testFilePath);
driver.executeScript("arguments[0].style.height=0; arguments[0].style.width=0", el);
```

**Comment by alb-i986** [comment]
+1

In our case, we have an input file element that is invisible because it has as css property top = -1000.

The javascript
```
document.getElementById('passport-photo').style.top = '0px';
```
does the trick, but I think that WebElement#sendKeys should not expect input file elements to be visible, since it's not a standard "type text in text field" thing.

Thanks
