### ISSUE TITLE
Manual HTTP calls for browser navigation

### ISSUE THREAD

**Issue by adiohana** [SeleniumHQ/selenium#7063]
## 🚀 Feature Proposal
Add manual HTTP calls (GET,POST,etc.) to RemoteWebDriver interface.

## Motivation
Currently, RemoteWebDriver has "browser" navigation utils - click, get, refresh, back, etc.
Sometimes, there are cases we want to navigate to a page and display the response in browser view using manual HTTP calls (GET,POST,etc.) in order to improve performance or simulate a test case.

## Example
driver.httpRequest(POST, body, headers, additionalParams);

I already have an implementation for that in my "selenium sdk" I am using on top of remote web driver interface. It is mainly using javascript executions and localStorage for async use cases.

**Comment by diemol** [comment]
@adiohana 
Could you please elaborate more? Perhaps show some code? Maybe I am not understanding, but that looks like an HTTP Client, right? If so, why mixing things?

**Comment by barancev** [comment]
Why should it be proxied through Selenium? How is it better than using an HTTP client to send HTTP requests to the target server?

**Comment by adiohana** [comment]
The idea is to have the ability to perform manual http requests inside the browser context. This will be faster than perform regular browser actions such as clicks and navigation.
We can use the java http client but then we will need to sync the http session between the browser and the http client which will be an overhead.

I will add some code examples later on, the idea is to use JavaScript Ajax inside the browser context.

**Comment by adiohana** [comment]
@diemol any input about this? Is it worth to add it to web driver API?

**Comment by diemol** [comment]
I personally think that this type of feature does not belong to Selenium, I would do it in a framework that leverages the power of the two worlds, something like https://github.com/tryolabs/requestium

**Comment by cgoldberg** [comment]
agreed this doesn't belong

**Comment by barancev** [comment]
I agree that it's an extension responsibility, there is no need to add this feature to the core API.
