### ISSUE TITLE
Save and Restore http sessions

### ISSUE THREAD

**Issue by adiohana** [SeleniumHQ/selenium#7064]
## 🚀 Feature Proposal
Add Save/Restore http session as a feature for RemoteWebDriver.

## Motivation
There are use cases where we want to simulate user's session without login - Verify that we have the correct cookies and allow the user to use the session as long as it is active.

## Example
1. Creating RemoteWebDriver and execute login
2. Before terminating the Driver session, call driver.saveSession() - this will take relevant cookies for the session and return it as a Map.
3. driver.quite()
4. Create a new RemoteWebDriver instance
5. call driver.restoreSession(Map) in order to "restore" the previous session. Another approach for this will be to add the map in capabilities when creating the RemoteWebDriver

**Comment by adiohana** [comment]
@barancev 
do you think it worth start working on it? I have this implementation in my selenium SDK and I can adopt it easily. Do you think it can be in Selenium 3.X.X ?

**Comment by barancev** [comment]
Yes, it might be a usable feature, but I'm not sure it should be a part of Core Selenium API. Big chance we'll leave this to be implemented in extensions.

**Comment by adiohana** [comment]
can you elaborate more about the "extensions"? is there any example?

**Comment by barancev** [comment]
Watir, Nerodia, Selenide, JDI, ...

**Comment by rapidroamer** [comment]
Hi @adiohana ,
Please check if the below can help in the mean time:
https://www.guru99.com/handling-cookies-selenium-webdriver.html
The linked webpage has code snippets to export cookies and reload them in the next session. The only bug in the snippet is that it tries to set cookies before loading any url, and it will fail. you can use the snippets after removing the bug.

**Comment by adiohana** [comment]
Thanks.
I already implemented it. I was thinking about open contribution of this feature.

**Comment by evgenybf** [comment]
I believe that having this feature would be a great help.
A page may contain iframe that may keep their own cookies. The worse thing is that the iframes may be controlled by a JS code and already disappear at the time when driver.Quit() is called. 
Another issue with the manual cookie management is that you always need to check the domain.

**Comment by diemol** [comment]
@adiohana, as mentioned above, an extension is more suitable for this than actually implementing it in the core project. If you already implemented it, let us know and if you'd like, this can be added as one of the ecosystem [projects](https://www.selenium.dev/ecosystem/). Feel free to create a PR to our website and we can have it there.
