### ISSUE TITLE
Keep getting "Failed to navigate to .... This usually means that a call to the COM method IWebBrowser2::Navigate2() failed."

### ISSUE THREAD

**Issue by etoperman** [SeleniumHQ/selenium#7068]
I'm using IE11 on Window Server 2012 r2.
IEDriver version is 3.141.5
I did  setup per https://support.leapwork.com/hc/en-us/articles/115001195111-Configuration-required-for-running-tests-on-Internet-Explorer-IE-
I'm keep getting "Failed to navigate to .... This usually means that a call to the COM method IWebBrowser2::Navigate2() failed."

**Comment by cgoldberg** [comment]
please provide more info.. including: steps to reproduce, example code you are running, and the full error message

**Comment by etoperman** [comment]
Hi Corey, Diego and Alexei!
Good news - after I updated IEDriverServer to:
    <package id="Selenium.WebDriver.IEDriver" version="3.141.59" targetFramework="net472" />
CPU is not jumping up to 100% and never going down, and all these troubles seems fixed.
Again: it's Windows 2012 R2 and I did normal setup per https://support.leapwork.com/hc/en-us/articles/115001195111-Configuration-required-for-running-tests-on-Internet-Explorer-IE-
Thank you guys, I'll keep you in a circle, Evgeniy

**Comment by gssanthosh12** [comment]
I am getting the same Error in IE X64 Driver
when I tried to handle the Authentication pop  in Selenium - WebDriver
this issue Occured.

DesiredCapabilities Capabilities = DesiredCapabilities.internetExplorer();
		Capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
		
		System.setProperty("webdriver.ie.driver","C:\\Selenium\\IE Driver\\IEDriverServer.exe");
				
		WebDriver driver=new InternetExplorerDriver();	
driver.get("https://username:password@url");

**Comment by karlareyes16** [comment]
@gssanthosh12 , have you found the fix for your issue above? Hope you can share it. Thanks
