### ISSUE TITLE
python selenium chrome yields wrong keys on send_keys

### ISSUE THREAD

**Issue by thestick613** [SeleniumHQ/selenium#707]
I've been running some tests on a remote ubuntu machine and i found a weird bug.
If i try to send any of these keys `%/?^56` to an input, using `send_keys`, they don't get there.

    5 creates a backspace
    6 creates a Shift+Tab
    ^ creates a Tab
    % creates a backspace
    ? creates a Enter

Software versions are:

    Selenium is 2.46.0
    Chrome is 43.0.2357.81 Ubuntu 14.04 (64-bit)
    ChromeDriver is 2.15.322488

I'm running all of this in a tightvncserver, with fluxbox. Same thing on Firefox works ok.

I later upgraded Chrome to 44.0 and Chromedriver to 2.16, but the issue still persists in some way. The list of wrongly printed keys gets reduced to `%/?5`.  How can i investigate this further? I've turned on logging to DEBUG level, and everything seems ok.

**Comment by lukeis** [comment]
please log chromedriver bugs with the chromedriver project:

https://code.google.com/p/chromedriver/issues/list

Further questions should be directed to the Selenium User Group:
https://groups.google.com/forum/#!forum/selenium-users
