### ISSUE TITLE
not filled input with type= number in chrom version 73

### ISSUE THREAD

**Issue by MasoumehEbhami** [SeleniumHQ/selenium#7071]
## 🐛 Bug Report

recently for function testing i installed selenium plugin on Chrome version 73. in test excute i founded that selenium did not fill inputs with type=number. after changing type to text every thing worked perfectly.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Win 10
Browser: Chrome
Browser version: Version 73.0.3683.86 (Offizieller Build) (64-Bit)
Browser Driver version: 
Language Bindings version:  
Selenium IDE version (if applicable): 3.5.8

**Comment by barancev** [comment]
Issue moved to [SeleniumHQ/selenium-ide #635](https://github.com/SeleniumHQ/selenium-ide/issues/635) via [**ZenHub**](https://www.zenhub.com/)
