### ISSUE TITLE
Webdriver3.14 hits Firewall where as in lower version of Webdriver, traffic goes via proxy

### ISSUE THREAD

**Issue by kniranjan4333** [SeleniumHQ/selenium#7076]
While troubleshooting on Webdriver we found that while running a webdriver3.14 few traffic hits proxy and one of its traffic hits a Firewall where as in lower version of Webdriver, it does not hit firewall and all its traffic goes via proxy properly. As lower version works well with proxy so new version should also have an option to use proxy for its connections

When i have tried running selenium code on browserstack server with older version of webdriver then it works fine but when tried running with latest version of webdriver3.141 then it throws an exception shown below :

Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 207.254.8.3:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

Please help me with this issue in order to run our script on browserstack.

**Comment by diemol** [comment]
Hi @kniranjan4333 

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

**Comment by kniranjan4333** [comment]
> Hi @kniranjan4333
> 
> This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.

I don't have permission to above group **selenium user group** to post my query
![image](https://user-images.githubusercontent.com/23027775/55323423-91288b80-546e-11e9-8b3e-c1c724e6e947.png)

**Comment by diemol** [comment]
There are no restrictions to post there, please make sure you are logged in. Also try to post a message much more descriptive, if you plan to post the same text as above, you will likely not get any answers.
