### ISSUE TITLE
30s Idle time between 2 handlers

### ISSUE THREAD

**Issue by mengyingdu** [SeleniumHQ/selenium#7078]
##  30s Idle time between 2 handlers

Hi , I integrated selenium with our app. However, there always 30s idle time between 'begin session service' and 'ServicedSession' This is the screenshot for it: 10:40:59.696 ---> 10:41:35.282

I also observed it in our recorder video (that is another process after test running)
What is remote driver doing during this 30s? 
Context: I am working on improving test automation performance now.
![Screen Shot 2019-04-01 at 9 40 32 AM](https://user-images.githubusercontent.com/24535640/55344669-ce871c00-5462-11e9-8ee1-830aa6f16bb0.png)

Thank you.

**Comment by cgoldberg** [comment]
This is the tracker for Selenium issues.  Please post general questions to the [**selenium-users**](https://groups.google.com/forum/#!forum/selenium-users) mailing list.
