### ISSUE TITLE
selenium.common.exceptions.JavascriptException

### ISSUE THREAD

**Issue by jydd** [SeleniumHQ/selenium#7079]
```selenium.common.exceptions.JavascriptException: Message: javascript error: Failed to construct 'Touch': member target is not of type EventTarget.```

from selenium.webdriver.common.touch_actions import TouchActions

TouchActions(driver).flick_element(element, 0, -200, 50).perform()

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
This issue can be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1543337

**Comment by lmtierney** [comment]
Closing due to lack of response
