### ISSUE TITLE
Calling Action second time in the page- No action takes place on the page for Firefox browser

### ISSUE THREAD

**Issue by ravimidathala** [SeleniumHQ/selenium#7081]
## 🐛 Bug Report

I'm trying to hover the mouse using Action on the navigation tabs on the webpage to reveal the dropdown with links. It works perfectly for the first time. When trying to again mouse over to click on an another link in the navigation tab's dropdown, the dropdown just doesn't open.

## Steps to reproduce: 
Hover the mouse on the navigation menu --> Click on a link in the menu --> Again hover the mouse on the navigation menu --> Click on another link in the menu

## Expected Behaviour: 
The Action should work for the second time too and should click on the link in the menu.

No error after performing Action for the second time:
1554278436604	Marionette	DEBUG	0 <- [1,74,null,{"value":null}]
1554278436682	Marionette	DEBUG	0 -> [0,75,"WebDriver:FindElements",{"using":"link text","value":"Charcoal Grills"}]
1554278470912	Marionette	DEBUG	0 <- [1,75,null,[]]
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.linkText: Charcoal Grills (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:81)

OS: Windows 10
Browser: Firefox
Browser version: 66.0.2
Browser Driver version: GeckoDriver 0.21 to GeckoDriver 0.24
Selenium version: 3.141.59

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by vinits91** [comment]
I am also facing the same issue while clicking on menu dropdown 2nd time with Action, with latest standalone Firefox image Neon.  any help is appreciated. Thank you.

**Comment by diemol** [comment]
Closing as we didn't get any more replies from the OP.
