### ISSUE TITLE
DesiredCapabilities still uses deprecated feature PLATFORM

### ISSUE THREAD

**Issue by ZozoZoeLi** [SeleniumHQ/selenium#7083]
## 🐛 Bug Report

The DesireCapabilities class still uses CapabilityType.PLATFORM which is deprecated, instead of CapabilityType.PLATFORM. This is inconsistent and at a certain point, we have to set up both capabilities making sure they're all passed in. We're also not sure the intention of why PLATFORM is @deprecated. 

Detailed steps to reproduce the behavior:

## Expected behavior

When setting up something alike capabilities.put("platformName", "iOS"), it should be passed correctly in DesiredCapabilities.

**Comment by ZozoZoeLi** [comment]
I've raised a PR https://github.com/SeleniumHQ/selenium/pull/7082.

**Comment by shs96c** [comment]
You're correct that the capabilities are currently using the deprecated "platform" key. This has been to ensure we preserve some level of backwards compatibility --- someone can use the latest version of the selenium client jars to communicate with older selenium servers successfully.

The new approach we're encouraging people to follow is to use the `*Option` classes to set things up. These don't set the platform at all, and so avoid this issue entirely.

I'd love to hear your opinion about the best way to proceed. For backwards compatibility, it may be best to leave things as they are (especially if we push `DesiredCapabilities` into a "legacy JSON Wire Protocol" jar. For the sake of code cleanliness, it's better to clean it. What do you think is the best thing to do?

**Comment by ZozoZoeLi** [comment]
Really sorry for the late reply. Checking this ancient PR https://github.com/SeleniumHQ/selenium/pull/7082/commits/c43e2528c0fe8e361502fb8a4fca51304926639c, instead of completely replacing it, maybe we can keep it both so people could pass this capability with either key?

**Comment by titusfortner** [comment]
we're going to err on the side of backwards compatibility still until we can remove all of the non-W3C code.
