### ISSUE TITLE
[Ruby] `element.get_text` ignore rlm symbol

### ISSUE THREAD

**Issue by ShockwaveNN** [SeleniumHQ/selenium#7085]
## 🐛 Bug Report

If element contains text with [RLM](https://unicode-table.com/en/200F/) symbol `element.text` will return only text, without that symbol

## To Reproduce

1. Create `/tmp/rtl_symbol.html` as shown below
2. Run `tmp.rb`

## Expected behavior
outputs
```
true
true
```
## Test script or set of commands reproducing this issue

```
cat /tmp/rtl_symbol.html

<html>
<body>
<div>Test‏</div> <!-- https://unicode-table.com/en/200F/ symbol in end of Test string -->
</body>
</html>
```
tmp.rb
```
require 'selenium-webdriver'
driver = Selenium::WebDriver.for :chrome
driver.navigate.to('file:////tmp/rtl_symbol.html')
div = driver.find_element(:xpath, '//div')
puts div.text.include?('Test')
puts div.text.include?('‏') # https://unicode-table.com/en/200F/ symbol in quotes
```
returns
```
true
false
```

Also this symbol is visible in Chrome Debuuger
![image](https://user-images.githubusercontent.com/668524/55551505-a4905c80-56e3-11e9-95be-2e15435f8b3c.png)

## Environment

OS: Ubuntu 18.04
Browser: Chrome
Browser version: Version 73.0.3683.86 (Official Build) (64-bit)
Browser Driver version: 73.0.3683.20
Language Bindings version: selenium-webdriver (3.141.0)

**Comment by twalpole** [comment]
I'm 99% sure this is as designed - The intention of `text` is intended to return the text "as rendered" - https://w3c.github.io/webdriver/#get-element-text - and since the `rlm` character is a non-printing character (not rendered) it is not include in the return from `text`

**Comment by twalpole** [comment]
And https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/dom.js#L1151 is where it's intentionally removed.

**Comment by titusfortner** [comment]
Yes, it should return only what is displayed. Watir created `#text_content` and `#inner_html` methods (implemented based on the atoms) to provide the information as it is found in the DOM. @twalpole I'm assuming Capybara does something similar? It doesn't look like other Selenium bindings implement those methods either, but I'm seeing references in the Java test code to being able to do: `driver.findElement(By.id("wrappingtext")).getAttribute("innerHTML");` which I haven't tried.

**Comment by twalpole** [comment]
In Capybara and in raw selenium-webdriver you can do `div[:innerHTML]` to get the info in the DOM
