### ISSUE TITLE
ChromeDriver crashes in Windows

### ISSUE THREAD

**Issue by skAutomation12** [SeleniumHQ/selenium#7086]
My code reads ChromeDriver from Project level yet; the chrome halfway through the suite it tries to pick driver from the C:\\ or local folder and crashes. 
Here chrome is starting from local folder rather Project folder. I did point the chrome location in my project folder using System.getProperty("user.dir") in Java. 
`System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "//Drivers//chromedriver.exe");
                ChromeOptions options = new ChromeOptions();
                options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
                options.setExperimentalOption("useAutomationExtension", false);
                options.addArguments("--disable-web-security", "--headless","enable-automation","--disable-gpu",
                        "--test-type","--disable-browser-side-navigation","--disable-infobars","--disable-hang-monitor",
"--incognito","start-maximized","--disable-dev-shm-usage","--no-sandbox","--ignore-certificate-errors");
                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.setCapability(ChromeOptions.CAPABILITY, options);
                driver = new ChromeDriver(options);`

 

> C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 

> os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'

![ChromeCrash](https://user-images.githubusercontent.com/43443475/55571004-430fc400-56ca-11e9-9ef3-09de59709e73.PNG)

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver

**Comment by skAutomation12** [comment]
Thank you.
