### ISSUE TITLE
protractor is not stable to handle hidden pop up in virtual machine for some times

### ISSUE THREAD

**Issue by dhanraj002** [SeleniumHQ/selenium#7087]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by lmtierney** [comment]
Please raise an issue with the Protractor team
