### ISSUE TITLE
How to simulate touch tap?

### ISSUE THREAD

**Issue by Linch1** [SeleniumHQ/selenium#7088]
**Environment**
OS:  Windows 10
Browser: Firefox
Browser version:  66.0.2 (32 bit)
gekodriver version: 0.24.0
Working with Python3

**Problem**
I'm trying to simulate a touch tap with selenium, this is the interested portion of the code that i wrote for this work 
```
elem = driver.find_element_by_css_selector(".qJfNm")
touch = TouchActions(driver)
touch.tap(elem).perform()
```

but it raise this error and i don't understand why, i don't know if is my pc/code problem or something else
```
Traceback (most recent call last):
  File "C:/Users/mcara/OneDrive/Desktop/instagram bot mobile/instagram_bot_mobile.py", line 63, in <module>
    touch.tap(elem).perform()
  File "C:\Users\mcara\PycharmProjects\1\venv\lib\site-packages\selenium\webdriver\common\touch_actions.py", line 47, in perform
    action()
  File "C:\Users\mcara\PycharmProjects\1\venv\lib\site-packages\selenium\webdriver\common\touch_actions.py", line 57, in <lambda>
    Command.SINGLE_TAP, {'element': on_element.id}))
  File "C:\Users\mcara\PycharmProjects\1\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mcara\PycharmProjects\1\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: POST /session/11d3859a-4963-49d9-a143-b11d71fbfa8a/touch/click did not match a known command
```

I've found nothing online about this issue

**Comment by AutomatedTester** [comment]
What version of Selenium python client are you using?

**Comment by Linch1** [comment]
i've selenium 3.141.0

**Comment by netzulo** [comment]
Touch events are not working in Firefox currently (version 48.0.1) but it is possible to enable pointer events by browsing to ``about:config`` and setting **dom.w3c_pointer_events.enabled** to true

And... checking python code i can this https://github.com/SeleniumHQ/selenium/blob/11c25d75bd7ed22e6172d6a2a795a1d195fb0875/py/selenium/webdriver/common/touch_actions.py#L31-L40

This comment it's suspicious ``driver: The WebDriver instance which performs user actions. It should be with touchscreen enabled.`` , so...

#### Can you check if it's enabled ?

1. open firefox browser with selenium in python and stop it with something like ``import pdb; pdb.set_trace()``
2. access to your ``about:config`` url and keep looking for **dom.w3c_pointer_events.enabled**
2.1 if NOT , you must enabled first
2.2 if ENABLED , then i personally have more questions on my head after reading code but if come to this point, somebody should check code :)


#### Notes ( *not totally tested, please, carefull with this* )

- I can suppose your are using deprecated param name ``firefox_options`` or not value for param ``options``

https://github.com/SeleniumHQ/selenium/blob/87101da63a035eb398967334d2e1e55c0265c4ab/py/selenium/webdriver/firefox/webdriver.py#L110-L111

You should to use firefox options or profile from your code to enable option what you need it **if not enabled with last test**

**Comment by cgoldberg** [comment]
> Touch events are not working in Firefox currently (version 48.0.1)

@netzulo,
Firefox 48 is 3 years old and is not compatible with latest selenium.
The rest of your comments are incoherent.

**Comment by netzulo** [comment]
it isn't but np, just was wasting my own time trying to help , deleted my comment... thank you for your "words"

**Comment by barancev** [comment]
Python client uses legacy Actions protocol that is not implemented in geckodriver (and never will be). It should be fixed.

On the other hand, new W3C-conformant Actions protocol is not implemented too, watch https://bugzilla.mozilla.org/show_bug.cgi?id=1543337 for the status.
