### ISSUE TITLE
java.lang.NoSuchMethodError try to update from 3.0.1 to 3.141.59

### ISSUE THREAD

**Issue by Patatone** [SeleniumHQ/selenium#7089]
## 💥 Regression Report
In my project i removed the old dependece selenium-server-standalone-3.0.1.jar and i putted the new selenium-server-standalone-3.141.59.jar but i got this error:

`Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:146)
	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:44)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:187)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at X.Main.main(Main.java:24)
`

Line 24:
`WebDriver driver = new FirefoxDriver();`

![image](https://user-images.githubusercontent.com/34103646/55689455-dffd8600-5984-11e9-9e68-7b0be483f96f.png)

OS: Windows 10
Browser: Firefox
Browser version: 66.0.2
Browser Driver version: geckodriver 0.24.0
Language Bindings version: 
Selenium Grid version (if applicable): e.g.: 3.141.59

**Comment by barancev** [comment]
Please upgrade dependency on guava too.

**Comment by Patatone** [comment]
But I used the standalone version, i didn't import guava. The standalone version should include all required libs.

**Comment by barancev** [comment]
Please show your classpath settings (the list of all dependencies)

**Comment by Patatone** [comment]
@barancev 
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="lib" path="lib/jsoup-1.11.3.jar"/>
	<classpathentry kind="lib" path="lib/telegrambots-4.1-jar-with-dependencies.jar"/>
	<classpathentry kind="lib" path="lib/selenium-server-standalone-3.141.59.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by barancev** [comment]
It's possible that telegrambots-4.1-jar-with-dependencies.jar contains an outdated guava version.

This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by Patatone** [comment]
@barancev 
Solved with maven: https://github.com/rubenlagus/TelegramBots/issues/595
