### ISSUE TITLE
Webdriver hangs when perform click action on a webelement

### ISSUE THREAD

**Issue by Ankit9568** [SeleniumHQ/selenium#709]
Hello Team Member,

Webdriver hangs When performing click action 

Code :
{
FirefoxDriver driver = new FirefoxDriver();
driver.navigate().to("https://developer.mozilla.org/samples/domref/showModalDialog.html");
WebElement we = driver.findElement(By.cssSelector("input[type='button']"));
we.click();
System.out.println(" Click successful perform ");
}

After click show an pop up window shows in below image 

![issue with selenium](https://cloud.githubusercontent.com/assets/7448394/8351336/215b148c-1b4a-11e5-9faf-5e7093ee0cb4.png)

If user close a window [shows after click] manually than "click" action pass successfully and continue My test case  
 
Also I have  tried another way to handle this scenario 

Code{
FirefoxDriver driver = new FirefoxDriver();		driver.navigate().to("https://developer.mozilla.org/samples/domref/showModalDialog.html");
WebElement we = driver.findElement(By.cssSelector("input[type='button']"));
JavascriptExecutor executor = (JavascriptExecutor) driver;
executor.executeScript("arguments[0].click();", we);
System.out.println("click sucessfully ");
}

Environment 
OS:                                   -  Window 7 Ultimate [ service pack 1]
OS Architecture                -  32 - bit operating system
Selenium client version    -   Selenium 2.46
Browser version               -   Firefox 36

But same problem is exist, can any one help me how to handle above scenario
Any help will be greatly appreciated

**Comment by AJ-72** [comment]
I was able to replicate this issue in earlier versions as well. The problem is with window.showModalDialog(). If you change that to window.open the issue doesn't happen

@Ankit9568 showModalDialog is deprecated and will be dropped soon from firefox as mentioned here - https://developer.mozilla.org/en-US/docs/Web/API/Window/showModalDialog .

**Comment by Ankit9568** [comment]
Hi AJ-72,

Thanks for reply
Any workaround to handle mentation scenario with Selenium 

Any help will be welcomed

**Comment by tarlabs** [comment]
@Ankit9568, The problem is simple, you execute a function, which is a blocking call because of the modal dialog. The solution is to execute the call in a async fashion. For that javascript will be to your rescue

```java
JavascriptExecutor executor = (JavascriptExecutor) driver;
executor.executeScript("var elem=arguments[0]; setTimeout(function() {elem.click();}, 100)", we);
```

**Comment by Ankit9568** [comment]
Thanks tarlabs Issue has been resloved
