### ISSUE TITLE
The IE webdriver is stuck when failed to find id : :\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(911) Unable to find managed browser with id 

### ISSUE THREAD

**Issue by 150170410** [SeleniumHQ/selenium#7090]
## 🐛 Bug Report

The IE webdriver is stuck and no responding forever unless kill the script when closed a windows by press the customize button on the webpage. 

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Exception thrown or something that webdriver can catch 

## Test script or set of commands reproducing this issue
........
self.click_close_full_screen_button()
self.select_current_window()
........

IE webdriver capabilities 
            caps["ignoreProtectedModeSettings"] = 1
            caps["browserFocus"]= True
            caps["INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS"] = True
            caps['ignoreProtectedModeSettings'] = True
            caps["IntroduceInstabilityByIgnoringProtectedModeSettings"] = True
            caps["ignoreZoomSetting"] = True
            caps["nativeEvents"] = True
            caps["requireWindowFocus"] = True
            caps["unexpectedAlertBehaviour"] = "ignore"

ie.log:

T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\browser.cpp(56) Entering Browser::OnQuit
W 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\browser.cpp(58) This instance of Internet Explorer is exiting without an explicit request to close it. Unless you clicked a link that specifically attempts to close the page, that likely means a Protected Mode boundary has been crossed (either entering or exiting Protected Mode). It is highly likely that any subsequent commands to this driver instance will fail. THIS IS NOT A BUG IN THE IE DRIVER! Fix your code and/or browser configuration so that a Protected Mode boundary is not crossed.
T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\documenthost.cpp(277) Entering DocumentHost::PostQuitMessage
T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(295) Entering IECommandExecutor::OnBrowserQuit
T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(829) Entering IECommandExecutor::IsAlertActive
T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\browser.cpp(714) Entering Browser::GetActiveDialogWindowHandle
T 2019-04-08 11:15:39:100 c:\projects\webdriver\cpp\iedriver\browser.cpp(218) Entering Browser::GetContentWindowHandle
D 2019-04-08 11:15:39:101 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(843) No alert handle is found
T 2019-04-08 11:15:39:101 c:\projects\webdriver\cpp\iedriver\browser.cpp(312) Entering Browser::DetachEvents
T 2019-04-08 11:15:39:161 c:\projects\webdriver\cpp\iedriver\script.cpp(554) Entering Script::ConvertResultToJsonValue
T 2019-04-08 11:15:39:163 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(418) Entering IECommandExecutor::OnScriptWait
T 2019-04-08 11:15:39:163 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(890) Entering IECommandExecutor::GetCurrentBrowser
T 2019-04-08 11:15:39:163 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(896) Entering IECommandExecutor::GetManagedBrowser
W 2019-04-08 11:15:39:163 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(911) Unable to find managed browser with id 52cae60d-0ab7-45cf-a38f-e77b18f68e69

## Environment

OS: Window10 
Browser: IE 11
Browser version:11.1029.16299.0 
Browser Driver version: 3.14.0.0.(32 bit) 
Language Bindings version: Python 3 
Selenium Grid version (if applicable):

**Comment by jimevans** [comment]
I’m not entirely sure I understand the issue. Are there multiple browser windows open, and you’re closing one? You haven’t provided the Selenium calls contained in your wrapper code (`click_close_full_screen_button()` and `select_current_window()`) without that, it will be a little difficult to diagnose the issue.

I also notice that you’re attempting to ignore the Protected Mode settings of IE. This is _required_ for proper operation of the IE driver. Using the capability is a workaround, but is _**NOT**_ guaranteed to work.

**Comment by 150170410** [comment]
> I’m not entirely sure I understand the issue. Are there multiple browser windows open, and you’re closing one? You haven’t provided the Selenium calls contained in your wrapper code (`click_close_full_screen_button()` and `select_current_window()`) without that, it will be a little difficult to diagnose the issue.
> 
> I also notice that you’re attempting to ignore the Protected Mode settings of IE. This is _required_ for proper operation of the IE driver. Using the capability is a workaround, but is _**NOT**_ guaranteed to work.

**Comment by 150170410** [comment]
Sorry, closed the issue by accidentally clicked the wrong button. :-( 

First, thank jimevans for your helping.
Here is my codes pieces: 
........
exit_full_screen_icon = self.driver.find_element_by_id('id')
exit_full_screen_icon.click()

after this action, the log stopped at 
W 2019-04-08 11:15:39:163 c:\projects\webdriver\cpp\iedriver\iecommandexecutor.cpp(911) Unable to find managed browser with id 52cae60d-0ab7-45cf-a38f-e77b18f68e69


my next step is below and never go through 
self.driver.switch_to.window(self.driver.window_handles[0])
........

 Second, I did uncheck all protect mode options on IE11.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by 150170410** [comment]
It could be very difficult for me as the codes might need to work on with the testing object. I am not sure what to make a the test case working without testing object. Please advise.

**Comment by diemol** [comment]
If this is a question then please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
