### ISSUE TITLE
Generic Defaultwait does not works

### ISSUE THREAD

**Issue by Haxy89** [SeleniumHQ/selenium#7091]
```
public static bool WaitUntil(this IDriver driver, Func<IDriver, bool> condition, TimeSpan timeout)
        {
            var wait = new DefaultWait<IDriver>(driver)
            {
                Timeout = timeout
            };

            bool result = wait.Until(condition);

            if (!result)
            {
                throw new Exception();
            }

            return result;
        }
```

trying to use this extension method like this without success:

```
this.driver.WaitUntil(x => Menu != null && Menu.Displayed && Menu.Enabled, TimeSpan.FromSeconds(5));
```

**Comment by Haxy89** [comment]
@jimevans 
Thanks for respond.
Saying "does not work" I meant it throw an exception (NoSuchElementException) on this method:

```
 public class ElementFinderService
    {
        public TElement Find<TElement>(ISearchContext searchContext, Utils.By by)
            where TElement : class, IElement
        {
            var element = searchContext.FindElement(by.ToSeleniumBy());
            var result = this.ResolveElement<TElement>(searchContext, element);

            return result;
        }
```
in line:
```
            var element = searchContext.FindElement(by.ToSeleniumBy());
```
so where the original Webdriver is called. 
I call my WaitUntil method like this:

```
            this.driver.WaitUntil(x => LoginForm != null && LoginForm.Displayed && LoginForm.Enabled, TimeSpan.FromSeconds(5));
```
driver variable is IDriver interface I made. So can I use IDriver interface instead IWebdriver together with Wait? I dont want to use IWebDriver in my test because I am building test framework and I want to use something like this in my test project:

IDriver driver = new SeleniumDriver();
IDriver driver = new WindowsDriver(); etc.

**Comment by jimevans** [comment]
Then you’ll need to have your wait ignore the `NoSuchElementException`. That code would look something like the following:

    public static bool WaitUntil(this IDriver driver, Func<IDriver, bool> condition, TimeSpan timeout)
    {
        var wait = new DefaultWait<IDriver>(driver)
        {
            Timeout = timeout
        };

        // This example ignores only the NoSuchElementException. To
        // have the same behavior as WebDriverWait, you should actually
        // use NotFoundException instead. 
        wait.IgnoreExceptionTypes(typeof(NoSuchElementException));

        bool result = wait.Until(condition);

         if (!result)
         {
             throw new Exception();
         }

        return result;
    }

**Comment by Haxy89** [comment]
@jimevans 
Method after your fix seems to work:
```
public static T WaitUntil<T>(this IDriver driver, Func<IDriver, T> condition, TimeSpan timeout)
        {
            var wait = new DefaultWait<IDriver>(driver)
            {
                Timeout = timeout
            };

            wait.IgnoreExceptionTypes(new Type[] { typeof(NotFoundException) });

            var result = wait.Until(condition);

            if (Nullable.GetUnderlyingType(typeof(T)) != null)
            {
                throw new Exception();
            }

            return result;
        }
```

Thanks for helping :)
