### ISSUE TITLE
unable to receive message from renderer

### ISSUE THREAD

**Issue by wck821829906** [SeleniumHQ/selenium#7092]
It is very strange the "unable to receiver message from render" error occurs when executing testcase 
chrome version: 73.0.3683.103
chrome driver version: 73.0.3683.68
selenium standalone version:  3.141.59
os: windows server 2012 R2

![image](https://user-images.githubusercontent.com/17002975/55789108-3a652680-5aec-11e9-9422-583fc73a497c.png)

**Comment by barancev** [comment]
Please report this issue to chromedriver bug-tracker:
https://bugs.chromium.org/p/chromedriver/issues/list
(and don't forget to attach a reproduction scenario)
