### ISSUE TITLE
Selenium WebDriver typing very slow(one by one character) in text field on IE browser in grid node

### ISSUE THREAD

**Issue by Elakkiyaab** [SeleniumHQ/selenium#7093]
## 🐛 Bug Report
Selenium WebDriver typing very slow(one by one character) in text field on IE browser in grid node

issue:
.The text are typing very slow in text field for IE browser in GRID node(both 32 bit and 64 bit).It is typing one by one character .So getting timeOut error. It is running and typing text fast in Local machine. It was working fine for 3.12 earlier . Due to IE version update it is not working .

## Environment

OS: Windows 10(1803 version)
Browser: Internet explorer
Browser version: 11.648.17134.0
Browser Driver version: 3.14.0 
Language Bindings version: : Java 3.141.59 
Selenium Grid version: : 3.141.59,

**Comment by barancev** [comment]
Try to start driver with `requireWindowFocus` capability:
```
new RemoteWebDriver(new InternetExplorerOptions().requireWindowFocus())
```
Will it help?

**Comment by diemol** [comment]
Closing as we didn't get any more replies from the OP.
