### ISSUE TITLE
Switching between windows is not working

### ISSUE THREAD

**Issue by gajiya** [SeleniumHQ/selenium#7094]
package Window_handle;

import java.util.Set;
import java.util.concurrent.TimeUnit;

import java.util.Iterator;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class handle_class {

	public static void main(String[] args) throws InterruptedException  {
		// TODO Auto-generated method stub
		
		System.setProperty("webdriver.chrome.driver",
"D:\\Driver\\chromedriver_win32\\chromedriver.exe");
		
	      WebDriver driver1 = new ChromeDriver();
		

		
driver1.get("https://accounts.google.com/ServiceLogin/signinchooser?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&ltmpl=default&flowName=GlifWebSignIn&flowEntry=ServiceLogin");

       driver1.findElement(By.xpath("//*[text ()='Create account']")).click();
       driver1.findElement(By.xpath("//*[text()='For myself']")).click();
	
	
	driver1.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
	
	
	String parent_window = driver1.getWindowHandle();
	
	
	System.out.println("Before switching title is =" +driver1.getTitle() );
	
	Set <String> s1 = driver1.getWindowHandles();
	
	
	Iterator<String> i1 = s1.iterator();
	
	
	while(i1.hasNext())
	{
		String child_window = i1.next();
		
		if(!parent_window.equals(child_window))
		
		
		{
			
			driver1.switchTo().window(child_window);
			
			Thread.sleep(10000);
			
			System.out.println("After swithcing title is" + driver1.getTitle());
			
			driver1.close();
		}
		
	}
	
	driver1.switchTo().window(parent_window);
	
	System.out.println(driver1.getTitle());
	
	
		
	}

}

I am writing the above code in selenium to switch the gmail page to create account but while loop is not executed.

Please help me

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
