### ISSUE TITLE
Please advise me a solution on the following errors when i run selenium code in using google chrome.  Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.

### ISSUE THREAD

**Issue by Rmalepatal** [SeleniumHQ/selenium#7095]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by lmtierney** [comment]
As posted in the template, that you didn't remove:

> Please note that this issue tracker is not a help form and this issue will be closed.
>
>For questions or help please see:
>
>    SeleniumHQ IRC channel
>    SeleniumHQ Slack channel
>    The Selenium Users google group
