### ISSUE TITLE
Random permission problem when trying to obtain a free port

### ISSUE THREAD

**Issue by tapioko** [SeleniumHQ/selenium#7097]
## 🐛 Bug Report
Selenium tests fail randomly with "listen EACCES: permission denied 0.0.0.0:54347" (port number varies). This is quite infrequent, roughly 1% of the time.

## To Reproduce
Run any tests multiple times over and over again on Windows with JS bindings. Sorry!

## Expected behavior

IMHO this permission problem should not be visible to user unless it's persistent.

This can be fixed by modifying javascript/node/selenium-webdriver/net/portprober.js#152 to include a check for EACCES: `if (e.code === 'EADDRINUSE' || e.code === 'EACCES') {`. Maybe error message in line 184 should include a note about possible permission problem.

With that fix (and some logging) I was able to see that on the second try a free port was obtained.

## Environment

OS: Windows 10, 1809, Build 17763.379
Browser: Chrome
Browser version: 73.0.3683.75
Browser Driver version: ChromeDriver 2.46.0
Language Bindings version: selenium-webdriver 4.0.0-alpha.1
Test runner: Jest 23.6.0

**Comment by adymorz** [comment]
I have got the same issue running selenium with `ava` on `node.js`, see [question on stackoverflow](https://stackoverflow.com/questions/55708266/occassional-eacces-error-running-selenium-tests-in-ava) for detailed informations about my case.

The environment is the same as described above except the test runner, which is `ava` in my case.

Also the described fix helps me to run the tests without error messages.

**Comment by trenowden** [comment]
I was having this issue as well, it's fixed in master but 4.0.0-alpha.1 is ages behind. When I pulled master and used that in my tests the problem went away.

**Comment by adymorz** [comment]
I tried to do use the code from `master` branch, but I failed: https://npm.community/t/npm-install-use-master-branch-from-monolithic-repository-e-g-selenium-webdriver/8387

**Comment by tapioko** [comment]
I don't think the fix is in master. At least not the fix I proposed in my first post.

https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/net/portprober.js

**Comment by adymorz** [comment]
I just created a PR: https://github.com/SeleniumHQ/selenium/pull/7327
