### ISSUE TITLE
Tests fail to run when launched from bamboo with   " org.openqa.selenium.NoSuchSessionException: No active session" exception

### ISSUE THREAD

**Issue by KuzhaliDhivyan** [SeleniumHQ/selenium#7098]
## 💬 Questions and Help
Hi,

When tests are launched from Bamboo build, they fail with the below error. 

com.mining.test.CMATest.init FAILED
12-Apr-2019 15:30:08
    org.openqa.selenium.NoSuchSessionException: No active session with ID 3284d088f56091eb470ccdc0f33f77f8 (WARNING: The server did not provide any stacktrace information)
12-Apr-2019 15:30:08
    Command duration or timeout: 0 milliseconds
12-Apr-2019 15:30:08
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
12-Apr-2019 15:30:08
    System info: host: 'AUWILL-APP-003', ip: '10.3.110.88', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_131'
12-Apr-2019 15:30:08
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
12-Apr-2019 15:30:08
    Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 73.0.3683.68 (47787ec04b6e3..., userDataDir: C:\Users\DEVELO~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:63719}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 73.0.3683.103, webStorageEnabled: true, webdriver.remote.sessionid: 3284d088f56091eb470ccdc0f33...}
12-Apr-2019 15:30:08
    Session ID: 3284d088f56091eb470ccdc0f33f77f8
12-Apr-2019 15:30:08
        at sun.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source)
12-Apr-2019 15:30:08
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12-Apr-2019 15:30:08

Kindly help to resolve the issue.

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
