### ISSUE TITLE
Webdriver does not work when rebranding firefox with -APP parameter

### ISSUE THREAD

**Issue by c094728** [SeleniumHQ/selenium#710]
What steps will reproduce the problem?
Firefox 38.1.0
1) Go to firefox installation directory and move the file 
applicationl.ini under subdirectory browser.

2) Edit application.ini and change 
Vendor=Mozilla
Name=Firefox
to 
Vendor=NewVendor
Name=NewApp

3) Create a firefox shorcut that starts up with command line parameter
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -app  browser\application.ini

Note, the shortcut needs the "Start In" directory set or else you have to include the full path to application.ini.

4) Click on the shortcut.  Browser will start up and create profile under
AppData/Roaming/NewVendor/NewApp.

Notice that if you select Help/Troubleshooting info menu that the userAgent contains NewVendor/NewApp instead of Mozilla/Firefox
You can make the userAgent also contain Mozilla/Firefox by setting
about:config property
general.useragent.compatMode.firefox=true

5)  Now I want to make webdriver start up using the -APP parameter

FirefoxBinary binary = new FirefoxBinary(new File(exePath+"\firefox.exe"));
            binary.addCommandLineOptions("-APP",exepath+"\browser\APPLICATION.INI");

```
        try{
        webDriver = new FirefoxDriver(binary,firefoxProfile);
        }catch(Exception e){
            e.printStackTrace();
```

6) Browser starts up up but Selenium doesn't connect. 
It gets
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
**\* LOG addons.manager: Application has been upgraded
**\* LOG addons.xpi: startup
**\* LOG addons.xpi: Skipping unavailable install location app-system-local
**\* LOG addons.xpi: Skipping unavailable install location app-system-share
**\* LOG addons.xpi: Ignoring file entry whose name is not a valid add-on ID: C:\Users\DKLEPP~1\AppData\Local\Temp\anonymous8056356403011805978webdriver-profile\extensions\webdriver-staging
*

What is the expected output? What do you see instead?

WebDriver 2.45.1
OS: Windows 7(64)
Browser: Firefox  
Browser version: 38.1.0(esr)

Using the -APP parameter is like running firefox as a xulrunner application.  We have created a customized version of firefox for corporate use by doing this.   We have a web app that we want to run on this specific instance of firefox so that users don't use the same browser to surf the web)

We used to not require the -APP parameter as firefox would automatically load application.ini and it would work fine with Selenium.  Now with the required command line parameter Selenium no longer works.

**Comment by gagekehoe** [comment]
I have the same issue. Like identical. I had to install 38.0.1 which I'm assuming overwrote the application.ini file that I had. Is there a work around for this?

**Comment by barancev** [comment]
This issue will never be fixed in legacy Firefox driver. If it is still actual for the new Firefox driver implementation aka geckodriver please raise an issue in geckodriver tracker: https://github.com/mozilla/geckodriver/issues
