### ISSUE TITLE
c# selenium webdriver IE 11 hide address bar and url fix size .

### ISSUE THREAD

**Issue by YounesseSoft** [SeleniumHQ/selenium#7103]
## 💬 Questions and Help
hello every one , i include in my small project  c# windows form selenium webdrive IE 11 i need hide address bar  and url disable context menu fix resize by client and  disable maximize button from IE i have searched everywhere i have not found someone can help me please i need this so i can protect info personell.

[https://ibb.co/XpdDHSc](url)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by YounesseSoft** [comment]
thks u so match
