### ISSUE TITLE
Selenium Click issue 3.10

### ISSUE THREAD

**Issue by Karthiele** [SeleniumHQ/selenium#7107]
Hi All, 

We have automated Our project using Selenium 3.9.0.0/ IE 3.9  version. with IE 11 

After we upgrade to Selenium and IE version > 3.9 , scripts are not clicking any elements ( If we use java script, its working fine. But normal click method is not working.)

Thanks
Karthikeyan Sundaram

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
