### ISSUE TITLE
Run ChromeDriver on Centos7 get status code:-11

### ISSUE THREAD

**Issue by lightflyer** [SeleniumHQ/selenium#7117]
- a simple test running on centos7, and I get some error like following:

/home/auser-tw/projects/IM3/chrome_test.py:13: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path='/home/auser-tw/projects/IM3/model/Twitter/TC/google_chrome_driver/linux/chromedriver', chrome_options=options)
Traceback (most recent call last):
  File "/home/auser-tw/projects/IM3/chrome_test.py", line 13, in <module>
    driver = webdriver.Chrome(executable_path='/home/auser-tw/projects/IM3/model/Twitter/TC/google_chrome_driver/linux/chromedriver', chrome_options=options)
  File "/home/auser-tw/miniconda3/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/auser-tw/miniconda3/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/auser-tw/miniconda3/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /home/auser-tw/projects/IM3/model/Twitter/TC/google_chrome_driver/linux/chromedriver unexpectedly exited. Status code was: -11

this is my code:
`from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')
driver = webdriver.Chrome(executable_path='/home/auser-tw/projects/IM3/model/Twitter/TC/google_chrome_driver/linux/chromedriver', chrome_options=options)
driver.get("https://www.google.com")
print(driver.page_source)
driver.quit()`
first submit issus, thank you for help from everyone

**Comment by AutomatedTester** [comment]
Please log chromedriver issues with the chromedriver project.

https://sites.google.com/a/chromium.org/chromedriver/help

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using [jsfiddle.net](https://jsfiddle.net)

**Comment by lightflyer** [comment]
thank you for you reply, I already fix it. The chrome driver is not matched with the browser because browser  is auto updated. And may I ask, where can I query status code about chrome driver, thank you  again. @AutomatedTester
