### ISSUE TITLE
#dig method

### ISSUE THREAD

**Issue by sashamd** [SeleniumHQ/selenium#7120]
I'm getting `.rvm/gems/ruby-2.4.5/gems/selenium-webdriver-3.141.5926/lib/selenium/webdriver/firefox/driver.rb:42:in 'dig': Selenium::WebDriver::Remote::Capabilities does not have #dig method (TypeError)`
and have to replace `opts.dig(:desired_capabilities, :marionette)`
with `opts[:desired_capabilities][:marionette]`

**Comment by andreyuhai** [comment]
Had the same issue but I just rolled back to the version 3.141.0.

**Comment by p0deje** [comment]
How do you instantiate driver?

**Comment by sashamd** [comment]
> How do you instantiate driver?

`b = Watir::Browser.new(:firefox)`

**Comment by theDogOfPavlov** [comment]
I'm having the same issue, and also instantiating via watir too:

`browser = Watir::Browser.new :firefox, profile: profile, http_client: client`

**Comment by p0deje** [comment]
Fixed in bc191b9d6a184ce9948552b7a0fa5c33c024c4bf and will be released in 3.142.0. Thank you for a bug report!
