### ISSUE TITLE
Get child element's attribute error

### ISSUE THREAD

**Issue by lincan00** [SeleniumHQ/selenium#7124]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by lincan00** [comment]
For example

The html code is as follows:
<pre><code><code><</code><code>body</code>>
  <<code>div class="position-relative js-header-wrapper "</code>>
    <<code>div id="js-pjax-loader-bar" class="pjax-loader-bar"</code>>
      <<code>div class="progress"</code>><<code></code><code>/</code>div>
    <<code>/div</code>>
  <<code>/div</code>>
<<code>/body</code>>
</code></pre>

<pre><code>WebElement elementA = driver.findElement(By.id("js-pjax-loader-bar"));
WebElement elementB = elementA.findElement(By.xpath("//div"));
//WebElement elementB = driver.findElement(By.id("js-pjax-loader-bar")).findElement(By.xpath("//div"));
System.out.println(elementB.getAttribute("class"));
</code></pre>
The result I expect is
<pre>progress</pre>
 But the actual result is:
<pre>
position-relative js-header-wrapper 
</pre>

**Comment by jimevans** [comment]
Since WebDriver follows the XPath specification, using the locator `//div` in a locator means “find `<div>` elements from the beginning of the document.” This is true even if calling `findElement` from a `WebElement`. Use the `.//` XPath (note the leading period) to limit the scope to the containing element.

**Comment by anujkumar21** [comment]
Hi @jimevans,

I tried with ".//div" 
`WebElement elementB = elementA.findElement(By.xpath(".//div"));`
Now getting NoSuchElementException.

> FAILED: testChallengingDOMPage
> org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//div"}
>   (Session info: chrome=73.0.3683.103)
>   (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 0 milliseconds
> For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'ANUJKUMAR-PC', ip: '192.168.0.103', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_74'
> Driver info: org.openqa.selenium.chrome.ChromeDriver
> Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.38.552522 (437e6fbedfa876..., userDataDir: C:\Users\ANUJKU~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 73.0.3683.103, webStorageEnabled: true}
> Session ID: fc1727d42b0cdfec914086942f584705
> *** Element info: {Using=xpath, value=.//div}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
> 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
> 	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
> 	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(Abstract

**Comment by diemol** [comment]
@anujkumar21 this is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
