### ISSUE TITLE
Python Binding 4.0 Make WebElement and WebDriver class rely on ABC to register all subtypes

### ISSUE THREAD

**Issue by isaulv** [SeleniumHQ/selenium#7127]
## 🚀 Feature Proposal

Add an Abstract Base Class to Remote.Webdriver and Remote.WebElement 

## Motivation

For most users of Python Selenium, they tend to have a straight forward use of the library, where they don't run into issues. However when it comes to using add on tools like Applitools Eyes, Appium, and even the current incarnation of the binding itself, there are times when the `isinstance` type checker will fail due to unforeseen uses of a WebElement. 

Examples are using EventFiringWebElement with an ActionChains.move_to command.   #6604 
The Applitools Eyes Python binding does not subclass WebElement, which makes it hard to integrate with EventFiringWebDriver, or other libraries that do isinstance checks.

The webdriver type itself hardly goes through checks itself, but a tool like Eyes, does do type checks on the driver to see if it is wrapped with the Eyes implementation.

## Example

If WebElement is an ABC, then the following code should _just work_.
```
from abc import ABC

class IWebElement(ABC):
    ... # some core methods are made abstract method.

class WebElement(IWebElement):
    ... # existing definition

# Eyes library
class EyesWebElement(object):
    ... # eyes specific code

IWebElement.register(EyesWebElement)
... # assume you have valid driver, element from a live session.
assert isinstance(EyesWebElement(driver, element), IWebElement)
```

The implementation of this should also include a scan of the code base for `type(object)` checks and replace them with `isinstance` or `issubclass` checks, unless we need exact type matching.

**Comment by vhryhorchuk-amplify** [comment]
The same problem exists for `EventFiringWebElement`, as it doesn't extends `WebElement`.
We have next bug:
```
class invisibility_of_element_located(object):
    """ An Expectation for checking that an element is either invisible or not
    present on the DOM.

    locator used to find the element
    """
    def __init__(self, locator):
        self.target = locator

    def __call__(self, driver):
        try:
            target = self.target
            if not isinstance(target, WebElement):
                target = _find_element(driver, target)
            return _element_if_visible(target, False)
        except (NoSuchElementException, StaleElementReferenceException):
            return True
```

When we pass `EventFiringWebElement` to the expected condition `invisibility_of_element(myEventFiringWebElement)` it goes to:
```
            if not isinstance(target, WebElement):
                target = _find_element(driver, target)
```
And fails with
```
 def _find_element(driver, by):
        """Looks up an element. Logs and re-raises ``WebDriverException``
        if thrown."""
        try:
>           return driver.find_element(*by)
E           TypeError: find_element() argument after * must be an iterable, not EventFiringWebElement
```

**Comment by isaulv** [comment]
Closing issue since changed has been merged.
