### ISSUE TITLE
Vivaldi browser support

### ISSUE THREAD

**Issue by senpl** [SeleniumHQ/selenium#7129]
## 🚀 Feature Proposal

Vivaldi and other chrome based browsers should have easy way to use drivers

## Motivation

More chrome based browsers exist and it would be nice to provide way to automate on them.

## Example

It should work as chrome driver, but with support of browser name like vivaldi , chromeEdge etc.
`desiredCapabilities: { browserName: "vivaldi"`...

**Comment by AutomatedTester** [comment]
This would need to be supported by Vivaldi themselves. They can follow the [spec](https://w3c.github.io/webdriver/) on how to develop it.
