### ISSUE TITLE
NoSuchElementException when running on IE9 with Selenium 2.40 and same IEDriver 32 bit.

### ISSUE THREAD

**Issue by DeepenShah** [SeleniumHQ/selenium#713]
Hi!!

I have my script which is working fine on IE11. For some case we need to test it on IE9, and here starts the problem. We ran same script on IE9 , it launches IE but fails to identify element from the first page.

It throws NoSuchElementException. I have enable IEDriver log it says, 

D 2015-06-25 11:12:02:104 ElementFinder.cpp(119) Using FindElements atom to locate element having id = overridelink
T 2015-06-25 11:12:02:104 Browser.cpp(95) Entering Browser::GetDocument
I 2015-06-25 11:12:02:104 Browser.cpp(99) No child frame focus. Focus is on top-level frame
T 2015-06-25 11:12:02:118 Browser.cpp(557) Entering Browser::GetDocumentFromWindow
T 2015-06-25 11:12:02:133 Script.cpp(40) Entering Script::Initialize
T 2015-06-25 11:12:02:133 Script.cpp(61) Entering Script::AddArgument(std::wstring)
T 2015-06-25 11:12:02:133 Script.cpp(96) Entering Script::AddArgument(VARIANT)
T 2015-06-25 11:12:02:133 Script.cpp(61) Entering Script::AddArgument(std::wstring)
T 2015-06-25 11:12:02:133 Script.cpp(96) Entering Script::AddArgument(VARIANT)
T 2015-06-25 11:12:02:133 Script.cpp(160) Entering Script::Execute
T 2015-06-25 11:12:02:133 Script.cpp(468) Entering Script::CreateAnonymousFunction
W 2015-06-25 11:12:02:142 Script.cpp(485) -2147024891 [Access is denied.]: Unable to execute code, call to IHTMLWindow2::execScript failed

I have Protected mode same for all zones and protected mode is on.  From other thread i found out to check by running java script so i tried following code,

if (driver instanceof JavascriptExecutor) {
	    ((JavascriptExecutor)driver).executeScript("alert('hiii');");
}

that too failed and IEDriver has same error log as above
W 2015-06-26 14:40:22:307 Script.cpp(485) -2147024891 [Access is denied.]: Unable to execute code, call to IHTMLWindow2::execScript failed
W 2015-06-26 14:40:22:308 Script.cpp(171) Cannot create anonymous function
W 2015-06-26 14:40:22:308 response.cc(69) Error response has status code 17 and message 'JavaScript error' message
D 2015-06-26 14:40:22:310 server.cc(308) Response: {"sessionId":"cd0bcf34-3f6e-4875-b91a-e74029584dcb","status":17,"value":{"message":"JavaScript error"}}

Please help what i am missing here.

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

Also, please upgrade, the latest Selenium version is 2.46 at the moment.

**Comment by DeepenShah** [comment]
Actually i found similar issue, https://code.google.com/p/selenium/issues/detail?id=5475, but it was closed due to inactivity hence i reported it as issue here.

Accept my apology if i have posted to wrong place. Thanks.

**Comment by barancev** [comment]
"Access is denied" means that some security policy blocks JS execution. There is no "official" guide to tune security settings, but I hope the community can help you.
