### ISSUE TITLE
python UnexpectedAlertPresentException doesn't contain alert_text string

### ISSUE THREAD

**Issue by bandophahita** [SeleniumHQ/selenium#7130]
## 🐛 Bug Report

When `UnexpectedAlertPresentException` is raised the exception attribute `alert_text` is None.  The `alert_text` message _can_ be found within the `msg` attribute but it's a pain to parse out the original alert text string from the rest of the exception message.  It would be nice if the `alert_text` attribute contained the original alert text.

Is this possible on the selenium side of things or is this something chromedriver must remedy?

## To Reproduce

Raise and catch `UnexpectedAlertPresentException` in python

## Expected behavior

The `UnexpectedAlertPresentException` attribute `alert_text` should contain the alert.text string.

## Environment

OS: OSX
Browser: Chrome
Browser version: 73.0.3683.103
Browser Driver version: chromedriver=2.38.552518
Language Bindings version: python 3.7
Selenium Grid version (if applicable): 3.141.0

**Comment by cgoldberg** [comment]
please upgrade:
 
https://github.com/SeleniumHQ/selenium/blob/4570582475c7c548ba42ef9f250605a07b11eeb1/py/CHANGES#L94

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L235

**Comment by jimevans** [comment]
Additionally, returning the alert text as part of the error response is optional, according to the spec. The Chrome driver has never supported this functionality, and does not currently do so, if memory serves.
