### ISSUE TITLE
Python: Cleaning up ErrorInResponseException?

### ISSUE THREAD

**Issue by averresen** [SeleniumHQ/selenium#7134]
## 🐛 Bug Report

The Python implementation of Selenium uses an exception class called 'ErrorInResponseException'. However, it seems like this exception isn't used for anything useful anymore :

- [It is only assigned to a variable once right before an if-elif-else block where the variable is always assigned a new value.](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L140)
- [A bit later, an if-statement checks whether the value of the aforementioned variable is still ErrorInResponseException, which will never be True.](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L206)
- [And the program does the same thing a couple of lines later.](
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/errorhandler.py#L233)
- ErrorInResponse is not used anywhere else.

Git blame shows that the code was added 9 years ago. It seems to me like this exception class, and the code that I mentiond, can be removed.

**Comment by AutomatedTester** [comment]
thanks for this, do you want to do a PR to remove the dead code?
