### ISSUE TITLE
New version issue

### ISSUE THREAD

**Issue by tejasbhosale** [SeleniumHQ/selenium#7136]
## 🐛 Bug Report

**[09:48:23] Error: Invalid or corrupt jarfile /Users/jenkins/workspace/TestGate-DEV/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-4.0.0-alpha-1.zip.jar**

Getting this error in npm module of protractor today. Seems like quite a few people affected by this. 
There is an error with newer version. Code base was working fine with our older version 3.14X 

-->

# Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment
Failing in local and jenkins

**Comment by tejasbhosale** [comment]
https://stackoverflow.com/questions/55835805/invalid-or-corrupt-jar-file-when-trying-to-start-selenium-server-from-intellij

**Comment by barancev** [comment]
Please report this issue to protractor.
1) It seems like their selenium server auto-download alorithm is broken, we don't ship selenium-server-standalove file with double extension .zip.jar (and never did)
2) selenium server 4.0 has a new non backward compatible set of CLI options so it hardly will work out of the box with protractor.
