### ISSUE TITLE
Cannot start the driver service on http://localhost after update to Chrome 74

### ISSUE THREAD

**Issue by ChrisGClark** [SeleniumHQ/selenium#7137]
After Chrome automatically updated to Version 74.0.3729.108 (Official Build) (64-bit), I updated chromedrive to latest (74.0.3729.6), I get following error: 

OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost:52736/

   at OpenQA.Selenium.DriverService.Start()

This code is run from following on mac, .net core:
```
        private void initWebDriver()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);
            options.AddUserProfilePreference("download.default_directory", directoryToSave);

            driverService.Start();
            driver = new ChromeDriver(driverService, options);
            wait = new WebDriverWait(driver, System.TimeSpan.FromMilliseconds(defaultSleep));
        }
```
 
This program was working fine for weeks when using Chrome 73, only has broken this morning with the latest chrome version.

I've also tried updating to latest NuGet packages (Selenium.Chrome.WebDriver 74.0.0, Selenium.WebDriver 3.141.0 and Selenium.WebDriver.MicrosoftDrive 17.17134.0 but still can not solve this).

In my programs bin/Debug i've also updated the alias for chromedrive to point at new chromedriver install:

big/Debug/netcoreapp2.2/chromedriver -> /usr/local/Caskroom/chromedriver/74.0.3729.6/chromedriver

I know this is working as there was a permissions problem until i did a chmod to change permissions on my new alias, then the error changed to the above.

Any ideas would be appreciated.

**Comment by jimevans** [comment]
Any chance you could provide a more complete example? For example, there’s no definition in the code you’ve posted for `driverService` nor `driver`. I ran tests using the tip-of-tree of the .NET bindings this afternoon, but on Windows and using .NET Framework instead of .NET Core, so there are at least some scenarios that work.

**Comment by ChrisGClark** [comment]
@jimevans 

`
        //Selenium
        private static string currentDirectory = Directory.GetCurrentDirectory();
        private ChromeDriverService driverService = ChromeDriverService.CreateDefaultService(currentDirectory);
        private ChromeDriver driver;
        private WebDriverWait wait;


        private void initWebDriver()
        {
            ChromeOptions options = new ChromeOptions();
            options.AddUserProfilePreference("plugins.always_open_pdf_externally", true);
            options.AddUserProfilePreference("download.default_directory", directoryToSave);

            driverService.Start();
            driver = new ChromeDriver(driverService, options);
            wait = new WebDriverWait(driver, System.TimeSpan.FromMilliseconds(defaultSleep));
        }

        private void shutdownWebDriver()
        {
            driver.Quit();
            driver.Dispose();
            Thread.Sleep(defaultSleep * 2);
        }

        [Fact]
        public void Test1()
        {
            initWebDriver();

            using (driver)
            {`
// run my tests
}
}

**Comment by ChrisGClark** [comment]
After some testing, i found out if i put the chromedriver unix exec in bin/Debug, chrome opens ok my unit test.  However, if i change to symlink in bin/Debug i still get the error above.  

Still confused why as if I chmod 777 on both source and symlink it still doesn't work.  Doesn't appear to be a permissions issue.

If i double click the sym link, command line also opens ok.  

Previously this worked fine as sym link too.
![Screen Shot 2019-04-25 at 22 45 20](https://user-images.githubusercontent.com/21120658/56749500-0a847700-67ac-11e9-9e79-5a3e9931bea1.png)

**Comment by dev-variety** [comment]
This is happening on my end too, and I am getting this too.

```csharp
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 34311
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

Unhandled Exception: OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.18-9-pve x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at test.Program.Main(String[] args) in LINE
   at test.Program.<Main>(String[] args)
Aborted
```

I have installed Google Chrome (latest) and made sure it is in `usr/bin`..

This was not an issue when it came to v73.

**Comment by cgoldberg** [comment]
please submit ChromeDriver issues to the Chromium team:
https://bugs.chromium.org/p/chromedriver
