### ISSUE TITLE
[C#] DefaultWait works with lambda expression but not with ExpectedConditions methods

### ISSUE THREAD

**Issue by ghost** [SeleniumHQ/selenium#7139]
I can't make DefaultWait to works with my custom ExpectedContidions method.

```
public sealed class ExpectedConditions
    {
        public static Func<ISeleniumDriver, bool> WaitForReady(IElement element)
        {
            return x =>
            {
                return element != null && element.Displayed && element.Enabled;
            };
        }
    }
```
My DefaultWait looks like this:

```
public static T WaitUntil<T>(this ISeleniumDriver driver, Func<ISeleniumDriver, T> condition, TimeSpan timeout)
        {
            var wait = new DefaultWait<ISeleniumDriver>(driver)
            {
                Timeout = timeout
            };

            wait.IgnoreExceptionTypes(new Type[] { typeof(NotFoundException) });

            var result = wait.Until(condition);

            if (default(T) == null)
            {
                throw new Exception();
            }

            return result;
        }
```

Everything works as expected when I use it like this:

`this.driver.WaitUntil(x => TuneSideNavigatioBar != null && TuneSideNavigatioBar.Displayed && TuneSideNavigatioBar.Enabled, TimeSpan.FromSeconds(10));`

But doesn't works in this way:

`this.driver.WaitUntil(ExpectedConditions.WaitForReady(TuneSideNavigatioBar), TimeSpan.FromSeconds(10));`

`TuneSideNavigatioBar` is `private IButton TuneSideNavigatioBar => driver.Find<Button>(By.XPath("//button[@qaid='Sidebar-Tune']"));`

I get: `Message: OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"xpath","selector":"//*[@qaid='Sidebar-Tune']"}`

Please tell me what is difference to use lambda and methods when calling Default wait

**Comment by Haxy89** [comment]
@jimevans 
Any ideas why lambda works and expected conditions does not in my code?
Many thanks for help

**Comment by jimevans** [comment]
ExpectedConditions has been removed from the .NET bindings support package.
