### ISSUE TITLE
Using xpath locator for xml document doesn't work in v2.45 & 2.46

### ISSUE THREAD

**Issue by noralin** [SeleniumHQ/selenium#714]
I'm getting a Selenium::WebDriver::Error::InvalidSelectorError error when I do:
driver.find_elements(:xpath, '//event') #this used to work in 2.43.0, but does not work in 2.45 & 2.46

My xml looks like this:
![test_xml](https://cloud.githubusercontent.com/assets/1933355/8386939/8863b818-1c22-11e5-830b-a1e1460a43c9.jpg)

Full error message:
Selenium::WebDriver::Error::InvalidSelectorError: The given selector //event is either invalid or does not result in a WebElement. The following error occurred:
InvalidSelectorError: Unable to locate an element with the xpath expression //event because of the following error:
TypeError: q is null

Please let me know if there's another way to find_element by xpath for xml documents. Thanks!

**Comment by ddavison** [comment]
reproduced in Firefox and Safari.  Works in Chrome

**Comment by noralin** [comment]
Thank you for fixing this! I've verified this works using v2.47.
