### ISSUE TITLE
Logging to file not working with Ruby and Geckodriver

### ISSUE THREAD

**Issue by theDogOfPavlov** [SeleniumHQ/selenium#7140]
## 🐛 Bug Report

Logging to file not working with Ruby and Geckodriver.

## Expected behavior

A log file to be created that includes the trace level output.

## Test script or set of commands reproducing this issue

```
profile = Selenium::WebDriver::Firefox::Profile.new( ) 
profile.log_file = File.expand_path( 'firefox.log' )
browser = Watir::Browser.new :firefox, profile: profile, log_level: :trace
browser.goto( 'https://www.google.co.uk/' ) 
```

## Environment

OS: Ubuntu bionic 64 bit 
Browser: Mozilla Firefox
Browser version: 67.0b2
Browser Driver version: GeckoDriver 0.24
Language Bindings version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Selenium Webdriver: 3.141.0 (latest version has unrelated fatal error)

**Comment by p0deje** [comment]
It's currently not possible to direct only Firefox/GeckoDriver logs to a file, but it is possible to aggregate all Selenium logs which will include Firefox/GeckoDriver:

```ruby
Selenium::WebDriver.logger.level = :debug
Selenium::WebDriver.logger.output = 'selenium.log'
browser = Watir::Browser.new :firefox, log_level: :trace
```

Please let me know if this works for you. Otherwise, we might provide service-level logging.

**Comment by theDogOfPavlov** [comment]
Yes, this works well, thanks. Though interestingly, the selenium level flag takes priority, so something like the following doesn't produce any debug from geckodriver:

```
Selenium::WebDriver.logger.level = :warn
Selenium::WebDriver.logger.output = 'selenium.log'
browser = Watir::Browser.new :firefox, log_level: :trace
```

**Comment by p0deje** [comment]
The way Selenium works is that it suppresses all GeckoDriver output unless `Selenium::WebDriver.logger.level` is `:debug`. In such case it redirects GeckoDriver output to stdout, so you can see it. `log_level` controls the verbosity of GeckoDriver output, but unless Selenium's logger level is `:debug`, you won't be able to see any of it.

If the provided solution works for you, please close the issue. I'll see how this can be improved if we have more similar issues.

**Comment by theDogOfPavlov** [comment]
ok, makes sense, and happy to close. Maybe a note in the code or some documentation would help make it clearer?

**Comment by p0deje** [comment]
It's actually documented in GeckoDriver: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by theDogOfPavlov** [comment]
Whilst it's true there is a working example, it's not very clear about the interaction of the log_level settings between Selenium and Geckodriver for Ruby. The examples for the other languages don't seem to have the same dependency.

**Comment by p0deje** [comment]
Well, that's because Watir hides that behavior. If you are using Selenium directly, it becomes more obvious as `log_level` is a part of `Firefox::Options` class:

```ruby
Selenium::WebDriver.logger.level = :debug
opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
driver = Selenium::WebDriver.for :firefox, options: opts
```

**Comment by theDogOfPavlov** [comment]
Ok. Thanks for your help!
