### ISSUE TITLE
How to build java-client.jar by BUCK？

### ISSUE THREAD

**Issue by tcwrleon** [SeleniumHQ/selenium#7141]
## 💬 Questions and Help
Hey guys，I have a question about how to build java-clinet.jar like which selenium.com can download?

I cloned the source，And  type "go selenium-server-standalone"  build selenium.jar success，But when I type "go selenium-java"
There is no client-java.jar was built，I don't know what to do。

Can you help me?

**Comment by lmtierney** [comment]
From the issue template that you deleted:


### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
