### ISSUE TITLE
What's in selenium-webdriver 3.142.0?

### ISSUE THREAD

**Issue by tisba** [SeleniumHQ/selenium#7143]
A new version 3.142.0 was released on rubygems 2 days ago (https://rubygems.org/gems/selenium-webdriver/versions/3.142.0). I've found no reference on that version, included changes etc anywhere – no git tag, no release note, no change log.

I've not done an analysis like diffing the gem, so I'm not sure what is going on. I think it would be good to let people know that this is a "good" release and not a potentially dangerous thing like a malicious release we've seen in the past for other libraries.

Thank you!

**Comment by barancev** [comment]
The gem package contains a link to the changelog:
https://github.com/SeleniumHQ/selenium/blob/master/rb/CHANGES

**Comment by tisba** [comment]
uh damn, I'm terribly sorry! I totally overlooked that :(
