### ISSUE TITLE
Ruby bindings allow snake cased capabilities to be sent in firstMatch which is against w3c protocol

### ISSUE THREAD

**Issue by ss3681755** [SeleniumHQ/selenium#7144]
## 🐛 Bug Report

`firstMatch` contains snake cased capabilities because of [this](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.0/rb/lib/selenium/webdriver/remote/w3c/capabilities.rb#L157).
Since W3C specification does not allow any of those snake cased capabilities, jar throws exception ```illegal key values seen in w3c capabilities```.

## To Reproduce - Ruby bindings 3.141.0
```ruby
require 'selenium-webdriver'
capabilities = { "browserName" => "chrome", "browser_version" => "73.0" }
remote_url = 'http://localhost:4444/wd/hub'
driver = Selenium::WebDriver::Remote::Driver.new(url: remote_url, desired_capabilities: capabilities)
```

Detailed steps to reproduce the behavior:

### Prerequisites
1. java "1.8.0" or later
2. ruby "2.3.0" or later

### Steps
1. Download selenium webdriver ruby bindings 3.141.0
2. Download selenium jar 3.13.0
3. Open a terminal and run ```java -jar selenium-server-standalone-3.13.0.jar```.
4. Now open a seperate terminal instance and run ```irb```.
5. Paste the code provided in `To Reproduce` section above.

## Expected behavior

The payload which is sent in start session request should look like
```json
{
  "desiredCapabilities": {
     "browserName": "chrome",
     "browser_version": "73.0"
  },
  "capabilities": {
     "firstMatch": [{
        "browserName": "chrome",
        "browserVersion": "73.0" # Either `browser_version` should be omitted or converted to `browserVersion`
     }],
     "alwaysMatch": {
     }
  }
}
```
But currently it looks like
```json
{
  "desiredCapabilities": {
     "browserName": "chrome",
     "browser_version": "73.0"
  },
  "capabilities": {
     "firstMatch": [{
        "browserName": "chrome",
        "browser_version": "73.0"
     }],
     "alwaysMatch": {
     }
  }
}
```

## Test script or set of commands reproducing this issue

Provided a minimal script in `To Reproduce` section above.

## Environment

OS: OS X (Mojave)
Browser: Chrome
Browser version: 73
Browser Driver version: chromedriver 2.45
Language Bindings version: ruby 3.141.0
Selenium Grid version (if applicable): 3.13.0

**Comment by p0deje** [comment]
This is somewhat _expected_. The convention we had is that if you use _string_ in capabilities - it's your responsibility to make sure the name is compliant to some expected value, but if you want Selenium to take care of conversion, you need to use _symbol_ instead. So basically you should use one of those:

```ruby
capabilities = { "browserName" => "chrome", "browserVersion" => "73.0" }
# or
capabilities = { browser_name: "chrome", browser_version: "73.0" }
```

**Comment by twalpole** [comment]
As mentioned above this is as currently designed, although will be changing in 4.0. As detailed above use symbols if you want selenium-webdriver to handle conversion.  Closing.
