### ISSUE TITLE
Selenium downloading 4.0.0-alpha-1 as dependency

### ISSUE THREAD

**Issue by camerenisonfire** [SeleniumHQ/selenium#7145]
The POM file for several Selenium libraries specifies version as "[3.1.0,4.0.0)". When downloading these dependencies, several of them come as 4.0.0-alpha-1 jar files. This mainly seems to be happening with Selenium-Support, Selenium-API, and Selenium-Remote-Driver. 

I believe this is because "4.0.0-alpha-1" is technically less than "4.0.0".  Can the alpha builds be renamed in order for them to not be downloaded as dependencies? 

Update: This seems to be mostly a problem for those that have older 3.x versions of Selenium defined in their project. Setting the project dependency to be "3.141.59" seems to keep Selenium at that version and not download any Alpha builds.

**Comment by diemol** [comment]
Closing as this is not really a bug and it is how Maven works, someone took the time to explain this in more detail https://medium.com/@MichaKutz/legit-but-useless-maven-version-ranges-explained-d4ba66ac654, credits to @mkutz
