### ISSUE TITLE
Selenium tests fail to run due to TestNG errors

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#7146]
## 🐛 Bug Report

A clear and concise description of what the bug is
After Selenium upgrade to version 3.141.59, the tests fail to run with TestNG 16.4.3 on Jenkins v2.138.3 errors like:
TestNGClassFinder: Warning: Can't link and determine methods of class....
TestNGClassFinder: Unable to read methods on class ... -unable to resolve class reference org/apache/http/HttpRequest
Eclipse : when trying to run the tests from Eclipse 2019-03 , I get a message that either TestNG cannot find class in classpath or that No tests were found and nothing was run

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

After Selenium upgrade to version 3.141.59, the tests are successfully run from Jenkins v2.138.3 as they used to run with lower Selenium version

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 7
Browser: Internet Explorer, Chrome
Browser version: Internet Explorer 11.0.9600.19002, Chrome 74.0.3729.108
Browser Driver version: IEWebDriver 3.14 for 32 bit Windows IE, ChromeDriver 74.0.3729.6
Language Bindings version: Java 11.0.2 
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
Add an explicit dependency on https://search.maven.org/artifact/org.apache.httpcomponents/httpclient/4.5.8/jar, Selenium does not use this library anymore so it does not load it as a transitive dependency.

**Comment by hnestorova** [comment]
Hi, I added the jar but the problem was not resolved
![Jenkins_error](https://user-images.githubusercontent.com/30794708/56847612-ff356680-68e5-11e9-8a32-a672692cb239.PNG)
