### ISSUE TITLE
Selenium tests fail to run due to TestNG errors - duplicate of #7146  but I cannot reopen it

### ISSUE THREAD

**Issue by hnestorova** [SeleniumHQ/selenium#7147]
## 🐛 Bug Report - duplicate of #7146  but I cannot reopen it

After Selenium upgrade to version 3.141.59, the tests fail to run with TestNG 16.4.3 on Jenkins v2.138.3 errors like:
TestNGClassFinder: Warning: Can't link and determine methods of class....
TestNGClassFinder: Unable to read methods on class ... -unable to resolve class reference org/apache/http/HttpRequest
Eclipse : when trying to run the tests from Eclipse 2019-03 , I get a message that either TestNG cannot find class in classpath or that No tests were found and nothing was run
## To Reproduce
check screenshots

Detailed steps to reproduce the behavior:

## Expected behavior

After Selenium upgrade to version 3.141.59, the tests are successfully run from Jenkins v2.138.3 as they used to run with lower Selenium version

## Test script or set of commands reproducing this issue

check screenshots

## Environment

OS: Windows 7
Browser: Internet Explorer, Chrome
Browser version: Internet Explorer 11.0.9600.19002, Chrome 74.0.3729.108
Browser Driver version: IEWebDriver 3.14 for 32 bit Windows IE, ChromeDriver 74.0.3729.6
Language Bindings version: Java 11.0.2
Selenium Grid version (if applicable): 3.141.59
![Java_class](https://user-images.githubusercontent.com/30794708/56847946-2e9aa200-68eb-11e9-854e-1b671b54a3b7.PNG)
![TestNG_error](https://user-images.githubusercontent.com/30794708/56847947-2e9aa200-68eb-11e9-8382-3509d4f92b8f.PNG)

**Comment by hnestorova** [comment]
after adding http client 4.5.8 jar:
![Jenkins_error](https://user-images.githubusercontent.com/30794708/56847942-1f1b5900-68eb-11e9-9b3b-d64be800cc7f.PNG)

**Comment by hnestorova** [comment]
I ttied with Selenium version 3.13 and here is what the Jenkins console log looked like:
![image](https://user-images.githubusercontent.com/30794708/56848602-a8368e00-68f3-11e9-8c0d-a4aa1198ae29.png)

**Comment by hnestorova** [comment]
i tried with Selenium version 3.12 and here are the Jenkins console logs:
![image](https://user-images.githubusercontent.com/30794708/56848645-15e2ba00-68f4-11e9-92a7-cd9040ae80b1.png)

**Comment by hnestorova** [comment]
i tried with Selenium version 3.13 and here are the Jenkins console logs:
![image](https://user-images.githubusercontent.com/30794708/56848662-39a60000-68f4-11e9-9835-8f44a5dcfca7.png)

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by hnestorova** [comment]
I honestly dont understand how this is a questuion and not an issue as I am not able to upgrade to a newer selenium version due to errors.

**Comment by barancev** [comment]
Yes, I understand that youэму got an issue. But it's not an issue we can fix in Selenium code. You need to fix your project dependencies.

This issue tracker is not a support line, It is indented to track issues in Selenium code.

Selenium is  supported by the comminity. You're welcome to
- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by hnestorova** [comment]
@barancev the needed explicit dependency turned out to be not the one stated in https://github.com/SeleniumHQ/selenium/issues/7146#issuecomment-487263217  but rather: https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore/4.4.11
