### ISSUE TITLE
selenium inside a windows docker cotnainer fails with 

### ISSUE THREAD

**Issue by jhealy** [SeleniumHQ/selenium#7150]
## 🐛 Bug Report

Reach out direct to me and I'll walk you through everything from scratch to build container.  Bit of a long run to a crash.  Github repo here - https://github.com/jhealy/aspnet45-docker-selenium .

Selenium C# webdriver inside a Windows container fails with 'HTTP request to the remote WebDriver server for URL http://localhost:49164/session timed out after 60 seconds. '.  Everything works fine locally or in a clean Windows Server 2016 with UI.  If I build a dockers container for windows and copy my tests in it fails with this message.  Consistent on ff and chrome drivers.  

Error dump below

> PS C:\Seleniumtests> .\SeleniumDockerTest.exe http://localhost
> Target Url=http://localhost
> chrome options include --headless --dns-prefetch-disable --disablefeatuers
> Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 49164
> Only local connections are allowed.
> Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
> [0427/172326.658:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> [0427/172326.673:ERROR:audio_device_listener_win.cc(46)] RegisterEndpointNotificationCallback failed: 80070424
> 
> DevTools listening on ws://127.0.0.1:49167/devtools/browser/920800fc-253a-4443-881d-925c21230f96
> [0427/172326.783:ERROR:browser_gpu_channel_host_factory.cc(139)] Failed to launch GPU process.
> [0427/172326.910:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 0
> !!!error:OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49164/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
>    at System.Net.HttpWebRequest.GetResponse()
>    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
>    --- End of inner exception stack trace ---
>    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
>    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
>    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
>    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
>    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
>    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
>    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
>    at SeleniumDockerTest.Program.Main(String[] args) in C:\dev\devfish-shares.git\docker-selenium-aspnet45\SeleniumDockerTest\Program.cs:line 44

--> 

## To Reproduce
Reach out to me for a demo of the problem, it would be easy than trying to repro.
Easy route is to provision up the docker file.  Location of docker file is https://hub.docker.com/r/jhealy62/devfish .

Git repo with source files here - https://github.com/jhealy/aspnet45-docker-selenium 

run local asp.net 4.5
build out docker container using buildit.ps1
buildit.ps1 leaves you inside container
cd \SeleniumTests
# verify web server works
curl http://localhost -UseBasicParsing
# run our test
.\SeleniumDockerTest.exe http://localhost
Boom.  Consisten with chrome or ff tests inside docker.  Outside docker is fine.

Github repo with goodies - https://github.com/jhealy/devfish-shares/tree/master/docker-selenium-aspnet45 

**Repro**

	docker build -f dockerfile -t aspnet45 .
	docker run -d --name aspnet45run -p 5000:80 aspnet45
Verify we are serving web pages
	Invoke-WebRequest http:\\localhost:5000 -UseBasicParsing
Connect to container with interactive ps
	docker exec -it aspnet45run powershell
Inside the container – make sure we can hit website
	Invoke-WebRequest http://localhost -UseBasicParsing
Extract out firefox, which we copy in with the docker file 
	Cd \seleniumtests\assets
	.\firefox_setup_66.0.3.exe -ms
Run selenium console app, which works fine outside container
	Cd \
	Cd  seleniumtests
	.\SeleniumDockerTests.exe http://localhost

Then I cry miserably cause I  get the network timeout.   Error dump below.  Same thing for Chrome and FF with variance on the namespaces.

DOCKERFILE
# The `FROM` instruction specifies the base image. We are extending the `microsoft/aspnet` image.
FROM microsoft/aspnet

RUN mkdir seleniumtests 
RUN mkdir seleniumtests/assets

# COPY IN THE WEBSITE
COPY ./MvcHelloWorld45/MvcHelloWorld45/bin/Publish/ /inetpub/wwwroot

# copy in the tests
COPY ./SeleniumDockerTest/bin/Release/ /seleniumtests 

# chromedriver is bundled into the official nuget
# make sure geckodriver is there with the selenium tests
COPY ./assets/geckodriver-v0.24.0-win64/ /seleniumtests

# COPY IN FF
COPY ./assets/firefox /seleniumtests/assets

# choco chrome takes a bit
RUN powershell -Command Install-PackageProvider -name chocolatey -Force
RUN powershell -Command Set-PackageSource -Name chocolatey -Trusted
RUN powershell -Command Get-PackageSource
RUN echo 'Install Chrome via chocolatey...'
RUN powershell -Command Install-Package GoogleChrome -MinimumVersion 74

TIMEOUT ERROR
PS C:\seleniumtests> .\SeleniumDockerTest.exe http://localhost

1556475837609   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\rust_mozprofile.PjTNZggGakAN"

!!!error:OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49164/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at SeleniumDockerTest.Program.DoFirefoxTests() in C:\dev\devfish-shares.git\docker-selenium-aspnet45\SeleniumDockerTest\Program.cs:line 160

GOOGLE TEST
        private static void DoChromeTests()
        {
            IWebDriver chromeDriver;
            try
            {
                ChromeOptions option = new ChromeOptions();
                option.AddArguments("--headless");
                // fix set from https://bugs.chromium.org/p/chromium/issues/detail?id=942023
                option.AddArguments("--window-size=1920,1080");
                option.AddArguments("--disable-features=VizDisplayCompositor");
                option.AddArguments("--disable-gpu");
                //option.AddArgument("--no-sandbox");
                //option.AddArgument("--dns-prefetch-disable");

                Console.WriteLine("chrome options include --headless --dns-prefetch-disable --disablefeatures");
                using (chromeDriver = new ChromeDriver(option))
                {
                    chromeDriver.Navigate().GoToUrl(m_targetUrl);

                    string msg = "hello world";
                    Console.WriteLine($"CheckWebElements('{msg}')={CheckWebElements(msg,chromeDriver)}");
                    msg = "Matias Bruno";
                    Console.WriteLine($"CheckWebElements('{msg}')={CheckWebElements(msg,chromeDriver)}");

                    chromeDriver.Close();
                    chromeDriver.Quit();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("!!!error:" + ex.ToString());
            }
        }

FIREFOX TEST
        private static void DoFirefoxTests()
        {
            Console.WriteLine("firefox tests commencing");
            string fflocation = @"C:\Program Files\Mozilla Firefox\firefox.exe";
            Console.WriteLine("BrowserExecutableLocation=" + fflocation);
            IWebDriver firefoxDriver;
            try
            {
                FirefoxOptions options = new FirefoxOptions();
                options.BrowserExecutableLocation = fflocation;                
                options.AddArgument("--headless");
                Console.WriteLine("--headless");

                using (firefoxDriver = new FirefoxDriver(options))
                {
                    firefoxDriver.Navigate().GoToUrl(m_targetUrl);

                    string msg = "hello world";
                    Console.WriteLine($"CheckWebElements('{msg}')={CheckWebElements(msg, firefoxDriver)}");
                    msg = "Matias";
                    Console.WriteLine($"CheckWebElements('{msg}')={CheckWebElements(msg, firefoxDriver)}");

                    firefoxDriver.Close();
                    firefoxDriver.Quit();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("!!!error:" + ex.ToString());
            }
            Console.WriteLine("firefox tests completed");
        }

## Expected behavior

Expect test to run and parse the website

## Test script or set of commands reproducing this issue
running test fails it.  kicks error out.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Docker windows container 10.0.1744
Browser: Chrome and Firefox 
Browser version: Chrome 74, Firefox  66.0.3
Browser Driver version: nugets v3.141
Language Bindings version: C#, .net 4.5
Selenium Grid version (if applicable): n/a

**Comment by diemol** [comment]
Hi @jhealy,
What you are trying to do sounds really great, running Chrome and Firefox headless in Windows containers! Nevertheless, we have not do anything similar in this project and we have only limited ourselves to linux based docker containers for those purposes. With my little knowledge of Windows containers, it just looks like Chrome could not start (`[0427/172326.783:ERROR:browser_gpu_channel_host_factory.cc(139)] Failed to launch GPU process.`), therefore the timeout error since it cannot reach the browser. Perhaps focus on that.

Having said that, I don't see how this is a Selenium issue. I understand that you are trying to build a docker image and you are looking for help to troubleshoot this, but this is not a help forum and speciall for something that could be seen as off topic. Perhaps you can try to reach out to the MS repos https://github.com/Microsoft?utf8=%E2%9C%93&q=docker&type=&language= and maybe they have more expertise in these type of containers. I'll personally watch your repo since it is an interesting idea, sorry that we could not be more helpful.

**Comment by jhealy** [comment]
I'll work it with the nogpu option.  Note firefox crashes with a similar issue.  FF appears to start here.

PS C:\seleniumtests> .\SeleniumDockerTest.exe http://localhost
Target Url=http://localhost
firefox tests commencing
BrowserExecutableLocation=C:\Program Files\Mozilla Firefox\firefox.exe
--headless

1556475837609   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\rust_mozprofile.PjTNZggGakAN"

!!!error:OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:49164/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   --- End of inner exception stack trace ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at SeleniumDockerTest.Program.DoFirefoxTests() in C:\dev\devfish-shares.git\docker-selenium-aspnet45\SeleniumDockerTest\Program.cs:line 160

**Comment by jhealy** [comment]
GPU error cleared for chrome.  Definitely starts and fails.  Updated repo with chrome messages and ff as well.  Will update issue above.

**Comment by jhealy** [comment]
Timeout issue resolved by installing websocket into dockerimage.  New issues, but will post separate.

<pre>
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8
RUN powershell -Command Add-WindowsFeature Web-WebSockets
RUN powershell -Command Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
RUN powershell -Command choco install googlechrome -y
RUN powershell -Command choco install firefox -y
</pre>

**Comment by n777ty** [comment]
7165 is not a duplicate of this.. they are different issues..

**Comment by diemol** [comment]
They are both related to running Selenium inside a Windows docker image, and the [comment](https://github.com/SeleniumHQ/selenium/issues/7150#issuecomment-487752781) I mentioned above still applies. Whereas this is something interesting, there is not really a bug caused by Selenium, if you are looking for help I pointed out resources to get it, you could also ask in [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
