### ISSUE TITLE
test no es estable java, ejecuta varias veces y aveces funciona y otras no #java #selenium

### ISSUE THREAD

**Issue by cristian-ramirez-b** [SeleniumHQ/selenium#7155]
buenas tardes, tengo problemas con los test hechos con firefox y selenium, ide netbeans java

el problema es que los casos no son estables, por ejemplo lo ejecuto 10 veces de las cuales 1 o 2 test me sale error, y son errores de tiempo entre selenium y el software, utilizo wait implicito, explicito de 10 segundos  y sleep, tambien un metodo que analiza los tiempos de javascript, pero aun asi no es estable, otro problema es que selenium le ingresa los parametros al software y aveces no los reconoce, ejemplo ingresar el nombre, selenium lo ingresa pero al darle click al boton sale la alerta que falta ingresar el nombre, manualmente el software no falla y su lenguaje es php, javascript y ajax.-...
estas fallas pueden ser selenium, el driver de firefox o como tal compativilidad con el software o puede ser codigo, muchas gracias por su ayuda

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
