### ISSUE TITLE
Selenium does not scroll element high enough if there is a navigation bar with position: fixed

### ISSUE THREAD

**Issue by aaltat** [SeleniumHQ/selenium#7159]
## 🐛 Bug Report

When page contains a navigation bar, which type `position: fixed` and page contains lots of elements, so that Selenium scrolls the element in view, before the element is clicked. Then Selenium does not scroll the element high enough in the browser window so that it could successfully click the element. 

Instead Selenium will scroll the element to the edge of the browser window, but because there is navigation bar, which type position: fixed, the element is behind the navigation bar. Therefore Selenium will raise an error:
```
Traceback (most recent call last):
  File "selenium_test.py ", line 7, in <module>
    element.click()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <p id="p29">...</p> is not clickable at point (628, 713). Other element would receive the click: <ul>...</ul>
  (Session info: chrome=74.0.3729.108)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-48-generic x86_64)
```

## To Reproduce
https://gist.github.com/aaltat/bff3d0511e306abb2abb9c8373343eed#file-page-html
https://gist.github.com/aaltat/bff3d0511e306abb2abb9c8373343eed#file-selenium_test-py

## Expected behavior
I did expect element to be scrolled in view and the click to be successful.

## Test script or set of commands reproducing this issue
See the gist in above. 

## Environment

OS: Ubuntu 18.04 LTS
Browser: Chrome and Firefoc
Browser version: Chrome:  74.0.3729.108, Firefox: 66.0.3
Browser Driver version: ChromeDriver 74.0.3729.6, geckodriver 0.24.0 ( 2019-01-28)
Language Bindings version: Python 3.7.1
Selenium Grid version (if applicable): Not used.

**Comment by lmtierney** [comment]
Selenium itself does not do the scrolling of elements, that is handled by the vendor webdrivers. The behavior defined for the webdriver in order to scroll this element into view [is defined here](https://w3c.github.io/webdriver/#dfn-scrolls-into-view).

If you think that behavior should change, please raise an issue here https://github.com/w3c/webdriver/issues

**Comment by aaltat** [comment]
Thanks for the quick response and clear explanation.
