### ISSUE TITLE
Element is not scrolled into view before click() when partially covered by scrollabar

### ISSUE THREAD

**Issue by lqc** [SeleniumHQ/selenium#716]
## Environment:

Windows 7, Selenium 2.46.0, Firefox 31.6.0 / 38.0.5
## Steps to reproduce

Open this page:

```
<!DOCTYPE html>
<html>
    <head><title>Foo bar</title></head>
    <body>
        <div style="height: 200px; width: 200px; overflow: auto">
            <div id="filler" style="height: 175px; width: 240px; border: 1px solid red;"></div>
            <button type="button" style="height: 40px; box-sizing: border-box" id="btn">CLICK ME</button>
        </div>
        <script type="text/javascript">
        document.getElementById("btn").addEventListener("click", function(event) {
            event.stopPropagation();
            event.currentTarget.style.color = "red";
        });
        </script>
    </body>
</html>
```

with the following script:

```
ff.get("http://localhost:8000/test.html")
e = ff.find_element_by_id("btn")
print e.is_displayed()
e.click()
```
## Expected:

As the button is supposed to be clicked in the center, the container should be scrolled so that it is fully visible.
## Actual:

On Firefox 31 (native events), the click never reaches the button (text color does not change). I seems it lands on the scrollbar.

On Firefox 38 (synthetic events), the click is generated, but no scrolling happens. If I increase the height of `filler` element by another 25px the scrolling does happen.

Same happens when using action chains directly, which seems to indicate that scrollbars are completely transparent to synthetic events.

**Comment by doberkofler** [comment]
+1

**Comment by barancev** [comment]
A test added by 4e5969142b2ee464d6852124b80c08301d5c0326

**Comment by barancev** [comment]
Related geckodriver issue: https://github.com/mozilla/geckodriver/issues/915

**Comment by barancev** [comment]
I've removed the "firefox" label because this issue had been fixed in geckodriver, and hardly ever will be fixed in legacy xpi-based Firefox driver.

**Comment by diemol** [comment]
Seems this was solved in GeckoDriver and based on the previous comment, that is the status where things will stay.
