### ISSUE TITLE
Add capability to disable 'Don't let this page create more messages' message for IE browser

### ISSUE THREAD

**Issue by ckzgraphics** [SeleniumHQ/selenium#7162]
## 🚀 Feature Proposal

Add a custom capability to disable 'Don't let this page create more messages' popup for IE browser.

Currently, this popup can be disabled by adding the website to 'trusted site' section.

Ref-
- https://answers.microsoft.com/en-us/ie/forum/all/disable-dont-let-this-page-create-more-messages-on/d77d2ab7-0044-4704-b69a-79fa4da99221
- https://github.com/SeleniumHQ/selenium/issues/3791
- https://stackoverflow.com/questions/54145363/selenium-internetexplorer-11-succesive-alert-text-empty-on-the-second-alert

## Steps to reproduce

1. Open URL- https://www.joecolantonio.com/SeleniumTestPage.html
2. Click on the element ( XPATH- .//a[contains(.,'Alert Dialog')] )
3. Accept alert
4. Click on the element ( XPATH- .//a[contains(.,'Alert Dialog')] )

## Test Configuration

OS: Windows 10
Browser: IE 11
IE Driver Version: 3.141.5
Selenium Version: 3.14.0

**Comment by diemol** [comment]
We normally leave these feature requests open for a while to see if the community has a strong interest in them, if there is a good and wide use case to support or if somehow a feature request is aligned with a current development.

This request, however, has not gotten any traction or interest. So I will go ahead and close it.
