### ISSUE TITLE
Returning blank page on a specific website.

### ISSUE THREAD

**Issue by nzaitseva** [SeleniumHQ/selenium#7168]
I'm getting a blank page when I try to open shops.coles.com.au. 

When I try to open coles.com.au it works, but if I try to visit the subdomain it shows a blank page. Also, if I open websites like google.com it works.

An example when it returns a blank page: 

> 
> from selenium import webdriver
> driver = webdriver.Firefox()
> driver.get(https://shop.coles.com.au/a/a-national/everything/browse)

However this page is shown correctly:
https://coles.com.au

## Environment

OS: Linux Debian 9
Browser: Chrome, Firefox
Browser version: Mozilla Firefox 60.6.1, Google Chrome 72.0.3626.119

Browser Driver version: ChromeDriver 73.0.3683.68 , GeckoDriver v0.24.0
Language Bindings version: python

**Comment by adiohana** [comment]
this is related to:
https://stackoverflow.com/questions/54587922/chromedriver-cause-status-code-429-when-request

there is a JS code running and generating a request to the server every time it identifies that you are using "Selenium" or "Driver" and then server is returning 429 (too many requests) error code.

You can filter out the specific JS to avoid this issue. You can use extensions in Chrome/Firefox (in case you are not running headless). If you do run in headless mode, then soon we will add the filter URL's feature in Chrome DevTools API - https://github.com/SeleniumHQ/selenium/issues/6667

**Comment by p0deje** [comment]
Closing per @adiohana's comment. Please comment if you think the issue should be re-opened.
