### ISSUE TITLE
Possible inconsistent log level regarding node server exception

### ISSUE THREAD

**Issue by khatchad** [SeleniumHQ/selenium#7169]
## 🐛 Bug Report

The level (`INFO`) of this log statement may not be consistent with its context (exception being thrown):

https://github.com/SeleniumHQ/selenium/blob/490f2d5ae0f6fb6f8fe23e6ea87197f80091032a/java/server/src/org/openqa/selenium/grid/node/httpd/NodeServer.java#L146-L148

**Comment by shs96c** [comment]
This is working as intended. The comment above the exception explains the reasoning.
