### ISSUE TITLE
[Ruby, 3.142.0] String does not have #dig method

### ISSUE THREAD

**Issue by boris-petrov** [SeleniumHQ/selenium#7178]
I get the following error after upgrading to version `3.142.0` from `3.141.0`:

```
TypeError:
       String does not have #dig method
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/response.rb:84:in `add_backtrace'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/response.rb:42:in `error'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/oss/bridge.rb:587:in `execute'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/remote/oss/bridge.rb:328:in `click_element'
     # ./features/build/tmp/jrubyExec/gems/selenium-webdriver-3.142.0/lib/selenium/webdriver/common/element.rb:74:in `click'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.18.0/lib/capybara/selenium/node.rb:97:in `click'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.18.0/lib/capybara/node/element.rb:158:in `block in click'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.18.0/lib/capybara/node/base.rb:83:in `synchronize'
     # ./features/build/tmp/jrubyExec/gems/capybara-3.18.0/lib/capybara/node/element.rb:158:in `click'
```

As you see, I'm using JRuby `9.2.7.0`, Capybara `3.18.0`, Selenium `3.142.0` and running with the legacy Firefox driver on Firefox version `47.0.2`.

This was working fine with Selenium `3.141.0`.

How can I help?

## Environment

OS: Arch Linux
Browser: Firefox
Browser version: 47.0.2

**Comment by p0deje** [comment]
Thanks for a bug report. Please try updating selenium-webdriver to 3.142.1 - it should be fixed now.

On a side note, keep in mind that old Firefox won't be supported in Selenium 4.

**Comment by p0deje** [comment]
772d18645feb63795cd3f6bfea882ab2989c21bc

**Comment by boris-petrov** [comment]
@p0deje - thanks for the fix, I'll try it out in a bit.

We talked on Slack a bit about that and what worries me is that by removing the legacy Firefox driver, no "old" ES5 browser (which doesn't support the `class` syntax for example) is left on Linux that can be used for testing. So our integration server, which is running Linux, won't be able to test our builds for legacy browsers any more after we update to Selenium 4. Don't you think this is a problem?

**Comment by p0deje** [comment]
@boris-petrov It should still be possible to use legacy Firefox driver through Selenium server but not directly anymore, so you'll still be able to do that, but with a bit of additional work (e.g. download, start server and connect via `:remote`). I'm not sure it's working right now, but we'll sort this out by 4.0 release.

**Comment by boris-petrov** [comment]
@p0deje - oh, that's good to hear! Thanks for the information. There will be documentation on migration I hope. :) Thanks!
