### ISSUE TITLE
WebDriverWait not working correctly when implicitly_wait is set

### ISSUE THREAD

**Issue by pgs-atanistra** [SeleniumHQ/selenium#718]
Example from python docs:

driver = webdriver.Firefox()
driver.get("http://somedomain/url_that_delays_loading")
try:
    element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
    )
finally:
    driver.quit()

and it's working, but dirver.implicitly_wait is set EC methods waits == driver.implicitly_wait

so:
driver.implicitly_wait(60)
WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "myDynamicElement"))

will return TimeoutException after 60 seconds.

**Comment by lukeis** [comment]
This is expected behavior. We document that you shouldn't be mixing them. I recommended to leave implicit waits set to 0 and only use the explicit waits. 

http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits
