### ISSUE TITLE
HTTP TRACE method activated Versions 3.5.0, 3.9.1 3.7.1

### ISSUE THREAD

**Issue by ctrast** [SeleniumHQ/selenium#7183]
OS:
any
Selenium stand alone jar version: 3.5.0, 3.9.1, 3.7.1
Browser:
any

Expected Behavior -
HTTP TRACE method disabled

Actual Behavior -
HTTP TRACE method activated on Selenium Hub port

Actual Behavior -
HTTP TRACE method activated on Selenium Hub port

Steps to reproduce -
curl  -X TRACE http://localhost:4444/

TRACE / HTTP/1.1 200 OK
User-Agent: curl/7.56.1
Accept: */*

/etc/httpd/conf/httpd.conf  file contains "TraceEnable off"
Trace is disabled on the server itself on port 80.

**Comment by shs96c** [comment]
Is this a problem for you? Or is this a general thing to do with securing selenium installations?

**Comment by ctrast** [comment]
This is a problem for us. I have logged am issue on git

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by barancev** [comment]
We can't change anything in already released versions.
Please upgrade, HTTP TRACE method is disabled since version 3.12
