### ISSUE TITLE
Selenium for Python ~ Random StaleElementReferenceException in select.select_by_visible_text

### ISSUE THREAD

**Issue by KiraResari** [SeleniumHQ/selenium#7186]
# Description

I am getting random `StaleElementReferenceExceptions` when calling `select.select_by_visible_text`. This happens even though I am only finding the element right before calling `select.select_by_visible_text`.

# Code Sample

```
select = Select(element = driver.find_element_by_xpath(searchString))
select.select_by_visible_text(str(entry))
```

# Env

* Selenium for Python
* Chrome Driver 74

# Workaround

I used the following Try-Catch Ribbon, and this successfully handles the bug on the first or second iteration 80%, and has never reached the maxIterations yet.

```
while True:
    maxIterations = 10
    try:
        select = Select(element = driver.find_element_by_xpath(searchString))
        select.select_by_visible_text(str(entry))
        break
    except StaleElementReferenceException:
        maxIterations -= 1
        if maxIterations == 0:
            throw
```

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by diemol** [comment]
Closing as we didn't get any more replies from the OP.
