### ISSUE TITLE
MS Edge Chromium not fully supported

### ISSUE THREAD

**Issue by teetime514** [SeleniumHQ/selenium#7188]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by teetime514** [comment]
Microsoft will release a new version of edge based on Chromium
https://www.microsoftedgeinsider.com/en-us/

They also released a webdriver.  Selenium does not currently have built in support for launching the new msedgedriver.exe unless creating a webdriver.Chrome() object and overriding the executable path.

Suggestion is to provide support for this new browser in the same way Firefox, Chrome etc etc are currently supported.

**Comment by diemol** [comment]
@teetime514 it is in process, thankfully a PR is being worked on, please follow #7164 for more details. You could also suscribe to the repo to get updates when the other bindings support it.
