### ISSUE TITLE
Selenium actions class for key board actions are not working using node js

### ISSUE THREAD

**Issue by 9LPittu** [SeleniumHQ/selenium#7191]
The keyboard actions are not working in selenium node js using actions class. Tried in different ways like below , but nothing is working out:

1. await driver.actions({bridge: true}).sendKeys(Key.ENTER).perform()
2. await driver.actions({bridge: true}).sendKeys(Keys.ENTER).perform()
3. await driver.actions({bridge: true}).sendKeys(Keys.ENTER).build().perform()
4. await driver.actions({bridge: true}).sendKeys(Key.ENTER).build().perform()
5. await driver.actions().sendKeys(Keys.ENTER).build().perform()
6. await driver.actions().sendKeys(Key.ENTER).build().perform()
7. await driver.actions().sendKeys(Key.ENTER).perform()
8. await driver.actions().sendKeys(Keys.ENTER).perform()

Another syntax for hover is working well which is : 
const element = await driver.findElement(By.xpath(myxpath)))
await driver.actions({ bridge: true }).move({ duration: 5000, origin: element }).perform()

Your help is much appreciated

**Comment by rakeshnambiar** [comment]
@9LPittu Have you find any solution for this? I too came across the same problem.

@juliemr nice if you could share your thoughts on this.

**Comment by pittgoose** [comment]
@9LPittu What versions are you using?

**Comment by betweenbrain** [comment]
I can report that `driver.actions().sendKeys(Key.ENTER).perform()` is working fine with v3.6.0.

**Comment by jcharnley** [comment]
it doesnt work for me, seems like the browser does not have focus, even tho i've clicked() a few elements... anyone help. i cannot simulate a key.SHIFT

**Comment by titusfortner** [comment]
Actions class was completely overhauled for W3C, and JS didn't get all the updates until Selenium 4.
If this doesn't work for you in Selenium 4.1, please create a new issue with specific reproducible code.
Thanks.
