### ISSUE TITLE
Incorrect duration unit for `nodeStatusCheckTimeout` option

### ISSUE THREAD

**Issue by wjordan** [SeleniumHQ/selenium#7194]
## 💥 Regression Report

There seems to be a duration-unit (ms / sec) regression on the `nodeStatusCheckTimeout` configuration option. The option is currently documented as having milliseconds (`ms`) units, and a default of `5000`:

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/internal/utils/configuration/GridNodeConfiguration.java#L132-L135

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/internal/cli/GridNodeCliOptions.java#L126-L133

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json#L35

However, it is being used as a `Duration.ofSeconds` in the `HttpClient` builder:

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java#L468-L469

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/internal/BaseRemoteProxy.java#L458-L461

https://github.com/SeleniumHQ/selenium/blob/38d5e4440b2c866a78a1ccb2a18d9795a1bdeafd/java/server/src/org/openqa/grid/internal/BaseGridRegistry.java#L63-L69

This causes connection/read timeouts related to node status checks to be 1000 times longer than expected (effectively useless).

Possibly related to #4891, #5218.

A workaround is to configure the option as seconds instead of milliseconds (e.g., set `-nodeStatusCheckTimeout 1` to expect a status-check timeout of 1 second).

I could provide additional reproduction steps / build info etc. if needed, but hopefully this regression should be clear enough through the lines of code quoted above.

**Comment by diemol** [comment]
Apologies for the late reply. This is a known issue in Grid 3.x, which we have very much in mind and won't happen in Grid 4 (currently in the alphas). Since Grid 3.x is not underdevelopment anymore, this issue will be closed (however, the related issue is part of the feature set of Grid 4).
