### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Unrecognized command: POST (Remote webdriver)

### ISSUE THREAD

**Issue by saimneftci** [SeleniumHQ/selenium#7195]
## 🐛 Bug Report

I am working with authenticated page. Using Remote webdriver to handle manually authenticated Firefox browser with passing executor_url. With new selenium session it working well;

with Python 2.7.10, geckodriver 0.24.0, Firefox 52.7.1, selenium 3.8.0
```
>>from selenium import webdriver
>>from selenium.webdriver.common.desired_capabilities import DesiredCapabilities    
>>cap = DesiredCapabilities().FIREFOX
>>cap["marionette"] = False
>>driver = webdriver.Firefox(capabilities=cap)
>>driver.execute_script("return myBalance")
[{u'currency': u'USD', u'balance': 1000.01}]
```
But when I handle it from webdriver.Remote for reuse authenticated browser;

```
>>from selenium import webdriver
>>from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
>>cap = DesiredCapabilities().FIREFOX
>>cap["marionette"] = False
>>new_driver = webdriver.Remote(command_executor=executor_url, desired_capabilities=cap)
>>driver.execute_script("return myBalance")

/python/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Unrecognized command: POST /session/89792e61-b195-3d45-8fad-8cdffa7b5a44/execute/sync
```

## Environment

OS: macos mojave
Browser: Firefox
Browser version: 52.7.1
Browser Driver version: geckodriver 0.24.0
Selenium: selenium 3.8.0

**Comment by cgoldberg** [comment]
> Firefox 52.7.1, selenium 3.8.0

can you try with a newer version of Firefox and the latest version of selenium?   also, don't disable the marionette capability.

**Comment by lmtierney** [comment]
Closing due to lack of response from issue creator
