### ISSUE TITLE
Unable to download Java

### ISSUE THREAD

**Issue by MalenaMiller** [SeleniumHQ/selenium#7196]
## 🐛 Bug Report

Unable to download Java from https://docs.seleniumhq.org/download/

When I navigate to https://docs.seleniumhq.org/download/ 
"Selenium Client & WebDriver Language Bindings" section.
And click on "Download" next to Java. 
Then "This site can’t be reached" error message is appearing

**Comment by lmtierney** [comment]
Seems to be working fine for me. You can also try from here: https://selenium-release.storage.googleapis.com/index.html?path=3.141/

**Comment by MalenaMiller** [comment]
> Seems to be working fine for me. You can also try from here: https://selenium-release.storage.googleapis.com/index.html?path=3.141/

Thank you! 👍
