### ISSUE TITLE
Python - Selenium Chrome webdriver doesn't have components like WidevineCDM

### ISSUE THREAD

**Issue by bhn013** [SeleniumHQ/selenium#720]
I'm trying to use Selenium to open a page and go to Netflix and open a video and play. Once I actually get to the video, I can't load it because I get the error:

Missing Components... Please visit chrome://components, locate the WidevineCdm component...

When going to chrome://components, there aren't any components installed. If I had opened Chrome regularly and navigated to the video like I did in Selenium, I can play it. When I got to chrome://components in regular Chrome, there are more components in there. I'm trying to find out how to import my normal Chrome settings but I can't seem to figure that out. I've tried using ChromeOptions and DesiredCapabilities.CHROME but I couldn't get it to work. I also can't find documentation on all the items inside the DesiredCapabilities.CHROME dictionary. I hope that once I'm able to get normal Chrome settings into the webdriver version, I'd be able to load Netflix videos via Selenium Chrome webdriver.

**Comment by lukeis** [comment]
For issues with Chrome and chromedriver please log them with the chromedriver project:

https://code.google.com/p/chromedriver/issues/list

Also I'd recommend asking on the selenium-users Google group (mailing list)
