### ISSUE TITLE
Wrong element selected when trying to get parent element by tagName.

### ISSUE THREAD

**Issue by David91** [SeleniumHQ/selenium#7200]
## 🐛 Bug Report
When trying to get the parent element using element.findElement(By.xpath("{xpathExpression}")), method returns parent's sibling element.
## To Reproduce

* Go to 6pm.com
* Filter any product ( for example hover "Accessories" and click on "Oval" )
* Select any input field in filters section. F. e. 
`WebElement searchInput = driver.findElement(By.xpath("//input[contains(@placeholder,'Search Color')]"));
`
* Select parent "section element
`WebElement parentSec = searchInput.findElement(By.xpath("//ancestor::section"));
`
## Expected behavior
The first parent should be selected with tag "section", but actually selected first "section" element in HTML, which is sibling of searchInput's parent "section" element.
P. S. Right section is selected when trying to find element by searching
`WebElement searchResult = driver.findElement(By.xpath("//input[contains(@placeholder,'Search Color')]//ancestor::section"));`
## Environment

OS: Windows 10
Browser: Chrome
Browser version: 74.0.3729.131
Browser Driver version: ChromeDriver 74.0.3729.6
Java version: Java 8

**Comment by barancev** [comment]
```WebElement parentSec = searchInput.findElement(By.xpath(".//ancestor::section"));```

**Comment by David91** [comment]
Ah, thank you very much :)
