### ISSUE TITLE
Selenium click on button functionality does not work consistently on Safari (Safari 12.1) browser on MAC (Macos Sierra 10.12.6)

### ISSUE THREAD

**Issue by sajid90** [SeleniumHQ/selenium#7206]
## :bug: Bug Report
Locator: //button[@name='Close']

self.objDriverWait.until(exp_cond.element_to_be_clickable(locator_value)
obj_element =self.objDriverWait.until(exp_cond.presence_of_all_elements_located(locator_value))
obj_element[0].click()

Button is present / visible / clickable still it through an exception ({ElementNotInteractableException}Message :) 

Same element is working fine on **Chrome and Firefox**

I have tried with **"execute_script"**, it doesn't through an exception but element was not clicked

if self.is_clickable(locator_value, locator_name):
    obj_element = self.objDriver.find_elements(*locator_value)
    self.objDriver.execute_script("arguments[0].click();", obj_element[0])

## Expected behavior

It should perform click operation

## Environment

OS: MAC (Macos Sierra 10.12.6)
Browser:  Safari
Browser version: 12.1
Selenium Grid version (if applicable): 3.141.59.jar
Python: 3.6
Selenium: 3.141.0

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
