### ISSUE TITLE
while running the selenium test case in azure devops getting below errors

### ISSUE THREAD

**Issue by mahammad13** [SeleniumHQ/selenium#7207]
Application : java  
 Using pom.xml file

while running the selenium test cases from eclipse IDE it's working fine  but  We are trying to replicate same in Azure DevOps ....getting below errors.........

Issue1:
session not created: This version of ChromeDriver only supports Chrome version 74.

Issue2:
The driver executable does not exist: D:\a\1\s\src\test\resources\Drivers\chromedriver.exe

please help me on this

**Comment by lmtierney** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
