### ISSUE TITLE
headless chrome download file java

### ISSUE THREAD

**Issue by amishad02** [SeleniumHQ/selenium#7210]
please help with solution for [https://stackoverflow.com/questions/56150874/remote-run-selenium-test-cases-for-download-file-test-using-chrome/56151484#56151484]

**Comment by lmtierney** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
