### ISSUE TITLE
Safari Element Identification Issue

### ISSUE THREAD

**Issue by rajkumar-cp** [SeleniumHQ/selenium#7211]
Detailed steps to reproduce the behavior:

We have a login page where we have username(textbox), password(textbox) and login
button
While trying to enter username and password at some instances of time password field is also getting written to username field itself.
Steps:
1) Clear username field
2) send username value to username field
3)clear password field
4)send password value to password field
5) Click login button

It occurs very randomly. If we try to rerun the failed case again we were not able to reproduce this issue. Could you please let us know the reason for this issue.

We had close to 700 cases failed because of this issue out of 3000 cases.

## Expected behavior

Elements should be interacted properly

## Environment

OS: iOS 10.12.6
Browser: Safari 
Browser version: 
Browser Driver version: 12.1
Selenium Grid version (if applicable): 3.11.0

**Comment by BadriE2179** [comment]
Can you try the following methods :- 

a) Try hardcoding sleep of 1 second before entering value into password text field
b) Highlight the element before entering value into password text field
c) click and then enter the value

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by ramonmedeiros** [comment]
Safari usually does not wait for browser loading time. Everytime you gonna deal with an element, verify if you are using the keywords for wait

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
