### ISSUE TITLE
ActionChains methods not working on Safari Browser

### ISSUE THREAD

**Issue by sajid90** [SeleniumHQ/selenium#7213]
I am performing mouse hover operation on web element.

ActionChains(self.objDriver).move_to_element(obj_element) doesn't return any action

obj_element = WebDriverWait(self.objDriver, 10).until(exp_cond.visibility_of_element_located(locator_value))
act_hover = ActionChains(self.objDriver).move_to_element(obj_element)
act_hover.perform()

or
ActionChains(self.objDriver).click(obj_element).perform()

or
self.objActionChains.context_click(obj_element)

## Expected behavior
Action chains methods should work

## Environment

OS: MAC (Macos Sierra 10.12.6)
Browser: Safari
Browser version: 12.1
Selenium Grid version (if applicable): 3.141.59.jar
Python: 3.6
Selenium: 3.141.0
![mouse_hover](https://user-images.githubusercontent.com/36481052/57848906-9f045700-77f7-11e9-81f5-b15ee79293d3.png)

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.

**Comment by sajid90** [comment]
Open Safari (ver- 12.1) browser from webdriver on MAC (Macos Sierra 10.12.6) and navigate to site where mouse hover is required and do that by executing below code which is working for Chrome, Firefox and Edge 

obj_element = WebDriverWait(self.objDriver, 10).until(exp_cond.visibility_of_element_located(locator_value))
act_hover = ActionChains(self.objDriver).move_to_element(obj_element)
act_hover.perform()

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) instead of a narrative text.

**Comment by jimevans** [comment]
How about `OpenQA.Selenium.Interactions.BasicMouseInterfaceTest.HoverPersists` from the .NET test suite of the Selenium project? That consistently fails for Safari according to the [WebDriver Herald](https://webdriver-herald.herokuapp.com). Yes, it indicates a bug in the Safari driver, rather than Selenium itself, but it’s a publicly available, reproducible test case.

**Comment by sajid90** [comment]
I am using Python3.6 language and launching the browser using selenium grid 

Launch Hub: Copy the jar file in "C:/selenium" and used same machine for hub and node
cd C:\selenium
java -jar selenium-server-standalone-3.141.59.jar -role hub -port 7777

Register Node
java -jar selenium-server-standalone-3.141.59.jar -role node -hub http://105.133.7.119:7777/grid/register -host 105.133.7.119 -browser browserName=MicrosoftEdge

command_executor = 'http://127.0.0.1:7777/wd/hub'
desired_capabilities = None
desired_capabilities = DesiredCapabilities.SAFARI
desired_capabilities["maxInstances"] = 5
desired_capabilities['platform'] = platform
desired_capabilities['loggingPrefs'] = {'browser_type': 'ALL'}
self.obj_driver = webdriver.Remote(
                        command_executor=command_executor,
                        desired_capabilities=desired_capabilities)

**Comment by barancev** [comment]
@jimevans It's cook we have already a reproduction scenario. I'll check the Java test suite too and add this scenario if there is no one.

**Comment by courtenayt** [comment]
Is there any update on the status of this fix? We are in need of it for a lot of our automation tests to be able to run on Safari.

**Comment by sajid90** [comment]
Hi @barancev ,
Is there any update on this?

**Comment by mwilkows** [comment]
Hi @barancev 
Is there any update on this?

**Comment by titusfortner** [comment]
Unfortunately, the issue with this is the driver's responsibility, so there isn't anything we can do in this code base. Alexei was just talking about adding a test in Selenium to show that it wasn't working in Safari.

You can see in the WPT results the `test_touch_pointer_properties` is verifying the `pointerMove` works correctly, which is what is used for hovering. You can see the status of that test here: https://wpt.fyi/results/webdriver/tests/perform_actions/pointer.py
