### ISSUE TITLE
IE resize/rerender Issue

### ISSUE THREAD

**Issue by AndreasKarz** [SeleniumHQ/selenium#7216]
## 🐛 Bug Report

Looks like the same issue like [6395](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6395) but is not solved.

The main problem is that the behaviour is not uniform. How @lukeis write in the post above, in my opinion a screenshot is a screenshot not a image of the page.

If this is the case, please use ALL browsers, not only IE.

What would be much more important, however, is that the size is always uniform. Because currently the sizes of the screenshots on the same page differ by between 5 and 20 pixels. It seems that the screenshot is taken while the size is changing or that the stitching is working incorrectly. So the screenshot function is simply useless for IE, that the results are so EVERYTHING different and no serious image comparison is possible.

We URGTLY need a reliable solution where we can disable this. ie.enableFullPageScreenshot = false in the Capabilities doesn't work, no matter if we go with browserstack.ie.driver 2.53.1 to an old version or work with the current one. 

The tool can only be used professionally if you get reliable and consistent results. False positives are fatal in automated testing.

## To Reproduce
Make a screenshot in IE

## Expected behavior
Identical screenshots of a unchanged page so that we can use the screenshots for image comparison in automated testing

## Environment

OS: Windows  10
Browser: IE
Browser version: All versions
Browser Driver version: browserstack.ie.driver 2.53.1

ie.enableFullPageScreenshot false 
os Windows 
build IEFullpage 
browser IE 
os_version 10 
browserstack.ie.driver 2.53.1 
browser_version 11.0 
resolution 1024x768 
acceptSslCert false 
detected_language selenium/3.14.0 (java mac) 
browserstack.useChromeDriver true 
browserstack.seleniumLogs true 
browserstack.appiumLogs false 
browserName IE

**Comment by jimevans** [comment]
The current version (3.141.59) of the IE driver follows the [W3C WebDriver Specification](https://w3c.github.io/webdriver/), which defines screenshots as only of the current browser view port. There is no longer any resizing done to the browser for taking screenshots. The capability you reference no longer has any effect in the IE driver. The behavior to attempt creation of so-called “full page” screenshots is unlikely to reappear in the IE driver unless and until a thorough rearchitecture of the driver is undertaken. Given these restrictions, I’m a bit unclear on the action you’d like to see taken. If, using the most recently released driver, and capturing only the visible view port, you are seeing differences, can you provide a complete example where that’s the case?

As an aside, I understand the frustration when things aren’t working properly, but the inflammatory tone of some of your comments is not conducive to a meaningful conversation. Please remember that the maintainers of Selenium (and the IE driver in particular) are not paid to work on the project. Using phrases like “completely useless,” “can only be used professionally,” and “are fatal,” come across as off-putting and judgmental, and can immediately cause your correspondent to become defensive and less willing to respond to (perceived or actual) hostility.

**Comment by jimevans** [comment]
Closing after no response from reporter after nearly one month. If you wish to provide the requested information, we can reopen, or you can open another issue.
