### ISSUE TITLE
Make driver.save_screenshot accept pathlib.Path objects.

### ISSUE THREAD

**Issue by carlosplanchon** [SeleniumHQ/selenium#7221]
## 🚀 Feature Proposal

On Python 3.6+
Make driver.save_screenshot accept pathlib.Path objects.

## Motivation

Better consistency of code that use that kind of abstractions.
(avoiding use of as_posix() method of pathlib.Path).

**Comment by cgoldberg** [comment]
`save_sreenshot()` currently accepts a string-based path... What's the advantage of `pathlib`?

We also need to support Python 2.7, where `pathlib` does not exist.

**Comment by carlosplanchon** [comment]
Ok. I'll come back in 2020. C:

**Comment by cgoldberg** [comment]
closing this for now.. will reconsider when we eventually drop Python 2 support.
