### ISSUE TITLE
Chromedriver hangs after quit

### ISSUE THREAD

**Issue by apollos124** [SeleniumHQ/selenium#7235]
## 🐛 Bug Report

OS: 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 GNU/Linux (Docker container)
Browser: Chrome
Browser version: 74.0.3729.169
Browser Driver version: Chromedriver 74.0.3729.6
Language Bindings version:  Ruby 2.6.2

I use Selenium with Chromedriver in my Docker container. I've noticed that after a job is finished and I invoke `driver.quit` the process is still hanging. I'm not using a selenium hub but I think it should work anyway. Here's what I have:

Dockerfile:
```
...
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get -y install google-chrome-stable
RUN wget -q https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip -d /usr/local/bin
RUN rm -f chromedriver_linux64.zip
...
```

Example of a Sidekiq job execution:
```
      def call
        do_stuff
      ensure
        capybara.driver.quit # so it should quit the process
      end
```

And if I type `ps aux` I can see a lot of processes like:
```
root      8085  0.0  0.2 102572 11768 ?        Sl   16:41   0:00 /usr/local/bin/chromedriver --port=9624
root      8107  0.2  0.0      0     0 ?        Z    16:41   0:00 [chrome] <defunct>
root      8109  0.3  0.0      0     0 ?        Z    16:41   0:00 [chrome] <defunct>
root      8120  0.0  0.0      0     0 ?        Z    16:41   0:00 [cat] <defunct>
root      8121  0.0  0.0      0     0 ?        Z    16:41   0:00 [cat] <defunct>
```

Is it something already reported or should I add something particular to the configuration? In my `Capybara` config I already have `no-sandbox` and `headless` options available.

**Comment by diemol** [comment]
This is not a Selenium bug as metioned but rather a question. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
