### ISSUE TITLE
Issue running webdriverio tests on IE11 using selenium grid

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7236]
**Environment:**
    **WebdriverIO version:** 4.14.2
    **Mode:** WDIO Testrunner (sync)
    **Browser name and version:** IE 11
    **Host machine:** Mac 10.13.6
    **Guest machine:** Windows 8.1
    **selenium standalone:** selenium-server-standalone-3.141.59.jar
    **IE driver:** 32 bit 3.14.0

**Config of WebdriverIO**
```
  host: '<host machine ip >',
  port: 4444,
  path: '/wd/hub',
  specs: [`${pathToTests}*.js`],
  deprecationWarnings: false,
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'internet explorer',
      version: 11,
      platformName: 'windows 8.1',
    }
  ],
  sync: true,
```
**Issue Description:**
Unable to execute webdriverio tests on IE using selenium grid. Getting exception:
org.openqa.grid.common.exception.CapabilityNotPresentOnTheGridException: cannot find : Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., platformName: windows 8.1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.14.2}, rotatable: true, version: 11}

**To Reproduce**
I am running windows 8.1 VM inside virtualbox on mac host. This is done in order to be able to run IE tests on mac.
The Mac is running a Selenium-Grid hub.
The Windows VM on Mac is running a Selenium node that hooks up to the hub.
I have tested that VM is able to ping my Mac. This is done by changing the value of 'Attached To' in the Network setting of VM to Bridged Adapter.
The whole set up is described here:
http://kprakobkit.github.io/how-to-setup-selenium-webdriver-to-run-in-ie-on-a-mac/
On my host machine, when I go to http://localhost:4444/grid/console, I can see IE node as well.

**Expected behavior**
IE browser should get launched inside windows VM on running test

**Actual behavior**
Getting the exception mentioned above

**Comment by diemol** [comment]
@pk-saxena 
What are the capabilities you are setting on the node running inside the VirtualBox VM?

**Comment by pk-saxena** [comment]
> @pk-saxena
> What are the capabilities you are setting on the node running inside the VirtualBox VM?  
capabilities: [
    {
      browserName: 'internet explorer',
      version: 11,
      platformName: 'windows 8.1',
    }
  ]

**Comment by diemol** [comment]
Can you please paste the whole configuration of the Selenium Node?

**Comment by pk-saxena** [comment]
browserTimeout: 0

debug: false

host: <host ip>

port: 43570

role: node

timeout: 1800

cleanUpCycle: 5000

maxSession: 5

capabilities: Capabilities {browserName: internet explorer, platform: WIN8_1, platformName: WIN8_1, seleniumProtocol: WebDriver, server:CONFIG_UUID: 4fc63012-1ea9-4b81-ab01-48c...}

downPollingLimit: 2

hub: http://<host ip>:4444/grid/register/

id: http://<node ip>:43570

nodePolling: 5000

nodeStatusCheckTimeout: 5000

proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy

register: true

registerCycle: 5000

remoteHost: http://<node ip>:43570

unregisterIfStillDownAfter: 60000

**Comment by diemol** [comment]
The issue lays on the node configuration, you are requesting a browser version that is not present in the capabilities of the node.
Also, I am not 100% sure, but I think the platform names need to match as well.
Please double check the node configuration.

If there are more questions, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
