### ISSUE TITLE
Better JavaScript API Documentation

### ISSUE THREAD

**Issue by ccorcos** [SeleniumHQ/selenium#7242]
I spend 2 days trying to get this to work in a Docker container and finally figured things out.

[Under `Using the Builder API` section]( https://seleniumhq.github.io/selenium/docs/api/javascript/), it would be nice if you explained how to add chrome options. I also did not realized that addArguments was immutable, returning a new options reference. I only discovered this with `strace` and seeing that the arguments weren't passed through to the google-chrome command.

```js
var webdriver = require('selenium-webdriver');
var chrome = require('selenium-webdriver/chrome');
var browser = new webdriver.Builder()
  .forBrowser('chrome')
  .setChromeOptions(new chrome.Options().headless().addArguments(/* ... */))
  .build()
```

**Comment by jleyba** [comment]
That top-level landing page is just a quick overview, it's not meant to include every possible scenario.

The [Builder API docs](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Builder.html#setChromeOptions) show there's a `setChromeOptions()` method. From there you can click-through to see the [API for chrome.Options](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Options.html)

> I also did not realized that addArguments was immutable, returning a new options reference.

[chrome.Options#addArguments](https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/chrome_exports_Options.html#addArguments) returns a self reference, as documented. You can also [click through to the source](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/chrome.js#L357) which confirms this.
