### ISSUE TITLE
kubernetes hub integration

### ISSUE THREAD

**Issue by kfox1111** [SeleniumHQ/selenium#7243]
We're using selenium inside kubernetes and its working pretty well. It would be nice though, if the hub itself was aware of kuberntes and could spin up / down deployments as load increaded/decreased.

**Comment by diemol** [comment]
We have discussed this internally and handling the Kubernetes API is a big effort that would lead into high maintenance, considering the different behaviour between all Kubernetes providers. 

What we will do is to provide a Helm chart to enable users to deploy to Kubernetes, which is being handled at https://github.com/SeleniumHQ/docker-selenium/issues/1184. We also have endpoints `/readyz` that can be queried for the state of the node, there is also a GraphQL endpoint that will let the user know the current size of the queue, and based on that, they can use a native Kubernetes cient to scale the Grid up. 

We will also spend some time documenting the use cases, but this will be probably treated after we do a Grid 4 release.

I will close this issue for now and folks can follow the other issue I linked above.

**Comment by kfox1111** [comment]
you wouldn't need to handle the whole k8s api, just take in a config value saying what deployment to scale and use the k8s scaling api to tweak the number of replicas based on the queue and a max config value? Just a thought.

I could see wiring this to the horizontal pod autoscaler via some plumbing too but I don't think normal users can do that, just cluster admins? so may be harder for folks to use.
