### ISSUE TITLE
Issue with clearing cookies/starting a clean session in IE11

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7246]
Environment:
**WebdriverIO version:** 4.14.2
**Mode:** WDIO Testrunner (sync)
**Browser name and version:** IE 11
**selenium standalone**: selenium-server-standalone-3.141.59.jar
**IE driver:** 32 bit 3.14.0

**Config of WebdriverIO**
  specs: [`${pathToTests}*.js`],
  deprecationWarnings: false,
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'internet explorer',
      platform: 'WIN8_1',
      platformName: 'windows',
      ignoreZoomSetting: true,
      ignoreProtectedModeSettings: true,
      IE_ENSURE_CLEAN_SESSION: true,
      logLevel: debug
    }
  ],
  sync: true,

**Issue Description:**
Unable to start a clean session in IE. Whenever I launch a new test, IE is already signed in with last user login

**Expected behavior**
IE browser should start a new session everytime

**Comment by jimevans** [comment]
If those are the capabilities being passed across the wire (without modification) by WebDriver.io, then no, that absolutely would not trigger the session cleanup code in the IE driver. I can say that I used this feature of the IE driver (from .NET code) just yesterday, so I’m quite certain it’s not globally broken for all users.

Since WebDriver.io is not a library created or maintained by the Selenium project, you’ll need to supply the actual JSON being passed over the wire to `IEDriverServer.exe` in the new session request. Without that data, it is impossible to render further assistance.

**Comment by pk-saxena** [comment]
**Config for the hub :**
browserTimeout : 0
debug : false
host : <host machine ip>
port : 4444
role : hub
timeout : 1800
cleanUpCycle : 5000
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
registry : org.openqa.grid.internal.DefaultGridRegistry

**Config for the node :**
browserTimeout: 0
debug: false
host: <host machine ip>
port: 45960
role: node
timeout: 1800
cleanUpCycle: 5000
maxSession: 5
capabilities: Capabilities {browserName: internet explorer, platform: WIN8_1, platformName: WIN8_1, seleniumProtocol: WebDriver, server:CONFIG_UUID: 5f16f26b-39da-425b-97b3-76c...}
downPollingLimit: 2
hub: http://<host ip>/grid/register/
id: http://node ip:45960
nodePolling: 5000
nodeStatusCheckTimeout: 5000
proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy
register: true
registerCycle: 5000
remoteHost: http://node ip:45960
unregisterIfStillDownAfter: 60000

**selenium hub logs:**
INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {IE_ENSURE_CLEAN_SESSION: true, browserName: internet explorer, handlesAlerts: true, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, javascriptEnabled: true, locationContextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., platform: WIN8_1, platformName: windows, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.14.2}, rotatable: true}

**selenium node logs:**
02:46:00.528 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "IE_ENSURE_CLEAN_SESSION": true,
  "browserName": "internet explorer",
  "handlesAlerts": true,
  "ignoreProtectedModeSettings": true,
  "ignoreZoomSetting": true,
  "javascriptEnabled": true,
  "locationContextEnabled": true,
  "loggingPrefs": {
    "browser": "ALL",
    "driver": "ALL"
  },
  "platform": "WIN8_1",
  "platformName": "windows",
  "requestOrigins": {
    "url": "http:\u002f\u002fwebdriver.io",
    "version": "4.14.2",
    "name": "webdriverio"
  },
  "rotatable": true
}

**Comment by jimevans** [comment]
What is `IE_ENSURE_CLEAN_SESSION`? I had assumed it was a constant you’d defined somewhere, but it looks as if that’s the literal capability name you’re attempting to use. The correct capability name is `ie.ensureCleanSession`.

**Comment by pk-saxena** [comment]
@jimevans 
updated capabilities -
  capabilities: [
    {
      browserName: 'internet explorer',
      platform: 'WIN8_1',
      platformName: 'windows',
      ignoreZoomSetting: true,
      ignoreProtectedModeSettings: true
      resolution: '1024x768',
      'ie.ensureCleanSession': true,
      logLevel: debug
    }
  ]
Still getting same issue. Clean session is not initiated. IE is always launched with last user login.

**Comment by jimevans** [comment]
Once again, I really need to see the actual JSON being sent across the wire for the new session command. Without that, rendering further assistance is impossible. You could (1) use the IE driver directly instead of through the grid, if WebDriver.io supports that, (2) have the IE driver create a log file, or (3) bump up the log verbosity on the node so that the command output is given. I’m sorry, but I am unable to provide detailed instructions for how to do any of those in your environment.

**Comment by pk-saxena** [comment]
@jimevans 
On increasing the log verbosity, the result of new session command can be seen below:
```
[15:14:29]  COMMAND	POST 	 "/wd/hub/session"
[15:14:29]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"internet explorer","platform":"WIN8_1","platformName":"windows","ignoreZoomSetting":true,"ignoreProtectedModeSettings":true,"resolution":"1024x768","_":"3 more keys: [\"ie.ensureCleanSession\",\"loggingPrefs\",\"requestOrigins\"]"}}
[15:14:30]  INFO	SET SESSION ID 770c15c3-c26f-42ee-8bf9-9d3305e09461
[15:14:30]  RESULT		{"sessionId":"770c15c3-c26f-42ee-8bf9-9d3305e09461","capabilities":{"acceptInsecureCerts":false,"browserName":"internet explorer","browserVersion":"11","pageLoadStrategy":"normal","platformName":"windows","proxy":{},"se:ieOptions":{"browserAttachTimeout":0,"elementScrollBehavior":0,"enablePersistentHover":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.fileUploadDialogTimeout":3000,"ie.forceCreateProcessApi":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"http://localhost:3840/","nativeEvents":true,"requireWindowFocus":false},"setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"webdriver.remote.sessionid":"770c15c3-c26f-42ee-8bf9-9d3305e09461"}}
```
Strange thing is that I am passing value= 'true' to these 3 capabilities: ignoreZoomSetting, ignoreProtectedModeSettings, 'ie.ensureCleanSession': true. But in the result of "se:ieOptions", all of them are set to false

**Comment by shs96c** [comment]
Those capabilities don't look like well-formed W3C dialect compatible capabilities. From memory, you may need something like:

```
"se:ieOptions": {
  "ie.ensureCleanSession": true
},
```

in your capabilities config.

**Comment by jimevans** [comment]
Yes, @shs96c is correct. You need to pass the IE-specific capabilities as part of an `se:ieOptions` property. The driver is spec-compliant, and expects capabilities to likewise be so. The `desiredCapabilities` property of the new session request will, at some point, be entirely ignored by the driver.

**Comment by pk-saxena** [comment]
@jimevans @shs96c 
Thank you guys. Really helpful. It is working now.
