### ISSUE TITLE
Run tests on BrowserStack with Selenium WebDriver NuGet Package Selenium 4.0.0-alpha 01 

### ISSUE THREAD

**Issue by abhi291096** [SeleniumHQ/selenium#7248]
## 💬 Questions and Help
1- I am executing tests with the latest NuGet Package: Selenium 4.0.0 alpha 01 on BrowserStack
2- Please refer the test script: https://gist.github.com/abhi291096/7606182b3edfd160b0aa2a28fc3567ae
3- I have printed the capabilities that are getting passed and getting the exception:

```
{
  "browserName": "chrome",
  "goog:chromeOptions": {
    "w3c": true,
    "bstack:options": {
      "osVersion": "11",
      "deviceName": "iPhone 8 Plus",
      "realMobile": "true",
      "buildName": "AM_CSharp",
      "local": "false"
    }
  }
}
{
  "browserName": "chrome",
  "goog:chromeOptions": {
    "w3c": true,
    "bstack:options": {
      "osVersion": "11",
      "deviceName": "iPhone 8 Plus",
      "realMobile": "true",
      "buildName": "AM_CSharp",
      "local": "false"
    }
  }
}
**System.Collections.Generic.Dictionary`2[System.String,System.Object]**
```

4- On executing the same test on BrowserStack with the Selenium Webdriver Version: 3.141.0
I am able to successfully able to execute the tests. 
5- Please refer the sample for 3.141.0: https://gist.github.com/abhi291096/f0a7ce62865a49074976a0721c8cb66a 
6- The difference between the tests is how the capabilities are getting passed:

With latest version - 4.0.0 alpha 1

 `options.AddAdditionalChromeOption("bstack:options", browserstackOptions);`

With version 3.141.0:

 `options.AddAdditionalCapability("bstack:options", browserstackOptions,true);
`
7- I have reviewed this link: https://github.com/SeleniumHQ/selenium/issues/6563 and see that the method AddAdditionalCapability() has been deprecated with Selenium 4.0.0 alpha 01 with Csharp

8- Can anyone please tell me why the session is not starting with Selenium 4.0.0 alpha 01 code 

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by jimevans** [comment]
Your BrowserStack options aren’t options that ChromeDriver would understand. Accordingly, `AddAdditionalChromeOption` is the wrong method for adding your BrowserStack options. Use `AddAdditionalOption` for your BrowserStack options.
