### ISSUE TITLE
Wait for element doesnot works on Safari Browser

### ISSUE THREAD

**Issue by musthafam** [SeleniumHQ/selenium#7254]
Latest Version Safari browser on Mac OS
Selenium version used: 3.4

Steps to Repro: 
Write script to click on element or Wait for element 

Expected Result : Script should click on element
Actual result : No such element exception occurs

Note; This is not specific to any website. I see this pattern on any website. But when i run the same script o Chrome or Firefox it is okay.
Also for now in our scirpts we are using thread.sleep to get rid of these failures

**Comment by cgoldberg** [comment]
please fill out all info on the template when filing an issue.
