### ISSUE TITLE
Selenium while dragAndDrop drag element to physical cursor

### ISSUE THREAD

**Issue by arturmkr** [SeleniumHQ/selenium#7261]
Selenium - 3.141.59<br>
Java

While execution of dragAndDrop method, source element is moving not to target element, but to physical cursor.

Tried following:

    public static void dragAndDrop(WebDriver driver, WebElement src, WebElement target) {
        Actions builder = new Actions(driver);
    
        builder.moveToElement(target).build().perform();
    
        Action dragAndDrop = builder.clickAndHold(src)
                .moveToElement(target)
                .release(target)
                .build();
        dragAndDrop.perform();
    }

And following:

    public static void dragAndDrop(WebDriver driver, WebElement src, WebElement target) {
        Actions builder = new Actions(driver);
        builder.dragAndDrop(src, target).build().perform();
    }

But these solutions don't work.
How to solve this issue?

**Comment by sachinboob** [comment]
Which browser are you using?
Also, is it possible to add the application URL that you are trying work with?
The second solution you tried should have worked fine.
Can you keep the mouse pointer away from the page and let me know if that works? I have observed for IE that the mouse pointer located within the page interferes with actions.

And, in your first solution, you do not need to use -> builder.moveToElement(target).build().perform();

Please try and confirm.

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.

**Comment by litinskii** [comment]
Have same issue (
