### ISSUE TITLE
not able to use Appium capability "allowTestPackages" 

### ISSUE THREAD

**Issue by budtmo** [SeleniumHQ/selenium#7262]
## 🐛 Bug Report

# Environment
Selenium Hub: 3.141.59
Appium Server: 1.13.0
OS: Ubuntu

# Situation
Connect Appium Server to Selenium Hub and run tests against Selenium Hub and set capability "allowTestPackages" to true.

# Current behaviour
If you unset capability "allowTestPackages", it works fine.
If you set capability "allowTestPackages" to true, it will fail and give this error message:
```
Caused by: java.lang.reflect.InvocationTargetException: null
10:58:03  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:58:03  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:58:03  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:58:03  	at java.lang.reflect.Method.invoke(Method.java:498)
10:58:03  	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:185)
10:58:03  	... 41 common frames omitted
10:58:03  Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html>
10:58:03  <head>
10:58:03  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
10:58:03  <title>Error 500 Server Error</title>
10:58:03  </head>
10:58:03  <body><h2>HTTP ERROR 500</h2>
```

# Expected behaviour
All capabilities that are defined in Appium should works through Selenium Hub. The list of Appium capabilities can be found [here](http://appium.io/docs/en/writing-running-appium/caps/)

**Comment by diemol** [comment]
@budtmo 
what happens if you use the Appium server directly, does it work?
Can you please provide the code used to build the capabilities? Which versions of Selenium and the language bindings are you using?

**Comment by budtmo** [comment]
Hi @diemol , 

yups, it worked fine with Appium last time I have checked.

I had some issues by using Appium through Selenium Hub and besides it is not stable for running a lot of parallel tests. Because of that reasons, I decided long time ago by not using Selenium Hub anymore, so I do not follow the issue. We can close the issue if you want.
