### ISSUE TITLE
Chrome custom profile - cannot propely logout

### ISSUE THREAD

**Issue by amarose** [SeleniumHQ/selenium#7269]
## 🐛 Bug Report
I'm using custom profile for Chrome in my tests, and in one test suite i have to logout from app, quit browser and then run following tests which starts with logging into app. When I log into app, i recieve a token (that gives me permission to access the app) which is stored in localStorage. After logout token is set to null.
The problem is - when i run following test that starts with opening the login site  (or just simply re-run the previous one, which also starts with logging in app), it turns out that... i am already logged in. What is more, the token i've mentioned at the beggining is set to value from previous session while it should be null after logout.

## To Reproduce

Detailed steps to reproduce the behavior:
1. Prepare script that loggs into app, does some stuff and logout.
2. Run the script for the first time
3. Check result - script should log in, test sth and logout without any issues
4. Re-run the same test
5. Bug appears - after driver.get('login_page_url'), im already logged in

## Expected behavior

After reruning the test that loggs out of app, I expect to be actually logged out when i start a new session.

## Test script or set of commands reproducing this issue

Simplified code script:
```driver = webdriver.Chrome()
driver.implicity_wait(10)
driver.maximize_window()
login_page_url = "https://app.pushpushgo.com/login"
driver.get(login_page_url)
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # This is where token is stored. It should return null now. 
lp = LoginPage(driver)  # page with locators and methods for login/logout
lp.login('email', 'password')  # use method
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token value should be set
# Skip tests, because its all about login/logout
lp.logout()
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token should be null again
```

Print outputs after first run:
1 print - token: null
2 print - token: "value for current session"
3 print - token: null

After second run:
1 print - token: "value from previous session"
Im already logged in, code fails

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 75.0.3770.80
Browser Driver version: ChromeDriver 75.0.3770.8
Language Bindings version: Python 3.7.1 
Selenium Grid version (if applicable): 3.141.0

**Comment by barancev** [comment]
I'm trying to reproduce the issue, here is a standalone script I use for this purpose:

```
from selenium import webdriver
from time import sleep

driver = webdriver.Chrome()

driver.implicitly_wait(10)
driver.maximize_window()
driver.get("https://app.pushpushgo.com/login")
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # This is where token is stored. It should return null now.
driver.find_element_by_id("login-field").send_keys("<my email>")
driver.find_element_by_id("password-field").send_keys("<my password>")
driver.find_element_by_css_selector("input.app-login-submit").click()
sleep(5)
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token value should be set
driver.find_element_by_css_selector("div.navigation-profile-trigger").click()
driver.find_element_by_css_selector("span.icon-logout-badge").click()
sleep(5)
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token should be null again
driver.quit()
```
The log from the first run:
```
{"canvasHeight":350}
{"canvasHeight":350,"token":"2c5065d6-5cbe-4552-a08a-fbc5b8ea7492","lang":"en","projectSelectorToggle":false,"currentProject":null}
{"canvasHeight":350,"token":null,"lang":"en","projectSelectorToggle":false,"currentProject":null}
```
The log from the second run:
```
{"canvasHeight":350}
{"canvasHeight":350,"token":"a8f7aa33-4564-45fb-9174-0e68cd68c48a","lang":"en","projectSelectorToggle":false,"currentProject":null}
{"canvasHeight":350,"token":null,"lang":"en","projectSelectorToggle":false,"currentProject":null}
```
That looks perfectly valid.

So please be more specific and provide a more detailed description on how to reproduce the issue.

**Comment by barancev** [comment]
Also, please use the latest Python binding version.

**Comment by amarose** [comment]
I am using Python 3.7.3 now

My apologises for not specifying custom profile in my code snippet.

Be sure You are using custom Chrome profile, while trying to reproduce bug, as it only occures under that condition.
Also try to run code three-four times in a row, because sometimes it won't happen after second try

```
options = webdriver.ChromeOptions()
options.add_argument("user-data-dir=C:\\Users\\<yourprofile>\\AppData\\Local\\Google\\Chrome\\selenium")  # example path
driver = webdriver.Chrome(options=options)
```

**Comment by diemol** [comment]
Is this still happening @amarose?
Can you please provide a way to reproduce the issue? Narrative descriptions are not enough.

**Comment by amarose** [comment]
@diemol 
I checked it and yes, it is still happening. To reproduce it u should run that code:

`from selenium import webdriver
from time import sleep

# This is crucial. You have to use custom profile
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("user-data-dir=base/tmp_data/chrome")  # Path to your Chrome Custom Profile
driver = webdriver.Chrome(options=chrome_options)

driver.implicitly_wait(10)
driver.maximize_window()
driver.get("https://app.stppg.co/login")
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # This is where token is stored. It should return null now.
driver.find_element_by_id("t-login-username").send_keys("logout@stppg.co")
driver.find_element_by_id("t-login-password").send_keys("logoutpwd")  # you can use that credentials as it is test account
driver.find_element_by_css_selector("input.app-login-submit").click()
sleep(5)
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token value should be set
driver.find_element_by_css_selector("div.navigation-profile-trigger").click()
driver.find_element_by_css_selector("span.icon-logout-badge").click()
sleep(5)
print(driver.execute_script("return window.localStorage.getItem('__pushpushgo')"))  # Token should be null again
driver.quit()`

You can use credentials provided inside code.
To catch bug you should run that code twice. First run - code will open login site, log into app and then log out. At second run, code will fail because you will be already logged into app (while u shouldn't be, because you have been logged out at previous run)
This only happens when i am using chrome custom profile as driver instance.
Everything works fine if i use default chrome profile (driver = webdriver.Chrome())
Code also prints the token that user receives after logging in. After log out token is set to null.

Output after first run:
 {"canvasHeight":350,"token":null,"lang":"en","projectSelectorToggle":false,"currentProject":null}
{"canvasHeight":350,"token":"0f853325-c095-4f68-a7e6-ddf49841ae32","lang":"en","projectSelectorToggle":false,"currentProject":null}
{"canvasHeight":350,"token":null,"lang":"en","projectSelectorToggle":false,"currentProject":null}

After second run:
{"canvasHeight":350,"token":"0f853325-c095-4f68-a7e6-ddf49841ae32","lang":"en","projectSelectorToggle":false,"currentProject":null}

And error message as it cannot locate login email input (because im already logged in)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="t-login-username"]"}
  (Session info: chrome=80.0.3987.163)

Chrome 80
Windows 10
Python 3.8.2
Selenium 3.141.59

**Comment by diemol** [comment]
I just wrote the test in Java and I cannot reproduce the issue:

```
    @Test
    public void issue7269() throws InterruptedException {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("user-data-dir=base/tmp_data/chrome");
        WebDriver webDriver = new ChromeDriver(chromeOptions);
        webDriver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        webDriver.manage().window().maximize();

        webDriver.get("https://app.stppg.co/login");
        JavascriptExecutor jsExecutor = (JavascriptExecutor) webDriver;
        System.out.println(jsExecutor.executeScript("return window.localStorage.getItem('__pushpushgo')"));
        webDriver.findElement(By.id("t-login-username")).sendKeys("logout@stppg.co");
        webDriver.findElement(By.id("t-login-password")).sendKeys("logoutpwd");
        webDriver.findElement(By.cssSelector("input.app-login-submit")).click();
        Thread.sleep(5000);
        System.out.println(jsExecutor.executeScript("return window.localStorage.getItem('__pushpushgo')"));
        webDriver.findElement(By.cssSelector("div.navigation-profile-trigger")).click();
        webDriver.findElement(By.cssSelector("span.icon-logout-badge")).click();
        Thread.sleep(5000);
        System.out.println(jsExecutor.executeScript("return window.localStorage.getItem('__pushpushgo')"));

        webDriver.quit();
    }
```

What am I missing?

**Comment by amarose** [comment]
Your code looks perfectly fine so i assume problem is here
```
 chromeOptions.addArguments("user-data-dir=base/tmp_data/chrome");
```

Firstly you should create a chrome custom profile in chrome browser
https://www.chromium.org/developers/creating-and-using-profiles

 "base/tmp_data/chrome" is path to mine chrome custom profile files. Instead of that path, provide path to your custom profile after you will create it

**Comment by diemol** [comment]
When you set a path like that the profile is created automatically.
Nevertheless, I have little time to create a profile and figure it out on my own, that's why we ask for your help by providing a complete self container test case that we can use to reproduce the issue. 
Aside from that, I highly doubt it is a Selenium issue, if there is a problem, it seems it is between Chrome and the profile creation, don't you think?
If so, I'd recommend to create an issue at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
