### ISSUE TITLE
Chrome 74 hangs when passing Chrome Extension

### ISSUE THREAD

**Issue by ckzgraphics** [SeleniumHQ/selenium#7271]
## 🐛 Bug Report

While executing the test on Chrome 74 the following exception is thrown- 
`timeout (Session info: chrome=74.0.3729.131) (Driver info: chromedriver=74.0.3729.6`

The same test works on Chrome 73 and lower browsers as expected.

## To Reproduce :recycle:

1. Start the Selenium JAR in Standalone mode
2. Provide Chrome Extension in the ChromeOptions
3. Run the test on Chrome 74

## Expected behavior :eight_spoked_asterisk:

The Chrome browser should open the URL and should NOT throw the timeout exception.

## Test script or set of commands reproducing this issue :cd:

**GIST to replicate the issue-** https://gist.github.com/ckzgraphics/660fbc0b086b504fd2ba3a7059f84f8a

## Environment

**OS-** Windows 10
**Browser-** Chrome
**Browser version-** 74
**Browser Driver version-** 74.0.3729.108
**Language Bindings version-** Java 3.14.0
**Selenium Grid version-** 3.14.0

## Failed Session | Chrome 74 | :sos:

**Session ID-** https://automate.browserstack.com/builds/dc03f2ef4188580b1aecf0ae6ec06dbded367de4/sessions/1d7fdd92f1e81e2f8b9e6bfa4f020cb8ee4f866b?auth_token=b252c140d27b977073a127fe950dc51cd0796aeaa1680d601ae6b75e340795ee
**Selenium Logs-** https://gist.github.com/ckzgraphics/953d8cfea127c8520d9479b9490873f9
**Video Logs-** https://drive.google.com/file/d/1vAfwYELfzwWRCkYOmsGeKxn514DpEwH9/view?usp=sharing 
:movie_camera:

## Passed Session | Chrome 73 | :white_check_mark:

**Session ID-** https://automate.browserstack.com/builds/dc03f2ef4188580b1aecf0ae6ec06dbded367de4/sessions/6f25762dfe045cd3b83fc9f8124aa37a98897021?auth_token=7de9c50464f82d89d359635fae3a9befc71950d3692e7460b9eb084e97406bdb
**Selenium Logs-** https://gist.github.com/ckzgraphics/790dec479e3dbd6d0ac39d9a8070b938
**Video Logs-** https://drive.google.com/file/d/1GnLiZXr-cBBmKr2k2msd4V0fwoOaq2Lz/view?usp=sharing  :movie_camera:

**Comment by Namrata-m13** [comment]
This has been raised on Chromium as well- [2942](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2942)

**Comment by cgoldberg** [comment]
closing since this is a chromedriver issue - https://bugs.chromium.org/p/chromedriver/issues/detail?id=2942
