### ISSUE TITLE
ie.enableFullPageScreenshot not set by default on version 3.14

### ISSUE THREAD

**Issue by prateeksarda** [SeleniumHQ/selenium#7272]
As per IE driver [CHANGELOG](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/cpp/iedriverserver/CHANGELOG)
version 2.52 has added the flag ie.enableFullPageScreenshot which is by default as true to take full page screenshot.
I am using IE driver version 3.14 and this behaviour is no longer working.
`
from selenium.webdriver import Remote
from selenium.webdriver.ie.options import Options as IEOptions
options = IEOptions()
options.full_page_screenshot = True // explicitly setting it even though assuming its set by default
webdriver = Remote(desired_capabilities=options.to_capabilities())
print(json.dumps(webdriver.desired_capabilities, indent=4, sort_keys=True))
webdriver.get(""https://www.google.co.uk/")
query = webdriver.find_element_by_name('q')
query.send_keys("Selenium")
query.send_keys(webdriver.common.keys.Keys.ENTER)
webdriver.save_screenshot("full_page_screenshot.png") // only gives screenshot of the viewport and not full page`

**Comment by jimevans** [comment]
As of version 3.5 of the IE driver, the driver implements the [W3C WebDriver Specification](https://w3c.github.io/webdriver/). The spec dictates that only the current view port is used in screenshots, so so-called “full page screenshots” are no longer supported in the IE driver. This aligns with all other spec-compliant implementations (chromedriver.exe, geckodriver.exe, etc.).

**Comment by prateeksarda** [comment]
@jimevans as you said the changes are post 3.5 I am still using older version 3.14 so it removed from that too?
And can you have this documented if not already helps to know what been updated.

**Comment by jimevans** [comment]
The [IE driver CHANGELOG](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG) pretty clearly spells out the changes for each version of the driver. For version 3.4.0.1, [the log](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG#L1097) states that the driver implement the standard. Although you’re correct, it doesn’t call out screenshots directly, that would be an implies change as part of the implementation of spec compliance. As noted at the top of the CHANGELOG, the version scheme means that the next public version after that would be 3.5. Please note that 3.14 is long after 3.5 (14 > 5), so I’m not sure how 3.14 is the “older version.”

**Comment by prateeksarda** [comment]
Thanks @jimevans for the details.
If the new specification states that full screenshot cannot be taken then I urge the maintainers of selenium python module to fix their module which still allows to set full_page_screenshot capability.
