### ISSUE TITLE
Test run on remote IE node connected to grid is failing with "No active session with ID"

### ISSUE THREAD

**Issue by mgrozdeva** [SeleniumHQ/selenium#7275]
## 🐛 Bug Report
Test run against IE node, connected to Grid fails **randomly** with Session terminated due to BROWSER_TIMEOUT or SO_TIMEOUT

Sometimes it fails on first test, sometimes it fails after several tests.

**Following error is observed in selenium log:**
`org.openqa.selenium.NoSuchSessionException: No active session with ID 063e8685-acce-4d00-bf17-8eb707f038cd
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'UKC9VM0005574', ip: '10.185.139.53', os.name: 'Windows Server 2016', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: true, ignoreZoomSetting: true, initialBrowserUrl: http://localhost:1033/, nativeEvents: true, requireWindowFocus: true}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 063e8685-acce-4d00-bf17-8eb...}
Session ID: 063e8685-acce-4d00-bf17-8eb707f038cd
*** Element info: {Using=id, value=username}`

`org.openqa.selenium.WebDriverException: Session [063e8685-acce-4d00-bf17-8eb707f038cd] was terminated due to BROWSER_TIMEOUT`

`org.openqa.selenium.WebDriverException: Session [aef91cca-3458-481f-b874-7af1d479f6c3] was terminated due to SO_TIMEOUT`

## Configuration
**I use following command to start selenium-server-standalone:**
`"C:\Program Files (x86)\Java\jdk1.8.0_211\bin\java.exe" -jar "C:\Program Files (x86)\Selenium\grid\selenium-server-standalone.jar" -role node -hub http://localhost:4444/grid/register/ -port 51622 -browserTimeout 300 -timeout 240 -debug -browser browserName="internet explorer",version=11.2906,platform=windows,maxInstances=5,maxSession=5`

**Remote driver capabilities**
```
BrowserType.IE:
	capability = new InternetExplorerOptions();
	capability.setCapability("requireWindowFocus", true);
	capability.setCapability("ignoreZoomSetting", true);
	capability.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
	capability.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
	capability.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
	break;
```

## Environment

OS - node: Windows 10, Windows Server 2016
OS - grid: Windows Server 2016, Cent OS 7
Browser: IE 11
Browser version: IE 11 (32 and 64 bit)
Browser Driver version: IEDriver 3.141.59 (32 and 64 bit)
Java: 1.8.0_211 (32 and 64 bit)
Selenium Grid version (if applicable): 3.141.59

## NOTE

- NOT reproducible with Chrome-driver
- NOT reproducible with local IE-driver
- Reproduced even when IE-node and Hub are running on same Windows Server 2016

**Comment by mgrozdeva** [comment]
I am still investigating failure cause and I have doubts that could be related to:

- test are executing javascripts
- Tests are running with  Cucumber and make browser.quit() after each feature end, not on test end

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we didn't get any information to reproduce the issue.
