### ISSUE TITLE
Javadoc for TakesScreenshot#getScreenshotAs() differ from w3c spec

### ISSUE THREAD

**Issue by takeya0x86** [SeleniumHQ/selenium#7277]
## 🐛 Bug Report

Javadoc for `TakesScreenshot#getScreenshotAs()` :

> For WebDriver extending TakesScreenshot, this makes a best effort
>  depending on the browser to return the following in order of preference:
>   <ul>
>     <li>Entire page</li>
>      <li>Current window</li>
>      <li>Visible portion of the current frame</li>
>      <li>The screenshot of the entire display containing the browser</li>
>    </ul>

but [w3c spec](https://www.w3.org/TR/webdriver/#screen-capture) :

>  Take Screenshot command to capture the top-level browsing context’s initial viewport,

If `getScreenshotAs` method always return current viewport instead of entire page,  javadoc should fit this behavior. 

## To Reproduce

Detailed steps to reproduce the behavior:

## Expected behavior

Javadoc and specs are match.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
Fixed by commit e055afda143807049eee5fc4037452e872f07c76
