### ISSUE TITLE
Unable to Select (Materialize Drop down) using Selenium Web Driver in Python  

### ISSUE THREAD

**Issue by MujtabaBinKhalid** [SeleniumHQ/selenium#7280]
I have tried different methods to select the materialize dropdown but none of them is working .

1 . select by Visible Text.

select_company = Select(driver.find_element_by_name("companies"))
select_company.selectByVisibleText("XYZ")
2 . select by Index

Select(driver.find_element_by_tag_name("select")).select_by_index(2)
3. select by Value.

select_company = Select(driver.find_element_by_name("companies"))
select_company.select_by_value("XYZ")

**Comment by lmtierney** [comment]
The `Select` class only works for `<select>` elements. You need to figure out your own way to deal with drop-downs that are made with other elements
