### ISSUE TITLE
Performance regression for mouse movements when w3c compliance is active

### ISSUE THREAD

**Issue by emily-d** [SeleniumHQ/selenium#7281]
## 💥 Regression Report

 In w3c mode, pointer actions incur a 250 ms overhead. Mouse movement is then extremely slow.

Setting  [DEFAULT_MOVE_DURATION ](https://github.com/SeleniumHQ/selenium/blob/selenium-3.14.0/py/selenium/webdriver/common/actions/pointer_input.py#L26) from 250 to 0 in the PointerInput class fixes the problem.

For the ruby bindings, the possibility to change the duration was [added](https://github.com/SeleniumHQ/selenium/blob/65804eae63a2f54d8d30bf1c8a66dd1a2b4b2280/rb/CHANGES#L215).  

See also https://bugs.chromium.org/p/chromedriver/issues/detail?id=2948#c4

## Last working Selenium version

Stopped working in version: Selenium 3.3.0

Regression introduced in this commit: https://github.com/SeleniumHQ/selenium/commit/b33a3c9f330bafec15b06b325b4120b2140acf88#diff-52a5fc90be38d4c3455748e21d70b1d4

## To Reproduce

Use the latest chrome/chromedriver >= 75, w3c is now the default mode.

```python
from selenium.webdriver.common.action_chains import ActionChains
from selenium import webdriver

 # chrome_options = webdriver.ChromeOptions()
# chrome_options.add_experimental_option('w3c', True)
# driver =  webdriver.Chrome(options=chrome_options)

driver =  webdriver.Chrome()
driver.get('https://www.google.com/')
action = ActionChains(driver)
for i in range(0, 50):
    action.move_by_offset(i, i)
action.perform()
```

## Expected behavior

This should be fast. But takes a lot of time.

## Environment

OS: Windows 10, x64
Browser: Chrome
Browser version: Version 75.0.3770.80 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40})
Language Bindings version: Python 3.141.0

**Comment by space88man** [comment]
No consumer of `PointerInput.create_pointer_move`, all the way up to `ActionChains` sets the duration kwarg, resulting in the 250 msec penalty. It would need something like:
```
ActionsChains( ..., duration=250) # add a duration kwarg
    self.duration = duration

ActionBuilder( ...,  duration=250) # add a duration kwarg
     self.duration = duration

PointerActions(..., duration=250) # add a duration kwarg
# then in all the PointerActions methods that use create_pointer_move
.... self.source.create_pointer_move(origin=????, duration=self.duration, x=????, y=????) 
```

...but this looks kinda yucky.
