### ISSUE TITLE
Element.Displayed return "the path is not of a legal form"

### ISSUE THREAD

**Issue by kbourro** [SeleniumHQ/selenium#7291]
Selecting an element with xpath returns an IWebElement then element.Displayed returns an error "the path is not of a legal form". Exist and Enabled works correctly.

**Comment by jimevans** [comment]
This is not globally broken for all users and all sites for all XPath values. You'll need to provide more information to have a chance of tracking down what the issue is. Please provide a full example, complete with an HTML page (or URL to a public site) that can reproduce the issue.

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
