### ISSUE TITLE
The script EXPORT in selenium ide is broken!!

### ISSUE THREAD

**Issue by Vmudugonda** [SeleniumHQ/selenium#7299]
## 💥 Regression Report

A clear and concise description of what the regression is.

## Last working Selenium version

Worked up to version:

Stopped working in version:

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by diemol** [comment]
Hi @Vmudugonda,

Please report this issue to https://github.com/SeleniumHQ/selenium-ide, don't forget to fill out the complete template.
