### ISSUE TITLE
element.click() doesn't work on chrome using webdriver 2.45

### ISSUE THREAD

**Issue by zhuxysun** [SeleniumHQ/selenium#730]
I'm using webdriver 2.45 to run the auto test scripts on chrome, but sometimes clicking an element of tag "a" on a pop  window doesn't work without any exception.

the html is 
<div class="popwinBtnCon popwinCloseBtn mt30">
    <a id="submitBtn" class="btnBlue" href="javascript:void(0);" onclick="uxe.app.triggerDomEvent('app332',this,'sendMms')"><span class="right"><span class="center">Yes, send it.</span></span></a>
</div>

i've tried focus the element before clicking, but that seems no effective
the java code is 
WebElement webElement = driver.findElement(By.id("submitBtn"));
((JavascriptExecutor) driver).executeScript("arguments[0].focus()", args);
webElement.click();

**Comment by p0deje** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by kasthurk** [comment]
Even I faced the same issue. It's chrome browser issue.  Add wait for element click
