### ISSUE TITLE
Does not open the localhost link in latest Firefox

### ISSUE THREAD

**Issue by ganesanviji** [SeleniumHQ/selenium#7309]
Hi,

I am using nunit console for test my ASP.NET Core web blazor application. But when run the local host of my application by using nunit I have faced the below issue like the localhost url is not open in latest firefox. Could you please update the details why Nunit does not support the latest version and work around for this issue. 

![image](https://user-images.githubusercontent.com/8706341/59263335-789ed380-8c5e-11e9-9eb4-10c9776ce899.png)

Note: Nunit is working in 43 version firefox. But blazor application is only running in latest version of firefox. So, could you please suggest me how can I run the nunit in latest firefox.

I am using the selenium for launch the localhost URL and I have given the testing assembly which is compiling by the below mentioned code as a parameter for the Nunit console exe. In below code I am using the Firebox browser which is supported only in 43 version. I have tried Chrome browser but localhost link is not open in that browser.

[TestFixture("Firefox")]
[ImageComparison(true)]
public class Test : NUnitUtil
{
private string activeBrowser;
private string SampleURL = "http://localhost:5000";

    public Test(string browser)
    {
        driver = GetWebDriverForBrowser(browser);
        activeBrowser = browser;
    }

    [TestFixtureTearDown]
    public void quitDriver()
    {
        driver.Quit();
    }

    [Test, Description("Control rendering")]
    [Category("Basic")]
    public void AngularCDNmaterial30()
    {
        
        driver.Navigate().GoToUrl(SampleURL);
        IWebElement element = driver.FindElement(By.TagName("body"));
        Thread.Sleep(15000);
        TakeAndCompareScreenshot(element);
    }
}

Please suggest the solution for this

Thanks.
Ganesan R.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
