### ISSUE TITLE
In version 2.46.0, DriverService triggers the @afterMethod

### ISSUE THREAD

**Issue by kolumbien** [SeleniumHQ/selenium#731]
I have moved to:
   <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>2.46.0</version>
        </dependency>

In  @BeforeMethod(alwaysRun = true) method, I call:

DriverService service = new ChromeDriverService.Builder().usingDriverExecutable(new File(browserPath)).usingAnyFreePort().build();
**Where browserPath=chromedriver.exe (last version 2.16.0)

When that line is called, the @AfterMethod(alwaysRun = true) is triggered.

But using my previous version, everything works fine:
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-server</artifactId>
            <version>2.40.0</version>
        </dependency>

**Comment by barancev** [comment]
Please provide a complete file or a project to reproduce the issue.

**Comment by ddavison** [comment]
no answer for over a month.  closing.
