### ISSUE TITLE
HTML5 Drag and Drop issue with IE11.

### ISSUE THREAD

**Issue by cnparmar** [SeleniumHQ/selenium#7311]
I want to drag and drop and element and I have written below code. It is working for all the other browsers except IE11.

Here are the 2 methods are tried and none of them are working.

Action Class
```
Actions act = new Actions(driver); 
act.dragAndDrop(sourceElement,targetElement).build().perform();
```
Robot Class
```
Robot robot = new Robot();		  
robot.mouseMove(sourceElement.getRect().getX(), sourceElement.getRect().getY());
robot.mousePress(InputEvent.BUTTON1_DOWN_MASK); 
Thread.sleep(4000);
robot.mouseMove(targetElement.getRect().getX(), targetElement.getRect().getY());
robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
```

Is there any other way I can simulate drag and drop in IE11?

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by cnparmar** [comment]
Hi Alexei, 

Here is the source and Target Element's DOM Structure.

Source Control HTML
```
<div id="div0_384" style="white-space: nowrap;overflow:hidden;width:179px;height:20px;" title="Customer Item">
	<input type="checkbox" name="0_384" onclick="Handler.onClickCtrl(this,true,'')" onfocus="Handler.onFocusCheckboxRadio(this,'')" onblur="Handler.onExitCheckboxRadio(this,'')" tabindex="11" onmouseover="updateHelpCursor('',this)" onhelp="hp('0_384')" id="C0_384" title="Customer Item" readonly="readonly" disable="true" disabled="" style="pointer-events: none;">
	<span class="checkboxText">
		<nobr>
			<label >Customer Item</label>
		</nobr>
	</span>
</div>
```

Target Control HTML
```
<div id="div0_413" style="white-space: nowrap;overflow:hidden;width:180px;height:22px;" title="Customer Name">
	<input type="checkbox" name="0_413" onclick="Handler.onClickCtrl(this,true,'')" onfocus="Handler.onFocusCheckboxRadio(this,'')" onblur="Handler.onExitCheckboxRadio(this,'')" tabindex="10" onmouseover="updateHelpCursor('',this)" onhelp="hp('0_413')" id="C0_413" title="Customer Name" readonly="readonly" disable="true" disabled="" style="pointer-events: none;">
	<span class="checkboxText">
		<nobr>
			<label >Customer Name</label>
		</nobr>
	</span>
</div>
```

When I am executing any of the below code using TestNG.xml in IE11 on Windows 10 machine, the test passes successfully without any error. However; the control is not dragged and dropped to target element. Nothing happens on screen while the test is being executed.

1. Action Class (This works in Chrome, Firefox and Edge.)
```
Actions act = new Actions(driver); 
act.dragAndDrop(sourceElement,targetElement).build().perform();
```

2. Robot Class
```
Robot robot = new Robot();		  
robot.mouseMove(sourceElement.getRect().getX(), sourceElement.getRect().getY());
robot.mousePress(InputEvent.BUTTON1_DOWN_MASK); 
Thread.sleep(4000);
robot.mouseMove(targetElement.getRect().getX(), targetElement.getRect().getY());
robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
```

Any idea what is going on or is there anything I am missing specific for IE?

Let me know if more information is required.

Thanks,
Chandresh Parmar

**Comment by barancev** [comment]
I'm asking again please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

**Comment by cnparmar** [comment]
Hi Alexei,

Here is the detailed code I have in my test. For security reasons I cannot attach the DOM of the page here. Can you please let me know what else is required.

```
System.setProperty("webdriver.chrome.driver",System.getProperty("user.dir") + "/Drivers/chromedriver.exe");
WebDriver driver = new ChromeDriver();
driver.get(URL);
driver.manage().window().maximize();
driver.findElement("//input[@id='username']").sendKeys(username);
driver.findElement("//input[@id='password']").sendKeys(password);
driver.findElement("//input[@id='password']").sendKeys(Keys.ENTER);
Thread.sleep(3000);
WebElement targetElement = driver.findElement(By.xpath("//div[@title='Customer Item']"));
WebElement sourceElement = driver.findElement(By.xpath("//div[@title='Customer Name']"));

Actions act = new Actions(driver);
act.dragAndDrop(sourceElement, targetElement).build().perform();
```

When I run this code in other browser it is working fine. But when I run it in IE11, test passes but the element is not dragged and dropped.

Thanks,
Chandresh Parmar

**Comment by barancev** [comment]
We also need an HTML page to run this code against.

**Comment by jimevans** [comment]
@cnparmar There are no less than three different ways in the IE driver to simulate mouse movement. If you use the `requireWindowFocus` capability when you launch your IE session, does it work?

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
