### ISSUE TITLE
Deprecation warning on `driver.switch_to.alert.text` call

### ISSUE THREAD

**Issue by ShockwaveNN** [SeleniumHQ/selenium#7314]
## 🐛 Bug Report

While calling `driver.switch_to.alert.text` on page without alert - there will be deprecation warning about `Selenium::WebDriver::Error::NoAlertPresentError`

## To Reproduce
1. Create test.rb
```
require 'selenium-webdriver'
driver = Selenium::WebDriver.for :chrome
driver.navigate.to('https://google.com')
driver.switch_to.alert.text
```

2. Run `ruby test.rb`

Outputs 
```
2019-06-21 15:16:49 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::NoAlertPresentError is deprecated. Use Selenium::WebDriver::Error::NoSuchAlertError (ensure the driver supports W3C WebDriver specification) instead.
```
But `NoAlertPresentError` was never used in my code, so I don't think deprecation warning should be shown

## Environment

OS: Ubuntu 18.04
Browser: Chrome
Browser version: 75.0.3770.100
Browser Driver version: chromedriver 75.0.3770.8
Language Bindings version: Ruby 'selenium-webdriver', '3.142.3'

**Comment by twalpole** [comment]
Have you disabled w3c by any chance?  The issue is that chromedriver is responding with an error message that isn't compliant with the WebDriver spec.  If you reenable w3c mode you shouldn't see the deprecation warning.

**Comment by twalpole** [comment]
The issue here is chromedriver is returning an error that isn't W3C WebDriver spec compliant.  Are you sure the code you show produces this? If you had disabled w3c mode when creating the driver I would expect the error message, but not if you left it in w3c mode

**Comment by ShockwaveNN** [comment]
@twalpole Yep, my bad, by default I used chromedriver 2.32
Update to `chromedriver 75.0.3770.8` and warning is gone, sorry
