### ISSUE TITLE
org.openqa.selenium.interactions.MoveTargetOutOfBoundsException after upgrading to 3.14.0 from 3.8.1

### ISSUE THREAD

**Issue by LubomirKovalcik** [SeleniumHQ/selenium#7315]
` new Actions(data).moveToElement(element,x,y).perform();`

This code worked find with: 
Selenium 3.8.1, Chrome 63, chromedriver 2.3.8

After finally upgrading to:
Selenium 3.14 , Chrome 75,  chromedriver 75.0.3770.9

I am getting error:

`org.openqa.selenium.interactions.MoveTargetOutOfBoundsException `

The page did not change at all, it still same page, but now I am getting error which I was not before and tests were working good back then...

What is cause of that?

**Comment by lmtierney** [comment]
With Chromedriver's switch to w3c compliance in version 75, you now have to scroll any elements into view before using actions on them. https://www.w3.org/TR/webdriver1/#pointer-actions

In the future, please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
