### ISSUE TITLE
Failed to import atoms module ./atoms/get-attribute.js.

### ISSUE THREAD

**Issue by Karangoyal25892** [SeleniumHQ/selenium#7321]
I am using selenium-webdriver in my testcases. They were executing fine until a new update (4.0.0-alpha.3) was rolled out for selenium-webdriver.
I even tested the same on (4.0.0-alpha.4), however, the issue is still the same.

Please help me if possible
![Screenshot_2](https://user-images.githubusercontent.com/34648979/60017257-f541a100-96a5-11e9-90cc-dceb67c02303.png)

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided.
