### ISSUE TITLE
Issue with element locators in IE

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7322]
**Environment:**
WebdriverIO version: 4.14.2
Mode: WDIO Testrunner (sync)
Browser name and version: IE 11
selenium standalone: selenium-server-standalone-3.141.59.jar
IE driver: 32 bit 3.14.0

**Config of WebdriverIO:**
specs: [${pathToTests}*.js],
deprecationWarnings: false,
maxInstances: 1,
capabilities: [
    {
      browserName: 'internet explorer',
      platform: 'WINDOWS',
      platformName: 'windows',
      logLevel: 'trace',
      'se:ieOptions': {
        'ie.ensureCleanSession': true,
        ignoreZoomSetting: true,
        ignoreProtectedModeSettings: true
      }
    }
  ],
sync: true,

**Issue Description:**
 I have following line of code that works perfectly fine in chrome browser but fails when running on IE:
`
        browser.waitForVisible('tbody tr #recruiter_application_status')
`
Getting error:
Error: Promise was rejected with the following reason: result.value.map is not a function
    at elementIdDisplayed

Did anyone face similar issue?

**Comment by diemol** [comment]
Hi @pk-saxena,
Please report the issue to https://github.com/webdriverio/webdriverio
