### ISSUE TITLE
Chromeprofiling works only in the second instance

### ISSUE THREAD

**Issue by xlco1** [SeleniumHQ/selenium#7325]
I use the following code to load my chrome with default extensions. 

            System.setProperty("webdriver.chrome.driver", projectPath +"/driver/chromedriver.exe");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("user-data-dir=C:\\Users\\ssreenivasan\\AppData\\Local\\Google\\Chrome\\User Data");
			options.addArguments("--start-maximized");
			options.addArguments("disable-infobars");
			DesiredCapabilities capabilities = DesiredCapabilities.chrome();
			capabilities.setCapability(ChromeOptions.CAPABILITY, options);
			 driver=new ChromeDriver(capabilities);
		}

My first instance loads with extensions, but the website doesn't open. Keeping the first instance open, when I run the code second time, everything works perfectly(load chrome with extensions and code works). how to resolve that?

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
