### ISSUE TITLE
Selenium 2.46 is working much slower than 2.44 with Firefox 33.1.1

### ISSUE THREAD

**Issue by lorenzofidalgo** [SeleniumHQ/selenium#733]
Hi all,
I have been working for a while with selenium 2.44 and firefox 33.1.1. Recently I upgraded to selenium 2.46, but I have seen that selenium 2.46 performance is worst than 2.44 performance.
I have done lots of tests and I have confirmed that the only change of my selenium version downgrades a lot my tests' performance.

I work with linux 14.04 and firefox 33.1.1.
With selenium 2.44, the bunch of tests takes 1h 35min to be executed.
With selenium 2.46, the bunch of tests takes 2h to be executed.

Could you tellme how to avoid this bug or if this is a known issue?
Thank you so much.

**Comment by lukeis** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

Firefox 33 is not apart of the common test suite for the latest release. 38, 37 and 31 are. We have not noticed such drastic performance issues as you are describing. You'll need to provide much more detailed reproduction steps or you can try asking for help on the [selenium users mailing list](https://groups.google.com/forum/#!forum/selenium-users)
