### ISSUE TITLE
Several Java typing tests incompatible with W3C spec

### ISSUE THREAD

**Issue by JohnChen0** [SeleniumHQ/selenium#7330]
## 🐛 Bug Report

Several Java client test cases in TypingTest class rely on the prior selection range and/or text insertion caret position before calling sendKeys() method. This is incompatible with the current definition of Element Send Keys in W3C WebDriver spec. For a normal text input, the spec requires the following two steps as part of Element Send keys implementation:

1. Let current text length be the JavaScript string’s length of element’s API value.
2. Set the text insertion caret using set selection range using current text length for both the start and end parameters.

After executing these two steps, and prior selection range is gone, and the insertion caret would be placed at the end of existing text. This causes failures in the following five tests:

* TypingTest.testChordControlHomeShiftEndDelete
* TypingTest.testChordReveseShiftHomeSelectionDeletes
* TypingTest.testChordControlCutAndPaste
* TypingTest.testDeleteAndBackspaceKeys
* TypingTest.testShiftSelectionDeletes

The failures were observed with the latest builds of ChromeDriver, after it is updated to carry out the above two steps from the spec.

**Comment by mtrea** [comment]
Related to this issue is the fact that IE Driver Server does not abide by the spec in this regard. Using version 3.141.59, with the given source: https://jsfiddle.net/w97qve2j/

`    WebElement element = driver.findElement(By.tagName("input"));
    element.sendKeys(Keys.LEFT, Keys.LEFT, Keys.LEFT);
    element.sendKeys("abc");
    assertThat(element.getAttribute("value")).isEqualTo("barabc");`

This test passes on Firefox 63+ and Chrome 77+ but not on IE11 or Edge Windows 44 because the cursor is still at the left side of the box, resulting in the text "abcbar".

**Comment by shs96c** [comment]
How did we miss this when writing the spec? The behaviour of Selenium is actually the better user experience. *sigh* I wonder whether the right thing to do is to change the spec?

**Comment by twalpole** [comment]
Just to point out - geckodrivers current behavior here is to not reset the selection if the field is already focused with a selection.  This is actually much preferred from a usability perspective than what the spec actually says to do.

**Comment by AutomatedTester** [comment]
Spec was updated today to match Selenium and Geckodriver. Further issues should be raised against the spec
