### ISSUE TITLE
Issue with generating logfile

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7334]
**Environment:**
WebdriverIO version: 4.14.2
Mode: WDIO Testrunner (sync)
Browser name and version: IE 11
selenium standalone: selenium-server-standalone-3.141.59.jar
IE driver: 32 bit 3.14.0

**Config of WebdriverIO:**
specs: [${pathToTests}*.js],
deprecationWarnings: false,
maxInstances: 1,
capabilities: [
{
browserName: 'internet explorer',
platform: 'WINDOWS',
platformName: 'windows',
logLevel: 'trace',
logFile: 'C:\\Users\\Administrator\\Downloads\\ielog.txt'
'se:ieOptions': {
'ie.ensureCleanSession': true,
ignoreZoomSetting: true,
ignoreProtectedModeSettings: true
}
}
],
sync: true,

**Issue Description:**
I want to generate logFile as specified in capabilities object. But it is not being generated. Any idea on what I am missing here?

**Comment by barancev** [comment]
Please ask this question in wd.io community.
