### ISSUE TITLE
Safari 13.0 is not compatible for mac-OS High Sierra  10.13.6

### ISSUE THREAD

**Issue by SundaresanUBP** [SeleniumHQ/selenium#7336]
Hi,

     I am using mac-OS High Sierra 10.13.6 and safari browser recently got upgraded to Safari 13.0,After that selenium scripts are not working properly,many of the objects using xpath locators like (text,contains text,using attribute values,placeholder etc ) are not identifying properly but mac OS chrome browser working fine.
    Please support me, how to overcome this issue.

**Comment by twalpole** [comment]
Safari 13 is in beta release and has a number of issues with its WebDriver support, there's not much Selenium can do to fix that - Apple has to fix their WebDriver support.
