### ISSUE TITLE
Error in class invisibility_of_element

### ISSUE THREAD

**Issue by mazl** [SeleniumHQ/selenium#7337]
![image](https://user-images.githubusercontent.com/3139609/60330807-d6a11a00-99c5-11e9-80a9-c875878204c2.png)
this __init function should be  `__init__()`?

**Comment by luckydonald** [comment]
I'm pretty sure @mazl means `__init__(...)` instead of `__init(...)`.  
Might be interested in reading [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by AutomatedTester** [comment]
@mazl so it is... guessing no one uses that API. Do you want to do PR for
this and I will get it merged.

**Comment by mazl** [comment]
@AutomatedTester  I already PR this,please check it

**Comment by GQAssurance** [comment]
> @mazl so it is... guessing no one uses that API. Do you want to do PR for this and I will get it merged.

I think we noticed it was broken a long time ago and quietly switched to `!visibility_of_element`, I imagine most people did the same.

@mazl nice catch!
