### ISSUE TITLE
Allow adding listeners for Chrome DevTools Protocol Events

### ISSUE THREAD

**Issue by JonWallsten** [SeleniumHQ/selenium#7339]
## 🚀 Feature Proposal

Expose a way to add listeners for Chrome DevTools Protocol Events. It's already possible to send commands with _browser.driver.sendDevToolsCommand_.

## Motivation

I'm allowed to start/stop a Screencast, but there is no way of adding a listener to get the actual images produced.

## Example

```
// I'm using Selenium through Protractor so I'm accessing the driver from the browser object.
browser.driver.addDevToolsEventListener('Page.screencastFrame', (frame) => {
    browser.driver.sendDevToolsCommand('Page.screencastFrameAck', { sessionId: frame.sessionId });
});
```

I'm happy to support the PR if someone points me in the right direction.

Events: https://chromedevtools.github.io/devtools-protocol/tot/Page#event-screencastFrame

**Comment by jimevans** [comment]
You should take a look at the 4.0 alpha 2 release, which has listeners as part of the DevTools protocol integration.

**Comment by faeit** [comment]
@jimevans do you know for which languages this will be possible? Currently I only see a java implementation and nothing for e.g. python. Thanks in advance!

**Comment by jimevans** [comment]
@faeit There is a full implementation in .NET that will be available in alpha 3. I cannot speak to other language bindings.

**Comment by pawelusfr** [comment]
@jleyba do you plan to have this in JS bindings?

**Comment by remote-specialist** [comment]
> @faeit There is a full implementation in .NET that will be available in alpha 3. I cannot speak to other language bindings.

@jimevans, Is it possible to use this functionality now in .Net somehow? If not - how long it will take until it can be used?

**Comment by diemol** [comment]
This is available right now in all bindings (current version is `beta-2`). If someone needs help on how to get started please check our [docs](https://www.selenium.dev/documentation/en/) or feel free to ask questions through our [help/support channels](https://www.selenium.dev/support/).
