### ISSUE TITLE
Not able to login to Site using Selenium WebDriver

### ISSUE THREAD

**Issue by araveeti** [SeleniumHQ/selenium#7341]
I am unable to log into a site under test with the Selenium WebDriver, but am not having any issues logging in when running Automatically.

driver.Navigate().GoToUrl(this._baseURL + "Account/Index");
var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30));
wait.Until(drv => drv.FindElement(By.Id("element-on-next-page")));
The login button calls the jQuery $.ajax method to POST data to a service, and is correctly going into the success() method. The service returns a redirect URL.

Reference:  https://stackoverflow.com/questions/54329793/cant-log-in-to-site-under-selenium-webdriver

Note : I have entered the credentials manually on the Selenium Opened browser but still no luck...any idea to resolve?

Thank you very much

**Comment by cgoldberg** [comment]
sounds like an issue with your site under test..  There isn't enough info here to suggest there is an issue with selenium.

**Comment by araveeti** [comment]
Full Details are here in the Link...

 https://stackoverflow.com/questions/54329793/cant-log-in-to-site-under-selenium-webdriver

**Comment by araveeti** [comment]
Can we please reopen this issue?

**Comment by araveeti** [comment]
> sounds like an issue with your site under test.. There isn't enough info here to suggest there is an issue with selenium.



> sounds like an issue with your site under test.. There isn't enough info here to suggest there is an issue with selenium.

Could you please check the details here : https://stackoverflow.com/questions/54329793/cant-log-in-to-site-under-selenium-webdriver
