### ISSUE TITLE
Critical hide window feature missing

### ISSUE THREAD

**Issue by ziron999** [SeleniumHQ/selenium#7344]
## 🚀 Feature Proposal

headless for chrome causes massive javascript errors with things like ASP.net security.
If you run without headless it works fine.
This is a huge problem for someone writing in PowerShell making a GUI.

## Motivation

This guy created a solution:
https://pixytech.com/2016/09/09/selenium-webdriver-get-browser-hwnd/
Created an extension to your webdll to fix this problem.
PLEASE MAKE THIS POSSIBLE BY DEFAULT!
A good reason for this is when you are at a company and are restricted to only PowerShell this is the only possible way to get things done nice and sleek. You don't want a window popping up showing the automation when using a tool.
All you need is the HWND of the main window being used and it's already been done by this guy...

All sites of people trying to reach out to get this fixed:
https://social.msdn.microsoft.com/Forums/vstudio/ja-JP/afb2d145-7280-4600-9f9f-231d53f2db25/how-to-get-the-process-id-of-the-browser-when-i-launch-a-new-browser?forum=vstest
https://stackoverflow.com/questions/11526260/get-window-handle-intptr-from-selenium-webdrivers-current-window-guid
https://groups.google.com/forum/#!topic/selenium-users/gjFHDKhiZD8

you can just google it, you get the idea.

## Example

I'm sure there is many sites that do this out there but my examples are internal so sorry i can't give them.
Really https://pixytech.com/2016/09/09/selenium-webdriver-get-browser-hwnd/ shows exactly what's wrong too.
setup everything in powershell and try to hide it.
This is the only way to do it right now...
########################
#the main dll hack call
$code = '[DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow);'
#must use an add-type but it will stop itself after $seleniumdriver dies
$type = Add-Type -MemberDefinition $code -Name MyAPI -PassThru
#tricky part to get the HWND, could fail if you have more than one edge running
#this is the BIGGEST problem
###need to create something like a $seleniumDriver.Manage().Window.HWND###
$parentEdgeHWND = (Get-Process -Name "msedge").MainWindowHandle | Where-Object { $_.ToInt32() -gt 0 }
#detect if there is more than one by type.
#The type will change because it will be an array instead of a value
if ($parentEdgeHWND.GetType().BaseType -eq [System.ValueType]){
    #hide it
    [void]$type::ShowWindowAsync($parentEdgeHWND, 0)
}
else {
    #no way to fix this problem...need a better way to detect THIS window
    [System.Windows.Forms.MessageBox]::Show("Another instance of Microsoft Edge found...`r`nPlease Close it if you want to use this correctly...")
}
########################

**Comment by corevo** [comment]
There is no need to yell or to be snark, people will be more willing to help you if you're courteous.

Now let me see if I understand since your explanation since it misses a lot of context, you wanna run chrome headless but you can't because of some issues that are unrelated to webdriver, so instead you want to use win32 APIs to hide it, correct?

If this is the issue let me explain why there are very good reasons for this feature to not be in selenium:

- It is only for windows
- It only works in .net

In my mind selenium needs to offer the same tools for every language and every OS, and this feature which has little to do with selenium and more to do with windows makes less sense to me, but at the end it is up to the people who maintain .net to decide.

Cheers,
Tomer

**Comment by barancev** [comment]
Do you want Selenium to start browser in background by default? This feature would cause a lot of harm to users because some browsers don't emit 'focus' and 'blur' events while being run in background.

**Comment by ziron999** [comment]
This was possible in the internet explorer comobject by simply doing .hide / .show commands and was extremely helpful (maybe learn from that comobject?). Basically, we just need the same thing to happen. The thing is, at this rate internet explorer is going away. This will be the ONLY way to automate things in a good way soon. This is the only feature missing.

Why do you think it is only working in windows is not worth it? This is a very strange reason to not do it?! I don't get the logic behind that. If you want it to happen in other OS's then those OS's need to be created better. I'm practically giving the solution to windows. Other people who use other OS's need to find solutions. This is still progress right?

You can already use headless for the other disadvantages you are claiming in chrome as a default. Why not just make something in-between that makes it so information passes through correctly still from websites while not seeing chrome?

**Comment by jimevans** [comment]
@ziron999 I’m sorry, but I’m still confused about what behavior you actually desire. Please forgive me for not being smart enough to understand it at first reading. To help me understand better, I need to ask some follow-up questions.

First, you say that running Chrome in headless mode “causes massive javascript [sic] errors.” Can you be more specific? Moreover, why wouldn’t having these issues addressed in the browser showing the errors itself be a better approach?

Second, are you asking for this behavior for one browser in particular, or for all browsers? Leaving aside the (in my opinion unhelpful) comment about “learning from the Internet Explorer COM object,” how would you expect the code to behave? Do you expect the browser to be launched normally, then use a Windows API (or some .NET equivalent) to hide the resulting window? That doesn’t sound to me like it meets your requirements, as I don’t see how the window wouldn’t “flash” visible before being hidden.

Third, it sounds like you’re asking for the ability to get the launches browser’s window handle, which only makes sense on Windows. Given that Selenium is a cross-platform library, the project looks askance at solutions applying only to a single platform. Do you have any suggestions how to handle the lack of cross-platform availability? (Please note that, “I don’t care about a cross-platform solution, I only care about Windows,” is a non-starter. That is no better than the vast majority of open source projects that support Windows as only an afterthought. Any solution that requires conditional compile directives [`#if`] is likely to be rejected out of hand.)

Finally, the .NET bindings already supply the process ID of the driver executable via the `ProcessId` property of the `DriverService` class; there’s no need for complicated querying of what process is listening on the appropriate port. Does that make anything more palatable? How about if there were a companion library that made this easier, even if it’s not part of Selenium proper?

**Comment by ziron999** [comment]
1. Headless will not load pages correctly which causes errors and stops automation. Chrome has a --hide argument but it does not behave in this way. I think convincing google to do this would be much more difficult and take a way longer amount of time. Doing it here is fast because someone has already written a clear explanation on the website I provided on how to go about fixing it with Selenium.

2. It would be amazing if this is possible on all browsers but I'm not sure how well that will work out. Chrome is the current focus in the business environment I'm working in. I only mentioned the comobject because I wanted to show it's already been done. It could of been done the same way I'm doing it. My way would work with all browsers as long as you get the hwnd. If you run my code now, you see the browser for about a second and then it disappears. This is still better progress than nothing.
However, you do have a point. A more "long term" solution would be to have google add an argument. That is just a hope though when something can be done right now.

3. I think I already answered pretty well. People who use other OS's need to step up their game and make things better. No reason to stay in the stone age because a couple of people in the industry can't get their part to work in the industrial age? See what I'm saying here? Others need to adapt and keep up.

4. I actually think you guys could make an all together better solution then mine. It's just an example more than anything. There is something I need to make clear because there is something incorrect in your final statement. The ProcessId in the DriverService class is for the chromedriver.exe NOT the browser. So that's basically useless in this case. If you can get the PID of the browser that would actually be an easier call, absolutely.
I could write this extension myself and have it work no problem. Unfortunately a lot of companies out there will only let you use PowerShell. I can not use anything 3rd party outside of selenium. So there is company restrictions making that impossible. I'm sure there is tons of companies that frown on 3rd party files. Selenium is the only exception due to it being so powerful for automation.
Also, I agree about Edge. No reason to focus on it because if you just focus on Chrome you are fixing 2 browsers by default.

**Comment by jimevans** [comment]
As a point of clarification, I never intentionally claimed or implied that the process ID returned from the `DriverService` class was that of the launched browser. Naturally, it’s the ID of the driver process. However, it can be used (via the techniques mentioned in some of the references you linked to) to find the actual browser process ID. 

I’m afraid I cannot agree with your analysis of potential Windows-only solutions vs. valid cross-platform ones. Your argument is, to me, an argument _against_ making such a change, not for, in my opinion.

I think that something that is missing from the discussion is that Selenium doesn’t have any way to introspect into the browser process that gets started by the driver executable. It’s a black box as far as Selenium is concerned. Attempting to determine the OS window handle or process ID of the launched browser process would either be a rehash of the techniques you already alluded to, or would be so fraught with race conditions as to be less useful than one would like.

I’d be interested to understand how a corporate environment decides not to use open-source software, but gives Selenium a pass. As long as the source code is available for auditing, I’m not sure I recognize the difference. I know how the Selenium project is authored, and ascribing it some quality as “better” than “3rd party files” is probably a mistake in many cases. (Obligatory Disclaimer: The preceding paragraph is intended as humor. People work in the environment they have to, and I’m not indifferent to that.)

**Comment by barancev** [comment]
Did I understand right that the issue ("massive JS errors") occurs only on Windows and is related somehow to PowerShell? Can you please provide a sample that allows us to reproduce it?

**Comment by ziron999** [comment]
A good test for this is to try and automate Service Now (ticketing system) with SSO credentials. Do this headless with a separate profile and you will get a "bssonotsupported" loop issue via powershell.
This was just a work around to this issue since you can't do it headless.

**Comment by diemol** [comment]
Closing this as no way to reproduce the "massive JS errors" was provided, which could have lead to understand the issue better.
