### ISSUE TITLE
duplicated text sent by actionchains send_keys when integrating in for loop python

### ISSUE THREAD

**Issue by huynh-stack** [SeleniumHQ/selenium#7346]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
0

I try to send_keys to textarea so I use actionchains to send keys. I used this code:

```
url='https://translate.google.com/?hl=vi'
browserdriver.get(url)
list_test=['product description 1','product description 2']
for i in range (0,2):   
    try:
        body_text=list_test[i]
        browserdriver.execute_script("window.scrollTo(0, document.body.scrollHeight)")      
        item = WebDriverWait(browserdriver, 10).until(EC.presence_of_element_located((By.TAG_NAME, "textarea")))        
        actions.move_to_element(item).send_keys(body_text).perform()        
        time.sleep(1)
    except:
        pass
print("done")
```
And the result of text was sent to Google Translate as below:

`product description 1product description 1product description 2`
You can see that is so weird that it should be like this:

`product description 1product description 2`
I also inserted print() to utils.py in source code of actionchains in order to know what typing text is sent to send_keys function:

```
def keys_to_typing(value):
    """Processes the values that will be typed in the element."""
    typing = []
    for val in value:
        if isinstance(val, Keys):
            typing.append(val)
        elif isinstance(val, int):
            val = str(val)
            for i in range(len(val)):
                typing.append(val[i])
        else:
            for i in range(len(val)):
                typing.append(val[i])    
    print(typing)#this is a code line that I inserted
    return typing
```
and the output console of keys_to_typing is:

```
['p', 'r', 'o', 'd', 'u', 'c', 't', ' ', 'd', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', ' ', '1']
['p', 'r', 'o', 'd', 'u', 'c', 't', ' ', 'd', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', ' ', '1']

['p', 'r', 'o', 'd', 'u', 'c', 't', ' ', 'd', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', ' ', '2']
['p', 'r', 'o', 'd', 'u', 'c', 't', ' ', 'd', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', ' ', '2']
```
And this is the send_keys function in actionchains sourcecode:

```
def send_keys(self, keys_to_send):
        """
        Sends keys to current focused element.

        :Args:
         - keys_to_send: The keys to send.  Modifier keys constants can be found in the
           'Keys' class.
        """
        typing = keys_to_typing(keys_to_send)
        if self._driver.w3c:
            for key in typing:
                self.key_down(key)
                self.key_up(key)
        else:
            self._actions.append(lambda: self._driver.execute(
                Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': typing}))
        return self
```
Pls help me to explain this weird situation? I do not know why in loop for, actionchains.send_keys send duplicated content? thanks!

**Comment by twalpole** [comment]
Calling `perform` on an action chain doesn't reset the actions in it, so next time through the loop you're adding more actions to the existing chain and then performing the doubled/tripled/etc chain.  Either create a new action chain for each run through the loop or call `reset_actions` on the chain to empty it out each run through the loop.

**Comment by huynh-stack** [comment]
I added actions.reset_actions() to for looping but the result did not change:
```
for i in range (0,2):	
	body_text=list_test[i]	
	browserdriver.execute_script("window.scrollTo(0, document.body.scrollHeight)")	
	item = WebDriverWait(browserdriver, 10).until(EC.presence_of_element_located((By.TAG_NAME, "textarea")))	
	actions.move_to_element(item).send_keys(body_text).perform()
	actions.reset_actions()	
	time.sleep(1)
```
