### ISSUE TITLE
SendKeys fails to send CTRL+SPACE in InternetExplorer

### ISSUE THREAD

**Issue by ccarmannt** [SeleniumHQ/selenium#7352]
[Test.zip](https://github.com/SeleniumHQ/selenium/files/3352089/Test.zip)

## 🐛 Bug Report

When a test attempts to send the key combination CTRL+SPACE using the SendKeys method, the browser element receives only SPACE.

This does not occur in Chrome, but does in Internet Explorer.

## To Reproduce

Use the attached script and sample html file to execute this line of code:

````
		    input.SendKeys(OpenQA.Selenium.Keys.Control + " ");
````

In Chrome, we get the expected output "CTRL+32". In Internet Explorer, the output is just "32".

## Expected behavior

The browser/element should receive the full key combination, not just part of it.

## Test script or set of commands reproducing this issue

See attached.

## Environment

OS: Windows 10
Browser: Internet Explorer
Browser version: 11 (11.557.17763.0)
Browser Driver version: IEDriver 3.141.59
Language Bindings version: C#

**Comment by jimevans** [comment]
Without looking at the supplied test case, what happens if you use the `requireWindowFocus` capability?

**Comment by ccarmannt** [comment]
I don't see how that should change anything, but I'll try to test it.

There's only one window open, and the test clicks the element in the window before sending the text to it. How can the window not already have focus?

**Comment by jimevans** [comment]
@ccarmannt The `requireWindowFocus` capability triggers a different, "more correct" code path for simulating keystrokes. With the capability set, it uses the Windows `SendInput` API instead of the default and flawed `SendMessage` API. If it works using the `requireWindowFocus` capability, then the issue should be considered resolved, as there's no way to fix it for the `SendMessage` case.

**Comment by ccarmannt** [comment]
I was able to verify that setting this option does indeed fix the behaviour in my contrived simple testcase.
