### ISSUE TITLE
Alert is closed when UnhandledAlertException is thrown

### ISSUE THREAD

**Issue by kwilson-93** [SeleniumHQ/selenium#7356]
Issue Description:
ChromeDriver version: 75.0.3770.90
Chrome version: 75.0.3770.100
Selenium version: 3.141.0
Language: C#
OS: Windows 7

When an alert is displayed on the page (e.g. "Are you sure you wish to leave this page?"), and any interaction with the driver is made without switching to the alert before hand. When the UnhandledAlertException is thrown, the alert is closed.
In our scenario we have some code within a try-catch that we wish to execute regardless of whether an alert is displayed or not.
When the alert is displayed the UnhandledAlertException will be thrown and we will catch it and handle the alert appropriately.
We can no longer do this as when the UnhandledAlertException is thrown, the alert is now closed.

**Note: This was NOT an issue with the following:**
ChromeDriver version: 74
Chrome version: 74
Selenium version: 3.4.0
Language: C#
OS: Windows 7

**Note: This is also an existing issue with the IEDriver and Geckodriver.**

**Steps to reproduce:**
- Instantiate the driver.
- Navigate to "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt".
- Click the "Try it" button. An alert will be displayed.
- Excecute the following line of code:
string a = driver.Title;

Observed behaviour:
Alert is closed when UnhandledAlertException is thrown.

Expected behaviour:
Alert is not closed when UnhandledAlertException is thrown.

**Comment by twalpole** [comment]
Chrome 75 swapped to W3C mode by default. As such this is behaving as specified in the WebDriver spec - https://w3c.github.io/webdriver/#capabilities - where the default behavior is defined to be "dismiss and notify".  You should be able to get the previous behavior by setting the `unhandledPromptBehavior` capability to 'ignore' in your driver configuration - https://w3c.github.io/webdriver/#user-prompts.

**Comment by kwilson-93** [comment]
Thanks @twalpole :)
