### ISSUE TITLE
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Ljava/util/function/Function;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by Praveenroy05** [SeleniumHQ/selenium#7360]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by Praveenroy05** [comment]
Due to the above issue selenium is not able to identify the elements and also unable to fill any details even after identifying the element.

**Comment by diemol** [comment]
Please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by barancev** [comment]
It's a classpath issue, you must be having multiple version of Selenium in classpath that cause collisions.
