### ISSUE TITLE
HTTPonly cookies are invisible

### ISSUE THREAD

**Issue by 12tom12** [SeleniumHQ/selenium#7361]
## 🐛 Bug Report

With the function `get_cookies ()` no _HTTPonly_ cookies can be retrieved. I know that these will be blocked, but you can also use Python to get cookies in other ways, and I think the best options should be taken out of the program.

### Possible solution
The cookies are stored in a sqlite3 file from which it is possible to read these cookies and decrypten.
_For example:_
```
import sqlite3
conn = sqlite3.connect('selenium/Default/Cookies')
c = conn.cursor()
c.execute("SELECT encrypted_value FROM 'cookies' WHERE name = 'httponlycookie'")
val = c.fetchall()
```
I know the value is still encrypted, but it's possible to decrypten it because the key is stored on the same device.

I hope someone knows better than me and can solve the problem with selenium to get _HTTPonly_ cookies.

## Environment
OS: Windows 10, OSX
Browser: Chrome
Browser version: 75.0.3770.100
Language Bindings version: Python 3.7

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
I can't confirm the issue, tested with the following sample:
```
    driver.get("https://aws.amazon.com/ru/");
    driver.findElement(By.cssSelector("div[data-da-campaign=header_signup] a")).click();
    Thread.sleep(3000);
    Cookie c1 = driver.manage().getCookieNamed("JSESSIONID");
    assertTrue(c1.isHttpOnly());
```

**Comment by barancev** [comment]
Closing the issue as there is no reproduction scenario provided
