### ISSUE TITLE
W3C Endpoint for upload_file on Ruby Remote Web Driver.

### ISSUE THREAD

**Issue by gorod4512** [SeleniumHQ/selenium#7362]
## 🐛 Bug Report

errors when upload file in input file form in remote browsers - chrome v75 and firefox v60 and v65

## Fix by change it:
Edit Endpoint
from
upload_file: [:post, 'session/:session_id/se/file']
to
upload_file: [:post, 'session/:session_id/file']
in line 150 https://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/Remote/W3C/Bridge

## To Reproduce
Seleniod in Docker with selenoid/vnc:browser_ver
Ruby with selenium-driver gem ver. 3.142.3
## Expected behavior

Success uploads.

## More details in

https://github.com/aerokube/selenoid-images/issues/169

**Comment by twalpole** [comment]
The W3C spec doesn't have an upload file endpoint. The `session/:session_id/se/file` endpoint is a selenium extension to the protocol and as such should still have the `/se` in it.  If selenoid has removed that from their endpoint implementation it's a bug on their end.
