### ISSUE TITLE
TimeoutException - Failed to execute DevTools commands in CDP Listener

### ISSUE THREAD

**Issue by adiohana** [SeleniumHQ/selenium#7369]
## 🐛 Bug Report

When trying to send DevTools commands inside a DevTools "Listener" context, web socket requests always timing out.

## To Reproduce

past the below code as a test case in ChromeDevToolsNetworkTest. You will see that the response body is never printed. if you will set a break point in RealWebSocket:211 you will see that there is always a TimeoutException when trying to perform devTools operation inside Consumer#accept()

```
@Test
  public void failToSendDataInEventListener() {

    devTools.send(enable(Optional.empty(), Optional.empty(), Optional.empty()));

    devTools.addListener(loadingFinished(), new Consumer<LoadingFinished>() {
      @Override
      public void accept(LoadingFinished loadingFinished) {
        ResponseBody responseBody = devTools.send(getResponseBody(loadingFinished.getRequestId()));
        System.out.println(responseBody.getBody());
      }
    });

    chromeDriver.get(appServer.whereIs("js/skins/lightgray/content.min.css"));

}
```

## Expected behavior

DevTools commands should return successfully inside a "Listener".

## Environment

OS: OSX
Browser: Chrome
Browser version: 75
Browser Driver version: 75
Language Bindings version: 4.0.0-alpha-2

**Comment by adiohana** [comment]
@shs96c 
how do we address this issue? do you think this should be implemented on the client?

**Comment by adiohana** [comment]
@shs96c please advise how to use the Consumer functionality and having devtools calls inside a listener.

**Comment by rohitgargnj** [comment]
Did you find any solution? Please help if it worked for you. Iam facing same issue

**Comment by diemol** [comment]
Is this issue still valid with `beta-1`?

**Comment by diemol** [comment]
Closing as this should be working properly in the most recent released version and we did not get more information from the OP.
