### ISSUE TITLE
Error loading test case with selenium IDE

### ISSUE THREAD

**Issue by trieukma** [SeleniumHQ/selenium#737]
Then I setup browsers Firefox again. I open project.  I see error as below:
error loading test case: [Exception... "Component returned failure code: 0x8050000e (NS_ERROR_ILLEGAL_INPUT) [nsIScriptableUnicodeConverter.ConvertToUnicode]"  nsresult: "0x8050000e (NS_ERROR_ILLEGAL_INPUT)"  location: "JS frame :: chrome://selenium-ide/content/format.js :: Format.prototype.loadFile :: line 397"  data: no]

Can you help me. Thanks.

**Comment by barancev** [comment]
Please attach the test case that causes this issue.

**Comment by trieukma** [comment]
I cannot open old projects with this program on my computer (it works well on other machines). However I can still create new projects.

**Comment by barancev** [comment]
cc @samitbadle
