### ISSUE TITLE
IJavaScriptExecutor.ExecuteScript args

### ISSUE THREAD

**Issue by mshot** [SeleniumHQ/selenium#7384]
Not sure if bug or feature.

I have class _IWebElementExtended_ implementing _IWebElement_ interface, when i want to use it as argument for _IJavaScriptExecutor.ExecuteScript_ it throws **"Argument is of an illegal type ....IWebElementExtended ..."** 

i think i see where is the catch - method _private static object ConvertObjectToJavaScriptObject(object arg)_ expect _IWrapsElement_ or _IWebElementReference_ (to make list complete also not relevant _IEnumerable_ or _IDictionary_) so if _IWebElementExtended_ also implements _IWrapsElement_ then no exceptions is thrown - so Remarks part of _IJavaScriptExecutor.ExecuteScript_ isn't correct imho

> Arguments must be a number (which will be converted to a System.Int64), a System.Boolean,
> a System.String or a **OpenQA.Selenium.IWebElement**. An exception will be thrown
> if the arguments do not meet these criteria. The arguments will be made available
> to the JavaScript via the "arguments" magic variable, as if the function were
> called via "Function.apply" )
> 

C# + Selenium 3.141

**Comment by mshot** [comment]
Is possible "solution" append Remarks part of IJavaScriptExecutor.ExecuteScript to include info about IWrapsElement?

**Comment by diemol** [comment]
Would you like to send a PR and fix the docs?

**Comment by titusfortner** [comment]
added
7f6a93ea93768c7aa2c863a4910289934abced0d
