### ISSUE TITLE
Edge WebDriverException: Cannot start the driver service on http://localhost:65401

### ISSUE THREAD

**Issue by Elangopalakrishnan** [SeleniumHQ/selenium#7386]
OS:
Windows 10
Selenium Version:
.net Selenium.WebDriver package 3.12.0

MicrosoftWebDriver:
Microsoft Edge 40.15063.674.0 | Microsoft EdgeHTML 15.15063

Browser:
Microsoft Edge

Browser Version:
Microsoft Edge 40.15063.674.0

Language:
C#

Expected Behavior -
Create a webDriver instance for Microsoft Edge.

Actual Behavior -
OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:65401/

Steps to reproduce -
// path to MicrosoftWebDriver in system path.

//Microsoft webdriver path have set in System Env variables
                ser = EdgeDriverService.CreateDefaultService();
                EdgeDriver driver = new EdgeDriver(ser);
                return driver;

// second attempt:
WebDriver = new EdgeDriver();
return driver;

Both have exactly the same results.

**Comment by barancev** [comment]
Is there any reason you use 3.12 but not the latest version? Can you reproduce the issue with the latest stable version 3.141.0?

**Comment by icnocop** [comment]
What do you see when you explicitly run `MicrosoftWebDriver.exe --verbose` in an elevated command prompt?

This is what I see on my machine:
Windows 10 Version 1909 OS Build 18363.693
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363
MicrosoftWebDriver Version 10.0.18362.1
```
Starting server...
Listening on http://127.0.0.1:17556/
Listening on http://[::1]:17556/
HttpAddUrlToUrlGroup failed with 1232
```

In order to fix this issue, I had to explicitly set the `Host` property to either `localhost` or `127.0.0.1`:
```
var edgeDriverService = EdgeDriverService.CreateDefaultService();
edgeDriverService.Host = "127.0.0.1";
```

**Comment by diemol** [comment]
Seems we never got a reply from the OP.

Will close this as it seems not relevant anymore. However, if the issue still exists, please feel free to create a new one and fill out all the required information on the template.
