### ISSUE TITLE
Upgrade childprocess gem to 2.0

### ISSUE THREAD

**Issue by Medvezo** [SeleniumHQ/selenium#7387]
childprocess gem has recently [released 2.0.0 version](https://github.com/enkessler/childprocess). Change constraints to accommodate that change: https://github.com/SeleniumHQ/selenium/blob/master/rb/selenium-webdriver.gemspec#L34

**Comment by twalpole** [comment]
This was done via 95645b892e1671ff1e1477ab27d3f821b858bd36
