### ISSUE TITLE
Error message for Jenkins build: The driver is not executable: /var/lib/jenkins/workspace/smoke_job/src/test/resources/chromedriver/chromedriver.exe

### ISSUE THREAD

**Issue by ailabogasieru85** [SeleniumHQ/selenium#7391]
When I am running from eclipse every test is running fine having set the path like this 
    public static final String RELATIV_PATH = "/src/test/resources/chromedriver/chromedriver.exe";
    public static final String ABSOLUTE_PATH = System.getProperty("user.dir")+ RELATIV_PATH;	
@BeforeTest
public void setUp() {
		System.setProperty("webdriver.chrome.driver", ABSOLUTE_PATH);
	}
but when I am building it from Jenkins every test has the same err that the chromedriver.exe can not be executed, what is the workaround for this ?

Regards,

**Comment by barancev** [comment]
Don't use a windows executable on an unix system.
