### ISSUE TITLE
When standalone server converts OSS click to W3C actions, button info is lost

### ISSUE THREAD

**Issue by JohnChen0** [SeleniumHQ/selenium#7393]
## 🐛 Bug Report

When an OSS-protocol client app uses Selenium standalone server to connect to a W3C-protocol WebDriver implementation (e.g., ChromeDriver 75 and above), the standalone server converts OSS protocol requests to W3C format. When some mouse related commands (e.g., [`/session/:sessionId/click`](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidclick)) are converted, the specified `button` property is ignored, and `button: 0` is sent to the WebDriver.

## To Reproduce

Run the following shell commands from a Linux command prompt:

Start Selenium standalone server, configure ChromeDriver location, and enable ChromeDriver logging:

    java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver -Dwebdriver.chrome.logfile=chromedriver.log -jar selenium-server-standalone-3.141.59.jar &

Send OSS-format request to start a new session, and extract the session ID.

    SESSION_ID=`curl -s -XPOST http://localhost:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"chrome"}}' | jq -r .sessionId`

Try to click the right mouse button:

    curl -XPOST http://localhost:4444/wd/hub/session/$SESSION_ID/click -d '{"button":2}'

Open the generated `chromedriver.log` file, and observe that the above click command has been converted into the following Perform Actions command, with `button` property of 0 instead of 2:

    "actions": [ {
       "actions": [ {
          "button": 0,
          "type": "pointerDown"
       }, {
          "button": 0,
          "type": "pointerUp"
       } ],
       "id": "mouse",
       "parameters": {
          "pointerType": "mouse"
       },
       "type": "pointer"
    } ]

## Expected behavior

The converted Perform Actions command should have `"button": 2`.

This issue was originally reported by a ChromeDriver user at https://crbug.com/chromedriver/2967. The user's app uses a version of Protractor that only supports OSS protocol.

OS: All
Browser: Chrome
Browser version: 75.0.3770.100
Browser Driver version: ChromeDriver 75.0.3770.140 used in the repro, but should apply to any W3C compliant driver
Language Bindings version: N/A
Selenium standalone server version (if applicable): 3.141.59

**Comment by diemol** [comment]
@JohnChen0 
As far as I remeber, the Selenium server convers capabilities from JWP to W3C and viceversa as needed. But that's it, it does not do any command conversion, so in this case the client side needs to use a recent binding version that sends W3C compatible commands.

@barancev @shs96c please correct me if I am wrong.

**Comment by JohnChen0** [comment]
Apparently some kind of command conversion happened in this case. I sent a /session/$SESSION_ID/click command to the standalone server, and a perform actions command came out at the other end. However I couldn't find the code that does the conversion, otherwise I'd be happy to try to make a fix.

**Comment by jimevans** [comment]
@diemol Yeah, this is the old OSS dialect version of `Actions.click()`, not `WebElement.click()`. There must be a protocol translation bug there somewhere.

**Comment by diemol** [comment]
@jimevans yes, I get that the client expects a translation of the `click` command from JWP to W3C, this in the case that the client is using an old WebDriver client. What I was trying to say is, IIRC, this was never considered/implemented in the Selenium server. What was only implemented, by @shs96c I think, was the capability translation between both protocols.

**Comment by barancev** [comment]
Closed by PR #7710
