### ISSUE TITLE
executeScript returns float number with e-notation as Long 

### ISSUE THREAD

**Issue by vkhromenkov** [SeleniumHQ/selenium#7398]
## 🐛 Bug Report

JavascriptExecutor.executeScript() returns float numbers with e-notation as Long instead of Double

## To Reproduce

Object ret = ((JavascriptExecutor) driver).executeScript("return parseFloat('6.02214129e+23');");

## Expected behavior

ret has Double class with value 6.02214129e+23

## Actual behavior

ret has Long class with value 9223372036854775807

## Test script or set of commands reproducing this issue

See above, just one line

## Environment

OS: Windows10
Browser: Chrome, Firefox, Internet Explorer
Browser version: 75.0.3770.100, 68, 11 
Browser Driver version: ChromeDriver 75.0.3770.90, GeckoDriver 0.24, InternetExplorerDriver 3.14.0
Language Bindings version: Java 1.8.0_201
Selenium Grid version (if applicable): 3.141.59

**Comment by albertor24** [comment]
I believe the issue is due to https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/json/JsonTypeCoercer.java#L80 not accounting for `Long` overflow

I would propose a change like
```
builder.add(
        new NumberCoercer<>(
            Number.class,
            num -> {
              double doubleValue = num.doubleValue();
              if (doubleValue % 1 != 0 || doubleValue > Long.MAX_VALUE) {
                return doubleValue;
              }
              return num.longValue();
            }));
```

If this change is OK, what would be the best place to add a unit test for this?
