### ISSUE TITLE
Fix Ruby spec execution

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#7400]
This is in response to #7264, since we decided that PR is not the right way to do it. 

I think we decided on: move the non-browser-specific tests out of the browser-specific test files.

So if the "chrome only" tests pass when using Firefox for instance, they should be moved to unit tests or into a common spec file of some kind.

**Comment by oneEdoubleD** [comment]
I'm happy to pick this up.

**Comment by p0deje** [comment]
@titusfortner @oneEdoubleD Any update on this?

**Comment by titusfortner** [comment]
This was fixed with #8511
