### ISSUE TITLE
Expose Event Bus to local ends

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7401]
CDP is an event-based API. We know that we need to remote the CDP across the network from the local machine, possibly through any number of intermediary nodes. To do so, we need a mechanism to expose the grid's event bus to users.

We should consider a dual-pronged approach.

 * Upgrade connections to HTTP/2 and push events to the user
 * Provide some sort of "store and forward" approach, either using long hanging GETs ("Comet style") or simple polling. The former will be more in line with the HTTP/2 approach, the latter will be laggier but more robust.

**Comment by diemol** [comment]
Just to remember why we closed it:
![image](https://user-images.githubusercontent.com/5992658/106479346-87c53b80-64aa-11eb-9394-e608a92807e8.png)
