### ISSUE TITLE
When running a WebDriven Firefox with a prepared profile, extensions get stopped after some seconds

### ISSUE THREAD

**Issue by KOLANICH** [SeleniumHQ/selenium#7403]
## 🐛 Bug Report
When running selenium with a prepared profile, extensions browser actions get disappeard after some seconds. They also stop working.

1. fx starts
2. all actions are visible and work
3. suddenly they disappear
4. they are still enabled in about:addons, but not working.

Workaround:

```python
def newTab(fx, url="about:blank"):
	wnd = fx.execute(selenium.webdriver.common.action_chains.Command.NEW_WINDOW)
	handle = wnd["value"]["handle"]
	fx.switch_to.window(handle)
	fx.get(url) # changes handle
	return fx.current_window_handle

def retoggleAllTheAddons(fx):
	"""FF has some glitch - I don't see addons actions in the panel and it is unclear if they still work or broken"""
	initialHandlesCount = len(fx.window_handles)
	addonsTabHandle = newTab(fx, "about:addons")
	fx.execute_script("""
		let hb = document.getElementById("html-view-browser");
		let al = hb.contentWindow.window.document.getElementsByTagName("addon-list")[0];
		let cards = al.getElementsByTagName("addon-card");
		for(let card of cards){
			card.addon.disable();
			card.addon.enable();
		}
	""")
	if len(fx.window_handles) != 1:
		fx.switch_to.window(addonsTabHandle)
		fx.close()
```

It is a regression. I remember that some versions ago (I don't remember the dates and exact versions) everything was ok.

## To Reproduce
Start a fx with a profile with some extensions.

## Expected behavior
They should not be stopped.

## Environment

OS: Win 7
Browser: Firefox
Browser version: 69.0b5
Browser Driver version: geckodriver 0.24.0
Language Bindings version: python, 4.0.0a1

**Comment by cgoldberg** [comment]
please report geckodriver issues to:  https://github.com/mozilla/geckodriver/issues
