### ISSUE TITLE
Sockets to chromedriver left in CLOSE_WAIT after `driver.quit`

### ISSUE THREAD

**Issue by bblack** [SeleniumHQ/selenium#7405]
## 🐛 Bug Report

`Selenium::WebDriver::Chrome::Driver#quit` leaves sockets open to chromedriver in `CLOSE_WAIT` state. A long-running process that opens and quits drivers can reach the system's file descriptor limit, causing the system to become unresponsive.

## To Reproduce

Detailed steps to reproduce the behavior:

In ruby:

```rb
puts "pid: #{Process.pid}"
```

In shell, confirm no TCP sockets are open from the ruby process:

```sh
lsof -p <pid>
```

Back in ruby:

```rb
require 'selenium-webdriver'

def new_driver
  driver_options = Selenium::WebDriver::Chrome::Options.new()
  driver_capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(loggingPrefs: {performance: 'ALL'})

  Selenium::WebDriver.for :chrome,
    listener: -> (event_name, *args) { puts "heard #{event_name}, #{args}" },
    options: driver_options,
    desired_capabilities: driver_capabilities
end

10.times { new_driver.quit }
```

And back in the shell:
```sh
lsof -p <pid>
```

The output will vary in format and clarity, depending on the host system. For example, on Mac OS, this will produce lines like:

```
ruby    20725 brian    9u   IPv4 0xe090a3bf8124a885        0t0      TCP localhost:58481->localhost:9516 (CLOSE_WAIT)
```

On Amazon Linux, it's more cryptic:
```
ruby    14866 ec2-user  413u  sock                0,8         0t0 2264485717 can't identify protocol
```

## Expected behavior
Sockets to chromedriver (e.g. TCP to remote port 9515) are closed on `quit`.

## Test script or set of commands reproducing this issue

See above.

## Environment

OS: Have reproduced this on Mac OS 10.14.5 and Amazon Linux 1, from MRI and JRuby.
Browser version: 75.0.3770.142 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29})
Language Bindings version: Ruby gem `selenium-webdriver` 3.11.0 and 3.142.3

**Comment by twalpole** [comment]
Sockets in a CLOSE_WAIT state should get cleaned up by garbage collection. If it's not happening try forcing garbage collection via `GC.start`

**Comment by bblack** [comment]
Tried that, to no avail.

**Comment by twalpole** [comment]
Did you try on MRI or JRuby -- The close_wait sockets went away on MRI in your example above for me on MRI 2.6.3

**Comment by twalpole** [comment]
https://gist.github.com/twalpole/ab163ea5f680306a50f554ecd62f3d6b  Is the exact code I ran which works fine under MRI (all clear after garbage collection runs)-- it does exhibit the issue under JRuby which appears to be a bug in JRuby since we are closing the connection (calling `finish` on the Net::HTTP instance)

**Comment by bblack** [comment]
Aha, you're right. For me as well, on JRuby they stay open, but on MRI, they do get closed.

This is JRuby 9.1.7.0, which is over 2 years old now. Did you reproduce on a more recent version?

**Comment by twalpole** [comment]
I replicated on the current JRuby (9.2.7.0)

**Comment by bblack** [comment]
Still doesn't seem quite right that the intended behavior is to rely on Ruby garbage collection to close the sockets. Outside of this lib, I don't see an issue in closing TCP sockets from the Ruby side; could it be that the Ruby side calls `finish` and chromedriver fails to ack?

**Comment by twalpole** [comment]
@bblack If by "rely on Ruby garbage collection to close the sockets" you mean "use the Net::HTTP API" - then yes that's what this lib does.  It's only an issue in your MRI example because the small amount of code hasn't yet consumed enough memory, and is doing so little in the loop, that it hasn't yet prioritized automatically running background GC. That really shouldn't be an issue in a normal application (although JRuby definitely appears to have a bug).  It's definitely possbile chromedriver isn't correctly handling the connection being closed, but if that's the case what would you like Selenium to do about?  Open to all suggestions.

**Comment by bblack** [comment]
Likely I don't have the time to dig deeper right now, but I used Net::HTTP to connect to chromedriver's TCP port, and it did not exhibit the same behavior. This makes me suspicious that either the webdriver ruby bindings are at fault, or they are doing something different than I am that causes some fault in chromedriver to be exposed. Unfortunately I don't have the tmie at the moment to dig deeper.

**Comment by ShaguftaShaikh** [comment]
I am not sure if this is gonna help but my team was facing the same issue and what we did was keeping the chromedriver process running in the background and used its URL ("http://localhost:9515") for setting the DesiredCapabilities while initializing WebDriver which in turn solved the problem of CLOSE_WAIT.

We are using Java + Selenium + Chromedriver.
