### ISSUE TITLE
Set focus to an input field in iOS/Safari

### ISSUE THREAD

**Issue by go-green** [SeleniumHQ/selenium#7407]
I am trying to automate tests on iOS 12.3.1 on Safari browser using RemoteWebDriver. I have a real device (iPad) and using Appium version 1.13.0. When I execute `element.SendKeys("some text")`, it's not triggering the character length validation. Then I tried using Actions (OpenQA.Selenium.Interactions.Actions) and figured out that, `Action.SendKeys(...)` trigger the character length validation if I can set focus into the input field. (When I set the focus manually, The iOS/iPad's keyboards get activated and comes to the screen and plus the cursor starts blicking inside the input element). I want to simulate the same behavior to send keys using actions.  

I have tried so many options including `javascript .focus()` and nothing seems to work to get the focus to the input field. The element itself has autofocus attribute, but still no luck. Any advice? 

Below is the element

`<input autofocus="autofocus" class="form-control" data-auto="CodeInput" data-val="true" data-val-required="Enter a valid code" id="Code" maxlength="6" name="Code" oninput="this.value=this.value.replace(/[^0-9]/g,'');" placeholder="Enter verification code" type="text" value="">`

This is how I initialized the remote web driver

```
case "SafariOniOS":
    var iOSCaps = new DesiredCapabilities();
    iOSCaps.SetCapability("platformName", "iOS");
    iOSCaps.SetCapability("platformVersion", Settings.PlatformVersion);
    iOSCaps.SetCapability("browserName", MobileBrowserType.Safari);
    iOSCaps.SetCapability("automationName", "XCUITest");
    iOSCaps.SetCapability("udid", Settings.DeviceId);
    iOSCaps.SetCapability("deviceName", Settings.DeviceName);
    iOSCaps.SetCapability("xcodeOrgId", Settings.AppleDeveloperTeamId);
    iOSCaps.SetCapability("xcodeSigningId", "iPhone Developer");
    iOSCaps.SetCapability("newCommandTimeout", 360);
    
    var iOSCommandExecutor = new SomeCommandExecutorImpl(
    	new Uri(Settings.RemoteServerAddress),
    	Timeout.InfiniteTimeSpan)
    {
    	CommandsToIgnore = SomeCommandExecutor.CommandsToIgnoreForMobileWeb
    };
    return new RemoteWebDriver(iOSCommandExecutor, iOSCaps);
```

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
