### ISSUE TITLE
NoSuchElementException in Selenium 2.46.0

### ISSUE THREAD

**Issue by DavidQA** [SeleniumHQ/selenium#741]
Hi,
since updating Selenium from 2.45.0 to 2.46.0 i get a NoSuchElementException when calling driver.findElement(By.id(String id)). I use Firefox 38 and also tried with Firefox 39. 

The following can be used te reproduce the issue.

		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		
		FirefoxProfile firefoxProfile = new FirefoxProfile();
		firefoxProfile.setAcceptUntrustedCertificates(true);
		firefoxProfile.setPreference("browser.cache.disk.enable", false);
		firefoxProfile.setPreference("browser.cache.memory.enable", false);
		firefoxProfile.setPreference("browser.cache.offline.enable", false);
		firefoxProfile.setPreference("network.http.use-cache", false);
		
		firefoxProfile.setPreference("dom.ipc.plugins.enabled", false);
		firefoxProfile.setPreference("dom.ipc.plugins.timeoutSecs", -1);
		
		firefoxProfile.setPreference("webdriver.load.strategy", "unstable");
		
		capabilities.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
		
		capabilities.setPlatform(Platform.WINDOWS);
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability(CapabilityType.HAS_NATIVE_EVENTS, false);
		capabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);

		driver = new FirefoxDriver(capabilities);
		driver.manage().window().maximize();
		driver.get("http://www.seleniumhq.org/");
		WebElement search = driver.findElement(By.id("q"));
		search.sendKeys("2.46.0");

It is a Maven Project and has the following dependencies in the pom.xml:

    <dependencies>
	  	<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.46.0</version>
		</dependency>
		  	<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>2.46.0</version>
		</dependency>
	</dependencies>

When running the code above the following error occurs:

Exception in thread "main" org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"q"}
Command duration or timeout: 14 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'hostname', ip: 'hostip', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 886190f7-f376-445a-b4cd-b5ae187277e3
*** Element info: {Using=id, value=q}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:399)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at test.core.Test.showCase(Test.java:23)
	at test.run.TestRun.main(TestRun.java:11)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"q"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'hostname', ip: 'hostip', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_25'
Driver info: driver.version: unknown

If i change the versions in the pom.xml back to 2.45.0 everthing works again.

Is there any solution for this issue?

Thanks in advance.

**Comment by ddavison** [comment]
Try not to file bugs that are using "unstable" techniques.

Take out

```java
firefoxProfile.setPreference("webdriver.load.strategy", "unstable");
```

After taking that out, it has a 100% pass rate.

Leaving that in, granted me a 60% pass rate.

**Comment by DavidQA** [comment]
Sorry for that.
We put it in so that the webdriver doesn't wait for the whole page to be loaded.
Thanks anyways.

**Comment by ddavison** [comment]
then that is your issue :smile: - `webdriver doesn't wait for the whole page to be loaded`.  The search box doesn't load in time
