### ISSUE TITLE
Debugger.setPauseOnExceptions passed to ChromeDevTools using execute_cdp_cmd() have no effect

### ISSUE THREAD

**Issue by Debanjan-B** [SeleniumHQ/selenium#7410]
## 🐛 Bug Report

I was trying to set[ `Debugger.setPauseOnExceptions`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-setPauseOnExceptions) as `"state": "all"` using [`execute_cdp_cmd()`](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_chrome/selenium.webdriver.chrome.webdriver.html#selenium.webdriver.chrome.webdriver.WebDriver.execute_cdp_cmd) method through Selenium Python Clients. But it seems `Debugger.setPauseOnExceptions` passed to ChromeDevTools using `execute_cdp_cmd()` have no effect.

## Code Block:

	from selenium import webdriver

	chrome_options = webdriver.ChromeOptions() 
	chrome_options.add_argument("start-maximized")
	chrome_options.add_argument("disable-infobars")
	chrome_options.add_argument("--auto-open-devtools-for-tabs")
	chrome_options.add_argument("--remote-debugging-port=0")
	driver = webdriver.Chrome(options=chrome_options, executable_path=r'C:\Utility\BrowserDrivers\chromedriver.exe')
	driver.execute_cdp_cmd("Debugger.enable", {})
	driver.execute_cdp_cmd("Debugger.setPauseOnExceptions", {"state": "all"})
	driver.get("https://protonmail.com/")

Result: Despite using `"state": "all"` I am still not able to _PauseOnExceptions_.

Detailed steps to reproduce the behavior:

## Expected behavior

Where as manually turning **ON** _Pause on exception_ correctly pauses the execution.

Screenshot of _Pause on exception_ when turned **ON** manually:

paused_on_exception
![paused_on_exception](https://user-images.githubusercontent.com/26503213/61528288-fe6f2500-aa3b-11e9-867f-2d0e15145a0c.png)

## Actual behavior:

Screenshot of error on ChromeDevTools Console tab:

Console
![Console](https://user-images.githubusercontent.com/26503213/61528352-26f71f00-aa3c-11e9-8c68-4958fb2be2e3.png)

Screenshot of error on ChromeDevTools Sources tab where _Pause on exception_ is not selected:

Sources
![Sources](https://user-images.githubusercontent.com/26503213/61528371-2eb6c380-aa3c-11e9-8bb7-eb99ae758b11.png)

## Environment

OS: Windows 8
Selenium version: 3.141.0
Browser: Google Chrome
Browser version: 75.0
Browser Driver version: ChromeDriver v75.0
Language Bindings version: Python 
Selenium Grid version (if applicable): N/A

**Comment by AutomatedTester** [comment]
This is either a limitation in geckodriver due to the polling nature of selenium and will likely get fixed when we add CDP support
