### ISSUE TITLE
ExpectedConditions#elementToBeClickable(By) fails to locate web element using linkText

### ISSUE THREAD

**Issue by hfontanez1968** [SeleniumHQ/selenium#7411]
## SSCCE 
 String path = "YOUR PATH";
 System.setProperty("webdriver.chrome.driver", path);
 ChromeOptions options = new ChromeOptions();
 options.addArguments("enable-automation");
 options.addArguments("--window-size=1920,1080");
 options.addArguments("--no-sandbox");
 options.addArguments("--disable-extensions");
 options.addArguments("--dns-prefetch-disable");
 options.addArguments("--disable-gpu");
 options.setPageLoadStrategy(PageLoadStrategy.NORMAL);
 WebDriver driver = new ChromeDriver(options);
 //By by = By.xpath("//a[text()='LINK TEXT']") <-- this works
 By by = By.linkText("LINK TEXT"); // This doesn't
 WebElement element = new WebDriverWait(driver, 2)
 	.until(ExpectedConditions.elementToBeClickable(by)); // throws exception when using linkText

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 75.0.3770.142
Browser Driver version: 75.0.3770.140 
Selenium WebDriver version: 3.141.59
Language Bindings version: Java

**Comment by hfontanez1968** [comment]
I am running a simple test where I need to locate a hyperlink. When I use a relative XPath to the component, my code succeeds locating it. However, when I use linkText using the same link text I used in my XPath expression, the web driver times out locating the component and throws a TimeoutException. The following is part of the exception stack trace.

`org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: By.linkText: Products (tried for 2 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at stepDefinition.XpressoStepDefinitions.hover(XpressoStepDefinitions.java:65)
	at ✽.I hover over "link(Products)"(features/Hector/XpressoBP.feature:23)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"Products"}
  (Session info: chrome=75.0.3770.142)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'XXXXXXX', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 75.0.3770.142, chrome: {chromedriverVersion: 75.0.3770.140 (2d9f97485c7b..., userDataDir: C:\Users\HFONTA~1\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:52434}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 1c863c7fd2e434e367e83b9cf16f39a6
*** Element info: {Using=link text, value=Products}`

**Comment by sharmaravi019** [comment]
hi @hfontanez1968 - I tried reproducing this issue in Chrome but it works fine with both the methods(linkText, xpath). Below is a snippet of what I have tried.

`System.setProperty( "webdriver.chrome.driver", "chromedriver" );
        WebDriver driver = new ChromeDriver();

        driver.get( "http://linkedin.com" );

        By by = By.linkText( "Sign in" );

        //  By by = By.xpath( "//a[text()='Sign in']" );

        WebElement element = new WebDriverWait( driver, 10 ).until( ExpectedConditions.elementToBeClickable( by ) );

        element.click();`
I have tried with and without ChromeOptions and it worked.

Environment:
`OS: macOS Mojave,
Browser: Chrome,
Browser version: 75.0.3770.142,
Browser Driver version: 75.0.3770.140,
Selenium WebDriver version: 3.141.59,
Language Bindings version: Java`

Let me know if i have missed anything while reproducing this.

**Comment by hfontanez1968** [comment]
Hello @sharmaravi019 

You didn't miss anything. I will try to test outside our webapp. But it is weird that I got consistent failures using Chrome Driver but passed using Gecko Driver without making any changes to my tests.

I will update this thread with my results.  Thank you!

**Comment by hfontanez1968** [comment]
@sharmaravi019 

I am not sure what's going on.... This is the part of the HTML document I am trying to test:

`<div class="item-ov1 left-nav-item-4jdw"><a href="/app/" class="toggle-ov1 css-yr5le">Products</a></div>`

When I try:
`By by = By.xpath("//a[text()='Products']");`
Works fine, but when I try
`By by = By.linkText("Products");`
fails every time.  I also tried with `WebDriverWait` and `WebDriver#findElement(By)`

```
//	WebElement element = new WebDriverWait(driver, waitTime)
//		.until(ExpectedConditions.elementToBeClickable(by));
	WebElement element = driver.findElement(by);

```
None work when using link text. It is extremely strange.

**Comment by hfontanez1968** [comment]
Disregard this issue. Apparently there is something wrong with this web element specifically. I ran a different test case using the same function to interact with other links and it works.

That said, I still find it bizarre that the same code and test works when I simply switch the driver to gecko.
