### ISSUE TITLE
DevTools Network.responseReceived() does not return the timing property 

### ISSUE THREAD

**Issue by takeya0x86** [SeleniumHQ/selenium#7413]
## 🐛 Bug Report

The `responseReceived.getResponse().getTiming()` method always returns `null`.

## To Reproduce

See below.

## Expected behavior

`responseReceived.getResponse().getTiming()` returns the value.

## Test script or set of commands reproducing this issue

```java
  @Test
  void testNetworkTraffic() {
    try (DevTools devTools = driver.getDevTools()) {
      devTools.createSession();
      devTools.addListener(Network.responseReceived(), (responseReceived -> {
        assertNotNull(responseReceived);
        assertNotNull(responseReceived.getResponse());
        assertNotNull(responseReceived.getResponse().getTiming());  // failed
      }));
      devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
      driver.get("https://www.seleniumhq.org/");
    }
  }
```

## Environment

OS: macOS Mojave
Browser: Chrome
Browser version: 75
Browser Driver version: ChromeDriver 75.0.3770.8
Language Bindings version:  Java 4.0.0-alpha-2
Selenium Grid version (if applicable):

**Comment by adiohana** [comment]
Hi @takeya0x86,

Indeed, the parser for "ResourceTiming" was missing. Added it in #7415

**Comment by takeya0x86** [comment]
Hi @adiohana, Thank you for fixing! I'm waiting for merging this.

**Comment by adiohana** [comment]
@p0deje I think we can close this, issue was fixed.

**Comment by barancev** [comment]
Done
