### ISSUE TITLE
 Selenium Webdriver fails to open chrome browser  in C#

### ISSUE THREAD

**Issue by kshigli** [SeleniumHQ/selenium#7417]
## 🐛 Bug Report
Selenium Webdriver fails to open chrome browser  in C#

## To Reproduce
Run the below test script using 'dotnet test' in Visual Studio Code

## Expected behavior

Open new chrome browser

## Test script or set of commands reproducing this issue
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using NUnit.Framework;
using SeleniumExtras.PageObjects;

namespace NAS
{
    [TestFixture]
    class Program
    {
        public static IWebDriver driver;

        [OneTimeSetUp]    
		public void startBrowser()
        {
            //System.Environment.SetEnvironmentVariable("webdriver.chrome.driver","C:\\Program Files\\Selenium");
            ChromeOptions opt = new ChromeOptions();
            opt.BinaryLocation = @"C:\ProgramData\Microsoft\AppV\Client\Integration\520B8677-106E-430B-8927-6F9261C56329\Root\VFS\ProgramFilesX86\Google\Chrome\Application\chrome.exe";
        
         driver = new ChromeDriver(@"C:\Progra~1\Selenium", opt);
            
            driver.Navigate().GoToUrl("http://www.goto.com");            
            //driver.Manage().Window.Maximize();
        }

        [Test]
		public void testLogin()
        {
            Console.WriteLine("test running..");
            Console.WriteLine("test");        
        }

        [OneTimeTearDown]
		public void closeBrowser()
        {
            //driver.Quit();
        }

    }
}

## Environment

OS: Windows 10
Browser: Google Chrome
Browser version: Version 74.0.3729.131 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 74.0.3729.6
Language Bindings version: C#

## Test Output
Starting test execution, please wait...
SetUp failed for test fixture NAS.Program
OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\ProgramData\Microsoft\AppV\Client\Integration\520B8677-106E-430B-8927-6F9261C56329\Root\VFS\ProgramFilesX86\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.14393 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at NAS.Program.startBrowser() in C:\NAS\Program.cs:line 28
Failed   testLogin
Error Message:
 OneTimeSetUp: OpenQA.Selenium.WebDriverException : unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\ProgramData\Microsoft\AppV\Client\Integration\520B8677-106E-430B-8927-6F9261C56329\Root\VFS\ProgramFilesX86\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.14393 x86_64)

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 8.4633 Seconds

**Comment by abmptit** [comment]
I have same problem, I changed my chromedriver location, it works...

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
