### ISSUE TITLE
npm versions behind

### ISSUE THREAD

**Issue by pauldraper** [SeleniumHQ/selenium#7420]
The latest (stable) version available in npm is 3.6.0.

I am interested in using this change from 2 years ago: https://github.com/SeleniumHQ/selenium/commit/bac9cdf9731f6d466db2ca1b6edf9ffe0d284a3d

**Comment by diemol** [comment]
We realise that the releases for the JS bindings have not been ideal, but we have improved that in the recent months. Please feel free to use the most recent [Alpha](https://www.npmjs.com/package/selenium-webdriver/v/4.0.0-alpha.8), which should be stable enough for normal use. We are soon moving to Beta 1. 

For any more questions or comments, feel free to drop by our Slack/IRC channels, see the links [here](https://www.selenium.dev/support/).
