### ISSUE TITLE
IE 11 Selenium Test Case automation is not launching

### ISSUE THREAD

**Issue by Malleshrms** [SeleniumHQ/selenium#7425]
Hello Team,

I am unable to Launch UI Test cases in **Internet Explorer** in Windows SERVER 2016.But chrome is launching with out any issues. Below is the Error MEssage.

  Failed: Unable to get browser
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'xxxxxxx', ip: '10.146.0.25', os.name: 'Windows Server 2016', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'
    Driver info: driver.version: unknown

Thanks
Mallesh

**Comment by barancev** [comment]
This is a question rather than an issue.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
