### ISSUE TITLE
Updated drivers in folder driver c# nugetPackage

### ISSUE THREAD

**Issue by ChuchoPV** [SeleniumHQ/selenium#7426]
This is not an issue at all. Is more a suggestion. 

I'm a developer that uses a lot this library in Mac and Windows in C#. It would be nice to have al the drivers in a same folder when downloading the NuGet package from the NuGet Packager Manage Tool in Visual Studio. It would be better than looking for any driver on internet.

Hope this works. Nice Library!!!!!

**Comment by jimevans** [comment]
The Selenium project does not maintain NuGet packages for browser-specific drivers. There are no plans to do so, as the browser drivers’ code (with the exception of the IE driver) is not maintained by the Selenium project.
