### ISSUE TITLE
Node.js npm package does not have lib/test anymore

### ISSUE THREAD

**Issue by oddui** [SeleniumHQ/selenium#7427]
The node.js npm package used to have the `lib/test` folder which contains code for a web server and web pages for testing. I use it for testing in a project that depends on the node.js npm package.

However It does not exist anymore in the current version 4.0.0-alpha.4. I'm just wondering if it's removed by intention or by accident so i can plan what i do.

## Last working Selenium version

Worked up to version:

4.0.0-alpha.1

Stopped working in version:

4.0.0-alpha.3

**Comment by rouke** [comment]
As far as I'm concerned, these directories should not be shipped with the normal module, but as a separate 'dev' module (as per nodejs module design guidelines: don't include testing and example code in a production module). Issue "Fix .npmignore #6005" from June last year notices this already and I hope the removal of said inclusions is a result of issue #6005.

**Comment by oddui** [comment]
@rouke thank your that makes sense.

However I think I saw somewhere that the test files are included by intention. Might be [this issue](https://github.com/SeleniumHQ/selenium/pull/3033#issuecomment-257977070) that I saw. Just want to confirm that if `lib/test` will be put back.

**Comment by baruchvlz** [comment]
If I may ask, why would you want this to be shipped?

**Comment by oddui** [comment]
@baruchvlz I used to use the included web server and html pages to test my project. I have moved on to create my own.
