### ISSUE TITLE
Linux selenium simulation Ctrl+V operation picture 

### ISSUE THREAD

**Issue by jxlining** [SeleniumHQ/selenium#7428]
Linux selenium simulation Ctrl+V operation, the text can be successful, the picture can not be successful, the windows are normal, what may be the reason

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
