### ISSUE TITLE
Namespace problem with the latest chromedriver

### ISSUE THREAD

**Issue by rdonuk** [SeleniumHQ/selenium#7429]
## 🐛 Bug Report

When I get my web page source with selenium 3.141.59  and latest chromedriver, no namespace (I am expecting xmlns="http://www.w3.org/1999/xhtml") returns. But I am able to get namespace while I was using chromedriver 2.46.

So, in my XSL file, I am getting "The source document is in no namespace, but the template rules all expect elements in a namespace". I don't want to change all of my XSL files and remove namespace declarations. What can be the reason of that difference?

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 75.xx
Browser Driver version: ChromeDriver 2.46 and latest
Language Bindings version: java 8
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
Please report this issue to https://bugs.chromium.org/p/chromedriver/issues/
