### ISSUE TITLE
org.openqa.selenium.WebDriverException: TypeError: Expected an element or WindowProxy, got: [object Text] {}

### ISSUE THREAD

**Issue by Ad-a-m** [SeleniumHQ/selenium#7435]
## 🐛 Bug Report

When I'm trying find Text element using findElements in context of WebElement, then I'm getting error: TypeError: Expected an element or WindowProxy, got: [object Text] {}
issue is with Firefox GeckoDriver but in browser this Xpath working as expected

## To Reproduce

List<WebElement> txtBefore = someWebElement.findElements(By.xpath("./preceding-sibling::text()"))

Detailed steps to reproduce the behavior:

## Expected behavior

it should find all Text elements

## Environment

OS: Windows 10
Browser: Firefox Quantum 
Browser version: 60.8.0esr (32bits)
Browser Driver version: geckodriver-v0.24.0-win64
Language Bindings version: java amazon-corretto-8.212.04.2-windows-x64
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
Selenium can work with element nodes only, text nodes are not supported.

**Comment by Ad-a-m** [comment]
Is there any way to check Text before element?

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
