### ISSUE TITLE
Unable to launch Edge browser

### ISSUE THREAD

**Issue by amitstudent2006** [SeleniumHQ/selenium#7437]
![selenium edgebrowser](https://user-images.githubusercontent.com/51488902/62005643-e42bfa00-b153-11e9-96ef-5717a44e01f1.jpg)
## 💬 Questions and Help
Dear Team,

I have tried a lot to launch edge browser during our script execution with selenium C# but it is giving exception error and unable to launch edge browser with any url because I didn’t get ‘MicrosoftWebDriver.exe’ release file according to my OS build number(17763.404).When I user latest ‘MicrosoftWebDriver.exe’ release(17134), it is throwing exception error while executing edge driver instance line.
Kindly go through below my os detail  and help me to assist/guide me whether we have any alternative solution for launching edit browser with url .

OS detail :- 
   

  
Code :- 
                EdgeOptions options = new EdgeOptions();
            this.Driver = new EdgeDriver("C:\Drivers\MicrosoftWebDriver.exe"
, options);
                this.Driver.Manage().Window.Maximize();

             //   options.PageLoadStrategy = EdgePageLoadStrategy.Eager;
                //this.Driver = new EdgeDriver();
                //  this.Driver = new EdgeDriver(ConfigurationManager.AppSettings["EdgeDriverPath"]);
Error :-

**Comment by jimevans** [comment]
You’re still pointing the driver service instance to the old (17134) release of `MicrosoftWebDriver.exe`. Unless you’ve explicitly copied the 17763 version to your `C:\Drivers` folder from where it’s installed by `dism`, that won’t work. In any case, this is not an issue with the Selenium .NET bindings, and would be better asked on the [user mailing list](https://groups.google.com/forum/?pli=1#!forum/selenium-users) or the project IRC/Slack channel.
