### ISSUE TITLE
Insecure certificate in mozialla firefox

### ISSUE THREAD

**Issue by amitstudent2006** [SeleniumHQ/selenium#7438]
Dear Team ,

While navigating URL in mozialla firefox driver with Selenium C# webdriver , I am getting SSL /potential risk certificate before launch browser successfully.Could anyone assist me for ignoring this ssl certificate issue and launch browesr successfully?

Code :- 
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(ConfigurationManager.AppSettings["GekoDriverPath"], "geckodriver.exe");

                service.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";

                FirefoxProfile fp = new FirefoxProfile();
                fp.SetPreference("dom.webnotifications.enabled", false);
                fp.AcceptUntrustedCertificates = true;
                fp.AssumeUntrustedCertificateIssuer = false;
                FirefoxOptions options = new FirefoxOptions();
                options.Profile = fp;
                this.Driver = new FirefoxDriver(service, options, TimeSpan.FromSeconds(20));

                this.Driver.Manage().Window.Maximize(); 
os DETAIL :-
Windows 10

Selenium Version: selenium==3.14

Browser: Firefox

Browser Version: 68.0.1 (64-bit)

pROGRAMMING LANGUAGE :- sELENIUM c#
Expected Behavior - The SSL exceptions should be handled by Selenium Web driver. (We are using c#).
Actual Behavior - The web driver stops at SSL certificate error page
![selenium firefox certificate error](https://user-images.githubusercontent.com/51488902/62005879-37ec1280-b157-11e9-8f1d-ecfcc926eba8.jpg)
![selenium firefox certificate error](https://user-images.githubusercontent.com/51488902/62005890-54884a80-b157-11e9-8040-e9d884c4d65e.jpg)
![selenium firefox certificate error1](https://user-images.githubusercontent.com/51488902/62005891-5520e100-b157-11e9-834e-4360732c5f62.JPG)

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
