### ISSUE TITLE
Moving automation tests from windows to Linux server

### ISSUE THREAD

**Issue by hamzash9500** [SeleniumHQ/selenium#7439]
I have some tests, I am using

chrome
Selenium
Maven

I run them on windows and all thing are going fine with a successful run, I noticed that browser on windows is explicitly open and see the tests directly on the browser.

Then I need to move this to run it on UBUNTU server.

My questions:
what are the main points we have to consider while moving our test from windows client environment to Linux server?

What are changes in code have to consider to run tests on the server? Or the same code should work fine on both environments?

**Comment by mmerrell** [comment]
This is a question regarding best practices and project-specific logistics. Please contact the #selenium channel on IRC or another Selenium or Test Automation forum. This issue list is for defects or issues where Selenium functionality is in question or believed to be broken.
