### ISSUE TITLE
IEDriver: Some elements require double-click instead of single-click

### ISSUE THREAD

**Issue by littlemju** [SeleniumHQ/selenium#744]
While working on running our tests on IE driver, I've encountered strange behaviour on part of the latter. 

Site: http://pressreader.com
Steps to reproduce:
1. Open website with IE driver
2. Click on "Sign In" link in the top right corner, create a new user.
3. After you are logged in, try to click on your username in the top right corner.

After a single click there should open a popup menu, but in case of IE driver it actually requires two clicks. Same behaviour is noted with popup menu items and all the items on the top bar (menu, < arrow, pressreader logo).

I've tried turning off native events and turning on requireWindowFocus, but it does not help.
Just to be sure, it works in FF/Chrome driver and FF/Chrome/IE browsers.

IEDriver v.2.46.0.0

**Comment by jimevans** [comment]
When I execute the following code, everything seems to work perfectly.

    IWebDriver driver = new InternetExplorerDriver();

    driver.Url = "http://www.pressreader.com";
    System.Threading.Thread.Sleep(3000);

    driver.FindElement(By.CssSelector(".toolbar-button-signin")).Click();
    System.Threading.Thread.Sleep(3000);
     driver.FindElement(By.CssSelector("#SignInEmailAddress")).SendKeys("seattlewonderboy@hotmail.com");
    driver.FindElement(By.CssSelector("input[type='password']")).SendKeys("JoeCool0");
    driver.FindElement(By.CssSelector("button[type='submit']")).Submit();
    System.Threading.Thread.Sleep(5000);

    driver.FindElement(By.CssSelector("a.toolbar-button-signin")).Click();
    System.Threading.Thread.Sleep(2000);

    driver.FindElement(By.XPath("//a[contains(., 'Sign Out')]")).Click();
    Console.ReadLine();
    driver.Quit();

**Comment by littlemju** [comment]
Update: the issue is cause by clicking on the left menu button.
You can reproduce it by using this code instead:

            IWebDriver driver = new InternetExplorerDriver();

            driver.Url = "http://www.pressreader.com";
            System.Threading.Thread.Sleep(3000);

            driver.FindElement(By.CssSelector(".toolbar-button-signin")).Click();
            System.Threading.Thread.Sleep(3000);
            driver.FindElement(By.CssSelector("#SignInEmailAddress")).SendKeys("seattlewonderboy@hotmail.com");
            driver.FindElement(By.CssSelector("input[type='password']")).SendKeys("JoeCool0");
            driver.FindElement(By.CssSelector("button[type='submit']")).Submit();
            System.Threading.Thread.Sleep(5000);
            
            driver.FindElement(By.ClassName("toolbar-button-appmenu")).Click();
            System.Threading.Thread.Sleep(2000);

            driver.FindElement(By.XPath("//a[contains(@data-bind, 'accountShow')]")).Click();
            System.Threading.Thread.Sleep(10000);

            Console.ReadLine();
            driver.Quit();

**Comment by jimevans** [comment]
Working with this particular issue, it's an artifact of this particular page. The issue can be resolved by using the Actions class for the element in question.
