### ISSUE TITLE
Unable to load webpage when a link on webpage results CORS error

### ISSUE THREAD

**Issue by pradeepnyk** [SeleniumHQ/selenium#7440]
## 🐛 Bug Report

Unable to load webpage when a link on webpage results CORS error [site has been blocked on the requested resource]

## To Reproduce

Detailed steps to reproduce the behavior:
Navigate to saiglobal.com and open Infostore section from the login dropdown value

## Expected behavior

I am expecting it should navigate to the clicked site from home page. This is working fine when navigated manually

## Test script or set of commands reproducing this issue

driver.get("https://www.saiglobal.com/");
WebElement el1 = driver.findElement(By.xpath("//div[@class='desktop-login']"));
WebElement el2 = driver.findElement(By.xpath("//div[@class='desktop-login']/ul/li[1]"));
Actions action = new Actions(driver);
action.moveToElement(el1).pause(1000).perform();
action.moveToElement(el2).click().perform();

## Environment

OS:  Mac OS 10.14.6
Browser:  Chrome, Firefox
Browser version:  Chrome 75, Firefox 67.0.4
Browser Driver version:  Gecko 0.24, Chrome 75
Language Bindings version:  3.141.59
Selenium Grid version (if applicable):

**Comment by mmerrell** [comment]
As discussed in the #selenium channel, this turned out to be an issue with bot detection in the production server, rather than Selenium. It was recommended that @pradeepnyk look for a cookie/whitelisting alternative.

This issue can be closed.
