### ISSUE TITLE
Black Screenshot with selenium-server-standalone-3.141.59.jar and IEDriverServer.exe 3.14.0

### ISSUE THREAD

**Issue by AntonStefanovLefterov** [SeleniumHQ/selenium#7445]
Hi,

Since I updated to selenium-server-standalone-3.141.59.jar and IEDriverServer.exe 3.14.0 I receive black screenshot.

Capabilities:
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setBrowserName(BrowserType.IE);
capabilities.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);
capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
capabilities.setCapability(CapabilityType.SUPPORTS_ALERTS, true);
capabilities.setCapability(CapabilityType.HAS_NATIVE_EVENTS, false);
capabilities.setCapability(InternetExplorerDriver.UNEXPECTED_ALERT_BEHAVIOR, UnexpectedAlertBehaviour.IGNORE);               capabilities.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, false);
capabilities.setCapability(InternetExplorerDriver.ENABLE_ELEMENT_CACHE_CLEANUP, false);
capabilities.setCapability(InternetExplorerDriver.REQUIRE_WINDOW_FOCUS, false);
InternetExplorerOptions internetExplorerOptions = new InternetExplorerOptions();
internetExplorerOptions.merge(capabilities);
internetExplorerOptions.setPageLoadStrategy(PageLoadStrategy.NORMAL);
driver = new RemoteWebDriver(getHostUrl(), internetExplorerOptions);

Screenshot code:
File source = driver.getScreenshotAs(OutputType.FILE);

Result:
Screenshot is black. Works OK with Firefox and Chrome.

Can you please help me?
Regards.

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
