### ISSUE TITLE
while invoking driver.quit(), IE browser is not properly closed as what will happen with other browser

### ISSUE THREAD

**Issue by mjf19891007** [SeleniumHQ/selenium#745]
My development environment is win 7 and the version of IE browser is ie11, below is the source i tried to run but failed to close the browser. when i invoke driver.quit(), the browser didn't close 

 @Test
    public void IETest() throws Exception{
        System.setProperty("webdriver.ie.driver"
                ,"C:\\Users\\ma.shunhou\\AppData\\Local\\Mozilla Firefox\\IEDriverServer.exe");
        DesiredCapabilities capability=DesiredCapabilities.internetExplorer();
        capability.setCapability(
                     InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        WebDriver driver = new InternetExplorerDriver(capability);

        driver.get("http://www.google.com");
        Runtime.getRuntime().exec("taskkill /F /IM iexplorer.exe");

       driver.quit();

    }

**Comment by mjf19891007** [comment]
here is the information that the console printed :
Started InternetExplorerDriver server (64-bit)
2.46.0.0
Listening on port 20878
情報: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@6b26e945 [水 7 08 12:25:28 JST 2015]

**Comment by lukeis** [comment]
huh? you are issuing a command to kill the browser and then complain that driver.quit() doesn't work properly? and on top of that you are using INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS

final bit, that log message is just a warning message, that's been addressed 7a5e890ac2d37c76ac972ee22cfbc8aa89f83742 (pending new release)

**Comment by mjf19891007** [comment]
oh,m sorry, m just new to selenium, and using INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS is the suggestion i found from other's blog~
Without using INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, the browser can just be shutdown properly
Thank you very munch
