### ISSUE TITLE
set_page_load_timeout fails for value of more than about 10minutes (600sec)

### ISSUE THREAD

**Issue by DanielGuir** [SeleniumHQ/selenium#7450]
## Environment

OS: windows7
Browser: chrome
Browser version: 75.0.3770.142
Browser Driver version: ChromeDriver 75.0.3770.140
Language Bindings version: python 3.7
Selenium Grid version (if applicable): 3.141.0

Chromedriver set_page_load_timeout works for timeout value less than about 10min, but the script will timeout after about 10 minutes even if the timeout value is set to -1 or 1800, for example.

The issue occurs while trying to perform automatic download on a webpage which, after a button on the webpage is clicked, calls a javascript function and loads for about an hour before a download file is prompted and auto-downloaded (using chrome).

Here's the code I used.

driver.set_page_load_timeout(72000)
driver.set_script_timeout(72000)
run = driver.find_element_by_id('iisform:_idJsp131')
driver.execute_script("arguments[0].click()", run)

I expected the driver to timeout after 72000 seconds yet only after 10 minutes the driver times out.

Here's the error message.
 File "C:/Users/liheng_zhao/Desktop/T3 File Downloader/T3_File_Downloader.py", line 413, in dl_iwf_events
    driver.execute_script("arguments[0].click()", run)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=75.0.3770.142)

Unfortunatly since the website is a local corporate database, I currently have no idea on how to reproduce the error. Will surely update if found a way to achieve that.

**Comment by cgoldberg** [comment]
Your error shows timeout during `execute_script()`.... 

but `set_page_load_timeout()` is for page loads, and `set_script_timeout()` is for async scripts, so neither should affect your call to `execute_script()`.

**Comment by DanielGuir** [comment]
Thanks for the reply... Actually that script in the code was equivalent to run.click(), but if I use that syntax the error still occurs. Yet that button's onclick event does contain a javascript function call though, so I wonder if the error lies in that function call. Is there a way to set timeout value for that?

Moreover, the set_page_load_timeout() does affect the call, as setting the value to 2 caused the page to time out immediately (in 2 secs).

**Comment by mmerrell** [comment]
This needs the C-python label

**Comment by lmtierney** [comment]
Please raise an issue with the Chrome/Chromedriver team. Selenium is sending the correct information to chromedriver, and the timeout is coming from chromedriver.

```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> from selenium.webdriver import Chrome
>>> d = Chrome()
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:51130/session {"capabilities": {"alwaysMatch": {"goog:chromeOptions": {"args": [], "extensions": []}, "browserName": "chrome", "platformName": "any"}, "firstMatch": [{}]}, "desiredCapabilities": {"goog:chromeOptions": {"args": [], "extensions": []}, "platform": "ANY", "browserName": "chrome", "version": ""}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:51130

DevTools listening on ws://127.0.0.1:51136/devtools/browser/8f3a45e1-5994-483c-a18d-8faeb6a41b0f
DEBUG:urllib3.connectionpool:http://127.0.0.1:51130 "POST /session HTTP/1.1" 200 681
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
>>> d.set_page_load_timeout(72000)
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:51130/session/9b7e128cc1985d14c1b573d510a24c0f/timeouts {"pageLoad": 72000000}
DEBUG:urllib3.connectionpool:http://127.0.0.1:51130 "POST /session/9b7e128cc1985d14c1b573d510a24c0f/timeouts HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
>>> d.quit()
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://127.0.0.1:51130/session/9b7e128cc1985d14c1b573d510a24c0f {}
DEBUG:urllib3.connectionpool:http://127.0.0.1:51130 "DELETE /session/9b7e128cc1985d14c1b573d510a24c0f HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```
