### ISSUE TITLE
proxy authentication with Selenium browser none-headless and headless

### ISSUE THREAD

**Issue by viseth** [SeleniumHQ/selenium#7453]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

Hi,

I've seen many thread around proxy authentication with Selenium but none of them provide a simple and straight forward answer that will work for **both none-headless and headless** mode of the browser.
**This is really a showstopper for implementing Selenium for some customer.** 
Is there someone that has a working example that he could share with the community.
Will Selenium 4.x handle nicely this feature ?

Thanks a lot for your help, 
Regards,

Viseth

**Comment by cgoldberg** [comment]
For questions or help please see:

SeleniumHQ IRC channel
SeleniumHQ Slack channel
The Selenium Users google group
