### ISSUE TITLE
Actions.MoveToElement() using offset doesn't work in Chrome v76

### ISSUE THREAD

**Issue by mahesh1632** [SeleniumHQ/selenium#7455]
Hi,
I am using moveToElement command using offset. 
But it drops element somewhere else.

The Selenium test case involves drag and drop action at xy location. 
But element is getting dropped at wrong location

Environment:
ChromeDriver Version -  76.0.3809.68
Chrome Browser Version - 76.0.3809.87
Selenium Jar Version - selenium-server-standalone-3.141.59

Sample Code

Sample Code Snippet 

 WebElement sourceElement = mySourceElement;
Actions builder = new Actions(driver);
Action dragAndDrop = builder.clickAndHold(sourceElement).build();
dragAndDrop.perform();
driver.switchTo().frame(iFrame);
WebElement targetElement = myTargetElement;
Thread.sleep(1000);
dragAndDrop = builder.moveToElement(targetElement).release().build();
  dragAndDrop.perform();

**Comment by lmtierney** [comment]
Chrome is now using w3c compliant actions, which means the x/y offset is based off of the center point of the element and not the 0, 0 location. Update your offsets accordingly.

See https://www.w3.org/TR/webdriver1/#pointer-actions

**Comment by Harsha509** [comment]
Thanks for the info @lmtierney
