### ISSUE TITLE
C# : Unable to switch to window in remotewebdriver using windowhandle : OpenQA.Selenium.WebDriverException: missing field `handle` at line 3 column 1

### ISSUE THREAD

**Issue by saiparth** [SeleniumHQ/selenium#7456]
## 🐛 Bug Report

While trying to switch to window using windowhandles, I am seing exception as 

OpenQA.Selenium.WebDriverException: missing field `handle` at line 3 column 1
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'SYS-LAPTOP-299', ip: 'aaaaaa', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_172'
Driver info: driver.version: unknown
Workd well if i use chromedriver instead of remotewebdriver
Browser : chrome 76
Chromdriver 76
Selenium version 3.14.0

## To Reproduce

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Chrome;
namespace Tests
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var cap = new ChromeOptions();
            cap.AddArgument("disable-popup-blocking");
            var wd = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"),cap);
            wd.Url = "https://www.google.com/";
            var handles = wd.WindowHandles;
            foreach (var item in handles)
            {
                var title=wd.SwitchTo().Window(item);//getting exception when this line executes
            }
        }
        [TestMethod]
        public void TestMethod2()
        {
            var wd = new ChromeDriver(@"D:\libs");
            wd.Url = "https://www.google.com/";
            var handles = wd.WindowHandles;
            foreach (var item in handles)
            {
                var title = wd.SwitchTo().Window(item).Title;
            }
        }
    }
}

```
TestMethod1->fails with above exception
TestMethod2->passes

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 76
Browser Driver version:76
Language Bindings version: C# 3.11 
Selenium Grid version (if applicable): 3.14.0

**Comment by OlegZarevych** [comment]
I also find this problem. In my case code fails on the FindElements() method

**Comment by orifn1** [comment]
Looks like this problem is resolved, my code works
