### ISSUE TITLE
Chording with Actions doesn't work as intended.

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7458]
From `testChordControlCutAndPaste`, the following should work:

```java
new Actions(driver) .sendKeys(Keys.CONTROL + "a" + "x")
```

This doesn't work since we press and then release the control key. We should keep it down until we see `Keys.NULL`

**Comment by mmerrell** [comment]
It seems like the behavior should be the same for the following keys: SHIFT, CONTROL, ALT, META (including the Keys that point to those). I'm going to go on that assumption and get started. If there are more, let me know.

**Comment by mmerrell** [comment]
Note: I verified the above assumption with the spec: https://www.w3.org/TR/2018/REC-webdriver1-20180605/#element-send-keys

**Comment by mmerrell** [comment]
I pushed a branch to my fork (https://github.com/mmerrell/selenium/tree/issue-7458), but I'm not confident that it's the right approach, nor was I able to attach to the server to debug while testing it out. I'll need a little more guidance for that, but the main issues were a) figuring out where the decisions needed to happen, and b) introducing the concept of a "modifier" key in the Keys class.

The "modifier" concept seems to be a good idea, considering that those 4 keys are codified in the W3C standard. Let me know what you think.

**Comment by ice1080** [comment]
I'm seeing the same thing both on Windows with Control and on Mac with Command. In our case we are trying to paste something from the clipboard, and these keys seem to be ignored, so only the character "v" is sent to the element. I have also tried using keyDown and stringing together multiple sendKeys instead of just chord and nothing seems to work

**Comment by werru** [comment]
use chrome 74 as temporary decision

**Comment by JohnChen0** [comment]
Rather than using an old version of Chrome, I'd recommend the following workaround code instead:

```
   new Actions(driver)
       .keyDown(Keys.CONTROL)
       .sendKeys("a" + "x")
       .keyUp(Keys.CONTROL)
```

**Comment by werru** [comment]
My piece of code
```
        ChromeDriverService service = new ChromeDriverService.Builder().usingDriverExecutable(new File("/usr/lib/chromium-browser/chromedriver")).usingAnyFreePort().build();
        service.start();
        DesiredCapabilities capabilities = new DesiredCapabilities();
        WebDriver driver = new RemoteWebDriver(service.getUrl(), capabilities);
        driver.get("https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea");
        Thread.sleep(1000);
        WebElement element= driver.findElements(By.tagName("input")).get(3);
        element.sendKeys("send smth");
        Actions actions = new Actions(driver);
//        actions.sendKeys(Keys.SHIFT,Keys.RIGHT).perform();
//        actions.sendKeys(Keys.chord(Keys.SHIFT,Keys.RIGHT)).perform();
//        actions.sendKeys(Keys.chord(Keys.CONTROL, "a")).perform();
        actions.keyDown(Keys.CONTROL)
                .sendKeys("a")
                .keyUp(Keys.CONTROL);
        actions.sendKeys(Keys.chord(Keys.SHIFT,Keys.RIGHT)).perform();
```
Your suggested code doesn't help
