### ISSUE TITLE
Expertise Request - Networking (Referral Request) 

### ISSUE THREAD

**Issue by tlicari** [SeleniumHQ/selenium#746]
Where is the best place to search for folks that know Selenium? I am currently conducting an extremely strategic search for a Mobile Architect to fill an important role within our company. I would be very appreciative for any referrals you’d be willing share. If there is anything I can help you find please let me know. I am happy to help. 

Position Brief - http://bit.ly/VTMobileArchitect
Location Chicago, IL 

Thank you in advance for the help, 

Thomas F.X. Licari  | Director of Recruitment  | Vertical Trail, LLC  | Thomas(ATSIGN)VerticalTrail.com  | VerticalTrail.com

**Comment by lukeis** [comment]
this is not a job posting board.
