### ISSUE TITLE
MoveToElement no longer calculates offset from top-left corner

### ISSUE THREAD

**Issue by gajduk-mansystems** [SeleniumHQ/selenium#7461]
## 💥 Regression Report

In the past, selenium v3.8.1  would correctly calculate the offset from the top-left corner of an element. Since selenium v3.14 this is no longer the case and the offset is being calculated from the center of the web element. Furthermore, the element is no longer scrolled into view either.

From my research it seems like this is caused by change in the chrome and gecko drivers. In that case selenium should ideally keep the API consistent or at the very least update the documentation:

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html#moveToElement-org.openqa.selenium.WebElement-int-int-

Moves the mouse to an offset from the **top-left corner of the element**. The element is scrolled into view and its location is calculated using getBoundingClientRect.

**Comment by cgoldberg** [comment]
> at the very least update the documentation

yes, the docs need updating.  This behavior has changed since drivers are following the W3C spec.

**Comment by mmerrell** [comment]
Updated Javadoc in PR 7473 https://github.com/SeleniumHQ/selenium/pull/7473

**Comment by diemol** [comment]
PR #7473 merged via https://github.com/SeleniumHQ/selenium/commit/43963b8df7a04ee75c40425596c93ed63c6042c6a, docs will be updated in the next alpha release.
