### ISSUE TITLE
Deprecating old versions of Python 

### ISSUE THREAD

**Issue by Dude-X** [SeleniumHQ/selenium#7462]
## 🚀 Feature Proposal
Drop support for Python 3.3 and earlier.
Drop support for Python 2(?)

## Motivation
Python 3 has had a significant update since the release of Python 3.4. At the time the client library was updated to support Python 3, Python 3.4 was the latest version, which re-added support for `u''` unicode strings to make the Python 2 to 3 transition easier.
However, to support both Python 3 and Python 2, at the time, we had to remove all the unicode prefixes from strings, and use `from __future__ import unicode_literals`.
I propose we add back the unicode literal prefixes to all strings and remove the future import. This also allows us to clean up all the `.encode().decode()` calls that are in the code base.

On January 1st, 2020, the core developers of Python will end the continued development and fixes for Python 2.7. Python 2.7.18 will be the last release by the Python Software Foundation. At the time of this writing many library and application authors have dropped Python 2 support; such libraries like `pip`, `ipython`, `numpy` have already published distributions that no longer support Python 2.

Despite the popularity of Python 3, Python 2 has a large install base, and many companies are successfully running Python 2 applications without issue. It would not be helpful to simply drop Python 2 support for those institutions who rely on Selenium for their apps. So I propose we create a new folder or repository that is strictly for Python 2, but let the Selenium community update it, while the core developers focus on a pure Python 3 version of the Python bindings.

Once we split out Python 2 from Python 3, we can remove `u''` prefixes since they're no longer necessary, and make Python 3.5.2 the minimally required version. Then we can think about adding features like type annotations, using `pathlib`, and other general clean up.

**Comment by AutomatedTester** [comment]
How many cases do we have of this in the code base? If it is a handful do we really feel like it is a good use of our time to support two separate bits of code?

**Comment by Dude-X** [comment]
The idea is to separate Python 2 code into a separate repo and let the community maintain it. Only new stuff and fixes will go in the main repo while the maintainers can backport the new changes, which in most cases is pretty trivial.

**Comment by hugovk** [comment]
Python 3.4 is also EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

---

Here's the pip installs for selenium from PyPI for September 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  30.99% |   774,876 |
| 3.7      |  30.00% |   750,173 |
| 3.6      |  28.94% |   723,664 |
| 3.5      |   6.61% |   165,328 |
| 3.4      |   1.73% |    43,316 |
| null     |   1.68% |    41,964 |
| 3.8      |   0.04% |       969 |
| 2.6      |   0.01% |       277 |
| 3.3      |   0.00% |        23 |
| 3.9      |   0.00% |         2 |
| 3.2      |   0.00% |         1 |
| Total    |         | 2,500,593 |

Source: `pip install -U pypistats && pypistats python_minor selenium --last-month`

---

> At the time of this writing many library and application authors have dropped Python 2 support; such libraries like `pip`, `ipython`, `numpy` have already published distributions that no longer support Python 2.

Many Scientific Python projects, such as IPython, NumPy, Matplotlib, scikit-learn, Jupyter, yt, SciPy, and scikit-image, have adopted a community policy to support even fewer Python versions. For example, 3.6+ now and 3.7+ in June.

* https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by AutomatedTester** [comment]
Thanks for this. Due to people still using python 2.7 we can't just remove it and I am not sure about removing 2.7 until python officially drops 2.7. I know companies like Google and Apple are still supporting 2.7 in their CI.

**Comment by hugovk** [comment]
31% isn't that high, and other projects have also dropped it at around this level. 

For example:

* 39% NumPy
* 37% SciPy
* 31% pandas
* 22% pytest

But no rush, it's important to plan this properly :)

---

In any case, I recommend adding `python_requires` to setup.py now.

Then pip will install the most recent release for the Python version the user is running. That means there will always still be a release available for them to use, just it won't be receiving updates (like CPython 2.7 itself, soon).

For example, use this now:
```python
'python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
```

And when you drop 2.7:
```python
'python_requires='>=3.4',
```

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by AutomatedTester** [comment]
Happy to take a PR for that if you want to do it.

**Comment by codemrkay** [comment]
Hi, I'm new in this repo.
Due to Python 3.4 is now the highest version of Python, which no longer has official support (3.5 is still supported) and that builds with tests for Pull Requests on Travis are running (for version 3.x) on Python 3.6.7, I changed the requirements for Python: 3.4 is now disabled from acceptable versions.
Official statement from python.org (Python Release Schedule for version 3.4):
"Python 3.4 has now reached its end-of-life and has been retired. No more releases will be made."
@AutomatedTester could you please take a look on my first Pull Request in this project? #8085

**Comment by SalmonMode** [comment]
I agree with @hugovk's assessment. People using Python 2 would still be able to install Selenium 3 through `pip` and PyPI, and if something goes wrong there, they can always install specific releases from GitHub directly. I would recommend adding some instructions for how to do this in the docs somewhere first, though.

**Comment by hugovk** [comment]
For March 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  31.19% |   957,325 |
| 3.6      |  28.55% |   876,274 |
| 2.7      |  20.48% |   628,524 |
| 3.8      |   9.31% |   285,874 |
| 3.5      |   7.16% |   219,714 |
| null     |   2.25% |    69,101 |
| 3.4      |   1.03% |    31,750 |
| 3.9      |   0.01% |       442 |
| 2.6      |   0.01% |       217 |
| 3.3      |   0.00% |        25 |
| Total    |         | 3,069,246 |

Source: `pip install -U pypistats && pypistats python_minor selenium --last-month`

**Comment by Dude-X** [comment]
I think once 4.0.0 becomes "stable" we should probably drop Python 2 support from the main repo, in the next minor release by:
1. Remove all version checks for imports
2. Restore the use of u' string prefixes (so that Python 2 can work correctly in the fork) (mostly in the Keys.py)
3. Drop all `from __future__ import unicode_literals`
4. Fix the few `encode('utf-8').decode('utf-8')`  uses.
5. Any other Python 2 hacks I can't think of.

Point 2 should be done before 4.0 is a stable release, so that we can fork the code to a github repo that is only for python 2 code and let the community maintain fixes. 4.1 should be when we drop the ax on Python 2.

**Comment by Dude-X** [comment]
PR https://github.com/SeleniumHQ/selenium/pull/8290 is good enough for 4.0 final release where it still maintains Python 2 compatibility before we think about dropping Python 2 from main and splitting 4.0 into a python 2 only source.
Then we can use uriyo's PR to remove all PY2 stuff.

**Comment by AutomatedTester** [comment]
Closing this as we have moved to Py3.7  as a minimum due to needed `@async_contextmanager`
