### ISSUE TITLE
Py: Replace instance checking for PointerActions.move_to() to try / except AttributeError block

### ISSUE THREAD

**Issue by vhryhorchuk-amplify** [SeleniumHQ/selenium#7467]
## 🚀 Feature Proposal
I feel the explicit instance checking in `move_to()` method of `selenium/webdriver/common/actions/pointer_actions.py` breaks flexibility of python code and may be against "easier to ask for forgiveness than permission" coding style.
The disputed code is:
```
class PointerActions(Interaction):

def move_to(self, element, x=None, y=None):
        if not isinstance(element, (WebElement, EventFiringWebElement)):
            raise AttributeError("move_to requires a WebElement")
        if x is not None or y is not None:
            el_rect = element.rect
            left_offset = el_rect['width'] / 2
            top_offset = el_rect['height'] / 2
            left = -left_offset + (x or 0)
            top = -top_offset + (y or 0)
        else:
            left = 0
            top = 0
        self.source.create_pointer_move(origin=element, x=int(left), y=int(top))
        return self
```
This might be an issue in case (mine in particular) when we have wrapper around `WebElement`.
Suppose:
```
class WebElementWrapper:

    def __init__(self, webdriver, selector):
        self.webdriver = webdriver
        self.selector = selector
        self._element = None

    @property
    def web_element(self):
        if self._element is None:
            try:
                self._element = self.webdriver.find_element_by_selector(self.selector)
            except NoSuchElementException as exc:
                raise NoSuchElementException(f"Web Element with selector {self.selector} has not been found."
                                             f"\n{exc.msg}")
        return self._element

    def __getattr__(self, attr):
        try:
            orig_attr = self.web_element.__getattribute__(attr)
            if callable(orig_attr):
                def hooked(*args, **kwargs):
                    return orig_attr(*args, **kwargs)
                return hooked
            return orig_attr
        except AttributeError as exc:
            raise AttributeError(f"WebElement has no attribute {attr}.\n{exc}")
```
When I pass instance of WebLementWrapper to `ActionChains(driver).move_to_element(my_wrapped_webelement)` it works as intended as far, as it executes this part:
```
self._actions.append(lambda: self._driver.execute(
                                 Command.MOVE_TO, {'element': to_element.id}))

```
But with forced `w3c` compatibility it goes to:
```
        if self._driver.w3c:
            self.w3c_actions.pointer_action.move_to(to_element)
            self.w3c_actions.key_action.pause()
```
Where it fails on `isinstance()` checking, what has no sense, as Python is flexible enough to handle this inside try / except.

**Comment by Dude-X** [comment]
Related: #7127

So you have two solutions: modify your wrapper to make it a subclass of webelement (which works in most cases) or to monkeypatch that function to remove that isinstance check or make an ABC out of webelement and register your wrapper.

**Comment by Dude-X** [comment]
There is no harm in removing the check;
Generally, Python programs  should rely on duck typing, that is you assume the object you pass has the right method/attribute name and just work.
However, in larger programs, mistakes can be made easily, so having stricter rules on validating inputs is a good thing.
In your own personal projects you can remove it, but in larger projects you will want some extra help with type checks to quickly error out and prevent subtle bugs or bad error messages.

**Comment by vhryhorchuk-amplify** [comment]
Okay, I see you point.

**Comment by vhryhorchuk-amplify** [comment]
Is it possible to fix, when Selenium will drop Python 2, so we can use `mypy` and optional type checking?

**Comment by vhryhorchuk-amplify** [comment]
@Dude-X I found another bug with this implicit type checking.
The Selenium fails when element is of type `EventFiringWebElement` from `selenium.webdriver.support.event_firing_webdriver import EventFiringWebElement`, as it doesn't inherits from WebElement.

**Comment by Dude-X** [comment]
Version 4 of the Python bindings (hopefully) will start using abstract base classes so that you can register WebElement wrappers as a WebElement type.

One can argue that Python code should be ducked type (formally called structural typing), but this would mean that we would have to define a standard of what is a WebElement. You can ask is a WebElement a type that has attributes X and methods Y, but which ones do you really care about? Do you want to even map these on to your custom type?  I think it's a better solution to allow registration of odd types so that when you really want to look at an object and say that it conforms to a type, it should pass the test without any other extra work.

With ABCs, you can register your type with WebElement.
```
from selenium.webdriver.remote import WebElement

class MyWrapper:
   ...

WebElement.register(MyWrapper)
```
This will solve problems where `isinstance(WebElement)` is used in unexpected places and won't break your custom type.
