### ISSUE TITLE
Launch cannot control browser access to web page, may appear, not every time

### ISSUE THREAD

**Issue by 2720851545** [SeleniumHQ/selenium#7470]
OS :	Microsoft Windows Server 2016 Datacenter
language: Python 3.7.3 
browser: chrome
ChromeDriver:76.0.3809.68 
selenium: 3.141.0

Launching chrome browser successfully, selenium controls chrome access to the page without responding, manually entering the page to access no problem

**Comment by 2720851545** [comment]
![image](https://user-images.githubusercontent.com/28623614/62515535-2bea0a00-b855-11e9-8f4d-65d20dc23e5b.png)

**Comment by 2720851545** [comment]
This problem is random, never on my Windows 10 system.

**Comment by 2720851545** [comment]
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:55854/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "goog:chromeOptions": {"prefs": {"profile.default_content_setting_values": {"notifications": 2}}, "extensions": [], "args": ["--disable-gpu", "--incognito"]}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "goog:chromeOptions": {"prefs": {"profile.default_content_setting_values": {"notifications": 2}}, "extensions": [], "args": ["--disable-gpu", "--incognito"]}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1:55854
DEBUG:urllib3.connectionpool:http://127.0.0.1:55854 "POST /session HTTP/1.1" 500 997
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by diemol** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium/issues/new/choose) and we'll make sure to look at it.
