### ISSUE TITLE
Selenium 3.5.3 Chrome options issue with chrome driver 76

### ISSUE THREAD

**Issue by kumarkrish85** [SeleniumHQ/selenium#7476]
## 🐛 Bug Report

I am using selenium 3.5.3 version and the chrome driver version is 76.0.3809. I faced the same issue which is reported in [https://github.com/SeleniumHQ/selenium/issues/7469](url). 
To workaround the issue i have tried the below snippet of code

`ChromeOptions options=new ChromeOptions(); 
options.addArguments("--start-maximized");
DesiredCapabilities chrome = new DesiredCapabilities.Chrome();
chrome.setCapability(ChromeOptions.CAPABILITY,options);
driver = new ChromeDrivers(chrome);
driver.get("https://Bing.com");
driver.quit();
`

The above code is running fine, but chrome options which I set is not working. Many of the users in my tool are using selenium 3.5.3 , can't immediately upgrade it to selenium 3.141.59. Can you please suggest me any workaround (or) fix to set the chrome options.

## To Reproduce

Detailed steps to reproduce the behavior:

![code](https://user-images.githubusercontent.com/27405093/62615014-1e528400-b92a-11e9-913a-a83a7d240d14.png)

**output**

![repro](https://user-images.githubusercontent.com/27405093/62615182-725d6880-b92a-11e9-88f8-e830573ed9f3.png)

## Expected behavior

The Chrome options should work find in latest chrome driver

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome 
Browser version: 76
Browser Driver version: 76.0.3809
Language Bindings version: Selenium 3.5.3 
Selenium Grid version (if applicable): NA  

Thanks,
Krishna

**Comment by mmerrell** [comment]
A few notes here: 
- DesiredCapabilities.chrome() is a static method, so the "new" there won't even compile
- This is also no longer the preferred way to create a ChromeDriver (ChromeOptions is the preferred method)
- In fact, the entire DesiredCapabilities object here is redundant--you can simply say 
`WebDriver driver = new ChromeDriver(options)`, skipping the DesiredCapabilities object
- This code, fixed, does not maximize the window for me on Selenium version v3.5.3 or on v3.141.59, so upgrading to the newer version wouldn't help you
- The window also didn't maximize using Selenium v2.53.1
- According to [chromedriver docs](http://chromedriver.chromium.org/capabilities), they skip the dashes before the option, so you'd say `options.addArguments("start-maximized"). This also did not work for me on chromedriver v76.0.3809

This is either a problem with ChromeDriver, or with their documentation. It's not a Selenium issue as far as I can tell.

**Comment by lmtierney** [comment]
This is most likely because chrome now expects `goog:chromeOptions` instead of `chromeOptions` which is what `3.5.3` `ChromeOptions.CAPABILITY gives you. You could try using that instead, but chrome/chromedriver `75+` uses w3c protocol which I'm not sure `3.5.3` will work with.

**Comment by lmtierney** [comment]
Your best bet is to downgrade your chrome to `74` until you can upgrade your selenium version

**Comment by iPet** [comment]
I van confirm the goog: prefix is the issue.
This works for me on chrome/chromedriver 76

```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
   “goog:chromeOptions”: { args: [“headless”, “disable-gpu”, “no-sandbox”], mobileEmulation: mobile_emulation },
  )
Capybara::Selenium::Driver.new(app, browser: :chrome, desired_capabilities: capabilities, clear_local_storage: true, clear_session_storage: true)
```

**Comment by kumarkrish85** [comment]
@iPet In Java, i have to do something like this below ? can you please confirm

`chrome.setCapability("goog:chromeOptions",options);`

**Comment by iPet** [comment]
@kumarkrish85 Yeah, that should do it.

**Comment by Harsha509** [comment]
Hi @lmtierney

can i have any reference link for this change to look into it. I've even searched for W3C docs and chromium docs. i didn't find ref to this change.

Thanks !

**Comment by diemol** [comment]
https://www.w3.org/TR/webdriver1/#dfn-extension-capability

**Comment by kumarkrish85** [comment]
Hi @iPet ,

Thanks a lot. your solution worked.

**Comment by lmtierney** [comment]
@Harsha509 the original change to allow both `chromeOptions` and `goog:chromeOptions` was in `2.31` https://chromedriver.storage.googleapis.com/2.31/notes.txt to ease the transition to w3c. Now that w3c is default in chromedriver 75+, it expects `goog:chromeOptions` as `chromeOptions` is not w3c compliant (see @diemol 's link above).

`chromeOptions` is still recognized when the driver is not in w3c mode, but to do that you'd have to set it explicitly or use a chromedriver less than 75

**Comment by NileshkumarShegokar** [comment]
great content folks!
I was really pissed off as the changes in chrome driver 76 stop adding extension and my whole framework goes down. 
thanks for your in details solution writing.

**Comment by beccagsc** [comment]
Thank you @lmtierney! When I upgraded from chrome/driver 74 to 76, my tests no longer ran headless. Prefixing "chromeOptions" with "goog" got the driver registration to read the headless option again.
