### ISSUE TITLE
Selenium grid missing configuration for custom capabilities mutators

### ISSUE THREAD

**Issue by JonathanHallKJR** [SeleniumHQ/selenium#7478]
## 🚀 Feature Proposal

Grid already allows configuration of a Custom Matcher in the hub's config json but if that custom matcher wants to make use of extension capabilities as part of the processing (allowed by w3c specification) but there is no configuration also allow a Capabilities Mutator.

## Motivation

Selenium Grid appears to passes intermediary extension capabilities through to the nodes which is a violation of the w3c specification for [New Session](https://w3c.github.io/webdriver/#dfn-new-sessions)
> If the remote end is an intermediary node, it may use the result of the capabilities processing algorithm to route the new session request to the appropriate endpoint node.
> An intermediary node is free to define extension capabilities to assist in this process, however, these specific capabilities *must not be forwarded to the endpoint node.*

## Suggested fix 
Selenium Grid does appears have mechanism to change capabilities with Capabilities Mutator, but it isn't configurable like the Capabilities Matcher. 

I think it would be possible to use the existing CapabilitiesMutator logic: 
* `org.openqa.selenium.remote.server.NewSessionPipeline#addCapabilitiesMutator`
* `org.openqa.selenium.remote.server.NewSessionPipeline#createNewSession`

Suggest adding new config option for `customMutator` like existing `org.openqa.grid.internal.utils.configuration.GridHubConfiguration#capabilityMatcher` 

Then when creating the NewSessionPipeline `org.openqa.selenium.remote.server.SeleniumServer#createPipeline` if the configuration is instance of GridHubConfiguration then register the customerMutator

**Comment by diemol** [comment]
@JonathanHallKJR can you provide an example with code of what you mean?

**Comment by JonathanHallKJR** [comment]
@diemol  My suggested fix was based on browsing the code so I haven't attempted to implement it and I may have missed something tracing the program flow.

Essentially the proposal is to add to config for the hub a `capabilityMutator` that can work in conjunction with the `capabilityMatcher` to remove capabilities before they're forwarded to the endpoint node.

This is required by the w3c web driver specification if the intermediary node (grid hub)'s capabilityMatcher relies on custom extension capabilities to route the request.

The mock up below hasn't been compiled but hopefully conveys enough of the intent.

## Example
Start the hub `java -jar selenium-server-standalone-3.141.59.jar -role hub -hubConfig hubConfig.json` with a `capabilityMutator` configured.
```javascript
{
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets": [],
  "withoutServlets": [],
  "custom": {},
  "capabilityMatcher": "hudson.plugins.selenium.JenkinsCapabilityMatcher",
  "capabilityMutator": "package.for.my.example.MyCapabilityFilter", // added 
  "throwOnCapabilityNotPresent": true,
  "cleanUpCycle": 5000,
  "role": "hub",
  "debug": false,
  "browserTimeout": 0,
  "timeout": 1800
}
```
> *:information_source: Investigating an issue with [JenkinsCapabilityMatcher](https://github.com/jenkinsci/selenium-plugin/blob/master/src/main/java/hudson/plugins/selenium/JenkinsCapabilityMatcher.java) forwarding the custom `jenkins:label` extension capability to IEDriverServer prompted this feature request*

The mutator class would then be given access to change the capabilities just before their forwarded to hubs during the [NewSessionPipeline#createNewSession](https://github.com/SeleniumHQ/selenium/blob/selenium-4.0.0-alpha-2/java/server/src/org/openqa/selenium/remote/server/NewSessionPipeline.java#L60)

```java
package package.for.my.example;

import java.util.*;
import java.util.function.Function;
import org.openqa.selenium.Capabilities;
import org.openqa.selenium.ImmutableCapabilities;

public class MyCapabilityFilter implements Function<Capabilities, Capabilities> {

    // todo: Could also add constructor like org.openqa.grid.selenium.node.ChromeMutator that would make this 
	// 		 configurable through the hubConfig.json
	//       for the example the filter is hard coded.
    static final String EXTENSION_CAPABILITY_PREFIX = "jenkins:";

    @Override
    public Capabilities apply(Capabilities capabilities) {
        Map<String, Object> toReturn = new HashMap<>(capabilities.asMap());
        List<String> toRemove = new LinkedList<>();

        // find all capabilities starting with filtered prefix.
        for (String k : toReturn.keySet()) {
            if (k.startsWith(EXTENSION_CAPABILITY_PREFIX)) {
                toRemove.add(k);
            }
        }

        // Remove all matches
        for (String r : toRemove) {
            toReturn.remove(r);
        }

        return new ImmutableCapabilities(toReturn);
    }

}
```

**Comment by diemol** [comment]
Revisiting this since the code for Grid 3 is not in `trunk` anymore and we are soon releasing formally the Grid.

A `SlotMatcher` is the one in charge of matching requests with Slots and it is possible to configure it via https://www.selenium.dev/documentation/grid/configuring_components/cli_options/#distributor (`--slot-matcher`). 

There is a `SessionCapabilitiesMutator` now that enhances capabilities when they drivers are customised, for example: https://www.selenium.dev/documentation/grid/configuring_components/toml_options/#configuring-and-customising-drivers 

Not sure if all this would already cover this use case. @JonathanHallKJR, what do you think?

**Comment by diemol** [comment]
Closing as we did not get more feedback.
