### ISSUE TITLE
IEDriverServer should ignore 'unknown extension capability'.

### ISSUE THREAD

**Issue by JonathanHallKJR** [SeleniumHQ/selenium#7479]
## 🐛 Bug Report
IEDriverServer should ignore 'unknown extension capability' and not reject them if provided.
This behaviour would match ChromeDriver and would still be complaint with w3c webdriver specifications.

## To Reproduce
I'm using the [Jenkins Selenium Plugin](https://wiki.jenkins.io/display/JENKINS/Selenium+Plugin) that creates a Selenium Grid with custom capabilities 
implemented in their own [JenkinsCapabilityMatcher](https://github.com/jenkinsci/selenium-plugin/blob/master/src/main/java/hudson/plugins/selenium/JenkinsCapabilityMatcher.java)
with `jenkins:label` and `jenkins:nodeName` capabilities to direct a newSession request to a specific node.

Attached [replication code](https://github.com/SeleniumHQ/selenium/files/3479608/SeleniumBug.java.txt) triggers the issue with a local IEDriverServer.

### Expected/Actual Behavior
When I sent a remote web driver request to the grid with desired capabilities `jenkins:label` it routes that request to the correct selenium grid node however the IEDriverServer on that node fails to start IE.
* Expect: IE Driver to ignore unknown/unhandled capabilities. (same behaviour as ChromeDriver)
* Actual: Sending a desired extension capability causes an error:
  ```
  Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
  Unable to match capability set 0: jenkins:label is an unknown extension capability for IE
  ```

### Environment
OS: Windows 8.1
Selenium Version: selenium-java latest (3.141.59)
IEDriverServer Version(s) - Win32 3.14.0 (and prerelease 3.141.59.3)
Browser: Internet Explorer
Browser Version: 11.0.9600.19356

## Analysis
Trying different values for the capablities 
* :heavy_check_mark: IEDriverServer doesn't fail with unknown capabilities (eg 'foo') 
* :heavy_check_mark: IEDriverServer doesn't fail with test extension capabilities (eg 'test:foo') 
  *this appears to be a special case in the code, but indicates that the unrecognised extension capabilities won't cause and issue*
* :x: IEDriverServer does fail with unknown extension capabilities (eg 'foo:bar')
* :information_source: Same code doesn't fail with other drivers (eg Chrome) using both unknown capabilities and unknown extension capabilities.

As far as I can tell the w3c specification should allow unmatched extension capabilities to succeed.

#### Matching capabilities 
w3c specification for [matching](https://w3c.github.io/webdriver/#dfn-matching-capabilities) includes wording to suggest endpoint node can Optionally include extension capabilities,
and if the extension capability does not match it is not a failure.

> When matching capabilities with JSON Object argument capabilities, an endpoint node must take the following steps:
> ...
> 2. Optionally add extension capabilities as entries to matched capabilities. The values of these may be elided, and *there is no requirement that all extension capabilities be added.*
> ...
> 3. For each name and value corresponding to capability’s own properties:
>   1. Run the substeps of the first matching name:
>      ...
>      Otherwise If name is the key of an extension capability, let value be the result of trying implementation-specific steps to match on name with value. *If the match is not successful, return success with data null.*

#### Validate Capabilities 
Note: The [NewSessionCommandHandler::ValidateCapabilities](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/cpp/iedriver/CommandHandlers/NewSessionCommandHandler.cpp#L932) already correctly allows other extension capability to pass through.

See specification for [validating capiblities](https://w3c.github.io/webdriver/#dfn-validate-capabilities)
> name is the key of an extension capability
> Let deserialized be the result of trying to deserialize value in an implementation-specific way.

```cpp
if (capability_name.find(":") != std::string::npos) {
  LOG(DEBUG) << "Found extension capability named " << capability_name << "."
			 << " Nothing further to validate.";
  continue;
}
```

## Suggested fix

Suggested fix would be removing this block from [NewSessionCommandHandler::MatchCapabilities](https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/cpp/iedriver/CommandHandlers/NewSessionCommandHandler.cpp#L564) 
is all that is needed.

Since the rest of the functionality still works when the 'test:' extension capability is used.

```cpp
if (capability_name.find(":") != std::string::npos &&
   (capability_name != IE_DRIVER_EXTENSIONS_CAPABILITY &&
   capability_name.find("test:") == std::string::npos)) {
	*error_message = capability_name + " is an unknown extension capability for IE";
	return false;
}
```

### Related issues
The root cause appears to arise because the Jenkins Selenium Grid Plugin passes intermediary capabilities through to the nodes; which is a violation of the w3c specification for [New Session](https://w3c.github.io/webdriver/#dfn-new-sessions)
> If the remote end is an intermediary node, it may use the result of the capabilities processing algorithm to route the new session request to the appropriate endpoint node.
> An intermediary node is free to define extension capabilities to assist in this process, however, these specific capabilities *must not be forwarded to the endpoint node.*

While Selenium Grid does appear have mechanism to remove extension capabilities it isn't exposed.
* `org.openqa.selenium.remote.server.NewSessionPipeline#addCapabilitiesMutator` - which appears to allow removal/changes to capabilities by the intermediary node.
* `org.openqa.grid.internal.utils.configuration.GridHubConfiguration` - doesn't have ability to provide a Capability Mutator. 

I've also raised the following issues for those projects, but fixing it in IEDriverServer would be fastest fix.
* Feature request for selenium grid [missing configuration for custom capabilities mutators #7478](https://github.com/SeleniumHQ/selenium/issues/7478)
* Bug against Jenkins Selenium-Grid Plugin for ['jekins:label' not w3c compatible when passed to endpoint node. #143](https://github.com/jenkinsci/selenium-plugin/issues/143)

**Comment by ghost** [comment]
We have also encountered this issue in our typescript Webdriverio v7.9.1 project
We use _cucumber 7.3.1_ and _multiple-cucumber-html-reporter 1.18.0_ for test reporting

**Challenge:**
For the IE11 browser, we cannot use **_cjson:metadata_** within the wdio-cucumberjs-json-reporter. When included in the config, it causes an error and doesn't allow to run our tests.

The Chrome configuration which works is:
In our wdio.conf.ts file
```
exports.config = {
  ...
  capabilities: [{
    maxInstances: 1,
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'cjson:metadata': {
      device: configUtils.getCurrentFranchiseName(),
      platform: {name: os.type, version: os.version()}
    }
  }],
  ...
};
```

Our IE11 configuration which doesn’t work is:
```
exports.config = {
  ...
  capabilities: [{
    maxInstances: 1,
    browserName: 'internet explorer',
    'se:ieOptions': {
      ignoreZoomSetting: true,
      nativeEvents: false,
      'ie.ensureCleanSession': true
    },
    'cjson:metadata': {
      device: configUtils.getCurrentFranchiseName(),
      platform: {name: os.type, version: os.version()}
    },
    timeouts: {}
  }],
  ...
};
```

❗ When we run with the above configuration we get error:
```
ERROR @wdio/runner: Error: Failed to create session.
No matching capability sets found.
Unable to match capability set 0: cjson:metadata is an unknown extension capability for IE
```

If you remove the following block from the IE11 config, there's no error:
```
'cjson:metadata': {
  device: configUtils.getCurrentFranchiseName(),
  platform: {name: os.type, version: os.version()}
},
```
But when this block is removed, then the metadata is not set in the report and we have for
device: "Device name not known"
OS: "Version not known"
![image](https://user-images.githubusercontent.com/69619422/132015756-ce599686-239a-4767-ba1c-1a855bb65f75.png)

**Analysis:**
Webdriverio reporter specs state (for metadata)
```
Note: This is currently not supported if you are using WebdriverIO V6, WebdriverIO V5 still supports this
https://webdriver.io/docs/wdio-cucumberjs-json-reporter/#metadata
```
We are not using V5 or V6 - we are using V7.
