### ISSUE TITLE
PageLoadStrategy Error

### ISSUE THREAD

**Issue by VarunJoshi** [SeleniumHQ/selenium#7487]
## 🐛 Bug Report

I am seeing this error when running selenium tests (using the open browser method) through RIDE in robot framework

Method not found: 'Void OpenQA.Selenium.DriverOptions.set_PageLoadStrategy(OpenQA.Selenium.PageLoadStrategy)'.

The Chrome version is 76.0.3809.100
chromedriver version is ChromeDriver 76.0.3809.68
Selenium version is 3.8.1

Thanks

## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by jimevans** [comment]
The .NET bindings have a [whole set of tests](https://github.com/SeleniumHQ/selenium/blob/master/dotnet/test/common/PageLoadingTest.cs) that test exactly the functionality of setting the `PageLoadStrategy` property. These tests [are passing](https://webdriver-herald.herokuapp.com) using the most recently available public stable (not alpha or beta) release of the .NET bindings ([3.141.0](https://www.nuget.org/packages/Selenium.WebDriver/3.141.0)). You'll need to provide a simple reproducible case, outside of other frameworks, that can be cloned onto a developer machine and used to reproduce the issue.

**Comment by jimevans** [comment]
No reproducible case provided by issue reporter. Closing after nearly three-week wait time.
