### ISSUE TITLE
Consecutive file uploads in firefox repeats previous uploads

### ISSUE THREAD

**Issue by marius-uncrop** [SeleniumHQ/selenium#7489]
## 🐛 Bug Report
When doing consecutive uploads on firefox, the previous uploads are repeated;

## To Reproduce
Tested on selenium + python
geckodriver version: 0.24
firefox versions: 61.0.1 and 68.0.1 (assuming issue would reproduce also on versions between these 2)

Detailed steps to reproduce the behavior:
1. Search for an input webelement of type file
2. Send keys to upload file1
3. Send keys to upload file2

## Expected behavior

file1 and file2 are successfully uploaded one time

## Actual behavior

file1 is uploaded two times
file2 is uploaded one time

For each new upload, the previous uploaded files are uploaded again

**Comment by cskubatz** [comment]
We have experienced the same behavior in a different environment.

**Setup**
"chromedriver": "76.0.0"
"nightwatch": "1.0.6"

All our file upload tests were running in chromedriver 74.0.0 without any errors. After updating to chromedriver 76.0.0 the described behavior set in. There were no other updates.

**Additional info**
If four files are uploaded, the first file is uploaded four times, the second file three times, the third file twice, and the fourth file once. The total number of uploaded files in a test case determines how often the first file is uploaded. Then the number decreases by one for each following file.

**Comment by werfmark** [comment]
> We have experienced the same behavior in a different environment.
> 
> **Setup**
> "chromedriver": "76.0.0"
> "nightwatch": "1.0.6"
> 
> All our file upload tests were running in chromedriver 74.0.0 without any errors. After updating to chromedriver 76.0.0 the described behavior set in. There were no other updates.
> 
> **Additional info**
> If four files are uploaded, the first file is uploaded four times, the second file three times, the third file twice, and the fourth file once. The total number of uploaded files in a test case determines how often the first file is uploaded. Then the number decreases by one for each following file.

Had the same issue, made a report last week:
https://github.com/SeleniumHQ/selenium/issues/7472

Happens with Chromedriver 75.0.0 and up.

**Comment by jimevans** [comment]
Remember that stating with Chrome/chromedriver 75, the driver implements the [W3C WebDriver Specification](https://w3c.github.io/webdriver) by default. This behavior is probably related to the spec’s wording about how multiple inputs to a file upload element works. Specifically, in step 8 of the remote end steps for the [Element Send Keys command](https://w3c.github.io/webdriver/#element-send-keys), for the file input case, it says in substep 6:

> Complete implementation specific steps equivalent to setting the selected files on the input. If multiple is true files are be appended to element’s selected files.

In your web application, if submitting the form on which the file upload element exists (the part that actually uploads the file) doesn’t clear the file upload element content, I would expect this behavior.

**Comment by twalpole** [comment]
Closing since this is WebDriver spec compliant behavior
