### ISSUE TITLE
Add log level mapping for ChromeDriver just like for Firefox

### ISSUE THREAD

**Issue by digulla** [SeleniumHQ/selenium#7493]
ChromeDriver uses the following log levels:

ALL, DEBUG, INFO, WARNING, SEVERE, and OFF

See https://cs.chromium.org/chromium/src/chrome/test/chromedriver/logging.cc

Selenium uses:

"OFF", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST", "ALL".

https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#loggingpreferences-json-object

Please add a mapping between the two list like for Firefox here: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriverLogLevel.java

Chromium is probably also affected.

The same needs to be done for the Python implementation of Selenium.

Related issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=457#c10

**Comment by digulla** [comment]
Related issue: https://bugs.chromium.org/p/chromedriver/issues/detail?id=457#c6

**Comment by barancev** [comment]
`FirefoxDriverLogLevel` defines log levels for the driver (that is converted to a value of the geckodriver commandline option --log-level), it's not related to `getLog` command and logging preferences.

Unfortunately, logging preferences are not specified in the WebDriver W3C standard yet. As soon as the spec is ready we'll implement mapping between the levels defined in the spec and the levels supported by the drivers.

**Comment by barancev** [comment]
On the other hand, chromedriver has `--log-level` commandline option too, and it's worth to implement `ChromeDriverLogLevel` to map Java standard logging levels to the chromedriver ones.

**Comment by digulla** [comment]
Please also add the Python label. Or should I create a linked issue which asks for a log-mapping in Python similar to the one in Java?

**Comment by bongosway** [comment]
@barancev if this is desired, I can work on it. Thoughts?
