### ISSUE TITLE
FluentWait might never complete

### ISSUE THREAD

**Issue by utamas** [SeleniumHQ/selenium#7494]
## 🐛 Bug Report

When `Function` passed to `until` never returns then FluentWait never completes.

## To Reproduce
1. Set a timeout value (e.g.: 1 second), 
2. Pass in a function to until that takes more time then timeout value set in previous step (e.g.: 2 sec).

## Expected behavior

`FluentWait` throws timeout exception after timeout value set for it has passed.

## Test script or set of commands reproducing this issue

```
        long start = System.currentTimeMillis();
        String actual = new FluentWait<>(driver)
                .withTimeout(ofSeconds(1))
                .pollingEvery(ofMillis(450))
                .withMessage("I got bored waiting for this function to complete")
                .until($ -> {
                    try {
                        SECONDS.sleep(5);
                        return "I'm done";
                    } catch (InterruptedException e) {
                        throw new RuntimeException(e);
                    }
                });

        long end = System.currentTimeMillis();
        assert end - start < 2000;
```

**Comment by markwheeler700** [comment]
Happens for me as well

await driver.wait(until.elementLocated(By.css("some element"), 5000, 'Could not locate the element within the time specified'));

Never returns

**Comment by utamas** [comment]
Is this JS code?

**Comment by markwheeler700** [comment]
Yes JS code using webdriverjs  https://www.npmjs.com/package/selenium-webdriver  latest version ^4.0.0-alpha.4 with chrome driver latest version ^76.0.0
I'm running tests using Jest 
The code will return ok if element is present but if element is not present then the test just hangs until it hits by Jest timeout, which is set at 60 seconds. But it should return after 5 seconds and fail with element not present. Looks like the timeout value in wait(until) does not work.

**Comment by utamas** [comment]
The issue I'm seeing is in a java client, so I'm fairly confident the two is unrelated. I'm not familiar with the JS client, so I can't really help you where to look, Sorry.

**Comment by utamas** [comment]
Once I get some time, I would love to open a PR (have a working solution in our project) for fixing this.

**Comment by utamas** [comment]
https://github.com/SeleniumHQ/selenium/pull/7692

**Comment by barancev** [comment]
Sorry to say this, but we decided to return back to the legacy (blocking) implementation after clients complains. It appears that many people use suboptimal approach to manage WebDriver instances using TreadLocal variables. And running conditions in a separate thread makes them lost their driver. So we decided to revert this change in favour of backward compatibility.
