### ISSUE TITLE
Cannot open any URL (chromedriver & C#)

### ISSUE THREAD

**Issue by mahmoud-hassan-911** [SeleniumHQ/selenium#7497]
## 💥 Regression Report

Using latest webdriver library and chromedriver 76 , i wasn't able to open any URL in Chrome in C# , the command prompt and chrome window are shown but nothing happens.
Check my code below.

```
IWebDriver drv = new ChromeDriver();
drv.Url = "http://google.com";
```
I also tried to disable W3C mode but this time only the command prompt window is shown without Chrome window.

```
ChromeOptions op = new ChromeOptions();
op.UseSpecCompliantProtocol = false;
IWebDriver drv = new ChromeDriver(op);
drv.Url = "http://google.com";
```

## Last working Selenium version

Worked up to version: Selenium 3.141.59

Stopped working in version: selenium-4.0.0-alpha-2

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 76.0.3809.100
Browser Driver version: ChromeDriver 76.0.3809.68

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
