### ISSUE TITLE
[Chromedriver 76] javascript error: Cannot read property 'left' of undefined  

### ISSUE THREAD

**Issue by CJMCT89** [SeleniumHQ/selenium#7498]
## 🐛 Bug Report

After upgrading to chromedriver 76, we are having an issue with dropdown elements in our scripts: 
It seems to be an issue with the moveTo method in Selenium2Driver.php line 776
$this->wdSession->moveto(array('element' => $element->getID()));

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 76.0.3809.100
Browser Driver version: Chromedriver 76
Language Bindings version: Java 12.0.1, PHP 7+
Selenium Webdriver: 3.141.59

**Comment by CJMCT89** [comment]
Here is the full error:

2019-08-15 09:47:26: [ERROR] javascript error: Cannot read property 'left' of undefined
  (Session info: chrome=76.0.3809.100)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MXL81622YV', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.1'

**Comment by jimevans** [comment]
Do the PHP language bindings properly support the W3C WebDriver Specification? if not, that needs to happen, since Chrome/chromedriver 75 and above use the spec-compliant dialect of the wire protocol by default.

**Comment by tburiak** [comment]
76 driver doesn't allow click, moveTo, etc on the element that is invisible or under scroll. You should check it.

**Comment by kkumar-g** [comment]
Facing the same issue on Chrome 76. Is there any workaround?
org.openqa.selenium.JavascriptException: javascript error: Cannot read property 'left' of undefined
  (Session info: chrome=76.0.3809.100)
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'

**Comment by barancev** [comment]
Please follow https://bugs.chromium.org/p/chromedriver/issues/detail?id=3044
