### ISSUE TITLE
the code  doesn't work very well with ie11, but ok with chrome

### ISSUE THREAD

**Issue by mjf19891007** [SeleniumHQ/selenium#750]
my development environment is win7 and the version of IE is ie11.

chrome can perform the action to open "www.google.com" and search with Cheese as a key word, but there's an exception  thrown out saying
 "org.openqa.selenium.NoSuchElementException: Unable to find element with name == q (WARNING: The server did not provide any stacktrace information)  Command duration or timeout: 312 milliseconds" 
when it came to ie11.

Does it mean that selenium won't work with ie11 or there is some setting i should make for ie11?

below is the source i tried to run~

package techtest;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class GoogleTest {

    @Test
    public void test(){
        System.setProperty("webdriver.chrome.driver",".\\src\\chromedriver.exe");
        System.setProperty("webdriver.ie.driver",".\\src\\IEDriverServer.exe");
        DesiredCapabilities capability = DesiredCapabilities.internetExplorer();
        capability.setCapability(
                InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        WebDriver IEDriver = new InternetExplorerDriver(capability);
        WebDriver googleDriver = new ChromeDriver();
        testRun(googleDriver);
        testRun(IEDriver);
    }

    private void testRun(WebDriver driver){
        driver.get("http://www.google.com");
        // Alternatively the same thing can be done like this
        // driver.navigate().to("http://www.google.com");
        // Find the text input element by its name
        WebElement element = driver.findElement(By.name("q"));
        // Enter something to search for
        element.sendKeys("Cheese!");
        // Now submit the form. WebDriver will find the form for us from the element
        element.submit();

    }

}

**Comment by mjf19891007** [comment]
ps: when i tried to change the site to a localhost website like "http://localhost:8080/Web/login", ie11 can work, but input action like
 " WebElement id = driver.findElement(By.name("operatorId"));
   id.sendKeys("admin");" 
was excuted very very slow ~

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
