### ISSUE TITLE
WebDriver.close() closes the session

### ISSUE THREAD

**Issue by milosjak** [SeleniumHQ/selenium#7503]
## 🐛 Bug Report

It is stated in various documentation that the difference between the close() and quit() methods is that the close() closes the currently active window, while the quit() closes all the windows while also closing the driver session.
However, I made a test, which calls the driver.close() (leaving it with no open windows) after which it calls driver.quit() which then throws the NoSuchSessionException because it tried to execute the Quit command.
The validation withing quit() checks if the sessionId is null, however it is not, because the close() method does not set it to null. However it seems that if there are no more windows open, the session is closed but the driver is not aware of it - since the session id is still set.
It appears that if you call close() at any point and are left with no windows, you can't call quit() any longer.

## To Reproduce

Create a Junit test, make a setup (@Before), destroy (@After) and the @Test methods.
In the setup put the initialization of the driver, for example, for Firefox:

`@Before
    public void setup() {
        driver = new FirefoxDriver(new FirefoxOptions());
    }`

In the @After method, put the quit() method call:

`@After
    public void destroy() {
        if (driver != null) {
            driver.quit();
        }
    }`

In the @Test method call the close() method:

`@Test
    public void testClosedDriver() {
        driver.close();
    }`

## Expected behavior

The driver should either be aware of the fact that the session is closed, and not try and execute the command on quit(), or calling close() should not kill the session.

## Test script or set of commands reproducing this issue

You should have a project with JUnit and Selenium. Create a new JUnit test and set it up as described in **ToReproduce** section.
I've also attached the test to this ticket (had to rename it to .txt since it doesn't accept .java as an attachment).
[WebDriverTest.java.txt](https://github.com/SeleniumHQ/selenium/files/3515232/WebDriverTest.java.txt)

## Environment

OS: Windows 10
Browser: Firefox 
Browser version: 68.0.2 (64 bit)
Browser Driver version: GeckoDriver 0.24.0 (64 bit)
Language Bindings version: Java 1.8.0_211
Selenium Grid version (if applicable): N/A

**Comment by Dude-X** [comment]
I believe that depending on the operating system, closing the only window may quit the application. In that case, the session is effectively dead. The way I work around this is my wrapper for selenium will ignore calls to driver.close() if the length of windows handles is equal to 1.

**Comment by milosjak** [comment]
Yeah, that's a work around though.
I believe the problem here is that you need some sort of way to know if a session is still up or not. That seems to have traditionally fallen to checking whether the sessionId is null or not. The quit() sets it to null. If the session is closed on close(), when it's the last open window, then the sessionId should also be set to null in this case, so that when the quit() is called, it can skip the call to execute().
However, what I'm not sure about is how clean the session is closed through close() (with only one window left) compared to when you call quit(). If there are some left-overs than this should be addressed as well.

**Comment by AutomatedTester** [comment]
This is by [design](https://w3c.github.io/webdriver/#close-window). There is an expectation that you need to be aware of the amount of windows there are available when you're doing your automation or handle the potential that the driver may not be there when you try access it. 

In this case, closing the last window will close the session

**Comment by milosjak** [comment]
@AutomatedTester So, are you saying that closing the last window cleans up the session properly as if you called quit(), and you can skip calling quit() at that point?
Also, this leaves a question of how would you check for this state where all the windows are closed? If you call getWindowHandles to try and check whether it's an empty set, you again get the NoSuchSessionException? Also, getting sessionId still returns a value, instead of null, which is returned when you check it after calling quit(). So at least, the sessionId should be set to null if close() closes the session.
