### ISSUE TITLE
Support for InternetExplorerDriver of Microsoft Edge on macOS

### ISSUE THREAD

**Issue by xcolwell** [SeleniumHQ/selenium#7507]
## 🚀 Feature Proposal

Microsoft is preparing to release Edge on macOS (https://www.microsoftedgeinsider.com/en-us/download). Requesting support of Edge on macOS in the InternetExplorerDriver.

## Motivation

Support for InternetExplorerDriver to run on macOS would help simplify deployment of integration servers, since all major modern browsers can now run on macOS.

## Example

As normal, except it would run on macOS instead of Windows, and only for Edge.

**Comment by jimevans** [comment]
A driver for Chromium-based Edge [already exists](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/), built and maintained by Microsoft, and there are even executables for MacOS.

InternetExplorerDriver does not now drive, and has never driven Microsoft Edge, and modern versions of IE do not run on any platform except Windows.
