### ISSUE TITLE
Unable to close the Browser if i use - driver.close Method if my java version is 8 along with java Binding version is  	2.46.0

### ISSUE THREAD

**Issue by vikram1015** [SeleniumHQ/selenium#751]
For Java 1.8 or 1.7 and along woth Java Bindings V2.46.0  and when i am trying to perform the below operations :

driver.close : then it is not performing this operation as expected 

driver.quit: then it is closing the browser by providing the below ERROR:

"org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@1837e72"
![issue](https://cloud.githubusercontent.com/assets/13248051/8587348/cd0ef0fa-

Hope i will get some response to my issue 

Thanks in advance 

2617-11e5-9902-95cd88b86de2.png)

**Comment by barancev** [comment]
Why do you think it is an ERROR if the message said it is an INFO? :)

The message is already fixed (removed), pending release 2.47

**Comment by vikram1015** [comment]
Hello

But when I use driver.close then it is not closing the browser

**Comment by barancev** [comment]
driver.close() should close the current window. To stop the browser one have to call driver.quit()

**Comment by vikram1015** [comment]
Yes that is what it is not closing if I am using Java 8 along with latest version of Java bindings

**Comment by barancev** [comment]
Please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

Also check the browser console (Ctrl-Shift-J) and attach the log here.

**Comment by vikram1015** [comment]
Hello

Please find the attached java file and we are using
"driver.close " to close my browser but as i already mentioned if i use
mySelenium-java- 2.46.0 then i am unable to close the browser

please let us know how to proceed

FYI: we have checked with both java 7 and java 8 versions and also it is
working fine for "selenium-java-2.45.0"

Thanks in advance :)

*Thanks & Regards*
*Happy Learning *
*Skype id : Happy.Learning*

**Comment by AJ-72** [comment]
@vikram1015 Can you run the same code using the server mentioned in the last comment by @barancev  in issue #654

**Comment by vikram1015** [comment]
Yes we have done and facing the same issue unable to close it

**Comment by vikram1015** [comment]
Could you please elaborate more on this issue because still facing the same
issue

*Thanks & Regards*
*Happy Learning *
*Skype id : Happy.Learning*

**Comment by barancev** [comment]
Closing the issue as there is npo reproduction case provided

**Comment by sunyang213** [comment]
Hi Barancev,

I am having the same issue by using selenium-dotnet-3.0.0 with Java version 8 update 111.

Here is my C# codes:
            FirefoxProfile profile = new FirefoxProfile();
            IWebDriver driver = new OpenQA.Selenium.Firefox.FirefoxDriver(profile);
            driver.Navigate().GoToUrl("www.bing.com");
            System.Threading.Thread.Sleep(10000);
            driver.Close();

The browser opened by Geckodriver does not close.

**Comment by lukeis** [comment]
@sunyang213 use `driver.Quit()` instead

**Comment by sunyang213** [comment]
driver.Quit() causes another issue by Firefox plugin-container.exe

I have to kill them before calling Quit()

               foreach (var process in Process.GetProcessesByName("plugin-container"))
               {
                    process.Kill();
               }

I just found another thing that driver.Close() does work when there are more than 1 window opened.

It could close each of them except the last one.
When it goes to the last one, nothing happen.
