### ISSUE TITLE
Documentation: missing template for selenium grid node/hub configs

### ISSUE THREAD

**Issue by dvasilev86** [SeleniumHQ/selenium#7513]
## 🐛 Bug Report

using selenium-server-standalone-3.141.59.jar from cli:
`java -jar selenium-server-standalone-3.141.59.jar -role node -nodeConfig seleniumNode.json`
gives me this error:
`Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Deprecated -nodeConfig file encountered. Please update the file to work with Selenium 3. See https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json for more details.`

the documentation on the above page (https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json)  states:
A sample nodeconfig file for server version 3.x.x (>= beta4) can be seen at https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json

the link points to 404 and i was not able to find any DefaultNodeWebDriver.json in the selenium project (using github's find file)

attaching the sample .json (github won't allow .json, so it's .txt instead)
[seleniumNode.txt](https://github.com/SeleniumHQ/selenium/files/3529500/seleniumNode.txt)

OS: any
Browser: n/a
Browser version: n/a
Browser Driver version: n/a
Language Bindings version: n/a
**Selenium Grid version (if applicable):  3.141.59**

**Comment by dvasilev86** [comment]
just a quick followup: the 'configuration' in the json is flattened, as the documentation says, which simply means all of it's contents are moved one level up (in json root) and the "configuration" key is simply removed, e.g.:
```
{
  "capabilities":
      [
        {
          "browserName": "chrome",
          "maxInstances": 100,
          "seleniumProtocol": "WebDriver"
        }
      ],
  "configuration":
  {
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "maxSession": 100,
    "port": 5555,
    "hub": "http://10.52.11.33:4444/grid/register",
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "http://10.52.11.33:4444/grid/register"
  }
}
```

**Comment by diemol** [comment]
Current docs for Grid 3.x can be seen here https://www.selenium.dev/documentation/en/grid/setting_up_your_own_grid/
