### ISSUE TITLE
moveToElement on Firefox throws MoveTargetOutOfBoundsException

### ISSUE THREAD

**Issue by jflorez** [SeleniumHQ/selenium#7515]
## 🐛 Bug Report

Using Selenium 3.141.59 on JDK11, moveToElement using FirefoxDriver (Firefox 68.0.2, Geckodriver 0.24.0) throws a MoveTargetOutOfBoundsException. Same code works when using ChromeDriver.

## To Reproduce

Compile and run the attached Java code

## Expected behavior

The selected element is scrolled into view and clicked

## Test script or set of commands reproducing this issue
```Java
public class BugDemo {
	public static void main(String[] args) {
		WebDriver driver =  new FirefoxDriver();
		try {
			driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
			driver.manage().window().maximize();
			driver.navigate().to("http://automationpractice.com");
			
			var rootElement = driver.findElements(By.className("ajax_block_product")).stream()
			        .filter(e->e.findElement(By.className("product-name")).getText().equalsIgnoreCase("Printed Summer Dress"))
			        .findFirst()
			        .orElseThrow();
			
			// To click the product first it needs to be scrolled into view
			// The JavascriptExecutor is required here because geckodriver doesn't
			// execute moveToElement correctly
			// ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", rootElement);
			new Actions(driver).moveToElement(rootElement).build().perform();
			rootElement.findElement(By.className("quick-view")).click();
		} finally {
			driver.quit();
		}
	}
}
```
## Environment

OS: macOS 10.14.6
Browser: Firefox
Browser version: 68.0.2
Browser Driver version: Geckodriver 0.24.0
Language Bindings version: Java 3.141.59

**Comment by jimevans** [comment]
What version of chromedriver? The behavior of the Firefox driver is compliant with the [W3C WebDriver Specification](https://w3c.github.io/webdriver). It is consistent with the behavior used by the IE driver, the Safari driver, and the Edge driver. It is also consistent with the behavior of the Chrome driver when it is running in spec-compliant mode, which became the default with Chrome/chromedriver 75. See steps 7 and 8 of the algorithm for [dispatching a pointerMove action](https://w3c.github.io/webdriver/#dfn-dispatch-a-pointermove-action) for full details.

**Comment by jflorez** [comment]
ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})

**Comment by jflorez** [comment]
@jimevans thank you, I agree that the behaviour is compliant. Also was not running chrome driver in spec-compliant mode when I filed the bug

**Comment by jflorez** [comment]
One thing I don't understand. While I agree that the moveToElement exception is compliant according to the WebDriver spec as you pointed the comments, in the moveToElement in the Actions class mention that the element is scrolled into view and this doesn't happen when the sample code run on Firefox but it does happen on Chrome.

**Comment by jimevans** [comment]
In the legacy OSS dialect of the JSON wire protocol, the move to element action was its own end point. In that dialect of the protocol, destination elements were expected to be scrolled into view during a move. In the W3C dialect of the protocol, they are not. Again, if you were using the legacy dialect of the protocol, as you say, that would explain the difference.

**Comment by jflorez** [comment]
Thank you for the detailed explanation. Does this mean that the Actions class will have a method to scroll an element into view?

**Comment by jimevans** [comment]
That depends on the W3C working group responsible for producing the spec. In the meantime, JavaScript is your friend.
