### ISSUE TITLE
Unable to launch remote session getting ProtocolHandshake error

### ISSUE THREAD

**Issue by evnraja32** [SeleniumHQ/selenium#7516]
## 🐛 Bug Report

In order perform parallel execution, I just ran selenium grid and triggered script couple of times. For any single grid call the script executed properly in remote PC, but if I try to execute more than 1 iteration getting ProtocolHandshare exception.

## Environment

OS: Windows 10
Browser: MS Edge
Browser version: 
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

Browser Driver version: 
[Release 17134](https://download.microsoft.com/download/F/8/A/F8AF50AB-3C3A-4BC4-8773-DC27B32988DD/MicrosoftWebDriver.exe)

Language Bindings version: Ruby 2.5.5
Selenium version : selenium-webdriver-3.142.3.gem
Selenium Grid version: selenium-server-standalone-3.141.59.jar

## Test script:

```
require 'selenium-webdriver'

remoteBrowser = "MicrosoftEdge"
Selenium::WebDriver::Edge::Service.driver_path = "C:/Webdriver/MicrosoftWebDriver.exe"
#remoteBrowser = "internet explorer"
#Selenium::WebDriver::IE::Service.driver_path = "C:/Webdriver/IEDriverServer.exe"
@browser = Selenium::WebDriver.for :remote,  url: "http://10.74.40.198:5555/wd/hub", 
  desired_capabilities: Selenium::WebDriver::Remote::Capabilities.new(
   {
      browser_name: remoteBrowser,
      platform: "WIN10",
   })
@browser.get("https://www.google.com")
sleep 5
@browser.find_element(xpath: "//input[@name='q']").send_keys("ruby software download\n")
sleep 5
@browser.find_elements(partial_link_text: 'ruby').each do |ele|
   p ele.text
   sleep 2
end

@browser.close
```

## For Launching Hub:
`java -jar selenium-server-standalone-3.141.59.jar -role hub -port 5555 --debug`

`java -jar selenium-server-standalone-3.141.59.jar -role node -hub http://10.74.40.198:5555/grid/register/ -port 1112 -browser browserName="MicrosoftEdge",maxInstances=5,platform="WIN10",platformName="WIN10" --debug`

`java -Dwebdriver.edge.driver="MicrosoftWebDriver.exe" -jar selenium-server-standalone-3.141.59.jar -role node -hub http://10.74.40.198:5555/grid/register/ -port 1112 -browser browserName="MicrosoftEdge",maxInstances=5,platform="WIN10",platformName="WIN10" --debug`

## Expected behavior

Selenium grid should execute multiple instances without any exceptions

## Actual Behavior

Getting ProtocolHandshake error.

Error:

`[remote server] org.openqa.selenium.remote.ProtocolHandshake(ProtocolHandshake.java):115:in 'createSession': Unable to parse remote response: Unknown error (Selenium::WebDriver::Error::UnknownError)
	from [remote server] org.openqa.selenium.remote.ProtocolHandshake(ProtocolHandshake.java):74:in 'createSession'
	from [remote server] org.openqa.selenium.grid.session.remote.RemoteSession$Factory(RemoteSession.java):147:in 'performHandshake'
	from [remote server] org.openqa.selenium.grid.session.remote.ServicedSession$Factory(ServicedSession.java):161:in 'apply'
	from [remote server] org.openqa.selenium.remote.server.ActiveSessionFactory(ActiveSessionFactory.java):180:in 'lambda$apply$12'`

Node Log collected from remote server PC:
[nodeLog.log](https://github.com/SeleniumHQ/selenium/files/3533238/nodeLog.log)

Hub Log collected from remote execution PC:
[hubLog.log](https://github.com/SeleniumHQ/selenium/files/3533239/hubLog.log)

Script Log collected at Local script triggered PC:
[ProtocolHandshakeError.txt](https://github.com/SeleniumHQ/selenium/files/3533242/ProtocolHandshakeError.txt)

**Comment by mooragor** [comment]
I'm having an almost identical issue.
selenium-server-standalone-3.141.59.jar 
Running on windows 10
Trying to start Edge browsers
Also coming from a Ruby test framework (SitePrism, Capybara)

`  Unable to parse remote response: Unknown error (Selenium::WebDriver::Error::UnknownError)
  [remote server] org.openqa.selenium.remote.ProtocolHandshake(ProtocolHandshake.java):115:in `createSession'
  [remote server] org.openqa.selenium.remote.ProtocolHandshake(ProtocolHandshake.java):74:in `createSession'
  [remote server] org.openqa.selenium.grid.session.remote.RemoteSession$Factory(RemoteSession.java):147:in `performHandshake'
  [remote server] org.openqa.selenium.grid.session.remote.ServicedSession$Factory(ServicedSession.java):161:in `apply'
  [remote server] org.openqa.selenium.remote.server.ActiveSessionFactory(ActiveSessionFactory.java):180:in `lambda$apply$12'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$11$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$2$1():-1:in `accept'
  [remote server] java.util.Spliterators$ArraySpliterator():-1:in `tryAdvance'
  [remote server] java.util.stream.ReferencePipeline():-1:in `forEachWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyIntoWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyInto'
  [remote server] java.util.stream.AbstractPipeline():-1:in `wrapAndCopyInto'
  [remote server] java.util.stream.FindOps$FindOp():-1:in `evaluateSequential'
  [remote server] java.util.stream.AbstractPipeline():-1:in `evaluate'
  [remote server] java.util.stream.ReferencePipeline():-1:in `findFirst'
  [remote server] org.openqa.selenium.remote.server.ActiveSessionFactory(ActiveSessionFactory.java):183:in `apply'
  [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):66:in `lambda$null$2'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$2$1():-1:in `accept'
  [remote server] java.util.Collections$2():-1:in `tryAdvance'
  [remote server] java.util.stream.ReferencePipeline():-1:in `forEachWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyIntoWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyInto'
  [remote server] java.util.stream.AbstractPipeline():-1:in `wrapAndCopyInto'
  [remote server] java.util.stream.FindOps$FindOp():-1:in `evaluateSequential'
  [remote server] java.util.stream.AbstractPipeline():-1:in `evaluate'
  [remote server] java.util.stream.ReferencePipeline():-1:in `findFirst'
  [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):69:in `lambda$createNewSession$3'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.DistinctOps$1$2():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$2$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$3$1():-1:in `accept'
  [remote server] java.util.stream.ReferencePipeline$2$1():-1:in `accept'
  [remote server] java.util.stream.Streams$StreamBuilderImpl():-1:in `tryAdvance'
  [remote server] java.util.stream.Streams$ConcatSpliterator():-1:in `tryAdvance'
  [remote server] java.util.stream.ReferencePipeline():-1:in `forEachWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyIntoWithCancel'
  [remote server] java.util.stream.AbstractPipeline():-1:in `copyInto'
  [remote server] java.util.stream.AbstractPipeline():-1:in `wrapAndCopyInto'
  [remote server] java.util.stream.FindOps$FindOp():-1:in `evaluateSequential'
  [remote server] java.util.stream.AbstractPipeline():-1:in `evaluate'
  [remote server] java.util.stream.ReferencePipeline():-1:in `findFirst'
  [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):72:in `createNewSession'
  [remote server] org.openqa.selenium.remote.server.commandhandler.BeginSession(BeginSession.java):65:in `execute'
  [remote server] org.openqa.selenium.remote.server.WebDriverServlet(WebDriverServlet.java):235:in `lambda$handle$0'
  [remote server] java.util.concurrent.Executors$RunnableAdapter():-1:in `call'
  [remote server] java.util.concurrent.FutureTask():-1:in `run'
  [remote server] java.util.concurrent.ThreadPoolExecutor():-1:in `runWorker'
  [remote server] java.util.concurrent.ThreadPoolExecutor$Worker():-1:in `run'
  [remote server] java.lang.Thread():-1:in `run'`

**Comment by JosephWardDotTech** [comment]
duplicate of https://github.com/SeleniumHQ/selenium/issues/5350?

**Comment by evnraja32** [comment]
Working fine in latest alpha3
