### ISSUE TITLE
Selenium WebDriverWait.until(invisiblityOfAllElements) returns timeout on NoSuchElementException

### ISSUE THREAD

**Issue by r-sniper** [SeleniumHQ/selenium#7518]
Please check my question asked on [stackoverflow](https://stackoverflow.com/questions/57488223/selenium-webdriverwait-untilinvisiblityofallelements-returns-timeout-on-nosuch)
## 🐛 Bug Report

When using `WebdriverWait.until(invisibilityOfAllElements(ArrayOfElements))`
And the elements are being located by Pagefactory Pattern
```
@FindBy(css=".className")
WebElement element;
```
the `isInvisible` method only catches `StaleElementException`, but in case of element located by `@FindBy` locator, the element holds ProxyElement and the actual element is looked up only when the element is referenced, and the element is referenced in `isInvisible` method by checking `!element.isDisplayed()` condition, whick causes timeout exception even though element is not present.

## To Reproduce

1. Have an element located by `@FindBy` Locator
```
@FindBy(css=".className")
WebElement element;
```
2. Check `invisibilityOFElement`

```
void fun(){
WebDriver driver = new ChromeDriver();
try{
    new WebDriverWait(driver, Duration.ofSeconds(5)).until(ExpectedConditions.invisibilityOf(element));
    }
catch(TimeoutException ex){
    }
}
```

## Expected behavior

The `invisibilityOfElement` should not throw `TimeoutException` when element is not found, instead like `StaleElementException` is caught, `NoSuchElementException` should be caught and timeout should not occur

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 76.0.3809.100
Browser Driver version: ChromeDriver: 76.0.3809.68
Language Bindings version: Java, Selenium Webdriver

**Comment by zweiron** [comment]
I agree that the methode `isInvisible(final WebElement element)` should catch `NoSuchElementException`. I think that an element that is not in the DOM can be treated as invisible.

**Comment by r-sniper** [comment]
Any Update regarding this, Solution seems fairly easy and obvious

**Comment by AutomatedTester** [comment]
Please submit a PR and we will look at it

**Comment by barancev** [comment]
The proposed fix is hitting a wrong target.
`element.isDisplayed()` should never throw a `NoSuchElementException`
It's the proxy that should be fixed instead of `isInvisible` method
