### ISSUE TITLE
Cannot set UseSpecCompliantProtocol to false in C# binding in 3.141.0

### ISSUE THREAD

**Issue by rhpijnacker** [SeleniumHQ/selenium#7521]
## 🐛 Bug Report

See commit https://github.com/SeleniumHQ/selenium/commit/005a942a5ce0a63a5917c3eb7386c02a2de8700b#diff-36634a6252409cef3f673d98e220c5e8.

Since Chrome 75, the default setting of the w3c spec compliance has switched to true.
However the C# binding only passes the option if it is set to true (assuming the deafult to be false).
This means we cannot set it to false at all with the current stable C# binding.

## Environment

Browser: Chrome
Browser version: 75.x and higher
Browser Driver version: ChromeDriver 75.x and higher
Language Bindings version: C# 3.141.0

**Comment by algot** [comment]
I can confirm that on 
C# Selenium 3.141.0 + ChromeDriver 77.0.3865.4000 this option is not applied to false value

**Comment by csjturbine** [comment]
I also discovered this to be the case in 77.0.3685.x versions today and it is requiring major revisions to our code to work around this issue.

**Comment by rhpijnacker** [comment]
@barancev I see you removed the C-dotnet label. It is a problem in the C# bindings, so isn't that label acurate?

**Comment by rhpijnacker** [comment]
It's been a while since this was first identified.
Any update on this?

**Comment by diemol** [comment]
This was released a few months ago and can be used in the latest release (`beta-2`).
