### ISSUE TITLE
Problem with opening and switching tabs in Firefox

### ISSUE THREAD

**Issue by ajust93** [SeleniumHQ/selenium#7525]
## 🐛 Bug Report

Opening new tabs and using them behaves differently in Chrome & Firefox.

The problem happens with every website, not just google.com.

The provided code is only the relevant part, with additional lines missing.

The problem may be with how windows are handled.

Code works perfectly with Chrome, but in Firefox usually two new tabs are opened, before switching tabs.

## Expected behavior

Steps:
1) Open google.com in current tab
2) Collect all links with tag "a" on google.com
    **for each collected link:**
    3) Open link in a new tab via CTRL + Left-Click
        **if two tabs are open:**
        4) Switch to second tab (= newly opened link)
        5) Close second tab
        6) Switch back to first tab (= google.com main page)

## Test script or set of commands reproducing this issue

driver.get("https://www.google.com/");
List\<WebElement\> allLinks = driver.findElements(By.tagName("a"));

for (WebElement link : allLinks) {
	Actions action = new Actions(driver);
	action.keyDown(Keys.CONTROL).click(link).keyUp(Keys.CONTROL).perform();
        ArrayList\<String\> tabs = new ArrayList\<String\>(driver.getWindowHandles());
	if (tabs.size() == 2) {
		driver.switchTo().window(tabs.get(1));
		driver.close();
		driver.switchTo().window(tabs.get(0));
        }
}

## Environment

OS: Windows 10
Browser: Chrome & Firefox
Browser version: Chrome 76.0.3809.132 & Firefox 68.0.2
Browser Driver version: ChromeDriver 76.0.3809.126 & GeckoDriver 0.24.0
Language Bindings version: Java Version 8 Update 221 (Build 1.8.0_221-b11)
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
1) `getWindowHandles` returns a set, not a list. There is no guarrantee that the new window (or tab) is "second" in the list you've build from the set
2) Window operations are asyncronous, the driver does not wait until a window is, for example, closed. You should implement explicit waits if you want them to be syncronous.
