### ISSUE TITLE
By.Classname does not work properly when having classnames with trailing spaces

### ISSUE THREAD

**Issue by boris779** [SeleniumHQ/selenium#7528]
## 🐛 Bug Report

I test a website where some classnames have trailing spaces (that's another story)
I found out that there was a change between chromedriver version 74 to 75

Since version 75 the elements could not be found anymore using the following statement:
`webDriver.findElements(By.className("Section__title-box "))`
Chromedriver 73, 74 and firefox works fine!

### Html-code:
\<div class="Section__title-box ">
\<h2 id="request-and-documents-section-title-id" class="Section__title" tabindex="-1">
Documents\</h2>\</div>

\<div class="Section__title-box sr-only">\<h2 id="request-and-document-my-requests-section-title-id" class="Section__title" tabindex="-1">My requests\</h2>\</div>

### Tested different drivers/browsers
Firefox 68 finds two elements ✔
Chromedriver 73 & 74 finds one element 
Chromedriver >75 does not find any element ❗

If changing the statement to 
`webDriver.findElements(By.className("Section__title-box"))`
Firefox 68 finds two elements ✔
Chromedriver 73 & 74 finds two elements ✔
Chromedriver 75 & 76 finds one element

### Workarounds
Using By.xpath with contains(@class,'Section__title-box ')

## Deep Analyse:
In my option, the following code seems to work differently in the driver versions

By.java:404
`private String containingWord(String attribute, String word)  {
            return "contains(concat(' ',normalize-space(@" + attribute + "),' '),' " + word + " ')";
        }`

## Environment

OS: Linux
Browser: Chromium
Browser version: 75.latest & 76.latest
Browser Driver version:  chromedriver 75.0.3770.140 & chromedriver 76.0.3809.126
Language Bindings version: Java 3.141.0

I'm not sure if that behavior is correct or not, because I think trailing spaces are not ok.

**Comment by boris779** [comment]
I have additional Infos, to harden my suspicion

on the webpage, there is an element like 

`<li>text   spaces</li>` <-- there are two blanks between the words!

After I getting the text with
`text = webDriver.findElement(By.xpath("//dl[@id='request-details-2']//li")).getText()`

the text in `text` does not contain two spaces between words. That's weird, isn't it?

**Comment by barancev** [comment]
A class name can't contain spaces, so it's working as expected now, you should change your code to pass proper class names without spaces.

The method getText returns "visible" text that in your example contains a single space, as defined by HTML specification. unless your element has CSS style `white-space: pre`
