### ISSUE TITLE
Instance is null on proxy failure, yet window is open.

### ISSUE THREAD

**Issue by Kalkonen** [SeleniumHQ/selenium#7529]
## 🐛 Bug Report
When creating a instance of FirefoxDriver / ChromeDriver and proxy fails, it will throw a WebDriverException and null the variable. So you end up with a open browser window, without being able to close it. 

## To Reproduce

Detailed steps to reproduce the behavior: 
1. Make a webdriver instance.
2. Catch the web driver exception.
3. Try closing the window. It will be null.

## Expected behavior

It is expected to be able to atleast kill it so you dont end up with a ghost window, unkillable.

## Test script or set of commands reproducing this issue

	System.setProperty("webdriver.gecko.driver", "driver/geckodriver.exe");
	try {
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		firefoxOptions.setBinary(binary);
		driver = new FirefoxDriver(firefoxOptions);
		
		Proxy proxy = new Proxy();
		proxy.setAutodetect(false);
		proxy.setHttpProxy(proxyData);
		firefoxOptions.setProxy(selProxy);
	} catch(WebDriverException e) {
		e.printStackTrace();
		if(driver != null)
			driver.quit();
	}
## Environment

OS: Windows 10
Browser: Firefox (But happeneds to chrome as well)
Browser version: 68.0.2
Browser Driver version: geckodriver v0.24.0
Language Bindings version: 1.8.0_221
Selenium Grid version (if applicable): 3.141.59

**Comment by barancev** [comment]
What's not working as expected? What exception did you mean? Setting a proxy after a driver initialization has no effect, so in your code the driver starts with no proxy settings.

**Comment by diemol** [comment]
Closing this as we didn't get any more information.
