### ISSUE TITLE
Allow passing of additional options to the Java Modules

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7531]
The generated modules need to "open" to (at least) the JSON package so that we can use the `fromJson` and `toJson` methods. Without this, all heck opens up. In addition, the `FindsBy*` classes are internal, and they should be made available to other classes until we find a way to replace them.

**Comment by diemol** [comment]
This has been moved to "Done" in the Selenium 4 [project](https://github.com/SeleniumHQ/selenium/projects/2), I could not find the commit related to it, but feel free to reopen if something is still missing.
