### ISSUE TITLE
Firefox fails to start with large (file size) profile directory

### ISSUE THREAD

**Issue by sciatro** [SeleniumHQ/selenium#7533]
## 🐛 Bug Report

Creating an instance of Firefox using a large (as in file size) profile directory errors out with:

    Traceback (most recent call last):
    File "~/.venvs/headless/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
        chunked=chunked)
    File "~/.venvs/headless/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
        conn.request(method, url, **httplib_request_kw)
    File "~/.venvs/headless/lib/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
    File "~/.venvs/headless/lib/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
    File "~/.venvs/headless/lib/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
    File "~/.venvs/headless/lib/python3.7/http/client.py", line 1055, in _send_output
        self.send(chunk)
    File "~/.venvs/headless/lib/python3.7/http/client.py", line 977, in send
        self.sock.sendall(data)
    OSError: [Errno 22] Invalid argument

Which ultimately becomes ``urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))`` 

## To Reproduce

    from selenium.webdriver import Firefox, FirefoxProfile

    BIG_PROF_PATH = "/path/to/large/profile/dir"

    profile = FirefoxProfile(profile_directory=BIG_PROF_PATH)
    driver = Firefox(executable_path=DRIVER_BIN, firefox_profile=profile)

Detailed steps to reproduce the behavior:

The above Py/FF/Se hello world is not particularly important; rather, it is the large profile directory as an init input. I cannot nail down an exact threshold for "large" (500mb seems to be enough much of the time and 1gb always is). 

The failure takes quite a while and in the run up to it the python process' memory consumption balloons (e.g. a 600mb profile dir as input results in nearly 16+gb of memory usage prior to error. 

This happens without any addons. If you just load up on cookies and browser cache that is sufficient.

Enabling python logging results in **vast** outputs (looks like the whole profile might be getting logged as base 64 or some such). The geckolog is empty (not a shock as FF never gets going).

## Expected behavior

Expect Selenium controlled instance of FF to be able to load up from the same profile as my install of FF. 

## Test script or set of commands reproducing this issue

The, trivial, code above will reproduce the error. Getting a large enough input profile is the hard part. If you use FF as a high traffic daily driver ``about:profiles`` and copy your actual profile path is a reasonable starting point for ``BIG_PROF_PATH``. You can confirm with ``$ du -h BIG_PROF_PATH``.

## Environment

OS: OSX
Browser: FF
Browser version: 68
Browser Driver version: GeckoDriver 0.24
Language Bindings version: Python 3.141 on Py3.7

**Comment by AutomatedTester** [comment]
Each profile does get turned into a base64 string. Sending over 500mb + size profiles is probably not the best use of Selenium and a grid. 

Is there something special in this profile that you couldn't use the Options class to bring down the size of what is sent across the wire?

**Comment by renjujv** [comment]
@sciatro Can you please confirm if this is possible using Options?

@AutomatedTester If the profile size gets to 500 MB when Firefox is used as a daily driver, wouldn't this be a valid issue?

Of course, using the capabilities/Options instead of the profile is a workaround and this issue is not a blocker per se. But this seems like a limitation in the approach with the size limit for profile directory right?

PS: I'm just starting up with the community and codebase. Please excuse if the questions are a bit ignorant.

**Comment by sciatro** [comment]
From my point of view the Options API is orthogonal. This size limit issue arose while attempting to run forward from a "real" profile that a human had driven into a particular state (where the issue with / nature of that state was totally unknown) then running repeatable testing from it.

The automated testing work around is to manually - via the FF ui - whittling down the irrelevant contributors to profile size (e.g. image cache).

For automation of a daily driver dumping parts of your cache on a per-run basis may or may not be a usable workaround.

**Comment by AutomatedTester** [comment]
Closing as FirefoxProfile has been deprecated in favour of using Options which will make what we send over the wire much smaller and just having people send over the relevant preferences/addons as needed.

**Comment by sciatro** [comment]
As I said above options are great but not a replacement for grabbing a live profile. Going to Options only may well be a warranted api cleanup but it is also a loss of functionality.
