### ISSUE TITLE
Chrome browser launched through C# selenium is not able to login to our application having azure authentication

### ISSUE THREAD

**Issue by VinitGopee** [SeleniumHQ/selenium#7536]
## 🐛 Bug Report

We are using c# selenium for automating our scripts in chrome browser. The browser launched through the scripts were working as expected before two weeks. But suddenly the chrome browser is not able to login to my application using azure authentication.

## To Reproduce
string url = ""
 ChromeOptions options = new ChromeOptions();
options.AddAdditionalCapability("useAutomationExtension", false);
 options.AddArgument("-no-sandbox");
driver = new ChromeDriver(options);
driver.Navigate().GoToUrl(url);
driver.Manage().Window.Maximize();

We are running the above script and providing the user name for azure authentication. After providing the username and click Next,it is throwing an error message and not allowing us to proceed. PFA the screenshot.
We have tried with enabling and disabling addins,but same result.
![chrome login](https://user-images.githubusercontent.com/26160703/64242019-6ad9b100-cf22-11e9-95f2-c4c4e9a7c8fd.jpg)

---------------------------------------
We had discussed the same with the IT team and their response-
"The issue that needs to be raised to Selenium is that when applications (specifically chrome with the windows 10 accounts addin enabled) are run through their automation engine they lose the ability to use hybrid device registration/modern authentication to authenticate to Azure applications.  This causes our conditional access rules to block access to those hosted applications"

OS: Windows 10
Browser: Chrome
Browser version: 76.0.3809
Browser Driver version:  ChromeDriver 75.0.3770.140
Language Bindings version: C# through visual studio
Selenium Grid version (if applicable): No

**Comment by sagarpatra** [comment]
We are facing the same issue due to Morden Authentication in Azure . Any update/ resolution to the Issue please

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
