### ISSUE TITLE
selenium-java versions 2.45.0 and 2.46.0 are corrupted on maven central

### ISSUE THREAD

**Issue by matthewgerrard** [SeleniumHQ/selenium#754]
Apologies if this is the wrong place for this... Let me know if it isn't and I'll repost elsewhere.

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.45.0/
http://repo2.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.45.0/

http://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.46.0/
http://repo2.maven.org/maven2/org/seleniumhq/selenium/selenium-java/2.46.0/

Currently contain a copy of the selenium-java jar file that does not contain any class files.

**Comment by lukeis** [comment]
this isn't an actual bug :)

All the classes that used to live there are now in other (dependent) jars. Essentially this artifact isn't needed... But I don't feel like breaking everyone who may have been using just the 'selenium-java' dependency, as that has been documented on the seleniumhq site for some time.

I may remove it / restructure the artifacts in a future 3.0 release... but not until then as that would be a breaking change for many users.s

**Comment by matthewgerrard** [comment]
Great, thanks. Sorry I must have missed the documentation on the site. My bad :)
