### ISSUE TITLE
Not found matching IPv4/IPv6 settings

### ISSUE THREAD

**Issue by zcmgyu** [SeleniumHQ/selenium#7541]
## 🐛 Bug Report

Could not start hub because not found matching IPv4/IPv6 settings.

## To Reproduce
**Start a Hub by source:**

<img width="1183" alt="Screen Shot 2019-09-06 at 15 52 10" src="https://user-images.githubusercontent.com/13638569/64407041-4e727b80-d0be-11e9-928f-912288c5b7e7.png">

**Start a Hub by built jar file:**

`$ java -jar selenium_server_deploy.jar hub`

**Result:**
> 15:55:08.537 INFO [EventBusConfig.createBus] - Creating event bus: org.openqa.selenium.events.zeromq.ZeroMqEventBus
> 15:55:08.701 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://fe80:0:0:0:142f:99c:ee0:455b%en0:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://fe80:0:0:0:142f:99c:ee0:455b%en0:4443]
> 15:55:08.762 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://fe80:0:0:0:142f:99c:ee0:455b%en0:4442 and tcp://fe80:0:0:0:142f:99c:ee0:455b%en0:4443
> Exception in thread "main" java.lang.IllegalArgumentException: Unable to find event bus class: org.openqa.selenium.events.zeromq.ZeroMqEventBus
> 	at org.openqa.selenium.grid.server.EventBusConfig.createBus(EventBusConfig.java:74)
> 	at org.openqa.selenium.grid.server.EventBusConfig.getEventBus(EventBusConfig.java:44)
> 	at org.openqa.selenium.grid.commands.Hub.lambda$configure$0(Hub.java:103)
> 	at org.openqa.selenium.grid.Main.launch(Main.java:123)
> 	at org.openqa.selenium.grid.Main.main(Main.java:100)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.openqa.selenium.grid.server.EventBusConfig.createBus(EventBusConfig.java:69)
> 	... 4 more
> Caused by: org.zeromq.ZMQException: fe80:0:0:0:142f:99c:ee0:455b%en0 not found matching IPv4/IPv6 settings : errno 49
> 	at zmq.io.net.tcp.TcpAddress.resolve(TcpAddress.java:147)
> 	at zmq.io.net.tcp.TcpAddress.<init>(TcpAddress.java:40)
> 	at zmq.io.net.Address.resolve(Address.java:93)
> 	at zmq.SocketBase.connect(SocketBase.java:549)
> 	at org.zeromq.ZMQ$Socket.connect(ZMQ.java:3069)
> 	at org.openqa.selenium.events.zeromq.UnboundZmqEventBus.<init>(UnboundEventBus.java:67)
> 	at org.openqa.selenium.events.zeromq.BoundZmqEventBus.<init>(BoundZmqEventBus.java:63)
> 	at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:35)
> 	at org.openqa.selenium.events.zeromq.ZeroMqEventBus.create(ZeroMqEventBus.java:51)
> 	... 9 more
> 

## Expected behavior

Could start a hub normally.
I researched how to config IPv4/IPv6 for Selenium, but seem like no description about it.
But I've found the same error log of Selenium Grid Hub on Selenium Gist.

https://gist.github.com/seleniumgists/51dad712b2cb48213c4694371315145c
https://gist.github.com/seleniumgists/4b042f7f9b3c09a58d22649f7ecf911b

## Environment

OS: OSX
Language Bindings version: Java 4.0.0-alpha-3
Selenium Grid version (if applicable): 4.0.0-alpha-3

**Comment by adamgoucher** [comment]
disabling ipv6 per https://support.nordvpn.com/Connectivity/macOS/1047410442/How-to-disable-IPv6-on-macOS.htm allowed me to get around this just now.

**Comment by thasso** [comment]
Another workaround is to set the system property `java.net.preferIPv4Stack` to `true`, i.e. `java -Djava.net.preferIPv4Stack=true -jar selenium_server_deploy.jar hub`

**Comment by shs96c** [comment]
You shouldn't need to force your machine to prefer IPv4 in 2020. @diemol can reproduce this issue on his machine, and I think we have a path to a fix in place.

**Comment by diemol** [comment]
Thanks for the hint @shs96c, this now works and it will be released in the next alpha.
