### ISSUE TITLE
driver.getKeyboard.sendKeys(…) throws an UnsupportedCommandException when using chromedriver 76.0.3809.126

### ISSUE THREAD

**Issue by Rinzwind** [SeleniumHQ/selenium#7542]
## 🐛 Bug Report

The following example using `sendKeys` works when using chromedriver 2.44, but throws an `UnsupportedCommandException` exception when using chromedriver 76.0.3809.126:

```
driver = new RemoteWebDriver(new ChromeOptions());
driver.get("http://en.wikipedia.org/");
driver.findElementById("searchInput").click();
driver.getKeyboard().sendKeys("Search string");
assertEquals(driver.findElementById("searchInput").getAttribute("value"), "Search string");
```

I'm not quite sure whether this is the expected behavior, due to the W3C protocol not supporting `/session/:sessionId/keys` as in the Json Wire protocol, or whether this is a bug with the `sendKeys` not being correctly mapped to the W3C protocol.

ZIP file with a runnable test case: [Test Keyboard SendKeys Java.zip](https://github.com/SeleniumHQ/selenium/files/3582912/Test.Keyboard.SendKeys.Java.zip)

When executed using chromedriver 76.0.3809.126 (execute using `ant`), the test has an error (`org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement`); it works when using chromedriver 2.44 (execute using `ant -Dchromedriverversion=2.44`) (pass `-Dchromedriverplatform=…` to use `linux64` or `win32` if not using `mac64`).

## Environment

OS: macOS 10.13.6
Browser: Chrome
Browser version: 76.0.3809.132
Browser Driver version: chromedriver 2.44 and 76.0.3809.126
Language Bindings version: selenium-java-3.141.59

**Comment by barancev** [comment]
Don't use `driver.getKeyboard()`, it returns an instance of `Keyboard` class that is deprecated. Use either regular `WebElement.sendKeys` method or `Actions` class

**Comment by Rinzwind** [comment]
The documentation for [RemoteWebDriver.getKeyboard()](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html#getKeyboard--) does not seem to mention that it is deprecated, nor does the documentation for [Keyboard](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Keyboard.html) or [Keyboard.sendKeys()](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Keyboard.html#sendKeys-java.lang.CharSequence...-) mention this. Should this not be mentioned in the documentation? Or is this already mentioned somewhere else?

**Comment by barancev** [comment]
Ah, sorry, it will be deprecated in 4.0 and the issue is related to 3.x, reopening.

**Comment by barancev** [comment]
Is the issue still actual in Chrome 77 and chromedriver 77?
I can't reproduce it in this version.

**Comment by barancev** [comment]
To use modern versions of Chrome that works in w3c-conformant mode by default you should explicitly switch to the legacy mode:
```ChromeOptions options = new ChromeOptions();
options.setExperimentalOption("w3c", false);
driver = new RemoteWebDriver(options);```
