### ISSUE TITLE
[#Possible bug] Selenium Firefox not using preferences

### ISSUE THREAD

**Issue by Mozza7** [SeleniumHQ/selenium#7543]
I've posted this problem around and have gotten no fixes, users suggested it may be an issue with selenium.

I've been trying to use the preferences to download files without having to click OK , using the SaveToDisk functon. My code is below:

    fprofile = webdriver.FirefoxProfile()
    fprofile.set_preference("browser.download.folderList", 2)
    fprofile.set_preference("browser.download.manager.showWhenStarting", False)
    fprofile.set_preference("browser.download.dir", 'C:/Downloads/backups')  
    fprofile.set_preference("browser.helperApps.neverAsk.saveToDisk", "attachment/x-tar" + ",text/plain") 

    options = Options()

    (hash)options.add_argument('--headless')

    driver = webdriver.Firefox(firefox_profile=fprofile, options=options)"

Headless is to be used once working, hence why it's commented out. (actual hash caused large)

Windows 10; Python 3.7; Pycharm if it matters

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by Mozza7** [comment]
[Here is the current full code](https://pastebin.com/UMXjMCJM), to be honest the shortest is what I put initially. 
No error messages or anything alike, but the preference **is** set. [See image](https://imgur.com/a/coHmIMH)

FYI, the options is currently unused, hence arguments being commented out. 

links:
[Full code](https://pastebin.com/UMXjMCJM)
[Preference section](https://pastebin.com/vV9H8BTA)
[Preference image](https://imgur.com/a/coHmIMH)

Can provide screenshots of it, but it's exactly the same as when downloading files from Firefox as usual; pop up asking to save or open.

Have tried the debugger (never used it before, apologies if this isn't helpful) and got the following after running the saveToDisk line:
{TypeError}set_preference() missing 1 required positional argument: 'value'

I cannot figure out what value is missing? As mentioned, it still gets added to the preferences.
Apologies for the delay in getting back, didn't see this at all, also, apologies if this is no more helpful - please let me know, pretty new to coding entirely to be honest.

**Comment by Mozza7** [comment]
[Here is the problem code](https://pastebin.com/vV9H8BTA), in particular saveToDisk/line 15.

[Here is the full code](https://pastebin.com/UMXjMCJM)

[Reddit post](https://www.reddit.com/r/learnpython/comments/dbqvxz/selenium_firefox_preferences_help/)

[Preferences image](https://imgur.com/a/7rTsKX6) - this shows that it **is** applying the profile.

Debug comes back:
{TypeError}set_preference() missing 1 required positional argument: 'value'
This is shown in the Reddit post.

The end game is to be able to download both TXT and TAR, but I'm just trying to get one working right now. I'm sorry if this is not enough, LMK if you need anything more.

**Comment by cgoldberg** [comment]
why don't you use an HTTP lib to download?

**Comment by Mozza7** [comment]
> why don't you use an HTTP lib to download?

Sorry, I'm not sure what you mean? What should I be doing? This is just the way I always see to do it

**Comment by Mozza7** [comment]
`from selenium import webdriver
import sys

DOWNLOAD_DIR = "C:\\TestFolder"

profile = webdriver.FirefoxProfile()

profile.set_preference("browser.download.folderList", 2)
profile.set_preference("browser.download.manager.showWhenStarting", False)
profile.set_preference("browser.download.dir", DOWNLOAD_DIR)
print(f"Backups will be stored in {DOWNLOAD_DIR}")
profile.set_preference("browser.helperApps.neverAsk.saveToDisk", "application/java-archive")

driver = webdriver.Firefox(firefox_profile=profile)


driver.get('https://bit.ly/2TlkRyu')

sys.exit()`

This downloads the file as expected, really not sure what's different apart from application/x-tar

**Comment by Mozza7** [comment]
Had some help from reddit, and the problem persists in my code, but not in a different code.

Test code [here](https://pastebin.com/VMwsRdbj). This goes into a onedrive folder which is where I upload most the backup files, including the .tar I am trying to download. Downloading from here worked fine. I applied a similar concept to my main code, this didn't work.

**Comment by Mozza7** [comment]
Ah, figured it out - **NOT a bug**. I didn't know that MIME types would differ dependant on the 'actual' file type (lack of a better word). I had thought FireFox downloaded based on extension name (.tar, .txt, .exe blah blah) but recently found it's not necessarily the case. I use the Network tool on Firefox(&Firebug) to see that the files were actually downloaded as application/octet-stream. 

HOWEVER, I copied the response headers and looked through, and I'm not sure if it's something from Firefox's side or what - but it was actually spelt "applicatoin/octet-stream" - application being spelt incorrectly. 

This is now working, apologies & thank you.
