### ISSUE TITLE
Stale element not found issue with chromedriver V76.0.3809.68 in Linux container

### ISSUE THREAD

**Issue by autoibi** [SeleniumHQ/selenium#7545]
### Meta -
Container OS: Ubuntu 18.04.2 LTS (Bionic Beaver)
Selenium version: 3.141.0
Chrome version: 76.0.3809.87
Chromedriver version: 76.0.3809.68
Python version: 3.6.8

### Issue - 
Executing JavaScript to retrieve SVG child tag in iframe throws: selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found

### Steps to reproduce - 
1. Copy the following source code and save it as html file:
```
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
	var htmlString = "<svg width=\"391\" height=\"391\" viewBox=\"-70.5 -70.5 391 391\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"25\" y=\"25\" width=\"200\" height=\"200\" fill=\"lime\" stroke-width=\"4\" stroke=\"pink\" /><circle cx=\"125\" cy=\"125\" r=\"75\" fill=\"orange\" /><polyline points=\"50,150 50,200 200,200 200,100\" stroke=\"red\" stroke-width=\"4\" fill=\"none\" /><line x1=\"50\" y1=\"50\" x2=\"200\" y2=\"200\" stroke=\"blue\" stroke-width=\"4\" /></svg>";
	document.getElementById("iframetest").contentWindow.document.write(htmlString);
});
</script>
</head>
<body>
<iframe id="iframetest" height="600" width="600" style="border:none;"></iframe>
</body>
</html>
```
2. Bring up Chrome using Python, and direct to saved html page. Execute following Python code:
`driver.execute_script('return $(\'iframe\').contents().find(\'rect\');')
`  

### Note - 
Executing same JavaScript in Chrome console has no issue.
`$('iframe').contents().find('rect')`

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://bugs.chromium.org/p/chromedriver/issues/list
