### ISSUE TITLE
Document to refer for newbies who are interested to contribute to SeleniumHQ project

### ISSUE THREAD

**Issue by electronsrace** [SeleniumHQ/selenium#7546]
## 💬 Questions and Help
Hello.. I am new to open source contribution community.. I have forked SeleniumHQ and cloned the repository into my local machine. 

I am using Windows 7 and Eclipse IDE. Plz tell me how can I import the Selenium project into Eclipse IDE ?. 

I tried to google, but none of the results really helped. Could you please tell if any document is there to refer for newbies like me who are interested to contribute to open source community.
I joined Selenium IRC and no one answered my query. I don't know whom to contact now. Hence, I raised this query.

Thanks in Advance!

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by cgoldberg** [comment]
> Please note that this issue tracker is not a help form and this issue will be closed.
> For questions or help please see:
> 
> SeleniumHQ IRC channel
> SeleniumHQ Slack channel
> The Selenium Users google group
