### ISSUE TITLE
Altitude is null despite set in LocationContext (Java)

### ISSUE THREAD

**Issue by heruan** [SeleniumHQ/selenium#7550]
## 🐛 Bug Report

When setting the `Location` via `LocationContext` with a non-null altitude, subsequent calls to `geolocation.getCurrentPosition` provide a null altitude value.

## To Reproduce

Detailed steps to reproduce the behavior:

```java
Location location = new Location(1.0, 1.0, 1.0);
ChromeDriver driver = new ChromeDriver();
driver.setLocation(location);
```

Then, opening a page with this script:

```javascript
navigator.geolocation.getCurrentPosition(position => {
    position.coords.latitude === 1.0 // true, correct
    position.coords.longitude === 1.0 // true, correct
    position.coords.altitude === 1.0 // false, it's null!
});
```

## Expected behavior

It's expected that `position.coords.altitude` to have the correct value.

## Test script or set of commands reproducing this issue

See code above.

## Environment

OS: macOS
Browser: Chrome
Browser version: 76.0.3809.132 
Browser Driver version: 76.0.3809.132
Language Bindings version: Java 3.141.59

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by heruan** [comment]
This test should reproduce, but it throws an unexpected NPE:

```java
public class LocationTest {

    @Test
    public void shouldHaveAltitude() {
        ChromeOptions options = new ChromeOptions()
                .addArguments("--disable-search-geolocation-disclosure")
                .setExperimentalOption("w3c", false);
        ChromeDriver chrome = new ChromeDriver(options);
        chrome.setLocation(new Location(1.1, 1.1, 1.1));
        chrome.get("https://google.com");

        double altitude = (double) chrome.executeAsyncScript(
                "navigator.geolocation.getCurrentPosition(p => arguments[0](p.coords.altitude))");

        assertEquals(1.1, altitude);
    }
}
```

Still investigating, any hint appreciated!

**Comment by barancev** [comment]
It seems to be a chromedriver issue and should be reported to https://bugs.chromium.org/p/chromedriver/issues/list

I tried to run our example with debug logs and here is the part related to setLocation:
```[1568990394.739][INFO]: [660f7f74eaff3ae8579bb0a64ea521a3] COMMAND SetGeolocation {
   "location": {
      "altitude": 1.1,
      "class": "org.openqa.selenium.html5.Location",
      "latitude": 1.1,
      "longitude": 1.1
   }
}
...
[1568990394.742][DEBUG]: DevTools WebSocket Command: Page.setGeolocationOverride (id=13) 5BC892F58DDA5430FDE7C6CA65AFAFD1 {
   "accuracy": 100.0,
   "latitude": 1.1,
   "longitude": 1.1
}
```
You can see that Selenium passes all the data (including altitude) but geckodriver loses part of it while converting the Selenium command to the corresponding DevTools command.

And it seems to be a restriction of DevTools API, it does not support altitude:
https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setGeolocationOverride

So the issue can be routed from chromedriver to DevTools
