### ISSUE TITLE
Does IE proxy support sslProxy

### ISSUE THREAD

**Issue by kunwong90** [SeleniumHQ/selenium#7553]
platform:windows7
selenium version:3.141.59
IE version:10.0.9200.17457

code example:
public WebDriver createWebDriver(ProxyIp proxyIp, String userAgent) throws FileNotFoundException {
        File file = ResourceUtils.getFile("classpath:iedriverServer_Win32_3.141.59/IEDriverServer.exe");
        System.setProperty("webdriver.ie.driver", file.getPath());
        InternetExplorerOptions ieOptions = new InternetExplorerOptions();
        Proxy proxy = new Proxy();
        //proxy.setProxyType(Proxy.ProxyType.MANUAL);
        //proxy.setAutodetect(false);
        proxy.setHttpProxy(proxyIp.getIp() + ":" + proxyIp.getPort());
        proxy.setSslProxy(proxyIp.getIp() + ":" + proxyIp.getPort());
        proxy.setFtpProxy(proxyIp.getIp() + ":" + proxyIp.getPort());
        ieOptions.setProxy(proxy);
        //ieOptions.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
        ieOptions.setCapability(InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAINS, true);
        ieOptions.setCapability(InternetExplorerDriver.INITIAL_BROWSER_URL, "");
        return new InternetExplorerDriver(ieOptions);
    }

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
