### ISSUE TITLE
EventFiringWebDriver doesn't truly fire events of WebDriver usage

### ISSUE THREAD

**Issue by nvborisenko** [SeleniumHQ/selenium#7554]
Current implementation of firing events is considering to wrap original WebDriver instance with `EventFiringWebDriver` instance, and use this instance in test.

```csharp
var driver = new EventFiringWebDriver(new ChromeDriver());
// use this driver
```

I see several issues in this way.

1.
`EventFiringWebDriver` class hides all original members of `ChromeDriver` class.
Example:
```csharp
var driver = new ChromeDriver();
driver.FindElementByLinkText("a");
```

And if I wrap driver with `EventFiringWebDriver` I lose `FindElementByLinkText` method.
```csharp
var driver = new ChromeDriver();
driver = new EventFiringWebDriver(driver);
driver.FindElementByLinkText("a"); // method not found
```

2.
Events are not fired if I get unwrapped instance of WebDriver and execute some method.
```csharp
var driver = new ChromeDriver();
driver = new EventFiringWebDriver(driver);
driver.FindElement(By.Id("id")); // fires event
((ChromeDriver)driver.WrappedDriver).FindElement(By.Id("id")); // doesn't fire event
```

WebDriver events are really useful, we need this feature. But current implementation of events are painful for users.

**Possible way to resolve it**: bring events directly to `RemoteWebDriver` class. Given that all drivers are inherited from `RemoteWebDriver` class, it brings events for all drivers.
```csharp
var driver = new ChromeDriver();
driver.OnNavigating += MyHandler;
```

Now events are in box solution, absolutely all user's actions are handled. Doesn't matter how user uses WebDriver, all events will be fired.

**Comment by jimevans** [comment]
It is the intent for .NET Selenium users to be coding to the interface (`IWebDriver`) rather than a specific implementation (`ChromeDriver`, `FirefoxDriver`, etc.). Thank you for the suggestion, but we won’t be moving these events to the base API.
