### ISSUE TITLE
"view source" links in documentation incorrect for JS bindings

### ISSUE THREAD

**Issue by camilstaps** [SeleniumHQ/selenium#7558]
## 🐛 Bug Report

The links to the source code from the [JS API documentation](https://seleniumhq.github.io/selenium/docs/api/javascript/index.html) seem to be incorrect. They point to the right repository, but the files and lines they reference are often incorrect.

Thanks for looking into this!

## To Reproduce

Go to https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_By.html (e.g.) and click on "view source". The linked line is not related to `By`.

## Expected behavior

In this particular example I'd expect a link like https://github.com/SeleniumHQ/selenium/blob/fcc43e2f64cc3bcd8839afb0f0097d8d8adf0ffb/javascript/node/selenium-webdriver/lib/by.js#L116 or https://github.com/SeleniumHQ/selenium/blob/fcc43e2f64cc3bcd8839afb0f0097d8d8adf0ffb/javascript/node/selenium-webdriver/lib/by.js#L121

## Test script or set of commands reproducing this issue

Not applicable.

## Environment

OS: any
Browser: any
Browser version: any
Browser Driver version: not applicable
Language Bindings version: JS any
Selenium Grid version (if applicable): not applicable

**Comment by renjujv** [comment]
The new documentation URL is:
```https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_By.html```

And the correct link to point to by the View Source button seems to be:
```https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js```

Anyone interested in making the change commit?

**Comment by camilstaps** [comment]
Closing because I don't use this anymore and I'm cleaning up my GitHub issues. If you want to keep this tracked, please open a new issue.
