### ISSUE TITLE
WebElement.findElement(By.js( ... )) throws a TypeError

### ISSUE THREAD

**Issue by camilstaps** [SeleniumHQ/selenium#7559]
## 🐛 Bug Report

`WebElement.findElement(By.js( ... ))` throws a `TypeError`.

## To Reproduce

```js
var driver=new Builder().forBrowser('firefox').build();
driver.get('https://google.com');
driver.wait(until.elementLocated(By.js('return document.getElementById("tsf");'))).then(function(form){
	form.findElement(By.js('return this.getElementsByName("q")[0];')); // <- TypeError
});
```

This throws a type error regardless of the contents of the second `By.js`. What is the expected behaviour? Should `this` in this case be linked to the `WebElement` (as I assumed here)?

If you can tell me what the expected behaviour is, I can see if I can make a PR. (Would it then this be OK if `WebElement` would provide a `executeScript` method, as this seems to be the most straightforward solution?)

## Expected behavior

This should open the Google page without errors (but do nothing, since no further actions are specified).

## Test script or set of commands reproducing this issue

See under "to reproduce".

## Environment

OS: Debian 10.1
Browser: Firefox
Browser version: 60.9.0esr
Browser Driver version: geckodriver 0.24.0
Language Bindings version: JS 4.0.0-alpha.5
Selenium Grid version (if applicable): not applicable.

**Comment by baruchvlz** [comment]
What is the error? I'm guessing something along `getElementsByName is not defined`? If so, this is due to the scope in which your JavaScript snippet is executed. You would expect `this` to refer to your resolved promise function but it really is the [scope of the driver](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L194) and `getElementsByName` is not a driver command but rather a browser command. 

Maybe this would fix it:

```js
form.findElement(By.js('return document.getElementsByName("q")[0];'));
```

**Comment by camilstaps** [comment]
@baruchvlz You can reproduce the error by copying my code to a JS file and running it. You need something like `const {Builder, By, until}=require ('selenium-webdriver');` to setup selenium.

Here is the full error for your convenience:

```
(node:1978) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'apply' of undefined
    at .../node_modules/selenium-webdriver/lib/by.js:194:35
    at thenableWebDriverProxy.findElementInternal_ (.../node_modules/selenium-webdriver/lib/webdriver.js:931:24)
    at WebElement.findElement (.../node_modules/selenium-webdriver/lib/webdriver.js:1905:25)
    at .../test.js:6:7
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also, as mentioned, this throws a type error regardless of the contents of the second `By.js`.

The problem is that the particular combination of `WebElement.findElement` and `By.js` is not implemented.

**Comment by pawelusfr** [comment]
@camilstaps `By.js` assumes [here](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L194) it's being called from `WebDriver` instances only.

I don't think there is a good way to change it on `selenium-webdriver` side as it would require passing the element to the script you are going to execute. Thus it would require to do in-place script modifications.

This should fix it for you:
```
driver.findElement(By.js((elem) => elem.getElementsByName("q")[0], form));
```
although in such simple case you could use `By.css` or `byName` and have the same result.

**Comment by camilstaps** [comment]
> Thus it would require to do in-place script modifications.

Not necessarily; you could set `this` to the element.

There are several workarounds available but this should be fixed. Or the documentation should clearly state the incompatibility of `WebElement.findElement` and `By.js`.

I don't see any problem to implement this. The function you linked to can check if its argument is a `WebElement`, and in this case get the driver with `getDriver`. The only problem is that [`executeScript` always sets `null` as `this`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L750), but for this a separate `executeScriptWithThis` can be added.

The real problem seems to be that the JS library doesn't seem to be actively maintained. I can create a PR along the lines suggested here, or with some other solution, but a decision has to be made on the intended behaviour first.

**Comment by camilstaps** [comment]
Closing because I don't use this anymore and I'm cleaning up my GitHub issues. If you want to keep this tracked, please open a new issue.
