### ISSUE TITLE
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>

### ISSUE THREAD

**Issue by yegor256** [SeleniumHQ/selenium#7563]
I'm getting this exception very often when the server is pretty loaded:

```
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
	/usr/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
	/usr/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
	/usr/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
	/usr/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
	/usr/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
	/usr/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
	/usr/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	/usr/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	/usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:129:in `response_for'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:82:in `request'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/w3c/bridge.rb:59:in `get'
	/var/lib/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/navigation.rb:32:in `to'
```

It seems that it would make sense to catch `Net::ReadTimeout` and retry, just like you are catching similar exceptions, in `http/default.rb`.

**Comment by p0deje** [comment]
Is your server page loads for more than 60 seconds? If yes, then you just need to increase the timeout - https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#internal-timeouts

**Comment by Rajagopalan-M** [comment]
@p0deje 

But it should have been like one has to set the value here

`driver.manage.timeouts.page_load=` 

not like this

```
client = Selenium::WebDriver::Remote::Http::Default.new
client.read_timeout = 120
```

That's the way Java binding works. But here in ruby selenium binding `page_load=` timings works only for `goto` method.

**Comment by p0deje** [comment]
@Rajagopalan-M That's how specification defines [page load timeout](https://w3c.github.io/webdriver/#dfn-page-load-timeout):

> Provides the timeout limit used to interrupt an explicit navigation attempt.

For navigation triggered by element clicks, it should be ignored.

**Comment by Rajagopalan-M** [comment]
@p0deje 
Okay,but In Java Binding, page_load is used for the page load as a result of element click as well.

**Comment by p0deje** [comment]
You are right, in Java this works the same way. I even found [a test](https://github.com/SeleniumHQ/selenium/blob/2f8943e9806ffb5edc5a396a5ac2677745064833/java/client/test/org/openqa/selenium/PageLoadingTest.java#L380-L411) for that. However, both Java and Ruby does the same thing when setting timeout, so I guess in Ruby you should also be able to just do the following and avoid timeout errors:

```ruby
driver.manage.timeouts.page_load = 120
```

**Comment by Rajagopalan-M** [comment]
@p0deje 

 However, both Java and Ruby does the same thing when setting timeout,

I am not sure whether I misunderstood you. 

> driver.manage.timeouts.page_load = 120

The above line not doing the same thing. If you set page_load in Java, it's used for loading the page as a result of loading the url by driver.navigate().To and also the page loading as a result of clicking the button but in ruby if you set page_load then it is only used Page loading as a result of `goto`.

**Comment by p0deje** [comment]
> The above line not doing the same thing. If you set page_load in Java, it's used for loading the page as a result of loading the url by driver.navigate().To and also the page loading as a result of clicking the button but in ruby if you set page_load then it is only used Page loading as a result of goto.

Hm, it _should_ work the same way. If it is not, can you create a bug report with the test case on how to reproduce?

**Comment by Rajagopalan-M** [comment]
@p0deje 

Okay, I will do it tomorrow morning. Thank you very much.

**Comment by Rajagopalan-M** [comment]
@p0deje 

I don't have site now to load more than 3 seconds now after a button click. I have one but that's my internal site. So use any site in the given below program and you can clearly see button click throws the time out error after 3 seconds. And I reduced this timeout to 3 seconds for you to notice the fact that setting up page load `driver.manage().timeouts().pageLoadTimeout(3L, TimeUnit.SECONDS);` infact involves in button click as well

Here is my program
```

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.concurrent.TimeUnit;

public class Gopal {
    public static void main(String args[]) {
        WebDriver driver = new ChromeDriver();
        System.setProperty("webdriver.chrome.driver", "C:\\Ruby26\\bin\\chromedriver.exe");
        driver.navigate().to("Your Url");
        driver.manage().timeouts().pageLoadTimeout(3L, TimeUnit.SECONDS);
        driver.findElement(By.id("UserName")).clear();
        driver.findElement(By.id("UserName")).sendKeys("xxxx");
        driver.findElement((By.id("Password"))).clear();
        driver.findElement((By.id("Password"))).sendKeys("yyy");
        driver.findElement((By.id("Login"))).click();
    }
}
```

**Comment by p0deje** [comment]
I've just added more tests for page load timeout in Ruby (https://github.com/SeleniumHQ/selenium/commit/81552aa0ae14f41aa8d3dda9f4ce0c3b3df4735e) and both scenarios timeout properly:

* navigation to a page that loads slowly (using `driver.get`)
* navigation to a page that loads slowly (using `driver.find_element(...).click`)

@Rajagopalan-M If you can find a case when it doesn't work in Ruby that I can use to debug the issue, please create a new bug report.

**Comment by Rajagopalan-M** [comment]
@p0deje  Sure thank you very much . I will check and let you know.
