### ISSUE TITLE
Issue with Latest Chrome Driver Version 77 on Android mobile devices.

### ISSUE THREAD

**Issue by skumar1122** [SeleniumHQ/selenium#7564]
## 🐛 Bug Report

I have updated my chrome driver version to 77 and my samsung s8 device chrome to 77 to run appium tests in my local. Its all working until I had 76 chrome version on that mobile. I can see now it fails and complaints about 77 version.

## Environment
Appium version (or git revision) that exhibits the issue: 1.15.0-beta.1
Last Appium version that did not exhibit the issue (if applicable): Release
Node.js version (unless using Appium.app|exe): v12.8.1
Npm or Yarn package manager: npm
Mobile platform/version under test: 8.0
Real device or emulator/simulator: Samsung S8
Appium CLI or Appium.app|exe: Appium CLI
Mobile Chrome Version : 77
$  chromedriver --version
ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})
$ which chromedriver
/usr/local/bin/chromedriver

## Details

> [Chromedriver] Error: No Chromedriver found that can automate Chrome '77.0.3865'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details. You could also try to enable automated chromedrivers download server feature
> 
> [debug] [WD Proxy] Got response with status 200: {"sessionId":"fdac66f928757106b922daaff342f4aa","status":13,"value":{"message":"unknown error: Failed to forward ports to device ce10182a6065d91a03: . unknown error: The adb command failed. Extra response: <>.\n (Driver info: chromedriver=77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}),platform=Mac OS X 10.14.6 x86_64)"}}

## Logs 
https://gist.github.com/skumar1122/2a90ac58c53130e49ef2194dfc6748aa

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by hijazi** [comment]
I've having the same issue and it wasn't resolved after updating to chromedriver 77

**Comment by andressav** [comment]
@hijazi I downgraded Appium to 1.14.1 and forced it to install with chromedriver 2.42 and it worked for version 77.
My installation looked like this: `npm install -g appium@1.14.1 --chromedriver_version="2.42"`

**Comment by vzdeadler** [comment]
> @hijazi I downgraded Appium to 1.14.1 and forced it to install with chromedriver 2.42 and it worked for version 77.
> My installation looked like this: `npm install -g appium@1.14.1 --chromedriver_version="2.42"`

I had the same issue, and it was the solution, thanks.
