### ISSUE TITLE
4.0 alpha 3 (or proper release) timing?

### ISSUE THREAD

**Issue by chriscapaci** [SeleniumHQ/selenium#7565]
There's a bug, 7390, that has been fixed in code in which the dev @jimevans  said will be in alpha 3. Is there any idea when this will happen? I've been waiting a while now and figured I'd see if there are any plans yet. Please let me know. Thanks.

**Comment by jimevans** [comment]
This is a question rather than an issue. Please use the user facing mailing list, or the project Slack/IRC channel.
