### ISSUE TITLE
Selenium / Edge Chromium JavaScript / Node support

### ISSUE THREAD

**Issue by bhaidar** [SeleniumHQ/selenium#7567]
## 🚀 Feature Proposal

I noticed all the examples online make use of Java to demonstrate how to use Selenium with Edge Chromium.

JavaScript/Node seems not to be supported by now.

Any feedback on this?

Thanks
Bilal

**Comment by avilela** [comment]
I tried to run in python, with remote webdriver and doesn't work too

**Comment by avilela** [comment]
@bhaidar you have any progress?

**Comment by bhaidar** [comment]
@avilela I was able to run my tests with Java! But still, it's not working with Node.js.

**Comment by diemol** [comment]
This is already possible in the Alpha versions of JS. The docs show how to do that [here](https://www.selenium.dev/documentation/en/webdriver/driver_requirements/).
If you are using Grid 3, you could see in this [issue](https://github.com/SeleniumHQ/selenium/issues/8712) how to configure the Node to get it working.
