### ISSUE TITLE
IEDriverServer 3.150.0 cannot connect when screen is locked

### ISSUE THREAD

**Issue by JoshuaHillerup** [SeleniumHQ/selenium#7568]
## 💥 Regression Report

A clear and concise description of what the regression is.

When the screen is locked, or when running on a remote PC with no RDP sessions active, when trying to create a new driver object the exception "The HTTP request to the remote WebDriver server for URL http://localhost:16357/session timed out after 60 seconds." is thrown.

## Last working Selenium version

Worked up to version:

IEDriverServer.exe version 3.14.0

Stopped working in version:

IEDriverServer.exe version 3.141.59

*note* different errors in the versions in between, but still does not function at higher than 3.14.0

## To Reproduce

Lock your screen, or run on a remote PC with no active RDP session.

While the screen is locked create a driver instance of InternetExplorerDriver.  The constructor will throw an exception for the timeout.

Note, I have tried a number of different IE driver configuration settings as well as configurations of IE itself without anything causing different behaviour.

Detailed steps to reproduce the behavior:

## Expected behavior

The driver will be created, and will function, like it does when the screen is not locked, or when there is an active RDP session.

## Test script reproducing this issue (when applicable)

in C#:
`var driver = new InternetExplorerDriver(
    InternetExplorerDriverService.CreateDefaultService(driversDir),
    new InternetExplorerOptions
    {
        InitialBrowserUrl = @"https://github.com/SeleniumHQ/selenium" 
    }, TimeSpan.FromSeconds(60));

driver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(time);
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(time);
`

## Environment

OS: Windows 10
Browser: Internet Explorer
Browser version: e.g.: 11.950.17134.0
Browser Driver version: 3.150 
Language Bindings version: C# 3.141.0 
Selenium Grid version (if applicable):  NA

**Comment by jimevans** [comment]
@JoshuaHillerup Please clarify for me what version the driver stops working in. You mentioned it worked in 3.14.0, but did not in 3.141.59. Did it work in 3.141.0 or 3.141.5?

Also, please bear in mind there may not be anything that can be done to resolve this, regardless of whether it was working before.

**Comment by JoshuaHillerup** [comment]
In 3.141.0 and 3.141.5 it seems to time out whenever you do things like driver.Open or IWebElement.Click, but does not timeout when the constructor is called.

**Comment by jahmai** [comment]
I think I am experiencing the same issue. All I get is this and the initial page never loads. I can manually type the page to navigate to and it loads.

![image](https://user-images.githubusercontent.com/2010997/66362597-25038300-e9cf-11e9-8a2f-0537ad354e43.png)

This broke about the same versions listed above and is extremely flakey, but fails to work the vast majority of the time. We run the tests on a TeamCity agent running in Azure.

**Comment by nehamantri** [comment]
Jahmai - how did you resolve the issue?

**Comment by harshkahlon** [comment]
> ~I think I am experiencing the same issue. All I get is this and the initial page never loads. I can manually type the page to navigate to and it loads.~
> 
> ![image](https://user-images.githubusercontent.com/2010997/66362597-25038300-e9cf-11e9-8a2f-0537ad354e43.png)
> 
> ~This broke about the same versions listed above and is extremely flakey, but fails to work the vast majority of the time. We run the tests on a TeamCity agent running in Azure.~
> 
> Nevermind, it appears my issue was to do with the DPI settings on the remote computer.

How did you resolve the issue ?

**Comment by josephreilly** [comment]
@harshkahlon @nehamantri 
I had a similar issue to this, my IE tests would work if I had my RDP session open, but if it was minimised or closed then they would fail. This is pretty much because closing an RDP session effectively locks the screen, preventing IEDriverServer from working. My solution was to use VNC to log into the remote machine, log in as my user, start Selenium Server, then disconnect (but not sign out). I can now run my IE tests. I used TightVNC but any VNC server should work.

Hope this helps.

**Comment by diemol** [comment]
Thank you for providing a workaround, @josephreilly!
Closing as no work is needed on the bindings side.
