### ISSUE TITLE
Selenium WebDriver can't click on AJAX element !

### ISSUE THREAD

**Issue by msayem63** [SeleniumHQ/selenium#7569]
Click failure on AJAX window Button.

An ajax panel inside webpage with different elements such as 'Login to Register', 'Register Me', 'View Details', Buttons etc, can't click

https://www.queenslibrary.org/calendar?searchField=*&category=calendar&fromlink=calendar&searchFilter=
 and click any card the right side of the Quick View exist the said elements ;

My Code to perform action on element- 
By container = By.xpath("//input[@value='View Details']]");
		WebDriverWait wait = new WebDriverWait(driver, 59);
		wait.until(ExpectedConditions.elementToBeClickable(container));
		JavascriptExecutor jsExe = ((JavascriptExecutor)driver);
		jsExe.executeScript("arguments[0].click();", container);

[HTML_Code.txt](https://github.com/SeleniumHQ/selenium/files/3617115/HTML_Code.txt)
@Environment
OS:  Windows 10
Browser: <! Chrome
Browser version: 76.0.3809.132
Browser Driver version: ChromeDriver 75.0.3770.8
Language Bindings version: Java 3.141.59
TestNG version 6.14.3

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
