### ISSUE TITLE
Shift key modifier no longer works in Actions

### ISSUE THREAD

**Issue by cailenmusselman** [SeleniumHQ/selenium#757]
C#
Windows 7
Firefox 34.0

Works with Selenium 2.44, but no longer works in 2.45, 2.46

    this.table.FindElement(By.CssSelector("tr[data-rule-id='" + ruleId + "'] td.dismiss input")).Click();
    IWebElement nextCheckbox = this.table.FindElement(By.CssSelector("tr[data-rule-id='" + secondRuleId + "'] td.dismiss input"));
    Actions action = new Actions(this.driver);
    action.KeyDown(Keys.Shift).Click(nextCheckbox).KeyUp(Keys.Shift).Build().Perform();

On the page in question all checkboxes between the two should be selected if the shift key is held down.

**Comment by lukeis** [comment]
a reproducible script should also contain the page (or html) in question

**Comment by cailenmusselman** [comment]
Sorry, it's a private, company page and I just don't have time to create a tiny version to reproduce the isssue.

Upgraded to Firefox 39.0, rather than downgrading to Selenium 2.44, has solved the problem though.

**Comment by lukeis** [comment]
ok... then we can't do much without a reproducible test case. We can reopen if you provide one.
