### ISSUE TITLE
Network intercept api to inspect request ans reponse

### ISSUE THREAD

**Issue by bimalviswam** [SeleniumHQ/selenium#7571]
## 🚀 Feature Proposal

Currently  what I learned in my research is that there is no direct way to intercept api calls in webdriverJS. I think it will be a handy feature and I see that already available in few libraries like puppeteer and taiko. (https://taiko.gauge.org/#request-response)

## Motivation

I searched for this feature for selenium js and could not get an accurate and simple solution. Talked to the Engineers as well and it seems that it will be a good feature to have. 

## Example

Consider a UI which is making calls to a third party api after some manipulations/calculations  on User entries. team does not control the api and they need to make sure the request created by the UI has the right data as per the business logic. In this scenario the only way we can validate this is by looking at the request. 

Another scenario is to isolate the testing to UI by sending a mock response to UI and then validating that UI has  the right data displayed .

**Comment by bimalviswam** [comment]
appreciate comment for down vote as it is an opportunity to learn since I am a beginner in the space .

**Comment by barancev** [comment]
There will be added DevTools integration in version 4.0 that will provide interception functionality. So we will not make separate implementation of this feature.
