### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError (unable to connect to chromedriver 127.0.0.1:9515)

### ISSUE THREAD

**Issue by SnehaReddyM** [SeleniumHQ/selenium#7574]
## 🐛 Bug Report
Attempt to start Automaton test in chrome is showing error unable to connect to chromedriver 127.0.0.1:9515"

Detailed steps to reproduce the behaviour:

1.Installed ruby "Ruby+Devkit 2.6.4-1 (x64)" from the site https://rubyinstaller.org/downloads/ on the windows10 machine with 64-bit.
2.The output of ruby -v is perfect:
C:\Users\smadadi>ruby -v
ruby 2.6.4p104 (2019-08-28 revision 67798) [x64-mingw32]
3.Then installed the gems from the command line :
gem install selenium-webdriver
gem install selenium-cucumber

list of gems are available at the bottom
4. Downloaded the compatible chromedriver_win32.zip verion  77.0.3865.40 for the chrome browser version 77.0.3865.75 (Official Build) (64-bit)

5.Extracted the chromedriver file and placed in the path "C:\Ruby26-x64\bin"

6.Opened command prompt "chromedriver -v exits without giving any output and error.

7.Opened the command prompt and opened irb & given the below commands:

C:\Users\smadadi>irb
irb(main):001:0> require 'selenium-webdriver'
=> true
irb(main):002:0> driver = Selenium::WebDriver.for :chrome
Traceback (most recent call last):
       13: from C:/Ruby26-x64/bin/irb.cmd:31:in `<main>'
       12: from C:/Ruby26-x64/bin/irb.cmd:31:in `load'
       11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       10: from (irb):2
        9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver.rb:88:in `for'
        8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/driver.rb:46:in `for'
        7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/driver.rb:46:in `new'
        6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/chrome/driver.rb:40:in `initialize'
        5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/driver.rb:303:in `service_url'
        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/service.rb:108:in `start'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/socket_lock.rb:41:in `locked'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/service.rb:111:in `block in start'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/common/service.rb:200:in `connect_until_stable'
Selenium::WebDriver::Error::WebDriverError (unable to connect to chromedriver 127.0.0.1:9515)

## Expected behavior

The command "driver = Selenium::WebDriver.for :chrome" should open the chrome window without above errors

## Test script or set of commands reproducing this issue
irb commands:
require 'selenium-webdriver'
driver = Selenium::WebDriver.for :chrome
## Environment

OS:  Windows 10 64 bit
Browser:  Chrome
Browser version: 77.0.3865.75
Browser Driver version:  ChromeDriver 77.0.3865.40
Language Bindings version:   ruby 2.6.4p104 (2019-08-28 revision 67798) [x64-mingw32]
Selenium Grid version (if applicable):  selenium-cucumber (3.1.5)
selenium-webdriver (3.142.4)

Please find the gem list and screenshot attached

**Comment by SnehaReddyM** [comment]
![unabletoconn](https://user-images.githubusercontent.com/45586766/65118311-8d7ec600-da08-11e9-80f6-ba161f1d0754.PNG)
[gemlist.txt](https://github.com/SeleniumHQ/selenium/files/3624664/gemlist.txt)

**Comment by p0deje** [comment]
What happens when you start chromedriver manually? It looks like it cannot start.

**Comment by SnehaReddyM** [comment]
When I tried to start manually there is no response& no error message also and exits out from the command 
Please find the screenshot attached
![startchdriver](https://user-images.githubusercontent.com/45586766/65218888-0a777180-dad5-11e9-88da-d18c747fed9f.PNG)

**Comment by p0deje** [comment]
Seems like something is wrong with your chromedriver installation. You'd normally see it print something:

```
$ chromedriver
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
```

I don't know what the issue might be, but you can ask in the [selenium-users](https://groups.google.com/forum/#!forum/selenium-users) group.

Closing as not Selenium issue.
