### ISSUE TITLE
driver.page_source hangs after running driver.switch_to.window

### ISSUE THREAD

**Issue by peiranguo** [SeleniumHQ/selenium#7577]
## 🐛 Bug Report
I updated from ChromeDriver 76 to ChromeDriver 77.

Now, selenium hangs on the first driver command after switching to a new window with switch_to.window(). The command that runs after switch_to.window doesn't have to be driver.page_source (I just used page_source as an example in the test script). The test hangs in the same way if you use driver.title, or driver.get_screenshot_as_png() instead.

## To Reproduce

Detailed steps to reproduce the behavior:

Selenium test script:
```
import time
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait


def test_switch_to() -> None:
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')

    driver = webdriver.Chrome(options=options, desired_capabilities=DesiredCapabilities.CHROME)
    driver.get('file:///bugreport/page.html')

    print('opened page and clicking on link')
    sys.stdout.flush()

    link = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.ID, 'NewWin')))
    link.click()

    print('clicked link and waiting for window handle')
    sys.stdout.flush()

    while len(driver.window_handles) != 2:
        pass
    new_tab = driver.window_handles[1]

    print('handles available,')
    sys.stdout.flush()
    time.sleep(1)
    print('switching')
    sys.stdout.flush()

    driver.switch_to.window(new_tab)

    print('done switching,')
    sys.stdout.flush()
    time.sleep(1)
    print('using driver,')
    sys.stdout.flush()

    driver.page_source
    print('done test')
```
page.html:
```
<html><head><title>Testing</title></head>
  <body><a id="NewWin" href="javascript:popupnewwin();">open new window</a>

<script type="text/javascript">
        function popupnewwin() { // simplified $.ajax(blah) to setTimeout() 
          setTimeout(function(){
            myWindow=window.open('','');
            myWindow.document.write('<html><head><title>New</title></head><body>Hi</body></html>');
            myWindow.focus();
          }, 1000)
        }
</script>
  </body></html>
```

## Expected behavior

Run with `pytest -s test_switch_to.py --fulltrace` and the test passes.

Actual behavior: operator runs out of patience after a few minutes and hits ctrl-C.

## Test script or set of commands reproducing this issue

Please see preformatted text in reproduce steps.

## Environment

OS: Linux, Debian (Docker image FROM marketplace.gcr.io/google/debian9)
Browser: Chrome
Browser version: google-chrome-stable 77.0.3865.75-1
Browser Driver version: ChromeDriver 77.0.3865.40
Language Bindings version: Python 3.6.8, selenium 3.141.0
Selenium Grid version (if applicable):  

Note: I just rebuilt my docker image with ChromeDriver 76.0.3809.68 (still using Chrome 77) and the test passed.

**Comment by cgoldberg** [comment]
> selenium hangs on the first driver command (in driver.execute())

your example script doesn't call `driver.execute()`

**Comment by peiranguo** [comment]
Oops. I was unclear in my comments. I updated the comment to say, 
> Now, selenium hangs on the first driver command after switching to a new window with switch_to.window(). It doesn't have to be driver.page_source. It can be any driver.* method that ends up calling self.execute on the driver.

**Comment by peiranguo** [comment]
In retrospect, I only ever tested this with driver.page_source, driver.title, and driver.get_screenshot_as_png(). I haven't tried it with other driver methods after the switch_to. I'll update the comments to clarify.

**Comment by peiranguo** [comment]
This issue got resolved in the ChromeDriver ticket.
