### ISSUE TITLE
Options.addCookie() signals UnableToSetCookieException when using chromedriver 77 but works when using chromedriver 2.44

### ISSUE THREAD

**Issue by Rinzwind** [SeleniumHQ/selenium#7579]
## 🐛 Bug Report

The following test works when using chromedriver 2.44, but when using chromedriver 77, the `addCookie` call signals an `UnableToSetCookieException`:

```
public void testAddCookie() {
	driver = new RemoteWebDriver(new ChromeOptions());
	driver.get("http://localhost:8080/test");
	Date expiry = new Date(2030, 1, 1);
	Cookie addedCookie = new Cookie("testcookie", "testvalue", "localhost:8080", "/", expiry, false, false);
	/* ... (see full test in zip file for assertions) */
	driver.manage().addCookie(addedCookie);
	Cookie retrievedCookie = driver.manage().getCookieNamed("testcookie");
	/* ... (see full test in zip file for assertions) */
}
```

I'm not quite sure whether this is a problem in selenium or in chromedriver; it's also unclear why the cookie cannot be set (the chromedriver log just says `RESPONSE AddCookie ERROR unable to set cookie`).

ZIP file with runnable test case: [Test_AddCookie_Java.zip](https://github.com/SeleniumHQ/selenium/files/3630971/Test_AddCookie_Java.zip)

Use `ant -Dchromedriverversion=2.44` to run the test case with chromedriver 2.44, or `ant` to use chromedriver 77.0.3865.40. Pass `-Dchromedriverplatform=…` to use `linux64` or `win32` if not using `mac64`.

## Environment

OS: macOS 10.13.6
Browser: Chrome
Browser version: 77.0.3865.90
Browser Driver version: chromedriver 2.44 and 77.0.3865.40
Language Bindings version: selenium-java-3.141.59

**Comment by cgoldberg** [comment]
see: https://bugs.chromium.org/p/chromium/issues/detail?id=56211

this is because Chrome won't allow cookies to be set on `localhost`.  You can use a valid domain name or localhost's IP address instead.

**Comment by Rinzwind** [comment]
> this is because Chrome won't allow cookies to be set on localhost. You can use a valid domain name or localhost's IP address instead.

But the test does work when using the older chromedriver 2.44?

I expected this to have something to do with the change to the W3C WebDriver protocol, but I wasn't sure whether it's because the Java-bindings are using the protocol incorrectly or whether chromedriver 77 is applying it incorrectly. (It doesn't help that the section about cookies seems to be missing from the W3C spec: there's a section “16. Cookies” in the table of contents, but in the text, [section 15.2.2](https://www.w3.org/TR/2018/REC-webdriver1-20180605/#execute-async-script) is immediately followed by [section “17. Actions”](https://www.w3.org/TR/2018/REC-webdriver1-20180605/#actions).)

Why does Chromium issue 56211 apply when using chromedriver 77 but not when using chromedriver 2.44?
