### ISSUE TITLE
Safari The command 'GET /session/:sessionId/log/types' was not found

### ISSUE THREAD

**Issue by Pratish89** [SeleniumHQ/selenium#7580]
## 🐛 Bug Report

Selenium: 3.141.59

`The command 'GET /session/7AC1E560-B662-400E-B403-D2780E2B4FC0/log/types' was not found. Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'Pratish-Patel-Mac.local', ip: 'fe80:0:0:0:18f5:f9d9:4106:1738%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_161' Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.1.2, javascriptEnabled: true, platform: MAC, platformName: MAC, safari:automaticInspection: false, safari:automaticProfiling: false, safari:diagnose: false, setWindowRect: true, strictFileInteractability: false, webkit:WebRTC: {DisableICECandidateFiltering: false, DisableInsecureMediaCapture: false}} Session ID: 7AC1E560-B662-400E-B403-D2780E2B4FC0
`

Getting error while running test in safari 12.1.2
Selenium version v3.141.59

**Comment by jimevans** [comment]
The Safari driver adheres to the W3C WebDriver Specification, which does not include the `log` endpoints. Those are only available in the driver for Chrome. This is not a bug in Selenium; it’s a lack of implementation in Apple’s driver for Safari.

**Comment by Pratish89** [comment]
Thanks @jimevans

**Comment by Pratish89** [comment]
@jimevans how can I bypass this while running the test safari?
