### ISSUE TITLE
Selenium - JAVA

### ISSUE THREAD

**Issue by Misbah19-ops** [SeleniumHQ/selenium#7583]
Hi ,

Im trying to automate mobile using appium. i have been caught under swipe down and swipe up.

Below is my code and i get error as ad cast to dr. Please help

				int ScreenWidth = dr.manage().window().getSize().getWidth();
				int ScreenHeight = dr.manage().window().getSize().getHeight();

				int startx = ScreenWidth/2;
				int endx = ScreenWidth/2;
				int starty = ScreenHeight*6/7;
				int endy = ScreenHeight/7;
				
			
				dr.swipe(startx, starty, endx, endy);

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
