### ISSUE TITLE
Upgrade childprocess gem to 3.0

### ISSUE THREAD

**Issue by aidistan** [SeleniumHQ/selenium#7586]
## 🚀 Feature Proposal

This issue is similar to #7387 since `childprocess` gem has recently released 3.0.0 version.

## Motivation

I have tried and failed to install this gem offline on Windows platform. Through an investigation, I found it was caused by `childprocess` which always tries to install a dependency on Windows through network access and reported it in enkessler/childprocess#158.

## Example

...

**Comment by connorshea** [comment]
This is also now necessary to upgrade to Rake 13 :)
