### ISSUE TITLE
Enable TLS support for Jetty

### ISSUE THREAD

**Issue by 4x0v7** [SeleniumHQ/selenium#7588]
## 🚀 Feature Proposal

Enable the Selenium hub to serve traffic over TLS using a defined PEM certificate and key file

## Motivation

As good security practice, exposing services over HTTP is discouraged. Enabling HTTPS will allow users to configure a certificate to validate communication with the hub

## Example

Deploying a Selenium hub server within a cloud provider (or container) and making it accessible via HTTPS

**Comment by 4x0v7** [comment]
I'm working in implementing this, my thinking is to add some options to the [BaseServerFlags](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/grid/server/BaseServerFlags.java) to enable SSL. `--ssl` as a boolean, then `--sslcert` and `--sslkey` to be passed as paths to PEM files. PEM is my preference over a jks keystore file as the user doesn't have to generate a jks themselves. We can use a sane default for the certificate name inside the generated jks which will get passed to Jetty's `SslContextFactory.setKeyStore`.

Would appreciate any feedback or suggestions on alternative approaches!

**Comment by barancev** [comment]
We are going to migrate from jetty to netty, so please don't add new features related to jetty.
