### ISSUE TITLE
Internet Explorer Driver doesn't have an option to set the User-Agent

### ISSUE THREAD

**Issue by tarlabs** [SeleniumHQ/selenium#759]
Currently there is no option for setting the user agent for a IE Browser.

@jimevans, Is it possible to use `UrlMkSetSessionOption` listed on the below URL?

https://msdn.microsoft.com/en-us/library/ms775125(v=vs.85).aspx

This needs to be executed inside the browser at startup, so I assume there is some kind of hook we have which can actually execute this. Any thoughts on this?

**Comment by jimevans** [comment]
You're right, that would have to be executed inside the browser, but such a feature is out of scope for the IE driver. There are two reasons for this. First, the WebDriver API doesn't provide any mechanism for setting the user agent string. Second, the browser itself doesn't provide any UI to the user allowing the user to set it.

Given this, I'm not sure I entirely buy the use case of changing the user agent string, but if you wanted to implement something like this on your own, you'd want to use a technique similar to that used to set the so-called "per-process" proxy in the IE driver. You'd need a Windows hook function, in a DLL, which hooks the window procedure of the IE content process. The hook procedure would need to handle a custom message, which you would define, that would set the user agent via `UrlMkSetSessionOption`. From your code, install the hook, then use `SendMessage` to fire off your hook procedure, and Bob's your uncle. Note carefully, that your DLL (and it _must_ be a DLL) will probably need to be written using C/C++. Managed languages like C# and Java don't produce artifacts that play nicely with the Windows API.

**Comment by tarlabs** [comment]
@jimevans, "Second, the browser itself doesn't provide any UI to the user allowing the user to set it."

That's not entirely true, IE developer tools provide and option to change the User Agent settings

**Comment by jimevans** [comment]
Be that as it may, it doesn't change my view of this being out of scope.
