### ISSUE TITLE
MoveTargetOutOfBoundsException on Firefox

### ISSUE THREAD

**Issue by umarambh** [SeleniumHQ/selenium#7591]
MoveTargetOutOfBoundsException is occurring in more recent times when used in Drag and drop scenario. This exception started to observed first with vertical movement and slowly with horizontal drag and drop actions too. Wanted someone to look into.
Error description:- MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847).
Also checked to make sure browser window is maximized, Firefox version 69.0, OS tested on : Mac OS 10.14.5 and Linux.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. If we dont have that then it is impossible for us to reproduce. Think what would you need to be able to debug an issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
