### ISSUE TITLE
Firefox -MoveTargetOutOfBoundsException

### ISSUE THREAD

**Issue by umarambh** [SeleniumHQ/selenium#7592]
MoveTargetOutOfBoundsException is occurring in more recent times when used in Drag and drop scenario. This exception started to observed first with vertical movement and slowly with horizontal drag and drop actions too. Wanted someone to look into.
Error description:- MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847).
Also checked to make sure browser window is maximized, Firefox version 69.0, OS tested on : Mac OS 10.14.5 and Linux.
This was absolutely working fine without issue. No upgrades have been done to the environment.

## To Reproduce
=========

1) Open firefox latest version on Linux or Mac OSX( tested on 10.14.x) version
2) Open AUT, browser maximized
3) Using RFSelenium library trying to move an element  horizontally or vertically with keyword Dragdrop by offset  $locator xoffset  yoffset
4) Get MoveTargetOutOfBoundsException with outbounds viewport width xxx and height xxx

Behaviour is see: Error i see:MoveTargetOutOfBoundsException: Message: (1428, 545) is out of bounds of viewport width (1152) and height (847)

## Environment
Mac OSX 10.14.x, Linux CentOS 7.6.1810 AWS EC2
Env: Robot Framework 3.1.2 ,Python 3.7.1 on linux,Selenium 3.14.0,

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by umarambh** [comment]
Environment:- Robot Framework 3.1.2 ,Python 3.7.1 on linux,Selenium 3.14.
Scenario is :
1) Login into the application
2) Navigate to a certain point for the dragdrop scenario 
a) Have to Drag Drop using Robotframework Selenium keyword -DragDrop by offset  $locator xoffset yoffset

eg:- I)Horizontal element dragdrop event.
In below example trying to Dragdrop element OPPONENT to re-arrage columns to next position.
<img width="412" alt="Screen Shot 2019-09-27 at 8 33 52 AM" src="https://user-images.githubusercontent.com/41133491/65774601-319cf700-e104-11e9-9e92-6ee7c728554d.png">

Expected output:
<img width="857" alt="Screen Shot 2019-09-27 at 8 41 31 AM" src="https://user-images.githubusercontent.com/41133491/65774689-6741e000-e104-11e9-97da-3d396f9b56fb.png">

II)Have a similar scenario to re-arrange Pages (1) and (2)  in below 
<img width="93" alt="Screen Shot 2019-09-27 at 8 34 49 AM" src="https://user-images.githubusercontent.com/41133491/65774769-8c365300-e104-11e9-84ed-406cd04c61e2.png">

**Comment by barancev** [comment]
Please provide an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by AutomatedTester** [comment]
Closing as requested information not given
