### ISSUE TITLE
WebDriverWait throwing null pointer exception with ChromeDriver v.77.0.3865.40

### ISSUE THREAD

**Issue by dbaldwin103** [SeleniumHQ/selenium#7593]
I recently updated chrome driver to use the latest release version 77.0.3865.40. I noticed that all my waits have started to throw a null pointer exception the second it runs this line: 

	    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("header")));

I did a bit of debugging and found that it specifically won't work for ExpectedConditions.visibilityOfElementLocated and a few other methods in the ExpectedConditions class. The only method that seemed to work was  ExpectedConditions.presenceOfElementLocated but I need to be able to check to see if that element is visible to the user and not just present in the markup. 

Here's the code: 

	public static void main(String args[]) {
		
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\bdqin\\Downloads\\chromedriver_win32_77_0_3865_40\\chromedriver.exe");
		
		WebDriver driver = new ChromeDriver();
		
		WebDriverWait wait = new WebDriverWait(driver, 20);

		driver.get("https://my-site.com/");
		
	       driver.manage().deleteAllCookies();
	    
	       wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("header")));
		
		
	}

Also to note I tried to do a work around for this by just implicitly waiting using this line below but even this doesn't seem to work properly either. It just ignores the timeout. 

		    driver.manage().timeouts().implicitlyWait(seconds, TimeUnit.SECONDS);

**Comment by Julioevm** [comment]
I'm running against the same issue. Are you using the windows chromedriver?

**Comment by dbaldwin103** [comment]
Yes. I'm using Chromedriver. Do you have any clues as for why this may be happening? I also looked at ExpectedConditions documentation and it doesn't say that visibilityofElementLocated is deprecated. Either way, the waits in general seemed to either get ignored or a null pointer exception is thrown.

**Comment by andrey-dyachenko** [comment]
have the same issue on OS X and Chromedriver 77.0.3865.40 and 77.0.3865.10
in Chromedriver 76.0.3809.126 works fine

**Comment by dbaldwin103** [comment]
I also posted this on the Chromedriver issues list the id is 3147: 

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3147&can=2&q=3147&colspec=ID%20Status%20Pri%20Owner%20Summary&sort=-id

**Comment by dbaldwin103** [comment]
As mentioned before I had added this to the Chromedriver issues list, the id is 3147. Click this link if you want the full resolution: 

https://bugs.chromium.org/p/chromedriver/issues/detail?id=3147&can=2&q=3147&colspec=ID%20Status%20Pri%20Owner%20Summary&sort=-id

It was mentioned that this issue was fixed with the most recent Chromedriver v.78.0.3904.11. 
So first I had to download Chromedriver v.78.0.3904.11 and then I had to set up the new path to go the Chromedriver executable for version 78: 

System.setProperty("webdriver.chrome.driver", "C:\\Your\\Path\\To\\ChromeDriverExecutable\\chromedriver.exe");

Once, that is done. You will need to download Chrome beta to use the beta version of Chrome 78. You can download the beta version here: 

https://www.chromium.org/getting-involved/dev-channel

Once your there, you should download the beta channel for whichever operating system that you are on. I'd suggest reading the bottom section about backing up the default folder of the chrome channels. 

After creating backup folders for your stable and beta channel, you will need to add a couple of lines to your program to get Selenium to route to the Chrome that is beta. You will need to import org.openqa.selenium.chrome.ChromeOptions into your program in order for this to work. Then, add these three lines into your program: 

ChromeOptions options = new ChromeOptions();
options.setBinary("\\path\\to\\chrome\\executable");
WebDriver driver = new ChromeDriver(options);

In the options.setBinary() line, you will need to add the path to the beta chrome executable. I found the path for mine, by right clicking the beta executable on my desktop screen and clicking 'Open file location.' In the folder, you should see the chrome application. Right click and select properties and then copy the location. Copy that into options.setBinary, and don't forget to have chrome.exe at the end of the file path. 

Once, I made these changes the Null Pointer Exceptions disappeared and now my program is running smoothly again. 

I've attached my finished file to help:

[test_expected_conditions.zip](https://github.com/SeleniumHQ/selenium/files/3655111/test_expected_conditions.zip)

**Comment by farheenahmad** [comment]
thank you guys for such insight and the solution, i have wasted my 2 weeks just to get what exactly the issue is :(
