### ISSUE TITLE
Inconsistent behavior of IE in WebdriverJS

### ISSUE THREAD

**Issue by qankp** [SeleniumHQ/selenium#7594]
I have multiple JavaScript tests created that use the chromedriver to run tests in Chrome and I now want to run the same tests IE. But its not working
IE version is 11.0.9600 and IEdriver version is 3.14
Configuration done is as below:
1.Zoom is set to 100%
2. Protected Mode settings for each zone have the same value
3, window 7 ,selenium 3.14,ie 11 and 64 bit
4.capabilities added:
		base_capabilities = webdriver.Capabilities.ie();
                base_capabilities.set('ignoreProtectedModeSettings', true);
                base_capabilities.set('introduceFlakinessByIgnoringProtectedModeSettings', true);
                base_capabilities.set('ignoreZoomSetting', true);
                base_capabilities.set('requireWindowFocus', true);				
                         
behavior
1. Case 1: It launches local host only ex:-http://localhost:42884/(every time local host value is random )
This is the initial start page for the WebDriver server(ie screen ).After that it does not proceed.
2. Case 2: It launches the application url but does not proceed after that.
WebDriverError: java.net.ConnectException: Connection refused: connect
(node:8824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: java.net.ConnectException: Connection refused: connect
(node:8824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
3. Case 3: It launches the application URL and start typing username characters one by one.It is very slow while entering characters. After entering password it fails.

NOTE: all these scenarios are working fine in chrome and Firefox.

**Comment by barancev** [comment]
I can't see any issue report here. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
