### ISSUE TITLE
Cannot Set Cookies on Chrome Browser 77 and ChromeDriver 77.0.3865.40

### ISSUE THREAD

**Issue by deepticake** [SeleniumHQ/selenium#7596]
Description: Cannot set Cookies.

The Error thrown on running the test:
```
UnableToSetCookieError: unable to set cookie
  (Session info: chrome=77.0.3865.75)
    at Object.throwDecodedError (/usr/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/app/node_modules/selenium-webdriver/lib/http.js:563:13)
    at Executor.execute (/usr/app/node_modules/selenium-webdriver/lib/http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async thenableWebDriverProxy.execute (/usr/app/node_modules/selenium-webdriver/lib/webdriver.js:699:17)
    at async loginWithRoles (/usr/app/features/support/pages/common.js:16:3)
```

## Expected behavior

The cookies should be set.

## Test script or set of commands reproducing this issue

```
await driver.get('http://web-server:3000')
  await driver.manage().addCookie({
    name: 'token',
    value: tokenValue,
    httpOnly: true,
    domain: 'web-server',
    path: '/',
    secure: false
  })
  await driver.get('http://web-server:3000')
  return driver.manage().window().setRect({width: 1920, height: 3000})
```

## Environment

OS: macOS:10.12 and Linux 
Browser: Chrome
Browser version: 77.0.3865.90
Browser Driver version: ChromeDriver 77.0.3865.40
Language Bindings version: Javascript
selenium-webdriver version: 4.0.0-alpha.5

**Comment by jmfadeley** [comment]
Similar issue on Windows 10. Triaging, my guess is driver 77.0.3865.90 is not found on https://chromedriver.storage.googleapis.com, which in my case `webdriver-manager` is pinging for the latest.

**Comment by deepticake** [comment]
I am visiting the domain using: `await driver.get('http://web-server:3000')` before trying to set-up the cookies.

These tests have been working fine until Chrome 77 and the supporting webDriver was released.

**Comment by robin-salih-fluke** [comment]
> I am visiting the domain using: `await driver.get('http://web-server:3000')` before trying to set-up the cookies.
> 
> These tests have been working fine until Chrome 77 and the supporting webDriver was released.

Yes I have the exact same problem, worked fine until I updated chrome/chromedriver, now getting this error.

**Comment by deepticake** [comment]
I resolved this issue by not adding `domain` while generating the tokens.

I had raised a bug with the chrome-driver team as well: 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3141
