### ISSUE TITLE
Selenium JAR v4.0.0-alpha-2 doesn't work with path specified in webdriver.edge.logfile 

### ISSUE THREAD

**Issue by abhijeetps** [SeleniumHQ/selenium#7597]
## 🐛 Bug Report

Selenium JAR v4.0.0-alpha-2 doesn't open EdgeHTML based Edge when `webdriver.edge.logfile` path is specified while running JAR.

## To Reproduce
When I try to open Microsoft Edge using MicrosoftWebDriver with Selenium JAR v4.0.0-alpha-2, and passing path of where it has to save Edge Driver logs(webdriver.edge.logfile), the driver doesn't run (Or Selenium JAR is unable to open MicrosoftWebDriver). 

Detailed steps to reproduce the behaviour:

## Expected behaviour

Let the path to MicrosoftWebDriver be _C:\path\to\driver\MicrosoftWebDriver.exe_.
And let the path to Selenium v4.0.0-alpha-2 JAR be _C:\path\to\jar\selenium-server-standalone-4.0.0-alpha-2.jar_.
Also, let the path where I want to save log be _C:\path\to\logfile\logfile.log_

Now, when I create a session using Selenium JAR with the following command:

:x: (Doesn't work as it is expected to) 
`java -Dwebdriver.edge.driver="C:\path\to\driver\MicrosoftWebDriver.exe" -Dwebdriver.edge.logfile="C:\path\to\logfile\logfile.log" -jar C:\path\to\jar\selenium-server-standalone-4.0.0-alpha-2.jar`

and then try to create a session by sending a request for the same, the webdriver doesn't open the Edge(EdgeHTML) Browser as it was expected.

However, when I follow the same by removing the log file, it opens the browser as it was expected when sending a request to create a session.

✅ (Works as expected to)
`java -Dwebdriver.edge.driver="C:\path\to\driver\MicrosoftWebDriver.exe" -jar C:\path\to\jar\selenium-server-standalone-4.0.0-alpha-2.jar`

**The first command doesn't run the MicrosoftWebDriver and the second one after removing flag for logFile works smoothly as expected.**

Facing this issue in case of 4.0.0-alpha-2. It works file with 4.0.0-alpha-1. (Maybe because of support of Chromium Based Edge)

## Test script or set of commands reproducing this issue

Not dependent on any test script.

## Environment

OS:  Windows 10
Browser:  Edge (EdgeHTML)
Browser version:  (tried on 41, 42, 43)
Browser Driver version:  MicrosoftWebDriver.exe v6.17134
Language Bindings version:  Ruby 3.141.0
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
Can you please try 4.0.0-alpha-3?
It has a new CLI so please run it with --help option to learn the new CLI.
And client libraries should connect to http://server:4444/ instead of http://server:4444/wd/hub/ now.

**Comment by abhijeetps** [comment]
Yes, I will check and will let you know.

**Comment by AutomatedTester** [comment]
Closing as information asking was not given
