### ISSUE TITLE
OpenQA.Selenium.WebDriverException : javascript error: Promise.resolve is not a function (Session info: chrome=77.0.3865.90)

### ISSUE THREAD

**Issue by nskliarov** [SeleniumHQ/selenium#7598]
Description:
Unable to Find element by Id:
This code works with Selenium.WebDriver.ChromeDriver Version 76:

var myUrl = "https://loginpage";
driver.Navigate().GoToUrl(myUrl);
var a = driver.FindElements(By.Id("username"));

The Error thrown on running the test:
Message: 
    OpenQA.Selenium.WebDriverException : javascript error: Promise.resolve is not a function
      (Session info: chrome=77.0.3865.90)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.FindElements(String mechanism, String value)

Expected behavior:
javascript error: Promise.resolve should not appear

Environment:
Browser: Chrome
Browser version: 77.0.3865.90
Browser Driver version: ChromeDriver 77.0.3865.4000

**Comment by barancev** [comment]
Please report this issue to chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
