### ISSUE TITLE
Unable to run webdriverio tests on IE11 using selenium grid

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7604]
**Environment:** 
**WebdriverIO version:** 5.11.0 
**Mode:** WDIO Testrunner (sync) 
**Browser name and version:** IE 11 
**Host machine:** Mac 10.13.6
 **Windows machine:** 64 bit windows server 2019 
**selenium standalone:** selenium-server-standalone-3.141.59.jar
 **IE driver:** 32 bit 3.14.0
**Config of WebdriverIO:**
  host: 'windows machine ip',
  port: 4444,
  path: '/wd/hub',
  specs: [`${pathToTests}*.js`],
  deprecationWarnings: false,
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'internet explorer',
      version: 11,
      platform: 'WINDOWS', 
      platformName: 'WINDOWS',
      logLevel: debug,
      'se:ieOptions': {
        'ie.ensureCleanSession': true,
        ignoreZoomSetting: true,
        ignoreProtectedModeSettings: true
      }
    }
  ]
sync: true,
**Issue Description:**
 Unable to execute webdriverio tests on IE using selenium grid. The browser itself is not launched.
My application is running locally on mac host port 3000. From Mac host, I have established reverse ssh tunnel to a windows machine hosted on aws.
I tested successfully that there is no issue with ssh tunnel since I can access my application on port 3000 inside windows machine. selenium grid is launched on windows machine.
When I trigger tests from my local mac host, I see an exception inside selenium hub.
**Selenium hub logs:** 
2019-09-26 12:48:17.446:WARN:osjs.HttpChannel:qtp21880137-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"internet explorer","version":11,"platform":"WINDOWS","platformName":"WINDOWS","se:ieOptions":{"ie.ensureCleanSession":true,"ignoreZoomSetting":true,"ignoreProtectedModeSettings":true}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"internet explorer","version":11,"platform":"WINDOWS","platformName":"WINDOWS","se:ieOptions":{"ie.ensureCleanSession":true,"ignoreZoomSetting":true,"ignoreProtectedModeSettings":true}}}

**Selenium hub config:**
browserTimeout: 0

debug: false

host: 172.31.31.173

port: 5555

role: node

timeout: 1800

cleanUpCycle: 5000

maxSession: 5

capabilities: Capabilities {browserName: internet explorer, platform: WINDOWS, platformName: WINDOWS, seleniumProtocol: WebDriver, server:CONFIG_UUID: b626910a-b79d-4d5d-a431-87d..., version: 11}

downPollingLimit: 2

hub: http://localhost:4444/grid/register

id: http://172.31.31.173:5555

nodePolling: 5000

nodeStatusCheckTimeout: 5000

proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy

register: true

registerCycle: 5000

remoteHost: http://172.31.31.173:5555

unregisterIfStillDownAfter: 60000

**Expected behavior :** 
IE browser should get launched on running test

**Actual behavior:** 
 Getting the exception mentioned above.

Any idea what could be the reason behind the exception?

**Comment by barancev** [comment]
Please report this issue to webdriver.io project.
