### ISSUE TITLE
How to launch chrome with performance logging using Ruby and Selenium Capybara

### ISSUE THREAD

**Issue by glebsonik** [SeleniumHQ/selenium#7605]
## 💬 Questions and Help

After I try to launch `
Capybara.register_driver(:selenium_mobile) do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_emulation(device_name: 'iPhone X')
  options.add_option(:perfLoggingPrefs, {enableNetwork: true})
  cps = Selenium::WebDriver::Remote::Capabilities.chrome(loggingPrefs: {browser: 'ALL'},
                                                           perfLoggingPrefs: {enableNetwork: true}
    )
  Capybara::Selenium::Driver.new(app, browser: :chrome, desired_capabilities: cps, options: options)
end
` to start logging in Chrome session, but i got message:

Selenium::WebDriver::Error::InvalidArgumentError: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: perfLoggingPrefs specified, but performance logging was not enabled

I have tried plenty of different variants, but any of them can fix this issue. Is there any way to luanch ruby with enabled Chrome logging of Network tab?

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
