### ISSUE TITLE
Allow usage of rubyzip 1.3.0 and 2.0.0

### ISSUE THREAD

**Issue by vtamara** [SeleniumHQ/selenium#7606]
## 🐛 Bug Report

In this moment requires rubyzip 1.2.x that has security problems.

## To Reproduce

Include the gem in a project that requires a recent rubyzip and run
bundle install

## Expected behavior

Allow using recent rubyzip

## Test script or set of commands reproducing this issue

In same Gemfile use:
```
gem 'rubyzip', '>= 1.3'
gem 'selenium-webdriver'
```

And run:
```
bundle update
```
It produces
```
Bundler could not find compatible versions for gem "rubyzip":
  In Gemfile:
    rubyzip (>= 2.0)

...
selenium-webdriver (>= 4.0.0.alpha3) was resolved to 4.0.0.alpha3, which
depends on
      rubyzip (~> 1.2, >= 1.2.2)
```
## Environment

OS: Any
Browser: Any
Browser version: Any
Browser Driver version:Any
Language Bindings version: Any 
Selenium Grid version (if applicable): Any

**Comment by snowblink** [comment]
Is it possible to get a 3.142.4 patch for this released on rubygems?

**Comment by p0deje** [comment]
I'll cut a release later today.

**Comment by p0deje** [comment]
selenium-webdriver 3.142.5 was released.
