### ISSUE TITLE
Generate javadocs

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7609]
The bazel builds should allow a javadoc jar to be generated.

**Comment by diemol** [comment]
This has been moved to "Done" in the Selenium 4 [project](https://github.com/SeleniumHQ/selenium/projects/2), the work was done via https://github.com/SeleniumHQ/selenium/commit/fbb253ff52dc5b1ae771688e712f0e89b29be29f

Feel free to reopen if something is still missing
