### ISSUE TITLE
driver.manage().getCookies() does not return cookies for active iframe, returning cookies from defaultContent()

### ISSUE THREAD

**Issue by evgenybf** [SeleniumHQ/selenium#7614]
## 💥 Regression Report

Selenium ignores selected iframe and always returns cookies for the document itself: According to this ticket, it used to work in the past:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7799

## Steps to reproduce

Open a site with iframe, switch to the iframe, get the list of cookies.

Current behavior:
get_cookies() returns cookies for the default content.

Expected behavior:
get_cookies() is expected to return cookies for the active content (iframe).

## Script to reproduce

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

browser = webdriver.Chrome()

browser.get("https://service.nemid.nu/dk-en/#log_paa_selvbetjening")
input("(page loaded) Press any key")

print(browser.get_cookies())  # OK - cookies for DefaultContent

elem = browser.find_element_by_id('nemid_iframe')

browser.switch_to.frame('nemid_iframe') # or frame(elem)

print(browser.get_cookies()) # ERROR - cookies for DefaultContent. Expected iframe cookies
````
I expected to see JSESSIONID for domain 'applet.danid.dk' among the cookies, but it never appeared. 

## Environment

OS:  Windows 10
Browser: Chrome, Firefox
Browser version: Chrome 77.0.3865.90, Firefox 69.0.1, 
Browser Driver version: ChromeDriver 77.0.3865.40, GeckoDriver 0.25.0
Language Bindings version: Python 3.141.0, ..Net Selenium.WebDriver 3.141.0, Selenium.WebDriver 3.11.0

**Comment by evgenybf** [comment]
![image](https://user-images.githubusercontent.com/1589970/65817520-95ace180-e210-11e9-93a6-d0cdd50c12a1.png)

**Comment by evgenybf** [comment]
![image](https://user-images.githubusercontent.com/1589970/65817527-bffe9f00-e210-11e9-963a-90717afdc3f0.png)

**Comment by barancev** [comment]
I saw you reported this issue to chromedriver
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3153

And this is a known issue for geckodriver too, follow
https://github.com/mozilla/geckodriver/issues/1104
