### ISSUE TITLE
why ? Deprecated Class LegacyTouchSequence

### ISSUE THREAD

**Issue by jiriyao** [SeleniumHQ/selenium#7617]
Deprecated. This class is strongly deprecated and will be removed once Google's Chrome and Microsoft's Edge browsers support the new action sequence API.

What that  mean? can't use LegacyTouchSequence? and is driver.input do not public method about touch?

how i can moblie touch for browser?
thks

**Comment by barancev** [comment]
### Please note that this issue tracker is not a help form.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
