### ISSUE TITLE
showModalDialog (IE) and isDisplayed() throws NullPointerException

### ISSUE THREAD

**Issue by Varro88** [SeleniumHQ/selenium#7619]
## 🐛 Bug Report

For modal window that is opened by window.showModalDialog in IE (other browsers don't support it) it's possible to find WebElements, but calling isDisplayed() method throws NullPointerException. Other methods like getTagName() are ok.
isDisplayed() is called in some ExpectedConditions, so it leads to problems with WebDriverWaits

## To Reproduce

1. Open in IE html page with **"window.showModalDialog"** in javascript for this page.
2. Fire event to call this function (e.g. button click).
3. Switch to modal window.
4. Find any WebElement and call isDisplayed() method for it.

## Expected behavior

isDisplayed() returns true/false, does not throw exception.

## Test script or set of commands reproducing this issue

As jsfiddle and similar web-sites don't support IE. [https://jsbin.com/royexapiwo/1/edit](https://jsbin.com/royexapiwo/1/edit) can be used by click() need to be done manually.

```html
<html>
  <head>
    <script language="JavaScript">
      function openWindow() {
        var myArguments = new Object();
        window.showModalDialog("https://www.seleniumhq.org/", '', '');
      }
    </script>
  </head>
  <body>
      <button onclick="openWindow();">Open window</button>
  <body>
</html>
```

``` java
WebDriver driver = new InternetExplorerDriver();

driver.get("https://jsbin.com/royexapiwo/1/edit"); //supports IE but click() need to be done manually 
String mainWindowHandle = driver.getWindowHandle();
driver.switchTo().frame("<proxy>").switchTo().frame("JS Bin Output ");
WebElement button = driver.findElement(By.tagName("button"));
button.click();

List<String> handles = new ArrayList<String>(driver.getWindowHandles());
if(mainWindowHandle.equals(handles.get(0))) {
	driver.switchTo().window(handles.get(1));
}
else {
	driver.switchTo().window(handles.get(0));
}
System.out.println(driver.findElement(By.cssSelector(".downloadBox")).getTagName()); //pass
System.out.println(driver.findElement(By.cssSelector(".downloadBox")).isDisplayed()); //fail
```

## Environment

OS: Win7, Win10
Browser: Internet Explorer
Browser version: 11.0.9600.19463
Browser Driver version: 3.14.0.0
Language Bindings version: Java 3.141.59

## StackTrace

```
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)
	at ModalTest.modalIE(ModalTest.java:31)
```

## Failed method in Selenium

```java
    public boolean isDisplayed() {
        Object value = this.execute("isElementDisplayed", ImmutableMap.of("id", this.id)).getValue();

        try {
            return (Boolean)value; // <------ NullPointerException
        } catch (ClassCastException var3) {
            throw new WebDriverException("Returned value cannot be converted to Boolean: " + value, var3);
        }
    }
```

**Comment by barancev** [comment]
Please upgrade IEDriverServer, I've reproduced this issue with the driver version 3.14.0, but checked that version 3.141.5.13 works well.
