### ISSUE TITLE
Release 3.141.59 not available in PyPI

### ISSUE THREAD

**Issue by gtirloni** [SeleniumHQ/selenium#7623]
## 🐛 Bug Report

3.141.59 was released but it was not uploaded to PyPI

## To Reproduce

https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.141.59
https://pypi.org/project/selenium/3.141.59/

## Expected behavior

All stable releases (including bug fixes) are uploaded to PyPI.

**Comment by AutomatedTester** [comment]
There were no meaningful changes to python that warranted a new release.
