### ISSUE TITLE
Status code 64 : Running Selenium without GUI

### ISSUE THREAD

**Issue by ortizbje** [SeleniumHQ/selenium#7627]
I'm trying to run Selenium in `Headless mode` in a Linux machine without GUI. The problem is that I'm getting a WebDriverException and I can't find anywhere what the `status code 64` means.

Does anyone know where to find the status code definitions ?

Code : 
```python
from pyvirtualdisplay import Display
from selenium import webdriver

display = Display(visible=0, size=(1024, 768))
display.start()

path = '/home/workspace/geckodriver'
driver = webdriver.Firefox(executable_path=path, service_args=['--verbose', '--log-path=/tmp/firefox.log']) 

# website testing functionality: 
driver.get('https://python.org') 
print(driver.title)
```
Error : 
`WebDriverException: Message: Service /home/workspace/geckodriver unexpectedly exited. Status code was: 64`

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
