### ISSUE TITLE
extending text_to_be_present_in_element_value functionality

### ISSUE THREAD

**Issue by LilyNatsuyuki** [SeleniumHQ/selenium#7628]
## 🚀 Feature Proposal

extend the functionality of `text_to_be_present_in_element_value` to not only check the attribute "value", but any attribute. 

## Motivation

I'm currently automating a webpage, where the title of an image changes from "in work" to "finished". `text_to_be_present_in_element_value` would be exactly what I need, if I just could change "value" to the attribute "title"

## Example

As I'm using python, I added following class: 

```
 class text_to_be_present_in_element_attribute(object):
 	"""
 	An expectation for checking if the given text is present in the elements attribute
 	locator, attribute, text
 	"""
 	def __init__(self, locator, attribute_, text_):
 		self.locator = locator
 		self.attribute = attribute_
 		self.text = text_
 	
 	def __call__(self, driver):
 		try:
 			element_text = _find_element(driver,
 										self.locator).get_attribute(self.attribute)
 			if element_text:
 				return self.text in element_text
 			else:
 				return False
 		except StaleElementReferenceException:
 				return False
```

So it can be called like: 
`WebDriverWait(client, 5).until(EC.text_to_be_present_in_element_attribute((By.XPATH, "//div[contains(text(), 'sending')]/../preceding-sibling::div/img"), "title", "finished"))`

**Comment by LilyNatsuyuki** [comment]
Another option of course would be, to just use "value" as default attribute in `text_to_be_present_in_element_value`. 
Like: 
'''
class text_to_be_present_in_element_value(object):
    """
    An expectation for checking if the given text is present in the element's attribute (default: value)
    locator, text, attribute="value"
    """
    def __init__(self, locator, text_, attribute="value"):
        self.locator = locator
        self.text = text_
        self.attribute = attribute

    def __call__(self, driver):
        try:
            element_text = _find_element(driver,
                                         self.locator).get_attribute(attribute)
            if element_text:
                return self.text in element_text
            else:
                return False
        except StaleElementReferenceException:
                return False
'''
Disclaimer: I have no idea about object oriented programming or python writing conventions, so please bear with me.

**Comment by Dude-X** [comment]
I am neutral about adding stuff to expected conditions, but the core maintainers will add it if you like, if you submit a pull request.

I would write:
```python
def text_to_be_present_in_element(locator, text, attribute='value'):
    def check_element_attribute_for_text(driver):
        try:
            element_text = _find_element(driver, locator).get_attribute(attribute)
            return element_text == text
        except StaleElementReferenceException:
            return False
    return check_element_attribute_for_text
``` 
This is succinct, and easier to understand as a closure.
