### ISSUE TITLE
Change chromedriver download links from Google Sites to actual domain link?

### ISSUE THREAD

**Issue by pbeart** [SeleniumHQ/selenium#7630]
## 🐛 Bug Report
In many places in the code, both in comments and in error messages, links are made to https://sites.google.com/a/chromium.org/chromedriver. It seems as though it would be more sensible to link to the actual Chromium website for this at https://chromedriver.chromium.org/, in case the chromedriver host changes and the URL is no longer valid. **I would be more than happy to fix and PR this but I want to check that it wouldn't be better to keep it as it is.**

## To Reproduce
n/a

## Expected behavior
Links should be made to https://chromedriver.chromium.org/, rather than https://sites.google.com/a/chromium.org/chromedriver

## Test script or set of commands reproducing this issue
https://github.com/SeleniumHQ/selenium/search?q=sites.google.com&unscoped_q=sites.google.com

## Environment
n/a

**Comment by JohnChen0** [comment]
Agreed. The official URL for ChromeDriver site is https://chromedriver.chromium.org/.

**Comment by pbeart** [comment]
Great, I can submit a PR on that shortly
