### ISSUE TITLE
isDisplayed throw Null Pointer - Chrome 77

### ISSUE THREAD

**Issue by Naumansh** [SeleniumHQ/selenium#7631]
## 🐛 Bug Report

isDisplayed method throws Null pointer exception sometimes which originates from RemoteWebDriver class. This issue specific to Chrome version 77.

There is no issue on Chrome version 76 and older.

#Reproduce:
Open any web page.
Call isDisplayed.

#Error Log:
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)
	at eyethink.automation.bots.actionsfactory.type.Is$Web.isDisplayed(Is.java:122)

#Environment:
OS: Windows 10/OSX
Browser: Chrome
Browser version: 77.0.3865.90 
Browser Driver version: ChromeDriver 77 (mac)
Language Bindings version: Java 3.141.59

**Comment by Szesan** [comment]
Same issue here: https://github.com/SeleniumHQ/selenium/issues/7619
and here: https://github.com/SeleniumHQ/selenium/issues/7641

**Comment by cgoldberg** [comment]
@Naumansh 
you are using ChromeDriver 2.43, which only supports Chrome versions 69-71.  Since you are using Chrome 77, please upgrade your Chromedriver to the matching version (v77) and try again.

**Comment by Szesan** [comment]
> @Naumansh
> you are using ChromeDriver 2.43, which only supports Chrome versions 69-71. Since you are using Chrome 77, please upgrade your Chromedriver to the matching version (v77) and try again.
I get null reference exceptions on displayed property when I use matching driver for chrome, ie
Chrome 77 with ChromeDriver 77: https://github.com/SeleniumHQ/selenium/issues/7641

**Comment by Naumansh** [comment]
@cgoldberg Yep using the latest one. That's my bad forgot to add new chromeDriver version. The issue is with lattest versions of both chrome browser and driver.

**Comment by Szesan** [comment]
Yep, same thing here. Latest ChromeDriver, latest Chrome see the result: https://github.com/SeleniumHQ/selenium/issues/7641

**Comment by oyablonskyi** [comment]
We faced with the same issue on 77 version of Chrome browser and driver

**Comment by barancev** [comment]
It's a chromedriver issue, please follow:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3123

I'll keep this issue open to track the status.

**Comment by oyablonskyi** [comment]
BTW, you can install Chrome 78 beta and bug will be gone.

**Comment by Naumansh** [comment]
@oyablonskyi Waiting for the final version of 78.

**Comment by barancev** [comment]
According to the chromedriver team the issue has been fixed in version 78, can you please check and confirm/reject this info?

**Comment by Naumansh** [comment]
@barancev Yes it is fixed in new version of chrome. Thanks to chromedriver and selenium team.
