### ISSUE TITLE
Add the response to the logs when executing a RemoteWebDriver command in Java

### ISSUE THREAD

**Issue by Valuuin** [SeleniumHQ/selenium#7632]
## 🚀 Feature Proposal

In the Java class RemoteWebDriver within the method:
`protected Response execute(String driverCommand, Map<String, ?> parameters)`

the execute command is wrapped around logs statements:

`log(sessionId, command.getName(), command, When.BEFORE);`
`response = executor.execute(command);`
`log(sessionId, command.getName(), command, When.AFTER);`

can this be changed to:

`log(sessionId, command.getName(), command, When.BEFORE);`
`response = executor.execute(command);`
`log(sessionId, command.getName(), response, When.AFTER);`

or something along these lines so we can see the result of the command being executed.

## Motivation

We can make a class that extends lets say AndroidDriver and then @Override the log method so we can use our own logging set up for test results.

**Comment by cgoldberg** [comment]
can you submit a PR?

**Comment by FernandaCG** [comment]
Hi! can I work on this?

**Comment by cgoldberg** [comment]
Go for it.  Please submit a new Pull Request.

**Comment by FernandaCG** [comment]
Hi! I made the pull request but I think that build failure doesn't seem related to my change.
