### ISSUE TITLE
Error in API frontpage

### ISSUE THREAD

**Issue by cefn** [SeleniumHQ/selenium#7635]
There is an error in the main usage example offered at https://seleniumhq.github.io/selenium/docs/api/javascript/index.html

```javascript
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();
```

There is a semicolon in the middle of the findElement line.

```javascript
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
```

**Comment by barancev** [comment]
It is already fixed in the code, documentation just to be regenerated and published to the site.

**Comment by camilstaps** [comment]
Related to #7558 then.

@barancev, do you have an overview of whether the JS bindings are being actively maintained?

**Comment by christian7877** [comment]
const {Builder, By, Key, until} = require('selenium-webdriver');

(async function example() {
  let driver = await new Builder().forBrowser('firefox').build();
  try {
    await driver.get('http://www.google.com/ncr');
    await driver.findElement(By.name('q'));.sendKeys('webdriver', Key.RETURN);
    await driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  } finally {
    await driver.quit();
  }
})();

**Comment by titusfortner** [comment]
The error has been fixed, the bigger issue is just getting the docs updated. Tracking here now: #10185
