### ISSUE TITLE
Can I start a web driver as service

### ISSUE THREAD

**Issue by aaronchen2k** [SeleniumHQ/selenium#7637]
I like to start a java thread to init the web driver,  then get the selenium script line by line from the soa remote request, and to run, is it possible? Thanks a lot!

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
