### ISSUE TITLE
Untested Commit with Syntax Error in Python Merged

### ISSUE THREAD

**Issue by tarunlalwani** [SeleniumHQ/selenium#764]
The below commit 

https://github.com/SeleniumHQ/selenium/commit/08882053

Was merged and it has python syntax error as well. I am not sure how it got missed. Any thoughts on this?

**Comment by tarlabs** [comment]
@lukeis, ping

**Comment by ddavison** [comment]
the merger most likely just looked at the travis build.  I think that Travis only compiles Java

**Comment by tarlabs** [comment]
@ddavison, can we get at least some kind of syntax check also added for the python stuff? We use python a lot and I would hate to every see a syntax error in the repo

**Comment by ddavison** [comment]
agreed.. it does happen though :)  someone looks at a merge, thinks it looks good and merges without compiling.  we've all done it.

**Comment by AutomatedTester** [comment]
Tarun, thanks for offering to get us up on Travis CI for Python. It's much appreciated! 






On Friday, 10 Jul 2015 at 13:52, Dj <notifications@github.com>, wrote:

agreed.. it does happen though :)  someone looks at a merge, thinks it looks good and merges without compiling.  we've all done it.

**Comment by tarlabs** [comment]
@AutomatedTester, I would be happy to help, though I may need some directions. Who would be the best person to get in touch with for the python bindings?

**Comment by AutomatedTester** [comment]
I am but Travis CI knowledge doesn't require Python knowledge to make it work. It's about generating the right matrix of tests



—

**Comment by cgoldberg** [comment]
:+1:  run flake8 or pylint on every push

**Comment by barancev** [comment]
We run flake8 on Travis CI now. Yes, it's not a pre-commit hook, but I think it's enough for our development speed and manner.
