### ISSUE TITLE
[Java] Enable OkHttp cookies

### ISSUE THREAD

**Issue by yunj** [SeleniumHQ/selenium#7646]
## 🚀 Feature Proposal

selenium-java-3.141.59 uses OkHttp client internally to execute HTTP commands. If a persistent cookies policy is enabled for OkHttp client, we could use AWS load balancer sticky session function.

## Motivation

We want to have an AWS load balancer sitting in front of a group of [selenoids](https://aerokube.com/selenoid/latest/) (similar to selenium hub), so the selenoid nodes can auto scale based on the running load.

## Example

OkHttp client is able to support cookie handling through some third-party dependency since version 3.0.0. If this request is useful, I'd like to raise a pull request.

**Comment by yunj** [comment]
@barancev Hi Alexei, I'm wondering if you have time to look at the proposal? Thank you very much.

**Comment by NoamGoren** [comment]
Hi @shs96c and @barancev ,
can @dratler  and me take this one ?

**Comment by yunj** [comment]
@barancev Hi Alexei, I'm wondering if you have time to look at the proposal? Thank you very much.

**Comment by barancev** [comment]
We don't use HttpOk in selenium v4, switched to a netty-based http client.
