### ISSUE TITLE
[selenium-webdriver] Need for a new version of selenium-webdriver

### ISSUE THREAD

**Issue by MaximeJEUSS** [SeleniumHQ/selenium#7648]
Hello,

We recently pushed this PR (https://github.com/SeleniumHQ/selenium/pull/7511). 
Could you please create a new selenium-webdriver version (alpha.6 ?) with this fix so that we could use this version in a project that use the selenium-webdriver dependency ? 

Thank you very much

**Comment by theredfish** [comment]
Hello,
Could we have a status about this issue? Just to know when we will have an official release to drop our forked library? Thank you!

**Comment by theredfish** [comment]
Hello,
Do you have any information please? @barancev / @shs96c

**Comment by theredfish** [comment]
Hi!
It's already merged in alpha-3 but Protractor use alpha-1. So @MaximeJEUSS you can close this issue ^^
