### ISSUE TITLE
Safari 6 takes screenshots only of the initial viewport

### ISSUE THREAD

**Issue by avietrov** [SeleniumHQ/selenium#765]
When using selenium 2.46 with Safari 6 on OS X 10.8, I get screenshots that do not correspond to the actual viewport. The following script supposed to take scroll and save screenshots. 
And the browser actually scrolls the page, but the resulting screenshots all look like the first one (at scroll: 0, 0)

```python
driver.get("http://wetter.com")
for i in range(0, 200, 20):
  driver.execute_script("window.scrollBy(0, " + str(i) + ");")
  driver.save_screenshot(str(i) + '.png')
```

**Comment by jleyba** [comment]
The current behavior complies with the W3C spec:

https://w3c.github.io/webdriver/webdriver-spec.html#take-screenshot

> The Take Screenshot command takes a screenshot of the top-level browsing context’s viewport.

**Comment by avietrov** [comment]
I believe screenshots in Chrome comply with the W3C spec, but not this case. In Chrome selenium indeed takes screenshots of the viewport, but the viewport can be modified by scrolling.
Safari 6, on the other hand, ignores scrolling position at all, that is even if I scroll to the very bottom of the page and take a screenshot, I still get screenshot of the viewport at the very top.

**Comment by jleyba** [comment]
In this case we are limited by the Safari extension API:

https://developer.apple.com/library/safari/documentation/UserExperience/Reference/SBrowserTabClassReference/index.html#//apple_ref/javascript/instm/SafariBrowserTab/visibleContentsAsDataURL
