### ISSUE TITLE
iframe that covers full screen causes hover to not work on a visible element outside iframe

### ISSUE THREAD

**Issue by LiChoi** [SeleniumHQ/selenium#7658]
## 🐛 Bug Report

When attempting to mouse hover over an element where there is an iframe that covers the entire screen, hovering will not work. The element is not within the iframe - it is within the main document. The element has a high z-index to force it to the very top layer so that it is visible. Hovering on manual testing works, but not when using Capybara + Selenium. 

## To Reproduce
Using ruby, Capybara + Rspec + Selenium

Create an html document with an iframe which covers the full screen. 
Create an element on the main document (outside the iframe) which triggers some other element to pop into view (opacity from 0 to 1) upon hovering. Give the element a high z-index to ensure it is at the top layer. 
Manually test to verify that the hover element is visible and hovering works on it. 
Write automation test using ruby, capybara and selenium, using chrome driver. Hover over the hover-element. Tell ruby to sleep for a few seconds so you can see that hover is not being triggered. 

Example can be found here:

https://jsfiddle.net/pwo7zuL2/1/

## Expected behavior
If manual hovering works, hovering using selenium should also work. 

## Test script or set of commands reproducing this issue
visit link 
find("#next").hover 
sleep(10)

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by twalpole** [comment]
This is because the element you're trying to hover on doesn't actually have any size on the page (0x0).
