### ISSUE TITLE
Grid: Verify incoming node registrations

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7663]
Include a key or certificate in the registration request that needs to be verified.

**Comment by diemol** [comment]
Closing as this was moved to "Done" in the Selenium 4 [project](https://github.com/SeleniumHQ/selenium/projects/2), the work was done via https://github.com/SeleniumHQ/selenium/commit/21246c9ae5f48e782653a8f58d4f86798d62da61.

Feel free to reopen if something is still missing.
