### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://cdmdfdgjgkdpjaagnhnianiklfiojfch/_generated_background_page.html

### ISSUE THREAD

**Issue by fengzifrank** [SeleniumHQ/selenium#7664]
When I use selenium to start chrome in win10 environment, it will load chrome plugin.
chromeOptions = webdriver.ChromeOptions()
chromeOptions.add_argument('--headless')
  Everything is normal, but with this sentence, I will report an error. I have been looking for a long time and I don’t know what went wrong.

**Comment by cgoldberg** [comment]
Please post the entire error message and stacktrace.

**Comment by AutomatedTester** [comment]
Closing as requested info not given
