### ISSUE TITLE
NullPointerException in RemoteWebElement.isSelected()

### ISSUE THREAD

**Issue by asolntsev** [SeleniumHQ/selenium#7672]
## 🐛 Bug Report

The stack trace clearly shows the NPE:

```java
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isSelected(RemoteWebElement.java:149)
```

## To Reproduce
It's hard to reproduce this issue. It happens very rarely.

**Comment by cgoldberg** [comment]
please fill out the issue template when filing issues.

**Comment by asolntsev** [comment]
@cgoldberg Sorry, but it smells like bureaucracy :(
I am pretty sure the issue contains all needed information. Why should anybody add useless text there?

**Comment by asolntsev** [comment]
PR is here: https://github.com/SeleniumHQ/selenium/pull/7673

**Comment by diemol** [comment]
After seeing the PR, and not being merged, I still conclude that templates are important.
Relevant information such as "this happens only in ChromeDriver/Chrome 77" was omitted and if that was present from the beginning so much less work would have been needed.
