### ISSUE TITLE
selenium  node runtime error:Actions is not a constructor 

### ISSUE THREAD

**Issue by Frederic-Zhou** [SeleniumHQ/selenium#7678]
my script like this:
``` javascript

const {
    Builder,
    By,
    Key,
    until,
    Actions
} = require('selenium-webdriver');

        /*just test */
        await driver.switchTo().frame(0)
        var action = new Actions(driver);
        await action.mouseDown(driver.findElement(By.xpath("//*[@id='loginButton']")))
            .mouseUp()
            .perform()
```
when I run this script , terminal show me error:
`(node:9640) UnhandledPromiseRejectionWarning: TypeError: Actions is not a constructor`

![image](https://user-images.githubusercontent.com/3068492/66697345-4cc45500-ed07-11e9-9b17-c730c5cf57ae.png)

![image](https://user-images.githubusercontent.com/3068492/66697380-a462c080-ed07-11e9-8a54-93e6bf22403c.png)

I can found the js module file in the module  path.

**Comment by baruchvlz** [comment]
Which version of the webdriver are you using? From looking at the code it seems like this class has been renamed to `LegacyActions` and deprecated. You should use `driver.actions(options)` instead.

From [the code](https://github.com/SeleniumHQ/selenium/blob/07ee491572f88790e598042ae779c44d3c1b3015/javascript/node/selenium-webdriver/lib/actions.js#L64-L87):

```js
/**
 * Class for defining sequences of complex user interactions. Each sequence
 * will not be executed until {@link #perform} is called.
 *
 * This class should not be instantiated directly. Instead, obtain an instance
 * using {@link ./webdriver.WebDriver#actions() WebDriver.actions()}.
 *
 * Sample usage:
 *
 *     new LegacyActions(driver).
 *         keyDown(Key.SHIFT).
 *         click(element1).
 *         click(element2).
 *         dragAndDrop(element3, element4).
 *         keyUp(Key.SHIFT).
 *         perform();
 *
 * @deprecated This class is strongly deprecated and will be removed once
 *     [Google's Chrome][Chrome] and [Microsoft's Edge][Edge] browsers
 *     support the new action sequence API.
 *
 * [Chrome]: https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md
 * [Edge]: https://docs.microsoft.com/en-us/microsoft-edge/webdriver
 */
```

**Comment by diemol** [comment]
Seems we never got a reply from the OP. 

Closing this issue, but if the problem still exists, feel free to open a new one with all the required information on the template.
