### ISSUE TITLE
Connect to opened Chrome instance

### ISSUE THREAD

**Issue by ZhaofengWu** [SeleniumHQ/selenium#7679]
I want to implement an auto log-in functionality and want to take advantage of the saved passwords in my default Chrome profile so that I don't need to supply passwords in plain-text. So I want to launch a Selenium driver with the default profile while also having another regular Chrome instance opened under the same profile for my usual browsing. Is there a way to achieve this?

I tried to set `user-data-dir=~/Library/Application Support/Google/Chrome/` for `webdriver.Chrome`, but I got the following error:

```
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
```

I guess it's because I already have an open Chrome instance with the same profile, but I need that for my usual browsing. I also tried starting my usual browsing instance on cmdline with `--remote-debugging-port={port}`, and connect from Selenium adding

```
chrome_options.add_experimental_option("debuggerAddress", f"127.0.0.1:{port}")
```

But I got the error

```
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=77.0.3865.120)
```

**Comment by barancev** [comment]
This is a question rather than an issue. For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
