### ISSUE TITLE
Deleting secured cookie on IE 

### ISSUE THREAD

**Issue by chenry35** [SeleniumHQ/selenium#7685]
Environment : 

Browser name and version: IE 11.13
Selenium : 3.141.0
robotframework-seleniumlibrary : 4.0.0
IE driver: 32 bit 3.141.59

With internet explorer, im trying to delete a cookie named wassup (with httpOnly True and secure True), but its not working, the cookie is still here. There is no error msg :

"DEBUG : DELETE http://127.0.0.1:61940/session/60566738-0540-4531-9c4c-21b1ada3d7ad/cookie/wassup {"name": "wassup"}"

With chrome, its working, the cookie is deleted.

Seems like we cant delete httpyOnly and secure cookie on IE, but getting value of the cookie is working.

**Comment by barancev** [comment]
Please include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by AutomatedTester** [comment]
Closing as the requested info was not given
