### ISSUE TITLE
UnsupportedCommandException sendKeysToActiveElement on Firefox

### ISSUE THREAD

**Issue by vmassol** [SeleniumHQ/selenium#7686]
Firefox version used: 69.0.3
Selenium version used: 3.14.159

Context: Migrating from Selenium 2.x to 3.x.

The error:

```
org.openqa.selenium.UnsupportedCommandException: 
sendKeysToActiveElement
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'vmassol', ip: 'fe80:0:0:0:18d2:2da9:44bb:783e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_202'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
	at org.xwiki.test.ui.po.SuggestInputElement$SuggestionElement.delete(SuggestInputElement.java:98)
```

The code:

```
// We don't send the keys directly to the text input because it can be hidden.(e.g. when multiple selection
// is on and we click on a selected suggestion).
getDriver().getKeyboard().sendKeys(Keys.BACK_SPACE);
```

I've found several issues on the topic but they were either related to Chrome and not Firefox or they didn't have a solution for FF and were closed due to inactivity:
* https://github.com/SeleniumHQ/selenium/issues/7542
* https://github.com/SeleniumHQ/selenium/issues/5517
* https://github.com/SeleniumHQ/selenium/issues/4546

If `sendKeysToActiveElement` is really unsupported then I guess it shouldn't be part of the API, right?

Note that I cannot use `sendKeys()` on a `WebElement` since the element is hidden (see comment in code above).

Any idea?

Thanks a lot

**Comment by barancev** [comment]
Selenium is not designed to support actions with non-interactable elements. In emergency you can use executeScript command.

**Comment by vmassol** [comment]
Hi @barancev . I don't really understand how your answer replies to my question about:

> If sendKeysToActiveElement is really unsupported then I guess it shouldn't be part of the API, right?

Could you explain why you closed the issue? Thanks

> Selenium is not designed to support actions with non-interactable elements.

I'm not trying to use actions with non-interactable elements. I'm getting an UnsupportedCommandException on Firefox.

Is `sendKeysToActiveElement` supposed to work? If so why do I get an UnsupportedCommandException?

Thanks

**Comment by barancev** [comment]
It's a part of legacy API that used to be supported in past (in old versions of drivers). At the moment it's deprecated, the interface HasInputDevices that contains getKeyboard() methid is deprecated, the interface Keyboard returned by this method is deprecated. Don't use this API with modern drivers, they don't support it already. It's still here for those who continues to work with old browser versions and have to use old drivers.

**Comment by barancev** [comment]
Instead of it please use `Actions` API.
