### ISSUE TITLE
Not able to press Ctrl + F5 keys to do hard refresh using chromedriver and C# webdriver bindings

### ISSUE THREAD

**Issue by papatelst** [SeleniumHQ/selenium#7687]
## 🐛 Bug Report

Not able to press Ctrl + F5 keys to do hard refresh using chromedriver and C# webdriver bindings

## To Reproduce
On any page, try to do hard refresh by pressing Ctrl and F5 keys together using any ONE of the following command variations (with or without any element on the page)
Actions action = new Actions(element.Browser.WebDriver);
action.KeyDown(Keys.Control).SendKeys(Keys.F5).KeyUp(Keys.Control).Perform();

action.KeyDown(Keys.Control).SendKeys(Keys.F5).KeyUp(Keys.Control).Build().Perform();

action.KeyDown(element.WebElement, Keys.Control).SendKeys(element.WebElement, Keys.F5).KeyUp(element.WebElement, Keys.Control).Build().Perform();

action.KeyDown(element.WebElement, Keys.Control).SendKeys(element.WebElement, Keys.F5).KeyUp(element.WebElement, Keys.Control).Perform());

action.SendKeys(Keys.Control + Keys.F5).Build().Perform();

## Actual behavior
Does not do anything on the page.

## Expected behavior
It should hard refresh the page. Looks like it was working for Java bindings in the past as mentioned at - https://stackoverflow.com/questions/12299960/browser-refresh-by-ctrlf5-in-webdriver-using-java

## Environment

OS: Windows 10 
Browser:  Chrome 
Chrome Browser version: 78.0.3904.97
Chrome Driver version: 78.0.3904.7000
Language Bindings version:  C#  4.0.0-alpha03

**Comment by papatelst** [comment]
Any updates on this issue. This is blocking many of our tests, which require the capability to do full refresh of a page like real user would do using Ctrl + F5 keys.

**Comment by 12371601** [comment]
Any updates on this issue.？？？？

**Comment by papatelst** [comment]
The solution is mentioned by chrome driver team here -
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3249

To replicate Control F5, this should work:
```
Dictionary<string, object> details = new Dictionary<string, object>();
details["ignoreCache"] = true;
driver.ExecuteChromeCommand("Page.reload", details);
```
