### ISSUE TITLE
[Regression] Form submit does not seems to wait for target page load anymore

### ISSUE THREAD

**Issue by tmortagne** [SeleniumHQ/selenium#7691]
## 💥 Regression Report

We just upgraded from Selenium 2.44.0 to 3.141.59 (yes big jump...).

In previous version the following code was waiting for the page load but it's not the case anymore:

https://github.com/xwiki/xwiki-platform/blob/xwiki-platform-11.8.1/xwiki-platform-core/xwiki-platform-extension/xwiki-platform-extension-test/xwiki-platform-extension-test-pageobjects/src/main/java/org/xwiki/extension/test/po/SimpleSearchPane.java#L104

`searchInput` is an `<input type="text">` in a `<form>` and clicking ENTER submit the form to the target page (in this case the current page). Problem is that Selenium does not seems to have any special handling of ENTER key anymore in the case of a form input and `#searchInput` returns immediately.

I tried also calling #submit() on the `<input>` and on the `<form>` WebElements but it has the same behavior (not waiting).

## Last working Selenium version

Worked up to version: 2.44 with Firefox 32.0

Stopped working in version: 3.141.59 with Firefox 69.0.2

(Did not really tested the versions in between so not really sure when the behavior change really started)

## To Reproduce

Detailed steps to reproduce the behavior:

* have some dynamic HTML page with a `<form>`
* access a string input of that form as a WebElement
* call #sendKeys(Keys.ENTER) on it
* assert something the resulting target page must contain

-> ENTER key work as expected and submit the form but the assert is executed before the target page get a chance to finish loading.

## Expected behavior

`#sendKeys` wait until the page is reloaded

## Environment

OS: Ubuntu 19.04
Browser: Firefox
Browser version: 69.0.2
Browser Driver version: GeckoDriver 0.26.0 (trough https://github.com/bonigarcia/webdrivermanager)
Language Bindings version: Java 3.141.59

**Comment by barancev** [comment]
Can it be that you faced this issue:
https://github.com/mozilla/geckodriver/issues/1026

**Comment by tmortagne** [comment]
Does not seem so. As far as I can see we have the issue with very simple forms, also as I said it's not just with click and calling directly #submit (which is not supposed to care about javascript officially) does not wait.

**Comment by surli** [comment]
AFAIR yes I only had the issue with Firefox, and I did not perform test on chrome.

**Comment by barancev** [comment]
So I'll close this issue, subscribe to the abovementioned one to watch the progress.
