### ISSUE TITLE
Bug: 77.0.3865.40 chromedriver.exe return null for getAttribute("href") in Java 

### ISSUE THREAD

**Issue by vlee00** [SeleniumHQ/selenium#7693]
## To Reproduce

Detailed steps to reproduce the behavior:

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Browser: 
Browser version: 
Browser Driver version: 
Language Bindings version:  
Selenium Grid version (if applicable):

**Comment by vlee00** [comment]
OS: Windows 10
Browser: Chrome
Browser version: 77.0.3865.120 (Official Build) (64-bit)
Browser Driver version: 77.0.3865.40
Language Bindings version: Java
Selenium Grid version (if applicable): None

WebDriver driver = driver.findElement(By.xpath("//*[@id=\"ServiceCommunityTemplate\"]/div[2]/div/div[2]/div/div/div/div[1]/table/tbody/tr[6]/td[2]/a")).getAttribute("href");

Result outcome: 
a href= return null

**Comment by jimevans** [comment]
This is a duplicate of #7631. It may not look like it at first glance, but both `isDispayed` and `getAttribute` are accomplished by means of executing JavaScript, which is the root cause of the issue here.
