### ISSUE TITLE
Issue in find_element_by_class_name()

### ISSUE THREAD

**Issue by 13aksh** [SeleniumHQ/selenium#770]
When we use the function find_element_by_class_name('xyz') then it returns the value of the tags with class = "abc xyz" also. Facing problem because of this issue.

**Comment by ddavison** [comment]
you need to be more specific with your selector.  `find_element_by_class_name` will return any elements that have "xyz" as a class.  it's the same thing as doing:

```python
find_element_by_css_selector('*[class~="xyz"]')
```

consult the selenium users group for help.  these issues are reserved for issues with selenium
