### ISSUE TITLE
Element Displayed check incorrect return value

### ISSUE THREAD

**Issue by nikembala** [SeleniumHQ/selenium#7702]
## 🐛 Bug Report

Element Displayed property is not calculated correct when the element is not in viewport.
---
Edit:
"Not calculated correct" means that it is true, while the element checked is outside of the viewport.

## To Reproduce

1.Locate an element on a page that is outside of the viewport
2.Check displayed property

## Expected behavior

Comply with https://www.w3.org/TR/webdriver1/#element-displayedness

## Test script or set of commands reproducing this issue

Please find few tests in the repo below:
https://github.com/nikembala/SeleniumWebDriverTests/tree/test-displayed

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 77.0.3865.120 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 77.0.3865.4000
Browser: Firefox
Browser version: 70.0 (64-bit)
Browser Driver version: GeckoDriver 0.26.0
Language Bindings version: .NetCore 3.0

**Comment by nikembala** [comment]
Doesnt that bother anyone at all

**Comment by jimevans** [comment]
@nikembala Bother anyone? Sure. But I’m not certain the agitation is helpful, given that Selenium is developed and maintained entirely on an unpaid volunteer basis.

**Comment by okyrylenko** [comment]
Your defect does not clearly define what the issue. Does display property returns true when it should return false, the other way around or something else? this is from the selenium documentation you have in your original post- "**The visibility of an element is guided by what is perceptually visible to the human eye**. In this context, an element's displayedness does not relate to the visibility or display style properties. 
If the element is not in a viewport, it is not visible to a human eye, hence it should return false. Are you seeing a different behavior?

**Comment by nikembala** [comment]
> If the element is not in a viewport, it is not visible to a human eye, hence it should return false. Are you seeing a different behavior?
@okyrylenko , yes, I do see different behaviour, that does not match expectations and documentation.

**Comment by nikembala** [comment]
Hello, issue is still present. "Displayed" property of an element returns "true" when the element is outside of the viewport, thus expecting it to be "false".
