### ISSUE TITLE
Cant get Full page screenshot

### ISSUE THREAD

**Issue by EFXPROMedia** [SeleniumHQ/selenium#7703]
I am currently trying to return a full-page screenshot for all browsers we are testing but it returns only the viewport screen, interesting enough IE11 is working just fine.

1 - Would it be a browser capability issue with selenium?
2 - can we use a config in the takeScreenshot() to get the screenshot the way we need it (viewport view, full page...) ?

I am using NodeJs v10.15.1  and selenium-webdriver 4.0.0-alpha.5

Thanks

**Comment by barancev** [comment]
The drivers work as specified in W3C WebDriver: https://w3c.github.io/webdriver/#screen-capture
