### ISSUE TITLE
FluentWait changes WebDriverWait().until(ExpectedCondition...) fails with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by americausa999** [SeleniumHQ/selenium#7705]
Issue is closed: https://github.com/SeleniumHQ/selenium/issues/3606

It's still reproducible on latest Selenium 4.x.x  using Guava 28.x.x 

Can anyone know how to fix this ?
I would be happy to provide more info but not sure whether we will like to start a new bug or re-open the old issue. Either way people are seeking solution, please let me know. 

Thanks

**Comment by barancev** [comment]
The mentioned issue has been closed with an explanation and a solution. If it does not cover your case please describe it in more details.

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
