### ISSUE TITLE
Exporting HAR file with Selenium triggers `Object.throwDecodedError` on some websites that can be loaded normally in Firefox web browser.

### ISSUE THREAD

**Issue by phongiswindy** [SeleniumHQ/selenium#7706]
## 🐛 Bug Report

Exporting HAR file with Selenium triggers `Object.throwDecodedError` on some websites that can be loaded normally in Firefox web browser.

I could export the HAR file normally when visiting some common sites: `google.com`, `facebook.com`, etc. But, I currently encounter `Object.throwDecodedError` when crawling and export HAR for some specific sites, such as: `http://www.team.aero`, `http://bilimselbilisim.com`, and `http://jmlsg.org.uk`.  Note that all of these sites can be viewed/rendered normally in real Firefox browser.

The errors are shown as:

>     at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
>     at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:560:13)
>     at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:486:26)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Original bug was filed here: https://github.com/sitespeedio/browsertime/issues/636#issuecomment-544894687

**Comment by barancev** [comment]
Please nclude an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by AutomatedTester** [comment]
Closing as the requested info was not given
