### ISSUE TITLE
WebDriver doesn't see and/or can't interact with elements inside element with attribute 'fragment'

### ISSUE THREAD

**Issue by silverenio** [SeleniumHQ/selenium#7709]
## 🐛 Bug Report

Elements with attribute 'fragment' are not visible.
Impossible to interact with child elements.

## To Reproduce

JUST for example (from stackoverflow)
https://stackoverflow.com/questions/54926023/documentfragment-elements-not-visible-for-webdriver/58523787#58523787

```
<div class="activity-container">
<!--fragment#54705578f9#head-->
<div fragment="54705578f9" class="activity-action">
    <span class="icon-arrow_drop_down"></span>
    <span class="actions-description">
        <b>Login</b>
    </span>
    <span>Date: 28/02/2019</span>
    <span>Time: 12:20</span></div>
<div class="activity-description" fragment="54705578f9" style="display: none;">
    <span></span>
    <span class="actions-no-info">No additional information</span>
</div>
<!--fragment#54705578f9#tail-->
<!--fragment#26552421c5#head--></div>
```

## Actual behavior
driver.findElement(By.xpath("```<correct xpath>```")).isDisplayed(); - will return false;
driver.findElement(By.cssSelector("```<correct selector>```")).isDisplayed(); - will return false;

any input into input elements will throw an error org.openqa.selenium.ElementNotInteractableException: element not interactable

## Expected behavior
driver.findElement(By.xpath("```<correct xpath>```")).isDisplayed(); - returns true;
driver.findElement(By.cssSelector("```<correct selector>```")).isDisplayed(); - returns true;

any input into input elements is success

## Environment

OS:  Windows 10 x64
Browser: Chrome
Browser version: 77
Browser Driver version: ChromeDriver 77
Language Bindings version: Java 3.141.59

**Comment by barancev** [comment]
Please include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
