### ISSUE TITLE
Mouse hover is not working with Firefox 29

### ISSUE THREAD

**Issue by prab2112** [SeleniumHQ/selenium#771]
Earlier i was using Firefox 25 and the following line of code to hover over a menu to get it's submenus.
````java
WebElement menu = driver.findElement(by);
		Actions builder = new Actions(driver);
		builder.moveToElement(menu).build().perform();
		WebDriverWait wait = new WebDriverWait(driver, 15);
````

When i upgraded to Firefox 29 it's not working as expected. it was working fine with Firefox 25
My selenium version is 2.42

**Comment by cgoldberg** [comment]
upgrade your browser and selenium version.

**Comment by prab2112** [comment]
I tried after updating my selenium version and firefox as well. Still same issue.

**Comment by barancev** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by prab2112** [comment]
This is working fine. Thanks
