### ISSUE TITLE
java.lang.ExceptionInInitializerError for chrome 77.0.3865.120 

### ISSUE THREAD

**Issue by kishor32** [SeleniumHQ/selenium#7711]
## 🐛 Bug Report

Chrome version : 77.0.3865.120 and above 

Chrome driver :  **Starting ChromeDriver 77.0.3865.10 (bc3579f611bbc73331171afe020ec7a45e6ccc55-refs/branch-heads/3865@{#93}) on port 38271
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.**

java.lang.ExceptionInInitializerError

java.lang.ExceptionInInitializerError
Caused by: org.openqa.selenium.WebDriverException: 
unknown error: cannot create temp dir for user data dir
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host:  ',', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00FCEBD3+1502163]
	Ordinal0 [0x00F4F781+980865]
	Ordinal0 [0x00ED763F+489023]
	Ordinal0 [0x00E6B894+47252]
	Ordinal0 [0x00E897E0+169952]
	Ordinal0 [0x00E8940D+168973]
	Ordinal0 [0x00E878EB+162027]
	Ordinal0 [0x00E70AC7+68295]
	Ordinal0 [0x00E71B40+72512]
	Ordinal0 [0x00E71AD9+72409]
	Ordinal0 [0x00F68FE7+1085415]
	GetHandleVerifier [0x0106D8AD+503293]
	GetHandleVerifier [0x0106D640+502672]
	GetHandleVerifier [0x0107471C+531564]
	GetHandleVerifier [0x0106E0BA+505354]
	Ordinal0 [0x00F606B6+1050294]
	Ordinal0 [0x00F6052F+1049903]
	Ordinal0 [0x00F6B04B+1093707]
	Ordinal0 [0x00F6B1B3+1094067]
	Ordinal0 [0x00F6A145+1089861]
	BaseThreadInitThunk [0x77278674+36]
	RtlGetAppContainerNamedObjectPath [0x77BB5E17+311]
	RtlGetAppContainerNamedObjectPath [0x77BB5DE7+263]

**Comment by diemol** [comment]
We have spent some time improving the issue templates in order to allow users to provide enough information when an issue is reported, which will end up helping the maintainers and collaborators to provide a better answer when an issue is created. Why did you delete the template? Please fill out a new issue with all the information needed.

**Comment by barancev** [comment]
Also version 3.9.1 is too out of date, please upgrade.
