### ISSUE TITLE
Code inside IEDriver confuses NTLM security dialog for an Alert Box and limits interaction

### ISSUE THREAD

**Issue by calphool** [SeleniumHQ/selenium#772]
Hello, after much gnashing of teeth, I believe I've discovered a bug in IECommandExecutor.cpp.

I'm automating a site that uses NTLM security and IE issues a challenge-response dialog when you navigate to a URL.  

It looks like this:

![image](https://cloud.githubusercontent.com/assets/4335553/8659127/1a2e6d58-296e-11e5-87b4-110c012499f0.png)

Once this dialog is present, any interaction you do with the browser raises an exception "Selenium::WebDriver::Error::UnhandledAlertError: Modal dialog present:"  (using Ruby bindings, but I'm sure it would be the same if I was using Java).

The only interactions that seem to be allowed once the dialog is present are:  send_keys, accept, and dismiss.  Since this is a security dialog, I need more control than that.  I need to be able to set focus on each field and fill it out (send_keys only types in the first field and special keys like tabs or returns are turned into strange text characters).

I *believe* the bug is in IECommandExecutor::IsAlertActive().  I *believe* it's returning true, which effectively shuts off my ability to ask the browser about its windows and work out some other way to fill out the NTLM dialog.  However, it might also be in IECommandExecutor::DispatchCommand() since that's what's using IsAlertActive().  I'm not familiar with the code, so I'm not sure.  If I could figure out how to build it, I might try a few different things to see if I can get around it, but I'm guessing the community isn't super excited about newbies mucking around in IEDriver, and my cpp skills are a little rusty at best.

Thanks!

**Comment by jimevans** [comment]
Login/security dialogs are explicitly unsupported by WebDriver generally, and the IE driver specifically. Handling authentication dialogs has been postponed by the W3C working group producing the WebDriver specification. There have been some proposals around an API for handling authentication dialogs, but none of these have been fully adopted by the drivers nor the language bindings. You will need to know _a priori_ that you expect the dialog to appear upon navigation to the URL in question, and you'll need to come up with an alternative way to handle it.

So, yes, it's a bug, I suppose, but it's a bug in the sense that the feature isn't supported. And, no, that's not the best answer, and certainly not what you wanted to hear, and for that, you have my apologies.

**Comment by calphool** [comment]
This is tied to me getting my company to adopt Automation Testing in general.  What you're saying is tantamount to:  "Your company will never adopt automation testing because you can't prove that it'll work."  My intention was to get some basic regression functional testing running, push it up to SauceLabs and show them that the modern world does cross browser automation testing rather than limiting users to a specific (ancient) browser.

Is there some way we can put a fix in that at least corrects the fact that the driver is confusing a security dialog for a plain old alert?  I mean all I really need is the ability to set focus on the controls in the dialog and send them text or a click event.

If I figure out a way to get this to work by building it myself Jim, will you reject the fix?  I'd need to somehow get it to Saucelabs to do the demonstration I'm planning.

**Comment by jimevans** [comment]
What do you expect the behavior to be here? That the driver will simply not throw the exception, and will allow you to then process the dialog at your discretion? You already have that ability. If you have another mechanism for handling the dialog, you can use that mechanism immediately following your call to `driver.get()`, before performing any other WebDriver command, and the driver will proceed just fine without throwing the exception.

Another alternative might be to use a proxy, and insert the authentication headers into the initial request. 

On the other hand, do you expect that the driver will allow you to manipulate the dialog to pass your credentials? That, specifically, is not going to work, and it won't be an easy fix to "just add it." I'm more than willing to look at any pull request you might want to send my way, but please be aware that it will need to work against all supported versions of IE (7, 8, 9, 10, and 11) and the various operating system versions those browsers are supported on (Windows Vista, 7, 8, and 8.1 at present, with Windows 10 coming soon). I point this out because the same IE version can present different authentication UI when running on different OSes.

If you're truly interested in contributing, I will be more than happy to give you guidance on getting a development environment set up. The easiest and fastest way to get information of that sort is on the Selenium IRC channel (#selenium on freenode.net).

**Comment by calphool** [comment]
>What do you expect the behavior to be here? That the driver will simply
not throw the exception, and will allow you to then process the dialog at
your discretion? You already have that ability. If you have another
mechanism for handling the dialog, you can use that mechanism immediately
following your call to driver.get(), before performing any other WebDriver
command, and the driver will proceed just fine without throwing the
exception.

I don't know for sure that I *do* have that ability.  I'm using Capybara
with Ruby bindings, so the way the driver actually gets invoked is a little
hidden from me (I use "visit", which indirectly uses "driver.get()" I'm
sure).  Once I've invoked "visit", anything other than switching to the
"alert" (sic) and invoking one of its 4 working methods causes an exception
to be thrown from what I can tell.  If the exception wasn't thrown, I
*might* have the ability to work with the security dialog, but I really
can't tell at this point.  The fact that it responds to send_keys is a good
sign though.

>Another alternative might be to use a proxy, and insert the authentication
headers into the initial request.

I messed around with a local proxy, but I couldn't come up with a strategy
that worked there... you see, I'm testing with SauceLabs, which uses a
tunneling utility called Sauce:Connect to forward remote Selenium
instructions to the browsers in their Cloud, and somehow sets up a network
segment in their Cloud that forwards its network requests (DNS resolution
for example) back to your local network.  So figuring out how to get a
proxy into the middle of that conversation to insert Auth headers seems to
be nontrivial.  I might be able to figure it out if I set up a sniffer
perhaps.  The Sauce:Connect utility claims to have the ability to inject
credentials for certain URLs, but from what I can tell that part of the
utility must be broken, because it seems to be ignoring those commands (its
logging sucks even on verbose, so I can't be sure what's going on without
installing a sniffer or something).

>On the other hand, do you expect that the driver will allow you to
manipulate the dialog to pass your credentials? That, specifically, is not
going to work, and it won't be an easy fix to "just add it."

Yeah, that's kind of what I'm thinking.  It doesn't seem insurmountable.  I
mean that's what an end user does after all, so it seems like that's what
we ought to be exposing.  The fact that every browser chose to do this
differently sucks yeah, but if we can figure out how to automate it
visually on each driver, then that's the substrate upon which proper
abstracted automation (with a credentials object sent a-priori) really
ought to be built upon anyway.  In IE's case, we first need to identify
that that's truly the situation we're in (not an Alert dialog), and then
we'd need to figure out some way to expose those two text boxes and two
buttons as addressable in the command dispatch protocol.  I just went and
read the new W3C protocol draft (
https://w3c.github.io/webdriver/webdriver-spec.html), and if I'm reading it
correctly, it completely avoids this whole issue -- it doesn't say a word
about it.  It's like the authors didn't realize this issue exists, though
the "modal" behavior I'm seeing is certainly addressed.

I completely grok the fact that a solution would need to work on all the
browsers and OSs.  It looks like Chrome has a slightly different behavior
(modal pops up, but visit() never gives control back to Ruby).  I grok the
fact that Edge is on the horizon and this could be kind of a thankless
chore, but I really hate to lose the entire test automation debate at my
shop over something so silly.  They'll throw it right at me:  "See, you
can't even automate the first page -- this automation stuff isn't fully
baked".  I've started at a new company, and it's a bit like walking
backward in time 5 years... I'm trying to show them the light of automated
functional testing in general.  They literally do almost none which is
frankly, unbelievable.

I'd definitely be willing to take a stab at getting a fix put together.  I
cloned the Selenium repository.  What's next?  I assume it's built with
Visual Studio?  I'll have to figure out a way to recreate the whole
situation locally (without SauceLabs in the middle)... I think I'll have to
tweak my local copy of IE to make it "unremember" my credentials (when I
script locally I don't get the popup because NTLM passthrough or something
has been set up).

--Joe

**Comment by jimevans** [comment]
Let me point out that the W3C spec is silent on the issue, as the Working Group decided to postpone the discussion until a later version of the spec. I believe I mentioned that in my first reply to your issue report.

Nevertheless, you'll want to look at 7604d12, which may help in giving you something closer to what you're looking for.

**Comment by calphool** [comment]
Great!!  I'll give it a shot as soon as I can... given that I'm a few
layers away from IEDriver (Capybara and Ruby), I'll have to chase the bug
up the stack, but at least it's possible now!  Thanks!
