### ISSUE TITLE
AWS JAVA Selenium as dependencies corrupting shade jar

### ISSUE THREAD

**Issue by AliceBroadhurst** [SeleniumHQ/selenium#7721]
## 🐛 Bug Report

Adding the selenium dependencies to a lambda project (created through eclipse) corrupts the jar which causes AWS to not recognise it. Once the dependencies are removed, the lambda jar is not longer corrupted and accepted. 

## To Reproduce

Add any of the newest selenium dependencies to a lambda project and build into a shade jar. Click test (I used an empty test so '{}') and upload the jar to AWS to see a 'cannot unzip' error from AWS.
![image](https://user-images.githubusercontent.com/49036568/67777135-359c9b80-fa59-11e9-8871-cd68a9cf986a.png)

## Expected behavior

The lambda should be uploaded and unzipped by aws. It should run on demand.

## Test script or set of commands reproducing this issue

https://github.com/distologyProgrammer/MSP_Lambda

## Environment

OS: 
Browser: Chrome
Browser version: Latest
Browser Driver version: Latest
Language Bindings version: Java 1.8
Selenium Grid version (if applicable): Latest

**Comment by barancev** [comment]
Can you please explain in more details how to reproduce the issue? Suppose I have an AWS account, what should I do with the provided sample project?

**Comment by distologyProgrammer** [comment]
@barancev 

You need to build a jar shaded jar from the add using package shade:shade and upload that to an aws lambda
