### ISSUE TITLE
Set capabilities via JSON

### ISSUE THREAD

**Issue by kodayashi** [SeleniumHQ/selenium#7722]
## 🚀 Feature Proposal

The Java client for selenium appears to require a programmatic approach to setting capabilities. It would be great if driver creation could be config driven.

## Motivation

When having a need to test against a large array of devices with various capabilities, it makes more sense to implement a config-driven approach to driver creation.

This approach could also be implemented across all binding languages.

## Example

WebDriver driver = new ChromeDriver(someJsonFileOrObject)

Please provide an example for how this feature would be used.

Any case where we want to modify the capabilities for a large set of drivers to use for testing without making any code changes.

**Comment by MarkGunlogson** [comment]
The Java client has some support for loading capability values as Gson's JsonObject but this falls over in complex examples when drivers expect specific Java types for values. For example, trying to set ChromeDriver "prefs" like `profile.managed_default_content_settings.geolocation` will always fail because the driver expects an integer value while Gson always de-serializes numbers to double.

Having these corner cases seems silly to me when the W3C WebDriver protocol has a standardized format for capabilities. Since these capabilities always end up looking the same on the wire for every client language, could we allow users to pass JSON capabilities in the standard wire format to WebDriver constructors?

**Comment by jimevans** [comment]
My resistance to something like this, at least for strongly-typed languages (Java, C#) is that the config then becomes a random key-value property bag where it’s incredibly easy to pass in invalid configuration values. This is the reason that `DesiredCapabilities` was deprecated in the .NET bindings in 3.x and removed from the public API in 4.x. Troubleshooting an invalid configuration in a text-based system with no type checking or validation is a nightmare, and I have the scars from mailing lists, from StackOverflow, and from the IRC/Slack channel to prove it.

I’m not saying, “No, I’m permanently opposed to this course of action,” but I’m skeptical, at least at the beginning of the discussion, of whether the pros outweigh the cons. On the other hand, it seems to me that if it’s something someone finds valuable enough, a “driver config factory” that reads the text-based configuration and emits a `Capabilities` object wouldn’t be _that_ difficult to write and open source as a companion project.

**Comment by MarkGunlogson** [comment]
> My resistance to something like this, at least for strongly-typed languages (Java, C#) is that the config then becomes a random key-value property bag where it’s incredibly easy to pass in invalid configuration values.

I agree in principle, but the driver specific capabilities basically are a random property bag, just nested a few levels below the main capabilities object. I'm all for having drivers do property validation, I've had my own nightmares of misspelling a capabilities for it to be silently ignored. That's whats happening to me right now when Gson parses my `profile.managed_default_content_settings.geolocation` value as a double :-(

**Comment by diemol** [comment]
We normally leave these feature requests open for a while to see if the community has a strong interest in them, if there is a good and wide use case to support or if somehow a feature request is aligned with a current development.

This request, however, has not gotten any traction or interest. So I will go ahead and close it.
