### ISSUE TITLE
Keys.Chord is not Working to launch incognito window for current instance

### ISSUE THREAD

**Issue by VijayVarmaKethe** [SeleniumHQ/selenium#7724]
OS: windows 10
Selenium Version: 3.141.59, IntelliJ 2018.2.5
Browser: Chrome
Browser Version: Version 78.0.3904.70 (64bit)
Chromedriver Version: 78.0.3904.70

Expected Behavior
Key.chord(Keys.CONTROl, Keys.SHIFT,"N") should launch incognito window for current running chrome instance
I tried with webelement.sendkeys(Keys.chord(Keys.CONTROL,Keys.SHIFT,"N")) and also tried with
Actions actions = new Actions(driver);
actions.sendKeys(Keys.chord(Keys.CONTROL, Keys.SHIFT, "N")).build().perform();

Actual Behavior
it does nothing, no error in log
Same happening for both Chrome and Firefox

Steps to reproduce:
System.setProperty("webdriver.chrome.driver", "./src/main/resources/chromedriver.exe");
Webdriver driver = new ChromeDriver();
driver.get("https://www.google.com/");
driver.findElement(By.xpath("//body")).sendKeys(Keys.chord(Keys.CONTROL,Keys.SHIFT,"N"));

**Comment by Harsha509** [comment]
Hi @VijayVarmaKethe ,

Did this feature worked in any other chrome versions ?. If yes can you please provide chromedriver log.

As far as i remember this feature has been removed as ChromeDriver no longer supports typing of special control keys

Thanks!

**Comment by VijayVarmaKethe** [comment]
Thanks @Harsha509 ,

Previously I used selenium 2.53 with chrome 50. Now I've update to selenium 3.141.59 with a latest chrome. Chrome driver removed that feature. But I'm facing the same issue in Firefox too..

Gecko version: 0.26.0
Firefox Version: latest

Thanks!

**Comment by Harsha509** [comment]
Hi @VijayVarmaKethe 

It is an expected feature form chrome as chromediver is can be used to test web application but not the chrome window operations. You can no longer do this.

In Firefox you may need to provide the geckodriver log in order to debug it.

Thanks,
Sri

**Comment by werru** [comment]
Hey
It works with selenium-chrome-driver 3.141.59 and 74 version of chrome. More fresh just ignore Keys.chord

**Comment by VijayVarmaKethe** [comment]
Thanks @werru 
I'm facing this issue in Firefox too.

**Comment by Harsha509** [comment]
Hi @VijayVarmaKethe ,

If you're using chrome 74+ you may need to use the selenium 4-aplha-3 (java) or selenium4-alpha-5 (JavaScript) to test out below feature.

Here is the new webdriver API to open new tab

driver.switchTo().newWindow('tab');

and for new window 

driver.switchTo().newWindow('window');

Thanks,
Sri Harsha

**Comment by VijayVarmaKethe** [comment]
Thanks Harsha.
