### ISSUE TITLE
Possible issue with Chromedriver 78, Selenium can not find web element of embeded PDF opened in Chrome

### ISSUE THREAD

**Issue by MilosRadovic304** [SeleniumHQ/selenium#7725]
Until my google Chrome wasn't updated to version 78 my test automation scripts worked fine. So I am not able anymore to find WebElement with id='plugin' in PDF opened in browser using Selenium WebDriver and Java:

```
<html>
<div id="content">
<embed id="plugin" type="application/x-google-chrome-pdf" src="http://??????????/offer_printed.php?printable=yes&amp;reanudar=&amp;>
</div>
</html>
```

Java selenium code:

```
WebDriverWait wait = new WebDriverWait (driver, 90);
WebElement scrollvalid = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("plugin")));

scrollvalid.sendKeys(Keys.PAGE_DOWN);                       
scrollvalid.sendKeys(Keys.PAGE_DOWN);
```

Error:
org.openqa.selenium.TimeoutException: Timed out after 90 seconds waiting for visibility of element located by By.id: plugin

After I deleted Google Chrome version 78 and installed version 76 my automation tests are working again. Everything works perfectly. I hope that this issue with version 78 will be fixed.

Thank you!

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://chromedriver.chromium.org/help
