### ISSUE TITLE
Chromedriver 78: cannot set selection and send keys in contenteditable 

### ISSUE THREAD

**Issue by johanneswilm** [SeleniumHQ/selenium#7728]
With Chromedriver 2.41.0 there was a bug that would not let you put focus on an element inside of a contenteditable element so that when you wanted to set the selection somewhere inside of a contenteditable element and and then send some keys there, you would first set the selection using a JavaScript helper function and then use sendkeys to the contenteditable element and the keys would affect the selected content.

In Chromedriver 78 the bug has been fixed. Now one can send keys directly to an element that is inside of a contenteditable element. However, one can now no longer use sendkeys to affect selected content as the selection is being reset to the end of the element when sendkeys is used. So for example, if I have this structure [] = selection:

```
<div contenteditable=true>1<span>2[MY SELECTION]3</span>4</div>
```

In 2.41.0 you could send the backspace key to the div, and it would delete the selection, giving you this, | = caret:

```
<div contenteditable=true>1<span>2|3</span>4</div>
```

In Chromedriover 78, if you send the keys to the `<div>`, it puts the caret at the end of the `<div>` and deletes the number 4. If you send the keys to the `<span>`, it will put the selection at the end of it and delete the 3.

Is there anyway to keep the selection and let the backspace affect that?

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://chromedriver.chromium.org/help
