### ISSUE TITLE
Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by apulido15** [SeleniumHQ/selenium#7729]
## 🐛 Bug Report

Hi my friends,
 i have a automation web app for execute in mobile devices, i have the next error when i execute the project

Caused by: org.openqa.selenium.UnsupportedCommandException: unknown command: Cannot call non W3C standard command while in W3C mode

why is this error?
 
info:
Android 9
appium 1.15.1
Serenity BDD Core 2.0.82
appium Client 7.2.0
Chrome Version 78.0.3904.62
chromeDriver 78.0.3904.70
Java 1.8
[appium-server-logs.txt](https://github.com/SeleniumHQ/selenium/files/3791132/appium-server-logs.txt)
[Eclipselog.txt](https://github.com/SeleniumHQ/selenium/files/3791133/Eclipselog.txt)

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
