### ISSUE TITLE
Not able to use RelativeLocator in page factory (@FindBy)?

### ISSUE THREAD

**Issue by sachinguptait** [SeleniumHQ/selenium#7731]
How can we use RelativeLocator in page factory (@FindBy), please help me here to use below code in page factory

```
driver.findElement(RelativeLocator.withTagName("input").above(By.name("password")).
                below(By.xpath("//td//b[text()='sign-in here']")));
```

Actually I want to use above code (RelativeLocator) in page factory, it's a new feature given by selenium4-alpha-3 version community, but I don't know how to use this in page factory. please see the below code of page factory, here we can use all the locators like name, cssSelector, xpath, id, className, linkText, etc. Same way how can we use Relative locator here:

```
@FindBy(name="uid")
 WebElement` userName;
```

I know it's normal uses, see the [Relative Locator video](https://www.youtube.com/watch?v=R7XOYM7ISRw) for your reference, I need help to use this new Relative locator in page factory with @FindBy annotation.

**Comment by barancev** [comment]
Relative locators are dynamic by its nature. They describe an element by its spatial relations to other elements. Java annotations allow to use static expressions only that can be evaluated on compilation stage. So it's impossible to use relative locators with the current implementation of PageFactory.
