### ISSUE TITLE
by.Tagname is not working as, the tag selector is falsely prefixed with the css id selector

### ISSUE THREAD

**Issue by asohail00** [SeleniumHQ/selenium#7732]
## 🐛 Bug Report

By.tagname() method is not working.

Chrome version(77.0.3865.120):-
https://chromedriver.chromium.org/help

## To Reproduce

Detailed steps to reproduce the behavior:
1. Logged in to the environment and selected a table via selenium web driver.
2. For rendering a column after row I was using (driver.findElement(By.tagName(locatorValue))) method.

## Expected behavior

(driver.findElement(By.tagName(locatorValue))) method should have rendered to column accordingly with column tag.

## Test script or set of commands reproducing this issue

(driver.findElement(By.tagName(locatorValue)))

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: <-- Windows 7 -->
Browser: <-- Chrome -->
Browser version: <--  77.0.3865.120 -->
Browser Driver version: <--  ChromeDriver 76.0.3809.126 -->
Language Bindings version: <-- : Java 1.8.0_152 -->

**Comment by AutomatedTester** [comment]
Have you got website we can reproduce against? If not we will close this bug

**Comment by asohail00** [comment]
website to reproduce against :- https://test.salesforce.com

**Comment by AutomatedTester** [comment]
That page doesn't have a table so closing. Please raise a bug with code to reproduce otherwise it will be closed too
