### ISSUE TITLE
get_implicit_wait

### ISSUE THREAD

**Issue by snoopyjc** [SeleniumHQ/selenium#7738]
## 🚀 Feature Proposal

I would like to propose a driver.get_implicit_wait() function.

## Motivation

Functions shouldn't have side-effects if if I call driver.implicitly_wait(2) in my function, there is no way to set it back to what it was.

## Example

    def do_something():
        old_wait = driver.get_implicit_wait()
        driver.implicitly_wait(2)
        try:
            ... do stuff ...
        finally:
            driver.implicitly_wait(old_wait)

**Comment by Dalvenjia** [comment]
I don't think `drv.implicitly_wait` is meant to be used that way, we have `WebdriverWait` + `ExpectedConditions` for that sort of things.
I think the implicit wait is for the webdriver to work correctly over slow networks, real or synthetic bandwidth throttle that take a long time to load overall

**Comment by Dude-X** [comment]
Since this is Python, write a context manager to reset your prior implicit wait.
This will not be added to the library, but if others want to add a thing under support, I am not opposed.

**Comment by snoopyjc** [comment]
Thank you!

-joe
