### ISSUE TITLE
Bug Issue

### ISSUE THREAD

**Issue by farisoft** [SeleniumHQ/selenium#7739]
## 🐛 Bug Report

I am getting this error, 

`Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from quorapy import QuoraPy
  File "C:\Users\Farath Shba\Downloads\QuoraPy-master\quorapy\__init__.py", line 1, in <module>
    from .quorapy import QuoraPy
  File "C:\Users\Farath Shba\Downloads\QuoraPy-master\quorapy\quorapy.py", line 8, in <module>
    from .login_util import login_user
  File "C:\Users\Farath Shba\Downloads\QuoraPy-master\quorapy\login_util.py", line 5, in <module>
    from selenium.webdriver.common.action_chains import ActionChains
ImportError: No module named selenium.webdriver.common.action_chains`

## To Reproduce

I am running a local script from Command Prompt from Windows 10 machine, which throws this error. 

## Expected behavior
Script should run properly.

## Test script or set of commands reproducing this issue

The issue is from https://github.com/socialbotspy/QuoraPy (quickstart.py in specific) where it throws the error.

## Environment

OS: Windows 10
Browser: NIL
Browser version: NIL
Browser Driver version: NIL
Language Bindings version: Python 2.7
Selenium Grid version (if applicable): NIL

**Comment by jsfehler** [comment]
@farisoft Did you install the project's dependencies? If you're getting this error, it means Selenium isn't installed on your machine.

**Comment by diemol** [comment]
@farisoft please raise the issue in the https://github.com/socialbotspy/QuoraPy repo so they can help you get started.
The root cause is probably what @jsfehler mentions.
