### ISSUE TITLE
IWebElement.GetAttribute() and IWebElement.Displayed throw exception on selenium github version, works fine on NuGet version.

### ISSUE THREAD

**Issue by KardoseR** [SeleniumHQ/selenium#7747]
## 💥 Regression Report

If you try to query these commands, an exception will be thrown if you are using the library cloned from github and built from visual studio. The resources "get-attribute.js" and "is-displayed.js" do not exist where they do in the NuGet version.

The reason I am using this version is that this one implements socksVersion property on the Proxy class, where the NuGet version does not, also had to modify the source myself to change the delay when executing actions from 250ms to 0, I really dont understand these inconsistencies in the code base.

## Last working Selenium version

Worked up to version: All nuget versions

Stopped working in version: Not sure but probably all github versions, it doesnt look like these resources are included

## To Reproduce

Just get a reference to any WebElement on the page and try to GetAttribute on it.

## Expected behavior

Expected these commands to run normally like they do in the NuGet version.

## Test script reproducing this issue (when applicable)

IWebElement element = null; // ANY ELEMENT HERE
var attribute = element.GetAttribute("outerHTML");
var displayed = element.Displayed;

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 78
Browser Driver version: from 2019-10-21 20:40:10
Language Bindings version: C# ?
Selenium Grid version (if applicable):

**Comment by jimevans** [comment]
Building the .NET bindings from Visual Studio is not, and never has been, sufficient to create assemblies equivalent to those created by the project build process. The JavaScript atoms files are generate by other parts of the build using Bazel. This is by design, and will not be changing.
