### ISSUE TITLE
ChromeDriver becomes "zombie" after initialization failure in C# project

### ISSUE THREAD

**Issue by JesseKPhillips** [SeleniumHQ/selenium#7748]
## 🐛 Bug Report

When creating a new Driver using the C# bindings on windows (Specifically in this case Chrome) when initialization fails, the application exits with the chromedriver continuing to run. (This combined with execution managed by gitlab results in a runner which does not complete)

## To Reproduce

The best example of this requires an incorrectly setup environment. Specifically, Install Chrome and Provide an incompatible version of the ChromeDriver

If you install Chrome 78, then install chromedriver 76.

Execute a C# application which initializes a ChromeDriver
https://stackoverflow.com/questions/58665122/stop-driver-process-after-session-not-created-this-version-of-chromedriver-on

UPDATED Example Workaround from comments:

```csharp
IWebDriver driver = null;
ChromeDriverService service = ChromeDriverService.CreateDefaultService();
try
{
    driver = new ChromeDriver(service);
}
catch (Exception)
{
    service.Dispose();
}
```

## Expected behavior

chromedriver.exe will not be in the process list.

## Environment

OS: Windows Server 2016
Browser: Chrome (may happen for others)
Browser version: 78 (and previous versions)
Browser Driver version: ChromeDriver 76 (because it should not match)
Language Bindings version: C# - 3.141.0
Selenium Grid version (if applicable): (No Grid Utilized)

**Comment by JesseKPhillips** [comment]
I wish to note that C# does not execute dispose on objects which failed construction.

**Comment by jimevans** [comment]
What happens if you use the `Dispose` method on a driver service object? To wit:

    IWebDriver driver = null;
    ChromeDriverService service = ChromeDriverService.CreateDefaultService();
    try
    {
        driver = new ChromeDriver(service);
    }
    catch (Exception)
    {
        service.Dispose();
    }

This is a workaround, to be sure, but would save from having to query for the running process.

**Comment by JesseKPhillips** [comment]
@jimevans, thanks for the suggested but the driver continues to live on.

**Comment by JesseKPhillips** [comment]
@jimevans Ignore my last comment, That is a solution which is much better than my process counting.

**Comment by vovanluan** [comment]
I have a problem similar to this. 
` driver = new ChromeDriver(service);`
throws error `OpenQA.Selenium.WebDriverException: unknown error: failed to wait for extension background page to load`
The driver is null and chrome process hangs. What can I do to kill this chrome process without driver?

**Comment by JesseKPhillips** [comment]
@vovanluan 

ChromeDriverService service = ChromeDriverService.CreateDefaultService();
try
{
    driver = new ChromeDriver(service);
}
catch (Exception)
{
    service.Dispose();
}

**Comment by vovanluan** [comment]
@JesseKPhillips 
It doesnt work for my case. 
The code fails to initialize `chromedriver.exe` and `driver` but it creates a zombie chrome.exe. I don't know how to interact with this zombie chrome.exe

**Comment by JesseKPhillips** [comment]
Sorry I missed you were talking about chrome itself. That seems like a bug in driver, I wouldn't expect there was anything you could do except the weird process counting trick I used, see the linked SO in the issue details..
