### ISSUE TITLE
Does anybody know how can I commit Documentation Translation?

### ISSUE THREAD

**Issue by lionking6792** [SeleniumHQ/selenium#7751]
## 💬 Questions and Help

Hi I'm looking forward to translate selenium documents to Korean. But, I'm not sure I can participate with in.

https://github.com/SeleniumHQ/seleniumhq.github.io/tree/master/documentation

This repsoitory gives translated version of documentation, but can I commit and PR to it?

Does anybody know about it? No pr exitst in there so, I'm not sure about it.
If anybody know please comment me.

Thanks :)

**Comment by mmerrell** [comment]
@diemol can you give some guidance here right before we close/lock?

**Comment by diemol** [comment]
Sure, hey @lionking6792, please follow this issue https://github.com/SeleniumHQ/seleniumhq.github.io/issues/19, we will post the link to the instructions during this week (some work still needs to be done).

**Comment by lionking6792** [comment]
Thanks for comment :) I'll follow that issue!
