### ISSUE TITLE
Selenium clicks above elements when running with ChromeDriver v.78

### ISSUE THREAD

**Issue by nick8704** [SeleniumHQ/selenium#7752]
## 🐛 Bug Report

After the updating from the version of Chrome 77 to 78 and, accordingly, the updating to the 78 ChromeDriver, we noticed problems when clicking on the elements. Selenium clicks on an area that is a few pixels higher from the top border of the element.
This problem does not reproduce for all elements. We did not find a pattern by which we could reproduce it for a specific set of elements. But if this problem is reproduced for any control, then this happens on an ongoing basis.
We tested this with Selenium 3.11.0 and 3.141.59 - bug reproduces identically on both versions.

## To Reproduce

Detailed steps to reproduce the behavior:

1. Use an Selenium test that involves clicking an element (button, table row etc) that is sufficiently narrow.
2. Run on Windows 10, Chrome v.78 selenium-java v.3.11.0 or v.3.141.59.
3. Clicking will be occur above the element. All clicking seems to be off expected location by a constant offset.

## Expected behavior

When you click on an element, the click should occur in the center of this element so that it is clicked.

## Environment

OS: Windows 10 (64-bit)
Browser: Chrome
Browser version: 78.0.3904.87 (Official Build) (64-bit)
Browser Driver version: ChromeDriver 78.0.3904.70
Language Bindings version: Java v.1.8.0_192

**Comment by tburiak** [comment]
I have the same problem.

**Comment by barancev** [comment]
Please report this issue to chromedriver project
https://chromedriver.chromium.org/help

(Also I want to note that I can't reproduce this issue, the Selenium regression tests pass for me locally on Windows 10, and they pass on CI server with Linux too)
