### ISSUE TITLE
TypeError: can't access dead object on firefox 70

### ISSUE THREAD

**Issue by Naumansh** [SeleniumHQ/selenium#7755]
## 🐛 Bug Report

**driver.findElements** is expected not to throw any exception even if the element is not present on page. However, with firefox if you have not yet switched to relevant iframe or default content and you try to validate element presence using **driver.findElements**, WebDriverException:TypeError: can't access dead object is thrown.

-->

## To Reproduce

Detailed steps to reproduce the behavior:

1- be on any webpage.
2- do driver.findElements for any locator which is not in current context.

## Expected behavior
It should not throw any exception rather should return an empty arrayList if element is not present or locator is not correct.

## Environment

OS: OSX
Browser: Firefox
Browser version: 70.0.1
Browser Driver version:  GeckoDriver 0.26 
Language Bindings version: Java 3.141.59

**Comment by barancev** [comment]
Please include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by Naumansh** [comment]
@barancev I am not able to share SSCCE due to organizational restrictions. However, below link does refer to this isuse (Second last post specifically on the page refers to selenium)
https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/
If it still doesn't make sense , please consider to close this issue.

**Comment by barancev** [comment]
Your point one "be on any webpage" implies that the isssue can be reproduced on a public page, so you don't have to share any proprietary information.

**Comment by okyrylenko** [comment]
based on selenium docs - https://www.w3.org/TR/webdriver/#find-elements no such element exception can be thrown in the following situation - If start node is null, return error with error code no such element.

**Comment by Naumansh** [comment]
@okyrylenko To this date and version 3.141.59 there is no error thrown for no such element using findElements. Secondly this issue is very specific to Firefox and it's a random error which sometimes is thrown and otherwise everything goes smooth. 

@barancev I am trying to share a SSCCE with consistent failure with this error but i believe this error comes up when the page loading is still in progress although the DOM is loaded and element is present. So this behaviour is really hard to re-produce with certain steps. It is really a random failure.

**Comment by AutomatedTester** [comment]
Closing as the requested info was not given
