### ISSUE TITLE
mobileEmulation doesn't work as it should

### ISSUE THREAD

**Issue by alissonlinneker** [SeleniumHQ/selenium#7758]
When defining a mobile device, such as iPhone X, the site does not function as if it were on a mobile device.

It only works if I activate the "Toggle device toolbar" button: https://i.stack.imgur.com/Up2rI.png

What should I do?

OS: macOS Catalina 10.15.1
Browser: Chrome
Browser version: 78.0.3904.97
Browser Driver version: 78.0.3904.70
Language Bindings version: PHP 7.3.10
Selenium Grid version (if applicable): 4.0.0-alpha-2

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
