### ISSUE TITLE
/sessions call does not return the right active sessions with the firefox

### ISSUE THREAD

**Issue by arpit-dhandhania** [SeleniumHQ/selenium#776]
Hi 

I use the /sessions command as stated @ https://code.google.com/p/selenium/wiki/JsonWireProtocol#/sessions for getting the list of active sessions. 

The returned sessions are not active atall. 

I tried to confirm this by trying to re-use the session using the sessions id and I am getting the exception as Cannot re-use the firefox driver after quit. 

I tried to upgrade the selenium to latest 46 version as well but still the issue exists

When i fire the /sessions command, currently it returns something aroung 40-45 active session every thing of firefox, but On accessing the machine physicallyI am able to see that there is no active session on the machine. 

This is happening only with firefox as observed so far. Is there something which I am doing wrong here ?

**Comment by arpit-dhandhania** [comment]
any update on this one ?

**Comment by lukeis** [comment]
If you have questions please ask on the selenium-users mailing list. Otherwise an issue is a poor place for support. 

Also there are currently very few active contributors working on selenium grid related items, I would suggest looking through the source code for the answers you are seeking.

**Comment by barancev** [comment]
/sessions endpoint is not included in the W3C Webdriver standard and will never be implemented.
