### ISSUE TITLE
Expose Server components over JMX

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7761]
We have the `ManagedService` annotation that used to be used expose the old selenium server via JMX. We should make the new server equally manageable.

**Comment by samueltauil** [comment]
I have interest on that to capture info from JMX and send to Prometheus then been able to build a custom chart

**Comment by amiluslu** [comment]
Can you give me a little bit details about this issue ? If you give me a little bit details or clue, hints, I can start to fix.

**Comment by shs96c** [comment]
@amiluslu we discussed this a little on the Slack channel. Do you still need some help getting started? I'm happy to provide more information if needed.

**Comment by pujagani** [comment]
The older Grid had the following managed services and attributes.

 - Hub as a managed service. 
			 - Managed attribute :
	 - Configuration
	 - Session request count
 - DefaultRemoteProxy as managed service :
			- Managed attributes:
	- Proxy status (alive or no)
- It extends the BaseRemoteProxy. BaseRemoteProxy has managed attributes:
	 - Max number of sessions 
	 - Remote host
	 - Total number of used slot
	 - Total number of slots
	 - Proxy status
	 - Resource usage counted as (total no of used slots/ max number of sessions) * 100
	 - The last session start time
- SeleniumServer which is an implementation of GridNodeServer as a managed service.

The new Grid can have analogous managed services and attributes as follows:

 - Each server of grid servers can be a managed service :
	 - DistributorServer 
	 - Hub  server
	 - SessionMapServer 
	 - Standalone server
	 - NodeServer 
	 - RouterServer
	 - NewSessionQueuer Server 
	 - EventBus 
 - All above-listed components share config values in BaseServerOptions. These config values can be exposed as managed attributes. 
 - Each individual components have additional component-specific attributes, which can be exposed as managed attributes.
 - The Distributor is aware of the Grid model. Grid specific attributes can be exposed by leveraging Grid model.
 - Information specific to a Node like max session count, slot information and availability can be obtained from via node implementations.

These are the observations and suggestions so so far. Can I get some help in understanding if this aligns with the intended feature? Please provide any other details I might have missed.

**Comment by diemol** [comment]
Fixed via #8838
