### ISSUE TITLE
Using webdriver.get() twice yields not the same as using it only second time

### ISSUE THREAD

**Issue by BorelConstruction** [SeleniumHQ/selenium#7766]
## 🐛 Bug Report
Consider the code:

from selenium import webdriver
browser = webdriver.Chrome(executable_path=r'D:\chromedriver.exe')
\# browser.get('https://www.flashscore.com/match/Wd0t1Cq9/#odds-comparison;1x2-odds;full-time')
browser.get('https://www.flashscore.com/match/AmZv2fcT/#odds-comparison;1x2-odds;full-time')
onextwo = browser.find_element_by_id('odds_1x2')
print('\nOkay')

It outputs "Okay" with no exceptions thrown. However, uncommenting first "get" gives me the following mistake: 
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"odds_1x2"}
  (Session info: chrome=78.0.3904.97)
  (Driver info: chromedriver=78.0.3904.70 (edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}),platform=Windows NT 6.1.7601 SP1 x86_64)
Second page seems to be loaded normally though.

Similar thing happens with Firefox and Ie drivers. 

## Environment

OS: Windows 7 64bit
Browser version: 78.0.3904.97
Browser Driver version: 78.0.3904.70
Language Bindings version: Python 3.7.4  
Selenium Grid version (if applicable):

**Comment by barancev** [comment]
This is a speeding issue, you can enable implicit waits to overcome it.
