### ISSUE TITLE
Enhanced PageFactory / Support of (nested) PageFragements

### ISSUE THREAD

**Issue by tandraschko** [SeleniumHQ/selenium#7769]
## 🚀 Feature Proposal

Currently the PageFactory does not support nesting of custom types (a.k.a. page fragement).
Whats currently supported by Selenium Java is:
- Page1
   - WebElement a
   - WebElement b
   - WebElement c

but not:
- Page1
   - MyPageFragement1
     - WebElement a
   - MyPageFragement2
     - WebElement b

## Motivation

Page Fragements is a pattern that was promoted by Arquillian Graphene (http://arquillian.org/arquillian-graphene/#_page_abstractions) and is really very nice to work with.
It has some great benefits:
  - Fragements are reusable, grouped components (something like "composite components" in the JSF world)
  - it makes it much more readable

## How can we support it?

Currently the PageFactory does:
- Loop all fields of the instantiated page parameter
- Check if @FindBy is present and make use of the ElementLocator, to resolve a WebElement via a Interceptor; a proxy is generated by the java default proxies, which only supports interfaces

What PageFactory could do:
- Loop all fields of the instantiated page parameter
- Check if @FindBy is present
- Create a Proxy via ByteBudy, which is really easy and supports also classes (we need to do this recursive, to also support nesting of fragments)
- Apply a interceptor, which delegates all calls of a WebElement to the ElementLocator; all calls of a method which is not from WebElement, will be delagated to the orignal method in the page fragement
- We should also allow custom @FindBy annotations (i need something like @FindByParentPartialId)

With this change, something like this is easy possible:

https://gist.github.com/tandraschko/8eaaea0a55846a48293dd99a61c8182b

**Comment by tandraschko** [comment]
I already have implemented this with my own PageFactory, however it would be great to have it directly in Selenium.

I can work on it.

**Comment by kalgon** [comment]
Is byte-buddy really necessary?
Can't that feature be implemented with a custom `FieldDecorator` like [this one](https://gist.github.com/kalgon/0f665de86aa78fb0642973f8b2a98535)?

**Comment by tandraschko** [comment]
I think so, to make the findby lazy.
I implemented it Here: https://github.com/primefaces/primefaces/tree/master/primefaces-selenium

**Comment by titusfortner** [comment]
PRs welcome for this, but additional page factory work is not on our roadmap.
