### ISSUE TITLE
addCookie doesnt work with IE

### ISSUE THREAD

**Issue by arpit-dhandhania** [SeleniumHQ/selenium#777]
Hi

the addCookie method doesnt work with IE latest 46 driver as well as latest 46 server standalone. 

Can some-one please check on this ?

**Comment by jimevans** [comment]
It's working well in the [continuous integration](http://ci.seleniumhq.org:8080/) builds of the project. You'll need to provide much more information, including a reproducible test case, for there to be any action that can be taken on this.
