### ISSUE TITLE
Issue with selenium UI tests performance in IE11

### ISSUE THREAD

**Issue by pk-saxena** [SeleniumHQ/selenium#7770]
Hi
I am facing significant performance issues while running UI tests in IE11. I am aware that IE11 is the slowest compared to other browsers. But the fact that a test that takes 5 mins in chrome is taking 60 mins in IE11 makes me wonder if there is something I can do to bridge the gap.

Things I am doing:
1. Using css selectors
2. Using 32 bit IE driver (3.14.0) in 64 bit windows server 2019 machine. Instantiating IE driver instance IE11 node by executing the command: 
`java -Dwebdriver.ie.driver="C:\Users\prate\Downloads\IEDriverServer.exe" -jar selenium-server-standalone-3.141.59.jar -port 5555 -role node -hub http://<hub ip>/grid/register -browser "browserName=internet explorer,version=11,platform=WINDOWS"`

3. I read that the two most expensive methods are getText() and isDisplayed() so they should be used very little. I admit to using them a lot. I tried to replace getText with something like `document.querySelector('.RichEditor-editor').innerText` but didn’t see much improvement in performance.

4. The capabilities object which is being used:
  capabilities: [
    {
      browserName: 'internet explorer',
      platformName: 'WINDOWS',
      logLevel: debug,
      'se:ieOptions': {
        'ie.ensureCleanSession': true,
        'ie.requireWindowFocus': true,
        'ie.enablePersistentHover': false,
        'ie.nativeEvents': false,
        ignoreZoomSetting: true,
        ignoreProtectedModeSettings: true
      }
    }
  ]

I am using webdriverio framework.
Is there any thing else I can try to somewhat speed up my tests?

**Comment by okyrylenko** [comment]
I believe it is iedirver issue not a WebDriver. All webdriver do is sending requests to the driver and getting a response. Everything that is done in a browser itself is the responsibility of IE driver.

**Comment by pk-saxena** [comment]
Yes seems so. I am wondering if anyone faced similar issue and managed to mitigate it somehow?

**Comment by jimevans** [comment]
Without a reproducible case, including both Selenium code (in any language) **_and_** a page to test against (either by supplying the HTML or via a publicly accessible URL), it will be nearly impossible to take any action here.

**Comment by diemol** [comment]
Closing as we didn't get any information on how to reproduce the issue.
