### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement when using perform method of Actions class

### ISSUE THREAD

**Issue by Taqueem** [SeleniumHQ/selenium#7774]
## 🐛 Bug Report

I am getting UnsupportedCommandException when using the perform method of the action class

Chrome version : 78
Build info: version: '3.141.59'

## To Reproduce

org.openqa.selenium.UnsupportedCommandException: sendKeysToActiveElement
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-AHAMQL5', ip: '172.26.147.129', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_192'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:218)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:35)
	at org.openqa.selenium.remote.RemoteKeyboard.sendKeys(RemoteKeyboard.java:38)
	at org.openqa.selenium.interactions.SendKeysAction.perform(SendKeysAction.java:56)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:34)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:642)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)

Detailed steps to reproduce the behavior:

## Expected behavior

Its working fir in chrome version 75

## Test script or set of commands reproducing this issue

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links with are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: Windows 10 
Browser: Chrome 
Browser version: 78.0.3904.97 
Browser Driver version: ChromeDriver 78.0.3904.70

**Comment by Harsha509** [comment]
Hi @Taqueem 

There are few legacy API like (sendKeysToActiveElement) deprecated from chrome 75. You can try using like this

driver.findElement(By.cssSelector("[name="q"]")).sendKeys("q" + Keys.ENTER);

Thanks!

**Comment by barancev** [comment]
Please include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/

**Comment by vlad230** [comment]
This issue is reproducing for me as well, but only when I use the RemoteDriver to execute tests. For regular driver (on local machine for Chrome 80.0) it works fine.

Example code using actions:
`Actions actions = new Actions(driver);
actions.keyDown(Keys.COMMAND).click(sourceElement).keyUp(Keys.COMMAND).perform();`

Like OP said, the exception appears when the perform() method is invoked.
Please fix.

**Comment by wilmargutierrez** [comment]
I am facing the same problem while trying to run the tests with Chrome v80.0 on BrowserStack (RemoteDriver).
It works perfectly fine with Chrome, same version, local machine.

The instruction I'm trying to use:

`action.sendKeys(textFieldDateForPostponement, postponementDate).build().perform();`

I hope a fix for this is on its way.

**Comment by vlad230** [comment]
@wilmargutierrez if you're not required to use the latest Chrome, you can run it with Chrome 74 and it works fine. This is what I ended up doing.

**Comment by wilmargutierrez** [comment]
@vlad230 thanks a lot! That's exactly what I'm trying to implement right now, so that the tests run on BrowserStack. Fingers crossed :)

**Comment by AutomatedTester** [comment]
This is just a mismatch of client bindings and browser. If you get this I suggest upgrading selenium or downgrading the browser

**Comment by wilmargutierrez** [comment]
@AutomatedTester then why does it work via custom browser without changing either of them?
