### ISSUE TITLE
Remove "prompts.tab_modal.enabled" from Java's default Firefox preferences

### ISSUE THREAD

**Issue by whimboo** [SeleniumHQ/selenium#7776]
## 🐛 Bug Report
For the Java bindings the preference [prompts.tab_modal.enabled](https://github.com/SeleniumHQ/selenium/blob/8a0691f55df5868b518e0f53c3c90b6251607dd4/third_party/js/selenium/webdriver.json#L38) gets set to false. This should not be done anymore given that this is an unsupported mode in Firefox. For a very long time this preference already defaults to `true` in Firefox, and when disabling it as done here for the FirefoxProfile in Java unexpected side-effects can happen with geckodriver. See https://github.com/mozilla/geckodriver/issues/1623 as example.

@shs96c or @barancev could you both please have a look at it? I would kinda appreciate if we can get this removed. If you can't please let us know why exactly. Thanks.

**Comment by shs96c** [comment]
This is used by the old XPI driver, so we can't just remove it, but I suspect that we could do away with using the defaulted settings from this JSON with geckodriver.

**Comment by whimboo** [comment]
Please note that for geckodriver we set our own default preferences. And these are two types:

1) Preferences which have to be set *before* Firefox is getting started: https://searchfox.org/mozilla-central/source/testing/geckodriver/src/prefs.rs

2) Preferences which do not require a restart of Firefox (recommended preferences): https://searchfox.org/mozilla-central/rev/6566d92dd46417a2f57e75c515135ebe84c9cef5/testing/marionette/components/marionette.js#68-289

**Comment by barancev** [comment]
Closing the issue as the reference issue https://github.com/mozilla/geckodriver/issues/1623 was closed.

**Comment by whimboo** [comment]
Why should this be done? It's not as long as the tab modal dialogs are getting disabled by the Selenium generated profile. The geckodriver was just fixed by avoiding the usage of `FirefoxProfile` in Selenium.

It would be great to not force those preferences for tests which are using geckodriver, which itself already sets all the required preferences. As I got from IRC only the old Firefox driver should be affected.

Not sure how many people are actually using this generated profile, but this *again* is triggering unsupported features in Firefox. @shs96c and @barancev please consider a solution which doesn't put people into such a situation, and reopen this issue. Thanks!

**Comment by barancev** [comment]
How are these preferences forced? Do you mean "set by default in a new `FirefoxProfile` instance"? Using `FirefoxProfile` is not required (and is not recommended) to instantiale a geckodriver-based `FirefoxDriver`.

**Comment by whimboo** [comment]
Yes, that's what I mean. Can you please point me to the documentation which says that FirefoxProfile should **not** be used for geckodriver? I have seen lots of reports in the past for the Java bindings which all seem to still use `FirefoxProfile`.

**Comment by barancev** [comment]
Well, I don't know how to answer this question ;)

There is no documentation which says explicitly that `FirefoxProfile` should **not** be used for geckodriver.

But the javadoc for `FirefoxDriver` and `FirefoxOptions` show the recommented way to pass preferences:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L58-L63

**Comment by whimboo** [comment]
Could we somehow log a deprecation warning for `FirefoxProfile` when Marionette is set to true? Maybe that's more eye-catching for people.

**Comment by barancev** [comment]
It's not competely deprecated, there is one important case when people can use `FirefoxProfile` with the geckodriver-based `FirefoxDriver` - if they want to use a pre-populated profile.

**Comment by barancev** [comment]
But I'll try to figure out if we can add more warnings to the log that would prevent ineffective use of `FirefoxProfile`.

**Comment by whimboo** [comment]
Thanks!

**Comment by whimboo** [comment]
Any update here? It would be great to completely see this preference gone for FirefoxProfile. In Firefox it has been enabled ages ago (way before we started geckodriver), and as such reversing it causes troubles in various areas.

**Comment by AutomatedTester** [comment]
We've deprecated the necessary, we can't do more than that for a while so closing as deprecated code has a process to be removed. see caeae219b377eccb5a6b3ef0a0c2bb293d4dd4d7
