### ISSUE TITLE
support for CDP in python

### ISSUE THREAD

**Issue by anbuhckr** [SeleniumHQ/selenium#7777]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by AutomatedTester** [comment]
There is already support for executing CDP commands

**Comment by anbuhckr** [comment]
java already have Basic support for CDP landed via the "DevTools" interface, so it have more advanve functin like addlistener on cdp session.
mybe python will update too?
