### ISSUE TITLE
Grid UI

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7779]
The Grid needs a UI of some sort to allow people to control it remotely. This should not rely on JMX.

**Comment by shs96c** [comment]
We recently relaunched the website, and have had a bunch of branding and assets produced. It'd be nice if the UI reused those components where appropriate.

**Comment by shs96c** [comment]
Since the UI will ship inside the regular selenium server jar, we should endeavour to keep the size of the UI as compact as possible.

**Comment by phanirithvij** [comment]
Working on this outside the mono repo. Will send a PR once I get bazel build working with react.
cc @AutomatedTester
