### ISSUE TITLE
ChromeDriver tests are not included in Bazel build

### ISSUE THREAD

**Issue by TriciaCrichton** [SeleniumHQ/selenium#7785]
## 🐛 Bug Report

The new bazel build doesn't build the ChromeDriver tests in java/client/test/org/openqa/selenium/chrome/

## To Reproduce

run bazel build java/...
The Chrome*Test.classes are not built or added to any jar.

We have a PR to add the Chrome tests.

**Comment by TriciaCrichton** [comment]
We are seeing a problem with ChromeOptionsFunctionalTest in the new environment. The tests uses a crx file found in third_party/chrome_ext, but this is no longer found when running in the bazel test setup.

Can someone tell us how to properly reference files in third_party/ from the java/ tree?

Thanks

**Comment by barancev** [comment]
Fixed time ago by commit 36105a01275c4f3f81bcd7d1b03430210f22a675
