### ISSUE TITLE
target frame detached

### ISSUE THREAD

**Issue by LuanShiZhiJian** [SeleniumHQ/selenium#7786]
### Please note that this issue tracker is not a help form and this issue will be closed.

**I don't understand the error message that "selenium.common.exceptions.WebDriverException: Message: target frame detached" and not solution found about it，Would you please advise?** 

![image](https://user-images.githubusercontent.com/41558924/68846327-dd77c180-0707-11ea-9776-980a337ab6eb.png)

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by LuanShiZhiJian** [comment]
Hi @barancev , Do you know how to solve the problem?

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
