### ISSUE TITLE
Returned value cannot be converted to Boolean: {} on isDisplayed() method.

### ISSUE THREAD

**Issue by Julioevm** [SeleniumHQ/selenium#7787]
## 🐛 Bug Report

Using the isDisplayed() method is returning this error: Returned value cannot be converted to Boolean: {}
I find that this happens on several elements on the site I test.

## To Reproduce

Run the test on the attached project from the repo I made to reproduce the issue.

## Expected behavior

isDisplayed() should return true or false.

## Test script or set of commands reproducing this issue

https://github.com/Julioevm/selenium_java_error

## Environment

OS: Ubuntu 18.04
Browser: Chrome
Browser version: 78.0.3904.70
Browser Driver version: ChromeDriver 78.0.3904.70
Language Bindings version: Java 3.141.59

**Comment by barancev** [comment]
Please report this issue to chromedriver project:
https://bugs.chromium.org/p/chromedriver/issues/list
