### ISSUE TITLE
Not working using chromium on Ubuntu 19.10 (snaps package)

### ISSUE THREAD

**Issue by michaelzangl** [SeleniumHQ/selenium#7788]
## 🐛 Bug Report

Ubuntu 19.10 installs chromium/chomedriver as snap package.

Chrome running in snaps has a separate /tmp directory and does not share the /tmp directory with the system.
Therefore, the browser cannot see the profile that was created in /tmp when using the default webdriver. Ubuntu provides a patched webdriver.

## To Reproduce

Use Ubuntu 19.10
```bash
apt-get install chromium-browser chromium-chromedriver
```
Run a java program:
```java
System.setProperty("webdriver.chrome.driver", "/snap/bin/chromium.chromedriver");
new ChromeDriver();
```

## Expected behavior

It should work start a new chrome browser

## Actual behavior

The process fails to start with the error message:
```
Error: unknown flag `port'
Nov. 14, 2019 2:06:43 NACHM. org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
Timed out waiting for driver server to start.
```

The problem is, that the driver service resolves the symlink from /snap/bin/chromium.chromedriver to /usr/bin/snap:
```java
this.executable = executable.getCanonicalPath();
```

It then executes the command:
```bash
/usr/bin/snap --port=…
```

snap attempts to find out which program acutally got called by examining the command line (args[0]), does not find chromedriver there and can therefore not start the chromedriver

## Workaround

```java
 		new ChromeDriver(
				(ChromeDriverService)(new ChromeDriverService.Builder() {
					@Override
					protected File findDefaultExecutable() {
						if (new File("/snap/bin/chromium.chromedriver").exists()) {
							return new File("/snap/bin/chromium.chromedriver") {
								@Override
								public String getCanonicalPath() throws IOException {
									return this.getAbsolutePath();
								}
							};
						} else {
							return super.findDefaultExecutable();
						}
					}
				}).build() /*, options */);
```

## Environment

OS: Ubuntu 19.10 (amd64)
Browser: Chromium
Browser version: Chromium 78.0.3904.97 snap
Browser Driver version: ChromeDriver 78.0.3904.97 (021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859})
Language Bindings version: '4.0.0-alpha-3', revision: '8c567de6dc'
Java version: '11.0.2'

**Comment by lsabi** [comment]
I have the same settings, except that I'm using python 3.7 and I get 

> Failed to load extension from: . Manifest file is missing or unreadable

The code used to run before upgrading Chromium from the deb to snap package format.

**Comment by michaelzangl** [comment]
@Isabi You are using the wrong chrome driver (the normal one). You need to use the chromedriver included in the snaps package.

**Comment by lsabi** [comment]
Now I managed to make it work. Sorry for posting in the wrong section then, I couldn't find anything about selenium and snap chromium, so I thought I had the same error.

Sorry

**Comment by DenEwout** [comment]
The workaround suggested by @michaelzangl seems to work for me, but after applying it I am greeted by the following error:

```
Starting ChromeDriver 79.0.3945.79 (29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}) on port 28675
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
org.openqa.selenium.WebDriverException: unknown error: no chrome binary at /snap/bin/chromium
  (Driver info: chromedriver=79.0.3945.79 (29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916}),platform=Linux 5.3.0-24-generic x86_64) (WARNING: The server did not provide any stacktrace information)
```

Any ideas?

**Comment by tvaidotas** [comment]
Good workaround, but I had to add chrome options to get it to work for me. Thanks @michaelzangl 

This is my before method if you had issues getting it to work just with the @michaelzangl workaround

`    @Before
    public void setup() {
        if (isLinux()){
            System.setProperty("webdriver.chrome.driver", "/snap/bin/chromium.chromedriver");
        } else {
            System.setProperty("webdriver.chrome.driver", "./chromedriver.exe");
        }
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--remote-debugging-port=9222");

        driver = new ChromeDriver(
                (ChromeDriverService)(new ChromeDriverService.Builder() {
                    @Override
                    protected File findDefaultExecutable() {
                        if (new File("/snap/bin/chromium.chromedriver").exists()) {
                            return new File("/snap/bin/chromium.chromedriver") {
                                @Override
                                public String getCanonicalPath() throws IOException {
                                    return this.getAbsolutePath();
                                }
                            };
                        } else {
                            return super.findDefaultExecutable();
                        }
                    }
                }).build(), options );
    }

    public boolean isLinux(){
        String os = System.getProperty("os.name").toLowerCase();
        return os.contains("win");
    }`

**Comment by ghost** [comment]
I found a way to work around it.
Just do this:

```bash
    cd /snap/bin ;
    sudo ln -s chromium.chromedriver chromedriver ;
```

Now everything will work fine.

**Comment by titusfortner** [comment]
I'm probably missing something here, but shouldn't you be able to use:

```
new ChromeDriverService.Builder().usingDriverExecutable("/snap/bin/chromium.chromedriver").build();
```

**Comment by pujagani** [comment]
Reopened since a duplicate issue #10969 was created and the solutions here did not solve it.

**Comment by pujagani** [comment]
Github locked the conversation so had to close it.

**Comment by titusfortner** [comment]
To add clarification to this issue... There are package installers that require their own driver be used. You likely will need to [specify the exact location of this driver in your Selenium code](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#3-hard-coded-location). You may also need to ensure that this driver is referencing the correct browser by specifying the `binary` in the Options class to point to the browser you want.

Optionally, as referenced earlier, the WebDriverManager tool has an automated solution, and we recommend using that tool at this time.
