### ISSUE TITLE
finding an image and click on on image takes more time  in webdriver

### ISSUE THREAD

**Issue by anandkatti** [SeleniumHQ/selenium#779]
We found that when clicking on <img alt>  in page from webdriver takes longer time. Currently we observed that , it is taking around 10 mins to find an image and click on it.

Here is sample test case 

Webdriver.findElement(By.xpath("xpath=//img[@alt='Application Performance Monitoring']").click();

**Comment by lukeis** [comment]
this is not a test case, that's one line. You would need to provide a link to the page or the html itself for us to profile the performance issue.

But mostly you're probably hitting a performance issue with your xpath selector. Can you try to emailing the selenium-users list and hash it out there and then come back and log something a little more concrete.

https://groups.google.com/forum/#!forum/selenium-users

**Comment by anandkatti** [comment]
Luke ,

we are blocked by this perf issue.  below is brower Logs.  Could not get much help from sel users forum. 

Could you pleae ehlp me here  
Proxy auth state: UNCHALLENGED
http-outgoing-37 >> POST /hub/session/64ce3a68-9fe5-42d3-a87b-4ee5800c1fae/element HTTP/1.1
http-outgoing-37 >> Content-Type: application/json; charset=utf-8
http-outgoing-37 >> Content-Length: 91
http-outgoing-37 >> Host: localhost:7055
http-outgoing-37 >> Connection: Keep-Alive
http-outgoing-37 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
http-outgoing-37 >> Accept-Encoding: gzip,deflate
http-outgoing-37 >> "POST /hub/session/64ce3a68-9fe5-42d3-a87b-4ee5800c1fae/element HTTP/1.1[\r][\n]"
http-outgoing-37 >> "Content-Type: application/json; charset=utf-8[\r][\n]"
http-outgoing-37 >> "Content-Length: 91[\r][\n]"
http-outgoing-37 >> "Host: localhost:7055[\r][\n]"
http-outgoing-37 >> "Connection: Keep-Alive[\r][\n]"
http-outgoing-37 >> "User-Agent: Apache-HttpClient/4.3.6 (java 1.5)[\r][\n]"
http-outgoing-37 >> "Accept-Encoding: gzip,deflate[\r][\n]"
http-outgoing-37 >> "[\r][\n]"
http-outgoing-37 >> "{"using":"xpath","value":"//img[@alt\u003d\u0027Application Performance Monitoring\u0027]"}"
XToolkit.callTimeoutTasks(): current time=1436950738583;  tasks=null
XToolkit.callTimeoutTasks(): current time=1436950739084;  tasks=null
.
.
.
XToolkit.callTimeoutTasks(): current time=1436950937902;  tasks=null
XToolkit.callTimeoutTasks(): current time=1436950938403;  tasks=null
http-outgoing-37 << "[read] I/O error: Read timed out"
http-outgoing-37: Close connection
http-outgoing-37: Shutdown connection

**Comment by lukeis** [comment]
To get help in the issues on github you must provide a /complete/ reproducible test case. This would include all relevant version numbers (selenium, browser, os), a site or html page, and a runnable test script showing the issue.
