### ISSUE TITLE
Zooming browsers using short cut keys such as "CMD+" does not work

### ISSUE THREAD

**Issue by Nick-Gottschlich** [SeleniumHQ/selenium#7793]
## 🐛 Bug Report

Hello,

I am trying to use selenium to control a browser programatically. I would like to be able to send the keys "CMD-" (or "CTRL-") to zoom out. I have tried every different way I can think of of sending these keys with no luck. I have tested this on both chromedriver and geckodriver on my macbook, and on geckodriver on my raspberry pi.

It looks like this closed issue was reporting a similar bug: https://github.com/SeleniumHQ/selenium/issues/4244

## Expected behavior

I would expect that sending the `COMMAND` and `SUBTRACT` keys together would zoom out on mac. Or sending the `CONTROL` and `SUBTRACT` keys together would zoom out on windows/linux.

See the script below to see all the code I've used to try and get this functionality to happen.

## Test script or set of commands reproducing this issue

Python script:

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
import time

browser = webdriver.Chrome(
    executable_path='/Users/nicholasgottschlich/Library/SeleniumWebdrivers/chromedriver')
# browser = webdriver.Firefox(
#     executable_path='/Users/nicholasgottschlich/Library/SeleniumWebdrivers/geckodriver')


def doit():
    browser.get('https://google.com')

    time.sleep(1)

    print('start')
    actions = ActionChains(browser)
    # actions.send_keys(Keys.COMMAND).perform()
    # actions.key_down(Keys.COMMAND).send_keys(Keys.SUBTRACT).perform()
    # actions.key_down(Keys.COMMAND).send_keys('_').perform()
    # actions.send_keys(Keys.COMMAND, Keys.SUBTRACT, Keys.NULL).perform()
    # actions.key_down(Keys.COMMAND).send_keys(Keys.SUBTRACT, Keys.NULL).perform()
    # actions.send_keys(Keys.COMMAND + Keys.SUBTRACT).perform()
    # actions.send_keys(Keys.COMMAND + Keys.SUBTRACT + Keys.NULL).perform()
    # html = browser.find_element_by_tag_name("html")
    # body = browser.find_element_by_tag_name("body")
    # print(html)
    # html.send_keys(Keys.COMMAND, Keys.SUBTRACT, Keys.NULL)
    # html.send_keys(Keys.COMMAND, '-')
    # body.send_keys(Keys.COMMAND, Keys.SUBTRACT, Keys.NULL)
    # html.send_keys(Keys.COMMAND + Keys.SUBTRACT + Keys.NULL)
    print('finish')


if __name__ == '__main__':
    doit()
```

## Environment

OS: macOS Mojave 10.14.6, Raspbian for Raspberry Pi
Browser + version: chromedriver (78.0.3904.97 (Official Build) (64-bit)) and geckodriver 70.0.1 (64-bit)
Browser Driver version: geckodriver: https://github.com/mozilla/geckodriver/releases/tag/v0.26.0 chromedriver: 78.0.3904.70
Language Bindings version: Python 3.7.4

**Comment by d0peman** [comment]
I've been scratching my head over this too. Found the solution [here](https://github.com/mozilla/geckodriver/issues/1075).

I made a quick [post over at stackoverflow](https://stackoverflow.com/a/59111830/7533707) just explaining how I managed to get this all working.

**Comment by diemol** [comment]
I am closing this as per the linked issue, this is not intended to work in recent versions. WebDriver interacts with the web page, not with the browser app itself.
