### ISSUE TITLE
Empty classifier in selenium-remote-driver et all lead to problems with sbt-launcher

### ISSUE THREAD

**Issue by hvesalai** [SeleniumHQ/selenium#7795]
## 🐛 Bug Report

The empty `clarrifier` tags in the generated `pom` file of this project lead to artifacts not being copied to the classpath by `sbt-launcher`

## To Reproduce

Create an application that depends on `selenium-remote-driver` version `3.141.59` (or any other 3.x version).

## Expected behavior

Expect jar files to be copied on to the classpath, but none are. If you manually modify the `pom` and comment out the `classifier` elements, everything works as expected.

## Environment

Selenium Grid version (if applicable): 3.141.59

Note: the empty tags have been creating problems before: https://github.com/SeleniumHQ/selenium/issues/6200

**Comment by hvesalai** [comment]
This time I hope the response it not the same as in #6200. Having empty `classifier` tags is highly irregular and while our project transitively depends on over 200 jars, none have produced this error.

**Comment by barancev** [comment]
We don't have classifier tag in 4.0 version artifacts, see for example
https://search.maven.org/artifact/org.seleniumhq.selenium/selenium-remote-driver/4.0.0-alpha-3/jar

**Comment by hvesalai** [comment]
Could that be backported to 3? We desperately need it. 

Our only other alternative is to make a private modified copy of the poms to our local artifactory. Which is less than ideal.

**Comment by barancev** [comment]
I'm afraid we'll not be able to backport it to version 3 because it uses a different build system and the current implementation cannot be backported. The only possible solution for version 3 is fixing the POM-files manually before deployment, that's exactly what you did. Sorry.
