### ISSUE TITLE
Cannot convert from AppiumOptions to DriverOptions() error when creating new AndroidDriver

### ISSUE THREAD

**Issue by nadvolod** [SeleniumHQ/selenium#7797]
## 🐛 Bug Report

I am using the [documentation here](https://github.com/appium/appium-dotnet-driver/wiki/How-to-start-an-AppiumDriver-when-the-server-is-launched-remotely-or-locally) to try and instantiate an AndroidDriver. However, I'm getting a compiler error saying "Cannot convert from AppiumOptions to DriverOptions() error when creating new AndroidDriver"

## To Reproduce

```
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;

DesiredCapabilities capabilities = new DesiredCapabilities();

capabilities.SetCapability("deviceName", "Android Emulator");
capabilities.SetCapability("platformName", "Android");
capabilities.SetCapability("app", "<Path to your app>");

AppiumDriver<AppiumWebElement> driver = new AndroidDriver<AppiumWebElement>(
                           new Uri("http://127.0.0.1:4723/wd/hub"), 
                               capabilities);
```

## Expected behavior

For the code to compile and work.

## Environment

OS: Windows 10
Language Bindings version: 4.1.1

**Comment by barancev** [comment]
Please report this issue to Appium project
