### ISSUE TITLE
Add `SameSite` attribute to `Cookie`

### ISSUE THREAD

**Issue by chlily1** [SeleniumHQ/selenium#7798]
## 🚀 Feature Proposal

`SameSite` attribute on [`Cookie`](https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Cookie.html) object

## Motivation

The [`Cookie.Builder`](https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Cookie.Builder.html) object does not accommodate a `SameSite` field, described [here](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-5.3.7) in the spec.

This makes it impossible to specify the `SameSite` field of a cookie, which can either be `None`, `Lax`, or `Strict`. This field can be specified in the `Set-Cookie` HTTP header, so the `Cookie` object should also support it.

## Example
```
Cookie cookie = new Cookie.Builder("name", "value")
    .sameSite("lax")
    .build();
```

**Comment by jmakr0** [comment]
Since [Chrome](https://www.chromium.org/updates/same-site), [Firefox](https://groups.google.com/forum/#!msg/mozilla.dev.platform/nx2uP0CzA9k/BNVPWDHsAQAJ), [Edge](https://groups.google.com/a/chromium.org/d/msg/blink-dev/AknSSyQTGYs/8lMmI5DwEAAJ) and consequently the others apply `SameSite` by default in the beginning of 2020, it would be much appreciated indeed.

**Comment by gjyalpha** [comment]
FYI. ChromeDriver has implemented the support of Cookie's `SameSite` attribute in https://bugs.chromium.org/p/chromedriver/issues/detail?id=3264

**Comment by adamklinkosz** [comment]
Any new on this one? Browsers will start to require this attribute to be set and we need to be able to test whether it is present.

**Comment by gjyalpha** [comment]
Ah, yes.

1. The WebDriver spec switched the JSON key from "samesite" to "sameSite". My previous PR followed the previous "samesite". Now we need to change it to "sameSite". I can try to make another PR to fix this.

2. Another minor issue is that no the samesite attribute accepts a string value. And in general, browser should treat these values as case insensitive values. But ChromeDriver uses Chrome DevTools Protocol (CDP) behind the scene, and CDP treats the value as case sensitive values. So we might need to consider add some normalization logic in Cookie.java to make user's life slightly easier.

**Comment by gjyalpha** [comment]
Fixing the JSON key in https://github.com/SeleniumHQ/selenium/pull/8265

**Comment by AutomatedTester** [comment]
I believe this is all fixed in all clients so closing
