### ISSUE TITLE
Click event on button on IFrame could not work and gives no error for selenium 3.141.59 on Chrome driver 78.0.3904.105

### ISSUE THREAD

**Issue by mitul494** [SeleniumHQ/selenium#7799]
While clicking on button in IFrame of custom application tab on SalesForce.com portal, Selenium click event on Button or any selectable object i.e. dropdown object could not be fired. As well, no error was thrown for this failure event.

When tried with method .sendKeys(Keys.Enter) then that object either button or selectable objects, could be worked.

I'm using Java-selenium version 3.141.59 and Chrome driver version 78.0.3904.105

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
