### ISSUE TITLE
Unable to switch to child window---Missing parameter name exception in JAVA code in Internet Explorer11

### ISSUE THREAD

**Issue by Abhinaykrs** [SeleniumHQ/selenium#7801]
Selenium server used is:selenium-server-standalone-3.141.59

I have a switchtochildwindow() function which finds the child window handle and tried to switch to it.But although the window is there its unable to switch giving exception missing parameter name.
I have tried print the strings corresponding the child window and parent window and they are different and are found while iterating through the loop but switch is not happening: exception displayed is "Unable to switch to Child Window Details: org.openqa.sel enium.WebDriv erException: Missing parameter name
Function code in JAVA is as below:
public String SwitchToChildWindow(String object, String data) {
try {

    String MainWindow = driver.getWindowHandle();
    System.out.println(driver.getTitle());
    System.out.println(MainWindow);
    Set<String> s1 = driver.getWindowHandles();
    Iterator<String> i1 = s1.iterator();
    while (i1.hasNext()) {
        String ChildWindow = i1.next();
        System.out.println(ChildWindow);
        System.out.println(driver.getTitle());

        if (!MainWindow.equalsIgnoreCase(ChildWindow)) {
            System.out.println(driver.getTitle());
            // Switching to Child window
            driver.switchTo().window(ChildWindow);
            System.out.println(driver.getTitle());

            this.Report(ResultStatus.PASS, "Switched to Child Window",
                    "Switched to Child Window", null);
        }
    }

} catch (Exception e) {
    this.Report(ResultStatus.FAIL, "Unable to switch to Child Window",
            "Unable to switch to Child Window", e.toString());
}
Exception is as follows:
Unable to
switch to Child
Window
Details:
org.openqa.sel
enium.WebDriv
erException:
Missing
parameter:
name
Build info:
version:
'3.141.59',
revision:
'e82be7d358',
time: '2018-11-
14T08:25:53'
System info:
host: 'ST-
XXXXXXXXX',
ip:
'10.79.111.209'
, os.name:
'Windows 10',
os.arch:
'amd64',
os.version:
'10.0',
java.version:
'1.8.0_221'
Driver info:
driver.version:
unknown
Command
duration or

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to:
- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
