### ISSUE TITLE
Tor browser suppoty

### ISSUE THREAD

**Issue by muhendis80** [SeleniumHQ/selenium#7803]
## 🚀 Feature Proposal

Tor browser support

## Motivation

tor browser is the best in its category but we can not use with selenium in python on windows

## Example

```
from selenium import webdriver
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary(r'c:\TorBrowser\Browser\firefox.exe')
profile = FirefoxProfile(r'C:\TorBrowser\Browser\TorBrowser\Data\Browser\profile.default')
profile.set_preference('network.proxy.type', 1)
profile.set_preference('network.proxy.socks', '127.0.0.1')
profile.set_preference('network.proxy.socks_port', 9150)
profile.set_preference("network.proxy.socks_remote_dns", True)
profile.update_preferences()
driver = webdriver.Firefox(firefox_profile= profile, executable_path=r'C:\analizer\geckodriver.exe')
driver.get("http://check.torproject.org")
```

there is a code for tor but not working

**Comment by AutomatedTester** [comment]
This is likely because the Tor project is not bundling Marionette in the final build. Marionette is the internal webdriver implementation for Firefox.

Do you need to test a specific site or have a specific feature that requires the Tor Browser?

**Comment by muhendis80** [comment]
Yes, i need specific feature of tor.. other browsers do not have. There is a tb.selenium library on the web, but it does not compatible with windows

**Comment by muhendis80** [comment]
Dear David , i want to ask a question
when i load this page from selenium it detects me and "you are robot" writes in turkish
this web site sells 2.hand things like ebay
site example:
"https://www.sahibinden.com/ilan/vasita-otomobil-audi-hatasiz-boyasiz-en-dolusu-313-hp-bayi-724162461/detay"

how can pass this robot control mechanism?

i tried selenium with chrome and firefox.. both of them are fails with selenium

**Comment by barancev** [comment]
It usually works other way round -- browser vendors create an executable driver and Selenium uses it to interact with the browser. Tor Browser is based on Gecko, so the Tor development team can use geckodriver to create their own driver. Or they can tune the browser itself to work with existing unmodified geckodriver.

**Comment by diemol** [comment]
As mentioned in previous comments, this should come from the Tor browser itself. Maybe you can [get in touch](https://support.torproject.org/get-in-touch/) with them and suggest this as a feature.
