### ISSUE TITLE
Window.Maximize works, but Window.Fullscreen doesn't work

### ISSUE THREAD

**Issue by sebastien-labbe** [SeleniumHQ/selenium#7804]
Hello,
In VBA, I try to open Chrome in full screen mode in many ways.
I have to mention that this macro is working:
`Sub Chrometest()`
`    Dim drv As New Selenium.ChromeDriver`
`    drv.Get "https://www.google.ca/"`
`    drv.Wait (1000)`
`    drv.Window.Maximize`
`    drv.Wait (1000)`
`End Sub`
However, when I switch "Maximize" for "FullScreen", it will stop at this line and return an error -2146233088 (80131500):
`Sub Chrometest()`
`    Dim drv As New Selenium.ChromeDriver`
`    drv.Get "https://www.google.ca/"`
`    drv.Wait (1000)`
`    drv.Window.FullScreen`
`    drv.Wait (1000)`
`End Sub`
How can I use the fullscreen function on Chrome with VBA?

**Comment by diemol** [comment]
@sebastien-labbe sorry, we do not provide VBA bindings. Could you please post this issue at the repository or support list where the VBA bindings are provided?
