### ISSUE TITLE
Element does not exist in cache

### ISSUE THREAD

**Issue by apulido15** [SeleniumHQ/selenium#7805]
Hi, i am executing a test in iOS Safari with appium and it show me this error:

Capabilities {autoGrantPermissions: true, automationName: XCuiTest, browserName: safari, databaseEnabled: false, deviceName: iPhone 7, dontStopAppOnReset: true, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, platform: MAC, platformName: ios, platformVersion: 12.2, takesScreenshot: true, udid: ..., webStorageEnabled: false}
Session ID: c98d2fd2-8d05-4a81-b75f-6d9d73609bd7
*** Element info: {Using=xpath, value=//*[contains(text(),'El campo es de obligatorio diligenciamiento.')]}
An unknown server-side error occurred while processing the command. Original error: Error: Remote debugger error with code 'undefined': StaleElementReferenceError: Element does not exist in cache
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: io.appium.java_client.AppiumDriver

someone knows why?

thaks

**Comment by diemol** [comment]
Please report this issue to the Appium project https://github.com/appium/appium
Also consider sending questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), or to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), where the community can help you as well.
