### ISSUE TITLE
Odd behavior noticed during UI tests with Selenium

### ISSUE THREAD

**Issue by mariankral** [SeleniumHQ/selenium#7809]
I want to ask you about the odd behavior I noticed when running multiple tests, using Visual studio, Selenium web-driver and Chrome browser.

I have all the tests written as follows:

1. sign in to the web app
2. go to desired page
3. take action on this page
4. sign out of the web app

In the older version of the browser and web-driver I started multiple tests, if one of the tests failed on the desired page (test was logged in app), after the time has passed then test was terminated and web app has been automatically redirected to the login page. Another test, in order, could be logged in and continued.

But now, with the current version of the browser and web-driver, if one of the tests failed on the desired page, the test will remain logged in the app, and another test cannot be signed in, because the web app was not redirected to the login page.

Have you noticed the same behavior? What can I do about it, how to fix it?

Thank you in advance for your ideas and assistance.

Chrome 78.0.3904.108
Selenium WebDriver 3.141.0
ChromeDriver 78.0.3904.105

**Comment by barancev** [comment]
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
