### ISSUE TITLE
IE - Browser launched URL not loading

### ISSUE THREAD

**Issue by krthknan** [SeleniumHQ/selenium#7811]
No error message in the console. The browser remains open until manually stop the execution.
Protractor Version: 5.4.2
Webdriver-manager version: 12.1.6
Node version: 10.13.0
I have tried the below IE driver versions: IEDriverServer3.150.1, IEDriverServer3.150.0, IEDriverServer3.141.59
Selenium server version: 3.141.59

Kindly help me.

**Comment by Harsha509** [comment]
hi @krthknan , can you please provide any SSCCE (Short, Self Contained, Correct (Compilable), Example) to reproduce the behavior.

**Comment by krthknan** [comment]
multiCapabilities:
        [
            {
                'browserName': 'internet explorer',
                'ignoreProtectedModeSettings': true,
                'enableElementCacheCleanup': true,
                'unexpectedAlertBehaviour': 'dismiss',
                "ie.forceCreateProcessApi": true,
                "ie.browserCommandLineSwitches": "-private",
                "ie.ensureCleanSession": "true",

            }
        ],

	
    // ieDriver:'D:\\Dev code\\pinpoint-client\\node_modules\\protractor\\node_modules\\webdriver-manager\\selenium\\IEDriverServer3.150.1.exe',
	
	 onPrepare: function () {
		browser.manage().window().maximize()
         
        
        // jasmine.getEnv().addReporter(
        //     new Jasmine2HtmlReporter({
        //         savePath: 'target/testreports/',
        //         filePrefix: 'testreport',
        //         takeScreenshots: true,
        //         takeScreenshotsOnlyOnFailures: true,
        //         screenshotsFolder: 'screenshots'
        //     })
        // );



        browser.addMockModule('disableNgAnimate', function () {
            angular.module('disableNgAnimate', []).run(['$animate', function ($animate) {
                $animate.enabled(false);
            }]);
        });

    },

}

**Comment by Harsha509** [comment]
Hi @krthknan , 

looks like you're using protractor. I have created a sample test and executed in IE it worked fine.

for more info, Can you please let me know if "protected mode" is enabled, if not follow:

1. Open Internet Explorer
2. Go to Tools menu – Internet Options
3. Select Security Tab
4. In Select a zone to view or change security settings choose Internet and select the check box of Enable protected mode (requires restarting Internet Explorer).
5. Similarly, select the check box of Enable protected mode (requires restarting Internet Explorer) for other three such as Local Intranet, Trusted sites, and Restricted site

Please make sure to check 'Enable Protected Mode' option checked for all security options. And restart IE and try to execute the test.

Thanks!

**Comment by krthknan** [comment]
Thanks @Harsha509 ,

I have enabled the protected mode for all zones and it is working fine
