### ISSUE TITLE
extension is already installed through selenium, but not working in firefox

### ISSUE THREAD

**Issue by hkglue** [SeleniumHQ/selenium#7812]
### extension is already installed through selenium, but not working in firefox,and does not throw：
`    

    firefox.install_addon("/Users/dev/dec/jid0-oEwF5ZcskGhjFv4Kk4lYc@jetpack.xpi",temporary=True)
    profile.set_preference("modifyheaders.config.openNewTab",1)
    profile.set_preference("modifyheaders.start",1)
    profile.set_preference("modifyheaders.config.migrated",1)
    
    profile.set_preference("modifyheaders.headers.count", 6)
    profile.set_preference("modifyheaders.headers.action0", "Add")
    profile.set_preference("modifyheaders.headers.name0", "urlkey")
    profile.set_preference("modifyheaders.headers.value0", "mmmmmmmmmm")
    profile.set_preference("modifyheaders.headers.enabled0", 1)
    profile.set_preference("modifyheaders.config.active", 1)
    profile.set_preference("modifyheaders.confsssig.alwaysOn",1)`
### Environment
OS: MacOS 10.13.06
Browser: Firefox
Browser version: 66.0.2
Browser Driver version: GeckoDriver 0.24
Language Bindings version: Java 8
Selenium Grid version (if applicable): 3.141.59
For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to:
- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
