### ISSUE TITLE
System.NotImplementedException : mouseMoveTo

### ISSUE THREAD

**Issue by AnthonyDewhirst** [SeleniumHQ/selenium#7813]
## 🐛 Bug Report

When using RemoteWebDriver and Actions and Move, we get the following error
System.NotImplementedException : mouseMoveTo

## To Reproduce
Simple App with the following class:

```csharp
using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Remote;

namespace SeleniumBugRepro
{
    [TestFixture]
    public class BugRepro
    {
        private Uri _gridUri = new Uri("http://<Yourgrid>/wd/hub/");

        [Test]
        public void Example()
        {
            // Arrange
            using (var driver = new RemoteWebDriver(_gridUri, new ChromeOptions().ToCapabilities()))
            {
                // Act
                driver.Navigate().GoToUrl("https://www.bbc.com/news");
                var element = driver.FindElement(By.Id("brand"));
                var actions = new Actions(driver);
                actions.MoveToElement(element);
                actions.Perform();
            }
        }
    }
}
```

And the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="Selenium.Support" Version="3.141.0" />
  </ItemGroup>

</Project>
```

Detailed steps to reproduce the behavior:

Run the test

## Expected behavior

The test to pass which it does if you use ChromeDriver

## Error

System.NotImplementedException : mouseMoveTo
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SeleniumNode8', ip: '10.0.0.7', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_231'
Driver info: driver.version: RemoteWebDriver
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteMouse.MouseMove(ICoordinates where)
   at OpenQA.Selenium.Interactions.CompositeAction.Perform()
   at SeleniumBugRepro.BugRepro.Example()

## Environment
Selenium
Grid Console v.3.141.59

**Comment by diemol** [comment]
Hi @AnthonyDewhirst 
The error log says `Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'`, so it seems that the Grid version being used is quite old. Could you try to upgrade and try again?

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
