### ISSUE TITLE
Enable Nodes to be configured via command line and settings file

### ISSUE THREAD

**Issue by shs96c** [SeleniumHQ/selenium#7814]
Right now, it's only possible to configure the Node instances to use Docker or to automatically detect drivers. This should be configurable. It would be nice if the key information from the original `nodeConfig.json` files could be used, but we can also explore other options.

**Comment by shs96c** [comment]
The configuration should mirror (where appropriate) the functionality from Grid 3

**Comment by kovalev007** [comment]
@shs96c can you describe why it closed? It is completed and we have commit(s)?

**Comment by diemol** [comment]
More info can be seen here:
https://github.com/SeleniumHQ/selenium/issues/8125
https://github.com/SeleniumHQ/selenium/issues/8232
