### ISSUE TITLE
file upload PhantomJSDriver

### ISSUE THREAD

**Issue by unabombergt** [SeleniumHQ/selenium#782]
Hello.
I would like to upload file image profile with PhantomJSDriver in vb net project (or c#)

html code is this: 

<input type="file" name="file" style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0;">

My .net code is this: 

Dim d As IWebDriver = New PhantomJSDriver(service, opzioni)
d.Navigate.GoToUrl(uri)
Dim elem As IWebElement = d.FindElement(By.XPath("//input[@type='file']"))          
Threading.Thread.Sleep(250)
elem.SendKeys(f)

I obtain this exception: 
07/2015 19:13:56: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:54874/session/6f8d4070-2a4b-11e5-a69c-9b9675b8fe83/element/:wdc:1436893975606/value timed out after 60 seconds. ---> System.Net.WebException: Timeout dell'operazione.
   in System.Net.HttpWebRequest.GetResponse()
   in OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\HttpCommandExecutor.cs:riga 142
   --- Fine della traccia dello stack dell'eccezione interna ---
   in OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\HttpCommandExecutor.cs:riga 150
   in OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\HttpCommandExecutor.cs:riga 114
   in OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\DriverServiceCommandExecutor.cs:riga 78
   in OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:riga 910
   in OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebDriver.cs:riga 781
   in OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebElement.cs:riga 849
   in OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebElement.cs:riga 303 

If i use FirefoxDriver this code works fine. 
Thanks for help

**Comment by lukeis** [comment]
duplicate issue:
https://github.com/detro/ghostdriver/issues/453
