### ISSUE TITLE
Selenium Node (4.0.0 alpha 3): Rejecting request with host

### ISSUE THREAD

**Issue by kovalev007** [SeleniumHQ/selenium#7821]
## 🐛 Bug Report

selenium-server-4.0.0-alpha-3.jar node - not working on remote machine with chromedriver(chrome) and msedgedriver(edge). But working with geckodriver(firefox).

HUB_IP=192.168.167.1
NODE_IP=192.168.167.3

java -jar selenium-server-4.0.0-alpha-3.jar hub --allow-cors --host HUB_IP --port 9999
java -jar selenium-server-4.0.0-alpha-3.jar node --allow-cors --host NODE_IP --port 8888 --detect-drivers --publish-events tcp://HUB_IP:4442 --subscribe-events tcp://HUB_IP:4443

Error from chromium:
[1574923703.235][SEVERE]: Rejecting request with host: HUB_IP:9999
[1574923703.252][SEVERE]: Rejecting request with host: HUB_IP:9999
[1574923703.266][SEVERE]: Rejecting request with host: HUB_IP:9999
[1574923703.281][SEVERE]: Rejecting request with host: HUB_IP:9999
[1574923703.293][SEVERE]: Rejecting request with host: HUB_IP:9999

Why hub try start/work with browser? Node should work with browser.

**Comment by kovalev007** [comment]
I want use any workaround while this issue not fixed.
May be any way to set "allow_remote_" property in chromium (chrome/edge browser)?
But I can't make it work:

ChromeOptions options = new ChromeOptions();
options.addArguments("--verbose");
options.addArguments("--whitelisted-ips=''");

This not working.

**Comment by shs96c** [comment]
So the remote node doesn't work at all if we're using chrome or edge? I imagine your remote webdriver is configured to use the Hub, right?

**Comment by kovalev007** [comment]
Doesn't work for me. And I think doesn't work in general.

HttpCommandExecutor executor = new HttpCommandExecutor(ImmutableMap.of(), new URL("http://" + HUB_IP + ":9999"), factory);
new RemoteWebDriver(executor, capabilities)

**Comment by kovalev007** [comment]
Info from IRC:
hub and node works on real OS/real machines. Without docker containers.

**Comment by diemol** [comment]
@kovalev007 
Can you please clarify what the issue is? The description and the subsequent comments are not enough to understand what the problem is.

**Comment by kovalev007** [comment]
The problem is that chrome not working with selenium 4.0.0 alpha 3 when we have distributed configuration.

My java test and selenium HUB on one machine.
Selenium NODE on other machine.

java -jar selenium-server-4.0.0-alpha-3.jar hub --allow-cors --host 192.168.56.1 --port 9999
java -jar selenium-server-4.0.0-alpha-3.jar node --allow-cors --host 192.168.56.101 --port 8888 --detect-drivers --publish-events tcp://192.168.56.1:4442 --subscribe-events tcp://192.168.56.1:4443

When I run test - browser opened on NODE, but any first WebDriver command failed.
log from node:
[1576216944.109][SEVERE]: Rejecting request with host: 192.168.56.1:9999
[1576216944.121][SEVERE]: Rejecting request with host: 192.168.56.1:9999
[1576216944.148][SEVERE]: Rejecting request with host: 192.168.56.1:9999
[1576216944.158][SEVERE]: Rejecting request with host: 192.168.56.1:9999
[1576216944.179][SEVERE]: Rejecting request with host: 192.168.56.1:9999

**Comment by kovalev007** [comment]
@shs96c 

I made some investigation on my local distributed environment.

Breakpoint on node
192.168.56.101 - it is HUB ip

![before](https://user-images.githubusercontent.com/12604192/71541877-e6f47a80-2991-11ea-868d-4f59bcfea58a.jpg)

If "Host" header not added to "toUpstream"- then all works for me.

![changes](https://user-images.githubusercontent.com/12604192/71541885-fd9ad180-2991-11ea-8cd5-12390bc71f3a.jpg)

**Comment by kovalev007** [comment]
"Rejecting request with host" from chromedriver:
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/server/chromedriver_server.cc?q=%22Rejecting+request+with+host%22&sq=package:chromium&g=0&l=86

Next steps?

**Comment by diemol** [comment]
Can you please provide the test code you used to get this issue? Are you running any CDP commands?

**Comment by diemol** [comment]
@kovalev007 I checked again and the host header is not [being added](https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/selenium/grid/web/ReverseProxyHandler.java#L39-L49) in the latest alpha 5.
Could you please provide the automated script being used to get this error?

**Comment by kovalev007** [comment]
This problem exist in alpha 5 and in MASTER.

Host header is not being added to **IGNORED_REQ_HEADERS** if I added host header to **IGNORED_REQ_HEADERS** then problem will be fixed.

I not good know selenium code - and solution with **IGNORED_REQ_HEADERS** it is place which I found to fix these problem. May be real fix will be in other place.

I repeat the problem -
...........Rejecting request with host:...................
it is error from chromedriver (and/or new edgedriver on chromium)

Problem exist because HUB "work" with driver. But NODE should "work" with driver.
"work" - the driver sees that the command came from the ip address on which the hub is running

Example of my commands:
seleniumSettings.getWebDriver().manage().window().setSize(new Dimension(1920, 1080));
seleniumSettings.getWebDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
seleniumSettings.getWebDriver().manage().deleteAllCookies();
seleniumSettings.getWebDriver().findElement(By.tagName("html"));


To reproduce the error - you should run HUB and NODE on different machines
java -jar selenium_server_deploy.jar hub --host 192.168.56.1 --port 9999
java -jar selenium_server_deploy.jar node --port 8888 --detect-drivers true --publish-events tcp://192.168.56.1:4442 --subscribe-events tcp://192.168.56.1:4443

**Comment by diemol** [comment]
Ok, so the issue is that the header is **not** present, this was not so clear from the previous comment. 
In any case, we need the complete test case using any given HTML or a public page, so we run it and also are able to fix it.

I cannot personally figure out what is happening by just these 4 lines:
```
seleniumSettings.getWebDriver().manage().window().setSize(new Dimension(1920, 1080));
seleniumSettings.getWebDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
seleniumSettings.getWebDriver().manage().deleteAllCookies();
seleniumSettings.getWebDriver().findElement(By.tagName("html"));
```

So please 🙏, could you please provide the code you used to bump into this issue?

**Comment by kovalev007** [comment]
https://github.com/kovalev007/selenium7821

**Comment by diemol** [comment]
I was able to reproduce the issue, I will have a look soon.

**Comment by diemol** [comment]
This will be released in the next Alpha.

**Comment by dmytrokostiuk** [comment]
Is there a way to monkey patch locally or add the header somewhere?
I'm running into exactly the same problem

**Comment by diemol** [comment]
The next release should happen in the next couple of days.

**Comment by dmytrokostiuk** [comment]
@diemol Thank you for such a quick response.
I'm kind of tight on deadline for my project, really need to unblock this, so was wondering if there is some quick way to temporarily patch it before the next release.

**Comment by evertones** [comment]
I still see the issue in version `4.0.0-alpha-6`. Should it be fixed in this version?

##### The message in LOGs I see on Selenium Grid
```
chrome_1        | [1591118032.838][SEVERE]: Rejecting request with host: myseleniumhub:4444. origin is
```

##### The messages in LOGs I see on the machine that runs the test
```
  - should return some results *** FAILED *** (3 seconds, 66 milliseconds)
    org.openqa.selenium.json.JsonException: Unable to determine type from: H. Last 1 characters read: H
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'everton.local', ip: '192.168.0.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
    at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:127)
    at org.openqa.selenium.json.JsonTypeCoercer.lambda$buildCoercer$6(JsonTypeCoercer.java:140)
    at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
    at org.openqa.selenium.json.Json.toType(Json.java:69)
    at org.openqa.selenium.json.Json.toType(Json.java:55)
    at org.openqa.selenium.json.Json.toType(Json.java:50)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:95)
    at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
```

It happens to me when running tests from one machine against a remote Selenium Grid set up in another machine. I have both the hub and the node running in a remote machine.

I'm using the latest Docker image there is at the moment with `docker-compose`:
- [4.0.0-alpha-5-20200525](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-alpha-5-20200525).

I first start the hub and nodes in one machine with 1 hub and 1 chrome instance: `docker-compose up -d`
Then I run tests from another machine pointing the Selenium Grid started.

If I start Selenium Grid on the same machine where I start tests, it works.

**Comment by simonoff** [comment]
@diemol but it still appears in alpha-6

**Comment by evertones** [comment]
> @diemol but it still appears in alpha-6

It worked well for me with the release of version `4.0.0-alpha-6`.
I think it would be good to have some details about the situation you're facing (config, OS, language, LOGs).

**Comment by simonoff** [comment]
Hello @evertones !
We running everything in Kubernetes. So using current 4.0 docker images. With usage of docker network all working fine. In kubernetes - connection is refused by nodes.
