### ISSUE TITLE
Getting "UnreachableBrowserException" exception when running multiple scripts in parrallel with 4.0.0-alpha-3 java bindings

### ISSUE THREAD

**Issue by okyrylenko** [SeleniumHQ/selenium#7824]
## 🐛 Bug Report

Getting "UnreachableBrowserException" exception when running multiple scripts in parrallel with 4.0.0-alpha-3 java bindings

it works fine when I run scripts individually but failing when in parallel. Also, different scripts failing each time, there is no pattern on how they fail
full exception:
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'
System info: host: 'removed', ip: 'removed', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 77.0.3865.120, chrome: {chromedriverVersion: 77.0.3865.40 

## Test script or set of commands reproducing this issue

download this repo and execute executeAllProd.xml file https://github.com/okyrylenko/JavaTestNGFramework

**Comment by barancev** [comment]
There is no executeAllProd.xml in the linked repository.

**Comment by okyrylenko** [comment]
@barancev  it is located here - /TestNgFrameworkAutomationUI/src/main/resources/runConfigurations/

**Comment by diemol** [comment]
@okyrylenko 
I executed the tests from the provided repo, some of them passed, some failed and some errored, but never got the exception mentioned above.
It is not straightforward to find the problem in the file structure of the project...

Could you please provide a simplified script to reproduce the issue? Something that does not depend on the complex structure of the provided repo. Please also provide clear instructions to execute the tests (for the new script).

**Comment by AutomatedTester** [comment]
Closing as requested info was not given
